>DL;BoLA-DQB*0101
BoLA-DQB*0101, 243 bases, 5597DDA8 checksum.
 TACCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGAACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTTCA ACAGCCAGAA GGACTTCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*0102
BoLA-DQB*0102, 243 bases, C978CA14 checksum.
 TACCAGTTTA TGGGCCAGTG TTATTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGAACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTTCA ACAGCCAGAA GGACTTCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*0103
BoLA-DQB*0103, 243 bases, 46DE8338 checksum.
 TACCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGACACATCT ACAACCAGGA GGAGAACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*0201
BoLA-DQB*0201, 243 bases, 37069731 checksum.
 TACCAGTTTA AGTGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACGTGGG CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGCCCGCC
 GAGCACTGGA ACAGCCAGAA GGACTTCCTG GAGCAGACGC GGGCCGAGGT
 GGACAGCGTG TGCAGACACA ACTACCAACT GGAGCTCATC ACA*

>DL;BoLA-DQB*0301
BoLA-DQB*0301, 243 bases, 1096CAFA checksum.
 TTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GCTCGTGACC AGAAACATAT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGG CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACCTCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGC GAGGCTCATC ACA*

>DL;BoLA-DQB*0302
BoLA-DQB*0302, 243 bases, 171EA559 checksum.
 TTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GCTCGTGACC AGAAACATAT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGG CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACCTCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*0303
BoLA-DQB*0303, 261 bases, E9017542 checksum.
 TGTTCCAGTT TAAGGGCCTG TGTTACTTCA CCAACGGGAC GGAGCGGGTG
 CGGCTCGTGA CCAGAAACAT ATACAACCAG CTGCAGTACG TGCGGTTCGA
 CAGCGACTGG GGCGAGTACC GGGCGCTGAC CCCGCTGGGG CGGCCGGACG
 CCGAGTACTG GAACAGCCAG AAGGACCTCC TGGAGCAGAC GCGGGCCGAG
 GCGGACACGG TGTGCAGACA CAACTACCAG GCGGAGCTCA TCACATCCTT
 GCAGCGGCGA G*

>DL;BoLA-DQB*0401
BoLA-DQB*0401, 243 bases, 28C3A96F checksum.
 GTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGAACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGGTGC GGGCCGAGGT
 GGACAGGGTG TGCAGAAACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*0402
BoLA-DQB*0402, 243 bases, C6FAE377 checksum.
 TACCAGTTTA AGTGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGAACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGGTGC GGGCCGAGGT
 GGACAGGGTG TGCAGAAACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*0403
BoLA-DQB*0403, 243 bases, B3D7B53A checksum.
 TACCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGCCGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGGTGC GGGCCGAGGT
 GGACAGGGTG TGCAGAAACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*0404
BoLA-DQB*0404, 243 bases, 14C764B4 checksum.
 TACCAGTTTA AGTGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGCCGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGGTGC GGGCCGAGGT
 GGACAGGGTG TGCAGAAACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*0405
BoLA-DQB*0405, 271 bases, 35C031A4 checksum.
 AGGAATTTCG TGTACCAGTT TAAGTGCCTG TGTTACTTCA CCAACGGGAC
 GGAGCGGGTG CGGTACGTGA CCTGCAGCAT CTACAACCAG GAGGAGAACG
 TGCGGTTCGA CAGCGACTGG GACGAGTACC GGGCGGTGAC CCCGCTGGGG
 CGGCCGGACG CCGAGTACTG GAACAGCCAG AAGGACATCC TGGAGCGGGT
 GCGGGCCGAG GTGGACAGGG TGTGCAGAAA CAACTACCAG GCGGAGCTCA
 TCACATCCTT GCAGCGGCGA G*

>DL;BoLA-DQB*0501
BoLA-DQB*0501, 243 bases, D8996EC3 checksum.
 TACCAGTATA AGGGCCTGTG TTACTTCACC AACGGGACGC AGCGGGTGCG
 GCTCGTGACC AGATACATCT ACAACCGGGA GGAGTTCGCG CGGTTCGACA
 GCGACGTGAA CGAGTTCCGG GCGGTGACCC CACTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCAGAGGC GGGCCGAGGT
 GGACAGGGTG TGCAGACACA ACTACCAGCT GGATGCCCCC TTC*

>DL;BoLA-DQB*0502
BoLA-DQB*0502, 243 bases, 88685E9B checksum.
 TACCAGTATA AGGGCCTGTG TTACTTCACC AACGGGACGC AGCGGGTGCG
 GCTCGTGACC AGATACATCT ACAACCGGGA GGAGTTCGCG CGGTTCGACA
 GCGACGTGAA CGAGTTCCGG GCGGTGACCC CACTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGACGC GGGCCGAGGT
 GGACAGGGTG TGCAGACACA ACTACCAGGT GGATGCCCCC TTC*

>DL;BoLA-DQB*0601
BoLA-DQB*0601, 240 bases, A2E2D814 checksum.
 TACCAGTTTA TATACCAGTG TTACTTCACC AATGGGACAG AGCGGGTGCG
 GAGTGTGAAA AAACAGATCT ACAACCGGCA AGAACACGTG CGATTCGACA
 GCGACGTGAA CGAGTTCCGG GCGGTTTCCC CGCTGGGGCA GCGGGACGCC
 GAGTACTTCA ATAGCCACGA CTTCCTGAAG CAGACGCGGG CCGAGGTGGA
 CACGGTGTGC AGACACAACT ACCAACTGGA GCTCCTCACA*

>DL;BoLA-DQB*0701
BoLA-DQB*0701, 243 bases, 2F35AA0D checksum.
 GTCCAGTTTC TGGGCCAGTG TTACTTCACC AACGGGACGG AGCGGGTCCG
 GGGTGTGACC AGATACATCT ACAACCGGGA GGAGTACGTG CGCTTCGACA
 GCGACGTGAA CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGTCCGCC
 GAGTACTGGA ACAGCCAGGA GGACATCCTG GAGCGGGTGC GGGCCGAGGT
 GGACACGGTG TGCAGACACA ACTACCAACT GGAGCTCATC ACA*

>DL;BoLA-DQB*0801
BoLA-DQB*0801, 243 bases, 90FD84AC checksum.
 ATCCAGTTTA AGTGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCA
 GTACGTGACC AGACACATCT ACAACCAGGA AGAGTTCATG CGCTTCGACA
 GCGAAGTGGG CGAGTACCGG GCGGTGACTC CGCTAGGGCG GCGGCAAACC
 GAGTACTTCA ACAGCCAGAA GGACGAACTG GAGCGGGTGC GGGCCGAGGC
 GGACACAGTG TGCAGACACA ACTACCAGGC GGAGCTCATT ACA*

>DL;BoLA-DQB*0802
BoLA-DQB*0802, 243 bases, FB8B71F5 checksum.
 TTCCAGTTTA AGTGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCA
 GTACGTGACC AGATACATCT ACAACCAGGA AGAGTTCATG CGCTTCGACA
 GCGAAGTGGG CGAGTACCGG GCGGTGACCC CGCTAGGGCG GCGGCAAACC
 GAGTACTTCA ACAGCCAGAA GGACGAACTG GAGCGGGTGC GGGCCGAGGC
 GGACACAGTG TGCAGACACA ACTACCAGGC GGAGCTCATT ACA*

>DL;BoLA-DQB*0901
BoLA-DQB*0901, 243 bases, 7BD5A157 checksum.
 GTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGAGTGCG
 GCTCGTGGTC AGACACATCT ACAACCGGGA GGAGTACGCG CGGTTTGACA
 GCGACGTGAA CGAGTACCGG GCGGTGACCC CTCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACCTCCTG GAGCAGAGGC GGGCCGAGGT
 GGACAGGGTG TGCAGACACA ACTACCAGGT GGCTGCCCCC TTC*

>DL;BoLA-DQB*0902
BoLA-DQB*0902, 243 bases, 6DF44666 checksum.
 GTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGAGTGCG
 GCTCGTGGTC GGACACATCT ACAACCGGGA GGAGTACGCG CGGTTTGACA
 GCGACGTGAA CGAGTACCGG GCGGTGACCC CTCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACCTCCTG GAGCAGAGGC GGGCCGAGGT
 GGACAGGGTG TGCAGACACA ACTACCAGGT GGCTGCCCCC TTC*

>DL;BoLA-DQB*0903
BoLA-DQB*0903, 240 bases, D7D0B67E checksum.
 GTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGAGTGCG
 GCTCGTGGTC AGACACATCT ACAACCGGGA GGAGTACGCG CGGTTTGACA
 GCGACGTGAA CGAGTACCGG GCGGTGACCT CTGGGGCGCC GCACGCCGAG
 TACTGGAACA GCCAGAAGGA CCTCCTGGAG CAGAGGCGGG CCGAGGTGGA
 CAGGGTGTGC AGACACAACT ACCAGGTGGC TGCCCCCTTC*

>DL;BoLA-DQB*1001
BoLA-DQB*1001, 243 bases, 2141F74F checksum.
 TACCAGTTTA TGGGCCAGTG TTATTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGTACGCG CGCTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGCCGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGACGC GGGCCGAGGT
 GGACAGGGTG TGCAGAAACA ACTACCAGGT GGATGCCCCC TTC*

>DL;BoLA-DQB*10021
BoLA-DQB*10021, 243 bases, E0C6BDE3 checksum.
 TACCAGTTTA TGGGCCAGTG TTATTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGTACGCG CGCTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGCCGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGACGC GGGCCGAGGT
 GGACAGGGTG TGCAGAAACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*1003
BoLA-DQB*1003, 243 bases, 8493266E checksum.
 TACCAGTTTA TGGGCCAGTG TTATTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGTACGCG CGCTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGCCGCC
 GAGTACTGGA ACAGCCAGGA GGACATCCTG GAGCGGACGC GGGCCGAGGT
 GGACAGGGTG TGCAGAAACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*1005
BoLA-DQB*1005, 243 bases, 2BA4E8EF checksum.
 TTCCAGTTTA TGGGCCAGTG TTATTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGTTCGCG CGCTTCGACA
 GCGACTGGGA CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGGACGCC
 GAGCTCTGGA ACAGCCAGAA GGACATCCTG GAGCGGACGC GGGCCGAGGT
 GGACAGGGTG TGCAGAAACA ACTACCAGGT GGATGCCCCC TTC*

>DL;BoLA-DQB*1006
BoLA-DQB*1006, 240 bases, 95D2F5A5 checksum.
 GTCCAGTTTA TGGGCCAGTG TTATTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGTACGCG CGCTTCGACA
 GCGACTGGGG CGAGTACCGG GCGCTGACCC GCTGGCGGCC GGCCGCCGAG
 TACTGGAACA GCCAGAAGGA CATCCTGGAG CAGACGTGGG CCGAGGTGGA
 CAGGGTGTGC AGAAACAACT ACCAGGTGGA AGCCCCCTTC*

>DL;BoLA-DQB*1008
BoLA-DQB*1008, 243 bases, E27CF041 checksum.
 TACCAGTTTA TGGGCCAGTG TTATTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGTACGCG CGCTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGCCGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GGGCGGACGC GGGCCGAGGT
 GGACAGGGTG TGCAGAAACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*1009
BoLA-DQB*1009, 243 bases, EBF469A3 checksum.
 TACCAGTTTA TGGGCCAGTG TTATTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATTCATCT ACAACCAGGA GGAGTACGCG CGCTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGCCGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGACGC GGGCCGAGGT
 GGACACGGTG TGCAGACACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*1101
BoLA-DQB*1101, 243 bases, 17331493 checksum.
 TTCCGGTTTA AGGGCCTGTG TTACTTCACC AACAGGACGG AGCGGGTGCG
 GTACGTGACC AGATACACCT ACAACCAGGA GGAGAACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGTCCGCC
 GAGTACTTCA ACAGCCAGGA GGACCTCCTG GAGCGGACGC GGGCCGAGGT
 GGACAGGGTG TGCAGAAACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*1201
BoLA-DQB*1201, 243 bases, 2C9333C2 checksum.
 TTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GAGTGTGAAC AGATACATCT ACAACCGGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCAGGACGCC
 GAGTACTTCA ACAGCCAGAA GGACTTCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGT GGCTGCCCCC TTC*

>DL;BoLA-DQB*1301
BoLA-DQB*1301, 243 bases, 4E4FB51B checksum.
 TTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GAGTGTGACC AGATACATCT ACAACCGGGA GGAGTACGTG CGGTTCGACA
 GCGACGTGAA CGAGTACCGG GCGGTGACCC CACTGGGGCG GCCGTCCGCC
 GAGTACTTCA ACAGCCAGGA GGACCTCCTG GAGCGGACGC GGGCCGAGGT
 GGACAGGGTG TGCAGACACA ACTACCAGCT GGATGCCCCC TTC*

>DL;BoLA-DQB*1401
BoLA-DQB*1401, 243 bases, EC14031B checksum.
 GTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GAGTGTGAAC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGACGC GGGCCGAGGC
 GGACACGGTG TGCAGAAACA ACTACCAGGT GGATGCCCCC TTC*

>DL;BoLA-DQB*1402
BoLA-DQB*1402, 243 bases, 12E1A4FD checksum.
 TACCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GAGTGTGAAC AGATACATCT ACAACCGGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*1403
BoLA-DQB*1403, 243 bases, 768362B checksum.
 GTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GAGTGTGAAC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTTCA ACAGCCAGAA GGACATCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGAAACA ACTACCAGGT GGATGCCCCC TTC*

>DL;BoLA-DQB*1404
BoLA-DQB*1404, 243 bases, 3AFF4C7D checksum.
 GTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG ATCGGGTGCG
 GAGTGTGAAC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGACGC GGGCCGAGGC
 GGACACGGTG TGCAGAAACA ACTACCAGGT GGATGCCCCC TTC*

>DL;BoLA-DQB*1501
BoLA-DQB*1501, 243 bases, 850D44E1 checksum.
 TACCAGTTTA AGTGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGAACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACCTCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*1601
BoLA-DQB*1601, 243 bases, 141FA159 checksum.
 TACCAGTATA AGGGCCTGTG TTACTTCACC AACGGGACGC AGCGGGTGCG
 GCTCGTGACC AGATACATCT ACAACCGGGA GGAGTACGCG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GTGGTGACCC CACTGGGGCG GCCGGCCGCC
 GAGTACTGGA ACAGCCAGAA GGACCTCCTG GAGCAGACGC GGGCCGAGGT
 GGACAGGGTG TGCAGACACA ACTACCAGGT GGCTGCCCCC TTC*

>DL;BoLA-DQB*1602
BoLA-DQB*1602, 241 bases, 6C4C515B checksum.
 ACCAGTATAA GGGCCTGTGT TACTTCACCA ACGGGACGCA GCGGGTGCGG
 CTCGTGACCA GATACATCTA CAACCGGGAG GAGTACGCGC GGTTCGACAG
 CGACTGGGAC GAGTACCGGG CGGTGACCCC ACTGGGGCGG CCGGCCGCCG
 AGTACTGGAA CAGCCAGAAG GACCTCCTGG AGCAGACGCG GGCCGAGGTG
 GACAGGGTGT GCAGACACAA CTACCAGGTG GCTGCCCCCT T*

>DL;BoLA-DQB*1701
BoLA-DQB*1701, 243 bases, 695B992F checksum.
 GTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GCTCGTGACC AGACACATCT ACAACCGGGA GGAGTACGCG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CACTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCAGAGGC GGGCCGAGGT
 GGACAGGGTG CGCAGACACA ACTACCAGCT GGATGCCCCC TTC*

>DL;BoLA-DQB*1702
BoLA-DQB*1702, 241 bases, ECC2BE91 checksum.
 TCCAGTTTAA GGGCCTGTGT TACTTCACCA ACGGGACGGA GCGGGTGCGG
 CTCGTGACCA GACACATCTA CAACCGGGAG GAGTACGCGC GGTTCGACAG
 CGACTGGGAC GAGTACCGGG CGCTGACCCC ACTGGGGCGG CCGGACGCCG
 AGTACTGGAA CAGCCAGAAG GACATCCTGG AGCAGAGGCG GGCCGAGGTG
 GACAGGGTGT GCAGACACAA CTACCAGCTG GATGCCCCCT T*

>DL;BoLA-DQB*1801
BoLA-DQB*1801, 243 bases, 3CB6FBD7 checksum.
 CTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GAGTGTGAAC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGCCGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*1802
BoLA-DQB*1802, 243 bases, 48D4204F checksum.
 GTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GCACGTGACC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CTTGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*1803
BoLA-DQB*1803, 241 bases, 97A0A726 checksum.
 TCCAGTTTAA GGGCCTGTGT TACTTCACCA ACGGGACGGA GCGGGTGCGG
 TACGTGACCA GATACATCTA CAACCAGGAG GAGTACGTGC GGTTCGACAG
 CGACTGGGAC TTGTACCGGG CGCTGACCCC GCTGGGGCGG CCGGACGCCG
 AGTACTGGAA CAGCCAGAAG GACATCCTGG AGCAGACGCG GGCCGAGGCG
 GACACGGTGT GCAGACACAA CTACCAGGCG GAGCTCATCA C*

>DL;BoLA-DQB*1804
BoLA-DQB*1804, 243 bases, 292A2526 checksum.
 TACCAGTTTA AGTGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CTTGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGTCAGAA GGACATCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*1805
BoLA-DQB*1805, 243 bases, E93DD179 checksum.
 CTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GAGTGTGAAC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*1806
BoLA-DQB*1806, 243 bases, 74E93D7F checksum.
 TACCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGCCGCC
 GAGCTCTGGA ACAGCCAGAA GGACATCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*1901
BoLA-DQB*1901, 242 bases, C3BA198A checksum.
 TCCAGTTTAA GGGCCTGTGT TACTTCACCA ACGGGACGGA GCGGGTCCGG
 GGTGTGACCA GATACATCTA CAACCAGGAG GAGTACGTGC GGTTCGACAG
 CGACTGGGAC GAGTACCGGG CGCTGACCCC GCTGGGGCGG CCGGAAGCCG
 AGTACTGGAA CAGCCAGAAG GACTTCCTGG AGCAGACGCG GGCCGCGGTG
 GACACGGTGT GCAGAAACAA CTACCAGGCG GAGCTCATCA CA*

>DL;BoLA-DQB*1902
BoLA-DQB*1902, 243 bases, 7EA1D350 checksum.
 GTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTCCG
 GGGTGTGACC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGACCGCC
 GAGTACTTCA ACAGCCAGAA GGACATCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*2001
BoLA-DQB*2001, 243 bases, CE826610 checksum.
 GTCCACTTTA TGGGCCAGTG TTACTTCACT AATGGCACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGACCGCA TACTATGACA
 GTGACGTGGG AGAGTACCGG GCTGTGACCC AACTAGGGCG GACTTTGGCT
 GAGTATTGGA ACAGCCAGAA AGATATCCTG GAGCAGACAC GGGCGGAGCT
 GGACACGGTG TGCAGACACA ATTACCAGCT GGAGGTCATC ACG*

>DL;BoLA-DQB*2101
BoLA-DQB*2101, 243 bases, D4D643A4 checksum.
 TTTCTGTTTA TGGGCCAGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GCTCGTGACC AGATACATCT ACAACCAGGA GGAGTACGTG CGCTTCGACA
 GCGACTGGGG CGAGTACCGG GCGGTGACGC CGCCGGGGCA GCGGCAAGCC
 GAGTACTTCA ACAGCCAGAA GGACTTCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGT GGAAGCCGCC TTC*

>DL;BoLA-DQB*2201
BoLA-DQB*2201, 243 bases, 6926CF94 checksum.
 ATCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTCCG
 GGGTGTGACC AGATACATCT ACAACCAGGA AGAGTTCATG CGCTTCGACA
 GCGAGGTGGG CGAGTACCGG GCGGTGACTC CGCTAGGGCG GCGGCTAACC
 GAGTACTTCA ACAGCCAGAA GGACGAACTG GAGCGGGTGC GGGCCGAGGC
 GGACACAGTG TGCAGACACA ACTACCAGGC GGAGCTCATT ACA*

>DL;BoLA-DQB*2301
BoLA-DQB*2301, 243 bases, 56F030BA checksum.
 GTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GCTCGTGACC AGATACATAT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CGGGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTTCA ACAGCCAGAA GGACATCCTG GAGCGGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*2401
BoLA-DQB*2401, 243 bases, 1D74D5E3 checksum.
 CTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGA AGCGGGTGCG
 GCTCGTGACC AGACACATCT ACAACCAGGA AGAGTTCATG CGCTTCGACA
 GCGACGTGGG CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCGGCAAACC
 GAGTACTTCA ACAGCCAGAA GGACGAACTG GAGCGGGTGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*2501
BoLA-DQB*2501, 243 bases, 45BA0E05 checksum.
 TACCAGTTTA AGGGCCTGTG TTATTTCACC AACGGGACGG AGCGGGTGCG
 GCTCGTGACC AGATACATAT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACGTGGG CGAACACCGG GCGGTGACCC CGCTGGGGCG GCCGGCCGCC
 GAGCACTGGA ACAGCCAGAA GGACCTCCTG GAGCAGAGGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*2502
BoLA-DQB*2502, 243 bases, 7C25ABB2 checksum.
 TACCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG ATAGGGTGCG
 GCTCGTGACC AGACACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACGTGGG CGAACACCGG GCGCTGACCC CGCTGGGGCG GCCGGCCGCC
 GAGTACTGGA ACAGCCAGAA GGACCTCCTG GAGCAGAGGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*2601
BoLA-DQB*2601, 243 bases, 85AB056F checksum.
 TACCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG ATAGGGTGCG
 GCTCGTGGCC AGATACATCT ACAACCAGGA GGAGAACGTG CGGTTCGACA
 GCGACTGGGG CGAACACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCAGAGGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*2701
BoLA-DQB*2701, 243 bases, 5140FD4B checksum.
 TACCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GCACGTGACC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGGCCGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGACGC GGGCCGAGGC
 GGACACGGTG TGCAGAAACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*2702
BoLA-DQB*2702, 243 bases, 98E110E6 checksum.
 TACCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GGGCGTGACC AGACACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGCCGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGACGC GGGCCGAGGC
 GGACACGGTG TGCAGAAACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*2801
BoLA-DQB*2801, 243 bases, C87E772C checksum.
 TACCAGTTTA TGGGCCAGTG TTATTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCGGGA GGAGTTCGCG CGGTTCGACA
 GCGACGTGAA CGAGTTCCGG GCGGTGACCC CACTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACCTCCTG GAGGGGACGC GGGCCGAGGT
 GGACAGGGTG TGCAGACACA ACTACCAGGT GTATGCCCCC TTC*

>DL;BoLA-DQB*2901
BoLA-DQB*2901, 243 bases, A5558BDB checksum.
 TTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GCTCGTGACC AGATACATCT ACAACCGGGA GGAGTACGCG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CACTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCAGACGC GGGCCGAGGT
 GGACAGGGTG TGCAGACACA ACTACCAGGT GTATGCCCCC TTC*

>DL;BoLA-DQB*3001
BoLA-DQB*3001, 243 bases, B02F68D7 checksum.
 TACCAGTTTG TAGGCCAGTG TTACTTTAAC AATGGGACAG AGCGGGTGCG
 GAGTGTGAAA AAACAGATCT ACAACCGGGC GGAGCACGTG CGATTCGACA
 GCGACGTGAA CGAGTTCCGG GCGGTTTCCC CGCTGGGGCA GCAAGACGCC
 GAGTACTTCA ACAGCCAGAA GGACATCCTG GAGCGGGCGC GGGCCGAGGT
 GGACGCGGTA TGCAGACACA ACTACCAACT GGAGCTCCGC ACA*

>DL;BoLA-DQB*3101
BoLA-DQB*3101, 243 bases, 93984443 checksum.
 TACCAGTATA AGGGCCTGTG TTACTTCACC AACGGGACGC AGCGGGTGCG
 GCTCGTGACC AGATACATCT ACAACCGGGA GGAGTTCGCG CGGTTCGACA
 GCGACGTGAA CGAGTTCCGG GCGGTGACCC CACTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACCTCCTG GAGGGGACGC GGGCCGAGGT
 GGACAGGGTG TGCAGATACA ACTACCAGGT GTATGCCCCC TTC*

>DL;BoLA-DQB*3201
BoLA-DQB*3201, 243 bases, F636C41F checksum.
 GTCCAGTTTA AGTTCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CTTGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGGTGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*3301
BoLA-DQB*3301, 243 bases, F476BA58 checksum.
 TACCAGTTTA AGTGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGAACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*3302
BoLA-DQB*3302, 243 bases, B91CED4B checksum.
 TACCAGTTTA AGTGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGAACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTTCA ACAGCCAGAA GGACTTCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*3401
BoLA-DQB*3401, 243 bases, 62DE5AD6 checksum.
 TACCAGTTTA TGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGTACGTG CGATTCGACA
 GCGACTGGGA CGGGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGGTGC GGGCCGAGGT
 GGACACGGTG TGCAGAAACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*3501
BoLA-DQB*3501, 243 bases, 39E1E5CF checksum.
 TACCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTCCG
 GGGTGTGACC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGG CGAACACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTTCA ACAGCCAGAA GGACTTCCTG GAGCAGACGC GGGCCGCGGT
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*3601
BoLA-DQB*3601, 243 bases, 42556332 checksum.
 TACCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTCCG
 GGGTGTGACC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGG CGAACACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTTCA ACAGCCAGAA GGACCTCCTG GAGCAGACGC GGGCCGCGGT
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*3701
BoLA-DQB*3701, 243 bases, 411E1F0B checksum.
 TACCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTCCG
 GGGTGTGGCC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGG CGAACACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTTCA ACAGCCAGAA GGACTTCCTG GAGCAGACGC GGGCCGCGGT
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*3801
BoLA-DQB*3801, 243 bases, 2FE32568 checksum.
 CTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGA AGCGGGTGCG
 GCTCGTGACC AGACACATCT ACAACCAGGA AGAGTTCATG CGCTTCGACA
 GCGACGTGGG CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCGGCAAACC
 GAGTACTTCA ACAGCCAGAA GGACGAACTG GAGCGGGTGC GGGCCGAGGC
 GGACACAGTG TGCAGACACA ACTACCAGGC GGAGCTCATT ACA*

>DL;BoLA-DQB*3901
BoLA-DQB*3901, 261 bases, FD87485D checksum.
 TGTACCAGTT TAAGTGCCTG TGTTACTTCA CCAACGGGAC GGAGCGGGTG
 CGGTACGTGA CCAGTTACAT CTGCAGCCAG GAGGAGATCG TGCGGTTCGA
 CAGCGACTGG GACGAGTACC GGGCGGTGAC CCCGCTGGGG CGGCCGGACG
 CCGAGTACTG GAACAGCCAG AAGGACATGC TGGAGCGGGT GCGGGCCGAG
 GTGGACAGGG TGTGCAGAAA CAACTACCAG GCGGCGCTCA TCACATCCTT
 GCAGCGGCGA G*

>DL;BoLA-DQB*4001
BoLA-DQB*4001, 261 bases, 1E0A5796 checksum.
 TGTACCAGTT TATGGGCCAG TGTTATTTCA CCAACGGGCT GCAGCGGGTG
 CGGTACGTGA CCAGATACAT CTACAACCAG GAGGAGTACG CGCGCTTCGA
 CAGCGACTGG GACGAGTACC GGGCGCTGAC CCCGCTGGGG CGGCCGGCCG
 CCGAGTACTG GAACAGCCAG AAGGACATCC TGCAGCGGAC GCGGGCCGAG
 GTGGACAGGG TGTGCAGAAA CAACTACCAG GTGGAAGCCC CCTTCACCTG
 GCAGCGGCGA G*

