>DL;BoLA-DRB3*0101
BoLA-DRB3*0101, 597 bases, DF29178 checksum.
 CATTTCCTGG AGTATTCTAA GAGCGAGTGT CATTTCTTCA ACGGGACCGA
 GCGGGTGCGG TTCCTGGACA GATACTACAC TAATGGAGAA GAGACCGTGC
 GCTTCGACAG CGACTGGGGC GAGTTCCGGG CGGTGACCGA GCTGGGGCGG
 CAGGACGCCG AGTACTGGAA CAGCCAGAAG GACTTCCTGG AGGAGAAGCG
 GGCCGAGGTG GACAGGGTGT GCAGACACAA CTACGGGGGT ATGGAGAGTT
 TCACTGTGCA GCGGCGAGTG GAGCCTACAG TGACTGTGTA TCCTGCAAAG
 ACTCAGCCCC TGCAGCACCA CAACCTCCTG GTCTGCTCTG TGAACGGTTT
 CTACCCAGGC CACATTGAAG TCAGGTGGTT CCGGAACGCC CATGAAGAGG
 AGGCTGTGGA TCACCCCAGC CGGACGAGCC CTATCACAGT AGAATGGAGG
 GCACGGTCTG ACTCTGCTCA GAGCAAGATG ATGAGTGGAG TCGGGGGCTT
 CGTTCTGGGT CTGCTCTTCC TTGCCGTGGG GCTCTTCATC TACTTCAGGA
 ATCAGAAAGG ACGCCCTACA CTTCAGCCAA CAGGGCTCCT GAGCTGA*

>DL;BoLA-DRB3*0201
BoLA-DRB3*0201, 247 bases, 5FBBFD68 checksum.
 GGAGTATTCT ACGAGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTGGA CAGATACTTC CATAATGGAG AAGAGTTCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTACCG GGCGGTGACC GAGCTAGGGC GGCCGGACGC
 CGAGTACTGG AACAGCCAGG AGATCCTGGA GCGGGCGCGG GCCGCGGTGG
 ACACGTACTG CAGACACAAC TACGGGGGCG TGGAGAGTTT CACTGTG*

>DL;BoLA-DRB3*0301
BoLA-DRB3*0301, 260 bases, B4F40037 checksum.
 GGAGTATTGT AAGAGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTGGA GAGATCCTTC TATAATGGAG AAGAGTTCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTACCG GGCGGTGACC GAGCTAGGGC GGCCGGACGC
 CAAGTACTGG AACAGCCAGA AGGACTTGCT GGAGCAGAAG CGGGCCAATG
 TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG TTTCACTGTG
 CAGCGGCGAG*

>DL;BoLA-DRB3*03021
BoLA-DRB3*03021, 250 bases, 56F6E982 checksum.
 GGAGTATTGT AAGAGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTGGA GAGATCCTTC TATAATGGAG AAGAGTTCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTACCG GGCGGTGACC GAGCTAGGGC GGCCGGACGC
 CAAGTACTGG AACAGCCAGA AGGACTTGCT GGAGCAGAAG CGGGCCAATG
 TGGACACGTA CTGCAGACAC AACTACGGGG TCGTGGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*03022
BoLA-DRB3*03022, 236 bases, B8B28760 checksum.
 TGGAGTATTG TAAGAGCGAG TGTCATTTCT TCAACGGGAC CGAGCGGGTG
 CGGTTCCTGG AGAGATCCTT CTATAATGGA GAAGAGTTCG TGCGCTTCGA
 CAGCGACTGG GGCGAGTACC GGGCGGTGAC CGAGCTAGGG CGGCCGGACG
 CCAAGTACTG GAACAGCCAG AAGGACTTGC TGGAGCAGAA GCGGGCCAAT
 GTTGACACGT ACTGCAGACA CAACTACGGG GTCGTG*

>DL;BoLA-DRB3*0303
BoLA-DRB3*0303, 249 bases, 77D5D0A4 checksum.
 GAGTATTGTA AGAGCGAGTG TCATTTCTTC GACGGGACCG AGCGGGTGCG
 GTTCCTGGAG AGATCCTTCT ATAATGGAGA AGAGTTCGTG CGCTTCGACA
 GCGACTGGGG CGAGTACCGG GCGGTGACCG AGCTAGGGCG GCCGGACGCC
 AAGTTATGGA ACAGCCAGAA AGACTTGCTG GAGCAGAAGC GGGCCAATGT
 GGACACGTAC TGCAGACACA ACTACGGGGT CGTGGAGAGT TTCACTGTG*

>DL;BoLA-DRB3*0401
BoLA-DRB3*0401, 250 bases, CFABED64 checksum.
 GGAGTATTCT ACGAGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTGGA CAGATACTTC TATAATGGAG AAGAGTACGT GCGCTTCGAC
 AGCGACTGGG GCGAGTTCCA GGCGGTGACC GAGCTGGGGC GGCCGGACGC
 CAAGTACTGG AACAGCCAGA AGGACATCCT GGAGCGGGAG CGGGCCGCGG
 TGGACACGTA CTGCAGACAC AACTACGGGG GCGTGGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*0501
BoLA-DRB3*0501, 260 bases, A897A147 checksum.
 GGAGTATCAT AAGAGTGAGT GTCATTTCTT CAACGGGACC GAGCGTTTGC
 GGTACCTGGA CAGATACTTC TATAATGGAG AAGAGTACGT GCGCTTCGAC
 AGCGACTGGG GCGAGTACCG GGCGGTGACC GAGCTGGGGC GGCCGGACGC
 CAAGTACTGG AACAGCCAGA AGGAGATCCT GGAGCGGAAG CGGGCCAATG
 TGGACACGTA CTGCAGACAC AACTACGGGG TCGTTGAGAG TTTCACTGTG
 CAGCGGCGAG*

>DL;BoLA-DRB3*0502
BoLA-DRB3*0502, 250 bases, 9FBCA42F checksum.
 GGAGTATCAT AAGAGCGAGT GTCATTTCTT CAACGGGACC GAGCGTTTGC
 GGTACCTGGA CAGATACTTC TATAATGGAG AAGAGTACGT GCGCTTCGAC
 AGCGACTGGG GCGAGTACCG GGCGGTGACC GAGCTGGGGC GGCCGGACGC
 CAAGTACTGG AACAGCCAGA AGGACTTGCT GGAGCGGAAG CGGGCCAATG
 TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*0503
BoLA-DRB3*0503, 250 bases, 5255659D checksum.
 GGAGTATTCT AAGAGCGAGT GTCATTTCTT CAACGGGACC GAGCGTTTGC
 GGTACCTGGA CAGATACTTC TATAATGGAG AAGAGTACGT GCGCTTCGAC
 AGCGACTGGG GCGAGTACCG GGCGGTGACC GAGCTGGGGC GGCCGGACGC
 CAAGTACTGG AACAGCCAGA AGGAGATCCT GGAGCGGAAG CGGGCCAATG
 TGGACACGTA CTGCAGACAC AACTACGGGG TCTTTGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*0504
BoLA-DRB3*0504, 229 bases, DD8F975C checksum.
 ATAAGAGTGA GTGTCATTTC TTCAACGGGA CCGAGCGTTT GCGGTACCTG
 GACAGATACT TCTATAATGG AGAAGAGTAC GTGCGCTTCG ACAGCGACTG
 GGGCGAGTAC CGGGCGGTGA CCGAGCTGGG GCGGCCGGAC GCCAAGTACT
 GGAACAGCCA GAAGGAGATC CTGGAGCGGA AGCGGGCCAA TGTGGACACG
 TACTGCAGAC ACAACTACGG GGTCTTTGA*

>DL;BoLA-DRB3*0601
BoLA-DRB3*0601, 250 bases, 666DB063 checksum.
 GGAGTATTGT AAGAGAGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTGCTGGA CAGATGCTTC CATAATGGAG AAGAGTTCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTTCCG GGCGGTGACC GAGCTGGGGC GGCGGGTCGC
 CGAGCACTTG AACAGCCAGA AGGAGATCCT GGAGCGGAAG CGGGCCGAGG
 TGGACACGGT GTGCAGACAC AACTACGGGG TTGGTGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*0701
BoLA-DRB3*0701, 250 bases, D1471337 checksum.
 GGAGTATTGT AAGAGAGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTGGA CAGATGCTTC CATAATGGAG AAGAGTTCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTTCCG GGCGGTGACC GAGCTAGGGC GGCGCGTCGC
 CGAGCAGTGG AACAGCCAGA AGGACTTCCT GGAGGAGAGG CGGGCCGAGG
 TGGACAGGGT GTGCAGACAC AACTACGGGG TCGTGGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*0702
BoLA-DRB3*0702, 236 bases, 86E59D13 checksum.
 TGGAGTATTG TAAGAGAGAG TGTCATTTCT TCAACGGGAC CGAGCGGGTG
 CGGTTCCTGG ACAGATGCTT CCATAATGGA GAAGAGTTCG TGCGCTTCGA
 CAGCGACTGG GGCGAGTTCC GGGCGGTGAC CGAGCTAGGG TGGCGCGACG
 CCGAGCAGTG GAACAGCCAG AAGGACTTCC TGGAGGAGAG GCGGGCCGAG
 GTGGACAGGG TGTGCAGACA CAACTACGGG GTCGTG*

>DL;BoLA-DRB3*0703
BoLA-DRB3*0703, 236 bases, C13EE46A checksum.
 TGGAGTATTC TAAGAGCGAG TGTCATTTCT TCAACGGGAC CGAGCGGGTG
 CGGTTGCTGG ACAGATGCTT CCATAATGGA GAAGAGTTCG TGCGCTTCGA
 CAGCGACTGG GGCGAGTTCC AGGCGGTGAC CGAGCTAGGG CGGCGCGTCG
 CCGAGCAGTG GAACAGCCAG AAGGACTTCC TGGAGGAGAG GCGGGCCGAG
 GTGGACAGGG TGTGCAGACA CAACTACGGG GTCGTG*

>DL;BoLA-DRB3*0801
BoLA-DRB3*0801, 250 bases, E61B1687 checksum.
 GGAGTATGCT ACGAGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTGGA CAGATACTTC CATAATGGAG AAGAGCTCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTTCCG GGCGGTGACC GAGCTGGGGC GGCCGTCCGC
 CGTGCACTTG AACAGCCAGA AGGACTTCCT GGAGGACGAG CGGGCTTCGG
 TGGACACGTA CTGCAGACAC AACTACGGGG TCGTTGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*0901
BoLA-DRB3*0901, 250 bases, D451A9B checksum.
 GGAGTATTCT AAGAGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTGGA GAGATCCTTC TATAATGGAG AAGAGAACGT GCGCTTCGAC
 AGCGACTGGG GCGAGTACCG GGCGGTGACC GAGCTAGGGC GGCCGGACGC
 CGAGTACTGG AACAGCCAGA AGGAGATCCT GGAGCGGAAG CGGGCCAATG
 TGGACAGGGT GTGCAGACAC AACTACGGGG TCGGTGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*0902
BoLA-DRB3*0902, 260 bases, 410F58FB checksum.
 GGAGTATTCT AAGAGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTGGA GAGATCCTTC TATAATGGAG AAGAGAACGT GCGCTTCGAC
 AGCGACTGGG GCGAGTACCG GGCGGTGACC GAGCTAGGGC GGCCGGACGC
 CGAGTACTGG AACAGCCAGA AGGAGATCCT GGAGGAGAGG CGGGCCGAGG
 TGGACAGGGT GTGCAGACAC AACTACGGGG TCGGTGAGAG TTTCACTGTG
 CAGCGGCGAG*

>DL;BoLA-DRB3*1001
BoLA-DRB3*1001, 250 bases, 992D3794 checksum.
 GGAGTATTCT AAGAGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTGGA CAGATACTTC CATAATGGAG AAGAGTACGT GCGCTTCGAC
 AGCGACTGGG GCGAGTACCG GGCGGTGACC GAGCTGGGGC AGCGGGTCGC
 CGAGTACTGC AACAGCCAGA AGGACTTCCT GGAGCGGGCG CGGGCCGCGG
 TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*1002
BoLA-DRB3*1002, 250 bases, 39D62A6B checksum.
 GGAGTATTAT AAGAGAGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTGGA CAGATACTTC CATAATGGAG AAGAGTACGT GCGCTTCGAC
 AGCGACTGGG GCGAGTACCG GGCGGTGACC GAGCTGGGGC AGCGGGTCGC
 CGAGTACTGC AACAGCCAGA AGGACTTCCT GGAGCGGGCG CGGGCCGCGG
 TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*1101
BoLA-DRB3*1101, 250 bases, E51E32E1 checksum.
 GCAGTATCAT AAGGGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTGCTGGA CAGACACTTC TATAATGGAG AAGAGTACGT GCGCTTCGAC
 AGCGACTGGG ACGAGTTCCG GGCGGTGACC GAGCTGGGGC GGCCGTCCGC
 CGAGTACTGG AACAGCCAGA AGGACTTCCT GGAGCGGAGG CGGGCCGAGG
 TGGACACGGT GTGCAGACAC AACTACGGGG TCGTGGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*1103
BoLA-DRB3*1103, 249 bases, 8F4F149A checksum.
 GAGTATTATA AGGGCGAGTG TCATTTCTTC AACGGGACCG AGCGGGTGCG
 GTTGCTGGAC AGACACTTCT ATAATGGAGA AGAGTACGTG CGCTTCGACA
 GCGACTGGGG CGAGTTCCGG GCGGTGACCG AGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACTTCCTG GAGCGGAAGC GGGCCGAGGT
 GGACACGGTG TGCAGACACA ACTACGGGGT CGTGGAGAGT TTCACTGTG*

>DL;BoLA-DRB3*1201
BoLA-DRB3*1201, 260 bases, 6769ACBD checksum.
 GGAGTATACC AAGAAAGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTGAA CAGATACTTC CATAATGGAG AAGAGTTCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTACCG GGCGGTGACC GAGCTAGGGC GGCCGGACGC
 CGAGTACTGG AACAGCCAGA AGGAGATCCT GGAGCGGGCG CGGGCCGCGG
 TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG TTTCACTGTG
 CAGCGGCGAG*

>DL;BoLA-DRB3*1202
BoLA-DRB3*1202, 237 bases, 5124A3D8 checksum.
 GGAGTATACC AAGAAAGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTGAA CAGATACTTC CATAATGGAG AAGAGTTCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTACCG GGCGGTGACC GAGCTAGGGC GGCCGGACGC
 CGAGTACTGG AACAGCCAGA AGGAGATCCT GGAGCGGGGG CGGGCCGCGG
 TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGA*

>DL;BoLA-DRB3*1301
BoLA-DRB3*1301, 260 bases, 9FA1941E checksum.
 GGAGTATCTT AAGAGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTGGA GAGATACTTC TATAATGGAG AAGAGTACGT GCGCTTCGAC
 AGCGACTGGG GCGAGTACCG GGCGGTGACC GAGCTAGGGC GGCCGGACGC
 CAAGTACTGG AACAGCCAGA AGGACTTGCT GGAGCGGAAG CGGGCCAATG
 TGGACACGTA CTGCAGACAC AACTACGGGG TCGTGGAGAG TTTCACTGTG
 CAGTGGCGAG*

>DL;BoLA-DRB3*1302
BoLA-DRB3*1302, 229 bases, E424D9A3 checksum.
 TTAAGAGCGA GTGTCATTTC TTCAACGGGA CCGAGCGGGT GCGGTTCCTG
 GAGAGATCCT TCTATAATGG AGAAGAGAAC GTGCGCTTCG ACAGCGACTG
 GGGCGAGTAC CGGGCGGTGA CCGAGCTAGG GCGGCCGGAC GCCAAGTACT
 GGAACAGCCA GAAGGACTTG CTGGAGCGGA AGCGGGCCAA TGTGGACACG
 TACTGCAGAC ACAACTACGG GGTCGTGGA*

>DL;BoLA-DRB3*14011
BoLA-DRB3*14011, 260 bases, 3D4EEDB5 checksum.
 GCAGTATCAT AAGGGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTGCTGGA CAGACACTTC TATAATGGAG AAGAGTTCGT GCGCTTCGAC
 AGCGACTGGG ACGAGTTCCG GGCGGTGACC GAGCTGGGGC GGCCGGCCGC
 CGAGCAGTGG AACAGCCAGA AGGACTTCCT GGAGCAGAAG CGGGCCGAGG
 TGGACAGGGT GTGCAGACAC AACTACGGGG GTGTGGAGAG TTTCACTGTG
 CAGCGGCGAG*

>DL;BoLA-DRB3*14012
BoLA-DRB3*14012, 249 bases, 4CCAFB4B checksum.
 CAGTATCATA AGGGCGAGTG TCATTTCTTC AACGGGACCG AGCGGGTGCG
 GTTGCTGGAC AGACACTTCT ATAATGGAGA AGAGTTCGTG CGCTTCGACA
 GCGACTGGGA CGAGTTCCGG GCGGTGACCG AGCTGGGGCG GCCGGCCGCC
 GAGCAGTGGA ACAGCCAGAA GGACTTCCTT GAGCAGAAGC GGGCCGAGGT
 GGACAGGGTG TGCAGACACA ACTACGGGGG TGTGGAGAGT TTCACTGTG*

>DL;BoLA-DRB3*1402
BoLA-DRB3*1402, 236 bases, 301CEC2A checksum.
 TGGAGTATCT TAAGAGCGAG TGTCATTTCT TCAACGGGAC CGAGCGGGTG
 CGGTTGCTGG ACAGACACTT CTATAATGGA GAAGAGTTCG TGCGCTTCGA
 CAGCGACTGG GACGAGTTCC GGGCGGTGAC CGAGCTGGGG CGGCCGGCCG
 CCGAGCAGTG GAACAGCCAG AAGGACTTCC TGGAGCAGAA GCGGGCCGAG
 GTGGACAGGG TGTGCAGACA CAACTACGGG GGTGTG*

>DL;BoLA-DRB3*1501
BoLA-DRB3*1501, 250 bases, 4B73BAA8 checksum.
 GGAGTATTCT ACGAGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTACCTGGA CAGATACTTC CATAATGGAG AAGAGTTCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTACCG GGCGGTGACC GAGCTAGGGC GGCGGGTCGC
 CGAGCAGTTG AACGGCCAGA AGGACACCCT GGAGCGGGAG CGGGCCTATG
 TGGACACGTA CTGCAGACAC AACTACGGGG TCGTTGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*1502
BoLA-DRB3*1502, 237 bases, 43671DA checksum.
 GGAGTATTCT ACGAGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTACCTGGA CAGATACTTC CATAATGGAG AAGAGTTCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTACCG GGCGGTGACC GAGCTAGGGC GGCGGTCCGC
 CGAGCAGTTG AACGGCCAGA AGGACACCCT GGAGCGGGAG CGGGCCTATG
 TGGACACGTA CTGCAGACAC AACTACGGGG TCGTTGA*

>DL;BoLA-DRB3*1503
BoLA-DRB3*1503, 236 bases, 739C14E8 checksum.
 TGGAGTATTC TACGAGCGAG TGTCATTTCT TCAACGGGAC CGAGCGGGTG
 CGGTTGCTGG ACAGATACTT CTATAATGGA GAAGAGTTCG TGCGCTTCGA
 CAGCGACTGG GGCGAGTACC GGGCGGTGAC CGAGCTAGGG CGGCGGGTCG
 CCGAGCAGCT GAACGGCCAG AAGGACACCC TGGAGCGGGA GCGGGCCTAT
 GTGGACACGT ACTGCAGACA CAACTACGGG GTCGTT*

>DL;BoLA-DRB3*1601
BoLA-DRB3*1601, 654 bases, 34C4E460 checksum.
 ATGGTGTGCC TGTATTTCTC TGGAGGCTCC TGGATGGCAG CTCTGATAGT
 GATGCTGATG GTGCTGTGCC CTCCCCTGGC CTGGGCCAGG GAGATCCAAC
 CACATTTCCT GGAGTATACC AAGAAAGAGT GTCATTTCTT CAACGGGACC
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC CATAATGGAG AAGAGTTCGT
 GCGCTTCGAT AGCGACTGGG GCGAGTACCG GGCGGTGACC GAGCTAGGGC
 GGCCGGACGC CAAGTACTGG AACAGCCAGA AGGACTTCCT GGAGGAGAAG
 CGGGCCGCGG TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG
 TTTCACTGTG CAGCCCCTGC AGCACCACAA CCTCCTGGTC TGCTCTGTGA
 ACGGTTTCTA CCCAGGCAAC ATTGAAGTCA GGTGGTTCCG GAATGGCCAT
 GAAGAGGAGG CTGTGGATCA CCCCAGCCGG ACGAGCCCTA TCACAGTAGA
 ATGGAGGGCA CGGTCTGACT CTGCTCAGAG CAAGATGATG AGTGGAGTCG
 GGGGCTTCGT TCTGGGTCTG CTCTTCCTTG ACGTAGGGCT CTTCATCTAC
 TTCAGGAATC AGAAAGGACG CCCTACACTT CAGCCAACAG GGCTCCTGAG
 CTGA*

>DL;BoLA-DRB3*1602
BoLA-DRB3*1602, 249 bases, 84599214 checksum.
 GAGTATACCA AGAAAGAGTG TCATTTCTTC AACGGGACCG AGCGGGTGCG
 GTTCCTGGAC AGATACTTCC ATAATGGAGA AGAGTTCGTG CGCTTCGACA
 GCGACTGGGG CGAGTACCGG GCGGTGACCG AGCTAGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACTTGCTG GAGCGGAAGC GGGCCAATGT
 GGACACGTAC TGCAGACACA ACTACGGGGT CGGTGAGAGT TTCACTGTG*

>DL;BoLA-DRB3*1701
BoLA-DRB3*1701, 250 bases, 3BBD0D04 checksum.
 GGAGTATGCT ACGAGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTGCA CAGATACTTC TATAATGGAG AAGAGTACGC GCGCTTCGAC
 AGCGACTGGG GCGAGTTCCG GGCGGTGACC GAGCTGGGGC GGCCGGACGC
 CAAGTACTGG AACAGCCAGA AGGAGATCCT GGAGCGGGAG CGGGCCTATG
 TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*1702
BoLA-DRB3*1702, 250 bases, 2965D531 checksum.
 GGAGTATGCT ACGAGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTGCA CAGATACTTC TATAATGGAG AAGAGTACGC GCGCTTCGAC
 AGCGACTGGG GCGAGTTCTG GGCGGTGACC GAGCTGGGGC GGCCGGACGC
 CAAGTACTGG AACAGCCAGA AGGAGATCCT GGAGCGGGAG CGGGCCTATG
 TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*1703
BoLA-DRB3*1703, 249 bases, 7C0CC2EB checksum.
 GAGTATTCTA CGGGCGAGTG TCATTTCTTC AACGGGACCG AGCGGGTGCG
 GTACCTGGAC AGATACTTCT ATAATGGAGA AGAGTACGCG CGCTTCGACA
 GCGACTGGGG CGAGTTCCGG GCGGTGACCG AGCTGGGGCG GCCGGACGCC
 AAGTACTGGA ACAGCCAGAA GGAGATCCTG GAGCGGGAGC GGGCCTATGT
 GGACACGTAC TGCAGACACA ACTACGGGGT CGGTGAGAGT TTCACTGTG*

>DL;BoLA-DRB3*1801
BoLA-DRB3*1801, 260 bases, 6B4A1574 checksum.
 GGAGTATGCT ACGAGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTGCA CAGATACTTC CATAATGGAG AAGAGTTCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTTCCG GGCGGTGACC GAGCTGGGGC GGCCGGCCGC
 CGAGCAGTGG AACAGCCAGA AGGACACCCT GGAGCGGGAG CGGGCCTATG
 TGGACACGTA CTGCAGACAC AACTACGGGG GCGTGGAGAG TTTCACTGTG
 CAGCGGCGAG*

>DL;BoLA-DRB3*1802
BoLA-DRB3*1802, 250 bases, 597AA8CE checksum.
 GGAGTATGCT ACGAGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTGGA CAGATACTTC CATAATGGTG AAGAGTTCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTTCCG GGCGGTGACC GAGCTGGGGC GGCCGGCCGC
 CGAGCAGTGG AACAGCCAGA AGGACACCCT GGAGCGGGAG CGGGCCTATG
 TGGACACGTA CTGCAGACAC AACTACGGGG TCGTGGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*1901
BoLA-DRB3*1901, 250 bases, 2A85A691 checksum.
 GGAGTATTCT AAGAGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTACCTGGA CAGATACTTC TATAATGGAG AAGAGTACGT GCGCTTCGAC
 AGCGACTGGG GCGAGTACCG GGCGGTGACC GAGCTGGGGC GGCCGTCCGC
 CGAGTACTGG AACAGCCAGA AGGACATCCT GGAGCGGAAG CGGGCCAATG
 TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*1902
BoLA-DRB3*1902, 249 bases, 9319D425 checksum.
 GAGTATTCTA AGAGCGAGTG TCATTTCTTC AACGGGACCG AGCGGGTGCG
 GTACCTGGAC AGATACTTCT ATAATGGAGA AGAGTTCGTG CGCTTCGACA
 GCGACTGGGG CGAGTACCGG GCGGTGACCG AGCTAGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGAAGC GGGCCAATGT
 GGACACGTAC TGCAGACACA ACTACGGGGT CGTGGAGAGT TTCACTGTG*

>DL;BoLA-DRB3*1903
BoLA-DRB3*1903, 250 bases, 6BA9BEFE checksum.
 GGAGTATTCT AAGAGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTACCTGGA CAGATCCTTC TATAATGGAG AAGAGTTCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTACCG GGCGGTGACC GAGCTAGGGC GGCGCGTCGC
 CGAGTACTGG AACAGCCAGA AGGACATCCT GGAGCGGAAG CGGGCCAATG
 TGGACACGTA CTGCAGACAC AACTACGGGG TCTGTGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*20011
BoLA-DRB3*20011, 250 bases, 8C3DDFD7 checksum.
 GGAGTATTGT AAGAGAGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTGCTGGA CAGATACTTC TATAATGGAG AAGAGCGCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTTCCG GGCGGTGACC GAGCTGGGGC GGCCGTCCGC
 CGAGTACTGG AACAGCCAGA AGGACTTCCT GGAGCAGAGG CGGGCCGCGG
 TGGACACGTA CTGCAGACAC AACTACGGGG TCGTTGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*20012
BoLA-DRB3*20012, 250 bases, 43D255BB checksum.
 GGAGTATTGT AAGAGAGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTGCTGGA CAGATACTTC TATAATGGAG AAGAGCGCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTTCCG GGCGGTGACC GAGCTGGGGC GGCCGTCCGC
 CGAGTACTGG AACAGCCAGA AGGACTTCCT GGAGCAGAGG CGGGCCGCGG
 TGGACACGTA CTGCAGACAC AACTACGGGG TCGTGGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*2002
BoLA-DRB3*2002, 250 bases, EF3BC460 checksum.
 GGAGTATTGT AAGAGAGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTGCTGGA CAGATACTTC TATAATGGAG AAGAGCGCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTTCCG GGCGGTGACC GAGCTGGGGC GGCCGGACGC
 CGAGTACTGG AACAGCCAGA AGGACTTCCT GGAGCAGAGG CGGGCCGCGG
 TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*2003
BoLA-DRB3*2003, 249 bases, 1D8CE41B checksum.
 GAGTATTGTA AGAGAGAGTG TCATTTCTTC AACGGGACCG AGCGGGTGCG
 GTTGCTGGAC AGATACTTCT ATAATGGAGA AGAGCGCGTG CGCTTCGACA
 GCGACTGGGG CGAGTTCCGG GCGGTGACCG AGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACTTCCTG GAGCAGAGGC GGGCCGCGGT
 GGACACGTAC TGCAGACACA ACTACGGGGT CGTGGAGAGT TTCACTGTG*

>DL;BoLA-DRB3*2004
BoLA-DRB3*2004, 258 bases, 5ED3086 checksum.
 AGTATTGTAA GAGAGAGTGT CATTTCTTCA ACGGGACCGA GCGGGTGCGG
 TTGCTGGACA GATACTTCTA TAATGGAGAA GAGCGCGTGC GCTTCGACAG
 CGACTGGGGC GAGTTCCGGG CGGTGACCGA GCTGGGGCGG CCGTCCGCCG
 AGTACTGGAA CAGCCAGAAG GACTTCCTGG AGCAGAGGCG GGCCGTGGTG
 GACACGTACT GCAGACACAA CTACGGGGTC GTGGAGAGTT TCACTGTGCA
 GCGGCGAG*

>DL;BoLA-DRB3*2005
BoLA-DRB3*2005, 249 bases, 62FECB30 checksum.
 GAGTATTCTA CGAGCGAGTG TCATTTCTTC AACGGGACCG AGCGGGTGCG
 GTTGCTGGAC AGATACTTCT ATAATGGAGA AGAGCGCGTG CGCTTCGACA
 GCGACTGGGG CGAGTTCCGG GCGGTGACCG AGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACTTCCTG GAGCAGAGGC GGGCCGCGGT
 GGACACGTAC TGCAGACACA ACTACGGGGT CGTGGAGAGT TTCACTGTG*

>DL;BoLA-DRB3*2101
BoLA-DRB3*2101, 345 bases, E90B9F42 checksum.
 ATAGTGATGC TGATGGTGCT GTGCCCTCCC CTGGCCTGGG CCAGGGAGAT
 CCAACCACAT TTCCTGGAGT ATTCTACGGG CGAGTGTCAT TTCTTCAACG
 GGACCGAGCG GGTGCGGTTC CTGGACAGAT ACTTCTATAA TGGAGAAGAG
 TACGTGCGCT TCGACAGCGA CTGGGGCGAG TACCGGGCGG TGACCGAGCT
 GGGGCGGCAG GACGCCGAGC AGTGGAACAG CCAGAAGGAC TTCCTGGAGG
 AGAGGCGGGC CGAGGTGGAC ACGTACTGCA GACACAACTA CGGGGTCGGT
 GAGAGTTTCA CTGTGCAGCG GCGAGTGGAA CCTATAGTGA CTGTG*

>DL;BoLA-DRB3*2201
BoLA-DRB3*2201, 345 bases, 44BBE160 checksum.
 ATAGTGATGC TGATGGTGCT GTGCCCTCCC CTGGCCTGGG CCAGGGAGAT
 CCAACCACAT TTCCTGCAGT ATCATAAGGG CGAGTGTCAT TTCTTCAACG
 GGACCGAGCG GGTGCGGTTG CTGGACAGAC ACTTCTATAA TGGAGAAGAG
 TACGTGCGCT TCGACAGCGA CTGGGGCGAG TACCGGGCGG TGACCGAGCT
 GGGGCGGCCG TCCGCCGAGC ACTGGAACAG CCAGAAGGAG ATCCTGGAGC
 GGAGGCGGGC CGAGGTGGAC AGGGTGTGCA GACACAACTA CGGGGTCGGT
 GAGAGTTTCA CTGTGCAGCG GCGAGTGGAA CCTATAGTGA CTGTG*

>DL;BoLA-DRB3*2202
BoLA-DRB3*2202, 250 bases, D4A9DBBB checksum.
 GCAGTATCAT AAGGGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTGCTGGA CAGACACTTC ACTAATGGAG AAGAGTACGT GCGCTTCGAC
 AGCGACTGGG GCGAGTACCG GGCGTTGACC GAGCTGGGGC GGCCGTCCGC
 CGAGCACTGG AACAGCCAGA AGGAGATCCT GGAGCGGAGG CGGGCCGAGG
 TGGACAGGGT GTGCAGACAC AACTACGGGG TCGGTGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*2203
BoLA-DRB3*2203, 236 bases, 2CDC2223 checksum.
 TGCAGTATCA TAAGGGCGAG TGTCATTTCT TCAACGGGAC CGAGCGGGTG
 CGGTTGCTGG ACAGACACTT CTATAATGGA GAAGAGCACG TGCGCTTCGA
 CAGCGACTGG GGCGAGTACC GGGCGGTGAC CGAGCTGGGG CGGCCGTCCG
 CCGAGCACTG GAACAGCCAG AAGGAGATCC TGGAGCGGAG GCGGGCCGAG
 GTGGACAGGG TGTGCAGACA CAACTACGGG GTCGGT*

>DL;BoLA-DRB3*2301
BoLA-DRB3*2301, 250 bases, F7368A7F checksum.
 GGAGTATACC AAGAAAGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTGCTGGA CAGATACTAC ACTAATGGAG AAGAGACCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTTCCG GGCGGTGACC GAGCTGGGGC GGCAGGACGC
 CGAGCAGTGG AACAGCCAGA AGGACACCCT GGAGGACGAG CGGGCCGCTG
 TGGACACGTA CTGCAGATAC AACTACGGGG TCGGTGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*2401
BoLA-DRB3*2401, 250 bases, CE02AF52 checksum.
 GGAGTATTGT AAGAGAGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTGGA CAGATACTTC TATAATGGAG AAGAGTACGT GCGCTTCGAC
 AGCGACTGGG GCGAGTTCCG GGCGGTGACC GAGCTAGGGC GGCCGGACGC
 CGAGTACTGG AACAGCCAGA AGGAGATCCT GGAGGAGAGG CGGGCCGAGG
 TGGACAGGGT GTGCAGACAC AACTACGGGG TCGGTGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*2402
BoLA-DRB3*2402, 249 bases, C15D7D35 checksum.
 GAGTATTGTA AGAGAGAGTG TCATTTCTTC AACGGGACCG AGCGGGTGCG
 GTTCCTGGAC AGATACTTCT ATAATGGAGA AGAGTACGTG CGCTTCGACA
 GCGACTGGGG CGAGTTCCGG GCGGTGACCG AGCTGGGGCG GCCGTCCGCC
 GAGTACTGGA ACAGCCAGAA GGAGATCCTG GAGGAGAGGC GGGCCGAGGT
 GGACAGGGTG TGCAGACACA ACTACGGGGT CGGTGAGAGT TTCACTGTG*

>DL;BoLA-DRB3*2403
BoLA-DRB3*2403, 228 bases, 109F2915 checksum.
 TAAGAGAGAG TGTCATTTCT TCAACGGGAC CGAGCGGGTG CGGTTCCTGG
 ACAGATACTT CTATAATGGA GAAGAGTACG TGCGCTTCGA CAGCGACTGG
 GGCGAGTTCC GGGCGGTGAC CGAGCTAGGG CGGCCGGACG CCGAGTACTG
 GAACAGCCAG AAGGACTTCC TGGAGGAGAG GCGGGCCGAG GTGGACAGGG
 TGTGCAGACA CAACTACGGG GTCGGTGA*

>DL;BoLA-DRB3*25011
BoLA-DRB3*25011, 250 bases, 4A214A95 checksum.
 GGAGTATTCT ACGAGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTACCTGGA CAGATACTTC CATAATGGAG AAGAGTTCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTTCCG GGCGGTGACC GAGCTGGGGC GGCCGGCCGC
 CGAGCAGTGG AACAGCCAGA AGGACACCCT GGAGGACGAG CGGGCTTCGG
 TGGACACGTA CTGCAGATAC AACTACGGGG TCGGTGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*25012
BoLA-DRB3*25012, 250 bases, E9836826 checksum.
 GGAGTATTCT ACGAGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTACCTGGA CAGATACTTC CATAATGGAG AAGAGTTCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTTCCG GGCGGTGACC GAGCTGGGGC GGCCGGCCGC
 CGAGCAGTGG AACAGCCAGA AGGACACCCT GGAGGACGAG CGGGCCTCGG
 TGGACACGTA CTGCAGATAC AACTACGGGG TCGGTGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*2502
BoLA-DRB3*2502, 225 bases, 782892A1 checksum.
 GAGCGAGTGT CATTTCTTCA ACGGGACCGA GCGGGTGCGG TACCTGGACA
 GATACTTCCA TAATGGAGAA GAGTTCGTGC GCTTCGACAG CGACTGGGGC
 GAGTTCCGGG CGGTGACCGA GCTGGGGCGG CAGGACGCCG AGCAGTGGAA
 CAGCCAGAAG GACACCCTGG AGGACGAGCG GGCCGCTGTG GACACGTACT
 GCAGATACAA CTACGGGGTC GGTGA*

>DL;BoLA-DRB3*2601
BoLA-DRB3*2601, 250 bases, 635570BA checksum.
 GGAGTATACC AAGAAAGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTGGA CAGATACTTC CATAATGGAG AAGAGACCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTACCG GGCGGTGACC GAGCTAGGGC GGCGCGTCGC
 CGAGCAGTGG AACAGCCAGA AGGACACCCT GGAGCGGGCG CGGGCCGCGG
 TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*2701
BoLA-DRB3*2701, 237 bases, 4A6ABF57 checksum.
 GGAGTATTAT AAGAGAGAGT GTCATTTCTT CGACGGGACC GAGCGGGTGC
 GGTTCCTGGA CAGATGCTAC ACTAATGGAG AAGAGACCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTTCCG GGCGGTGACC GAGCTAGGGC GGCCGGACGC
 CGAGTACTGG AACAGCCAGA AGGACTTCCT GGAGGAGAGG CGGGCCGAGG
 TGGACAGGGT GTGCAGACAC AACTACGGGG TCGGTGA*

>DL;BoLA-DRB3*2702
BoLA-DRB3*2702, 250 bases, BBE05F95 checksum.
 GGAGTATTAT AAGAGAGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 AGTTCCTGGA CAGATGCTAC ACTAATGGAG AAGAGACCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTTCCG GGCGGTGACC GAGCTAGGGC GGCCGGACGC
 CGAGTACTGG AACAGCCAGA AGGACTTCCT GGAGGAGAGG CGGGCCGAGG
 TGGACAGGGT GTGCAGACAC AACTACGGGG TCGGTGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*2703
BoLA-DRB3*2703, 250 bases, 32BF35FB checksum.
 GGAGTATTAT AAGAGAGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTGGA CAGATGCTAC ACTAATGGAG AAGAGACCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTTCCG GGCGGTGACC GAGCTAGGGC GGCCGGACGC
 CGAGTACTGG AACAGCCAGA AGGACTTCCT GGAGGAGAGG CGGGCCGAGG
 TGGACAGGGT GTGCAGACAC AACTACGGGG TCGGTGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*2704
BoLA-DRB3*2704, 250 bases, FA73CD7F checksum.
 GGAGTATTAT AAGAGAGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTGGA CAGATGCTTC CATAATGGAG AAGAGTTCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTTCCG GGCGGTGACC GAGCTAGGGC GGCCGGCCGC
 CGAGTACTGG AACAGCCAGA AGGACTTCCT GGAGGAGAGG CGGGCCGAGG
 TGGACAGGGT GTGCAGACAC AACTACGGGG TCGGTGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*2705
BoLA-DRB3*2705, 250 bases, 442A1DEC checksum.
 GGAGTATTAT AAGAGAGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTGGA CAGATGCTAC ACTAATGGAG AAGAGACCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTTCCG GGCGGTGACC GAGCTAGGGC GGCCGGACGC
 CGAGTACTGG AACAGCCAGA AGGACTTCCT GGAGGAGAGG CGGGCCGCGG
 TGGACAGGGT GTGCAGACAC AACTACGGGG TCGTGGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*2706
BoLA-DRB3*2706, 236 bases, 81198C4B checksum.
 TGGAGTATTA TAAGAGAGAG TGTCATTTCT TCAACGGGAC CGAGCGGGTG
 CGGTTCCTGG ACAGATGCTA CACTAATGGA GAAGAGACCG TGCGCTTCGA
 CAGCGACTGG GGCGAGTTCC GGGCGGTGAC CGAGCTAGGG CGGCCGTCCG
 CCGAGTACTG GAACAGCCAG AAGGACATCC TGGAGGAGAG GCGGGCCGAG
 GTGGACAGGG TGTGCAGACA CAACTACGGG GTCGTG*

>DL;BoLA-DRB3*2707
BoLA-DRB3*2707, 249 bases, C0081580 checksum.
 GAGTATTATA AGAGAGAGTG TCATTTCTTC AACGGGACCG AGCGGGTGCG
 GTTCCTGGAC AGATGCTACA CTAATGGAGA AGAGACCGTG CGCTTCGACA
 GCGACTGGGG CGAGTTCCGG GCGGTGACCG AGCTAGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACTTCCTG GAGGAGAGGC GGGCCGAGGT
 GGACAGGGTG TGCAGACACA ACTACGGGGT CGTGGAGAGT TTCACTGTG*

>DL;BoLA-DRB3*2708
BoLA-DRB3*2708, 250 bases, 4BAEAD2D checksum.
 GGAGTATTAT AAGAGAGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTGGA CAGATGCTTC CATAATGGAG AAGAGTTCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTTCCG GGCGGTGACC GAGCTAGGGC GGCCGGACGC
 CGAGTACTGG AACAGCCAGA AGGACTTCCT GGAGGAGAGG CGGGCCGAGG
 TGGACACGGT GTGCAGACAC AACTACGGGG TCGGTGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*2709
BoLA-DRB3*2709, 258 bases, 5B0AEB7F checksum.
 AGTATTATAA GAGAGAGTGT CATTTCTTCA ACGGGACCGA GCGGGTGCGG
 TTCCTGGACA GATACTACAC TAATGGAGAA GAGACCGTGC GCTTCGACAG
 CGACTGGGGC GAGTTCCGGG CGGTGACCGA GCTAGGGCGG CCGGACGCCG
 AGTACTGGAA CAGCCAGAAG GACTTCCTGG AGGAGAGGCG GGCCGAGGTG
 GACAGGGTGT GCAGACACAA CTACGGGGTC GGTGAGAGTT TCACTGTGCA
 GCGGCGAG*

>DL;BoLA-DRB3*2710
BoLA-DRB3*2710, 249 bases, 9A9D244B checksum.
 GAGTATTATA AGAGAGAGTG TCATTTCTTC AACGGGACCG AGCGGGTGCG
 GTTCCTGGAC AGATGCTTCC ATAATGGAGA AGAGTTCGTG CGCTTCGACA
 GCGACTGGGG CGAGTTCCGG GCGGTGACCG AGCTAGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACTTCCTG GAGGAGAGGC GGGCCGAGGT
 GGACAGGGTG TGCAGACACA ACTACGGGGT CGGTGAGAGT TTCACTGTG*

>DL;BoLA-DRB3*2801
BoLA-DRB3*2801, 345 bases, 39FF2C1A checksum.
 ATAGTGATGC TGATGGTGCT GTGCCCTCCC CTGGCCTGGG CCAGGGAGAT
 CCAACCACAT TTCCTGCAGT ATCATAAGGG CGAGTGTCAT TTCTTCAACG
 GGACCGAGCG GGTGCGGTTG CTGGACAGAC ACTTCTATAA TGGAGAAGAG
 TTCGTGCGCT TCGACAGCGA CTGGGACGAG TTCCGGGCGG TGACCGAGCT
 GGGGCGGCCG GCCGCCGAGT ACTGGAACAG CCAGAAGGAC TTCCTGGAGG
 AGAGGCGGGC CGAGGTGGAC ACGTACTGCA GACACAACTA CGGGGGCGTG
 GAGAGTTTCA CTGTGCAGCG GCGAGTGGAA CCTATAGTGA CTGTG*

>DL;BoLA-DRB3*2802
BoLA-DRB3*2802, 234 bases, 1CC338D6 checksum.
 CAGTATCATA AGGGCGAGTG TCATTTCTTC AACGGGACCG AGCGGGTGCG
 GTTGCTGGAC AGACACTTCT ATAATGGAGA AGAGTACGTG CGCTTCGACA
 GCGACTGGGA CGAGTTCCGG GCGGTGACCG AGCTGGGGCG GCCGGCCGCC
 GAGTACTGGA ACAGCCAGAA GGACTTCCTG GAGGAGAGGC GGGCCGAGGT
 GGACACGTAC TGCAGACACA ACTACGGGGG CGTG*

>DL;BoLA-DRB3*2901
BoLA-DRB3*2901, 250 bases, 4D3F8D6D checksum.
 GGAGTATGCT CAGAGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTGCA CAGATACTTC CATAATGGAG AAGAGTTCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTTCCG GGCGGTGACC GAGCTGGGGC AGCGGGTCGC
 CGAGCAGTGG AACAGCCAGA AGGACACGCT GGAGCGGGAG CGGGCCTATG
 TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*3001
BoLA-DRB3*3001, 250 bases, E5B53002 checksum.
 GGAGTATTCT AAGAGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTGGA CAGATACTAC ACTAATGGAG AAGAGACCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTTCCG GGCGTTGACC GAGCTGGGGC GGCAGGACGC
 CGAGCAGTGG AACAGCCAGA AGGAGATCCT GGAGGACGAG CGGGCCGCGG
 TGGACACGTA CTGCAGATAC AACTACGGGG TCGGTGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*3002
BoLA-DRB3*3002, 250 bases, B0129193 checksum.
 GGAGTATTGT AAGAGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTAGA CAGATACTAC ACTAATGGAG AAGAGACCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTTCCG GGCGTTGACC GAGCTGGGGC GGCAGGACGC
 CGAGCAGTGG AACAGCCAGA AGGAGATCCT GGAGGACGAG CGGGCCGCGG
 TGGACACGTA CTGCAGACAC AACTACGGGG GCGTGGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*3101
BoLA-DRB3*3101, 699 bases, 2F54AA81 checksum.
 ATGGTGTGCC TGTATTTCTC TGGAGGCTCC TGGATGGCAG CTCTGATAGT
 GATGCTGATG GTGCTGTGCC CTCCCCTGGC CTGGGCCAGG GAGATCCAAC
 CACATTTCCT GGAGTATTAT AAGGGCGAGT GTCATTTCTT CAACGGGACC
 GAGCGGGTGC GGTTCCTGGA CAGACACTTC TATAATGGAG AAGAGTTCGT
 GCGCTTCGAC AGCGACTGGG GCGAGTTCCG GGCGGTGACC GAGCTGGGGC
 GGCCGGCCGC CGAGCACTGG AACAGCCAGA AGGACTTCCT GGAGCAGAAG
 CGGGCCGAGG TGGACAGGGT GTGCAGACAC AACTACGGGG GTGTGGAGAG
 TTTCACTGTG CAGCGGCGAG TGGAGCCTAC AGTGACTGTG TATCCTGCAA
 AGACTCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAACGGT
 TTCTACCCAG GCCACATTGA AGTCAGGTGG TTCCGGAACG GCCATGAAGA
 GGAGGCTGTG GATCACCCCA GCCGGACGAG CCCTATCACA GTAGAATGGA
 GGGCACGGTC TGACTCTGCT CAGAGCAAGA TGATGAGTGG AGTCGGGGGC
 TTCGTTCTGG GTCTGCTCTT CCAGGCCGTG GGGCTCTTCA TCTACTTCAG
 GAATCAGAAA GGACGCCCTA CACTTCAGCC AACAGGGCTC CTGAGCTGA*

>DL;BoLA-DRB3*3102
BoLA-DRB3*3102, 236 bases, 48C1D5 checksum.
 TGGAGTATTC TAAGGGCGAG TGTCATTTCT TCAACGGGAC CGAGCGGGTG
 CGGTTCCTGG ACAGACACTT CTATAATGGA GAAGAGTTCG TGCGCTTCGA
 CAGCGACTGG GGCGAGTTCC GGGCGGTGAC CGAGCTGGGG CGGCCGGCCG
 CCAAGTACTG GAACAGCCAG AAGGACTTCC TGGAGCAGAA GCGGGCCGAG
 GTGGACAGGG TGTGCAGACA CAACTACGGG GGTGTG*

>DL;BoLA-DRB3*3103
BoLA-DRB3*3103, 233 bases, CE56FDF4 checksum.
 TGGAGTATTA TAAGGGCGAG TGTCATTTCT TCAACGGGAC CGAGCGGGTG
 CGGTTCCTGG ACAGACACTT CTATAATGGA GAAGAGTTCG TGCGCTTCGA
 CAGCGACTGG GACGAGTTCC GGGCGGTGAC CGAGCTGGGG CGGCCGGCCG
 CCGAGCACTG GAACAGCCAG AAGGACTTCC TGGAGCAGAA GCGGGCCGAG
 GTGGACAGGG TGTGCAGACA CAACTACGGG GGT*

>DL;BoLA-DRB3*3201
BoLA-DRB3*3201, 599 bases, 1096C71C checksum.
 CACATTTCCT GGAGTATTGT AAGAGAGAGT GTCATTTCTT CAACGGGACC
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAATGGAG AAGAGTACGT
 GCGCTTCGAC AGCGACTGGG GCGAGTTCCG GGCGGTGACC GAGCTGGGGC
 GGCCGGACGC CAAGTACTGG AACAGCCAGA AGGAGATCCT GGAGCGGGAG
 CGGGCCTATG TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG
 TTTCACTGTG CAGCGGCGAG TGGAGCCTAT AGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAACGGT
 TTCTACCCAG GCCACATTGA AGTCAGGTGG TTCCGGAATG GCCATGAAGA
 GGAGGCTGTG GATCACCCCA GCCGGACGAG CCCTATCACA GTAGAATGGA
 GGGCACGGTC TGACTCTGCT CAGAGCAAGA TGATGAGTGG AGTCGGGGGC
 TTCGTTCTGG GTCTGCTCTT CCTTACCGTA GGGCTCTTCA TCTAGTTCAG
 GGATCAGAAA GGACGCCCTA CACTTCAGCC AACAGGGCTC CTGAGCTGA*

>DL;BoLA-DRB3*3202
BoLA-DRB3*3202, 250 bases, 4B2FF342 checksum.
 GGAGTATTGT AAGAGAGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTGGA CAGATACTTC TATAATGGAG AAGAGTACGT GCGCTTCGAC
 AGCGACTGGG GCGAGTTCCG GGCGGTGACC GAGCTGGGGC GGCCGGACGC
 CAAGTACTGG AACAGCCAGA AGGAGATCCT GGAGCGGGAG CGGGCCTATG
 TGGACACGTA CTGCAGACAC AACTACGGGG TCGTGGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*3203
BoLA-DRB3*3203, 249 bases, C5D4D9F9 checksum.
 GAGTATTGTA AGAAAGAGTG TCATTTCTTC AACGGGACCG AGCGGGTGCG
 GTTCCTGGAC AGATACTTCT ATAATGGAGA AGAGTACGTG CGCTTCGACA
 GCGACTGGGG CGAGTTCCGG GCGGTGACCG AGCTGGGGCG GCCGGACGCC
 AAGTACTGGA ACAGCCAGAA GGAGATCCTG GAGCGGGAGC GGGCCTATGT
 GGACACGTAC TGCAGACACA ACTACGGGGT CGTGGAGAGT TTCACTGTG*

>DL;BoLA-DRB3*3301
BoLA-DRB3*3301, 247 bases, 893D503F checksum.
 GGAGTATTCT ACGAGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTGCTGGA CAGATACTTC TATAATGGAG AAGAGTACGT GCGCTTCGAC
 AGCGACTGGG GCGAGTACCA GGCGGTGACC GAGCTGGGGC GGCCGTCCGC
 CGAGCACTGG AACAGCCAGG AGATCCTGGA GCAGAGGCGG GCCGCGGTGG
 ACACGTACTG CAGACACAAC TACGGGGTCG TGGAGAGTTT CACTGTG*

>DL;BoLA-DRB3*3401
BoLA-DRB3*3401, 250 bases, 7E6280E1 checksum.
 GGAGTATTGT AAGAGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTGGA GAGATCCTTC TATAATGGAG AAGAGTTCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTACCG GGCGGTGACC GAGCTAGGGC GGCGGGTCGC
 CGAGCAGTTG AACAGCCAGA AGGACTTGCT GGAGCAGAAG CGGGCCAATG
 TGGACACGTA CTGCAGACAC AACTACGGGG TCGTGGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*3402
BoLA-DRB3*3402, 249 bases, 5832FA75 checksum.
 GAGTATTGTA AGAGCGAGTG TCATTTCTTC AACGGGACCG AGCGGGTGCG
 GTTCCTGGAG AGATCCTTCT ATAATGGAGA AGAGTTCGTG CGCTTCGACA
 GCGACTGGGG CGAGTACCGG GCGGTGACCG AGCTAGGGCG GCGGGTCGCG
 AAGCAGTTGA ACAGCCAGAA GGACTTGCTG GAGCAGAAGC GGGCCAATGT
 GGACACGTAC TGCAGACACA ACTACGGGGT CGTGGAGAGT TTCACTGTG*

>DL;BoLA-DRB3*3501
BoLA-DRB3*3501, 250 bases, DB9F8501 checksum.
 GGAGTATTCT AAGAGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTACCTGGA CAGATACTAC ACTAATGGAG AAGAGAACGT GCGCTTCGAC
 AGCGACTGGG GCGAGTTCCG GGCGGTGACC GAGCTGGGGC GGCCGGACGC
 CGAGTACTGG AACAGCCAGA AGGACTTCCT GGAGCGGAAG CGGGCCAATG
 TGGACACGTA CTGCAGACAC AACTACGGGG TCTTTGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*3601
BoLA-DRB3*3601, 250 bases, 365E1C14 checksum.
 GGAGTATTCT AAGAGCGAGT GTCATTTCTT CAACGGGACC GAGCGGGTGC
 GGTTCCTGGA CAGATACTAC ACTAATGGAG AAGAGACCGT GCGCTTCGAC
 AGCGACTGGG GCGAGTTCCG GGCGTTGACC GAGCTGGGGC GGCAGGACGC
 CGAGCAGTGG AACAGCCAGA AGGACACCCT GGAGCGGGAG CGGGCCTATG
 TGGACACGTA CTGCAGACAC AACTACGGGG GCGTGGAGAG TTTCACTGTG*

>DL;BoLA-DRB3*3701
BoLA-DRB3*3701, 234 bases, A7B64604 checksum.
 GAGTATTCTA CGAGCGAGTG TCATTTCTTC AACGGGACCG AGCGGGTGCG
 GTACCTGGAC AGATACTTCT ATAATGGAGA AGAGTACGTG CGCTTCGACA
 GCGACTGGGG CGAGTTCCGG GCGGTGACCG AGCTGGGGCG GCCGGACGCC
 AAGTACTGGA ACAGCCAGAA GGACACCCTG GAGGACGAGC GGGCTTCGGT
 GGACACGTAC TGCAGATACA ACTACGGGGT CGGT*

>DL;BoLA-DRB3*3801
BoLA-DRB3*3801, 234 bases, 37124F8C checksum.
 GAGTATTCTA AGAGCGAGTG TCATTTCTTC AACGGGACCG AGCGGGTGCG
 GTACCTGGAC AGATACTTCT ATAATGGAGA AGAGTACGTG CGCTTCGACA
 GCGACTGGGG CGAGTACCGG GCGGTGACCG AGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACTTCCTG GAGCGGAAGC GGGCCAATGT
 GGACACGTAC TGCAGACACA ACTACGGGGT CGTG*

>DL;BoLA-DRB3*3901
BoLA-DRB3*3901, 234 bases, 3AD453C6 checksum.
 GAGTATTCTA CGGGCGAGTG TCATTTCTTC AACGGGACCG AGCGGGTGCG
 GTACCTGGAC AGATACTTCT ATAATGGAGA AGAGTACGTG CGCTTCGACA
 GCGACTGGGG CGAGTTCCAG GCGGTGACCG AGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACACCCTG GAGCGGGAGC GGGCCTATGT
 GGACACGTAC TGCAGACACA ACTACGGGGT CGGT*

>DL;BoLA-DRB3*4001
BoLA-DRB3*4001, 249 bases, 38D80C8B checksum.
 GAGTATTCTA CGGGCGAGTG TCATTTCTTC AACGGGACCG AGCGGGTGCG
 GTACCTGGAC AGATACTTCT ATAATGGAGA AGAGTACGCG CGCTTCGACA
 GCGACTGGGG CGAGTTCCGG GCGGTGACCG AGCTGGGGCG GCCGGACGCC
 AAGTACTGGA ACAGCCAGAA GGACTTCCTG GAGCAGAAGC GGGCCGAGGT
 GGACAGGGTG TGCAGACACA ACTACGGGGG TGTGGAGAGT TTCACTGTG*

>DL;BoLA-DRB3*4002
BoLA-DRB3*4002, 228 bases, 37BB33A3 checksum.
 TAAGGGCGAG TGTCATTTCT TCAACGGGAC CGAGCGGGTG CGGTTGCTGG
 ACAGACACTT CTATAATGGA GAAGAGTACG TGCGCTTCGA CAGCGACTGG
 GGCGAGTTCC GGGCGGTGAC CGAGCTGGGG CGGCCGGACG CCAAGTACTG
 GAACAGCCAG AAGGACTTCC TGGAGCAGAA GCGGGCCGAG GTGGACAGGG
 TGTGCAGACA CAACTACGGG GGTGTGGA*

>DL;BoLA-DRB3*4101
BoLA-DRB3*4101, 246 bases, 690E3BA6 checksum.
 GAGTATACCA AGAAAGAGTG TCATTTCTTC AACGGGACCG AGCGGGTGCG
 GTTCCTGGAC AGATACTTCT ATAATGGAGA AGAGTACGTG CGCTTCGACA
 GCGACTGGAG CGAGTACCGG GCGGTGACCG AGCTAGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGGA GATCCTGGAG CGGGCGCGGG CCGCGGTGGA
 CACGTACTGC AGACACAACT ACGGGGTCGG TGAGAGTTTC ACTGTG*

>DL;BoLA-DRB3*4201
BoLA-DRB3*4201, 249 bases, C92BBBAF checksum.
 GAGTATCGTA AGAGCGAGTG TCATTTCTTC AACGGGACCG AGCGGGTGCG
 GTTCCTGGAC AGATACTTCT ATAATGGAGA AGAGCACGTG CGCTTCGACA
 GCGACTGGGG CGAGTACCGG GCGGTGACCG AGCTGGGGCG GCCGGACGCC
 AAGTACTGGA ACAGCCAGAA GGAGATCCTG GAGCGGAGGC GGGCCGAGGT
 GGACACGGTG TGCAGACACA ACTACGGGGT CGTGGAGAGT TTCACTGTG*

>DL;BoLA-DRB3*4301
BoLA-DRB3*4301, 249 bases, 59F0E7BA checksum.
 GAGTATCGTA AGAGCGAGTG TCATTTCTTC AACGGGACCG AGCGGGTGCG
 GTACCTGGAC AGATCCTTCT ATAATGGAGA AGAGTTCGTG CGCTTCGACA
 GCGACTGGGG CGAGTACCGG GCGGTGACCG AGCTAGGGCG GCGCGTCGCC
 GAGCAGTGGA ACAGCCAGAA GGACTTGCTG GAGCGGAAGC GGGCCAATGT
 GGACACGTAC TGCAGACACA ACTACGGGGT CGGTGAGAGT TTCACTGTG*

>DL;BoLA-DRB3*4302
BoLA-DRB3*4302, 251 bases, 7D38AE64 checksum.
 TGGAGTATCG TAAGAGCGAG TGTCATTTCT TCAACGGGAC CGAGCGGGTG
 CGGTACCTGG ACAGATACTT CTATAATGGA GAAGAGTTCG TGCGCTTCGA
 CAGCGACTGG GGCGAGTACC GGGCGGTGAC CGAGCTAGGG CGGCGCGTCG
 CCGAGCAGTG GAACAGCCAG AAGGACTTGC TGGAGCGGAA GCGGGCCAAT
 GTGGACACGT ACTGCAGACA CAACTACGGG GTCGGTGAGA GTTTCACTGT
 G*

>DL;BoLA-DRB3*4303
BoLA-DRB3*4303, 252 bases, 258BD592 checksum.
 TGGAGTATTG TAAGAGCGAG TGTCATTTCT TCAACGGGAC CGAGCGGGTG
 CGGTACCTGG ACAGATCCTT CTATAATGGA GAAGAGTTCG TGCGCTTCGA
 CAGCGACTGG GGCGAGTACC GGGCGGTGAC CGAGCTAGGG CGGCGCGTCG
 CCGAGCAGTG GAACAGCCAG AAGGACTTCC TGGAGCGGAA GCGGGCCAAT
 GTGGACACGT ACTGCAGACA CAACTACGGG GTCGGTGAGA GTTTCACTGT
 GC*

>DL;BoLA-DRB3*4401
BoLA-DRB3*4401, 249 bases, 8033CB4 checksum.
 GAGTATTATA AGAGCGAGTG TCATTTCTTC AACGGGACCG AGCGGGTGCG
 GTTCCTGGAC AGATACTACA CTAATGGAGA AGAGACCGTG CGCTTCGACA
 GCGACTGGGG CGAGTTCCGG GCGTTGACCG AGCTGGGGCG GCAGGACGCC
 GAGCAGTGGA ACAGCCAGAA GGACTTCCTG GAGCGGGCGC GGGCCGCGGT
 GGACACGTAC TGCAGATACA ACTACGGGGT CGGTGAGAGT TTCACTGTG*

>DL;BoLA-DRB3*4501
BoLA-DRB3*4501, 249 bases, 33D6B75D checksum.
 GAGTATTATA AGAGAGAGTG TCATTTCTTC AACGGGACCG AGCGGGTGCG
 GTTCCTGGAC AGATGCTACA CTAATGGAGA AGAGACCGTG CGCTTCGACA
 GCGACTGGGG CGAGTTCCGG GCGGTGACCG AGCTGGGGCG GCCGGACGCC
 AAGTACTGGA ACAGCCAGAA GGACTTCCTG GAGCAGGCGC GGGCCGCGGT
 GGACACGTAC TGCAGACACA ACTACGGGGT CGGTGAGAGT TTCACTGTG*

>DL;BoLA-DRB3*46011
BoLA-DRB3*46011, 249 bases, E5207B3D checksum.
 GAGTATTGTA AGAGAGAGTG TCATTTCTTC AACGGGACCG AGCGGGTGCG
 GTTCCTGGAC AGATACTTCT ATAATGGAGA AGAGTACGTG CGCTTCGACA
 GCGACTGGGG CGAGTTCCGG GCGGTGACCG AGCTGGGGCG GCCGGACGCC
 AAGTACTGGA ACAGCCAGAA GGACTTCCTG GAGCAGGCGC GGGCCGCGGT
 GGACACGTAC TGCAGACACA ACTACGGGGT CGGTGAGAGT TTCACTGTG*

>DL;BoLA-DRB3*4701
BoLA-DRB3*4701, 249 bases, E9C83A checksum.
 GAGTATACCA AGAAAGAGTG TCATTTCTTC AACGGGACCG AGCGGGTGCG
 GTTGCTGGAC AGATACTTCT ATAATGGAGA AGAGCGCGTG CGCTTCGACA
 GCGACTGGGG CGAGTACCGG GAGGTGACCG AGCTGGGGCG GCCGTCCGCC
 GAGTACTGGA ACAGCCAGAA GGACTTCCTG GAGCAGAGGC GGGCCGCGGT
 GGACACGTAC TGCAGACACA ACTACGGGGT CGTTGAGAGT TTCACTGCG*

>DL;BoLA-DRB3*4801
BoLA-DRB3*4801, 236 bases, 870B1F1E checksum.
 TGGAGTATTC TAAGAGCGAG TGTCATTTCT TCAACGGGAC CGAGCGGGTG
 CGGTTGCTGG ACAGATACTA CACTAATGGA GAAGAGACCG TGCGCTTCGA
 CAGCGACTGG GGCGAGTTCC GGGCGGTGAC CGAGCTGGGG CGGCCGGACG
 CCGAGTACTG GAACAGCCAG AAGGACTTCC TGGAGCAGAG GCGGGCCGAG
 GTGGACACGT ACTGCAGACA CAACTACGGG GTCGTG*

>DL;BoLA-DRB3*4802
BoLA-DRB3*4802, 249 bases, EBEC1B08 checksum.
 GAGTATTGTA AGAGAGAGTG TCATTTCTTC AACGGGACCG AGCGGGTGCG
 GTTGCTGGAC AGATACTACA CTAATGGAGA AGAGACCGTG CGCTTCGACA
 GCGACTGGGG CGAGTTCCGG GCGGTGACCG AGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACTTCCTG GAGCAGAGGC GGGCCGCGGT
 GGACACGTAC TGCAGACACA ACTACGGGGT CGTGGAGAGT TTCACTGTG*

>DL;BoLA-DRB3*4901
BoLA-DRB3*4901, 236 bases, 46910C9D checksum.
 TGGAGTATTC TACGGGCGAG TGTCATTTCT TCAACGGGAC CGAGCGGGTG
 CGGTACCTGG ACAGATACTT CTATAATGGA GAAGAGTACG CGCGCTTCGA
 CAGCGACTGG GGCGAGTTCC GGGCGGTGAC CGAGCTGGGG CGGCCGGACG
 CCAAGTACTG GAACAGCCAG AAGGACTTCC TGGAGGAGAA GCGGGCCTAT
 GTGGACACGT ACTGCAGACA CAACTACGGG GTCGGT*

>DL;BoLA-DRB3*5001
BoLA-DRB3*5001, 236 bases, CF9BBBA7 checksum.
 TGGAGTATTC TACGGGGGAG TGTCATTTCT TCAACGGGAC CGAGCGGGTG
 CGGTACCTGG ACAGATACTT CCATAATGGA GAAGAGCTCG TGCGCTTCGA
 CAGCGACTGG GGCGAGTTCC GGGCGGTGAC CGAGCTGGGG CGGCCGGACG
 CCGAGCACTT GAACGGCCAG AAGGACACCC TGGAGCGGGA GCGGGCCTAT
 GTGGACACGT ACTGCAGACA CAACTACGGG GTCGTT*

>DL;BoLA-DRB3*5101
BoLA-DRB3*5101, 237 bases, 14B24EEF checksum.
 CTGGAGTATT CCAAGAAAGA GTGTCATTTC TTCAACGGGA CCGAGCGGGT
 GCGGTTCCTG GACAGATCCT TCCATAATGG AGAAGAGATC GTGCGCTTCG
 ACAGCGACTG GGGCGAGTAC CGGGCGGTGA CCGAGCTAGG GCGGCCGGAC
 GCCGAGTACT GGAACAGCCA GAAGGACTTC CTGGAGGAGA AGCGGGCCGC
 GGTGGACAGG TACTGCAGAC ACAACTACGG GGTCGGT*

>DL;BoLA-DRB3*5701
BoLA-DRB3*5701, 252 bases, D9C72C84 checksum.
 TGGAGTATTA TAAGAGTGAG TGTCATTTCT TCAACGGGAC CGAGCGTGTG
 CGGTACCTGG ACAGATACTT CTATAATGGA GAAGAGTACG TGCGCTTCGA
 CAGCGACTGG GGCGAGTACC GGGCGGTGAC CGAGCTGGGG CGGCCGGACG
 CCAAGTACTG GAACAGCCAG AAGGAGATCC TGGAGCGGAG GCGGGCCGAG
 GTGGACACGG TGTGCAGACA CAACTACGGG GTCGTTGAGA GTTTCACTGT
 GC*

>DL;BoLA-DRB3*5702
BoLA-DRB3*5702, 252 bases, F627E737 checksum.
 TGGAGTATCA TAAGAGTGAG TGTCATTTCT TCAACGGGAC CGAGCGTTTG
 CGGTACCTGG ACAGATACTT CTATAATGGA GAAGAGTACG TGCGCTTCGA
 CAGCGACTGG GGCGAGTACC GGGCGGTGAC CGAGCTGGGG CGGCCGGACG
 CCAAGTACTG GAACAGCCAG AAGGAGATCC TGGAGCGGAG GCGGGCCGAG
 GTGGACACGG TGTGCAGACA CAACTACGGG GTCGGTGAGA GTTTCACTGT
 GC*

>DL;BoLA-DRB3*5801
BoLA-DRB3*5801, 252 bases, B411287A checksum.
 TGGAGTATCG TAAGAGCGAG TGTCATTTCT TCAACGGGAC CGAGCGGGTG
 CGGTTCCTGG ACAGATACTA CACTAATGGA GAAGAGACCG TGCGCTTCGA
 CAGCGACTGG GGCGAGTTCC GGGCGTTGAC CGAGCTGGGG CGGCCGGACG
 CCGAGTACTG GAACAGCCAG AAGGAGATCC TGGAGCGGAG GCGGGCCGAG
 GTGGACACGG TGTGCAGACA CAACTACGGG GTCTTTGAGA GTTTCACTGT
 GC*

>DL;BoLA-DRB3*5901
BoLA-DRB3*5901, 252 bases, 170680DD checksum.
 TGGAGTATTC TAAGAGCGAG TGTCATTTCT TCAACGGGAC CGAGCGTTTG
 CGGTACCTGG ACAGATACTT CCATAATGGA GAAGAGTACG TGCGCTTCGA
 CAGCGACTGG GGCGAGTTCC GGGCGGTGAC CGAGCTGGGG CGGCCGGACG
 CCGAGTACTG GAACAGCCAG AAGGACATCC TGGAGCACAA GCGGGCCTAT
 GTGGACACGT ACTGCAGATA CAACTACGGG GTCTTTGAGA GTTTCACTGT
 GC*

>DL;BoLA-DRB3*6001
BoLA-DRB3*6001, 252 bases, 518FE5E checksum.
 TGGAGTATTA TAAGAGAGAG TGTCATTTCT TCAACGGGAC CGAGCGTTTG
 CGGTTCCTGG ACAGATACTT CTATAATGGA GAAGAGTACG TGCGCTTCGA
 CAGCGACTGG GGCGAGTACC GGGCGGTGAC CGAGCTGGGG CGGCCGGTCG
 CCAAGTACTG GAACAGCCAG AAGGACTTCC TGGAGCGGAA GCGGGCCACT
 GTGGACACGT ACTGCAGACA CAACTACGGG GTCTTTGAGA GTTTCACTGT
 GC*

>DL;BoLA-DRB3*6101
BoLA-DRB3*6101, 252 bases, 79EE9610 checksum.
 TGGAGTATGC TACGAGCGAG TGTCATTTCT TCAACGGGAC CGAGCGGGTG
 CGGTTCCTGC ACAGATACTT CCATAATGGA GAAGAGTTCG TGCGCTTCGA
 CAGCGACTGG GGCGAGTTCC GGGCGGTGAC CGAGCTGGGG CGGCAGGACG
 CCGAGTACTG GAACAGCCAG AAGGACTTGC TGGAGCGGAA GCGGGCTTCG
 GTGGACACGT ACTGCAGACA CAACTACGGG GGCGTGGAGA GTTTCACTGT
 GC*

>DL;BoLA-DRB3*6201
BoLA-DRB3*6201, 252 bases, EA9BDD62 checksum.
 TGGAGTATTT TAAGAGCGAG TGTCATTTCT TCAACGGGAC CGAGCGGGTG
 CGGTTCCTGG ACAGATCCTA CTATAATGGA GAAGAGAACG TGCGCTTCGA
 CAGCGACTGG GGCGAGTTCC GGGCGTTGAC CGAGCTGGGG CGGCCGGACG
 CCGAGTACTG GAACAGCCAG AAGGACTTGC TGGAGCGGAA GCGGGCCAAT
 GTGGACACGT ACTGCAGACA CAACTACGGG GTCGTGGAGA GTTTCACTGT
 GC*

>DL;BoLA-DRB3*6301
BoLA-DRB3*6301, 252 bases, 422954A6 checksum.
 TGGAGTATAC CAAGAAAGAG TGTCATTTCT TCAACGGGAC CGAGCGGGTG
 CGGTTCCTGG ACAGATACTT CCATAATGGA GAAGAGGTCG TGCGCTTCGA
 CAGCGACTGG GGCGAGTACC GGGCGGTGAC CGAGCTAGGG CGGCCGGACG
 CCGAGTACTG GAGCAGCCAG GAGATCCTGG AGCGGGCGCG GGCCGCGGTG
 GACACGTACT GCAGACACAA CTACGGGGTC GGTGAGAGTT TCACTGTGCA
 GC*

>DL;BoLA-DRB3*6401
BoLA-DRB3*6401, 252 bases, 599D01 checksum.
 TGGAGTATTA TAAGGGCGAG TGTCATTTCT TCAACGGGAC CGAGCGGGTG
 CGGTTCCTGG ACAGACACTT CTATAATGGA GAAGAGTACG TGCGCTTCGA
 CAGCGACTGG GGCGAGTTCC GGGCGGTGAC CGAGCTGGGG CGGCCGGACG
 CCAAGTACTG GAACAGCCAG AAGGACTTCC TGGAGCAGAA GCGGGCCGAG
 GTGGACAGGG TGTGCAGACA CAACTACGGG GGTGTGGAGA GTTTCACTGT
 GC*

>DL;BoLA-DRB3*6402
BoLA-DRB3*6402, 252 bases, BC9FFB83 checksum.
 TGGAGTATTA TAAGGGCGAG TGTCATTTCT TCAACGGGAC CGAGCGGGTG
 CGGTTCCTGG ACAGATTCTT CTATAATGGA GAAGAGTACG TGCGCTTCGA
 CAGCGACTTG GGCGAGTTCC GGGCGGTGAC CGAGCTGGGG CGGCCGGACG
 CCGAGTACTG GAACAGCCAG AAGGACTTCC TGGAGCAGAA GCGGGCCGAG
 GTGGACAGGG TGTGCAGACA CAACTACGGG GGTGTGGAGA GTTTCACTGT
 GC*

>DL;BoLA-DRB3*6501
BoLA-DRB3*6501, 252 bases, 7C65B82 checksum.
 TGGAGTATTT TAAGAGCGAG TGTCATTTCT TCAACGGGAC CGAGCGGGTG
 CGGTTCCTGG AGAGATCCTT CTATAATGGA GAAGAGAACG TGCGCTTCGA
 CAGCGACTGG GGCGAGTACC GGGCGTTGAC CGAGCTAGGG CGGCCGGACG
 CCAAGTACTG GAACAGCCAG AAGGACATGC TGGAGCGGAA GCGGGCCAAT
 GTGGACACGT ACTGCAGATA CAACTACGGG GTCGTGGAGA GTTTCACTGT
 GC*

>DL;BoLA-DRB3*6601
BoLA-DRB3*6601, 252 bases, 964673BE checksum.
 TGGAGTATTA TAAGAGCGAG TGTCATTTCT TCAACGGGAC CGAGCGGGTG
 CGGTACCTGG ACAGATCCTT CTATAATGGA GAAGAGTTCG TGCGCTTCGA
 CAGCGACTGG GGCGAGTACC GGGCGGTGAC CGAGCTAGGG CGGCCCGTCG
 CCGAGCACTG GAACAGCCAG AAGGACTTCC TGGAGCGGAA GCGGGCCAAT
 GTGGACACGT GTTGCAGACA CAACTACGGG GTCGGTGAGA GTTTCACTGT
 GC*

