>DL;BoLA-DQA*0101
BoLA-DQA*0101, 768 bases, D5265B76 checksum.
 ATGATCCTGA ACAGAGCCCT GATTTGGGGG GCCCTCGCCC TGACCACCAT
 GATGGGTCCC TCTGGGAGTG AAGACATTGT GGCTGACCAC ATTGGCGCCT
 ATGGCATAAA CGTCTACCAC ACATATGGTC CCTCTGGCTA CTATACCCAT
 GAATTTGATG GAGATGAAGA GTTCTACGTG GACCTGGAAA AGAGGGAGAC
 TGTCTGGCGT CTGCCTGTGT TTAGTAAATT TACAAGTTTT GACCCTCAGG
 GTGCGCTGAG AAACATAGCT ACAGCGAAGC ACAATTTGGA GGTCTTGATT
 CAAAGGTCCA ACTCTACTGC TGCTACCAAC AAGGTTCCTG AGATGACTGT
 GTTTCCCAAG TCTCCTGTAA TGCTGGGCCA GCCCAACACC CTCATCTGTC
 ACGTGGACAA CATCTTTCCT CCTGTGATCA ACATTACATG GTTGAGGAAC
 GGGCACTTGG TCATAGAGGG TATTTCTGAG ACCAGCTTCC TCTCCAAGGA
 TGATCATTCC TTCGCCAAGA TCAGTTACCT CACCTTCCTT CCTTCTGATG
 ATGATGTTTA TGACTGCAAA GTGGAGCACT GGGGCCTGGA TAAGCCACTG
 CTAAAACACT GGGAACCTGA GATTCCAGCC CCTATGTCAG AGCTGACAGA
 GACTGTGGTC TGTGCCTTGG GGTTGACCGT GGGCCTCGTG GGCATCGTGG
 TGGGCACTGT CCTCATCATC CGAGGTCTGC GCTCAGGTGG CCCCTCCAGA
 CACCAGGGGC CGTTGTGA*

>DL;BoLA-DQA*0102
BoLA-DQA*0102, 246 bases, 21E16FA1 checksum.
 GACCACATTG GCGCCTATGG CATAAACGTC TACCACACAT ATGGTCCCTC
 TGGCTACTAT ACCCATGAAT TTGATGGAGA TGAAGAGTTC TACGTGGACC
 TGGAAAAGAG GGAGACTGTC TGGCGTCTGC CTGTGTTTAG TAAATTTACA
 AGTTTTGACC CTCAGGGTGC GCTGAGAAAC ATAGCTACAG TGAAGCACAA
 TTTGGAGATC TTGATTCAAA GGTCCAACTC TACTGCTGCT ACCAAC*

>DL;BoLA-DQA*0103
BoLA-DQA*0103, 246 bases, A1436C33 checksum.
 GACCACATTG GTGCCTATGG CATAAACGTC TACCACACAT ATGGTCCCTC
 TGGCTACTAT ACCCATGAAT TTGATGGAGA TGAAGAGTTC TACGTGGACC
 TGGAAAAGAG GGAGACTGTC TGGCGTCTGC CTGTGTTTAG TAAATTTACA
 AGTTTTGACC CTCAGGGTGC GCTGAGAAAC ATAGCTACGA CGAAGCACAA
 TTTGGAGATC ATGATTCGAA GGTCCAACTC TACTGCTGCT ACCAAC*

>DL;BoLA-DQA*0201
BoLA-DQA*0201, 690 bases, 1A599AAF checksum.
 GTGGCTGACC ACATTGGCCG CTATGGCATA AACGTCTACC ACACATATGG
 TCCCTCTGGC TACTATACCC ATGAATTTGA TGGAGATGAA GAGTTCTACG
 TGGACCTGGA AAAGAGGGAG ACTGTCTGGA ATCTGCCTCT GTTTAGTAAA
 TTTAGACGTT TTGACCCTCA GGGTGCGCTG AGAAACATAG CTACAGTGAA
 GCACAATTTG GAGATCGTGA TTCAAAGGTC CAACTCTACT GCTGCTACCA
 ACAAGGTTCC TGAAGTGACT GTGTTTTCCA AGTCTCCCAT GATGCTGGGC
 CAGCCCAACA CCCTCATCTG TCACGTGGAC AACATCTTTC CTCCTGTGAT
 CAACATTACA TGGCTGAAGA ACGGGCACTT GGTCATAGAG GGTATTTCTG
 AGACCAGCTT CCTCTCCAAG GATGATCATT CCTTCTCCAA GATCAGTTAC
 CTCACCTTCC TTCCTTCTGA TGATGATGTT TATGACTGCA AAGTGGAGCA
 CTGGGGCCTG GATAAGCCGC TGCTAAAACA CTGGGAACCT GATATTCCAG
 CCCCTATGTC AGAGCTGACA GAGACTGTGG TCTGTGCCTT GGGGTTGACC
 GTGGGCCTCG TGGGCATCGT GGTGGGCACT GTCCTCATCA TCCGAGGTCT
 GCGCTCAGGC GGCCCCTCCA GAGACCAGGG GCCGTTGTGA*

>DL;BoLA-DQA*0202
BoLA-DQA*0202, 228 bases, 2ADE6664 checksum.
 GCGCCTATGG CATAAACGTC TACCACACAT ATGGTCCCTC TGGCTACTTT
 ACCCATGAAT TTGATGGAGA TGAAGAGTTC TACGTGGACC TGGAAAAGAG
 GGAGACTGTC TGGAATCTGC CTCTGTTTAG TAAATTTAGA CGTTTTGACC
 CTCAGGGTGC GCTGAGAAAC ATAGCTACAG TGAAGCACAA TTTGGAGATC
 GTGATTCAAA GGTCCAACTC TACTGCTG*

>DL;BoLA-DQA*0203
BoLA-DQA*0203, 246 bases, EE1C17FB checksum.
 GACCACATTG GCGCCTATGG CATAAACGTC TACCACACAT ATGGTCCCTC
 TGGCTACTAT ACCCATGAAT TTGATGGAGA TGAAGAGTTC TACGTGGACC
 TGGAAAAGAG GGAGACTGTC TGGAATCTGC CTCTGTTTAG TAAATTTAGA
 CGTTTTGACC CTCAGGGTGC GCTGAGAAAC ATAGCTACAG TGAAGCACAA
 TTTGGAGATC GTGATTCAAA GGTCCAACTC TACTGCTGCT ACCAAC*

>DL;BoLA-DQA*0204
BoLA-DQA*0204, 246 bases, 85A3E0DD checksum.
 GACCACATTG GTGCCTATGG CATAAACGTC TACCACACAT ATGGTCCCTC
 TGGCTACTAT ACCCATGAAT TTGATGGAGA TGAAGAGTTC TACGTGGACC
 TGGAAAAGAG GGAGACTGTC TGGAATCTGC CTCTGTTTAG TAAATTTAGA
 CGTTTTGACC CTCAGGGTGC GCTGAGAAAC ATAGCTACAG CGAAGCACAA
 TTTGGAGATC GTGATTCAAA GGTCCAACTC TACTGCTGCT ACCAAC*

>DL;BoLA-DQA*0301
BoLA-DQA*0301, 246 bases, F74662A5 checksum.
 GACCACATTG GCGCCTATGG CATAAACGTC TACCACTCAT ATGGTCCCTC
 TGGCTACTAT ACCCATGAAT TTGATGGAGA TGAAGAGTTC TACGTGGACC
 TGGAAAAGAG GGAGACTGTC TGGAATCTGC CTCTGTTTAG TAAATTTAGA
 CGTTTTGACC CTCAGGGTGC GCTGAGAAAC ATAGCTACGA CGAAGCACAA
 TTTGGAGATC ATGATGCAAA GGTCCAACTC TACTGCTGCT ACCAAC*

>DL;BoLA-DQA*0302
BoLA-DQA*0302, 221 bases, 31C47521 checksum.
 GCCTATGGCA TAAACGTCTA CCACTCATAT GGTCCCTCTG GCTACTATAC
 CCATGAATTT GATGGAGATG AAGAGTTCTA CGTGGACCTG GAAAAGAGGG
 AGACTGTCTG GAATCTGCCT CTGTTTAGTA AATTTAGACG TTTTGACCCT
 CGGGGTGCGC TGAGAAACAT AGCTACGACG AAGCACAATT TGGAGATCAT
 GATGCAAGGG TCCAACTCTA C*

>DL;BoLA-DQA*0401
BoLA-DQA*0401, 246 bases, E31668BC checksum.
 GACCACATTG GCGCCTATGG CATAAACGTC TACCACTCAT ATGGTCCCTC
 TGGCTACTAT ACCCATGAAT TTGATGGAGA TGAAGAGTTC TACGTGGACC
 TGGAAAAGAG GGAGACTGTC TGGAATCTGC CTCTGTTTAG TAAATTTAGA
 CGTTTTGACC CTCAGGGTGC GCTGAGAAAC ATAGCTACAG CGAAGCACAA
 TTTGGAGGTC TTGATTCAAA GGTCCAACTC TACTACTGCT ACCAAC*

>DL;BoLA-DQA*0801
BoLA-DQA*0801, 246 bases, FA202CE4 checksum.
 GACCACATTG GCGCCTATGG CATAAACGTC TACCACTCAT ATGGTCCCTC
 TGGCTACTAT ACCCATGAAT TTGATGGAGA TGAACAGTTC TACGTGGACC
 TGGAAAAGAG GGAGACTGTC TGGCGTCTGC CTGTGTTTAG TAAATTTGCA
 AGTTTTGACC CTCAGGGTGC GCTGAGAAAC ATAGCTACAG CGAAGCACAA
 TTTGGAGATT ATGATTCAAG AGTCCAACTC TACTGCTGCT ACCAAC*

>DL;BoLA-DQA*0802
BoLA-DQA*0802, 246 bases, 6C5D9F80 checksum.
 GACCACATTG GCGCCTATGG CATAAACGTC TACCACTCAT ATGGTCCCTC
 TGGCTACTAT ACCCATGAAT TTGATGGAGA TGAACAGTTC TACGTGGACC
 TGGAAAAGAG GGAGACTGTC TGGCGTCTGC ATGTGTTTAG TAAATTTGCA
 AGTTTTGACC CTCAGGGTGC GCTGAGAAAC ATAGCTACAG CGAAGCACAA
 TTTGGAGATT ATGATTCAAG AGTCCAACTC TACTGCTTCT ACCAAC*

>DL;BoLA-DQA*10011
BoLA-DQA*10011, 246 bases, DF9B0D7B checksum.
 GACCACATTG GCACCTATGG CATAAGCGTC TACCACACAT ATGGTCCCTC
 TGGCTACTAT ACCCATGAAT TTGATGGAGA TGAAGAGTTC TACGTGGACC
 TAGAAAAGAG GGAGACTGTC TGGCGTCTGC CTGTGTTTAG TAAATTTACA
 AGTTTTGACC CTCAGGGTGC GCTGAGAAAC ATAGCTATAG TGAAGCACAA
 TTTGGAGATC GTGATTCAAA GGTCCAACTC TACTGCTGCT ACCAAC*

>DL;BoLA-DQA*10012
BoLA-DQA*10012, 246 bases, D54C1174 checksum.
 GACCACATTG GCACCTATGG CATAAGCGTC TACCACACAT ATGGTCCCTC
 TGGCTACTAT ACCCATGAAT TTGATGGAGA TGAAGAGTTC TACGTGGACC
 TGGAAAAGAG GGAGACTGTC TGGCGTCTGC CTGTGTTTAG TAAATTTACA
 AGTTTTGACC CTCAGGGTGC GCTGAGAAAC ATAGCTATAG TGAAGCACAA
 TTTGGAGATC GTGATTCAAA GGTCCAACTC TACTGCTGCT ACCAAC*

>DL;BoLA-DQA*1002
BoLA-DQA*1002, 241 bases, 3645D85D checksum.
 TGACCACATT GGTGCCTATG GCATAAACGT CTACCACACA TATGGTCCCT
 CTGGCTACTA TACCCATGAA TTTGATGGAG ATGAAGAGTT CTACGTGGAC
 CTGGAAAAGA GGGAGACTGT CTGGCGTCTG CCTGTGTTTA GTAAATTTAC
 AAGTTTTGAC CCTCAGGGTG CGCTGAGAAA CATAGCTATA GTGAAGCACA
 ATTTGGATAT CGTGATTCAA AGGTCCAACT CTACTGCTGC T*

>DL;BoLA-DQA*1101
BoLA-DQA*1101, 246 bases, 8269B2CE checksum.
 GACCACATTG GCGCCTATGG CATAAACGTC TACCACACAT ATGGTCCCTC
 TGGCTACTAT ACCCATGAAT TTGATGGAGA TGAAGAGTTC TACGTGGACC
 TGGAAAAGAG GGAGACTGTC TGGCGTCTGC CTGTGTTTAG TAAATTTGCA
 ACTTTTGACC CTCAGGGTGC GCTGAGAAAC ATAGCTACGA TGAAGCACAA
 TTTGGAGATC GTGATTCAAA GGTCCAACTC TACTGCTGCT ACCAAC*

>DL;BoLA-DQA*12011
BoLA-DQA*12011, 768 bases, D511A2E9 checksum.
 ATGGTCCTGA ACAGAGCCCT GATTTTGGGG GCCCTCGCCC TGACCACCAT
 GATGAGTCCC TCTGGGAGTG AAGACATTGT GGCTGACCAC ATTGGCACCT
 ATGGCATAAG CGTCTACCAC ACATATGGTC CCTCTGGCTA CTATACCCAT
 GAATTTGATG GAGATGAAGA GTTCTACGTG GACCTGGAAA AGAGGGAGAC
 TGTCTGGCGT CTGCCTGTGT TTAGTAAATT TGCAACTTTT GACCCTCAGG
 GTGCGCTGAG AAACATAGCT ACGACGAAGC ACAATCTGGA GATCGTGATT
 CAAAGGTCCA ACTCTACTGC TGCTACCAAC AAGGTTCCTG AGGTGACTGT
 GTTTTCCAAG TCTCCCGTGA TGCTGGGTCA GCCCAACACT CTCATCTGTC
 ATGTGGACAA CATCTTTCCC CCTGTGATCA ACATCACATG GTTGAGGAAT
 GGGCACTCGG TCACAGAGGG AGTTTCTGAG ACCAGTTTTC TCATCAAGAG
 TGATTATTCT TTTCTCAAGA TCAATTATCT CACCTTCCTC CCTTCTGATG
 ATGACGTTTA TGACTGCAAA GTGGAGCACT GGGGTCTGGA TGAGCCACTT
 CTGAAACACT GGGAGCCTGA TATTCCAGCC CCTATGTCAG AGCTGACAGA
 GACTGTGGTC TGTGCCCTGG GGTTGACCGT GGGCCTCGTG GGCATCATGG
 TGGGCACCAT CCTCATCATC CAAGGTCTGC GCTCAGGTGG CCCCTCCAGA
 CACCAGGGGC CGTTGTGA*

>DL;BoLA-DQA*12012
BoLA-DQA*12012, 228 bases, C05FDD46 checksum.
 GCACCTATGG CATAAGCGTC TACCACACAT ATGGTCCCTC TGGCTACTAT
 ACCCATGAAT TTGATGGAGA TGAAGAGTTC TACGTGGACC TGGAAAAGAG
 GGAGACTGTC TGGCGTCTGC CTGTGTTTAG TAAATTTGCA ACTTTTGACC
 CTCAGGGTGC GCTGAGAAAC ATAGCTACGA CGAAGCACAA TTTGGAGATC
 GTGATTCAAA GGTCCAACTC TACTGCTG*

>DL;BoLA-DQA*12021
BoLA-DQA*12021, 768 bases, D0EE2150 checksum.
 ATGATCCTGA ACAGAGCCCT GATTTTGGGG GCCCTCGCCC TGACCACCAT
 GATGAGTCCC TCTGGGAGTG AAGACATTGT GGCTGACCAC ATTGGCACCT
 ATGGCATAAG CGTCTACCAC ACATATGGTC CCTCTGGCTA CTATACCCAT
 GAATTTGATG GAGATGAAGA GTTCTACGTG GACCTGGAAA AGAGGGAGAC
 TGTCTGGCGT CTGCCTGTGT TTAGTAAATT TGCAACTTTT GACCCTCAGG
 GTGCGCTGAG AAACATAGCT ACGATGAAGC ACAATTTGGA GATCGTGATT
 CAAAGGTCCA ACTCTACTGC TGCTACCAAC AAGGTTCCTG AGGTGACTGT
 GTTTTCCAAG TCTCCCGTGA TGCTGGGTCA GCCCAACACT CTCATCTGTC
 ATGTGGACAA CATCTTTCCC CCTGTGATCA ACATCACATG GTTGAGGAAT
 GGGCACTCGG TCACAGAGGG AGTTTCTGAG ACCAGTTTTC TCATCAAGAG
 TGATTATTCT TTTCTCAAGA TCAATTATCT CACCTTCCTC CCTTCTGATG
 ATGACGTTTA TGACTGCAAA GTGGAGCACT GGGGTCTGGA TGAGCCACTT
 CTGAAACACT GGGAGCCTGA TATTCCAGCC CCTATGTCAG AGCTGACAGA
 GACTGTGGTC TGTGCCCTGG GGTTGACCGT GGGCCTCGTG GGCATCATGG
 TGGGCACCAT CCTCATCATC CAAGGTCTGC GCTCAGGTGG CCCCTCCAGA
 CACCAGGGGC CGTTGTGA*

>DL;BoLA-DQA*12022
BoLA-DQA*12022, 246 bases, BDAD9FB3 checksum.
 GACCACATTG GCACCTATGG CATAAGCGTC TACCACACAT ATGGTCCCTC
 TGGCTACTAT ACCCATGAAT TTGATGGAGA TGAAGAGTTC TACGTGGACC
 TGGAAAAGAG GGAGACTGTC TGGCGTCTGC CTGTGTTTAG TAAATTTGCA
 ACTTTTGACC CTCAGGGTGC GCTGAGAAAC ATAGCTACGA TGAAGCACAA
 TTTGGAGATC GTGATTCAAA GGTCCAACTC TACAGCTGCT ACCAAC*

>DL;BoLA-DQA*1203
BoLA-DQA*1203, 686 bases, 22448156 checksum.
 CTGACCACAT TGGCACCTAT GGCATAAGCG TCTACCACAC ATATGGTCCC
 TCTGGCTACT ATACCCATGA ATTTGATGGA GATGAAGAGT TCTACGTGGA
 CCTGGAAAAG AGGGAGACTG TCTGGCGTCT GCCTGTGTTT AGTAAATTTG
 CAACTTTTGA CCCTCAGGGT GCGCTGAGAA ACATAGCTAC GTCGAAGCAC
 GATTTGGAGG TCTTGATTCA AAGGTCCAAC TCTACTGCTG CTACCAACAA
 GGTTCCTGAG GTGACTGTGT TTTCCAAGTC TCCCGTGATG CTGGGTCAGC
 CCAACACTCT CATCTGTCAT GTGGACAACA TCTTTCCCCC TGTGATCAAC
 ATCACATGGT TGAGGAATGG GCACTCGGTC ACAGAGGGAG TTTCTGAGAC
 CAGTTTTCTC ATCAAGAGTG ATTATTCTTT TCTCAAGATC AATTATCTCA
 CCTTCCTCCC TTCTGATGAT GACGTTTATG ACTGCAAAGT GGAGCACTGG
 GGTCTGGATG AGCCACTTCT GAAACACTGG GAGCCTGATA TTCCAGCCCC
 TATGTCAGAG CTGACAGAGA CTGTGGTCTG TGCCCTGGGG TTGACCGTGG
 GCCTCGTGGG CATCATGGTG GGCACCATCC TCATCATCCA AGGTCTGCGC
 TCAGGTGGCC CCTCCAGACA CCAGGGGCCG TTGTGA*

>DL;BoLA-DQA*1204
BoLA-DQA*1204, 242 bases, 8E26623D checksum.
 CTGACCACAT TGGCACCTAT GGCATAAGCA TCTACCACTC ATATGGTCCC
 TCTGGCTACT ATACCCATGA ATTTGATGGA GATGAAGAGT TCTACGTGGA
 CCTGGAAAAG AGGGAGACTG TCTGGCGTCT GCCTGTGTTT AGTAAATTTG
 CAACTTTTGA CCCTCAGGGT GCGCTGAGAA ACATAGCTAC GACGAAGCAC
 AATTTGGAGA TCGTGATTCA AAGGTCCAAC TCTACTGCTG CT*

>DL;BoLA-DQA*1301
BoLA-DQA*1301, 228 bases, 40A801A5 checksum.
 GCGCCTATGG CATAAACGTC TACCACTCAT ATGGTCCCTC TGGCTACTAT
 ACCCATGAAT TTGATGGAGA TGAACAGTTC TACGTGGACC TGGAAAAGAA
 GGAGACTGTC TGGCGTCTGC CTGTGTTTAG TAAATTTGCA ACTTTTGACC
 CTCAGGGTGC GCTGAGAAAC ATAGCTGTGG GGAAACAGAC TTTGGAGGTC
 ATGATTCGAA GGTCCAACTC TACTGCTG*

>DL;BoLA-DQA*1302
BoLA-DQA*1302, 221 bases, 515F18F2 checksum.
 GCCTATGGCA TAAACGTCTA CCACACATAT GGTCCCTCTG GCTACTATAC
 CCATGAATTT GATGGAGATG AACAGTTCTA CGTGGACCTG GAAAAGAAGG
 AGACTGTCTG GCGTCTGCCT GTGTTTAGTA AATTTGCAAC TTTTGACCCT
 CAGGGTGCGC TGAGAAACAT AGCTGTGGGG AAACAGACTT TGGAGGTCAT
 GATTCGAAGG TCCAACTCTA C*

>DL;BoLA-DQA*1401
BoLA-DQA*1401, 246 bases, 6D0970F7 checksum.
 GACCACATTG GCGCCTATGG CATAAACGTC TACCACTCAT ATGGTCCCTC
 TGGCTACTAT ACCCATGAAT TTGATGGAGA TGAAGAGTTC TACGTGGACC
 TGGAAAAGAG GGAGACTGTC TGGCGTCTGC CTGTGTTTAG TAAATTTGCA
 AGTTTTGACC CTCAGGGTGC GCTGAGAAAC ATAGCTGTGG GGAAACGGAC
 TTTGGAGGTC ATGATTCGAA GGTCCAACTC TACTGCTGCT ACCAAC*

>DL;BoLA-DQA*2001
BoLA-DQA*2001, 221 bases, F770A0EE checksum.
 TCCTATGGCA CAGAGGTCTA CCAATCTCAT GGTCCCTCTG GCCAGTACAC
 CCAGGAATTT GATGGAGACG AGATGTTTTA TGTGGACCTG GGGAAGAAGG
 AGACTGTCTG GAGGCTGCCT AGTTTTAGCC AGTTTGCAGG TTTTGACCCA
 CAAGCTGCAC TGAGTGAAAT AGCTACATCA AAACACAACT TGGATGTCCT
 GACTAAACGC TCCAACTTTA C*

>DL;BoLA-DQA*2002
BoLA-DQA*2002, 246 bases, 433994D9 checksum.
 GACCACGTTG GCTCCTATGG CACAGAGGTC TACCAATCTC ATGGTCCCTC
 TGGCCAGTAC ACCCAGGAAT TTGATGGAGA CGAGATGTTT TATGTGGACC
 TGGGGAAGAA GGAGACTGTC TGGAGGCTGC CTACGTTTAG CCAGTTTGCA
 GGTTTTGACC CACAGGCTGC ACTGAGTGAA ATAGCTACAT CAAAACACAA
 CTTGGATGTC CTGACTAAAC GCTCCAACTT TACCCCTGTT ATCAAT*

>DL;BoLA-DQA*2101
BoLA-DQA*2101, 246 bases, 22A2BFCE checksum.
 GACCACGTTG GCTCCTATGG CACAGAGGTC TACCAATCTC ATGGTCCCTC
 TGGCCAGTAC ACCCAGGAAT TTGATGGAGA CGAGATGTTT TATGTGGACC
 TGGGGAAGAA GGAGACTGTC TGGAGGCTGC CTATTTTTAG CCAGTTTGCA
 GGTTTTGACC CACAGTTTGC ACTGAGTGAA ATAGCTACAT CAAAACACAA
 CTTGGATGTC CTGACTAAAC GCTCCAACTT TACCCCTGTT ATCAAT*

>DL;BoLA-DQA*2201
BoLA-DQA*2201, 768 bases, 1A7639E9 checksum.
 ATGGTCCTGA ACAGAGCTCT GATTCTGGGG GCCCTCGCCC TGACCACCAT
 GATGAGCCCC AATGGAGGTG AAGACATTGT GGCTGACCAC GTTGGCTCCT
 ATGGCACAGA GGTCTACCAA TCTCATGGTC CCTCTGGCCA GTACACCCAG
 GAATTTGATG GAGACGAGAT GTTTTATGTG GACCTGGGGA AGAAGGAGAC
 TGTCTGGAGG CTGCCTATGT TTAGCCAGTT TGCAGGTTTT GACCCACAGG
 CTGCACTGAG TGAAATAGCT ACATCAAAAC ACAACTTGGA TGTCCTGACT
 AAACGCTCCA ACTTTACCCC TGTTATCAAT GAGGTTCCAG AGGTGACTGT
 GTTTTCCAAG TCTCCCGTGA TCCTGAGTCA GCCCAACACC CTCATCTGTC
 ACGTGGACAA CATTTTTCCC CCTGTGATCA ACATTACATG GCTGAAGAAT
 GGGCATGCAG TCACAGAGGG TGTTTCTGAG ACCAGCTTCC TCCCTAAGGA
 TGATCATTCT TTCCTCAAGA TTGGTTATCT CACCTTCCTC CCTTCTGATA
 ATGACATTTA TGACTGCAAA GTGGAGCACT GGGGTCTGGA TGAGCCACTT
 CTGAAACACT GGGAGCCTGA GGTTCCAGCC CCTATGTCAG AGCTGACAGA
 GACTGTGGTC TGTGCCCTGG GGTTGACCGT GGGCCTTGTG GGTATCGTGG
 TGGGCACCAT CTTCATCATC CAAGGCCTGC GCTCAGGTGG GACCTCCAGA
 CACCAGGGTC CCTTGTGA*

>DL;BoLA-DQA*22021
BoLA-DQA*22021, 768 bases, 52C39108 checksum.
 ATGGTCCTGA ACAGAGCTCT GATTCTAGGG GCCCTCGCCC TGACCACCAT
 GATGAGCCCC AGTGGAGGTG AAGACATTGT GGCTGACCAC GTTGGCTCCT
 ATGGCACAGA GGTCTACCAA TCTCATGGTC CCTCTGGCCA GTACACCCAG
 GAATTTGATG GAGACGAGAT GTTTTATGTG GACCTGGGGA AGAAGGAGAC
 TGTCTGGAGG CTGCCTATGT TTAGCCAGTT TGCAGGTTTT GACCCACAGG
 CTGCACTGAG TGAAATAGCT ACAGCAAAAC ACAACTTGGA TGTCCTGACT
 AAACGCTCCA ACTTTACCCC TGTTATCAAT GAGGTTCCAG AGGTGACTGT
 GTTTTCCAAG TCTCCCGTGA TGCTGGGTCA GCCCAACACC CTCATCTGTC
 ACGTGGACAA CATTTTTCCC CCTGTGATCA ACATTACATG GCTGAAGAAC
 GGGCATGCAG TCACAGAGGG TGTTTCTGAG ACCAGCTTCC TCCCTAAGGA
 TGATCATTCT TTCCTCAAGA TTGGTTATCT CACCTTCCTC CCTTCTGATA
 ATGACATTTA TGACTGCAAA GTGGAGCACT GGGGTCTGGA TGAGCCACTT
 CTGAAACACT GGGAGCCTGA GGTTCCAGCC CCTATGTCAG AGCTGACAGA
 GACTGTGGTC TGTGCCCTGG GGTTGACCGT GGGCCTTGTG GGTATCGTGG
 TGGGCACCAT CTTCATCATC CAAGGCCTGC GCTCAGGTGG GGCCTCCAGA
 CACCAGGGTC CCTTGTGA*

>DL;BoLA-DQA*22022
BoLA-DQA*22022, 221 bases, CDAFB946 checksum.
 TCCTATGGCA CAGAGGTCTA CCAATCTCAT GGTCCCTCTG GCCAGTACAC
 CCAGGAATTT GATGGAGACG AGATGTTTTA TGTGGACCTG GGGAAGAAAG
 AGACTGTCTG GAGACTGCCT ATGTTTAGCC AGTTTGCAGG GTTTGACCCA
 CAGGCTGCAC TGAGTGAAAT AGCTACAGCA AAACACAACT TGGATGTCCT
 GACTAAACGC TCCAACTTTA C*

>DL;BoLA-DQA*22023
BoLA-DQA*22023, 246 bases, EA26BC5D checksum.
 GACCACGTTG GCTCCTATGG CACAGAGGTC TACCAATCTC ATGGTCCCTC
 TGGCCAGTAC ACCCAGGAAT TTGATGGAGA CGAGATGTTT TATGTGGACC
 TGGGGAAGAA AGAGACTGTC TGGAGGCTGC CTATGTTTAG CCAGTTTGCA
 GGGTTTGACC CACAGGCTGC ACTGAGTGAA ATAGCTACAG CAAAACACAA
 CTTGGATGTC CTGACTAAAC GCTCCAACTT TACCCCTGTT ATCAAT*

>DL;BoLA-DQA*22031
BoLA-DQA*22031, 246 bases, EFBC4924 checksum.
 GACCACGTTG GCTCCTATGG CACAGAGGTC TACCAATCTC ATGGTCCCTC
 TGGCCAGTAC ACCCAGGAAT TTGATGGAGA CGAGCTGTTT TATGTGGACC
 TGGGGAAGAA AGAGACTGTC TGGAGGCTGC CTATGTTTAG CCAGTTTGCA
 GGGTTTGACC CACAGGCTGC ACTGAGTGAA ATAGCTACAG CAAAACACAA
 CTTGGATGTC CTGACTAAAC GCTCCAACTT TACCCCTGTT ATCAAT*

>DL;BoLA-DQA*22032
BoLA-DQA*22032, 221 bases, 10C14DE1 checksum.
 TCCTATGGCA CAGAGGTCTA CCAATCTCAT GGTCCCTCTG GCCAGTACAC
 CCAGGAATTT GATGGAGACG AGCTGTTTTA TGTGGACCTG GGGAAGAAGG
 AGACTGTCTG GAGGCTGCCT ATGTTTAGCC AGTTTGCAGG GTTTGACCCA
 CAGGCTGCAC TGAGTGAAAT AGCTACAGCA AAACACAACT TGGATGTCCT
 GACTAAACGC TCCAACTTTA C*

>DL;BoLA-DQA*2204
BoLA-DQA*2204, 246 bases, 2DB2CAD2 checksum.
 GACCACGTTG GCTCCTATGG CACAGAGGTC TACCAATCTC ATGGTCCCTC
 TGGCCAGTAC ACCCAGGAAT TTGATGGAGA CGAGATGTTT TATGTGGACC
 TGGGGAAGAA GGAGACTGTC TGGAGGCTGC TTATGTTTAG CCAGTTTGCA
 GGTTTTGACC CACAGGCTGC ACTGAGTGAA ATAGCTACAG CAAAACACAA
 CTTGGATGTC CTGACTAAAC GCTCCAACTT TACCCCTGTT ATCAAT*

>DL;BoLA-DQA*2205
BoLA-DQA*2205, 221 bases, E70B376C checksum.
 TCCTACGGCA CAGAGGTCTA CCAATCTCAT GGTCCCTCTG GCCAGTACAC
 CCAGGAATTT GATGGAGACG AGATGTTTTA TGTGGACCTG GGGAAGAAGG
 AGACTGTCTG GAGGCTGCCT ATGTTTAGCC AGTTTGCAGG TTTTGCCCCA
 CAGGCTGCAC TGAGTGAAAT AGCTACATCA AAACACAACT TGGATGTCCT
 GACTAAACGC TCCAACTTTA C*

>DL;BoLA-DQA*2207
BoLA-DQA*2207, 227 bases, 721B994 checksum.
 CGCAGAGTTC TACCAATCTC ATGGTCCCTC TGGCCAGTAC ACCCAGGAAT
 TTGATGGAGA CGAGCTGTTT TATGTGGACC TGGGGAAGAA AGAGACTGTC
 TGGAGGCTGC CTATGTTTAG CCAGTTTGCA GGGTTTGACC CACAGGCTGC
 ACTGAGTGAA ATAGCTACAG CAAAACACAA CTTGGATGTC CTGACTAAAC
 GCTCCAACTT TACCCCTGTT ATCAATG*

>DL;BoLA-DQA*2301
BoLA-DQA*2301, 221 bases, 2B51FB33 checksum.
 TCCTATGGCA TAGACTTCTA CCAATCTCAT GGTCCCTCTG GCCAGTACAT
 CCATGAATTT GATGGAGACG AGATGTTTTA TGTGGATCTG GGGAAGAAGG
 AGACTGTCTG GAGGCTGCCT ATGTTTGGTG AATTAACAGG TTTTGACCCG
 CAAGGTGCAC TGAGGAACAT AGCTACAGAA AAACACAACT TGGATATCTT
 GACTAAATGC TCCAACTTTA C*

>DL;BoLA-DQA*2401
BoLA-DQA*2401, 246 bases, 176F718E checksum.
 GACCACGTTG GCTCCTATGG CACAGAGGTC TACCAATCTC ATGGTCCCTC
 TGGCCAGTAC ACCCACGAAT TTGATGGAGA CGAGCTGTTT TATGTGGACC
 TGGGGAAGAA GGAGACTGTC TGGAGGCTGC CTATGTTTGG TGATTTAACA
 AGTTTTGACC CACAGGGTGC ACTGAGTGAA ATAGCTACAT CAAAACACAA
 TTTGGATATC CTGACTAGAC GCTCCAACTT TACCCCTGCC ATCAAC*

>DL;BoLA-DQA*25011
BoLA-DQA*25011, 243 bases, 6A9FA2B7 checksum.
 GACCACGTTG GCACTTATGG CACAGACTTC TACCAATCTC ATGGTCCTTC
 TGGCCAGTAC ATCCACCAAT TTGATGGAGA CGAGGAGTTT TATGTGGACC
 TGGAGAAGGA AGAGGCTGTC TGGAGGCTGC CTATGTTTGA TAAATTACGT
 TTCCACCCGC AAGGTGCACT GAGAAACATA GCTATAGCGA AACACAACTT
 GGATGTTCTG ACAAAGCTCT ACAACTTTAC CCCTGTTATC AAT*

>DL;BoLA-DQA*25012
BoLA-DQA*25012, 243 bases, F0B33597 checksum.
 GACCACGTTG GCACTTATGG CACAGACTTC TACCAATCTC ATGGTCCTTC
 TGGCCAGTAC ATCCACCAAT TTGATGGAGA CGAGGAGTTT TATGTGGACC
 TGGAGAAGGA AGAGGCTGTC TGGAGGCTGC CTATGTTTGA TAAATTACGT
 TTTCACCCGC AAGGTGCACT GAGAAACATA GCTATAGCGA AACACAACTT
 GGATGTTCTG ACAAAACTCT ACAACTTTAC CCCTGTTATC AAT*

>DL;BoLA-DQA*2502
BoLA-DQA*2502, 243 bases, F68B63A0 checksum.
 GACCACGTTG GCACTTATGG CGCAGACTTC TACCAATCTC ATGGTCCCTC
 TGGCCAGTAC ATCCACCAAT TTGATGGAGA CGAGGAGTTT TATGTGGACC
 TGGAGAAGGA AGAGGCTGTC TGGAGGCTGC CTATGTTTGA TAAATTACGT
 TTTCACCCGC AAGGTGCACT GAGAAACATA GCTATAGCGA AACACAACCT
 GGATGTTCTG ACAAAACTCT ACAACTTTAC CCCTGTTATC AAT*

>DL;BoLA-DQA*2601
BoLA-DQA*2601, 221 bases, 907BE9C9 checksum.
 ACTTATGGCA CAGACTTCTA CCAATCTCAT GGTCCTTCTG GCCAGTACAT
 CCACCAATTT GATGGAGACG AGGAGTTTTA TGTGGACCTG GAGAAGGAAG
 AGGCTGTCTG GAGGCTGCCT ATGTTTGATA AATTAAGACG TTTTCACCCG
 CAAGGTGCAC TGAGAGACAT AGCTGTAGCG AAACACAACT TGGATGTCCT
 GACTAAACGC TACAACTTTA C*

>DL;BoLA-DQA*2602
BoLA-DQA*2602, 221 bases, DD05813B checksum.
 ACTTATGGCA CAGACTTCTA CCAATCTCAT GGTCCTTCTG GCCAGTACAT
 CCACCAATTT GATGGAGACG AGGAGTTTTA TGTGGACCTG GAGAAGGAAG
 AGGCTGTCTG GAGGCTGCCT ATGTTTGATA AATTAAGACG TTTTCACCCG
 CAAGGTGCAC TGAGAAACAT AGCTGTAGCG AAACACAACT TGGATGTCCT
 GACTAAACGC TACAACTTTA C*

>DL;BoLA-DQA*2603
BoLA-DQA*2603, 234 bases, B989231C checksum.
 ACTTATGGCA CAGACTTCTA CCAATCTCAT GGTCCTTCTG GCCAGTACAT
 CCACCAATTT GATGGAGACG AGGAGTTTTA TGTGGACCTG GAGAAGGAAG
 AGGCTGTCTG GAGGCTGCCT ATGTTTGATA AATTAAGACG TTTTCACCCG
 CAAGGTGCAC TGAGAAACAT AGCTATAGCG AAACACAACT TGGATGTTCT
 GACAAAACTC TACAACTTTA CCCCTGTTAT CAAT*

>DL;BoLA-DQA*27011
BoLA-DQA*27011, 246 bases, 58734A20 checksum.
 GACCACATTG GCACCTACGG TGCAGACTTC TACCAATCTC ATGGTCCCTC
 TGGCCAGTAC ATCCATGAAT TTGATGGAGA TGAGTTGTTT TATGTGGACC
 TGGGGAAGAA GGAGACTGTC TGGCAGCTGC CTATGTTTGG TGAATTAACA
 AGTTTTGAAG CACAAGATGC GCTGAATGAA ATAGCTAAAG CAAAACACAC
 CTTGGATGTC CTGACTAAAC GCTCCAACTT TACCCCTGTT ATCAAT*

>DL;BoLA-DQA*27012
BoLA-DQA*27012, 221 bases, BA248E39 checksum.
 ACCTATGGCG CAGACTTCTA CCAATCTCAT GGTCCCTCTG GCCAGTACAT
 CCACGAATTT GATGGAGACG AGTTGTTTTA TGTGGACCTG GGGAAGAAGG
 AGACTGTCTG GCAGCTGCCT ATGTTTGGTG AATTAACAAG TTTTGAAGCA
 CAAGATGCGC TGAATGAAAT AGCTAAAGCA AAACACACCT TGGATGTCCT
 GACTAAACGC TCCAACTTTA C*

>DL;BoLA-DQA*2702
BoLA-DQA*2702, 248 bases, D9071355 checksum.
 CTGACCACAT TGGCACCTAT GGCGCAGAAT TCTACCAATC TCATGGTCCC
 TCTGGCCAGT ACATCCACGA ATTTGATGGA GATGAGTTGT TTTATGTGGA
 CCTGGGGAAG AAGGAGACTG TCTGGCAGCT GCCTATGTTT GGTGAATTAA
 CAAGTTTTGA AGCACAAGAT GCGCTGAATG AAATAGCTAA AGCAAAACAC
 ACCTTGGATG TCCTGACTAA ACGCTCCAAC TTTACCCCTG TTATCAAT*

>DL;BoLA-DQA*2801
BoLA-DQA*2801, 228 bases, 6F650A68 checksum.
 GCATCTATGG CATAAGCGTA TATCAGTCTT ATGGTCCCTC TGGCCAGTAC
 ACCCATGAAT TTGATGGAGA TGAGCAGTTC TATGTGGACC TGGAGAAGAA
 GGAGACTGCC TGGCAGCTGC CCCTATTTAG CAGAATGTTA AGTTTTGACC
 CACAGTTAGC ACTGAGAAAC ATAGCTATCA TGAAACTTCA TGTGGACTTC
 CTGACTAAAT TCTCCAACTC TACTGCTG*

