>P1;IPD:MHC03166
IPD:MHC03166 BoLA-N*00101, 354 bases, C48E4186 checksum.
 LLLSGVLVLT ETRAGSHSMR YFSTAVSRPG LGEPRYLEVG YVDDTQFVRF
 DSDAPNPRME PRARWVEQEG PEYWDRETQR AKGNAQFFRV SLNNLRGYYN
 QSEAGSHTLQ WMSGCYVGPD GRLRRGFMQF GYDGRDYLAL NEDLRSWTAV
 ETMAQISKRK MEAAGEAEVQ RNYLEGRCVE WLRRYLENGK DTLLRADPPK
 AHVTRHPISG REVTLRCWAL GFYPEEISLT WQRNGEDQTQ DMELVETRPS
 GDGNFQKWAA LLVPSGEEQK YTCQVQHEGL QEPLTLKWEP PQPSFLTMGI
 IVGLVLLVVT GAVVAGVVIC MKKRSGEKRG TYIQASSSDS AQGSDVSLTV
 PKVX*

>P1;IPD:MHC03167
IPD:MHC03167 BoLA-N*00102, 348 bases, 4D708C53 checksum.
 LVLTETRAGS HSMRYFSTAV SRPGLGEPRF ISVGYVDDTQ FVRFDSDAPN
 PRMEPRARWV EQEGPEYWDR ETQRAKGNAQ FFRVSLNNLR GYYNQSEAGS
 HTLQWMSGCY VGPDGRLRRG FMQFGYDGRD YLALNEDLRS WTAVETMAQI
 SKRKMEAAGE AEVQRNYLEG RCVEWLRRYL ENGKDTLLRA DPPKAHVTRH
 PISGREVTLR CWALGFYPEE ISLTWQRNGE DQTQDMELVE TRPSGDGNFQ
 KWAALLVPSG EEQKYTCQVQ HEGLQEPLTL KWEPPQPSFL TMGIIVGLVL
 LVVTGAVVAG VVICMKKRSG EKRGTYIQAS SSDSAQGSDV SLTVPKVX*

>P1;IPD:MHC03168
IPD:MHC03168 BoLA-N*00103, 348 bases, 357B1E23 checksum.
 LVLTETRAGS HSMRYFSTAV SRPGLGEPRF IIVGYVDDTQ FVRFDSDAPN
 PRMEPRARWV EQEGPEYWDR ETQRAKGNAQ FFRVSLNNLR GYYNQSEAGS
 HTLQWMSGCY VGPDGRLRRG FMQFGYDGRD YLALNEDLRS WTAVETMAQI
 SKRKMEAAGE AEVQRNYLEG RCVEWLRRYL ENGKDTLLRA DPPKAHVTRH
 PISGREVTLR CWALGFYPEE ISLTWQRNGE DQTQDMELVE TRPSGDGNFQ
 KWAALLVPSG EEQKYTCQVQ HEGLQEPLTL KWEPPQPSFL TMGIIVGLVL
 LVVTGAVVAG VVICMKKRSG EKRGTYIQAS SSDSAQGSDV SLTVPKVX*

>P1;IPD:MHC03169
IPD:MHC03169 BoLA-N*00201, 356 bases, 53FB5A18 checksum.
 LLLLLSGVLV LTETVAGSHS MRYFLTAVSR PGFGEPRYLE VGYVDDTQFV
 RFDSDAPNPR MEPRARWVEQ EGPEYWDQET RKAKGNAQFF RVSLNNLRGY
 YNQSEAGSHT LQLMSGCYVG PDGRLRRGFM QFGYDGRDYL ALNEDLRSWT
 AVETVAQISK RKMEAAGEAE VQRNYLEGRC VEWLRRYLEN GKDTLLRADP
 PKAHVTHHPI SDREVTLRCW ALGFYPEEIS LTWQRNGEDQ TQDMELVETR
 PSGDGNFQKW VALVVPSGEE QRYTCRVQHE GLQEPLTLRW EPPQPSFLTM
 GIIVGLVLLV VTGAVVAGVV VCMKKRSGEK RGTYIQASSS DSAQGSDVSL
 TVPKVX*

>P1;IPD:MHC03170
IPD:MHC03170 BoLA-N*00301, 353 bases, D40691A8 checksum.
 QLLSGALVLT ETLAGSHSLR YFLTAVSRPG VREPRFIIVG YVDDLQFVRF
 DSDAGDPRVE PRARWVEKEG PEYWDEETWR AKDHAQFFRR GLNALRGYYN
 QSEAGSHTFQ EMYGCYVGPD GRLLRGYEQF GYEGRDYIAL NGDLHSWTAA
 DTAAQISKRK WEAAGSTDFY RNYLEGECVE WLRRYLENGK DTLLRADPPK
 AHVTHHPISE REVTLRCWAL GFYPEEISLT WQHDGEDQTQ DMELVETRPS
 GDGTFQKWVA LVVPSGEEQR YTCRVQHEGL QEPLTLRWEP PQTSFLTMGI
 IVGLVLLVTG AVVAGFVIWM KKRSGEKGGN YIQASSSASA RGSDVSLTVP
 KVX*

>P1;IPD:MHC03171
IPD:MHC03171 BoLA-N*00401, 361 bases, 31C5B206 checksum.
 MGPRALLLLL SGVLILTETR AGSHSLRYFS TAVSRPGLGE PRYLEVGYVD
 DTQFVQFDSD APNPRMEPRA RWVEQEGPEY WDRNTRNAKG NAQSFRVNLN
 TLRGYYNQSE AGSHTLQWMS GCDVGPDGAL RRGFMQYGYD GRDYLALNED
 LRSWTAGETE AQITKRKWEA AGYAEVQRNY LEGECVEWLR RYLENGKDTL
 LRADPPKAHV THHPISGREV TLRCWALGFY PEEISLTWQH DGEDQTQDME
 LVETRPSGDG TFQKWAALVV PSGDEQRYTC RVQHEGLQEP LTLRWEPPQP
 SFLTMGIIVG LVLLVVTGAV VAGVVICMKK RSGEKGGNYI QASSSDSAQG
 SDVSLTVPKV X*

>P1;IPD:MHC03172
IPD:MHC03172 BoLA-N*00402, 361 bases, 91561960 checksum.
 MGPRALLLLL SGVLVLTETR AGSHSLRYFS TAVSRPGFGE PRYLEVGYVD
 DTQFVQFDSD APNPRMEPRA RWVEQEGPEY WDRNTRNAKG NAQSFRVNLN
 TLRGYYNQSE AGSHTLQWMS GCDVGPDGRL RRGFMQYGYD GRDYLALNED
 LRSWTAGETE AQITKRKWEA AGYAEVQRNY LEGECVEWLR RYLENGKDTL
 LRADPPKAHV AHHPISDREV TLRCWALGFY PEEISLTWQH DGEDQTQDME
 LVETRPSGDG TFQKWAALVV PSGDEQRYTC RVQHEGLQEP LTLRWEPPQP
 SFLTMGIIVG LVLLVVTGAV VAGVVICMKK RSGEKGGNYI QASGSDSAQG
 SDVSLTVPKV X*

>P1;IPD:MHC03173
IPD:MHC03173 BoLA-N*00501, 362 bases, 8810185E checksum.
 MRVMRPRTLL LLLSGVLVLT ETLAGSHSLR YFYTGVSRPG LGEPRFIAVG
 YVDDTQFVRF DSDAPNPREE PRVPWMEQEG PEYWDRNTRI YKDTAQIFRV
 DLNTLRGYYN QSETGSHNIQ AMYGCDVGPD GRLLRGFWQF GYDGRDYIAL
 NEELRSWTAA DTAAQITKRK WEAAGAAETW RNYLEGECVE WLRRYLENGK
 DTLLRADPPK AHVTHHSISD REVTLRCWAL GFYPEEISLT WQREGEDQTQ
 DMELVETRPS GDGTFQKWAA LVVPSGEEQR YTCRVQHEGL QEPLTLRWEP
 PQTSFLIMGI IVGLVLLVVA LVAGAVIWRK KRSGEKGRIY TQAASSDSAQ
 GSDVSLTVPK VX*

>P1;IPD:MHC03174
IPD:MHC03174 BoLA-N*00601, 353 bases, 5ED9F8A2 checksum.
 MLLLSGVLVL TETVAGSHSL RYFSTAVSRP GLGEPRFIAV GYVDDTQFTR
 FDSDAPNPRE EPRAPWMEQE GLEYWDRNTR IYKDTAQTFR VYLNTLRGYY
 NQSEAGSHTL QWMSGCDVGP GGRLLRGFMQ FGYDGRDYIA LNQDLRSWTA
 ADTAAQITKR KWEAADNAES ERNYLEGECV EWLRRYLENG KDTLLRADPP
 KAHVTHHPIS DREVTLRCWA LGFYPEEISL TWQRNGEDQT QYMELVETRP
 SGDGTFQKWA ALVVPPGEEQ RYTCRVQHEG LQEPLTLRWE PPQTSFLIMG
 IIVGLVLLVV ALVAGAVIWR KKRSGEKGRI YTQAASSDST QGSDVSLTVP
 KAV*

>P1;IPD:MHC02984
IPD:MHC02984 BoLA-N*00602, 354 bases, A1C073FC checksum.
 LLLLLSGVLV LTETVAGSHS LRYFSTAVSR PGLGEPRFIA VGYVDDTQFT
 RFDSDAPNPR EEPRAPWMEQ EGLEYWDRNT RIYKDTAQTF RVYLNTLRGY
 YNQSEAGSHT LQWMSGCDVG PGGRLLRGFM QFGYDGRDYI ALNQDLRSWT
 AADTAAQITK RKWEAADNAE SERNYLEGEC VEWLRRHLEN GKDTLLRADP
 PKAHVTHHPI SDREVTLRCW ALGFYPEEIS LTWQRNGEDQ TQYMELVETR
 PSGDGTFQKW AALVVPPGEE QRYTCRVQHE GLQEPLTLRW EPPQTSFLIM
 GIIVGLVLLV VALVAGAVIW RKKRSGEKGR IYTQAASSDS TQGSDVSLTV
 PKAV*

>P1;IPD:MHC03175
IPD:MHC03175 BoLA-N*00701, 314 bases, B180C91A checksum.
 VGYVDDTQFV RFDSDAPDPR KEPRAPWIEK EGPEYWDRET RISKENTLVY
 RGSLNNLRGY YNQSEAGSHT FQQMYGCDVG PDGRLLRGFK QFAYDSRDYI
 ALNEELRSWT AADTAAQITK RKWEAAGAAE TWRNYLEGEC VEWLRRYLEN
 GKDTLLRADP PKAHVTHHPI SDREVTLRCW ALGFYPKEIS LTWQRNGEDQ
 TQDMELVETR PSGDGNFQKW AALVVPSGEE QRYTCHVQHE GLQEPLTLRW
 EPPQTSFLIM GIIVGLVLLV VAVVAGAVIW RKKRSGEKRQ TYTQAASGDS
 DQGSDVSLTV PKVX*

>P1;IPD:MHC03176
IPD:MHC03176 BoLA-N*00801, 354 bases, 45251495 checksum.
 LLLLLSGVLV LTETLAGSHS LRYFLTAVSR PGLGEPRFII VGYVDDTQFV
 RFDSNTPNPR MEPRARWVEK EGPEYWDRET RNSKETAQTF RANLNTALGY
 YNQSEAGSHT VQEMYGCDVG PDGRLLRGFM QDAYDGRDYI ALNEDLRSWT
 AADTAAQITK RKWEAAGDAE TWRNYLEGRC VEWLRRYLEN GKDALLRADP
 PKAHVTHHSI SEREVTLRCW ALGFYPEEIS LTWQRDGEDQ TQDMELVETR
 PSGDGTFQKW AALAVPSGEE QRYTCRVQHE GLQEPLTLRW EPPQTSFLTM
 GIIVGLVLLV VAVVAGAVIW RKKRSGEKGR IYTQAASSDS TQGSDVSLTV
 PKVX*

>P1;IPD:MHC02986
IPD:MHC02986 BoLA-N*00802, 354 bases, 4C796A1C checksum.
 LLLLLSGVLV LTETLAGSHS LRYFLTAVSR PGLGEPRFII VGYVDDTQFV
 RFDSNTPNPR MEPRARWVEK EGPEYWDRET RNSKETAQTF RANLNTALGY
 YNQSEAGSHT VQEMYGCDVG PDGRLLRGFM QDAYDGRDYI ALNEDLRSWT
 AADTAAQITK RKWEAAGDAE TWRNYLEGRC VEGLRRYLEN GKDALLRADP
 PKAHVTHHSI SEREVTLRCW ALGFYPEEIS LTWQRDGEDQ TQDMELVETR
 PSGDGTFQKW AALAVPSGEE QRYTCRVQHE GLQEPLTLRW EPPQTSFLTM
 GIIVGLVLLV VAVVAGAVIW RKKRSGEKGR IYTQAASSDS TQGSDVSLTV
 PKVX*

>P1;IPD:MHC03177
IPD:MHC03177 BoLA-N*00901, 359 bases, F7054F5B checksum.
 MGPRTLFVLL LGALALTETR AGSHSLRYFY TAVSRPGLGE PRFISVGYVD
 DTQFVRFDSD APDPRMEPRA PWIEKEGPEY WDRETRISKE NTLVYRGSLN
 NLRGYYNQSE AGSHTLQLMY GCDVGPDGRL LRGYRQDAYD SRDYIALNEE
 LRSWTAADTA AQITKRKWEA EGYAESLRNY LEGRCVEWLR RYLENGKDAL
 LRADPPMAHV THHPSSEREV TLRCWALGFY PKEISLTWQR EGEDQTQDME
 LVETRPSGDG TFQKWAALVV PSGEEQRYTC HVQHEGLQEP LILRWEPPQT
 SFLIMGIIVG LVLLVVAVVA GAVIWRKKRS GEKRQTYTQA ASGDSDQGSD
 VSLTVPKVX*

>P1;IPD:MHC03249
IPD:MHC03249 BoLA-N*00902, 359 bases, 3EA85E37 checksum.
 MGPRTLFVLL LGALALTETR AGSHSLRYFY TAVSRPGLGE PRFISVGYVD
 DTQFVRFDSD APNPREEPRA PWIEKEGPEY WDRETRISKE NTLVYRESLN
 NLRGYYNQSE AGSHTLQLMY GCDVGPDGRL LRGYRQDAYD SRDYIALNEE
 LRSWTAADTA AQITKRKWEA EGYAESLRNY LEGRCVEWLR RYLENGKDAL
 LRADPPMAHV THHPSSEREV TLRCWALGFY PKEISLTWQR EGEDQTQDME
 LVETRPSGDG TFQKWAALVV PSGEEQRYTC HVQHEGLQEP LILRWEPPQT
 SFLIMGIIVG LVLLVVAVVA GAVIWRKKRS GEKRQTYTQA ASGDSDQGSD
 VSLTVPKVX*

>P1;IPD:MHC03178
IPD:MHC03178 BoLA-N*01001, 361 bases, 17BD22A8 checksum.
 MGPRALLLLL SGVLVLTETR AGSHSLRYFY TAVSRPGLGE PRFISVGYVD
 NTEFVRFDSD APDPREEPRV RWMEQEGLEY WDRNTRIYKD TAQTFRVDLN
 TLRGYYNQSE AGSHTLQEMY GCDVGPDGRL LGGYEQYGYE GRDYLALNED
 LRSWTAADTA AHISKRKVEA AGEAERFRNY LEGRCVEGLR RYLENGKDAL
 LRADPPKAHV AHHPISDREV TLRCWALGFY PEEISLTWQH DGEDQTQDME
 LVETRPSGDG TFQKWAALVV PSGDEQRYTC RVQHEGLQEP LTLRWEPPQP
 SFLTMGIIVG LVLLVVTGAV VAGVVICMKK RSGEKGGNYI QASGSDSAQG
 SDVSLTVPKV X*

>P1;IPD:MHC03179
IPD:MHC03179 BoLA-N*01101, 361 bases, D4F9303D checksum.
 MGPRTLLLLL SGVLVLTETR AGSHSMRYFS TAVSRPGLGE PRYLEVGYVD
 DTQFVRFDSD APNPRMEPRA RWVEQEGPEY WDQETRKAKG TAQTFRANLN
 IALGYYNQSE AGSHTFQWMY GCDVGPDGRL RRGFMQYGYD GRDYIALNED
 LRSWTAADTA AQITKRKWEA AGEAERQRNY LEGTCVEWLR RYLETGKDTL
 LRADPPKAHV THHSISGHEV TLRCWALGFY PEDISLTWQR NGEDQTQDME
 LVETRPSGDG NFQKWAALVV PSGEEQKYTC RVQHEGLQEP LTLKWEPPQP
 SFLTMGIIVG LVLLVVTGAV VAGVVICMKK RSGEKRGTYI QASSSDSAQG
 SDVSLTVPKV X*

>P1;IPD:MHC02982
IPD:MHC02982 BoLA-N*01201, 354 bases, 83CAF26D checksum.
 LLLLLSGVLV LTETLAGSHS LRYFYTAVSR PGLGEPRFIA VGYVDDTQFV
 RFDSDAPDPR TEPRVRWVEQ EGPEYWDRET RNFKDTAQTF RVDLNTLRGY
 YNQSEAGSHN IQAMYGCDVG PDGRLLRGYR QDAYDGRDYI ALNEDLRSWT
 AADTAAQITK RKWEAAGEAE RHRNYLEGTC VEWLRRYLEN GKDTLLRADP
 PKAHVTHHSI SDREVTLRCW ALGFYPEEIS LTWQREGEDQ TQDMELVETR
 PSGDGTFQKW AALVVPSGEE QRYTCRVQHE GLQEPLTLRW EPPQTSFLTM
 GIIVGLVLLV VAVVAGAVIW RKKRSGEKGR IYTQAASSDS AQGSDVSLTV
 PKVX*

>P1;IPD:MHC03180
IPD:MHC03180 BoLA-N*01301, 359 bases, D3CEBE4D checksum.
 MGPGTLFMLL LGALVLIETR AGSHSLRYFH TAVSRPGLRE PLFITVGYVD
 DTQFVRFDSD ARDPRTEPRQ PWMEKEGPEY WDRETQISKE NALWYREALN
 NLRGYYNQSE AGSHTLQEMY GCDVGSDGRL RRGYEQYGYD GRDYLALNED
 LRSWTAADTA AQISKRKMEA AGAAERFRNY LEGTCVEWLR RYLENGKDTL
 LRADPPKAHV TRHPSSEHEV TLRCWALGFY PEEISLTWQR NGEDQTQDME
 LVETRPSGDG NFQKWAALVV PSGEEQRYTC RVQHEGLQEP LTLRWEPPQT
 SFLTMGIIVG LVLLVVAVVA GAVIWMKKHS GEKRRTYTQA ASNDSAQGSD
 VSLTVPKVX*

>P1;IPD:MHC03181
IPD:MHC03181 BoLA-N*01302, 354 bases, 345E5907 checksum.
 LFMLLLGALV LIETRAGSHS LRYFHTAVSR PGLREPLFIT VGYVDDTQFV
 RFDSDARDPR TEPRQPWMEK EGPEYWDRET QISKENALWY REALNNLRGY
 YNQSEAGSHT LQLMYGCDVG SDGRLRRGYE QYGYDGRDYL ALNEDLRSWT
 AADTAAQISK RKMEAAGAAE RFRNYLEGTC VEWLRRYLEN GKDTLLRADP
 PKAHVTRHPS SEHEVTLRCW ALGFYPEEIS LTWQRNGEDQ TQDMELVETR
 PSGDGNFQKW AALVVPSGEE QRYTCRVQHE GLQEPLTLRW EPPQTSFLTM
 GIIVGLVLLV VAVVAGAVIW MKKHSGEKRR TYTQAASNDS AQGSDVSLTV
 PKVX*

>P1;IPD:MHC03182
IPD:MHC03182 BoLA-N*01401, 354 bases, C57F25B6 checksum.
 LFMLLLGALV LIETRAGSHF LRYFHTAVSR PGLREPLFIT VGYVDDTQFV
 RFDSDARDPR KEPRQPWMEK EGPEYWDRET QISKENALWY REALNNLRGY
 YNQSEAGSHT YQRMYGCDVG PDGRLLSGFT QFGYDGRDYI ALNEDLRSWT
 AADTAAQITK RKWEAAGEAE RFRNYVEGRC VEGLRRYLEN GKDALLRADP
 PKAHVTHHPI SEHEVTLRCW ALGFYPEEIS LTWQRNGEDQ TQDMELVETR
 PSGDGNFQKW AALVVPSGEE QRYTCRVQHE GLQEPLTLRW EPPQTSFLTM
 GIIVGLVLLV VAVVAGAVIW MKKHSGEKRR TYTQAASNDS AQGSDVSLTV
 PKVX*

>P1;IPD:MHC03183
IPD:MHC03183 BoLA-N*01402, 353 bases, 569432A8 checksum.
 FMLLLGALVL IETRAGSHFL RYFHTAVSRP GLREPLFITV GYVDDTQFVR
 FDSDARDPRK EPRQPWMEKE GPEYWDRETQ ISKENALKYR EALNILRGYY
 NQSEAGSHTY QRMYGCDVGP DGRLLSGFTQ FGYDGRDYIA LNEDLRSWTA
 ADTAAQITKR KWEAAGEAER FRNYVEGRCV EWLRRYLENG KDALLRADPP
 KAHVTHHPIS EHEVTLRCWA LGFYPEEISL TWQRNGEDQT QDMELVETRP
 SGDGNFQKWA ALVVPSGEEQ RYTCRVQHEG LQEPLTLRWE PPQTSFLTMG
 IIVGLVLLVV AVVAGAVIWM KKHSGEKRRT YTQAASNDSA QGSDVSLTVP
 KVX*

>P1;IPD:MHC03184
IPD:MHC03184 BoLA-N*01501, 354 bases, 2949E09C checksum.
 LFMLLLGALV LIETRAGSHS LRYFYTGVSR PGLREPLFIT VGYVDDTQFV
 RFDSDARDPR KEPRQPWMEK EGPEYWDRET QISKENALWY REALNNLRGY
 YNQSEAGSHT LQLMYGCDVG PDGRLLRGFT QFGYDGRDYL ALNEDLRSWT
 AADTAAQISK RKMEAAGDAE RQRNYLEGRC VEGLRRYLEN GKDTLLRADP
 PKAHVTRHPS SEHEVTLRCW ALGFYPEEIS LTWQRNGEDQ TQDMELVETR
 PSGDGNFQKW AALVVPSGEE QRYTCRVQHE GLQEPLTLRW EPPQTSFLTM
 GIIVGLVLLV VAVVAGAVIW MKKHSGEKRR TYTQAASNDS AQGSDVSLTV
 PKVX*

>P1;IPD:MHC02983
IPD:MHC02983 BoLA-N*01502, 354 bases, C537AFE9 checksum.
 LFMLLLGALV LIETRAGSHS LRYFYTGVSR PGLREPLFIT VGYVDDTQFV
 RFDSDARDPR KEPRQPWMEK EGPEYWDRET QISKENALWY REALNNLRGY
 YNQSEAGSHT LQQMFGCDVG PDGRLLRGFT QFGYDGRDYL ALNEDLRSWT
 AADTAAQISK RKMEAAGDAE RQRNYLEGRC VEGLRRYLEN GKDTLLRADP
 PKAHVTRHPS SEHEVTLRCW ALGFYPEEIS LTWQRNGEDQ TQDMELVETR
 PSGDGNFQKW AALVVPSGEE QRYTCRVQHE GLQEPLTLRW EPPQTSFLTM
 GIIVGLVLLV VAVVAGAVIW MKKHSGEKRR TYTQAASNDS AQGSDVSLTV
 PKVX*

>P1;IPD:MHC03185
IPD:MHC03185 BoLA-N*01601, 354 bases, 6F8F14E1 checksum.
 LLLLLSGVLV LTETVAGSHS LRYFSTAVSR PGLGEPRFIA VGYVDDTQFT
 RFDSDAPNPR EEPRAPWMEQ EGLEYWDRNT RIYKDTAQTF RVYLNTLRGY
 YNQSEAGSHT LQWMSGCDVG PDGRLLRGFM QFGYDGRDYI ALNQDLRSWT
 AADTAAQITK RKWEAADNAE SERNYLEGEC VEGLRRYLEN GKDALLRADP
 PKAHVTHHPI SDREVTLRCW ALGFYPEEIS LTWQRNGEDQ TQDMELVETR
 PSGDGTFQKW AALVVPSGEE QRYTCRVQHE GLQEPLTLRW EPPQTSFLTM
 GIIVGLVLLV VAVVAGAVIW RKKRSGEKGR IYTQAASSDS AQGSDVSLTV
 PKVX*

>P1;IPD:MHC03256
IPD:MHC03256 BoLA-N*01602, 359 bases, 9EC49924 checksum.
 MGPRTLLLLL SGVLVLTETV AGSHSLRYFS TAVSRPGLGE PRFIAVGYVD
 DTQFTRFDSD APNPREEPRA PWMEQEGLEY WDRNTRIYKD TAQTFRVYLN
 TLRGYYNQSE AGSHTLQWMS GCDVGPDGRL LRGFMQFGYD GRDYIALNQD
 LRSWTAADTA AQITKRKWEA ADNAESERNY LEGECVEWLR RYLENGKDAL
 LRADPPKAHV THHPISDREV TLRCWALGFY PEEISLTWQR NGEDQTQDME
 LVETRPSGDG TFQKWAALVV PSGEEQRYTC RVQHEGLQEP LTLRWEPPQT
 SFLIMGIIVG LVLLVVALVA GAVIWRKKRS GEKGRIYTQA ASSDSTQGSD
 VSLTVPKVX*

>P1;IPD:MHC03186
IPD:MHC03186 BoLA-N*01701, 364 bases, F1343BFB checksum.
 MRVMGPRTLL LLLSGVLVLT ETRAGSHSMR YFSTAVSRPG LGEPRYLEVG
 YVDDTQFVRF DSDARNPRME PRKRWVEQEG PEYWDRETQR AKGNAQIFRV
 SLNNLRGYYN QSEAGSHTFQ WMYGCDVGPD GRLLGGYEQY GYDGRDYIAL
 NEDLRSWTAG ETEAQITKRK WEAAGAAERQ RNYLEGRCVE WLRRYLENGK
 DTLLRADPPK AHVTHHPISE REVTLRCWAL GFYPEEISLT WQRNGEDQTQ
 DMELVETRPS GDGNFQKWAA LVVPSGEEQK YTCRVQHEGL QEPLTLKWEP
 PQPSFLTMGI IVGLVLLVVT GAVVAGVVIC MKKRSGEKRG TYIQASSSDS
 AQGSDVSLTV PKVX*

>P1;IPD:MHC03262
IPD:MHC03262 BoLA-N*01702, 356 bases, C64BBE5 checksum.
 LLLLLSGVLV LTETRAGSHS MRYFSTAVSR PGLGEPRYLE VGYVDDTQFV
 RFDSDARNPR MEPRKRWVEQ EGPEYWDRET QRAKGNAQIF RVSLNNLRGY
 YNQSEAGSHT FQWMYGCDVG PDGRLRRGFM QYGYDGRDYI ALNEDLRSWT
 AGETEAQITK RKWEAAGAAE RQRNYLEGRC VEWLRRYLEN GKDTLLRADP
 PKAHVTHHPI SEREVTLRCW ALGFYPEEIS LTWQRNGEDQ TQDMELVETR
 PSGDGNFQKW AALVVPSGEE QKYTCRVQHE GLQEPLTLKW EPPQPSFLTM
 GIIVGLVLLV VTGAVVAGVV ICMKKRSGEK RGTYIQASSS DSAQGSDVSL
 TVPKVX*

>P1;IPD:MHC03187
IPD:MHC03187 BoLA-N*01801, 362 bases, E6FC757F checksum.
 MRVMRPRTLL LVLSRVLVLT ETLAGSHSLR YFYTAVSRPG LGEPRFIAVG
 YVDDTQFTRF DSDAPNPRDE PRVPWMEQEG PEYWDRNTRI YKDTAQIFRA
 NLNTALGYYN QSEAGSHTFQ EMYGCYVGPD GRLLLGFMQF AYDGRDYIAL
 NEDLRSWTAA DTAAQITKRK WEAAGEAERQ RNYLEGRCVE GLRRYLENGK
 DTLLRADPPK AHVTHHPISD REVTLRCWAL GFYPEEISLT WQHEGEDQTQ
 DMELVETRPS GDGTFQKWAA LVVPSGEEQR YTCRVQHEGL QEPLTLRWEP
 PQTSFLTMGI IVGLVLLVVA VVAGAVIWRK KRSGEKGRIY TQAASSDSAQ
 GSDVSLTVPK VX*

>P1;IPD:MHC03188
IPD:MHC03188 BoLA-N*01802, 353 bases, 2A5546F3 checksum.
 LLLLSRVLVL TETLAGSHSL RYFYTAVSRP GLGEPRFIAV GYVDDTQFTR
 FDSDAPNPRD EPRVPWMEQE GPEYWDRNTR IYKDTAQIFR ANLNTALGYY
 NQSEAGSHTF QEMYGCYVGP DGRLLLGFMQ FAYDGRDYIA LNEDLRSWTA
 ADTAAQITKR KWEAAGEAER QRNYLEGRCV EGLRRYLENG KDTLLRADPP
 KAHVTHHPIS DREVTLRCWA LGFYPEEISL TWQHEGEDQT QDMELVETRP
 SGDGTFQKWA ALVVPSGEEQ RYTCRVQHEG LQEPLTLRWE PPQTSFLTMG
 IIVGLVLLVV AVVAGAVIWR KKRSGEKGRI YTQAASSDSA QGSDVSLTVP
 KVX*

>P1;IPD:MHC03189
IPD:MHC03189 BoLA-N*01901, 359 bases, 627DA110 checksum.
 MGPRTLFVLL LGALVLTETR AGSHSLKYFH TAVSRPGDGE PRFITVGYVD
 DTQFVRFDSD APDPRKEPRA PWIEKEGPEY WDRETRISKE NTLVYRGSLN
 NLRGYYNQSE AGSHTYQDMY GCDVGPDGRL LGGYDQYGYD GRDYLALNED
 LRSWTAADTA AQITKRKWEA AGVAERFRNY VEGRCVEGLR RYLENGKDAL
 LRADPPKAHV THHPISEREV TLRCWALGFY PKEISLTWQR NGEDQTQDME
 LVETRPSGDG NFQKWAALVV PSGEEQRYTC HVQHEGLQEP LTLRWEPPQT
 SFLIMGIIVG LVLLVVAVVA GAVIWRKKRS GEKRQTYTQA ASGDSDQGSD
 VSLTVPKVX*

>P1;IPD:MHC03190
IPD:MHC03190 BoLA-N*02001, 354 bases, BF59F664 checksum.
 LFVLLLGALV LTETRAGSHS LKYFHTAVSR PGDGEPRFIT VGYVDDTQFV
 RFDSDAPDPR KEPRAPWIEK EGPEYWDRET RISKENTLVY RGSLNNLRGY
 YNQSEAGSHT FQLMYGCDVG PDGRLLRGFM QDAYDSRDYI ALNEDLRSWT
 VADTAAQITK RKWEAAGVAE RFRNYVEGRC VEGLRRYLEN GKDALLRADP
 PKAHVTHHPI SEREVTLRCW ALGFYPKEIS LTWQRNGEDQ TQDMELVETR
 PSGDGNFQKW AALVVPSGEE QRYTCHVQHE GLQEPLTLRW EPPQTSFLIM
 GIIVGLVLLV VAVVAGAVIW RKKRSGEKRQ TYTQAASGDS DQGSDVSLTV
 PKVX*

>P1;IPD:MHC03191
IPD:MHC03191 BoLA-N*02101, 362 bases, DC689714 checksum.
 MRVMGPRTLF VLLLGALVLT ETRAGSHSLR YFYTAVSRPG DGEPRFITVG
 YVDDTQFVWF DSDAPDPRKE PRTPWIEKEG PEYWDRETRI SKENTLVYRG
 SLNNLRGYYN QSEAGSHTFQ QMFGCDVGPD GRLLGGYRQY AYDGRDYIAL
 NEDLRSWTAA DTAAQITKRK WEAAGDAERF RNYVEGECVE GLRRYLENGK
 DTLLRADPPK AHVTHHPISE REVTLRCWAL GFYPEEISLT WQRNGEDQTQ
 DMELVETRPS GDGNFQKWAA LVVPSGEEQR YTCHVQHKGL QEPLTLRWEP
 PQTSFLTMGI IVGLVLLVVA VVAGAVIWRK KRSGEKRQTY TQAASGDSDQ
 GSDVSLTVPK VX*

>P1;IPD:MHC03192
IPD:MHC03192 BoLA-N*02201, 356 bases, 4E79EE19 checksum.
 RTLLLLLSGV LVLTETRAGS HSLRYFHTAV SRPGLGEPRF ISVGYVDDTQ
 FVRFDSDSAN PREEPRAPWM EQEGPEYWDE QTRIVKDTAQ SFRVGLNTLR
 GYYNQSEAGS HTLQLMYGCD VGPDGRLLRG YEQDAYDGRD YIALNEDLRS
 WTAADTAAQI TKRKREAAGA AERLRNYLEG TCVEGLRRYL ENGKDALLRA
 DPPKAHVTHH PVSDREVTLR CWALGFYPEE ISLTWQREGE DQTQDMELVE
 TRPSGDGTFQ KWAALVVPSG EEQRYTCRVQ HEGLQEPLTL RWEPPQTSFL
 IMGIIVGLVL LVVALVAGAV IWRKKRSGEK GRIYTQAASS DSAQGSDVSL
 TVPKVX*

>P1;IPD:MHC03193
IPD:MHC03193 BoLA-N*02301, 361 bases, AD3EA425 checksum.
 RVMGPRTLFV LLLGALALTE TRAGSHSLRY FYTAVSRPGL GEPRFISVGY
 VDDTQFVRFD SDAPNPREEP RAPWIEKEGP EYWDRETRIS KENTLVYRES
 LNNLRGYYNQ SEAGSHNIQA MYGCDVGSDG SFLRGYSQDA YDGRDYIALN
 EDLRSWTAAD TAAQITKRKW EAEGYAESLR NYLEGRCVEW LRRYLENGKD
 ALLRADPPMA HVTHHPSSER EVTLRCWALG FYPKEISLTW QREGEDQTQD
 MELVETRPSG DGTFQKWAAL VVPSGEEQRY TCHVQHEGLQ EPLILRWEPP
 QTSFLIMGII VGLVLLVVAV VAGAVIWRKK RSGEKRQTYT QAASGDSDQG
 SDVSLTVPKV X*

>P1;IPD:MHC03194
IPD:MHC03194 BoLA-N*02401, 361 bases, F4A73AFE checksum.
 MGPRTLLLLL SGVLVLTETR AGSHSLRYFS TAVSRPGLEE PRFIIVGYVD
 DTQFVRFDSD SPNPRAEPRA PWMEQEGPEY WDEQTRIVKD TAQTFRANLN
 TALGYYNQSE AGSHNIQAMY GCDVGSDGSF LRGYSQDAYD GRDYIALNED
 LRSWTAADTA AQITKRKWEA EGYAESLRNY LEGTCVEWLR RYLENGKDTL
 LRADPPKAHV THHSISGREV TLRCWALGFY PEEISLTWQR KGEDQTQEME
 LVETRPSGDG NFQKWAALVV PSGEEQKYTC RVQHKGLQEP LTLRWEPPQT
 SFLTMGIIVG LVLLVVTGVV VAGAVIWMKR RSGEKGGNYI QASSSDSAQG
 SDVSLTVPKV X*

>P1;IPD:MHC03195
IPD:MHC03195 BoLA-N*02402, 356 bases, A174B255 checksum.
 LLLLLSGVLV LTETRAGSHS LRYFSTAVSR PGLEEPRFII VGYVDDTQFV
 RFDSDSPNPR AEPRAPWMEQ EGPEYWDEET RIVKDTAQTF RANLNTALGY
 YNQSEAGSHT LQPMYGCDVG SDGSFLRGYS QDAYDGRDYI ALNEDLRSWT
 AADTAAQITK RKWEATGYAE SLRNYLEGTC VEWLRRYLEN GKDTLLRADP
 PKAHVTHHSI SGREVTLRCW ALGFYPEEIS LTWQRKGEDQ TQEMELVETR
 PSGDGNFQKW AALVVPSGEE QKYTCRVQHK GLQEPLTLRW EPPQTSFLTM
 GIIVGLVLLV VTGVVVAGAV IWMRKRSGEK GGNYIQASSS DSAQGSDVSL
 TVPKVX*

>P1;IPD:MHC03196
IPD:MHC03196 BoLA-N*02501, 354 bases, 145EA278 checksum.
 LLLLLSGVLV LTETLAGSHS LRYFSTAVSR PGLGEPRFIA VGYVDDTQFT
 RFDSDAPNPR EEPRVPWMEQ EGLEYWDRNT RIYKDTAQTF RVYLNALRGY
 YNQSEAGSHT LQWMSGCDVG PDGRLLRGFW QFGYDGRNYI ALNEDLRSWT
 AADTAAQITK RKWEAAGAAE GERNYVEGRC VEGLRRYLEN GKDALLRADP
 PKAHVTHHPI SEREVTLRCW ALGFYPEEIS LTWQREGEDQ TQDMELVETR
 PSGDGTFQKW AALVVPSGEE QRYTCRVQHE GLQEPLTLRW EPPQTSFLTM
 GIIVGLVLLV VAVVAGAVIW RKKRSGEKGR IYTQAASSDS TQGSDMSLTV
 PKVX*

>P1;IPD:MHC03197
IPD:MHC03197 BoLA-N*02601, 354 bases, ADD56647 checksum.
 LLLLPLGVLV LTENLAGSHS LRYLYTGVSR PGLGEPRFIA VGYVDDTQFT
 RFDSDAPNPR EEPRVPWMEQ EGPEYWDRET RISKETAQTF RVDLNTLRGY
 YNQSEAGSHT IQEMYGCDVG PDGRFLRGYE QYGYEGRDYI ALNEDLRSWT
 AADTAAQITK RKWEAADYAE SLRNYLEGRC VEGLRRYLEN GKDTLLRADP
 PKAHVTRHPI SEREVTLRCW ALGFYPEEIS LTWQREGEDQ TQDMELVETR
 PSGDGTFQKW AALVVPSGEE QRYTCRVQHE GLREPLTLRW EPPQTSFLTM
 GIIVGLVLLV VAVVAGAVIW RKKRSGEKGR IYTQAASSDS AQGSDVSLTV
 PKVX*

>P1;IPD:MHC03198
IPD:MHC03198 BoLA-N*02602, 353 bases, 916077A2 checksum.
 LLLLSGVLVL TETLAGSHSL RYFYTGVSRP GLGEPRFIAV GYVDDTQFTR
 FDSDAPNPRE EPRVPWMEQE GPEYWDRETR ISKETAQTFR VDLNTLRGYY
 NQSEAGSHTI QEMYGCDVGP DGRFLRGYEQ YGYEGRDYIA LNEDLRFWTA
 ADTAAQITKR KWEAADYAES LRNYLEGRCV EGLRRYLENG KDALLRADPP
 KAHVTRHPIS EREVTLRCWA LGFYPEEISL TWQREGEDQT QDMELVETRP
 SGDGTFQKWA ALVVPSGEEQ RYTCRVQHEG LREPLTLRWE PPQTSFLTMG
 IIVGLVLLVV AVVAGAVIWR KKRSGEKGRI YTQAASSDSA QGSDVSLTVP
 KVX*

>P1;IPD:MHC03199
IPD:MHC03199 BoLA-N*02701, 356 bases, 42DF0837 checksum.
 LLLLPLGVLV LTETRAGSHS MRYFSTAVSR PGFGEPRYLE VGYVDDTQFV
 RFDSDARNPR MEPRTRWVKQ EGPEYWDRNT RNAKGNAQSF RVGLNTLRGY
 YNQSEAGSHT LQWMSGCYVG PDGRLLRGFM QYGYDGRDYL ALNEDLRSWT
 AADTEAQITK RKWEAEGYAE VQRNYLEGEC VEWLRRHLEN GKDTLLRADP
 PKAHVTHHPI SDREVTLRCW ALGFYPEEIS LTWQHNGEDQ TQDMELVETR
 PSGDGTFQKW AALVVPSGEE QKYTCRVQHE GLQEPLTLKW EPPQPSFLTM
 GIIVGLVLLV VTGAVVAGVV ICMKKPSGEK RGTYIQALSS DSAQGSDVSL
 TVPKVX*

>P1;IPD:MHC03200
IPD:MHC03200 BoLA-N*02702, 361 bases, 5F3C7F09 checksum.
 MGPRTLLLLL SGVLVLTETR AGSHSMRYFS TAVSRPGFGE PRYLEVGYVD
 DTQFVRFDSD ARNPRMEPRT RWVKQEGPEY WDRNTRNAKG NAQSFRVGLN
 TLRGYYNQSE AGSHTLQWMS GCYVGPDGRL LRGFMQYGYD GRDYLALNED
 LRSWTAADTE AQITKRKWEA EGYAEVQRNY LEGECVEWLR RHLENGKDTL
 LRADPPKAHV THHPISDREV TLRCWALGFY PEEISLTWQH NGEDQTQDME
 LVETRPSGDG TFQKWAALVV PSGEEQKYTC RVQHEGLQEP LTLKWEPPQP
 SFLTMGIIVG LVLLVVTGAV VAGVVICMKK PSGEKRGTYI QALSSDSAQG
 SDVSLTVPKV X*

>P1;IPD:MHC03201
IPD:MHC03201 BoLA-N*02801, 354 bases, 19044DD checksum.
 LFVLLLGALV LTETRAGSHS LRYFYTAVSR PGDGEPRFIT VGYVDDTQFV
 WFDSDAPDPR KEPRTPWIEK EGPEYWDRET RISKEKTLLY RENLNTLRGY
 YNQSEAGSHT LQQMFGCDVG PDGRLLRGYR QYAYDGRDYI ALNEDLRSWT
 AADTAAQITK RKWEAAGDAE RFRNYVEGEC VEWLRRYLEN GKDTLLRADP
 PKTHVAHHPI SGREVTLRCW ALGFYPEEIS LTWQRNGEDQ TQDMELVETR
 PSGDGNFQKW AALVVPSGEE QRYTCHVQHK GLQEPLTLRW EPPQTSFLTM
 GIIVGLVLLV VAVVAGAVIW RKKRSGEKRQ TYTQAASGDS DQGSDVSLTV
 PKVX*

>P1;IPD:MHC03202
IPD:MHC03202 BoLA-N*02901, 354 bases, 38C2C623 checksum.
 LFVLLSGALV LTETRAGSHS MKYFYTAVSR PGDGEPRFIT VGYVDDTEFV
 RFDSDAPDPR REPRAPWIEK EGPEYWDRET RISKENTLLY RKNLNTALGY
 YNQSEAGSHT IQTMFGCDVG PDGRFLRGFM QYAYDGRDYI ALNEDLRSWT
 AADTAAQITK RKWEAADNAE SERNYLEGRC VEGLRRYLEN GKDALLRADP
 PKAHVTHHPI SHREVTLRCW ALGFYPKEIS LTWQRNGEDQ TQDMELVETR
 PSGDGNFQKW AALVVPSGEE QRYTCHVQHE GLQEPLTLRW EPPQTSFLTM
 GIIVGLVLLV VAVVAGAVIW RKKRSGEKRQ TYTQAASGDS DQGSDVSLAV
 PKVX*

>P1;IPD:MHC03203
IPD:MHC03203 BoLA-N*03001, 352 bases, 17E64E62 checksum.
 LLLLLSGVLV LTETLAGSHS LKYFYTAVSR PGLGEPRFIS VGYVDDTQFV
 WFDSDAPNPR EEPRAPWMEQ EGLEYWDRNT RIYKDTAQNF RVSLNNLRGY
 YNQSEAGSHT LQWMSGCYVG PDGRLRRGFW QFGYDGRDYI ALNEDLRSWT
 AADTAAQITK RKWEAADNAE SERNYLEGEC VEWLRRYLEN GKDALLRADP
 PKAHVTHHPI SDREVTLRCW ALGFYPEEIS LTWQREGEDQ TQDMELVETM
 PSGDGFQKWA ALVVPSGEEQ RYTCRVQHEG LQEPLTLRWE PPQTSFLTMG
 IIVGLVLLIV AVVAGAVIRR KKRSGEKGRI YQAASSDSAQ GSDVSLTVPK
 VX*

>P1;IPD:MHC03204
IPD:MHC03204 BoLA-N*03101, 353 bases, 80D2EF48 checksum.
 FVLLLGALAL TETRAGSHSL KYFYTAVSRP GDGEPRFITV GYVDDTQFVR
 FDSDAPDPRK EPRAPWIEKE GPEYWDDETR ISKENTLLYR KNLNTLRGYY
 NQSEAGSHNI QAMFGCDVGP DGRFLRGYRQ DAYDGRDYIA LNEDLRSWTA
 ADTAAQITKR KWEAADYAES LRNYLEGTCV EWLRRYLENG KDTLLRADPP
 KAHVTHHPSS EREVTLRCWA LGFYPEEISL TWQRSGEDQT QDMELVETRP
 SGDGNFQKWA ALVVPSGEEQ RYTCHVQHEG LQEPLTLRWE PPQTSFLTMG
 IIVGLVLLVV AVVAGAVIWR KKRSGEKRQT YTQAASGDSD QGSDVSLTVP
 KVX*

>P1;IPD:MHC03205
IPD:MHC03205 BoLA-N*03201N, 20 bases, 668C5E00 checksum.
 LLLLSGVLVL TETLAGSHSX*

>P1;IPD:MHC03206
IPD:MHC03206 BoLA-N*03301N, 168 bases, 18ED7216 checksum.
 LLLLSGVLVL TETRAGSHSL RYFSTAVSRP GFGEPRYLEV GYVDDTQFVQ
 FDSDAPNPRM EPRARWVEQE GPEYWDRNTR NAKGNAQFPS EPEHPARLLQ
 PERGRVSHPP VDVRLLRGAG RASPPRVHAV RLRRQRLPRP ERGPALLDRG
 GDGGSDHQAQ VGGGRLRX*

>P1;IPD:MHC03207
IPD:MHC03207 BoLA-N*03401, 353 bases, 4E109EA8 checksum.
 FVLLLGALVL TETRAGSHSL KYFHTAVSRP GDGEPRFITV GYVDDTQFVR
 FDSDAPDPRK EPRAPWIEKE GPEYWDRETR ISKENTLVYR GSLNNLRGYY
 NQSEAGFHTL QLMYGCDVGP DGRLLRGFTQ FGYDGRDYLA LNEDLRSWTA
 ADTAAQISKR KMEAAGDAER RRNYLEGRCV EGLRRYLENG KDTLLRADPP
 KAHVTRHPSS EHEVTLRCWA LGFYPEEISL TWQRNGEDQT QDMELVETRP
 SGDGNFQKWA ALVVPSGEEQ RYTCRVQHEG LQEPLTLRWE PPQTSFLTMG
 IIVGLVLLVV AVVAGAVIWM KKHSGEKRRT YTQAASNDSA QGSDVSLTVP
 KVX*

>P1;IPD:MHC03208
IPD:MHC03208 BoLA-N*03501, 356 bases, 4996BFB2 checksum.
 LLLLLSGVLV LTETGAGSHS MRYFYTAVSR PGLGEPRFIN VGYVDDTQFV
 RFDSDAPNPR MEPRARWVEQ EGPEYWDQET RNAKGNAQTF RVGLNTLRGY
 YNQSEAGSHT LQWMSGCDVG PDGRLLRGYE QFGYDGRDYL ALNEDLRSWT
 AADTAAQITK RKWEEAGAEE RHRNYLEGTC VEWLRRYLEN GKDTLLRADP
 PKAHVTHHPI SDREVTLRCW ALGFYPEDIS LTWQRNGEDQ MQDMELVETR
 PSGDGNFQKW AALVVPSGEE QKYTCRVQHE GLQEPLTLKW EPPQPSFLTM
 GIIVGLVLLV VTGAVVAGVV ICMKKRSGEK RGTYIQASSS DSAQGSDVSL
 TVPKVX*

>P1;IPD:MHC03209
IPD:MHC03209 BoLA-N*03601, 356 bases, 3A77966E checksum.
 LLLLLSGVLV LTETRAGSHS LRYFYTGVSR PGLGEPRFIA VGYVDDTQFV
 RFDSDAPDPR MEPRARWVEQ EGPEYWDRNT RNAKDAAQTF RVNLNTLRGY
 YNQSEAGSHT FQLMYGCDVG PDGRLLRGYE QYGYDGRDYI ALNEDLRSWT
 AADTAAQITK RKVEAAGDAE GHRNYLEGRC VEWLRRYLEN GKDTLLRADP
 PKAHVTHHPI SGREVTLRCW ALGFYPEDIS LTWQRNGEDQ TQDMELVETR
 PSGDGNFQKW VALVVPSGEE QKYTCRVQHE GLQEPLTLKW EPPQPSFLTM
 GIIVGLVLLV VTGAVVAGVV ICMKKRSGEK RGTYIQASSS DSAQGSDVSL
 TVPKVX*

>P1;IPD:MHC03210
IPD:MHC03210 BoLA-N*03701, 356 bases, E738DB0 checksum.
 LLLLLSGVLV LTETRAGSHS LRYFSTAVSR PGFGEPRYLE VGYVDDTQFV
 RFDSDAPNPR MEPRARWVEQ EGPEYWDRNT RNAKGNAQSF RVGLNTLRGY
 YNQSEAGSHT LQLMYGCYVG PDGRLRRGFM QDAYDGRDYL ALNEDLRSWT
 AADTAAQISK RKREAAGVAE EQRNYLEGRC VEWLRRYLEN GKDTLLRADP
 PKAHVTHHPI SHREVTLRCW ALGFYPEEIS LTWQRNGEDQ MQDMEFVETR
 PSGDGNFQKW AALVVPSGEE QKYTCRVQHE GLQEPLTLKW EPPQPSFLTM
 GIIVGLVLLV VTGAVVAGVV ICMKKRSGEK RGTYIQASSS DSAQGSDVSL
 TVPKVX*

>P1;IPD:MHC03211
IPD:MHC03211 BoLA-N*03801, 356 bases, D36052F4 checksum.
 LLLLLSGVLV LTETRAGSHS MRYFNTAVSR PGFGEPRYLE VGYVDDTQFV
 RFDSDAPNPR MEPRARWVEQ EGPEYWDRNT RNAKGNAQDS RVGLNTLRGY
 YNQSEAGSHT LQWMYGCDVG PDGRLRRGFM QYGYDGRDYL ALNEDLRSWT
 AVETVAQISK RKMEAAGVAE EQRNYLEGTC VEWLRRYLEN GKDTLLRADP
 PKAHVTHHPI SGREVTLRCW ALGFYPEEIS LTWQRNGEDQ TQDMELVETR
 PSGDGTFQKW AALLVPSGEE QKYTCRVQHE GLQEPLTLKW EPPQPSFLTM
 GIIVGLVLLV VTGAVVAGVV ICMKKRSGEK RGTYIQASSS DSAQGSDVSL
 TVPKVX*

>P1;IPD:MHC03221
IPD:MHC03221 BoLA-N*03901, 355 bases, 92E42388 checksum.
 LLLLLSGVLV LTETRAGSHS LRYFYTAVSR PGLGEPRFII VGYVDDTQFV
 RFDSDAGDPR VEPRARWVEQ EGPEYWDQET RKAKDTAQFF RLGLNTLRGY
 YNQSEAGSHT LQWMCGCDVG PDGRLRRGFW QFGYEGRDYL ALNEDLRSWT
 AADTAAQITK RKWEAADNAE GERNYLEGEC VEWLPRYLEN GKDTLLRADP
 PKAHVTHHPI SGREVTLRCW ALGFYPEEIS LTWQRNGEDQ TQDMELVETR
 PSGDGTFQKW AALVVPSGEE QRYTCSVQHE GLQEPLTLRW EPPQTSFLTM
 GIIVGLVLLV TGAVVAGFVI WMKKRSGEKG GNYIQASRSD SAQGSDVSLT
 VPKVX*

>P1;IPD:MHC03220
IPD:MHC03220 BoLA-N*04001, 357 bases, 1CBF1834 checksum.
 PRGLLLLLSG VLVLTGTRAG SHSMRYFSTA VSRPGLGEPQ YLEVGYVDDT
 QFVRFDSDAP NPRMEPRARW VKQEGPEYWD EETQRAKGIT QVFRVNLNTL
 RGYYNQSEAG SHTLQWMCGC DVGPDGRLRR GFWQFGYDGR DYLALNEDLR
 SWTAADTAAQ ISKRKMEAAG AAESGRKYVE GTCVEWLRRY LENGKDTLLR
 ADPPKAHVTH HPISDHEVTL RCWALGFYPE EISLTWQRNG EDQTQDMELV
 ETRPSGDGNF QKWAALVVPS GEEQRYTCRV QHEGLQEPLT LRWEPPQTPF
 LTVGIIVGLV LLVVAVVAGA VIWRKKCSGE KGRTYTQASS NDSAQGSDVS
 LTVPKVX*

>P1;IPD:MHC03222
IPD:MHC03222 BoLA-N*04101, 359 bases, 2A6B95AC checksum.
 MGPRTLFMLL LGALVLIETR AGSHFLRYFH TAVSRPGLRE PLFITVGYVD
 DTQFVRFDSD ARDPRKEPRQ PWMEKEGPEY WDRETQISKE NALWYREALN
 TLRGYYNQSE AGSHTLQEMY GCDVGSDGRL RRGYEQYGYD GRDYLALNED
 LRSWTAADTA AQISKRKMEA AGAAERFRNY LEGRCVESLR RYLENGKDTL
 LRADPPKAHV TRHPSSEHEV TLRCWALGFY PEEISLTWQR NGEDQTQDME
 LVETRPSGDG NFQKWAALVV PSGEEQRYTC RVQHEGLQEP LTLRWEPPQT
 SFLTMGIIVG LVLLVVAVVA GAVIWMKKHS GEKRRTYTQA ASNDSAQGSD
 VSLTVPKAX*

>P1;IPD:MHC03248
IPD:MHC03248 BoLA-N*04201, 359 bases, 57BF7186 checksum.
 MGPRTLFVLL LGALALTETR AGSHSLKYFH TAVSRPGDGE PRFITVGYVD
 DTQFVRFDSD APDPRKEPRA PWIEKEGPEY WDDETRISKE NTLLYRKDLN
 TLRGYYNQSE AGSHNIQAMY GCDVGPDGRF LRGYRQDAYD GRDYIALNED
 LRSWTAADTA AQITKRKWEA EGYAESLRNY LEGRCVEGLR RYLENGKDAL
 LRADPPKAHV THHPSSEREV TLRCWALGFY PKEISLTWQR SGEDQTQDME
 LVETRPSGDG NFQKWAALVV PSGEEQRYTC HVQHEGLQEP LTLRWEPPQT
 SFLTMGIIVG LVLLVVAVVA GAVIWRKKRS GEKRQTYTQA ASGDSDQGSD
 VSLTVPKVX*

>P1;IPD:MHC03250
IPD:MHC03250 BoLA-N*04301, 359 bases, 2C28AD6F checksum.
 MGPRTLLLLL SGVLVLTETR AGSHSMRYFS TAVSRPGFGE PRYLEVGYVD
 DTQFVRFDSD APNPRMEPRA RWVEQEGPEY WDRETQRAKG NAQTFRVNLN
 TLRGYYNQSE AGSHTIQWMY GCYVGPDGRF LRGYRQDAYD GRDYIALNED
 LRSWTAADTA AQITKRKWEA AGVAERFRNY LEGLCVEGLR RYLENGKDTL
 LRADPPKAHV THHPISDREV TLRCWALGFY PEEISLTWQR EGEDQTQDME
 LVETMPSGDG TFQKWAALVV PSGEEQRYTC RVQHEGLQEP LTLRWEPPQT
 SFLTMGIIVG LVLLVVAVVA GAVIWRKKRS GEKGRIYTQA ASSDSAQGSD
 VSLTVPKVX*

>P1;IPD:MHC03251
IPD:MHC03251 BoLA-N*04401, 359 bases, 730F1585 checksum.
 MGPRTLLLLL LGVLVLTETL AGSHSLRYFY TAVSRPGLGE PRFIAVGYVD
 DTQFVRFDSD RPDPRMEPRA RWVEQEGPEY WDEETRKAKD TAQTFRVDLN
 TLRGYYNQSE AGSHNIQAMY GCDVGPDGRF LRGYRQDAYD GRDYIALNED
 LRSWTAADTA AQITKRKWEA AGVAERFRNY LEGLCVEGLR RYLENGKDTL
 LRADPPKAHV THHPISDREV TLRCWALGFY PEEISLTWQR EGEDQTQDME
 LVETMPSGDG TFQKWAALVV PSGEEQRYTC RVQHEGLQEP LTLRWEPPQT
 SFLTMGIIVG LVLLVVAVVA GAVIWRKKRS GEKGRIYTQA ASSDSAQGSD
 VSLTVPKVX*

>P1;IPD:MHC03252
IPD:MHC03252 BoLA-N*04501, 359 bases, 86A681FF checksum.
 MGPRTLLLLL SGVLVLTETL AGSHSLRYFY TGVSRPGLGE PRFIAVGYVD
 DTQFVRFDSD APDPRTEPRV RWIEQEGPEY WDRETRNLKD TAQTFRVDLN
 TLRGYYNQSE AGSHTIQEMY GCDVGPDGRF LRGYRQDAYD GRDYLALNED
 LRSWTAADTA AQITKRKWEA AGEAERFRNY VEGLCVEGLR RYLENGKDTL
 LRADPPKAHV THHPISHREV TLRCWALGFY PEEISLTWQR EGEDQTQDME
 LVETRPSGDG TFQKWAALGV PSGEEQRYTC RVQHEGLQEP LTLRWEPPQT
 SFLTMGIIVG LVLLVVAVVA GAVIWRKKRS GEKGRIYTQA ASNDSAQGSD
 VSLTVPKVX*

>P1;IPD:MHC03253
IPD:MHC03253 BoLA-N*04601, 359 bases, D1035240 checksum.
 MGPRTLLLLL SGVLVLTETR AGSHSMRYFS TAVSRPGFGE PRYLEVGYVD
 DTQFVRFDSD APNPRMEPRA RWVEQEGPEY WDRETQRAKG NAQTFRVNLN
 TLRGYYNQSE AGSHTIQWMY GCYVGPDGRF LRGYRQDAYD GRDYIALNED
 LRSWTAADTA AQITKRKWEA AGEAERQRNY LEGTCVEWLR RYLENGKDTL
 LRADPPKAHV THHPVSDREV TLRCWALGFY PEEISLTWQR EGEDQTQDME
 LVETRPSGDG TFQKWAALVV PSGEEQRYTC RVQHEGLQEP LTLRWEPPQT
 SFLIMGIIVG LVLLVVALVA GAVIWRKKRS GEKGRIYTQA ASSDSAQGSD
 VSLTVPKVX*

>P1;IPD:MHC03254
IPD:MHC03254 BoLA-N*04701, 359 bases, C572FD77 checksum.
 MGPRTLLLLL SGVLVLTETR AGSHSMRYFS TAVSRPGFGE PRYLEVGYVD
 DTQFVRFDSD APNPRMEPRV RWMEQEGPEY WDQETQRAKG NAQTFRVDLN
 TLRGYYNQSE AGSHTLQWMY GCYVGPDGRL LRGFMQDAYD GRDYLALNED
 LRSWTAADTA AQITKRKWEA AGEAERQRNY LEGTCVEWLR RYLENGKDTL
 LRADPPKAHV THHPVSDREV TLRCWALGFY PEEISLTWQR EGEDQTQDME
 LVETRPSGDG TFQKWAALVV PSGEEQRYTC RVQHEGLQEP LTLRWEPPQT
 SFLIMGIIVG LVLLVVALVA GAVIWRKKRS GEKGRIYTQA ASSDSAQGSD
 VSLTVPKVX*

>P1;IPD:MHC03255
IPD:MHC03255 BoLA-N*04801, 359 bases, 3C6C251E checksum.
 MGPRTLLLLL SGVLVLTETR AGSHSLRYFY TAVSRPGLGE PRFISVGYVD
 DTQFVRFDSD SANPREEPRA PWMEQEGPEY WDEQTRIVKD TAQSFRVGLN
 TLRGYYNQSE AGSHTLQLMY GCDVGPDGRF LRGFMQDAYD GRDYIALNED
 LRSWTAADTA AQITKRKREA AGAAERQRNY LEGRCVEGLR RYLENGKDAL
 LRADPPKAHV THHPISEREV TLRCWALGFY PEEISLTWQR EGEDQTQDME
 LVETRPSGDG TFQKWAALVV PSGEEQRYTC RVQHEGLQEP LTLRWEPPQT
 SFLIMGIIVG LVLLVVALVA GAVIWRKKRS GEKGRIYTQA ASSDSAQGSD
 VSLTVPKVX*

>P1;IPD:MHC03257
IPD:MHC03257 BoLA-N*04901, 359 bases, 124FDC29 checksum.
 MGPRTLLLLL SGVLVLTETL AGSHSLRYFY TGVSRPGLGE PRFIAVGYVD
 DTQFTRFDSD APNPREEPRV PWMEQEGPEY WDRETRISKD TAQSFRVGLN
 TLRGYYNQSE AGSHTIQEMY GCDVGPDGRF LRGYEQYGYE GRDYIALNED
 LRSWTAADTA AQITKRKWEA ADYAESLRNY LEGECVEGLR RYLENGKDTL
 LRADPPKAHV THHPISDREV TLRCWALGFY PKEISLTWQR NGEDLTQDME
 LVETRPSGDG NFQKWAALVV PSGEEQRYTC HVQHEGLQEP LTLRWEPPQT
 SFLTMGIIVG LVLLVVAVVA GAVIWRKKRS GEKRQTYTQA ASGDSDQGSD
 VSLTVPKVX*

>P1;IPD:MHC03258
IPD:MHC03258 BoLA-N*05001, 361 bases, 1D989F89 checksum.
 MGPRTLLLLL SGVLVLTETR AGSHSMRYFS TAVSRPGLGE PRYLEVGYVD
 DTQFVRFDSD APNPRMEPRT RWVKQEGPEY WDRNTRNAKG NAQTFRGSLN
 NLRGYYNQSE AGSHTFQLMY GCDVGPDGRL RRGFTQYGYD GRDYIALNEE
 LRSWTAADTA AQITKRKWEA AGEAESWRNY LEGTCVEWLR RHLENGKDTL
 LRADPPKAHV THHPISDYEV TLRCWALGFY PEEISLTWQR NGEDQMQDME
 LVETRPSGDG NFQKWAALVV PSGEEQKYTC RVQHEGLQEP LTLKWEPPQP
 SFLTMGIIVG LVLLVVTGAV VAGVVICMKK RSGEKRGTYI QASSSDSAQG
 SDVSLTVPKV X*

>P1;IPD:MHC03259
IPD:MHC03259 BoLA-N*05101, 361 bases, 96BD779D checksum.
 MGPRTLLLLL SGVLVLTETR AGSHSMRYFS TAVSRPGFGE PRYLEVGYVD
 DTQFVRFDSD APNPRMEPRA RWVEQEGPEY WDRETQRAKG NAQTFRVNLN
 TLRGYYNQSE AGSHTIQWMY GCYVGPDGRF LRGYRQDAYD GRDYIALNED
 LRSWTAGDTA AQITKRKWEE AGAAEGERNY LEGTCVEWLR RYLENGKDAL
 LRADPPKAHV THHPISGREV TLRCWALGFY PEDISLTWQR NGEDQTQDME
 LVETRPSGDG NFQKWVALVV PSGEEQKYTC RVQHEGLQEP LTLKWEPPQP
 SFLTMGIIVG LVLLVVTGAV VAGVVICMKK RSGEKRGTYI QASSSDSAQG
 SDVSLTVPKV X*

>P1;IPD:MHC03260
IPD:MHC03260 BoLA-N*05201, 361 bases, 2DF38033 checksum.
 MGPRTLLLLL SGVLVLTETR AGSHSLRYFY TAVSRPGLGE PRFISVGYVD
 DTQFVRFDSD APNPRMEPRA RWVEQEGPEY WDRETRNSKD TAQGFRVDLN
 TLRGYYNQSE AGSHTLQLMY GCYVGPDGSL RRGFTQYGYD GRDYLALNED
 LRSWTAVETM AQISKRKVEA AGVAEKQRNY LEGRCVEWLR RYLENGKDTL
 LRADPPKAHV TRHPISGREV TLRCWALGFY PEEISLTWQR NGEDQTQDME
 LVETRPSGDG NFQKWAALLV PSGEEQKYTC QVQHEGLQEP LTLKWEPPQP
 SFLTMGIIVG LVLLVVTGAV VAGVVICMKK RSGEKRGTYI QASSSDSAQG
 SDVSLTVPKV X*

>P1;IPD:MHC03261
IPD:MHC03261 BoLA-N*05301, 361 bases, 4B4AA916 checksum.
 MGPRTLLLLL SGVLVLTETR AGSHSLRYFS TAVSRPGFGE PRYLEVGYVD
 DTQFVQFDSD APNPRMEPRA RWVEQEGPEY WDRNTRNAKG NAQSFRVNLN
 TLRGYYNQSE AGSHTLQWMS GCDVGPDGRL RRGFMQYGYD GRDYLALNED
 LRSWTAGETE AQITKRKWEA AGYAEVQRNY LEGECVEWLR RYLENGKDTL
 LRADPPKAHV THHPISDREV TLRCWALGFY PEEISLTWQH DGEDQTQDME
 LVETRPSGDG NFQKWVALVV PSGEEQKYTC RVQHEGLQEP LTLKWEPPQP
 SFLTMGIIVG LVLLVVTGAV VAGVVICMKK RSGEKRGTYI QASSSDSAQG
 SDVSLTVPKV X*

>P1;IPD:MHC03263
IPD:MHC03263 BoLA-N*05401, 354 bases, 4CC1AD9B checksum.
 LLLLLSGVLV LTETLAGSHS LRYFYTGVSR PGLGEPRFII VGYVDDTQFV
 RFDSNTPNPR MEPRARWVEQ EGPEYWDQET RNSKGAAQTF RANLNTLRGY
 YNQSEAGSHT FQWMYGCYVG PDGRLRRGFW QFGYDGRDYI ALNEDLRSWT
 AADTAAQITK RKWEAADNAE GERNYVEGRC VEGLRRYLEN GKDTLLRADP
 PKAHVAHHPI SDREVTLRCW ALGFYPEEIS LTWQREGEDQ TQDMELVETR
 PSGDGTFQKW AALVVPSGEE QRYTCRVQHE GLQEPLTLRW EPPQTSFLIM
 GIIVCLVLLV VALVAGAVIW RKKRSGEKGR IYTQAASSDS AQGSDVSLTV
 PKVX*

>P1;IPD:MHC03264
IPD:MHC03264 BoLA-N*05501, 354 bases, E494C173 checksum.
 LLLLLSGVLV LTETLAGSHS LRYFYTAVSR PGLGEPRFIA VGYVDDTQFT
 RFDSDAPNPR EEPRVPWMEQ EGPEYWDRET RISKETAQTF RVDLNSLRGY
 YNQSEAGSHT IQAMYGCDVG PDGRFLRGYR QDAYDGRDYI ALNEDLRSWT
 AADTAAQITK RKWEAADYAE SLRNYLEGRC VEGLRRYLEN GKDALLRADP
 PKAHVTRHPI SEREVTLRCW ALGFYPEEIS LTWQREGEDQ TQDMELVETR
 PSGDGTFQKW AALVVPSGEE QRYTCRVQHE GLREPLTLRW EPPQTSFLTM
 GIIVGLVLLV VAVVAGAVIW RKKRSGEKGR IYTQAASSDS AQGSDVSLTV
 PKVX*

>P1;IPD:MHC03265
IPD:MHC03265 BoLA-N*05601, 354 bases, A2B55669 checksum.
 LLLLLSGVLV LTETLAGSHS LRYFYTGVSR PGLGEPRFIA VGYVDDTQFV
 RFDSDAADPR TEPRVPWMEQ EGPEYWDQET RNFKDAAQTF RANLNTLLGY
 YNQSEAGSHT FQLMSGCDVG PDGRLLSGFT QYGYEGRDYI ALNEDLRSWT
 AADTAAQITK RKWEAEGAAE GHRNYLEGRC VEGLRRYLEN GKDALLRADP
 PKAHVTHHPI SDREVTLRCW ALGFYPEEIS LTWQCEGEDQ TQDMELVETM
 PSGDGTFQKW AALVVPSGEE QRYTCRVQHE GLQEPLTLRW EPPQTSFLTM
 GIIVGLVLLV VAVVAGAVIW RKKRSGEKGR IYTQAASSDS AQGSDVSLTV
 PKVX*

>P1;IPD:MHC02985
IPD:MHC02985 BoLA-NC1*00101, 334 bases, AE40A0BE checksum.
 LLLLLLGVLV PRDTRAGPHS MRYFLTAVSR PGLGEPRFIT VGYVDDTQFV
 RFDSDRPDPR MEPRARWVED EGPEYWDQET RIQKENTQTF RANLNTLLGY
 YNQSEAGSHT IQWMHGCGVG SDGRLLRGYN QHAYDGKDYL ALNEDLRSWT
 AADTAAQITK RKWEATGAAE RFRNYLEGKC VKLLRRHLEN GKDTLLRADP
 PMAHVTHHPI SEREVTLRCW ALGFYPEEIS LTWQRNGEDQ TQDMELVETR
 PSGDGTFQKW AALAVPSGEE QRYTCRVQHE GLQEPLTLRW EPPQPSVPIM
 GIILVLVLLV VAVVAGAVIW SKKRSGEKGR IYTX*

>P1;IPD:MHC03212
IPD:MHC03212 BoLA-NC1*00201, 323 bases, 49012298 checksum.
 LLLLLGVLVP RDTRAGPHSM RYFLTAVSRP GLGEPRFITV GYVDDTQFVR
 FDSDRPDPRM EPRARWVEDE GPEYWDQETR IQKENTQTFR ANLNTLLGYY
 NQSEAGSHTI QWMHGCGVGS DGRLLRGYNQ HAYDGKDYLA LNEDLRSWTA
 ADTAAQITKR KWEATGAAER FRNYLEGKCV KLLRRHLENG KDTLLRADPP
 MAHVTHHPIS EHEVTLRCWA LGFYPEEISL TWQRNGEDQT QDMELVETRP
 SGDGTFQKWA ALAVPSGEEQ RYTCRVQHEG LQEPLTLRWG IILVLVLLVV
 AVVAGAVIWS KKRSGEKGRI YTX*

>P1;IPD:MHC03213
IPD:MHC03213 BoLA-NC1*00301, 324 bases, 55D763B8 checksum.
 LLLLLGVLVP RDTRAGPHSM RYFLTAVSRP GLGEPRFITV GYVDDTQFVR
 FDSDRPDPRM EPRARWVEDE GPEYWDQETR IQKENTQTFR ANLNTLLGYY
 NQSEAGSHTI QWMHGCGVGS DGRLLRGYNQ HAYDGKDYLA LNEDLRSWTA
 ADTAAQITKR KWEATGAAER FRNYLEGKCV KLLRRHLENG KDTLLRADPP
 MAHVTHHPIS EREVTLRCWA LGFYPEEISL TWQRNGEDQT QDMELVETRP
 SGDGTFQKWA ALAVPSGEEQ RYTCRVQHEG LQEPLTLRWE PPQPSVPIMG
 IILVLVLLVV AVVAGAVIWS KKRX*

>P1;IPD:MHC03219
IPD:MHC03219 BoLA-NC1*00401, 318 bases, B90406C5 checksum.
 LLLLLGVLVP RDTRAGSHSL RYFLTAVSRP GLGEPRFITV GYVDDTQFVR
 FDSDRPDPRM EPRARWVEDE GPEYWDQETR IQKENTQTFR ANLNTLLGYY
 NQSEAGSHTI QWMHGCGVGS DGRLLRGYNQ HAYDGKDYLA LNEDLRSWTA
 ADTAAQITKR KWEAAGEAER FRNYLEGECV KLLRRHLENG KDTLLRADPP
 KAHVAHHPSS EREVTLRCWA LGFYPEEISL TWQRNGEDQT QDMELVETRP
 SGDGTFQKWA ALAVPSGEEQ RYTCRVQHEG LQGPLTLRWG EKGRIYTQAS
 SSDSAQGSDV SLTVPKVX*

>P1;IPD:MHC03214
IPD:MHC03214 BoLA-NC2*00101, 363 bases, A96EE4D3 checksum.
 MRVVGPRTLL LLLPGALILT ETRAGSHSLR YFYTAVSRPG LGEPRFISVG
 YVDDTQFVRF DSDAPDPRIE PTARWVEQEG PEYWHQETQR TKDTAQFFRV
 YLNTLRGYYN QSEAGSHTVQ EMYGCDVGPD GLLRGYDQFA YDGRDYIALN
 EDLRSWTAAD TAAQVTKHNA EAAGDAARVR IYLEGKCVEW LRRYLVTGKD
 TLLRADPPKT HVAHHPISDH EVTLRCWALG FYPDEISLTW QRDGEDQTQD
 MELVETRPSG DGTFQKWAAL VVPSGEEQRY TCHVQHEGLQ EPLTLRWEPP
 QPSIPIMGII VGLVLLMVTG AVVTGAMIWR KKHSGEKGRG YTQTASSYSD
 QGSDVSLMVP KVX*

>P1;IPD:MHC03215
IPD:MHC03215 BoLA-NC2*00102, 354 bases, A1B45E5B checksum.
 LLLLPGALIL TETWAGSHSL RYFYTAVSRP GLGEPRFISV GYVDDTQFVR
 FDSDAPDPRI EPTARWVEQE GPEYWHQETQ RTKDTAQFFR VYLNTLRGYY
 NQSEAGSHTV QEMYGCDVGP DGLLRGYDQF AYDGRDYIAL NEDLRSWTAA
 DTAAQVTKHN AEAAGDAARV RIYLEGKCVE WLRRYLVTGK DTLLRADPPK
 THVAHHPISD HEVTLRCWAL GFYPDEISLT WQRDGEDQTQ DMELVETRPS
 GDGTFQKWAA LVVPSGEEQR YTCHVQHEGL QEPLTLRWEP PQPSIPIMGI
 IVGLVLLMVT GAVVTGAMIW RKKHSGEKGR GYTQTASSYS DQGSDVSLMV
 PKVX*

>P1;IPD:MHC03216
IPD:MHC03216 BoLA-NC3*00101, 343 bases, B42F907A checksum.
 LLLLSGVLVL TETWAGSHSL SYFNTGVYQP GLGEPRFFAV GYVDDTQFAR
 FDSDAPNPRM EPRAPWMEQE GPEYWEEMTR DAKESQQESR LCLYNLRGYY
 NQSEAESHIL QVMFGCEVGP DGRLLRGFWQ KAYDGRDYIA LNEDLRSWTA
 ADTVAQITKR KWDVSGQAKI QRNYLEVKCV QWLLRHLETG KDTLLRADPP
 KTHVAHHRIS DREVTLRCWA LGFYPKEITL TWQQDGEDLT QDMELVETRP
 SGDGTFQKWA ALVVPSGEEQ RYTCRVQHEG LQEPLTLRWE PPQLSVLIKG
 IIVGLILLMV TGAVVTGAVI WRKKHSGEKG RGYTQTASSD SAX*

>P1;IPD:MHC03217
IPD:MHC03217 BoLA-NC4*00101, 355 bases, 27B5BE1B checksum.
 LLLLSEVLVL TETWAGSHSL SCFCTCVSRP GLGEPRFFAV GYVDDTQFAR
 FDSDAPNPRM EPRAPWMEQE GPEYWEAMTR DAKKAQQRLR TGLNTIRGFY
 NQSEAGSHTL QWVLGCDVGP EGRLLRGIWQ NAYDGADYLA LNEDLRSWTA
 ANTVAQITKR KWETSGEAEF QRNYLEVKCV QWLLRHLETG KDTLLRADPP
 KTHVAHHPIS DREVTLRCWA LGFYPEEISL TWQRDGEDQT QDMELVETRP
 SGDGTFQKWA ALVVPSGEEQ RYTCHVQHEG LQEPLSLRWK PPQPSIPIMD
 IIVGLVLLMV TGAVVTGAVI WRKKHSGQIG KGYTQSASSD SAQGSDVSLM
 VPKVX*

>P1;IPD:MHC03218
IPD:MHC03218 BoLA-NC4*00201, 355 bases, 3AA3A1EB checksum.
 LLLLSEVLVL TETWAGSHSL SYFCTCVSRP GLGEPRFFAV GYVDDTQFAR
 FDSDAPNPRM EPRAPWMEQE GPEYWEAMTR DAKKAQQRLR TGLNTIRGFY
 NQSEAGSHTL QWVLGCDVGL DGRLLRGIWQ NAYDGADYLA LNEDLRSWTA
 ANTVAQITKR KWETSGEAEF QRNYLEVKCV QWLLRHLETG KDTLLRADPP
 KTHVAHHPIS DREVTLRCWA LGFYPEEISL TWQCDGEDQT QDMELVETRP
 SGDGTFQKWA ALVVPSGEEQ RYTCHVQHEG LQEPLSLRWK PPQPSIPIMG
 IIVGLVLLMV TGAVVTGAVI WRKKHSGQTG RGYTQAASSD SAQGSDVSLM
 VPKVX*

