>P1;BoLA-DQA*0101
BoLA-DQA*0101, 256 bases, CB04F7F7 checksum.
 MILNRALIWG ALALTTMMGP SGSEDIVADH IGAYGINVYH TYGPSGYYTH
 EFDGDEEFYV DLEKRETVWR LPVFSKFTSF DPQGALRNIA TAKHNLEVLI
 QRSNSTAATN KVPEMTVFPK SPVMLGQPNT LICHVDNIFP PVINITWLRN
 GHLVIEGISE TSFLSKDDHS FAKISYLTFL PSDDDVYDCK VEHWGLDKPL
 LKHWEPEIPA PMSELTETVV CALGLTVGLV GIVVGTVLII RGLRSGGPSR
 HQGPLX*

>P1;BoLA-DQA*0102
BoLA-DQA*0102, 82 bases, 8374A63C checksum.
 DHIGAYGINV YHTYGPSGYY THEFDGDEEF YVDLEKRETV WRLPVFSKFT
 SFDPQGALRN IATVKHNLEI LIQRSNSTAA TN*

>P1;BoLA-DQA*0103
BoLA-DQA*0103, 82 bases, 875257A1 checksum.
 DHIGAYGINV YHTYGPSGYY THEFDGDEEF YVDLEKRETV WRLPVFSKFT
 SFDPQGALRN IATTKHNLEI MIRRSNSTAA TN*

>P1;BoLA-DQA*0201
BoLA-DQA*0201, 230 bases, AB492FF7 checksum.
 VADHIGRYGI NVYHTYGPSG YYTHEFDGDE EFYVDLEKRE TVWNLPLFSK
 FRRFDPQGAL RNIATVKHNL EIVIQRSNST AATNKVPEVT VFSKSPMMLG
 QPNTLICHVD NIFPPVINIT WLKNGHLVIE GISETSFLSK DDHSFSKISY
 LTFLPSDDDV YDCKVEHWGL DKPLLKHWEP DIPAPMSELT ETVVCALGLT
 VGLVGIVVGT VLIIRGLRSG GPSRDQGPLX*

>P1;BoLA-DQA*0202
BoLA-DQA*0202, 75 bases, 5E312601 checksum.
 AYGINVYHTY GPSGYFTHEF DGDEEFYVDL EKRETVWNLP LFSKFRRFDP
 QGALRNIATV KHNLEIVIQR SNSTA*

>P1;BoLA-DQA*0203
BoLA-DQA*0203, 82 bases, 8128DA4D checksum.
 DHIGAYGINV YHTYGPSGYY THEFDGDEEF YVDLEKRETV WNLPLFSKFR
 RFDPQGALRN IATVKHNLEI VIQRSNSTAA TN*

>P1;BoLA-DQA*0204
BoLA-DQA*0204, 82 bases, D8546A0C checksum.
 DHIGAYGINV YHTYGPSGYY THEFDGDEEF YVDLEKRETV WNLPLFSKFR
 RFDPQGALRN IATAKHNLEI VIQRSNSTAA TN*

>P1;BoLA-DQA*0301
BoLA-DQA*0301, 82 bases, 6D8C499C checksum.
 DHIGAYGINV YHSYGPSGYY THEFDGDEEF YVDLEKRETV WNLPLFSKFR
 RFDPQGALRN IATTKHNLEI MMQRSNSTAA TN*

>P1;BoLA-DQA*0302
BoLA-DQA*0302, 74 bases, 503C4FEF checksum.
 AYGINVYHSY GPSGYYTHEF DGDEEFYVDL EKRETVWNLP LFSKFRRFDP
 RGALRNIATT KHNLEIMMQG SNST*

>P1;BoLA-DQA*0401
BoLA-DQA*0401, 82 bases, 9F881483 checksum.
 DHIGAYGINV YHSYGPSGYY THEFDGDEEF YVDLEKRETV WNLPLFSKFR
 RFDPQGALRN IATAKHNLEV LIQRSNSTTA TN*

>P1;BoLA-DQA*0801
BoLA-DQA*0801, 82 bases, F47037CF checksum.
 DHIGAYGINV YHSYGPSGYY THEFDGDEQF YVDLEKRETV WRLPVFSKFA
 SFDPQGALRN IATAKHNLEI MIQESNSTAA TN*

>P1;BoLA-DQA*0802
BoLA-DQA*0802, 82 bases, C1BFB84C checksum.
 DHIGAYGINV YHSYGPSGYY THEFDGDEQF YVDLEKRETV WRLHVFSKFA
 SFDPQGALRN IATAKHNLEI MIQESNSTAS TN*

>P1;BoLA-DQA*10011
BoLA-DQA*10011, 82 bases, 609646D2 checksum.
 DHIGTYGISV YHTYGPSGYY THEFDGDEEF YVDLEKRETV WRLPVFSKFT
 SFDPQGALRN IAIVKHNLEI VIQRSNSTAA TN*

>P1;BoLA-DQA*10012
BoLA-DQA*10012, 82 bases, 609646D2 checksum.
 DHIGTYGISV YHTYGPSGYY THEFDGDEEF YVDLEKRETV WRLPVFSKFT
 SFDPQGALRN IAIVKHNLEI VIQRSNSTAA TN*

>P1;BoLA-DQA*1002
BoLA-DQA*1002, 80 bases, 571F9462 checksum.
 DHIGAYGINV YHTYGPSGYY THEFDGDEEF YVDLEKRETV WRLPVFSKFT
 SFDPQGALRN IAIVKHNLDI VIQRSNSTAA*

>P1;BoLA-DQA*1101
BoLA-DQA*1101, 82 bases, 5088C19F checksum.
 DHIGAYGINV YHTYGPSGYY THEFDGDEEF YVDLEKRETV WRLPVFSKFA
 TFDPQGALRN IATMKHNLEI VIQRSNSTAA TN*

>P1;BoLA-DQA*12011
BoLA-DQA*12011, 256 bases, 6992E43E checksum.
 MVLNRALILG ALALTTMMSP SGSEDIVADH IGTYGISVYH TYGPSGYYTH
 EFDGDEEFYV DLEKRETVWR LPVFSKFATF DPQGALRNIA TTKHNLEIVI
 QRSNSTAATN KVPEVTVFSK SPVMLGQPNT LICHVDNIFP PVINITWLRN
 GHSVTEGVSE TSFLIKSDYS FLKINYLTFL PSDDDVYDCK VEHWGLDEPL
 LKHWEPDIPA PMSELTETVV CALGLTVGLV GIMVGTILII QGLRSGGPSR
 HQGPLX*

>P1;BoLA-DQA*12012
BoLA-DQA*12012, 75 bases, D5EDE391 checksum.
 TYGISVYHTY GPSGYYTHEF DGDEEFYVDL EKRETVWRLP VFSKFATFDP
 QGALRNIATT KHNLEIVIQR SNSTA*

>P1;BoLA-DQA*12021
BoLA-DQA*12021, 256 bases, 8C1638AB checksum.
 MILNRALILG ALALTTMMSP SGSEDIVADH IGTYGISVYH TYGPSGYYTH
 EFDGDEEFYV DLEKRETVWR LPVFSKFATF DPQGALRNIA TMKHNLEIVI
 QRSNSTAATN KVPEVTVFSK SPVMLGQPNT LICHVDNIFP PVINITWLRN
 GHSVTEGVSE TSFLIKSDYS FLKINYLTFL PSDDDVYDCK VEHWGLDEPL
 LKHWEPDIPA PMSELTETVV CALGLTVGLV GIMVGTILII QGLRSGGPSR
 HQGPLX*

>P1;BoLA-DQA*12022
BoLA-DQA*12022, 82 bases, 3D28964 checksum.
 DHIGTYGISV YHTYGPSGYY THEFDGDEEF YVDLEKRETV WRLPVFSKFA
 TFDPQGALRN IATMKHNLEI VIQRSNSTAA TN*

>P1;BoLA-DQA*1203
BoLA-DQA*1203, 228 bases, 3ED20272 checksum.
 DHIGTYGISV YHTYGPSGYY THEFDGDEEF YVDLEKRETV WRLPVFSKFA
 TFDPQGALRN IATSKHDLEV LIQRSNSTAA TNKVPEVTVF SKSPVMLGQP
 NTLICHVDNI FPPVINITWL RNGHSVTEGV SETSFLIKSD YSFLKINYLT
 FLPSDDDVYD CKVEHWGLDE PLLKHWEPDI PAPMSELTET VVCALGLTVG
 LVGIMVGTIL IIQGLRSGGP SRHQGPLX*

>P1;BoLA-DQA*1204
BoLA-DQA*1204, 80 bases, 31B79779 checksum.
 DHIGTYGISI YHSYGPSGYY THEFDGDEEF YVDLEKRETV WRLPVFSKFA
 TFDPQGALRN IATTKHNLEI VIQRSNSTAA*

>P1;BoLA-DQA*1301
BoLA-DQA*1301, 75 bases, B5F4AC60 checksum.
 AYGINVYHSY GPSGYYTHEF DGDEQFYVDL EKKETVWRLP VFSKFATFDP
 QGALRNIAVG KQTLEVMIRR SNSTA*

>P1;BoLA-DQA*1302
BoLA-DQA*1302, 74 bases, DE464C6 checksum.
 AYGINVYHTY GPSGYYTHEF DGDEQFYVDL EKKETVWRLP VFSKFATFDP
 QGALRNIAVG KQTLEVMIRR SNST*

>P1;BoLA-DQA*1401
BoLA-DQA*1401, 82 bases, 38A6522A checksum.
 DHIGAYGINV YHSYGPSGYY THEFDGDEEF YVDLEKRETV WRLPVFSKFA
 SFDPQGALRN IAVGKRTLEV MIRRSNSTAA TN*

>P1;BoLA-DQA*2001
BoLA-DQA*2001, 74 bases, 254C19BC checksum.
 SYGTEVYQSH GPSGQYTQEF DGDEMFYVDL GKKETVWRLP SFSQFAGFDP
 QAALSEIATS KHNLDVLTKR SNFT*

>P1;BoLA-DQA*2002
BoLA-DQA*2002, 82 bases, 83E6DC63 checksum.
 DHVGSYGTEV YQSHGPSGQY TQEFDGDEMF YVDLGKKETV WRLPTFSQFA
 GFDPQAALSE IATSKHNLDV LTKRSNFTPV IN*

>P1;BoLA-DQA*2101
BoLA-DQA*2101, 82 bases, 85D893B7 checksum.
 DHVGSYGTEV YQSHGPSGQY TQEFDGDEMF YVDLGKKETV WRLPIFSQFA
 GFDPQFALSE IATSKHNLDV LTKRSNFTPV IN*

>P1;BoLA-DQA*2201
BoLA-DQA*2201, 256 bases, 75455987 checksum.
 MVLNRALILG ALALTTMMSP NGGEDIVADH VGSYGTEVYQ SHGPSGQYTQ
 EFDGDEMFYV DLGKKETVWR LPMFSQFAGF DPQAALSEIA TSKHNLDVLT
 KRSNFTPVIN EVPEVTVFSK SPVILSQPNT LICHVDNIFP PVINITWLKN
 GHAVTEGVSE TSFLPKDDHS FLKIGYLTFL PSDNDIYDCK VEHWGLDEPL
 LKHWEPEVPA PMSELTETVV CALGLTVGLV GIVVGTIFII QGLRSGGTSR
 HQGPLX*

>P1;BoLA-DQA*22021
BoLA-DQA*22021, 256 bases, CEC93179 checksum.
 MVLNRALILG ALALTTMMSP SGGEDIVADH VGSYGTEVYQ SHGPSGQYTQ
 EFDGDEMFYV DLGKKETVWR LPMFSQFAGF DPQAALSEIA TAKHNLDVLT
 KRSNFTPVIN EVPEVTVFSK SPVMLGQPNT LICHVDNIFP PVINITWLKN
 GHAVTEGVSE TSFLPKDDHS FLKIGYLTFL PSDNDIYDCK VEHWGLDEPL
 LKHWEPEVPA PMSELTETVV CALGLTVGLV GIVVGTIFII QGLRSGGASR
 HQGPLX*

>P1;BoLA-DQA*22022
BoLA-DQA*22022, 74 bases, C8704784 checksum.
 SYGTEVYQSH GPSGQYTQEF DGDEMFYVDL GKKETVWRLP MFSQFAGFDP
 QAALSEIATA KHNLDVLTKR SNFT*

>P1;BoLA-DQA*22023
BoLA-DQA*22023, 82 bases, 6B4B1581 checksum.
 DHVGSYGTEV YQSHGPSGQY TQEFDGDEMF YVDLGKKETV WRLPMFSQFA
 GFDPQAALSE IATAKHNLDV LTKRSNFTPV IN*

>P1;BoLA-DQA*22031
BoLA-DQA*22031, 82 bases, 6AEEBC37 checksum.
 DHVGSYGTEV YQSHGPSGQY TQEFDGDELF YVDLGKKETV WRLPMFSQFA
 GFDPQAALSE IATAKHNLDV LTKRSNFTPV IN*

>P1;BoLA-DQA*22032
BoLA-DQA*22032, 74 bases, 4C415E75 checksum.
 SYGTEVYQSH GPSGQYTQEF DGDELFYVDL GKKETVWRLP MFSQFAGFDP
 QAALSEIATA KHNLDVLTKR SNFT*

>P1;BoLA-DQA*2204
BoLA-DQA*2204, 82 bases, A073C5F9 checksum.
 DHVGSYGTEV YQSHGPSGQY TQEFDGDEMF YVDLGKKETV WRLLMFSQFA
 GFDPQAALSE IATAKHNLDV LTKRSNFTPV IN*

>P1;BoLA-DQA*2205
BoLA-DQA*2205, 74 bases, E91D5913 checksum.
 SYGTEVYQSH GPSGQYTQEF DGDEMFYVDL GKKETVWRLP MFSQFAGFAP
 QAALSEIATS KHNLDVLTKR SNFT*

>P1;BoLA-DQA*2207
BoLA-DQA*2207, 75 bases, AEB67A04 checksum.
 AEFYQSHGPS GQYTQEFDGD ELFYVDLGKK ETVWRLPMFS QFAGFDPQAA
 LSEIATAKHN LDVLTKRSNF TPVIN*

>P1;BoLA-DQA*2301
BoLA-DQA*2301, 74 bases, B617EBC1 checksum.
 SYGIDFYQSH GPSGQYIHEF DGDEMFYVDL GKKETVWRLP MFGELTGFDP
 QGALRNIATE KHNLDILTKC SNFT*

>P1;BoLA-DQA*2401
BoLA-DQA*2401, 82 bases, 4B19E1BB checksum.
 DHVGSYGTEV YQSHGPSGQY THEFDGDELF YVDLGKKETV WRLPMFGDLT
 SFDPQGALSE IATSKHNLDI LTRRSNFTPA IN*

>P1;BoLA-DQA*25011
BoLA-DQA*25011, 81 bases, 74D68338 checksum.
 DHVGTYGTDF YQSHGPSGQY IHQFDGDEEF YVDLEKEEAV WRLPMFDKLR
 FHPQGALRNI AIAKHNLDVL TKLYNFTPVI N*

>P1;BoLA-DQA*25012
BoLA-DQA*25012, 81 bases, 74D68338 checksum.
 DHVGTYGTDF YQSHGPSGQY IHQFDGDEEF YVDLEKEEAV WRLPMFDKLR
 FHPQGALRNI AIAKHNLDVL TKLYNFTPVI N*

>P1;BoLA-DQA*2502
BoLA-DQA*2502, 81 bases, 1732CC35 checksum.
 DHVGTYGADF YQSHGPSGQY IHQFDGDEEF YVDLEKEEAV WRLPMFDKLR
 FHPQGALRNI AIAKHNLDVL TKLYNFTPVI N*

>P1;BoLA-DQA*2601
BoLA-DQA*2601, 74 bases, B183FFC7 checksum.
 TYGTDFYQSH GPSGQYIHQF DGDEEFYVDL EKEEAVWRLP MFDKLRRFHP
 QGALRDIAVA KHNLDVLTKR YNFT*

>P1;BoLA-DQA*2602
BoLA-DQA*2602, 74 bases, CC96E4B3 checksum.
 TYGTDFYQSH GPSGQYIHQF DGDEEFYVDL EKEEAVWRLP MFDKLRRFHP
 QGALRNIAVA KHNLDVLTKR YNFT*

>P1;BoLA-DQA*2603
BoLA-DQA*2603, 78 bases, DE19628F checksum.
 TYGTDFYQSH GPSGQYIHQF DGDEEFYVDL EKEEAVWRLP MFDKLRRFHP
 QGALRNIAIA KHNLDVLTKL YNFTPVIN*

>P1;BoLA-DQA*27011
BoLA-DQA*27011, 82 bases, 2DB95AA4 checksum.
 DHIGTYGADF YQSHGPSGQY IHEFDGDELF YVDLGKKETV WQLPMFGELT
 SFEAQDALNE IAKAKHTLDV LTKRSNFTPV IN*

>P1;BoLA-DQA*27012
BoLA-DQA*27012, 74 bases, 14CC8353 checksum.
 TYGADFYQSH GPSGQYIHEF DGDELFYVDL GKKETVWQLP MFGELTSFEA
 QDALNEIAKA KHTLDVLTKR SNFT*

>P1;BoLA-DQA*2702
BoLA-DQA*2702, 82 bases, CAF6BBFF checksum.
 DHIGTYGAEF YQSHGPSGQY IHEFDGDELF YVDLGKKETV WQLPMFGELT
 SFEAQDALNE IAKAKHTLDV LTKRSNFTPV IN*

>P1;BoLA-DQA*2801
BoLA-DQA*2801, 75 bases, F45FF557 checksum.
 IYGISVYQSY GPSGQYTHEF DGDEQFYVDL EKKETAWQLP LFSRMLSFDP
 QLALRNIAIM KLHVDFLTKF SNSTA*

