>P1;Bubu-DQA*0101
Bubu-DQA*0101, 256 bases, DA9701A5 checksum.
 MVLNRALILG ALALTTMMSP SGSEDIVADH IGAYGINVYH SYGPSGYYTH
 EFDGDEEFYV DLEKKETVWH LPLFSKFTSF DPQGALRNIA NAKYNLEIMI
 QESNSTAATN KVPEVTVFSK SPVMLDQPNT LICHVDNIFP PVISITWLRN
 GHSVIEGVSE TSFLSKDDHS FSKISYLTFL PSDDDVYDCK VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLTVGLV GIVVGTVLII RGLRSGGPSR
 HQGPLX*

>P1;Bubu-DQA*2001
Bubu-DQA*2001, 256 bases, 14A9380B checksum.
 MVLNRALILG ALALTTMMSP SGGEDIVADH VGSYGTEIYQ SHGPSGQYTQ
 EFDGDEMFYV DLGKKETVWR LPMFSQFAGF DPQAALSEIA TSKHNLDVLT
 KRSNFTPVIN EVPEVTVFSK SPVMLGQPNT LICHVDNIFP PVINITWLKN
 GHSVTEGVSE TSFLSKDDHS FLKIGYLTFL PSDDDVYDCK VEHWGLDEPL
 LKHWEPEVPA PMSELTETVV CALGLTVGLV GIVVGTIFII QGLRSGGASR
 HQGPLX*

