>P1;SLA-DRA_010101
SLA-DRA_010101, 253 bases, E5100A53 checksum.
 MTILGVPVLG FVITILNLQK SWAIVENHVI IQAEFYLSPD KSGEFMFDFD
 GDEIFHVDME KRETVWRLEE FGHFASFEAQ GALANIAVDK ANLEIMIKRS
 NNTPNTNVPP EVTVLSDKPV ELGEPNILIC FIDKFSPPVV NVTWLRNGSP
 VTRGVSETVF LPREDHLFRK FHYLPFMPST EDVYDCQVEH WGLDKPLLKH
 WEFEAQTPLP ETTENTVCAL GLIVALVGII VGTVLIIKGV RKGNATERRG
 PLX*

>P1;SLA-DRA_010102
SLA-DRA_010102, 253 bases, E5100A53 checksum.
 MTILGVPVLG FVITILNLQK SWAIVENHVI IQAEFYLSPD KSGEFMFDFD
 GDEIFHVDME KRETVWRLEE FGHFASFEAQ GALANIAVDK ANLEIMIKRS
 NNTPNTNVPP EVTVLSDKPV ELGEPNILIC FIDKFSPPVV NVTWLRNGSP
 VTRGVSETVF LPREDHLFRK FHYLPFMPST EDVYDCQVEH WGLDKPLLKH
 WEFEAQTPLP ETTENTVCAL GLIVALVGII VGTVLIIKGV RKGNATERRG
 PLX*

>P1;SLA-DRA_010103
SLA-DRA_010103, 253 bases, E5100A53 checksum.
 MTILGVPVLG FVITILNLQK SWAIVENHVI IQAEFYLSPD KSGEFMFDFD
 GDEIFHVDME KRETVWRLEE FGHFASFEAQ GALANIAVDK ANLEIMIKRS
 NNTPNTNVPP EVTVLSDKPV ELGEPNILIC FIDKFSPPVV NVTWLRNGSP
 VTRGVSETVF LPREDHLFRK FHYLPFMPST EDVYDCQVEH WGLDKPLLKH
 WEFEAQTPLP ETTENTVCAL GLIVALVGII VGTVLIIKGV RKGNATERRG
 PLX*

>P1;SLA-DRA_0101we01
SLA-DRA_0101we01, 253 bases, E5100A53 checksum.
 MTILGVPVLG FVITILNLQK SWAIVENHVI IQAEFYLSPD KSGEFMFDFD
 GDEIFHVDME KRETVWRLEE FGHFASFEAQ GALANIAVDK ANLEIMIKRS
 NNTPNTNVPP EVTVLSDKPV ELGEPNILIC FIDKFSPPVV NVTWLRNGSP
 VTRGVSETVF LPREDHLFRK FHYLPFMPST EDVYDCQVEH WGLDKPLLKH
 WEFEAQTPLP ETTENTVCAL GLIVALVGII VGTVLIIKGV RKGNATERRG
 PLX*

>P1;SLA-DRA_0201
SLA-DRA_0201, 253 bases, AF945345 checksum.
 MTILGVPVLG FVITILNLQK SWAIVENHVI IQAEFYLSPD KSGEFMFDFD
 GDEIFHVDME KRETVWRLEE FGHFASFEAQ GALANIAVDK ANLEILIKRS
 NNTPNTNVPP EVTVLSDKPV ELGEPNILIC FIDKFSPPVV NVTWLRNGSP
 VTRGVSETVF LPREDHLFRK FHYLPFMPST EDVYDCQVEH WGLDKPLLKH
 WEFEAQTPLP ETTENTVCAL GLIVALVGII VGTVLIIKGV RKGNATEHRG
 PLX*

>P1;SLA-DRA_0201jh01
SLA-DRA_0201jh01, 253 bases, AF945345 checksum.
 MTILGVPVLG FVITILNLQK SWAIVENHVI IQAEFYLSPD KSGEFMFDFD
 GDEIFHVDME KRETVWRLEE FGHFASFEAQ GALANIAVDK ANLEILIKRS
 NNTPNTNVPP EVTVLSDKPV ELGEPNILIC FIDKFSPPVV NVTWLRNGSP
 VTRGVSETVF LPREDHLFRK FHYLPFMPST EDVYDCQVEH WGLDKPLLKH
 WEFEAQTPLP ETTENTVCAL GLIVALVGII VGTVLIIKGV RKGNATEHRG
 PLX*

>P1;SLA-DRA_020201
SLA-DRA_020201, 253 bases, DD972B8 checksum.
 MTILGVPVLG FVITILNLQK SWAIVENHVI IQAEFYLSPD KSGEFMFDFD
 GDEIFHVDME KRETVWRLEE FGHFASFEAQ GALANIAVDK ANLEILIKRS
 NNTPNTNVPP EVTVLSDKPV ELGEPNILIC FIDKFSPPVV NVTWLRNGSP
 VTRGVSETVF LPREDHLFRK FHYLPFMPST EDVYDCQVEH WGLDKPLLKH
 WEFEAQTPLP ETTENTVCAL GLIVALVGII VGTVLIIKGV RKGNATERRG
 PLX*

>P1;SLA-DRA_020202
SLA-DRA_020202, 253 bases, DD972B8 checksum.
 MTILGVPVLG FVITILNLQK SWAIVENHVI IQAEFYLSPD KSGEFMFDFD
 GDEIFHVDME KRETVWRLEE FGHFASFEAQ GALANIAVDK ANLEILIKRS
 NNTPNTNVPP EVTVLSDKPV ELGEPNILIC FIDKFSPPVV NVTWLRNGSP
 VTRGVSETVF LPREDHLFRK FHYLPFMPST EDVYDCQVEH WGLDKPLLKH
 WEFEAQTPLP ETTENTVCAL GLIVALVGII VGTVLIIKGV RKGNATERRG
 PLX*

>P1;SLA-DRA_020203
SLA-DRA_020203, 253 bases, DD972B8 checksum.
 MTILGVPVLG FVITILNLQK SWAIVENHVI IQAEFYLSPD KSGEFMFDFD
 GDEIFHVDME KRETVWRLEE FGHFASFEAQ GALANIAVDK ANLEILIKRS
 NNTPNTNVPP EVTVLSDKPV ELGEPNILIC FIDKFSPPVV NVTWLRNGSP
 VTRGVSETVF LPREDHLFRK FHYLPFMPST EDVYDCQVEH WGLDKPLLKH
 WEFEAQTPLP ETTENTVCAL GLIVALVGII VGTVLIIKGV RKGNATERRG
 PLX*

>P1;SLA-DRA_0202Lw02
SLA-DRA_0202Lw02, 253 bases, DD972B8 checksum.
 MTILGVPVLG FVITILNLQK SWAIVENHVI IQAEFYLSPD KSGEFMFDFD
 GDEIFHVDME KRETVWRLEE FGHFASFEAQ GALANIAVDK ANLEILIKRS
 NNTPNTNVPP EVTVLSDKPV ELGEPNILIC FIDKFSPPVV NVTWLRNGSP
 VTRGVSETVF LPREDHLFRK FHYLPFMPST EDVYDCQVEH WGLDKPLLKH
 WEFEAQTPLP ETTENTVCAL GLIVALVGII VGTVLIIKGV RKGNATERRG
 PLX*

>P1;SLA-DRA_020301
SLA-DRA_020301, 253 bases, 4B0B47DC checksum.
 MTILGVPVLG FVITILNLQK SWAIVENHVI IQAEFYLSPD KSGEFMFDFD
 GDEIFHVDME KRETVWRLEE FGHFASFEAQ GALANIAVDK ANLEILIKRS
 NNTPNTNVPP EVTVLSDKPV ELGEPNILIC FIDKFSPPVV NVTWLRNGSP
 VTRGVSETVF LPREDHLFRK FHYLPFMPST EDVYDCQVEH WGLDKPLLKH
 WEFEARTPLP ETTENTVCAL GLIVALVGII VGTVLIIKGV RKGNATERRG
 PLX*

>P1;SLA-DRA_0203my01
SLA-DRA_0203my01, 253 bases, 4B0B47DC checksum.
 MTILGVPVLG FVITILNLQK SWAIVENHVI IQAEFYLSPD KSGEFMFDFD
 GDEIFHVDME KRETVWRLEE FGHFASFEAQ GALANIAVDK ANLEILIKRS
 NNTPNTNVPP EVTVLSDKPV ELGEPNILIC FIDKFSPPVV NVTWLRNGSP
 VTRGVSETVF LPREDHLFRK FHYLPFMPST EDVYDCQVEH WGLDKPLLKH
 WEFEARTPLP ETTENTVCAL GLIVALVGII VGTVLIIKGV RKGNATERRG
 PLX*

>P1;SLA-DRA_w03ta01
SLA-DRA_w03ta01, 253 bases, 126C5E42 checksum.
 MTILGVPVLG FVITILNLQK SWAIVENHVI IQAEFYLSPD KSGEFMFDFD
 GDEIFHVDME KRETVWRLEE FGHFASFEAQ GALANIAVDK ANLEIVIKRS
 NNTPNTNVPP EVTVLSDKPV ELGEPNILIC FIDKFSPPVV NVTWLRNGSP
 VTRGVSETVF LPREDHLFRK FHCLPFMPST EDVYDCQVEH WGLDKPLLKH
 WEFEAQTPLP ETTENTVCAL GLIVALVGII VGTVLIIKGV RKGNATERRG
 PLX*

