>DL;SLA-DQB1_0101
SLA-DQB1_0101, 786 bases, 2A98A58A checksum.
 ATGTCTGGGA TGGTGGCTCT GCGGCTCCCC AGAGGCCTTT GGACAGCGGC
 CGTGACGATG ATGCTGGTGG TGCTGGGTGC TCCGGTGGCT GAGGGCAGAG
 ACTCTCCACA GGATTTCGTG TTCCAGTTTA AGTTCGAGTG CTACTTCTTC
 AACGGAACGC AGCGGGTGCG GCTCGTGGCC AGATACATCT ACAACCAGGA
 GGAGCTTTTG CGCTTCGACA GCGACGTGGG GGAATACCGG GCGGTGACCC
 CGCTGGGGCG GCCGGAGGCC GACTCCTGGA ACGGCCAGAA GGACGTCCTG
 GAGCAGACGC GGGCCGAGCT GGACACGGTG TGCAAACACA ACTACCAGAT
 AGAGGAAGGC ACGACTCTGC AGCGGCGAGT GCAACCTACA GTGACTATCT
 CCCCATCCAA GGCAGAGGCT CTAAACCACC ACAACCTGCT GGTCTGTGCG
 GTGACAGATT TCTATCCAAG CCAGGTGAAA GTCCAGTGGT TCCGGAATGG
 CCAGGAGGAG ACAGCTGGCG TTGTGTCCAC TCCTCTTATT AGGAACGGAG
 ACTGGACCTA CCAGGTGCTC GTGATGCTAG AGATGAATCT CCAGCGAGGA
 GATGTCTACA CCTGCCGCGT GGAGCACTCC AGCCTCCAGA GCCCCATCTT
 GGTGGAGTGG CGGGCACAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGCG
 GTGTCGGGGG CTTCGTGCTG GGGCTGATCT TCCTCGGGCT GGGCCTTTTC
 ATCCGTCACA GGAGTCAGAA GGGGCTCGTG CGCTGA*

>DL;SLA-DQB1_01Lu01
SLA-DQB1_01Lu01, 270 bases, A84D35A7 checksum.
 AGGATTTCGT GTTCCAGTTT AAGTTCGAGT GCTACTTATC CAACGGAACG
 CAGCGGGTGC GGCTCGTGAC CAGATACATC TACAACCAGG AGGAGCTTTT
 GCGCTTCGAC AGCGACGTGG GGGAATACCG GGCGGTGACC CCGCTGGGGC
 GGCCGGAGGC CGACTCCTGG AACGGCCAGA AGGACGTCAT GGAGCAGACG
 CGGGCCGAGC TGGACACGGT GTGCAAACAC AACTACCAGA TAGAGGAAGG
 CACGACTCTG CAGCGGCGAG*

>DL;SLA-DQB1_01be01
SLA-DQB1_01be01, 270 bases, 146DB442 checksum.
 AGGATTTCGT GTTCCAGTTT AAGTTAGAGT GCTACTTCTT CAACGGAACG
 CAGCGGGTGC GGCTCGTGGC CAGATACATC TACAACCAGG AGGAGCTTTT
 GCGCTTCGAC AGCGACGTGG GGGAATACCG GGCGGTGACC CCGCTGGGGC
 GGCCGGAGGC CGACTCCTGG AACGGCCAGA AGGACGTCCT GGAGCAGACG
 CGGGCCGAGC TGGACACGGT GTGCAAACAC AACTACCAGA TAGAGGAAGG
 CGCGACTCTG CAGCGGCGAG*

>DL;SLA-DQB1_01ha02
SLA-DQB1_01ha02, 270 bases, D9EA1CA0 checksum.
 AGGATTTCGT GTTCCAGTTT AAGTTCGAGT GCTACTTCTT CAACGGAGCG
 CAGCGGGTGC GGCTCGTGGC CAGATACATC TACAACCAGG AGGAGCTTTT
 GCGCTTCGAC AGCGACGTGG GGGAATACCA GGCGGTGACC CCGCTGGGGC
 GGCCGGAGGC CGACTCCTGG AACGGCCGGA AGGACGTCCT GGAGCAGACG
 CGGGCCGAGC TGGACACGGT GTGCAAACAC AACTACCAGA TAGAGGAAGG
 CACGACTCTG CAGCGGCGAG*

>DL;SLA-DQB1_01me03
SLA-DQB1_01me03, 270 bases, 54823472 checksum.
 AGGATTTCGT GTTACAGTTT AAGTTCGAGT GCTACTTCTT CAACGGAACA
 CAGCGGGTGC GGCTCGTGGC CAGATACATC TACAACCAGG AGGAGCTTTT
 GCGCTTCGAC AGCGACGTGG GGGAATACCA GGCGGTGACC ACGCTGGGGC
 GGCCGGAGGC CGACTCCTGG AACGGCCAGA AGGACGTCCT GGAGCAGACG
 CGGGCCGAGC TGGACACGGT GTGCAAACAC AACTACCAGA TAAAGGAAGG
 CACGACTCTG CAGCGGCGAG*

>DL;SLA-DQB1_01sh01
SLA-DQB1_01sh01, 279 bases, AC111303 checksum.
 AGAGACTCTC CACAGGATTT CGTGTACCAG TTTAAGTTCG AGTGCTACTT
 CTTCAACGGA ACGCAGCGGG TGCGGCTCGT GACCAGATAC ATCTACAACC
 AGGAGGAGCT TTTGCGCTTC GACAGCGACG TGGGGGAATA CCGGGCGGTG
 ACCCCGCTGG GGCGGCCGGA GGCCGACTCC TGGAACGGCC AGAAGGACGT
 CCTGGAGCAG ACGCGGGCCG AGCTGGACAC GGTGTGCAAA CACAACTACC
 AGATGGAGGA AGGCACGACT CTGCAGCGG*

>DL;SLA-DQB1_0201
SLA-DQB1_0201, 786 bases, DCDAA318 checksum.
 ATGTCTGGGA TGGTGGCTCT GCGGCTCCCC AGAGGCCTTT GGACAGCGGC
 CTTGACGGTG ATGCTGGTGG TGCTGGGTGC TCCAGTGGCT GAGGGCAGAG
 ACTCTCCACA GGATTTCGTG TACCAGTTTA AGTTCGAGTG CTACTTCTTC
 AACGGAACGC AGCGGGTGCG GGGCGTGGCC AGGTGGGTCT ACAACCAGGA
 GGAGCACGTG CGCTTCGACA GCGACGTGGG GGAGTTCCGG GCGGTGACCC
 CGCTGGGGCG GCCGACCGCC GACTACTGGA ACGGCCAGAA GGACGTCCTG
 GAGCAGAAGC GGGCCGAGGT GGACACGGTG TGCAAACACA ACTACCAGAT
 AGAGGAAGGC ACGACCCTGC AGCGGCGAGT GCAACCTACA GTGACTATCT
 CCCCATCCAA GGCAGAGGCT CTAAACCACC ACAACCTGCT GGTCTGTGCG
 GTGACAGATT TCTATCCAAG CCAGGTGAAA GTCCAGTGGT TCCGGAATGG
 CCAGGAGGAG ACAGCTGGCG TTGTGTCCAC TCCTCTTATT AGGAACGGAG
 ACTGGACCTA CCAGGTGCTC GTGATGCTAG AGATGAATCT CCAGCGAGGA
 GATGTCTACA CCTGCCGCGT GGAGCACTCC AGCCTCCAGA ACCCCATCTT
 GGTGGAGTGG CGGGCACAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGCG
 GTGTCGGGGG CTTCGTGCTG GGGCTGATCT TCCTCGGGCT GGGCCTTTTC
 ATCCGTCACA GGAGTCAGAA GGGGCTCGTG CGCTGA*

>DL;SLA-DQB1_0202
SLA-DQB1_0202, 786 bases, 4EB2E330 checksum.
 ATGTCTGGGA TGGTGGCTCT GCGGCTCCCC AGAGGCCTTT GGACAGCGGC
 CGTGACGGTG ATGCTGGTGG TGCTGGGTGC TCCGGTGGCT GAGGGCAGAG
 ACTCTCCACA GGATTTCGTG TACCAGTTTA AGTTCGAGTG CTACTTCTAC
 AACGGAACGC AGCGGGTGCG GCTCGTGGCC AGGTGGGTCT ACAACCGGGA
 GGAGCACGTG CGCTTCGACA GCGACGTGGG GGAGTTCCGG GCGGTGACCC
 CGCTGGGGCG GCCGGACGCC GACTACTGGA ACGGCCAGAA GGAGGTCCTG
 GAGCAGAAGC GGGCCGAGCT GGACACGGTG TGCAAACACA ACTACCAGAT
 AGAGGAAGGC ACGACCCTGC AGCGGCGAGT GCAACCTACA GTGACTATCT
 CCCCATCCAA GGCAGAGGCT CTAAACCACC ACAACCTGCT GGTCTGTGCG
 GTGACAGATT TCTATCCAAG CCAGGTGAAA GTCCAGTGGT TCCGGAATGG
 CCAGGAGGAG ACAGCTGGCG TTGTGTCCAC TCCTCTTATT AGGAACGGAG
 ACTGGACCTA CCAGGTGCTC GTGATGCTAG AGATGAATCT CCAGCGAGGA
 GATGTCTACA CCTGCCGCGT GGAGCACTCC AGCCTCCAGA GCCCCATCTT
 GGTGGAGTGG CGGGCACAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGCG
 GTGTCGGGGG CTTCGTGCTG GGGCTGATCT TCCTCGGGCT GGGCCTTTTC
 ATCCGTCACA GGAGTCAGAA GGGGCTCGTG CGCTGA*

>DL;SLA-DQB1_0203
SLA-DQB1_0203, 268 bases, 5D87377 checksum.
 GATTTCGTGT ACCAGTTTAA GGGCGAGTGC TACTTCTACA ACGGAACGCA
 GCGGGTGCGG GGCGTGGCCA GGTGGGTCTA CAACCAGGAG GAGTACGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTGACCCC GCTGGGGCTG
 CCGACCGCCG ACTACTGGAA CGGCCAGAAG GACGTCCTGG AGCAGATGCG
 GGCCGAGGTG GACAGGGTGT GCAAACACAA CTACCAGATA GAGGAAGGCA
 CGACCCTGCA GCGGCGAG*

>DL;SLA-DQB1_0204
SLA-DQB1_0204, 283 bases, C75C8958 checksum.
 AGAGACTCTC CACAGGATTT CGTGGTCCAG TTTAAGGGCG AGTGCTACTT
 CTACAACGGA ACGCAGCGGG TGCGGGGCGT GGCCAGGTGG GTCTACAACC
 AGGAGGAGTA CGTGCGCTTC GACAGCGACG TGGGGGAGTT CCGGGCGGTG
 ACCCCGCTGG GGCGGCCGGA CGCCGACTAC TGGAACGGCC AGAAGGAGGT
 CCTGGAGCAG AAGCGGGCCG AGCTGGACAC GGTGTGCAAA CACAACTACC
 AGATAGAGGA AGGCACGACC CTGCAGCGGC GAG*

>DL;SLA-DQB1_02La03
SLA-DQB1_02La03, 270 bases, 70BA9D9C checksum.
 AGGATTTCGT GTACCAGTTT AAGTTAGAGT GCTACTTCTT CAACGGGACG
 CAGCGGGTGC AGGGCGTGGC CAGGTGGGTC TACAACCAGG AGGAGCACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACC CCGCTGGGGC
 GGCCGACCGC CGACTACTGG AACGGCCAGA AGGACGTCCT GGAGCAGAAG
 CGGGCCGAGG TGGACACGGT GTGCAAACAC AACTACCAGA TAGAGGAAGG
 CACGACCCTG CAGCGGCGAG*

>DL;SLA-DQB1_02du01
SLA-DQB1_02du01, 270 bases, E3871F3 checksum.
 AGGATTTCGT GTACCAGTTT AGGTTCGAGT GCTACTTCTT CAACGGAACG
 CAGCGGGTGC GGGGCGTGGC CAGGTGGGTC TACAACCAGG AGGAGCACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACC CCGCTGGGGC
 GGCCGACCGC CGACTACTGG AACGGCCAGA AGGACGTCCT GGAGCAGAAG
 CGGGCCGAGG TGGACACGGT GTGCAAACAC AACTACCAGA TAGAGGAAGG
 CACGACCCTG CAGCGGCGAG*

>DL;SLA-DQB1_02kg02
SLA-DQB1_02kg02, 403 bases, 7E8E776C checksum.
 ATGTCTGGGA TGGTGGCTCT GCGGCTCCCC AGAGGCCTTT GGACAGCGGC
 CTTGACGGTG ATGCTGGTGG TGCTGGGTGC TCCAGTGGCT GAGAGCAGAG
 ACTCTCCACA GGATTTCGTG TACCAGTTTA AGTTCGAGTG CTACTTCTTC
 AACGGAACGC AGCGGGTGCG GGGCGTGGCC AGGTGGGTCT ACAACCAGGA
 GGAGCACGTG CGCTTCGACA GCGACGTGGG GGAGTTCCGG GCGGTGACCC
 CGCTGGGGCG GCCGACCGCC GACTACTGGA ACGGCCAGAA GGACGTCCTG
 GAGCAGAAGC GGGCCGAGGT GGACACGGTG TGCAAACACA ACTACCAGAT
 AGAGGAAGGC ACGACCCTGC AGCGGCGAGT GCAACCTACA GTGACTATCT
 CCC*

>DL;SLA-DQB1_02me01
SLA-DQB1_02me01, 270 bases, 621B61A4 checksum.
 AGGATTTCGT GTACCAGTTT AAGTTCGAGT GCTACTTCTT CAACGGAACG
 CAGCGGGTGC GGGGCGTGGC CAGGTGGGTC TACAACCAGG AGGAGCACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACC CCGCTGGGGC
 GGCCGACCGC CGACTACTGG AACGGCCAGA AGGACGTCCT GGAGCAGAAG
 CGGGCCGAGG TGGACACGGT GTGCAAACAC AACTACCAGA TAGGGGAAGG
 CACGACCCTG CAGCGGCGAG*

>DL;SLA-DQB1_02zs16
SLA-DQB1_02zs16, 258 bases, 94E27F74 checksum.
 AGGATTTCGT GTACCAGTTT AAGGGCGAGT GCTACTTCTA CAACGGAACG
 CAGCGGGTGC GGCTCGTGGC CGGGTGGGTC TACAACCGGG AGGAGCACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACC CCGCTGGGGC
 GGCCGGACGC CGACTACTGG AACGGCCAGA AGGACGTCCT GGAGCAGATG
 CGGGCCGAGG TGGACAGGGT GTGCAAACAC AACTACCAGA TAGAGGAAGG
 CACGACCC*

>DL;SLA-DQB1_0301
SLA-DQB1_0301, 786 bases, F783799A checksum.
 ATGTCTGGGA TGGTGGCTCT GCGGCTCCCC AGAGGCCTTT GGACAGCGGC
 CTTGACGGTG ATGCTGGTGG TGCTGGGTGC TCCAGTGGCT GAGGGCAGAG
 ACTCTCCACA GGATTTCGTG TTCCAGTTTA AGGGCGAGTG CTACTTCTAC
 AACGGAACGC AGCGGGTGCG GGGCGTGGCC AGATACATCT ACAACCAGGA
 GGAGCATTTG CGCTTCGACA GCGACGTGGG GGAGTTCCGG GCGGTGACCC
 CGCTGGGGCG GCCGGAGGCC GACTCCTGGA ACAGCCAGAA GGACGTCCTG
 GAGCAGATGC GGGCCGAGGT GGACAGGGTG TGCAAACACA ACTACCAGAT
 AGAGGAAGGC ACGACCCTGC AGCGGCGAGT GCAACCTACA GTGACTATCT
 CCCCATCCAA GGCAGAGGCT CTAAACCACC ACAACCTGCT GGTCTGTGCG
 GTGACAGATT TCTATCCAAG CCAGGTGAAA GTCCAGTGGT TCCGGAATGG
 CCAGGAGGAG ACAGCTGGCG TTGTGTCCAC TCCTCTTATT AGGAACGGAG
 ACTGGACCTA CCAGGTGCTC GTGATGCTAG AGATGAATCT CCAGCGAGGA
 GATGTCTACA CCTGCCGCGT GGAGCACTCC AGCCTCCAGA ACCCCATCTT
 GGTGGAGTGG CGGGCACAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGCG
 GTGTCGGGGG CTTCGTGCTG GGGCTGATCT TCCTCGGGCT GGGCCTTTTC
 ATCCGTCACA GGAGTCAGAA GGGGCTCGTG CGCTGA*

>DL;SLA-DQB1_0302
SLA-DQB1_0302, 269 bases, 296B9C30 checksum.
 AGGATTTCGT GTACCAGTTT AAGGGCGAGT GCTACTTCTA CAACGGAACG
 CAGCGGGTGC GGCTCGTGGC CAGATACATC TACAACCAGG AGGAGCATTT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACC CCGCTGGGGC
 GGCCGGAGGC CGACTCCTGG AACAGCCAGA AGGACGTCCT GGAGCAGAAG
 CGGGCCGAGC TGGACACTGT GTGCAAACAC AACTACCAGA TAGAGGAAGG
 CACGACTCTG CAGCGGCGA*

>DL;SLA-DQB1_0303
SLA-DQB1_0303, 786 bases, 1F6757F4 checksum.
 ATGTCTGGGA TGGTGGCTCT GCGGCTCCCC AGAGGCCTTT GGACAGCGGC
 CGTGACGGTG ATGCTGGTGG TGCTGGGTGC TCCGGTGGCT GAGGGCAGAG
 ACTCTCCACA GGATTTCGTG GTCCAGTTTA AGGGCGAGTG CTACTTCTAC
 AACGGAACGC AGCGGGTGCG GCTCGTGGCC AGATACATCT ACAACCAGGA
 GGAGCATTTG CGCTTCGACA GCGACGTGGG GGAGTTCCGG GCGGTGACCC
 CGCTGGGGCG GCCGGAGGCC GACTCCTGGA ACAGCCAGAA GGACGTCCTG
 GAGCAGAAGC GGGCCGAGCT GGACACTGTG TGCAAACACA ACTACCAGAT
 AGAGGAAGGC ACGACCCTGC AGCGGCGAGT GCAACCTACA GTGACTATCT
 CCCCATCCAA GGCAGAGGCT CTAAACCACC ACAACCTGCT GGTCTGTGCG
 GTGACAGATT TCTATCCAAG CCAGGTGAAA GTCCAGTGGT TCCGGAATGG
 CCAGGAGGAG ACAGCTGGCG TTGTGTCCAC TCCTCTTATT AGGAACGGAG
 ACTGGACCTA CCAGGTGCTC GTGATGCTAG AGATGAATCT CCAGCGAGGA
 GATGTCTACA CCTGCCGCGT GGAGCACTCC AGCCTCCAGA ACCCCATCTT
 GGTGGAGTGG CGGGCACAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGCG
 GTGTCGGGGG CTTCGTGCTG GGGCTGATCT TCCTCGGGCT GGGCCTTTTC
 ATCCGTCACA GGAGTCAGAA GGGGCTCGTG CGCTGA*

>DL;SLA-DQB1_040101
SLA-DQB1_040101, 786 bases, 3BD4F68B checksum.
 ATGTCTGGGA TGGTGGCTCT GCGGCTCCCC AGAGGCCTTT GGACAGCGGC
 CTTGACGGTG ATGCTGGTGG TGCTGGGTGC TCCAGTGGCT GAGGGCAGAG
 ACTCTCCACA GGATTTCGTG GTCCAGTTTA AGGGCGAGTG CTACTTCTAC
 AACGGAACGC AGCGGGTGTG GAGCGTGGAC AGATACATCT ACAACCAGGA
 GGAGTTTTTG CGCTTCGACA GCGACATGGG GGAGTACCGG GCGGTGACCC
 CGCTGGGGCG GCCGGACGCC GACTACTTGA ACGGCCAGAA GGAGGCCCTG
 GAGCAGAAGC GGGCCGAGCT GGACACTGTG TGCAAACACA ACTACCAGAT
 AGAGGAAGGC ACGACCCTGC AGCGGCGAGT GCAACCTACA GTGACTATCT
 CCCCATCCAA GGCAGAGGCT CTAAACCACC ACAACCTGCT GGTCTGTGCG
 GTGACAGATT TCTATCCAAG CCAGGTGAAA GTCCAGTGGT TCCGGAATGG
 CCAGGAGGAG ACAGCTGGCG TTGTGTCCAC TCCTCTTATT AGGAACGGAG
 ACTGGACCTA CCAGGTGCTC GTGATGCTAG AGATGAATCT CCAGCGAGGA
 GATGTCTACA CCTGCCGCGT GGAGCACTCC AGCCTCCAGA GCCCCATCTT
 GGTGGAGTGG CGGGCACAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGCG
 GTGTCGGGGG CTTCGTGCTG GGGCTGATCT TCCTCGGGCT GGGCCTTTTC
 ATCCGTCACA GGAGTCAGAA GGGGCTCGTG CGCTGA*

>DL;SLA-DQB1_040102
SLA-DQB1_040102, 786 bases, 67217F74 checksum.
 ATGTCTGGGA TGGTGGCTCT GCGGCTCCCC AGAGGCCTTT GGACAGCGGC
 CTTGACGGTG ATGCTGGTGG TGCTGGGTGC TCCAGTGGCT GAGGGCAGAG
 ACTCTCCACA GGATTTCGTG GTCCAGTTTA AGGGCGAGTG CTACTTCTAC
 AACGGAACGC AGCGGGTGTG GAGCGTGGAC AGATACATCT ACAACCAGGA
 GGAGTTTTTG CGCTTCGACA GCGACATGGG GGAGTACCGG GCGGTGACCC
 CGCTGGGGCG GCCGGACGCT GACTACTTGA ACGGCCAGAA GGAGGCCCTG
 GAGCAGAAGC GGGCCGAGCT GGACACTGTG TGCAAACACA ACTACCAGAT
 AGAGGAAGGC ACGACCCTGC AGCGGCGAGT GCAACCTACA GTGACTATCT
 CCCCATCCAA GGCAGAGGCT CTAAACCACC ACAACCTGCT GGTCTGTGCG
 GTGACAGATT TCTATCCAAG CCAGGTGAAA GTCCAGTGGT TCCGGAATGG
 CCAGGAGGAG ACAGCTGGCG TTGTGTCCAC TCCTCTTATT AGGAACGGAG
 ACTGGACCTA CCAGGTGCTC GTGATGCTAG AGATGAATCT CCAGCGAGGA
 GATGTCTACA CCTGCCGCGT GGAGCACTCC AGCCTCCAGA GCCCCATCTT
 GGTGGAGTGG CGGGCACAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGCG
 GTGTCGGGGG CTTCGTGCTG GGGCTGATCT TCCTCGGGCT GGGCCTTTTC
 ATCCGTCACA GGAGTCAGAA GGGGCTCGTG CGCTGA*

>DL;SLA-DQB1_0402
SLA-DQB1_0402, 781 bases, 8B3C99B8 checksum.
 TGGGATGGTG GCTCTGCGGC TCCCCAGAGG CCTTTGGACA GCGGCCTTGA
 CGGTGATGCT GGTGGTGCTG GGTGCTCCAG TGGCTGAGGG CAGAGACTCT
 CCACAGGATT TCGTGTTCCA GTTTAAGGGC GAGTGCTACT TCTACAACGG
 AACGCAGCGG GTGTGGAGCG TGGACAGATA CATCTACAAC CAGGAGGAGT
 TTTTGCGCTT CGACAGCGAC ATGGGGGAGT ACCGGGCGGT GACCCCGCTG
 GGGCGGCCGG ACGCCGACTA CTTGAACGGC CAGAAGGAGG CCCTGGAGCA
 GAAGCGGGCC GAGCTGGACA CTGTGTGCAA ACACAACTAC CAGATAGAGG
 AAGGCACGAC CCTGCAGCGG CGAGTGCAAC CTACAGTGAC TATCTCCCCA
 TCCAAGGCAG AGGCTCTAAA CCACCACAAC CTGCTGGTCT GTGCGGTGAC
 AGATTTCTAT CCAAGCCAGG TGAAAGTCCA GTGGTTCCGG AATGGCCAGG
 AGGAGACAGC TGGCGTTGTG TCCACTCCTC TTATTAGGAA CGGAGACTGG
 ACCTACCAGG TGCTCGTGAT GCTAGAGATG AATCTCCAGC GAGGAGATGT
 CTACACCTGC CGCGTGGAGC ACTCCAGCCT CCAGAGCCCC ATCTTGGTGG
 AGTGGCGGGC ACAGTCTGAA TCTGCCCAGA GCAAGATGCT GAGCGGTGTC
 GGGGGCTTCG TGCTGGGGCT GATCTTCCTC GGGCTGGGCC TTTTCATCCG
 TCACAGGAGT CAGAAGGGGC TCGTGCGCTG A*

>DL;SLA-DQB1_0402we01
SLA-DQB1_0402we01, 786 bases, F650EF3F checksum.
 ATGTCTGGGA TGGTGGCTCT GCGGCTCCCC AGAGGCCTTT GGACAGCGGC
 CTTGACGGTG ATGCTGGTGG TGCTGGGTGC TCCAGTGGCT GAGGGCAGAG
 ACTCTCCACA GGATTTCGTG TTCCAGTTTA AGGGCGAGTG CTACTTCTAC
 AACGGAACGC AGCGGGTGTG GAGCGTGGAC AGATACATCT ACAACCAGGA
 GGAGTTTTTG CGCTTCGACA GCGACATGGG GGAGTACCGG GCGGTGACCC
 CGCTGGGGCG GCCGGACGCC GACTACTTGA ACGGCCAGAA GGAGGCTCTG
 GAGCAGAAGC GGGCCGAGCT GGACACTGTG TGCAAACACA ACTACCAGAT
 AGAGGAAGGC ACGACCCTGC AGCGGCGAGT GCAACCTACA GTGACTATCT
 CCCCATCCAA GGCAGAGGCT CTAAACCACC ACAACCTGCT GGTCTGTGCG
 GTGACAGATT TCTATCCAAG CCAGGTGAAA GTCCAGTGGT TCCGGAATGG
 CCAGGAGGAG ACAGCTGGCG TTGTGTCCAC TCCTCTTATT AGGAACGGAG
 ACTGGACCTA CCAGGTGCTC GTGATGCTAG AGATGAATCT CCAGCGAGGA
 GATGTCTACA CCTGCCGCGT GGAGCACTCC AGCCTCCAGA GCCCCATCTT
 GGTGGAGTGG CGGGCACAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGCG
 GTGTCGGGGG CTTCGTGCTG GGGCTGATCT TCCTCGGGCT GGGCCTTTTC
 ATCCGTCACA GGAGTCAGAA GGGGCTCGTG CGCTGA*

>DL;SLA-DQB1_04hg09
SLA-DQB1_04hg09, 403 bases, 5ACBFAA2 checksum.
 ATGTCTGGGA TGGTGGCTCT GCGGCTCCCC AGAGGCCTTT GGACAGCGGC
 CTTGGCGGTG ATGCTGGTGG TGCTGGGTGC TCCAGTGGCT GAGGGCAGAG
 ACTCTCCACA GGATTTCGTG GTCCAGTTTA AGGGCGAGTG CTACTTCTAC
 AACGGAACGC AGCGGGTGTG GAGCGTGGAC AGATACATCT ACAACCAGGA
 GGAGTTTTTG CGCTTCGACA GCGACATGGG GGAGTACCGG GCGGTGACCC
 CGCTGGGGCG GCCGGACGCC GACTACTTGA ACGGCCAGAA GGAGGCCCTG
 GAGCAGAAGC GGGCCGAGCT GGACACTGTG TGCAAACACA ACTACCAGAT
 AGAGGAAGGC ACGACCCTGC AGCGGCGAGT GCAACCTACA GTGACTATCT
 CCC*

>DL;SLA-DQB1_04sk51
SLA-DQB1_04sk51, 786 bases, 6E9AFB68 checksum.
 ATGTCTGGGA TGGTGGCTCT GCGGCTCCCC AGAGGCCTTT GGACAGCGGC
 CTTGACGGTG ATGCTGGTGG TGCTGGGTGC TCCAGTGGCT GAGGGCAGAG
 ACTCTCCACA GGATTTCGTG TTCCAGTTTA AGGGCGAGTG CTACTTCTAC
 AACGGAACGC AGCGGGTGTG GAGCGTGGAC AGATACATCT ACAACCAGGA
 GGAGTACGTG CGCTTCGACA GCGACATGGG GGAGTACCGG GCGGTGACCC
 CGCTGGGGCG GCCGACCGCC GACTACTGGA ACAGCCAGAA GGAGGCCCTG
 GAGCAGAAGC GGGCCGAGCT GGACACTGTG TGCAAACACA ACTACCAGAT
 AGAGGAAAGC ACGACCCTGC AGCGGCGAGT GCAACCTACA GTGACTATCT
 CCCCATCCAA GGCAGAGGCT CTAAACCACC ACAACCTGCT GGTCTGTGCG
 GTGACAGATT TCTATCCAAG CCAGGTGAAA GTCCAGTGGT TCCGGAATGG
 CCAGGAGGAG ACAGCTGGCG TTGTGTCCAC TCCTCTTATT AGGAACGGAG
 ACTGGACCTA CCAGGTGCTC GTGATGCTAG AGATGAATCT CCAGCGAGGA
 GATGTCTACA CCTGCCGCGT GGAGCACTCC AGCCTCCAGA ACCCCATCTT
 GGTGGAGTGG CGGGCACAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGCG
 GTGTCGGGGG CTTCGTGCTG GGGCTGATCT TCCTCGGGCT GGGCCTTTTC
 ATCCGTCACA GGAGTCAGAA GGGGCTCGTG CGCTGA*

>DL;SLA-DQB1_04sp16
SLA-DQB1_04sp16, 267 bases, 4326E130 checksum.
 GATTTCGTGT ACCAGTTTAA GGGCGAGTGC TACTTCTACA ACGGAACGCA
 GCGGGTGTGG AGCGTGGACA GATACATCTA CAACCAGGAG GAGTTTTTGC
 GCTTCGACAG CGACATGGGG GAGTACCGGG CGGTGACCCC GCTGGGGCGG
 CCGGACGCCG ACTACTTGAA CGGCCAGAAG GAGGCCCTGG AGCAGAAGCG
 GGCCGAGCTG GACACTGTGT GCAAACACAA CTACCAGATA GAGGAAGGCA
 CGACTCTGCA GCGGCGA*

>DL;SLA-DQB1_0501
SLA-DQB1_0501, 786 bases, 159E2D1A checksum.
 ATGTCTGGGA TGGTGGCTCT GCGGCTCCCC AGAGGCCTTT GGACAGCGGC
 CTTGACGGTG ATGCTGGTGG TGCTGGGTGC TCCAGTGGCT GAGGGCAGAG
 ACTCTCCACA GGATTTCGTG GTCCAGTTTA AGTTCGAGTG CTACTTCTAC
 AACGGAACGC AGCGGGTGCG GCTCTTGGCC AGATACATCT ACAACCAGGA
 GGAGTACGCG CGCTTCGACA GCGACGTGGG GGAGTACCGG GCGGTGACCC
 CGCTGGGGCG GCCGGACGCC GACTACTGGA ACGGCCAGAA GGAGGTCCTG
 GAGCAGACGC GGGCCGAGCT GGACACGGTG TGCAAACACA ACTACCAGAT
 AGAGGAAGGC ACGACCCTGC AGCGGCGAGT GCAACCTACA GTGACTATCT
 CCCCATCCAA GGCAGAGGCT CTAAACCACC ACAACCTGCT GGTCTGTGCG
 GTGACAGATT TCTATCCAAG CCAGGTGAAA GTCCAGTGGT TCCGGAATGG
 CCAGGAGGAG ACAGCTGGCG TTGTGTCCAC TCCTCTTATT AGGAACGGAG
 ACTGGACCTA CCAGGTGCTC GTGATGCTAG AGATGAATCT CCAGCGAGGA
 GATGTCTACA CCTGCCGCGT GGAGCACTCC AGCCTCCAGA GCCCCATCTT
 GGTGGAGTGG CGGGCACAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGCG
 GTGTCGGGGG CTTCGTGCTG GGGCTGATCT TCCTCGGGCT GGGCCTTTTC
 ATCCATCACA GGAGTCAGAA GGGGCTCGTG CGCTGA*

>DL;SLA-DQB1_0502
SLA-DQB1_0502, 786 bases, E8DDE331 checksum.
 ATGTCTGGGA TGGTGGCTCT GCGGCTCCCC AGAGGCCTTT GGACAGCGGC
 CTTGACGGTG ATGCTGGTGG TGCTGGGTGC TCCAGTGGCT GAGGGCAGAG
 ACTCTCCACA GGATTTCGTG TTCCAGTTTA AGGGCGAGTG CTACTTCTTC
 AACGGAACGC AGCGGGTGCG GCTCTTGACC AGATACATCT ACAACCAGGA
 GGAGTACGCG CGCTTCGACA GCGACGTGGG GGAGTACCGG GCGGTGACCC
 CGCTGGGGCG GCCGGACGCC GACTACTGGA ACGGCCAGAA GGAGGTCCTG
 GAGCAGACGC GGGCCGAGCT GGACACGGTG TGCAAACACA ACTACCAGAT
 AGAGGAAGGC ACGACCCTGC AGCGGCGAGT GCAACCTACA GTGACTATCT
 CCCCATCCAA GGCAGAGGCT CTAAACCACC ACAACCTGCT GGTCTGTGCG
 GTGACAGATT TCTATCCAAG CCAGGTGAAA GTCCAGTGGT TCCGGAATGG
 CCAGGAGGAG ACAGCTGGCG TTGTGTCCAC TCCTCTTATT AGGAATGGAG
 ACTGGACCTA CCAGGTGCTC GTGATGCTAG AGATGAATCT CCAGCGAGGA
 GATGTCTACA CCTGCCGCGT GGAGCACTCC AGCCTCCAGA GCCCCATCTT
 GGTGGAGTGG CGGGCACAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGCG
 GTGTCGGGGG CTTCGTGCTG GGGCTGATCT TCCTCGGGCT GGGCCTTTTC
 ATCCATCACA GGAGTCAGAA GGGGCTCGTG CGCTGA*

>DL;SLA-DQB1_0503
SLA-DQB1_0503, 786 bases, B928E068 checksum.
 ATGTCTGGGA TGGTGGCTCT GCGGCTCCCC AGAGGCCTTT GGACAGCGGC
 CGTGACGGTG ATGCTGGTGG TGCTGGGTGC TCCGGTGGCT GAGGGCAGAG
 ACTCTCCACA GGATTTCGTG TTCCAGTTTA AGGGCGAGTG CTACTTCTTC
 AACGGAACGC AGCGGGTGCG GCTCTTGACC AGATACATCT ACAACCAGGA
 GGAGTACGCG CGCTTCGACA GCGACATGGG GGAGTACCGG GCGGTGACCC
 CGCTGGGGCG GCCGGCCGCC GACTACTGGA ACAGCCAGAA GGACGTCCTG
 GAGCAGACGC GGGCCGAGCT GGACACGGTG TGCAAACACA ACTACCAGGC
 AGAGGAAGGC ACGACCCTGC AGCGGCGAGT GCAACCTACA GTGACTATCT
 CCCCATCCAA GGCAGAGGCT CTAAACCACC ACAACCTGCT GGTCTGTGCG
 GTGACAGATT TCTATCCAAG CCAGGTGAAA GTCCAGTGGT TCCGGAATGG
 CCAGGAGGAG ACAGCTGGCG TTGTGTCCAC TCCTCTTATT AGGAACGGAG
 ACTGGACCTA CCAGGTGCTC GTGATGCTAG AGATGAATCT CCAGCGAGGA
 GATGTCTACA CCTGCCGCGT GGAGCACTCC AGCCTCCAGA ACCCCATCTT
 GGTGGAGTGG CGGGCACAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGCG
 GTGTCGGGGG CTTCGTGCTG GGGCTGATCT TCCTCGGGCT GGGCCTTTTC
 ATCCGTCACA GGAGTCAGAA GGGGCTCGTG CGCTGA*

>DL;SLA-DQB1_05sp06
SLA-DQB1_05sp06, 267 bases, 6AA939B5 checksum.
 GATTTCGTGG TCCAGTTTAA GTTCGAGTGC TACTTCTACA ACGGAACGCA
 GCGGGTGCGG CTCTTGGCCA GATACATCTA CAACCAGGAG GAGTACGCGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACCCC GCTGGGGCGG
 CCGGGCGCCG ACTACTGGAA CGGCCAGAAG GAGGTCCTGG AGCAGACGCG
 GGCCGAGCTG GACACGGTGT GCAAACACAA CTACCAGATA GAGGAAGGCA
 CGACCCTGCA GCGGCGA*

>DL;SLA-DQB1_0601
SLA-DQB1_0601, 786 bases, FBA4823E checksum.
 ATGTCTGGGA TGGTGGCTCT GCGGCTCCCC AGAGGCCTTT GGACAGCGGC
 CTTGACGGTG ATGCTGGTGG TGCTGGGTGC TCCAGTGGCT GAGGGCAGAG
 ACTCTCCACA GGATTTCGTG TACCAGTTTA AGGGCGAGTG CTACTTCTTC
 AACGGAACGC AGCGGGTGCG GCACGTGACC AGATACATCT ACAACCAGGA
 GGAGCACGTG CGCTTCGACA GCGACGTGGG GGAGTTCCGG GCGGTGACCC
 CGCTGGGGCG GCCGGACGCC GACTACTGGA ACGGCCAGAA GGACTTCCTG
 GAGCAGACGC GGGCCGAGCT GGACACTGTG TGCAAACACA ACTACCAGAT
 AGAGGAAGGC ACGACCCTGC AGCGGCGAGT GCAACCTACA GTGACTATCT
 CCCCATCCAA GGCAGAGGCT CTAAACCACC ACAACCTGCT GGTCTGTGCG
 GTGACAGATT TCTATCCAAG CCAGGTGAAA GTCCAGTGGT TCCGGAATGG
 CCAGGAGGAG ACAGCTGGCG TTGTGTCCAC TCCTCTTATT AGGAACGGAG
 ACTGGACCTA CCAGGTGCTC GTGATGCTAG AGATGAATCT CCAGCGAGGA
 GATGTCTACA CCTGCCGCGT GGAGCACTCC AGCCTCCAGA GCCCCATCTT
 GGTGGAGTGG CGGGCACAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGCG
 GTGTCGGGGG CTTCGTGCTG GGGCTGATCT TCCTCGGGCT GGGCCTTTTC
 ATCCGTCACA GGAGTCAGAA GGGGCTCGTG CGCTGA*

>DL;SLA-DQB1_0602
SLA-DQB1_0602, 270 bases, A37B6BA0 checksum.
 AGGATTTCGT GTACCAGTTT AAGGGCGAGT GCTACTTCTT CAACGGAACG
 CAGCGGGTGC GGCACGTGAC CAGATACATC TACAACCAGG AGGAGCACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACC CCGCTGGGGC
 GGCCGGACGC CGACTACTGG AACAGCCAGA AGGACATCCT GGAGCAGACG
 CGGGCAGAGC TGGACACTGT GTGCAAACAC AACTACCAGA TAGAGGAAGG
 CACGACCCTG CAGCGGCGAG*

>DL;SLA-DQB1_06sp10
SLA-DQB1_06sp10, 267 bases, 7DBEB0 checksum.
 GATTTCGTGT ACCAGGTTAA GGGCGAGTGC TACTTCTTCA ACGGAACGCA
 GCGGGTGCGG CACGTGACCA GATACATCTA CAACCAGGAG GAGCACGTGC
 GCTTCGACAG CGACGTGGGG GAGTKCCGGG CGGKGACCCC GCTGGGGCGG
 CCGGACGCCG ACTACTGGAA CGGCCAGAAG GACTTCCTGG AGCAGACGCG
 GGCCGAGCTG GACACTGTGT GCAAACACAA CTACCAGATA GAGGAAGGCA
 CGACTCTGCA GCGGCGA*

>DL;SLA-DQB1_0701
SLA-DQB1_0701, 786 bases, 34654662 checksum.
 ATGTCTGGGA TGGTGGCTCT GCGGCTCCCC AGAGGCCTTT GGACAGCGGC
 CTTGACGGTG ATGCTGGTGG TGCTGGGTGC TCCAGTGGCT GAGGGCAGAG
 ACTCTCCACA GGATTTCGTG TACCAGTTTA AGTTCGAGTG CTACTTCTTC
 AACGGAACGC AGCGGGTGCG GCTCTTGACC AGATACATCT ACAACCAGGA
 GGAGCACGTG CGCTTCGACA GCAACGTGGG GGAGTACCGG GCGGTGACCC
 CGCTGGGGCG GCCGGACGCC GACTACTGGA ACGGCCAGAA GGACGTCCTG
 GAGCAGACGC GGGCCGAGCT GGACACTGTG TGCAAACACA ACTACCAGAT
 AGAGGAAGGC ACGACCCTGC AGCGGCGAGT GCAACCTACA GTGACTATCT
 CCCCATCCAA GGCAGAGGCT CTAAACCACC ACAACCTGCT GGTCTGTGCG
 GTGACAGATT TCTATCCAAG CCAGGTGAAA GTCCAGTGGT TCCGGAATGG
 CCAGGAGGAG ACAGCTGGCG TTGTGTCCAC TCCTCTTATT AGGAATGGAG
 ACTGGACCTA CCAGGTGCTC GTGATGCTAG AGATGAATCT CCAGCGAGGA
 GATGTCTACA CCTGCCGCGT GGAGCACTCC AGCCTCCAGA GCCCCATCTT
 GGTGGAGTGG CGGGCACAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGCG
 GTGTCGGGGG CTTCGTGCTG GGGCTGATCT TCCTCGGGCT GGGCCTTTTC
 ATCCGTCACA GGAGTCAGAA GGGGCTCGTG CGCTGA*

>DL;SLA-DQB1_0801
SLA-DQB1_0801, 786 bases, 9CB5B918 checksum.
 ATGTCTGGGA TGGTGCCTCT GCGGCTCCCC AGAGGCCTTT GGACAGCGGC
 CGTGACGGTG ATGCTGGTGG TGCTGGGTGC TCCGGTGGCT GAGGGCAGAG
 ACTCTCCACA GGATTTCGTG TACCAGTTTA AGTTCGAGTG CTACTTCTTC
 AACGGAACGC AGCGGGTGCG GCTCGTGACC AGATACATCT ACAACCAGGA
 GGAGTACGCG CGCTTCGACA GCGACGTGGG GGAGTACCGG GCGGTGACCC
 CGCTGGGGCG GCCGGCCGCC GACTACTGGA ACAGCCAGAA GGACATCCTG
 GAGCAGACGC GGGCAGAGCT GGACACGGTG TGCAAACACA ACTACCAGAT
 AGAGGAAGGC ACGACCCTGC AGCGGCGAGT GCAACCTACA GTGACCATCT
 CCCCATCCAA AGCAGAGGCT CTAAACCATC ACAACCTGCT GGTCTGCGCT
 GTGACAGATT TCTATCCAAG CCAGGTCAAA GTTCAGTGGT TCCGGAATGG
 CCAGGAGGAG ACAGCTGGCG TTGTGTCCAC TCCTCTTATT AGGAACGGAG
 ACTGGACCTA CCAGGTGCTT GTGATGCTAG AGATGAATCT CCAGCGAGGA
 GATGTCTACA CCTGCCGCGT GGAGCACTCC AGCCTCCAGA GCCCCATCTT
 GGTGGAGTGG CGGGCACAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGCG
 GTGTCGGGGG CTTCGTGCTG GGGCTGATCT TCCTCGGGCT GGGCCTTTTC
 ATCCGTCACA GGAGTCAGAA GGGGCTCGTG CGCTGA*

>DL;SLA-DQB1_08Lu03
SLA-DQB1_08Lu03, 270 bases, 5C779CF0 checksum.
 AGGATTTCGT GTACCAGTTT AAGTTAGAGT GCTACTTCTT CAACGGAACG
 CAGCGGGTGC GGCTCGTGAC CAGATACATC TACAACCAGG AGGAGTACGC
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACC CCGCTGGGGC
 GGCCGGCCGC CGACTACTGG AACAGCCAGA AGGACATCCT GGAGCAGGCG
 CGGGCAGAGC TGGACACGGT GTGCAAACAC AACTACCAGA TAGAGGAAGG
 CACGACCCTG CAGCGGCGAG*

>DL;SLA-DQB1_08ch01
SLA-DQB1_08ch01, 786 bases, 6CF295E3 checksum.
 ATGTCTGGGA TGGTGCCTCT GCGGCTCCCC AGAGGCCTTT GGACAGCGGC
 CTTGACGGTG ATGCTGGTGG TGCTGGGTGC TCCGGTGGCT GAGGGCAGAG
 ACTCTCCACA GGATTTCGTG TACCAGTTTA AGTTCGAGTG CTACTTCTTC
 AACGGAACGC AGCGGGTGCG GCTCGTGACC AGATACATCT ACAACCAGGA
 GGAGTACGCG CGCTTCGACA GCGACGTGGG GGAGTACCGG GCGGTGACCC
 CGCTGGGGCG GCCGGCCGCC GACTACTGGA ACAGCCAGAA GGACATCCTG
 GAGCAGACGC GGGCAGAGCT GGACACGGTG TGCAAACACA ACTACCAGAT
 AGAGGAAGGC ACGACCCTGC AGCGGCGAGT GCAACCTACA GTGACCATCT
 CCCCATCCAA AGCAGAGGCT CTAAACCATC ACAACCTGCT GGTCTGCGCT
 GTGACAGATT TCTATCCAAG CCAGGTCAAA GTTCAGTGGT TCCGGAATGG
 CCAGGAGGAG ACAGCTGGCG TTGTGTCCAC TCCTCTTATT AGGAACGGAG
 ACTGGACCTA CCAGGTGCTT GTGATGCTAG AGATGAATCT CCAGCGAGGA
 GATGTTTACA CCTGCCGCGT GGAGCACTCC AGCCTCCAGA GCCCCATCTT
 GGTGGAGTGG CGGGCACAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGCG
 GTGTCGGGGG CTTCGTGCTG GGGCTGATCT TCCTCGGGCT GGGCCTTTTC
 ATCCGTCACA GGAGTCAGAA GGGGCTCGTG CGCTGA*

>DL;SLA-DQB1_0901
SLA-DQB1_0901, 786 bases, A3881B91 checksum.
 ATGTCTGGGA TGGTGGCTCT GCGGCTCCCC AGAGGCCTTT GGACAGCGGC
 CTTGACGGTG ATGCTGGTGG TGCTGGGTGC TCCAGTGGCT GAGGGCAGAG
 ACTCTCCACA GGATTTCGTG GTCCAGTTTA AGGGCGAGTG CTACTTCTTC
 AACGGAACGC AGCGGGTGCG GCTCGTGACC AGATTCATCT ACAACCAGGA
 GGAGTACGCG CGCTTCGACA GCGACGTGGG GGAGTACCGG GCGGTGACCC
 CGCTGGGGCG GCCGGACGCC GACTACTGGA ACAGCCAGAA GGACATCCTG
 GAGCAGACGC GGGCCGAGCT GGACACGGTG TGCAAACACA ACTACCAGAT
 AGAGGAAGGA ACGACCCTGC AGCGGCGAGT GCAACCTACA GTGACTATCT
 CCCCATCCAA GGCAGAGGCT CTAAACCACC ACAACCTGCT GGTCTGTGCG
 GTGACAGATT TCTATCCAAG CCAGGTGAAA GTCCAGTGGT TCCGGAATGG
 CCAGGAGGAG ACAGCTGGCG TTGTGTCCAC TCCTCTTATT AGGAACGGAG
 ACTGGACCTA CCAGGTGCTC GTGATGCTAG AGATGAATCT CCAGCGAGGA
 GATGTCTACA CCTGCCGCGT GGAGCACTCC AGCCTCCAGA GCCCCATCTT
 GGTGGAGTGG CGGGCACAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGCG
 GTGTCGGGGG CTTCGTGCTG GGGCTGATCT TCCTCGGGCT GGGCCTTTTC
 ATCCATCACA GGAGTCAGAA GGGGCTCGTG CGCTGA*

>DL;SLA-DQB1_09zh01
SLA-DQB1_09zh01, 249 bases, AF29289D checksum.
 GTCCAGTTTA AGGGCGAGTG CTACTTCTTC AACGGAACGC AGCGGGTGCG
 GCTCGTGACC AGATTCATCT ACAACCAGGA GGAGTACGCG CGCTTCGACA
 GCGACGTGGG GGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGGACGCC
 GACTACTGGA ACAGCCAGAA GGACATCCTG GAGCAGGCGC GGGCCGAGCT
 GGACACGGTG TGCAAACACA ACTACCAGAT AGAGGAAGGA ACGACCCTG*

>DL;SLA-DQB1_Lu02
SLA-DQB1_Lu02, 270 bases, FCA5541 checksum.
 AGGATTTCGT GGTCCAGTTT AAGGGCCAGT GCTACTTCTT CAACGGAACG
 CAGCGGGTGC GGGGCGTGAC CAGATTCATC TACAACCAGG AGGAGTTTTT
 GCGCTTCGAT AGCGACGTGG GGGAGTTCCG GGCGGTGACC CCGCTGGGGC
 GGCCGGAGGC CGACTACTGG AACAGCCAGA AGGACGTCCT GGAGCAGACG
 CGGGCCGAGG CGGACACGGT GTGCAAACAC AACTACCAGA TAGAAGAAGG
 CACGACCCTG CAGCGGCGAG*

>DL;SLA-DQB1_es51
SLA-DQB1_es51, 786 bases, F69ED6AB checksum.
 ATGTCTGGGA TGGTGGCTCT GCGGCTCCCC AGAGGCCTTT GGACAGCGGC
 CTTGACGGTG ATGCTGGTGG TGCTGGGTGC TCCAGTGGCT GAGGGCAGAG
 ACTCTCCACA GGATTTCGTG GTCCAGTTTA AGGGCGAGTG CTACTTCTAC
 AACGGAACGC AGCGGGTGCG GAGCGTGGAC AGATACATCT ACAACCAGGA
 GGAGTACGCG CGCTTCGACA GCGACGTGGG GGAGTACCGG GCGGTGACCC
 CGCTGGGGCG GCCGGACGCC GACTACTGGA ACAGCCAGAA GGACGTCCTG
 GAGCAGACGC GGGCCGAGGT GGACACGGTG TGCAAACACA ACTACCAGAT
 AGAGGAAGGC ACGACCCTGC AGCGGCGAGT GCAACCTACA GTGACTATCT
 CCCCATCCAA GGCAGAGGCT CTAAACCACC ACAACCTGCT GGTCTGTGCG
 GTGACAGATT TCTATCCAAG CCAGGTGAAA GTCCAGTGGT TCCGGAATGG
 CCAGGAGGAG ACAGCTGGCG TTGTGTCCAC TCCTCTTATT AGGAATGGAG
 ACTGGACCTA CCAGGTGCTC GTGATGCTAG AGATGAATCT CCAGCGAGGA
 GATGTCTACA CCTGCCGCGT GGAGCACTCC AGCCTCCAGA GCCCCATCTT
 GGTGGAGTGG CGGGCACAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGCG
 GTGTCGGGGG CTTCGTGCTG GGGCTGATCT TCCTCGGGCT GGGCCTTTTC
 ATCCATCACA GGAGTCAGAA GGGGCTCGTG CGCTGA*

>DL;SLA-DQB1_sh03
SLA-DQB1_sh03, 279 bases, A1D7725B checksum.
 AGAGACTCTC CACAGGATTT CGTGTACCAG TTTAAGTTCG AGTGCTACTT
 CTTCAACGGA ACGCAGCGGG TGCGGCTCGT GACCAGATAC ATCTACAACC
 AGGAGGAGTA CGCGCGCTTC GACAGCGACG TGGGGGAGTA CCGGGCGGTG
 ACCCCGCTGG GGCGGCCGGA GGCCGACTCC TGGAACGGCC AGAAGGACGT
 CCTGGAGCAG ACGCGGGCCG AGCTGGACAC GGTGTGCAAA CACAACTACC
 AGATAGAGGA AGGCACGACT CTGCAGCGG*

>DL;SLA-DQB1_zs12
SLA-DQB1_zs12, 256 bases, E974F216 checksum.
 AGGATTTCGT GTACCAGTTT AAGGGCGAGT GCTACTTCTT CAACGGAACG
 CAGCGGGTGC GGCACGTGAC CAGATACATC TACAACCAGG AGGAGCACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACC CCGCTGGGGC
 GGCCGGCCGC CGACTACTGG AACAGCCAGA AGGACATCCT GGAGCAGACG
 CGGGCAGAGC TGGACACGGT GTGCAAACAC AACTACCAGA TAGAGGAAGG
 CACGAC*

>DL;SLA-DQB1_zs13
SLA-DQB1_zs13, 256 bases, B685275C checksum.
 AGGATTTCGT GTACCAGTTT AAGTTCGAGT GCTTCTTCTT CAACGGAACG
 CAGCGGGTGC GGGGCGTGGC CAGGTGGGTC TACAACCAGG AGGAGTACGC
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACC CCGCTGGGGC
 GGCCGGCCGC CGACTACTGG AACAGCCAGA AGGACATCCT GGAGCAGACG
 CGGGCAGAGC TGGACACGGT GTGCAAACAC AACTACCAGA TAGAGGAAGG
 CACGAC*

>DL;SLA-DQB1_zs14
SLA-DQB1_zs14, 256 bases, 1585FD4A checksum.
 AGGATTTCGT GTACCAGTTT AAGTTCGAGT GCTACTTCTT CAACGGAACG
 CAGCGGGTGC GGCTCGTGAC CAGATACATC TACAACCAGG AGGAGTACGC
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACC CCGCTGGGGC
 GGCCGGACGC CGACTACTGG AACGGCCAGA AGGACGTCCT GGAGCAGATG
 CGGGCCGAGG TGGACAGGGT GTGCAAACAC AACTACCAGA TAGAGGAAGG
 CACGAC*

