>P1;SLA-1_0101
SLA-1_0101, 362 bases, C8709C52 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDSD APNPRMEPRA PWIQQEGQDY WDRETRKQRD TSQTYRVGLK
 NLRGYYNQSE AGSHTYQSMY GCYLGPDGLL LRGYRQYAYD GADYIALNED
 LRSWTAADTA AQITKRKWET ANVAERRRSY LQGLCVESLR EYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGIIVG LVLVLVAGAM VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_0102
SLA-1_0102, 219 bases, D39D8B7D checksum.
 YVDDTQFVRF DSDAPNPRME PRAPWIQQEG QDYWDRETRK QRDTSQTYRV
 GLKNLRGYYN QSEAGSHTYQ SMYGCYLGPD GLLLRGYRQY AYDGADYIAL
 NEDLRSWTAA DTAAQITKRK WETANVAERR RSYLQGLCVE GLREYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWA*

>P1;SLA-1_01rh28
SLA-1_01rh28, 219 bases, E244BEF4 checksum.
 YVDDTQFVRF DSDAPNPRME PRAPWIQQEG QDYWDRETRK QRDTSQTYRV
 GLKNLRGYYN QSEAGSHTYQ SMYGCYLGPD GLLLRGYRQY AYDGADYIAL
 NEDLRSWTAA DTAAQITKRK WETANVAERR RSYLQGLCVE GLREYLEMGK
 DTLQRAEPPR THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWA*

>P1;SLA-1_0201
SLA-1_0201, 362 bases, 16EBD842 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDRGE PRFIAVGYVD
 DTQFVRFDNY APNPRMEPRV PWIQQEGQDY WDEETRKVKD NAQTLRVGLN
 TLRGYYNQSE AGSHTLQSMF GCYLGPDGLL LHGYRQDAYD GADYIALNED
 LRSWTAADMA AQISKRKWEA ADEAERMRSY LQGRCVEGLR RYLQMGKDTL
 QRADPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPMVGITVG LVLVLVAGAM VAGVVIWRKT RSGEKGGSYT QAAGSDSAQG
 SDVSLTKDPR VX*

>P1;SLA-1_0202
SLA-1_0202, 362 bases, 60ECA269 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDNY APNPRMEPRV PWIQQEGQDY WDEETRKVKD NAQTLRVGLN
 TLRGYYNQSE AGSHTLQSMF GCYLGPDGLL LHGYRQDAYD GADYIALNED
 LRSWTAADMA AQISKRKWKA AHEAERMRSY LQGRCVEGLR RYLQMGKDTL
 QRADPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPMVGITVG LVLVLVAGAM VAGVVIWRKT RSGEKGGSYT QAAGSDSAQG
 SDVSLTKDPR VX*

>P1;SLA-1_02we02
SLA-1_02we02, 362 bases, 5544F0D5 checksum.
 MGPGALFLLL SGTLALTGTQ AGPRSLSYFY TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDNY APNPRMEPRV PWIQQEGQDY WDEETRKVKD NAQTLRVGLN
 TLRGYYNQSE AGSHTLQSMF GCYLGPDGLL LHGYRQDAYD GADYIALNED
 LRSWTAADMA AQISKRKWKA AHEAERMRSY LQGRCVEGLR RYLQMGKDTL
 QRADPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPMVGITVG LVLVLVAGAM VAGVVIWRKT RSGEKGGSYT QAAGSDSAQG
 SDVSLTKDPR VX*

>P1;SLA-1_0401
SLA-1_0401, 362 bases, 9F60E406 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDNY APNPRMEPRV PWIQQEGQEY WDRETRNVKE TAQTYGVGLN
 TLRGYYNQSE AGSHTLQSMY GCYLGPDGLL LHGYRQDAYD GADYIALNED
 LRSWTAADMA AQITKRKWEA ADEAERRRSY LQGLCVESLR RYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVLVAGAM VAGVVIWRKT RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_04gx01
SLA-1_04gx01, 362 bases, 403E2304 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDNY APNPRMEPRV PWIQQEGQEY WDRETRNVKE TAQTYGVGLN
 TLRGYYNQSE AGSHTLQSMY GCYLGPDGLL LHGYRQDAYD GADYIALNED
 LRSWTAADMA AQNTKCKWEA ADEAERKRSY LQGLGVEALP KYLEKGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTMRWDPAQP
 PVPIVGIIVG LVLVLVAGAM VAGVVIWRKT RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_04gz01
SLA-1_04gz01, 362 bases, 7B554E33 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDNY APNPRMEPRV PWIQQEGQEY WDRETRNVKE TAQTYGVGLN
 TLRGYYNQSE AGSHTLQSMY GCYLGPDGLL LHGYRQDAYD GADYIALNED
 LRSWTAADMA AQITKRKWEA ADEAERKRSY LQGLCVESLR RYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPMVGIIVG LVLVLVAGAM VAGVVIWRKT RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_04we01
SLA-1_04we01, 362 bases, 816E9C2D checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDNY APNPRMEPRV PWIQQEGQDY WDRNTRNVKE TAQTYGVGLN
 TLRGYYNQSE AGSHTLQSMY GCYLGPDGLL LHGYRQDAYD GADYIALNED
 LRSWTAADMA AQITKRKWEA ADEAERRRSY LQGLCVESLR RYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVLVAGAM VAGVVIWRKT RSGEKGGSYT QAAGSDSAQG
 SDVSLTKDPR VX*

>P1;SLA-1_0501
SLA-1_0501, 361 bases, 71EA1AAF checksum.
 GPGALFLLLS GTLALTGTQA GPHSLSYFST AVSRPDRGDS RFIAVGYVDD
 TQFVRFDSDA PNPRMEPRAP WIQQEGQDYW DRETRKQRDT SQTFRVNLRT
 ALGYYNQSEA GSHTLQSMYG CYLGPDGLLL RGYSQDAYDG ADYVALNEDL
 RSWTAADMAA QITKRKWEAA NVAERMRSYL QGLCVESLQK YLEMGKDTLQ
 RAEPPKTHVT RHPSSDLGVT LRCWALGFYP KEISLTWQRE GQDQSQDMEL
 VETRPSGDGT FQKWAALVVP PGEEQSYTCH VQHEGLQEPL TLRWDPPQPP
 VPIVGIIVGL VLVLVAGAMV AGVVIWRKKR SGEKGGSYTQ AAGSDSDQGS
 DVSLTKGPRV X*

>P1;SLA-1_0601
SLA-1_0601, 362 bases, EE89512C checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDLGD SRFIAVGYVD
 DTQFVRFDNY APNPRMEPRV PWIQQEGQEY WDEETRKVKD NAQTYGVGLN
 TLRGYYNQSE AGSHTLQSMY GCYLGPDGLL LHGYRQDAYD GADYIALNED
 LRSWTAADMA AQISKRKREA ADAAEQERSY LQGLCVESLR RYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKT RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_06an04
SLA-1_06an04, 171 bases, 59CA15A2 checksum.
 SGTLALTGTQ AGPHSLSYFY TAVSRPDRGD SRFIAVGYVD DTQFVRFDNY
 APNPRMEPRV PWIQQEGQDY WDEETRKVKD NAQTYGVGLN TLRGYYNQSE
 AGSHTLQSMF GCYLGPDGLL LHGYRQDAYD GADYIALNED LRSWTAADMA
 AQISKRKWEA ADAAEHWRSY L*

>P1;SLA-1_0701
SLA-1_0701, 362 bases, D476C4DA checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDSD APNPREEPRA PWIQQEGQEY WDRNTQIYKE TAQTYRVNLN
 TLRGYYNQSE AGSHTIQIMY GCDVGPDGLL LRGYRQDAYD GADYIALNED
 LRSWTAADTA AQITKRKWEA ADVAEQLRSY LQGRCVEGLR RYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKT RSGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_0702
SLA-1_0702, 362 bases, 59B15F7A checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDSD APNPREEPRA PWIQQEGQEY WDRNTQIYKE TAQTYRVNLN
 TLRGYYNQSE AGSHTIQIMY GCDVGPDGLL LRGYRQDAYD GADYIALNED
 LRSWTAADMA AQITKRKWEA ADVAEQLRSY LQGRCVEGLR RYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKT RSGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_0801
SLA-1_0801, 362 bases, 793A8873 checksum.
 MGPGALFLLL SGALALTGTQ AGPHSLSYFY TAVSRPDRGD SRFFIVGYVD
 DTQFVRFDSD APNAKMEPRA QWIKQEGPEY WDRETQISKE TAQTYRVGLK
 TLRGYYNQSE AGSHTLQRMY GCYLGPDGLL LRGYRQDAYD GADYIALNED
 LRSWTAADMA AQISKRKWEA ADEAERMRSY LQGLCVEGLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQT
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_08Lw02
SLA-1_08Lw02, 362 bases, 24A4AFF8 checksum.
 MGPGALFLLL SGALALTGTQ AGPHSLSYFY TAVSRPDRGD SRFFIVGYVD
 DTQFVRFDSD APNAKMEPRA QWIKQEGPEY WDRETQISKE TAQTYRVGLK
 TLRGYYNQSE AGSHTLQRMY DCYLGPDGLL LRGYRQDAYD GADYIALNED
 LRSWTAADMA AQISKRKWEA ADEAERMRSY LQGLCVEGLQ KYLEMGKDTL
 QRAEPPKTHV TRRPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQT
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_08an03
SLA-1_08an03, 170 bases, 797A56 checksum.
 GALALTGTQA GPHSLSYFYT AVSRPDRGDS RFFIVGYVDD TQFVRFDSDA
 PNAKMEPRAQ WIKQEGPEYW DRETQISKET AQTYRVGLKT LRGYYNQSEA
 GSHTLQRMYG CYLGPDGLLL RGYRQDAYDG ADYLALNEDL RSWTAADTAA
 QITKRKWEAA DEAEGERSYL*

>P1;SLA-1_08ms05
SLA-1_08ms05, 362 bases, CFCEA499 checksum.
 MGPGALFLLL SGALALTGTQ AGPHSLSYFY TAVSRPDRGD SRFFIVGYVD
 DTQFVRFDSD APNAKMEPRA QWIQQEGPEY WDRETQISKE TAQNYRVSLN
 NLRGYYNQSE AGSHTYQNMY GCYLGPDGLL LRGYSQYGYD GADYIALNED
 LRSWTAADMA AQISKRKWEA ADAAEQWRSY LQGLCVEGLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDHSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQT
 PVPIVGIIVV LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_08pt13
SLA-1_08pt13, 362 bases, 6E3D5249 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDRGD SRFFIVGYVD
 DTQFVRFDSD APNAKMEPRA QWIQQEGPEY WDRETQISKE TAQTYRVDLK
 TLRGYYNQSE AGSHTLQRMY GCYLGPDGLL LRGYHQDAYD GADYLALNED
 LRSWTAADMA AQISKRKWEA ANVAEGERSY LQGRCVESLR RYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVV LVLVLVAGAV VAGVVIWRLK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_08sk11
SLA-1_08sk11, 362 bases, 8F61A0EA checksum.
 MGPGALFLLL SGALALTGTQ AGPHSLSYFY TAVSRPDRGD SRFFIVGYVD
 DTQFVRFDSD APNAKMEPRA QWIQQEGPEY WDRETQISKE TAQTYRVSLN
 NLRGYYNQSE AGSHTYQNMY GCYLGPDGLL LRGYSQYGYD GADYIALNED
 LRSWTAADMA AQISKRKWEA ADAAEQWRSY LQGRCVEWLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDHSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVV LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_08sm08
SLA-1_08sm08, 362 bases, A1ABB111 checksum.
 MGPGALFLLL SGALALTGTQ AGPHSLSYFY TAVSRPDRGD SRFFIVGYVD
 DTQFVRFDSD APNAKMEPRA QWIQQEGPEY WDRETQISKE TAQNYRVDLK
 TLRGYYNQSE AGSHTYQNMY GCYLGPDGLL LRGYSQYGYD GADYIALNED
 LRSWTAADMA AQISKRKWEA ADAAEQWRSY LQGLCVEGLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDHSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVV LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_08sy01
SLA-1_08sy01, 362 bases, 3DA4F879 checksum.
 MGPGALFLLL SGALALTGTQ AGPHSLSYFY TAVSRPDRGD SRFFIVGYVD
 DTQFVRFDSD APNAKMEPRA QWIQQEGPEY WDRETQISKE TAQNYRVSLN
 NLRGYYNQSE AGSHTIQRMF GCYLGPDGLL LRGYSQYGYD GADYIALNED
 LRSWTAADMA AQISKHKWEA ADAAEQERSY LQGLCVEGLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDHSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVV LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_1101
SLA-1_1101, 362 bases, 431EC687 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFS TAVSRPDRGE PCFIEVGYVD
 DTQFVRFDSD APNPRMEPRA PWIEKEGQEY WDRETRRVMG NAQTFRGSLN
 NLRGYYNQSE AGSHTLQWMY GCYLGPDGLL LRGYSQFGYD GADYLALNED
 LRSWTAADTA AQISKRKWEA ADAAERRRSY LQGTCVEWLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_11jh01
SLA-1_11jh01, 362 bases, EEF13189 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFF TVVSRPDRGE PCFIEVGYVD
 DTQFVRFDSD APNPRMEPRA PWIEKEGQEY WDEETRRVMG NAQNDRVSLN
 NLRGYYNQSE AGSHTLQWMY GCYLGPDGLL LRGYDQYAYD GADYLALNED
 LRSWTAADTA AQISKRKFDA ANEAERMRSY LQGRCVEWLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKELSLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_11jh02
SLA-1_11jh02, 362 bases, FDC90D4D checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFD TAVSRPDLGD SRFLTVGYVD
 DTQFVRFDSD APNPRMEPRA PWIEKEGQGY WDEETRRVMG SAQIYRVGLK
 TLRGYYNQSE AGSHTYQWMY GCYLGPDGLF LRGYSQFGYD GADYVALNED
 LRSWTAADMA AQISKRKWEA ADEAERMRSY LQGRCVEWLQ KYLEMGKDTL
 QHAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_11mp11
SLA-1_11mp11, 362 bases, B631383A checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVFRPDRGE PRFIEVGYVD
 DTQFVRFDSD APNPRMEPRA PWIQQEGQEY WDEETRRVMG SAQIYRVNLN
 TLRGYYNQSE AGSHTLQWMY GCDVGPDGLF LRGYSQDAYD GADYIALNED
 LRSWTAADTA AQITKRKWEA ADAAERRRSY LQGLCVEWLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_11yn01
SLA-1_11yn01, 362 bases, 5556B193 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDRGE PRFIEVGYVD
 DTQFVRFDSD APNPRMEPRA PWIQQEGQEY WDEETRRVMG SAQIYRVNLN
 TLRGYYNQSE AGSHTLQWMY GCDVGPDGLF LRGYSQDAYD GADYIALNED
 LRSWTAADTA AQITKRKWET ANVAEQEKSY LQGLCVEWLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_1201
SLA-1_1201, 362 bases, 4221C237 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDLGD SRFIEVGYVD
 DTQFVRFDSD ALNPRMEPRA PWIEKEGQDY WDEETRKVKE TAQINRVDLK
 TLRGYYNQSE AGSHTLQSMF GCYLGPDGLL LRGYRQDAYD GADYIALNED
 LRSWTAADTA AQITKRKWEA ADEAEQWRSY LQGLCVESLR EYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RPGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_12Lw01
SLA-1_12Lw01, 362 bases, A6870B38 checksum.
 MGPGALFLLL SGALALTGTQ AGPHSLSYFY TAVSRPDRGD SRFFIVGYVD
 DTQFVRFDSD ALNPRMEPRA PWIEKEGQDY WDEETRKVKE TAQINRVDLK
 TLRGYYNQSE AGSHTLQSMF GCYLGPDGLL LRGYRQDAYD GADYIALNED
 LRSWTAADTA AQITKRKWEA ADEAEQWRSY LQGLCVESLR EYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQT
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_12hy01
SLA-1_12hy01, 362 bases, 663909CC checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDLGD SRFIEVGYVD
 DTQFVRFDSD ALNPRMEPRA PWIEKEGQDY WDEETRKVKE TAQINRVDLK
 TLRGYYNQSE AGSHTLQSMF GCYLGPDGLL LRGYRQDAYD GADYIALNED
 LRSWTAADTA AQITKRKWEA ADEAEQWRSY LQGLCVESLR EYLEMGKDTL
 QRADPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_1301
SLA-1_1301, 362 bases, 49A0B39 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDNY APNPRMEPRV PWIQQEGQDY WDEETRKVKD NAQTYGVGLN
 TLRGYYNQSE AGSHTLQSMF GCYLGPDGLL LHGYRQDAYD GADYIALNED
 LRSWTAADMA AQITKRKWEA ANVAERRRSY LQGLCVESLR RYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKT RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_13ms21
SLA-1_13ms21, 362 bases, 29B5A689 checksum.
 MGPGALFLML SGTLALTGTQ AGPHSLSYFY TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDNY APNPRMEPRV PWIQQEGQEY WDEETRKVKE TAQNYRVSLN
 TLRGYYNQSE AGSHTLQSMF GCYLGPDGLL LHGYRQDAYD GADYIALNED
 LRSWTAADMA AQITKRKREA ADEAERRRSY LQGLCVESLR RYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVLVAGAM VAGVVIWRKT RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_an01
SLA-1_an01, 170 bases, 95C558FE checksum.
 GTLALTGTQA GPHSLSYFYT AVSRPDRGDS RFFIVGYVDD TQFVRFDSDA
 PNPRMEPRAP WIQQEGQDYW DRETQIQRDT SQTYRVGLKN LRGYYNQSEA
 GSHTLQWMYG CYLGPDGLLL RGYSQDAYDG ADYIALNEDL RSWTAADMAA
 QITKRKWEAA DAAEQMRSYL*

>P1;SLA-1_an02
SLA-1_an02, 169 bases, 36047A85 checksum.
 TLALTGTQAG PHSLSYFSTA VSRPDLGDSR FIAVGYVDDT QFVRFDSDAP
 NPRMEPRAPW IEQEGQEYWD RETQIQRDTS QNYRVNLKNL RGYYNQSEAG
 SHTIQWMYGC DVGPDGLFLH GYHQYAYDGA DYLALNEDLR SWTAADMAAQ
 ISKRKFDAAN VAEQERSYL*

>P1;SLA-1_cs02
SLA-1_cs02, 362 bases, CDDB39E5 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDSD APNPRMEPRV PWIQQEGQDY WDEETRKVKD NAQTYGVGLK
 TLRGYYNQSE AGSHTLQSMF GCYLGPDGLL LHGYRQDTYD GADYIALNED
 LRSWTAADMA AQITKRKWEA ADEAEGERSY LQGLCVEGLQ KYLEMGEDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVLVAGAM VAGVVIWRKT RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_es11
SLA-1_es11, 362 bases, B7A45A4E checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFS TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDSD APNPRMEPRA PWIQQEGQEY WDRNTRNVMG SAQINRVNLK
 TLRGYYNQSE AGSHTLQWMY GCYLGPDGLL LRGYDQFAYD GADYLALNED
 LRSWTAADMA AQISKRKWEA ADAAEHWRSY LQGTCVESLR RYLQMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFH PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQT
 PVPMVGITVG LVLVLVAGAM VAGVVIWRKT RSGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_es12
SLA-1_es12, 362 bases, 3E16BE38 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFF TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDSD APNPRMEPRA PWIQQEGQEY WDQQTRNVMD NAQINRVNLK
 TLRGYYNQSE AGSHTLQRMF GCYLGPDGLL LRGYDQDAYD GADYLALNED
 LRSWTAADTA AQISKRKQEE ADVAERMRSY LQGTCVEGLR KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLRV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_rh03
SLA-1_rh03, 219 bases, BDDECCB9 checksum.
 YVDDTQFVRF DSDAPNPREE PRAPWIQQEG QEYWDRNTQI YKETAQTYRV
 SLNNLRGYYN QSEAGSHTLQ SMYGCYLGPD GLLLRGYRQY AYDSADYIAL
 NEDLRSWTAA DTAAQITKRK WEAANVAERR RSYLQGLCVE SLRRYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWA*

>P1;SLA-1_sk13
SLA-1_sk13, 362 bases, F825E17F checksum.
 MGPGALFLLL SGALALTGTQ AGPHSLRYFD TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDSD APNPRMEPRV PWIQQEGQDY WDEETRKVKD NAQTYRVDLN
 TLRGYYNQSE AGSHTIQTMY GCDVGPDGLL LRGYRQDAYD GADYIALNED
 LRSWTAADMA AQITKRKWKA AHEAERMRSY LQGRCVEWLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGITVG LVLVLVAGAM VAGAVIWRKK RSGEKGGSYT QAAGSDSAQG
 SDVSLTQDPR VX*

>P1;SLA-1_st11
SLA-1_st11, 362 bases, 9202D130 checksum.
 MGPRGLFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDSD APNPREEPRA PWIQQEGQEY WDRNTQIYKE TAQTYRVSLN
 NLRGYYNQSE AGSHTFQSMY GCYLGPDGLL LRGYRQYAYD SADYIALNED
 LRSWTAADTA AQITKRKWEA ADVAERRRSY LQGTCVEWLQ KYLEMGNNTL
 QRADPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVLVIGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_w09sm09
SLA-1_w09sm09, 362 bases, C94F62D6 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFF TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDSD APNPREEPRA PWIQQEGQDY WDRETQISKE TAQTYRVGLK
 TLRGYYNQSE AGSHTLQSMY GCDVGPDGLF LRGYSQDAYD GADYVALNED
 LRSWTAADMA AQITKRKREA ADVAEQERSY LQGLCVESLR EYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDHSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVV LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_w10cs01
SLA-1_w10cs01, 362 bases, C59F64A8 checksum.
 MGPGALFLLL SGALALTGTQ AGPHSLRYFY TAVSRPDLGD SRFIAVGYVD
 DTQFVRFDSD APNPRMEPRA PWIQQEGQEY WDRNTRNVMG SAQNDRVDLK
 TLRGYYNQSE AGSHTIQRMY GCDVGPDGLL LRGYDQDAYD GADYIALNED
 LRSWTAADTA AQITKRKWEA ANVAEQERSY LEGTCVEWLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_w10sm21
SLA-1_w10sm21, 357 bases, 29A2D9B1 checksum.
 LFLLLSGTLA LTGTQAGPHS LRYFYTAVSR PDLGDSRFIA VGYVDDTQFV
 RFDSDAPNPR MEPRAPWIQQ EGQEYWDEET RNAMGSAQND RVDLKTLRGY
 YNQSEAGSHT IQRMYGCDVG PDGLLLRGYD QDAYDGADYI ALNEDLRSWT
 AADTAAQITK RKWEAANVAE QERSYLEGTC VEWLQKYLEM GKDTLQRAEP
 PKTHVTRHPS SDLGVTLRCW ALGFYPKEIS LTWQREGQDQ SQDMELVETR
 PSGDGTFQKW AALVVPPGEE QSYTCHVQHE GLQEPLTLRW DPPQPPVPIV
 GIIVGLVLVL VAGAVVAGVV IWRKKRSGEK GGSYTQAAGS DSDQGSDVSL
 TKGPRVX*

