>DL;SLA-DRB1_0101
SLA-DRB1_0101, 801 bases, C298BC96 checksum.
 ATGTTGCATC TGTGTTTCTC CAGAGGCTTC TGGATGGCGG CTCTGACCGT
 GATGCTGGTG GTGCTGAGCC CTCCCTTGGC TTTGGCCAGG GACACCCCAC
 CGCATTTCTT GTTTCTGGTG AAAGACGAGT GTCATTTCTT CAACGGGACC
 GAGCGGGTGA GGTTATTGCA GAAGCAGTAC TATAACGGAG AGGAGCACGT
 GCGCTTCGAC AGCGACGTGG GCGAGTACCG GGCGGTGACC GAGCTGGGGC
 GGCCAGACGC CAAGTACTGG AACAGCCAGA AGGACCTCCT GGAGCAGATG
 CGGGCGGCGG TGGACACGTA CTGCAGACAC AACTACAGGA TCTTGGATAC
 ATTCCTGGTG CCGCGGCGAG CTGAGCCCAC GGTGACGGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGACCGGG
 TTCTACCCAG GCCACGTGGA GGTCAGGTGG TTCCGGAATG GCCAGGAAGA
 GGCGGCCGGG GTGGTCTCCA CAGGCCTGAT CCCTAATGGA GACTGGACCT
 TCCAGACCAT GGTGATGCTT GAAACGGTTC CTCAGAGTGG AGAGGTCTAC
 AGCTGCCGAG TGGAGCACCC CAGCCTGACG AGCCCCGTCA CAGTGGAATG
 GAGGGCACGG TCTGAATCTG CTCAGGGCAA GATGATGAGT GGGGTCGGGG
 GCTTCGTCCT GGGTCTGCTC TTTGTTGCTG TGGGGCTGTT CATCTACTTC
 AAGAATCAGA AAGGACGCCC TGCCCTTCAG CCAACAGGCC TCCTGAGCTG
 A*

>DL;SLA-DRB2_0101
SLA-DRB2_0101, 786 bases, E73DF2EF checksum.
 ATGGTGTGTC TGTGTTTCTC TGGAGGCTCC TGGTTGGCAG CTCTGACAGT
 GATACTGGGG GTGCTGAGCC CTCCCCTAGC TTTGGCCAGG GACATCGCAT
 CGCATTTCTT GTTTCTGGTG AAACACGAGT GTCATTTCTT CACTGGAACG
 GAGCGGGTGA GGTTTCTGGA CAGATACTTC TATAATGGAG AGGAGTACGT
 GCGCTTCGAC AGCGACGTGG GCGAGTTCCG GGTGGTGACC TAGCTGGGCG
 GCCTTCAGCC AAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCACTTTC
 GGACCGCAGT GGACTGGTTC TGCAGATGCA GCTACAAGGT CTATGCGACC
 TTCCTTGTGC TGTGGCGAGC TGAGCCCACG GTGACGGTGT ATCCTGCAAA
 GACCCAGCCC CTGCAGCACC ACAACCTCCT GGTCTGCTCT GTGACCGGGT
 TCTACCCAGG CCACGTGGAG GTCAGGTGGT TCCGGAATGG CCAGGAAGAG
 GCGGCGGGGG TGGTCTCCAC AGGCCTGATC CCTAATGGAG ACTGGACCTT
 CCAGACCATG GTGATGCTTG AAACGGTTCC TCAGAGTGGA GAGGTCTACA
 GCTGCCGAGT GGAGCACCCC AGCCTGACGA GCCCCGTCAC AGTGGAATGG
 AGGGCACAGT CTGAATCTGC TCAGGGCAAG ATGATGAGTG GGGTCGGGGG
 CTTCGTCCTG GGTCTGCTCT TTGTTGCTGT GGGGCTGTTC ATCTACTTCA
 AGAATCAGAA AGGACGCCCT GCCCTTCAGC CAACAG*

>DL;SLA-DRB2_0102
SLA-DRB2_0102, 250 bases, 322038B1 checksum.
 CGCATTTCTT GCTTCGGGTG AAACACGAGT GTCATTTCTT CACTGGAACG
 GAGCGGGTGA GGTTTCTGGA CAGATACTTC TATAATGGAG AGGAGTACGT
 GCGCTTCGAC AGCGACGTGG GCGAGTTCCG GGTGGTGACC TAGCTGGGCG
 GCCTTCAGCC AAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCACTTTC
 GGACCGCAGT GGACTGGTTC TGCAGATGCA GCTACAAGGT CTATGCGACC*

>DL;SLA-DRB2_01bL77
SLA-DRB2_01bL77, 250 bases, BF425365 checksum.
 CGCATTTCTT GCTTCTGGTG AAACACGAGT GTCATTTCTT CACTGGAACG
 GAGCGGGTGA GGTTTCTGGA CAGATACTTC TATAATGGAG AGGAGTACGT
 GCGCTTCGAC AGCGACGTGG GCGAGTTCCG GGTGGTGACC TAGCTGGGCG
 GCCTTCAGCC AAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCACTTTT
 GGACCGCAGT GGACTGGTTC TGCAGATGCA GCTACAAGGT CTATGCGACC*

>DL;SLA-DRB2_01bL78
SLA-DRB2_01bL78, 248 bases, 3F8E21E6 checksum.
 CATTTCTTGC TTCTGGTGAA ACATGAGTGT CATTTCTTCA CTGGGACGGA
 GCGGGTGAGG TTTCTGGACA GATACTTCTA TAATGGAGAG GAGTACGTGC
 GCTTCGACAG CGACGTGGGC GAGTTCCGGG TGGTGACCTA GCTGGGCGGC
 CTTCAGCCAA GTACTGGAAC AGCCAGAAGG ACATCCTGGA GCACTTTCGG
 ACCGCAGTGG ACTGGTTCTG CAGATGCAGC TACAAGGTCT ATGCGACA*

>DL;SLA-DRB2_01bL80
SLA-DRB2_01bL80, 248 bases, 4C486807 checksum.
 CATTTCTTGC TTCTGGTGAA ACACGAGTGT CATTTCTTCA CTGGGACGGA
 GCGGGTGAGG TTTCTGGACA GATACTTCTA TAATGGAGAG GAGTACGTGC
 GCTTCGACAG CGACGTGGGC GAGTTCCGGG TGGTGACCTA GCTGGGCGGC
 CTTCAGCCAA GTACTGGAAC AGCCAGAAGG ACATCCTGGA GCACTTTCGG
 ACCGCAGTGG ACTGGTTCTG CAGATCGAGC TACAAGGTCT ATGCGACC*

>DL;SLA-DRB2_01vz42
SLA-DRB2_01vz42, 248 bases, 10B55A94 checksum.
 CATTTCTTGC TTCTGGTGAA ACACGAGTGT CATTTCTTCA CTGGGACGGA
 GCGGGTGAGG TTTCTGGACA GATACTTCTA TAATGGAGAG GAGTACGTGC
 GCTTCGACAG CGACGTGGGC GAGTTCCGGG TGGTGACCTA GCTGGGCGGC
 CTTCAGCCAA GTACTGGAAC AGCCAGAAGG ACATCCTGGA GCACTTTCGG
 ACCGCAGTGG ACTGGTTCTG CAGATGCAGC TACAAGGTCT ATGCGACC*

>DL;SLA-DRB2_bL75
SLA-DRB2_bL75, 250 bases, 63978260 checksum.
 CGCATTTCTT GCTTCTGGTG AAACACGAGT GTCATTTCTT CACTGGAACG
 GAGCGGGTGA GGTTTCTGGA CAGATACTTC TATAATGGAG AGGAGTACGT
 GCGCTTCGAC AGCGACGTGG GCGAGTTCCG GGTGGTGACC TAGCTGGGCG
 GCCTTCAGCC AAGTACTGGA ACAGCCAGAA GGACTTCATG GAGCAGAAGC
 GGGCGGAGGT GGACACGGTG TGCAGACACA ACTACGAGAT CTTAGAGACC*

>DL;SLA-DRB2_bL79
SLA-DRB2_bL79, 248 bases, 80D52B40 checksum.
 CATTTCTTGC TTCTGGTGAA ACACGAGTGT CATTTCTTTA CTGGAACGGA
 GCGGGTGAGG TTATTGGAGA GGCAGTACTA TAACGGAGAG GAGTACGTGC
 GCTTCGACAG CGACGTGGGC GAGTTCCGGG TGGTGACCTA GCTGGGCGGC
 CTTCAGCCAA GTACTGGAAC AGCCAGAAGG ACATCCTGGA GCACTTTCGG
 ACCGCAGTGG ACTGGTTCTG CAGATCGAGC TACAAGGTCT ATGCGACC*

>DL;SLA-DRB2_vz44
SLA-DRB2_vz44, 248 bases, F6E6A3 checksum.
 CATTTCTTGC TTCTGGTGAA ACACGAGTGT CATTTCTTTA CTGGAACGGA
 GCGGGTGAGG TTATTGGAGA GGCAGTACTA TTACGGAGAG GAGTACGTGC
 GCTTCGACAG CGACGTGGGC GAGTTCCGGG TGGTGACCTA GCTGGGCGGC
 CTTCAGCCAA GTACTGGAAC AGCCAGAAGG ACATCCTGGA GCACTTTCGG
 ACCGCAGTGG ACTGGTTCTG CAGATGCAGC TACAAGGTCT ATGCGACC*

>DL;SLA-DRB3_0101
SLA-DRB3_0101, 671 bases, A7FBC813 checksum.
 CATTTCTTGT TTCTGGGTAA GCTCGAGTAT CACTAGTCCA ACCGGACGGA
 GCGGGTGCTG TTGCTGGACA GATTCTTCTA TAACAGAGAG GAGTTCGTGC
 GCTTCGACAG CGACTTGGGC GAGTACCGGG CGGTGACTGA GTCTGTGAGG
 CTTGAACGAC CAGAAGGATT TCCTGGAGCA GAAGCGGGTG GAGGTGGACA
 GCGTGTGTAG ACTCAACTAT GGGGTCTTGG ATACATTCCT GGTGCCGAGG
 CAAACTGAGC CCAGAGTGAC GGTGTACCCT GCAAAGACCC AGCCCCTGCA
 GCACCACAAC CTCCTGGTCT GCTCTGTGAC TGGGTTCTAC CCAGGCCACG
 TGGAGGTCAG GTGGTTCCGG AATGGCCAGG AAGAGGCGGC CGGGGTGGTC
 TCCACAGGCC TGATCCCTAA TGGAGACTGG ACCTTCCAGA CCATGGTGAT
 GCTTGAAACG GTTCCTCAGA GTGGAGAGGT CTACAGCTGC CGAGTGGAGC
 ACCCCAGCCT GACGAGCCCC GTCACAGTGG AATGGAGGGT ATGGTCTGAA
 AATGCACAGA ACAAGAAACT GAGTGGACTT GGGGGCTTTG TCCTGGGAAT
 CCTCTTCCTG GCGGTGGGGC TGTTCTTCTG CTTCAGGAGT CAGAAAGGAC
 ACTCTGGACT TCAGCCAACA G*

>DL;SLA-DRB3_01bL82
SLA-DRB3_01bL82, 237 bases, 5C611586 checksum.
 CTCATTTCTT GTTTCTGGGG AAGCTCGAGT ATCACTAGTC CAACCGGACG
 CAGCGGGTGC TGTTGCTGGA CAGATTCTTC TATAACGGAG AGGAGTTCGT
 GCGCTTCCAC AGCGACTTGG GCGAGTACCG GGCGGTGACT GAGTCTGTGA
 GGCTTGAACG ACCAGAAGGA TTTCCTGGAG CAGAAGCGGG TGGAGGTGGA
 CAGGGTGTGT AGACTCAACT ATGGGGTCTT GGATACA*

>DL;SLA-DRB3_01bL83
SLA-DRB3_01bL83, 237 bases, 88AC0B19 checksum.
 CGCATTTCTT GTTTCTGGGT AAGCTCGAGT ATCACTAGTC CAACCGGACG
 CAGCGGGTGC TGTTGCTGGA CAGATTCTTC TATAACAGAG AGGAGTTCGT
 GCGCTTCGAC AGCGACTTGG GCGAGTACCG GGCGGTGACT GAGTCTGTGA
 GGCTTGAACG ACCAGAAGGA TTTCCTGGAG CAGAAGCGGG TGGAGGTGGA
 CAGGGTGTGT AGACTCAACT ATGGGGTCTT GGATACA*

>DL;SLA-DRB3_01bL84
SLA-DRB3_01bL84, 237 bases, 2AC51218 checksum.
 CTCATTTCTT GCTTCTGGTG AAACACGAGT ATCACTAGTC CAACCGGACG
 CAGCGGGTGC TGTTGCTGGA CAGATTCTTC TATAACAGAG AGGAGTTCGT
 GCGCTTCGAC AGCGACTTGG GCGAGTACCG GGCGGTGACT GAGTCTGTGA
 GGCTTGAACG ACCAGAAGGA TTTCCTGGAG CAGAAGCGGG TGGAGGTGGA
 CAGGGTGTGT AGATTCAACT ATGGGGTCTT GGATACA*

>DL;SLA-DRB3_01bL85
SLA-DRB3_01bL85, 237 bases, 7059D273 checksum.
 CGCATTTCTT GTTTCTGGGT AAGCTCGAGT ATCACTAGTC CAACCGGACG
 CAGCGGGTGC TGTTGCTGGA CAGATTCTTC TATAACAGAG AGGAGTTCGT
 GCGCTTCCAC AGCGACTAGG GCGAGTACCG GGCGGTGACT GAGTCTGTGA
 GGCTTGAACG ACCAGAAGGA TTTCCTGGAG CAGAAGCGGG TGGAGGTGGA
 CAGGGTGTGT AGACTCAACT ATGGGGTCTT GGATACA*

>DL;SLA-DRB4_0101
SLA-DRB4_0101, 701 bases, C420C2D5 checksum.
 CTGTTTTCAT GCATCAGTTT AAGTGCGAGT GTCAATTCTC CAACGGGACG
 GAGCGGGTGA GGTTCTTGGC CAGATACATC TACAACACGG AGGAGGATGT
 GCACTTCGAC AGCGACTTGG GTGAGTTCAG GGCCCTGACT GAGCTGGGGC
 GGCCAGACGC TGAGTACTGG AACCAGCAGA AGGGCTTCTT GGAGCAGATG
 CGGACCAAGG TGGACACGAT GTGCAGATCC AACTACTTGG GTATTGGCAG
 CCTCATGATG CAGCGGCGAG TCAAGCCCAC AGTGACGGTG TACCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGACCGGG
 TTCTACCCAG GCCACGTGGA GGTCAGGTGG TTCCGGAATG GCCAGGAAGA
 GGCGGCGGGG GTGGTCTCCA CAGGCCTGAT CCCTAATGGA GACTGGACCT
 TCCAGACCAT GGTGATGCTT GAAACGGTTC CTCAGAGTGG AGAGGTCTAC
 AGCTGCCGAG TGGAGCACCC CAGCCTGACG AGCCCCGTCA CAGTGGAATG
 GAGGGCATGG TCTGAATCTG CTCAGGGCAA AATGCTGAGT GGAATCGGGG
 GCTGTGTCCT GGGTCTGCTC GTCCTGGCTG TGGGGCTGTT CATCTCCTGC
 CGGAGTCAGA AAGAACACTC TGGACGTCAG CCAACAGGAC TCTTGAGCTG
 A*

>DL;SLA-DRB5_0101
SLA-DRB5_0101, 777 bases, D2F5F589 checksum.
 ATGGTGCGTC ATTGGTCCCC TGGAAGCTCC TGGACAGTAT TTCTGACAGT
 GATACTGATG GTGCTGAGCC CTCCCCTGGC TTGGGCTGGG GACACCCGAC
 CAGTTTTCAT GATACAGGGT AAGTCCGAGT GTCATTTCTC CAACGGAACG
 CAGCAGGTGC GGTTCCTGGA CAGATACATC TACAACCGGG ACGAGTTGGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACAG GGCGGTGACC CCAATGGGGC
 AGCCGGCTGC CAAGTACTGG AACAGCCAGA AGGACATCCT AAAGCGGGTG
 CGAGCCGCAG TGGACACGTT CTGCAGAAGC AACTATGAAT TTTTTGAGAG
 CTGCACGGTG CAGCGACGAG TCAAGCCCAC AGTGACGGTG TACCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGACCGGG
 TTCTACCCAG GCCACGTGGA GGTCAGGTGG TTCCGGAATG GCCAGGAAGA
 GGCGGCGGGG GTGGTCTCCA CAGGCCTGAT CCCTAATGGA GACTGGACCT
 TCCAGACCAT GGTGATGCTT GAAACGGTTC CTCAGAGTGG AGAGGTCTAC
 AGCTGCCGAG TGGAGCACCC CAGCCTGACG AGCCCCGTCA CAGTGGAATG
 GAGGGCGCAG CATGACTCTT CACAAGGCAA GATGCTGTGT GGAATCGGGG
 CCTCGGTTCT GGGCCTGCTC TTCCTGGGGA TGGGACTGTT CATCTCCATC
 AGGTATTAGA AAGGATACTC TGGACTT*

