>P1;SLA-3_0101
SLA-3_0101, 362 bases, 4E4634DD checksum.
 MGPRALFLLL SGTLALTGTR EGPHSLRYFD TAVSRPDRGK PRFISVGYVD
 DTQFVRFDSD APNPRMEPRA PWIEQEGQEY WDEETRNAMG SAQTFRVNLN
 NLRGYYNQSE AGSHTFQSMY GCDVGPDGLL LRGYSQFGYD GADYIALNED
 LRSWTAADTA AQITKRKREA ADAAEQMRSY LEGACVVWLQ KYLEMGNNTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGITVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSAQG
 SDVSLTKDPR VX*

>P1;SLA-3_01ev04
SLA-3_01ev04, 295 bases, 64C4B1D6 checksum.
 MGPGALFLLL SGTLALTGTR EGPHSLRYFD TAVSRPDRGK PRFISVGYVD
 DTQFVRFDSD APNPRMEPRA PWIEQEGQEY WDEETRNAMG SAQTFRVNLN
 NLRGYYNQSE AGSHTFQSMY GCDVGPDGLL LRGYSQFGYD GADYIALNED
 LRSWTAADTA AQITKRKREA ADAAEQMRSY LEGACVVWLQ KYLEMGSNTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRW*

>P1;SLA-3_01rh12
SLA-3_01rh12, 219 bases, B3428738 checksum.
 YVDDTQFVRF DSDAPNPRME PRAPWIEQEG QEYWDEETRN AMGSAQTFRV
 NLNNLRGYYN QSEAGSHTFQ SMYGCDVGPD GLLLRGYSQF GYDGADYIAL
 NEDLRSWTAA DTAAQITKRK REAADVAEQM RSYLEGACVE WLQKYLQMGN
 NTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWA*

>P1;SLA-3_01rh28
SLA-3_01rh28, 219 bases, 9BFBB585 checksum.
 YVDDTQFVRF DSDAPNPRME PRAPWIEQEG QEYWDEETRN AMGGAQTFRV
 NLNNLRGYYN QSEAGSHTFQ SMYGCDVGPD GLLLRGYSQF GYDGADYIAL
 NEDLRSWTAA DTAAQITKRK REAADAAEQM RSYLEGACVV WLQKYLEMGN
 NTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWA*

>P1;SLA-3_0301
SLA-3_0301, 362 bases, CF927CF6 checksum.
 MGPRALFLLL SGTLALTGTR EGPHSLRYFD TAVSRPDRRK PRFISVGYVD
 DTQFVRFDSD APNPRMEPRA PWIQQEGQKY WDEETQNAMG SAQTFRVNLK
 NLRGYYNQSE AGSHTLQSMY GCDVGPDGLF LRGYHQDAYD GADYIALNED
 LRSWTAADTA AQIAKRKWEA ADVAEQWRSY LEGACVEWLQ KYLEMGNNTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGIIVG LVLVLVTGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSAQG
 SDVYLIKDPR VX*

>P1;SLA-3_0302
SLA-3_0302, 362 bases, 7F657DA4 checksum.
 MGPRALFLLL SGTLALTGTR EGPHSLRYFD TAVSRPDRGK PRFISVGYVD
 DTQFVRFDSD APNPRMEPRA QWIQQEGQDY WDRETQNSKD NAQRYRVNLK
 NLRGYYNQSE AGSHTIQRMY GCDVGPDGLF LHGYHQDAYD GADYLALNED
 LRSWTAADTA AQISKRKWEA ADAAEQWRSY LEGACVEGLQ KYLDLGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQES LTLRWDPPQH
 PVPIMGIIVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSAQG
 SDVYLIKDPR VX*

>P1;SLA-3_0303
SLA-3_0303, 362 bases, 7D4BFCAF checksum.
 MGPRALFLLL SGTLALTGTR EGPHSLRYFD TAVSRPDRGK PRFISVGYVD
 DTQFVRFDSD APNPRMEPRV PWIEKEGQEY WDEETQNAMG SAQTFRVNLK
 NLRGYYNQSE AGSHTLQSMY GCDVGPDGLF LHGYHQDAYD GADYIALNED
 LRSWTAADTA AQIAKRKWEA ADVAEQWRSY LEGACVEWLQ KYLEMGNNTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSAQG
 SDVYLIKDPR VX*

>P1;SLA-3_0304
SLA-3_0304, 362 bases, 139E2E8F checksum.
 MGPGALFLLL SGTLALTGTR EGPHSLRYFD TAVSRPDRGK PRFISVGYVD
 DTQFVRFDSD APNPRMEPRA PWIEKAEQKY WDEETQNAMG SAQTFRVNLK
 NLRGYYNQSE AGSHTLQSMY GCDVGPDGLF LHGYHQDAYD GADYIALNED
 LRSWTAADTA AQIAKRKWEA ADAAEQWRSY LEGACVEWLQ KYLEMGNNTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR ESQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVLVAGAM VAGVVIWRKT RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-3_03an02
SLA-3_03an02, 165 bases, 66EED070 checksum.
 TREGPHSLRY FDTAVSRPDR GKPRFISVGY VDDTQFVRFD SDAPNPRMEP
 RAQWIQQKGQ EYWDRETQIS KDNAQRYRVN LKNLRGYYNQ SEAGSHTIQS
 MYGCDVGPDG LFLHGYHQDA YDGADYLALN EDLRSWTAAD MAAQITKRKW
 EAADAAEQWR SYLEG*

>P1;SLA-3_03an04
SLA-3_03an04, 166 bases, 45735233 checksum.
 TREGPHSLRY FDTAVSRPDR GKPRFISVGY VDDTQFVRFD SDALNPRMEP
 RAPWIEKAEQ KYWDEETQNA MGSAQTFRVN LKNLRGYYNQ SEAGSHTLQS
 MYGCDVGPDG LFLHGYHQDA YDGADYIALN EDLRSWTAAD TAAQIAKRKW
 EAADVAEQWR SYLEGA*

>P1;SLA-3_03an05
SLA-3_03an05, 178 bases, 50B5A0B1 checksum.
 LSGTLALTGT REGPHSLRYF DTAVSRPDRG KPRFISVGYV DDTQFVRFDS
 DAPNPRMEPR APWIEKDEQK YWDEETQNAM GSAQTFRVNL KNLRGYYNQS
 EAGSHTLQSM YGCDVGPDGL FLHGYHQDAY DGADYIALNE DLRSWTAADT
 AAQIAKRKWE AADAAEQWRS YLEGACVV*

>P1;SLA-3_03pt31
SLA-3_03pt31, 362 bases, AB26C5D9 checksum.
 MGPRALFLLL SGTLALTGTR EGPHSLRYFD TAVSRPDRGK PRFISVGYVD
 DTQFVRFDSY APNPRMEPRA QWIQQEGQEY WDRETQISKD NAQRYRVNLN
 TLRGYYNQSE AGSHTIQTMY GCDVGPDGLF LHGYHQYAYD GADYLALNED
 LRSWTAADTA AQISKRKREA ADAAEQWRSY LEGACVEWLQ KYLEMGEDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQH
 PVPIMGIIVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSSQG
 SDVYLIKDPR VX*

>P1;SLA-3_0401
SLA-3_0401, 362 bases, 10CB9A7D checksum.
 MGPRALFLLL SGALALTGTR AGPHSLRYFD TAVSRPDRGK PRFIEVGYVD
 DTQFVRFDSD APNPRMEPRV PWIEKEGQEY WDKETENAMG SAQTFRVNLK
 NLRGYYNQSE AGSHTLQSMY GCDVGPDGLL LRGYSQDAYD GADYIALNED
 LRSWTAADTA AQITKRKREA ADAAEQMRSY LEGACVEWLQ KYLQMGKDTL
 QHAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGIIVG LVLVLVAGAV VTGVVIWRKK RSGEKGGSYT QAAGSDSAQG
 SDVSLTKDPR VX*

>P1;SLA-3_0402
SLA-3_0402, 361 bases, AFD0D710 checksum.
 MGPRALVLLL SGALALTGTR AGPHSLRYFD TALSRPDRGK PRFIEVGYVD
 DTQFVRFDSD APNPRMEPRA PWIEKAEQKY WDEETQNAMG SAQTFRVNLK
 KLRGYYNQSE AGSHTLQSMY GCDVGPDGLL LRGYSQDAYD GADYIALNED
 LRSWTAADTA AQITKRKREA DAAEQMRSYL EGACVEWLQK YLEMGKDTLQ
 RAEPPKTHVT RHPSSDLGVT LRCWALGFYP KEISLTWQRE GQDQSQDMEL
 VETRPSGDGT FQKWAALVVP PGEEQSYTCH VQHEGLQEPL TLRWDPPQPP
 VPIVGIIVGL VLVLVAGAMV TGVVIWRKKR SGEKGGSYTQ AAGSDSAQGS
 DVSLTKDPRV X*

>P1;SLA-3_04es32
SLA-3_04es32, 365 bases, 6B643870 checksum.
 MGPRALVLLL SGALALTGTR AGPHSLRYFD TALSRPDRGK PRFIEVGYVD
 DTQFVRFDSD APNPRMEPRA PWIEKAEQKY WDEETQNAMG SAQTFRVNLK
 KLRGYYNQSE AGSHTLQSMY GCDVGPDGLL LRGYSQDAYD GADYIALNED
 LRSWTAADTA AQITKRKREA DAAEQMRSYL EGACVEWLQK YLEMGKDTLQ
 RAEPPKTHVT RHPSSDLGVT LRCWALGFYP KEISLTWQRE GQDQGQDQSQ
 YMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPIVGI IVGLVLVLVA GAMVTGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-3_0501
SLA-3_0501, 363 bases, 136B79D5 checksum.
 MGPRALVLLL SGTLALTGTR AGPHSLRYFD TAVSRPDRGK PRFIEVGYVD
 DTQFVWFDSD APNPRMEPRA PWIEQEGQEY WDRETQISKD NAQTYRVNLN
 NLRGYYNQSE AGSHTLQSMY GCDVGPDGLF LRGYSQFAYD GADYIALNED
 LRSWTAADTA AQITKRKREA ADAAEQMRSY LEGACVEGLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVVLVAGA MVAGVVIWRK KRSGEKGGSY TQAAGSDSAQ
 GSDVSLTQDP RVX*

>P1;SLA-3_0502
SLA-3_0502, 362 bases, 7412C536 checksum.
 MGPRALVLLL SGTLALTGTR AGPHSLRYFD TAVSRPDRGK PRFIEVGYVD
 DTQFVWFDSD APNPRMEPRA PWIQQEGQEY WDRETQISKD NAQTYRVNLN
 NLRGYYNQSE AGSHTLQSMY GCDVGPDGLF LRGYSQFAYD GADYIALNED
 LRSWTAADTA AQITKRKREA ADAAEQMRSY LEGACVEGLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLSWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGIIVG LVLVLVAGAM VAGVVIWRKK RSGEKGGSYT QAAGSDSAQG
 SDVSLTQDPR VX*

>P1;SLA-3_0503
SLA-3_0503, 362 bases, E67675CB checksum.
 MGPRALVLLL SGTLALTGTR AGPHSLRYFD TAVSRPDRGK PRFIEVGYVD
 DTQFVWFDSD APNPRMEPRA PWIEKEGQEY WDRETQISKD NAQTYRVNLN
 NLRGYYNQSE AGSHTLQSMY GCDVGPDGLF LRGYSQFAYD GADYIALNED
 LRSWTAADTA AQITKRKREA ADAAEQMRSY LEGACVEGLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVLVAGAM VAGVVIWRKK RSGEKGGSYT QAAGSDSAQG
 SDVSLTQDPR VX*

>P1;SLA-3_05sw01
SLA-3_05sw01, 362 bases, C1C3EF50 checksum.
 MGPRALVLLL SGTLALTGTR AGPHSLRYFD TAVSRPDRGK PRFIEVGYVD
 DTQFVWFDSD APNPRMEPRA PWIEKEGQEY WDRETQISKD NAQTYRVNLN
 NLRGYYNQSE AGSHTLQSMY GCDVGPDGLF LRGYSQFAYD GTDYIALNED
 LRSWTAADTA AQITKRKREA ADAAEQMRSY LEGACVEGLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVLVAGAM VAGVVIWRKK RSGEKGGRYT QAAGSDSAQG
 SDVSLTQDPR VX*

>P1;SLA-3_0601
SLA-3_0601, 362 bases, 6448E0EE checksum.
 MGPRALFLLL SGTLALTGTR EGPHSLRYFD TAVSRPDRGK PRFISVGYVD
 DTQFVRFDSD APNPRMEPRA PWIEQEGQEY WDEETRNAMG SAQTFRVNLN
 NLRGYYNQSE AGSHTLQSMY GCDVGPDWLF LRGYSQDAYD GADYIALNED
 LRSWTAADTA AQITKRKWEA ADEAEQMRSY LEGACVEWLQ KYLQMGNNTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RPGEKGGSYT QAAGSDSAQG
 SDVSLTKDPR VX*

>P1;SLA-3_0602
SLA-3_0602, 362 bases, 55A24CC checksum.
 MGPGALFLLL SGTLALTGTR EGPHSLRYFD TAVSRPDRGK PRFTSVGYVD
 DTQFVRFDSD APNPRMEPRA PWIEQERQEY WDEETRNAMG SAQTFRVNLN
 NLRGYYNQSE AGSHTYQWMY GCDVGPDWLF LRGYSQDAYD GADYIALNED
 LRSWTAADTA AQITKRKREA ADAAEQMRSY LEGACVEWLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWAMGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RPGEKGGSYT QAAGSDSAQG
 SDVSLTKDPR VX*

>P1;SLA-3_0701
SLA-3_0701, 365 bases, 330429FB checksum.
 MGPRALFLLL SGTLALTGTR EGPHSLRYFD TAVSRPDRGK PRFISVGYVD
 DTQFVRFDSD APNPRMEPRA PWIKQEGQEW QEYWDEETRN AMGSAQTFRV
 NLNNLRGYYN QSEAGSHTLQ SMYGCDVGPD WLFLRGYSQD AYDGADYIAL
 NEDLRSWTAA DTAAQITKRK REAADAAEQM RSYLEGACVE WLQKYLQMGN
 NTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPIVGI IVGLVLVLVA GAVVAGVVIW RKKRPGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-3_0701sm19
SLA-3_0701sm19, 365 bases, 330429FB checksum.
 MGPRALFLLL SGTLALTGTR EGPHSLRYFD TAVSRPDRGK PRFISVGYVD
 DTQFVRFDSD APNPRMEPRA PWIKQEGQEW QEYWDEETRN AMGSAQTFRV
 NLNNLRGYYN QSEAGSHTLQ SMYGCDVGPD WLFLRGYSQD AYDGADYIAL
 NEDLRSWTAA DTAAQITKRK REAADAAEQM RSYLEGACVE WLQKYLQMGN
 NTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPIVGI IVGLVLVLVA GAVVAGVVIW RKKRPGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-3_07Lw02
SLA-3_07Lw02, 365 bases, B440ED55 checksum.
 MGPRALFLLL SGTLALTGTR EGPHSLRYFD TAVSRPDRGK PRFISVGYVD
 DTQFVRFDSD APNPRMEPRA PWIKQEGQEW QEYWDEETRN AMGSAQTFRV
 NLNNLRGYYN QSEAGSHTLQ SMYGCDVGPD WLFLRGYSQD AYDGADYIAL
 NEDLRSWTAA DTAAQITKRK REAADAAEQM RSYLEGACVE WLQKYLQMGN
 NTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPIVGI IVGLVLVLVA GAMVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTQ DPRVX*

>P1;SLA-3_07rh34
SLA-3_07rh34, 222 bases, DFC814E7 checksum.
 YVDDTQFVRF DSDAPNPRME PRAPWIKQEG QEWQEYWDEE TRNAMGSAQT
 FRVNLNNLRG YYNQSEAGSL TLQSMYGCDV GPDWLFLRGY SQDAYDGADY
 IALNEDLRSW TAADTAAQIT KRKREAADVA EQMRSYLEGA CVEWLQKYLQ
 MGNNTLQRAE PPKTHVTRHP SSDLGVTLRC WALGFYPKEI SLTWQREGQD
 QSQDMELVET RPSGDGTFQK WA*

>P1;SLA-3_hm22
SLA-3_hm22, 175 bases, 5BB8CBCA checksum.
 LSGTLALTGT QAGPHSLRYF HTAVSRPDLG KPRFIAVGYV DDTQFVRFDS
 DAPNPRMESR VPWIQQEGQE YWDEETRKQR DTSQTFRVSL NTLRGYYNQS
 EAGSHTIQVM YGCYLGPDGL LLHGYHQYAY DGADYLALNE DLRSWTAADT
 AAQITKRKWE AADVTERRRS YLEGA*

