>P1;SLA-DRB1_0101
SLA-DRB1_0101, 267 bases, 795141D1 checksum.
 MLHLCFSRGF WMAALTVMLV VLSPPLALAR DTPPHFLFLV KDECHFFNGT
 ERVRLLQKQY YNGEEHVRFD SDVGEYRAVT ELGRPDAKYW NSQKDLLEQM
 RAAVDTYCRH NYRILDTFLV PRRAEPTVTV YPAKTQPLQH HNLLVCSVTG
 FYPGHVEVRW FRNGQEEAAG VVSTGLIPNG DWTFQTMVML ETVPQSGEVY
 SCRVEHPSLT SPVTVEWRAR SESAQGKMMS GVGGFVLGLL FVAVGLFIYF
 KNQKGRPALQ PTGLLSX*

>P1;SLA-DRB1_0102
SLA-DRB1_0102, 267 bases, C1952F4A checksum.
 MLHLCFSRGF WMAALTVMLV VLSPPLALAR DTPPHFLFLV KDECHFFNGT
 ERVRLLQKQY YNGEEHVRFD SDVGEYRAVT ELGRPDAKYW NSQKDLLEQM
 RAAVDTYCRH NYRTSDTFLV PRRAEPTVTV YPAKTQPLQH HNLLVCSVTG
 FYPGHVEVRW FRNGQEEAAG VVSTGLIPNG DWTFQTMVML ETVPQSGEVY
 SCRVEHPSLT SPVTVEWRAR SESAQGKMMS GVGGFVLGLL FVAVGLFIYF
 KNQKGRPALQ PTGLLSX*

>P1;SLA-DRB1_0201
SLA-DRB1_0201, 267 bases, 427177FB checksum.
 MLHLCFSRGF WMAALTVMLV VLSPPLALAR DTPPHFLHLL KFECHFFNGT
 ERVRLLERQY YNGEEFLRFD SDVGEYRAVT ELGRPDAKDW NSQKDLLEQR
 RAEVDTYCRH NYRILDTFLV PRRAEPTVTV YPAKTQPLQH HNLLVCSVTG
 FYPGHVEVRW FRNGQEEAAG VVSTGLIPNG DWTFQTMVML ETVPQSGEVY
 SCRVEHPSLT SPVTVEWRAR SESAQGKMMS GIGGFVLGLL FVAVGLFIYF
 KNQKGRPALQ PTGLLSX*

>P1;SLA-DRB1_0201br05
SLA-DRB1_0201br05, 92 bases, 44BA1A0B checksum.
 TPPHFLHLLK FECHFFNGTE RVRLLERQYY NGEEFLRFDS DVGEYRAVTE
 LGRPDAKDWN SQKDLLEQRR AEVDTYCRHN YRILDTFLVP RR*

>P1;SLA-DRB1_0201du02
SLA-DRB1_0201du02, 89 bases, F9521CD9 checksum.
 HFLHLLKFEC HFFNGTERVR LLERQYYNGE EFLRFDSDVG EYRAVTELGR
 PDAKDWNSQK DLLEQRRAEV DTYCRHNYRI LDTFLVPRR*

>P1;SLA-DRB1_02du01
SLA-DRB1_02du01, 89 bases, EF998213 checksum.
 HFLHLLKFEC HFFNGTDRLR LLERQFYNGE EFLRFDSDVG EYRAVTELGR
 PDAKDWNSQK DLLEQRRAEV DTYCRHNYRI LDTFLVPRR*

>P1;SLA-DRB1_02du03
SLA-DRB1_02du03, 89 bases, D03EEE24 checksum.
 HFLHLLKFEC HFFNGTEQVR LLERQYYNGE EFLRFDSDVG EYRAVTELGR
 PDAKDWNSQK DLLEQRRAEV DTYCRHNYRI LDTFLVPRR*

>P1;SLA-DRB1_02ka05
SLA-DRB1_02ka05, 70 bases, DFD0A5CD checksum.
 FLLKFECHFF NGTERVRLLE RQYYNGEEFL RFDSDVGEYR AVTELGRPDA
 KDWNSQKDLL EQRRAEVDTY*

>P1;SLA-DRB1_02ka06
SLA-DRB1_02ka06, 70 bases, 513E5058 checksum.
 HLLKFECHFF NGTERVRLLE RQYYNGEEFL RFDSDVGEYR AVTELGRPDA
 KYWNSQKDLL EQRRAEVDTY*

>P1;SLA-DRB1_02ka08
SLA-DRB1_02ka08, 70 bases, F08ED75B checksum.
 HQLKFECHFF NGTDRVRLLE RQYYNGEEFQ RFDSDVGEYR AVTELGRPDA
 KDWNSQKDLL EQRRAEVDTY*

>P1;SLA-DRB1_02sp02
SLA-DRB1_02sp02, 81 bases, 9B7A166B checksum.
 HFLDLLKFEC HFFNGTERVR LLERQYYNGE EFLRFDSDVG EYRAVTELGR
 PDAKDWNSQK DLLEQRRAEV DTYCRHNYRT S*

>P1;SLA-DRB1_02sp08
SLA-DRB1_02sp08, 81 bases, 6A70373 checksum.
 HFLHLLKFEC HFFNGTERVR LLERQYYNGE EFLRFDSDVG EYRAVTELGR
 PDAKDWNSRK DILEQRRAEV DTYCRHNYRT S*

>P1;SLA-DRB1_02zs13
SLA-DRB1_02zs13, 76 bases, 85639F5E checksum.
 HFLHLLKFEC HFFNGTERVR LLERQYYNGE EFLRFDSDVG EYRAVTELGR
 PDAKYWNSQK DILEDSRASV DTYCRH*

>P1;SLA-DRB1_0301
SLA-DRB1_0301, 267 bases, CADB1D70 checksum.
 MACLCFSRGS WMAALTVIVV VLSPPLALAR DIPPHFLHQL KFECHFFNGT
 ERVRLLQRNC YNGEEYVRFD SDVGEYRAVT ELGRPDAKYR NSQKDLLEQR
 RAAVDTYCRH NYRILDTFLV PRRAEPTVTV YPAKTQPLQH HNLLVCSVTG
 FYPGHVEVRW FRNGQEEAAG VVSTGLIPNG DWTFQTMVML ETVPQSGEVY
 SCRVEHPSLT SPVTVEWRAR SESAQGKMMS GVGGFVLGLL FVAVGLFIYF
 KNQKGRPALQ PTGLLSX*

>P1;SLA-DRB1_0401
SLA-DRB1_0401, 267 bases, B95FFACD checksum.
 MLHLCFSRGF WMAALTMMLV VLSPPLALAR DTPPHFLFLG KAECHFFNGT
 ERVRLLDRYF YNGDEYVRFD SDVGEFREVT EFGRPDAKYW NSQKDFMEQK
 RAEVDTVCRH NYEILETFLV PRRAEPRVTV YPAKTQPLQH HNLLVCSVTG
 FYPGHVEVRW FRNGQEEAAG VVSTGLIPNG DWTFQTMVML ETVPQSGEVY
 TCRVEHPSLT SPVTVEWRAR SESAQGKMMS GIGGFVLGLL FVAVGLFIYF
 KNQKGRPALQ PTGLLSX*

>P1;SLA-DRB1_0402
SLA-DRB1_0402, 267 bases, D3116D28 checksum.
 MLHLCFSRGF WMAALTMMLV VLSPPLALAR DTPPHFLFLG KAECHFFNGT
 ERVRLLDRYF YNGDEYVRFD SDVGEFREVT EFGRPSAKYW NSQKDFMEQK
 RAEVDTVCRH NYEISETFLV PRRAEPRVTV YPAKTQPLQH HNLLVCSVTG
 FYPGHVEVRW FRNGQEEVAG VVSTGLIPNG DWTFQTMVML ETVPQSGEVY
 TCRVEHPSLT SPVTVEWRAR SESAQGKMMS GIGGFVLGLL FVAVGLFIYF
 KNQKGRPALQ PTGLLSX*

>P1;SLA-DRB1_0403
SLA-DRB1_0403, 267 bases, 6E6E14D4 checksum.
 MLHLCFSRGF WMAALTMMLV VLSPPLALAR DTPPHFLFLR KAECHFFNGT
 ERVRFLDRYF YNGDEYVRFD SDVGEFREVT EFGRPDAKYW NSQKDFMEQK
 RAEVDTVCRH NYEILETFLV PRRAEPRVTV YPAKTQPLQH HNLLVCSVTG
 FYPGHVEVRW FRNGQEEAAG VVSTGLIPNG DWTFQTMVML ETVPQSGEVY
 TCRVEHPSLT SPVTVEWRAR SESAQGKMMS GIGGFVLGLL FVAVGLFIYF
 KNQKGRPALQ PTGLLSX*

>P1;SLA-DRB1_0404
SLA-DRB1_0404, 267 bases, 2B44167E checksum.
 MLHLCFSRGF WMAALTMMLV VLSPPLALAR DTPPHFLFLG KAECHFFNGT
 ERVRFLDRYF YNGDEYVRFD SDVGEFREVT EFGRPDAKYW NSQKDFMEQK
 RAEVDTVCRH NYEILETFLV PRRAEPRVTV YPAKTQPLQH HNLLVCSVTG
 FYPGHVEVRW FRNGQEEAAG VVSTGLIPNG DWTFQTMVML ETVPQSGEVY
 TCRVEHPSLT SPVTVEWRAR SESAQGKMMS GIGGFVLGLL FVAVGLFIYF
 KNQKGRPALQ PTGLLSX*

>P1;SLA-DRB1_04ga01
SLA-DRB1_04ga01, 267 bases, 41777963 checksum.
 MLHLCFSRAF WMAALTEMLV VLSPSLALAR DTPPHFLFLG KAECHFFNGT
 ERVRLLDRYF YNGDEYVRFD SDVGEFREVT EFGRPSAKYW NSQKDFMEQK
 RAEVDTVCRH NYEISETFLV PRRAEPRVTV YPAKTQPLQH HNLLVCSVTG
 FYPGHVEVRW FRNGQEEVAG VVSTGLIPNG DWTFHTMVML ETVPQSGEVY
 TCRVEHPSLT SPVTVEWRAR SESAQGKMMS GIGGFVLGLL FVAVGLFIYF
 KNQKGRPALQ PTGLLSX*

>P1;SLA-DRB1_04ta01
SLA-DRB1_04ta01, 267 bases, 7ED5DE79 checksum.
 MLHLCFSRGF WMAALTMMLV VLSPPLALAR DTPPHFLFLG KAECHFFNGT
 ERVRLLDRYF YNGDEYVRFD SDVGEFREVT EFGRPDAKYW NSQKDFMEQK
 RAEVDTVCRH NYEILETFLV PRRAEPRVTV YPAKTQPPQH HNLLVCSVTG
 FYPGHVEVRW FRNGQEEAAG VVSTGLIPNG DWTFQTMVML ETVPQSGEVY
 TCRVEHPSLT SPVTVEWRAR SESAQGKMMS GIGGFVLGLL FVAVGLFIYF
 KNQKGRPALQ PTGPLSX*

>P1;SLA-DRB1_0501
SLA-DRB1_0501, 267 bases, 4E6B2048 checksum.
 MLHLCFSRGF WMVALTVMLV VLSPPLALAR DTPPHFLHLV KHECRFFNGT
 ERVLLLDRYF YNGEEFVRFD SDVGEFRAVT ELGRPDAKYW NSQKDILEDS
 RASVDTYCIH NYRILDTFLV PRRAEPTVTV YPAKTQPLQH HNLLVCSVTG
 FYPGHVEVRW FRNGQEEAAG VVSTGLIPNG DWTFQTMVML ETVPQSGEVY
 SCRVEHPSLT SPVTVEWRAR SESAQGKMMS GIGGFVLGLL FVAVGLFIYF
 KNQKGRPALQ PTGLLSX*

>P1;SLA-DRB1_0502
SLA-DRB1_0502, 267 bases, 32531248 checksum.
 MLHLCFSRGF WMAALTMMLV VLSPPLALAR DTPPHFLHLV KHECRFFNGT
 ERVLLLDRYF YNGEEYVRFD SDVGEFRAVT ELGRPDAKYW NSQKDILEDS
 RASVDTYCIH NYRILDTFLV PRRAEPTVTV YPAKTQPLQH HNLLVCSVTG
 FYPGHVEVRW FRNGQEEVAG VVSTGLIPNG DWTFQTMVML ETVPQSGEVY
 SCRVEHPSLT SPVTVEWRAR SESAQGKMMS GIGGFVLGLL FVAVGLFIYF
 KNQKGRPALQ PTGLLSX*

>P1;SLA-DRB1_05ch01
SLA-DRB1_05ch01, 267 bases, 73F3A925 checksum.
 MLHLCFSRGF RMVALTVMLV VLSPPLALAR DTPPHFLHLV KHECRFFNGT
 ERVLLLDRYF YNGEEFVRFD SDVGEFRAVT ELGRPDAKYW NSQKDILEDS
 RASVDTYCIH NYRILDTFLV PRRAEPTVTV YPAKTQPLQH HNLLVCSVTG
 FYPGHVEVRW FRNGQEEAAG VVSTGLIPNG DWTFQTMVML ETVPQSGEVY
 SCRVEHPSLT SPVTVEWRAR SESAQGKMMS GIGGFVLGLL FVAVGLFIYF
 KNQKGRPALQ PTGLLSX*

>P1;SLA-DRB1_05ka01
SLA-DRB1_05ka01, 70 bases, C6F11779 checksum.
 HLVKHECRFF NGTERVLLLD RYFYNGEEFV RFDSDVGEFR AVTELGRPDA
 KYWNSQKEIL EDSRASVDTY*

>P1;SLA-DRB1_05ka03
SLA-DRB1_05ka03, 70 bases, 8A57613B checksum.
 HQLKHECRFF NGTERVLLLD RYFYNGEEFV RFDSDVGEFW AVTELGRPDA
 KYWNSQKDIL EDSRASVDTY*

>P1;SLA-DRB1_05np01
SLA-DRB1_05np01, 70 bases, 1E564D73 checksum.
 LLVKHECRFF NGTERALLLD RYFYNGEEFV RFDSDVGEFR AVTELGRPDA
 RYWNSQKDIL EDSRASVDTY*

>P1;SLA-DRB1_05sp06
SLA-DRB1_05sp06, 81 bases, 1375331C checksum.
 HFLHLVKHEC RFFNGTERVL LLDRYFYNGE EFVRFDSDVG EFRAVTELGR
 PDAKYWNGQK DILEDSRASV DTYCIHNYRT S*

>P1;SLA-DRB1_0601
SLA-DRB1_0601, 267 bases, E28CD851 checksum.
 MACLCFSRGS WMAALTVIVV VLSPPLALAR DIPPHFFFMG KSECHFFNGT
 ERVRYLLKYL YNGEEFVRFD SDLGEYREVT ELGRPDAKYW NSQKDLLEQR
 REKVDTYCRH NYGVSDSFLV PRRAEPTVTV YPAKTQPLQH HNLLVCSVTG
 FYPGHVEVRW FRNGQEEAAG VVSTGLIPNG DWTFQTMVML ETVPQSGEVY
 SCRVEHPSLT SPVTVEWRAR SESAQGKMMS GVGGFVLGLL FVAVGLFIYF
 KNQKGRPALQ PTGLLSX*

>P1;SLA-DRB1_0602
SLA-DRB1_0602, 267 bases, FA28FAE0 checksum.
 MACLCFSRGS WMAALTVIVV VLSPPLALAR DIAQHFFFMG KSECHFFNGT
 ERVRYLQKYL YNGEEFVRFD SDLGEFRAVT ELGRPDAKYW NSQKDLMEQK
 RAVVDTYCRH NYRILDTFLV PRRAEPTVTV YPAKTQPLQH HNLLVCSVTG
 FYPGHVEVRW FRNGQEEAAG VVSTGLIPNG DWTFQTMVML ETVPQSGEVY
 SCRVEHPSLT SPVTVEWRAR SESAQGKMMS GVGGFVLGLL FVAVGLFIYF
 KNQKGRPALQ PTGLLSX*

>P1;SLA-DRB1_0603Q
SLA-DRB1_0603Q, 259 bases, 95B3DFE1 checksum.
 MACLCFSRGS WMAALTVIVV VLSPPLALAR DIAQHFFFMG KSECHFFNGT
 ERVRYLQKYL YNGEEFVRFD SDLGEFRAVT ELGRPDAKYW NSQKDLMEQK
 RAVVDTYCRH NYRILDTFLV PRRAEPTVTV YPAKTQPLQH HNLLVCSVTG
 FYPGHVEVRW FRNGQEEAAG VVSTGLIPNG DWTFQTMVML ETVPQSGEVY
 SCRVEHPSLT SPVTVEWRAR SESAQGKMMS GVGGFVLGLL FVAVGLFIYF
 KNQKGLLSX*

>P1;SLA-DRB1_06sL47
SLA-DRB1_06sL47, 94 bases, 65992D21 checksum.
 RDIAQHFFFM GKFECHFFNG TERVRYLQKY LYNGEEFVRF DSDLGEFRAV
 TELGRPDAKY WNSQKDLMEQ KRAVVDTYCR HNYRILDTFL VPRR*

>P1;SLA-DRB1_06zs12
SLA-DRB1_06zs12, 73 bases, 6E25FE18 checksum.
 HMGKSECHFF NGTERVRYLQ KYLYNGEEFV RFDSDLGEFR AVTELGRPDA
 KDWNSQKDLL EQRRAEVDTY CRH*

>P1;SLA-DRB1_0701
SLA-DRB1_0701, 267 bases, D0E0E308 checksum.
 MLHLCFSRGF WMAALTVMLV VLSPPLALAR DTPPHFLLLV KSECHFFNGT
 ERVRFMERHY YNGEEHVRFD SDVGEYRAVT ELGRPSAKYW NSQKDILEEK
 RAEVDTYCRH NYRTSDTFLV PRRAEPRVTV YPAKTQPLQH HNLLVCSVTG
 FYPGRVEVRW FRNGQEEAAG VVSTGLIPNG DWTFQTMVML ETVPQSGEVY
 TCRVEHPSLT SPVTVEWRAR SESAQGKMMS GVGGFVLGLL FVAVGLFIYF
 KNQKGRPALQ PTGLLSX*

>P1;SLA-DRB1_07ka03
SLA-DRB1_07ka03, 70 bases, 1A16A240 checksum.
 FLVKSECHFF NGTERVRFME RHYYNGEEHV RFDSDVGEYR AVTELGRPSA
 KYWNSQKDIL EEKRAEVDTY*

>P1;SLA-DRB1_07yo02
SLA-DRB1_07yo02, 89 bases, 870D8A53 checksum.
 HFLLLVKSEC HFFNGTERVR FMERHYYNGE EHVRFDSDVG EYRAVTELGR
 PSAKYWNSQK DILEERRAEV DTYCRHNYRT SDTFLVPRR*

>P1;SLA-DRB1_0801
SLA-DRB1_0801, 267 bases, 3F7FE87A checksum.
 MLHLCFSRGF WMAALTVMLV VLSPPLALAR DTPPHFLYLL KFECHFFNGT
 ERVRLLERQY YNGEEYVRFD SDVGEYRAVT ELGRPVAKDW NSQKDLLEQR
 RAEVDTYCRH NYRTSDTFLV PRRAEPRVTV YPAKTQPLQH HNLLVCSVTG
 FYPGHVEVRW FRNGQEEAAG VVSTGLIPNG DWTFQTMVML ETVPQSGEVY
 SCRVEHPSLT SPVTVEWRAR SESAQGKMMS GVGGFVLGLL FVAVGLFIYF
 KNQKGRPALQ PTGLLSX*

>P1;SLA-DRB1_0801hg06
SLA-DRB1_0801hg06, 101 bases, A71BCDE8 checksum.
 RDTPPHFLYL LKFECHFFNG TERVRLLERQ YYNGEEYVRF DSDVGEYRAV
 TELGRPVAKD WNSQKDLLEQ RRAEVDTYCR HNYRTSDTFL VPRRAEPTVT
 V*

>P1;SLA-DRB1_08hg09
SLA-DRB1_08hg09, 101 bases, AA3E7B04 checksum.
 RDTPPHFLYL LKFECHFFNG TERVRLLERQ YYNGEEYVRF DSDVGEYRAV
 TELGRPVAKD WNSQKDPLEQ RRAEVDTYCR HNYRTSDTFL VPRRAEPTVT
 V*

>P1;SLA-DRB1_08ka83
SLA-DRB1_08ka83, 70 bases, 7E666854 checksum.
 LLLRFECHFF NGTERVRLLE RQYYNGEEYV RFDSDVGEYR AVTELGRPVA
 KDWNSQKDLL EQRRAEVDTY*

>P1;SLA-DRB1_08ka92
SLA-DRB1_08ka92, 70 bases, 45C4346A checksum.
 HLLKFECHFF NGTERVRLLE RQYYNGEEYV RFDSDVGEYR AVTELGRPVA
 KDWNSQKDLL EQRRAEVDTY*

>P1;SLA-DRB1_08sp05
SLA-DRB1_08sp05, 81 bases, AC339598 checksum.
 HFLDLSKFEC HFFNGTERVR LLERQYYNGE EYVRFDSDVG EYRAVTELGR
 PVAKDWNSQK DLLEQRRAEV DTYCRHNYRT S*

>P1;SLA-DRB1_0901
SLA-DRB1_0901, 267 bases, 964102C1 checksum.
 MLHLCFSRGF WMAALTVMLV VLSPPLALAR DTPPHFLFLG KFECHFFNGT
 EQVRLLERQY YNGEEFVRFD SDVGEYRAVT ELGRPDAKNY NSQKDLLEQR
 RAEVDTYCRH NYRTSDTFLV PRRAEPRVTV YPAKTQPLQH HNLLVCSVTG
 FYPGHVEVRW FRNGQEEAAG VVSTGLIPNG DWTFQTMVML ETVPQSGEVY
 SCRVEHPSLT SPVTVEWRAR SESAQGKMMS GIGGFVLGLL FVAVGLFIYF
 KNQKGRPALQ PTGLLSX*

>P1;SLA-DRB1_0901br04
SLA-DRB1_0901br04, 92 bases, 771153B4 checksum.
 TPPHFLFLGK FECHFFNGTE QVRLLERQYY NGEEFVRFDS DVGEYRAVTE
 LGRPDAKNYN SQKDLLEQRR AEVDTYCRHN YRTSDTFLVP RR*

>P1;SLA-DRB1_09sL48
SLA-DRB1_09sL48, 94 bases, 273D1D09 checksum.
 RDTPPHFLFL GKFECHFFNG TEQVRLLERQ YYNGEEFVRF DSDVGEYRAV
 TELGRPDAKN YNSQKDLLEQ RRAEVDTYCR HNYRILDTFL VPRR*

>P1;SLA-DRB1_09ta01
SLA-DRB1_09ta01, 267 bases, 3BCECE8 checksum.
 MLHLCFSGGF WMAALTVMLV VLSPPLALAR DTPPHFLFLG KFECHFFNGT
 EQVRLLERQY YNGEEFVRFD SDVGEYRAVT ELGRPDAKNY NSQKDLLEQR
 RAEVDTYCRH NYRTSDTFLV PRRAEPRVTV YPAKTQPLQH HNLLVCSVTG
 FYPGHVEVRW FRNGQEEAAG VVSTGLIPNG DWTFQTMVML ETVPQSGEVY
 SCRVEHPSLT SPVTVEWRAR SESAQGKMMS GIGGFVLGLL FVAVGLFIYF
 KSQKGRPALQ PTALLSX*

>P1;SLA-DRB1_1001
SLA-DRB1_1001, 267 bases, 5DB7E7FB checksum.
 MLHLCFSRGF WMAALTVMLV VLSPPLALAR DTPPHFFFME KFECHFFNGT
 ERVRLLDRHY YNGEEILRFD SDVGEYRAVT ELGRPEAKDW NSRKDILEQR
 RAEVDTYCRH NYRISDTFLV PRRAEPTVTV YPAKTQPLQH HNLLVCSVTG
 FYPGHVEVRW FRNGQEEAAG VVSTGLIPNG DWTFQTMVML ETVPQSGEVY
 SCRVEHPSLT SPVTVEWRAR SESAQGKMMS GVGGFVLGLL FVAVGLFIYF
 KNQKGRPALQ PTGLLSX*

>P1;SLA-DRB1_10Lu03
SLA-DRB1_10Lu03, 89 bases, 45118120 checksum.
 HFFFMEKFEC HFFNGTERVR LLDKHYYNGE EILRFDSDVG EYRAVTELGR
 PEAKDWNSRK DILEQRRAEV DTYCRHDYRI SDTFLVPRR*

>P1;SLA-DRB1_10jh01
SLA-DRB1_10jh01, 267 bases, 928E0ABF checksum.
 MLHLCFSRGF WMAALTVMLV VLSPPLALAR DTPPHFFFME KFECHFFNGT
 ERVRFLDRYF YNGEEILRFD SDVGEYRAVT ELGRPEAKDW NSRKDILEQR
 RAEVDTYCRH NYRISDTFLV PRRAEPTVTV YPAKTQPLQH HNLLVCSVTG
 FYPGHVEVRW FRNGQEEAAG VVSTGLIPNG DWTFQTMVML ETVPQSGEVY
 SCRVEHPSLT SPVTVEWRAR SESAQGKMMS GVGGFVLGLL FVAVGLFIYF
 KNQKGRPALQ PTGLLSX*

>P1;SLA-DRB1_10ka06
SLA-DRB1_10ka06, 70 bases, CB6C5A0D checksum.
 FMEKFECHFF NGTERVRLLD RHYYNGEEIL RFDSDVGEYR AVTELGRLEA
 KDWNSRKDIL EQRRAEVDTY*

>P1;SLA-DRB1_10sp07
SLA-DRB1_10sp07, 81 bases, ACC1E51E checksum.
 HFFFMEKFEC HFFNGTERVR LLDRHYYNGE EILRFDSDVG EYRAVTELGR
 PEAKDWNSRK DILEQRRAEV DTYCRHNYRT S*

>P1;SLA-DRB1_1101
SLA-DRB1_1101, 267 bases, DDA09D31 checksum.
 MLHLCFSRGF WMAALTVMLV VLSPPLALAR DTPTHFLHLV KSECRFFNGT
 ERVRFLDRYF YNGEEFVRFD SDVGEFREVT EFGRPDAEYW NSLKDFLEQS
 RTAVDTYCRY NYGVFDGFLV SRRAEPRVTV YPAKTQPLQH HNLLVCSVTG
 FYPGHVEVRW FRNGQEEAAG VVSTGLIPNG DWTFQTMVML ETVPQSGEVY
 SCRVEHPSLT SPVTVEWRAR SESAQGKMMS GVGGFVLGLL FVAVGLFIYF
 KNQKGRPALQ PTGLLSX*

>P1;SLA-DRB1_1102
SLA-DRB1_1102, 267 bases, C16A4113 checksum.
 MLHLCFSRGF WMAALTVMLV VLSPPLALAR DTPPHFLFLR KAECRFFNGT
 ERVRLLDRYF YNGDEYVRFD SDVGEFREVT EFGRPDAKYW NSLKDFLEQR
 RTAVDTYCRH NYGVSDGFLV SRRAEPTVTV YPAKTQPLQH HNLLVCSVTG
 FYPGHVEVRW FRNGQEEAAG VVSTGLIPNG DWTFQTMVML ETVPQSGEVY
 SCRVEHPSLT SPVTVEWRAR SESAQGKMMS GVGGFVLGLL FVAVGLFIYF
 KNQKGRPALQ PTGLLSX*

>P1;SLA-DRB1_11ac21
SLA-DRB1_11ac21, 176 bases, 254ECF86 checksum.
 MLHLCFSRGF WMAALTVMLM VLSPPLALAR DTPPHFLLLV KRECHFFNGT
 ERVRFLDRYF YNGEEFVRFD SDVGEFREVT EFGRPDAKYW NSLKDFLEQS
 RTAVDTYCRH NYGVSDGFLV SRRAEPRVTV YPAKTQPLQH HNLLVCSVTG
 FYPGHVEVRW FRNGQEEAAG VVSTGL*

>P1;SLA-DRB1_11br02
SLA-DRB1_11br02, 83 bases, 3AB259F checksum.
 HFLFLRKAEC RFFNGTERVR LLDRYFYNGD EYVRFDSDVG EFREVTECGR
 PDAKYWNSLK DFLEQRRTAV DTYCRHNYGV SDG*

>P1;SLA-DRB1_11sp01
SLA-DRB1_11sp01, 81 bases, E65267A2 checksum.
 HFLLLRKAEC RFFNGTERVR LLDRYFYNGD EYVRFDSDVG EFREVTEFGR
 PDAKYRNSLK DFLEQRRTAV DTYCRHNYRT S*

>P1;SLA-DRB1_11zs10
SLA-DRB1_11zs10, 81 bases, DC51FAA5 checksum.
 GSLTAHFLFL RKAECRFFNG TERMRLLDRY FYNGDEYVRF DSDVGEFREV
 TEFGRPDAKY WNSLKDFLEQ RRTAVDTYCR H*

>P1;SLA-DRB1_1301
SLA-DRB1_1301, 267 bases, 392FF6B4 checksum.
 MLHLCFSRGF WMAALTVMLV VLSPPLALAR DTPPHFLFLV KDECHFFNGT
 ERVRLLERQY YNGEEHVRFD SDVGEYRAVT ELGRPDAKYW NSQKDILEQK
 RAEVDTVCRH NYRILDTFLV PRRAEPTVTV YPAKTQPLQH HNLLVCSVTG
 FYPGRVEVRW FRNGQEEAAG VVSTGLIPNG DWTFQTMVML ETVPQSGEVY
 SCRVEHPSLT SPVTVEWRAR SESAQGKMMS GVGGFVLGLL FVAVGLFIYF
 KNQKGRPALQ PTGLLSX*

>P1;SLA-DRB1_1401
SLA-DRB1_1401, 267 bases, DD16772E checksum.
 MLHLCFSRGF WMAALTVMLV VLSPPLALAR DTPPHFLHLV KSECRFFNGT
 ERVRFLDRYF YNGEEFVRFD SDVGEFREVT ELGRPDAKYW NSQKDFMEQK
 RAEVDTVCRH NYEISETFLV PRRAEPRVTV YPAKTQPLQH HNLLVCSVTG
 FYPGHVEVRW FRNGQEEVAG VVSTGLIPNG DWTFQTMVML ETVPQSGEVY
 SCRVEHPSLT SPVTVEWRAR SESAQGKMMS GVGGFVLGLL FVAVGLFIYF
 KNQKGRPALQ PTGLLSX*

>P1;SLA-DRB1_La02
SLA-DRB1_La02, 89 bases, 9818952A checksum.
 HFLFLGKFEC HFFNGTEQVR LLERQYYNGE EFVRFDSDVG EYRAVTEQGR
 PDAKNYNSQK DLLEQRRAEV DTYCRHNYRT SDTFLVPRR*

>P1;SLA-DRB1_La03
SLA-DRB1_La03, 89 bases, 6261C03D checksum.
 HFFFMEKFEC HFFNGTERVR LLDRHYYNGE EILRFDSDVG EYRAVTELGR
 PDAKNYNSQK DLLEQRRAEV DTYCRHNYRI SDTFLVPRR*

>P1;SLA-DRB1_La04
SLA-DRB1_La04, 89 bases, 9A4A46B7 checksum.
 HFFFMEKFEC HFFNGTEQVR LLERQYYNGE EFVRFDSDVG EYRAVTELGR
 PDAKNYNSQK DLLEQRRAEV DTYCRHNYRT SDTFLVPRR*

>P1;SLA-DRB1_La05
SLA-DRB1_La05, 89 bases, D3318937 checksum.
 HFFFMEKFEC HFFNGTERVR LLDRHYYNGE EFVRFDSDVG EYRAVTELGR
 PDAKNYNSQK DLLEQRRAEV DTYCRHNYRI SDTFLVPRR*

>P1;SLA-DRB1_Lu02
SLA-DRB1_Lu02, 89 bases, 26363439 checksum.
 HFLLLVKFEC HFFNGTERVR FMERQYYNGE EHVRFDSDVG EYRAVTELGR
 PDAKYWNSQK DLLEQKRGAV DRYCRHNYRI LDTFLVPRR*

>P1;SLA-DRB1_be01
SLA-DRB1_be01, 89 bases, 40CCF133 checksum.
 HFLFLVKDEC HFFNGTERVR LLQKQYYNGE EHVRFDSDVG EYRAVTELGR
 PDAKYWNSQK DLLEQMRAAV DTVCRHNYRI LDTFLVPRR*

>P1;SLA-DRB1_du05
SLA-DRB1_du05, 89 bases, 41FB6ECB checksum.
 HFLFLGKFEC HFFNGTGQVR LLERQYYNGE EFVRFDSDAG EYRAVTELGR
 PDAKNYNSQE DLLEQRRAEV DTYCRHNYRT SDTFLVPRR*

>P1;SLA-DRB1_er01
SLA-DRB1_er01, 89 bases, 93AAA2F8 checksum.
 HFFFMEKFEC HFFNGTERVR LLDRHYYNGE EILRFDSDVG GYRAVTELGR
 PDAKYWNSQK DLLEQMRAAV DTYCRHNYRT SDTFLVPRR*

>P1;SLA-DRB1_ha01
SLA-DRB1_ha01, 89 bases, 416878DE checksum.
 HFLFLGKFEC HFFNGTERVR LLQKQYYNGE EHVRFDSDVG EYRAVTELGR
 PDAKYWNSQR DLLEQMRAAV DTYCRHNYRI LDTFLVPRR*

>P1;SLA-DRB1_ha04
SLA-DRB1_ha04, 89 bases, 49723ADA checksum.
 HFLFLVKDEC HFFNGTERVR LLERQYYNGE EHVRFDSDVG EYRAVTELGR
 PDAKYWNSQK DLLEQMRAAV DTYCRHNYRI LDTFLVPRR*

>P1;SLA-DRB1_ka04
SLA-DRB1_ka04, 70 bases, 5E2E9B48 checksum.
 HQLKFECHFF SGTERVRLLE RQYYNGEEYV RFDSDVGEYR AVTELGRPDA
 KYWNSQKDLL EQRRAEVDTY*

>P1;SLA-DRB1_ka05
SLA-DRB1_ka05, 70 bases, 4AAC9B82 checksum.
 YLLKFECHFF NGTERVRLLE RQYYNGEEYV RFDSDVGEYR AVTELGRPDA
 KYWNSQKDLL EQKRAEVDTY*

>P1;SLA-DRB1_ka09
SLA-DRB1_ka09, 70 bases, 62A715E checksum.
 HQLKFECHFF NGTEQVRLLE RQYYNGEEFV RFDSDVGEYR AVTELGRPDA
 KYYNSQKDLL EQRRAEVDTY*

>P1;SLA-DRB1_ka13
SLA-DRB1_ka13, 70 bases, CAE15584 checksum.
 HQLKFECHFF NGTERVRFLD RYFYNGDEYV RFDSDVGEFR EVTEFGRPDA
 KYWNSQKDFM EQKRAEVDTV*

>P1;SLA-DRB1_ka14
SLA-DRB1_ka14, 70 bases, BA6E4FF0 checksum.
 LLVKHECHFF TGTERVRFLD RYFYNGEEYV RFDSDVGEFR VVTELGRPSA
 KYWNSQKDFM EQKRAEVDTV*

>P1;SLA-DRB1_kb02
SLA-DRB1_kb02, 83 bases, B75D2FA checksum.
 HFLFLVKHEC HFFNGTEQVR FLDRYFYNGE EYVRFDSDVG EYRAVTELGR
 PDAKNYNSQK DLLEQRRAEV DTYCRHNYRT SDT*

>P1;SLA-DRB1_kb03N
SLA-DRB1_kb03N, 47 bases, 757698C3 checksum.
 HFLLLVKHEC HFFTGTERVR FLDRYFYNGE EYVRFDSDVG EFRVVTX*

>P1;SLA-DRB1_kb04N
SLA-DRB1_kb04N, 47 bases, 757698C3 checksum.
 HFLLLVKHEC HFFTGTERVR FLDRYFYNGE EYVRFDSDVG EFRVVTX*

>P1;SLA-DRB1_me02
SLA-DRB1_me02, 89 bases, C13D75E4 checksum.
 HFLFLVKDEC HFFNGTERVR LLQKQYYNGE EHVRFDSDVG EYRAVTELGR
 PDAKNYNSQK DLLEQRRAEV DTYCRHNYRT SDTFLVPRR*

>P1;SLA-DRB1_oj01
SLA-DRB1_oj01, 72 bases, 91C0B1B9 checksum.
 YLLKFECHFF NGTERVRLLE RQYYNGEEYV RFDSDVGEYR AVTELGRPDA
 KNYNSQKDLL EQRRAEVDTY CR*

>P1;SLA-DRB1_oj02
SLA-DRB1_oj02, 72 bases, 8223172F checksum.
 FLGKFECHFF NGTEQVRLLE RQYYNGEEFV RFDSDVGEYR AVTELGRPVA
 KDWNSQKDLL EQRRAEVDTY CR*

>P1;SLA-DRB1_w12ka02
SLA-DRB1_w12ka02, 70 bases, D93891F9 checksum.
 LLVKSECRFF NGTERVRFLD RYFYNGEEFV RFDSDVGEFR AVTELGRPFA
 KYWNGQKDFL EDSRASVDTY*

>P1;SLA-DRB1_w12ka05
SLA-DRB1_w12ka05, 70 bases, A5B3C981 checksum.
 LLVKSECRYF NGTERLRFLD RYFYNGEEFV RFDSDVGEFR AVTELGRPFA
 KYWNGQKDFL EDSRASVDTY*

>P1;SLA-DRB1_w12ka12
SLA-DRB1_w12ka12, 70 bases, 67D17614 checksum.
 HLVKSECRFF NGTERVRFLD RYFYNGEEFV RFDSDVGEFR AVTELGRPFA
 KYWNGQKDFL EDSRASVDTY*

