>P1;SLA-1_0101
SLA-1_0101, 362 bases, C8709C52 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDSD APNPRMEPRA PWIQQEGQDY WDRETRKQRD TSQTYRVGLK
 NLRGYYNQSE AGSHTYQSMY GCYLGPDGLL LRGYRQYAYD GADYIALNED
 LRSWTAADTA AQITKRKWET ANVAERRRSY LQGLCVESLR EYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGIIVG LVLVLVAGAM VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_0102
SLA-1_0102, 219 bases, D39D8B7D checksum.
 YVDDTQFVRF DSDAPNPRME PRAPWIQQEG QDYWDRETRK QRDTSQTYRV
 GLKNLRGYYN QSEAGSHTYQ SMYGCYLGPD GLLLRGYRQY AYDGADYIAL
 NEDLRSWTAA DTAAQITKRK WETANVAERR RSYLQGLCVE GLREYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWA*

>P1;SLA-1_01rh28
SLA-1_01rh28, 219 bases, E244BEF4 checksum.
 YVDDTQFVRF DSDAPNPRME PRAPWIQQEG QDYWDRETRK QRDTSQTYRV
 GLKNLRGYYN QSEAGSHTYQ SMYGCYLGPD GLLLRGYRQY AYDGADYIAL
 NEDLRSWTAA DTAAQITKRK WETANVAERR RSYLQGLCVE GLREYLEMGK
 DTLQRAEPPR THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWA*

>P1;SLA-1_0201
SLA-1_0201, 362 bases, 16EBD842 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDRGE PRFIAVGYVD
 DTQFVRFDNY APNPRMEPRV PWIQQEGQDY WDEETRKVKD NAQTLRVGLN
 TLRGYYNQSE AGSHTLQSMF GCYLGPDGLL LHGYRQDAYD GADYIALNED
 LRSWTAADMA AQISKRKWEA ADEAERMRSY LQGRCVEGLR RYLQMGKDTL
 QRADPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPMVGITVG LVLVLVAGAM VAGVVIWRKT RSGEKGGSYT QAAGSDSAQG
 SDVSLTKDPR VX*

>P1;SLA-1_0202
SLA-1_0202, 362 bases, 60ECA269 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDNY APNPRMEPRV PWIQQEGQDY WDEETRKVKD NAQTLRVGLN
 TLRGYYNQSE AGSHTLQSMF GCYLGPDGLL LHGYRQDAYD GADYIALNED
 LRSWTAADMA AQISKRKWKA AHEAERMRSY LQGRCVEGLR RYLQMGKDTL
 QRADPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPMVGITVG LVLVLVAGAM VAGVVIWRKT RSGEKGGSYT QAAGSDSAQG
 SDVSLTKDPR VX*

>P1;SLA-1_02we02
SLA-1_02we02, 362 bases, 5544F0D5 checksum.
 MGPGALFLLL SGTLALTGTQ AGPRSLSYFY TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDNY APNPRMEPRV PWIQQEGQDY WDEETRKVKD NAQTLRVGLN
 TLRGYYNQSE AGSHTLQSMF GCYLGPDGLL LHGYRQDAYD GADYIALNED
 LRSWTAADMA AQISKRKWKA AHEAERMRSY LQGRCVEGLR RYLQMGKDTL
 QRADPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPMVGITVG LVLVLVAGAM VAGVVIWRKT RSGEKGGSYT QAAGSDSAQG
 SDVSLTKDPR VX*

>P1;SLA-1_0401
SLA-1_0401, 362 bases, 9F60E406 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDNY APNPRMEPRV PWIQQEGQEY WDRETRNVKE TAQTYGVGLN
 TLRGYYNQSE AGSHTLQSMY GCYLGPDGLL LHGYRQDAYD GADYIALNED
 LRSWTAADMA AQITKRKWEA ADEAERRRSY LQGLCVESLR RYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVLVAGAM VAGVVIWRKT RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_04gx01
SLA-1_04gx01, 362 bases, 403E2304 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDNY APNPRMEPRV PWIQQEGQEY WDRETRNVKE TAQTYGVGLN
 TLRGYYNQSE AGSHTLQSMY GCYLGPDGLL LHGYRQDAYD GADYIALNED
 LRSWTAADMA AQNTKCKWEA ADEAERKRSY LQGLGVEALP KYLEKGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTMRWDPAQP
 PVPIVGIIVG LVLVLVAGAM VAGVVIWRKT RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_04gz01
SLA-1_04gz01, 362 bases, 7B554E33 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDNY APNPRMEPRV PWIQQEGQEY WDRETRNVKE TAQTYGVGLN
 TLRGYYNQSE AGSHTLQSMY GCYLGPDGLL LHGYRQDAYD GADYIALNED
 LRSWTAADMA AQITKRKWEA ADEAERKRSY LQGLCVESLR RYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPMVGIIVG LVLVLVAGAM VAGVVIWRKT RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_04we01
SLA-1_04we01, 362 bases, 816E9C2D checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDNY APNPRMEPRV PWIQQEGQDY WDRNTRNVKE TAQTYGVGLN
 TLRGYYNQSE AGSHTLQSMY GCYLGPDGLL LHGYRQDAYD GADYIALNED
 LRSWTAADMA AQITKRKWEA ADEAERRRSY LQGLCVESLR RYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVLVAGAM VAGVVIWRKT RSGEKGGSYT QAAGSDSAQG
 SDVSLTKDPR VX*

>P1;SLA-1_0501
SLA-1_0501, 361 bases, 71EA1AAF checksum.
 GPGALFLLLS GTLALTGTQA GPHSLSYFST AVSRPDRGDS RFIAVGYVDD
 TQFVRFDSDA PNPRMEPRAP WIQQEGQDYW DRETRKQRDT SQTFRVNLRT
 ALGYYNQSEA GSHTLQSMYG CYLGPDGLLL RGYSQDAYDG ADYVALNEDL
 RSWTAADMAA QITKRKWEAA NVAERMRSYL QGLCVESLQK YLEMGKDTLQ
 RAEPPKTHVT RHPSSDLGVT LRCWALGFYP KEISLTWQRE GQDQSQDMEL
 VETRPSGDGT FQKWAALVVP PGEEQSYTCH VQHEGLQEPL TLRWDPPQPP
 VPIVGIIVGL VLVLVAGAMV AGVVIWRKKR SGEKGGSYTQ AAGSDSDQGS
 DVSLTKGPRV X*

>P1;SLA-1_0601
SLA-1_0601, 362 bases, EE89512C checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDLGD SRFIAVGYVD
 DTQFVRFDNY APNPRMEPRV PWIQQEGQEY WDEETRKVKD NAQTYGVGLN
 TLRGYYNQSE AGSHTLQSMY GCYLGPDGLL LHGYRQDAYD GADYIALNED
 LRSWTAADMA AQISKRKREA ADAAEQERSY LQGLCVESLR RYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKT RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_06an04
SLA-1_06an04, 171 bases, 59CA15A2 checksum.
 SGTLALTGTQ AGPHSLSYFY TAVSRPDRGD SRFIAVGYVD DTQFVRFDNY
 APNPRMEPRV PWIQQEGQDY WDEETRKVKD NAQTYGVGLN TLRGYYNQSE
 AGSHTLQSMF GCYLGPDGLL LHGYRQDAYD GADYIALNED LRSWTAADMA
 AQISKRKWEA ADAAEHWRSY L*

>P1;SLA-1_0701
SLA-1_0701, 362 bases, D476C4DA checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDSD APNPREEPRA PWIQQEGQEY WDRNTQIYKE TAQTYRVNLN
 TLRGYYNQSE AGSHTIQIMY GCDVGPDGLL LRGYRQDAYD GADYIALNED
 LRSWTAADTA AQITKRKWEA ADVAEQLRSY LQGRCVEGLR RYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKT RSGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_0702
SLA-1_0702, 362 bases, 59B15F7A checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDSD APNPREEPRA PWIQQEGQEY WDRNTQIYKE TAQTYRVNLN
 TLRGYYNQSE AGSHTIQIMY GCDVGPDGLL LRGYRQDAYD GADYIALNED
 LRSWTAADMA AQITKRKWEA ADVAEQLRSY LQGRCVEGLR RYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKT RSGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_0801
SLA-1_0801, 362 bases, 793A8873 checksum.
 MGPGALFLLL SGALALTGTQ AGPHSLSYFY TAVSRPDRGD SRFFIVGYVD
 DTQFVRFDSD APNAKMEPRA QWIKQEGPEY WDRETQISKE TAQTYRVGLK
 TLRGYYNQSE AGSHTLQRMY GCYLGPDGLL LRGYRQDAYD GADYIALNED
 LRSWTAADMA AQISKRKWEA ADEAERMRSY LQGLCVEGLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQT
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_08Lw02
SLA-1_08Lw02, 362 bases, 24A4AFF8 checksum.
 MGPGALFLLL SGALALTGTQ AGPHSLSYFY TAVSRPDRGD SRFFIVGYVD
 DTQFVRFDSD APNAKMEPRA QWIKQEGPEY WDRETQISKE TAQTYRVGLK
 TLRGYYNQSE AGSHTLQRMY DCYLGPDGLL LRGYRQDAYD GADYIALNED
 LRSWTAADMA AQISKRKWEA ADEAERMRSY LQGLCVEGLQ KYLEMGKDTL
 QRAEPPKTHV TRRPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQT
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_08an03
SLA-1_08an03, 170 bases, 797A56 checksum.
 GALALTGTQA GPHSLSYFYT AVSRPDRGDS RFFIVGYVDD TQFVRFDSDA
 PNAKMEPRAQ WIKQEGPEYW DRETQISKET AQTYRVGLKT LRGYYNQSEA
 GSHTLQRMYG CYLGPDGLLL RGYRQDAYDG ADYLALNEDL RSWTAADTAA
 QITKRKWEAA DEAEGERSYL*

>P1;SLA-1_08ms05
SLA-1_08ms05, 362 bases, CFCEA499 checksum.
 MGPGALFLLL SGALALTGTQ AGPHSLSYFY TAVSRPDRGD SRFFIVGYVD
 DTQFVRFDSD APNAKMEPRA QWIQQEGPEY WDRETQISKE TAQNYRVSLN
 NLRGYYNQSE AGSHTYQNMY GCYLGPDGLL LRGYSQYGYD GADYIALNED
 LRSWTAADMA AQISKRKWEA ADAAEQWRSY LQGLCVEGLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDHSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQT
 PVPIVGIIVV LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_08pt13
SLA-1_08pt13, 362 bases, 6E3D5249 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDRGD SRFFIVGYVD
 DTQFVRFDSD APNAKMEPRA QWIQQEGPEY WDRETQISKE TAQTYRVDLK
 TLRGYYNQSE AGSHTLQRMY GCYLGPDGLL LRGYHQDAYD GADYLALNED
 LRSWTAADMA AQISKRKWEA ANVAEGERSY LQGRCVESLR RYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVV LVLVLVAGAV VAGVVIWRLK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_08sk11
SLA-1_08sk11, 362 bases, 8F61A0EA checksum.
 MGPGALFLLL SGALALTGTQ AGPHSLSYFY TAVSRPDRGD SRFFIVGYVD
 DTQFVRFDSD APNAKMEPRA QWIQQEGPEY WDRETQISKE TAQTYRVSLN
 NLRGYYNQSE AGSHTYQNMY GCYLGPDGLL LRGYSQYGYD GADYIALNED
 LRSWTAADMA AQISKRKWEA ADAAEQWRSY LQGRCVEWLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDHSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVV LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_08sm08
SLA-1_08sm08, 362 bases, A1ABB111 checksum.
 MGPGALFLLL SGALALTGTQ AGPHSLSYFY TAVSRPDRGD SRFFIVGYVD
 DTQFVRFDSD APNAKMEPRA QWIQQEGPEY WDRETQISKE TAQNYRVDLK
 TLRGYYNQSE AGSHTYQNMY GCYLGPDGLL LRGYSQYGYD GADYIALNED
 LRSWTAADMA AQISKRKWEA ADAAEQWRSY LQGLCVEGLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDHSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVV LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_08sy01
SLA-1_08sy01, 362 bases, 3DA4F879 checksum.
 MGPGALFLLL SGALALTGTQ AGPHSLSYFY TAVSRPDRGD SRFFIVGYVD
 DTQFVRFDSD APNAKMEPRA QWIQQEGPEY WDRETQISKE TAQNYRVSLN
 NLRGYYNQSE AGSHTIQRMF GCYLGPDGLL LRGYSQYGYD GADYIALNED
 LRSWTAADMA AQISKHKWEA ADAAEQERSY LQGLCVEGLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDHSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVV LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_1101
SLA-1_1101, 362 bases, 431EC687 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFS TAVSRPDRGE PCFIEVGYVD
 DTQFVRFDSD APNPRMEPRA PWIEKEGQEY WDRETRRVMG NAQTFRGSLN
 NLRGYYNQSE AGSHTLQWMY GCYLGPDGLL LRGYSQFGYD GADYLALNED
 LRSWTAADTA AQISKRKWEA ADAAERRRSY LQGTCVEWLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_11jh01
SLA-1_11jh01, 362 bases, EEF13189 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFF TVVSRPDRGE PCFIEVGYVD
 DTQFVRFDSD APNPRMEPRA PWIEKEGQEY WDEETRRVMG NAQNDRVSLN
 NLRGYYNQSE AGSHTLQWMY GCYLGPDGLL LRGYDQYAYD GADYLALNED
 LRSWTAADTA AQISKRKFDA ANEAERMRSY LQGRCVEWLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKELSLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_11jh02
SLA-1_11jh02, 362 bases, FDC90D4D checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFD TAVSRPDLGD SRFLTVGYVD
 DTQFVRFDSD APNPRMEPRA PWIEKEGQGY WDEETRRVMG SAQIYRVGLK
 TLRGYYNQSE AGSHTYQWMY GCYLGPDGLF LRGYSQFGYD GADYVALNED
 LRSWTAADMA AQISKRKWEA ADEAERMRSY LQGRCVEWLQ KYLEMGKDTL
 QHAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_11mp11
SLA-1_11mp11, 362 bases, B631383A checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVFRPDRGE PRFIEVGYVD
 DTQFVRFDSD APNPRMEPRA PWIQQEGQEY WDEETRRVMG SAQIYRVNLN
 TLRGYYNQSE AGSHTLQWMY GCDVGPDGLF LRGYSQDAYD GADYIALNED
 LRSWTAADTA AQITKRKWEA ADAAERRRSY LQGLCVEWLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_11yn01
SLA-1_11yn01, 362 bases, 5556B193 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDRGE PRFIEVGYVD
 DTQFVRFDSD APNPRMEPRA PWIQQEGQEY WDEETRRVMG SAQIYRVNLN
 TLRGYYNQSE AGSHTLQWMY GCDVGPDGLF LRGYSQDAYD GADYIALNED
 LRSWTAADTA AQITKRKWET ANVAEQEKSY LQGLCVEWLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_1201
SLA-1_1201, 362 bases, 4221C237 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDLGD SRFIEVGYVD
 DTQFVRFDSD ALNPRMEPRA PWIEKEGQDY WDEETRKVKE TAQINRVDLK
 TLRGYYNQSE AGSHTLQSMF GCYLGPDGLL LRGYRQDAYD GADYIALNED
 LRSWTAADTA AQITKRKWEA ADEAEQWRSY LQGLCVESLR EYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RPGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_12Lw01
SLA-1_12Lw01, 362 bases, A6870B38 checksum.
 MGPGALFLLL SGALALTGTQ AGPHSLSYFY TAVSRPDRGD SRFFIVGYVD
 DTQFVRFDSD ALNPRMEPRA PWIEKEGQDY WDEETRKVKE TAQINRVDLK
 TLRGYYNQSE AGSHTLQSMF GCYLGPDGLL LRGYRQDAYD GADYIALNED
 LRSWTAADTA AQITKRKWEA ADEAEQWRSY LQGLCVESLR EYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQT
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_12hy01
SLA-1_12hy01, 362 bases, 663909CC checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDLGD SRFIEVGYVD
 DTQFVRFDSD ALNPRMEPRA PWIEKEGQDY WDEETRKVKE TAQINRVDLK
 TLRGYYNQSE AGSHTLQSMF GCYLGPDGLL LRGYRQDAYD GADYIALNED
 LRSWTAADTA AQITKRKWEA ADEAEQWRSY LQGLCVESLR EYLEMGKDTL
 QRADPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_1301
SLA-1_1301, 362 bases, 49A0B39 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDNY APNPRMEPRV PWIQQEGQDY WDEETRKVKD NAQTYGVGLN
 TLRGYYNQSE AGSHTLQSMF GCYLGPDGLL LHGYRQDAYD GADYIALNED
 LRSWTAADMA AQITKRKWEA ANVAERRRSY LQGLCVESLR RYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKT RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_13ms21
SLA-1_13ms21, 362 bases, 29B5A689 checksum.
 MGPGALFLML SGTLALTGTQ AGPHSLSYFY TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDNY APNPRMEPRV PWIQQEGQEY WDEETRKVKE TAQNYRVSLN
 TLRGYYNQSE AGSHTLQSMF GCYLGPDGLL LHGYRQDAYD GADYIALNED
 LRSWTAADMA AQITKRKREA ADEAERRRSY LQGLCVESLR RYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVLVAGAM VAGVVIWRKT RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_an01
SLA-1_an01, 170 bases, 95C558FE checksum.
 GTLALTGTQA GPHSLSYFYT AVSRPDRGDS RFFIVGYVDD TQFVRFDSDA
 PNPRMEPRAP WIQQEGQDYW DRETQIQRDT SQTYRVGLKN LRGYYNQSEA
 GSHTLQWMYG CYLGPDGLLL RGYSQDAYDG ADYIALNEDL RSWTAADMAA
 QITKRKWEAA DAAEQMRSYL*

>P1;SLA-1_an02
SLA-1_an02, 169 bases, 36047A85 checksum.
 TLALTGTQAG PHSLSYFSTA VSRPDLGDSR FIAVGYVDDT QFVRFDSDAP
 NPRMEPRAPW IEQEGQEYWD RETQIQRDTS QNYRVNLKNL RGYYNQSEAG
 SHTIQWMYGC DVGPDGLFLH GYHQYAYDGA DYLALNEDLR SWTAADMAAQ
 ISKRKFDAAN VAEQERSYL*

>P1;SLA-1_cs02
SLA-1_cs02, 362 bases, CDDB39E5 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDSD APNPRMEPRV PWIQQEGQDY WDEETRKVKD NAQTYGVGLK
 TLRGYYNQSE AGSHTLQSMF GCYLGPDGLL LHGYRQDTYD GADYIALNED
 LRSWTAADMA AQITKRKWEA ADEAEGERSY LQGLCVEGLQ KYLEMGEDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVLVAGAM VAGVVIWRKT RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_es11
SLA-1_es11, 362 bases, B7A45A4E checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFS TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDSD APNPRMEPRA PWIQQEGQEY WDRNTRNVMG SAQINRVNLK
 TLRGYYNQSE AGSHTLQWMY GCYLGPDGLL LRGYDQFAYD GADYLALNED
 LRSWTAADMA AQISKRKWEA ADAAEHWRSY LQGTCVESLR RYLQMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFH PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQT
 PVPMVGITVG LVLVLVAGAM VAGVVIWRKT RSGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_es12
SLA-1_es12, 362 bases, 3E16BE38 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFF TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDSD APNPRMEPRA PWIQQEGQEY WDQQTRNVMD NAQINRVNLK
 TLRGYYNQSE AGSHTLQRMF GCYLGPDGLL LRGYDQDAYD GADYLALNED
 LRSWTAADTA AQISKRKQEE ADVAERMRSY LQGTCVEGLR KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLRV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_rh03
SLA-1_rh03, 219 bases, BDDECCB9 checksum.
 YVDDTQFVRF DSDAPNPREE PRAPWIQQEG QEYWDRNTQI YKETAQTYRV
 SLNNLRGYYN QSEAGSHTLQ SMYGCYLGPD GLLLRGYRQY AYDSADYIAL
 NEDLRSWTAA DTAAQITKRK WEAANVAERR RSYLQGLCVE SLRRYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWA*

>P1;SLA-1_sk13
SLA-1_sk13, 362 bases, F825E17F checksum.
 MGPGALFLLL SGALALTGTQ AGPHSLRYFD TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDSD APNPRMEPRV PWIQQEGQDY WDEETRKVKD NAQTYRVDLN
 TLRGYYNQSE AGSHTIQTMY GCDVGPDGLL LRGYRQDAYD GADYIALNED
 LRSWTAADMA AQITKRKWKA AHEAERMRSY LQGRCVEWLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGITVG LVLVLVAGAM VAGAVIWRKK RSGEKGGSYT QAAGSDSAQG
 SDVSLTQDPR VX*

>P1;SLA-1_st11
SLA-1_st11, 362 bases, 9202D130 checksum.
 MGPRGLFLLL SGTLALTGTQ AGPHSLSYFY TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDSD APNPREEPRA PWIQQEGQEY WDRNTQIYKE TAQTYRVSLN
 NLRGYYNQSE AGSHTFQSMY GCYLGPDGLL LRGYRQYAYD SADYIALNED
 LRSWTAADTA AQITKRKWEA ADVAERRRSY LQGTCVEWLQ KYLEMGNNTL
 QRADPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVLVIGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_w09sm09
SLA-1_w09sm09, 362 bases, C94F62D6 checksum.
 MGPGALFLLL SGTLALTGTQ AGPHSLSYFF TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDSD APNPREEPRA PWIQQEGQDY WDRETQISKE TAQTYRVGLK
 TLRGYYNQSE AGSHTLQSMY GCDVGPDGLF LRGYSQDAYD GADYVALNED
 LRSWTAADMA AQITKRKREA ADVAEQERSY LQGLCVESLR EYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDHSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVV LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-1_w10cs01
SLA-1_w10cs01, 362 bases, C59F64A8 checksum.
 MGPGALFLLL SGALALTGTQ AGPHSLRYFY TAVSRPDLGD SRFIAVGYVD
 DTQFVRFDSD APNPRMEPRA PWIQQEGQEY WDRNTRNVMG SAQNDRVDLK
 TLRGYYNQSE AGSHTIQRMY GCDVGPDGLL LRGYDQDAYD GADYIALNED
 LRSWTAADTA AQITKRKWEA ANVAEQERSY LEGTCVEWLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSDQG
 SDVSLTKGPR VX*

>P1;SLA-1_w10sm21
SLA-1_w10sm21, 357 bases, 29A2D9B1 checksum.
 LFLLLSGTLA LTGTQAGPHS LRYFYTAVSR PDLGDSRFIA VGYVDDTQFV
 RFDSDAPNPR MEPRAPWIQQ EGQEYWDEET RNAMGSAQND RVDLKTLRGY
 YNQSEAGSHT IQRMYGCDVG PDGLLLRGYD QDAYDGADYI ALNEDLRSWT
 AADTAAQITK RKWEAANVAE QERSYLEGTC VEWLQKYLEM GKDTLQRAEP
 PKTHVTRHPS SDLGVTLRCW ALGFYPKEIS LTWQREGQDQ SQDMELVETR
 PSGDGTFQKW AALVVPPGEE QSYTCHVQHE GLQEPLTLRW DPPQPPVPIV
 GIIVGLVLVL VAGAVVAGVV IWRKKRSGEK GGSYTQAAGS DSDQGSDVSL
 TKGPRVX*

>P1;SLA-2_0101
SLA-2_0101, 365 bases, D7CA5DBF checksum.
 MRVRGPQAIL ILLSGALALT GTWAGPHSLS YFSTAVSRPD RGEPRFIAVG
 YVDDTQFVRF DSDAPNPRME PRAPWIQQEG QDYWDRETRN VMGSAQTDRV
 NLKTLRGYYN QSEAGSHTIQ SMYGCDVGPD GLLLRGYSQD AYDGADYIAL
 NEDLRSWTAA DTAAQITKRK WEAANVAERM RSYLQGLCVE GLQKYLQMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPIPIVGI IVGLVLVLVA GAMVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_0102
SLA-2_0102, 182 bases, 5D7E2000 checksum.
 GALALTGTWA GPHSLSYFST AVSRPDRGEP RFIAVGYVDD TQFVRFDSDA
 PNPRMEPRAP WIQQEGQDYW DRETRNVMGS AQTDRVNLKT LRGYYNQSEA
 GSHTIQSMYG CDVGPDGLLL RGYRQDAYDG ADYIALNEDL RSWTAADTAA
 QITKRKWEAA DVAEQERSYL EGTCVEWLQK YL*

>P1;SLA-2_0201
SLA-2_0201, 365 bases, 90EE05FC checksum.
 MRVRGPQAIL ILLSGALALT GTRAGPHSLS YFYTAVSRPD RGDSRFLTVG
 YVDDTQFVRF DSDAPNPREE PRAPWIQQEG QDYWDRETQI SKETAQTYRV
 NLNTLRSYYN QSEAGSHTLQ RMYGCDVGPD GLFLRGYSQF GYDGADYLAL
 NEDLRSWTAA DTAAQISKRK FDAANVAEQE RSYLQGLCVE GLRRYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWEP
 PQPPVPIVGI FVGLVLVLVA GTMVTGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK GPRVX*

>P1;SLA-2_0202
SLA-2_0202, 365 bases, 90EE05FC checksum.
 MRVRGPQAIL ILLSGALALT GTRAGPHSLS YFYTAVSRPD RGDSRFLTVG
 YVDDTQFVRF DSDAPNPREE PRAPWIQQEG QDYWDRETQI SKETAQTYRV
 NLNTLRSYYN QSEAGSHTLQ RMYGCDVGPD GLFLRGYSQF GYDGADYLAL
 NEDLRSWTAA DTAAQISKRK FDAANVAEQE RSYLQGLCVE GLRRYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWEP
 PQPPVPIVGI FVGLVLVLVA GTMVTGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK GPRVX*

>P1;SLA-2_0301
SLA-2_0301, 365 bases, C6438D3C checksum.
 MRVRGPQAIL ILLSGALALT GTRAGPHSLS YFYTAVSRPD LGDSRFIAVG
 YVDDTQFVRF DSDAPNPRME PRAPWIEKEG QEYWDRETQI QRDTSQTYRV
 DLKTLRGYYN QSEAGSHTLQ SMYGCYLGPD GLLLRGYRQF AYDGADYLAL
 NEDLRSWTAA DMAAQISKRK WEAANAAEQE RSYLQGRCVE WLRRYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPIVGI IVGLVLVLVA GAMVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_0302
SLA-2_0302, 363 bases, 8B9E3B7A checksum.
 MRVRGPQAIL ILLSGALALT GTQAGPHSLR YFYTAVSRPD RGEPRFIAVG
 YVDDTQFVRF DSDAPNPRME SRVPWIQQEG QEYWDRETQI QRDTSQTYRV
 DLKTLRGYYN QSEAGSHTLQ RMYGCYLGPD GLLLRGYHQD AYDGADYLAL
 NEDLRSWTAA DMAAQISKRK WEAADVAEQL RSYLQGRCVE SLRRYLQMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQHPVPIVGI IVGLVLVVGA MVAGVVIWWK KRSGEKGGSY TQAAGSDSAQ
 GSDVSLTKGP RVX*

>P1;SLA-2_03gz01
SLA-2_03gz01, 365 bases, 881B8839 checksum.
 MRVRGPQAIL ILLSGALALT GTQAGPHSLS YFYTAVSRPD RGEPRFIAVG
 YVDDTQFVRF DSDAPNPRME PRVPWIQQEG QEYWDRETQI QRDTSQTYRV
 GLNTLRGYYN QSEAGSHTIQ SMYGCYLGPD GLLLRGYSQD AYDGADYVAL
 NEDLRSWTAA DMAAQISKRK WEAADVAEQL RSYLQGTCVE WLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPIVGI IVGLVLVLVA GAMVAGVVIW WKKRSGEKGG SYTQAAGSDS
 AQGSNVSLNK DPRVX*

>P1;SLA-2_0401
SLA-2_0401, 365 bases, C8211540 checksum.
 MRVRGPQAIL ILLSGALALT GTQAGPHSLR YFDTAVSRPD RGEPRFIEVG
 YVDDTQFVRF DSDAPNPRME PRAPWIQQEG QEYWDRNTRN AMGNAQIYRG
 NLRTALGYYN QSEAGSHTIQ IMYGCDVGPD GLLLRGYSQD AYDGADYIAL
 NEDLRSWTAA DTAAQITKRK WEAADEAERR RSYLQGTCVE WLQKYLQMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPIVGI IVGLVLVLVA GAVVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_040201
SLA-2_040201, 365 bases, 60BD92 checksum.
 MRVRGPQAIL ILLSGALALT GTQAGPHSLR YFDTAVSRPD RGEPRFIEVG
 YVDDTQFVRF DSDAPNPRME PRAPWIQQEG QEYWDRNTRN AMGNAQIYRG
 NLRTALGYYN QSEAGSHTLQ IMYGCDVGPD GLLLRGYSQD AYDGADYIAL
 NEDLRSWTAA DTAAQITKRK WEAANVAEQW RSYLQGTCVE WLQKYLQMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPIVGI IVGLVLVLVA GAVVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_040202
SLA-2_040202, 365 bases, 60BD92 checksum.
 MRVRGPQAIL ILLSGALALT GTQAGPHSLR YFDTAVSRPD RGEPRFIEVG
 YVDDTQFVRF DSDAPNPRME PRAPWIQQEG QEYWDRNTRN AMGNAQIYRG
 NLRTALGYYN QSEAGSHTLQ IMYGCDVGPD GLLLRGYSQD AYDGADYIAL
 NEDLRSWTAA DTAAQITKRK WEAANVAEQW RSYLQGTCVE WLQKYLQMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPIVGI IVGLVLVLVA GAVVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_0501
SLA-2_0501, 362 bases, FD6E5D6E checksum.
 RGPQAILILL SGALALTGTW AGPHSLSYFY TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDSD APNPRMEPRA PWIEKEGQEY WDEETRNAMG SAQTFRVNLR
 TALGYYNQSV AGSHTFQWMY GCYLGPDGLL LRGYSQYAYD SADYIALNED
 LRSWTAADTA AQITKRKWET ANVAERRRSY LQGLCVEWLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWEPPQP
 PVPIVGIIVG LVLVLVAGAM VAGVVIWRKK RPGEKGGSYT QAAGSDSAQG
 SDVSLTKDPR VX*

>P1;SLA-2_0502
SLA-2_0502, 365 bases, 4C85A6FB checksum.
 MRVRGPQAIL ILLSGALALT GTWAGPHSLS YFYTAVSRPD RGDSRFIAVG
 YVDDTQFVRF DSDAPNPRME PRAPWIEKEG QEYWDRNTRN AMRSAQTFRV
 NLRTALGYYN QSVAGSHTFQ SMYGCYLGPD GLLLRGYRQY AYDSADYIAL
 NEDLRSWTAA DTAAQITKRK WETANVAEGE RSYLQGLCVE SLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWEP
 PQPPVPIVGI IVGLVLVLVA GAMVAGVVIW RKKRPGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_05rh03
SLA-2_05rh03, 219 bases, 82259480 checksum.
 YVDDTQFVRF DSDAPNPRME PRAPWIEKEG QEYWDEETRK VMGSAQTFRV
 NLRTALGYYN QSVAGSHTLQ WMYGCYLGPD GLLLRGYRQD AYDGADYIAL
 NEDLRSWTAA DTAAQITKRK WEAADEAEQW RSYLQGLCVE GLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWA*

>P1;SLA-2_05rh07
SLA-2_05rh07, 263 bases, C013EB4E checksum.
 YFYTAVSRPD RGDSRFIAVG YVDDTQFVRF DSDAPNPRME PRAPWIEKEG
 QEYWDEETRK VMGSAQTFRV NLRTALGYYN QSVAGSHTFQ WMYGCYLGPD
 GLLLRGYSQY AYDSADYIAL NEDLRSWTAA DTAAQISKRK WETANVAEGE
 RSYLQGLCVE SLQKYLEMGK DTLQRAEPPK THVTRHPSSD LGVTLRCWAL
 GFYPKEISLT WQREGQDQSQ DMELVETRPS GDGTFQKWAA LVVPPGEEQS
 YTCHVQHEGL QEP*

>P1;SLA-2_05rh34
SLA-2_05rh34, 219 bases, 8317F04A checksum.
 YVDDTQFVRF DSDAPNPRME PRAPWIEKEG QEYWDEETRN AMGSAQTFRV
 NLRTALGYYN QSVAGSHTFQ WMYGCYLGPD GLLLRGYSQY AYDSADYIAL
 NEDLRSWTAA DTAAQITKRK WETANVAERR RSYLQGLCVD WLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWA*

>P1;SLA-2_05sy01
SLA-2_05sy01, 365 bases, 4F98AF8A checksum.
 MRVRGPQAIL ILLSGALALT GTWAGPHSLS YFSTAVSRPD RGDSRFIAVG
 YVDDTQFVRF DSDAPNPRME PRAPWIEKEG QEYWDEETRK VMGSAQTFRV
 NLRTALGYYN QSVAGSHTFQ WMFGCYLGPD GLLLRGYSQY AYDSADYIAL
 NEDLRSWTAA DTAAQITKRK WETANVAEGE RSYLQGLCVE GLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWEP
 PQPPVPIVGI IVGLVLVLVA GAMVAGVVIW RKKRPGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_0601
SLA-2_0601, 365 bases, E928D7F3 checksum.
 MRVRGPQAIL ILLSGALALT GTQAGSHSLS YFHTAVSRPD LGDSRFLTVG
 YVDDTQFVRF DSDAPNPRKE PRAPWIEQEG QDYWDRETQI SKDYAQRYRV
 GLNTLRGYYN QSEAGSHTYQ RMYGCDMGPD GLLLRGYDQF AYDGADYVAL
 NEDLRSWTAA DTAAQITKRK WEAADAAEQE RSYLQGTCVE WLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQQWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWEP
 PQPPVPIVGI TVGLVLVLVA GAMVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_06an03
SLA-2_06an03, 182 bases, 1160126C checksum.
 GALALTGTRA GPHSLRYFHT AVSRPDRGDS RFLTVGYVDD TQFVRFDSDA
 PNPRKEPRAP WIEQEGQDYW DRETQISKDN AQIYRGSLNN LRGYYNQSEA
 GSHTLQWMCG CDVGPDGLFL RGYDQDAYDG ADYIALNEDL RSWTAADTAA
 QITKRKWEAA DEAERMRSYL QGRCVESLQK YL*

>P1;SLA-2_06me01
SLA-2_06me01, 365 bases, 6B2A71A8 checksum.
 MRVRGPQAIL ILLSGALALT GTQAGPHSLR YFYTAVSRPD LGDSRFLTVG
 YVDDTQFVRF DSDAPNPRKE PRAPWIEQEG PEYWDRETQI SKDNAQNYRV
 NLNTLRGYYN QSEAGSHTLQ VMFGCDVGPD GLFLHGYHQD AYDGADYIAL
 NEDLRSWTAA DMAAQITKRK REASGWAEQW RSYLQGLCVE GLRRYLEMGK
 DTLQHAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWEP
 PQPPVPIVGI IVGLVLVLVA GAMVAGVVIW RKKRPGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_06sr01
SLA-2_06sr01, 353 bases, 274EB9E4 checksum.
 LSGALALTGT QAGPHSLSYF HTAVSRPDLG DSRFLTVGYV DDTQFVRFDS
 DAPNPRKEPR APWIEQEGQD YWDRETQISK DNAQTYRVGL NTLRGYYNQS
 EAGSHTLQVM FGCDVGPDGL LLRGYIQFAY DGADYLALNE DLRSWTAADT
 AAQISKRKFD AADEAEQMRS YLQGLCVESL RKYLEMGKDT LQRAEPPKTH
 VTRHPSSDLG VTMRCWALGF YPKEISLTWQ REGQDQSQDM ELVETRPSGD
 GTFQKWAALV VPPGEEQSYT CHVQHEGLQE PLTLRWEPPQ PPVPIVGIIV
 GLVLVLVAGA MVAGVVIWRK KRSGEKGGSY TQAAGSDSAQ GSDVSLTKDP
 RVX*

>P1;SLA-2_06sv01
SLA-2_06sv01, 353 bases, BB9A7703 checksum.
 LSGALALTGT QAGSHSLSYF HTAVSRPDLG DSRFLTVGYV DDTQFVRFDS
 DAPNPRKEPR APWIEQEGQD YWDRETQISK DNAQRYRVGL NTLRGYYNQS
 EAGSHTLQSM FGCDVGPDGL FLRGYSQDAY DGADYIALNE DLRSWTAADT
 AAQITKRKWE AADEAERMRS YLQGLCVEGL REYLEMGKDT LQRAEPPKTH
 VTRHPSSDLG VTLRCWALGF YPKEISLTWQ REGQDQSQDM ELVETRPSGD
 GTFQKWAALV VPPGEEQSYT CHVQHEGLQE PLTLRWEPPQ PPVPIVGIIV
 GLVLVLVAGA MVAGVVIWRK KRSGEKGGSY TQAAGSDSAQ GSDVSLTKDP
 RVX*

>P1;SLA-2_0701
SLA-2_0701, 365 bases, 92E826D1 checksum.
 MRVRGPQAIL ILLSGALALT GTWAGPHSLS YFSTAVSRPD RGDSRFIAVG
 YVDDTQFVRF DSDAPNPRME PRAPWIQQEG QDYWDRETRN VMGSAQTDRV
 SLNNLRGYYN QSEAGSHTLQ VMYGCDVGPD GLFLHGYRQF AYDGADYLAL
 NEDLRSWTAA DMAAQISKRK FDAANVAEGE RSYLEGLCVE GLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPIVGI IVGLVLVLVA GAMVTGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_07an05
SLA-2_07an05, 182 bases, 94D7C655 checksum.
 GALALTGTWA GPHSLSYFST AVSRPDRGDS RFIAVGYVDD TQFVRFDSDA
 PNPRMEPRAP WIQQEGQDYW DRETRNVMGS AQTDRVSLNN LRGYYNQSEA
 GSHTLQVMYG CDVGPDGLLL RGYHQYGYDG ADYLALNEDL RSWTAADMAA
 QISKRKFDAA NVAEGERSYL KGLCVEGLQK YL*

>P1;SLA-2_07rh12
SLA-2_07rh12, 62 bases, 20995242 checksum.
 YVDDTQFVRF DSDAPNPRME PRAPWIQQEG QDYWDRETRN VMGSAQTDRV
 NLKTLRGYYN QS*

>P1;SLA-2_07we01
SLA-2_07we01, 365 bases, 1DE9999C checksum.
 MRVRGPQAIL ILLSGALALT GTWAGPHSLS YFYTAVSRPD RGDSRFIAVG
 YVDDTQFVRF DSDAPNPRME PRAPWIQQEG QDYWDRETRN VMGSAQTDRV
 NLKTLRGYYN QSEAGSHTLQ VMYGCDVGPD GLLLRGYRQF AYDGADYLAL
 NEDLRSWTAA DMAAQISKRK FDAANVAEGE RSYLEGLCVE GLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPIVGI IVGLVLVLVA GAMVTGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_1001
SLA-2_1001, 365 bases, 6EE242B2 checksum.
 MRVRGPQAIL ILLSGALALT GTQAGPHSLS YFYTAVSRPD RGDSRFFIVG
 YVDDTQFVRF DSDAPNAKME PRAQWIQQEG QEYWDRETQI SKDNAQINRV
 NLNTLRGYYN QSEAGSHTLQ RMYGCYLGPD GLLLRGYDQD AYDGADYIAL
 NEDLRSWTAA DMAAQISKRK REAADEAERM RSYLQGRCVE WLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLS WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 AQPPVPMVGI IVGLVLVLVA GAMVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_1002
SLA-2_1002, 182 bases, C129819A checksum.
 GALALTGTQA GPHSLSYFYT AVSRPDRGDS RFFIVGYVDD TQFVRFDSDA
 PNAKMEPRAQ WIQQEGQEYW DRETQISKET AQNYRVDLNT LRGYYNQSEA
 GSHTLQRMYG CYLGPDGLLL RGYRQDAYDG ADYIALNEDL RSWTAADMAA
 QITKRKWEAA NVAEGERSYL QGRCVEWLQK YL*

>P1;SLA-2_10es21
SLA-2_10es21, 365 bases, E21F5388 checksum.
 MRVRGPQAIL ILLSGALALT GTQAGPHSLS YFYTAVSRPD RGDSRFFIVG
 YVDDTQFVRF DSDAPNAKME PRAQWIQQEG QEYWDRETQI SKDNAQTYRV
 GLKNLRGYYN QSEAGSHTLQ RMFGCYLGPD GLLLRGYDQD AYDGADYLAL
 NEDLRSWTAA DMAAQISKRK REAADEAERM RSYLQGRCVE WLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLS WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 AQPPVPMVGI IVGLVLVLVA GAMVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_10sk21
SLA-2_10sk21, 365 bases, 7268624B checksum.
 MRVRGPQAIL ILLSGALALT GTQAGPHSLS YFYTAVSRPD RGDSRFFIVG
 YVDDTQFVRF DSDAPNAKME PRAQWIQQEG QEYWDRETQI SKETAQNYRV
 DLNTLRGYYN QSEAGSHTYQ WMYGCYLGPD GLLLRGYDQD AYDGADYLAL
 NEDLRSWTAA DMAAQISKRK REAADEAERM RSYLQGRCVE WLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLS WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 AQPPVPMVGI IVGLVLVLVA GAMVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_10sm01
SLA-2_10sm01, 365 bases, FDA91BE7 checksum.
 MRVRGPQAIL ILLSGALALT GTQAGPHSLS YFYTAVSRPD RGDSRFFIVG
 YVDDTQFVRF DSDAPNAKME PRAQWIQQEG QEYWDRETQI SKETAQINRV
 DLNTLRGYYN QSEAGSHTLQ RMFGCYLGPD GLLLRGYDQD AYDGADYLAL
 NEDLRSWTAA DMAAQISKRK REAADEAERM RSYLQGRCVE WLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLS WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 AQPPVPMVGI IVGLVLVLVA GAMVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_110101
SLA-2_110101, 365 bases, C3D6E91E checksum.
 MRVRGPQAIL ILLSGALALT GTWAGPHSLS YFYTAVSRPD RGDSRFIAVG
 YVDDTQFVRF DSDAPNPREE PRAPWIQQEG QEYWDRNTQI YKETAQIYRG
 NLRTALGYYN QSEAGSHTFQ SMYGCDVGPD GLLLRGYSQF GYDGADYIAL
 NEDLRSWTAA DTAAQITKRK WEAADAAERR RSYLQGLCVE SLREYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPMVGI IVGLVLVLVA GAMVTGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_110102
SLA-2_110102, 365 bases, C3D6E91E checksum.
 MRVRGPQAIL ILLSGALALT GTWAGPHSLS YFYTAVSRPD RGDSRFIAVG
 YVDDTQFVRF DSDAPNPREE PRAPWIQQEG QEYWDRNTQI YKETAQIYRG
 NLRTALGYYN QSEAGSHTFQ SMYGCDVGPD GLLLRGYSQF GYDGADYIAL
 NEDLRSWTAA DTAAQITKRK WEAADAAERR RSYLQGLCVE SLREYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPMVGI IVGLVLVLVA GAMVTGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_11so01
SLA-2_11so01, 365 bases, E23AE964 checksum.
 MRVRGPQAIL ILLSGALALT GTWAGPHSLS YFYTAVSRPD RGDSRFIAVG
 YVDDTQFVRF DSDAPNPREE PRAPWIQQEG QEYWDRNTQI YKETAQIYRG
 NLRTALGYYN QSEAGSHTFQ SMCGCYLGPD GLLLRGYSQY GYDGADYIAL
 NEDLRSWTAA DTAAQITKRK WEAADAAEQE RSYLQGTCVE WLQKYLEMGE
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPMVGI IVGLVLVLVA GAMVTGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_1201
SLA-2_1201, 365 bases, F176EC35 checksum.
 MRVRGPQAIL ILLSGALALT GTWAGPHSLS YFYTAVSRPD RGDSRFIAVG
 YVDDTQFVRF DSDAPNPRME PRAPWIEKEG QEYWDRETRN VMGSAQTDRV
 NLKTLRGYYN QSEAGSHTFQ WMYGCYLGPD GLLLRGYSQF AYDSADYIAL
 NEDLRSWTAA DTAAQISKRK WEAANVAEHW RSYLQGLCVE SLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWEP
 PQPPVPIVGI IVGLVLVLVA GAMVAGVVIW RKKRPGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_12Lw01
SLA-2_12Lw01, 365 bases, C3E95272 checksum.
 MRVRGPQAIL ILLSGALALT GTWAGPHSLS YFYTAVSRPD RGDSRFIAVG
 YVDDTQFVRF DSDAPNPRME PRAPWIEKEG QEYWDRETRN VMGSAQTDRV
 NLKTLRGYYN QSEAGSHTFQ WMYGCYLGPD GLLLRGYSQF AYDSADYIAL
 NEDLRSWTAA DTAAQISKRK LEAANVAEHW RSYLQGLCVE SLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWEP
 PQPPVPIVGI IVGLVLVLVA GAMVAGVVIW RKKRPGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_an04
SLA-2_an04, 175 bases, 46169BC8 checksum.
 GALALTGTRA GPHSLSYFHT AVSRPDRGDS RFLTVGYVDD TQFVRFDSDA
 PNPREEPRAP WIEKEGQEYW DRNTQISKET AQTFRVDLNT LRGYYNQSEA
 GSHTIQWMYG CDMGPDGLFL HGYHQYAYDG ADYLALNEDL RSWTAADMAA
 QITKRKFDAA NVAERRRSYL QGRCV*

>P1;SLA-2_es22
SLA-2_es22, 365 bases, F2DB3AED checksum.
 MRVRGPQAIL ILLSGALALT GTWAGPHSLS YFYTAVSRPD RGEPRFIAVG
 YVDDTQFVRF DSDAPNPRME PRAPWIQQEG QDYWDRETQI QRDNAQTFRV
 NLRTALGYYN QSEAGSHTFQ SMYGCYLGPD GLLLRGYSQY GYDSADYIAL
 NEDLRSWTAA DTAAQITKRK WEAADEAEQW RSYLQGLCVE GLRRYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPIPIVGI IVGLVLVLVA GAMVTGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_jh01
SLA-2_jh01, 365 bases, 2E74ECA9 checksum.
 MRVRGPQAIL ILLSGALALT GTQAGPHSLS YFYTAVSRPD RGKPRFIEVG
 YVDDTQFVRF DSDAPNPRME PRVPWIEKEG QEYWDEETRK AVGSAQTFRG
 SLNNLRGYYN QSEAGSHTLQ IMYGCDVGPD GLLLRGYRQD AYDGADYIAL
 NEDLRSWTAA DTAAQITKRK WETADEAEQW RSYLQGLCVE WLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPIVGI IVGLVLVLVA GAVVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_jh02
SLA-2_jh02, 365 bases, D4CA6FB4 checksum.
 MRVRGPQAIL ILLSGALALT GTQAGSHSLS YFYTAVSRPD RGDSRFLTVG
 YVDDTQFVRF DSDAPNPREE PRAPWIQQEG QDYWDRNTQI YKETAQIYRV
 GLNNLRGYYN QSEAGSHTFQ SMYGCDVGPD GLFLRGYSQD AYDGADYVAL
 NEDLRSWTAA DMAAQITKRK REAADAAEQW RSYLQGTCVE GLRRYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPIVGI IVGLVLVLVT GAVVTGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_sw14yn01
SLA-2_sw14yn01, 365 bases, 436A3729 checksum.
 MRVRGPQAIL ILLSGALALT GTQAGPHSLR YFYTAVSRPD RGDSRFLTVG
 YVDDTQFVRF DSDAPNPREE PRAPWIEQEG QDYWDRETQI SKETAQTYRV
 GLKILRGYYN QSEAGSHTYQ WMYGCYLGPD GLFLRGYSQY GYDGADYIAL
 NEDLRSWTAA DTAAQITKRK WEAADEAEQM RSYLQGLCVE WLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQTQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWEP
 PQPPVPIVGI IVGLVLVLVT GAMVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_w08gx01
SLA-2_w08gx01, 365 bases, A34DE4EC checksum.
 MRVRGPQAIL ILLSGALALT GTWAGPHSLR YFHTAVSRPD RGDSRFLTVG
 YVDDTQFVRF DSDAPNPRKE PRAPWIEQEG QDYWDRETQI SKDNAEINRV
 GLNTLRGYYN QSEAGSHTLQ SMYGCDVGPD GLFLRGYSQD AYDGADYIAL
 NEDLRFWTAA DMAVQITKRK WEAADAAEEE RSYLQGTCVE WLRRYLEMGK
 DTCKRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 AQPPVPMVGI IVGLVLVLVA GAVVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_w08sw01
SLA-2_w08sw01, 364 bases, C10AD579 checksum.
 MRVRGPQAIL ILLSGALALT GTWAGPHSLR YFHTAVSRPD RGDSRFLTVG
 YVDDTQFVRF DSDAPNPRKE PRAPWIEQEG QDYWDRETQI SKDNAEINRV
 DLKTLRGYYN QSEAGSHTLQ SMYGCDVGPD GLFLRGYRQD AYDGADYIAL
 NEDLRSWTAA DMAAQITKRK WEAADAAERR RSYLQGTCVE WLRRYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVGTRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 AQPPVPMVGI IVGLVLVLVA GAVVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK GPRV*

>P1;SLA-2_w09an02
SLA-2_w09an02, 180 bases, 30D8B1CA checksum.
 ALALTGTQAG PHSLSYFYTA VSRPDLGDSR FLTVGYVDDT QFVRFDNYAP
 NPRMEPRAPW IQQEGQEYWD RETRKVKETA QTYRVGLNTL RGYYNQSEAG
 SHTIQSMFGC DVGPDGLFLH GYHQDAYDGA DYIALNEDLR SWTAADMAAQ
 ITKRKREAAN VAEHWRSYLQ GLCVEGLRKY*

>P1;SLA-2_w09pt22
SLA-2_w09pt22, 363 bases, 65957E74 checksum.
 MRVRGPQAIL ILLSGALALT GTQAGSHSLS YFHTAVSRPD RGDSRFIAVG
 YVDDTQFVRF DNYAPNPRME PRAPWIQQEG QDYWDRETQI SKDNAQIYRV
 GLNNLRGYYN QSEAGSHTIQ SMYGCDVGPD GLFLHGYHQD AYDGADYIAL
 NEDLRSWTAA DMAAQISKRK REAADVAEHW RSYLQGRCVE GLRRYLQMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWEP
 PQPPVPIVGI IVGLVFVVGT MVAGVVIWWK KRSGEKGGSY TQAAGSDSAQ
 GSDVSLTKGP RVX*

>P1;SLA-2_w09sn01
SLA-2_w09sn01, 365 bases, 926B962A checksum.
 MRVRGPQAIL ILLSGALALT GTQAGPHSLS YFYTAVSRPD LGDSRFLTVG
 YVDDTQFVRF DNYAPNPRME PRAPWIQQEG QEYWDRETRK VKETAQTYRV
 GLNTLRGYYN QSEAGSHTIQ SMFGCDVGPD GLFLHGYHQD AYDGADYIAL
 NEDLRSWTAA DMAAQITKRK WEAADAAEHW RSYLQGLCVE GLRKYLQMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWEP
 PQPPVPIVGI IVGLVLVLVA GAMVAGVVIW RKKRPGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_w13sm20
SLA-2_w13sm20, 365 bases, 618E1DE9 checksum.
 MRVRGPQAIL ILLSGALALT GTWAGPHSLS YFYTAVSRPD RGDSRFIAVG
 YVDDTQFVRF DSDAPNPRME PRAPWIEQEG QGYWDRETRN VMGSAQTYRV
 NLNTLRGYYN QSEAGSHTIQ IMYGCDVGPD GLLLRGYRQD AYDGADYIAL
 NEDLRSWTAA DMAAQITKRK WEAADVAEGE RSYLQGRCVE WLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPIVGI IVGLVLLLVA VAMVTGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-3_0101
SLA-3_0101, 362 bases, 4E4634DD checksum.
 MGPRALFLLL SGTLALTGTR EGPHSLRYFD TAVSRPDRGK PRFISVGYVD
 DTQFVRFDSD APNPRMEPRA PWIEQEGQEY WDEETRNAMG SAQTFRVNLN
 NLRGYYNQSE AGSHTFQSMY GCDVGPDGLL LRGYSQFGYD GADYIALNED
 LRSWTAADTA AQITKRKREA ADAAEQMRSY LEGACVVWLQ KYLEMGNNTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGITVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSAQG
 SDVSLTKDPR VX*

>P1;SLA-3_01ev04
SLA-3_01ev04, 295 bases, 64C4B1D6 checksum.
 MGPGALFLLL SGTLALTGTR EGPHSLRYFD TAVSRPDRGK PRFISVGYVD
 DTQFVRFDSD APNPRMEPRA PWIEQEGQEY WDEETRNAMG SAQTFRVNLN
 NLRGYYNQSE AGSHTFQSMY GCDVGPDGLL LRGYSQFGYD GADYIALNED
 LRSWTAADTA AQITKRKREA ADAAEQMRSY LEGACVVWLQ KYLEMGSNTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRW*

>P1;SLA-3_01rh12
SLA-3_01rh12, 219 bases, B3428738 checksum.
 YVDDTQFVRF DSDAPNPRME PRAPWIEQEG QEYWDEETRN AMGSAQTFRV
 NLNNLRGYYN QSEAGSHTFQ SMYGCDVGPD GLLLRGYSQF GYDGADYIAL
 NEDLRSWTAA DTAAQITKRK REAADVAEQM RSYLEGACVE WLQKYLQMGN
 NTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWA*

>P1;SLA-3_01rh28
SLA-3_01rh28, 219 bases, 9BFBB585 checksum.
 YVDDTQFVRF DSDAPNPRME PRAPWIEQEG QEYWDEETRN AMGGAQTFRV
 NLNNLRGYYN QSEAGSHTFQ SMYGCDVGPD GLLLRGYSQF GYDGADYIAL
 NEDLRSWTAA DTAAQITKRK REAADAAEQM RSYLEGACVV WLQKYLEMGN
 NTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWA*

>P1;SLA-3_0301
SLA-3_0301, 362 bases, CF927CF6 checksum.
 MGPRALFLLL SGTLALTGTR EGPHSLRYFD TAVSRPDRRK PRFISVGYVD
 DTQFVRFDSD APNPRMEPRA PWIQQEGQKY WDEETQNAMG SAQTFRVNLK
 NLRGYYNQSE AGSHTLQSMY GCDVGPDGLF LRGYHQDAYD GADYIALNED
 LRSWTAADTA AQIAKRKWEA ADVAEQWRSY LEGACVEWLQ KYLEMGNNTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGIIVG LVLVLVTGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSAQG
 SDVYLIKDPR VX*

>P1;SLA-3_0302
SLA-3_0302, 362 bases, 7F657DA4 checksum.
 MGPRALFLLL SGTLALTGTR EGPHSLRYFD TAVSRPDRGK PRFISVGYVD
 DTQFVRFDSD APNPRMEPRA QWIQQEGQDY WDRETQNSKD NAQRYRVNLK
 NLRGYYNQSE AGSHTIQRMY GCDVGPDGLF LHGYHQDAYD GADYLALNED
 LRSWTAADTA AQISKRKWEA ADAAEQWRSY LEGACVEGLQ KYLDLGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQES LTLRWDPPQH
 PVPIMGIIVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSAQG
 SDVYLIKDPR VX*

>P1;SLA-3_0303
SLA-3_0303, 362 bases, 7D4BFCAF checksum.
 MGPRALFLLL SGTLALTGTR EGPHSLRYFD TAVSRPDRGK PRFISVGYVD
 DTQFVRFDSD APNPRMEPRV PWIEKEGQEY WDEETQNAMG SAQTFRVNLK
 NLRGYYNQSE AGSHTLQSMY GCDVGPDGLF LHGYHQDAYD GADYIALNED
 LRSWTAADTA AQIAKRKWEA ADVAEQWRSY LEGACVEWLQ KYLEMGNNTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSAQG
 SDVYLIKDPR VX*

>P1;SLA-3_0304
SLA-3_0304, 362 bases, 139E2E8F checksum.
 MGPGALFLLL SGTLALTGTR EGPHSLRYFD TAVSRPDRGK PRFISVGYVD
 DTQFVRFDSD APNPRMEPRA PWIEKAEQKY WDEETQNAMG SAQTFRVNLK
 NLRGYYNQSE AGSHTLQSMY GCDVGPDGLF LHGYHQDAYD GADYIALNED
 LRSWTAADTA AQIAKRKWEA ADAAEQWRSY LEGACVEWLQ KYLEMGNNTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR ESQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVLVAGAM VAGVVIWRKT RSGEKGGSYT QAAGSDSDQG
 SDVSLTKDPR VX*

>P1;SLA-3_03an02
SLA-3_03an02, 165 bases, 66EED070 checksum.
 TREGPHSLRY FDTAVSRPDR GKPRFISVGY VDDTQFVRFD SDAPNPRMEP
 RAQWIQQKGQ EYWDRETQIS KDNAQRYRVN LKNLRGYYNQ SEAGSHTIQS
 MYGCDVGPDG LFLHGYHQDA YDGADYLALN EDLRSWTAAD MAAQITKRKW
 EAADAAEQWR SYLEG*

>P1;SLA-3_03an04
SLA-3_03an04, 166 bases, 45735233 checksum.
 TREGPHSLRY FDTAVSRPDR GKPRFISVGY VDDTQFVRFD SDALNPRMEP
 RAPWIEKAEQ KYWDEETQNA MGSAQTFRVN LKNLRGYYNQ SEAGSHTLQS
 MYGCDVGPDG LFLHGYHQDA YDGADYIALN EDLRSWTAAD TAAQIAKRKW
 EAADVAEQWR SYLEGA*

>P1;SLA-3_03an05
SLA-3_03an05, 178 bases, 50B5A0B1 checksum.
 LSGTLALTGT REGPHSLRYF DTAVSRPDRG KPRFISVGYV DDTQFVRFDS
 DAPNPRMEPR APWIEKDEQK YWDEETQNAM GSAQTFRVNL KNLRGYYNQS
 EAGSHTLQSM YGCDVGPDGL FLHGYHQDAY DGADYIALNE DLRSWTAADT
 AAQIAKRKWE AADAAEQWRS YLEGACVV*

>P1;SLA-3_03pt31
SLA-3_03pt31, 362 bases, AB26C5D9 checksum.
 MGPRALFLLL SGTLALTGTR EGPHSLRYFD TAVSRPDRGK PRFISVGYVD
 DTQFVRFDSY APNPRMEPRA QWIQQEGQEY WDRETQISKD NAQRYRVNLN
 TLRGYYNQSE AGSHTIQTMY GCDVGPDGLF LHGYHQYAYD GADYLALNED
 LRSWTAADTA AQISKRKREA ADAAEQWRSY LEGACVEWLQ KYLEMGEDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQH
 PVPIMGIIVG LVLVLVAGAV VAGVVIWRKK RSGEKGGSYT QAAGSDSSQG
 SDVYLIKDPR VX*

>P1;SLA-3_0401
SLA-3_0401, 362 bases, 10CB9A7D checksum.
 MGPRALFLLL SGALALTGTR AGPHSLRYFD TAVSRPDRGK PRFIEVGYVD
 DTQFVRFDSD APNPRMEPRV PWIEKEGQEY WDKETENAMG SAQTFRVNLK
 NLRGYYNQSE AGSHTLQSMY GCDVGPDGLL LRGYSQDAYD GADYIALNED
 LRSWTAADTA AQITKRKREA ADAAEQMRSY LEGACVEWLQ KYLQMGKDTL
 QHAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGIIVG LVLVLVAGAV VTGVVIWRKK RSGEKGGSYT QAAGSDSAQG
 SDVSLTKDPR VX*

>P1;SLA-3_0402
SLA-3_0402, 361 bases, AFD0D710 checksum.
 MGPRALVLLL SGALALTGTR AGPHSLRYFD TALSRPDRGK PRFIEVGYVD
 DTQFVRFDSD APNPRMEPRA PWIEKAEQKY WDEETQNAMG SAQTFRVNLK
 KLRGYYNQSE AGSHTLQSMY GCDVGPDGLL LRGYSQDAYD GADYIALNED
 LRSWTAADTA AQITKRKREA DAAEQMRSYL EGACVEWLQK YLEMGKDTLQ
 RAEPPKTHVT RHPSSDLGVT LRCWALGFYP KEISLTWQRE GQDQSQDMEL
 VETRPSGDGT FQKWAALVVP PGEEQSYTCH VQHEGLQEPL TLRWDPPQPP
 VPIVGIIVGL VLVLVAGAMV TGVVIWRKKR SGEKGGSYTQ AAGSDSAQGS
 DVSLTKDPRV X*

>P1;SLA-3_04es32
SLA-3_04es32, 365 bases, 6B643870 checksum.
 MGPRALVLLL SGALALTGTR AGPHSLRYFD TALSRPDRGK PRFIEVGYVD
 DTQFVRFDSD APNPRMEPRA PWIEKAEQKY WDEETQNAMG SAQTFRVNLK
 KLRGYYNQSE AGSHTLQSMY GCDVGPDGLL LRGYSQDAYD GADYIALNED
 LRSWTAADTA AQITKRKREA DAAEQMRSYL EGACVEWLQK YLEMGKDTLQ
 RAEPPKTHVT RHPSSDLGVT LRCWALGFYP KEISLTWQRE GQDQGQDQSQ
 YMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPIVGI IVGLVLVLVA GAMVTGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-3_0501
SLA-3_0501, 363 bases, 136B79D5 checksum.
 MGPRALVLLL SGTLALTGTR AGPHSLRYFD TAVSRPDRGK PRFIEVGYVD
 DTQFVWFDSD APNPRMEPRA PWIEQEGQEY WDRETQISKD NAQTYRVNLN
 NLRGYYNQSE AGSHTLQSMY GCDVGPDGLF LRGYSQFAYD GADYIALNED
 LRSWTAADTA AQITKRKREA ADAAEQMRSY LEGACVEGLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVVLVAGA MVAGVVIWRK KRSGEKGGSY TQAAGSDSAQ
 GSDVSLTQDP RVX*

>P1;SLA-3_0502
SLA-3_0502, 362 bases, 7412C536 checksum.
 MGPRALVLLL SGTLALTGTR AGPHSLRYFD TAVSRPDRGK PRFIEVGYVD
 DTQFVWFDSD APNPRMEPRA PWIQQEGQEY WDRETQISKD NAQTYRVNLN
 NLRGYYNQSE AGSHTLQSMY GCDVGPDGLF LRGYSQFAYD GADYIALNED
 LRSWTAADTA AQITKRKREA ADAAEQMRSY LEGACVEGLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLSWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGIIVG LVLVLVAGAM VAGVVIWRKK RSGEKGGSYT QAAGSDSAQG
 SDVSLTQDPR VX*

>P1;SLA-3_0503
SLA-3_0503, 362 bases, E67675CB checksum.
 MGPRALVLLL SGTLALTGTR AGPHSLRYFD TAVSRPDRGK PRFIEVGYVD
 DTQFVWFDSD APNPRMEPRA PWIEKEGQEY WDRETQISKD NAQTYRVNLN
 NLRGYYNQSE AGSHTLQSMY GCDVGPDGLF LRGYSQFAYD GADYIALNED
 LRSWTAADTA AQITKRKREA ADAAEQMRSY LEGACVEGLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVLVAGAM VAGVVIWRKK RSGEKGGSYT QAAGSDSAQG
 SDVSLTQDPR VX*

>P1;SLA-3_05sw01
SLA-3_05sw01, 362 bases, C1C3EF50 checksum.
 MGPRALVLLL SGTLALTGTR AGPHSLRYFD TAVSRPDRGK PRFIEVGYVD
 DTQFVWFDSD APNPRMEPRA PWIEKEGQEY WDRETQISKD NAQTYRVNLN
 NLRGYYNQSE AGSHTLQSMY GCDVGPDGLF LRGYSQFAYD GTDYIALNED
 LRSWTAADTA AQITKRKREA ADAAEQMRSY LEGACVEGLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPAQP
 PVPIVGIIVG LVLVLVAGAM VAGVVIWRKK RSGEKGGRYT QAAGSDSAQG
 SDVSLTQDPR VX*

>P1;SLA-3_0601
SLA-3_0601, 362 bases, 6448E0EE checksum.
 MGPRALFLLL SGTLALTGTR EGPHSLRYFD TAVSRPDRGK PRFISVGYVD
 DTQFVRFDSD APNPRMEPRA PWIEQEGQEY WDEETRNAMG SAQTFRVNLN
 NLRGYYNQSE AGSHTLQSMY GCDVGPDWLF LRGYSQDAYD GADYIALNED
 LRSWTAADTA AQITKRKWEA ADEAEQMRSY LEGACVEWLQ KYLQMGNNTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RPGEKGGSYT QAAGSDSAQG
 SDVSLTKDPR VX*

>P1;SLA-3_0602
SLA-3_0602, 362 bases, 55A24CC checksum.
 MGPGALFLLL SGTLALTGTR EGPHSLRYFD TAVSRPDRGK PRFTSVGYVD
 DTQFVRFDSD APNPRMEPRA PWIEQERQEY WDEETRNAMG SAQTFRVNLN
 NLRGYYNQSE AGSHTYQWMY GCDVGPDWLF LRGYSQDAYD GADYIALNED
 LRSWTAADTA AQITKRKREA ADAAEQMRSY LEGACVEWLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWAMGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWDPPQP
 PVPIVGIIVG LVLVLVAGAV VAGVVIWRKK RPGEKGGSYT QAAGSDSAQG
 SDVSLTKDPR VX*

>P1;SLA-3_0701
SLA-3_0701, 365 bases, 330429FB checksum.
 MGPRALFLLL SGTLALTGTR EGPHSLRYFD TAVSRPDRGK PRFISVGYVD
 DTQFVRFDSD APNPRMEPRA PWIKQEGQEW QEYWDEETRN AMGSAQTFRV
 NLNNLRGYYN QSEAGSHTLQ SMYGCDVGPD WLFLRGYSQD AYDGADYIAL
 NEDLRSWTAA DTAAQITKRK REAADAAEQM RSYLEGACVE WLQKYLQMGN
 NTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPIVGI IVGLVLVLVA GAVVAGVVIW RKKRPGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-3_0701sm19
SLA-3_0701sm19, 365 bases, 330429FB checksum.
 MGPRALFLLL SGTLALTGTR EGPHSLRYFD TAVSRPDRGK PRFISVGYVD
 DTQFVRFDSD APNPRMEPRA PWIKQEGQEW QEYWDEETRN AMGSAQTFRV
 NLNNLRGYYN QSEAGSHTLQ SMYGCDVGPD WLFLRGYSQD AYDGADYIAL
 NEDLRSWTAA DTAAQITKRK REAADAAEQM RSYLEGACVE WLQKYLQMGN
 NTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPIVGI IVGLVLVLVA GAVVAGVVIW RKKRPGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-3_07Lw02
SLA-3_07Lw02, 365 bases, B440ED55 checksum.
 MGPRALFLLL SGTLALTGTR EGPHSLRYFD TAVSRPDRGK PRFISVGYVD
 DTQFVRFDSD APNPRMEPRA PWIKQEGQEW QEYWDEETRN AMGSAQTFRV
 NLNNLRGYYN QSEAGSHTLQ SMYGCDVGPD WLFLRGYSQD AYDGADYIAL
 NEDLRSWTAA DTAAQITKRK REAADAAEQM RSYLEGACVE WLQKYLQMGN
 NTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPIVGI IVGLVLVLVA GAMVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTQ DPRVX*

>P1;SLA-3_07rh34
SLA-3_07rh34, 222 bases, DFC814E7 checksum.
 YVDDTQFVRF DSDAPNPRME PRAPWIKQEG QEWQEYWDEE TRNAMGSAQT
 FRVNLNNLRG YYNQSEAGSL TLQSMYGCDV GPDWLFLRGY SQDAYDGADY
 IALNEDLRSW TAADTAAQIT KRKREAADVA EQMRSYLEGA CVEWLQKYLQ
 MGNNTLQRAE PPKTHVTRHP SSDLGVTLRC WALGFYPKEI SLTWQREGQD
 QSQDMELVET RPSGDGTFQK WA*

>P1;SLA-3_hm22
SLA-3_hm22, 175 bases, 5BB8CBCA checksum.
 LSGTLALTGT QAGPHSLRYF HTAVSRPDLG KPRFIAVGYV DDTQFVRFDS
 DAPNPRMESR VPWIQQEGQE YWDEETRKQR DTSQTFRVSL NTLRGYYNQS
 EAGSHTIQVM YGCYLGPDGL LLHGYHQYAY DGADYLALNE DLRSWTAADT
 AAQITKRKWE AADVTERRRS YLEGA*

