>DL;SLA-3_0101
SLA-3_0101, 1086 bases, F688628D checksum.
 ATGGGGCCCC GAGCCCTCTT CTTGCTGCTG TCGGGGACCC TGGCCCTGAC
 TGGTACCCGG GAGGGTCCCC ACTCCCTGAG GTATTTCGAC ACCGCCGTGT
 CCCGGCCCGA CCGCGGGAAG CCCCGTTTCA TCTCCGTCGG CTACGTGGAC
 GACACGCAGT TCGTGCGGTT CGACAGCGAC GCCCCGAATC CGCGGATGGA
 GCCGCGGGCG CCGTGGATAG AGCAGGAGGG GCAGGAGTAT TGGGATGAGG
 AGACGCGGAA CGCCATGGGC AGCGCACAGA CTTTCCGAGT GAACCTGAAC
 AACCTGCGCG GCTACTACAA CCAGAGCGAG GCCGGGTCTC ACACCTTCCA
 GAGCATGTAC GGCTGCGACG TGGGGCCAGA CGGGCTCCTC CTCCGCGGGT
 ACAGTCAGTT TGGCTACGAC GGCGCCGATT ACATCGCCCT GAACGAGGAC
 CTGCGCTCCT GGACCGCGGC GGACACGGCG GCTCAGATCA CCAAGCGCAA
 GAGGGAGGCG GCCGATGCGG CGGAGCAAAT GAGAAGCTAC CTGGAGGGCG
 CGTGTGTGGT GTGGCTCCAG AAATACCTGG AGATGGGGAA TAACACGCTG
 CAGCGCGCAG AGCCTCCAAA GACACATGTG ACCCGCCACC CCAGCTCTGA
 CCTGGGGGTC ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTAAGGAGA
 TCTCCCTGAC CTGGCAGCGC GAGGGCCAGG ACCAGAGCCA AGACATGGAG
 CTGGTGGAGA CCAGGCCCTC AGGGGATGGG ACCTTCCAGA AGTGGGCGGC
 CCTGGTGGTG CCTCCTGGAG AGGAGCAGAG CTACACCTGC CATGTGCAGC
 ACGAGGGCCT GCAGGAGCCC CTCACCCTGA GATGGGACCC TCCTCAGCCC
 CCCGTCCCCA TCGTGGGCAT CACTGTTGGC CTGGTTCTCG TCCTGGTTGC
 TGGAGCCGTG GTGGCTGGAG TTGTGATCTG GAGGAAGAAG CGCTCAGGTG
 AAAAAGGAGG GAGCTACACT CAGGCTGCAG GCAGTGACAG TGCCCAGGGC
 TCTGATGTGT CCCTCACCAA GGATCCTAGA GTGTGA*

>DL;SLA-3_01ev04
SLA-3_01ev04, 885 bases, 5E4F342A checksum.
 ATGGGGCCTG GAGCCCTCTT CTTGCTGCTG TCGGGGACCC TGGCCCTGAC
 TGGTACCCGG GAGGGTCCCC ACTCCCTGAG GTATTTCGAC ACCGCCGTGT
 CCCGGCCCGA CCGCGGGAAG CCCCGTTTCA TCTCCGTCGG CTACGTGGAC
 GACACGCAGT TCGTGCGGTT CGACAGCGAC GCCCCGAATC CGCGGATGGA
 GCCGCGGGCG CCGTGGATAG AGCAGGAGGG GCAGGAGTAT TGGGATGAGG
 AGACGCGGAA CGCCATGGGC AGCGCACAGA CTTTCCGAGT GAACCTGAAC
 AACCTGCGCG GCTACTACAA CCAGAGCGAG GCCGGGTCTC ACACCTTCCA
 GAGCATGTAC GGCTGCGACG TGGGGCCAGA CGGGCTCCTC CTCCGCGGGT
 ACAGTCAGTT TGGCTACGAC GGCGCCGATT ACATCGCCCT GAACGAGGAC
 CTGCGCTCCT GGACCGCGGC GGACACGGCG GCTCAGATCA CCAAGCGCAA
 GAGGGAGGCG GCCGATGCGG CGGAGCAAAT GAGAAGCTAC CTGGAGGGCG
 CGTGTGTGGT GTGGCTCCAG AAATACCTGG AGATGGGGAG TAACACGCTG
 CAGCGCGCAG AGCCTCCAAA GACACATGTG ACCCGCCACC CCAGCTCTGA
 CCTGGGGGTC ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTAAGGAGA
 TCTCCCTGAC CTGGCAGCGC GAGGGCCAGG ACCAGAGCCA AGACATGGAG
 CTGGTGGAGA CCAGGCCCTC AGGGGATGGG ACCTTCCAGA AGTGGGCGGC
 CCTGGTGGTG CCTCCTGGAG AGGAGCAGAG CTACACCTGC CATGTGCAGC
 ACGAGGGCCT GCAGGAGCCC CTCACCCTGA GATGG*

>DL;SLA-3_01rh12
SLA-3_01rh12, 659 bases, AA36323 checksum.
 GCTACGTGGA CGACACGCAG TTCGTGCGGT TCGACAGCGA CGCCCCGAAT
 CCGCGGATGG AGCCGCGGGC GCCGTGGATA GAGCAGGAGG GGCAGGAGTA
 TTGGGATGAG GAGACGCGGA ACGCCATGGG CAGCGCACAG ACTTTCCGAG
 TGAACCTGAA CAACCTGCGC GGCTACTACA ACCAGAGCGA GGCCGGGTCT
 CACACCTTCC AGAGCATGTA CGGCTGCGAC GTGGGGCCAG ACGGGCTCCT
 CCTCCGCGGG TACAGTCAGT TTGGCTACGA CGGCGCCGAT TACATCGCCC
 TGAACGAGGA CCTGCGCTCC TGGACCGCGG CGGACACGGC GGCTCAGATC
 ACCAAGCGCA AGAGGGAGGC GGCCGATGTG GCGGAGCAAA TGAGAAGCTA
 CCTGGAGGGC GCGTGTGTGG AGTGGCTCCA GAAATACCTG CAGATGGGGA
 ATAACACGCT GCAGCGCGCA GAGCCTCCAA AGACACATGT GACCCGCCAC
 CCCAGCTCTG ACCTGGGGGT CACCCTGAGG TGCTGGGCCC TGGGCTTCTA
 CCCTAAGGAG ATCTCCCTGA CCTGGCAGCG CGAGGGCCAG GACCAGAGCC
 AAGACATGGA GCTGGTGGAG ACCAGGCCCT CAGGGGATGG GACCTTCCAG
 AAGTGGGCG*

>DL;SLA-3_01rh28
SLA-3_01rh28, 659 bases, E550A5B4 checksum.
 GCTACGTGGA CGACACGCAG TTCGTGCGGT TCGACAGCGA CGCCCCGAAT
 CCGCGGATGG AGCCGCGGGC GCCGTGGATA GAGCAGGAGG GGCAGGAGTA
 TTGGGATGAG GAGACGCGGA ACGCCATGGG CGGCGCACAG ACTTTCCGAG
 TGAACCTGAA CAACCTGCGC GGCTACTACA ACCAGAGCGA GGCCGGGTCT
 CACACCTTCC AGAGCATGTA CGGCTGCGAC GTGGGGCCAG ACGGGCTCCT
 CCTCCGCGGG TACAGTCAGT TTGGCTACGA CGGCGCCGAT TACATCGCCC
 TGAACGAGGA CCTGCGCTCC TGGACCGCGG CGGACACGGC GGCTCAGATC
 ACCAAGCGCA AGAGGGAGGC GGCCGATGCG GCGGAGCAAA TGAGAAGCTA
 CCTGGAGGGC GCGTGTGTGG TGTGGCTCCA GAAATACCTG GAGATGGGGA
 ATAACACGTT GCAGCGCGCA GAGCCTCCAA AGACACATGT GACCCGCCAC
 CCCAGCTCTG ACCTGGGGGT CACCCTGAGG TGCTGGGCCC TGGGCTTCTA
 CCCTAAGGAG ATCTCCCTGA CCTGGCAGCG CGAGGGCCAG GACCAGAGCC
 AAGACATGGA GCTGGTGGAG ACCAGGCCCT CAGGGGATGG GACCTTCCAG
 AAGTGGGCG*

>DL;SLA-3_0301
SLA-3_0301, 1086 bases, 1D291D63 checksum.
 ATGGGGCCCC GAGCCCTCTT CTTGCTGCTG TCGGGGACCC TGGCCCTGAC
 TGGTACCCGG GAGGGTCCCC ACTCCCTGAG GTATTTCGAC ACCGCCGTGT
 CCCGGCCCGA CCGCAGGAAG CCCCGTTTCA TCTCCGTCGG CTACGTGGAC
 GACACGCAGT TCGTGCGGTT CGACAGCGAC GCCCCCAATC CGCGGATGGA
 GCCGCGGGCG CCGTGGATAC AGCAGGAGGG GCAGAAGTAT TGGGATGAGG
 AGACGCAGAA CGCCATGGGC AGCGCACAGA CTTTCCGAGT GAACCTGAAG
 AACCTGCGCG GCTACTACAA CCAGAGCGAG GCCGGGTCTC ACACCCTCCA
 GAGCATGTAC GGCTGCGACG TGGGACCAGA CGGGCTCTTC CTCCGCGGGT
 ACCATCAGGA CGCCTACGAC GGCGCCGATT ACATCGCCCT GAACGAGGAC
 CTGCGCTCCT GGACCGCGGC GGACACGGCG GCTCAGATCG CCAAGCGCAA
 GTGGGAGGCG GCCGATGTGG CTGAGCAGTG GAGGAGCTAC CTGGAGGGCG
 CGTGTGTGGA GTGGCTCCAG AAATACCTGG AGATGGGAAA TAACACGCTG
 CAGCGCGCAG AGCCTCCAAA GACACATGTG ACCCGCCACC CCAGCTCTGA
 CCTGGGGGTC ACCTTGAGGT GCTGGGCCCT GGGCTTCTAC CCTAAGGAGA
 TCTCCCTGAC CTGGCAGCGG GAGGGGCAGG ACCAGAGCCA GGACATGGAG
 CTGGTGGAGA CCAGGCCCTC AGGGGATGGG ACCTTCCAGA AGTGGGCGGC
 CCTGGTGGTG CCTCCTGGAG AGGAGCAGAG CTACACCTGC CATGTGCAGC
 ACGAGGGCCT GCAGGAGCCC CTCACCCTGA GATGGGACCC TCCTCAGCCC
 CCCGTCCCCA TCGTGGGCAT CATTGTTGGC CTGGTTCTCG TCCTGGTCAC
 TGGAGCCGTG GTGGCTGGAG TTGTGATCTG GAGGAAGAAG CGCTCAGGTG
 AAAAAGGAGG GAGCTACACT CAGGCTGCAG GCAGTGACAG TGCCCAGGGC
 TCTGATGTGT ACCTCATCAA GGATCCTAGA GTGTGA*

>DL;SLA-3_0302
SLA-3_0302, 1086 bases, 8ED090BD checksum.
 ATGGGGCCCC GAGCCCTCTT CTTGCTGCTG TCGGGGACCC TGGCCCTGAC
 TGGTACCCGG GAGGGTCCCC ACTCCCTGAG GTATTTCGAC ACCGCCGTGT
 CCCGGCCCGA CCGCGGGAAG CCCCGTTTCA TCTCCGTCGG CTACGTGGAC
 GACACGCAGT TCGTGCGGTT CGACAGCGAC GCCCCCAATC CGCGGATGGA
 GCCGCGGGCG CAGTGGATAC AGCAGGAGGG GCAGGACTAT TGGGATCGGG
 AGACGCAGAA CAGCAAGGAC AACGCACAGA GATACCGAGT GAACCTGAAG
 AACCTGCGCG GCTACTACAA CCAGAGCGAG GCCGGGTCTC ACACCATCCA
 GAGAATGTAC GGCTGCGACG TGGGACCAGA CGGGCTCTTC CTCCACGGGT
 ACCATCAGGA CGCCTACGAC GGCGCCGATT ACCTCGCCCT GAACGAGGAC
 CTGCGCTCCT GGACCGCGGC GGACACGGCG GCTCAGATCT CCAAGCGCAA
 GTGGGAGGCG GCCGATGCGG CGGAGCAGTG GAGGAGCTAC CTGGAGGGCG
 CGTGTGTGGA GGGGCTCCAG AAATACCTGG ATTTGGGGAA GGACACGCTG
 CAGCGCGCAG AGCCTCCAAA GACACATGTG ACCCGCCACC CCAGCTCTGA
 CCTGGGGGTC ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTAAGGAGA
 TCTCCCTGAC CTGGCAGCGC GAGGGCCAGG ACCAGAGCCA GGACATGGAG
 CTGGTGGAGA CCAGGCCCTC AGGGGATGGG ACCTTCCAGA AGTGGGCGGC
 CCTGGTGGTG CCTCCTGGAG AGGAGCAGAG CTACACCTGC CATGTGCAGC
 ACGAGGGCCT GCAGGAGTCC CTCACCCTGA GATGGGACCC TCCTCAGCAC
 CCCGTACCCA TCATGGGCAT CATTGTTGGC CTGGTTCTTG TCCTGGTCGC
 TGGAGCTGTG GTGGCTGGAG TTGTGATCTG GAGGAAGAAG CGCTCAGGTG
 AAAAAGGAGG GAGCTACACT CAGGCTGCAG GCAGTGACAG TGCCCAGGGC
 TCCGATGTGT ACCTCATCAA GGATCCTAGA GTGTGA*

>DL;SLA-3_0303
SLA-3_0303, 1086 bases, EC7B6ABF checksum.
 ATGGGGCCCC GAGCCCTCTT CTTGCTGCTG TCGGGGACCC TGGCCCTGAC
 TGGTACCCGG GAGGGTCCCC ACTCCCTGAG GTATTTCGAC ACCGCCGTGT
 CCCGGCCCGA CCGCGGGAAG CCCCGTTTCA TCTCCGTCGG CTACGTGGAC
 GACACGCAGT TCGTGCGGTT CGACAGCGAC GCCCCCAATC CGCGGATGGA
 GCCTCGGGTG CCGTGGATAG AGAAGGAGGG GCAGGAGTAT TGGGATGAGG
 AGACGCAGAA CGCCATGGGC AGCGCACAGA CTTTCCGAGT GAACCTGAAG
 AACCTGCGCG GCTACTACAA CCAGAGCGAG GCCGGGTCTC ACACCCTCCA
 GAGCATGTAC GGCTGCGACG TGGGACCAGA CGGGCTCTTC CTCCACGGGT
 ACCATCAGGA CGCCTACGAC GGCGCCGATT ACATCGCCCT GAACGAGGAC
 CTGCGCTCCT GGACCGCGGC GGACACGGCG GCTCAGATCG CCAAGCGCAA
 GTGGGAGGCG GCCGATGTGG CTGAGCAGTG GAGGAGCTAC CTGGAGGGCG
 CGTGTGTGGA GTGGCTCCAG AAATACCTGG AGATGGGAAA TAACACGCTG
 CAGCGCGCAG AGCCTCCAAA GACACATGTG ACCCGCCACC CCAGCTCTGA
 CCTGGGGGTC ACCTTGAGGT GCTGGGCCCT GGGCTTCTAC CCTAAGGAGA
 TCTCCCTGAC CTGGCAGCGC GAGGGCCAGG ACCAGAGCCA GGACATGGAG
 CTGGTGGAGA CCAGGCCCTC AGGGGATGGG ACCTTCCAGA AGTGGGCGGC
 CCTGGTGGTG CCTCCTGGAG AGGAGCAGAG CTACACCTGC CATGTGCAGC
 ACGAGGGCCT GCAGGAGCCC CTCACCCTGA GATGGGACCC TCCTCAGCCC
 CCCGTCCCCA TCGTGGGCAT CATTGTTGGC CTGGTTCTGG TCCTGGTCGC
 TGGAGCCGTG GTGGCTGGAG TTGTGATCTG GAGGAAGAAG CGCTCAGGTG
 AAAAAGGAGG GAGCTACACT CAGGCTGCAG GCAGTGACAG TGCCCAGGGC
 TCTGATGTGT ACCTCATCAA GGATCCTAGA GTGTGA*

>DL;SLA-3_0304
SLA-3_0304, 1086 bases, 52D88531 checksum.
 ATGGGGCCTG GAGCCCTCTT CTTGCTGCTG TCGGGGACCC TGGCCCTGAC
 TGGTACCCGG GAGGGTCCCC ACTCCCTGAG GTATTTCGAC ACCGCCGTGT
 CCCGGCCCGA CCGCGGGAAG CCCCGTTTCA TCTCCGTCGG CTACGTGGAC
 GACACGCAGT TCGTGCGGTT CGACAGCGAC GCCCCCAATC CGCGGATGGA
 GCCGCGGGCG CCGTGGATAG AGAAGGCGGA GCAGAAGTAT TGGGATGAGG
 AGACGCAGAA CGCCATGGGC AGCGCACAGA CTTTCCGAGT GAACCTGAAG
 AACCTGCGCG GCTACTACAA CCAGAGCGAG GCCGGGTCTC ACACCCTCCA
 GAGCATGTAT GGCTGCGACG TGGGACCAGA CGGGCTCTTC CTCCACGGGT
 ACCATCAGGA CGCCTACGAC GGCGCCGATT ACATCGCCCT GAACGAGGAC
 CTGCGCTCCT GGACCGCGGC GGACACGGCG GCTCAGATCG CCAAGCGCAA
 GTGGGAGGCG GCCGATGCGG CGGAGCAGTG GAGGAGCTAC CTGGAGGGCG
 CGTGTGTGGA GTGGCTCCAG AAATACCTGG AGATGGGAAA TAACACGCTG
 CAGCGCGCAG AGCCTCCAAA GACACATGTG ACCCGCCACC CCAGCTCTGA
 CCTCGGGGTC ACCTTGAGGT GCTGGGCCCT GGGCTTCTAC CCTAAGGAGA
 TCTCCCTGAC CTGGCAGCGG GAGAGCCAGG ACCAGAGCCA GGACATGGAG
 CTGGTGGAGA CCAGGCCCTC AGGGGATGGG ACCTTCCAGA AGTGGGCGGC
 CCTGGTGGTG CCTCCTGGAG AGGAGCAGAG CTACACCTGC CATGTGCAGC
 ACGAGGGCCT GCAGGAGCCC CTCACCCTGA GATGGGACCC TGCTCAGCCC
 CCCGTCCCCA TCGTGGGCAT CATTGTTGGC CTGGTTCTGG TCCTGGTCGC
 TGGAGCCATG GTGGCTGGAG TTGTGATCTG GAGGAAGACG CGCTCAGGTG
 AAAAAGGAGG GAGCTACACT CAGGCTGCAG GCAGTGACAG TGACCAGGGC
 TCCGATGTGT CCCTTACCAA GGATCCTAGA GTGTGA*

>DL;SLA-3_03an02
SLA-3_03an02, 495 bases, 7DD2962 checksum.
 ACCCGGGAGG GTCCCCACTC CCTGAGGTAT TTCGACACCG CCGTGTCCCG
 GCCCGACCGC GGGAAGCCCC GTTTCATCTC CGTCGGCTAC GTGGACGACA
 CGCAGTTCGT GCGGTTCGAC AGCGACGCCC CCAATCCGCG GATGGAGCCG
 CGGGCGCAGT GGATACAGCA GAAGGGGCAG GAGTATTGGG ATCGGGAGAC
 ACAGATCAGC AAGGACAACG CACAGAGATA CCGAGTGAAC CTGAAGAACC
 TGCGCGGCTA CTACAACCAG AGCGAGGCCG GGTCTCACAC CATCCAGAGC
 ATGTACGGCT GCGACGTGGG ACCAGACGGG CTCTTCCTCC ACGGGTACCA
 TCAGGACGCC TACGACGGCG CCGATTACCT CGCCCTGAAC GAGGACCTGC
 GCTCCTGGAC CGCGGCGGAC ATGGCGGCTC AGATCACCAA GCGCAAGTGG
 GAGGCGGCCG ATGCGGCGGA GCAGTGGAGG AGCTACCTGG AGGGC*

>DL;SLA-3_03an04
SLA-3_03an04, 499 bases, 624DD489 checksum.
 ACCCGGGAGG GTCCCCACTC CCTGAGGTAT TTCGACACCG CCGTGTCCCG
 GCCCGACCGC GGGAAGCCCC GTTTCATCTC CGTCGGCTAC GTGGACGACA
 CGCAGTTCGT GCGGTTCGAC AGCGACGCCC TCAATCCGCG GATGGAGCCG
 CGGGCGCCGT GGATAGAGAA GGCGGAGCAG AAGTATTGGG ATGAGGAGAC
 GCAGAACGCC ATGGGCAGCG CACAGACTTT CCGAGTGAAC CTGAAGAACC
 TGCGCGGCTA CTACAACCAG AGCGAGGCCG GGTCTCACAC CCTCCAGAGC
 ATGTATGGCT GCGACGTGGG ACCAGACGGG CTCTTCCTCC ACGGGTACCA
 TCAGGACGCC TACGACGGCG CCGATTACAT CGCCCTGAAC GAGGACCTGC
 GCTCCTGGAC CGCGGCGGAC ACGGCGGCTC AGATCGCCAA GCGCAAGTGG
 GAGGCGGCCG ATGTGGCGGA GCAGTGGAGG AGCTACCTGG AGGGCGCGT*

>DL;SLA-3_03an05
SLA-3_03an05, 537 bases, 780AA1EC checksum.
 GCTGTCGGGA ACCCTGGCCC TGACTGGTAC CCGGGAGGGT CCCCACTCCC
 TGAGGTATTT CGACACCGCC GTGTCCCGGC CCGACCGCGG GAAGCCCCGT
 TTCATCTCCG TCGGCTACGT GGACGACACG CAGTTCGTGC GGTTCGACAG
 CGACGCCCCC AATCCGCGGA TGGAGCCGCG GGCGCCGTGG ATAGAGAAGG
 ACGAGCAGAA GTATTGGGAT GAGGAGACGC AGAACGCCAT GGGCAGCGCA
 CAGACTTTCC GAGTGAACCT GAAGAACCTG CGCGGCTACT ACAACCAGAG
 CGAGGCCGGG TCTCACACCC TCCAGAGCAT GTATGGCTGC GACGTGGGAC
 CAGACGGGCT CTTCCTCCAC GGGTACCATC AGGACGCCTA CGACGGCGCC
 GATTACATCG CCCTGAACGA GGACCTGCGC TCCTGGACCG CGGCGGACAC
 GGCGGCTCAG ATCGCCAAGC GCAAGTGGGA GGCGGCCGAT GCGGCTGAGC
 AGTGGAGGAG CTACCTGGAG GGCGCGTGTG TGGTGTG*

>DL;SLA-3_03pt31
SLA-3_03pt31, 1086 bases, DB74939F checksum.
 ATGGGGCCCC GAGCCCTCTT CTTGCTGCTG TCGGGGACCC TGGCCCTGAC
 TGGTACCCGG GAGGGTCCCC ACTCCCTGAG GTATTTCGAC ACCGCCGTGT
 CCCGGCCCGA CCGCGGGAAG CCCCGTTTCA TCTCCGTCGG CTACGTGGAC
 GACACGCAGT TCGTGCGGTT CGACAGCTAC GCCCCGAATC CGCGGATGGA
 GCCGCGGGCG CAGTGGATAC AGCAGGAGGG GCAGGAGTAT TGGGATCGGG
 AGACACAGAT CAGCAAGGAC AACGCACAGA GATACCGAGT GAACCTGAAC
 ACCCTGCGCG GCTACTACAA CCAGAGCGAG GCCGGGTCTC ACACCATCCA
 GACCATGTAC GGCTGCGACG TGGGACCAGA CGGCCTCTTC CTCCACGGGT
 ACCATCAGTA CGCCTACGAC GGCGCCGATT ACCTCGCCCT GAACGAGGAC
 CTGCGCTCCT GGACCGCGGC GGACACGGCG GCTCAGATCT CCAAGCGCAA
 GAGGGAGGCG GCCGATGCGG CGGAGCAGTG GAGGAGCTAC CTGGAGGGCG
 CGTGTGTGGA GTGGCTCCAG AAATACCTGG AGATGGGGGA GGACACGCTG
 CAGCGCGCAG AGCCTCCAAA GACACATGTG ACCCGCCACC CCAGCTCTGA
 CCTCGGGGTC ACCTTGAGGT GCTGGGCCCT GGGCTTCTAC CCTAAGGAGA
 TCTCCCTGAC CTGGCAGCGG GAGGGCCAGG ACCAGAGCCA GGACATGGAG
 CTGGTGGAGA CCAGGCCCTC AGGGGATGGG ACCTTCCAGA AGTGGGCGGC
 CCTGGTGGTG CCTCCTGGAG AGGAGCAGAG CTACACCTGC CATGTGCAGC
 ACGAGGGCCT GCAGGAGCCC CTCACCCTGA GATGGGACCC TCCTCAGCAC
 CCCGTACCCA TCATGGGCAT CATTGTTGGC CTGGTTCTTG TCCTGGTCGC
 TGGAGCTGTG GTGGCTGGAG TTGTGATCTG GAGGAAGAAG CGCTCAGGTG
 AAAAAGGAGG GAGCTACACT CAGGCTGCAG GCAGTGACAG TTCCCAGGGC
 TCCGATGTGT ACCTCATCAA GGATCCTAGA GTGTGA*

>DL;SLA-3_0401
SLA-3_0401, 1086 bases, 8926F9CB checksum.
 ATGGGGCCCC GAGCCCTCTT CCTGCTGCTC TCGGGGGCCC TGGCCCTGAC
 TGGGACCCGG GCGGGTCCCC ACTCCCTGAG GTATTTCGAC ACCGCCGTGT
 CCCGGCCCGA CCGCGGGAAG CCCCGTTTCA TCGAAGTCGG CTACGTGGAC
 GACACGCAGT TCGTGCGGTT CGACAGCGAC GCCCCCAATC CGCGGATGGA
 GCCTCGGGTG CCGTGGATAG AGAAGGAGGG GCAGGAGTAT TGGGATAAGG
 AGACGGAGAA CGCCATGGGC AGCGCACAGA CTTTCCGAGT GAACCTGAAA
 AACCTGCGCG GCTACTACAA CCAGAGCGAG GCCGGGTCTC ACACCCTCCA
 GAGCATGTAC GGCTGCGACG TGGGACCAGA CGGGCTCCTC CTCCGCGGGT
 ACAGTCAGGA CGCCTACGAC GGCGCCGATT ACATCGCCCT GAACGAGGAC
 CTGCGCTCCT GGACCGCGGC GGACACGGCG GCTCAGATCA CCAAGCGCAA
 GAGGGAGGCG GCCGATGCGG CGGAGCAAAT GAGAAGCTAC CTGGAGGGCG
 CGTGTGTGGA GTGGCTCCAG AAATACCTGC AGATGGGGAA GGACACGCTG
 CAGCACGCAG AGCCTCCAAA GACACATGTG ACCCGCCACC CCAGCTCTGA
 CCTCGGGGTC ACCTTGAGGT GCTGGGCCCT GGGCTTCTAC CCTAAGGAGA
 TCTCCCTGAC CTGGCAGCGC GAGGGCCAGG ACCAGAGCCA GGACATGGAG
 CTGGTGGAGA CCAGGCCCTC AGGGGATGGG ACCTTCCAGA AGTGGGCGGC
 CCTGGTGGTG CCTCCTGGAG AGGAGCAGAG CTACACCTGC CATGTGCAGC
 ACGAGGGCCT GCAGGAGCCC CTCACCCTGA GATGGGACCC TCCTCAGCCC
 CCCGTCCCCA TCGTGGGCAT CATTGTTGGC CTGGTTCTCG TCCTGGTCGC
 TGGAGCCGTG GTGACTGGAG TTGTGATCTG GAGGAAGAAG CGCTCAGGTG
 AAAAAGGAGG GAGCTACACT CAGGCTGCAG GCAGTGACAG TGCCCAGGGC
 TCCGATGTGT CCCTTACCAA GGATCCTAGA GTGTGA*

>DL;SLA-3_0402
SLA-3_0402, 1083 bases, 12EAD34F checksum.
 ATGGGGCCCC GAGCCCTCGT TCTGCTGCTC TCGGGGGCCC TGGCCCTGAC
 TGGGACCCGG GCGGGTCCCC ACTCCCTGAG ATATTTCGAC ACCGCCCTGT
 CCCGGCCCGA CCGCGGGAAG CCCCGTTTCA TCGAAGTCGG CTACGTGGAC
 GACACGCAGT TCGTGCGGTT CGACAGCGAC GCCCCCAATC CGCGGATGGA
 GCCGCGGGCG CCGTGGATAG AGAAGGCGGA GCAGAAGTAT TGGGATGAGG
 AGACGCAGAA CGCCATGGGC AGCGCACAGA CTTTCCGAGT GAACCTGAAA
 AAGCTGCGCG GCTACTACAA CCAGAGCGAG GCCGGGTCTC ACACCCTCCA
 GAGCATGTAC GGCTGCGACG TGGGACCAGA CGGGCTCCTC CTCCGCGGGT
 ACAGTCAGGA CGCCTACGAC GGCGCCGATT ACATCGCCCT GAACGAGGAC
 CTGCGCTCCT GGACCGCGGC GGACACGGCG GCTCAGATCA CCAAGCGCAA
 GAGGGAGGCC GATGCGGCGG AGCAAATGAG AAGCTACCTG GAGGGCGCGT
 GTGTGGAGTG GCTCCAGAAA TACCTGGAGA TGGGGAAGGA CACGCTGCAG
 CGCGCAGAGC CTCCAAAGAC ACATGTGACC CGCCACCCCA GCTCTGACCT
 GGGGGTCACC CTGAGGTGCT GGGCCCTGGG CTTCTACCCT AAGGAGATCT
 CCCTGACCTG GCAGCGGGAG GGCCAGGACC AGAGCCAGGA CATGGAGCTG
 GTGGAGACCA GGCCCTCAGG GGATGGGACC TTCCAGAAGT GGGCGGCCCT
 GGTGGTGCCT CCTGGAGAGG AGCAGAGCTA CACCTGCCAT GTGCAGCACG
 AGGGCCTGCA GGAGCCCCTC ACCCTGAGAT GGGACCCTCC TCAGCCCCCC
 GTCCCCATCG TGGGCATCAT TGTTGGCCTG GTTCTCGTCC TGGTCGCTGG
 AGCCATGGTG ACTGGAGTTG TGATCTGGAG GAAGAAGCGC TCAGGTGAAA
 AAGGAGGGAG CTACACTCAG GCTGCAGGCA GTGACAGTGC CCAGGGCTCC
 GATGTGTCCC TTACCAAGGA TCCTAGAGTG TGA*

>DL;SLA-3_04es32
SLA-3_04es32, 1095 bases, B8E9A452 checksum.
 ATGGGGCCCC GAGCCCTCGT TCTGCTGCTC TCGGGGGCCC TGGCCCTGAC
 TGGGACCCGG GCGGGTCCCC ACTCCCTGAG ATATTTCGAC ACCGCCCTGT
 CCCGGCCCGA CCGCGGGAAG CCCCGTTTCA TCGAAGTCGG CTACGTGGAC
 GACACGCAGT TCGTGCGGTT CGACAGCGAC GCCCCCAATC CGCGGATGGA
 GCCGCGGGCG CCGTGGATAG AGAAGGCGGA GCAGAAGTAT TGGGATGAGG
 AGACGCAGAA CGCCATGGGC AGCGCACAGA CTTTCCGAGT GAACCTGAAA
 AAGCTGCGCG GCTACTACAA CCAGAGCGAG GCCGGGTCTC ACACCCTCCA
 GAGCATGTAC GGCTGCGACG TGGGACCAGA CGGGCTCCTC CTCCGCGGGT
 ACAGTCAGGA CGCCTACGAC GGCGCCGATT ACATCGCCCT GAACGAGGAC
 CTGCGCTCCT GGACCGCGGC GGACACGGCG GCTCAGATCA CCAAGCGCAA
 GAGGGAGGCC GATGCGGCGG AGCAAATGAG AAGCTACCTG GAGGGCGCGT
 GTGTGGAGTG GCTCCAGAAA TACCTGGAGA TGGGGAAGGA CACGCTGCAG
 CGCGCAGAGC CTCCAAAGAC ACATGTGACC CGCCACCCCA GCTCTGACCT
 GGGGGTCACC CTGAGGTGCT GGGCCCTGGG CTTCTACCCT AAGGAGATCT
 CCCTGACCTG GCAGCGGGAG GGCCAGGACC AGGGCCAGGA CCAGAGCCAG
 TACATGGAGC TGGTGGAGAC CAGGCCCTCA GGGGATGGGA CCTTCCAGAA
 GTGGGCGGCC CTGGTGGTGC CTCCTGGAGA GGAGCAGAGC TACACCTGCC
 ATGTGCAGCA CGAGGGCCTG CAGGAGCCCC TCACCCTGAG ATGGGACCCT
 CCTCAGCCCC CCGTCCCCAT CGTGGGCATC ATTGTTGGCC TGGTTCTCGT
 CCTGGTCGCT GGAGCCATGG TGACTGGAGT TGTGATCTGG AGGAAGAAGC
 GCTCAGGTGA AAAAGGAGGG AGCTACACTC AGGCTGCAGG CAGTGACAGT
 GCCCAGGGCT CCGATGTGTC CCTTACCAAG GATCCTAGAG TGTGA*

>DL;SLA-3_0501
SLA-3_0501, 1089 bases, 385EA7C2 checksum.
 ATGGGGCCCC GAGCCCTCGT CCTGCTGCTG TCGGGGACCC TGGCCCTGAC
 TGGGACCCGG GCGGGTCCCC ACTCCCTGAG GTATTTCGAC ACCGCCGTGT
 CCCGGCCCGA CCGCGGGAAG CCCCGTTTCA TCGAAGTCGG CTACGTGGAC
 GACACGCAGT TCGTGTGGTT CGACAGCGAC GCCCCGAATC CGCGGATGGA
 GCCGCGGGCG CCGTGGATAG AGCAGGAGGG GCAGGAGTAT TGGGATCGGG
 AGACACAGAT CAGCAAGGAC AACGCACAGA CTTACCGAGT GAACCTGAAC
 AACCTGCGCG GCTACTACAA CCAGAGCGAG GCCGGGTCTC ACACCCTCCA
 GAGCATGTAC GGCTGCGACG TGGGACCAGA CGGGCTCTTC CTCCGCGGGT
 ACAGTCAGTT CGCCTACGAC GGCGCGGATT ACATCGCCCT GAACGAGGAC
 CTGCGCTCCT GGACCGCGGC GGACACGGCG GCTCAGATCA CCAAGCGCAA
 GAGGGAGGCG GCCGATGCGG CGGAGCAAAT GAGAAGCTAC CTGGAGGGCG
 CCTGTGTGGA GGGGCTCCAG AAATACCTGG AGATGGGGAA GGACACGCTG
 CAGCGCGCAG AGCCTCCAAA GACACATGTG ACCCGCCACC CCAGCTCTGA
 CCTCGGGGTC ACCTTGAGGT GCTGGGCCCT GGGCTTCTAC CCTAAGGAGA
 TCTCCCTGAC CTGGCAGCGC GAGGGCCAGG ACCAGAGCCA GGACATGGAG
 CTGGTGGAGA CCAGGCCCTC AGGGGATGGG ACCTTCCAGA AGTGGGCGGC
 CCTGGTGGTG CCTCCTGGAG AGGAGCAGAG CTACACCTGC CATGTGCAGC
 ACGAGGGCCT GCAGGAGCCC CTCACCCTGA GATGGGACCC TGCTCAGCCC
 CCCGTCCCCA TCGTGGGCAT CATTGTTGGC CTGGTTCTCG TTGTCCTGGT
 CGCTGGAGCC ATGGTGGCTG GAGTTGTGAT CTGGAGGAAG AAGCGCTCAG
 GTGAAAAAGG AGGGAGCTAC ACTCAGGCTG CAGGCAGTGA CAGTGCCCAG
 GGCTCTGATG TGTCCCTCAC CCAGGATCCT AGAGTGTGA*

>DL;SLA-3_0502
SLA-3_0502, 1086 bases, 6A412F8B checksum.
 ATGGGGCCCC GAGCCCTCGT CCTGCTGCTG TCGGGGACCC TGGCCCTGAC
 TGGGACCCGG GCGGGTCCCC ACTCCCTGAG GTATTTCGAC ACCGCCGTGT
 CCCGGCCCGA CCGCGGGAAG CCCCGTTTCA TCGAAGTCGG CTACGTGGAC
 GACACGCAGT TCGTGTGGTT CGACAGCGAC GCCCCGAATC CGCGGATGGA
 GCCGCGGGCG CCGTGGATAC AGCAGGAGGG TCAGGAGTAT TGGGATCGGG
 AGACACAGAT CAGCAAGGAC AACGCACAGA CTTACCGAGT GAACCTGAAC
 AACCTGCGCG GCTACTACAA CCAGAGCGAG GCCGGGTCTC ACACCCTCCA
 GAGCATGTAC GGCTGCGACG TGGGACCAGA CGGGCTCTTC CTCCGCGGGT
 ACAGTCAGTT CGCCTACGAC GGCGCGGATT ACATCGCCCT GAACGAGGAC
 CTGCGCTCCT GGACCGCGGC GGACACGGCG GCTCAGATCA CCAAGCGCAA
 GAGGGAGGCG GCCGATGCGG CGGAGCAAAT GAGAAGCTAC CTGGAGGGCG
 CCTGTGTGGA GGGGCTCCAG AAATACCTGG AGATGGGGAA GGACACGCTG
 CAGCGCGCAG AGCCTCCAAA GACACATGTG ACCCGCCACC CCAGCTCTGA
 CCTCGGGGTC ACCTTGAGGT GCTGGGCCCT GGGCTTCTAC CCTAAGGAGA
 TCTCCCTGAG CTGGCAGCGC GAGGGCCAGG ACCAGAGCCA GGACATGGAG
 CTGGTGGAGA CCAGGCCCTC AGGGGATGGG ACCTTCCAGA AGTGGGCGGC
 CCTGGTGGTG CCTCCTGGAG AGGAGCAGAG CTACACCTGC CATGTGCAGC
 ACGAGGGCCT GCAGGAGCCC CTCACCCTGA GATGGGACCC TCCTCAGCCC
 CCCGTCCCCA TCGTGGGCAT CATTGTTGGC CTGGTTCTCG TCCTGGTCGC
 TGGAGCCATG GTGGCTGGAG TTGTGATCTG GAGGAAGAAG CGCTCAGGTG
 AAAAAGGAGG GAGCTACACT CAGGCTGCAG GCAGTGACAG TGCCCAGGGC
 TCTGATGTGT CCCTCACCCA GGATCCTAGA GTGTGA*

>DL;SLA-3_0503
SLA-3_0503, 1086 bases, FE72E850 checksum.
 ATGGGGCCCC GAGCCCTCGT CCTGCTGCTG TCGGGGACCC TGGCCCTGAC
 TGGGACCCGG GCGGGTCCCC ACTCCCTGAG GTATTTCGAC ACCGCCGTGT
 CCCGGCCCGA CCGCGGGAAG CCCCGTTTCA TCGAAGTCGG CTACGTGGAC
 GACACGCAGT TCGTGTGGTT CGACAGCGAC GCCCCGAATC CGCGGATGGA
 GCCGCGGGCG CCGTGGATAG AGAAGGAGGG TCAGGAGTAT TGGGATCGGG
 AGACACAGAT CAGCAAGGAC AACGCACAGA CTTACCGAGT GAACCTGAAC
 AACCTGCGCG GCTACTACAA CCAGAGCGAG GCCGGGTCTC ACACCCTCCA
 GAGCATGTAC GGCTGCGACG TGGGACCAGA CGGGCTCTTC CTCCGCGGGT
 ACAGTCAGTT CGCCTACGAC GGCGCGGATT ACATCGCCCT GAACGAGGAC
 CTGCGCTCCT GGACCGCGGC GGACACGGCG GCTCAGATCA CCAAGCGCAA
 GAGGGAGGCG GCCGATGCGG CGGAGCAAAT GAGAAGCTAC CTGGAGGGCG
 CCTGTGTGGA GGGGCTCCAG AAATACCTGG AGATGGGGAA GGACACGCTG
 CAGCGCGCAG AGCCTCCAAA GACACATGTG ACCCGCCACC CCAGCTCTGA
 CCTGGGGGTC ACCTTGAGGT GCTGGGCCCT GGGCTTCTAC CCTAAGGAGA
 TCTCCCTGAC CTGGCAGCGC GAGGGCCAGG ACCAGAGCCA GGACATGGAG
 CTGGTGGAGA CCAGGCCCTC AGGGGATGGG ACCTTCCAGA AGTGGGCGGC
 CCTGGTGGTG CCTCCTGGAG AGGAGCAGAG CTACACCTGC CATGTGCAGC
 ACGAGGGCCT GCAGGAGCCC CTCACCCTGA GATGGGACCC TGCTCAGCCC
 CCCGTCCCCA TCGTGGGCAT CATTGTTGGC CTGGTTCTCG TCCTGGTCGC
 TGGAGCCATG GTGGCTGGAG TTGTGATCTG GAGGAAGAAG CGCTCAGGTG
 AAAAAGGAGG GAGCTACACT CAGGCTGCAG GCAGTGACAG TGCCCAGGGC
 TCTGATGTGT CCCTCACCCA GGATCCTAGA GTGTGA*

>DL;SLA-3_05sw01
SLA-3_05sw01, 1086 bases, DF796D1A checksum.
 ATGGGGCCCC GAGCCCTCGT CCTGCTGCTG TCGGGGACCC TGGCCCTGAC
 TGGGACCCGG GCGGGTCCCC ACTCCCTGAG GTATTTCGAC ACCGCCGTGT
 CCCGGCCCGA CCGCGGGAAG CCCCGTTTCA TCGAAGTCGG CTACGTGGAC
 GACACGCAGT TCGTGTGGTT CGACAGCGAC GCCCCGAATC CGCGGATGGA
 GCCGCGGGCG CCGTGGATAG AGAAGGAGGG TCAGGAGTAT TGGGATCGGG
 AGACACAGAT CAGCAAGGAC AACGCACAGA CTTACCGAGT GAACCTGAAC
 AACCTGCGCG GCTACTACAA CCAGAGCGAG GCCGGGTCTC ACACCCTCCA
 GAGCATGTAC GGCTGCGACG TGGGACCAGA CGGGCTCTTC CTCCGCGGGT
 ACAGTCAGTT CGCCTACGAC GGCACGGATT ACATCGCCCT GAACGAGGAC
 CTGCGCTCCT GGACCGCGGC GGACACGGCG GCTCAGATCA CCAAGCGCAA
 GAGGGAGGCG GCCGATGCGG CGGAGCAAAT GAGAAGCTAC CTGGAGGGCG
 CCTGTGTGGA GGGGCTCCAG AAATACCTGG AGATGGGGAA GGACACGCTG
 CAGCGCGCAG AGCCTCCAAA GACACATGTG ACCCGCCACC CCAGCTCTGA
 CCTGGGGGTC ACCTTGAGGT GCTGGGCCCT GGGCTTCTAC CCTAAGGAGA
 TCTCCCTGAC CTGGCAGCGC GAGGGCCAGG ACCAGAGCCA GGACATGGAG
 CTGGTGGAGA CCAGGCCCTC AGGGGATGGG ACCTTCCAGA AGTGGGCGGC
 CCTGGTGGTG CCTCCTGGAG AGGAGCAGAG CTACACCTGC CATGTGCAGC
 ACGAGGGCCT GCAGGAGCCC CTCACCCTGA GATGGGACCC TGCTCAGCCC
 CCCGTCCCCA TCGTGGGCAT CATTGTTGGC CTGGTTCTCG TCCTGGTCGC
 TGGAGCCATG GTGGCTGGAG TTGTGATCTG GAGGAAGAAG CGCTCAGGTG
 AAAAAGGAGG GAGGTACACT CAGGCTGCAG GCAGTGACAG TGCCCAGGGC
 TCTGATGTGT CCCTCACCCA GGATCCTAGA GTGTGA*

>DL;SLA-3_0601
SLA-3_0601, 1086 bases, 178079B7 checksum.
 ATGGGGCCCC GAGCCCTCTT CTTGCTGCTG TCGGGGACCC TGGCCCTGAC
 TGGTACCCGG GAGGGTCCCC ACTCCCTGAG GTATTTCGAC ACCGCCGTGT
 CCCGGCCCGA CCGCGGGAAG CCCCGTTTCA TCTCCGTCGG CTACGTGGAC
 GACACGCAGT TCGTGCGGTT CGACAGCGAC GCCCCGAATC CGCGGATGGA
 GCCGCGGGCG CCGTGGATAG AGCAGGAGGG GCAGGAGTAT TGGGATGAGG
 AGACGCGGAA CGCCATGGGC AGCGCACAGA CTTTCCGAGT GAACCTGAAC
 AACCTGCGCG GCTACTACAA CCAGAGCGAG GCCGGGTCTC ACACCCTCCA
 GAGCATGTAC GGCTGCGACG TGGGGCCAGA CTGGCTCTTC CTCCGCGGGT
 ACAGTCAGGA CGCCTACGAC GGCGCCGATT ACATCGCCCT GAACGAGGAC
 CTGCGCTCCT GGACCGCGGC GGACACGGCG GCTCAGATCA CCAAGCGCAA
 GTGGGAGGCG GCCGATGAGG CGGAGCAAAT GAGAAGCTAC CTGGAGGGCG
 CGTGTGTGGA GTGGCTCCAG AAATACCTGC AGATGGGGAA TAACACGCTG
 CAGCGCGCAG AGCCTCCAAA GACACATGTG ACCCGCCACC CCAGCTCTGA
 CCTGGGGGTC ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTAAGGAGA
 TCTCCCTGAC CTGGCAGCGC GAGGGCCAGG ACCAGAGCCA AGACATGGAG
 CTGGTGGAGA CCAGGCCCTC AGGGGATGGG ACCTTCCAGA AGTGGGCGGC
 CCTGGTGGTG CCTCCTGGAG AGGAGCAGAG CTACACCTGC CATGTGCAGC
 ATGAGGGCCT GCAGGAGCCC CTCACCCTGA GATGGGACCC TCCTCAGCCC
 CCCGTCCCCA TCGTGGGCAT CATTGTTGGC CTGGTTCTCG TCCTGGTTGC
 TGGAGCCGTG GTGGCTGGAG TTGTGATCTG GAGGAAGAAG CGCCCAGGTG
 AAAAAGGAGG GAGCTACACT CAGGCTGCAG GCAGTGACAG TGCCCAGGGC
 TCTGATGTGT CCCTCACCAA GGATCCTAGA GTGTGA*

>DL;SLA-3_0602
SLA-3_0602, 1086 bases, 851FD7F6 checksum.
 ATGGGGCCTG GAGCCCTCTT CTTGCTGCTG TCGGGGACCC TGGCCCTGAC
 TGGTACCCGG GAGGGTCCCC ACTCCCTGAG GTATTTCGAC ACCGCCGTGT
 CCCGGCCCGA CCGCGGGAAG CCCCGTTTCA CCTCCGTCGG CTACGTGGAC
 GACACGCAGT TCGTGCGGTT CGACAGCGAC GCCCCGAATC CGCGGATGGA
 GCCGCGGGCG CCGTGGATCG AACAGGAGAG GCAGGAGTAT TGGGATGAGG
 AGACGCGGAA CGCCATGGGC AGCGCACAGA CTTTCCGAGT GAACCTGAAC
 AACCTGCGCG GCTACTACAA CCAGAGCGAG GCCGGGTCTC ACACCTACCA
 GTGGATGTAC GGCTGCGACG TGGGGCCAGA CTGGCTCTTC CTCCGCGGGT
 ACAGTCAGGA CGCCTACGAC GGCGCCGATT ACATCGCCCT GAACGAGGAC
 CTGCGCTCCT GGACCGCGGC GGACACGGCG GCTCAGATCA CCAAGCGCAA
 GAGGGAGGCG GCCGATGCGG CGGAGCAAAT GAGAAGCTAC CTGGAGGGCG
 CGTGTGTGGA GTGGCTCCAG AAATACCTGG AGATGGGGAA GGACACGCTG
 CAGCGCGCAG AGCCTCCAAA GACACATGTG ACCCGCCACC CCAGCTCTGA
 CCTCGGGGTC ACCCTGAGGT GCTGGGCCAT GGGCTTCTAC CCTAAGGAGA
 TCTCCCTGAC CTGGCAGCGC GAGGGCCAGG ACCAGAGCCA GGACATGGAG
 CTGGTGGAGA CCAGGCCCTC AGGGGATGGG ACCTTCCAGA AGTGGGCGGC
 CCTGGTGGTG CCTCCTGGAG AGGAGCAGAG CTACACCTGC CATGTGCAGC
 ACGAGGGCCT GCAGGAGCCC CTCACCCTGA GATGGGACCC TCCTCAGCCC
 CCCGTCCCCA TCGTGGGCAT CATTGTTGGC CTGGTTCTCG TCCTGGTTGC
 TGGAGCCGTG GTGGCTGGAG TTGTGATCTG GAGGAAGAAG CGCCCAGGTG
 AAAAAGGAGG GAGCTACACT CAGGCTGCAG GCAGTGACAG TGCCCAGGGC
 TCTGATGTGT CTCTCACCAA GGATCCTAGA GTGTGA*

>DL;SLA-3_0701
SLA-3_0701, 1095 bases, B352D784 checksum.
 ATGGGGCCCC GAGCCCTCTT CTTGCTGCTG TCGGGGACCC TGGCCCTGAC
 TGGTACCCGG GAGGGTCCCC ACTCCCTGAG GTATTTCGAC ACCGCCGTGT
 CCCGGCCCGA CCGCGGGAAG CCCCGTTTCA TCTCCGTCGG CTACGTGGAC
 GACACGCAGT TCGTGCGGTT CGACAGCGAC GCCCCGAATC CGCGGATGGA
 GCCGCGGGCG CCGTGGATAA AGCAGGAGGG GCAGGAGTGG CAGGAGTATT
 GGGATGAGGA GACGCGGAAC GCCATGGGCA GCGCACAGAC TTTCCGAGTG
 AACCTGAACA ACCTGCGCGG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCCTCCAG AGCATGTACG GCTGCGACGT GGGACCAGAC TGGCTCTTCC
 TCCGCGGGTA CAGTCAGGAC GCCTACGACG GCGCCGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCGGCG GACACGGCGG CTCAGATCAC
 CAAGCGCAAG AGGGAGGCGG CCGATGCGGC GGAGCAAATG AGAAGCTACC
 TGGAGGGCGC GTGTGTGGAG TGGCTCCAGA AATACCTGCA GATGGGGAAT
 AACACGCTGC AGCGCGCAGA GCCTCCAAAG ACACATGTGA CCCGCCACCC
 CAGCTCTGAC CTGGGGGTCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTAAGGAGAT CTCCCTGACC TGGCAGCGCG AGGGCCAGGA CCAGAGCCAA
 GACATGGAGC TGGTGGAGAC CAGGCCCTCA GGGGATGGGA CCTTCCAGAA
 GTGGGCGGCC CTGGTGGTGC CTCCTGGAGA GGAGCAGAGC TACACCTGCC
 ATGTGCAGCA CGAGGGCCTG CAGGAGCCCC TCACCCTGAG ATGGGACCCT
 CCTCAGCCCC CCGTCCCCAT CGTGGGCATC ATTGTTGGCC TGGTTCTCGT
 CCTGGTTGCT GGAGCCGTGG TGGCTGGAGT TGTGATCTGG AGGAAGAAGC
 GCCCAGGTGA AAAAGGAGGG AGCTACACTC AGGCTGCAGG CAGTGACAGT
 GCCCAGGGCT CTGATGTGTC CCTCACCAAG GATCCTAGAG TGTGA*

>DL;SLA-3_0701sm19
SLA-3_0701sm19, 1095 bases, 3215BC70 checksum.
 ATGGGGCCCC GAGCCCTCTT CTTGCTGCTG TCGGGGACCC TGGCCCTGAC
 TGGTACCCGG GAGGGTCCCC ACTCCCTGAG GTATTTCGAC ACCGCCGTGT
 CCCGGCCCGA CCGCGGGAAG CCCCGTTTCA TCTCCGTCGG CTACGTGGAC
 GACACGCAGT TCGTGCGGTT CGACAGCGAC GCCCCGAATC CGCGGATGGA
 GCCGCGGGCG CCGTGGATAA AGCAGGAGGG GCAGGAGTGG CAGGAGTATT
 GGGATGAGGA GACGCGGAAC GCCATGGGCA GCGCACAGAC TTTCCGAGTG
 AACCTGAACA ACCTGCGCGG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCCTCCAG AGCATGTACG GCTGCGACGT GGGGCCAGAC TGGCTCTTCC
 TCCGCGGGTA CAGTCAGGAC GCCTACGACG GCGCCGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCGGCG GACACGGCGG CTCAGATCAC
 CAAGCGCAAG AGGGAGGCGG CCGATGCGGC GGAGCAAATG AGAAGCTACC
 TGGAGGGCGC GTGTGTGGAG TGGCTCCAGA AATACCTGCA GATGGGGAAT
 AACACGCTGC AGCGCGCAGA GCCTCCAAAG ACACATGTGA CCCGCCACCC
 CAGCTCTGAC CTGGGGGTCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTAAGGAGAT CTCCCTGACC TGGCAGCGCG AGGGCCAGGA CCAGAGCCAA
 GACATGGAGC TGGTGGAGAC CAGGCCCTCA GGGGATGGGA CCTTCCAGAA
 GTGGGCGGCC CTGGTGGTGC CTCCTGGAGA GGAGCAGAGC TACACCTGCC
 ATGTGCAGCA CGAGGGCCTG CAGGAGCCCC TCACCCTGAG ATGGGACCCT
 CCTCAGCCCC CCGTCCCCAT CGTGGGCATC ATTGTTGGCC TGGTTCTCGT
 CCTGGTTGCT GGAGCCGTGG TGGCTGGAGT TGTGATCTGG AGGAAGAAGC
 GCCCAGGTGA AAAAGGAGGG AGCTACACTC AGGCTGCAGG CAGTGACAGT
 GCCCAGGGCT CTGATGTGTC CCTCACCAAG GATCCTAGAG TGTGA*

>DL;SLA-3_07Lw02
SLA-3_07Lw02, 1095 bases, B523BBAD checksum.
 ATGGGGCCCC GAGCCCTCTT CTTGCTGCTG TCGGGGACCC TGGCCCTGAC
 TGGTACCCGG GAGGGTCCCC ACTCCCTGAG GTATTTCGAC ACCGCCGTGT
 CCCGGCCCGA CCGCGGGAAG CCCCGTTTCA TCTCCGTCGG CTACGTGGAC
 GACACGCAGT TCGTGCGGTT CGACAGCGAC GCCCCGAATC CGCGGATGGA
 GCCGCGGGCG CCGTGGATAA AGCAGGAGGG GCAGGAGTGG CAGGAGTATT
 GGGATGAGGA GACGCGGAAC GCCATGGGCA GCGCACAGAC TTTCCGAGTG
 AACCTGAACA ACCTGCGCGG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCCTCCAG AGCATGTACG GCTGCGACGT GGGACCAGAC TGGCTCTTCC
 TCCGCGGGTA CAGTCAGGAC GCCTACGACG GCGCCGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCGGCG GACACGGCGG CTCAGATCAC
 CAAGCGCAAG AGGGAGGCGG CCGATGCGGC GGAGCAAATG AGAAGCTACC
 TGGAGGGCGC GTGTGTGGAG TGGCTCCAGA AATACCTGCA GATGGGGAAT
 AACACGCTGC AGCGCGCAGA GCCTCCAAAG ACACATGTGA CCCGCCACCC
 CAGCTCTGAC CTGGGGGTCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTAAGGAGAT CTCCCTGACC TGGCAGCGCG AGGGCCAGGA CCAGAGCCAA
 GACATGGAGC TGGTGGAGAC CAGGCCCTCA GGGGATGGGA CCTTCCAGAA
 GTGGGCGGCC CTGGTGGTGC CTCCTGGAGA GGAGCAGAGC TACACCTGCC
 ATGTGCAGCA CGAGGGCCTG CAGGAGCCCC TCACCCTGAG ATGGGACCCT
 CCTCAGCCCC CCGTCCCCAT CGTGGGCATC ATTGTTGGCC TGGTTCTCGT
 CCTGGTCGCT GGAGCCATGG TGGCTGGAGT TGTGATCTGG AGGAAGAAGC
 GCTCAGGTGA AAAAGGAGGG AGCTACACTC AGGCTGCAGG CAGTGACAGT
 GCCCAGGGCT CTGATGTGTC CCTCACCCAG GATCCTAGAG TGTGA*

>DL;SLA-3_07rh34
SLA-3_07rh34, 668 bases, 318D0BAC checksum.
 GCTACGTGGA CGACACGCAG TTCGTGCGGT TCGACAGCGA CGCCCCGAAT
 CCGCGGATGG AGCCGCGGGC GCCGTGGATA AAGCAGGAGG GGCAGGAGTG
 GCAGGAGTAT TGGGATGAGG AGACGCGGAA CGCCATGGGC AGCGCACAGA
 CTTTCCGAGT GAACCTGAAC AACCTGCGCG GCTACTACAA CCAGAGCGAG
 GCCGGGTCTC TCACCCTCCA GAGCATGTAC GGCTGCGACG TGGGGCCAGA
 CTGGCTCTTC CTCCGCGGGT ACAGTCAGGA CGCCTACGAC GGCGCCGATT
 ACATCGCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACGGCG
 GCGCAGATCA CCAAGCGCAA GAGGGAGGCG GCCGATGTGG CGGAGCAAAT
 GAGAAGCTAC CTGGAGGGCG CGTGTGTGGA GTGGCTCCAG AAATACCTGC
 AGATGGGGAA TAACACGCTG CAGCGCGCAG AGCCTCCAAA GACACATGTG
 ACCCGCCACC CCAGCTCTGA CCTGGGGGTC ACCCTGAGGT GCTGGGCCCT
 GGGCTTCTAC CCTAAGGAGA TCTCCCTGAC CTGGCAGCGC GAGGGCCAGG
 ACCAGAGCCA AGACATGGAG CTGGTGGAGA CCAGGCCCTC AGGGGATGGG
 ACCTTCCAGA AGTGGGCG*

>DL;SLA-3_hm22
SLA-3_hm22, 528 bases, 58F93131 checksum.
 GCTGTCGGGA ACCCTGGCCC TGACCGGGAC CCAGGCGGGT CCCCACTCCC
 TGAGGTATTT CCACACCGCC GTGTCCCGGC CCGACCTCGG GAAGCCCCGT
 TTCATCGCCG TCGGCTACGT GGACGACACG CAGTTCGTGC GGTTCGACAG
 CGACGCCCCG AATCCGCGGA TGGAGTCTCG GGTGCCGTGG ATACAGCAGG
 AGGGGCAGGA GTATTGGGAT GAGGAGACGC GGAAACAAAG GGACACCTCA
 CAGACTTTCC GAGTGAGCCT GAACACCCTG CGCGGCTACT ACAACCAGAG
 CGAGGCCGGG TCTCACACCA TCCAGGTCAT GTACGGCTGC TACTTGGGAC
 CAGACGGGCT CCTCCTCCAC GGGTACCATC AGTACGCCTA CGACGGCGCC
 GATTACCTCG CCCTGAACGA GGACCTGCGC TCCTGGACCG CGGCGGACAC
 GGCGGCTCAG ATCACCAAGC GCAAGTGGGA GGCGGCCGAT GTGACAGAGC
 GTAGGAGGAG CTACCTGGAG GGCGCCTG*

