>DL;SLA-DRA_010101
SLA-DRA_010101, 759 bases, FBFE78DA checksum.
 ATGACCATAC TTGGGGTCCC AGTCCTGGGA TTTGTCATCA CCATCTTGAA
 CCTTCAGAAA TCATGGGCTA TCGTAGAGAA TCACGTGATC ATCCAGGCTG
 AGTTCTATCT GAGCCCTGAC AAATCTGGCG AGTTTATGTT TGACTTTGAC
 GGTGATGAGA TTTTCCACGT GGATATGGAA AAGAGGGAGA CGGTCTGGCG
 ACTTGAAGAA TTTGGACATT TTGCCAGCTT TGAGGCTCAG GGTGCACTGG
 CCAACATAGC TGTGGACAAA GCCAACCTGG AAATCATGAT CAAGCGCTCC
 AACAACACCC CGAACACCAA TGTACCTCCA GAAGTGACTG TGCTCTCAGA
 CAAGCCTGTT GAACTGGGAG AGCCCAACAT CCTCATCTGT TTCATCGACA
 AGTTCTCCCC GCCAGTGGTC AATGTCACCT GGCTTCGAAA TGGCTCCCCT
 GTCACCAGAG GAGTGTCAGA GACAGTCTTC CTGCCCCGGG AGGACCACCT
 TTTCCGCAAG TTCCACTATC TCCCCTTCAT GCCCTCAACC GAGGATGTCT
 ATGACTGCCA GGTGGAGCAC TGGGGTTTGG ACAAGCCTCT TCTCAAGCAC
 TGGGAGTTTG AAGCTCAAAC CCCCCTCCCA GAGACTACAG AGAACACCGT
 GTGTGCTCTG GGCCTGATTG TGGCTCTGGT GGGCATCATC GTCGGAACCG
 TCCTCATCAT CAAGGGTGTG CGCAAAGGCA ACGCCACTGA ACGCCGAGGG
 CCTCTGTGA*

>DL;SLA-DRA_010102
SLA-DRA_010102, 759 bases, 6FA29926 checksum.
 ATGACCATAC TTGGGGTCCC AGTCCTGGGA TTTGTCATCA CCATCTTGAA
 CCTTCAGAAA TCATGGGCTA TCGTAGAGAA TCACGTGATC ATCCAGGCTG
 AGTTCTATCT GAGCCCTGAC AAATCTGGCG AGTTTATGTT TGACTTTGAC
 GGTGATGAGA TTTTCCACGT GGATATGGAA AAGAGGGAGA CGGTCTGGCG
 ACTTGAAGAA TTTGGACATT TTGCCAGCTT TGAGGCTCAG GGTGCACTGG
 CCAACATAGC TGTGGACAAA GCCAACCTGG AAATCATGAT CAAGCGCTCC
 AACAACACCC CGAACACCAA TGTACCTCCA GAAGTGACTG TGCTCTCAGA
 CAAGCCTGTT GAACTGGGAG AGCCCAACAT CCTCATCTGT TTCATCGACA
 AGTTCTCCCC GCCAGTGGTC AATGTCACCT GGCTTCGAAA TGGCTCCCCT
 GTCACCAGAG GAGTGTCAGA GACAGTCTTC CTGCCCCGGG AGGACCACCT
 TTTCCGCAAG TTCCACTATC TCCCCTTCAT GCCCTCAACC GAGGATGTCT
 ATGACTGCCA GGTGGAGCAC TGGGGTTTGG ACAAGCCTCT TCTCAAGCAC
 TGGGAGTTTG AAGCTCAAAC CCCCCTCCCA GAGACTACAG AGAACACCGT
 GTGTGCTCTG GGCCTGATTG TGGCTCTGGT GGGCATCATC GTCGGGACCG
 TCCTCATCAT CAAGGGTGTG CGCAAAGGCA ACGCCACTGA ACGCCGAGGG
 CCTCTGTGA*

>DL;SLA-DRA_010103
SLA-DRA_010103, 759 bases, A800C761 checksum.
 ATGACCATAC TTGGGGTCCC AGTCCTAGGA TTTGTCATCA CCATCTTGAA
 CCTTCAGAAA TCATGGGCTA TCGTAGAGAA TCACGTGATC ATCCAGGCTG
 AGTTCTATCT GAGCCCTGAC AAATCTGGCG AGTTTATGTT TGACTTTGAC
 GGTGATGAGA TTTTCCACGT GGATATGGAA AAGAGGGAGA CGGTCTGGCG
 ACTTGAAGAA TTTGGACATT TTGCCAGCTT TGAGGCTCAG GGTGCACTGG
 CCAACATAGC TGTGGACAAA GCCAACCTGG AAATCATGAT CAAGCGCTCC
 AACAACACCC CGAACACCAA TGTACCTCCA GAAGTGACTG TGCTCTCAGA
 CAAGCCTGTT GAACTGGGAG AGCCCAACAT CCTCATCTGT TTCATCGACA
 AGTTCTCCCC GCCAGTGGTC AATGTCACCT GGCTTCGAAA TGGCTCCCCT
 GTCACCAGAG GAGTGTCAGA GACAGTCTTC CTGCCCCGGG AGGACCACCT
 TTTCCGCAAG TTCCACTATC TCCCCTTCAT GCCCTCAACC GAGGATGTCT
 ATGACTGCCA GGTGGAGCAC TGGGGTTTGG ACAAGCCTCT TCTCAAGCAC
 TGGGAGTTTG AAGCTCAAAC CCCCCTCCCA GAGACTACAG AGAACACCGT
 GTGTGCTCTG GGCCTGATTG TGGCTCTGGT GGGCATCATC GTCGGAACCG
 TCCTCATCAT CAAGGGTGTG CGCAAAGGCA ACGCCACTGA ACGCCGAGGG
 CCTCTGTGA*

>DL;SLA-DRA_0101we01
SLA-DRA_0101we01, 759 bases, 2DCB16E7 checksum.
 ATGACAATAC TTGGGGTCCC AGTCCTAGGA TTTGTCATCA CCATCTTGAA
 CCTTCAGAAA TCATGGGCTA TCGTAGAGAA TCACGTGATC ATCCAGGCTG
 AGTTCTATCT GAGCCCTGAC AAATCTGGCG AGTTTATGTT TGACTTTGAC
 GGTGATGAGA TTTTCCACGT GGATATGGAA AAGAGGGAGA CGGTCTGGCG
 ACTTGAAGAA TTTGGACATT TTGCCAGCTT TGAGGCTCAG GGTGCACTGG
 CCAACATAGC TGTGGACAAA GCCAACCTGG AAATCATGAT CAAGCGCTCC
 AACAACACCC CGAACACCAA TGTACCTCCA GAAGTGACTG TGCTCTCAGA
 CAAGCCTGTT GAACTGGGAG AGCCCAACAT CCTCATCTGT TTCATCGACA
 AGTTCTCCCC GCCAGTGGTC AATGTCACCT GGCTTCGAAA TGGCTCCCCT
 GTCACCAGAG GAGTGTCAGA GACAGTCTTC CTGCCCCGGG AGGACCACCT
 TTTCCGCAAG TTCCACTATC TCCCCTTCAT GCCCTCAACC GAGGATGTCT
 ATGACTGCCA GGTGGAGCAC TGGGGTTTGG ACAAGCCTCT TCTCAAGCAC
 TGGGAGTTTG AAGCTCAAAC CCCCCTCCCA GAGACTACAG AGAACACCGT
 GTGTGCTCTG GGCCTGATTG TGGCTCTGGT GGGCATCATC GTCGGAACCG
 TCCTCATCAT CAAGGGTGTG CGCAAAGGCA ACGCCACTGA ACGCCGAGGG
 CCTCTGTGA*

>DL;SLA-DRA_0201
SLA-DRA_0201, 759 bases, E85CBA2 checksum.
 ATGACCATAC TTGGGGTCCC AGTCCTGGGA TTTGTCATCA CCATCTTGAA
 CCTTCAGAAA TCATGGGCTA TCGTAGAGAA TCACGTGATC ATCCAGGCTG
 AGTTCTATCT GAGCCCTGAC AAATCTGGCG AGTTTATGTT TGACTTTGAC
 GGTGATGAGA TTTTCCACGT GGATATGGAA AAGAGGGAGA CGGTCTGGCG
 ACTTGAAGAA TTTGGACATT TTGCCAGCTT TGAGGCTCAG GGTGCACTGG
 CCAACATAGC TGTGGACAAA GCCAACCTGG AAATCCTGAT CAAGCGCTCC
 AACAACACCC CGAACACCAA TGTACCTCCA GAAGTGACTG TGCTCTCAGA
 CAAGCCTGTT GAACTGGGAG AGCCCAACAT CCTCATCTGT TTCATCGACA
 AGTTCTCCCC GCCAGTGGTC AATGTCACCT GGCTTCGAAA TGGCTCCCCT
 GTCACCAGAG GAGTGTCAGA GACAGTCTTC CTGCCCCGGG AGGACCACCT
 TTTCCGCAAG TTCCACTATC TCCCCTTCAT GCCCTCAACC GAGGATGTCT
 ATGACTGCCA GGTGGAGCAC TGGGGTTTGG ACAAGCCTCT TCTCAAGCAC
 TGGGAGTTTG AAGCTCAAAC CCCCCTCCCA GAGACTACAG AGAACACCGT
 GTGTGCTCTG GGCCTGATTG TGGCTCTGGT GGGCATCATC GTCGGGACCG
 TCCTCATCAT CAAGGGTGTG CGCAAAGGCA ACGCCACTGA ACACCGAGGG
 CCTCTGTGA*

>DL;SLA-DRA_0201jh01
SLA-DRA_0201jh01, 759 bases, 5D7B7419 checksum.
 ATGACCATAC TTGGGGTCCC AGTCCTAGGA TTTGTCATCA CCATCTTGAA
 CCTTCAGAAA TCATGGGCTA TCGTAGAGAA TCACGTGATC ATCCAGGCTG
 AGTTCTATCT GAGCCCTGAC AAATCTGGCG AGTTTATGTT TGACTTTGAC
 GGTGATGAGA TTTTCCACGT GGATATGGAA AAGAGGGAGA CGGTCTGGCG
 ACTTGAAGAA TTTGGACATT TTGCCAGCTT TGAGGCTCAG GGTGCACTGG
 CCAACATAGC TGTGGACAAA GCCAACCTGG AAATCCTGAT CAAGCGCTCC
 AACAACACCC CGAACACCAA TGTACCTCCA GAAGTGACTG TGCTCTCAGA
 CAAGCCTGTT GAACTGGGAG AGCCCAACAT CCTCATCTGT TTCATCGACA
 AGTTCTCCCC GCCAGTGGTC AATGTCACCT GGCTTCGAAA TGGCTCCCCT
 GTCACCAGAG GAGTGTCAGA GACAGTCTTC CTGCCCCGGG AGGACCACCT
 TTTCCGCAAG TTCCACTATC TCCCCTTCAT GCCCTCAACC GAGGATGTCT
 ATGACTGCCA GGTGGAGCAC TGGGGTTTGG ACAAGCCTCT TCTCAAGCAC
 TGGGAGTTTG AAGCTCAAAC CCCCCTCCCA GAGACTACAG AGAACACCGT
 GTGTGCTCTG GGCCTGATTG TGGCTCTGGT GGGCATCATC GTCGGGACCG
 TCCTCATCAT CAAGGGTGTG CGCAAAGGCA ACGCCACTGA ACACCGAGGG
 CCTCTGTGA*

>DL;SLA-DRA_020201
SLA-DRA_020201, 759 bases, FA4FC311 checksum.
 ATGACCATAC TTGGGGTCCC AGTCCTAGGA TTTGTCATCA CCATCTTGAA
 CCTTCAGAAA TCATGGGCTA TCGTAGAGAA TCACGTGATC ATCCAGGCTG
 AGTTCTATCT GAGCCCTGAC AAATCTGGCG AGTTTATGTT TGACTTTGAC
 GGTGATGAGA TTTTCCACGT GGATATGGAA AAGAGGGAGA CGGTCTGGCG
 ACTTGAAGAA TTTGGACATT TTGCCAGCTT TGAGGCTCAG GGTGCACTGG
 CCAACATAGC TGTGGACAAA GCCAACCTGG AAATCCTGAT CAAGCGCTCC
 AACAACACCC CGAACACCAA TGTACCTCCA GAAGTGACTG TGCTCTCAGA
 CAAGCCTGTT GAACTGGGAG AGCCCAACAT CCTCATCTGT TTCATCGACA
 AGTTCTCCCC GCCAGTGGTC AATGTCACCT GGCTTCGAAA TGGCTCCCCT
 GTCACCAGAG GAGTGTCAGA GACAGTCTTC CTGCCCCGGG AGGACCACCT
 TTTCCGCAAG TTCCACTATC TCCCCTTCAT GCCCTCAACC GAGGATGTCT
 ATGACTGCCA GGTGGAGCAC TGGGGTTTGG ACAAGCCTCT TCTCAAGCAC
 TGGGAGTTTG AAGCTCAAAC CCCCCTCCCA GAGACTACAG AGAACACCGT
 GTGTGCTCTG GGCCTGATTG TGGCTCTGGT GGGCATCATC GTCGGGACCG
 TCCTCATCAT CAAGGGTGTG CGCAAAGGCA ACGCCACTGA ACGCCGAGGG
 CCTCTGTGA*

>DL;SLA-DRA_020202
SLA-DRA_020202, 759 bases, 6E1322ED checksum.
 ATGACCATAC TTGGGGTCCC AGTCCTAGGA TTTGTCATCA CCATCTTGAA
 CCTTCAGAAA TCATGGGCTA TCGTAGAGAA TCACGTGATC ATCCAGGCTG
 AGTTCTATCT GAGCCCTGAC AAATCTGGCG AGTTTATGTT TGACTTTGAC
 GGTGATGAGA TTTTCCACGT GGATATGGAA AAGAGGGAGA CGGTCTGGCG
 ACTTGAAGAA TTTGGACATT TTGCCAGCTT TGAGGCTCAG GGTGCACTGG
 CCAACATAGC TGTGGACAAA GCCAACCTGG AAATCCTGAT CAAGCGCTCC
 AACAACACCC CGAACACCAA TGTACCTCCA GAAGTGACTG TGCTCTCAGA
 CAAGCCTGTT GAACTGGGAG AGCCCAACAT CCTCATCTGT TTCATCGACA
 AGTTCTCCCC GCCAGTGGTC AATGTCACCT GGCTTCGAAA TGGCTCCCCT
 GTCACCAGAG GAGTGTCAGA GACAGTCTTC CTGCCCCGGG AGGACCACCT
 TTTCCGCAAG TTCCACTATC TCCCCTTCAT GCCCTCAACC GAGGATGTCT
 ATGACTGCCA GGTGGAGCAC TGGGGTTTGG ACAAGCCTCT TCTCAAGCAC
 TGGGAGTTTG AAGCTCAAAC CCCCCTCCCA GAGACTACAG AGAACACCGT
 GTGTGCTCTG GGCCTGATTG TGGCTCTGGT GGGCATCATC GTCGGAACCG
 TCCTCATCAT CAAGGGTGTG CGCAAAGGCA ACGCCACTGA ACGCCGAGGG
 CCTCTGTGA*

>DL;SLA-DRA_020203
SLA-DRA_020203, 759 bases, A9B17CAA checksum.
 ATGACCATAC TTGGGGTCCC AGTCCTGGGA TTTGTCATCA CCATCTTGAA
 CCTTCAGAAA TCATGGGCTA TCGTAGAGAA TCACGTGATC ATCCAGGCTG
 AGTTCTATCT GAGCCCTGAC AAATCTGGCG AGTTTATGTT TGACTTTGAC
 GGTGATGAGA TTTTCCACGT GGATATGGAA AAGAGGGAGA CGGTCTGGCG
 ACTTGAAGAA TTTGGACATT TTGCCAGCTT TGAGGCTCAG GGTGCACTGG
 CCAACATAGC TGTGGACAAA GCCAACCTGG AAATCCTGAT CAAGCGCTCC
 AACAACACCC CGAACACCAA TGTACCTCCA GAAGTGACTG TGCTCTCAGA
 CAAGCCTGTT GAACTGGGAG AGCCCAACAT CCTCATCTGT TTCATCGACA
 AGTTCTCCCC GCCAGTGGTC AATGTCACCT GGCTTCGAAA TGGCTCCCCT
 GTCACCAGAG GAGTGTCAGA GACAGTCTTC CTGCCCCGGG AGGACCACCT
 TTTCCGCAAG TTCCACTATC TCCCCTTCAT GCCCTCAACC GAGGATGTCT
 ATGACTGCCA GGTGGAGCAC TGGGGTTTGG ACAAGCCTCT TCTCAAGCAC
 TGGGAGTTTG AAGCTCAAAC CCCCCTCCCA GAGACTACAG AGAACACCGT
 GTGTGCTCTG GGCCTGATTG TGGCTCTGGT GGGCATCATC GTCGGGACCG
 TCCTCATCAT CAAGGGTGTG CGCAAAGGCA ACGCCACTGA ACGCCGAGGG
 CCTCTGTGA*

>DL;SLA-DRA_0202Lw02
SLA-DRA_0202Lw02, 759 bases, DEA5B18 checksum.
 ATGACCATAC TTGGGGTCCC AGTCCTGGGA TTTGTCATCA CCATCTTGAA
 CCTTCAGAAA TCATGGGCTA TCGTAGAGAA TCACGTGATC ATCCAGGCTG
 AGTTCTATCT GAGCCCTGAC AAATCTGGCG AGTTTATGTT TGACTTTGAC
 GGTGATGAGA TTTTCCACGT GGATATGGAA AAGAGGGAGA CGGTCTGGCG
 ACTTGAAGAA TTTGGACATT TTGCCAGCTT TGAGGCTCAG GGTGCACTGG
 CCAACATAGC TGTGGACAAA GCCAACCTGG AAATCCTGAT CAAGCGTTCC
 AACAACACCC CGAACACCAA TGTACCTCCA GAAGTGACTG TGCTCTCAGA
 CAAGCCTGTT GAACTGGGAG AGCCCAACAT CCTCATCTGT TTCATCGACA
 AGTTCTCCCC GCCAGTGGTC AATGTCACCT GGCTTCGAAA TGGCTCCCCT
 GTCACCAGAG GAGTGTCAGA GACAGTCTTC CTGCCCCGGG AGGACCACCT
 TTTCCGCAAG TTCCACTATC TCCCCTTCAT GCCCTCAACC GAGGATGTCT
 ATGACTGCCA GGTGGAGCAC TGGGGTTTGG ACAAGCCTCT TCTCAAGCAC
 TGGGAGTTTG AAGCTCAAAC CCCCCTCCCA GAGACTACAG AGAACACCGT
 GTGTGCTCTG GGCCTGATTG TGGCTCTGGT GGGCATCATC GTCGGGACCG
 TCCTCATCAT CAAGGGTGTG CGCAAAGGCA ACGCCACTGA ACGCCGAGGG
 CCTCTGTGA*

>DL;SLA-DRA_020301
SLA-DRA_020301, 759 bases, B2103BF9 checksum.
 ATGACCATAC TTGGGGTCCC AGTCCTGGGA TTTGTCATCA CCATCTTGAA
 CCTTCAGAAA TCATGGGCTA TCGTAGAGAA TCACGTGATC ATCCAGGCTG
 AGTTCTATCT GAGCCCTGAC AAATCTGGCG AGTTTATGTT TGACTTTGAC
 GGTGATGAGA TTTTCCACGT GGATATGGAA AAGAGGGAGA CGGTCTGGCG
 ACTTGAAGAA TTTGGACATT TTGCCAGCTT TGAGGCTCAG GGTGCACTGG
 CCAACATAGC TGTGGACAAA GCCAACCTGG AAATCCTGAT CAAGCGTTCC
 AACAACACCC CGAACACCAA TGTACCTCCA GAAGTGACTG TGCTCTCAGA
 CAAGCCTGTT GAACTGGGAG AGCCCAACAT CCTCATCTGT TTCATCGACA
 AGTTCTCCCC GCCAGTGGTC AATGTCACCT GGCTTCGAAA TGGCTCCCCT
 GTCACCAGAG GAGTGTCAGA GACAGTCTTC CTGCCCCGGG AGGACCACCT
 TTTCCGCAAG TTCCACTATC TCCCCTTCAT GCCCTCAACC GAGGATGTCT
 ATGACTGCCA GGTGGAGCAC TGGGGTTTGG ACAAGCCTCT TCTCAAGCAC
 TGGGAGTTTG AAGCTCGAAC CCCCCTCCCA GAGACTACAG AGAACACCGT
 GTGTGCTCTG GGCCTGATTG TGGCTCTGGT GGGCATCATC GTCGGGACCG
 TCCTCATCAT CAAGGGTGTG CGCAAAGGCA ACGCCACTGA ACGCCGAGGG
 CCTCTGTGA*

>DL;SLA-DRA_0203my01
SLA-DRA_0203my01, 759 bases, 58C9B6F7 checksum.
 ATGACCATAC TTGGGGTCCC GGTCCTGGGA TTTGTCATCA CCATCTTGAA
 CCTTCAGAAA TCATGGGCTA TCGTAGAGAA TCACGTGATC ATCCAGGCTG
 AGTTCTATCT GAGCCCTGAC AAATCTGGCG AGTTTATGTT TGACTTTGAC
 GGTGATGAGA TTTTCCACGT GGATATGGAA AAGAGGGAGA CGGTCTGGCG
 ACTTGAAGAA TTTGGACATT TTGCCAGCTT TGAGGCTCAG GGTGCACTGG
 CCAACATAGC TGTGGACAAA GCCAACCTGG AAATCCTGAT CAAGCGTTCC
 AACAACACCC CGAACACCAA TGTACCTCCA GAAGTGACTG TGCTCTCAGA
 CAAGCCTGTT GAACTGGGAG AGCCCAACAT CCTCATCTGT TTCATCGACA
 AGTTCTCCCC GCCAGTGGTC AATGTCACCT GGCTTCGAAA TGGCTCCCCT
 GTCACCAGAG GAGTGTCAGA GACAGTCTTC CTGCCCCGGG AGGACCACCT
 TTTCCGCAAG TTCCACTATC TCCCCTTCAT GCCCTCAACC GAGGATGTCT
 ATGACTGCCA GGTGGAGCAC TGGGGTTTGG ACAAGCCTCT TCTCAAGCAC
 TGGGAGTTTG AAGCTCGAAC CCCCCTCCCA GAGACTACAG AGAACACCGT
 GTGTGCTCTG GGCCTGATTG TGGCTCTGGT GGGCATCATC GTCGGGACCG
 TCCTCATCAT CAAGGGTGTG CGCAAAGGCA ACGCCACTGA ACGCCGAGGG
 CCTCTGTGA*

>DL;SLA-DRA_w03ta01
SLA-DRA_w03ta01, 759 bases, 5AD278DB checksum.
 ATGACCATAC TTGGGGTCCC AGTCCTGGGA TTTGTCATCA CCATCTTGAA
 CCTTCAGAAA TCATGGGCTA TCGTAGAGAA TCACGTGATC ATCCAGGCTG
 AGTTCTATCT GAGCCCTGAC AAATCTGGCG AGTTTATGTT TGACTTTGAC
 GGTGATGAGA TTTTCCACGT GGATATGGAA AAGAGGGAGA CGGTCTGGCG
 ACTTGAAGAA TTTGGACATT TTGCCAGCTT TGAGGCTCAG GGTGCACTGG
 CCAACATAGC TGTGGACAAA GCCAACCTGG AAATCGTGAT CAAGCGCTCC
 AACAACACCC CGAACACCAA TGTACCTCCA GAAGTGACTG TGCTCTCAGA
 CAAGCCTGTT GAACTGGGAG AGCCCAACAT CCTCATCTGT TTCATCGACA
 AGTTCTCCCC GCCAGTGGTC AATGTCACCT GGCTTCGAAA TGGCTCCCCT
 GTCACCAGAG GAGTGTCAGA GACAGTCTTC CTGCCCCGGG AGGACCACCT
 TTTCCGCAAG TTCCACTGTC TCCCCTTCAT GCCCTCAACC GAGGATGTCT
 ATGACTGCCA GGTGGAGCAC TGGGGTTTGG ACAAGCCTCT TCTCAAGCAC
 TGGGAGTTTG AAGCTCAAAC CCCCCTCCCA GAGACTACAG AGAACACCGT
 GTGTGCTCTG GGCCTGATTG TGGCTCTGGT GGGCATCATC GTCGGAACCG
 TCCTCATCAT CAAGGGTGTG CGCAAAGGCA ACGCCACTGA ACGCCGAGGG
 CCTCTGTGA*

