>P1;SLA-2_0101
SLA-2_0101, 365 bases, D7CA5DBF checksum.
 MRVRGPQAIL ILLSGALALT GTWAGPHSLS YFSTAVSRPD RGEPRFIAVG
 YVDDTQFVRF DSDAPNPRME PRAPWIQQEG QDYWDRETRN VMGSAQTDRV
 NLKTLRGYYN QSEAGSHTIQ SMYGCDVGPD GLLLRGYSQD AYDGADYIAL
 NEDLRSWTAA DTAAQITKRK WEAANVAERM RSYLQGLCVE GLQKYLQMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPIPIVGI IVGLVLVLVA GAMVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_0102
SLA-2_0102, 182 bases, 5D7E2000 checksum.
 GALALTGTWA GPHSLSYFST AVSRPDRGEP RFIAVGYVDD TQFVRFDSDA
 PNPRMEPRAP WIQQEGQDYW DRETRNVMGS AQTDRVNLKT LRGYYNQSEA
 GSHTIQSMYG CDVGPDGLLL RGYRQDAYDG ADYIALNEDL RSWTAADTAA
 QITKRKWEAA DVAEQERSYL EGTCVEWLQK YL*

>P1;SLA-2_0201
SLA-2_0201, 365 bases, 90EE05FC checksum.
 MRVRGPQAIL ILLSGALALT GTRAGPHSLS YFYTAVSRPD RGDSRFLTVG
 YVDDTQFVRF DSDAPNPREE PRAPWIQQEG QDYWDRETQI SKETAQTYRV
 NLNTLRSYYN QSEAGSHTLQ RMYGCDVGPD GLFLRGYSQF GYDGADYLAL
 NEDLRSWTAA DTAAQISKRK FDAANVAEQE RSYLQGLCVE GLRRYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWEP
 PQPPVPIVGI FVGLVLVLVA GTMVTGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK GPRVX*

>P1;SLA-2_0202
SLA-2_0202, 365 bases, 90EE05FC checksum.
 MRVRGPQAIL ILLSGALALT GTRAGPHSLS YFYTAVSRPD RGDSRFLTVG
 YVDDTQFVRF DSDAPNPREE PRAPWIQQEG QDYWDRETQI SKETAQTYRV
 NLNTLRSYYN QSEAGSHTLQ RMYGCDVGPD GLFLRGYSQF GYDGADYLAL
 NEDLRSWTAA DTAAQISKRK FDAANVAEQE RSYLQGLCVE GLRRYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWEP
 PQPPVPIVGI FVGLVLVLVA GTMVTGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK GPRVX*

>P1;SLA-2_0301
SLA-2_0301, 365 bases, C6438D3C checksum.
 MRVRGPQAIL ILLSGALALT GTRAGPHSLS YFYTAVSRPD LGDSRFIAVG
 YVDDTQFVRF DSDAPNPRME PRAPWIEKEG QEYWDRETQI QRDTSQTYRV
 DLKTLRGYYN QSEAGSHTLQ SMYGCYLGPD GLLLRGYRQF AYDGADYLAL
 NEDLRSWTAA DMAAQISKRK WEAANAAEQE RSYLQGRCVE WLRRYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPIVGI IVGLVLVLVA GAMVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_0302
SLA-2_0302, 363 bases, 8B9E3B7A checksum.
 MRVRGPQAIL ILLSGALALT GTQAGPHSLR YFYTAVSRPD RGEPRFIAVG
 YVDDTQFVRF DSDAPNPRME SRVPWIQQEG QEYWDRETQI QRDTSQTYRV
 DLKTLRGYYN QSEAGSHTLQ RMYGCYLGPD GLLLRGYHQD AYDGADYLAL
 NEDLRSWTAA DMAAQISKRK WEAADVAEQL RSYLQGRCVE SLRRYLQMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQHPVPIVGI IVGLVLVVGA MVAGVVIWWK KRSGEKGGSY TQAAGSDSAQ
 GSDVSLTKGP RVX*

>P1;SLA-2_03gz01
SLA-2_03gz01, 365 bases, 881B8839 checksum.
 MRVRGPQAIL ILLSGALALT GTQAGPHSLS YFYTAVSRPD RGEPRFIAVG
 YVDDTQFVRF DSDAPNPRME PRVPWIQQEG QEYWDRETQI QRDTSQTYRV
 GLNTLRGYYN QSEAGSHTIQ SMYGCYLGPD GLLLRGYSQD AYDGADYVAL
 NEDLRSWTAA DMAAQISKRK WEAADVAEQL RSYLQGTCVE WLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPIVGI IVGLVLVLVA GAMVAGVVIW WKKRSGEKGG SYTQAAGSDS
 AQGSNVSLNK DPRVX*

>P1;SLA-2_0401
SLA-2_0401, 365 bases, C8211540 checksum.
 MRVRGPQAIL ILLSGALALT GTQAGPHSLR YFDTAVSRPD RGEPRFIEVG
 YVDDTQFVRF DSDAPNPRME PRAPWIQQEG QEYWDRNTRN AMGNAQIYRG
 NLRTALGYYN QSEAGSHTIQ IMYGCDVGPD GLLLRGYSQD AYDGADYIAL
 NEDLRSWTAA DTAAQITKRK WEAADEAERR RSYLQGTCVE WLQKYLQMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPIVGI IVGLVLVLVA GAVVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_040201
SLA-2_040201, 365 bases, 60BD92 checksum.
 MRVRGPQAIL ILLSGALALT GTQAGPHSLR YFDTAVSRPD RGEPRFIEVG
 YVDDTQFVRF DSDAPNPRME PRAPWIQQEG QEYWDRNTRN AMGNAQIYRG
 NLRTALGYYN QSEAGSHTLQ IMYGCDVGPD GLLLRGYSQD AYDGADYIAL
 NEDLRSWTAA DTAAQITKRK WEAANVAEQW RSYLQGTCVE WLQKYLQMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPIVGI IVGLVLVLVA GAVVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_040202
SLA-2_040202, 365 bases, 60BD92 checksum.
 MRVRGPQAIL ILLSGALALT GTQAGPHSLR YFDTAVSRPD RGEPRFIEVG
 YVDDTQFVRF DSDAPNPRME PRAPWIQQEG QEYWDRNTRN AMGNAQIYRG
 NLRTALGYYN QSEAGSHTLQ IMYGCDVGPD GLLLRGYSQD AYDGADYIAL
 NEDLRSWTAA DTAAQITKRK WEAANVAEQW RSYLQGTCVE WLQKYLQMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPIVGI IVGLVLVLVA GAVVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_0501
SLA-2_0501, 362 bases, FD6E5D6E checksum.
 RGPQAILILL SGALALTGTW AGPHSLSYFY TAVSRPDRGD SRFIAVGYVD
 DTQFVRFDSD APNPRMEPRA PWIEKEGQEY WDEETRNAMG SAQTFRVNLR
 TALGYYNQSV AGSHTFQWMY GCYLGPDGLL LRGYSQYAYD SADYIALNED
 LRSWTAADTA AQITKRKWET ANVAERRRSY LQGLCVEWLQ KYLEMGKDTL
 QRAEPPKTHV TRHPSSDLGV TLRCWALGFY PKEISLTWQR EGQDQSQDME
 LVETRPSGDG TFQKWAALVV PPGEEQSYTC HVQHEGLQEP LTLRWEPPQP
 PVPIVGIIVG LVLVLVAGAM VAGVVIWRKK RPGEKGGSYT QAAGSDSAQG
 SDVSLTKDPR VX*

>P1;SLA-2_0502
SLA-2_0502, 365 bases, 4C85A6FB checksum.
 MRVRGPQAIL ILLSGALALT GTWAGPHSLS YFYTAVSRPD RGDSRFIAVG
 YVDDTQFVRF DSDAPNPRME PRAPWIEKEG QEYWDRNTRN AMRSAQTFRV
 NLRTALGYYN QSVAGSHTFQ SMYGCYLGPD GLLLRGYRQY AYDSADYIAL
 NEDLRSWTAA DTAAQITKRK WETANVAEGE RSYLQGLCVE SLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWEP
 PQPPVPIVGI IVGLVLVLVA GAMVAGVVIW RKKRPGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_05rh03
SLA-2_05rh03, 219 bases, 82259480 checksum.
 YVDDTQFVRF DSDAPNPRME PRAPWIEKEG QEYWDEETRK VMGSAQTFRV
 NLRTALGYYN QSVAGSHTLQ WMYGCYLGPD GLLLRGYRQD AYDGADYIAL
 NEDLRSWTAA DTAAQITKRK WEAADEAEQW RSYLQGLCVE GLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWA*

>P1;SLA-2_05rh07
SLA-2_05rh07, 263 bases, C013EB4E checksum.
 YFYTAVSRPD RGDSRFIAVG YVDDTQFVRF DSDAPNPRME PRAPWIEKEG
 QEYWDEETRK VMGSAQTFRV NLRTALGYYN QSVAGSHTFQ WMYGCYLGPD
 GLLLRGYSQY AYDSADYIAL NEDLRSWTAA DTAAQISKRK WETANVAEGE
 RSYLQGLCVE SLQKYLEMGK DTLQRAEPPK THVTRHPSSD LGVTLRCWAL
 GFYPKEISLT WQREGQDQSQ DMELVETRPS GDGTFQKWAA LVVPPGEEQS
 YTCHVQHEGL QEP*

>P1;SLA-2_05rh34
SLA-2_05rh34, 219 bases, 8317F04A checksum.
 YVDDTQFVRF DSDAPNPRME PRAPWIEKEG QEYWDEETRN AMGSAQTFRV
 NLRTALGYYN QSVAGSHTFQ WMYGCYLGPD GLLLRGYSQY AYDSADYIAL
 NEDLRSWTAA DTAAQITKRK WETANVAERR RSYLQGLCVD WLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWA*

>P1;SLA-2_05sy01
SLA-2_05sy01, 365 bases, 4F98AF8A checksum.
 MRVRGPQAIL ILLSGALALT GTWAGPHSLS YFSTAVSRPD RGDSRFIAVG
 YVDDTQFVRF DSDAPNPRME PRAPWIEKEG QEYWDEETRK VMGSAQTFRV
 NLRTALGYYN QSVAGSHTFQ WMFGCYLGPD GLLLRGYSQY AYDSADYIAL
 NEDLRSWTAA DTAAQITKRK WETANVAEGE RSYLQGLCVE GLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWEP
 PQPPVPIVGI IVGLVLVLVA GAMVAGVVIW RKKRPGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_0601
SLA-2_0601, 365 bases, E928D7F3 checksum.
 MRVRGPQAIL ILLSGALALT GTQAGSHSLS YFHTAVSRPD LGDSRFLTVG
 YVDDTQFVRF DSDAPNPRKE PRAPWIEQEG QDYWDRETQI SKDYAQRYRV
 GLNTLRGYYN QSEAGSHTYQ RMYGCDMGPD GLLLRGYDQF AYDGADYVAL
 NEDLRSWTAA DTAAQITKRK WEAADAAEQE RSYLQGTCVE WLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQQWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWEP
 PQPPVPIVGI TVGLVLVLVA GAMVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_06an03
SLA-2_06an03, 182 bases, 1160126C checksum.
 GALALTGTRA GPHSLRYFHT AVSRPDRGDS RFLTVGYVDD TQFVRFDSDA
 PNPRKEPRAP WIEQEGQDYW DRETQISKDN AQIYRGSLNN LRGYYNQSEA
 GSHTLQWMCG CDVGPDGLFL RGYDQDAYDG ADYIALNEDL RSWTAADTAA
 QITKRKWEAA DEAERMRSYL QGRCVESLQK YL*

>P1;SLA-2_06me01
SLA-2_06me01, 365 bases, 6B2A71A8 checksum.
 MRVRGPQAIL ILLSGALALT GTQAGPHSLR YFYTAVSRPD LGDSRFLTVG
 YVDDTQFVRF DSDAPNPRKE PRAPWIEQEG PEYWDRETQI SKDNAQNYRV
 NLNTLRGYYN QSEAGSHTLQ VMFGCDVGPD GLFLHGYHQD AYDGADYIAL
 NEDLRSWTAA DMAAQITKRK REASGWAEQW RSYLQGLCVE GLRRYLEMGK
 DTLQHAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWEP
 PQPPVPIVGI IVGLVLVLVA GAMVAGVVIW RKKRPGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_06sr01
SLA-2_06sr01, 353 bases, 274EB9E4 checksum.
 LSGALALTGT QAGPHSLSYF HTAVSRPDLG DSRFLTVGYV DDTQFVRFDS
 DAPNPRKEPR APWIEQEGQD YWDRETQISK DNAQTYRVGL NTLRGYYNQS
 EAGSHTLQVM FGCDVGPDGL LLRGYIQFAY DGADYLALNE DLRSWTAADT
 AAQISKRKFD AADEAEQMRS YLQGLCVESL RKYLEMGKDT LQRAEPPKTH
 VTRHPSSDLG VTMRCWALGF YPKEISLTWQ REGQDQSQDM ELVETRPSGD
 GTFQKWAALV VPPGEEQSYT CHVQHEGLQE PLTLRWEPPQ PPVPIVGIIV
 GLVLVLVAGA MVAGVVIWRK KRSGEKGGSY TQAAGSDSAQ GSDVSLTKDP
 RVX*

>P1;SLA-2_06sv01
SLA-2_06sv01, 353 bases, BB9A7703 checksum.
 LSGALALTGT QAGSHSLSYF HTAVSRPDLG DSRFLTVGYV DDTQFVRFDS
 DAPNPRKEPR APWIEQEGQD YWDRETQISK DNAQRYRVGL NTLRGYYNQS
 EAGSHTLQSM FGCDVGPDGL FLRGYSQDAY DGADYIALNE DLRSWTAADT
 AAQITKRKWE AADEAERMRS YLQGLCVEGL REYLEMGKDT LQRAEPPKTH
 VTRHPSSDLG VTLRCWALGF YPKEISLTWQ REGQDQSQDM ELVETRPSGD
 GTFQKWAALV VPPGEEQSYT CHVQHEGLQE PLTLRWEPPQ PPVPIVGIIV
 GLVLVLVAGA MVAGVVIWRK KRSGEKGGSY TQAAGSDSAQ GSDVSLTKDP
 RVX*

>P1;SLA-2_0701
SLA-2_0701, 365 bases, 92E826D1 checksum.
 MRVRGPQAIL ILLSGALALT GTWAGPHSLS YFSTAVSRPD RGDSRFIAVG
 YVDDTQFVRF DSDAPNPRME PRAPWIQQEG QDYWDRETRN VMGSAQTDRV
 SLNNLRGYYN QSEAGSHTLQ VMYGCDVGPD GLFLHGYRQF AYDGADYLAL
 NEDLRSWTAA DMAAQISKRK FDAANVAEGE RSYLEGLCVE GLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPIVGI IVGLVLVLVA GAMVTGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_07an05
SLA-2_07an05, 182 bases, 94D7C655 checksum.
 GALALTGTWA GPHSLSYFST AVSRPDRGDS RFIAVGYVDD TQFVRFDSDA
 PNPRMEPRAP WIQQEGQDYW DRETRNVMGS AQTDRVSLNN LRGYYNQSEA
 GSHTLQVMYG CDVGPDGLLL RGYHQYGYDG ADYLALNEDL RSWTAADMAA
 QISKRKFDAA NVAEGERSYL KGLCVEGLQK YL*

>P1;SLA-2_07rh12
SLA-2_07rh12, 62 bases, 20995242 checksum.
 YVDDTQFVRF DSDAPNPRME PRAPWIQQEG QDYWDRETRN VMGSAQTDRV
 NLKTLRGYYN QS*

>P1;SLA-2_07we01
SLA-2_07we01, 365 bases, 1DE9999C checksum.
 MRVRGPQAIL ILLSGALALT GTWAGPHSLS YFYTAVSRPD RGDSRFIAVG
 YVDDTQFVRF DSDAPNPRME PRAPWIQQEG QDYWDRETRN VMGSAQTDRV
 NLKTLRGYYN QSEAGSHTLQ VMYGCDVGPD GLLLRGYRQF AYDGADYLAL
 NEDLRSWTAA DMAAQISKRK FDAANVAEGE RSYLEGLCVE GLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPIVGI IVGLVLVLVA GAMVTGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_1001
SLA-2_1001, 365 bases, 6EE242B2 checksum.
 MRVRGPQAIL ILLSGALALT GTQAGPHSLS YFYTAVSRPD RGDSRFFIVG
 YVDDTQFVRF DSDAPNAKME PRAQWIQQEG QEYWDRETQI SKDNAQINRV
 NLNTLRGYYN QSEAGSHTLQ RMYGCYLGPD GLLLRGYDQD AYDGADYIAL
 NEDLRSWTAA DMAAQISKRK REAADEAERM RSYLQGRCVE WLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLS WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 AQPPVPMVGI IVGLVLVLVA GAMVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_1002
SLA-2_1002, 182 bases, C129819A checksum.
 GALALTGTQA GPHSLSYFYT AVSRPDRGDS RFFIVGYVDD TQFVRFDSDA
 PNAKMEPRAQ WIQQEGQEYW DRETQISKET AQNYRVDLNT LRGYYNQSEA
 GSHTLQRMYG CYLGPDGLLL RGYRQDAYDG ADYIALNEDL RSWTAADMAA
 QITKRKWEAA NVAEGERSYL QGRCVEWLQK YL*

>P1;SLA-2_10es21
SLA-2_10es21, 365 bases, E21F5388 checksum.
 MRVRGPQAIL ILLSGALALT GTQAGPHSLS YFYTAVSRPD RGDSRFFIVG
 YVDDTQFVRF DSDAPNAKME PRAQWIQQEG QEYWDRETQI SKDNAQTYRV
 GLKNLRGYYN QSEAGSHTLQ RMFGCYLGPD GLLLRGYDQD AYDGADYLAL
 NEDLRSWTAA DMAAQISKRK REAADEAERM RSYLQGRCVE WLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLS WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 AQPPVPMVGI IVGLVLVLVA GAMVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_10sk21
SLA-2_10sk21, 365 bases, 7268624B checksum.
 MRVRGPQAIL ILLSGALALT GTQAGPHSLS YFYTAVSRPD RGDSRFFIVG
 YVDDTQFVRF DSDAPNAKME PRAQWIQQEG QEYWDRETQI SKETAQNYRV
 DLNTLRGYYN QSEAGSHTYQ WMYGCYLGPD GLLLRGYDQD AYDGADYLAL
 NEDLRSWTAA DMAAQISKRK REAADEAERM RSYLQGRCVE WLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLS WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 AQPPVPMVGI IVGLVLVLVA GAMVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_10sm01
SLA-2_10sm01, 365 bases, FDA91BE7 checksum.
 MRVRGPQAIL ILLSGALALT GTQAGPHSLS YFYTAVSRPD RGDSRFFIVG
 YVDDTQFVRF DSDAPNAKME PRAQWIQQEG QEYWDRETQI SKETAQINRV
 DLNTLRGYYN QSEAGSHTLQ RMFGCYLGPD GLLLRGYDQD AYDGADYLAL
 NEDLRSWTAA DMAAQISKRK REAADEAERM RSYLQGRCVE WLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLS WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 AQPPVPMVGI IVGLVLVLVA GAMVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_110101
SLA-2_110101, 365 bases, C3D6E91E checksum.
 MRVRGPQAIL ILLSGALALT GTWAGPHSLS YFYTAVSRPD RGDSRFIAVG
 YVDDTQFVRF DSDAPNPREE PRAPWIQQEG QEYWDRNTQI YKETAQIYRG
 NLRTALGYYN QSEAGSHTFQ SMYGCDVGPD GLLLRGYSQF GYDGADYIAL
 NEDLRSWTAA DTAAQITKRK WEAADAAERR RSYLQGLCVE SLREYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPMVGI IVGLVLVLVA GAMVTGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_110102
SLA-2_110102, 365 bases, C3D6E91E checksum.
 MRVRGPQAIL ILLSGALALT GTWAGPHSLS YFYTAVSRPD RGDSRFIAVG
 YVDDTQFVRF DSDAPNPREE PRAPWIQQEG QEYWDRNTQI YKETAQIYRG
 NLRTALGYYN QSEAGSHTFQ SMYGCDVGPD GLLLRGYSQF GYDGADYIAL
 NEDLRSWTAA DTAAQITKRK WEAADAAERR RSYLQGLCVE SLREYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPMVGI IVGLVLVLVA GAMVTGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_11so01
SLA-2_11so01, 365 bases, E23AE964 checksum.
 MRVRGPQAIL ILLSGALALT GTWAGPHSLS YFYTAVSRPD RGDSRFIAVG
 YVDDTQFVRF DSDAPNPREE PRAPWIQQEG QEYWDRNTQI YKETAQIYRG
 NLRTALGYYN QSEAGSHTFQ SMCGCYLGPD GLLLRGYSQY GYDGADYIAL
 NEDLRSWTAA DTAAQITKRK WEAADAAEQE RSYLQGTCVE WLQKYLEMGE
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPMVGI IVGLVLVLVA GAMVTGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_1201
SLA-2_1201, 365 bases, F176EC35 checksum.
 MRVRGPQAIL ILLSGALALT GTWAGPHSLS YFYTAVSRPD RGDSRFIAVG
 YVDDTQFVRF DSDAPNPRME PRAPWIEKEG QEYWDRETRN VMGSAQTDRV
 NLKTLRGYYN QSEAGSHTFQ WMYGCYLGPD GLLLRGYSQF AYDSADYIAL
 NEDLRSWTAA DTAAQISKRK WEAANVAEHW RSYLQGLCVE SLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWEP
 PQPPVPIVGI IVGLVLVLVA GAMVAGVVIW RKKRPGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_12Lw01
SLA-2_12Lw01, 365 bases, C3E95272 checksum.
 MRVRGPQAIL ILLSGALALT GTWAGPHSLS YFYTAVSRPD RGDSRFIAVG
 YVDDTQFVRF DSDAPNPRME PRAPWIEKEG QEYWDRETRN VMGSAQTDRV
 NLKTLRGYYN QSEAGSHTFQ WMYGCYLGPD GLLLRGYSQF AYDSADYIAL
 NEDLRSWTAA DTAAQISKRK LEAANVAEHW RSYLQGLCVE SLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWEP
 PQPPVPIVGI IVGLVLVLVA GAMVAGVVIW RKKRPGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_an04
SLA-2_an04, 175 bases, 46169BC8 checksum.
 GALALTGTRA GPHSLSYFHT AVSRPDRGDS RFLTVGYVDD TQFVRFDSDA
 PNPREEPRAP WIEKEGQEYW DRNTQISKET AQTFRVDLNT LRGYYNQSEA
 GSHTIQWMYG CDMGPDGLFL HGYHQYAYDG ADYLALNEDL RSWTAADMAA
 QITKRKFDAA NVAERRRSYL QGRCV*

>P1;SLA-2_es22
SLA-2_es22, 365 bases, F2DB3AED checksum.
 MRVRGPQAIL ILLSGALALT GTWAGPHSLS YFYTAVSRPD RGEPRFIAVG
 YVDDTQFVRF DSDAPNPRME PRAPWIQQEG QDYWDRETQI QRDNAQTFRV
 NLRTALGYYN QSEAGSHTFQ SMYGCYLGPD GLLLRGYSQY GYDSADYIAL
 NEDLRSWTAA DTAAQITKRK WEAADEAEQW RSYLQGLCVE GLRRYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPIPIVGI IVGLVLVLVA GAMVTGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_jh01
SLA-2_jh01, 365 bases, 2E74ECA9 checksum.
 MRVRGPQAIL ILLSGALALT GTQAGPHSLS YFYTAVSRPD RGKPRFIEVG
 YVDDTQFVRF DSDAPNPRME PRVPWIEKEG QEYWDEETRK AVGSAQTFRG
 SLNNLRGYYN QSEAGSHTLQ IMYGCDVGPD GLLLRGYRQD AYDGADYIAL
 NEDLRSWTAA DTAAQITKRK WETADEAEQW RSYLQGLCVE WLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPIVGI IVGLVLVLVA GAVVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_jh02
SLA-2_jh02, 365 bases, D4CA6FB4 checksum.
 MRVRGPQAIL ILLSGALALT GTQAGSHSLS YFYTAVSRPD RGDSRFLTVG
 YVDDTQFVRF DSDAPNPREE PRAPWIQQEG QDYWDRNTQI YKETAQIYRV
 GLNNLRGYYN QSEAGSHTFQ SMYGCDVGPD GLFLRGYSQD AYDGADYVAL
 NEDLRSWTAA DMAAQITKRK REAADAAEQW RSYLQGTCVE GLRRYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPIVGI IVGLVLVLVT GAVVTGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_sw14yn01
SLA-2_sw14yn01, 365 bases, 436A3729 checksum.
 MRVRGPQAIL ILLSGALALT GTQAGPHSLR YFYTAVSRPD RGDSRFLTVG
 YVDDTQFVRF DSDAPNPREE PRAPWIEQEG QDYWDRETQI SKETAQTYRV
 GLKILRGYYN QSEAGSHTYQ WMYGCYLGPD GLFLRGYSQY GYDGADYIAL
 NEDLRSWTAA DTAAQITKRK WEAADEAEQM RSYLQGLCVE WLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQTQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWEP
 PQPPVPIVGI IVGLVLVLVT GAMVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_w08gx01
SLA-2_w08gx01, 365 bases, A34DE4EC checksum.
 MRVRGPQAIL ILLSGALALT GTWAGPHSLR YFHTAVSRPD RGDSRFLTVG
 YVDDTQFVRF DSDAPNPRKE PRAPWIEQEG QDYWDRETQI SKDNAEINRV
 GLNTLRGYYN QSEAGSHTLQ SMYGCDVGPD GLFLRGYSQD AYDGADYIAL
 NEDLRFWTAA DMAVQITKRK WEAADAAEEE RSYLQGTCVE WLRRYLEMGK
 DTCKRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 AQPPVPMVGI IVGLVLVLVA GAVVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_w08sw01
SLA-2_w08sw01, 364 bases, C10AD579 checksum.
 MRVRGPQAIL ILLSGALALT GTWAGPHSLR YFHTAVSRPD RGDSRFLTVG
 YVDDTQFVRF DSDAPNPRKE PRAPWIEQEG QDYWDRETQI SKDNAEINRV
 DLKTLRGYYN QSEAGSHTLQ SMYGCDVGPD GLFLRGYRQD AYDGADYIAL
 NEDLRSWTAA DMAAQITKRK WEAADAAERR RSYLQGTCVE WLRRYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVGTRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 AQPPVPMVGI IVGLVLVLVA GAVVAGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK GPRV*

>P1;SLA-2_w09an02
SLA-2_w09an02, 180 bases, 30D8B1CA checksum.
 ALALTGTQAG PHSLSYFYTA VSRPDLGDSR FLTVGYVDDT QFVRFDNYAP
 NPRMEPRAPW IQQEGQEYWD RETRKVKETA QTYRVGLNTL RGYYNQSEAG
 SHTIQSMFGC DVGPDGLFLH GYHQDAYDGA DYIALNEDLR SWTAADMAAQ
 ITKRKREAAN VAEHWRSYLQ GLCVEGLRKY*

>P1;SLA-2_w09pt22
SLA-2_w09pt22, 363 bases, 65957E74 checksum.
 MRVRGPQAIL ILLSGALALT GTQAGSHSLS YFHTAVSRPD RGDSRFIAVG
 YVDDTQFVRF DNYAPNPRME PRAPWIQQEG QDYWDRETQI SKDNAQIYRV
 GLNNLRGYYN QSEAGSHTIQ SMYGCDVGPD GLFLHGYHQD AYDGADYIAL
 NEDLRSWTAA DMAAQISKRK REAADVAEHW RSYLQGRCVE GLRRYLQMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWEP
 PQPPVPIVGI IVGLVFVVGT MVAGVVIWWK KRSGEKGGSY TQAAGSDSAQ
 GSDVSLTKGP RVX*

>P1;SLA-2_w09sn01
SLA-2_w09sn01, 365 bases, 926B962A checksum.
 MRVRGPQAIL ILLSGALALT GTQAGPHSLS YFYTAVSRPD LGDSRFLTVG
 YVDDTQFVRF DNYAPNPRME PRAPWIQQEG QEYWDRETRK VKETAQTYRV
 GLNTLRGYYN QSEAGSHTIQ SMFGCDVGPD GLFLHGYHQD AYDGADYIAL
 NEDLRSWTAA DMAAQITKRK WEAADAAEHW RSYLQGLCVE GLRKYLQMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWEP
 PQPPVPIVGI IVGLVLVLVA GAMVAGVVIW RKKRPGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

>P1;SLA-2_w13sm20
SLA-2_w13sm20, 365 bases, 618E1DE9 checksum.
 MRVRGPQAIL ILLSGALALT GTWAGPHSLS YFYTAVSRPD RGDSRFIAVG
 YVDDTQFVRF DSDAPNPRME PRAPWIEQEG QGYWDRETRN VMGSAQTYRV
 NLNTLRGYYN QSEAGSHTIQ IMYGCDVGPD GLLLRGYRQD AYDGADYIAL
 NEDLRSWTAA DMAAQITKRK WEAADVAEGE RSYLQGRCVE WLQKYLEMGK
 DTLQRAEPPK THVTRHPSSD LGVTLRCWAL GFYPKEISLT WQREGQDQSQ
 DMELVETRPS GDGTFQKWAA LVVPPGEEQS YTCHVQHEGL QEPLTLRWDP
 PQPPVPIVGI IVGLVLLLVA VAMVTGVVIW RKKRSGEKGG SYTQAAGSDS
 AQGSDVSLTK DPRVX*

