>DL;SLA-6_0101
SLA-6_0101, 1110 bases, 84DB482D checksum.
 ATGCAGGTCA CGGAGCCTCG AACCCTCCTG CTGGTGCTCT CGGGGTCCCT
 GGCCCTGACC GAGACCTGGG CAGGCCACCT TCACCACGGA CCCAAGGACC
 CGCGTCTGGA GAAGGGTCAG ACCCGGCCTC AGCCCCTCCC TGTTATAGGA
 TCCCACTCGC TAAGATACCT CCATATTTTG GTATCCCGGC CCGGCCACGG
 TAGTGACCTT TACAGCTCTG TCGGTTTCTT GGACGACACG CAGTTCGTAC
 GGTTCAGCAG CGATGCCGCG AATCCAAGGG TGGAGCCTCG GGCGCCGTGG
 ATGGAGCAGG AGGGGCGGGA ATATTGGGAT CGTCAGACTG ATATAGCCAA
 AGAACATTCG AAGGCTTCAA GATCGAACCT GCGGGTGATC ATTGGCAACC
 ACAACCATAG CCAGTCGGAG TCGCACAGCT TTCTTTGGGT ATCCGGCTGC
 GACGTGGGAT CCGACGGGCG CATCCTTCGA GGGTACGAGC AGTTCTCCTA
 CGACGGCGAC GATTACATCG TCCTGAATGA AGACCTGCGC TCCTGGACCG
 CGATCAGTAC AGTGGCTCAG ATCATCCGGC GCAAGTGGGA GGCGGAGGGA
 GTAGCTGAAC AGTATCGGGC ATACTTGGAG ATCGAGTGTG TGGAGTGGCT
 CCGCAAGTAC CTCGAGAAGG GGAAGGACGT GCTGCAGCGC GCAGTTCCTC
 CAAAGACTCA TGTGACCCGC CACCCCTTCT ATGACAATAA AGTCACTCTA
 AGATGCTGGG CCCTGGGCTT CTACCCTAAG GAGATCTCCC TGACCTGGCA
 GCGTGATGGG GAGGACCAGA CCCAGGACAT GGAGCTCGTG GAGACCAGGC
 CTTCAGGGGA TGGGACCTTC CAGAAGTGGG CGGCCCTGGT GGTGCCTTCT
 GGAGAGGAGC AGAGCTACAC CTGCCAGGTG CAGCACGAGG GCCTGCAGGA
 GCCCCTCACC CTGAGATGGG AGCCACCTCC TCTGTCCCTC AACCTCATCA
 TGATTTGCAT TCCTGTGAGT GTGCTTGTGG TCACTGTGCT TGGAACTGTG
 ATCTGGAGAA AGAGGAACTC AGGTGGAAAT AGAGGGAACT ATGTTCAGGC
 TGCAAGCTGA*

>DL;SLA-6_0102
SLA-6_0102, 1110 bases, E7AD43A7 checksum.
 ATGCAGGTCA CGGAGCCTCG AACCCTCCTG CTGGTGCTCT CGGGGTCCCT
 GGCCCTGACC GAGACCTGGG CAGGCCACCT TCACCACGGA CCCAAGGACC
 CGCGTCTGGA GAAGGGTCAG ACCCGGCCTC AGCCCCTCCC TGTTATAGGA
 TCCCACTCGC TAAGATACCT CCATATTTTG GTATCCCGGC CCGGCCACGG
 TAGTGACCTT TACAGCTCTG TCGGTTTCTT GGACGACACG CAGTTCGTAC
 GGTTCAGCAG CGATGCCGCG AATCCAAGGG TGGAGCCTCG GGCGCCGTGG
 ATGGAGCAGG AGGGGCGGGA ATATTGGGAT CGTCAGACTG ATATAGCCAA
 AGAACATTCG AAGGCTTCAA GATCGAACCT GCGGGTGATC ATTGGCAACC
 ACAACCATAG CCAGTCGGAG TCGCACAGCT TTCTTTGGGT ATCCGGCTGC
 GACGTGGGAT CCGACGGGCG CATCCTTCGA GGGTACGAGC AGTTCTCCTA
 CGACGGCGAC GATTACATCG TCCTGAATGA AGACCTGCGC TCCTGGACCG
 CGATCAGTAC AGTGGCTCAG ATCATCCGGC GCAAGTGGGA GGCGGAGGGA
 GTAGCTGAAC AGTATCGGGC ATACTTGGAG ATCGAGTGTG TGGAGTGGCT
 CCGCAAGTAC CTCGAGAAGG GGAAGGACGT GCTGCAGCGC GCAGTTCCTC
 CAAAGACTCA TGTGACCCGC CACCCCTTCT ATGACAATAA AGTCACTCTA
 AGATGCTGGG CCCTGGGCTT CTACCCTAAG GAGATCTCCC TGACCTGGCA
 GCGTGATGGG GAGGACCAGA CCCAGGACAT GGAGCTCGTG GAGACCAGGC
 CTTCAGGGGA TGGGACCTTC CAGAAGTGGG CGGCCCTGGT GGTGCCTTCT
 GGAGAGGAGC AGAGCTACAC CTGCCAGGTG CAGCACGAGG GCCTGCAGGA
 GCCCCTCACC CTGAGATGGG AGCCACCTCC TCTGTCCCTC AACCTCATCA
 TGATTTGCAT TGCTGTGAGT GTGCTTGTGG TCACTGTGCT TGGAACTGTG
 ATCTGGAGAA AGAGGAACTC AGGTGGAAAT AGAGGGAACT ATGTTCAGGC
 TGCAAGCTGA*

>DL;SLA-6_0103
SLA-6_0103, 1110 bases, DE4B48DB checksum.
 ATGCAGGTCA CGGAGCCTCG AACCCTCCTG CTGGTGCTCT CGGGGTCCCT
 GGCCCTGACC GAGACCTGGG CAGGCCACCT TCACCACGGA CCCAAGGACC
 CGCGTCTGGA GAAGGGTCAG ACCCGGCCTC AGCCCCTCCC TGTTATAGGA
 TCCCACTCGC TAAGATACCT CCATATTTTG GTATCCCGGC CCGGCCACGG
 TAGTGACCTT TACAGCTCTG TCGGTTTCTT GGACGACACG CAGTTCGTAC
 GGTTCAGCAG CGATGCCGCG AATCCAAGGG TGGAGCCTCG GGCGCCGTGG
 ATGGAGCAGG AGGGGCGGGA ATATTGGGAT CGTCAGACTG ATATAGCCAA
 AGAACATTCG AAGGCTTCAA GATCGAACCT GCGGGTGATC ATTGGCAACC
 ACAACCATAG CCAGTCGGAG TCGCACAGCT TTCTTTGGGT ATCCGGCTGC
 GACGTGGGAT CCGACGGGCG CATCCTTCGA GGGTACGAGC AGTTCTCCTA
 CGACGGCGAC GATTACATCG TCCTGAATGA AGACCTGCGC TCCTGGACCG
 CGATCAGTAC AGTGGCTCAG ATCATCCGGC GCAAGTGGGA GGCGGAGGGA
 GTAGCTGAAC AGTATCGGGC ATACTTGGAG ATCGAGTGTG TGGAGTGGCT
 CCGCAAGTAC CTCGAGAAGG GGAAGGACGT GCTGCAGCGC GCAGTTCCTC
 CAAAGACTCA TGTGACCCGC CACCCCTTCT ATGACAATAA AGTCACTCTA
 AGATGCTGGG CCCTGGGCTT CTACCCTAAG GATATCTCCC TGACCTGGCA
 GCGTGATGGG GAGGACCAGA CCCAGGACAT GGAGCTCGTG GAGACCAGGC
 CTTCAGGGGA TGGGACCTTC CAGAAGTGGG CGGCCCTGGT GGTGCCTTCT
 GGAGAGGAGC AGAGCTACAC CTGCCAGGTG CAGCACGAGG GCCTGCAGGA
 GCCCCTCACC CTGAGATGGG AGCCACCTCC TCTGTCCCTC AACCTCATCA
 TGATTTGCAT TGCTGTGAGT GTGCTTGTGG TCACTGTGCT TGGAACTGTG
 ATCTGGAGAA AGAGGAACTC AGGTGGAAAT AGAGGGAACT ATGTTCAGGC
 TGCAAGCTGA*

>DL;SLA-6_0104
SLA-6_0104, 1110 bases, 47C6957E checksum.
 ATGCAGGTCA CGGAGCCTCG AACCCTCCTG CTGGTGCTCT CGGGGTCCCT
 GGCCCTGACC GAGACCTGGG CAGGCCACCT TCACCACGGA CCCAAGGACC
 CGCGTCTGGA GAAGGGTCAG ACCCGGCCTC AGCCCCTCCC TGTTATAGGA
 TCCCACTCGC TAAGATACCT CCATATTTTG GTATCCCGGC CCGGCCACGG
 TAGTGACCTT TACAGCTCTG TCGGTTTCTT GGACGACACG CAGTTCGTAC
 GGTTCAGCAG CGATGCCGCG AATCCAAGGG TGGAGCCTCG GGCGCCGTGG
 ATGGAGCAGG AGGGGCGGGA ATATTGGGAT CGTCAGACTG ATATAGCCAA
 AGAACATTCG AAGGCTTCAA GATCGAACCT GCGGGTGATC ATTGGCAACC
 ACAACCATAG CCAGTCGGAG TCGCACAGCT TTCTTTGGGT ATCCGGCTGC
 GACGTGGGAT CCGACGGGCG CATCCTTCGA GGGTACGAGC AGTTCTCCTA
 CGACGGCGAC GATTACATCG TCCTGAATGA AGACCTGCGC TCCTGGACCG
 CGATCAGTAC AGTGGCTCAG ATCATCCGGC GCAAGTGGGA GGCGGAGGGA
 GTAGCTGAAC AGTATCGGGC ATACTTGGAG ATCGAGTGTG TGGAGTGGCT
 CCGCAAGTAC CTCGAGAAGG GGAAGGACGT GCTGCAGCGC GCAGTTCCTC
 CAAAGACTCA TGTGACCCGC CACCCCTTCT ATGACAATAA AGTCACTCTA
 AGATGCTGGG CCCTGGGCTT CTACCCTAAG GAGATCTCCC TGACCTGGCA
 GCAGGAGGGG CAGGACCAGA CCCAGGACAT GGAGCTCGTG GAGACCAGGC
 CTTCAGGGGA TGGGACCTTC CAGAAGTGGG CGGCCCTGGT GGTGCCTTCT
 GGAGAGGAGC AGAGCTACAC CTGCCAGGTG CAGCACGAGG GCCTGCAGGA
 GCCCCTCACC CTGAGATGGG AGCCACCTCC TCTGTCCCTC AACCTCATCA
 TGATTTGCAT TGCTGTGAGT GTGCTTGTGG TCACTGTGCT TGGAACTGTG
 ATCTGGAGAA AGAGGAACTC AGGTGGAAAT AGAGGGAACT ATGTTCAGGC
 TGCAAGCTGA*

>DL;SLA-6_0105
SLA-6_0105, 1110 bases, 7C402C70 checksum.
 ATGCAGGTCA CGGAGCCTCG AACCCTCCTG CTGGTGCTCT CGGGGTCCCT
 GGCCCTGACC GAGACCTGGG CAGGCCACCT TCACCACGGA CCCAAGGACC
 CGCGTCTGGA GAAGGGTCAG ACCCGGCCTC AGCCCCTCCC TGTTATAGGA
 TCCCACTCGC TAAGATACCT CCATATTTTG GTATCCCGGC CCGGCCACGG
 TAGTGACCTT TACAGCTCTG TCGGTTTCTT GGACGACACG CAGTTCGTAC
 GGTTCAGCAG CGATGCCGCG AATCCAAGGG TGGAGCCTCG GGCGCCGTGG
 ATGGAGCAGG AGGGGCGGGA ATATTGGGAT CGTCAGACTG ATATAGCCAA
 AGAACATTCG AAGGCTTCAA GATCGAACCT GCGGGTGATC ATTGGCAACC
 ACAACCATAG CCAGTCGGAG TCGCACAGCT TTCTTTGGGT ATCCGGCTGC
 GACGTGGGAT CCGACGGGCG CATCCTTCGA GGGTACGAGC AGTTCTCCTA
 CGACGGCGAC GATTACATCG TCCTGAATGA AGACCTGCGC TCCTGGACCG
 CGATCAGTAC AGTGGCTCAG ATCATCCGGC GCAAGTGGGA GGCGGAGGGA
 GTAGCTGAAC AGTATCGGGC ATACTTGGAG ATCGAGTGTG TGGAGTGGCT
 CCGCAAGTAC CTCGAGAAGG GGAAGGACGT GCTGCAGCGC GCAGTTCCTC
 CAAAGACTCA TGTGACCCGC CACCCCTTCT ATGACAATAA AGTCACTCTA
 AGATGCTGGG CCCTGGGCTT CTACCCTAAG GAGATCTCCC TGACCTGGCA
 GCGTGATGGG GAGGACCAGA CCCAGGACAT GGAGCTCGTG GAGACCAGGC
 CTTCAGGGGA TGGGACCTTC CAGAAGTGGG CGGCCCTGGT GGTGCCTTCT
 GGAGAGGAGC AGAGCTACAC CTGCCATGTG CAGCACGAGG GCCTGCAGGA
 GCCCCTCACC CTGAGATGGG AGCCACCTCC TCTGTCCCTC AACCTCATCA
 TGATTTGCAT TGCTGTGAGT GTGCTTGTGG TCACTGTGCT TGGAACTGTG
 ATCTGGAGAA AGAGGAACTC AGGTGGAAAT AGAGGGAACT ATGTTCAGGC
 TGCAAGCTGA*

>DL;SLA-6_01we01
SLA-6_01we01, 1110 bases, F6DD0749 checksum.
 ATGCAGGTCA CGGAGCCTCG AACCCTCCTG CTGGTGCTCT CGGGGTCCCT
 GGCCCTGACC GAGACCTGGG CAGGCCACCT TCACCACGGA CCCAAGGACC
 CGCGTCTGGA GAAGGGTCAG ACCCGGCCTC AGCCCCTCCC TGTTATAGGA
 TCCCACTCGC TAAGATACCT CCATATTTTG GTATCCCGGC CCGGCCACGG
 TAGTGACCTT TACAGCTCTG TCGGTTTCTT GGACGACACG CAGTTCGTAC
 GGTTCAGCAG CGATGCCGCG AATCCAAGGG TGGAGCCTCG GGCGCCGTGG
 ATGGAGCAGG AGGGGCGGGA ATATTGGGAT CGTCAGACTG ATATAGCCAA
 AGAACATTCG AAGGCTTCAA GATCGAACCT GCGGGTGATC ATTGGCAACC
 ACAACCATAG CCAGTCGGAG TCGCACAGCT TTCTTTGGGT ATCCGGCTGC
 GACGTGGGAT CCGACGGGCG CATCCTTCGA GGGTACGAGC AGTTCTCCTA
 CGACGGCGAC GATTACATCG TCCTGAATGA AGACCTGCGC TCCTGGACCG
 CGATCAGTAC AGTGGCTCAG ATCATCCGGC GCAAGTGGGA GGCGGAGGGA
 GTAGCTGAAC AGTATCGGGC ATACTTGGAG ATCGAGTGTG TGGAGTGGCT
 CCGCAAGTAC CTCGAGAAGG GGAAGGACGT GCTGCAGCGC GCAGTTCCTC
 CAAAGACTCA TGTGACCCGC CACCCCTTCT ATGACAATAA AGTCACTCTA
 AGATGCTGGG CCCTGGGCTT CTACCCTAAG GAGATCTCCC TGACCTGGCA
 GCGTGATGGG GAGGACCAGA CCCAGGACAT GGAGCTCGTG GAGACCAGGC
 CTTCAGGGGA TGGGACCTTC CAGAAGTGGG CGGCCCTGGT GGTGCCTTCT
 GGAGAGGAGC AGAGCTACAC CTGCCAGGTG CAGCACGAGG GCCTGCAGGA
 GCCCCTCACC CTGAGATGGG AGTCACCTCC TCTGTCCCTC AACCTCATCA
 TGATTTGCAT TGCTGTGAGT GTGCTTGTGG TCACTGTGCT TGGAACTGTG
 ATCTGGAGAA AGAGGAACTC AGGTGGAAAT AGAGGGAACT ATGTTCAGGC
 TGCAAGCTGA*

>DL;SLA-6_w02sa01
SLA-6_w02sa01, 1110 bases, EA023C2A checksum.
 ATGCAGGTCA CGGAGCCTCG AACCCTCCTG CTGGTGCTCT CGGGGTCCCT
 GGCCCTGACC GAGACCTGGG CAGGCCACCT TCACCACGGA CCCAAGGACC
 CGCGTCTGGA GAAGGGTCAG ACCCGGCCTC AGCCCCTCCC TGTTATAGGA
 TCCCACTCGC TAAGATACCT CCATATTTTG GTATCCCGGC CCGGCCACGG
 TAGTGACCTT TACAGCTCTG TCGGTTTCTT GGACGACACG CAGTTCGTAC
 GGTTCAGCAG CGATGCCGCG AATCCAAGGG TGGAGCCTCG GGCGCCGTGG
 ATGGAGCAGG AGGGGCGGGA ATATTGGGAT CGTCAGACTG ATATAGCCAA
 AGAACATTCG AAGGCTTCAA GATCGAACCT GCGGGTGATC ATTGGCAACC
 ACAACCATAG CCAGTCGGAG TCGCACAGCT TTCTTTGGGT ATCCGGCTGC
 GACGTGGGAT CCGACGGGCG CATCCTTCGA GGGTACGAGC AGTTCTCCTA
 CGACGGCGAC GATTACATCG TCCTGAATGA AGACCTGCGC TCCTGGACCG
 CGATCAGTAC AGTGGCTCAG ATCATCCGGC GCAAGTGGGA GGCGGAGGGA
 GTAGCTGAAC AGTATCGGGC ATACTTGGAG ATCGAGTGTG TGGAGTGGCT
 CCGCAAGTAC CTCGAGAAGG GGAAGGACAT GCTGCAGCGC GCAGTTCCTC
 CAAAGACTCA TGTGACCCGC CACCCCTTCT ATGACAATAA AGTCACTCTA
 AGATGCTGGG CCCTGGGCTT CTACCCTAAG GAGATCTCCC TGACCTGGCA
 GCGTGATGGG GAGGACCAGA CCCAGGACAT GGAGCTCGTG GAGACCAGGC
 CTTCAGGGGA TGGGACCTTC CAGAAGTGGG CGGCCCTGGT GGTGCCTTCT
 GGAGAGGAGC AGAGCTACAC CTGCCAGGTG CAGCACGAGG GCCTGCAGGA
 GCCCCTCACC CTGAGATGGG AGCCACCTCC TCTGTCCCTC AACCTCATCA
 TGATTTGCAT TGCTGTGAGT GTGCTTGTGG TCACTGTGCT TGGAACTGTG
 ATCTGGAGAA AGAGGAACTC AGGTGGAAAT AGAGGGAACT ATGTTCAGGC
 TGCAAGCTGA*

>DL;SLA-6_w03sy01
SLA-6_w03sy01, 1110 bases, 9C8BB101 checksum.
 ATGCAGGTCA CGGAGCCTCG AACCCTCCTG CTGGTGCTCT CGGGGTCCCT
 GGCCCTGACC GAGACCTGGG CAGGCCACCT TCACCACGGA CCCAAGGACC
 CGCGTCTGGA GAAGGGTCAG ACCCGGCCTC AGCCCCTCCC TGTTATAGGA
 TCCCACTCGC TAAGATACCT CCATATTTTG GTATCCCGGC CCGGCCACGG
 TAGTGACCTT TACAGCTCTG TCGGTTTCTT GGACGACACG CAGTTCGTAC
 GGTTCAGCAG CGATGCCGCG AATCCAAGGG TGGAGCCTCG GGCGCCGTGG
 ATGGAGCAGG AGGGGCGGGA ATATTGGGAT CGTCAGACTG ATATAGCCAA
 AGAACATTCG AAGGCTTCAA GATCGAACCT GCGGGTGATC ATTGGCAACC
 ACAACCATAG CCAGTCGGAG TCGCACAGCT TTCTTTGGGT ATCCGGCTGC
 GACGTGGGAT CCGAAGGGCG CATCCTTCGA GGGTACGAGC AGTTCTCCTA
 CGACGGCGAC GATTACATCG TCCTGAATGA AGACCTGCGC TCCTGGACCG
 CGATCAGTAC AGTGGCTCAG ATCATCCGGC GCAAGTGGGA GGCGGAGGGA
 GTAGCTGAAC AGTATCGGGC ATACTTGGAG ATCGAGTGTG TGGAGTGGCT
 CCGCAAGTAC CTCGAGAAGG GGAAGGACGT GCTGCAGCGC GCAGTTCCTC
 CAAAGACTCA TGTGACCCGC CACCCCTTCT ATGACAATAA AGTCACTCTA
 AGATGCTGGG CCCTGGGCTT CTACCCTAAG GAGATCTCCC TGACCTGGCA
 GCGTGATGGG GAGGACCAGA CCCAGGACAT GGAGCTCGTG GAGACCAGGC
 CTTCAGGGGA TGGGACCTTC CAGAAGTGGG CGGCCCTGGT GGTGCCTTCT
 GGAGAGGAGC AGAGCTACAC CTGCCAGGTG CAGCACGAGG GCCTGCAGGA
 GCCCCTCACC CTGAGATGGG AGCCACCTCC TCTGTCCCTC AACCTCATCA
 TGATTTGCAT TGCTGTGAGT GTGCTTGTGG TCACTGTGCT TGGAACTGTG
 ATCTGGAGAA AGAGGAACTC AGGTGGAAAT AGAGGGAACT ATGTTCAGGC
 TGCAAGCTGA*

>DL;SLA-6_w04jh01
SLA-6_w04jh01, 1110 bases, B7608C16 checksum.
 ATGCAGGTCA CGGAGCCTCG AACCCTCCTG CTGGTGCTCT CGGGGTCCCT
 GGCCCTGACC GAGACCTGGG CAGGCCACCT TCACCACGGA CCCAAGGACC
 CGCGTCTGGA GAAGGGTCAG ACCCGGCCTC AGCCCCTCCC TGTTATAGGA
 TCCCACTCGC TAAGATACCT CCATATTTTG GTATCCCGGC CCGGCCACGG
 TAGTGACGTT TACAGCTCTG TCGGTTTCTT GGACGACACG CAGTTCGTAC
 GGTTCAGCAG CGATGCCGCG AATCCAAGGG TGGAGCCTCG GGCGCCGTGG
 ATGGAGCAGG AGGGGCGGGA ATATTGGGAT CGTCAGACTG ATATAGCCAA
 AGAACATTCG AAGGCTTCAA GATCGAACCT GCGGGTGATC ATTGGCAACC
 ACAACCATAG CCAGTCGGAG TCGCACAGCT TTCTTTGGGT ATCCGGCTGC
 GACGTGGGAT CCGACGGACG CATCCTTCGA GGGTACGAGC AGTTCTCCTA
 CGACGGCGAC GATTACATCG TCCTGAATGA AGACCTGCGC TCCTGGACCG
 CGATCAGTAC AGTGGCTCAG ATCATCCGGC GCAAGTGGGA GGCGGAGGGA
 GTAGCTGAAC AGTATCGGGC ATACTTGGAG ATCGAGTGTG TGGAGTGGCT
 CCGCAAGTAC CTCGAGAAGG GGAAGGACGT GCTGCAGCGC TCAGTTCCTC
 CAAAGACTCA TGTGACCCGC CACCCCTTCT ATGACAATAA AGTCACTCTA
 AGATGCTGGG CCCTAGGCTT CTACCCTAAG GAGATCTCCC TGACCTGGCA
 GCGTGATGGG GAGGACCAGA CCCAGGACAT GGAGCTCGTG GAGACCAGGC
 CTTCAGGGGA TGGGACCTTC CAGAAGTGGG CGGCCCTGGT GGTGCCTTCT
 GGAGAGGAGC AGAGCTACAC CTGCCAGGTG CAGCACGAGG GCCTGCAGGA
 GCCCCTCACC CTGAGATGGG AGCCACCTCC TCTGTCCCTC AACCTCATCA
 TGATTTGCAT TGCTGTGAGT GTGCTTGTGG TCACTGTGCT TGGAACTGTG
 ATCTGGAGAA AGAGGAACTC AGGTGGAAAT AGAGGGAACT ATGTTCAGGC
 TGCAAGCTGA*

