>DL;RT1-DMb_a
RT1-DMb_a  786 bases  
 ATGGCTGCAC TATGGCCGCT GCTGCTGGCC CTAGGTCTGG GCTGTATAGG
 AGCAGGTGGC TTTGTGGCTC ACGTGGAAAG CACGTGCTTG CTGGATGATG
 AAGGGACCCC AATGGACTTC ACATACTGTA TTTCCTTCAA CAAAGATCTG
 CTGGCCTGCT GGGATCCAGA GGAGGGACAA ATAGTCCCCT GTGAATATGG
 GGTCCTGTTT AAGTTGGCCG AATTCATTTC AAATATCCTC AACAAGGAAG
 AAGGCCTGAT CCAGCGCTTG AAAAATGGGC TTCAGGACTG TTCCACGCAC
 ACCCAGCCCT TCTGGAACGC GCTGACCCAC AGAACCAGAA CGCCATCTGT
 CCAAGTAGCC CAAACCGCTC CTTTTAACAC AAGGGAGCCT GTGATGCTGG
 CCTGCTACGT CTGGGGCTTC TATCCGGCGG ATGTGACCGT GGTGTGGATG
 AAGAACGGGC AGCTTGTTAC TTCCCACAGC AACAAGGAGA AGACGGCTCA
 GCCTAACGGG GACTGGACAT ACCAGACCGT CTCCTACCTA GCCTTAACCC
 CTTCCTACTG GGACATCTAC ACCTGCGTGG TACAGCACAG CGGGACCCCT
 GAGCCCATCC GCGCGAACTG GACACCCGGG CTGTCCCCCA TCCAGACAGT
 GAAGGTCTCT GTGTCTGCAG CCACCCTGGG CCTGGGCTTC ATCATCTTCT
 GTCTTGGCTT CTTCAGATGG CGCAAGTCTC ACTCCTCCAG CTACACTCCT
 CTCCCTGGAT CCACCTACCC GGAAGGACGG CCCTAG*

>DL;RT1-DMb_n
RT1-DMb_n  786 bases  
 ATGGCTGCAC TATGGCCGCT GCTGCTGGCC CTGAGTCTGG GTTGTATAGG
 AGCAGGTGGC TTTGTGGCTC ATGTGGAAAG CACGTGCTTG CTGGATGATG
 AAGGGACCCC AATGGACTTC ACATACTGTA TTTCCTTCAA CAAAGATCTG
 CTGGCCTGCT GGGATCCAGA GGAGGGACAA ATAGTCCCCT GTGAATATGG
 GGTCCTGTTT AAGTTGGCCG AATTCATTTC AAATATCCTC AACAAGGAAG
 AAGGCCTGAT CCAGCGCTTG AAAAATGGGC TTCAGGACTG TTCCACACAC
 ACCCAGCCCT TCTGGAACGC GCTGACCCAC AGAACCAGAA CGCCATCTGT
 CCAAGTAGCC CAAACCGCTC CTTTTAACAC AAGGGAGCCT GTGATGCTGG
 CCTGCTACGT CTGGGGCTTC TATCCGGCGG ATGTGACCGT CGTGTGGATG
 AAGAACGGGC AGCTTGTTAC TTCCCACAGC AACAAGGAGA AGACGGCTCA
 GCCTAATGGG GACTGGACAT ACCAGACCGT CTCCTACCTA GCCTTAACCC
 CTTCCTACTG GGACATCTAC ACCTGCGTGG TACAGCACAG CGGGACCCCT
 GAGCCCATCC GCGCGAACTG GACACCCGGG CTGTCCCCCA TCCAGACAGT
 GAAGGTCTCT GTGTCTGCAG CCACCCTGGG CCTGGGCTTC ATCATCTTCT
 GTCTTGGCTT CTTCAGATGG CGCAAGTCTC ACTCCTCCAG CTACACTCCT
 CTCCCTGGAT CCACCTACCC GGAAGGACGG CCCTAG*

