>P1;RT1-M1-2_n
RT1-M1-2_n  189 bases  
 MKVLLVLAVL LLMVTLVITK NPKGSHSLRY LQTLLSWPGL AEPQFIFVGY
 VGNTQFIGFN SRSQSQWSLH RAPWKDQQTP EYWEKTIQEV LSEKRNLKEV
 MEKMLHIYPN STTGNHTIQM RYGCDVLPGG YFSHGILELN FDSQDYIILN
 DELHNWIIDG KAAEMLKQEW EDTLCTNCEE LPEGIMCGX*

>P1;RT1-M1-4_n
RT1-M1-4_n  209 bases  
 MKTFVTEALL LLLLAVLALA SHPEGSHLFG LFQTLLTRPG HSEPLFISAG
 FMDNIQFERF NNRSDFPGME HCAPWIDHRS PEYWKEHTQR ALKDIRFMRQ
 ALKLMIHTYN YSATGYHTIQ RRIGCHVLPR GYFSHGFLEL AFNGQDYIML
 NEDLRTWTTV GKAAEILRKE WETQFCTSHE DLFGGFMCGL ISHRAGLWEG
 DFAENRSPX*

>P1;RT1-M1-5_n
RT1-M1-5_n  175 bases  
 METSAILTLH LLLSASLALT QSFKGSHSLR YFDIAVSRPG LEETHYMTLG
 YVDDTEFVHF NNEAVNPRFE PRVPWMEQMG QKYWDDQTRI AKVAEQQIRV
 YFQKLRGYYN QSQNSSHTIQ RMTGCYIGPD GHLLHAYRQF GYDGQDYLTL
 NEDLSTWTAA DSAAEITHRE WKATX*

