>P1;RT1-M3-1_av1
RT1-M3-1_av1  340 bases  
 MATSNKFSLL LMVVVALAVS RTGAGTHSLR YFHTALSRPG RGEPQYISVG
 YVDDKLFQRC DSVEEIPRME ARAPWMEKEG PEYWEELKLK VKSIAQRARA
 RLRTLIRYYN QSEGGSHILQ WMVACEVGPD MRLLGAHYQA AYDGSDYITL
 NEDLSSWTAA DMVAQITKSE LESEGRAEYF RAYVDGECLE LLHRFLQNGK
 EILQRADPPK AHVTLHPRPE GDVTLRCWAL GFYPADITLT WQLNGEDLTQ
 DMELVETRPS GDGTFQKWAS VVVPSGEEQK YTCHVEHEGL PEPLVLKWGG
 SSQSFVVIMV IIVIIVILAL LGGVLTVVLV YRRRGAGMLX*

>P1;RT1-M3-1_n
RT1-M3-1_n  340 bases  
 MATSNKFSLL LMVVVALAVS RTGAGTHSLR YFHTALSRPG RGEPQYISVG
 YVDDKLFQRC DSVEEIPRME ARAPWMEKEG PEYWEELKLK VKSIAQRARA
 RLRTLIRYYN QSEGSSHILQ WMVACEVGPD MRLLGAHYQA AYDGSDYITL
 NEDLSSWTAA DMVAQITKSE LESEGRAEYF RAYVDGECLE LLHRFLQNGK
 EILQRADPPK AHVTLHPRPE GDVTLRCWAL GFYPADITLT WQLNGEDLTQ
 DMELVETKPS GDGTFQKWAS VVVPSGEEQK YTCHVEHEGL PEPLVLKWGG
 SSQSFVVIMV IIVIIVILAL LGGVLTVVLV YRRRGAGERX*

