>P1;RT1-Bb_l
RT1-Bb_l  264 bases  
 MALQTPSFLL PAAVVVLMVL SSPGTEGRDS PRDFVYQFKG LCYYTNGTQR
 IRDVIRYIYN QEEYLRYDSD VGEYRALTEL GRPSAEYFNK QYLEQTRAEL
 DTVCRHNYEG SEVRTSLRRL EQPNVAISLS RTEALNHHNL LVCSVTDFYP
 AQIKVRWFRN GQEETAGVVS TQLIRNGDWT FQILVMLEMT PQRGEVYICH
 VDHPSLESPV TVEWRAQSES AQSKMLSGIG GFVLGVIFLG LGLFIRHKRQ
 KGPRGPPPAG LLQX*

>P1;RT1-Bb_n
RT1-Bb_n  235 bases  
 SAGDFVFQFK GLCYYTNGTQ RIRLVIRYIY NREEYVRFDS DVGEFRALTE
 LGRPSAEYYN KQYLERTRAE LDTVCRHNYE ETEVPTSLRR LEQPNVAISL
 SRTEALNHHN LLVCSVTDFY PAQIKVRWFR NGQEETAGVV STQLIRNGDW
 TFQILVMLEM TPQRGEVYIC HVDHPSLESP VTVEWRAQSE SAQSKMLSGI
 GGFVLGVIFL GLGLFIRHKR QKGPRGPPPA GLLQX*

>P1;RT1-Bb_u
RT1-Bb_u  245 bases  
 LMVLSSPGTE GRDSRRDFLV QFKPYCYFTN GTQRIRNVIR YIYNREEYLR
 YDSDVGEYRA VTELGRPSAE YFNKQYLERT RAELDTVCRH NYEKTEVPTS
 LRRLEQPNVA ISLSRTEALN HHNLLVCSVT DFYPAQIKVR WFRNGQEEMA
 GVVSTQLIRN GDWTFQILVM LEMTPQRGDV YTCRVDHPSL DSPVTVEWRA
 QSESAQSKML SGIGGLVLGV IFLGLGLFIH YKSQKGPQGP PPARS*

