>P1;RT1-119_l
RT1-119_l  344 bases  
 MGAKAPQALL LLVAVALAPT QTRAGSHSLR YFETAVSRPG LGEPRFISVG
 YVDDTEFVRY DSNAENPRYE PRARWIEWEK PDYWETQTRR AKGNEQIYRG
 SLTTLLHYYN QSEDGSHTIQ WMYGCDVGSD GSLLRGYWQH AYDGRDYLAL
 NEDLKTWEAS DRAAQKTRNK WERKGVAERS RAYLKGTCVE SLRRYLELRK
 ETLLRSDPPK VRVTLHPRPE GDVTLRCWAL GFYPADITLT WQLNGEDLTQ
 DMELVETRPA GDGTFQKWAS VVVPLGKEQS YTCLVEHEGL PEPLTQRWEP
 PPSTDSNMGI IAVLAVVGAV AVIVLVALIG VVVRRRRKNI GGIX*

>P1;RT1-3_6_av1
RT1-3_6_av1  320 bases  
 MGAMAPRTLL LLLAAVLAPT QTWAGSHSLR YFHTAVSRPG LGEPRFISVG
 YVDDTQFVRY DSDAENPRYE PRARWMEREG PEYWEEQTLV AKGQELDYRV
 SLRNLLSYYN QSEGGSHTIQ RMYGCDVGSD GSLLRGYEQH AYDGRDYIAL
 NEDLKTWAVA DFAAWITRSK WQRNGAAERS RAYLEGTCVE WLLRYLERGK
 ETLLRSDPPE AHVTLHPRPE GDVTLRCWAL GFYPADITLT WQLNGEDLTQ
 DMELVETRPA GDGTFQKWAS VVVPLGKEQN YTCRVEHEGL PEPLSQRWEP
 SPSTDSNLLL LFLELWQFLX*

>P1;RT1-9_5_f
RT1-9_5_f  292 bases  
 GSHSLRYFHT AVSRPGLGEP RFISVGYVDD TQFVRYDSDA ENPRYEPRAR
 WMEREGPEYW EEQTLVAKGQ ELDYRVSLRN LLSYYNQSEG GSHTIQRMYG
 CDVGSDGSLL RGYEQHAYDG RDYIALNEDL KTWAVADFAA WITRSKWQRN
 GAAERSRAYL EGTCVEWLLR YLERGKETLL RSDPPEARVT LHPRPEGDVT
 LRCWALGFYP ADITLTWQLN GEDLTQDMEL VETRPAGDGT FQKWASVVVP
 LGKEQNYTCR VEHEGLPEPL SQRWGRYSSQ SSVVSLPDCE AX*

>P1;RT1-9_6_f
RT1-9_6_f  292 bases  
 GSHSLRYFHT AVSRPGLGEP RFISVGYVDD TQFVRYDSDA ENPRYEPRAR
 WMEREGPEYW EEQTRVAKGQ EQDYRVSLRN LLSYYNQSEG GSHTIQRMYG
 CDVGSDGSLL RGYEQHAYDG RDYIALNEDL KTWAVADFAA WITRSKWQRN
 GAAERSRAYL EGTCVEWLLR YLERGKETLL RSDPPEAHVT LHPRPEGDVT
 LRCWALGFYP ADITLTWQLN GEDLTQDMEL VETRPAGDGT FQKWASVVVP
 LGKEQNYTCL VEHEGLPEPL SQRWGRYSSQ SSVVSLPGCE AX*

>P1;RT1-C113_l
RT1-C113_l  354 bases  
 MAPRTLLLLL AAALAPTQIR AGSHSLRYFY TAMSRPGLGE PRFIEVGYVD
 GTEFVRYDSD AENPRYEPRA RWMEREGTEY WERETRRAKG DEHMFRVSLR
 NLRGYYNQSE GGSHTIQRIY GCVMGSDGIL LRGYWQFAYD GRDYMALNED
 LKTYTAADFA ARITRNKWER VGAAQSQKAY LEGKCMVWLS RHLEQGKETL
 VRSDPPKAHV TLHPRPEGDV TLRCWALGFY PADITLTWQL NGEDLTQDME
 LVETRPSGDG TFQKWAAVVV PLGKEQNYTC LVDHEGLPEP LTLRWEPPPS
 TDFNMVIITV LVVLGAVAII GVVVAVVMKW RNPGGTGGDY APAPARRQLP
 GVDX*

>P1;RT1-CE10_n
RT1-CE10_n  361 bases  
 MEAMARPTLL LLLAAALAPT KTRAGSHWMR YFHTAVSRPG LGEPRYISVG
 YVDDTQFVRF DSDAENPRYE PRARWMEREG PEYWERNTRI VKGKEQIFRD
 NLRTLLGYYN QSEGGSHTLQ LMYGCDVGSD WSLLRGYEQH AYDGRDYIAL
 NEDLKTWAAA DFEAQKTRSK WEREGVAERS RAYLEGECVK WLRRHLEHGK
 EALLRLDPPE AHVTLHPRPE GDVTLRCWAL GFYPADITLT WQLNGEDLTQ
 DMEFVETRPA GDGTFQKWAS VVVPLGKEQN YTCLVEHEGL PEPLTQRWEP
 SPSTNTNMGI DVTSVFLGPL AVFVVLAIIG AAVAVVRRRR RRNTGGEGGD
 YTPAPGRDSS X*

>P1;RT1-CE11_n
RT1-CE11_n  368 bases  
 MGSRAPHTLL LLLVAALAQT QPRAGSHSLW YFTSALSWPG LGEPRFISVR
 YVDDTEFVRF DSGSENPRYE PRAPWMEREG PEYWEQQTRR AKGNQQTFQV
 NLRTALRYYN QSEDRSHTIQ RMYGCDMGSD RSLLRGYEQY AYDGRDYIAL
 NEDLKTWTAA DVAAQITRNK WDQAGVAERR RAYLEGTCVK WLRRYLEHGK
 ETLLRSDPPK AHVTLHPRPE GDVTLRCWAL GFYPADITLT WQLNGEDLTQ
 DMELVETRPA GDGTFQKWAS VVVALGKEQK YTCLVEHEGL PEPLTQRWEA
 PPSTDSNMET NVIYVVVGAL VITGAVIIGA VVAVVRKRNT GGTGGDYAPA
 PGKANPNSSV SLPDCKAX*

>P1;RT1-CE12_n
RT1-CE12_n  372 bases  
 MGVTAPPLLL LLLAAALART QTRAGSHSLR YFKTAVSRPG LGEPRFMEVG
 YVDDTEFVRF DSDAENPRYE PRARWMEQQG PEYWERETQG AKEKEQTFRV
 NLRTLLGYYN QSEGDSHTLQ LMFGCDVGSD GRLLRGYDQF AYDGRDYIAL
 NEDLKTWAAA DVVAQMTRNK WERARYAEKR RANLEGECVE SLRRFLELGK
 ETLLRSDPPK AHVTLHPRPE GDVTLRCWAL GFYPADITLT WQMNGEDLTQ
 DMELVETRPA GDGTFQKWAA VVVPLGKEQN YTCLVEHEGL PEPLTLRWEP
 PSSTNSNMEF NVIYVVLGAI SAVAISGAVI IGAVLAVVRK RNTGGEGGDY
 TPAPDRDSCQ SSNVSLPDCK AX*

>P1;RT1-CE13_n
RT1-CE13_n  366 bases  
 MGAMAPRMLL LLLAAALAPT QTRAGSHSLL YFYTAMSRPG LGEPWFMEVG
 YVDDTEFVRF DNDAENPRME PRARWMEREG PEYWERNTRI AKENEQWSRM
 GLRNLRGYYN QSEGGSHTVQ RLYGCDVGSD GSLLRGYDQF AYDGRDYISL
 NEDLKTWAAA DLAAQKTRNK WDQAGTAERR RAYLEGTCLE WLRRYLELGK
 ETLLRSDPPE AHVTLHPRPE GGVTLRCWAL GFYPPGISLI WQLNGEDLTQ
 DMELVETRPA GDGTFQKWAS VVVPLGKEQN YTCHVEHEGL PEPLTLRWEP
 PSSTDFNMRI IAVLVVLGAV AIIGAVVAVM MKWRRNTGGT GGDYTPAPGK
 ASPNSCDLSL PLCKAX*

>P1;RT1-CE14_n
RT1-CE14_n  351 bases  
 MVPPKLLPLL AAVLAPTQTQ GGECRSHSLR YFKTAVSRPG LGEPRFMEVG
 YVDDTEFVRF DSDAENPRYE PRARWMEQQG PEYWERETQG AKEKEQTFRV
 NLRTLLGYYN QSEGDSHTLQ LMFGCDVGSD GSLLRGYDQF AYDGRDYIAL
 NEDLKTWAAA DVVAQMTRNK WERARYAEKR RANLEGECVE SLRRYLELGK
 ETLLRSDPPK AHVTLHPRPE GDVTLRCWAL GFYPAEITLT WQLNGEDLSQ
 DMELVETRPA GDGTFQKWAS VVVPLGKEQN YTCLVEHEGL PEPLTLRWEL
 PPSTDSNMET NVIYVVFGAV TIIGAVAIIG AVAIIGVCVR RRRRRNIGGI
 X*

>P1;RT1-CE15_n
RT1-CE15_n  374 bases  
 MGAMARRTLL LLLAAALAPT QTLPSSHSMR CFKTAVSRPG LGEPRFIAVA
 YVDDTEFVRY DGDAENPRTE PRARWMEREG PEYWEEETRK IKGQEQWFRM
 SLRILRGYYN QSEGGSHTFQ KMSGCDVGSD GSLLRGYNQY AYDGHDYIAL
 NKDLKTWTAA DFAALITKTK WDQAGTAERK RAYLEGTCVE WLRRYLELGK
 ETLLRSDPPK AHVTLHPRPE GDVTLRCWAL GFYPADITLT WQLNGEDLTQ
 DMELVETRPA GDGTFQKWAA VVVPLGKEQN YTCLVEHEGL PEPLTLRWEA
 PPGTDSNMET KVIYVVLGAV AMIGAVAVIG AVVAVVRRRR RKRNTGGTGG
 DYAPAPGSDS CQSSDVSLAD CEAX*

>P1;RT1-CE16_f
RT1-CE16_f  347 bases  
 GSHSLRYFVT AMSGPGLGKP RFMEVGYVDD TEFVRYDSDA KNPGMEPRAR
 WMEREGREYW ERETRIAKGN EQTFRENLRT LLRYYNQSEG GSHTFQWMSG
 CDVGSDGSLL RGYEQFAYDG RDYIVLNEDL KTWTAADTAA RITRNKWDRA
 GVAERHKAYL EGKCLESLLR YLELGKETLL RSDPPKAHVT LHPRPEGDVT
 LRCWALGFYP AGISLTWQLN GEDLTQDMEL VETRPAGDGT FQKWASVVVP
 LGKEQNYTCL VEHEGLPEPL TQRWEPSPST DSNMETYVIY VILGAVAIIA
 AVIIVAVVAV VMKRRRNTGG KVGVYAPAPS RDSSESSDVS LSDCKAX*

>P1;RT1-CE16_g
RT1-CE16_g  347 bases  
 GSHSLRYFVT AMSGPGLGKP RFMEVGYVDD TEFVRYDSDA KNPGMEPRAR
 WMEREGREYW ERETRIAKGN EQTFRENLRT LLRYYNQSEG GSHTFQWMSG
 CDVGSDGSLL RGYEQHAYDG RDYIVLNEDL KTWTAADTAA RITRNKWDRA
 GVAERHKAYL EGKCLESLLR YLELGKETLL RSDPPKAHVT LHPRPEGDVT
 LRCWALGFYP AGISLTWQLN GEDLTQDMEL VETRPAGDGT FQKWASVVVP
 LGKEQNYTCL VEHEGLPEPL TQRWEPSPST DSNMETYVIY VILGAVAIIA
 AVIIVAVVAV VMKRRRNTGG KVGVYAPAPS RDSSESSDVS LSDCKAX*

>P1;RT1-CE16_n
RT1-CE16_n  371 bases  
 MGAMAPRTLL LLLAAALAPT QTRAGSHSLR YFVTAISGPG LGEPRFMEVG
 YVDGTEFVRY DSDAKNPGME PRARWMEREG REYWERETRR VKENEQLFRG
 NLRTLLGYYN QSEGGSHTIQ WMSGCDVGSD GSLLRGYDQF AYDGRDYIVL
 NEDLKTWTAA DTAARITRNK WDRAGVAERH KAYLEGKCLE SLLRYLELGK
 ETLLRSDPPK AHVTLHPRPE GDVTLRCWAL GFYPAGISLT WQLNGEDLTQ
 DMELVETRPA GDGTFQKWAS VVVPLGKEQN YTCLVEHEGL PEPLTQRWEP
 SPSTDSNMET YVIYVILGAV AIIAAVIIVA VVAVVMKRRR NTGGKVGVYA
 PAPSRDSSES SDVSLSDCKA X*

>P1;RT1-CE1_c
RT1-CE1_c  332 bases  
 GSHSLRYFKT AVSRPGLGEP RFMEVGYVDD TEFVRFDSDA ENPRCEPRAR
 WMERQRPEYW ERETQGAKEK EQTFRVNLRT LLGYYNQSEG DSHTLQLMFG
 CDLGSDGRLL RGYDQFAYDG RDYIALNEDL KTWAAADVVA QMTRNKWERA
 RYAEERRANL EGECVESLRR YLELGKETLL RSDPPKAHVT LHPRPEGDVT
 LRCWALGLYP ADITLTWQLN GEDLTQDMEL VETRPAGDGT FQKWAAVVVP
 LGKEQNYTCH MEHEGLPEPL TLRWEAPPST NSNMEFNVIY VVLGAISAVA
 IIGAVIIGGV LAVVRKRNTG GTGGDYTPAS SM*

>P1;RT1-CE1_n
RT1-CE1_n  375 bases  
 MGVTAPPLLL LLLAAALART QTRAGSHSLR YFKTAVSRPG LGEPRFMEVG
 YVDDTEFVRF DSDAENPRYE PRVRWMERQR PEYWERETQG AKEKEQTFRV
 NLRTLLGYYN QSEGDSHTLQ LMFGCDVGSD GRLLRGYDQF AYDGRDYIAL
 NEDLKTWAAA DVVAQMTRNK WERARYAEKR RANLEGECVE SLRRYLELGK
 ETLLRSDPPK AHVTLHPRPE GDVTLRCWAL GFYPADITLT WQLNGEDLTQ
 DMELVETRPA GDGTFQKWAA VVVPLGKEQN YTCHMEHEGL PEPLTLRWEA
 PPSTNSNMEF NVIYVVLAIS AVAIIGAVII GAVLAVVRKR NTGRKGQGGK
 GDYAPAPDRD SCQSSNVSLP DCKAX*

>P1;RT1-CE2_n
RT1-CE2_n  366 bases  
 MAPRTLLLLL AAALARTQTR EGSHSLRYFK TAVSRPGLGK PLFMEVGYVD
 DTEFVRFDSD AENPRMEPRA RWMEREGPEY WDRETRIAKG NEQRFRVHLR
 TLLGHYNQSE GGSHTFQLMY GCDLGSDGSL LRGYDHYAYD GRDYIALNED
 LKTWTAADAA ARITLNQWHQ TGYAERRRAD LEGECVESLR RYLELGKETL
 LRSDPPKAHV TLHPRPEGDV TLRCWALGFY PADITMTWLL NGEDLSQDME
 LVETRPAGDG TFQKWASVVV PLGKEQNYTC LVEHEGLPEP LSQRWEPSPS
 TDSNMGIDVT SVLPGAVAVF VVLAIIGAVV AIVRRRNTGG KGDYAPAPGR
 DSSQSSDVSF SDCKAX*

>P1;RT1-CE3_n
RT1-CE3_n  353 bases  
 MEVMAPRALL LLLAAALALA QTGIGSHSLR YFETALSRPG FGESRFIIVG
 YVDDTQFMRF DSDAENPRME PRARWMEREG PGYWEQNTRM AKRQEQWYRV
 NLRTALRYYN QSEGGSHTFQ RMYGCDVGSD GSLLRGYNQF AYDSLDYIAL
 NEDLKTWTAA DTTGRMTQSK WVQAGVADYY RAYLEGECVE WLRRYLELGK
 ETLMRSDPPK AHVTLHPRPE GDVTLRCWAL GFYPADITLT WQLNGEDLTQ
 DMELVETRPA GDGTFQKWAS VVVPPGKEQN YTCLVEHEGL PEPLTLRWAP
 SLSTDSNMET TVIYVVLGAI SALAIIGALV PVVRRRKRNT GGKGGVYAPA
 PGX*

>P1;RT1-CE4_n
RT1-CE4_n  374 bases  
 MGAMAPPTLL LLVAAALTPT KTRAGSHSLR YFHTAVSRPG LGEPRFISVG
 YVDDTEFVRY DSDAENPRYE PRARWMEREG PEYWERQTQI AKRNEQVYRV
 DLSTLRGYYN QSEGGSHTYQ RMHGCELGSD GSLLRGYMQY AYDGRDYIAL
 NEDLKTWMVK DTAARITRNK WDQAGFGERK RTYLQVECLE WLRKYLELGK
 ETLLRSDPPK VHVTLHPRPE GGVTLRCWAL GFYPADITLT WQLNGEDLTQ
 DMELVETRPA GDGTFQKWAA VVVPSGEEQK YTCHVEHEGL PEPLTQRWEA
 PPGTDSNMET NVIYVFFGAV AMIGAVAVIG AVVAVVRRRR RRKRNTGGKG
 DYAPAPGSDS CQSSDVSLAD CEAX*

>P1;RT1-CE5_g
RT1-CE5_g  348 bases  
 GSHSLRYFHT AVSRPGLREP RFIIVGYVDH TEFVRYDSDA ENPRYEPRAR
 WMEREGPEYW EQQTQIVKGH EWSFRVSLRN LLGYYNQSEG GSHTLQVMSG
 CDMGSDRSLR RGYEQYAYDG RDYISLNEDL KTWSAADLAA QITLNKWDQA
 GELDYYKAYL EGPCLEWLLR YLEHGKETLM RSDPPEAHVT LHPRPEGDVT
 LRCWALGFYP ADITLTWQLN EEDLTQDMEL VETRPAGDGT FQKWASVVVP
 LGKEQNYTCL VEHEGLPEPL TLRWEAPPST NSNTGMSVIL GTVTIIAVMA
 IIVVVAVIRT VVRKRWIKTG GKGGDYAPAP GRDSCQSSDV SLPDCKAX*

>P1;RT1-CE5_l
RT1-CE5_l  307 bases  
 GSHSLRYFHT AVSRPGLREP RFVIVGYVDH TEFVRYDSDA ENPRYEQRAR
 WMEREGPEYW EQQTQIVKGH EWSFRVSLRN LLGYYNQSEG GSHTLQVMSG
 CDMGSDRSLR RGYEQYAYDG RDYISLNEDL KTWSAADLAA QITLNKWDQA
 GELDYYKTYL EGPCLEWLLR YLEHGKETLM RSDPPKAHVT LHPRHEGDVT
 LRCWALGFYP ADITLTWQLN GEDLTQDMEL VETRPAGDGT FQKWASVVVP
 LGKEQKYTCL VEHEGLPEPL TLRWAFLLTS GKGVYTPAPG RDSSQSSDVS
 LPDCKAX*

>P1;RT1-CE5_n
RT1-CE5_n  371 bases  
 MGAMAPRTLL LLLAAALAPT RTRAGSHSLR YFHTAVSRPG LGEPRFIIVG
 YVDHTEFVRY DSDAENPRYE PRARWMEREG PEYWEQQTQI VKGHEWSFRV
 SLRNLLGYYN QSEGGSHTLQ VMSGCDMGSD QSLRRGYEQY AYDGRDYISL
 NEDLKTWSAA DLAAQITLNK WDQAGELDYY KAYLEGPCLE WLLRYLEHGK
 ETLMRSDPPK AHVTLHPRPE GDVTLRCWAL GFYPADITLT WQLNGEDLTQ
 DMELVETRPA GDGTFQKWAS VVVPLGKEQN YTCLVEHEGL PEPLTFRWEA
 PPSTNSNTGM SVILGTVTII AVMAIIVVVA VIRTVVRKRW IKTGGKGVYT
 PAPGRDSSQS SDVSLPDCKA X*

>P1;RT1-CE7_n
RT1-CE7_n  356 bases  
 MGSRAPHTLL LLLAAALART QPRAGSHSLR YFTTALSRPG LGEPRFISVG
 YVDDTEFVRF DSDAENPRYE PRAPWMEREG LEYWEQQTRR AKGNQQTFQV
 NLRTALHYYN QSEDRSHTIQ RMYGCDVGSD GSLLRGYEQS AYDGRDYIAL
 NEDLKTWTAA DVAAQITRNK WDQAGVAERR RAYLEGTCMK WLRRYLEHGK
 ETLLRSDPPK AHVTLHPRPE GDVTLRCWAL GFYPADITLT WQLNGEDLTQ
 DMELVETRPA GDGTFQKWAS VVVPPGKEQN YTCRVEHEGL PEPLTLRWEA
 PPSTDSNMET NVIYVVIGAI SAVAIIGAVL AVVRKKNTGG TGGDYTPAPG
 QPQQLX*

>P1;RT1-C_l
RT1-C_l  369 bases  
 MAPRTLLLLL AAALAPTQVR AGSHSLRYFH TAVSRPGLGE PRFIIVGYVD
 DTEFVRYDSD AENPRYEPRV GWMEREGPEY WERETLMVKE NEQVYRVSLR
 TLLRYYNQSE GGSHTIQWMS GCDVGSDGSL LRGYDQFAYD GRDYLALNED
 LKTWMAADTA AQMTRNKWDQ AGEAERHKAY LQGTCVEWLR RYLELGKETL
 LRSDPPKAHV TLHPRPEGDV TLRCWALGFY PAGIFLTWLL NGEDLTQDME
 LVETRPAGDG TFQKWASVVV PLGKEQNYTC LVEHEGLPDP LTLRWEAPPS
 TDPNMETTVI YVVVGAVVIT GAVTMIGALL TVVRGRKRNT GGKVGVYTPA
 PGKDSSESSD VSLPDCKAX*

>P1;RT1-Cc22_c
RT1-Cc22_c  296 bases  
 GSHSLRYFHT AVSRPGLGEP RFISVGYVDD TQFVRYDSDA ENPKYEPRAR
 WMEREGPEYW EEQTRVAKGQ EQDYRVSLRN LLSYYNQSEG GSHTIQRMYG
 CDVGSDGSLL RGYEQHAYDG RDYIALNEDL KTWAVADFAA WITRSKWQRN
 GAAERSRAYV EGTCVEWLLR YLERGKETLL RSDPPEAHVT LHPRPEGDVT
 LRCWALGFYP ADITLTWQLN GEDLTQDMEL VETRPAGDGT FQKWSSVVVP
 LGKEQNYTCR VEHEGLPEPL SQRWEPSPST DSNLLLLFLE LWQFLX*

>P1;RT1-Cc23_c
RT1-Cc23_c  292 bases  
 GSHSLRYFHT AVSRPGLGEP RFISVGYVDD TQFVRYDSDA ENPKYEPRAR
 WMEREGPEYW EEQTRVAKGQ EQDYRVSLRN LLSYYNQSEG GSHTIQRMYG
 CDVGSDGSLL RGYEQHAYDG RDYIALNEDL KTWAVADFAA WITRSKWRRN
 GAAERSRAYV EGTCVEWLLR YLERGKETLL RSDPPEAHVT LHPRPEGDVT
 LRCWALGFYP ADITLTWQLN GEDLTQDMEL VETRPAGDGT FQKWSSVVVP
 LGKEQNYTCR VEHEGLPEPL SQRWGRYSSQ SSVVSLPDCE AX*

>P1;RT1-Cc9_c
RT1-Cc9_c  338 bases  
 GSHSLRYFHT AVSRPRLGKP RFIIVGYVDD TEFMRYDSDA DNPRMEREGP
 EYWEERTRIA KETEQIFRVD LRILRGYYNQ SEGGSHTIQR IYGCVMGSDG
 KLQHGYDQLA YDGRDYIALN EDLKTWTAAD KAARITRSKW ERAGVAERRR
 AYLEGECVES LRRYLEEEKE TLLRSDPPKA HVTLHPRPEG DVTLRCWALG
 FYPADITLTW QLNGEDLTQD MELVETRPAG DGTFQKWAAV VVPLGEEPNY
 TCRVEHEGLP EPLTLRWEPP PSTNSNMSII AVLVVLIVSV AINGTVAFIE
 TDERRRRNTG GTGGDYAPAP GRDSSQSSDV SLPDCKAX*

>P1;RT1-Clw2_l
RT1-Clw2_l  368 bases  
 MAPRTLLLLL AAALAPTQVR AGSHSLRYFH TAVSRPGLGE PRFIIVGYVD
 DTEFVRYDSD AENPRYEPRV GWMEREGPEY WERETLMVKE NEQVYRVSLR
 TLLRYYNQSE GGSHTIQWMS GCDVGSDGSL LRGYDQFAYD GRDYLALNED
 LKTWMAADTA AQMTRNKWDQ AGEAERHKAY LQGTCVEWLR RYLELGKETL
 LRSDPPKAHV TLHPRPEGDV TLRCWALGFY PAGIFLTWLL NGEDLTQDME
 LVETRPAGDG TFQKWASVVV PLGKEQNYTC LVEHEGLPDP LTLRWEAPPS
 TDPNMETTVI YVVVGAVVIT GAVTMIGALL TVVRGKRNTG GKVGVYTPAP
 GKDSSESSDV SLPDCKAX*

>P1;RT1-EC2_r21
RT1-EC2_r21  349 bases  
 MGAKALQALL LLVAVALAPT QTSAGSHSLR YFETAVSRPG LGEPRFISVG
 YVDDTEFVRY DSDAENPRYE PRARWIEWEK PDYWETQTRR AKGNEQIYRG
 SLTTLLHYYN QSEDGSHTIQ WMYGCDVGSD GSLLRGYWQH AYDGRDYLAL
 NEDLKTWEAS DRAAQKTRNK WERKGVAERS RAYLKGTCVE SVRRYLELRK
 ETLVRSDPPK VRVTLHPRPE GDVTLRCWAL GFYPADITLT WQLNGEDLTQ
 DMELVETRPA GDGTFQKWAS VVVPLGKEQS YTCLVEHEGL PEPLTQRWEP
 PPSTDSNMGI IAVLAVVGAV AVIVLVALIG VVVRRRRKNI AFLLTGGIX*

>P1;RT1-EC3_r21
RT1-EC3_r21  364 bases  
 MAEVAHPTLP LLLAATLAPT QTRAGSHSLR YFYTAVSRPG LGEPLFIAVG
 YVDDTPFVRY DSDAENPRME PRVTWMEREG PEYWEEETRR IQETEQWFQM
 DLRTLRGYYN QNEDGSHTIQ RIFGCDLGSD GKLRRGYDQL AYDGLDHIAL
 KEDLKKWTVA DKVAWITRSR LEQTGETERR RAYLEGECVE SLHRYLELGK
 ERSAASDPLK VHVTLHPRPE GGVTLRCWAL GFYPAEITLS WQLNGEDLTQ
 DVEIVETRPA GDGTFQKWAS VVVPPGKEQK YTCHVDHEGL PEPITQRWEP
 SPSTDSNMET YVIYVVLGAV AIIAAVIIGA VVAVVRKRRR NTAFLLTGGT
 GGDYTPAPGR DSSX*

>P1;RT1-E_u
RT1-E_u  374 bases  
 MAPRTLLLLL AAALAPTQIR AGSHSLRYFD ITVSRPGLGE PRFISVGYVD
 DTEFVRYDSD AENPRFKPRV RWMEREGPEY WERITRIAKE SEQIYRVGLR
 TLRGYYNQSE GGSHTIQRLS GCEVGSDGIL LRGYEQFAYD GRDYIALNED
 LKTWAAADFA AGITRNKLER DGEAERLRAY LEGECVEWLR RYLELRKETL
 LRSEPPKAHV TLHSRPEGDV TLRCWALGFY PADIFLTWLL NGEDLTQDME
 LVETRPAGDG TFQKWASVVV PLGKEQNYTC HVEHEGLPEP LTLRWEGPPS
 ANSNTGMSVI LGTVAIIAVM AIIAAVAFIG PVVRKRWIKT AFLLTSGKGG
 DYTPAPGRDS SQSSDVSLPD CKAX*

>P1;RT1-K_u
RT1-K_u  373 bases  
 APRTLLLLLA AALAPTQIHA GSHSLRYFDI TVSRPGLGEP RFISVGYVDD
 TEFVRYDSDA ENPRFKPRVR WMEREGPEYW ERITRIAKES EQIYRVGLRT
 LRGYYNQSEG GSHTIQRLSG CEVGSDGILL RGYEQFAYDG RDYIALNEDL
 KTWAAADFAA GITRNKLERD GEAERLRAYL EGGSVEWLRR YLELRKETLL
 RSEPPKAHVT LHSRPEGDVT LRCWALGFYP ADIFLTWLLN GEDLTQDMEL
 VETRPAGDGT FQKWASVVVP LGKEQNYTCH VEHEGLPEPL TLRWEGPPSA
 NSNTGMSVIL GTVAIIAVMA IIAAVAFIGP VVRKRWIKTA FLLTSGKGGD
 YTPAPGRDSS QSSDVSLPDC KAM*

>P1;RT1-L1_l
RT1-L1_l  326 bases  
 MVLCMLLLLL VASLALTLTR AGSHSLRYFE TAVSRPGLGE PGFISVGYVD
 DTEFVRYDSD KENPKMEPRV RWMEQEGPEY WERETQRAKG QAQWSRVNLG
 TALRYYNQSE GGSHTIQRLS GCDLGSGRSL LPGYEQYAYD GRDYIALNED
 LKTWTAADAA AQITQSKWDQ AGTAERHRAY LEGTCVKSLC RYLELGKEKL
 LRSDPPKAHV TLHPSPEGDV TLRCWALDFY PADITLTWHL NGEDLTQDME
 LVETRPAGDG TFQKLASVVV PLGKEQNYTC LVEHEGLPEP LSQRWESSPS
 DTNMETNVIY VFLGAVAVMA AVAIHC*

>P1;RT1-L2_l
RT1-L2_l  365 bases  
 MGVTAPPLLL LLWRPLGRTQ TRAGSHSLRY FETAMSRPGL GEPRFISVGY
 VDDRQFVRYD NDAENPRMEP RARWMEREGP EYWQRETQRA KGQEQWSRVN
 LGTALRYYNQ SEGGSHTIQR MYGCDLGSDG SLLRGYEQYA YAGRDYIALN
 EDLKTWTAAD MVAQITQNKW DQAGTAERHR DYLEGTCVES LLRHLELGKE
 TLLRSDPPKT HVTLHPRPEG DVTLRCWALG FYPADITLTW QLNGEDLTQD
 MELVETRPAG DGTFQKWASV VVPLGKEQNY TCLVEHEGLP EPLTLRWEPS
 PSTDSNMETN VIYVVVGAVV IIGAVAIIVA LVVVVRRRRR SRTRRRRRRN
 IGGKGGVYAP APEVX*

>P1;RT1-L3_l
RT1-L3_l  341 bases  
 SHSLRYFETA VSQPGLGEPP VISVGFVDDT QFVRYDSDEE NPKYEPRARW
 MEREGPEYWE RETQRAKGNE QWSRVNLGTA LRYYNQSEGG SHTMQRLSGC
 AVGSDGSLLR GYDQYAYDGR DYIALNEDLK TWTAADTAAQ ITQSKWDQAG
 EAERSRAYLE GKCVEWLLRY LELGKETLLR SDPPKAHMTL HPRPEGDVTL
 RCWALGFYPA DITLTWQLNG EDLTQDMELV ETRPAGDGTF QKWASVVVPL
 GKEQSYTCHV EHEGLPEPLT LRWEPPPSTD FNVRIIAVLV VLGAVAIIGP
 VVAVVMKRRR NTGGTGGDYA PASGKTSPNS CDVSLPDCKA X*

>P1;RT1-U2_c
RT1-U2_c  349 bases  
 TRAGSHSLRY FVTAMSGPGL GKPRFMEVGY VDDTEFVRYD SDAKNPGMEP
 RARWMEREGR EYWERETRIA KENEQTFREN LRTLLRYYNQ SEGGSHTFQW
 MSGCDLGSDG SLLRGYEQSA YNGRDYIVLN EDLKTWTAAD TAARITRNKW
 DRAGVAERHK AYLEGTCLES LLRYLELGKE TLLRSDPPKA HVTLHPRPEG
 DVTLRCWALG FYPAGISLTW QLNGEDLTQD MELVETRPAG DGTFQKWASV
 VVPLGKEQNY TCLVEHEGLP EPLTQRWEPS PSTDSNMETN VIYVILGAVA
 IIGAVIIAAL VTVVRKRRNT GGKVGVYTPA PSRDSSESSD VSLPDCKAX*

