>DL;RT1-M5_n
RT1-M5_n  1008 bases  
 ATGGGAAGCT CCGTTTTCTC TGTCCTCCTA CCATTGCTGC TCAGCCGAGC
 TTGGGCATTG AACCAGGTCG GCGCAGGCAT CCATTCCTTG CAGTTTTTTG
 CCACTGCTGT GACCCAGCCT AGTTCGAGGG AGCATTCCTT CATCTTTGTC
 GGCTTTGTGG ACGACACACA GTTCCTGTGC TACAACAATC AGGGGGAAAG
 TCAGAGAATG GAGCCGCGCG CTCTGTGGGT AAAGAATATG GGGCCCGGAT
 ATTGGGAGCG GCAGACTAGG ATGGTCAAGG ACATTTCCAA GAATTCCCTA
 GTGAACTTGC GGGAGGCCAT GAGTGTCTAC AACCACAGCG AGGATGGCAC
 TCATGTCTTT CAGTGTGTGT CTGGCTGTGA CGTGGGGCCA GATGGACTCT
 TCCTCCGTGG GCACGAGCAG CACGCATACG ACGGCCGCGA CTACCTCGCT
 CTAAACAAGG ACCTGCACTC CTGGACGGCA GGTGACACAG CAGCGCAGAT
 CACGCGGCGC AAGTGGGAGG AAGCTGGTGT CGCGGAGCAA AGGCGAACCT
 ACCTGAAGGG CGAGTGTGTG GAGTCGCTCC GCACATACCT GGAGATAGGG
 AAGGAGACTC TGCTAGGAGC AGATCCTCCA AAAGCACATG TGACCCATCA
 CCCCAGCCCT GAAGGTGATA ACACCCTGAG GTGCTGGGCC CTGGGCTTCT
 ACCCTTCTGA CATCACCCTG ACCTGGCAGC GGGATGGAGA AGACCTGACC
 CAGGACATGG AGCTTGTGGA GACAAGACCT GGGGGTGATG GAACCTTCCA
 GAAGTGGGCA GCTGTGGTGG TGCCTTCTGG GGAGGAGCAT AGATACACAT
 GCTGTGTGGA GCATGAGGGG CTAACTGAGC CTCTCCTTCT GAAATGGGAC
 CCTTCTAAGC ACACCATCCC CATCATGGGA ATCACTGCTG GCCTGGTTTT
 CCTTGGAGTT GCCTTCACTG GAGCTGTGGT TGCCATAGCG ATGAGGAAGC
 AGAGAGGT*

