>P1;RT1-N1_r21
RT1-N1_r21  393 bases  
 MLWVPKAGAL WLSALLLLLN ACFSWTWTPE GSHSLRYFSI VMSWLGLREP
 RIIVSGCIDD TEFVRLDTNK ETVSLKPLVP WQEQEGLEYW EQQVHKVKTQ
 EQQSARNLMM LVRFYNKSMD DFHTLQWQQG CDVGSDGRLL HWYDQLAFDG
 VDHPTLNKDL RFWTAWTSTV AQISQPELEA RLKDNCSELL QKYPEKEKER
 LLRSDPPRAH VTRQPRPEGD VTLRCWALGF YPADITLTWQ LNGEDLIQEM
 EFVETRPAGD GTFQKWASVV VPLGKEQKYT CLVEHEGLSE PLTLRWEPAQ
 DSTTTIILII LPTVSAIVLC VAAAAAICIC LKKKAGERGR HDTQEADGDS
 PQDSCRIVVD DQEIEGPSWN TENYRTHLGF HSGTLGLLSL SFX*

>P1;RT1-N2_n
RT1-N2_n  378 bases  
 MLWVPKAGAL WLSALLLLLN ASFSWTWTPE GSHSLRYFSI VMSWLGLREP
 RIIVSGCIDD TEFVRLDTNK EIVSLKPLVP LQEQEGLEYW EQQVHKVKTQ
 EQQSARNLMM LVRFYNKSMD DFHTLQWQQG CDVGSDGRLL HWYDQLAFDG
 VDHPTLNKDL RFWTAWTSTV AQISQPELEA RLKDNCSELL QKYPEKEKER
 LLRSDPPRAH VTRHPRPEGD VTLRCWALGF YPADITLTWQ LNGEDLIQEM
 EFVETRPAGD GTFQKWASVV VPLGKEQKYT CLVEHEGLSE PLTLRWEPTQ
 DSTTTIILII LPTVSAIVLC VAAAVAICIC LKKKAGERGR HDTRKQMETV
 PKTLAGLLWM IRRSRVPLGI LRTTELIX*

>P1;RT1-N2_r21
RT1-N2_r21  378 bases  
 MLWVPKAGAL WLSALLLLLN ASFSWTWTPE GSHSLRYFSI VMSWLGLREP
 RIIVSGCIDD TEFVRLDTNK EIVSLKPLVP LQEQEGLEYW EQQVHKVKTQ
 EQQSARNLMM LVRFYNKSMD DFHTLQWQQG CDVGSDGRLL HWYDQLAFDG
 VDHPTLNKDL RFWTAWTSTV AQISQPELEA RLKDNCSELL QKYPEKEKER
 LLRSDPPRAH VTRHPRPEGD VTLRCWALGF YPADITLTWQ LNGEDLIQEM
 EFVETRPAGD GTFQKWASVV VPLGKEQKYT CLVEHEGLSE PLTLRWEPTQ
 DSTTTIILII LPTVSAIVLC VAAAVAICIC LKKKAGERGR HDTRKQMETV
 PKTLAGLLWM IRRSRVPLGI LRTTELIX*

>P1;RT1-N3_n
RT1-N3_n  394 bases  
 MLWVPKAAAR WLSALLQILL LNACFSWTWT LVGSHSLRYF STVMSWPGLR
 EPRIIVSGYI DNMEFLRLDS DAETPRVKPL VPWLEQEGLE YLEQQIHRIR
 TQAQQSERNL MTLVRFYNKS MDDFHTLQWQ QGCDVGSDGR LLHWYDQLAF
 DGIDHPTLNK DLRFWTAWTS TVAQISQPEL EARLKDNCSE LLQKYPEKEK
 ERLLRSDPPR AHVTRHPRPE SDVTLRCWAL GFYPADITLT WQLNGEDLIQ
 EMEFVETRPA GDGTFQKWAS VVVPLGKEQK YTCLVEHEGL SEPLTLRWEP
 AQDSTTTIIL IILPTVSAIA LCVAAVATCI CLKKKAGERG RHDTQEADGD
 SPQDSSKIVV DDQEMEDPFW NTENYRTHLG YRSGTLGFLS LSPX*

>P1;RT1-N3_r21
RT1-N3_r21  394 bases  
 MLWVPKAAAR WLSALLQILL LNACFSWTWT LVGSHSLRYF STVMSWPGLR
 EPRIIVSGYI DNMEFLRLDS DAETPRVKPL VPWLEQEGLE YLEQQIHRIR
 TQAQQSERNL MTLVRFYNKS MDDFHTLQWQ QGCDVGSDGR LLHWYDQLAF
 DGIDHPTLNK DLRFWTAWTS TVAQISQPEL EARLKDNCSE LLQKYPEKEK
 ERLLRSDPPR AHVTRHPRPE SDVTLRCWAL GFYPADITLT WQLNGEDLIQ
 EMEFVETRPA GDGTFQKWAS VVVPLGKEQK YTCLVEHEGL SEPLTLRWEP
 AQDSTTTIIL IILPTVSAIA LCVAAVATCI CLKKKAGERG RHDTQEADGD
 SPQDSSKIVV DDQEMEDPFW NTENYRTHLG YRSGTLGFLS LSPX*

