>DL;RT1-T18_n
RT1-T18_n  1050 bases  
 ATGGGAAACA TGGTGCCCAG CGCCCTCCTT CTCCTCCTGG CGACGTCGCC
 AGGCGAGACC CAGACCTGCT CAGGGTCACA CTCTCTGCGG TATTTCTACA
 CCGCCCTGTC CCGACCTGCA CCCGGCGAGT CCTGGTACAT CGCTGTGGGC
 TACGTGGACG ACACACAGTT CGTGCGCTTC AACAGCGCAG GGGAGAGTGC
 GAGATATAAG CTACGTGCGT CCTGGGTGGA GCAGGAGGGC CCCGAGTATT
 GGCAGAAGGA GACAGAGATC GTCACAAGCA ATGCACAGTT TTTCCGAGGA
 AACCTACAGA CCATGCTTGA CTACTACAAC CTGAGCCACG ACGGCTCTCA
 CATCATCCAG GTGATGTATG GCTGTGACGT GGAATCCGAT GGGAGCCTCC
 TCCGCGGTTA TGAGCAGTAT GCCTACGATG GCCGAGATTA CATCACCCTC
 AACGAAGATC TTAAGACTTG GACAGCAGAG GACAGGGCGG CGCAGATCAC
 CAGACTCAAG TGGGAGCAGG CTGGTTATGC AGAGCTCCGC AGGACCTACT
 TAGAGGGCCC ATGCAAGGAT TCGCTGCTCA GATACCTAGA GAATAGAAAA
 GAGATGCTGC AGTGTACAGA TCCTCCAAAG GCACATGTGA GCCATCACCC
 CGGACATGAA GGTGATGTCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCTGACAT CACTCTGATC TGGAAGAAGG AGGAGGAGGA ACTGAACCAA
 GAGATGGAGC TTATACAGAC CAGGCCTGCA GGGGATGGGA CTTTTCAGAA
 GTGGGCAGCT CTGGTGGTGC CTTCTGGGGA GGAGCAGAAG TACACATGTC
 ATGTGTACCA TGAGGGGCTA CCTGAGCCCC TCACCCTGAG ATGGGAGCCT
 CCTCAGTCCA GAATGCGGAC CAGGGTCATT GTTGGTGCTG TCCTTGGTGC
 TATGGCCATC TTAGGTTTTA TGACTGGAGG TGCTGTGATG TGCATGAGAA
 AGAACAAGGG AGGAGACAGA GATTATGATC CTGCTGCCGT CACAATGTGA*

