>DL;RT1-T24-1_n
RT1-T24-1_n  993 bases  
 ATGTGGTCTC TGATCTTCTG CTTCCTGAGC CACCCCCAAG ACACTGGAGC
 CCGATCACAC TCTCTGCACT ATTCTTACTC AGCCGTGACG GAGCCGGGCC
 CAGGAGTTCC TGCATTTTTT GCCAGTGGCT TTGTAGATAA CCAGACCTTC
 ATCCACTATG ACAGTAGGAA GATGGAGGCA GAGCCTTGTG CTGACTGGCT
 GAGGGAAAAT CCATATTACT TTGATGAGGA GACCCAGGTT TTCACCAATC
 AGATGAAGAT CTTCCAGTTG AGCCTGAGAA ACATTCAGCA ATACTACAAC
 AGCTCTGGTG ACCGGAGTCA CAGAGCAGAC GGCTTCCACC AGCAAGCAGG
 CCCTCACACC CTCCAATTCA CGTACGGCTG TGAGATGCAG GGCAACAGGA
 CCACAGGGCA CTGGCAGTAT GGCTACGATG GCAGAGATTA CCTGACCTTG
 GACTTGGACT CTATGCAATA TACAGCAGCC ACCTTCATTG CTGGCTACAC
 CAAGCACAAG TGGCAAAACA ATGAGTACTG GTTGGAGAGA GAGAAGACCT
 ACTTGGAGAA GGAGTGTGTC CTGTGGCTAA AGAGATACTT AACTATGGGA
 GGAGAGAACT TTACCCGAAC TGACCCTCCA CAGACAACAG TGACACACCA
 CCCCAGACCT GAAGGTGATG TCACCCTGAG GTGCTGGGCC CTGGGCTTCT
 ACCCTGCTGA CATCACCCTG ACCTGGCAGT TGAATGGGGA GGACCTGACC
 CAGGACATGG AGCTTGTGGA GACCAGGCCT ACAGGGGATG GAACCTTCCA
 GAAGTGGGCA GCTGTGGTGG TGCCTCTTGG GAAGGAGCAG AAGTACACAT
 GCCATGTGGA GCATGAGGGG CTGCCTGAGC CGCTTACCCA GAGATGGGAG
 GCTCCTCCAG GCACTGACTC CAACATGGGA ATCAATGTTA TTGCTGTTTT
 CTTCAAGCTG TGGCCATCAT TGCAGCTGTG GCCATCATCA TAG*

>DL;RT1-T24-3_n
RT1-T24-3_n  513 bases  
 ATGTGGGCTC TGATCTTCTG GTTCCTGACC CACCCCCAAG AAACTGGAGC
 CCGATCACAC TCTCTGCACT ATTCTTACTC AGCCGTGACA GAGCCGGGCC
 CAGGAGTTCC TGCATTTTTT GCCAGTGGTT TTGTAGATAA CCAGCCCTTC
 ATCCACTATG ACAGTAGGAA GATGGAGGCA GAACCTTGTG CTGACTGGCT
 GAGGGAAAAT CCATATTACT TTGATGAGGA GACCCAGGTT TTCACCAATC
 GGATGAAGAT CTTCCAGTTG AGCCTGAGAA ACATTCAGCA ATACTACAAC
 AGCTCTGGTG ACCGGAGTCA GAGAGCAGAC GGCTTCCACC AGCAAGCAGG
 CCCTCACACC CTCCAGTTCA CGTACGGCTG TGAGATGCAG GACAACAGGA
 CCACAGGGCA CTGGCAGTAT GGCTACGATG GCAGGGATTA CCTGACCTTG
 GACTTGGACT CTATGCAATA TACAGCAGCC ACCTTCATTG CTGGCTACAC
 CAAGCACAAG TGG*

>DL;RT1-T24-4_n
RT1-T24-4_n  1074 bases  
 ATGTGGGCTC TGATCTTCTG CTTCCTGAGT CACCCCCGAG ACACTGGAGC
 CCGATCACAC TCTCTGCACT ATTCTTACTC AGCCGTGACA GAGCCGGGCC
 CAGGAGTTCC TGCATTTTTT GCCAGTGGCT TTGTAGATAA CCAGCCCTTC
 ATCCACTATG ACAGTAGGAA GATGGAGGCA GAGCCTTGTG CTGACTGGCT
 GAGGGAAAAT CCATATTACT TTGATGAGGA GACCCAGGTT TTCACCAATC
 GGATGAAGAT CTTCCAGTTG AGCCTGAGAA ACATTCAGCA ATACTACAAC
 AGCTCTGGTG ACCGGAGTCA GAGAGCAGAT GGCTTCCACC AGCAAGCAGG
 CCCTCACACC CTCCAGTTCA CGTACGGCTG TGAGATGCAG GACAACAGGA
 CCACAGGGCA CTGGCAGTAT GGCTACGATG GCAGGGATTA CCTGACCTTG
 GACTTGGACT CTATGCAATA TACAGCAGCC ACCTTCATTG CTGGCTACAC
 CAAGCACAAG TGGCAAAACA ATGAGTACTG GCTGGAGAGA GAGAAGACCT
 ACTTGGAGAA GGAGTGTGTC CTGTGGCTAA AGAGATACTT AACTATGGGA
 GGAGAGAACT TTACCCGAAC TGACCCTCCA CAGACAACAG TGACACACCA
 CCCCAGACCT GAAGGTGATG TCACCCTGAG GTGCTGGGCC CTGGGCTTCT
 ACCCTGCTGA CATCACCCTG ACCTGGCAGT TGAATGGGGA GGACCTGACC
 CAGGAAATGG AGCTTGTGGA GACCAGGCCT GCAGGGGATG GAACCTTCCA
 GAAGTGGGCA TCTGTGGTGG TGCCTCTTGG GAAGGAGCAG AAGTACACAT
 GCCATGTGGA GCATGAGGGG CTGCCTGAGC CGCTTACCCA GAGATGGGAG
 CCTCCTTCAT CCACTGATTC CAACATGGAA ACCAATGTCA TTTATGTTGT
 CGTTGGAGCC GTCTCTGCTG TGGCCATTAT TGGAGCTGTG ATCATTGGAG
 CTGTGGTGGC TGTTGTGAGG AAGAGGAGGA GAAACACAGG TGGGAAAGGA
 GTCTACGCCC CTGCTCCAGC ATGA*

