>DL;RT1-DOb_n
RT1-DOb_n  819 bases  
 ATGGGTGCTG GGAGGGCCCC CTGGGTGGTG GCTCTGCTAG TGAACCTCAT
 GAGGCCAGAT TCCTTCATGG TTGAAGGCAG AGACTCCCCA GAGGATTTTG
 TGATTCAGGC GAAGGCAGAG TGTTACTTCA CCAACGGTAC AGAAAAGGTC
 CGCTTCCTGG TCAGGTTCAT CTTCAACCTG GAGGAGTACT TACATTTCGA
 CAGTGACCTG GGGTTTTTCG TGGCACTGAC GGAGCTGGGG GAGGTGGACG
 CTGATCAGTG GAACAAACGC CTGGATCTCC TGGAAACAAG TAGAGCTGCT
 GTGAACATGG TCTGCAGGCA AGAGTACAAG CTGGGGGCCC CCTTCACCGT
 GGAGAGAAAT GTGCCTCCGG AGGTGACGGT GTACCCAGAG AGGACCCCAT
 TGCTGCAGCA GCACAACCTG TTGCTCTGCT CTGTGACAGA CTTCTACCCT
 GGGGACATAA GTGTCAGGTG GTTCCGGAAT GGGCAGGAGG AGAGGTCCGG
 GGTCATGTCC ACTGGCCTTG TTAGGAATGG AGACTGGACC TTCCAGACGA
 CGGTAATGCT GGAAATGATC CCAGAGCTTG GAGACGTCTA CAGTTGCCTT
 GTGGAGCACC CCGGCCTCCT GAGACCTGTT TCTGTGGCAT GGGTGGCTCA
 GTCTGAATAT TCCTGGGAAA AGATACTGAG TGGAGCTGCA GCATTCCTGC
 TTGGGCTGAC TGTCTTTCTG GTGGGAGCTG TCATCCACCT CAAGGCTCAG
 AAAGCGTCCG TGGAGACTCA GCCTGGCAAT GAGGCTTCAA GGGCGCTTCT
 CCCACCTCAC CCCTACTAA*

