>DL;RT1-O1_n
RT1-O1_n  546 bases  
 ATGGCTCCGT GCTGCTGCTG CTCCTGCTGC TGGTGGCCTC CTTGGCCTTT
 ACCAGGACTC CTACCAGAGA AACCCCCAAA GACACATGTG ACCCACCACC
 CCAGTCCTGA AGGTGATGTC ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC
 ACTGCTGACA TCACTCTGAC CTGGAAGAGG GATGGGGAGA ACCTGACCCA
 GGACATGGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA ACCTTCCAGA
 AGTGGGCAGC TGTGGTGGTG CCTTCTGGAG AGGAGGAGAA TTACACATGC
 CTTGTGGAGC ATGAGGGGCT GCCTGAGCCC CTCACCCTGA GATGGGGCTC
 CTCCATCCAC CAACTCCAAC ATGGGAATCA TTGCTGTCCT GGTTGTCCTT
 GGAGCTGTGG CCATCATAGG AGCTGTGGTG GCTGTTGTGA GGAAGAGGAG
 GAGAAACACA GGTGGAAAAG GAGGGGACTA TGCTCCAGCT CAAAGCAGCA
 ACAGTGTCCA CAGCTGGGAC TCCTCTCAGG AGACTTGAAA AGGTGA*

>DL;RT1-S2_n
RT1-S2_n  531 bases  
 ATGTTACCTC CTGCCTACTT GCTCCAACTG CTGGCCTGCA CCATGGTCTT
 GACCCACACT CAACCCCCAA AGACACATGT GACCCACCAC CCCAGTCCTG
 AAGGTGATGT CACCCTGAGG TGCTGGGCCC TGGGCTTCTA CCCTGCTGAC
 ATCACTCTGA CCTGGAAGAG GGATGGGGAG AACCTGACCC AGGACATGGA
 GCTTGTGGAG ACCAGGCCTG CAGGGGATGA AACCTTCCAG AAGTGGGCAG
 CTGTGGTGGT GCCTTCTGGA GAGGAGGAGA ATTACACATG CCTTGTGGAG
 CATGAGGGGC TGCCTGAGCC GCTTTCCCAG AGATGGGAGT CTCCTCCATC
 CACTGTCTCC AACACAGCCA TGATTGCTGT CCTGGTTGTC CTTGGAGCTG
 TGACCATCAT AGGAGCTGTG GTGGCTGTTG TGAGGAAGAG GAGGAGAAAC
 ACAGGTGGAA AAGGAGGGGA CTATGCTCCA GCTCAAAGCA GCAACAATGT
 CCACCGGTCT GACTTGTCTC TGGAGGCTTG A*

