>P1;RT1-O1_n
RT1-O1_n  182 bases  
 MAPCCCCSCC WWPPWPLPGL LPEKPPKTHV THHPSPEGDV TLRCWALGFY
 TADITLTWKR DGENLTQDME LVETRPAGDG TFQKWAAVVV PSGEEENYTC
 LVEHEGLPEP LTLRWGSSIH QLQHGNHCCP GCPWSCGHHR SCGGCCEEEE
 EKHRWKRRGL CSSSKQQQCP QLGLLSGDLK RX*

>P1;RT1-S2_n
RT1-S2_n  177 bases  
 MLPPAYLLQL LACTMVLTHT QPPKTHVTHH PSPEGDVTLR CWALGFYPAD
 ITLTWKRDGE NLTQDMELVE TRPAGDETFQ KWAAVVVPSG EEENYTCLVE
 HEGLPEPLSQ RWESPPSTVS NTAMIAVLVV LGAVTIIGAV VAVVRKRRRN
 TGGKGGDYAP AQSSNNVHRS DLSLEAX*

