>P1;RT1-M10-1_n
RT1-M10-1_n  97 bases  
 MKNREPWVVV LLLLLVTMDL TQYCAGSRWL QTFNTVIAEP RKSAHQFIQV
 SYVDSIQFQG FDSQAPNAKM RPRAAWMEQE PPEYWEKGTA QPRACHX*

>P1;RT1-M10-3_n
RT1-M10-3_n  332 bases  
 MKNRGSWAFL LLPLVALDLA KYCAGSHWLQ IFNAAILEPG MGEARFIQVS
 YVDSIQFQAF DSKAGIIRMQ PRAAWMEQEP PEYWDKETAQ VVHLSRKDRK
 FLQFLVKNNK DSNDEYHTLQ ELFGCNVATD GTFLRGQYRF TYYGYDNITL
 KEDLSSWIAE GQRAQILKRA WERHGLTEQW KTYLQGECIE KLLRCLELGN
 ETLLRTDAPK THLTHQVRPD GNVILRCWAL GFYPADITLT WQRDGINHTQ
 DMELPDTRPA GDGTFQKWAA VMVPSGEEQR YTCHVHHEGL PEPLTLKWEP
 STTIPIVTIL IGLIVVTLVI GTVVILLIWK KX*

