>P1;RT1-DOb_n
RT1-DOb_n  273 bases  
 MGAGRAPWVV ALLVNLMRPD SFMVEGRDSP EDFVIQAKAE CYFTNGTEKV
 RFLVRFIFNL EEYLHFDSDL GFFVALTELG EVDADQWNKR LDLLETSRAA
 VNMVCRQEYK LGAPFTVERN VPPEVTVYPE RTPLLQQHNL LLCSVTDFYP
 GDISVRWFRN GQEERSGVMS TGLVRNGDWT FQTTVMLEMI PELGDVYSCL
 VEHPGLLRPV SVAWVAQSEY SWEKILSGAA AFLLGLTVFL VGAVIHLKAQ
 KASVETQPGN EASRALLPPH PYX*

