>DL;RT1-M10-1_n
RT1-M10-1_n  911 bases  
 ATGAAGAACC GTGAACCCTG GGTTGTAGTC CTCCTCCTCC TATTGGTGAC
 CATGGACCTG ACCCAGTATT GTGCAGGTTC ACGCTGGCTG CAGACTTTCA
 ACACTGTGAT TGCGGAACCT CGCAAGTCAG CGCACCAGTT CATCCAGGTC
 AGCTATGTAG ACTCGATACA GTTTCAGGGA TTCGACAGCC AAGCTCCCAA
 TGCAAAGATG CGACCTCGGG CTGCTTGGAT GGAGCAGGAG CCACCTGAAT
 ACTGGGAGAA GGGAACAGCA CAACCCCGCG CTTGTCACTG ACAAACCAAC
 GAGTCCTTCA GTTCCTGGTG ATTGAGAATA AACACAGCAA GAATGAATAT
 CACACCCTGC AGGAATTGTT TGGCTGCAAT GTAGCAAATG ATGGGAGCTT
 CCTCCGCGGT CAATACCGGC TCACCTACTA TGGCTATGAT AACATCATCC
 TGAATGAGGA CCTGAGCTCT TCCACAGAGG GATCTGCAGC ACAAGACCTG
 ATGAAGTACT CGGAGACCGG AGGCATGGCA GAAATGCCCC CCAAAACACA
 TCTGACCCAC CAAGTAAGAC CTGATGGCAA TGTCACCCTG AGGTGCTGGG
 CCTTAGGCTT CTACCCAGCT GACATCACCC TGACCTGGCA GAGGGATGGC
 AAAAACCACA CCCAGGACAT GGAGCTGCCA GACACCAGGC CAGCAGGGGA
 TGGAACCTTC CAGAAATGGG CAGTAGTGAT AGTTCCTTCT GGAGAGGAGC
 AGAGATACAC GTGTCATGTG CACCATGAAG GATTACCTGA GCCTCTCACT
 CTGAAGTGGG AGCCTTCAAC AACCATCCCC ATCATGGCAA TTCTCACTGG
 CCTGATTCTT GGGACTTTGG TGATGGGAAC TGTGGTGTAT CTTCTGGTAT
 GGAAGAAATA A*

>DL;RT1-M10-3_n
RT1-M10-3_n  996 bases  
 ATGAAGAACC GTGGATCCTG GGCCTTCCTC CTCCTCCCCT TGGTGGCCTT
 GGACCTGGCC AAGTATTGTG CAGGTTCACA CTGGCTGCAG ATTTTCAACG
 CTGCGATTTT GGAGCCTGGC ATGGGGGAGG CCCGGTTCAT CCAGGTCAGC
 TATGTAGACT CCATCCAGTT TCAGGCATTC GACAGCAAAG CAGGGATTAT
 AAGGATGCAA CCTCGGGCTG CTTGGATGGA GCAGGAGCCA CCTGAATATT
 GGGATAAGGA AACAGCACAA GTTGTGCACT TGTCACGGAA AGACAGAAAA
 TTTCTTCAGT TCCTGGTGAA AAACAATAAG GACAGCAATG ATGAATATCA
 CACCCTGCAG GAATTGTTTG GCTGCAATGT GGCAACTGAT GGGACCTTCC
 TTCGCGGTCA ATACCGGTTC ACCTACTATG GCTATGATAA CATCACCCTG
 AAGGAGGACC TGAGCTCTTG GATTGCAGAG GGCCAGAGAG CTCAAATTCT
 GAAGCGTGCC TGGGAGCGTC ATGGTCTGAC TGAACAATGG AAGACTTACC
 TGCAAGGGGA GTGCATAGAA AAGCTTCTTA GATGCCTGGA ACTTGGAAAT
 GAGACTTTGC TGCGCACTGA TGCCCCCAAA ACACATCTGA CCCACCAAGT
 AAGACCTGAT GGCAATGTCA TCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CAGCTGACAT CACCCTGACC TGGCAGAGGG ATGGGATCAA CCACACCCAG
 GACATGGAGC TGCCAGACAC CAGGCCTGCA GGGGATGGAA CCTTCCAGAA
 ATGGGCGGCA GTGATGGTTC CTTCTGGAGA GGAGCAGAGA TACACGTGTC
 ATGTGCACCA TGAAGGGCTC CCTGAGCCTC TCACTCTGAA GTGGGAACCT
 TCAACAACCA TCCCCATCGT GACAATTCTC ATCGGCTTGA TTGTTGTAAC
 ATTGGTGATA GGAACTGTGG TGATTCTTCT GATATGGAAG AAATAA*

