>DL;RT1-Da_l
RT1-Da_l  768 bases  
 ATGGCCACAA TTGGAGACCT GGTGATAAGA TTTTTCTTCA TGGCTGTCCT
 CATGAGCCCC CAGAAGTCGT GGGCTATCAG AGAGGAGCAC ACCATCATCC
 AGGCGGAGTT CTATCTTTCC CCCGACCAAA ATGGAGAGTT CATGTTTGAC
 TTTGACGGTG ACGAGATTTT CCATGTAGAT ATTAAAAAGT CAGAGACCAT
 CTGGAGACTT GAAGAATTTG CACAGTTTGC CAGCTTTGAG GCTCAGGGTG
 CATTGGCTAA TATAGCTGTG GACAAAGCTA ACCTGGACAT CATGATAAAG
 CGCTCCAACA ACACTCCAGA TGCCAATGTG ATTCCAGAGG TGACTGTACT
 CCCCAAAAGC CCGGTGAACC TGGGAGAGCC CAACATCCTC ATCTGTTTCA
 TTGACAAGTT CTCCCCTCCA GCGGTCAATG TCACCTGGCT TCGGAACGGA
 CAGCCTGTCA CCAAAGGCGT GTCAGAGACG GTGTTTCTCC CAAGGGAGGA
 CCACCTCTTC CGCAAATTCC ACTATCTGAC CTTCCTGCCC TCCACGGAAG
 ATTACTATGA CTGTGAGGTG GATCACTGGG GTCTGGAGGA GCCTCTGCGG
 AAGCACTGGG AGTTTGAAGA GAAAACCCTC CTCCCAGAAA CTAAAGAGAA
 TGTCCTGTGT GTTCTCGGGT TGTTTGTGGG TCTGGTAGGC ATCGTCGTCG
 GGATTGTGCT CATCATCAAG GGCCTTCGGA AACGCAACGC AGTGGAACGG
 CGCCAAGGAG CCCTGTGA*

>DL;RT1-Da_n
RT1-Da_n  768 bases  
 ATGGCCACAC TTGGAGACCT GGTGATAAGA TTTTTCTTCA TGGCTGTCCT
 CATGAGCCCC CAGAAGTCGT GGGCTATCAG AGAGGAGCAC ACCATCATCC
 AGGCGGAGTT CTATCTTTCC CCCGACCAAA ATGGAGAGTT CATGTTTGAC
 TTTGACGGTG ACGAGATTTT CCATGTAGAT ATTAAAAAGT CAGAGACCAT
 CTGGAGACTT GAAGAATTTG CACAGTTTGC CAGCTTTGAG GCTCAGGGTG
 CATTGGCTAA TATAGCTGTG GACAAAGCTA ACCTGGACAT CATGATAAAG
 CGCTCCAACA ACACTCCAGA TGCCAATGTG ATTCCAGAGG TGACTGTACT
 CCCCAAAAGC CCGGTGAACC TGGGAGAGCC CAACATCCTC ATCTGTTTCA
 TTGACAAGTT CTCCCCTCCA GCGGTCAATG TCACCTGGCT TCGGAACGGA
 CAACCTGTCA CCAAAGGCGT GTCAGAGACG GTGTTTCTCC CAAGGGAGGA
 CCACCTCTTC CGCAAATTCC ACTATCTGAC CTTCCTGCCC TCCACGGAAG
 ATTACTATGA CTGTGAGGTG GATCACTGGG GTCTGGAGGA GCCTCTGCGG
 AAGCACTGGG AGTTTGAAGA GAAAACCCTC CTCCCAGAAA CTAAAGAGAA
 TGTCCTGTGT GTTCTCGGGT TGTTTGTGGG TCTGGTAGGC ATCGTCGTCG
 GGATTGTGCT CATCATCAAG GGCCTTCGGA AACGCAACGC AGTGGAACGG
 CGCCAAGGAG CCCTGTGA*

>DL;RT1-Da_u
RT1-Da_u  768 bases  
 ATGGCCACAA TTGGAGACCT GGTGATAAGA TTTTTCTTCA TGGCTGTCCT
 CATGAGCCCC CAGAAGTCGT GGGCTATCAG AGAGGAGCAC ACCATCATCC
 AGGCGGAGTT CTATCTTTCC CCCGACCAAA ATGGAGAGTT CATGTTTGAC
 TTTGACGGCG ACGAGATTTT CCATGTAGAT ATTAAAAAGT CAGAGACCAT
 CTGGAGACTT GAAGAATTTG CACAGTTTGC CAGCTTTGAG GCTCAGGGTG
 CATTGGCTAA TATAGCTGTG GACAAAGCTA ACCTGGACAT CATGATAAAG
 CGCTCCAACA ACACCCCAGA TGCCAATGTG ATTCCAGAGG TGACTGTACT
 CCCCAAAAGC CCGGTGAACC TGGGAGAGCC CAACATCCTC ATCTGTTTCA
 TTGACAAGTT CTCCCCTCCA GCGGTCAATG TCACCTGGCT TCGGAACGGA
 CAGCCTGTCA CCAAAGGCGT GTCAGAGACA GTGTTTCTCC CAAGGGAGGA
 CCACCTCTTC CGCAAATTCC ACTATCTCAC CTTCCTGCCC TCCGTGGAAG
 ATTACTATGA CTGTGAGGTG GATCACTGGG GTCTGGAGGA GCCTCTGCGG
 AAGCACTGGG AGTTTGAAGA GAAAACCCTC CTCCCAGAAA CTAAAGAGAA
 TGTCCTGTGT GTTCTCGGGT TGTTTGTGGG TCTGGTAGGC ATCGTCGTCG
 GGATTGTGCT CATCATCAAG GGCCTTCGGA AACGCAACGC AGTGGAACGG
 CGCCAAGGAG CCCTGTGA*

