>DL;RT1-M1-2_n
RT1-M1-2_n  1033 bases  
 ATGAAGGTCC TTTTAGTTCT GGCTGTCCTG CTGCT---TA TGGTCACCCT
 TGTCATCACC AAGAATCCAA AAGGTTCACA CTCTCTGAGA TATTTACAAA
 CACTCCTGTC ATGGCCTGGC CTTGCGGAGC CCCAGTTCAT CTTTGTTGGC
 TATGTGGGCA ATACACAGTT CATAGGATTC AACAGCAGAT CACAGAGTCA
 GTGGTCGTTG CACAGAGCAC CGTGGAAAGA TCAACAGACT CCAGAGTATT
 GGGAGAAGAC AATACAGGAA GTCCTGAGTG AAAAACGGAA CTTGAAAGAA
 GTAATGGAGA AAATGCTTCA CATCTACCCT AACAGCACGA CTGGTAATCA
 CACAATCCAG ATGAGGTATG GCTGTGACGT GCTGCCTGGA GGTTACTTCA
 GTCATGGAAT CCTAGAATTG AATTTTGATA GCCAGGATTA CATCATACTG
 AATGATGAAC TGCACAACTG GATAATAGAT GGCAAGGCAG CTGAGATGCT
 CAAGCAGGAG TGGGAGGACA CGCA-TTATG CACAAATTGT GAAGAATTAC
 CTGAAGGGAT CATGTGTGGA TGAACTCCTT ACAGAGCTGG ACCTTGGGAA
 AGATTATTTG CTGAGAACAG ACACCCCCAG AACACACGTG ATCCACAAAG
 TCAGACCTGA CAGAAAAATC ATCCTGAGGT GCTGGGCCCT GAACTTCTAC
 CCTGCTGAAA TCACTATAAC CTGGCAGAGA GATGGGAGGA ACCAGACTCA
 GGATGTGGAA GTGATAGAGA CGAGGCCTGC AGGGGATGGA ACCTTCCAGA
 AGTGGGCAGC TGTGGTGGTG CCTTCTGGGG AAGAGCAGAA ATACACATGC
 CGTGTGGAGC ATGAGGGGCT GCCAGAGCCC ATCACCCTGA GATGGGA---
 GTCTCCTCAG TCCACCATCC CCGTCATGGC TATTGTTCTT TGTCTGGTTC
 TTGGAGCTCT GCTTACAGGA GCAGTGGTGA CTTCTCTGAT ATGGAAGAGG
 AAGATTAAAG GTAAAGACAG GGCAGGGTCT TAG*

>DL;RT1-M1-4_n
RT1-M1-4_n  1033 bases  
 ATGAAGACCT TTGTTACTGA GGCTCTCCTG CTGCTGCTCC TAGCAGTGCT
 GGCCCTGGCC AGCCATCCAG AAGGTTCACA TCTTTTTGGC CTTTTCCAAA
 CTCTCTTGAC CCGGCCTGGA CATTCTGAGC CCCTATTTAT CAGTGCTGGC
 TTTATGGATA ATATACAGTT TGAGAGGTTC AACAACAGAT CAGATTTTCC
 TGGGATGGAG CACTGCGCAC CATGGATAGA TCATCGGAGT CCAGAGTATT
 GGAAGGAGCA CACACAGAGG GCCCTGAAAG ATATTCGGTT TATGAGACAA
 GCACTGAAAT TAATGATCCA CACCTACAAC TACAGTGCAA CTGGATATCA
 CACAATCCAG AGGAGGATTG GCTGCCATGT CTTGCCTAGA GGGTACTTCA
 GTCATGGATT CTTAGAATTA GCCTTCAATG GCCAGGATTA CATCATGCTG
 AATGAAGACC TGAGGACTTG GACCACAGTT GGCAAGGCAG CTGAGATTCT
 CAGGAAAGAG TGGGAGAA-A CACAGTTTTG CACAAGCCAT GAAGATTTAT
 TTGGAGGTTT CATGTGTGGA CTCATTTCTC ACAGAGCTGG CTTATGGGAA
 GGAGATTTTG CTGAGAATAG ATCCCCCTAA AGTACAAGTG ATCCGCAAGG
 TCAGACTTAA CAGGAAAATT ACCCTGATGT GCTGGGCCCT GAGTTTCTAC
 CCTCCTGAAA TTACCCTGAC CTGGCAGAGA GATGGATGCA ATCAGATGCA
 GGACATGGAG GTGGTAGAGA CCAGGCCTGC AGGGGACGGA ACTTTCCAGA
 AATGGGCAGC TGTGGTGGTT TCTTCTGGGG AAGAGCAAAG ATACACATGT
 CATGTGAATC ATAAGGGGCT ACCTGAGGTC ATCACCATGA GGTGGGA---
 GCCTCCTGAG CCTATCATCC CAATTACTAC TATTGTTATT GCTGTAGTTC
 TCGGAGCTCT GGTTGTGGGA GCTGTGATGA CTTTTCTGAT ATGGAAGATG
 A---CTAGAG GTAAGGAAAG GGCATGGTTT TAG*

>DL;RT1-M1-5_n
RT1-M1-5_n  1033 bases  
 ATGGAGACTT CAGCAATCCT CACTCTCCAC CTGCTGCTGA GCGCTTCTTT
 GGCCCTGACC CAGTCCTTTA AAGGCTCCCA CTCCTTGCGG TACTTTGACA
 TCGCAGTGTC AAGGCCTGGC CTAGAGGAGA CCCACTACAT GACTCTTGGC
 TACGTGGATG ACACAGAGTT TGTGCATTTC AACAATGAGG CAGTGAATCC
 GAGGTTTGAG CCCCGGGTGC CCTGGATGGA ACAGATGGGA CAGAAGTACT
 GGGATGACCA GACACGAATT GCCAAAGTCG CGGAACAGCA GATTAGAGTG
 TACTTTCAGA AACTGCGAGG CTACTACAAC CAGAGCCAGA ACAGTTCTCA
 CACCATCCAA AGGATGACTG GCTGCTACAT TGGACCAGAC GGACACCTAC
 TTCACGCATA CCGTCAGTTT GGATATGATG GACAAGATTA CCTCACTTTG
 AATGAAGATC TGAGCACCTG GACTGCGGCA GATTCGGCAG CTGAGATCAC
 CCATAGAGAG TGGAAGGCAA C-TAATGAAG CTGAGTTCTG GAGGGTCTAC
 TTGGAGGGCC CTTGCATGGT GTGGCTCTTT AAATACCTGA CAGTGGGAAA
 TGAGACTCTA CTGCGCGCAG ATCCCCCCAA AGTATATGTG ACCCATCACC
 CCAGACCTGA AGGTGATATC ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC
 CCTTCTGACA TCACCCTGAT CTGGCAAAGA GATGGAGAGG ACCTGACCCA
 GGACATGGAC GTAATTGAGA CCAGACCTGC AGGGGATGGA ACCTTCCAGA
 AGTGGGCAGC TGTGGTGGTG CCTTCGGGGA AGGAGCAGAA TTATACATGC
 TATGTAGAAC ATGAGGGGCT GCCTGAACCC CTCACCCTGA GATGGAGTAG
 ACCTCCTCAG TCGTTCATTC CCACAATAGT GGTTGCTGTT GGCCTGGTTC
 TC-------- -CTGGGAGCT TCTGTGGTTA CACTTGTCAT TTGGAAGAAG
 A---GCTCAG GTGGTGGAAG GG-GTAGCCT GA-*

