>P1;RT1-DOa_n
RT1-DOa_n  251 bases  
 MVLFVELVQV FLTIMSFLGP RGVWAIKADH MGSYGPAFYQ SYDASGQFTH
 EFDGEQIFSV DLKKGEVVWR LPEFADFAYS DFQSGLMSIS MIRAHLDVLV
 ERSNRTRAVS VPPRVTVFPK SRVELGKPNV LICMVEDIFP PVINITWLRN
 SQPITKGVTQ TSFYSQPNHR FRKFHYLTFV PTAEDVYDCR VEHWGLDAPL
 LQHWEPQVLT PPPDTTETLI CGLGLALGLV GCLLGTLLMV TATRMPSTRR
 X*

>P1;RT1-DOa_u
RT1-DOa_u  251 bases  
 MVLFVELVQV FLTIMSFLGP RGVWAIKADH MGSYGPAFYQ SYDASGQFTH
 EFDGEQIFSV DLKKGEVVWR LPEFADFAYS DFQSGLMSIS MIRAHLDVLV
 ERSNRTRAVS VPPRVTVFPK SRVELGKPNV LICMVEDIFP PMINITWLRN
 SQPITKGVTQ TSFYSQPNHR FRKFHYLTFV PTAEDVYDCR VEHWGLDAPL
 LQHWEPQVLT PPPDTTETLI CGLGLALGLV GCLLGTVLMV TATRMPSTRR
 X*

