>DL;RT1-N1_r21
RT1-N1_r21  1179 bases  
 ATGCTCTGGG TTCCCAAGGC TGGTGCGCTC TGGCTCAGTG CCCTTCTCCT
 GCTCCTGAAT GCCTGCTTCT CCTGGACTTG GACCCCTGAG GGCTCACACT
 CCCTGCGGTA TTTCTCCATT GTCATGTCCT GGCTGGGCCT CCGGGAGCCA
 CGGATCATAG TCAGCGGCTG CATAGATGAT ACGGAGTTCG TGCGCTTGGA
 CACCAACAAG GAGACTGTAA GCCTGAAGCC CCTAGTGCCT TGGCAGGAGC
 AGGAGGGGCT AGAGTACTGG GAGCAGCAGG TTCATAAAGT CAAGACTCAA
 GAACAACAGT CTGCAAGGAA CCTGATGATG CTGGTTCGTT TTTACAATAA
 GAGCATGGAC GACTTCCACA CACTACAGTG GCAGCAAGGC TGCGATGTGG
 GGTCAGATGG GCGCCTGCTT CACTGGTACG ACCAGCTCGC CTTTGATGGT
 GTAGATCACC CCACCCTGAA CAAAGACCTG CGTTTCTGGA CAGCGTGGAC
 CAGCACTGTA GCTCAGATAT CTCAGCCCGA GTTAGAAGCT CGCCTGAAGG
 ACAACTGCTC AGAGCTGCTG CAGAAATACC CAGAAAAGGA GAAGGAGAGG
 CTGCTGCGTT CAGACCCGCC AAGGGCACAT GTGACCCGGC AACCCAGACC
 TGAAGGTGAT GTCACCCTGA GGTGCTGGGC CCTGGGTTTC TACCCTGCTG
 ACATCACCCT GACCTGGCAG TTGAATGGGG AGGACCTGAT CCAAGAAATG
 GAGTTTGTGG AGACCAGGCC TGCAGGGGAT GGAACCTTCC AGAAGTGGGC
 ATCTGTGGTG GTGCCTCTAG GGAAGGAGCA GAAGTACACA TGCCTTGTGG
 AGCATGAGGG GCTGTCAGAG CCGCTCACCC TGAGATGGGA GCCTGCCCAG
 GATTCCACCA CTACAATCAT TCTAATTATT CTACCCACTG TCTCTGCAAT
 TGTCCTCTGT GTTGCTGCTG CTGCGGCAAT TTGCATATGC CTGAAGAAGA
 AGGCAGGTGA AAGAGGAAGG CACGACACCC AGGAAGCAGA TGGAGACAGT
 CCCCAAGACT CTTGCAGGAT TGTTGTGGAT GATCAGGAGA TCGAGGGTCC
 CTCTTGGAAT ACTGAGAACT ACAGAACTCA TCTAGGATTC CACTCTGGGA
 CTTTAGGATT GCTTAGCTTG TCATTTTAA*

>DL;RT1-N2_n
RT1-N2_n  1134 bases  
 ATGCTCTGGG TTCCCAAGGC TGGTGCGCTC TGGCTCAGTG CCCTTCTCCT
 GCTCCTGAAT GCCTCCTTCT CCTGGACTTG GACCCCTGAG GGCTCACACT
 CCCTGCGGTA TTTCTCCATT GTCATGTCCT GGCTGGGCCT CCGGGAGCCA
 CGGATCATAG TCAGCGGCTG CATAGATGAT ACGGAGTTCG TGCGCTTGGA
 CACCAACAAG GAGATTGTAA GCCTGAAGCC CCTAGTGCCT TTGCAGGAGC
 AGGAGGGGCT AGAGTACTGG GAGCAGCAGG TTCATAAAGT CAAGACTCAA
 GAACAACAGT CTGCAAGGAA CCTGATGATG CTGGTTCGTT TTTACAATAA
 GAGCATGGAC GACTTCCACA CACTACAGTG GCAGCAAGGC TGCGATGTGG
 GGTCAGATGG GCGCCTGCTT CACTGGTACG ACCAGCTCGC CTTTGATGGT
 GTAGATCACC CCACCCTGAA CAAAGACCTG CGTTTCTGGA CAGCGTGGAC
 CAGCACTGTA GCTCAGATAT CTCAGCCTGA GTTAGAAGCT CGCCTGAAGG
 ACAACTGCTC AGAGCTGCTG CAGAAATACC CAGAAAAGGA AAAGGAGAGG
 CTGCTGCGTT CAGACCCGCC ACGGGCACAT GTGACCCGGC ACCCCAGACC
 TGAAGGTGAT GTCACCCTGA GGTGCTGGGC CCTGGGTTTC TACCCTGCTG
 ACATCACCCT GACCTGGCAG TTGAATGGGG AGGACCTGAT CCAAGAAATG
 GAGTTTGTGG AGACCAGGCC TGCAGGGGAT GGAACCTTCC AGAAGTGGGC
 ATCTGTGGTG GTGCCCCTAG GGAAGGAGCA GAAGTACACA TGCCTTGTGG
 AGCATGAGGG GCTGTCAGAG CCGCTCACCC TGAGATGGGA GCCTACCCAG
 GATTCCACCA CTACAATCAT TCTAATTATT CTACCCACTG TCTCTGCAAT
 TGTCCTCTGT GTTGCTGCTG CTGTGGCAAT TTGCATATGC CTGAAGAAGA
 AGGCAGGTGA AAGAGGAAGG CACGACACCA GGAAGCAGAT GGAGACAGTC
 CCCAAGACTC TTGCAGGATT GTTGTGGATG ATCAGGAGAT CGAGGGTCCC
 TCTTGGAATA CTGAGAACTA CAGAACTCAT CTAG*

>DL;RT1-N2_r21
RT1-N2_r21  1134 bases  
 ATGCTCTGGG TTCCCAAGGC TGGTGCGCTC TGGCTCAGTG CCCTTCTCCT
 GCTCCTGAAT GCCTCCTTCT CCTGGACTTG GACCCCTGAG GGCTCACACT
 CCCTGCGGTA TTTCTCCATT GTCATGTCCT GGCTGGGCCT CCGGGAGCCA
 CGGATCATAG TCAGCGGCTG CATAGATGAT ACGGAGTTCG TGCGCTTGGA
 CACCAACAAG GAGATTGTAA GCCTGAAGCC CCTAGTGCCT TTGCAGGAGC
 AGGAGGGGCT AGAGTACTGG GAGCAGCAGG TTCATAAAGT CAAGACTCAA
 GAACAACAGT CTGCAAGGAA CCTGATGATG CTGGTTCGTT TTTACAATAA
 GAGCATGGAC GACTTCCACA CACTACAGTG GCAGCAAGGC TGCGATGTGG
 GGTCAGATGG GCGCCTGCTT CACTGGTACG ACCAGCTCGC CTTTGATGGT
 GTAGATCACC CCACCCTGAA CAAAGACCTG CGTTTCTGGA CAGCGTGGAC
 CAGCACTGTA GCTCAGATAT CTCAGCCTGA GTTAGAAGCT CGCCTGAAGG
 ACAACTGCTC AGAGCTGCTG CAGAAATACC CAGAAAAGGA AAAGGAGAGG
 CTGCTGCGTT CAGACCCGCC ACGGGCACAT GTGACCCGGC ACCCCAGACC
 TGAAGGTGAT GTCACCCTGA GGTGCTGGGC CCTGGGTTTC TACCCTGCTG
 ACATCACCCT GACCTGGCAG TTGAATGGGG AGGACCTGAT CCAAGAAATG
 GAGTTTGTGG AGACCAGGCC TGCAGGGGAT GGAACCTTCC AGAAGTGGGC
 ATCTGTGGTG GTGCCCCTAG GGAAGGAGCA GAAGTACACA TGCCTTGTGG
 AGCATGAGGG GCTGTCAGAG CCGCTCACCC TGAGATGGGA GCCTACCCAG
 GATTCCACCA CTACAATCAT TCTAATTATT CTACCCACTG TCTCTGCAAT
 TGTCCTCTGT GTTGCTGCTG CTGTGGCAAT TTGCATATGC CTGAAGAAGA
 AGGCAGGTGA AAGAGGAAGG CACGACACCA GGAAGCAGAT GGAGACAGTC
 CCCAAGACTC TTGCAGGATT GTTGTGGATG ATCAGGAGAT CGAGGGTCCC
 TCTTGGAATA CTGAGAACTA CAGAACTCAT CTAG*

>DL;RT1-N3_n
RT1-N3_n  1182 bases  
 ATGCTCTGGG TTCCTAAGGC TGCTGCGCGC TGGCTCAGTG CCCTTCTCCA
 GATCCTGCTC CTGAATGCCT GCTTCTCCTG GACTTGGACC CTTGTGGGCT
 CACACTCCCT GCGGTATTTC TCCACTGTCA TGTCCTGGCC CGGCCTCCGG
 GAGCCAAGGA TAATAGTCAG CGGCTACATA GATAATATGG AGTTCCTGCG
 CTTGGACAGC GACGCCGAAA CTCCAAGGGT GAAGCCCCTA GTACCATGGC
 TGGAGCAGGA GGGGCTGGAA TACTTGGAGC AGCAGATTCA TAGAATCAGG
 ACTCAAGCAC AACAGTCTGA AAGGAACCTG ATGACGCTGG TTCGTTTTTA
 CAATAAGAGC ATGGACGACT TCCACACACT ACAGTGGCAG CAAGGCTGCG
 ATGTGGGGTC AGATGGGCGC CTGCTTCACT GGTACGACCA GCTCGCCTTT
 GATGGCATAG ATCACCCCAC CCTGAACAAA GACCTGCGTT TCTGGACAGC
 GTGGACCAGC ACTGTAGCTC AGATCTCTCA GCCCGAGTTA GAAGCTCGCC
 TGAAGGACAA CTGCTCAGAG CTGCTGCAGA AATACCCAGA AAAGGAGAAG
 GAGAGGCTGC TGCGTTCAGA CCCGCCAAGG GCACATGTGA CCCGGCACCC
 CAGACCTGAA AGTGATGTGA CCCTGAGGTG CTGGGCCCTG GGTTTCTACC
 CTGCTGACAT CACCCTGACC TGGCAGTTGA ATGGGGAGGA CCTGATCCAA
 GAAATGGAGT TTGTGGAGAC CAGGCCTGCA GGGGATGGAA CCTTCCAGAA
 GTGGGCATCT GTGGTGGTGC CTCTAGGGAA GGAGCAGAAG TACACATGCC
 TTGTGGAGCA TGAGGGGCTG TCAGAGCCGC TCACCCTGAG ATGGGAGCCT
 GCCCAGGACT CCACCACTAC AATCATTCTA ATTATTCTAC CCACTGTCTC
 TGCAATTGCC CTCTGCGTTG CTGCTGTGGC AACTTGCATA TGCCTGAAGA
 AGAAGGCAGG TGAAAGAGGA AGGCACGACA CCCAGGAAGC AGATGGAGAC
 AGTCCCCAAG ACTCTAGCAA GATTGTTGTG GATGATCAGG AGATGGAGGA
 TCCCTTTTGG AATACTGAGA ACTACAGAAC TCATCTAGGA TACCGCTCTG
 GGACTTTAGG ATTTCTAAGC TTGTCACCCT AA*

>DL;RT1-N3_r21
RT1-N3_r21  1182 bases  
 ATGCTCTGGG TTCCTAAGGC TGCTGCGCGC TGGCTCAGTG CCCTTCTCCA
 GATCCTGCTC CTGAATGCCT GCTTCTCCTG GACTTGGACC CTTGTGGGCT
 CACACTCCCT GCGGTATTTC TCCACTGTCA TGTCCTGGCC CGGCCTCCGG
 GAGCCAAGGA TAATAGTCAG CGGCTACATA GATAATATGG AGTTCCTGCG
 CTTGGACAGC GACGCCGAAA CTCCAAGGGT GAAGCCCCTA GTACCATGGC
 TGGAGCAGGA GGGGCTGGAA TACTTGGAGC AGCAGATTCA TAGAATCAGG
 ACTCAAGCAC AACAGTCTGA AAGGAACCTG ATGACGCTGG TTCGTTTTTA
 CAATAAGAGC ATGGACGACT TCCACACACT ACAGTGGCAG CAAGGCTGCG
 ATGTGGGGTC AGATGGGCGC CTGCTTCACT GGTACGACCA GCTCGCCTTT
 GATGGCATAG ATCACCCCAC CCTGAACAAA GACCTGCGTT TCTGGACAGC
 GTGGACCAGC ACTGTAGCTC AGATCTCTCA GCCCGAGTTA GAAGCTCGCC
 TGAAGGACAA CTGCTCAGAG CTGCTGCAGA AATACCCAGA AAAGGAGAAG
 GAGAGGCTGC TGCGTTCAGA CCCGCCAAGG GCACATGTGA CCCGGCACCC
 CAGACCTGAA AGTGATGTGA CCCTGAGGTG CTGGGCCCTG GGTTTCTACC
 CTGCTGACAT CACCCTGACC TGGCAGTTGA ATGGGGAGGA CCTGATCCAA
 GAAATGGAGT TTGTGGAGAC CAGGCCTGCA GGGGATGGAA CCTTCCAGAA
 GTGGGCATCT GTGGTGGTGC CCCTAGGGAA GGAGCAGAAG TACACATGCC
 TTGTGGAGCA TGAGGGGCTG TCAGAGCCGC TCACCCTGAG ATGGGAGCCT
 GCCCAGGACT CCACCACTAC AATCATTCTA ATTATTCTAC CCACTGTCTC
 TGCAATTGCC CTCTGCGTTG CTGCTGTGGC AACTTGCATA TGCCTGAAGA
 AGAAGGCAGG TGAAAGAGGA AGGCACGACA CCCAGGAAGC AGATGGAGAC
 AGTCCCCAAG ACTCTAGCAA GATTGTTGTG GATGATCAGG AGATGGAGGA
 TCCCTTTTGG AATACTGAGA ACTACAGAAC TCATCTAGGA TACCGCTCTG
 GGACTTTAGG ATTTCTAAGC TTGTCACCCT AA*

