>DL;RT1-DOa_n
RT1-DOa_n  753 bases  
 ATGGTCCTCT TTGTGGAGCT GGTCCAGGTA TTTCTAACCA TAATGAGCTT
 CCTGGGTCCC CGGGGAGTAT GGGCCATCAA GGCCGACCAC ATGGGCTCCT
 ACGGACCAGC CTTCTACCAG TCTTACGACG CCTCCGGACA GTTCACACAC
 GAATTTGACG GGGAACAGAT TTTCTCTGTG GATCTGAAGA AGGGGGAGGT
 CGTGTGGCGT CTGCCCGAGT TTGCAGACTT CGCGTACTCG GACTTTCAGA
 GCGGGCTGAT GAGCATCTCC ATGATCAGAG CTCATCTGGA CGTCTTGGTA
 GAACGCTCCA ACCGAACCAG AGCCGTCAGT GTGCCTCCCC GGGTGACCGT
 ATTCCCCAAG TCTCGCGTGG AGCTGGGAAA ACCCAATGTC CTCATCTGCA
 TGGTGGAAGA TATCTTCCCG CCTGTGATCA ATATCACCTG GCTGCGCAAC
 AGCCAGCCCA TCACTAAGGG AGTGACCCAG ACCAGCTTCT ACTCCCAGCC
 TAACCACAGG TTCCGGAAGT TCCACTACCT GACCTTCGTG CCCACGGCGG
 AGGATGTGTA CGACTGCAGG GTGGAGCACT GGGGCCTGGA CGCACCGCTC
 CTCCAGCACT GGGAGCCCCA GGTGCTTACC CCACCACCGG ACACCACAGA
 GACCCTGATC TGTGGCCTGG GCCTGGCTCT CGGCCTTGTG GGATGCCTCC
 TGGGCACCTT GCTCATGGTC ACAGCCACAC GCATGCCCAG TACCCGCAGG
 TAA*

>DL;RT1-DOa_u
RT1-DOa_u  753 bases  
 ATGGTCCTCT TTGTGGAGCT GGTCCAGGTA TTTCTAACCA TAATGAGCTT
 CCTGGGTCCC CGGGGAGTAT GGGCCATCAA GGCCGACCAC ATGGGCTCCT
 ACGGACCAGC CTTCTACCAG TCTTACGACG CCTCTGGACA GTTCACACAT
 GAATTTGACG GGGAACAGAT TTTCTCTGTG GATCTGAAGA AGGGGGAGGT
 CGTGTGGCGT CTGCCCGAGT TTGCAGACTT CGCGTACTCG GACTTTCAGA
 GCGGGCTGAT GAGCATCTCC ATGATCAGAG CTCATCTGGA CGTCTTGGTA
 GAACGCTCCA ACCGAACCAG AGCCGTCAGT GTGCCTCCCC GGGTGACCGT
 ATTCCCCAAG TCGCGTGTGG AGCTGGGAAA ACCCAATGTC CTCATCTGCA
 TGGTGGAAGA TATCTTCCCG CCTATGATCA ATATCACCTG GCTGCGCAAC
 AGCCAGCCCA TCACTAAGGG AGTGACCCAG ACCAGCTTCT ACTCCCAGCC
 TAACCACAGG TTCCGGAAGT TCCACTACCT GACCTTCGTG CCCACGGCGG
 AGGATGTGTA CGACTGCAGG GTGGAGCACT GGGGCCTGGA CGCACCGCTC
 CTCCAGCACT GGGAGCCCCA GGTGCTTACC CCACCACCGG ACACCACAGA
 GACCCTGATC TGTGGCCTGG GCCTGGCTCT CGGCCTTGTG GGATGCCTCC
 TGGGCACCGT GCTCATGGTC ACAGCCACAC GCATGCCCAG TACCCGCAGG
 TAA*

