>DL;RT1-M6-1_n
RT1-M6-1_n  993 bases  
 ATGGGGGCTC CAGTGCTGCA TGCTACCCTA CTGCTGCTCT CAGCCTTCCT
 GGCTCTGACC CAAACCAAGA ACCAGAGTTT TGCTGGTTCA CACTTCATGC
 AGTATTTGGT AACCACCACC TCGTCTCAAC CCGGTCTTCA AGATTCGCAT
 GTCTGCATTG TTGGCCATGT GGACTACATG CCATTTATGC GCTTTGACAG
 TGATGGAGCT GCTCAGAGGA TCCAGACGAG AGGGCCTTGG ATGAAGCAGA
 TGGGGCCTGA GTATTTGGAA ATGGAGAGAA AGAATGCGGA GGGGTATTCA
 CACAGGGCTC GAGAAAACCT GCGATTCGCA ATCCAAGTCT ATAACCAGAG
 CGATAAAGCG CACTATAGCC ATGCTTTTGA CGGCCAACAT TACATCAGCC
 TGAACTCGGA CCTGACAACA TGGAGTGTGG GAGACAGCAC AGCTCAGATC
 ACCAAGCGAC GGTGGGAGGC AGATGGTGTA GCAGAGGCCT TGAGTCACTT
 CTTGAAAGTC TCTTGTGTTG AACACCTGCA GAAGCACTTG GAGACAGGGA
 AGGAGACTCT ACAGCGCTCA GATCCCCCAA AGGCACATGT GACCCTTCAC
 CCCAGACCTG AAGGTGATGT CACCCTGAGG TGCTGGGCCC TGGGCTTCTA
 CCCTGCTGAC ATCACCCTGA CCTGGCAGTT GAATGGGGAG GACCTGACCC
 AGGACATGGA GCTTGTGGAG ACCAGGCCTG CAGGGGATGG AACCTTCCAG
 AAGTGGGCAT CTGTGGTGGT GCCTAATGGG GAGGAGCAGA AGTACACATG
 CCTTGTGGAG CATGAGGGGC TGCCTGAGCC CCTCACACTG AGATGGAAAC
 CAGCAACTTG GCCTGTGGTT GGAATAACTG TTGGTGTAGT TCTCCTTGGG
 TTTGTCATCA TTGGAGCTCT GATTGCCATT GTGACCATGA GGAAGAAGAG
 AGCAGACCCT GTGGATCCTG TGGACCTTAT GGATCCAGTG TGA*

