>DL;RT1-Bb_l
RT1-Bb_l  792 bases  
 ATGGCTCTGC AGACCCCCAG CTTCCTCCTC CCAGCAGCTG TGGTTGTGCT
 GATGGTGCTG AGCAGCCCAG GGACTGAGGG CAGAGACTCC CCAAGGGATT
 TCGTGTACCA GTTCAAGGGC CTGTGCTACT ACACCAACGG GACGCAGCGC
 ATACGGGATG TGATCAGATA CATCTACAAC CAGGAGGAGT ACCTGCGCTA
 CGACAGCGAC GTGGGCGAGT ACCGCGCGCT GACCGAGCTG GGGCGGCCCT
 CAGCCGAGTA CTTTAACAAG CAGTACCTGG AGCAGACGCG GGCCGAGCTG
 GACACGGTCT GCAGACACAA CTACGAGGGG TCGGAGGTCC GCACCTCCCT
 GCGGCGGCTT GAGCAGCCCA ATGTGGCCAT CTCCCTGTCC AGGACAGAGG
 CCCTCAACCA CCACAACTTG CTGGTCTGCT CAGTGACAGA TTTCTACCCA
 GCCCAGATCA AAGTGCGCTG GTTCCGGAAT GGCCAGGAGG AGACGGCGGG
 GGTCGTGTCC ACACAGCTTA TTAGGAACGG GGACTGGACC TTCCAGATCC
 TGGTCATGCT GGAGATGACG CCTCAGCGGG GAGAGGTGTA CATCTGCCAT
 GTTGACCACC CCAGCCTTGA GAGCCCCGTC ACAGTGGAGT GGCGGGCACA
 GTCCGAGTCT GCCCAGAGCA AGATGCTGAG CGGCATCGGG GGCTTTGTGC
 TGGGGGTGAT CTTCCTCGGG CTTGGCCTTT TCATCCGTCA CAAGCGTCAG
 AAAGGACCTC GGGGGCCTCC TCCAGCAGGG CTCCTACAGT GA*

>DL;RT1-Bb_n
RT1-Bb_n  705 bases  
 TCCGCAGGGG ATTTCGTATT CCAGTTCAAG GGCCTGTGCT ACTACACCAA
 CGGGACGCAG CGCATACGGC TCGTGATCAG ATACATCTAC AACCGGGAGG
 AGTACGTGCG CTTCGACAGC GACGTGGGCG AGTTCCGCGC GCTGACCGAG
 CTGGGGCGGC CCTCAGCCGA GTACTATAAC AAACAGTACC TGGAGCGGAC
 GCGGGCCGAG CTGGACACGG TCTGCAGACA CAACTACGAG GAGACGGAGG
 TCCCCACCTC CCTGCGGCGG CTTGAGCAGC CCAATGTGGC CATCTCCCTG
 TCCAGGACAG AGGCCCTCAA CCACCACAAC TTGCTGGTCT GCTCAGTGAC
 AGATTTCTAC CCAGCCCAGA TCAAAGTGCG CTGGTTCCGG AATGGCCAGG
 AGGAGACGGC GGGGGTCGTG TCCACACAGC TTATTAGGAA CGGGGACTGG
 ACCTTCCAGA TCCTGGTCAT GCTGGAGATG ACGCCTCAGC GGGGAGAGGT
 GTACATCTGC CATGTTGACC ACCCCAGCCT CGAGAGCCCC GTCACAGTGG
 AGTGGCGGGC ACAGTCCGAG TCTGCCCAGA GCAAGATGCT GAGCGGCATC
 GGGGGCTTTG TGCTGGGGGT GATCTTCCTC GGGCTTGGCC TTTTCATCCG
 TCACAAGCGT CAGAAAGGAC CTCGGGGGCC TCCTCCAGCA GGGCTCCTAC
 AGTGA*

>DL;RT1-Bb_u
RT1-Bb_u  735 bases  
 CTGATGGTGC TGAGCAGCCC AGGGACTGAG GGCAGAGACT CCCGAAGGGA
 TTTCTTGGTC CAGTTTAAGC CCTACTGCTA CTTCACCAAC GGGACGCAGC
 GCATACGGAA TGTGATCAGA TACATCTACA ACCGGGAGGA GTACCTGCGC
 TACGACAGCG ACGTGGGCGA GTACCGCGCG GTGACCGAGC TGGGGCGGCC
 CTCAGCCGAG TACTTTAACA AGCAGTACCT GGAGCGGACG CGGGCCGAGC
 TGGACACGGT CTGCAGACAC AACTACGAGA AGACAGAGGT CCCCACCTCC
 CTGCGGCGGC TTGAGCAGCC CAATGTGGCC ATCTCCCTGT CCAGGACAGA
 GGCCCTCAAC CACCACAACT TGCTGGTCTG CTCAGTGACA GATTTCTACC
 CAGCCCAGAT CAAAGTGCGC TGGTTCCGGA ATGGCCAGGA GGAGATGGCG
 GGGGTCGTGT CCACACAGCT TATTAGGAAC GGGGACTGGA CCTTTCAGAT
 CCTGGTCATG CTGGAGATGA CGCCTCAGCG GGGAGATGTG TACACCTGCC
 GTGTTGACCA CCCCAGCCTC GATAGCCCTG TCACAGTGGA GTGGCGGGCA
 CAGTCCGAGT CTGCCCAGAG CAAGATGCTG AGTGGCATCG GGGGCCTTGT
 GCTGGGGGTG ATCTTCCTTG GGCTTGGCCT TTTCATCCAT TATAAGAGTC
 AGAAAGGACC TCAGGGGCCT CCTCCAGCAA GGTCT*

