>P1;RT1-T18_n
RT1-T18_n  350 bases  
 MGNMVPSALL LLLATSPGET QTCSGSHSLR YFYTALSRPA PGESWYIAVG
 YVDDTQFVRF NSAGESARYK LRASWVEQEG PEYWQKETEI VTSNAQFFRG
 NLQTMLDYYN LSHDGSHIIQ VMYGCDVESD GSLLRGYEQY AYDGRDYITL
 NEDLKTWTAE DRAAQITRLK WEQAGYAELR RTYLEGPCKD SLLRYLENRK
 EMLQCTDPPK AHVSHHPGHE GDVTLRCWAL GFYPADITLI WKKEEEELNQ
 EMELIQTRPA GDGTFQKWAA LVVPSGEEQK YTCHVYHEGL PEPLTLRWEP
 PQSRMRTRVI VGAVLGAMAI LGFMTGGAVM CMRKNKGGDR DYDPAAVTMX*

