>DL;RT1-119_l
RT1-119_l  1032 bases  
 ATGGGGGCAA AGGCACCTCA GGCGCTGCTC CTGCTGGTGG CGGTCGCCCT
 GGCCCCGACC CAGACCCGCG CAGGCTCACA CTCGCTGCGG TATTTCGAAA
 CCGCCGTGTC CCGGCCCGGC CTCGGGGAGC CACGGTTCAT CTCTGTAGGC
 TACGTGGACG ACACGGAGTT CGTGCGCTAC GACAGTAACG CGGAGAATCC
 GAGATACGAG CCGCGGGCGC GGTGGATTGA GTGGGAGAAG CCGGACTATT
 GGGAGACGCA GACACGGAGA GCCAAGGGAA ACGAGCAGAT TTACCGAGGG
 AGCCTGACGA CCCTGCTCCA CTACTACAAC CAGAGCGAGG ACGGCTCTCA
 CACCATCCAG TGGATGTATG GCTGTGACGT GGGGTCGGAC GGGAGCCTCC
 TCCGCGGGTA TTGGCAGCAC GCCTATGATG GCCGCGATTA CCTCGCCCTG
 AATGAAGACC TGAAAACGTG GGAGGCCTCG GACAGAGCGG CGCAGAAAAC
 CCGGAACAAG TGGGAGCGGA AAGGTGTTGC AGAGAGAAGC AGGGCCTACC
 TGAAGGGCAC ATGTGTGGAG TCGCTCCGCA GATACCTGGA GCTCAGAAAG
 GAGACGCTGC TGCGCTCAGA TCCCCCAAAG GTGCGTGTGA CCCTTCACCC
 CAGACCTGAA GGTGATGTCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCTGACAT CACCCTGACC TGGCAGTTGA ATGGGGAGGA CCTGACCCAG
 GACATGGAAC TTGTGGAGAC CAGGCCTGCA GGGGATGGAA CCTTCCAGAA
 GTGGGCATCT GTGGTGGTGC CTCTTGGGAA GGAGCAGAGT TACACATGCC
 TTGTGGAGCA TGAGGGGCTG CCTGAGCCGC TTACCCAGAG ATGGGAGCCT
 CCTCCATCAA CTGATTCCAA CATGGGAATC ATTGCTGTTC TGGCTGTCGT
 TGGAGCTGTG GCTGTCATTG TACTTGTGGC CCTCATTGGA GTTGTTGTGA
 GGAGGAGGAG GAAAAACATA GGTGGAATAT GA*

>DL;RT1-3_6_av1
RT1-3_6_av1  960 bases  
 ATGGGGGCGA TGGCACCGCG CACGCTGCTC CTGCTGCTGG CGGCGGTCCT
 GGCCCCCACC CAGACCTGGG CGGGCTCACA CTCGCTGCGG TATTTCCACA
 CCGCCGTGTC CCGGCCCGGC CTCGGGGAGC CCCGGTTCAT TTCTGTCGGC
 TACGTGGACG ACACGCAGTT CGTGCGCTAC GACAGCGACG CGGAGAATCC
 GAGATACGAG CCGCGGGCGC GGTGGATGGA GCGGGAGGGG CCGGAGTATT
 GGGAGGAGCA GACACTGGTC GCCAAGGGAC AGGAGCTGGA TTACCGAGTG
 AGCCTGAGGA ACCTGCTAAG CTACTACAAC CAGAGCGAGG GCGGCTCTCA
 CACCATCCAG AGGATGTATG GCTGTGACGT GGGGTCCGAC GGGAGCCTCC
 TCCGCGGGTA TGAGCAGCAC GCCTACGACG GCCGCGATTA CATCGCCCTG
 AACGAAGACC TGAAAACATG GGCTGTGGCA GACTTTGCAG CATGGATCAC
 CCGGAGCAAG TGGCAGCGGA ATGGTGCTGC AGAGAGAAGC AGGGCCTATC
 TGGAGGGCAC GTGTGTGGAG TGGCTCCTCA GATACCTGGA GCGCGGGAAG
 GAGACGCTGC TGCGCTCAGA TCCCCCAGAG GCACATGTGA CCCTTCACCC
 CAGACCTGAA GGTGATGTGA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCTGACAT CACCCTGACC TGGCAGTTGA ATGGGGAGGA CCTGACCCAG
 GACATGGAGC TTGTGGAGAC CAGGCCTGCA GGGGATGGAA CCTTCCAGAA
 GTGGGCATCT GTGGTGGTGC CTCTTGGGAA GGAGCAGAAT TACACATGCC
 GTGTGGAGCA TGAGGGGCTG CCTGAGCCCC TTTCCCAGAG ATGGGAGCCT
 TCTCCATCCA CCGACTCCAA CTTACTTCTG TTGTTCTTGG AGCTGTGGCA
 GTTTTTGTAG*

>DL;RT1-9_5_f
RT1-9_5_f  876 bases  
 GGCTCACACT CGCTGCGGTA TTTCCACACC GCCGTGTCCC GGCCCGGCCT
 CGGGGAGCCC CGGTTCATTT CTGTCGGCTA CGTGGACGAC ACGCAGTTCG
 TGCGCTACGA CAGCGACGCG GAGAATCCGA GATACGAGCC GCGGGCGCGG
 TGGATGGAGC GGGAGGGGCC GGAGTATTGG GAGGAGCAGA CACTGGTCGC
 CAAGGGACAG GAGCTGGATT ACCGAGTGAG CCTGAGGAAC CTGCTAAGCT
 ACTACAACCA GAGCGAGGGC GGCTCTCACA CCATCCAGAG GATGTATGGC
 TGTGACGTGG GGTCCGACGG GAGCCTCCTC CGCGGGTATG AGCAGCACGC
 CTACGACGGC CGCGATTACA TCGCCCTGAA CGAAGACCTG AAAACATGGG
 CTGTGGCAGA CTTTGCAGCA TGGATCACCC GGAGCAAGTG GCAGCGGAAT
 GGTGCTGCAG AGAGAAGCAG GGCCTATCTG GAGGGCACGT GTGTGGAGTG
 GCTCCTCAGA TACCTGGAGC GCGGGAAGGA GACGCTGCTG CGCTCAGATC
 CCCCAGAGGC ACGTGTGACC CTTCACCCCA GACCTGAAGG TGATGTGACC
 CTGAGGTGCT GGGCCCTGGG CTTCTACCCT GCTGACATCA CCCTGACCTG
 GCAGTTGAAT GGGGAGGACC TGACCCAGGA CATGGAGCTT GTGGAGACCA
 GGCCTGCAGG GGATGGAACC TTCCAGAAGT GGGCATCTGT GGTGGTGCCT
 CTTGGGAAGG AGCAGAATTA CACATGCCGT GTGGAGCATG AGGGGCTGCC
 TGAGCCCCTT TCCCAGAGAT GGGGCAGGTA CAGCTCCCAG AGCTCCGTTG
 TGTCTCTCCC AGATTGTGAA GCATGA*

>DL;RT1-9_6_f
RT1-9_6_f  876 bases  
 GGCTCACACT CGCTGCGGTA TTTCCACACC GCCGTGTCCC GGCCCGGCCT
 CGGGGAGCCC CGGTTCATTT CTGTCGGCTA CGTGGACGAC ACGCAGTTCG
 TGCGCTACGA CAGCGACGCG GAGAATCCGA GATACGAGCC GCGGGCGCGG
 TGGATGGAGC GGGAGGGGCC GGAGTATTGG GAGGAGCAGA CACGGGTCGC
 CAAGGGACAG GAGCAGGATT ACCGAGTGAG CCTGAGGAAC CTGCTAAGCT
 ACTACAACCA GAGCGAGGGC GGCTCTCACA CCATCCAGAG GATGTATGGC
 TGTGACGTGG GGTCCGACGG GAGCCTCCTC CGCGGGTATG AGCAGCACGC
 CTACGACGGC CGCGATTACA TCGCCCTGAA CGAAGACCTG AAAACATGGG
 CTGTGGCAGA CTTTGCAGCA TGGATCACCC GGAGCAAGTG GCAGCGGAAT
 GGTGCTGCAG AGAGAAGCAG GGCCTATCTG GAGGGCACGT GTGTGGAGTG
 GCTCCTCAGA TACCTGGAGC GCGGGAAGGA GACGCTGCTG CGCTCAGATC
 CCCCAGAGGC ACATGTGACC CTTCACCCCA GACCTGAAGG TGATGTGACC
 CTGAGGTGCT GGGCCCTGGG CTTCTACCCT GCTGACATCA CCCTGACCTG
 GCAGTTGAAT GGGGAGGACC TGACCCAGGA CATGGAGCTT GTGGAGACCA
 GGCCTGCAGG GGATGGAACC TTCCAGAAGT GGGCATCTGT GGTGGTGCCT
 CTTGGGAAGG AGCAGAATTA CACATGCCTT GTGGAGCATG AGGGGCTGCC
 TGAGCCCCTT TCCCAGAGAT GGGGCAGGTA CAGCTCCCAG AGCTCCGTTG
 TGTCTCTCCC AGGTTGTGAA GCATGA*

>DL;RT1-C113_l
RT1-C113_l  1062 bases  
 ATGGCACCGC GCACGCTGCT CCTGCTGCTG GCGGCCGCCC TGGCCCCGAC
 CCAAATCCGC GCGGGCTCAC ACTCGTTGCG GTATTTCTAC ACCGCCATGT
 CCCGGCCCGG CCTCGGGGAG CCCCGGTTCA TCGAAGTCGG CTACGTGGAT
 GGCACAGAGT TCGTGCGCTA CGACAGCGAC GCGGAGAATC CGAGATATGA
 GCCGCGGGCG CGGTGGATGG AGCGGGAGGG GACGGAGTAT TGGGAGAGGG
 AGACAAGGAG AGCCAAGGGA GACGAGCATA TGTTCCGAGT GAGCCTGAGG
 AATCTGCGCG GCTACTACAA CCAGAGCGAG GGCGGCTCTC ACACCATCCA
 GAGGATATAT GGCTGTGTCA TGGGGTCGGA CGGGATCCTC CTCCGCGGAT
 ATTGGCAGTT CGCCTACGAT GGCCGCGATT ACATGGCCCT GAACGAAGAC
 CTGAAAACGT ATACGGCTGC GGACTTTGCA GCAAGGATCA CCCGGAACAA
 GTGGGAGCGG GTTGGTGCTG CACAGAGTCA GAAGGCCTAC CTGGAGGGCA
 AGTGCATGGT GTGGCTCAGC AGACACCTGG AGCAAGGGAA GGAGACACTC
 GTGCGCTCAG ATCCCCCAAA GGCACATGTG ACCCTTCACC CCAGACCTGA
 AGGTGATGTC ACTCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCTGACA
 TCACCCTGAC CTGGCAGTTG AATGGGGAGG ACCTGACCCA GGACATGGAG
 CTTGTGGAGA CCAGGCCTTC AGGGGATGGA ACCTTCCAGA AGTGGGCAGC
 TGTGGTGGTG CCTCTTGGGA AGGAGCAGAA TTACACATGC CTTGTGGACC
 ATGAGGGGCT GCCTGAGCCT CTCACCTTGA GATGGGAACC TCCTCCATCC
 ACAGACTTCA ACATGGTAAT CATCACTGTC CTGGTTGTCC TTGGAGCTGT
 GGCCATCATT GGAGTTGTGG TGGCTGTTGT GATGAAGTGG AGAAACCCAG
 GAGGAACAGG AGGAGACTAC GCCCCTGCTC CAGCACGAAG ACAGCTGCCT
 GGAGTGGACT GA*

>DL;RT1-CE10_n
RT1-CE10_n  1083 bases  
 ATGGAGGCGA TGGCACGGCC CACGCTGCTC CTGCTGCTGG CCGCCGCCCT
 GGCCCCGACC AAGACCCGCG CGGGCTCACA CTGGATGCGG TATTTCCACA
 CCGCCGTGTC CCGGCCGGGC CTCGGGGAGC CCCGGTACAT CTCTGTCGGC
 TACGTGGACG ACACGCAGTT CGTGCGCTTC GACAGCGACG CGGAGAATCC
 AAGATACGAG CCGCGGGCGC GGTGGATGGA ACGGGAGGGG CCGGAGTATT
 GGGAGCGGAA CACACGGATC GTCAAGGGAA AGGAGCAGAT TTTCCGAGAC
 AACCTGAGGA CCCTGCTTGG CTACTACAAC CAGAGCGAGG GCGGCTCTCA
 CACACTCCAG TTGATGTATG GCTGTGACGT GGGGTCGGAC TGGAGCCTCC
 TCCGCGGGTA TGAGCAGCAC GCCTACGACG GCCGCGATTA CATCGCCCTG
 AACGAAGACC TGAAAACGTG GGCGGCGGCG GACTTTGAGG CACAGAAGAC
 CCGGAGCAAG TGGGAGAGGG AAGGTGTTGC AGAGAGAAGC AGGGCCTACC
 TGGAGGGCGA GTGTGTGAAG TGGCTCAGGA GACACCTGGA GCACGGGAAG
 GAGGCGCTGC TGCGCTTAGA TCCCCCAGAG GCACATGTGA CCCTTCACCC
 CAGACCTGAA GGTGATGTCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCTGACAT CACATTGACC TGGCAGTTGA ATGGGGAGGA CCTAACCCAG
 GACATGGAGT TTGTGGAGAC CAGGCCTGCA GGGGATGGAA CCTTCCAGAA
 GTGGGCATCT GTGGTGGTGC CTCTTGGGAA GGAGCAGAAT TACACATGCC
 TTGTGGAGCA TGAGGGGCTG CCTGAGCCTC TTACCCAGAG ATGGGAGCCT
 TCTCCATCCA CCAACACCAA CATGGGAATC GATGTTACTT CTGTTTTTCT
 TGGACCTTTG GCTGTCTTTG TAGTTTTGGC CATCATTGGA GCTGCGGTGG
 CTGTTGTGAG GAGGAGGAGG AGGAGAAACA CAGGTGGGGA AGGAGGAGAC
 TACACCCCTG CTCCAGGCAG GGACAGCTCC TAG*

>DL;RT1-CE11_n
RT1-CE11_n  1104 bases  
 ATGGGGTCAA GGGCACCTCA CACTCTGCTC CTGCTGCTGG TGGCCGCCCT
 GGCCCAGACC CAGCCCCGCG CGGGCTCGCA CTCGCTGTGG TATTTCACCT
 CGGCGCTGTC CTGGCCCGGC CTCGGGGAGC CCCGGTTCAT CTCTGTCCGC
 TATGTGGACG ACACGGAGTT CGTGCGCTTC GACAGCGGCT CTGAGAATCC
 GAGATACGAG CCGCGGGCGC CGTGGATGGA GCGGGAGGGG CCGGAGTATT
 GGGAGCAGCA GACACGGAGA GCCAAGGGCA ACCAGCAGAC TTTCCAAGTG
 AACCTGAGGA CCGCGCTCCG CTACTACAAC CAGAGCGAGG ACCGCTCTCA
 CACCATCCAG AGGATGTATG GCTGTGACAT GGGGTCGGAC AGGAGCCTCC
 TCCGCGGGTA TGAGCAGTAC GCCTACGACG GCCGCGATTA TATCGCCCTG
 AACGAAGACC TGAAGACCTG GACAGCAGCA GACGTGGCTG CGCAGATCAC
 CCGGAACAAG TGGGATCAGG CTGGTGTTGC AGAGAGACGC AGGGCCTACC
 TGGAGGGCAC GTGCGTGAAG TGGCTCCGCA GATACCTGGA GCACGGGAAG
 GAGACGCTGC TGCGCTCAGA TCCCCCAAAG GCACATGTGA CACTTCACCC
 CAGACCTGAA GGTGATGTGA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCTGACAT CACCCTGACC TGGCAGTTGA ATGGGGAGGA CCTGACCCAG
 GACATGGAGC TTGTGGAGAC CAGGCCTGCA GGGGATGGAA CCTTCCAGAA
 GTGGGCATCT GTGGTGGTGG CTCTTGGGAA GGAGCAGAAG TACACATGCC
 TTGTGGAGCA TGAGGGGCTG CCTGAGCCGC TTACCCAGAG ATGGGAGGCT
 CCTCCATCCA CTGACTCCAA CATGGAAACC AATGTCATTT ATGTTGTCGT
 TGGAGCCCTG GTCATCACTG GAGCTGTGAT CATTGGAGCT GTGGTGGCTG
 TTGTGAGGAA GAGAAACACA GGAGGAACAG GAGGAGACTA CGCCCCTGCT
 CCAGGCAAGG CCAACCCCAA CAGCTCTGTG TCTCTCCCAG ATTGTAAAGC
 ATGA*

>DL;RT1-CE12_n
RT1-CE12_n  1116 bases  
 ATGGGGGTGA CTGCGCCGCC CTTGCTGCTC CTGCTGCTGG CGGCCGCCTT
 GGCCCGGACC CAGACCCGCG CGGGCTCACA CTCGCTGCGG TATTTCAAAA
 CCGCCGTGTC CCGGCCCGGC CTCGGGGAGC CCCGGTTCAT GGAAGTCGGC
 TACGTGGACG ACACGGAGTT CGTGCGCTTC GACAGTGACG CGGAGAATCC
 GAGATACGAG CCGCGGGCCC GGTGGATGGA GCAGCAGGGG CCGGAGTATT
 GGGAGCGGGA GACGCAGGGA GCCAAGGAAA AGGAGCAGAC TTTCCGAGTG
 AACCTGAGGA CACTGCTTGG CTACTACAAC CAGAGCGAGG GCGACTCTCA
 CACACTCCAG TTGATGTTTG GCTGTGACGT GGGGTCGGAC GGGAGGCTCC
 TCCGCGGGTA TGATCAGTTC GCCTACGACG GCCGCGATTA CATCGCCCTG
 AACGAAGACC TGAAAACGTG GGCGGCGGCG GACGTGGTGG CGCAGATGAC
 CCGAAACAAG TGGGAGCGGG CTCGTTATGC AGAGAAACGC AGGGCCAATC
 TGGAAGGAGA GTGTGTGGAG TCGCTCCGCA GATTCCTGGA ACTCGGGAAG
 GAGACGCTGC TGCGCTCAGA TCCCCCAAAG GCACATGTGA CCCTTCACCC
 CAGACCTGAA GGTGATGTCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCTGACAT CACCCTGACC TGGCAGATGA ATGGGGAGGA CCTGACCCAG
 GACATGGAGC TTGTGGAGAC CAGGCCTGCA GGGGATGGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTCTTGGGAA GGAGCAGAAT TACACATGCC
 TTGTGGAGCA TGAGGGGCTG CCTGAGCCTC TCACCTTGAG ATGGGAGCCT
 CCTTCATCCA CCAACTCCAA CATGGAATTC AATGTCATTT ATGTTGTCCT
 TGGAGCCATC TCTGCTGTGG CCATCAGTGG AGCTGTGATC ATTGGAGCTG
 TGTTGGCTGT TGTGAGGAAG AGAAACACAG GTGGGGAAGG AGGAGACTAC
 ACCCCTGCTC CAGACAGGGA CAGCTGCCAG AGCTCTAATG TGTCTCTCCC
 AGATTGTAAA GCATGA*

>DL;RT1-CE13_n
RT1-CE13_n  1098 bases  
 ATGGGGGCGA TGGCACCGCG CATGCTACTC CTGCTGCTGG CGGCCGCCCT
 GGCCCCGACC CAGACCCGCG CGGGCTCACA CTCGCTGCTG TATTTCTACA
 CCGCCATGTC CCGGCCCGGC CTCGGGGAGC CCTGGTTCAT GGAAGTCGGC
 TACGTGGACG ACACGGAGTT CGTGCGCTTC GACAACGACG CGGAGAATCC
 GAGGATGGAG CCGCGGGCGC GGTGGATGGA GCGGGAGGGG CCGGAGTATT
 GGGAGAGGAA CACACGGATC GCCAAGGAAA ACGAGCAGTG GTCCCGAATG
 GGCCTGAGGA ACCTGCGCGG CTACTACAAC CAGAGCGAGG GCGGCTCTCA
 CACCGTCCAG AGATTGTATG GTTGTGACGT GGGGTCGGAC GGGAGCCTCC
 TCCGCGGGTA TGATCAGTTC GCCTACGATG GCCGCGATTA CATCTCCCTG
 AATGAAGACC TGAAAACGTG GGCGGCGGCA GACCTGGCAG CACAGAAGAC
 CCGGAACAAG TGGGATCAGG CTGGTACTGC AGAGAGACGC AGGGCCTACC
 TGGAGGGCAC GTGCTTGGAG TGGCTCCGCA GATACCTGGA GCTCGGGAAG
 GAGACGCTGC TGCGCTCAGA TCCCCCAGAG GCACATGTGA CCCTTCACCC
 AAGACCTGAA GGTGGTGTCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTCCTGGTAT CTCCTTGATC TGGCAGTTGA ATGGGGAGGA CCTGACCCAG
 GACATGGAGC TTGTGGAGAC CAGGCCTGCA GGGGATGGAA CCTTCCAGAA
 GTGGGCATCT GTGGTGGTGC CTCTTGGGAA GGAACAGAAT TACACATGCC
 ATGTAGAGCA TGAGGGGCTG CCTGAGCCTC TCACCCTGAG ATGGGAGCCT
 CCTTCATCCA CAGACTTCAA CATGAGAATC ATTGCTGTTC TGGTTGTCCT
 TGGAGCTGTG GCCATCATTG GAGCTGTGGT GGCTGTTATG ATGAAGTGGA
 GGAGAAACAC AGGAGGAACA GGAGGAGACT ACACCCCTGC TCCAGGTAAG
 GCCAGCCCCA ACAGCTGTGA TTTGTCTCTC CCACTTTGTA AAGCATGA*

>DL;RT1-CE14_n
RT1-CE14_n  1053 bases  
 ATGGTGCCGC CCAAGCTGCT CCCACTGCTG GCCGCTGTCC TGGCCCCGAC
 TCAGACTCAA GGCGGTGAGT GCCGCTCACA CTCGCTGCGG TATTTCAAAA
 CCGCCGTGTC CCGGCCCGGC CTCGGGGAGC CCCGGTTCAT GGAAGTCGGC
 TACGTGGACG ACACGGAGTT CGTGCGCTTC GACAGCGACG CGGAGAATCC
 GAGATACGAG CCGCGGGCCC GGTGGATGGA GCAGCAGGGG CCGGAGTATT
 GGGAGCGGGA GACGCAGGGA GCCAAGGAAA AGGAGCAGAC TTTCCGAGTG
 AACCTGAGGA CCCTGCTTGG CTACTACAAC CAGAGCGAGG GCGACTCTCA
 CACACTCCAG TTGATGTTTG GCTGTGACGT GGGGTCGGAC GGGAGCCTCC
 TCCGCGGGTA TGATCAGTTC GCCTACGACG GCCGCGATTA CATCGCCCTG
 AACGAAGACC TGAAAACCTG GGCGGCGGCG GACGTGGTGG CGCAGATGAC
 CCGAAACAAG TGGGAGCGGG CTCGTTATGC AGAGAAACGC AGGGCCAACC
 TGGAAGGCGA GTGTGTGGAG TCGCTCCGCA GATACCTGGA ACTCGGGAAG
 GAGACGCTGC TGCGCTCAGA TCCCCCAAAG GCACATGTGA CCCTTCACCC
 CAGACCTGAA GGTGATGTCA CTCTGAGGTG CTGGGCCCTG GGCTTTTACC
 CTGCTGAAAT CACCCTGACC TGGCAGTTGA ATGGGGAGGA TCTGAGCCAG
 GACATGGAAC TTGTGGAGAC CAGGCCTGCA GGGGATGGAA CCTTCCAGAA
 GTGGGCATCT GTGGTGGTGC CTCTTGGGAA GGAGCAGAAT TACACATGCC
 TTGTGGAGCA TGAGGGGCTG CCTGAGCCTC TCACCCTGAG ATGGGAGCTG
 CCTCCATCCA CCGACTCCAA CATGGAAACC AATGTTATTT ATGTTGTCTT
 TGGAGCTGTG ACCATCATTG GAGCTGTGGC CATCATTGGA GCTGTGGCCA
 TCATTGGAGT TTGTGTGAGG AGGAGAAGGA GGAGAAACAT AGGTGGAATA
 TGA*

>DL;RT1-CE15_n
RT1-CE15_n  1122 bases  
 ATGGGGGCGA TGGCCCGGCG CACGCTGCTC CTGCTGCTAG CGGCCGCCCT
 GGCCCCGACC CAGACCCTCC CGAGCTCACA TTCGATGCGG TGTTTCAAAA
 CCGCCGTGTC CCGGCCGGGC CTCGGGGAGC CCCGGTTCAT AGCTGTCGCC
 TACGTGGACG ACACGGAGTT CGTGCGCTAC GACGGCGACG CGGAGAATCC
 GAGGACCGAG CCGCGGGCGC GGTGGATGGA GCGGGAGGGG CCGGAGTACT
 GGGAGGAGGA GACACGGAAA ATCAAGGGAC AGGAGCAGTG GTTCCGAATG
 AGCCTGAGGA TCTTGCGCGG CTACTACAAC CAGAGCGAGG GCGGATCGCA
 CACCTTCCAG AAGATGTCCG GCTGTGACGT GGGGTCAGAC GGGAGCCTCC
 TCCGCGGGTA TAATCAGTAC GCCTACGACG GCCACGATTA CATCGCCCTG
 AACAAAGACC TGAAGACCTG GACAGCGGCG GACTTTGCAG CACTGATCAC
 CAAAACCAAG TGGGATCAGG CTGGTACTGC AGAGAGAAAG AGGGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GCTCGGGAAG
 GAGACGCTGC TGCGCTCAGA TCCCCCAAAG GCACATGTGA CCCTTCACCC
 CAGACCTGAA GGTGATGTCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCTGACAT CACCCTGACC TGGCAGTTGA ATGGGGAGGA CCTGACCCAG
 GACATGGAGC TTGTGGAGAC CAGGCCTGCA GGGGATGGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTCTTGGGAA GGAGCAGAAT TACACATGCC
 TTGTGGAGCA TGAGGGGCTG CCTGAGCCTC TCACCCTGAG ATGGGAGGCT
 CCTCCAGGCA CTGACTCCAA CATGGAAACC AAAGTTATTT ATGTTGTCCT
 TGGAGCTGTG GCCATGATTG GAGCTGTGGC CGTGATTGGA GCTGTGGTGG
 CTGTTGTGAG GAGGAGGAGG AGGAAGAGAA ACACAGGTGG AACAGGAGGA
 GACTACGCCC CTGCTCCAGG CAGTGACAGC TGCCAGAGCT CTGATGTGTC
 CCTCGCAGAT TGTGAAGCAT GA*

>DL;RT1-CE16_f
RT1-CE16_f  1041 bases  
 GGCTCACACT CGCTGCGGTA TTTCGTCACC GCCATGTCCG GGCCCGGCCT
 CGGGAAGCCC CGATTCATGG AAGTCGGCTA CGTGGACGAC ACGGAGTTCG
 TGCGCTACGA CAGCGACGCG AAGAATCCGG GGATGGAGCC GCGGGCGAGG
 TGGATGGAGC GGGAGGGGCG GGAGTATTGG GAGCGGGAGA CACGGATCGC
 CAAGGGAAAC GAGCAGACTT TCCGAGAGAA CCTGAGGACC CTGCTCCGCT
 ACTACAACCA GAGCGAGGGC GGCTCTCACA CCTTCCAGTG GATGTCTGGC
 TGTGACGTGG GGTCGGACGG GAGCCTCCTC CGCGGGTATG AGCAGTTCGC
 CTACGACGGC CGCGATTACA TCGTCCTGAA CGAAGACCTG AAAACGTGGA
 CGGCGGCGGA CACGGCGGCA CGGATCACCC GGAACAAGTG GGATCGGGCT
 GGTGTTGCAG AGAGACACAA GGCCTACCTG GAGGGCAAGT GCTTGGAGTC
 GCTCCTCAGA TACCTGGAGC TCGGGAAGGA GACGCTGCTG CGCTCAGATC
 CCCCAAAGGC ACATGTGACC CTTCACCCCA GACCTGAAGG TGATGTCACC
 CTGAGGTGCT GGGCCCTGGG CTTCTACCCT GCTGGCATCT CCCTGACCTG
 GCAGTTGAAT GGGGAGGACC TGACCCAGGA CATGGAGCTT GTGGAGACCA
 GGCCTGCAGG GGATGGAACC TTCCAAAAGT GGGCATCTGT GGTGGTGCCT
 CTTGGGAAGG AGCAGAATTA CACATGCCTT GTGGAGCATG AGGGGCTGCC
 TGAGCCGCTT ACCCAGAGAT GGGAGCCTTC TCCATCGACC GACTCCAACA
 TGGAAACCTA TGTCATTTAT GTCATCCTTG GAGCTGTGGC CATCATTGCA
 GCTGTGATCA TTGTAGCTGT GGTGGCTGTT GTGATGAAGA GGAGGAGAAA
 CACAGGTGGA AAAGTAGGAG TCTACGCCCC TGCTCCAAGC AGGGACAGCT
 CTGAGAGCTC TGATGTGTCT CTCTCAGATT GTAAAGCATG A*

>DL;RT1-CE16_g
RT1-CE16_g  1041 bases  
 GGCTCACACT CGCTGCGGTA TTTCGTCACC GCCATGTCCG GGCCCGGCCT
 CGGGAAGCCC CGATTCATGG AAGTCGGCTA CGTGGACGAC ACGGAGTTCG
 TGCGCTACGA CAGCGACGCG AAGAATCCGG GGATGGAGCC GCGGGCGAGG
 TGGATGGAGC GGGAGGGGCG GGAGTATTGG GAGCGGGAGA CACGGATCGC
 CAAGGGAAAC GAGCAGACTT TCCGAGAGAA CCTGAGGACC CTGCTCCGCT
 ACTACAACCA GAGCGAGGGC GGCTCTCACA CCTTCCAGTG GATGTCTGGC
 TGTGACGTGG GGTCGGACGG GAGCCTCCTC CGCGGATATG AGCAGCACGC
 TTACGACGGC CGCGATTACA TCGTCCTGAA CGAAGACCTG AAAACGTGGA
 CGGCGGCGGA CACGGCGGCA CGGATCACCC GGAACAAGTG GGATCGGGCT
 GGTGTTGCAG AGAGACACAA GGCCTACCTG GAGGGCAAGT GCTTGGAGTC
 GCTCCTCAGA TACCTGGAGC TCGGGAAGGA GACGCTGCTG CGCTCAGATC
 CCCCAAAGGC ACATGTGACC CTTCACCCCA GACCTGAAGG TGATGTCACC
 CTGAGGTGCT GGGCCCTGGG CTTCTACCCT GCTGGCATCT CCCTGACCTG
 GCAGTTGAAT GGGGAGGACC TGACCCAGGA CATGGAGCTT GTGGAGACCA
 GGCCTGCAGG GGATGGAACC TTCCAAAAGT GGGCATCTGT GGTGGTGCCT
 CTTGGGAAGG AGCAGAATTA CACATGCCTT GTGGAGCATG AGGGGCTGCC
 TGAGCCGCTT ACCCAGAGAT GGGAGCCTTC TCCATCGACC GACTCCAACA
 TGGAAACCTA TGTCATTTAT GTCATCCTTG GAGCTGTGGC CATCATTGCA
 GCTGTGATCA TTGTAGCTGT GGTGGCTGTT GTGATGAAGA GGAGGAGAAA
 CACAGGTGGA AAAGTAGGAG TCTACGCCCC TGCTCCAAGC AGGGACAGCT
 CTGAGAGCTC TGATGTGTCT CTCTCAGATT GTAAAGCATG A*

>DL;RT1-CE16_n
RT1-CE16_n  1113 bases  
 ATGGGGGCGA TGGCACCGCG CACGCTGCTC CTGCTGCTGG CGGCCGCCCT
 GGCCCCGACG CAGACTCGCG CGGGCTCACA CTCGCTGCGG TATTTCGTCA
 CCGCCATATC CGGGCCCGGC CTCGGGGAGC CCCGATTCAT GGAAGTCGGC
 TACGTGGACG GCACGGAGTT CGTGCGCTAC GACAGCGACG CAAAGAATCC
 GGGGATGGAG CCGCGGGCGA GGTGGATGGA GCGGGAGGGG CGGGAGTATT
 GGGAGCGGGA GACACGGAGA GTCAAGGAAA ACGAGCAGTT GTTCCGAGGG
 AACCTGAGGA CCCTGCTTGG CTACTACAAC CAGAGCGAGG GCGGCTCTCA
 CACCATCCAG TGGATGTCTG GCTGTGACGT GGGGTCGGAC GGGAGCCTCC
 TCCGCGGGTA TGATCAGTTC GCCTACGACG GCCGCGATTA CATCGTCCTG
 AACGAAGACC TGAAAACGTG GACGGCGGCG GACACGGCGG CACGGATCAC
 CCGGAACAAG TGGGATCGGG CTGGTGTTGC AGAGAGACAC AAGGCCTACC
 TGGAGGGCAA GTGCTTGGAG TCGCTCCTCA GATACCTGGA GCTCGGGAAG
 GAGACGCTGC TGCGCTCAGA TCCCCCAAAG GCACATGTGA CCCTTCACCC
 CAGACCTGAA GGTGATGTCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCTGGCAT CTCCCTGACC TGGCAGTTGA ATGGGGAGGA CCTGACCCAG
 GACATGGAGC TTGTGGAGAC CAGGCCTGCA GGGGATGGAA CCTTCCAAAA
 GTGGGCATCT GTGGTGGTGC CTCTTGGGAA GGAGCAGAAT TACACATGCC
 TTGTGGAGCA TGAGGGGCTG CCTGAGCCGC TTACCCAGAG ATGGGAGCCT
 TCTCCATCGA CCGACTCCAA CATGGAAACC TATGTCATTT ATGTCATCCT
 TGGAGCTGTG GCCATCATTG CAGCTGTGAT CATTGTAGCT GTGGTGGCTG
 TTGTGATGAA GAGGAGGAGA AACACAGGTG GAAAAGTAGG AGTCTACGCC
 CCTGCTCCAA GCAGGGACAG CTCTGAGAGC TCTGATGTGT CTCTCTCAGA
 TTGTAAAGCA TGA*

>DL;RT1-CE1_c
RT1-CE1_c  998 bases  
 CGGCTCACAC TCGCTGCGGT ATTTCAAAAC CGCCGTGTCC CGGCCGGGCC
 TCGGGGAGCC CCGGTTCATG GAAGTCGGCT ATGTGGACGA CACGGAGTTC
 GTGCGCTTCG ACAGTGACGC GGAGAATCCG AGATGCGAGC CGCGGGCGCG
 GTGGATGGAG CGGCAGAGGC CGGAGTATTG GGAGCGGGAG ACGCAGGGAG
 CCAAGGAAAA GGAGCAGACT TTCCGAGTGA ACCTGAGGAC CCTGCTTGGC
 TACTACAACC AGAGCGAGGG CGACTCTCAC ACACTCCAGT TGATGTTTGG
 CTGTGACCTG GGGTCGGACG GGAGGCTCCT CCGCGGGTAT GATCAGTTCG
 CCTACGACGG CCGCGATTAC ATCGCCCTGA ACGAAGACCT GAAAACGTGG
 GCGGCGGCGG ACGTGGTGGC GCAGATGACC CGAAACAAGT GGGAGCGGGC
 TCGTTATGCA GAGGAACGCA GGGCCAATCT GGAAGGAGAG TGTGTGGAGT
 CGCTCCGCAG ATACCTGGAA CTCGGGAAGG AGACGCTGCT GCGCTCAGAT
 CCCCCAAAGG CACATGTGAC CCTTCACCCC AGACCTGAAG GTGATGTCAC
 CCTGAGGTGC TGGGCCCTGG GGTTATACCC TGCTGACATC ACCCTGACCT
 GGCAGTTGAA TGGGGAGGAC CTGACCCAGG ACATGGAGCT TGTGGAGACC
 AGGCCTGCAG GGGATGGAAC CTTCCAGAAG TGGGCAGCTG TGGTGGTGCC
 TCTTGGGAAG GAGCAGAATT ACACATGCCA CATGGAGCAT GAGGGGCTGC
 CTGAGCCTCT CACCTTGAGA TGGGAGGCCC CTCCATCCAC CAACTCCAAC
 ATGGAATTCA ATGTCATTTA TGTTGTCCTT GGAGCCATCT CTGCTGTGGC
 CATCATTGGA GCTGTGATCA TTGGAGGTGT GTTGGCTGTT GTGAGGAAGA
 GAAACACAGG TGGAACAGGA GGAGACTACA CCCCTGCTTC CAGCATGA*

>DL;RT1-CE1_n
RT1-CE1_n  1128 bases  
 ATGGGGGTGA CTGCGCCGCC CTTGCTGCTC CTGCTGCTGG CGGCCGCCTT
 GGCCCGGACC CAGACCCGCG CTGGCTCACA CTCGCTGCGG TATTTCAAAA
 CCGCCGTGTC CCGGCCGGGC CTCGGGGAGC CCCGGTTCAT GGAAGTCGGC
 TATGTGGACG ACACGGAGTT CGTGCGCTTC GACAGTGACG CGGAGAATCC
 GAGATACGAG CCGCGGGTGC GGTGGATGGA GCGGCAGAGG CCGGAGTATT
 GGGAGCGGGA GACGCAGGGA GCCAAGGAAA AGGAGCAGAC TTTCCGAGTG
 AACCTGAGGA CCCTGCTTGG CTACTACAAC CAGAGCGAGG GCGACTCTCA
 CACACTCCAG TTGATGTTTG GCTGTGACGT GGGGTCGGAC GGGAGGCTCC
 TCCGCGGGTA TGATCAGTTC GCCTACGACG GCCGCGATTA CATCGCCCTG
 AACGAAGACC TGAAAACGTG GGCGGCGGCG GACGTGGTGG CGCAGATGAC
 CCGAAACAAG TGGGAGCGGG CTCGTTATGC AGAGAAACGC AGGGCCAATC
 TGGAAGGAGA GTGTGTGGAG TCGCTCCGCA GATACCTGGA ACTCGGGAAG
 GAGACGCTGC TGCGCTCAGA TCCCCCAAAG GCACATGTGA CCCTTCACCC
 CAGACCTGAA GGTGATGTCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCTGACAT CACCCTGACC TGGCAGTTGA ATGGGGAGGA CCTGACCCAG
 GACATGGAGC TTGTGGAGAC CAGGCCTGCA GGGGATGGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTCTTGGGAA GGAGCAGAAT TACACATGCC
 ACATGGAGCA TGAGGGGCTG CCTGAGCCTC TCACCTTGAG ATGGGAGGCC
 CCTCCATCCA CCAACTCCAA CATGGAATTC AATGTCATTT ATGTTGTCCT
 TGGAGCCATC TCTGCTGTGG CCATCATTGG AGCTGTGATC ATTGGAGCTG
 TGTTGGCTGT TGTGAGGAAG AGAAACACAG GTAGGAAAGG GCAGGGTGGG
 AAAGGAGACT ACGCCCCTGC TCCAGACAGG GACAGCTGCC AGAGCTCTAA
 TGTGTCTCTC CCAGATTGTA AAGCATGA*

>DL;RT1-CE2_n
RT1-CE2_n  1098 bases  
 ATGGCGCCGC GCACGCTGCT CTTGCTTCTG GCCGCAGCCC TGGCCCGGAC
 CCAGACCCGG GAGGGCTCAC ACTCGCTGCG GTATTTCAAA ACCGCCGTGT
 CCCGGCCCGG CCTCGGGAAG CCCTTGTTCA TGGAAGTCGG CTACGTGGAC
 GACACGGAGT TCGTGCGCTT CGACAGCGAC GCGGAGAATC CGAGGATGGA
 GCCGCGGGCG CGGTGGATGG AGCGGGAGGG GCCGGAGTAT TGGGATCGGG
 AGACACGGAT CGCCAAGGGA AATGAGCAGA GGTTCCGAGT GCACCTGAGG
 ACCCTGCTTG GCCACTACAA CCAGAGCGAG GGCGGCTCTC ACACCTTCCA
 GTTGATGTAT GGCTGTGACC TGGGGTCGGA CGGGAGCCTC CTACGCGGGT
 ATGATCACTA CGCCTACGAT GGCCGCGATT ACATCGCCCT GAACGAAGAC
 CTGAAGACTT GGACGGCGGC GGACGCGGCG GCACGGATCA CCCTGAACCA
 GTGGCATCAG ACTGGTTATG CAGAGAGACG CAGGGCCGAC CTGGAGGGCG
 AGTGCGTGGA GTCACTCCGC AGATACCTGG AGCTCGGGAA GGAGACGCTG
 CTGCGCTCAG ATCCCCCAAA GGCACATGTG ACCCTTCACC CCAGACCTGA
 AGGTGATGTC ACCCTGAGGT GCTGGGCCCT GGGATTCTAC CCTGCTGACA
 TCACCATGAC CTGGCTGTTG AATGGGGAGG ACCTGAGCCA GGACATGGAG
 CTTGTGGAGA CCAGGCCTGC AGGGGATGGA ACCTTCCAGA AGTGGGCATC
 TGTGGTGGTG CCTCTTGGGA AGGAGCAGAA TTACACTTGC CTTGTGGAGC
 ATGAGGGGCT GCCTGAGCCG CTTTCCCAGA GATGGGAGCC TTCTCCATCC
 ACCGACTCCA ACATGGGAAT TGATGTTACT TCTGTTCTTC CTGGAGCTGT
 GGCTGTCTTT GTAGTTTTGG CCATCATTGG AGCTGTGGTG GCTATTGTGA
 GGAGGAGAAA CACAGGTGGG AAAGGAGACT ACGCCCCTGC TCCAGGCAGG
 GACAGCTCCC AGAGCTCTGA TGTGTCTTTC TCAGATTGTA AAGCATGA*

>DL;RT1-CE3_n
RT1-CE3_n  1059 bases  
 ATGGAGGTGA TGGCACCGCG GGCGCTGCTC CTGCTGCTGG CGGCCGCCCT
 GGCCCTGGCC CAGACCGGCA TAGGCTCACA CTCGCTGCGG TATTTCGAAA
 CCGCCTTGTC CCGGCCCGGC TTCGGGGAGT CCCGGTTCAT TATCGTCGGC
 TACGTGGACG ACACGCAGTT CATGCGCTTC GACAGCGACG CGGAGAATCC
 GAGGATGGAG CCGCGGGCGC GGTGGATGGA GCGGGAGGGG CCGGGGTATT
 GGGAGCAGAA CACACGGATG GCGAAGAGAC AAGAGCAATG GTACCGAGTG
 AACCTGAGGA CCGCGCTCCG CTACTACAAC CAGAGCGAGG GCGGCTCGCA
 CACCTTCCAG AGGATGTACG GCTGTGACGT GGGGTCGGAC GGAAGCCTCC
 TCCGCGGATA TAATCAGTTC GCCTACGACA GCCTCGATTA CATCGCCCTG
 AACGAAGACC TGAAGACCTG GACAGCGGCG GACACAACAG GACGGATGAC
 ACAGAGCAAG TGGGTTCAGG CTGGTGTTGC AGACTATTAC AGAGCCTACC
 TGGAGGGCGA GTGCGTGGAG TGGCTCCGCA GATACCTGGA ACTCGGGAAG
 GAGACGCTGA TGCGCTCAGA TCCCCCAAAG GCACATGTGA CCCTTCACCC
 CAGACCTGAA GGTGATGTCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCTGACAT CACCCTGACC TGGCAGTTGA ATGGGGAGGA CCTGACCCAG
 GACATGGAGC TTGTGGAGAC CAGGCCTGCA GGGGATGGAA CCTTCCAGAA
 GTGGGCATCT GTAGTGGTGC CTCCTGGGAA GGAGCAGAAT TACACATGCC
 TTGTGGAACA TGAGGGGCTG CCTGAGCCCC TCACCTTGAG ATGGGCGCCT
 TCTCTATCCA CTGACTCCAA CATGGAAACC ACTGTCATTT ATGTCGTCCT
 TGGAGCCATC TCTGCTCTGG CCATTATTGG AGCTCTGGTG CCTGTTGTGA
 GGAGGAGGAA GAGAAACACA GGTGGAAAAG GAGGAGTCTA CGCCCCTGCT
 CCAGGTTAG*

>DL;RT1-CE4_n
RT1-CE4_n  1122 bases  
 ATGGGGGCGA TGGCGCCGCC CACGCTGCTC CTGCTTGTTG CGGCCGCCCT
 GACCCCGACC AAGACGCGCG CCGGCTCACA CTCGCTGCGG TATTTCCACA
 CCGCCGTGTC CCGGCCCGGC CTCGGGGAGC CCCGGTTCAT CTCTGTCGGC
 TACGTGGACG ACACGGAGTT CGTGCGCTAC GATAGCGACG CGGAGAATCC
 GAGATATGAG CCGCGGGCGC GGTGGATGGA GCGGGAGGGG CCGGAGTATT
 GGGAGAGGCA GACACAGATC GCCAAGAGAA ACGAGCAGGT TTACCGAGTG
 GACCTGAGTA CCCTGCGAGG CTACTATAAC CAGAGCGAGG GCGGCTCTCA
 CACCTACCAG AGGATGCATG GCTGTGAGTT GGGGTCGGAC GGGAGCCTCC
 TCCGCGGGTA TATGCAGTAC GCCTATGACG GCCGCGATTA CATCGCCCTG
 AACGAAGACC TCAAAACGTG GATGGTGAAG GACACAGCAG CACGGATCAC
 CAGAAACAAG TGGGATCAGG CTGGTTTTGG AGAGAGAAAG AGGACCTACC
 TGCAGGTCGA GTGCTTGGAG TGGCTCCGCA AATACCTGGA GCTCGGGAAG
 GAGACACTGC TGCGCTCAGA TCCCCCTAAG GTACATGTGA CCCTTCACCC
 CAGACCTGAA GGTGGTGTCA CCCTGAGGTG CTGGGCTCTG GGCTTCTACC
 CTGCTGACAT CACCCTGACC TGGCAGTTGA ATGGGGAGGA CCTGACCCAG
 GACATGGAGC TTGTGGAGAC CAGGCCTGCA GGGGATGGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGGGA GGAGCAGAAG TACACATGCC
 ATGTGGAGCA TGAGGGGCTG CCTGAGCCAC TTACCCAGAG ATGGGAGGCT
 CCTCCAGGCA CTGACTCCAA CATGGAAACC AATGTTATTT ATGTTTTCTT
 TGGAGCTGTG GCCATGATTG GGGCTGTGGC TGTGATTGGA GCTGTGGTGG
 CTGTTGTGAG GAGGAGGAGG AGGAGGAAGA GAAACACAGG TGGGAAAGGA
 GACTACGCCC CTGCTCCAGG CAGTGACAGC TGCCAGAGCT CTGATGTGTC
 CCTCGCAGAT TGTGAAGCAT GA*

>DL;RT1-CE5_g
RT1-CE5_g  1045 bases  
 GGGCTCACAC TCGCTGCGGT ATTTCCACAC CGCCGTGTCC CGGCCCGGCC
 TCCGGGAGCC CCGGTTCATT ATCGTCGGCT ATGTGGACCA CACGGAGTTC
 GTGCGCTACG ACAGCGACGC AGAGAATCCG AGATACGAGC CGCGGGCGCG
 GTGGATGGAG CGGGAGGGGC CGGAGTATTG GGAGCAGCAG ACACAGATCG
 TCAAGGGACA CGAATGGAGT TTCCGAGTGA GCCTGAGGAA TCTGCTAGGC
 TACTACAACC AGAGCGAGGG CGGCTCTCAC ACACTCCAGG TGATGTCTGG
 ATGTGACATG GGGTCGGACC GGAGCCTGCG CCGCGGGTAT GAGCAATACG
 CCTATGACGG CCGCGATTAC ATCTCCCTGA ACGAAGACCT GAAGACGTGG
 TCGGCTGCGG ACTTGGCAGC ACAGATCACT CTAAACAAGT GGGATCAGGC
 TGGTGAATTA GACTATTACA AGGCCTACCT GGAGGGTCCC TGCCTGGAGT
 GGCTTCTCAG ATACCTGGAG CACGGGAAGG AGACACTGAT GCGCTCAGAT
 CCCCCAGAGG CACATGTGAC CCTTCACCCC AGACCTGAAG GTGATGTCAC
 CCTGAGGTGC TGGGCCCTGG GCTTCTACCC TGCTGACATC ACCCTGACCT
 GGCAGTTGAA TGAGGAGGAC CTGACCCAGG ACATGGAGCT TGTGGAGACC
 AGGCCTGCAG GGGATGGAAC CTTCCAGAAG TGGGCATCTG TGGTGGTGCC
 TCTTGGGAAG GAGCAGAATT ACACATGCCT TGTGGAGCAT GAGGGGCTGC
 CTGAGCCTCT CACCTTGAGA TGGGAGGCTC CTCCCTCCAC CAACTCCAAC
 ACGGGAATGT CTGTTATTCT TGGAACTGTG ACCATCATTG CAGTTATGGC
 CATCATTGTA GTTGTAGCCG TCATTAGAAC TGTTGTGAGG AAGAGATGGA
 TAAAAACAGG TGGGAAAGGA GGAGACTACG CCCCTGCTCC AGGCAGGGAC
 AGCTGCCAGA GCTCTGATGT GTCTCTCCCA GATTGTAAAG CATGA*

>DL;RT1-CE5_l
RT1-CE5_l  921 bases  
 GGCTCACACT CGCTGCGGTA TTTCCACACC GCCGTGTCCA GGCCCGGCCT
 CCGGGAGCCC CGGTTCGTTA TCGTCGGCTA TGTGGACCAC ACGGAGTTCG
 TGCGCTACGA CAGCGACGCA GAGAATCCGA GATACGAGCA GCGGGCGCGG
 TGGATGGAGC GGGAGGGGCC GGAGTATTGG GAGCAGCAGA CACAGATCGT
 CAAGGGACAC GAATGGAGTT TCCGAGTGAG CCTGAGGAAT CTGCTAGGCT
 ACTACAACCA GAGCGAGGGC GGCTCTCACA CGCTCCAGGT GATGTCTGGA
 TGTGACATGG GGTCTGACCG GAGCCTGCGC CGCGGGTATG AGCAATACGC
 CTATGACGGC CGCGATTACA TCTCTCTGAA CGAAGACCTG AAGACGTGGT
 CGGCTGCGGA CTTGGCAGCA CAGATCACTC TAAACAAGTG GGATCAGGCT
 GGTGAATTAG ACTATTACAA GACCTACCTG GAGGGTCCAT GCCTGGAGTG
 GCTTCTCAGA TACCTGGAGC ACGGGAAGGA GACACTGATG CGCTCAGATC
 CCCCAAAGGC ACATGTGACC CTTCACCCCA GACATGAAGG TGATGTGACC
 CTGAGGTGCT GGGCCCTGGG CTTCTACCCT GCTGACATCA CCCTGACCTG
 GCAGTTGAAT GGGGAGGACC TGACCCAGGA CATGGAGCTT GTGGAGACCA
 GGCCTGCAGG GGATGGAACC TTCCAGAAGT GGGCATCTGT GGTGGTGCCT
 CTTGGGAAAG AGCAGAAGTA CACATGCCTT GTAGAACATG AGGGGCTGCC
 TGAGCCTCTT ACCTTGAGAT GGGCTTTTCT TCTCACAAGT GGAAAAGGAG
 TTTACACCCC TGCTCCAGGC AGGGACAGCT CCCAGAGCTC TGATGTGTCT
 CTCCCAGATT GTAAAGCATG A*

>DL;RT1-CE5_n
RT1-CE5_n  1113 bases  
 ATGGGGGCGA TGGCACCGCG CACGCTGCTC CTGCTGCTGG CGGCGGCCCT
 GGCCCCAACC CGGACCCGCG CGGGCTCACA CTCGCTGCGG TATTTCCACA
 CCGCCGTGTC CCGGCCCGGC CTCGGGGAGC CCCGGTTCAT TATCGTCGGC
 TATGTGGACC ACACGGAGTT CGTGCGCTAC GACAGCGACG CAGAGAATCC
 GAGATACGAG CCGCGGGCGC GGTGGATGGA GCGGGAGGGG CCGGAGTATT
 GGGAGCAGCA GACACAGATC GTCAAGGGAC ACGAATGGAG TTTCCGAGTG
 AGCCTGAGGA ATCTGCTAGG CTACTACAAC CAGAGCGAGG GCGGCTCTCA
 CACACTCCAG GTGATGTCTG GATGTGACAT GGGGTCGGAC CAGAGCCTGC
 GCCGCGGGTA TGAGCAATAC GCCTATGACG GCCGCGATTA CATCTCCCTG
 AACGAAGACC TGAAGACGTG GTCGGCTGCG GACTTGGCAG CACAGATCAC
 TCTAAACAAG TGGGATCAGG CTGGTGAATT AGACTATTAC AAGGCCTACC
 TGGAGGGTCC ATGCCTGGAG TGGCTTCTCA GATACCTGGA GCACGGGAAG
 GAGACACTGA TGCGCTCAGA TCCCCCAAAG GCACATGTGA CCCTTCACCC
 CAGACCTGAA GGTGATGTGA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCTGACAT CACCCTGACC TGGCAGTTGA ATGGGGAGGA CCTGACCCAG
 GACATGGAGC TTGTGGAGAC CAGGCCTGCA GGGGATGGAA CCTTCCAGAA
 GTGGGCATCT GTGGTGGTGC CTCTTGGGAA GGAGCAGAAT TACACATGCC
 TTGTGGAGCA TGAGGGGCTG CCTGAGCCCC TCACCTTTAG ATGGGAGGCT
 CCTCCCTCCA CCAACTCCAA CACGGGAATG TCTGTTATTC TTGGAACTGT
 GACCATCATT GCAGTTATGG CCATCATTGT AGTTGTAGCC GTCATTAGAA
 CTGTTGTGAG GAAGAGATGG ATAAAAACAG GTGGAAAAGG AGTCTACACC
 CCTGCTCCAG GCAGGGACAG CTCCCAGAGC TCTGATGTGT CTCTCCCAGA
 TTGTAAAGCA TGA*

>DL;RT1-CE7_n
RT1-CE7_n  1068 bases  
 ATGGGGTCAA GGGCACCTCA CACTCTGCTT CTGCTGCTGG CGGCCGCCCT
 GGCCCGGACC CAGCCCCGCG CGGGCTCGCA CTCGCTGCGG TATTTCACCA
 CGGCGCTGTC CCGGCCCGGC CTCGGGGAGC CCCGGTTCAT CTCTGTCGGC
 TACGTGGACG ACACGGAGTT CGTGCGCTTC GACAGCGACG CGGAGAATCC
 GAGATACGAG CCGCGGGCGC CGTGGATGGA GCGGGAGGGG CTGGAGTATT
 GGGAGCAGCA GACACGGAGA GCCAAGGGCA ACCAGCAGAC TTTCCAAGTG
 AACCTGAGGA CCGCGCTCCA CTACTACAAC CAGAGCGAGG ACCGCTCTCA
 CACCATCCAG AGGATGTATG GCTGTGACGT GGGGTCGGAC GGGAGCCTCC
 TCCGCGGGTA TGAGCAGTCC GCCTACGATG GCCGCGATTA TATCGCCCTG
 AACGAAGACC TGAAGACCTG GACAGCAGCA GACGTGGCTG CGCAGATCAC
 CCGGAACAAG TGGGATCAGG CTGGTGTTGC AGAGAGACGC AGGGCCTACC
 TGGAGGGCAC ATGCATGAAG TGGCTCCGCA GATACCTGGA GCATGGGAAG
 GAGACGCTGC TGCGCTCAGA TCCCCCAAAG GCACATGTGA CCCTTCACCC
 CAGACCTGAA GGTGATGTCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCTGACAT CACCCTGACC TGGCAGTTGA ATGGGGAGGA CCTGACCCAG
 GACATGGAGC TTGTGGAGAC CAGGCCTGCA GGGGATGGAA CCTTCCAGAA
 GTGGGCATCT GTGGTGGTGC CTCCTGGGAA GGAGCAGAAT TACACATGCC
 GTGTGGAGCA TGAGGGGCTG CCTGAGCCCC TCACCTTGAG ATGGGAGGCT
 CCTCCATCCA CTGACTCCAA CATGGAAACC AATGTCATTT ATGTTGTCAT
 TGGAGCCATC TCTGCTGTGG CCATCATTGG AGCTGTGTTG GCTGTTGTGA
 GGAAGAAAAA CACAGGAGGA ACAGGAGGAG ACTACACCCC TGCTCCAGGC
 CAGCCCCAAC AGCTGTGA*

>DL;RT1-C_l
RT1-C_l  1107 bases  
 ATGGCACCGC GCACGCTGCT CCTGCTGCTG GCGGCCGCCC TGGCCCCGAC
 CCAGGTTCGC GCGGGCTCAC ACTCGCTGCG GTATTTCCAC ACCGCCGTGT
 CCCGGCCCGG CCTCGGGGAG CCCCGGTTCA TTATCGTCGG CTACGTGGAC
 GACACGGAGT TCGTGCGCTA CGACAGCGAC GCGGAGAATC CGAGATACGA
 GCCGCGGGTT GGGTGGATGG AGCGGGAGGG TCCGGAGTAT TGGGAGCGGG
 AGACACTGAT GGTCAAGGAA AACGAGCAGG TTTACCGAGT GAGCCTGAGG
 ACCCTGCTCC GCTACTACAA CCAGAGCGAG GGCGGCTCTC ACACCATCCA
 GTGGATGTCC GGCTGTGACG TGGGGTCGGA CGGGAGCCTC CTCCGCGGGT
 ATGATCAGTT CGCCTACGAC GGCCGCGATT ACCTCGCCCT GAACGAAGAC
 CTGAAAACGT GGATGGCGGC GGACACGGCG GCACAGATGA CCCGAAACAA
 GTGGGATCAG GCAGGTGAAG CAGAGAGACA CAAGGCCTAC CTGCAGGGCA
 CGTGTGTGGA GTGGCTCCGC AGATACCTGG AGCTCGGGAA GGAGACGCTG
 CTGCGCTCAG ATCCCCCAAA GGCACATGTG ACCCTTCACC CCAGACCTGA
 AGGTGATGTC ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCTGGCA
 TATTCCTGAC CTGGCTGTTG AATGGGGAGG ATCTGACCCA GGACATGGAG
 CTTGTGGAGA CCAGGCCTGC AGGGGATGGA ACCTTCCAGA AGTGGGCATC
 TGTGGTGGTG CCTCTTGGGA AGGAGCAGAA TTACACATGC CTTGTGGAGC
 ATGAGGGGCT GCCTGATCCT CTCACCCTGA GATGGGAGGC TCCTCCATCC
 ACTGACCCCA ACATGGAAAC CACTGTCATT TATGTTGTCG TTGGAGCTGT
 GGTCATCACT GGAGCTGTGA CCATGATTGG AGCTCTGCTG ACTGTTGTGA
 GGGGGAGGAA GAGAAACACA GGTGGGAAAG TAGGAGTCTA CACCCCTGCT
 CCAGGCAAGG ACAGCTCCGA GAGCTCTGAT GTGTCTCTCC CAGATTGTAA
 AGCATGA*

>DL;RT1-Cc22_c
RT1-Cc22_c  889 bases  
 CGGCTCACAC TCGCTGCGGT ATTTCCACAC CGCCGTGTCC CGGCCCGGCC
 TCGGGGAGCC CCGGTTCATT TCTGTCGGCT ACGTGGACGA CACACAGTTC
 GTGCGCTACG ACAGCGACGC GGAGAATCCG AAATACGAGC CGCGGGCGCG
 GTGGATGGAG CGGGAGGGGC CGGAGTATTG GGAGGAGCAG ACACGGGTCG
 CCAAGGGACA GGAGCAGGAT TACCGAGTGA GCCTGAGGAA CCTGCTAAGC
 TACTACAACC AGAGCGAGGG CGGCTCTCAC ACCATCCAGA GGATGTATGG
 CTGTGACGTG GGGTCCGACG GGAGCCTCCT CCGCGGGTAT GAGCAGCACG
 CCTACGACGG CCGCGATTAC ATCGCCCTGA ACGAAGACCT GAAAACATGG
 GCTGTGGCAG ACTTTGCAGC ATGGATCACC CGGAGCAAGT GGCAGCGGAA
 TGGTGCTGCA GAGAGAAGCA GGGCCTATGT GGAGGGCACG TGTGTGGAGT
 GGCTCCTCAG ATACCTGGAG CGCGGGAAGG AGACGCTGCT GCGCTCAGAT
 CCCCCAGAGG CACATGTGAC CCTTCACCCC AGACCTGAAG GTGATGTGAC
 CCTGAGGTGC TGGGCCCTGG GCTTTTACCC TGCTGACATC ACCCTGACCT
 GGCAGTTGAA TGGGGAGGAC CTGACCCAGG ACATGGAGCT TGTGGAGACC
 AGGCCTGCAG GGGATGGAAC CTTCCAGAAG TGGTCATCTG TGGTGGTGCC
 TCTTGGGAAG GAGCAGAATT ACACATGCCG TGTGGAGCAT GAGGGGCTGC
 CTGAGCCCCT TTCCCAGAGA TGGGAGCCTT CTCCATCCAC CGACTCCAAC
 TTACTTCTGT TGTTCTTGGA GCTGTGGCAG TTTTTGTAG*

>DL;RT1-Cc23_c
RT1-Cc23_c  877 bases  
 CGGCTCACAC TCGCTGCGGT ATTTCCACAC CGCCGTGTCC CGGCCCGGCC
 TCGGGGAGCC CCGGTTCATT TCTGTCGGCT ACGTGGACGA CACGCAGTTC
 GTGCGCTACG ACAGCGACGC GGAGAATCCG AAATACGAGC CGCGGGCGCG
 GTGGATGGAG CGGGAGGGGC CGGAGTATTG GGAGGAGCAG ACACGGGTCG
 CCAAGGGACA GGAGCAGGAT TACCGAGTGA GCCTGAGGAA CCTGCTAAGC
 TACTACAACC AGAGCGAGGG CGGCTCTCAC ACCATCCAGA GGATGTATGG
 CTGTGACGTG GGGTCCGACG GGAGCCTCCT CCGCGGGTAT GAGCAGCACG
 CCTACGACGG CCGCGATTAC ATCGCCCTGA ACGAAGACCT GAAAACATGG
 GCTGTGGCAG ACTTTGCAGC ATGGATCACC CGGAGCAAGT GGCGGCGGAA
 TGGTGCTGCA GAGAGAAGCA GGGCCTATGT GGAGGGCACG TGTGTGGAGT
 GGCTCCTCAG ATACCTGGAG CGCGGGAAGG AGACGCTGCT GCGCTCAGAT
 CCCCCAGAGG CACATGTGAC CCTTCACCCC AGACCTGAAG GTGATGTGAC
 CCTGAGGTGC TGGGCCCTGG GCTTCTACCC TGCTGACATC ACCCTGACCT
 GGCAGTTGAA TGGGGAGGAC CTGACCCAGG ACATGGAGCT TGTGGAGACC
 AGGCCTGCAG GGGATGGAAC CTTCCAGAAG TGGTCATCTG TGGTGGTGCC
 TCTTGGGAAG GAGCAGAATT ACACATGCCG TGTGGAGCAT GAGGGGCTGC
 CTGAGCCCCT TTCCCAGAGA TGGGGCAGGT ACAGCTCCCA GAGCTCCGTT
 GTGTCTCTCC CAGATTGTGA AGCATGA*

>DL;RT1-Cc9_c
RT1-Cc9_c  1014 bases  
 GGCTCACACT CGCTGCGGTA TTTCCACACC GCCGTGTCCC GGCCCCGCCT
 CGGGAAGCCC CGGTTCATTA TTGTCGGCTA CGTGGACGAC ACGGAGTTCA
 TGCGCTACGA CAGCGACGCA GATAATCCGA GGATGGAGCG GGAGGGGCCG
 GAGTATTGGG AGGAGCGGAC ACGGATCGCT AAGGAAACCG AGCAAATTTT
 CCGAGTGGAT CTGAGGATCT TGCGCGGCTA CTACAACCAG AGCGAGGGCG
 GCTCTCACAC CATCCAGAGA ATTTATGGCT GTGTCATGGG GTCGGACGGG
 AAACTCCAGC ATGGGTATGA TCAGCTCGCC TATGACGGCC GAGATTACAT
 CGCCCTTAAT GAAGACCTGA AAACCTGGAC GGCGGCGGAT AAGGCAGCAC
 GGATCACAAG GAGCAAGTGG GAGCGGGCTG GTGTTGCAGA GAGACGCAGG
 GCCTACCTGG AGGGGGAGTG CGTGGAGTCT CTCCGCAGAT ACCTGGAGGA
 GGAGAAGGAG ACGCTGCTTC GCTCAGATCC CCCAAAGGCA CATGTGACCC
 TTCACCCCAG ACCTGAAGGT GATGTCACCC TGAGGTGCTG GGCCCTGGGC
 TTCTACCCTG CTGACATCAC CCTGACCTGG CAGTTGAATG GGGAGGATCT
 GACCCAGGAC ATGGAGCTTG TGGAGACCAG GCCTGCAGGG GATGGAACCT
 TCCAGAAGTG GGCAGCTGTG GTGGTACCTC TTGGGGAGGA GCCGAATTAC
 ACATGCCGTG TGGAGCATGA GGGGCTGCCT GAGCCCCTCA CCTTGAGATG
 GGAGCCACCT CCATCTACCA ACTCCAACAT GAGTATCATT GCTGTCCTGG
 TTGTCCTCAT TGTGTCTGTG GCAATCAATG GAACTGTGGC CTTCATTGAA
 ACTGATGAGA GGAGGAGGAG AAACACAGGT GGAACAGGAG GAGACTACGC
 CCCTGCTCCA GGCAGGGACA GCTCCCAGAG CTCTGATGTG TCTCTCCCAG
 ATTGTAAAGC ATGA*

>DL;RT1-Clw2_l
RT1-Clw2_l  1104 bases  
 ATGGCACCGC GCACGCTGCT CCTGCTGCTG GCGGCCGCCC TGGCCCCGAC
 CCAGGTTCGC GCGGGCTCAC ACTCGCTGCG GTATTTCCAC ACCGCCGTGT
 CCCGGCCCGG CCTCGGGGAG CCCCGGTTCA TTATCGTCGG CTACGTGGAC
 GACACGGAGT TCGTGCGCTA CGACAGCGAC GCGGAGAATC CGAGATACGA
 GCCGCGGGTT GGGTGGATGG AGCGGGAGGG TCCGGAGTAT TGGGAGCGGG
 AGACACTGAT GGTCAAGGAA AACGAGCAGG TTTACCGAGT GAGCCTGAGG
 ACCCTGCTCC GCTACTACAA CCAGAGCGAG GGCGGCTCTC ACACCATCCA
 GTGGATGTCC GGCTGTGACG TGGGGTCGGA CGGGAGCCTC CTCCGCGGGT
 ATGATCAGTT CGCCTACGAC GGCCGCGATT ACCTCGCCCT GAACGAAGAC
 CTGAAAACGT GGATGGCGGC GGACACGGCG GCACAGATGA CCCGAAACAA
 GTGGGATCAG GCAGGTGAAG CAGAGAGACA CAAGGCCTAC CTGCAGGGCA
 CGTGTGTGGA GTGGCTCCGC AGATACCTGG AGCTCGGGAA GGAGACGCTG
 CTGCGCTCAG ATCCCCCAAA GGCACATGTG ACCCTTCACC CCAGACCTGA
 AGGTGATGTC ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCTGGCA
 TATTCCTGAC CTGGCTGTTG AATGGGGAGG ATCTGACCCA GGACATGGAG
 CTTGTGGAGA CCAGGCCTGC AGGGGATGGA ACCTTCCAGA AGTGGGCATC
 TGTGGTGGTG CCTCTTGGGA AGGAGCAGAA TTACACATGC CTTGTGGAGC
 ATGAGGGGCT GCCTGATCCT CTCACCCTGA GATGGGAGGC TCCTCCATCC
 ACTGACCCCA ACATGGAAAC CACTGTCATT TATGTTGTCG TTGGAGCTGT
 GGTCATCACT GGAGCTGTGA CCATGATTGG AGCTCTGCTG ACTGTTGTGA
 GGGGGAAGAG AAACACAGGT GGGAAAGTAG GAGTCTACAC CCCTGCTCCA
 GGCAAGGACA GCTCCGAGAG CTCTGATGTG TCTCTCCCAG ATTGTAAAGC
 ATGA*

>DL;RT1-EC2_r21
RT1-EC2_r21  1047 bases  
 ATGGGGGCAA AGGCACTTCA GGCGCTGCTC CTGCTGGTGG CGGTCGCCCT
 GGCCCCGACC CAGACCAGCG CAGGCTCACA CTCGCTGCGG TATTTCGAAA
 CCGCCGTGTC CCGGCCCGGC CTCGGGGAGC CACGGTTCAT CTCTGTCGGC
 TACGTGGACG ACACGGAGTT CGTGCGCTAC GACAGTGACG CGGAGAATCC
 GAGATACGAG CCGCGGGCGC GGTGGATTGA GTGGGAGAAG CCGGACTATT
 GGGAGACGCA GACACGGAGA GCCAAGGGAA ACGAGCAGAT TTACCGAGGG
 AGCCTGACGA CCCTGCTCCA CTACTACAAC CAGAGCGAGG ACGGCTCTCA
 CACCATCCAG TGGATGTATG GCTGTGACGT GGGGTCGGAC GGGAGCCTCC
 TCCGCGGGTA TTGGCAGCAC GCCTATGATG GCCGCGATTA CCTCGCCCTG
 AATGAAGACC TGAAAACGTG GGAGGCCTCG GACAGAGCGG CGCAGAAAAC
 CCGGAACAAG TGGGAGCGGA AAGGTGTTGC AGAGAGAAGC AGGGCCTACC
 TGAAGGGCAC ATGTGTGGAG TCCGTCCGCA GATACCTGGA GCTCAGAAAG
 GAGACGCTCG TGCGCTCAGA TCCCCCAAAG GTGCGTGTGA CCCTTCACCC
 CAGACCTGAA GGTGATGTCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCTGACAT CACCCTGACC TGGCAGTTGA ATGGGGAGGA CCTGACCCAG
 GACATGGAAC TTGTGGAGAC CAGGCCTGCA GGGGATGGAA CCTTCCAGAA
 GTGGGCATCT GTGGTGGTGC CTCTTGGGAA GGAGCAGAGT TACACATGCC
 TTGTGGAGCA TGAGGGGCTG CCTGAGCCGC TTACCCAGAG ATGGGAGCCT
 CCTCCATCAA CTGATTCCAA CATGGGAATC ATTGCTGTTC TGGCTGTCGT
 TGGAGCTGTG GCTGTCATTG TACTTGTGGC CCTCATTGGA GTTGTTGTGA
 GGAGGAGGAG GAAAAACATA GCTTTCCTTC TCACAGGTGG AATATGA*

>DL;RT1-EC3_r21
RT1-EC3_r21  1092 bases  
 ATGGCAGAGG TGGCGCACCC CACGCTGCCC CTGCTGCTGG CGGCCACCCT
 GGCCCCGACC CAGACCCGCG CGGGCTCACA CTCGCTGCGG TATTTCTACA
 CCGCTGTGTC CCGGCCCGGC CTTGGGGAGC CCCTTTTCAT TGCTGTCGGC
 TACGTGGACG ACACGCCGTT CGTGCGCTAC GACAGCGATG CGGAGAATCC
 GAGGATGGAG CCGCGGGTGA CGTGGATGGA GCGGGAGGGG CCGGAGTATT
 GGGAGGAGGA GACACGGAGA ATCCAGGAAA CCGAGCAGTG GTTCCAAATG
 GACCTGAGGA CCCTGCGCGG CTACTACAAC CAGAACGAGG ACGGCTCTCA
 CACCATCCAG AGAATCTTTG GCTGTGACTT GGGATCGGAC GGGAAACTCC
 GCCGCGGGTA TGATCAGCTC GCCTATGATG GCCTCGATCA CATCGCCCTT
 AAAGAAGACC TGAAAAAGTG GACGGTGGCA GACAAGGTGG CATGGATTAC
 CCGAAGCAGG TTGGAGCAGA CTGGTGAAAC AGAGAGACGA AGGGCCTACC
 TGGAGGGTGA ATGCGTGGAG TCTCTCCACA GATACCTGGA GCTTGGGAAG
 GAGCGCTCTG CGGCGTCAGA TCCCCTAAAG GTGCATGTGA CTCTTCACCC
 CAGACCTGAA GGTGGTGTCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCTGAAAT CACCCTGTCC TGGCAGTTGA ATGGGGAGGA CCTGACCCAG
 GACGTGGAGA TTGTGGAGAC CAGGCCTGCA GGGGATGGAA CCTTCCAGAA
 GTGGGCATCT GTGGTGGTGC CTCCTGGGAA GGAGCAGAAG TACACATGCC
 ATGTGGATCA TGAGGGACTG CCTGAGCCGA TTACCCAGAG ATGGGAGCCT
 TCTCCATCCA CCGACTCCAA CATGGAAACC TATGTCATTT ATGTCGTCCT
 TGGAGCTGTG GCCATCATTG CAGCTGTGAT CATTGGAGCT GTGGTGGCTG
 TTGTGAGGAA GAGGAGGAGA AACACAGCTT TTCTTCTCAC AGGAGGAACA
 GGAGGAGACT ACACCCCTGC TCCAGGCAGG GACAGCTCCT AG*

>DL;RT1-E_u
RT1-E_u  1122 bases  
 ATGGCACCGC GCACGCTGCT CCTGCTGTTG GCGGCCGCCC TGGCCCCGAC
 CCAGATTCGC GCGGGCTCAC ACTCGCTGCG GTATTTCGAC ATCACCGTGT
 CCCGGCCCGG CCTCGGGGAG CCCCGGTTCA TCTCTGTAGG CTACGTGGAC
 GACACGGAGT TCGTGCGCTA CGACAGCGAC GCAGAGAATC CGAGATTCAA
 GCCGCGGGTG CGGTGGATGG AGCGGGAGGG GCCGGAGTAT TGGGAGCGGA
 TCACACGGAT CGCCAAGGAA AGCGAGCAGA TTTACCGAGT GGGCCTGAGG
 ACCCTGCGCG GTTACTACAA CCAGAGCGAG GGCGGCTCTC ACACCATCCA
 GAGATTGTCT GGCTGTGAGG TGGGGTCGGA CGGGATCCTC CTCCGAGGGT
 ATGAGCAGTT CGCCTACGAC GGCCGCGATT ACATCGCCCT GAACGAAGAC
 CTGAAAACGT GGGCGGCGGC GGACTTTGCA GCAGGGATCA CCCGGAACAA
 GTTGGAGCGG GATGGTGAGG CAGAGAGACT CAGGGCCTAC CTGGAAGGCG
 AGTGCGTAGA GTGGCTCCGC AGATACCTGG AGCTCAGGAA GGAGACGCTG
 CTGCGCTCAG AACCCCCAAA GGCACATGTG ACCCTTCACT CCAGACCTGA
 AGGTGATGTG ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCTGACA
 TATTCCTGAC CTGGCTGTTG AATGGGGAGG ACCTGACCCA GGACATGGAA
 CTTGTGGAGA CCAGGCCTGC AGGGGATGGA ACCTTCCAGA AGTGGGCATC
 TGTGGTGGTG CCTCTTGGGA AGGAGCAGAA TTACACATGC CATGTGGAGC
 ATGAGGGGCT GCCTGAGCCG CTCACCCTGA GATGGGAGGG TCCTCCCTCC
 GCCAACTCCA ACACGGGAAT GTCTGTTATT CTTGGAACTG TGGCCATCAT
 TGCAGTTATG GCCATCATTG CAGCTGTAGC CTTCATTGGA CCTGTTGTGA
 GGAAGAGGTG GATAAAAACA GCTTTTCTTC TCACAAGTGG AAAAGGAGGA
 GACTACACCC CTGCTCCAGG CAGGGACAGC TCCCAGAGCT CTGATGTGTC
 TCTCCCAGAT TGTAAAGCAT GA*

>DL;RT1-K_u
RT1-K_u  1120 bases  
 GCACCGCGCA CGCTGCTCCT GCTGTTGGCG GCCGCCCTGG CCCCGACCCA
 GATTCACGCG GGCTCACACT CGCTGCGGTA TTTCGACATC ACCGTGTCCC
 GGCCCGGCCT CGGGGAGCCC CGGTTCATCT CTGTCGGCTA CGTGGACGAC
 ACGGAGTTCG TGCGCTACGA CAGCGACGCA GAGAATCCGA GATTCAAGCC
 GCGGGTCCGG TGGATGGAGC GGGAGGGGCC GGAGTATTGG GAGCGGATCA
 CACGGATCGC CAAGGAAAGC GAGCAGATTT ACCGAGTGGG CCTGAGGACC
 CTGCGCGGTT ACTACAACCA GAGCGAGGGC GGCTCTCACA CCATCCAGAG
 ATTGTCTGGC TGTGAGGTGG GGTCGGACGG GATCCTCCTC CGCGGGTATG
 AGCAGTTCGC CTACGACGGC CGCGATTACA TCGCCCTGAA CGAAGACCTG
 AAAACGTGGG CGGCGGCGGA CTTTGCAGCA GGGATCACCC GGAACAAGTT
 GGAGCGGGAT GGTGAGGCAG AGAGACTCAG GGCCTACCTT GAAGGCGGGA
 GCGTGGAGTG GCTCCGCAGA TACTTGGAGC TCAGGAAGGA GACGCTGCTG
 CGCTCAGAAC CCCCAAAGGC ACATGTGACC CTTCACTCCA GACCTGAAGG
 TGATGTGACC CTGAGGTGCT GGGCCTTGGG CTTCTACCCT GCTGACATAT
 TCCTGACCTG GCTGTTGAAT GGGGAGGACC TGACCCAGGA CATGGAACTT
 GTGGAGACCA GGCCTGCAGG GGATGGAACC TTCCAGAAGT GGGCATCTGT
 GGTGGTGCCT CTTGGGAAGG AGCAGAATTA CACATGCCAT GTGGAGCATG
 AGGGGCTGCC TGAGCCGCTC ACCCTGAGAT GGGAGGGTCC TCCCTCCGCC
 AACTCCAACA CGGGAATGTC TGTTATTCTT GGAACTGTGG CCATCATTGC
 AGTTATGGCC ATCATTGCAG CTGTGGCCTT CATTGGACCT GTTGTGAGGA
 AGAGGTGGAT AAAAACAGCT TTTCTTCTCA CAAGTGGAAA AGGAGGAGAC
 TACACCCCTG CTCCAGGCAG GGACAGCTCC CAGAGCTCTG ATGTGTCTCT
 CCCAGATTGT AAAGCCATGA*

>DL;RT1-L1_l
RT1-L1_l  981 bases  
 ATGGTGCTGT GCATGCTGCT CTTGCTTCTG GTGGCCTCCC TGGCCCTGAC
 CCTGACCCGC GCAGGCTCAC ACTCGCTGCG GTATTTCGAA ACCGCCGTGT
 CCCGGCCGGG CCTCGGGGAG CCCGGGTTCA TCTCTGTTGG CTACGTGGAC
 GACACGGAGT TCGTGCGCTA CGACAGCGAC AAGGAGAACC CGAAGATGGA
 GCCCCGGGTG CGGTGGATGG AGCAGGAGGG GCCGGAGTAT TGGGAGAGGG
 AGACGCAGAG AGCCAAGGGA CAAGCGCAGT GGTCCCGAGT GAACCTGGGG
 ACCGCGCTCC GCTACTACAA CCAGAGCGAG GGCGGCTCTC ACACCATCCA
 GAGATTGTCT GGCTGTGATT TGGGGTCGGG CAGGAGCCTC CTACCCGGGT
 ATGAACAGTA CGCCTACGAT GGCCGCGATT ACATCGCCCT GAACGAAGAC
 CTGAAAACGT GGACGGCGGC GGACGCGGCA GCACAGATCA CCCAGAGCAA
 GTGGGATCAG GCTGGTACTG CAGAGAGACA CAGGGCCTAC CTGGAGGGCA
 CGTGCGTGAA GTCGCTCTGC AGATACCTGG AGCTCGGGAA GGAGAAGCTG
 CTGCGCTCAG ATCCCCCAAA GGCACATGTG ACCCTTCACC CAAGCCCTGA
 AGGTGATGTC ACCCTGAGGT GCTGGGCCCT GGACTTCTAC CCTGCTGACA
 TCACCCTGAC CTGGCATTTG AATGGGGAGG ACCTGACCCA GGACATGGAG
 CTTGTGGAGA CCAGGCCTGC AGGGGATGGA ACCTTCCAGA AGTTGGCATC
 TGTGGTGGTG CCTCTTGGGA AGGAGCAGAA TTACACATGC CTTGTGGAGC
 ATGAGGGACT GCCTGAGCCG CTTTCCCAGA GATGGGAGTC TTCTCCATCC
 CGACACCAAC ATGGAAACCA ATGTCATTTA TGTTTTCCTT GGAGCTGTGG
 CTGTCATGGC AGCTGTGGCC ATTCATTGTA G*

>DL;RT1-L2_l
RT1-L2_l  1095 bases  
 ATGGGGGTGA CTGCGCCGCC CTTGCTGCTC CTGCTCTGGC GGCCGCTTGG
 CCGGACCCAG ACCCGCGCGG GCTCGCACTC GCTGCGGTAT TTTGAAACCG
 CCATGTCCCG GCCGGGCCTC GGGGAGCCCC GGTTCATCTC CGTCGGCTAC
 GTGGACGACA GGCAGTTCGT GCGCTATGAC AACGACGCGG AGAATCCGAG
 GATGGAGCCG CGGGCCCGGT GGATGGAGCG GGAGGGGCCA GAGTATTGGC
 AGCGGGAGAC GCAGAGAGCC AAGGGACAAG AGCAGTGGTC CCGAGTAAAC
 CTGGGTACCG CGCTCCGCTA CTACAACCAG AGCGAGGGCG GCTCTCACAC
 CATCCAGAGG ATGTATGGCT GTGACCTGGG GTCGGACGGG AGCCTCCTTC
 GCGGGTATGA GCAGTACGCC TACGCCGGCC GCGATTACAT CGCCCTGAAC
 GAAGACCTGA AAACCTGGAC AGCTGCGGAC ATGGTAGCAC AGATCACCCA
 GAACAAGTGG GATCAGGCTG GTACTGCAGA GAGACATAGG GACTACCTGG
 AGGGCACGTG TGTGGAGTCG CTCCTCAGAC ACCTGGAGCT CGGGAAGGAG
 ACACTGCTGC GCTCAGATCC CCCAAAGACA CATGTGACCC TTCACCCCAG
 ACCTGAAGGT GATGTCACCC TGAGGTGCTG GGCCCTGGGC TTCTACCCTG
 CTGACATCAC CCTGACCTGG CAGTTGAATG GGGAGGACCT GACCCAGGAC
 ATGGAGCTTG TGGAGACCAG GCCTGCAGGG GATGGAACCT TCCAGAAGTG
 GGCATCTGTG GTGGTGCCTC TTGGGAAGGA GCAGAATTAC ACATGCCTTG
 TGGAGCATGA GGGGCTGCCT GAGCCTCTCA CCCTGAGATG GGAGCCTTCT
 CCATCCACCG ACTCCAACAT GGAAACCAAT GTCATTTATG TTGTCGTCGG
 AGCTGTGGTC ATCATTGGTG CTGTGGCCAT CATTGTAGCT TTGGTGGTTG
 TTGTGAGGAG AAGGAGGAGG AGCAGGACGA GGAGGAGGAG AAGAAGAAAC
 ATAGGTGGGA AAGGAGGAGT CTACGCCCCT GCTCCAGAGG TCTGA*

>DL;RT1-L3_l
RT1-L3_l  1025 bases  
 GCTCACACTC GCTGCGGTAT TTCGAAACCG CTGTGTCCCA GCCTGGCCTC
 GGGGAGCCCC CGGTCATCTC TGTCGGCTTC GTGGACGACA CGCAGTTCGT
 GCGCTACGAC AGCGACGAGG AGAATCCGAA ATACGAGCCG CGGGCCCGGT
 GGATGGAGCG CGAGGGGCCG GAGTATTGGG AGCGGGAGAC GCAGAGAGCC
 AAGGGAAATG AGCAGTGGTC CCGAGTGAAC CTGGGGACCG CGCTCCGGTA
 CTACAACCAG AGCGAGGGCG GCTCTCACAC GATGCAGAGA TTGTCTGGCT
 GTGCAGTGGG GTCAGACGGG AGCCTCCTCC GCGGGTATGA TCAGTACGCC
 TACGACGGCC GCGATTACAT CGCCCTGAAC GAAGACCTGA AAACGTGGAC
 TGCAGCGGAC ACTGCAGCAC AGATCACCCA GAGCAAGTGG GATCAGGCTG
 GTGAGGCAGA GAGAAGCAGG GCCTACCTGG AAGGCAAGTG TGTGGAGTGG
 CTCCTCAGGT ACCTGGAGCT CGGGAAGGAG ACGCTGCTGC GCTCAGACCC
 CCCAAAGGCA CATATGACCC TTCACCCCAG ACCTGAAGGT GATGTCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CTGACATCAC CCTGACCTGG
 CAGTTGAATG GGGAGGACCT GACCCAGGAC ATGGAGCTTG TGGAGACCAG
 GCCTGCAGGG GATGGAACCT TCCAGAAGTG GGCATCTGTG GTGGTGCCTC
 TTGGGAAGGA GCAGAGTTAC ACATGCCATG TTGAGCATGA GGGGCTGCCT
 GAGCCTCTCA CCCTGAGATG GGAGCCTCCT CCATCAACAG ACTTCAACGT
 GAGAATCATT GCTGTTCTGG TTGTCCTTGG AGCTGTGGCC ATCATTGGAC
 CTGTGGTGGC TGTTGTGATG AAGAGGAGGA GAAACACAGG TGGAACAGGA
 GGAGACTATG CCCCTGCTTC AGGTAAGACC AGCCCCAACA GCTGTGATGT
 ATCTCTCCCA GATTGTAAAG CATGA*

>DL;RT1-U2_c
RT1-U2_c  1047 bases  
 ACTCGCGCGG GCTCACACTC GCTGCGGTAT TTCGTCACCG CCATGTCCGG
 GCCCGGCCTC GGGAAGCCCC GATTCATGGA AGTCGGCTAC GTGGACGACA
 CGGAGTTCGT GCGCTACGAC AGCGACGCGA AGAATCCGGG GATGGAGCCG
 CGGGCGAGGT GGATGGAGCG GGAGGGGCGG GAGTATTGGG AGCGGGAGAC
 ACGGATCGCC AAGGAAAACG AGCAGACTTT CCGAGAGAAC CTGAGGACCC
 TGCTCCGCTA CTACAACCAG AGCGAGGGCG GCTCTCACAC CTTCCAGTGG
 ATGTCTGGCT GTGACCTGGG GTCGGACGGG AGCCTCCTCC GCGGATATGA
 GCAGTCCGCC TACAACGGCC GCGATTACAT CGTCCTGAAC GAAGACCTGA
 AAACGTGGAC GGCGGCGGAC ACGGCGGCAC GGATCACCCG GAACAAGTGG
 GATCGGGCTG GTGTTGCAGA GAGACACAAG GCCTACCTGG AGGGCACGTG
 CTTGGAGTCG CTCCTCAGAT ACCTGGAGCT CGGGAAGGAG ACGCTGCTGC
 GCTCAGATCC CCCAAAGGCA CATGTGACCC TTCACCCCAG ACCTGAAGGT
 GATGTCACCC TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CTGGCATCTC
 CCTGACCTGG CAGTTGAATG GGGAGGACCT GACCCAGGAC ATGGAGCTTG
 TGGAGACCAG GCCTGCAGGG GATGGAACCT TCCAGAAGTG GGCATCTGTG
 GTGGTGCCTC TTGGGAAGGA ACAGAATTAC ACATGCCTTG TGGAGCATGA
 GGGGCTGCCT GAGCCGCTTA CCCAGAGATG GGAGCCTTCT CCATCGACCG
 ACTCCAACAT GGAAACCAAT GTCATTTATG TCATCCTTGG AGCTGTGGCC
 ATCATTGGAG CTGTGATCAT TGCAGCTCTG GTGACTGTTG TGAGGAAGAG
 GAGAAACACA GGTGGAAAAG TAGGAGTCTA CACCCCTGCT CCAAGCAGGG
 ACAGCTCTGA GAGCTCTGAT GTGTCTCTCC CAGATTGTAA AGCATGA*

