>P1;RT1-Da_l
RT1-Da_l  256 bases  
 MATIGDLVIR FFFMAVLMSP QKSWAIREEH TIIQAEFYLS PDQNGEFMFD
 FDGDEIFHVD IKKSETIWRL EEFAQFASFE AQGALANIAV DKANLDIMIK
 RSNNTPDANV IPEVTVLPKS PVNLGEPNIL ICFIDKFSPP AVNVTWLRNG
 QPVTKGVSET VFLPREDHLF RKFHYLTFLP STEDYYDCEV DHWGLEEPLR
 KHWEFEEKTL LPETKENVLC VLGLFVGLVG IVVGIVLIIK GLRKRNAVER
 RQGALX*

>P1;RT1-Da_n
RT1-Da_n  256 bases  
 MATLGDLVIR FFFMAVLMSP QKSWAIREEH TIIQAEFYLS PDQNGEFMFD
 FDGDEIFHVD IKKSETIWRL EEFAQFASFE AQGALANIAV DKANLDIMIK
 RSNNTPDANV IPEVTVLPKS PVNLGEPNIL ICFIDKFSPP AVNVTWLRNG
 QPVTKGVSET VFLPREDHLF RKFHYLTFLP STEDYYDCEV DHWGLEEPLR
 KHWEFEEKTL LPETKENVLC VLGLFVGLVG IVVGIVLIIK GLRKRNAVER
 RQGALX*

>P1;RT1-Da_u
RT1-Da_u  256 bases  
 MATIGDLVIR FFFMAVLMSP QKSWAIREEH TIIQAEFYLS PDQNGEFMFD
 FDGDEIFHVD IKKSETIWRL EEFAQFASFE AQGALANIAV DKANLDIMIK
 RSNNTPDANV IPEVTVLPKS PVNLGEPNIL ICFIDKFSPP AVNVTWLRNG
 QPVTKGVSET VFLPREDHLF RKFHYLTFLP SVEDYYDCEV DHWGLEEPLR
 KHWEFEEKTL LPETKENVLC VLGLFVGLVG IVVGIVLIIK GLRKRNAVER
 RQGALX*

