>P1;RT1-M5_n
RT1-M5_n  336 bases  
 MGSSVFSVLL PLLLSRAWAL NQVGAGIHSL QFFATAVTQP SSREHSFIFV
 GFVDDTQFLC YNNQGESQRM EPRALWVKNM GPGYWERQTR MVKDISKNSL
 VNLREAMSVY NHSEDGTHVF QCVSGCDVGP DGLFLRGHEQ HAYDGRDYLA
 LNKDLHSWTA GDTAAQITRR KWEEAGVAEQ RRTYLKGECV ESLRTYLEIG
 KETLLGADPP KAHVTHHPSP EGDNTLRCWA LGFYPSDITL TWQRDGEDLT
 QDMELVETRP GGDGTFQKWA AVVVPSGEEH RYTCCVEHEG LTEPLLLKWD
 PSKHTIPIMG ITAGLVFLGV AFTGAVVAIA MRKQRG*

