>P1;RT1-DMb_a
RT1-DMb_a  262 bases  
 MAALWPLLLA LGLGCIGAGG FVAHVESTCL LDDEGTPMDF TYCISFNKDL
 LACWDPEEGQ IVPCEYGVLF KLAEFISNIL NKEEGLIQRL KNGLQDCSTH
 TQPFWNALTH RTRTPSVQVA QTAPFNTREP VMLACYVWGF YPADVTVVWM
 KNGQLVTSHS NKEKTAQPNG DWTYQTVSYL ALTPSYWDIY TCVVQHSGTP
 EPIRANWTPG LSPIQTVKVS VSAATLGLGF IIFCLGFFRW RKSHSSSYTP
 LPGSTYPEGR PX*

>P1;RT1-DMb_n
RT1-DMb_n  262 bases  
 MAALWPLLLA LSLGCIGAGG FVAHVESTCL LDDEGTPMDF TYCISFNKDL
 LACWDPEEGQ IVPCEYGVLF KLAEFISNIL NKEEGLIQRL KNGLQDCSTH
 TQPFWNALTH RTRTPSVQVA QTAPFNTREP VMLACYVWGF YPADVTVVWM
 KNGQLVTSHS NKEKTAQPNG DWTYQTVSYL ALTPSYWDIY TCVVQHSGTP
 EPIRANWTPG LSPIQTVKVS VSAATLGLGF IIFCLGFFRW RKSHSSSYTP
 LPGSTYPEGR PX*

