>DL;RT1-BM1_av1
RT1-BM1_av1  806 bases  
 TGAATCTGAG GACCCTGCGC CGCTACTACA ATCAGAGTGA CGACGAATCT
 CACACGCTGC AGTGGATGTA CGGCTGCGAC GTGGGGCCCG ATGGGCACCT
 GCTCCGCGGT TATTGTCAGG AGGCTTATGA CGGCCGGGAT TATATCTCCT
 TGAACGAGGA CCTGCGCTCC TGGACCGCGA CTGACATGGC CTCACAGGCC
 TCTAAGATCA AGTCAGAGGA AGTTGGTGAG GCCCATCACC AGAGGGCCTA
 CCTGCAAGGT CCTTGCGTGG AGTGGCTCCA CACATACCTA CATCTGGGAA
 AGGAGACGCT GCTGCGCTCA GACCCCCCAA AGGCACATGT GACCCTTCAC
 CCCAGACCTG AAGGTGATGT CACCCTGAGG TGCTGGGCCC TGGGCTTCTA
 CCCTGCTGAC ATCACCTTGA CCTGGCAATT GAATGGGGAG GACCTGACCC
 AGGACATGGA GCTTGTGGAG ACCAGGCCTG CAGGGTATGG AACCTTCCAG
 AAGTGGGCAG CTGTGGTAGT GCCTTCTGGG GAGGAGCTGA AGTACACATG
 CCATGTGGAG CATGAGGGAC TGCCTGAACC TCTCGCCCTG AGATGGGAGC
 CTTCTCCATT CACCGACTCC AGCATGCCAG TGATTGTTGT CCTTGGAGCT
 GTGGCCATCA TTGGAGCTGT GGCCATCATT GGAGCTGTGG CCATCATTGG
 AGCTGTTGTG AGGAGGAGGA AGAGAAACAC AGGTGAAAAA GGCAGCTATG
 CTCATGTTCT AGGCAGCAAG GCTTTCCAGA TCTCTGACTG GCCTCAGAAG
 GCATGA*

>DL;RT1-BM1_c
RT1-BM1_c  1034 bases  
 CTAGCTCACA CTCGCTGCGG TATTTCTACA CCGCCCTGTC CCGGCCCGGC
 CTCGGGGAGC CCAGGTTCAT TGTCGTTGGC TACGTGGACG ACACGCAGTT
 CGTGCGCTAT GACAGCGATG TGGAGAATCC GAGGATGGAG CCACGGGCGC
 GGTGGATGGA GCAGGAGGAG CCGGCATATT GGGAGCGGGA GACTCGGAAA
 GCCAGGGACA CCGGGAGGAA CTTCAAAGTG AATCTGAGGA CCCTGCTCCG
 CTACTACAAT CAGAGTGACG ACGAATCTCA CACGCTGCAG TGGATGTACG
 GCTGCGACTT GGGGCCCGAT GGGCACCTGC TCCGCGGTTA TTGTCAGGAG
 GCTTATGACG GCCGGGATTA TATCTCCTTG AACGAGGACC TGCGCTCCTG
 GACCGCGACT GACATGGCCT CACAGGCCTC TAAGATCAAG TCAGAGGAAG
 TTGGTGAGGC CCATCACCAG AGGGCCTACC TGCAAGGTCC TTGCGTGGAG
 TGGCTCCACA CATACCTACA TCTGGGAAAG GAGACGCTGC TGCGCTCAGA
 CCCCCCAAAG GCACATGTGA CCCTTCACCC CAGACCTGAA GGTGATGTCA
 CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCTGACAT CACCTTGACC
 TGGCAATTGA ATGGGGAGGA CCTGACCCAG GACATGGAGC TTGTGGAGAC
 CAGGCCTGCA GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTAGTGC
 CTTCTGGGGA GGAGCTGAAG TACACATGCC ATGTGGAGCA TGAGGGACTG
 CCTGAACCTC TCGCCCTGAG ATGGGAGCCT TCTCCATTCA CCGACTCCAG
 CATGCCAGTG ATTGTTGTCC TTGGAGCTGT GGCCATCATT GGAGCTGTGG
 CCATCATTGG AGCTGTGGCC ATCATTGGAG CTGTTGTGAG GAGGAGGAAG
 AGAAACACAG GTGAAAAAGG CAGCTATGCT CATGTTCTAG GCAGCAAGGC
 TTTCCAGATC TCTGACTGGC CTCAGAAGGC ATGA*

>DL;RT1-BM1_k
RT1-BM1_k  1034 bases  
 CTAGCTCACA CTCGCTGCGG TATTTCTACA CCGCCCTGTC CCGGCCCGGC
 CTCGGGGAGC CCAGGTTCAT TGTCGTTGGC TACGTGGACG ACACGCAGTT
 CGTGCGCTAT GACAGCGATG TGGAGAATCC GAGGATGGAG CCACGGGCGC
 GGTGGATGGA GCAGGAGGAG CCGGCATATT GGGAGCGGGA GACTCGGAAA
 GCCAGGGACA CCGGGAGGAA CTTCAAAGTG AATCTGAGGA CCCTGCTCCG
 CTACTACAAT CAGAGTGACG ACGAATCTCA CACGCTGCAG TGGATGTACG
 GCTGCGACGT GGGGCCCGAT GGGCACCTGC TCCGCGGTTA TTGTCAGGAG
 GCTTATGACG GCCGGGATTA TATCTCCTTG AACGAGGACC TGCGCTCCTG
 GACCGCGACT GACATGGCCT CACAGGCCTC TAAGATCAAG TCAGAGGAAG
 TTGGTGAGGC CCATCACCAG AGGGCCTACC TGCAAGGTCC TTGCGTGGAG
 TGGCTCCACA CATACCTACA TCTGGGAAAG GAGACGCTGC TGCGCTCAGA
 CCCCCCAAAG GCACATGTGA CCCTTCACCC CAGACCTGAA GGTGATGTCA
 CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCTGACAT CACCTTGACC
 TGGCAATTGA ATGGGGAGGA CCTGACCCAG GACATGGAGC TTGTGGAGAC
 CAGGCCTGCA GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTAGTGC
 CTTCTGGGGA GGAGCTAAAG TACACATGCC ATGTGGAGCA TGAGGGACTG
 CCTGAACCTC TCGCCCTGAG ATGGGAGCCT TCTCCATTCA CCGACTCCAG
 CATGCCAGTG ATTGTTGTCC TTGGAGCTGT GGCCATCATT GGAGCTGTGG
 CCATCATTGG AGCTGTGGCC ATCATTGGAG CTGTTGTGAG GAGGAGGAAG
 AGAAACACAG GTGAAAAAGG CAGCTATGCT CATGTTCTAG GCAGCAAGGC
 TTTCCAGATC TCTGACTGGC CTCAGAAGGC ATGA*

>DL;RT1-BM1_n
RT1-BM1_n  1092 bases  
 ATGTTACCTC CTGCCTATTT GCTCCAACTA CTGGCAGGCA CCATGGTCCT
 GACCCAGACT AGCTCACACT CGCTGCGGTA TTTCTACACC GCCCTGTCCC
 GGCCCGGCCT CGGGGAGCCC AGGTTCATTG TCGTTGGCTA CGTGGACGAC
 ACGCAGTTCG TGCGCTATGA CAGCGATGTG GAGAATCCGA GGATGGAGCC
 ACGGGCGCGG TGGATGGAGC AGGAGGAGCC GGCATATTGG GAGCGGGAGA
 CTCGGAAAGC CAGGGACACC GGGAGGAACT TCAAAGTGAA TCTGAGGACC
 CTGCTCCGCT ACTACAATCA GAGTGACGAC GAATCTCACA CGCTGCAGTG
 GATGTACGGC TGCGACGTGG GGCCCGATGG GCACCTGCTC CGCGGTTATT
 GTCAGGAGGC TTATGACGGC CGGGATTATA TCTCCTTGAA CGAGGACCTG
 CGCTCCTGGA CCGCGACTGA CATGGCCTCA CAGGCCTCTA AGATCAAGTC
 AGAGGAAGTT GGTGAGGCCC ATCACCAGAG GGCCTACCTG CAAGGTCCTT
 GCGTGGAGTG GCTCCACACA TACCTACATC TGGGAAAGGA GACGCTGCTG
 CGCTCAGACC CCCCAAAGGC ACATGTGACC CTTCACCCCA GACCTGAAGG
 TGATGTCACC CTGAGGTGCT GGGCCCTGGG CTTCTACCCT GCTGACATCA
 CCTTGACCTG GCAATTGAAT GGGGAGGACC TGACCCAGGA CATGGAGCTT
 GTGGAGACCA GGCCTGCAGG GGATGGAACC TTCCAGAAGT GGGCAGCTGT
 GGTAGTGCCT TCTGGGGAGG AGCTGAAGTA CACATGCCAT GTGGAGCATG
 AGGGACTGCC TGAACCTCTC GCCCTGAGAT GGGAGCCTTC TCCATTCACC
 GACTCCAGCA TGCCAGTGAT TGTTGTCCTT GGAGCTGTGG CCATCATTGG
 AGCTGTGGCC ATCATTGGAG CTGTGGCCAT CATTGGAGCT GTTGTGAGGA
 GGAGGAAGAG AAACACAGGT GAAAAAGGCA GCTATGCTCA TGTTCTAGGC
 AGCAAGGCTT TCCAGATCTC TGACTGGCCT CAGAAGGCAT GA*

>DL;RT1-BM1_r21
RT1-BM1_r21  1092 bases  
 ATGTTACCTC CTGCCTATTT GCTCCAACTA CTGGCAGGCA CCATGGTCCT
 GACCCAGACT AGCTCACACT CGCTGCGGTA TTTCTACACC GCCCTGTCCC
 GGCCCGGCCT CGGGGAGCCC AGGTTCATTG TCGTTGGCTA CGTGGACGAC
 ACGCAGTTCG TGCGCTATGA CAGCGATGTG GAGAATCCGA GGATGGAGCC
 ACGGGCGCGG TGGATGGAGC AGGAGGAGCC GGCATATTGG GAGCGGGAGA
 CTCGGAAAGC CAGGGACACC GGGAGGAACT TCAAAGTGAA TCTGAGGACC
 CTGCTCCGCT ACTACAATCA GAGTGACGAC GAATCTCACA CGCTGCAGTG
 GATGTACGGC TGCGACGTGG GGCCCGATGG GCACCTGCTC CGCGGTTATT
 GTCAGGAGGC TTATGACGGC CGGGATTATA TCTCCTTGAA CGAGGACCTG
 CGCTCCTGGA CCGCGACTGA CATGGCCTCA CAGGCCTCTA AGATCAAGTC
 AGAGGAAGTT GGTGAGGCCC ATCACCAGAG GGCCTACCTG CAAGGTCCTT
 GCGTGGAGTG GCTCCACACA TACCTACATC TGGGAAAGGA GACGCTGCTG
 CGCTCAGACC CCCCAAAGGC ACATGTGACC CTTCACCCCA GACCTGAAGG
 TGATGTCACC CTGAGGTGCT GGGCCCTGGG CTTCTACCCT GCTGACATCA
 CCTTGACCTG GCAATTGAAT GGGGAGGACC TGACCCAGGA CATGGAGCTT
 GTGGAGACCA GGCCTGCAGG GGATGGAACC TTCCAGAAGT GGGCAGCTGT
 GGTAGTGCCT TCTGGGGAGG AGCTAAAGTA CACATGCCAT GTGGAGCATG
 AGGGACTGCC TGAACCTCTC GCCCTGAGAT GGGAGCCTTC TCCATTCACC
 GACTCCAGCA TGCCAGTGAT TGTTGTCCTT GGAGCTGTGG CCATCATTGG
 AGCTGTGGCC ATCATTGGAG CTGTGGCCAT CATTGGAGCT GTTGTGAGGA
 GGAGGAAGAG AAACACAGGT GAAAAAGGCA GCTATGCTCA TGTTCTAGGC
 AGCAAGGCTT TCCAGATCTC TGACTGGCCT CAGAAGGCAT GA*

