>P1;RT1-M2_av1
RT1-M2_av1  345 bases  
 METSAILTLH LLLSASLALT QSFKGSHSLR YFDIAVSRPG LEETHYMTLG
 YVDDTEFVHF NNEAVNPRFE PRVPWMEQMG QKYWDDQTRI AKVAEQQIRV
 YFQKLRGYYN QSQNSSHTIQ RMTGCYIGPD GHLLHAYRQF GYDGQDYLTL
 NEDLSTWTAA DSAAEITHRE WKATNEAEFW RVYLEGPCMV WLFKYLTVGN
 ETLLRADPPK VYVTHHPRPE GDITLRCWAL GFYPSDITLI WQRDGEDLTQ
 DMDVIETRPA GDGTFQKWAA VVVPSGKEQN YTCYVEHEGL PEPLTLRWSR
 PPQSFIPTIV VAVGLVLLGA SVVTLVIWKK SSGGGRGSLR FLSNX*

>P1;RT1-M2_n
RT1-M2_n  339 bases  
 METSAILTLH LLLSASLALT QSFKGSHSLR YFDIAVSRPG LEETHYMTLG
 YVDDTEFVHF NNEAVNPRFE PRVPWMEQMG QKYWDDQTRI AKVAEQQIRV
 YFQKLRGYYN QSQNSSHTIQ RMTGCYIGPD GHLLHAYRQF GYDGQDYLTL
 NEDLSTWTAA DSAAEITHRE WKATNEAEFW RVYLEGPCMV WLFKYLTVGN
 ETLLRADPPK VYVTHHPRPE GDITLRCWAL GFYPSDITLI WQRDGEDLTQ
 DMDVIETRPA GDGTFQKWAA VVVPSGKEQN YTCYVEHEGL PEPLTLRWSR
 PPQSFIPTIV VAVGLVLLGA SVVTLVIWKK SSGGGRGSL*

