>P1;RT1-Db1_a
RT1-Db1_a  262 bases  
 MMWLPRDSCV AAVILLLTVL SPPVALVRDP TPRFLLQGKS ECHFYNGTQR
 VRFLDRNIYN REEFARFDSD VGEYRAVTEL GRSIAEYLNK QKEFMEQARA
 AVDTICRHNY GVVKYFRTVE PKVTVYPSKT QPLEHHNLLV CSVSDFYPGS
 IEVRWFRNGK EEKDGLVSTG LIRNGDWTFQ LLVMLETVPQ GGEVYTCQVE
 HPSLPSPVRV EWKAQSTSAQ NKKMSGVGGI VLGLLFLGAG LFVYFRSQKG
 QSGLQPTGLL NX*

>P1;RT1-Db1_l
RT1-Db1_l  265 bases  
 MVWLARDSCV AAVILLLTVL SPPVALVRDP TPRFLEQVKG ECHFYNGTQR
 VRFLARYIYN REEYTRFDSD VGEFRAVTEL GRPSAEYYNK QKEYMEQLRA
 TVDTACKHDY EISESFLVPR TVEPKVTVYP SKTQPLEHHN LLVCSVSDFY
 PGSVEVRWFR NGEEEKDGLV STGLIRNGDW TFQLLVMLET VPQGGEVYTC
 QVEHPSLPSP VRVEWKAQST SAQNKKMSGV GGIVLGLLFL GAGLFVYFRN
 QKGQSGLQPT GLLNX*

>P1;RT1-Db1_n
RT1-Db1_n  265 bases  
 MVWLARDSCV AAVILLLTVL SPPVALVRDP TPRFLEQYKS ECYFYNGTQR
 VRLLVRYIYN REEYTRFDSD VGEFRAVTEL GRRDTEYYNK QKEYIERERA
 AVDTICRHNY EISDRFLVPR TVEPKVTVYP SKTQPLKHHN LLVCSVSDFY
 PGSVEVRWFR NGEEEKDGLV STGLIPNGDW TFQLLVMLEM VPQGGEVYTC
 QVEHPSLTSP VRVEWKAQST SAQNKKMSGV GGIVLGLLFL GAGLFVYFRN
 QKGQSGLQPT GLLNX*

>P1;RT1-Db1_u
RT1-Db1_u  265 bases  
 MVWLARDSCV AAVILLLTVL SPPVALVRDP TPRFLGYLKF ECHFYNGTQR
 VRLLARLIYN REEYARFDSD VGEYRAVTEL GRPSAEYRNK QKEFMERRRA
 AVDTYCRHNY EIFDRFLVPR RVEPKVTVYP SKTQPLEHHN LLVCSVSDFY
 PGSIEVRWFR NGKEEKDGLV STGLIRNGDW TFQLLVMLET VPQGGEVYTC
 QVEHPSLPSP VRVEWKAQST SAQNKKMSGV GGIVLGLLFL GAGLFVYFRS
 QKGQSGLQPT GLLNX*

