>DL;RT1-Db1_a
RT1-Db1_a  786 bases  
 ATGATGTGGC TCCCGAGAGA CTCCTGTGTG GCAGCTGTGA TCCTGCTGCT
 GACAGTGCTG AGCCCTCCGG TGGCGTTGGT CAGAGACCCC ACGCCACGGT
 TTTTGTTACA AGGTAAAAGT GAGTGTCATT TCTACAATGG GACGCAGCGC
 GTGCGGTTTC TGGACAGAAA CATCTACAAC CGGGAGGAGT TCGCGCGCTT
 CGACAGCGAC GTGGGCGAGT ACCGCGCGGT GACCGAGCTG GGGCGGAGCA
 TAGCGGAGTA CTTGAACAAA CAGAAGGAGT TCATGGAGCA GGCGCGGGCC
 GCGGTGGACA CGATCTGCAG ACACAACTAC GGCGTAGTGA AATACTTCAG
 GACAGTTGAA CCCAAGGTGA CCGTGTACCC TTCAAAGACG CAGCCCCTGG
 AACACCACAA CCTCCTGGTC TGCTCTGTGA GTGACTTCTA CCCTGGCAGC
 ATTGAAGTCA GATGGTTCCG GAATGGCAAG GAGGAAAAGG ATGGACTCGT
 GTCCACCGGC CTGATCCGAA ATGGAGATTG GACCTTCCAG TTGCTGGTGA
 TGCTGGAGAC GGTTCCTCAA GGTGGAGAGG TTTACACCTG CCAGGTGGAG
 CATCCAAGCC TGCCCAGCCC TGTCAGAGTG GAGTGGAAAG CACAGTCCAC
 GTCTGCACAA AATAAGAAGA TGAGTGGAGT CGGGGGCATC GTGCTGGGTC
 TGCTCTTCCT GGGAGCCGGG CTGTTCGTCT ACTTCAGGAG CCAGAAAGGA
 CAGTCTGGAC TTCAGCCAAC AGGACTCCTG AACTGA*

>DL;RT1-Db1_l
RT1-Db1_l  795 bases  
 ATGGTGTGGC TCGCCAGAGA TTCCTGTGTG GCAGCTGTGA TCCTGCTGCT
 GACAGTGCTG AGCCCTCCCG TGGCGTTGGT CAGAGACCCC ACGCCACGAT
 TTTTGGAACA AGTTAAAGGT GAGTGTCATT TCTACAACGG GACGCAGCGA
 GTCCGGTTTC TGGCCAGATA CATCTACAAC CGGGAGGAGT ACACGCGCTT
 CGACAGCGAC GTGGGCGAGT TCCGCGCGGT GACCGAGCTG GGGCGGCCCT
 CAGCCGAGTA CTATAACAAA CAGAAGGAGT ACATGGAGCA GTTGCGGGCC
 ACGGTGGACA CGGCCTGCAA ACACGACTAC GAGATCTCTG AGAGCTTCCT
 TGTTCCGCGG ACAGTTGAGC CCAAGGTGAC TGTGTACCCT TCAAAGACGC
 AGCCCCTGGA ACACCACAAC CTCCTGGTCT GCTCTGTGAG TGACTTCTAC
 CCTGGCAGCG TTGAAGTCAG ATGGTTCCGG AATGGCGAGG AGGAAAAGGA
 TGGACTCGTG TCCACCGGCC TGATCCGAAA TGGAGACTGG ACCTTCCAGT
 TGCTGGTGAT GCTGGAGACG GTTCCTCAAG GTGGAGAGGT TTATACCTGC
 CAGGTGGAGC ATCCAAGCCT GCCCAGCCCT GTCAGAGTGG AGTGGAAAGC
 ACAGTCCACA TCTGCACAAA ATAAGAAGAT GAGTGGAGTC GGGGGCATCG
 TGCTGGGTCT GCTCTTCCTT GGAGCTGGGC TGTTTGTCTA CTTCAGGAAC
 CAGAAAGGAC AGTCTGGACT TCAGCCAACA GGACTCCTGA ACTGA*

>DL;RT1-Db1_n
RT1-Db1_n  795 bases  
 ATGGTGTGGC TCGCCAGAGA TTCCTGTGTG GCAGCTGTGA TCCTGTTGCT
 AACAGTGCTG AGCCCTCCGG TGGCGTTGGT CAGAGACCCC ACGCCACGGT
 TTTTGGAACA GTATAAATCC GAGTGTTATT TTTACAACGG GACGCAGCGC
 GTACGGCTTC TGGTCAGATA CATCTACAAC CGGGAGGAGT ACACGCGCTT
 CGACAGCGAC GTGGGCGAGT TCCGCGCGGT GACCGAGCTG GGGCGGCGGG
 ACACCGAGTA CTATAACAAA CAGAAGGAGT ACATAGAGCG GGAGAGGGCC
 GCGGTGGACA CGATCTGCAG ACACAACTAC GAGATCTCTG ATAGATTCCT
 TGTGCCGCGG ACAGTTGAAC CCAAGGTGAC TGTGTACCCT TCAAAGACGC
 AGCCCCTGAA ACACCACAAC CTCCTGGTCT GCTCTGTGAG TGACTTCTAC
 CCTGGCAGCG TTGAAGTCAG ATGGTTCCGG AATGGCGAGG AAGAAAAGGA
 TGGACTCGTG TCCACTGGCC TGATCCCAAA TGGAGACTGG ACCTTCCAGT
 TGTTGGTGAT GCTGGAGATG GTTCCTCAAG GTGGAGAGGT TTATACCTGC
 CAGGTGGAGC ATCCCAGCCT GACCAGCCCT GTCAGAGTCG AGTGGAAAGC
 ACAGTCCACG TCTGCACAAA ATAAGAAGAT GAGTGGAGTC GGGGGCATCG
 TGCTGGGTCT GCTCTTCCTG GGAGCCGGGC TGTTCGTCTA CTTCAGGAAC
 CAGAAAGGAC AGTCTGGACT TCAGCCAACA GGACTCCTGA ACTGA*

>DL;RT1-Db1_u
RT1-Db1_u  795 bases  
 ATGGTGTGGC TCGCCAGAGA TTCCTGTGTG GCAGCTGTGA TCCTGCTGCT
 GACAGTGCTG AGCCCTCCGG TGGCGTTGGT CAGAGACCCC ACGCCACGGT
 TTTTGGGATA CCTTAAATTT GAGTGTCATT TCTACAACGG GACGCAGCGC
 GTGCGGCTTC TGGCCAGATT AATCTACAAC AGGGAGGAGT ACGCGCGCTT
 CGACAGCGAC GTGGGCGAGT ACCGCGCGGT GACCGAGCTG GGGCGGCCCT
 CAGCCGAGTA CAGGAACAAA CAGAAGGAGT TCATGGAGCG GAGGCGGGCC
 GCGGTGGACA CGTACTGCAG ACACAACTAC GAGATTTTTG ATAGATTCCT
 TGTGCCGCGG AGAGTTGAAC CCAAGGTGAC CGTGTACCCT TCAAAGACGC
 AGCCCCTGGA ACACCACAAC CTCCTGGTCT GCTCTGTGAG TGACTTCTAC
 CCTGGCAGCA TTGAAGTCAG ATGGTTCCGG AATGGCAAGG AGGAAAAGGA
 TGGACTCGTG TCCACCGGCC TGATCCGAAA TGGAGATTGG ACCTTCCAGT
 TGCTGGTGAT GCTGGAGACG GTTCCTCAAG GTGGAGAGGT TTACACCTGC
 CAGGTGGAGC ATCCAAGCCT GCCCAGCCCT GTCAGAGTGG AGTGGAAAGC
 ACAGTCCACG TCTGCACAAA ATAAGAAGAT GAGTGGAGTC GGGGGCATCG
 TGCTGGGTCT GCTCTTCCTG GGAGCCGGGC TGTTCGTCTA CTTCAGGAGC
 CAGAAAGGAC AGTCTGGACT TCAGCCAACA GGACTCCTGA ACTGA*

