>DL;DLA-DRB1_00101
DLA-DRB1_00101  270 bases  
 CACATTTCTT GGAGGTGGCA AAGTCCGAGT GCTATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTCGTGGA AAGATACATC CATAACCGGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCCCGTCGC TGAGTCCTGG AACGGGCAGA AGGAGATCTT GGAGCAGGAG
 CGGGCAACGG TGGACACCTA CTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_00102
DLA-DRB1_00102  270 bases  
 CACATTTCTT GGAGGTGGCA AAGTCCGAGT GCTATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTCGTGGA AAGATACATC CATAACCGGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTCACG GAGCTCGGGC
 GGCCCGTCGC TGAGTCCTGG AACGGGCAGA AGGAGATCTT GGAGCAGGAG
 CGGGCAACGG TGGACACCTA CTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_00201
DLA-DRB1_00201  270 bases  
 CACATTTCTT GGAGATGGTA AAGTTCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTATCTGGC GAGAGACATC TATAACCGGG AGGAGATCCT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCCCATCGC TGAGTCCTGG AACCGGCAGA AGGAGATCTT GGAGCAGAGG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCGCGGTG CAGCGGCGAG*

>DL;DLA-DRB1_00202
DLA-DRB1_00202  270 bases  
 CACATTTCTT GGAGATGGTA AAGTTCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTATCTGGC GAGAGACATC TATAACCGGG AGGAGATCCT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCCCATCGC TGAGTCCTGG AACCGGCAGA AGGAGATCTT GGAGCAGAGG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_00301
DLA-DRB1_00301  270 bases  
 CACATTTCTT GGAGGTGGCA AAGTCCGAGT GCTATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTCGTGGA AAGATACATC CATAACCGGG AGGAGAACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTCACG GAGCTCGGGC
 GGCCCGACGC TGAGTCCTGG AACCGGCAGA AGGAGCTCTT GGAGCGGAAG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_00401
DLA-DRB1_00401  270 bases  
 CACATTTCGT GTACCAGTTT AAGCCCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTCGTGGA AAGACACATC CATAACCGGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCCCGACGC TGAGTCCTGG AACGGGCAGA AGGAGCTCTT GGAGCAGGAG
 CGGGCAACGG TGGACACCTA CTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_00501
DLA-DRB1_00501  270 bases  
 CACATTTCTT GGAGATGTTA AAGTTCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTCGTGGA AAGATACATC CATAACCGGG AGGAGAACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCCCGACGC TGAGTCCTGG AACCGGCAGA AGGAGCTCTT GGAGCAGGAG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACCGGG TGGGCGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_00601
DLA-DRB1_00601  270 bases  
 CACATTTCTT GGAGGTGGCA AAGGCCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTCGTGGA AAGATACATC TATAACCGGG AGGAGTACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCCCGACGC TGAGTACTGG AACCCGCAGA AGGAGCTCTT GGAGCGGGCG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG TGGGCGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_00701
DLA-DRB1_00701  270 bases  
 CACATTTCTT GGAGGTGGCA AAGGCCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTCGTGGA AAGATACATC TATAACCGGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCCCGACGC TGAGTACTGG AACCCGCAGA AGGAGCTCTT GGAGGGGGGC
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG TGGGCGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_00801
DLA-DRB1_00801  270 bases  
 CACATTTCGT GAAGATGTAT AAGGCCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTATCTGAT GAGAGACATC TATAACCGGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTCACG GAGCTCGGGC
 GGCGCGACGC TGAGTACTGG AACGGGCAGA AGGAGATCTT GGAGCGGAAG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACCGGG TGGGCGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_00802
DLA-DRB1_00802  270 bases  
 CACATTTCGT GAAGATGTAT AAGGCCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTATCTGAT GAGAGACATC TATAACCGGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTCACG GAGCTCGGGC
 GGCGCGACGC TGAGTACTGG AACGGGCAGA AGGAGATCTT GGAGCGGAAG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCGCGGTG CAGCGGCGAG*

>DL;DLA-DRB1_00901
DLA-DRB1_00901  270 bases  
 CACATTTCTT GGAGGTGGCA AAGTCCGAGT GCTATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTCGTGGA AAGATACATC CATAACCGGG AGGAGAACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCCCGACGC TGAGTCCTGG AACCGGCAGA AGGAGTTCTT GGAGCGGAAG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_010011
DLA-DRB1_010011  237 bases  
 GTGTACCAGT TTAAGCCCGA GTGCCATTTC ACCAACGGGA CGGAGCGGGT
 GCGGTTCGTG GAAAGATACA TCCATAACCG GGAGGAGTTC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTCA CGGAGCTCGG GCGGCCCGTC
 GCTGAGTCCT GGAACGGGCA GAAGGAGCTC TTGGAGCAGG AGCGGGCAAC
 GGTGGACACC TACTGCAGAC ACAACTACGG GGTGATT*

>DL;DLA-DRB1_010012
DLA-DRB1_010012  237 bases  
 GTGTACCAGT TTAAGCCCGA GTGCCATTTC ACCAACGGGA CGGAGCGGGT
 GCGGTTCGTG GAAAGATACA TCCACAACCG GGAGGAGTTC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTCA CGGAGCTCGG GCGGCCCGTC
 GCTGAGTCCT GGAACGGGCA GAAGGAGCTC TTGGAGCAGG AGCGGGCAAC
 GGTGGACACC TACTGCAGAC ACAACTACGG GGTGATT*

>DL;DLA-DRB1_01101
DLA-DRB1_01101  270 bases  
 CACATTTCGT GAAGATGTTT AAGGCCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGCTTCTGGC GAGAAGCATC TATAACCGGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTCACG GAGCTCGGGC
 GGCGCGACGC TGAGTCCTGG AACCGGCAGA AGGAGCTCTT GGAGCAGAGG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACCGGG TGGGCGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_01201
DLA-DRB1_01201  270 bases  
 CACATTTCGT GAGGATGTAT AAGGCCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTTCTGGC GAGAAGCATC TATAACCGGG AGGAGTTCGC
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCGCGACGC TGAGTCCTGG AACCGGCAGA AGGAGCTCTT GGAGCGGAGG
 CGGGCCGAGG TGGACACCTA CTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_01301
DLA-DRB1_01301  270 bases  
 CACATTTCGT GTACCAGTTT AAGCCCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTCGTGGA AAGATACATC CATAACCGGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCCCGACGC TGAGTCCTGG AACCGGCAGA AGGAGCTCTT GGAGCAGGAG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACCGGG TGGGCGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_01401
DLA-DRB1_01401  270 bases  
 CACATTTCTT GGAGATGTTA AAGTCCGAGT GCTATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTCGTGGA AAGATACATC CATAACCGGG AGGAGAACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCCCGACGC TGAGTACTGG AACCCGCAGA AGGAGCTCTT GGAGCGGGCG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG TGGGCGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_01501
DLA-DRB1_01501  270 bases  
 CACATTTCTT GGAGATGGTA AAGTTCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGCTTCTGGT GAGAGACATC TATAACCGGG AGGAGCACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCCCGACGC TGAGTACTGG AACGGGCAGA AGGAGCTCTT GGAGCAGAGG
 CGGGCCGAGG TGGACACGGT GTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_01502
DLA-DRB1_01502  270 bases  
 CACATTTCTT GGAGATGGTA AAGTTCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGCTTCTGGT GAGAGACATC TATAACCGGG AGGAGCACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCCCGACGC TGAGTACTGG AACGGGCAGA AGGAGCTCTT GGAGCAGAGG
 CGGGCCGAGG TGGACACGGT GTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCGCGGTG CAGCGGCGAG*

>DL;DLA-DRB1_01503
DLA-DRB1_01503  270 bases  
 CACATTTCTT GGAGATGGTA AAGTTCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGCTTCTGGT GAGAGACATC TATAACCGGG AGGAGCACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCCCGACGC TGAGTACTGG AACGGGCAGA AGGAGCTCTT GGAGCAGAGG
 CGGGCCGAGG TGGACACCTA CTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_01601
DLA-DRB1_01601  270 bases  
 CACATTTCTT GGAGGTGGCA AAGGCCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTCGTGGA AAGATACATC CATAACCGGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCCCGACGC TGAGTCCTGG AACCGGCAGA AGGAGCTCTT GGAGCGGAAG
 CGGGCCGAGG TGGACACCTA CTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_01701
DLA-DRB1_01701  270 bases  
 CACATTTCGT GAAGATGTTT AAGGCCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTTCTGGC GAGAAGCATC TATAACCGGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCGCGACGC TGAGTCCTGG AACCGGCAGA AGGAGCTCTT GGAGCGGGCG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_01801
DLA-DRB1_01801  270 bases  
 CACATTTCTT GGAGGTGGCA AAGTCCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTCGTGGA AAGATACATC CATAACCGGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCCCGACGC TGAGTCCTGG AACCGGCAGA AGGAGCTCTT GGAGCGGAAG
 CGGGCCGAGG TGGACACCTA CTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_01901
DLA-DRB1_01901  270 bases  
 CACATTTCGT GAGGATGTAT AAGGCCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTTCTGGC GAGAAGCATC TATAACCGGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCGCGACGC TGAGTCCTGG AACCGGCAGA AGGAGCTCTT GGAGCGGAGG
 CGGGCCGAGG TGGACACCTA CTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_02001
DLA-DRB1_02001  270 bases  
 CACATTTCTT GAAGATGGTA AAGTTCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTGGTGGA AAGAGACATC TATAACCGGG AGGAGTACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCCCTCGGC TGAGTCCTGG AACCGGCAGA AGGAGTTCTT GGAGCAGAGG
 CGGGCCGAGG TGGACACGGT GTGCAGACAC AACTACGGGG TGGGCGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_02101
DLA-DRB1_02101  270 bases  
 CACATTTCGT GAAGATGTTT AAGGCCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGCTTCTGGC GAGAAGCATC TATAACCGGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTCACG GAGCTCGGGC
 GGCGCGACGC TGAGTCCTGG AACCGGCAGA AGGAGCTCTT GGAGCAGAGG
 CGGCCCGCGG TGGACACCTA CTGCAGACAC AACTACCGGG TGGGCGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_02201
DLA-DRB1_02201  270 bases  
 CACATTTCGT GTACCAGTTT AAGCCCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTCGTGGA AAGATACATC CATAACCGGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCCCGACGC TGAGTCCTGG AACGGGCAGA AGGAGATCTT GGAGCAGGAG
 CGGGCCGAGG TGGACACCTA CTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_02301
DLA-DRB1_02301  270 bases  
 CACATTTCTT GGAGATGTTA AAGTTCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTCGTGGA AAGATACATC CATAACCGGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCCCGACGC TGAGTCCTGG AACCGGCAGA AGGAGCTCTT GGAGCAGGAG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACCGGG TGGGCGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_02401
DLA-DRB1_02401  270 bases  
 CACATTTCTT GGAGGTGTTA AAGTCCGAGT GCTATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTCGTGGA AAGATACATC CATAACCGGG AGGAGAACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCGCGACGC TGAGTCCTGG AACCGGCAGA AGGAGCTCTT GGAGCGGAAG
 CGGGCCGAGG TGGACACCTA CTGCAGACAC AACTACCGGG TGGGCGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_02501
DLA-DRB1_02501  270 bases  
 CACATTTCTT GGAGGTGTTA AAGTTCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTGGTGGA AAGATACATC TATAACCGGG AGGAGTTCGC
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCGCGACGC TGAGTCCTGG AACCGGCAGA AGGAGCTCTT GGAGCAGAGG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACCGGG TGGGCGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_02601
DLA-DRB1_02601  270 bases  
 CACATTTCTT GGAGATGTTA AAGTCCGAGT GCTATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTCGTGGA AAGATACATC CATAACCGGG AGGAGAACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCCCGACGC TGAGTACTGG AACCGGCAGA AGGAGCTCTT GGAGCGGAAG
 CGGGCCGAGG TGGACACCTA CTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_02701
DLA-DRB1_02701  270 bases  
 CACATTTCGT GTACCAGTTT AAGGCCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTCGTGGA AAGATACATC CATAACCGGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCGCGACGC TGAGTCCTGG AACGGGCAGA AGGAGATCTT GGAGCAGGAG
 CGGGCAACGG TGGACACCTA CTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_02801
DLA-DRB1_02801  270 bases  
 CACATTTCTT GGAGGTGGCA AAGGCCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTCGTGGA AAGATACATC TATAACCGGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCCCGACGC TGAGTACTGG AACCCGCAGA AGGAGCTCTT GGAGCGGGCG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG TGGGCGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_02901
DLA-DRB1_02901  270 bases  
 CACATTTCGT GAAGATGTAT AAGGCCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTATCTGAT GAGAGACATC TATAACCGGG AGGAGAACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTCACG GAGCTCGGGC
 GGCGCGACGC TGAGTCCTGG AACGGGCAGA AGGAGATCTT GGAGCGGAAG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCGCGGTG CAGCGGCGAG*

>DL;DLA-DRB1_03001
DLA-DRB1_03001  237 bases  
 TTGGAGATGG TAAAGTTCGA GTGCCATTTC ACCAACGGGA CGGAGCGGGT
 GCGGCTTCTG GTGAGAGACA TCTATAACCG GGAGGAGCAC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTCA CGGAGCTCGG GCGGCCCGAC
 GCTGAGTCCT GGAACCGGCA GAAGGAGCTC TTGGAGCAGA GGCGGGCCGA
 GGTGGACACG GTGTGCAGAC ACAACTACGG GGTGATT*

>DL;DLA-DRB1_03101
DLA-DRB1_03101  270 bases  
 CACATTTCTT GAAGATGGTA AAGTTCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTATCTGAT GAGAGACATC TATAACCGGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTCACG GAGCTCGGGC
 GGCGCGACGC TGAGTCCTGG AACGGGCAGA AGGAGCTCTT GGAGCAGAAG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCGCGGTG CAGCGGCGAG*

>DL;DLA-DRB1_03201
DLA-DRB1_03201  270 bases  
 CACATTTCGT GTACCAGTTT AAGCCCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTCGTGGA AAGATACATC CATAACCGGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCCCGTCGC TGAGTCCTGG AACGGGCAGA AGGAGATCTT GGAGCAGGAG
 CGGGCAACGG TGGACACGGT GTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_03301
DLA-DRB1_03301  270 bases  
 CACATTTCTT GGAGATGTTA AAGTTCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTATCTGGT GAGAGACATC TATAACCGGG AGGAGCACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCCCGACGC TGAGTACTGG AACCGGCAGA AGGAGCTCTT GGAGCGGAGG
 CGGGCCGAGG TGGACACCTA CTGCAGACAC AACTACCGGG TGGGCGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_03501
DLA-DRB1_03501  270 bases  
 CACATTTCGT GAAGATGTTT AAGGCCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGCTTCTGGC GAGAAGCATC TATAACCGGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTCACG GAGCTCGGGC
 GGCGCGACGC TGAGTCCTGG AACCGGCAGA AGGAGTTCTT GGAGCAGAGG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACCGGG TGGGCGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_03601
DLA-DRB1_03601  270 bases  
 CACATTTCTT GGAGATGTTA AAGTCCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTCGTGGA AAGATACATC CATAACCGGG AGGAGAACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCGCGACGC TGAGTCCTGG AACCGGCAGA AGGAGCTCTT GGAGCGGAAG
 CGGGCCGAGG TGGACACCTA CTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_03701
DLA-DRB1_03701  270 bases  
 CACATTTCTT GGAGGTGGCA AAGGCCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTCGTGGA AAGATACATC TATAACCGGG AGGAGTACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCCCGACGC TGAGTCCTGG AACCCGCAGA AGGAGCTCTT GGAGCGGGCG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG TGGGCGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_03801
DLA-DRB1_03801  270 bases  
 CACATTTCTT GGAGATGGTA AAGTTCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGCTTCTGGT GAGAGACATC TATAACCGGG AGGAGCACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCCCGACGC TGAGTACTGG AACGGGCAGA AGGAGCTCTT GGAGCGGAGG
 CGGGCCGAGG TGGACACGGT GTGCAGACAC AACTACCGGG TGATTGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_03901
DLA-DRB1_03901  270 bases  
 CACATTTCGT GTACCAGTTT AAGCCCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTCGTGGA AAGATACATC CATAACCGGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCCCGTCGC TGAGTCCTGG AACGGGCAGA AGGAGATCTT GGAGCAGGAG
 CGGGCAACGG TGGACACCTA CTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_04001
DLA-DRB1_04001  270 bases  
 CACATTTCTT GAAGATGGTA AAGTTCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTGGTGGA AAGAGACATC TATAACCGGG AGGAGTACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTCACG GAGCTCGGGC
 GGCCCTCGGC TGAGTACTGG AACGGGCAGA AGGAGATCTT GGAGCAGAGG
 CGGGCCGAGG TGGACACGGT GTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCGCGGTG CAGCGGCGAG*

>DL;DLA-DRB1_04101
DLA-DRB1_04101  270 bases  
 CACATTTCTT GGAGATGTTA AAGTTCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTATCTGAT GAGAGACATC TATAACCGGG AGGAGAACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTCACG GAGCTCGGGC
 GGCGCGACGC TGAGTCCTGG AACGGGCAGA AGGAGCTCTT GGAGCAGAAG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCGCGGTG CAGCGGCGAG*

>DL;DLA-DRB1_04201
DLA-DRB1_04201  270 bases  
 CACATTTCTT GGAGATGTTA AAGTTCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTATCTGGT GAGAGACATC TATAACCGGG AGGAGAACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTCACG GAGCTCGGGC
 GGCCCGACGC TGAGTACTGG AACGGGCAGA AGGAGCTCTT GGAGCAGAAG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCGCGGTG CAGCGGCGAG*

>DL;DLA-DRB1_04301
DLA-DRB1_04301  270 bases  
 CACATTTCTT GGAGATGTTA AAGTTCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTATCTGGT GAGAGACATC TATAACCGGG AGGAGCACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCCCGACGC TGAGTACTGG AACCGGCAGA AGGAGCTCTT GGAGCGGAGG
 CGGGCCGAGG TGGACACGGT GTGCAGACAC AACTACCGGG TGGGCGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_04401
DLA-DRB1_04401  270 bases  
 CACATTTCTT GGAGGTGGCA AAGTCCGAGT GCTATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTAGTGGA AAGATACATC CATAACCGGG AGGAGAACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTCACG GAGCTCGGGC
 GGCCCGACGC TGAGTCCTGG AACCGGCAGA AGGAGCTCTT GGAGCAGAGG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACCGGG TGGGCGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_04501
DLA-DRB1_04501  270 bases  
 CACATTTCTT GGAGATGTTA AAGTCCGAGT GCTATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTCGTGGA AAGATACATC CATAACCGGG AGGAGAACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCCCGACGC TGAGTCCTGG AACGGGCAGA AGGAGCTCTT GGAGCGGAAG
 CGGGCCGAGG TGGACACCTA CTGCAGACAC AACTACGGGG TGGGCGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_04601
DLA-DRB1_04601  270 bases  
 CACATTTCTT GGAGATGTTA AAGTCCGAGT GCTATTTCAC CAACGGGACG
 GAGCGGGTGC GGTTCGTGGA AAGATACATC CATAACCGGG AGGAGAACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTCACG GAGCTCGGGC
 GGCCCGACGC TGAGTCCTGG AACCGGCAGA AGGAGCTCTT GGAGCAGGAG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCACGGTG CAGCGGCGAG*

>DL;DLA-DRB1_04701
DLA-DRB1_04701  270 bases  
 CACATTTCTT GAAGATGGTA AAGTTCGAGT GCCATTTCAC CAACGGGACG
 GAGCGGGTGC GGTATCTGAT GAGAGACATC TATAACCGGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTCACG GAGCTCGGGC
 GGCGCGACGC TGAGTCCTGG AACGGGCAGA AGGAGCTCTT GGAGCGGAGG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG TGATTGAGAG
 CTTCACGGTG CAGCGGCGAG*

