>P1;DLA-88_00101
DLA-88_00101  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRMEPRAPW
 MEQEGPEYWD RETRTAKETA QRYRVDLDTL RGYYNQSEAG SHTRQTMYGC
 DLGPGGRLLR GYSQDAYDGA DYIALNEDLR SWTAADTAAQ ITRRKWEAAG
 TAEHDRNYLE TTCVEWLRRY LEMGKETLLR A*

>P1;DLA-88_00201
DLA-88_00201  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRTEPRAPW
 VEQEGPEYWD RQTRTFKETA QVYRVDLDTL RGYYNQSEAG SHTRQTTYGC
 DLGPGGRLLR GYSQDAYDGA DYIALNEDLR SWTAADAAAQ ITRRKWEAAG
 TAEHDRNYLE TTCVEWLRRY LEMGKETLLR A*

>P1;DLA-88_00301
DLA-88_00301  181 bases  
 SHSLRYFRTS VSRPGRGDPL YISVGYVDDA QFVRFDSDAA SQKVEPRAPW
 VEQEGPEYWD RETRTSKENA QVYRVDLDTL RGYYNQSEAG SHTRQTTFGC
 DLGPGGRLLR GYWQDAYDGA DYIALNEDLR SWTAADAAAQ ITRRKREAAG
 DAGHLRNYLE TTCVEWLRRY LEMGKETLLR A*

>P1;DLA-88_00401
DLA-88_00401  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRVEPRAPW
 VEQEGPEYWD PQTRTIKETA RTFRVDLDTL RGYYNQSEAG SHTRQTMYGC
 DLGPGGRLLR GYRQDAYDGA DYIALNEDLR SWTAADAAAQ ITRRKWEAAG
 TAEHRRNYLE TTCVEWLRRY LEMGKETLLR A*

>P1;DLA-88_00402
DLA-88_00402  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRMEPRAPW
 VEQEGPEYWD PQTRTIKETA RTFRVDLDTL RGYYNQSEAG SHTRQTMYGC
 DLGPGGRLLR GYRQDAYDGA DYIALNEDLR SWTAADAAAQ ITRRKWEAAG
 TAEHRRNYLE TTCVEWLRRY LEMGKETLLR A*

>P1;DLA-88_00501
DLA-88_00501  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRTEPRAPW
 VEQEGPEYWD RQTRNFKETA RNFRVDLDTL RGYYNQSEAG AHTLQWMYGC
 DLGPGGRLLR GYWQDAYDGA DYLALNEDLR SWTAADTATQ ITRRKREAAG
 DAEHLRNYLE TTCVEWLRRY LEMGKETLQR A*

>P1;DLA-88_00601
DLA-88_00601  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRTEPRAPW
 VEQEGPEYWD PQTRTIKETA QLYRVDLDTL RGYYNQSEAG SHTRQTMYGC
 DLGPGGRLLR GYSQDAYDGA DYIALNEDLR SYTAADTAAQ ITRRKWEAAG
 TAEHDRNYLE TTCVEWLRRY LEMGKETLQR A*

>P1;DLA-88_00701
DLA-88_00701  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRTEPRAPW
 VEQEGPEYWD RETRNFKETA RNFRVDLDTL RGYYNQSEAG AHTLQWMYGC
 DLGPGGRLLR GYWQDAYDGA DYLALNEDLR SWTAADTATQ ITRRKREAAG
 DAEHLRNYLE TTCVEWLRRY LEMGKETLQR A*

>P1;DLA-88_00801
DLA-88_00801  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDA QFVRFDSDAA TGRTEPRAPW
 MEQEGPEYWD RETRTAKETA QRYRVDLDTL RGYYNQSEAG SHTRQTMYGC
 DLGPGGRLLR GYSQDAYDGA DYIALNEDLR SWTAADTAAQ ITRRKTEAAG
 VAEHLRNYLE MTCVEWLRRY LEMGKETLLR A*

>P1;DLA-88_00901
DLA-88_00901  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRMEPRAPW
 VEQEGPEYWD PQTRAIKETA RTFRVDLDTL RGYYNQSEAG SHTRQTMYGC
 DLGPGGRLLR GYRQDAYDGA DYIALNEDLR SWTAADAAAQ ITRRKWEAAG
 TAEHRRNYLE TTCVEWLRRY LEMGKETLLR A*

>P1;DLA-88_01001
DLA-88_01001  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRTEPRAPW
 VEQEGPEYWD RQTRTIKETA RTFRVDLDTL RGYYNQSEAG SHTRQTMYGC
 DLGPGGRLLR GYRQDAYDGA DYIALNEDLR SWTAADAAAQ ITRRKWEAAG
 TAEHRRNYLE TTCVEWLRRY LEMGKETLLR A*

>P1;DLA-88_01301
DLA-88_01301  181 bases  
 SHSLRYFYTA VSRPGRGDPL YISVGYVDDA QFVRFDSDAA TGRMEPRAPW
 VEQEGPEYWD GETRNVKETA RTFRVNLDTL RGYYNQSEAG SHTFQWMFGC
 DLGPGGRLLR GYSQVAYDGA DYIALNEDLR SWTAADAAAQ ITRRKWEAAG
 DAGHLRNYLE TTCVEWLQRY LEMGKETLLR A*

>P1;DLA-88_01401
DLA-88_01401  181 bases  
 SHSLRYFDTA VSRPGRGDPL YITVGYVDDT QFVRFDSDAA TGRMEPRAPW
 VEQEGPEYWD GETRKVKETA RTFRVSLDTL RGYYNQSEAG SHTIQWTSGC
 DVGPDGRLLR GYDQFAYDGA DYIALNEDLR SYTAADAAAQ ITRRKWEAAG
 VAEHDRNYLE TTCVEWLRRY LEMGKETLLR A*

>P1;DLA-88_01501
DLA-88_01501  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRTEPRAPW
 VEQEGPEYWD RQTRTFKETA RTFRVDLDTL RGYYNQSEAG SHTRQTMYGC
 DLGPGGRLLR GYRQEAYDGA DYIALNEDLR SWTAADAAAQ ITRRKWEAAG
 TAEHRRNYLE TTCVEWLRRY LEMGKETLLR A*

>P1;DLA-88_01601
DLA-88_01601  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRMEPRAPW
 VEQEGPEYWD PQTRTIKETA QRYRVSLDTL RGYYNQSEAG SHTRQTMYGC
 DLGPGGRLLR GYRQEAYDGA DYIALNEDLR SWTAADAAAQ ITRRKWEAAG
 TAEHEKNYLE TTCVEWLQRY LEMGKETLLR A*

>P1;DLA-88_01602
DLA-88_01602  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRMEPRAPW
 VEQEGPEYWD PQTRTIKETA QRYRVSLDTL RGYYNQSEAG SHTRQTMYGC
 DLGPGGRLLR GYRQEAYDGA DYIALNEDLR SWTAADTAAQ ITRRKWEAAG
 TAEHEKNYLE TTCVEWLQRY LEMGKETLLR A*

>P1;DLA-88_01701
DLA-88_01701  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRMEPRAPW
 VEQEGPEYWD PQTRTIKETA QRYRVSLDTL RGYYNQSEAG SHTIQTMYGC
 DLGPGGRLLR GYRQVAYDGA DYIALDEDLR SWTAADTAAQ ITRRKWEAAG
 DAEHERNYLE MTCVEWLRRY LEMGKETLLR A*

>P1;DLA-88_01801
DLA-88_01801  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRMEPRAPW
 VEQEGPEYWD PQTRTIRETA QRYRVSLDTL RGYYNQSEAG SHTIQTMYGC
 DLGPGGRLLR GYRQVAYDGA DYIALDEDLR SWTAADTAAQ ITRRKWEAAG
 DAEHERNYLE MTCVEWLRRY LEMGKETLLR A*

>P1;DLA-88_01901
DLA-88_01901  181 bases  
 SHSLRYFHTS VSRPGRGDPL YISVGYVDDT QFVRFDSDAA TGRMEPRAPW
 VEQEGPEYWD GQTRISKENA QLYRVDLDTL RGYYNQSEAG SHTRQTMYGC
 DLGPGGRLLR GYSQVAYDGA DYIALNEDLR SWTAADAAAQ ITRRKWEAAG
 VAEHDRNYLE TTCVEWLQRY LEMGKETLLR A*

>P1;DLA-88_02001
DLA-88_02001  181 bases  
 SHSLRYFRTS VSRPGRGDPL YISVGYVDDA QFVRFDSDAA SQKVEPRAPW
 VEQEGPEYWD RETRTSKENA QVYRVDLDTL HGYYNQSEAG SHTRQTMFGC
 DLGPGGRLLR GYWQDAYDGA DYIALNEDLR SWTAADAAAQ ITRRKREAAG
 DAGHLRNYLE TTCVEWLRRY LEMGKETLLR A*

>P1;DLA-88_02201
DLA-88_02201  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRTEPRAPW
 VEQEGPEYWD PQTRTIKETA RTFRVDLDTL RGYYNQSEAG SHTRQTMYGC
 DLGPGGRLLR GYSQDAYDGA DYIALNEDLR SYTAADTAAQ ITRRKWEAAG
 TAEHDRNYLE TTCVEWLRRY LEMGKETLQR A*

>P1;DLA-88_02301
DLA-88_02301  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRTEPRAPW
 VEQEGPEYWD GQTRKVKETA QLYRVDLDPL RGYYNQSEAG SHTIQTMYGC
 DLGPGGRLLR GYRQDAYDGA DYIALNEDLR SWTAADTAAQ ITRRKWEAAG
 TAEHDRNYLE TTCVEWLQRY LEMGKETLQR T*

>P1;DLA-88_02401
DLA-88_02401  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRTEPRAPW
 VEQEGPEYWD RQTRTIKETA RGYRVGLDTL RGYYNQSEAG SHTIQTMYGC
 DLGPGGRLLR GYRQDAYDGA DYIALNEDLR SWTAADTAAQ ITRRKWEAAG
 DAEHRRNYLE TTCVEWLQRY LEMGKETLLR A*

>P1;DLA-88_02501
DLA-88_02501  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRTEPRAPW
 VEQEGPEYWD RETRNFKETA RGYRVDLDTL RGYYNQSEAG SHTRQTMYGC
 DLGPGGRLLR GYRQEAYDGA DYIALNEDLR SWTAADTAAQ ITRRKWEAAG
 TAEHEKNYLE TTCVEWLQRY LEMGKETLLR A*

>P1;DLA-88_02601
DLA-88_02601  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRMEPRAPW
 VEQEGPEYWD RETRNFKETA RGYRVGLDTL RGYYNQSEAG SHTIQTMYGC
 DLGPGGRLLR GYRQDAYDGA DYIALNEDLR SWTAADTAAQ ITRRKWEAAG
 TAEHDRNYLE TTCVEWLQRY LEMGKETLQR T*

>P1;DLA-88_02701
DLA-88_02701  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRTEPRAPW
 VEQEGPEYWD RQTRNFKETA RGYRVGLDTL RGYYNQSEAG SHTIQTMYGC
 DLGPGGRLLR GYRQDAYDGA DYIALNEDLR SWTAADTAAQ ITRRKWEAAG
 TAEHDRSYLE TTCVEWLQRY LEMGKETLQR T*

>P1;DLA-88_02801
DLA-88_02801  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRMEPRAPW
 VEQEGPEYWD RETRNFKETA QVYRVGLDTL RGYYNQSEAG SHTIQTMYGC
 DLGPGGRLLR GYSQDAYDGA DYIALNEDLR SWTAADTAAQ ITRRKREAAG
 DAGHLRNYLE TTCVEWLQRY LEMGKETLLR A*

>P1;DLA-88_02802
DLA-88_02802  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDA QFVRFDSDAA TGRLEPRAPW
 VEQEGPEYWD RETRNFKETA QVYRVGLDTL RGYYNQSEAG SHTIQTMYGC
 DLGPGGRLLR GYSQDAYDGA DYIALNEDLR SWTAADTAAQ ITRRKREAAG
 DAGHLRNYLE TTCVEWLQRY LEMGKETLLR A*

>P1;DLA-88_03001
DLA-88_03001  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDA QFVRFDSDAA TGRLEPRAPW
 VEQEGPEYWD RETRNLKETA QVYRVGLDTL RGYYNQSEAG SHTIQTMYGC
 DLGPGGRLLR GYRQDAYDGA DYIALNEDLR SWTAADTAAQ ITRRKREAAG
 DAEHRRNYLE TTCVEWLQRY LEMGKETLLR A*

>P1;DLA-88_03101
DLA-88_03101  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRLEPRAPW
 VEQEGPEYWD PQTRTFKETA QLYRVDLDTL RGYYNQSEAG SHTRQTMYGC
 DLGPGGRLLR GYSQDAYDGA DYIALNEDTR SWTAADTAAQ ITRRKREAAG
 TAEHRRNYLE TTCVEWLRRY LEMGKETLLR A*

>P1;DLA-88_03401
DLA-88_03401  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRMEPRAPW
 VEQEGPEYWD GETRKVKETA QLYRVDLDTL RGYYNQSEAG SHTIQTMYGC
 DLGPGGRLLR GYSQDAYDGA DYIALNEDLR SWTAADAAAL ITRRKREAAG
 DAGHLRNYLE TTCVEWLRRY LEMGKETLLR A*

>P1;DLA-88_03501
DLA-88_03501  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRTEPRAPW
 VEQEGPEYWD RQTRTIKETA RTFRVDLDTL RGYYNQSEAG SHTRQTMYGC
 DLGPGGRLLR GYRQDAYDGA DYIALNEDLR SWTAADAAAQ ITRRKWEAAG
 DAEHRRNYLE TTCVEWLRRY LEMGKETLLR A*

>P1;DLA-88_03701
DLA-88_03701  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRTEPRAPW
 VEQEGPEYWD RQTRTFKETA QVFRVDLDTL RGYYNQSEAG SHTRQTTYGC
 DLGPGGRLLR GYSQDAYDGA DYIALNEDLR SWTAADAAAQ ITRRKWEAAG
 TAEHDRNYLE TTCVEWLRRY LEMGKETLLR A*

>P1;DLA-88_03801
DLA-88_03801  181 bases  
 SHSLRYFDTS VSRPGRGDPR FISVGYVDDT QFVRFDSDAA TGRMEPRAPW
 VEQEGPEYWD RQTRTSKENA QVCRVDLDTL RGYYNQSEAG SHTRQTMYGC
 DLGPGGRLLR GYWQVAYDGA DYIALNEDLR SWTAADTAAQ ITRRKWEAAG
 DAEHRRNYLE TTCVEWLRRY LEMGKETLLR A*

>P1;DLA-88_03901
DLA-88_03901  181 bases  
 SHSLRYFDTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRMEPRAPW
 VEQEGPEYWD GETRKVKETA QLYRVDLDTL RGYYNQSEAG SHTRQTMYGC
 DLGPGGRLLR GYRQVAYDGA DYIALNEDLR SWTAADAAAQ ITRRKWEAAG
 TAERHRNYLE TTCVEWLRRY LEMGKETLLR A*

>P1;DLA-88_04101
DLA-88_04101  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRMEPRAPW
 VEQEGPEYWD GETRNLKETA QVYRVDLDTL RGYYNQSEAG SHTIQTMYGC
 DLGPGGRLLR GYRQDAYDGA DYIALNEDLR SYTAADTAAQ ITRRKWEAAG
 TAEHDRNYLE TTCVEWLQRY LEMGKETLLR A*

>P1;DLA-88_04201
DLA-88_04201  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRMEPRAPW
 VEQEGPEYWD RQTRTFKETA RGYRVGLDTL RGYYNQSEAG SHTIQTMYGC
 DLGPGGRLLR GYRQDAYDGA DYIALNEDLR SWTAADTAAQ ITRRKWEAAG
 DAGHLRNYLE TTCVEWLQRY LEMGKETLLR A*

>P1;DLA-88_04301
DLA-88_04301  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRMEPRAPW
 VEQEGPEYWD RETRTAKETA QVYRVDLDTL RGYYNQSEAG SHTRQTMYGC
 DLGPGGRLLR GYWQDAYDGA DYIALNEDLR SWTAADTAAQ ITRRKWEAAG
 DAEHERNYLE TTCVEWLQRY LEMGKETLLR A*

>P1;DLA-88_04401
DLA-88_04401  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRTEPRAPW
 VEQEGPEYWD PQTRTIKETA QLYRVDLDTL RGYYNQSEAG SHTRQTMYGC
 DLGPGGRLLR GYRQDAYDGA DYIALNEDLR SWTAADAAAQ ITRRKWEAAG
 TAEHRRNYLE TTCVEWLRRY LEMGKETLLR A*

>P1;DLA-88_04801
DLA-88_04801  181 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRMEPRAPW
 VEQEGPEYWD PQTRTIKETA RTFRVDLDTL RGYYNQSEAG SHTRQTMYGC
 DLGPGGRLLR GYRQVAYDGA DYIALNEDLR SWTAADAAAQ ITRRKREAAG
 DAGHLRNYLE TTCVEWLRRY LEMGKETLLR A*

>P1;DLA-88_50101
DLA-88_50101  182 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDA QFVRFDSDAA TGRMEPRAPW
 VEQEGPEYWD PQTRTIKETA RTFRVDLDTL RGYYNQSEAG SHTRQTMYGC
 DLGPGGRLLR GYRQDAYDGA DYIALNEDLR SWTAADTAAQ ITRRKWEAAG
 VAELQWRNYL ETTCVEWLRR YLEMGKETLL RA*

>P1;DLA-88_50201
DLA-88_50201  182 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDA QFVRFDSDAA TGRMEPRAPW
 VEQEGPEYWD PQTRTIKETA RTFRVDLDTL RGYYNQSEAG SHTRQTMYGC
 DLGPGGRLLR GYSQDAYDGA DYIALNEDLR SWTAADTAAQ ITRRKWEAAG
 VAELQWRNYL ETTCVEWLRR YLEMGKETLL RA*

>P1;DLA-88_50301
DLA-88_50301  182 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDA QFVRFDSDAA TGRMEPRAPW
 VEQEGPEYWD RQTRTIKETA RTFRVDLDTL RGYYNQSEAG SHTRQTMYGC
 DLGPGGRLLR GYSQDAYDGA DYIALNEDLR SWTAADTAAQ ITRRKWEAAG
 VAELQWRNYL ETTCVEWLRR YLEMGKETLL RA*

>P1;DLA-88_50401
DLA-88_50401  182 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRMEPRAPW
 VEQEGPEYWD PQTRTIKETA RTFRVDLDTL RGYYNQSEAG SHTIQTMYGC
 DLGPGGRLLR GYSQDAYDGA DYIALNEDLR SWTAADTAAQ ITRRKWEAAG
 VAELQWRNYL ETTCVEWLRR YLEMGKETLL RA*

>P1;DLA-88_50501
DLA-88_50501  182 bases  
 SHSLRYFHTS VSRPGRGDPL YISVGYVDDT QFVRFDSDAA TGRMEPRAPW
 VEQEGPEYWD RQTRISKENA QVYRVDLDTL RGYYNQSEAG SHTIQTMYGC
 DLGPGGRLLR GYSQVAYDGA DYISLNEDLR SWTAADAAAQ ITRRKWEAAG
 VAELQWRNYL ETTCVEWLRR YLEMGKETLL RA*

>P1;DLA-88_50601
DLA-88_50601  182 bases  
 SHSLRYFHTS VSRPGRGDPL YISVGYVDDT QFVRFNSDAA TGRMEPRAPW
 VEQEGPEYWD PQTRISKENA QVYRVSLDTL RGYYNQSEAG SHTIQTMYGC
 DLGPGGRLLR GYSQVAYDGA DYISLNEDLR SWTAADAAAQ ITRRKWEAAG
 VAELQWRNYL ETTCVEWLQR YLEMGKETLL RA*

>P1;DLA-88_50701
DLA-88_50701  182 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRMEPRAPW
 VEQEGPEYWD GETRKVKETA QVYRVDLDTL RGYYNQSEAG SHTRQTMYGC
 DLGPGGRLLR GYRQVAYDGA DYIALNEDLR SWTAADAAAQ ITRRKWEAAG
 VAELQWRNYL ETTCVEWLRR YLEMGKETLL RA*

>P1;DLA-88_50801
DLA-88_50801  182 bases  
 SHSLRYFYTS VSRPGRGDPR FIAVGYVDDT QFVRFDSDAA TGRTEPRAPW
 VEQEGPEYWD GETRKVKETA QVYRVDLDTL RGYYNQSEAG SHTIQTMYGC
 DLGPGGRLLR GYRQDAYDGA DYIALNEDLR SWTAADTAAQ ITRRKWEAAG
 VAELQWRNYL ETTCVEWLQR YLEMGKETLL RA*

