>DL;DLA-DQB1*00101
DLA-DQB1*00101, 357 bases, 96A26FFF checksum.
 GATTTCGTGT ACCAGTTTAA GGGCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGACGA GAGACATCTA TAACCGGGAG GAGCACGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG
 CCGGACGCTG AGTACTGGAA CGGGCAGGAG GAGCACGTGC GCTTCGACAG
 CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG CCGGACGCTG
 AGTACTGGAA CGGGCAGAAG GAGCTCTTGG AGCGGAGGCG GGCCGAGGTG
 GACACGGTGT GCAGACACAA CTACGGGAGG GAAGAGCTCA CCACGTTGCA
 GCGGCGA*

>DL;DLA-DQB1*00201
DLA-DQB1*00201, 267 bases, CD5C0E12 checksum.
 GATTTCGTGT TCCAGTATAA GGCCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGACTA AATACATCTA TAACCGGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTCACGGA GCTCGGGCGG
 CCCGACGCTG AGTACTGGAA CCGACAGGAG GACGAGATGC GCTTCGTAAG
 CGACGTGCGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG CCGGACGCTG
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*00301
DLA-DQB1*00301, 267 bases, 36C3B361 checksum.
 GATTTCGTGT ACCAGTTTAA GGCCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGACTA AATACATCTA TAACCGGGAG GAGTACGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG
 CCCTCGGCTG AGTACTGGAA CCCGCAGGAG GACGAGATGC GCTTCGTAAG
 CGACGTGCGG GAGTACCGGG CGGTCACGGA GCTCGGGTTG CCGGACGCTG
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*00401
DLA-DQB1*00401, 267 bases, 112D21D checksum.
 GATTTCGTGT TCCAGTTTAA GGGCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGACTA AATACATCTA TAACCGGGAG GAGTACGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG
 CCCTGGGCTG AGTACTGGAA CCCGCAGGAG GACGAGATGC GCTTCGTAAG
 CGACGTGCGG GAGTACCGGG CGGTCACGGA GCTCGGGTTG CCGGACGCTT
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*00501
DLA-DQB1*00501, 267 bases, FA97DA06 checksum.
 GATTTCGTGT TCCAGTATAA GGCCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGACTA AATACATCTA TAACCGGGAG GAGTACGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG
 CCCTGGGCTG AGTACTGGAA CCCGCAGGAG GACGAGATGC GCTTCGTAAG
 CGACGTGCGG GAGTACCGGG CGGTCACGGA GCTCGGGTTG CCGGACGCTG
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*00502
DLA-DQB1*00502, 267 bases, A25405F2 checksum.
 GATTTCGTGT TCCAGTATAA GGCCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGACTA AATACATCTA TAACCGGGAG GAGTACGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTCACGGA GCTCGGGCGG
 CCCTGGGCTG AGTACTGGAA CCCGCAGGAG GACGAGATGC GCTTCGTAAG
 CGACGTGCGG GAGTACCGGG CGGTCACGGA GCTCGGGTTG CCGGACGCTG
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*00701
DLA-DQB1*00701, 267 bases, C4C700EC checksum.
 GATTTCGTGT ACCAGTTTAA GTTCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGGCGA GAGACATCTA TAACCGGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG
 CCGGACGCTG AGTACTGGAA CGGGCAGGAG GAGCACGTGC GCTACGACAG
 CGACGTGCGG GAGTACCGGG CGGTCACGGA GCTCGGGTTG CCGGACGCTT
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*008011
DLA-DQB1*008011, 267 bases, 5025557A checksum.
 GATTTCGTGT ACCAGTTTAA GGGCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGACTA AATACATCTA TAACCGGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG
 CCCGACGCTG AGTACTGGAA CCGACAGGAG GACGAGATGC GCTTCGTAAG
 CGACGTGCGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG CCGGACGCTG
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*008012
DLA-DQB1*008012, 267 bases, 46849772 checksum.
 GATTTCGTGT ACCAGTTTAA GGGCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGACTA AATACATCTA TAACCGGGAG GAGTTCGTGC
 GCTTTGACAG CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG
 CCCGACGCTG AGTACTGGAA CCGACAGGAG GACGAGATGC GCTTCGTAAG
 CGACGTGCGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG CCGGACGCTG
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*00802
DLA-DQB1*00802, 267 bases, 8E68A8E checksum.
 GATTTCGTGT ACCAGTTTAA GGGCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGACTA AATACATCTA TAACCGGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTCACGGA GCTCGGGCGG
 CCCGACGCTG AGTACTGGAA CCGACAGGAG GACGAGATGC GCTTCGTAAG
 CGACGTGCGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG CCGGACGCTG
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*01101
DLA-DQB1*01101, 267 bases, B94122BB checksum.
 GATTTCGTGT ACCAGTTTAA GGCCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGACTA AATACATCTA TAACCGGGAG GAGCACGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG
 CCCTCGGCTG AGTACTGGAA CCCGCAGGAG GACGAGATGC GCTTCGTAAG
 CGACGTGCGG GAGTACCGGG CGGTCACGGA GCTCGGGTTG CCGGACGCTG
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*01201
DLA-DQB1*01201, 267 bases, 3EDD0D11 checksum.
 GATTTCGTGT TCCAGTTTAA GTTCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGGCGA GAGACATCTA TAACCGGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG
 CCGGACGCTG AGTACTGGAA CGGGCAGGAG GAGCACGTGC GCTACGACAG
 CGACGTGCGG GAGTACCGGG CGGTCACGGA GCTCGGGTTG CCGGACGCTT
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*01301
DLA-DQB1*01301, 267 bases, 5B1AE02A checksum.
 GATTTCGTGT ACCAGTTTAA GTTCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGACTA AATACATCTA TAACCGGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG
 CCCGACGCTG AGTACTGGAA CCCGCAGGAG GACGAGATGC GCTTCGTAAG
 CGACGTGCGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG CCGGACGCTG
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*01302
DLA-DQB1*01302, 267 bases, 89598A63 checksum.
 GATTTCGTGT ACCAGTTTAA GTTCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGACTA AATACATCTA TAACCGGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG
 CCCGACGCTG AGTACTGGAA CCCGCAGGAG GACGAGATGC GCTTCGTAAG
 CGACGTGCGG GAGTACCGGG CGGTCACGGA GCTCGGGGTG CCGGACGCTG
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*01303
DLA-DQB1*01303, 267 bases, 4D7C0B19 checksum.
 GATTTCGTGT ACCAGTTTAA GTTCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGACTA AATACATCTA TAACCGGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG
 CCCGACGCTG AGTACTGGAA CCCGCAGGAG GACGAGATGC GCTTCGTAAG
 CGACGTGCGG GAGTACCGGG CGGTCACGGA GCTCGGGGTG CCGGACGCTT
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*01401
DLA-DQB1*01401, 267 bases, A53F2BED checksum.
 GATTTCGTGT ACCAGTTTAA GGGCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGGCGA GAGACATCTA TAACCGGGAG GAGCACGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTCACGGA GCTCGGGCGG
 CCCTGGGCTG AGTACTGGAA CGGGCAGGAG GAGAACGTGC GCTTCGACAG
 CGACGTGCGG GAGTACCGGG CGGTCACGGA GCTCGGGGTG CCGGACGCTT
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*01501
DLA-DQB1*01501, 267 bases, 743361FC checksum.
 GATTTCGTGT ACCAGTGTAA GGCCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG TTTCTGGCTA AATACATCTA TAACCGGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTCACGGA GCTCGGGCGG
 CCCTCGGCTG AGTACTGGAA CGGGCAGGAG GAGAACGTGC GCTACGACAG
 CGAAACGGGG GAGTACCGGG CGGTCACGGA GCTCGGGGTG CCGGACGCTT
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*01601
DLA-DQB1*01601, 267 bases, CF3FB2B0 checksum.
 GATTTCGTGT ACCAGTTTAA GGGCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGACGA GAAGCATCTA TAACCGGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTCACGGA GCTCGGGCGG
 CCCGTCGCTG AGTACTGGAA CGGGCAGGAG GAGAACGTGC GCTTCGACAG
 CGACGTGGGG GAGTGCCGGG CGGTCACGGA GCTCGGGCGG CCGGACGCTG
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*01701
DLA-DQB1*01701, 267 bases, F907B631 checksum.
 GATTTCGTGT TCCAGTGTAA GGCCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG TTTCTGGCTA AATACATCTA TAACCGGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG
 CCCGACGCTG AGTCCTGGAA CGGGCAGGAG GAGTACGTGC GCTACGACAG
 CGAAACGGGG GAGTACCGGG CGGTCACGGA GCTCGGGGTG CCGGACGCTT
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*01801
DLA-DQB1*01801, 267 bases, 621C4D71 checksum.
 GATTTCGTGT ACCAGTTTAA GTTCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGACTA AATACATCTA TAACCGGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG
 CCCGACGCTG AGTACTGGAA CCCGCAGGAG GACGAGATGC GCTTCGTCAG
 CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGGTG CCGGACGCTT
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*01901
DLA-DQB1*01901, 267 bases, 18A178F1 checksum.
 GATTTCGTGT TCCAGTGTAA GGCCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG TTTCTGGCTA AATACATCTA TAACCGGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTCACGGA GCTCGGGCGG
 CCCTCGGCTG AGTACTGGAA CGGGCAGGAG GAGCACGTGC GCTAAGACAG
 CGAAACGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG CCGGACGCTG
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*02001
DLA-DQB1*02001, 267 bases, A17F2D66 checksum.
 GATTTCGTGT ACCAGTTTAA GGCCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGACGA GAAGCATCTA TAACCGGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTCACGGA GCTCGGGCGG
 CCCGTCGCTG AGTACTGGAA CGGGCAGGAG GAGAACGTGC GCTTCGACAG
 CGACGCGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG CCGGACGCTG
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*02002
DLA-DQB1*02002, 267 bases, 7CDD8AA1 checksum.
 GATTTCGTGT ACCAGTTTAA GGCCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGACGA GAAGCATCTA TAACCGGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTCACGGA GCTCGGGCGG
 CCCGTCGCTG AGTACTGGAA CGGGCAGGAG GAGAACGTGC GCTTCGACAG
 CGACGCGGGG GAGTGCCGGG CGGTCACGGA GCTCGGGCGG CCGGACGCTG
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*02101
DLA-DQB1*02101, 267 bases, AFBFA67B checksum.
 GATTTCGTGT ACCAGTTTAA GGCCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGACGA GAAGCATCTA TAACCGGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTCACGGA GCTCGGGCGG
 CCCGTCGCTG AGTACTGGAA CGGGCAGGAG GAGAACGTGC GCTTCGACAG
 CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG CCGGACGCTG
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*02201
DLA-DQB1*02201, 267 bases, 8BFC8DE checksum.
 GATTTCGTGT ACCAGTTTAA GGGCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGACTA AATACATCTA TAACCGGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG
 CCCTCGGCTG AGTACTGGAA CCCGCAGGAG GACGAGATGC GCTTCGTAAG
 CGACGTGCGG GAGTACCGGG CGGTCACGGA GCTCGGGTTG CCGGACGCTG
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*02301
DLA-DQB1*02301, 267 bases, 8BE1006D checksum.
 GATTTCGTGT ACCAGTTTAA GGGCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGACTA AATACATCTA TAACCGGGAG GAGTACGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG
 CCCTCGGCTG AGTACTGGAA CCCGCAGGAG GACGAGATGC GCTTCGTAAG
 CGACGTGCGG GAGTACCGGG CGGTCACGGA GCTCGGGTTG CCGGACGCTG
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*02401
DLA-DQB1*02401, 267 bases, 7ADA77B3 checksum.
 GATTTCGTGT ACCAGTGTAA GGCCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG TTTCTGGCTA AATACATCTA TAACCGGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG
 CCCGACGCTG AGTACTGGAA CGGGCAGGAG GAGCACGTGC GCTACGACAG
 CGAAACGCGG GAGTACCGGG CGGTCACGGA GCTCGGGGTG CCGGACGCTT
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*02601
DLA-DQB1*02601, 267 bases, C1FF39AD checksum.
 GATTTCGTGT ACCAGTTTAA GGGCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGACGA GAAGCATCTA TAACCGGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTCACGGA GCTCGGGCGG
 CCCGTCGCTG AGTACTGGAA CGGGCAGGAG GAGAACGTGC GCTTCGACAG
 CGACGCGGGG GAGTGCCGGG CGGTCACGGA GCTCGGGCGG CCGGACGCTG
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*02701
DLA-DQB1*02701, 267 bases, DAE2857 checksum.
 GATTTCGTGT ACCAGTTTAA GTTCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGGCGA GAGACATCTA TAACCGGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG
 CCCGACGCTG AGTACTGGAA CCCGCAGGAG GACGAGATGC GCTTCGTAAG
 CGACGTGCGG GAGTACCGGG CGGTCACGGA GCTCGGGGTG CCGGACGCTT
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*02801
DLA-DQB1*02801, 267 bases, 9D5386C5 checksum.
 GATTTCGTGT ACCAGTTTAA GTTCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGGCGA GAGACATCTA TAACCGGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG
 CCGGACGCTG AGTACTGGAA CCGGCAGGAG GAGCACGTGC GCTACGACAG
 CGACGCGGGG GAGTACCGGG CGGTCACGGA GCTCGGGTTG CCGGACGCTT
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*03001
DLA-DQB1*03001, 267 bases, 8ECB29EB checksum.
 GATTTCGTGT TCCAGTTTAA GGGCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGACGA GAGACATCTA TAACCGGGAG GAGCACGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG
 CCGGACGCTG AGTACTGGAA CGGGCAGGAG GAGCACGTGC GCTTCGACAG
 CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG CCGGACGCTG
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*03101
DLA-DQB1*03101, 267 bases, 71FB0D90 checksum.
 GATTTCGTGT TCCAGTTTAA GGGCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGACTA AATACATCTA TAACCGGGAG GAGTACGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG
 CCCTCGGCTG AGTACTGGAA CCCGCAGGAG GACGAGATGC GCTTCGTAAG
 CGACGTGCGG GAGTACCGGG CGGTCACGGA GCTCGGGTTG CCGGACGCTG
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*03201
DLA-DQB1*03201, 267 bases, 6015BDBB checksum.
 GATTTCGTGT TCCAGTTTAA GTTCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGACTA AATACATCTA TAACCGGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG
 CCCGACGCTG AGTACTGGAA CCGACAGGAG GACGAGATGC GCTTCGTAAG
 CGACGTGCGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG CCGGACGCTG
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*03301
DLA-DQB1*03301, 267 bases, BC51950D checksum.
 GATTTCGTGT ACCAGTTTAA GGCCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGACGA GAAGCATCTA TAACCGGGAG GAGTTGGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTCACGGA GCTCGGGCGG
 CCCGTCGCTG AGTACTGGAA CGGGCAGGAG GAGCACGTGC GCTTCGACAG
 CGACGCGGGG GAGTGCCGGG CGGTCACGGA GCTCGGGCGG CCGGACGCTG
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*03401
DLA-DQB1*03401, 267 bases, E4C725A2 checksum.
 GATTTCGTGT TCCAGTTTAA GGCCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGACGA GAGACATCTA TAACCGGGAG GAGCACGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG
 CCCGACGCTG AGTACTGGAA CGGGCAGGAG GAGCACGTGC GCTTCGACAG
 CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG CCGGACGCTG
 AGTACTGGAA CGGGCAG*

>DL;DLA-DQB1*03501
DLA-DQB1*03501, 267 bases, 1F35E6C0 checksum.
 GATTTCGTGT ACCAGTTTAA GTTCGAGTGC TATTTCACCA ACGGGACGGA
 GCGGGTGCGG CTTCTGGCGA GAGACATCTA TAACCGGGAG GAGCACGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTCACGGA GCTCGGGCGG
 CCCGACGCTG AGTACTGGAA CGGGCAGGAG GAGCACGTGC GCTACGACAG
 CGACGTGCGG GAGTACCGGG CGGTCACGGA GCTCGGGTTG CCGGACGCTT
 AGTACTGGAA CGGGCAG*

