>DL;DLA-DQA1_00101
DLA-DQA1_00101  246 bases  
 GACCATGTTG CCAACTACGG CATAAATGTC TACCAGTCTT ACGGTCCCTC
 TGGCCAGTAC ACCCATGAAT TTGATGGCGA TGAGGAGTTC TACGTGGACC
 TGGAGAAGAA GGAAACTGTC TGGCGGCTGC CTGTGTTTAG CACATTTAGA
 AGTTTTGACC CACAGGGTGC ACTGAGAAAC TTGGCTATAA TAAAACAAAA
 CTTGAACATC ATGACTAAAA GGTCCAACCA AACTGCTGCT ACCAAT*

>DL;DLA-DQA1_00201
DLA-DQA1_00201  246 bases  
 GACCATGTTG CCTACTACGG CATAAATGTC TACCAGTCTT ACGGTCCCTC
 TGGCCAGTAC ACCCATGAAT TTGATGGCGA TGAGGAGTTC TACGTGGACC
 TGGAGAAGAA GGAAACTGTC TGGCGGCTGC CTGTGTTTAG CACATTTACA
 AGTTTTGACC CACAGGGTGC ACTGAGAAAC TTGGCTATAA CAAAACAAAA
 CTTGAACATC ATGACTAAAA GGTCCAACAA AACTGCTGCT ACCAAT*

>DL;DLA-DQA1_00301
DLA-DQA1_00301  246 bases  
 GACCATGTTG CCTACTACGG CATAAATGTC TACCAGTCTT ACGGTCCCTC
 TGGCCAGTAC ACCCATGAAT TTGATGGCGA TGAGGAGTTC TACGTGGACC
 TGGAGAAGAA GGAAACTGTC TGGCGGCTGC CTGTGTTTAG CACATTTACA
 AGTTTTGACC CACAGGGTGC ACTGAGAAAC TTGGCCAGAG CAAAACAAAA
 CTTGAACATC CTGACTAAAA GTTCCAACCA AACTGCTGCT ACCAAT*

>DL;DLA-DQA1_00401
DLA-DQA1_00401  246 bases  
 GACCATGTTG CCTACTACGG CATAAATGTC TACCAGTCTT ACGGTCCCTC
 TGGCCAGTAC ACCCATGAAT TTGATGGCGA TGAGGAGTTC TACGTGGACC
 TGGAGAAGAA GGAAACTGTC TGGCGGCTGC CTGTGTTTAG CACATTTACA
 AGTTTTGACC CACAGGGTGC ACTGAGAAAC TTGGCTATAA TAAAACAAAA
 CTTGAACATC CTGACTAAAA GGTCCAACCA AACTGCTGCT ACCAAT*

>DL;DLA-DQA1_005011
DLA-DQA1_005011  246 bases  
 GACCATGTTG CCTACTACGG CATAAATGTC TACCAGTCTT ACGGTCCCTC
 TGGCCAGTTC ACCCATGAAT TTGATGGCGA TGAGGAGTTC TACGTGGACC
 TGGAGAAGAA GGAAACTGTC TGGCGGCTGC CTGTGTTTAG CACATTTACA
 AGTTTTGACC CACAGGGTGC ACTGAGAAAC TTGGCTATAA CAAAACAAAA
 CTTGAACATC ATGACTAAAA GGTCCAACAA AACTGCTGCT ACCAAT*

>DL;DLA-DQA1_005012
DLA-DQA1_005012  246 bases  
 GACCATGTTG CCTACTACGG CATAAATGTC TACCAGTCTT ACGGTCCCTC
 TGGCCAGTTC ACCCATGAAT TTGATGGCGA TGAGGAGTTC TACGTGGACC
 TGGAGAAGAA GGAAACTGTC TGGCGGCTGC CTGTGTTTAG CACATTTACA
 AGTTTTGACC CACAGGGTGC GCTGAGAAAC TTGGCTATAA CAAAACAAAA
 CTTGAACATC ATGACTAAAA GGTCCAACAA AACTGCTGCT ACCAAT*

>DL;DLA-DQA1_00601
DLA-DQA1_00601  246 bases  
 GACCATGTTG CCTACTACGG CATAAATGTC TACCAGTCTT ACGGTCCCTC
 TGGCCAGTAC ACCCATGAAT TTGATGGCGA TGAGGAGTTC TACGTGGACC
 TGGAGAAGAA GGAAACTGTC TGGCGGCTGC CTGTGTTTAG CACATTTAGA
 AGTTTTGACC CACAGGGTGC ACTGAGAAAC TTGGCTATAA TAAAACAAAA
 CTTGAACATC CTGACTAAAA GGTCCAACCA AACTGCTGCT ACCAAT*

>DL;DLA-DQA1_00701
DLA-DQA1_00701  246 bases  
 GACCATGTTG CCTACTACGG CATAAATGTC TACCAGTCTT ACGGTCCCTC
 TGGCCAGTAC ACCCATGAAT TTGATGGCGA TGAGGAGTTC TACGTGGACC
 TGGAGAAGAA GGAAACTGTC TGGCGGCTGC CTGTGTTTAG CACATTTACA
 AGTTTTGACC CACAGGGTGC ACTGAGAAAC TTGGCTATAA CAAAACAAAA
 CTTGAACATC ATGACTAAAA GGTCCAACCA AACTGCTGCT ACCAAT*

>DL;DLA-DQA1_00801
DLA-DQA1_00801  246 bases  
 GACCATGTTG CCTACTACGG CATAAATGTC TACCAGTCTT ACGGTCCCTC
 TGGCCAGTAC ACCCATGAAT TTGATGGCGA TGAGGAGTTC TACGTGGACC
 TGGAGAAGAA GGAAACTGTC TGGCGGCTGC CTGTGTTTAG CACATTTACA
 AGTTTTGACC CACAGGGTGC ACTGAGAAAC TTGGCCAGAG CAAAACAAAA
 CTTGAACATC CTGACTAAAA GGTCCAACCA AACTGCTGCT ACCAAT*

>DL;DLA-DQA1_00901
DLA-DQA1_00901  246 bases  
 GACCATGTTG CCTACTACGG CATAAATGTC TACCAGTCTT ACGGTCCCTC
 TGGCCAGTTC ACCCATGAAT TTGATGGCGA TGAGGAGTTC TACGTGGACC
 TGGAGAAGAA GGAAACTGTC TGGCGGCTGC CTGTGTTTAG CACATTTAGA
 AGTTTTGACC CACAGGGTGC ACTGAGAAAC TTGGCTATAA TAAAACAAAA
 CTTGAACATC ATGACTAAAA GGTCCAACCA AACTGCTGCT ACCAAT*

>DL;DLA-DQA1_01001
DLA-DQA1_01001  246 bases  
 GACCATGTTG CCTACTACGG CATAAATGTC TACCAGTCTT ACGGTCCCTC
 TGGCCAGTAC ACCCATGAAT TTGATGGCGA TGAGGAGTTC TACGTGGACC
 TGGAGAAGAA GGAAACTGTC TGGCGGCTGC CTGTGTTTAG CACATTTAGA
 AGTTTTGACC CACAGGGTGC ACTGAGAAAC TTGGCTATAG CAAAACAAAA
 CTTGAACATC CTGACTAAAA GTTCCAACCA AACTGCTGCT ACCAAT*

>DL;DLA-DQA1_01101
DLA-DQA1_01101  246 bases  
 GACCATGTTG CCTACTACGG CATAAATGTC TACCAGTCTT ACGGTCCCTC
 TGGCCAGTAC ACCCATGAAT TTGATGGCGA TGAGGAGTTC TACGTGGACC
 TGGAGAAGAA GGAAACTGTC TGGCGGCTGC CTGTGTTTAG CACATTTACA
 AGTTTTGACC CACAGGGTGC ACTGAGAAAC TTGGCTATAA TAAAACAAAA
 CTTGAACATC ATGACTAAAA GGTCCAACAA AACTGCTGCT ACCAAT*

>DL;DLA-DQA1_01201
DLA-DQA1_01201  246 bases  
 GACCATGTTG CCTACTACGG CATAAATGTC TACCAGTCTT ACGGTCCCTC
 TGGCCAGTAC ACCCATGAAT TTGATGGCGA TGAGGAGTTC TACGTGGACC
 TGGAGAAGAA GGAAACTGTC TGGCGGCTGC CTGTGTTTAG CACATTTGCA
 AGTTTTGACC CACAGGGTGC ACTGAGAAAC TTGGCTATAG CAAAACAAAA
 CTTGAACATC ATGACTAAAA GGTCCAACCA AACTGCTGCT ACCAAT*

>DL;DLA-DQA1_01301
DLA-DQA1_01301  246 bases  
 GACCATGTTG CCTACTACGG CATAAATGTC TACCAGTCTT ACGGTCCCTC
 TGGCCAGTAC ACCCATGAAT TTGATGGCGA TGAGGAGTTC TACGTGGACC
 TGGAGAAGAA GGAAACTGTC TGGCGGCTGC CTGTGTTTAG CACATTTAGA
 AGTTTTGACC CACAGGGTGC ACTGAGAAAC TTGGCTATAA CAAAACAAAA
 CTTGAACATC ATGACTAAAA GGTCCAACAA AACTGCTGCT ACCAAT*

>DL;DLA-DQA1_01401
DLA-DQA1_01401  246 bases  
 GACCATGTTG CCTACTACGG CATAAATGTC TACCAGTCTT ACGGTCCCTC
 TGGCCAGTAC ACCCATGAAT TTGATGGCGA TGAGGAGTTC TACGTGGACC
 TGGAGAAGAA GGAAACTGTC TGGCGGCTGC CTGTGTTTAG CACATTTAGA
 AGTTTTGACC CACAGGGTGC ACTGAGAAAC TTGGCTATAA TAAAACAAAA
 CTTGAACATC ATGACTAAAA GGTCCAACCA AACTGCTGCT ACCAAT*

>DL;DLA-DQA1_01501
DLA-DQA1_01501  246 bases  
 GACCATGTTG CCAACTACGG CATAAATGTC TACCAGTCTT ACGGTCCCTC
 TGGCCAGTTC ACCCATGAAT TTGATGGCGA TGAGGAGTTC TACGTGGACC
 TGGAGAAGAA GGAAACTGTC TGGCGGCTGC CTGTGTTTAG CACATTTAGA
 AGTTTTGACC CACAGGGTGC ACTGAGAAAC TTGGCTATAA TAAAACAAAA
 CTTGAACATC ATGACTAAAA GGTCCAACCA AACTGCTGCT ACCAAT*

