>DL;IPD:MHC01451
IPD:MHC01451 Aoaz-DRB*W38:01 252 bases
 TTGGAGCAGG CTAAGTATGA GTGTCATTTC CTCAACGGGA CGGAGCGGGT
 GCGGTTCCTG GAAAGACACA TCCATAACCA GGAGGAGTAT GCGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCGGACC
 GCAGAGTACT GGAACAGCCA GAAGGACATC CTGGAGGACA GGCGGGCCCA
 GGTGGACACC GTGTGCAGAC ACAACTACGG GGTTGGTGAG AGCTTCACAG
 TG*    
>DL;IPD:MHC01450
IPD:MHC01450 Aoaz-DRB3*06:01 252 bases
 TTGGAGCTGG TTAAGCATGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTACCTG GACAGATACC TTTATAACCA GAAGGAGTAT GTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCGAGTACT GGAACAGCCA GAAGGACTAC GTGGAGCAGA AGCGGGGCCA
 AGTGGACAAC TACTGCAGAC ACAACTACGG GGTTTTTGAG AGCTTCACAG
 TG*    
