>DL;IPD:MHC04219
IPD:MHC04219 Aona-DPB1*01 157 bases
 RLYECYAFNG TQRLLDRLFY NREEFVRFDS DLGEFRSVTE LGRPDAKYWN
 SDKDILEGMR AEVERVCRHN YELVEPLIRK RQVQPKVNVS PSKKGSLQHH
 NLLVCHVTDF YPGSIQVRWF LNGQEETAGI VSTNLIRNGD WTFQILVMLE
 MTPQQGD*    
>DL;IPD:MHC04220
IPD:MHC04220 Aona-DPB1*02 157 bases
 RLYECYAFNG TQRLLDRLFY NREEFVRFDS DLGEYLAVTE LGRPDAKYWN
 SDKDILEGMR AEVERVCRHN YELVEPLIRK RQVQPKVNVS PSKKGSLQHH
 NLLVCHVTDF YPGSIQVRWF LNGQEETAGI VSTNLIRNGD WTFQILVMLE
 MTPQQGD*    
>DL;IPD:MHC04221
IPD:MHC04221 Aona-DPB1*03 157 bases
 RLYECYAFNG TQRLLDRLFY NREEFVRFDS DLGEYLAVTE LGRPDAKYWN
 SDKDILEGMR AEVERVCRHN YELVEPLNRK RQVQPKVNVS PSKKGSLQHH
 NLLVCHVTDF YPGSIQVRWF LNGQEETAGI VSTNLIRNGD WTFQILVMLE
 MTPQQGD*    
