>DL;IPD:MHC04219
IPD:MHC04219 Aona-DPB1*01 473 bases
 AGCGATTGTA TGAATGCTAC GCGTTTAACG GGACACAGCG CCTCCTGGAC
 AGATTGTTCT ACAACCGGGA GGAGTTCGTG CGCTTCGACA GCGACCTGGG
 GGAGTTCCGG TCGGTGACGG AGCTGGGACG GCCCGATGCA AAGTACTGGA
 ACAGCGATAA GGACATCCTG GAGGGGATGC GGGCCGAGGT GGAGAGGGTG
 TGCAGACACA ACTACGAATT GGTGGAGCCA CTCATCCGGA AGCGCCAAGT
 CCAGCCTAAG GTGAACGTCT CCCCATCCAA GAAGGGGTCC TTGCAGCACC
 ACAACCTACT TGTCTGCCAC GTGACAGATT TCTACCCAGG CAGCATTCAA
 GTCCGCTGGT TCCTGAATGG ACAGGAGGAA ACAGCTGGGA TCGTGTCCAC
 CAACCTGATC CGTAACGGAG ACTGGACCTT CCAGATCCTG GTGATGCTAG
 AAATGACCCC CCAGCAGGGA GAC*  
>DL;IPD:MHC04220
IPD:MHC04220 Aona-DPB1*02 473 bases
 AGCGATTGTA TGAATGCTAC GCGTTTAACG GGACACAGCG CCTCCTGGAC
 AGATTGTTCT ACAACCGGGA GGAGTTCGTG CGCTTCGACA GCGACCTGGG
 GGAGTACCTG GCGGTGACGG AGCTGGGACG GCCCGATGCA AAGTACTGGA
 ACAGCGATAA GGACATCCTG GAGGGGATGC GGGCCGAGGT GGAGAGGGTG
 TGCAGACACA ACTACGAATT GGTGGAGCCA CTCATCCGGA AGCGCCAAGT
 CCAGCCTAAG GTGAACGTCT CCCCATCCAA GAAGGGGTCC TTGCAGCACC
 ACAACCTACT TGTCTGCCAC GTGACAGATT TCTACCCAGG CAGCATTCAA
 GTCCGCTGGT TCCTGAATGG ACAGGAGGAA ACAGCTGGGA TCGTGTCCAC
 CAACCTGATC CGTAATGGAG ACTGGACCTT CCAGATCCTG GTGATGCTAG
 AAATGACCCC CCAGCAGGGA GAC*  
>DL;IPD:MHC04221
IPD:MHC04221 Aona-DPB1*03 473 bases
 AGCGATTGTA TGAATGCTAC GCGTTTAACG GGACACAGCG CCTCCTGGAC
 AGATTGTTCT ACAACCGGGA GGAGTTCGTG CGCTTCGACA GCGACCTGGG
 GGAGTACCTG GCGGTGACGG AGCTGGGACG GCCCGATGCA AAGTACTGGA
 ACAGCGATAA GGACATCCTG GAGGGGATGC GGGCCGAGGT GGAGAGGGTG
 TGCAGACACA ACTACGAATT GGTGGAGCCA CTCAACCGGA AGCGCCAAGT
 CCAGCCTAAG GTGAACGTCT CCCCATCCAA GAAGGGGTCC TTGCAGCACC
 ACAACCTACT TGTCTGCCAC GTGACAGATT TCTACCCAGG CAGCATTCAA
 GTCCGCTGGT TCCTGAATGG ACAGGAGGAA ACAGCTGGGA TCGTGTCCAC
 CAACCTGATC CGTAATGGAG ACTGGACCTT CCAGATCCTG GTGATGCTAG
 AAATGACCCC CCAGCAGGGA GAC*  
