>DL;IPD:MHC00001
IPD:MHC00001 Aona-DQA1*27:01 226 bases
 CTGACCATGT TGCCGCTTAC GGTATAAACT TGTACCAGTC TTATGGTCTC
 TCTGGCCAGT ACACCCACGA ATTTGATGGA GATGAGGAGT TCTACGTGGA
 CCTGGGAAGA AAGGAGACTG TCTGGCGATT GCCTGTGTTC AGCAAATTTG
 CAGGTTTTGA CCCTCAGGGT GCACTGACAA ACATCGCTGC GGGAAAACAC
 AACTTGGACA TCCTGATTAA ACGCTC*  
>DL;IPD:MHC00002
IPD:MHC00002 Aona-DQA1*27:02 226 bases
 CTGACCATGT TGCCGCTTAC GGTATAAACT TGTACCAGTC TTATGGTCTC
 TCTGGCCAGT ACACCCACGA ATTTGATGGA GATGAGGAGT TCTACATGGA
 CCTGGAAAGA AAGGAGACTG TCTGGCGATT GCCTGTGTTC AGCAAATTTG
 CAGGTTTTGA CCCTCAGGGT GCACTGACAA ACATCGCTGC GGGAAAACAC
 AACTTGGACA TCCTGATTAA ACGCTC*  
>DL;IPD:MHC00003
IPD:MHC00003 Aona-DQA1*27:03 226 bases
 CTGACCACGT TGCCGCTTAT GGTATAACCT TATACCAGTC TTATGGTCCC
 TCTGGCCAGT ACACCCATGA ATTTGATGGA GATGAGGAGT TCTACGTGGA
 CCTGGGAAGA AAGGAGACTG TCTGGCGATT GCCTGTGTTC AGCAAATTTA
 CAAGTTTTGA CCCACAGGGT GCACTGACAG AAACCGCTAC GGGAAAATAC
 AACTTGGACA TCCTGATTAA ACAGTC*  
>DL;IPD:MHC00004
IPD:MHC00004 Aona-DQA1*27:04 226 bases
 CTGACCACGT TGCCGCTTAC GGTATAAACT TGTACCAGTC TTATGGTCCC
 TCTGGCCAGT ACACCCACGA ATTTGATGGA GATGAAGAGT TCTACGTGGA
 CCTAGGGAAA AAGGAGACTG TCTGGCGATT GCCTGTGTTC AGCACATTTA
 CAAGTTTTGA CCCACAGATT GCACTGACAA ACATCGCTAC GGGAAAATAC
 AACTTGGACA TCCTGATTAA ACGCTC*  
>DL;IPD:MHC00005
IPD:MHC00005 Aona-DQA1*27:05 226 bases
 CTGACCATGT TGCCGCTTAT GGTATAAACT TGTACCAGTC TTATGGTCTC
 TCTGGCCAGT ACACCCATGA ATTTGATGGA GATGAGCAGT TCTACGTGGA
 CCTGGGAAGA AAGGAGACTG TCTGGCGATT GCCTGTGTTC AGCAAATTTG
 CAGGTTTTGA CCCTCAGGGT GCACTGACAA ACATCGCTAC GGGAAAATAC
 ACCTTGGACA TCCTGATTAA ACGCTC*  
