>DL;IPD:MHC01522
IPD:MHC01522 Aoni-DRB*W13:01 255 bases
 CGTTTCTTGG AGCAGTTTAA GCCTGAATGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCGG TTCCTGGACA GATACTTCTA TAACCAGGAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCCG AGTACTTTAA CAGCCTGAAG GACTTCATTG AGGAGACGCG
 GGCCGCGGTG GACACCTACT GCAGACACAA CTACGGGGTT GTTGAGAGCT
 TCACA*    
>DL;IPD:MHC01523
IPD:MHC01523 Aoni-DRB*W13:02 255 bases
 CGTTTCTTGG AGCAGTTTAA GCCTGAATGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCGG TTCCTGGACA GATACTTCTA TAACCAGGAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCCG AGCACTTTAA CAGCCTGAAG GACTTCATGG AGGAGACGCG
 GGCCGCGGTG GACACCTACT GCAGACACAA CTACGGGGTT GTGGAGAGCT
 TCACA*    
>DL;IPD:MHC01524
IPD:MHC01524 Aoni-DRB*W13:03 267 bases
 CGTTTCTTGG AGCAGTTTAA GCCTGAATGT CATCTCTTCA ACGGGACGGA
 GCGGGTGCGG TTCCTGGACA GATACTTCTA TAACCAGGAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCCG AGTACTTTAA CAGCCTGAAG GACTTCATGG AGGAGACGCG
 GGCCGCGGTG GACACCTACT GCAGACACAA CTACGGGGTT GTTGAGAGCT
 TCACAGTGCA GCGGAGA*   
>DL;IPD:MHC01525
IPD:MHC01525 Aoni-DRB*W13:04 255 bases
 CGTTTCTTGG AGCAGTTTAA GCCTGAATGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCGG TTCCTGGACA GATACTTCTA TAACCAGGAG GAGTACGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCCG AGTACTTTAA CAGCCTGAAG GACTTCATGG AGGAGACGCG
 GGCCGCGGTG GACACCTACT GCAGACACAA CTACGGGGTT GTTGAGAGCT
 TCACA*    
>DL;IPD:MHC01526
IPD:MHC01526 Aoni-DRB*W13:05 255 bases
 CGTTTCTTGG AGCAGTTTAA GCCTGAATGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCGG TTCCTGGACA GATACTTCTA TAACCAGGAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGAAGCAG AGTACTTTAA CAGCCTGAAG GACTTCATGG AGGAGACGCG
 GGCCGCGATG GACACCTACT GCAGACACAA CTACGGGGTT GCTGAGAGCT
 TCACA*    
>DL;IPD:MHC01527
IPD:MHC01527 Aoni-DRB*W13:06 255 bases
 CGTTTCTCGG AGCAGTTTAA GCCTGAATGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCGG TTCCTGGACA GATACTTCTA TAACCAGGAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCCG AGTACTGGAA CAGCCTGAAG GACTTCATGG AGGAGACGCG
 GGCCGCGGTG GACACCTACT GCAGACACAA CTACGGGGTT GTTGAGAGCT
 TCACA*    
>DL;IPD:MHC01528
IPD:MHC01528 Aoni-DRB*W13:07 267 bases
 CGTTTCTTGG AGCAGTTTAA GCCTGAATGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCGG TTCCTGGACA GATACTTCTA TAACCAGGAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCCG AGTACTTTAA CAGCCTGAAG GACTTCATGG AGGAGACGCG
 GGCCGCGGTG GACACCTACT GCAGACACAA CTACGGGGTT GGTGAGAGCT
 TCACAGTGCA GCGGAGA*   
>DL;IPD:MHC01529
IPD:MHC01529 Aoni-DRB*W13:08 267 bases
 CGTTTCTTGG AGCAGTTTAA GCCTGAATGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCGG TTCCTGGACA GATACTTCTA TAACCAGGAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCCG AGTACTTTAA CAGCCTGAAG GACTTCATGG AGGAGACGCG
 GGCCGCGGTG GACACCTACT GCAGACACGA CTACGGGGTT GTTGAGAGCT
 TCACAGTGCA GTGGAGA*   
>DL;IPD:MHC01530
IPD:MHC01530 Aoni-DRB*W13:09 267 bases
 CGTTTCTTGG AGCAGTTTAA GCCTGAATGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCGG TTCCTGGACA GATACTTCTA TAACCAGGAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCCG AGTACTGGAA CAGCCTGAAG GACTTCATGG AGGAGACGCG
 GGCCGCGGTG GACACCTACT GCAGACACAA CTACGGGGTT GTTGAGAGCT
 TCACAGTGCA GCGGAGA*   
>DL;IPD:MHC01531
IPD:MHC01531 Aoni-DRB*W18:01 255 bases
 CGTTTCTTGG AGCAGGTTAA GTCTGAGTGT TATTTCTTCA ACGGGACGGA
 GCGGGTGCAG TTCCTGGAAA GATACTTTCA TAACCAGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGATGCAA AGTACTGGAA CGGTCAGCAG GACATCCTGG AGCTGAAGCG
 GGGCCAGGTA GACAACTACT GCAGACACAA CTACGGGGTT GGTGAGAGCT
 TCACA*    
>DL;IPD:MHC01532
IPD:MHC01532 Aoni-DRB*W29:01 255 bases
 CGTTTCTTGG AGCAGACTAA GAGTGAGTGT CATTTCCTCA ACGGGACGGA
 GCGGGTGCGG CTCCTGCAAA GATACTTCTA TAACCAGGAG GAGTATGCGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCCG AGTACTGGAA CAGCCTGAAG GAACGCCTGG AGTATCTGCG
 GGCCGCGGTG GACACCTACT GCAGACACAA CTACGGGGTT GGTGAGAGCT
 TCACA*    
>DL;IPD:MHC01533
IPD:MHC01533 Aoni-DRB*W29:02 255 bases
 CGTTTCTTGG AGCAGACTAA GAGTGAGTGT CATTTCCTCA ACGGGACGGA
 GCGGGTGCGG CTCCTGCAAA GATACTTCTA TAACCAGGAG GAGTATGTGC
 GCTTCGTCTG CGACGTGGGG GAGTTCCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCCG AGTACTGGAA CAGCCTGAAG GAACGCCTGG AGTATCTGCG
 GGCCGCGGTG GACACCTGCT GCAGACACAA CTACGGGGTT GTTGAGAGCT
 TCACA*    
>DL;IPD:MHC01534
IPD:MHC01534 Aoni-DRB*W29:03 255 bases
 CGTTTCTTGG AGCAGACTAA GAGTGAGTGT CATTTCCTCA ACGGGACGGA
 GCGGGTGCGG CTCCTGCAAA GATACTTCTA TAACCAGGAG GAGTATGTGC
 GGTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCCG AGTACTGGAA CAGCCTGAAG GAACGCCTGG AGTATCTGCG
 GGCCGCGGTG GACACCTGCT GCAGACACAA CTACGGGGTT GTTGAGAGCT
 TCACA*    
>DL;IPD:MHC01535
IPD:MHC01535 Aoni-DRB*W29:04:01 267 bases
 CGTTTCTTGG AGCAGACTAA GAGTGAGTGT CATTTCCTCA ACGGGACGGA
 GCGGGTGCGG CTCCTGCAAA GATACTTCTA TAACCAGGAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCCG AGTACTGGAA CAGCCTGAAG GAACGCCTGG AGTATCTGCG
 GGCCGCGGTG GACACCTGCT GCAGACACAA CTACGGGGTT GTTGAGAGCT
 TCACAGTGCA GCGGAGA*   
>DL;IPD:MHC01536
IPD:MHC01536 Aoni-DRB*W29:04:02 267 bases
 CGTTTCTTGG AGCAGACTAA GAGTGAGTGT CATTTCCTCA ACGGGACGGA
 GCGGGTGCGG CTCCTGCAAA GATACTTCTA TAACCAGGAA GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCCG AGTACTGGAA CAGCCTGAAG GAACGCCTGG AGTATCTGCG
 GGCCGCGGTG GACACCTGCT GCAGACACAA CTACGGGGTT GTTGAGAGCT
 TCACAGTGCA GCGGAGA*   
>DL;IPD:MHC01537
IPD:MHC01537 Aoni-DRB*W38:01 255 bases
 CGTTTCTTGG AGCAGGCTAA GTATGAGTGT CATTTCCTCA ACGGGACGGA
 GCGGGTGCGG TTCCTGGAAA GACACATCCA TAACCAGGAG GAGTATGCGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CGGACCGCAG AGTACTGGAA CAGCCAGAAG GACTTCCTGG AGGACAGGCG
 GGCCCAGGTG GACACCGTGT GCAGACACAA CTACGGGGTT GTTGAGAGCT
 TCACA*    
>DL;IPD:MHC01538
IPD:MHC01538 Aoni-DRB*W42:01 255 bases
 CGTTTCTTGG AACAGGTTAA GGATGAGTGT CATTTCCTCA ACGGGACGGA
 GCGGGTGCGG TTCCTGGAAA GATACTTCTA TAACCAGGAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCCG AGTACTGGAA CAGCCTGAAG GAACGCCTGG AGTATCTGCG
 GGCCGCGGTG GACACCTACT GTAAACACAA CTACGGGGTT GTTGAGAGCT
 TCACA*    
>DL;IPD:MHC01539
IPD:MHC01539 Aoni-DRB*W43:01 255 bases
 CGTTTCTTGA AGCAGGTTAA GTGTGAGTGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCAG CTCCTGGACA GACACTTTTA TAACCAGGAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CGGACCGCAG AGTACTGGAA CAGCCAGAAG GACTTCCTGG AGAACAGGCG
 GGCCGCGGTG GACACCTACT GTAAACACAA CTACGGGGTT GGTGAGAGCT
 TCACA*    
>DL;IPD:MHC01540
IPD:MHC01540 Aoni-DRB*W43:02 255 bases
 CGTTTCTTGA AGCAGGTTAA GTGTGAGTGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCAG CTCCTGGACA GACACTTTTA TAACCAGGAG GAGTATGTGC
 GCTCCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CGGACCGCAG AGTACTGGAA CAGCCAGAAG GACTTCCTGG AGAACAGGCG
 GGCCGCGGTG GACACCTACT GTAAACACAA CTACGGGGTT GGTGAGAGCT
 TCACA*    
>DL;IPD:MHC01541
IPD:MHC01541 Aoni-DRB*W43:03 255 bases
 CGTTTCTTGA AGCAGGTTAA GTGTGAGTGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCAG CTCCTGGACA GACACTTTTA TAACCAGGAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CGGACCGCAG AGTACTGGAA CAGCCAGAAG GACTTCCTGG AGAACAGGCG
 GGCCGCGGTG GACACCTACT GCAAACACAA CTACGGGGTT GGGGAGAGCC
 TCACA*    
>DL;IPD:MHC01542
IPD:MHC01542 Aoni-DRB*W43:04 255 bases
 CGTTTCTTGA AGCAGGTTAA GTGTGAGTGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCAG CTCCTGGACA GACACTTTTA TAACCAGGAG GAGTATGTGC
 GCTTCGACAG CGACGAGGGG GAGTACCGGG CGGAGACGGA GCTGGGGCGG
 CGGACCGCAG AGTACTGGAA CAGCCAGAAG GACTACGTGG AGAACAGGCG
 GGCCGCGGAG GACACCTACC GTAAACACAA CTACGGGGTT GTTGAAGACT
 TCACA*    
>DL;IPD:MHC01543
IPD:MHC01543 Aoni-DRB*W43:05 255 bases
 CGTTTCTTGA AGCAGGTTAA GTGTGAGTGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCAG CTCCTGGACA GACACTTTTA TAACCAGGAG GAGGTACGGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CAGGACCGCA AGTACTGGAA CAGCCAGAAG GACTTCCTGG AGAACAGGCG
 GGCCGCGGTG GACACCTACT GCAAACACAA CTACGGGGTT GGTGAGAGCT
 CCACA*    
>DL;IPD:MHC01544
IPD:MHC01544 Aoni-DRB*W44:01 255 bases
 CGTTTCTTGG AGCAGGCTAA GTCTGAGTGT TATTTCTTCA ACGGGACGGA
 GCGGGTGCGG TACCTGGACA GATACTTCTA TAACCAGAAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CTGTGACGGA GCTGGGGCGG
 CGGACCGCAG AGTACTGGAA CAGCCAGAAG GACTTCCTGG AGGACAGGCG
 GGCCGCGGTG GACACCTACT GTAAACACAA ATACGGGGTT GGTGAGAGCT
 TCACA*    
>DL;IPD:MHC01545
IPD:MHC01545 Aoni-DRB*W47:01 255 bases
 CGTTTCTTGG AGCAGGTTAA GCATGAGTGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCAG TTCCTGGACA GATACTTTTA TAACCAGGAG GAGTATGCGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCGG AGTACTGGAA CAGCCAGAAG GACATCCTGG AGGACAGGCG
 GGCCCAGGTG GACAGCTACT GCAGACACAA CTACGGGGTT GGTGAGAGCT
 TCACA*    
>DL;IPD:MHC00056
IPD:MHC00056 Aoni-DRB1*03:01 268 bases
 CGTTTCTTGT TCCAGACTAC GTCTGAGTGT TATTTCTTCA ACGGGACGGA
 GCGGGTGCGG TACCTGGACA GATACTTTTA TAACCAGGAG GAATATGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCCG AGTACTGGAA CAGCCAGAAG GACTACGTGG AGCGGAAGCG
 GGGCCAGGTG GACAACTACT GCAGACACAA CTACGGGGTT GGTGAGAGCT
 TCACAGTGCA GCGGCGAA*   
>DL;IPD:MHC00057
IPD:MHC00057 Aoni-DRB1*03:02 267 bases
 CGTTTCTTGT TCCAGACTAC GTCTGAGTGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCGG TACCTGGACA GATACCTTTA TAACCAGAAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCCG AGTACTGGAA CAGCCAGAAG GACTACGTGG AGCGGAAGCG
 GGGCCGGGTG GACAACTACT GCAGACACAA CTACGGGGTT GGTGAGAGCT
 TCACAGTGCA GCGGCGA*   
>DL;IPD:MHC01516
IPD:MHC01516 Aoni-DRB1*03:03 255 bases
 CGTTTCTTGT TCCAGACTAC GTCTGAGTGT TATTTCTTCA ACGGGACGGA
 GCGGGTGCGG TACCTGGACA GATACTTTTA TAACCAGGAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGAGG
 CCTGACGCGG AGTACTGGAA CAGCCAGAAG GACTACGTGG AGCGGAAGCG
 GGGCCGGGTG GACAACTACT GCAGACACAA CTACGGGGTT GGTGAGAGCT
 TCACA*    
>DL;IPD:MHC01517
IPD:MHC01517 Aoni-DRB1*03:04 255 bases
 CGTTTCTTGT TCCAGACTAC GTCTGAGTGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCGG TACCTGGACA GATACTTCTA TAACCAGAAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCCG AGTACTGGAA CAGCCAGAAG GACTACGTGG AGCAGAAGCG
 GGGCCGGGTG GACAACTACT GCAGACACAA CTACGGGGTT GGTGAGAGCT
 TCACA*    
>DL;IPD:MHC01518
IPD:MHC01518 Aoni-DRB1*03:05 255 bases
 CGTTTCTTGT TCCAGACTAC GTCTGAGTGT TATTTCTTCA ACGGGACGGA
 GCGGGTGCGG TACCTGGACA GATACTTCTA TAACCAGGAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCCG AGTACTTTAA CAGCCTGAAG GACTTCATGG AGGAGACGCG
 GGCCGCGGTG GACACCTACT GCAGACACAA CTACGGGGTT GTTGAGAGCT
 TCACA*    
>DL;IPD:MHC01519
IPD:MHC01519 Aoni-DRB1*03:06 267 bases
 CGTTTCTTGT TCCAGACTAC GTCTGAGTGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCGG TACCTGGACA GATACTTTTA TAACCAGGAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCCG AGTACTGGAA CAGCCAGAAG GACTACGTGG AGCAGAAGCG
 GGGCCGGGTG GACAACTACT GCAGACACAA CTACGGGGTT GGTGAGAGCT
 TCACAGTGCA GCGGAGA*   
>DL;IPD:MHC01520
IPD:MHC01520 Aoni-DRB1*03:07 267 bases
 CGTTTCTTGT TCCAGACTAC GTCTGAGTGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCGG CACCTGGACA GATACTTTTA TAACCAGGAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCCG AGTACTGGAA CAGCCAGAAG GACTACGTGG AGCAGAAGCG
 GGGCCGGGTG GACAACTACT GCAGACACAA CTACGGGGTT GGTGAGAGCT
 TCACAGTGCA GCGGAGA*   
>DL;IPD:MHC01521
IPD:MHC01521 Aoni-DRB3*06:01 255 bases
 CGTTTCTTGG AGCTGGTTAA GCATGAGTGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCGG TACCTGGACA GATACCTTTA TAACCAGAAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCCG AGTACTGGAA CAGCCAGAAG GACTACGTGG AGCAGAAGCG
 GGGCCAGGTG GACAACTACT GCAGACACAA CTACGGGGTT GTTGAGAGCT
 TCACA*    
