>DL;IPD:MHC00070
IPD:MHC00070 Aotr-E*03:01 144 bases
 ARDTAQSFRV NLRTLLRYYN QSEAGSHTLQ WMHGCDVGPD GRLFRGYEQF
 AYDGTDYLAL NEDLRSWTAA DTAAQISQRK AEEACEAEHQ RAYLEGKCVE
 WLRRYLENGK ETLQRADPPK TYVSHHPLSD HEATLRCWAL GFYP*
