>DL;IPD:MHC00071
IPD:MHC00071 Aotr-G*03:01 331 bases
 LLLLLSGALA LTQTCAGSHS MRYFSIAVSR PGAREPRYME VGYVDDTQFV
 RFDSDAAIPR MEPRAPWVEQ EGPEYWDGQT RKAKANAQTD RVNLRIALGY
 YNQSEVGSHT FQRMYGCDLG PDGRLLRGYY QLAYDGKDYM VLNEDLRSWT
 AADVAAQITK RKWEAANEVD QWRAYLEGTC VEWLRRHLEN GKETLQRAEP
 PKTHVSHHPS SDNEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDMELVETR
 PAGDGNFQKW AAVVVPSGEE QRYTCHVQHE GLPEPLTLRW EPSSQPTIPI
 VGIVAGLAVL GAVVTGAVVA AVMWRKKSSD K* 
>DL;IPD:MHC00072
IPD:MHC00072 Aotr-G*05:01 331 bases
 LLLLLSGALF LTETRAGSHS MRYFYTSVSR PGRGEPPFIS VGYVDDTQFV
 RFDSDAANPR EEPRAPWMEK VGPEYWDRNT RIHKTTAQAD RVNLRTLPGY
 YNQSEAGSHT FQTMYGCDLG PDGRLLLGYD QSAYDGKDYI ALNEDLRSWT
 AADVAAQITQ RKWEAANVAE QMRAYLEGTC VEWLRRHLEN GKETLQRAEP
 PKTHVTHHPI SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDMELVETR
 PTGDGTFQKW AAVLVPSGEE QRYICHVQHE GLPEPLTLRW EPSSQPTIPI
 VGIVAGLAVL VAVVTGAVVA AVRWRKKSSD K* 
>DL;IPD:MHC00073
IPD:MHC00073 Aotr-G*05:02 330 bases
 LLLLFSGALF VTETWAGSHS MRYFDTSVSR PGRGEPRFFS VGYVDDTQFV
 RFDSDAAIPR DEPRAPWVEQ VGPEYWDRNT RIHKTTAQAD RVNLRTLPGY
 YNQSEAGSHT LQGMYGCDMG PDGRLLRGYR QYAYDGKDYL ALNEDLRSWT
 AADVAAQITK RKWEAANVAE QYRAYLEGTC VESLRRYLEN GKETLQRAEP
 PKTHMSHHPI SDNEATLRCW ALGFYPAEIT LTWQRDGEDQ AQDMELVETR
 PAGDGNFQKW AAVVVPSGEE QRYTCHVQHE GLPEPLTLRW EPSSQPTIPI
 VGIVAGLAVL GAVIIAVVAA VMWRKKSSDK * 
