>DL;IPD:MHC00074
IPD:MHC00074 Aotr-PS2 821 bases
 ACCCGGGCGG GCTCCCACTC CATGAGGTAT TTCCAGACCG GCGTGTCCCG
 GCCTGGCCGC GGGGAGCCCC GCTTCATCGA AGTCGGCTAC GTGGACGACA
 CGCAGATCAT GAGGCTCGAC AGCGACGCCG CGATTGCGAG GCTGGAGCCG
 CGGGCGCCGT GGGTGGAGCA GGAGGGGCCG GAGTATCGGG ACTGGAACGC
 ACGGAACGCC AAGGTCTCCG CACAGACTCA GCGAGTGAGC CTGCAGAACC
 AGAGCGCGGC GGGGTCTCAC ACCTACCAGG GGATGTGTGG CTGCGACCCG
 GGGCCAGACG GGCGCCTCCT CCGCGGATAT AACCAGTTCG CCGACGATGG
 CAAGGATTAC ATCGCCCTGA ACGAGGACTT GCGTTCCTGA ACCGCCGCGG
 ACGCAGCGCC TCACACCGCC CAGCGCAAGC GGGGGGCGGC CAATGAGGCG
 GAGCAACAGA GAGCCCACCT GGAAGGCAGG TGCGTGGAGT GGCTCTGCAG
 ATACCTGGAC AACGGGAAGG AGACGCTTCA GCGCGCGGAG CCCCCCAAGA
 CACAAGTGAC CCACCACCTC ATCTCCGACC ATGAGGCCAC CCTGAGGTGC
 TGGGCCCTTG GCTTCTACCC TGCGGAGATC ACACTGACCT GGCAGGGGGA
 TGGGGAGGAT CAGACCCAGG ACATGGAGCT CGTGGAGACC AGGCCGGCAG
 GGGACAGAAA CTTCCAGAAG TGGGCTGCTG TGGTGGTGCC TTCTGGAGAG
 GAGCAGAGAT ACACGTGCCA TGTGCAGCAT GAGGGGCTGC CAGAGACCCT
 CAGCCTGAGA TGGGAGCCGC C*  
