>DL;IPD:MHC00065
IPD:MHC00065 Aotr-DRB*W13:01 270 bases
 CACGTTTCTT GGAGCAGTTT AAGCCTGAAT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTT TATAACCAGG AGGAGTATGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGAAGC AGAGTACTTT AACAGCCTGA AGGACTTCAT GGAGGAGACG
 CGGGCCGCGG TGGACACCTA CTGTAAACAC AACTACGGGG TTTTTGAGAG
 CTTCACAGTG CAGCGGAGAG *  
>DL;IPD:MHC00067
IPD:MHC00067 Aotr-DRB*W18:01 270 bases
 CACGTTTCTT GGAGCAGGCT AAGTCTGAGT GTTATTTCTT CAACGGGACG
 GAGCGGGTGC AGTTCCTGGA AAGATACTTT TATAACCAGG AGGAGTATGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGATGC AAAGTACTGG AACGGTCAGC AGGACATCCT GGAGCTGAAG
 CGGGGCCAGG TAGACAACTA CTGCAGACAC AACTACGGGG TTTTTGAGAG
 CTTCACAGTG CAGCGGAGAG *  
>DL;IPD:MHC00068
IPD:MHC00068 Aotr-DRB*W29:01 249 bases
 TTGGAGCAGA CTAAGAGTGA GTGTCATTTC CTTAACGGGA CGGAGCGGGT
 GCGGCTCCTG CAAAGATACT TCTATAACCA GGAGGAGTTT GCGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCGAGTACT GGAACAGCCT GAAGGAACGC CTGGAGTATA TGCGGGCCGC
 GGTGGACACC TACTGCAGAC ACAACTACGG GGTTTTTGAG AGCTTCACA*
>DL;IPD:MHC00069
IPD:MHC00069 Aotr-DRB*W29:02 248 bases
 TTGGAGCAGA CTAAGTGTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTCCTG GACAGATACT TCTATAACCA GGAGGAGTTT GTGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCGAGTACT GGAACAGCCA GAAGGAATAC GTGGAGCATA TGCGGGCCCC
 GGTGGACACC TACTGCAGAC ACAACTACGG GTTTTTGAGA GCTTCACA*
>DL;IPD:MHC00059
IPD:MHC00059 Aotr-DRB1*03:01 270 bases
 CACGTTTCTT GTTCCAGACT ACGTCTGAGT GTTATTTCTT CAACGGGACG
 GAGCGGGTGC GGTACCTGGA CAGATACTTT TATAACCAGG AGGAGTATGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC CGAGTACTGG AACAGCCAGA AGGACTACGT GGAGCAGAAG
 CGGGGCCGGG TGGACAACTA CTGCAGACAC AACTACGGGG TTGGTGAGAG
 CTTCACAGTG CAGCGGAGAG *  
>DL;IPD:MHC00060
IPD:MHC00060 Aotr-DRB1*03:02 270 bases
 CACGTTTCTT GTTCCAGACT ACGTCTGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTACCTGGA CAGATACTTT TATAACCAGG AGGAGTATGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC CGAGTACTGG AACAGCCAGA AGGACTACGT GGAGCGGAAG
 CGGGGCCAGG TGGACAACTA CTGCAGACAC AACTACGGGG TTGGTGAGAG
 CTTCACAGTG CAGCGGAGAG *  
>DL;IPD:MHC00061
IPD:MHC00061 Aotr-DRB1*03:03 249 bases
 TTGTTCCAGA CTACGTCTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTACCTG GACAGATACT TTTATAACCA GGAGGAGTAT GTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCGAGTACT GGAACAGCCA GAAGGAATAC GTGGAGCAGA AGCGGGCCCG
 GGTGGACAAC TACTGCAGAC ACAACTACGG GGTTGGTGAG AGCTTCACA*
>DL;IPD:MHC00062
IPD:MHC00062 Aotr-DRB1*03:04 249 bases
 TTGTTCCAGA CTACGTCTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTCCTG GACAGATACT TCTATAACCA GGAGGAGTAT GTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCGGAGC
 GCAGAGTACT GGAACAGCCA GAAGGACTTC CTGGAGGAGA GGCGGGCCTT
 GGTGGACACC TACTGTAGAT ACAACTACGG GGTTGCTGAG AGCTTCACA*
>DL;IPD:MHC00066
IPD:MHC00066 Aotr-DRB1*03:05 270 bases
 CACGTTTCTT GTTCCAGACT ACGTCTGAGT GTTATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTT TATAACCAGG AGGAGTATGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC CGAGTACTGG AACAGCCAGA AGGACTTCCT GGAGGACAGG
 CGGGCCGCAG TGGACACCTA CTGTAGATAC AACTACGGGG TTGGTGAGAG
 CTTCACAGTG CAGCGGAGAG *  
>DL;IPD:MHC00063
IPD:MHC00063 Aotr-DRB3*06:01 270 bases
 CACGTTTCTT GGAGCTGGTT AAGCATGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTACCTGGA CAGATACATC CATAACCAGG AGGAGGTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC CGAGTACTGG AACAGCCAGA AGGACTACGT GGAGCAGAAG
 CGGGGCCGGG TGGACACCTA CTGCAGACAC AACTACGGGG TTGTTGAGAG
 CTTCACAGTG CAGCGGAGAG *  
>DL;IPD:MHC00064
IPD:MHC00064 Aotr-DRB3*06:02 248 bases
 TTGGAGCTGG TTAAGCATGA GTGTCATTTC TTTAACGGGA CGGAGCGGGT
 GCGGTACCTG GACAGATACA TCCATAACCA GGAGGAGGTC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCGAGTACT GGAACAGCCA GAAGGAATAC GTGGAGCAGA AGCGGGGCCA
 GGTGGACAAC TACTGCAGAC ACAACTACGG GTTTTTGAGA GCTTCACA*
