>DL;IPD:MHC00071
IPD:MHC00071 Aotr-G*03:01 993 bases
 CTCCTCCTGC TGCTCTCGGG GGCCCTGGCC TTGACCCAGA CCTGCGCGGG
 CTCCCACTCC ATGAGGTATT TCAGCATCGC TGTGTCCCGG CCCGGCGCGC
 GGGAGCCCCG GTACATGGAA GTCGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCCGC GATTCCGAGG ATGGAGCCGC GGGCGCCGTG
 GGTGGAGCAG GAGGGACCGG AGTATTGGGA CGGGCAGACA CGGAAAGCGA
 AGGCCAATGC ACAGACTGAC CGAGTGAACC TGCGGATCGC GCTCGGCTAC
 TACAACCAGA GCGAGGTCGG GTCTCACACC TTCCAGAGGA TGTATGGCTG
 CGACTTGGGG CCGGACGGGC GCCTCCTCCG CGGGTATTAC CAGCTCGCCT
 ACGACGGCAA GGACTACATG GTCCTGAACG AGGACCTGCG CTCTTGGACC
 GCTGCGGACG TGGCGGCTCA GATCACCAAG CGCAAGTGGG AGGCGGCCAA
 TGAGGTGGAC CAGTGGAGAG CCTACCTGGA GGGCACGTGC GTGGAGTGGC
 TCCGCAGACA CCTGGAGAAT GGGAAGGAGA CGCTGCAGCG CGCGGAGCCC
 CCCAAGACAC ACGTGTCCCA TCACCCCAGC TCTGACAATG AGGCCACCCT
 GAGGTGCTGG GCCCTTGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG GGAGGACCAG ACCCAGGACA TGGAGCTTGT AGAGACCAGG
 CCCGCAGGGG ATGGAAACTT CCAGAAGTGG GCGGCTGTGG TGGTGCCTTC
 TGGAGAGGAG CAGAGATACA CATGCCATGT GCAGCACGAG GGGCTGCCCG
 AGCCCCTCAC CCTGAGATGG GAGCCGTCTT CCCAGCCCAC CATCCCCATC
 GTGGGGATCG TTGCTGGCCT GGCTGTCCTT GGAGCTGTAG TCACTGGAGC
 TGTGGTCGCT GCTGTGATGT GGAGGAAGAA GAGCTCAGAT AAA*
>DL;IPD:MHC00072
IPD:MHC00072 Aotr-G*05:01 993 bases
 CTCCTGTTGC TGCTCTCGGG GGCCCTGTTC CTGACCGAGA CCCGGGCGGG
 CTCCCACTCC ATGAGGTATT TCTACACCTC CGTGTCCCGG CCCGGCCGCG
 GGGAGCCCCC GTTCATCTCC GTGGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCTGC GAATCCGAGA GAGGAGCCGA GGGCGCCGTG
 GATGGAGAAG GTGGGGCCGG AGTATTGGGA CCGGAACACA CGGATCCACA
 AGACCACCGC ACAGGCTGAC CGAGTGAACC TGCGGACCCT GCCCGGCTAC
 TACAACCAGA GCGAGGCCGG GTCTCACACC TTCCAGACAA TGTATGGCTG
 CGACCTGGGG CCGGACGGGC GCCTCCTCCT CGGGTATGAC CAGTCCGCCT
 ACGACGGCAA GGACTACATC GCCCTGAACG AGGACCTGCG CTCCTGGACC
 GCCGCGGACG TGGCGGCTCA GATCACCCAG CGCAAGTGGG AGGCGGCCAA
 TGTGGCGGAG CAAATGAGAG CCTACCTGGA GGGCACGTGC GTGGAGTGGC
 TCCGCAGACA CCTGGAGAAT GGGAAGGAGA CGCTGCAGCG CGCAGAGCCC
 CCCAAGACAC ACGTGACCCA CCACCCCATC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCTCTGGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG GGAGGACCAG ACCCAGGATA TGGAGCTCGT AGAGACCAGG
 CCTACGGGGG ATGGAACCTT CCAGAAGTGG GCAGCTGTGT TGGTGCCTTC
 TGGAGAGGAG CAGAGATACA TATGCCATGT GCAGCACGAG GGGCTGCCTG
 AGCCCCTCAC CCTGAGATGG GAGCCGTCTT CCCAGCCCAC CATCCCCATC
 GTGGGCATCG TTGCTGGCCT GGCTGTCCTT GTTGCTGTAG TCACTGGAGC
 TGTGGTCGCT GCTGTGAGGT GGAGGAAGAA GAGCTCAGAT AAA*
>DL;IPD:MHC00073
IPD:MHC00073 Aotr-G*05:02 990 bases
 CTCCTCCTGC TGTTCTCGGG GGCCCTGTTC GTGACCGAGA CCTGGGCGGG
 CTCCCACTCC ATGAGGTATT TCGACACCTC CGTGTCCCGG CCCGGCCGCG
 GGGAGCCCCG CTTCTTCTCC GTGGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCCGC GATTCCGAGA GACGAGCCGC GGGCGCCGTG
 GGTGGAGCAG GTGGGGCCGG AGTATTGGGA CCGGAACACA CGGATCCACA
 AGACCACCGC ACAGGCTGAC CGAGTGAACC TGCGGACCCT GCCCGGCTAC
 TACAACCAGA GCGAGGCCGG GTCTCACACG CTCCAGGGGA TGTATGGCTG
 CGACATGGGG CCGGACGGGC GCCTTCTCCG CGGGTATCGC CAGTACGCCT
 ACGACGGCAA GGACTACCTC GCCCTGAACG AGGACCTGCG CTCCTGGACG
 GCCGCGGACG TGGCGGCTCA GATCACCAAG CGCAAGTGGG AGGCGGCCAA
 TGTGGCGGAG CAATACAGAG CCTACCTGGA GGGCACGTGC GTGGAGTCAC
 TCCGCAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CGCGGAGCCC
 CCCAAGACAC ACATGTCCCA TCACCCCATC TCTGACAATG AGGCCACCCT
 GAGGTGCTGG GCCCTTGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG GGAGGACCAG GCCCAGGACA TGGAGCTTGT GGAGACCAGG
 CCCGCAGGGG ATGGAAACTT CCAGAAGTGG GCGGCTGTGG TGGTGCCTTC
 TGGAGAGGAG CAGAGATACA CATGCCATGT GCAGCACGAG GGGCTGCCTG
 AGCCCCTCAC CCTGAGATGG GAGCCGTCTT CCCAGCCCAC CATCCCCATC
 GTGGGCATCG TTGCTGGCCT GGCTGTCCTT GGAGCTGTAA TCATTGCTGT
 GGTCGCTGCT GTGATGTGGA GGAAGAAGAG CTCAGATAAA *
