>DL;IPD:MHC01550
IPD:MHC01550 Aovo-DRB*W13:01:01 267 bases
 CGTTTCTTGG AGCAGTTTAA GCCTGAATGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCGG TTCCTGGACA GATACTTTTA TAACCAGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CGGACCGCAG AGTACTTTAA CAGCCTGAAG GACTTCATGG AGGAGACGCG
 GGCCGCGGTG GACACCTACT GTAAACACAA CTACGGGGTT GTTGAGAGCT
 TCACAGTACA GCGGAGA*   
>DL;IPD:MHC01551
IPD:MHC01551 Aovo-DRB*W13:01:02 267 bases
 CGTTTCTTGG AGCAGTTTAA GCCTGAATGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCGG TTCCTGGACA GATACTTTTA TAACCAGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CGGACCGCAG AGTACTTTAA CAGCCTGAAG GACTTCATGG AGGAGACGCG
 GGCCGCGGTG GACACCTACT GTAAACACAA CTACGGGGTT GTTGAGAGCT
 TCACAGTGCA GCGGAGA*   
>DL;IPD:MHC01552
IPD:MHC01552 Aovo-DRB*W13:02 267 bases
 CGTTTCTTGG AGCAGTTTAA GCCTGAATGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCGG TTCCTGGACA GATACTTTTA TAACCAGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CGGACCGCAG AGTACTTTAA CAGCCTGAAG GACTTCATGG AGGAGACGCG
 GGCCGCGGTG GACTCCTTCT GTAAACACAA CTACGGGGTT GTTGAGAGCT
 TCACAGTGCA GCGGAGA*   
>DL;IPD:MHC04082
IPD:MHC04082 Aovo-DRB*W13:03 255 bases
 CGTTTCTTGG AGCAGTTTAA GCCTGAATGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCGG TTCCTGGACA GATACTTCTA TAACCAGGAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCCG AGTACTTTAA CAGCCTGAAG GACTTCATGG AGGAGACGCG
 GGCCGCGGTG GACACCTACT GCAGACACAA CTACGGGGTT GTTGAGAGCT
 TCACA*    
>DL;IPD:MHC01553
IPD:MHC01553 Aovo-DRB*W29:01 267 bases
 CGTTTCTTGG AGCAGACTAA GAGTGAGTGT CATTTCCTCA ACGGGACGGA
 GCGGGTGCGG CTCCTGCAAA GATACTTCTA TAACCAGGAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCCG AGTACTGGAA CAGCCTGAAG GAACGCCTGG AGTATCTGCG
 GGCCGCGGTG GACACCTGCT GCAGACACAA CTACGGGGTT GTTGAGAGCT
 TCACAGTGCA GCGGAGA*   
>DL;IPD:MHC01554
IPD:MHC01554 Aovo-DRB*W43:01 267 bases
 CGTTTCTTGA AGCAGGTTAA GTGTGAGTGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCAG CTCCTGGACA GACACTTCTA TAACCAGGAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CGGACCGCAG AGTACTGGAA CAGCCAGAAG GACTTCCTGG AGAACAGGCG
 GGCCGCGGTG GACACCTACT GTAAACACAA CTACGGGGTT GGTGAGAGCT
 TCACAGTGCA GCGGAGA*   
>DL;IPD:MHC01555
IPD:MHC01555 Aovo-DRB*W47:01 255 bases
 CGTTTCTTGG AGCAGGTTAA GCATGAGTGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCGG TTCCTGGACA GATACTTTTA TAACCAGGAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCGG AGTACTGGAA CAGCCAGAAG GACTTAATGG AGGACAGGCG
 GGCCCAGGTG GACACCTACT GCAGACACAA CTACGGGGTT GGTGAGAGCT
 TCACA*    
>DL;IPD:MHC01556
IPD:MHC01556 Aovo-DRB*W47:02 267 bases
 CGTTTCTTGG AGCAGGTTAA GCATGAGTGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCAG TTCCTGGACA GATACTTTTA TAACCAGGGG GAGTATGCGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCGG AGTACTGGAA CAGCCAGAAG GACATCCTGG AGGACAGGCG
 GGCCCAGGTG GACAGCTACT GCAGACACAA CTACGGGGTT GGTGAGAGCT
 TCACAGAGCA GAGGAGA*   
>DL;IPD:MHC01546
IPD:MHC01546 Aovo-DRB1*03:01 267 bases
 CACGTTTCTT GTTCCAGACT ACGTCTGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTACCTGGA CAGATACTTC TATAACCAGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTACTGG AACAGCCAGA AGGACTACGT GGAGCGGAAG
 CGGGGCCAGG TGGACAACTA CTGCAGACAC AACTACGGGG TTGGTGAGAG
 CTTCACAGTG CAGCGGA*   
>DL;IPD:MHC01547
IPD:MHC01547 Aovo-DRB1*03:02 255 bases
 CGTTTCTTGT TCCAGACTAC GTCTGAGTGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCGG TACCTGGACA GATACTTCTA TAACCAGAAG GAGTATGTGC
 GCTTCGCCAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCCG AGTACTGGAA CAGCCAGAAG GACTACGTGG AGCAGAAGCG
 GGGCCGGGTG GACAACTACT GCAGACACAA CTACGGGGTT GGTGAGAGCT
 TCACA*    
>DL;IPD:MHC01548
IPD:MHC01548 Aovo-DRB1*03:03 267 bases
 CGTTTCTTGT TCCAGACTAC GTCTGAGTGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCGG TACCTGCACA GATACTTCTA TAACCAGAAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCCG AGTACTGGAA CAGCCAGAAG GACTACGTGG AGCAGAAGCG
 GGGCCGGGTG GACAACTACT GCAGACACAA CTACGGGGTT GGTGAGAGCT
 TCACAGTGCA GCGGAGA*   
>DL;IPD:MHC01549
IPD:MHC01549 Aovo-DRB1*03:04 267 bases
 CGTTTCTTGT TCCAGACTAC GTCTGAGTGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCGG TACCTGGACA GATACTTCTA TAACCAGAAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGCCG AGTACTGGAA CAGCCAGAAG GACTACGTGG AGCAGAAGCG
 GGGCCGGGTG GACAACTACT GCAGACACAA CTACGGGGTT GGTGAGAGCT
 TCACAGTGCA GCGGAGA*   
