>DL;IPD:MHC00080
IPD:MHC00080 Atbe-G*03:01 993 bases
 CTCCTCCTGC TGCTCTCGGG GGCCCTGGCC CTGACCCAGA CCCGGGCGGG
 CTCCCACTCC ATGAGGTATT TCGACACCGC CGTGTCCCGG CCCGGCCGCG
 GGGAGCCCCA CTTCTTCGCC GTGGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCCGC GAGTCCGAGG ATGGAGCCGC GGGCGCGGTG
 GATGGAGCAG GAGGGGCCGG AGTATTGGGA GGAGGAGACA CGGAGATCCA
 AGGCCCAGGC ACAGACTCAC CGAGTGAGCC TGCGGAACCT GCGCGGCTAC
 TACAACCAGA GCGAGGCCGG GTCTCACACG CTCCAGAGGA TGTCTGGCTG
 CGACCTGGGG CCGGACGGGC GCCTCCTCCG CGGGTATTAC CAGTACGCCT
 ACGACGGCAA GGACTACATC GCCCTGAACG AGGACCTGCG CTCCTGGACC
 GCCGCGGACG TGGCAGCTCA GATCACCCAG CGCAAGTGGG GGTCGGGCAA
 TGAGGCGGAG CAATCGAAAG CCTACCTGGA GGGCGAGTGC GTGGAGTCGC
 TCCGCAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CGCGGAGCCC
 CCTAAGACAC ACGTGACCCA TCACCCCGTC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGT GGAGATCACA CTGACCTGGC
 AGCGGGATGG GGAGGACCAG ACCCAGGACA CGGAGCTCGT AGAGACCAGG
 CCCGCAGGGG ATGGAACCTT CCAGAAGTGG GCGGCTGTGG TGGTGCCTTC
 TGGAGAGGAG CAGAGATACA CCTGCCATGT GCAGCACGAT GGGCTCCCCG
 AGCCTCTCAC CCTGAGATGG GAGCCATCTT CCCAACCCAC CATCCCCATC
 GTGGGCATCG TTGCTGGCCT GGTTGTCCTT GGAGCTGTAG TCACTGGAGC
 TTTGGTCGCT GCTATGATGT GGAGGAAGAA GAGCTCAGAT AAA*
>DL;IPD:MHC00082
IPD:MHC00082 Atbe-G*03:02 993 bases
 CTCCTCCTGC TGCTCTCGGG GGTCCTGGCC CTGACCCAGA CCCGGGCGGG
 CTCCCACTCC TTGAGGTATT TCAGCACCAC CGTCTCCCGG CCCGGTCGCG
 GGGAGCCCCG GTACATGGAA GTCGGCTACG TGGACGACAC GCAGTTCATG
 CGGTTCGACA GCGACGCAGC GATTCCGAGG GTGGAGCCGC GGGCGCCGTG
 GATGGAGCAG GAGGGGCCGG AGTATTGGGA GGACCAGACA CGGAAAGTCA
 AGGCCGCCGC ACAGACTGAG CGAGTGAACC TGCGGTTGGT GCGCGGCTAC
 TACAACCAGA GCGAGGCCGG GTCTCACACC TTCCAGAGGA TGTATGGCTG
 CAACCTGGAG CCGGACGGGC GCCTCCTCCG CGGGTATTAC CAGCTCGCCT
 ACGACGGCAA GGACTACATC GTCCTGAACG AGGACCTGCG CTCCTGGACG
 GCCGCGGACC TGGCGGCTCA GATCACCCAG CGCAAGTGGG AGGCGGCCAA
 TGCGGCTGAG AGGATGAGAG CCTACCTGGA GGGCACGTGC GTTGAATGGC
 TCCGCAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CACGGAGCTC
 CCCAAGACAC ACGTGTCCCA CCACCCCATC TCTGACCATC AGACCACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG AGAGGACCAG ACCCAGGACA TGGAGCTCGT AGAGACCAGG
 CCTGCAGGGG ATGGAACCTT CCAGAAGTGG GCGGCTGTGG TGGTGCTTTC
 TGGAGAGGAG CAGAGGTACA CATGCCATGT GCAGCACCAG GGGCTGCCCG
 AGCCCCTCAC CCTGAGATGG GAGCCATCTT CCCAGCCCAC CATCCCCAAC
 GTGGGCATCG TTGCTGGCCT GGCTGTCCTT GGAGCTGTAG TCACTGGAGC
 TGTGGTCGCT GCTGTGATGT GGAGGAAGAA GAGCTCAGAT AAA*
>DL;IPD:MHC00081
IPD:MHC00081 Atbe-G*06:01 993 bases
 GTTCTCCTGT TGCTCTCGGA GGCCCTGCTC CTGACTGAAA CCTGGGCAAG
 CTCCTACTCC ATGAGGTATT TCTTCACCGC CCTGTCCCGG CCCGGCCGCG
 GGGAGCCCCG CTTCATCTCC GTGGGCTACG TGGACAACAC GCAGTTCCTG
 TGGTTCGACA GCGACGCCGC GATTCCAAGA GCAGAGCCGC GAGCGCCTTG
 GGCGGAGCAG GAGGGGGAAG AGTATTGGGA CTGGAACACA CGGTTCTGCA
 AGGACATTGC ACAGACTTAC CGGGGGAACC TGCGGACCCT GCGCGGCTAC
 TACAACCAGA GCGAGAAGGG GTCTCACATC TTCCAGAGCC TGCATGGCTG
 CGACCTGGGG CCGGATGGGC GCCTTCTCCG CGTGTATCAC CAGTTCGCCT
 ACGACGGCAA GGATTACATC GCCCTGAACG AGGACCTGCG CTCCTGGACC
 GCCGCGGATG TGGTGGCTCA GATCACACAG CGCAAGTGGC AGGCGAAAAA
 TGAGGCTGAG AATATTAGAC CCTACCTGGA GGGCACGTGC GTGGAGCGGC
 TCCGCAAATA CCTGAACAAC GGGAAGGAGA CGCTGCAGCG CGCGGAGCCC
 CCCAAGACAC ACGTGACCCA CCACCCCGTC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTTGGCT TCTACCCTGC CGAGATCACA CTGACCTGGC
 AGCGGGATGA GGAGGACCAG ACCCAGGACA TGGAGCTGGT AGAGACCAGG
 CCCATGGGGG ATGGAACCTC CCAGAAGTGG GCGGCTGTGG TGGTGCCTTC
 TGGAGAGGAG CAGAGATACA CATGCCGTGT GCAGCATGAG GGGCTGCCTG
 AGCCCCTCAC CCTGAGATGG GAGCCACCTT CCCAGCCCAC CATCCCCATC
 GTGGGCATCG TTGCTGGCCT GGCTGTCCTT GCAGCTATAG TCACTGGAGT
 TGTGGTTGCT GCTGTGATGT GGAGGAAGAA GAGCTCAGAT AAA*
