>DL;IPD:MHC00075
IPD:MHC00075 Atbe-B*01 1066 bases
 CTCCTCCTGC TGCTCTCGGG GGCCCTGGCC TTGACCCAGA CCCGGGCGGG
 CTCCCACTCC ATGAGGTATT TCTACACCTC CGTGTCCCGG CCCGGGCGCG
 GGGAGCCCCG CTTCATCGCC GTGGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCCGC GATTCCGAGG ATGGAGCCGC GGGCGCTGTG
 GATGGAGCAG GAGGGGCCGG AGTATTGGGA GGAGCAGACA CGGAGAGTCA
 AGGCCGCCGC ACAGACTGAC CGAGTGGACC TGCAGACCCT GCGCGGCTAC
 TACAACCAGA GCGAGGCCGG GTCTCACACC ATCCAGACAA TGTACGGCTG
 CGACGTGGGG CCCGAGGGGC GCTTCCTCCG TGGGTACCGG CAAGACGCCT
 ACGATGGCAA GGATTACATC GCCCTGAACG AGGACCTGCG CTCCTGGACC
 GCCGCGGACA TGGCGGCTCA GAACACCAAG CGCAAGTGGG AGGCGGCCAA
 CGTGGCTGAG CAATTGAGAG CCTACCTGGA GGGCAAGTGC CAGGAGTCGC
 TCCGCAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CGCGGATCCC
 CCAAAGACAC ACGTGACCCA CCACCCCGTC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTAC GGAGATCACA CTGACCTGGC
 AGCGGGATGG GGAAGATCAA ACTCAGGACA CGGAGCTTGT GGAGACAAGG
 CCAGCAGGGG ATGGAACCTT CCAGAAGTGG GCAGCTGTGG TGGTGCCTTC
 TGGAGAAGAG CAGAGATACA CGTGCTATGT GCAGCACGAG GGGCTGCCAG
 AGCCCCTCAC CCTGAGATGG GAGCCATCTT CCCAGCTCAC CATCCCTGTC
 GGCATCATTG CTGGCCTGGC TGTCCTAGTA GCTGTGGTCA TCGGAGCTGC
 GGTCACTGCT GTGATGTGGA GGAGGAAGAG CTCAGGTGGA AAAGGAGGGA
 GCTACTCTCA GGCTGCGTGT AGCGACAGTG CCCAGGGCTC TGATGTGTCT
 CTCACGGCTT GTAAAG*   
