>DL;IPD:MHC00079
IPD:MHC00079 Atbe-E*03:01 144 bases
 ARDTAQSFRV NLRTLLRYYN QSEAGSHTLQ WMHGCDVGPD GRFLSGYEQF
 AYDGTDYLTL NEDLRSWTAA DTAAQISQRK AEEACEAEHQ RAYLEDACVE
 WLLTYLENGK ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYP*
