>DL;IPD:MHC00079
IPD:MHC00079 Atbe-E*03:01 433 bases
 GCCAGGGACA CCGCACAGAG TTTCCGAGTG AACCTGCGGA CCCTGCTCCG
 CTACTACAAC CAGAGCGAGG CCGGGTCTCA CACCCTCCAG TGGATGCATG
 GCTGCGACGT GGGGCCCGAC GGGCGCTTCC TCAGCGGGTA TGAACAGTTC
 GCCTACGACG GCACGGATTA CCTCACCTTG AACGAGGACC TGCGCTCCTG
 GACCGCGGCG GACACCGCGG CTCAGATCTC CCAGCGCAAG GCAGAGGAGG
 CCTGTGAGGC GGAGCACCAA AGAGCCTACC TGGAGGACGC GTGCGTGGAG
 TGGCTCCTCA CATACCTGGA GAACGGGAAG GAGACGTTGC AGCGTGCGGA
 TCCCCCAAAG ACACATGTGA CCCACCACCC TGTCTCTGAC CATGAGGCCA
 CCCTGAGGTG CTGGGCCCTG GGTTTCTACC CTG* 
