>DL;IPD:MHC00080
IPD:MHC00080 Atbe-G*03:01 331 bases
 LLLLLSGALA LTQTRAGSHS MRYFDTAVSR PGRGEPHFFA VGYVDDTQFV
 RFDSDAASPR MEPRARWMEQ EGPEYWEEET RRSKAQAQTH RVSLRNLRGY
 YNQSEAGSHT LQRMSGCDLG PDGRLLRGYY QYAYDGKDYI ALNEDLRSWT
 AADVAAQITQ RKWGSGNEAE QSKAYLEGEC VESLRRYLEN GKETLQRAEP
 PKTHVTHHPV SDHEATLRCW ALGFYPVEIT LTWQRDGEDQ TQDTELVETR
 PAGDGTFQKW AAVVVPSGEE QRYTCHVQHD GLPEPLTLRW EPSSQPTIPI
 VGIVAGLVVL GAVVTGALVA AMMWRKKSSD K* 
>DL;IPD:MHC00082
IPD:MHC00082 Atbe-G*03:02 331 bases
 LLLLLSGVLA LTQTRAGSHS LRYFSTTVSR PGRGEPRYME VGYVDDTQFM
 RFDSDAAIPR VEPRAPWMEQ EGPEYWEDQT RKVKAAAQTE RVNLRLVRGY
 YNQSEAGSHT FQRMYGCNLE PDGRLLRGYY QLAYDGKDYI VLNEDLRSWT
 AADLAAQITQ RKWEAANAAE RMRAYLEGTC VEWLRRYLEN GKETLQRTEL
 PKTHVSHHPI SDHQTTLRCW ALGFYPAEIT LTWQRDGEDQ TQDMELVETR
 PAGDGTFQKW AAVVVLSGEE QRYTCHVQHQ GLPEPLTLRW EPSSQPTIPN
 VGIVAGLAVL GAVVTGAVVA AVMWRKKSSD K* 
>DL;IPD:MHC00081
IPD:MHC00081 Atbe-G*06:01 331 bases
 VLLLLSEALL LTETWASSYS MRYFFTALSR PGRGEPRFIS VGYVDNTQFL
 WFDSDAAIPR AEPRAPWAEQ EGEEYWDWNT RFCKDIAQTY RGNLRTLRGY
 YNQSEKGSHI FQSLHGCDLG PDGRLLRVYH QFAYDGKDYI ALNEDLRSWT
 AADVVAQITQ RKWQAKNEAE NIRPYLEGTC VERLRKYLNN GKETLQRAEP
 PKTHVTHHPV SDHEATLRCW ALGFYPAEIT LTWQRDEEDQ TQDMELVETR
 PMGDGTSQKW AAVVVPSGEE QRYTCRVQHE GLPEPLTLRW EPPSQPTIPI
 VGIVAGLAVL AAIVTGVVVA AVMWRKKSSD K* 
