>DL;IPD:MHC00083
IPD:MHC00083 Atfu-E*03:01 144 bases
 ARDTAQSFRV NLRTLLRYYN QSEAGSHTLQ WMHGCDVGPD GRFLSGYEQF
 AYDGTDYLTL NEDLRSWTAA DTAAQISQRK AEEACEAEHQ RAYLEDACVE
 WLLTYLENGK ETLQRADAPK THVTHHPVSD HEATLRCWAL GFYP*
>DL;IPD:MHC00084
IPD:MHC00084 Atfu-E*03:02 144 bases
 ARDTAQSFRV NLRTLLRYYN QSEAGSHTLQ WMHGCDVGPD GRFLRGYEQF
 AYDGTDYLTL NEDLRSWTAA DTAAQISQRK AEEACEAEHQ RAYLEDTCVE
 WLLTYLENGK ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYP*
