>DL;IPD:MHC05038
IPD:MHC05038 Atfu-B*01:01 365 bases
 MTVMAPRTLL LLLSGALALT QTRAGSHSLR YFYTSVSRPG RGEPRFIIVG
 YVDDTQFVRF DSDAASPRLE PRAPWMEQEG PEYWEEETRT AKAQAQTERV
 NLQILRGYYN QSEAGSHTIQ LMFGCDVGPE GRFLRGYRQD AYDGKDYIAL
 NEDLRSWTAA DVAAQNTKRK WEAANVAEQL RAYLEGECLE WLRRYLENGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCYVQHEGL PEPLTLRWEP
 SSQLTIPVGI IAGLAVLVAV VIGAAVTAVM WRRKSSGGKG GSYSQAACSD
 SAQGSDVSLT VCKAX*   
>DL;IPD:MHC05039
IPD:MHC05039 Atfu-B*01:02 365 bases
 MTVMAPRTLL LLLSGALALT QTGAGSHSMR YFSTAMSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASPRME PRALWMEQEG PEYWEEQTRR VKAAAQTERV
 SLRNLRGYYN QSEAGSHTIQ LMFGCDVGPE GRFLRGYRQD AYDGKDYIAL
 NEDLRSWTAA DVAAQNTKRK WEAANVAEQL RAYLEGECLE WLRRYLENGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCYVQHEGL PEPLTLRWEP
 SSQLTIPVGI IAGLAVLVAV VIGAAVTAVM WRRKSSGGKG GSYSQAACSD
 SAQGSDVSLT ACKAX*   
>DL;IPD:MHC05087
IPD:MHC05087 Atfu-B*01:03 365 bases
 MTVMAPRTLL LLLSGALALT QTRAGSHSLR YFYTSVSRPG RGEPRFIIVG
 YVDDTQFVRF DSDAASPRLE PRAPWMEQEG PEYWEEETRT AKAQAQTERV
 NLQILRGYYN QSEAGSHTIQ TMYGCDVGPG GRLLRGYRQY AYDGKDYIAL
 NEDLRSWTAA DMAAQITQRK WEAANEAEQL RAYLEGECLE WLRRYLENGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCYVQHEGL PEPLTLRWEP
 SSQLTIPVGI IAGLAVLVAV VIGAVVTAVM WRRKSSGGKG GSYSQAACSD
 GAQGSDVSLT VCKAX*   
>DL;IPD:MHC05040
IPD:MHC05040 Atfu-B*02:01 365 bases
 MTVMAPRTLL LLLSGALALT QTRAGFHSLR YFYTSVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAAIPREE PRVPWMEQEG PEYWEDETRI SKATTQTDRV
 SLRNLRGYYN QSEAGSHTIQ AMYGCDVGPG GRFLRGYRQD AYDGKDYIAL
 NEDLRSWTAA DMAAQNTKRK WEATNVAEQF RAYLEGECLE GLRRYLENGK
 ETLQRADSPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCYVQHEGL PEPLTLRWEP
 SSQLTIPVGI IAGLAVLVAV VIGAAVTAVM WRRKSSGGKG GSYSQAACSD
 SAQGSDVSLT ACKAX*   
>DL;IPD:MHC05088
IPD:MHC05088 Atfu-B*02:02 365 bases
 MTVMAPRTLL LLLSGALALT QTRAGFHSLR YFYTSVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAAIPREE PRVPWMEQEG PEYWEDETRI SKATTQTDRV
 SLRNLRGYYN QSEAGSHTLQ TMYGCDVGPE GRFLRGYRQY AYDGKDYIAL
 NEDLRSWTAA DMAAQNTKRK WEATNVAEQF RAYLEGECLE GLRRYLENGK
 ETLQRADSPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WLRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCYVQHGGL PEPLTLRWEP
 SSQLTIPVGI IAGLAVLVAV VIGAAVTAVM WRRKSSGGKG GSYSQAACSD
 SAQGSDVSLT ACKAX*   
>DL;IPD:MHC05089
IPD:MHC05089 Atfu-B*02:03 365 bases
 MTVMAPRTLL LLLSGALALT QTRAGSHSLR YFYTAVSRPG RGEPRFISVG
 YVDDMQFVRF DSDAAIPREE PRVPWMEQEG PEYWEEQTRR VKAAAQTYRV
 NLRTALGYYN QSEAGSHTIQ AMYGCDVGPG GRFLRGYRQD AYDGKDYIAL
 NEDLRSWTAA DMAAQNTKRK WEATNVAEQF RAYLEGECLE GLRRYLENGK
 ETLQRADSPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCYVQHEGL PEPLTLRWEP
 SSQLTIPVGI IAGLAVLVAV VIGAAVTAVM WRRKSSGGKG GSYSQAACSD
 SAQGSDVSLT ACKAX*   
>DL;IPD:MHC05042
IPD:MHC05042 Atfu-B*02:04 365 bases
 MTVMAPRTLL LLLSGALALT QTRAGSHSLR YFYTAVSRPG RGEPRFISVG
 YVDDMQFVRF DSDAAIPREE PRVPWMEQEG PEYWEEQTRR VKAAAQTYRV
 NLRTALGYYN QSEAGSHTIQ AMYGCDVGPE GRFLRGYRQY AYDGKDYIAL
 NEDLRSWTAA DMAAQNTKRK WEAANNAEQR RAYLEGECVE WLRRYLENGK
 EMLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQLTIPVGI IAGLAVLVAV VIGAVVTAVM WRRKSSGGKG GSYSQAACSD
 SAQGSDVSLT ACKAX*   
>DL;IPD:MHC05041
IPD:MHC05041 Atfu-B*03:01 365 bases
 MTVMAPRTLL LLLSGALALT QTRAGFHSLR YFYTSVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAAIPREE PRVPWMEQEG PEYWEDETRI SKATTQTDRV
 SLRNLRGYYN QSEAGSHTLQ TMYGCDVGPE GRFLRGYRQY AYDGKDYIAL
 NEDLRSRTAA DMAAQNTKRK WEAANNAEQR RAYLEGECVE WLRRYLENGK
 EMLQRADPPK THVTHHPVSD HEATLRCRAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQLTIPVGI IAGLAVLVAV VIGAVVTAVM WRRKSSGGKG GSYSQAACSD
 SAQGSDVSLT ACKAX*   
>DL;IPD:MHC05086
IPD:MHC05086 Atfu-B*03:02 362 bases
 MAPRTVLLLL SGALALTQTR AVSHSMRYFT TAVSRPGRGE PRFISVGYVD
 DTQFVRFDSD AAIPREEPRV PWMEQEGPEY WEDETRISKA TTQTDRVSLR
 NLRGYYNQSE AGSHTLQTMY GCDVGPEGRF LRGYRQYAYD GKDYIALNED
 LRSWTAADMA AQNTKRKWEA ANNAEQRRAY LEGECVEWLR RYLENGKEML
 QRADPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEDQTQDTE
 LVETRPAGDG TFQKWAAVVV PSGEEQRYTC RVQHEGLPEP LTLRWEPSSQ
 LTIPVGIIAG LAVLVAVVIG AVVTAVMWRR KSSGGKGGSY SQAACSDSAQ
 GSDVSLTACK AX*   
>DL;IPD:MHC05043
IPD:MHC05043 Atfu-B*04:01 363 bases
 MEPRTLLLLL WGALGLTEIW ASSHSMRYLS TVVSRPGRGE PWYFAVGYVD
 DTQFLRFDSD AAIPRMEPQA PWAEQEGPEY WDLLTRRAEA CAQTCRVSLR
 DIRGYYSQSE AGSHTLQVTF GCYLGPNGRL LRGYCRIAYD GKDHVALNED
 LHSWTAADTA AQVTQRKLEA EKYAEQLRAQ LEGECVEWLK RYLENGKETL
 QRAEPPKTHV THHPTSDQEA TLRCWALGFY PAEITLTWQR DGEDQTRDTE
 LVETRPSGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP LTLRWEPSSQ
 PTIPIVGIVA GLAVLGAVVV GAVVTAVMWR RKSSGGKGGS YSQAACSDSA
 QGSDVSLTAC KAX*   
>DL;IPD:MHC05044
IPD:MHC05044 Atfu-B*04:02 362 bases
 MEPRTLLLLL WGALGLTEIW ASSHSMRYLS TVVSRPGRGE PWYFAVGYVD
 DTQFLRFDSD AAIPRMEPQA PWAEQEGPEY WDLLTRRAEA CAQTCRVSLR
 DIRGYYNQSE AGSHTLQVTF GCYLGPNGRL LRGYCRIAYD GKDHVALNED
 LHSWTAADTA AQVTQRKLEA EKYAEQLRAQ LEGECVEWLK RYLENGKEML
 QRADPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEDQTQDTE
 LVETRPAGDG TFQKWAAVVV PSGEEQRYTC YVQHEGLPEP LTLRWEPSSQ
 PTIPVGIIAG LAVLVAVVIG AAVTAVVWRR KSSGGKGGSY SQAACSDSAQ
 GSDVSLTACK AX*   
>DL;IPD:MHC05085
IPD:MHC05085 Atfu-B*05:01 365 bases
 MTVMAPRTLL LLLSGALALT QTRAVSHSMR YFTTAVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAAIPREE PRVPWMEQEG PEYWEDETRI SKATTQTDRV
 NLRTLRGYYN QSEAGSHTVQ EMHGCDLGPD GRFLRGYYQS AYDGKDYISL
 NEDLCSWTAA DTAAEITQRK CEAANEAEEW RAYLEGECVE FLRRHLENGK
 ETLQRADPPK TQVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQLTIPVGI IAGLAVLVAV VIGAVVTAVM WRRKSSGGKG GSYSQAACSD
 SAQGSDVSLT ACKAX*   
