>DL;IPD:MHC00085
IPD:MHC00085 Caja-DQA1*01:01 188 bases
 TCTTATGGTA CCTCTGGCCA GTTCACCCAT GAATTTGATG GAGATGAACA
 GTTCTACGTG GACCTGGAGA GAAAGGAGAC TCTCTGGCGG TGGCCTATGT
 TGAGCAAATT TGGAGGTTTT GACCCGCAGG GCGCACTGAG AAACCTCGCT
 GTGTCAAAAC ACAACTTGGA CATCCTGATT AAACGCTC* 
>DL;IPD:MHC00086
IPD:MHC00086 Caja-DQA1*27:01 188 bases
 TCTTATGGTC CCTCTGGCCA GTTCACCCAT GAATTCGATG GAGACGAGGA
 GTTCTACGTG GACCTAGGGA AAAAGGAGAC TGTCTGGCGA TTGCCTGTGT
 TCAGCACATT TACAAGTTTT GACCCACAGG GCGCACTGAC AAACATCGCT
 ACGATGAAAC CCGGCTTGGA CATCCTGATT AAACGCTC* 
