>DL;IPD:MHC00114
IPD:MHC00114 Caja-E*03:01 433 bases
 GCCAGGGACA CCGCACAGAG TTTCCGAGTG AACCTGCGGA CCCTGCTCCG
 CTACTACAAC CAGAGCGAGG CCGGGTCTCA CACCCTCCAG TGGCTGCATG
 GCTGCGACGT GGGGCCAGAC GGGCGCTTCC TCCGCGGGTA TGAACAGTTC
 GCCTACGATG GCAAGGATTA CCTCACCTTG AACGAGGACC TGCGCTCCTG
 GACCGCAGCG GACACGGCGG CTCAGATCTC CCAGCGCAAG TCAGAGGAGG
 CCTGTGAGGC GGAGCACCAA AGGGCCTACC TGGAGGACAC GTGCGTGGAG
 TGGCTCCGCA GATACCTGGA GAACGGGAAG GAGACGCTGC AGCGTGCGGA
 ACCCCCAAAG ACACATGTGA CCCACCACCC TGTCTCTGAC CATGAGGCCA
 CCCTGAGATG CTGGGCCCTG GGTTTCTACC CTG* 
>DL;IPD:MHC00115
IPD:MHC00115 Caja-E*03:02 433 bases
 GCCAGGGACA CCGCACAGAG TTTCCGAGTG AACCTGCGGA CCCTGCTCCG
 CTACTACAAC CAGAGCGAGG CCGGGTCTCA CACCCTCCAG TGGCTGCATG
 GCTGCGACTT GGGGCCAGAC GGGCGCTTCC TCCGCGGGTA TGAACAGTTC
 GCCTACGATG GCAAGGATTA CCTCACCTTG AACGAGGACC TGCGCTCCTG
 GACCGCAGCG GACACCGCGG CTCAGATCTC CCAGCGCAAG TCAGAGGAGG
 CCTGTGAGGC GGAGCACCAA AGGGCCTACC TGGAGGACAC GTGCGTGGAG
 TGGCTCCGCA GATACCTGGA GAACGGGAAG GAGACGCTGC AGCGTGCGGA
 ACCCCCAAAG ACACATGTGA CCCACCACCC TGTCTCTGAC CATGAGGCCA
 CCCTGAGATG CTGGGCCCTG GGTTTCTACC CTG* 
