>DL;IPD:MHC05010
IPD:MHC05010 Caja-G*07:01:01 362 bases
 MAPRTLLLLL SGALALTETW AGSHSMRYFS TAVSRPGRGE PRFIIVGYVD
 DTQFVRFDSD AANPRMEPRA PWVEQEGPEY WEEQTRRAKA IAQIDRVDLR
 TLRGYYNQSD AGSHTIQWMS GCDVGPDGRL LRGYRQDAYD GKDYIALNED
 LRSWTAADMA AQITQRKWEA ANAAEEMRAY LEGECLEWLH RYLENAKETL
 QRAEPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEDQTQDME
 LVETRPTGDR TFQKWAAVVV PSGEEHRYTC HMQHEGLPEP LTLRWEPPSQ
 PTIPIMGIVA ALAILGAVGG AVVVAVMWRK KSSDKKGGSY SQAARSESAQ
 GSDVSLTACK VX*   
>DL;IPD:MHC04992
IPD:MHC04992 Caja-G*07:01:02 344 bases
 LLLLSGALAL TETWAGSHSM RYFSTAVSRP GRGEPRFIIV GYVDDTQFVR
 FDSDAANPRM EPRAPWVEQE GPEYWEEQTR RAKAIAQIDR VDLRTLRGYY
 NQSDAGSHTI QWMSGCDVGP DGRLLRGYRQ DAYDGKDYIA LNEDLRSWTA
 ADMAAQITQR KWEAANAAEE MRAYLEGECL EWLHRYLENA KETLQRAEPP
 KTHVTHHPVS DHEATLRCWA LGFYPAEITL TWQRDGEDQT QDMELVETRP
 TGDRTFQKWA AVVVPSGEEH RYTCHMQHEG LPEPLTLRWE PPSQPTIPIM
 GIVAALAILG AVGGAVVVAV MWRKKSSDKK GGSYSQAARS ESAQ*
>DL;IPD:MHC00116
IPD:MHC00116 Caja-G*07:02 330 bases
 LLLLLSGALV LTETWAGSHS MRYFYTSVSR PGRGEPRFII VGYVDDTQFV
 RFDSDAANPR MEPRAPWVEQ EGPEYWEEQT RRAKAHAQTD RVDLRTLRGY
 YNQSDAGSHT IQWMSGCVVG PDGRLLRGYR QDAYDGKDYI ALNEDLRSWT
 AADMAAQITQ RKWEAANAAE EMRAYLEGEC LEWLHRYLEN AKETLQRAEP
 PKTHVTHHPV SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDMELVETR
 PTGDRTFQKW AAVVVPSGEE HRYTCHVQHE GLPEPLTLRW EPPSQPTIPI
 MGIVAALAIL GAVGGAVVVA VMWRKKSSDK * 
>DL;IPD:MHC04990
IPD:MHC04990 Caja-G*07:03 347 bases
 LLLLSGALAP TETWAGSHSM RYFSTAVSRP GRGEPRFIIV GYVDDTQFVR
 FDSDAANPRM EPRAPWVEQE GPEYWDEETR RAKAIAQIDR VDLRTLRGYY
 NQSDAGSHTI QWMSGCDVGP DGRLLRGYRQ DAYDGKDYIA LNEDLRSWTA
 ADVAAQITQR KWEAANAAEE MRAYLEGECL EWLHRYLENA KETLQRAEPP
 KTHVTHHPVS DHEATLRCWA LGFYPAEITL TWQRDGEDQT QDMELVETRP
 TGDRTFQKWA AVVVPSGEEH RYTCHMQHEG LPEPLTLRWE PPSQPTIPIM
 GIVAALATLG AVGGAVVVAV MWRKKSSDKK GGSYSQAARS ESAQGSD*
>DL;IPD:MHC05052
IPD:MHC05052 Caja-G*07:04 347 bases
 LLLLSGALAL TETWAGSHSM RYFSTAVSRP GRGEPRFIIV GYVDDTQFVR
 FDSDAANPRM EPRAPWVEQE GPEYWEEQTR RAKAIAQIDR VDLRTLRGYY
 NQSDAGSHTI QWMSGCDVGP DGRLLRGYRQ DAYDGKDYIA LNEDLRSWTA
 ADMAAQITQR KWEAANAAEE MRAYLEGECL EWLHRYLENA KETLQRAEPP
 KTHVTHHPVS DHEATLRCWA LGFYPAEITL TWQRDGEDQS QDMELVETRP
 TGDRTFQKWA AVVVPSGEEH RYTCHMQHEG LPEPLTLRWE PPSQPTIPIM
 GIVAALAILG AVGGAVVVAV MWRKKSSDKK GGSYSQAARS ESAQGSD*
>DL;IPD:MHC05051
IPD:MHC05051 Caja-G*07:05 362 bases
 MAPRTLLLLL SGALALTETW AGSHSMRYFS TAVSRPGRGE PRFIIVGYVD
 DTQFVRFDSD AANPRMEPRA PWVEQEGPEY WDEETRRAKA IAQIDRVDLR
 TLRGYYNQSD AGSHTIQWMS GCDVGPDGRL LRGYRQDAYD GKDYIALNED
 LRSWTAADMA AQITQRKWEA ANAAEEMRAY LEGECLEWLH RYLENAKETL
 QRAEPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEDQTQDME
 LVETRPTGDR TFQKWAAVVV PSGEEHRYTC HMQHEGLPEP LTLRWEPPSQ
 PTIPIMGIVA ALAILGAVGG AVVVAVMWRK KSSDKKGGSY SQAARSESAQ
 GSDVSLTACK VX*   
>DL;IPD:MHC00119
IPD:MHC00119 Caja-G*08:01 362 bases
 MAPRTLLLLL SGALALTETG AGSHSMRYFS TAMSRPGRGE PRYIEVGYVD
 DTQFVRFDSD AASPRMEPRA PWVEQEGPEY WDEETRRAKT LAQTFRGNLR
 TALGYYNQTD AGSHTIQWMS GCDVGPDGRL LRGYNQFAYD GKDYIALNED
 LRSWTAPDVA AQITQRKWEA ANEAERRRAY LEGTCVEWLR RYLENGKETL
 QRAEPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEDQTQDME
 LVETRPAGDR TFQKWAAVVV LSGEERRYTC HVHHEGLPEP LTLRWEPPSQ
 PTIPIMGIVA ALAILGAVTG AVVVAVMWRK NSSDKKGGSY SQAARSDSAQ
 GSDVSLTACK VX*   
>DL;IPD:MHC05025
IPD:MHC05025 Caja-G*08:02 362 bases
 MAPRTLLLLL SGALALTETG AGSHSMRYFS TAMSRPGRGE PRYIEVGYVD
 DTQFVRFDSD AASPRMEPRA PWVEQEGPEY WDEETRRAKT LAQTFRGNLR
 TALGYYNQTD AGSHTIQWMS GCDVGPDGRL LRGYNQFAYD GKDYIALNED
 LRSWTAPDVA AQITQRKWEA ANEAERRRAY LEGTCVEWLR RYLENGKETL
 QRAEPPKTHV THHPVSDHEA TLRCRALGFY PAEITLTWQR DGEDQTQDME
 LVETRPAGDR TFQKWAAVVV LSGEERRYTC HVHHEGLPEP LTLRWEPPPQ
 PTIPIMGIVA ALAILGAVTG AVVVAVMWRK NSSDKKGGSY SQAARSDSAQ
 GSDVSLTACK VX*   
>DL;IPD:MHC04981
IPD:MHC04981 Caja-G*08:03 362 bases
 MAPRTLLLLL SGALALTETW AGSHSMRYFS TAMSRPGRGE PRYIEVGYVD
 DTQFVRFDSD AASPRMEPRA PWVEQEGPEY WDEETRRAKT LAQTFRGNLR
 TALGYYNQTD AGSHTIQWMS GCDVGPDGRL LRGYNQFAYD GKDYIALNED
 LRSWTAADVA AQITQRKWEA ANEAERRRAY LEGTCVEWLR RYLENGKETL
 QRAEPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEDQTQDME
 LVETRPAGDR TFQKWAAVVV LSGEERRYTC HVHHEGLPEP LTLRWEPPSQ
 PTIPIMGIVA ALAILGAVTG AVVVAVMWRK KSSDKKGGSY SQAARSDSAQ
 GSDVSLTACK VX*   
>DL;IPD:MHC04983
IPD:MHC04983 Caja-G*08:04 344 bases
 LLLLSGALAL TETWAGSHSM RYFSTAMSRP GRGEPRYIEV GYVDDTQFVR
 FDSDAASPRV EPRAPWVEQE GPEYWDEETR RAKTLAQTFR GNLRTALGYY
 NQTDAGSHTI QWMSGCDVGP DGRLLRGYNQ FAYDGKDYIA LNEDLRSWTA
 ADVAAQITQR KWEAANEAEG RRAYLEGTCV EWLRRYLENG KETLQRAEPP
 KTHVTHHPVS DHEATLRCWA LGFYPAEITL TWQRDGEDQT QDMELVETRP
 VGDRTFQKWA AVVVLSGEER RYTCHVHHEG LPEPLTLRWE PPSQPTIPIM
 GIVAALAILG AVTGAVVVAV MWRKKSSDKK GGSYSQAARS DSAQ*
>DL;IPD:MHC04982
IPD:MHC04982 Caja-G*08:05 347 bases
 LLLLSGALAL TETWAGSHSM RYFSTAVSRP GRGEPRYIEV GYVDDTQFVR
 FDSDAASPRM EPRAPWVEQE GPEYWDEETR RAKTLAQTFR GNLRTALGYY
 NQTDAGSHTI QWMSGCDVGP DGRLFRGYNQ FAYDGKDYIA LNEDLRSWTA
 ADVAAQITQR KWEAANEAER RRAYLEGTCV EWLRRYLENG KETLQRAEPP
 KTHVTHHPVS DHEATLRCWA LGFYPAEITL TWQRDGEDQT QDMELVETRP
 AGDRTFQKWA AVVVLSGEER RYTCHVHHEG PPEPLTLRWE PPSQPTIPIM
 GIVAALAILG AVTGAVVVAV MWRKKSSDKK GGSYSQAARS DSAQGSD*
>DL;IPD:MHC05009
IPD:MHC05009 Caja-G*09:01 362 bases
 MAPRTLLLLL SGALALTETG AGSHSMRYFS TAVSRPGRGE PRYIEVGYVD
 DTQFVRFDSD AASPRMEPRA PWVEQEGPEY WDEETRRAKA NAQTDRVNLQ
 TALGYYNQTD AGSHTIQWMS GCDVGPDGRL LRGYDQYAYD GKDYIALNED
 LRSWTAADVA AQITQRKWEA ANVAEEWRAY LEGTCLEWLH RYLENGKETL
 QRAEPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEDQTQDME
 LVETRPAGDR TFQKWAAVVV PSGEEQRYTC HMQHEGLPEP LTLRWEPPSQ
 PTIPIMGIVT ALAILGTVAG AVVVAVMWRK KSSDKKGGSY SQAARSESAQ
 GSDVSLTACK VX*   
>DL;IPD:MHC05020
IPD:MHC05020 Caja-G*09:02 362 bases
 MAPRTLLLLL SGALALTETG AGSHSMRYFS TAVSRPGRGE PRYIEVGYVD
 DTQFVRFDSD AASPRMEPRA PWVEQEGPEY WDEETRRAKA NAQTFRVNLR
 TALGYYNQTD AGSHTFQVMY GCDVGPDGRL LRGYDQYAYD GKDYIALNED
 LRSWTAADVA AQITQRKWEA ANVAEEWRAY LEGTCLEWLH RYLENGKETL
 QRAEPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEDQTQDME
 LVETRPAGDR TFQKWAAVVV PSGEEQRYTC HMQHEGLPEP LTLRWEPPSQ
 PTIPIMGIVT ALAILGTVAG AVVVAVMWRK KSSDKKGGSY SQAARSESAQ
 GSDVSLTACK VX*   
>DL;IPD:MHC05021
IPD:MHC05021 Caja-G*09:03 365 bases
 MTVMAPRTLL LLLSGALALT ETGAGSHSMR YFSTAVSRPG RGEPRYIEVG
 YVDDTQFVRF DSDAASPRME PRAPWVEQEG PEYWDEETRR AKANAQTDRV
 NLQTALGYYN QTDAGSHTFQ VMYGCDVGPD GRLLRGYDQY AYDGKDYIAL
 NEDLRSWTAA DVAAQITQRK WEAANVAEEW RAYLEGTCLE WLHRYLENGK
 ETLQRAEPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DMELVETRPA GDRTFQKWAA VVVPSGEEQR YTCHMQHEGL PEPLTLRWEP
 PSQPTIPIMG IVTALAILGT VAGAVVVAVM WRKKSSDKKG GSYSQAARSE
 SAQGSDVSLT ACKVX*   
>DL;IPD:MHC05022
IPD:MHC05022 Caja-G*09:04 362 bases
 MAPRTLLLLL SGALALTETG AGSHSMRYFS TAVSRPGRGE PRYIEVGYVD
 DTQFVRFDSD AASPRMEPRA PWVEQEGPEY WDEETRKAKA NAQTDRVNLQ
 TALGYYNQTD AGSHTFQVMY GCDVGPDGRL LRGYDQYAYD GKDYIALNED
 LRSWTAADVA AQITQRKWEA ANVAEEWRAY LEGTCLEWLH RYLENGKETL
 QRAEPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEDQTQDME
 LVETRPAGDR TFQKWAAVVV PSGEEQRYTC HMQHEGLPEP LTLRWEPPSQ
 PTIPIMGIVT ALAILGTVAG AVVVAVMWRK KSSDKKGGSY SQAARSESAQ
 GSDVSLTACK VX*   
>DL;IPD:MHC04985
IPD:MHC04985 Caja-G*09:05 347 bases
 LLLLSGALAL TETGAGSHSM RYFSTAVSRP GRGEPRYIEV GYVDDTQFVR
 FDSDAASPRM EPRAPWVEQE GPEYWDEETR KAKANAQTDR VNLQTALGYY
 NQTDAGSHTF QVMYGCDVGP DGRLLRGYDQ YAYDGKDYIA LNEDLRSWTA
 ADVAAQITQR KWEAANVAEE WRAYLEGTCL EWLHRYLENG KGTLQRAEPP
 KTHVTHHPVS DHEATLRCWA LGFYPAEITL TWQRDGEDQT QDMELVETRP
 AGDRTFQKWA AVVVPSGEEQ RYTCHMQHEG LPEPLTLRWE PPSQPTIPIM
 GIVTALAILG TVAGAVVVAV MWRKKSSDKK GGSYSQAARS ESAQGSD*
>DL;IPD:MHC05056
IPD:MHC05056 Caja-G*09:06 365 bases
 MTVLAPRTLL LLLSGALALT ETGAGSHSMR YLHTAMSRPG RGEPRFIYVG
 YVDDTQLVRF DSDAASPRME PRAPWVEQEG PEYWDEETRR AKANAQTDRV
 NLQTALGYYN QTDAGSHTFQ VMYGCDVGPD GRLLRGYDQY AYDGKDYIAL
 NEDLRSWTAA DVAAQITQRK WEAANVAEEW RAYLEGTCLE WLHRYLENGK
 ETLQRAEPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DMELVETRPA GDRTFQKWAA VVVPSGEEQR YTCHMQHEGL PEPLTLRWEP
 PSQPTVPIMG IVTALAILGT VAGAVVVAVM WRKKSSDKKG GSYSQAARSE
 SAQGSDVSLT ACKVX*   
>DL;IPD:MHC00118
IPD:MHC00118 Caja-G*10:01 330 bases
 LLLLLSGALA LTETWAGSHS MRYFSTAVSR PGRGEPRYIE VGYVDDTQFV
 RFDSDAASPR MEPRAPWVEQ EGPEYWEEQT RNAKTHAQTD RVNLQTLRGY
 YNQTDAGSHT FQVMYGCDVG PDGRLLRGYD QYAYDGKDYI ALNEDLRSWT
 AADVAAQITQ RKWEAANEAE SIRAYLEGTC LEWLHRYLEN GKETLQRAEP
 PKTHVTHHPV SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDMELVETR
 PAGDRTFQKW AAVVVPSGEE QRYTCHMQHE GLPEPLTLRW EPPSQPTIPI
 MGIVTALAIL GTVAGAVVVA VMWRKKSSDK * 
>DL;IPD:MHC05023
IPD:MHC05023 Caja-G*10:02 362 bases
 MAPRTLLLLL SGALALTETG AGSHSMRYFS TAVSRPGRGE PRYIEVGYVD
 DTQFVRFDSD AASPRMEPRA PWVEQEGPEY WEEQTRNAKT HAQTDRVNLR
 TLRGYYNQTD AGSHTFQVMY GCDVGPDGRL LRGYDQYAYD GKDYIALNED
 LRSWTAADVA AQITQRKWEA ANEAERIRAY LEGTCLEWLR RYLENGKETL
 QRAEPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEDQTQDME
 LVETRPAGDR TFQKWAAVVV PSGEEQRYTC HMQHEGLPEP LTLRWEPPSQ
 PTIPIMGIVT ALAILGTVAG AVVVAVMWRK KSSDKKGGSY SQAARSESAQ
 GSDVSLTACK VX*   
>DL;IPD:MHC04984
IPD:MHC04984 Caja-G*10:03:01 362 bases
 MAPRTLLLLL SGALALTETG AGSHSMRYFS TAVSRPGRGE PRYIEVGYVD
 DTQFVRFDSD AASPRMEPRA PWVEQEGPEY WEEQTRNAKT HAQTDRVNLQ
 TALGYYNQTD AGSHTFQVMY GCDVGPDGRL LRGYDQYAYD GKDYIALNED
 LRSWTAADVA AQITQRKWEA ANEAERIRAY LEGTCLEWLH RYLENGKETL
 QRAEPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEDQTQDME
 LVETRPAGDR TFQKWAAVVV PSGEEQRYTC HMQHEGLPEP LTLRWEPPSQ
 PTIPIMGIVT ALAILGTVAG AVVVAVMWRK KSSDKKGGSY SQAARSESAQ
 GSDVSLTACK VX*   
>DL;IPD:MHC04987
IPD:MHC04987 Caja-G*10:03:02 347 bases
 LLLLSGALAL TETGAGSHSM RYFSTAVSRP GRGEPRYIEV GYVDDTQFVR
 FDSDAASPRM EPRAPWVEQE GPEYWEEQTR NAKTHAQTDR VNLQTALGYY
 NQTDAGSHTF QVMYGCDVGP DGRLLRGYDQ YAYDGKDYIA LNEDLRSWTA
 ADVAAQITQR KWEAANEAER IRAYLEGTCL EWLHRYLENG KETLQRAEPP
 KTHVTHHPVS DHEATLRCWA LGFYPAEITL TWQRDGEDQT QDMELVETRP
 AGDRTFQKWA AVVVPSGEEQ RYTCHMQHEG LPEPLTLRWE PPSQPTIPIM
 GIVTALAILG TVAGAVVVAV MWRKKSSDKK GGSYSQAARS ESAQGSD*
>DL;IPD:MHC05055
IPD:MHC05055 Caja-G*10:03:03 365 bases
 MTVMAPRTLL LLLSGALALT ETGAGSHSMR YFSTAVSRPG RGEPRYIEVG
 YVDDTQFVRF DSDAASPRME PRAPWVEQEG PEYWEEQTRN AKTHAQTDRV
 NLQTALGYYN QTDAGSHTFQ VMYGCDVGPD GRLLRGYDQY AYDGKDYIAL
 NEDLRSWTAA DVAAQITQRK WEAANEAERI RAYLEGTCLE WLHRYLENGK
 ETLQRAEPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DMELVETRPA GDRTFQKWAA VVVPSGEEQR YTCHMQHEGL PEPLTLRWEP
 PSQPTIPIMG IVTALAILGT VAGAVVVAVM WRKKSSDKKG GSYSQAARSE
 SAQGSDVSLT ACKVX*   
>DL;IPD:MHC00117
IPD:MHC00117 Caja-G*11:01:01 330 bases
 LLLLLSGALA LTETWAGSHS MKYFSTAVSR PGRGEPRYIE VGYVDDTQFV
 RFDSDAASPR MEPRAPWVEQ EGPEYWDEET RKAKTHAQTF RVNLRTALGY
 YNQSDAGSHT IQLMYGCYLG PDGRLLRGYR QDAYDGKDYI ALNEDLRSWT
 AADVAAQITQ RKWEATNEAE EWRAYLEGTC VEWLRRYLEN GKETLQRAEP
 PKTHVTHHPV SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDMELVETR
 PAGDGTFQKW AAVVVPSGEE QRYTCHVHHE GLSEPVTLRW EPPSQPTIPI
 MGIVAALAIL GAVAGAVVVA VMWRKKSSDK * 
>DL;IPD:MHC04998
IPD:MHC04998 Caja-G*11:01:02 362 bases
 MAPRTLLLLL SGALALTETW AGSHSMKYFS TAVSRPGRGE PRYIEVGYVD
 DTQFVRFDSD AASPRMEPRA PWVEQEGPEY WDEETRKAKT HAQTFRVNLR
 TALGYYNQSD AGSHTIQLMY GCYLGPDGRL LRGYRQDAYD GKDYIALNED
 LRSWTAADVA AQITQRKWEA TNEAEEWRAY LEGTCVEWLR RYLENGKETL
 QRAEPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEDQTQDME
 LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVHHEGLSEP VTLRWEPPSQ
 PTIPIMGIVA ALAILGAVAG AVVVAVMWRK KSSDKKGGSY SQATRSDSAQ
 GSDVSLTACK VX*   
>DL;IPD:MHC05015
IPD:MHC05015 Caja-G*11:02 365 bases
 MTVMAPRTLL LLLSGALALT ETWAGSHSMK YFSTAVSRPG RGEPRYIEVG
 YVDDTQFVRF DSDAASPRME PRAPWVEQEG PEYWDEETRR AKTLAQTFRV
 NLRTALGYYN QSDAGSHTIQ LMYGCYLGPD GRLLRGYRQD AYDGKDYIAL
 NEDLRSWTAA DVAAQITQRK WEATNEAEEW RAYLEGTCVE WLRRYLENGK
 ETLQRAEPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DMELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVHHEGL SEPVTLRWEP
 PSQPTIPIMG IVAALAILGA VAGAVVVAVM WRKKSSDKKG GSYSQATRSD
 SAQGSDVSLT ACKVX*   
>DL;IPD:MHC05026
IPD:MHC05026 Caja-G*11:03 362 bases
 MAPRTLLLLL SGALALTETW AGSHSMKYFS TAVSRPGRGE PRYIEVGYVD
 DTQFVRFDSD AASPRMEPRA PWVEQEGPEY WDEETRRAKT LAQTFRVNLR
 TALGYYNQSD AGSHTIQLMY GCYLGPDGRL LRGYHQFAYD GKDYIALNED
 LRSWTAADVA AQITQRKWEA TNEAERRRAY LEGTCVEWLR RYLENGKETL
 QRAEPPKTHV THHPVSDHEA TLRCWALGFY PVEITLTWQR DGEDQTQDME
 LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVHHEGLSEP VTLRWEPPSQ
 PTIPIMGIVA ALAILGAVAG AVVVAVMWRK KSSDKKGGSY SQATRSDSAQ
 GSDVSLTACK VX*   
>DL;IPD:MHC05008
IPD:MHC05008 Caja-G*12:01 362 bases
 MAPRTLLLLL SGALALTETW AGSHSMRYFH TAMSRPGRGE PRFIIVGYVD
 DTQFVRFDSD AASPRMEPRA PWVEQEGPEY WDEETRKAKA NAQIDRVNLR
 TLRGYYNQTD AGSHTIQWMS GCDVGPDGRL LRGYRQDAYD GKDYIALNED
 LRSWTAADVA AQITQRKWEA ANVAERRRAY LEGTCVEWLR RYLENGKETL
 QRAEPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEDQTQDME
 LIETRPAGDR TFQKWAAVVV LSGEEHRYTC HVQHEGLPEP LTLRWEPSSQ
 PTIPIMGIVA ALAILGALAG AVVAAVMWRK KSSDKKGGSY SQAARSESAQ
 GSDVSLTACK VX*   
>DL;IPD:MHC05013
IPD:MHC05013 Caja-G*12:02 362 bases
 MAPRTLLLLL SGALALTETW AGSHSMRYFH TAMSRPGRGE LRFIIVGYVD
 DTQFVRFDSD AASPRMEPRA PWVEQEGPEY WDEETRKAKA NAQIDRVDLQ
 TLRGYYNQTD AGSHTIQWMS GCDVGPDGRL LRGYRQDAYD GKDYIALNED
 LRSWTAADVA AQITQRKWEA ANVAERRRAY LEGTCVEWLR RYLENGKETL
 QRAEPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEDQTQDME
 LIETRPAGDR TFQKWAAVVV LSGEEHRYTC HVQHEGLPEP LTLRWEPSSQ
 PTIPIMGIVA ALAILGALAG AVVAAVMWRK KSSDKKGGSY SQAARSESAQ
 GSDVSLTACK VX*   
>DL;IPD:MHC04986
IPD:MHC04986 Caja-G*12:03  bases
>DL;IPD:MHC05053
IPD:MHC05053 Caja-G*12:03:01 365 bases
 MTVMAPRTLL LLLSGALALT ETWAGSHSMR YFHTAMSRPG RGEPRFIIVG
 YVDDTQFVRF DSDAASPRME PRAPWVEQEG PEYWDEETRK AKANAQIDRV
 DLQTLRGYYN QTDAGSHTIQ WMSGCDVGPD GRLLRGYRQD AYDGKDYIAL
 NEDLRSWTAA DVAAQITQRK WEAANVAERR RAYLEGTCVE WLRRYLENGK
 ETLQRAEPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DMELIETRPA GDRTFQKWAA VVVLSGEEHR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIMG IVAALAILGA LAGAVVAAVM WRKKSSDKKG GSYSQAARSE
 SAQGSDVSLT ACKVX*   
>DL;IPD:MHC05031
IPD:MHC05031 Caja-G*12:03:02 290 bases
 RTLLLLLSGA LALTETWAGS HSMRYFHTAM SRPGRGEPRF IIVGYVDDTQ
 FVRFDSDAAS PRMEPRAPWV EQEGPEYWDE ETRKAKANAQ IDRVDLQTLR
 GYYNQTDAGS HTIQWMSGCD VGPDGRLLRG YRQDAYDGKD YIALNEDLRS
 WTAADVAAQI TQRKWEAANV AERRRAYLEG TCVEWLRRYL ENGKETLQRA
 EPPKTHVTHH PVSDHEATLR CWALGFYPAE ITLTWQRDGE DQTQDMELIE
 TRPAGDRTFQ KWAAVVVLSG EEHRYTCHVQ HEGLPEPLTL *
>DL;IPD:MHC04989
IPD:MHC04989 Caja-G*12:04 344 bases
 LLLLSGALAL TETWAGSHSM RYFHTAMSRP GRGEPRFIIV GYVDDTQFVR
 FDSDAASPRM EPRAPWVEQE GPEYWDEETR KAKANAQIDR VDLQTLRGYY
 NQTDAGSHTI QWMSGCDVGP DGRLLRGYRQ DAYDGKDYIA LNEDLRSWTA
 ADVAAQITQR KWEAANVAER RRAYLEGTRV EWLRRYLENG KETLQRAEPP
 KTHVTHHPVS DHEATLRCWA LGFYPAEITL TWQRDGEDQT QDMELIETRP
 AGDRTFQKWA AVVVLSGEEH RYTCHVQHEG LPEPLTLRWE PSSQPTIPIM
 GIVAALAILG ALAGAVVAAV MWRKKSSDKK GGSYSQAARS ESAQ*
>DL;IPD:MHC05007
IPD:MHC05007 Caja-G*13:01 362 bases
 MAPRTLLLLL SGALALTETW AGSHSMRYFH TAMSRPGRGE PRFIIVGYVD
 DTQFVRFDSD AASPRMEPRA PWVEQEGPEY WDGETRKAKA NAQTDRVNLQ
 TLRGYYNQTD AGSHTIQWMY GCDVGPDGRL LRGYNQDAYD GKDYIALNED
 LRSWTAADVA AQITQRKWEA ANEAERRRAY LEGTCVEWLR RYLENGKETL
 QRAEPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEDQTQDME
 LIETRPAGDR TFQKWAAVVV LSGEEHRYTC HVQHEGLPEP LTLRWEPSSQ
 PTIPIMGIVA VLAILGALAG AVVAAVMWRK KSSDKKGGSY SQAARSESAQ
 GSDVSLTACK VX*   
>DL;IPD:MHC05012
IPD:MHC05012 Caja-G*13:02 365 bases
 MTVMAPRTLL LLLSGALALT ETWAGSHSMR YFHTAMSRPG RGEPRFIIVG
 YVDDTQFVRF DSDAASPRME PRAPWVEQEG PEYWEEETRT AKANAQIDRV
 NLRTLRGYYN QTDAGSHTIQ WMYGCDVGPD GRLLRGYRQY AYDGKDYIAL
 NEDLRSWTAA DVAAQITQRK WEAANVAERR RAYLEGTCVE WLRRYLENGK
 ETLQRAEPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DMELIETRPA GDRTFQKWAA VVVLSGEEHR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIMG IVAVLAILGA LAGAVVAAVM WRKKSSDKKG GSYSQAARSE
 SAQGSDVSLT ACKVX*   
>DL;IPD:MHC05049
IPD:MHC05049 Caja-G*13:03 365 bases
 MTVMAPRTLL LLLSGALALT ETWAGSHSMR YFHTAMSRPG RGEPRFIIVG
 YVDDTQFVRF DSDAASPRME PRAPWVEQEG PEYWDGETRK AKAHAQTDRV
 DLQTLRGYCN QTDAGSHTIQ WMYGCDVGPD GRLLRGYNQD AYDGKDYIAL
 NEDLRSWTAA DVAAQITQRK WEAANEAERR RAYLEGTCVE WLRRYLENGK
 ETLQRAEPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DMELVETRPA GDRTFQKWAA VVVPSGEEQR YTCHMQHEGL PEPLTLRWEP
 PSQPTIPIMG IVTALAILGT VAGAVVVAVM WRKKSSDKKG GSYSQAARSE
 SAQGSDVSLT ACKVX*   
>DL;IPD:MHC05095
IPD:MHC05095 Caja-G*13:04 365 bases
 MTVMAPRTLL LLLSGALALT ETWAGSHSMR YFHTAMSRPG RGEPRFIIVG
 YVDDTQFVRF DSDAASPRME PRAPWVEQEG PEYWDGETRK AKAHAQTDRV
 DLQTLRGYYN QTDAGSHTIQ WMYGCDVGPD GRLLRGYNQD AYDGKDYIAL
 NEDLRSWTAA DVAAQITQRK WEAANEAERR RAYLEGTCVE WLRRYLENGK
 ETLQRAEPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DMELIETRPA GDRTFQKWAA VVVLSGEEHR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIMG IVAVLAILGA LAGAVVAAVM WRKKSSDKKG GSYSQAARSE
 SAQGSDVSLT ACKVX*   
>DL;IPD:MHC05002
IPD:MHC05002 Caja-G*14:01 365 bases
 MTVMAPRTLL LLLSGALALT ETGAGSHSMR YFSTAVSRPG RGEPRYIEVG
 YVDDTQFVRF DSDAASPRME PRAPWVEQEG PEYWEEQTRK AKTHAQTDRV
 NLQTALGYYN QTDAGSHTIQ WMYGCDVGPD GRLLRGYWQD AYDGKDYIAL
 NEDLRSWTAA DVAAQITQRK WEAANEAERI RAYLEGTCLE WLHRYLENGK
 ETLQRAEPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DMELVETRPA GDRTFQKWAA VVVPSGEEQR YTCHMQHEGL PEPLTLRWEP
 PSQPTIPIMG IVTALAILGT VAGAVVVAVM WRKKSSDKKG GSYSQAARSE
 SAQGSDVSLT ACKVX*   
>DL;IPD:MHC05024
IPD:MHC05024 Caja-G*14:02 365 bases
 MTVMAPRTLL LLLSGALALT ETGAGSHSMR YFSTAVSRPG RGEPRYIEVG
 YVDDTQFVRF DSDAASPRME PRAPWVEQEG PEYWEEQTRN AKTHAQTDRV
 NLQTALGYYN QTDAGSHTIQ WMYGCDVGPD GRLLRGYWQD AYDGKDYIAL
 NEDLRSWTAA DVAAQITQRK WEAANEAERI RAYLEGTCLE WLHRYLENGK
 ETLQRAEPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DMELVETRPA GDRTFQKWAA VVVPSGEEQR YTCHMQHEGL PEPLTLRWEP
 PSQPTIPIMG IVTALAILGT VAGAVVVAVM WRKKSSDKKG GSYSQAARSE
 SAQGSDVSLT ACKVX*   
>DL;IPD:MHC00120
IPD:MHC00120 Caja-G*15:01 330 bases
 LLLLLSGALA LTETWAGSHS MRYFSTAVSR PGREEPRFIS VGYVDDTQFV
 RFDSDAAIPR DEPRAPWVEQ EGPEYWEEQT RRAKAHAQTD RVNLRTLRGY
 YNQTEAGSHT IQWMYGCNVG PDRRLLRGYD QYAYDGKDYI ALNEDLRSWT
 AADVAAQITQ RKWEAANEAE RRRAYLEGTC VEWLHRYLEN GKETLQRAEP
 PKTHVTHHPV SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDMELVETR
 PAGDRTFQKW AAVVVLSGEE HRYTCHVQHE GLPEPLTLRW EPSSQPTIPI
 MGIVAALAVL GAVAGAVVAA VMWRKKSSDK * 
>DL;IPD:MHC05006
IPD:MHC05006 Caja-G*15:02 365 bases
 MTVMASRTLL LLLSGALALT ETWAGSHSMR YFSTAVSRPG REEPRFISVG
 YVDDTQFVRF DSDAAIPRDE PRAPWVEQEG PEYWEEQTRR AKAHAQTDRV
 NLRTLRGYYN QTEAGSHTIQ WMYGCDVGPD RRLLRGYDQY AYDGKDYIAL
 NEDLRSWTAA DVAAQITQRK WEAANEAERR RAYLEGTCVE WLHRYLENGK
 ETLQRAEPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DMELVETRPA GDRTFQKWAA VVVLSGEEHR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIMG IVAALAVLGA VAGAVVAAVM WRKKSSDKKG GSYSQAARSE
 SAQGSDVSLT ACKVX*   
>DL;IPD:MHC05018
IPD:MHC05018 Caja-G*16:01 365 bases
 MTVMAPRTLL LLLSGALALT ETWAGSHSMR YFGTAVSRPG RGEPRYIIVG
 YVDDTQFVRF DSDAASPRME PRAPWVEQEG PEYWDEETRK AKAIAQIDRV
 DLQTLRGYYN QSDAGSHTIQ WMYGCDVGPD GRLLRGYRQD AYDGKDYIAL
 NEDLRSWTAA DVAAQITQRK WEAANVAEEW RAYLEGTCLE WLRRYLENGK
 ETLQRAEPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DMELIETRPA GDRTFQKWAA VVVLSGEEHR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIMG IVAALAILGA LAGAVVAAVM WRKKSSDKKG GSYSQAARSE
 SAQGSDVSLT ACKVX*   
>DL;IPD:MHC04991
IPD:MHC04991 Caja-G*17:01 344 bases
 LLLLSGALAL TETGAGSHSM RYFHTAMSRP GRGEPRFIYV GYVDDTQFVR
 FDSDAASPRM EPRAPWVEQE GPEYWDEETR KAKANAQIDR VDLRTLRGYY
 NQTDAGSHTI QWMYGCDVGP DGRLLRGYWQ DAYDGKDYIA LNEDLRSWTA
 ADVAAQITQR KWEAANEAER MRAYLEGTCV EWLRRYLENG KETPQRAEPP
 KTHVTHHPVS DHEATLRCWA LGFYPAEITL TWQRDGEDQT QDMELIETRP
 AGDRTFQKWA AVVVLSGEEH RYTCHVQHEG LPEPLTLRWE PSSQPTIPIM
 GIVAALAILG ALAGAVVAAV MWRKKSSDKK GGSYSQAARS ESAQ*
>DL;IPD:MHC05054
IPD:MHC05054 Caja-G*17:02 365 bases
 MTVLAPRTLL LLLSGALALT ETGAGSHSMR YFHTAMSRPG RGEPRFIYVG
 YVDDTQFVRF DSDAASPRME PRAPWVEQEG PEYWDEETRK AKANAQIDRV
 DLRTLRGYYN QTDAGSHTIQ WMYGCDVGPD GRLLRGYWQD AYDGKDYIAL
 NEDLRSWTAA DVAAQITQRK WEAANEAERM RAYLEGTCVE WLRRYLENGK
 ETLQRAEPPK THVTHHPVSD HEATLRCWAL GFYPAEIALT WQRDGEDQTQ
 DMELIETRPA GDRTFQKWAA VVVLSGEEHR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIMG IVAALAILGA LAGAVVAAVM WRKKSSDKKG GSYSQAARSE
 SAQGSDVSLT ACKVX*   
>DL;IPD:MHC04988
IPD:MHC04988 Caja-G*18:01 348 bases
 LLLLSGTLAL TQTRAGSHSL RYLHISVSRP GRGEPRFITV GYVDDTQFVR
 FDSDAASPRK EPRAPWMEQE GPEYWDRETL ISKQNAQTYR VNLRTLRGYY
 NQTEAGSHTI QRMYGCDVGP DGRLLRGYNQ DAHDGKDYIA LNEDLRSWTA
 ADVAAQITQR KWEAANVAER RRAYLEGTCV EWLRRYLENG KETLQRAVPP
 KTHVTHHPVS DDEATLRCWT LGFYPAEITL TRQRDGEDQT QDMELVETRP
 TGDGNFQKWA AVVVPSGEEQ RYTCHVQHEG LPEPLTLRWE PPSQPTIPIV
 GIIAGLVAFG AVVTGAVVAA VMCRKKSSDK KGGSYSQAAS SDSAQGSD*
>DL;IPD:MHC04993
IPD:MHC04993 Caja-G*18:02 348 bases
 LLLLSGTLAL TQTRAGSHSL RYFHISVSRP GRGEPRFITV GYVDDTQFVR
 FDSDAASPRK EPRAPWMEQE GPEYWDRETL ISKQNAQTYR VGLRTLRGYY
 NQTEAGSHTI QRMSGCDVGP DGRLLRGYDQ FAYDGKDYIA LNEDLRSWTA
 ADVAAQITQR KWEAANEAER MRAYLEGTCV EWLRRYLENG KETLQRAVPP
 KTHVTHHPVS DDEATLRCWT LGFYPAEITL TWQRDGEDQT QDMELVETRP
 TGDGNFQKWA AVVVPSGEEQ RYTCHVQHEG LPEPLTLRWE PPSQPTIPIV
 GIIAGLVAFG AVVTGAVVAA VMCRKKSSDK KGGSYSQAAS SDSAQGSD*
>DL;IPD:MHC05035
IPD:MHC05035 Caja-G*18:03 290 bases
 RTLLLLLSGT LALTQTRAGS HSLRYFHISV SRPGRGEPRF ITVGYVDDTQ
 FVRFDSDAAS PRKEPRAPWM EQEGPEYWDR ETLISKQNAQ TYRVNLRTLR
 GYYNQTEAGS HTIQRMYGCD VGPDGRLLRG YNQDAYDGKD YIALNEDLRS
 WTAADVAAQI TQRKWEAANV AERRRAYLEG TCVEWLRRYL ENGKETLQRA
 VPPKTHVTHH PVSDDEATLR CWTLGFYPAE ITLTWQRDGE DQTQDMELVE
 TRPTGDGNFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPLTL *
>DL;IPD:MHC05029
IPD:MHC05029 Caja-G*18:04 290 bases
 RTLLLLLSGT LALTQTRAGS HSLRYFHTSV SRPRREEPRF ITVGYVDDTQ
 FVRFDSDAAS PRKEPRAPWM EQEGPEYWDR ETLISKQNAQ TYRVNLRTLR
 GYYNQTEAGS HTIQLMYGCD VGPDGRLLRG YNQFAYDGKD YIALNEDLRS
 WTAADVAAQI TQRKWEAANV AEEWRAYLEG TCVEGLRRYL KNGKETLQRA
 VPPKTHVTHH PVSDDEATLR CWTLGFYPAE ITLTWQRDGE DQTQDMELVE
 TRPTGDGNFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPLTL *
>DL;IPD:MHC05004
IPD:MHC05004 Caja-G*19:01 362 bases
 MASRTLLLLL SGALALTETG AGSHSMRYFS TAVSRPGRRE PRYIEVGYVD
 DTQFVRFDSD AASPRMEPRA PWVEQEGPEY WDEETRKAKT HAQTFRGNLQ
 TLRGYYNQTE AGSHTIQWMS GCDVGPDARL LRGYDQHAYD GKDYIALNED
 LRSWTAADLA AQITQRKWEA ANVAEEWRAY LEGRCLEWLH RYLENGKETL
 QRAEPPKTHV THHPVSDHEA TLRCWALGFY PSEITLTWQR DGEDQTQDME
 LVETRPAGDR TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP LTLRWEPPSQ
 PTIPIMGIVA ALAILGTVAG AVVVAVMWRK KSSDKKGGSY SQAARSESAQ
 GSDVSLTACK VX*   
>DL;IPD:MHC05099
IPD:MHC05099 Caja-G*19:02 365 bases
 MTVMASRTLL LLLSGALALT ETGAGSHSMR YFSTAVSRPG RREPRYIEVG
 YVDDTQFVRF DSDAASPRME PRAPWVEQEG PEYWDEETRK AKTHAQTFRG
 NLQTLRGYYN QTEAGSHTIQ WMSGCDVGPD ARLLRGYDQH AYDGKDYIAL
 NEDLRSWAAA DLAAQITQRK WEAANVAEEW RAYLEGRCLE WLHRYLENGK
 ETLQRAEPPK THVTHHPVSD HEATLRCWAL GFYPSEITLT WQRDGEDQTQ
 DMELVETRPA GDRTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 PSQPTIPIMG IVAALAILGT VAGAVVVAVM WRKKSSDKKG GSYSQAARSE
 SAQGSDVSLT ACKVX*   
>DL;IPD:MHC05027
IPD:MHC05027 Caja-G*20:01 362 bases
 MAPRTLLLLL SGALALTETW AGSHSMRYFH TAVVRPGRGE PRFIYVGYVD
 DTQFVRFDSD AASPRMEPRA PWVEQEGPEY WEEQTRRAKA NAQIDRGNLQ
 TLRGYYNQTD AGSHTIQVMY GCDVGPDGRL LRGYRQDAYD GKDYIALNED
 LRSWTAADVA AQITQRKWEA ANEAERMRAY LEGTCVEWLH RYLENGKETL
 QRAEPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEDQTQDME
 LVETRPAGDR TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP LTLRWEPPSQ
 PTIPIMGLVT ALAILGTVAG AVVVAVMWRK KRSDKKGGSY SQAARSESAQ
 GSDVSLTACK VX*   
>DL;IPD:MHC05050
IPD:MHC05050 Caja-G*21:01 365 bases
 MTVMAPRTLL LLLSGALALT ETGAGSHSMR YFSTAVSRPG RGEPRYIEVG
 YVDDTQFVRF DSDAASPRME PRAPWVEQEG PEYWDGETRK AKANAQIDRV
 DLQTLRGYYN QTDAGSHTIQ WMSGCDVGPD GRLLRGYRQD AYDGKDYIAL
 NEDLRSWTAA DVAAQITQRK WEAANVAERR RAYLEGTCVE WLRRYLENGK
 ETLQRAEPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DMELIETRPA GDRTFQKWAA VVVLSGEEHR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIMG IVAVLAILGA LAGAVVAAVM WRKKSSDKEG GSYSQAARSE
 SAQGSDVSLT ACKVX*   
>DL;IPD:MHC05097
IPD:MHC05097 Caja-G*22:01 365 bases
 MTVMAPRTLL LLLSGALALT ETWAGSHSMR YFHTAMSRPG RGEPRFIIVG
 YVDDTQFVRF DSDAASPRME PRAPWVEQEG PEYWDEETRK AKANAQIDRV
 DLQTLRGYYN QTDAGSHTIQ WMSGCDVGPD GRLLRGYRQD AYDGKDYIAL
 NEDLRSWTAA DVAAQITQRK WEAANEAERM RAYLEGTCLE WLHRYLENGK
 ETLQRAEPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DMELVETRPA GDRTFQKWAA VVVPSGEEQR YTCHMQHEGL PEPLTLRWEP
 PPQPTIPIMG IVTALAILGT VAGAVVVAVM WRKKSSDKKG GSYSQAARSE
 SAQGSDVSLT ACKVX*   
