>DL;IPD:MHC00087
IPD:MHC00087 Caja-DQB1*22:01:01 246 bases
 TACCAGGTTA AGGGCATGTG CTACTTCAGG AACGGGACGG AGCGCGTGCC
 GCTTGTGACC CGATTCATCT ATAACCGAGA GGAGTACCTG CGCTTCGACA
 GCGACGTGGG GGAGTACCTG CCGGTGACGC CGCTGGGGCC GCCGGATGCT
 GAGTACTTGA ACAGCCAGAA GGACTTACTG GACAGGACCC GGGCGGAGCT
 GGACACGGTG TGCAGACACA ACTACCAGCT GGAGTTCCCG CGATCT*
>DL;IPD:MHC00088
IPD:MHC00088 Caja-DQB1*22:01:02 246 bases
 TACCAGGTTA AGGGCATGTG CTACTTCAGG AACGGGACGG AGCGCGTGCC
 GCTTGTGACC CGATTCATCT ATAACCGAGA GGAGTACCTG CGCTTCGACA
 GCGACGTGGG GGAGTACCTG CCGGTGACGC CGCTGGGGCC GCCCGATGCT
 GAGTACTTGA ACAGCCAGAA GGACTTACTG GACAGGACCC GGGCGGAGCT
 GGACACGGTG TGCAGACACA ACTACCAGCT GGAGTTCCCG CGATCT*
>DL;IPD:MHC00089
IPD:MHC00089 Caja-DQB1*23:01 246 bases
 TACCAGTTTA AGGGTTTCTG CTACTTCACC AACGGGACAG AGAGCGTGCG
 TCTTGTGACA GAATACGTCT ATAACCGAGA GGAGTACGTG CGCTTCGACA
 GCGACGTGGG GGAGTATTGG GCGGTGACGC CGCTGGGGCT GCCTGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGAGCACCC GGGCGGAGCT
 GGACACGGTG TGCAGGCCCA ACTACGAGGT GGCGTTCCGC GGATCT*
>DL;IPD:MHC00090
IPD:MHC00090 Caja-DQB1*23:02 246 bases
 TACCAGTTTA AGTTTCTCTG CTACTTCACC AACGGGACAG AGCGCGTGCG
 TCTTGTGACA GAATACGTCT ATAACAGAGA GGAGCACGTG CGCTTCGACA
 GCGACGTGGG GGAGTATTGG GCGGTGACGC CGCAGGGGCT GCCTGACGCC
 AAGTACTGGA ACAGCCAGAA GGACATCCTG GAGAGGACCC GGGCGGAGCT
 GGACACGGTG TGCAGGCACA ACTACGAGGT GGCGTTCCGC GGATCT*
>DL;IPD:MHC00091
IPD:MHC00091 Caja-DQB2*01:01 243 bases
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACGG AGCGCGTGCG
 GGGTGTGGCC AGATACATCT ATAACCGCGA GGAGTACGCG CGCTTCGACA
 GCGACGTGGG GGAGTTCCGG GCGGTGACCG AGCTGGGGCG GACGACCGAG
 GACTGGAACA ACTATAAGGA CTTCTTGGAG CAGGAGCGGG CCGGCGTGTA
 CACGGTGTGC AGACACAACT ACGAGGCGGA GCTCCGCACG ACC*
>DL;IPD:MHC00092
IPD:MHC00092 Caja-DQB2*01:02 243 bases
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACGG AGCGCGTGCG
 GGGTGTGGCC AGATACATCT ATAACCGCGA GGAGTACGCG CGCTTCGACA
 GCGACGTGGG GGAGTTCCGG GCGATGACCG AGCTGGGGCG GACGACCGAG
 GACTGGAACA ACTATAAGGA CTTCTTGGAG CAGGAGCGGG CCGCGGTGTA
 CACGGTGTGC AGACACAACT ACGAGGCGGA GCTCCGCACG ACC*
