>DL;IPD:MHC05046
IPD:MHC05046 Caja-B*01:01 352 bases
 MEPRSRLLLL SGALALTETW PSSHSLRYFS TTVSRPGGGE PRYFSVGYVD
 DTQFLRFDSD AAIPKTEPRA PWAEQEGPEY WDLLTRRTEA CAQACRVSLR
 DIRGYYNQSE AGSHTLQVLF GCDLWPDGHL LLGYCRIAYD GKDHVALNED
 LRSWTAADTV AEFTQRKLEE EKYAEQLRAQ LEGECVEMLK RYLENGKETL
 QRAKPPKTHV THHPISNQEV TLRCWALGFY PAEVTLTWQR DGEDQTQDTE
 LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLLEP LSLRWEPSSQ
 PTIPIMGIIA GLAVLAAVVT GAVVTAVMWR RKSSGSDSAQ GSDVSLRACK
 VX*    
>DL;IPD:MHC05048
IPD:MHC05048 Caja-B*01:02 323 bases
 MEPRSRLLLL SGALALTETW PSSHSLKYFS TTVSRPGGGE PRYFSVGYVD
 DTQFLRFDSD AEIPKTEPRA PWAEQEGPEY WDLLTRRTEA CAQACRVSLR
 DIRGYYNQSE AGSHTLQVLF GCDLWPDGHL LLGYCRIAYD GKDHVALNED
 LRSWTAADTV AEFTQRKLEE EKYAEQLRAQ LEGECVEMLK RYLENGKETL
 QRAEVTLTWQ RDGENQTQDT ELVETRPAGD GTFQKWAAVV VPSGEEQRYT
 CHVQHEGLLE PLSLRWEPSS QPTIPIMGII AGLAVLAAVV TGAVVTAVMW
 RRKSSGSDSA QGSDVSLRAC KVX*  
>DL;IPD:MHC05093
IPD:MHC05093 Caja-B*02:01 362 bases
 MAPRILLLLS GALALTKTSA SSHSFSRFLT TVSRPGRGEP RHIAVGYVDD
 TQFMRFDSDA AIPRMEPRAP WAEQEGPEYW DLLTRRTEAC AQACRVSLQI
 IRGHYNQSEA GSHTLQVLFG CDLGPDGRLL RGYCRIAYDG KDHVALNEDL
 RSWTAADTAA QVTQRKLEAE KYAERLRAQL EGECVGMLKR FLENGKETLE
 RAEPPKTRVT HHPINDHEAT LRCWALGFYP AEITLTWQRD GEDQTQDTEL
 VETRPAGDGT FQKWAAMVVP SGEEQRYTCH VQHEGLPEPL TLRWEPPSQP
 TTPIVSIVAG LVVLAAVVTG AVVSAAMWKR KSSGGKQGSY SQATCSDSAR
 GSDVSLTVCK VX*   
>DL;IPD:MHC05045
IPD:MHC05045 Caja-B*03:01 352 bases
 MAPRTLLLLL SAAMALTETW AGSHSLRYFQ TAVSRSGSRE PHFFAVGYVD
 DTQFERFDSD AAIPRGEPRT PWMELEGPEY WDLQTRTLKA RAQTNQVCLR
 TLRGYYNQSE AGSHIYQRMY GCDLGPDGRL LRGYDKRAYD GKDYLALNED
 LRSWTAADRA AQVTQRKFEA AHEAEKMKAY LEGTCVESLR RYLENGKERL
 QRADPPKTHV AHHPISDQEA TLRCWALGFY PAEITLTWQR DGEDQTQDTE
 FVETRPSGDG TFQKWVAVVV PSGEEQRYTC HVQHEGLLEP LTLRWEPSSQ
 PTIHIMGIIA GLAVLGAVVT GAVVTAVIWR SLSSGSDSTQ GSDVSLTTCK
 AX*    
>DL;IPD:MHC04378
IPD:MHC04378 Caja-B1*01:01 363 bases
 MAPQTLLLLL SGALALTQTL EGSHSLTYFY TAVSRPGLGK PSFIAVGYVD
 DTQFERFHSD AASPRMDPRA LWMEQEGPEY WDRETTSLKA DAQISEMCVR
 ILSGHYNQSE TRSHTFQRMY GCEVGPDGRF LRGYDKRAYD GKDHVALNED
 LRSWTAAVRE AQISLGWLEA NNVAERMRAY LEGECVELLR RHLENGKETL
 QRADPPKTHV THHPVSDHEA TLRCWALGFY PADITLTWQR DGEDQIQDME
 LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHKGLLEP LTLRWEPSSQ
 PTIPIVGIVA GLAVLGAVIT GAVVIAVMLR RKSSGGKRGS YSQAACSDSA
 QGSDVSLRAC KAX*   
>DL;IPD:MHC04383
IPD:MHC04383 Caja-B2*01:01Ps 149 bases
 VVPRTLLLLL SGTLDLTETR AGSHSLRYFG TALSRPGYGE PCFIAVGYVD
 DTQFVGFDSD AESPRMEPRE PWVEQEGQEY WDRETRRAMA KAQTFRGNLR
 ILRGYYNQSD YRSHTIQGMI GCDVGPDGSF LLGYLQFAYD GKDYISMNX*
>DL;IPD:MHC04379
IPD:MHC04379 Caja-B3*01:01 363 bases
 MEPRSLLLLL SGALALTETW ASSHSPRYFS TTVSRPGGGE PRYFSVGYVD
 DTQFLRFDSD AEIPKTEPRA PWAEQEGPEY WDLLTRRTEA CAQACRVSLR
 DIRGYYNQSE AGSHTLQVLF GCDLGPDGRL LLGYCRIAYD GKDHVALNED
 LRSWTAADMV AEFTQRKLEA ENYAEQLRAQ LEGECVEMLK RYLENGKETL
 QRAEPPKTHV THHPISNQEV TLRCWALGFY PAEVTLTWQR DGEDQTQDTE
 LVETRPAGDG NFQKWAAVVV PSGEEQRYTC HVQHEGLLEP LSLRWEPSSQ
 PTIPIMGIIA GLAVLVAVVI GAVVTAVMWR RKSSGRKGGS YSQAACSDSA
 QGSDVSLRAC KAX*   
>DL;IPD:MHC05047
IPD:MHC05047 Caja-B3*01:02 363 bases
 MEPRSLLLLL SGALALTETW ASSHSPRYFS TTVSRPGGGE PRYFSVGYVD
 DTQFLRFDSD AEIPKTEPRA PWAEQEGPEY WDLLTRRTEA CAQACRVSLR
 DIRGYYNQSE AGSHTLQVLF GCDLGPDGRL LLGYCRIAYD GKDHVALNED
 LRSWTAADMV AEFTQRKLEA ENYAEQLRAQ LEGECVEMLK RYLENGKETL
 QRAEPPKTHV THHPISNQEV TLRCWALGFY PAEVALTWQR DGEDQTQDTE
 LVETRPAGDG NFQKWAAVVV PSGEEQRYTC HVQHEGLLEP LSLRWEPSSQ
 PTIPIMGIIA GLAVLVAVVI GAVVTAVMWR RKSSGGKGGS YSQAACSDSA
 QGSDVSLRAC KAX*   
>DL;IPD:MHC04380
IPD:MHC04380 Caja-B4*01:01 366 bases
 MAVLAPRTLL LLLLGALAQT KTWAGSHFMR YFHIAVSRPG RGEPRYLEVG
 YVDDTQFVRF DSDAARPRME PRAPWVEQEG PEYWEEETQR AKDVAQTFRV
 NLQTLRGYYN QSGAGSHTLQ LMYRCYLGPD WSLLRGYLQF AYDAKDYISL
 NHDLSSWTAA DTAAQITQRK WEAANVAEEW RAYMEGTCLE WLRRHLKNGK
 ETLQRADPPK THVTHHPISD HEAILRCWAM GFYAAEITLT WQRDGEDQTQ
 DMELVETRPA GDGNFQKWAA VVVPSGEEQR YMCHVQHEGL LEPLTLRWEP
 SSQLTISIVG IVAGLVVLGA VVIGAMVTAV MWRKKSSGGE RGSYSQAVCS
 DSTQGSDVSL MACKAX*   
>DL;IPD:MHC04384
IPD:MHC04384 Caja-B5*01:01Ps 169 bases
 MAPRILLLLL SGALVLIKTW AGSHYMRYFC TAVSWPGRGE PRFISAGYVD
 DTQFVRFDSD AASGRGEPRA PWMEQEGPEY WDRETLTLRA SAQTHRGNLR
 TLRGYYNQSE AGSHTLQTTY GCDLGPDGRL FRGYYQHAYD DKDYIALNED
 LRSWTAADTA AQITQRKLX*   
>DL;IPD:MHC04381
IPD:MHC04381 Caja-B6*01:01 363 bases
 MAPRTLLLLL SGTLALTKTS ASSHSLYGFF STVSRPGRGE PRFIGVGYVD
 DTQFMRFDSD AAVPRMEPRA PWAEQEGPEY WDGLTRRAKA CAQACRVSLR
 DIRGYYNQSE AGSHTLQVLY GCDLGPDGRL LLGYYRIAYD GKDHVTLNED
 LRSWTAADTV AEFTQRKLEA EKYAEQLRAE LQGECVERLK RFLENGKEKL
 QRAEPPKTHV THHSITDHEA TLRCWALGFY PAEITLTWQR DGEEQTQDTE
 LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP LSLRWEPPSQ
 PIIPIVSIVA GLAVLASVVT GAVVTAVMWR RKSSGGKGGS YSQAAGSDSA
 QGSDVSLTVC KAX*   
>DL;IPD:MHC04382
IPD:MHC04382 Caja-B7*01:01 363 bases
 MEPRSRLLLL SGALALTETW PSSHSLRYFS TTVSRPGGGE PRYFSVGYVD
 DTQFLRFDSD AAIPKTEPRA PWAEQEGPEY WDLLTRRTEA CAQACRVSLR
 DIRGYYNQSE AGSHTLQVLF GCDLWPDGHL LLGYCRIAYD GKDHVALNED
 LRSWTAADTV AEFTQRKLEA EKYAEQLRAQ LEGECVEMLK RYLENGKETL
 QRAEPPKTHV THHPISNQEV TLRCWALGFY PAEVTLTWQR DGEDQTQDTE
 LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLLEP LSLRWEPSSQ
 PTIPIMGIIA GLAVLAAVVT GAVVTAVMWR RKSSGGKGGS YSQAACSDSA
 QGSDVSLRAC KVX*   
>DL;IPD:MHC04385
IPD:MHC04385 Caja-B8*01:01Ps 137 bases
 MEVVEPRTLL LLLSRSVTLT QTWAGSHSLR YFHTAVSRPS RLEPHFISVG
 YVDHTQFVQF DSYAVIPRME PRAPWMEQEG PEYWEEQTRT LKVRALIHRV
 SVRTLLRYYN QSEAGSRPPG DVWLRPGVRR APPPGVX* 
>DL;IPD:MHC04386
IPD:MHC04386 Caja-B9*01:01Ps 76 bases
 MTVMAPRTLL LLLSGALALI QTRAGSHSLR YFHTAVSRPG RGEPRYIEVG
 YVDDTQFVRF DSYAANPGWS RGSCGX*  
