>DL;IPD:MHC00100
IPD:MHC00100 Caja-DRB*W12:01 258 bases
 SYIAALTVTL MALSSPLALA GDSPPRFLEQ FKYECLHLNG TEGVRLLVRY
 IYNQEEYVRF DSDVGEFRAV TELGRPAAEY FNSLKDYMEQ TRAAVDTVCR
 HNYGIFERFL VQRRVQPKVT VYPAKTQPLQ RHNLLVCSVS GFYPGSIEVR
 WFRNDQEEKT GVVSTGLIHN GDWTFQTLVM LETLPQSGEV YICQVEHPSV
 TSPLTVQWRA QSESAQSKML SGVGGSVLGL LFLGAGLFIY FRNQKGHSAL
 RPSGVLSX*    
>DL;IPD:MHC01561
IPD:MHC01561 Caja-DRB*W12:02 258 bases
 SYIAALTVTL MALSSPLALA GDSPPRFLEQ FKYECLHLNG TEGVRLLVRY
 IYNQEEYVRF DSDVGEFRAV TELGRPAAEY FNSLKDYMEQ TRAAVDTVCR
 HNYGIFERFL VQRRVQPKVT VYPAKTQPLQ RHNLLVCSVS GFYPGSIEVR
 WFRNDQEEKT GVVSTGLIHN GDWTFQTLVM LETLPQSGEV YICQVEHPSV
 TSPLTVQWRA QSESAQSKML SGVGGFVLGL LFLGAGLFIY FRNQKGHSAL
 RPSGVVSX*    
>DL;IPD:MHC00101
IPD:MHC00101 Caja-DRB*W16:01 266 bases
 MVCLRFPGGS CVAALTVTLM VLSSPLALAG DTRPRYLEQV KFECHHFNGT
 ERVRYLERYF YNQEEYVRFD SDVGEYRAVT ELGRPDAEYW NSQKDILEQK
 RAAVDRCRHN YEGFETFLVP RRVQPKVTVY PAKTQPLQHH NLLVCSVSGF
 YPGSIEVRWF RNDQEEKAGV VSTGLIQNGD WTFQTLVMLE TVPQSGEVYI
 CQVEHPSVTS PLTVQWRAQS ESAQSKMLSG VGGFVLGLLF LGAGLFIYFR
 NQKGRSGLQP TGLLSX*   
>DL;IPD:MHC00102
IPD:MHC00102 Caja-DRB*W16:04 88 bases
 RYLEQAKCEC HHFNGTERVR YLERYFYNQE ENLRFDSDVG EYRAVTELGR
 PDAEYWNSQK DILEQKRAAV DRCRHNYEIS ERFLVPRR* 
>DL;IPD:MHC00103
IPD:MHC00103 Caja-DRB*W16:05 267 bases
 MVCLRFPGGS CVAALTVTLM VLSSPLALAG DTRPRYLEQV KFECHHFNGT
 ERVRLLERRI HNQEEYARFD SDVGEYRAVT ELGRPDAEYW NSQKDLLEQR
 RAAVDTYCRH NYEILDRFLV PRRVQPKVTV YPAKTQPLQH HNLLVCSVSG
 FYPGSIEVRW FRNDQEEKAG VVSTGLIQNG DWTFQTLVML ETVPQSGEVY
 ICQVEHPSVT SPLTVQWRAW SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGRSGLQ PTGLLSX*   
>DL;IPD:MHC00104
IPD:MHC00104 Caja-DRB*W16:06 267 bases
 MVCLRFPGGS CVAALTVTLM VLSSPLALAG DTRPRFLEQV KYECHHFNGT
 ERVRFLFRDI YNQEEVLRFD SDVGEFRAVT ELGRPDAEYW NSQKDILEDR
 RAAVDTVCRH NYEILDRFLV PRRVQPKVTV YPAKTQPLQH HNLLVCSVSG
 FYPGSIEVRW FRNDQEEKAG VVSTGLIQNG DWTFQTLVML ETLPQSGEVY
 TCQVEHPSVT SPLTVQWRAQ SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGRSGLQ PTGLLSX*   
>DL;IPD:MHC00105
IPD:MHC00105 Caja-DRB*W16:07 89 bases
 RFLEQVKYEC HHFNGTERVR FLFRDIYNQE EVLRFDSDVW EFRAVTELGR
 PDAEYWNSQK DILEDRRAAV DTVCRHNYEI LDRFLVPRR* 
>DL;IPD:MHC00106
IPD:MHC00106 Caja-DRB*W16:08 266 bases
 MVCLRFPGGS CVAALTVTLM VLSSPLALAG DTRPRYLEQH KAECHHFNGT
 ERVRFLDRYF YNQEEVLRFD SDVGEYRAVT ELGRPSAEKL NSQKDILEQT
 RAEVDRCRHN YEIFETFLVP RRVQPKVTVY PAKTQPLQRH NLLVCSVSGF
 YPGSIEVRWF RNDQEEKAGV VSTGLIQNGD WTFQTLVMLE TVPQSGEVYI
 CQVEHPSVTS PLTVQWRAQS ESAQSKMLSG VGGFVLGLLF LGAGLFIYFR
 NQKGRSGLQP TGLLSX*   
>DL;IPD:MHC00107
IPD:MHC00107 Caja-DRB*W16:09 266 bases
 MVCLRFPGGS CVAALTVTLM VLSSPLALAG DTRPRYLEQA KCECHHFNGT
 ERVRYLERYF YNQEEYVRFD SDVGEYRAVT ELGRPDAEYW NSQKDILEQK
 RAEVDRCRHN YEVSERFLVP RRVQPKVTVY PAKTQPLQHH NLLVCSVSGF
 YPGSIEVRWF RNDQEEKAGV VSTGLIQNGD WTFQTLVMLE TVPQSGEVYI
 CQVEHPSVTS PLTVQWRAQS ESAQSKMLSG VGGFVLGLLF LGAGLFIYFR
 NQKGRSGLQP TGLLSX*   
>DL;IPD:MHC00108
IPD:MHC00108 Caja-DRB*W16:10 266 bases
 MVCLRFPGGS CVAALTVTLM VLSSPLALAG DTRPRYLEQA KCECHHFNGT
 ERVRYLERYF YNQEEYVRFD SDVGEYRAVT ELGRPDAEYW NSQKDILEQK
 RAAVDRCRHN YEVSETFLVP RRVQPKVTVY PAKTQPLQHH NLLVCSVSGF
 YPGSIEVRWF RNDQEEKAGV VSTGLIQNGD WTFQTLVMLE TVPQSGEVYI
 CQVEHPSVTS PLTVQWRAQS ESAQSKMLSG VGGFVLGLLF LGAGLFIYFR
 NQKGRSGLQP TGLLSX*   
>DL;IPD:MHC00109
IPD:MHC00109 Caja-DRB*W16:11 267 bases
 MVCLRFPGGS CVAALTVTLM VLSSPLALAG DTRPRYLEQR KAECHHFNGT
 ERVRLLERYF YNQEEFVRFD SDVGEFRAVT ELGRPVAESW NSRKDILEQR
 RAAVDTFCRH NYEGFETFLV PRRVQPKVTV YPAKTQPLQH HNLLVCSVSG
 FYPGSIEVRW FRNDQEEKAG VVSTGLIQNG DWTFQTLVML ETVPQSGEVY
 ICQVEHPSVT SPLTVQWRAQ SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGRSGLQ PTGLLSX*   
>DL;IPD:MHC00110
IPD:MHC00110 Caja-DRB*W16:12 267 bases
 MVCLRFPGGS CVAALTVTLM VLSSPLALAG DTRPRYLEQA KCECHHFNGT
 ERVRYLERYF YNQEELVRFD SDVGEYRAVT ELGRPSAEKL NSQKDLLEQR
 RAEVDTVCRH NYEISERFLV PRRVQPKVTV YPAKTQPLQH HNLLVCSVSG
 FYPGSIEVRW FRNDQEEKAG VVSTGLIQNG DWTFQTLVML ETVPQSGEVY
 ICQVEHPSVT SPLTVQWRAQ SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGRSGLQ PTGLLSX*   
>DL;IPD:MHC00111
IPD:MHC00111 Caja-DRB*W16:13 267 bases
 MVCLRFPGGS CVAALTVTLM VLSSPLALAG DTRPRYLEQV KFECHHFNGT
 ERVRLLERRI HNQEEYARFD SDVGEYRAVT ELGRPDAEYW NSQKDILEQR
 RAAVDTYCRH NYEILDRFLV PRRVQPKVTV YPAKTQPLQH HNLLVCSVSG
 FYPGSIEVRW FRNDQEEKAG VVSTGLIQNG DWTFQTLVML ETVPQSGEVY
 ICQVEHPSVT SPLTVQWRAW SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGRSGLQ PTGLLSX*   
>DL;IPD:MHC00112
IPD:MHC00112 Caja-DRB*W16:14 88 bases
 RYLEQAKCEC HHFNGTERVR YLERYFYNQE ELVRFDSDVG EYRAVTELGR
 PSAEKLNSQK DLLEQKRAEV DRCRHNYEVS ERFLVPRR* 
>DL;IPD:MHC00113
IPD:MHC00113 Caja-DRB*W16:15 89 bases
 RYLEQVKFEC HHFNGTERVR LLERRIHNQE EYARFDSDVG EYRAVTELGR
 PDAEYWNSQK DLLEQRRAEV DTYCRHNYEI SERFLVPRR* 
>DL;IPD:MHC01562
IPD:MHC01562 Caja-DRB*W16:16 267 bases
 MVCLRFPGGS CVAALTVTLM VLSSPLALAG DTRPRYLEQA KCECHHFNGT
 ERVRYLERYF YNQEEYVRFD SDVGEYRAVT ELGRPDAEYW NSQKDLLEQT
 RAEVDTVCRH NYEIFETFLV PRRVQPKVTV YPAKTQPLQH HNLLVCSVSG
 FYPGSIEVRW FRNDQEEKAG VVSTGLIQNG DWTFQTLVML ETVPQSGEVY
 ICQVEHPSVT SPLTVQWRAQ SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGRSGLQ PTGLLSX*   
>DL;IPD:MHC01567
IPD:MHC01567 Caja-DRB*W16:17 81 bases
 YLEQAKCECH HFNGTERVRY LERYFYNQEE YVRFDSDVGE YRAVTELGRP
 DAEYWNSQKD ILEQKRAAVD RCRHNYEIFE T* 
>DL;IPD:MHC01568
IPD:MHC01568 Caja-DRB*W16:18 76 bases
 VKFECHHFNG TERVRLLERR IHNQEEYARF DSDVGEYRAV TELGRPDAEY
 WNSQKDILEQ KRAEVDRCRH NYEVSE*  
>DL;IPD:MHC01563
IPD:MHC01563 Caja-DRB*W16:20 267 bases
 MVCLRFPGGS CVAALTVTLM VLSSPLALAG DTRPRYLEQA KCECHHFNGT
 ERVRYLERYF YNQEEYVRFD SDVGEYRAVT ELGRPDAEYW NSQKDLLEQT
 RAEVDTVCRH NYEGFETFLV PRRVQPKVTV YPAKTQPLQH HNLLVCSVSG
 FYPGSIEVRW FRNDQEEKAG VVSTGLIQNG DWTFQTLVML ETVPQSGEVY
 ICQVEHPSVT SPLTVQWRAQ SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGRSGLQ PTGLLSX*   
>DL;IPD:MHC01564
IPD:MHC01564 Caja-DRB*W16:22 267 bases
 MVCLRFPGGS CVAALTVTLM VLSSPLALAG DTRPRYLEQR KAECHFFNGT
 ERVRYLDRYI HNQEELVRFD SDVGEYRAVT ELGRPEAESW NSRKDILEQK
 RAAVDTYCRH NYEILDRFLV PRRVQPKVTV YPAKTQPLQR HNLLVCSVSG
 FYPGSIEVRW FRNDQEEKAG VVSTGLIQNG DWTFQTLVML ETVPQSGEVY
 ICQVEHPSVT SPLTVQWRAQ SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGRSGLQ PTGLLSX*   
>DL;IPD:MHC01569
IPD:MHC01569 Caja-DRB*W16:23 88 bases
 RYLEQAKCEC HHFNGTERVR YLERYFYNQE EYVRFDSDVG EYRAVTELGR
 PDAEYWNSQK DILEQKRAAV DRCRHNYEVS ERFLVPRR* 
>DL;IPD:MHC01570
IPD:MHC01570 Caja-DRB*W16:24 89 bases
 RYLEQAKCEC HHFNGTERVR YLERYFYNQE EYVRFDSDVG EYRAVTELGR
 PDAEYWNSQK DLLEQRRAEV DTVCRHNYEI LDRFLVPRR* 
>DL;IPD:MHC00093
IPD:MHC00093 Caja-DRB1*03:01 222 bases
 MLMVLSSPLA LAGDTRPRFL EYSTSECHFF NGTERVRFLD RYFFNQEENL
 RFDSDVGEFR AVTELGRPDA ESWNSQKDFL EDRRAEVDTV CRHNYEILDR
 FLVPRRVQPK VTVYPAKAQP LQHHNLLVCS VSGFYPGSIE VRWFRNDQEE
 KTGVVSTGLI QNGDWTFQTL VMLETLPQSG EVYTCQVEHP SVTSPLTVQW
 RAQSESAQSK MLSGVGGSVL GL*  
>DL;IPD:MHC00094
IPD:MHC00094 Caja-DRB1*03:02 259 bases
 MVYMRLPGGS CMAVLTVMLM VLSSPLALAG DTRPRFLEYS TSECHFFNGT
 ERVRLLERYI HNQEENLRFD SDVGEFRAVT ELGRPDAESW NSQKDFLEDR
 RAAVDTFCRH NYEISERFLV PRRVQPKVTV YPAKAQPLQH HNLLVCSVSG
 FYPGSIEVRW FRNDQEEKTG VVSTGLIQNG DWTFQTLVML ETLPQSGEVY
 TCQVEHPSVT SPLTVQWRAQ SESAQSKMLS GVGGSVLGLL FLGAGLFIYF
 RNQKGLLSX*    
>DL;IPD:MHC00095
IPD:MHC00095 Caja-DRB1*03:03 242 bases
 MLMVLSSPLA LAGDTRPRFL EYSTSECHFF NGTERVRFLD RYFFNQEENL
 RFDSDVGEFR AVTELGRPDA ESWNSQKDFL EDRRAAVDTF CRHNYEILDR
 FLVPRRVQPK VTVYPAKAQP LQHHNLLVCS VSGFYPGSIE VRWFRNDQEE
 KTGVVSTGLI QNGDWTFQTL VMLETLPQSG EVYTCQVEHP SVTSPLTVQW
 RAQSESAQSK MLSGVGGSVL GLLFLGAGLF IYFRNQKGLL SX*
>DL;IPD:MHC00096
IPD:MHC00096 Caja-DRB1*03:04 89 bases
 RFLEYSTSEC HFFNGTERVR FLDRYFFNQE ENLRFDSDVG EFRAVTELGR
 PDAESWNSQK DLLEQRRAEV DTFCRHNYEI LDRFLVPRR* 
>DL;IPD:MHC00097
IPD:MHC00097 Caja-DRB1*03:05 259 bases
 MVYMRLPGGS CMAVLTVMLM VLSSPLALAG DTRPRFLEYS TSECHFFNGT
 ERVRLLERYI HNQEEYVRFD SDVGEYRAVT ELGRPDAESW NSQKDFLEQR
 RAEVDTYCRH NYEISERFLV PRRVQPKVTV YPAKAQPLQH HNLLVCSLSG
 FYPGSIEVRW FRNDQEEKAG VVSTGLIQNG DWTFQTLVML ETLPQSGEVY
 TCQVEHPSVT SPLTVQWRAQ SESAQSKMLS GVGGSVLGLL FLGAGLFIYF
 RNQKGLLSX*    
>DL;IPD:MHC00098
IPD:MHC00098 Caja-DRB1*03:06 89 bases
 RFLEYSTSEC HFFNGTERVR LLDRYFFNQE ELVRFDSDVG EFRAVTELGR
 PDAESWNSQK DFLEDRRAAV DTFCRHNYEI SERFLVPRR* 
>DL;IPD:MHC00099
IPD:MHC00099 Caja-DRB1*03:07 267 bases
 MVCLRFPGGS CVAALTVTLM VLSSPLALAG DTRPRFLEYS TSECHFFNGT
 ERVRFLDRYF FNQEENLRFD SDVGEFRAVT ELGRPDAEYW NSQKDLLEQR
 RAEVDTYCRH NYEISERFLV PRRVQPKVTV YPAKTQPLQH HNLLVCSVSG
 FYPGSIEVRW FRNDQEEKAG VVSTGLIQNG DWTFQTLVML ETVPQSGEVY
 ICQVEHPSVT SPLTVQWRAW SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGRSGLQ PTGLLSX*   
>DL;IPD:MHC01560
IPD:MHC01560 Caja-DRB1*03:08 259 bases
 MVYMRLPGGS CMAVLTVMLM VLSSPLALAG DTRPRFLEYS TSECHFFNGT
 ERVRFLDRYF FNQEENLRFD SDVGEFRAVT ELGRPDAESW NSQKDFLEDR
 RAAVDTVCRH NYEILDRFLV PRRVQPKVTV YPAKAQPLQH HNLLVCSVSG
 FYPGSIEVRW FRNDQEEKTG VVSTGLIQNG DWTFQTLVML ETLPQSGEVY
 TCQVEHPSVT SPLTVQWRAQ SESAQSKMLS GVGGSVLGLL FLGAGLFIYF
 RNQKGLLSX*    
>DL;IPD:MHC01565
IPD:MHC01565 Caja-DRB1*03:09 76 bases
 TSECHFFNGT ERVRFLDRYF FNQEENLRFD SDVGEFRAVT ELGRPDAESW
 NSQKDFLEDR RAEVDTFCRH NYEILD*  
>DL;IPD:MHC01566
IPD:MHC01566 Caja-DRB1*03:10 76 bases
 TSECHFFNGT ERVRLLERYI HNQEEYVRFD SDVGEYRAVT ELGRPDAESW
 NSQKDFLEDR RAAVDTFCRH NYEILD*  
>DL;IPD:MHC01557
IPD:MHC01557 Caja-DRB1*03:11 242 bases
 MLMVLSSPLA LAGDTRPRFL EYSTSECHFF NGTERVRFLD RYFFNQEENL
 RFDSDVGEFR AVTELGRPDA ESWNSQKDLL EQRRAAVDTF CRHNYEILDR
 FLVPRRVQPK VTVYPAKAQP LQHHNLLVCS VSGFYPGSIE VRWFRNDQEE
 KTGVVSTGLI QNGDWTFQTL VMLETLPQSG EVYTCQVEHP SVTSPLTVQW
 RAQSESAQSK MLSGVGGSVL GLLFLGAGLF IYFRNQKGLL SX*
>DL;IPD:MHC01558
IPD:MHC01558 Caja-DRB1*03:12 267 bases
 MVCLRFPGGS CVAALTVTLM VLSSPLALAG DTRPRFLEYS TSECHFFNGT
 ERVRFLDRYF FNQEENLRFD SDVGEFRAVT ELGRPDAEYW NSQKDLLEQR
 RAEVDTFCRH NYEILDRFLV PRRVQPKVTV YPAKTQPLQH HNLLVCSVSG
 FYPGSIEVRW FRNDQEEKAG VVSTGLIQNG DWTFQTLVML ETVPQSGEVY
 ICQVEHPSVT SPLTVQWRAW SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGRSGLQ PTGLLSX*   
>DL;IPD:MHC01559
IPD:MHC01559 Caja-DRB1*03:14 89 bases
 RFLEYSTSEC HFFNGTERVR LLERYIHNQE ENLRFDSDVG EYRAVTELGR
 PDAEYWNSQK DLLEQRRAAV DTYCRHNYEI LDRFLVPRR* 
>DL;IPD:MHC04222
IPD:MHC04222 Caja-DRB1*03:16 259 bases
 MVYMRLPGGS CMAVLTVMLM VLSSPLALAG DTRPRFLEYS TSECHFFNGT
 ERVRFLDRYF FNQEENLRFD SDVGEFRAVT ELGRPDAESW NSQKDFLEDR
 RAAVDTVCRH NYEILDRFLV PRRVQPKVTV YPAKAQPLQH HNLLVCSVSG
 FYPGSIEVRW FRNDQEEKTG VVSTGLIQNG DWTFQTLVML ETLPQSGEVY
 TCQVEHPSVT SPLTVQWRAQ SESAQSKMLS GVGGSVLGLL FLGAGLFIYF
 RNQKGLLSX*    
