>DL;IPD:MHC00100
IPD:MHC00100 Caja-DRB*W12:01 776 bases
 GCTCCTACAT AGCAGCGCTG ACAGTGACAC TCATGGCGCT GAGCTCCCCA
 CTGGCTTTGG CTGGGGACTC CCCACCACGT TTCTTGGAGC AGTTTAAGTA
 TGAGTGTCTT CACCTCAACG GGACGGAGGG TGTACGGCTC CTGGTCAGAT
 ACATCTACAA CCAGGAGGAG TATGTGCGCT TTGACAGCGA CGTGGGGGAG
 TTCCGGGCGG TGACAGAGCT GGGGCGGCCT GCCGCAGAGT ACTTCAACAG
 CCTGAAGGAC TACATGGAGC AGACGCGGGC CGCGGTGGAC ACCGTGTGCA
 GACACAACTA CGGGATTTTT GAGAGGTTCC TAGTGCAGCG GCGAGTCCAA
 CCTAAGGTGA CTGTGTATCC TGCAAAGACC CAGCCCCTGC AGCGCCACAA
 CCTCCTGGTC TGCTCTGTGA GTGGTTTCTA TCCAGGCAGC ATTGAAGTCA
 GGTGGTTCCG GAACGACCAG GAGGAGAAGA CTGGGGTGGT GTCCACAGGC
 CTGATCCACA ATGGAGACTG GACTTTCCAG ACCCTGGTGA TGCTGGAAAC
 ACTTCCTCAG AGTGGAGAGG TTTACATCTG CCAAGTGGAG CACCCAAGCG
 TGACCAGCCC TCTCACAGTG CAATGGAGAG CACAGTCTGA ATCTGCACAG
 AGCAAGATGC TGAGTGGAGT CGGGGGCTCT GTGCTGGGCC TGCTCTTCCT
 TGGGGCAGGG CTGTTCATCT ACTTCAGGAA TCAGAAAGGA CATTCTGCCC
 TTCGGCCATC AGGAGTCCTT AGCTGA*  
>DL;IPD:MHC01561
IPD:MHC01561 Caja-DRB*W12:02 776 bases
 GCTCCTACAT AGCAGCGCTG ACAGTGACAC TCATGGCGCT GAGCTCCCCA
 CTGGCTTTGG CTGGGGACTC CCCACCACGT TTCTTGGAGC AGTTTAAGTA
 TGAGTGTCTT CACCTCAACG GGACGGAGGG TGTACGGCTC CTGGTCAGAT
 ACATCTACAA CCAGGAGGAG TATGTGCGCT TTGACAGCGA CGTGGGGGAG
 TTCCGGGCGG TGACAGAGCT GGGGCGGCCT GCCGCAGAGT ACTTCAACAG
 CCTGAAGGAC TACATGGAGC AGACGCGGGC CGCGGTGGAC ACCGTGTGCA
 GACACAACTA CGGGATTTTT GAGAGGTTCC TAGTGCAGAG GCGAGTCCAA
 CCTAAGGTGA CTGTGTATCC TGCAAAGACC CAGCCCCTGC AGCGCCACAA
 CCTCCTGGTC TGCTCTGTGA GTGGTTTCTA TCCAGGCAGC ATTGAAGTCA
 GGTGGTTCCG GAACGACCAG GAGGAGAAGA CTGGGGTGGT GTCCACAGGC
 CTGATCCACA ATGGAGACTG GACTTTCCAG ACCCTGGTGA TGCTGGAAAC
 ACTTCCTCAG AGTGGAGAGG TTTACATCTG CCAAGTGGAG CACCCAAGCG
 TGACCAGCCC TCTCACAGTG CAATGGAGAG CACAGTCTGA ATCTGCACAG
 AGCAAGATGC TGAGTGGAGT CGGGGGCTTT GTGCTGGGCC TGCTCTTCCT
 TGGCGCAGGG CTGTTCATCT ACTTCAGGAA TCAGAAAGGA CATTCTGCCC
 TTCGGCCATC AGGAGTCGTT AGCTGA*  
>DL;IPD:MHC00101
IPD:MHC00101 Caja-DRB*W16:01 798 bases
 ATGGTGTGTC TGAGATTCCC TGGAGGCTCC TGCGTGGCAG CGCTGACAGT
 GACGCTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTACTT GGAGCAGGTT AAGTTTGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GGTACCTGGA AAGATACTTC TATAACCAGG AGGAGTATGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTACTGG AACAGCCAGA AGGACATCCT GGAGCAGAAG
 CGGGCCGCGG TGGACAGATG CAGACACAAC TACGAGGGTT TCGAGACGTT
 CCTAGTGCCG CGGAGAGTAC AACCTAAGGT GACTGTGTAT CCTGCAAAGA
 CCCAGCCCCT GCAGCACCAC AACCTCCTGG TCTGCTCTGT GAGTGGTTTC
 TATCCAGGCA GCATTGAAGT CAGGTGGTTC CGGAATGATC AGGAAGAGAA
 GGCTGGGGTG GTGTCCACAG GCCTGATCCA GAATGGAGAC TGGACCTTCC
 AGACCCTGGT GATGCTGGAA ACAGTTCCTC AGAGTGGAGA GGTTTATATC
 TGCCAAGTGG AGCACCCAAG CGTGACCAGC CCTCTCACAG TGCAATGGAG
 AGCGCAGTCT GAATCTGCAC AGAGCAAGAT GCTGAGTGGA GTTGGGGGCT
 TTGTGCTGGG CCTGCTCTTC CTTGGGGCAG GGCTGTTCAT CTACTTCAGG
 AATCAGAAAG GACGCTCTGG ACTTCAGCCA ACAGGACTCC TGAGCTGA*
>DL;IPD:MHC00102
IPD:MHC00102 Caja-DRB*W16:04 267 bases
 CACGTTACTT GGAGCAGGCT AAGTGTGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GGTACCTGGA AAGATACTTC TATAACCAGG AGGAGAACTT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTACTGG AACAGCCAGA AGGACATCCT GGAGCAGAAG
 CGGGCCGCGG TGGACAGATG CAGACACAAC TACGAGATTT CAGAGAGGTT
 CCTAGTGCCG CGGAGAG*   
>DL;IPD:MHC00103
IPD:MHC00103 Caja-DRB*W16:05 801 bases
 ATGGTGTGTC TGAGATTCCC TGGAGGCTCC TGCGTGGCAG CGCTGACAGT
 GACGCTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTACTT GGAGCAGGTT AAGTTTGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GGCTCCTGGA AAGACGCATC CATAACCAGG AGGAGTATGC
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTACTGG AACAGCCAGA AGGACCTCCT GGAGCAGAGG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGAGA TTTTAGACAG
 GTTCCTAGTG CCGCGGAGAG TACAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAGTGGT
 TTCTACCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAATG ATCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCCT GGTGATGCTG GAAACAGTTC CTCAGAGTGG AGAGGTTTAT
 ATCTGCCAAG TGGAGCACCC AAGCGTGACC AGCCCTCTCA CAGTGCAATG
 GAGAGCATGG TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTCGGGG
 GCTTTGTGCT GGGCCTGCTC TTCCTTGGGG CAGGGCTGTT CATCTACTTC
 AGGAATCAGA AAGGACGCTC TGGACTTCAG CCAACAGGAC TCCTGAGCTG
 A*    
>DL;IPD:MHC00104
IPD:MHC00104 Caja-DRB*W16:06 801 bases
 ATGGTGTGTC TGAGATTCCC TGGAGGCTCC TGCGTGGCAG CGCTGACAGT
 GACGCTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT GGAGCAGGTT AAGTATGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGTT CAGAGACATC TACAACCAGG AGGAGGTCCT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTACTGG AACAGCCAGA AGGACATCCT GGAGGACAGG
 CGGGCCGCGG TGGACACCGT GTGCAGACAC AACTACGAGA TTTTAGACAG
 GTTCCTAGTG CCGCGGAGAG TACAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAGTGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAATG ATCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCCT GGTGATGCTG GAAACACTTC CTCAGAGTGG AGAGGTTTAC
 ACCTGCCAAG TGGAGCACCC AAGCGTGACC AGCCCTCTCA CAGTGCAATG
 GAGAGCGCAG TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTTGGGG
 GCTTTGTGCT GGGCCTGCTC TTCCTTGGGG CAGGGCTGTT CATCTACTTC
 AGGAATCAGA AAGGACGCTC TGGACTTCAG CCAACAGGAC TCCTGAGCTG
 A*    
>DL;IPD:MHC00105
IPD:MHC00105 Caja-DRB*W16:07 270 bases
 CACGTTTCTT GGAGCAGGTT AAGTATGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGTT CAGAGACATC TACAACCAGG AGGAGGTCCT
 GCGCTTCGAC AGCGACGTGT GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTACTGG AACAGCCAGA AGGACATCCT GGAGGACAGG
 CGGGCCGCGG TGGACACCGT GTGCAGACAC AACTACGAGA TTTTAGACAG
 GTTCCTAGTG CCGCGGAGAG *  
>DL;IPD:MHC00106
IPD:MHC00106 Caja-DRB*W16:08 798 bases
 ATGGTGTGTC TGAGATTCCC TGGAGGCTCC TGCGTGGCAG CGCTGACAGT
 GACGCTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTACTT GGAGCAGCAT AAGGCTGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAACCAGG AGGAGGTCCT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTAGCGC AGAGAAGCTC AACAGCCAGA AGGACATCCT GGAGCAGACG
 CGGGCCGAGG TGGACAGATG CAGACACAAC TACGAGATTT TCGAGACGTT
 CCTAGTGCCG CGGAGAGTAC AACCTAAGGT GACTGTGTAT CCTGCAAAGA
 CCCAGCCCCT GCAGCGCCAC AACCTCCTGG TCTGCTCTGT GAGTGGTTTC
 TATCCAGGCA GCATTGAAGT CAGGTGGTTC CGGAATGATC AGGAAGAGAA
 GGCTGGGGTG GTGTCCACAG GCCTGATCCA GAATGGAGAC TGGACCTTCC
 AGACCCTGGT GATGCTGGAA ACAGTTCCTC AGAGTGGAGA GGTTTATATC
 TGCCAAGTGG AGCACCCAAG CGTGACCAGC CCTCTCACAG TGCAATGGAG
 AGCACAGTCT GAATCTGCAC AGAGCAAGAT GCTGAGTGGA GTTGGGGGCT
 TTGTGCTGGG CCTGCTCTTC CTTGGGGCAG GGCTGTTCAT CTACTTCAGG
 AATCAGAAAG GACGCTCTGG ACTTCAGCCA ACAGGACTCC TGAGCTGA*
>DL;IPD:MHC00107
IPD:MHC00107 Caja-DRB*W16:09 798 bases
 ATGGTGTGTC TGAGATTCCC TGGAGGCTCC TGCGTGGCAG CGCTGACAGT
 GACGCTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTACTT GGAGCAGGCT AAGTGTGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GGTACCTGGA AAGATACTTC TATAACCAGG AGGAGTATGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTACTGG AACAGCCAGA AGGACATCCT GGAGCAGAAG
 CGGGCCGAGG TGGACAGATG CAGACACAAC TACGAGGTTT CAGAGAGGTT
 CCTAGTGCCG CGGAGAGTAC AACCTAAGGT GACTGTGTAT CCTGCAAAGA
 CCCAGCCCCT GCAGCACCAC AACCTCCTGG TCTGCTCTGT GAGTGGTTTC
 TATCCAGGCA GCATTGAAGT CAGGTGGTTC CGGAATGATC AGGAAGAGAA
 GGCTGGGGTG GTGTCCACAG GCCTGATCCA GAATGGAGAC TGGACCTTCC
 AGACCCTGGT GATGCTGGAA ACAGTTCCTC AGAGTGGAGA GGTTTATATC
 TGCCAAGTGG AGCACCCAAG CGTGACCAGC CCTCTCACAG TGCAATGGAG
 AGCGCAGTCT GAATCTGCAC AGAGCAAGAT GCTGAGTGGA GTTGGGGGCT
 TTGTGCTGGG CCTGCTCTTC CTTGGGGCAG GGCTGTTCAT CTACTTCAGG
 AATCAGAAAG GACGCTCTGG ACTTCAGCCA ACAGGACTCC TGAGCTGA*
>DL;IPD:MHC00108
IPD:MHC00108 Caja-DRB*W16:10 798 bases
 ATGGTGTGTC TGAGATTCCC TGGAGGCTCC TGCGTGGCAG CGCTGACAGT
 GACGCTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTACTT GGAGCAGGCT AAGTGTGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GGTACCTGGA AAGATACTTC TATAACCAGG AGGAGTATGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTACTGG AACAGCCAGA AGGACATCCT GGAGCAGAAG
 CGGGCCGCGG TGGACAGATG CAGACACAAC TACGAGGTTT CAGAGACGTT
 CCTAGTGCCG CGGAGAGTAC AACCTAAGGT GACTGTGTAT CCTGCAAAGA
 CCCAGCCCCT GCAGCACCAC AACCTCCTGG TCTGCTCTGT GAGTGGTTTC
 TATCCAGGCA GCATTGAAGT CAGGTGGTTC CGGAATGATC AGGAAGAGAA
 GGCTGGGGTG GTGTCCACAG GCCTGATCCA GAATGGAGAC TGGACCTTCC
 AGACCCTGGT GATGCTGGAA ACAGTTCCTC AGAGTGGAGA GGTTTATATC
 TGCCAAGTGG AGCACCCAAG CGTGACCAGC CCTCTCACAG TGCAATGGAG
 AGCGCAGTCT GAATCTGCAC AGAGCAAGAT GCTGAGTGGA GTTGGGGGCT
 TTGTGCTGGG CCTGCTCTTC CTTGGGGCAG GGCTGTTCAT CTACTTCAGG
 AATCAGAAAG GACGCTCTGG ACTTCAGCCA ACAGGACTCC TGAGCTGA*
>DL;IPD:MHC00109
IPD:MHC00109 Caja-DRB*W16:11 801 bases
 ATGGTGTGTC TGAGATTCCC TGGAGGCTCC TGCGTGGCAG CGCTGACAGT
 GACGCTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTACTT GGAGCAGCGT AAGGCTGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GGCTCCTGGA AAGATACTTC TATAACCAGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGTCGC GGAGTCCTGG AACAGCCGGA AGGACATCCT GGAGCAGAGG
 CGGGCCGCGG TGGACACCTT CTGCAGACAC AACTACGAGG GTTTCGAGAC
 GTTCCTAGTG CCGCGGAGAG TACAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAGTGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAATG ATCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCCT GGTGATGCTG GAAACAGTTC CTCAGAGTGG AGAGGTTTAT
 ATCTGCCAAG TGGAGCACCC AAGCGTGACC AGCCCTCTCA CAGTGCAATG
 GAGAGCGCAG TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTTGGGG
 GCTTTGTGCT GGGCCTGCTC TTCCTTGGGG CAGGGCTGTT CATCTACTTC
 AGGAATCAGA AAGGACGCTC TGGACTTCAG CCAACAGGAC TCCTGAGCTG
 A*    
>DL;IPD:MHC00110
IPD:MHC00110 Caja-DRB*W16:12 801 bases
 ATGGTGTGTC TGAGATTCCC TGGAGGCTCC TGCGTGGCAG CGCTGACAGT
 GACGCTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTACTT GGAGCAGGCT AAGTGTGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GGTACCTGGA AAGATACTTC TATAACCAGG AGGAGTTAGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTAGCGC AGAGAAGCTC AACAGCCAGA AGGACCTCCT GGAGCAGAGG
 CGGGCCGAGG TGGACACCGT GTGCAGACAC AACTACGAGA TTTCAGAGAG
 GTTCCTAGTG CCGCGGAGAG TACAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAGTGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAATG ATCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCCT GGTGATGCTG GAAACAGTTC CTCAGAGTGG AGAGGTTTAT
 ATCTGCCAAG TGGAGCACCC AAGCGTGACC AGCCCTCTCA CAGTGCAATG
 GAGAGCGCAG TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTTGGGG
 GCTTTGTGCT GGGCCTGCTC TTCCTTGGGG CAGGGCTGTT CATCTACTTC
 AGGAATCAGA AAGGACGCTC TGGACTTCAG CCAACAGGAC TCCTGAGCTG
 A*    
>DL;IPD:MHC00111
IPD:MHC00111 Caja-DRB*W16:13 801 bases
 ATGGTGTGTC TGAGATTCCC TGGAGGCTCC TGCGTGGCAG CGCTGACAGT
 GACGCTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTACTT GGAGCAGGTT AAGTTTGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GGCTCCTGGA AAGACGCATC CATAACCAGG AGGAGTATGC
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTACTGG AACAGCCAGA AGGACATCCT GGAGCAGAGG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGAGA TTTTAGACAG
 GTTCCTAGTG CCGCGGAGAG TACAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAGTGGT
 TTCTACCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAATG ATCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCCT GGTGATGCTG GAAACAGTTC CTCAGAGTGG AGAGGTTTAT
 ATCTGCCAAG TGGAGCACCC AAGCGTGACC AGCCCTCTCA CAGTGCAATG
 GAGAGCATGG TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTCGGGG
 GCTTTGTGCT GGGCCTGCTC TTCCTTGGGG CAGGGCTGTT CATCTACTTC
 AGGAATCAGA AAGGACGCTC TGGACTTCAG CCAACAGGAC TCCTGAGCTG
 A*    
>DL;IPD:MHC00112
IPD:MHC00112 Caja-DRB*W16:14 267 bases
 CACGTTACTT GGAGCAGGCT AAGTGTGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GGTACCTGGA AAGATACTTC TATAACCAGG AGGAGTTAGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTAGCGC AGAGAAGCTC AACAGCCAGA AGGACCTCCT GGAGCAGAAG
 CGGGCCGAGG TGGACAGATG CAGACACAAC TACGAGGTTT CAGAGAGGTT
 CCTAGTGCCG CGGAGAG*   
>DL;IPD:MHC00113
IPD:MHC00113 Caja-DRB*W16:15 270 bases
 CACGTTACTT GGAGCAGGTT AAGTTTGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GGCTCCTGGA AAGACGCATC CATAACCAGG AGGAGTATGC
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTACTGG AACAGCCAGA AGGACCTCCT GGAGCAGAGG
 CGGGCCGAGG TGGACACCTA CTGCAGACAC AACTACGAGA TTTCAGAGAG
 GTTCCTAGTG CCGCGGAGAG *  
>DL;IPD:MHC01562
IPD:MHC01562 Caja-DRB*W16:16 801 bases
 ATGGTGTGTC TGAGATTCCC TGGAGGCTCC TGCGTGGCAG CGCTGACAGT
 GACGCTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTACTT GGAGCAGGCT AAGTGTGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GGTACCTGGA AAGATACTTC TATAACCAGG AGGAGTATGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTACTGG AACAGCCAGA AGGACCTCCT GGAGCAGACG
 CGGGCCGAGG TGGACACCGT GTGCAGACAC AACTACGAGA TTTTCGAGAC
 GTTCCTAGTG CCGCGGAGAG TACAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAGTGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAATG ATCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCCT GGTGATGCTG GAAACAGTTC CTCAGAGTGG AGAGGTTTAT
 ATCTGCCAAG TGGAGCACCC AAGCGTGACC AGCCCTCTCA CAGTGCAATG
 GAGAGCGCAG TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTTGGGG
 GCTTTGTGCT GGGCCTGCTC TTCCTTGGGG CAGGGCTGTT CATCTACTTC
 AGGAATCAGA AAGGACGCTC TGGACTTCAG CCAACAGGAC TCCTGAGCTG
 A*    
>DL;IPD:MHC01567
IPD:MHC01567 Caja-DRB*W16:17 242 bases
 TACTTGGAGC AGGCTAAGTG TGAGTGTCAT CACTTCAACG GGACGGAGCG
 GGTGCGGTAC CTGGAAAGAT ACTTCTATAA CCAGGAGGAG TATGTGCGCT
 TCGACAGCGA CGTGGGGGAG TACCGGGCGG TGACGGAGCT GGGGCGGCCT
 GACGCGGAGT ACTGGAACAG CCAGAAGGAC ATCCTGGAGC AGAAGCGGGC
 CGCGGTGGAC AGATGCAGAC ACAACTACGA GATTTTCGAG AC*
>DL;IPD:MHC01568
IPD:MHC01568 Caja-DRB*W16:18 230 bases
 GTTAAGTTTG AGTGTCATCA CTTCAACGGG ACGGAGCGGG TGCGGCTCCT
 GGAAAGACGC ATCCATAACC AGGAGGAGTA TGCGCGCTTC GACAGCGACG
 TGGGGGAGTA CCGGGCGGTG ACGGAGCTGG GGCGGCCTGA CGCGGAGTAC
 TGGAACAGCC AGAAGGACAT CCTGGAGCAG AAGCGGGCCG AGGTGGACAG
 ATGCAGACAC AACTACGAGG TTTCAGAGAG * 
>DL;IPD:MHC01563
IPD:MHC01563 Caja-DRB*W16:20 801 bases
 ATGGTGTGTC TGAGATTCCC TGGAGGCTCC TGCGTGGCAG CGCTGACAGT
 GACGCTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTACTT GGAGCAGGCT AAGTGTGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GGTACCTGGA AAGATACTTC TATAACCAGG AGGAGTATGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTACTGG AACAGCCAGA AGGACCTCCT GGAGCAGACG
 CGGGCCGAGG TGGACACCGT GTGCAGACAC AACTACGAGG GTTTCGAGAC
 GTTCCTAGTG CCGCGGAGAG TACAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAGTGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAATG ATCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCCT GGTGATGCTG GAAACAGTTC CTCAGAGTGG AGAGGTTTAT
 ATCTGCCAAG TGGAGCACCC AAGCGTGACC AGCCCTCTCA CAGTGCAATG
 GAGAGCGCAG TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTTGGGG
 GCTTTGTGCT GGGCCTGCTC TTCCTTGGGG CAGGGCTGTT CATCTACTTC
 AGGAATCAGA AAGGACGCTC TGGACTTCAG CCAACAGGAC TCCTGAGCTG
 A*    
>DL;IPD:MHC01564
IPD:MHC01564 Caja-DRB*W16:22 801 bases
 ATGGTGTGTC TGAGATTCCC TGGAGGCTCC TGCGTGGCAG CGCTGACAGT
 GACGCTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTACTT GGAGCAGCGT AAGGCTGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTACCTGGA CAGATACATC CATAACCAGG AGGAGTTAGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGAAGC GGAGTCCTGG AACAGCCGGA AGGACATCCT GGAGCAGAAG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGAGA TTTTAGACAG
 GTTCCTAGTG CCGCGGAGAG TACAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCGC CACAACCTCC TGGTCTGCTC TGTGAGTGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAATG ATCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCCT GGTGATGCTG GAAACAGTTC CTCAGAGTGG AGAGGTTTAT
 ATCTGCCAAG TGGAGCACCC AAGCGTGACC AGCCCTCTCA CAGTGCAATG
 GAGAGCACAG TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTTGGGG
 GCTTTGTGCT GGGCCTGCTC TTCCTTGGGG CAGGGCTGTT CATCTACTTC
 AGGAATCAGA AAGGACGCTC TGGACTTCAG CCAACAGGAC TCCTGAGCTG
 A*    
>DL;IPD:MHC01569
IPD:MHC01569 Caja-DRB*W16:23 267 bases
 CACGTTACTT GGAGCAGGCT AAGTGTGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GGTACCTGGA AAGATACTTC TATAACCAGG AGGAGTATGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTACTGG AACAGCCAGA AGGACATCCT GGAGCAGAAG
 CGGGCCGCGG TGGACAGATG CAGACACAAC TACGAGGTTT CAGAGAGGTT
 CCTAGTGCCG CGGAGAG*   
>DL;IPD:MHC01570
IPD:MHC01570 Caja-DRB*W16:24 270 bases
 CACGTTACTT GGAGCAGGCT AAGTGTGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GGTACCTGGA AAGATACTTC TATAACCAGG AGGAGTATGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTACTGG AACAGCCAGA AGGACCTCCT GGAGCAGAGG
 CGGGCCGAGG TGGACACCGT GTGCAGACAC AACTACGAGA TTTTAGACAG
 GTTCCTAGTG CCGCGGAGAG *  
>DL;IPD:MHC00093
IPD:MHC00093 Caja-DRB1*03:01 665 bases
 ATGCTGATGG TGCTGAGCTC CCCACTGGCT TTGGCTGGGG ACACCCGACC
 ACGTTTCTTG GAGTATAGCA CGTCTGAGTG TCATTTCTTC AACGGGACGG
 AGCGGGTGCG GTTCCTGGAC AGATACTTCT TTAATCAGGA GGAGAACTTG
 CGCTTCGACA GCGACGTGGG GGAGTTCCGG GCGGTGACGG AGCTGGGGCG
 GCCTGACGCG GAGTCCTGGA ACAGCCAGAA GGACTTCCTG GAGGACAGGC
 GGGCCGAGGT GGACACCGTG TGCAGACACA ACTACGAGAT TTTAGACAGG
 TTCCTAGTGC CGCGGAGAGT CCAACCTAAG GTGACTGTGT ATCCTGCAAA
 GGCCCAGCCC CTGCAGCACC ACAACCTCCT GGTCTGCTCT GTGAGTGGGT
 TCTATCCAGG CAGCATTGAA GTCAGGTGGT TCCGGAACGA CCAGGAGGAG
 AAGACTGGGG TGGTGTCCAC AGGCCTGATC CAGAATGGAG ACTGGACCTT
 CCAGACCCTG GTGATGCTGG AAACACTTCC TCAGAGTGGA GAGGTTTACA
 CCTGCCAAGT GGAGCACCCA AGCGTGACCA GCCCTCTCAC AGTGCAATGG
 AGAGCACAGT CTGAATCTGC ACAGAGCAAG ATGCTGAGTG GAGTCGGGGG
 CTCTGTGCTG GGCCT*   
>DL;IPD:MHC00094
IPD:MHC00094 Caja-DRB1*03:02 777 bases
 ATGGTGTATA TGAGGCTCCC TGGAGGCTCC TGCATGGCAG TGCTGACAGT
 GATGCTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT GGAGTATAGC ACGTCTGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGCTCCTGGA AAGATACATC CATAACCAGG AGGAGAACTT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTCCTGG AACAGCCAGA AGGACTTCCT GGAGGACAGG
 CGGGCCGCGG TGGACACCTT CTGCAGACAC AACTACGAGA TTTCAGAGAG
 GTTCCTAGTG CCGCGGAGAG TCCAACCTAA GGTGACTGTG TATCCTGCAA
 AGGCCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAGTGGG
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACG ACCAGGAAGA
 GAAGACTGGG GTGGTGTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCCT GGTGATGCTG GAAACACTTC CTCAGAGTGG AGAGGTTTAC
 ACCTGCCAAG TGGAGCACCC AAGCGTGACC AGCCCTCTCA CAGTGCAATG
 GAGAGCACAG TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTCGGGG
 GCTCTGTGCT GGGCCTGCTC TTCCTTGGGG CAGGGCTGTT CATCTACTTC
 AGGAATCAGA AAGGACTCCT GAGCTGA*  
>DL;IPD:MHC00095
IPD:MHC00095 Caja-DRB1*03:03 726 bases
 ATGCTGATGG TGCTGAGCTC CCCACTGGCT TTGGCTGGGG ACACCCGACC
 ACGTTTCTTG GAGTATAGCA CGTCTGAGTG TCATTTCTTC AACGGGACGG
 AGCGGGTGCG GTTCCTGGAC AGATACTTCT TTAATCAGGA GGAGAACTTG
 CGCTTCGACA GCGACGTGGG GGAGTTCCGG GCGGTGACGG AGCTGGGGCG
 GCCTGACGCG GAGTCCTGGA ACAGCCAGAA GGACTTCCTG GAGGACAGGC
 GGGCCGCGGT GGACACCTTC TGCAGACACA ACTACGAGAT TTTAGACAGG
 TTCCTAGTGC CGCGGAGAGT CCAACCTAAG GTGACTGTGT ATCCTGCAAA
 GGCCCAGCCC CTGCAGCACC ACAACCTCCT GGTCTGCTCT GTGAGTGGGT
 TCTATCCAGG CAGCATTGAA GTCAGGTGGT TCCGGAACGA CCAGGAGGAG
 AAGACTGGGG TGGTGTCCAC AGGCCTGATC CAGAATGGAG ACTGGACCTT
 CCAGACCCTG GTGATGCTGG AAACACTTCC TCAGAGTGGA GAGGTTTACA
 CCTGCCAAGT GGAGCACCCA AGCGTGACCA GCCCTCTCAC AGTGCAATGG
 AGAGCACAGT CTGAATCTGC ACAGAGCAAG ATGCTGAGTG GAGTCGGGGG
 CTCTGTGCTG GGCCTGCTCT TCCTTGGGGC AGGGCTGTTC ATCTACTTCA
 GGAATCAGAA AGGACTCCTG AGCTGA*  
>DL;IPD:MHC00096
IPD:MHC00096 Caja-DRB1*03:04 270 bases
 CACGTTTCTT GGAGTATAGC ACGTCTGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TTTAATCAGG AGGAGAACTT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTCCTGG AACAGCCAGA AGGACCTCCT GGAGCAGAGG
 CGGGCCGAGG TGGACACCTT CTGCAGACAC AACTACGAGA TTTTAGACAG
 GTTCCTAGTG CCGCGGAGAG *  
>DL;IPD:MHC00097
IPD:MHC00097 Caja-DRB1*03:05 777 bases
 ATGGTGTATA TGAGGCTCCC TGGAGGCTCC TGCATGGCAG TGCTGACAGT
 GATGCTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT GGAGTATAGC ACGTCTGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGCTCCTGGA AAGATACATC CATAACCAGG AGGAGTATGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTCCTGG AACAGCCAGA AGGACTTCCT GGAGCAGAGG
 CGGGCGGAGG TGGACACCTA CTGCAGACAC AACTACGAGA TTTCAGAGAG
 GTTCCTAGTG CCGCGGAGAG TACAACCTAA GGTGACTGTG TATCCTGCAA
 AGGCCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TCTGAGTGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAATG ATCAGGAGGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCCT GGTGATGCTG GAAACACTTC CTCAGAGTGG AGAGGTTTAC
 ACCTGCCAAG TGGAGCACCC AAGCGTGACC AGCCCTCTCA CAGTGCAATG
 GAGAGCACAG TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTCGGGG
 GCTCTGTGCT GGGCCTGCTC TTCCTTGGGG CAGGGCTGTT CATCTACTTC
 AGGAATCAGA AAGGACTCCT GAGCTGA*  
>DL;IPD:MHC00098
IPD:MHC00098 Caja-DRB1*03:06 270 bases
 CACGTTTCTT GGAGTATAGC ACGTCTGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGCTCCTGGA CAGATACTTC TTTAATCAGG AGGAGTTAGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTCCTGG AACAGCCAGA AGGACTTCCT GGAGGACAGG
 CGGGCCGCGG TGGACACCTT CTGCAGACAC AACTACGAGA TTTCAGAGAG
 GTTCCTAGTG CCGCGGAGAG *  
>DL;IPD:MHC00099
IPD:MHC00099 Caja-DRB1*03:07 801 bases
 ATGGTGTGTC TGAGATTCCC TGGAGGCTCC TGCGTGGCAG CGCTGACAGT
 GACGCTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT GGAGTATAGC ACGTCTGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TTTAATCAGG AGGAGAACTT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTACTGG AACAGCCAGA AGGACCTCCT GGAGCAGAGG
 CGGGCCGAGG TGGACACCTA CTGCAGACAC AACTACGAGA TTTCAGAGAG
 GTTCCTAGTG CCGCGGAGAG TACAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAGTGGT
 TTCTACCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAATG ATCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCCT GGTGATGCTG GAAACAGTTC CTCAGAGTGG AGAGGTTTAT
 ATCTGCCAAG TGGAGCACCC AAGCGTGACC AGCCCTCTCA CAGTGCAATG
 GAGAGCATGG TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTCGGGG
 GCTTTGTGCT GGGCCTGCTC TTCCTTGGGG CAGGGCTGTT CATCTACTTC
 AGGAATCAGA AAGGACGCTC TGGACTTCAG CCAACAGGAC TCCTGAGCTG
 A*    
>DL;IPD:MHC01560
IPD:MHC01560 Caja-DRB1*03:08 777 bases
 ATGGTGTATA TGAGGCTCCC TGGAGGCTCC TGCATGGCAG TGCTGACAGT
 GATGCTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT GGAGTATAGC ACGTCTGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TTTAATCAGG AGGAGAACTT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTCCTGG AACAGCCAGA AGGACTTCCT GGAGGACAGG
 CGGGCCGCGG TGGACACCGT GTGCAGACAC AACTACGAGA TTTTAGACAG
 GTTCCTAGTG CCGCGGAGAG TCCAACCTAA GGTGACTGTG TATCCTGCAA
 AGGCCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAGTGGG
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACG ACCAGGAGGA
 GAAGACTGGG GTGGTGTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCCT GGTGATGCTG GAAACACTTC CTCAGAGTGG AGAGGTTTAC
 ACCTGCCAAG TGGAGCACCC AAGCGTGACC AGCCCTCTCA CAGTGCAATG
 GAGAGCACAG TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTCGGGG
 GCTCTGTGCT GGGCCTGCTC TTCCTTGGGG CAGGGCTGTT CATCTACTTC
 AGGAATCAGA AAGGACTCCT GAGCTGA*  
>DL;IPD:MHC01565
IPD:MHC01565 Caja-DRB1*03:09 230 bases
 ACGTCTGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC GGTTCCTGGA
 CAGATACTTC TTTAATCAGG AGGAGAACTT GCGCTTCGAC AGCGACGTGG
 GGGAGTTCCG GGCGGTGACG GAGCTGGGGC GGCCTGACGC GGAGTCCTGG
 AACAGCCAGA AGGACTTCCT GGAGGACAGG CGGGCCGAGG TGGACACCTT
 CTGCAGACAC AACTACGAGA TTTTAGACAG * 
>DL;IPD:MHC01566
IPD:MHC01566 Caja-DRB1*03:10 230 bases
 ACGTCTGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC GGCTCCTGGA
 AAGATACATC CATAACCAGG AGGAGTATGT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGACGC GGAGTCCTGG
 AACAGCCAGA AGGACTTCCT GGAGGACAGG CGGGCCGCGG TGGACACCTT
 CTGCAGACAC AACTACGAGA TTTTAGACAG * 
>DL;IPD:MHC01557
IPD:MHC01557 Caja-DRB1*03:11 726 bases
 ATGCTGATGG TGCTGAGCTC CCCACTGGCT TTGGCTGGGG ACACCCGACC
 ACGTTTCTTG GAGTATAGCA CGTCTGAGTG TCATTTCTTC AACGGGACGG
 AGCGGGTGCG GTTCCTGGAC AGATACTTCT TTAATCAGGA GGAGAACTTG
 CGCTTCGACA GCGACGTGGG GGAGTTCCGG GCGGTGACGG AGCTGGGGCG
 GCCTGACGCG GAGTCCTGGA ACAGCCAGAA GGACCTCCTG GAGCAGAGGC
 GGGCCGCGGT GGACACCTTC TGCAGACACA ACTACGAGAT TTTAGACAGG
 TTCCTAGTGC CGCGGAGAGT CCAACCTAAG GTGACTGTGT ATCCTGCAAA
 GGCCCAGCCC CTGCAGCACC ACAACCTCCT GGTCTGCTCT GTGAGTGGGT
 TCTATCCAGG CAGCATTGAA GTCAGGTGGT TCCGGAACGA CCAGGAGGAG
 AAGACTGGGG TGGTGTCCAC AGGCCTGATC CAGAATGGAG ACTGGACCTT
 CCAGACCCTG GTGATGCTGG AAACACTTCC TCAGAGTGGA GAGGTTTACA
 CCTGCCAAGT GGAGCACCCA AGCGTGACCA GCCCTCTCAC AGTGCAATGG
 AGAGCACAGT CTGAATCTGC ACAGAGCAAG ATGCTGAGTG GAGTCGGGGG
 CTCTGTGCTG GGCCTGCTCT TCCTTGGGGC AGGGCTGTTC ATCTACTTCA
 GGAATCAGAA AGGACTCCTG AGCTGA*  
>DL;IPD:MHC01558
IPD:MHC01558 Caja-DRB1*03:12 801 bases
 ATGGTGTGTC TGAGATTCCC TGGAGGCTCC TGCGTGGCAG CGCTGACAGT
 GACGCTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT GGAGTATAGC ACGTCTGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TTTAATCAGG AGGAGAACTT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTACTGG AACAGCCAGA AGGACCTCCT GGAGCAGAGG
 CGGGCCGAGG TGGACACCTT CTGCAGACAC AACTACGAGA TTTTAGACAG
 GTTCCTAGTG CCGCGGAGAG TACAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAGTGGT
 TTCTACCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAATG ATCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCCT GGTGATGCTG GAAACAGTTC CTCAGAGTGG AGAGGTTTAT
 ATCTGCCAAG TGGAGCACCC AAGCGTGACC AGCCCTCTCA CAGTGCAATG
 GAGAGCATGG TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTCGGGG
 GCTTTGTGCT GGGCCTGCTC TTCCTTGGGG CAGGGCTGTT CATCTACTTC
 AGGAATCAGA AAGGACGCTC TGGACTTCAG CCAACAGGAC TCCTGAGCTG
 A*    
>DL;IPD:MHC01559
IPD:MHC01559 Caja-DRB1*03:14 270 bases
 CACGTTTCTT GGAGTATAGC ACGTCTGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGCTCCTGGA AAGATACATC CATAACCAGG AGGAGAACTT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTACTGG AACAGCCAGA AGGACCTCCT GGAGCAGAGG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGAGA TTTTAGACAG
 GTTCCTAGTG CCGCGGAGAG *  
>DL;IPD:MHC04222
IPD:MHC04222 Caja-DRB1*03:16 777 bases
 ATGGTGTATA TGAGGCTCCC TGGAGGCTCC TGCATGGCAG TGCTGACAGT
 GATGCTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT GGAGTATAGC ACGTCTGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TTTAATCAGG AGGAGAACTT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTCCTGG AACAGCCAGA AGGACTTCCT GGAGGACAGG
 CGGGCCGCGG TGGACACCGT GTGCAGACAC AACTACGAGA TTTTAGACAG
 GTTCCTAGTG CCGCGGAGAG TCCAACCTAA GGTGACTGTG TATCCTGCAA
 AGGCCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAGTGGG
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACG ACCAGGAGGA
 GAAGACTGGG GTGGTGTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCCT GGTGATGCTG GAAACACTTC CTCAGAGTGG AGAGGTTTAC
 ACCTGCCAAG TGGAGCACCC AAGCGTGACC AGCCCTCTCA CAGTGCAATG
 GAGAGCACAG TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTCGGGG
 GCTCTGTGCT GGGCCTGCTC TTCCTTGGGG CAGGGCTGTT CATCTACTTC
 AGGAATCAGA AAGGACTCCT GAGCTGA*  
