>DL;IPD:MHC00134
IPD:MHC00134 Camo-DRB*W14:01 270 bases
 CACGTTTCTT GGAGCAGCTT AAGTTTGAGT GCCATCACTT CAACGGGACG
 GAGCGGGTGC GGCTGCTGGT CAGATTCTTC TATAACCAGG AGGAGTTTGT
 GCGCTTTGAC AGCGACGTGG GGGAGTTCCG GCCGGTGACG GAGCTGGGGC
 GGCCGGACGC GGAGTCCTGG AACAGCCGGG AGGACATCCT GGAGCGGAAG
 CGGGCCGAGG TGGACACGAT GTGCAGACAC AACTACGAGG TTTCAGAGAG
 GTTCCTAGTG CCGCGGAGAG *  
>DL;IPD:MHC00135
IPD:MHC00135 Camo-DRB*W14:02 254 bases
 CACGTTTCTT GGAGCAGCTT AAGGGTGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGCTCCTGGT GAGAAACATC CACAACCAGG AGGAGTTTGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GCCGGTGACG GAGCTGGGGC
 GGCCTGTCGC GGAGTCCTGG AACAGCCAGA AGGAACTCCT GGAGCGGAAG
 CGGGCCGAGG TGGACACGGT GTGCAGACAC AACTACGAGT TTTCAGAGAG
 GATC*    
>DL;IPD:MHC00136
IPD:MHC00136 Camo-DRB*W17:01 270 bases
 CACGTTTCTT GGAGCAGGTT AAGCACGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACATC CACAACCAGG AGGAGCTTGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGAGGC GGAGTCCTGG AACAGCCGGG AGGACATCCT GGAGGACGAG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGAGA TTTTAGAGAG
 GTTCCTAGTG CCGCGGAGAG *  
>DL;IPD:MHC00123
IPD:MHC00123 Camo-DRB1*03:01 270 bases
 CACGTTTCTT GGAGTACAGT ACGTCTGAGT GTTATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC CACAACCAGG AGGAGCTTGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTACTGG AACGGTCAGG AGGACTTCCT GGAGCGGAAG
 CGGGGCCAGG TGGACAACTA CTGCAGACAC AACTACGGGG TTTTTGAGAG
 CTTCACAGTG CAGCGGAGAG *  
>DL;IPD:MHC00124
IPD:MHC00124 Camo-DRB1*03:02 270 bases
 CACGTTTCTT GGAGTACAGT ACGTCTGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA AAGATTCTTC TATAACCAGG AGGAGTATGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GCCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTACTGG AACGGTCAGG AGGACTTCCT GGAGCAGAAG
 CGGGGCCAGG TGGACAACTA CTGCAGACAC AACTACGAGA TTTCAGAGAG
 GTTCCTAGTG CCGCGGAGAG *  
>DL;IPD:MHC00125
IPD:MHC00125 Camo-DRB1*03:03 270 bases
 CACGTTTCTT GGAGCACGTT AAGCACGAGT GTCATTTCTT CAACGGGACA
 GAGCGGGTGC GGTTCCTGGT GAGAGACATC TATAACCAGG AGGAGCATGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTACTGG AACAGCCAGA AGGAACTCCT GGAGCAGAAG
 CGGGGCCAGG TGGACAACTA CTGCAGACAC AACTACGAGA TTTTAGAGAG
 GTTCCTAGTG CCGCGGAGAG *  
>DL;IPD:MHC00126
IPD:MHC00126 Camo-DRB1*03:04 270 bases
 CACGTTTCTT GGAGTACAGT ACGTCTGAGT GTCATTTCTT CAACGGGACA
 GAGCGGGTGC GGTTCCTGGA AAGATTCTTC TATAACCAGG AGGAGTATGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GCCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTACTGG AACGGTCAGG AGGACTTCCT GGAGCAGAAG
 CGGGGCCAGG TGGACAACTA CTGCAGACAC AACTACGAGA TTTCAGAGAG
 GTTCCTAGTG CCGCGGAGAG *  
>DL;IPD:MHC00127
IPD:MHC00127 Camo-DRB1*03:05 270 bases
 CACGTTTCTT GGAGCACGTT AAGCACGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GGTACCTGGA CAGATACTTC TATAACCAGA AGGAGTATGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GCCGGTGACG GAGCTGGGGC
 GGCCTGAGGC GGAGTACTGG AACGGTCAGG AGGACTTCCT GGAGCAGAAG
 CGGGGCCAGG TGGACAACTA CTGCAGACAC AACTACGAGA TTTTAGAGAG
 GTTCCTAGTG CCGCGGAGAG *  
>DL;IPD:MHC00122
IPD:MHC00122 Camo-DRB11*01:01 270 bases
 CACGTTTCTT GGAGCACCAT AAGGCTGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GGCTCCTGGA AAGATACATC CACAACCAGG AGGAGTTTGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGAGCG GGAGTACTGG AACAGCCGGG AGGACTTCCT GGAGCAGATG
 CGGGCCGCGG TGGACACGGT GTGCAGACAC AACTACGAGA TTTCAGAGAG
 GTTCCTAGTG CCGCGGAGAG *  
>DL;IPD:MHC00128
IPD:MHC00128 Camo-DRB3*05:01 270 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCGTTTCTT CAACGGGACG
 GAGCAGGTGC GGTTCCTGGA AAGACACATC TACAACCAGG AGGAGTTCCT
 CCTCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGATC GCGCTGGGGC
 GGCCGGAAGG AGAGTCCTGG AACCGCCGGA AGGAACTCCT GGAGCGGAAG
 CGGGGCCAGG TGGACAAGTA CTGCAGACAC AACTACAGGG TTGGTGAGAG
 CTTCACAGTG CAGCGGCGAG *  
>DL;IPD:MHC00129
IPD:MHC00129 Camo-DRB3*05:02 270 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCGTTTCTT CAACGGGACG
 GAGCAGGTGA GGTTCCTGGA AAGACACATC TACAACCAGG AGGAGTTCCT
 CCTCTTCGAC AGCGACGTGG GGGAGTATCG GGCGGTGGCC GCGCTGGGGC
 GGCCGGAAGA AGAGTCCTGG AACCGCCGGA AGGAACTCCT GGAGCGGAAG
 CGGGGCCAGG TGGACAACTA CTGCAGACAC AACTACAGGG TTGGTGAGAG
 CTTCACAGTG CAGCGGCGAG *  
>DL;IPD:MHC00130
IPD:MHC00130 Camo-DRB3*05:03 270 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCGTTTCTT CAACGGGACG
 GAGCAGGTGC GGTTCCTGGA AAGACACATC TACAACCAGG AGGAGTTCCT
 CCTCTTCGAC AGCGACGTGG GGGAGTATCG GGCCGTGACC GCGCTGGGGC
 GGCCGGAAGA AGAGTCCTGG AACCGCCGGA AGGAACTCCT GGAGCGGAAG
 CGGGGCCAGG TGGACAAGTA CTGCAGACAC AACTACGGGG TTGGTGAGAG
 CTTCACAGTG CAGCGGCGAG *  
>DL;IPD:MHC00131
IPD:MHC00131 Camo-DRB3*05:04 255 bases
 CACGTTTCTC TGAGTGTCGT TTCTTCAACG GGACGGAGCA GGTGCGGTTC
 CTGGAAAGAC ACATCTACAA CCAGGAGGAG TTCCTCCTCT TCGACAGCGA
 CGTGGGGGAG TATCGGGCGG TGATCGCGCT GGGGCGGCCG GAAGGAGAGT
 CCTGGAACCG CCGGAAGGAA CTCCTGGAGC GGAAGCGGGG CCAGGTGGAC
 AACTACTGCA GACACAACTA CGGGGTTGGT GAGAGCTTCA CAGTGCAGCG
 GCGAG*    
>DL;IPD:MHC00132
IPD:MHC00132 Camo-DRB3*06:01 270 bases
 CACGTTTCTT GGAGCACGTT AAGGCTGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTACCTGGA AAGATACATC CACAACCAGG AGGAGCTTGT
 GCGCTTCGAC AGCGACGTGT GGGAGTACCG GCCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTACTGG AACAGCCAGA AGGACAGCCT GGAGGACGCG
 CGGGCCGCGG TGGACACCTT CTGCAGACAC AACTACGGAG TTGGTGAGAG
 CTTCACAGTG CAGCGGCGAG *  
>DL;IPD:MHC00133
IPD:MHC00133 Camo-DRB3*07:01 270 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA AAGATACTTC CACAACCAGG AGGAGCAGGT
 GCGCTTTGAC AGCGACGTGG GGGAGTACCG GCCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTCCTGG AACGGTCAGG AGGAACTCCT GGAGCGGAAG
 CGGGCCGAGG TGGACAACTA CTGCAGACAC AACTACGGGG TTGGTGAGAG
 CTTCACAGTG CAGCGGAGAG *  
