>DL;IPD:MHC00137
IPD:MHC00137 Ceap-DRB*W13:01 270 bases
 CACGTTTCTT GGAGCAGGCT AAGTCTGAGT GTCATTTCCT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CCGATACTTC TATAACCAGG AGGAGTATGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTAGCGC AGAGTACTGG AACAGCCAGA AGGACATCCT GGAGGACGCG
 CGGGGCCAGG TGGACAACTA CTGCAGACAC AACTACGGGG TTGGTGAGAG
 CTTCACAGTG CAGCGGAGAG *  
>DL;IPD:MHC00138
IPD:MHC00138 Ceap-DRB*W13:02 270 bases
 CACGTTTCTT GGAGCAGGCT AAGTCTGAGT GTCATTTCCT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CCGATACTTC TATAACCAGG AGGAGTATGT
 GCGCTTCGAC AGCGACGTCG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTAGCGC AGAGTACTGG AACAGCCAGA AGGACATCCT GGAGGACGCG
 CGGGGCCAGG TGGACAACTA CTGCAGACAC AACTACGGGG TTGGTGAGAG
 CTTCACAGTG CAGCGGAGAG *  
>DL;IPD:MHC00139
IPD:MHC00139 Ceap-DRB*W13:03 270 bases
 CACGTTTCTT GGAGCAGTTT AAGCCTGAGT GTCATTTCCT CAACGGGACG
 GAGCGGGTGC GGTACCTGCA GAGACTCATC TATAACCAGG AGGAGTATGC
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGTCGC AGAGTACCTG AACAGCCAGA AGGACTACCT GGAGCAGAGG
 CGGGCCGCGG TGGACAACTA CTGCAGACAC AACTACGGGG TTGGTGAGAG
 CTTCACAGTG CAGCGGAGAG *  
>DL;IPD:MHC00140
IPD:MHC00140 Ceap-DRB*W15:01 270 bases
 CACGTTTCTT GAGGCAGTTT AAGCCTGAGT GTCATTTCCT CAACGGCACG
 GAGCGGGTGC GGTCTTCGGA AAGACACATC TATAACCAGG AGGAGAACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTACTGG AACAGCCAGA AGGACTACAT GGAGCAGAGG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGAGA TTTCAGAGAG
 GTTCCTAGTG CCGCGGAGAG *  
>DL;IPD:MHC00141
IPD:MHC00141 Ceap-DRB*W15:02 270 bases
 CACGTTTCTT GAGGCAGTTT AAGCCTGAGT GTCATTTCCT CAACGGCACG
 GAGCGGGTGC GGCTCCTGGA AAGACACATC TATAACCAGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC GGAGTACTGG AACAGCCAGA AGGACTACAT GGAGCAGAGG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGAGA TTTCAGAGAG
 GTTCCTAGTG CCGCGGAGAG *  
>DL;IPD:MHC00142
IPD:MHC00142 Ceap-DRB*W32:01 225 bases
 CACGTTTCTT GGAGCAGTTT GAGCGTCGTC CCCTCAACGG GACGGAGCGC
 GCGCGGCTCC TGGTCAGACA CACCTACAAC CAGGAGGAGT ATGTGGGTTC
 GACGGCGCCG TGGGGGGCTC CGGCCGGTGA CGGAGCTGGG GCGGCCTGAC
 CAACAGTACT ACGACAGCCG GGAGGACATC ATGGAGCAGA CACGGGCCGC
 GGCGGACACT GTGTGCAGAC GCGAC*  
