>DL;IPD:MHC00143
IPD:MHC00143 Cemi-DQA1*01:01 188 bases
 TCTTACGGTT TCTCTGGCCA GTTCACCCAT GAATTTGATG GAGATGAGCA
 GTTCTACGTG GATCTGGAGA GGAAGGAGAC GGCCTGGCGA TGGCCTGAGT
 TAAGCAAATT TGGAGATTTT GACCCACAGG GTGCACTGAG AAACTTGGCT
 GTGTCAAAAC ACAACTTGAA CATCATAACC AAAGACTA* 
>DL;IPD:MHC00144
IPD:MHC00144 Cemi-DQA1*01:02 188 bases
 ACTTACGGTC TCTCTGGCCA GTTCACCCAT GAATTTGATG GAGATGAGCA
 GTTCTATGTG GACCTGAGGA GGAAGGAGAC GGCCTGGCGA TGGCCTGGGT
 TAAGCAAATT TGGAGGTTTT GACCCGCAGT GCACACTGAG AAACTTGGCT
 GTGTTAAAGC ACAACTTGAA CATCATGACT AAACGCTA* 
>DL;IPD:MHC00145
IPD:MHC00145 Cemi-DQA1*01:03 188 bases
 ACTTACGGTC TCTCTGGCCA GTTCACCCAT GAATTTGATG GAGATGAGCA
 GTTCTATGTG GACCTGAGGA GGAAGGAGAC GGCCTGGCGA TGGCCTGAGT
 TAAGCAAATT TGGAGGTTTT GACCCGCAGT GCAACATGAG AAACTTGGCT
 GTGTTAAAGC ACAACTTGAA CATCATGACT AAACGCTA* 
>DL;IPD:MHC00146
IPD:MHC00146 Cemi-DQA1*01:04 188 bases
 ACTTACGGTC TCTCTGGCCA GTTCACCCAT GAATTTGATG GAGATGAGCA
 GTTCTATGTG GACCTGAGGA GGAAGGAGAC GGCCTGGCGA TGGCCTGAGT
 TAAGCAAATT TGGAGGTTTT GACCCGCAGT GCACCATGAG AAACTTGGCT
 GTGTTAAAGC ACAACTTGAA CATCATGACT AAACGCTA* 
>DL;IPD:MHC00147
IPD:MHC00147 Cemi-DQA1*01:05 185 bases
 ACTTACGGTC TCTCTGGCCA GTTCACCCAT GAATTTGATG GAGATGAGCA
 GTTCTATGTG GACCTGAGGA GGAAGGAGAC GGCCTGGCGA TGGCCTGAGT
 TAAGCAAATT TGGAGGTTTT GACCCGCAGG CACTGAGAAA CTTGGCTGTG
 TTAAAGCACA ACTTGAACAT CATGACTAAA CGCTA* 
>DL;IPD:MHC00148
IPD:MHC00148 Cemi-DQA1*05:01 185 bases
 TTTTACGGTT TCTCTGGCCA GTACTCCCAT GAATTTGACG GAGATGAGCA
 GTTCTACGTG GACCTGGAGA GGAAGGAGAC TGTCTGGCGG TTGCCTGTTC
 TCAGCCAATT TAGTTTCGAC GCGCAATTTG CACTGACAAA CATTGCTCTG
 GGAAAACAGA ACTTGAACTA CCTGATGAAA CAGTC* 
>DL;IPD:MHC00149
IPD:MHC00149 Cemi-DQA1*20:01 188 bases
 TCTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGACGAGGA
 GTTCTATGTG GACCTGGAGA GGAAGGAGAC TGTCTGGCAG TTGCCACTGT
 TCAGCAAATT TAGAAGCTTT GACCCGCAGG GTGCACTGAG AAACTTGGCT
 GTGGGAAAAC ACAACTTGAA CATCCTGATT AAAGACTC* 
>DL;IPD:MHC00150
IPD:MHC00150 Cemi-DQA1*20:02 185 bases
 TCTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGACGAGGA
 GTTCTATGTG GACCTGGAGA GGAAGGAGAC TGTCTGGCAG TTGCCACTGT
 TCAGCAAATT TAGAAGCTTT GACCCGCATG CACTGAGAAA CTTGGCTGTG
 GGAAAACACA ACTTGAACAT CCCGATTAAA GACTC* 
