>DL;IPD:MHC00151
IPD:MHC00151 Cene-DQA1*26:01 188 bases
 ACTTACGGTT TCTCTGGCCA GTTCACCCAT GAATTTGATG GAGACGAGCA
 GTTCTACGTG GACCTGGAGA GGAAGGAGAC TGTCTGGCGG CTGCCTCTGT
 TCAGCAAATT TGGAGGTTTT GACCCGCAGG GTGCACTGAG AAACTTGGCT
 GTGGGAAAAC ACAACTTGAA CATCCTGATT AAACACTC* 
>DL;IPD:MHC00152
IPD:MHC00152 Cene-DQA1*26:02 187 bases
 ACTTACGGTT TCTCTGGCCA GTTCACCCAT GAATTTGATG GAGACGAGCA
 GTTCTACGAG GACCTGGAGA GGAAGGAGAC TGTCTGGCGG CTGCCTCTGT
 TCAGCAAATT TGGAGGTTTT GACCCGCAGG GTGCACTGAG AAACTTGGCT
 GTGGGAAAAC ACAACTTGAA CATCCTGATT AATCGCT* 
