>DL;IPD:MHC04086
IPD:MHC04086 Chae-B*01:01 1039 bases
 AACCCTCCTC CTGCTGCTCT CGGGGACCCT GGCCCTGACC GAGACCTGGG
 CCGGCTCGCA CTCCATGAGG TATTTCAGCA CCGCCGTGTC CCGGCCCGGC
 CGCCGGGAAC CCTGGTATCT CGCAGTCGGC TACGTGGATG ACACGCAGTT
 CGTGTGGTTC GACAGCGACG CCGAGAGTCC GAGGATGGAG CCGCGGGCGC
 CGTGGATAGA GCAGGAGGAG CCGGAGTATT GGGAAGAGCA GACACGGAGA
 GCCAAGGGAA ACGCACAGGC TGACCGAGGG AACCTGCGGA CCCTGCTCCG
 CTACTACAAC CAGAGCGAGG GGGGGTCTCA CACCTTCCAG TGGATGTACG
 GCTGCGACCT GGGACCCGAC GGGCGTCTCC TCCGCGGGTA TCACCAGTCC
 GCCTACGACG GCAAGGATTA CATCGCCCTG AACGAGGACC TGCGCTCCTG
 GACCGCGGCG GACATGGCGG CTGGGTTCAC CCAGCGCAAG TGGGAGGCAG
 CCCGTGCGGC GGAGCGGTTC AGAGCCTACC TGGAGGGCGA GTGCCTGGAG
 TGGCTCCGCA GACACCTGGA GAACGGGAAG GAGACGCTGC AGCGCGCGGA
 ACCCCCAAAG ACACACGTGA CCCACCACCC CATCTCTGAC CATGAGGCCA
 CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CACACTGACC
 TGGCAACGGG ATGGGGAGGA TCAAACTCAG GACACCGAAC TTGTGGAGAC
 CAGGCCAGGA GGAGATGGAA CCTTCCAAAA GTGGGGAGCT GTGGTGGTGC
 CTTCTGGAGA AGAGCAGAGA TACACGTGCC ATGTGCAGCA CGAGGGATTG
 ACGGAGCCCC TCACCCTGAG ATGGGAGCCA TCTTCCCAGT CCACCATCCC
 CATCGTGGGC ATTGTTGCTG GCCTGGCTGT CCTAGCAGTT GTGTTCATCG
 GAGCTGTGGT CGCTGCTATG ATGAGGAAGA AGTGCTCAGG TGGAAAAGGA
 GGGAGCTACT CTCAGGCTGC GTCCAAGGAC AGTTCCCAG* 
>DL;IPD:MHC04085
IPD:MHC04085 Chae-B*02:01 1051 bases
 AACCCTGCTC CTGCTGCTCT CGGGGGCCCT GGCCCTGACC GAGACCTGGG
 CCGGCTCGCA CTCCTTGAGG TATTTCCACA CCGCCGTGTC CCGGCCCGGC
 CGCTGGGAGC CCCACTTCAT CTCCGTGGGC TACGTGGACG ACACGCAGTT
 CGTGCGGTTC GACAGCGACG CCGAGAGTCC GAGAGAGGAG CCGCGGGCGC
 CGTGGGTGGA GCAGGAGGGG CCGGAGTATT GGGACCGGAA CACACGGAGA
 GCCAAGGCCC ACGCACAGAC TGACCGAAGG AACCTGCGGA CCCTGCTCCG
 CTACTACAAC CAGAGCGAGT GGGGGTCTCA CACCCTCCAG AGGATGTGCG
 GCTGCGACCT GGGGCCGGAC GGGCGCCTCC TCCGCGGGTA TCACCAGTCC
 GCCTACGACG GCAAGGATTA CATCGCCCTG AACGAGGACC TGCGCTCCTG
 GACCACCGCG GACATGGCGG CTCAGAGCAC CCAGCGCAAG TGGGAGGCGG
 CCGGTGTGGC GGAGCAGATT AGAGCCTACC TGGAGGGGAC ATGCGTGGAG
 TGGCTCCGCA GACACCTGGA GAACGGGAAG GAGACGCTGC AGCGCGCGGA
 TCCCCCAAAG ACACACGTGA CCCACCACCC CGTCTCTGAC CATGAGGCCA
 CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CACATTGACC
 TGGCAGCGGG ATGGGGAGGA GCAAACTCAG GACACCGAGC TTGTGGAGAC
 CAGGCCAGGA GGAGATGGAA CCTTCCAGAA GTGGGGAGCT GTGGTGGTAC
 CTTCTGGAGA GGAGCAGAGA TACACCTGTC ATGTGCAACA TGAGGGTCTG
 CCCGAGCCCC TCACCTTGAG ATGGGAGCCA TCTTTCCAGT CTACCATCCT
 CATCGTAGGC ATCATTGCTG GCCTGGTTCT CCTTGGAACT GTGGTCACTG
 GAGCTGTGGT TGCTGCTGTG ATGTGGAGGA GGAAGAGCTC AGATAGAAAA
 GGAGGGAGCT ACTCTCAGGC TGCAAGCAGT GACAGTGCCC AAGGTTCTGA
 T*    
