>DL;IPD:MHC00175
IPD:MHC00175 Chae-G*02:01 503 bases
 CGCCGTGTCC CGGCCCGGCC GCGGGGAGCC CCGCTTCATC CCTGTGGGCT
 ATGTGGACGA CACGCAGTTC GTGCGGCTGG ATAGCGACAC TGCGAGTCCC
 AGGATGGAGC CGCGGGCGCG GTCGGTGGAG CAGGAGTGGC CGGAGTATTG
 GGAAGAGGAG ACACGGAACA CCAAGGCCCA CGCACAGACT GACAGAGTGA
 ACCTGCGGAC CCTGCGCAGC TACTATAACC AGAGCCAGGT CGGGTCTCAC
 ACCCTCCAGT GGATGATTGG TTGCGACCTG GGGCCCGACG GGCGCCTCCT
 CCGCAGGTGT GAACAGTTCG CCTACGATGG CAAGGATTAC CTCGCCCTGA
 ACGAGGACCT GTGCTCCTGA ACCGCAGCGG ACACTGTGGC TCAGATCTCC
 AAGCGCAAGC GTGAGGCGGC CAAAGTGACT GAACGAAGGA GAGCCTACCT
 GGAGGGTGCG TGAGTGGAGT GGCTCCACAG ATACCTGGAG AATGGGAAGG
 AGA*    
>DL;IPD:MHC00176
IPD:MHC00176 Chae-G*02:02 503 bases
 CGCCGTGTCC CGGCCCGGCC GCGGGGAGCC CCGCTTCATC CCTGTGGGCT
 ATGTGGACGA CACGCAGTTC GTGCGGCTGG ATAGCGACAC TGCGAGTCCC
 AGGATGGAGC CGCGGGCGCG GTCGGTGGAG CAGGAGTGGC CGGAGTATCG
 GGAAGAGGAG ACACGGAACA CCAAGGCCCA CGCACAGACT GACAGAGTGA
 ACCTGCGGAC CCTGCGCAGC TACTATAACC AGAGCCAGGT CGGGTCTCAC
 ACCCTCCAGT GGATGATTGG TTGCGACCTG GGGCCCGACG GGCGCCTCCT
 CCGCAGGTGT GAACAGTTCG CCTACGATGG CAAGGATTAC CTCGCCCTGA
 ACGAGGACCT GTGCTCCTGA ACCGCAGCGG ACACTGTGGC TCAGATCTCC
 AAGCGCAAGC GTGAGGCGGC CAAAGTGACT GAACGAAGGA GAGCCTACCT
 GGAGGGTGCG TGAGTGGAGT GGCTCCACAG ATACCTGGAG AATGGGAAGG
 AGA*    
