>DL;IPD:MHC04083
IPD:MHC04083 Chae-A*01:01 350 bases
 TLLLVLSGVL ALTQTRAGSH SMRYFYTYMS RPGRGEPRFI AVGYVDDTQF
 VRFDSDAASQ RMEPRAPWVE QEGPEYWDRS TRIMKTETQM APVGLRNLRG
 YYNQSEAGSH TYQRMYGCDL GPDGRLLRGY HQLAYDGKDY IALNEDLRSW
 TAADLAAQNT QRKWEASGWV EQFRTYLEGE CLEWLRRYLE NGKETLQRAE
 PPKTHVTHHP VSDHETTLRC WALGFYPAEI TLTWQRDGEE QTQDTELVET
 RPSGNGTFQK WAAVVVPSGK EQRYTCHVQH EGLREPLTLR WEPSSQSTIP
 IVGIIAGLVL LGAVVTGAVV AAVMWRRKSS DRKGGSYAQA ASSDSAQGSD
>DL;IPD:MHC04084
IPD:MHC04084 Chae-A*02:01 350 bases
 TLLLVLSGAL VLTETWAGSH SLRYFYTSMS RPGRGEPRFI SVGYVDNTQF
 VRFDSDAESP REEPRAPWME QEGPEYWDRN TRIFKAETQT FRVGLQNLRG
 YYNQSEAGSH TIQEMYGCDL GPDGRLLRGY DQYAYDGRDY IALNEDLHSW
 TAADMAAQNT QRKWEAAGVA EQMRTYLEDE CLEWLRRYLE NGKETLQRAD
 PPKTHVTHHP VSDHEATLRC WALGFYPAEI TLTWQRDGED QTQDTELVET
 RPAGDGTFQK WAAVVVPSGK EQRYTCHVQH EGLPEPLTLR WEPSSQSTIP
 IVGIIAGLVL LGAVVTGAVV AAVMWRRKSS DRKGGSYSQA ASSDSAQGSD
