>DL;IPD:MHC04086
IPD:MHC04086 Chae-B*01:01 346 bases
 TLLLLLSGTL ALTETWAGSH SMRYFSTAVS RPGRREPWYL AVGYVDDTQF
 VWFDSDAESP RMEPRAPWIE QEEPEYWEEQ TRRAKGNAQA DRGNLRTLLR
 YYNQSEGGSH TFQWMYGCDL GPDGRLLRGY HQSAYDGKDY IALNEDLRSW
 TAADMAAGFT QRKWEAARAA ERFRAYLEGE CLEWLRRHLE NGKETLQRAE
 PPKTHVTHHP ISDHEATLRC WALGFYPAEI TLTWQRDGED QTQDTELVET
 RPGGDGTFQK WGAVVVPSGE EQRYTCHVQH EGLTEPLTLR WEPSSQSTIP
 IVGIVAGLAV LAVVFIGAVV AAMMRKKCSG GKGGSYSQAA SKDSSQ*
>DL;IPD:MHC04085
IPD:MHC04085 Chae-B*02:01 350 bases
 TLLLLLSGAL ALTETWAGSH SLRYFHTAVS RPGRWEPHFI SVGYVDDTQF
 VRFDSDAESP REEPRAPWVE QEGPEYWDRN TRRAKAHAQT DRRNLRTLLR
 YYNQSEWGSH TLQRMCGCDL GPDGRLLRGY HQSAYDGKDY IALNEDLRSW
 TTADMAAQST QRKWEAAGVA EQIRAYLEGT CVEWLRRHLE NGKETLQRAD
 PPKTHVTHHP VSDHEATLRC WALGFYPAEI TLTWQRDGEE QTQDTELVET
 RPGGDGTFQK WGAVVVPSGE EQRYTCHVQH EGLPEPLTLR WEPSFQSTIL
 IVGIIAGLVL LGTVVTGAVV AAVMWRRKSS DRKGGSYSQA ASSDSAQGSD
