>DL;IPD:MHC00172
IPD:MHC00172 Chae-DRB*W6:01 159 bases
 KQAKAECHFF NGTERVRFLE RHFYNQEEYV RFDSNVGEFR AVTELGRRSA
 EYFNSRKGYL EQARAAVDTY CRHNYGVVES FTVQRRVQPK VTVYPAKTQP
 LQHHTLLVCS VNGFYPGSIE VRWFRNGQEE KAGVVSTGLM QNGDWTFQTL
 VMLETVPQS*    
>DL;IPD:MHC00173
IPD:MHC00173 Chae-DRB*W7:01 159 bases
 QQQKAECHFF NGTERVRLLE RYFYNQEEYV RYDSDGGEYR AVTELGRPDA
 EYWNSQKDAL EQRRTEVDTV CRHNYGVGES FTVQRRVQPK VTVYPAKTQP
 LQHRNLLVCS VSGFYPGSIE VRWFRNDQEE KAGVVSTVLI QNGDWTFQTL
 VMLETVPRS*    
>DL;IPD:MHC00174
IPD:MHC00174 Chae-DRB*W7:02 159 bases
 QQQKAECHFF NGTERVRLLE RYFYNQEEYV RYDSDVGEFR AVTELGRPDA
 ESWNSQKDAL EQRRTEVDTV CRHNYGVGES FTVQRRVQPK VTVYPAKTQP
 LQHHNLLVCS VNGFYPGNIE VRWFRNDQEE KAGVVSTGLI QNGDWTFQTL
 VMLETVPRS*    
>DL;IPD:MHC00164
IPD:MHC00164 Chae-DRB1*03:01 159 bases
 EQVKSECHFF NGTERVRFLD RYFYNQEEYV RFDSDVGEFR AVSELGRHSA
 EYWNSRKDLL EDERASVDNY CRYNYGVVES FTVQRRVQPK VTVYPAKTQP
 LQHHTLLVCS VNGFYPGSIE VRWFRNGQEE KAGVVSTGLI QNGDWTFQTL
 VMLETVPQS*    
>DL;IPD:MHC00165
IPD:MHC00165 Chae-DRB1*03:02 159 bases
 EQVKSECHFF NGTERVRFLD RYFYNQEEYV RFDSDVGEFR AVSELGRHSA
 EYWSSRKDLL EDERPSVDNY CRYNYGVVES FTVQRRVQPK VTVYPAKTQP
 LQHHTLMVCS VNGFYPGSIE VRWFRSAQEE KAGVVPTGLI QNGDWTFQTL
 VMLETVPQS*    
>DL;IPD:MHC01278
IPD:MHC01278 Chae-DRB1*03:03 159 bases
 EQVKSECHFF NGTERVRFLD RYFYNQEEYV RFDSDVGEFR AVSELGRHSA
 EYWNSRKDLL EDERASVDNY CRYNYGVVES FTVQRRVQPK VTVYPAKTQP
 LQHHTLLVCS VSGFYPGSIE VRWFRNGQEE KAGVVSTGLI QNGDWTFQTL
 VMLETVPQS*    
>DL;IPD:MHC00166
IPD:MHC00166 Chae-DRB1*03:04 159 bases
 EQVKSECHFF NGTERVRFLD RYFYNQEEYV RFDSDVGEFR AVSELGRHSA
 EYWNSQKDIL EDERASVDNY CRYNYGVVES FTVQRRVQPK VTVYPAKTQP
 LQHHTLLVCS VNGFYPGSIE VRWFRNGQEE KAGVVSTGLI QNGDWTFQTL
 VMLETVPRS*    
>DL;IPD:MHC00167
IPD:MHC00167 Chae-DRB1*07:01 159 bases
 WQAKAKCHFF NGTERVRYLE RHFYNQEELV RFDSDVGEYR AVSELGRPDA
 EYWNSLKDYL EQARAAVDNY CRHSYGVVES FTVQRRVQPK VTVYPAKTQP
 LQHHNLLVCS VNGFYPGSIE VRWFRNSQEE KAGVVSTGLI HNGDWTFQTL
 VMLETVPRS*    
>DL;IPD:MHC00168
IPD:MHC00168 Chae-DRB1*07:02 159 bases
 WQAKAKCHFF SGTERAQYLE RHFYNQEELV RFDSDVGEYR AVSELGRPDA
 EYWNSLKDYL EQARPAMDNY CRHNYGVVES FTVQRRVQPK VTVYPAKTQP
 LQHHNLLVCS VNGFYPGSIE VRWFRNSQEE KAGVVSTGLI HNGDWTFQTL
 VMLETVPRS*    
>DL;IPD:MHC00169
IPD:MHC00169 Chae-DRB1*07:03 159 bases
 WQAKAKCHFF NGTERVRYLE RHFYNQEELV RFDSDVGEYR AVSELGRPDA
 EYWNSLKDYL EQKRAAVDNY CRHNYGVGES FTVQRRVQPK VTVYPAKTQP
 LQHHNLLVCS VNGFYPGSIE VRWFRNSQEE KAGVVSTGLI HNGDWTFQTL
 VMLETVPRS*    
>DL;IPD:MHC00170
IPD:MHC00170 Chae-DRB5*01:01 159 bases
 KQDMHECHFF NGTERVRYLH RDIYNQEEDL RFDSDVGEYR AVTELGRPDA
 EYWNSRKDIL EDRRASVDNV CRHNYRVVES FTVQRRVEPK VTVYPSKTQP
 LQHHNLLVCS VNGFYPGSIE VRWFRNAQEE KAGVVSTGLI HNGDWTFQIL
 VMLETVPRS*    
>DL;IPD:MHC00171
IPD:MHC00171 Chae-DRB6*01:01N 66 bases
 EQAKCECRIF NGTERVRYLN RYIHKREENL RFHSDVGEFQ AVTELGRPVA
 ENWNSQKGNL EEKRDX*   
