>DL;IPD:MHC00175
IPD:MHC00175 Chae-G*02:01 123 bases
 AVSRPGRGEP RFIPVGYVDD TQFVRLDSDT ASPRMEPRAR SVEQEWPEYW
 EEETRNTKAH AQTDRVNLRT LRSYYNQSQV GSHTLQWMIG CDLGPDGRLL
 RRCEQFAYDG KDYLALNEDL CSX*  
>DL;IPD:MHC00176
IPD:MHC00176 Chae-G*02:02 123 bases
 AVSRPGRGEP RFIPVGYVDD TQFVRLDSDT ASPRMEPRAR SVEQEWPEYR
 EEETRNTKAH AQTDRVNLRT LRSYYNQSQV GSHTLQWMIG CDLGPDGRLL
 RRCEQFAYDG KDYLALNEDL CSX*  
