>DL;IPD:MHC04792
IPD:MHC04792 Chsa-E*02:01:01 1080 bases
 ATGGCACTAG GAACCCTACT TCTCCTGCTC TCGGCCCTTA CCAAGACCTG
 GGCGGGCTCC CACTCCTTGA AGTATTTCCA CACTTCCGTG TCCCGGCCCG
 GCCGCGGGGA GCCCCGCTTC ATCTCCGTGG GCTACGTGGA CGACACCCAG
 TTCGTGCGGT TCGACAGCGA TGCCGCGAGT CCGAGGATGC AGCCGCGGGC
 GCCGTGGGTG GAGCAGGAGG GGCCGGAGTA TTGGGACCAG GAGACACGGA
 GCGCCAGGGA CACCGCACAG ACTTTCCGAG TGAACCTGAA TACCCTGCGC
 GGCTACTACA ACCAGAGCGA GGCCGGGTCT CATACCCTCC AGTGGATGCA
 TGGCTGCGAC CTGGGGCCCG ACGGGCGCTT CCTCCGCGGG TATGAACAGT
 TTGCCTACGA CGGCAAGGAT TATCTCACCC TGAATGAGGA CCTGCGCTCC
 TGGTCCGCGG TGGACACGGC GGCTCAAATC TCCGAGCAAA AGTCAAATGA
 TGGCTCTGAG GCGGAGCACC AGAGAGCCTA CCTGGAAGAC ACATGCGTGG
 AGTGGCTCCG CAGATACCTG GAGAATGGGA AGGAGACGCT GCAGCGCTCG
 GAACCCCCAA AGACACACGT GACCCACCAC CCCGTCTCTG ATCATGAGGC
 CACCCTGAGG TGCTGGGCCC TGGGCTTCTA CCCTGCGGAG ATCACAGTGA
 CCTGGCAGCG GGATGGGGAG GACCAGACCC AGGACATGGA GCTTGTGGAG
 ACCAGGCCTG CAGGGGATGG AACTTTCCAG AAGTGGGCAG CTGTGGTGGT
 ACCTTCTGGA GAGGAGCAGA GATACACGTG CCATGTGCAG CATGAGGGGC
 TACCCGAGCC CCTCACCCTG AGATGGGAGC CATCTTCCCA GTCCACCATC
 CCCATCGTGG GCATCATTTC TTGCCTGTTT CTCCTTGGAG CTGTGGTCAC
 TGGAGCTGTG GTTGCTGCTG TGATGTGGAG GAGGAAGAGC TCAGGTAGAA
 AAGGATGGAG CTACTCTCAG GCTGAGTGTG GTGACAGTGC CCAGGGATCT
 GATGTGTCTC TCACAGCTTG TAAAGCCTGA * 
>DL;IPD:MHC04794
IPD:MHC04794 Chsa-E*02:01:02 871 bases
 ATGGCACTAG GAACCCTACT TCTCCTGCTC TCGGCCCTTA CCAAGACCTG
 GGCGGGCTCC CACTCCTTGA AGTATTTCCA CACTTCCGTG TCCCGGCCCG
 GCCGCGGGGA GCCCCGCTTC ATCTCCGTGG GCTACGTGGA CGACACCCAG
 TTCGTGCGGT TCGATAGCGA TGCCGCGAGT CCGAGGATGC AGCCGCGGGC
 GCCGTGGGTG GAGCAGGAGG GGCCGGAGTA TTGGGACCAG GAGACACGGA
 GCGCCAGGGA CACCGCACAG ACTTTCCGAG TGAACCTGAA TACCCTGCGC
 GGCTACTACA ACCAGAGCGA GGCTGGGTCT CATACCCTCC AGTGGATGCA
 TGGCTGCGAC CTGGGGCCCG ACGGGCGCTT CCTCCGCGGG TATGAACAGT
 TTGCCTACGA CGGCAAGGAT TATCTCACCC TGAATGAGGA CCTGCGCTCC
 TGGTCCGCGG TGGACACGGC GGCTCAAATC TCCGAGCAAA AGTCAAATGA
 TGGCTCTGAG GCGGAGCACC AGAGAGCCTA CCTGGAAGAC ACATGCGTGG
 AGTGGCTCCG CAGATACCTG GAGAATGGGA AGGAGACGCT GCAGCGCTCG
 GAACCCCCAA AGACACACGT GACCCACCAC CCCGTCTCTG ATCATGAGGC
 CACCCTGAGG TGCTGGGCCC TGGGCTTCTA CCCTGCGGAG ATCACAGTGA
 CCTGGCAGCG GGATGGGGAG GACCAGACCC AGGACATGGA GCTTGTGGAG
 ACCAGGCCTG CAGGGGATGG AACTTTCCAG AAGTGGGCAG CTGTGGTGGT
 ACCTTCTGGA GAGGAGCAGA GATACACGTG CCATGTGCAG CATGAGGGGC
 TACCCGAGCC CCTCACCCTG A*  
>DL;IPD:MHC04793
IPD:MHC04793 Chsa-E*02:02 1080 bases
 ATGGCACTAC GAACCCTACT TCTCCTGCTC TTGGCCCTTA CCGAGACCTG
 GGCGGGCTCC CACTCCTTGA AGTATTTCCA CACTTCCGTG TCCCGGCCCG
 GCCGCGGGGA GCCCCGCTTC ATCTCCGTGG GCTACGTGGA CGACACCCAG
 TTCGTGCAGT ACGACAGCGA TGCGGCGAGT CCGAGGATGG AGCCGCGGGC
 GTGGTGGATG GAGCAGGAGC GGTCGGAGTA TTGGGACCAG GAGACACGGA
 GCGCCAGGGA CACCGCACAG GCTTTCCGAA TGAACCTGCA GACCCTGCGC
 GGCTACTACA ACCAGAGCGA GACCGGGTCT CATACCCTCC AGTGGATGCA
 TGGCTGCGAC CTGGGGCCGG ACGGGCGCTT CCTCCGCGGA TATGAACAGT
 TCGCCTACGA CGGCAAGGAT TATCTCACCC TGAATGAGGA CCTGCGCTCC
 TGGTCCGCGG TGGACACGGC GGCTCAGATC TCCGCGCGAA AGTCAAATGA
 TGGCTCTGAG GCGGAGCACC AGAGAGCCTA CCTGGAAGAC ACATGCGTGG
 AGTGGCTCCG CAGATACCTG GAGAATGGGA AGGAGACGCT GCAGCGCCCG
 GAACCCCCAA AGACACACGT GACCCACCAC CCCGTCTCTG ATCATGAGGC
 CACCCTGAGG TGCTGGGCCC TGGGCTTCTA CCCTGCGGAG ATCACAGTGA
 CCTGGCAGCG GGATGGGGAG GACCAGACCC AGGACACGGA GCTTGTGGAG
 ACCAGGCCTG CAGGGGATGG AACTTTCCAG AAGTGGGCAG CTGTGGTGGT
 ACCTTCTGGA GAGGAGCAGA GATACACGTG CCATGTGCAG CATGAGGGGC
 TACCTGAGCC CCTCACCCTG AGATGGGAGC CGTCTTCCCA GTCCACCATC
 CCCGTCGTGG GCATCATTGC TGGCCTGTTT TTCCTTGGAG CTGTGGTCAC
 TGGAGCCTTG GTTGCTGCTG TGATGTGGAG GAGGAAGAGC TCAGGTAGAA
 AAGGAGGGAG CTACTCTCAG GCTGTGTGTA GCGACGGTGC CCAGGGATCT
 GATGAGTCTC TCACAGCTTA AAAACCCTGA * 
