>DL;IPD:MHC04792
IPD:MHC04792 Chsa-E*02:01:01 360 bases
 MALGTLLLLL SALTKTWAGS HSLKYFHTSV SRPGRGEPRF ISVGYVDDTQ
 FVRFDSDAAS PRMQPRAPWV EQEGPEYWDQ ETRSARDTAQ TFRVNLNTLR
 GYYNQSEAGS HTLQWMHGCD LGPDGRFLRG YEQFAYDGKD YLTLNEDLRS
 WSAVDTAAQI SEQKSNDGSE AEHQRAYLED TCVEWLRRYL ENGKETLQRS
 EPPKTHVTHH PVSDHEATLR CWALGFYPAE ITVTWQRDGE DQTQDMELVE
 TRPAGDGTFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPLTL RWEPSSQSTI
 PIVGIISCLF LLGAVVTGAV VAAVMWRRKS SGRKGWSYSQ AECGDSAQGS
 DVSLTACKAX *   
>DL;IPD:MHC04794
IPD:MHC04794 Chsa-E*02:01:02 290 bases
 MALGTLLLLL SALTKTWAGS HSLKYFHTSV SRPGRGEPRF ISVGYVDDTQ
 FVRFDSDAAS PRMQPRAPWV EQEGPEYWDQ ETRSARDTAQ TFRVNLNTLR
 GYYNQSEAGS HTLQWMHGCD LGPDGRFLRG YEQFAYDGKD YLTLNEDLRS
 WSAVDTAAQI SEQKSNDGSE AEHQRAYLED TCVEWLRRYL ENGKETLQRS
 EPPKTHVTHH PVSDHEATLR CWALGFYPAE ITVTWQRDGE DQTQDMELVE
 TRPAGDGTFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPLTL *
>DL;IPD:MHC04793
IPD:MHC04793 Chsa-E*02:02 357 bases
 MALRTLLLLL LALTETWAGS HSLKYFHTSV SRPGRGEPRF ISVGYVDDTQ
 FVQYDSDAAS PRMEPRAWWM EQERSEYWDQ ETRSARDTAQ AFRMNLQTLR
 GYYNQSETGS HTLQWMHGCD LGPDGRFLRG YEQFAYDGKD YLTLNEDLRS
 WSAVDTAAQI SARKSNDGSE AEHQRAYLED TCVEWLRRYL ENGKETLQRP
 EPPKTHVTHH PVSDHEATLR CWALGFYPAE ITVTWQRDGE DQTQDTELVE
 TRPAGDGTFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPLTL RWEPSSQSTI
 PVVGIIAGLF FLGAVVTGAL VAAVMWRRKS SGRKGGSYSQ AVCSDGAQGS
 DESLTAX*    
