>DL;IPD:MHC04201
IPD:MHC04201 Chsa-B*01:01 692 bases
 ATGCAGGTCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CGGGGACCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCATGAGG TATTTCAGCA
 CCGCCGTGTC CCGGCCCGGC CGCCGGGAAC CCTGGTATCT CGCAGTCGGC
 TACGTGGATG ACACGCAGTT CGTGTGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGATAGA GCAGGAGGAG CCGGAGTATT
 GGGAAGAGCA GACACGGAGA GCCAAGGGAA ACGCACAGGC TGACCGAGGG
 AACCTGCGGA CCCTGCTCCG CTACTACAAC CAGAGCGAGG GGGGGTCTCA
 CACCTTCCAG TGGATGTACG GCTGCGACCT GGGACCCGAC GGGCGTCTCC
 TCCGCGGGTA TCACCAGTCC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCGGCG GACATGGCGG CTGGGTTCAC
 CCAGCGCAAG TGGGAGGCAG CCCGTGCGGC GGAGCGGTTC AGAGCCTACC
 TGGAGGGCGA GTGCCTGGAG TGGCTCCGCA GACACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA ACCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GG*
>DL;IPD:MHC04194
IPD:MHC04194 Chsa-B*02:01 692 bases
 ATGCGGGTCA TGGCGCCCCG AACCCTGCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCCACA
 CCGCCGTGTC CCGGCCCGGC CGCTGGGAGC CCCACTTCAT CTCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGAGAGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGAA CACACGGAGA GCCAAGGCCC ACGCACAGAC TGACCGAAGG
 AACCTGCGGA CCCTGCTCCG CTACTACAAC CAGAGCGAGT GGGGGTCTCA
 CACCCTCCAG AGGATGTGCG GCTGCGACCT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TCACCAGTCC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCACCGCG GACATGGCGG CTCAGAGCAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGTGGC GGAGCAGATT AGAGCCTACC
 TGGAGGGGAC ATGCGTGGAG TGGCTCCGCA GACACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GG*
>DL;IPD:MHC04199
IPD:MHC04199 Chsa-B*03:01 974 bases
 ATGCGGGTCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC CAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCAGCA
 CCGCCGTGTC CCGGCCCGGC CGCCGGGAAC CCTGGTATCT CGAAGTCGGC
 TACGTGGATG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCAGAGTATT
 GGGAAGAGGC GACACGGAGA GCCAAGGGCA ACGCACAGAC TCACCGAGGG
 AACCTGAGGA CCGCGCTCCG CTACTACAAC CAGAGCGAGG GGGGGTCTCA
 CACCCTCCAG TGGATGTACG GCTGCGACCT GGGGCCCGAC GGGCGCCTCC
 TCCGCGGGTA TGAACAGTTC GCTTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCCGCG GACATGGCGG CTCGGTTCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGCGGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGCAA GTGCCTGGAG TGGCTCCGCA GATACCTGGA GAACCAGAAG
 GAGTCCCTGC TGCGCGCGGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA GCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA CCTTCCAAAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACGTGCC
 ATGTGCAGCA CGAGGGATTG CTGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGC*  
>DL;IPD:MHC04195
IPD:MHC04195 Chsa-B*04:01 1089 bases
 ATGCGGGTCA TGGCGCCCCG AATCCTCCTC CTGCTGCTCT CGGGTGCCCT
 GGCCCTGACG GAGACCTGGG CCGGCTCCCA CTCCTTGAGG TATTTCGACA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGACC TCTGGTATCT CGAAGTCGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGAAG CCGCGGGCGC CGTGGGTGGA ACAGGAGGGG CCGGAGTATT
 GGGAAGAGCA GACACGGAAC GCCAAGGTCA GCGCACAGAC TGACCGAGGG
 AACCTGCGGA CCGCGCTCCG CTACTACAAC CAGAGCGAGG CGGGGTCTCA
 CACCATCCAG AGGATGTACG GCTGCGACCT GGGACCCGAC GGGCGCTTCC
 TCCGCGGGTA TCACCAGTCC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCGGCG GACATGGCGG CTCAGAACAC
 CCAGCGGAAG TGGGAGGCGG CCGGTGAGGC GGAGAGGGTG AGAGCCTACC
 TGGAGGGGCG GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCACAGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 GGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGGTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGA ATGGGGAGGA CCAAACTCAG
 GACACGGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA CCTTCCAGAA
 GTGGGGAGCT GTGATGGTGC CTTCTGGAGA AGAGCAGAGA TACACGTGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAACCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTGGCAGTT GTGGTCACCG GAGCTGTGGT CGCTGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC04204
IPD:MHC04204 Chsa-B*05:01 659 bases
 CTGGTCTCGG GGACCCTGAT CCTGACCCAG ACCTGGGCGG GCTTGCACTC
 CTTGAGGTAC TTCAGCACCG CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCTC CGTGGGCTAC GTGGACAACA CGCAGATCCT GCGGTTCAAC
 AGCGACGCGG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT GGTTGGAGCA
 GGAGGGGCCG GAGTATTGGG AAGAGCAGAC AGGGCTCGCC AAGGCCAACG
 CACAGACTTT CCGAGGGTGC CTGCGGACCG TGCCCGGCTA CTACAACCAG
 AGCGAGGCCG GGTCTCACAC CTTCCAGTGG ATGTACGGCT GCGACCTGGG
 ACCCGACGGG CGCCTCCTCC GCGGGTATCA TCGGTTCGCC TACGACGGCC
 AGGATTACAT CGCCCTGAAC CGGGACCTGC GCTCCTGGAT CGCGGCGGAC
 ACGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCGGCCC GCGAGGCAGA
 GCAGATAAGA GCCCACCTGG AGGGGACGTG CGTGGAGTGG CTCCGCAGAT
 ACCTGGAGAA CGGGGAGGAG ACGCTGCAGC GCGCGGACCC CCCAAAGACA
 CACGTGACCC ACCACCCCGT CTCTGACCAT GAGGCCACCC TGAAGTGCTG
 GGCCCTGGG*    
>DL;IPD:MHC04206
IPD:MHC04206 Chsa-B*06:01 692 bases
 ATGCAGGTCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCAGCA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCTGGTATCT CGAAGTCGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGATGAA GCAGGAGGGG CCGGAGTATT
 GGGACCGGGA GACACGGAGA GCCAAGGCCA ACGCACAGTG TTTCCAAGGG
 AACCTGCGGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACTCTCCAG ACGATGTCCC GCTGCGACCT GGGGCCCGAC GGGCGCCTCC
 TCCGCGGGTA TTATCAGCAA GCCTACGATG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCTGCG GATGAGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGAGGC AGAGCAGCTG AGAGCCTACC
 TGGAGGGGAC ATGCGTGGAG TGGCTCCGCA GACACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GG*
>DL;IPD:MHC04200
IPD:MHC04200 Chsa-B*07:01 692 bases
 ATGCGGGTCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGGGG TATTTCTACA
 CGGCCGAGTC CCGGCCCCGC CGCGGGGAGC CCCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCAACG CCGCGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGATGAA GCAGGAGGGG CCGGAGTATT
 GGGAAGAGCA GACACAGAGA GTCCAGGGCC ACGCACAGAC TTTCCGGGTG
 AGCCTGCGGA ACCTGCTCCG CTACTACAAC CAGAGCAAGG CCGGGTCTCA
 CACCCTCCAG AGGATGTCTG GCTGCGACCT GGGACCCGAC GGGCGCCTCC
 TCCGCGGGTA TGACCAGTAC GCCTACGACG GCAAGGATTA TATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCCGCG GACACTGCGG CTCAGAAAAC
 CCAGCGCAAG TGGGAGGCGG CACGTGCGGC GGAGAAGCTG AGAGCCTACC
 TGGAGGGCGA GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACCAGAAG
 GAGATGCGGC AGCGCGCGGA TCCCCCAAAG ACAAACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GG*
>DL;IPD:MHC04189
IPD:MHC04189 Chsa-B*08:01 1089 bases
 ATGAGGATCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT TGGGGGTCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCTTGAGG TATTTCGCCA
 CCGCCGTGTC CCGGCCCGGC CGCCGGGAGC CCCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGAGGTTC GACAGTGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGATGAA GCAGGAGGGG CCGGAGTATT
 GGGAAGAGAA CACACGGAGA GTCAAGGACA CCGCACAGAC TTTCCGAGTG
 GGCCTGCGGA ACCTGCTCCG CTACTACAAC CAGAGCGAGG GGGGGTCTCA
 CACCGTCCAG ATAATGTTTG GCTGCGACCT GGGACCCGAC GGGAGCCTCC
 TCCGCGGGTA TGACCAGCAC GCCTACGACG GGAAGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCCGCG GACATGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CTGGTGAGGC AGAGCAGTGG AGAGCCTACC
 TGGAGGGCGA GTGCCTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACACTGC AGCGCGCCGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCTCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA GCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCGGGGA TACACGTGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATTGTGGGC ATCGTTGCTG GCCTGGCTGT
 CCTAGGAGTT GTGTTCACCG GAGCTGTGGT CGCTGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACGGCTTGA* 
>DL;IPD:MHC04190
IPD:MHC04190 Chsa-B*08:02 1089 bases
 ATGAGGATCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT TGGGGGTCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCTTGAGG TATTTCGCCA
 CCGCCGTGTC CCGGCCCGGC CGCCGGGAGC CCCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGAGGTTC GACAGTGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGATGAA GCAGGAGGGG CCGGAGTATT
 GGGAAGAGAA CACACGGAGA GTCAAGGACA CCGCACAGAC TTTCCGAGTG
 GGCCTGCGGA ACCTGCTCCG CTACTACAAC CAGAGCGAGG GGGGGTCTCA
 CACCGTCCAG ATAATGTTTG GCTGCGACCT GGGACCCGAC GGGAGCCTCC
 TCCGCGGGTA TGACCAGTAC GCCTACGACG GGAAGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCCGCG GACATGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CTGGTGAGGC AGAGCAGTGG AGAGCCTACC
 TGGAGGGCGA GTGCCTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACACTGC AGCGCGCCGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCTCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA GCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCGGGGA TACACGTGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATTGTGGGC ATCGTTGCTG GCCTGGCTGT
 CCTAGGAGTT GTGTTCACCG GAGCTGTGGT CGCTGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACGGCTTGA* 
>DL;IPD:MHC04203
IPD:MHC04203 Chsa-B*09:01 683 bases
 ATGGCGCCCC GAACCCTCCT CCTGCTGCTC TGGGGGGCCC TGGCCCTGAC
 CGAGACCTGG GCCGGCTCGC ACTCCTTGAG GTATTTCCAC ACCGCCGTGT
 CCCGGCCCGG CCGCTGGGAG CCCCACTTCA TCTCCGTGGG CTACGTGGAC
 GACACGCAGT TCGTGCGGTT CGACAGCGAC GCCGCGAGTC CGAGAGAGGA
 GCCGCGGGCG CCGTGGATGG AGCAGGAGGG GCCGGAGTAT TGGGAAGAGC
 AGACACGGAA CGCCGAGGCC CACGCACAGT CTCACCGAGT GAGCCTGCGG
 AACCTGCGCG GCTACTACAA CCAGAGCGAG TGGGGGTCTC ACACCCTCCA
 GAAGATGTAT GGCTGCGACC TGGGACCCGA CGGGCGCCTC CTCCGCGGGT
 ATGAACAGTT CGCCTACGAC GGCAGGGATT ACATCGCCCT GAACGAGGAC
 CTGCGCTCCT GGACGGCCAC GGACATGGCG GCTCAGAACA CCCAGCGGAA
 GTGGGAGGCG GCCCGTGCGG CGGAGAAGCT GAGAGCCTAC CTGGAGGGGA
 CGTGCCTGGA GTGGCTCCGC AGATACCTGG AGAACGGGAA GGAGACGCTG
 CAGCGCGCGG ATCCCCCAAA GACACACGTG ACCCACCACC CCATCTCTGA
 CCATGAGGCC ACCCTGAGGT GCTGGGCCCT GGG* 
>DL;IPD:MHC04787
IPD:MHC04787 Chsa-B*09:02 1080 bases
 ATGGCGGCCC GAACCCTCTT CCTGCTGCTC TCGGGGGCCC TGGCCCTGAC
 CGAGACCTGG GCCGGCTCGC ACTCCTTGAG GTATTTCCAC ACCGCCGTGT
 CCCGGCCCGG CCGCTGGGAG CCCCACTTCA TCTCCGTGGG CTACGTGGAC
 GACACGCAGT TCCTGCGGTT CGACAGCGAC GCCGCGAGTC CGAGAGAGGA
 GCCGCGGGCG CCGTGGATGG AGCAGGAGGG GCCGGAGTAT TGGGAAGAGC
 AGACACGGAA CGCCGAGGCC CACGCACAGT CTCACCGAGT AAGCCTGCGG
 AACCTGCGCG GCTACTACAA CCAGAGCGAG TGGGGGTCTC ACACCCTCCA
 GAAGATGTAT GGCTGCGACG TGGGACCCGA CGGGCGCCTC CTCCGCGGGT
 ATGAACAGTT CGCCTACGAC GGCAAGGATT ACATCGCCCT GAACGAGGAC
 CTGCGCTCCT GGACGGCAGC GGACATGGCG GCTCGGAACA CCCAGCGCAA
 GTGGGAGGCG GCCCGTGCGG CGGAGAAGCT GAGAGCCTAC CTGGAGGGGA
 CGTGCGTGGA GTGGCTCCGC AGATACCTGG AGAACGGGAA GGAGACACTG
 CAGCGCGCGG ATCCCCCAAA GACACACGTG ACCCACCACC CCATCTCTGA
 CCATGAGGCC ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA
 TCACACTGAC CTGGCAGCGG GATGGGGAGG ATCAAACTCA GGACACCGAA
 CTTGTGGAGA CCAGGCCAGC AGGAGATGGA ACCTACCAGA AGTGGGGAGC
 TGTGGTGGTG CCTTCTGGAG AAGAGCAGAG ATACACGTGC CATGTGCAGC
 ACAAGGGACT GTCGGAGCCC CTCACCCTGA GATGGGAGCC ATCTTCCCAG
 TCCACCATCC CCATCGTGGG CATTGTTGCT GGCCTGGCTG TCCTAGCAGT
 TGTGGTCACT GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AGGAAGAGCT
 CAGGTGGAAA AGGAGGGAGC TACTCTCAGG CTGCGTCCAG CGACAGTGCC
 CAGGGCTCTG ATGTGTCTCT CACAGCTTGA * 
>DL;IPD:MHC04202
IPD:MHC04202 Chsa-B*10:01 1105 bases
 GGTCATGGCG CCCCGAACCC TCCTCCTGCT GCTCTCGGGG GCCCTGGCCC
 TGACCGAGAC CTGGGCGGGC TCGCACTCCT TGAGGTATTT CCACACCGCC
 GTGTCCCGGC CCGGCTGCTG GGAGCCCCAC TTCATCTCCG TGGGCTACGT
 GGACGACACG CAGTTCGTGC GGTTCGACAG CGACGCCGCG AGTCCGAGAG
 AGGAGCCGCG GGCGCCGAGG ATGGAGCCGC GGGCGCCGTG GGCGGAGCAG
 GAGGGGCCGG AGTATTGGGA AGAGGAGACA CGGAACGCCG AGGCCCACGC
 ACAGTCTCAC CGAGTGAGCC TGCGGAACCT GCGCGGCTAC TACAACCAGA
 GCGAGTGGGG GTCTCACACC CTCCAGAAGA TGTACGGCTG CGACCTGGGA
 CCCGACGGGC GCCTCCTCCG CGGTTATGAA CAGTTCGCCT ACGACGGCAA
 GGATTACATC GCCCTGAACG AGGACCTGCG CTCCTGGACC GCCGCGGACA
 TGGCGGCTCG GAACACCCAG CGCAAGTGGG AGGCGGCCCG TGCGGCGGAG
 AAGCTGAGAG CCTACCTGGA GGGGACGTGC GTGGAGTGGC TCCGCAGATA
 CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CGCGGATCCC CCAAAGACAC
 ACGTGACCCA CCACCCCATC TCTGACCATG AGGCCACCCT GAGGTGCTGG
 GCCCTGGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC AGCGGGATGG
 GGAGGATCAA ACTCAGGACA CCGAACTTGT GGAGACCAGG CCAGCAGGAG
 ATGGAACCTT CCAGAAGTGG GGAGCTGTGG TGGTGCCTTC TGGAGAAGAG
 CAGAGATACA CGTGCCATGT GCAGCACAAG GGGCTGTCGG AGCCCCTCAC
 CCTGAGATGG GAGCCATCTT CCCAGTCCAC CATCCCCATC GTGGGCATTG
 TTGCTGGCCT GGCTGTCCTA GCAGTTGTGG TCACCGGAGC TATGGTCGCT
 GCTGTGATGT GGAGGAGGAA GAGCTCAGGT GGAAAAGGAG GGAGCTACTC
 TCCGGCTGCG TCCAGCGACA GTGTCCAGGG CTCTGATGTG TCTCTCACGG
 ATTGA*    
>DL;IPD:MHC04191
IPD:MHC04191 Chsa-B*11:01 683 bases
 ATGGCGCCCC GAACCCTCCT CCTGCTGCTC TCGGGGGCCC TGGCCCTGAC
 CGAGACCTGG GCGGGCTCGC ACTCCTTGAG GTATTTCCAC ACTGCCGTGT
 CCCGGCCCGG CCGCGGGGAG CCCCACTTCA TCTCCGTGGG CTACGTGGAC
 GACACGCAGT TCCTGCGGTT CGACAGCGAC GCCGCGAGTC CGAGAGAGGA
 GCCGCGGGCG CCGTGGGTGG AGCAGGAGGG GCCGGAGTAT TGGGAAGAGG
 AGACACGGAA CGCCGAGGAC CACGCACAGT CTCACCGAGT GAGCCTGCGG
 AACCTGCGCG GCTACTACAA CCAGAGCGAG TGGGGGTCTC ACACCCTCCA
 GAAGATGTAC GGCTGCGACC TGGGACCCGA CGGGCGCCTC CTCCGCGGGT
 ATGAACAGTA CGCCTACGAC GGCAAGGATT ACATCGCCCT GAACGAGGAC
 CTGCGCTCCT GGACGGCCGC GGACATGGCG GCTCGGAACA CCCAGCGCAA
 GTGGGAGGCG GCCCGTGCGG CGGAGAAGCT GAGAGCCTAC CTGGAGGGGA
 CGTGCGTGGA GTGGCTCCGC AGATACCTGG AGAACGGGAA GGAGACACTG
 CAGCGCGCGG ATCCCCCAAA GACACACGTG ACCCACCACC CCATCTCTGA
 CCATGAGGCC ACCCTGAGGT GCTGGGCCCT GGG* 
>DL;IPD:MHC04192
IPD:MHC04192 Chsa-B*11:02 683 bases
 ATGGCGCCCC GAACCCTCCT CCTGCTGCTC TCGGGGGCCC TGGCCCTGAC
 CGAGACCTGG GCGGGCTCGC ACTCCTTGAG GTATTTCCAC ACCGCCGTGT
 CCCGGCCCGG CCGCGGGGAG CCCCACTTCA TCTCCGTGGG CTACGTGGAC
 GACACGCAGT TCCTGCGGTT CGACAGCGAC GCCGCGAGTC CGAGAGAGGA
 GCCGCGGGCG CCGTGGGTGG AGCAGGAGGG GCCGGAGTAT TGGGAAGAGG
 AGACACGGAA CGCCGAGGAC CACGCACAGT CTCACCGAGT GAGCCTGCGG
 AACCTGCTCG GCTACTACAA CCAGAGCGAG TGGGGGTCTC ACACCCTCCA
 GAAGATGTAC GGCTGCGACC TGGGACCCGA CGGGCGCCTC CTCCGCGGGT
 ATGAACAGTA CGCCTACGAC GGCAAGGATT ACATCGCCCT GAACGAGGAC
 CTGCGCTCCT GGACGGCCGC GGACATGGCG GCTAGGAACA CCCAGCGCAA
 GTGGGAGGCG GCCCGTGCGG CGGAGAAGCT GAGAGCCTAC CTGGAGGGGA
 CGTGCGTGGA GTGGCTCCGC AGATACCTGG AGAACGGGAA GGAGACACTG
 CAGCGCGCGG ATCCCCCAAA GACACACGTG ACCCACCACC CCATCTCTGA
 CCATGAGGCC ACCCTGAGGT GCTGGGCCCT GGG* 
>DL;IPD:MHC04205
IPD:MHC04205 Chsa-B*12:01 659 bases
 CTGCTCTCAG GGACCCTGGC CCTGACCGAG ACCTGGGCCG GCTCGCACTC
 CTTGAGGTAT TTCCACACCG CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCTC CGTGGGCTAC GTGGACGACA CGCAGGTCGT GCGGTTCGAC
 AGCGACGCTG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCA
 GGAGGGGCCG GAGTTTTGGG AAGAGCAGAC ACGGAACGCC CAGGGCCACG
 CACAGAATCA CCGAGTGTGC CTGCGGACCG TGCCCGGCTA CTACAACCAG
 AGCGAGGCCG GGTCTCACAC CTTCCAGAGG ATGTACGGCT GTGACCTGGG
 GCCCGACGGG CGCCTCCTCC GCGGATATAA CCAGTACGCC TACGACGGCA
 AGGATTACAT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CTCCGCGGAC
 GTGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCGACCC GTTATGCGGA
 GCAGTTCAGA GCCTACCTGG AGGAGACGTG CGTGGAGTCG CTCCGCAGAC
 ACCTGGAGAA CGGGAAGGAG ATCCTGCAGC GCGCGGATCC CCCAAAGACA
 CACGTGACCC ACCACCCCGT CTCTGACCAT GAGGCCACCC TGAGGTGCTG
 GGCCCTGAG*    
>DL;IPD:MHC04198
IPD:MHC04198 Chsa-B*13:01 692 bases
 ATGCGGGTCA TGGCGCCCCG AACCCTGCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCAGCA
 CCGCCGTGTC CCGGCCCGGC CGCTGGGAGC CCCACTTCAT CTCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GACGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGAA CACACGGAAA GCCAAGGGCA ACGCACAGAC TAACCGAAGG
 AACCTGCGGA TCCTGCTCCG CTACTACAAC CAGAGCGAGT GGGGGTCTCA
 CACAGTCCAG AGGATGTACG GCTGCGACCT GGGGCCCGAC GGGCGCCTCC
 TCCGCGGGTA TGACCAGTTA GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCACCGCG GACATGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CCGGTACTGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGGAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GG*
>DL;IPD:MHC04786
IPD:MHC04786 Chsa-B*13:02 1089 bases
 ATGCGGGTCA TGGCGCCCCG AACCCTGCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCAGCA
 CCGCCGTGTC CCGGCCCGGC CGCTGGGAGC CCCACTTCAT CTCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GACGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGAA CACACGGAGA GTCAAGGGCC ACGCACAGAC TGACCGAAGG
 AACCTGCGGA CCCTGCTCCG CTACTACAAC CAGAGCGAGT GGGGGTCTCA
 CACAGTCCAG AGGATGTTTG GCTGCGACCT GGGGCCCGAC GGGCGCCTCC
 TCCGCGGGTA TCACCAGTCC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCACCGCG GACATGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CCGGTACTGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGGAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA GCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA CCTTCCAGAA
 GTGGGGAGCT GTGGTGGTAC CTTCTGGAGA AGAGCAGAGA TACACGTGCC
 ATGTGCAGCA CGAGGGATTG CCAGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATTGTGGGC ATTGTTGCCC CGGCTGTCCT
 GGCACTTGTG TTAATCGGAG CTGTTGTGGT CACTGCTGTG ATGTGGAGGT
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ATGGCTTGA* 
>DL;IPD:MHC04193
IPD:MHC04193 Chsa-B*14:01 692 bases
 ATGCGGGTCA TGGCGCCCCG AACCCTGCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCAGCA
 CCTCCGTGTC CCGGCCCGGC CGCTGGGAGC CCCACTTCAT CTCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGAGAGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGAA CACACGGATC GCCAAGGGCC ACGCACAGAC TGACCGAAGG
 AACCTGCGGA CCCTGCTCCG CTACTACAAC CAGAGCGAGT GGGGGTCTCA
 CACAGTCCAG AGGATGTACG GCTGCGACCT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TGACCAGTCC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCCGCG GACATGGCGG CTCAGAGCAC
 CCAGCGCAAG TGGGAGGCGG CCGGTACGGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGGAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GG*
>DL;IPD:MHC04196
IPD:MHC04196 Chsa-B*15:01 692 bases
 ATGCGGGTCA TGGCGCCCCG AACCCTGCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCAGCA
 CCGCTGTCTC CCGGCCCGGC CGCCGGGAAC CCTGGTATGT CGAAGTCGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGAA CACACGGAGA GCCAAGGCCC ACGCACAGAC TGACCGAGGG
 AACCTGCGGA CCCTGCTCCG CTACTACAAC CAGAGCGAGG GGGGGTCTCA
 CACCATCCAG AGGATGTTTG GCTGCGACCT GGGGCCCGAC GGGCACCTCC
 TCCGCGGGTA TGACCAGTTA GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCCGCG GACATGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGCGGC GGAGCGGTTG AGAGCCTACC
 TGGAGGGTGA GTGCCTGGAG TGGCTCCGCA GACACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCACAGA TCCCCCAAAG ACACACGTGA CCCATCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GG*
>DL;IPD:MHC04197
IPD:MHC04197 Chsa-B*15:02 692 bases
 ATGCGGGTCA TGGCGCCCCG AACCCTGCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCAGCA
 CCGCTGTCTC CCGGCCCGGC CGCCGGGAAC CCTGGTATGT CGAAGTCGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGAA CACACGGAGA GCCAAGGCCC ACGCACAGAC TGACCGAGGG
 AACCTGCGGA CCCTGCTCCG CTACTACAAC CAGAGCGAGG GGGGGTCTCA
 CACCATCCAG AGGATGTTTG GCTGCGACCT GGGGCCCGAC GGGCACCTCC
 TCCGCGGGTA TGAACAGCAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCCGCG GACATGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGCGGC GGAGCGGTTG AGAGCCTACC
 TGGAGGGTGA GTGCCTGGAG TGGCTCCGCA GACACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCACAGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GG*
>DL;IPD:MHC04788
IPD:MHC04788 Chsa-B*15:03 1087 bases
 GCGGGTCATG GCGCCCCGAA CCCTGCTCCT GCTGCTCTCG GGGGCCCTGG
 CCCTGACCGA GCCCTGGGCC GGCTCGCACT CCTTGAGGTA TTTCAGCACC
 GCTGTCTCCC GGCCCGGCCG CCGGGAACCC TGGTATGTCG AAGTCGGCTA
 CGTGGATGAC ACGCAGTTCG TGCGGTTCGA CAGCGACGCC GAGAGTCCGA
 GGATGGAGCC GCGGGCGCAG TGGGTGGAGC AGGAGGGGCC GGAGTATTGG
 GACCGGAACA CACGGAGAGC CAAGGCCCAC GCACAGACTG ACCGAGGGAA
 CCTGCGGACC CTGCTCCGCT ACTACAACCA GAGCGAGGGG GGGTCTCACA
 CCATCCAGAG GATGTTTGGC TGCGACCTGG GGCCCGACGG GCACCTCCTC
 CGCGGGTATG AACAGCACGC CTACGACGGC AAAGATTACA TCGCCCTGAA
 CGAGGACCTG CGCTCCTGGA CCGCCGCGGA CATGGCGGCT CAGAACACCC
 AGCGCAAGTG GGAGGCGGCC CGTGCGGCGG AGCGGTTGAG AGCCTACCTG
 GAGGGTGAGT GCCTGGAGTG GCTCCGCAGA CACCTGGAGA ACGGGAAGGA
 GACGCTGCAG CGCACAGATC CCCCAAAGAC ACACGTGACC CACCACCCCG
 TCTCTGACCA TGAGGCCACC CTGAGGTGCT GGGCCCTGGG CTTCTACCCT
 GCGGAGATCA CATTGACCTG GCAGCGGGAT GGGGAGGAGC AAACTCAGGA
 CACTGAGCTT GTGGAGACCA GGCCAGGAGG AGATGGAACC TTCCAGAAGT
 GGGGAGCTGT GGTGGTGCCT TCTGGAGAAG AGCAGAGATA CACATGCCAT
 GTGCAGCATG AGGGACTGCC GGAGCCCCTC ACCCTGAGAT GGGAGCCATC
 TTCCCAGTCC ACCATCCCCA TCGTGGGCAT TGTTGCTGGC CTGGCTGTCC
 TAGCAGTTGT GGTCACCGGA GCTGTGGTCG CTGCTGTGAT GTGGAGGAGG
 AAGAGCTCAG GTGGAAAAGG AGGGGGCTAC TCTCAGGCTG CGTCCAGCGA
 CAGTGCCCAG GGCTCTGATG TGTCTCTCAC GGCTTGA* 
>DL;IPD:MHC04791
IPD:MHC04791 Chsa-B*15:04 1089 bases
 ATGCGGGTCA TGGCGCCCCG AACCCTGCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCAGCA
 CCGCTGTCTC CCGGCCCGGC CGCCGGGAAC CCTGGTATGT CGAAGTCGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGAA CACACGGAGA GCCAAGGCCC ACGCACAGAC TGACCGAGGG
 AACCTGCGGA CCCTGCTCCG CTACTACAAC CAGAGCGAGG GGGGGTCTCA
 CACCATCCAG AGGATGTTTG GCTGCGACCT GGGGCCCGAC GGGCACCTCC
 TCCGCGGGTA TGAACAGCAC GCCTACGACG GCAAAGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCCGCG GACATGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGACGCGG CCCGTGCGGC GGAGCGGTTG AGAGCCTACC
 TGGAGGGTGA GTGCCTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCACAGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACATTGACC TGGCAGCGGG ATGGGGAGGA GCAAACTCAG
 GACACTGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA CCTTCCAGAA
 GTGGGGAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGACTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCTGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGGGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACGGCTTGA* 
>DL;IPD:MHC04785
IPD:MHC04785 Chsa-B*16:01 1089 bases
 ATGCGGGTCG TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCATGAGG TATTTCGGCA
 CCACCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CTACGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CCTGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGAAGAGGA GACACGGAAC GCCAAGGTCA CCGCACAGAC TGACCGAGTG
 GACCTGGGGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG GGGGGTCTCA
 CACCCTCCAG TGGATGTATG GCTGCGACCT GGGGCCCGAC GGGCGCCTCC
 TCCGCGGGTA CCGGCAGGAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCCGCG GACATGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGTGGC AGAGCAGCTG AGAGCCTACC
 TGGAGGGGAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCATCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACAGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA CCTTCCAGAA
 GTGGGGAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACGTGCC
 ATGTGCAGCA TGATGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTTCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCTGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCATCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC04789
IPD:MHC04789 Chsa-B*17:01 1089 bases
 ATGCGGGTCA TGGCGCCCCG AACCCTGCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCAGCA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CTCTGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCAACG CCGCGAGTCC
 GAGAGAGGAG CCGCGGGCGC CGTGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGAAGAGAA CACACGGAGA GTCAAGGCCC ACGCACAGAC TCACCGAGGG
 AACCTGCGGA CCCTGCTCCG CTACTACAAC CAGAGCGAGG GGGGGTCTCA
 CACCCTCCAG AGGATGTACG GCTGCGACCT GGGGCCCGAC GGGCGCCTCC
 TCCGCGGGTA TGAACAGTTC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCGGCG GACATGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGCGGC GGAGCAGTTG AGAGCCTACC
 TGGAGGGCGA GTGCCCGGAG TGGCTCCGCA GATACCTGGA GAACGGGGAG
 GAGACGCTGC AGCGCGCGGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA CCTTCCAGAA
 GTGGGGAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACGTGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACTG GAGCTGTGGT CGCTGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACGGCTTGA* 
>DL;IPD:MHC04790
IPD:MHC04790 Chsa-B*18:01 975 bases
 ATGGCGCCCC AAACCCTCCT CCTGCTGCTC TCGGGGGCCC TGGCCCTGAC
 CGAGACCTGG GCCGGCTCGC ACTCCATGAG GTATTTCAGC ACCTCCGTGT
 CCCGGCCCGG CCGCGGGGAG CCCCGCTTCA TCGCCGTGGG CTACGTGGAC
 GACACGCAGT TCGTGCGGTT CGACAGCGAC GCCGCGAGTC CGAGGATGGA
 GCCGCGGGCG CCGTGGATGG AGCAGGAGGG GCCGGAGTAT TGGGAAGAGC
 AGACACGGAG AGCCAAGAAC ATCGCACAGA CTGACCGAGT GAGCCTGCGG
 AACCTGCGCG GCTACTACAA CCAGAGCGAG TGGGGGTCTC ACACCTTCCA
 GTGGATGTCT GGCTGTGACC TGGGGCCCGA CGGGCGCCTC CTCCGCGGGT
 ATTACCAGTT CGCCTACGAC GGCAAGGATT ACATCGCCCT GAACGAGGAC
 CTGCGCTCCT GGACCGCCGC GGACGTGGCG GCTCAGAACA CCCAGCGCAA
 GTGGGAGGCG ACCCGCGAGG CAGAGCAGAT AAGAGCCTAC CTGGAGGGCG
 AGTGCGTGGA GTGGCTCCGC AGATACCTGG AGAACGGGAA GGAGACGCTG
 CAGCACGCGG ATCCCCCAAA GACACACGTG ACCCACCACC CCGTCTCTGA
 CCATGAGGCC ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA
 TCACACTGAC CTGGCAGCGG GATGGGGAGG ACCAAACTCA GGACACTGAG
 CTTGTGGAGA CCAGGCCCGC AGGGAATGGA ACCTTCCAGA AATGGGCAGC
 TGTGGTGGTG CCTTCTGGAG AAGAGCAGAG ATACACGTGC CATGTGCAGC
 ACGAGGGATT GACGGAGCCC CTCACCCTGA GATGGGAGCC ATCTTCCCAG
 TCCACCATCC CCATCGTGGG CATTGTTGCT GGCCTGGCTG TCCTAGCAGT
 TGTGGTCTTT GGAGCTGTGA TCGCA*  
