>DL;IPD:MHC04186
IPD:MHC04186 Chsa-A*01:01 366 bases
 MAVMAPRTLL LVLSGVLALT QTRAGSHSMR YFYTYMSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWVEQEG PEYWDRSTRI MKTETQMAPV
 GLRNLRGYYN QSEAGSHTYQ RMYGCDLGPD GRLLRGYHQL AYDGKDYIAL
 NEDLRSWTAA DLAAQNTQRK WEASGWVEQF RTYLEGECLE WLRRYLENGK
 ETLQRAEPPK THVTHHPVSD HETTLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPS GNGTFQKWAA VVVPSGKEQR YTCHVQHEGL REPLTLRWEP
 SSQSTIPIVG IIAGLVLLGA VVTGAVVAAV MWRRKSSDRK GGSYAQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC04183
IPD:MHC04183 Chsa-A*02:01 366 bases
 MAVMAPRTLL LVLSGALVLT ETWAGSHSLR YFYTSMSRPG RGEPRFISVG
 YVDNTQFVRF DSDAESPREE PRAPWMEQEG PEYWDRNTRI FKAETQTFRV
 GLQNLRGYYN QSEAGSHTIQ EMYGCDLGPD GRLLRGYDQY AYDGRDYIAL
 NEDLHSWTAA DMAAQNTQRK WEAAGVAEQM RTYLEDECLE WLRRYLENGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGKEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IIAGLVLLGA VVTGAVVAAV MWRRKSSDRK GGSYSQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC04184
IPD:MHC04184 Chsa-A*03:01 231 bases
 MAVMAPRTLL LVLSGVLALT QTRAGSHSMR YFYTSVSRPG RGQPRFFAVG
 YVDDTQFVRF DSNAASQRME PRAPWVEQEG PEYWDRETRI MKGETQRAPM
 DLRILRGYYN QSEAGSHTYQ RMYGCDLGPD GRLLRGYEQL AYDGKDYIAL
 NEDLRSWTAA DLAAQNTQRK WEAEGWAEQV RAYLEGRCVE WLRRYLENGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL G* 
>DL;IPD:MHC04185
IPD:MHC04185 Chsa-A*03:02 366 bases
 MAVMAPRTLL LVLSGVLALT QTRAGSHSMR YFHTSVSRPG RGEPRFFAVG
 YVDDTQFVRF DSNAASQRME PRAPWVEQEG PEYWDRETRI MKGETQRAPM
 DLRILRGYYN QSEAGSHTYQ RMYGCDLGPD GRLLRGYEQL AYDGRDYIAL
 NEDLRSWTAA DLAAQNTQRK WEAEGWAEQV RAYLEGRCVE WLRRYLENGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQLDGEDQTQ
 DTELVETRPE GDGTFQKWAA VVVPSGKEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVD IIVGLVLLGA VVTGTVVTAV MWRRKSSGRK GGSYSQAASG
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC04782
IPD:MHC04782 Chsa-A*03:03 340 bases
 MAVMAPRTLL LVLSGVLALT QTRAGSHSMR YFHTAVSRPG RGEPRFFAVG
 YVDDTQFVRF DSNAASQRME PRAPWVEQEG PEYWDRETRI MKGETQRAPM
 DLRILRGYYN QSEAGSHTYQ RMYGCDLGPD GRLLRGYEQL AYDGRDYIAL
 NEDLRSWTAA DLAAQNTQRK WEAEGWAEQV RAYLEGRCVE WLRRYLENGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQLDGEDQTQ
 DTELVETRPE GDGTFQKWAA VVVPSGKEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVD IIVGLVLLGA VVTGTVVTAV MWRRKSSGRK *
>DL;IPD:MHC04783
IPD:MHC04783 Chsa-A*03:04 366 bases
 MAVMAPRTLL LVLSGVLALT QTRAGSHSMR YFYTSVSRPG RGEPRFFAVG
 YVDDTQFVRF DSNAASQRME PRAPWVEQEG PEYWDQETRI MKGETQTAPM
 DLRILRGYYN QSEAGSHTYQ RMYGCDLGPD GRLLRGYEQF AYDGKDYIAL
 NEDLRSWTAA DLAAQNTQRK WEAEGWAEQV RAYLEGRCVE WLRRYLENGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQLDGEDQTQ
 DTELVETRPE GDGTFQKWAA VVVPSGKEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IIVGLVLLGA VVTGTVVTAV MWRRKSSGRK GGSYSQAASG
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC04182
IPD:MHC04182 Chsa-A*04:01 361 bases
 MAVMAPRTLL LLLSGALALT QTRGGSHSMR YFYTYMSRPG RGEPRFIAVG
 YVDDTQFVWF DSDAASQRME PRAPWVEQEG PEYWDRSTRI MKTATQMAPV
 ALRILRGYYN QSEGGSHTYQ RMYGCDLGPD GRLLRGYNQY AYDGKDYIAL
 NEDLRSWTAA DLAAQNTQRK WEAAGVAEQK RAYLEGTCVE WLRRYLENGK
 ETLERADPPK THVTHHPVSD HETTLRCWAL GFYPAEITLT WQRDGEEQTQ
 DMELVETRPS GNGTFQKWAA VVVPSGKEQR YTCHVQHEGL PKPLALRWEP
 SSQSTIPIVG IIAGLVLLGA VVTAVMWRRK SSDRKGGSYS QAASSDSAQG
 SDVSLTACKV X*   
>DL;IPD:MHC04187
IPD:MHC04187 Chsa-A*05:01 363 bases
 MAPRTLILVF SGALALTQTR AGSHSMRYFY TSMSRPGRGQ PRFIAVGYVD
 DTQFVRFDSD AASPRMEPRA PWVEQEGPEY WDRNTGIMKT ATQTYRENLR
 TALRYYNQSE AGSHTLQTMH GCDLGPDGRL LRGYDQFAYD GKDYIALNED
 LRSWTAADVA AQNTQRKWEA AGEAERLRTY LEGECLEWLR RHLENGKETL
 QRADPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEDQTQDTE
 LVETRPAGDG TFQKWAAVVV PSGKEQRYTC HVQHEGLPEP LTLRWEPSSQ
 STIPIVGIIA SLVLLGAAVT GAVVAAVRWR RKSSDRKGGS YSQAASSDSA
 QGSDVSLTAC KVX*   
>DL;IPD:MHC04188
IPD:MHC04188 Chsa-A*06:01 366 bases
 MAVMAPRTLL LVLSGVLALT QTWAGSHSMR YFYTSMSRPG SWEPRFIAVG
 YVDDTQFLRF DSDAASPRME PRAPWVEQEG PEYWDRETRI MKTATQTFRV
 GLQNLRGYYN QSEAGSHTVQ KMYGCDLGPD GRLLRGYEQY AYDGRDYIAL
 NEDLRSWTAA DMAAQNTQRK WEVARVAEQR RGYLEGTCLE WLRRYLENGK
 ETLQRAEPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGKEQR YTCHVQHEGL REPLTLRWEP
 SSQSTIPIVG IIAGLVLLGA VVTGAVAAAV MWRRKSSDRK GGNYSQAESS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC04781
IPD:MHC04781 Chsa-A*07:01 366 bases
 MAVMAPRTLL LVLSGALALT QTWAGSHSMR YFYTYMSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWVEQEG PEYWDRSTRI MKTETQRAPV
 NLRNLRGYYN QSEAGSHTVQ RMYGCDLGPD GRLLRGYEQF AYDGKDYIAL
 NEDLRSWTAA DLAAQNTQRK WEAAGVAEQH RTYLEAQCLE WLRRHLENGK
 ETLQRAEPPK THVTHHPVSD HETTLRCWAL DFYPEEITLT WQRDGEDQTQ
 DTELVETRPS GNGTFQKWAA VVVPSGKEKR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG VIAGLVLLGA VVTGAVVAAV MWRRKSSDRK AGSYSQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC04784
IPD:MHC04784 Chsa-A*08:01 247 bases
 MAVMAPRTLL LVLSGALALT QTWAGSHSMR YFYTSMSRPG RGQPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWVEQEG PEYWDRETRI MKTATQNYRE
 NLRTALRYYN QSEAGSHTVQ KMYGCDLDPD GRLLRGYEQF AYDGRDYIAL
 NEDLRSWTAA DLAAQNTQRK WEAAGVAEQQ RAYLEGLCVE WLRRYLENGK
 ETLQRAEPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGED*
