>DL;IPD:MHC04201
IPD:MHC04201 Chsa-B*01:01 231 bases
 MQVMAPRTLL LLLSGTLALT ETWAGSHSMR YFSTAVSRPG RREPWYLAVG
 YVDDTQFVWF DSDAESPRME PRAPWIEQEE PEYWEEQTRR AKGNAQADRG
 NLRTLLRYYN QSEGGSHTFQ WMYGCDLGPD GRLLRGYHQS AYDGKDYIAL
 NEDLRSWTAA DMAAGFTQRK WEAARAAERF RAYLEGECLE WLRRHLENGK
 ETLQRAEPPK THVTHHPISD HEATLRCWAL G* 
>DL;IPD:MHC04194
IPD:MHC04194 Chsa-B*02:01 231 bases
 MRVMAPRTLL LLLSGALALT ETWAGSHSLR YFHTAVSRPG RWEPHFISVG
 YVDDTQFVRF DSDAESPREE PRAPWVEQEG PEYWDRNTRR AKAHAQTDRR
 NLRTLLRYYN QSEWGSHTLQ RMCGCDLGPD GRLLRGYHQS AYDGKDYIAL
 NEDLRSWTTA DMAAQSTQRK WEAAGVAEQI RAYLEGTCVE WLRRHLENGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL G* 
>DL;IPD:MHC04199
IPD:MHC04199 Chsa-B*03:01 325 bases
 MRVMAPRTLL LLLSGALALT QTWAGSHSLR YFSTAVSRPG RREPWYLEVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEATRR AKGNAQTHRG
 NLRTALRYYN QSEGGSHTLQ WMYGCDLGPD GRLLRGYEQF AYDGKDYIAL
 NEDLRSWTAA DMAARFTQRK WEAARAAEQL RAYLEGKCLE WLRRYLENQK
 ESLLRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL LEPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVTGA*  
>DL;IPD:MHC04195
IPD:MHC04195 Chsa-B*04:01 363 bases
 MRVMAPRILL LLLSGALALT ETWAGSHSLR YFDTAVSRPG RGDLWYLEVG
 YVDDTQFVRF DSDAESPRMK PRAPWVEQEG PEYWEEQTRN AKVSAQTDRG
 NLRTALRYYN QSEAGSHTIQ RMYGCDLGPD GRFLRGYHQS AYDGKDYIAL
 NEDLRSWTAA DMAAQNTQRK WEAAGEAERV RAYLEGRCVE WLRRYLENGK
 ETLQRTDPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRNGEDQTQ
 DTELVETRPG GDGTFQKWGA VMVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC04204
IPD:MHC04204 Chsa-B*05:01 220 bases
 LVSGTLILTQ TWAGLHSLRY FSTAVSRPGR GEPRFISVGY VDNTQILRFN
 SDAESPRMEP RAPWLEQEGP EYWEEQTGLA KANAQTFRGC LRTVPGYYNQ
 SEAGSHTFQW MYGCDLGPDG RLLRGYHRFA YDGQDYIALN RDLRSWIAAD
 TAAQNTQRKW EAAREAEQIR AHLEGTCVEW LRRYLENGEE TLQRADPPKT
 HVTHHPVSDH EATLKCWALG *  
>DL;IPD:MHC04206
IPD:MHC04206 Chsa-B*06:01 231 bases
 MQVMAPRTLL LLLSGALALT ETWAGSHSMR YFSTAVSRPG RGEPWYLEVG
 YVDDTQFVRF DSDAESPRME PRAPWMKQEG PEYWDRETRR AKANAQCFQG
 NLRTLRGYYN QSEAGSHTLQ TMSRCDLGPD GRLLRGYYQQ AYDGKDYIAL
 NEDLRSWTAA DEAAQNTQRK WEAAGEAEQL RAYLEGTCVE WLRRHLENGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL G* 
>DL;IPD:MHC04200
IPD:MHC04200 Chsa-B*07:01 231 bases
 MRVMAPRTLL LLLSGALALT ETWAGSHSLG YFYTAESRPR RGEPRFIAVG
 YVDDTQFVRF DSNAASPRME PRAPWMKQEG PEYWEEQTQR VQGHAQTFRV
 SLRNLLRYYN QSKAGSHTLQ RMSGCDLGPD GRLLRGYDQY AYDGKDYIAL
 NEDLRSWTAA DTAAQKTQRK WEAARAAEKL RAYLEGECVE WLRRYLENQK
 EMRQRADPPK TNVTHHPISD HEATLRCWAL G* 
>DL;IPD:MHC04189
IPD:MHC04189 Chsa-B*08:01 363 bases
 MRIMAPRTLL LLLLGVLALT ETWAGSHSLR YFATAVSRPG RREPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMKQEG PEYWEENTRR VKDTAQTFRV
 GLRNLLRYYN QSEGGSHTVQ IMFGCDLGPD GSLLRGYDQH AYDGKDYIAL
 NEDLRSWTAA DMAAQNTQRK WEAAGEAEQW RAYLEGECLE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGTFQKWAA VVVPSGEERG YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLGV VFTGAVVAAV MWRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC04190
IPD:MHC04190 Chsa-B*08:02 363 bases
 MRIMAPRTLL LLLLGVLALT ETWAGSHSLR YFATAVSRPG RREPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMKQEG PEYWEENTRR VKDTAQTFRV
 GLRNLLRYYN QSEGGSHTVQ IMFGCDLGPD GSLLRGYDQY AYDGKDYIAL
 NEDLRSWTAA DMAAQNTQRK WEAAGEAEQW RAYLEGECLE WLRRYLENGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGTFQKWAA VVVPSGEERG YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLGV VFTGAVVAAV MWRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC04203
IPD:MHC04203 Chsa-B*09:01 228 bases
 MAPRTLLLLL WGALALTETW AGSHSLRYFH TAVSRPGRWE PHFISVGYVD
 DTQFVRFDSD AASPREEPRA PWMEQEGPEY WEEQTRNAEA HAQSHRVSLR
 NLRGYYNQSE WGSHTLQKMY GCDLGPDGRL LRGYEQFAYD GRDYIALNED
 LRSWTATDMA AQNTQRKWEA ARAAEKLRAY LEGTCLEWLR RYLENGKETL
 QRADPPKTHV THHPISDHEA TLRCWALG*  
>DL;IPD:MHC04787
IPD:MHC04787 Chsa-B*09:02 360 bases
 MAARTLFLLL SGALALTETW AGSHSLRYFH TAVSRPGRWE PHFISVGYVD
 DTQFLRFDSD AASPREEPRA PWMEQEGPEY WEEQTRNAEA HAQSHRVSLR
 NLRGYYNQSE WGSHTLQKMY GCDVGPDGRL LRGYEQFAYD GKDYIALNED
 LRSWTAADMA ARNTQRKWEA ARAAEKLRAY LEGTCVEWLR RYLENGKETL
 QRADPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQR DGEDQTQDTE
 LVETRPAGDG TYQKWGAVVV PSGEEQRYTC HVQHKGLSEP LTLRWEPSSQ
 STIPIVGIVA GLAVLAVVVT GAVVAAVMWR RKSSGGKGGS YSQAASSDSA
 QGSDVSLTAX *   
>DL;IPD:MHC04202
IPD:MHC04202 Chsa-B*10:01 368 bases
 VMAPRTLLLL LSGALALTET WAGSHSLRYF HTAVSRPGCW EPHFISVGYV
 DDTQFVRFDS DAASPREEPR APRMEPRAPW AEQEGPEYWE EETRNAEAHA
 QSHRVSLRNL RGYYNQSEWG SHTLQKMYGC DLGPDGRLLR GYEQFAYDGK
 DYIALNEDLR SWTAADMAAR NTQRKWEAAR AAEKLRAYLE GTCVEWLRRY
 LENGKETLQR ADPPKTHVTH HPISDHEATL RCWALGFYPA EITLTWQRDG
 EDQTQDTELV ETRPAGDGTF QKWGAVVVPS GEEQRYTCHV QHKGLSEPLT
 LRWEPSSQST IPIVGIVAGL AVLAVVVTGA MVAAVMWRRK SSGGKGGSYS
 PAASSDSVQG SDVSLTDX*   
>DL;IPD:MHC04191
IPD:MHC04191 Chsa-B*11:01 228 bases
 MAPRTLLLLL SGALALTETW AGSHSLRYFH TAVSRPGRGE PHFISVGYVD
 DTQFLRFDSD AASPREEPRA PWVEQEGPEY WEEETRNAED HAQSHRVSLR
 NLRGYYNQSE WGSHTLQKMY GCDLGPDGRL LRGYEQYAYD GKDYIALNED
 LRSWTAADMA ARNTQRKWEA ARAAEKLRAY LEGTCVEWLR RYLENGKETL
 QRADPPKTHV THHPISDHEA TLRCWALG*  
>DL;IPD:MHC04192
IPD:MHC04192 Chsa-B*11:02 228 bases
 MAPRTLLLLL SGALALTETW AGSHSLRYFH TAVSRPGRGE PHFISVGYVD
 DTQFLRFDSD AASPREEPRA PWVEQEGPEY WEEETRNAED HAQSHRVSLR
 NLLGYYNQSE WGSHTLQKMY GCDLGPDGRL LRGYEQYAYD GKDYIALNED
 LRSWTAADMA ARNTQRKWEA ARAAEKLRAY LEGTCVEWLR RYLENGKETL
 QRADPPKTHV THHPISDHEA TLRCWALG*  
>DL;IPD:MHC04205
IPD:MHC04205 Chsa-B*12:01 219 bases
 LLSGTLALTE TWAGSHSLRY FHTAVSRPGR GEPRFISVGY VDDTQVVRFD
 SDAESPRMEP RAPWVEQEGP EFWEEQTRNA QGHAQNHRVC LRTVPGYYNQ
 SEAGSHTFQR MYGCDLGPDG RLLRGYNQYA YDGKDYIALN EDLRSWTSAD
 VAAQNTQRKW EATRYAEQFR AYLEETCVES LRRHLENGKE ILQRADPPKT
 HVTHHPVSDH EATLRCWAL*   
>DL;IPD:MHC04198
IPD:MHC04198 Chsa-B*13:01 231 bases
 MRVMAPRTLL LLLSGALALT ETWAGSHSLR YFSTAVSRPG RWEPHFISVG
 YVDDTQFVRF DSDAESPTME PRAPWVEQEG PEYWDRNTRK AKGNAQTNRR
 NLRILLRYYN QSEWGSHTVQ RMYGCDLGPD GRLLRGYDQL AYDGKDYIAL
 NEDLRSWTTA DMAAQNTQRK WEAAGTAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL G* 
>DL;IPD:MHC04786
IPD:MHC04786 Chsa-B*13:02 363 bases
 MRVMAPRTLL LLLSGALALT ETWAGSHSLR YFSTAVSRPG RWEPHFISVG
 YVDDTQFVRF DSDAESPTME PRAPWVEQEG PEYWDRNTRR VKGHAQTDRR
 NLRTLLRYYN QSEWGSHTVQ RMFGCDLGPD GRLLRGYHQS AYDGKDYIAL
 NEDLRSWTTA DMAAQNTQRK WEAAGTAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGTFQKWGA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAPAVLALV LIGAVVVTAV MWRWKSSGGK GGSYSQAASS
 DSAQGSDVSL MAX*   
>DL;IPD:MHC04193
IPD:MHC04193 Chsa-B*14:01 231 bases
 MRVMAPRTLL LLLSGALALT ETWAGSHSLR YFSTSVSRPG RWEPHFISVG
 YVDDTQFVRF DSDAESPREE PRAPWVEQEG PEYWDRNTRI AKGHAQTDRR
 NLRTLLRYYN QSEWGSHTVQ RMYGCDLGPD GRLLRGYDQS AYDGKDYIAL
 NEDLRSWTAA DMAAQSTQRK WEAAGTAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL G* 
>DL;IPD:MHC04196
IPD:MHC04196 Chsa-B*15:01 231 bases
 MRVMAPRTLL LLLSGALALT ETWAGSHSLR YFSTAVSRPG RREPWYVEVG
 YVDDTQFVRF DSDAESPRME PRAPWVEQEG PEYWDRNTRR AKAHAQTDRG
 NLRTLLRYYN QSEGGSHTIQ RMFGCDLGPD GHLLRGYDQL AYDGKDYIAL
 NEDLRSWTAA DMAAQNTQRK WEAARAAERL RAYLEGECLE WLRRHLENGK
 ETLQRTDPPK THVTHHPVSD HEATLRCWAL G* 
>DL;IPD:MHC04197
IPD:MHC04197 Chsa-B*15:02 231 bases
 MRVMAPRTLL LLLSGALALT ETWAGSHSLR YFSTAVSRPG RREPWYVEVG
 YVDDTQFVRF DSDAESPRME PRAPWVEQEG PEYWDRNTRR AKAHAQTDRG
 NLRTLLRYYN QSEGGSHTIQ RMFGCDLGPD GHLLRGYEQH AYDGKDYIAL
 NEDLRSWTAA DMAAQNTQRK WEAARAAERL RAYLEGECLE WLRRHLENGK
 ETLQRTDPPK THVTHHPVSD HEATLRCWAL G* 
>DL;IPD:MHC04788
IPD:MHC04788 Chsa-B*15:03 362 bases
 RVMAPRTLLL LLSGALALTE PWAGSHSLRY FSTAVSRPGR REPWYVEVGY
 VDDTQFVRFD SDAESPRMEP RAQWVEQEGP EYWDRNTRRA KAHAQTDRGN
 LRTLLRYYNQ SEGGSHTIQR MFGCDLGPDG HLLRGYEQHA YDGKDYIALN
 EDLRSWTAAD MAAQNTQRKW EAARAAERLR AYLEGECLEW LRRHLENGKE
 TLQRTDPPKT HVTHHPVSDH EATLRCWALG FYPAEITLTW QRDGEEQTQD
 TELVETRPGG DGTFQKWGAV VVPSGEEQRY TCHVQHEGLP EPLTLRWEPS
 SQSTIPIVGI VAGLAVLAVV VTGAVVAAVM WRRKSSGGKG GGYSQAASSD
 SAQGSDVSLT AX*   
>DL;IPD:MHC04791
IPD:MHC04791 Chsa-B*15:04 363 bases
 MRVMAPRTLL LLLSGALALT ETWAGSHSLR YFSTAVSRPG RREPWYVEVG
 YVDDTQFVRF DSDAESPRME PRAPWVEQEG PEYWDRNTRR AKAHAQTDRG
 NLRTLLRYYN QSEGGSHTIQ RMFGCDLGPD GHLLRGYEQH AYDGKDYIAL
 NEDLRSWTAA DMAAQNTQRK WDAARAAERL RAYLEGECLE WLRRYLENGK
 ETLQRTDPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGTFQKWGA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGGYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC04785
IPD:MHC04785 Chsa-B*16:01 363 bases
 MRVVAPRTLL LLLSAALALT ETWAGSHSMR YFGTTVSRPG RGEPRFIYVG
 YVDDTQFVRF DSDAESPRME PRAPWIEQEG PEYWEEETRN AKVTAQTDRV
 DLGTLRGYYN QSEGGSHTLQ WMYGCDLGPD GRLLRGYRQD AYDGKDYIAL
 NEDLRSWTAA DMAAQNTQRK WEAAGVAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPG GDGTFQKWGA VVVPSGEEQR YTCHVQHDGL PEPLTLRWEP
 SSQSTIPIVG IVSGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC04789
IPD:MHC04789 Chsa-B*17:01 363 bases
 MRVMAPRTLL LLLSGALALT ETWAGSHSLR YFSTAVSRPG RGEPRFISVG
 YVDDTQFVRF DSNAASPREE PRAPWIEQEG PEYWEENTRR VKAHAQTHRG
 NLRTLLRYYN QSEGGSHTLQ RMYGCDLGPD GRLLRGYEQF AYDGKDYIAL
 NEDLRSWTAA DMAAQNTQRK WEAARAAEQL RAYLEGECPE WLRRYLENGE
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPG GDGTFQKWGA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC04790
IPD:MHC04790 Chsa-B*18:01 325 bases
 MAPQTLLLLL SGALALTETW AGSHSMRYFS TSVSRPGRGE PRFIAVGYVD
 DTQFVRFDSD AASPRMEPRA PWMEQEGPEY WEEQTRRAKN IAQTDRVSLR
 NLRGYYNQSE WGSHTFQWMS GCDLGPDGRL LRGYYQFAYD GKDYIALNED
 LRSWTAADVA AQNTQRKWEA TREAEQIRAY LEGECVEWLR RYLENGKETL
 QHADPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEDQTQDTE
 LVETRPAGNG TFQKWAAVVV PSGEEQRYTC HVQHEGLTEP LTLRWEPSSQ
 STIPIVGIVA GLAVLAVVVF GAVIA*  
