>DL;IPD:MHC00201
IPD:MHC00201 Gogo-DPA1*04:01 189 bases
 TTTGTACAGA CGCATAGAAC AACAGGAGAG TTTATGTTTG AGTTTGATGA
 GGATGAGATG TTCTATGTGG ATCTGGACAA GAAGGAGACC GTCTGGCATC
 TGGAGGAGTT TGGCCGAGCC TTTTCCTTTG AGGCTCAGGG CGGGCTGGCT
 AACATTGCTA TATTGAACAA CAACTTGAAT ATCACTATC* 
>DL;IPD:MHC00202
IPD:MHC00202 Gogo-DPA1*04:02 189 bases
 TTTGTACAGA CGCATAGAAC AACAGGAGAG TTTATGTTTG AGTTTGATGA
 GGATGAGATG TTCTATGTGG ATCTGGACAA GAAGGAGACC GTCTGGCATC
 TGGAGGAGTT TGGCCGAGCC TTTTCCTTTG AGGCTCAGGG CGGGCTGGCT
 AACATTGCTA TATTGAACAA CAACTTGAAT ATCGCTATC* 
