>DL;IPD:MHC00179
IPD:MHC00179 Gogo-A*01:01 366 bases
 MAVMAPRTLV LLLSGALALT QTWAGSHSMR YFSTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWIEQEG PEYWDRNTRN VKAHSQTDRV
 DLGTLRGYYN QSEDGSHTIQ RMYGCDVGSD GRFLRGYQQD AYDGKDYIAL
 NEDLRSWTAA DMAAEITKRK WEAAHFAEQL RAYLEGTCVE WLRRHLENGK
 ETLQRTDAPK THMTHHAVSD HEAILRCWAL SFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGQEQR YTCHVQHEGL PEPLTLRWEP
 SSQPTIPIVG IIAGLVLFGA VIAGAVVAAV RWRRKSSDRK GGSYSQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC00180
IPD:MHC00180 Gogo-A*02:01 366 bases
 MAVMAPRTLL LLLLGALALT QTWAGSHSMR YFSTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWIEQEE PEYWDGETRK VKAHSQTDRV
 NLGTLRGYYN QSEDGSHTIQ KMYGCDVGSD GRFLRGYQQD AYDGKDYIAL
 NEDLRSWTAA DMAAEITKRK WEAAHFAEQL RAYLEGECVE WLRRYLENGK
 ETLQRTDAPK THMTHHAVSD HEAILRCWAL SFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGQEQR YTCHVQHESL PKPLTLRWEP
 SSQPTIPIVG IIAGLVLFGA VIAGAVIAAV RWRRKSSDRK GGSYSQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC00181
IPD:MHC00181 Gogo-A*04:01 366 bases
 MAVMAPRTLV LLLSGALALT QTWAGSHSMR YFYTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWIEQEE PEYWDGETRN MKARSQTDRV
 DLGTLRGYYN QSEDGSHTIQ RMYGCDVGSD GRFLRGYQQD AYDGKDYIAL
 NEDLRSWTAA DMAAQITQRK WEAAHEAEQL RAYLEGTCVE WLRRYLENGK
 ETLQLTDAPK THMTHHPVSD HEAILRCWAL SFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGQEQR YTCHVQHEGL PKPLTLRWEP
 SSQPTIPIVG IIAGLVLFGA VIAGAVVAAV RWRRKSSDRK GGSYSQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC00182
IPD:MHC00182 Gogo-A*05:01 366 bases
 MAVRAPRTLL LLLSGALALT QTWAGSHSMR YFSTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWMEQEE PEYWDRQTQI SKTNAQIELE
 SLRIALRYYN QSEDGSHTIQ RMYGCDVGSD GRFLRGYQQD AYDGKDYIAS
 NEDLRSWTAA DMAAEITKRK WEAAHFAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRTDAPK THTTHQAVSD HEATLKCWAL SFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGQEQR YTCHVQHEGL PKPLTLRWEP
 SSQPTIPIVG IIAGLVLFGA VIAGAVVAAV RWRRKSSDRK GGSYSQAASS
 DSAQGSDVSL TACKVX*   
