>DL;IPD:MHC00239
IPD:MHC00239 Gogo-H*01 1090 bases
 TCATGGAGCC CCGAACCCTC CTCCTGCTGC TCTCAGGGGC CCTGGCCCTG
 ACCCAGACCT GGGCGCGCTC CCACTCCATG AGGTATTTCT ATACCACCAT
 GTCCCGGCCC GGCCGCGGGG AGCCCCGCTT CATCTCCGTC GGCTACGTGG
 ACGATACGCA GTTCGTGCGG TTCGACAGCG ACGACGCGAG TCCGAGAGAG
 GAGCCGCGAG CGCCGTGGAT GGAGCGGGAG GGGCCGGAGT ATTGGGACCG
 GAACACACAG ATCTGCAAGG CCCAAGCACA GACTGAACGA GAGAACCTGC
 GGATCGCGCT CCGATACTAC AACCAGAGCG AGGGCGGTTC TCACACCATG
 CAGGTGATGT ATGGCTGCGA CGTGGGGCCC GACGGGCGCT TCCTCCGCGG
 GTATGAACAG CACGCCTACG ACGGCAAGGA TTACATCGCT CTGAACGAGG
 ACCTGCGCTC CTGGACCGCG GCGGACATGG CAGCTCAGAT CACCAAGCGC
 AAGTGGGAGG CGGCCCGTCG GGCGGAGCAG TTGAGAGCCT ACCTGGAGGG
 CGAGTTCGTC GAGTGGCTCC GCAGATACCT GGAGAACGGG AAGGAGACGC
 TGCAGCGCGC GGACCCCCCC AAGACACATA TGACTCACCA CCCTGTCTCT
 GACCATGAGG CCACCCTGAG GTGCTGGGCC CTGGGCTTCT ACCCCGCGGA
 GATCACACTG ACCTGGCAGC GGGATGGAGA GGACCAGACC CAGGACACGG
 AGCTCGTGGA GACCAGGCCT GGAGGGGATG GGACCTTCCA GAAGTGGGCG
 GCTGTGGTGG TGCCTTCTGG AGAGGAGCAG AGATACACCT GCCATGTGCA
 GCATGAGGGT CTGCCCGAGC CCCTCACCCT GAGATGGGAG CCATCTTCCC
 AGCCCACCGT CCCCATCGTG GGCATCGTTG CTGGCCTGGT TCTACTTGTA
 GCTGTGGTCA CTGGAGCTGT GGTCGCTGCT GTAATGTGGA GGAAGAAGAG
 CTCAGATAGA AAAGGAGGGA GCTACTCTCA GGCTGCAAGC AGCAACAGTG
 CCCAGGGCTC TGATGTGTCT CTCACGGCTT GAAAGTGTGA *
