>DL;IPD:MHC04389
IPD:MHC04389 Gogo-DRB*W8:01 219 bases
 CGTTTCTTGT GGCAGACTAA GTCTGAGTGT CATTTCTTCA ATGGGACGGA
 GCGGGTGCGG TACCTGGACA GATACTTCTA TAACCAGGAG GAGACCGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGATGCCG AGTACTGGAA CAGCCAGAAG GACCTCCTGG AGCAGAGGCG
 GGCCGACGTG GACACCTAC*   
>DL;IPD:MHC00235
IPD:MHC00235 Gogo-DRB*W8:02 270 bases
 CACGTTTCTT GTGGCAGACT AAGTCTGAGT GTCATTTCTT CAATGGGACG
 GAGCGGGTGC GGTACCTGGA CAGATACTTC TATAACCAGG AGGAGACCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGATGC CGAGTACTGG AACAGCCAGA AGGACTTCCT GGAGCAGAAG
 CGGGGCCAGG TGGACAATTA CTGCAGACAC AACTACGGGG TTGGTGAGAG
 GTTCACAGTG CAGCGGCGAG *  
>DL;IPD:MHC04390
IPD:MHC04390 Gogo-DRB1*02:01 219 bases
 CGTTTCCTGT TGCAGCCTAA GGGGGAGTGT CATTTCTTCA ATGGGACGGA
 GCGGGTGCGG TTCCTGGACA GATACTTCTA TAACCAGGAG GAGTACGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGGCGCCG AGTACTGGAA CAGCCAGAAG GACCTCCTGG AGCAGAAGCG
 GGGCCAGGCG GACACCTAC*   
>DL;IPD:MHC00222
IPD:MHC00222 Gogo-DRB1*03:01 270 bases
 CACGTTTCTT GGAGTACTCT ACGGGTGAGT GTTATTTCTT CAATGGGACG
 GAGAGGGTGC GGTTCCTGGA CAGATACTTC TACAACCAAG AGGAGTACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGATGC CGAGTACTGG AACAGCCAGA AGGACATCCT GGAAGACAGG
 CGGGCCTCGG TGGACACCTA TTGCAGACAC AACTACGGGG TTGGGGAGAG
 CTTCACAGTG CAGCGGCGAG *  
>DL;IPD:MHC04391
IPD:MHC04391 Gogo-DRB1*03:02 219 bases
 CGTTTCTTGG AGTACTCTAC GTCTGAGTGT CATTTCTTCA ATGGGACGGA
 GCGGGTGCGG TACCTGGACA GATACTTCCA TAACCAAGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGTCGCCG AGTACTGGAA CAGCCAGAAG GACCTCCTGG AGCAGAAGCG
 GGCCGCGGTG GACACCTAC*   
>DL;IPD:MHC02074
IPD:MHC02074 Gogo-DRB1*03:07 270 bases
 CACGTTTCTT GGAGTACTCT ACGTCTGAGT GTCATTTCTT CAATGGGACG
 GAGCGGGTGC GGTACCTGGA CAGATACTTC CATAACCAAG AGGAGCTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGATGC CGAGTACTGG AACAGCCAGA AGGACATCCT GGAAGACCAG
 CGGGCCTCGG TGGACACCTA TTGCAGACAC AACTACGGGG TTGTGGAGAG
 CTTCACAGTG CAGCGGCGAG *  
>DL;IPD:MHC00223
IPD:MHC00223 Gogo-DRB1*03:08 262 bases
 TTGGAGTACT CTACGGGTGA GTGTTATTTC TTCAATGGGA CGGAGAGGGT
 GCGGTTCCTG GACAGATACT TCTACAACCA AGAGGAGTAC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAT
 GCCGAGTACT GGAACAGCCA GAAGGACATC CTGGAAGACA GGCGGGCCCT
 GGTGGACACC TATTGCAGAC ACAACTACGG GGTTGGGGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC01433
IPD:MHC01433 Gogo-DRB1*03:09 216 bases
 TTCTTGGAGT ACTCTACGGG TGAGTGTTAT TTCTTCAATG GGACGGAGAG
 GGTGCGGTTC CTGGACAGAT ACTTCTACAA CCAAGAGGAG TACGTGCGCT
 TCGACAGCGA CGTGGGGGAG TACCGGGCGG TGACGGAGCT GGGGCGGCCT
 AGCGCCGAGT ACTGGAACAG CCAGAAGGAC ATCCTGGAAG ACAGGCGGGC
 CCTGGTGGAC ACCTAT*   
>DL;IPD:MHC01434
IPD:MHC01434 Gogo-DRB1*03:10 216 bases
 TTCTTGGAGT ACTCTACGTC TGAGTGTCAT TTCTTCAATG GGACGGAGCG
 GGTGCGGTAC CTGGACAGAT ACTTCCATAA CCAAGAGGAG AACGTGCGCT
 TCGACAGCGA CGTGGGGGAG TACCGGGCGG TGACGGAGCT GGGGCGGCCT
 GATGCCGAGT ACTGGAACAG CCAGAAGGAC ATCCTGGAAG ACCAGCGGGC
 CTCGGTGGAC ACCTAT*   
>DL;IPD:MHC01435
IPD:MHC01435 Gogo-DRB1*03:11 216 bases
 TTCTTGGAGT ACTCTACGTC TGAGTGTCAT TTCTTCAATG GGACGGAGCG
 GGTGCGGTAC CTGGACAGAT ACTTCCATAA CCAAGAGGAG TTCGTGCGCT
 TCGACAGCGA CGTGGGGGAG TACCGGGCGG TGACGGAGCT GGGGCGGCCT
 GATGCCGAGT ACTGGAACAG CCAGAAGGAC ATCCTGGAAG ACCAGCGGGC
 CTCGGTGGAC ACCTAT*   
>DL;IPD:MHC01436
IPD:MHC01436 Gogo-DRB1*03:12 216 bases
 TTCTTGGAGT ACTCTACGTC TGAGTGCCAT TTCTTCAATG AGACGGAGCG
 GGTGCGGTAT CTGCACAGAT ACATCTATAA CCAAGAGGAG GACGCGCGCT
 TCGACAGCGA CGTGGGGGAG TACCGGGCGG TGACGGAGCT GGGGCGGCCT
 GCTGCCGAGT ACTGGAACAG CCGGAAGGAC GTCCTGGAGC AGAAGCGGGG
 CCAGGTGGAC AATTAC*   
>DL;IPD:MHC01437
IPD:MHC01437 Gogo-DRB1*03:13 216 bases
 TTCTTGGAGT ACTCTACGTC TGAGTGTCAT TTCTTCAATG GGACGGAGCG
 GGTGCGGTAC CTGGACAGAT ACATCTATAA CCAAGAGGAG GACGCGCGCT
 TCGACAGCGA CGTGGGGGAG TACCGGGCGG TGACGGAGCT GGGGCGGCCT
 AGCGCCGAGT ACTGGAACAG CCAGAAGGAC ATCCTGGAAG ACAGGCGGGC
 CGAGGTGGAC ACCGTG*   
>DL;IPD:MHC01438
IPD:MHC01438 Gogo-DRB1*03:14 216 bases
 TTCTTGGAGT ACTCTACGTC TGAGTGTCAT TTCTTCAATG GGACGGAGCG
 GGTGCGGTAC CTGGACAGAT ACTTCCATAA CCAAGAGGAG CTCGTGCGCT
 TCGACAGCGA CGTGGGGGAG TACCGGGCGG TGACGGAGCT GGGGCGGCCT
 GATGCCGAGT ACTGGAACAG CCAGAAGGAC ATCCTGGAAG ACCAGCGGGC
 CTCGGTGGAC ACCTAC*   
>DL;IPD:MHC00224
IPD:MHC00224 Gogo-DRB1*10:01 270 bases
 CACGTTTCTT GGATCAGGCT AAGGCTGAGT GTCATTTCTT CAATGGGACG
 GAGCGGGTGC GGTTACTGGA GAGACGCATC CATAACCAAG AGGAGTACGC
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGATGC CGAGTACTGG AACAGCCAGA AGGACCTCCT GGAGCAGAGG
 CGGGCCGACG TGGACACCTT CTGCAGACAC AACTACAGGG TTGGTGAGAG
 GTTCACAGTG CAGCGGCAAG *  
>DL;IPD:MHC01439
IPD:MHC01439 Gogo-DRB1*10:02 216 bases
 TTCTTGGATC AGGCTAAGGC TGAGTGTCAT TTCTTCAATG GGACGGAGCG
 GGTGCGGTTA CTGGAGAGAC GCATCCATAA CCAAGAGGAG TACGCGCGCT
 ACGACAGCGA CGTGGGGGAG TACCGGGCGG TGACGGAGCT GGGGCGGCCT
 GATGCCGAGT ACTGGAACAG CCAGAAGGAC CTCCTGGAGC AGAGGCGGGC
 CGACGTGGAC ACCTTC*   
>DL;IPD:MHC00225
IPD:MHC00225 Gogo-DRB3*01:01 270 bases
 CACGTTTCTT GGAGCTGCGT AAGTCTGAGT GTCATTTCTT CAATGGGACG
 GAGCTGGTGC GGTACCTGGA CAGATACTTC CATAACCAAG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGTCGC CGAGTACTGG AACAGCCAGA AGGACCTCCT GGAGCAGAAG
 CGGGGCCGGG TGGACAATTA CTGCAGACAC AACTACGGGG TTGTGGAGAG
 CTTCACAGTG CAGCGGCGAG *  
>DL;IPD:MHC00226
IPD:MHC00226 Gogo-DRB3*01:07 270 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG
 GAGCGGGTGC GGTTCCTTGA GAGGTACATC CATAACCAAG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGATGC CGAGTCCTGG AACAGCCAGA AGGACCTCCT GGAGCAGAAG
 CGGGGCCAGG TGGACAATTA CTGCAGACAC AACTACGGGG TTGGTGAGAG
 CTTCACAGTG CAGCGGCGAG *  
>DL;IPD:MHC01440
IPD:MHC01440 Gogo-DRB3*01:08 216 bases
 TTCTTGGAGC TGCGTAAGTC TGAGTGTCAT TTCTTCAATG GGACGGAGCT
 GGTGCGGTAC CTGGACAGAT ACTTCCATAA CCAAGAGGAG TTCGTGCGCT
 TCGACAGCGA CGTGGGGGAG TACCGGGCGG TGACGGAGCT GGGGCGGCCT
 GATGCCGAGT ACTGGAACAG CCAGAAGGAC CTCCTGGAGC AGAAGCGGGG
 CCGGGTGGAC AATTAC*   
>DL;IPD:MHC00227
IPD:MHC00227 Gogo-DRB3*04:01 270 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG
 GAGCGGGTGC GGTTCCTTGA GAGATACATC CATAACCAAG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGATGC CGAGTACTGG AACAGCCAGA AGGACATCCT GGAAGACGAG
 CGGGCCTCGG TGGACACCTA TTGGAGATAC AACTACGGGA TTGTGGAGAG
 CTTCACAGTG CAGCGGCGAG *  
>DL;IPD:MHC01441
IPD:MHC01441 Gogo-DRB3*04:02 216 bases
 TTCTTGGAGC TGCGTAAGTC TGAGTGTCAT TTCTTCAATG GGACGGAGCG
 GGTGCGGTTC CTTGAGAGAT ACATCCATAA CCAAGAGGAG TTCGTGCGCT
 TCGACAGCGA CGTGGGGGAG TTCCGGGCGG TGACGGAGCT GGGGCGGCCT
 GCTGCCGAGT ACTGGAACAG CCGGAAGGAC GTCCTGGAAG ACGAGCGGGC
 CTCGGTGGAC ACCTAT*   
>DL;IPD:MHC00228
IPD:MHC00228 Gogo-DRB5*01:01 270 bases
 CACGTTTCTT GAAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTATCTGCA CAGAGACATC TATAACCAAG AGGAGGACTT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC CGAGTACTGG AACAGCCAGA AGGACGTCCT GGAAGACGAG
 CGGGCCTCGG TGGACACCTA TTGCAGACAC AACTACGGGG TTGTGGAGAG
 CTTCACAGTG CAGCGGCGAG *  
>DL;IPD:MHC00229
IPD:MHC00229 Gogo-DRB5*02:01 219 bases
 CGTTTCTTGA AGCAGGATAA GTATGAGTGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCGG TATCTGCACA GAGACATCTA TAACCAAGAG GAGGACTTGC
 GCTTCGACAG CGACGTGGAG GAGTTCCAGG CAGTGACAGA ACTGGGGCGG
 CCTGTCGCAG AGAACTGGAA CAGCCAGAAG GGAATCCTGG AGGAGAATCG
 GGACGCGGTG GACACCTAC*   
>DL;IPD:MHC00230
IPD:MHC00230 Gogo-DRB5*04:03 243 bases
 TTGAAGCAGG ATAAGGCTGA GTGTCATTTC TTCAACGGGA CCGAGCGGGT
 GCGGTTCCTG CACAGAGACA TCTATAACCA AGAGGAGGAC GCGCTCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGTGGTGA CGGAGCTGGG GCGGCCGGAC
 GCGGAGTACT GGAACAGCCA GAAGGACATC CTGGAGCGGA TGCGGGCCAC
 GGTGGACACC TGCAGATACG ACTACGATAT TATAGAGAGC TTC*
>DL;IPD:MHC02075
IPD:MHC02075 Gogo-DRB5*05:01 270 bases
 CACGTTTCTT GAAGCAGGAT AAGGGTGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGCA CAGATACATC TATAACCAAG AGGAGGACGC
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGCTGC CGAGTACTGG AACAGCCGGA AGGACGTCCT GGAGCGGAGG
 CGGGCCGAGG TGGACACCGT GTGCAGACAC AACTACGGGG TTGTGGAGAG
 CTTCACAGTG CAGCGGCGAG *  
>DL;IPD:MHC01442
IPD:MHC01442 Gogo-DRB5*05:04 216 bases
 TTCTTGAAGC AGGATAAGTG TGAGTGTCAT TTCTTCAACG GGACGGAGCG
 GGTGCGGTAT CTGCACAGAC ACATCTATAA CCAAGAGGAG GACGCGCGCT
 TCGACAGCGA CGTGGGGGAG TACCGGGCTG TGACGGAGCT GGGGCGGCCT
 GACGCCGAGT ACTGGAACAG CCGGAAGGAC GTCCTGGAGC GGAGGCGGGC
 CGAGGTGGAC AATTAC*   
>DL;IPD:MHC01443
IPD:MHC01443 Gogo-DRB5*05:05 216 bases
 TTCCTGAAGC AGGATAAGTG TGAGTGTCAT TTCTTCAACG GGACGGAGCG
 GGTGCGGTAT CTGCACAGAC ACATCTATAA CCAAGAGGAG GACGCGCGCT
 TCGACAGCGA CGTGGGGGAG TACCGGGCTG TGACGGAGCT GGGGCGGCCT
 GACGCCGAGT ACTGGAACAG CCGGAAGGAC GTCCTGGAGC GGAGGCGGGC
 CGAGGTGGAC AATTAC*   
>DL;IPD:MHC01444
IPD:MHC01444 Gogo-DRB5*05:06 216 bases
 TTCTTGAAGC AGGATAAGCA TGAGTGTCAT TTCTTCAACG GGACGGAGCG
 GGTGCGGTAT CTGCACAGAT ACATCTATAA CCAAGAGGAG GACGCGCGCT
 TCGACAGCGA CGTGGGGGAG TACCGGGCGG TGACGGAGCT GGGGCGGCCT
 GCTGCCGAGT ACTGGAACAG CCGGAAGGAC GTCCTGGAGC GGAGGCGGGC
 CGAGGTGGAC ACCGTG*   
>DL;IPD:MHC00231
IPD:MHC00231 Gogo-DRB6*01:02N 268 bases
 CACGTTTCTT GGAGAAGGCT AAGTGTGAGT GTCATATCTT CAATGGGACG
 AAGCGGGTGC GGTACCTGAA CAGATACATC CATAAATGGG AAGAGAACCT
 GCGCTTCGAC AGCGACGTGG AGGAGTTCCA GGCAGTGACA GAACTGGGGC
 GGCCTGTCGC AGAGAACTGG AACAGCCAGA AGGGAATCCT GGAGGAGAAT
 CGGGACAAGG TGGACATACT GCAGATACAA TTACGGGGTT TTTGAGAGCT
 TCACAGTGCA GCCATCAG*   
>DL;IPD:MHC00232
IPD:MHC00232 Gogo-DRB6*01:03N 244 bases
 TTGGAGAAGG CTAAGTGTGA GTGTCATATC TTCAATGGGA CGAAGCGGGT
 GCAGTACCTG AACAGATACA TCCATAAACG GGAAGAGAAC CTGCGCTTCG
 ACAGCGACGT GGAGGAGTTC CAGGCGGTGA CAGAACTGGG GCGGCCTGTC
 GCCGAGAACT GGAACAGCCA GAAGGGAATC CTGGAGGAGA AGCGGGACAA
 GGTGGACATA CTGCAGATAC AATTACGGGG TTTTTGAGAG CTTC*
>DL;IPD:MHC01445
IPD:MHC01445 Gogo-DRB6*01:04 214 bases
 TTCTTGGAGA AGGCTAAGTG TGAGTGTCAT ATCTTCAATG GGACGAAGCG
 GGTGCTGTAC CTGAACAGAT ACATCCATAA ATGGGAAGAG AACCTGCGCT
 TCGACAGCGA CGTGGAGGAG TTCCAGGCAG TGACAGAACT GGGGCGGCCT
 GTCGCAGAGA ACTGGAACAG CCAGAAGGGA ATCCTGGAGG AGAATCGGGA
 CAAGGTGGAC ATAC*   
>DL;IPD:MHC00233
IPD:MHC00233 Gogo-DRB6*02:02N 270 bases
 CACGTTTCTT GGAGCAGGCT AAGTGTGAGT GTCATATCCT CAATGGGACG
 GAGCGGGTTC AGTACCTGAA CAGATACATC CATAAACGGG AGGAGAACCT
 GCGCTTCGAC AGCGACGTAG GGGAGTTCCA GGCGGTAACG GAACTGGGGC
 GGCCTGTCGC AGAGAAATGG AACAGCCAGA AGGAAATCCT GGAGGAGAAG
 CGGGACAAGG TGGACACCTA CTGCAGATAC AGTTACGGGG TTTTTGAGAG
 CTTCACAGTA CCGCGATGAG *  
>DL;IPD:MHC00234
IPD:MHC00234 Gogo-DRB6*02:03N 259 bases
 GAGCAGGCTA AGTGTGAGTG TCATATCCTC AATGGGACGG AGCGGGTTCA
 GTACCTGAAC AGATACATCC ATAAACGGGA GGAGAACCTG CGCTTCGACA
 GCGACGTAGG GGAGTTCCAG GCGGTAACGG AACTGGGGCG GCCTGTCGCA
 GAGAAATGGA ACAGCCAGAA GGAAATCCTG GAGGAGAAGC GGGACAAGGT
 GGACACCTAC TGCAGATACA GTTACGGGGT TTTTGAGAGC TTCACAGTAC
 TGCGATGAG*    
>DL;IPD:MHC01446
IPD:MHC01446 Gogo-DRB6*02:04 216 bases
 TTCTTGGAGC AGGCTAAGTG TGAGTGTCAT ATCCTCAATG GGACGGAGCG
 GGTGCAGTAC CTGAACAGAT ACATCCATAA ACGGGAGGAG AACCTGCGCT
 TCGACAGCGA CGTAGGGGAG TTCCAGGCGG TAACGGAACT GGGGCGGCCT
 GTCGCAGAGA AATGGAACAG CCAGAAGGAA ATCCTGGAGG AGAAGCGGGA
 CAAGGTGGAC ACCTAC*   
