>DL;IPD:MHC00239
IPD:MHC00239 Gogo-H*01 360 bases
 MEPRTLLLLL SGALALTQTW ARSHSMRYFY TTMSRPGRGE PRFISVGYVD
 DTQFVRFDSD DASPREEPRA PWMEREGPEY WDRNTQICKA QAQTERENLR
 IALRYYNQSE GGSHTMQVMY GCDVGPDGRF LRGYEQHAYD GKDYIALNED
 LRSWTAADMA AQITKRKWEA ARRAEQLRAY LEGEFVEWLR RYLENGKETL
 QRADPPKTHM THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEDQTQDTE
 LVETRPGGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP LTLRWEPSSQ
 PTVPIVGIVA GLVLLVAVVT GAVVAAVMWR KKSSDRKGGS YSQAASSNSA
 QGSDVSLTAX *   
