>DL;IPD:MHC00183
IPD:MHC00183 Gogo-B*01:01 363 bases
 MRVTAPRTLL LLLSAALALT ETWAGSHSMR YFDTAVSRPG RGEPRFITVG
 YVDDTQFVRF DSDAASPRME PRAPWIEQEG PEYWDRETQT SKAQAQTDRE
 NLRIALRYYN QSEAGSHTIQ RMFGCDVGPD GRLLRGYSQS AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAAREAEQL RAYLEGTCVE WLRRYLENGR
 ETLQRADTPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEER YTCHVQHEGL PKPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVIGAVVTAV ICRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00184
IPD:MHC00184 Gogo-B*01:02 363 bases
 MRVTAPRTLL LLLSAALALT ETWAGSHSMR YFDTAVSRPG RGEPRFITVG
 YVDDTQFVRF DSDAASPRME PRAPWIEQEG PEYWDRETQT SKAQAQTDRE
 NLRIALRYYN QSEAGSHTFQ RMFGCDVGPD GRLLRGYSQS AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAAREAEQL RAYLEGTCVE WLRRYLENGR
 ETLQRADTPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEER YTCHVQHEGL PKPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVIGAVVTAV ICRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00185
IPD:MHC00185 Gogo-B*01:03 363 bases
 MRVTAPRTLL LLLSAALALT ETWAGSHSMR YFDTAVSRPG RGEPRFITVG
 YVDDTQFVRF DSDAASPRME PRAPWIEQEG PEYWDRETQT SKAQAQTDRE
 NLRIALRYYN QSEAGSHTIQ WMYGCDMGPD GRLLRGYSQS AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAAREAEQL RAYLEGTCVE WLRRYLENGR
 ETLQRADTPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEER YTCHVQHEGL PKPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVIGAVVTAV ICRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00186
IPD:MHC00186 Gogo-B*02:01 364 bases
 MQVTAPRTLL LLLSAALALT ETWAGSHSMR YFHTAMSRPG RGEPRFITVG
 YVDDTQFVWF DSDAASPRKE PRTPWIEQEG PEYWDRETQI SKTNTQTYRV
 GLGTLRGYYN QSEDGSHTIQ RMYGCDMGPD GRLLRGYSQL AYDGKDYLAL
 NEDLSSWTAA DTAAQITQRK WEAARAAEQE RAYLEGLCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGEEQR YTCRVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLVV TVAVVAVVAA VMCRRKSSGG KGGSYSQAAS
 SDSAQGSDVS LTAX*   
>DL;IPD:MHC00187
IPD:MHC00187 Gogo-B*03:01 364 bases
 MQVTAPRTLL LLLSAALALT ETWAGSHSMR YFYTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASPRME PRSPWIEQEA PEYWDGETRK VKASAQIYRV
 GLGTLRGYYN QSESGSHTIQ WMYGCDMGPD GRLLRGYSQY AYDGKDYLAL
 NEDLSSWTAA DTAAQVTQRK WEAARVAEQE RAYLEGLCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGEEQR YTCRVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLVV TVAVVAVVAA VMCRRKSSGG KGGGYSQAAS
 SDSAQGSDVS LTAX*   
>DL;IPD:MHC00188
IPD:MHC00188 Gogo-B*04:01 348 bases
 ALALTETWAG SHSMRYFDTA VSRPGRGEPR FITVGYVDDT QFVRFDSDAA
 SPRMEPRAPW IEQEAPEYWD GETRKVKASA QTYRVDLGTL RGYYNQSESG
 SHTLQRMFGC DVGPDGRLLR GYSQFAYDGK DYLALNEDLS SWTAADTAAQ
 ITQRKWEAAR AAEQERAYLE GLCVEWLRRY LENGKETLQR ADPPKTHVTH
 HPISDHEATL RCWALGFYPA EITLTWQRDG EDQTQDTELV ETRPAGDRTF
 QKWAAVVVPS GEEQRYTCRV QHEGLPEPLT LRWESSSQST IPIVGIVAGL
 AVLVVTVAVV AVVAAVMCRR KSSGGKGGGY SQAASSDSAQ GSDVSLTA*
>DL;IPD:MHC00189
IPD:MHC00189 Gogo-B*05:01 347 bases
 ALALTETWAG SHSMRYFDTA VSRPGRGEPR FISVGYVDDT QFVRFDSDAA
 SPRMEPRAPW IEQEGPEYWD GETQTSKAQA QTDRENLRIA LRYYNQSEDG
 SHTFQKMYGC DMGPDGRLLR GYSQFAYDGK DYIALNEDLS SWTAADTAAQ
 ITQRKWEAAR VAEQLRAYLE GLCVEWLRRY LENGRETLQR ADPPKTHVTH
 HPISDHEATL RCWALAFYPA EITLTWQRDG EDQTQDTELV ETRPAGDGTF
 QKWAAVVVPS GEEERYTCHV QHEGLPKPLT LRWEPSSQST IPIVGIVAGL
 AVLAVVVIGA VVTAVICRRK SSGGKGGGYS QAASSDSAQG SDVSLTA*
>DL;IPD:MHC00190
IPD:MHC00190 Gogo-B*05:02 347 bases
 ALALTETWAG SHSMRYFDTA VSRPGRGEPR FISVGYVDDT QFVRFDSDAA
 SPRMEPRAPW IEQEGPEYWD RETQTSKAQA QTDRENLRIA LRYYNQSEDG
 SHTIQWMYGC DMGPDGRLLR GYSQFAYDGK DYIALNEDLS SWTAADTAAQ
 ITQRKWEAAR VAEQLRAYLE GLCVEWLRRY LENGRETLQR ADPPKTHVTH
 HPISDHEATL RCWALAFYPA EITLTWQRDG EDQTQDTELV ETRPAGDGTF
 QKWAAVVVPS GEEERYTCHV QHEGLPKPLT LRWEPSSQST IPIVGIVAGL
 AVLAVVVIGA VVTAVICRRK SSGGKGGGYS QAASSDSAQG SDVSLTA*
>DL;IPD:MHC01426
IPD:MHC01426 Gogo-B*05:03 191 bases
 ALALTETWAG SHSMRYFDTA VSRPGRGEPR FISVGYVDDT QFVRFDSDAA
 SPRMEPRAPW IEQEGPEYWD GETQTSKAQA QTDRENLRIA LRYYNQSEDG
 SHTFQKMYGC DVGPDGRLLR GYSQFAYDGK DYIALNEDLS SWTAADTAAQ
 ITQRKWEAAR VAEQLRAYLE GLCVEWLRRY LENGKETLQR A*
