>DL;IPD:MHC00208
IPD:MHC00208 Gogo-DQA1*01:01 188 bases
 TCTTACGGTC CCTCTGGCCA GTTCACCCAT GAATTTGATG GAGATGAGCA
 GTTCTACGTG GACCTGGAGA GGAAGGAGAC TGCCTGGCGG TGGCCTGAGT
 TCAGCAAATT TGGAGGTTTT GACCCACAGG GTGCACTGAG AAACATGGCT
 GTGGCAAAAC ACAACTTGAA CATCATGATT AACCGCTA* 
>DL;IPD:MHC00209
IPD:MHC00209 Gogo-DQA1*03:01 188 bases
 TCTTACGGTC CCTCTGGGCA GTACAGCCAT GAATTTGATG GAGACGAGGA
 GTTCTATGTG GACCTGGAGA GGAAGGAGAC TGTCTGGCAG TTGCCTATGT
 TTAGCAGATT GAGAAGATTT GACCCGCAGG GTGCACTGAC AAACATCGCT
 GTGCTAAAAC ATAACTTGAA CATCGTGATT AACCGCTC* 
>DL;IPD:MHC00210
IPD:MHC00210 Gogo-DQA1*05:01 185 bases
 TCTTACGGTC CCTCTGGCCA GTTCACCCAT GAATTTGATG GAGATGAGCA
 GTTCTACGTG GACCTGGAGA GGAAGGAGAC TGTCTGGTGT TTGCCTGTGC
 TCAGACAATT TAGATTTGAC CCGCAATTTG CACTGACAAA CATCGCTGTC
 CTAAAACATA ACTTGAACAG TCTGATTAAA CGCTC* 
>DL;IPD:MHC00211
IPD:MHC00211 Gogo-DQA1*05:02 185 bases
 TCTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGAA
 GTTCTACGTG GACCTGGAGA GGAAGGAGAC TGTCTGGTGT TTGCCTGTTC
 TCAGACAATT TAGATTTGAC CCGCAATTTG CACTGACAAA CATCGCTGTC
 CTAAAACATA ACTTGAACAG TCTGATTAAA CGCTC* 
>DL;IPD:MHC00212
IPD:MHC00212 Gogo-DQA1*05:03 185 bases
 TCTTACGGTC CCTCTGGCCA GTTCACCCAT GAATTTGATG GAGATGAGCA
 GTTCTACGTG GACCTGGAGA GGAAGGAGAC TGTCTGGTGT TTGCCTGTTC
 TCAGACAATT TAGATTTGAC CCGCAATTTG CACTGACAAA CATCGCTGTC
 CTAAAACATA ACTTGAACAG TCTGATTAAA CGCTC* 
>DL;IPD:MHC00213
IPD:MHC00213 Gogo-DQA1*20:01 188 bases
 TCTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGACGAGGA
 GTTCTATGTG GACCTGGAGA GGAAGGAGAC TGTCTGGCAG TTGCCTCTGT
 TCCGCAGCTT TAGAAGATAT GACCCGCAGG GTGCACTGAC CAACATTGCT
 ATTGCAAAAC ACAACTTGAA CATCCTGATT AAGTGCTC* 
>DL;IPD:MHC00214
IPD:MHC00214 Gogo-DQA2*01:01 188 bases
 TCTCACGGTC CCTCTGGCCA GTACACCCAT GAATCTGATG GAGACGAGGA
 GTTCTACGTG GACCTGGAGA CGAAAGAGAC TGTCTGGCAG TTGCCTATGT
 TTAGCAGATT TATAAGTTTT GACCCGCAGA GTGCACTGAG AAATATGGCT
 GTGGGAAAAC ACACCTTGGA ATTCATGATG AGACAGTC* 
>DL;IPD:MHC00215
IPD:MHC00215 Gogo-DQA2*01:02 188 bases
 TCTCACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGACGAGGA
 GTTCTACGTG GACCTGGAGA CGAAAGAGAC TGTCTGGCAG TTGCCTATGT
 TTAGCAGATT TATAAGTTTT GACCCGCAGA GTGCACTGAG AAATATGGCT
 GTGGGAAAAC ACACCTTGGA ATTCATGATG AGACAGTC* 
