>DL;IPD:MHC00183
IPD:MHC00183 Gogo-B*01:01 1089 bases
 ATGCGGGTCA CGGCGCCCCG AACCCTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCGACA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACAGTGGGC
 TACGTGGACG ACACCCAGTT CGTGAGGTTC GACAGCGACG CCGCGAGTCC
 GAGGATGGAG CCCCGGGCGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGAGA GACACAGACC TCCAAGGCTC AGGCACAGAC TGACCGAGAG
 AACCTGCGGA TCGCGCTCCG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCATCCAG AGGATGTTTG GCTGCGACGT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TAGCCAGTCC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACCGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGAGGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAGA
 GAGACGCTGC AGCGCGCGGA CACCCCAAAG ACACACGTGA CCCACCACCC
 GATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGCGAGGA CCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGCA GGAGATGGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGGAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGAAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCATCG GAGCTGTGGT CACTGCTGTG ATATGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00184
IPD:MHC00184 Gogo-B*01:02 1089 bases
 ATGCGGGTCA CGGCGCCCCG AACCCTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCGACA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACAGTGGGC
 TACGTGGACG ACACCCAGTT CGTGAGGTTC GACAGCGACG CCGCGAGTCC
 GAGGATGGAG CCCCGGGCGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGAGA GACACAGACC TCCAAGGCTC AGGCACAGAC TGACCGAGAG
 AACCTGCGGA TCGCGCTCCG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCTTCCAG AGGATGTTTG GCTGCGACGT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TAGCCAGTCC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACCGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGAGGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAGA
 GAGACGCTGC AGCGCGCGGA CACCCCAAAG ACACACGTGA CCCACCACCC
 GATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGCGAGGA CCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGCA GGAGATGGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGGAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGAAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCATCG GAGCTGTGGT CACTGCTGTG ATATGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00185
IPD:MHC00185 Gogo-B*01:03 1089 bases
 ATGCGGGTCA CGGCGCCCCG AACCCTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCGACA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACAGTGGGC
 TACGTGGACG ACACCCAGTT CGTGAGGTTC GACAGCGACG CCGCGAGTCC
 GAGGATGGAG CCCCGGGCGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGAGA GACACAGACC TCCAAGGCTC AGGCACAGAC TGACCGAGAG
 AACCTGCGGA TCGCGCTCCG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCATCCAG TGGATGTATG GCTGCGACAT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TAGCCAGTCC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACCGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGAGGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAGA
 GAGACGCTGC AGCGCGCGGA CACCCCAAAG ACACACGTGA CCCACCACCC
 GATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGCGAGGA CCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGCA GGAGATGGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGGAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGAAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCATCG GAGCTGTGGT CACTGCTGTG ATATGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00186
IPD:MHC00186 Gogo-B*02:01 1092 bases
 ATGCAGGTCA CGGCGCCCCG AACCCTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCCACA
 CCGCCATGTC CCGGCCCGGC CGCGGAGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGTGGTTC GACAGCGACG CCGCGAGTCC
 GAGGAAGGAG CCGCGGACGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGAGA GACACAGATC TCCAAGACCA ACACACAGAC TTACCGAGTG
 GGCCTGGGGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG ACGGGTCTCA
 CACCATCCAG AGGATGTATG GCTGCGACAT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TAGCCAGTTG GCCTACGACG GCAAGGATTA CCTCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACCGCGG CTCAGATCAC
 ACAGCGCAAG TGGGAGGCGG CCCGTGCGGC GGAGCAGGAG AGAGCCTACC
 TGGAGGGCCT GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGAG ATGGCGAGGA CCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAACAGAGA TACACATGCC
 GTGTGCAGCA CGAGGGGCTG CCGGAGCCCC TTACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTTGTGGTC ACCGTAGCTG TGGTCGCTGT GGTCGCTGCT GTGATGTGTA
 GGAGGAAGAG CTCAGGTGGA AAAGGAGGGA GCTACTCTCA GGCTGCGTCC
 AGCGACAGTG CCCAGGGCTC TGATGTGTCT CTCACAGCTT GA*
>DL;IPD:MHC00187
IPD:MHC00187 Gogo-B*03:01 1092 bases
 ATGCAGGTCA CGGCGCCCCG AACTCTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCTACA
 CCTCCGTGTC CCGGCCCGGC CGCGGAGAGC CCCGCTTCAT CGCAGTGGGC
 TACGTGGACG ACACCCAGTT CGTGAGGTTC GACAGCGACG CCGCGAGTCC
 GAGGATGGAG CCCCGGTCGC CATGGATAGA GCAGGAGGCG CCGGAGTATT
 GGGACGGGGA GACACGGAAA GTCAAGGCCT CCGCACAGAT TTACCGAGTG
 GGCCTGGGGA CCCTGCGCGG CTACTACAAC CAGAGCGAGT CCGGGTCTCA
 CACCATCCAG TGGATGTATG GCTGCGACAT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TAGCCAGTAC GCCTACGACG GCAAGGATTA CCTCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACCGCGG CTCAGGTCAC
 ACAGCGCAAG TGGGAGGCGG CCCGTGTGGC GGAGCAGGAG AGAGCCTACC
 TGGAGGGCCT GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGAG ATGGCGAGGA CCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAACAGAGA TACACATGCC
 GTGTGCAGCA CGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTTGTGGTC ACCGTAGCTG TGGTCGCTGT GGTCGCTGCT GTGATGTGTA
 GGAGGAAGAG CTCAGGTGGA AAAGGAGGGG GCTACTCTCA GGCTGCGTCC
 AGCGACAGTG CCCAGGGCTC TGATGTGTCT CTCACAGCTT GA*
>DL;IPD:MHC00188
IPD:MHC00188 Gogo-B*04:01 1047 bases
 GGCCCTGGCC CTGACCGAGA CCTGGGCCGG CTCCCACTCC ATGAGGTATT
 TCGACACCGC CGTGTCCCGG CCCGGCCGCG GGGAGCCCCG CTTCATCACC
 GTGGGCTACG TGGACGACAC CCAGTTCGTG AGGTTCGACA GCGACGCCGC
 GAGTCCGAGG ATGGAGCCCC GGGCGCCATG GATAGAGCAG GAGGCGCCGG
 AGTATTGGGA CGGGGAGACA CGGAAAGTCA AGGCCTCCGC ACAGACTTAC
 CGAGTGGACC TGGGGACCCT GCGCGGCTAC TACAACCAGA GCGAGTCCGG
 GTCTCACACC CTCCAGAGGA TGTTTGGCTG CGACGTGGGG CCGGACGGGC
 GCCTCCTCCG CGGGTATAGC CAGTTCGCCT ACGACGGCAA GGATTACCTC
 GCCCTGAACG AGGACCTGAG CTCCTGGACC GCGGCGGACA CCGCGGCTCA
 GATCACACAG CGCAAGTGGG AGGCGGCCCG TGCGGCGGAG CAGGAGAGAG
 CCTACCTGGA GGGCCTGTGC GTGGAGTGGC TCCGCAGATA CCTGGAGAAC
 GGGAAAGAGA CGCTGCAGCG CGCGGACCCC CCAAAGACAC ACGTGACCCA
 CCACCCCATC TCTGACCATG AGGCCACCCT GAGGTGCTGG GCCCTGGGCT
 TCTACCCTGC GGAGATCACA CTGACCTGGC AGCGAGATGG CGAGGACCAA
 ACTCAGGACA CCGAGCTTGT GGAGACCAGG CCAGCAGGAG ATAGAACCTT
 CCAGAAGTGG GCAGCTGTGG TGGTGCCTTC TGGAGAAGAA CAGAGATACA
 CATGCCGTGT GCAGCACGAG GGGCTGCCGG AGCCCCTCAC CCTGAGATGG
 GAGTCATCTT CCCAGTCCAC CATCCCCATC GTGGGCATTG TTGCTGGCCT
 GGCTGTCCTT GTGGTCACCG TAGCTGTGGT CGCTGTGGTC GCTGCTGTGA
 TGTGTAGGAG GAAGAGCTCA GGTGGAAAAG GAGGGGGCTA CTCTCAGGCT
 GCGTCCAGCG ACAGTGCCCA GGGCTCTGAT GTGTCTCTCA CAGCTTG*
>DL;IPD:MHC00189
IPD:MHC00189 Gogo-B*05:01 1044 bases
 GGCCCTGGCC CTGACCGAGA CCTGGGCCGG CTCCCACTCC ATGAGGTATT
 TCGACACCGC CGTGTCCCGG CCCGGCCGCG GGGAGCCCCG CTTCATCTCA
 GTGGGCTACG TGGACGACAC CCAGTTCGTG AGGTTCGACA GCGACGCCGC
 GAGTCCGAGG ATGGAGCCCC GGGCGCCATG GATAGAGCAG GAGGGGCCGG
 AGTATTGGGA CGGAGAGACA CAGACCTCCA AGGCTCAGGC ACAGACTGAC
 CGAGAGAACC TGCGGATCGC GCTCCGCTAC TACAACCAGA GCGAGGACGG
 GTCTCACACC TTCCAGAAGA TGTATGGCTG CGACATGGGG CCGGACGGGC
 GCCTCCTCCG CGGGTATAGC CAGTTCGCCT ACGACGGCAA GGATTACATC
 GCCCTGAACG AGGACCTGAG CTCCTGGACC GCGGCGGACA CCGCGGCTCA
 GATCACCCAG CGCAAGTGGG AGGCGGCCCG TGTGGCGGAG CAGCTGAGAG
 CCTACCTGGA GGGCCTGTGC GTGGAGTGGC TCCGCAGATA CCTGGAGAAC
 GGGAGGGAGA CGCTGCAGCG CGCGGACCCC CCAAAGACAC ACGTGACCCA
 CCACCCCATC TCTGACCATG AGGCCACCCT GAGGTGCTGG GCCCTGGCCT
 TCTACCCTGC GGAGATCACA CTGACCTGGC AGCGGGATGG CGAGGACCAA
 ACTCAGGACA CCGAGCTTGT GGAGACCAGG CCAGCAGGAG ATGGAACCTT
 CCAGAAGTGG GCAGCTGTGG TGGTGCCTTC TGGAGAAGAG GAGAGATACA
 CATGCCATGT GCAGCATGAG GGGCTGCCGA AGCCCCTCAC CCTGAGATGG
 GAGCCATCTT CCCAGTCCAC CATCCCCATC GTGGGCATTG TTGCTGGCCT
 GGCTGTCCTA GCAGTTGTGG TCATCGGAGC TGTGGTCACT GCTGTGATAT
 GTAGGAGGAA GAGCTCAGGT GGAAAAGGAG GGGGCTACTC TCAGGCTGCG
 TCCAGCGACA GTGCCCAGGG CTCTGATGTG TCTCTCACAG CTTG*
>DL;IPD:MHC00190
IPD:MHC00190 Gogo-B*05:02 1044 bases
 GGCCCTGGCC CTGACCGAGA CCTGGGCCGG CTCCCACTCC ATGAGGTATT
 TCGACACCGC CGTGTCCCGG CCCGGCCGCG GGGAGCCCCG CTTCATCTCA
 GTGGGCTACG TGGACGACAC CCAGTTCGTG AGGTTCGACA GCGACGCCGC
 GAGTCCGAGG ATGGAGCCCC GGGCGCCATG GATAGAGCAG GAGGGGCCGG
 AGTATTGGGA CCGAGAGACA CAGACCTCCA AGGCTCAGGC ACAGACTGAC
 CGAGAGAACC TGCGGATCGC GCTCCGCTAC TACAACCAGA GCGAGGACGG
 GTCTCACACC ATCCAGTGGA TGTATGGCTG CGACATGGGG CCGGACGGGC
 GCCTCCTCCG CGGGTATAGC CAGTTCGCCT ACGACGGCAA GGATTACATC
 GCCCTGAACG AGGACCTGAG CTCCTGGACC GCGGCGGACA CCGCGGCTCA
 GATCACCCAG CGCAAGTGGG AGGCGGCCCG TGTGGCGGAG CAGCTGAGAG
 CCTACCTGGA GGGCCTGTGC GTGGAGTGGC TCCGCAGATA CCTGGAGAAC
 GGGAGGGAGA CGCTGCAGCG CGCGGACCCC CCAAAGACAC ACGTGACCCA
 CCACCCCATC TCTGACCATG AGGCCACCCT GAGGTGCTGG GCCCTGGCCT
 TCTACCCTGC GGAGATCACA CTGACCTGGC AGCGGGATGG CGAGGACCAA
 ACTCAGGACA CCGAGCTTGT GGAGACCAGG CCAGCAGGAG ATGGAACCTT
 CCAGAAGTGG GCAGCTGTGG TGGTGCCTTC TGGAGAAGAG GAGAGATACA
 CATGCCATGT GCAGCATGAG GGGCTGCCGA AGCCCCTCAC CCTGAGATGG
 GAGCCATCTT CCCAGTCCAC CATCCCCATC GTGGGCATTG TTGCTGGCCT
 GGCTGTCCTA GCAGTTGTGG TCATCGGAGC TGTGGTCACT GCTGTGATAT
 GTAGGAGGAA GAGCTCAGGT GGAAAAGGAG GGGGCTACTC TCAGGCTGCG
 TCCAGCGACA GTGCCCAGGG CTCTGATGTG TCTCTCACAG CTTG*
>DL;IPD:MHC01426
IPD:MHC01426 Gogo-B*05:03 575 bases
 GGCCCTGGCC CTGACCGAGA CCTGGGCCGG CTCCCACTCC ATGAGGTATT
 TCGACACCGC CGTGTCCCGG CCCGGCCGCG GGGAGCCCCG CTTCATCTCA
 GTGGGCTACG TGGACGACAC CCAGTTCGTG AGGTTCGACA GCGACGCCGC
 GAGTCCGAGG ATGGAGCCCC GGGCGCCATG GATAGAGCAG GAGGGGCCGG
 AGTATTGGGA CGGAGAGACA CAGACCTCCA AGGCTCAGGC ACAGACTGAC
 CGAGAGAACC TGCGGATCGC GCTCCGCTAC TACAACCAGA GCGAGGACGG
 GTCTCACACC TTCCAGAAGA TGTATGGCTG CGACGTGGGG CCGGACGGGC
 GCCTCCTCCG CGGGTATAGC CAGTTCGCCT ACGACGGCAA GGATTACATC
 GCCCTGAACG AGGACCTGAG CTCCTGGACC GCGGCGGACA CCGCGGCTCA
 GATCACCCAG CGCAAGTGGG AGGCGGCCCG TGTGGCGGAG CAGCTGAGAG
 CCTACCTGGA GGGCCTGTGC GTGGAGTGGC TCCGCAGATA CCTGGAGAAC
 GGGAAGGAGA CGCTGCAGCG CGCGG*  
