>DL;IPD:MHC00191
IPD:MHC00191 Gogo-C*01:01 366 bases
 MRVMAPRTLI LLLSGALALT ETWAGSHSMR YFFTAVAPPG RGEPRFIAVG
 YVDDTQFVRF DSDAANTRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV
 SLRKLRGYYN QSEDGSHTFQ RMYGCDVGPD GRLQRGYDQL AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAARWAERQ RAYLEGLCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DIELVETRPA GDGTFQKWAA MVVPSGEEQR YTCHVQHKGL LEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV VFTGTVVAAV MCRRKSSGGK GGSCSQAACS
 NSAQGSDESL IACKAX*   
>DL;IPD:MHC00192
IPD:MHC00192 Gogo-C*01:02 366 bases
 MRVMAPRTLI LLLSGALALT ETWAGSHSMR YFFTAVAPPG RGEPRFIAVG
 YVDDTQFVRF DSDAANTRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV
 SLRKLRGYYN QSEDGSHTFQ RMYGCDVGPD GRLQRGYDQL AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAARWAERQ RAYLEGLCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DIELVETRPA GDGTFQKWAA MVVPSGEEQR YTCHVQHKGL LEPLTLRWEP
 SSQPTIPIVG IVAGLAVLAV VFTGTVVAAV MCRRKSSGGK GGSCSQAACS
 NSAQGSDESL IACKAX*   
>DL;IPD:MHC00193
IPD:MHC00193 Gogo-C*01:03 347 bases
 LLLSGALALT ETWAGSHSMR YFFTAVAPPG RGEPRFIAVG YVDDTQFVRF
 DSDAANTRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV NLRKLRGYYN
 QSEDGSHTFQ RMYGCDVGPD GRLQRGYDQL AYDGKDYIAL NEDLRSWTAA
 DTAAQITQRK WEAARWAERQ RAYLEGLCVE WLRRYLENGK ETLQRADPPK
 THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ DIELVETRPA
 GDGTFQKWAA MVVPSGEEQR YTCHVQHKGL PEPLTLRWEP SSQPTIPIVG
 IVAGLAVLAV VFTGTVVAAV MCRRKSSGGK GGSCSQAACS NSAQGSD*
>DL;IPD:MHC00194
IPD:MHC00194 Gogo-C*02:01 367 bases
 MRVMAPRTLI LPLSGALALT ETWAGSHSMR YFYTSVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV
 NLRKLRGYYN QSEDGSHTLQ SMYGCDLGPD GRLLRGYSQF AYDGKDYIAL
 NEDLRSWTAA DTAAQVTQRK WEAARVAEQE RAYLEGLCVE WLRRYLENGK
 ETLQRADPPK THVTHHPLSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGQEQR YTCHMQHEGL PEPLTLRWEP
 SSQPTIPIVG IVVGLAVLVV LAVLGAVVTA MMCRRKSSGG KGGSCSQAAC
 SNSAQGSDES LITCKAX*   
>DL;IPD:MHC00195
IPD:MHC00195 Gogo-C*02:02 367 bases
 MRVMAPRTLI LLLSGALALT ETWAGSHSMR YFYTSVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV
 NLRKLRGYYN QSEDGSHTLQ SMYGCDLGPD GRLLRGYSQF AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK LEAARAAEQQ RAYLEGLCVE SLRRYLENGK
 ETLQRAEPPK THVTHHPLSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGQEQR YTCHMQHEGL PEPLTLRWEP
 SSQPTIPIVG IVVGLAVLVV LAVLGAVVTA MMCRRKSSGG KGGSCSQAAC
 SNSAQGSDES LITCKAX*   
>DL;IPD:MHC00196
IPD:MHC00196 Gogo-C*02:03 367 bases
 MRVMAPRTLI LLLSGALALT ETWAGSHSMR YFYTSVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQK YKRQAQTDRV
 NLRKLRGYYN QSEDGSHTLQ SMYGCDLGPD GRLLRGYSQF AYDGKDYIAL
 NEDLRSWTAA DTAAQVTQRK WEAARVAEQE RAYLEGLCVE WLRRYLENGK
 ETLQRAEPPK THVTHHPLSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGQEQR YTCHMQHEGL PEPLTLRWEP
 SSQPTIPIVG IVVGLAVLVV LAVLGAVVTA MMCRRKSSGG KGGSCSQAAC
 SNSAQGSDES LITCKAX*   
>DL;IPD:MHC00197
IPD:MHC00197 Gogo-C*02:04 348 bases
 LLLSGALALT ETWAGSHSMR YFYTSVSRPG RGEPRFISVG YVDDTQFVRF
 DSDAASPRGE PRAPWVEQEG PEYWDRETQN YKRQAQTDRV NLRKLRGYYN
 QSEDGSHTLQ SMYGCDLGPD GRLLRGYSQF AYDGKDYIAL NEDLRSWTAA
 DTAAQITQRK LEAARAAEQQ RAYLEGLCVE SLRRYLENGK ETLQRAEPPK
 THVTHHPLSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ DTELVETRPA
 GDGTFQKWAA VVVPSGQEQR YTCHMQHEGL PEPLTLRWEP SSQPTIPIVG
 IVVGLAVLVV LAVLGAVVTA MMCRRKSSGG KGGSCSQAAC SNSAQGSD*
