>DL;IPD:MHC00198
IPD:MHC00198 Gogo-DMB*01:01:01 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL
 LTCWDPEENK MAPCEFGVLN SLANVLSQHL NQQDTLMQRL RNGLQNCATH
 TQPFWGSLTN RTRPPSVQVA KTTPFNTREP VMLACYVWGF YPAEVTITWR
 KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL ALTPSYGDTY TCVVEHIGAP
 EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW RRAGHSSYTP
 LPGSNYSEGW HIS*   
>DL;IPD:MHC00199
IPD:MHC00199 Gogo-DMB*01:01:02 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL
 LTCWDPEENK MAPCEFGVLN SLANVLSQHL NQQDTLMQRL RNGLQNCATH
 TQPFWGSLTN RTRPPSVQVA KTTPFNTREP VMLACYVWGF YPAEVTITWR
 KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL ALTPSYGDTY TCVVEHIGAP
 EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW RRAGHSSYTP
 LPGSNYSEGW HIS*   
>DL;IPD:MHC00200
IPD:MHC00200 Gogo-DMB*01:03 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL
 LTCWDPEENK MAPCEFGVLN SLANVLSQHL NQQDTLMQRL RNGLQNCATH
 TQPFWGSLTN RTRPPSVQVA KTTPFNTREP VMLACYVWGF YPAEVTITWR
 KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL ALTPSYGDTY TCVVEHIGAP
 EPILQDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW RRAGHSSYTP
 LPGSNYSEGW HIS*   
