>DL;IPD:MHC00236
IPD:MHC00236 Gogo-E*01:01:01 193 bases
 SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDNE
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE
 AGSHTLQWMH GCDLGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA
 AQISERKSND ACEAEHQRAY LEDTCVEWLR KYLEKGKETL LHL*
>DL;IPD:MHC00237
IPD:MHC00237 Gogo-E*01:01:02 193 bases
 SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDNE
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE
 AGSHTLQWMH GCDLGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA
 AQISERKSND ACEAEHQRAY LEDTCVEWLR KYLEKGKETL LHL*
