>DL;IPD:MHC00216
IPD:MHC00216 Gogo-DQB1*02:02 246 bases
 TACCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG
 TCTTGTGAGC AGAAACATCT ATAACCGAGA AGAGATCGTG CGCTTCGACA
 GCGACGTGGG GGAGTTCCGG GCGGTGACGC TGCTGGGGCT GCCTGCTGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGAGGAAAC GGGCGGCGGT
 GGACAGGGTG TGCAGACACA ACTACCAGTT GGAGCTCCGC ACGACC*
>DL;IPD:MHC00217
IPD:MHC00217 Gogo-DQB1*05:02 246 bases
 TACCAGTTTA AGGGCCTGTG CTACTTCACC AACGGGACGG AGCGCGTGCG
 GGCTGTGACC AGACACATCT ATAACCGAGA GGAGTACGTG CGCTTCGACA
 GCGACGTGGG GGTGTACCGG GCAGTGACGC CGCAGGGGCG GCCTGCTGCC
 GACTACTGGA ACAGCCAGAA GGAAGTCCTG GAGGAGACCC GGGCGTCGGT
 GGACAGGGTG TGCAGACACA ACTACGAGTT GGCGTACCGC GGGATC*
>DL;IPD:MHC00218
IPD:MHC00218 Gogo-DQB1*19:03 246 bases
 TACCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACGG AGCGCGTGCG
 TGTTGTGACG AGATACATCT ATAACCGAGA GGAGTACGCG CGCTTCGACA
 GCGACGTGGG GGTGTATCAG GCGGTGACGC CGCTGGGGCC GCCTGATGCC
 GACTACTGGA ACAGCCAGAA GGAAGTCCTG GAGGAGACCC GGGCGTCGGT
 GGACAGGGTG TGCAGACACA ACTACCAGTT GGAGCTCCTC ACGACC*
>DL;IPD:MHC00219
IPD:MHC00219 Gogo-DQB1*19:04 171 bases
 ACGGAGCGCG TGCGTCTTGT GACGAGATAC ATCTATAACC GAGAGGAGTA
 CGCGCGCTTC GACAGCGACG TGGGGGTGTA TCGGGCGGTG ACGCCGCTGG
 GGCCGCCTGA TGCCGACTAC TGGAACAGCC AGAAGGAAGT CCTGGAGGAG
 ACCCGGGCGT CGGTGGACAG G*  
>DL;IPD:MHC00220
IPD:MHC00220 Gogo-DQB2*01:01 243 bases
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG
 GGGTGTGGCC AGACACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA
 GCGACGTTGG GGAGTTCCAG GCGGTGACCG AGCTGGGGCG GAGTATCGAG
 GACTGGAACA ACTATAAGGA CTTCTTGGAG CAGGAGCGGG CCGCGGTGGA
 CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG ACC*
>DL;IPD:MHC00221
IPD:MHC00221 Gogo-DQB2*01:03 168 bases
 ACAGAGCGCG TGCGGGGTGT GGCCAGATAC ATCTATAACC GCGAGGAGTA
 CGGGCGCTTC GACAGCGACG TTGGGGAGTT CCAGGCGGTG ACCGAGCTGG
 GGCGGAGTAT CGAGGACTGG AACAACTACA AGGACTTCTT GGAGCAGGAG
 CGGGCCGCGG TGGACAAG*   
