>DL;IPD:MHC00243
IPD:MHC00243 Hyla-B*01 1065 bases
 CTCCTCCTGC TGCTCTCGGC GGCCCTGGCC CTGACCGAGA CGTGGGCGGG
 CTCCCACTCC ATGAGGTATT TCTACACCTC CGTGTCCCGG CCCGGCCGCG
 GGGAGCCCCG CTTCATCACC GTGGGCTACG TGGACGACAC CCAGTTCGTG
 CGGTTCGACA GCGACGCCGC GAGTCCGAGG ATGGAGCCGC GGGCGCCGTG
 GATAGAGCAG GAGGGGCCGG AGTATTGGGA CCAGCAGACA CAGATCTCCA
 AGACCAACGC ACAGACTGAC CGAGAGAACC TGCGGATCGC GCTCCGCTAC
 TACAACCAGA GCGAGGACGG GTCTCACACC CTCCAGACGA TGTATGGCTG
 CGACCTGGGG CCCGACGGGC GCCTCCTCCG CGGGTATCGC CAGTACGCCT
 ACGACGGCAA GGATTACATC GCCCTGAACG AGGACCTGAG CTCCTGGACC
 GCCGCGGACA CGGCGGCTCA GATCACCCAG CGCAAGTGGG AGGCGGCCCA
 TGAGGCGGAG CAGATGAGAG CCTACCTGGA GGGCCGGTGC CTGGAGTGGC
 TCCGCAGATA CCTGGAGAAC GGGAAGGAGA CTCTGCAGCG CGCGGAGCCC
 CCAGAGACAC ACGTGACTCA CCACCCCATC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG GGAGGACCAA ACTCAGGACA CTGAGCTTGT GGAGACCAGG
 CCAGCAGGAG ACAGAACCTT CCAGAAGTGG GTAGCTGTGG TGGTGCCTTC
 TGGAGAAGAG CAGAGATACA CATGCCATGT GCAGCACGAG GGGCTGCCGG
 AGCCCCTCAC CCTGAGATGG GAGCCATCTT CCCAGTCCAC CATCCCCATC
 GTGGGCATTG TTGCTGGCCT GGCTGTCCTA GCAGTTGTGG TCACCGGAGC
 TGTGGTTGCT GCTGTGATGT GGAGGAGGAA GAGCTTAGGT GGAAAAGGAG
 GGAGCTACTC TAAGGCTGCG TCCAGCGACA GTGCCCAGGG CTCTGATGTG
 TCTCTCACGG CTTGA*   
