>DL;IPD:MHC00241
IPD:MHC00241 Hyla-A*01 358 bases
 LLLLLSGTLA LTQTWAGSHS MRYFSTTVSR PGRGEPRYLE VGYVDDTQFV
 RFDSDSASPR MEPRASWVEQ EGPEYWDQNT RNSKARAQLD RVDLGTLRGY
 YNQSEAGSHT IQLMYGCYVG PDGRFLRGYR QDAYDGKDYI SLNEDLRSWT
 AADVAAQITK RKWEAAGVAE QYRAYLEGTC VEWLHRYLEN GKEILQRTDP
 PKTHMTHHPI SDREATLRCW ALGYYPAEIM LTWQRDGEDQ TQDTELVETR
 PAGDGTFQKW AAVVVPSGKE QRYTCHVQHE GLPEPLTLRW EPSSQTTIPI
 VGIIAGLVLL GAVITGAVVA AVMWRRKSSD RKGGSYSQAA SSDSAQGSDV
 SLTACKVX*    
>DL;IPD:MHC00242
IPD:MHC00242 Hyla-A*02 358 bases
 LLLLLSGTLA LTQTWAGSHS MRYFSTTVSR PGHGEPRYLE VGYVDDTQFV
 RFDSDSASPR MEPRASWVEQ EGPEYWDRNT RNSKARAQLD RVDLGTLRRY
 YNQSEAGSHT IQIMYGCDMG PDGRFLRGYR QDAYDGKDYI SLNEDLRSWT
 AADMAAQITK RKWEAAGVAE QDRAYLEGTC MEWLRRHLEN GKETLQRADP
 PKTHMTHHPV SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDTELVETR
 PAGDGTFQKW AAVVVPSGKE QRYTCHVQHE GLPEPLTLRW EPSSQPTIPI
 VGIIAGLVLL GAVITGAVVA AVMWRRKSSD RKGGSYSQAA SSDSAQGSDV
 SLTACKVX*    
