>DL;IPD:MHC00254
IPD:MHC00254 Lero-G*03:01 327 bases
 LLLLLSGALT LTETRAGSHS MRYFDTTVSR PGRGEPRFIS VGYVDDTQFV
 RFDSDAASPR MEPRAPWVER EGPEYWEEVT RRTKAHAQTF RVNLRTLRGY
 YNQSDAGSHT IQWTYGCDMG PDGRLLRGYN QFAYDGKDYI ALNEDLRSWT
 AADVGAQITQ RKWEAANAAE PMRAYLEGEC LEWLRRYLEN GKETLQRAEP
 PKTDVTHHPV SDHEATLRCW ALDFYPAEIT LTWQRDGEDQ TQDMELLETR
 PMGNRTFQKW AAVVVPSGEE QRYTCHVQHE GLPEPLTLRW EPPSSQLTIL
 IVGIVAGVAI LGVVVAAVVW KKKSSDK*  
>DL;IPD:MHC00255
IPD:MHC00255 Lero-G*03:02 327 bases
 LLLLLSGALA LTQTRAGSHS MRYFYTTVSR PGRGEPRFIS VGYVDDTQFV
 RFDSDAASPR MEPRAPWVER EGPEYWEEQT RRTKAHAQNF RVNLRTLRGY
 YNQSDAGSHT IQWTFGCDLG PDGRLLRGYN QFAYDGKDYI ALNEDLRSWT
 TADVAAQITQ RKWEAANAAE PMRAYLEGEC LEWLRRYLEN GKETLQRAEP
 PKTDVTHHPV SDQEATLRCW ALDFYPAEIT LTWQRDGEDQ TQDMELVETR
 PTGNRTFQKW AAVVVPSGEK QRYTCHVQHE GLPEPLTLRW EPPSSQPTIL
 IVGIVAGVAI LGVVVTAVVW KKKSSDK*  
