>DL;IPD:MHC00254
IPD:MHC00254 Lero-G*03:01 981 bases
 CTCCTCCTGC TGCTCTCGGG GGCCCTGACC CTCACCGAGA CCCGGGCGGG
 CTCCCACTCC ATGAGGTATT TCGACACCAC CGTGTCGCGG CCCGGTCGCG
 GGGAGCCCCG CTTCATCTCC GTGGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCCGC GAGTCCGAGG ATGGAGCCGC GGGCGCCGTG
 GGTGGAGCGG GAGGGGCCGG AGTATTGGGA GGAGGTGACA CGGAGAACCA
 AGGCCCACGC ACAGACTTTC CGAGTGAACC TGCGGACCCT GCGCGGCTAC
 TACAACCAGA GCGACGCCGG GTCTCACACC ATCCAGTGGA CGTACGGCTG
 CGACATGGGG CCGGACGGGC GCCTCCTCCG CGGTTATAAC CAGTTTGCCT
 ACGATGGCAA GGACTACATC GCCCTGAACG AGGACCTGCG CTCCTGGACG
 GCCGCGGACG TGGGGGCTCA GATCACCCAG CGCAAGTGGG AGGCGGCCAA
 TGCGGCTGAG CCGATGAGAG CCTACCTGGA GGGCGAGTGC CTGGAGTGGC
 TCCGCAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CGCAGAGCCC
 CCGAAGACAG ACGTGACCCA CCACCCCGTC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTGGACT TCTACCCTGC GGAGATCACA TTGACCTGGC
 AGCGGGATGG GGAGGACCAG ACCCAGGACA TGGAGCTCTT AGAGACCAGG
 CCCATGGGGA ATAGAACCTT CCAGAAGTGG GCGGCTGTGG TGGTGCCTTC
 TGGAGAGGAG CAGAGATACA CATGCCATGT GCAGCATGAG GGGCTGCCCG
 AGCCCCTCAC CCTCAGATGG GAGCCGCCGT CTTCCCAGCT CACCATCCTC
 ATCGTGGGCA TCGTTGCTGG TGTGGCTATC CTTGGAGTTG TGGTCGCTGC
 TGTGGTGTGG AAGAAGAAGA GCTCAGATAA A* 
>DL;IPD:MHC00255
IPD:MHC00255 Lero-G*03:02 981 bases
 CTCCTCCTGC TGCTCTCAGG GGCCCTCGCT CTGACCCAGA CCCGGGCGGG
 CTCCCACTCC ATGAGGTATT TCTACACCAC CGTGTCGCGG CCCGGCCGCG
 GGGAGCCCCG CTTCATCTCC GTGGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCCGC GAGTCCGAGG ATGGAGCCGC GGGCGCCGTG
 GGTGGAGCGG GAGGGGCCGG AGTATTGGGA GGAGCAGACA CGGAGAACCA
 AGGCCCACGC ACAGAATTTC CGAGTGAACC TGCGGACCCT GCGCGGCTAC
 TACAACCAGA GCGACGCCGG GTCTCACACC ATCCAGTGGA CGTTCGGCTG
 CGACCTGGGG CCGGACGGGC GCCTCCTCCG CGGGTATAAC CAGTTTGCCT
 ACGACGGCAA GGACTACATC GCCCTGAACG AGGACCTGCG CTCCTGGACG
 ACCGCGGACG TGGCGGCTCA GATCACCCAG CGCAAGTGGG AGGCGGCCAA
 TGCGGCTGAG CCGATGAGAG CCTACCTGGA GGGCGAGTGC CTGGAGTGGC
 TCCGCAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CGCGGAGCCC
 CCGAAGACAG ACGTGACCCA CCACCCCGTC TCTGACCAGG AGGCCACCTT
 GAGGTGCTGG GCCCTGGACT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG GGAGGACCAG ACCCAGGACA TGGAGCTTGT AGAGACCAGG
 CCCACGGGGA ATAGAACCTT CCAGAAGTGG GCGGCTGTGG TGGTGCCTTC
 TGGAGAGAAG CAGAGATACA CCTGCCATGT GCAGCACGAA GGGCTGCCCG
 AGCCCCTCAC CCTGAGATGG GAGCCGCCGT CTTCCCAGCC CACCATCCTC
 ATCGTGGGCA TCGTTGCTGG CGTGGCTATC CTTGGAGTTG TGGTCACTGC
 TGTGGTGTGG AAGAAGAAGA GCTCAGATAA A* 
