>DL;IPD:MHC00256
IPD:MHC00256 Loat-DQA1*01:01 185 bases
 ACTTACGGTC TCTCTGGCCA GTACACCCAT GAATTTGATG GAGACGAGCA
 GTTCTACGTG GACCTGGAGA GGAAGGAGAC GGCCTGGCGA TGGCCTGAAT
 TAAGCAAATT TGGAGGTTTT GACCCGCATG CACTGAGAAA CTTGGCTGTG
 TTAAAACACA ACTTGAACAT CGTGACTAAA CGCTA* 
