>DL;IPD:MHC00257
IPD:MHC00257 Maar-DPA1*02:01 189 bases
 TTTGTACAGA CACATAGACC AACAGGGGAG TATATGTTTG AGTTTGATGA
 AGATGAGCAG TTCTATGTGG ATCTGGACAA GAAGGAGACC GTCTGGCATC
 TGGAGGAGTT TGGCCGAGCC TTTTCCTTTG AGGCTCAGGG CGGGCTGGCT
 AACATTGCTA TATTGAACAA CAACTTGAAT ATCACGATC* 
