>DL;IPD:MHC00269
IPD:MHC00269 Maar-I*01:01 1089 bases
 ATGCGGGTCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCGGCA
 CCACAGTGTC CCGGCCCGGC CGCGGGGAGC CGCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCGGAGTATT
 GGGAAGAGGA GACACGGATC GCCAAGGCCC GCGCACAGAC TGAGCGAGGG
 AACCTGCGGA CCGCGCTCCG CTACTACAAC CAGAGCGAGG GGGGGTCTCA
 CACCCTCCAG AAGATGTGTG GCTGCGACCT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGTCC GCCTACGACG GCAGGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCTGCG GGTGAGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGAGGC AGAGCAGCGG AGAGCCTACC
 TGGAGGGCCG GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAAGGGGAAG
 GAGACGCTGC AGCGCGCGGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA GCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA ACTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACGTGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCATGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCAGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00270
IPD:MHC00270 Maar-I*01:02 496 bases
 GCACCACAGT GTCCCGGCCC GGCCGCGGGG AGCCCCGCTT CATCGCCGTG
 GGCTACGTGG ACGACACGCA GTTCGTGCGG TTCGACAGCG ACGCCGCGAG
 TCCGAGGATG GAGCCGCGGG CGCCGTGGAT GGAGCAGGAG GGGCCGGAGT
 ATTGGGAAGA GGAGACACGG ATCGCCAAGG CCCGCGCACA GACTGAGCGA
 GGGAACCTGC GGACCGCGCT CCGCTACTAC AACCAGAGCG AGGCGGGGTC
 TCACACCCTC CAGAAGATGT GTGGCTGCGA CCTGGGGCCG GACGGGCGCC
 TCCTCCGCGG GTATTACCAG TCCGCCTACG ACGGCAGGGA TTACATCGCC
 CTGAACGAGG ACCTGCGCTC CTGGACCGCT GCGGGTGAGG CGGCTCAGAA
 CACCCAGCGC AAGTGGGAGG CGGCCGGTGA GGCAGAGCAG CGGAGAGCCT
 ACCTGGAGGG CCGGTGCGTG GAGTGGCTCC GCAGATACCT GGAGAA*
>DL;IPD:MHC00271
IPD:MHC00271 Maar-I*01:03 496 bases
 GCACCACAGT GTCCCGGCCC GGCCGCGGGG AGCCGCGCTT CATCGCCGTG
 GGCTACGTGG ACGACACGCA GTTCGTGCGG TTCGACAGCG ACGCCGCGAG
 TCCGAGGATG GAGCCGCGGG CGCCGTGGAT GGAGCAGGAG GGGCCGGAGT
 ATTGGGAAGA GGAGACACGG ATCGCCAAGG CCCGCGCACA GACTGAGCGA
 GGGAACCTGC GGACCGCGCT CCGCTACTAC AACCAGAGCG AGGGGGGGTC
 TCACACCCTC CAGAAGATGT GTGGCTGCGA CCTGGGGCCG GACGGGCGCC
 TCCTCCGCGG GTATTACCAG TCCGCCTACG ACGGCAGGGA TTACATCGCC
 CTGAACGAGG ACCTGCGCTC CTGGACCGCT GCGGGTGAGG CGGCTCAGAA
 CACCCAGCGC AAGTGGGAGG CGGCCGGTGA GGCAGAGCAG CGGAGAGCCT
 ACCTGGAGGG CCGGTGCGTG GAGTGGCTCC GCAGATACCT GGAGAA*
