>DL;IPD:MHC00269
IPD:MHC00269 Maar-I*01:01 363 bases
 MRVMAPRTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00270
IPD:MHC00270 Maar-I*01:02 164 bases
 TTVSRPGRGE PRFIAVGYVD DTQFVRFDSD AASPRMEPRA PWMEQEGPEY
 WEEETRIAKA RAQTERGNLR TALRYYNQSE AGSHTLQKMC GCDLGPDGRL
 LRGYYQSAYD GRDYIALNED LRSWTAAGEA AQNTQRKWEA AGEAEQRRAY
 LEGRCVEWLR RYLE*   
>DL;IPD:MHC00271
IPD:MHC00271 Maar-I*01:03 164 bases
 TTVSRPGRGE PRFIAVGYVD DTQFVRFDSD AASPRMEPRA PWMEQEGPEY
 WEEETRIAKA RAQTERGNLR TALRYYNQSE GGSHTLQKMC GCDLGPDGRL
 LRGYYQSAYD GRDYIALNED LRSWTAAGEA AQNTQRKWEA AGEAEQRRAY
 LEGRCVEWLR RYLE*   
