>DL;IPD:MHC00353
IPD:MHC00353 Mafa-I*01:01:01 363 bases
 MQIMAPRTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC02486
IPD:MHC02486 Mafa-I*01:02 363 bases
 MRVMAPRTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGPVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC02488
IPD:MHC02488 Mafa-I*01:03 363 bases
 MRVMAPGTLL LLLSGTLALT ETWAGSHSLR YFGTTVSQPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD RRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAHNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC02489
IPD:MHC02489 Mafa-I*01:04 363 bases
 MRVMAPGTLL LLLSGALALT ETWAGSHSLR YFGTTVSQPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC02490
IPD:MHC02490 Mafa-I*01:05 363 bases
 MRVMAPGTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GVAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC02491
IPD:MHC02491 Mafa-I*01:06 363 bases
 MRVMAPGTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEAGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC02492
IPD:MHC02492 Mafa-I*01:07 363 bases
 MRVMAPGTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPKME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEAGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQW RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEPTLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC02493
IPD:MHC02493 Mafa-I*01:08 363 bases
 MRVMAPGTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLWTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC02494
IPD:MHC02494 Mafa-I*01:09 363 bases
 MRVMAPGTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLWTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC02496
IPD:MHC02496 Mafa-I*01:10 363 bases
 MRVMAPGTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWES
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC02054
IPD:MHC02054 Mafa-I*01:11 363 bases
 MRVMAPRTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC02052
IPD:MHC02052 Mafa-I*01:12:01 363 bases
 MRVMAPGTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIVVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEQTRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC02155
IPD:MHC02155 Mafa-I*01:12:02 363 bases
 MRVMAPGTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIVVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEQTRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC02053
IPD:MHC02053 Mafa-I*01:13:01 363 bases
 MRVMAPGTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIRIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC02602
IPD:MHC02602 Mafa-I*01:13:02 352 bases
 LLSGALALTE TWAGSHSLRY FGTTVSRPGR GEPRFIAVGY VDDTQFVRFD
 SDAESPRMEP RAPWMEQEGP EYWEEETRIA KARAQTERGN LRTALRYYNQ
 SEGGSHTLQK MCGCDLGPDG RLLRGYYQSA YDGRDYIALN EDLRSWTAAG
 EAAQNTQRKW EAAGEAEQRR AYLEGRCVEW LRRYLEKGKE TLQRADPPKT
 HVTHHPVSDH EATLRCWALG FYPAEITLTW QRDGEEQTQD TELVETRPGG
 DGNFQKWAAV VVPSGEEQRY TCHVQHEGLP EPLTLRWEPS SQSTIRIMGI
 VAGLAVLAVV VTGAVVAAVM WRRKSSGGKG GSYSQAASSN SAQGSDVSLT
 AX*    
>DL;IPD:MHC02156
IPD:MHC02156 Mafa-I*01:14 363 bases
 MRVMAPGTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC02600
IPD:MHC02600 Mafa-I*01:15 352 bases
 LLSGALALTE TWAGSHSLRY FGTTVSRPGR GEPRFIAVGY VDDTQFVRFD
 SDAESPRMEP RAPWMEQEGP EYWEEETRIA KARAQTERGN LRTALRYYNQ
 SEGGSHTLQK MCGCDLGPDG RLLRGYYQSA YDGRDYIALN EDLRSWTAAG
 EAAQNTQRKW EAAGEAEQRR AYLEGRCVEW LRRYLEKGKE TLQRADPPKT
 HVTHHPVSDH EATLRCWALG FYPAEITLTW QRDGEDQTQD TELVETRPGG
 DGNFQKWAAV VVPSGEEQRY TCHVQHEGLP EPLTLRWEPS SQSTIPIMGI
 VAGLAVLAVV VTGAVVAAVM WRRKSSGGKG GSYSQAASSN SAQGSDVSLT
 AX*    
>DL;IPD:MHC02601
IPD:MHC02601 Mafa-I*01:16 352 bases
 LLSGALALTQ TWAGSHSLRY FGTTVSRPGR GEPRFIAVGY VDDTQFVRFD
 SDAESPRMEP RAPWMEQEGP EYWEEETRIA KARAQTERGN LRTALRYYNQ
 SEGGSHTLQK MCGCDLGPDG RLLRGYYQSA YDGRDYIALN EDLRSWTAAG
 EAAQNTQRKW EAAGEAEQRR AYLEGRCVEW LRRYLEKGKE TLQRADPPKT
 HVTHHPVSDH EATLRCWALG FYPAEITLTW QRDGEEQTQD TELVETRPGG
 DGNFQKWAAV VVPSGEEQRY TCHVQHEGLP EPLTLRWEPS SQSTIRIMGI
 VAGLAVLAVV VTGAVLAAVM WRRKSSGGKG GSYSQAASSN SAQGSDVSLT
 AX*    
>DL;IPD:MHC02603
IPD:MHC02603 Mafa-I*01:17 352 bases
 LLSGALALTE TWAGSHSLRY FGTTVSRPGR GEPRFIAVGY VDDTQFVRFD
 SDAESPRMEP RAPWMEQEGP EYWEEETRIA KARAQTERGN LRTALRYYNQ
 SEGGSHTLQK MCGCDLGPDG RLLRGYYQSA YDGRDYIALN EDLRSWTAAG
 EAAQNTQRKW EAAGEAEQRR AYLEGRCVEW LRRYLEKGKE TLQRADPPKT
 HVTHHPISDH EATLRCWALG FYPAEITLTW QRDGEDQTQD TELVETRPGG
 DGNFQKWAAV VVPSGEEQRY TCHVQHEGLP EPLTLRWEPS SQSTIPIMGI
 VAGLAVLAVV VTGPVVAAVM WRRKSSGGKG GSYSQAASSN SAQGSDVSLT
 AX*    
>DL;IPD:MHC02604
IPD:MHC02604 Mafa-I*01:18 352 bases
 LLSGALALTE TWAGSHSLRY FGTTVSRPGR GEPRFIAVGY VDDTQFVRFD
 SDAESPRMEP RAPWMEQEGP EYWEEETRIA KARAQTERGN LRTALRYYNQ
 SEAGSHTLQK MCGCDLGPDG RLLRGYYQSA YDGRDYIALN EDLRSWTAAG
 EAAQNTQRKW EAAGEAEQRR AYLEGRCVEW LRRYLEKGKE TLQRADPPKT
 HVTHHPVSDH EATLRCWALG FYPAEITLTW QRDGEEQTQD TELVETRPGG
 DGNFQKWAAV VVPSGEEQRY TCHVQHEGLP EPLTLRWEPS SQSTIPIMGI
 VAGLAVLAVV VTGAVVAAVM WRRKSSGGKG GSYSQAASSN SAQGSDVSLT
 AX*    
>DL;IPD:MHC02605
IPD:MHC02605 Mafa-I*01:19 352 bases
 LLSGALALTE TRAGSHSLRY FGTTVSRPGR GEPRFIAVGY VDDTQFVRFD
 SDAESPRMEP RAPWMEQEGP EYWEEETRIA KARAQTERGN LRTALRYYNQ
 SEGGSHTLQK MCGCDLGPDG RLLRGYYQSA YDGRDYIALN EDLRSWTAAG
 EAAQNTQRKW EAAGEAEQRR AYLEGRCVEW LRRYLEKGKE TLQRADPPKT
 HVTHHPVSDH EATLRCWALG FYPAEITLTW QRDGEEQTQD TELVETRPGG
 DGNFQKWAAV VVPSGEEQRY TCHVQHEGLP EPLTLRWEPS SQSTIPIMGI
 VAGLAVLAVV VTGAVVAAVM WRRKSSGGKG GSYSQAASSN SAQGSDVSLT
 AX*    
>DL;IPD:MHC02606
IPD:MHC02606 Mafa-I*01:20 346 bases
 LLSGALALTQ TWAGSHSLRY FGTTVSRPGR GEPRFIAVGY VDDTQFVRFD
 SDAESPRMEP RAPWMEQEGP EYWEEETRIA KARAQTERGN LRTALRYYNQ
 SEGGSHTLQK MCGCDLGPDG RLLRGYYQSA YDGRDYIALN EDLRSWTAAG
 EAAQNTQRKW EAAGEAEQRR AYLEGRCVEW LRRYLEKGKE TLQRADPPKT
 HMTHHPISDH EATLRCWALG FYPAEITLTW QRDGEEQTQD TELVETRPGG
 DGNFQKWAAV VVPSGEEQRY TCHVQHEGLP EPLTLRWEPS SQSTIPIMGI
 VAGLAVLAVV VTGAVVAAVM WRRKSSGGKG GSYSQAAVQQ QCPGLX*
>DL;IPD:MHC03381
IPD:MHC03381 Mafa-I*01:21 363 bases
 MRVMAPGTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWES
 SSQSTTPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC03819
IPD:MHC03819 Mafa-I*01:22 363 bases
 MQIMAPRTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRAVPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC02487
IPD:MHC02487 Mafa-I*02:01 363 bases
 MRVMAPGTLL LLLSGALALT ETWAGSHSLR YFGTTVSQPG RGEPRFIAVG
 YNDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTDRG
 TLRTLLRYYN QSEGGSHTLQ KMYGCDLGPD GRLLRGYYQD AYDGRDYIAL
 NEDLRSWTAA DEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGPVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC02497
IPD:MHC02497 Mafa-I*03:01:01 357 bases
 MRVMAPGTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKGHAQTDRA
 DLGTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGKDYITL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAAVQ
 QQCPGLX*    
>DL;IPD:MHC02607
IPD:MHC02607 Mafa-I*03:01:02 346 bases
 LLSGALALTE TWAGSHSLRY FGTTVSRPGR GEPRFIAVGY VDDTQFVRFD
 SDAESPRMEP RAPWMEQEGP EYWEEETRIA KGHAQTDRAD LGTALRYYNQ
 SEGGSHTLQK MCGCDLGPDG RLLRGYYQSA YDGKDYITLN EDLRSWTAAG
 EAAQNTQRKW EAAGEAEQRR AYLEGRCVEW LRRYLEKGKE TLQRADPPKT
 HMTHHPVSDH EATLRCWALG FYPAEITLTW QRDGEDQTQD TELVETRPGG
 DGNFQKWAAV VVPSGEEQRY TCHVQHEGLP EPLTLRWEPS SQSTIPIMGI
 VAGLAVLAVV VTGAVVAAVM WRRKSSGGKG GSYSQAAVQQ QCPGLX*
>DL;IPD:MHC02669
IPD:MHC02669 Mafa-I*04:01 363 bases
 MRVMAPGTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERE
 DLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GKAAQNTQRK WEAAGVAEQR RAYLEGLCLE SLRRYLENGK
 ETAQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTEFVETRPG GDGTFQKWGA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIAIVG IVVGLAVLAI VVTGAVVAAV MWRRKSSGGK GGSYSQAASN
 DSAQGSDVSL TAX*   
