>DL;IPD:MHC00275
IPD:MHC00275 Mafa-DQA1*01:01 188 bases
 ACTTACGGGC TTTCTGGCCA GTACACCCAC GAATTTGATG GAGACGAGCA
 GTTCTACGTG GACCTGGAGA GGAAGGAGAC GGCATGGCGA TGGCCTGAGT
 TAAGCAAATT TGGAGGTTTT GACCCGCAGG GTGCACTGAG AAACTTGGCT
 GTGTCAAAAC ACAACTTGAA TATCATGACT AAACGCTA* 
>DL;IPD:MHC01175
IPD:MHC01175 Mafa-DQA1*01:02 768 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTCGTTC TGACCGCTGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT CGCTGACCAC GTTGCCTCTT
 GCGGTGTAAA CTTGTACCAG ACTTACGGTC TTTCTGGCCA GTACACCCAC
 GAATTTGACG GAGACGAGCA GTTCTACGTG AACCTGGAGA GGAAGGAGAC
 GGCATGGCGA TGGCCTGAGT TAAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGTCAAAAC ACAACTTGAA TATCATGACT
 AAACGCTACA ACTCTACCGC TGCTATCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA TGCTGGGTCA GCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCGCTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAGG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG
 TGGGCACTGT CTTCATCATT CAAGGCCTAC GTTCAGTTGG TGCTTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC01177
IPD:MHC01177 Mafa-DQA1*01:03:02 768 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTCGTTC TGACCGCTGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT CGCTGACCAC GTTGCCTCTT
 GCGGTGTAAA CTTGTACCAG ACTTACGGTC TTTCTGGCCA GTACACCCAC
 GAATTTGACG GAGACGAGCA GTTCTACGTG GACCTGGAGA GGAAGGAGAC
 GGCATGGCGA TGGCCTGAGT TAAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGTCAAAAC ACAACTTGAA TATCATGACT
 AAACGCTACA ACTCTACCGC TGCTATCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CGCTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCACTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAGG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG
 TGGGCACTGT CTTCATCATT CAAGGCCTAC GTTCAGTTGG TGCTTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC04700
IPD:MHC04700 Mafa-DQA1*01:03:03 687 bases
 GGAGGTGAAG ACATAGTGGC TGACCACGTT GCCTCTTGCG GTGTAAACTT
 GTACCAGACT TACGGTCTTT CTGGCCAGTA CACCCACGAA TTTGACGGAG
 ACGAGCAGTT CTACGTGGAC CTGGAGAGGA AGGAGACGGC ATGGCGATGG
 CCTGAGTTAA GCAAATTTGG AGGTTTTGAC CCGCAGGGTG CACTGAGAAA
 CTTGGCTGTG TCAAAACACA ACTTGAATAT CATGACTAAA CGCTACAACT
 CTACCGCTGC TATCAATGAG GTTCCTGAGG TCACAGTGTT TTCCAAGTCT
 CCCGTGACGC TGGGTCACCC CAACACCCTC ATCTGTCTTG TGGACAACAT
 CTTTCCTCCT GTGGTGAACA TCACATGGTT GAGCAATGGG CACTCAGTCA
 CAGAAGGGGT TTCTGAGACC AGCTTCCTCT CCAAGAGTGA TCATTCCTTC
 TTCAAGATCA GTTACCTCAC CTTCCTCCCT TCTGCTGATG AGATTTATGA
 CTGCAGGGTG GAGCACTGGG GCCTGGACGA GCCTCTTCTG AAACACTGGG
 AGCCTGAGAT TCCAGCGCCC ATGTCAGAGC TCACAGAGAC TGTGGTCTGC
 GCCCTGGGGT TGTCTGTGGG CCTCGTGGGC ATTGTGGTGG GCACTGTCTT
 CATCATTCAA GGCCTACGTT CAGTTGGTGC CTCCAGA* 
>DL;IPD:MHC01178
IPD:MHC01178 Mafa-DQA1*01:04 768 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTCGCCC TGACCACCGT
 GATGAGCCCC TGTGGAGGTG AAGACATTGT GGCTGACCAC GTTGCCTCTT
 GCGGTGTAAA CTTGTACCAG TCTTACGGTC CCTCTGGCCA GTACACCCAT
 GAATTTGACG GAGACGAGCA GTTCTACGTG GACCTGGGGA GGAAGGAGAC
 GGCCTGGCGA TGGCCTGAGT TAAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT ACAGTAAAAT ACAACTTGAA CATCATGACT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCCG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CACTGGGTCA GCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCGCTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCATCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAGG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCGGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG
 TGGGCACTGT CTTCATCATT CAAGGCCTAC GTTCAGTTGG TGCTTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC01179
IPD:MHC01179 Mafa-DQA1*01:05 226 bases
 CTGACCACGT TGCCTCTTGC GGTGTAAACT TGTACCAGTC TTACGGTACC
 TCTGGCCAGT ACAACCATGA ATTTGATGGA GACGAGCAGT TCTACGTGGA
 CCTGGGGAGG AAGGAGACGG CCTGGCGATG GCCTGAGTTA AGCAAATTTG
 AAGGTTTTGA CCCGCAGGGT GCACTGAGAA ACTTGGCTGC GGCAAAACAC
 AACTTGAACA TCTTGACTAA ACGCTA*  
>DL;IPD:MHC01620
IPD:MHC01620 Mafa-DQA1*01:06 768 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTCGTTC TGACCGCTGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT GGCTGACCAC GTTGCCTCTT
 GCGGTGTAAA CTTGTACCAG TCTTACGGTA CCTCTGGCCA GTACAACCAT
 GAATTTGATG GAGACGAGCA GTTCTACGTG GACCTGGGGA GGAAGGAGAC
 GGCCTGGCGA TGGCCTGAGT TAAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GCGGCAAAAC ACAACTTGAA CATCTTGACT
 AAACGCTACA ACTCCACCGC TGCTACCAAT GAGGTTCCCG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CGCTGGGTCA GCCCAATACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCACTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTTTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAGG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCGGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG
 TGGGCACTGT CTTCATCATT CAAGGCCTAC GTTCAGTTGG TGCTTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC01621
IPD:MHC01621 Mafa-DQA1*01:07:01 768 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTCGTTC TGACCGCTGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT CGCTGACCAT GTTGCCTCTT
 GCGGTGTAAA CTTGTACCAG ACTTACGGTC TCTCTGGCCA GTTCACCCAT
 GAATTTGATG GAGATGAGCA GTTCTACGTG GACCTGAGGA GGAAGGAGAC
 AGCCTGGCGA TGGCCTGAGT TAAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGTTAAAAC ACAACTTGAA CATCGTGACT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCCG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CACTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCGCTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAGG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCGGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG
 TGGGCACTGT CTTCATCATT CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC04708
IPD:MHC04708 Mafa-DQA1*01:07:02 687 bases
 GGAGGTGAAG ACATAGTGGC TGACCATGTT GCCTCTTGCG GTGTAAACTT
 GTACCAGACT TACGGTCTCT CTGGCCAGTT CACCCATGAA TTTGATGGAG
 ATGAGCAGTT CTACGTGGAC CTGAGGAGGA AGGAGACAGC CTGGCGATGG
 CCTGAGTTAA GCAAATTTGG AGGTTTTGAC CCGCAGGGTG CACTGAGAAA
 CTTGGCTGTG TTAAAACACA ACTTGAACAT CGTGACTAAA CGCTACAACT
 CTACCGCTGC TACCAATGAG GTTCCCGAGG TCACAGTGTT TTCCAAGTCT
 CCCGTGACAC TGGGTCACCC CAACACCCTC ATCTGTCTTG TGGACAACAT
 CTTTCCTCCT GTGGTGAACA TCACATGGTT GAGCAATGGG CGCTCAGTCA
 CAGAAGGGGT TTCTGAGACC AGCTTCCTCT CCAAGAGTGA TCATTCCTTC
 TTCAAGATCA GTTACCTCAC CTTCCTCCCT TCTGCTGATG AGATTTATGA
 CTGCAGGGTG GAGCACTGGG GCCTGGACGA GCCTCTTCTG AAACACTGGG
 AGCCGGAGAT TCCAGCGCCC ATGTCAGAGC TCACAGAGAC TGTGGTCTGC
 GCCCTGGGGT TGTCTGTGGG CCTCGTGGGC ATTGTGGTGG GCACTGTCTT
 CATCATTCAA GGCCTGCGTT CAGTTGGTGC CTCCAGA* 
>DL;IPD:MHC01622
IPD:MHC01622 Mafa-DQA1*01:08:01 768 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTCGCCC TGACCACCGT
 GATAAGCCCC TGTGGAGGTG AAGACATTGT GGCTGACCAC GTTGCCTCTT
 GCGGTGTAAA CGTGTACCAG TCTTACGGTC CCTCTGGCCA GTACACCCAT
 GAATTTGATG GGGACGAGCA GTTCTACGTG GACCTGGGGA GGAAGGAGAC
 GGCCTGGCGA TGGCCTGAGT TAAGCAAATT TGGAGGTTTT GACCCACAGG
 GTGCACTGAG AAACTTGGCT ACAGCAAAAT ACAACTTGAA CATCATGACT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCCG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CGCTGGGTCA GCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCGCTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAGG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCGGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGTGCCCTGG GGTTGTCTGC GGGCCTCGTG GGCATTGTGG
 TGGGCACTGT CTTCATCATT CAAGGCCTAC GTTCAGTTGG TGCTTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC04131
IPD:MHC04131 Mafa-DQA1*01:08:02 768 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTCGCCC TGACCACCGT
 GATAAGCCCC TGTGGAGGTG AAGACATTGT GGCTGACCAC GTTGCCTCTT
 GTGGTGTAAA CGTGTACCAG TCTTACGGTC CCTCTGGCCA GTACACCCAT
 GAATTTGATG GGGACGAGCA GTTCTACGTG GACCTGGGGA GGAAGGAGAC
 GGCCTGGCGA TGGCCTGAGT TAAGCAAATT TGGAGGTTTT GACCCACAGG
 GTGCACTGAG AAACTTGGCT ACAGCAAAAT ACAACTTGAA CATCATGACT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCCG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CGCTGGGTCA GCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCGCTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAGG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCGGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGTGCCCTGG GGTTGTCTGC GGGCCTCGTG GGCATTGTGG
 TGGGCACTGT CTTCATCATT CAAGGCCTAC GTTCAGTTGG TGCTTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC04703
IPD:MHC04703 Mafa-DQA1*01:08:03 687 bases
 GGAGGTGAAG ACATAGTGGC TGACCACGTT GCCTCTTGCG GTGTAAACGT
 GTACCAGTCT TACGGTCCCT CTGGCCAGTA CACCCATGAA TTTGATGGGG
 ACGAGCAGTT CTACGTGGAC CTGGGGAGGA AGGAGACGGC CTGGCGATGG
 CCTGAGTTAA GCAAATTTGG AGGTTTTGAC CCACAGGGTG CACTGAGAAA
 CTTGGCTACA GCAAAATACA ACTTGAACAT CATGACTAAA CGCTACAACT
 CTACCGCTGC TACCAATGAG GTTCCCGAGG TCACAGTGTT TTCCAAGTCT
 CCCGTGACGC TGGGTCAGCC CAACACCCTC ATCTGTCTTG TGGACAACAT
 CTTTCCTCCT GTGGTGAACA TCACATGGTT GAGCAATGGG CGCTCAGTCA
 CAGAAGGGGT TTCTGAGACC AGCTTCCTCT CCAAGAGTGA TCATTCCTTC
 TTCAAGATCA GTTACCTCAC CTTCCTCCCT TCTGCTGATG AGATTTATGA
 CTGCAGGGTG GAGCACTGGG GCCTGGACGA GCCTCTTCTG AAACACTGGG
 AGCCGGAGAT TCCAGCGCCC ATGTCAGAGC TCACAGAGAC TGTGGTCTGT
 GCCCTGGGGT TGTCTGCGGG CCTCGTGGGC ATTGTGGTGG GCACTGTCTT
 CATCATTCAA GGCCTACGTT CAGTTGGTGC CTCCAGA* 
>DL;IPD:MHC03772
IPD:MHC03772 Mafa-DQA1*01:09 768 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTCGCCC TGACCACCGT
 GATGAGCCCC TGTGGAGGTG AAGACATTGT GGCTGACCAC GTTGCCTCTT
 GCGGTGTAAA CTTGTACCAG TCTTACGGTC CCTCTGGCCA GTACACCCAC
 GAATTTGACG GAGACGAGCA GTTCTACGTG GACCTGGGGA GGAAGGAGAC
 GGCCTGGCGA TGGCCTGAGT TAAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT ACAGTAAAAT ACAACTTGAA CATCATGACT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCCG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CACTGGGTCA GCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAGT
 GGGCGCTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCATCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAGG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCGGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG
 TGGGCACTGT CTTCATCATT CAAGGCCTAC GTTCAGTTGG TGCTTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC03773
IPD:MHC03773 Mafa-DQA1*01:10 768 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTCGCCC TGACCACCGT
 GATGAGCCCC TGTGGAGGTG AAGACATTGT GGCTGACCAC GTTGCCTCTT
 GTGGTGTAAA CTTGTACCAG TCTTACGGTC CCTCTGGCCA GTTCACCCAT
 GAATTTGATG GGGACGAGCA GTTCTACGTG GACCTGGGGA GGAAGGAGAC
 GGCCTGGCGA TGGCCTGAGT TAAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GCGGCAAAAC ACAACTTGAA CATCTTGACT
 AAACGCTACA ACTTCACCGC TGCTACCAAT GAGGTTCCCG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CGCTGGGTCA GCCCAATAAC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCACTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTTTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAGG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCGGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG
 TGGGCACCGT CTTCATCATT CAAGGCCTAC GTTCAGTTGG TGCTTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC03775
IPD:MHC03775 Mafa-DQA1*01:11 768 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTCGTTC TGACCGCTGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT CGCTGACCAC GTTGCCTCTT
 GCGGTGTAAA CTTGTACCAG ACTTACGGTC TTTCTGGCCA GTACACCCAC
 GAATTTGACG GAGACGAGCA GTTCTACGTG GACCTGGAGA GGAAGGAGAC
 GGCATGGCGA TGGCCTGAGT TAAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGTCAAAAC ACAACTTGAA TATCATGACT
 AAACGCTACA ACTCTACCGC TGCTATCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA TGCTGGGTCA GCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCGCTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAGG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG
 TGGGCACTGT CTTCATCATT CAAGGCCTAC GTTCAGTTGG TGCTTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC03841
IPD:MHC03841 Mafa-DQA1*01:12 768 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTCGCCC TGACCACCAT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT CGCTGACCAT GTTGCCTCTT
 GCGGTGTAAA CTTGTACCAG ACTTACGGTC TCTCTGGCCA GTTCACCCAT
 GAATTTGATG GAGATGAGCA GTTCTACGTG GACCTGAGGA GGAAGGAGAC
 AGCCTGGCGA TGGCCTGAGT TAAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGTTAAAAC ACAACTTGAA CATCGTGACT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCCG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CACTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCGCTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAGG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCGGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG
 TGGGCACTGT CTTCATCATT CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC04127
IPD:MHC04127 Mafa-DQA1*01:13 768 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTTGCTC TGACCACCGT
 GATGAGCCCC TGTGGAGGTG AAGACATTGT GGCTGACCAC GTTGCCTCTT
 GCGGTGTAAA CTTGTACCAG TCTTACGGTC CCTCTGGCCA GTACACCCAC
 GAATTTGATG GAGACGAGCA GTTCTACGTG GACCTGGAGA GGAAGGAGAC
 GGCCTGGCGA TGGCCTGAGT TAAGGAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGGCAAAAC ACAACTTGAA CATCATAACC
 AAAGACTACA ACTCCACTGC TGCTACCAAT GAGGTTCCCG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CACTGGGTCA GCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCACTCAG TCACAGAAGG TGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTCACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAGG GTGGAGCACT GGGGCCTGGA CGAGCCTATT
 CTGAAACACT GGGAGCCTGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGTGCCCTGG GGTTGTCTGC GGGCCTCGTG GGCATTGTGG
 TGGGCACTGT CTTCATCATT CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC04128
IPD:MHC04128 Mafa-DQA1*01:14:01 768 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTCGTTC TGACCGCTGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT CGCTGACCAC GTTGCCTCTT
 GCGGTGTAAA CTTGTACCAG ACTTACGGTC TTTCTGGCCA GTACACCCAC
 GAATTTGATG GAGATGAGCG GTTCTACGTG GACCTGGAGA GGAAGGAGAC
 GGCCTGGCGA TGGCCTGAGT TAAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGTTAAAAC ACACCTTGAA CATCGTGACT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA TGCTGGGTCA GCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCGCTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAGG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCAGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG
 TGGGCACTGT CTTCATCATT CAAGGCCTAC GTTCAGTTGG TGCTTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC04714
IPD:MHC04714 Mafa-DQA1*01:14:02 687 bases
 GGAGGTGAAG ACATAGTGGC TGACCACGTT GCCTCTTGCG GTGTAAACTT
 GTACCAGACT TACGGTCTTT CTGGCCAGTA CACCCACGAA TTTGATGGAG
 ACGAGCGGTT CTACGTGGAC CTGGAGAGGA AGGAGACGGC CTGGCGATGG
 CCTGAGTTAA GCAAATTTGG AGGTTTTGAC CCGCAGGGTG CACTGAGAAA
 CTTGGCTGTG TTAAAACACA CCTTGAACAT CGTGACTAAA CGCTACAACT
 CTACCGCTGC TACCAATGAG GTTCCTGAGG TCACAGTGTT TTCCAAGTCT
 CCCGTGATGC TGGGTCAGCC CAACACCCTC ATCTGTCTTG TGGACAACAT
 CTTTCCTCCT GTGGTGAACA TCACATGGTT GAGCAATGGG CGCTCAGTCA
 CAGAAGGGGT TTCTGAGACC AGCTTCCTCT CCAAGAGTGA TCATTCCTTC
 TTCAAGATCA GTTACCTCAC CTTCCTCCCT TCTGCTGATG AGATTTATGA
 CTGCAGGGTG GAGCACTGGG GCCTGGACGA GCCTCTTCTG AAACACTGGG
 AGCCAGAGAT TCCAGCGCCC ATGTCAGAGC TCACAGAGAC TGTGGTCTGC
 GCCCTGGGGT TGTCTGTGGG CCTCGTGGGC ATTGTGGTGG GCACTGTCTT
 CATCATTCAA GGCCTACGTT CAGTTGGTGC CTCCAGA* 
>DL;IPD:MHC01176
IPD:MHC01176 Mafa-DQA1*01:15 768 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTCGCCC TGACCACCAT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT CGCTGACCAC GTTGCCTCTT
 GCGGTGTAAA CTTGTACCAG ACTTACGGTC TTTCTGGCCA GTACACCCAC
 GAATTTGATG GAGACGAGCA GTTCTATGTG GACCTGGAGA GGAAGGAGAC
 GGCATGGCGA TGGCCTGAGT TAAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGTCAAAAC ACAACTTGAA TATCATGACT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CGCTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCACTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAGA GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGTG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG
 TGGGCACTGT CTTCATCATT CAAGGCCTAC GTTCAGTTGG TGCTTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC05139
IPD:MHC05139 Mafa-DQA1*01:15:02 768 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTCGCCC TGACCACCAT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT CGCTGACCAC GTTGCCTCTT
 GCGGTGTAAA CTTGTACCAG ACTTACGGTC TTTCTGGCCA GTACACCCAC
 GAATTTGATG GAGACGAGCA GTTCTACGTG GACCTGGAGA GGAAGGAGAC
 GGCATGGCGA TGGCCTGAGT TAAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGTCAAAAC ACAACTTGAA TATCATGACT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CGCTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCACTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAGA GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGTG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG
 TGGGCACTGT CTTCATCATT CAAGGCCTAC GTTCAGTTGG TGCTTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC04701
IPD:MHC04701 Mafa-DQA1*01:16 687 bases
 GGAGGTGAAG ACATAGTGGC TGACCACGTT GCCTCTTGTG GTGTAAACTT
 GTACCAGTCT TACGGTCCCT CTGGCCAGTT CACCCATGAA TTTGATGGGG
 ACGAGCAGTT CTACGTGGAC CTGGGGAGGA AGGAGACGGC CTGGCGATGG
 CCTGAGTTAA GCAAATTTGG AGGTTTTGAC CCGCAGGGTG CACTGAGAAA
 CTTGGCTGCG GCGAAACACA ACTTGAACAT CTTGACTAAA CGCTACAACT
 TCACCGCTGC TACCAATGAG GTTCCCGAGG TCACAGTGTT TTCCAAGTCT
 CCCGTGACGC TGGGTCAGCC CAATACCCTC ATCTGTCTTG TGGACAACAT
 CTTTCCTCCT GTGGTGAACA TCACATGGTT GAGCAATGGG CACTCAGTCA
 CAGAAGGGGT TTCTGAGACC AGCTTCCTCT CCAAGAGTGA TCATTCCTTT
 TTCAAGATCA GTTACCTCAC CTTCCTCCCT TCTGCTGATG AGATTTATGA
 CTGCAGGGTG GAGCACTGGG GCCTGGACGA GCCTCTTCTG AAACACTGGG
 AGCCGGAAAT TCCAGCGCCC ATGTCAGAGC TCACAGAGAC TGTGGTCTGC
 GCCCTGGGGT TGTCTGTGGG CCTCGTGGGC ATTGTGGTGG GCACTGTCTT
 CATCATTCAA GGCCTACGTT CAGTTGGTGC CTCCAGA* 
>DL;IPD:MHC04710
IPD:MHC04710 Mafa-DQA1*01:17 687 bases
 GGAGGTGAAG ACATAGTGGC TGACCACGTT GCCTCTTGCG GTGTAAACTT
 GTACCAGACT TACGGTCTTT CTGGCCAGTA CACCCACGAA TTTGATGGAG
 ACGAGCGGTT CTACGTGGAC CTGGAGAGGA AGGAGACGGC CTGGCGATGG
 CCTGAGTTAA GCAAATTTGG AGGTTTTGAC CCGCAGGGTG CACTGAGAAA
 CTTGGCTGTG TTAAAACACA CCTTGAACAT CGTGACTAAA CGCTACAACT
 CTACCGCTGC TACCAATGAG GTTCCTGAGG TCACAGTGTT TTCCAAGTCT
 CCCGTGATGC TGGGTCAGCC CAACACCCTC ATCTGTCTTG TGGACAACAT
 CTTTCCTCCT GTGGTGAACA TCACATGGTT GAGCAATGGG CGCTCAGTCA
 CAGAAGGGGT TTCCGAGACC AGCTTCCTCC CCAAGAGTGA TCATTCCTTC
 TTCAAGATCA GTTACCTCAC CTTCCTCCCT TCTGCTGATG AGATTTATGA
 CTGCAAGGTG GAGCACTGGG GCCTGGACGA GCTTCTTCTG AAACACAGGG
 AGCCTGAGAT TCCAGCGCCC TTGTCAGAGC TCACAGAGAC TGTGGTCCGC
 GCCCTGGGGT TGTCTGTGGG CCTCGTGGGC ATTGTGGTGG GGACCGTCTT
 GATCATCCGA GGCCTGCGTT CAGTTGGTGC CTCCAGA* 
>DL;IPD:MHC05137
IPD:MHC05137 Mafa-DQA1*01:21 768 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTCGTTC TGACCGCTGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT CGCTGACCAC GTTGCCTCTT
 GCGGTGTAAA CTTGTACCAG ACTTACGGTC TTTCTGGCCA GTACACCCAC
 GAATTTGATG GAGACGAGCG GTTCTACGTG GACCTGGAGA GGAAGGAGAC
 GGCCTGGCGA TGGCCTGAGT TAAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGTCAAAAC ACAACTTGAA TATCATGACT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA TGCTGGGTCA GCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCGCTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAGG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCAGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG
 TGGGCACTGT CTTCATCATT CAAGGCCTAC GTTCAGTTGG TGCTTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC01180
IPD:MHC01180 Mafa-DQA1*05:01:01 765 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTTGCTC TGACCACCGT
 GATGAGCCCC TGCGGAGGTG AAGACATAGT GGCTGACCAC GTTGCCTCTT
 ACGGTGTAAA CGTGTACCAG TCTTACGGTC CCTCTGGCCA GTACTCCCAT
 GAATTTGATG GAGACGAGCA GTTCTACGTG GACCTGGGGA GGAAGGAGAC
 TGTCTGGCGG TTGCCTATTC CCTACCGATA TGGTTTTGAC CCGCAATTTG
 CATTGAGAAA CATCGCTGTG CTAACACATA ACTTGAACAT CCTGATTAAA
 CGCTCCAACT CTACCGCTGC TACCAATGAG GTTCCCGAGG TCACAGTGTT
 TTCCAAGTCT CCTGTGATGC TGGGTCAGCC CAACACCCTC ATCTGTCTTG
 TGGACAACAT CTTTCCTCCT GTGGTGAACA TCACATGGTT GAGCAATGGA
 CACTCAGTCA TAGAAGGGGT TTCTGAGACC AGCTTCCTCT CCAAGAGTGA
 TCATTCCTTC TTCAAGATGA GTTACCTCAC CTTCCTCCCT TCTGCTGATG
 AGATTTATGA CTGCAGGGTG GAGCACTGGG GCCTGGATGA GCCTCTTCTG
 AAACACTGGG AGCCGGAGAT TCCAGTGCCC ATGTCAGAGC TCACAGAGAC
 TGTGGTCTGC GCCCTGGGGT TGTCTGCGGG CCTCGTGGGC ATTGTGGTGG
 GGACCGTCTT GATCATCCGA GGCCTGCGTT CAGTTGGTGC TTCCAGACAC
 CAAGGGCCCT TGTGA*   
>DL;IPD:MHC04704
IPD:MHC04704 Mafa-DQA1*05:01:02 684 bases
 GGAGGTGAAG ACATAGTGGC TGACCACGTT GCCTCTTACG GTGTAAACGT
 GTACCAGTCT TACGGTCCCT CTGGCCAGTA CTCCCATGAA TTTGATGGAG
 ACGAGCAGTT CTACGTGGAC CTGGGGAGGA AGGAGACTGT CTGGCGGTTG
 CCTATTCCCT ACCGATATGG TTTTGACCCG CAATTTGCAT TGAGAAACAT
 CGCTGTGCTA ACACATAACT TGAACATCCT GATTAAACGC TCCAACTCTA
 CCGCTGCTAC CAATGAGGTT CCCGAGGTCA CAGTGTTTTC CAAGTCTCCT
 GTGATGCTGG GTCAGCCCAA CACCCTCATC TGTCTTGTGG ACAACATCTT
 TCCTCCTGTG GTGAACATCA CATGGTTGAG CAATGGACAC TCAGTCATAG
 AAGGGGTTTC TGAGACCAGC TTCCTCTCCA AGAGTGATCA TTCCTTCTTC
 AAGATGAGTT ACCTCACCTT CCTCCCTTCT GCTGATGAGA TTTATGACTG
 CAGGGTGGAG CACTGGGGCC TGGATGAGCC TCTTCTGAAA CACTGGGAGC
 CGGAGATTCC AGTGCCCATG TCAGAGCTCA CAGAGACTGT GGTCTGCGCC
 CTGGGGTTGT CTGCGGGCCT CGTGGGCATT GTGGTGGGGA CCGTCTTGAT
 CATCCGAGGC CTGCGTTCAG TTGGTGCCTC CAGA* 
>DL;IPD:MHC01181
IPD:MHC01181 Mafa-DQA1*05:02 750 bases
 GCTCTGTTGC TGGGGGCCCT CACTCTGACC ACCGTGATGA GCCCCTGTGG
 AGGTGAAGAC ATAGTGGCTG ACCACGTTGC CTCTTACGGT GTAAACGTGT
 ACCAGTCTTA TGGTCCCTCT GGCCAGTTCA CTCATGAATT TGATGGAGAC
 GAGCAGTTCT ACGTGGACCT GGGGAGGAAG GAGACTGTCT GGCGGTTGCC
 TATTCCCTAC CGATATGGTT TTGACCCGCA ATTTGCATTG AGAAACATCG
 CTGTGCTAAC ACATAACTTG AACATCCTGA TTAAACGCTC CAACTCTACC
 GCTGCTACCA ATGAGGTTCC CGAGGTCACA GTGTTTTCCA AGTCTCCCGT
 GATGCTGGGT CAGCCCAACA CCCTCATCTG TCTTGTGGAC AACATCTTTC
 CTCCTGTGGT GAACATCACA TGGTTGAGCA ATGGACACTC AGTCATAGAA
 GGGGTTTCTG AGACCAGCTT CCTCTCCAAG AGTGATCATT CCTTCTTCAA
 GATCAGTTAC CTCACCTTCC TCCCTTCTGC TGATGAGATT TATGACTGCA
 GGGTGGAGCA CTGGGGCCTG GATGAGCCTC TTCTGAAACA CTGGGAGCCG
 GAGATTCCAG TGCCCATGTC AGAGCTCACA GAGACTGTGG TCTGCGCCCT
 GGGGTTGTCT GCGGGCCTCG TGGGCATTGT GGTGGGGACC GTCTTGATCA
 TCCGAGGCCT GCGTTCAGTT GGTGCTTCCA GACACCAAGG GCCCTTGTGA
>DL;IPD:MHC01182
IPD:MHC01182 Mafa-DQA1*05:03:01 765 bases
 ATGATCTTAA ACAAAGCTCT GATGCTGGCG GCCCTCGCCC TGACCACCGT
 GATGAGCCCC TGTGGAGGTG AAGAAATTGT GGCTGACCAT GTTGCCTCTT
 ACGGTGTAAA CTTGTACCAG TCTTACGGTT TCTCTGGCCA GTACTCCCAT
 GAATTTGATG GAGATGAGCA GTTCTACGTG GACCTGGAGA GGAAGGAGAC
 TGTCTGGCAG TTGCCTGTTC TCAGCCAATT TAGTTTCGAC GCGCAATTTG
 CACTGACAAA CATTGCTGTG GGAAAACAGA ACTTGAACTA CCTGATGAAA
 CAGTCCAACT CTACCGCTGC TACCAATGAG GTACCTGAGG TCACAGTGTT
 TTCCAAGTCG CCCGTGACAC TGGGTCACCC CAACACCCTC ATCTGTCTTG
 TGGACAACAT CTTTCCTCCT GTGGTGAACA TCACATGGTT GAGCAATGGG
 CACTCAGTCA CAGAAGGTGT TTCTGAGACC AGCTTCCTCT CCAAGAGTGA
 TCATTCCTTC TTCAAGATCA GTTACCTCAC CTTCCTCGCT TCTGCTGATG
 AGATTTATGA CTGCAAGGTA GAGCACTGGG GCCTGGATGA GCCTCTTCTG
 AAACACTGGG AGCCGGAGAT TCCAGCGCCC ATGTCAGAGC TCACAGAGAC
 TGTGGTCTGC GCCCTGGGGT TGTCTGTGGG CCTCGTGGGC ATTGTGGTGG
 GCACTGTCTT CATCATCCGA GGCCTGCGTT CAGTTGGTGC CTCCAGACAC
 CAAGGGCCCT TGTGA*   
>DL;IPD:MHC03769
IPD:MHC03769 Mafa-DQA1*05:03:02 765 bases
 ATGATCTTAA ACAAAGCTCT GATGCTGGCG GCCCTCGCCC TGACCACCGT
 GATGAGCCCC TGTGGAGGTG AAGAAATTGT GGCTGACCAT GTTGCCTCTT
 ACGGTGTAAA CTTGTACCAG TCTTACGGTT TCTCTGGCCA GTACTCCCAT
 GAATTTGATG GAGATGAGCA GTTCTACGTG GACCTGGAGA GGAAGGAGAC
 TGTCTGGCAG TTGCCTGTTC TCAGCCAATT TAGTTTCGAC GCGCAATTTG
 CACTGACAAA CATTGCTGTG GGAAAACAGA ACTTGAACTA CCTGATGAAA
 CAGTCCAACT CTACCGCTGC TACCAATGAG GTACCTGAGG TCACAGTGTT
 TTCCAAGTCG CCCGTGACAC TGGGTCACCC CAACACCCTC ATCTGTCTTG
 TGGACAACAT CTTTCCTCCT GTGGTGAACA TCACATGGTT GAGCAATGGG
 CACTCAGTCA CAGAAGGTGT TTCTGAGACC AGCTTCCTCT CCAAGAGTGA
 TCATTCCTTC TTCAAGATCA GTTACCTCAC CTTCCTCGCT TCTGCTGATG
 AGATTTATGA CTGCAAGGTA GAGCACTGGG GCCTGGATGA GCCTCTTCTG
 AAACACTGGG AGCCGGAGAT TCCAGCGCCC ATGTCAGAGC TCACAGAGAC
 TGTGGTCTGC GCCCTGGGGT TGTCTGTAGG CCTCGTGGGC ATTGTGGTGG
 GCACTGTCTT CATCATCCGA GGCCTGCGTT CAGTTGGTGC CTCCAGACAC
 CAAGGGCCCT TGTGA*   
>DL;IPD:MHC01183
IPD:MHC01183 Mafa-DQA1*05:04 765 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTCGCCC TGACCACCGT
 GATGAGCTCC TGTGGAGGTG AAGACATTGT GGCTGACCAC CTCGCCTCTT
 ACGGTGTGAA CTTCTACCAG TCTTACGGTC TTTCTGGCCA GTACTCCCAT
 GAATTTGATG GAGACGAGCA GTTCTATGTG GACCTGGGGA GGAAGGAGAC
 TGTCTGGCGG TTGCCTATTC CCTACCGATA TGGTTTTGAC CCGCAATTTG
 CATTGAGAAA CATCGCTGTG CTAACACATA ACTTGAACGT CCTAATTAAA
 CGCTCCAACT CTACCGCTGC TACCAATGAG GTTCCCGAGG TCACAGTGTT
 TTCCAAGTCT CCCGTGACGC TGGGTCACCC CAACACCCTC ATCTGTCTTG
 TGGACCACAT CTTTCCTCCT GTGGTGAACA TCACATGGTT GAGCAATGGG
 CGCTCAGTCA CAGAAGGGGT TTCTGAGACC AGCTTCCTCT CCAAGAGTGA
 TCATTCCTTC TTCAAGATCA GTTACCTCAC CTTCCTCCCT TCTGCTGATG
 AGATTTATGA CTGCAGGGTG GAGCACTGGG GCCTGGACGA GCCTCTTCTG
 AAACACTGGG AGCCAGAGAT TCCAGCGCCC ATGTCAGAGC TCACAGAGAC
 TGTGGTCTGC GCCCTGGGGT TGTCTGCGGG CCTCGTGGGC ATTGTGGTGG
 GGACCATCTT GATCATCCGA GGCCTGCGTT CAGTTGGTGC TTCCAGACAT
 CAAGGGCCCT TGTAA*   
>DL;IPD:MHC03766
IPD:MHC03766 Mafa-DQA1*05:05:01 765 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTCGTTC TGACCACCGT
 GATGAGCCCC TGTGGAGGTG AAGACATTGT GGCTGACCAC GTCGCCTCTT
 ACGGTGTAAA TGTGTACCAG TCTTACGGTC TCTCTGGTCA GTACTCCCAT
 GAATTTGATG GAGACGAGCA GTTCTACGTG GACCTGGGGA GGAAAGAGAC
 TGTCTGGCGG TTGCCCATTC TCAGCCAATT TAGTTTTGAT CCACAATTTG
 CATTGAGAAA CATCGCTGTG CTAACACATA ACTTGAACAT CCTGATTAAA
 CGCTCCAACT CTACCGCTGC TACCAATGAG GTTCCCGAGG TCACAGTGTT
 TTCCAAGTCT CCTGTGACAC TGGGTCACCC CAACACCCTC ATCTGTCTTG
 TGGACAACAT CTTTCCTCCT GTGGTCAACA TCACATGGTT GAGCAATGGG
 CACTCAGTCA CAGAAGGGGT TTCTGAGACC AGCTTCCTCT CCAAGAGTGA
 TCATTCATTC TTCAAGATCA GTTACCTCAC CTTCCTCCCT TCTGCTGATG
 AGATTTATGA CTGCAGGGTG GAGCACTGGG GCCTGGATGA GCCTCTTCTG
 AAACACTGGG AGCCGGAGAT TCCAGCACCC ATGTCAGAGC TCACAGAGAC
 TGTGGTCTGC GCCCTGGGGT TGTCTGCGGG CCTCGTGGGC ATTGTGGTGG
 GGACCGTCTT GATCATCCGA GGCCTGCGTT CAGTTGGTGC TTCCAGACAC
 CAAGGGCCCT TGTGA*   
>DL;IPD:MHC04705
IPD:MHC04705 Mafa-DQA1*05:05:02 684 bases
 GGAGGTGAAG ACATAGTGGC TGACCACGTC GCCTCTTACG GTGTAAATGT
 GTACCAGTCT TACGGTCTCT CTGGTCAGTA CTCCCATGAA TTTGATGGAG
 ACGAGCAGTT CTACGTGGAC CTGGGGAGGA AAGAGACTGT CTGGCGGTTG
 CCCATTCTCA GCCAATTTAG TTTTGATCCA CAATTTGCAT TGAGAAACAT
 CGCTGTGCTA ACACATAACT TGAACATCCT GATTAAACGC TCCAACTCTA
 CCGCTGCTAC CAATGAGGTT CCCGAGGTCA CAGTGTTTTC CAAGTCTCCT
 GTGACACTGG GTCACCCCAA CACCCTCATC TGTCTTGTGG ACAACATCTT
 TCCTCCTGTG GTCAACATCA CATGGTTGAG CAATGGGCAC TCAGTCACAG
 AAGGGGTTTC TGAGACCAGC TTCCTCTCCA AGAGTGATCA TTCATTCTTC
 AAGATCAGTT ACCTCACCTT CCTCCCTTCT GCTGATGAGA TTTATGACTG
 CAGGGTGGAG CACTGGGGCC TGGATGAGCC TCTTCTGAAA CACTGGGAGC
 CGGAGATTCC AGCACCCATG TCAGAGCTCA CAGAGACTGT GGTCTGCGCC
 CTGGGGTTGT CTGCGGGCCT CGTGGGCATT GTGGTGGGGA CCGTCTTGAT
 CATCCGAGGC CTGCGTTCAG TTGGTGCCTC CAGA* 
>DL;IPD:MHC03768
IPD:MHC03768 Mafa-DQA1*05:06 765 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTTGCTC TGACCACCGT
 GATGAGCCCC TGCGGAGGTG AAGACATAGT GGCTGACCAC GTTGCCTCTT
 ACGGTGTAAA CGTGTACCAG TCTTACGGTC CCTCTGGCCA GTACTCCCAT
 GAATTTGATG GAGACGAGCA GTTCTACGTG GACCTGGGGA GGAAGGAGAC
 TGTCTGGCGG TTGCCTATTC CCTACCGATA TGGTTTTGAC CCGCAATTTG
 CATTGAGAAA CATCGCTGTG CTAACACATA ACTTGAACAT CCTGATTAAA
 CGCTCCAACT CTACCGCTGC TACCAATGAG GTTCCCGAGG TCACAGTGTT
 TTCCAAGTCT CCCGTGATGC TGGGTCAGCC CAACACCCTC ATCTGTCTTG
 TGGACAACAT CTTTCCTCCT GTGGTGAACA TCACATGGTT GAGCAATGGA
 CACTCAGTCA TAGAAGGGGT TTCTGAGACC AGCTTCCTCT CCAAGAGTGA
 TCATTCCTTC TTCAAGATCA GTTACCTCAC CTTCCTCCCT TCTGCTGATG
 AGATTTATGA CTGCAGGGTG GAGCACTGGG GCCTGGATGA GCCTCTTCTG
 AAACACTGGG AGCCAGAGAT TCCAGTGCCC ATGTCAGAGC TCACAGAGAC
 TGTGGTCTGC GCCCTGGGGT TGTCTGCGGG CCTCGTGGGC ATTGTGGTGG
 GGACCGTCTT GATCATCCGA GGCCTGCGTT CAGTTGGTGC TTCCAGACAC
 CAAGGGCCCT TGTGA*   
>DL;IPD:MHC04125
IPD:MHC04125 Mafa-DQA1*05:07:01 765 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTCGCTC TGACCACCAT
 GATGAGACCC TGTGGAGGTG AAGACATTGT GGCTGACCAC GTCGCCTCTT
 ACGGTGTAAA TGTGTACCAG TCTTACGGTC TCTCTGGTCA GTACTCCCAT
 GAATTTGATG GAGACGAGCA GTTCTACGTG GACCTGGGGA GGAAAGAGAC
 TGTCTGGCGG TTGCCCATTC TCAGCCAATT TAGTTTTGAT CCACAATTTG
 CATTGAGAAA CATCGCTGTG CTAACACATA ACTTGAACAG CCTGATTAAA
 CGCTCCAACT CTACCGCTGC TACCAATGAG GTTCCCGAGG TCACAGTGTT
 TTCCAAGTCT CCTGTGACAC TGGGTCACCC CAACACCCTC ATCTGTCTTG
 TGGACAACAT CTTTCCTCCT GTGGTCAACA TCACATGGTT GAGCAATGGG
 CACTCAGTCA CAGAAGGGGT TTCTGAGACC AGCTTCCTCT CCAAGAGTGA
 TCATTCATTC TTCAAGATCA GTTACCTCAC CTTCCTCCCT TCTGCTGATG
 AGATTTATGA CTGCAGGGTG GAGCACTGGG GCCTGGATGA GCCTCTTCTG
 AAACACTGGG AGCCGGAGAT TCCAGCACCC ATGTCAGAGC TCACAGAGAC
 TGTGGTCTGC GCCCTGGGGT TGTCTGCGGG CCTCGTGGGC ATTGTGGTGG
 GGACCGTCTT GATCATCCGA GGCCTGCGTT CAGTTGGTGC TTCCAGACAC
 CAAGGGCCCT TGTGA*   
>DL;IPD:MHC04707
IPD:MHC04707 Mafa-DQA1*05:07:02 684 bases
 GGAGGTGAAG ACATAGTGGC TGACCACGTC GCCTCTTACG GTGTAAATGT
 GTACCAGTCT TACGGTCTCT CTGGTCAGTA CTCCCATGAA TTTGATGGAG
 ACGAGCAGTT CTACGTGGAC CTGGGGAGGA AAGAGACTGT CTGGCGGTTG
 CCCATTCTCA GCCAATTTAG TTTTGATCCA CAATTTGCAT TGAGAAACAT
 CGCTGTGCTA ACACATAACT TGAACAGCCT GATTAAACGC TCCAACTCTA
 CCGCTGCTAC CAATGAGGTT CCCGAGGTCA CAGTGTTTTC CAAGTCTCCT
 GTGACACTGG GTCACCCCAA CACCCTCATC TGTCTTGTGG ACAACATCTT
 TCCTCCTGTG GTCAACATCA CATGGTTGAG CAATGGGCAC TCAGTCACAG
 AAGGGGTTTC TGAGACCAGC TTCCTCTCCA AGAGTGATCA TTCATTCTTC
 AAGATCAGTT ACCTCACCTT CCTCCCTTCT GCTGATGAGA TTTATGACTG
 CAGGGTGGAG CACTGGGGCC TGGATGAGCC TCTTCTGAAA CACTGGGAGC
 CGGAGATTCC AGCACCCATG TCAGAGCTCA CAGAGACTGT GGTCTGCGCC
 CTGGGGTTGT CTGCGGGCCT CGTGGGCATT GTGGTGGGGA CCGTCTTGAT
 CATCCGAGGC CTGCGTTCAG TTGGTGCCTC CAGA* 
>DL;IPD:MHC04129
IPD:MHC04129 Mafa-DQA1*05:08 765 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTCGCTC TGACCACCGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT GGCTGACCAC GTTGCCTCTT
 ACGGTGTAAA CGTGTACCAG TCTTACGGTC CCTCTGGCCA GTACTCCCAT
 GAATTTGATG GAGACGAGCA GTTCTACGTG GACCTGGGGA GGAAGGAGAC
 TGTCTGGCGG TTGCCTATTC CCTACCGATA TGGTTTTGAC CCGCAATTTG
 CATTGAGAAA CATCGCTGTG CTAACACATA ACTTGAACAT CCTGATTAAA
 CGCTCCAACT CTACCGCTGC TACCAATGAG GTTCCCGAGG TCACAGTGTT
 TTCCAAGTCT CCTGTGATGC TGGGTCAGCC CAACACCCTC ATCTGTCTTG
 TGGACAACAT CTTTCCTCCT GTGGTGAACA TCACATGGTT GAGCAATGGA
 CACTCAGTCA TAGAAGGGGT TTCTGAGACC AGCTTCCTCT CCAAGAGTGA
 TCATTCCTTC TTCAAGATCA GTTACCTCAC CTTCCTCCCT TCTGCTGATG
 AGATTTATGA CTGCAGGGTG GAGCACTGGG GCCTGGATGA GCCTCTTCTG
 AAACACTGGG AGCCGGAGAT TCCAGTGCCC ATGTCAGAGC TCACAGAGAC
 TGTGGTCTGC GCCCTGGGGT TGTCTGCGGG CCTCGTGGGC ATTGTGGTGG
 GGACCGTCTT GATCATCCGA GGCCTGCGTT CAGTTGGTGC TTCCAGACAC
 CAAGGGCCCT TGTGA*   
>DL;IPD:MHC04130
IPD:MHC04130 Mafa-DQA1*05:09 765 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTCACTC TGACCACCGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT GGCTGACCAC GTTGCCTCTT
 ACGGTGTAAA CGTGTACCAG TCTTACGGTC CCTCTGGCCA GTACTCCCAT
 GAATTTGATG GAGACGAGCA GTTCTACGTG GACCTGGGGA GGAAGGAGAC
 TGTCTGGCGG TTGCCTATTC CCTACCGATA TGGTTTTGAC CCGCAATTTG
 CATTGAGAAA CATCGCTGTG CTAACACATA ACTTGAACAT CCTGATTAAA
 CGCTCCAACT CTACCGCTGC TACCAATGAG GTTCCCGAGG TCACAGTGTT
 TTCCAAGTCT CCTGTGATGC TGGGTCAGCC CAACACCCTC ATCTGTCTTG
 TGGACAACAT CTTTCCTCCT GTGGTGAACA TCACATGGTT GAGCAATGGA
 CACTCAGTCA TAGAAGGGGT TTCTGAGACC AGCTTCCTCT CCAAGAGTGA
 TCATTCCTTC TTCAAGATCA GTTACCTCAC CTTCCTCCCT TCTGCTGATG
 AGATTTATGA CTGCAGGGTG GAGCACTGGG GCCTGGATGA GCCTCTTCTG
 AAACACTGGG AGCCGGAGAT TCCAGTGCCC ATGTCAGAGC TCACAGAGAC
 TGTGGTCTGC GCCCTGGGGT TGTCTGCGGG CCTCGTGGGC ATTGTGGTGG
 GGACCGTCTT GATCATCCGA GGCCTGCGTT CAGTTGGTGC TTCCAGACAC
 CAAGGGCCCT TGTGA*   
>DL;IPD:MHC01184
IPD:MHC01184 Mafa-DQA1*23:01 768 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTCGCTC TGACCACCGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT GGCTGACCAC GTTGCCTCTT
 ACGGTGTAAA CATGTACCAG TCTTACGGTC CCTCTGGCCA GTACACCCAT
 GAATTTGATG GAGACGAGGA GTTCTATGTG GACCTGGAGA GAAAGCAGAC
 TGTCTGGCAG TTGCCTCTGT TCAGCAAATT TAGAAGGTTT GACCCGCAGG
 GTGCACTGAG AAACATCGCT GTGCTACAAC ATAACTTGAA CATCGTGATT
 AAACGCTCCA ACTCCACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTCA TGCTGGGTCA GCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCACTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCGGA GATTCCAGCG CCCATGTCAG AGCTCACCGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTGT AGGCCTCGTG GGCATTGTGG
 TGGGCACTGT CTTCATCATC CGAGGCCTGC GTTCAATTGG CGCTTCCAGA
 CACCAAGGGC CCTTGTAA*   
>DL;IPD:MHC00276
IPD:MHC00276 Mafa-DQA1*24:01 188 bases
 TCTTATGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGACGAGGA
 GTTCTATGTG GACCTGGAGA GGAAGGAGAC CATCTGGCAG TTGCCTCTGT
 TCAGCAAATT TAGAAGTTTT GACCCGCAGG GTGCACTGAG AAACTTGGCT
 GTGGGAAAAC ACAACTTGAA CATCCTGATT AAACTCTC* 
>DL;IPD:MHC01185
IPD:MHC01185 Mafa-DQA1*24:02:01 768 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTCGCTC TGACCACCGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT GGCTGACCAC GTTGCGTCTT
 ACGGTGTAAA CCTGTACCAG TCTTATGGTC CCTCTGGCCA GTACACCCAT
 GAATTTGATG GAGATGAGGA GTTCTATGTG GACCTGGAGA GGAAGGAGAC
 CGTCTGGCAG TTGCCTCTGT TCAGCAAATT TAGAAGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGTCAAAAC ACAACTTGAA CATCCTGATT
 AAACACTCCA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CACTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCGCTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCGGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCACCCTGG GGTTGTCTAT GGGCCTCGTG GGCATTGTGG
 TGGGGACCGT CTTGATCATC CGAGGCCTGC GTTCAGTTGG TGCCTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC01186
IPD:MHC01186 Mafa-DQA1*24:02:02 768 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTCGCTC TGACCACCGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT GGCTGACCAC GTTGCGTCTT
 ACGGTGTGAA CCTGTACCAG TCTTATGGTC CCTCTGGCCA GTACACCCAT
 GAATTTGATG GAGATGAGGA GTTCTATGTG GACCTGGAGA GGAAGGAGAC
 CGTCTGGCAG TTGCCTCTGT TCAGCAAATT TAGAAGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGTCAAAAC ACAACTTGAA CATCCTGATT
 AAACACTCCA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CACTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCGCTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCGGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCACCCTGG GGTTGTCTAT GGGCCTCGTG GGCATTGTGG
 TGGGGACCGT CTTGATCATC CGAGGCCTGC GTTCAGTTGG TGCCTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC04435
IPD:MHC04435 Mafa-DQA1*24:02:03 768 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTTGCTC TGACCACCGT
 GATGAGCCCC TGCGGAGGTG AAGACATAGT GGCTGACCAC GTTGCGTCTT
 ACGGTGTAAA CCTGTACCAG TCTTATGGTC CCTCTGGCCA GTACACCCAT
 GAATTTGATG GAGATGAGGA GTTCTATGTG GACCTGGAGA GGAAGGAGAC
 CGTCTGGCAG TTGCCTCTGT TCAGCAAATT TAGAAGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGTCAAAAC ACAACTTGAA CATCCTGATT
 AAACACTCCA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CACTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCGCTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCGGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCACCCTGG GGTTGTCTAT GGGCCTCGTG GGCATTGTGG
 TGGGGACCGT CTTGATCATC CGAGGCCTGC GTTCAGTTGG TGCCTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC05134
IPD:MHC05134 Mafa-DQA1*24:02:04 768 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTTGCTC TGACCACCGT
 GATGAGCCCC TGCGGAGGTG AAGACATAGT GGCTGACCAC GTTGCGTCTT
 ACGGTGTAAA CCTGTACCAG TCTTATGGTC CCTCTGGCCA GTACACCCAT
 GAATTTGATG GAGACGAGGA GTTCTATGTG GACCTGGAGA GGAAGGAGAC
 CGTCTGGCAG TTGCCTCTGT TCAGCAAATT TAGAAGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGTCAAAAC ACAACTTGAA CATCCTGATT
 AAACACTCCA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CACTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCGCTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCGGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCACCCTGG GGTTGTCTAT GGGCCTCGTG GGCATTGTGG
 TGGGGACCGT CTTGATCATC CGAGGCCTGC GTTCAGTTGG TGCCTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC01619
IPD:MHC01619 Mafa-DQA1*24:03 768 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTCGCTC TGACCACCGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT GGCTGACCAC GTTGCGTCTT
 ACGGTGTAAA CATGTACCAG TCTTACGGTC CCTCTGGCCA GTACACCCAT
 GAATTTGATG GAGACGAGGA GTTCTATGTG GACCTGGAGA GGAAGGAGAC
 CGTCTGGCAG TTGCCTCTGT TCAGCAAATT TAGAAGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGGGAAAAC ACAACTTGAA CATCCTGATT
 AAACGCTCCA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CACTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCGCTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCGGA GATTCCAGCA CCCATGTCAG AGCTCACAGA
 AACTGTGGTC TGCGCCCTGG GGTTGTCTAT GGGCCTCGTG GGCATTGTGG
 TGGGGACCGT CTTGATCATC CGAGGCCTGC GTTCAGTTGG TGCCTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC03770
IPD:MHC03770 Mafa-DQA1*24:04 768 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTCGCTC TGACCACCGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT GGCTGACCAC GTTGCGTCTT
 ACGGTGTAAA CATGTACCAG TCTTACGGTC CCTCTGGCCA GTACACCCAT
 GAATTTGATG GAGACGAGGA GTTCTATGTG GACCTGGAGA GGAAGGAGAC
 CGTCTGGCAG TTGCCTCTGT TCAGCAAATT TAGAAGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGGGAAAAC ACAACTTGAA CATCCTGATT
 AAACGCTCCA ACTCTACCGT TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CACTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCGCTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCGGA GATTCCAGCA CCCATGTCAG AGCTCACAGA
 AACTGTGGTC TGCGCCCTGG GGTTGTCTAT GGGCCTCGTG GGCATTGTGG
 TGGGGACCGT CTTGATCATC CGAGGCCTGC GTTCAGTTGG TGCCTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC03771
IPD:MHC03771 Mafa-DQA1*24:05 768 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTCGCTC TGACCACCGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT GGCTGACCAC GTTGCGTCTT
 ACGGTGTAAA CCTGTACCAG TCTTATGGTC CCTCTGGCCA GTTCACCCAT
 GAATTTGATG GAGACGAGGA GTTCTATGTG GACCTGGAGA GGAAGGAGAC
 CGTCTGGCAG TTGCCTCTGT TCAGCAAATT TAGAAGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGGGAAAAC ACAACTTGAA CATCCTGATT
 AAACGCTCCA ACTCTACCGC TGCTACCAAT GAGGTTCCCG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CACTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCACTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCGGA GATTCCAGCA CCCATGTCAG AGCTCACAGA
 AACTGTGGTC TGCGCCCTGG GGTTGTCTAT GGGCCTCGTG GGCATTGTGG
 TGGGGACCGT CTTGATCATC CGAGGCCTGC GTTCAGTTGG TGCCTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC04371
IPD:MHC04371 Mafa-DQA1*24:06 768 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTTGCTC TGACCACCGT
 GATGAGCCCC TGCGGAGGTG AAGACATAGT GGCTGACCAC GTTGCGTCTT
 ACGGTGTAAA CCTGTACCAG TCTTATGGTC CCTCTGGCCA GTACACCCAT
 GAATTTGATG GAGACGAGGA GTTCTATGTG GACCTGGAGA GGAAGGAGAC
 CGTCTGGCAG TTGCCTCTGT TCAGCAAATT TAGAAGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGGGAAAAC ACAACTTGAA CATCCTGATT
 AAACACTCCA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CACTGGGTCA CCCCAGCACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCGCTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCGGA GATTCCAGCA CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTAT GGGCCTCGTG GGCATTGTGG
 TGGGGACCGT CTTGATCATC CGAGGCCTGC GTTCAGTTGG TGCCTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC04709
IPD:MHC04709 Mafa-DQA1*24:07 687 bases
 GGAGGTGAAG ACATAGTGGC TGACCACGTT GCGTCTTATG GTGTAAACCT
 GTACCAGTCT TATGGTCCCT CTGGCCAGTA CACCCATGAA TTTGATGGAG
 ATGAGGAGTT CTATGTGGAC CTGGAGAGGA AGGAGACCGT CTGGCAGTTG
 CCTCTGTTCA GCAAATTTAG AAGTTTTGAC CCGCAGGGTG CACTGAGAAA
 CTTGGCTGTG TCAAAACACA ACTTGAACAT CCTGATTAAA CACTCCAACT
 CTACCGCTGC TACCAATGAG GTTCCTGAGG TCACAGTGTT TTCCAAGTCT
 CCCGTGACAC TGGGTCACCC CAACACCCTC ATCTGTCTTG TGGACAACAT
 CTTTCCTCCT GTGGTGAACA TCACATGGTT GAGTAATGGG CGCTCAGTCA
 CAGAAGGGGT TTCTGAGACC AGCTTCCTCT CCAAGAGTGA TCATTCCTTC
 TTCAAGATCA GTTACCTCAC CTTCCTCCCT TCTGCTGATG AGATTTATGA
 CTGCAAGGTG GAGCACTGGG GCCTGGACGA GCCTCTTCTG AAACACTGGG
 AGCCGGAGAT TCCAGCACCC ATGTCAGAGC TCACAGAGAC TGTGGTCTGC
 GCCCTGGGGT TGTCTATGGG CCTCGTGGGC ATTGTGGTGG GGACCGTCTT
 GATCATCCGA GGCCTGCGTT CAGTTGGTGC CTCCAGA* 
>DL;IPD:MHC04711
IPD:MHC04711 Mafa-DQA1*24:08 687 bases
 GGAGGTGAAG ACATAGTGGC TGACCACGTT GCGTCTTACG GTGTAAACCT
 GTACCAGTCT TATGGTCCCT CTGGCCAGTA CACCCATGAA TTTGATGGAG
 ACGAGGAGTT CTATGTGGAC CTGGAGAGGA AGGAGACCGT CTGGCAGTTG
 CCTCTGTTCA GCAAATTTAG AAGTTTTGAC CCGCAGGGTG CACTGAGAAA
 CTTGGCTGTG GGAAAACACA ACTTGAACAT CCTGATTAAA CGCTCCAACT
 CTACCGCTGC TACCAATGAG GTTCCTGAGG TCACAGTGTT TTCCAAGTCT
 CCCGTGACAC TGGGTCACCC CAACACCCTC ATCTGTCTTG TGGACAACAT
 CTTTCCTCCT GTGGTGAACA TCACATGGTT GAGCAATGGG CGCTCAGTCA
 CAGAAGGGGT TTCTGAGACC AGCTTCCTCT CCAAGAGTGA TCATTCCTTC
 TTCAAGATCA GTTACCTCAC CTTCCTCCCT TCTGCTGATG AGATTTATGA
 CTGCAAGGTG GAGCACTGGG GCCTGGACGA GCCTCTTCTG AAACACTGGG
 AGCCGGAGAT TCCAGCACCC ATGTCAGAGC TCACAGAGAC TGTGGTCTGC
 GCCCTGGGGT TGTCTATGGG CCTCGTGGGC ATTGTGGTGG GGACCGTCTT
 GATCATCCGA GGCCTGCGTT CAGTTGGTGC CTCCAGA* 
>DL;IPD:MHC04713
IPD:MHC04713 Mafa-DQA1*24:09 687 bases
 GGAGGTGAAG ACATAGTGGC TGACCACGTT GCGTCTTACG GTGTAAACCT
 GTACCAGTCT TATGGTCCCT CTGGCCAGTT CACCCATGAA TTTGATGGAG
 ACGAGGAGTT CTATGTGGAC CTGGAGAGGA AGGAGACCGT CTGGCAGTTG
 CCTCTGTTCA GCAAATTTAG AAGTTTTGAC CCGCAGGGTG CACTGAGAAA
 CTTGGCTGTG TCAAAACACA ACTTGAACAT CCTGATTAAA CACTCCAACT
 CTACCGCTGC TACCAATGAG GTTCCTGAGG TCACAGTGTT TTCCAAGTCT
 CCCGTGACAC TGGGTCACCC CAACACCCTC ATCTGTCTTG TGGACAACAT
 CTTTCCTCCT GTGGTGAACA TCACATGGTT GAGCAATGGG CGCTCAGTCA
 CAGAAGGGGT TTCTGAGACC AGCTTCCTCT CCAAGAGTGA TCATTCCTTC
 TTCAAGATCA GTTACCTCAC CTTCCTCCCT TCTGCTGATG AGATTTATGA
 CTGCAAGGTG GAGCACTGGG GCCTGGACGA GCCTCTTCTG AAACACTGGG
 AGCCGGAGAT TCCAGCGCCC ATGTCAGAGC TCACAGAGAC TGTGGTCTGC
 ACCCTGGGGT TGTCTATGGG CCTCGTGGGC ATTGTGGTGG GGACCGTCTT
 GATCATCCGA GGCCTGCGTT CAGTTGGTGC CTCCAGA* 
>DL;IPD:MHC04702
IPD:MHC04702 Mafa-DQA1*26:01 687 bases
 GGAGGTGAAG ACATAGTGGC TGACCACATT GCCTCTTACG GTGTAAACTT
 GTACCAGACT TACGGTCTCT CTGGCCAGTT CACTCATGAA TTTGATGGAG
 ACGAGCAGTT CTACGTGGAC CTGGAGAGGA AGGAGACTGT CTGGCGGTTG
 CCTCTGTTCA GCAAATTTGG AGGTTTTGAC CCGCAGGGTG CACTGAGAAA
 CTTGGCTGTG GGAAAACACA ACTTGAACAT CCTGATTAAA CACTCCAACT
 CTACTGCTGC TACCAATGAG GTTCCTGAGG TCACAGTGTT TTCCAAGTCT
 CCCGTGACAC TGGGTCACCC CAACACCCTC ATCTGTCTTG TGGACAACAT
 CTTTCCTCCT GTGGTGAACA TCACATGGTT GAGCAATGGG CACTCAGTCA
 CAGAAGGGGT TTCTGAGACC AGCTTCCTCT CCAAGAGTGA TCATTCCTTC
 TTCAAGATCA GTTACCTCAC CTTCCTCCCT TCTGCTGATG AGATTTATGA
 CTGCAGGGTG GAGCACTGGG GCCTGGACGA GCCTCTTCTG AAACACTGGG
 AGCCTGAGAT TCCAGCGCCC ATGTCAGAGC TCACAGAGAC TGTGGTCTGC
 GCCCTGGGGT TGTCTATGGG CCTCGTGGGC ATTGTGGTGG GGACCGTCTT
 GATCATCCGA GGCCTGCGTT CAGTTGGTGC CTCCAGA* 
>DL;IPD:MHC00277
IPD:MHC00277 Mafa-DQA1*26:01:01 768 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTTGCTC TGACCACCGT
 GATGAGCCCC TGCGGAGGTG AAGACATAGT GGCTGACCAC ATTGCCTCTT
 ACGGTGTAAA CTTGTACCAG ACTTACGGTC TCTCTGGCCA GTTCACTCAT
 GAATTTGATG GAGACGAGCA GTTCTACGTG GACCTGGAGA GGAAGGAGAC
 TGTCTGGCGG TTGCCTCTGT TCAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGGGAAAAC ACAACTTGAA CATCCTGATT
 AAACACTCCA ACTCTACTGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CACTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCACTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAGG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTAT GGGCCTCGTG GGCATTGTGG
 TGGGGACCGT CTTGATCATC CGAGGCCTGC GTTCAGTTGG TGCCTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC04126
IPD:MHC04126 Mafa-DQA1*26:01:02 768 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTCGCTC TGACCACCGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT GGCTGACCAC ATTGCCTCTT
 ACGGTGTAAA CTTGTACCAG ACTTACGGTC TCTCTGGCCA GTTCACTCAT
 GAATTTGATG GAGACGAGCA GTTCTACGTG GACCTGGAGA GGAAGGAGAC
 TGTCTGGCGG TTGCCTCTGT TCAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGGGAAAAC ACAACTTGAA CATCCTGATT
 AAACACTCCA ACTCTACTGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CACTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCACTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAGG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTAT GGGCCTCGTG GGCATTGTGG
 TGGGGACCGT CTTGATCATC CGAGGCCTGC GTTCAGTTGG TGCCTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC04699
IPD:MHC04699 Mafa-DQA1*26:01:03 687 bases
 GGAGGTGAAG ACATAGTGGC TGACCACATT GCCTCTTACG GTGTAAACTT
 GTACCAGACT TACGGTCTCT CTGGCCAGTT CACTCATGAA TTTGATGGAG
 ACGAGCAGTT CTACGTGGAC CTGGAGAGGA AGGAGACTGT CTGGCGGTTG
 CCTCTGTTCA GCAAATTTGG AGGTTTTGAC CCGCAGGGTG CACTGAGAAA
 CTTGGCTGTG GGAAAACACA ACTTGAACAT CCTGATTAAA CACTCCAACT
 CTACTGCTGC TACCAATGAG GTTCCTGAGG TCACAGTGTT TTCCAAGTCT
 CCCGTGACAC TGGGTCACCC CAACACCCTC ATCTGTCTTG TGGACAACAT
 CTTTCCTCCT GTGGTGAACA TCACATGGTT GAGCAATGGG CACTCAGTCA
 CAGAAGGGGT TTCTGAGACC AGCTTCCTCT CCAAGAGCGA TCATTCCTTC
 TTCAAGATCA GTTACCTCAC CTTCCTCCCT TCTGCTGATG AGATTTATGA
 CTGCAGGGTG GAGCACTGGG GCCTGGACGA GCCTCTTCTG AAACACTGGG
 AGCCTGAGAT TCCAGCGCCC ATGTCAGAGC TCACAGAGAC TGTGGTCTGC
 GCCCTGGGGT TGTCTATGGG CCTCGTGGGC ATTGTGGTGG GGACCGTCTT
 GATCATCCGA GGCCTGCGTT CAGTTGGTGC CTCCAGA* 
>DL;IPD:MHC01187
IPD:MHC01187 Mafa-DQA1*26:02 768 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTCACTC TGACCACCGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT GGCTGACCAC GTTGCCTCTT
 ACGGTGTAAA CTTGTACCAG ACTTACGGTC TCTCTGGCCA GTTCACTCAT
 GAATTTGATG GAGACGAGCA GTTCTACGTG GACCTGGAGA GGAAGGAGAC
 TGTCTGGCGG TTGCCTCTGT TCAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGGGAAAAC ACAACTTGAA CATCCTGATT
 AAACACTCCA ACTCTACTGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CGCTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCACTCGG TCACAGAAGG TGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAGG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTAT GGGCCTCGTG GGCATTGTGG
 TGGGGACCGT CTTGATCATC CGAGGCCTGC GTTCAGTTGG TGCCTCCAGA
 CACCAAGGAC CCTTGTGA*   
>DL;IPD:MHC02064
IPD:MHC02064 Mafa-DQA1*26:03 768 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTCGCTC TGACCACCGT
 GATGAGCCCC TGTGGAGGTG AAGACATAAT GGCTGACCAC GTTGCCTCTT
 ACGGTGTAAA CTTGTACCAG ACTTACGGTC TCTCTGGCCA GTACACCCAC
 GAATTTGATG GAGACGAGCA GTTCTACGTG GACCTGGAGA GGAAGGAGAC
 TGTCTGGCGG TTGCCTCTGT TCAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGGGAAAAC ACAACTTGAA CATCCTGATT
 AAACACTCCA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CGCTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCACTCGG TCACAGAAGG TGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAGG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTAT GGGCCTCGTG GGCATTGTGG
 TGGGGACCGT CTTGATCATC CGAGGCCTGC GTTCAGTTGG TGCCTCCAGA
 CACCAAGGAC CCTTGTGA*   
>DL;IPD:MHC03767
IPD:MHC03767 Mafa-DQA1*26:04:01 768 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTCGCTC TGACCACCGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT GGCTGACCAC GTTGCCTCTT
 ACGGTGTAAA CTTGTACCAG ACTTACGGTC TCTCTGGCCA GTACACCCAT
 GAATTTGATG GAGACGAGCA GTTCTACGTG GACCTGGAGA GGAAGGAGAC
 TGTCTGGCGG TTGCCTCTGT TCAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGTCAAAAC ACAACTTGAA CATCATGATT
 AAACGCTCCA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CACTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAGT
 GGGCGCTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG
 TGGGGACCGT CTTGATCATC CGAGGCCTGC GTTCAGTTGG TGCTTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC04712
IPD:MHC04712 Mafa-DQA1*26:04:02 687 bases
 GGAGGTGAAG ACATAGTGGC TGACCACGTT GCCTCTTACG GTGTAAACTT
 GTACCAGACT TACGGTCTCT CTGGCCAGTA CACCCATGAA TTTGATGGAG
 ACGAGCAGTT CTACGTGGAC CTGGAGAGGA AGGAGACTGT CTGGCGGTTG
 CCTCTGTTCA GCAAATTTGG AGGTTTTGAC CCGCAGGGTG CACTGAGAAA
 CTTGGCTGTG TCAAAACACA ACTTGAACAT CATGATTAAA CGCTCCAACT
 CTACCGCTGC TACCAATGAG GTTCCTGAGG TCACAGTGTT TTCCAAGTCT
 CCCGTGACAC TGGGTCACCC CAACACCCTC ATCTGTCTTG TGGACAACAT
 CTTTCCTCCT GTGGTGAACA TCACATGGTT GAGCAGTGGG CGCTCAGTCA
 CAGAAGGGGT TTCTGAGACC AGCTTCCTCT CCAAGAGTGA TCATTCCTTC
 TTCAAGATCA GTTACCTCAC CTTCCTCCCT TCTGCTGATG AGATTTATGA
 CTGCAAGGTG GAGCACTGGG GCCTGGACGA GCCTCTTCTG AAACACTGGG
 AGCCTGAGAT TCCAGCGCCC ATGTCAGAGC TCACAGAGAC TGTGGTCTGC
 GCCCTGGGGT TGTCTGTGGG CCTCGTGGGC ATTGTGGTGG GGACCGTCTT
 GATCATCCGA GGCCTGCGTT CAGTTGGTGC CTCCAGA* 
>DL;IPD:MHC03774
IPD:MHC03774 Mafa-DQA1*26:05 768 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTCACTC TGACCACCGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT GGCTGACCAC GTTGCCTCTT
 ACGGTGTAAA CTTGTACCAG ACTTACGGTC TCTCTGGCCA GTACACCCAT
 GAATTTGATG GAGACGAGCA GTTCTACGTG GACCTGGAGA GGAAGGAGAC
 TGTCTGGCGG TTGCCTCTGT TCAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGTCAAAAC ACAACTTGAA CATCATGATT
 AAACGCTCCA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CACTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAGT
 GGGCACTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG
 TGGGGACCGT CTTGATCATC CGAGGCCTGC GTTCAGTTGG TGCTTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC03814
IPD:MHC03814 Mafa-DQA1*26:06 768 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTTGCTC TGACCACCGT
 GATGAGCCCC TGCGGAGGTG AAGACATAGT GGCTGACCAC ATTGCCTCTT
 ACGGTGTAAA CTTGTACCAG ACTTACGGTC TCTCTGGCCA GTTCACTCAT
 GAATTTGATG GAGACGAGCA GTTCTACGTG GACCTGGAGA GGAAGGAGAC
 TGTCTGGCGG TTGCCTCTGT TCAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGGGAAAAC ACAACTTGAA CATCCTGATT
 AAACACTCCA ACTCTACTGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCATGA CACTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGTAAT
 GGGCACTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG
 TGGGGACCGT CTTGATCATC CGAGGCCTGC GTTCAGTTGG TGCTTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC04706
IPD:MHC04706 Mafa-DQA1*26:07 687 bases
 GGAGGTGAAG ACATAGTGGC TGACCACGTT GCCTCTTACG GTGTAAACTT
 GTACCAGACT TACGGTCTCT CTGGCCAGTA CACCCATGAA TTTGATGGAG
 ACGAGCAGTT CTACGTGGAC CTGGAGAGGA AGGAGACTGT CTGGCGGTTG
 CCTCTGTTCA GCAAATTTGG AGGTTTTGAC CCGCAGGGTG CACTGAGAAA
 CTTGGCTGTG TCAAAACACA ACTTGAACAT CATGATTAAA CGCTCCAACT
 CTACCGCTGC TACCAATGAG GTTCCTGAGG TCACAGTGTT TTCCAAGTCT
 CCCGTGACAC TGGGTCACCC CAACACCCTC ATCTGTCTTG TGGACAACAT
 CTTTCCTCCT GTGGTGAACA TCACATGGTT GAGCAATGGG CACTCAGTCA
 CAGAAGGGGT TTCTGAGACC AGCTTCCTCT CCAAGAGTGA TCATTCCTTC
 TTCAAGATCA GTTACCTCAC CTTCCTCCCT TCTGCTGATG AGATTTATGA
 CTGCAAGGTG GAGCACTGGG GCCTGGACGA GCCTCTTCTG AAACACTGGG
 AGCCTGAGAT TCCAGCGCCC ATGTCAGAGC TCACAGAGAC TGTGGTCTGC
 GCCCTGGGGT TGTCTGTGGG CCTCGTGGGC ATTGTGGTGG GGACCGTCTT
 GATCATCCGA GGCCTGCGTT CAGTTGGTGC CTCCAGA* 
