>DL;IPD:MHC04306
IPD:MHC04306 Mafa-AG*01:01 822 bases
 GCTCCCACTC CATGAGGTAT TTCTACACCG CCGTGTCCCG GCCCGGCCGC
 TGGGAGCCCC GCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCC AGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGGTGGAGCA GGAGGGGCCG GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CACAGACCTA CCAAGGGAAC CTGCGGACCC TGCTCCGCTA
 CTACAACCAG AGCGAGGCCA GGTCTCACAC CATCCAGAAG ATGTACGGCT
 GCGACCTGGG GCCCGACGGG CGCCTCCTCC GCGGGTATGA ACAGTTCGCC
 TACGACGGCA GGGATTACAT CATCCTGAAC GAGGACCTGC GCTCCTGGAC
 GGCCGCGGAC ATGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCGGCCC
 GTGCGGCGGA GCAGCACAGA ACCTACCTGG AGGGCGAGTG CCTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGGACCC
 CCCCAAGACA CACGTGACCC ACCACCCCAT CTCTGACCAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG
 CAGCGGGATG GAGAGGAACA AACTCAGGAC ACAGAGCTCA TGGAGACCAG
 GCCTACAGGG AATGGAACCT TCCAGAAGTG GGCGGCTGTG GTGGTGCCTT
 CTGGAGAGGA GCAGAGATAC ACCTGTCATG TGCAACATGA GGGTCTGCCC
 AAGCCCCTCA CCTTGAGATG GG*  
>DL;IPD:MHC04426
IPD:MHC04426 Mafa-AG*01:02 546 bases
 GCTCCCACTC CATGAGGTAT TTCTACACCG CCGTGTCCCG GCCCGGCCGC
 TGGGAGCCCC GCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGGTGGAGCA GGAGGGGCCG GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CACAGACCTA CCAAGGGAAC CTGCGGACCC TGCTCCGCTA
 CTACAACCAG AGCGAGGCCA GGTCTCACAC CGTCCAGAAG ATGTACGGCT
 GCGACCTGGG GCCCGACGGG CGCCTCCTCC GCGGGTATGA ACAGTTCGCC
 TACGACGGCA GGGATTACAT CATCCTGAAC GAGGACCTGC GCTCCTGGAC
 GGCCGCGGAC ATGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCGGCGG
 GTGTGGCGGA GCAGCACAGA ACCTACCTGG AGGGCGAGTG CCTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGG*
>DL;IPD:MHC04429
IPD:MHC04429 Mafa-AG*01:03 546 bases
 GCTCCCACTC CATGAGGTAT TTCTACACCG CCGTGTCCCG GCCCGGCCGC
 TGGGAGCCCC GCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCC AGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGGTGGAGCA GGAGGGGCCG GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CACAGACCTA CCAAGGGAAC CTGCGGACCC TGCTCCGCTA
 CTACAACCAG AGCGAGGCCA GGTCTCACAC CGTCCAGAAG ATGTACGGCT
 GCGACCTGGG GCCCGACGGG CGCCTCCTCC GCGGGTATGA ACAGTTCGCC
 TACGACGGCA GGGATTACAT CATCCTGAAC GAGGACCTGC GCTCCTGGAC
 GGCCGCGGAC ATGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCGGCGG
 GTGTGGCGGA GCAGCACAGA ACCTACCTGG AGGGCGAGTG CCTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGG*
>DL;IPD:MHC04432
IPD:MHC04432 Mafa-AG*01:04 546 bases
 GCTCCCACTC CATGAGGTAT TTCTACACCG CCGTGTCCCG GCCCGGCCGC
 TGGGAGCCCC GCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCC AGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGGTGGAGCA GGAGGGGCCG GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CACAGACCTA CCAAGGGAAC CTGCGGACCC TGCTCGGCTA
 CTACAACCAG AGCGAGGCCA GGTCTCACAC CGTCCAGAAG ATGTACGGCT
 GCGACCTGGG GCCAGACGGG CGCCTCCTCC GCGGGTATGA ACAGTTCGCC
 TACGACGGCA GGGATTACAT CATCCTGAAC GAGGACCTGC GCTCCTGGAC
 GGCCGCGGAC ATGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCGGCGG
 GTGTGGCGGA GCAGCACAGA ACCTACCTGG AGGGCGAGTG CCTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGG*
>DL;IPD:MHC03759
IPD:MHC03759 Mafa-AG*02:01 822 bases
 GCTCGCACTC CATGAGGTAT TTCTACACCT CCATGTCCCG GCCCGGCCGC
 GGGCAGCCCC GCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGGTGGAGCA GGAGGGTCCA GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CACAGACCTA CCGAGAGAAC CTGCGGACCC TGCTCCGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC CATCCAGAAG ATGTATGGCT
 GCGACCTGGG GCCAGACGGG CGCCTCCTCC GCGGGTATGA ACAGTTCGCC
 TACGACGGCA GGGATTACAT CATCCTGAAC GAGGACCTGC GCTCCTGGAC
 GGCCGCGGAC ATGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCGGCGG
 GTGCGGCGGA GCAGCACAGA ACCTACCTGG AGGGCGAGTG CCTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGGACCC
 CCCCAAGACA AATGTGACCC ACCACCCTGT CTCTGACTAC GAGGCCACCC
 TGAGGTGTTG GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG
 CAGCGGGATG GAGAGGAACA AACTGAGGAC ACAGAGCTCG TGGAGACCAG
 GCCTACAGGG GATGGAACCT TCCAGAAGTG GGCGGCTGTG GTGGTGCCTT
 CTGGAGAGGA GCAGAGATAC ACCTGTCATG TGCAACATGA GGGTCTGCCC
 GAGCCCCTCA CCTTGAGATG GG*  
>DL;IPD:MHC03843
IPD:MHC03843 Mafa-AG*03:01:01 1098 bases
 ATGGCGGTCA TGGCGCCCCG AACCCTCCTC CTGGTGCTCT CAGGGGTCCT
 GGCCCTGACC CAGCCCCGGG CGGGCTCGCA CTCCATGAGG TATTTCTACA
 CCGCCGTGTC CCGGCCCGGC CGCGGGCAGC CCCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGT CCAGAGTATT
 GGGACCGGGA GACACAGAAC ATGAAGACCG CGACACAGAC CTACCAAGCG
 AACCTGCGGA CCCTGCTCCG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCTTCCAG AAGATGTACG GCTGCGACCT GGGGCCAGAC GGGCGCCTCC
 TCCGCGGGTA TGAACAGTTC GCCTACGACG GCAGGGATTA CATCATCCTG
 AACGAGGACC TGCGCTCCTG GACCGCCGCG GACATGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CGGGTGCGGC GGAGCAGCAC AGAACCTACC
 TGGAGGGCGA GTGCCTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCCAAG ACAAATGTGA CCCACCACCC
 TGTCTCTGAC TACGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGAGAGGA ACAAACTGAG
 GACACAGAGC TCGTGGAGAC CAGGCCTACA GGGGATGGAA CCTTCCAGAA
 GTGGGCGGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA TACACCTGTC
 ATGTGCAACA TGAGGGTCTG CCCAAGCCCC TCACCTTGAG ATGGGAGCCA
 TCTTCCCAGT CTACCATCCT CATCGTAGGC ATCATTGCTG GCCTGGTTCT
 CCTTGGAACT GTGGTCACTG GAGCTGTGGT TGCTGCTGTG ATGTGGAGGA
 GGAAGAGCTA AGATAGATAA GGCGGGAGCT ACTCTCAGGC TGCAAGCAGT
 GACAGTGCCC AAGGTTCTGA TGTGTCTCTC ACGGCTTGTA AAGTGTGA*
>DL;IPD:MHC04274
IPD:MHC04274 Mafa-AG*03:01:02 546 bases
 GCTCGCACTC CATGAGGTAT TTCTACACCG CCGTGTCCCG GCCCGGCCGC
 GGGCAGCCCC GCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGGTGGAGCA GGAGGGTCCA GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CACAGACCTA CCAAGCGAAC CTGCGGACCC TGCTCCGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC CTTCCAGAAG ATGTACGGCT
 GCGACCTGGG GCCAGACGGG CGCCTCCTCC GCGGGTATGA ACAGTTCGCC
 TACGACGGCA GGGATTACAT CATCCTGAAC GAGGACCTGC GCTCCTGGAC
 GGCCGCGGAC ATGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCGGCGG
 GTGCGGCGGA GCAGCACAGA ACCTACCTGG AGGGCGAGTG CCTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGG*
>DL;IPD:MHC04420
IPD:MHC04420 Mafa-AG*03:01:03 546 bases
 GCTCGCACTC CATGAGGTAT TTCTACACCG CCGTGTCCCG GCCCGGCCGC
 GGGCAGCCCC GCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGGTGGAGCA GGAGGGTCCA GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CACAGACCTA CCAAGCGAAC CTGCGGACCC TGCTCCGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC CTTCCAGAAG ATGTACGGCT
 GCGACCTGGG GCCAGACGGG CGCCTCCTCC GCGGGTATGA ACAGTTCGCC
 TACGACGGCA GGGATTACAT CATCCTGAAC GAGGACCTGC GCTCCTGGAC
 GGCCGCGGAC ATGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCGGCGG
 GTGCGGCGGA GCAGCACAGA ACCTACCTGG AGGGCGAGTG CCTAGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGG*
>DL;IPD:MHC04277
IPD:MHC04277 Mafa-AG*03:02 546 bases
 GGCTCGCACT CCATGAGGTA TTTCTACACC GCCGTGTCCC GGCCCGGCCG
 CGGGCAGCCC CGCTTCATCG CCGTGGGCTA CGTGGACGAC ACGCAGTTCG
 TGCGGTTCGA CAGCGACGCC GAGAGTCCGA GGATGGAGCC GCGGGCGCCG
 TGGGTGGAGC AGGAGGGTCC AGAGTATTGG GACCGGGAGA CACAGAACAT
 GAAGACCGCG ACACAGACCT ACCAAGCGAA CCTGCGGACC CTGCTCCGCT
 ACTACAACCA GAGCGAGGCC GGGTCTCACA CCTTCCAGAA GACGTACGGC
 TGCGACCTGG GGCCAGACGG GCGCCTCCTC CGCGGGTATG AACAGTTCGC
 CTACGACGGC AGGGATTACA TCATCCTGAA CGAGGACCTG CGCTCCTGGA
 CGGCCGCGGA CATGGCGGCT CAGAACACCC AGCGCAAGTG GGAGGCGGCG
 GGTGCGGCGG AGCAGCACAG AACCTACCTG GAGGGCGAGT GCCTGGAGTG
 GCTCCGCAGA TACCTGGAGA ACGGGAAGGA GACGCTGCAG CGCGCG*
>DL;IPD:MHC03758
IPD:MHC03758 Mafa-AG*04:01 822 bases
 GCTCCCACTC CATGAGGTAT TTCTACACCG CCGTGTCCCG GCCCGGCCGC
 TGGGAGCCCC GCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCAGTTCGAC AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGGTGGAGCA GGAGGGACCG GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CACAGACCTA CCGAGTGAAC CTGCGGACCC TGCTCCGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC CGTCCAGAAG ATGTACGGCT
 GCGACCTGGG GCCCGACGGG CGCCTCCTCC GCGGGTATGA ACAGTTCGCC
 TACGACGGCA GTGATTACAT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC
 GGCCGCGGAC ATGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCGGCCC
 GTGCGGCGGA GCAGCACAGA ACCTACCTGG AGGGCGAGTG CCTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGGACCC
 CCCCAAGACA CATGTGACCC ACCACCCCGT CTCTGACCAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG
 CAGCGGGATG GAGAGGAACA AACTGAGGAC ACAGAGCTCG TGGAGACCAG
 GCCTACAGGG GATGGAACCT TCCAGAAGTG GGCGGCTGTG GTGGTGCCTT
 CTGGAGAGGA GCAGAGATAC ACCTGTCATG TGCAACATGA GGGTCTGCCC
 AAGCCCCACA CCTTGAGATG GA*  
>DL;IPD:MHC03765
IPD:MHC03765 Mafa-AG*04:02 822 bases
 GCTCCCACTC CATGAGGTAT TTCTACACCG CCGTGTCCCG GCCCGGCCGC
 TGGGAGCCCC GCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCAGTTCGAC AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGGTGGAGCA GGAGGGACCG GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CACAGACCTA CCGAGTGAAC CTGCGGACCC TGCTCCGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC CGTCCAGAAG ATGTACGGCT
 GCGACCTGGG GCCCGACGGG CGCCTCCTCC GCGGGTATGA ACAGTTCGCC
 TACGACGGCA GTGATTACAT CGCCCTGAAT GAGGACCTGC GCTCCTGGAC
 GGCCGCGGAC ATGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCGGCCC
 GTGCCGCGGA GCAGCACAGA ACCTACCTGG AGGGCGAGTG CCTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGGACCC
 CCCCAAGACA CATGTGACCC ACCACCCCGT CTCTGACCAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG
 CAGCGGGATG GAGAGGAACA AACTGAGGAC ACAGAGCTCG TGGAGACCAG
 GCCTACAGGG GATGGAACCT TCCAGAAGTG GGCGGCTGTG GTGGTGCCTT
 CTGGAGAGGA GCAGAGATAC ACCTGTCATG TGCAACATGA GGGTCTGCCC
 AAGCCCCTCA CCTTGAGATG GA*  
>DL;IPD:MHC03734
IPD:MHC03734 Mafa-AG*04:03 646 bases
 TGCTCTCAGG GGTCCTGGCC CTGACCCAGA CCCGGGCGGG CTCCCACTCC
 ATGAGGTATT TCTACACCGC CGTGTCCCGG CCCGGCCGCT GGGAGCCCCG
 CTTCATCGCC GTGGGCTACG TGGACGACAC GCAGTTCGTG CAGTTCGACA
 GCGACGCCGA GAGTCCGAGG ATGGAGCCGC GGGCGCCGTG GGTGGAGCAG
 GAGGGACCGG AGTATTGGGA CCGGGAGACA CAGAACATGA AGACCGCGAC
 ACAGACCTAC CGAGTGAACC TGCGGACCGC GCTCCGCTAC TACAACCAGA
 GCGAGGCCGG GTCTCACACA GTCCAGAAGA TGTATGGCTG CGACCTGGGG
 CCCGACGGGC GCCTCCTCCG CGGGTATGAA CAGTTCGCCT ACGACGGCAG
 TGATTACATC GCCCTGAATG AGGACCTGCG CTCCTGGACG GGCGCGGACA
 TGGCGGCTCA GAACACCCAG CGCAAGTGGG AGGCGGCCCG TGCCGCGGAG
 CAGCACAGAA CCTACCTGGA GGGCGAGTGC CTGGAGTGGC TCCGCAGATA
 CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CGCGGACCCC CCCAAGACAC
 ATGTGACCCA CCACCCCGTC TCTGACCATG AGGCCACCCT GAGGTG*
>DL;IPD:MHC04273
IPD:MHC04273 Mafa-AG*04:04:01 546 bases
 GGCTCCCACT CCATGAGGTA TTTCTACACC GCCGTGTCCC GGCCCGGCCG
 CTGGGAGCCC CTCTTCATCG CCGTGGGCTA CGTGGACGAC ACGCAGTTCG
 TGCAGTTCGA CAGCGACGCC GAGAGTCCGA GGATGGAGCC GCGGGCGCCG
 TGGGTGGAGC AGGAGGGGCC GGAGTATTGG GACCGGGAGA CACAGAACAT
 GAAGACCGCG ACACAGACCT ACCGAGTGAA CCTGCGGACC GCGCTCCGCT
 ACTACAACCA GAGCGAGGCC GGGTCTCACA CCGTCCAGAA AATGTACGGC
 TGCGACCTGG GGCCCGACGG GCGCCTCCTC CGCGGGTATG AACAGTTCGC
 CTACGACGGC AGTGATTACA TCGCCCTGAA CGAGGACCTG CGCTCCTGGA
 CGGCCGCGGA CATGGCGGCT CAGAACACCC AGCGCAAGTG GGAGGCGGCC
 CGTGCGGCGG AGCAGCACAG AACCTACCTG GAGGGCGAGT GCCTGGAGTG
 GCTCCGCAGA TACCTGGAGA ACGGGAAGGA GACGCTGCAG CGCGCG*
>DL;IPD:MHC04419
IPD:MHC04419 Mafa-AG*04:04:02 546 bases
 GCTCCCACTC CATGAGGTAT TTCTACACCG CCGTGTCCCG GCCCGGCCGC
 TGGGAGCCCC TCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCAGTTCGAC AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGGTGGAGCA GGAGGGGCCG GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CACAGACCTA CCGAGTGAAC CTGCGGACCG CGCTCCGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC CGTCCAGAAA ATGTACGGCT
 GCGACCTGGG GCCCGACGGG CGCCTCCTCC GCGGGTATGA ACAGTTCGCC
 TACGACGGCA GTGATTACAT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC
 GGCCGCGGAC ATGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCGGCCC
 GTGCGGCGGA GCAGCACAGA ACCTACCTGG AGGGCGAGTG CCTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACACTGCAGC GCGCGG*
>DL;IPD:MHC04301
IPD:MHC04301 Mafa-AG*04:05 822 bases
 GCTCCCACTC CATGAGGTAT TTCTACACCG CCGTGTCCCG GCCCGGCCGC
 TGGGAGCCCC GCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCAGTTCGAC AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGGTGGAGCA GGAGGGACCG GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CACAGACCTA CCGAGTGAAC CTGCGGACCC TGCTCCGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC CGTCCAGAAG ATGTATGGCT
 GCGACCTGGG GCCAGACGGG CGCCTCCTCC GCGGGTATGA ACAGTTCGCC
 TACGACGGCA GTGATTACAT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC
 GGCCGCGGAC ATGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCGGCCC
 GTGCCGCGGA GCAGCACAGA ACCTACCTGG AGGGCGAGTG CCTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGGACCC
 CCCCAAGACA CACGTGACCC ACCACCCCGT CTCTGACCAT GAGGCCACCC
 TGAGGTGTTG GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG
 CAGCGGGATG GAGGGGAACA AACTGAGGAC ACAGAGCTCG TGGAGACCAG
 GCCTACAGGG GATGGAACCT TCCAGAAGTG GGCGGCTGTG GTGGTGCCTT
 CTGGAGAGGA GCAGAGATAC ACCTGTCATG TGCAACATGA GGGTCTGCCC
 AAGCCCCTCA CCTTGAGATG GA*  
>DL;IPD:MHC04427
IPD:MHC04427 Mafa-AG*04:06 546 bases
 GCTCCCACTC CATGAGGTAT TTCTACACCG CCGTGTCCCG GCCCGGCCGC
 TGGGAGCCCC GCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCAGTTCGAC AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGAGCCGT
 GGGTGGAGCA GGAGGGGCCG GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CACAGACCTA CCGAGTGAAC CTGAGGACCG CGCTCCGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC CGTCCAGAAA ATGTATGGCT
 GCGACCTGGG GCCCGACGGG CGCCTCCTCC GCGGGTATGA ACAGTTCGCC
 TACGACGGCA GTGATTACAT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC
 GGCCGCGGAC ATGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCGGCCC
 GTGCGGCGGA GCAGCACAGA ACCTACCTGG AGGGCGAGTG CCTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGG*
>DL;IPD:MHC04431
IPD:MHC04431 Mafa-AG*04:07 546 bases
 GCTCCCACTC CATGAGGTAT TTCTACACCG CCGTGTCCCG GCCCGGCCGC
 TGGGAGCCGC GCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTTGAC AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGGTGGAGCA GGAGGGGCCG GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CACAGACCTA CCGAGGGAAC CTGCGGACCG CGCTCCGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC CATCCAGAAG ATGTACGGCT
 GCGACTTGGG ACCCGACGGG CGCCTCCTCC GCGGGTATGA ACAGTTCGCC
 TACGACGGCA GGGATTACAT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC
 GGCAGCGGAC TTGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCGGCCC
 GTGCGGCGGA GCAGCACAGA ACCTACCTGG AGGGCGAGTG CCTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGG*
>DL;IPD:MHC04638
IPD:MHC04638 Mafa-AG*04:08 546 bases
 GCTCCCACTC CATGAGGTAT TTCTACACCG CCGTGTCCCG GCCCGGCCGC
 TGGGAGCCCC GCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCC AGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGGTGGAGCA GGAGGGGCCG GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CACAGACCTA CCGAGTGAAC CTGCGGACCG CGCTCCGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC CGTCCAGAAA ATGTACGGCT
 GCGACCTGGG GCCCGACGGG CGCCTCCTCC GCGGGTATGA ACAGTTCGCC
 TACGACGGCA GTGATTACAT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC
 GGCCGCGGAC ATGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCGGCCC
 GTGCGGCGGA GCAGCACAGA ACCTACCTGG AGGGCGAGTG CCTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGG*
>DL;IPD:MHC04271
IPD:MHC04271 Mafa-AG*05:01:01 546 bases
 GGCTCCCACT CCATGAGGTA TTTCTACACC GCCGTGTCCC GGCCCGGCCG
 TCGGGAGCCC CTCTTCATCG CCGTGGGCTA CGTGGACGAC ACGCAGTTCG
 TGCGGTTCGA CAGCGACGCC GAGAGTCCGA GGATGGAGCC GCGGGCGCCG
 TGGGTGGAGC AGGAGGGTCC AGAGTATTGG GACCGGGAGA CACAGAACAT
 GAAGACCGCG ACACAGACCT ACCGAGGGAA CCTGCGGACC GCGCTCCGCT
 ACTACAACCA GAGCGAGGGG GGGTCTCACA CGATCCAGAA GATGTACGGC
 TGCGACCTGG GGCCCGACGG GCGCCTCCTC CGCGGGTATG AACAGTTCGC
 CTACGACGGC AGGGATTACA TCGCCCTGAA CGAGGACCTG CGCTCCTGGA
 CCGCCGCGGA CATGGCGGCT CAGTTCACCC AGCGGAAGTG GGAGGCGGCC
 CGTGCGGCGG AGCAGCACAG AACCTACCTG GAGGGCGAGT GCCTGGAGTG
 GCTCCGCAGA TACCTGGAGA ACGGGAAGGA GACGCTGCAG CGCGCG*
>DL;IPD:MHC04300
IPD:MHC04300 Mafa-AG*05:01:02 822 bases
 GCTCCCACTC CATGAGGTAT TTCTACACCG CCGTGTCCCG GCCCGGCCGT
 CGGGAGCCCC TCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGGTGGAGCA GGAGGGTCCA GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CACAGACCTA CCGAGGGAAC CTGCGGACCG CGCTCCGCTA
 CTACAACCAG AGCGAGGGGG GGTCTCACAC CATCCAGAAG ATGTACGGCT
 GCGACCTGGG GCCCGACGGG CGCCTCCTCC GCGGGTATGA ACAGTTCGCC
 TACGACGGCA GGGATTACAT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC
 CGCCGCGGAC ATGGCGGCTC AGTTCACCCA GCGGAAGTGG GAGGCGGCCC
 GTGCGGCGGA GCAGCACAGA ACCTACCTGG AGGGCGAGTG CCTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGGACCC
 CCCCAAGACA CATGTGACCC ACCACCCCGT CTCTGACTAC GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGGGATCAC ACTGACCTGG
 CAGCGGGATG GAGAGGAACA AACTGAAGAC ACAGAGCTCG TGGAGACCAG
 GCCTACAGGG GATGGAACCT TCCAGAAGTG GGCGGCTGTG GTGGTGCCTT
 CTGGAGAGGA GCAGAGATAC ACCTGTCATG TGCAGCATGA GGGTCTGCCC
 AAGCCTCTCA CCTTGAGATG GG*  
>DL;IPD:MHC04276
IPD:MHC04276 Mafa-AG*05:02:01 546 bases
 GGCTCCCACT CCATGAGGTA TTTCTACACC GCCGTGTCCC GGCCCGGCCG
 TCGGGAGCCC CTCTTCATCG CCGTGGGCTA CGTGGACGAC ACGCAGTTCG
 TGCGGTTCGA CAGCGACGCC GAGAGTCCGA GGATGGAGCC GCGGGCGCCG
 TGGGTGGAGC AGGAGGGTCC AGAGTATTGG GACCGGGAGA CACAGAACAT
 GAAGACCGCG ACACAGACCT ACCGAGTGAA CCTGCGGACC GCGCTCCGCT
 ACTACAACCA GAGCGAGGGG GGGTCTCACA CCATCCAGAA GATGTACGGC
 TGCGACCTGG GGCCCGACGG GCGCCTCCTC CGCGGGTATG AACAGTTCGC
 CTACGACGGC AGGGATTACA TCGCCCTGAA CGAGGACCTG CGCTCCTGGA
 CCGCCGCGGA CATGGCGGCT CAGTTCACCC AGCGGAAGTG GGAGGCAGCC
 CGTGCGGCGG AGCAGCACAG AACCTACCTG GAGGGCGAGT GCCTGGAGTG
 GCTCCGCAGA TACCTGGAGA ACGGGAAGGA GACGCTGCAG CGCGCG*
>DL;IPD:MHC04302
IPD:MHC04302 Mafa-AG*05:02:02 822 bases
 GCTCCCACTC CATGAGGTAT TTCTACACCG CCGTGTCCCG ACCCGGCCGT
 CGGGAGCCCC TCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGGTGGAGCA GGAGGGTCCA GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CACAGACCTA CCGAGTGAAC CTGCGGACCG CGCTCCGCTA
 CTACAACCAG AGCGAGGGGG GGTCTCACAC CATCCAGAAG ATGTACGGCT
 GCGACCTGGG GCCCGACGGG CGCCTCCTCC GCGGGTATGA ACAGTTCGCC
 TACGACGGCA GGGATTACAT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC
 CGCCGCGGAC ATGGCGGCTC AGTTCACCCA GCGGAAGTGG GAGGCGGCCC
 GTGCGGCGGA GCAGCACAGA ACCTACCTGG AGGGCGAGTG CCTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGGACCC
 CCCCAAGACA CATGTGACCC ACCACCCCGT CTCTGACTAC GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG
 CAGCGGGATG GAGAGGAACA AACTGAAGAC ACAGAGCTCG TGGAGACCAG
 GCCTACAGGG GATGGAACCT TCCAGAAGTG GGCGGCTGTG GTGGTGCCTT
 CTGGAGAGGA GCAGAGATAC ACCTGTCATG TGCGGCATGA GGGTCTGCCC
 AAGCCCCTCA CCTTGAGATG GG*  
>DL;IPD:MHC04424
IPD:MHC04424 Mafa-AG*05:02:03 546 bases
 GCTCCCACTC CATGAGGTAT TTCTACACCG CCGTGTCCCG GCCCGGCCGT
 CGGGAGCCCC TCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGGTGGAGCA GGAGGGTCCA GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CACAGACCTA CCGAGTGAAC CTGCGGACCG CGCTCCGCTA
 CTACAACCAG AGCGAGGGGG GGTCTCACAC CATCCAGAAG ATGTACGGCT
 GCGACCTGGG GCCCGACGGG CGCCTCCTCC GCGGGTATGA ACAGTTCGCC
 TACGACGGCA GGGATTACAT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC
 CGCCGCGGAC ATGGCGGCTC AGTTCACCCA GCGGAAGTGG GAGGCGGCCC
 GTGCGGCGGA GCAGCACAGA ACCTACCTGG AGGGCGAGTG CCTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGG*
>DL;IPD:MHC04425
IPD:MHC04425 Mafa-AG*05:02:04 546 bases
 GCTCCCACTC CATGAGGTAT TTCTACACCG CCGTGTCCCG GCCCGGCCGT
 AGGGAGCCCC TCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGGTGGAGCA GGAGGGACCG GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CACAGACCTA CCGAGTGAAC CTGCGGACCG CGCTCCGCTA
 CTACAACCAG AGCGAGGGGG GGTCTCACAC CATCCAGAAG ATGTACGGCT
 GCGACCTGGG GCCAGACGGG CGCCTCCTCC GCGGGTATGA ACAGTTCGCC
 TACGACGGCA GGGATTACAT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC
 CGCCGCGGAC ATGGCGGCTC AGTTCACCCA GCGGAAGTGG GAGGCGGCCC
 GTGCGGCGGA GCAGCACAGA ACCTACCTGG AGGGCGAGTG CCTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGG*
>DL;IPD:MHC04303
IPD:MHC04303 Mafa-AG*05:03 822 bases
 GCTCCCACTC CATGAGGTAT TTCTACACCG CCGTGTCCCG ACCCGGCCGT
 CGGGAGCCCC TCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGGTGGAGCA GGAGGGTCCA GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CACAGACCTA CCGAGTGAAC CTGCGGACCG CGCTCCGCTA
 CTACAACCAG AGCGAGGGGG GGTCTCACAC CATCCAGAAG ATGTACGGCT
 GCGACCTGGG GCCCGACGGG CGCCTCCTCC GCGGGTATGA ACAGTTCGCC
 TACGACGGCA GGGATTACAT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC
 CGCCGCGGAC ATGGCGGCTC AGTTCACCCA GCGGAAGTGG GAGGCGGCCC
 GTGCGGCGGA GCAGCACAGA ACCTACCTGG AGGGCGAGTG CCTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGGACCC
 CCCCAAGACA CATGTGACCC ACCACCCCGT CTCTGACTAC GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG
 CAGCGGGATG GAGAGGAACA AACTGAAGAC ACAGAGCTCG TGGAGACCAG
 GCCTACAGGG GATGGAACCT TCCAGAAGTG GGCGGCTGCG GTGGTGCCTT
 CTGGAGAGGA GCAGAGATAC ACCTGTCATG TGCGGCATGA GGGTCTGCCC
 AAGCCCCTCA CCTTGAGATG GG*  
>DL;IPD:MHC04304
IPD:MHC04304 Mafa-AG*05:04 822 bases
 GCTCCCACTC CATGAGGTAT TTCTACACCG CCGTGTCCCG GCCCGGCCGT
 CGGGAGCCCC TCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTTGAC AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGGTGGAGCA GGAGGGGCCG GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CACAGACCTA CCGAGGGAAC CTGCGGACCG CGCTCCGCTA
 CTACAACCAG AGCGAGGGCG GGTCTCACAC CATCCAGAAG ATGTACGGCT
 GCGACCTGGG GCCCGACGGG CGCCTCCTCC GCGGGTATGA ACAGTTAGCC
 TACGACGGCA GGGATTACAT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC
 GGCCGCGGAC ATGGCGGCTC AGTTCACCCA GCGGAAGTGG GAGGCGGCCC
 GTGCGGCGGA GCAGCACAGA ACCTACCTGG AGGGCAAGTG CCTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGGACCC
 CCCCAAGACA CATGTGACCC ACCACCCCGT CTCTGACTAC GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG
 CAGCGGGATG GAGAGGAACA AACTGAGGAC ACAGAGCTCG TGGAGACCAG
 GCCTACAGGG GATGGAACCT TCCAGAAGTG GGCGGCTGTG GTGGTGCCTT
 CTGGAGAGGA GCAGAGATAC ACCTGTCATG TGCAGCATGA GGGTCTGCCC
 AAGCCCCTCA CCTTGAGATG GG*  
>DL;IPD:MHC04428
IPD:MHC04428 Mafa-AG*05:05 546 bases
 GCTCCCACTC CATGAGGTAT TTCTACACCG CCGTGTCCCG GCCCGGCCGT
 CGGGAGCCCC TCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGGTGGAGCC GGAGGGGCCG GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CACAGACCTA CCGAGGGAAC CTGCGGACCG CGCTCCGCTA
 CTACAACCAG AGCGAGGGGG GGTCTCACAC CATCCAGAAG ATGTACGGCT
 GCGACCTGGG GCCCGACGGG CGCCTCCTCC GCGGGTATGA ACAGTTCGCC
 TACGACGGCA GGGATTACAT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC
 CGCCGCGGAC ATGGCGGCTC AGTTCACCCA GCGGAAGTGG GAGGCGGCCC
 GTGCGGCGGA GCAGCACAGA ACCTACCTGG AGGGCGAGTG CCTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGG*
>DL;IPD:MHC03842
IPD:MHC03842 Mafa-AG*06:01 1097 bases
 ATGGCGGTCA TGGCGCCCCG AACCCTCCTC CTGGTGCTCT CAGGGGTCCT
 GGCCCTGACC CAGACCCGGG CGGGCTCTCA CTCCTTGAGG TATTTCTACA
 CCTCCATGTC CCGGCCCGGC CGCTGGGAGC CCCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCAC CGTGGGTGGA GCAGGAGGGT CCAGAGTATT
 GGGACCGGGA GACACAGAAC ATGAAGACCG CGACACAGAC CTACCGAGTG
 AACCTGCGGA CCCTGCTCCG CTACTACAAC CAGAGCCAGG GCGGGTCTCA
 CACCATCCAG AAGATGTACG GCTGCGACCT GGGGCCCGAC GGGCGCCTCC
 TCCGCGGGCA TGAACAGTTC GCCTACGATG GCAGGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCCGCG GACATGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCAG AGGATGTGGC GGAGCAGCAC AGAACCTACC
 TGGAGGGCGA GTGCCTGGAG TCGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCCAAG ACACATGTGA CCCACCACCC
 TGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGGGAT CACACTGACC TGGCAGCGGG ATGGAGAGGA ACAAACTCAG
 GACACGGAGC TCGTGGAGAC CAGGCCTACA GGGGATGGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA TACACCTGTC
 ATGTGCAACA TGAGGGTCTG CCCAAGCCCC TCACCTTGAG ATGGGAGCCG
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATCATTGCTG GCCTGGTTCT
 GCTTGGAACT GTGGTCACTG GAGCGGTGGT TGCTGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGATAGATAA GGCGGGAGCT ACTCTCAGGC TGCAAGCAGT
 GACAGTGCCC AAGGTTCTGA TGTGTCTCTC ACGGCTTTAA AGTGTGA*
>DL;IPD:MHC04269
IPD:MHC04269 Mafa-AG*06:02 546 bases
 GGCTCTCACT CCATGAGGTA TTTCTACACC TCCATGTCCC GGCCCGGCCG
 CTGGGAGCCC CGCTTCATCG CCGTGGGCTA CGTGGACGAC ACGCAGTTCG
 TGCGGTTCGA CAGCGACGCC GAGAGTCCGA GGATGGAGCC GCGGGCGCCG
 TGGGTGGAGC AGGAGGGTCC AGAGTATTGG GACCGGGAGA CACAGAACAT
 GAAGACCGCG ACACAGACCT ACCGAGTGAA CCTGCGGACC CTGCTCCGCT
 ACTACAACCA GAGCCAGGGC GGGTCTCACA CCATCCAGAA GATGTACGGC
 TGCGACCTGG GGCCCGACGG GCGCCTCCTC CGCGGGCATG AACAGTTCGC
 CTACGATGGC AGGGATTACA TCGCCCTGAA CGAGGACCTG CGCTCCTGGA
 CGGCCGCGGA CATGGCGGCT CAGAACACCC AGCGCAAGTG GGAGGCGGAG
 GATGTGGCGG AGCAGCACAG AACCTACCTG GAGGGCGAGT GCCTGGAGTC
 GCTCCGCAGA TACCTGGAGA ACGGGAAGGA GACGCTGCAG CGCGCG*
>DL;IPD:MHC04307
IPD:MHC04307 Mafa-AG*06:03 822 bases
 GCTCCCACTC CATGAGGTAT TTCTACACCT CCATGTCCCG GCCCGGCCGC
 TGGGAGCCCC GCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGGTGGAGCA GGAGGGGCCG GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CACAGACCTA CCGAGTGAAC CTGCGGACCC TGCTCCGCTA
 CTACAACCAG AGCCAGGGCG GGTCTCACAC CATCCAGAAG ATGTACGGCT
 GCGACCTGGG GCCCGACGGG CGCCTCCTCC GCGGGCATGA ACAGTTCGCC
 TACGATGGCA GGGATTACAT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC
 GGCCGCGGAC ATGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCGGCGG
 GTGTGGCGGA GCAGCACAGA ACCTACCTGG AGGGCGAGTG CCTGGAGTCG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGGACCC
 CCCCAAGACA CATGTGACCC ACCACCCCGT CTCTGACCAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGGGATCAC ACTGACCTGG
 CAGCGGGATG GAGAGGAACA AACTCAGGAC ACGGAGCTCG TGGAGACCAG
 GCCTACAGGG GATGGAACCT TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT
 CTGGAGAGGA GCAGAGATAC ACCTGTCATG TGCAACATGA GGGTCTGCCC
 AAGCCCCTCA CCTTGAGATG GG*  
>DL;IPD:MHC04639
IPD:MHC04639 Mafa-AG*06:04 546 bases
 GCTCTCACTC CATGAGGTAT TTCTACACCT CCATGTCCCG GCCCGGCCGC
 GGGCAGCCCC GCTTCATCTC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGGTGGAGCA GGAGGGTCCA GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CACAGACCTA CCGAGTGAAC CTGCGGACCG CGCTCCGCTA
 CTACAACCAG AGCCAGGGCA GGTCTCACAC CATCCAGAAG ATGTACGGCT
 GCGACCTGGG GCCCGACGGG CGCCTCCTCC GCGGGCATGA ACAGTTCGCC
 TACGACGGCA GGGATTACAT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC
 GGCCGCGGAC ATGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCGGAGG
 ATGTGGCGGA GCAGCACAGA ACCTACCTGG AGGGCGAGTG CCTGGAGTGG
 CTCCGCAGAC ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGG*
>DL;IPD:MHC04640
IPD:MHC04640 Mafa-AG*06:05 546 bases
 GCTCTCACTC CATGAGGTAT TTCTACACCT CCATGTCCCG GCCCGGCCGC
 GGGCAGCCCC GCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGGTGGAGCA GGAGGGTCCA GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CACAGACCTA CCGAGTGAAC CTGCGGACCC TGCTCCGCTA
 CTACAACCAG AGCCAGGGCA GGTCTCACAC CATCCAGAAG ATGTACGGCT
 GCGACCTGGG GCCCGACGGG CGCCTCCTCC GCGGGCATGA ACAGTTCGCC
 TACGACGGCA GTGATTACAT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC
 GGCCGCGGAC ATGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCGGAGG
 ATGTGGCGGA GCAGCACAGA ACCTACCTGG AGGGCGAGTG CCTGGAGTGG
 CTCCGCAGAC ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGG*
>DL;IPD:MHC04305
IPD:MHC04305 Mafa-AG*07:01:01 822 bases
 GCTCTCACTC CTTGAGGTAT TTCTACACCG CCGTGTCCCG GCCCGGCCGC
 GGACAGCCCC GCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGGTGGAGCA GGAGGGGCCG GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CGCAGACCTA CCGAGTGAAC CTGCGGACCC TGCTCCGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC CATCCAGAAG ATGTACGGCT
 GCGACCTGGG GCCCGACGGG CGCCGCCTCC GCGGGTATGA ACAGTTCGCC
 TACGATGGCA GGGATTACAT CGCCCTGAAC GAGGACCTGC GGTCCTGGAC
 GGCCGCGGAC ATGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCAGAGG
 ATGTGGCGGA GCAGCACAGA ACCTACCTGG AGGGCGAGTG CCTGGAGTCG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGGACCC
 CCCCAAGACA CATGTGACCC ACCACCCCGT CTCTGACCAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG
 CAGCGGGATG GAGAGGAACA AACTCAGGAC ACGGAGCTCG TGGAGACCAG
 GCCTACAGGG GATGGAACCT TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT
 CTGGAGAGGA GCAGAGATAC ACCTGTCATG TGCAACATGA GGGTCTGCCC
 AAGCCCCTCA CCTTGAGATG GG*  
>DL;IPD:MHC04308
IPD:MHC04308 Mafa-AG*07:01:02 822 bases
 GCTCTCACTC CTTGAGGTAT TTCTACACCG CCGTGTCCCG GCCCGGCCGC
 GGACAGCCCC GCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGGTGGAGCA GGAGGGGCCG GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CACAGACCTA CCGAGTGAAC CTGCGGACCC TGCTCCGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC CATCCAGAAG ATGTACGGCT
 GCGACCTGGG GCCCGACGGG CGCCGCCTCC GCGGGTATGA ACAGTTCGCC
 TACGATGGCA GGGATTACAT CGCCCTGAAC GAGGACCTGC GGTCCTGGAC
 GGCCGCGGAC ATGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCAGAGG
 ATGTGGCGGA GCAGCACAGA ACCTACCTGG AGGGCGAGTG CCTGGAGTCG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGGACCC
 CCCCAAGACA CATGTGACCC ACCACCCCGT CTCTGACCAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG
 CAGCGGGATG GAGAGGAACA AACTCAGGAC ACGGAGCTCG TGGAGACCAG
 GCCTACAGGG GATGGAACCT TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT
 CTGGAGAGGA GCAGAGATAC ACCTGTCATG TGCAACATGA GGGTCTGCCC
 AAGCCCCTCA CCTTGAGATG GG*  
>DL;IPD:MHC04430
IPD:MHC04430 Mafa-AG*07:02 546 bases
 GCTCTCACTC CTTGAGGTAT TTCTACACCT CCATGTCCCG GCCCGGCCGC
 GGGCAGCCCC GCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGGTGGAGCA GGAGGGGCCG GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CACAGACCTA CCGAGTGAAC CTGCGGACCC TGCTCCGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC CATCCAGAAG ATGTACGGCT
 GCGACCTGGG GCCCGACGGG CGCCGCCTCC GCGGGTATGA ACAGTTCGCC
 TACGATGGCA GGGATTACAT CGCCCTGAAC GGGGACCTGC GCTCCTGGAC
 CGCCGCGGAC ATGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCAGAGG
 ATGTAGCGGA GCAGCACAGA ACCTACCTGG AGGGCGAGTG CCTGGAGTCG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGG*
