>DL;IPD:MHC01316
IPD:MHC01316 Mafa-DPB1*01:01:01 777 bases
 ATGATGGTTC TGCAGGTTTC TGGGACCCCC CAGACAGTGG GTCTGATGGC
 GTTACTGATG GTGCTGCTCA CATCTGTGGT CCAGGGCAGG GCCACTCCAG
 AGAATTACCT GTACCAGGGA CGGCAGGAAT GCTACGCGTT TAATGGGACA
 CAGCGCTTCC TGGAGAGACA CATCTACAAC CGGGAGGAGT ACGCGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 CTGTGGAATA CTGGAACAGC CAGAAGGACC GCCTGGAGGA GAAGCGGGCA
 GTGGTGGACA CGGTGTGCAG ACACAACTAC GAGTTGGACG AGGCCGTGAC
 CCTGCAGCGC CGAGTCCAGC CGAGGGTGAA CATCGCCCCC TCCAAGAAGG
 GTCCCTTACA GCACCACAAC CTGCTCGTCT GCCATGTGAC AGATTTCTAC
 CCAGGCAGCA TTCAAGTCCG ATGGTTCCTG AATGGACAGG AGGAAACAAC
 TGGGGTCGTG TCCACCAACC TGATCCGTAA TGGAGACTGG ACCTTCCAGA
 TCCTGGTGAT GCTGGAAATG ACCCCCCAGC AGGGAGACGT CTACACCTGC
 CAAGTGGAGC ACCCCAGCCT GGACAGTCCT GTCACTGTGG AGTGGAAGGC
 ACAGTCTGAT TCTGCCCGGA GTAAGACGCT GACGGGAGCC GGGGGCTTCG
 TGCTGGGGCT CATCACCTGC GGAGTGGGCA TCTTCATGCA CAGGAGGAGC
 AAGAAAGTTC AACGAGGATC TGTATGA*  
>DL;IPD:MHC03726
IPD:MHC03726 Mafa-DPB1*01:01:02 777 bases
 ATGATGGTTC TGCAGGTTTC TGGGACCCCC CAGACAGTGG GTCTGATGGC
 GTTACTGATG GTGCTGCTCA CATCTGTGGT CCAGGGCAGG GCCACTCCAG
 AGAATTACCT GTACCAGGGA CGGCAGGAAT GCTACGCGTT TAATGGGACA
 CAGCGCTTCC TGGAGAGACA CATCTACAAC CGGGAGGAGT ACGCGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 CTGTGGAATA CTGGAACAGC CAGAAGGACC GCCTGGAGGA GAAGCGGGCA
 GTGGTGGACA CGGTGTGCAG ACACAACTAC GAGTTGGACG AGGCCGTGAC
 CCTGCAGCGC CGAGTCCAGC CGAGGGTGAA CATCGCCCCC TCCAAGAAGG
 GTCCCTTACA GCACCACAAC CTGCTCGTCT GCCATGTGAC AGATTTCTAC
 CCAGGCAGCA TTCAAGTCCG ATGGTTCCTG AATGGACAGG AGGAAACAAC
 TGGGGTCGTG TCCACCAACC TGATCCGTAA TGGAGACTGG ACCTTCCAGA
 TCCTGGTGAT GCTGGAAATG ACCCCCCAGC AGGGAGACGT CTACACCTGC
 CAAGTGGAGC ACCCCAGCCT GGACAGTCCT GTCACTGTGG AGTGGAAGGC
 ACAGTCTGAT TCTGCCCGGA GTAAGACGCT TACGGGAGCC GGGGGCTTCG
 TGCTGGGGCT CATCACCTGT GGAGTGGGCA TCTTCATGCA CAGGAGGAGC
 AAGAAAGTTC AACGAGGATC TGTATAA*  
>DL;IPD:MHC01211
IPD:MHC01211 Mafa-DPB1*01:02:01 777 bases
 ATGATGGTTC TGCAGGTTTC TGCAGCCCCT AGGACAGTGG GTCTGATGGC
 GTTACTGATG GTGCTGCTCA CATCTGTGGT CCAGGGCAGG GCCACTCCAG
 AGAATTACCT GTACCAGGGA CGGCAGGAAT GCTACGCGTT TAATGGGACA
 CAGCGCTTCC TGGAGAGATA CATCTACAAC CGGGAGGAGT ACGCGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 CTGTGGAATA CTGGAACAGC CAGAAGGACC GCCTGGAGGA GAAGCGGGCA
 GTGGTGGACA CGATGTGCAG ACACAACTAC GAGCTGGACG AGGCCGTGAC
 CCTGCAGCGC CGAGTCCAGC CGAGGGTGAA CATCGCCCCC TCCAAGAAGG
 GTCCCTTACA GCACCATAAC CTGCTCGTCT GCCATGTGAC AGATTTCTAC
 CCAGGCAGCA TTCAAGTCCG ATGGTTCCTG AATGGACAGG AGGAAACAAC
 TGGGGTCGTG TCCACCAACC TGATCCGTAA TGGAGACTGG ACCTTCCAGA
 TCCTGGTGAT GCTGGAAATG ACCCCCCAGC AGGGAGACGT CTACACCTGC
 CAAGTGGAGC ACCCCAGCCT GGACAGTCCT GTCACCGTGG AGTGGAAGGC
 ACAGTCTGAT TCTGCCCGGA GTAAGACGCT GACGGGAGCC GGGGGCTTCG
 TGCTGGGGCT CATCATCTGT GGAGTGGGCA TCTTCATGCA CAGGAGGAGC
 AAGAAAGTTC AACGAGGATC TGTATAA*  
>DL;IPD:MHC03741
IPD:MHC03741 Mafa-DPB1*01:02:02 777 bases
 ATGATGGTTC TGCAGGTTTC TGCAGCCCCT AGGACAGTGG GTCTGATGGC
 GTTACTGATG GTGCTGCTCA CATCTGTGGT CCAGGGCAGG GCCACTCCAG
 AGAATTACCT GTACCAGGGA CGGCAGGAAT GCTACGCGTT TAATGGGACA
 CAGCGCTTCC TGGAGAGATA CATCTACAAC CGGGAGGAGT ACGCGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 CTGTGGAATA CTGGAACAGC CAGAAGGACC GCCTGGAGGA GAAGCGGGCA
 GTGGTGGACA CGATGTGCAG ACACAACTAC GAGCTGGACG AGGCCGTGAC
 CCTGCAGCGC CGAGTCCAGC CGAGGGTGAA CATCGCCCCC TCCAAGAAGG
 GTCCCTTACA GCACCACAAC CTGCTCGTCT GCCATGTGAC AGATTTCTAC
 CCAGGCAGCA TTCAAGTCCG ATGGTTCCTG AATGGACAGG AGGAAACAAC
 TGGGGTCGTG TCCACCAACC TGATCCGTAA TGGAGACTGG ACCTTCCAGA
 TCCTGGTGAT GCTGGAAATG ACCCCCCAGC AGGGAGACGT CTACACCTGC
 CAAGTGGAGC ACCCCAGCCT GGACAGTCCT GTCACCGTGG AGTGGAAGGC
 ACAGTCTGAT TCTGCCCGGA GTAAGACGCT GACGGGAGCC GGGGGCTTCG
 TGCTGGGGCT CATCATCTGT GGAGTGGGCA TCTTCATGCA CAGGAGGAGC
 AAGAAAGTTC AACGAGGATC TGTATAA*  
>DL;IPD:MHC01317
IPD:MHC01317 Mafa-DPB1*01:03 265 bases
 GAGAATTACC TGTACCAGGG ACGGCAGGAA TGCTACGCGT TTAATGGGAC
 ACAGCGCTTC CTGGAGAGAT ACATCTACAA CCGGGAGGAG TACGCGCGCT
 TCGACAGCGA CGTGGGGGAG TTCCGGGCGG TGACGGAGCT GGGGCGGCCT
 GCTGTGGAAT ACTGGAACAG CCAGAAGGAC CGTCTGGAGG AGAAGCGGGC
 AGTGGTGGAC ACGGTGTGCA GACACAACTA CGAGTTGGAC GAGGCCGTGA
 CCCTGCAGCG CCGAG*   
>DL;IPD:MHC01319
IPD:MHC01319 Mafa-DPB1*01:04 265 bases
 GAGAATTACC TGTACCAGGG ACGGCAGGAA TGCTACGCGT TTAATGGGAC
 ACAGCGCTTC CTGGAGAGAT ACATCTACAA CCGGGAGGAG TACGCGCGCT
 TCGACAGCGA CGTGGGGGAG TTCCGGGCGG TGACGGAGCT GGGGCGGCCT
 GCTGTGGAAT ACTGGAACAG CCAGAAGGAC TTCCTGGAGG AGAAGCGGGC
 AGTGGTGGAC ACGGTGTGCA GACACAACTA CGAGTTGGAC GAGGCCGTGA
 CCCTGCAGCG CCGAG*   
>DL;IPD:MHC01320
IPD:MHC01320 Mafa-DPB1*01:05 774 bases
 ATGGTTCTGC AGGTTTCTGG GACCCCCCAG ACAGTGGGTC TGATGGCGTT
 ACTGATGGTG CTGCTCACAT CTGTGGTCCA GGGCAGGGCC ACTCCAGAGA
 ATTACCTGTA CCAGGGACGG CAGGAATGCT ACGCGTTTAA TGGGACACAG
 CGCTTCCTGG AGAGATACAT CTACAACCGG GAGGAGTACG CGCGCTTCGA
 CAGCGACGTT GGGGAGTTCC GGGCGGTGAC GGAGCTGGGG CGGCCTGCTG
 TGGAACACTG GAACAGCCAG AAGGACTTCC TGGAGGAGAA GCGGGCAGTG
 GTGGACACGG TGTGCAGACA CAACTACGAG TTGGACGAGG CCGTGACCCT
 GCAGCGCCGA GTCCAGCCGA GGGTGAATGT CTCCCCTTCC AAGAAGGGGC
 CCTTACAGCA CCACAACCTG CTCGTCTGCC ACGTGACAGA TTTCTACCCA
 GGCAGCATTC AAGTCCGATG GTTCCTGAAT GGACAGGAGG AAACAACTGG
 GGTCGTGTCC ACCAACCTGA TCCGTAATGG AGACTGGACC TTCCAGATCC
 TGGTGATGCT GGAAATGACC CCCCAGCAGG GAGACGTCTA CACCTGCCAA
 GTGGAGCACC CCAGCCTGGA CAGTCCTGTC ACTGTGGAGT GGAAGGCACA
 GTCTGATTCT GCCCGGAGTA AGACACTGAC GGGAGCCGGG GGCTTCGTGC
 TGGGGCTCAT CACCTGTGGA GTGGGCATCT TCATGCACAG GAGGAGCAAG
 AAAGTTCAAC GAGGATCTGC ATAA*  
>DL;IPD:MHC01321
IPD:MHC01321 Mafa-DPB1*01:06 265 bases
 GAGAATTACC TGTACCAGGG ACGGCAGGAA TGCTACGCGT TTAATGGGAC
 ACAGCGCTTC CTGGAGAGAT ACATCTACAA CCGGGAGGAG TACGCGCGCT
 TCGACAGCGA CGTTGGGGAG TTCCGGGCGG TGACGGAGCT GGGGCGGCCT
 GCTGTGGAAC ACTGGAACAG CCAGAAGGAC TTCCTGGAGG AGAAGCGGGC
 AGTGGTGGAC ACGATGTGCA GACACAACTA CGAGTTGGAC GAGGCCGTGA
 CCCTGCAGCG CCGAG*   
>DL;IPD:MHC04123
IPD:MHC04123 Mafa-DPB1*01:07 777 bases
 ATGATGGTTC TGCAGGTTTC TGGGACCCCC CAGACAGTGG GTCTGATGGC
 GTTACTGATG GTGCTGCTCA CATCTGTGGT CCAGGGCAGG GCCACTCCAG
 AGAATTACCT GTACCAGGGA CGGCAGGAAT GCTACGCGTT TAATGGGACA
 CAGCGCTTCC TGGAGAGACA CATCTACAAC CGGGAGGAGT ACGCGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 CTGTGGAATA CTGGAACAGC CAGAAGGACC GCCTGGAGGA GAAGCGGGCA
 GTGGTGGACA CGGTGTGCAG ACACAACTAC GAGTTGGACG AGGCCGTGAC
 CCTGCAGCGC CGAGTCCAGC CGAGGGTGAA CATCGCCCCC TCCAAGAAGG
 GTCCCTTACA GCACCACAAC CTGCTCGTCT GCCATGTGAC AGATTTCTAC
 CCAGGCAGCA TTCAAGTCCG ATGGTTCCTG AATGGACAGG AGGAAACAGC
 TGGGGTCGTG TCCACCAACC TGATCCGTAA TGGAGACTGG ACCTTCCAGA
 TCCTGGTGAT GCTGGAAATG ACCCCCCAGC AGGGAGACGT CTACACCTGC
 CAAGTGGAGC ACCCCAGCCT GGACAGTCCT GTCACTGTGG AGTGGAAGGC
 ACAGTCTGAT TCTGCCCGGA GTAAGACGCT GACGGGAGCC GGGGGCTTCG
 TGCTGGGGCT CATCACCTGC GGAGTGGGCA TCTTCATGCA CAGGAGGAGC
 AAGAAAGTTC AACGAGGATC TGTATGA*  
>DL;IPD:MHC01322
IPD:MHC01322 Mafa-DPB1*02:01 265 bases
 GAGAATTACC TGTACCAGGG ACGGCAGGAA TGCTACGCGA TTAACGGGAC
 ACAGCGCTTC CTGGAGAGAC ACATCTACAA CCGGGAGGAG TTCATGCGCT
 TCGACAGCGA CGCCGGGGAG TACCGGGCGG TGACAGAGAT GGGACGGCCT
 ACTGCGGAAT ACTGCAACAG CCAGAAGGAC TTCCTGGAGG AGAAGCGGGC
 CGAGGTGGAC AGGGTGTGCA GACATAACTA CGAGGGGCAC GAGGCAGTGA
 CCCTGCGGCG CCGAG*   
>DL;IPD:MHC00273
IPD:MHC00273 Mafa-DPB1*02:02 777 bases
 ATGATGGTTC TGCAGGTATC TGCAGCCCCC AGGACAGTGG CTCTGACGGC
 ATTACTGATG GTGCTGCTCA CATCTGTGGT CCGGGGCAGG GCCACTCCAG
 AGAATTACCT GTACCAGGGA CGGCAGGAAT GCTACGCGAT TAACGGGACA
 CAGCGCTTCC TGGAGAGACA CATCTACAAC CGGGAGGAGT TCATGCGCTT
 CGACAGCGAC GCCGGGGAGT ACCGGGCGGT GACAGAGATG GGACGGCCTA
 CTGCGGAATA CTGGAACAGC CAGAAGGACC GCCTGGAGGA GAAGCGGGCC
 GAGGTGGACA GGGTGTGCAG ACATAACTAC GAGGGGCACG AGGCAGTGAC
 CCTGCGGCGC CGAGTCCAGC CGAGGGTAAA CATCGCCCCC TCCAAGAAGG
 GGCCCTTACA GCACCACAAC CTGCTCGTCT GCCATGTGAC AGATTTCTAC
 CCAGGCAGCA TTCAAGTCCG ATGGTTCCTG AATGGACAGG AGGAAACAGC
 TGGGGTTGTG TCCACCAACC TGATCCGTAA TGGAGACTGG ACCTTCCAGA
 TCCTGGTGAT GCTGGAAATG ACCCCCCAGC AGGGAGACGT CTACACCTGC
 CAAGTGGAGC ACCCCAGCCT GGACAGTCCT GTCATGGTGG AGTGGAAGGC
 ACAGTCTGAT TCTGCCCGGA GTAAGACGCT GACGGGAGCC GGGGGCTTCG
 TGCTGGGGCT CATCACCTGT GGAGTGGGCA TCTTCATGCA CAGGAGGAGC
 AAGAAAGTTC AACGAGGATC TGTATGA*  
>DL;IPD:MHC01346
IPD:MHC01346 Mafa-DPB1*02:03 264 bases
 AGAATTACCT GTACCAGGGA CGGCAGGAAT GCTACGCGAT TAACGGGACA
 CAGCGCTTCC TGGAGAGACA CATCTACAAC CGGGAGGAGT TCATGCGCTT
 CGACAGCGAC GCCGGGGAGT ACCGGGCGGT GACAGAGATG GGACGGCCTA
 CTGCGGAATA CTGGAACAGC CAGAAGGACC GCCTGGAGGA GAAGCGGTCC
 GAGGTGGACA GGGTGTGCAG ACATAACTAC GAGGGGCACG AGGCAGTGAC
 CCTGCGGCGC CGAG*   
>DL;IPD:MHC03725
IPD:MHC03725 Mafa-DPB1*02:04 777 bases
 ATGATGGTTC TGCAGGTATC TGCAGCCCCC AGGACAGTGG CTCTGACGGC
 ATTACTGATG GTGCTGCTCA CATCTGTGGT CCGGGGCAGG GCCACTCCAG
 AGAATTACCT GTACCAGGGA CGGCAGGAAT GCTACGCGAT TAACGGGACA
 CAGCGCTTCC TGGAGAGACA CATCTACAAC CGGGAGGAGT TCATGCGCTT
 CGACAGCGAC GCCGGGGAGT ACCGGGCGGT GACAGAGATG GGACGGCCTA
 GTGCGGAATA CTGGAACAGC CAGAAGGACC GCCTGGAGGA GAAGCGGGCC
 GAGGTGGACA GGGTGTGCAG ACATAACTAC GAGGGGCACG AGGCAGTGAC
 CCTGCGGCGC CGAGTCCAGC CGAGGGTAAA CATCGCCCCC TCCAAGAAGG
 GGCCCTTACA GCACCACAAC CTGCTCGTCT GCCATGTGAC AGATTTCTAC
 CCAGGAAGCA TTCAAGTCCG ATGGTTCCTG AATGGACAGG AGGAAACAGC
 TGGGGTTGTG TCCACCAACC TGATCCGTAA TGGAGACTGG ACCTTCCAGA
 TCCTGGTGAT GCTGGAAATG ACCCCCCAGC AGGGAGACGT CTACACCTGC
 CAAGTGGAGC ACCCCAGCCT GGACAGTCCT GTCATGGTGG AGTGGAAGGC
 ACAGTCTGAT TCTGCCCGGA GTAAGACGCT GACGGGAGCC GGGGGCTTCG
 TGCTGGGGCT CATCACCTGT GGAGTGGGCA TCTTCATGCA CAGGAGGAGC
 AAGAAAGTTC AACGAGGATC TGTATGA*  
>DL;IPD:MHC04124
IPD:MHC04124 Mafa-DPB1*02:05 777 bases
 ATGATGGTTC TGCAGGTATC TGCAGCCCTC AGGACAGTGG CTCTGACGGC
 ATTACTGATG GTGCTGCTCA CATCTGTGGT CCGGGGCAGG GCCACTCCAG
 AGAATTACCT GTACCAGGGA CGGCAGGAAT GCTACGCGAT TAACGGGACA
 CAGCGCTTCC TGGAGAGACA CATCTACAAC CGGGAGGAGT TCATGCGCTT
 CGACAGCGAC GCCGGGGAGT ACCGGGCGGT GACAGAGATG GGACGGCCTA
 CTGCGGAATA CTGGAACAGC CAGAAGGACC GCCTGGAGGA GAAGCGGGCC
 GAGGTGGACA GGGTGTGCAG ACATAACTAC GAGGGGCACG AGGCAGTGAC
 CCTGCGGCGC CGAGTCCAGC CGAGGGTAAA CATCGCCCCC TCCAAGAAGG
 GGCCCTTACA GCACCACAAC CTGCTCGTCT GCCATGTGAC AGATTTCTAC
 CCAGGCAGCA TTCAAGTCCG ATGGTTCCTG AATGGACAGG AGGAAACAGC
 TGGGGTTGTG TCCACCAACC TGATCCGTAA TGGAGACTGG ACCTTCCAGA
 TCCTGGTGAT GCTGGAAATG ACCCCCCAGC AGGGAGACGT CTACACCTGC
 CAAGTGGAGC ACCCCAGCCT GGACAGTCCT GTCATGGTGG AGTGGAAGGC
 ACAGTCTGAT TCTGCCCGGA GTAAGACGCT GACGGGAGCC GGGGGCTTCG
 TGCTGGGGCT CATCACCTGT GGAGTGGGCA TCTTCATGCA CAGGAGGAGC
 AAGAAAGTTC AACGAGGATC TGTATGA*  
>DL;IPD:MHC00274
IPD:MHC00274 Mafa-DPB1*03:01 777 bases
 ATGATGGTTC TGCAGGTATC TGCAGCCCCC AGGACAGTGG CTCTGACGGC
 ATTACTGATG GTGCTGCTCA CATCTGTGGT CCGGGGCAGG GCCACTCCAG
 AGAATTACCT GTACCAGGGA CGGCAGGAAT GCTACGCGAT TAACGGGACA
 CAGCGCTTCC TGGAGAGACA CATCTACAAC CGGGAGGAGT TCATGCGCTT
 CGACAGCGAC GTGGGGGAGT ACCGGGCGGT GACAGAGATG GGACGGCCTA
 CTGCGGAATA CTGCAACAGC CAGAAGGACA AACTGGAGGA GATGCGGGCA
 GTGGCGGACA GGATGTGCAG ACACAACTAC GAGGTGAACG AGGCTGTGAC
 CCTGCAGCGC CGAGTCCAGC CGAGGGTGAA CATCGCCCCC TCCAAGAAGG
 GGCCCTTACA GCACCACAAC CTGCTCGTCT GCCATGTGAC AGATTTCTAC
 CCAGGCAGCA TTCAAGTCCG ATGGTTCCTG AATGGACAGG AGGAAACAGC
 TGGGGTCGTG TCCACCAACC TGATCCGTAA TGGAGACTGG ACCTTCCAGA
 TCCTGGTGAT GCTGGAAATG ACCCCCCAGC AGGGAGATGT CTACACCTGC
 CAAGTGGAGC ACCCCAGCCT GGACAGTCCT GTCACTATGG AGTGGAAGGC
 ACAGTCTGAT TCTGCCCGGA GTAAGACGCT GACGGGAGCC GGGGGCTTCG
 TGCTGGGGCT CATCATCTGT GGAGTGGGCA TCTTCATGCA CAGGAGGAGC
 AAGAAAGTTC AACGAGGATC TGTATGA*  
>DL;IPD:MHC01323
IPD:MHC01323 Mafa-DPB1*03:02 265 bases
 GAGAATTACC TGTACCAGGG ACGGCAGGAA TGCTACGCGA TTAACGGGAC
 ACAGCGCTTC CTGGAGAGAC ACATCTACAA CCGGGAGGAG TTCATGCGCT
 TCGACAGCGA CGTGGGGGAG TACCGGGCGG TGACAGAGAT GGGACGGCCT
 ACTGCGGAAT ACTGCAACAG CCAGAAGGAC AAACTGGAGG AGATGCGGGC
 AGTGGCGGAC ACGGTGTGCA GACACAACTA CGAGGTGAAC GAGGCTGTGA
 CCCTGCAGCG CCGAG*   
>DL;IPD:MHC01174
IPD:MHC01174 Mafa-DPB1*03:03 777 bases
 ATGATGGTTC TGCAGGTATC TGCAGCCCCC AGGACAGTGG CTCTGACGGC
 ATTACTGATG GTGCTGCTCA CATCTGTGGT CCGGGGCAGG GCCACTCCAG
 AGAATTACCT GTACCAGGGA CGGATGGAAT GCTACGCGAT TAACGGGACA
 CAGCGCTTCC TGGAGAGACA CATCTACAAC CGGGAGGAGT TCATGCGCTT
 CGACAGCGAC GTGGGGGAGT ACCGGGCGGT GACAGAGATG GGACGGCCTA
 CTGCGGAATA CTGCAACAGC CAGAAGGACA AACTGGAGGA GATGCGGGCA
 GTGGCGGACA CGGTGTGCAG ACACAACTAC GAGGTGAACG AGGCTGTGAC
 CCTGCAGCGC CGAGTCCAGC CGAGGGTGAA CATCGCCCCC TCCAAGAAGG
 GGCCCTTACA GCACCACAAC CTGCTCGTCT GCCATGTGAC AGATTTCTAC
 CCAGGCAGCA TTCAAGTCCG ATGGTTCCTG AATGGACAGG AGGAAACAGC
 TGGGGTCGTG TCCACCAACC TGATCCGTAA TGGAGACTGG ACCTTCCAGA
 TCCTGGTGAT GCTGGAAATG ACCCCCCAGC AGGGAGATGT CTACACCTGC
 CAAGTGGAGC ACCCCAGCCT GGACAGTCCT GTCACTATGG AGTGGAAGGC
 ACAGTCTGAT TCTGCCCGGA GTAAGACGCT AACGGGAGCC GGGGGCTTCG
 TGCTGGGGCT CATCATCTGT GGAGTGGGCA TCTTCATGCA CAGGAGGAGC
 AAGAAAGTTC AACGAGGATC TGTATGA*  
>DL;IPD:MHC03727
IPD:MHC03727 Mafa-DPB1*03:04 777 bases
 ATGATGGTTC TGCAGGTTTC TGTGGTCCCC GGGACAGTGG CTCTGACGGC
 ATTACTGATG GTGCTGCTCA CATCTGTGGT CCGGGGCAGG GCCACTCCAG
 AGAATTACCT GTACCAGGGA CGGATGGAAT GCTACGCGAT TAACGGGACA
 CAGCGCTTCC TGGAGAGACA CATCTACAAC CGGGAGGAGT TCATGCGCTT
 CGACAGCGAC GTGGGGGAGT ACCGGGCGGT GACAGAGATG GGACGGCCTA
 CTGCGGAATA CTGCAACAGC CAGAAGGACA AACTGGAGGA GATGCGGGCA
 GTGGCGGACA CGGTGTGCAG ACACAACTAC GAGGTGAACG AGGCTGTGAC
 CCTGCAGCGC CGAGTCCAGC CGAGGGTGAA CATCGCCCCC TCCAAGAAGG
 GGCCCTTACA GCACCACAAC CTGCTCGTCT GCCATGTGAC AGATTTCTAC
 CCAGGCAGCA TTCAAGTCCG ATGGTTCCTG AATGGACAGG AGGAAACAGC
 TGGGGTCGTG TCCACCAACC TGATCCGTAA TGGAGACTGG ACCTTCCAGA
 TCCTGGTGAT GCTGGAAATG ACCCCCCAGC AGGGAGATGT CTACACCTGC
 CAAGTGGAGC ACCCCAGCCT GGACAGTCCT GTCACTATGG AGTGGAAGGC
 ACAGTCTGAT TCTGCCCGGA GTAAGACGCT AACGGGAGCC GGGGGCTTCG
 TGCTGGGGCT CATCATCTGT GGAGTGGGCA TCTTCATGCA CAGGAGGAGC
 AAGAAAGTTC AACGAGGATC TGTATGA*  
>DL;IPD:MHC01173
IPD:MHC01173 Mafa-DPB1*04:01 777 bases
 ATGATGGTTC TGCAGGTTTC TGGGACCCCC CAGACAGTGG GTCTGATGGC
 GTTACTGATG GTGCTGCTCA CATCTGTGGT CCAGGGCAGG GCCACTCCAG
 AGAATTACCT GTACCAGGTA CGGCAGGAAT GCTACGCGTT TAACGGGACA
 CAGCGCTACC TGAACAGACA GATCTACAAC CGGGAGGAGT TCGTGCGCTT
 CGACAGCGAC GTGGGGGAGT ACCGGGCGGT GACAGAGCTG GGACGGCCTA
 CTGCGGAATA CTGGAACAGC CAGAAGGACA TCCTGGAGGA GAACCGGGCA
 GTGGTGGACA GGGTGTGCAG ACACAACTAC GAGCTGGACG AGGCCGTGAC
 CCTGCAGCGC CGAGTCCAGC CGAGGGTGAA TGTCTCCCCT TCCAAGAAGG
 GGCCCTTACA GCACCACAAC CTGCTCGTCT GCCACGTGAC AGATTTCTAC
 CCAGGCAGCA TTCAAGTCCG ATGGTTCCTG AATGGACAGG AGGAAACAAC
 TGGGGTCGTG TCCACCAACC TGATCCGTAA TGGAGACTGG ACCTTCCAGA
 TCCTGGTGAT GCTGGAAATG ACCCCCCAGC AGGGAGACGT CTACACCTGC
 CAAGTGGAGC ACCCCAGCCT GGACAGTCCT GTCACTGTGG AGTGGAAGGC
 ACAGTCTGAT TCTGCCCGGA GTAAGACACT GACGGGAGCC GGGGGCTTCG
 TGCTGGGGCT CATCACCTGT GGAGTGGGCA TCTTCATGCA CAGGAGGAGC
 AAGAAAGTTC AACGAGGATC TGCATAA*  
>DL;IPD:MHC01318
IPD:MHC01318 Mafa-DPB1*05:01 265 bases
 GAGAATTACC TGTACCAGGT AAGGCAGGAA TGCTACGCGT TTAATGGGAC
 ACAGCGCTTC CTGGAGAGAT ACATCTACAA CCGGGAGGAG TACGCGCGCT
 TCGACAGCGA CGTGGGGGAG TTCCGGGCGG TGACAGAGCT GGGACGGCCT
 GCTGTGGAAT ACTGGAACAG CCAGAAGGAC CGCCTGGAGG AGAAGCGGGC
 AGTGGTGGAC ACGGTGTGCA GACACAACTA CGAACTGGAC GAGGCCGTGA
 CCCTGCAGCG CCGAG*   
>DL;IPD:MHC03648
IPD:MHC03648 Mafa-DPB1*05:02 777 bases
 ATGATGGTTC TGCAGGTTTC TGGGACCCCC CAGACAGTGG GTCTGATGGC
 GTTACTGATG GTGCTGCTCA CATCTGTGGT CCAGGGCAGG GCCACTCCAG
 AGAATTACCT GTACCAGGTA AGGCAGGAAT GCTACGCGTT TAATGGGACA
 CAGCGCTTCC TGGAGAGATA CATCTACAAC CGGGAGGAGT ACGCGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACAGAGCTG GGACGGCCTA
 CTGCGGAATA CTGGAACAGC CAGAAGGACA GACTGGAGGA GAGGCGGGCA
 GTGGTGGACA CGATGTGCAG ACACAACTAC GAACTGGACG AGGCCGTGAC
 CCTGCAGCGC CGAGTCCAAC CAAGGGTGAA CATTGCCCCC TCCAAGAAGG
 GTCCCTTACA GCACCACAAC CTGCTCGTCT GCCACGTGAC AGATTTCTAC
 CCAGGCAGCA TTCAAGTCCG ATGGTTCCTG AATGGACAGG AGGAAACAGC
 TGGGGTTGTG TCCACCAACC TGATCCGTAA TGGAGACTGG ACCTTCCAGA
 TCCTGGTGAT GCTGGAAATG ACCCCCCAGC AGGGAGACGT CTACACCTGC
 CAAGTGGAGC ACCCCAGCCT GGACAGTCCT GTCATGGTGG AGTGGAAGGC
 ACAGTCTGAT TCTGCCCGGA GTAAGACGCT GACGGGAGCC GGGGGCTTCG
 TGCTGGGGCT CATCACCTGT GGAGTGGGCA TCTTCATGCA CAGGAGAAGC
 AAGAAAGTTC AACGAGGATC TGTATGA*  
>DL;IPD:MHC01326
IPD:MHC01326 Mafa-DPB1*06:01 777 bases
 ATGATGGTTC TGCAGGTTTC TGGGACTCCC CAGACAGTGG GTCTGATGGC
 GTTACTGATG GTGCTGCTCA CATCTGTGGT CCAGGGCAGG GCCACTCCAG
 AGAATTACCT GTTCCAGTTA CGGCAGGAAT GCTACGCGTT TAACGGGACA
 CAGCGCTACC TGGAGAGATA CCTCTACAAC CGGGAGGAGT TCGTGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 ATGCGGAATA CTGGAACAGC CAGAAGGACA TCCTGGAGGA GATGCGGGCA
 GTGACGGACA CGGTGTGCAG ACACAACTAC GAGCTGGACG AGGCCGTGAC
 CCTGCAGCGC CGAGTCCAGC CGAGGGTGAA TGTCTCCCCT TCCAAGAAGG
 GGCCCTTACA GCACCACAAC CTGCTCGTCT GCCACGTGAC AGATTTCTAC
 CCAGGCAGCA TTCAAGTCCG ATGGTTCCTG AATGGACAGG AGGAAACAAC
 TGGGGTCGTG TCCACCAACC TGATCCGTAA TGGAGACTGG ACCTTCCAGA
 TCCTGGTGAT GCTGGAAATG ACCCCCCAGC AGGGAGACGT CTACACCTGC
 CAAGTGGAGC ACCCCAGCCT GGACAGTCCT GTCACTGTGG AGTGGAAGGC
 ACAGTCTGAT TCTGCCCGGA GTAAGACACT GACGGGAGCC GGGGGCTTCG
 TGCTGGGGCT CATCACCTGT GGAGTGGGCA TCTTCATGCA CAGGAGGAGC
 AAGAAAGTTC AACGAGGATC TGCATAA*  
>DL;IPD:MHC01327
IPD:MHC01327 Mafa-DPB1*06:02 265 bases
 GAGAATTACC TGTTCCAGTT ACGGCAGGAA TGCTATGCGT TTAATGGGAC
 ACAGCGCTAC CTGGAGAGAT ACCTCTACAA CCGGGAGGAG TTCGTGCGCT
 TCGACAGCGA CGTGGGGGAG TTCCGGGCGG TGACGGAGCT GGGGCGGCCT
 GATGCGGAAT ACTGGAACAG CCAGAAGGAC ATCCTGGAGG AGAGGCGGGC
 AGTGGTGGAC ACGATGTGCA GACACAACTA CGAGCTGGAC GAGGCCGTGA
 CCCTGCAGCG CCGAG*   
>DL;IPD:MHC01328
IPD:MHC01328 Mafa-DPB1*06:03 777 bases
 ATGATGGTTC TGGAGGTTTC TGCAGCCCCC GGGACAGTTG GTCTGATGGC
 GTTACTGATG GTACTGCTCA CATCTGTGGT CCAGGGCAGG GCCACTCCAG
 AGAATTACGT GTTCCAGGGA CGGCAGGAAT GCTACGCGTT TAACGGGACA
 CAGCGCTACC TGGAGAGATA CATCTACAAC CGGGAGGAGT TCGTGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGAGGT GACGGAGCTG GGGCGGCCTG
 ATGCGGAATA CTGGAACAGC CAGAAGGACC TCCTGGAGGA GATGCGGGCA
 GTGGTGGACA CGATGTGCAG ATACAACTAC GAACTGGACG AGGCCGTGAC
 CCTGCAGCGC CGAGTCCAGC CAAGGGTGAA CATCGCCCCC TCCAAGAAGG
 GGCCCTTACA GCACCACAAC CTGCTTGTCT GCCATGTGAC AGATTTCTAC
 CCAGGCAGCA TTCAAGTCCG ATGGTTCCTG AATGGACAGG AGGAAACAAC
 TGGGGTCGTG TCCACCAACC TGATCCGTAA TGGAGACTGG ACCTTCCAGA
 TCCTGGTGAT GCTGGAAATG ACCCCCCAGC AGGGAGACGT CTACACCTGC
 CAAGTGGAGC ACCCCAGCCT GGACAGTCCT GTCACCGTGG AGTGGAAGGC
 ACAGTCTGAT TCTGCCCGGA GTAAGACGCT GACGGGAGCC GGGGGCTTCG
 TGCTGGGGCT CATCATCTGT GGAGTGGGTA TCTTCATGCA CAGGAGGAGG
 AAGAAAGTTC AACGAGGATC TGTATAA*  
>DL;IPD:MHC01335
IPD:MHC01335 Mafa-DPB1*06:04 265 bases
 GAGAATTACG TGTACCAGGT ACGGCAGGAA TGCTACGCGT TTAACGGGAC
 ACAGCGCTAC CTGGAGAGAT ACATCTACAA CCGGGAGGAG TTCGTGCGCT
 TCGACAGCGA CGTGGGGGAG TTCCGGGCGG TGACGGAGCT GGGGCGGCCT
 GATGCGGAAT ACTGGAACAG CCAGAAGGAC ATCCTGGAGG AGAAGCAGGC
 AGTGGCGGGC ACGAGTTGCA GACACGACTA CGAGCTGGAC GAGGCCGTGA
 CCCTGCAGCG CCGAG*   
>DL;IPD:MHC01336
IPD:MHC01336 Mafa-DPB1*06:05 265 bases
 GAGAATTACG TGTACCAGTT ACGGCAGGAA TGCTACGCGT TTAATGGGAC
 ACAGCGCTAC CTGGAGAGAT ACCTCTACAA CCGGGAGGAG TTCGTGCGCT
 TCGACAGCGA CGTGGGGGAG TTCCGGGCGG TGACGGAGCT GGGGCGGCCT
 GATGCGGAAT ACTGGAACAG CCAGAAGGAC ATCCTGGAGG AGATGCGGGC
 AGTGACGGAC ACGGTGTGCA GACACAACTA CGAGCTGGAC GAGGCCGTGA
 CCCTGCAGCG CCGAG*   
>DL;IPD:MHC01337
IPD:MHC01337 Mafa-DPB1*06:06:01 777 bases
 ATGATGGTTC TGCAGGTTTC TGGGACCCCC CAGACAGTGG GTCTGATGGC
 GTTACTGATG GTGCTGCTCA CATCTGTGGT CCAGGGCAGG GCCACTCCAG
 AGAATTACCT GTACCAGTTA CGGCAGGAAT GCTATGCGTT TAATGGGACA
 CAGCGCTACC TGGAGAGATA CCTCTACAAC CGGGAGGAGT TCGTGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 ATGCGGAATA CTGGAACAGC CAGAAGGACA TCCTGGAGGA GATGCGGGCA
 GTGACGGACA CGGTGTGCAG ACACAACTAC GAGCTGGACG AGGCCGTGAC
 CCTGCAGCGC CGAGTCCAGC CGAGGGTGAA TGTCTCCCCT TCCAAGAAGG
 GGCCCTTACA GCACCACAAC CTGCTCGTCT GCCACGTGAC AGATTTCTAC
 CCAGGCAGCA TTCAAGTCCG ATGGTTCCTG AATGGACAGG AGGAAACAAC
 TGGGGTCGTG TCCACCAACC TGATCCGTAA TGGAGACTGG ACCTTCCAGA
 TCCTGGTGAT GCTGGAAATG ACCCCCCAGC AGGGAGACGT CTACACCTGC
 CAAGTGGAGC ACCCCAGCCT GGACAGTCCT GTCACTGTGG AGTGGAAGGC
 ACAGTCTGAT TCTGCCCGGA GTAAGACACT GACGGGAGCC GGGGGCTTCG
 TGCTGGGGCT CATCACCTGT GGAGTGGGCA TCTTCATGCA CAGGAGGAGC
 AAGAAAGTTC AACGAGGATC TGCATAA*  
>DL;IPD:MHC05126
IPD:MHC05126 Mafa-DPB1*06:06:02 264 bases
 AGAATTACCT GTACCAGTTA CGGCAGGAAT GCTACGCGTT TAATGGGACA
 CAGCGCTACC TGGAGAGATA CCTCTACAAC CGGGAGGAGT TCGTGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 ATGCGGAATA CTGGAACAGC CAGAAGGACA TCCTGGAGGA GATGCGGGCA
 GTGACGGACA CGGTGTGCAG ACACAACTAC GAGCTGGACG AGGCCGTGAC
 CCTGCAGCGC CGAG*   
>DL;IPD:MHC03676
IPD:MHC03676 Mafa-DPB1*06:07 264 bases
 AGAATTACCT GTACCAGGAA CGGCAGGAAT GCTACGCGTT TAATGGGACA
 CAGCGCTACC TGGACAGATA CATCTACAAC CGGGAGGAGT TCGTGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 ATGCGGAATA CTGGAACAGC CAGAAGGACT TCCTGGAGGA GAAGCGGGCA
 GAGGTGGACA CGGTGTGCAG ACACAACTAC GAGTTGGACG AGGCCGTGAC
 CCTGCAGCGC CGAG*   
>DL;IPD:MHC03728
IPD:MHC03728 Mafa-DPB1*06:08 777 bases
 ATGATGGTTC TGCAGGTTTC TGGGACCCCC CAGACAGTGG GTCTGATGGC
 GTTACTGATG GTGCTGCTCA CATCTGTGGT CCAGGGCAGG GCCACTCCAG
 AGAATTACCT GTACCAGGAA CGGCAGGAAT GCTACGCGTT TAATGGGACA
 CAGCGCTACC TGGACAGATA CATCTACAAC CGGGAGGAGT TCGTGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 ATGCGGAATA CTGGAACAGC CAGAAGGACA TCCTGGAGGA GAAGCGGGCC
 GAGGTGGACA CGGTGTGCAG ACACAACTAC GAGTTGGACG AGGCCGTGAC
 CCTGCAGCGC CGAGTCCAGC CGAGGGTGAA TGTTTCCCCC TCCAAGAAGG
 GTCCCTTACA GCACCACAAC CTGCTCGTCT GCCACGTGAC AGATTTCTAC
 CCAGGCAGCA TTCAAGTCCG ATGGTTCCTG AATGGACAGG AGGAAACAGC
 TGGGGTCGTG TCCACCAACC TCATCCGTAA TGGAGACTGG ACCTTCCAGA
 TCCTGGTGAT GCTGGAAATG ACCCCCCAGC AGGGAGATGT CTACACCTGC
 CAAGTGGAGC ACCCCAGCCT GGACAGTCCT GTCACTATGG AGTGGAAGGC
 ACAGTCTGAT TCTGCCCGGA GTAAGACGCT GACGGGAGCC GGGGGCTTCG
 TGCTGGGGCT CATCACCTGT GGAGTGGGCA TCTTCATGCA CAGGAGGAGC
 AAGAAAGTTC AACGAGGATC TGTATAA*  
>DL;IPD:MHC01214
IPD:MHC01214 Mafa-DPB1*07:01 777 bases
 ATGATGGTTC TGGAGGTTTC TGCAGCCCCC GGGACAGTTG GTCTGATGGC
 GTTACTGATG GTACTGCTCA CATCTGTGGT CCAGGGCAGG GCCACTCCAG
 AGAATTACGT GTTCCAGGGA CGGCAGGAAT GCTACGCGTT TAACGGGACA
 CAGCGCTACC TGGAGAGATA CATCTACAAT CGGGAAGAGT ACGTGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 ATGCGGAATA CTGGAACAGC CAGAAGGACC TCCTGGAGGA GATGCGGGCA
 GTGGTGGACA CGATGTGCAG ATACAACTAC GAACTGGACG AGGCCGTGAC
 CCTGCAGCGC CGAGTCCAGC CAAGGGTGAA CATTGCCCCC TCCAAGAAGG
 GGCCCTTACA GCACCACAAC CTGCTTGTCT GCCATGTGAC AGATTTCTAC
 CCAGGCAACA TTCAAGTCCG ATGGTTCCTG AATGGACAGG AGGAAACAAC
 TGGGGTCGTG TCCACCAACC TGATCCGTAA TGGAGACTGG ACCTTCCAGA
 TCCTGGTGAT GCTGGAAATG ACCCCCCAGC AGGGAGACGT CTACACCTGC
 CAAGTGGAGC ACCCCAGCCT GGACAGTCCT GTCACCGTGG AGTGGAAGGC
 ACAGTCTGAT TCTGCCCGGA GTAAGACGCT GACGGGAGCC GGGGGCTTCG
 TGCTGGGGCT CATCATCTGT GGAGTGGGTA TCTTCATGCA CAGGAGGAGG
 AAGAAAGTTC AACGAGGATC TGTATAA*  
>DL;IPD:MHC01329
IPD:MHC01329 Mafa-DPB1*08:01 265 bases
 GAGAATTACG TGTACCAGGG ACGGCTGGAA TGCTACGCGT TTAACGGGAC
 ACAGCGCTAC CTGGAGAGAT ACATCTACAA CCGGGAGGAG TACGCGCTCT
 TCGACAGCGA CGTGGGGGAG TTCCGGGCGG TGACGGAGCT GGGGCGGCCT
 GATGCGGAAT ACTGGAACAG CCAGAAGGAC CTCCTGGAGG AGATGCGGGC
 AGTGGTGGAC ACGATGTGCA GATACAACTA CGAACTGGAC GAGGCCGTGA
 CCCTGCAGCG CCGAG*   
>DL;IPD:MHC01330
IPD:MHC01330 Mafa-DPB1*08:02 265 bases
 GAGAATTACG TGTACCAGGG ACGGATGGAA TGCTACGCGT TTAACGGGAC
 ACAGCGCTAC CTGGAGAGAT ACATCTACAA CCGGGAGGAG TACGCGCGCT
 TCGACAGCGA CGTGGGGGAG TTCCGGGCGG TGACGGAGCT GGGGCGGCCT
 GATGCGGAAT ACTGGAACAG CCAGAAGGAC ATCCTGGAGG AGAAGCAGGC
 AGTGGCGGGC ACGAGTTGCA GACACGACTA CGAGCTGGAC GAGGCCGTGA
 CCCTGCAGCG CCGAG*   
>DL;IPD:MHC01216
IPD:MHC01216 Mafa-DPB1*08:03 265 bases
 GAGAATTACG TGTACCAGGG ACGGATGGAA TGCTACGCGT TTAACGGGAC
 ACAGCGCTAC CTGGAGAGAT ACATCTACAA CCGGGAGGAG TACGCGCTCT
 TCGACAGCGA CGTGGGGGAG TTCCGGGCGG TGACGGAGCT GGGGCGGCCT
 GATGCGGAAT ACTGGAACAG CCAGAAGGAC CTCCTGGAGG AGATGCGGGC
 AGTGGTGGAC ACGATGTGCA GATACAACTA CGAACTGGAC GAGGCCGTGA
 CCCTGCAGCG CCAAG*   
>DL;IPD:MHC02061
IPD:MHC02061 Mafa-DPB1*08:04 777 bases
 ATGATGGTTC TGCAGGTTTC TGGGACCCCC CAGACAGTGG GTCTGATGGC
 GTTACTGATG GTGCTGCTCA CATCTGTGGT CCAGGGCAGG GCCACTCCAG
 AGAATTACGT GTACCAGGGA CGGATGGAAT GCTACGCGTT TAACGGGACA
 CAGCGCTACC TGGAGAGATA CATCTACAAC CGGGAGGAGT ACGCGCTCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 ATGCGGAATA CTGGAACAGC CAGAAGGACC TCCTGGAGGA GATGCGGGCA
 GTGGTGGACA CGATGTGCAG ATACAACTAC GAACTGGACG AGGCCGTGAC
 CCTGCAGCGC CGAGTCCAGC CAAGGGTGAA CATCGCCCCC TCCAAGAAGG
 GGCCCCTGCA GCACCACAAC CTGCTTGTCT GCCATGTGAC AGATTTCTAC
 CCAGGCAGCA TTCAAGTCCG ATGGTTCCTG AATGGACAGG AGGAAACAAC
 TGGGGTCGTG TCCACCAACC TGATCCGTAA TGGAGACTGG ACCTTCCAGA
 TCCTGGTGAT GCTGGAAATG ACCCCCCAGC AGGGAGACGT CTACACCTGC
 CAAGTGGAGC ACCCCAGCCT GGACAGTCCT GTCACCGTGG AGTGGAAGGC
 ACAGTCTGAT TCTGCCCGGA GTAAGACGCT GACGGGAGCC GGGGGCTTCG
 TGCTGGGGCT CATCATCTGT GGAGTGGGCA TCTTCATGCA CAGGAGGAGG
 AATAAAGTTC AACGAGGATC TGTATAA*  
>DL;IPD:MHC01333
IPD:MHC01333 Mafa-DPB1*09:01 265 bases
 GAGAATTACC TGTTGCAGGT ACGGCAGGAA TGCTATGCAT TTAATGGGAC
 ACAGCGCTAC CTGGAAAGAC ACATCTACAA TCGGGAAGAG CACGTGCGCT
 TCGACAGCGA CGTGGGGGAG TTCCGGGCGG TGACGGAGCT GGGGCGGCCT
 GCTGCGGAAT ACTGGAACAG CCAGAAGGAC TTCCTGGAGG AGAAGCGGGC
 AGAGGTGGAC ACGGTGTGCA GACACAACTA CGAGTTGGAC GAGGCCGTGA
 CCCTGCAGCG CCGAG*   
>DL;IPD:MHC01334
IPD:MHC01334 Mafa-DPB1*09:02 774 bases
 ATGGTTCTGC AGGTTTCTGG GACCCCCCAG ACAGTGGGTC TGATGGCGTT
 ACTGATGGTG CTGCTCACAT CTGTGGTCCA GGGCAGGGCC ACTCCAGAGA
 ATTACCTGTT GCAGATACGG GATGAATGCT ACGCGTTTAA TGGGACACAG
 CGCTACCTGG AAAGACACAT CTACAATCGG GAAGAGCACG TGCGCTTCGA
 CAGCGACGTG GGGGAGTACC GGGCGGTGAC GGAGCTGGGG CGGCCTGATG
 CGGAATACTG GAACAGCCAG AAGGACTTCC TGGAGGAGAA GCGGGCAGAG
 GTGGACACGG TGTGCAGATA CAACTACGAG CTGGACGAGG CCGTGACCCT
 GCAGCGCCGA GTCCAGCCGA GGGTGAATGT TTCCCCCTCC AAGAAGGGTC
 CCTTACAGCA CCACAACCTG CTCGTCTGCC ACGTGACAGA TTTCTACCCA
 GGCAGCATTC AAGTCCGATG GTTCCTGAAT GGACAGGAGG AAACAGCTGG
 GGTCGTGTCC ACCAACCTCA TCCGTAATGG AGACTGGACC TTCCAGATCC
 TGGTGATGCT GGAAATGACC CCCCAGCAGG GAGACGTCTA CACCTGCCAA
 GTGGAGCACC CCAGCCTGGA CAGTCCTGTC ACTATGGAGT GGAAGGCACA
 GTCTGATTCT GCCCGGAGTA AGACGCTGAC GGGAGTCGGG GGCTTCGTGC
 TGGGGCTCAT CACCTGTGGA GTGGGCATCT TCATGCACAG GAGGAGCAAG
 AAAGTTCAAC GAGGATCTGT ATAA*  
>DL;IPD:MHC03678
IPD:MHC03678 Mafa-DPB1*09:03 264 bases
 AGAATTACCT GTTGCAGGTA CGGGATGACT GCTACGCGTT TAATGGGACA
 CAGCGCTACC TGCAAAGACA CATCTACAAT CGGGAAGAGC ACGTGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 ATGCGGAATA CTGGAACAGC CAGAAGGACC TCCTGGAGGA GATGCGGGCA
 GTGGTGGACA GGGTGTGCAG ACACAACTAC GAGCTGGACG AGGCCGTGAC
 CCTGCAGCGC CGAG*   
>DL;IPD:MHC01215
IPD:MHC01215 Mafa-DPB1*10:01 777 bases
 ATGATGGTTC TGCAGGTTTC TGGGACCCCG CAGACAGTGG GTCTGATGGC
 GTTACTGATG GTGCTGCTCA CATCTGTGGT CCAGGGCAGG GCCACTCCAG
 AGAATTACCT GTACCAGGGA CGGCAGGAAT GCTACGCGTT TAATGGGACA
 CAGCGCTACC TGGAGAGATA CATCTACAAC CGGGAGGAGT ACGCGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACAGAGCTG GGACGGCCTG
 ATGCGGAATA CTGGAACAGC CAGAAGGACC GCCTGGAGGA GAAGCGGGCA
 GTGGTGGACA CGATGTGCAG ACACAACTAC GAGCTGGACG AGGCCGTGAC
 CCTGCAGCGC CGAGTCCAGC CGAGGGTGAA CATCGCCCCC TCCAAGAAGG
 GTCCCTTACA GCACCACAAC CTGCTCGTCT GCCATGTGAC AGATTTCTAC
 CCAGGCAGCA TTCAAGTCCG ATGGTTCCTG AATGGACAGG AGGAAACAAC
 TGGGGTCGTG TCCACCAACC TGATCCGTAA TGGAGACTGG ACCTTCCAGA
 TCCTGGTGAT GCTGGAAATG ACCCCCCAGC AGGGAGACGT CTACACCTGC
 CAAGTGGAGC ACCCCAGCCT GGACAGTCCT GTCACGGTGG AGTGGAAGGC
 ACAGTCTGAT TCTGCCCGGA GTAAGACGCT GACGGGAGCC GGGGGCTTCG
 TGCTGGGGCT CATCATCTGC GGAGTGGGCA TCTTCATGCA CAGGAGGAGC
 AAGAAAGTTC AACGAGGATC TGTATGA*  
>DL;IPD:MHC01331
IPD:MHC01331 Mafa-DPB1*12:01 265 bases
 GAGAATTACG TGTACCAGGG ACGGATGGAA TGCTACGTGT TTAACGGGAC
 ACAGCGCTAC CTGAAGAGAT ACATCTACAA CCGGGAGGAG TTCATGCGCT
 TCGACAGCGA CGCCGGGGAG TTCCGGGCGG TGACAGAGCT GGGAAGGCCT
 ATTGCAGAGT CCTGGAACAG CCAGAAGGAC AAACTGGAGG AGAAGCGGGC
 AGTGGCGGGC ACGGGTTGCA GACACAACTA CCAGTCGACA GAGCCAGTCA
 TCCGGAAGCG CCGAG*   
>DL;IPD:MHC01332
IPD:MHC01332 Mafa-DPB1*12:02 265 bases
 GAGAATTACG TGTACCAGGG ACGGATGGAA TGCTACGTGT TTAACGGGAC
 ACAGCGCTAC CTGGAGAGAT ACATCTACAA CTGGGAGGAG TTCGTGCGCT
 TCGACAGCGA CGCCGGGGAG TTCCGGGCGG TGACAGAGCT GGGAAGGCCT
 ATTGCAGAGT ACTGGAACAG CCAGAAGGAC AAACTGGAGG AGAAGCGGGC
 AGTGGCGGGC ACGGGTTGCA GACACAACTA CCAGTCGACA GAGCCAGTCA
 TCCGGAAGCG CCGAG*   
>DL;IPD:MHC01324
IPD:MHC01324 Mafa-DPB1*15:01 777 bases
 ATGATGGTTC TGCAGGTTTC TGCAGCTCCC GGGACAGTGG GTCTGATGGC
 ATTACTGATG GTGCTGCTCA CATCTGTGGT CCAGGGCAGG GCCACTCCAG
 AGAATTACCT GTTCCAGGCA CGGCAGGAAT GCTATGCATT TAACGGGACA
 CAGCGCTTCC TGGAGAGATA CATCTACAAC CGGGAGGAGT TGTTGCGCTT
 TGACAGTGAC GTGGGGGAGT TCCGGGCGGT GACAGAGCTG GGGCGACCTG
 AGGCCGAGTC CTGGAACAGC CAGAAGGACA CACTGGAGAA GAAGCGGGCA
 GTGGTGGACA CGATGTGCAG ACACAACTAC GAGCTGGACG AGGCCGTGAC
 CCTGCAGCGC CGAGTCCAGC CAAGGGTGAA CATCGCCCCC TCCAAGAAGG
 GTCCCTTACA GCACCACAAC CTGCTCGTCT GCCATGTGAC AGATTTCTAC
 CCAGGCAGCG TTCAAGTCCG ATGGTTCCTG AATGGACAGG AGGAAACAGC
 TGGGGTCGTG TCCACCAACC TGATCCGTAA TGGAGACTGG ACCTTCCAGA
 TCCTGGTGAT GCTGGAAATG ACCCCCCAGC AGGGAGACGT CTACACCTGC
 CAAGTGGAGC ACCCCAGCCT GGACAGTCCT GTCACCGTGG AGTGGAAGGC
 ACAGTCTGAT TCTGCCCGGA GTAAGACGCT GACGGGAGCT GGGGGCTTCG
 TGCTGGGGCT CATCATCTGT GGAGTGGGCA TCTTCATGCA CAGGAGGAGC
 AAGAAAGTTC AACGAGGATC TGTATAA*  
>DL;IPD:MHC01212
IPD:MHC01212 Mafa-DPB1*15:02 777 bases
 ATGATGGTTC TGCAGGTTTC TGCAGCCCCT AGGACAGTGG GTCTGATGGC
 GTTACTGATG GTGCTGCTCA CATCTGTGGT CCAGGGCAGG GCCACTCCAG
 AGAATTACCT GTTCCAGGCA CGGCAGGAAT GCTATGCATT TAACGGGACA
 CAGCGCTACC TGGAAAGATA CATCTACAAC CGGGAGGAGT TGTTGCGCTT
 TGACAGTGAC GTGGGGGAGT TCCGGGCGGT GACAGAGCTG GGGCGACCTG
 AGGCCGAGTC CTGGAACAGC CAGAAGGACA TCCTGGAGGA GAAGCGGGCA
 GTGGCGGGCA CGGGTTGCAG ACACAACTAC GAGCTGGACG AGGCCGTGAC
 CCTGCAGCGC CGAGTCCAGC CAAGGGTGAA CATCGCCCCC TCCAAGAAGG
 GTCCCTTACA GCACCACAAC CTGCTCGTCT GCCATGTGAC AGATTTCTAC
 CCAGGCAGCG TTCAAGTCCG ATGGTTCCTG AATGGACAGG AGGAAACAGC
 TGGGGTCGTG TCCACCAACC TGATCCGTAA TGGAGACTGG ACCTTCCAGA
 TCCTGGTGAT GCTGGAAATG ACCCCCCAGC AGGGAGACGT CTACACCTGC
 CAAGTGGAGC ACCCCAGCCT GGACAGTCCT GTCACCGTGG AGTGGAAGGC
 ACAGTCTGAT TCTGCCCGGA GTAAGACGCT GACGGGAGCT GGGGGCTTCG
 TGCTGGGGCT CATCATCTGT GGAGTGGGCA TCTTCATGCA CAGGAGGAGC
 AAGAAAGTTC AACGAGGATC TGTATAA*  
>DL;IPD:MHC01213
IPD:MHC01213 Mafa-DPB1*15:03 777 bases
 ATGATGGTTC TGCAGGTTTC TGCAGCTCCC GGGACAGTGG GTCTGATGGC
 ATTACTGATG GTGCTGCTCA CATCTGTGGT CCAGGGCAGG GCCACTCCAG
 AGAATTACCT GTTCCAGGCA CGGCAGGAAT GCTATGCATT TAACGGGACA
 CAGCGCTACC TGGAAAGATA CATCTACAAC CGGGAGGAGT TGTTGCGCTT
 TGACAGTGAC GTGGGGGAGT TCCGGGCGGT GACAGAGCTG GGGCGACCTG
 AGGCCGAGTC CTGGAACAGC CAGAAGGACA CACTGGAGAA GAAGCGGGCA
 GCGGTGGACA CGATGTGCAG ACACAACTAC GAGCTGGACG AGGCCGTGAC
 CCTGCAGCGC CGAGTCCAGC CAAGGGTGAA CATCGCCCCC TCCAAGAAAG
 GGCCCTTACA GCACCACAAC CTGCTCGTCT GCCATGTGAC AGATTTCTAC
 CCAGGCAGCA TTCAAGTCCG ATGGTTCCTG AATGGACAGG AGGAAACAGC
 TGGGGTCGTG TCCACCAACC TGATCCGTAA TGGAGACTGG ACCTTCCAGA
 TCCTGGTGAT GCTGGAAATG ACCCCCCAGC AGGGAGACGT CTATACCTGC
 CAAGTGGAGC ACCCCAGCCT GGACAGTCCT GTCACCGTGG AGTGGAAGGC
 ACAGTCTGAT TCTGCCCGGA GTAAGACGCT GACGGGAGCC GGGGGCTTCG
 TGCTGGGGCT CATCACCTGT GGAGTGGGCA TCTTCATGCA CAGGAGAAGC
 AAGAAAGTTC AACGAGGATC TGCATAA*  
>DL;IPD:MHC01325
IPD:MHC01325 Mafa-DPB1*15:04 780 bases
 ATGATGGTTC TGCAGGTTTC TGCAGCTCCC GGGACAGTGG GTCTGATGGC
 ATTACTGATG GTGCTGCTCA CATCTGTGGT CCAGGGCAGG GCCACTCCAG
 AGAATTACCT GTTCCAGGCA CGGCAGGAAT GCTATGCATT TAACGGGACA
 CAGCGCTTCC TGGAGAGATA CATCTACAAC CGGGAGGAGT TGTTGCGCTT
 TGACAGTGAC GTGGGGGAGT ACCGGGCGGT GATGACAGAG CTGTGGCGAC
 CTGAGGCCGA GTCCTGGAAC AGCCAGAAGG ACACACTGGA GAAGAAGCGG
 GCAGCGGTGG ACACGATGTG CAGACACAAC TACGAGCTGG ACGAGGCCGT
 GACCCTGCAG CGCCGAGTCC AGCCAAGGGT GAACATCGCC CCCTCCAAGA
 AAGGGCCCTT ACAGCACCAC AACCTGCTCA TCTGCCATGT GACAGATTTC
 TACCCAGGCA GCATTCAAGT CCGATGGTTC CTGAATGGAC AGGAGGAAAC
 AGCTGGGGTC GTGTCCACCA ACCTGATCCG TAATGGAGAC TGGACCTTCC
 AGATCCTGGT GATGCTGGAA ATGACCCCCC AGCAGGGAGA CGTCTATACC
 TGCCAAGTGG AGCACCCCAG CCTGGACAGT CCTGTCACCG TGGAGTGGAA
 GGCACAGTCT GATTCTGCCC GGAGTAAGAC GCTGACGGGA GCCGGGGGCT
 TCGTGCTGGG GCTCATCACC TGTGGAGTGG GCATCTTCAT GCACAGGAGA
 AGCAAGAAAG TTCAACGAGG ATCTGCATAA * 
>DL;IPD:MHC01171
IPD:MHC01171 Mafa-DPB1*15:05 777 bases
 ATGATGGTTC TGCAGGTTTC TGCAGCCCCT AGGACAGTGG GTCTGGTGGC
 GTTACTGATG GTGCTGCTCA CATCTGTGGT CCAGGGCAGG GCCACTCCAG
 AGAATTACCT GTTCCAGGCA CGGCAGGAAT GCTATGCATT TAACGGGACA
 CAGCGCTACC TGGAAAGATA CATCTACAAC CGGGAGGAGT TGTTGCGCTT
 TGACAGTGAC GTGGGGGAGT TCCGGGCGGT GACAGAGCTG GGGCGACCTG
 AGGCCGAGTC CTGGAACAGC CAGAAGGACA CACTGGAGAA GAAGCGGGCA
 GGGGTGGACA CGATGTGCAG ACACAACTAC GAGCTGGACG AGGCCGTGAC
 CCTGCAGCGC CGAGTCCAGC CAAGGGTGAA CATCGCCCCC TCCAAGAAGG
 GTCCCTTACA GCACCACAAC CTGCTCGTCT GCCATGTGAC AGATTTCTAC
 CCAGGCAGCG TTCAAGTCCG ATGGTTCCTG AATGGACAGG AGGAAACAGC
 TGGGGTCGTG TCCACCAACC TGATCCGTAA TGGAGACTGG ACCTTCCAGA
 TCCTGGTGAT GCTGGAAATG ACCCCCCAGC AGGGAGACGT CTACACCTGC
 CAAGTGGAGC ACCCCAGCCT GGACAGTCCT GTCACCGTGG AGTGGAAGGC
 ACAGTCTGAT TCTGCCCGGA GTAAGACGCT GACGGGAGCT GGGGGCTTCG
 TGCTGGGGCT CATCATCTGT GGAGTGGGCA TCTTCATGCA CAGGAGGAGC
 AAGAAAGTTC AACGAGGATC TGTATAA*  
>DL;IPD:MHC01172
IPD:MHC01172 Mafa-DPB1*15:06 777 bases
 ATGATGGTTC TGCAGGTTTC TGCAGCTCCC GGGACAGTGG GTCTGATGGC
 ATTACTGATG GTGCTGCTCA CATCTGTGGT CCAGGGCAGG GCCACTCCAG
 AGAATTACCT GTTCCAGGCA CGGCAGGAAT GCTATGCATT TAACGGGACA
 CAGCGCTTCC TGGAGAGATA CATCTACAAC CGGGAGGAGT TGTTGCGCTT
 TGACAGTGAC GTGGGGGAGT ACCGGGCGGT GACAGAGCTG TGGCGACCTG
 AGGCCGAGTC CTGGAACAGC CAGAAGGACA CACTGGAGAA GAAGCGGGCA
 GTGGTGGACA CGATGTGCAG ACACAACTAC GAGCTGGACG AGGCCGTGAC
 CCTGCAGCGC CGAGTCCAGC CAAGGGTGAA CATCGCCCCC TCCAAGAAAG
 GGCCCTTACA GCACCACAAC CTGCTCGTCT GCCATGTGAC AGATTTCTAC
 CCAGGCAGCA TTCAAGTCCG ATGGTTCCTG AATGGACAGG AGGAAACAGC
 TGGGGTCGTG TCCACCAACC TGATCCGTAA TGGAGACTGG ACCTTCCAGA
 TCCTGGTGAT GCTGGAAATG ACCCCCCAGC AGGGAGACGT CTATACCTGC
 CAAGTGGAGC ACCCCAGCCT GGACAGTCCT GTCACCGTGG AGTGGAAGGC
 ACAGTCTGAT TCTGCCCGGA GTAAGACGCT GACGGGAGCC GGGGGCTTCG
 TGCTGGGGCT CATCACCTGT GGAGTGGGCA TCTTCATGCA CAGGAGAAGC
 AAGAAAGTTC AACGAGGATC TGCATAA*  
>DL;IPD:MHC03671
IPD:MHC03671 Mafa-DPB1*15:07 264 bases
 AGAATTACCT GTTCCAGGCA CGGAAGGAAT GCTATGCATT TAACGGGACA
 CAGCGCTTCC TGGAGAGATA CATCTACAAC CGGGAGGAGT TGTTGCGCTT
 TGACAGTGAC GTGGGGGAGT TCCGGGCGGT GACAGAGCTG GGGCGACCTG
 AGGCCGAGTC CTGGAACAGC CAGAAGGACA CACTGGAGAA GAAGCGGGCA
 GTGGTGGACA CGATGTGCAG ACACAACTAC GAGCTGGACG AGGCCGTGAC
 CCTGCAGCGC CGAG*   
>DL;IPD:MHC04370
IPD:MHC04370 Mafa-DPB1*15:08 777 bases
 ATGATGGTTC TGCAGGTTTC TGCAGCCCCT AGGACAGTGG GTCTGATGGC
 GTTACTGATG GTGCTGCTCA CATCTGTGGT CCAGGGCAGG GCCACTCCAG
 AGAATTACCT GTTCCAGGCA CGGCAGGAAT GCTATGCATT TAACGGGACA
 CAGCGCTACC TGGAAAGATA CATCTACAAC CGGGAGGAGT TGTTGCGCTT
 TGACAGTGAC GTGGGGGAGT TCCGGGCGGT GACAGAGCTG GGGCGACCTG
 AGGCCGAGTC CTGGAACAGC CAGAAGGACA TCCTGGAGGA GAAGCGGGCA
 GTGGCGGGCA CGGGTTGCAG ACACAACTAC GAGCTGGACG AGGCCGTGAC
 CCTGCAGCGC CGAGTCCAGC CAAGGGTGAA CATCGCCCCC TCCAAGAAGG
 GTCCCTTACA GCACCACAAC CTGCTCGTCT GCCATGTGAC AGATTTCTAC
 CCAGGCAGCG TTCAAGTCCG ATGGTTCCTG AATGGACAGG AGGAAACAGC
 TGGGGTCGTG TCCACCAACC TGATCCGTAA TGGAGACTGG ACCTTCCAGA
 TCCTGGTGAT GCTGGAAATG ACCCCCCAGC AGGGAGACGT CTACACCTGC
 CAAGTGGAGC ACCCCAGCCT GGACAGTCCT GTCACCGTGG AGTGGAAGGC
 ACAGTCTGAT TCTGCCCGGA GTAAGACGCT GACGGGAGCT GGGGGCTTCG
 TGCTGGGGCT CATCATCTGT GGAGTGGGCA TCTTCAGGCA CAGGAGGAGC
 AAGAAAGTTC AACGAGGATC TGTATAA*  
>DL;IPD:MHC05128
IPD:MHC05128 Mafa-DPB1*16:01 264 bases
 AGAATTACGT GTACCAGAGT CTGACTGAAT GCTACGAGTT TAACGGGACA
 CAGCGCCTCC TGGACAGATA CATCTACAAC CGGGAGGAGT TCGTGCGCTT
 CGACAGCTAC GTGGGGGAGT ACCGGGCGGT GACGGAGCTG GGACGGCCTA
 CTGCCGAGTA CTGGAACAGC CTGGAGGACT ACATGGAGGA GACAAGGGCC
 GCGGTGGACA CGGTGTGCAG ATACAACTAC GAGTTGGACG AGGCCGTGAC
 CCTGCAGCGC CGAG*   
>DL;IPD:MHC03675
IPD:MHC03675 Mafa-DPB1*17:01 264 bases
 AGAATTACGT GTACCAGAGA TGGTATGAAT GCTATGCGTT TAACGGGACA
 CAGCGCCTCC TGGACAGATA CATGTACAAC CAGGAGGAGT TCGTGCGCTT
 CGACAGCGAC CTGGGGGAGT TCCGGGCAGT GACGGAGCTG GGACGGCCTA
 CTGCTGAGCG CTGGAACAGC CAGAAGGACA TCCTGGAGCG GGAGCGGGCC
 TCCGTGGACA GGGTGTGCAG ATACAACTAC GAGCTGGAGG AGCCACTCAT
 CCGGAAGCGC CGAG*   
>DL;IPD:MHC01338
IPD:MHC01338 Mafa-DPB1*18:01 655 bases
 TCACATCTGT GGTCCAGGGC AGGGCCACTC CAGAGAATTA CGTGTGCCAG
 AGACGGTTTG AATGCTATGC GTATAACGGG ACACAGCGCC TCCTGGACAG
 ATACATCTAC AACCAGGAGG AGTACGTGCG CTTCGACAGC GACCTGCGGG
 AGTTCCGGGC AGTGACGGAG CTGGGACGGC CTACTGCTGA GCGCTGGAAC
 AGACAGGACA TCCTGGAGCA GGCGCGGGCC GAGGTGGACA GGGTGTGTAG
 ACACAACTAC GAGCTGGCGG AGCCACTCAT CCGGAAGCGC CGAGTCCAGC
 CGAGGGTGAA CGTCTCCCCC TCCAAGAAGG GGCCCTTACA GCACCACAAC
 CTGCTCGTCT GCCATGTGAC AGATTTCTAC CCAGGCAGCA TTCAAGTCCG
 GTGGTTCCTG AATGGACAGG AGGAAACAGC TGGGGTCGTG TCCACCAACC
 TCATCCGTAA TGGAGACTGG ACCTTCCAGA TCCTGGTGAT GCTGGAAATG
 ACCCCCCAGC AGGGAGATGT CTACACCTGC CAAGTGGAGC ACCCCAGCCT
 GGACAGTCCT GTCACCGTGG AGTGGAAGGC ACAGTCTGAT TCTGCCCGGA
 GTAAGACGCT GACGGGAGCC GGGGGCTTCG TGCTGGGGCT CATCACCTGT
 GGAGT*    
>DL;IPD:MHC01345
IPD:MHC01345 Mafa-DPB1*18:02 262 bases
 GAGAATTACG TGTGCCAGAG ACGGTTTGAA TGCTATGCGT ATAACGGGAC
 ACAGCGCCTC CTGGACAGAT ACATCTACAA CCAGGAGGAG TACGTGCGCT
 TCGACAGCGA CCTGCGGGAG TTCCGGGCAG TGACGGAGCT GGGACAGCCT
 ACTGCTGAGC GCTGGAACAG ACAGGACATC CTGGAGCAGG CGCGGGCCGA
 GGTGGACAGG GTGTGTAGAC ACAACTACGA GCTGGCGGAG CCACTCATCC
 GGAAGCGCCG AG*   
>DL;IPD:MHC01339
IPD:MHC01339 Mafa-DPB1*19:01 262 bases
 GAGAATTACG TGTACCAGAG ACGGTTTGAA TGCTATGCGT TTAACGGGAC
 ACAGCGCCTC CTGGACAGAT TCATCTACAA CCAGGAGGAG TACGTGCGCT
 TCGACAGCGA CCTGGGGGAG TTCCGGGCAG TGACGGAGCT GGGACGGCCT
 ACTGCCGAGT ACTGGAACAG ACAGGACTCC CTGGAGCAGG AGCGGGCCGA
 GGTGGACAGG GTGTGCAGAC ATAACTACGA GCTGGATGAG GCCGTGACCC
 TGAAGCGCCG AG*   
>DL;IPD:MHC01340
IPD:MHC01340 Mafa-DPB1*19:02 262 bases
 GAGAATTACG TGTACCAGAG ACGGTTTGAA TGCTATGCGT TTAACGGGAC
 ACAGCGCCTC CTGGACAGAT TCATCTACAA CCAGGAGGAG TTCGTGCGCT
 TCGACAGCGA CCTGGGGGAG TTCCGGGCAG TGATGGAGCT GGGACGGCCT
 ACTGCCGAGT ACTGGAACAG ACAGGACTCC CTGGAGCAGG AGCGGGCCGA
 GGTGGACAGG GTGTGCAGAC ATAACTACGA GCTGGATGAG GCCGTGACCC
 TGAAGCGCCG AG*   
>DL;IPD:MHC01341
IPD:MHC01341 Mafa-DPB1*19:03 774 bases
 ATGATGGTTC TGCCAGTTTC TGGGGCCCCC CAGACAGTGA CTCTGACGGC
 GTTACTGATG GTGCTGCTCA CATCTGTAGT CCAGGGCACG GCCACTCCAG
 AGAATTACGT GTACCAGAGA CGGTTTGAAT GCTATGCGTT TAACGGGACA
 CAGCGCCTCC TGGACAGATT CATCTACAAC CAGGAGGAGT TCGTGCGCTT
 CGACAGCGAC CTGGGGGAGT TCCGGGCAGT GACGGAGCTG GGACGGCCTA
 CTGCCGAGTA CTGGAACAGA CAGGACTCCC TGGAGCAGGA GCGGGCCGAG
 GTGGACAGGG TGTGCAGACA TAACTACGAG CTGGATGAGG CCGTGACCCT
 GAAGCGCCGA GTCCAGCCGA GGGTGAACGT CTCCCCCTCC AAGAAGGGGC
 CCTTACAGCA CCACAACCTG CTCGTCTGCC ATGTGACAGA TTTCTACCCA
 GGCAGCATTC AAGTCCGGTG GTTCCTGAAT GGACAGGAGG AAACAGCTGG
 GGTCGTGTCC ACCAACCTGA TCCGTAATGG AGACTGGACC TTCCAGATCC
 TGGTGATGCT GGAAATGACC CCCCAGCAGG GAGACGTCTA CACCTGCCAA
 GTGGAGCACC CCAGCCTGGA CAGTCCTGTC ACTATGGAGT GGAAGGCACA
 GTCTGATTCT GCCCGGAGTA AGACGCTGAC GGGAGCCGGG GGCTTCGTGC
 TGGGGCTCAT CATCTGTGGA GTGGGCATCT TCATGCACAG GAGGAGCAAG
 AAAGTTCAAC GAGGATCTGT ATAA*  
>DL;IPD:MHC01342
IPD:MHC01342 Mafa-DPB1*19:04 262 bases
 GAGAATTACG TGTACCAGAG ACGGTCTGAA TGCTATGCGT TTAACGGGAC
 ACAGCGCCTC CTGGACAGAT TCATCTACAA CCAGGAGGAG TTCGTGCGCT
 TCGACAGCGA CCTGGGGGAG TTCCGGGCAG TGACGGAGCT GGGACGGCCT
 ACTGCCGAGT ACTGGAACAG ACAGGACACC CTGGAGCAGG AGCGGGCCGA
 GGTGGACAGG GTGTGCAGAC ATAACTACGA GCTGGATGAG GCCGTGACCC
 TGAAGCGCCG AG*   
>DL;IPD:MHC01343
IPD:MHC01343 Mafa-DPB1*19:05 262 bases
 GAGAATTACG TGTACCAGAG ACGGTCTGAA TGCTATGCGT TTAACGGGAC
 ACAGCGCCTC CTGGACAGAT TCATCTACAA CCAGGAGGAG TTCGTGCGCT
 TCGACAGCGA CCTGGGGGAG TTCCGGGCAG TGACGGAGCT GGGACGGCCT
 AACGCCGAGT ACTGGAACAG ACAGGACACC CTGGAGCAGG AGCGGGCCGA
 GGTGGACAGG GTGTGCAGAC ATAACTACGA GCTGGATGAG GCCGTGACCC
 TGAAGCGCCG AG*   
>DL;IPD:MHC01344
IPD:MHC01344 Mafa-DPB1*19:06 262 bases
 GAGAATTACG TGTACCAGAG ACGGTCTGAA TGCTATGCGT TTAACGGGAC
 ACAGCGCCTC CTGGACAGAT TCATCTACAA CCAGGAGGAG TACGTGCGCT
 TCGACAGCGA CCTGGGGGAG TTCCGGGCAG TGACGGAGCT GGGACGGCCT
 GACGCCGAGT ACTGGAACAG ACAGGACACC CTGGAGCAGG AGCGGGCCGA
 GGTGGACAGG GTGTGCAGAC ATAACTACGA GCTGGATGAG GCCGTGACCC
 TGAAGCGCCG AG*   
>DL;IPD:MHC01618
IPD:MHC01618 Mafa-DPB1*20:01 777 bases
 ATGGTGGTTC TGCCAGTTTC TGGGGCCCCC TGGACAGTGA CTCTGACGGC
 GTTACTGATG GTGCTGCTCA CATCTGTGGT CCAGGGCAGG GCCACTCCAG
 AGAATTACGT GTACCAGAGA CGGTATGAAT GCTATGCGTT TAACGGGACA
 CAGCGCCTCC TGGACAGATC CATCTACAAC CAGGAGGAGT TCGTGCGCTT
 CGACAGCGAC CTGGGGGAGT TCCGGGCAGT GACGGAGCTG GGACGGCCTG
 CTGCTGAGCG CTGGAACAGC CAGAAGGACA TCCTGGAGCG GGAGCGGGCC
 TCCGTGGACA GGGTGTGCAG ATACAACTAC GAGCTGAACG AGGCCGTGAC
 CCTGAAGCGC CGAGTCCAGC CGAGGGTGAA CGTCTCCCCC TCCAAGAAGG
 GGCCCTTACA GCACCACAAC CTGCTCGTCT GCCATGTGAC AGATTTCTAC
 CCAGGCAGCA TTCAAGTCCG GTGGTTCCTG AATGGACAGG AGGAAACAGC
 TGGGGTCGTG TCCACCAACC TGATCCGTAA TGGAGACTGG ACCTTCCAGA
 TCCTGGTGAT GCTGGAAATG ACCCCCCAGC AGGGAGACGT CTACACCTGC
 CAAGTGGAGC ACCCCAGCCT GGACAGTCCT GTCACTGTGG AGTGGAAGGC
 ACAGTCTGAT TCTGCCCGGA GTAAGACGCT GACGGGAGCC GGGGGCTTCG
 TGCTGGGGCT CATCACCTGT GGAGTGGGCA TCTTCATGCA CAGGAGGAGC
 AAGAAAGTTC AACGAGGATC TGCATAA*  
>DL;IPD:MHC04433
IPD:MHC04433 Mafa-DPB1*21:01 655 bases
 TCACATCTGT GGTCCAGGGC AGGGCCACTC CAGAGAATTA CGTGTACCAG
 AGACGGTATG AATGCTATGC GTTTAACGGG ACACAGCGCC TCCTGGACAG
 ATCCATCTAC AACCAGGAGG AGTTCGTGCG CTTCGACAGC GACCTGGGGG
 AGTTCCGGGC AGTGACGGAG CTGGGACGGC CTGCTGCTGA GCGCTGGAAC
 AGACAGGACA ACCTGGAGCG GGAGCGGGCT GAGGTGGACA GGGTGTGCAG
 ACACAACTAC GAGCTGAACG AGGCCGTGAC CCTGAAGCGC CGAGTCCAGC
 CGAGGGTGAA CGTCTCCCCC TCCAAGAAGG GGCCCTTACA GCACCACAAC
 CTGCTCGTCT GCCATGTGAC AGATTTCTAC CCAGGCAGCA TTCAAGTCCG
 GTGGTTCCTG AATGGACAGG AGGAAACAGC TGGGGTCGTG TCCACCAACC
 TGATCCGTAA TGGAGACTGG ACCTTCCAGA TCCTGGTGAT GCTGGAAATG
 ACCCCCCAGC AGGGAGACGT CTACACCTGC CAAGTGGAGC ACCCCAGCCT
 GGACAGTCCT GTCACTGTGG AGTGGAAGGC ACAGTCTGAT TCTGCCCGGA
 GTAAGACGCT GACGGGAGCC GGGGGCTTCG TGCTGGGGCT CATCACCTGC
 GGAGT*    
