>DL;IPD:MHC04306
IPD:MHC04306 Mafa-AG*01:01 273 bases
 SHSMRYFYTA VSRPGRWEPR FIAVGYVDDT QFVRFDSDAQ SPRMEPRAPW
 VEQEGPEYWD RETQNMKTAT QTYQGNLRTL LRYYNQSEAR SHTIQKMYGC
 DLGPDGRLLR GYEQFAYDGR DYIILNEDLR SWTAADMAAQ NTQRKWEAAR
 AAEQHRTYLE GECLEWLRRY LENGKETLQR ADPPKTHVTH HPISDHEATL
 RCWALGFYPA EITLTWQRDG EEQTQDTELM ETRPTGNGTF QKWAAVVVPS
 GEEQRYTCHV QHEGLPKPLT LRW*  
>DL;IPD:MHC04426
IPD:MHC04426 Mafa-AG*01:02 181 bases
 SHSMRYFYTA VSRPGRWEPR FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 VEQEGPEYWD RETQNMKTAT QTYQGNLRTL LRYYNQSEAR SHTVQKMYGC
 DLGPDGRLLR GYEQFAYDGR DYIILNEDLR SWTAADMAAQ NTQRKWEAAG
 VAEQHRTYLE GECLEWLRRY LENGKETLQR A* 
>DL;IPD:MHC04429
IPD:MHC04429 Mafa-AG*01:03 181 bases
 SHSMRYFYTA VSRPGRWEPR FIAVGYVDDT QFVRFDSDAQ SPRMEPRAPW
 VEQEGPEYWD RETQNMKTAT QTYQGNLRTL LRYYNQSEAR SHTVQKMYGC
 DLGPDGRLLR GYEQFAYDGR DYIILNEDLR SWTAADMAAQ NTQRKWEAAG
 VAEQHRTYLE GECLEWLRRY LENGKETLQR A* 
>DL;IPD:MHC04432
IPD:MHC04432 Mafa-AG*01:04 181 bases
 SHSMRYFYTA VSRPGRWEPR FIAVGYVDDT QFVRFDSDAQ SPRMEPRAPW
 VEQEGPEYWD RETQNMKTAT QTYQGNLRTL LGYYNQSEAR SHTVQKMYGC
 DLGPDGRLLR GYEQFAYDGR DYIILNEDLR SWTAADMAAQ NTQRKWEAAG
 VAEQHRTYLE GECLEWLRRY LENGKETLQR A* 
>DL;IPD:MHC03759
IPD:MHC03759 Mafa-AG*02:01 273 bases
 SHSMRYFYTS MSRPGRGQPR FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 VEQEGPEYWD RETQNMKTAT QTYRENLRTL LRYYNQSEAG SHTIQKMYGC
 DLGPDGRLLR GYEQFAYDGR DYIILNEDLR SWTAADMAAQ NTQRKWEAAG
 AAEQHRTYLE GECLEWLRRY LENGKETLQR ADPPKTNVTH HPVSDYEATL
 RCWALGFYPA EITLTWQRDG EEQTEDTELV ETRPTGDGTF QKWAAVVVPS
 GEEQRYTCHV QHEGLPEPLT LRW*  
>DL;IPD:MHC03843
IPD:MHC03843 Mafa-AG*03:01:01 337 bases
 MAVMAPRTLL LVLSGVLALT QPRAGSHSMR YFYTAVSRPG RGQPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWVEQEG PEYWDRETQN MKTATQTYQA
 NLRTLLRYYN QSEAGSHTFQ KMYGCDLGPD GRLLRGYEQF AYDGRDYIIL
 NEDLRSWTAA DMAAQNTQRK WEAAGAAEQH RTYLEGECLE WLRRYLENGK
 ETLQRADPPK TNVTHHPVSD YEATLRCWAL GFYPAEITLT WQRDGEEQTE
 DTELVETRPT GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQSTILIVG IIAGLVLLGT VVTGAVVAAV MWRRKSX* 
>DL;IPD:MHC04274
IPD:MHC04274 Mafa-AG*03:01:02 181 bases
 SHSMRYFYTA VSRPGRGQPR FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 VEQEGPEYWD RETQNMKTAT QTYQANLRTL LRYYNQSEAG SHTFQKMYGC
 DLGPDGRLLR GYEQFAYDGR DYIILNEDLR SWTAADMAAQ NTQRKWEAAG
 AAEQHRTYLE GECLEWLRRY LENGKETLQR A* 
>DL;IPD:MHC04420
IPD:MHC04420 Mafa-AG*03:01:03 181 bases
 SHSMRYFYTA VSRPGRGQPR FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 VEQEGPEYWD RETQNMKTAT QTYQANLRTL LRYYNQSEAG SHTFQKMYGC
 DLGPDGRLLR GYEQFAYDGR DYIILNEDLR SWTAADMAAQ NTQRKWEAAG
 AAEQHRTYLE GECLEWLRRY LENGKETLQR A* 
>DL;IPD:MHC04277
IPD:MHC04277 Mafa-AG*03:02 182 bases
 GSHSMRYFYT AVSRPGRGQP RFIAVGYVDD TQFVRFDSDA ESPRMEPRAP
 WVEQEGPEYW DRETQNMKTA TQTYQANLRT LLRYYNQSEA GSHTFQKTYG
 CDLGPDGRLL RGYEQFAYDG RDYIILNEDL RSWTAADMAA QNTQRKWEAA
 GAAEQHRTYL EGECLEWLRR YLENGKETLQ RA* 
>DL;IPD:MHC03758
IPD:MHC03758 Mafa-AG*04:01 273 bases
 SHSMRYFYTA VSRPGRWEPR FIAVGYVDDT QFVQFDSDAE SPRMEPRAPW
 VEQEGPEYWD RETQNMKTAT QTYRVNLRTL LRYYNQSEAG SHTVQKMYGC
 DLGPDGRLLR GYEQFAYDGS DYIALNEDLR SWTAADMAAQ NTQRKWEAAR
 AAEQHRTYLE GECLEWLRRY LENGKETLQR ADPPKTHVTH HPVSDHEATL
 RCWALGFYPA EITLTWQRDG EEQTEDTELV ETRPTGDGTF QKWAAVVVPS
 GEEQRYTCHV QHEGLPKPHT LRW*  
>DL;IPD:MHC03765
IPD:MHC03765 Mafa-AG*04:02 273 bases
 SHSMRYFYTA VSRPGRWEPR FIAVGYVDDT QFVQFDSDAE SPRMEPRAPW
 VEQEGPEYWD RETQNMKTAT QTYRVNLRTL LRYYNQSEAG SHTVQKMYGC
 DLGPDGRLLR GYEQFAYDGS DYIALNEDLR SWTAADMAAQ NTQRKWEAAR
 AAEQHRTYLE GECLEWLRRY LENGKETLQR ADPPKTHVTH HPVSDHEATL
 RCWALGFYPA EITLTWQRDG EEQTEDTELV ETRPTGDGTF QKWAAVVVPS
 GEEQRYTCHV QHEGLPKPLT LRW*  
>DL;IPD:MHC03734
IPD:MHC03734 Mafa-AG*04:03 214 bases
 LSGVLALTQT RAGSHSMRYF YTAVSRPGRW EPRFIAVGYV DDTQFVQFDS
 DAESPRMEPR APWVEQEGPE YWDRETQNMK TATQTYRVNL RTALRYYNQS
 EAGSHTVQKM YGCDLGPDGR LLRGYEQFAY DGSDYIALNE DLRSWTGADM
 AAQNTQRKWE AARAAEQHRT YLEGECLEWL RRYLENGKET LQRADPPKTH
 VTHHPVSDHE ATLR*   
>DL;IPD:MHC04273
IPD:MHC04273 Mafa-AG*04:04:01 182 bases
 GSHSMRYFYT AVSRPGRWEP LFIAVGYVDD TQFVQFDSDA ESPRMEPRAP
 WVEQEGPEYW DRETQNMKTA TQTYRVNLRT ALRYYNQSEA GSHTVQKMYG
 CDLGPDGRLL RGYEQFAYDG SDYIALNEDL RSWTAADMAA QNTQRKWEAA
 RAAEQHRTYL EGECLEWLRR YLENGKETLQ RA* 
>DL;IPD:MHC04419
IPD:MHC04419 Mafa-AG*04:04:02 181 bases
 SHSMRYFYTA VSRPGRWEPL FIAVGYVDDT QFVQFDSDAE SPRMEPRAPW
 VEQEGPEYWD RETQNMKTAT QTYRVNLRTA LRYYNQSEAG SHTVQKMYGC
 DLGPDGRLLR GYEQFAYDGS DYIALNEDLR SWTAADMAAQ NTQRKWEAAR
 AAEQHRTYLE GECLEWLRRY LENGKETLQR A* 
>DL;IPD:MHC04301
IPD:MHC04301 Mafa-AG*04:05 273 bases
 SHSMRYFYTA VSRPGRWEPR FIAVGYVDDT QFVQFDSDAE SPRMEPRAPW
 VEQEGPEYWD RETQNMKTAT QTYRVNLRTL LRYYNQSEAG SHTVQKMYGC
 DLGPDGRLLR GYEQFAYDGS DYIALNEDLR SWTAADMAAQ NTQRKWEAAR
 AAEQHRTYLE GECLEWLRRY LENGKETLQR ADPPKTHVTH HPVSDHEATL
 RCWALGFYPA EITLTWQRDG GEQTEDTELV ETRPTGDGTF QKWAAVVVPS
 GEEQRYTCHV QHEGLPKPLT LRW*  
>DL;IPD:MHC04427
IPD:MHC04427 Mafa-AG*04:06 181 bases
 SHSMRYFYTA VSRPGRWEPR FIAVGYVDDT QFVQFDSDAE SPRMEPREPW
 VEQEGPEYWD RETQNMKTAT QTYRVNLRTA LRYYNQSEAG SHTVQKMYGC
 DLGPDGRLLR GYEQFAYDGS DYIALNEDLR SWTAADMAAQ NTQRKWEAAR
 AAEQHRTYLE GECLEWLRRY LENGKETLQR A* 
>DL;IPD:MHC04431
IPD:MHC04431 Mafa-AG*04:07 181 bases
 SHSMRYFYTA VSRPGRWEPR FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 VEQEGPEYWD RETQNMKTAT QTYRGNLRTA LRYYNQSEAG SHTIQKMYGC
 DLGPDGRLLR GYEQFAYDGR DYIALNEDLR SWTAADLAAQ NTQRKWEAAR
 AAEQHRTYLE GECLEWLRRY LENGKETLQR A* 
>DL;IPD:MHC04638
IPD:MHC04638 Mafa-AG*04:08 181 bases
 SHSMRYFYTA VSRPGRWEPR FIAVGYVDDT QFVRFDSDAQ SPRMEPRAPW
 VEQEGPEYWD RETQNMKTAT QTYRVNLRTA LRYYNQSEAG SHTVQKMYGC
 DLGPDGRLLR GYEQFAYDGS DYIALNEDLR SWTAADMAAQ NTQRKWEAAR
 AAEQHRTYLE GECLEWLRRY LENGKETLQR A* 
>DL;IPD:MHC04271
IPD:MHC04271 Mafa-AG*05:01:01 182 bases
 GSHSMRYFYT AVSRPGRREP LFIAVGYVDD TQFVRFDSDA ESPRMEPRAP
 WVEQEGPEYW DRETQNMKTA TQTYRGNLRT ALRYYNQSEG GSHTIQKMYG
 CDLGPDGRLL RGYEQFAYDG RDYIALNEDL RSWTAADMAA QFTQRKWEAA
 RAAEQHRTYL EGECLEWLRR YLENGKETLQ RA* 
>DL;IPD:MHC04300
IPD:MHC04300 Mafa-AG*05:01:02 273 bases
 SHSMRYFYTA VSRPGRREPL FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 VEQEGPEYWD RETQNMKTAT QTYRGNLRTA LRYYNQSEGG SHTIQKMYGC
 DLGPDGRLLR GYEQFAYDGR DYIALNEDLR SWTAADMAAQ FTQRKWEAAR
 AAEQHRTYLE GECLEWLRRY LENGKETLQR ADPPKTHVTH HPVSDYEATL
 RCWALGFYPA GITLTWQRDG EEQTEDTELV ETRPTGDGTF QKWAAVVVPS
 GEEQRYTCHV QHEGLPKPLT LRW*  
>DL;IPD:MHC04276
IPD:MHC04276 Mafa-AG*05:02:01 182 bases
 GSHSMRYFYT AVSRPGRREP LFIAVGYVDD TQFVRFDSDA ESPRMEPRAP
 WVEQEGPEYW DRETQNMKTA TQTYRVNLRT ALRYYNQSEG GSHTIQKMYG
 CDLGPDGRLL RGYEQFAYDG RDYIALNEDL RSWTAADMAA QFTQRKWEAA
 RAAEQHRTYL EGECLEWLRR YLENGKETLQ RA* 
>DL;IPD:MHC04302
IPD:MHC04302 Mafa-AG*05:02:02 273 bases
 SHSMRYFYTA VSRPGRREPL FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 VEQEGPEYWD RETQNMKTAT QTYRVNLRTA LRYYNQSEGG SHTIQKMYGC
 DLGPDGRLLR GYEQFAYDGR DYIALNEDLR SWTAADMAAQ FTQRKWEAAR
 AAEQHRTYLE GECLEWLRRY LENGKETLQR ADPPKTHVTH HPVSDYEATL
 RCWALGFYPA EITLTWQRDG EEQTEDTELV ETRPTGDGTF QKWAAVVVPS
 GEEQRYTCHV RHEGLPKPLT LRW*  
>DL;IPD:MHC04424
IPD:MHC04424 Mafa-AG*05:02:03 181 bases
 SHSMRYFYTA VSRPGRREPL FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 VEQEGPEYWD RETQNMKTAT QTYRVNLRTA LRYYNQSEGG SHTIQKMYGC
 DLGPDGRLLR GYEQFAYDGR DYIALNEDLR SWTAADMAAQ FTQRKWEAAR
 AAEQHRTYLE GECLEWLRRY LENGKETLQR A* 
>DL;IPD:MHC04425
IPD:MHC04425 Mafa-AG*05:02:04 181 bases
 SHSMRYFYTA VSRPGRREPL FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 VEQEGPEYWD RETQNMKTAT QTYRVNLRTA LRYYNQSEGG SHTIQKMYGC
 DLGPDGRLLR GYEQFAYDGR DYIALNEDLR SWTAADMAAQ FTQRKWEAAR
 AAEQHRTYLE GECLEWLRRY LENGKETLQR A* 
>DL;IPD:MHC04303
IPD:MHC04303 Mafa-AG*05:03 273 bases
 SHSMRYFYTA VSRPGRREPL FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 VEQEGPEYWD RETQNMKTAT QTYRVNLRTA LRYYNQSEGG SHTIQKMYGC
 DLGPDGRLLR GYEQFAYDGR DYIALNEDLR SWTAADMAAQ FTQRKWEAAR
 AAEQHRTYLE GECLEWLRRY LENGKETLQR ADPPKTHVTH HPVSDYEATL
 RCWALGFYPA EITLTWQRDG EEQTEDTELV ETRPTGDGTF QKWAAAVVPS
 GEEQRYTCHV RHEGLPKPLT LRW*  
>DL;IPD:MHC04304
IPD:MHC04304 Mafa-AG*05:04 273 bases
 SHSMRYFYTA VSRPGRREPL FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 VEQEGPEYWD RETQNMKTAT QTYRGNLRTA LRYYNQSEGG SHTIQKMYGC
 DLGPDGRLLR GYEQLAYDGR DYIALNEDLR SWTAADMAAQ FTQRKWEAAR
 AAEQHRTYLE GKCLEWLRRY LENGKETLQR ADPPKTHVTH HPVSDYEATL
 RCWALGFYPA EITLTWQRDG EEQTEDTELV ETRPTGDGTF QKWAAVVVPS
 GEEQRYTCHV QHEGLPKPLT LRW*  
>DL;IPD:MHC04428
IPD:MHC04428 Mafa-AG*05:05 181 bases
 SHSMRYFYTA VSRPGRREPL FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 VEPEGPEYWD RETQNMKTAT QTYRGNLRTA LRYYNQSEGG SHTIQKMYGC
 DLGPDGRLLR GYEQFAYDGR DYIALNEDLR SWTAADMAAQ FTQRKWEAAR
 AAEQHRTYLE GECLEWLRRY LENGKETLQR A* 
>DL;IPD:MHC03842
IPD:MHC03842 Mafa-AG*06:01 340 bases
 MAVMAPRTLL LVLSGVLALT QTRAGSHSLR YFYTSMSRPG RWEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWVEQEG PEYWDRETQN MKTATQTYRV
 NLRTLLRYYN QSQGGSHTIQ KMYGCDLGPD GRLLRGHEQF AYDGRDYIAL
 NEDLRSWTAA DMAAQNTQRK WEAEDVAEQH RTYLEGECLE SLRRYLENGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAGITLT WQRDGEEQTQ
 DTELVETRPT GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQSTIPIVG IIAGLVLLGT VVTGAVVAAV MWRRKSSDRX *
>DL;IPD:MHC04269
IPD:MHC04269 Mafa-AG*06:02 182 bases
 GSHSMRYFYT SMSRPGRWEP RFIAVGYVDD TQFVRFDSDA ESPRMEPRAP
 WVEQEGPEYW DRETQNMKTA TQTYRVNLRT LLRYYNQSQG GSHTIQKMYG
 CDLGPDGRLL RGHEQFAYDG RDYIALNEDL RSWTAADMAA QNTQRKWEAE
 DVAEQHRTYL EGECLESLRR YLENGKETLQ RA* 
>DL;IPD:MHC04307
IPD:MHC04307 Mafa-AG*06:03 273 bases
 SHSMRYFYTS MSRPGRWEPR FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 VEQEGPEYWD RETQNMKTAT QTYRVNLRTL LRYYNQSQGG SHTIQKMYGC
 DLGPDGRLLR GHEQFAYDGR DYIALNEDLR SWTAADMAAQ NTQRKWEAAG
 VAEQHRTYLE GECLESLRRY LENGKETLQR ADPPKTHVTH HPVSDHEATL
 RCWALGFYPA GITLTWQRDG EEQTQDTELV ETRPTGDGTF QKWAAVVVPS
 GEEQRYTCHV QHEGLPKPLT LRW*  
>DL;IPD:MHC04639
IPD:MHC04639 Mafa-AG*06:04 181 bases
 SHSMRYFYTS MSRPGRGQPR FISVGYVDDT QFVRFDSDAE SPRMEPRAPW
 VEQEGPEYWD RETQNMKTAT QTYRVNLRTA LRYYNQSQGR SHTIQKMYGC
 DLGPDGRLLR GHEQFAYDGR DYIALNEDLR SWTAADMAAQ NTQRKWEAED
 VAEQHRTYLE GECLEWLRRH LENGKETLQR A* 
>DL;IPD:MHC04640
IPD:MHC04640 Mafa-AG*06:05 181 bases
 SHSMRYFYTS MSRPGRGQPR FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 VEQEGPEYWD RETQNMKTAT QTYRVNLRTL LRYYNQSQGR SHTIQKMYGC
 DLGPDGRLLR GHEQFAYDGS DYIALNEDLR SWTAADMAAQ NTQRKWEAED
 VAEQHRTYLE GECLEWLRRH LENGKETLQR A* 
>DL;IPD:MHC04305
IPD:MHC04305 Mafa-AG*07:01:01 273 bases
 SHSLRYFYTA VSRPGRGQPR FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 VEQEGPEYWD RETQNMKTAT QTYRVNLRTL LRYYNQSEAG SHTIQKMYGC
 DLGPDGRRLR GYEQFAYDGR DYIALNEDLR SWTAADMAAQ NTQRKWEAED
 VAEQHRTYLE GECLESLRRY LENGKETLQR ADPPKTHVTH HPVSDHEATL
 RCWALGFYPA EITLTWQRDG EEQTQDTELV ETRPTGDGTF QKWAAVVVPS
 GEEQRYTCHV QHEGLPKPLT LRW*  
>DL;IPD:MHC04308
IPD:MHC04308 Mafa-AG*07:01:02 273 bases
 SHSLRYFYTA VSRPGRGQPR FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 VEQEGPEYWD RETQNMKTAT QTYRVNLRTL LRYYNQSEAG SHTIQKMYGC
 DLGPDGRRLR GYEQFAYDGR DYIALNEDLR SWTAADMAAQ NTQRKWEAED
 VAEQHRTYLE GECLESLRRY LENGKETLQR ADPPKTHVTH HPVSDHEATL
 RCWALGFYPA EITLTWQRDG EEQTQDTELV ETRPTGDGTF QKWAAVVVPS
 GEEQRYTCHV QHEGLPKPLT LRW*  
>DL;IPD:MHC04430
IPD:MHC04430 Mafa-AG*07:02 181 bases
 SHSLRYFYTS MSRPGRGQPR FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 VEQEGPEYWD RETQNMKTAT QTYRVNLRTL LRYYNQSEAG SHTIQKMYGC
 DLGPDGRRLR GYEQFAYDGR DYIALNGDLR SWTAADMAAQ NTQRKWEAED
 VAEQHRTYLE GECLESLRRY LENGKETLQR A* 
