>DL;IPD:MHC04727
IPD:MHC04727 Mafa-DMB*03:01:01 282 bases
 GCGGCTTTGT GGCCCATGTG GAAAGCACCT GTCTACTGGA TGATGATGGG
 ACTGCAAAGG ATTTCACATA CTGTATCTCC TTCAACAAGG ATCTGCTGAC
 CTGCTGGGAT CCAGAGGAGA ACAAGATGGT CCCTTGCGAA TTTGGGGTGC
 TGAATCCCTT GGCCAATGGC ATCTCACATT ACCTCAACCA ACAGGACACC
 CTGATGCAGC GCTTGCGCAA TGGGCTTCAG AATTGTACCA CACACACCCA
 GCCCTTCTGG GGATCACTGA CCCACAGGAC AC* 
>DL;IPD:MHC04729
IPD:MHC04729 Mafa-DMB*03:01:02 282 bases
 GTGGCTTTGT GGCCCATGTG GAAAGCACCT GTCTACTGGA TGATGATGGG
 ACTGCAAAGG ATTTCACATA CTGTATCTCC TTCAACAAGG ATCTGCTGAC
 CTGCTGGGAT CCAGAGGAGA ACAAGATGGT CCCTTGCGAA TTTGGGGTGC
 TGAATCCCTT GGCCAATGGC ATCTCACATT ACCTCAACCA ACAGGACACC
 CTGATGCAGC GCTTGCGCAA TGGGCTTCAG AATTGTACCA CACACACCCA
 GCCCTTCTGG GGATCACTGA CCCACAGGAC AC* 
>DL;IPD:MHC04733
IPD:MHC04733 Mafa-DMB*03:01:03 282 bases
 GTGGCTTTGT GGCCCATGTG GAAAGCACCT GTCTACTGGA TGATGATGGG
 ACTGCGAAGG ATTTCACATA CTGTATCTCC TTCAACAAGG ATCTGCTGAC
 CTGCTGGGAT CCAGAGGAGA ACAAGATGGT CCCTTGCGAA TTTGGGGTGC
 TGAATCCCTT GGCCAATGGC ATCTCACATT ACCTCAACCA ACAGGACACC
 CTGATGCAGC GCTTGCGCAA TGGGCTTCAG AATTGTACCA CACACACCCA
 GCCCTTCTGG GGATCACTGA CCCACAGGAC AC* 
>DL;IPD:MHC04728
IPD:MHC04728 Mafa-DMB*03:02:01 282 bases
 GTGGCTTTGT GGCCCATGTG GAAAGCACCT GTCTACTGGA TGATGATGGG
 ACTGCAAAGG ATTTCACATA CTGTATCTCC TTCAACAAGG ATCTGCTGAC
 CTGCTGGGAT CCAGAGGAGA ACAAGATGGT CCCTTGCGAA TTTGGGGTGC
 TGAATCCCGT GGCCAATGGC ATCTCACATT ACCTCAACCA ACAGGACACC
 CTGATGCAGC GCTTGCGCAA TGGGCTTCAG AATTGTACCA CACACACCCA
 GCCCTTCTGG GGATCACTGA CCCACAGGAC AC* 
>DL;IPD:MHC04732
IPD:MHC04732 Mafa-DMB*03:02:02 282 bases
 GTGGCTTTGT GGCCCATGTG GAAAGCACCT GTCTACTGGA TGATGATGGG
 ACTGCGAAGG ATTTCACATA CTGTATCTCC TTCAACAAGG ATCTGCTGAC
 CTGCTGGGAT CCAGAGGAGA ACAAGATGGT CCCTTGCGAA TTTGGGGTGC
 TGAATCCCGT GGCCAATGGC ATCTCACATT ACCTCAACCA ACAGGACACC
 CTGATGCAGC GCTTGCGCAA TGGGCTTCAG AATTGTACCA CACACACCCA
 GCCCTTCTGG GGATCACTGA CCCACAGGAC AC* 
>DL;IPD:MHC04730
IPD:MHC04730 Mafa-DMB*03:03 282 bases
 GTGGCTTTGT GGCCCATGTG GAAAGCACCT GTCTACTGGA TGATGATGGG
 ACTGCAAAGG ATTTCACATA CTGTATCTCC TTCAACAAGG ATCTGCTGAC
 CTGCTGGGAT CCAGAGGAGA ACAAGATGGT CCCTTGCGAA TTTGGGGTGC
 TGAATCCCTT GGCCAATGGC ATCTCACATT ACCTCAACCT ACAGGACACC
 CTGATGCAGC GCTTGCGCAA TGGGCTTCAG AATTGTACCA CACACACCCA
 GCCCTTCTGG GGATCACTGA CCCACAGGAC AC* 
>DL;IPD:MHC04731
IPD:MHC04731 Mafa-DMB*03:04 282 bases
 GTGGCTTTGT GGCCCATGTG GAAAGCACCT GTCTACTGGA TGATGATGGG
 ACTGCAAAGG ATTTCACATA CTGTATCTCC TTCAACAAGT GTCTGCTGAC
 CTGCTGGGAT CCAGAGGAGA ACAAGATGGT CCCTTGCACA TTTGGGGTGC
 TGAATCCCTT GGCCAATGGC ATCTCACATT ACCTCAACCA ACAGGACACC
 CTGATGCAGC GCTTGCGCAA TGGGCTTCAG AATTGTACCA CACACACCCA
 GCCCTTCTGG GGATCACTGA CCCACAGGAC AC* 
