>DL;IPD:MHC04806
IPD:MHC04806 Mafa-F*01:01 80 bases
 APTPCGILAP LCRGPAAGSP GTGTSRWSTW TTRSSCGSTA TPRFRGWSRG
 RRGWSKRGRS IGSGPQGTPR PTHGLTEWPX * 
>DL;IPD:MHC04807
IPD:MHC04807 Mafa-F*01:02:01 336 bases
 MAPRTLLLVL SGALALTETW AGSHSLRYFS TAVSRPGRRE PQYRYIAVEY
 VDDTQFLRFD SDAAIPRMEP RAPWVEQEGP QYWERTTGYA KANARTDRVA
 LRKLLLRYNQ SEAGSHTLQG MNGCDMGPDG RLLRGYHQHA YDGKDYISLN
 EDLRSWTAAD TVARITQRFY EAEEYAEEFR TYLEGECLEL LRRYLENGKE
 TLQRADPPKA HVAHHPISDR EATLRCWALG FYPAEITLTW QRDGEEQTQD
 TELVETRPAG DGTFQKWAAV VVPSGEEQRY TCHVQHEGLP QPLTLRWESS
 SQPTIPIVGI VAGLAVLAVV VTGAVVAAVM WRRKSS* 
>DL;IPD:MHC04813
IPD:MHC04813 Mafa-F*01:02:02 336 bases
 MAPRTLLLVL SGALALTETW AGSHSLRYFS TAVSRPGRRE PQYRYIAVEY
 VDDTQFLRFD SDAAIPRMEP RAPWVEQEGP QYWERTTGYA KANARTDRVA
 LRKLLLRYNQ SEAGSHTLQG MNGCDMGPDG RLLRGYHQHA YDGKDYISLN
 EDLRSWTAAD TVARITQRFY EAEEYAEEFR TYLEGECLEL LRRYLENGKE
 TLQRADPPKA HVAHHPISDR EATLRCWALG FYPAEITLTW QRDGEEQTQD
 TELVETRPAG DGTFQKWAAV VVPSGEEQRY TCHVQHEGLP QPLTLRWESS
 SQPTIPIVGI VAGLAVLAVV VTGAVVAAVM WRRKSS* 
>DL;IPD:MHC04808
IPD:MHC04808 Mafa-F*01:03 336 bases
 MAPRTLLLVL SGALALTETW AGSHSLRYFS TAVSRPGRRE PQYRYIAVEY
 VDDTQFLRFD SDAAIPRMEP RAPWVEQEGP QYWERTTGYA KANARTDRVA
 LRKLLLRYNQ SEAGSHTLQG MNGCDMGPDG RLLRGYHQHA YDGKDYISLN
 EDLRSWTAAD TVARITQRFY EAEEYAEEFR TYLEGECLEL LRRYLENGKE
 TLQRADPPKA HVAHHPISDR EATLRCWALG FYPAEITLTW QRDGEEQTQD
 TELVETRPAG DGTFQKWAAV VVPSGEEQRY TCHVQHEGLP QPLTLRWESS
 SQPTIPIVGI VAGLAVLAVV VTGAVVTAVM WRRKSS* 
>DL;IPD:MHC04809
IPD:MHC04809 Mafa-F*01:04 336 bases
 MAPRTLLLVL SGALALTETW AGSHSLRYFS TAVSRPGRRE PRYRYIAVEY
 VDDTQFLRFD SDAAIPRMEP RAPWVEQEGP QYWERTTGYA KANARTDRVA
 LRKLLLRYNQ SEAGSHTLQG MNGCDMGPDG RLLRGYHQHA YDGKDYISLN
 EDLRSWTAAD TVARITQRFY EAEEYAEEFR TYLEGECLEL LRRYLENGKE
 TLQRADPPKA HVAHHHISDR EATLRCWALG FYPAEITLTW QRDGEEQTQD
 TELVETRPAG DGTFQKWAAV VVPSGEEQRY TCHVQHEGLP QPLTLRWESS
 SQPTIPIVGI VAGLAVLAVV VTGAVVAAVM WKRKSS* 
>DL;IPD:MHC04810
IPD:MHC04810 Mafa-F*01:05 336 bases
 MAPRTLLLVL SGALALTETW AGSHSLRYFS TAVSRPGRRE PQYRYIAVEY
 VDDTQFLRFD SDAAIPRMEP RAPWVEQEGP QYWERTTGYA KANARTDRVA
 LRKLLLRYNQ SEAGSHTLQG MNGCDMGPDG RLLRGYHQHA YDGKDYISLN
 EDLRSWTAAD TVARITQRFY EAEEYAEEFR TYLEGECLEL LRRYLENGKE
 TLQRADPPKA HVVHHPISDR EATLRCWALG FYPAEITLTW QRDGEEQTQD
 TELVETRPAG DGTFQKWAAV VVPSGEEQRY TCHVQHEGLP QPLTLRWESS
 SQPTIPIVGI VAGLAVLAVV VTGAVVAAVM WRRKSS* 
>DL;IPD:MHC04811
IPD:MHC04811 Mafa-F*01:06 336 bases
 MAPRTLLLVL SGALALTETW AGSHSLRYFS TAVSRPGRRE PRYRYIAVEY
 VDDTQFLRFD SDAAIPRMEP RAPWVEQEGP QYWERTTGYA KANARTDRVA
 LRKLLLRYNQ SEAGSHTLQG MNGCDMGPDG RLLRGYHQHA YDGKDYISLN
 EDLRSWTAAD TVARITQRFY EAEEYAEEFR TYLEGECLEL LRRYLENGKE
 TLQRADPPKA HVAHHPISDR EATLRCWALG FYPAEITLTW QRDGEEQTQD
 TELVETRPAG DGTFQKWAAV VVPSGEEQRY TCHVQHEGLP QPLTLRWESS
 SQPTIPIVGI VAGLAVLAVV VTGAVVAAVM WKRKSS* 
>DL;IPD:MHC04812
IPD:MHC04812 Mafa-F*01:07 336 bases
 MAPRTLLLVL SGALALTETW AGSHSLRYFS TAVSRPGRRE PRYRYIAVEY
 VDDTQFLRFD SDAAIPRMEP RALWVEQEGP QYWERTTGYA KANARTDRVA
 LRKLLLRYNQ SEAGSHTLQG MNGCDMGPDG RLLRGYHQHA YDGKDYISLN
 EDLRSWTAAD TVARITQRFY EAEEYAEEFR TYLEGECLEL LRRYLENGKE
 TLQRADPPKA HVAHHHISDR EATLRCWALG FYPAEITLTW QRDGEEQTQD
 TELVETRPAG DGTFQKWAAV VVPSGEEQRY TCHVQHEGLP QPLTLRWESS
 SQPTIPIVGI VAGLAVLAVV VTGAVVAAVM WKRKSS* 
