>DL;IPD:MHC00346
IPD:MHC00346 Mafa-G*02:01 123 bases
 AVSRPGRGEP RFIAVGYVDD TQFVRLDSDA ASLRMEPRGP WVDQEGPEYW
 EEETRIAKAH AQTDRVNLRT LRSCYNQSEA GSHTLQWMIG CDLGPDGRLL
 CRCEQFAYDG KDYLALNEDL CSX*  
>DL;IPD:MHC00347
IPD:MHC00347 Mafa-G*02:02 154 bases
 AMSRPGRGEP RFIAVGYVDD TQFVRLDSDA ASLRMEPRGP WVDQERPEYW
 EEETRIAKAH AQTDRVNLRT LRSCYNQSEA GPHTLQWMIG CDLGPDGRLL
 CRCEQFAYDG KDYLALNEDL LSWTAADTVA QISKRKREAA KATERRRAYL
 EGTX*    
>DL;IPD:MHC00348
IPD:MHC00348 Mafa-G*02:03 123 bases
 AVSRPGRGEL RFIAVGYVDD TQFVRLDSYA ASPRMEPRVP WVEQEGPEYW
 EEETRIAKAH AHTDRVNLRT LRSYYNQSEA GSHTLQWMIG CDLGPDGRLL
 CRCEQFAYDG KDYLALNEDL CSX*  
>DL;IPD:MHC00349
IPD:MHC00349 Mafa-G*02:04 123 bases
 AVSRPGRGEL RFIAVGYVDD TQFVRLDSYA ASPRMEPRVP WVEQEGPEYW
 EEETRIAKAH AHTDRVNLRT LRSYYNQSEA GSHTLQWMIG CDLGPDGRLL
 CRCEQFAYDG KDYLALNEDL CSX*  
>DL;IPD:MHC04278
IPD:MHC04278 Mafa-G*02:05:01:01 132 bases
 GSHSMRYFSA AESQPGRGEP RFIPVGYVDD TQFVWLDSYA ASLRMERRAP
 WVEQEGPEYW EEETRIAKAH AQTDRVNQRT LRSCYNQSEA GSHTLQWMIG
 CDLGPDGRLF RCEPFAYDGK DYLALKEDLC SX* 
>DL;IPD:MHC04279
IPD:MHC04279 Mafa-G*02:05:01:02 132 bases
 GSHSMRYFSA AESQPGRGEP RFIPVGYVDD TQFVWLDSYA ASLRMERRAP
 WVEQEGPEYW EEETRIAKAH AQTDRVNQRT LRSCYNQSEA GSHTLQWMIG
 CDLGPDGRLF RCEPFAYDGK DYLALKEDLC SX* 
>DL;IPD:MHC04280
IPD:MHC04280 Mafa-G*02:06 132 bases
 GSHSMRYFSA AESQPGRGEP RFIAVGYVDD TQFVWLDSYA ASLRMEPRAP
 WVEQERPEYW EEQTRMAKAH AQTDRVNQRT LRSCYNQSEA GSHTLQWMIG
 CDLGPDGRLF RCEPFAYDGK DYLALKEDLC SX* 
>DL;IPD:MHC04281
IPD:MHC04281 Mafa-G*02:07 117 bases
 GSHSMRYFSA AVSQPGRGEP RFIPVGYVDY TQFVWLDSYA ASLRMEPRGP
 WVEQERPEYW EEQTRMGKAH AQTDRVNQRT LRSCYNQSEA GYHTLQWMIG
 CDLGPDGRLF RCEQFAX*   
>DL;IPD:MHC04282
IPD:MHC04282 Mafa-G*02:08 132 bases
 GSHSMRYFSA AESQPGRGEP RFIPVGYVDD TQFVWLDSYA ASLRMERRAP
 WVEQEGPEYW EEETRIAKAH AQTDRVNQRT LRSCYNQSEA GSHTLQWMIG
 CDLGPDGRLF RCEPFAYDGK DYLALKEDLC SX* 
>DL;IPD:MHC04283
IPD:MHC04283 Mafa-G*02:09 132 bases
 GSHSMRYFSA AVSRPGRGEP RFIPVGYVDD TQFVWLDSYA ASLRMEPRAP
 WVEQEGPEYW EEETRIAKAH AHTDRVNQRT LRSCYNQSEA GSHTLQWMIG
 CDLGSDGRLF RCEPFAYDGK DYLALKEDLC SX* 
