>DL;IPD:MHC04623
IPD:MHC04623 Mafa-DOA*01:01:01 248 bases
 GCTGACCACA TGGGCTCCTA CGGACCCGCC TTCTACCAGT CTTACGGTGC
 CTCGGGCCAG TTCACCCATG AATTTGATGG GGAACAGCTG TTCTCTGTGG
 ACCTGAAGAA AAGCGAGGCT GTGTGGCGTC TGCCTGAGTT TGGCGACTCT
 GCCCGCTTTG ACCCGCAGGG TGGGCTGGCC GGCATCGCCG CGATCAAAGC
 CCATCTGGAT GTCCTGGTGG AGCGCTCCAA CCGCACCAGA GCCATCAA*
>DL;IPD:MHC04625
IPD:MHC04625 Mafa-DOA*01:01:02 248 bases
 GCTGACCACA TGGGCTCCTA CGGACCCGCC TTCTACCAGT CTTACGGTGC
 CTCGGGCCAG TTCACCCATG AATTTGATGG GGAACAGCTG TTCTCTGTGG
 ACCTGAAGAA AAGCGAGGCT GTGTGGCGTC TGCCTGAGTT TGGCGACTCT
 GCCCGCTTTG ACCCGCAGGG TGGGCTGGCC GGCATCGCTG CGATCAAAGC
 CCATCTGGAC GTCCTGGTGG AGCGCTCCAA CCGCACCAGA GCCATCAA*
>DL;IPD:MHC04634
IPD:MHC04634 Mafa-DOA*01:01:03 248 bases
 GCTGACCACA TGGGCTCCTA CGGACCCGCC TTCTACCAGT CTTACGGTGC
 CTCGGGCCAG TTCACCCATG AATTTGATGG GGAACAGCTG TTCTCTGTGG
 ACCTGAAGAA AAGCGAGGCT GTGTGGCGTC TGCCTGAGTT TGGCGACTCT
 GCCCGCTTTG ACCCGCAGGG TGGGCTGGCT GGCATCGCTG CGATCAAAGC
 CCATCTGGAC GTCCTGGTGG AGCGCTCCAA CCGCACCAGA GCCATCAA*
>DL;IPD:MHC04627
IPD:MHC04627 Mafa-DOA*01:02:01 248 bases
 GCTGACCACA TGGGCTCCTA CGGACCCGCC TTCTACCAGT CTTACGGTGC
 CTCGGGCCAG TTCACCCATG AATTTGATGG GGAACAGCTG TTCTCTGTGG
 ACCTGAAGAA AAGCGAGGCT GTGTGGCGTC TGCCTGAGTT TGGCGACTTT
 GCCCGCTTTG ACCCACAGGG TGGGCTGGCC GGCATCGCCG CGATCAAAGC
 CCATCTGGAT GTCCTGGTGG AGCGCTCCAA CCGCACCAGA GCCATCAA*
>DL;IPD:MHC04629
IPD:MHC04629 Mafa-DOA*01:02:02 248 bases
 GCTGACCACA TGGGCTCCTA CGGACCCGCC TTCTACCAGT CTTACGGTGC
 CTCGGGCCAG TTCACCCATG AATTTGATGG GGAACAGCTG TTCTCTGTGG
 ACCTGAAGAA AAGCGAGGCT GTGTGGCGTC TGCCTGAGTT TGGCGACTTT
 GCCCGCTTTG ACCCACAGGG TGGGCTGGCC GGCATCGCCG CAATCAAAGC
 CCATCTGGAT GTCCTGGTGG AGCGCTCCAA CCGCACCAGA GCCATCAA*
>DL;IPD:MHC04630
IPD:MHC04630 Mafa-DOA*01:02:03 247 bases
 CTGACCACAT GGGCTCCTAC GGACCCGCCT TCTACCAGTC TTACGGCGCC
 TCGGGCCAGT TCACCCATGA ATTTGATGGG GAACAGCTGT TCTCTGTGGA
 CCTGAAGAAA AGCGAGGCTG TGTGGCGTCT GCCTGAGTTT GGCGACTTTG
 CCCGCTTTGA CCCACAGGGT GGGCTGGCCG GCATCGCCGC GATCAAAGCC
 CATCTGGATG TCCTGGTGGA GCGCTCCAAC CGCACCAGAG CCATCAA*
>DL;IPD:MHC04632
IPD:MHC04632 Mafa-DOA*01:02:04 248 bases
 GCTGACCACA TGGGCTCCTA CGGACCCGCC TTCTACCAGT CTTACGGTGC
 CTCCGGCCAG TTCACCCATG AATTTGATGG GGAACAGCTG TTCTCTGTGG
 ACCTGAAGAA AAGCGAGGCT GTGTGGCGTC TGCCTGAGTT TGGCGACTTT
 GCCCGCTTTG ACCCGCAGGG TGGGCTGGCC GGCATCGCCG CGATCAAAGC
 CCATCTGGAT GTCCTGGTGG AGCGCTCCAA CCGCACCAGA GCCATCAA*
>DL;IPD:MHC04633
IPD:MHC04633 Mafa-DOA*01:02:05 248 bases
 GCTGACCACA TGGGCTCCTA CGGACCCGCC TTCTACCAGT CTTACGGTGC
 CTCAGGCCAG TTCACCCATG AATTTGATGG GGAACAGCTG TTCTCTGTGG
 ACCTGAAGAA AAGCGAGGCT GTGTGGCGTC TGCCTGAGTT TGGCGACTTT
 GCCCGCTTTG ACCCACAGGG TGGGCTGGCC GGCATCGCCG CGATCAAAGC
 CCATCTGGAT GTCCTGGTGG AGCGCTCCAA CCGCACCAGA GCCATCAA*
>DL;IPD:MHC04635
IPD:MHC04635 Mafa-DOA*01:02:06 248 bases
 GCTGACCACA TGGGCTCCTA CGGACCCGCC TTCTACCAGT CTTACGGCGC
 CTCGGGCCAG TTCACCCATG AATTTGATGG GGAACAGCTG TTTTCTGTGG
 ACCTGAAGAA AAGCGAGGCT GTGTGGCGTC TGCCTGAGTT TGGCGACTTT
 GCCCGCTTTG ACCCGCAGGG TGGGCTGGCC GGCATCGCCG CGATCAAAGC
 CCATCTGGAT GTCCTGGTGG AGCGCTCCAA CCGCACCAGA GCCATCAA*
>DL;IPD:MHC04636
IPD:MHC04636 Mafa-DOA*01:02:07 248 bases
 GCTGACCACA TGGGCTCCTA CGGACCCGCC TTCTACCAGT CTTACGGTGC
 CTCGGGCCAG TTCACCCATG AATTTGATGG GGAACAGCTG TTCTCTGTGG
 ACCTGAAGAA AAGCGAGGCT GTGTGGCGTC TGCCTGAGTT TGGCGACTTT
 GCCCGCTTTG ACCCGCAGGG TGGGCTGGCC GGCATCGCCG CGATCAAAGC
 CCATCTGGAT GTCCTGGTGG AGCGCTCCAA CCGCACCAGA GCCATCAA*
>DL;IPD:MHC04637
IPD:MHC04637 Mafa-DOA*01:02:08 248 bases
 GCTGACCACA TGGGCTCCTA CGGACCCGCC TTCTACCAGT CTTACGGTGC
 CTCAGGCCAG TTCACCCATG AATTTGATGG GGAACAGCTG TTCTCTGTGG
 ACCTGAAGAA AAGCGAGGCT GTGTGGCGTC TGCCTGAGTT TGGCGACTTT
 GCCCGCTTTG ACCCGCAGGG TGGGCTGGCC GGCATCGCCG CGATCAAAGC
 CCATCTGGAT GTCCTGGTGG AGCGCTCCAA CCGCACCAGA GCCATCAA*
>DL;IPD:MHC04626
IPD:MHC04626 Mafa-DOA*01:03:01 248 bases
 GCTGACCACA TGGGCTCCTA CGGACCCGCC TTCTACCAGT CTTATGGTGC
 CTCGGGCCAG TTCACTCATG AATTTGATGG GGAACAGCTG TTCTCTGTGG
 ACCTGAAGAA AAGCGAGGCT GTGTGGCGTC TGCCTGAGTT TGGCGACTCT
 GCCCGCTTTG ACCCGCAGGG TGGGCTGGCC GGCATCGCCG CGATCAAAGC
 CCATCTGGAT GTCCTGGTGG AGCGCTCCAA CCACACCAGA GCCATCAA*
>DL;IPD:MHC04628
IPD:MHC04628 Mafa-DOA*01:03:02 248 bases
 GCTGACCACA TGGGCTCCTA CGGACCCGCC TTCTACCAGT CTTACGGTGC
 CTCCGGCCAG TTCACTCATG AATTTGATGG GGAACAGCTG TTCTCTGTGG
 ACCTGAAGAA AAGCGAGGCT GTGTGGCGTC TGCCTGAGTT TGGCGACTCT
 GCCCGCTTTG ACCCGCAGGG TGGGCTGGCC GGCATCGCCG CGATCAAAGC
 CCATCTGGAT GTCCTGGTGG AGCGCTCCAA CCACACCAGA GCCATCAA*
>DL;IPD:MHC04624
IPD:MHC04624 Mafa-DOA*01:04 248 bases
 GCTGACCACA TGGGCTCCTA CGGACCCGCC TTCTACCAGT CTTACGGTGC
 CTCGGGCCAG TTCACCCATG AATTTGATGG GGAACAGCTG TTCTCTGTGG
 ACCTGAAGAA AAGCGAGGCT GTGTGGCGTC TGCCTGAGTT TGGCGACTTT
 GCCCGCTTTG ACCCGCAGAG TGGGCTGGCC GGCATCGCCG CGATCAAAGC
 CCATCTGGAT GTCCTGGTGG AGCGCTCCAA CCGCACCAGA GCCATCAA*
>DL;IPD:MHC04631
IPD:MHC04631 Mafa-DOA*01:05 248 bases
 GCTGACCACA TGGGCTCCTA CGGACCCGCC TTCTACCAGT CTTACGGCTT
 CTCAGGCCAG TTCACCCATG AATTTGATGG GGAACAGCTG TTCTCTGTGG
 ACCTGAAGAA AAGCGAGGCT GTGTGGCGTC TGCCTGAGTT TGGCGACTTT
 GCCCGCTTTG ACCCGCAGGG TGGGCTGGCC GGCATCGCCG CGATCAAAGC
 CCATCTGGAC GTCCTGGTGG AGCGCTCCAA CCGCACCAGA GCCATCAA*
