>DL;IPD:MHC00272
IPD:MHC00272 Mafa-DPA1*02:01 261 bases
 MRPEDRMFQT RAVILRTLSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT
 GEYMFEFDED EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN
 LNITIQRSNY TQAANDPPEV TVFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGQPAT EGVAESLFLP RTDYSFHKFH YLTFVPSAED YYDCRVEHWG
 LDQPLLKHWE AQEPIQMPET RETVLCALGL VLGLVGIIVG TVLIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC01614
IPD:MHC01614 Mafa-DPA1*02:02 261 bases
 MCPEDRMFQT RSVILRTLSL AFLLSLRGAG AIKADHVSTY ALFVQTHRPT
 GEYMFEFDED EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LDDIATLKYN
 LNITIQRSNH TQAANDPPEV TVFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGEPVT EGVAESLFLP RTDYSFHKFH YLTFVPSAED FYDCRVEHWG
 LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG TVLIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC01616
IPD:MHC01616 Mafa-DPA1*02:03 261 bases
 MHPEDRMFET RAVILRTLSL ALLLSLGGAG AIKADHVSTY ALFVQTHRPT
 GEYMFEFDED EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LDDIATLKYN
 LNITIQRSNH TQAANDPPEV TVFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGEPVT EGVAESLFLP RTDYSFHKFH YLTFVPSAED FYDCRVEHWG
 LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG TVLIIKSLHS
 GRDPRAQGPL X*   
>DL;IPD:MHC02058
IPD:MHC02058 Mafa-DPA1*02:04 261 bases
 MRPEDRMFQT RAVILRTLSL AFLLSLRGAG AIKADHVSTY AMFVQTHRPT
 GEYMFEFDED EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN
 LNITIRRSNY TQAANDPPEV TMFPKEPVEL GQPNTLICHI DKFFPPVLNA
 TWLCNGQPVT EGVAESLFLP RTDYSFHKFH YLTFVPSAED YYDCRVEHWG
 LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG TVLIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC02059
IPD:MHC02059 Mafa-DPA1*02:05 261 bases
 MRPEDRMFQT RAVILRTLSL AFLLSLRGAG AIKADHVSTY AMFVQTHRPT
 GEYMFEFDED EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN
 LNITIRRSNY TQAANDPPEV TMFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGQPVT EGVAESLFLP RTDYSFHKFH YLTFVPSAED YYDCRVEHWG
 LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG TVLIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC03706
IPD:MHC03706 Mafa-DPA1*02:06:01 261 bases
 MHPEDRMFQT RAVILRTLSL ALLLSLGGAG AIKADHVSTY ATFVQTHRPT
 GEFMFEFDED EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN
 LNITIRRSNY TQAANDPPEV TVFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGQPAT EGVAESLFLP RTDYSFHKFH YLTFVPSAED YYDCRVEHWG
 LDQPLLKHWE AQEPIQMPET RETVLCALGL VLGLVGIIVG TVLIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC04120
IPD:MHC04120 Mafa-DPA1*02:06:02 261 bases
 MHPEDRMFQT RAVILRTLSL ALLLSLGGAG AIKADHVSTY ATFVQTHRPT
 GEFMFEFDED EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN
 LNITIRRSNY TQAANDPPEV TVFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGQPAT EGVAESLFLP RTDYSFHKFH YLTFVPSAED YYDCRVEHWG
 LDQPLLKHWE AQEPIQMPET RETVLCALGL VLGLVGIIVG TVLIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC03707
IPD:MHC03707 Mafa-DPA1*02:07 255 bases
 MFQTRAIVLR TLSLAFLLSL RGAGAIKADH VSTYAAFVQT HRPTGEYMFE
 FDEDEQFYVD LDKKETVWHL EEFGRAFSFE AQGGLANIAI LNNNLNITIQ
 RSNYTQAAND PPEVTVFPKE PVELGQPNTL ICHIDKFFPP VLNVTWLCNG
 QPATEGVAES LFLPRTDYSF HKFHYLTFVP SAEDYYDCRV EHWGLDQPLL
 KHWEAQEPIQ MPETTETVLC ALGLVLGLVG IIVGTVLIIK SLRSGRDPRA
 QGPLX*    
>DL;IPD:MHC03710
IPD:MHC03710 Mafa-DPA1*02:08:01 261 bases
 MHPEDRMFQT RAVILRTLSL ALLLSLGGAG AIKADHVSTY ATFVQTHRPT
 GEFMFEFDED EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN
 LNITIRRSNY TQAANDPPEV TVFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGQPAT EGVAESLFLP RTDYSFHKFH YLTFVPSAED YYDCRVEHWG
 LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG TVLIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC03720
IPD:MHC03720 Mafa-DPA1*02:08:02 261 bases
 MHPEDRMFQT RAVILRTLSL ALLLSLGGAG AIKADHVSTY ATFVQTHRPT
 GEFMFEFDED EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN
 LNITIRRSNY TQAANDPPEV TVFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGQPAT EGVAESLFLP RTDYSFHKFH YLTFVPSAED YYDCRVEHWG
 LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG TVLIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC03711
IPD:MHC03711 Mafa-DPA1*02:09:01 261 bases
 MRPEDRMFQT RAVILRTLSL AFLLSLRGAG AIKADHVSTY ALFVQTHRPT
 GEFMFEFDED EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN
 LNITIQRSNY TQAANDPPEV TVFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGEPVT EGVAESLFLP RTDYSFHKFH YLTFVPSAED YYDCRVEHWG
 LDQPLLKHWE AQEPIQIPET TETVLCALGL VLGLVGIIVG TVLIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC05213
IPD:MHC05213 Mafa-DPA1*02:09:02 261 bases
 MRPEDRMFQT RAVILRTLSL AFLLSLRGAG AIKADHVSTY ALFVQTHRPT
 GEFMFEFDED EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN
 LNITIQRSNY TQAANDPPEV TVFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGEPVT EGVAESLFLP RTDYSFHKFH YLTFVPSAED YYDCRVEHWG
 LDQPLLKHWE AQEPIQIPET TETVLCALGL VLGLVGIIVG TVLIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC03712
IPD:MHC03712 Mafa-DPA1*02:10 261 bases
 MRPEDRMFET RAVILRTLSL ALLLSLGGAG AIKADHVSTY ALFVQTHRPT
 GEFMFEFDED EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNHN
 LNITIQRSNY TQAANDPPEV TVFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGEPVT EGVAESLFLP RTDYSFHKFH YLTFVPSAED YYDCRVEHWG
 LDQPLLKHWE AQEPIQIPET TETVLCALGL VLGLVGIIVG TVLIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC03715
IPD:MHC03715 Mafa-DPA1*02:11 261 bases
 MCPEDRMFQT RAVILRTLSL AFLLSLRGAG AIKADHVSTY ATFVQTHRPT
 GEFMFEFDED EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN
 LNITIRRSNY TQAANDPPEV TVFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGQPAT EGVAESLFLP RTDYSFHKFH YLTFVPSAED YYDCRVEHWG
 LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG TVLIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC03716
IPD:MHC03716 Mafa-DPA1*02:12 261 bases
 MRPEDRMFQT RAVILRTLSL AFLLSLGGAG AIKADHVSTY AMFVQTHRPT
 GEFMFEFDED EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN
 LNITIQRSNY TQAANDPPEV TVFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGEPVT EGVAESLFLP RTDYSFHKFH YLTFVPSAED YYDCRVEHWG
 LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG TVLIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC03717
IPD:MHC03717 Mafa-DPA1*02:13:01 261 bases
 MCPEDRMFQT RAVILRTLSL AFLLSLRGAG AIKADHVSTY AMFVQTHRPT
 GEYMFEFDED EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN
 LNITIRRSNY TQAANDPPEV TMFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGQPVT EGVAESLFLP RTDYSFHKFH YLTFVPSAED YYDCRVEHWG
 LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIMG TVLIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC04119
IPD:MHC04119 Mafa-DPA1*02:13:02 261 bases
 MCPEDRMFQT RAVILRTLSL AFLLSLRGAG AIKADHVSTY AMFVQTHRPT
 GEYMFEFDED EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN
 LNITIRRSNY TQAANDPPEV TMFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGQPVT EGVAESLFLP RTDYSFHKFH YLTFVPSAED YYDCRVEHWG
 LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIMG TVLIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC03718
IPD:MHC03718 Mafa-DPA1*02:14 261 bases
 MRPEDRMFQT RAVILRTLSL ALLLSLGGAG AIKADHVSTY ALFVQTHRPT
 GEFMFEFDED EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNHN
 LNITIQRSNY TQAANDPPEV TVFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGEPVT EGVAESLFLP RTDYSFHKFH YLTFVPSAED YYDCRVEHWG
 LDQPLLKHWE AQEPIQIPET TETVLCALGL VLGLVGIIVG TVLIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC03721
IPD:MHC03721 Mafa-DPA1*02:15:01 255 bases
 MFQTRAIVLR TLSLAFLLSL RGAGAIKADH VSTYATFVQT HRPTGEFMFE
 FDEDEQFYVD LDKKETVWHL EEFGRAFSFE AQGGLANIAI LNNNLNITIR
 RSNYTQAAND PPEVTVFPKE PVELGQPNTL ICHIDKFFPP VLNVTWLCNG
 QPATEGVAES LFLPRTDYSF HKFHYLTFVP SAEDYYDCRV EHWGLDQPLL
 KHWEAQEPIQ MPETTETVLC ALGLVLGLVG IIVGTVLIIK SLRSGRDPRA
 QGPLX*    
>DL;IPD:MHC04736
IPD:MHC04736 Mafa-DPA1*02:15:02 255 bases
 MFQTRAIVLR TLSLAFLLSL RGAGAIKADH VSTYATFVQT HRPTGEFMFE
 FDEDEQFYVD LDKKETVWHL EEFGRAFSFE AQGGLANIAI LNNNLNITIR
 RSNYTQAAND PPEVTVFPKE PVELGQPNTL ICHIDKFFPP VLNVTWLCNG
 QPATEGVAES LFLPRTDYSF HKFHYLTFVP SAEDYYDCRV EHWGLDQPLL
 KHWEAQEPIQ MPETTETVLC ALGLVLGLVG IIVGTVLIIK SLRSGRDPRA
 QGPLX*    
>DL;IPD:MHC03722
IPD:MHC03722 Mafa-DPA1*02:16 261 bases
 MHPEDRMFET RAVILRTLSL ALLLSLGGAG AIKADHVSTY ALFVQTHRPT
 GEFMFEFDED EMFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN
 LNITIRRSNY TQAANDPPEV TVFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGQPAT EGVAESLFLP RTDYSFHKFH YLTFVPSAED YYDCRVEHWG
 LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG TVLIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC03723
IPD:MHC03723 Mafa-DPA1*02:17 261 bases
 MRPEDRMFET RAVILRTLSL ALLLSLGGAG AIKADHVSTY AMFVQTHRPT
 GEYMFEFDED EMFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN
 LNITIRRSNY TQAANDPPEV TMFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGQPVT EGVAESLFLP RTDYSFHKFH YLTFVPSAED YYDCRVEHWG
 LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG TVLIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC03724
IPD:MHC03724 Mafa-DPA1*02:18 261 bases
 MHPEDRMFET RAVILRTLSL ALLLSLGGAG AIKADHVSTY AMFVQTHRPT
 GEYMFEFDED EMFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN
 LNITIRRSNY TQAANDPPEV TMFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGQPVT EGVAESLFLP RTDYSFHKFH YLTFVPSAED YYDCRVEHWG
 LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG TVLIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC04116
IPD:MHC04116 Mafa-DPA1*02:19 261 bases
 VCPEDRMFQT RAIVLRTLSL AFLLSLRGAG AIKADHVSTY ATFVQTHRPT
 GEFMFEFDED EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN
 LNITIRRSNY TQAANDPPEV TVFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGQPAT EGVAESLFLP RTDYSFHKFH YLTFVPSAED YYDCRVEHWG
 LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIMG TVLIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC04117
IPD:MHC04117 Mafa-DPA1*02:20 261 bases
 VCPEDRMFQT RAIVLRTLSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT
 GEFMFEFDED EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN
 LNITIQRSNY TQAANDPPEV TVFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGQPAT EGVAESLFLP RTDYSFHKFH YLTFVPSAED YYDCRVEHWG
 LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG TVLIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC04118
IPD:MHC04118 Mafa-DPA1*02:21:01 261 bases
 MHPEDRMFQT RAVILRTLSL ALLLSLGGAG AIKADHVSTY ALFVQTHRPT
 GEFMFEFDED EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN
 LNITIQRSNY TQAANDPPEV TVFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGEPVT EGVAESLFLP RTDYSFHKFH YLTFVPSAED YYDCRVEHWG
 LDQPLLKHWE AQEPIQIPET TETVLCALGL VLGLVGIIVG TVLIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC04596
IPD:MHC04596 Mafa-DPA1*02:21:02 176 bases
 ADHVSTYALF VQTHRPTGEF MFEFDEDEQF YVDLDKKETV WHLEEFGRAF
 SFEAQGGLAN IAILNNNLNI TIQRSNYTQA ANDPPEVTVF PKEPVELGQP
 NTLICHIDKF FPPVLNVTWL CNGEPVTEGV AESLFLPRTD YSFHKFHYLT
 FVPSAEDYYD CRVEHWGLDQ PLLKHW*  
>DL;IPD:MHC04121
IPD:MHC04121 Mafa-DPA1*02:22 261 bases
 MCPEDRMFQT RAVILRTLSL AFLLSLRGAG AIKADHVSTY ATFVQTHRPT
 GEFMFEFDED EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN
 LNITIRRSNY TQAANDPPEV TVFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGQPAT EGVAESLFLP RTDYSFHKFH YLTFVPSAED YYDCRVEHWG
 LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG TVLIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC04368
IPD:MHC04368 Mafa-DPA1*02:23 261 bases
 MRPEDRMFQT RAVILRTLSL ALLLSLGGAG AIKADHVSTY ALFVQTHRPT
 GEFMFEFDED EMFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN
 LNITIRRSNY TQAANDPPEV TMFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGQPVT EGVAESLFLP RTDYSFHKFH YLTFVPSAED YYDCRVEHWG
 LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG TVLIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC04598
IPD:MHC04598 Mafa-DPA1*02:24 250 bases
 AVILRTLSLA FLLSLRGAGA IKADHVSTYA AFVQTHRPTG EYMFEFDEDE
 QFYVDLDKKE TVWHLEEFGR AFSFEAQGGL ANIAILNNNL NITIQRSNYT
 QAANDPPEVT VFPKEPVELG QPNTLICHID KFFPPVLNVT WLCNGQPATE
 GVAESLFLPR TDYSFHKFHY LTFVPSAEDY YDCRVEHWGL DQPLLKHWEA
 QEPIQMPETT ETVLCALGLV LGLVGIIVGT VLIIKSLRSG RDPRAQGPLX
>DL;IPD:MHC04600
IPD:MHC04600 Mafa-DPA1*02:25 176 bases
 ADHVSTYAMF VQTHRPTGEY MFEFDEDEMF YVDLDKKETV WHLEEFGRAF
 SFEAQGGLAS IAILNNNLNN TIQRSNYTQA ANDPPEVTVF PKEPVVLGQP
 NTLICHIDKF FPPVLNVTWL CNGQPVTEGV AESLFLPRTD YSFHKFHYLT
 FVPSAEDYYD CRVEHWGLDQ PLLKHW*  
>DL;IPD:MHC04737
IPD:MHC04737 Mafa-DPA1*02:26 261 bases
 MRPEDRMFET RAVILRTLSL ALLLSLGGAG AIKADHVSTY ALFVQTHRPT
 GEFMFEFDED EMFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN
 LNITIRRSNY TQAANDPPEV TMFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGQPVT EGVAESLFLP RTDYSFHKFH YLTFVPSAED YYDCRVEHWG
 LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG TVLIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC01615
IPD:MHC01615 Mafa-DPA1*04:01 261 bases
 MRPEDRMFQT RAVILRTLSL AFLLSLRGAG AIKADHVLTF TTFVQTHRPT
 GEFMYELDED EIFFVDLDKK ETIWHLEEFG RAFSFEAQGG LANIAISNNN
 LNVTIQLSNH TQATNDPPEV TVFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGQPVT EGVTESLFLP RTDYSFHKFH YLTFVPSAED YYDCRVEHWG
 LDQPLLKHWE PQEPIQMPET TETVLCALGL VLGLVGIIVG TVLIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC03719
IPD:MHC03719 Mafa-DPA1*04:02 261 bases
 MRPEDRMFQT RAVILRTLSL AFLLSLRGAG AIKADHVLTF TTFVQTHRPT
 GEYMYELDED EIFFVDLDKK ETIWHLEEFG RAFSFEAQGG LANIAISNNN
 LNVTIQLSNH TQATNDPPEV TVFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGQPVT EGVTESLFLP RTDYSFHKFH YLTFVPSAED YYDCRVEHWG
 LDQPLLKHWE PQEPIQMPET TETVLCALGL VLGLVGIIVG TVLIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC03708
IPD:MHC03708 Mafa-DPA1*06:01:01 255 bases
 MFQTRAIVLR TLSLAFLLSL RGAGAIKADH VSTYAMFVQT HRPTGEFMFE
 FDEDEMFYVD LDKKETVWHL EEFGQAISFE AQGGLANIAI LNHNLNITIQ
 RSNYTQAAND PPEVTVFPKE PVELGQPNTL ICHIDKFFPP VLNVTWLCNG
 EPVTEGVAES LFLPRTDYSF HKFHYLTFVP SAEDYYDCRV EHWGLDQPLL
 KHWEAQEPIQ IPETTETVLC ALGLVLGLVG IIVGTVLIIK SLRSGRDPRA
 QGPLX*    
>DL;IPD:MHC04608
IPD:MHC04608 Mafa-DPA1*06:01:02 176 bases
 ADHVSTYAMF VQTHRPTGEF MFEFDEDEMF YVDLDKKETV WHLEEFGQAI
 SFEAQGGLAN IAILNHNLNI TIQRSNYTQA ANDPPEVTVF PKEPVELGQP
 NTLICHIDKF FPPVLNVTWL CNGEPVTEGV AESLFLPRTD YSFHKFHYLT
 FVPSAEDYYD CRVEHWGLDQ PLLKHW*  
>DL;IPD:MHC04603
IPD:MHC04603 Mafa-DPA1*06:02 176 bases
 ADHVSTYAMF VQTHRPTGEF MFEFDEDEMF YVDLDKKETV WHLEEFGRAF
 SFEAQGGLAN IAILNNNLNI TIQRSNYTQA ANDPPEVTVF PKEPVELGQP
 NTLICHIDKF FPPVLNVTWL CNGEPVTEGV AESLFLPRTD YSFHKFHYLT
 FVPSAEDYYD CRVEHWGLDQ PLLKHW*  
>DL;IPD:MHC04604
IPD:MHC04604 Mafa-DPA1*06:03 176 bases
 ADHVSTYAMF VQTHRPTGEF MFEFDEDEMF YVDLDKKETV WHLEEFGRAF
 SFEAQGGLAN IAILNDNLNI TIQRSNYTQA ANDPPEVTVF PKEPVELGQP
 NTLICHIDKF FPPVLNVTWL CNGEPVTEGV AESLFLPRTD YSFHKFHYLT
 FVPSAEDYYD CRVEHWGLDQ PLLKHW*  
>DL;IPD:MHC01612
IPD:MHC01612 Mafa-DPA1*07:01 261 bases
 MCPEDRMFQT RAVILRTLSL AFLLSLRGAG AIKADHVSTY ALFVQTHRPT
 GEFMFEFDED EMFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAALNNN
 LNTLIQLSNH TPAANDPPEV TVFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGEPVT EGVAESLFLP RTDYRLHKFH YLTFVPSAED FYDCRVEHWG
 LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG SILILKAMRS
 GRDPRAQGPL X*   
>DL;IPD:MHC01613
IPD:MHC01613 Mafa-DPA1*07:02 255 bases
 MFQTRAVILR ALSLAFLLSL RGAGAIKADH VSTYASFVQT HRPTGEYMFE
 FDEDEMFYVD LDKKETVWHL EEFGRAFSFE AQGGLANIAA LNNNLNTLIQ
 LSNHTPAAND PPEVTVFPKE PVELGQPNTL ICHIDKFFPP VLNVTWLCNG
 EPVTEGVAES LFLPRTDYRL HKFHYLTFVP SAEDFYDCRV EHWGLDQPLL
 KHWEAQEPIQ MPETRETVLC ALGLVLGLVG IIVGTVLIIK SLQSGRDPRA
 QGPLX*    
>DL;IPD:MHC03709
IPD:MHC03709 Mafa-DPA1*07:03 255 bases
 MFQTRAVILR ALSLAFLLSL RGAGAIKADH VSTYASFVQT HRPTGEYMFE
 FDEDEMFYVD LDKKETVWHL EEFGRAFSFE AQGGLANIAA LNHNLNTLIQ
 RSNHTQAAND PPEVTVFPKE PVELGQPNTL ICHIDKFFPP VLNVTWLCNG
 EPVTEGVAES LFLPRTDYRL HKFHYLTFVP SAEDFYDCRV EHWGLDQPLL
 KHWEAQEPIQ MPETRETVLC ALGLVLGLVG IIVGTVLIIK SLRSGRDPRA
 QGPLX*    
>DL;IPD:MHC03714
IPD:MHC03714 Mafa-DPA1*07:04 261 bases
 MCPEDRMFQT RAVILRTLSL AFLLSLRGAG AIKADHVSTY AMFVQTHRPT
 GEFMFEFDED EMFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAALNHN
 LNTLIQLSNH TPAANDPPEV TVFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGEPVT EGVAESLFLP RTDYRLHKFH YLTFVPSAED FYDCRVEHWG
 LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG SILILKAMRS
 GRDPRAQGPL X*   
>DL;IPD:MHC04601
IPD:MHC04601 Mafa-DPA1*07:05 176 bases
 ADHVSTYASF VQTHRPTGEF MFEFDEDEQF YVDLDKKETV WHLEEFGRAF
 SFEAQGGLAN IAALNHNLNI LIQRSNHTKA ANDPPEVTVF PKEPVELGQP
 NTLICHIDKF FPPVLNVTWL CNGEPVTEGV AESLFLPRTD YRLHKFHYLT
 FVPSAEDFYD CRVEHWGLDQ PLLKHW*  
>DL;IPD:MHC04605
IPD:MHC04605 Mafa-DPA1*07:06 176 bases
 ADHVSTYASF VQTHRPTGEF MFEFDEDEMF YVDLDKKETV WHLEEFGRAF
 SFEAQGGLAN IAALNHNLNN LIQRSNHTQA ANDPPEVTVF PKEPVELGQP
 NTLICHIDKF FPPVLNVTWL CNGEPVTEGV AESLFLPRTD YRLHKFHYLT
 FVPSAEDFYD CRVEHWGLDQ PLLKHW*  
>DL;IPD:MHC04606
IPD:MHC04606 Mafa-DPA1*07:07 261 bases
 VCPEDRMFQT RAVILRALSW AFLLSLRGAG AIKADHVSTY ASFVQTHRPT
 GEFMFEFDED EMFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAALNHN
 LNTLIQRSNH TQAANDPPEV TVFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGEPVT EGVAESLFLP RTDYRLHKFH YLTFVPSAED FYDCRVEHWG
 LDQPLLKHWE AQEPIQMPET RETVLCALGL VLGLVGIIVG TVLIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC04607
IPD:MHC04607 Mafa-DPA1*07:08 176 bases
 ADHVSTYASF VQTHRPTGEF MFEFDEDEQF YVDLDKKETV WHLEEFGRAF
 SFEAQGGLAN IAALNHNLNI LIQRSNHTQA ANDPPEVTVF PKEPVELGQP
 NTLICHIDKF FPPVLNVTWL CNGEPVTEGV AESLFLPRTD YRLHKFHYLT
 FVPSAEDFYD CRVEHWGLDQ PLLKHW*  
>DL;IPD:MHC04610
IPD:MHC04610 Mafa-DPA1*07:09 176 bases
 ADHVSTYASF VQTHRPTGEF MFEFDEDEMF YVDLDKKETV WHLEEFGRAL
 FLEAQGGLAN IAALNHNLNT LIQRSNHTQA ANDPPEVTVF PKEPVELGQP
 NTLICHIDKF FPPVLNVTWL CNGEPVTEGV AESLFLPRTD YRLHKFHYLT
 FVPSAEDFYD CRVEHWGLDQ PLLKHW*  
>DL;IPD:MHC04612
IPD:MHC04612 Mafa-DPA1*07:10 176 bases
 ADHVSTYALF VQTHRPTGEY MSEFDEDEMF YVDLDKKETV WHLEEFGRAL
 FLEAQGGLAN IAALNNNLNI MIQRSNHTQA ANDPPEVTVF PKEPVELGQP
 NTLICHIDKF FPPVLNVTWL CNGEPVTEGV AESLFLPRTD YRLHKFHYLT
 FVPSAEDYYD CRVEHWGLDQ PLLKHW*  
>DL;IPD:MHC04613
IPD:MHC04613 Mafa-DPA1*07:11 176 bases
 ADHVSTYASF VQTHRPTGEY MFEFDEDEQF YVDLDKKETV WHLEEFGRAF
 SFEAQGGLAN IAALNHNLNI LIQRSNHTKA ANDPPEVTVF PKEPVELGQP
 NTLICHIDKF FPPVLNVTWL CNGEPVTEGV AESLFLPRTD YRLHKFHYLT
 FVPSAEDFYD CRVEHWGLDQ PLLKHW*  
>DL;IPD:MHC04614
IPD:MHC04614 Mafa-DPA1*07:12 176 bases
 ADHVSTYAMF VQTHRPTGEF MFEFDEDEMF YVDLDKKETV WHLEEFGRAF
 SFEAQGGLAN IAALNNNLNT LIQLSNHTPA ANDPPEVTVF PKEPVELGQP
 NTLICHIDKF FPPVLNVTWL CNGEPVTEGV AESLFLPRTD YRLHKFHYLT
 FVPSAEDFYD CRVEHWGLDQ PLLKHW*  
>DL;IPD:MHC05214
IPD:MHC05214 Mafa-DPA1*07:13 256 bases
 RMFQTRAVIL RTLSLAFLLS LRGAGAIKAD HVSTYAMFVQ THRPTGEFMF
 EFDEDEMFYV DLDKKETVWH LEEFGRAFSF EAQGGLANIA ALNHNLNTLI
 QLSNHTPAAS DPPEVTVFPK EPVELGQPNT LICHIDKFFP PVLNVTWLCN
 GEPVTEGVAE SLFLPRTDYR LHKFHYLTFV PSAEDFYDCR VEHWGLDQPL
 LKHWEAQEPI QMPETTETVL CALGLVLGLV GIIVGSILIL KAMRSGRDPR
 AQGPLX*    
>DL;IPD:MHC03713
IPD:MHC03713 Mafa-DPA1*08:01 261 bases
 MRPEDRMFET RAVILRTLSL ALLLSLGGAG AIKADHVSTY ALFVQTHRPT
 GEYMFEFDED EMFYVDLDKK ETVWHLEEFG RAFSFEAQGG LDDIATLKYN
 LNITIQRSNH TQAANDPPEV MVFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGEPVT EGVAESLFLP RTDYSFHKFH YLTFVPSAED FYDCRVEHWG
 LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG TILIIKSLRS
 GRDPRAQGPL X*   
>DL;IPD:MHC03705
IPD:MHC03705 Mafa-DPA1*09:01 261 bases
 MCPEGRMFQT RAVILRALSL AFLLSLRGAG AIKADHVSTY VMFVQTHRPT
 GEFMFEFDED EMFYVDLDKK ETVWHLEEFG RAFFFEAQRV LSHIVILNDS
 LNIMIQRSNH TPAANDPPEV TVFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGQPVT EGVAESIFLP RTGYNFHKFH YLTFVPSAED VYDCRVEHWG
 LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG SILILKAMRS
 GRDPRAQGPL X*   
>DL;IPD:MHC05204
IPD:MHC05204 Mafa-DPA1*09:02 250 bases
 AVILRALSLA FLLSLRGAGA IKADHVSTYV MFVQTHRPTG EFMFEFDEDE
 MFYVDLDKKE TVWHLEEFGR AFFFEAQRVL SHIVILNDSL NIMIQRSNHT
 PAANDPPEVA VFPKEPVELG QPNTLICHID KFFPPVLNVT WLCNGQPVTE
 GVAESIFLPR TGYNFHKFHY LTFVPSAEDV YDCRVEHWGL DQPLLKHWEA
 QEPIQMPETT ETVLCALGLV LGLVGIIVGS ILILKAMRSG RDPRAQGPLX
>DL;IPD:MHC04115
IPD:MHC04115 Mafa-DPA1*10:01 261 bases
 MRPEDRMFQT RAVILRTLSL AFLLSLRGAG AIKADHVSTF AMFVQTHRPT
 GEYMSEFDED EMLYVDLDKK ETVWHLEEFG RALFLDAQGG LANIAALNNH
 LNIMIQRSNH SQAANDPPEV TVFPKEPVEL GQPNTLICHI DKFFPPVLNV
 TWLCNGELVT KGVTESLFLP RTDYRLHKFH YLTFVPSAED YYDCRVEHWG
 LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG SILILKAMRS
 GRDSRAQGPL X*   
>DL;IPD:MHC04599
IPD:MHC04599 Mafa-DPA1*10:02 176 bases
 ADHVSTFAMF VQTHRPTGEY MSEFDEDEML YVDLDKKETV WHLEEFGRAL
 FLDAQGVLAN IAALNNHLNI MIQRSNHSQA ANDPPEVTVF PKEPVELGQP
 NTLICHIDKF FPPVLNVTWL CNGKLVTKGV TESLFLPRTD YRLHKFHYLT
 FVPSAEDYYD CRVEHWGLDQ PLLKHW*  
>DL;IPD:MHC04609
IPD:MHC04609 Mafa-DPA1*10:03 176 bases
 ADHVSTFAMF VQTHRPTGEY MSEFDEDEML YVDLDKKETV WHLEEFGRAL
 FLDAQGGLAN IAALNNHLNI MIQRSNHSQA ANDPPEVTVF PKEPVELGQP
 NTLICHIDKF FPPVLNVTWL CNGKLVTKGV TESLFLPRTD YRLHKFHYLT
 FVPSAEDYYD CRVEHWGLDQ PLLKHW*  
>DL;IPD:MHC04611
IPD:MHC04611 Mafa-DPA1*10:04 176 bases
 ADHVSTFAMF VQTHRPTGEY MSEFDEDEMF YVDLDKKETV WHLEEFGRAL
 FLDAQGGLAN IAALNNHLNI MIQRSNHSQA ANDPPEVTVF PKEPVELGQP
 NTLICHIDKF FPPVLNVTWL CNGELVTKGV TESLFLPRTD YRLHKFHYLT
 FVPSAEDYYD CRVEHWGLDQ PLLKHW*  
