>DL;IPD:MHC00272
IPD:MHC00272 Mafa-DPA1*02:01 783 bases
 ATGCGCCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTGA TCTTGAGAAC
 CCTCTCCTTG GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG
 CAGACCATGT ATCAACTTAT GCCGCGTTTG TACAGACACA TAGACCAACA
 GGGGAGTATA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CGATCCAGCG TTCCAACTAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAATGTC
 ACGTGGCTGT GCAACGGGCA GCCGGCCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGACT ACAGCTTCCA CAAGTTCCAT TACTTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGATT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA AGGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACTGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGATC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC01614
IPD:MHC01614 Mafa-DPA1*02:02 783 bases
 ATGTGCCCTG AAGACAGAAT GTTCCAGACC AGATCTGTGA TCTTGAGAAC
 CCTCTCCTTG GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT GTCCACTTAT GCCTTGTTTG TACAGACACA TAGACCAACA
 GGGGAGTATA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGATGACA TTGCTACATT GAAGTACAAC
 TTGAATATCA CGATCCAGCG TTCCAACCAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGACAGCCCA
 ACACCCTCAT CTGCCACATT GACAAATTCT TCCCTCCGGT GCTCAACGTC
 ACGTGGCTGT GCAATGGGGA GCCGGTCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGACT ACAGCTTCCA CAAGTTCCAT TACTTGACCT
 TTGTGCCCTC GGCCGAGGAC TTCTATGACT GCAGGGTGGA GCATTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACCGTCCTCA TCATAAAGTC TCTGCGTTCT
 GGCCGTGACC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC01616
IPD:MHC01616 Mafa-DPA1*02:03 783 bases
 ATGCACCCTG AAGACAGAAT GTTCGAGACC AGAGCTGTTA TCTTGAGAAC
 CCTCTCCTTG GCTTTGCTGC TGAGTCTCGG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT GTCCACTTAT GCCTTGTTTG TACAGACACA TAGACCAACA
 GGGGAGTATA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGATGACA TTGCTACATT GAAGTACAAC
 TTGAATATCA CGATCCAGCG TTCCAACCAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGACAGCCCA
 ACACCCTCAT CTGCCACATT GACAAATTCT TCCCTCCGGT GCTCAACGTC
 ACGTGGCTGT GCAATGGGGA GCCGGTCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGACT ACAGCTTCCA CAAGTTCCAT TACTTGACCT
 TTGTGCCCTC GGCCGAGGAC TTCTATGACT GCAGGGTGGA GCATTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACCGTCCTCA TCATAAAGTC TCTGCATTCT
 GGCCGTGACC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC02058
IPD:MHC02058 Mafa-DPA1*02:04 783 bases
 ATGCGCCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTGA TCTTGAGAAC
 CCTCTCCTTG GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT ATCAACTTAT GCCATGTTTG TACAGACACA TAGACCAACA
 GGGGAGTATA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CGATCCGGCG TTCCAACTAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCATGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAACGCC
 ACGTGGCTGT GCAACGGGCA GCCCGTCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGATT ATAGCTTCCA CAAGTTCCAT TACCTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACTGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGATC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC02059
IPD:MHC02059 Mafa-DPA1*02:05 783 bases
 ATGCGCCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTGA TCTTGAGAAC
 CCTCTCCTTG GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT ATCAACTTAT GCCATGTTTG TACAGACACA TAGACCAACA
 GGGGAGTATA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CGATCCGGCG TTCCAACTAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCATGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAACGTC
 ACGTGGCTGT GCAACGGGCA GCCCGTCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGATT ATAGCTTCCA CAAGTTCCAT TACCTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACTGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGATC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC03706
IPD:MHC03706 Mafa-DPA1*02:06:01 783 bases
 ATGCACCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTTA TCTTGAGAAC
 CCTCTCCTTG GCTTTGCTGC TGAGTCTCGG AGGAGCTGGG GCCATCAAGG
 CAGACCATGT ATCAACTTAT GCCACGTTTG TACAGACACA TAGACCAACA
 GGGGAGTTTA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CGATCCGGCG TTCCAACTAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAACGTC
 ACGTGGCTGT GCAACGGGCA GCCGGCCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGACT ACAGCTTCCA CAAGTTCCAT TACTTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGATT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA AGGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACTGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGATC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC04120
IPD:MHC04120 Mafa-DPA1*02:06:02 783 bases
 ATGCACCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTTA TCTTGAGAAC
 CCTCTCCTTG GCTTTGCTGC TGAGTCTCGG AGGAGCTGGG GCCATCAAGG
 CAGACCATGT ATCAACTTAT GCCACGTTTG TACAGACACA TAGACCAACA
 GGGGAGTTTA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CGATCCGGCG TTCCAACTAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAACGTC
 ACGTGGCTGT GCAATGGGCA GCCGGCCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGACT ACAGCTTCCA CAAGTTCCAT TACTTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGATT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA AGGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACTGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGATC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC03707
IPD:MHC03707 Mafa-DPA1*02:07 765 bases
 ATGTTCCAGA CCAGAGCTAT TGTCTTGAGA ACCCTCTCCT TGGCTTTCCT
 GCTGAGTCTC CGAGGAGCTG GGGCCATCAA GGCAGACCAT GTATCAACTT
 ATGCTGCGTT TGTACAGACA CATAGACCAA CAGGGGAGTA TATGTTTGAG
 TTTGATGAAG ATGAGCAGTT CTATGTGGAT CTGGACAAGA AGGAGACCGT
 CTGGCATCTG GAGGAGTTTG GCCGAGCCTT TTCCTTTGAG GCTCAGGGCG
 GGCTGGCTAA CATTGCTATA TTGAACAACA ACTTGAATAT CACGATCCAG
 CGTTCCAACT ACACTCAGGC CGCCAATGAT CCCCCTGAGG TGACCGTGTT
 TCCCAAGGAG CCTGTGGAGC TGGGCCAACC CAACACCCTC ATCTGCCACA
 TTGACAAGTT CTTCCCTCCA GTGCTCAACG TCACGTGGCT GTGCAACGGG
 CAGCCGGCCA CTGAGGGTGT CGCTGAGAGC CTCTTCCTGC CCAGAACAGA
 CTACAGCTTC CACAAGTTCC ATTACTTGAC CTTTGTGCCC TCAGCCGAGG
 ACTACTATGA TTGCAGGGTG GAGCACTGGG GCTTGGACCA GCCGCTCCTC
 AAACACTGGG AGGCCCAAGA GCCAATCCAG ATGCCTGAGA CAACGGAGAC
 TGTGCTCTGT GCCCTGGGCC TGGTGCTGGG CCTAGTGGGC ATCATCGTGG
 GCACTGTCCT CATCATAAAG TCTCTGCGAT CTGGCCGTGA TCCCCGGGCC
 CAGGGGCCCC TGTGA*   
>DL;IPD:MHC03710
IPD:MHC03710 Mafa-DPA1*02:08:01 783 bases
 ATGCACCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTTA TCTTGAGAAC
 CCTCTCCTTG GCTTTGCTGC TGAGTCTCGG AGGAGCTGGG GCCATCAAGG
 CAGACCATGT ATCAACTTAT GCCACGTTTG TACAGACACA TAGACCAACA
 GGGGAGTTTA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CGATCCGGCG TTCCAACTAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAACGTC
 ACGTGGCTGT GCAACGGGCA GCCGGCCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGACT ACAGCTTCCA CAAGTTCCAT TACTTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGATT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACCGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGACC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC03720
IPD:MHC03720 Mafa-DPA1*02:08:02 783 bases
 ATGCACCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTTA TCTTGAGAAC
 CCTCTCCTTG GCTTTGCTGC TGAGTCTCGG AGGAGCTGGG GCCATCAAGG
 CAGACCATGT ATCAACTTAT GCCACGTTTG TACAGACACA TAGACCAACA
 GGGGAGTTTA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CGATCCGGCG TTCCAACTAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAACGTC
 ACGTGGCTGT GCAACGGGCA GCCGGCCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGATT ATAGCTTCCA CAAGTTCCAT TACTTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGATT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACCGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGACC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC03711
IPD:MHC03711 Mafa-DPA1*02:09:01 783 bases
 ATGCGCCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTGA TCTTGAGAAC
 CCTCTCCTTG GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT ATCAACTTAT GCCTTGTTTG TACAGACACA TAGACCAACA
 GGGGAGTTTA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CGATCCAGCG TTCCAACTAC ACTCAGGCTG CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAACGTC
 ACGTGGCTGT GCAATGGGGA GCCAGTCACT GAGGGTGTCG CTGAGAGCCT
 TTTCCTGCCC AGAACAGATT ATAGCTTCCA CAAGTTCCAT TACCTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGACT GCAGGGTGGA GCATTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 CCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACCGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGACC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC05213
IPD:MHC05213 Mafa-DPA1*02:09:02 783 bases
 ATGCGCCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTGA TCTTGAGAAC
 CCTCTCCTTG GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT ATCAACTTAT GCCTTGTTTG TACAGACACA TAGACCAACA
 GGGGAGTTTA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CGATCCAGCG TTCCAACTAC ACTCAGGCTG CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAACGTC
 ACGTGGCTGT GCAATGGGGA GCCAGTCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGATT ATAGCTTCCA CAAGTTCCAT TACCTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGACT GCAGGGTGGA GCATTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 CCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACCGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGACC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC03712
IPD:MHC03712 Mafa-DPA1*02:10 783 bases
 ATGCGTCCTG AAGACAGAAT GTTCGAGACC AGAGCTGTTA TCTTGAGAAC
 CCTCTCCTTG GCTTTGCTGC TGAGTCTCGG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT ATCAACTTAT GCCTTGTTTG TACAGACACA TAGACCAACA
 GGGGAGTTTA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACCACAAC
 TTGAATATCA CGATCCAGCG TTCCAACTAC ACTCAGGCTG CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAACGTC
 ACGTGGCTGT GCAATGGGGA GCCAGTCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGATT ATAGCTTCCA CAAGTTCCAT TACCTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGACT GCAGGGTGGA GCATTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 CCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACCGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGACC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC03715
IPD:MHC03715 Mafa-DPA1*02:11 783 bases
 ATGTGCCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTGA TCTTGAGAAC
 CCTCTCCTTG GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG
 CAGACCATGT ATCAACTTAT GCCACGTTTG TACAGACACA TAGACCAACA
 GGGGAGTTTA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CGATCCGGCG TTCCAACTAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAACGTC
 ACGTGGCTGT GCAACGGGCA GCCGGCCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGACT ACAGCTTCCA CAAGTTCCAT TACTTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGATT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACTGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGATC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC03716
IPD:MHC03716 Mafa-DPA1*02:12 783 bases
 ATGCGCCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTTA TCTTGAGAAC
 CCTCTCCTTG GCTTTCCTGC TGAGTCTCGG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT ATCAACTTAT GCCATGTTTG TACAGACACA TAGACCAACA
 GGGGAGTTTA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTCGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CGATCCAGCG TTCCAACTAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGACAGCCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCGGT ACTCAACGTC
 ACGTGGCTGT GCAATGGGGA GCCGGTCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGATT ATAGCTTCCA CAAGTTCCAT TACCTGACCT
 TTGTGCCGTC AGCCGAGGAC TACTATGACT GCAGGGTGGA GCATTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACTGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGACC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC03717
IPD:MHC03717 Mafa-DPA1*02:13:01 783 bases
 ATGTGCCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTGA TCTTGAGAAC
 CCTCTCCTTG GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT ATCAACTTAT GCCATGTTTG TACAGACACA TAGACCAACA
 GGGGAGTATA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CGATCCGGCG TTCCAACTAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCATGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAACGTC
 ACGTGGCTGT GCAACGGGCA GCCCGTCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGATT ATAGCTTCCA CAAGTTCCAT TACCTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCATGGGC ACTGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGACC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC04119
IPD:MHC04119 Mafa-DPA1*02:13:02 783 bases
 ATGTGCCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTGA TCTTGAGAAC
 CCTCTCCTTG GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT ATCAACTTAT GCCATGTTTG TACAGACACA TAGACCAACA
 GGGGAGTATA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CGATCCGGCG TTCCAACTAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCATGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAACGTC
 ACGTGGCTGT GCAACGGGCA GCCCGTCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGATT ATAGCTTCCA CAAGTTCCAT TACCTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCATGGGC ACTGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGATC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC03718
IPD:MHC03718 Mafa-DPA1*02:14 783 bases
 ATGCGCCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTTA TCTTGAGAAC
 CCTCTCCTTG GCTTTGCTGC TGAGTCTCGG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT ATCAACTTAT GCCTTGTTTG TACAGACACA TAGACCAACA
 GGGGAGTTTA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACCACAAC
 TTGAATATCA CGATCCAGCG TTCCAACTAC ACTCAGGCTG CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAACGTC
 ACGTGGCTGT GCAATGGGGA ACCAGTCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGATT ATAGCTTCCA CAAGTTCCAT TACCTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGACT GCAGGGTGGA GCATTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 CCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACCGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGACC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC03721
IPD:MHC03721 Mafa-DPA1*02:15:01 765 bases
 ATGTTCCAGA CCAGAGCTAT TGTCTTGAGA ACCCTCTCCT TGGCTTTCCT
 GCTGAGTCTC CGAGGAGCTG GGGCCATCAA GGCAGACCAT GTATCAACTT
 ATGCCACGTT TGTACAGACA CATAGACCAA CAGGGGAGTT TATGTTTGAG
 TTTGATGAAG ATGAGCAGTT CTATGTGGAT CTGGACAAGA AGGAGACCGT
 CTGGCATCTG GAGGAGTTTG GCCGAGCCTT TTCCTTTGAG GCTCAGGGCG
 GGCTGGCTAA CATTGCTATA TTGAACAACA ACTTGAATAT CACGATCCGG
 CGTTCCAACT ACACTCAGGC CGCCAATGAT CCCCCTGAGG TGACCGTGTT
 TCCCAAGGAG CCTGTGGAGC TGGGCCAACC CAACACCCTC ATCTGCCACA
 TTGACAAGTT CTTCCCTCCA GTGCTCAACG TCACGTGGCT GTGCAACGGG
 CAGCCGGCCA CTGAGGGTGT CGCTGAGAGC CTCTTCCTGC CCAGAACAGA
 CTACAGCTTC CACAAGTTCC ATTACTTGAC CTTTGTGCCC TCAGCCGAGG
 ACTACTATGA TTGCAGGGTG GAGCACTGGG GCTTGGACCA GCCGCTCCTC
 AAACACTGGG AGGCCCAAGA GCCAATCCAG ATGCCTGAGA CAACGGAGAC
 TGTGCTCTGT GCCCTGGGCC TGGTGCTGGG CCTAGTGGGC ATCATCGTGG
 GCACTGTCCT CATCATAAAG TCTCTGCGAT CTGGCCGTGA TCCCCGGGCC
 CAGGGGCCCC TGTGA*   
>DL;IPD:MHC04736
IPD:MHC04736 Mafa-DPA1*02:15:02 765 bases
 ATGTTCCAGA CCAGAGCTAT TGTCTTGAGA ACCCTCTCCT TGGCTTTCCT
 GCTGAGTCTC CGAGGAGCTG GGGCCATCAA GGCAGACCAT GTATCAACTT
 ATGCCACGTT TGTACAGACA CATAGACCAA CAGGGGAGTT TATGTTTGAG
 TTTGATGAAG ATGAGCAGTT CTATGTGGAT CTGGACAAGA AGGAGACCGT
 CTGGCATCTG GAGGAGTTTG GCCGAGCCTT TTCCTTTGAG GCTCAGGGCG
 GGCTGGCTAA CATTGCTATA TTGAACAACA ACTTGAATAT CACGATCCGG
 CGTTCCAACT ACACTCAGGC CGCCAATGAT CCCCCTGAGG TGACCGTGTT
 TCCCAAGGAG CCTGTGGAGC TGGGCCAACC CAACACCCTC ATCTGCCACA
 TTGACAAGTT CTTCCCTCCA GTGCTCAACG TCACGTGGCT GTGCAACGGG
 CAGCCGGCCA CTGAGGGTGT CGCTGAGAGC CTCTTCCTGC CCAGAACAGA
 CTACAGCTTC CACAAGTTCC ATTACTTGAC CTTTGTGCCC TCAGCCGAGG
 ACTACTATGA TTGCAGGGTG GAGCACTGGG GCTTGGACCA GCCGCTCCTC
 AAACACTGGG AGGCCCAAGA GCCAATCCAG ATGCCTGAGA CAACGGAGAC
 TGTGCTCTGT GCCCTGGGCC TGGTGCTGGG CCTAGTGGGC ATCATCGTGG
 GCACTGTCCT CATCATAAAG TCTCTGCGAT CTGGCCGTGA CCCCCGGGCC
 CAGGGGCCCC TGTGA*   
>DL;IPD:MHC03722
IPD:MHC03722 Mafa-DPA1*02:16 783 bases
 ATGCACCCTG AAGACAGAAT GTTCGAGACC AGAGCTGTTA TCTTGAGAAC
 CCTCTCCTTG GCTTTGCTGC TGAGTCTCGG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT ATCAACTTAT GCCTTGTTTG TACAGACACA TAGACCAACA
 GGGGAGTTTA TGTTTGAGTT TGATGAAGAT GAGATGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CGATCCGGCG TTCCAACTAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAACGTC
 ACGTGGCTGT GCAACGGGCA GCCGGCCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGACT ACAGCTTCCA CAAGTTCCAT TACTTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGATT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACTGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGATC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC03723
IPD:MHC03723 Mafa-DPA1*02:17 783 bases
 ATGCGTCCTG AAGACAGAAT GTTCGAGACC AGAGCTGTTA TCTTGAGAAC
 CCTCTCCTTG GCTTTGCTGC TGAGTCTCGG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT ATCAACTTAT GCCATGTTTG TACAGACACA TAGACCAACA
 GGGGAGTATA TGTTTGAGTT TGATGAAGAT GAGATGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CCATCCGGCG TTCCAACTAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCATGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAACGTC
 ACGTGGCTGT GCAACGGGCA GCCCGTCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGATT ATAGCTTCCA CAAGTTCCAT TACCTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACTGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGATC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC03724
IPD:MHC03724 Mafa-DPA1*02:18 783 bases
 ATGCACCCTG AAGACAGAAT GTTCGAGACC AGAGCTGTTA TCTTGAGAAC
 CCTCTCCTTG GCTTTGCTGC TGAGTCTCGG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT ATCAACTTAT GCCATGTTTG TACAGACACA TAGACCAACA
 GGGGAGTATA TGTTTGAGTT TGATGAAGAT GAGATGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CGATCCGGCG TTCCAACTAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCATGTTTC CCAAGGAGCC TGTGGAGCTG GGACAGCCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAACGTC
 ACGTGGCTGT GCAACGGGCA GCCCGTCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGACT ACAGCTTCCA CAAGTTCCAT TACCTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACCGTCCTCA TCATAAAGTC TCTGCGTTCT
 GGCCGTGACC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC04116
IPD:MHC04116 Mafa-DPA1*02:19 783 bases
 GTGTGCCCTG AAGACAGAAT GTTCCAGACC AGAGCTATTG TCTTGAGAAC
 CCTCTCCTTG GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG
 CAGACCATGT ATCAACTTAT GCCACGTTTG TACAGACACA TAGACCAACA
 GGGGAGTTTA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CGATCCGGCG TTCCAACTAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAACGTC
 ACGTGGCTGT GCAACGGGCA GCCGGCCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGACT ACAGCTTCCA CAAGTTCCAT TACTTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGATT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCATGGGC ACTGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGATC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC04117
IPD:MHC04117 Mafa-DPA1*02:20 783 bases
 GTGTGCCCTG AAGACAGAAT GTTCCAGACC AGAGCTATTG TCTTGAGAAC
 CCTCTCCTTG GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG
 CAGACCATGT ATCAACTTAT GCCGCGTTTG TACAGACACA TAGACCAACA
 GGGGAGTTTA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CGATCCAGCG TTCCAACTAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAACGTC
 ACGTGGCTGT GCAACGGGCA GCCGGCCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGACT ACAGCTTCCA CAAGTTCCAT TACTTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGATT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGA ACTGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGATC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC04118
IPD:MHC04118 Mafa-DPA1*02:21:01 783 bases
 ATGCACCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTTA TCTTGAGAAC
 CCTCTCCTTG GCTTTGCTGC TGAGTCTCGG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT ATCAACTTAT GCCTTGTTTG TACAGACACA TAGACCAACA
 GGGGAGTTTA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CGATCCAGCG TTCCAACTAC ACTCAGGCTG CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAACGTC
 ACGTGGCTGT GCAATGGGGA GCCAGTCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGATT ATAGCTTCCA CAAGTTCCAT TACCTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGACT GCAGGGTGGA GCATTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 CCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACCGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGACC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC04596
IPD:MHC04596 Mafa-DPA1*02:21:02 529 bases
 GCGGACCATG TATCAACTTA TGCCTTGTTT GTACAGACAC ATAGACCAAC
 AGGGGAGTTT ATGTTTGAGT TTGATGAAGA TGAGCAGTTC TATGTGGATC
 TGGACAAGAA GGAGACCGTC TGGCATCTGG AGGAGTTTGG CCGAGCCTTT
 TCCTTTGAGG CTCAGGGCGG GCTGGCTAAC ATTGCTATAT TGAACAACAA
 CTTGAATATC ACGATCCAGC GTTCCAACTA CACTCAGGCC GCCAATGATC
 CCCCTGAGGT GACCGTGTTT CCCAAGGAGC CTGTGGAGCT GGGCCAACCC
 AACACCCTCA TCTGCCACAT TGACAAGTTC TTCCCTCCAG TGCTCAACGT
 CACGTGGCTG TGCAATGGGG AGCCGGTCAC TGAGGGTGTC GCTGAGAGCC
 TCTTCCTGCC CAGAACAGAT TATAGCTTCC ACAAGTTCCA TTACTTGACC
 TTTGTGCCCT CAGCCGAGGA CTACTATGAT TGCAGGGTGG AGCACTGGGG
 CTTGGACCAG CCGCTCCTCA AACACTGGG*  
>DL;IPD:MHC04121
IPD:MHC04121 Mafa-DPA1*02:22 783 bases
 ATGTGCCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTGA TCTTGAGAAC
 CCTCTCCTTG GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG
 CAGACCATGT ATCAACTTAT GCCACGTTTG TACAGACACA TAGACCAACA
 GGGGAGTTTA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CGATCCGGCG TTCCAACTAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAACGTC
 ACGTGGCTGT GCAACGGGCA GCCGGCCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGATT ATAGCTTCCA CAAGTTCCAT TACTTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGATT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACCGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGACC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC04368
IPD:MHC04368 Mafa-DPA1*02:23 783 bases
 ATGCGCCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTTA TCTTGAGAAC
 CCTCTCCTTG GCTTTGCTGC TGAGTCTCGG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT ATCAACTTAT GCCTTGTTTG TACAGACACA TAGACCAACA
 GGGGAGTTTA TGTTTGAGTT TGATGAAGAT GAGATGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CGATCCGGCG TTCCAACTAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCATGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAACGTC
 ACGTGGCTGT GCAACGGGCA GCCCGTCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGATT ATAGCTTCCA CAAGTTCCAT TACCTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACTGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGATC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC04598
IPD:MHC04598 Mafa-DPA1*02:24 751 bases
 AGCTGTGATC TTGAGAACCC TCTCCTTGGC TTTCCTGCTG AGTCTCCGAG
 GAGCTGGGGC CATCAAGGCA GACCATGTAT CAACTTATGC CGCGTTTGTA
 CAGACACATA GACCAACAGG GGAGTATATG TTTGAGTTTG ATGAAGATGA
 GCAGTTCTAT GTGGATCTGG ACAAGAAGGA GACCGTCTGG CATCTGGAGG
 AGTTTGGCCG AGCCTTTTCC TTTGAGGCTC AGGGCGGGCT GGCTAACATT
 GCTATATTGA ACAACAACTT GAATATCACG ATCCAGCGTT CCAACTACAC
 TCAGGCCGCC AATGATCCCC CTGAGGTGAC CGTGTTTCCC AAGGAGCCTG
 TGGAGCTGGG CCAACCCAAC ACCCTCATCT GCCACATTGA CAAGTTCTTC
 CCTCCAGTGC TCAATGTCAC GTGGCTGTGC AACGGGCAGC CGGCCACTGA
 GGGTGTCGCT GAGAGCCTCT TCCTGCCCAG AACAGACTAC AGCTTCCACA
 AGTTCCATTA CTTGACCTTT GTGCCCTCAG CCGAGGACTA CTATGATTGC
 AGGGTGGAGC ACTGGGGCTT GGACCAGCCG CTCCTCAAAC ACTGGGAGGC
 CCAAGAGCCA ATCCAGATGC CTGAGACAAC GGAGACTGTG CTCTGTGCCC
 TGGGCCTGGT GCTGGGCCTA GTGGGCATCA TCGTGGGCAC TGTCCTCATC
 ATAAAGTCTC TGCGATCTGG CCGTGATCCC CGGGCCCAGG GGCCCCTGTG
 A*    
>DL;IPD:MHC04600
IPD:MHC04600 Mafa-DPA1*02:25 528 bases
 GCGGACCATG TATCAACTTA TGCCATGTTT GTACAGACAC ATAGACCAAC
 AGGGGAGTAT ATGTTTGAGT TTGATGAGGA TGAGATGTTC TATGTGGATC
 TGGACAAGAA GGAGACCGTC TGGCATCTGG AGGAGTTTGG CCGAGCCTTT
 TCCTTTGAGG CTCAGGGCGG GCTGGCTAGC ATTGCTATAT TGAACAACAA
 CTTGAATAAC ACGATCCAGC GTTCCAACTA CACTCAGGCC GCCAATGATC
 CCCCTGAGGT GACCGTGTTT CCCAAGGAGC CTGTGGTGCT GGGCCAACCC
 AACACCCTCA TCTGCCACAT TGACAAGTTC TTCCCTCCAG TGCTCAACGT
 CACGTGGCTG TGCAACGGGC AGCCGGTCAC TGAGGGTGTC GCTGAGAGCC
 TCTTCCTGCC CAGAACAGAT TATAGCTTCC ACAAGTTCCA TTACCTGACC
 TTTGTGCCCT CAGCCGAGGA CTACTATGAC TGCAGGGTGG AGCACTGGGG
 CTTGGACCAG CCGCTCCTCA AACACTGG*  
>DL;IPD:MHC04737
IPD:MHC04737 Mafa-DPA1*02:26 783 bases
 ATGCGTCCTG AAGACAGAAT GTTCGAGACC AGAGCTGTTA TCTTGAGAAC
 CCTCTCCTTG GCTTTGCTGC TGAGTCTCGG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT ATCAACTTAT GCCTTGTTTG TACAGACACA TAGACCAACA
 GGGGAGTTTA TGTTTGAGTT TGATGAAGAT GAGATGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CGATCCGGCG TTCCAACTAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCATGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAACGTC
 ACGTGGCTGT GCAACGGGCA GCCCGTCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGATT ATAGCTTCCA CAAGTTCCAT TACCTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACTGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGATC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC01615
IPD:MHC01615 Mafa-DPA1*04:01 783 bases
 ATGCGTCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTTA TCTTGAGAAC
 CCTTTCCTTG GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT GTTAACTTTT ACCACATTTG TACAGACGCA TAGACCAACA
 GGGGAGTTTA TGTATGAGTT GGATGAAGAT GAAATATTCT TTGTGGATCT
 GGACAAGAAG GAGACCATCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATC GAACAACAAC
 TTGAATGTCA CGATCCAGCT TTCCAACCAT ACTCAGGCCA CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAATGTC
 ACATGGCTGT GCAACGGGCA GCCGGTCACT GAGGGTGTCA CTGAGAGCCT
 CTTCCTGCCC AGAACAGACT ACAGCTTCCA CAAGTTCCAT TACCTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAAC CGCTCCTCAA GCACTGGGAG CCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACCGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGACC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC03719
IPD:MHC03719 Mafa-DPA1*04:02 783 bases
 ATGCGTCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTTA TCTTGAGAAC
 CCTTTCCTTG GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT GTTAACTTTT ACCACATTTG TACAGACGCA TAGACCAACA
 GGGGAGTATA TGTATGAGTT GGATGAAGAT GAAATATTCT TTGTGGATCT
 GGACAAGAAG GAGACCATCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATC GAACAACAAC
 TTGAATGTCA CGATCCAGCT TTCCAACCAT ACTCAGGCCA CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAATGTC
 ACATGGCTGT GCAACGGGCA GCCGGTCACT GAGGGTGTCA CTGAGAGCCT
 CTTCCTGCCC AGAACAGACT ACAGCTTCCA CAAGTTCCAT TACCTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAAC CGCTCCTCAA GCACTGGGAG CCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACCGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGACC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC03708
IPD:MHC03708 Mafa-DPA1*06:01:01 765 bases
 ATGTTCCAGA CCAGAGCTAT TGTCTTGAGA ACCCTCTCCT TGGCTTTCCT
 GCTGAGTCTC CGAGGAGCTG GGGCCATCAA GGCGGACCAT GTATCAACTT
 ATGCCATGTT TGTACAGACA CATAGACCAA CAGGGGAGTT TATGTTTGAG
 TTTGATGAGG ATGAGATGTT CTATGTGGAT CTGGACAAGA AGGAGACCGT
 CTGGCATCTG GAGGAGTTTG GCCAAGCCAT TTCCTTTGAG GCTCAGGGCG
 GGCTGGCTAA CATTGCTATA TTGAACCACA ACTTGAATAT CACGATCCAG
 CGTTCCAACT ACACTCAGGC CGCCAATGAT CCCCCTGAGG TGACCGTGTT
 TCCCAAGGAG CCTGTGGAGC TGGGCCAACC CAACACCCTC ATCTGCCACA
 TTGACAAGTT CTTCCCTCCA GTGCTCAACG TCACGTGGCT GTGCAATGGG
 GAGCCGGTCA CTGAGGGTGT CGCTGAGAGC CTCTTCCTGC CCAGAACAGA
 TTATAGCTTC CACAAGTTCC ATTACCTGAC CTTTGTGCCC TCAGCCGAGG
 ACTACTATGA CTGCAGGGTG GAGCATTGGG GCTTGGACCA GCCGCTCCTC
 AAACACTGGG AGGCCCAAGA GCCAATCCAG ATCCCTGAGA CAACGGAGAC
 TGTGCTCTGT GCCCTGGGCC TGGTGCTGGG CCTAGTGGGC ATCATCGTGG
 GCACCGTCCT CATCATAAAG TCTCTGCGAT CTGGCCGTGA CCCCCGGGCC
 CAGGGGCCCC TGTGA*   
>DL;IPD:MHC04608
IPD:MHC04608 Mafa-DPA1*06:01:02 529 bases
 GCGGACCATG TATCAACTTA TGCCATGTTT GTACAGACAC ATAGACCAAC
 AGGGGAGTTT ATGTTTGAGT TTGATGAGGA TGAGATGTTC TATGTGGATC
 TGGACAAGAA GGAGACCGTC TGGCATCTGG AGGAGTTTGG CCAAGCCATT
 TCCTTTGAGG CTCAGGGCGG GCTGGCTAAC ATTGCTATAT TGAACCACAA
 CTTGAATATC ACGATCCAGC GTTCCAACTA CACTCAGGCC GCCAATGATC
 CCCCTGAGGT GACCGTGTTT CCCAAGGAGC CTGTGGAGCT GGGACAGCCC
 AACACCCTCA TCTGCCACAT TGACAAGTTC TTCCCTCCAG TGCTCAACGT
 CACGTGGCTG TGCAATGGGG AGCCGGTCAC TGAGGGTGTC GCTGAGAGCC
 TCTTCCTGCC CAGAACAGAT TATAGCTTCC ACAAGTTCCA TTACCTGACC
 TTTGTGCCCT CAGCCGAGGA CTACTATGAC TGCAGGGTGG AGCATTGGGG
 CTTGGACCAG CCGCTCCTCA AACACTGGG*  
>DL;IPD:MHC04603
IPD:MHC04603 Mafa-DPA1*06:02 528 bases
 GCGGACCATG TATCAACTTA TGCCATGTTT GTACAGACAC ATAGACCAAC
 AGGGGAGTTT ATGTTTGAGT TTGATGAGGA TGAGATGTTC TATGTGGATC
 TGGACAAGAA GGAGACCGTC TGGCATCTGG AGGAGTTTGG CCGAGCCTTT
 TCCTTTGAGG CTCAGGGCGG GCTGGCTAAC ATTGCTATAT TGAACAACAA
 CTTGAATATC ACGATCCAGC GTTCCAACTA CACTCAGGCC GCCAATGATC
 CCCCTGAGGT GACCGTGTTT CCCAAGGAGC CTGTGGAGCT GGGCCAACCC
 AACACCCTCA TCTGCCACAT TGACAAGTTC TTCCCTCCAG TGCTCAACGT
 CACGTGGCTG TGCAATGGGG AGCCGGTCAC TGAGGGTGTC GCTGAGAGCC
 TCTTCCTGCC CAGAACAGAT TACAGCTTCC ACAAGTTCCA TTACCTGACC
 TTTGTGCCCT CAGCCGAGGA CTACTATGAC TGCAGGGTGG AGCACTGGGG
 CTTGGACCAG CCGCTCCTCA AACACTGG*  
>DL;IPD:MHC04604
IPD:MHC04604 Mafa-DPA1*06:03 528 bases
 GCGGACCATG TATCAACTTA TGCCATGTTT GTACAGACAC ATAGACCAAC
 AGGGGAGTTT ATGTTTGAGT TTGATGAGGA TGAGATGTTC TATGTGGATC
 TGGACAAGAA GGAGACCGTC TGGCATCTGG AGGAGTTTGG CCGAGCCTTT
 TCCTTTGAGG CTCAGGGCGG GCTGGCTAAC ATTGCTATAT TGAACGACAA
 CTTGAATATC ACGATCCAGC GTTCCAACTA CACTCAGGCC GCCAATGATC
 CCCCTGAGGT GACCGTGTTT CCCAAGGAGC CTGTGGAGCT GGGCCAACCC
 AACACCCTCA TCTGCCACAT TGACAAGTTC TTCCCTCCAG TGCTCAACGT
 CACGTGGCTG TGCAATGGGG AGCCGGTCAC TGAGGGTGTC GCTGAGAGCC
 TCTTCCTGCC CAGAACAGAT TACAGCTTCC ACAAGTTCCA TTACCTGACC
 TTTGTGCCCT CAGCCGAGGA CTACTATGAC TGCAGGGTGG AGCACTGGGG
 CTTGGACCAG CCGCTCCTCA AACACTGG*  
>DL;IPD:MHC01612
IPD:MHC01612 Mafa-DPA1*07:01 783 bases
 ATGTGCCCTG AGGACAGAAT GTTCCAGACC AGAGCTGTGA TCTTGAGAAC
 CCTCTCCTTG GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT GTCCACTTAT GCCTTGTTTG TACAGACACA TAGACCAACA
 GGGGAGTTTA TGTTTGAGTT TGATGAAGAT GAGATGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGAGGG CTGGCTAACA TTGCTGCATT GAACAACAAC
 TTGAATACCT TGATCCAGCT TTCCAACCAC ACTCCGGCCG CCAATGATCC
 CCCTGAGGTG ACTGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAGCCCA
 ACACCCTCAT CTGCCACATT GACAAATTCT TCCCTCCGGT GCTCAACGTC
 ACGTGGCTGT GCAACGGAGA GCCGGTCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACTGATT ACAGATTACA CAAGTTCCAT TACCTGACCT
 TTGTGCCCTC AGCCGAGGAC TTCTATGACT GCAGGGTGGA ACACTGGGGC
 TTGGACCAGC CGCTCCTCAA GCACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGTCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC AGCATCCTCA TCTTAAAGGC TATGCGTTCT
 GGCCGTGACC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC01613
IPD:MHC01613 Mafa-DPA1*07:02 765 bases
 ATGTTCCAGA CCAGAGCTGT GATCTTGAGA GCCCTCTCCT TGGCTTTCCT
 GCTGAGTCTC CGAGGAGCTG GGGCCATCAA GGCGGACCAT GTGTCCACTT
 ATGCCTCGTT TGTACAGACA CATAGACCAA CAGGGGAGTA TATGTTTGAG
 TTTGATGAGG ATGAGATGTT CTATGTGGAT CTGGACAAGA AGGAGACCGT
 CTGGCATCTG GAGGAGTTTG GCCGAGCCTT TTCCTTTGAG GCTCAGGGCG
 GGCTGGCTAA CATTGCTGCA TTGAACAACA ACTTGAATAC CTTGATCCAG
 CTTTCCAACC ACACTCCGGC CGCCAATGAT CCCCCTGAGG TGACTGTGTT
 TCCCAAGGAG CCTGTGGAGC TGGGACAGCC CAACACCCTC ATCTGCCACA
 TTGACAAGTT CTTCCCACCG GTGCTCAACG TTACATGGCT GTGCAATGGG
 GAGCCGGTCA CTGAGGGTGT TGCTGAGAGC CTCTTCCTGC CCAGAACAGA
 TTACAGATTA CACAAGTTCC ATTACCTGAC CTTTGTGCCC TCGGCCGAGG
 ACTTCTATGA CTGCAGGGTG GAACACTGGG GCTTGGACCA GCCGCTCCTC
 AAGCACTGGG AGGCCCAAGA GCCAATCCAG ATGCCTGAGA CAAGGGAGAC
 TGTGCTCTGT GCCCTGGGCC TGGTGCTGGG CCTAGTGGGC ATCATCGTGG
 GCACCGTCCT CATCATAAAG TCTCTGCAAT CTGGCCGTGA CCCCCGGGCC
 CAGGGGCCCC TGTGA*   
>DL;IPD:MHC03709
IPD:MHC03709 Mafa-DPA1*07:03 765 bases
 ATGTTCCAGA CCAGAGCTGT GATCTTGAGA GCCCTCTCCT TGGCTTTCCT
 GCTGAGTCTC CGAGGAGCTG GGGCCATCAA GGCGGACCAT GTGTCCACTT
 ATGCCTCGTT TGTACAGACA CATAGACCAA CAGGGGAGTA TATGTTTGAG
 TTTGATGAGG ATGAGATGTT CTATGTGGAT CTGGACAAGA AGGAGACCGT
 CTGGCATCTG GAGGAGTTTG GCCGAGCCTT TTCCTTTGAG GCTCAGGGCG
 GGCTGGCTAA CATTGCTGCA TTGAACCACA ACTTGAATAC CTTGATCCAG
 CGTTCCAACC ACACTCAGGC CGCCAATGAT CCCCCTGAGG TGACTGTGTT
 TCCCAAGGAG CCTGTGGAGC TGGGACAGCC CAACACCCTC ATCTGCCACA
 TTGACAAGTT CTTCCCACCG GTGCTCAACG TTACATGGCT GTGCAATGGG
 GAGCCGGTCA CTGAGGGTGT TGCTGAGAGC CTCTTCCTGC CCAGAACAGA
 TTACAGATTA CACAAGTTCC ATTACCTGAC CTTTGTGCCC TCGGCCGAGG
 ACTTCTATGA CTGCAGGGTG GAACACTGGG GCTTGGACCA GCCGCTCCTC
 AAGCACTGGG AGGCCCAAGA GCCAATCCAG ATGCCTGAGA CAAGGGAGAC
 TGTGCTCTGT GCCCTGGGCC TGGTGCTGGG CCTAGTGGGC ATCATCGTGG
 GCACCGTCCT CATCATAAAG TCTCTGCGAT CTGGCCGTGA CCCCCGGGCC
 CAGGGGCCCC TGTGA*   
>DL;IPD:MHC03714
IPD:MHC03714 Mafa-DPA1*07:04 783 bases
 ATGTGCCCGG AGGACAGAAT GTTCCAGACC AGAGCTGTGA TCTTGAGAAC
 CCTCTCCTTG GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT ATCAACTTAT GCCATGTTTG TACAGACACA TAGACCAACA
 GGGGAGTTTA TGTTTGAGTT TGATGAAGAT GAGATGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTGCATT GAACCACAAC
 TTGAATACCT TGATCCAGCT TTCCAACCAC ACTCCGGCCG CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAGCCCA
 ACACCCTCAT CTGCCACATT GACAAATTCT TCCCTCCGGT GCTCAACGTC
 ACGTGGCTGT GCAACGGAGA GCCGGTCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACTGATT ACAGATTACA CAAGTTCCAT TACCTGACCT
 TTGTGCCCTC AGCCGAGGAC TTCTATGACT GCAGGGTGGA ACACTGGGGC
 TTGGACCAGC CGCTCCTCAA GCACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGTCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC AGCATCCTCA TCTTAAAGGC TATGCGTTCT
 GGCCGTGACC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC04601
IPD:MHC04601 Mafa-DPA1*07:05 529 bases
 GCGGACCATG TGTCCACTTA TGCCTCGTTT GTACAGACAC ATAGACCAAC
 AGGGGAGTTT ATGTTTGAGT TTGATGAAGA TGAGCAGTTC TATGTGGATC
 TGGACAAGAA GGAGACCGTC TGGCATCTGG AGGAGTTTGG CCGAGCCTTT
 TCCTTTGAGG CTCAGGGCGG GCTGGCTAAC ATTGCTGCAT TGAACCACAA
 CTTGAATATC TTGATCCAGC GTTCCAACCA CACTAAGGCC GCCAATGATC
 CCCCTGAGGT GACCGTGTTT CCCAAGGAGC CTGTGGAGCT GGGACAGCCC
 AACACCCTCA TCTGCCACAT TGACAAGTTC TTCCCACCGG TGCTCAACGT
 TACATGGCTG TGCAATGGGG AGCCGGTCAC TGAGGGTGTT GCTGAGAGCC
 TCTTCCTGCC CAGAACAGAT TACAGATTAC ACAAGTTCCA TTACCTGACC
 TTTGTGCCCT CGGCCGAGGA CTTCTATGAC TGCAGGGTGG AACACTGGGG
 CTTGGACCAG CCGCTCCTCA AGCACTGGG*  
>DL;IPD:MHC04605
IPD:MHC04605 Mafa-DPA1*07:06 529 bases
 GCGGACCATG TGTCCACTTA TGCCTCGTTT GTACAGACAC ATAGACCAAC
 AGGGGAGTTT ATGTTTGAGT TTGATGAGGA TGAGATGTTC TATGTGGATC
 TGGACAAGAA GGAGACCGTC TGGCATCTGG AGGAGTTTGG CCGAGCCTTT
 TCCTTTGAGG CTCAGGGCGG GCTGGCTAAC ATTGCTGCAT TGAACCACAA
 CTTGAATAAC TTGATCCAGC GTTCCAACCA CACTCAGGCC GCCAATGATC
 CCCCTGAGGT GACCGTGTTT CCCAAGGAGC CTGTGGAGCT GGGACAGCCC
 AACACCCTCA TCTGCCACAT TGACAAGTTC TTCCCACCGG TGCTCAACGT
 TACATGGCTG TGCAATGGGG AGCCGGTCAC TGAGGGTGTT GCTGAGAGCC
 TCTTCCTGCC CAGAACAGAT TACAGATTAC ACAAGTTCCA TTACCTGACC
 TTTGTGCCCT CGGCCGAGGA CTTCTATGAC TGCAGGGTGG AACACTGGGG
 CTTGGACCAG CCGCTCCTCA AGCACTGGG*  
>DL;IPD:MHC04606
IPD:MHC04606 Mafa-DPA1*07:07 783 bases
 GTGTGCCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTGA TCTTGAGAGC
 CCTCTCCTGG GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT GTCCACTTAT GCCTCGTTTG TACAGACACA TAGACCAACA
 GGGGAGTTTA TGTTTGAGTT TGATGAGGAT GAGATGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTGCATT GAACCACAAC
 TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACTGTGTTTC CCAAGGAGCC TGTGGAGCTG GGACAGCCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCACCGGT GCTCAACGTT
 ACATGGCTGT GCAATGGGGA GCCGGTCACT GAGGGTGTTG CTGAGAGCCT
 CTTCCTGCCC AGAACAGATT ACAGATTACA CAAGTTCCAT TACCTGACCT
 TTGTGCCCTC GGCCGAGGAC TTCTATGACT GCAGGGTGGA ACACTGGGGC
 TTGGACCAGC CGCTCCTCAA GCACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA AGGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACCGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGACC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC04607
IPD:MHC04607 Mafa-DPA1*07:08 529 bases
 GCGGACCATG TGTCCACTTA TGCCTCGTTT GTACAGACAC ATAGACCAAC
 AGGGGAGTTT ATGTTTGAGT TTGATGAAGA TGAGCAGTTC TATGTGGATC
 TGGACAAGAA GGAGACCGTC TGGCATCTGG AGGAGTTTGG CCGAGCCTTT
 TCCTTTGAGG CTCAGGGCGG GCTGGCTAAC ATTGCTGCAT TGAACCACAA
 CTTGAATATC TTGATCCAGC GTTCCAACCA CACTCAGGCC GCCAATGATC
 CCCCTGAGGT GACCGTGTTT CCCAAGGAGC CTGTGGAGCT GGGACAGCCC
 AACACCCTCA TCTGCCACAT TGACAAGTTC TTCCCACCGG TGCTCAACGT
 TACATGGCTG TGCAATGGGG AGCCGGTCAC TGAGGGTGTT GCTGAGAGCC
 TCTTCCTGCC CAGAACAGAT TACAGATTAC ACAAGTTCCA TTACCTGACC
 TTTGTGCCCT CGGCCGAGGA CTTCTATGAC TGCAGGGTGG AACACTGGGG
 CTTGGACCAG CCGCTCCTCA AGCACTGGG*  
>DL;IPD:MHC04610
IPD:MHC04610 Mafa-DPA1*07:09 529 bases
 GCGGACCATG TGTCCACTTA TGCCTCGTTT GTACAGACAC ATAGACCAAC
 AGGGGAGTTT ATGTTTGAGT TTGATGAGGA TGAGATGTTC TATGTGGATC
 TGGACAAGAA GGAGACCGTC TGGCATCTGG AGGAGTTTGG CCGAGCCCTT
 TTCCTTGAGG CTCAGGGCGG GCTGGCTAAC ATTGCTGCAT TGAACCACAA
 CTTGAATACC TTGATCCAGC GTTCCAACCA CACTCAGGCC GCCAATGATC
 CCCCTGAGGT GACTGTGTTT CCCAAGGAGC CTGTGGAGCT GGGACAGCCC
 AACACCCTCA TCTGCCACAT TGACAAGTTC TTCCCACCGG TGCTCAACGT
 TACATGGCTG TGCAATGGGG AGCCGGTCAC TGAGGGTGTT GCTGAGAGCC
 TCTTCCTGCC CAGAACAGAT TACAGATTAC ACAAGTTCCA TTACCTGACC
 TTTGTGCCCT CGGCCGAGGA CTTCTATGAC TGCAGGGTGG AACACTGGGG
 CTTGGACCAG CCGCTCCTCA AGCACTGGG*  
>DL;IPD:MHC04612
IPD:MHC04612 Mafa-DPA1*07:10 529 bases
 GCGGACCATG TGTCCACTTA TGCCTTGTTT GTACAGACAC ATAGACCAAC
 AGGGGAGTAT ATGTCTGAGT TTGATGAGGA TGAGATGTTC TATGTGGATC
 TGGACAAGAA GGAGACCGTC TGGCATCTGG AGGAGTTTGG CCGAGCCCTT
 TTCCTTGAGG CTCAGGGCGG GCTGGCTAAC ATTGCTGCAT TGAACAACAA
 CTTGAATATC ATGATCCAGC GTTCCAACCA CACTCAGGCC GCCAATGATC
 CCCCTGAGGT GACTGTGTTT CCCAAGGAGC CTGTGGAGCT GGGACAGCCC
 AACACCCTCA TCTGCCACAT TGACAAGTTC TTCCCACCAG TGCTCAACGT
 CACATGGCTG TGCAATGGGG AGCCGGTCAC TGAGGGTGTC GCTGAGAGCC
 TCTTCCTGCC CAGAACAGAT TACAGATTAC ACAAGTTCCA TTACCTGACC
 TTTGTGCCCT CGGCCGAGGA CTACTATGAC TGCAGGGTGG AACACTGGGG
 CTTGGACCAG CCGCTCCTCA AGCACTGGG*  
>DL;IPD:MHC04613
IPD:MHC04613 Mafa-DPA1*07:11 529 bases
 GCGGACCATG TGTCCACTTA TGCCTCGTTT GTACAGACAC ATAGACCAAC
 AGGGGAGTAT ATGTTTGAGT TTGATGAAGA TGAGCAGTTC TATGTGGATC
 TGGACAAGAA GGAGACCGTC TGGCATCTGG AGGAGTTTGG CCGAGCCTTT
 TCCTTTGAGG CTCAGGGCGG GCTGGCTAAC ATTGCTGCAT TGAACCACAA
 CTTGAATATC TTGATCCAGC GTTCCAACCA CACTAAGGCC GCCAATGATC
 CCCCTGAGGT GACTGTGTTT CCCAAGGAGC CTGTGGAGCT GGGACAGCCC
 AACACCCTCA TCTGCCACAT TGACAAGTTC TTCCCACCGG TGCTCAACGT
 TACATGGCTG TGCAATGGGG AGCCGGTCAC TGAGGGTGTT GCTGAGAGCC
 TCTTCCTGCC CAGAACAGAT TACAGATTAC ACAAGTTCCA TTACCTGACC
 TTTGTGCCCT CGGCCGAGGA CTTCTATGAC TGCAGGGTGG AACACTGGGG
 CTTGGACCAG CCGCTCCTCA AGCACTGGG*  
>DL;IPD:MHC04614
IPD:MHC04614 Mafa-DPA1*07:12 529 bases
 GCGGACCATG TATCAACTTA TGCCATGTTT GTACAGACAC ATAGACCAAC
 AGGGGAGTTT ATGTTTGAGT TTGATGAAGA TGAGATGTTC TATGTGGATC
 TGGACAAGAA GGAGACCGTC TGGCATCTGG AGGAGTTTGG CCGAGCCTTT
 TCCTTTGAGG CTCAGGGCGG GCTGGCTAAC ATTGCTGCAT TGAACAACAA
 CTTGAATACC TTGATCCAGC TTTCCAACCA CACTCCGGCC GCCAATGATC
 CCCCTGAGGT GACCGTGTTT CCCAAGGAGC CTGTGGAGCT GGGCCAGCCC
 AACACCCTCA TCTGCCACAT TGACAAATTC TTCCCTCCGG TGCTCAACGT
 CACGTGGCTG TGCAACGGAG AGCCGGTCAC TGAGGGTGTC GCTGAGAGCC
 TCTTCCTGCC CAGAACTGAT TACAGATTAC ACAAGTTCCA TTACCTGACC
 TTTGTGCCCT CAGCCGAGGA CTTCTATGAC TGCAGGGTGG AACACTGGGG
 CTTGGACCAG CCGCTCCTCA AGCACTGGG*  
>DL;IPD:MHC05214
IPD:MHC05214 Mafa-DPA1*07:13 770 bases
 ACAGAATGTT CCAGACCAGA GCTGTGATCT TGAGAACCCT CTCCTTGGCT
 TTCCTGCTGA GTCTCCGAGG AGCTGGGGCC ATCAAGGCGG ACCATGTATC
 AACTTATGCC ATGTTTGTAC AGACACATAG ACCAACAGGG GAGTTTATGT
 TTGAGTTTGA TGAAGATGAG ATGTTCTATG TGGATCTGGA CAAGAAGGAG
 ACCGTCTGGC ATCTGGAGGA GTTTGGCCGA GCCTTTTCCT TTGAGGCTCA
 GGGCGGGCTG GCTAACATTG CTGCATTGAA CCACAACTTG AATACCTTGA
 TCCAGCTTTC CAACCACACT CCGGCCGCCA GTGATCCCCC TGAGGTGACC
 GTGTTTCCCA AGGAGCCTGT GGAGCTGGGC CAGCCCAACA CCCTCATCTG
 CCACATTGAC AAATTCTTCC CTCCGGTGCT CAACGTCACG TGGCTGTGCA
 ACGGAGAGCC GGTCACTGAG GGTGTCGCTG AGAGCCTCTT CCTGCCCAGA
 ACTGATTACA GATTACACAA GTTCCATTAC CTGACCTTTG TGCCCTCAGC
 CGAGGACTTC TATGACTGCA GGGTGGAACA CTGGGGCTTG GACCAGCCGC
 TCCTCAAGCA CTGGGAGGCC CAAGAGCCAA TCCAGATGCC TGAGACAACG
 GAGACTGTGC TCTGTGCCCT GGGTCTGGTG CTGGGCCTAG TGGGCATCAT
 CGTGGGCAGC ATCCTCATCT TAAAGGCTAT GCGTTCTGGC CGTGACCCCC
 GGGCCCAGGG GCCCCTGTGA *  
>DL;IPD:MHC03713
IPD:MHC03713 Mafa-DPA1*08:01 783 bases
 ATGCGTCCTG AAGACAGAAT GTTCGAGACC AGAGCTGTTA TCTTGAGAAC
 CCTCTCCTTG GCTTTGCTGC TGAGTCTCGG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT GTCCACTTAT GCCTTGTTTG TACAGACACA TAGACCAACA
 GGGGAGTATA TGTTTGAGTT TGATGAGGAT GAGATGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGATGACA TTGCTACATT GAAGTACAAC
 TTGAATATCA CGATCCAGCG TTCCAACCAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ATGGTGTTTC CCAAGGAGCC TGTGGAGCTG GGACAGCCCA
 ACACCCTCAT CTGCCACATT GACAAATTCT TCCCTCCGGT GCTCAACGTC
 ACGTGGCTGT GCAATGGGGA GCCGGTCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGACT ACAGCTTCCA CAAGTTCCAT TACTTGACCT
 TTGTGCCCTC GGCCGAAGAC TTCTATGACT GCAGGGTGGA GCATTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACCATCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGACC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC03705
IPD:MHC03705 Mafa-DPA1*09:01 783 bases
 ATGTGCCCTG AAGGCAGAAT GTTCCAGACC AGAGCTGTGA TCTTGAGAGC
 CCTCTCCTTG GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT ATCAACTTAT GTCATGTTTG TACAGACACA TAGACCAACA
 GGAGAGTTTA TGTTTGAGTT TGATGAGGAT GAGATGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 TCTTTGAGGC TCAGAGGGTG CTGTCTCACA TTGTTATATT GAATGACAGC
 TTGAATATCA TGATCCAGCG TTCCAACCAC ACTCCGGCCG CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGACAGCCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCACCAGT GCTCAATGTC
 ACATGGCTGT GCAACGGGCA GCCGGTCACT GAGGGTGTCG CTGAGAGCAT
 CTTCCTGCCC AGAACAGGTT ACAACTTCCA CAAGTTCCAT TACCTGACCT
 TTGTGCCCTC GGCCGAGGAC GTCTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA GCACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC AGCATCCTCA TCTTAAAGGC TATGCGTTCT
 GGCCGTGACC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC05204
IPD:MHC05204 Mafa-DPA1*09:02 751 bases
 AGCTGTGATC TTGAGAGCCC TCTCCTTGGC TTTCCTGCTG AGTCTCCGAG
 GAGCTGGGGC CATCAAGGCG GACCATGTAT CAACTTATGT CATGTTTGTA
 CAGACACATA GACCAACAGG AGAGTTTATG TTTGAGTTTG ATGAGGATGA
 GATGTTCTAT GTGGATCTGG ACAAGAAGGA GACCGTCTGG CATCTGGAGG
 AGTTTGGCCG AGCCTTTTTC TTTGAGGCTC AGAGGGTGCT GTCTCACATT
 GTTATATTGA ATGACAGCTT GAATATCATG ATCCAGCGTT CCAACCACAC
 TCCGGCCGCC AATGATCCCC CTGAGGTGGC CGTGTTTCCC AAGGAGCCTG
 TGGAGCTGGG ACAGCCCAAC ACCCTCATCT GCCACATTGA CAAGTTCTTC
 CCACCAGTGC TCAATGTCAC GTGGCTGTGC AACGGGCAGC CGGTCACTGA
 GGGTGTCGCT GAGAGCATCT TCCTGCCCAG AACAGGTTAC AACTTCCACA
 AGTTCCATTA CCTGACCTTT GTGCCCTCGG CCGAGGACGT CTATGACTGC
 AGGGTGGAGC ACTGGGGCTT GGACCAGCCG CTCCTCAAGC ACTGGGAGGC
 CCAAGAGCCA ATCCAGATGC CTGAGACAAC GGAGACTGTG CTCTGTGCCC
 TGGGCCTGGT GCTGGGCCTA GTGGGCATCA TCGTGGGCAG CATCCTCATC
 TTAAAGGCTA TGCGTTCTGG CCGTGACCCC CGGGCCCAGG GGCCCCTGTG
 A*    
>DL;IPD:MHC04115
IPD:MHC04115 Mafa-DPA1*10:01 783 bases
 ATGCGCCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTTA TCTTGAGAAC
 CCTCTCTTTG GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT GTCCACTTTT GCCATGTTTG TACAGACACA TAGACCAACA
 GGGGAGTATA TGTCTGAATT TGATGAGGAT GAGATGCTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCCTTT
 TCCTTGACGC TCAGGGCGGG CTGGCTAACA TTGCTGCATT GAACAACCAC
 TTGAATATCA TGATCCAGCG TTCCAACCAC TCTCAGGCCG CCAATGATCC
 TCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAGCCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCACCAGT GCTCAACGTC
 ACATGGCTGT GCAACGGAGA GCTGGTCACT AAGGGTGTCA CTGAGAGCCT
 CTTCCTGCCC AGAACAGATT ACAGATTACA CAAGTTCCAT TACTTGACCT
 TTGTGCCCTC GGCCGAGGAC TACTATGACT GCAGGGTGGA ACACTGGGGC
 TTGGACCAGC CACTCCTCAA GCACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC AGCATCCTCA TCTTAAAGGC TATGCGTTCT
 GGCCGTGACT CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC04599
IPD:MHC04599 Mafa-DPA1*10:02 529 bases
 GCGGACCATG TGTCCACTTT TGCCATGTTT GTACAGACAC ATAGACCAAC
 AGGGGAGTAT ATGTCTGAAT TTGATGAGGA TGAGATGCTC TATGTGGATC
 TGGACAAGAA GGAGACCGTC TGGCATCTGG AGGAGTTTGG CCGAGCCCTT
 TTCCTTGACG CTCAGGGCGT GCTGGCTAAC ATTGCTGCAT TGAACAACCA
 CTTGAATATC ATGATCCAGC GTTCCAACCA CTCTCAGGCC GCCAATGATC
 CCCCTGAGGT GACTGTGTTT CCCAAGGAGC CTGTGGAGCT GGGCCAGCCC
 AACACCCTCA TCTGCCACAT TGACAAGTTC TTCCCACCAG TGCTCAACGT
 CACATGGCTG TGCAATGGAA AGCTGGTCAC TAAGGGTGTC ACTGAGAGCC
 TCTTCCTGCC CAGAACAGAT TACAGATTAC ACAAGTTCCA TTACTTGACC
 TTTGTGCCCT CGGCCGAGGA CTACTATGAC TGCAGGGTGG AACACTGGGG
 CTTGGACCAG CCACTCCTCA AGCACTGGG*  
>DL;IPD:MHC04609
IPD:MHC04609 Mafa-DPA1*10:03 529 bases
 GCGGACCATG TGTCCACTTT TGCCATGTTT GTACAGACAC ATAGACCAAC
 AGGGGAGTAT ATGTCTGAAT TTGATGAGGA TGAGATGCTC TATGTGGATC
 TGGACAAGAA GGAGACCGTC TGGCATCTGG AGGAGTTTGG CCGAGCCCTT
 TTCCTTGACG CTCAGGGCGG GCTGGCTAAC ATTGCTGCAT TGAACAACCA
 CTTGAATATC ATGATCCAGC GTTCCAACCA CTCTCAGGCC GCCAATGATC
 CCCCTGAGGT GACTGTGTTT CCCAAGGAGC CTGTGGAGCT GGGCCAGCCC
 AACACCCTCA TCTGCCACAT TGACAAGTTC TTCCCACCAG TGCTCAACGT
 CACATGGCTG TGCAATGGAA AGCTGGTCAC TAAGGGTGTC ACTGAGAGCC
 TCTTCCTGCC CAGAACAGAT TACAGATTAC ACAAGTTCCA TTACTTGACC
 TTTGTGCCCT CGGCCGAGGA CTACTATGAC TGCAGGGTGG AACACTGGGG
 CTTGGACCAG CCACTCCTCA AGCACTGGG*  
>DL;IPD:MHC04611
IPD:MHC04611 Mafa-DPA1*10:04 529 bases
 GCGGACCATG TGTCCACTTT TGCCATGTTT GTACAGACAC ATAGACCAAC
 AGGGGAGTAT ATGTCTGAAT TTGATGAGGA TGAGATGTTC TATGTGGATC
 TGGACAAGAA GGAGACCGTC TGGCATCTGG AGGAGTTTGG CCGAGCCCTT
 TTCCTTGACG CTCAGGGCGG GCTGGCTAAC ATTGCTGCAT TGAACAACCA
 CTTGAATATC ATGATCCAGC GTTCCAACCA CTCTCAGGCC GCCAATGATC
 CTCCTGAGGT GACCGTGTTT CCCAAGGAGC CTGTGGAGCT GGGCCAGCCC
 AACACCCTCA TCTGCCACAT TGACAAGTTC TTCCCACCAG TGCTCAACGT
 CACATGGCTG TGCAACGGAG AGCTGGTCAC TAAGGGTGTC ACTGAGAGCC
 TCTTCCTGCC CAGAACAGAT TACAGATTAC ACAAGTTCCA TTACTTGACC
 TTTGTGCCCT CGGCCGAGGA CTACTATGAC TGCAGGGTGG AACACTGGGG
 CTTGGACCAG CCACTCCTCA AGCACTGGG*  
