>DL;IPD:MHC00275
IPD:MHC00275 Mafa-DQA1*01:01 62 bases
 TYGLSGQYTH EFDGDEQFYV DLERKETAWR WPELSKFGGF DPQGALRNLA
 VSKHNLNIMT KR*   
>DL;IPD:MHC01175
IPD:MHC01175 Mafa-DQA1*01:02 256 bases
 MILNKALMLG ALVLTAVMSP CGGEDIVADH VASCGVNLYQ TYGLSGQYTH
 EFDGDEQFYV NLERKETAWR WPELSKFGGF DPQGALRNLA VSKHNLNIMT
 KRYNSTAAIN EVPEVTVFSK SPVMLGQPNT LICLVDNIFP PVVNITWLSN
 GRSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCR VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII QGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC01177
IPD:MHC01177 Mafa-DQA1*01:03:02 256 bases
 MILNKALMLG ALVLTAVMSP CGGEDIVADH VASCGVNLYQ TYGLSGQYTH
 EFDGDEQFYV DLERKETAWR WPELSKFGGF DPQGALRNLA VSKHNLNIMT
 KRYNSTAAIN EVPEVTVFSK SPVTLGHPNT LICLVDNIFP PVVNITWLSN
 GHSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCR VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII QGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC04700
IPD:MHC04700 Mafa-DQA1*01:03:03 229 bases
 GGEDIVADHV ASCGVNLYQT YGLSGQYTHE FDGDEQFYVD LERKETAWRW
 PELSKFGGFD PQGALRNLAV SKHNLNIMTK RYNSTAAINE VPEVTVFSKS
 PVTLGHPNTL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF
 FKISYLTFLP SADEIYDCRV EHWGLDEPLL KHWEPEIPAP MSELTETVVC
 ALGLSVGLVG IVVGTVFIIQ GLRSVGASR*  
>DL;IPD:MHC01178
IPD:MHC01178 Mafa-DQA1*01:04 256 bases
 MILNKALMLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ SYGPSGQYTH
 EFDGDEQFYV DLGRKETAWR WPELSKFGGF DPQGALRNLA TVKYNLNIMT
 KRYNSTAATN EVPEVTVFSK SPVTLGQPNT LICLVDNIFP PVVNITWLSN
 GRSVTEGVSE TSFLSKSDHS FIKISYLTFL PSADEIYDCR VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII QGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC01179
IPD:MHC01179 Mafa-DQA1*01:05 74 bases
 DHVASCGVNL YQSYGTSGQY NHEFDGDEQF YVDLGRKETA WRWPELSKFE
 GFDPQGALRN LAAAKHNLNI LTKR*  
>DL;IPD:MHC01620
IPD:MHC01620 Mafa-DQA1*01:06 256 bases
 MILNKALMLG ALVLTAVMSP CGGEDIVADH VASCGVNLYQ SYGTSGQYNH
 EFDGDEQFYV DLGRKETAWR WPELSKFGGF DPQGALRNLA AAKHNLNILT
 KRYNSTAATN EVPEVTVFSK SPVTLGQPNT LICLVDNIFP PVVNITWLSN
 GHSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCR VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII QGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC01621
IPD:MHC01621 Mafa-DQA1*01:07:01 256 bases
 MILNKALMLG ALVLTAVMSP CGGEDIVADH VASCGVNLYQ TYGLSGQFTH
 EFDGDEQFYV DLRRKETAWR WPELSKFGGF DPQGALRNLA VLKHNLNIVT
 KRYNSTAATN EVPEVTVFSK SPVTLGHPNT LICLVDNIFP PVVNITWLSN
 GRSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCR VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII QGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC04708
IPD:MHC04708 Mafa-DQA1*01:07:02 229 bases
 GGEDIVADHV ASCGVNLYQT YGLSGQFTHE FDGDEQFYVD LRRKETAWRW
 PELSKFGGFD PQGALRNLAV LKHNLNIVTK RYNSTAATNE VPEVTVFSKS
 PVTLGHPNTL ICLVDNIFPP VVNITWLSNG RSVTEGVSET SFLSKSDHSF
 FKISYLTFLP SADEIYDCRV EHWGLDEPLL KHWEPEIPAP MSELTETVVC
 ALGLSVGLVG IVVGTVFIIQ GLRSVGASR*  
>DL;IPD:MHC01622
IPD:MHC01622 Mafa-DQA1*01:08:01 256 bases
 MILNKALMLG ALALTTVISP CGGEDIVADH VASCGVNVYQ SYGPSGQYTH
 EFDGDEQFYV DLGRKETAWR WPELSKFGGF DPQGALRNLA TAKYNLNIMT
 KRYNSTAATN EVPEVTVFSK SPVTLGQPNT LICLVDNIFP PVVNITWLSN
 GRSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCR VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSAGLV GIVVGTVFII QGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC04131
IPD:MHC04131 Mafa-DQA1*01:08:02 256 bases
 MILNKALMLG ALALTTVISP CGGEDIVADH VASCGVNVYQ SYGPSGQYTH
 EFDGDEQFYV DLGRKETAWR WPELSKFGGF DPQGALRNLA TAKYNLNIMT
 KRYNSTAATN EVPEVTVFSK SPVTLGQPNT LICLVDNIFP PVVNITWLSN
 GRSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCR VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSAGLV GIVVGTVFII QGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC04703
IPD:MHC04703 Mafa-DQA1*01:08:03 229 bases
 GGEDIVADHV ASCGVNVYQS YGPSGQYTHE FDGDEQFYVD LGRKETAWRW
 PELSKFGGFD PQGALRNLAT AKYNLNIMTK RYNSTAATNE VPEVTVFSKS
 PVTLGQPNTL ICLVDNIFPP VVNITWLSNG RSVTEGVSET SFLSKSDHSF
 FKISYLTFLP SADEIYDCRV EHWGLDEPLL KHWEPEIPAP MSELTETVVC
 ALGLSAGLVG IVVGTVFIIQ GLRSVGASR*  
>DL;IPD:MHC03772
IPD:MHC03772 Mafa-DQA1*01:09 256 bases
 MILNKALMLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ SYGPSGQYTH
 EFDGDEQFYV DLGRKETAWR WPELSKFGGF DPQGALRNLA TVKYNLNIMT
 KRYNSTAATN EVPEVTVFSK SPVTLGQPNT LICLVDNIFP PVVNITWLSS
 GRSVTEGVSE TSFLSKSDHS FIKISYLTFL PSADEIYDCR VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII QGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC03773
IPD:MHC03773 Mafa-DQA1*01:10 256 bases
 MILNKALMLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ SYGPSGQFTH
 EFDGDEQFYV DLGRKETAWR WPELSKFGGF DPQGALRNLA AAKHNLNILT
 KRYNFTAATN EVPEVTVFSK SPVTLGQPNN LICLVDNIFP PVVNITWLSN
 GHSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCR VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII QGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC03775
IPD:MHC03775 Mafa-DQA1*01:11 256 bases
 MILNKALMLG ALVLTAVMSP CGGEDIVADH VASCGVNLYQ TYGLSGQYTH
 EFDGDEQFYV DLERKETAWR WPELSKFGGF DPQGALRNLA VSKHNLNIMT
 KRYNSTAAIN EVPEVTVFSK SPVMLGQPNT LICLVDNIFP PVVNITWLSN
 GRSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCR VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII QGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC03841
IPD:MHC03841 Mafa-DQA1*01:12 256 bases
 MILNKALMLG ALALTTMMSP CGGEDIVADH VASCGVNLYQ TYGLSGQFTH
 EFDGDEQFYV DLRRKETAWR WPELSKFGGF DPQGALRNLA VLKHNLNIVT
 KRYNSTAATN EVPEVTVFSK SPVTLGHPNT LICLVDNIFP PVVNITWLSN
 GRSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCR VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII QGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC04127
IPD:MHC04127 Mafa-DQA1*01:13 256 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ SYGPSGQYTH
 EFDGDEQFYV DLERKETAWR WPELRKFGGF DPQGALRNLA VAKHNLNIIT
 KDYNSTAATN EVPEVTVFSK SPVTLGQPNT LICLVDNIFP PVVNITWLSN
 GHSVTEGVSE TSFLSKSDHS FFKISHLTFL PSADEIYDCR VEHWGLDEPI
 LKHWEPEIPA PMSELTETVV CALGLSAGLV GIVVGTVFII QGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC04128
IPD:MHC04128 Mafa-DQA1*01:14:01 256 bases
 MILNKALMLG ALVLTAVMSP CGGEDIVADH VASCGVNLYQ TYGLSGQYTH
 EFDGDERFYV DLERKETAWR WPELSKFGGF DPQGALRNLA VLKHTLNIVT
 KRYNSTAATN EVPEVTVFSK SPVMLGQPNT LICLVDNIFP PVVNITWLSN
 GRSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCR VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII QGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC04714
IPD:MHC04714 Mafa-DQA1*01:14:02 229 bases
 GGEDIVADHV ASCGVNLYQT YGLSGQYTHE FDGDERFYVD LERKETAWRW
 PELSKFGGFD PQGALRNLAV LKHTLNIVTK RYNSTAATNE VPEVTVFSKS
 PVMLGQPNTL ICLVDNIFPP VVNITWLSNG RSVTEGVSET SFLSKSDHSF
 FKISYLTFLP SADEIYDCRV EHWGLDEPLL KHWEPEIPAP MSELTETVVC
 ALGLSVGLVG IVVGTVFIIQ GLRSVGASR*  
>DL;IPD:MHC01176
IPD:MHC01176 Mafa-DQA1*01:15 256 bases
 MILNKALMLG ALALTTMMSP CGGEDIVADH VASCGVNLYQ TYGLSGQYTH
 EFDGDEQFYV DLERKETAWR WPELSKFGGF DPQGALRNLA VSKHNLNIMT
 KRYNSTAATN EVPEVTVFSK SPVTLGHPNT LICLVDNIFP PVVNITWLSN
 GHSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCR VEHWGLDEPL
 LKHWEPEIPV PMSELTETVV CALGLSVGLV GIVVGTVFII QGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC05139
IPD:MHC05139 Mafa-DQA1*01:15:02 256 bases
 MILNKALMLG ALALTTMMSP CGGEDIVADH VASCGVNLYQ TYGLSGQYTH
 EFDGDEQFYV DLERKETAWR WPELSKFGGF DPQGALRNLA VSKHNLNIMT
 KRYNSTAATN EVPEVTVFSK SPVTLGHPNT LICLVDNIFP PVVNITWLSN
 GHSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCR VEHWGLDEPL
 LKHWEPEIPV PMSELTETVV CALGLSVGLV GIVVGTVFII QGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC04701
IPD:MHC04701 Mafa-DQA1*01:16 229 bases
 GGEDIVADHV ASCGVNLYQS YGPSGQFTHE FDGDEQFYVD LGRKETAWRW
 PELSKFGGFD PQGALRNLAA AKHNLNILTK RYNFTAATNE VPEVTVFSKS
 PVTLGQPNTL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF
 FKISYLTFLP SADEIYDCRV EHWGLDEPLL KHWEPEIPAP MSELTETVVC
 ALGLSVGLVG IVVGTVFIIQ GLRSVGASR*  
>DL;IPD:MHC04710
IPD:MHC04710 Mafa-DQA1*01:17 229 bases
 GGEDIVADHV ASCGVNLYQT YGLSGQYTHE FDGDERFYVD LERKETAWRW
 PELSKFGGFD PQGALRNLAV LKHTLNIVTK RYNSTAATNE VPEVTVFSKS
 PVMLGQPNTL ICLVDNIFPP VVNITWLSNG RSVTEGVSET SFLPKSDHSF
 FKISYLTFLP SADEIYDCKV EHWGLDELLL KHREPEIPAP LSELTETVVR
 ALGLSVGLVG IVVGTVLIIR GLRSVGASR*  
>DL;IPD:MHC05137
IPD:MHC05137 Mafa-DQA1*01:21 256 bases
 MILNKALMLG ALVLTAVMSP CGGEDIVADH VASCGVNLYQ TYGLSGQYTH
 EFDGDERFYV DLERKETAWR WPELSKFGGF DPQGALRNLA VSKHNLNIMT
 KRYNSTAATN EVPEVTVFSK SPVMLGQPNT LICLVDNIFP PVVNITWLSN
 GRSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCR VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII QGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC01180
IPD:MHC01180 Mafa-DQA1*05:01:01 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNVYQ SYGPSGQYSH
 EFDGDEQFYV DLGRKETVWR LPIPYRYGFD PQFALRNIAV LTHNLNILIK
 RSNSTAATNE VPEVTVFSKS PVMLGQPNTL ICLVDNIFPP VVNITWLSNG
 HSVIEGVSET SFLSKSDHSF FKMSYLTFLP SADEIYDCRV EHWGLDEPLL
 KHWEPEIPVP MSELTETVVC ALGLSAGLVG IVVGTVLIIR GLRSVGASRH
 QGPLX*    
>DL;IPD:MHC04704
IPD:MHC04704 Mafa-DQA1*05:01:02 228 bases
 GGEDIVADHV ASYGVNVYQS YGPSGQYSHE FDGDEQFYVD LGRKETVWRL
 PIPYRYGFDP QFALRNIAVL THNLNILIKR SNSTAATNEV PEVTVFSKSP
 VMLGQPNTLI CLVDNIFPPV VNITWLSNGH SVIEGVSETS FLSKSDHSFF
 KMSYLTFLPS ADEIYDCRVE HWGLDEPLLK HWEPEIPVPM SELTETVVCA
 LGLSAGLVGI VVGTVLIIRG LRSVGASR*  
>DL;IPD:MHC01181
IPD:MHC01181 Mafa-DQA1*05:02 250 bases
 ALLLGALTLT TVMSPCGGED IVADHVASYG VNVYQSYGPS GQFTHEFDGD
 EQFYVDLGRK ETVWRLPIPY RYGFDPQFAL RNIAVLTHNL NILIKRSNST
 AATNEVPEVT VFSKSPVMLG QPNTLICLVD NIFPPVVNIT WLSNGHSVIE
 GVSETSFLSK SDHSFFKISY LTFLPSADEI YDCRVEHWGL DEPLLKHWEP
 EIPVPMSELT ETVVCALGLS AGLVGIVVGT VLIIRGLRSV GASRHQGPLX
>DL;IPD:MHC01182
IPD:MHC01182 Mafa-DQA1*05:03:01 255 bases
 MILNKALMLA ALALTTVMSP CGGEEIVADH VASYGVNLYQ SYGFSGQYSH
 EFDGDEQFYV DLERKETVWQ LPVLSQFSFD AQFALTNIAV GKQNLNYLMK
 QSNSTAATNE VPEVTVFSKS PVTLGHPNTL ICLVDNIFPP VVNITWLSNG
 HSVTEGVSET SFLSKSDHSF FKISYLTFLA SADEIYDCKV EHWGLDEPLL
 KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR GLRSVGASRH
 QGPLX*    
>DL;IPD:MHC03769
IPD:MHC03769 Mafa-DQA1*05:03:02 255 bases
 MILNKALMLA ALALTTVMSP CGGEEIVADH VASYGVNLYQ SYGFSGQYSH
 EFDGDEQFYV DLERKETVWQ LPVLSQFSFD AQFALTNIAV GKQNLNYLMK
 QSNSTAATNE VPEVTVFSKS PVTLGHPNTL ICLVDNIFPP VVNITWLSNG
 HSVTEGVSET SFLSKSDHSF FKISYLTFLA SADEIYDCKV EHWGLDEPLL
 KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR GLRSVGASRH
 QGPLX*    
>DL;IPD:MHC01183
IPD:MHC01183 Mafa-DQA1*05:04 255 bases
 MILNKALMLG ALALTTVMSS CGGEDIVADH LASYGVNFYQ SYGLSGQYSH
 EFDGDEQFYV DLGRKETVWR LPIPYRYGFD PQFALRNIAV LTHNLNVLIK
 RSNSTAATNE VPEVTVFSKS PVTLGHPNTL ICLVDHIFPP VVNITWLSNG
 RSVTEGVSET SFLSKSDHSF FKISYLTFLP SADEIYDCRV EHWGLDEPLL
 KHWEPEIPAP MSELTETVVC ALGLSAGLVG IVVGTILIIR GLRSVGASRH
 QGPLX*    
>DL;IPD:MHC03766
IPD:MHC03766 Mafa-DQA1*05:05:01 255 bases
 MILNKALMLG ALVLTTVMSP CGGEDIVADH VASYGVNVYQ SYGLSGQYSH
 EFDGDEQFYV DLGRKETVWR LPILSQFSFD PQFALRNIAV LTHNLNILIK
 RSNSTAATNE VPEVTVFSKS PVTLGHPNTL ICLVDNIFPP VVNITWLSNG
 HSVTEGVSET SFLSKSDHSF FKISYLTFLP SADEIYDCRV EHWGLDEPLL
 KHWEPEIPAP MSELTETVVC ALGLSAGLVG IVVGTVLIIR GLRSVGASRH
 QGPLX*    
>DL;IPD:MHC04705
IPD:MHC04705 Mafa-DQA1*05:05:02 228 bases
 GGEDIVADHV ASYGVNVYQS YGLSGQYSHE FDGDEQFYVD LGRKETVWRL
 PILSQFSFDP QFALRNIAVL THNLNILIKR SNSTAATNEV PEVTVFSKSP
 VTLGHPNTLI CLVDNIFPPV VNITWLSNGH SVTEGVSETS FLSKSDHSFF
 KISYLTFLPS ADEIYDCRVE HWGLDEPLLK HWEPEIPAPM SELTETVVCA
 LGLSAGLVGI VVGTVLIIRG LRSVGASR*  
>DL;IPD:MHC03768
IPD:MHC03768 Mafa-DQA1*05:06 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNVYQ SYGPSGQYSH
 EFDGDEQFYV DLGRKETVWR LPIPYRYGFD PQFALRNIAV LTHNLNILIK
 RSNSTAATNE VPEVTVFSKS PVMLGQPNTL ICLVDNIFPP VVNITWLSNG
 HSVIEGVSET SFLSKSDHSF FKISYLTFLP SADEIYDCRV EHWGLDEPLL
 KHWEPEIPVP MSELTETVVC ALGLSAGLVG IVVGTVLIIR GLRSVGASRH
 QGPLX*    
>DL;IPD:MHC04125
IPD:MHC04125 Mafa-DQA1*05:07:01 255 bases
 MILNKALMLG ALALTTMMRP CGGEDIVADH VASYGVNVYQ SYGLSGQYSH
 EFDGDEQFYV DLGRKETVWR LPILSQFSFD PQFALRNIAV LTHNLNSLIK
 RSNSTAATNE VPEVTVFSKS PVTLGHPNTL ICLVDNIFPP VVNITWLSNG
 HSVTEGVSET SFLSKSDHSF FKISYLTFLP SADEIYDCRV EHWGLDEPLL
 KHWEPEIPAP MSELTETVVC ALGLSAGLVG IVVGTVLIIR GLRSVGASRH
 QGPLX*    
>DL;IPD:MHC04707
IPD:MHC04707 Mafa-DQA1*05:07:02 228 bases
 GGEDIVADHV ASYGVNVYQS YGLSGQYSHE FDGDEQFYVD LGRKETVWRL
 PILSQFSFDP QFALRNIAVL THNLNSLIKR SNSTAATNEV PEVTVFSKSP
 VTLGHPNTLI CLVDNIFPPV VNITWLSNGH SVTEGVSETS FLSKSDHSFF
 KISYLTFLPS ADEIYDCRVE HWGLDEPLLK HWEPEIPAPM SELTETVVCA
 LGLSAGLVGI VVGTVLIIRG LRSVGASR*  
>DL;IPD:MHC04129
IPD:MHC04129 Mafa-DQA1*05:08 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNVYQ SYGPSGQYSH
 EFDGDEQFYV DLGRKETVWR LPIPYRYGFD PQFALRNIAV LTHNLNILIK
 RSNSTAATNE VPEVTVFSKS PVMLGQPNTL ICLVDNIFPP VVNITWLSNG
 HSVIEGVSET SFLSKSDHSF FKISYLTFLP SADEIYDCRV EHWGLDEPLL
 KHWEPEIPVP MSELTETVVC ALGLSAGLVG IVVGTVLIIR GLRSVGASRH
 QGPLX*    
>DL;IPD:MHC04130
IPD:MHC04130 Mafa-DQA1*05:09 255 bases
 MILNKALLLG ALTLTTVMSP CGGEDIVADH VASYGVNVYQ SYGPSGQYSH
 EFDGDEQFYV DLGRKETVWR LPIPYRYGFD PQFALRNIAV LTHNLNILIK
 RSNSTAATNE VPEVTVFSKS PVMLGQPNTL ICLVDNIFPP VVNITWLSNG
 HSVIEGVSET SFLSKSDHSF FKISYLTFLP SADEIYDCRV EHWGLDEPLL
 KHWEPEIPVP MSELTETVVC ALGLSAGLVG IVVGTVLIIR GLRSVGASRH
 QGPLX*    
>DL;IPD:MHC01184
IPD:MHC01184 Mafa-DQA1*23:01 256 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNMYQ SYGPSGQYTH
 EFDGDEEFYV DLERKQTVWQ LPLFSKFRRF DPQGALRNIA VLQHNLNIVI
 KRSNSTAATN EVPEVTVFSK SPVMLGQPNT LICLVDNIFP PVVNITWLSN
 GHSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCK VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII RGLRSIGASR
 HQGPLX*    
>DL;IPD:MHC00276
IPD:MHC00276 Mafa-DQA1*24:01 63 bases
 SYGPSGQYTH EFDGDEEFYV DLERKETIWQ LPLFSKFRSF DPQGALRNLA
 VGKHNLNILI KLS*   
>DL;IPD:MHC01185
IPD:MHC01185 Mafa-DQA1*24:02:01 256 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH
 EFDGDEEFYV DLERKETVWQ LPLFSKFRSF DPQGALRNLA VSKHNLNILI
 KHSNSTAATN EVPEVTVFSK SPVTLGHPNT LICLVDNIFP PVVNITWLSN
 GRSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCK VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CTLGLSMGLV GIVVGTVLII RGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC01186
IPD:MHC01186 Mafa-DQA1*24:02:02 256 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH
 EFDGDEEFYV DLERKETVWQ LPLFSKFRSF DPQGALRNLA VSKHNLNILI
 KHSNSTAATN EVPEVTVFSK SPVTLGHPNT LICLVDNIFP PVVNITWLSN
 GRSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCK VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CTLGLSMGLV GIVVGTVLII RGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC04435
IPD:MHC04435 Mafa-DQA1*24:02:03 256 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH
 EFDGDEEFYV DLERKETVWQ LPLFSKFRSF DPQGALRNLA VSKHNLNILI
 KHSNSTAATN EVPEVTVFSK SPVTLGHPNT LICLVDNIFP PVVNITWLSN
 GRSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCK VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CTLGLSMGLV GIVVGTVLII RGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC05134
IPD:MHC05134 Mafa-DQA1*24:02:04 256 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH
 EFDGDEEFYV DLERKETVWQ LPLFSKFRSF DPQGALRNLA VSKHNLNILI
 KHSNSTAATN EVPEVTVFSK SPVTLGHPNT LICLVDNIFP PVVNITWLSN
 GRSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCK VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CTLGLSMGLV GIVVGTVLII RGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC01619
IPD:MHC01619 Mafa-DQA1*24:03 256 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNMYQ SYGPSGQYTH
 EFDGDEEFYV DLERKETVWQ LPLFSKFRSF DPQGALRNLA VGKHNLNILI
 KRSNSTAATN EVPEVTVFSK SPVTLGHPNT LICLVDNIFP PVVNITWLSN
 GRSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCK VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSMGLV GIVVGTVLII RGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC03770
IPD:MHC03770 Mafa-DQA1*24:04 256 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNMYQ SYGPSGQYTH
 EFDGDEEFYV DLERKETVWQ LPLFSKFRSF DPQGALRNLA VGKHNLNILI
 KRSNSTVATN EVPEVTVFSK SPVTLGHPNT LICLVDNIFP PVVNITWLSN
 GRSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCK VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSMGLV GIVVGTVLII RGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC03771
IPD:MHC03771 Mafa-DQA1*24:05 256 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQFTH
 EFDGDEEFYV DLERKETVWQ LPLFSKFRSF DPQGALRNLA VGKHNLNILI
 KRSNSTAATN EVPEVTVFSK SPVTLGHPNT LICLVDNIFP PVVNITWLSN
 GHSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCK VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSMGLV GIVVGTVLII RGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC04371
IPD:MHC04371 Mafa-DQA1*24:06 256 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH
 EFDGDEEFYV DLERKETVWQ LPLFSKFRSF DPQGALRNLA VGKHNLNILI
 KHSNSTAATN EVPEVTVFSK SPVTLGHPST LICLVDNIFP PVVNITWLSN
 GRSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCK VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSMGLV GIVVGTVLII RGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC04709
IPD:MHC04709 Mafa-DQA1*24:07 229 bases
 GGEDIVADHV ASYGVNLYQS YGPSGQYTHE FDGDEEFYVD LERKETVWQL
 PLFSKFRSFD PQGALRNLAV SKHNLNILIK HSNSTAATNE VPEVTVFSKS
 PVTLGHPNTL ICLVDNIFPP VVNITWLSNG RSVTEGVSET SFLSKSDHSF
 FKISYLTFLP SADEIYDCKV EHWGLDEPLL KHWEPEIPAP MSELTETVVC
 ALGLSMGLVG IVVGTVLIIR GLRSVGASR*  
>DL;IPD:MHC04711
IPD:MHC04711 Mafa-DQA1*24:08 229 bases
 GGEDIVADHV ASYGVNLYQS YGPSGQYTHE FDGDEEFYVD LERKETVWQL
 PLFSKFRSFD PQGALRNLAV GKHNLNILIK RSNSTAATNE VPEVTVFSKS
 PVTLGHPNTL ICLVDNIFPP VVNITWLSNG RSVTEGVSET SFLSKSDHSF
 FKISYLTFLP SADEIYDCKV EHWGLDEPLL KHWEPEIPAP MSELTETVVC
 ALGLSMGLVG IVVGTVLIIR GLRSVGASR*  
>DL;IPD:MHC04713
IPD:MHC04713 Mafa-DQA1*24:09 229 bases
 GGEDIVADHV ASYGVNLYQS YGPSGQFTHE FDGDEEFYVD LERKETVWQL
 PLFSKFRSFD PQGALRNLAV SKHNLNILIK HSNSTAATNE VPEVTVFSKS
 PVTLGHPNTL ICLVDNIFPP VVNITWLSNG RSVTEGVSET SFLSKSDHSF
 FKISYLTFLP SADEIYDCKV EHWGLDEPLL KHWEPEIPAP MSELTETVVC
 TLGLSMGLVG IVVGTVLIIR GLRSVGASR*  
>DL;IPD:MHC04702
IPD:MHC04702 Mafa-DQA1*26:01 229 bases
 GGEDIVADHI ASYGVNLYQT YGLSGQFTHE FDGDEQFYVD LERKETVWRL
 PLFSKFGGFD PQGALRNLAV GKHNLNILIK HSNSTAATNE VPEVTVFSKS
 PVTLGHPNTL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF
 FKISYLTFLP SADEIYDCRV EHWGLDEPLL KHWEPEIPAP MSELTETVVC
 ALGLSMGLVG IVVGTVLIIR GLRSVGASR*  
>DL;IPD:MHC00277
IPD:MHC00277 Mafa-DQA1*26:01:01 256 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH IASYGVNLYQ TYGLSGQFTH
 EFDGDEQFYV DLERKETVWR LPLFSKFGGF DPQGALRNLA VGKHNLNILI
 KHSNSTAATN EVPEVTVFSK SPVTLGHPNT LICLVDNIFP PVVNITWLSN
 GHSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCR VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSMGLV GIVVGTVLII RGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC04126
IPD:MHC04126 Mafa-DQA1*26:01:02 256 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH IASYGVNLYQ TYGLSGQFTH
 EFDGDEQFYV DLERKETVWR LPLFSKFGGF DPQGALRNLA VGKHNLNILI
 KHSNSTAATN EVPEVTVFSK SPVTLGHPNT LICLVDNIFP PVVNITWLSN
 GHSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCR VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSMGLV GIVVGTVLII RGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC04699
IPD:MHC04699 Mafa-DQA1*26:01:03 229 bases
 GGEDIVADHI ASYGVNLYQT YGLSGQFTHE FDGDEQFYVD LERKETVWRL
 PLFSKFGGFD PQGALRNLAV GKHNLNILIK HSNSTAATNE VPEVTVFSKS
 PVTLGHPNTL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF
 FKISYLTFLP SADEIYDCRV EHWGLDEPLL KHWEPEIPAP MSELTETVVC
 ALGLSMGLVG IVVGTVLIIR GLRSVGASR*  
>DL;IPD:MHC01187
IPD:MHC01187 Mafa-DQA1*26:02 256 bases
 MILNKALLLG ALTLTTVMSP CGGEDIVADH VASYGVNLYQ TYGLSGQFTH
 EFDGDEQFYV DLERKETVWR LPLFSKFGGF DPQGALRNLA VGKHNLNILI
 KHSNSTAATN EVPEVTVFSK SPVTLGHPNT LICLVDNIFP PVVNITWLSN
 GHSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCR VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSMGLV GIVVGTVLII RGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC02064
IPD:MHC02064 Mafa-DQA1*26:03 256 bases
 MILNKALLLG ALALTTVMSP CGGEDIMADH VASYGVNLYQ TYGLSGQYTH
 EFDGDEQFYV DLERKETVWR LPLFSKFGGF DPQGALRNLA VGKHNLNILI
 KHSNSTAATN EVPEVTVFSK SPVTLGHPNT LICLVDNIFP PVVNITWLSN
 GHSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCR VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSMGLV GIVVGTVLII RGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC03767
IPD:MHC03767 Mafa-DQA1*26:04:01 256 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ TYGLSGQYTH
 EFDGDEQFYV DLERKETVWR LPLFSKFGGF DPQGALRNLA VSKHNLNIMI
 KRSNSTAATN EVPEVTVFSK SPVTLGHPNT LICLVDNIFP PVVNITWLSS
 GRSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCK VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVLII RGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC04712
IPD:MHC04712 Mafa-DQA1*26:04:02 229 bases
 GGEDIVADHV ASYGVNLYQT YGLSGQYTHE FDGDEQFYVD LERKETVWRL
 PLFSKFGGFD PQGALRNLAV SKHNLNIMIK RSNSTAATNE VPEVTVFSKS
 PVTLGHPNTL ICLVDNIFPP VVNITWLSSG RSVTEGVSET SFLSKSDHSF
 FKISYLTFLP SADEIYDCKV EHWGLDEPLL KHWEPEIPAP MSELTETVVC
 ALGLSVGLVG IVVGTVLIIR GLRSVGASR*  
>DL;IPD:MHC03774
IPD:MHC03774 Mafa-DQA1*26:05 256 bases
 MILNKALLLG ALTLTTVMSP CGGEDIVADH VASYGVNLYQ TYGLSGQYTH
 EFDGDEQFYV DLERKETVWR LPLFSKFGGF DPQGALRNLA VSKHNLNIMI
 KRSNSTAATN EVPEVTVFSK SPVTLGHPNT LICLVDNIFP PVVNITWLSS
 GHSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCK VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVLII RGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC03814
IPD:MHC03814 Mafa-DQA1*26:06 256 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH IASYGVNLYQ TYGLSGQFTH
 EFDGDEQFYV DLERKETVWR LPLFSKFGGF DPQGALRNLA VGKHNLNILI
 KHSNSTAATN EVPEVTVFSK SPMTLGHPNT LICLVDNIFP PVVNITWLSN
 GHSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCK VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVLII RGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC04706
IPD:MHC04706 Mafa-DQA1*26:07 229 bases
 GGEDIVADHV ASYGVNLYQT YGLSGQYTHE FDGDEQFYVD LERKETVWRL
 PLFSKFGGFD PQGALRNLAV SKHNLNIMIK RSNSTAATNE VPEVTVFSKS
 PVTLGHPNTL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF
 FKISYLTFLP SADEIYDCKV EHWGLDEPLL KHWEPEIPAP MSELTETVVC
 ALGLSVGLVG IVVGTVLIIR GLRSVGASR*  
