>DL;IPD:MHC00278
IPD:MHC00278 Mafa-DQB1*06:01:01 262 bases
 MSWKKALRIP GGLRAATVTL MLAMLSTPVA EGRDAPEDFV YQFKAMCYFT
 NWTERVRYVT RYIYNREEFV RFDSAVGEYR AVTPQGRLDA EYWNSQKDVL
 ESTRAELDTV CKHNYEVAFR GILQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNNQEE TVGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK LLSGIGGLVL GLIFFGLGLI
 IRQRSQKGLP HX*   
>DL;IPD:MHC01623
IPD:MHC01623 Mafa-DQB1*06:01:02 262 bases
 MSWKKALRIP GGLRAATVTL MLAMLSTPVA EGRDAPEDFV YQFKAMCYFT
 NWTERVRYVT RYIYNREEFV RFDSAVGEYR AVTPQGRLDA EYWNSQKDVL
 ESTRAELDTV CKHNYEVAFR GILQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNNQEE TVGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK LLSGIGGLVL GLIFFGLGLI
 IRQRSQKGLP HX*   
>DL;IPD:MHC00279
IPD:MHC00279 Mafa-DQB1*06:02 82 bases
 YQFKAMCYFT NWTERVRYVT RYIYNREEFV RFDSAVGEYR AVTPQGRLDA
 EYWNSQKDIL ERTRAELDTV CMHNYEVAYR GI* 
>DL;IPD:MHC00280
IPD:MHC00280 Mafa-DQB1*06:03 82 bases
 YQFKGMCYFT NGTERVRGVT RYIYNREEYV RFDSDVGVYR AVTPQGRPDA
 EYWNSQKDIL ERTRAELDTV CRHNYEVAYR GI* 
>DL;IPD:MHC00281
IPD:MHC00281 Mafa-DQB1*06:04 82 bases
 YQFKGLCYFT NGTERVRSVT RYIYNREEYA RFDSDWGEYR AVTPQGRPDA
 EYWNSQKDIL ERTRAELDTV CIHNYEVAYR GI* 
>DL;IPD:MHC00282
IPD:MHC00282 Mafa-DQB1*06:06 82 bases
 YQFKGLCYFT NGTERVRSVN RYIYNREEYA RFDSDWGEYR AVTPQGRPDA
 EYWNSQKDIL ERTRAELDTV CMHNYEVAYR GI* 
>DL;IPD:MHC00283
IPD:MHC00283 Mafa-DQB1*06:07:01 262 bases
 MSWKKALRIP GGLRVATVTL MLAMLSTPVA EGRDSPEDFV YQFKGLCYFT
 NGTERVRSVT RHIYNREEYV RFDSDWGEYR AVTPQGRPDA EYWNSQKDIL
 ESTRAELDTV CMHNYEVAYR GILQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNNQEE TVGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGIGGLVL GLIFFGLGLI
 IRQRSQKGLL HX*   
>DL;IPD:MHC03520
IPD:MHC03520 Mafa-DQB1*06:07:02 89 bases
 DFVYQFKGLC YFTNGTERVR SVTRHIYNRE EYVRFDSDWG EYRAVTPQGR
 PDAEYWNSQK DILESTRAEL DTVCMHNYEV AYRGILQRR* 
>DL;IPD:MHC00284
IPD:MHC00284 Mafa-DQB1*06:08 262 bases
 MSWKKALRIP GGLRVATVTL MLAMLSTPVT EGRDSPEDFV YQFKGMCYFT
 NGTERVRHVT RYIYNREEYA RFDSDWGEYR AVTPQGRPSA EYWNSQKDIL
 ESTRAELDTV CKHNYEVAFR GILQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNNQEE TVGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK LLSGIGGLVL GLIFFGLGLI
 IRQRSQKGLP RX*   
>DL;IPD:MHC00285
IPD:MHC00285 Mafa-DQB1*06:09 82 bases
 YQFKGMCYFT NGKERVRLVT RHIYNREEYV RFDSDWGEYR AVTPQGRSWA
 KYWNSQKDFL ESTRAELDTV CKHNYEVAYR GI* 
>DL;IPD:MHC00286
IPD:MHC00286 Mafa-DQB1*06:10 89 bases
 DFVYQFKGLC YFTNGTERVR SVNRYIYNRE EYARFDSDWG EYRAVTPQGR
 PDAEYWNSQK DILERTRAEL DTVCMHNYEV AYRGILQRR* 
>DL;IPD:MHC00287
IPD:MHC00287 Mafa-DQB1*06:11 262 bases
 MSWKKALRIP SGLRVATVTL MLAMLSTPVA EGRDSPEDFV FQFKGLCYFT
 NGTERVRLVT RYIYNREEFL RFDSAVGEYR AVTPQGRSDA EHLNSQKDVL
 ERTRAELDTV CMHNYEVAYR GILQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNNQEE TVGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGIGGFVL GLIFFGLGLI
 IRQRSQKGLL HX*   
>DL;IPD:MHC00288
IPD:MHC00288 Mafa-DQB1*06:12 82 bases
 HQFKGMCYFT NGTERVRHVT RYIYNREEYV RFDSDVGEYR AVTPQGRPDA
 EYWNSQKDIL ERTRAELDTV CKHNYEVAFR GI* 
>DL;IPD:MHC00289
IPD:MHC00289 Mafa-DQB1*06:13 262 bases
 MSWKKALRIP SGLRVATVTL MLAMLSTPVA EGRDSPEDFV FQFKGLCYFT
 NGTERVRHVT RYIYNREEFL RFDSAVGEYR AVTPQGRSDA EHLNSQKDVL
 ESTRAELDTV CMHNYEVTYR GILQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNNQEE TVGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGIGGFVL GLIFFGLGLI
 IRQRSQKGLL HX*   
>DL;IPD:MHC00290
IPD:MHC00290 Mafa-DQB1*06:14 262 bases
 MSWKKALRIP GGLRVATVTL MLAMLSTPVT EGRDSPEDFV YQFKGMCYFT
 NGTERVRHVT RYIYNREEYA RFDSDWGEYR AVTPQGRPDA EYWNSQKDIL
 ESTRAELDTV CKHNYEVAFR GILQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNNQEE TVGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK LLSGIGGLVL GLIFFGLGLI
 IRQRSQKGLP RX*   
>DL;IPD:MHC01188
IPD:MHC01188 Mafa-DQB1*06:15 262 bases
 MSWKKALRIP GGLRVATVTL MLAMLSTPVA EGRDSPEDFV YQFKGLCYFT
 NGTERVRLVT RHVYNREEYV RFDSDWGEYR AVTPQGRPDA EYWNSQKDIL
 ESTRAELDTV CMHNYEVAYR GILQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNNQEE TVGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGIGGLVL GLIFFGLGLI
 IRQRSQKGLL HX*   
>DL;IPD:MHC03518
IPD:MHC03518 Mafa-DQB1*06:16 262 bases
 MSWKKALRIP GGLRAATVTL MLAMLSTPVA EGRDAPEDFV YQFKGLCYFT
 NGTERVRGVT RYIYNREEYA RFDSDWGEYR AVTPQGRPAA EYWNSQKDIL
 ERTRAELDTV CIHNYEVAYR GILQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNNQEE TVGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGIGGFVL GLIFFGLGLI
 IRQRSQKGLL HX*   
>DL;IPD:MHC03519
IPD:MHC03519 Mafa-DQB1*06:17:01 262 bases
 MSWKKALRIP GGLRAATVTL MLAMLSTPVA EGRDSPEDFV YQFKGLCYFT
 NGKERVRLVT RHIYNREEYV RFDSDWGEYR AVTPQGRSWA KYWNSQKDFL
 ESTRAELDTV CKHNYEVAYR GILQRRVEPT VTISLSRTEA LDHHNLLVCS
 VTDFYPGQIK VRWFRNDQEE TTGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DIYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGIGGFVL GLIFLGLGLI
 IRQRSQKGLL HX*   
>DL;IPD:MHC03521
IPD:MHC03521 Mafa-DQB1*06:18 262 bases
 MSWKKALRIP GGLRVATVTL MLAMLSTPVA EGRDSPEDFV YQFKGLCYFT
 NGTERVRSVT RHIYNREEYV RFDSDWGEYR AVTPQGRPDA EYWNSQKDIL
 ESTRAELDTV CMHNYEVVYR GILQRRVEPT VTISLSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNNQEE TVGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGIGGLVL GLIFFGLGLI
 IRQRSQKGLL HX*   
>DL;IPD:MHC03522
IPD:MHC03522 Mafa-DQB1*06:19 262 bases
 MSWKKALRIP GGLRVATVTL MLAMLSTPVA EGRDSPEDFV YQFKGLCYFT
 NGTERVRSVT RHIYNREEYV RFDSDWGEYR AVTPQGRPDA EYWNSQKDIL
 ESTRAELDTV CKHNYEVAYR GILQRRVEPT VTISLSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNNQEE TVGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGIGGLVL GLIFFGLGLI
 IRQRSQKGLL HX*   
>DL;IPD:MHC03523
IPD:MHC03523 Mafa-DQB1*06:20 84 bases
 YQFKGLCYFT NGTERVRSVT RHIYNREEYV RFDSDWGEYR AVTPQGRPSA
 EYWNSQKDIL ESTRAELDTV CMHNYEVAYR GILQ* 
>DL;IPD:MHC03524
IPD:MHC03524 Mafa-DQB1*06:21 84 bases
 YQFKGLCYFT NGTERVRSVT RYIYNREEYV RFDSDWGEYR AVTPQGRPAA
 EYWNSQKDIL ERTRAELDTV CIHNYEVVYR GILQ* 
>DL;IPD:MHC03525
IPD:MHC03525 Mafa-DQB1*06:22 89 bases
 DFVYQFKGLC YFTNGKERVR LVTRYIYNRE EYVRFDSDWG EYRAVTPQGR
 SWAKYWNSQK DFLESTRAEL DTVCKHNYEV AFRGILQRR* 
>DL;IPD:MHC03526
IPD:MHC03526 Mafa-DQB1*06:23 262 bases
 MSWKKALRIP DGLRAATVTL MLAMLSTPVA EGRDAPEDFV VQFKGLCYYT
 NGTERVRGVT RYIYNREEYA RFDSDWGEYR AVTPQGRPDA EYWNSQKDIL
 ERTRAELDTV CIHNYEVVYR GILQRRVEPT VTISLSRTEA LNHHNLLVCS
 VTDFYPGQVK VRWFRNNQEE TVGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SVQSPITVEW RAQSESAQSK MLSGIGGFVL GLIFFGLGLI
 IRQRSQKGLL HX*   
>DL;IPD:MHC03527
IPD:MHC03527 Mafa-DQB1*06:24 83 bases
 VQFKGLCYYT NGTERVRLVT RYIYNREEYA RFDSDWGEYR AVTPQGRPAA
 EYWNSQKDIL ERTRAELDTV CIHNYEVVYR GIL* 
>DL;IPD:MHC03528
IPD:MHC03528 Mafa-DQB1*06:25 84 bases
 YQFKAMCYFT NGTERVRYVT RYIYNREEYV RFDSAVGEHR AVTPQGRPDA
 EYWNSQKDIL ERTRAELDTV CKHNYEVAFR GILQ* 
>DL;IPD:MHC03529
IPD:MHC03529 Mafa-DQB1*06:26 262 bases
 MSWKKALRIP GGLRVATVTL MLAMLSTPVA EGRDSPEDFV YQFKGLCYFT
 NGTERVRLVS RYIYNREEYV RFDSDVGEYR AVTPQGRPDA EYWNSQKDIL
 ESKRAELDTV CKHNYEVAYR GILQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNNQEE TVGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVQW RAQSESAQSK LLSGIGGLVL GLIFFGLGLI
 IRQRSQKGLP HX*   
>DL;IPD:MHC03698
IPD:MHC03698 Mafa-DQB1*06:27 89 bases
 DFVVQFKGLC YFTNGTERVR LVSRFIYNRE EYARFDSDVG EYRAVTPQGR
 PDAEYWNSQK DILESTRAEL DTVCRHNYEV AYRGILQRR* 
>DL;IPD:MHC03699
IPD:MHC03699 Mafa-DQB1*06:28 89 bases
 DFVHQFKAMC YFTNGTERVR YVTRYIYNRE EYVRFDSAVG EHRAVTPQGR
 PDAEYWNSQK DILERTRAEL DTVCKHNYEV AFRGILQRR* 
>DL;IPD:MHC03700
IPD:MHC03700 Mafa-DQB1*06:29 89 bases
 DFVYQFKGMC YFTNGTERVR HVTRYIYNRE EYARFDSDWG EYRAVTPQGR
 PAAEYWNSQK DILERTRAEL DTVCIHNYEV AYRGILQRR* 
>DL;IPD:MHC03701
IPD:MHC03701 Mafa-DQB1*06:30 89 bases
 DFVYQFKGMC YFTNGTERVR HVTRYIYNRE EYARFDSDWG EYRAVTPQGR
 PAAEYWNSQK DILERTRAEL DTVCKHNYEV AYRGILQRR* 
>DL;IPD:MHC03777
IPD:MHC03777 Mafa-DQB1*06:31 262 bases
 MSWKKALRIP GGLRVATVTL MLAMLSTPVT EGRDSPEDFV YQFKGMCYFT
 NGTERVRHVT RYIYNREEYA RFDSDWGEYR AVTPQGRPAA EYWNSQKDIL
 ERTRAELDTV CKHNYQVAYR GILQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNNQEE TVGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK LLSGIGGLVL GLIFFGLGLI
 IRQRSQKGLP RX*   
>DL;IPD:MHC03779
IPD:MHC03779 Mafa-DQB1*06:32 262 bases
 MSWKKALRIP GGLRVATVTL MLAMLSTPVT EGRDSPEDFV YQFKGMCYFT
 NRTERVRHVT RYIYNREEYA RFDSDWGEYR AVTPQGRPDA EYWNSQKDIL
 ESTRAELDTV CKHNYEVAFR GILQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNNQEE TVGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK LLSGIGGLVL GLIFFGLGLI
 IRQRSQKGLP RX*   
>DL;IPD:MHC03888
IPD:MHC03888 Mafa-DQB1*06:33 84 bases
 FQFKGLCYFT NGTERVRHVT RYIYNREEFL RFDSAVGEYR AVTPQGRSDA
 EHLNSQKDVL ERTRAELDTV CMHNYEVTYR GILQ* 
>DL;IPD:MHC03889
IPD:MHC03889 Mafa-DQB1*06:34 84 bases
 YQFKAMCYFT NWTERVRYVT RYIYNREEFV RFDSAVGEYR AVTPQGRLDA
 EYWNSQKDIL ESTRAELDTV CKHNYEVAFR GILQ* 
>DL;IPD:MHC04715
IPD:MHC04715 Mafa-DQB1*06:35 262 bases
 MSWKKALRIP GGLRVATVTL MLAMLSTPVT EGRDSPEDFV YQFKGLCYFT
 NGTERVRSVN RYIYNREEFV RFDSDWGEYR AVTPQGRPDA EYWNSQKDIL
 ERTRAELDTV CMHNYEVAYR GILQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNNQEE TVGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK LLSGIGGLVL GLIFFGLGLI
 IRQRSQKGLP HX*   
>DL;IPD:MHC05121
IPD:MHC05121 Mafa-DQB1*06:36 262 bases
 MSWKKALRIP GGLRAATVTL MLAMLSTPVA DCRDAPEDFV HQFKGLCYFT
 NGTERVRLVT RYIYNREEYA RFDSDWGEYR AVTPQGRPDA EYWNSQKDVL
 ESTRAELDTV CKHNYEVAFR GILQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNNQEE TVGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGIGGFVL GLIFFGLGLI
 IRQRSQKGLL HX*   
>DL;IPD:MHC00291
IPD:MHC00291 Mafa-DQB1*15:01 89 bases
 DFVFQFKGMC YFTNGTERVW SVDRYIYNRE EYVRFDSDVG LYLPVTPLGR
 SSAEYWNSQK EALESKRAEL DTVCIHNYQL ELGTTLQRR* 
>DL;IPD:MHC00292
IPD:MHC00292 Mafa-DQB1*15:02 82 bases
 FQFKGMCYFT NGTERVWSVD RYIYNREEFV RFDSDVGLYL PVTPLGRSSA
 EYWNSQKEAL ESKRAELDTV CIHNYQLELG TT* 
>DL;IPD:MHC00293
IPD:MHC00293 Mafa-DQB1*15:03 262 bases
 MSWKKALRIP GGLRAATVTL MLAMLSTPVA ECRDSPEDFV FQFKGMCYFT
 NGTERVWSVD RYIYNREEYV RFDSDVGLYL PVTPLGRSSA EYMNSQKEAL
 ESKRAELDTV CIHNYQLELG TTLQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNDQEE TTGIVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGIGGFVL GMIFLGLGLI
 IHHRSQKGLL HX*   
>DL;IPD:MHC03778
IPD:MHC03778 Mafa-DQB1*15:04 262 bases
 MSWKKALRIP GGLRAATVTL MLALLSTPVA ECRDSPENFV YQFKGLCYFT
 NGTERVWSVD RYIYNREEYV RFDSDVGLYL PVTPLGRSSA EYWNSQKEAL
 ESKRAELDTV CIHNYQLELR TTLQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNDQEE TAGIVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK MMSGIGGFVL GLIFLGLGLI
 IHYRSQKGLP HX*   
>DL;IPD:MHC00294
IPD:MHC00294 Mafa-DQB1*16:01 262 bases
 MSWKKALQIP GGLWAATVTL MLAMLSTPVT EGRDSPEDFV YQFKGMCYFT
 NGTERVRLVA RHVYNREEFA RFDSDVGVYR EVTPMGQSWA EYWNSQKEVL
 ERKRAELDTV CRHNYQLELL STLQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNDQEE TTGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPIAVEW RVQSESAQSK MLSGIGGFVL GLIFLGLGLI
 IHHRNQKGLL HX*   
>DL;IPD:MHC03447
IPD:MHC03447 Mafa-DQB1*16:02 89 bases
 DFVHQFKFMC YFVNGTERVR AIARHVYNRE EFARFDSDVG VYRAVTPLGR
 SSAEYWNSQK EVLERKRAEL DTVCRHNYQL ELRSTLQRR* 
>DL;IPD:MHC03697
IPD:MHC03697 Mafa-DQB1*16:03 89 bases
 DFVHQFKFMC YFVNGTERVR AIARHVYNRE EFARFDSDVG VYRAVTPLGR
 SSAEYWNNQK EVLERKRAEL DTVCRHNYQL ELRSTLQRR* 
>DL;IPD:MHC00295
IPD:MHC00295 Mafa-DQB1*17:01 82 bases
 YQFKAMCYFT NGTERVHCVT RYIYNREEYA RFDSDVGKYL PVTPLGPPDA
 EYWNSQKDFL ESTRAELDTV CRHNYQLELR TI* 
>DL;IPD:MHC00296
IPD:MHC00296 Mafa-DQB1*17:02:01 262 bases
 MPPKKALRIP GGLWGTTVTL MLAMLSTPVA EGRDSPEDFV YQFKAMCYFT
 NGTERVHYVT RYIYNREEYA RFDSDVGKYL PVTPLGPPDA EYWNSQKDVL
 ESTRAELDTV CRHNYQLELR TILQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNDQEE TTGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQRPITVEW RAQSESAQSK MLSGVGGFVL GLIFLGLGLI
 IHHRSQKGLL HX*   
>DL;IPD:MHC04132
IPD:MHC04132 Mafa-DQB1*17:02:02 262 bases
 MPPKKALRIP GGLWGTTVTL MLAMLSTPVA EGRDSPEDFV YQFKAMCYFT
 NGTERVHYVT RYIYNREEYA RFDSDVGKYL PVTPLGPPDA EYWNSQKDVL
 ESTRAELDTV CRHNYQLELR TILQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNDQEE TTGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQRPITVEW RAQSESAQSK MLSGVGGFVL GLIFLGLGLI
 IHHRSQKGLL HX*   
>DL;IPD:MHC00297
IPD:MHC00297 Mafa-DQB1*17:03 262 bases
 MPPKKALRIP GGLWGTTVTL MLAMLSTPVA EGRDSPEDFV YQFKAMCYFT
 NGTERVHYVT RYIYNREEYA RFDSDVGKYL PVTPLGPPDA EYWNSQKDFL
 ESTRAELDTV CRHNYQLELR TILQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNDQEE TTGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQRPITVEW RAQSESAQSK MLSGVGGFVL GLIFLGLGLI
 IHHRSQKGLL HX*   
>DL;IPD:MHC00298
IPD:MHC00298 Mafa-DQB1*17:04 262 bases
 MPPKKALRIP GGLWGTTVTL MLAMLSTPVA EGRDSPEDFV YQFKAMCYFT
 NGTERVHYVT RYIYNREEYA RFDSDVGKYL PVTPLGPPAA EYWNSQKDVL
 ESTRAELDTV CRHNYQLELR TILQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNDQEE TTGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQRPITVEW RAQSESAQSK MLSGVGGFVL GLIFLGLGLI
 IHHRSQKGLL HX*   
>DL;IPD:MHC00299
IPD:MHC00299 Mafa-DQB1*17:05 262 bases
 MPRKKALWIP GGLWGTTGTL MLAMLSTPVA GGRDSPEDFV YQFKAMCYFT
 NGTERVHYVT RYIYNREEYA RFDSDVGKYL PVTPLGPPAA EYWNSQKDIL
 ERTRAELDTV CRHNYQLELH TTLQWRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VQWFRNDQEE TAGIVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RPQSESAQSK MLSGVGGFVL GLIFLGLGLI
 IHHRSQKGLL HX*   
>DL;IPD:MHC03445
IPD:MHC03445 Mafa-DQB1*17:06:01 84 bases
 YQFKAMCYFT NGTERVHYVT RYIYNREEYA RFDSDVGKYL PVTPLGPPAA
 EYWNSQKDVL ERTRAELDTV CRHNYQLELR TILQ* 
>DL;IPD:MHC03446
IPD:MHC03446 Mafa-DQB1*17:06:02 262 bases
 MPPKKALRIP GGLWGTTVTL MLAMLSTPVA EGRDSPEDFV YQFKAMCYFT
 NGTERVHYVT RYIYNREEYA RFDSDVGKYL PVTPLGPPAA EYWNSQKDVL
 ERTRAELDTV CRHNYQLELR TILQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNDQEE TTGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQRPITVEW RAQSESAQSK MLSGVGGFVL GLIFLGLGLI
 IHHRSQKGLL HX*   
>DL;IPD:MHC03438
IPD:MHC03438 Mafa-DQB1*17:07:01 262 bases
 MPRKKALRIP GGLWGTTVTL MLAMLSTPVA EGRDSPEDFV YQFKCLCYFT
 NGTERVHYVT RHIYNREEYV RFDSDWGEYR AVTPLGRPTA EYWNSQKDFL
 ESTRAELDTV CKHNYQLELL TTLQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNDQEE TAGIVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQRPITVEW RAQSESAQSK MLSGVGGFVL GLIFLGLGLI
 IHHRSQKGLL HX*   
>DL;IPD:MHC03513
IPD:MHC03513 Mafa-DQB1*17:07:02 84 bases
 YQFKCLCYFT NGTERVHYVT RHIYNREEYV RFDSDWGEYR AVTPLGRPTA
 EYWNSQKDFL ESTRAELDTV CKHNYQLELL TTLQ* 
>DL;IPD:MHC03516
IPD:MHC03516 Mafa-DQB1*17:08:01 84 bases
 YQFKGLCYFT NGTERVHYVT RHIYNREEYV RFDSDWGEYR AVTPLGRPTA
 EYWNSQKDFL ESTRAELDTV CKHNYQLELL TTLQ* 
>DL;IPD:MHC03661
IPD:MHC03661 Mafa-DQB1*17:08:02 89 bases
 DFVYQFKGLC YFTNGTERVH YVTRHIYNRE EYVRFDSDWG EYRAVTPLGR
 PTAEYWNSQK DFLESTRAEL DTVCKHNYQL ELLTTLQRQ* 
>DL;IPD:MHC03866
IPD:MHC03866 Mafa-DQB1*17:09 89 bases
 DFVYQFKCLC YFTNGTERVH YVTRHIYNRE EYVRFDNDWG EYRAVTPLGR
 PTAEYWNSQK DFLESTRAEL DTVCKHNYQL ELLTTLQRR* 
>DL;IPD:MHC00300
IPD:MHC00300 Mafa-DQB1*18:01:01 262 bases
 MPRKKALRIP GGLWGTTVTL MLAMLSTPVA EGRDSPEDFV VQFKGLCYFT
 NGTERVRHVT RYIYNREEYA RFDSDWGEYR AVTPLGRPDA EYWNSQKDIL
 ESTRAEADTV CRHNYQSELR TTLQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNDQQE TAGIVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGVGGFVL GLIFLGLGLI
 IHHRSQKGLP HX*   
>DL;IPD:MHC03444
IPD:MHC03444 Mafa-DQB1*18:01:02 84 bases
 VQFKGLCYFT NGTERVRHVT RYIYNREEYA RFDSDWGEYR AVTPLGRPDA
 EYWNSQKDIL ESTRAEADTV CRHNYQSELR TTLQ* 
>DL;IPD:MHC00301
IPD:MHC00301 Mafa-DQB1*18:02 89 bases
 DFVHQFKGLC YFTNGTERVR GVTRYIYNRE EYVRFDSDWG EYRAVTPQGQ
 SDAEYWNSQK DILERTRASV DTVCRHNYQL ELRTTLQRR* 
>DL;IPD:MHC00302
IPD:MHC00302 Mafa-DQB1*18:03 82 bases
 YQFKGLCYFT NGTERVRLVT RHVYNREEYV RFDSDWGEHR AVTPLGLPSA
 EYWNSQKDIL ERTRAELDTV CKHNYQSELR TT* 
>DL;IPD:MHC00303
IPD:MHC00303 Mafa-DQB1*18:04 262 bases
 MPRKKALRIP GGLWGTTVTL MLAMLSTPVA GGRDSPEDFV YQFKGLCYFT
 NGTERVRLVT RYIYNREEYV RFDSDWGEYR AVTPLGPPAA EYWNSQKDIL
 ERTRAELDTV CRHNYQSELR TTLQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNDQEE TAGIVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGVGGFVL GLIFLGLGLI
 IHYRSQKGLL HX*   
>DL;IPD:MHC00304
IPD:MHC00304 Mafa-DQB1*18:05 262 bases
 MPRKKALRIP GGLWGTTVTL MLAMLSTPVA EGRDSPEDFV VQFKGLCYFT
 NGTERVRSVN RYIYNREEYA RFDSDWGEYR AVTPLGRPDA EYWNSQKDIL
 ESTRAEADTV CRHNYQSELR TTLQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNDQQE TAGIVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGVGGFVL GLIFLGLGLI
 IHHRSQKGLP HX*   
>DL;IPD:MHC00305
IPD:MHC00305 Mafa-DQB1*18:06 262 bases
 MPRKKALRIP GGLWGTTVTL MLAMLSTPVA EGRDSPEDFV FQFKGLCYFT
 NGTERVRLVT RYVYNREEYV RFDSDWGEHR AVTPLGRSWA EYWNNQKDFL
 ETTRASVDTV CRHNYQLELR TTLQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPSQIK VKWFRNDQEE TTGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCRVEHP SLQSPITVEW RAQSESAQSK MLSGVGGFVL GLIFLGLGLI
 IHYRSQKGLL HX*   
>DL;IPD:MHC00306
IPD:MHC00306 Mafa-DQB1*18:07 262 bases
 MPRKKALRIP GGLWGTTVTL MLAMLSTPVA EGRDSPEDFV YQFKGLCYFI
 NGTERVRGVT RHIYNREEYV RFDSDWGEHR AVTPLGRSWA EYWNNQKDFL
 ETTRASVDTV CRHNYQLELR TTLQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPSQIK VKWFRNDQEE TTGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCRVEHP SLQSPITVEW RAQSESAQSK MLSGVGGFVL GLIFLGLGLI
 IHYRSQKGLP HX*   
>DL;IPD:MHC02065
IPD:MHC02065 Mafa-DQB1*18:07:02  bases
>DL;IPD:MHC00307
IPD:MHC00307 Mafa-DQB1*18:08 262 bases
 MSWKKALRIP GGLRAATVTL MLAMLSTPVA EGRDSPEDFV FQFKGMCYFI
 NGTEHVHHVN RYIYNREEFV GFDSYLGVYR PVTPLGRSWA EYWNSQKDIL
 ERTRAVVDTV CRHNYQSELR TTLQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNDQEE TTGIVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK MMSGIGGFVL GLIFLALGLI
 IHHRSQKGLL HX*   
>DL;IPD:MHC03439
IPD:MHC03439 Mafa-DQB1*18:09 262 bases
 MPWKKALRIP GGLLGATVTL MLAMLSTPVA EGRDSPEDFV YQFKGLCYFT
 NGTERVRLVT RYIYNREEYV RFDSDWGEYR AVTPLGPPDA EYWNSQKDIL
 ESTRAEADTV CRHNYQSELR TTLQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNDQEE TAGIVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGVGGFVL GLIFLGLGLI
 IHHRSQKGLL HX*   
>DL;IPD:MHC03440
IPD:MHC03440 Mafa-DQB1*18:10 89 bases
 DFVYQFKGLC YFTNGTERVR LVTRHISNRE EFVRFDSDWG EYRAVTPLGR
 PDAEYWNSQK DILERTRAEL DTVCRHNYQS ELRTTLQRR* 
>DL;IPD:MHC03441
IPD:MHC03441 Mafa-DQB1*18:11 84 bases
 YQFKGLCYFI NGTERVRGVT RYIYNREEYV RFDSDWGEHR AVTPLGRSWA
 EYWNNQKDFL ETTRASVDTV CRHNYQLELR TTLQ* 
>DL;IPD:MHC03442
IPD:MHC03442 Mafa-DQB1*18:12 84 bases
 HQFKGLCYFT NGTERVRSVT RYIYNREEYV RFDSDWGEYR AVTPQGQSDA
 EYWNSQKDIL ESTRAELDTV CIHNYQLELR TTLQ* 
>DL;IPD:MHC03443
IPD:MHC03443 Mafa-DQB1*18:13 262 bases
 MPWKKALRIP GGLLGATVTL MLAMLSTPVA EGRDSPEDFV HQFKGLCYFT
 NGTERVRSVT RYIYNREEYV RFDSDWGEYR AVTPQGQSDA EYWNSQKDIL
 ERTRAELDTV CIHNYQLELR TTLQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNDQEE TAGIVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQRPITVEW RAQSESAQSK MLSGVGGFVL GLIFLGLGLI
 IHHRSQKGLL HX*   
>DL;IPD:MHC03512
IPD:MHC03512 Mafa-DQB1*18:14 257 bases
 ALRIPGGLWG TTVTLMLAML STPVAGGRDS PEDFVYQFKG LCYFTNGTER
 VRLVTRYIYN REEYVRFDSD WGEYRAVTPL GPPDAEYWNS QKDILERTRA
 ELDTVCRHNY QSELRTTLQR RVEPTVTISP SRTEALNHHN LLVCSVTDFY
 PGQIKVRWFR NDQEETAGIV STPLIRNGDW TFQILVMLEM TPQRGDVYTC
 HVEHPSLQSP ITVEWRAQSE SAQSKMLSGV GGFVLGLIFL GLGLIIHYRS
 QKGLLHX*    
>DL;IPD:MHC03514
IPD:MHC03514 Mafa-DQB1*18:15 84 bases
 VQFKGLCYFT NGTERVRSVT RYIYNREEYA RFDSDWGEYR AVTPLGRPDA
 EYWNSQKDIL ESTRAEADTV CRHNYQSELR TTLQ* 
>DL;IPD:MHC03515
IPD:MHC03515 Mafa-DQB1*18:16 89 bases
 DFVFQFKGLC YFTNGTERVR HVTRYIYNRE EYARFDSDWG EYRAVTPLGR
 PDAEYWNSQK DILESTRAEA DTVCRHNYQS ELRTTLQRR* 
>DL;IPD:MHC03517
IPD:MHC03517 Mafa-DQB1*18:17 89 bases
 DFVYQFKGLC YFINGTERVR GVTRYIYNRE EFVRFDSDWG EHRAVTPLGR
 SWAEYWNSQK DFLETTRASV DTVCRHNYQS ELRTTLQRR* 
>DL;IPD:MHC03702
IPD:MHC03702 Mafa-DQB1*18:18 89 bases
 DFVVQFKGLC YFTNGTERVR SVTRYIYNRE EYVRFDSDWG EYRAVTPQGQ
 SDAEYWNSQK DILERTRAEL DTVCIHNYQL ELRTTLQRR* 
>DL;IPD:MHC03703
IPD:MHC03703 Mafa-DQB1*18:19 89 bases
 DFVFQFKGLC YFTNGTERVR LVTRYIYNRE EYVRFDSDWG EYRAVTPLGP
 PDAEYWNSQK DILESTRAEA DTVCRHNYQS ELRTTLQRR* 
>DL;IPD:MHC03776
IPD:MHC03776 Mafa-DQB1*18:20 262 bases
 MPRKKALRIP GGLWGTTVTL MLAMLSTPVA EGRDSPEDFV YQFKGLCYFT
 NGTERVRLVT RYVYNREEYV RFDSDWGEHR AVTPLGRPSA EYWNSQKDFL
 ETTRASVDTV CRHNYQLELR TTLQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNDQEE TAGIVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQRPITVEW RAQSESAQSK MLSGVGGFVL GLIFLGLGLI
 IHHRSQKGLL HX*   
>DL;IPD:MHC03780
IPD:MHC03780 Mafa-DQB1*18:21 262 bases
 MPRKKALRIP GGLWGTTVTL MLAMLSTPVA EGRDSPEDFV FQFKGLCYFT
 NGTERVRHVT RYIYNREEYA RFDSDWGEYR AVTPLGRPDA EYWNSQKDIL
 ESTRAEADTV CRHNYQSELR TTLQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNDQQE TAGIVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGVGGFVL GLIFLGLGLI
 IHHRSQKGLP HX*   
>DL;IPD:MHC03863
IPD:MHC03863 Mafa-DQB1*18:22 89 bases
 DFVYQFKGLC YFTNGTERVR LVTRYIHNRE EYVRFDSDWG EYRAVTPLGP
 PAAEYWNSQK DILERTRAEL DTVCRHNYQS ELRTTLRRR* 
>DL;IPD:MHC03864
IPD:MHC03864 Mafa-DQB1*18:23 89 bases
 DFVFQFKSMC YFINGTEHVH HVNRYIYNRE EFVGFDSYLG VYRPVTPLGR
 SWAEYWNSQK DILERTRAVV DTVCRHNYQS ELRTTLQRR* 
>DL;IPD:MHC03865
IPD:MHC03865 Mafa-DQB1*18:24 89 bases
 DFVYQFKGLC YFTNGTERVR LVTRYIHNRE EYVRFDSDWG EYRAVTPLGP
 PAAEYWNSQK DILERTRAEL DTVCRHNYQS ELRTTLQRR* 
>DL;IPD:MHC04240
IPD:MHC04240 Mafa-DQB1*18:25 89 bases
 DFVYQFKGLC YFTNGTERVR LVTRHVYNRE EYVRFDSDWG EHRAVTPLGR
 PSAEYWNSQK DFLETTRASV DTVCKHNYQS ELRTTLQRR* 
>DL;IPD:MHC05119
IPD:MHC05119 Mafa-DQB1*18:28 84 bases
 QFKGLCYFIN GTERVRGVTR YIYNREEFVR FDSDWGEHRA VTPLGRSWAE
 YWNNQKDFLE TTRASVDTVC RHNYQSELRT TLQR* 
>DL;IPD:MHC00308
IPD:MHC00308 Mafa-DQB1*24:01 89 bases
 DFVVQFKAMC YFTNGTERVH YVTRYIYNRE EFARFDSDVW EYRAVTPLGR
 SWAENWNNQK DVLERTRAEL DTVCRHNYQL ELLSTLQRR* 
