>DL;IPD:MHC00353
IPD:MHC00353 Mafa-I*01:01:01 1098 bases
 ATGCAGATCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCGGCA
 CCACAGTGTC CCGGCCCGGC CGCGGGGAGC CGCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCGGAGTATT
 GGGAAGAGGA GACACGGATC GCCAAGGCCC GCGCACAGAC TGAGCGAGGG
 AACCTGCGGA CCGCGCTCCG CTACTACAAC CAGAGCGAGG GGGGGTCTCA
 CACCCTCCAG AAGATGTGTG GCTGCGACCT GGGGCCGGAC GGGCGCCTAC
 TCCGCGGGTA TTACCAGTCC GCCTACGACG GCAGGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCTGCG GGTGAGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGAGGC AGAGCAGCGG AGAGCCTACC
 TGGAGGGCCG GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAAGGGGAAG
 GAGACGCTGC AGCGCGCGGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA GCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA ACTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAACAGAGA TACACGTGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCATGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCAGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 AACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACGGCTTGAA AAGCCTGA*
>DL;IPD:MHC02486
IPD:MHC02486 Mafa-I*01:02 1089 bases
 ATGCGGGTCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCGGCA
 CCACAGTGTC GCGGCCCGGC CGCGGGGAGC CGCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCGGAGTATT
 GGGAAGAGGA GACACGGATC GCCAAGGCCC GCGCACAGAC TGAGCGAGGG
 AACCTGCGGA CCGCGCTCCG CTACTACAAC CAGAGCGAGG GGGGGTCTCA
 CACCCTCCAG AAGATGTGTG GCTGCGACCT GGGGCCAGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGTCC GCCTACGACG GCAGGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCTGCG GGTGAGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGAGGC AGAGCAGCGG AGAGCCTACC
 TGGAGGGCCG GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAAGGGGAAG
 GAGACGCTGC AGCGCGCGGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA ACTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACGTGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCATGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GACCTGTGGT CGCAGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 AACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC02488
IPD:MHC02488 Mafa-I*01:03 1089 bases
 ATGCGGGTTA TGGCGCCCGG AACCCTCCTC CTGCTGCTCT CGGGGACCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCGGCA
 CCACAGTGTC CCAGCCCGGC CGCGGGGAGC CGCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCGGAGTATT
 GGGAAGAGGA GACACGGATC GCCAAGGCCC GCGCACAGAC TGAGCGAGGG
 AACCTGCGGA CCGCGCTCCG CTACTACAAC CAGAGCGAGG GGGGGTCTCA
 CACTCTCCAG AAGATGTGTG GCTGCGACCT GGGGCCGGAC AGGCGCCTCC
 TCCGCGGGTA TTACCAGTCC GCCTACGACG GCAGGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCTGCT GGTGAGGCGG CTCATAACAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGAGGC AGAGCAGCGG AGAGCCTACC
 TGGAGGGCCG GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAAGGGGAAG
 GAGACGCTGC AGCGCGCGGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA GCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA ACTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACGTGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCATGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCAGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 AACAGTGCCC AAGGCTCTGA TGTGTCTCTT ACAGCTTGA* 
>DL;IPD:MHC02489
IPD:MHC02489 Mafa-I*01:04 1089 bases
 ATGCGGGTCA TGGCGCCCGG AACCCTCCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCGGCA
 CCACAGTGTC CCAGCCCGGC CGCGGGGAGC CGCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCGGAGTATT
 GGGAAGAGGA GACACGGATC GCCAAGGCCC GCGCACAGAC TGAGCGAGGG
 AACCTGCGGA CCGCGCTCCG CTACTACAAC CAGAGCGAGG GGGGGTCTCA
 CACTCTCCAG AAGATGTGTG GCTGCGACCT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGTCC GCCTACGACG GCAGGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCTGCG GGTGAGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGAGGC AGAGCAGCGG AGAGCCTACC
 TGGAGGGCCG GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAAGGGGAAG
 GAGACGCTGC AGCGCGCGGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA GCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA ACTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACGTGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCATGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCAGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 AACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC02490
IPD:MHC02490 Mafa-I*01:05 1089 bases
 ATGCGGGTTA TGGCGCCCGG AACCCTCCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCGGCA
 CCACAGTGTC CCGGCCCGGC CGCGGGGAGC CGCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCGGAGTATT
 GGGAAGAGGA GACACGGATC GCCAAGGCCC GCGCACAGAC TGAGCGAGGG
 AACCTGCGGA CCGCGCTCCG CTACTACAAC CAGAGCGAGG GGGGGTCTCA
 CACCCTCCAG AAGATGTGTG GCTGCGACCT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGTCC GCCTACGACG GCAGGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCTGCG GGTGTGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGAGGC AGAGCAGCGG AGAGCCTACC
 TGGAGGGCCG GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAAGGGGAAG
 GAGACGCTGC AGCGCGCGGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA GCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA ACTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACGTGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCATGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCAGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 AACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC02491
IPD:MHC02491 Mafa-I*01:06 1089 bases
 ATGCGGGTCA TGGCGCCCGG AACCCTCCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCGGCA
 CCACAGTGTC CCGGCCCGGC CGCGGGGAGC CGCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCGGAGTATT
 GGGAAGAGGA GACACGGATC GCCAAGGCCC GCGCACAGAC TGAGCGAGGG
 AACCTGCGGA CCGCGCTCCG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCCTCCAG AAGATGTGTG GCTGCGACCT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGTCC GCCTACGACG GCAGGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCTGCG GGTGAGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGAGGC AGAGCAGCGG AGAGCCTACC
 TGGAGGGCCG GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAAGGGGAAG
 GAGACGCTGC AGCGCGCGGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA GCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA ACTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACGTGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCATGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCAGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACGGCTTGA* 
>DL;IPD:MHC02492
IPD:MHC02492 Mafa-I*01:07 1089 bases
 ATGCGGGTTA TGGCGCCCGG AACCCTCCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCTTGAGG TATTTCGGCA
 CCACAGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAAGATGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCGGAGTATT
 GGGAAGAGGA GACACGGATC GCCAAGGCCC GCGCACAGAC TGAGCGAGGG
 AACCTGCGGA CCGCGCTCCG CTACTACAAC CAGAGCGAGG CGGGGTCTCA
 CACCCTCCAG AAGATGTGTG GCTGCGACCT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGTCC GCCTACGACG GCAGGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCTGCG GGTGAGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGAGGC AGAGCAGTGG AGAGCCTACC
 TGGAGGGCCG GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAAGGGGAAG
 GAGACGCTGC AGCGCGCGGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGCCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA ACAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCTGCA GGAGATGGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACGTGCC
 ATGTGCAGCA CGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCATGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCTGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 AACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC02493
IPD:MHC02493 Mafa-I*01:08 1089 bases
 ATGCGGGTCA TGGCGCCCGG AACCCTCCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCGGCA
 CCACAGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTT GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCGGAGTATT
 GGGAAGAGGA GACACGGATC GCCAAGGCCC GCGCACAGAC TGAGCGAGGG
 AACCTGTGGA CCGCGCTCCG CTACTACAAC CAGAGCGAGG GGGGGTCTCA
 CACCCTCCAG AAGATGTGTG GCTGCGACCT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGTCC GCCTACGACG GCAGGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCTGCG GGTGAGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGAGGC AGAGCAGCGG AGAGCCTACC
 TGGAGGGCCG GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAAGGGGAAG
 GAGACGCTGC AGCGCGCGGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA GCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA ACTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACGTGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCATGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCAGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACGGCTTGA* 
>DL;IPD:MHC02494
IPD:MHC02494 Mafa-I*01:09 1089 bases
 ATGCGGGTCA TGGCGCCCGG AACCCTCCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCGGCA
 CCACAGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTT GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCGGAGTATT
 GGGAAGAGGA GACACGGATC GCCAAGGCCC GCGCACAGAC TGAGCGAGGG
 AACCTGTGGA CCGCGCTCCG CTACTACAAC CAGAGCGAGG GGGGGTCTCA
 CACCCTCCAG AAGATGTGTG GCTGCGACCT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGTCC GCCTACGACG GCAGGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCTGCG GGTGAGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGAGGC AGAGCAGCGG AGAGCCTACC
 TGGAGGGCCG GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAAGGGGAAG
 GAGACGCTGC AGCGCGCGGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA GCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA ACTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACGTGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCATGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCAGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 AACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC02496
IPD:MHC02496 Mafa-I*01:10 1098 bases
 ATGCGGGTTA TGGCGCCCGG AACCCTCCTC CTGCTGCTCT CTGGAGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCGGCA
 CCACAGTGTC CCGGCCCGGC CGCGGGGAGC CGCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCGGAGTATT
 GGGAAGAGGA GACACGGATC GCCAAGGCCC GCGCACAGAC TGAGCGAGGG
 AACCTGCGGA CCGCGCTCCG CTACTACAAC CAGAGCGAGG GGGGGTCTCA
 CACCCTCCAG AAGATGTGTG GCTGCGACCT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGTCC GCCTACGACG GCAGGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCTGCG GGTGAGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGAGGC AGAGCAGCGG AGAGCCTACC
 TGGAGGGCCG GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAAGGGGAAG
 GAGACGCTGC AGCGCGCGGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA GCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA ACTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACGTGCC
 ATGTGCAGCA CGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGTCA
 TCTTCCCAGT CCACCATCCC CATCATGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCAGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 AACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGAA AAGCCTGA*
>DL;IPD:MHC02054
IPD:MHC02054 Mafa-I*01:11 1098 bases
 ATGCGGGTCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCGGCA
 CCACAGTGTC CCGGCCCGGC CGCGGGGAGC CGCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCGGAGTATT
 GGGAAGAGGA GACACGGATC GCCAAGGCCC GCGCACAGAC TGAGCGAGGG
 AACCTGCGGA CCGCGCTCCG CTACTACAAC CAGAGCGAGG GGGGGTCTCA
 CACCCTCCAG AAGATGTGTG GCTGCGACCT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGTCC GCCTACGACG GCAGGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCTGCG GGTGAGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGAGGC AGAGCAGCGG AGAGCCTACC
 TGGAGGGCCG GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAAGGGGAAG
 GAGACGCTGC AGCGCGCGGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA GCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA ACTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACGTGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCATGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCAGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 AACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGAA AAGCCTGA*
>DL;IPD:MHC02052
IPD:MHC02052 Mafa-I*01:12:01 1098 bases
 ATGCGGGTTA TGGCGCCCGG AACCCTCCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCGGCA
 CCACAGTGTC CCGGCCCGGC CGCGGGGAGC CGCGCTTCAT CGTCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCGGAGTATT
 GGGAAGAGCA GACACGGATC GCCAAGGCCC GCGCACAGAC TGAGCGAGGG
 AACCTGCGGA CCGCGCTCCG CTACTACAAC CAGAGCGAGG GGGGGTCTCA
 CACCCTCCAG AAGATGTGTG GCTGCGACCT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGTCC GCCTACGACG GCAGGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCTGCG GGTGAGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGAGGC AGAGCAGCGG AGAGCCTACC
 TGGAGGGCCG GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAAGGGGAAG
 GAGACGCTGC AGCGCGCGGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA GCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA ACTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACGTGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCATGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCAGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC AGCGTCCAGC
 AACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGAA AAGCCTGA*
>DL;IPD:MHC02155
IPD:MHC02155 Mafa-I*01:12:02 1098 bases
 ATGCGGGTTA TGGCGCCCGG AACCCTCCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCGGCA
 CCACAGTGTC CCGGCCCGGC CGCGGGGAGC CGCGCTTCAT CGTCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCGGAGTATT
 GGGAAGAGCA GACACGGATC GCCAAGGCCC GCGCACAGAC TGAGCGAGGG
 AACCTGCGGA CCGCGCTCCG CTACTACAAC CAGAGCGAGG GGGGGTCTCA
 CACCCTCCAG AAGATGTGTG GCTGCGACCT GGGGCCAGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGTCC GCCTACGACG GCAGGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCTGCG GGTGAGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGAGGC AGAGCAGCGG AGAGCCTACC
 TGGAGGGCCG GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAAGGGGAAG
 GAGACGCTGC AGCGCGCGGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA GCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA ACTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACGTGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCATGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCAGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC AGCGTCCAGC
 AACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGAA AAGCCTGA*
>DL;IPD:MHC02053
IPD:MHC02053 Mafa-I*01:13:01 1098 bases
 ATGCGGGTTA TGGCGCCCGG AACCCTCCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA TTCCTTGAGG TATTTCGGCA
 CCACAGTGTC CCGGCCCGGC CGCGGGGAGC CGCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCGGAGTATT
 GGGAAGAGGA GACACGGATC GCCAAGGCCC GCGCACAGAC TGAGCGAGGG
 AACCTGCGGA CCGCGCTCCG CTACTACAAC CAGAGCGAGG GGGGGTCTCA
 CACCCTCCAG AAGATGTGTG GCTGCGACCT GGGACCCGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGTCC GCCTACGACG GCAGGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCTGCG GGTGAGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGAGGC AGAGCAGCGG AGAGCCTACC
 TGGAGGGCCG GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAAGGGGAAG
 GAGACGCTGC AGCGCGCGGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA GCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA ACTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACGTGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCG CATCATGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCAGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 AACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGAA AAGCCTGA*
>DL;IPD:MHC02602
IPD:MHC02602 Mafa-I*01:13:02 1056 bases
 CTGCTCTCGG GGGCCCTGGC CCTGACCGAG ACCTGGGCCG GCTCGCACTC
 CTTGAGGTAT TTCGGCACCA CAGTGTCCCG GCCCGGCCGC GGGGAGCCGC
 GCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC
 AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT GGATGGAGCA
 GGAGGGGCCG GAGTATTGGG AAGAGGAGAC ACGGATCGCC AAGGCCCGCG
 CACAGACTGA GCGAGGGAAC CTGCGGACCG CGCTCCGCTA CTACAACCAG
 AGCGAGGGGG GGTCTCACAC CCTCCAGAAG ATGTGTGGCT GCGACCTGGG
 GCCGGACGGG CGCCTCCTCC GCGGGTATTA CCAGTCCGCC TACGACGGCA
 GGGATTACAT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCTGCGGGT
 GAGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCGGCCG GTGAGGCAGA
 GCAGCGGAGA GCCTACCTGG AGGGCCGGTG CGTGGAGTGG CTCCGCAGAT
 ACCTGGAGAA GGGGAAGGAG ACGCTGCAGC GCGCGGATCC CCCAAAGACA
 CACGTGACCC ACCACCCCGT CTCTGACCAT GAAGCCACCC TGAGGTGCTG
 GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG CAGCGGGATG
 GGGAGGAGCA AACTCAGGAC ACCGAGCTTG TGGAGACCAG GCCAGGAGGA
 GATGGAAACT TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT CTGGAGAAGA
 GCAGAGATAC ACGTGCCATG TGCAGCATGA GGGGCTGCCG GAGCCCCTCA
 CCCTGAGATG GGAGCCATCT TCCCAGTCCA CCATCCGCAT CATGGGCATT
 GTTGCTGGCC TGGCTGTCCT AGCAGTTGTG GTCACCGGAG CTGTGGTCGC
 AGCTGTGATG TGGAGGAGGA AGAGCTCAGG TGGAAAAGGA GGGAGCTACT
 CTCAGGCTGC GTCCAGCAAC AGTGCCCAGG GCTCTGATGT GTCTCTCACA
 GCTTGA*    
>DL;IPD:MHC02156
IPD:MHC02156 Mafa-I*01:14 1098 bases
 ATGCGGGTTA TGGCGCCCGG AACCCTCCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCGGCA
 CCACAGTGTC CCGGCCCGGC CGCGGGGAGC CGCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCGGAGTATT
 GGGAAGAGGA GACACGGATC GCCAAGGCCC GCGCACAGAC TGAGCGAGGG
 AACCTGCGGA CCGCGCTCCG CTACTACAAC CAGAGCGAGG GGGGGTCTCA
 CACCCTCCAG AAGATGTGTG GCTGCGACCT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGTCC GCCTACGACG GCAGGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCTGCG GGTGAGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGAGGC AGAGCAGCGG AGAGCCTACC
 TGGAGGGCCG GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAAGGGGAAG
 GAGACGCTGC AGCGCGCGGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA GCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA ACTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACGTGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCATGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCAGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC AGCGTCCAGC
 AACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGAA AAGCCTGA*
>DL;IPD:MHC02600
IPD:MHC02600 Mafa-I*01:15 1056 bases
 CTGCTCTCGG GGGCCCTGGC CCTGACCGAG ACCTGGGCCG GCTCGCACTC
 CTTGAGGTAT TTCGGCACCA CAGTGTCCCG GCCCGGCCGC GGGGAGCCGC
 GCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC
 AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT GGATGGAGCA
 GGAGGGGCCG GAGTATTGGG AAGAGGAGAC ACGGATCGCC AAGGCCCGCG
 CACAGACTGA GCGAGGGAAC CTGCGGACCG CGCTCCGCTA CTACAACCAG
 AGCGAGGGGG GGTCTCACAC CCTCCAGAAG ATGTGTGGCT GCGACCTGGG
 GCCGGACGGG CGCCTCCTCC GCGGGTATTA CCAGTCCGCC TACGACGGCA
 GGGATTACAT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCTGCGGGT
 GAGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCGGCCG GTGAGGCAGA
 GCAGCGGAGA GCCTACCTGG AGGGCCGGTG CGTGGAGTGG CTCCGCAGAT
 ACCTGGAGAA GGGGAAGGAG ACGCTGCAGC GCGCGGATCC CCCAAAGACA
 CACGTGACCC ACCACCCCGT CTCTGACCAT GAGGCCACCC TGAGGTGCTG
 GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG CAGCGGGATG
 GGGAGGACCA AACTCAGGAC ACCGAGCTTG TGGAGACCAG GCCAGGAGGA
 GATGGAAACT TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT CTGGAGAAGA
 GCAGAGATAC ACGTGCCATG TGCAGCATGA GGGGCTGCCG GAGCCCCTCA
 CCCTGAGATG GGAGCCATCT TCCCAGTCCA CCATCCCCAT CATGGGCATT
 GTTGCTGGCC TGGCTGTCCT AGCAGTTGTG GTCACTGGAG CTGTGGTCGC
 AGCTGTGATG TGGAGGAGGA AGAGCTCAGG TGGAAAAGGA GGGAGCTACT
 CTCAGGCTGC GTCCAGCAAC AGTGCCCAGG GCTCTGATGT GTCTCTCACA
 GCTTGA*    
>DL;IPD:MHC02601
IPD:MHC02601 Mafa-I*01:16 1056 bases
 CTGCTCTCGG GGGCCCTGGC CCTGACCCAG ACCTGGGCCG GCTCGCATTC
 CTTGAGGTAT TTCGGCACCA CAGTGTCCCG GCCCGGCCGC GGGGAGCCGC
 GCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC
 AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT GGATGGAGCA
 GGAGGGGCCG GAGTATTGGG AAGAGGAGAC ACGGATCGCC AAGGCCCGCG
 CACAGACTGA GCGAGGGAAC CTGCGGACCG CGCTCCGCTA CTACAACCAG
 AGCGAGGGGG GGTCTCACAC CCTCCAGAAG ATGTGTGGCT GCGACCTGGG
 GCCGGACGGG CGCCTCCTCC GCGGGTATTA CCAGTCCGCC TACGACGGCA
 GGGATTACAT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCTGCGGGT
 GAGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCGGCCG GTGAGGCAGA
 GCAGCGGAGA GCCTACCTGG AGGGCCGGTG CGTGGAGTGG CTCCGCAGAT
 ACCTGGAGAA GGGGAAGGAG ACGCTGCAGC GCGCGGATCC CCCAAAGACA
 CACGTGACCC ACCACCCCGT CTCTGACCAT GAGGCCACCC TGAGGTGCTG
 GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG CAGCGGGATG
 GGGAGGAGCA AACTCAGGAC ACCGAGCTTG TGGAGACCAG GCCAGGAGGA
 GATGGAAACT TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT CTGGAGAAGA
 GCAGAGATAC ACGTGCCATG TGCAGCATGA GGGGCTGCCG GAGCCCCTCA
 CCCTGAGATG GGAGCCATCT TCCCAGTCCA CCATCCGCAT CATGGGCATT
 GTTGCTGGCC TGGCTGTCCT AGCAGTTGTG GTCACTGGAG CTGTGCTCGC
 TGCTGTGATG TGGAGGAGGA AGAGCTCAGG TGGAAAAGGA GGGAGCTACT
 CTCAGGCTGC GTCCAGCAAC AGTGCCCAGG GCTCTGATGT GTCTCTCACA
 GCTTGA*    
>DL;IPD:MHC02603
IPD:MHC02603 Mafa-I*01:17 1056 bases
 CTGCTCTCGG GGGCCCTGGC CCTGACCGAG ACCTGGGCCG GCTCGCACTC
 CTTGAGGTAT TTCGGCACCA CAGTGTCCCG GCCCGGCCGC GGGGAGCCGC
 GCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC
 AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT GGATGGAGCA
 GGAGGGGCCG GAGTATTGGG AAGAGGAGAC ACGGATCGCC AAGGCCCGCG
 CACAGACTGA GCGAGGGAAC CTGCGGACCG CGCTCCGCTA CTACAACCAG
 AGCGAGGGGG GGTCTCACAC CCTCCAGAAG ATGTGTGGCT GCGACCTGGG
 GCCAGACGGG CGCCTCCTCC GCGGGTATTA CCAGTCCGCC TACGACGGCA
 GGGATTACAT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCTGCGGGT
 GAGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCGGCCG GTGAGGCAGA
 GCAGCGGAGA GCCTACCTGG AGGGCCGGTG CGTGGAGTGG CTCCGCAGAT
 ACCTGGAGAA GGGGAAGGAG ACGCTGCAGC GCGCGGATCC CCCAAAGACA
 CACGTGACCC ACCACCCCAT CTCTGACCAT GAGGCCACCC TGAGGTGCTG
 GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG CAGCGGGATG
 GGGAGGACCA AACTCAGGAC ACCGAGCTTG TGGAGACCAG GCCAGGAGGA
 GATGGAAACT TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT CTGGAGAAGA
 GCAGAGATAC ACGTGCCATG TGCAGCATGA GGGGCTGCCG GAGCCCCTCA
 CCCTGAGATG GGAGCCATCT TCCCAGTCCA CCATCCCCAT CATGGGCATT
 GTTGCTGGCC TGGCTGTCCT AGCAGTTGTG GTCACCGGAC CTGTGGTCGC
 AGCTGTGATG TGGAGGAGGA AGAGCTCAGG TGGAAAAGGA GGGAGCTACT
 CTCAGGCTGC GTCCAGCAAC AGTGCCCAGG GCTCTGATGT GTCTCTCACA
 GCTTGA*    
>DL;IPD:MHC02604
IPD:MHC02604 Mafa-I*01:18 1056 bases
 CTGCTCTCGG GGGCCCTGGC CCTGACCGAG ACCTGGGCCG GCTCGCACTC
 CTTGAGGTAT TTCGGCACCA CAGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC
 AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT GGATGGAGCA
 GGAGGGGCCG GAGTATTGGG AAGAGGAGAC ACGGATCGCC AAGGCCCGCG
 CACAGACTGA GCGAGGGAAC CTGCGGACCG CGCTCCGCTA CTACAACCAG
 AGCGAGGCGG GGTCTCACAC CCTCCAGAAG ATGTGTGGCT GCGACCTGGG
 GCCGGACGGG CGCCTCCTCC GCGGGTATTA CCAGTCCGCC TACGACGGCA
 GGGATTACAT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCTGCGGGT
 GAGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCGGCCG GTGAGGCAGA
 GCAGCGGAGA GCCTACCTGG AGGGCCGGTG CGTGGAGTGG CTCCGCAGAT
 ACCTGGAGAA GGGGAAGGAG ACGCTGCAGC GCGCGGATCC CCCAAAGACA
 CACGTGACCC ACCACCCCGT CTCTGACCAT GAGGCCACCC TGAGGTGCTG
 GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG CAGCGGGATG
 GGGAGGAGCA AACTCAGGAC ACCGAGCTTG TGGAGACCAG GCCAGGAGGA
 GATGGAAACT TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT CTGGAGAAGA
 GCAGAGATAC ACGTGCCATG TGCAGCATGA GGGGCTGCCG GAGCCCCTCA
 CCCTGAGATG GGAGCCATCT TCCCAGTCCA CCATCCCCAT CATGGGCATT
 GTTGCTGGCC TGGCTGTCCT AGCAGTTGTG GTCACCGGAG CTGTGGTCGC
 AGCTGTGATG TGGAGGAGGA AGAGCTCAGG TGGAAAAGGA GGGAGCTACT
 CTCAGGCTGC GTCCAGCAAC AGTGCCCAGG GCTCTGATGT GTCTCTCACA
 GCTTGA*    
>DL;IPD:MHC02605
IPD:MHC02605 Mafa-I*01:19 1056 bases
 CTGCTCTCGG GGGCCCTGGC CCTGACCGAG ACCCGGGCCG GCTCGCACTC
 CTTGAGGTAT TTCGGCACCA CAGTGTCCCG GCCCGGCCGC GGGGAGCCGC
 GCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC
 AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT GGATGGAGCA
 GGAGGGGCCG GAGTATTGGG AAGAGGAGAC ACGGATCGCC AAGGCCCGCG
 CACAGACTGA GCGAGGGAAC CTGCGGACCG CGCTCCGCTA CTACAACCAG
 AGCGAGGGGG GGTCTCACAC CCTCCAGAAG ATGTGTGGCT GCGACCTGGG
 GCCGGACGGG CGCCTCCTCC GCGGGTATTA CCAGTCCGCC TACGACGGCA
 GGGATTACAT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCTGCGGGT
 GAGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCGGCCG GTGAGGCAGA
 GCAGCGGAGA GCCTACCTGG AGGGCCGGTG CGTGGAGTGG CTCCGCAGAT
 ACCTGGAGAA GGGGAAGGAG ACGCTGCAGC GCGCGGATCC CCCAAAGACA
 CACGTGACCC ACCACCCCGT CTCAGACCAT GAGGCCACCC TGAGGTGCTG
 GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG CAGCGGGATG
 GGGAGGAGCA AACTCAGGAC ACCGAGCTTG TGGAGACCAG GCCAGGAGGA
 GATGGAAACT TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT CTGGAGAAGA
 GCAGAGATAC ACGTGCCATG TGCAGCATGA GGGGCTGCCG GAGCCCCTCA
 CCCTGAGATG GGAGCCATCT TCCCAGTCCA CCATCCCCAT CATGGGCATT
 GTTGCTGGCC TGGCTGTCCT AGCAGTTGTG GTCACTGGAG CTGTGGTCGC
 AGCTGTGATG TGGAGGAGGA AGAGCTCAGG TGGAAAAGGA GGGAGCTACT
 CTCAGGCTGC GTCCAGCAAC AGTGCCCAGG GCTCTGATGT GTCTCTCACA
 GCTTGA*    
>DL;IPD:MHC02606
IPD:MHC02606 Mafa-I*01:20 1056 bases
 CTGCTCTCGG GGGCCCTGGC CCTGACCCAG ACCTGGGCCG GCTCGCACTC
 CTTGAGGTAT TTCGGCACCA CAGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC
 AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT GGATGGAGCA
 GGAGGGGCCG GAGTATTGGG AAGAGGAGAC ACGGATCGCC AAGGCCCGCG
 CACAGACTGA GCGAGGGAAC CTGCGGACCG CGCTCCGCTA CTACAACCAG
 AGCGAGGGGG GGTCTCACAC CCTCCAGAAG ATGTGTGGCT GCGACCTGGG
 GCCGGACGGG CGCCTCCTCC GCGGGTATTA CCAGTCCGCC TACGACGGCA
 GGGATTACAT CGCCCTTAAC GAGGACCTGC GCTCCTGGAC CGCTGCGGGT
 GAGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCGGCCG GTGAGGCAGA
 GCAGCGGAGA GCCTACCTGG AGGGCCGGTG CGTGGAGTGG CTCCGCAGAT
 ACCTGGAGAA GGGGAAGGAG ACGCTGCAGC GCGCGGATCC CCCAAAGACA
 CACATGACCC ACCACCCCAT CTCTGACCAT GAGGCCACCC TGAGGTGCTG
 GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG CAGCGGGATG
 GGGAGGAGCA AACTCAGGAC ACCGAGCTTG TGGAGACCAG GCCAGGAGGA
 GATGGAAACT TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT CTGGAGAAGA
 GCAGAGATAC ACGTGCCATG TGCAGCATGA GGGGCTGCCG GAGCCCCTCA
 CCCTGAGATG GGAGCCATCT TCCCAGTCCA CCATCCCCAT CATGGGCATT
 GTTGCTGGCC TGGCTGTCCT AGCAGTTGTG GTCACCGGAG CTGTGGTCGC
 AGCTGTGATG TGGAGGAGGA AGAGCTCAGG TGGAAAAGGA GGGAGCTACT
 CTCAGGCTGC TGTCCAGCAA CAGTGCCCAG GGCTCTGATG TGTCTCTCAC
 AGCTTG*    
>DL;IPD:MHC03381
IPD:MHC03381 Mafa-I*01:21 1098 bases
 ATGCGGGTTA TGGCGCCCGG AACCCTCCTC CTGCTGCTCT CTGGAGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCGGCA
 CCACAGTGTC CCGGCCCGGC CGCGGGGAGC CGCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCGGAGTATT
 GGGAAGAGGA GACACGGATC GCCAAGGCCC GCGCACAGAC TGAGCGAGGG
 AACCTGCGGA CCGCGCTCCG CTACTACAAC CAGAGCGAGG GGGGGTCTCA
 CACCCTCCAG AAGATGTGTG GCTGCGACCT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGTCC GCCTACGACG GCAGGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCTGCG GGTGAGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGAGGC AGAGCAGCGG AGAGCCTACC
 TGGAGGGCCG GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAAGGGGAAG
 GAGACGCTGC AGCGCGCGGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA GCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA ACTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACGTGCC
 ATGTGCAGCA CGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGTCA
 TCTTCCCAGT CCACCACCCC CATCATGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCAGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 AACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGAA AAGCCTGA*
>DL;IPD:MHC03819
IPD:MHC03819 Mafa-I*01:22 1098 bases
 ATGCAGATCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCGGCA
 CCACAGTGTC CCGGCCCGGC CGCGGGGAGC CGCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCGGAGTATT
 GGGAAGAGGA GACACGGATC GCCAAGGCCC GCGCACAGAC TGAGCGAGGG
 AACCTGCGGA CCGCGCTCCG CTACTACAAC CAGAGCGAGG GGGGGTCTCA
 CACCCTCCAG AAGATGTGTG GCTGCGACCT GGGGCCGGAC GGGCGCCTAC
 TCCGCGGGTA TTACCAGTCC GCCTACGACG GCAGGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCTGCG GGTGAGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGAGGC AGAGCAGCGG AGAGCCTACC
 TGGAGGGCCG GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAAGGGGAAG
 GAGACACTGC AGCGCGCGGT TCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA GCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA ACTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACGTGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCATGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCAGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 AACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACGGCTTGAA AAGCCTGA*
>DL;IPD:MHC02487
IPD:MHC02487 Mafa-I*02:01 1089 bases
 ATGCGGGTCA TGGCGCCCGG AACCCTCCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCGGCA
 CCACAGTGTC CCAGCCCGGC CGCGGGGAGC CGCGCTTCAT CGCCGTGGGC
 TACAATGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCGGAGTATT
 GGGAAGAGGA GACACGGATC GCCAAGGCCC GCGCACAGAC TGACCGAGGA
 ACCCTGCGGA CCCTGCTCCG CTACTACAAC CAGAGCGAGG GGGGGTCTCA
 CACCCTCCAG AAGATGTACG GCTGCGACCT GGGGCCCGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGGAC GCCTACGACG GCAGGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCTGCG GATGAGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGAGGC AGAGCAGCGG AGAGCCTACC
 TGGAGGGCCG GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAAGGGGAAG
 GAGACGCTGC AGCGCGCGGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA ACTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACGTGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCATGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GACCTGTGGT CGCAGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 AACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC02497
IPD:MHC02497 Mafa-I*03:01:01 1099 bases
 ATGCGGGTCA TGGCGCCCGG AACCCTCCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCGGCA
 CCACAGTGTC GCGGCCCGGC CGCGGGGAGC CGCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCGGAGTATT
 GGGAAGAGGA GACACGGATC GCCAAGGGCC ACGCACAGAC TGACCGAGCA
 GACCTGGGGA CCGCGCTCCG CTACTACAAC CAGAGCGAGG GGGGGTCTCA
 CACCCTCCAG AAGATGTGTG GCTGCGACCT GGGGCCAGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGTCC GCCTATGACG GCAAGGATTA CATCACCCTG
 AACGAGGACC TGCGCTCCTG GACCGCTGCG GGTGAGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGAGGC AGAGCAGCGG AGAGCCTACC
 TGGAGGGCCG GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAAGGGGAAG
 GAGACGCTGC AGCGCGCGGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA ACTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACGTGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCATGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCAGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCTGTCCAG
 CAACAGTGCC CAGGGCTCTG ATGTGTCTCT CACAGCTTGA AAAGTCTGA*
>DL;IPD:MHC02607
IPD:MHC02607 Mafa-I*03:01:02 1056 bases
 CTGCTCTCGG GGGCCCTGGC CCTGACCGAG ACCTGGGCCG GCTCGCACTC
 CTTGAGGTAT TTCGGCACCA CAGTGTCGCG GCCCGGCCGC GGGGAGCCGC
 GCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC
 AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT GGATGGAGCA
 GGAGGGGCCG GAGTATTGGG AAGAGGAGAC ACGGATCGCC AAGGGCCACG
 CACAGACTGA CCGAGCAGAC CTGGGGACCG CGCTCCGCTA CTACAACCAG
 AGCGAGGGGG GGTCTCACAC CCTCCAGAAG ATGTGTGGCT GCGACCTGGG
 GCCAGACGGG CGCCTCCTCC GCGGGTATTA CCAGTCCGCC TATGACGGCA
 AGGATTACAT CACCCTGAAC GAGGACCTGC GCTCCTGGAC CGCTGCGGGT
 GAGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCGGCCG GTGAGGCAGA
 GCAGCGGAGA GCCTACCTGG AGGGCCGGTG CGTGGAGTGG CTCCGCAGAT
 ACCTGGAGAA GGGGAAGGAG ACGCTGCAGC GCGCGGATCC CCCAAAGACA
 CACATGACCC ACCACCCCGT CTCTGACCAT GAGGCCACCC TGAGGTGCTG
 GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG CAGCGGGATG
 GGGAGGACCA AACTCAGGAC ACCGAGCTTG TGGAGACCAG GCCAGGAGGA
 GATGGAAACT TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT CTGGAGAAGA
 GCAGAGATAC ACGTGCCATG TGCAGCATGA GGGGCTGCCG GAGCCCCTCA
 CCCTGAGATG GGAGCCATCT TCCCAGTCCA CCATCCCCAT CATGGGCATT
 GTTGCTGGCC TGGCTGTCCT AGCAGTTGTG GTCACCGGAG CTGTGGTCGC
 AGCTGTGATG TGGAGGAGGA AGAGCTCAGG TGGAAAAGGA GGGAGCTACT
 CTCAGGCTGC TGTCCAGCAA CAGTGCCCAG GGCTCTGATG TGTCTCTCAC
 AGCTTG*    
>DL;IPD:MHC02669
IPD:MHC02669 Mafa-I*04:01 1089 bases
 ATGCGGGTTA TGGCGCCCGG AACCCTCCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCGGCA
 CCACAGTGTC CCGGCCCGGC CGCGGGGAGC CGCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCGGAGTATT
 GGGAAGAGGA GACACGGATC GCCAAGGCCC GCGCACAGAC TGAGCGAGAG
 GACCTGCGGA CCGCGCTCCG CTACTACAAC CAGAGCGAGG GGGGGTCTCA
 CACCCTCCAG AAGATGTGTG GCTGCGACCT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGTCC GCCTACGACG GCAGGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCTGCG GGTAAGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGTGGC GGAGCAGCGG AGAGCCTACC
 TGGAGGGCCT GTGTTTGGAG TCACTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGGCGC AGCGCGCGGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA GCAAACTCAG
 GACACAGAGT TTGTGGAGAC CAGGCCAGGA GGAGATGGAA CCTTCCAGAA
 GTGGGGAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACGTGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCGC CATCGTGGGC ATTGTTGTTG GCCTGGCTGT
 CCTAGCAATT GTGGTCACCG GAGCTGTGGT CGCTGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAAC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACGGCTTGA* 
