>DL;IPD:MHC02559
IPD:MHC02559 Mafa-B11L*01:01 273 bases
 SHSMRYFHTA VSRPGRGEPR FISVGYVDDT QFVRFDSNAA SPRMEPRAPW
 IEQEGPEYWD RETQKAKAHA QVFRVNLRTA LRYYNQSEAG SHTFQRMHGC
 DLGPDGRLLR GYHQLAYDGK DYIALNGDLS SWSAADMAAQ VTQRKWEAAG
 EAEQRRAYLE GECLESIRRY LENGKETLQR VDPPKTHVTH HPVSDHEAIL
 RCWALGFYPA EITLTWQRDG EEQTQDTELV ETRPAGNGTF QKWAAVVVPS
 GEEQRYTCHV QHQGLLEPLT LRW*  
>DL;IPD:MHC02560
IPD:MHC02560 Mafa-B11L*01:02 273 bases
 SHSMRYFHTA VSRPGRGEPR FISVGYVDDT QFVRFDSNAA SPRMEPRAPW
 IEQEGPEYWD RETQKAKAHA QVFRVNLRTA LRYYNQSEAG SHTFQRMHGC
 DLGPDGRLLR GYHQLAYDGK DYIALNGDLS SWSAADMAAQ VTQRKWEAAR
 EAEQRRAYLE GECLESLRRY LENGKETLQR VDPPKTHVTH HPVSDHEAIL
 RCWALGFYPA EITLTWQRDG EEQTQDTELV ETRPAGNGTF QKWAAVVVPS
 GEEQRYTCHV QHQGLLEPLT LRW*  
>DL;IPD:MHC02561
IPD:MHC02561 Mafa-B11L*01:03 273 bases
 SHSMRYFHTA VSRPGRGEPR FIAVGYVDDT QFVRFDSNAA SPRMEPRAPW
 IEQEGPEYWD RETQKAKAHA QVFRVNLRTP LRYYNQSEAG SHTFQRMHGC
 DLGPDGRLLR GYHQLAYDGK DYIALNGDLS SWSAADMAAQ VTQRKWEAAR
 EAEQRRAYLE GECLESLRRY LENGKETLQR VDPPKTHVTH HPVSDHEAIL
 RCWALGFYPA EITLTWQRDG EEQTQDTELV ETRPAGNGTF QKWAAVVVPS
 GEEQRYTCHV QHKGLLEPLT LRW*  
>DL;IPD:MHC03833
IPD:MHC03833 Mafa-B11L*01:04 316 bases
 LLSGTLALTE TWAGSHSMRY FHTAVSRPGR GEPRFIAVGY VDDTQFVRFD
 SDAASPRMEP RAPWIEQEGP EYWDRETHKA KAHAQVFRVN LRTALRYYNQ
 SEAGSHTFQR MHGCDLGPDG RLLRGYHQLA YDGKDYIALN GDLSSWSAAD
 MAAQVTQRKW EAAREAEQRR AYLEGECLEW LRRYLENGKE TLQRVDPPKT
 HVTHHPVSDH EATLRCWALG FYPAEITLTW QGDGEEQTQD TELVETRPAG
 DRTFQKWAAV VVPSGEEQRY MCHVQHQGLL EPLTLRWERA SQPSIPIVGI
 VAGLAVLGTV VTVAVV*   
>DL;IPD:MHC03836
IPD:MHC03836 Mafa-B11L*01:05 219 bases
 LLSGTLALTE TWAGSHSMRY FHTAVSRPGR GEPRFIAVGY VDDTQFVRFD
 SDAASPRMEP RAPWIEQEGP EYWDRETQKA KAHAQVFRVN LRTALRYYNQ
 SEAGSHTFQR MHGCDLGSDG RLLRGYHQLA YDGKDYIALN GDLSSWSAAD
 MAAQVTQRKW EAAREAEQRR AYLEGECLEW LRRYLENGKE TLQRVDPPKT
 HVTHHPVSDH EATLRCWAL*   
