>DL;IPD:MHC04806
IPD:MHC04806 Mafa-F*01:01 552 bases
 GCTCCCACTC CTTGCGGTAT TTTAGCACCG CTGTGTCGCG GCCCGGCCGC
 AGGGAGCCCC GGTACAGGTA CATCGCGGTG GAGTACGTGG ACGACACGCA
 GTTCCTGCGG TTCGACAGCG ACGCCGCGAT TCCGAGGATG GAGCCGCGGG
 CGCCGTGGGT GGAGCAAGAG GGGCCGCAGT ATTGGGAGCG GACCACAGGG
 TACGCCAAGG CCAACGCACG GACTGACCGA GTGGCCCTGA GGAAGCTGCT
 CCTCCGCTAC AACCAGAGCG AGGCAGGGTC TCACACCCTC CAGGGAATGA
 ACGGCTGCGA CATGGGGCCC GACGGACGCC TCCTCCGCGG GTATCACCAG
 CACGCCTACG ACGGCAAGGA TTACATCTCC CTGAACGAGG ACCCGCGCTC
 CTGGACCGCC GCGGACACGG TAGCTCGGAT CACCCAGCGC TTCTATGAGG
 CAGAGGAATA TGCAGAGGAG TTCAGGACCT ACCTGGAGGG CGAGTGCCTG
 GAGTTGCTCC GCAGATACCT GGAGAACGGG AAGGAGACGC TACAGCGCGC
 AG*    
>DL;IPD:MHC04807
IPD:MHC04807 Mafa-F*01:02:01 1010 bases
 ATGGCGCCCC GAACCCTCCT CCTGGTGCTC TCAGGGGCCC TGGCCCTGAC
 CGAGACCTGG GCGGGCTCCC ACTCCTTGCG GTATTTTAGC ACCGCTGTGT
 CGCGGCCCGG CCGCAGGGAG CCTCAGTACA GGTACATCGC GGTGGAGTAC
 GTGGACGACA CGCAGTTCCT GCGGTTCGAC AGCGACGCCG CGATTCCGAG
 GATGGAGCCG CGAGCGCCGT GGGTGGAGCA AGAGGGGCCG CAGTATTGGG
 AGCGGACCAC AGGGTACGCC AAGGCCAACG CACGGACTGA CCGAGTGGCC
 CTGAGGAAGC TGCTCCTCCG CTACAACCAG AGCGAGGCCG GGTCTCACAC
 CCTCCAGGGA ATGAATGGCT GCGACATGGG GCCCGACGGA CGCCTCCTCC
 GCGGGTATCA CCAGCACGCC TACGACGGCA AGGATTACAT CTCCCTGAAC
 GAGGACCTGC GCTCCTGGAC CGCCGCGGAC ACGGTAGCTC GGATCACCCA
 GCGCTTCTAT GAGGCAGAGG AATATGCAGA GGAGTTCAGG ACCTACCTGG
 AGGGCGAGTG CCTGGAGTTG CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG
 ACGCTACAGC GCGCAGATCC TCCAAAGGCA CACGTTGCCC ACCACCCCAT
 CTCTGACCGT GAGGCCACCC TGAGGTGCTG GGCCCTGGGC TTCTACCCTG
 CCGAGATCAC ACTGACCTGG CAGCGGGACG GGGAGGAACA GACCCAGGAC
 ACGGAGCTTG TGGAGACCAG GCCTGCAGGG GATGGAACCT TCCAGAAGTG
 GGCAGCTGTG GTGGTGCCTT CCGGAGAGGA GCAGAGATAC ACGTGCCATG
 TGCAACACGA AGGGCTGCCC CAGCCCCTCA CCCTGAGATG GGAGTCGTCT
 TCTCAGCCCA CCATCCCCAT TGTGGGCATC GTTGCTGGCC TGGCTGTCCT
 AGCAGTTGTG GTTACTGGAG CTGTGGTCGC TGCTGTAATG TGGAGGAGAA
 AGAGCTCAGC *   
>DL;IPD:MHC04813
IPD:MHC04813 Mafa-F*01:02:02 1010 bases
 ATGGCGCCCC GAACCCTCCT CCTGGTGCTC TCAGGGGCCC TGGCCCTGAC
 CGAGACCTGG GCGGGCTCCC ACTCCTTGCG GTATTTTAGC ACCGCTGTGT
 CGCGGCCCGG CCGCAGGGAG CCTCAGTACA GGTACATCGC GGTGGAGTAC
 GTGGACGACA CGCAGTTCCT GCGGTTCGAC AGCGACGCCG CGATTCCGAG
 GATGGAGCCG CGAGCGCCGT GGGTGGAGCA AGAGGGGCCG CAGTATTGGG
 AGCGGACCAC AGGGTACGCC AAGGCCAACG CACGGACTGA CCGAGTGGCC
 CTGAGGAAGC TGCTCCTCCG CTACAACCAG AGCGAGGCCG GGTCTCACAC
 CCTCCAGGGA ATGAACGGCT GCGACATGGG GCCCGACGGA CGCCTCCTCC
 GCGGGTATCA CCAGCACGCC TACGACGGCA AGGATTACAT CTCCCTGAAC
 GAGGACCTGC GCTCCTGGAC CGCCGCGGAC ACGGTAGCTC GGATCACCCA
 GCGCTTCTAT GAGGCAGAGG AATATGCAGA GGAGTTCAGG ACCTACCTGG
 AGGGCGAGTG CCTGGAGTTG CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG
 ACGCTACAGC GCGCAGATCC TCCAAAGGCA CACGTTGCCC ACCACCCCAT
 CTCTGACCGT GAGGCCACCC TGAGGTGCTG GGCCCTGGGC TTCTACCCTG
 CCGAGATCAC ACTGACCTGG CAGCGGGACG GGGAGGAACA GACCCAGGAC
 ACGGAGCTTG TGGAGACCAG GCCTGCAGGG GATGGAACCT TCCAGAAGTG
 GGCAGCTGTG GTGGTGCCTT CCGGAGAGGA GCAGAGATAC ACGTGCCATG
 TGCAACACGA AGGGCTGCCC CAGCCCCTCA CCCTGAGATG GGAGTCGTCT
 TCTCAGCCCA CCATCCCCAT TGTGGGCATC GTTGCTGGCC TGGCTGTCCT
 AGCAGTTGTG GTTACTGGAG CTGTGGTCGC TGCTGTAATG TGGAGGAGAA
 AGAGCTCAGC *   
>DL;IPD:MHC04808
IPD:MHC04808 Mafa-F*01:03 1010 bases
 ATGGCGCCCC GAACCCTCCT CCTGGTGCTC TCAGGGGCCC TGGCCCTGAC
 CGAGACCTGG GCGGGCTCCC ACTCCTTGCG GTATTTTAGC ACCGCTGTGT
 CGCGGCCCGG CCGCAGGGAG CCTCAGTACA GGTACATCGC GGTGGAGTAC
 GTGGACGACA CGCAGTTCCT GCGGTTCGAC AGCGACGCCG CGATTCCGAG
 GATGGAGCCG CGAGCGCCGT GGGTGGAGCA AGAGGGGCCG CAGTATTGGG
 AGCGGACCAC AGGGTACGCC AAGGCCAACG CACGGACTGA CCGAGTGGCC
 CTGAGGAAGC TGCTCCTCCG CTACAACCAG AGCGAGGCCG GGTCTCACAC
 CCTCCAGGGA ATGAACGGCT GCGACATGGG GCCCGACGGA CGTCTCCTCC
 GCGGGTATCA CCAGCACGCC TACGACGGCA AGGATTACAT CTCCCTGAAC
 GAGGACCTGC GCTCCTGGAC CGCCGCGGAC ACGGTAGCTC GGATCACCCA
 GCGCTTCTAT GAGGCAGAGG AATATGCAGA GGAGTTCAGG ACCTACCTGG
 AGGGCGAGTG CCTGGAGTTG CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG
 ACGCTACAGC GCGCAGATCC TCCAAAGGCA CACGTTGCCC ACCACCCCAT
 CTCTGACCGT GAGGCCACCC TGAGGTGCTG GGCCCTGGGC TTCTACCCTG
 CCGAGATCAC ACTGACCTGG CAGCGGGACG GGGAGGAACA GACCCAGGAC
 ACGGAGCTTG TGGAGACCAG GCCTGCAGGG GATGGAACCT TCCAGAAGTG
 GGCAGCTGTG GTGGTGCCTT CCGGAGAGGA GCAGAGATAC ACGTGCCATG
 TGCAACACGA AGGGCTGCCC CAGCCCCTCA CCCTGAGATG GGAGTCGTCT
 TCTCAGCCCA CCATCCCCAT TGTGGGCATC GTTGCTGGCC TGGCTGTCCT
 AGCAGTTGTG GTTACTGGAG CTGTGGTCAC TGCTGTAATG TGGAGGAGAA
 AGAGCTCAGC *   
>DL;IPD:MHC04809
IPD:MHC04809 Mafa-F*01:04 1010 bases
 ATGGCACCCC GAACCCTCCT CCTGGTGCTC TCAGGGGCCC TGGCCCTGAC
 CGAGACCTGG GCAGGCTCCC ACTCCTTGCG GTATTTTAGC ACCGCTGTGT
 CGCGGCCCGG CCGCAGGGAG CCTCGGTACA GGTACATCGC GGTGGAGTAC
 GTGGACGACA CGCAGTTCCT GCGGTTCGAC AGCGACGCCG CGATTCCGAG
 GATGGAGCCG CGGGCGCCGT GGGTGGAGCA AGAGGGGCCG CAGTATTGGG
 AGCGGACCAC AGGGTACGCC AAGGCCAACG CACGGACTGA CCGAGTGGCC
 CTGAGGAAGC TGCTCCTCCG CTACAACCAG AGCGAGGCCG GGTCTCACAC
 CCTCCAGGGA ATGAACGGCT GCGACATGGG GCCCGACGGA CGCCTCCTCC
 GCGGGTATCA CCAGCACGCT TACGACGGCA AGGATTACAT CTCCCTGAAC
 GAGGACCTGC GCTCCTGGAC CGCCGCGGAC ACGGTAGCTC GGATCACCCA
 GCGCTTCTAT GAGGCAGAGG AATATGCAGA GGAGTTCAGG ACCTACCTGG
 AGGGCGAGTG CCTGGAGTTG CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG
 ACGCTACAGC GCGCAGATCC TCCAAAGGCA CACGTTGCCC ACCACCACAT
 CTCTGACCGT GAGGCCACCC TGAGGTGCTG GGCCCTGGGC TTCTACCCTG
 CCGAGATCAC ACTGACCTGG CAGCGGGACG GGGAGGAACA GACCCAGGAC
 ACGGAGCTTG TGGAGACCAG GCCTGCAGGG GATGGAACCT TCCAGAAGTG
 GGCAGCTGTG GTGGTGCCTT CCGGAGAGGA GCAGAGATAT ACGTGCCATG
 TGCAACACGA AGGGCTGCCC CAGCCCCTCA CCCTGAGATG GGAGTCGTCT
 TCTCAGCCCA CCATCCCCAT TGTGGGCATC GTTGCTGGCC TGGCTGTCCT
 AGCAGTTGTG GTCACTGGAG CTGTGGTCGC TGCTGTAATG TGGAAGAGGA
 AGAGCTCAGC *   
>DL;IPD:MHC04810
IPD:MHC04810 Mafa-F*01:05 1010 bases
 ATGGCACCCC GAACCCTCCT CCTGGTGCTC TCAGGGGCCC TGGCCCTGAC
 CGAGACCTGG GCGGGCTCCC ACTCCTTGCG GTATTTTAGC ACCGCTGTGT
 CGCGGCCCGG CCGCAGGGAG CCTCAGTACA GGTACATTGC GGTGGAGTAC
 GTGGACGACA CGCAGTTCCT GCGGTTCGAC AGCGACGCCG CGATTCCGAG
 GATGGAGCCG CGGGCGCCGT GGGTGGAGCA AGAGGGGCCG CAGTATTGGG
 AGCGGACCAC AGGGTACGCC AAGGCCAACG CACGGACTGA CCGAGTGGCC
 CTGAGGAAGC TGCTCCTCCG CTACAACCAG AGCGAGGCAG GGTCTCACAC
 CCTCCAGGGA ATGAACGGCT GCGACATGGG GCCCGACGGA CGCCTCCTCC
 GCGGGTATCA CCAGCACGCC TACGACGGCA AGGATTACAT CTCCCTGAAC
 GAGGACCTGC GCTCCTGGAC CGCCGCGGAC ACGGTAGCTC GGATCACCCA
 GCGCTTCTAT GAGGCAGAGG AATATGCAGA GGAGTTCAGG ACCTACCTGG
 AGGGCGAGTG CCTGGAGTTG CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG
 ACGCTACAGC GCGCAGATCC TCCAAAGGCA CACGTTGTCC ACCACCCCAT
 CTCTGACCGT GAGGCCACCC TGAGGTGCTG GGCCCTGGGC TTCTACCCTG
 CCGAGATCAC ACTGACCTGG CAGCGGGACG GGGAGGAACA GACCCAGGAC
 ACGGAGCTTG TGGAGACCAG GCCTGCAGGG GATGGAACCT TCCAGAAGTG
 GGCAGCTGTG GTGGTGCCTT CCGGAGAGGA GCAGAGATAC ACGTGCCATG
 TGCAACACGA AGGGCTGCCC CAGCCCCTCA CCCTGAGATG GGAGTCGTCT
 TCTCAGCCCA CCATCCCCAT TGTGGGCATC GTTGCTGGCC TGGCTGTCCT
 AGCAGTTGTG GTTACTGGAG CTGTGGTCGC TGCTGTAATG TGGAGGAGAA
 AGAGCTCAGC *   
>DL;IPD:MHC04811
IPD:MHC04811 Mafa-F*01:06 1010 bases
 ATGGCGCCCC GAACCCTCCT CCTGGTGCTC TCAGGGGCCC TGGCCCTGAC
 CGAGACCTGG GCGGGCTCCC ACTCCTTGCG GTATTTTAGC ACCGCTGTGT
 CGCGGCCCGG CCGCAGGGAG CCTCGGTACA GGTACATCGC GGTGGAGTAC
 GTGGACGACA CGCAGTTCCT GCGGTTCGAC AGCGACGCCG CGATTCCGAG
 GATGGAGCCG CGGGCGCCGT GGGTGGAGCA AGAGGGGCCG CAGTATTGGG
 AGCGGACCAC AGGGTACGCC AAGGCCAACG CACGGACTGA CCGAGTGGCC
 CTGAGGAAGC TGCTCCTCCG CTACAACCAG AGCGAGGCCG GGTCTCACAC
 CCTCCAGGGA ATGAACGGCT GCGACATGGG GCCCGACGGA CGCCTCCTCC
 GCGGGTATCA CCAGCACGCC TACGACGGCA AGGATTACAT CTCCCTGAAC
 GAGGACCTGC GCTCCTGGAC CGCCGCGGAC ACGGTAGCTC GGATCACCCA
 GCGCTTCTAT GAGGCAGAGG AATATGCAGA GGAGTTCAGG ACCTACCTGG
 AGGGCGAGTG CCTGGAGTTG CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG
 ACGCTACAGC GCGCAGATCC TCCAAAGGCA CACGTTGCCC ACCACCCCAT
 CTCTGACCGT GAGGCCACCC TGAGGTGCTG GGCCCTGGGC TTCTACCCTG
 CCGAGATCAC ACTGACCTGG CAGCGGGACG GGGAGGAACA GACCCAGGAC
 ACGGAGCTTG TGGAGACCAG GCCTGCAGGG GATGGAACCT TCCAGAAGTG
 GGCAGCTGTG GTGGTGCCTT CCGGAGAGGA GCAGAGATAC ACGTGCCATG
 TGCAACACGA AGGGCTGCCC CAGCCCCTCA CCCTGAGATG GGAGTCGTCT
 TCTCAGCCCA CCATCCCCAT TGTGGGCATC GTTGCTGGCC TGGCTGTCCT
 AGCAGTTGTG GTCACTGGAG CTGTGGTCGC TGCTGTAATG TGGAAGAGGA
 AGAGCTCAGC *   
>DL;IPD:MHC04812
IPD:MHC04812 Mafa-F*01:07 1010 bases
 ATGGCACCCC GAACCCTCCT CCTGGTGCTC TCAGGGGCCC TGGCCCTGAC
 CGAGACCTGG GCGGGCTCCC ACTCCTTGCG GTATTTTAGC ACCGCTGTGT
 CGCGGCCCGG CCGCAGGGAG CCTCGGTACA GGTACATCGC GGTGGAGTAC
 GTGGACGACA CGCAGTTCCT GCGGTTCGAC AGCGACGCCG CGATTCCGAG
 GATGGAGCCG CGGGCGCTGT GGGTGGAGCA AGAGGGGCCG CAGTATTGGG
 AGCGGACCAC AGGGTACGCC AAGGCCAACG CACGGACTGA CCGAGTGGCC
 CTGAGGAAGC TGCTCCTCCG CTACAACCAG AGCGAGGCCG GGTCTCACAC
 CCTCCAGGGA ATGAACGGCT GCGACATGGG GCCCGACGGA CGCCTCCTCC
 GCGGGTATCA CCAGCACGCC TACGACGGCA AGGATTACAT CTCCCTGAAC
 GAGGACCTGC GCTCCTGGAC CGCCGCGGAC ACGGTAGCTC GGATCACCCA
 GCGCTTCTAT GAGGCAGAGG AATATGCAGA GGAGTTCAGG ACCTACCTGG
 AGGGCGAGTG CCTGGAGTTG CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG
 ACGCTACAGC GCGCAGATCC TCCAAAGGCA CACGTTGCCC ACCACCACAT
 CTCTGACCGT GAGGCCACCC TGAGGTGCTG GGCCCTGGGC TTCTACCCTG
 CCGAGATCAC ACTGACCTGG CAGCGGGACG GGGAGGAACA GACCCAGGAC
 ACGGAGCTTG TGGAGACCAG GCCTGCAGGG GATGGAACCT TCCAGAAGTG
 GGCAGCTGTG GTGGTGCCTT CCGGAGAGGA GCAGAGATAC ACGTGCCATG
 TGCAACACGA AGGGCTGCCC CAGCCCCTCA CCCTGAGATG GGAGTCGTCT
 TCTCAGCCCA CCATCCCCAT TGTGGGCATC GTTGCTGGCC TGGCTGTCCT
 AGCAGTTGTG GTCACTGGAG CTGTGGTCGC TGCTGTAATG TGGAAGAGGA
 AGAGCTCAGC *   
