>DL;IPD:MHC00344
IPD:MHC00344 Mafa-E*02:01 1065 bases
 CTACTTCTCC TGCTCTCGGC CCTTACCAAG ACCTGGGCGG GCTCCCACTC
 CTTGAAGTAT TTCCACACTT CCGTGTCCCG GCCCGGCCGC GGGGGGCCCC
 GCTTCATCTC AGTGGGCTAC GTGGACGACA CCCAGTTCGT GCGGTATGAC
 AGCGACGCCG CGAGTCAGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCA
 GGAGGGGCCG GAGTATTGGG ACCAGGAGAC ACGGAGCGCC AGGGACACCG
 CACAGACTTT CCGAGTGAAC CTGGAGACCC TGCGCGGCTA CTACAACCAG
 AGCGAGGCCG GGTCTCATAC CCTCCAGTGG ATGCATGGCT GCGACCTGGG
 ATCCGACGGG CGCTTCCTCC GCGGGTATGA ACAGTTCGCC TACGACGGCA
 AGGATTATCT CACCCTGAAT GAGGACCTGC GCTCCTGGTC CGCGGTGGAC
 ACGGCGGCTC AAATCTCCGA GCAAAAGTCA AATGATGGCT CTGAGGCTGA
 GCACCAGAGA GCCTACCTGG AAGACACATG CGTGGAGTGG CTCCACAGAT
 ACCTGGAGAA TGGGAAGGAG ACGCTGCAGC GCTCAGAACC CCCAAAGACA
 CACGTGACCC ACCACCCCGT CTCTGATCAT GAGGCCACCC TGAGGTGCTG
 GGCCCTGGGC TTCTATCCTG CGGAGATCAC AGTGACCTGG CAGCGGGATG
 GGGAGGACCA GACCCAGGAC ACGGAGCTTG TGGAGACCAG GCCTGCAGGG
 GATGGAACTT TCCAGAAGTG GGCAGCTGTG GTGGTACCTT CTGGAGAGGA
 GCAGAGATAC ACGTGCCATG TGCAGCATGA GGGGCTACCC GAGCCCCGAG
 CCCTGAGATG GGAGCCGTCT TCCCGGTCCA CCATCCCCAT CGTGGGCATC
 ATTGCTGGCC TGGTTCTCCT TGGAGCTGTG GTCACTGGAG CTGTGGTTGT
 TGCTGTGATG TGGAGGAGGA AGAGCTCAGG TAGAAAAGGA GGGAGCTACT
 CTCAGGCTTC GTGTAGCGAC AGTACCCAGG GATCTGATGA GTCTCTCACA
 GCTTGTAAAG CCTGA*   
>DL;IPD:MHC00345
IPD:MHC00345 Mafa-E*02:02 1065 bases
 CTACTTCTCC TGCTCTCGGC CCTTACCAAG ACCTGGGCGG GCTCCCACTC
 CTTGAAGTAT TTCCACACTT CCGTGTCCCG GCCCGGCCGC GGGGGGCCCC
 GCTTCATCTC AGTGGGCTAC GTGGACGACA CCCAGTTCGT GCGGTATGAC
 AGCGACGCCG CGAGTCAGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCA
 GGAGGGGCCG GAGTATTGGG ACCAGGAGAC ACGGAGCGCC AGGGACACCG
 CACAGACTTT CCGAGTGAAC CTGGAGACCC TGCGCGGCTA CTACAACCAG
 AGCGAGGCCG GGTCTCATAC CCTCCAGTGG ATGCATGGCT GCGACCTGGG
 ATCCGACGGG CGCTTCCTCC GCGGGTATGA ACAGTTCGCC TACGACGGCA
 AGGATTATCT CACCCTGAAT GAGGACCTGC GCTCCTGGTC CGCGGTGGAC
 ACGGCGGCTC AAATCTCCGA GCAAAAGTCA AATGATGGCT CTGAGGCTGA
 GCACCAGAGA GCCTACCTGG AAGACACATG CGTGGAGTGG CTCCACAGAT
 ACCTGGAGAA TGGGAAGGAG ACGCTGCAGC GCTCAGAACC CCCAAAGACA
 CACGTGACCC ACCACCCCGT CTCTGATCAT GAGGCCACCC TGAGGTGCTG
 GGCCCTGGGC TTCTATCCTG CGGAGATCAC AGTGACCTGG CAGCGGGATG
 GGGAGGACCA GACCCAGGAC ACGGAGCTTT TGGAGACCAG GCCTGCAGGG
 GATGGAACTT TCCAGAAGTG GGCAGCTGTG GTGGTACCTT CTGGAGAGGA
 GCAGAGATAC ACGTGCCATG TGCAGCATGA GGGGCTACCC GAGCCCCTCA
 CCCTGAGATG GGAGCCGTCT TCCCAGTCCA CCATCCCCAT CGTGGGCATC
 ATTGCTGGCC TGGTTCTCCT TGGAGCTGTG GTCACTGGAG CTGTGGTTGT
 TGCTGTGATG TGGAGGAGGA AGAGCTCAGG TAGAAAAGGA GGGAGCTACT
 CTCAGGCTTT GTGTAGCGAC AGTACCCAGG GATCTGATGA GTCTCTCACA
 GCTTGTAAAG CCTGA*   
>DL;IPD:MHC04237
IPD:MHC04237 Mafa-E*02:03 645 bases
 ATGGCACTAC GAACCCTACT TCTCCTGCTC TCGGCCCTTA CCAAGACCTG
 GGCGGGCTCC CACTCCTTGA AGTATTTCCA CACTTCCGTG TCCCGGCCCG
 GCCGCGGGGG GCCCCGCTTC ATCTCCGTGG GCTACGTGGA CGACACCCAG
 TTCGTGCGGT ATGACAGCGA CGCCGCGAGT CCGAGGATGG AGCCGCGGGC
 GCCGTGGGTG GAGCAGGAGG GGCCGGAGTA TTGGGACCAG GAGACACGGA
 GCGCCAGGGA CACCGCACAG ACTTTCCGAG TGAACCTGGA GACCCTGCGC
 GGCTACTACA ACCAGAGCGA GGCCGGGTCT CATACCCTCC AGTGGATGCA
 TGGCTGCGAC CTGGGGTCCG ACGGGCGCTT CCTCCGCGGG TATGAACAGT
 TCGCCTACGA CGGCAAGGAT TATCTCACCC TGAATGAGGA CCTGCGCTCC
 TGGTCCGCGG TGGACACGGC GGCTCAAATC TCCGAGCAAA AGTCAAATGA
 TGGCTCTGAG GCTGAGCACC AGAGAGCCTA CCTGGAAGAC ACATGCGTGG
 AGTGGCTCCA CAGATACCTG GAGAATGGGA AGGAGACGCT GCAGCGCTCG
 GAACCCCCAA AGACACACGT GACCCACCAC CCCGTCTCTG ATCAT*
>DL;IPD:MHC04238
IPD:MHC04238 Mafa-E*02:04 645 bases
 ATGGCACTAC GAACCCTACT TCTCCTGCTC TCGGCCCTTA CCAAGACCTG
 GGCGGGCTCC CACTCCTTGA AGTATTTCCA CACTTCCGTG TCCCGGCCCG
 GCCGCGGGGG GCCCCGCTTC ATCTCCGTGG GCTACGTGGA TGACACCCAG
 TTCGTGCGGT ATGACAGCGA CGCCGCGAGT CCGAGGATGG AGCCGCGGGC
 GCCGTGGGTG GAGCAGGAGG GGCCGGAGTA TTGGGACCAG GAGACACGGA
 GCGCCAGGGA CACCGCACAG ACTTTCCGAG TGAACCTGGA GACCCTGCGC
 GGCTACTACA ACCAGAGCGA GGCCGGGTCT CATACCCTCC AGTGGATGCA
 TGGCTGCGAC CTGGGGTCCG ACGGGCGCTT CCTCCGCGGG TATGAACAGT
 TCGCCTACGA CGGCAAGGAT TATCTCACCC TGAATGAGGA CCTGCGCTCC
 TGGTCCGCGG TGGACACGGC GGCTCAAATC TCCGAGCAAA AGTCAAATGA
 TGGCTCTGAG GCGGAGCACC AGAGAGCCTA CCTGGAAGAC ACATGCGTGG
 AGTGGCTCCA CAGATACCTG GAGAATGGGA AGGAGATGCT GCAGCGCTCA
 GAACCCCCAA AGACACACGT GACCCACCAC CCCGTCTCTG ATCAT*
>DL;IPD:MHC04239
IPD:MHC04239 Mafa-E*02:05N 643 bases
 ATGGCACTAC GAACCCTACT TCTCCTGCTC TCGGCCCTTA CCAAGACCTG
 GGCCGGCTCC CACTCCTTGA AGTATTTCCA CACTTCCGTG TCCCGGCCCG
 GCCGCGGGGA GCCCCGCTTC ATCTCCGTGG GCTACGTGGA CGACACCCAG
 TTCGTGCGGT ACGACAGCGA CGCCGCGAGT CCGAGGATGC AGCCGCGGGC
 GCTGTGGATG AAGCAGGAGG GGCCGGAGTA TTGGGAGCAG GAGACACGAA
 GCGCCAGGGA CACCGCATAG ACTTTCCGAG TGAACCTGAA TACCCTGCGC
 GGCTACTACA ACCAGAGCGA GGCCGCGTCT CATACCCTCC AGTGGATGTA
 TGGCTGCGAC CTGGGGCCCT ACGGGCGCTT CCTCCGCGGG TATGAACAGT
 TTGCCTACGG GCAAGGATTA TCTCACCCTG AATGAGGACC TGCGCTCCTG
 GTCCGCGGTG GACACGGCGG CTCAGATCTC TGCACAAAAG TCAAATGATG
 GCTCTGAGGT GGAGCACCAG AGAGCCTACC TGGAAGACAC ATGCGTGGAG
 TGGCTCCACA GATACCTGGA GAATGGGAAG GAGACGCTGC AGCGCTCGGA
 ATCCCCAAAG ACACACGTGA CCCACCACCC CATCTCTGAT CAT*
