>DL;IPD:MHC01316
IPD:MHC01316 Mafa-DPB1*01:01:01 259 bases
 MMVLQVSGTP QTVGLMALLM VLLTSVVQGR ATPENYLYQG RQECYAFNGT
 QRFLERHIYN REEYARFDSD VGEFRAVTEL GRPAVEYWNS QKDRLEEKRA
 VVDTVCRHNY ELDEAVTLQR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETTGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLITC GVGIFMHRRS
 KKVQRGSVX*    
>DL;IPD:MHC03726
IPD:MHC03726 Mafa-DPB1*01:01:02 259 bases
 MMVLQVSGTP QTVGLMALLM VLLTSVVQGR ATPENYLYQG RQECYAFNGT
 QRFLERHIYN REEYARFDSD VGEFRAVTEL GRPAVEYWNS QKDRLEEKRA
 VVDTVCRHNY ELDEAVTLQR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETTGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLITC GVGIFMHRRS
 KKVQRGSVX*    
>DL;IPD:MHC01211
IPD:MHC01211 Mafa-DPB1*01:02:01 259 bases
 MMVLQVSAAP RTVGLMALLM VLLTSVVQGR ATPENYLYQG RQECYAFNGT
 QRFLERYIYN REEYARFDSD VGEFRAVTEL GRPAVEYWNS QKDRLEEKRA
 VVDTMCRHNY ELDEAVTLQR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETTGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC GVGIFMHRRS
 KKVQRGSVX*    
>DL;IPD:MHC03741
IPD:MHC03741 Mafa-DPB1*01:02:02 259 bases
 MMVLQVSAAP RTVGLMALLM VLLTSVVQGR ATPENYLYQG RQECYAFNGT
 QRFLERYIYN REEYARFDSD VGEFRAVTEL GRPAVEYWNS QKDRLEEKRA
 VVDTMCRHNY ELDEAVTLQR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETTGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC GVGIFMHRRS
 KKVQRGSVX*    
>DL;IPD:MHC01317
IPD:MHC01317 Mafa-DPB1*01:03 88 bases
 ENYLYQGRQE CYAFNGTQRF LERYIYNREE YARFDSDVGE FRAVTELGRP
 AVEYWNSQKD RLEEKRAVVD TVCRHNYELD EAVTLQRR* 
>DL;IPD:MHC01319
IPD:MHC01319 Mafa-DPB1*01:04 88 bases
 ENYLYQGRQE CYAFNGTQRF LERYIYNREE YARFDSDVGE FRAVTELGRP
 AVEYWNSQKD FLEEKRAVVD TVCRHNYELD EAVTLQRR* 
>DL;IPD:MHC01320
IPD:MHC01320 Mafa-DPB1*01:05 258 bases
 MVLQVSGTPQ TVGLMALLMV LLTSVVQGRA TPENYLYQGR QECYAFNGTQ
 RFLERYIYNR EEYARFDSDV GEFRAVTELG RPAVEHWNSQ KDFLEEKRAV
 VDTVCRHNYE LDEAVTLQRR VQPRVNVSPS KKGPLQHHNL LVCHVTDFYP
 GSIQVRWFLN GQEETTGVVS TNLIRNGDWT FQILVMLEMT PQQGDVYTCQ
 VEHPSLDSPV TVEWKAQSDS ARSKTLTGAG GFVLGLITCG VGIFMHRRSK
 KVQRGSAX*    
>DL;IPD:MHC01321
IPD:MHC01321 Mafa-DPB1*01:06 88 bases
 ENYLYQGRQE CYAFNGTQRF LERYIYNREE YARFDSDVGE FRAVTELGRP
 AVEHWNSQKD FLEEKRAVVD TMCRHNYELD EAVTLQRR* 
>DL;IPD:MHC04123
IPD:MHC04123 Mafa-DPB1*01:07 259 bases
 MMVLQVSGTP QTVGLMALLM VLLTSVVQGR ATPENYLYQG RQECYAFNGT
 QRFLERHIYN REEYARFDSD VGEFRAVTEL GRPAVEYWNS QKDRLEEKRA
 VVDTVCRHNY ELDEAVTLQR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETAGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLITC GVGIFMHRRS
 KKVQRGSVX*    
>DL;IPD:MHC01322
IPD:MHC01322 Mafa-DPB1*02:01 88 bases
 ENYLYQGRQE CYAINGTQRF LERHIYNREE FMRFDSDAGE YRAVTEMGRP
 TAEYCNSQKD FLEEKRAEVD RVCRHNYEGH EAVTLRRR* 
>DL;IPD:MHC00273
IPD:MHC00273 Mafa-DPB1*02:02 259 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVRGR ATPENYLYQG RQECYAINGT
 QRFLERHIYN REEFMRFDSD AGEYRAVTEM GRPTAEYWNS QKDRLEEKRA
 EVDRVCRHNY EGHEAVTLRR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETAGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VMVEWKAQSD SARSKTLTGA GGFVLGLITC GVGIFMHRRS
 KKVQRGSVX*    
>DL;IPD:MHC01346
IPD:MHC01346 Mafa-DPB1*02:03 87 bases
 NYLYQGRQEC YAINGTQRFL ERHIYNREEF MRFDSDAGEY RAVTEMGRPT
 AEYWNSQKDR LEEKRSEVDR VCRHNYEGHE AVTLRRR* 
>DL;IPD:MHC03725
IPD:MHC03725 Mafa-DPB1*02:04 259 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVRGR ATPENYLYQG RQECYAINGT
 QRFLERHIYN REEFMRFDSD AGEYRAVTEM GRPSAEYWNS QKDRLEEKRA
 EVDRVCRHNY EGHEAVTLRR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETAGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VMVEWKAQSD SARSKTLTGA GGFVLGLITC GVGIFMHRRS
 KKVQRGSVX*    
>DL;IPD:MHC04124
IPD:MHC04124 Mafa-DPB1*02:05 259 bases
 MMVLQVSAAL RTVALTALLM VLLTSVVRGR ATPENYLYQG RQECYAINGT
 QRFLERHIYN REEFMRFDSD AGEYRAVTEM GRPTAEYWNS QKDRLEEKRA
 EVDRVCRHNY EGHEAVTLRR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETAGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VMVEWKAQSD SARSKTLTGA GGFVLGLITC GVGIFMHRRS
 KKVQRGSVX*    
>DL;IPD:MHC00274
IPD:MHC00274 Mafa-DPB1*03:01 259 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVRGR ATPENYLYQG RQECYAINGT
 QRFLERHIYN REEFMRFDSD VGEYRAVTEM GRPTAEYCNS QKDKLEEMRA
 VADRMCRHNY EVNEAVTLQR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETAGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTMEWKAQSD SARSKTLTGA GGFVLGLIIC GVGIFMHRRS
 KKVQRGSVX*    
>DL;IPD:MHC01323
IPD:MHC01323 Mafa-DPB1*03:02 88 bases
 ENYLYQGRQE CYAINGTQRF LERHIYNREE FMRFDSDVGE YRAVTEMGRP
 TAEYCNSQKD KLEEMRAVAD TVCRHNYEVN EAVTLQRR* 
>DL;IPD:MHC01174
IPD:MHC01174 Mafa-DPB1*03:03 259 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVRGR ATPENYLYQG RMECYAINGT
 QRFLERHIYN REEFMRFDSD VGEYRAVTEM GRPTAEYCNS QKDKLEEMRA
 VADTVCRHNY EVNEAVTLQR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETAGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTMEWKAQSD SARSKTLTGA GGFVLGLIIC GVGIFMHRRS
 KKVQRGSVX*    
>DL;IPD:MHC03727
IPD:MHC03727 Mafa-DPB1*03:04 259 bases
 MMVLQVSVVP GTVALTALLM VLLTSVVRGR ATPENYLYQG RMECYAINGT
 QRFLERHIYN REEFMRFDSD VGEYRAVTEM GRPTAEYCNS QKDKLEEMRA
 VADTVCRHNY EVNEAVTLQR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETAGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTMEWKAQSD SARSKTLTGA GGFVLGLIIC GVGIFMHRRS
 KKVQRGSVX*    
>DL;IPD:MHC01173
IPD:MHC01173 Mafa-DPB1*04:01 259 bases
 MMVLQVSGTP QTVGLMALLM VLLTSVVQGR ATPENYLYQV RQECYAFNGT
 QRYLNRQIYN REEFVRFDSD VGEYRAVTEL GRPTAEYWNS QKDILEENRA
 VVDRVCRHNY ELDEAVTLQR RVQPRVNVSP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETTGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLITC GVGIFMHRRS
 KKVQRGSAX*    
>DL;IPD:MHC01318
IPD:MHC01318 Mafa-DPB1*05:01 88 bases
 ENYLYQVRQE CYAFNGTQRF LERYIYNREE YARFDSDVGE FRAVTELGRP
 AVEYWNSQKD RLEEKRAVVD TVCRHNYELD EAVTLQRR* 
>DL;IPD:MHC03648
IPD:MHC03648 Mafa-DPB1*05:02 259 bases
 MMVLQVSGTP QTVGLMALLM VLLTSVVQGR ATPENYLYQV RQECYAFNGT
 QRFLERYIYN REEYARFDSD VGEFRAVTEL GRPTAEYWNS QKDRLEERRA
 VVDTMCRHNY ELDEAVTLQR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETAGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VMVEWKAQSD SARSKTLTGA GGFVLGLITC GVGIFMHRRS
 KKVQRGSVX*    
>DL;IPD:MHC01326
IPD:MHC01326 Mafa-DPB1*06:01 259 bases
 MMVLQVSGTP QTVGLMALLM VLLTSVVQGR ATPENYLFQL RQECYAFNGT
 QRYLERYLYN REEFVRFDSD VGEFRAVTEL GRPDAEYWNS QKDILEEMRA
 VTDTVCRHNY ELDEAVTLQR RVQPRVNVSP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETTGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLITC GVGIFMHRRS
 KKVQRGSAX*    
>DL;IPD:MHC01327
IPD:MHC01327 Mafa-DPB1*06:02 88 bases
 ENYLFQLRQE CYAFNGTQRY LERYLYNREE FVRFDSDVGE FRAVTELGRP
 DAEYWNSQKD ILEERRAVVD TMCRHNYELD EAVTLQRR* 
>DL;IPD:MHC01328
IPD:MHC01328 Mafa-DPB1*06:03 259 bases
 MMVLEVSAAP GTVGLMALLM VLLTSVVQGR ATPENYVFQG RQECYAFNGT
 QRYLERYIYN REEFVRFDSD VGEFREVTEL GRPDAEYWNS QKDLLEEMRA
 VVDTMCRYNY ELDEAVTLQR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETTGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC GVGIFMHRRR
 KKVQRGSVX*    
>DL;IPD:MHC01335
IPD:MHC01335 Mafa-DPB1*06:04 88 bases
 ENYVYQVRQE CYAFNGTQRY LERYIYNREE FVRFDSDVGE FRAVTELGRP
 DAEYWNSQKD ILEEKQAVAG TSCRHDYELD EAVTLQRR* 
>DL;IPD:MHC01336
IPD:MHC01336 Mafa-DPB1*06:05 88 bases
 ENYVYQLRQE CYAFNGTQRY LERYLYNREE FVRFDSDVGE FRAVTELGRP
 DAEYWNSQKD ILEEMRAVTD TVCRHNYELD EAVTLQRR* 
>DL;IPD:MHC01337
IPD:MHC01337 Mafa-DPB1*06:06:01 259 bases
 MMVLQVSGTP QTVGLMALLM VLLTSVVQGR ATPENYLYQL RQECYAFNGT
 QRYLERYLYN REEFVRFDSD VGEFRAVTEL GRPDAEYWNS QKDILEEMRA
 VTDTVCRHNY ELDEAVTLQR RVQPRVNVSP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETTGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLITC GVGIFMHRRS
 KKVQRGSAX*    
>DL;IPD:MHC05126
IPD:MHC05126 Mafa-DPB1*06:06:02 87 bases
 NYLYQLRQEC YAFNGTQRYL ERYLYNREEF VRFDSDVGEF RAVTELGRPD
 AEYWNSQKDI LEEMRAVTDT VCRHNYELDE AVTLQRR* 
>DL;IPD:MHC03676
IPD:MHC03676 Mafa-DPB1*06:07 87 bases
 NYLYQERQEC YAFNGTQRYL DRYIYNREEF VRFDSDVGEF RAVTELGRPD
 AEYWNSQKDF LEEKRAEVDT VCRHNYELDE AVTLQRR* 
>DL;IPD:MHC03728
IPD:MHC03728 Mafa-DPB1*06:08 259 bases
 MMVLQVSGTP QTVGLMALLM VLLTSVVQGR ATPENYLYQE RQECYAFNGT
 QRYLDRYIYN REEFVRFDSD VGEFRAVTEL GRPDAEYWNS QKDILEEKRA
 EVDTVCRHNY ELDEAVTLQR RVQPRVNVSP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETAGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTMEWKAQSD SARSKTLTGA GGFVLGLITC GVGIFMHRRS
 KKVQRGSVX*    
>DL;IPD:MHC01214
IPD:MHC01214 Mafa-DPB1*07:01 259 bases
 MMVLEVSAAP GTVGLMALLM VLLTSVVQGR ATPENYVFQG RQECYAFNGT
 QRYLERYIYN REEYVRFDSD VGEFRAVTEL GRPDAEYWNS QKDLLEEMRA
 VVDTMCRYNY ELDEAVTLQR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGNIQVRWFL NGQEETTGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC GVGIFMHRRR
 KKVQRGSVX*    
>DL;IPD:MHC01329
IPD:MHC01329 Mafa-DPB1*08:01 88 bases
 ENYVYQGRLE CYAFNGTQRY LERYIYNREE YALFDSDVGE FRAVTELGRP
 DAEYWNSQKD LLEEMRAVVD TMCRYNYELD EAVTLQRR* 
>DL;IPD:MHC01330
IPD:MHC01330 Mafa-DPB1*08:02 88 bases
 ENYVYQGRME CYAFNGTQRY LERYIYNREE YARFDSDVGE FRAVTELGRP
 DAEYWNSQKD ILEEKQAVAG TSCRHDYELD EAVTLQRR* 
>DL;IPD:MHC01216
IPD:MHC01216 Mafa-DPB1*08:03 88 bases
 ENYVYQGRME CYAFNGTQRY LERYIYNREE YALFDSDVGE FRAVTELGRP
 DAEYWNSQKD LLEEMRAVVD TMCRYNYELD EAVTLQRQ* 
>DL;IPD:MHC02061
IPD:MHC02061 Mafa-DPB1*08:04 259 bases
 MMVLQVSGTP QTVGLMALLM VLLTSVVQGR ATPENYVYQG RMECYAFNGT
 QRYLERYIYN REEYALFDSD VGEFRAVTEL GRPDAEYWNS QKDLLEEMRA
 VVDTMCRYNY ELDEAVTLQR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETTGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC GVGIFMHRRR
 NKVQRGSVX*    
>DL;IPD:MHC01333
IPD:MHC01333 Mafa-DPB1*09:01 88 bases
 ENYLLQVRQE CYAFNGTQRY LERHIYNREE HVRFDSDVGE FRAVTELGRP
 AAEYWNSQKD FLEEKRAEVD TVCRHNYELD EAVTLQRR* 
>DL;IPD:MHC01334
IPD:MHC01334 Mafa-DPB1*09:02 258 bases
 MVLQVSGTPQ TVGLMALLMV LLTSVVQGRA TPENYLLQIR DECYAFNGTQ
 RYLERHIYNR EEHVRFDSDV GEYRAVTELG RPDAEYWNSQ KDFLEEKRAE
 VDTVCRYNYE LDEAVTLQRR VQPRVNVSPS KKGPLQHHNL LVCHVTDFYP
 GSIQVRWFLN GQEETAGVVS TNLIRNGDWT FQILVMLEMT PQQGDVYTCQ
 VEHPSLDSPV TMEWKAQSDS ARSKTLTGVG GFVLGLITCG VGIFMHRRSK
 KVQRGSVX*    
>DL;IPD:MHC03678
IPD:MHC03678 Mafa-DPB1*09:03 87 bases
 NYLLQVRDDC YAFNGTQRYL QRHIYNREEH VRFDSDVGEF RAVTELGRPD
 AEYWNSQKDL LEEMRAVVDR VCRHNYELDE AVTLQRR* 
>DL;IPD:MHC01215
IPD:MHC01215 Mafa-DPB1*10:01 259 bases
 MMVLQVSGTP QTVGLMALLM VLLTSVVQGR ATPENYLYQG RQECYAFNGT
 QRYLERYIYN REEYARFDSD VGEFRAVTEL GRPDAEYWNS QKDRLEEKRA
 VVDTMCRHNY ELDEAVTLQR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETTGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC GVGIFMHRRS
 KKVQRGSVX*    
>DL;IPD:MHC01331
IPD:MHC01331 Mafa-DPB1*12:01 88 bases
 ENYVYQGRME CYVFNGTQRY LKRYIYNREE FMRFDSDAGE FRAVTELGRP
 IAESWNSQKD KLEEKRAVAG TGCRHNYQST EPVIRKRR* 
>DL;IPD:MHC01332
IPD:MHC01332 Mafa-DPB1*12:02 88 bases
 ENYVYQGRME CYVFNGTQRY LERYIYNWEE FVRFDSDAGE FRAVTELGRP
 IAEYWNSQKD KLEEKRAVAG TGCRHNYQST EPVIRKRR* 
>DL;IPD:MHC01324
IPD:MHC01324 Mafa-DPB1*15:01 259 bases
 MMVLQVSAAP GTVGLMALLM VLLTSVVQGR ATPENYLFQA RQECYAFNGT
 QRFLERYIYN REELLRFDSD VGEFRAVTEL GRPEAESWNS QKDTLEKKRA
 VVDTMCRHNY ELDEAVTLQR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSVQVRWFL NGQEETAGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC GVGIFMHRRS
 KKVQRGSVX*    
>DL;IPD:MHC01212
IPD:MHC01212 Mafa-DPB1*15:02 259 bases
 MMVLQVSAAP RTVGLMALLM VLLTSVVQGR ATPENYLFQA RQECYAFNGT
 QRYLERYIYN REELLRFDSD VGEFRAVTEL GRPEAESWNS QKDILEEKRA
 VAGTGCRHNY ELDEAVTLQR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSVQVRWFL NGQEETAGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC GVGIFMHRRS
 KKVQRGSVX*    
>DL;IPD:MHC01213
IPD:MHC01213 Mafa-DPB1*15:03 259 bases
 MMVLQVSAAP GTVGLMALLM VLLTSVVQGR ATPENYLFQA RQECYAFNGT
 QRYLERYIYN REELLRFDSD VGEFRAVTEL GRPEAESWNS QKDTLEKKRA
 AVDTMCRHNY ELDEAVTLQR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETAGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLITC GVGIFMHRRS
 KKVQRGSAX*    
>DL;IPD:MHC01325
IPD:MHC01325 Mafa-DPB1*15:04 260 bases
 MMVLQVSAAP GTVGLMALLM VLLTSVVQGR ATPENYLFQA RQECYAFNGT
 QRFLERYIYN REELLRFDSD VGEYRAVMTE LWRPEAESWN SQKDTLEKKR
 AAVDTMCRHN YELDEAVTLQ RRVQPRVNIA PSKKGPLQHH NLLICHVTDF
 YPGSIQVRWF LNGQEETAGV VSTNLIRNGD WTFQILVMLE MTPQQGDVYT
 CQVEHPSLDS PVTVEWKAQS DSARSKTLTG AGGFVLGLIT CGVGIFMHRR
 SKKVQRGSAX *   
>DL;IPD:MHC01171
IPD:MHC01171 Mafa-DPB1*15:05 259 bases
 MMVLQVSAAP RTVGLVALLM VLLTSVVQGR ATPENYLFQA RQECYAFNGT
 QRYLERYIYN REELLRFDSD VGEFRAVTEL GRPEAESWNS QKDTLEKKRA
 GVDTMCRHNY ELDEAVTLQR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSVQVRWFL NGQEETAGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC GVGIFMHRRS
 KKVQRGSVX*    
>DL;IPD:MHC01172
IPD:MHC01172 Mafa-DPB1*15:06 259 bases
 MMVLQVSAAP GTVGLMALLM VLLTSVVQGR ATPENYLFQA RQECYAFNGT
 QRFLERYIYN REELLRFDSD VGEYRAVTEL WRPEAESWNS QKDTLEKKRA
 VVDTMCRHNY ELDEAVTLQR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETAGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLITC GVGIFMHRRS
 KKVQRGSAX*    
>DL;IPD:MHC03671
IPD:MHC03671 Mafa-DPB1*15:07 87 bases
 NYLFQARKEC YAFNGTQRFL ERYIYNREEL LRFDSDVGEF RAVTELGRPE
 AESWNSQKDT LEKKRAVVDT MCRHNYELDE AVTLQRR* 
>DL;IPD:MHC04370
IPD:MHC04370 Mafa-DPB1*15:08 259 bases
 MMVLQVSAAP RTVGLMALLM VLLTSVVQGR ATPENYLFQA RQECYAFNGT
 QRYLERYIYN REELLRFDSD VGEFRAVTEL GRPEAESWNS QKDILEEKRA
 VAGTGCRHNY ELDEAVTLQR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSVQVRWFL NGQEETAGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC GVGIFRHRRS
 KKVQRGSVX*    
>DL;IPD:MHC05128
IPD:MHC05128 Mafa-DPB1*16:01 87 bases
 NYVYQSLTEC YEFNGTQRLL DRYIYNREEF VRFDSYVGEY RAVTELGRPT
 AEYWNSLEDY MEETRAAVDT VCRYNYELDE AVTLQRR* 
>DL;IPD:MHC03675
IPD:MHC03675 Mafa-DPB1*17:01 87 bases
 NYVYQRWYEC YAFNGTQRLL DRYMYNQEEF VRFDSDLGEF RAVTELGRPT
 AERWNSQKDI LERERASVDR VCRYNYELEE PLIRKRR* 
>DL;IPD:MHC01338
IPD:MHC01338 Mafa-DPB1*18:01 218 bases
 TSVVQGRATP ENYVCQRRFE CYAYNGTQRL LDRYIYNQEE YVRFDSDLRE
 FRAVTELGRP TAERWNRQDI LEQARAEVDR VCRHNYELAE PLIRKRRVQP
 RVNVSPSKKG PLQHHNLLVC HVTDFYPGSI QVRWFLNGQE ETAGVVSTNL
 IRNGDWTFQI LVMLEMTPQQ GDVYTCQVEH PSLDSPVTVE WKAQSDSARS
 KTLTGAGGFV LGLITCGV*   
>DL;IPD:MHC01345
IPD:MHC01345 Mafa-DPB1*18:02 87 bases
 ENYVCQRRFE CYAYNGTQRL LDRYIYNQEE YVRFDSDLRE FRAVTELGQP
 TAERWNRQDI LEQARAEVDR VCRHNYELAE PLIRKRR* 
>DL;IPD:MHC01339
IPD:MHC01339 Mafa-DPB1*19:01 87 bases
 ENYVYQRRFE CYAFNGTQRL LDRFIYNQEE YVRFDSDLGE FRAVTELGRP
 TAEYWNRQDS LEQERAEVDR VCRHNYELDE AVTLKRR* 
>DL;IPD:MHC01340
IPD:MHC01340 Mafa-DPB1*19:02 87 bases
 ENYVYQRRFE CYAFNGTQRL LDRFIYNQEE FVRFDSDLGE FRAVMELGRP
 TAEYWNRQDS LEQERAEVDR VCRHNYELDE AVTLKRR* 
>DL;IPD:MHC01341
IPD:MHC01341 Mafa-DPB1*19:03 258 bases
 MMVLPVSGAP QTVTLTALLM VLLTSVVQGT ATPENYVYQR RFECYAFNGT
 QRLLDRFIYN QEEFVRFDSD LGEFRAVTEL GRPTAEYWNR QDSLEQERAE
 VDRVCRHNYE LDEAVTLKRR VQPRVNVSPS KKGPLQHHNL LVCHVTDFYP
 GSIQVRWFLN GQEETAGVVS TNLIRNGDWT FQILVMLEMT PQQGDVYTCQ
 VEHPSLDSPV TMEWKAQSDS ARSKTLTGAG GFVLGLIICG VGIFMHRRSK
 KVQRGSVX*    
>DL;IPD:MHC01342
IPD:MHC01342 Mafa-DPB1*19:04 87 bases
 ENYVYQRRSE CYAFNGTQRL LDRFIYNQEE FVRFDSDLGE FRAVTELGRP
 TAEYWNRQDT LEQERAEVDR VCRHNYELDE AVTLKRR* 
>DL;IPD:MHC01343
IPD:MHC01343 Mafa-DPB1*19:05 87 bases
 ENYVYQRRSE CYAFNGTQRL LDRFIYNQEE FVRFDSDLGE FRAVTELGRP
 NAEYWNRQDT LEQERAEVDR VCRHNYELDE AVTLKRR* 
>DL;IPD:MHC01344
IPD:MHC01344 Mafa-DPB1*19:06 87 bases
 ENYVYQRRSE CYAFNGTQRL LDRFIYNQEE YVRFDSDLGE FRAVTELGRP
 DAEYWNRQDT LEQERAEVDR VCRHNYELDE AVTLKRR* 
>DL;IPD:MHC01618
IPD:MHC01618 Mafa-DPB1*20:01 259 bases
 MVVLPVSGAP WTVTLTALLM VLLTSVVQGR ATPENYVYQR RYECYAFNGT
 QRLLDRSIYN QEEFVRFDSD LGEFRAVTEL GRPAAERWNS QKDILERERA
 SVDRVCRYNY ELNEAVTLKR RVQPRVNVSP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETAGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLITC GVGIFMHRRS
 KKVQRGSAX*    
>DL;IPD:MHC04433
IPD:MHC04433 Mafa-DPB1*21:01 218 bases
 TSVVQGRATP ENYVYQRRYE CYAFNGTQRL LDRSIYNQEE FVRFDSDLGE
 FRAVTELGRP AAERWNRQDN LERERAEVDR VCRHNYELNE AVTLKRRVQP
 RVNVSPSKKG PLQHHNLLVC HVTDFYPGSI QVRWFLNGQE ETAGVVSTNL
 IRNGDWTFQI LVMLEMTPQQ GDVYTCQVEH PSLDSPVTVE WKAQSDSARS
 KTLTGAGGFV LGLITCGV*   
