>DL;IPD:MHC01071
IPD:MHC01071 Mafu-DRB*W1:01 237 bases
 TTAGAGTACT GTAAGTTTGA GTGCCATTTC TTCAATGGGA CGGAGCGGGT
 GCTGAACCTG ATCAGATACT TCTATAACCA AGAGGAGTAC GTGCGCTACG
 ACAGCGACGT CGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCAAGTACT GGAACGGCCA GAAGGACCTC CTGGAGCAGA GGCGGGCCGA
 GGTGGACACC TACTGCAGAC ACAACTACCG GGTTGTT* 
>DL;IPD:MHC01072
IPD:MHC01072 Mafu-DRB*W1:02 237 bases
 TTAGAGTACT GTAAGTTTGA GTGCCATTTC TTCAATGGGA CGGAGCGGGT
 GCAGTACCTG ATCAGATACT TCTATAACCA AGAGGAGTAC GTGCGCTACG
 ACAGCGACGT CGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCAAGTACT GGAACGGCCA GAAGGACCTC CTGGAGCAGA GGCGGGCCGA
 GGTGGACACC TACTGCAGAC ACAACTACCG GGTTGGT* 
>DL;IPD:MHC01073
IPD:MHC01073 Mafu-DRB*W25:01 237 bases
 TTGGAGCAGG TTAAGTATGA GTGTCATTTC TTCAATGGGA CGGAGCGGGT
 GCGGTTCCTG GAGAGACACT TCTATAACCA GGAGGAGAAC CTGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCGAGTCCT GGAACAGCCA GAAGGACTTC CTGGAAGACA GGCGGGCCTC
 GGTGGACACC TTCTGCAGAT ACAACTACGG GGTTGGT* 
>DL;IPD:MHC01082
IPD:MHC01082 Mafu-DRB*W25:02 237 bases
 TTGGAGCAGG CTAAGGTTGA GTGTCACTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTCCTG GAGAGACACT TCTATAACCA GGAGGAGTTG GTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCGTAGC
 GCCGAGTCCT GGAACAGTCG GAAGGACGTC CTGGAGCAGG CGCGGACCGC
 AGCGGACACC TACTGCAGAC ACAACTACGG GGCTGTG* 
>DL;IPD:MHC01084
IPD:MHC01084 Mafu-DRB*W25:03 237 bases
 TTGGAGCAGG CTAAGTTTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTCCTG GAGAGACACT TCTATAACCA GGAGGAGTTC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGA CGGAGCTGGG GCGGCCTGTC
 GCCGAGTCCT GGAACAGCCA GAAGGACTTC CTGGAGCAGA AGCGGGCCGC
 GGTGGACACC TACTGCAGAC ACAACTACGG GGTTGGT* 
>DL;IPD:MHC02770
IPD:MHC02770 Mafu-DRB*W31:01 234 bases
 TTGTGGCAGG CTAAGGGTGA GTGTCATTTC TTCAATGGGA CTGAGCGGGT
 GCGGTACCTG GAGAGATACT TCTATAACCA GGAGGAGTTC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCGAGTACT GGAACAGCCA GAAGGACCTC CTGGAGCGGA GGCGGGCCGT
 GGTGGACACC TGCAGATACG ACTACTGGGT TGGT* 
>DL;IPD:MHC01085
IPD:MHC01085 Mafu-DRB*W3:01 237 bases
 TTGGAGCAGG CTAAACGTGA GTGTCATTTC TTCAATGGGA CGGAGCGGGT
 GCGGTTCCTG GACAGATACT TCCATAACCA GGAGGAGTAC GCGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGA CGGAGCTGGG GCGGCGTAGC
 GCGGAGTACT GGAACGGCCA GAAGGACTTT CTGGAGCAGG CGCGGACCGC
 GGTGGACAAC TACTGCAGAC ACAACTACGG GGTTGGC* 
>DL;IPD:MHC01086
IPD:MHC01086 Mafu-DRB*W3:02 237 bases
 TTGGAGCAGG CTAAACGTGA GTGTCATTTC TTCAATGGGA CGGAGCGGGT
 GCGGTTCCTG GACAGATACT TCCATAACCA GGAGGAGTAC GCGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCGTAGC
 GCGGAGTACT GGAACGGCCA GAAGGACTTT CTGGAGCAGG CGCGGACCGC
 GGTGGACAAC TACTGCAGAC ACAACTACGG GGTTGGC* 
>DL;IPD:MHC01077
IPD:MHC01077 Mafu-DRB*W3:03 237 bases
 TTGGAGCAGG CTAAGTCTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTCCTG GATAGATACT TCCATAACCA GGAGGAGTTG GTGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGT CGGAGCTGGG GCGGCCTGAA
 GCCCAGTCCT GGAACAGCCG GAAGGACATC CTGGAGCAGA GGCGGGCCGA
 GGTGGACACC TACTGCAGAC ACAACTACGG GGTTTTT* 
>DL;IPD:MHC01074
IPD:MHC01074 Mafu-DRB*W4:01 237 bases
 TTGGAGCACG TTAAGTCTGA GTGTCATTTC TTCAATGGGA CGGAGCGGGT
 GCGGTTCCTG GAGAGACACT TCTATAACCA GGAGGAGTTC CTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAA
 GCCCAGTCCT GGAACAGCCA GAAGGACTTC CTGGAGCAGA AGCGGGGCCA
 GGTGGACAAC TACTGCAGAT ACAACTACGG GGTTGGT* 
>DL;IPD:MHC01078
IPD:MHC01078 Mafu-DRB*W4:02 237 bases
 TTGGAGCAGT TTAAGCCTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTCCTG GAGAGACACT TCTATAACCA GGAGGAGTTC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGT CGGAGCTGGG GCGGCCTGAC
 GCCCAGTCCT GGAACAGCCA GAAGGACTTC CTGGAGCAGA GGCGGGCCGC
 GGTGGACACC TTCTGCAGAC ACAACTACGG GGTTGTG* 
>DL;IPD:MHC01076
IPD:MHC01076 Mafu-DRB*W60:01 237 bases
 TCTGGACAGG CTAAGTCTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTCCTG GATAGATACT TCTATAACCA GGAGGAGTTC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGT CGGAGCTGGG GCGGCCTGAC
 GCCGAGTCCT GGAACAGCCA GAAGGACTTC CTGGAGCAGA GGCGGGCCGA
 GGTGGACACC TACTGCAGAC ACAACTACGG GGTTGTT* 
>DL;IPD:MHC01087
IPD:MHC01087 Mafu-DRB*W60:02 237 bases
 TCTGGACAGG CTAAGTCTGA GTGTCATTTC TTCAATGGGA CGGAGCGGGT
 GCGGTTCCTG GACAGATACT TCTATAACCA GGAGGAGTTC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGA CGGAGCTGGG GCGGCCTATC
 GCCGAGTACT GGAACGGCCA GAAGGACTTT CTGGAGCAGA CGCGGACCGC
 GGTGGACAAC TACTGCAGAC ACAACTACCG GGTTGGT* 
>DL;IPD:MHC01088
IPD:MHC01088 Mafu-DRB*W60:03 237 bases
 TCTGGACAGG CTAAGTCTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTCCTG GACAGATACT TCTATAACCA GGAGGAGTAC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCGAGTACT GGAACAGCCA GAAGGACTTC CTGGAGCAGA AGCGGGCCCC
 GGTGGACAAT TACTGCAGAC ACAACTACCG GGTTGGT* 
>DL;IPD:MHC01092
IPD:MHC01092 Mafu-DRB*W61:01 237 bases
 TTGGGGCAGG CTAAGTCTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTACCTG GACAGATACT TCCATAACCA GGAGGAGTAC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCGAGAACT GGAACAGCCG GAAGGACATC CTGGAAGACC AGCGGGCCTC
 GGTGGACACC TACTGCAGAC ACAACTACGG GGTTGGT* 
>DL;IPD:MHC01093
IPD:MHC01093 Mafu-DRB*W61:02 237 bases
 TTGGGGCAGG CTAAGTCTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTACCTG GACAGATACT TCCATAACCA GGAGGAGAAC CTGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCGAGAACT GGAACAGCCG GAAGGACATC CTGGAAGACC AGCGGGCCGC
 GGTGGACACC TACTGCAGAC ACAACTACGG GGTTGTG* 
>DL;IPD:MHC01094
IPD:MHC01094 Mafu-DRB*W62:01 237 bases
 TTGGAGCAGG TTAAACATGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTACCTG GACAGATACT TCTATAACCA GGAGGAGTAC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCGAGTACT GGAACGGCCA GGAGGACATC CTGGAGCAGA AGCGGGGCCA
 GGTGGACAAC TACTGCAGAC ACAACTACGG GGTTTTT* 
>DL;IPD:MHC01080
IPD:MHC01080 Mafu-DRB*W6:01 237 bases
 TTGAAGCAGG CTAAGGCTGA GTGTCACTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTCCTG GAGAGACACT TCTATAACCA GGAGGAGTAC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGA CGGAGCTGGG GCGGCGTAGC
 GCCGAGTACT TCAACAGCCA GAAGGGCTAC CTGGAGCAGG CGCGGGCCGC
 GGTGGACACC TACTGCAGAC ACAACTACGG GGTTGGT* 
>DL;IPD:MHC01081
IPD:MHC01081 Mafu-DRB*W6:02 237 bases
 TTGAAGCAGG CTAAGGCTGA GTGTCACTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTCCTG GAGAGACACT TCTATAACCA GGAGGAGTAC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCGTAGC
 GCGGAGTACT GGAACAGCCA GAAGGACATC CTGGAAGACA GGCGGGCCGC
 GGTGGACACC TACTGCAGAC ACAACTACCG GATTGGT* 
>DL;IPD:MHC01083
IPD:MHC01083 Mafu-DRB*W6:03 237 bases
 TTGAAGCAGG CTAAGGCTGA GTGTCACTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTCCTG GAGAGACACT TCTATAACCA GGAGGAGTAC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCGTGAC
 GCCGAGTACT GGAACAGCCA GAAGGACTTC CTGGAACACA CGCGGGCCGC
 GGTGGACACC TACTGCAGAC ACAACTACGG GGTTGGT* 
>DL;IPD:MHC01069
IPD:MHC01069 Mafu-DRB1*03:01 237 bases
 TTGGAGTACT CTACATCTGA GTGTCACTTC TTCAATGGGA CGGAGCGGGT
 GCGGTACCTG GACAGATACT TCTATAACCA GGAGGAGTAC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCGAGTACT GGAACGGCCA GAAGGACATC CTGGAGCAGA AGCGGGGCCA
 GGTGGACAAT TACTGCAGAC ACAACTACCG GGTTGGT* 
>DL;IPD:MHC01070
IPD:MHC01070 Mafu-DRB1*03:02 237 bases
 TTGGAGTACT CTACATCTGA GTGTCACTTC TTCAACGGGA CGGAGCGGGT
 GCGGTACCTG GACAGATACT TCTATAACCA GGAGGAGTAC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGT CGGAGCTGGG GCGGCCTGAC
 GCCGAGTACT TCAACAGCCA GAAGGACATC CTGGAGCAGA AGCGGGCCCG
 GGTGGACAAT TACTGCAGAC ACAACTACCG GGTTGGT* 
>DL;IPD:MHC01068
IPD:MHC01068 Mafu-DRB1*10:01 237 bases
 TTGGAATACG TTAAGTTTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTCCTG ATCAGAGTCT TCCATAACCG AGAGGAGTAC GCGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGA CGGAGCTGGG GCGGCCTGCA
 GCCGAGTACT TGAACAGTCA GAAGGACTTC CTGGAGGAGA AGCGGGCCGC
 GGTGGACACC TACTGCAGAC ACAACTACGG GGTTGTG* 
>DL;IPD:MHC01089
IPD:MHC01089 Mafu-DRB1*10:02 237 bases
 TTGGAGCAGG TTAAGTTTGA GTGTCATTTC TTCAATGGGA CGGAGCGGGT
 GCGGTTCCTG GAGAGACGCG TCCATAACCA AGAGGAGTAC GCGCGCTTCG
 ACAGCGACGT CGGGGAGTAC CGGGCGGTGA CAGAGCTGGG GCGGCCTGAC
 GCCGAGTACT GGAACGGCCA GAAGGACCTC CTGGAAGACA GGCGGGCCTC
 GGTGGACAAC TACTGCAGAC ACAACTACGG GGTTGGT* 
>DL;IPD:MHC01090
IPD:MHC01090 Mafu-DRB1*10:03 237 bases
 TTGGAGCAGG TTAAGTTTGA GTGTCATTTC TTCAATGGGA CGGAGCGGGT
 GCGGTTCCTG GAGAGACGCG TCCATAACCA AGAGGAGTAC GCGCGCTTCG
 ACAGCGACGT CGGGGAGTAC CGGGCGGTGA CAGAGCTGGG GCGGCCTGAC
 GCCGAGTACT GGAACGGCCA GAAGGACCTC CTGGAGCAGA GGCGGGCCGA
 GGTGGACACC GTGTGCAGAC ACAACTACGG GGTTGGT* 
>DL;IPD:MHC01091
IPD:MHC01091 Mafu-DRB1*10:04 237 bases
 TTGGAGCAGG CTAAGGTTGA GTGTCATTTC TTCAACGGGA CAGAGCGGGT
 GCAGTTATTG GAGAGACGCG TCCATAACCA GGAAGAGTAC GCGCGCTACG
 ACAGCGACGT GGGGGAGTAC CGGGCCGTCA CGGAGCTGGG GCGGCCTGAC
 GCCGAGTACT GGAACAGCCA GAAGGACCTC CTGGAGCAGA GGCGGGCCGC
 GGTGGACACC TACTGCAGAC ACAACTACGG GGTTGGT* 
>DL;IPD:MHC01079
IPD:MHC01079 Mafu-DRB3*04:01 237 bases
 TTGGAGCAGG GTAAGTCTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTACCTG CAGAGACACT TCTATAACCA GGAGGAGTTC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGT CGGAGCTGGG GCGGCCTGTC
 GCCGAGTCCT GGAACAGCCA GAAGGACTAC CTGGAGCAGA GGCGGGCCGC
 GGTGGACAAC TACTGCAGAC ACAACTACCA GGTTGGT* 
