>DL;IPD:MHC04403
IPD:MHC04403 Male-DRB1*03:01 219 bases
 CGTTTCTTGG AGTACTCTAC ATCTGAGTGT CACTTCTTCA ACGGGATGGA
 GCGGGTGCGG TTCCTGGACA GATACTTCTA TAACCAGGAG GAGTACGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTGTCGGA GCTGGGGCGG
 CGTAGCGCGG AGTACTGGAA CAGCCGGAAG GACATCCTGG AAGACGAGCG
 GGCCGCGGTG GACACCTAC*   
>DL;IPD:MHC04404
IPD:MHC04404 Male-DRB1*04:01 219 bases
 CGTTTCTTGG AGCAGGTTAA ACATGAGTGT CACTTCTTCA ATGGGACGGA
 GCGGGTGCGG TTCCTGGAGA GATACTTCTA TAACCAGGAG GAGTACGTGC
 GCTTCGACAG CGACGTGGGG GAGCACCGGG CGGTGACGGA GCTGGGGCGG
 CCTAGCGCCG AGTACTGGAA CAGCCAAAAG GACATCCTGG AAGACCAGCG
 GGCCGCGGTG GACACCTAC*   
