>DL;IPD:MHC00378
IPD:MHC00378 Mamu-DQA1*01:02 768 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTCGCCC TGACCACCAT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT CGCTGACCAT GTTGCCTCTT
 GCGGTGTAAA CTTGTACCAG ACTTACGGTC TCTCTGGCCA GTTCACCCAT
 GAATTTGATG GAGATGAGCA GTTCTACGTG GACCTGAGGA GGAAGGAGAC
 AGCCTGGCGA TGGCCTGAGT TAAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGTTAAAAC ACAACTTGAA CATCGTGACT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCCG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CACTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCGCTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAGG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCGGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG
 TGGGCACTGT CTTCATCATT CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC00379
IPD:MHC00379 Mamu-DQA1*01:04:01 768 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTCGCCC TGACCACCGT
 GATGAGCCCC TGTGGAGGTG AAGACATTGT GGCTGACCAC GTTGCCTCTT
 GCGGTGTAAA CTTGTACCAG TCTTACGGTC CCTCTGGCCA GTACACCCAT
 GAATTTGACG GAGACGAGCA GTTCTACGTG GACCTGGGGA GGAAGGAGAC
 GGCCTGGCGA TGGCCTGAGT TAAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT ACAGTAAAAT ACAACTTGAA CATCATGACT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCCG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CACTGGGTCA GCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAGT
 GGGCGCTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCATCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAGG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCGGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG
 TGGGCACTGT CTTCATCATT CAAGGCCTAC GTTCAGTTGG TGCTTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC05130
IPD:MHC05130 Mamu-DQA1*01:04:02 249 bases
 CTGACCATGT TGCCTCTTGC GGTGTAAACT TGTACCAGTC TTACGGTCCC
 TCTGGCCAGT ACACCCATGA ATTTGACGGA GACGAGCAGT TCTACGTGGA
 CCTGGGGAGG AAGGAGACGG CCTGGCGATG GCCTGAGTTA AGCAAATTTG
 GAGGTTTTGA CCCGCAGGGT GCACTGAGAA ACTTGGCTAC AGTAAAATAC
 AACTTGAACA TCATGACTAA ACGCTACAAC TCTACCGCTG CTACCAATG*
>DL;IPD:MHC00380
IPD:MHC00380 Mamu-DQA1*01:05:01 768 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTCGTTC TGACCGCTGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT CGCTGACCAC GTTGCCTCTT
 GCGGTGTAAA CTTGTACCAG ACTTACGGTC TTTCTGGCCA GTACACCCAC
 GAATTTGACG GAGACGAGCA GTTCTACGTG GACCTGGAGA GGAAGGAGAC
 GGCATGGCGA TGGCCTGAGT TAAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGTCAAAAC ACAACTTGAA TATCATGACT
 AAACGCTACA ACTCTACCGC TGCTATCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CGCTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCACTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAGG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG
 TGGGCACTGT CTTCATCATT CAAGGCCTAC GTTCAGTTGG TGCTTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC05059
IPD:MHC05059 Mamu-DQA1*01:05:03 683 bases
 GAGGTGAAGA CATAGTGGCT GACCACGTTG CCTCTTGCGG TGTAAACTTG
 TACCAGACTT ACGGTCTTTC TGGCCAGTAC ACCCACGAAT TTGACGGAGA
 CGAGCAGTTC TACGTGGACC TGGAGAGGAA GGAGACGGCA TGGCGATGGC
 CTGAGTTAAG CAAATTTGGA GGTTTTGACC CGCAGGGTGC ACTGAGAAAC
 TTGGCTGTGT CAAAACACAA CTTGAATATC ATGACTAAAC GCTACAACTC
 TACCGCTGCT ATCAATGAGG TTCCTGAGGT CACAGTGTTT TCCAAGTCTC
 CCGTGACGCT GGGTCACCCC AACACCCTCA TCTGTCTTGT GGACAACATC
 TTTCCTCCTG TGGTGAACAT CACATGGTTG AGCAATGGGC ACTCAGTCAC
 AGAAGGGGTT TCTGAGACCA GCTTCCTCTC CAAGAGTGAT CATTCCTTCT
 TCAAGATCAG TTACCTCACC TTCCTCCCTT CTGCTGATGA GATTTATGAC
 TGCAGGGTGG AGCACTGGGG CCTGGACGAG CCTCTTCTGA AACACTGGGA
 GCCTGAGATT CCAGCGCCCA TGTCAGAGCT CACAGAGACT GTGGTCTGCG
 CCCTGGGGTT GTCTGTGGGC CTCGTGGGCA TTGTGGTGGG CACTGTCTTC
 ATCATTCAGG GCCTACGTTC AGTTGGTGCC TCC* 
>DL;IPD:MHC00382
IPD:MHC00382 Mamu-DQA1*01:06 768 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTCGTTC TGACCGCTGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT CGCTGACCAC GTTGCCTCTT
 GCGGTGTAAA CTTGTACCAG ACTTACGGTC TTTCTGGCCA GTACACCCAC
 GAATTTGATG GAGACGAGCG GTTCTACGTG GACCTGGAGA GGAAGGAGAC
 GGCCTGGCGA TGGCCTGAGT TAAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGTTAAAAC ACACCTTGAA CATCGTGACT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA TGCTGGGTCA GCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCGCTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAGG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCAGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG
 TGGGCACTGT CTTCATCATT CAAGGCCTAC GTTCAGTTGG TGCTTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC00383
IPD:MHC00383 Mamu-DQA1*01:07 226 bases
 CTGACCACGT TGCCTCTTGC GGTGTAAACT TGTACCAGAC TTACGGTCTT
 TCTGGCCAGT ACACCCACGA ATTTGATGGA GACGAGCGGT TCTACGTGGA
 CCTGGAGAGG AAGGAGACGG CCTGGCGATG GCCTGAGTTA AGCAAATTTG
 GAGGTTTTGA CCCGCAGGGT GCACTGAGAA ACTTGGCTGT GTCAAAACAC
 AACTTGAATA TCATGACTAA ACGCTA*  
>DL;IPD:MHC00384
IPD:MHC00384 Mamu-DQA1*01:08 683 bases
 GAGGTGAAGA CATAGTGGCT GACCACGTTG CCTCTTGTGG TGTAAACTTG
 TACCAGTCTT ACGGTCCCTC TGGCCAGTTC ACCCATGAAT TTGATGGGGA
 CGAGCAGTTC TACGTGGACC TGGGGAGGAA GGAGACGGCC TGGCGATGGC
 CTGAGTTAAG CAAATTTGGA GGTTTTGACC CGCAGGGTGC ACTGAGAAAC
 TTGGCTGCGG CAAAACACAA CTTGAACATC TTGACTAAAC GCTACAACTT
 CACCGCTGCT ACCAATGAGG TTCCCGAGGT CACAGTGTTT TCCAAGTCTC
 CCGTGACGCT GGGTCAGCCC AATACCCTCA TCTGTCTTGT GGACAACATC
 TTTCCTCCTG TGGTGAACAT CACATGGTTG AGCAATGGGC GCTCAGTCAC
 AGAAGGGGTT TCTGAGACCA GCTTCCTCTC CAAGAGTGAT CATTCCTTCT
 TCAAGATCAG TTACCTCACC TTCCTCCCTT CTGCTGATGA GATTTATGAC
 TGCAGGGTGG AGCACTGGGG CCTGGACGAG CCTCTTCTGA AACACTGGGA
 GCCGGAGATT CCAGCGCCCA TGTCAGAGCT CACAGAGACT GTGGTCTGCA
 CCCTGGGGTT GTCTGTGGGC CTCGTGGGCA TTGTGGTGGG CACTGTCTTC
 ATCATTCAAG GCCTACGTTC AGTTGGTGCC TCC* 
>DL;IPD:MHC00381
IPD:MHC00381 Mamu-DQA1*01:09 768 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTCGTTC TGACCGCTGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT CGCTGACCAC GTTGCCTCTT
 GCGGTGTAAA CTTGTACCAG ACTTACGGTC TTTCTGGCCA GTACACCCAC
 GAATTTGATG GAGACGAGCA GTTCTACGTG GACCTGGAGA GGAAGGAGAC
 GGCATGGCGA TGGCCTGAGT TAAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGTCAAAAC ACAACTTGAA TATCATGACT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CGCTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCACTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAGG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCTTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG
 TGGGCACTGT CTTCATCATT CAAGGCCTAC GTTCAGTTGG TGCTTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC00385
IPD:MHC00385 Mamu-DQA1*05:01 185 bases
 TCTTACGGTT TCTCTGGCCA GTTCACCCAT GAATTTGATG GAGATGAGCA
 GTTCTACGTG GACCTGGAGA GGAAGGAGAC TGTCTGGCAG TTGCCTGTTC
 TCAGCCAATT TAGTTTCGAC GCGCAATTTG CACTGACAAA CATTGCTGTG
 GGAAAACAGA ACTTGAACTA CCTGATGAAA CAGTC* 
>DL;IPD:MHC00386
IPD:MHC00386 Mamu-DQA1*05:02 183 bases
 TCTTACGGTT TCTCTGGCCA GTACTCCCAT GAATTTGATG GAGATGAGCA
 GTTCTACGTG GACCTGGAGA GGAAGGAGAC TGTCTGGCAG TTGCCTGTTC
 TCAGCCAATT TAGTTTCGAC GCGCAATTTG CACTGACAAA CATTGCTGTG
 GGAAAACAGA ACTTGAACTA CCTGATGAAA CAG* 
>DL;IPD:MHC00387
IPD:MHC00387 Mamu-DQA1*05:03 176 bases
 TTCTCTGGCC AGTACTCCCA TGAATTTGAC GGAGATGAGC AGTTCTACGT
 GGACCTGGAG AGGAAGGAGA CTGTCTGGCG GTTGCCTGTT CTCAGCCAAT
 TTAGTTTCGA CGCGCAATTT GCACTGACAA ACATTGCCGT GGGAAAACAG
 AACTTGAACT ACCTGATGAA ACAGTC*  
>DL;IPD:MHC01276
IPD:MHC01276 Mamu-DQA1*05:04 765 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTTGCCC TGACCACCGT
 GATGAGCTCC TGTGGAGGTG AAGACATTGT GGCTGACCAC CTCGCCTCTT
 ACGGTGTGAA CTTCTACCAG TCTTACGGTC TTTCTGGCCA GTACTCCCAT
 GAATTTGATG GAGACGAGCA GTTCTATGTG GACCTGGGGA GGAAGGAGAC
 TGTCTGGCGG TTGCCTATTC CCTACCGATA TGGTTTTGAC CCGCAATTTG
 CATTGAGAAA CATCGCTGTG CTAACACATA ACTTGAACGT CCTAATTAAA
 CGCTCCAACT CTACCGCTGC TACCAATGAG GTTCCCGAGG TCACAGTGTT
 TTCCAAGTCT CCCGTGACGC TGGGTCACCC CAACACCCTC ATCTGTCTTG
 TGGACCACAT CTTTCCTCCT GTGGTGAACA TCACATGGTT GAGCAATGGG
 CGCTCAGTCA CAGAAGGGGT TTCTGAGACC AGCTTCCTCT CCAAGAGTGA
 TCATTCCTTC TTCAAGATCA GTTACCTCAC CTTCCTCCCT TCTGCTGATG
 AGATTTATGA CTGCAGGGTG GAGCACTGGG GCCTGGACGA GCCTCTTCTG
 AAACACTGGG AGCCAGAGAT TCCAGCGCCC ATGTCAGAGC TCACAGAGAC
 TGTGGTCTGC GCCCTGGGGT TGTCTGCGGG CCTCGTGGGC ATTGTGGTGG
 GGACCATCTT GATCATCCGA GGCCTGCGTT CAGTTGGTGC TTCCAGACAT
 CAAGGGCCCT TGTAA*   
>DL;IPD:MHC05063
IPD:MHC05063 Mamu-DQA1*05:05 680 bases
 GAGGTGAAGA CATAGTGGCT GACCACGTTG CCTCTTACGG TGTAAACGTG
 TACCAGTCTT ATGGTCCCTC TGGCCAGTTC ACTCATGAAT TTGATGGAGA
 CGAGCAGTTC TACGTGGACC TGGGGAGGAA GGAGACTGTC TGGCGGTTGC
 CTATTCCCTA CCGATATGGT TTTGACCCGC AATTTGCATT GAGAAACATC
 GCTGTGCTAA CACATAACTT GAACATCCTG ATTAAACGCT CCAACTCTAC
 CGCTGCTACC AATGAGGTTC CCGAGGTCAC AGTGTTTTCC AAGTCTCCCG
 TGATGCTGGG TCAGCCCAAC ACCCTCATCT GTCTTGTGGA CAACATCTTT
 CCTCCTGTGG TGAACATCAC ATGGTTGAGC AATGGACACT CAGTCATAGA
 AGGGGTTTCT GAGACCAGCT TCCTCTCCAA GAGTGATCAT TCCTTCTTCA
 AGATCAGTTA CCTCACCTTC CTCCCTTCTG CTGATGAGAT TTATGACTGC
 AGGGTGGAGC ACTGGGGCCT GGATGAGCCT CTTCTGAAAC ACTGGGAGCC
 GGAGATTCCA GTGCCCATGT CAGAGCTCAC AGAGACTGTG GTCTGCGCCC
 TGGGGTTGTC TGCGGGCCTC GTGGGCATTG TGGTGGGGAC CGTCTTGATC
 ATCCGAGGCC TGCGTTCAGT TGGTGCCTCC * 
>DL;IPD:MHC05131
IPD:MHC05131 Mamu-DQA1*05:06 246 bases
 CTGACCACGT TGCCTCTTAC GGTGTAAACG TGTACCAGTC TTACGGTCCC
 TCTGGCCAGT ACTCCCATGA ATTTGATGGA GACGAGCAGT TCTACGTGGA
 CCTGGGGAGG AAGGAGACTG TCTGGCGGTT GCCTATTCCC TACCGATATG
 GTTTTGACCC GCAATTTGCA TTGAGAAACA TCGCTGTGCT AACACATAAC
 TTGAACATCC TGATTAAACG CTCCAACTCT ACCGCTGCTA CCAATG*
>DL;IPD:MHC00388
IPD:MHC00388 Mamu-DQA1*23:01 768 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTCGCTC TGACCACCGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT GGCTGACCAC GTTGCCTCTT
 ACGGTGTAAA CATGTACCAG TCTTACGGTC CCTCTGGCCA GTACACCCAT
 GAATTTGATG GAGACGAGGA GTTCTATGTG GACCTGGAGA GAAAGCAGAC
 TGTCTGGCAG TTGCCTCTGT TCAGCAAATT TAGAAGGTTT GACCCGCAGG
 GTGCACTGAG AAACATCGCT GTGCTACAAC ATAACTTGAA CATCGTGATT
 AAACGCTCCA ACTCCACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTCA TGCTGGGTCA GCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCACTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCGGA GATTCCAGCG CCCATGTCAG AGCTCACCGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTGT AGGCCTCGTG GGCATTGTGG
 TGGGCACTGT CTTCATCATC CGAGGCCTGC GTTCAATTGG CGCTTCCAGA
 CACCAAGGGC CCTTGTAA*   
>DL;IPD:MHC00389
IPD:MHC00389 Mamu-DQA1*23:02 768 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTTGCTC TGACCACCGT
 GATGAGCCCC TGCGGAGGTG AAGACATAGT GGCTGACCAC GTTGCCTCTT
 ACGGTGTAAA CGTGTACCAG TCTTATGGTC CCTCTGGCCA GTACACCCAT
 GAATTTGATG GAGACGAGGA GTTCTATGTG GACCTGGAGA GGAAGCAGAC
 TGTCTGGCAG TTGCCTCTGT TCAGCAAATT TAGAAGGTTT GACCCGCAGC
 GTGCACTGAG AAACATCGCT GTGCTACAAC ATAACTTGAA CATCGTGATT
 AAACGCTCCA ACTCCACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTCA TGCTGGGTCA GCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCACTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCGGA GATTCCAGCG CCCATGTCAG AGCTCACCGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTGT AGGCCTCGTG GGCATTGTGG
 TGGGCACTGT CTTCATCATC CGAGGCCTGC GTTCAATTGG CGCTTCCAGA
 CACCAAGGGC CCTTGTAA*   
>DL;IPD:MHC02421
IPD:MHC02421 Mamu-DQA1*23:03 768 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTCACTC TGACCACCGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT GGCTGACCAC GTTGCCTCTT
 ATGGTGTAAA CATGTACCAG TCTTATGGTC CCTCTGGCCA GTTCACTCAT
 GAATTTGATG GAGACGAGGA GTTCTATGTG GACCTGGAGA GAAAGCAGAC
 TGTCTGGCAG TTGCCTCTGT TCAGCAAATT TAGAAGGTTT GACCCGCAGG
 GTGCACTGAG AAACATCGCT GTGCTACAAC ATAACTTGAA CATCGTGATT
 AAACGCTCCA ACTCCACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTCA TGCTGGGTCA GCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCACTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCGGA GATTCCAGCG CCCATGTCAG AGCTCACCGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTGT AGGCCTCGTG GGCATTGTGG
 TGGGCACTGT CTTCATCATC CGAGGCCTGC GTTCAATTGG CGCTTCCAGA
 CACCAAGGGC CCTTGTAA*   
>DL;IPD:MHC00390
IPD:MHC00390 Mamu-DQA1*24:01:01 768 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTCGCTC TGACCACCGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT GGCTGACCAC GTTGCGTCTT
 ACGGTGTAAA CATGTACCAG TCTTACGGTC CCTCTGGCCA GTACACCCAT
 GAATTTGATG GAGACGAGGA GTTCTATGTG GACCTGGAGA GGAAGGAGAC
 CGTCTGGCAG TTGCCTCTGT TCAGCAAATT TAGAAGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGGGAAAAC ACAACTTGAA CATCCTGATT
 AAACGCTCCA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CACTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCGCTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCGGA GATTCCAGCA CCCATGTCAG AGCTCACAGA
 AACTGTGGTC TGCGCCCTGG GGTTGTCTAT GGGCCTCGTG GGCATTGTGG
 TGGGGACCGT CTTGATCATC CGAGGCCTGC GTTCAGTTGG TGCCTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC05019
IPD:MHC05019 Mamu-DQA1*24:01:02 683 bases
 GAGGTGAAGA CATAGTGGCT GACCACGTTG CGTCTTACGG TGTAAACATG
 TACCAGTCTT ACGGTCCCTC TGGCCAGTAC ACCCATGAAT TTGATGGAGA
 CGAGGAGTTC TATGTGGACC TGGAGAGGAA GGAGACCGTC TGGCAGTTGC
 CTCTGTTCAG CAAATTTAGA AGTTTTGACC CGCAGGGTGC ACTGAGAAAC
 TTGGCTGTGG GAAAACACAA CTTGAACATC CTGATTAAAC GCTCCAACTC
 TACCGCTGCT ACCAATGAGG TTCCTGAGGT CACAGTGTTT TCCAAGTCTC
 CCGTGACACT GGGTCACCCC AACACCCTCA TCTGTCTTGT GGACAACATC
 TTTCCTCCTG TGGTGAACAT CACATGGTTG AGCAATGGGC GCTCAGTCAC
 AGAAGGGGTT TCTGAGACCA GCTTCCTCTC CAAGAGTGAT CATTCCTTCT
 TCAAGATCAG TTACCTCACC TTCCTCCCTT CTGCTGATGA GATTTATGAC
 TGCAAGGTGG AGCACTGGGG CCTGGACGAG CCTCTACTGA AACACTGGGA
 GCCGGAGATT CCAGCACCCA TGTCAGAGCT CACAGAAACT GTGGTCTGCG
 CCCTGGGGTT GTCTATGGGC CTCGTGGGCA TTGTGGTGGG GACCGTCTTG
 ATCATCCGAG GCCTGCGTTC AGTTGGTGCC TCC* 
>DL;IPD:MHC00391
IPD:MHC00391 Mamu-DQA1*24:02 768 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTCGCTC TGACCACCGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT GGCTGACCAC GTTGCGTCTT
 ACGGTGTAAA CCTGTACCAG TCTTATGGTC CCTCTGGCCA GTACACCCAT
 GAATTTGATG GAGATGAGGA GTTCTATGTG GACCTGGAGA GGAAGGAGAC
 CGTCTGGCAG TTGCCTCTGT TCAGCAAATT TAGAAGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGTCAAAAC ACAACTTGAA CATCCTGATT
 AAACACTCCA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CACTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCGCTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCGGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCACCCTGG GGTTGTCTAT GGGCCTCGTG GGCATTGTGG
 TGGGGACCGT CTTGATCATC CGAGGCCTGC GTTCAGTTGG TGCCTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC00392
IPD:MHC00392 Mamu-DQA1*24:03 188 bases
 TCTTATGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGACGAGGA
 GTTCTATGTG GACCTGGAGA GGAAGGAGAC CATCTGGCAG TTGCCTCTGT
 TCAGCAAATT TAGAAGTTTT GACCCGCAGG GTGCACTGAG AAACTTGGCT
 GTGGGAAAAC ACAACTTGAA CATCCTGATT AAATGCTC* 
>DL;IPD:MHC00393
IPD:MHC00393 Mamu-DQA1*24:04 188 bases
 TCTTATGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGACGAGGA
 GTTCTATGTG GACCTGGAGA GGAAGGAGAC CGTCTGGCAG TTGCCTCTGT
 TCAGCAAATT TAGAAGTTTT GACCCGCAGG GTGCACTGAG AAACTTGGCT
 GTGGGAAAAC ACAACTTGAA CATCCTGATT AAACACTC* 
>DL;IPD:MHC02630
IPD:MHC02630 Mamu-DQA1*24:05 768 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTTGCTC TGACCACCGT
 GATGAGCCCC TGCGGAGGTG AAGACATAGT GGCTGACCAC GTTGCGTCTT
 ACGGTGTAAA CCTGTACCAG TCTTATGGTC CCTCTGGCCA GTACACCCAT
 GAATTTGATG GAGACGAGGA GTTCTATGTG GACCTGGAGA GGAAGGAGAC
 CGTCTGGCAG TTGCCTCTGT TCAGCAAATT TAGAAGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGGGAAAAC ACAACTTGAA CATCCTGATT
 AAACGCTCCA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CACTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCGCTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCGGA GATTCCAGCA CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG
 TGGGGACCGT CTTGATCATC CGAGGCCTGC GTTCAGTTGG TGCCTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC05058
IPD:MHC05058 Mamu-DQA1*24:06 683 bases
 GAGGTGAAGA CATAGTGGCT GACCACGTTG CGTCTTACGG TGTAAACCTG
 TACCAGTCTT ATGGTCCCTC TGGCCAGTAC ACCCATGAAT TTGATGGAGA
 CGAGGAGTTC TATGTGGACC TGGAGAGGAA GGAGACCGTC TGGCAGTTGC
 CTCTGTTCAG CAAATTTAGA AGTTTTGACC CGCAGGGTGC ACTGAGAAAC
 TTGGCTGTGG GAAAACACAA CTTGAACATC CTGATTAAAC GCTCCAACTC
 TACCGCTGCT ACCAATGAGG TTCCTGAGGT CACAGTGTTT TCCAAGTCTC
 CCGTGACACT GGGTCACCCC AACACCCTCA TCTGTCTTGT GGACAACATC
 TTTCCTCCTG TGGTGAACAT CACATGGTTG AGCAATGGGC GCTCAGTCAC
 AGAAGGGGTT TCTGAGACCA GCTTCCTCTC CAAGAGTGAT CATTCCTTCT
 TCAAGATCAG TTACCTCACC TTCCTCCCTT CTGCTGATGA GATTTATGAC
 TGCAAGGTGG AGCACTGGGG CCTGGACGAG CCTCTTCTGA AACACTGGGA
 GCCGGAGATT CCAGCACCCA TGTCAGAGCT CACAGAGACT GTGGTCTGCG
 CCCTGGGGTT GTCTATGGGC CTCGTGGGCA TTGTGGTGGG GACCGTCTTG
 ATCATCCGAG GCCTGCGTTC AGTTGGTGCC TCC* 
>DL;IPD:MHC05060
IPD:MHC05060 Mamu-DQA1*24:07 683 bases
 GAGGTGAAGA CATAGTGGCT GACCACATTG CGTCTTACGG TGTAAACCTG
 TACCAGTCTT ATGGTCCCTC TGGCCAGTAC ACCCATGAAT TTGATGGAGA
 CGAGGAGTTC TATGTGGACC TGGAGAGGAA GGAGACCGTC TGGCAGTTGC
 CTCTGTTCAG CAAATTTAGA AGTTTTGACC CGCAGGGTGC ACTGAGAAAC
 TTGGCTGTGG GAAAACACAA CCTGAACATC CTGATTAAAC GCTCCAACTC
 TACCGCTGCT ACCAATGAGG TTCCTGAGGT CACAGTGTTT TCCAAGTCTC
 CCGTGACACT GGGTCACCCC AACACCCTCA TCTGTCTTGT GGACAACATC
 TTTCCTCCTG TGGTGAACAT CACATGGTTG AGCAATGGGC GCTCAGTCAC
 AGAAGGGGTT TCTGAGACCA GCTTCCTCTC CAAGAGTGAT CATTCCTTCT
 TTAAGATCAG TTACCTCACC TTCCTCCCTT CTGCTGATGA GATTTATGAC
 TGCAAGGTGG AGCACTGGGG CCTGGACGAG CCTCTTCTGA AACACTGGGA
 GCCGGAGATT CCAGCACCCA TGTCAGAGCT CACAGAGACT GCGGTCTGCG
 CCCTGGGGTT GTCTATGGGC CTCGTGGGCA TTGTGGTGGG GACCGTCTTG
 ATCATCCGAG GCCTGCGTTC AGTTGGTGCC TCC* 
>DL;IPD:MHC05064
IPD:MHC05064 Mamu-DQA1*24:08 683 bases
 GAGGTGAAGA CATAGTGGCT GACCACGTTG CGTCTTACGG TGTAAACCTG
 TACCAGTCTT ATGGTCCCTC TGGCCAGTTC ACCCATGAAT TTGATGGAGA
 CGAGGAGTTC TATGTGGACC TGGAGAGGAA GGAGACCGTC TGGCAGTTGC
 CTCTGTTCAG CAAATTTAGA AGTTTTGACC CGCAGGGTGC ACTGAGAAAC
 TTGGCTGTGG GAAAACACAA CTTGAACATC CTGATTAAAC GCTCCAACTC
 TACCGCTGCT ACCAATGAGG TTCCCGAGGT CACAGTGTTT TCCAAGTCTC
 CCGTGACACT GGGTCACCCC AACACCCTCA TCTGTCTTGT GGACAACATC
 TTTCCTCCTG TGGTGAACAT CACATGGTTG AGCAATGGGC ACTCAGTCAC
 AGAAGGGGTT TCTGAGACCA GCTTCCTCTC CAAGAGTGAT CATTCCTTCT
 TCAAGATCAG TTACCTCACC TTCCTCCCTT CTGCTGATGA GATTTATGAC
 TGCAAGGTGG AGCACTGGGG CCTGGACGAG CCTCTTCTGA AACACTGGGA
 GCCGGAGATT CCAGCACCCA TGTCAGAGCT CACAGAAACT GTGGTCTGCG
 CCCTGGGGTT GTCTATGGGC CTCGTGGGCA TTGTGGTGGG GACCGTCTTG
 ATCATCCGAG GCCTGCGTTC AGTTGGTGCC TCC* 
>DL;IPD:MHC05067
IPD:MHC05067 Mamu-DQA1*24:09 683 bases
 GAGGTGAAGA CATAGTGGCT GACCACATTG CGTCTTACGG TGTAAACATG
 TACCAGTCTT ACGGTCCCTC TGGCCAGTAC ACCCATGAAT TTGATGGAGA
 CGAGGAGTTC TATGTGGACC TGGAGAGGAA GGAGACCGTC TGGCAGTTGC
 CTCTGTTCAG CAAATTTAGA AGTTTTGACC CGCAGGGTGC ACTGAGAAAC
 TTGGCTGTGG GAAAACACAA CTTGAACATC CTGATTAAAC GCTCCAACTC
 TACCGCTGCT ACCAATGAGG TTCCTGAGGT CACAGTGTTT TCCAAGTCTC
 CCGTGACACT GGGTCACCCC AACACCCTCA TCTGTCTTGT GGACAACATC
 TTTCCTCCTG TGGTGAACAT CACATGGTTG AGCAATGGGC GCTCAGTCAC
 AGAAGGGGTT TCTGAGACCA GCTTCCTCTC CAAGAGTGAT CATTCCTTCT
 TCAAGATCAG TTACCTCACC TTCCTCCCTT CTGCTGATGA GATTTATGAC
 TGCAAGGTGG AGCACTGGGG CCTGGACGAG CCTCTTCTGA AACACTGGGA
 GCCGGAGATT CCAGCACCCA TGTCAGAGCT CACAGAAACT GTGGTCTGCG
 CCCTGGGGTT GTCTATGGGC CTCGTGGGCA TTGTGGTGGG GACCGTCTTG
 ATCATCCGAG GCCTGCGTTC AGTTGGTGCC TCC* 
>DL;IPD:MHC05068
IPD:MHC05068 Mamu-DQA1*24:10 683 bases
 GAGGTGAAGA CATAGTGGCT GACCACGTTG CCTCTTACGG TGTAAACGTG
 TACCAGTCTT ATGGTCCCTC TGGCCAGTTC ACTCATGAAT TTGATGGAGA
 CGAGGAGTTC TATGTGGACC TGGAGAGGAA GGAGACCGTC TGGCAGTTGC
 CTCTGTTCAG CAAATTTAGA AGTTTTGACC CGCAGGGTGC ACTGAGAAAC
 TTGGCTGTGG GAAAACACAA CTTGAACATC CTGATTAAAC GCTCCAACTC
 TACCGCTGCT ACCAGTGAGG TTCCTGAGGT CACAGTGTTT TCCAAGTCTC
 CCGTGACACT GGGTCACCCC AACACCCTCA TCTGTCTTGT GGACAACATC
 TTTCCTCCTG TGGTGAACAT CACATGGTTG AGCAATGGGC GCTCAGTCAC
 AGAAGGGGTT TCTGAGACCA GCTTCCTCTC CAAGAGTGAT CATTCCTTCT
 TCAAGATCAG TTACCTCACC TTCCTCCCTT CTGCTGATGA GATTTATGAC
 TGCAAGGTGG AGCACTGGGG CCTGGACGAG CCTCTTCTGA AACACTGGGA
 GCCGGAGATT CCAGCACCCA TGTCAGAGCT CACAGAGACT GTGGTCTGCG
 CCCTGGGGTT GTCTATGGGC CTCGTGGGCA TTGTGGTGGG GACCGTCTTG
 ATCATCCGAG GCCTGCGTTC AGTTGGTGCC TCC* 
>DL;IPD:MHC00394
IPD:MHC00394 Mamu-DQA1*26:01 768 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTCGCTC TGACCACCGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT GGCTGACCAC GTTGCCTCTT
 ACGGTGTAAA CTTGTACCAG ACTTACGGTC TCTCTGGCCA GTACACCCAT
 GAATTTGATG GAGACGAGCA GTTCTACGTG GACCTGGAGA GGAAGGAGAC
 TGTCTGGCGG TTGCCTCTGT TCAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGTCAAAAC ACAACTTGAA CATCATGATT
 AAACGCTCCA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CACTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAGT
 GGGCGCTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG
 TGGGGACCGT CTTGATCATC CGAGGCCTGC GTTCAGTTGG TGCTTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC00395
IPD:MHC00395 Mamu-DQA1*26:02 768 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTCGCTC TGACCACCGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT GGCTGACCAC GTTGCCTCTT
 ACGGTGTAAA CTTGTACCAG ACTTACGGTC TCTCTGGCCA GTACACCCAC
 GAATTTGATG GAGACGAGCA GTTCTACGTG GACCTGGAGA GGAAGGAGAC
 TGTCTGGCGG TTGCCTCTGT TCAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGGGAAAAC ACAACTTGAA CATCCTGATT
 AAACACTCCA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CGCTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCACTCGG TCACAGAAGG TGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAGG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTAT GGGCCTCGTG GGCATTGTGG
 TGGGGACCGT CTTGATCATC CAAGGCCTGC GTTCAGTTGG TGCCTCCAGA
 CACCAAGGAC CCTTGTGA*   
>DL;IPD:MHC00396
IPD:MHC00396 Mamu-DQA1*26:03 768 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTTGCTC TGACCACCGT
 GATGAGCCCC TGCAGAGGTG AAGACATAGT GGCTGACCAC ATTGCCTCTT
 ACGGTGTAAA CTTGTACCAG ACTTACGGTC TCTCTGGCCA GTTCACTCAT
 GAATTTGATG GAGACGAGCA GTTCTACGTG GACCTGGAGA GGAAGGAGAC
 TGTCTGGCGG TTGCCTCTGT TCAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGGGAAAAC ACAACTTGAA CATCCTGATT
 AAACACTCCA ACTCTACTGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CACTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CCTGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCACTCAG TCACAGAAGG GGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAGG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTAT GGGCCTCGTG GGCATTGTGG
 TGGGGACCGT CTTGATCATC CGAGGCCTGC GTTCAGTTGG TGCCTCCAGA
 CACCAAGGGC CCTTGTGA*   
>DL;IPD:MHC00397
IPD:MHC00397 Mamu-DQA1*26:04 157 bases
 AATTTGATGG AGACGAGCAG TTCTACGTGG ACCTGGAGAG GAAGGAGGCT
 GTCTGGCGGT TGCCTCTGTT AAGCAAATTT GGAGGTTTTG ACCCGCAGGG
 TGCACTGAGA AACTTGGCTG TGTCAAAACA CAACTTGAAC ATCATGATTA
 AACGCTC*    
>DL;IPD:MHC02904
IPD:MHC02904 Mamu-DQA1*26:05 226 bases
 CTGACCACGT TGCCTCTTAC GGTGTAAACT TGTACCAGAC TTACGGTCTC
 TCTGGCCAGT ACACCCATGA ATTTGATGGA GACGAGCAGT TCTACGTGGA
 CCTGGAGAGG AAGGAGACTG TCTGGCGGTT GCCTCTGTTA AGCAAATTTG
 GAGGTTTTGA CCCGCAGGGT GCACTGAGAA ACTTGGCTGT GTCAAAACAC
 AACTTGAACA TCATGATTAA ACGCTC*  
>DL;IPD:MHC03806
IPD:MHC03806 Mamu-DQA1*26:06 768 bases
 ATGATCCTAA ACAAAGCTCT GTTGCTGGGG GCCCTCGCTC TGACCACCGT
 GATGAGCCCC TGTGGAGGTG AAGACATAGT GGCTGACCAC GTTGCCTCTT
 ACGGTGTAAA CTTGTACCAG ACTTACGGTC TCTCTGGCCA GTACACCCAC
 GAATTTGATG GAGACGAGCA GTTCTACGTG GACCTGGAGA GGAAGGAGAC
 TGTCTGGCGG TTGCCTCTGT TCAGCAAATT TGGAGGTTTT GACCCGCAGG
 GTGCACTGAG AAACTTGGCT GTGGGAAAAC ACAACTTGAA CATCCTGATT
 AAACACTCCA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT
 GTTTTCCAAG TCTCCCGTGA CGCTGGGTCA CCCCAACACC CTCATCTGTC
 TTGTGGACAA CATCTTTCCT CATGTGGTGA ACATCACATG GTTGAGCAAT
 GGGCACTCGG TCACAGAAGG TGTTTCTGAG ACCAGCTTCC TCTCCAAGAG
 TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGCTG
 ATGAGATTTA TGACTGCAGG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCG CCCATGTCAG AGCTCACAGA
 GACTGTGGTC TGCGCCCTGG GGTTGTCTAT GGGCCTCGTG GGCATTGTGG
 TGGGGACCGT CTTGATCATC CAAGGCCTGC GTTCAGTTGG TGCCTCCAGA
 CACCAAGGAC CCTTGTGA*   
>DL;IPD:MHC05065
IPD:MHC05065 Mamu-DQA1*26:07 683 bases
 GAGGTGAAGA CATAGTGGCT GACCACATTG CCTCTTACGG TGTAAACTTG
 TACCAGACTT ACGGTCTCTC TGGCCAGTTC ACTCATGAAT TTGATGGAGA
 CGAGCAGTTC TACGTGGACC TGGAGAGGAA GGAGACTGTC TGGCGGTTGC
 CTCTGTTCAG CAAATTTGGA GGTTTTGACC CGCAGGGTGC ACTGAGAAAC
 TTGGCTGTGG GAAAACACAA CTTGAACATC CTGATTAAAC ACTCCAACTC
 TACCGCTGCT ACCAATGAGG TTCCTGAGGT CACAGTGTTT TCCAAGTCTC
 CCGTGACACT GGGTCACCCC AACACCCTCA TCTGTCTTGT GGACAACATC
 TTTCCTCCTG TGGTGAACAT CACATGGTTG AGCAATGGGC ACTCAGTCAC
 AGAAGGGGTT TCTGAGACCA GCTTCCTCTC CAAGAGTGAT CATTCCTTCT
 TCAAGATCAG TTACCTCACC TTCCTCCCTT CTGCTGATGA GATTTATGAC
 TGCAGGGTGG AGCACTGGGG CCTGGACGAG CCTCTTCTGA AACACTGGGA
 GCCTGAGATT CCAGCGCCCA TGTCAGAGCT CACAGAGACT GTGGTCTGCG
 CCCTGGGGTT GTCTATGGGC CTCGTGGGCA TTGTGGTGGG GACCGTCTTG
 ATCATCCAAG GCCTGCGTTC AGTTGGTGCC TCC* 
>DL;IPD:MHC05066
IPD:MHC05066 Mamu-DQA1*26:08 683 bases
 GAGGTGAAGA CATAGTGGCT GACCACATTG CCTCTTACGG TGTAAACTTG
 TACCAGACTT ACGGTCTCTC TGGCCAGTTC ACTCATGAAT TTGATGGAGA
 CGAGCAGTTC TACGTGGACC TGGAGAGGAA GGAGACTGTC TGGCGGTTGC
 CTCTGTTCAG CAAATTTGGA GGTTTTGACC CGCAGGGTGC ACTGAGAAAC
 TTGGCTGTGG GAAAACACAA CTTGAACATC CTGATTAAAC ACTCCAACTC
 TACTGCTGCT ACCAATGAGG TTCCTGAGGT CACAGTGTTT TCCAAGTCTC
 CCATGACACT GGGTCACCCC AACACCCTCA TCTGTCTTGT GGACAACATC
 TTTCCTCCTG TGGTGAACAT CACATGGTTG AGTAATGGGC ACTCAGTCAC
 AGAAGGGGTT TCTGAGACCA GCTTCCTCTC CAAGAGTGAT CATTCCTTCT
 TCAAGATCAG TTACCTCACC TTCCTCCCTT CTGCTGATGA GATTTATGAC
 TGCAAGGTGG AGCACTGGGG CCTGGACGAG CCTCTTCTGA AACACTGGGA
 GCCTGAGATT CCAGCGCCCA TGTCAGAGCT CACAGAGACT GTGGTCTGCG
 CCCTGGGGTT GTCTGTGGGC CTCGTGGGCA TTGTGGTGGG GACCGTCTTG
 ATCATCCGAG GCCTGCGTTC AGTTGGTGCC TCC* 
