>DL;IPD:MHC00355
IPD:MHC00355 Mamu-AG*01:01 332 bases
 LLLVLSGVLA PTQTRAGSHS MRYFYTSVSR PGRWEPRFIA VGYVDDTQFV
 RFDSDAESPR MEPRAPWVEQ EGPEYWDRET QNMKTPTQTY RVNLRTLLRY
 YNQSEAGSHT IQKMYGCDLG PDGRLLRGYE QFAYDGRDYI ILNEDLRSWT
 AADMAAQNTQ RKWEAAGAAE QHRTYLEGEC LEWLRRYLEN GKETLQRADP
 PKTHVTHHPV SDYEATLRCW ALGFYPAEIT LTWQRDGEEQ TQDTELMETR
 PTGNGTFQKW AAVVVPSGEE QRYTCHVQHE GLPKPLTLRW ELSSQPTIPI
 VGIIAGLVLL GTVVTGAVVA AVMWRRKSSD RX* 
>DL;IPD:MHC00356
IPD:MHC00356 Mamu-AG*02:01:01 332 bases
 LLLVLSGVLA LTQTRAGSHS MRYFYTSMSR PGRGQPRFIA VGYVDDTQFV
 RFDSDAESPR MEPRAPWVEQ EGPEYWDRET QNMKTATQTY RENLRTLLRY
 YNQSEAGSHT IQKMYGCDLG PDGRLLRGYE QFAYDGRDYI ALNEDLRSWT
 AADMAAQNTQ RKWEAAGAAE QHRTYLEGEC LEWLRRYLEN GKETLQRADP
 PKTNVTHHPV SDYEATLRCW ALGFYPAEIT LTWQRDGEEQ TEDTELVETR
 PTGDGTFQKW AAVVVPSGEE QRYTCHVQHE GLPEPLTLRW EPSSQSTILI
 VGIIAGLVLL GTVVTGAVVA AVMWRRKSSD RX* 
>DL;IPD:MHC00357
IPD:MHC00357 Mamu-AG*02:01:02 331 bases
 LLVLSGVLAL TQTRAGSHSM RYFYTSMSRP GRGQPRFIAV GYVDDTQFVR
 FDSDAESPRM EPRAPWVEQE GPEYWDRETQ NMKTATQTYR ENLRTLLRYY
 NQSEAGSHTI QKMYGCDLGP DGRLLRGYEQ FAYDGRDYIA LNEDLRSWTA
 ADMAAQNTQR KWEAAGAAEQ HRTYLEGECL EWLRRYLENG KETLQRADPP
 KTNVTHHPVS DYEATLRCWA LGFYPAEITL TWQRDGEEQT EDTELVETRP
 TGDGTFQKWA AVVVPSGEEQ RYTCHVQHEG LPEPLTLRWE PSSQSTILIV
 GIIAGLVLLG TVVTGAVVAA VMWRRKSSDR X* 
>DL;IPD:MHC00358
IPD:MHC00358 Mamu-AG*02:02 332 bases
 LLLVLSGVLA LTQTRAGSHS MRYFYTSMSR PGRGQPRFIA VGYVDDTQFV
 RFDSDAESPR MEPRAPWVEQ EGPEYWDRET QNMKTATQTY RENLRTLLRY
 YNQSEAGSHT IQKMYGCDLG PDGRLLRGYE QFAYDGRDYI ALNEDLRSWT
 AADMAAQFTQ RKWEAAGAAE QHRTYLEGEC LEWLRRYLEN GKETLQRADP
 PKTNVTHHPV SDYEATLRCW ALGFYPAEIT LTWQRDGEEQ TEDTELVETR
 PTGDGTFQKW AAVVVPSGEE QRYTCHVQHE GLPEPLTLRW EPSSQSTILI
 VGIIAGLVLL GTVVTGAVVA AVMWRRKSSD RX* 
>DL;IPD:MHC00359
IPD:MHC00359 Mamu-AG*03:01 331 bases
 LLVLSGVLAL TQPRAGSHSM RYFYTAVSRP GRGQPRFIAV GYVDDTQFVR
 FDSDAESPRM EPRAPWVEQE GPEYWDRETQ NMKTATQTYQ ANLRTLLRYY
 NQSEAGSHTF QKMYGCDLGP DGRLLRGYEQ FAYDGRDYII LNEDLRSWTA
 ADMAAQNTQR KWEAAGAAEQ HRTYLEGECL EWLRRYLENG KETLQRADPP
 KTNVTHHPVS DYEATLRCWA LGFYPAEITL TWQRDGEEQT EDTELVETRP
 TGDGTFQKWA AVVVPSGEEQ RYTCHVQHEG LPEPLTLRWE PSSQSTILIV
 GIIAGLVLLG TVVTGAVVAA VMWRRKSSDR X* 
>DL;IPD:MHC00360
IPD:MHC00360 Mamu-AG*03:02 340 bases
 MAVMAPRTLL LVLSGVLALT QPRAGSHSMR YFYTAVSRPG RGQPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWVEQEG PEYWDRETQN MKTATQTYQA
 NLRTLLRYYN QSEAGSHTFQ KMYGCDLGPD GRLLRGYEQF AYDGRDYIIL
 NEDLRSWTAA DMAAQNTQRK WEAAGAAEQH RTYLEGECLE WLGRYLENGK
 ETLQRADPPK TNVTHHPVSD YEATLRCWAL GFYPAEITLT WQRDGEEQTE
 DTELVETRPT GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTILIVG IIAGLVLLGT VVTGAVVAAV MWRRKSSDRX *
>DL;IPD:MHC03743
IPD:MHC03743 Mamu-AG*05:01 273 bases
 SHSMRYFYTA VSRPGRREPL FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 VEQEGPEYWD RETQNMKTAT QTYRVNLRTA LRYYNQSEGG SHTIQKMYGC
 DLGPDGRLLR GYEQFAYDGR DYIALNEDLR SWTAADMAAQ FTQRKWEAAG
 AAEQHRTYLE GECLEWLRRY LENGKETLQR ADPPKTHVTH HPVSDYEATL
 RCWALGFYPA EITLTWQRDG EEQTEDTELV ETRPTGDGTF QKWAAVVVPS
 GEEQRYTCHV QHEGLPKPLT LRF*  
