>DL;IPD:MHC04408
IPD:MHC04408 Mamu-DRA*01:01 765 bases
 ATGGCCGAAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTGTGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAGG
 ACATTTATGA CTGCAAGGTG GAGCACTGGT GCTTGGATGC ACCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC00437
IPD:MHC00437 Mamu-DRA*01:02:01 765 bases
 ATGGCCATAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTGTGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAAG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC00438
IPD:MHC00438 Mamu-DRA*01:02:02 765 bases
 ATGGCCATAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTGTGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAAG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAAG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC00439
IPD:MHC00439 Mamu-DRA*01:02:03 765 bases
 ATGGCCATAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTGTGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAGG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC ACCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC00440
IPD:MHC00440 Mamu-DRA*01:02:04 765 bases
 ATGGCCATAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTGTGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAGG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC ACCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACTGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC00441
IPD:MHC00441 Mamu-DRA*01:02:05 765 bases
 ATGGCCATAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTGTGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CACTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAAG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTATGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC00442
IPD:MHC00442 Mamu-DRA*01:02:06 765 bases
 ATGGCCATAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTGTGCT
 GATGAGCGCT CAGGAATCAT GGGCTATTAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAGG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC ACCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC00443
IPD:MHC00443 Mamu-DRA*01:02:07 765 bases
 ATGGCCATAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTGTGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CACTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAAG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC05150
IPD:MHC05150 Mamu-DRA*01:02:08 765 bases
 ATGGCCATAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTGTGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAGG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC ACCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCATCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC05151
IPD:MHC05151 Mamu-DRA*01:02:09 765 bases
 ATGGCCATAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTGTGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAAG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATTAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC00444
IPD:MHC00444 Mamu-DRA*01:03:01 765 bases
 ATGGCCGTAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTATGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAAG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC02419
IPD:MHC02419 Mamu-DRA*01:03:02 765 bases
 ATGGCCGTAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTATGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAAG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACTGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC00445
IPD:MHC00445 Mamu-DRA*01:04:01 765 bases
 ATGGCCGAAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTGTGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CACTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAATAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAAG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC00446
IPD:MHC00446 Mamu-DRA*01:04:02 765 bases
 ATGGCCGAAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTGTGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAGG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC ACCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC03579
IPD:MHC03579 Mamu-DRA*01:04:03 765 bases
 ATGGCCGAAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTGTGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGAGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CACTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAAG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC TCCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACTGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC05103
IPD:MHC05103 Mamu-DRA*01:04:04 765 bases
 ATGGCCGAAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAAG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATTAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC05106
IPD:MHC05106 Mamu-DRA*01:04:05 765 bases
 ATGGCCGAAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTGTGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CACTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAAG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC05108
IPD:MHC05108 Mamu-DRA*01:04:06 765 bases
 ATGGCCGAAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CACTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAAG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC05149
IPD:MHC05149 Mamu-DRA*01:04:07 765 bases
 ATGGCCGAAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTGTGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CACTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAATAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAAG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC ACCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC00447
IPD:MHC00447 Mamu-DRA*01:05 765 bases
 ATGGCCATAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTGTGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAAG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAATGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC05075
IPD:MHC05075 Mamu-DRA*01:06:01 765 bases
 ATGGCCGTAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTGTGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CACTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACT GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAAG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTATGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC05148
IPD:MHC05148 Mamu-DRA*01:06:02 765 bases
 ATGGCCGTAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTGTGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CACTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAAG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC05152
IPD:MHC05152 Mamu-DRA*01:06:03 765 bases
 ATGGCCGTAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTGTGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CACTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAAG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTATGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC05070
IPD:MHC05070 Mamu-DRA*01:07 594 bases
 TTCTATCTGA ACCCTGACCA ATCAGGAGAG TTTATGTTTG ACTTTGATGG
 TGATGAGATT TTCCACGTGG ATATGGCAAA GAAGGAGACG GTCTGGCGGC
 TTGAAGAATT TGGACGATTT GCCAGCTTTG AGGCTCAAGG TGCATTGGCC
 AACATAGCTG TGGACAAAGC CAACCTGGAA ATCATGACAA AGCGCTCCAA
 CAATACTCCA ATCACCAATG TACCTCCAGA GGTAACTGTG CTCACAAACA
 GCCCTGTGGA ACTGGGAGAG CCCAACGTCC TCATCTGTTT CATCGACAAG
 TTCTCTCCAC CAGTGGTCAA AGTTACATGG CTTAAAAATG GAAAACCTGT
 CACCACAGGA GTGTCAGAGA CAGTCTTCCT GCCCAGGGAA GACCACCTTT
 TCCGCAAGTT CCACTATCTC CCCTTCCTGC CCTCAACTGA AGACATTTAT
 GACTGCAAGG TGGAGCACTG GGGCTTGGAT GTGCCTCTTC TCAAGCACTG
 GGAGTTTGAT GCACCAAGCC CTCTCCCAGA GACTACAGAG AACGTGGTGT
 GTGCCCTGGG CCTGATTGTG GGTCTGGTGG GCATCATCGT TGGA*
>DL;IPD:MHC05071
IPD:MHC05071 Mamu-DRA*01:08 594 bases
 TTCTATCTGA ACCCTGACCA ATCAGGAGAG TTTATGTTTG ACTTTGATGG
 TGATGAGATT TTCCACGTGG ATATGGCAAA GAAGGAGACG GTCTGGCGGC
 TTGAAGAATT TGGACGATTT GCCAGCTTTG AGGCTCAAGG TGCATTGGCC
 AACATAGCTG TGGACAAAGC CAACCTGGAA ATCATGACAA AGCGCTCCAA
 CAATACTCCA ATCACCAATG TACCTCCAGA GGTAACTGTG CTCACAAACA
 GCCCTGTGGA ACTGGGAGAG CCCAACGTCC TCATCTGTTT CATCGACAAG
 TTCTCTCCAC CAGTGGTCAA AGTTACATGG CTTAAAAATG GAAAACCTGT
 CACCACAGGA GTGTCAGAGA CAGTCTTCCT GCCCAGGGAA GACCACCTTT
 TCCGCAAGTT CCACTATCTC CCCTTCCTGC CCTCAACTGA AGACATTTAT
 GACTGCAAGG TGGAGCACTG GGGCTTGGAT GCGCCTCTTC TCAAGCACTG
 GGAGTTTGAT GTACCAAGCC CTCTCCCAGA GACTACAGAG AACGTGGTGT
 GTGCCCTGGG CCTGATTGTG GGTCTGGTGG GCATCATCGT TGGA*
>DL;IPD:MHC05077
IPD:MHC05077 Mamu-DRA*01:09 594 bases
 TTCTATCTGA ACCCTGACCA ATCAGGAGAG TTTATGTTTG ACTTTGATGG
 TGATGAGATT TTCCACGTGG ATATGGCAAA GAAGGAGACG GTCTGGCGGC
 TTGAAGAATT TGGACGATTT GCCAGCTTTG AGGCTCAAGG TGCACTGGCC
 AACATAGCTG TGGACAAAGC CAACCTGGAA ATCATGACAA AGCGCTCCAA
 CAATACTCCA ATCACCAATG TACCTCCAGA GGTAACTGTG CTCACAAACA
 GCCCTGTGGA ACTGGGAGAG CCCAACGTCC TCATCTGTTT CATCGACAAG
 TTCTCTCCAC CAGTGGTCAA AGTTACATGG CTTAAAAATG GAAAACCTGT
 CACCACAGGA GTGTCAGAGA CAGTCTTCCT GCCCAGGGAA GACCACCTTT
 TCCGCAAGTT CCACTATCTC CCCTTCCTGC CCTCAACTGA AGACATTTAT
 GACTGCAAGG TGGAGCACTG GGGCTTGGAT GCGCCTCTTC TCAAGCACCG
 GGAGTTTGAT GCACCAAGCC CTCTCCCAGA GACTACAGAG AACGTGGTAT
 GTGCCCTGGG CCTGATTGTG GGTCTGGTGG GCATCATCGT TGGA*
>DL;IPD:MHC05110
IPD:MHC05110 Mamu-DRA*02:01 765 bases
 ATGGCCGCAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA CAGCTGTGCT
 GATGAGCGCT CAAGAATCAT GGGCTATCAA AGAAGATCAT GTGATCATCC
 AGGCCGAGTT CTATCTGAAC CCTGACCAAT CAGGCGAGTA TATGTTTGAC
 TTTGATGGTG ATGAGCTTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CACTGGCGAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAATAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAGG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC ACCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
