>DL;IPD:MHC00577
IPD:MHC00577 Mamu-E*02:01:01 498 bases
 CACACTTCCG TGTCCCGGCC CGGCCGCGGG GGGCCCCGCT TCATCTCCGT
 GGGCTACGTG GACGACACCC AGTTCGTGCG GTATGACAGC GACGCCGCGA
 GTCCGAGGAT GGAGCCGCGG GCGCCGTGGG TGGAGCAGGA GGGGCCGGAG
 TATTGGGACC AGGAGACACG GAGCGCCAGG GACACCGCAC AGACTTTCCG
 AGTGAACCTG GAGACCCTGC GCGGCTACTA CAACCAGAGC GAGGCCGGGT
 CTCATACCCT CCAGTGGATG CATGGCTGCG ACCTGGGGCC GGACGGGCGC
 TTCCTCCGCG GGTATGAACA GTTCGCCTAC GACGGCAAGG ATTATCTCAC
 CCTGAATGAG GACCTGCGCT CCTGGTCCGC GGTGGACACG GCGGCTCAAA
 TCTCCGAGCA AAAGTCAAAT GATGGCTCTG AGGCTGAGCA CCAGAGAGCC
 TACCTGGAAG ACACATGCGT GGAGTGGCTC CACAGATACC TGGAGAAT*
>DL;IPD:MHC02417
IPD:MHC02417 Mamu-E*02:01:02 1080 bases
 ATGGCACTAC GAACCCTACT TCTCCTGCTC TCGGCCCTTA CCAAGACCTG
 GGCGGGCTCC CACTCCTTGA AGTATTTCCA CACTTCCGTG TCCCGGCCCG
 GCCGCGGGGG GCCCCGCTTC ATCTCCGTGG GCTACGTGGA CGACACCCAG
 TTCGTGCGGT ATGACAGCGA CGCCGCGAGT CCGAGGATGG AGCCGCGGGC
 GCCGTGGGTG GAGCAGGAGG GGCCGGAGTA TTGGGACCAG GAGACACGGA
 GCGCCAGGGA CACCGCACAG ACTTTCCGAG TGAACCTGGA GACCCTGCGC
 GGCTACTACA ACCAGAGCGA GGCCGGGTCT CATACCCTCC AGTGGATGCA
 TGGCTGCGAC CTGGGGCCGG ACGGGCGCTT CCTCCGCGGG TATGAACAGT
 TCGCCTACGA CGGCAAGGAT TATCTCACCC TGAATGAGGA CCTGCGCTCC
 TGGTCCGCGG TGGACACGGC GGCTCAAATC TCCGAGCAAA AGTCAAATGA
 TGGCTCTGAG GCTGAGCACC AGAGAGCCTA CCTGGAAGAC ACATGCGTGG
 AGTGGCTCCA CAGATACCTG GAGAATGGGA AGGAGACGCT GCAGCGCTCG
 GAACCCCCAA AGACACACGT GACCCACCAC CCCGTCTCTG ATCATGAGGC
 CACCCTGAGG TGCTGGGCCC TGGGCTTCTA TCCTGCGGAG ATCACAGTGA
 CCTGGCAGCG GGATGGGGAG GACCAGACCC AGGACACGGA GCTTGTGGAG
 ACCAGGCCTG CAGGGGATGG AACTTTCCAG AAGTGGGCAG CTGTGGTGGT
 ACCTTCTGGA GAGGAGCAGA GATACACGTG CCATGTGCAG CATGAGGGGC
 TACCCGAGCC CCTCACCCTG AGATGGGAGC CGTCTTCCCC GTCCACCATC
 CCCATCGTGG GCATCAGTGC TGGCCTGGTT CTCCTTGGAG CTGTGGTCAC
 TGGAGCTGTG GTTGCTGCTG TGATGTGGAG GAGGAAGAGC TCAGGTAGAA
 AAGGAGGGAG CTACTCTCAG GCTTCGTGTA GCGACAGTAC CCAGGGATCT
 GATGAGTCTC TCACAGCTTG TAAAGCCTGA * 
>DL;IPD:MHC00578
IPD:MHC00578 Mamu-E*02:02 1065 bases
 ATGGCACTAC GAACCCTACT TCTCCTGCTC TCGGCCCTTA CCAAGACCTG
 GGCGGGCTCC CACTCCTTGA AGTATTTCCA CACTTCCGTG TCCCGGCCCG
 GCCGCGGGGA GCCCCGCTTC ATCTCCGTGG GCTACGTGGA CGACACCCAG
 TTCGTGCGGT ACGACAGCGA CGCCGCGAGT CCGAGGATGG AGCCGCGGGC
 GCTGTGGATG AAGCAGGAGG GGCCGGAGTA TTGGGACCAG GAGACACGGA
 GCGCCAGGGA CACCGCACAG ACTTTCCGAG TGAACCTGAA GACCCTGCGC
 GGCTACTACA ACCAGAGCGA GGCCGGGTCT CATACTCTCC AGTGGATGCA
 TGGCTGCGAC CTGGGGCCGG ACGGGCGCTT CTTCCGCGGG TATGAACAGT
 TTGCCTACGA CGGCAAGGAT TATCTCACCC TGAATGAGGA CCTGCGCTCC
 TGGTCCGCGG TGGACACGGC GGCTCAAATC TCCGAGCAAA AGTCAAATGA
 TGGCTCTGAG GCGGAGCACC AGAGAGCCTA CCTGGAAGAC ACATGCGTGG
 AGTGGCTCCG CAGATACCTG GAGAATGGGA AGGAGACGCT GCTGCGCTCG
 GAATCCCCAA AGACACACGT GACCCGCCAC CCCGTCTCTG ATCATGAGGC
 CACCCTGAGG TGCTGGGCCC TGGGCTTCTA CCCTGCGGAG ATCACAGTGA
 CCTGGCAGCG GGATGGGGAG GACCAGACCC AGGACACGGA GCTTGTGGAG
 ACCAGGCCTG CAGGGGATGG AACTTTCCAG AAGTGGGCAG CTGTGGTGGT
 ACCTTCTGGA GAGGAGCAGA GATACACGTG CCATGTGCAG CATGAGGGGC
 TACCCGAGCC CCTCATCCTG AGATGGGAGC CGTCTTCCCA ATCCTCCATC
 CCAATCGTGG GCATCATTGT TGGCCTGGTT CTCCTTGGAG CTGTGGTCAC
 TGGAGCTGTG GTTGCTGCTG TGATGTGGAG GAAGAGCTCA GGTAGAAAAG
 GACGGAGCTA CTCTCAGGCT TCGTGTAGCG ACAGTGCCCA GGGATCTGAT
 GAGTCTCTCA CAGCT*   
>DL;IPD:MHC00579
IPD:MHC00579 Mamu-E*02:03 1080 bases
 ATGGCACTAG GAACCCTACT TCTCCTGCTC TCGGCCCTTA CCAAGACCTG
 GGCGGGCTCC CACTCCTTGA AGTATTTCCA CACTTCCGTG TCCCGGCCCG
 GCCGCGGGGG GCCCCGCTTC ATCTCCGTGG GCTACGTGGA CGACACCCAG
 TTCGTGCGGT ACGACAGCGA CGCCGCGAGT CAGAGGATGG AGCCGCGGGC
 GCCGTGGGTG GAGCAGGAGG GGCCGGAGTA TTGGGACCAG GAGACACGGA
 GCGCCAGGGA CACCGCACAG ACTTTCCGAG TGAACCTGGA GACCCTGCGC
 GGCTACTACA ACCAGAGCGA GGCCGGGTCT CATACCCTCC AGTGGATGCA
 TGGCTGCGAC CTGGGGTCCG ACGGGCGCTT CCTCCGCGGG TATGAACAGT
 TCGCCTACGA CGGCAAGGAT TATCTCACCC TGAATGAGGA CCTGCGCTCC
 TGGTCCGCGG TGGACACGGC GGCTCAAATC TCCGAGCAAA AGTCAAATGA
 TGGCTCTGAG GCTGAGCACC AGAGAGCCTA CCTGGAAGAC ACATGCGTGG
 AGTGGCTCCA CAGATACCTG GAGAATGGGA AGGAGACGCT GCAGCGCTCA
 GAACCCCCAA AGACACACGT GGCCCACCAC CCCGTCTCTG ATCATGAGGC
 CACCCTGAGG TGCTGGGCCC TGGGCTTCTA TCCTGCGGAG ATCACAGTGA
 CCTGGCAGCG GGATGGGGAG GACCAGACCC AGGACACGGA GCTTGTGGAG
 ACCAGGCCTG CAGGGGATGG AACTTTCCAG AAGTGGGCAG CTGTGGTGGT
 ACCTTCTGGA GAGGAGCAGA GATACACGTG CCATGTGCAG CATGAGGGGC
 TACCCGAGCC CCTCACCCTG AGATGGGAGC CGTCTTCCCA GTCCACCATC
 CCCATCGTGG GCATCATTGC TGGCCTGGTT CTCCTTGGAG CTGTGGTCAC
 TGGAGCTGTG ATTGTTGCTG TGATGTGGAG GAGGAAGAGC TCAGGTAGAA
 AAGGAGGGAG CTACTCTCAG GCTTCGTGTA GCGACAGTAC CCAGGGATCT
 GATGAGTCTC TCACAGCTTG TAAAGCCTGA * 
>DL;IPD:MHC00580
IPD:MHC00580 Mamu-E*02:04 1080 bases
 ATGGCACTAC GAACCCTACT TCTCCTGCTC TCGGCCCTTA CCAAGACCTG
 GGCGGGCTCC CACTCCTTGA AGTATTTCCA CACTTCCGTG TCCCGGCCCG
 GCGGCGGGGG GCCCCGCTTC ATCTCCGTGG GCTACGTGGA CGACACCCAG
 TTCGTGCGGT ATGACAGCGA CGCGGCGAGT CCGAGGATGG AGCCGCGGGC
 GCTGTGGATG AAGCAGGAGG GGCCGGAGTA TTGGGACCAG GAGACACGGA
 GCGCCAGGGC CACCGCACAG ACTTTCCGAG TGAACCTGGA GACCCTGCGC
 GGCTACTACA ACCAGAGCGA GGCCGGGTCT CATACCCTCC AGTGGATGCA
 TGGCTGCGAC CTGGGGCCGG ACGGGCGCTT CCTCCGCGGG TATGAACAGT
 TCGCCTACGA CGGCAAGGAT TATCTCACCC TGAATGAGGA CCTGCGCTCC
 TGGTCCGCGG TGGACACGGC GGCTCAAATC TCCGAGCAAA AGTCAAATGA
 TGGCTCTGAG GCGGAGCACC AGAGAGCCTA CCTGGAAGAC ACATGCGTGG
 AGTGGCTCCG CAGATACCTG GAGAATGGGA AGGAGACGCT GCAGCGCTCG
 GAATCCCCAA AGACACACGT GACCCACCAC CCCGTCTCTG ATCATGAGGC
 CACCCTGAGG TGCTGGGCCC TGGGCTTCTA CCCTGCGGAG ATCACAGTGA
 CCTGGCAGCG GGATGGGGAG GACCAGACCC AGGACACGGA GCTTGTGGAG
 ACCAGGCCTG CAGGGGATGG AACTTTCCAG AAGTGGGCAG CTGTGGTGGT
 ACCTTCTGGA GAGGAGCAGA GATACACGTG CCATGTGCAG CATGAGGGGC
 TACCCGAGCC CCTCACCCTG AGATGGGAGC CGTCTTCCCA GTCCACCATC
 CCCATCGTGG GCATCATTGC TGGCCTGGTT CTCCTTGGCG CTGTGCTCAC
 TGGAGCTGTG GTTGCTGCTG TGGTGTGGAG GAGGAAGAGC TCAGGTAGAA
 AAGGATGGAG CTACTCTCAG GCTGTGGGTA GCGACAGTTC CCAGGGATCT
 GATGATTCTC TCACAGCTTA TAAACCCTGA * 
>DL;IPD:MHC00581
IPD:MHC00581 Mamu-E*02:05 1077 bases
 ATGGCACTAG GAACCCTACT TCTCCTGCTC TCGGCCCTTA CCAAGACCTG
 GGCGGGCTCC CACTCCTTGA AGTATTTCCA CACTTCCGTG TCCCGGCCCG
 GCCGCGGGGA GCCCCGCTTC ATCTCCGTGG GCTACGTGGA CGACACCCAG
 TTCGTGCGGT TCGACAGCGA TGCCGCGAGT CCGAGGATGG AGCCGCGGGC
 GCCGTGGGTG GAGCAGGAGG GGCCGGAGTA TTGGGACCAG GAGACACGGA
 GCGCCAGGGA CACCGCACAG ACTTTCCGAG TGAACCTGAA GACCCTGCGC
 GGCTACTACA ACCAGAGCGA GGCCGCGTCT CATACCCTCC AGTGGATGCA
 TGGCTGCGAC CTGGGGCCCG ACGGGCGCTT CCTCCGCGGG TATGAACAGT
 TCGCCTACGA CGGCAAGGAT TATCTCACCC TGAATGAGGA CCTGCGCTCC
 TGGTCCGCGG TGGACACGGC GGCTCAGATT TCCGAGCGAA AGTCAAATGA
 TGGCTCTGAG GCGGAGCACC AGAGAGCCTA CCTGGAAGAC ACATGCGTGG
 AGTGGCTCCG CAGATACCTG GAGAATGGGA AGGAGACGCT GCAGCGCCCG
 GAATCCCCAA AGACACACGT GACCCACCAC CCCGTCTCTG GTCATGAGGC
 CACCCTGAGG TGCTGGGCCC TGGGCTTCTA CCCTGCGGAG ATCACAGTGA
 CCTGGCAGCG GGATGGGGAG GACCAGACCC AGGACACGGA GCTTGTGGAG
 ACCAGGCCTG CAGGGGATGG AACTTTTCAG AAGTGGGCAG CTGTGGTGGT
 ACCTTCTGGA GAGGAGCAGA GATACACGTG CCATGTGCAG CATGAGGGGC
 TACCGGAGCC CCTCACCCTG AGATGGGAGC CGTCTTCCCA GTCCACTATC
 GCCATCGTGG GCATCATTGC TGGCCTGGTT CTTGGCGCTG TGGTCACTGG
 AGCTGTGGTT GCTGCTGTGA TGTGGAGGAG GAAGAGCTCA GGTAGAAAAG
 GATGGAGCTA CTCTCAGGCT GTGGGTAGTG ACAGTTCCCA GGGATCTGAT
 GATTCTCTCA CAGCTTATAA ACCCTGA*  
>DL;IPD:MHC00582
IPD:MHC00582 Mamu-E*02:06 582 bases
 CCTTACCAAG ACCTGGGCGG GCTCCCACTC CTTGAAGTAT TTCCACACTT
 CCGTGTCCCG GCCCGGCGGC GGGGGGCCCC GCTTCATCTC CGTGGGCTAC
 GTGGACGACA CCCAGTTCGT GCGGTATGAC AGCGACGCGG CGAGTCCGAG
 GATGGAGCCG CGGGCGCTGT GGATGAAGCA GGAGGGGCCG GAGTATTGGG
 ACCAGGAGAC ACGGAGCGCC AGGGCCACCG CACAGACTTT CCGAGTGAAC
 CTGGAGACCC TGCGCGGCTA CTACAACCAG AGCGAGGCCG GGTCTCATAC
 CCTCCAGTGG ATGCATGGCT GCGACCTGGG GCCGGACGGG CGCTTCCTCC
 GCGGGTATGA ACAGTTCGCC TACGACGGCA AGGATTATCT CACCCTGAAT
 GAGGACCTGC GCTCCTGGTC CGCGGTGGAC ACGGCGGCTC AAATCTCCGA
 GCAAAAGTCA AATGATGGCT CTGAGGCTGA GCACCAGAGA GCCTACCTGG
 AAGACACATG CGTGGAGTGG CTCCACAGAT ACCTGGAGAA TGGGAAGGAG
 ACGCTGCAGC GCTCAGAACC CCCAAAGACA CA* 
>DL;IPD:MHC02638
IPD:MHC02638 Mamu-E*02:07 1080 bases
 ATGGCACTAC GAACCCTACT TCTCCTGCTC TCGGCCCTTA CCAAGACCTG
 GGCGGGCTCC CACTCCTTGA AGTATTTCCA CACTTCCGTG TCCCGGCCCG
 GCCGCGGGGG GCCCCGCTTC ATCTCCGTGG GCTACGTGGA CGACACCCAG
 TTCGTGCGGT ATGACAGCGA CGCCGCGAGT CCGAGGATGG AGCCGCGGGC
 GCCGTGGGTG GAGCAGGAGG GGCCGGAGTA TTGGGACCAG GAGACACGGA
 GCGCCAGGGA CACCGCACAG ACTTTCCGAG TGAACCTGGA GACCCTGCGC
 GGCTACTACA ACCAGAGCGA GGCCGGGTCT CATACCCTCC AGTGGATGCA
 TGGCTGCGAC CTGGGGTCCG ACGGGCGCTT CCTCCGCGGG TATGAACAGT
 TCGCCTACGA CGGCAAGGAT TATCTCACCC TGAATGAGGA CCTGCGCTCC
 TGGTCCGCGG TGGACACGGC GGCTCAAATC TCCGAGCAAA AGTCAAATGA
 TGGCTCTGAG GCTGAGCACC AGAGAGCCTA CCTGGAAGAC ACATGCGTGG
 AGTGGCTCCA CAGATACCTG GAGAATGGGA AGGAGACGCT GCAGCGCTCG
 GAACCCCCAA AGACACACGT GACCCACCAC CCCGTCTCTG ATCATGAGGC
 CACCCTGAGG TGCTGGGCCC TGGGCTTCTA TCCTGCGGAG ATCACAGTGA
 CCTGGCAGCG GGATGGGGAG GACCAGACCC AGGACACGGA GCTTGTGGAG
 ACCAGGCCTG CAGGGGATGG AACTTTCCAG AAGTGGGCAG CTGTGGTGGT
 ACCTTCTGGA GAGGAGCAGA GATACACGTG CCATGTGCAG CATGAGGGGC
 TACCCGAGCC CCTCACCCTG AGATGGGAGC CGTCTTCCCA GTCCACCATC
 CCCATCGTGG GCATCAGTGC TGGCCTGGTT CTCCTTGGAG CTGTGGTCAC
 TGGAGCTGTG GTTGCTGCTG TGATGTGGAG GAGGAAGAGC TCAGGTAGAA
 AAGGAGGGAG CTACTCTCAG GCTTCGTGTA GCGACAGTAC CCAGGGATCT
 GATGAGTCTC TCACAGCTTG TAAAGCCTGA * 
>DL;IPD:MHC00584
IPD:MHC00584 Mamu-E*02:08 582 bases
 CCTTACCAAG ACCTGGGCGG GCTCCCACTC CTTGAAGTAT TTCCACACTT
 CCGTGTCCCG GCCCGGCCGC GGGGGGCCCC GCTTCATCTC CGTGGGCTAC
 GTGGACGACA CCCAGTTCGT GCGGTACGAC AGCGACGCCG CGAGTCAGAG
 GATGGAGCCG CGGGCGCCGT GGGTGGAGCA GGAGGGGCCG GAGTATTGGG
 ACCAGGAGAC ACGGAGCGCC AGGGACACCG CACAGACTTT CCGAGTGAAC
 CTGGAGACCC TGCGCGGCTA CTACAACCAG AGCGAGGCCG GGTCTCATAC
 CCTCCAGTGG ATGCATGGCT GCGACCTGGG GTCCGACGGG CGCTTCCTCC
 GCGGGTATGA ACAGTTCGCC TACGACGGCA AGGATTATCT CACCCTGAAT
 GAGGACCTGC GCTCCTGGTC TGCGGTGGAC ACGGCGGCTC AGACCTCCGC
 GCAAAAGTCA AATGATGGCG GTGAGGCGGA GCACCAGAGA GCCTACCTGG
 AAGACACATG CGTGGAGTGG CTCCGCAGAT ACCTGGAGAA TGGGAAGGAG
 ACGCTGCAGC GCTCGCAATC CCCAAAGACA CA* 
>DL;IPD:MHC02639
IPD:MHC02639 Mamu-E*02:09 1077 bases
 ATGGCACTAC GAACCCTACT TCTCCTGCTC TCGGCCCTTA CCAAGACCTG
 GGCGGGCTCC CACTCCTTGA AGTATTTCCA CACTTCCGTG TCCCGGCCCG
 GCCGCGGGGG GCCCCGCTTC ATCTCCGTGG GCTACGTGGA CGACACCCAG
 TTCGTGCGGT ACGACAGCGA CGCCGCGAGT CCGAGGATGG AGCCGCGGGC
 GCCGTGGGTG GAGCAGGAGG GGCCGGAGTA TTGGGACCAG GAGACACGGA
 GCGCCAGGGA CACCGCACAG ACTTTCCGAG TGAACCTGGA GACCCTGCGC
 GGCTACTACA ACCAGAGCGA GGCCGGGTCT CATACCCTCC AGTGGATGCA
 TGGCTGCGAC CTGGGGTCCG ACGGGCGCTT CCTCCGCGGG TATGAACAGT
 TCGCCTACGA CGGCAAGGAT TATCTCACCC TGAATGAGGA CCTGCGCTCC
 TGGTCCGCGG TGGACACGGC GGCTCAAATC TCCGAGCAAA AGTCAAATGA
 TGGCTCTGAG GCTGAGCACC AGAGAGCCTA CCTGGAAGAC ACATGCGTGG
 AGTGGCTCCG CAGATACCTG GAGAATGGGA AGGAGACGCT GCAGCGCTCA
 GAACCCCCAA AGACACACGT GACCCACCAC CCCATCTCTG ATCATGAGGC
 CACCCTGAGG TGCTGGGCCC TGGGCTTCTA TCCTGCGGAG ATCACAGTGA
 CCTGGCAGCG GGATGGGGAG GACCAGACCC AGGACACGGA GCTTGTGGAG
 ACCAGGCCTG CAGGGGATGG AACTTTCCAG AAGTGGGCAG CTGTGGTGGT
 ACCTTCTGGA GAGGAGCAGA GATACACGTG CCATGTGCAG CATGAGGGGC
 TACCCGAGCC CCTCACCCTG AGATGGGAGC CGTCTTCCCA GTCCACCATC
 CCCATCGTGG GCATCATTGC TGGCCTGGTT CTCCTTGGAG CTGTGGTTGT
 TGCTGTGGTT GTTGCTGTGA TGTGGAGGAG GAAGAGCTCA GGTAGAAAAG
 GAGGGAGCTA CTCTCAGGCT TCGTGTAGCG ACAGTACCCA GGGATCTGAT
 GAGTCTCTCA CAGCTTGTAA AGCCTGA*  
>DL;IPD:MHC01629
IPD:MHC01629 Mamu-E*02:10 1077 bases
 ATGGCACTAC GAACCCTACT TCTCCTGCTC TCGGCCCTTA CCAAGACCTG
 GGCGGGCTCC CACTCCTTGA AGTATTTCCA CACTTCCGTG TCCCGGCCCG
 GCCGCGGGGG GCCCCGCTTC ATCTCCGTGG GCTACGTGGA CGACACCCAG
 TTCGTGCGGT ATGACAGCGA CGCCGCGAGT CCGAGGATGG AGCCGCGGGC
 GCCGTGGGTG GAGCAGGAGG GGCCGGAGTA TTGGGACCAG GAGACACGGA
 GCGCCAGGGA CACCGCACAG ACTTTCCGAG TGAACCTGGA GACCCTGCGC
 GGCTACTACA ACCAGAGCGA GGCCGGGTCT CATACCCTCC AGTGGATGCA
 TGGCTGCGAC CTGGGGCCGG ACGGGCGCTT CCTCCGCGGG TATGAACAGT
 TCGCCTACGA CGGCAAGGAT TATCTCACCC TGAATGAGGA CCTGCGCTCC
 TGGTCCGCGG TGGACACGGC GGCTCAAATC TCCGAGCAAA AGTCAAATGA
 TGGCTCTGAG GCTGAGCACC AGAGAGCCTA CCTGGAAGAC ACATGCGTGG
 AGTGGCTCCA CAGATACCTG GAGAATGGGA AGGAGACGCT GCAGCGCTCA
 GAACCCCCAA AGACACACGT GACCCACCAC CCCGTCTCTG ATCATGAGGC
 CACCCTGAGG TGCTGGGCCC TGGGCTTCTA TCCTGCGAAG ATCACAGTGA
 CCTGGCAGCG GGATGGGGAG GACCAGACCC AGGACACGGA GCTTGTGGAG
 ACCAGGCCTG CAGGGGATGG AACTTTCCAG AAGTGGGCAG CTGTGGTGGT
 ACCTTCTGGA GAGGAGCAGA GATACACGTG CCATGTGCAG CATGAGGGGC
 TACCCGAGCC CCTCACCCTG AGATGGGAGC CGTCTTCCCA GTCCACCATC
 CCCATCGTGG GCATCATTGC TGGCCTGGTT CTCCTTGGAG CTATGGTTGT
 TGCTGTGGTT GTTGCTGTGA TGTGGAGGAG GAAGAGCTCA GGTAGAAAAG
 GAGGGAGCTA CTCTCAGGCT TCGTGTAGCG ACAGTACCCA GGGATCTGAT
 GAGTCTCTCA CAGCTTGTAA AGCCTGA*  
>DL;IPD:MHC01630
IPD:MHC01630 Mamu-E*02:11 1077 bases
 ATGGCACTAC GAACCCTACT TCTCCTGCTC TCGGCCCTTA CCAAGACCTG
 GGCGGGCTCC CACTCCTTGA AGTATTTCCA CACTTCCGTG TCCCGGCCCG
 GCCGCGGGGG GCCCCGCTTC ATCTCCGTGG GCTACGTGGA CGACACCCAG
 TTCGTGCGGT ATGACAGCGA CGCCGCGAGT CCGAGGATGG AGCCGCGGGC
 GCCGTGGGTG GAGCAGGAGG GGCCGGAGTA TTGGGACCAG GAGACACGGA
 GCGCCAGGGA CACCGCACAG ACTTTCCGAG TGAACCTGGA GACCCTGCGC
 GGCTACTACA ACCAGAGCGA GGCCGGGTCT CATACCCTCC AGTGGATGCA
 TGGCTGCGAC CTGGGGCCGG ACGGGCGCTT CCTCCGCGGG TATGAACAGT
 TCGCCTACGA CGGCAAGGAT TATCTCACCC TGAATGAGGA CCTGCGCTCC
 TGGTCCGCGG TGGACACGGC GGCTCAAATC TCCGAGCAAA AGTCAAATGA
 TGGCTCTGAG GCTGAGCACC AGAGAGCCTA CCTGGAAGAC ACATGCGTGG
 AGTGGCTCCA CAGATACCTG GAGAATGGGA AGGAGACGCT GCAGCGCTCA
 GAACCCCCAA AGACACACGT GACCCACCAC CCCGTCTCTG ATCATGAGGC
 CACCCTGAGG TGCTGGGCCC TGGGCTTCTA TCCTGCGGAG ATCACAGTGA
 CCTGGCAGCG GGATGGGGAG GACCAGACCC AGGACACGGA GCTTGTGGAG
 ACCAGGCCTG CAGGGGATGG AACTTTCCAG AAGTGGGCAG CTGTGGTGGT
 ACCTTCTGGA GAGGAGCAGA GATACACGTG CCATGTGCAG CATGAGGGGC
 TACCCGAGCC CCTCACCCTG AGATGGGAGC CGTCTTCCCA GTCCACCATC
 CCCATCGTGG GCATCATTGC TGGCCTGGTT CTCCTTGGAG CTATGGTTGT
 TGCTGTGGTT GTTGCTGTGA TGTGGAGGAG GAAGAGCTCA GGTAGAAAAG
 GAGGGAGCTA CTCTCAGGCT TCGTGTAGCG ACAGTACCCA GGGATCTGAT
 GAGTCTCTCA CAGCTTGTAA AGCCTGA*  
>DL;IPD:MHC01984
IPD:MHC01984 Mamu-E*02:12:01 1080 bases
 ATGGCACAAC GAACCCTACT TCTCCTGCTC TCGGCCCTTA CCAAGACCTG
 GGCGGGCTCC CACTCCTTGA AGTATTTCCA CACTTCCGTG TCCCGGCCCG
 GCCGCGGGGA GCCCCGCTTC ATCTCCGTGG GCTACGTGGA CGACACCCAG
 TTCGTGCGGT ACGACAGCGA CGCCGCCAGT CCGAGGATGC AGCCGCGGGC
 GCCGTGGGTG GAGCAGGAGG GGCCGGAGTA TTGGGACCAG GAGACACGGA
 GCGCCAGGGA CACCGCACGG ACTTTCCGAG TGAACCTGGA GACCCTGCGC
 GGCTACTACA ACCAGAGCGT GGCCGCGTCT CATACCCTCC AGTGGATGCA
 TGGCTGCGAC CTGGCGCCCG ACAGGCGCTT CCTCCGCGGG TATGAACAGT
 TCGCCTACGA CGGCAAGGAT TATCTCACCC TGAATGAGGA CCTGCGCTCC
 TGGTCTGCGG TGGACACGGC GGCTCAGATC TCCGCGCAAA AGTCAAATGA
 TGGCGGTGAG GCGGAGCACC AGAGAGCCTA CCTGGAAGAC ACATGCGTGG
 AGTGGCTCCG CAGATACCTG GAGAATGGGA AGGAGACGCT GCAGCGCTCG
 GAACCCCCAA AGACACACGT GACCCACCAC CCCGTCTCTG ATCATGAGGC
 CACCCTGAGG TGCTGGGCCC TGGGCTTCTA CCCTGCGGAG ATCACAGTGA
 CCTGGCAGCG GGATGGGGAG GACCAGACCC AGGACACGGA GCTTGTGGAG
 ACTAGGCCTG CAGGGGATGG AACCTTCCAG AAGTGGGCAG CTGTGGTGGT
 GCCTTCTGGA GAGGAGCAGA GATACACGTG CCATGTGCAG CATGAGGGGC
 TACCCGAGCC CCTCACCCTG AGATGGGAGC CGTCTTCCCA GTCCACCATC
 CCCATCGTGG GCATCAGTGC TGGCCTGGTT CTCCTTGGAA CTGTGGTCAC
 TGGAGCTGTG GTTGCTGCTG TGATGTGGAG GAGGAAGAGC TCAGGTAGAA
 AAGGAGGGAG CTACTCTCAG GCTTCGTGTA GCGACAGTAC CCAGGGATCT
 GATGAGTCTC TCACAGCTTA TAAAACCTGA * 
>DL;IPD:MHC03583
IPD:MHC03583 Mamu-E*02:12:02 1080 bases
 ATGGCACAAC GAACCCTACT TCTCCTGCTC TCGGCCCTTA CCAAGACCTG
 GGCGGGCTCC CACTCCTTGA AGTATTTCCA CACTTCCGTG TCCCGGCCCG
 GCCGCGGGGA GCCCCGCTTC ATCTCCGTGG GCTACGTGGA CGACACCCAG
 TTCGTGCGGT ACGACAGCGA CGCCGCCAGT CCGAGGATGC AGCCGCGGGC
 GCCGTGGGTG GAGCAGGAGG GGCCGGAGTA TTGGGACCAG GAGACACGGA
 GCGCCAGGGA CACCGCAAGG ACTTTCCGAG TGAACCTGGA GACCCTGCGC
 GGCTACTACA ACCAGAGCGT GGCCGCGTCT CATACCCTCC AGTGGATGCA
 TGGCTGCGAC CTGGCGCCCG ACAGGCGCTT CCTCCGCGGG TATGAACAGT
 TCGCCTACGA CGGCAAGGAT TATCTCACCC TGAATGAGGA CCTGCGCTCC
 TGGTCTGCGG TGGACACGGC GGCTCAGATC TCCGCGCAAA AGTCAAATGA
 TGGCGGTGAG GCGGAGCACC AGAGAGCCTA CCTGGAAGAC ACATGCGTGG
 AGTGGCTCCG CAGATACCTG GAGAATGGGA AGGAGACGCT GCAGCGCTCG
 GAACCCCCAA AGACACACGT GACCCACCAC CCCGTCTCTG ATCATGAGGC
 CACCCTGAGG TGCTGGGCCC TGGGCTTCTA CCCTGCGGAG ATCACAGTGA
 CCTGGCAGCG GGATGGGGAG GACCAGACCC AGGACACGGA GCTTGTGGAG
 ACTAGGCCTG CAGGGGATGG AACCTTCCAG AAGTGGGCAG CTGTGGTGGT
 GCCTTCTGGA GAGGAGCAGA GATACACGTG CCATGTGCAG CATGAGGGGC
 TACCCGAGCC CCTCACCCTG AGATGGGAGC CGTCTTCCCA GTCCACCATC
 CCCATCGTGG GCATCAGTGC TGGCCTGGTT CTCCTTGGAA CTGTGGTCAC
 TGGAGCTGTG GTTGCTGCTG TGATGTGGAG GAGGAAGAGC TCAGGTAGAA
 AAGGAGGGAG CTACTCTCAG GCTTCGTGTA GCGACAGTAC CCAGGGATCT
 GATGAGTCTC TCACAGCTTA TAAAACCTGA * 
>DL;IPD:MHC01985
IPD:MHC01985 Mamu-E*02:13 1056 bases
 ATGGCACTAC GAACCCTACT TCTCCTGCTC TCGGCCCTTA CCAAGACCTC
 GGCGGGCTCC CACTCCTTGA AGTATTTCCA CACTTCCGTG TCCCGGCCCG
 GCCACGCGGA GCCCCACTTC ATCTCCGTGG GCTACGTGGA CGACACCCAG
 TTCGTGCGGT ACGACAGCGA TGCCGCGAGT CCGAGGATGG AGCCGCGGGC
 GCCGTGGGTG GAGCAGGAGG GGCCGGAGTA TTGGGACCAG GAGACACGGA
 GCGCCAGGGA CACCGCACAG ACTTTCCGAG TGAACCTGAA GACCCTGCGC
 GGCTACTACA ACCAGAGCGT GGCCGGGTCT CATACCCTCC AGTGGATGCA
 TGGCTGCGAC CTGGGGCCCG ACGGGCGCTT CCTCCGCGGA TATGAACAGT
 TCGCCTACGA CGGCAAGGAT TATCTCACCC TGAATGAGGA CCTGCGCTCC
 TGGTCCGCGG TGGACACGGC GGCTCAGATC TCTGAGCAAA AGTCAAATAA
 TGGCTCTGAG GCGGAGTACC AGAGAGCCTA CCTGGAAGAC ACATGCGTGG
 AGTGGCTCCG CAGATACCTG GAGAATGGGA AGGAGACGCT GCAGCGCTCG
 GAACCCCCAA AGACACATGT GACCCACCAC CCCGTCTCTG ATCATGAGGC
 CATCCTGAGG TGCTGGGCCC TGGGCTTCTA CCCTGCAGAG ATCACAGTGA
 CCTGGCAGCG GGATGGGGAG GACCAGACCC AGGACACGGA GCTTGTGGAG
 ACCAGGCCTG CAGGGGATGG AACTTTCCAG AAGTGGGCAG CTGTGGTGGT
 ACCTTCTGGA GAGGAGCAGA GATACACGTG CCATGTGCAG CATGAGGGGC
 TACCCGAGCC CCTCACCCTG AGATGGGAGC CGTCTTCCCA GCCCTCTATC
 CCAATCTTGG GCATCATTGC TGGCCTGGTT CTCCTTGGAG CTGTGGTCAT
 TGTGGTTGCT GCTGTGATGT GGAGGAGGAA GAGCTCAGGT GGGGAAGAGA
 GAGGTAGCGA CAGTGCCCAG GGATCTGATG AGTCTCTCAC AGCTTATAAA
 ACCTGA*    
>DL;IPD:MHC01986
IPD:MHC01986 Mamu-E*02:14 1080 bases
 ATGGCACTAC GAACCCTACT TCTCCTGCTC TCGGCCCTTA CCAAGACCTG
 GGCGGGCTCC CACTCCTTGA AGTATTTCCA CACTTCCGTG TCCCGGCCCG
 GCCGCGGGGG GCCCCGCTTC ATCTCCGTGG GCTACGTGGA CGACACCCAG
 TTCGTGCGGT ATGACAGCGA CGCCGCGAGT CCGAGGATGG AGCCGCGGGC
 GCCGTGGGTG GAGCAGGAGG GGCCGGAGTA TTGGGACCAG GAGACACGGA
 GCGCCAGGGA CACCGCACAG ACTTTCCGAG TGAACCTGGA GACCCTGCGC
 GGCTACTACA ACCAGAGCGA GGCCGGGTCT CATACCCTCC AGTGGATGCA
 TGGCTGCGAC CTGGGGTCCG ACGGGCGCTT CCTCCGCGGG TATGAACAGT
 TCGCCTACGA CGGCAAGGAT TATCTCACCC TGAATGAGGA CCTGCGCTCC
 TGGTCCGCGG TGGACACGGC GGCTCAAATC TCCGAGCAAA AGTCAAATGA
 TGGCTCTGAG GCGGAGCACC AGAGAGCCTA CCTGGAAGAC ACATGCGTGG
 AGTGGCTCCA CAGATACCTG GAGAATGGGA AGGAGACGCT GCAGCGCTCA
 GAACCCCCAA AGACACACGT GACCCACCAC CCCGTCTCTG ATCATGAGGC
 CACCCTGAGG TGCTGGGCCC TGGGCTTCTA TCCTGCGGAC ATCACAGTGA
 CCTGGCAGCG GGATGGGGAG GACCAGACCC AGGACACGGA GCTTGTGGAG
 ACCAGGCCTG CAGGGGATGG AACTTTCCAG AAGTGGGCAG CTGTGGTGGT
 ACCTTCTGGA GAGGAGCAGA GATACACGTG CCATGTGCAG CATGAGGGGC
 TACCCGAGCC CCTCACCCTG AGATGGGAGC CGTCTTCCCA GTCCACCATC
 CCCATCGTGG GCATCATTGC TGGCCTGGTT CTCCTTGGAG CTGTGGTCAC
 TGGAGCTGTG GTTGTTGCTG TGATGTGGAG GAGGAAGAGC TCAGGTAGAA
 AAGGAGGGAG CTACTCTCAG GCTTCGTGTA GCGACAGTAC CCAGGGATCT
 GATGAGTCTC TCACAGCTTG TAAAGCCTGA * 
>DL;IPD:MHC01987
IPD:MHC01987 Mamu-E*02:15 1020 bases
 ATGGCACTAC GAACCCTACT TCTCCTGCTC TCGGCCCTTA CCAAGACCTG
 GGCGGGCTCC CACTCCTTGA AGTATTTCCA CACTTCCGTG TCCCGGCCCG
 GCCGCGCGGA GCCCCACTTC ATCTCCGTGG GCTACGTGGA CGACACCCAG
 TTCGTGCGGT ACGACAGCGA TGCCGCGAGT CCGAGGATGC AGCCGCGGGC
 GCCGTGGGTG GAGCAGGAGG GGCCGGAGTA TTGGGACCAG GAGACACGGA
 TCGCCAGGGA CACCGCACGG ACTTTCCGAG TGAACCTGAA GACCCTGCGC
 GGCTACTACA ACCAGAGCGT GGCCGGGTCT CATACCCTCC AGTGGATGCA
 TGGCTGCGAC CTGGGGCCGG ACGGGCGCTT CCTCCGCGGG TATGAACAGT
 TCGCCTACGA CGGCAAGGAT TATCTCACCC TGAATGAGGA CCTGCGCTCC
 TGGTCCGCGA TGGACACGGC GGCTCAGATC TCTGAGCAAA AGTCAAATGA
 TGGCGGTGAG GCGGAGCACC AGAGAGCCTA CCTGGAAGAC ACATGCGTGG
 AGTGGCTCCG CAGATACCTG GAGAATGGGA AGGAGACGCT GCAGCGCTCG
 GAATCCCCAA AGACACACGT GACCCACCAC CCCATCTCTG ATCATGAGGC
 CACCCTGAGG TGCTGGGCCC TGGGCTTCTA CCCTGCAGAG ATCACAGTGA
 CCTGGCAGCG GGATGGGGAG GACCAGACCC AGGACACGGA GCTTGTGGAG
 ACCAGGCCTG CAGGGGATGG AACTTTCCAG AAGTGGGCAG CTGTGGTGGT
 ACCTTCTGGA GAGGAGCAGA GATACACGTG CCATGTGCAG CATGAGGGGC
 TACCCGAGCC CCTCACCCTG AGATGGGAGC CGTCTTCGCA GCCCTCTATC
 CCAATCGTGG GCATCATTGC TGGCCTGGAC CTCCTTGCAG CTGTGGTCAC
 TGGAGCTGTG GTTGCTGCTG TGATGTGGAA GAGGAAGAGC TCAGGTGGGG
 AAGGGAGAGA GGTAGACTGA *  
>DL;IPD:MHC02418
IPD:MHC02418 Mamu-E*02:16 1080 bases
 ATGGCACTAG GAACCCTACT TCTCCTGCTC TCGGCCCTTA CCAAGACCTG
 GGCGGGCTCC CACTCCTTGA AGTATTTCCA CACTTCCGTG TCCCGGCCCG
 GCCGCGGGGA GCCCCGCTTC ATCTCCGTGG GCTACGTGGA CGACACCCAG
 TTCGTGCGGT ACGACAGCGA CGCCGCGAGT CCGAGGATGC AGCCGCGGGC
 GCCGTGGGTG GAGCAGGAGG GGCCGGAGTA TTGGGACCAG GAGACACGGA
 GCGCCAGGGA CACCGCACGG ACTTTCCGAG TGAACCTGGA GACCCTGCGC
 GGCTACTACA ACCAGAGCGA GGCCGGGTCT CATACCCTCC AGTGGATGCA
 TGGCTGCGAC CTGGCGCCCG ACAGGCGCTT CCTCCGCGGG TATGAACAGT
 TCGCCTACGA CGGCAAGGAT TATCTCACCC TGAATGAGGA CCTGCGCTCC
 TGGTCTGCGG TGGACACGGC GGCTCAGACC TCCGCGCAAA AGTCAAATGA
 TGGCGGTGAG GCGGAGCACC AGAGAGCCTA CCTGGAAGAC ACATGCGTGG
 AGTGGCTCCG CAGATACCTG GAGAATGGGA AGGAGACGCT GCAGCGCTCG
 CAATCCCCAA AGACACACGT GACCCACCAC CCCGTCTCTG ATCATGAGGC
 CACCCTGAGG TGCTGGGCCC TGGGCTTCTA CCCTGCGGAG ATCACAGTGA
 CCTGGCAGCG GGATGGGGAG GACCAGACCC AGGACACGGA GCTTGTGGAG
 ACTAGGCCTG CAGGGGATGG AACCTTCCAG AAGTGGGCAG CTGTGGTGGT
 GCCTTCTGGA GAGGAGCAGA GATACACGTG CCATGTGCAG CATGAGGGGC
 TACCCGAGCC CCGAGCCCTG AGATGCGAGC CGTCTTCCCA GTCCACCATC
 CCCATCGTGG GCATCAGTGC TGGCCTGGTT CTCCTTGGAA CTGTGGTCAC
 TGGAGCTGTG GTTGTTGCTG TGATGTGGAG GAGGAAGAGC TCAGGTAGAA
 AAGGATGGAG CTACTCTCAG GCTTCGTGTA GCGACAGTAC CCAGGGATCT
 GATGAGTCTC TCACAGCTTA TAAAACCTGA * 
>DL;IPD:MHC02629
IPD:MHC02629 Mamu-E*02:17 1080 bases
 ATGGCACTAC GAACCCTACT TCTCCTGCTC TCGGCCCTTA CCAAGACCTG
 GGCGGGCTCC CACTCCTTGA AGTATTTCCA CACTTCCGTG TCCCGGCCCG
 GCCGCGGGGG GCCCCGCTTC ATCTCCGTGG GCTACGTGGA CGACACCCAG
 TTCGTGCGGT ATGACAGCGA CGCCGCGAGT CCGAGGATGG AGCCGCGGGC
 GCCGTGGGTG GAGCAGGAGG GGCCGGAGTA TTGGGACCAG GAGACACGGA
 GCGCCAGGGA CACCGCACAG ACTTTCCGAG TGAACCTGGA GACCCTGCGC
 GGCTACTACA ACCAGAGCGA GGCCGGGTCT CATACCCTCC AGTGGATGCA
 TGGCTGCGAC CTGGGGTCCG ACGGGCGCTT CCTCCGCGGG TATGAACAGT
 TCGCCTACGA CGGCAAGGAT TATCTCACCC TGAATGAGGA CCTGCGCTCC
 TGGTCCGCGG TGGACACGGC GGCTCAAATC TCCGAGCAAA AGTCAAATGA
 TGGCTCTGAG GCTGAGCACC AGAGAGCCTA CCTGGAAGAC ACATGCGTGG
 AGTGGCTCCG CAGATACCTG GAGAATGGGA AGGAGACGCT GCAGCGCTCG
 GAACCCCCAA AGACACACGT GACCCACCAC CCCGTCTCTG ATCATGAGGC
 CACCCTGAGG TGCTGGGCCC TGGGCTTCTA TCCTGCGGAG ATCACAGTGA
 CCTGGCAGCG GGATGGGGAG GACCAGACCC AGGACACGGA GCTTGTGGAG
 ACCAGGCCTG CAGGGGATGG AACTTTCCAG AAGTGGGCAG CTGTGGTGGT
 ACCTTCTGGA GAGGAGCAGA GATACACGTG CCATGTGCAG CATGAGGGGC
 TACCCGAGCC CCTCACCCTG AGATGGGAGC CGTCTTCCCC GTCCACCATC
 CCCATCGTGG GCATCAGTGC TGGCCTGGTT CTCCTTGGAG CTGTGGTCAC
 TGGAGCTGTG GTTGCTGCTG TGATGTGGAG GAGGAAGAGC TCAGGTAGAA
 AAGGAGGGAG CTACTCTCAG GCTTCGTGTA GCGACAGTAC CCAGGGATCT
 GATGAGTCTC TCACAGCTTG TAAAGCCTGA * 
>DL;IPD:MHC03582
IPD:MHC03582 Mamu-E*02:18 1080 bases
 ATGGCACTAC GAACCCTACT TCTCCTGCTC TCGGCCCTTA CCAAGACCTG
 GGCGGGCTCC CACTCCTTGA AGTATTTCCA CACTTCCGTG TCCCGGCCCG
 GCCGCGGGGA GCCCCGCTTC ATCTCCGTGG GCTACGTGGA CGACACCCAG
 TTCGTGCGGT ATGACAGCGA CGCCGCGAGT CCGAGGATGG AGCCGCGGGC
 GCCGTGGGTG GAGCAGGAGG GGCCGGAGTA TTGGGACCAG GAGACACGGA
 GCGCCAGGGA CACCGCACAG ACTTTCCGAG TGAACCTGGA GACCCTGCGC
 GGCTACTACA ACCAGAGCGA GGCCGGGTCT CATACCCTCC AGTGGATGCA
 TGGCTGCGAC CTGGGGTCCG ACGGGCGCTT CCTCCGCGGG TATGAACAGT
 TCGCCTACGA CGGCAAGGAT TATCTCACCC TGAATGAGGA CCTGCGCTCC
 TGGTCCGCGG TGGACACGGC GGCTCAAATC TCCGAGCAAA AGTCAAATGA
 TGGCTCTGAG GCTGAGCACC AGAGAGCCTA CCTGGAAGAC ACATGCGTGG
 AGTGGCTCCA CAGATACCTG GAGAATGGGA AGGAGACGCT GCAGCGCTCA
 GAATCCCCAA AGACACACGT GACCCACCAC CCCGTCTCTG ATCATGAGGC
 CACCCTGAGG TGCTGGGCCC TGGGCTTCTA TCCTGCGGAG ATCACAGTGA
 CCTGGCAGCG GGATGGGGAG GACCAGACCC AGGACACGGA GCTTGTGGAG
 ACCAGGCCTG CAGGGGATGG AACTTTCCAG AAGTGGGCAG CTGTGGTGGT
 ACCTTCTGGA GAGGAGCAGA GATACACGTG CCATGTGCAG CATGAGGGGC
 TACCCGAGCC CCGAGCCCTG AGATGGGAGC CGTCTTCCCA GTCCACCATC
 CCCATCGTGG GCATCATTGC TGGCCTGGTT CTCCTTGGAG CTGTGGTCAC
 TGGAGCTGTG GTTGTTGCTG TGATGTGGAG GAGGAAGAGC TCAGGTAGAA
 AAGGAGGGAG CTACTCTCAG GCTTCGTGTA GCGACAGTAC CCAGGGATCT
 GATGAGTCTC TCACAGCTTG TAAAGCCTGA * 
>DL;IPD:MHC00583
IPD:MHC00583 Mamu-E*02:19 1080 bases
 ATGGCACTAC GAACCCTACT TCTCCTGCTC TCGGCCCTTA CCAAGACCTG
 GGCGGGCTCC CACTCCTTGA AGTATTTCCA CACTTCCGTG TCCCGGCCCG
 GCCGCGGGGG GCCCCGCTTC ATCTCCGTGG GCTACGTGGA CGACACCCAG
 TTCGTGCGGT ATGACAGCGA CGCCGCGAGT CCGAGGATGG AGCCGCGGGC
 GCCGTGGGTG GAGCAGGAGG GGCCGGAGTA TTGGGACCAG GAGACACGGA
 GCGCCAGGGA CACCGCACAG ACTTTCCGAG TGAACCTGGA GACCCTGCGC
 GGCTACTACA ACCAGAGCGA GGCCGGGTCT CATACCCTCC AGTGGATGCA
 TGGCTGCGAC CTGGGGTCCG ACGGGCGCTT CCTCCGCGGG TATGAACAGT
 TCGCCTACGA CGGCAAGGAT TATCTCACCC TGAATGAGGA CCTGCGCTCC
 TGGTCCGCGG TGGACACGGC GGCTCAAATC TCCGAGCAAA AGTCAAATGA
 TGGCTCTGAG GCTGAGCACC AGAGAGCCTA CCTGGAAGAC ACATGCGTGG
 AGTGGCTCCA CAGATACCTG GAGAATGGGA AGGAGACGCT GCAGCGCTCA
 GAACCCCCAA AGACACACGT GACCCACCAC CCCGTCTCTG ATCATGAGGC
 CACCCTGAGG TGCTGGGCCC TGGGCTTCTA TCCTGCGGAG ATCACAGTGA
 CCTGGCAGCG GGATGGGGAG GACCAGACCC AGGACACGGA GCTTGTGGAG
 ACCAGGCCTG CAGGGGATGG AACTTTCCAG AAGTGGGCAG CTGTGGTGGT
 ACCTTCTGGA GAGGAGCAGA GATACACGTG CCATGTGCAG CATGAGGGGC
 TACCCGAGCC CCGAGCCCTG AGATGGGAGC CGTCTTCCCA GTCCACCATC
 CCCATCGTGG GCATCATTGC TGGCCTGGTT CTCCTTGGAG CTGTGGTCAC
 TGGAGCTGTG GTTGTTGCTG TGATGTGGAG GAGGAAGAGC TCAGGTAGAA
 AAGGAGGGAG CTACTCTCAG GCTTCGTGTA GCGACAGTAC CCAGGGATCT
 GATGAGTCTC TCACAGCTTG TAAAGCCTGA * 
>DL;IPD:MHC01628
IPD:MHC01628 Mamu-E*02:20 1077 bases
 ATGGCACTAG GAAGCCTACT TCTGCTCTCA GCACTTACCA AGACCTGGGC
 GGGCTCCCAC TCCTTGAAGT ATTTCCACAC CGCCGTGTCC CGGCCCGGCT
 GCGTGGAGCC CCGCTTCATC TTCGTGGGCT ACGTGGACGA CACCCAGTTC
 GTGCGGTTCG ACAGCGATGC CGCGAATCCG AGGATGCAGC CGCGGGCGCC
 ATGGATGGAG CAGGAGGGGC CGGAGTATTG GGACCAGGAG ACACGCAGAG
 CCAGGGACAC CGCACAGACT TTACGAGTGA AACTGAAGAC CCTGCGCGGC
 TACTACAACC AGAGCGAGGC CGGGTCTCAT ACCCTCCAGT GGATGTATGG
 CTGCGACCTG GGGCCCGACG GGCGCTTCCT CCGCGAGTAT GAACAGTTCG
 CCTACGACGG CAAGGATTAT CTCACCCTGA ATGAGGACCT GCGCTCCTGG
 TCCGCGGTGG ACACGGCGGC TCAAATCTCC GAGCAAAAGT CAAATGATGG
 CGGTGAGGCG GAGCACCAGA GAGCCTACCT GGAAGACACA TGCGTGGAGT
 GGCTCCGCAG ATACCTGGAG AATGGGAAGG AGACGCTGCA ACGCCCGGAA
 CCCCCAAAGA CACACGTGAC CCACCACCCC ATCTCTGATC ATGAGGCCAC
 CCTGAGGTGC TGGGCCCTGG GCTTCTACCC TGCGGAGATC ACAGTGACCT
 GGCAGCGGGA TGGGGAGGAC CAGACCCAGG ACACGGAGCT TGTGGAGACC
 AGGCCTGCAG GGGATGGAAC CTTCCAGAAG TGGGCAGCTG TGGTGGTGCC
 TTCTGGAGAG GAGCAGAGAT ACACGTGCCA TGTGCAGCAT GAGGGGCTAC
 CCGAGCCCCT CACCCTGAGA TGGGAGCCGC CTTCCCAACA CTCCATCCCC
 ATCGTGGGCA TCAGTGCTGG CCTGGTTCTC CTTGGAGCTG TGGTCACTGG
 AGCTGTGGTT GCTGCTGTGA TGTGGAGGAG GAAGAGCTCA GGTAGAAAAG
 GAGGGAGCTA CTCTCAGGCT TTGTGTAGCG ACAGTACCCA GGGATCTGAA
 GAGTCTCTCA CAGCTTATAA AACCTGA*  
