>DL;IPD:MHC00398
IPD:MHC00398 Mamu-DQB1*06:01 262 bases
 MSWKKALRIP GGLRAATVTL MLAMLSTPVA EGRDAPEDFV YQFKAMCYFT
 NWTERVRYVT RYIYNREEFV RFDSAVGEYR AVTPQGRLDA EYWNSQKDVL
 ESTRAELDTV CKHNYEVAFR GILQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNNQEE TVGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK LLSGIGGLVL GLIFFGLGLI
 IRQRSQKGLP HX*   
>DL;IPD:MHC00399
IPD:MHC00399 Mamu-DQB1*06:02:01 262 bases
 MSWKKALRIP GGLRVATVTL MLAMLSTPVA EGRDSPEDFV YQFKGLCYFT
 NGTERVRSVT RHIYNREEYV RFDSDWGEYR AVTPQGRPDA EYWNSQKDIL
 ESTRAELDTV CMHNYEVAYR GILQRRVEPT VTISLSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNNQEE TVGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGIGGLVL GLIFLGLGLI
 IRQRSQKGLL HX*   
>DL;IPD:MHC03494
IPD:MHC03494 Mamu-DQB1*06:02:02 84 bases
 YQFKGLCYFT NGTERVRSVT RHIYNREEYV RFDSDWGEYR AVTPQGRPDA
 EYWNSQKDIL ESTRAELDTV CMHNYEVAYR GILQ* 
>DL;IPD:MHC04024
IPD:MHC04024 Mamu-DQB1*06:02:03 90 bases
 EDFVYQFKGL CYFTNGTERV RSVTRHIYNR EEYVRFDSDW GEYRAVTPQG
 RPDAEYWNSQ KDILESTRAE LDTVCMHNYE VAYRGILQRR *
>DL;IPD:MHC00400
IPD:MHC00400 Mamu-DQB1*06:05 262 bases
 MSWKKALRIP GGLRVATVTL MLAMLSTPVT EGRDSPEDFV YQFKGLCYFT
 NGTERVRLVS RFIYNREEYA RFDSDVGEYR AVTPQGRPDA EYWNSQKDIL
 ERTRAELDTV CRHNYEVAYR GILQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNNQEE TVGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVQW RAQSESAQSK LLSGIGGLVL GLIFFGLGLI
 IRQRSQKGLP HX*   
>DL;IPD:MHC00401
IPD:MHC00401 Mamu-DQB1*06:06 262 bases
 MSWKKALRIP DGLRAATVTL MLAMLSTPVA EGRDAPEDFV VQFKGLCYYT
 NGTERVRLVT RYIYNREEYA RFDSDWGEYR AVTPQGRPDA EYWNSQKDIL
 ERTRAELDTV CIHNYEVVYR GILQRRVEPT VTISLSRTEA LNHHNLLVCS
 VTDFYPGQVK VRWFRNNQEE TVGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SVQSPITVEW RAQSESAQSK MLSGIGGFVL GLIFFGLGLI
 IRQRSQKGLL HX*   
>DL;IPD:MHC00402
IPD:MHC00402 Mamu-DQB1*06:07 89 bases
 DFVYQFKGLC YFTNGTERVR LVSRYIYNRE EYVRFDSDVG EYRAVTPQGR
 PDAEYWNSQK DILESKRAEL DTVCKHNYEV AYRGILQRR* 
>DL;IPD:MHC00403
IPD:MHC00403 Mamu-DQB1*06:08 89 bases
 DFVHQFKAMC YFTNGTERVR YVTRYIYNRE EYVRFDSAVG EHRAVTPQGR
 PDAEYWNSQK DILERTRAEL DTVCKHNYEV AFRGILQRR* 
>DL;IPD:MHC00404
IPD:MHC00404 Mamu-DQB1*06:09 262 bases
 MSWKKALRIP GGLRVATVTL MLAMLSTPVA EGRDSPEDFV YQFKGLCYFT
 NGTERVRSVT RHIYNREEYV RFDSDWGEYR AVTPQGRPTA EYWNSQKDIL
 ESTRAELDTV CMHNYEVAYR GILQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNNQEE TVGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGIGGLVL GLIFFGLGLI
 IRQRSQKGLL HX*   
>DL;IPD:MHC00405
IPD:MHC00405 Mamu-DQB1*06:10 89 bases
 DFVYQFKGLC YFTNGTERVR SVTRHIYNRE EYVRFDSDWG EYRAVTPQGR
 PAAEYWNSQK DILERTRAEL DTVCIHNYEV VYRGILQRR* 
>DL;IPD:MHC00406
IPD:MHC00406 Mamu-DQB1*06:11:01 262 bases
 MSWKKALRIP SGLRVATVTL MLAMLSTPVA EGRDSPEDFV FQFKGLCYFT
 NGTERVRHVT RYIYNREEFL RFDSAVGEYR AVTPQGRSDA EHLNSQKDVL
 ESTRAELDTV CMHNYEVTYR GILQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNNQEE TVGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGIGGFVL GLIFFGLGLI
 IRQRSQKGLL HX*   
>DL;IPD:MHC00407
IPD:MHC00407 Mamu-DQB1*06:11:02 89 bases
 DFVFQFKGLC YFTNGTERVR HVTRYIYNRE EFLRFDSAVG EYRAVTPQGR
 SDAEHLNSQK DVLESTRAEL DTVCMHNYEV TYRGILQRR* 
>DL;IPD:MHC00408
IPD:MHC00408 Mamu-DQB1*06:12 82 bases
 YQFKGLCYYT NGTERVRLVT RYIYNREEYA RFDSDWGEYR AVTPQGRPAA
 EYWNSQKDIL ERTRAELDTV CIHNYEVVYR GI* 
>DL;IPD:MHC00409
IPD:MHC00409 Mamu-DQB1*06:13:01 90 bases
 EDFVVQFKGL CYYTNGTERV RGVTRYIYNR EEYARFDSDW GEYRAVTPQG
 RPDAEYWNSQ KDILERTRAE LDTVCIHNYE VVYRGILQRR *
>DL;IPD:MHC02196
IPD:MHC02196 Mamu-DQB1*06:13:02 89 bases
 DFVVQFKGLC YYTNGTERVR GVTRYIYNRE EYARFDSDWG EYRAVTPQGR
 PDAEYWNSQK DILERTRAEL DTVCIHNYEV VYRGILQRR* 
>DL;IPD:MHC01626
IPD:MHC01626 Mamu-DQB1*06:14 262 bases
 MSWKKALRIP GGLRVATVTL MLAMLSTPVA EGRDSPEDFV YQFKGLCYFT
 NGTERVRSVT RHIYNREEYV RFDSDWGEYR AVTPQGRPDA EYWNSQKDIL
 ESTRAELDTV CMHNYEVAYR GILQRRVEPT VTISLSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNNQEE TVGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGIGGLVL GLIFFGLGLI
 IRQRSQKGLL HX*   
>DL;IPD:MHC02192
IPD:MHC02192 Mamu-DQB1*06:15 89 bases
 DFVYQFKGLC YFTNGTERVR SVTRYIYNRE EYVRFDSDWG EYRAVTPQGR
 PAAEYWNSQK DILERTRAEL DTVCIHNYEV VYRGILQRR* 
>DL;IPD:MHC02350
IPD:MHC02350 Mamu-DQB1*06:16 89 bases
 DFVVQFKGLC YFTNGTERVR LVSRFIYNRE EYARFDSDVG EYRAVTPQGR
 PDAEYWNSQK DILESTRAEL DTVCRHNYEV AYRGILQRR* 
>DL;IPD:MHC02905
IPD:MHC02905 Mamu-DQB1*06:17 89 bases
 DFVVQFKGLC YYTNGTERVR LVTRYIYNRE EYARFDSDWG EYRAVTPQGR
 PAAEYWNSQK DILERTRAEL DTVCIHNYEV VYRGILQRR* 
>DL;IPD:MHC03495
IPD:MHC03495 Mamu-DQB1*06:18 84 bases
 YQFKGLCYFT NGTERVRLVS RFIYNREEYA RFDSDVGEYR AVTPQGRPDA
 EYWNSQKDIL ESTRAELDTV CRHNYEVAYR GILQ* 
>DL;IPD:MHC03496
IPD:MHC03496 Mamu-DQB1*06:19 84 bases
 VQFKGLCYFT NGTERVRHVT RYIYNREEFL RFDSAVGEYR AVTPQGRSDA
 EHLNSQKDVL ESTRAELDTV CMHNYEVTYR GILQ* 
>DL;IPD:MHC04013
IPD:MHC04013 Mamu-DQB1*06:20 90 bases
 EDFVFQFKGM CYFTNGTERV RLVSRFIYNR EEYARFDSDV GEYRAVTPQG
 RPDAEYWNSQ KDILERTRAE LDTVCRHNYE VAYRGILQRR *
>DL;IPD:MHC04014
IPD:MHC04014 Mamu-DQB1*06:21 90 bases
 EDFVYQFKGM CYFTNGTERV RHVTRYIYNR EEYVRFDSDV GEHRAVTPQG
 RPDAEYWNSQ KDILERTRAE LDTVCKHNYE VAFRGILQRR *
>DL;IPD:MHC04015
IPD:MHC04015 Mamu-DQB1*06:22 89 bases
 DFVYQFKGLC YFINGTERVR GVTRHIYNRE EYVRFDSDWG EYRAVTPQGR
 PDAEYWNSQK DILESTRAEL DTVCMHNYEV AYRGILQRR* 
>DL;IPD:MHC00410
IPD:MHC00410 Mamu-DQB1*15:01 262 bases
 MSWKKALRIP GGLRAATVTL MLAMLSTPVA ECRDSPEDFV FQFKGMCYFT
 NGTERVWSVD RYIYNREEYV RFDSDVGLYL PVTPLGRSSA EYWNSQKEAL
 ESKRAELDTV CIHNYQLELG TTLQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNDQEE TTGIVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGIGGFVL GMIFLGLGLI
 IHHRSQKGLL HX*   
>DL;IPD:MHC00411
IPD:MHC00411 Mamu-DQB1*15:02 82 bases
 FQFKGMCYFT NGTERVWSVD RYIYNREEYV RFDSDVGLYL PVTPLGRSIA
 EYWNSQKEAL ESKRAELDTV CIHNYQLELG TT* 
>DL;IPD:MHC00412
IPD:MHC00412 Mamu-DQB1*15:03 262 bases
 MSWKKALRIP GGLRAATVTL MLAMLSTPVA ECRDSPEDFV FQFKGMCYFT
 NGTERVWSVD RYIYNREEYV RFDSDVGLYL PVTPLGRSSA EYMNSQKEAL
 ESKRAELDTV CIHNYQLELG TTLQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNDQEE TTGIVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGIGGFVL GMIFLGLGLI
 IHHRSQKGLL HX*   
>DL;IPD:MHC02193
IPD:MHC02193 Mamu-DQB1*15:04 89 bases
 DFVYQFKGLC YFTNGTERVW SVDRYIYNRE EYVRFDSDVG LYLPVTPLGR
 SSAEYWNSQK EALESKRAEL DTVCIHNYQL ELRTTLQRR* 
>DL;IPD:MHC04025
IPD:MHC04025 Mamu-DQB1*15:05 90 bases
 EDFVYQFKGM CYFTNGTERV WSVDRYIYNR EEYVRFDSDV GLYLPVTPLG
 RSSAEYMNSQ KEALESKRAE LDTVCIHNYQ LELGTTLQRR *
>DL;IPD:MHC00413
IPD:MHC00413 Mamu-DQB1*16:01 89 bases
 DFVHQFKFMC YFVNGTERVR AIARHVYNRE EFARFDSDVG VYRAVTPLGR
 SSAEYWNSQK EVLERKRAEL DTVCRHNYQL ELRSTLQRR* 
>DL;IPD:MHC00414
IPD:MHC00414 Mamu-DQB1*16:02 82 bases
 YQFKGMCYFT NGTERVRWVA RHVYNREEYA RFDSDVGVYR AVTPLGQSSV
 EYWNSQKEVL ESKRAALDTV CIHNYQLELR TT* 
>DL;IPD:MHC00415
IPD:MHC00415 Mamu-DQB1*16:03:01 76 bases
 YQFKGMCYFT NGTERVRLVA RHVYNREEFA RFDSDVGVYR EVTPMGQSWA
 EYWNSQKEVL ERKRAELDTV CRHNYQ*  
>DL;IPD:MHC03880
IPD:MHC03880 Mamu-DQB1*16:03:02 84 bases
 YQFKGMCYFT NGTERVRLVA RHVYNREEFA RFDSDVGVYR EVTPMGQSWA
 EYWNSQKEVL ERKRAELDTV CRHNYQLELL STLQ* 
>DL;IPD:MHC00416
IPD:MHC00416 Mamu-DQB1*17:02 82 bases
 YQFKCLCYFT NGTERVHYVT RHIYNREEYV RFDSDWGEYR AVTPQGRPTA
 EYWNNQKDFL ESTRAELDTV CKHNYELELL TT* 
>DL;IPD:MHC00417
IPD:MHC00417 Mamu-DQB1*17:03 262 bases
 MPRKKALRIP GGLWGTTVTL MLAMLSTPVA GGRDSPEDFV YQFKAMCYFT
 NGTERVHYVT RYIYNREEYA RFDSDVGKYL PVTPLGPPAA EYWNSQKDIL
 ERTRAELDTV CRHNYQLELH TTLQWRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VQWFRNDQEE TAGIVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGVGGFVL GLIFLGLGLI
 IHHRSQKGLL HX*   
>DL;IPD:MHC00418
IPD:MHC00418 Mamu-DQB1*17:04 82 bases
 YQFKCLCYFT NGTERVHFVT RHIYNREEYV RFDSDWGEYR AVTPLGRPAA
 EYWNSQKDFL ESTRAELDTV CKHNYQLELL TT* 
>DL;IPD:MHC00419
IPD:MHC00419 Mamu-DQB1*17:05 89 bases
 DFVYQFKCLC YFTNGTERVH YVTRHIYNRE EYVRFDSDWG EYRAVTPLGR
 PAAEYWNSQK DILESTRAEL DTVCKHNYQL ELLTTLQRR* 
>DL;IPD:MHC00420
IPD:MHC00420 Mamu-DQB1*17:06:01 89 bases
 DFVYQFKCLC YFTNGTERVH YVTRHIYNRE EYVRFDSDWG EYRAVTPLGR
 PTAEYWNSQK DFLESTRAEL DTVCKHNYQL ELLTTLQRR* 
>DL;IPD:MHC03500
IPD:MHC03500 Mamu-DQB1*17:06:02 88 bases
 DFVYQFKCLC YFTNGTERVH YVTRHIYNRE EYVRFDSDWG EYRAVTPLGR
 PTAEYWNSQK DFLESTRAEL DTVCKHNYQL ELLTTLQR* 
>DL;IPD:MHC00421
IPD:MHC00421 Mamu-DQB1*17:07 89 bases
 DFVYQFKAMC YFTNGTERVH YVTRYIYNRE EYARFDSDVG KYLPVTPLGP
 PAAEYWNSQK DFLESTRAEL DTVCRHNYQL ELRTILQRR* 
>DL;IPD:MHC00423
IPD:MHC00423 Mamu-DQB1*17:09 89 bases
 DFVYQFKCLC YFTNGTERVH YVTRHIYNRE EYVRFDSDWG EYRAVTPLGR
 PAAEYWNSQK DFLESTRAEL DTVCKHNYQL ELLTTLQRR* 
>DL;IPD:MHC01277
IPD:MHC01277 Mamu-DQB1*17:10 89 bases
 DFVYQFKGLC YFTNGTERVR LVTRHVYNRE EYVRFDSDWG EYRAVTPLGR
 PTAEYWNSQK DFLESTRAEL DTVCKHNYQL ELLTTLQRR* 
>DL;IPD:MHC02194
IPD:MHC02194 Mamu-DQB1*17:11 89 bases
 DFVYQFKAMC YFTNGTERVH YVTRYIYNRE EYARFDSDVG KYLPVTPLGP
 PDAEYWNSQK DFLESTRAEL DTVCRHNYQL ELRTILQRR* 
>DL;IPD:MHC03499
IPD:MHC03499 Mamu-DQB1*17:12 90 bases
 EDFVYQFKCL CYFTNGTERV HYVTRHIYNR EEYVRFDSDW GEYRAVTPLG
 RPTAEYWNNQ KDFLESTRAE LDTVCKHNYQ LELLTTLQRR *
>DL;IPD:MHC04026
IPD:MHC04026 Mamu-DQB1*17:13 90 bases
 EDFVYQFKAM CYFTNGTERV HYVTRYIYNR EEYARFDSDV GKYLPVTPLG
 PPAAEYWNSQ KDVLERTRAE LDTVCRHNYQ LELRTILQRR *
>DL;IPD:MHC00424
IPD:MHC00424 Mamu-DQB1*18:01 242 bases
 MLAMLSTPVA EGRDSPEDFV HQFKGLCYFT NGTERVRSVT RYIYNREEYV
 RFDSDWGEYR AVTPQGQSDA EYWNSQKDIL ERTRAELDTV CIHNYQLELR
 TTLQRRVEPT VTISPSRTEA LNHHNLLVCS VTDFYPGQIK VRWFRNDQEE
 TAGIVSTPLI RNGDWTFQIL VMLEMTPQRG DVYTCHVEHP SLQRPITVEW
 RAQSESAQSK MLSGVGGFVL GLIFLGLGLI IHHRSQKGLL HX*
>DL;IPD:MHC00425
IPD:MHC00425 Mamu-DQB1*18:02 262 bases
 MPRKKALRIP GGLWGTTVTL MLAMLSTPVA GGRDSPEDFV YQFKGLCYFT
 NGTERVRLVT RYIYNREEYV RFDSDWGEYR AVTPLGPPAA EYWNSQKDIL
 ERTRAELDTV CRHNYQSELR TTLQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNDQEE TAGIVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGVGGFVL GLIFLGLGLI
 IHYRSQKGLL HX*   
>DL;IPD:MHC00426
IPD:MHC00426 Mamu-DQB1*18:03 262 bases
 MPPKKALRIP GGLWGTTVTL MLAMLSTPVA EGRDSPEDFV YQFKGLCYFT
 NGTERVRLVT RHISNREEFV RFDSDWGEYR AVTPLGRPDA EYWNSQKDFL
 ERTRASVDTV CRHNYQSELR TTLQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VQWFRNDQEE TAGIVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQRPITVEW RAQSESAQSK MLSGVGGFVL GLIFLGLGLI
 IHHRSQKGLL HX*   
>DL;IPD:MHC00427
IPD:MHC00427 Mamu-DQB1*18:04 262 bases
 MPPKKALRIP GGLWGTTVTL MLAMLSTPVA EGRDSPEDFV YQFKGLCYFT
 NGTERVRLVT RHISNREEFV RFDSDWGEYR AVTPLGRPDA EYWNSQKDIL
 ERTRAELDTV CRHNYQSELR TTLQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VQWFRNDQEE TAGIVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQRPITVEW RAQSESAQSK MLSGVGGFVL GLIFLGLGLI
 IHHRSQKGLL HX*   
>DL;IPD:MHC00428
IPD:MHC00428 Mamu-DQB1*18:07 82 bases
 YQFKGLCYFI NGTERVRGVT RHIYNREEYV RFDSDWGEYR AVTPLGRPDA
 EYWNSQKDIL ESTRAEADTV CRHNYQLELR TT* 
>DL;IPD:MHC00429
IPD:MHC00429 Mamu-DQB1*18:08 262 bases
 MSWKKALRIP GGLRAATVTL MLAMLSTPVA EGRDSPEDFV FQFKGMCYFI
 NGTEHVHHVN RYIYNREEFV GFDSYLGVYR PVTPLGRSWA EYWNSQKDIL
 ERTRAVVDTV CRHNYQSELR TTLQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNDQEE TTGIVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK MMSGIGGFVL GLIFLALGLI
 IHHRSQKGLL HX*   
>DL;IPD:MHC00430
IPD:MHC00430 Mamu-DQB1*18:09 262 bases
 MPRKKALRIP GGLWGTTVTL MLAMLSTPVA EGRDSPEDFV YQFKGLCYFI
 NGTERVRGVT RHIYNREEYV RFDSDWGEHR AVTPLGRSWA EYWNNQKDFL
 ETTRASVDTV CRHNYQSELR TTLQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPSQIK VKWFRNDQEE TTGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCRVEHP SLQSPITVEW RAQSESAQSK MLSGVGGFVL GLIFLGLGLI
 IHYRSQKGLP HX*   
>DL;IPD:MHC00431
IPD:MHC00431 Mamu-DQB1*18:10 262 bases
 MPRKKALRIP GGLWGTTVTL MLAMLSTPVA EGRDSPEDFV VQFKGLCYFT
 NGTERVRHVT RYIYNREEYA RFDSDWGEYR AVTPLGRPDA EYWNSQKDIL
 ESTRAEADTV CRHNYQSELR TTLQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNDQQE TAGIVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGVGGFVL GLIFLGLGLI
 IHHRSQKGLP HX*   
>DL;IPD:MHC00432
IPD:MHC00432 Mamu-DQB1*18:11 262 bases
 MPRKKALRIP GGLWGTTVTL MLAMLSTPVA EGRDSPEDFV YQFKGLCYFI
 NGTERVRGVT RHIYNREEYV RFDSDWGEHR AVTPLGRSWA EYWNNQKDFL
 ETTRASVDTV CRHNYQLELR TTLQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPSQIK VKWFRNDQEE TTGVVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCRVEHP SLQSPITVEW RAQSESAQSK MLSGVGGFVL GLIFLGLGLI
 IHYRSQKGLP HX*   
>DL;IPD:MHC00433
IPD:MHC00433 Mamu-DQB1*18:12 90 bases
 EDFVYQFKGL CYFTNGTERV RLVTRYIYNR EEYVRFDSDW GEYRAVTPLG
 PPDAEYWNSQ KDILESTRAE ADTVCRHNYQ SELRTTLQRR *
>DL;IPD:MHC00434
IPD:MHC00434 Mamu-DQB1*18:13 82 bases
 VQFKGLCYFT NGTERVRSVT RYIYNREEYA RFDSDWGEYR AVTPLGRPDA
 EYWNSQKDIL ESTRAEADTV CIHNYQSELR TT* 
>DL;IPD:MHC00435
IPD:MHC00435 Mamu-DQB1*18:14 82 bases
 FQFKGLCYFT NGTERVRHVT RYIYNREEYA RFDSDWGEYR AVTPLGRSWA
 EYWNNQKDIL ESTRAEADTV CRHNYQSELR TT* 
>DL;IPD:MHC01067
IPD:MHC01067 Mamu-DQB1*18:15 89 bases
 DFVYQFKGLC YFINGTERVR GVTRHIYNRE EYVRFDSDWG EYRAVTPLGR
 SWAEYWNNQK DFLETTRASV DTVCKHNYQL ELRTTLQRR* 
>DL;IPD:MHC02191
IPD:MHC02191 Mamu-DQB1*18:17 89 bases
 DFVYQFKGLC YFTNGTERVR LVTRHVYNRE EYVRFDSDWG EHRAVTPLGR
 PSAEYWNSQK DFLETTRASV DTVCKHNYQS ELRTTLQRR* 
>DL;IPD:MHC02195
IPD:MHC02195 Mamu-DQB1*18:18 89 bases
 DFVFQFKGLC YFTNGTERVR HVTRYIYNRE EYARFDSDWG EYRAVTPLGR
 PDAEYWNSQK DILESTRAEA DTVCRHNYQS ELRTTLQRR* 
>DL;IPD:MHC02197
IPD:MHC02197 Mamu-DQB1*18:19 89 bases
 DFVVQFKGLC YFTNGTERVR SVTRYIYNRE EYARFDSDWG EYRAVTPLGR
 PDAEYWNSQK DILESTRAEA DTVCRHNYQS ELRTTLQRR* 
>DL;IPD:MHC02198
IPD:MHC02198 Mamu-DQB1*18:20 89 bases
 DFVVQFKGLC YFTNGTKRVR LVTRYIYNRE EYARFDSDWG EYRAVTPLGR
 PDAEYWNSQK DILESTRAEA DTVCRHNYQS ELRTTLQRR* 
>DL;IPD:MHC02199
IPD:MHC02199 Mamu-DQB1*18:21 89 bases
 DFVYQFKGLC YFINGTERVR GVTRYIYNRE EFVRFDSDWG EHRAVTPLGR
 SWAEYWNNQK DFLETTRASV DTVCRHNYQS ELRTTLQRR* 
>DL;IPD:MHC02906
IPD:MHC02906 Mamu-DQB1*18:22 89 bases
 DFVVQFKGLC YFTNGTERVR LVTRYIYNRE EYARFDSDWG EYRAVTPLGR
 PDAEYWNSQK DILESTRAEA DTVCRHNYQS ELRTTLQRR* 
>DL;IPD:MHC03497
IPD:MHC03497 Mamu-DQB1*18:23 88 bases
 DFVYQFKGLC YFINGTERVR GVTRHIYNRE EYVRFDSDWG EHRAVTPLGR
 SWAEYWNNQK DFLETTRASV DTVCRHNYQL ELRTTLQR* 
>DL;IPD:MHC03498
IPD:MHC03498 Mamu-DQB1*18:24 90 bases
 EDFVVQFKGL CYFTNGTERV RHVTRYIYNR EEYVRFDSDW GEYRAVTPLG
 RPDAEYWNSQ KDILESTRAE ADTVCRHNYQ SELRTTLQRR *
>DL;IPD:MHC03578
IPD:MHC03578 Mamu-DQB1*18:25 262 bases
 MPWKKALRIP GGLLGATVTL MLAMLSTPVA EGRDSPEDFV HQFKGLCYFT
 NGTERVRSVT RYIYNREEYV RFDSDWGEYR AVTPQGQSDA EYWNSQKDIL
 ERTRAELDMV CIHNYQLELR TTLQRRVEPT VTISPSRTEA LNHHNLLVCS
 VTDFYPGQIK VRWFRNDQEE TAGIVSTPLI RNGDWTFQIL VMLEMTPQRG
 DVYTCHVEHP SLQRPITVEW RAQSESAQSK MLSGVGGFVL GLIFLGLGLI
 IHHRSQKGLL HX*   
>DL;IPD:MHC04027
IPD:MHC04027 Mamu-DQB1*18:26N 60 bases
 EDFVYQFKGL CYFTNGTERV RLVTRYIYNR EEYVRFDSDW GEYRAVTPLG
 PPAAEYWNSX *   
>DL;IPD:MHC00436
IPD:MHC00436 Mamu-DQB1*24:01 89 bases
 DFVVQFKAMC YFTNGTERVH YVTRYIYNRE EFARFDSDVW EYRAVTPLGR
 SWAENWNNQK DVLERTRAEL DTVCRHNYQL ELLSTLQRR* 
