>DL;IPD:MHC00378
IPD:MHC00378 Mamu-DQA1*01:02 256 bases
 MILNKALMLG ALALTTMMSP CGGEDIVADH VASCGVNLYQ TYGLSGQFTH
 EFDGDEQFYV DLRRKETAWR WPELSKFGGF DPQGALRNLA VLKHNLNIVT
 KRYNSTAATN EVPEVTVFSK SPVTLGHPNT LICLVDNIFP PVVNITWLSN
 GRSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCR VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII QGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC00379
IPD:MHC00379 Mamu-DQA1*01:04:01 256 bases
 MILNKALMLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ SYGPSGQYTH
 EFDGDEQFYV DLGRKETAWR WPELSKFGGF DPQGALRNLA TVKYNLNIMT
 KRYNSTAATN EVPEVTVFSK SPVTLGQPNT LICLVDNIFP PVVNITWLSS
 GRSVTEGVSE TSFLSKSDHS FIKISYLTFL PSADEIYDCR VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII QGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC05130
IPD:MHC05130 Mamu-DQA1*01:04:02 82 bases
 DHVASCGVNL YQSYGPSGQY THEFDGDEQF YVDLGRKETA WRWPELSKFG
 GFDPQGALRN LATVKYNLNI MTKRYNSTAA TN* 
>DL;IPD:MHC00380
IPD:MHC00380 Mamu-DQA1*01:05:01 256 bases
 MILNKALMLG ALVLTAVMSP CGGEDIVADH VASCGVNLYQ TYGLSGQYTH
 EFDGDEQFYV DLERKETAWR WPELSKFGGF DPQGALRNLA VSKHNLNIMT
 KRYNSTAAIN EVPEVTVFSK SPVTLGHPNT LICLVDNIFP PVVNITWLSN
 GHSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCR VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII QGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC05059
IPD:MHC05059 Mamu-DQA1*01:05:03 227 bases
 GEDIVADHVA SCGVNLYQTY GLSGQYTHEF DGDEQFYVDL ERKETAWRWP
 ELSKFGGFDP QGALRNLAVS KHNLNIMTKR YNSTAAINEV PEVTVFSKSP
 VTLGHPNTLI CLVDNIFPPV VNITWLSNGH SVTEGVSETS FLSKSDHSFF
 KISYLTFLPS ADEIYDCRVE HWGLDEPLLK HWEPEIPAPM SELTETVVCA
 LGLSVGLVGI VVGTVFIIQG LRSVGAS*  
>DL;IPD:MHC00382
IPD:MHC00382 Mamu-DQA1*01:06 256 bases
 MILNKALMLG ALVLTAVMSP CGGEDIVADH VASCGVNLYQ TYGLSGQYTH
 EFDGDERFYV DLERKETAWR WPELSKFGGF DPQGALRNLA VLKHTLNIVT
 KRYNSTAATN EVPEVTVFSK SPVMLGQPNT LICLVDNIFP PVVNITWLSN
 GRSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCR VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII QGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC00383
IPD:MHC00383 Mamu-DQA1*01:07 74 bases
 DHVASCGVNL YQTYGLSGQY THEFDGDERF YVDLERKETA WRWPELSKFG
 GFDPQGALRN LAVSKHNLNI MTKR*  
>DL;IPD:MHC00384
IPD:MHC00384 Mamu-DQA1*01:08 227 bases
 GEDIVADHVA SCGVNLYQSY GPSGQFTHEF DGDEQFYVDL GRKETAWRWP
 ELSKFGGFDP QGALRNLAAA KHNLNILTKR YNFTAATNEV PEVTVFSKSP
 VTLGQPNTLI CLVDNIFPPV VNITWLSNGR SVTEGVSETS FLSKSDHSFF
 KISYLTFLPS ADEIYDCRVE HWGLDEPLLK HWEPEIPAPM SELTETVVCT
 LGLSVGLVGI VVGTVFIIQG LRSVGAS*  
>DL;IPD:MHC00381
IPD:MHC00381 Mamu-DQA1*01:09 256 bases
 MILNKALMLG ALVLTAVMSP CGGEDIVADH VASCGVNLYQ TYGLSGQYTH
 EFDGDEQFYV DLERKETAWR WPELSKFGGF DPQGALRNLA VSKHNLNIMT
 KRYNSTAATN EVPEVTVFSK SPVTLGHPNT LICLVDNIFP PVVNITWLSN
 GHSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCR VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII QGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC00385
IPD:MHC00385 Mamu-DQA1*05:01 62 bases
 SYGFSGQFTH EFDGDEQFYV DLERKETVWQ LPVLSQFSFD AQFALTNIAV
 GKQNLNYLMK QS*   
>DL;IPD:MHC00386
IPD:MHC00386 Mamu-DQA1*05:02 61 bases
 SYGFSGQYSH EFDGDEQFYV DLERKETVWQ LPVLSQFSFD AQFALTNIAV
 GKQNLNYLMK Q*   
>DL;IPD:MHC00387
IPD:MHC00387 Mamu-DQA1*05:03 59 bases
 FSGQYSHEFD GDEQFYVDLE RKETVWRLPV LSQFSFDAQF ALTNIAVGKQ
 NLNYLMKQS*    
>DL;IPD:MHC01276
IPD:MHC01276 Mamu-DQA1*05:04 255 bases
 MILNKALMLG ALALTTVMSS CGGEDIVADH LASYGVNFYQ SYGLSGQYSH
 EFDGDEQFYV DLGRKETVWR LPIPYRYGFD PQFALRNIAV LTHNLNVLIK
 RSNSTAATNE VPEVTVFSKS PVTLGHPNTL ICLVDHIFPP VVNITWLSNG
 RSVTEGVSET SFLSKSDHSF FKISYLTFLP SADEIYDCRV EHWGLDEPLL
 KHWEPEIPAP MSELTETVVC ALGLSAGLVG IVVGTILIIR GLRSVGASRH
 QGPLX*    
>DL;IPD:MHC05063
IPD:MHC05063 Mamu-DQA1*05:05 226 bases
 GEDIVADHVA SYGVNVYQSY GPSGQFTHEF DGDEQFYVDL GRKETVWRLP
 IPYRYGFDPQ FALRNIAVLT HNLNILIKRS NSTAATNEVP EVTVFSKSPV
 MLGQPNTLIC LVDNIFPPVV NITWLSNGHS VIEGVSETSF LSKSDHSFFK
 ISYLTFLPSA DEIYDCRVEH WGLDEPLLKH WEPEIPVPMS ELTETVVCAL
 GLSAGLVGIV VGTVLIIRGL RSVGAS*  
>DL;IPD:MHC05131
IPD:MHC05131 Mamu-DQA1*05:06 81 bases
 DHVASYGVNV YQSYGPSGQY SHEFDGDEQF YVDLGRKETV WRLPIPYRYG
 FDPQFALRNI AVLTHNLNIL IKRSNSTAAT N* 
>DL;IPD:MHC00388
IPD:MHC00388 Mamu-DQA1*23:01 256 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNMYQ SYGPSGQYTH
 EFDGDEEFYV DLERKQTVWQ LPLFSKFRRF DPQGALRNIA VLQHNLNIVI
 KRSNSTAATN EVPEVTVFSK SPVMLGQPNT LICLVDNIFP PVVNITWLSN
 GHSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCK VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII RGLRSIGASR
 HQGPLX*    
>DL;IPD:MHC00389
IPD:MHC00389 Mamu-DQA1*23:02 256 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNVYQ SYGPSGQYTH
 EFDGDEEFYV DLERKQTVWQ LPLFSKFRRF DPQRALRNIA VLQHNLNIVI
 KRSNSTAATN EVPEVTVFSK SPVMLGQPNT LICLVDNIFP PVVNITWLSN
 GHSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCK VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII RGLRSIGASR
 HQGPLX*    
>DL;IPD:MHC02421
IPD:MHC02421 Mamu-DQA1*23:03 256 bases
 MILNKALLLG ALTLTTVMSP CGGEDIVADH VASYGVNMYQ SYGPSGQFTH
 EFDGDEEFYV DLERKQTVWQ LPLFSKFRRF DPQGALRNIA VLQHNLNIVI
 KRSNSTAATN EVPEVTVFSK SPVMLGQPNT LICLVDNIFP PVVNITWLSN
 GHSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCK VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII RGLRSIGASR
 HQGPLX*    
>DL;IPD:MHC00390
IPD:MHC00390 Mamu-DQA1*24:01:01 256 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNMYQ SYGPSGQYTH
 EFDGDEEFYV DLERKETVWQ LPLFSKFRSF DPQGALRNLA VGKHNLNILI
 KRSNSTAATN EVPEVTVFSK SPVTLGHPNT LICLVDNIFP PVVNITWLSN
 GRSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCK VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSMGLV GIVVGTVLII RGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC05019
IPD:MHC05019 Mamu-DQA1*24:01:02 227 bases
 GEDIVADHVA SYGVNMYQSY GPSGQYTHEF DGDEEFYVDL ERKETVWQLP
 LFSKFRSFDP QGALRNLAVG KHNLNILIKR SNSTAATNEV PEVTVFSKSP
 VTLGHPNTLI CLVDNIFPPV VNITWLSNGR SVTEGVSETS FLSKSDHSFF
 KISYLTFLPS ADEIYDCKVE HWGLDEPLLK HWEPEIPAPM SELTETVVCA
 LGLSMGLVGI VVGTVLIIRG LRSVGAS*  
>DL;IPD:MHC00391
IPD:MHC00391 Mamu-DQA1*24:02 256 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH
 EFDGDEEFYV DLERKETVWQ LPLFSKFRSF DPQGALRNLA VSKHNLNILI
 KHSNSTAATN EVPEVTVFSK SPVTLGHPNT LICLVDNIFP PVVNITWLSN
 GRSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCK VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CTLGLSMGLV GIVVGTVLII RGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC00392
IPD:MHC00392 Mamu-DQA1*24:03 63 bases
 SYGPSGQYTH EFDGDEEFYV DLERKETIWQ LPLFSKFRSF DPQGALRNLA
 VGKHNLNILI KCS*   
>DL;IPD:MHC00393
IPD:MHC00393 Mamu-DQA1*24:04 63 bases
 SYGPSGQYTH EFDGDEEFYV DLERKETVWQ LPLFSKFRSF DPQGALRNLA
 VGKHNLNILI KHS*   
>DL;IPD:MHC02630
IPD:MHC02630 Mamu-DQA1*24:05 256 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH
 EFDGDEEFYV DLERKETVWQ LPLFSKFRSF DPQGALRNLA VGKHNLNILI
 KRSNSTAATN EVPEVTVFSK SPVTLGHPNT LICLVDNIFP PVVNITWLSN
 GRSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCK VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVLII RGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC05058
IPD:MHC05058 Mamu-DQA1*24:06 227 bases
 GEDIVADHVA SYGVNLYQSY GPSGQYTHEF DGDEEFYVDL ERKETVWQLP
 LFSKFRSFDP QGALRNLAVG KHNLNILIKR SNSTAATNEV PEVTVFSKSP
 VTLGHPNTLI CLVDNIFPPV VNITWLSNGR SVTEGVSETS FLSKSDHSFF
 KISYLTFLPS ADEIYDCKVE HWGLDEPLLK HWEPEIPAPM SELTETVVCA
 LGLSMGLVGI VVGTVLIIRG LRSVGAS*  
>DL;IPD:MHC05060
IPD:MHC05060 Mamu-DQA1*24:07 227 bases
 GEDIVADHIA SYGVNLYQSY GPSGQYTHEF DGDEEFYVDL ERKETVWQLP
 LFSKFRSFDP QGALRNLAVG KHNLNILIKR SNSTAATNEV PEVTVFSKSP
 VTLGHPNTLI CLVDNIFPPV VNITWLSNGR SVTEGVSETS FLSKSDHSFF
 KISYLTFLPS ADEIYDCKVE HWGLDEPLLK HWEPEIPAPM SELTETAVCA
 LGLSMGLVGI VVGTVLIIRG LRSVGAS*  
>DL;IPD:MHC05064
IPD:MHC05064 Mamu-DQA1*24:08 227 bases
 GEDIVADHVA SYGVNLYQSY GPSGQFTHEF DGDEEFYVDL ERKETVWQLP
 LFSKFRSFDP QGALRNLAVG KHNLNILIKR SNSTAATNEV PEVTVFSKSP
 VTLGHPNTLI CLVDNIFPPV VNITWLSNGH SVTEGVSETS FLSKSDHSFF
 KISYLTFLPS ADEIYDCKVE HWGLDEPLLK HWEPEIPAPM SELTETVVCA
 LGLSMGLVGI VVGTVLIIRG LRSVGAS*  
>DL;IPD:MHC05067
IPD:MHC05067 Mamu-DQA1*24:09 227 bases
 GEDIVADHIA SYGVNMYQSY GPSGQYTHEF DGDEEFYVDL ERKETVWQLP
 LFSKFRSFDP QGALRNLAVG KHNLNILIKR SNSTAATNEV PEVTVFSKSP
 VTLGHPNTLI CLVDNIFPPV VNITWLSNGR SVTEGVSETS FLSKSDHSFF
 KISYLTFLPS ADEIYDCKVE HWGLDEPLLK HWEPEIPAPM SELTETVVCA
 LGLSMGLVGI VVGTVLIIRG LRSVGAS*  
>DL;IPD:MHC05068
IPD:MHC05068 Mamu-DQA1*24:10 227 bases
 GEDIVADHVA SYGVNVYQSY GPSGQFTHEF DGDEEFYVDL ERKETVWQLP
 LFSKFRSFDP QGALRNLAVG KHNLNILIKR SNSTAATSEV PEVTVFSKSP
 VTLGHPNTLI CLVDNIFPPV VNITWLSNGR SVTEGVSETS FLSKSDHSFF
 KISYLTFLPS ADEIYDCKVE HWGLDEPLLK HWEPEIPAPM SELTETVVCA
 LGLSMGLVGI VVGTVLIIRG LRSVGAS*  
>DL;IPD:MHC00394
IPD:MHC00394 Mamu-DQA1*26:01 256 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ TYGLSGQYTH
 EFDGDEQFYV DLERKETVWR LPLFSKFGGF DPQGALRNLA VSKHNLNIMI
 KRSNSTAATN EVPEVTVFSK SPVTLGHPNT LICLVDNIFP PVVNITWLSS
 GRSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCK VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVLII RGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC00395
IPD:MHC00395 Mamu-DQA1*26:02 256 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ TYGLSGQYTH
 EFDGDEQFYV DLERKETVWR LPLFSKFGGF DPQGALRNLA VGKHNLNILI
 KHSNSTAATN EVPEVTVFSK SPVTLGHPNT LICLVDNIFP PVVNITWLSN
 GHSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCR VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSMGLV GIVVGTVLII QGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC00396
IPD:MHC00396 Mamu-DQA1*26:03 256 bases
 MILNKALLLG ALALTTVMSP CRGEDIVADH IASYGVNLYQ TYGLSGQFTH
 EFDGDEQFYV DLERKETVWR LPLFSKFGGF DPQGALRNLA VGKHNLNILI
 KHSNSTAATN EVPEVTVFSK SPVTLGHPNT LICLVDNIFP PVVNITWLSN
 GHSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCR VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSMGLV GIVVGTVLII RGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC00397
IPD:MHC00397 Mamu-DQA1*26:04 52 bases
 FDGDEQFYVD LERKEAVWRL PLLSKFGGFD PQGALRNLAV SKHNLNIMIK
 RS*    
>DL;IPD:MHC02904
IPD:MHC02904 Mamu-DQA1*26:05 75 bases
 DHVASYGVNL YQTYGLSGQY THEFDGDEQF YVDLERKETV WRLPLLSKFG
 GFDPQGALRN LAVSKHNLNI MIKRS*  
>DL;IPD:MHC03806
IPD:MHC03806 Mamu-DQA1*26:06 256 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ TYGLSGQYTH
 EFDGDEQFYV DLERKETVWR LPLFSKFGGF DPQGALRNLA VGKHNLNILI
 KHSNSTAATN EVPEVTVFSK SPVTLGHPNT LICLVDNIFP HVVNITWLSN
 GHSVTEGVSE TSFLSKSDHS FFKISYLTFL PSADEIYDCR VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLSMGLV GIVVGTVLII QGLRSVGASR
 HQGPLX*    
>DL;IPD:MHC05065
IPD:MHC05065 Mamu-DQA1*26:07 227 bases
 GEDIVADHIA SYGVNLYQTY GLSGQFTHEF DGDEQFYVDL ERKETVWRLP
 LFSKFGGFDP QGALRNLAVG KHNLNILIKH SNSTAATNEV PEVTVFSKSP
 VTLGHPNTLI CLVDNIFPPV VNITWLSNGH SVTEGVSETS FLSKSDHSFF
 KISYLTFLPS ADEIYDCRVE HWGLDEPLLK HWEPEIPAPM SELTETVVCA
 LGLSMGLVGI VVGTVLIIQG LRSVGAS*  
>DL;IPD:MHC05066
IPD:MHC05066 Mamu-DQA1*26:08 227 bases
 GEDIVADHIA SYGVNLYQTY GLSGQFTHEF DGDEQFYVDL ERKETVWRLP
 LFSKFGGFDP QGALRNLAVG KHNLNILIKH SNSTAATNEV PEVTVFSKSP
 MTLGHPNTLI CLVDNIFPPV VNITWLSNGH SVTEGVSETS FLSKSDHSFF
 KISYLTFLPS ADEIYDCKVE HWGLDEPLLK HWEPEIPAPM SELTETVVCA
 LGLSVGLVGI VVGTVLIIRG LRSVGAS*  
