>DL;IPD:MHC00355
IPD:MHC00355 Mamu-AG*01:01 1073 bases
 CTCCTCCTAG TGCTCTCAGG GGTCCTGGCC CCGACCCAGA CCCGGGCGGG
 CTCCCACTCC ATGAGGTATT TCTACACCTC CGTGTCCCGG CCCGGCCGCT
 GGGAGCCCCG CTTCATCGCC GTGGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCCGA GAGTCCGAGG ATGGAGCCGC GGGCGCCGTG
 GGTGGAGCAG GAGGGGCCGG AGTATTGGGA CCGGGAGACA CAGAACATGA
 AGACCCCGAC ACAGACCTAC CGAGTGAACC TGCGGACCCT GCTCCGCTAC
 TACAACCAGA GCGAGGCCGG GTCTCACACC ATCCAGAAGA TGTACGGCTG
 CGACCTGGGG CCCGACGGGC GCCTCCTCCG CGGGTATGAA CAGTTCGCCT
 ACGACGGCAG GGATTACATC ATCCTGAACG AGGACCTGCG CTCCTGGACT
 GCCGCGGACA TGGCGGCTCA GAACACCCAG CGCAAGTGGG AGGCGGCGGG
 TGCGGCGGAG CAGCACAGAA CCTACCTGGA GGGCGAGTGC CTGGAGTGGC
 TCCGCAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CGCGGACCCC
 CCCAAGACAC ATGTGACCCA CCACCCCGTC TCTGACTACG AGGCCACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG AGAGGAACAA ACTCAGGACA CAGAGCTCAT GGAGACCAGG
 CCTACAGGGA ATGGAACCTT CCAGAAGTGG GCGGCTGTGG TGGTGCCTTC
 TGGAGAGGAG CAGAGATACA CCTGTCATGT GCAACATGAG GGTCTGCCCA
 AGCCCCTCAC CTTGAGATGG GAGTTGTCTT CCCAGCCCAC CATCCCCATC
 GTGGGCATCA TTGCTGGCCT GGTTCTGCTT GGAACTGTGG TCACTGGAGC
 TGTGGTTGCT GCTGTGATGT GGAGGAGGAA GAGCTCAGAT AGATAAGGCG
 GGAGCTACTC TCAGGCTGCA AGCAGTGACA GTGCCCAGGG CTCTGATGTG
 TCTCTCACGG CTTTAAAGTG TGA*  
>DL;IPD:MHC00356
IPD:MHC00356 Mamu-AG*02:01:01 1074 bases
 CTCCTCCTGG TGCTCTCAGG GGTCCTGGCC CTGACCCAGA CCCGGGCGGG
 CTCGCACTCC ATGAGGTATT TCTACACCTC CATGTCCCGG CCCGGCCGCG
 GGCAGCCCCG CTTCATCGCC GTGGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCCGA GAGTCCGAGG ATGGAGCCGC GGGCGCCGTG
 GGTGGAGCAG GAGGGGCCGG AGTATTGGGA CCGGGAGACA CAGAACATGA
 AGACCGCGAC ACAGACCTAC CGAGAGAACC TGCGGACCCT GCTCCGCTAC
 TACAACCAGA GCGAGGCCGG GTCTCACACC ATCCAGAAGA TGTACGGCTG
 CGACCTGGGG CCAGACGGGC GCCTCCTCCG CGGGTATGAA CAGTTCGCCT
 ACGACGGCAG GGATTACATC GCCCTGAACG AGGACCTGCG CTCCTGGACG
 GCCGCGGACA TGGCGGCTCA GAACACCCAG CGCAAGTGGG AGGCGGCGGG
 TGCGGCGGAG CAGCACAGAA CCTACCTGGA GGGCGAGTGC CTGGAGTGGC
 TCCGCAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CGCGGACCCC
 CCCAAGACAA ATGTGACCCA CCACCCTGTC TCTGACTACG AGGCCACCCT
 GAGGTGTTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG AGAGGAACAA ACTGAAGACA CAGAGCTCGT GGAGACCAGG
 CCTACAGGGG ATGGAACCTT CCAGAAGTGG GCGGCTGTGG TGGTGCCTTC
 TGGAGAGGAG CAGAGATACA CCTGTCATGT GCAACATGAG GGTCTGCCCG
 AGCCCCTCAC CTTGAGATGG GAGCCATCTT CCCAGTCTAC CATCCTCATC
 GTAGGCATCA TTGCTGGCCT GGTTCTCCTT GGAACTGTGG TCACTGGAGC
 TGTGGTTGCT GCTGTGATGT GGAGGAGGAA GAGCTCAGAT AGATAAGGCG
 GGAGCTACTC TCAGGCTGCA AGCAGTGACA GTTCCCAAGG TTCTGATGTG
 TCTCTCACGG CTTGTAAAGT GTGA*  
>DL;IPD:MHC00357
IPD:MHC00357 Mamu-AG*02:01:02 1071 bases
 CTCCTGGTGC TCTCAGGGGT ACTGGCCCTG ACCCAGACCC GGGCGGGCTC
 GCACTCCATG AGGTATTTCT ACACCTCCAT GTCCCGGCCC GGCCGCGGGC
 AGCCCCGCTT CATCGCCGTG GGCTACGTGG ACGACACGCA GTTCGTGCGG
 TTCGACAGCG ACGCCGAGAG TCCGAGGATG GAGCCGCGGG CGCCGTGGGT
 GGAGCAGGAG GGTCCAGAGT ATTGGGACCG GGAGACACAG AACATGAAGA
 CCGCGACACA GACCTACCGA GAGAACCTGC GGACCCTGCT CCGCTACTAC
 AACCAGAGCG AGGCCGGGTC TCACACCATC CAGAAGATGT ACGGCTGCGA
 CCTGGGGCCC GACGGGCGCC TCCTCCGCGG GTATGAACAG TTCGCCTACG
 ACGGCAGGGA TTACATCGCC CTGAACGAGG ACCTGCGCTC CTGGACGGCC
 GCGGACATGG CGGCTCAGAA CACCCAGCGC AAGTGGGAGG CGGCGGGTGC
 GGCGGAGCAG CACAGAACCT ACCTGGAGGG CGAGTGCCTG GAGTGGCTCC
 GCAGATACCT GGAGAACGGG AAGGAGACGC TGCAGCGCGC GGACCCCCCC
 AAGACAAATG TGACCCACCA CCCTGTCTCT GACTACGAGG CCACCCTGAG
 GTGCTGGGCC CTGGGCTTCT ACCCTGCGGA GATCACACTG ACCTGGCAGC
 GGGATGGAGA GGAACAAACT GAGGACACAG AGCTCGTGGA GACCAGGCCT
 ACAGGGGATG GAACCTTCCA GAAGTGGGCG GCTGTGGTGG TGCCTTCTGG
 AGAGGAGCAG AGATACACCT GTCATGTGCA ACATGAGGGT CTGCCCGAGC
 CCCTCACCTT GAGATGGGAG CCATCTTCCC AGTCTACCAT CCTCATCGTA
 GGCATCATTG CTGGCCTGGT TCTCCTTGGA ACTGTGGTCA CTGGAGCTGT
 GGTTGCTGCT GTGATGTGGA GGAGGAAGAG CTCAGATAGA TAAGGCGGGA
 GCTACTCTCA GGCTGCAAGC AGTGACAGTT CCCAAGGTTC TGATGTGTCT
 CTCACGGCTT GTAAAGTGTG A*  
>DL;IPD:MHC00358
IPD:MHC00358 Mamu-AG*02:02 1074 bases
 CTCCTCCTGG TGCTCTCAGG GGTACTGGCC CTGACCCAGA CCCGGGCGGG
 CTCGCACTCC ATGAGGTATT TCTACACCTC CATGTCCCGG CCCGGCCGCG
 GGCAGCCCCG CTTCATCGCC GTGGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCCGA GAGTCCGAGG ATGGAGCCGC GGGCGCCGTG
 GGTGGAGCAG GAGGGTCCAG AGTATTGGGA CCGGGAGACA CAGAACATGA
 AGACCGCGAC ACAGACCTAC CGAGAGAACC TGAGGACCCT GCTCCGCTAC
 TACAACCAGA GCGAGGCCGG GTCTCACACC ATCCAGAAGA TGTACGGCTG
 CGACCTGGGG CCCGACGGGC GCCTCCTCCG CGGGTATGAA CAGTTCGCCT
 ACGACGGCAG GGATTACATC GCCCTGAACG AGGACCTGCG CTCCTGGACG
 GCCGCGGACA TGGCGGCTCA GTTCACCCAG CGCAAGTGGG AGGCGGCGGG
 TGCGGCGGAG CAGCACAGAA CCTACCTGGA GGGCGAGTGC CTGGAGTGGC
 TCCGCAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CGCGGACCCC
 CCCAAGACAA ATGTGACCCA CCACCCTGTC TCTGACTACG AGGCCACCCT
 GAGGTGTTGG GCCCTCGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG AGAGGAACAA ACTGAGGACA CAGAGCTCGT GGAGACCAGG
 CCTACAGGGG ATGGAACCTT CCAGAAGTGG GCGGCTGTGG TGGTGCCTTC
 TGGAGAGGAG CAGAGATACA CCTGTCATGT GCAACATGAG GGTCTGCCCG
 AGCCCCTCAC CTTGAGATGG GAGCCATCTT CCCAGTCTAC CATCCTCATC
 GTAGGCATCA TTGCTGGCCT GGTTCTCCTT GGAACTGTGG TCACTGGAGC
 TGTGGTTGCT GCTGTGATGT GGAGGAGGAA GAGCTCAGAT AGATAAGGCG
 GGAGCTACTC TCAGGCTGCA AGCAGTGACA GTTCCCAAGG TTCTGATGTG
 TCTCTCACGG CTTGTAAAGT GTGA*  
>DL;IPD:MHC00359
IPD:MHC00359 Mamu-AG*03:01 1071 bases
 CTCCTGGTGC TCTCAGGGGT CCTGGCCCTG ACCCAGCCCC GGGCGGGCTC
 GCACTCCATG AGGTATTTCT ACACCGCCGT GTCCCGGCCC GGCCGCGGGC
 AGCCCCGCTT CATCGCCGTG GGCTACGTGG ACGACACGCA GTTCGTGCGG
 TTCGACAGCG ACGCCGAGAG TCCGAGGATG GAGCCGCGGG CGCCGTGGGT
 GGAGCAGGAG GGTCCAGAGT ATTGGGACCG GGAGACACAG AACATGAAGA
 CCGCGACACA GACCTACCAA GCGAACCTGC GGACCCTGCT CCGCTACTAC
 AACCAGAGCG AGGCCGGGTC TCACACCTTC CAGAAGATGT ACGGCTGCGA
 CCTGGGGCCA GACGGGCGCC TCCTCCGCGG GTATGAACAG TTCGCCTACG
 ACGGGAGGGA TTACATCATC CTGAACGAGG ACCTGCGCTC CTGGACGGCC
 GCGGACATGG CGGCTCAGAA CACCCAGCGC AAGTGGGAGG CGGCGGGTGC
 GGCGGAGCAG CACAGAACCT ACCTGGAGGG CGAGTGCCTG GAGTGGCTCC
 GCAGATACCT GGAGAACGGG AAGGAGACGC TGCAGCGCGC GGATCCCCCC
 AAGACAAATG TGACCCACCA CCCTGTCTCT GACTACGAGG CCACCCTGAG
 GTGTTGGGCC CTGGGCTTCT ACCCTGCGGA GATCACACTG ACCTGGCAGC
 GGGATGGAGA GGAACAAACT GAGGACACAG AGCTCGTGGA GACCAGGCCT
 ACAGGGGATG GAACCTTCCA GAAGTGGGCG GCTGTGGTGG TGCCTTCTGG
 AGAGGAGCAG AGATACACCT GTCATGTGCA ACATGAGGGT CTGCCTGAGC
 CCCTCACCTT GAGATGGGAG CCATCTTCCC AGTCTACCAT CCTCATCGTA
 GGCATCATTG CTGGCCTGGT TCTCCTTGGA ACTGTGGTCA CTGGAGCTGT
 GGTTGCTGCT GTGATGTGGA GGAGGAAGAG CTCAGATAGA TAAGGCGGGA
 GCTACTCTCA GGCTGCAAGC AGTGACAGTT CCCAAGGTTC TGATGTGTCT
 CTCACGGCTT GTAAAGTGTG A*  
>DL;IPD:MHC00360
IPD:MHC00360 Mamu-AG*03:02 1098 bases
 ATGGCGGTCA TGGCGCCCCG AACCCTCCTC CTGGTGCTCT CAGGGGTACT
 GGCCCTGACC CAGCCCCGGG CGGGCTCGCA CTCCATGAGG TATTTCTACA
 CCGCCGTGTC CCGGCCCGGC CGCGGGCAGC CCCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGAGAGTCC
 GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGT CCAGAGTATT
 GGGACCGGGA GACACAGAAC ATGAAGACCG CGACACAGAC CTACCAAGCG
 AACCTGCGGA CCCTGCTCCG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCTTCCAG AAGATGTATG GCTGCGACCT GGGGCCAGAC GGGCGCCTCC
 TCCGCGGGTA TGAACAGTTC GCCTACGACG GCAGGGATTA CATCATCCTG
 AACGAGGACC TGCGCTCCTG GACGGCCGCG GACATGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CGGGTGCGGC GGAGCAGCAC AGAACCTACC
 TGGAGGGCGA GTGCCTGGAG TGGCTCGGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCCAAG ACAAATGTGA CCCACCACCC
 TGTCTCTGAC TACGAGGCCA CCCTGAGGTG TTGGGCCCTC GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGAGAGGA ACAAACTGAG
 GACACAGAGC TCGTGGAGAC CAGGCCTACA GGGGATGGAA CCTTCCAGAA
 GTGGGCGGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA TACACCTGTC
 ATGTGCAACA TGAGGGTCTG CCCGAGCCCC TCACCTTGAG ATGGGAGCCA
 TCTTCCCAGT CTACCATCCT CATCGTAGGC ATCATTGCTG GCCTGGTTCT
 CCTTGGAACT GTGGTCACTG GAGCTGTGGT TGCTGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGATAGATAA GGCGGGAGCT ACTCTCAGGC TGCAAGCAGT
 GACAGTTCCC AAGGTTCTGA TGTGTCTCTC ACGGCTTGTA AAGTGTGA*
>DL;IPD:MHC03743
IPD:MHC03743 Mamu-AG*05:01 822 bases
 GCTCCCACTC CATGAGGTAT TTCTACACCG CCGTGTCCCG GCCCGGCCGT
 CGGGAGCCCC TCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGGTGGAGCA GGAGGGTCCA GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CACAGACCTA CCGAGTGAAC CTGCGGACCG CGCTCCGCTA
 CTACAACCAG AGCGAGGGGG GGTCTCACAC CATCCAGAAG ATGTACGGCT
 GCGACCTGGG GCCCGACGGG CGCCTCCTCC GCGGGTATGA ACAGTTCGCC
 TACGACGGCA GGGATTACAT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC
 CGCCGCGGAC ATGGCGGCTC AGTTCACCCA GCGGAAGTGG GAGGCGGCGG
 GTGCGGCGGA GCAGCACAGA ACCTACCTGG AGGGCGAGTG CCTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGGACCC
 CCCCAAGACA CATGTGACCC ACCACCCCGT CTCTGACTAC GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACTTGG
 CAGCGGGATG GAGAGGAACA AACTGAAGAC ACAGAGCTCG TGGAGACCAG
 GCCTACAGGG GATGGAACCT TCCAGAAGTG GGCGGCTGTG GTGGTGCCTT
 CTGGAGAGGA GCAGAGATAC ACCTGTCATG TGCAGCATGA GGGTCTGCCC
 AAGCCCCTCA CCTTGAGATT CG*  
