>DL;IPD:MHC00398
IPD:MHC00398 Mamu-DQB1*06:01 786 bases
 ATGTCTTGGA AGAAGGCTTT GCGGATCCCT GGCGGCCTTC GGGCAGCAAC
 TGTGACCTTG ATGCTGGCGA TGCTGAGCAC CCCAGTGGCT GAGGGCAGAG
 ACGCTCCCGA GGATTTCGTG TACCAGTTTA AGGCCATGTG CTACTTCACC
 AACTGGACGG AGCGCGTGCG TTATGTGACC AGATACATCT ATAACCGAGA
 GGAGTTCGTG CGATTCGACA GCGCCGTGGG GGAGTACCGG GCGGTGACGC
 CGCAAGGGCG GCTTGACGCC GAGTACTGGA ACAGCCAGAA GGACGTGCTG
 GAGAGCACCC GGGCGGAATT GGACACGGTG TGCAAACACA ACTACGAGGT
 GGCGTTCCGC GGGATCTTGC AGAGGAGAGT GGAGCCCACA GTGACCATCT
 CCCCGTCCAG GACAGAGGCC CTCAACCACC ACAACCTGCT GGTCTGCTCG
 GTGACAGATT TCTATCCAGG CCAGATCAAA GTCCGGTGGT TTCGGAACAA
 TCAGGAGGAG ACAGTCGGCG TTGTGTCCAC CCCCCTCATT AGGAACGGTG
 ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GACGTCTACA CCTGCCACGT GGAGCACCCT AGCCTCCAGA GCCCCATCAC
 CGTGGAGTGG CGGGCTCAGT CTGAGTCTGC CCAGAGCAAG CTGCTGAGTG
 GCATTGGAGG CCTCGTGCTG GGGCTCATCT TCTTTGGGCT GGGCCTTATC
 ATCCGTCAGA GGAGTCAGAA AGGGCTCCCG CACTGA* 
>DL;IPD:MHC00399
IPD:MHC00399 Mamu-DQB1*06:02:01 786 bases
 ATGTCTTGGA AGAAGGCTTT GCGGATCCCC GGCGGCCTTC GGGTAGCAAC
 TGTGACCTTG ATGCTGGCGA TGCTGAGCAC CCCAGTGGCT GAGGGCAGAG
 ACTCTCCCGA GGATTTCGTG TACCAGTTTA AGGGTCTGTG CTACTTCACC
 AACGGGACGG AGCGCGTGCG GAGTGTGACC AGACACATTT ATAACCGAGA
 GGAGTACGTG CGCTTCGACA GCGACTGGGG GGAGTACCGG GCGGTGACGC
 CGCAGGGGCG GCCTGACGCC GAGTACTGGA ACAGCCAGAA GGACATCCTG
 GAGAGCACCC GGGCGGAGTT GGACACGGTG TGCATGCACA ACTACGAGGT
 GGCGTACCGC GGGATCTTGC AGAGGAGAGT GGAGCCCACA GTGACCATCT
 CCCTGTCCAG GACAGAGGCC CTCAACCACC ACAACCTGCT GGTCTGCTCG
 GTGACAGATT TCTATCCAGG CCAGATCAAA GTCCGGTGGT TTCGGAACAA
 TCAGGAGGAG ACAGTCGGCG TTGTGTCCAC CCCCCTCATT AGGAATGGCG
 ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GACGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA GCCCCATCAC
 CGTGGAGTGG CGGGCTCAGT CTGAGTCTGC CCAGAGCAAG ATGCTGAGTG
 GCATTGGAGG CCTCGTGCTG GGATTGATCT TCCTCGGGCT GGGCCTTATC
 ATCCGTCAGA GGAGTCAGAA AGGGCTCCTG CACTGA* 
>DL;IPD:MHC03494
IPD:MHC03494 Mamu-DQB1*06:02:02 254 bases
 TGTACCAGTT TAAGGGTCTG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CGGAGTGTGA CCAGACACAT TTATAACCGA GAGGAGTACG TGCGCTTCGA
 CAGCGACTGG GGGGAGTACC GGGCGGTGAC GCCGCAGGGG CGGCCTGACG
 CCGAGTACTG GAACAGCCAG AAGGACATCC TGGAGAGCAC CCGGGCGGAG
 TTGGACACAG TGTGCATGCA CAACTACGAG GTGGCGTACC GCGGGATCTT
 GCAG*    
>DL;IPD:MHC04024
IPD:MHC04024 Mamu-DQB1*06:02:03 270 bases
 GAGGATTTCG TGTACCAGTT TAAGGGCCTG TGCTACTTCA CCAACGGGAC
 GGAGCGCGTG CGGAGTGTGA CCAGACACAT TTATAACCGA GAGGAGTACG
 TGCGCTTCGA CAGCGACTGG GGGGAGTACC GGGCGGTGAC GCCGCAGGGG
 CGGCCTGACG CCGAGTACTG GAACAGCCAG AAGGACATCC TGGAGAGCAC
 CCGGGCGGAG TTGGACACGG TGTGCATGCA CAACTACGAG GTGGCGTACC
 GCGGGATCTT GCAGAGGAGA *  
>DL;IPD:MHC00400
IPD:MHC00400 Mamu-DQB1*06:05 786 bases
 ATGTCTTGGA AGAAGGCTTT GCGGATCCCC GGCGGCCTTC GGGTAGCAAC
 TGTGACCTTG ATGCTGGCAA TGCTGAGCAC CCCAGTGACT GAGGGCAGAG
 ACTCTCCCGA GGATTTCGTG TACCAGTTTA AGGGCCTGTG CTACTTCACC
 AACGGGACGG AGCGCGTGCG TCTTGTGAGC AGATTCATCT ATAACCGAGA
 GGAGTACGCG CGCTTCGACA GCGACGTGGG GGAGTACCGG GCGGTGACGC
 CGCAGGGGCG GCCTGACGCC GAGTACTGGA ACAGCCAGAA GGACATCCTG
 GAGAGGACCC GGGCGGAGTT GGACACTGTG TGCAGACACA ACTACGAGGT
 GGCTTACCGC GGGATCTTGC AGAGGAGAGT GGAGCCCACA GTGACCATCT
 CCCCGTCCAG GACAGAGGCC CTCAACCACC ACAACCTGCT GGTCTGCTCG
 GTGACAGATT TCTATCCAGG CCAGATCAAA GTCCGGTGGT TTCGGAACAA
 TCAGGAGGAG ACAGTCGGCG TTGTGTCCAC CCCCCTCATT AGGAACGGTG
 ACTGGACCTT CCAGATCTTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GACGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA GCCCCATCAC
 CGTGCAGTGG CGGGCTCAGT CTGAGTCTGC CCAGAGCAAG CTGCTGAGTG
 GCATTGGAGG CCTTGTGCTG GGGCTCATCT TCTTTGGGCT GGGCCTTATC
 ATCCGTCAGA GGAGTCAGAA AGGGCTCCCG CACTGA* 
>DL;IPD:MHC00401
IPD:MHC00401 Mamu-DQB1*06:06 786 bases
 ATGTCTTGGA AGAAGGCTTT GCGGATCCCT GATGGCCTTC GGGCAGCAAC
 TGTGACCTTG ATGCTGGCGA TGCTAAGCAC CCCAGTGGCT GAGGGCAGAG
 ACGCTCCCGA GGATTTCGTG GTCCAGTTTA AGGGCCTGTG CTACTACACC
 AACGGGACGG AGCGCGTGCG TCTTGTGACC AGATACATCT ATAACCGAGA
 GGAGTACGCG CGCTTCGACA GCGACTGGGG GGAGTACCGG GCGGTGACGC
 CGCAGGGGCG GCCTGACGCC GAGTACTGGA ACAGCCAGAA GGACATCCTG
 GAGAGGACCC GGGCGGAGTT GGACACTGTG TGCATACACA ACTACGAGGT
 GGTGTACCGC GGGATCTTGC AGAGGAGAGT GGAGCCCACA GTGACCATCT
 CCCTGTCCAG GACAGAGGCC CTCAACCACC ACAACCTGCT GGTCTGCTCA
 GTGACAGATT TCTATCCAGG CCAGGTCAAA GTCCGGTGGT TTCGGAACAA
 TCAGGAGGAG ACAGTCGGCG TTGTGTCCAC CCCCCTCATT AGGAACGGCG
 ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GACGTCTACA CCTGCCACGT GGAGCACCCC AGCGTCCAGA GCCCCATCAC
 CGTGGAGTGG CGGGCTCAGT CTGAGTCTGC CCAGAGCAAG ATGCTGAGTG
 GCATTGGAGG CTTCGTGCTG GGGCTCATCT TCTTTGGGCT GGGCCTTATC
 ATCCGTCAGA GGAGTCAGAA AGGGCTCCTG CACTGA* 
>DL;IPD:MHC00402
IPD:MHC00402 Mamu-DQB1*06:07 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACG
 GAGCGCGTGC GTCTTGTGAG CAGATACATC TATAACCGAG AGGAGTACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG CCGCAGGGGC
 GGCCTGACGC CGAGTACTGG AACAGCCAGA AGGACATCCT GGAGAGCAAA
 CGGGCGGAGT TGGACACTGT GTGCAAACAC AACTACGAGG TGGCTTACCG
 CGGGATCTTG CAGAGGAGAG *  
>DL;IPD:MHC00403
IPD:MHC00403 Mamu-DQB1*06:08 269 bases
 AGGATTTCGT GCACCAGTTT AAGGCCATGT GCTACTTCAC CAACGGGACG
 GAGCGCGTGC GTTATGTGAC CAGATACATC TATAACCGAG AGGAGTACGT
 GCGATTCGAC AGCGCCGTGG GGGAGCACCG GGCGGTGACG CCGCAGGGGC
 GGCCTGACGC CGAGTACTGG AACAGCCAGA AGGACATCCT GGAGAGGACC
 CGGGCGGAGT TGGACACGGT GTGCAAACAC AACTACGAGG TGGCGTTCCG
 CGGGATCTTG CAGAGGAGA*   
>DL;IPD:MHC00404
IPD:MHC00404 Mamu-DQB1*06:09 786 bases
 ATGTCTTGGA AGAAGGCTTT GCGGATCCCC GGCGGCCTTC GGGTAGCAAC
 TGTGACCTTG ATGCTGGCGA TGCTGAGCAC CCCAGTGGCT GAGGGCAGAG
 ACTCTCCCGA GGATTTCGTG TACCAGTTTA AGGGTCTGTG CTACTTCACC
 AACGGGACGG AGCGCGTGCG GAGTGTGACC AGACACATTT ATAACCGAGA
 GGAGTACGTG CGCTTCGACA GCGACTGGGG GGAGTACCGG GCGGTGACGC
 CGCAGGGGCG ACCTACCGCC GAGTACTGGA ACAGCCAGAA GGACATCCTG
 GAGAGCACCC GGGCGGAGTT GGACACGGTG TGCATGCACA ACTACGAGGT
 GGCGTACCGC GGGATCTTGC AGAGGAGAGT GGAGCCCACA GTGACCATCT
 CCCCGTCCAG GACAGAGGCC CTCAACCACC ACAACCTGCT GGTCTGCTCG
 GTGACAGATT TCTATCCAGG CCAGATCAAA GTCCGGTGGT TTCGGAACAA
 TCAGGAGGAG ACAGTCGGCG TTGTGTCCAC CCCCCTCATT AGGAACGGCG
 ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GACGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA GCCCCATCAC
 CGTGGAGTGG CGGGCTCAGT CTGAGTCTGC CCAGAGCAAG ATGCTGAGTG
 GCATTGGAGG CCTCGTGCTG GGGCTCATCT TCTTTGGGCT GGGCCTTATC
 ATCCGTCAGA GGAGTCAGAA AGGGCTCCTG CACTGA* 
>DL;IPD:MHC00405
IPD:MHC00405 Mamu-DQB1*06:10 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGTCTGT GCTACTTCAC CAACGGGACG
 GAGCGCGTGC GGAGTGTGAC CAGACACATT TATAACCGAG AGGAGTACGT
 GCGCTTCGAC AGCGACTGGG GGGAGTACCG GGCGGTGACG CCGCAGGGGC
 GGCCTGCCGC CGAGTACTGG AACAGCCAGA AGGACATCCT GGAGAGGACC
 CGGGCGGAGT TGGACACTGT GTGCATACAC AACTACGAGG TGGTGTACCG
 CGGGATCTTG CAGAGGAGAG *  
>DL;IPD:MHC00406
IPD:MHC00406 Mamu-DQB1*06:11:01 786 bases
 ATGTCTTGGA AGAAGGCTTT GCGGATCCCC AGCGGCCTTC GGGTAGCAAC
 TGTGACCTTG ATGCTGGCGA TGCTGAGCAC CCCAGTGGCT GAGGGCAGAG
 ACTCTCCCGA GGATTTCGTG TTCCAGTTTA AGGGCCTGTG CTACTTCACC
 AACGGGACGG AGCGCGTGCG TCATGTGACC AGATACATCT ATAACCGAGA
 GGAGTTCCTG CGATTCGACA GCGCCGTGGG GGAGTACCGG GCTGTGACGC
 CACAGGGGCG GTCTGACGCC GAGCACTTGA ACAGCCAGAA GGACGTGCTG
 GAGAGCACCC GGGCGGAGTT GGACACGGTG TGCATGCACA ACTACGAGGT
 GACGTACCGC GGGATCTTGC AGAGGAGAGT GGAGCCCACA GTGACCATCT
 CCCCGTCCAG GACAGAGGCC CTCAACCACC ACAACCTGCT GGTCTGCTCG
 GTGACAGATT TCTATCCAGG CCAGATCAAA GTCCGGTGGT TTCGGAACAA
 TCAGGAGGAG ACAGTCGGCG TTGTGTCCAC CCCCCTCATT AGGAACGGTG
 ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GATGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA GCCCCATCAC
 CGTGGAGTGG CGGGCTCAGT CTGAGTCTGC CCAGAGCAAG ATGCTGAGTG
 GCATTGGAGG CTTCGTGCTG GGGCTCATCT TCTTTGGGCT GGGCCTTATC
 ATCCGTCAGA GGAGTCAGAA AGGGCTCCTG CACTGA* 
>DL;IPD:MHC00407
IPD:MHC00407 Mamu-DQB1*06:11:02 270 bases
 AGGATTTCGT GTTCCAGTTT AAGGGTCTGT GCTACTTCAC CAACGGGACG
 GAGCGCGTGC GTCATGTGAC CAGATACATC TATAACCGAG AGGAGTTCCT
 GCGATTCGAC AGCGCCGTGG GGGAGTACCG GGCTGTGACG CCACAGGGGC
 GGTCTGACGC CGAGCACTTG AACAGCCAGA AGGACGTGCT GGAGAGCACC
 CGGGCGGAGT TGGACACGGT GTGCATGCAC AACTACGAGG TGACGTACCG
 CGGGATCTTG CAGAGGAGAG *  
>DL;IPD:MHC00408
IPD:MHC00408 Mamu-DQB1*06:12 246 bases
 TACCAGTTTA AGGGCCTGTG CTACTACACC AACGGGACGG AGCGCGTGCG
 TCTTGTGACC AGATACATCT ATAACCGAGA GGAGTACGCG CGCTTCGACA
 GCGACTGGGG GGAGTACCGG GCGGTGACGC CGCAGGGGCG GCCTGCCGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGAGGACCC GGGCGGAGTT
 GGACACTGTG TGCATACACA ACTACGAGGT GGTGTACCGC GGGATC*
>DL;IPD:MHC00409
IPD:MHC00409 Mamu-DQB1*06:13:01 270 bases
 GAGGATTTCG TGGTCCAGTT TAAGGGCCTG TGCTACTACA CCAACGGGAC
 GGAGCGCGTG CGGGGTGTGA CCAGATACAT CTATAACCGA GAGGAGTACG
 CGCGCTTCGA CAGCGACTGG GGGGAGTACC GGGCGGTGAC GCCGCAGGGG
 CGGCCTGACG CCGAGTACTG GAACAGCCAG AAGGACATCC TGGAGAGGAC
 CCGGGCGGAG TTGGACACTG TGTGCATACA CAACTACGAG GTGGTGTACC
 GCGGGATCTT GCAGAGGAGA *  
>DL;IPD:MHC02196
IPD:MHC02196 Mamu-DQB1*06:13:02 269 bases
 AGGATTTCGT GGTCCAGTTT AAGGGTCTGT GCTACTACAC CAACGGGACG
 GAGCGCGTGC GGGGTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC
 GCGCTTCGAC AGCGACTGGG GGGAGTACCG GGCGGTGACG CCGCAGGGGC
 GGCCTGACGC CGAGTACTGG AACAGCCAGA AGGACATCCT GGAGAGGACC
 CGGGCGGAGT TGGACACTGT GTGCATACAC AACTACGAGG TGGTGTACCG
 CGGGATCTTG CAGAGGAGA*   
>DL;IPD:MHC01626
IPD:MHC01626 Mamu-DQB1*06:14 786 bases
 ATGTCTTGGA AGAAGGCTTT GCGGATCCCC GGCGGCCTTC GGGTAGCAAC
 TGTGACCTTG ATGCTGGCGA TGCTGAGCAC CCCAGTGGCT GAGGGCAGAG
 ACTCTCCCGA GGATTTCGTG TACCAGTTTA AGGGTCTGTG CTACTTCACC
 AACGGGACGG AGCGCGTGCG GAGTGTGACC AGACACATTT ATAACCGAGA
 GGAGTACGTG CGCTTCGACA GCGACTGGGG GGAGTACCGG GCGGTGACGC
 CGCAGGGGCG GCCTGACGCC GAGTACTGGA ACAGCCAGAA GGACATCCTG
 GAGAGCACCC GGGCGGAGTT GGACACGGTG TGCATGCACA ACTACGAGGT
 GGCGTACCGC GGGATCTTGC AGAGGAGAGT GGAGCCCACA GTGACCATCT
 CCCTGTCCAG GACAGAGGCC CTCAACCACC ACAACCTGCT GGTCTGCTCG
 GTGACAGATT TCTATCCAGG CCAGATCAAA GTCCGGTGGT TTCGGAACAA
 TCAGGAGGAG ACAGTCGGCG TTGTGTCCAC CCCCCTCATT AGGAATGGCG
 ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GACGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA GCCCCATCAC
 CGTGGAGTGG CGGGCTCAGT CTGAGTCTGC CCAGAGCAAG ATGCTGAGTG
 GCATTGGAGG CCTCGTGCTG GGGCTCATCT TCTTTGGGCT GGGCCTTATC
 ATCCGTCAGA GGAGTCAGAA AGGGCTCCTG CACTGA* 
>DL;IPD:MHC02192
IPD:MHC02192 Mamu-DQB1*06:15 269 bases
 AGGATTTCGT GTACCAGTTT AAGGGTCTGT GCTACTTCAC CAACGGGACG
 GAGCGCGTGC GGAGTGTGAC CAGATACATC TATAACCGAG AGGAGTACGT
 GCGCTTCGAC AGCGACTGGG GGGAGTACCG GGCGGTGACG CCGCAGGGGC
 GGCCTGCCGC CGAGTACTGG AACAGCCAGA AGGACATCCT GGAGAGGACC
 CGGGCGGAGT TGGACACTGT GTGCATACAC AACTACGAGG TGGTGTACCG
 CGGGATCTTG CAGAGGAGA*   
>DL;IPD:MHC02350
IPD:MHC02350 Mamu-DQB1*06:16 269 bases
 AGGATTTCGT GGTCCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACG
 GAGCGCGTGC GTCTTGTGAG CAGATTCATC TATAACCGAG AGGAGTACGC
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG CCGCAGGGGC
 GGCCTGACGC CGAGTACTGG AACAGCCAGA AGGACATCCT GGAGAGCACC
 CGGGCGGAGT TGGACACTGT GTGCAGACAC AACTACGAGG TGGCTTACCG
 CGGGATCTTG CAGAGGAGA*   
>DL;IPD:MHC02905
IPD:MHC02905 Mamu-DQB1*06:17 270 bases
 AGGATTTCGT GGTCCAGTTT AAGGGCCTGT GCTACTACAC CAACGGGACG
 GAGCGCGTGC GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC
 GCGCTTCGAC AGCGACTGGG GGGAGTACCG GGCGGTGACG CCGCAGGGGC
 GGCCTGCCGC CGAGTACTGG AACAGCCAGA AGGACATCCT GGAGAGGACC
 CGGGCGGAGT TGGACACTGT GTGCATACAC AACTACGAGG TGGTGTACCG
 CGGGATCTTG CAGAGGAGAG *  
>DL;IPD:MHC03495
IPD:MHC03495 Mamu-DQB1*06:18 254 bases
 TGTACCAGTT TAAGGGCCTG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CGTCTTGTGA GCAGATTCAT CTATAACCGA GAGGAGTACG CGCGCTTCGA
 CAGCGACGTG GGGGAGTACC GGGCGGTGAC GCCGCAGGGG CGGCCTGACG
 CCGAGTACTG GAACAGCCAG AAGGACATCC TGGAGAGCAC CCGGGCGGAG
 TTGGACACTG TGTGCAGACA CAACTACGAG GTGGCTTACC GCGGGATCTT
 GCAG*    
>DL;IPD:MHC03496
IPD:MHC03496 Mamu-DQB1*06:19 254 bases
 TGGTCCAGTT TAAGGGCCTG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CGTCATGTGA CCAGATACAT CTATAACCGA GAGGAGTTCC TGCGATTCGA
 CAGCGCCGTG GGGGAGTACC GGGCTGTGAC GCCACAGGGG CGGTCTGACG
 CCGAGCACTT GAACAGCCAG AAGGACGTGC TGGAGAGCAC CCGGGCGGAG
 TTGGACACGG TGTGCATGCA CAACTACGAG GTGACGTACC GCGGGATCTT
 GCAG*    
>DL;IPD:MHC04013
IPD:MHC04013 Mamu-DQB1*06:20 270 bases
 GAGGATTTCG TGTTCCAGTT TAAGGGCATG TGCTACTTCA CCAACGGGAC
 GGAGCGCGTG CGTCTTGTGA GCAGATTCAT CTATAACCGA GAGGAGTACG
 CGCGCTTCGA CAGCGACGTG GGGGAGTACC GGGCGGTGAC GCCGCAGGGG
 CGGCCTGACG CCGAGTACTG GAACAGCCAG AAGGACATCC TGGAGAGGAC
 CCGGGCGGAG TTGGACACTG TGTGCAGACA CAACTACGAG GTGGCTTACC
 GCGGGATCTT GCAGAGGAGA *  
>DL;IPD:MHC04014
IPD:MHC04014 Mamu-DQB1*06:21 270 bases
 GAGGATTTCG TGTACCAGTT TAAGGGCATG TGCTACTTCA CCAACGGGAC
 GGAGCGCGTG CGTCATGTGA CCAGGTACAT CTATAACCGA GAGGAGTACG
 TGCGCTTCGA CAGCGACGTG GGGGAGCACC GGGCGGTGAC GCCGCAGGGG
 CGGCCTGACG CTGAGTACTG GAACAGCCAG AAGGACATCC TGGAGAGGAC
 CCGGGCGGAG TTGGACACGG TGTGCAAACA CAACTACGAG GTGGCGTTCC
 GCGGGATCTT GCAGAGGAGA *  
>DL;IPD:MHC04015
IPD:MHC04015 Mamu-DQB1*06:22 269 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAT CAACGGGACG
 GAGCGCGTGC GGGGTGTGAC CAGACACATT TATAACCGAG AGGAGTACGT
 GCGCTTCGAC AGCGACTGGG GGGAGTACCG GGCGGTGACG CCGCAGGGGC
 GGCCTGACGC CGAGTACTGG AACAGCCAGA AGGACATCCT GGAGAGCACC
 CGGGCGGAGT TGGACACGGT GTGCATGCAC AACTACGAGG TGGCGTACCG
 CGGGATCTTG CAGAGGAGA*   
>DL;IPD:MHC00410
IPD:MHC00410 Mamu-DQB1*15:01 786 bases
 ATGTCTTGGA AGAAGGCTTT GCGGATCCCT GGCGGCCTTC GGGCAGCAAC
 TGTGACCTTG ATGCTGGCAA TGCTGAGCAC CCCAGTGGCT GAGTGCAGAG
 ACTCTCCCGA GGATTTCGTG TTCCAGTTTA AGGGCATGTG CTACTTCACC
 AACGGGACAG AGCGCGTGTG GAGTGTAGAC AGATACATCT ATAACCGAGA
 GGAGTACGTG CGCTTCGACA GCGACGTGGG GTTGTACCTG CCGGTGACGC
 CGCTGGGGCG GTCCAGTGCC GAGTACTGGA ACAGCCAGAA GGAAGCCCTG
 GAGAGCAAAC GGGCGGAGTT GGACACGGTG TGCATACACA ACTACCAGTT
 GGAGCTCGGC ACGACCTTGC AGCGGCGAGT GGAGCCCACA GTGACCATCT
 CCCCATCCAG AACAGAGGCC CTCAACCACC ACAACCTGCT GGTCTGCTCG
 GTGACAGATT TCTATCCAGG CCAGATCAAA GTCCGGTGGT TTCGAAATGA
 CCAGGAGGAG ACAACCGGCA TTGTGTCCAC CCCCCTTATT AGGAACGGTG
 ACTGGACCTT CCAGATCCTA GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GATGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAAA GCCCTATCAC
 CGTGGAGTGG CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG
 GCATTGGAGG CTTCGTGCTG GGGATGATCT TCCTTGGACT GGGCCTTATC
 ATCCATCACA GGAGTCAGAA AGGGCTCCTG CACTGA* 
>DL;IPD:MHC00411
IPD:MHC00411 Mamu-DQB1*15:02 246 bases
 TTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGTG
 GAGTGTAGAC AGATACATCT ATAACCGAGA GGAGTACGTG CGCTTCGACA
 GCGACGTGGG GTTGTACCTG CCGGTGACGC CGCTGGGGCG GTCCATTGCC
 GAGTACTGGA ACAGCCAGAA GGAAGCCCTG GAGAGCAAAC GGGCGGAGTT
 GGACACGGTG TGCATACACA ACTACCAGTT GGAGCTCGGC ACGACC*
>DL;IPD:MHC00412
IPD:MHC00412 Mamu-DQB1*15:03 786 bases
 ATGTCTTGGA AGAAGGCTTT GCGGATCCCT GGCGGCCTTC GGGCAGCAAC
 TGTGACCTTG ATGCTGGCAA TGCTGAGCAC CCCAGTGGCT GAGTGCAGAG
 ACTCTCCCGA GGATTTCGTG TTCCAGTTTA AGGGCATGTG CTACTTCACC
 AACGGGACAG AGCGCGTGTG GAGTGTAGAC AGATACATCT ATAACCGAGA
 GGAGTACGTG CGCTTCGACA GCGACGTGGG GTTGTACCTG CCGGTGACGC
 CGCTGGGGCG GTCCAGTGCC GAGTACATGA ACAGCCAGAA GGAAGCCCTG
 GAGAGCAAAC GGGCGGAGTT GGACACGGTG TGCATACACA ACTACCAGTT
 GGAGCTCGGC ACGACCTTGC AGCGGCGAGT GGAGCCCACA GTGACCATCT
 CCCCATCCAG AACAGAGGCC CTCAACCACC ACAACCTGCT GGTCTGCTCG
 GTGACAGATT TCTATCCAGG CCAGATCAAA GTCCGGTGGT TTCGAAATGA
 CCAGGAGGAG ACAACCGGCA TTGTGTCCAC CCCCCTTATT AGGAACGGTG
 ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GATGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAAA GCCCTATCAC
 CGTGGAGTGG CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG
 GCATTGGAGG CTTCGTGCTG GGGATGATCT TCCTTGGACT GGGCCTTATC
 ATCCATCACA GGAGTCAGAA AGGGCTCCTG CACTGA* 
>DL;IPD:MHC02193
IPD:MHC02193 Mamu-DQB1*15:04 269 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACA
 GAGCGCGTGT GGAGTGTAGA CAGATACATC TATAACCGAG AGGAGTACGT
 GCGCTTCGAC AGCGACGTGG GATTGTACCT GCCGGTGACG CCGCTGGGGC
 GGTCCAGTGC CGAGTACTGG AACAGCCAGA AGGAAGCCCT GGAGAGCAAA
 CGGGCGGAGT TGGACACGGT GTGCATACAC AACTACCAGT TGGAGCTCCG
 CACGACCTTG CAGCGGCGA*   
>DL;IPD:MHC04025
IPD:MHC04025 Mamu-DQB1*15:05 270 bases
 GAGGATTTCG TGTACCAGTT TAAGGGCATG TGCTACTTCA CCAACGGGAC
 AGAGCGCGTG TGGAGTGTAG ACAGATACAT CTATAACCGA GAGGAGTACG
 TGCGCTTCGA CAGCGACGTG GGGTTGTACC TGCCGGTGAC GCCGCTGGGG
 CGGTCCAGTG CCGAGTACAT GAACAGCCAG AAGGAAGCCC TGGAGAGCAA
 ACGGGCGGAG TTGGACACGG TGTGCATACA CAACTACCAG TTGGAGCTCG
 GCACGACCTT GCAGCGGCGA *  
>DL;IPD:MHC00413
IPD:MHC00413 Mamu-DQB1*16:01 270 bases
 AGGATTTCGT GCACCAGTTT AAGTTCATGT GCTACTTCGT CAACGGGACA
 GAGCGCGTGC GGGCTATAGC CAGACACGTC TATAACCGCG AAGAGTTCGC
 GCGCTTCGAC AGCGACGTGG GGGTGTACCG AGCGGTGACG CCGCTGGGGC
 GGTCTAGTGC CGAGTACTGG AACAGCCAGA AGGAAGTCCT GGAGAGGAAA
 CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT TGGAACTCCG
 CTCGACCTTG CAGCGGCGAG *  
>DL;IPD:MHC00414
IPD:MHC00414 Mamu-DQB1*16:02 246 bases
 TACCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG
 TTGGGTAGCC AGACACGTCT ATAACCGCGA AGAGTACGCG CGCTTCGACA
 GCGACGTGGG GGTGTACCGG GCGGTGACGC CTCTGGGACA GTCTAGCGTC
 GAGTACTGGA ACAGCCAGAA GGAAGTCCTG GAGAGCAAAC GGGCGGCGTT
 GGACACGGTG TGCATACACA ACTACCAGTT GGAACTCCGC ACGACC*
>DL;IPD:MHC00415
IPD:MHC00415 Mamu-DQB1*16:03:01 228 bases
 TACCAGTTTA AAGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG
 GTTAGTAGCC AGACACGTCT ATAACCGCGA GGAGTTCGCG CGCTTCGACA
 GCGACGTGGG GGTGTACCGA GAGGTGACGC CGATGGGGCA GTCTTGGGCC
 GAGTACTGGA ACAGCCAGAA GGAAGTCCTG GAGAGGAAAC GGGCGGAGCT
 GGACACGGTG TGCAGACACA ACTACCAG*  
>DL;IPD:MHC03880
IPD:MHC03880 Mamu-DQB1*16:03:02 254 bases
 TGTACCAGTT TAAAGGCATG TGCTACTTCA CCAACGGGAC AGAGCGCGTG
 CGGTTAGTAG CCAGACACGT CTATAACCGC GAAGAGTTCG CGCGCTTCGA
 CAGCGACGTG GGGGTGTACC GAGAGGTGAC GCCGATGGGG CAGTCTTGGG
 CCGAGTACTG GAACAGCCAG AAGGAAGTCC TGGAGAGGAA ACGGGCGGAG
 CTGGACACGG TGTGCAGACA CAACTACCAG TTGGAACTCC TCTCGACCTT
 GCAG*    
>DL;IPD:MHC00416
IPD:MHC00416 Mamu-DQB1*17:02 246 bases
 TACCAGTTTA AGTGCCTGTG CTACTTCACC AACGGGACGG AGCGCGTGCA
 TTATGTGACC AGACACATTT ATAACCGAGA GGAGTACGTG CGCTTCGACA
 GCGACTGGGG GGAGTACCGG GCGGTGACGC CGCAGGGGCG ACCTACCGCC
 GAGTACTGGA ACAACCAGAA GGACTTCCTG GAGAGCACCC GGGCGGAGTT
 GGACACGGTG TGCAAACACA ACTACGAGTT GGAACTCCTC ACGACC*
>DL;IPD:MHC00417
IPD:MHC00417 Mamu-DQB1*17:03 786 bases
 ATGCCTCGGA AGAAGGCTTT GCGGATTCCC GGAGGCCTTT GGGGGACAAC
 TGTGACCTTG ATGCTGGCGA TGCTGAGCAC CCCAGTGGCT GGGGGCAGAG
 ACTCTCCCGA GGATTTCGTG TACCAGTTTA AGGCCATGTG CTACTTCACC
 AACGGGACGG AGCGCGTGCA TTATGTGACC AGATACATCT ATAACCGAGA
 GGAGTACGCG CGTTTCGACA GCGACGTGGG GAAATACCTG CCGGTGACGC
 CGCTGGGGCC GCCTGCCGCC GAGTACTGGA ACAGCCAGAA GGACATCCTG
 GAGAGGACCC GGGCGGAACT GGACACGGTG TGCAGACACA ACTACCAGTT
 GGAACTCCAC ACGACCTTGC AGTGGCGAGT GGAGCCCACA GTGACCATCT
 CCCCATCCAG GACAGAGGCC CTCAACCACC ACAACCTGCT GGTCTGCTCG
 GTGACAGATT TCTATCCAGG CCAGATAAAA GTCCAGTGGT TTCGGAATGA
 CCAGGAGGAG ACAGCCGGCA TTGTGTCCAC CCCCCTTATT AGGAACGGCG
 ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGGGGA
 GATGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA GCCCCATCAC
 CGTGGAGTGG CGAGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG
 GCGTTGGAGG CTTCGTGCTG GGACTGATCT TCCTTGGGCT GGGCCTTATC
 ATCCATCACA GGAGTCAGAA AGGGCTCCTG CACTGA* 
>DL;IPD:MHC00418
IPD:MHC00418 Mamu-DQB1*17:04 246 bases
 TACCAGTTTA AGTGCCTGTG CTACTTCACC AACGGGACGG AGCGCGTGCA
 TTTTGTGACC AGACACATTT ATAACCGAGA GGAGTACGTG CGCTTCGACA
 GCGACTGGGG GGAGTACCGG GCGGTGACGC CGCTGGGGCG ACCTGCCGCC
 GAGTACTGGA ACAGCCAGAA GGACTTCCTG GAGAGCACCC GGGCGGAGTT
 GGACACGGTG TGCAAACACA ACTACCAGTT GGAACTCCTC ACGACC*
>DL;IPD:MHC00419
IPD:MHC00419 Mamu-DQB1*17:05 270 bases
 AGGATTTCGT GTACCAGTTT AAGTGCCTGT GCTACTTCAC CAACGGGACG
 GAGCGCGTGC ATTATGTGAC CAGACACATT TATAACCGAG AGGAGTACGT
 GCGCTTCGAC AGCGACTGGG GGGAGTACCG GGCGGTGACG CCGCTGGGGC
 GACCTGCCGC CGAGTACTGG AACAGCCAGA AGGACATCCT GGAGAGCACC
 CGGGCGGAGT TGGACACGGT GTGCAAACAC AACTACCAGT TGGAACTCCT
 CACGACCTTG CAGCGGCGAG *  
>DL;IPD:MHC00420
IPD:MHC00420 Mamu-DQB1*17:06:01 270 bases
 AGGATTTCGT GTACCAGTTT AAGTGCCTGT GCTACTTCAC CAACGGGACG
 GAGCGCGTGC ATTATGTGAC CAGACACATT TATAACCGAG AGGAGTACGT
 GCGCTTCGAC AGCGACTGGG GGGAGTACCG GGCGGTGACG CCGCTGGGGC
 GACCTACCGC CGAGTACTGG AACAGCCAGA AGGACTTCCT GGAGAGCACC
 CGGGCGGAGT TGGACACGGT GTGCAAACAC AACTACCAGT TGGAACTCCT
 CACGACCTTG CAGCGGCGAG *  
>DL;IPD:MHC03500
IPD:MHC03500 Mamu-DQB1*17:06:02 266 bases
 AGGATTTCGT GTACCAGTTT AAGTGCCTGT GCTACTTCAC CAACGGGACG
 GAGCGCGTGC ATTATGTGAC CAGACACATT TATAACCGAG AGGAGTACGT
 GCGCTTCGAC AGCGACTGGG GGGAGTACCG GGCGGTGACT CCGCTGGGGC
 GACCTACCGC CGAGTACTGG AACAGCCAGA AGGACTTCCT GGAGAGCACC
 CGGGCGGAGT TGGACACGGT GTGCAAACAC AACTACCAGT TGGAACTCCT
 CACGACCTTG CAGCGG*   
>DL;IPD:MHC00421
IPD:MHC00421 Mamu-DQB1*17:07 270 bases
 AGGATTTCGT GTACCAGTTT AAGGCCATGT GCTACTTCAC CAACGGGACG
 GAGCGCGTGC ATTATGTGAC CAGATACATC TATAACCGAG AGGAGTACGC
 GCGCTTCGAC AGCGACGTGG GGAAGTACCT GCCGGTGACG CCTCTGGGGC
 CGCCTGCCGC CGAGTATTGG AACAGCCAGA AGGACTTCCT GGAGAGCACC
 CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT TGGAGCTCCG
 CACGATCTTG CAGCGGCGAG *  
>DL;IPD:MHC00423
IPD:MHC00423 Mamu-DQB1*17:09 270 bases
 AGGATTTCGT GTACCAGTTT AAGTGCCTGT GCTACTTCAC CAACGGGACG
 GAGCGCGTGC ATTATGTGAC CAGACACATT TATAACCGAG AGGAGTACGT
 GCGCTTCGAC AGCGACTGGG GGGAGTACCG GGCGGTGACG CCGCTGGGGC
 GACCTGCCGC CGAGTACTGG AACAGCCAGA AGGACTTCCT GGAGAGCACC
 CGGGCGGAGT TGGACACGGT GTGCAAACAC AACTACCAGT TGGAACTCCT
 CACGACCTTG CAGCGGCGAG *  
>DL;IPD:MHC01277
IPD:MHC01277 Mamu-DQB1*17:10 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACG
 GAGCGCGTGC GTCTTGTGAC CAGACACGTT TATAACCGAG AGGAGTACGT
 GCGCTTCGAC AGCGACTGGG GGGAGTACCG GGCGGTGACG CCGCTGGGGC
 GACCTACCGC CGAGTACTGG AACAGCCAGA AGGACTTCCT GGAGAGCACC
 CGGGCGGAGT TGGACACGGT GTGCAAACAC AACTACCAGT TGGAACTCCT
 CACGACCTTG CAGCGGCGAG *  
>DL;IPD:MHC02194
IPD:MHC02194 Mamu-DQB1*17:11 269 bases
 AGGATTTCGT GTACCAGTTT AAGGCCATGT GCTACTTCAC CAACGGGACG
 GAGCGCGTGC ATTATGTGAC CAGATACATC TATAACCGAG AGGAGTACGC
 GCGCTTCGAC AGCGACGTGG GGAAGTACCT GCCGGTGACG CCTCTGGGGC
 CGCCTGACGC CGAGTATTGG AACAGCCAGA AGGACTTCCT GGAGAGCACC
 CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT TGGAGCTCCG
 CACGATCTTG CAGCGGCGA*   
>DL;IPD:MHC03499
IPD:MHC03499 Mamu-DQB1*17:12 270 bases
 GAGGATTTCG TGTACCAGTT TAAGTGCCTG TGCTACTTCA CCAACGGGAC
 GGAGCGCGTG CATTATGTGA CCAGACACAT TTATAACCGA GAGGAGTACG
 TGCGCTTCGA CAGCGACTGG GGGGAGTACC GGGCGGTGAC GCCGCTGGGG
 CGACCTACCG CCGAGTACTG GAACAACCAG AAGGACTTCC TGGAGAGCAC
 CCGGGCGGAG TTGGACACGG TGTGCAAACA CAACTACCAG TTGGAACTCC
 TCACGACCTT GCAGCGGCGA *  
>DL;IPD:MHC04026
IPD:MHC04026 Mamu-DQB1*17:13 270 bases
 GAGGATTTCG TGTACCAGTT TAAGGCCATG TGCTACTTCA CCAACGGGAC
 GGAGCGCGTG CATTATGTGA CCAGATACAT CTATAACCGA GAGGAGTACG
 CGCGCTTCGA CAGCGACGTG GGGAAGTACC TGCCGGTGAC GCCTCTGGGG
 CCGCCTGCCG CCGAGTATTG GAACAGCCAG AAGGACGTCC TGGAGAGGAC
 CCGGGCGGAG TTGGACACGG TGTGCAGACA CAACTACCAG TTGGAGCTCC
 GCACGATCTT GCAGCGGCGA *  
>DL;IPD:MHC00424
IPD:MHC00424 Mamu-DQB1*18:01 726 bases
 ATGCTGGCGA TGCTGAGCAC CCCAGTGGCT GAGGGCAGAG ACTCTCCCGA
 GGATTTCGTG CACCAGTTTA AGGGCCTGTG CTACTTCACC AACGGGACGG
 AGCGCGTGCG GAGTGTGACC AGATACATCT ATAACCGAGA GGAGTACGTG
 CGCTTCGACA GCGACTGGGG GGAGTACCGG GCGGTGACGC CGCAGGGGCA
 GTCTGACGCC GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGAGGACCC
 GGGCGGAGTT GGACACGGTG TGCATACACA ACTACCAGTT GGAGCTCCGC
 ACCACCTTGC AGCGGCGAGT GGAGCCCACA GTGACCATCT CCCCGTCCAG
 GACAGAGGCC CTCAACCACC ACAACCTGCT GGTCTGCTCG GTGACAGATT
 TCTATCCAGG CCAGATCAAA GTCCGGTGGT TTCGGAATGA CCAGGAGGAG
 ACAGCTGGCA TTGTGTCCAC CCCCCTTATT AGGAACGGTG ACTGGACCTT
 CCAGATCCTG GTGATGCTAG AAATGACTCC CCAGCGTGGA GACGTCTACA
 CCTGCCACGT GGAGCACCCC AGCCTCCAGA GACCCATCAC TGTGGAGTGG
 CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG GTGTTGGAGG
 TTTTGTGCTG GGATTGATCT TCCTCGGGCT GGGCCTTATC ATCCATCACA
 GGAGTCAGAA AGGGCTCCTG CACTGA*  
>DL;IPD:MHC00425
IPD:MHC00425 Mamu-DQB1*18:02 786 bases
 ATGCCTCGGA AGAAGGCTTT GCGGATTCCC GGAGGCCTTT GGGGGACAAC
 TGTGACCTTG ATGCTGGCGA TGCTGAGCAC CCCAGTGGCT GGGGGCAGAG
 ACTCTCCCGA GGATTTCGTG TACCAGTTTA AGGGCCTGTG CTACTTCACC
 AACGGGACGG AGCGCGTGCG TCTTGTGACC AGATACATCT ATAACCGAGA
 GGAGTACGTG CGCTTCGACA GCGACTGGGG GGAGTACCGG GCGGTGACGC
 CGCTGGGGCC GCCTGCTGCA GAGTACTGGA ACAGCCAGAA GGACATCCTG
 GAGAGGACCC GGGCGGAACT GGACACGGTG TGCAGACACA ACTACCAGTC
 AGAGCTCCGC ACGACCTTGC AGCGGCGAGT GGAGCCCACA GTGACCATCT
 CCCCATCCAG GACAGAGGCC CTCAACCACC ACAACCTGCT GGTCTGCTCG
 GTGACAGATT TCTATCCAGG CCAGATCAAA GTCCGGTGGT TTCGGAATGA
 CCAGGAGGAG ACAGCCGGCA TTGTGTCCAC CCCCCTCATT AGGAACGGCG
 ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GACGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA GCCCCATCAC
 CGTGGAGTGG CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG
 GTGTTGGAGG CTTCGTGCTG GGACTGATCT TCCTTGGGTT GGGCCTTATC
 ATCCATTACA GGAGTCAGAA AGGGCTCCTG CACTGA* 
>DL;IPD:MHC00426
IPD:MHC00426 Mamu-DQB1*18:03 786 bases
 ATGCCTCCGA AGAAGGCTTT GCGGATCCCC GGAGGACTTT GGGGGACAAC
 TGTGACCTTG ATGCTGGCGA TGCTGAGCAC CCCTGTGGCT GAGGGCAGAG
 ACTCTCCCGA GGATTTCGTG TACCAGTTTA AGGGCCTGTG CTACTTCACC
 AACGGGACGG AGCGCGTGCG TCTTGTGACC AGACACATTT CTAACCGAGA
 GGAGTTCGTG CGCTTCGACA GCGACTGGGG GGAGTACCGG GCGGTGACTC
 CGCTGGGGCG ACCTGACGCC GAGTACTGGA ACAGCCAGAA GGACTTCCTG
 GAGAGGACCC GGGCGTCGGT GGACACGGTG TGCAGACACA ACTACCAGTC
 GGAGCTCCGC ACGACCTTGC AACGGCGAGT GGAGCCCACA GTGACCATCT
 CCCCATCCAG GACAGAGGCC CTCAACCACC ACAACCTGCT GGTCTGCTCG
 GTGACAGATT TCTATCCAGG CCAGATCAAA GTCCAGTGGT TTCGGAATGA
 CCAGGAGGAG ACAGCCGGCA TTGTGTCCAC CCCCCTTATT AGGAACGGCG
 ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GACGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA GACCCATCAC
 TGTGGAGTGG CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG
 GTGTTGGAGG CTTTGTGCTG GGATTGATCT TCCTCGGGCT GGGCCTTATC
 ATCCATCACA GGAGTCAGAA AGGGCTCCTG CACTGA* 
>DL;IPD:MHC00427
IPD:MHC00427 Mamu-DQB1*18:04 786 bases
 ATGCCTCCGA AGAAGGCTTT GCGGATCCCC GGAGGACTTT GGGGGACAAC
 TGTGACCTTG ATGCTGGCGA TGCTGAGCAC CCCTGTGGCT GAGGGCAGAG
 ACTCTCCCGA GGATTTCGTG TACCAGTTTA AGGGCCTGTG CTACTTCACC
 AACGGGACGG AGCGCGTGCG TCTTGTGACC AGACACATTT CTAACCGAGA
 GGAGTTCGTG CGCTTCGACA GCGACTGGGG GGAGTACCGG GCGGTGACTC
 CGCTGGGGCG ACCTGACGCC GAGTACTGGA ACAGCCAGAA GGACATCCTG
 GAGAGGACCC GGGCGGAGTT GGACACGGTG TGCAGACACA ACTACCAGTC
 GGAGCTCCGC ACGACCTTGC AACGGCGAGT GGAGCCCACA GTGACCATCT
 CCCCATCCAG GACAGAGGCC CTCAACCACC ACAACCTGCT GGTCTGCTCG
 GTGACAGATT TCTATCCAGG CCAGATCAAA GTCCAGTGGT TTCGGAATGA
 CCAGGAGGAG ACAGCCGGCA TTGTGTCCAC CCCCCTTATT AGGAACGGCG
 ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GACGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA GACCCATCAC
 TGTGGAGTGG CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG
 GTGTTGGAGG CTTTGTGCTG GGATTGATCT TCCTCGGGCT GGGCCTTATC
 ATCCATCACA GGAGTCAGAA AGGGCTCCTG CACTGA* 
>DL;IPD:MHC00428
IPD:MHC00428 Mamu-DQB1*18:07 246 bases
 TACCAGTTTA AGGGCCTGTG CTACTTCATC AACGGGACGG AGCGCGTGCG
 GGGTGTGACC AGACACATTT ATAACCGAGA GGAGTACGTG CGCTTCGACA
 GCGACTGGGG GGAGTACCGG GCGGTGACGC CGCTGGGGCG ACCTGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGAGCACCC GGGCGGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGTT GGAGCTCCGC ACGACC*
>DL;IPD:MHC00429
IPD:MHC00429 Mamu-DQB1*18:08 786 bases
 ATGTCTTGGA AGAAGGCTTT GCGGATCCCT GGAGGCCTTC GAGCAGCAAC
 CGTGACCTTG ATGCTGGCGA TGCTGAGTAC CCCAGTGGCT GAGGGCAGAG
 ACTCTCCCGA GGATTTCGTG TTCCAGTTTA AGGGCATGTG CTACTTCATC
 AACGGGACGG AGCACGTGCA TCATGTGAAC AGATACATCT ATAACCGAGA
 GGAGTTCGTG GGCTTCGACA GCTACTTGGG TGTGTACCGG CCAGTGACGC
 CGCTGGGGCG GTCTTGGGCC GAGTACTGGA ACAGCCAGAA GGACATCCTG
 GAGCGCACCC GGGCGGTGGT GGACACGGTG TGCAGACACA ACTACCAGTC
 GGAGCTCCGC ACGACCTTGC AACGGCGAGT GGAGCCCACA GTGACCATCT
 CCCCATCCAG GACAGAGGCC CTCAACCACC ACAACCTGCT GGTCTGCTCA
 GTGACAGATT TCTATCCAGG CCAGATCAAA GTCCGGTGGT TTCGAAATGA
 CCAGGAGGAG ACAACCGGCA TTGTGTCCAC TCCCCTTATT AGGAACGGCG
 ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GATGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAAA GCCCCATCAC
 CGTGGAGTGG CGGGCTCAAT CTGAATCTGC CCAGAGCAAG ATGATGAGTG
 GCATTGGAGG CTTCGTGCTG GGGCTGATCT TCCTTGCACT GGGCCTTATC
 ATCCATCACA GGAGTCAGAA AGGGCTCCTG CACTGA* 
>DL;IPD:MHC00430
IPD:MHC00430 Mamu-DQB1*18:09 786 bases
 ATGCCTCGGA AGAAGGCTTT GCGGATCCCC GGAGGCCTTT GGGGGACAAC
 TGTGACCTTG ATGCTGGCGA TGCTGAGCAC CCCAGTGGCT GAGGGCAGAG
 ACTCTCCCGA GGATTTCGTG TACCAGTTTA AGGGCCTGTG CTACTTCATC
 AACGGGACGG AGCGCGTGCG GGGTGTGACC AGACACATTT ATAACCGAGA
 GGAGTACGTG CGCTTCGACA GCGACTGGGG GGAGCACCGG GCGGTGACGC
 CGCTGGGGCG GTCTTGGGCC GAGTACTGGA ACAACCAGAA GGACTTCCTG
 GAGACGACCC GGGCGTCGGT GGACACGGTG TGCAGACACA ACTACCAGTC
 GGAGCTCCGC ACGACCTTGC AGCGGCGAGT GGAGCCCACA GTGACCATCT
 CCCCGTCCAG GACAGAGGCC CTCAACCACC ACAACCTGCT GGTCTGCTCG
 GTGACAGATT TCTATCCAAG CCAGATCAAA GTCAAGTGGT TTCGGAATGA
 CCAGGAAGAG ACAACTGGCG TTGTGTCCAC CCCCCTTATT AGGAACGGCG
 ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GATGTCTACA CCTGCCGCGT GGAGCACCCC AGCCTCCAGA GCCCCATCAC
 TGTGGAGTGG CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG
 GCGTTGGAGG CTTCGTGCTG GGACTGATCT TCCTTGGGCT GGGCCTTATC
 ATCCATTACA GGAGTCAGAA AGGGCTCCCG CACTGA* 
>DL;IPD:MHC00431
IPD:MHC00431 Mamu-DQB1*18:10 786 bases
 ATGCCTCGGA AGAAGGCTTT GCGGATCCCC GGAGGCCTTT GGGGGACAAC
 TGTGACCTTG ATGCTGGCGA TGCTGAGCAC CCCAGTGGCT GAGGGCAGAG
 ACTCTCCCGA GGATTTCGTG GTCCAGTTTA AGGGCCTGTG CTACTTCACC
 AACGGGACGG AGCGCGTGCG TCATGTGACC AGATACATCT ATAACCGAGA
 GGAGTACGCG CGCTTCGACA GCGACTGGGG GGAGTACCGG GCGGTGACGC
 CGCTGGGGCG ACCTGACGCC GAGTACTGGA ACAGCCAGAA GGACATCCTG
 GAGAGCACCC GGGCGGAGGC GGACACGGTG TGCAGACACA ACTACCAGTC
 AGAGCTCCGC ACGACGTTGC AGCGGCGAGT GGAGCCCACA GTGACCATCT
 CCCCATCCAG GACAGAGGCC CTCAACCACC ACAACCTGCT GGTCTGCTCG
 GTGACAGATT TCTATCCAGG CCAGATCAAA GTCCGGTGGT TTCGGAATGA
 CCAGCAGGAG ACAGCCGGCA TTGTGTCCAC CCCCCTTATT AGGAACGGCG
 ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGGGGA
 GATGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA GCCCCATCAC
 CGTGGAGTGG CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG
 GCGTTGGAGG CTTCGTGCTG GGACTGATCT TCCTTGGGCT GGGCCTTATC
 ATCCATCACA GGAGTCAGAA AGGGCTCCCG CACTGA* 
>DL;IPD:MHC00432
IPD:MHC00432 Mamu-DQB1*18:11 786 bases
 ATGCCTCGGA AGAAGGCTTT GCGGATCCCC GGAGGCCTTT GGGGGACAAC
 TGTGACCTTG ATGCTGGCGA TGCTGAGCAC CCCAGTGGCT GAGGGCAGAG
 ACTCTCCCGA GGATTTCGTG TACCAGTTTA AGGGCCTGTG CTACTTCATC
 AACGGGACGG AGCGCGTGCG GGGTGTGACC AGACACATTT ATAACCGAGA
 GGAGTACGTG CGCTTCGACA GCGACTGGGG GGAGCACCGG GCGGTGACGC
 CGCTGGGGCG GTCTTGGGCC GAGTACTGGA ACAACCAGAA GGACTTCCTG
 GAGACGACCC GGGCGTCGGT GGACACGGTG TGCAGACACA ACTACCAGTT
 GGAACTCCGC ACGACCTTGC AGCGGCGAGT GGAGCCCACA GTGACCATCT
 CCCCGTCCAG GACAGAGGCC CTCAACCACC ACAACCTGCT GGTCTGCTCG
 GTGACAGATT TCTATCCAAG CCAGATCAAA GTCAAGTGGT TTCGGAATGA
 CCAGGAAGAG ACAACTGGCG TTGTGTCCAC CCCCCTTATT AGGAACGGCG
 ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GATGTCTACA CCTGCCGCGT GGAGCACCCC AGCCTCCAGA GCCCCATCAC
 TGTGGAGTGG CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG
 GCGTTGGAGG CTTCGTGCTG GGACTGATCT TCCTTGGGCT GGGCCTTATC
 ATCCATTACA GGAGTCAGAA AGGGCTCCCG CACTGA* 
>DL;IPD:MHC00433
IPD:MHC00433 Mamu-DQB1*18:12 270 bases
 GAGGATTTCG TGTACCAGTT TAAGGGCCTG TGCTACTTCA CCAACGGGAC
 GGAGCGCGTG CGTCTTGTGA CCAGATACAT CTATAACCGA GAGGAGTACG
 TGCGCTTCGA CAGCGACTGG GGGGAGTACC GGGCGGTGAC GCCGCTGGGG
 CCGCCTGACG CCGAGTACTG GAACAGCCAG AAGGACATCC TGGAGAGCAC
 CCGGGCGGAG GCGGACACGG TGTGCAGACA CAACTACCAG TCAGAGCTCC
 GCACGACCTT GCAGCGGCGA *  
>DL;IPD:MHC00434
IPD:MHC00434 Mamu-DQB1*18:13 246 bases
 GTCCAGTTTA AGGGCCTGTG CTACTTCACC AACGGGACGG AGCGCGTGCG
 GAGTGTGACC AGATACATCT ATAACCGAGA GGAGTACGCG CGCTTCGACA
 GCGACTGGGG GGAGTACCGG GCGGTGACGC CGCTGGGGCG ACCTGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGAGCACCC GGGCGGAGGC
 GGACACGGTG TGCATACACA ACTACCAGTC AGAGCTCCGC ACGACG*
>DL;IPD:MHC00435
IPD:MHC00435 Mamu-DQB1*18:14 246 bases
 TTCCAGTTTA AGGGCCTGTG CTACTTCACC AACGGGACGG AGCGCGTGCG
 TCATGTGACC AGATACATCT ATAACCGAGA GGAGTACGCG CGCTTCGACA
 GCGACTGGGG GGAGTACCGG GCGGTGACGC CGCTGGGGCG GTCTTGGGCC
 GAGTACTGGA ACAACCAGAA GGACATCCTG GAGAGCACCC GGGCGGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGTC AGAGCTCCGC ACGACG*
>DL;IPD:MHC01067
IPD:MHC01067 Mamu-DQB1*18:15 269 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAT CAACGGGACG
 GAGCGCGTGC GGGGTGTGAC CAGACACATT TATAACCGAG AGGAGTACGT
 GCGCTTCGAC AGCGACTGGG GGGAGTACCG GGCGGTGACG CCGCTGGGGC
 GGTCTTGGGC CGAGTACTGG AACAACCAGA AGGACTTCCT GGAGACGACC
 AGGGCGTCGG TGGACACGGT GTGCAAACAC AACTACCAGT TGGAACTCCG
 CACGACCTTG CAGCGGCGA*   
>DL;IPD:MHC02191
IPD:MHC02191 Mamu-DQB1*18:17 269 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACG
 GAGCGCGTGC GTCTTGTGAC CAGACACGTT TATAACCGAG AGGAGTACGT
 GCGCTTCGAC AGCGACTGGG GGGAGCACCG GGCGGTGACG CCGCTGGGGC
 GGCCTAGCGC CGAGTACTGG AACAGCCAGA AGGACTTCCT GGAGACGACC
 CGGGCGTCGG TGGACACGGT GTGCAAACAC AACTACCAGT CGGAGCTCCG
 CACGACCTTG CAGCGGCGA*   
>DL;IPD:MHC02195
IPD:MHC02195 Mamu-DQB1*18:18 269 bases
 AGGATTTCGT GTTCCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACG
 GAGCGCGTGC GTCATGTGAC CAGATACATC TATAACCGAG AGGAGTACGC
 GCGCTTCGAC AGCGACTGGG GGGAGTACCG GGCGGTGACG CCGCTGGGGC
 GACCTGACGC CGAGTACTGG AACAGCCAGA AGGACATCCT GGAGAGCACC
 CGGGCGGAGG CGGACACGGT GTGCAGACAC AACTACCAGT CAGAGCTCCG
 CACGACGTTG CAGCGGCGA*   
>DL;IPD:MHC02197
IPD:MHC02197 Mamu-DQB1*18:19 269 bases
 AGGATTTCGT GGTCCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACG
 GAGCGCGTGC GGAGTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC
 GCGCTTCGAC AGCGACTGGG GGGAGTACCG GGCGGTGACG CCGCTGGGGC
 GACCTGACGC CGAGTACTGG AACAGCCAGA AGGACATCCT GGAGAGCACC
 CGGGCGGAGG CGGACACGGT GTGCAGACAC AACTACCAGT CAGAGCTCCG
 CACGACGTTG CAGCGGCGA*   
>DL;IPD:MHC02198
IPD:MHC02198 Mamu-DQB1*18:20 269 bases
 AGGATTTCGT GGTCCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACG
 AAGCGCGTGC GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC
 GCGCTTCGAC AGCGACTGGG GGGAGTACCG GGCGGTGACG CCGCTGGGGC
 GACCTGACGC CGAGTACTGG AACAGCCAGA AGGACATCCT GGAGAGCACC
 CGGGCGGAGG CGGACACGGT GTGCAGACAC AACTACCAGT CAGAGCTCCG
 CACGACGTTG CAGCGGCGA*   
>DL;IPD:MHC02199
IPD:MHC02199 Mamu-DQB1*18:21 269 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAT CAACGGGACG
 GAGCGCGTGC GGGGTGTGAC CAGATACATC TATAACCGAG AGGAGTTCGT
 GCGCTTCGAC AGCGACTGGG GGGAGCACCG GGCGGTGACG CCGCTGGGGC
 GGTCTTGGGC CGAGTACTGG AACAACCAGA AGGACTTCCT GGAGACGACC
 CGGGCGTCGG TGGACACGGT GTGCAGACAC AACTACCAGT CGGAGCTCCG
 CACGACCTTG CAGCGGCGA*   
>DL;IPD:MHC02906
IPD:MHC02906 Mamu-DQB1*18:22 270 bases
 AGGATTTCGT GGTCCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACG
 GAGCGCGTGC GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC
 GCGCTTCGAC AGCGACTGGG GGGAGTACCG GGCGGTGACG CCGCTGGGGC
 GACCTGACGC CGAGTACTGG AACAGCCAGA AGGACATCCT GGAGAGCACC
 CGGGCGGAGG CGGACACGGT GTGCAGACAC AACTACCAGT CAGAGCTCCG
 CACGACGTTG CAGCGGCGAG *  
>DL;IPD:MHC03497
IPD:MHC03497 Mamu-DQB1*18:23 266 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAT CAACGGGACG
 GAGCGCGTGC GGGGTGTGAC CAGACACATT TATAACCGAG AGGAGTACGT
 GCGCTTCGAC AGCGACTGGG GGGAGCACCG GGCGGTGACG CCGCTGGGGC
 GGTCTTGGGC CGAGTACTGG AACAACCAGA AGGACTTCCT GGAGACGACC
 CGGGCGTCGG TGGACACGGT GTGCAGACAC AACTACCAGT TGGAGCTCCG
 CACCACCTTG CAGCGG*   
>DL;IPD:MHC03498
IPD:MHC03498 Mamu-DQB1*18:24 270 bases
 GAGGATTTCG TGGTCCAGTT TAAGGGCCTG TGCTACTTCA CCAACGGGAC
 GGAGCGCGTG CGTCATGTGA CCAGATACAT CTATAACCGA GAGGAGTACG
 TGCGCTTCGA CAGCGACTGG GGGGAGTACC GGGCGGTGAC GCCGCTGGGG
 CGACCTGACG CCGAGTACTG GAACAGCCAG AAGGACATCC TGGAGAGCAC
 CCGGGCGGAG GCGGACACGG TGTGCAGACA CAACTACCAG TCAGAGCTCC
 GCACGACGTT GCAGCGGCGA *  
>DL;IPD:MHC03578
IPD:MHC03578 Mamu-DQB1*18:25 786 bases
 ATGCCTTGGA AGAAGGCTTT GCGGATCCCT GGAGGCCTTT TGGGGGCAAC
 TGTGACCTTG ATGCTGGCGA TGCTGAGCAC CCCAGTGGCT GAGGGCAGAG
 ACTCTCCCGA GGATTTCGTG CACCAGTTTA AGGGCCTGTG CTACTTCACC
 AACGGGACGG AGCGCGTGCG GAGTGTGACC AGATACATCT ATAACCGAGA
 GGAGTACGTG CGCTTCGACA GCGACTGGGG GGAGTACCGG GCGGTGACGC
 CGCAGGGGCA GTCTGACGCC GAGTACTGGA ACAGCCAGAA GGACATCCTG
 GAGAGGACCC GGGCGGAGTT GGACATGGTG TGCATACACA ACTACCAGTT
 GGAGCTCCGC ACCACCTTGC AGCGGCGAGT GGAGCCCACA GTGACCATCT
 CCCCGTCCAG GACAGAGGCC CTCAACCACC ACAACCTGCT GGTCTGCTCG
 GTGACAGATT TCTATCCAGG CCAGATCAAA GTCCGGTGGT TTCGGAATGA
 CCAGGAGGAG ACAGCTGGCA TTGTGTCCAC CCCCCTTATT AGGAACGGTG
 ACTGGACCTT CCAGATCCTG GTGATGCTAG AAATGACTCC CCAGCGTGGA
 GACGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA GACCCATCAC
 TGTGGAGTGG CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG
 GTGTTGGAGG TTTTGTGCTG GGATTGATCT TCCTCGGGCT GGGCCTTATC
 ATCCATCACA GGAGTCAGAA AGGGCTCCTG CACTGA* 
>DL;IPD:MHC04027
IPD:MHC04027 Mamu-DQB1*18:26N 270 bases
 GAGGATTTCG TGTACCAGTT TAAAGGCCTG TGCTACTTCA CCAACGGGAC
 GGAGCGCGTG CGTCTTGTGA CCAGATACAT CTATAACCGA GAGGAGTACG
 TGCGCTTCGA CAGCGACTGG GGGGAGTACC GGGCGGTGAC GCCGCTGGGG
 CCGCCTGCTG CAGAGTACTG GAACAGCTAG AAGGACATCC TGGAGAGGAC
 CCGGGCGGAA CTGGACACGG TGTGCAGACA CAACTACCAG TCAGAGCTCC
 GCACGACCTT GCAGCGGCGA *  
>DL;IPD:MHC00436
IPD:MHC00436 Mamu-DQB1*24:01 270 bases
 AGGATTTCGT GGTCCAGTTT AAGGCCATGT GCTACTTCAC CAACGGGACG
 GAGCGCGTGC ATTATGTGAC CAGATACATC TATAACCGAG AGGAGTTCGC
 GCGCTTCGAC AGCGACGTGT GGGAGTACCG GGCCGTGACG CCGCTGGGGC
 GGTCTTGGGC CGAGAACTGG AACAACCAGA AGGACGTCCT GGAGAGGACC
 CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT TGGAACTCCT
 CTCGACCTTG CAGCGGCGAG *  
