>DL;IPD:MHC00586
IPD:MHC00586 Mamu-G*02:01 123 bases
 AVSRPGRGKP RFIAVGHVED TQFVRLDSDA ASPRMEPRAP WVEQEGPEYW
 EEETRIAKAH AHTDRVNLRT LRSYYNQSQA GSHTLQWMIG CDLGPDGRLL
 CRCEQFAYDG KDYLALNEDL CSX*  
>DL;IPD:MHC00587
IPD:MHC00587 Mamu-G*02:02 123 bases
 AVSRPGRGEP RFIPVGYVDD TQFVRLDSDA ASPRMEPRAP WVEQEGPEYW
 EEETRIAKAH AHTDRVNLRT LRSYYNQSEA GSHTLQWMIG CDLGPDGRLL
 CRCEQFAYDG KDYLALNEDL CSX*  
>DL;IPD:MHC00588
IPD:MHC00588 Mamu-G*02:03 154 bases
 AVSRPGRGEP RFIAVGYVDD TQFVRFDSDA ASPRMEPRAP WVDQEGPEYW
 EEETRIAKAH AQTDRVNLRT LRSYYNQSEA GSHTLQWMIG CDLGPDGRLL
 RRCEQFAYDG KDYLALNEDL LSWTAADTVA QISKRKREAA KATERRRAYL
 EGTX*    
>DL;IPD:MHC00589
IPD:MHC00589 Mamu-G*02:04 123 bases
 ALSRPGRGKP RFIAVGHVED TQFLRLDSDA ASPRMEPRAP WVEQEGPEYW
 EEETRIAKAH AHTDRVNLRT LRSYYNQSQA GSHTLQWMIG CDLGPDGRLL
 CRCEQFAYDG KDYLALNEDL CSX*  
