>DL;IPD:MHC00577
IPD:MHC00577 Mamu-E*02:01:01 166 bases
 HTSVSRPGRG GPRFISVGYV DDTQFVRYDS DAASPRMEPR APWVEQEGPE
 YWDQETRSAR DTAQTFRVNL ETLRGYYNQS EAGSHTLQWM HGCDLGPDGR
 FLRGYEQFAY DGKDYLTLNE DLRSWSAVDT AAQISEQKSN DGSEAEHQRA
 YLEDTCVEWL HRYLEN*   
>DL;IPD:MHC02417
IPD:MHC02417 Mamu-E*02:01:02 360 bases
 MALRTLLLLL SALTKTWAGS HSLKYFHTSV SRPGRGGPRF ISVGYVDDTQ
 FVRYDSDAAS PRMEPRAPWV EQEGPEYWDQ ETRSARDTAQ TFRVNLETLR
 GYYNQSEAGS HTLQWMHGCD LGPDGRFLRG YEQFAYDGKD YLTLNEDLRS
 WSAVDTAAQI SEQKSNDGSE AEHQRAYLED TCVEWLHRYL ENGKETLQRS
 EPPKTHVTHH PVSDHEATLR CWALGFYPAE ITVTWQRDGE DQTQDTELVE
 TRPAGDGTFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPLTL RWEPSSPSTI
 PIVGISAGLV LLGAVVTGAV VAAVMWRRKS SGRKGGSYSQ ASCSDSTQGS
 DESLTACKAX *   
>DL;IPD:MHC00578
IPD:MHC00578 Mamu-E*02:02 355 bases
 MALRTLLLLL SALTKTWAGS HSLKYFHTSV SRPGRGEPRF ISVGYVDDTQ
 FVRYDSDAAS PRMEPRALWM KQEGPEYWDQ ETRSARDTAQ TFRVNLKTLR
 GYYNQSEAGS HTLQWMHGCD LGPDGRFFRG YEQFAYDGKD YLTLNEDLRS
 WSAVDTAAQI SEQKSNDGSE AEHQRAYLED TCVEWLRRYL ENGKETLLRS
 ESPKTHVTRH PVSDHEATLR CWALGFYPAE ITVTWQRDGE DQTQDTELVE
 TRPAGDGTFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPLIL RWEPSSQSSI
 PIVGIIVGLV LLGAVVTGAV VAAVMWRKSS GRKGRSYSQA SCSDSAQGSD
 ESLTA*    
>DL;IPD:MHC00579
IPD:MHC00579 Mamu-E*02:03 360 bases
 MALGTLLLLL SALTKTWAGS HSLKYFHTSV SRPGRGGPRF ISVGYVDDTQ
 FVRYDSDAAS QRMEPRAPWV EQEGPEYWDQ ETRSARDTAQ TFRVNLETLR
 GYYNQSEAGS HTLQWMHGCD LGSDGRFLRG YEQFAYDGKD YLTLNEDLRS
 WSAVDTAAQI SEQKSNDGSE AEHQRAYLED TCVEWLHRYL ENGKETLQRS
 EPPKTHVAHH PVSDHEATLR CWALGFYPAE ITVTWQRDGE DQTQDTELVE
 TRPAGDGTFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPLTL RWEPSSQSTI
 PIVGIIAGLV LLGAVVTGAV IVAVMWRRKS SGRKGGSYSQ ASCSDSTQGS
 DESLTACKAX *   
>DL;IPD:MHC00580
IPD:MHC00580 Mamu-E*02:04 360 bases
 MALRTLLLLL SALTKTWAGS HSLKYFHTSV SRPGGGGPRF ISVGYVDDTQ
 FVRYDSDAAS PRMEPRALWM KQEGPEYWDQ ETRSARATAQ TFRVNLETLR
 GYYNQSEAGS HTLQWMHGCD LGPDGRFLRG YEQFAYDGKD YLTLNEDLRS
 WSAVDTAAQI SEQKSNDGSE AEHQRAYLED TCVEWLRRYL ENGKETLQRS
 ESPKTHVTHH PVSDHEATLR CWALGFYPAE ITVTWQRDGE DQTQDTELVE
 TRPAGDGTFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPLTL RWEPSSQSTI
 PIVGIIAGLV LLGAVLTGAV VAAVVWRRKS SGRKGWSYSQ AVGSDSSQGS
 DDSLTAYKPX *   
>DL;IPD:MHC00581
IPD:MHC00581 Mamu-E*02:05 359 bases
 MALGTLLLLL SALTKTWAGS HSLKYFHTSV SRPGRGEPRF ISVGYVDDTQ
 FVRFDSDAAS PRMEPRAPWV EQEGPEYWDQ ETRSARDTAQ TFRVNLKTLR
 GYYNQSEAAS HTLQWMHGCD LGPDGRFLRG YEQFAYDGKD YLTLNEDLRS
 WSAVDTAAQI SERKSNDGSE AEHQRAYLED TCVEWLRRYL ENGKETLQRP
 ESPKTHVTHH PVSGHEATLR CWALGFYPAE ITVTWQRDGE DQTQDTELVE
 TRPAGDGTFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPLTL RWEPSSQSTI
 AIVGIIAGLV LGAVVTGAVV AAVMWRRKSS GRKGWSYSQA VGSDSSQGSD
 DSLTAYKPX*    
>DL;IPD:MHC00582
IPD:MHC00582 Mamu-E*02:06 193 bases
 LTKTWAGSHS LKYFHTSVSR PGGGGPRFIS VGYVDDTQFV RYDSDAASPR
 MEPRALWMKQ EGPEYWDQET RSARATAQTF RVNLETLRGY YNQSEAGSHT
 LQWMHGCDLG PDGRFLRGYE QFAYDGKDYL TLNEDLRSWS AVDTAAQISE
 QKSNDGSEAE HQRAYLEDTC VEWLHRYLEN GKETLQRSEP PKT*
>DL;IPD:MHC02638
IPD:MHC02638 Mamu-E*02:07 360 bases
 MALRTLLLLL SALTKTWAGS HSLKYFHTSV SRPGRGGPRF ISVGYVDDTQ
 FVRYDSDAAS PRMEPRAPWV EQEGPEYWDQ ETRSARDTAQ TFRVNLETLR
 GYYNQSEAGS HTLQWMHGCD LGSDGRFLRG YEQFAYDGKD YLTLNEDLRS
 WSAVDTAAQI SEQKSNDGSE AEHQRAYLED TCVEWLHRYL ENGKETLQRS
 EPPKTHVTHH PVSDHEATLR CWALGFYPAE ITVTWQRDGE DQTQDTELVE
 TRPAGDGTFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPLTL RWEPSSQSTI
 PIVGISAGLV LLGAVVTGAV VAAVMWRRKS SGRKGGSYSQ ASCSDSTQGS
 DESLTACKAX *   
>DL;IPD:MHC00584
IPD:MHC00584 Mamu-E*02:08 193 bases
 LTKTWAGSHS LKYFHTSVSR PGRGGPRFIS VGYVDDTQFV RYDSDAASQR
 MEPRAPWVEQ EGPEYWDQET RSARDTAQTF RVNLETLRGY YNQSEAGSHT
 LQWMHGCDLG SDGRFLRGYE QFAYDGKDYL TLNEDLRSWS AVDTAAQTSA
 QKSNDGGEAE HQRAYLEDTC VEWLRRYLEN GKETLQRSQS PKT*
>DL;IPD:MHC02639
IPD:MHC02639 Mamu-E*02:09 359 bases
 MALRTLLLLL SALTKTWAGS HSLKYFHTSV SRPGRGGPRF ISVGYVDDTQ
 FVRYDSDAAS PRMEPRAPWV EQEGPEYWDQ ETRSARDTAQ TFRVNLETLR
 GYYNQSEAGS HTLQWMHGCD LGSDGRFLRG YEQFAYDGKD YLTLNEDLRS
 WSAVDTAAQI SEQKSNDGSE AEHQRAYLED TCVEWLRRYL ENGKETLQRS
 EPPKTHVTHH PISDHEATLR CWALGFYPAE ITVTWQRDGE DQTQDTELVE
 TRPAGDGTFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPLTL RWEPSSQSTI
 PIVGIIAGLV LLGAVVVAVV VAVMWRRKSS GRKGGSYSQA SCSDSTQGSD
 ESLTACKAX*    
>DL;IPD:MHC01629
IPD:MHC01629 Mamu-E*02:10 359 bases
 MALRTLLLLL SALTKTWAGS HSLKYFHTSV SRPGRGGPRF ISVGYVDDTQ
 FVRYDSDAAS PRMEPRAPWV EQEGPEYWDQ ETRSARDTAQ TFRVNLETLR
 GYYNQSEAGS HTLQWMHGCD LGPDGRFLRG YEQFAYDGKD YLTLNEDLRS
 WSAVDTAAQI SEQKSNDGSE AEHQRAYLED TCVEWLHRYL ENGKETLQRS
 EPPKTHVTHH PVSDHEATLR CWALGFYPAK ITVTWQRDGE DQTQDTELVE
 TRPAGDGTFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPLTL RWEPSSQSTI
 PIVGIIAGLV LLGAMVVAVV VAVMWRRKSS GRKGGSYSQA SCSDSTQGSD
 ESLTACKAX*    
>DL;IPD:MHC01630
IPD:MHC01630 Mamu-E*02:11 359 bases
 MALRTLLLLL SALTKTWAGS HSLKYFHTSV SRPGRGGPRF ISVGYVDDTQ
 FVRYDSDAAS PRMEPRAPWV EQEGPEYWDQ ETRSARDTAQ TFRVNLETLR
 GYYNQSEAGS HTLQWMHGCD LGPDGRFLRG YEQFAYDGKD YLTLNEDLRS
 WSAVDTAAQI SEQKSNDGSE AEHQRAYLED TCVEWLHRYL ENGKETLQRS
 EPPKTHVTHH PVSDHEATLR CWALGFYPAE ITVTWQRDGE DQTQDTELVE
 TRPAGDGTFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPLTL RWEPSSQSTI
 PIVGIIAGLV LLGAMVVAVV VAVMWRRKSS GRKGGSYSQA SCSDSTQGSD
 ESLTACKAX*    
>DL;IPD:MHC01984
IPD:MHC01984 Mamu-E*02:12:01 360 bases
 MAQRTLLLLL SALTKTWAGS HSLKYFHTSV SRPGRGEPRF ISVGYVDDTQ
 FVRYDSDAAS PRMQPRAPWV EQEGPEYWDQ ETRSARDTAR TFRVNLETLR
 GYYNQSVAAS HTLQWMHGCD LAPDRRFLRG YEQFAYDGKD YLTLNEDLRS
 WSAVDTAAQI SAQKSNDGGE AEHQRAYLED TCVEWLRRYL ENGKETLQRS
 EPPKTHVTHH PVSDHEATLR CWALGFYPAE ITVTWQRDGE DQTQDTELVE
 TRPAGDGTFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPLTL RWEPSSQSTI
 PIVGISAGLV LLGTVVTGAV VAAVMWRRKS SGRKGGSYSQ ASCSDSTQGS
 DESLTAYKTX *   
>DL;IPD:MHC03583
IPD:MHC03583 Mamu-E*02:12:02 360 bases
 MAQRTLLLLL SALTKTWAGS HSLKYFHTSV SRPGRGEPRF ISVGYVDDTQ
 FVRYDSDAAS PRMQPRAPWV EQEGPEYWDQ ETRSARDTAR TFRVNLETLR
 GYYNQSVAAS HTLQWMHGCD LAPDRRFLRG YEQFAYDGKD YLTLNEDLRS
 WSAVDTAAQI SAQKSNDGGE AEHQRAYLED TCVEWLRRYL ENGKETLQRS
 EPPKTHVTHH PVSDHEATLR CWALGFYPAE ITVTWQRDGE DQTQDTELVE
 TRPAGDGTFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPLTL RWEPSSQSTI
 PIVGISAGLV LLGTVVTGAV VAAVMWRRKS SGRKGGSYSQ ASCSDSTQGS
 DESLTAYKTX *   
>DL;IPD:MHC01985
IPD:MHC01985 Mamu-E*02:13 352 bases
 MALRTLLLLL SALTKTSAGS HSLKYFHTSV SRPGHAEPHF ISVGYVDDTQ
 FVRYDSDAAS PRMEPRAPWV EQEGPEYWDQ ETRSARDTAQ TFRVNLKTLR
 GYYNQSVAGS HTLQWMHGCD LGPDGRFLRG YEQFAYDGKD YLTLNEDLRS
 WSAVDTAAQI SEQKSNNGSE AEYQRAYLED TCVEWLRRYL ENGKETLQRS
 EPPKTHVTHH PVSDHEAILR CWALGFYPAE ITVTWQRDGE DQTQDTELVE
 TRPAGDGTFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPLTL RWEPSSQPSI
 PILGIIAGLV LLGAVVIVVA AVMWRRKSSG GEERGSDSAQ GSDESLTAYK
 TX*    
>DL;IPD:MHC01986
IPD:MHC01986 Mamu-E*02:14 360 bases
 MALRTLLLLL SALTKTWAGS HSLKYFHTSV SRPGRGGPRF ISVGYVDDTQ
 FVRYDSDAAS PRMEPRAPWV EQEGPEYWDQ ETRSARDTAQ TFRVNLETLR
 GYYNQSEAGS HTLQWMHGCD LGSDGRFLRG YEQFAYDGKD YLTLNEDLRS
 WSAVDTAAQI SEQKSNDGSE AEHQRAYLED TCVEWLHRYL ENGKETLQRS
 EPPKTHVTHH PVSDHEATLR CWALGFYPAD ITVTWQRDGE DQTQDTELVE
 TRPAGDGTFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPLTL RWEPSSQSTI
 PIVGIIAGLV LLGAVVTGAV VVAVMWRRKS SGRKGGSYSQ ASCSDSTQGS
 DESLTACKAX *   
>DL;IPD:MHC01987
IPD:MHC01987 Mamu-E*02:15 340 bases
 MALRTLLLLL SALTKTWAGS HSLKYFHTSV SRPGRAEPHF ISVGYVDDTQ
 FVRYDSDAAS PRMQPRAPWV EQEGPEYWDQ ETRIARDTAR TFRVNLKTLR
 GYYNQSVAGS HTLQWMHGCD LGPDGRFLRG YEQFAYDGKD YLTLNEDLRS
 WSAMDTAAQI SEQKSNDGGE AEHQRAYLED TCVEWLRRYL ENGKETLQRS
 ESPKTHVTHH PISDHEATLR CWALGFYPAE ITVTWQRDGE DQTQDTELVE
 TRPAGDGTFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPLTL RWEPSSQPSI
 PIVGIIAGLD LLAAVVTGAV VAAVMWKRKS SGGEGREVDX *
>DL;IPD:MHC02418
IPD:MHC02418 Mamu-E*02:16 360 bases
 MALGTLLLLL SALTKTWAGS HSLKYFHTSV SRPGRGEPRF ISVGYVDDTQ
 FVRYDSDAAS PRMQPRAPWV EQEGPEYWDQ ETRSARDTAR TFRVNLETLR
 GYYNQSEAGS HTLQWMHGCD LAPDRRFLRG YEQFAYDGKD YLTLNEDLRS
 WSAVDTAAQT SAQKSNDGGE AEHQRAYLED TCVEWLRRYL ENGKETLQRS
 QSPKTHVTHH PVSDHEATLR CWALGFYPAE ITVTWQRDGE DQTQDTELVE
 TRPAGDGTFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPRAL RCEPSSQSTI
 PIVGISAGLV LLGTVVTGAV VVAVMWRRKS SGRKGWSYSQ ASCSDSTQGS
 DESLTAYKTX *   
>DL;IPD:MHC02629
IPD:MHC02629 Mamu-E*02:17 360 bases
 MALRTLLLLL SALTKTWAGS HSLKYFHTSV SRPGRGGPRF ISVGYVDDTQ
 FVRYDSDAAS PRMEPRAPWV EQEGPEYWDQ ETRSARDTAQ TFRVNLETLR
 GYYNQSEAGS HTLQWMHGCD LGSDGRFLRG YEQFAYDGKD YLTLNEDLRS
 WSAVDTAAQI SEQKSNDGSE AEHQRAYLED TCVEWLRRYL ENGKETLQRS
 EPPKTHVTHH PVSDHEATLR CWALGFYPAE ITVTWQRDGE DQTQDTELVE
 TRPAGDGTFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPLTL RWEPSSPSTI
 PIVGISAGLV LLGAVVTGAV VAAVMWRRKS SGRKGGSYSQ ASCSDSTQGS
 DESLTACKAX *   
>DL;IPD:MHC03582
IPD:MHC03582 Mamu-E*02:18 360 bases
 MALRTLLLLL SALTKTWAGS HSLKYFHTSV SRPGRGEPRF ISVGYVDDTQ
 FVRYDSDAAS PRMEPRAPWV EQEGPEYWDQ ETRSARDTAQ TFRVNLETLR
 GYYNQSEAGS HTLQWMHGCD LGSDGRFLRG YEQFAYDGKD YLTLNEDLRS
 WSAVDTAAQI SEQKSNDGSE AEHQRAYLED TCVEWLHRYL ENGKETLQRS
 ESPKTHVTHH PVSDHEATLR CWALGFYPAE ITVTWQRDGE DQTQDTELVE
 TRPAGDGTFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPRAL RWEPSSQSTI
 PIVGIIAGLV LLGAVVTGAV VVAVMWRRKS SGRKGGSYSQ ASCSDSTQGS
 DESLTACKAX *   
>DL;IPD:MHC00583
IPD:MHC00583 Mamu-E*02:19 360 bases
 MALRTLLLLL SALTKTWAGS HSLKYFHTSV SRPGRGGPRF ISVGYVDDTQ
 FVRYDSDAAS PRMEPRAPWV EQEGPEYWDQ ETRSARDTAQ TFRVNLETLR
 GYYNQSEAGS HTLQWMHGCD LGSDGRFLRG YEQFAYDGKD YLTLNEDLRS
 WSAVDTAAQI SEQKSNDGSE AEHQRAYLED TCVEWLHRYL ENGKETLQRS
 EPPKTHVTHH PVSDHEATLR CWALGFYPAE ITVTWQRDGE DQTQDTELVE
 TRPAGDGTFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPRAL RWEPSSQSTI
 PIVGIIAGLV LLGAVVTGAV VVAVMWRRKS SGRKGGSYSQ ASCSDSTQGS
 DESLTACKAX *   
>DL;IPD:MHC01628
IPD:MHC01628 Mamu-E*02:20 359 bases
 MALGSLLLLS ALTKTWAGSH SLKYFHTAVS RPGCVEPRFI FVGYVDDTQF
 VRFDSDAANP RMQPRAPWME QEGPEYWDQE TRRARDTAQT LRVKLKTLRG
 YYNQSEAGSH TLQWMYGCDL GPDGRFLREY EQFAYDGKDY LTLNEDLRSW
 SAVDTAAQIS EQKSNDGGEA EHQRAYLEDT CVEWLRRYLE NGKETLQRPE
 PPKTHVTHHP ISDHEATLRC WALGFYPAEI TVTWQRDGED QTQDTELVET
 RPAGDGTFQK WAAVVVPSGE EQRYTCHVQH EGLPEPLTLR WEPPSQHSIP
 IVGISAGLVL LGAVVTGAVV AAVMWRRKSS GRKGGSYSQA LCSDSTQGSE
 ESLTAYKTX*    
