>DL;IPD:MHC02114
IPD:MHC02114 Mamu-B11L*01:01:01 822 bases
 GCTCCCACTC CATGAGGTAT TTCCACACCG CCGTGTCCCG GCCCGGCCGC
 GGGGAGCCCC GCTTCATCGC CGTGGGTTAT GTGGACGACA CGCAGTTCGT
 GCGATTCGAC AGCAACGCCG CGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGATAGAGCA GGAGGGACCG GAGTATTGGG ACCGGGAGAC ACAGAAAGCC
 AAGGCCCACG CACAGGTTTT CCGAGTGAAC CTGCGCACCG CGCTTCGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC CTTCCAGAGG ATGCATGGCT
 GCGACCTGGG GCCTGACGGG CGCCTCCTCC GCGGGTATCA CCAGTTAGCC
 TATGATGGCA AGGATTACAT CGCCCTGAAC GGGGACCTGA GCTCCTGGAG
 CGCCGCGGAT ATGGCGGCTC AGGTCACACA GCGCAAGTGG GAGGCGGCCC
 GTGAAGCTGA GCAGCGGAGA GCCTACCTGG AGGGCGAGTG CCTGGAGTCG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGTGGATCC
 CCCAAAGACA CACGTGACCC ACCACCCAGT CTCTGACCAT GAGGCCATCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG
 CAGCGGGATG GGGAGGAGCA AACTCAGGAC ACTGAGCTTG TGGAGACCAG
 GCCCGCAGGG AACGGAACCT TCCAGAAATG GGCAGCTGTG GTGGTGCCTT
 CTGGAGAAGA GCAGAGATAC ACGTGCCATG TGCAGCACAA GGGGCTGCTG
 GAGCCCCTCA CCCTGAGATG GG*  
>DL;IPD:MHC02116
IPD:MHC02116 Mamu-B11L*01:01:02 822 bases
 GCTCCCACTC CATGAGGTAT TTCCACACCG CCGTGTCCCG GCCCGGCCGC
 GGGGAGCCCC GCTTCATCGC CGTGGGTTAC GTGGATGACA CGCAGTTCGT
 GCGGTTCGAC AGCAACGCCG CGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGATAGAGCA GGAGGGACCG GAGTATTGGG ACCGGGAGAC ACAGAAAGCC
 AAGGCCCACG CACAGGTTTT CCGAGTGAAC CTGCGCACCG CGCTTCGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC CTTCCAGAGG ATGCATGGCT
 GCGACCTGGG GCCTGACGGG CGCCTCCTCC GCGGGTATCA CCAGTTAGCC
 TATGATGGCA AGGATTACAT CGCCCTGAAC GGGGACCTGA GCTCCTGGAG
 CGCCGCGGAT ATGGCGGCTC AGGTCACACA GCGCAAGTGG GAGGCGGCCC
 GTGAAGCTGA GCAGCGGAGA GCCTACCTGG AGGGCGAGTG CCTGGAGTCG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGTGGATCC
 CCCAAAGACA CACGTGACCC ACCACCCCGT CTCTGACCAT GAGGCCATCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG
 CAGCGGGATG GGGAGGAGCA AACTCAGGAC ACTGAGCTTG TGGAGACCAG
 GCCCGCAGGG AACGGAACCT TCCAGAAATG GGCAGCTGTG GTGGTGCCTT
 CTGGAGAAGA GCAGAGATAC ACGTGCCATG TGCAGCACAA GGGGCTGCTG
 GAGCCCCTCA CCCTGAGATG GG*  
>DL;IPD:MHC02113
IPD:MHC02113 Mamu-B11L*01:02 822 bases
 GCTCCCACTC CATGAGGTAT TTCCACACCG CCGTGTCCCG GCCCGGCCGC
 GGGGAGCCCC GCTTCATCTC CGTGGGTTAC GTGGATGACA CGCAGTTCGT
 GCGGTTCGAC AGCAACGCCG CGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGATAGAGCA GGAGGGACCG GAGTATTGGG ACCGGGAGAC ACAGAAAGCC
 AAGGCCCACG CACAGGTTTT CCGAGTGAAC CTGCGCACCG CGCTTCGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC CTTCCAGAGG ATGCATGGCT
 GCGACCTGGG GCCAGACGGG CGCCTCCTCC GCGGGTATCA CCAGTTAGCC
 TATGATGGCA AGGATTACAT CGCCCTGAAC GGGGACCTGA GCTCCTGGAG
 CGCCGCGGAT ATGGCGGCTC AGGTCACACA GCGCAAGTGG GAGGCGGCCG
 GTGAAGCTGA GCAGCGGAGA GCCTACCTGG AGGGCGAGTG CCTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGGATCC
 CCCAAAGACA CACGTGACCC ACCACCCAGT CTCTGACCAT GAGGCCATCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG
 CAGCGGGATG GGGAGGAGCA AACACAGGAC ACTGAGCTTG TGGAGACCAG
 GCCCGCAGGG AACGGAACCT TCCAGAAATG GGCAGCTGTG GTGGTGCCTT
 CTGGAGAAGA GCAGAGATAC ACGTGCCATG TGCAGCACCA GGGGCTGCTG
 GAGCCCCTCA CCCTGAGATG GG*  
>DL;IPD:MHC02115
IPD:MHC02115 Mamu-B11L*01:03 822 bases
 GCTCCCACTC CATGAGGTAT TTCCACACCG CCGTGTCCCG GCCCGGCCGC
 GGGGAGCCCC GCTTCATCCC CGTGGGTTAT GTGGACCACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCG CGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGATAGAGCA GGAGGGGCCG GAGTATTGGG ACCGGGAGAC ACAGAAAGCC
 AAGGCCCACG CACAGGTTTT CCGAGTGAAC CTGCGCACCG CGCTTCGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC CTTCCAGAGG ATGCATGGCT
 GCGACCTGGG GCCTGACGGG CGCCTTCTCC GCGGGTATCA CCAGTTAGCC
 TATGATGGCA AGGATTACAT CGCCCTGAAC GGGGACCTGA GCTCCTGGAC
 CGCCGCGGAT ATGGCGGCTC AGGTCACACA GCGCAAGTGG GAGGCGGCCC
 GTGAAGCTGA ACAGCGGAGA GCCTACCTGG AGGGCGAGTG CCTGGAGTCG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGTGGATCC
 CCCAAAGACA CACGTGGCCC ACCACCCCGT CTCTGACCAT GAGGCCACAC
 TGAGGTGCTG GGCTCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG
 CAGCGAGATG GGGAGGAGCA AACTCAGGAC ACTGAGCTTG TGGAGACCAG
 GCCAGCAGGG GACAGAACCT TCCAGAAATG GGCAGCTGTG GTGGTACCTT
 CTGGAGAAGA GCAGAGATAC ACGTGCCATG TGCAGCACCA GGGGCTGCTG
 GAGCCCCTCA CCCTGAGATG GG*  
>DL;IPD:MHC02117
IPD:MHC02117 Mamu-B11L*01:04 822 bases
 GCTCCCACTC CATGAGGTAT TTCCACACCG CCGTGTCCCG GCCCGACCGC
 GGGGAGCCCC GCTTCATCTC CGTGGGTTAC GTGGATGACA CGCAGTTCGT
 GCGGTTCGAC AGCAACGCCG CGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGATAGAGCA GGAGGGACCG GAGTATTGGG ACCGGGAGAC ACAGAAAGCC
 AAGGCCCACG CACAGGTTTT CCGAGTGAAC CTGCGCACCG CGCTTCGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC CTTCCAGAGG ATGCATGGCT
 GCGACCTGGG GCCAGACGGG CGCCTCCTCC GCGGGTATCA CCAGTTAGCC
 TATGATGGCA AGGATTACAT CGCCCTGAAC GGGGACCTGA GCTCCTGGAG
 CGCCGCGGAT ATGGCGGCTC AGGTCACACA GCGCAAGTGG GAGGCGGCCG
 GTGAAGCTGA GCAGCGGAGA GCCTACCTGG AGGGCGAGTG CCTGGAGTCG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGTGGATCC
 CCCAAAGACA CACGTGACCC ACCACCCAGT CTCTGACCAT GAGGCCATCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG
 CAGCGGGATG GGGAGGAGCA AACTCAGGAC ACTGAGCTTG TGGAGACCAG
 GCCCGCAGGG AACGGAACCT TCCAGAAATG GGCAGCTGTG GTGGTGCCTT
 CTGGAGAAGA GCAGAGATAC ACGTGCCATG TGCAGCACCA GGGGCTGCTG
 GAGCCCCTCA CCCTGAGATG GG*  
>DL;IPD:MHC02118
IPD:MHC02118 Mamu-B11L*01:05 822 bases
 GCTCCCACTC CATGAGGTAT TTCCACACCG CCGTGTCCCG GCCCGGCCGC
 GGGGAGCCCC GCTTCATCTC CGTGGGTTAC GTGGATGACA CGCAGTTCGT
 GCGGTTCGAC AGCAACGCCG CGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGATAGAGCA GGAGGGACCG GAGTATTGGG ACCGGGAGAC ACAGAAAGCC
 AAGGCCCACG CACAGGTTTT CCGAGTGAAC CTGCGCACCG CGCTTCGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC CTTCCAGAGG ATGCATGGCT
 GCGACCTGGG GCCAGACGGG CGCCTCCTCC GCGGGTATCA CCAGTTAGCC
 TATGATGGCA AGGATTACAT CGCCCTGAAC GGGGACCTGA GCTCCTGGAG
 CGCCGCGGAT ATGGCGGCTC AGGTCACACA GCGCAAGTGG GAGGCGGCCG
 GTGAAGCTGA GCAGCGGAGA GCCTACCTGG AGGGCGAGTG CCTGGAGTCG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGTGGATCC
 CCCAAAGACA CACGTGACCC ACCACCCAGT CTCTGACCAT GAGGCCATCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG
 CAGCGGGATG GGGAGGAGCA AACACAGGAC ACTGAGCTTG TGGAGACCAG
 GCCCGCAGGG AACGGAACCT TCCAGAAATG GGCAGCTGTG GTGGTGCCTT
 CTGGAGAAGA GCAGAGATAC ACGTGCCATG TGCAGCACCA GGGGCTGCTG
 GAGCCCCTCA CCCTGAGATG GG*  
>DL;IPD:MHC02119
IPD:MHC02119 Mamu-B11L*01:06 822 bases
 GCTCCCACTC CATGAGGTAT TTCCACACCG CCGTGTCTCG GCCCGGCCGC
 GGGGAGCCCC GCTTCATCTC CGTGGGTTAC GTGGATGACA CGCAGTTCGT
 GCGGTTCGAC AGCAACGCCG CGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGATAGAGCA GGAGGGGCCG GAGTATTGGG ACCGGGAGAC ACAGAAAGCC
 AAGGCCCACG CACAGGTTTT CCGAGTGAAC CTGCGCACCG CGCTTCGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC TGTCCAGAGG ATGCATGGCT
 GCGACCTGGG GCCTGACGGG CGCCTCCTCC GCGGGTATCA CCAGTTAGCC
 TATGATGGCA AGGATTACAT CGCCCTGAAC GGGGACCTGA GCTCCTGGAG
 CGCCGCGGAT ATGGCGGCTC AGGTCACACA GCGCAAGTGG GAGGCGGCCC
 GTGCGGCGGA GCGGCAGAGA GCCTACCTGG AGGGCGAGTG CCTGGAGTCG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGTGGATCC
 CCCAAAGACA CACGTCACCC ACCACCTCGT CTCTGACCAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG TGGAGATCAC ACTGACCTGG
 CAGCGAGATG AGAAGGAGCA AACTCAGGAC ACTGAGCTTG TGGAGACCAG
 GCCAGCAGGG GACAGAACCT TCCAGAAATG GGCAGCTGTG GTGGTACCTT
 CTGGAGAAGA GCAGAGATAC ATGTGCCATG TGCAGCACCA GGGGCTGCTG
 GAGCCCCTCA CCCTGAGATG GG*  
>DL;IPD:MHC02120
IPD:MHC02120 Mamu-B11L*01:07 822 bases
 GCTCCCACTC CATGAGGTAT TTCCACACCG CCGTGTCTCG GCCCGGCCGC
 GGGGAGCCCC GCTTCATCTC CGTGGGTTAC GTGGATGACA CGCAGTTCGT
 GCGGTTCGAC AGCAACGCCG CGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGATAGAGCA GGAGGGGCCG GAGTATTGGG ACCGGGAGAC ACAGAAAGCC
 AAGGCCCACG CACAGGTTTT CCGAGTGAAC CTGCGCACCG CGCTTCGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC TGTCCAGAGG ATGCATGGCT
 GCGACCTGGG GCCTGACGGG CGCCTCCTCC GCGGGTATCA CCAGTTAGCC
 TATGATGGCA AGGATTACAT CGCCCTGAAC GGGGACCTGA GCTCCTGGAG
 CGCCGCGGAT ATGGCGGCTC AGGTCACACA GCGCAAGTGG GAGGCGGCCG
 GTGAAGCTGA GCAGCGGAGA GCCTACCTGG AGGGCGAGTG CCTGGAGTCG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGTGGATCC
 CCCAAAGACA CACGTGACCC ACCACCCAGT CTCTGACCAT GAGGCCATCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG
 CAGCGGGATG GGGAGGAGCA AACATAGGAC ACTGAGCTTG TGGAGACCAG
 GCCCGCAGGG AACGGAACCT TCCAGAAATG GGCAGCTGTG GTGGTGCCTT
 CTGGAGAAGA GCAGAGATAC ACGTGCCATG TGCAGCACCA GGGGCTGCTG
 GAGCCCCTCA CCCTGAGATG GG*  
>DL;IPD:MHC02121
IPD:MHC02121 Mamu-B11L*01:08 822 bases
 GCTCCCACTC CATGAGGTAT TTCCACACCG CCGTGTCCCG GCCCGGCCGC
 GGGGAGCCCC GCTTCATCTC CGTGGGTTAC GTGGATGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCG CGAGTCCGAG GATGGAGCCA CGGGCGCCGT
 GGATAGAGCA GGAGGGACCG GAGTATTGGG ACCGGGAGAC ACAGAAAGCC
 AAGGCCCACG CACAGGTTTT CCGAGTGAAC CTGTGCACCG CGCTTCGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC CTTCCAGAGG ATGCATGGCT
 GCGACCTGGG GCCAGACGGG CGCCTCCTCC GCGGGTATCA CCAGTTAGCC
 TATGATGGCA AGGATTACAT CGCCCTGAAC GGGGACCTGA GCTCCTGGAG
 CGCCGCGGAT ATGGCGGCTC AGGTCACACA GCGCAAGTGG GAGGCGGCCG
 GTGAAGCTGA GCAGCGGAGA GCCTACCTGG AGGGCGAGTG CCTGGAGTCG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACACTGCAGC GCGTGGATCC
 CCCAAAGACA CACGTGACCC ACCACCCAGT CTCTGACCAT GAGGCCATCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG
 CAGCGGGATG GGGAGGAGCA AACTCAGGAC ACTGAGCTTG TGGAGACCAG
 GCTCGCAGGG AACGGAACCT TCCAGAAATG GGCAGCTGTG GTGGTGCCTT
 CTGGAGAAGA GCAGAGATAC ACGTGCCATG TGCAGCACCA GGGGCTGCTG
 GAGCCCCTCA CCCTGAGATG GG*  
>DL;IPD:MHC02512
IPD:MHC02512 Mamu-B11L*01:09 822 bases
 GCTCCCACTC CATGAGGTAT TTCCACACCG CCGTGTCCCG GCCCGGCCGC
 GGGGAGCCCC GCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCG CGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGATAGAGCA GGAGGGGCCG GAGTATTGGG ACCGGGAGAC ACAGAAAGCC
 AAGGCCCACG CACAGGTTTT CCGAGTGAAC CTGCGCACCG CGCTTCGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC CTTCCAGAGG ATGCATGGCT
 GCGACCTGGG GCCTGACGGG CGCCTCCTCC GCGGGTATCA CCAGTTAGCC
 TATGATGGCA AGGATTACAT CGCCCTGAAT GGAGACCTGA GCTCCTGGAG
 CGCCGCGGAT ATGGCGGCTC AGGTCACACA GCGCAAGTGG GAGGCGGCCC
 GTGAAGCTGA GCAGCGGAGA GCCTACCTGG AGGGCGAGTG CCTAGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGTGGATCC
 CCCAAAGACA CACGTGACCC ACCACCCCGT CTCTGACCAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG
 CAGCGAGATG GGGAGGAGCA AACTCAGGAC ACTGAGCTTG TGGAGACCAG
 GCCAGCAGGG GACAGAACCT TCCAGAAATG GGCAGCTGTG GTGGTACCTT
 CTGGAGAAGA GCAGAGATAC ATGTGCCATG TGCAGCACCA GGGGCTGCTG
 GAGCCCCTCA CCCTGAGATG GG*  
>DL;IPD:MHC02523
IPD:MHC02523 Mamu-B11L*01:10 823 bases
 GCTCCCACTC CATGAGGTAT TTCCACACCG CCGTGTCCCG GCCCGGCCGC
 GGGGAGCCCC GCTTCATCGC CGTGGGTTAT GTGGACGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCG CGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGATAGAGCA GGAGGGGCCG GAGTATTGGG ACCGGGAGAC ACAGAAAGCC
 AAGGCCCACG CACAGGTTTT CCGAGTGAAC CTGCGCACCG CGCTTCGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC CTTCCAGAGG ATGCATGGCT
 GCGACCTGGG GCCTGACGGG CGCCTCCTCC GCGGGTATCA CCAGTTAGCC
 TATGATGGCA AGGATTACAT CGCCCTGAAC GGGGACCTGA GCTCCTGGAG
 CGCCGCGGAT ATGGCGGCTC AGGTCACACA GCGCAAGTGG GAGGCGGCCC
 GTGAAGCTGA GCAGCGGAGA GCCTACCTGG AGGGCGAGTG CCTGGAGTCG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GAGTGGATCC
 CCCAAAGACA CACGTGACCC ACCACCCTGT CTCTGACCAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG
 CAGCGAGATG GGGAGGAGCA AACTCAGGAC ACTGAGCTTG TGGAGACCAG
 GCCAGCAGGG GACAGAACCT TCCAGAAATG GGCAGCTGTG GTGGTACCTT
 CTGGAGAAGA GCAGAGATAC ATGTGCCATG TGCAGCACCA GGGGCTGCTG
 GAGCTCCCTC ACCCTGAGAT GGG*  
>DL;IPD:MHC02627
IPD:MHC02627 Mamu-B11L*01:11 1089 bases
 ATGGCGCCTC GAGCCCTCCT CCTGCTGCTC TCGGGGGCCC TGGCCCTGAC
 CGAGACCTGG GCCGGCTCCC ACTCCATGAG GTATTTCCAC ACCGCCGTGT
 CTCGGCCCGG CCGCGGGGAG CCCCGCTTCA TCTCCGTGGG TTACGTGGAT
 GACACGCAGT TCGTGCGGTT CGACAGCAAC GCCGCGAGTC CGAGGATGGA
 GCCGCGGGCG CCGTGGATAG AGCAGGAGGG GCCGGAGTAT TGGGACCGGG
 AGACACAGAA AGCCAAGGCC CACGCACAGG TTTTCCGAGT GAACCTGCGC
 ACCGCGCTTC GCTACTACAA CCCGAGCGAG GCCGGGTCTC ACACTGTCCA
 GAGGATGCAT GGCTGCGACC TGGGGCCTGA CGGGCGCCTC CTCCGCGGGT
 ATCACCAGTT AGCCTATGAT GGCAAGGATT ACATCGCCCT GAACGGGGAC
 CTGAGCTCCT GGACCGCCGC GGATATGGCG GCTCAGGTCA CACAGCGCAA
 GTGGGAGGCG GCCCGTGAAG CTGAACAGCG GAGAGCCTAC CTGGAGGGCG
 AGTGCCTGGA GTCGCTCCGC AGATACCTGG AGAACGGGAA GGAGACGCTG
 CAGCGCGTGG ATCCCCCAAA GACACACGTC ACCCACCACC TCGTCTCTGA
 CCATGAGGCC ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGTGGAGA
 TCACACTGAC CTGGCAGCGA GATGAGAAGG AGCAAACTCA GGACACTGAG
 CTTGTGGAGA CCAGGCCAGC AGGGGACAGA ACCTTCCAGA AATGGGCAGC
 TGTGGTGGTA CCTTCTGGAG AAGAGCAGAG ATACATGTGC CATGTGCAGC
 ACCAGGGGCT GCTGGAGCCC CTCACCCTGA GATGGGAGCG GGCTTCCCAG
 CCCTCCATCC CCATCGTGGG CATCGTTGCT GGCCTGGCTG TCTTAGGAAC
 TGTGGTCACC GTAGCTGTGG TTGCTGCTGT GATGTGGTGG ACAGAGAGCT
 CAGGTGGAAA AAGCCGGAGC TACTGGAGCA GCAGTGCCCA GGGCTCTGAT
 CAGGACTCTG ATGAGTCTCT CATGGCCTGT AAAGCCTGA* 
>DL;IPD:MHC04032
IPD:MHC04032 Mamu-B11L*01:12 822 bases
 GCTCCCACTC CATGAGGTAT TTCCACACCG CCGTGTCCCG GCCCGGCCGC
 GGGGAGCCCC GCTTCATCTC CGTGGGTTAC GTGGATGACA CGCAGTTCGT
 GCGGTTCGAC AGCAACGCCG CGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGATAGAGCA GGAGGGACCA GAGTATTGGG ACCGGGAGAC ACAGAAAGCC
 AAGGCCCACG CACAGGTTTT CCGAGTGAAC CTGCGCACAG CGCTTCGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC CTTCCAGAGG ATGCATGGCT
 GCGACCTGGG GCCTGACGGG CGCCTCCTCC GCGGGTATCA CCAGTTAGCC
 TATGATGGCA AGGATTACAT CGCCCTGAAC GGGGACCTGA GCTCCTGGAG
 CGCCGCGGAT ATGGCGGCTC AGGTCACACA GCGCAAGTGG GAGGCGGCCC
 GTGAAGCTGA GCAGCGGAGA GCCTACCTGG AGGGCGAGTG CCTGGAGTCG
 CTCCGCAGAT ATCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGTGGATCC
 CCCAAAGACA CACGTGACCC ACCACCCAGT CTCTGACCAT GAGGCCATCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG
 CAGCGGGATG GGGAGGAGCA AACTCAGGAC ACTGAGCTTG TGGAGACCAG
 GCCCGCAGGG AACGGAACCT TCCAGAAATG GGCAGCTGTG GTGGTGCCTT
 CTGGAGAAGA GCAGAGATAC ACGTGCCATG TGCAGCACCA GGGGCTGCTG
 GAGCCCCTCA CCCTGAGATG GG*  
