>DL;IPD:MHC02590
IPD:MHC02590 Mamu-I*01:01:01 352 bases
 LLSGALALTE TWAGSHSLRY FGTTVSRPGR GEPRFIAVGY VDDTQFVRFD
 SDAESPRMEP RAPWMEQEGP EYWEEETRIA KARAQTERGN LRTALRYYNQ
 SEAGSHTLQK MCGCDLGPDG RLLRGYYQSA YDGRDYIALN EDLRSWTAAG
 EAAQNTQRKW EAAGEAEQRR AYLEGRCVEW LRRYLEKGKE TLQRADPPKT
 HVTHHPVSDH EATLRCWALG FYPAEITLTW QRDGEEQTQD TELVETRPGG
 DGNFQKWAAV VVPSGEEQRY TCHVQHEGLP EPLTLRWEPS SQSTIPIMGI
 VAGLAVLAVV VTGAVVAAVM WRRKSSGGKG GSYSQAASSN SAQGSDVSLT
 AX*    
>DL;IPD:MHC02509
IPD:MHC02509 Mamu-I*01:01:02 360 bases
 MAPGTLLLLL SGALALTETW AGSHSLRYFG TTVSRPGRGE PRFIAVGYVD
 DTQFVRFDSD AESPRMEPRA PWMEQEGPEY WEEETRIAKA RAQTERGNLR
 TALRYYNQSE AGSHTLQKMC GCDLGPDGRL LRGYYQSAYD GRDYIALNED
 LRSWTAAGEA AQNTQRKWEA AGEAEQRRAY LEGRCVEWLR RYLEKGKETL
 QRADPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEEQTQDTE
 LVETRPGGDG NFQKWAAVVV PSGEEQRYTC HVQHEGLPEP LTLRWEPSSQ
 STIPIMGIVA GLAVLAVVVT GAVVAAVMWR RKSSGGKGGS YSQAASSNSA
 QGSDVSLTAX *   
>DL;IPD:MHC02495
IPD:MHC02495 Mamu-I*01:02:01 363 bases
 MRVMAPGTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGTFQKWGA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC02591
IPD:MHC02591 Mamu-I*01:02:02 352 bases
 LLSGALALTE TWAGSHSLRY FGTTVSRPGR GEPRFIAVGY VDDTQFVRFD
 SDAESPRMEP RAPWMEQEGP EYWEEETRIA KARAQTERGN LRTALRYYNQ
 SEGGSHTLQK MCGCDLGPDG RLLRGYYQSA YDGRDYIALN EDLRSWTAAG
 EAAQNTQRKW EAAGEAEQRR AYLEGRCVEW LRRYLEKGKE TLQRADPPKT
 HVTHHPVSDH EATLRCWALG FYPAEITLTW QRDGEEQTQD TELVETRPGG
 DGTFQKWGAV VVPSGEEQRY TCHVQHEGLP EPLTLRWEPS SQSTIPIMGI
 VAGLAVLAVV VTGAVVAAVM WRRKSSGGKG GSYSQAASSN SAQGSDVSLT
 AX*    
>DL;IPD:MHC02505
IPD:MHC02505 Mamu-I*01:02:03 360 bases
 MAPGTLLLLL SGALALTETW AGSHSLRYFG TTVSRPGRGE PRFIAVGYVD
 DTQFVRFDSD AESPRMEPRA PWMEQEGPEY WEEETRIAKA RAQTERGNLR
 TALRYYNQSE GGSHTLQKMC GCDLGPDGRL LRGYYQSAYD GRDYIALNED
 LRSWTAAGEA AQNTQRKWEA AGEAEQRRAY LEGRCVEWLR RYLEKGKETL
 QRADPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEEQTQDTE
 LVETRPGGDG TFQKWGAVVV PSGEEQRYTC HVQHEGLPEP LTLRWEPSSQ
 STIPIMGIVA GLAVLAVVVT GAVVAAVMWR RKSSGGKGGS YSQAASSNSA
 QGSDVSLTAX *   
>DL;IPD:MHC00601
IPD:MHC00601 Mamu-I*01:04 351 bases
 HSGALALTET WAGSHSLRYF GTTVSRPGRG EPRFIAVGYV DDTQFVRFDS
 DAESPRMEPR APWMEQEGPE YWEEETRIAK ARAQTERGNL RTALRYYNQS
 EAGSHTLQKM CGCDLGPDGR LLRGYYQSAY DGRDYIALNE DLRSWTAAGE
 AAQNTQRKWE AAGEAEQRRA YLEGRCVEWL RRYLEKGKET LQRADPPKTH
 VTHHPVSDHE ATLRCWALGF YPAEITLTWQ RDGEEQTQDT ELVETRPGGD
 GNFQKWAAVV VPSGEEQRYT CHVQHEGLPE PLTLRWEPSS QSTIPIMGIV
 AGLAVLAVVV TGAVVAAVMW RRKSSGGKGG SYSQAASSDS AQGSDVSLTA
 X*    
>DL;IPD:MHC02484
IPD:MHC02484 Mamu-I*01:05 363 bases
 MRVMAPGTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYISL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL LEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC01264
IPD:MHC01264 Mamu-I*01:06:01 363 bases
 MRVMAPGTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC02626
IPD:MHC02626 Mamu-I*01:06:02 363 bases
 MRVMAPGTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC01982
IPD:MHC01982 Mamu-I*01:06:03 360 bases
 MAPGTLLLLL SGALALTETW AGSHSLRYFG TTVSRPGRGE PRFIAVGYVD
 DTQFVRFDSD AESPRMEPRA PWMEQEGPEY WEEETRIAKA RAQTERGNLR
 TALRYYNQSE GGSHTLQKMC GCDLGPDGRL LRGYYQSAYD GRDYIALNED
 LRSWTAAGEA AQNTQRKWEA AGEAEQRRAY LEGRCVEWLR RYLEKGKETL
 QRADPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEEQTQDTE
 LVETRPGGDG NFQKWAAVVV PSGEEQRYTC HVQHEGLPEP LTLRWEPSSQ
 STIPIMGIVA GLAVLAVVVT GAVVAAVMWR RKSSGGKGGS YSQAASSNSA
 QGSDVSLTAX *   
>DL;IPD:MHC02151
IPD:MHC02151 Mamu-I*01:06:04 334 bases
 MAPGTLLLLL SGALALTETW AGSHSLRYFG TTVSRPGRGE PRFIAVGYVD
 DTQFVRFDSD AESPRMEPRA PWMEQEGPEY WEEETRIAKA RAQTERGNLR
 TALRYYNQSE GGSHTLQKMC GCDLGPDGRL LRGYYQSAYD GRDYIALNED
 LRSWTAAGEA AQNTQRKWEA AGEAEQRRAY LEGRCVEWLR RYLEKGKETL
 QRADPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEEQTQDTE
 LVETRPGGDG NFQKWAAVVV PSGEEQRYTC HVQHEGLPEP LTLRWEPSSQ
 STIPIMGIVA GLAVLAVVVT GAVVAAVMWR RKSS* 
>DL;IPD:MHC02503
IPD:MHC02503 Mamu-I*01:06:05 360 bases
 MAPGTLLLLL SGALALTETW AGSHSLRYFG TTVSRPGRGE PRFIAVGYVD
 DTQFVRFDSD AESPRMEPRA PWMEQEGPEY WEEETRIAKA RAQTERGNLR
 TALRYYNQSE GGSHTLQKMC GCDLGPDGRL LRGYYQSAYD GRDYIALNED
 LRSWTAAGEA AQNTQRKWEA AGEAEQRRAY LEGRCVEWLR RYLEKGKETL
 QRADPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEEQTQDTE
 LVETRPGGDG NFQKWAAVVV PSGEEQRYTC HVQHEGLPEP LTLRWEPSSQ
 STIPIMGIVA GLAVLAVVVT GAVVAAVMWR RKSSGGKGGS YSQAASSNSA
 QGSDVSLTAX *   
>DL;IPD:MHC02504
IPD:MHC02504 Mamu-I*01:06:06 360 bases
 MAPGTLLLLL SGALALTETW AGSHSLRYFG TTVSRPGRGE PRFIAVGYVD
 DTQFVRFDSD AESPRMEPRA PWMEQEGPEY WEEETRIAKA RAQTERGNLR
 TALRYYNQSE GGSHTLQKMC GCDLGPDGRL LRGYYQSAYD GRDYIALNED
 LRSWTAAGEA AQNTQRKWEA AGEAEQRRAY LEGRCVEWLR RYLEKGKETL
 QRADPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEEQTQDTE
 LVETRPGGDG NFQKWAAVVV PSGEEQRYTC HVQHEGLPEP LTLRWEPSSQ
 STIPIMGIVA GLAVLAVVVT GAVVAAVMWR RKSSGGKGGS YSQAASSNSA
 QGSDVSLTAX *   
>DL;IPD:MHC02902
IPD:MHC02902 Mamu-I*01:06:07 363 bases
 MRVMAPGTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC02903
IPD:MHC02903 Mamu-I*01:06:08 360 bases
 MAPRTLLLLL SGALALTETW AGSHSLRYFG TTVSRPGRGE PRFIAVGYVD
 DTQFVRFDSD AESPRMEPRA PWMEQEGPEY WEEETRIAKA RAQTERGNLR
 TALRYYNQSE GGSHTLQKMC GCDLGPDGRL LRGYYQSAYD GRDYIALNED
 LRSWTAAGEA AQNTQRKWEA AGEAEQRRAY LEGRCVEWLR RYLEKGKETL
 QRADPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEEQTQDTE
 LVETRPGGDG NFQKWAAVVV PSGEEQRYTC HVQHEGLPEP LTLRWEPSSQ
 STIPIMGIVA GLAVLAVVVT GAVVAAVMWR RKSSGGKGGS YSQAASSNSA
 QGSDVSLTAX *   
>DL;IPD:MHC03574
IPD:MHC03574 Mamu-I*01:06:09 215 bases
 LSGALALTET WAGSHSLRYF GTTVSRPGRG EPRFIAVGYV DDTQFVRFDS
 DAESPRMEPR APWMEQEGPE YWEEETRIAK ARAQTERGNL RTALRYYNQS
 EGGSHTLQKM CGCDLGPDGR LLRGYYQSAY DGRDYIALNE DLRSWTAAGE
 AAQNTQRKWE AAGEAEQRRA YLEGRCVEWL RRYLEKGKET LQRADPPKTH
 VTHHPVSDHE ATLRC*   
>DL;IPD:MHC03575
IPD:MHC03575 Mamu-I*01:06:10 215 bases
 LSGALALTET WAGSHSLRYF GTTVSRPGRG EPRFIAVGYV DDTQFVRFDS
 DAESPRMEPR APWMEQEGPE YWEEETRIAK ARAQTERGNL RTALRYYNQS
 EGGSHTLQKM CGCDLGPDGR LLRGYYQSAY DGRDYIALNE DLRSWTAAGE
 AAQNTQRKWE AAGEAEQRRA YLEGRCVEWL RRYLEKGKET LQRADPPKTH
 VTHHPVSDHE ATLRC*   
>DL;IPD:MHC03742
IPD:MHC03742 Mamu-I*01:06:11 273 bases
 SHSLRYFGTT VSRPGRGEPR FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 MEQEGPEYWE EETRIAKARA QTERGNLRTA LRYYNQSEGG SHTLQKMCGC
 DLGPDGRLLR GYYQSAYDGR DYIALNEDLR SWTAAGEAAQ NTQRKWEAAG
 EAEQRRAYLE GRCVEWLRRY LEKGKETLQR ADPPKTHVTH HPVSDHEATL
 RCWALGFYPA EITLTWQRDG EEQTQDTELV ETRPGGDGNF QKWAAVVVPS
 GEEQRYTCHV QHEGLPEPLT LRW*  
>DL;IPD:MHC00602
IPD:MHC00602 Mamu-I*01:07 359 bases
 VMAPGTLLLL LSGALALTET WAGSHSLRYF GTTVSRPGRG EPRFIAVGYV
 DDTQFVRFDS DAESPRMEPR APWMEQEGPE YWEEETRIAK ARAQTERGNL
 RTALRYYNQS EGGSHTLQKM CGCDLGPDGR LLRGYYQSAY DGRDYIALNE
 DLRSWTAAGE AAQNTQRKWE AAGEAEQRRA YLEGRCVEWL RRYLEKGKET
 LQRADPPKTH VTHHPVSDHE ATLRCWALGF YPAEITLTWQ RDGEDQTQDT
 ELVETRPGGD GNFQKWAAVV VPSGEEQRYT CHVQHEGLPE PLTLRWEPSS
 QSTIPIMGIV AGLAVLAVVV TGAVVAAVMW RRKSSGGKGG SYSQAASSDS
 AQGSDVSLT*    
>DL;IPD:MHC02508
IPD:MHC02508 Mamu-I*01:08 363 bases
 MRVMAPGTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC02628
IPD:MHC02628 Mamu-I*01:09 363 bases
 MRVMAPRTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC02485
IPD:MHC02485 Mamu-I*01:16 360 bases
 MAPGTLLLLL SGALALTETW AGSHSLRYFG TTVSRPGRGE PRFIAVGYVD
 DTQFVRFDSD AESPRMEPRA PWMEQEGPEY WEEETRIAKA RAQTERGNLR
 TALRYYNQSE GGSHTLQKMC GCDLGPDGRL LRGYYQSAYD GRDYIALNED
 LRSWTAAGEA AQNTQRKWEA AGEAEQRRAY LEGRCVEWLH RYLEKGKETL
 QRADPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEEQTQDTE
 LVETRPGGDG NFQKWAAVVV PSGEEQRYTC HVQHEGLLEP LTLRWEPSSQ
 STIPIMGIVA GLAVLAVVVT GAVVAAVMWR RKSSGGKGGS YSQAASSNSA
 QGSDVSLTAX *   
>DL;IPD:MHC01263
IPD:MHC01263 Mamu-I*01:18 363 bases
 MRVMAPGTLL LLLSGALALT ETRAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC01980
IPD:MHC01980 Mamu-I*01:19 363 bases
 MRVMAPGTLL LLLSAALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC01981
IPD:MHC01981 Mamu-I*01:20:01 363 bases
 MRVMAPGTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC02589
IPD:MHC02589 Mamu-I*01:20:02 360 bases
 MAPRTLLLLL SGALALTETW AGSHSLRYFG TTVSRPGRGE PRFIAVGYVD
 DTQFVRFDSD AESPRMEPRA PWMEQEGPEY WEEETRIAKA RAQTERGNLR
 TALRYYNQSE GGSHTLQKMC GCDLGPDGRL LRGYYQSAYD GRDYIALNED
 LRSWTAAGEA AQNTQRKWEA AGEAEQRRAY LEGRCVEWLR RYLEKGKETL
 QRADPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEEQTQDTE
 LVETRPGGDG NFQKWAAVVV PSGEEQRYTC HVQHEGLPEP LTLRWEPSSQ
 STIPIVGIVA GLAVLAVVVT GAVVAAVMWR RKSSGGKGGS YSQAASSNSA
 QGSDVSLTAX *   
>DL;IPD:MHC03346
IPD:MHC03346 Mamu-I*01:21 351 bases
 TLLLLLSGAL ALTETWAGSH SLRYFGTTVS RPGRGEPRFI AVGYVDDTQF
 VRFDSDAESP RMEPRAPWME QEGPEYWEEE TRIAKARAQT ERGNLRTALR
 YYNQSEAGSH TLQKMCGCDL GPDGRLLRGY YQSAYDGRDY IALNEDLRSW
 TAAGEAAQNT QRKWEAAGEA EQRRAYLEGR CVEWLRRYLE KGKETLQRAD
 PPKTHVTHHP VSDHEATLRC WALGFYPAEI TLTWQRDGEE QTQDTELVET
 RPGGDGNFQK WAAVVVPSGE EQRYTCHVQH EGLPEPLTLR WEPSSQSTIP
 IMGIVAGLAV LAVVVTGAVV AAVMWRRKSS GGKGGSYSQA APSNSAQGSD
 V*    
>DL;IPD:MHC03541
IPD:MHC03541 Mamu-I*01:22 360 bases
 MAPGTLLLLL SGALALTETW AGSHSLRYFG TTVSRPGRGE PRFIAVGYVD
 DTQFVRFDGD AESPRMEPRA PWMEQEGPEY WEEETRIAKA RAQTERGNLR
 TALRYYNQSE AGSHTLQKMC GCDLGPDGRL LRGYYQSAYD GRDYIALNED
 LRSWTAAGEA AQNTQRKWEA AGEAEQRRAY LEGRCVEWLR RYLEKGKETL
 QRADPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEEQTQDTE
 LVETRPGGDG NFQKWAAVVV PSGEEQRYTC HVQHEGLPEP LTLRWEPSSQ
 STIPIMGIVA GLAVLAVVVT GAVVAAVMWR RKSSGGKGGS YSQAAFSNSA
 QGSDVSLTAX *   
>DL;IPD:MHC03573
IPD:MHC03573 Mamu-I*01:23 360 bases
 MAPGTLLLLL SGALALTETW AGSHSLRYFG TTVSRPGRGE PRFIAVGYVD
 DTQFVRFDSD AESPRMEPRA PWMEQEGPEY WEEETRIAKA RAQTERGNLR
 TALRYYNQSE AGSHTLQKMC GCDLGPDGRL LRGYYQSAYD GRDYIALNED
 LRSWTAAGEA AQNTQRKWEA AGEAEQRRAY LEGRCVEWLR RYLEKGKETL
 QRADPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEEQTQDTE
 LVETRPGGDG NFQKWAAVVV PSGEEQRYTC HVQHEGLPEP LTLRWEPSSQ
 STIPIMGIVA GLAVLAVVVT GAVVAAVMWR RKSSGGKGGS YSQAASSDSA
 QGSDVSLTAX *   
>DL;IPD:MHC03576
IPD:MHC03576 Mamu-I*01:24 360 bases
 MAPGTLLLLL SGALALTETR AGSHSLRYFG TTVSRPGRGE PRFIAVGYVD
 DTQFVRFDSD AESPRMEPRA PWMEQEGPEY WEEETRIAKA RAQTERGNLR
 TALRYYNQSE GGSHTLQKMC GCDLGPDGRL LRGYYQSAYD GRDYIALNED
 LRSWTAAGEA AQNTQRKWEA AGEAEQRRAY LEGRCVEWLR RYLEKGKETL
 QRADPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEEQTQDTE
 LVETRPGGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP LTLRWEPSSQ
 STIPIMGIVA GLAVLAVVVT GAVVAAVMWR RKSSGGKGGS YSQAASSNSA
 QGSDVSLTAX *   
>DL;IPD:MHC03591
IPD:MHC03591 Mamu-I*01:25 363 bases
 MRVMAPGTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEAGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPLSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC03670
IPD:MHC03670 Mamu-I*01:26 363 bases
 MRVMAPGTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIRIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
