>DL;IPD:MHC00365
IPD:MHC00365 Mamu-DPB1*01:01 259 bases
 MMVLQVSAAP RTVGLMALLM VLLTSVVQGR ATPENYLYQG RQECYAFNGT
 QRFLERYIYN REEYARFDSD VGEFRAVTEL GRPAVEYWNS QKDRLEEKRA
 VVDTMCRHNY ELDEAVTLQR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETTGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLITC GVGIFMHRRS
 KKVQRGSVX*    
>DL;IPD:MHC04372
IPD:MHC04372 Mamu-DPB1*01:02 85 bases
 NYLYQGRQEC YAFNGTQRFL ERHIYNREGY ARFDSDVGEF RAVTELGRPA
 VEYWSSQKDL LEEMRAVVDT MCRYNYELDE AVTLQ* 
>DL;IPD:MHC04373
IPD:MHC04373 Mamu-DPB1*01:03 85 bases
 NYLYQGRQEC YAFNGTQRFL ERHIYNREEY ARFDSDVGEF RAVTELGRPA
 VEYWNSQKDR LEEKRAVVDT VCGHNYELDE AVTLQ* 
>DL;IPD:MHC04374
IPD:MHC04374 Mamu-DPB1*01:04 85 bases
 NYLYQGRQEC YAFNGTQRFL ERHIYNREEY ARFDSDVGEF RAVTGLGRPA
 VEYWNSQKDI LEENRAVVDR VCRHNYELDE AVTLQ* 
>DL;IPD:MHC04375
IPD:MHC04375 Mamu-DPB1*01:05 85 bases
 SYLYQGRQEC YAFNGTQRFL ERYIYNQEEY ARFDSDVGEF RAVTELGRPA
 VEYWNSQKDR LEEKRAVVDT MCRHNYELDE AVTLQ* 
>DL;IPD:MHC04377
IPD:MHC04377 Mamu-DPB1*01:06 85 bases
 SYLYQGRQEC YAFNGTQRFL ERYIYNREEY ARFDSDVGEF RAVTELGRPA
 VEYWNSQKDR LEEKRAVVDT MCRHNYELDE AVTLQ* 
>DL;IPD:MHC04387
IPD:MHC04387 Mamu-DPB1*01:07 85 bases
 NYLYQGRQEC YAFNGTQRFL ERYIYNREEY ARFDSDVGEF RAVTELGRPA
 VEYWNSQKDR LEERRAVVDT MCRHNYELDE AVTLQ* 
>DL;IPD:MHC05124
IPD:MHC05124 Mamu-DPB1*01:08 87 bases
 NYLYQVRQEC YAFNGTQRFL ERYIYNREEY ARFDSDVGEF RAVTELGRPA
 VEYWNSQKDR LEEKRAVVDT VCRHNYELDE AVTLQRR* 
>DL;IPD:MHC00374
IPD:MHC00374 Mamu-DPB1*02:01 259 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVRGR ATPENYLYQG RQECYAINGT
 QRFLERHIYN REEFMRFDSD AGEYRAVTEM GRPSAEYWNS QKDRLEEKRA
 EVDRVCRHNY EGHEAVTLRR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETAGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VMVEWKAQSD SARSKTLTGA GGFVLGLITC GVGIFMHRRS
 KKVQRGSVX*    
>DL;IPD:MHC03805
IPD:MHC03805 Mamu-DPB1*02:02 259 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVRGR ATPENYLYQG RQECYAINGT
 QRFLERHIYN REEFMRFDSD AGEYRAVTEM GRPTAEYWNS QKDRLEEKRA
 EVDRVCRHNY EGHEAVTLRR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETAGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VMVEWKAQSD SARSKTLTGA GGFVLGLITC GVGIFMHRRS
 KKVQRGSVX*    
>DL;IPD:MHC05122
IPD:MHC05122 Mamu-DPB1*02:03 87 bases
 NYLYQGRQEC YAINGTQRFL ERHIYNREEF MRFDSDAGEY RAVTEMGRPT
 AEYCNSQKDF LEEKRAEVDR VCRHNYEGHE AVTLRRR* 
>DL;IPD:MHC00375
IPD:MHC00375 Mamu-DPB1*03:01 85 bases
 NYLYQGRQEC YAINGTQRFL ERHIYNREEF MRFDSDVGEY RAVTEMGRPT
 AEYCNSQKDK LEEMRAVADT VCRHNYEVNE AVTLQ* 
>DL;IPD:MHC01999
IPD:MHC01999 Mamu-DPB1*03:02 259 bases
 MMVLQVSVVP GTVALTALLM VLLTSVVRGR ATPDNYLYQG RQECYAINGT
 QRFLERHIYN REEFMRFDSD VGEYRAVTEM GRPTAEYCNS QKDKLEEMRA
 VADTVCRHNY EVNEAVTLQR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETAGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTMEWKAQSD SARSKTLTGA GGFVLGLIIC GVGIFMHRRS
 KKVQRGSVX*    
>DL;IPD:MHC03585
IPD:MHC03585 Mamu-DPB1*03:03 88 bases
 ENYLYQGRQE CYAINGTQRF LERHIYNREE FMRFDSDVGE YRAVTEMGRP
 TAEYCNSQKD KLEEMRAVAD RMCRHNYEVN EAVTLQRR* 
>DL;IPD:MHC00373
IPD:MHC00373 Mamu-DPB1*04:01 259 bases
 MMVLQVSGTP QTVGLMALLM VLLTSVVQGR ATPENYLYQV RQECYAFNGT
 QRYLNRQIYN REEFVRFDSD VGEYRAVTEL GRPTAEYWNS QKDILEENRA
 VVDRVCRHNY ELDEAVTLQR RVQPRVNVSP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETTGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLITC GVGIFMHRRS
 KKVQRGSAX*    
>DL;IPD:MHC00364
IPD:MHC00364 Mamu-DPB1*05:01 259 bases
 MMVLQVSGTP QTVGLMALLM VLLTSVVQGR ATPENYLYQV RQECYAFNGT
 QRFLERYIYN REEYARFDSD VGEFRAVTEL GRPTAEYWNS QKDRLEERRA
 VVDTMCRHNY ELDEAVTLQR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETAGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VMVEWKAQSD SARSKTLTGA GGFVLGLITC GVGIFMHRRS
 KKVQRGSVX*    
>DL;IPD:MHC00363
IPD:MHC00363 Mamu-DPB1*06:01 259 bases
 MMVLQVSAAP RTVGLMALLM VLLTSVVQGR ATPENYLYQV RQECYAFNGT
 QRYLERYIYN REEFVRFDSD VGEFRAVTEL GRPDAEYWNS QKDILEEKQA
 VAGTSCRHDY ELDEAVTLQR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSIQIRWFL NGQEETDGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTVEWKAQSD SARSKTLTGA GGFMLGLITC GVGIFMHRRS
 KKVQRGSVX*    
>DL;IPD:MHC00369
IPD:MHC00369 Mamu-DPB1*06:02 85 bases
 NYLFQLRQEC YAFNGTQRYL ERYLYNREEF VRFDSDVGEF RAVTELGRPD
 AEYWNSQKDI LEERRAVVDT MCRHNYELDE AVTLQ* 
>DL;IPD:MHC00370
IPD:MHC00370 Mamu-DPB1*06:03 85 bases
 NYLFQLRQEC YAFNGTQRYL ERYLYNREEF VRFDSDVGEF RAVTELGRPD
 AEYWNSQKDI LEEMRAVTDT VCRHNYELDE AVTLQ* 
>DL;IPD:MHC00372
IPD:MHC00372 Mamu-DPB1*06:04 59 bases
 NYLFQERQEC YAFNGTQRYL DRYIYNREEF VRFDSDVGEY RAVTELGRPD
 AEYWNSQKD*    
>DL;IPD:MHC00376
IPD:MHC00376 Mamu-DPB1*06:05 85 bases
 NYVFQGRMEC YAFNGTQRYL NRYIYNREEF VRFDSDVGEF RAVTELGRPD
 AEYWNSQKDI LEEKRAVVDR VCRHNYELDE AVTLQ* 
>DL;IPD:MHC00367
IPD:MHC00367 Mamu-DPB1*07:01 259 bases
 MMVLEVSAAP GTVGLMALLM VLLTSVVQGR ATPENYVFQG RQECYAFNGT
 QRYLERYIYN REEYVRFDSD VGEFRAVTEL GRPDAEYWNS QKDLLEEMRA
 VVDTMCRYNY ELDEAVTLQR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETTGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC GVGIFMHRRR
 KKVQRGSVX*    
>DL;IPD:MHC00368
IPD:MHC00368 Mamu-DPB1*07:02 85 bases
 NYVFQGRQEC YAFNGTQRYL ERYIYNREEY VRFDSDVGEF RAVTELGRPD
 AEYWNSQKDL LEEMRAVVDT MCRYNYELDE AVTLQ* 
>DL;IPD:MHC03804
IPD:MHC03804 Mamu-DPB1*07:03 259 bases
 MMVLEVSAAP GTVGLMALLM VLLTSVVQGR ATPENYVFQG RQECYAFNGT
 QRYLERYIYN REEYARFDSD VGEFRAVTEL GRPDAEYWNS QKDLLEEMRA
 VVDTMCRYNY ELDEAVTLQR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETTGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC GVGIFMHRRR
 KKVQRGSVX*    
>DL;IPD:MHC04376
IPD:MHC04376 Mamu-DPB1*07:04 85 bases
 NYVFQGRQEC YAFNGAQRYL ERYIYNREEY ERFDSDVGEF RAVTELGRPD
 AEYRNSQKDL LEEMRAVVDT MCRYNYELDE AVTLQ* 
>DL;IPD:MHC00362
IPD:MHC00362 Mamu-DPB1*08:01 259 bases
 MMVLQVSAAP RTVGLMALLM VLLTSVVQGR ATPENYVYQG RMECYAFNGT
 QRYLERYIYN REEYARFDSD VGEFRAVTEL GRPDAEYWNS QKDILEEKQA
 VAGTSCRHDY ELDEAVTLQR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSIQIRWFL NGQEETDGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTVEWKAQSD SARSKTLTGA GGFMLGLITC GVGIFMHRRS
 KKVQRGSVX*    
>DL;IPD:MHC00377
IPD:MHC00377 Mamu-DPB1*11:01 85 bases
 NYVFQGRQEC YAFNGTQRYL ERYIYNREEY ARFDSDVGEF RAVTELGRPT
 AEYWNSQKDR LEERRAVVDT MCRHNYELDE AVTLQ* 
>DL;IPD:MHC00366
IPD:MHC00366 Mamu-DPB1*13:01 53 bases
 NYVYQGRQEC YAFNGTQHFL ERYIYNRREY ARFDSVVAKF RAVTELGRPA
 AEY*    
>DL;IPD:MHC01168
IPD:MHC01168 Mamu-DPB1*14:01 259 bases
 MMVLQVSGTP QTVGLMALLM VLLTSVVQGR ATPENYLFQA RHDCYAFNGT
 QRFLERYIYN REEFLRFDSD VGEYRAVTEL GRPEAEYWNS QKDKLEEKRA
 VVDTMCRHNY ELDEAVTLQR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSIQVRWFL NGQEETAGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC GVGIFMHRRS
 KKVQRGSVX*    
>DL;IPD:MHC00371
IPD:MHC00371 Mamu-DPB1*15:01 259 bases
 MMVLQVSAAP RTVGLMALLM VLLTSVVQGR ATPENYLFQA RQECYAFNGT
 QRYLERYIYN REELLRFDSD VGEFRAVTEL GRPEAESWNS QKDTLEKKRA
 GVDTMCRHNY ELDEAVTLQR RVQPRVNIAP SKKGPLQHHN LLVCHVTDFY
 PGSVQVRWFL NGQEETAGVV STNLIRNGDW TFQILVMLEM TPQQGDVYTC
 QVEHPSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC GVGIFMHRRS
 KKVQRGSVX*    
>DL;IPD:MHC03586
IPD:MHC03586 Mamu-DPB1*16:01 89 bases
 PENYVYQSLT ECYEFNGTQR LLDRYIYNRE EFVRFDSYVG EYRAVTELGR
 PTAEYWNSLE DYMEETRAAV DTVCRYNYEL DEAVTLQRR* 
>DL;IPD:MHC03587
IPD:MHC03587 Mamu-DPB1*17:01 87 bases
 PENYVYQRWY ECYAFNGTQR LLDRYMYNQE EFVRFDSDLG EFRAVTELGR
 PTAERWNSQK DILERERASV DRVCRYNYEL EEPLIRK* 
>DL;IPD:MHC02190
IPD:MHC02190 Mamu-DPB1*19:01:01 258 bases
 MMVLPVSGAP QTVTLTALLM VLLTSVVQGT ATPENYVYQR RSECYAFNGT
 QRLLDRFIYN QEEYVRFDSD LGEFRAVTEL GRPDAEYWNR QDTLEQERAE
 VDRVCRHNYE LDEAVTLKRR VQPRVNVSPS KKGPLQHHNL LVCHVTDFYP
 GSIQVRWFLN GQEETAGVVS TNLIRNGDWT FQILVMLEMT PQQGDVYTCQ
 VEHPSLDSPV TMEWKAQSDS ARSKTLTGAG GFVLGLITCG VGIFMHRRSK
 KVQRGSAX*    
>DL;IPD:MHC02507
IPD:MHC02507 Mamu-DPB1*19:01:02 258 bases
 MMVLPVSGAP QTVTLTALLM VLLTSVVQGT ATPENYVYQR RSECYAFNGT
 QRLLDRFIYN QEEYVRFDSD LGEFRAVTEL GRPDAEYWNR QDTLEQERAE
 VDRVCRHNYE LDEAVTLKRR VQPRVNVSPS KKGPLQHHNL LVCHVTDFYP
 GSIQVRWFLN GQEETAGVVS TNLIRNGDWT FQILVMLEMT PQQGDVYTCQ
 VEHPSLDSPV TMEWKAQSDS ARSKTLTGAG GFVLGLITCG VGIFMHRRSK
 KVQRGSAX*    
>DL;IPD:MHC02506
IPD:MHC02506 Mamu-DPB1*19:02 258 bases
 MMVLPVSGAP QTVTLTALLM VLLTSVVQGT ATPENYVYQR RSECYAFNGT
 QRLLDRFIYN QEEYVRFDSD LGEFRAVTEL GRPDAEYWNR QDTLEQERAE
 VDRVCRHNYE LHEAVTLKRR VQPRVNVSPS KKGPLQHHNL LVCHVTDFYP
 GSIQVRWFLN GQEETAGVVS TNLIRNGDWT FQILVMLEMT PQQGDVYTCQ
 VEHPSLDSPV TMEWKAQSDS ARSKTLTGAG GFVLGLITCG VGIFMHRRSK
 KVQRGSAX*    
