>DL;IPD:MHC00361
IPD:MHC00361 Mamu-DPA1*02:01 810 bases
 ATGGACATCA ATTATAGACC CCACAACGTG TGTCCTGAAG ACAGAATGTT
 CCAGACCAGA GCTATTGTCT TGAGAACCCT CTCCTTGGCT TTCCTGCTGA
 GTCTCCGAGG AGCTGGGGCC ATCAAGGCAG ACCATGTATC AACTTATGCC
 GCGTTTGTAC AGACACATAG ACCAACAGGG GAGTTTATGT TTGAGTTTGA
 TGAAGATGAG CAGTTCTATG TGGATCTGGA CAAGAAGGAG ACCGTCTGGC
 ATCTGGAGGA GTTTGGCCGA GCCTTTTCCT TTGAGGCTCA GGGCGGGCTG
 GCTAACATTG CTATATTGAA CAACAACTTG AATATCACGA TCCAGCGTTC
 CAACTACACT CAGGCCGCCA ATGATCCCCC TGAGGTGACC GTGTTTCCCA
 AGGAGCCTGT GGCGCTGGGC CAACCCAACA CCCTCATCTG CCACATTGAC
 AAGTTCTTCC CTCCAGTGCT CAACGTCACG TGGCTGTGCA ATGGGGAGCC
 GGTCACTGAG GGTGTCGCTG AGAGCCTCTT CCTGCCCAGA ACAGATTATA
 GCTTCCACAA GTTCCATTAC CTGACCTTTG TGCCGTCAGC CGAGGACTAC
 TATGACTGCA GGGTGGAGCA TTGGGGCTTG GACCAGCCAC TCCTCAAACA
 CTGGGAGGCC CAAGAGCCAA TCCAGATCCC TGAGACAACG GAGACTGTGC
 TCTGTGCCCT GGGCCTGGTG CTGGGCCTAG TGGGCATCAT CGTGGGCACC
 GTCCTCATCA TAAAGTCTCT GCGATCTGGC CGTGACCCCC GTGCCCAGGG
 GCCCCTGTGA *   
>DL;IPD:MHC01161
IPD:MHC01161 Mamu-DPA1*02:02:01 783 bases
 ATGCACCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTTA TCTTGAGAAC
 CCTCTCCTTG GCTTTGCTGC TGAGTCTCGG AGGAGCTGGG GCCATCAAGG
 CAGACCATGT ATCAACTTAT GCCACGTTTG TACAGACACA TAGACCAACA
 GGGGAGTTTA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CGATCCGGCG TTCCAACTAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAACGTC
 ACGTGGCTGT GCAACGGGCA GCCGGCCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGACT ACAGCTTCCA CAAGTTCCAT TACTTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGATT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACCGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGACC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC03800
IPD:MHC03800 Mamu-DPA1*02:02:02 783 bases
 ATGCACCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTTA TCTTGAGAAC
 CCTCTCCTTG GCTTTGCTGC TGAGTCTCGG AGGAGCTGGG GCCATCAAGG
 CAGACCATGT ATCAACTTAT GCCACGTTTG TACAGACACA TAGACCAACA
 GGGGAGTTTA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CGATCCGGCG TTCCAACTAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAACGTC
 ACGTGGCTGT GCAACGGGCA GCCGGCCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGATT ATAGCTTCCA CAAGTTCCAT TACTTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGATT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGA ACTGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGATC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC01162
IPD:MHC01162 Mamu-DPA1*02:03 783 bases
 ATGTGCCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTGA TCTTGAGAAC
 CCTCTCCTTG GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT ATCAATTTAT GCCATGTTTG TACAGACACA TAGACCAACA
 GGGGAGTTTA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGT CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CGATCCAGCG TTCCAACTAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGACAGCCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCGGT GCTCAACGTC
 ACGTGGCTGT GCAATGGGGA GCCGGTCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGATT ATAGCTTCCA CAAGTTCCAT TACCTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGACT GCAGGGTGGA GCATTGGGGT
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACTGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGACC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC01163
IPD:MHC01163 Mamu-DPA1*02:04 783 bases
 ATGTGCCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTGA TCTTGAGAAC
 CCTCTCCTTG GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT ATCAACTTAT GCCTTGTTTG TACAGACACA TAGACCAACA
 GGGGAGTTTA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CGATCCAGCG TTCCAACTAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGACAGCCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCGGT GCTCAACGTC
 ACGTGGCTGT GCAATGGGGA GCCGGTCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGATT ATAGCTTCCA CAAGTTCCAT TACCTGACCT
 TTGTGCCGTC AGCCGAGGAC TACTATGACT GCAGGGTGGA GCATTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACTGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGACC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC01166
IPD:MHC01166 Mamu-DPA1*02:05 810 bases
 ATGGACATCA ATTATAGACC CCACAACGTG TGTCCTGAAG ACAGAATGTT
 CCAGACCAGA GCTATTGTCT TGAGAACCCT CTCCTTGGCT TTCCTGCTGA
 GTCTCCGAGG AGCTGGGGCC ATCAAGGCAG ACCATGTATC AACTTATGCC
 GCGTTTGTAC AGACACATAG ACCAACAGGG GAGTTTATGT TTGAGTTTGA
 TGAAGATGAG CAGTTCTATG TGGATCTGGA CAAGAAGGAG ACCGTCTGGC
 ATCTGGAGGA GTTTGGCCGA GCCTTTTCCT TTGAGGCTCA GGGCGGGCTG
 GCTAACATTG CTATATTGAA CAACAACTTG AATATCACGA TCCAGCGTTC
 CAACTACACT CAGGCCGCCA ATGATCCCCC TGAGGTGACC GTGTTTCCCA
 AGGAGCCTGT GGAGCTGGGC CAACCCAACA TCCTCATCTG CCACATTGAC
 AAGTTCTTCC CTCCAGTGCT CAACGTCACG TGGCTGTGCA ACGGGCAGCC
 GGCCACTGAG GGTGTCGCTG AGAGCCTCTT CCTGCCCAGA ACAGACTACA
 GCTTCCACAA GTTCCATTAC TTGACCTTTG TGCCCTCAGC CGAGGACTAC
 TATGATTGCA GGGTGGAGCA CTGGGGCTTG GACCAGCCGC TCCTCAAACA
 CTGGGAGGCC CAAGAGCCAA TCCAGATGCC TGAGACAACG GAGACTGTGC
 TCTGTGCCCT GGGCCTGGTG CTGGGCCTAG TGGGCATCAT CGTGGGAACT
 GTCCTCATCA TAAAGTCTCT GCGATCTGGC CGTGATCCCC GGGCCCAGGG
 GCCCCTGTGA *   
>DL;IPD:MHC01167
IPD:MHC01167 Mamu-DPA1*02:06 783 bases
 ATGCGCCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTTA TCTTGAGAAC
 CCTCTCCTTG GCTTTGCTGC TGAGTCTCGG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT ATCAACTTAT GCCTTGTTTG TACAGACACA TAGACCAACA
 GGGGAGTTTA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CGATCCAGCG TTCCAACTAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGACAGCCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCGGT GCTCAACGTC
 ACGTGGCTGT GCAATGGGGA GCCGGTCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGATT ATAGCTTCCA CAAGTTCCAT TACCTGACCT
 TTGTGCCGTC AGCCGAGGAC TACTATGACT GCAGGGTGGA GCATTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACCGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGATC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC02422
IPD:MHC02422 Mamu-DPA1*02:07 783 bases
 ATGCGCCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTTA TCTTGAGAAC
 CCTCTCCTTG GCTTTGCTGC TGAGTCTCGG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT ATCAACTTAT GCCATGTTTG TACAGACACA TAGACCAACA
 GGGGAGTTTA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CGATCCAGCG TTCCAACTAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGACAGCCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCGGT GCTCAACGTC
 ACGTGGCTGT GCAATGGGGA GCCGGTCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGATT ATAGCTTCCA CAAGTTCCAT TACCTGACCT
 TTGTGCCGTC AGCCGAGGAC TACTATGACT GCAGGGTGGA GCATTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACCGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGATC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC02632
IPD:MHC02632 Mamu-DPA1*02:08 783 bases
 ATGCACCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTTA TCTTGAGAAC
 CCTCTCCTTG GCTTTGCTGC TGAGTCTCGG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT ATCAACTTAT GCCTTGTTTG TACAGACACA TAGACCAACA
 GGGGAGTATA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA TGATCCGGCG TTCCAACTAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCATGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAACGTC
 ACGTGGCTGT GCAACGGGCA GCCCGTCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGATT ATAGCTTCCA CAAGTTCCAT TACCTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACTGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGATC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC03590
IPD:MHC03590 Mamu-DPA1*02:09 810 bases
 ATGGACATCA ATTATAGACC CCACAACGTG TGTCCTGAAG ACAGAATGTT
 CCAGACCAGA GCTATTGTCT TGAGAACCCT CTCCTTGGCT TTCCTGCTGA
 GTCTCCGAGG AGCTGGGGCC ATCAAGGCAG ACCATGTATC AACTTATGCC
 TTGTTTGTAC AGACACATAG ACCAACAGGG GAGTTTATGT TTGAGTTTGA
 TGAAGATGAG CAGTTCTATG TGGATCTGGA CAAGAAGGAG ACCGTCTGGC
 ATCTGGAGGA GTTTGGCCGA GCCTTTTCCT TTGAGGCTCA GGGCGGGCTG
 GCTAACATTG CTATATTGAA CAACAACTTG AATATCACGA TCCAGCGTTC
 CAACTACACT CAGGCCGCCA ATGATCCCCC TGAGGTGACC GTGTTTCCCA
 AGGAGCCTGT GGCGCTGGGC CAACCCAACA CCCTCATCTG CCACATTGAC
 AAGTTCTTCC CTCCAGTGCT CAACGTCACG TGGCTGTGCA ATGGGGAGCC
 GGTCACTGAG GGTGTCGCTG AGAGCCTCTT CCTGCCCAGA ACAGATTATA
 GCTTCCACAA GTTCCATTAC CTGACCTTTG TGCCGTCAGC CGAGGACTAC
 TATGACTGCA GGGTGGAGCA TTGGGGCTTG GACCAGCCAC TCCTCAAACA
 CTGGGAGGCC CAAGAGCCAA TCCAGATCCC TGAGACAACG GAGACTGTGC
 TCTGTGCCCT GGGCCTGGTG CTGGGCCTAG TGGGCATCAT CGTGGGCACC
 GTCCTCATCA TAAAGTCTCT GCGATCTGGC CGTGACCCCC GTGCCCAGGG
 GCCCCTGTGA *   
>DL;IPD:MHC05005
IPD:MHC05005 Mamu-DPA1*02:10 578 bases
 CCTGCTGAGT CTCGGAGGAG CTGGGGCCAT CAAGGCGGAC CATGTATCAA
 CTTATGCCAT GTTTGTACAG ACACATAGAC CAACAGGGGA GTTTATGTTT
 GAGTTTGATG AAGATGAGCA GTTCTATGTG GATCTGGACA AGAAGGAGAC
 CGTCTGGCAT CTGGAGGAGT TTGGCCGAGC CTTTTCCTTT GAGGCTCAGG
 GCGGGCTGGC TAACATTGCT ATATTGAACC ACAACTTGAA TATCACGATC
 CAGCGTTCCA ACTACACTCA GGCTGCCAAT GATCCCCCTG AGGTGACCGT
 GTTTCCCAAG GAGCCTGTGG AGCTGGGCCA ACCCAACACC CTCATCTGCC
 ACATTGACAA GTTCTTCCCT CCAGTGCTCA ATGTCACGTG GCTGTGCAAT
 GGGGAGCCAG TCACTGAGGG TGTCGCTGAG AGCCTCTTCC TGCCCAGAAC
 AGATTATAGC TTCCACAAGT TCCATTACCT GACCTTTGTG CCCTCAGCCG
 AGGACTACTA TGACTGCAGG GTGGAGCATT GGGGCTTGGA CCAGCCGCTC
 CTCAAACACT GGGAGGCCCA AGAGCCAA*  
>DL;IPD:MHC05016
IPD:MHC05016 Mamu-DPA1*02:11 578 bases
 CCTGCTGAGT CTCCGAGGAG CTGGGGCCAT CAAGGCGGAC CATGTATCAA
 CATATGTCGT GTTTACACAG ACACATAGAC CAACAGGGGA GTTTATGTTT
 GAGTTTGATG AAGATGAGCA GTTCTATGTG GATCTGGACA AGAAGGAGAC
 TGTCTGGCAT CTGGAGGAGT TTGGCCGAGC CTTTTCCTTT GAGGCTCAGG
 GCGGGCTGGC TAACATTGCT ATATCGAACA ACAACTTGAA TACCATGATC
 CAGCGTTCCA ACTACACTCA GGCCGCCAAT GATCCCCCTG AGGTGACCGT
 GTTTCCCAAG GAGCCTGTGG AGCTGGGACA GCCCAACACC CTCATCTGCC
 ACATTGACAA ATTCTTCCCT CCGGTGCTCA ACGTCACGTG GCTGTGCAAT
 GGGGAGCCGG TCACTGAGGG TGTCGCTGAG AGCCTCTTCC TGCCCAGAAC
 AGATTATAGC TTCCACAAGT TCCATTACCT GACCTTTGTG CCCTCAGCCG
 AGGACTACTA TGACTGCAGG GTGGAGCATT GGGGCTTGGA CCAGCCGCTC
 CTCAAACACT GGGAGGCCCA AGAGCCAA*  
>DL;IPD:MHC05215
IPD:MHC05215 Mamu-DPA1*02:12 783 bases
 ATGCGCCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTTA TCTTGAGAAC
 CCTCTCCTTG GCTTTGCTGC TGAGTCTCGG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT ATCAACTTAT GCCACGTTTG TACAGACACA TAGACCAACA
 GGGGAGTTTA TGTTTGAGTT TGATGAAGAT GAGCAGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCA CGATCCAGCG TTCCAACTAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGACAGCCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCGGT GCTCAACGTC
 ACGTGGCTGT GCAATGGGGA GCCGGTCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGATT ATAGCTTCCA CAAGTTCCAT TACCTGACCT
 TTGTGCCGTC AGCCGAGGAC TACTATGACT GCAGGGTGGA GCATTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACTGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGATC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC02633
IPD:MHC02633 Mamu-DPA1*04:01 783 bases
 ATGCGTCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTTA TCTTGAGAAC
 CCTTTCCTTG GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT GTTAACTTTT ACCACATTTG TACAGACGCA TAGACCAACA
 GGGGAGTATA TGTATGAGTT GGATGAAGAT GAAATGTTCT TTGTGGATCT
 GGACAAGAAA GAGACCATCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATC GAACAACAAC
 TTGAATGTCA CGATCCAGCT TTCCAACCAT ACTCAGGCCA CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAATGTC
 ACATGGCTGT GCAACGGGCA GCCGGTCACT GAGGGTGTCA CTGAGAGCCT
 CTTCCTGCCC AGAACAGACT ACAGCTTCCA CAAGTTCCAT TACCTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAAC CGCTCCTCAA GCACTGGGAG CCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACCGTCCTCA TCATAAAGTC TCTGCGTTCT
 GGCCGTGACC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC02631
IPD:MHC02631 Mamu-DPA1*04:02 765 bases
 ATGTTCCAGA CCAGAGCTGT GATCTTGAGA ACCCTCTCCT TGGCTTTCCT
 GCTGAGTCTC CGAGGAGCTG GGGCCATCAA GGCGGACCAT GTGTTAACTT
 TTGCCGCATT TGTACAGACG CATAGACCAA CAGGGGAGTA TATGTACGAG
 TTGGATGAAG ATGAAATATT CTTTGTGGAT CTGGACAAGA AGGAGACTGT
 CTGGCATCTG GAGGAGTTTG GCCGAGCCTT TTCCTTTGAG GCTCAGGGCG
 GGCTGGCTAA CATTGCTATA TTGAACAACA ACTTGAATGT CACGATCCAG
 CTTTCCAACC ACACTCAGGC CACCAATGAT CCCCCTGAGG TGACCGTGTT
 TCCCAAGGAG CCTGTGGAGC TGGGCCAACC CAACACCCTC ATCTGCCACA
 TTGACAAGTT CTTCCCTCCA GTGCTCAATG TCACATGGCT GTGCAACGGG
 CAGCCGGTCA CTGAGGGTGT CACTGAGAGC CTCTTCCTGC CCAGAACAGA
 CTACAGCTTC CACAAGTTCC ATTACCTGAC CTTTGTGCCC TCAGCCGAGG
 ACTACTATGA CTGCAGGGTG GAGCACTGGG GCTTGGACCA GCCGCTCCTC
 AAGCACTGGG AGGCCCAAGA GCCAATCCAG ATGCCTGAGA CAACGGAGAC
 TGTGCTCTGT GCCCTGGGCC TGGTGCTGGG CCTAGTGGGC ATCATCGTGG
 GCACCGTCCT CATCATAAAG TCTCTGCGAT CTGGCCGTGA CCTCCGGGCC
 GAGGGGCCCC TGTAA*   
>DL;IPD:MHC03577
IPD:MHC03577 Mamu-DPA1*04:03 783 bases
 ATGCGTCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTTA TCTTGAGAAC
 CCTTTCCTTG GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT GTTAACTTTT ACCACATTTG TACAGACGCA TAGACCAACA
 GGGGAGTATA TGTATGAGTT GGATGAAGAT GAAATATTCT TTGTGGATCT
 GGACAAGAAG GAGACCATCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATC GAACAACAAC
 TTGAATGTCA CGATCCAGCT TTCCAACCAT ACTCAGGCCA CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAATGTC
 ACATGGCTGT GCAACGGGCA GCCGGTCACT GAGGGTGTCA CTGAGAGCCT
 CTTCCTGCCC AGAACAGACT ACAGCTTCCA CAAGTTCCAT TACCTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAAC CGCTCCTCAA GCACTGGGAG CCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACCGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGACC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC03801
IPD:MHC03801 Mamu-DPA1*04:04 783 bases
 ATGCGTCCTG AAGACAGAAT GTTCCAGACC AGAGCTGTTA TCTTGAGAAC
 CCTTTCCTTG GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT GTTAACTTTT ACCACATTTG TACAGACGCA TAGACCAACA
 GGGGAGTTTA TGTATGAGTT GGATGAAGAT GAAATATTCT TTGTGGATCT
 GGACAAGAAG GAGACCATCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATC GAACAACAAC
 TTGAATGTCA CGATCCAGCT TTCCAACCAT ACTCAGGCCA CCAATGATCC
 CCCTGAGGTG ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAACCCA
 ACACCCTCAT CTGCCACATT GACAAGTTCT TCCCTCCAGT GCTCAATGTC
 ACATGGCTGT GCAACGGGCA GCCGGTCACT GAGGGTGTCA CTGAGAGCCT
 CTTCCTGCCC AGAACAGACT ACAGCTTCCA CAAGTTCCAT TACCTGACCT
 TTGTGCCCTC AGCCGAGGAC TACTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAAC CGCTCCTCAA GCACTGGGAG CCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACCGTCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGACC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC01164
IPD:MHC01164 Mamu-DPA1*06:01 810 bases
 ATGGACATCA ATTATAGACC CCACAACGTG TGCCCTGAAG ACAGAATGTT
 CCAGACCAGA GCTATTGTCT TGAGAACCCT CTCCTTGGCT TTCCTGCTGA
 GTCTCCGAGG AGCTGGGGCC ATCAAGGCGG ACCATGTATC AACTTATGCC
 ATGTTTGTAC AGACACATAG ACCAACAGGG GAGTTTATGT TTGAGTTTGA
 TGAGGATGAG ATGTTCTATG TGGATCTGGA CAAGAAGGAG ACCGTCTGGC
 ATCTGGAGGA GTTTGGCCAA GCCATTTCCT TTGAGGCTCA GGGCGGGCTG
 GCTAACATTG CTATATTGAA CCACAACTTG AATATCACGA TCCAGCGTTC
 CAACTACACT CAGGCCGCCA ATGATCCCCC TGAGGTGACC GTGTTTCCCA
 AGGAGCCTGT GGAGCTGGGC CAACCCAACA CCCTCATCTG CCACATTGAC
 AAGTTCTTCC CTCCAGTGCT CAACGTCACG TGGCTGTGCA ATGGGGAGCC
 GGTCACTGAG GGTGTCGCTG AGAGCCTCTT CCTGCCCAGA ACAGATTATA
 GCTTCCACAA GTTCCATTAC CTGACCTTTG TGCCCTCAGC CGAGGACTAC
 TATGACTGCA GGGTGGAGCA TTGGGGCTTG GACCAGCCGC TCCTCAAACA
 CTGGGAGGCC CAAGAGCCAA TCCAGATCCC TGAGACAACG GAGACTGTGC
 TCTGTGCCCT GGGCCTGGTG CTGGGCCTAG TGGGCATCAT CGTGGGCACC
 GTCCTCATCA TAAAGTCTCT GCGATCTGGC CGTGACCCCC GGGCCCAGGG
 GCCCCTGTGA *   
>DL;IPD:MHC05001
IPD:MHC05001 Mamu-DPA1*06:01:02 578 bases
 CCTGCTGAGT CTCCGAGGAG CTGGGGCCAT CAAGGCGGAC CATGTGTCCA
 CTTATGCCAT GTTTGTACAG ACACATAGAC CAACAGGGGA GTTTATGTTT
 GAGTTTGATG AGGATGAGAT GTTCTATGTG GATCTGGACA AGAAGGAGAC
 CGTCTGGCAT CTGGAGGAGT TTGGCCAAGC CATTTCCTTT GAGGCTCAGG
 GCGGGCTGGC TAACATTGCT ATATTGAACC ACAACTTGAA TATCACGATC
 CAGCGTTCCA ACTACACTCA GGCCGCCAAT GATCCCCCTG AGGTGACCGT
 GTTTCCCAAG GAGCCTGTGG AGCTGGGCCA ACCCAACACC CTCATCTGCC
 ACATTGACAA GTTCTTCCCT CCAGTGCTCA ACGTCACGTG GCTGTGCAAT
 GGGGAGCCGG TCACTGAGGG TGTCGCTGAG AGCCTCTTCC TGCCCAGAAC
 AGATTATAGC TTCCACAAGT TCCATTACCT GACCTTTGTG CCCTCAGCCG
 AGGACTACTA TGACTGCAGG GTGGAGCATT GGGGCTTGGA CCAGCCGCTC
 CTCAAACACT GGGAGGCCCA AGAGCCAA*  
>DL;IPD:MHC01990
IPD:MHC01990 Mamu-DPA1*06:02 810 bases
 ATGGACATCA ATTATAGACC CCACAACGTG TGCCCTGAAG ACAGAATGTT
 CCAGACCAGA GCTATTGTCT TGAGAACCCT CTCCTTGGCT TTCCTGCTGA
 GTCTCCGAGG AGCTGGGGCC ATCAAGGCGG ACCATGTATC AACTTATGCC
 GCGTTTGTAC AGACACATAG ACCAACAGGG GAGTTTATGT TTGAGTTTGA
 TGAGGATGAG ATGTTCTATG TGGATCTGGA CAAGAAGGAG ACCGTCTGGC
 ATCTGGAGGA GTTTGGCCAA GCCATTTCCT TTGAGGCTCA GGGCGGGCTG
 GCTAACATTG CTATATTGAA CCACAACTTG AATATCACGA TCCAGCGTTC
 CAACTACACT CAGGCCGCCA ATGATCCCCC TGAGGTGACC GTGTTTCCCA
 AGGAGCCTGT GGAGCTGGGC CAACCCAACA CCCTCATCTG CCACATTGAC
 AAGTTCTTCC CTCCAGTGCT CAACGTCACG TGGCTGTGCA ATGGGGAGCC
 GGTCACTGAG GGTGTCGCTG AGAGCCTCTT CCTGCCCAGA ACAGATTATA
 GCTTCCACAA GTTCCATTAC CTGACCTTTG TGCCCTCAGC CGAGGACTAC
 TATGACTGCA GGGTGGAGCA TTGGGGCTTG GACCAGCCGC TCCTCAAACA
 CTGGGAGGCC CAAGAGCCAA TCCAGATCCC TGAGACAACG GAGACTGTGC
 TCTGTGCCCT GGGCCTGGTG CTGGGCCTAG TGGGCATCAT CGTGGGCACC
 GTCCTCATCA TAAAGTCTCT GCGATCTGGC CGTGACCCCC GGGCCCAGGG
 GCCCCTGTGA *   
>DL;IPD:MHC04999
IPD:MHC04999 Mamu-DPA1*06:03 578 bases
 CCTGCTGAGT CTCCGAGGAG CTGGGGCCAT CAAGGCGGAC CATGTATCAA
 CTTATGCCAT GTTTGTACAG ACACATAGAC CAACAGGGGA GTTTATGTTT
 GAGTTTGATG AGGATGAGAT GTTCTATGTG GATCTGGACA AGAAGGAGAC
 CGTCTGGCAT CTGGAGGAGT TTGGCCAAGC CATTTCCTTT GAGGCTCAGG
 GCGGGCTGGC TAACATTGCT ATATTGAACC ACAACTTGAA TATCACGATC
 CAGCGTTCCA ACTACACTCA GGCCGCCAAT GATCCCCCTG AGGTGACCGT
 GTTTCCCAAG GAGCCTGTGG AGCTGGGCCA ACCCAACACC CTCATCTGCC
 ACATTGACAA GCTCTTCCCT CCAGTGCTCA ACGTCACGTG GCTGTGCAAT
 GGGGAGCCGG TCACTGAGGG TGTCGCTGAG AGCCTCTTCC TGCCCAGAAC
 AGATTATAGC CTCCACAAGT TCCATTACCT GACCTTTGTG CCCTCAGCCG
 AGGACTACTA TGACTGCAGG GTGGAGCATT GGGGCTTGGA CCAGCCGCTC
 CTCAAACACT GGGAGGCCCA AGAGCCAA*  
>DL;IPD:MHC01165
IPD:MHC01165 Mamu-DPA1*07:01 807 bases
 GTCATCAATT ATAGACCCCA CAACGTGTGC CCTGAAGACA GAATGTTCCA
 GACCAGAGCT GTGATCTTGA GAGCCCTCTC CTGGGCTTTC CTGCTGAGTC
 TCCGAGGAGC TGGGGCCATC AAGGCGGACC ATGTGTCCAC TTATGCCTCG
 TTTGTACAGA CACATAGACC AACAGGGGAG TTTATGTTTG AGTTTGATGA
 GGATGAGATG TTCTATGTGG ATCTGGACAA GAAGGAGACC GTCTGGCATC
 TGGAGGAGTT TGGCCGAGCC TTTTCCTTTG AGGCTCAGGG CGGGCTGGCT
 AACATTGCTG CATTGAACCA CAACTTGAAT ACCTTGATCC AGCGTTCCAA
 CCACACTCAG GCCGCCAATG ATCCCCCTGA GGTGACTGTG TTTCCCAAGG
 AGCCTGTGGA GCTGGGACAG CCCAACACCC TCATCTGCCA CATTGACAAG
 TTCTTCCCAC CGGTGCTCAA CGTTACATGG CTGTGCAATG GGGAGCCGGT
 CACTGAGGGT GTTGCTGAGA GCCTCTTCCT GCCCAGAACA GATTACAGAT
 TACACAAGTT CCATTACCTG ACCTTTGTGC CCTCGGCCGA GGACTTCTAT
 GACTGCAGGG TGGAACACTG GGGCTTGGAC CAGCCGCTCC TCAAGCACTG
 GGAGGCCCAA GAGCCAATCC AGATGCCTGA GACAAGGGAG ACTGTGCTCT
 GTGCCCTGGG CCTGGTGCTG GGCCTAGTGG GCATCATCGT GGGCACCGTC
 CTCATCATAA AGTCTCTGCG ATCTGGCCGT GACCCCCGGG CCCAGGGGCC
 CCTGTGA*    
>DL;IPD:MHC05003
IPD:MHC05003 Mamu-DPA1*07:02 578 bases
 CCTGCTGAGT CTCCGAGGAG CTGGGGCCAT CAAGGCGGAC CATGTATCAA
 CTTATGCCAT GTTTGTACAG ACACATAGAC CAACAGGGGA GTTTATGTTT
 GAGTTTGATG AAGATGAGAT GTTCTATGTG GATCTGGACA AGAAGGAGAC
 CGTCTGGCAT CTGGAGGAGT TTGGCCGAGC CTTTTCCTTT GAGGCTCAGG
 GCGGGCTGGC TAACATTGCT GCATTGAACA ACAACTTGAA TACCTTGATC
 CAGCTTTCCA ACCACACTCC GGCCGCCAAT GATCCCCCTG AGGTGACCGT
 GTTTCCCAAG GAGCCTGTGG AGCTGGGCCA GCCCAACACC CTCATCTGCC
 ACATTGACAA ATTCTTCCCT CCGGTGCTCA ATGTCACGTG GCTGTGCAAC
 GGAGAGCCGG TCACTGAGGG TGTCGCTGAG AGCCTCTTCC TGCCCAGAAC
 TGATTACAGA TTACACAAGT TCCATTACCT GACCTTTGTG CCCTCAGCCG
 AGGACTACTA TGACTGCAGG GTGGAACACT GGGGCTTGGA CCAGCCGCTC
 CTCAAGCACT GGGAGGCCCA AGAGCCAA*  
>DL;IPD:MHC04997
IPD:MHC04997 Mamu-DPA1*07:03 578 bases
 CCTGCTGAGT CTCCGAGGAG CTGGGGCCAT CAAGGCGGAC CATGTGTCCA
 CTTATGCCTC GTTTGTACAG ACACATAGAC CAACAGGGGA GTTTATGTTT
 GAGTTTGATG AAGATGAGCA GTTCTATGTG GATCTGGACA AGAAGGAGAC
 CGTCTGGCAT CTGGAGGAGT TTGGCCGAGC CTTTTCCTTT GAGGCTCAGG
 GCGGGCTGGC TAACATTGCT GCATTGAACC ACAACTTGAA TATCTTGATC
 CAGCGTTCCA ACCACACTAA GGCCGCCAAT GATCCCCCTG AGGTGACCGT
 GTTTCCCAAG GAGCCTGTGG AGCTGGGACA GCCCAACACC CTCATCTGCC
 ACATTGACAA GTTCTTCCCA CCGGTGCTCA ACGTTACATG GCTGTGCAAT
 GGGGAGCCGG TCACTGAGGG TGTTGCTGAG AGCCTCTTCC TGCCCAGAAC
 AGATTACAGA TTACACAAGT TCCATTACCT GACCTTTGTG CCCTCGGCCG
 AGGACTTCTA TGACTGCAGG GTGGAACACT GGGGCTTGGA CCAGCCGCTC
 CTCAAGCACT GGGAGGCCCA AGAGCCAA*  
>DL;IPD:MHC01989
IPD:MHC01989 Mamu-DPA1*08:01 783 bases
 ATGTGCCCTG AAGACAGAAT GTTCCAGACC AGATCTGTGA TCTTGAGAAC
 CCTCTCCTTG GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT GTCCACTTAT GCCTTGTTTG TACAGACACA TAGACCAACA
 GGGGAGTATA TGTTTGAGTT TGATGAGGAT GAGATGTTCT ATGTGGATCT
 GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC CGAGCCTTTT
 CCTTTGAGGC TCAGGGCGGG CTGGATGACA TTGCTACATT GAAGTACAAC
 TTGAATATCA CGATCCAGCG TTCCAACCAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ATGGTGTTTC CCAAGGAGCC TGTGGAGCTG GGACAGCCCA
 ACACCCTCAT CTGCCACATT GACAAATTCT TCCCTCCGGT GCTCAACGTC
 ACGTGGCTGT GCAATGGGGA GCCGGTCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC AGAACAGACT ACAGCTTCCA CAAGTTCCAT TACTTGACCT
 TTGTGCCCTC GGCCGAAGAC TTCTATGACT GCAGGGTGGA GCATTGGGGC
 TTGGACCAGC CGCTCCTCAA ACACTGGGAG GCCCAAGAGC CAATCCAGAT
 GCCTGAGACA ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC
 TAGTGGGCAT CATCGTGGGC ACCATCCTCA TCATAAAGTC TCTGCGATCT
 GGCCGTGACC CCCGGGCCCA GGGGCCCCTG TGA* 
>DL;IPD:MHC05017
IPD:MHC05017 Mamu-DPA1*08:02 578 bases
 CCTGCTGAGT CTCGGAGGAG CTGGGGCCAT CAAGGCGGAC CATGTGTCCA
 CTTATGCCTT GTTTGTACAG ACACATAGAC CAACAGGGGA GTATATGTTT
 GAGTTTGATG AGGATGAGAT GTTCTATGTG GATCTGGACA AGAAGGAGAC
 CGTCTGGCAT CTGGAGGAGT TTGGCCGAGC CTTTTCCTTT GAGGCTCAGG
 GCGGGCTGGA TGACATTGCT ACATTGAAGT ACAACTTGAA TATCACGATC
 CAGCGTTCCA ACCACACTCA GGCCGCCAAT GATCCCCCTG AGGTGATGGT
 GTTTCCCAAG GAGCCTGTGG AGCTGGGACA GCCCAACACC CTCATCTGCC
 ACATTGACAA ATTCTTCCCT CCGGTGCTCA ACGTCACGTG GCTGTGCAAT
 GGGGAGCCGG TCACTGAGGG TGTCGCTGAG AGCCTCTTCC TGCCCAGAAC
 AGACTACAGC TTCCACAAGT TCCATTACTT GACCTTTGTG CCCTCGGCCG
 AAGACTTCTA TGACTGCAGG GTGGAGCATT GGGGCTTGGA CCAGCCGCTC
 CTCAAACACT GGGAGGCCCA AGAGCCAA*  
>DL;IPD:MHC05011
IPD:MHC05011 Mamu-DPA1*10:01 578 bases
 CCTGCTGAGT CTCCGAGGAG CTGGGGCCAT CAAGGCGGAC CATGTGTCCA
 CTTTTGCCAT GTTTGTACAG ACACATAGAC CAACAGGGGA GTATATGTCT
 GAATTTGATG AGGATGAGAT GCTCTATGTG GATCTGGACA AGAAGGAGAC
 CGTCTGGCAT CTGGAGGAGT TTGGCCGAGC CCTTTTCCTT GACGCTCAGG
 GCGGGCTGGC TAACATTGCT GCATTGAACA ACCACTTGAA TATCATGATC
 CAGCGTTCCA ACCACTCTCA GGCCGCCAAT GATCCCCCTG AGGTGACCGT
 GTTTCCCAAG GAGCCTGTGG AGCTGGGCCA GCCCAACACC CTCATCTGCC
 ACATTGACAA GTTCTTCCCA CCAGTGCTCA ACGTCACATG GCTGTGCAAC
 GGAAAGCTGG TCACTAAGGG TGTCACTGAG AGCCTCTTCC TGCCCAGAAC
 AGATTACAGA TTACACAAGT TCCATTACTT GACCTTTGTG CCCTCGGCCG
 AGGACTACTA TGACTGCAGG GTGGAACACT GGGGCTTGGA CCAGCCACTC
 CTCAAGCACT GGGAGGCCCA AGAGCCAA*  
>DL;IPD:MHC05014
IPD:MHC05014 Mamu-DPA1*11:01 783 bases
 ATGCGCCCTG AAGGCAGAGT GTTCCAGACC AGAACTGTGA TCTTAAGAGC
 CTTCTCCTTT GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG
 CGGACCATGT GTCAACTTAT GCCATGTTTG TACAGACGCA TAACCCAACA
 GGGGAGTATA TGTTTGAGTT TGATGAGGAT GAGCAGTTCT ATGTGGATCT
 GGATAAGAAG GAGACTGTCT GGCATCTGGA GGAGTTTGCC CAAGCCTTTT
 CCTTTGAGGC TCAGGGTGGG CTGGATGACA TTGCTACATT GAAGTACAAC
 TTGAATATCA TGATCCAGCG TTCCAACCAC ACTCAGGCCG CCAATGATCC
 CCCTGAGGTG ACTGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAGCCCA
 ACACCCTCAT TTGCCACATT GACAAGTTCT TCCCTCCGGT GCTCAACGTC
 ACATGGTTGT GCAACGGGGA GCCCGTCACT GAGGGTGTCG CTGAGAGCCT
 CTTCCTGCCC GGAACAGATT TTAGCTTCCA CAAGTTTCAT TACCTGACCT
 TTGTGCCTTC AGTCGAGGAC GTCTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGATCAGC CATTCCTCAA GCACTGGGAG GCCCAAGAGC CAATCCAGAT
 CCCTGAGACG ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTAGGCT
 TAGTGGGCAT CATCGTGGGC ACCATCCTCA TCTTAAAGGC TATGCGTTCT
 GGCCGTGACC CCCGGGCCCA GGGGCCCCTG TGA* 
