>DL;IPD:MHC00629
IPD:MHC00629 Mane-DRB*W1:01 89 bases
 RFLEYCKFEC HFFNGTERVQ YLIRYFYNQE EYVRYDSDVG EYRAVTELGR
 PDAEYWNGQK DLLEQRRAEV DTVCRHNYGV VESFTVQRR* 
>DL;IPD:MHC00630
IPD:MHC00630 Mane-DRB*W1:02 89 bases
 RFLEYCKFEC HFFNGTELML YLIRYFHNQE EYVRYDSDVG EYRAVTELGR
 PVAENWNSQK DLLEQRRAEV DTYCRHNYGV GESFTVQRR* 
>DL;IPD:MHC03925
IPD:MHC03925 Mane-DRB*W1:03 75 bases
 KFECHFFNGT ERVLNLIRYF YNQEEYVRYD SDVGEYRAVT ELGRPDAKYW
 NGQKDLLEQR RAEVDTYCRH NYGVV*  
>DL;IPD:MHC03926
IPD:MHC03926 Mane-DRB*W1:04 75 bases
 KFECHFFNGT ERVLNLIRYF YNQEEYVRYD SDVGEYRAVT ELGRPDAEYW
 NGQKDLLEQR RAEVDTYCRH NYRVG*  
>DL;IPD:MHC03927
IPD:MHC03927 Mane-DRB*W1:05 75 bases
 KFECHFFNGT ERVQYLIRYF YNQEEYVRYD SDVGEYRAVT ELGRPDAEYW
 NGQKDLLEQR RAEVDNYCRH NYGVG*  
>DL;IPD:MHC03928
IPD:MHC03928 Mane-DRB*W1:06 178 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALAG DTRPRFLEYC KFECHFFNGT
 ERVLNLIRYF YNQEEYVRYD SDVGEYRAVT ELGRPDAKYW NGQKDLLEQR
 RAEVDTYCRH NYRVGESFTV QRRVQPKVTV YPAKTQPLQH HTLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQ*  
>DL;IPD:MHC03929
IPD:MHC03929 Mane-DRB*W1:07 178 bases
 MVCLKLPGGS CMAPLTVTLM VLSSPLALAG DTRPRFLEYC KFECHFFNGT
 ERVLNLIRYF YNQEEYVRYD SDVGEYRAVT ELGRPDAKYW NGQKDLLEQR
 RAEVDTYCRH NYRVVESFTV QRRVQPKVTV YPAKTQPLQH HTLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQ*  
>DL;IPD:MHC03986
IPD:MHC03986 Mane-DRB*W1:08 75 bases
 TFECHFFNGT ERVLNLIRYF YNQEEYVRYD SDVGEYRAVT ELGRPDAKYW
 NGQKDLLEQR RAEVDTYCRH NYRVG*  
>DL;IPD:MHC03987
IPD:MHC03987 Mane-DRB*W1:09 75 bases
 KFECHFFNGT ERVQYLIRYF YNQEEYVRYD SDVGEYRAVT ELGRPDAEYW
 NGQKDLLEQR RAEVDTYCRH NYRVV*  
>DL;IPD:MHC03988
IPD:MHC03988 Mane-DRB*W1:10 178 bases
 MVCLKLPGGS CMAPLTVTLM VLSSPLALAG DTRPRFLEYC KFECHFFNGT
 ERVQYLIRYF YNQEEYVRYD SDVGEYRAVT ELGRPDAEYW NGQKDLLEQR
 RAEVDTVCRH NYGVGESFTV QRRVQPKVTV YPAKTQPLQH HTLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQ*  
>DL;IPD:MHC03989
IPD:MHC03989 Mane-DRB*W1:11 178 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALTG DIRPRFLEYC KFECHFFNGT
 ERVLNLIRYF YNQEEYVRYD SDVGEYRAVT ELGRPDAKYW NGQKDLLEQR
 RAEVDTVCRH NYGVVESFTV QRRVQPKVTV YPAKTQPLQH HTLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQ*  
>DL;IPD:MHC04579
IPD:MHC04579 Mane-DRB*W1:12 178 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALAG DTRPRFLEYC KFECHFFNGT
 ERVLNLIRYF YNQEEYVRYD SDVGEYRAVT ELGRPDAKYW NGQKDLLEQR
 RAEVDTYCRH NYRVVESFTV QRRVQPKVTV YPAKTQPLQH HTLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQ*  
>DL;IPD:MHC03448
IPD:MHC03448 Mane-DRB*W20:01 178 bases
 MVFLKLPGGS CMAALTVTLM VLSSPLALAG DTRPRFLEQF KSECHFFNGT
 ERVRYLQRYF YNQEEYVRFD SDVGEFRAVT ELGRRSAEYF NSQKDFLERR
 RAQVDNYCRH NYGVVESFTV QRRVHPKVTV YPSKTQPLQH HTLLVCSVSG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIH*  
>DL;IPD:MHC03930
IPD:MHC03930 Mane-DRB*W21:01 75 bases
 KSECHFFNGT ERVRFLERYF YNQEEYVRFD SDVGEYRAVS ELGRRSAEYW
 NGQKGYLEQK RGQVDNYCRH NYGVG*  
>DL;IPD:MHC03993
IPD:MHC03993 Mane-DRB*W21:02 178 bases
 MVCLKLPGGS CMAALTMTLM VLSSPLALAG DTRPRFLEQV KSECHFFNGT
 ERVRFLERYF YNQEEYVRFD SDVGEYRAVS ELGRRSAEYW NGQKGYLEQK
 RGQVDNYCRH NYGVVESFTV QRRVQPKVTV YPAKTQPLQH HTLLVCSVSG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQ*  
>DL;IPD:MHC03897
IPD:MHC03897 Mane-DRB*W25:01 75 bases
 KYECHFFNGT ERVRFLERHI SNQEENVRFD SDVGEYRAVT ELGRPDAESW
 NSQKDILEDN RAAVDTYCRH NYRIA*  
>DL;IPD:MHC03921
IPD:MHC03921 Mane-DRB*W25:02 75 bases
 KYECHFFNGT ERVRFLERHI SNQEENVRFD SDVGEYRAVT ELGRPDAESW
 NSQKDFLEDR RAAVDNYCRY NYRVG*  
>DL;IPD:MHC04580
IPD:MHC04580 Mane-DRB*W25:03 178 bases
 MVCLKLPGGS CMATLTVTLM VLSSPLALAG DTRPRFLEQA KAECHFFNGT
 ERVRFLQRHI SNQEENVRFD SDVGEFRAVT ELGRPDAEYW NSQKDILEEK
 RAAVDTYCRH NYRIAESFTV QRRVQPKVTV YPAKTQPLQH HNLLVCSVNG
 FYPGSTEVRW FRNGQEEKAG VVSTGLIQ*  
>DL;IPD:MHC04588
IPD:MHC04588 Mane-DRB*W25:04 178 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLAVAG DTRPRFLEQA KAECHFFNGT
 ERVRFLERHF YNQEEFLRFD SDVGEYRAVT ELGRPTAESW NSRKDVLERA
 RTAADTYCRH NYRGGESFTV QRRVQPKVTV YPAKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIH*  
>DL;IPD:MHC03920
IPD:MHC03920 Mane-DRB*W26:01 75 bases
 KCECHFFNGT ERVRFLERHF YNQEEFVRFD SDVGEYRAVT ELGRPAAEYW
 NGQKDFLEDR RAQVDTVCRH NYGVF*  
>DL;IPD:MHC03449
IPD:MHC03449 Mane-DRB*W27:01 178 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLAVAG DTRSRFLEQA KSECHFFNGT
 ERVRYLQRYL YNQEEYVLFD SDVGEHRAVT ELGRPDAEYW NSQKDILEDQ
 RAAVDTFCRY NYRVFESFTV QRRVQPKVTV YPAKTQPLQH HTLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQ*  
>DL;IPD:MHC03991
IPD:MHC03991 Mane-DRB*W27:02 178 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALAG DTRPRFLEQV KSECHFFNGT
 ERVRFLQRYI YNQEEYVRFD SDVGEHRAVT ELGRRSAEYF NSQKDFLEDQ
 RAAVDTYCRY NYGVGESFTV QRRVQPKVTV YPAKTQPLQH HTLLVCSVNG
 FYPGSIEVRW FRNDQEEKAG VVSTGLIQ*  
>DL;IPD:MHC00631
IPD:MHC00631 Mane-DRB*W2:01 88 bases
 RFLGHAKSEC HFFNGTERVR FLQRYIYNQE ELVRFDSDVG EFRAVTELGR
 PVAESWNSRK DFLERERAQV DTCRHNYGGV ESFTVQRR* 
>DL;IPD:MHC00632
IPD:MHC00632 Mane-DRB*W2:02 88 bases
 HFLDQVKYEC HFFNGTERVR LLGRHFYNQE ELVRFDSDVG EYRAVSELGR
 PDAENLNARK DVLEQARAQV DTCRHNYGVV ESFTVQRR* 
>DL;IPD:MHC03913
IPD:MHC03913 Mane-DRB*W2:03 75 bases
 KSECHFFNGT ERVRFLQRYI YNQEELVRFD SDVGEFRAVT ELGRPVAESW
 NSRKDILERE RAQVDTFCRH NYGGV*  
>DL;IPD:MHC03914
IPD:MHC03914 Mane-DRB*W2:04 75 bases
 KSECHFFNGT ERVRFLQRYI YNQEEFVRFD SDVGEFRAVT ELGRPDAESW
 NTREDILERE RAQVDTFCRH NYGGV*  
>DL;IPD:MHC03915
IPD:MHC03915 Mane-DRB*W2:05 75 bases
 KSECHFFNGT ERVRFLQRYI YNQEEFVRFD SDVGEFRAVT ELGRPVAESW
 NSRKDILERE RAQVDTFCRH NYGGV*  
>DL;IPD:MHC03916
IPD:MHC03916 Mane-DRB*W2:06 177 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALAG DTRARFLGHA KSECHFFNGT
 ERVRFLQRYI YNQEEFVRFD SDVGEFRAVT ELGRPVAESW NSRKDFLERE
 RAQVDTCRHN YGVGESFTVQ RRVQPKVTVY PAKTQPLQHH TLLVCSVSGF
 YPGSIEVRWF RNGQEEKAGV VSTGLIQ*  
>DL;IPD:MHC03917
IPD:MHC03917 Mane-DRB*W2:07 75 bases
 KSECHFFNGT ERVRFLDRYF HNQEEFVRFD SDVGEFRAVT ELGRPDAESW
 NTREDILERE RAQVDTFCRH NYGVV*  
>DL;IPD:MHC03918
IPD:MHC03918 Mane-DRB*W2:08 177 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALAG DTRPRFLGHA KSECHFFNGT
 ERVRFLQRYI YNQEEFVRFD SDVGEFRAVT ELGRPVAESW NSRKDFLERE
 RAQVDTCRHN YGVGESFTVQ RRVQPKVTVY PAKTQPLQHH TLLVCSVSGF
 YPGSIEVRWF RNGQEEKAGV VSTGLIQ*  
>DL;IPD:MHC04581
IPD:MHC04581 Mane-DRB*W2:09 177 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALAG DTRPRFLGHA KSECHFFNGT
 ERVRFLQRYI YNQEEFVRFD SDVGEFRAVT ELGRPVAESW NSRKDFLERE
 RAQVDTCRHN YGVGESFTVQ RRVQPKVTVY PAKTQPLQHH TLLVCSVSGF
 YPGSIEVRWF RNGQEEKAGV VSTGLIQ*  
>DL;IPD:MHC04582
IPD:MHC04582 Mane-DRB*W2:10 177 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLAVAG DTRPRFLGHA KSECHFFNGT
 ERVRFLQRYI YNQEELVRFD SDVGEFRAVT ELGRPVAESW NSRKDFLERE
 RAQVDTCRHN YGVGESFTVQ RRVQPKVTVY PAKTQPLQHH NLLVCSVSGF
 YPGSIEVRWF RNGQEEKAGV VSTGLIQ*  
>DL;IPD:MHC04583
IPD:MHC04583 Mane-DRB*W2:11 177 bases
 MVCLRLPGGS CMAPLTVTLM VLSSPLALAG DTRPHFLDQV KYECHFFNGT
 ERVRLLGRHF YNQEELVRFD SDVGEYRAVS ELGRPDAENL NARKDFLEQA
 RAQVDTCRHN YGVVESFTVQ RRVQPKVTVY PAKTQPLQHH TLLVCSVNGF
 YPGSIEVRWF RNGQEEKAGV ASTGLIQ*  
>DL;IPD:MHC03459
IPD:MHC03459 Mane-DRB*W31:01 177 bases
 MVCLKLPGGS WMAALTVTLM VLSSPLALAG DTRPRFLEYA KGECHFFNGT
 ERVRYLERYI YNQEENVRFD SDVGEFRAVT ELGRPDAEYW NSQKDVLEQR
 RAVVDTCRYD YGIAESFTVQ RRVKPKVTVY PAKTQPLQHH NLLVCSVSGF
 YPGSIEVRWF RNGQEEKAGV VSTGLIQ*  
>DL;IPD:MHC04584
IPD:MHC04584 Mane-DRB*W33:01 178 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALAG DTQPRFLEQA KSECHFFNGT
 ERVRFLDRYI HNQEENLRFD SDVGEFRAVT ELGRPDAEYW NSQKDFLEQR
 RAAVDTYCRH NYGAVESFTV QRRVQPKVTV YPAKTQPLQH HTLLVCSVSG
 FYPGTIEVRW FRNGQEEKTG VVSTGLIQ*  
>DL;IPD:MHC03502
IPD:MHC03502 Mane-DRB*W3:01 75 bases
 KRECHFFNGT ERVRFLDRYF HNQEEYARFD SDVGEFWAVT ELGRRSAEYW
 NSQKDFLEQA RTAVDNYCRH NYGVG*  
>DL;IPD:MHC04585
IPD:MHC04585 Mane-DRB*W3:02 178 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALAG DTRPRFLEQA KRECHFFNGT
 ERVRFLDRYF HNQEEYARFD SDVGEFRAVT ELGRRSAEYW NSQKDFLEQA
 RTAVDNYCRH NYGVGESFTV QRRVQPKVTV YPEKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQ*  
>DL;IPD:MHC04589
IPD:MHC04589 Mane-DRB*W3:03 178 bases
 TLCLKLPGGS CMAALTVTLM VLSSPLALAG DTRPRFLEQA KRECHFFNGT
 ERVRFLDRYF HNQEEYARFD SDVGEFRAVT ELGRRSAEYW NSQKDFLEQA
 RTAVDNYCRH NYGVGESFTV QRRVQPKVTV YPEKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNSQEEKAG VVSTGLIQ*  
>DL;IPD:MHC04590
IPD:MHC04590 Mane-DRB*W3:04 178 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALAG DTRPRFLEQA KRECHFFNGT
 ERVRFLDRYF HNQEEYARFD SDVGEFRAVT ELGRRSAEYW NSQKDFLEQA
 RTAVDNYCRH NYGVGESFTV QRRVQPKVTV YPEKTQPLQH HTLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQ*  
>DL;IPD:MHC03985
IPD:MHC03985 Mane-DRB*W4:01 75 bases
 KPECHFFNGT ERVRFLERHF YNQEENLRFD SDVGEYRAVS ELGRPEAQSW
 NSQKDFLEQR RAAVDTYCRH NYRIG*  
>DL;IPD:MHC03509
IPD:MHC03509 Mane-DRB*W5:01 178 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALAG DTRPRFLEQA KSECHFFNGT
 ERVRYLDRYI YNQEEYVRFD SDVGEHRAVT ELGRPDAEYW NSQKDFLEDQ
 RAAVDNYCRH NYGVGESFTV QRRVQPKVTV YPAKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQ*  
>DL;IPD:MHC03896
IPD:MHC03896 Mane-DRB*W5:02 75 bases
 KSECHFFNGT ERVRFLDRYI YNQEEYVRFD SDVGEHRAVT ELGRPDAEYW
 NSQKDFLEDQ RAAVDNYCRH NYGVG*  
>DL;IPD:MHC03904
IPD:MHC03904 Mane-DRB*W63:01 75 bases
 KRECHFFNGT ERVRFLDRYF YNQEEFVRFD SDVGEFRAVT ELGRPVAENL
 NSRKDYLEQA RAAVDNYCRY NYGVG*  
>DL;IPD:MHC03905
IPD:MHC03905 Mane-DRB*W63:02 75 bases
 KRECHFFNGT ERVRFLDRYF YNQEEFVRFD SDVGEFRAVT ELGRPVAENL
 NSQKDYLEQA RAAVDNYCRY NYGVG*  
>DL;IPD:MHC03922
IPD:MHC03922 Mane-DRB*W64:01 75 bases
 KVECHFFNGT ERVRFLERYF YNQEEYVRFD SDVGEYRAVS ELGRRSAEYW
 NGQKDILERA RAAVDTYCRH NYRIG*  
>DL;IPD:MHC03919
IPD:MHC03919 Mane-DRB*W65:01 24 bases
 KAEYHFFNGT ERVRYLERYI YNQX*  
>DL;IPD:MHC03984
IPD:MHC03984 Mane-DRB*W67:01 75 bases
 KPECHFFNGT ERVRYLVRYI YNQEEFVRFD SDVGEFRAVS ELGRPVAESW
 NGQKDLLEQR RAEVDTVCRH NYGVG*  
>DL;IPD:MHC03450
IPD:MHC03450 Mane-DRB*W69:01 75 bases
 KYECHFFNGT ERVRFLERHF YNQEEFVRFD SDVGEFRAVT ELGRPDAEYW
 NSQKDLLEDR RAQVDTVCRH NYGVG*  
>DL;IPD:MHC03501
IPD:MHC03501 Mane-DRB*W69:02 75 bases
 KYECHFFNGT ERVRFLERHF YNQEEFVRFD SDVGEYRAVT ELGRPDAEYW
 NSQKDLLEDR RAQVDTVCRH NYGVG*  
>DL;IPD:MHC03451
IPD:MHC03451 Mane-DRB*W6:01 178 bases
 MVCLKLPGGS CMAALTATLM VLSSPLALAG DTGPRFLKQA KAECHFFNGT
 ERVRFLERHF YNQEEYVRFD SDVGEFRAVT ELGRRSAEYF NSQKGYLEQR
 RAAVDTYCRH NYGVVESFTV QRRVQPKVTV YPAKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNDQEEKAG VVSTGLIQ*  
>DL;IPD:MHC03508
IPD:MHC03508 Mane-DRB*W6:02 75 bases
 KAECHFFNGT ERVRLLDRHF YNQEEYVRYD SDVGEYRAVT ELGRRSAEYW
 NSQKDYLEQR RAAVDTYCRH NYRIG*  
>DL;IPD:MHC03992
IPD:MHC03992 Mane-DRB*W74:01:01 75 bases
 KHECHFFNGT ERVRFLDRYF HNQEEFVRFD SDVGEYRAVT ELGRPDAQSW
 NSQKDILEDA RAAVDTYCRY NYGVV*  
>DL;IPD:MHC04586
IPD:MHC04586 Mane-DRB*W74:01:02 178 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALAG DTRPRFLEQV KHECHFFNGT
 ERVRFLDRYF HNQEEFVRFD SDVGEYRAVT ELGRPDAQSW NSQKDILEDA
 RAAVDTYCRY NYGVVESFTV QRRVQPKVTV YPAKTQPLQH HNLLVCSVNG
 FYPGTIEVRW FRNGQKEKAG VVSTGLIQ*  
>DL;IPD:MHC00628
IPD:MHC00628 Mane-DRB1*03:01 89 bases
 RFLEYSTSEC HFFNGTERVR FLDRYFYNQE EYVRFDSDVG EYRAVSELGR
 RSAEYWNGQK DILEDARAAV DTYCRHNYRI GESFTVQRR* 
>DL;IPD:MHC03457
IPD:MHC03457 Mane-DRB1*03:02 178 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALAG DTRPRFLEYS TSECHFFNGT
 ERVRYLDRYF YNQEEDVRFD SDVGEYRAVS ELGRPVAEYW NSQKDILEDQ
 RASVDTFCRH NYRVAESFTV QRRVQPKVTV YPSKTQPLQH HTLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQ*  
>DL;IPD:MHC03458
IPD:MHC03458 Mane-DRB1*03:03 75 bases
 TSECHFFNGT ERVRYLDRYF YNQEENVRFD SDVGEYRAVT ELGRPDAEYW
 NGQKDILEDQ RASVDTYCRH NYRVA*  
>DL;IPD:MHC03460
IPD:MHC03460 Mane-DRB1*03:04 75 bases
 TSECHFFNGT ERVRYLDRYF YNQEENVRFD SDVGEYRAVS ELGRPDAEYW
 NSQKDILEQK RARVDNYCRH NYGVF*  
>DL;IPD:MHC03461
IPD:MHC03461 Mane-DRB1*03:05 75 bases
 TSECHFFNGT ERVRFLDRYF YNQEEYVRFD SDVGEYRAVT ELGRRSAEYW
 NGQKDILEDA RAAVDTYCRH NYRIG*  
>DL;IPD:MHC03462
IPD:MHC03462 Mane-DRB1*03:06 75 bases
 TSECHFFNGT ERVRFLDRYF YNQEEYVRFD SDVGEYRAVT ELGRRSAEYW
 NGQKDILEDA RAAVDTYCRH NYGVF*  
>DL;IPD:MHC03463
IPD:MHC03463 Mane-DRB1*03:07 75 bases
 TSECHFFNGT ERVRYLDRYF YNQEEYVRFD SDVGEYRAVS ELGRPDAEYF
 NSQKDILEQK RARVDNYCRH NYRVG*  
>DL;IPD:MHC03464
IPD:MHC03464 Mane-DRB1*03:08 75 bases
 TSECHFFNGT ERVRYLDRYF YNQEENVRFD SDVGEYRAVT ELGRPDAEYW
 NSQKDILEQK RARVDNYCRH NYGVF*  
>DL;IPD:MHC03891
IPD:MHC03891 Mane-DRB1*03:09 75 bases
 TSECHFFNGT ERVRFLDRYF YNQEEYVRFD SDVGEFRAVT ELGRRSAEYW
 NGQKDILEDA RAAVDTYCRH NYRIG*  
>DL;IPD:MHC03894
IPD:MHC03894 Mane-DRB1*03:10 178 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALTG DIRPRFLEYS TSECHFFNGT
 ERVRFLDRYF YNQEEYVRFD SDVGEYRAVT ELGRPDAEYW NGQKDFLEDR
 RASVDNYCRH NYGVVESFTV QRRVQPKVTV YPSKIQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIH*  
>DL;IPD:MHC03900
IPD:MHC03900 Mane-DRB1*03:11 75 bases
 TSECHFFNGT ERVRYLDRYF YNQEEYVRFD SDVGEHRAVS ELGRPDAEYW
 NSQKDILEDQ RASVDTFCRH NYRVA*  
>DL;IPD:MHC03895
IPD:MHC03895 Mane-DRB1*03:12 75 bases
 TSECHFFNGT ERVRFLERYF YNQEENVRFD SDVGEYRAVS ELGRPDAEYW
 NGQEDILELK RGQVDNYCRH NYGVF*  
>DL;IPD:MHC03892
IPD:MHC03892 Mane-DRB1*03:13 178 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALAG DTRPRFLEYS TSECHFFNGT
 ERVRFLDRYF YNQEENVRFD SDVGEFRAVS ELGRPDAENW NSRKDILERE
 RAAVDNYCRY NYRVGESFTV QRRVQPKVTV YPAKTQPLQH HTLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIH*  
>DL;IPD:MHC03893
IPD:MHC03893 Mane-DRB1*03:14 75 bases
 TSECHFFNGT ERVRFLDRYF YNQEEYVRFD SDVGEYRAVS ELGRPDAENW
 NSRKDILERA RAAVDTYCRH NYGAV*  
>DL;IPD:MHC03901
IPD:MHC03901 Mane-DRB1*03:15 178 bases
 MVCLKLPGGS CMATLTVTLM VLSSPLALAG DTRPRFLEYS TSECHFFNGT
 ERVRFLDRYF YNQEENLRFD SDVGEFRAVS ELGRPDAEYW NSQKDFLEQR
 RAAVDNYCRY NYRVGESFTV QRRVQPKVTV YPAKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIH*  
>DL;IPD:MHC03990
IPD:MHC03990 Mane-DRB1*04:01 178 bases
 MVCLKLPGGS CMAALTMTLM VLSSPLALAG DTRARFLEQV KHECHFFNGT
 ERVRFLDRYF YNQEEYVRFD SDVGEYRAVT ELGRRSAEYW NGQKDLLEQK
 RAAVDTYCRY NYGVAESFTV QRRVQAKVTV YPAKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQ*  
>DL;IPD:MHC03994
IPD:MHC03994 Mane-DRB1*04:02 178 bases
 MVCLKLPGGS CMAALTMTLM VLSSPLALAR DTRARFLEQV KHECHFFNGT
 ERVRFLDRYF YNQEEYVRFD SDVGEYRAVT ELGRRSAEYW NSQKDILEDR
 RAVVDTYCRH NYGVGESFTV QRRVQAKVTV YPAKTQPLQH HTLLVCSVNG
 FYPGSVEVRW FRNGQEEKAG VVSTGLIQ*  
>DL;IPD:MHC04591
IPD:MHC04591 Mane-DRB1*04:03 178 bases
 MVCLKLPGGS CMAALTMTLM VLSSPLALAG DTRARFLEQV KHECHFFNGT
 ERVRFLDRYF YNQEEYVRFD SDVGEYRAVT ELGRRSAEYW NGQKDLLEQK
 RAAVDNYCRY NYGVAESFTV QRRVQAKVTV YPAKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQ*  
>DL;IPD:MHC03906
IPD:MHC03906 Mane-DRB1*07:01 75 bases
 KAKCHFFNGT ERVRYLQRHF YNQEEFVRFD SDVGEFRAVT ELGRPVAENW
 NSQKDFLEQR RASVDNYCRH NYRGV*  
>DL;IPD:MHC03908
IPD:MHC03908 Mane-DRB1*10:01 75 bases
 KFECHFFNGT ERVRFLIRVF HNREEYARFD SDVGEFRAVT ELGRPAAEYL
 NSQKDFLEEK RAAVDTYCRH NYRIG*  
>DL;IPD:MHC03909
IPD:MHC03909 Mane-DRB1*10:02 75 bases
 KFECHFFNGT ERVRFLIRVF YNREEYVRFD SDVGEFRAVT ELGRLSAEYF
 NSQKDFLEQK RASVDTYCRH NYGAV*  
>DL;IPD:MHC03910
IPD:MHC03910 Mane-DRB1*10:03 75 bases
 KFECHFFNGT ERVRFLIRVF YNREEYASFD SDVGEFRAVT ELGRPDAKYW
 NSQKDFLEEK RAAVDTYCRH NYRVG*  
>DL;IPD:MHC03931
IPD:MHC03931 Mane-DRB1*10:04 178 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALAG DTQSRFLEQV KFECHFFNGT
 ERVRFLERRV HNQEEYARFD SDVGEYRAVT ELGRPDAEYW NGQKDLLEDR
 RAQVDTVCRH NYRVGESFTV QRRVQPKVTV YPAKTQPLQH HTLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQ*  
>DL;IPD:MHC04592
IPD:MHC04592 Mane-DRB1*10:05 178 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALAG DTRPRFLEQV KFECHFFNGT
 ERVRYLVRFF YNREEYARFD SHVGEFRAVT QLGRPDAEYW NSQKDILERK
 RAEVDTVCKH NYGVVESFTV QRRVQPKVTV YPAKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQ*  
>DL;IPD:MHC03511
IPD:MHC03511 Mane-DRB3*04:01 75 bases
 KSECHFFNGT ERVRYLQRHF YNQEEFVRFD SDVGEFRAVS ELGRPVAESW
 NSQKDYLEQR RAAVDNYCRY NYQVG*  
>DL;IPD:MHC03506
IPD:MHC03506 Mane-DRB3*04:02 178 bases
 MVFLKLPGGS CMAALTVTLM VLSSPLALAG DTRPRFLEQG KSECHFFNGT
 ERVRYLQRHF YNQEEFVRFD SDVGEFRAVS ELGRPVAEYW NSQKDYLEQR
 RAQVDNYCRY NYRVGESFTV QRRVQPKVTV YPEKTQPLQH HTLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQ*  
>DL;IPD:MHC03507
IPD:MHC03507 Mane-DRB3*04:03 178 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALAG DTRPRFLEQG KSECHFFNGT
 ERVRYLQRYF YNQEEFVRFD SDVGEFRAVS ELGRPDAEYF NSQKDFLEQR
 RAQVDNYCRY NYRVGESFTV QRRVQPKVTV YPSKTQPLQH HTLLVCSVSG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQ*  
>DL;IPD:MHC03911
IPD:MHC03911 Mane-DRB3*04:04 75 bases
 KSECHFFNGT ERVRYLQRHF YNQEEFVRFD SDVGEFRAVS ELGRPVAESW
 NSQKDYLEQR RAQVDNYCRY NYRVG*  
>DL;IPD:MHC03453
IPD:MHC03453 Mane-DRB5*01:01 178 bases
 MVCLRFPGGS CMAALTVTLM VLSSPLALAG DTQPRFLKQD MHECHFFNGT
 ERVRYLHRDI YNQEEDLRFD SDVGEYRAVT ELGRPDAEYW NSQKDILEDA
 RAAVDTYCRH NYGVVESFTV QRRVQPKVTV YPAKTQALQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQ*  
>DL;IPD:MHC03505
IPD:MHC03505 Mane-DRB5*01:02 73 bases
 ECHFFNGTER VRYLHRDIYN QEEDLRFDSD VGEYRAVTEL GRPDAEYWNS
 QKDILERRRA AVDTYCRHNY GVV*  
>DL;IPD:MHC03510
IPD:MHC03510 Mane-DRB5*01:03 178 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALAG DTRPRFLKQD KYECHFFNGT
 ERVRFLHRDI YNQEEDLRFD SDVGEYRAVT ELGRPDAEYW NSQKDILEDA
 RAAVDTYCRH NYGVVESFTV QRRVQPKVTV YPAKTQALQH HTLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQ*  
>DL;IPD:MHC03452
IPD:MHC03452 Mane-DRB5*03:01 178 bases
 MVCLRFPGGS CMAALTVTLM VLSSPLALAG DTQPRFLKQD KYECHFFNGT
 ERVRFLHRDI HNQEEDARFD SDVGEYRAVS ELGRLSAEYF NSQKDVLERR
 RAEVDTVCRH NYRGVESFTV QRRVEPKVTV YPAKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIH*  
>DL;IPD:MHC03504
IPD:MHC03504 Mane-DRB5*03:02 75 bases
 KYECHFFNGT ERVRFLHRYI YNQEEDARFD SDVGEYRAVS ELGRLSAEYF
 NSQKDVLERR RAEVDTVCRH NYRGV*  
>DL;IPD:MHC03912
IPD:MHC03912 Mane-DRB5*03:03 75 bases
 KYECHFFNGT ERVRFLHRDI HNQEEDLRFD SDVGEYRAVT ELGRPDAESW
 NSRKDILEDR RAAVDTFCRH NYGVG*  
>DL;IPD:MHC03454
IPD:MHC03454 Mane-DRB6*01:01 75 bases
 KCECHIFNGT ERVQYLNRNI HKREENLRFH SDLGEFQAVT ELGRPVAENW
 NSRMGILEEK RDKVDIYCRY NYGVF*  
>DL;IPD:MHC03455
IPD:MHC03455 Mane-DRB6*01:02 75 bases
 KCECHIFNGT ERVQYLNRNI HKREENLRFH SDLGEFQAVT ELGRPVAENW
 NSRMGILEEK RDKVDTYCRY NYGVF*  
>DL;IPD:MHC03456
IPD:MHC03456 Mane-DRB6*01:03 76 bases
 KCECHFFNGT ERVQYLNRNI HKREENLRFH SDLGEFQAVT ELEWPPVAEN
 WNSQKGILEE KRDKGDTYCI NNYGVL*  
>DL;IPD:MHC03503
IPD:MHC03503 Mane-DRB6*01:04 72 bases
 KSECQIFNGR ERVRYLNRYI HKREENLRFD SDVGEFQAVT ELGRPVAENW
 NSQKGILEEK RDKVDTYCRY NX*  
>DL;IPD:MHC03890
IPD:MHC03890 Mane-DRB6*01:05 63 bases
 KCECHFFNGT ERMQYLNRYI HKREENLRFH SDVGEFQAVT QLERPVAENW
 NSRMGILEEK RDX*   
>DL;IPD:MHC03898
IPD:MHC03898 Mane-DRB6*01:06 54 bases
 KCECPIFNGT EPVQYLNRYI HKREENLRYN SDLGEFQAVT ELGWPVTELQ
 LWGF*    
>DL;IPD:MHC03899
IPD:MHC03899 Mane-DRB6*01:07 76 bases
 KCECHFFNGT ERVQYLNRNI HKREENLRFH SDLGEFQAVT ELEWPPVAEN
 WNSQKGILEE KRDKGDTYCI NNYGVF*  
>DL;IPD:MHC03902
IPD:MHC03902 Mane-DRB6*01:08 54 bases
 KCECHIFNGT ERVRYLNRNI HKQEENLRFH SDVGEFQAVT ELGWPVTELQ
 LWGF*    
>DL;IPD:MHC03903
IPD:MHC03903 Mane-DRB6*01:09 54 bases
 KCECHIFNGT ERVRYLNRNI HKQEENLRFH SDVGEFQAVT ELGWPVTELQ
 LWGF*    
>DL;IPD:MHC03907
IPD:MHC03907 Mane-DRB6*01:10 76 bases
 KYECHIFNGT ERVQYLNRNI HKGEKNLRFQ SDVGEFQAVT EPEWPPVAEN
 WNSQKGILEE KQDKVDTYCR NNYGVF*  
>DL;IPD:MHC03923
IPD:MHC03923 Mane-DRB6*01:11 54 bases
 KCECHIFNGS EQVQYLNRNI HKRGENLGFH SDVGEFQAVT QLGRPVTELQ
 LPGF*    
>DL;IPD:MHC03924
IPD:MHC03924 Mane-DRB6*01:12 54 bases
 KCECPIFNGT EWVQYLNRNI HKREENLRFH SDVGEFQAVM ELGRPVTELQ
 LWGF*    
