>DL;IPD:MHC02211
IPD:MHC02211 Mane-E*02:01 360 bases
 MALGNLLLLL SALTKTWAGS HSLKYFHTSV SRPGRGEPRF ISVGYVDDTQ
 FVRYDSDAAS PRMEPRAPWV EQEGPEYWDQ ETRSARDTAQ TFRVNLKTLR
 GYYNQSEAGS HTLQWMHGCD LGPDGRFLRG YEQFAYDGKD YLTLNEDLRS
 WSAVDTAAQI SERKSNDGSE AEHQRAYLED TCVEWLRRYL ENGKETLQRP
 DPPKTHVTHH PISDHEATLR CWALGFYPAE ITVTWQQDGE DQTQDTELVE
 TRPAGDGTFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPLTL RWEPPSQHSI
 PIVGIIAGLV LLGAVVTGAV VAAVMWRSNS SGRKGWSYSQ AVCSDSAQGS
 DESLTACKAX *   
>DL;IPD:MHC02212
IPD:MHC02212 Mane-E*02:02 314 bases
 HTSVSRPGRG EPRFISVGYV DDTQFVRYDS DAASPRMEPR APWVEQEGPE
 YWDQETRSAR DTAQTFRVNL KTLRGYYNQS EAGSHTLQWM HGCDLGPDGR
 FLRGYEQFAY DGKDYLTLNE DLRSWSAVDT AAQISERKSN DGSEAEHQRA
 YLEDTCVEWL RRYLENGKET LQRPDPPKTH VTHHPISDHE ATLRCWALGF
 YPAEITVTWQ QDGEDQTQDT ELVETRPAGD GTFQKWAAVV VPSGEEQRYT
 CHVQHEGLPE PLTLRWEPPS QHSISIVGII AGLVLLGAVV TGAVVAAVMW
 RSNSSGRKGW SYSQ*   
>DL;IPD:MHC02213
IPD:MHC02213 Mane-E*02:03 314 bases
 HTSVSRPGRG EPRFISVGYV DDTQFVRYDS DAASPRMEPR APWVEQEGPE
 YWDQETRSAR DTAQTFRVNL KTLRGYYNQS EAGSHTLQWM HGCDLGPDGR
 FLRGYEQFAY DGKDYLTLNE DLRSWSAVDT AAQISERKSN DGSEAEHQRA
 YLEDTCVEWL RRYLENGKET LQRSDPPKTH VTHHLISDHE ATLRCWALGF
 YPAEITVTWQ QDGEDQTQDT ELMETRPAGD GTFQKWAAVV VPSGEEQRYT
 CHVQHEGLPE PLTLRWEPPS QHSIPIVGII AGLVLLGAVV TGAVVAAVMW
 RRNSSGRKGW SYSQ*   
>DL;IPD:MHC02214
IPD:MHC02214 Mane-E*02:04 360 bases
 MALRTLLLLL SALTKTWAGS HSLKYFHTSV SRPGCGGPRF ISVGYVDDTQ
 FVRYDSDAAS PRMEPRAPWV EQEGPEYWDQ ETRSARDTAQ TFRVNLETLR
 GYYNQSEAGS HTLQWMHGCD LGSDGRFLRG YEQFAYDGKD YLTLNEDLRS
 WSAVDTAAQI SEQKSNDGSE AEHQRAYLED TCVEWLHRYL ENGKETLQRS
 EPPKTHVAHH PVSDHEATLR CWALGFYPAE ITVTWQRDGE DQTQDTELVE
 TRPAGDGTFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPLTL RWEPSSQSTI
 PIVGIIAGLV LLGAVVTGAV IVAVMCRRKS SGRKGGSYSQ ASCSDSTQGS
 DESLTACKAX *   
>DL;IPD:MHC02215
IPD:MHC02215 Mane-E*02:05 333 bases
 HTSVSRPGRG GPRFISVGYV DDTQFVRYDS DAASPRMEPR APWVEQEGPE
 YWDQETRSAR DTAQTFRVNL ETLRGYYNQS EAGSHTLQWM HGCDLGSDGR
 FLRGYEQFAY DGKDYLTLNE DLRSWSAVDT AAQISEQKSN DGSEAEHQRA
 YLEDTCVEWL HRYLENGKET LQRSEPPKTH VAHHPVSDHE ATLRCWALGF
 YPAEITVTWQ RDGEDQTQDT ELVETRPAGD GTFQKWAAVV VPSGEEQRYT
 CHVQHEGLPE PLTLRWEPSS QSTIPIVGII AGLVLLGAVV TGAVIVAVMC
 RRKSSGRKGG SYSQASCSDS TQGSDESLTA CKA* 
>DL;IPD:MHC02216
IPD:MHC02216 Mane-E*02:06 360 bases
 MALRTLLLLL SALTETWAGS HSLKYFHTSV SRPGGGGPRF ISVGYVDDTQ
 FVRYDSDAAS PRMEPRALWM KQEGPEYWDQ ETRSARDTAQ TFRVNLETLR
 GYYNQSEAGS HTLQWMHGCD LGPDGRFLRG YEQFAYDGKD YLTLNEDLRS
 WSAVDTAAQI SEQKSNDGSE AEHQRAYLED TCVEWLHRYL ENGKETLQRS
 ESPKTHVTHH PVSDHEATLR CWALGFYPAE ITVTWQRDGE DQTQDTELVE
 TRPAGDGTFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPLTL RWEPSSQSTI
 PIVGIIAGLV LLGAVVTGAV VAAVMWRRKS SGRKGWSYSQ AVCSDSSQGS
 DDSLTAYKPX *   
>DL;IPD:MHC02217
IPD:MHC02217 Mane-E*02:07 347 bases
 ALTKTWAGSH SLKYFHTSVS RPGRGEPRFI SVGYVDDTQF VRYDSDAASP
 RMEPRALWMK QEGPEYWDQE TRSARDTAQT FRVNLKTLRG YYNQSEAGSH
 TLQWMHGCDL GPDGRFFRGY EQFAYDGKDY LTLNEDLRSW SAVDTAAQIS
 EQKSNDGSEA EHQRAYLEDT CVEWLRRYLE NGKETLLRSE SPKTHVTRHP
 VSDHEATLRC WALGFYPAEI TVTWQRDGED QTQDTELVET RPAGDGTFQK
 WAAVVVPSGE EQRYTCHVQH EGLPEPLILR WEPSSQSSIP IVGIIVGLVL
 LGAVVTGAVV AAVMWRKSSG RKGRSYSQAS CSDSAQGSDE SLTAYKA*
>DL;IPD:MHC02218
IPD:MHC02218 Mane-E*02:08 333 bases
 HTSVSRPGGG GPRFISVGYV DDTQFVRYDS DAASPRMQPR ALWMKQEGPE
 YWDQETRSAR DTAQAFRVNL NTLRGYYNQS EAGSHTLQWM YGCDLGPDGR
 FLRGYEQFAY DGKDYLTLNE DLRSWSAVDT AAQISAQKSN DGSEAEHQRA
 YLEDTCVEWL HRYLENGKET LQRSESPKTH VTHHPISDHE ATLRCWALGF
 YPAEITVTWQ RDGEDQTQDT ELVETRPAGD GTFQKWAAVV VPSGEEQRYT
 CHVQHEGLPE PLTLRWEPSS WSTIPIVGII AGLVLLGAVV TGAVVAAVMW
 RRKSSGRKGG SYSQASCSNS TQGSDESLTA YKT* 
