>DL;IPD:MHC04359
IPD:MHC04359 Mane-AG*03:01 822 bases
 GCTCGCACTC CATGAGGTAT TTCTACACCG CCGTGTCCCG GCCCGGCCGC
 GGGCAGCCCC GCTTCATCGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCG AGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGGTGGAGCA GGAGGGTCCA GAGTATTGGG ACCGGGAGAC ACAGAACATG
 AAGACCGCGA CACAGACCTA CCGAGAGAAC CTGCGGACCC TGCTCCGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC CGTCCAGAAG ATGTACGGCT
 GCGACCTGGG GCCAGACGGG CGCCTCCTCC GCGGGTATGA ACAGTTCGCC
 TACGACGGCA GGGATTACAT CATCCTGAAC GAGGACCTGC GCTCCTGGAC
 GGCCGCGGAC ATGGCGGCTC AGAACACCCA GCGCAAGTGG GAGGCGGCGG
 GTGCGGCGGA GCAGCACAGA ACCTACCTGG AGGGCGAGTG CCTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGGACCC
 CCCCAAGACA AATGTGACCC ACCACCCTGT CTCTGACTAC GAGGCCACCC
 TGAGGTGTTG GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG
 CAGCGGGATG GAGAGGAACA AACTGAGGAC ACAGAGCTCG TGGAGACCAG
 GCCTACAGGG GATGGAACCT TCCAGAAGTG GGCGGCTGTG GTGGTGCCTT
 CTGGAGAGGA GCAGAGATAC ACCTGTCATG TGCAACATGA GGGTCTGCCC
 GAGCCCCTCA CCTTGAGATG GG*  
