>DL;IPD:MHC05161
IPD:MHC05161 Mane-DRA*01:01 255 bases
 MAESGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD
 FDGDEIFHVD MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK
 RSNNTPITNV PPEVTVLTNS PVELGEPNVL ICFIDKFSPP VVKVTWLKNG
 KPVTTGVSET VFLPREDHLF RKFHYLPFLP STEDIYDCKV EHWGLDAPLL
 KHWEFDAPSP LPETTENVVC ALGLIVGLVG IIIGTVFIIK GVRKSNAAER
 RGPLX*    
>DL;IPD:MHC05153
IPD:MHC05153 Mane-DRA*01:02:01 255 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD
 FDGDEIFHVD MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK
 RSNNTPITNV PPEVTVLTNS PVELGEPNVL ICFIDKFSPP VVKVTWLKNG
 KPVTTGVSET VFLPREDHLF RKFHYLPFLP STEDIYDCKV EHWGLDAPLL
 KHWEFDAPSP LPETTENVVC ALGLIVGLVG IIVGTVFIIK GVRKSNAAER
 RGPLX*    
>DL;IPD:MHC05154
IPD:MHC05154 Mane-DRA*01:02:02 255 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD
 FDGDEIFHVD MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK
 RSNNTPITNV PPEVTVLTNS PVELGEPNVL ICFIDKFSPP VVKVTWLKNG
 KPVTTGVSET VFLPREDHLF RKFHYLPFLP STEDIYDCKV EHWGLDAPLL
 KHWEFDAPSP LPETTENVVC ALGLIVGLVG IIVGTVFIIK GVRKSNAAER
 RGPLX*    
>DL;IPD:MHC05158
IPD:MHC05158 Mane-DRA*01:03:01 255 bases
 MAVSGVPVLG FFIIAMLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD
 FDGDEIFHVD MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK
 RSNNTPITNV PPEVTVLTNS PVELGEPNVL ICFIDKFSPP VVKVTWLKNG
 KPVTTGVSET VFLPREDHLF RKFHYLPFLP STEDIYDCKV EHWGLDAPLL
 KHWEFDAPSP LPETTENVVC ALGLIVGLVG IIVGTVFIIK GVRKSNAAER
 RGPLX*    
>DL;IPD:MHC05159
IPD:MHC05159 Mane-DRA*01:03:02 255 bases
 MAVSGVPVLG FFIIAMLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD
 FDGDEIFHVD MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK
 RSNNTPITNV PPEVTVLTNS PVELGEPNVL ICFIDKFSPP VVKVTWLKNG
 KPVTTGVSET VFLPREDHLF RKFHYLPFLP STEDIYDCKV EHWGLDAPLL
 KHWEFDAPSP LPETTENVVC ALGLIVGLVG IIVGTVFIIK GVRKSNAAER
 RGPLX*    
>DL;IPD:MHC05160
IPD:MHC05160 Mane-DRA*01:04 255 bases
 MAESGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD
 FDGDEIFHVD MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK
 RSNNTPITNV PPEVTVLTNS PVELGEPNVL ICFIDKFSPP VVKVTWLKNG
 KPVTTGVSET VFLPREDHLF RKFHYLPFLP STEDIYDCKV EHWGLDAPLL
 KHWEFDAPSP LPETTENVVC ALGLIVGLVG IIVGTVFIIK GVRKSNAAER
 RGPLX*    
>DL;IPD:MHC05155
IPD:MHC05155 Mane-DRA*01:05 255 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD
 FDGDEIFHVD MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK
 RSNNTPITNV PPEVTVLTNS PVELGEPNVL ICFIDKFSPP VVKVTWLKNG
 KPVTTGVSET VFLPREDHLF RKFHYLPFLP STEDIYDCKV EHWGLDVPLL
 KHWEFDAPSP LPETTENVVC ALGLIVGLVG IIVGTVFIIK GVRKSNAAER
 RGPLX*    
>DL;IPD:MHC05156
IPD:MHC05156 Mane-DRA*01:06:01 255 bases
 MAVSGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD
 FDGDEIFHVD MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK
 RSNNTPITNV PPEVTVLTNS PVELGEPNVL ICFIDKFSPP VVKVTWLKNG
 KPVTTGVSET VFLPREDHLF RKFHYLPFLP STEDIYDCKV EHWGLDAPLL
 KHWEFDAPSP LPETTENVVC ALGLIVGLVG IIVGTVFIIK GVRKSNAAER
 RGPLX*    
>DL;IPD:MHC05157
IPD:MHC05157 Mane-DRA*01:06:02 255 bases
 MAVSGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD
 FDGDEIFHVD MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK
 RSNNTPITNV PPEVTVLTNS PVELGEPNVL ICFIDKFSPP VVKVTWLKNG
 KPVTTGVSET VFLPREDHLF RKFHYLPFLP STEDIYDCKV EHWGLDAPLL
 KHWEFDAPSP LPETTENVVC ALGLIVGLVG IIVGTVFIIK GVRKSNAAER
 RGPLX*    
>DL;IPD:MHC05162
IPD:MHC05162 Mane-DRA*02:01:01 255 bases
 MAASGVPVLG FFITAVLMSA QESWAIKEDH VIIQAEFYLN PDQSGEYMFD
 FDGDELFHVD MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK
 RSNNTPITNV PPEVTVLTNS PVELGEPNVL ICFIDKFSPP VVKVTWLKNG
 KPVTTGVSET VFLPREDHLF RKFHYLPFLP STEDIYDCKV EHWGLDAPLL
 KHWEFDAPSP LPETTENVVC ALGLIVGLVG IIVGTVFIIK GVRKSNAAER
 RGPLX*    
>DL;IPD:MHC05163
IPD:MHC05163 Mane-DRA*02:01:02 255 bases
 MAASGVPVLG FFITAVLMSA QESWAIKEDH VIIQAEFYLN PDQSGEYMFD
 FDGDELFHVD MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK
 RSNNTPITNV PPEVTVLTNS PVELGEPNVL ICFIDKFSPP VVKVTWLKNG
 KPVTTGVSET VFLPREDHLF RKFHYLPFLP STEDIYDCKV EHWGLDAPLL
 KHWEFDAPSP LPETTENVVC ALGLIVGLVG IIVGTVFIIK GVRKSNAAER
 RGPLX*    
