>DL;IPD:MHC02211
IPD:MHC02211 Mane-E*02:01 1080 bases
 ATGGCACTAG GAAATCTACT TCTCCTGCTC TCGGCCCTTA CCAAGACCTG
 GGCGGGCTCC CACTCCTTGA AGTATTTCCA CACTTCCGTG TCCCGGCCCG
 GCCGCGGGGA GCCCCGCTTC ATCTCCGTGG GCTACGTGGA CGACACCCAG
 TTCGTGCGGT ACGACAGCGA TGCCGCGAGT CCGAGGATGG AGCCGCGGGC
 GCCGTGGGTG GAGCAGGAGG GGCCGGAGTA TTGGGACCAG GAGACACGGA
 GCGCCAGGGA CACCGCACAG ACTTTCCGAG TGAACCTGAA GACCCTGCGC
 GGCTACTACA ACCAGAGCGA GGCCGGGTCT CATACCCTCC AGTGGATGCA
 TGGCTGCGAC CTGGGGCCCG ACGGGCGCTT CCTCCGCGGA TATGAACAGT
 TCGCCTACGA CGGCAAGGAT TATCTCACCC TGAATGAGGA CCTGCGCTCC
 TGGTCCGCGG TGGACACGGC GGCTCAGATT TCCGAGCGAA AGTCAAATGA
 TGGCTCTGAG GCGGAGCACC AGAGAGCCTA CCTGGAAGAC ACATGCGTGG
 AGTGGCTCCG CAGATACCTT GAGAATGGGA AGGAGACGCT GCAGCGCCCG
 GACCCCCCAA AGACACACGT GACCCATCAC CCCATCTCTG ATCATGAGGC
 CACCCTGAGG TGCTGGGCCC TGGGCTTCTA CCCTGCGGAG ATCACAGTGA
 CCTGGCAGCA GGATGGGGAG GACCAGACCC AGGACACGGA GCTTGTGGAG
 ACCAGGCCTG CAGGGGATGG AACTTTCCAG AAGTGGGCAG CTGTGGTGGT
 GCCTTCTGGA GAGGAGCAGA GATACACGTG CCATGTGCAG CATGAGGGGC
 TACCCGAGCC CCTCACCCTG AGATGGGAGC CGCCTTCCCA ACACTCCATC
 CCCATCGTGG GCATCATTGC TGGCCTGGTT CTCCTTGGAG CTGTGGTCAC
 TGGAGCTGTG GTTGCTGCTG TGATGTGGAG GAGTAACAGC TCAGGTAGAA
 AAGGATGGAG CTACTCTCAG GCTGTGTGTA GTGACAGTGC CCAGGGATCT
 GATGAGTCTC TCACAGCTTG TAAAGCCTGA * 
>DL;IPD:MHC02212
IPD:MHC02212 Mane-E*02:02 943 bases
 CACACTTCCG TGTCCCGGCC CGGCCGCGGG GAGCCCCGCT TCATCTCCGT
 GGGCTACGTG GACGACACCC AGTTCGTGCG GTACGACAGC GATGCCGCGA
 GTCCGAGGAT GGAGCCGCGG GCGCCGTGGG TGGAGCAGGA GGGGCCGGAG
 TATTGGGACC AGGAGACACG GAGCGCCAGG GACACCGCAC AGACTTTCCG
 AGTGAACCTG AAGACCCTGC GCGGCTACTA CAACCAGAGC GAGGCCGGGT
 CTCATACCCT CCAGTGGATG CATGGCTGCG ACCTGGGGCC CGACGGGCGC
 TTCCTCCGCG GATATGAACA GTTCGCCTAC GACGGCAAGG ATTATCTCAC
 CCTGAATGAG GACCTGCGCT CCTGGTCCGC GGTGGACACG GCGGCTCAGA
 TTTCCGAGCG AAAGTCAAAT GATGGCTCTG AGGCGGAGCA CCAGAGAGCC
 TACCTGGAAG ACACATGCGT GGAGTGGCTC CGCAGATACC TTGAGAATGG
 GAAGGAGACG CTGCAGCGCC CGGACCCCCC AAAGACACAC GTGACCCATC
 ACCCCATCTC TGATCATGAG GCCACCCTGA GGTGCTGGGC CCTGGGCTTC
 TACCCTGCGG AGATCACAGT GACCTGGCAG CAGGATGGGG AGGACCAGAC
 CCAGGACACG GAGCTTGTGG AGACCAGGCC TGCAGGGGAT GGAACTTTCC
 AGAAGTGGGC AGCTGTGGTG GTGCCTTCTG GAGAGGAGCA GAGATACACG
 TGCCATGTGC AGCATGAGGG GCTACCCGAG CCCCTCACCC TGAGATGGGA
 GCCGCCTTCC CAACACTCCA TCTCCATCGT GGGCATCATT GCTGGCCTGG
 TTCTCCTTGG AGCTGTGGTC ACTGGAGCTG TGGTTGCTGC TGTGATGTGG
 AGGAGTAACA GCTCAGGTAG AAAAGGATGG AGCTACTCTC AGG*
>DL;IPD:MHC02213
IPD:MHC02213 Mane-E*02:03 943 bases
 CACACTTCCG TGTCCCGGCC CGGCCGCGGG GAGCCCCGCT TCATCTCCGT
 GGGCTACGTG GACGACACCC AGTTCGTGCG GTACGACAGC GATGCCGCGA
 GTCCGAGGAT GGAGCCGCGG GCGCCGTGGG TGGAGCAGGA GGGGCCGGAG
 TATTGGGACC AGGAGACACG GAGCGCCAGG GACACCGCAC AGACTTTCCG
 AGTGAACCTG AAGACCCTGC GCGGCTACTA CAACCAGAGC GAGGCCGGGT
 CTCATACCCT CCAGTGGATG CATGGCTGCG ACCTGGGGCC CGACGGGCGC
 TTCCTCCGCG GATATGAACA GTTCGCCTAC GACGGCAAGG ATTATCTCAC
 CCTGAATGAG GACCTGCGCT CCTGGTCCGC GGTGGACACG GCGGCTCAGA
 TTTCCGAGCG AAAGTCAAAT GATGGCTCTG AGGCGGAGCA CCAGAGAGCC
 TACCTGGAAG ACACATGCGT GGAGTGGCTC CGCAGATACC TGGAGAATGG
 GAAGGAGACG CTGCAGCGCT CGGACCCCCC AAAGACACAC GTGACCCATC
 ACCTCATCTC TGATCATGAG GCCACCCTGA GGTGCTGGGC CCTGGGCTTC
 TACCCTGCGG AGATCACAGT GACCTGGCAG CAGGATGGGG AGGACCAGAC
 CCAGGACACG GAGCTTATGG AGACCAGGCC TGCAGGGGAT GGAACTTTCC
 AGAAGTGGGC AGCTGTGGTG GTGCCTTCTG GAGAGGAGCA GAGATACACG
 TGCCATGTGC AGCATGAGGG GCTACCCGAG CCCCTCACCC TGAGATGGGA
 GCCGCCTTCC CAACACTCCA TCCCCATCGT GGGCATCATT GCTGGCCTGG
 TTCTCCTTGG AGCTGTGGTC ACTGGAGCTG TGGTTGCTGC TGTGATGTGG
 AGGAGGAACA GCTCAGGTAG AAAAGGATGG AGCTACTCTC AGG*
>DL;IPD:MHC02214
IPD:MHC02214 Mane-E*02:04 1080 bases
 ATGGCACTAC GAACCCTACT TCTCCTGCTC TCGGCCCTTA CCAAGACCTG
 GGCCGGCTCC CACTCCTTGA AGTATTTCCA CACTTCCGTG TCCCGGCCCG
 GCTGCGGGGG GCCCCGCTTC ATCTCCGTGG GCTACGTGGA TGACACCCAG
 TTCGTGCGGT ATGACAGCGA CGCCGCGAGT CCGAGGATGG AGCCGCGGGC
 GCCGTGGGTG GAGCAGGAGG GGCCGGAGTA TTGGGACCAG GAGACACGGA
 GCGCCAGGGA CACCGCACAG ACTTTCCGAG TGAACCTGGA GACCCTGCGC
 GGCTACTACA ACCAGAGCGA GGCCGGGTCT CATACCCTCC AGTGGATGCA
 TGGCTGCGAC CTGGGGTCCG ACGGGCGCTT CCTCCGCGGG TATGAACAGT
 TCGCCTACGA CGGCAAGGAT TATCTCACCC TGAATGAGGA CCTGCGCTCC
 TGGTCCGCGG TGGACACGGC GGCTCAAATC TCCGAGCAAA AGTCAAATGA
 TGGCTCTGAG GCTGAGCACC AGAGAGCCTA CCTGGAAGAC ACATGCGTGG
 AGTGGCTCCA CAGATACCTG GAGAATGGGA AGGAGACGCT GCAGCGCTCA
 GAACCCCCAA AGACACACGT GGCCCACCAC CCCGTCTCTG ATCATGAGGC
 CACCCTGAGG TGCTGGGCCC TGGGCTTCTA TCCTGCGGAG ATCACAGTGA
 CCTGGCAGCG GGATGGGGAG GACCAGACCC AGGACACGGA GCTTGTGGAG
 ACCAGGCCTG CAGGGGATGG AACTTTCCAG AAGTGGGCAG CTGTGGTGGT
 ACCTTCTGGA GAGGAGCAGA GATACACGTG CCATGTGCAG CATGAGGGGC
 TACCCGAGCC CCTCACCCTG AGATGGGAGC CGTCTTCCCA GTCCACCATC
 CCCATCGTGG GCATCATTGC TGGCCTGGTT CTCCTTGGAG CTGTGGTCAC
 TGGAGCTGTG ATTGTTGCTG TGATGTGCAG GAGGAAGAGC TCAGGTAGAA
 AAGGAGGGAG CTACTCTCAG GCTTCATGTA GCGACAGTAC CCAGGGATCT
 GATGAGTCTC TCACAGCTTG TAAAGCCTGA * 
>DL;IPD:MHC02215
IPD:MHC02215 Mane-E*02:05 999 bases
 CACACTTCCG TGTCCCGGCC CGGCCGCGGG GGGCCCCGCT TCATCTCCGT
 GGGCTACGTG GATGACACCC AGTTCGTGCG GTATGACAGC GACGCCGCGA
 GTCCGAGGAT GGAGCCGCGG GCGCCGTGGG TGGAGCAGGA GGGGCCGGAG
 TATTGGGACC AGGAGACACG GAGCGCCAGG GACACCGCAC AGACTTTCCG
 AGTGAACCTG GAGACCCTGC GCGGCTACTA CAACCAGAGC GAGGCCGGGT
 CTCATACCCT CCAGTGGATG CATGGCTGCG ACCTGGGGTC CGACGGGCGC
 TTCCTCCGCG GGTATGAACA GTTCGCCTAC GACGGCAAGG ATTATCTCAC
 CCTGAATGAG GACCTGCGCT CCTGGTCCGC GGTGGACACG GCGGCTCAAA
 TCTCCGAGCA AAAGTCAAAT GATGGCTCTG AGGCTGAGCA CCAGAGAGCC
 TACCTGGAAG ACACATGCGT GGAGTGGCTC CACAGATACC TGGAGAATGG
 GAAGGAGACG CTGCAGCGCT CAGAACCCCC AAAGACACAC GTGGCCCACC
 ACCCCGTCTC TGATCATGAG GCCACCCTGA GGTGCTGGGC CCTGGGCTTC
 TATCCTGCGG AGATCACAGT GACCTGGCAG CGGGATGGGG AGGACCAGAC
 CCAGGACACG GAGCTTGTGG AGACCAGGCC TGCAGGGGAT GGAACTTTCC
 AGAAGTGGGC AGCTGTGGTG GTACCTTCTG GAGAGGAGCA GAGATACACG
 TGCCATGTGC AGCATGAGGG GCTACCCGAG CCCCTCACCC TGAGATGGGA
 GCCGTCTTCC CAGTCCACCA TCCCCATCGT GGGCATCATT GCTGGCCTGG
 TTCTCCTTGG AGCTGTGGTC ACTGGAGCTG TGATTGTTGC TGTGATGTGC
 AGGAGGAAGA GCTCAGGTAG AAAAGGAGGG AGCTACTCTC AGGCTTCGTG
 TAGCGACAGT ACCCAGGGAT CTGATGAGTC TCTCACAGCT TGTAAAGCC*
>DL;IPD:MHC02216
IPD:MHC02216 Mane-E*02:06 1080 bases
 ATGGCACTAC GAACCCTACT TCTCCTGCTC TCGGCCCTTA CCGAGACCTG
 GGCGGGCTCC CACTCCTTGA AGTATTTCCA CACTTCCGTG TCCCGGCCCG
 GCGGCGGGGG GCCCCGCTTC ATCTCCGTGG GCTACGTGGA CGACACCCAG
 TTCGTGCGGT ATGACAGCGA CGCGGCGAGT CCGAGGATGG AGCCGCGGGC
 GCTGTGGATG AAGCAGGAGG GGCCGGAGTA TTGGGACCAG GAGACACGGA
 GCGCCAGGGA CACCGCACAG ACTTTCCGAG TGAACCTGGA GACCCTGCGC
 GGCTACTACA ACCAGAGCGA GGCCGGGTCT CATACCCTCC AGTGGATGCA
 TGGCTGCGAC CTGGGGCCGG ACGGGCGCTT CCTCCGCGGG TATGAACAGT
 TCGCCTACGA CGGCAAGGAT TATCTCACCC TGAATGAGGA CCTGCGCTCC
 TGGTCCGCGG TGGACACGGC GGCTCAAATC TCCGAGCAAA AGTCAAATGA
 TGGCTCTGAG GCGGAGCACC AGAGAGCCTA CCTGGAAGAC ACATGCGTGG
 AGTGGCTCCA CAGATACCTG GAGAATGGGA AGGAGACGCT GCAGCGCTCG
 GAATCCCCAA AGACACACGT GACCCACCAC CCCGTCTCTG ATCATGAGGC
 CACCCTGAGG TGCTGGGCCC TGGGCTTCTA CCCTGCGGAG ATCACAGTGA
 CCTGGCAGCG GGATGGGGAG GACCAGACCC AGGACACGGA GCTTGTGGAG
 ACCAGGCCTG CAGGGGATGG AACTTTCCAG AAGTGGGCAG CTGTGGTGGT
 ACCTTCTGGA GAGGAGCAGA GATACACGTG CCATGTGCAG CATGAGGGGC
 TACCCGAGCC CCTCACCCTG AGATGGGAGC CGTCTTCCCA GTCCACCATC
 CCCATCGTGG GCATCATTGC TGGCCTGGTT CTCCTTGGCG CTGTGGTCAC
 TGGAGCTGTG GTTGCTGCTG TGATGTGGAG GAGGAAGAGC TCAGGTAGAA
 AAGGATGGAG CTACTCTCAG GCTGTGTGTA GCGACAGTTC CCAGGGATCT
 GATGATTCTC TCACAGCTTA TAAACCCTGA * 
>DL;IPD:MHC02217
IPD:MHC02217 Mane-E*02:07 1043 bases
 CGGCCCTTAC CAAGACCTGG GCGGGCTCCC ACTCCTTGAA GTATTTCCAC
 ACTTCCGTGT CCCGGCCCGG CCGCGGGGAG CCCCGCTTCA TCTCCGTGGG
 CTACGTGGAC GACACCCAGT TCGTGCGGTA CGACAGCGAC GCCGCGAGTC
 CGAGGATGGA GCCGCGGGCG CTGTGGATGA AGCAGGAGGG GCCGGAGTAT
 TGGGACCAGG AGACACGGAG CGCCAGGGAC ACCGCACAGA CTTTCCGAGT
 GAACCTGAAG ACCCTGCGCG GCTACTACAA CCAGAGCGAG GCCGGGTCTC
 ATACTCTCCA GTGGATGCAT GGCTGCGACC TGGGGCCGGA CGGGCGCTTC
 TTCCGCGGGT ATGAACAGTT TGCCTACGAC GGCAAGGATT ATCTCACCCT
 GAATGAGGAC CTGCGCTCCT GGTCCGCGGT GGACACGGCG GCTCAAATCT
 CCGAGCAAAA GTCAAATGAT GGCTCTGAGG CGGAGCACCA GAGAGCCTAC
 CTGGAAGACA CATGCGTGGA GTGGCTCCGC AGATACCTGG AGAATGGGAA
 GGAGACGCTG CTGCGCTCGG AATCCCCAAA GACACACGTG ACCCGCCACC
 CCGTCTCTGA TCATGAGGCC ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC
 CCTGCGGAGA TCACAGTGAC CTGGCAGCGG GATGGGGAGG ACCAGACCCA
 GGACACGGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA ACTTTCCAGA
 AGTGGGCAGC TGTGGTGGTA CCTTCTGGAG AGGAGCAGAG ATACACGTGC
 CATGTGCAGC ATGAGGGGCT ACCCGAGCCC CTCATCCTGA GATGGGAGCC
 GTCTTCCCAA TCCTCCATCC CAATCGTGGG CATCATTGTT GGCCTGGTTC
 TCCTTGGAGC TGTGGTCACT GGAGCTGTGG TTGCTGCTGT GATGTGGAGG
 AAGAGCTCAG GTAGAAAAGG ACGGAGCTAC TCTCAGGCTT CGTGTAGCGA
 CAGTGCCCAG GGATCTGATG AGTCTCTCAC AGCTTATAAA GCC*
>DL;IPD:MHC02218
IPD:MHC02218 Mane-E*02:08 999 bases
 CACACTTCCG TGTCCCGGCC CGGCGGCGGG GGGCCCCGCT TCATCTCCGT
 GGGCTACGTG GACGACACCC AGTTCGTGCG GTACGACAGC GACGCCGCGA
 GTCCGAGGAT GCAGCCGCGG GCGCTGTGGA TGAAGCAGGA GGGGCCGGAG
 TATTGGGACC AGGAGACACG GAGCGCCAGG GACACCGCAC AGGCTTTCCG
 AGTGAACCTG AATACCCTGC GCGGCTACTA CAACCAGAGC GAGGCCGGGT
 CTCATACCCT CCAGTGGATG TATGGCTGCG ACCTGGGGCC CGACGGGCGC
 TTCCTCCGCG GGTATGAACA GTTTGCCTAC GACGGCAAGG ATTATCTCAC
 CCTGAATGAG GACCTGCGCT CCTGGTCCGC GGTGGACACG GCGGCTCAGA
 TCTCTGCACA AAAGTCAAAT GATGGCTCTG AGGCGGAGCA CCAGAGAGCC
 TACCTGGAAG ACACATGCGT GGAGTGGCTC CACAGATACC TGGAGAATGG
 GAAGGAGACC CTGCAGCGCT CGGAATCCCC AAAGACACAC GTGACCCACC
 ACCCCATCTC TGATCATGAG GCCACCCTGA GGTGCTGGGC CCTGGGCTTC
 TACCCTGCGG AGATCACAGT GACCTGGCAG CGGGATGGGG AGGACCAGAC
 CCAGGACACG GAGCTTGTGG AGACCAGGCC TGCAGGGGAT GGAACCTTCC
 AGAAGTGGGC AGCTGTGGTG GTGCCTTCTG GAGAGGAGCA GAGATACACA
 TGCCATGTGC AGCATGAGGG GCTACCCGAG CCCCTCACCC TGAGATGGGA
 GCCGTCTTCC TGGTCCACCA TCCCCATTGT GGGCATCATT GCTGGCCTGG
 TTCTCCTTGG AGCTGTGGTC ACTGGAGCTG TGGTTGCTGC TGTGATGTGG
 AGGAGGAAGA GCTCAGGTAG AAAAGGAGGG AGCTACTCTC AGGCTTCGTG
 TAGCAACAGT ACCCAGGGAT CTGATGAGTC TCTCACAGCT TATAAAACC*
