>DL;IPD:MHC04359
IPD:MHC04359 Mane-AG*03:01 273 bases
 SHSMRYFYTA VSRPGRGQPR FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 VEQEGPEYWD RETQNMKTAT QTYRENLRTL LRYYNQSEAG SHTVQKMYGC
 DLGPDGRLLR GYEQFAYDGR DYIILNEDLR SWTAADMAAQ NTQRKWEAAG
 AAEQHRTYLE GECLEWLRRY LENGKETLQR ADPPKTNVTH HPVSDYEATL
 RCWALGFYPA EITLTWQRDG EEQTEDTELV ETRPTGDGTF QKWAAVVVPS
 GEEQRYTCHV QHEGLPEPLT LRW*  
