>DL;IPD:MHC03423
IPD:MHC03423 Mane-DQB1*06:01 254 bases
 TGTACCAGTT TAAGGCCATG TGCTACTTCA CCAACTGGAC GGAGCGCGTG
 CGTTATGTGA CCAGATACAT CTATAACCGA GAGGAGTTCG TGCGATTCGA
 CAGCGCCGTG GGGGAGTACC GGGCGGTGAC GCCGCAAGGG CGGCTTGACG
 CCGAGTACTG GAACAGCCAG AAGGACGTGC TGGAGAGCAC CCGGGCGGAA
 TTGGACACGG TGTGCAAACA CAACTACGAG GTGGCGTTCC GCGGGATCTT
 GCAG*    
>DL;IPD:MHC03424
IPD:MHC03424 Mane-DQB1*06:02 254 bases
 TGTACCAGTT TAAGGGCATG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CGTCATGTGA CCAGGTACAT CTATAACCGA GAGGAGTACG CGCGCTTCGA
 CAGCGACTGG GGGGAGTACC GGGCGGTGAC GCCGCAGGGG CGGCCTGACG
 CCGAGTACTG GAACAGCCAG AAGGACATCC TGGAGAGCAC CCGGGCGGAG
 TTGGACACGG TGTGCAAACA CAACTACGAG GTGGCGTTCC GCGGGATCTT
 GCAG*    
>DL;IPD:MHC03426
IPD:MHC03426 Mane-DQB1*06:03 254 bases
 TGTACCAGTT TAAGGGTCTG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CGGAGTGTGA CCAGATACAT CTATAACCGA GAGGAGTACG TGCGCTTCGA
 CAGCGACTGG GGGGAGTACC GGGCGGTGAC GCCGCAGGGG CGGCCTGCCG
 CCGAGTACTG GAACAGCCAG AAGGACATCC TGGAGAGGAC CCGGGCGGAG
 TTGGACACTG TGTGCATACA CAACTACGAG GTGGTGTACC GCGGGATCTT
 GCAG*    
>DL;IPD:MHC03428
IPD:MHC03428 Mane-DQB1*06:04 254 bases
 TGTACCAGTT TAAGGGTCTG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CGTCTTGTGA CCAGACACGT TTATAACCGA GAGGAGTACG TGCGCTTCGA
 CAGCGACTGG GGGGAGTACC GGGCGGTGAC GCCGCAGGGG CGGCCTGACG
 CCGAGTACTG GAACAGCCAG AAGGACATCC TGGAGAGCAC CCGGGCGGAG
 TTGGACACGG TGTGCATGCA CAACTACGAG GTGGCGTACC GCGGGATCTT
 GCAG*    
>DL;IPD:MHC03430
IPD:MHC03430 Mane-DQB1*06:05 254 bases
 TGTACCAGTT TAAGGGTCTG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CGGAGTGTGA CCAGACACAT TTATAACCGA GAGGAGTACG TGCGCTTCGA
 CAGCGACTGG GGGGAGTACC GGGCGGTGAC GCCGCAGGGG CGGCCTGCCG
 CCGAGTACTG GAACAGCCAG AAGGACATCC TGGAGAGGAC CCGGGCGGAG
 TTGGACACTG TGTGCATACA CAACTACGAG GTGGTGTACC GCGGGATCTT
 GCAG*    
>DL;IPD:MHC03433
IPD:MHC03433 Mane-DQB1*06:06 254 bases
 TGTACCAGTT TAAGGGTCTG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CGGAGTGTGA CCAGACACAT TTATAACCGA GAGGAGTACG TGCGCTTCGA
 CAGCGACTGG GGGGAGTACC GGGCGGTGAC GCCGCAGGGG CGGCCTGACG
 CCGAGTACTG GAACAGCCAG AAGGACATCC TGGAGAGCAC CCGGGCGGAA
 TTGGACACGG TGTGCATGCA CAACTACGAG GTGGCGTACC GCGGGATCTT
 GCAG*    
>DL;IPD:MHC03435
IPD:MHC03435 Mane-DQB1*06:07 254 bases
 TGTTCCAGTT TAAGGGCCTG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CGTCTTGTGA CCAGATACAT CTATAACCGA GAGGAGTTCC TGCGATTCGA
 CAGCGCCGTG GGGGAGTACC GGGCTGTGAC GCCACAGGGG CGGTCTGACG
 CCGAGCACTT GAACAGCCAG AAGGACGTGC TGGAGAGGAC CCGGGCGGAG
 TTGGACACGG TGTGCATGCA CAACTACGAG GTGGCGTACC GCGGGATCTT
 GCAG*    
>DL;IPD:MHC03436
IPD:MHC03436 Mane-DQB1*06:08:01 254 bases
 TGTTCCAGTT TAAGGGCCTG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CGTCATGTGA CCAGATACAT CTATAACCGA GAGGAGTTCC TGCGATTCGA
 CAGCGCCGTG GGGGAGTACC GGGCTGTGAC GCCACAGGGG CGGTCTGACG
 CCGAGCACTT GAACAGCCAG AAGGACGTGC TGGAGAGCAC CCGGGCGGAG
 TTGGACACGG TGTGCATGCA CAACTACGAG GTGACGTACC GCGGGATCTT
 GCAG*    
>DL;IPD:MHC03432
IPD:MHC03432 Mane-DQB1*06:08:02 254 bases
 TGTTCCAGTT TAAGGGCCTG TGCTACTTCA CCAACGGGAC GGAGCGTGTG
 CGTCATGTGA CCAGATACAT CTATAACCGA GAGGAGTTCC TGCGATTCGA
 CAGCGCCGTG GGGGAGTACC GGGCTGTGAC GCCACAGGGG CGGTCTGACG
 CCGAGCACTT GAACAGCCAG AAGGACGTGC TGGAGAGCAC CCGGGCGGAG
 TTGGACACGG TGTGCATGCA CAACTACGAG GTGACGTACC GCGGGATCTT
 GCAG*    
>DL;IPD:MHC03425
IPD:MHC03425 Mane-DQB1*06:09:01 254 bases
 TGTACCAGTT TAAGGGCCTG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CGGAGTGTGA ACAGATACAT CTATAACCGA GAGGAGTACG TGCGCTTCGA
 CAGCGACTGG GGGGAGTACC GGGCGGTGAC GCCGCAGGGG CGGCCTGACG
 CCGAGTACTG GAACAGCCAG AAGGACATCC TGGAGAGGAC CCGGGCGGAG
 TTGGACACGG TGTGCATGCA CAACTACGAG GTGGCGTACC GCGGGATCTT
 GCAG*    
>DL;IPD:MHC03429
IPD:MHC03429 Mane-DQB1*06:09:02 254 bases
 TGTACCAGTT TAAGGGTCTG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CGGAGTGTGA ACAGATACAT CTATAACCGA GAGGAGTACG TGCGCTTCGA
 CAGCGACTGG GGGGAGTACC GGGCGGTGAC GCCGCAGGGG CGGCCTGACG
 CCGAGTACTG GAACAGCCAG AAGGACATCC TGGAGAGGAC CCGGGCAGAG
 TTGGACACGG TGTGCATGCA CAACTACGAG GTGGCGTACC GCGGAATCTT
 GCAG*    
>DL;IPD:MHC03427
IPD:MHC03427 Mane-DQB1*06:10 254 bases
 TGTTCCAGTT TAAGGGCCTG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CGTCATGTGA CCAGATACAT CTATAACCGA GAGGAGTTCC TGCGATTCGA
 CAGCGCCGTG GGGGAGTACC GGGCTGTGAC GCCACAGGGG CGGTCTGACG
 CCGAGCACTT GAACAGCCAG AAGGACGTGC TGGAGAGCAC CCGGGCGGAG
 TTGGACACGG TGTGCATGCA CAACTACGAG GTGACGTTCC GCGGGATCTT
 GCAG*    
>DL;IPD:MHC03431
IPD:MHC03431 Mane-DQB1*06:11 254 bases
 TGGTCCAGTT TAAGGGCCTG TGCTACTACA CCAACGGGAC GGAGCGCGTG
 CGGGGTGTGA CCAGATACAT CTATAACCGA GAGGAGTACG CGCGCTTCGA
 CAGCGACTGG GGGGAGTACC GGGCGGTGAC GCCGCAGGGG CGGCCTGCCG
 CCGAGTACTG GAACAGCCAG AAGGACATCC TGGAGAGGAC CCGGGCGGAG
 TTGGACACTG TGTGCATACA CAACTACGAG GTGGTGTACC GCGGGATCTT
 GCAG*    
>DL;IPD:MHC03434
IPD:MHC03434 Mane-DQB1*06:12 254 bases
 TGTACCAGTT TAAGGGCCTG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CGTCTTGTGA GCAGATTCAT CTATAACCGA GAGGAGTACG TGCGCTTCGA
 CAGCGACTGG GGGGAGTACC GGGCGGTGAC GCCGCAGGGG CGGCCTGACG
 CCGAGTACTG GAACAGTCAG AAGGACATCC TGGAGAGCAC CCGGGCGGAG
 TTGGACACGG TGTGCATGCA CAACTACGAG GTGGCGTACC GCGGGATCTT
 GCAG*    
>DL;IPD:MHC03437
IPD:MHC03437 Mane-DQB1*06:13 254 bases
 TGTACCAGTT TAAAGGCCTG TGCTACTTCA CCAACGGGAA GGAGCGCGTG
 CGTCTTGTGA CCAGATACAT CTATAACCGA GAGGAGTACG TGCGCTTCGA
 CAGCGACTGG GGGGAGTACC GGGCGGTGAC GCCGCAGGGG CGGTCTTGGG
 CCAAGTACTG GAACAGCCAG AAGGACTTCC TGGAGAGCAC CCGGGCGGAA
 TTGGACACGG TGTGCAAACA CAACTACGAG GTGGCGTTCC GCGGGATCTT
 GCAG*    
>DL;IPD:MHC03414
IPD:MHC03414 Mane-DQB1*15:01 254 bases
 TGTTCCAGTT TAAGGGCATG TGCTACTTCA CCAACGGGAC AGAGCGCGTG
 TGGAGTGTAG ACAGATACAT CTATAACCGA GAGGAGTACG TGCGCTTCGA
 CAGCGACGTG GGGTTGTACC TGCCGGTGAC GCCGCTGGGG CGGTCCATTG
 CCGAGTACTG GAACAGCCAG AAGGAAGCCC TGGAGAGCAA ACGGGCGGAG
 TTGGACACGG TGTGCATACA CAACTACCAG TTGGAGCTCG GCACGACCTT
 GCAG*    
>DL;IPD:MHC03886
IPD:MHC03886 Mane-DQB1*16:01 254 bases
 TGCACCAGTT TAAGTTCATG TGCTACTTCG TCAACGGGAC AGAGCGCGTG
 CGGGCTATAG CCAGACACGT CTATAACCGC GAAGAGTTCG CGCGCTTCGA
 CAGCGACGTG GGGGTGTACC GAGCGGTGAC GCCGCTGGGG CGGTCTAGTG
 CCGAGTACTG GAACAGCCAG AAGGAAGTCC TGGAGAGGAA ACGGGCGGAG
 TTGGACACGG TGTGCAGACA CAACTACCAG TTGGAACTCC GCTCGACCTT
 GCAG*    
>DL;IPD:MHC03417
IPD:MHC03417 Mane-DQB1*17:01:01 254 bases
 TGTACCAGTT TAAGGCCATG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CATTATGTGA CCAGATACAT CTATAACCGA GAGGAGTACG CGCGCTTCGA
 CAGCGACGTG GGGAAGTACC TGCCGGTGAC GCCTCTGGGG CCGCCTGCCG
 CCGAGTATTG GAACAGCCAG AAGGACGTCC TGGAGAGCAC CCGGGCGGAG
 TTGGACACGG TGTGCAGACA CAACTACCAG TTGGAGCTCC GCACGATCTT
 GCAG*    
>DL;IPD:MHC03419
IPD:MHC03419 Mane-DQB1*17:01:02 254 bases
 TGTACCAGTT TAAGGCCATG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CATTATGTGA CCAGATACAT CTATAACCGA GAGGAGTACG CGCGCTTCGA
 CAGCGACGTG GGGAAGTACC TGCCGGTGAC GCCTCTGGGG CCGCCTGCCG
 CCGAGTATTG GAACAGCCAG AAGGACGTCC TGGAGAGCAC CCGGGCGGAG
 TTGGACACGG TATGCAGACA CAACTACCAG TTGGAGCTCC GCACGATCTT
 GCAG*    
>DL;IPD:MHC03420
IPD:MHC03420 Mane-DQB1*17:02 254 bases
 TGTACCAGTT TAAGTGCCTG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CATTATGTGA CCAGACACAT TTATAACCGA GAGGAGTACG TGCGCTTCGA
 CAGCGACTGG GGGGAGTACC GGGCGGTGAC GCCGCTGGGG CGACCTACCG
 CCGAGTACTG GAACAGCCAG AAGGACTTCC TGGAGAGCAC CCGGGCGGAG
 TTGGACACGG TGTGCAAACA CAACTACCAG TTGGAACTCC TCACGACCTT
 GCAG*    
>DL;IPD:MHC03421
IPD:MHC03421 Mane-DQB1*17:03 254 bases
 TGTACCAGTT TAAGGCCATG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CATTATGTGA CCAGATACAT CTATAACCGA GAGGAGTACG CGCGCTTCGA
 CAGCGACGTG GGGAAGTACC TGCCGGTGAC GCCTCTGGGG CCGCCTGACG
 CCGAGTATTG GAACAGCCAG AAGGACTTCC TGGAGAGCAC CCGGGCGGAG
 TTGGACACGG TGTGCAGACA CAACTACCAG TTGGAGCTCC GCACGATCTT
 GCAG*    
>DL;IPD:MHC03884
IPD:MHC03884 Mane-DQB1*17:04 254 bases
 TGTACCAGTT TAAGGCCATG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CATTATGTGA CCAGATACAT CTATAACCGA GAGGAGTACG CGCGCTTCGA
 CAGCGACGTG GGGAAGTACC TGCCGGTGAC GCCTCTGGGG CCGCCTGACG
 CCGAGTATTG GAACAGCCAG AAGGACGTCC TGGAGAGCAC CCGGGCGGAG
 TTGGACACGG TGTGCAGACA CAACTACCAG TTGGAGCTCC GCACGATCTT
 GCAG*    
>DL;IPD:MHC03885
IPD:MHC03885 Mane-DQB1*17:05 254 bases
 TGTACCAGTT TAAGGCCATG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CATTATGTGA CCAGATACAT CTATAACCGA GAGGAGTACG CGCGCTTCGA
 CAGCGACGTG GGCAAGTACC TGCCGGTGAC GCCTCTGGGG CCGCCTGCCG
 CCGAGTATTG GAACAGCCAG AAGGACTTCC TGGAGAGCAC CCGGGCGGAG
 TTGGACACGG TGTGCAGACA CAACTACCAG TTGGAGCTCC GCACGATCTT
 GCAG*    
>DL;IPD:MHC03415
IPD:MHC03415 Mane-DQB1*18:01 254 bases
 TGTTCCAGTT TAAGGGCATG TGCTACTTCA TCAACGGGAC GGAGCACGTG
 CATCATGTGA ACAGATACAT CTACAACCGA GAGGAGTTCG TGGGCTTCGA
 CAGCTACTTG GGTGTGTACC GGCCAGTGAC GCCGCTGGGG CGGTCTTGGG
 CCGAGTACTG GAACAGCCAG AAGGACATCC TGGAGCGCAC CCGGGCGGTG
 GTGGACACGG TGTGCAGACA CAACTACCAG TCGGAGCTCC GCACGACCTT
 GCAG*    
>DL;IPD:MHC03416
IPD:MHC03416 Mane-DQB1*18:02 254 bases
 TGTTCCAGTT TAAGGGCCTG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CGTCTTGTGA CCAGATACGT TTATAACCGA GAGGAGTACG TGCGCTTCGA
 CAGCGACTGG GGGGAGCACC GGGCGGTGAC GCCGCTGGGG CGGTCTTGGG
 CCGAGTACTG GAACAACCAG AAGGACTTCC TGGAGACGAC CCGGGCGTCG
 GTGGACACGG TGTGCAGACA CAACTACCAG TTGGAACTCC GCACGACCTT
 GCAG*    
>DL;IPD:MHC03418
IPD:MHC03418 Mane-DQB1*18:03 254 bases
 TGTACCAGTT TAAGGGCCTG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CGGGGTGTGA CCAGACACAT TTATAACCGA GAGGAGTTCG TGCGCTTCGA
 CAGCGACTGG GGGGAGCACC GGGCGGTGAC GCCGCTGGGG CGGTCTTGGG
 CCGAGTACTG GAACAACCAG AAGGACGTCC TGGAGACGAC CCGGGCGTCG
 GTGGACACGG TGTGCAGACA CAACTACCAG TTGGAACTCC GCACGACCTT
 GCAG*    
>DL;IPD:MHC03422
IPD:MHC03422 Mane-DQB1*18:04 254 bases
 TGCACCAGTT TAAGGGCCTG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CGGGGTGTGA CCAGATACAT CTATAACCGA GAGGAGTACG TGCGCTTCGA
 CAGCGACTGG GGGGAGTACC GGGCGGTGAC GCCGCAGGGG CAGTCTGACG
 CCGAGTACTG GAACAGCCAG AAGGACATCC TGGAGAGGAC CCGGGCGTCG
 GTGGACACGG TGTGCAGACA CAACTACCAG TTGGAGCTCC GCACCACCTT
 GCAG*    
>DL;IPD:MHC03881
IPD:MHC03881 Mane-DQB1*18:05 254 bases
 TGTACCAGTT TAAGGGCCTG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CGTCTTGTGA CCAGATACAT CTATAACCGA GAGGAGTACG TGCGCTTCGA
 CAGCGACTGG GGGGAGTACC GGGCGGTGAC GCCGCTGGGG CCGCCTGACG
 CCGAGTACTG GAACAGCCAG AAGGACATCC TGGAGAGCAC CCGGGCGGAG
 GCGGACACGG TGTGCAGACA CAACTACCAG TCAGAGCTCC GCACGACCTT
 GCAG*    
>DL;IPD:MHC03882
IPD:MHC03882 Mane-DQB1*18:06 254 bases
 TGTACCAGTT TAAGGGCCTG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CGTCTTGTGA CCAGATACAT CTATAACCGA GAGGAGTACG TGCGCTTCGA
 CAGCGACTGG GGGGAGTACC GGGCGGTGAC GCCGCTGGGG CCGCCTGCTG
 CAGAGTACTG GAACAGCCAG AAGGACATCC TGGAGAGGAC CCGGGCGGAA
 CTGGACACGG TGTGCAGACA CAACTACCAG TCAGAGCTCC GCACGACCTT
 GCAG*    
>DL;IPD:MHC03883
IPD:MHC03883 Mane-DQB1*18:07 254 bases
 TGTTCCAGTT TAAGGGCCTG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CGTCATGTGA CCAGATACAT CTATAACCGA GAGGAGTACG TGCGCTTCGA
 CAGCGACTGG GGGGAGTACC GGGCGGTGAC TCCGCTGGGG CGACCTGACG
 CCGAGTACTG GAACAGCCAG AAGGATATCC TGGAGAGGAC CCGGGCGGAG
 TTGGACACGG TGTGCAGACA CAACTACCAG TCGGAGCTCC GCACGACCTT
 GCAA*    
>DL;IPD:MHC03887
IPD:MHC03887 Mane-DQB1*18:08 254 bases
 TGGTCCAGTT TAAGGGCCTG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CGGAGTGTGA ACAGATACAT CTATAACCGA GAGGAGTACG CGCGCTTCGA
 CAGCGACTGG GGGGAGTACC GGGCGGTGAC GCCGCTGGGG CGACCTGACG
 CCGAGTACTG GAACAGCCAG AAGGACATCC TGGAGAGCAC CCGGGCGGAG
 GCGGACACGG TGTGCAGACA CAACTACCAG TCAGAGCTCC GCACGACGTT
 GCAG*    
