>DL;IPD:MHC00629
IPD:MHC00629 Mane-DRB*W1:01 270 bases
 CACGTTTCTT AGAGTACTGT AAGTTTGAGT GTCATTTCTT CAATGGGACG
 GAGCGGGTGC AGTACCTGAT CAGATACTTC TATAACCAAG AGGAGTACGT
 GCGCTACGAC AGCGACGTCG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC CGAGTACTGG AACGGCCAGA AGGACCTCCT GGAGCAGAGG
 CGGGCCGAGG TGGACACCGT GTGCAGACAC AACTACGGGG TTGTTGAGAG
 CTTCACAGTG CAGCGGCGAG *  
>DL;IPD:MHC00630
IPD:MHC00630 Mane-DRB*W1:02 270 bases
 CACGTTTCTT AGAGTACTGT AAGTTTGAGT GTCATTTCTT CAATGGGACG
 GAGCTGATGC TGTACCTGAT CAGATACTTC CATAACCAAG AGGAGTACGT
 GCGCTACGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGTCGC CGAGAACTGG AACAGCCAGA AGGACCTCCT GGAGCAGAGG
 CGGGCCGAGG TGGACACCTA CTGCAGACAC AACTACGGGG TTGGTGAGAG
 CTTCACAGTG CAGCGGCGAG *  
>DL;IPD:MHC03925
IPD:MHC03925 Mane-DRB*W1:03 226 bases
 TAAGTTTGAG TGCCATTTCT TCAATGGGAC GGAGCGGGTG CTGAACCTGA
 TCAGATACTT CTATAACCAA GAGGAGTACG TGCGCTACGA CAGCGACGTC
 GGGGAGTACC GGGCGGTGAC GGAGCTGGGG CGGCCTGACG CCAAGTACTG
 GAACGGCCAG AAGGACCTCC TGGAGCAGAG GCGGGCCGAG GTGGACACCT
 ACTGCAGACA CAACTACGGG GTTGTT*  
>DL;IPD:MHC03926
IPD:MHC03926 Mane-DRB*W1:04 226 bases
 TAAGTTTGAG TGCCATTTCT TCAATGGGAC GGAGCGGGTG CTGAACCTGA
 TCAGATACTT CTATAACCAA GAGGAGTACG TGCGCTACGA CAGCGACGTG
 GGGGAGTACC GGGCGGTGAC GGAGCTGGGG CGGCCTGACG CCGAGTACTG
 GAACGGCCAG AAGGACCTCC TGGAGCAGAG GCGGGCCGAG GTGGACACCT
 ACTGCAGACA CAACTACCGG GTTGGT*  
>DL;IPD:MHC03927
IPD:MHC03927 Mane-DRB*W1:05 225 bases
 TAAGTTTGAG TGTCATTTCT TCAATGGGAC GGAGCGGGTG CAGTACCTGA
 TCAGATACTT CTATAACCAA GAGGAGTACG TGCGCTACGA CAGCGACGTC
 GGGGAGTACC GGGCGGTGAC GGAGCTGGGG CGGCCTGACG CCGAGTACTG
 GAACGGCCAG AAGGACCTCC TGGAGCAGAG GCGGGCCGAG GTGGACAACT
 ACTGCAGACA CAACTACGGG GTTGG*  
>DL;IPD:MHC03928
IPD:MHC03928 Mane-DRB*W1:06 534 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CTCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT AGAGTACTGT AAGTTTGAGT GCCATTTCTT CAATGGGACG
 GAGCGGGTGC TGAACCTGAT CAGATACTTC TATAACCAAG AGGAGTACGT
 GCGCTACGAC AGCGACGTCG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC CAAGTACTGG AACGGCCAGA AGGACCTCCT GGAGCAGAGG
 CGGGCCGAGG TGGACACCTA CTGCAGACAC AACTACCGGG TTGGTGAGAG
 CTTCACAGTG CAGCGGCGAG TTCAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACACCCTCC TGGTCTGCTC TGTGAACGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACG GCCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAG* 
>DL;IPD:MHC03929
IPD:MHC03929 Mane-DRB*W1:07 534 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAC CTCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT AGAGTACTGT AAGTTTGAGT GCCATTTCTT CAATGGGACG
 GAGCGGGTGC TGAACCTGAT CAGATACTTC TATAACCAAG AGGAGTACGT
 GCGCTACGAC AGCGACGTCG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC CAAGTACTGG AACGGCCAGA AGGACCTCCT GGAGCAGAGG
 CGGGCCGAGG TGGACACCTA CTGCAGACAC AACTACCGGG TTGTTGAGAG
 CTTCACAGTG CAGCGGCGAG TTCAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACACCCTCC TGGTCTGCTC TGTGAACGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACG GCCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAG* 
>DL;IPD:MHC03986
IPD:MHC03986 Mane-DRB*W1:08 226 bases
 TACGTTTGAG TGCCATTTCT TCAATGGGAC GGAGCGGGTG CTGAACCTGA
 TCAGATACTT CTATAACCAA GAGGAGTACG TGCGCTACGA CAGCGACGTC
 GGGGAGTACC GGGCGGTGAC GGAGCTGGGG CGGCCTGACG CCAAGTACTG
 GAACGGCCAG AAGGACCTCC TGGAGCAGAG GCGGGCCGAG GTGGACACCT
 ACTGCAGACA CAACTACCGG GTTGGT*  
>DL;IPD:MHC03987
IPD:MHC03987 Mane-DRB*W1:09 226 bases
 TAAGTTTGAG TGCCATTTCT TCAATGGGAC GGAGCGGGTG CAGTACCTGA
 TCAGATACTT CTATAACCAA GAGGAGTACG TGCGCTACGA CAGCGACGTC
 GGGGAGTACC GGGCGGTGAC GGAGCTGGGG CGGCCTGACG CCGAGTACTG
 GAACGGCCAG AAGGACCTCC TGGAGCAGAG GCGGGCCGAG GTGGACACCT
 ACTGCAGACA CAACTACCGG GTTGTT*  
>DL;IPD:MHC03988
IPD:MHC03988 Mane-DRB*W1:10 534 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAC CTCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT AGAGTACTGT AAGTTTGAGT GCCATTTCTT CAATGGGACG
 GAGCGGGTGC AGTACCTGAT CAGATACTTC TATAACCAAG AGGAGTACGT
 GCGCTACGAC AGCGACGTCG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC CGAGTACTGG AACGGCCAGA AGGACCTCCT GGAGCAGAGG
 CGGGCCGAGG TGGACACCGT GTGCAGACAC AACTACGGGG TTGGTGAGAG
 CTTCACAGTG CAGCGGCGAG TTCAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACACCCTCC TGGTCTGCTC TGTGAACGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACG GCCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAG* 
>DL;IPD:MHC03989
IPD:MHC03989 Mane-DRB*W1:11 534 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CTCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGACTGGG GACATCCGAC
 CACGTTTCTT AGAGTACTGT AAGTTTGAGT GCCATTTCTT CAATGGGACG
 GAGCGGGTGC TGAACCTGAT CAGATACTTC TATAACCAAG AGGAGTACGT
 GCGCTACGAC AGCGACGTCG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC CAAGTACTGG AACGGCCAGA AGGACCTCCT GGAGCAGAGG
 CGGGCCGAGG TGGACACCGT GTGCAGACAC AACTACGGGG TTGTTGAGAG
 CTTCACAGTG CAGCGGCGAG TTCAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACACCCTCC TGGTCTGCTC TGTGAACGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACG GCCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAG* 
>DL;IPD:MHC04579
IPD:MHC04579 Mane-DRB*W1:12 534 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CTCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT AGAGTACTGT AAGTTTGAGT GCCATTTCTT CAATGGGACG
 GAGCGGGTGC TGAACCTGAT CAGATACTTC TATAACCAAG AGGAGTACGT
 GCGCTACGAC AGCGACGTCG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC CAAGTACTGG AACGGCCAGA AGGACCTCCT GGAGCAGAGG
 CGGGCCGAGG TGGACACCTA CTGCAGACAC AACTACCGGG TTGTTGAGAG
 CTTCACAGTG CAGCGGCGAG TTCAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACACCCTCC TGGTCTGCTC TGTGAACGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACG GCCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAG* 
>DL;IPD:MHC03448
IPD:MHC03448 Mane-DRB*W20:01 534 bases
 ATGGTGTTTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CGCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT GGAGCAGTTT AAGTCTGAGT GTCACTTCTT CAACGGGACG
 GAGCGGGTGC GGTACCTGCA GAGATACTTC TATAACCAGG AGGAGTACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCGTAGCGC CGAGTACTTC AACAGCCAGA AGGACTTCCT GGAGCGGAGG
 CGGGCCCAGG TGGACAACTA CTGCAGACAC AACTACGGGG TTGTGGAGAG
 CTTCACAGTG CAGCGGCGAG TCCATCCTAA GGTGACTGTG TATCCTTCAA
 AGACCCAGCC CCTGCAGCAC CACACCCTCC TGGTCTGCTC TGTGAGTGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACG GCCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAC* 
>DL;IPD:MHC03930
IPD:MHC03930 Mane-DRB*W21:01 226 bases
 TAAGTCTGAG TGTCATTTCT TCAATGGGAC GGAGCGGGTG CGGTTCCTGG
 AGAGATACTT CTATAACCAG GAGGAGTACG TGCGCTTCGA CAGCGACGTG
 GGGGAGTACC GGGCGGTGTC GGAGCTGGGG CGGCGTAGCG CCGAGTACTG
 GAACGGCCAG AAGGGCTACC TGGAGCAGAA GCGGGGCCAG GTTGACAACT
 ACTGCAGACA CAACTACGGG GTTGGT*  
>DL;IPD:MHC03993
IPD:MHC03993 Mane-DRB*W21:02 534 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CGCTGACAAT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT GGAGCAGGTT AAGTCTGAGT GTCATTTCTT CAATGGGACG
 GAGCGGGTGC GGTTCCTGGA GAGATACTTC TATAACCAGG AGGAGTACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGTCG GAGCTGGGGC
 GGCGTAGCGC CGAGTACTGG AACGGCCAGA AGGGCTACCT GGAGCAGAAG
 CGGGGCCAGG TTGACAACTA CTGCAGACAC AACTACGGGG TTGTGGAGAG
 CTTCACAGTG CAGCGGCGAG TCCAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACACCCTGC TGGTCTGCTC TGTGAGTGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACG GCCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAG* 
>DL;IPD:MHC03897
IPD:MHC03897 Mane-DRB*W25:01 225 bases
 TAAGTATGAG TGTCACTTCT TCAATGGGAC GGAGCGGGTG CGGTTCCTGG
 AGAGACACAT CAGTAACCAA GAGGAGAACG TGCGCTTCGA CAGCGACGTG
 GGGGAGTACC GGGCGGTGAC GGAGCTGGGG CGGCCTGACG CCGAGTCCTG
 GAACAGCCAG AAGGACATCC TGGAAGACAA TCGGGCCGCG GTGGACACCT
 ACTGCAGACA CAACTACCGG ATTGC*  
>DL;IPD:MHC03921
IPD:MHC03921 Mane-DRB*W25:02 226 bases
 TAAGTATGAG TGTCACTTCT TCAATGGGAC GGAGCGGGTG CGGTTCCTGG
 AGAGACACAT CAGTAACCAA GAGGAGAACG TGCGCTTCGA CAGCGACGTG
 GGGGAGTACC GGGCGGTGAC GGAGCTGGGG CGGCCTGACG CCGAGTCCTG
 GAACAGCCAG AAGGACTTCC TGGAAGACAG GCGGGCCGCG GTGGACAACT
 ACTGCAGATA CAACTACCGG GTTGGT*  
>DL;IPD:MHC04580
IPD:MHC04580 Mane-DRB*W25:03 534 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAA CTCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT GGAGCAGGCT AAGGCTGAGT GTCACTTCTT CAATGGGACG
 GAGCGGGTGC GGTTCCTGCA GAGACACATC AGTAACCAAG AGGAGAACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC CGAGTACTGG AACAGTCAGA AGGACATCCT GGAGGAGAAG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACCGGA TTGCGGAGAG
 CTTCACAGTG CAGCGGCGAG TCCAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAATGGT
 TTCTATCCAG GCAGCACTGA AGTCAGGTGG TTCCGGAACG GCCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAG* 
>DL;IPD:MHC04588
IPD:MHC04588 Mane-DRB*W25:04 535 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CTCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TGTGGCTGGG GACACCCGAC
 CACGTTTCTT GGAGCAGGCT AAGGCTGAGT GTCACTTCTT CAATGGGACG
 GAGCGGGTGC GGTTCCTGGA GAGACACTTC TATAACCAGG AGGAGTTCCT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTACCGC CGAGTCCTGG AACAGTCGGA AGGACGTCCT GGAGCGGGCG
 CGGACCGCAG CGGACACCTA CTGCAGACAC AACTACCGGG GTGGTGAGAG
 CTTCACAGTG CAGCGGCGAG TCCAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAACGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACG GCCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCACA* 
>DL;IPD:MHC03920
IPD:MHC03920 Mane-DRB*W26:01 226 bases
 TAAGTGTGAG TGTCACTTCT TCAACGGGAC GGAGCGGGTG CGGTTCCTGG
 AGAGACACTT CTATAACCAG GAGGAGTTCG TGCGCTTCGA CAGCGACGTG
 GGGGAGTACC GGGCGGTGAC GGAACTGGGG AGGCCTGCAG CCGAGTACTG
 GAACGGCCAG AAGGACTTCC TGGAAGACAG GCGGGCCCAG GTGGACACCG
 TGTGCAGACA CAACTACGGG GTTTTT*  
>DL;IPD:MHC03449
IPD:MHC03449 Mane-DRB*W27:01 534 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CTCTCACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TGTGGCTGGG GACACCCGAT
 CACGTTTCTT GGAGCAGGCT AAGTCTGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTACCTGCA GAGATACCTC TATAACCAGG AGGAGTACGT
 GCTCTTCGAC AGCGACGTGG GGGAGCACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC CGAGTACTGG AACAGCCAGA AGGACATCCT GGAAGACCAG
 CGGGCCGCGG TGGACACCTT CTGCAGATAC AACTACCGGG TTTTTGAGAG
 CTTCACAGTG CAGCGGCGAG TCCAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACACCCTCC TGGTCTGCTC TGTGAATGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACG GCCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAG* 
>DL;IPD:MHC03991
IPD:MHC03991 Mane-DRB*W27:02 534 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CTCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT GGAGCAGGTT AAGTCTGAGT GTCACTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGCA GAGATACATC TATAACCAGG AAGAGTACGT
 GCGCTTCGAC AGCGACGTGG GGGAGCACCG GGCGGTGACG GAGCTGGGGC
 GGCGTAGCGC CGAGTACTTC AACAGCCAGA AGGACTTCCT GGAAGACCAG
 CGGGCCGCGG TGGACACCTA CTGCAGATAC AACTACGGGG TTGGTGAGAG
 CTTCACAGTG CAGCGGCGAG TCCAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACACCCTGC TGGTCTGCTC TGTGAACGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACG ACCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAG* 
>DL;IPD:MHC00631
IPD:MHC00631 Mane-DRB*W2:01 267 bases
 CACGTTTCCT GGGGCATGCT AAGTCAGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGCA GAGATACATC TATAACCAGG AGGAGTTGGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGTCGC CGAGTCCTGG AACAGTCGGA AGGACTTCCT GGAGCGGGAG
 CGGGCCCAGG TGGACACCTG CAGACACAAC TACGGGGGTG TGGAGAGCTT
 CACAGTGCAG CGGCGAG*   
>DL;IPD:MHC00632
IPD:MHC00632 Mane-DRB*W2:02 267 bases
 CACATTTCTT GGATCAGGTT AAGTATGAGT GTCATTTCTT CAATGGGACG
 GAGCGGGTGC GGCTCCTGGG CAGACACTTC TATAACCAGG AGGAGTTAGT
 GCGCTTCGAC AGCGACGTCG GGGAGTACCG GGCGGTGTCG GAGCTGGGGC
 GGCCTGACGC CGAGAACTTG AACGCTCGGA AGGACGTCCT GGAGCAGGCG
 CGGGCCCAGG TGGACACCTG CAGACACAAC TACGGGGTTG TGGAGAGCTT
 CACAGTGCAG CGGCGAG*   
>DL;IPD:MHC03913
IPD:MHC03913 Mane-DRB*W2:03 226 bases
 TAAGTCAGAG TGTCATTTCT TCAACGGGAC GGAGCGGGTG CGGTTCCTGC
 AGAGATACAT CTATAACCAG GAGGAGTTGG TGCGCTTCGA CAGCGACGTG
 GGGGAGTTCC GGGCGGTGAC GGAGCTGGGG CGGCCTGTCG CCGAGTCCTG
 GAACAGTCGG AAGGACATCC TGGAGCGGGA GCGGGCCCAG GTGGACACCT
 TCTGCAGACA CAACTACGGG GGTGTG*  
>DL;IPD:MHC03914
IPD:MHC03914 Mane-DRB*W2:04 226 bases
 TAAGTCAGAG TGCCATTTCT TCAACGGGAC GGAGCGGGTG CGGTTCCTGC
 AGAGATACAT CTATAACCAG GAGGAGTTCG TGCGCTTCGA CAGCGACGTG
 GGGGAGTTCC GGGCGGTGAC GGAGCTGGGG CGGCCTGACG CCGAGTCCTG
 GAACACTCGG GAGGACATCC TGGAGCGGGA GCGGGCCCAG GTGGACACCT
 TCTGCAGACA CAACTACGGG GGTGTG*  
>DL;IPD:MHC03915
IPD:MHC03915 Mane-DRB*W2:05 226 bases
 TAAGTCAGAG TGTCATTTCT TCAACGGGAC GGAGCGGGTG CGGTTCCTGC
 AGAGATACAT CTATAACCAG GAGGAGTTCG TGCGCTTCGA CAGCGACGTG
 GGGGAGTTCC GGGCGGTGAC GGAGCTGGGG CGGCCTGTCG CCGAGTCCTG
 GAACAGTCGG AAGGACATCC TGGAGCGGGA GCGGGCCCAG GTGGACACCT
 TCTGCAGACA CAACTACGGG GGTGTG*  
>DL;IPD:MHC03916
IPD:MHC03916 Mane-DRB*W2:06 531 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CTCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAG
 CACGTTTCCT GGGGCATGCT AAGTCAGAGT GCCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGCA GAGATACATC TATAACCAGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGTCGC CGAGTCCTGG AACAGTCGGA AGGACTTCCT GGAGCGGGAG
 CGGGCCCAGG TGGACACCTG CAGACACAAC TACGGGGTTG GTGAGAGCTT
 CACAGTGCAG CGGCGAGTCC AACCTAAGGT GACTGTGTAT CCTGCAAAGA
 CCCAGCCCCT GCAGCACCAC ACCCTCCTGG TCTGCTCTGT GAGTGGTTTC
 TATCCAGGCA GCATTGAAGT CAGGTGGTTC CGGAACGGCC AGGAAGAGAA
 GGCTGGGGTG GTGTCCACAG GCCTGATCCA G* 
>DL;IPD:MHC03917
IPD:MHC03917 Mane-DRB*W2:07 226 bases
 TAAGTCAGAG TGCCATTTCT TCAACGGGAC GGAGCGGGTG CGGTTCCTGG
 ACAGATACTT CCATAACCAG GAGGAGTTCG TGCGCTTCGA CAGCGACGTG
 GGGGAGTTCC GGGCGGTGAC GGAGCTGGGG CGGCCTGACG CCGAGTCCTG
 GAACACTCGG GAGGACATCC TGGAGCGGGA GCGGGCCCAG GTGGACACCT
 TCTGCAGACA CAACTACGGG GTTGTG*  
>DL;IPD:MHC03918
IPD:MHC03918 Mane-DRB*W2:08 531 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CTCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCCT GGGGCATGCT AAGTCAGAGT GCCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGCA GAGATACATC TATAACCAGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGTCGC CGAGTCCTGG AACAGTCGGA AGGACTTCCT GGAGCGGGAG
 CGGGCCCAGG TGGACACCTG CAGACACAAC TACGGGGTTG GTGAGAGCTT
 CACAGTGCAG CGGCGAGTCC AACCTAAGGT GACTGTGTAT CCTGCAAAGA
 CCCAGCCCCT GCAGCACCAC ACCCTCCTGG TCTGCTCTGT GAGTGGTTTC
 TATCCAGGCA GCATTGAAGT CAGGTGGTTC CGGAACGGCC AGGAAGAGAA
 GGCTGGGGTG GTGTCCACAG GCCTGATCCA G* 
>DL;IPD:MHC04581
IPD:MHC04581 Mane-DRB*W2:09 531 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CTCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCCT GGGGCATGCT AAGTCAGAGT GCCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGCA GAGATACATC TATAACCAGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGTCGC CGAGTCCTGG AACAGTCGGA AGGACTTCCT GGAGCGGGAG
 CGGGCCCAGG TGGACACCTG CAGACACAAC TACGGGGTTG GTGAGAGCTT
 CACAGTGCAG CGGCGAGTCC AACCTAAGGT GACTGTGTAT CCTGCAAAGA
 CCCAGCCCCT GCAGCACCAC ACCCTCCTGG TCTGCTCTGT GAGTGGTTTC
 TATCCAGGCA GCATTGAAGT CAGGTGGTTC CGGAACGGCC AGGAAGAGAA
 GGCTGGGGTG GTGTCCACAG GCCTGATCCA G* 
>DL;IPD:MHC04582
IPD:MHC04582 Mane-DRB*W2:10 531 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CTCTCACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TGTGGCTGGG GACACCCGAC
 CACGTTTCCT GGGGCATGCT AAGTCAGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGCA GAGATACATC TATAACCAGG AGGAGTTGGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGTCGC CGAGTCCTGG AACAGTCGGA AGGACTTCCT GGAGCGGGAG
 CGGGCCCAGG TGGACACCTG CAGACACAAC TACGGGGTTG GTGAGAGCTT
 CACAGTGCAG CGGCGAGTCC AACCTAAGGT GACTGTGTAT CCTGCAAAGA
 CCCAGCCCCT GCAGCACCAC AACCTCCTGG TCTGCTCTGT GAGTGGTTTC
 TATCCAGGCA GCATTGAAGT CAGGTGGTTC CGGAACGGCC AGGAAGAGAA
 GGCTGGGGTG GTGTCCACAG GCCTGATCCA G* 
>DL;IPD:MHC04583
IPD:MHC04583 Mane-DRB*W2:11 531 bases
 ATGGTGTGTC TGAGGCTCCC TGGAGGCTCC TGCATGGCAC CTCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACATTTCTT GGATCAGGTT AAGTATGAGT GTCATTTCTT CAATGGGACG
 GAGCGGGTGC GGCTCCTGGG CAGACACTTC TATAACCAGG AGGAGTTAGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGTCG GAGCTGGGGC
 GGCCTGACGC CGAGAACTTG AACGCTCGGA AGGACTTCCT GGAGCAGGCG
 CGGGCCCAGG TGGACACCTG CAGACACAAC TACGGGGTTG TGGAGAGCTT
 CACAGTGCAG CGGCGAGTCC AACCTAAGGT GACTGTGTAT CCTGCAAAGA
 CCCAGCCCCT GCAGCACCAC ACCCTCCTGG TCTGCTCTGT GAACGGTTTC
 TATCCAGGCA GCATTGAAGT CAGGTGGTTC CGGAACGGCC AGGAAGAGAA
 GGCTGGGGTG GCGTCCACAG GCCTGATCCA G* 
>DL;IPD:MHC03459
IPD:MHC03459 Mane-DRB*W31:01 531 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGGATGGCAG CTCTCACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT GGAGTACGCT AAGGGTGAGT GTCACTTCTT CAACGGGACG
 GAGCGGGTGC GGTACCTGGA GAGATACATC TATAACCAGG AGGAGAACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC CGAGTACTGG AACAGCCAGA AGGACGTCCT GGAGCAGAGG
 CGGGCCGTGG TGGACACCTG CAGATATGAC TACGGGATTG CGGAGAGCTT
 CACAGTGCAG CGGCGAGTCA AACCTAAGGT GACTGTGTAT CCTGCAAAGA
 CCCAGCCCCT GCAGCACCAC AACCTCCTGG TCTGCTCTGT GAGTGGTTTC
 TATCCAGGCA GCATTGAAGT CAGGTGGTTC CGGAACGGCC AGGAAGAGAA
 GGCTGGGGTG GTGTCCACAG GCCTGATCCA G* 
>DL;IPD:MHC04584
IPD:MHC04584 Mane-DRB*W33:01 534 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CTCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCAAC
 CACGTTTCTT GGAGCAGGCT AAGTCTGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA TAGATACATC CATAACCAAG AGGAGAACCT
 GCGCTTCGAC AGCGACGTAG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC CGAGTACTGG AACAGCCAGA AGGACTTCCT GGAGCAGAGG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG CTGTGGAGAG
 CTTCACAGTG CAGCGGCGAG TCCAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACACCCTCC TGGTCTGCTC TGTGAGTGGT
 TTCTATCCAG GCACCATTGA AGTCAGGTGG TTCCGGAACG GCCAAGAGGA
 GAAGACTGGG GTGGTGTCCA CAGGCCTGAT CCAG* 
>DL;IPD:MHC03502
IPD:MHC03502 Mane-DRB*W3:01 226 bases
 TAAACGTGAG TGTCATTTCT TCAATGGGAC GGAGCGGGTG CGGTTCCTGG
 ACAGATACTT CCATAACCAG GAGGAGTACG CGCGCTTCGA CAGCGACGTG
 GGGGAGTTCT GGGCGGTGAC GGAGCTGGGG CGGCGTAGCG CGGAGTACTG
 GAACAGCCAG AAGGACTTTC TGGAGCAGGC GCGGACCGCG GTGGACAACT
 ACTGCAGACA CAACTACGGG GTTGGC*  
>DL;IPD:MHC04585
IPD:MHC04585 Mane-DRB*W3:02 534 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CTCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT GGAGCAGGCT AAACGTGAGT GTCATTTCTT CAATGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC CATAACCAGG AGGAGTACGC
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCGTAGCGC GGAGTACTGG AACAGCCAGA AGGACTTTCT GGAGCAGGCG
 CGGACCGCGG TGGACAACTA CTGCAGACAC AACTACGGGG TTGGCGAGAG
 CTTCACAGTG CAGCGGCGAG TCCAACCTAA GGTGACTGTG TATCCTGAAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAACGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACG GCCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAG* 
>DL;IPD:MHC04589
IPD:MHC04589 Mane-DRB*W3:03 534 bases
 ACGCTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CTCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTAGC TTTGGCTGGG GACACCAGAC
 CACGTTTCTT GGAGCAGGCT AAACGTGAGT GTCATTTCTT CAATGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC CATAACCAGG AGGAGTACGC
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCGTAGCGC GGAGTACTGG AACAGCCAGA AGGACTTTCT GGAGCAGGCG
 CGGACCGCGG TGGACAACTA CTGCAGACAC AACTACGGGG TTGGCGAGAG
 CTTCACAGTG CAGCGGCGAG TCCAACCTAA GGTGACTGTG TATCCTGAAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAACGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACA GCCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAG* 
>DL;IPD:MHC04590
IPD:MHC04590 Mane-DRB*W3:04 534 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CTCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT GGAGCAGGCT AAACGTGAGT GTCATTTCTT CAATGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC CATAACCAGG AGGAGTACGC
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCGTAGCGC GGAGTACTGG AACAGCCAGA AGGACTTTCT GGAGCAGGCG
 CGGACCGCGG TGGACAACTA CTGCAGACAC AACTACGGGG TTGGCGAGAG
 CTTCACAGTG CAGCGGCGAG TCCAACCTAA GGTGACTGTG TATCCTGAAA
 AGACCCAGCC CCTGCAGCAC CACACCCTCC TGGTCTGCTC TGTGAACGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACG GCCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAG* 
>DL;IPD:MHC03985
IPD:MHC03985 Mane-DRB*W4:01 226 bases
 TAAGCCTGAG TGTCATTTCT TCAACGGGAC GGAGCGGGTG CGGTTCCTGG
 AGAGACACTT CTATAACCAG GAGGAGAACC TGCGCTTCGA CAGCGACGTG
 GGGGAGTACC GGGCGGTGTC GGAGCTGGGG CGGCCTGAAG CCCAGTCCTG
 GAACAGCCAG AAGGACTTCC TGGAGCAGAG GCGGGCCGCG GTGGACACCT
 ACTGCAGACA CAACTACCGG ATTGGT*  
>DL;IPD:MHC03509
IPD:MHC03509 Mane-DRB*W5:01 534 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CTCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT GGAGCAGGCT AAGTCTGAGT GTCACTTCTT CAACGGGACG
 GAGCGGGTGC GGTACCTGGA CAGATACATC TATAACCAGG AGGAGTACGT
 GCGCTTCGAC AGCGACGTGG GGGAGCACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC CGAGTACTGG AACAGCCAGA AGGACTTCCT GGAAGACCAG
 CGGGCCGCGG TGGACAACTA CTGCAGACAC AACTACGGGG TTGGTGAGAG
 CTTCACAGTG CAGCGGCGAG TCCAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAACGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACG GCCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAG* 
>DL;IPD:MHC03896
IPD:MHC03896 Mane-DRB*W5:02 226 bases
 TAAGTCTGAG TGTCACTTCT TCAACGGGAC GGAGCGGGTG CGGTTCCTGG
 ACAGATACAT CTATAACCAG GAGGAGTACG TGCGCTTCGA CAGCGACGTG
 GGGGAGCACC GGGCGGTGAC GGAGCTGGGG CGGCCTGACG CCGAGTACTG
 GAACAGCCAG AAGGACTTCC TGGAAGACCA GCGGGCCGCG GTGGACAACT
 ACTGCAGACA CAACTACGGG GTTGGT*  
>DL;IPD:MHC03904
IPD:MHC03904 Mane-DRB*W63:01 226 bases
 TAAACGTGAG TGTCACTTCT TCAACGGGAC GGAGCGGGTG CGGTTCCTGG
 ACAGATACTT CTATAACCAG GAGGAGTTCG TGCGCTTCGA CAGCGACGTG
 GGGGAGTTCC GGGCGGTGAC GGAACTGGGG AGGCCTGTCG CGGAGAACTT
 GAACAGTCGG AAGGACTACC TGGAGCAGGC GCGGGCCGCG GTGGACAATT
 ACTGCAGATA CAACTACGGG GTTGGT*  
>DL;IPD:MHC03905
IPD:MHC03905 Mane-DRB*W63:02 226 bases
 TAAACGTGAG TGTCACTTCT TCAACGGGAC GGAGCGGGTG CGGTTCCTGG
 ACAGATACTT CTATAACCAG GAGGAGTTCG TGCGCTTCGA CAGCGACGTG
 GGGGAGTTCC GGGCGGTGAC GGAACTGGGG AGGCCTGTCG CGGAGAACTT
 GAACAGCCAG AAGGACTACC TGGAGCAGGC GCGGGCCGCG GTGGACAATT
 ACTGCAGATA CAACTACGGG GTTGGT*  
>DL;IPD:MHC03922
IPD:MHC03922 Mane-DRB*W64:01 226 bases
 TAAGGTTGAG TGTCACTTCT TCAACGGGAC GGAGCGGGTG CGGTTCCTGG
 AGAGATACTT CTATAACCAG GAGGAGTACG TGCGCTTCGA CAGCGACGTG
 GGGGAGTACC GGGCGGTGTC GGAGCTGGGG CGGCGTAGCG CCGAGTACTG
 GAACGGCCAG AAGGACATCC TGGAGCGGGC GCGGGCCGCG GTGGACACCT
 ACTGCAGACA CAACTACCGG ATTGGT*  
>DL;IPD:MHC03919
IPD:MHC03919 Mane-DRB*W65:01 226 bases
 TAAGGCTGAG TATCACTTCT TCAACGGGAC GGAGCGGGTG CGGTACCTGG
 AGAGATACAT CTATAACCAG TAGGAGTACG TGCGCTTCGA CAGCGACGTA
 GGGGAGTACC GGGCGGTGAC GGAGCTGGGG CGGCGTAGCG CCGAGTACTT
 CAACAGCCAG AAGGGCTACC TGGAGCAGAA GCGGGCCGCG GTGGACACCT
 ACTGCAGACA CAACTACGGG GTTGGT*  
>DL;IPD:MHC03984
IPD:MHC03984 Mane-DRB*W67:01 226 bases
 TAAGCCTGAG TGTCATTTCT TCAACGGGAC GGAGCGGGTG CGGTACCTGG
 TCAGATACAT CTATAACCAG GAGGAGTTCG TGCGCTTCGA CAGCGACGTG
 GGGGAGTTCC GGGCGGTGTC GGAGCTGGGG CGGCCTGTCG CCGAGTCCTG
 GAACGGCCAG AAGGACCTCC TGGAGCAGAG GCGGGCCGAG GTGGACACCG
 TGTGCAGACA CAACTACGGG GTTGGT*  
>DL;IPD:MHC03450
IPD:MHC03450 Mane-DRB*W69:01 226 bases
 TAAGTATGAG TGTCACTTCT TCAATGGGAC GGAGCGGGTG CGGTTCCTGG
 AGAGACACTT CTATAACCAG GAGGAGTTCG TGCGCTTCGA CAGCGACGTG
 GGGGAGTTCC GGGCGGTGAC GGAACTGGGG AGGCCTGACG CCGAGTACTG
 GAACAGCCAG AAGGACCTCC TGGAAGACAG GCGGGCCCAG GTGGACACCG
 TGTGCAGACA CAACTACGGG GTTGGT*  
>DL;IPD:MHC03501
IPD:MHC03501 Mane-DRB*W69:02 226 bases
 TAAGTATGAG TGTCACTTCT TCAATGGGAC GGAGCGGGTG CGGTTCCTGG
 AGAGACACTT CTATAACCAG GAGGAGTTCG TGCGCTTCGA CAGCGACGTG
 GGGGAGTACC GGGCGGTGAC GGAACTGGGG AGGCCTGACG CCGAGTACTG
 GAACAGCCAG AAGGACCTCC TGGAAGACAG GCGGGCCCAG GTGGACACCG
 TGTGCAGACA CAACTACGGG GTTGGT*  
>DL;IPD:MHC03451
IPD:MHC03451 Mane-DRB*W6:01 534 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CTCTGACAGC
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCGGAC
 CACGTTTCTT GAAGCAGGCT AAGGCTGAGT GTCACTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA GAGACACTTC TATAACCAGG AGGAGTACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCGTAGCGC CGAGTACTTC AACAGCCAGA AGGGCTACCT GGAGCAGAGG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG TTGTGGAGAG
 CTTCACAGTG CAGCGGCGAG TCCAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAACGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACG ACCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAG* 
>DL;IPD:MHC03508
IPD:MHC03508 Mane-DRB*W6:02 226 bases
 TAAGGCTGAG TGTCATTTCT TCAACGGGAC GGAGCGGGTG CGGTTGCTGG
 ACAGACACTT CTATAACCAG GAGGAGTACG TGCGCTATGA CAGCGACGTG
 GGGGAGTACC GGGCGGTGAC GGAGCTGGGG CGGCGTAGCG CGGAGTACTG
 GAACAGCCAG AAGGACTACC TGGAGCAGAG GCGGGCCGCG GTGGACACCT
 ACTGCAGACA CAACTACCGG ATTGGT*  
>DL;IPD:MHC03992
IPD:MHC03992 Mane-DRB*W74:01:01 226 bases
 TAAACATGAG TGTCACTTCT TCAATGGGAC GGAGCGGGTG CGGTTCCTGG
 ATAGATACTT CCATAACCAG GAGGAGTTCG TGCGCTTCGA CAGCGACGTG
 GGGGAGTACC GGGCGGTGAC AGAGCTGGGG CGGCCTGACG CCCAGTCCTG
 GAACAGCCAG AAGGACATCC TGGAAGACGC GCGGGCCGCG GTGGACACCT
 ACTGCAGATA CAACTACGGG GTTGTT*  
>DL;IPD:MHC04586
IPD:MHC04586 Mane-DRB*W74:01:02 534 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CTCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACTCGAC
 CACGTTTCTT GGAGCAGGTT AAACATGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA TAGATACTTC CATAACCAGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACA GAGCTGGGGC
 GGCCTGACGC CCAGTCCTGG AACAGCCAGA AGGACATCCT GGAAGACGCG
 CGGGCCGCGG TGGACACCTA CTGCAGATAC AACTACGGGG TTGTTGAGAG
 CTTCACAGTG CAGCGGCGAG TCCAACCTAA GGTAACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAACGGT
 TTCTATCCAG GCACCATTGA AGTCAGGTGG TTCCGGAACG GCCAGAAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAG* 
>DL;IPD:MHC00628
IPD:MHC00628 Mane-DRB1*03:01 270 bases
 CACGTTTCTT GGAGTACTCT ACATCTGAGT GTCACTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAACCAGG AGGAGTACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGTCG GAGCTGGGGC
 GGCGTAGCGC CGAGTACTGG AACGGCCAGA AGGACATCCT GGAAGACGCG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACCGGA TTGGTGAGAG
 CTTCACAGTG CAGCGGCGAG *  
>DL;IPD:MHC03457
IPD:MHC03457 Mane-DRB1*03:02 534 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CTCTCACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT GGAGTACTCT ACATCTGAGT GTCACTTCTT CAACGGGACG
 GAGCGGGTGC GGTACCTGGA CAGATACTTC TATAACCAGG AGGAGGACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGTCG GAGCTGGGGC
 GGCCTGTCGC CGAGTACTGG AACAGCCAGA AGGACATCCT GGAAGACCAG
 CGGGCCTCGG TGGACACCTT CTGCAGACAC AACTACCGGG TTGCGGAGAG
 CTTCACAGTG CAGCGGCGAG TCCAACCTAA GGTGACTGTG TATCCTTCAA
 AGACCCAGCC CCTGCAGCAC CACACCCTCC TGGTCTGCTC TGTGAACGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACG GCCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAG* 
>DL;IPD:MHC03458
IPD:MHC03458 Mane-DRB1*03:03 226 bases
 TACATCTGAG TGTCACTTCT TCAACGGGAC GGAGCGGGTG CGGTACCTGG
 ACAGATACTT CTATAACCAG GAGGAGAACG TGCGCTTCGA CAGCGACGTG
 GGGGAGTACC GGGCGGTGAC AGAGCTGGGG CGGCCTGACG CCGAGTACTG
 GAACGGCCAG AAGGACATCC TGGAAGACCA GCGGGCCTCG GTGGACACCT
 ACTGCAGACA CAACTACCGG GTTGCG*  
>DL;IPD:MHC03460
IPD:MHC03460 Mane-DRB1*03:04 226 bases
 TACATCTGAG TGTCACTTCT TCAATGGGAC GGAGCGGGTG CGGTACCTGG
 ACAGATACTT CTATAACCAA GAGGAGAACG TGCGCTTCGA CAGCGACGTG
 GGGGAGTACC GGGCGGTGTC GGAGCTGGGG CGGCCTGACG CCGAGTACTG
 GAACAGCCAG AAGGACATCC TGGAGCAGAA GCGGGCCCGG GTGGACAACT
 ACTGCAGACA CAACTACGGG GTTTTT*  
>DL;IPD:MHC03461
IPD:MHC03461 Mane-DRB1*03:05 226 bases
 TACATCTGAG TGTCACTTCT TCAACGGGAC GGAGCGGGTG CGGTTCCTGG
 ACAGATACTT CTATAACCAG GAGGAGTACG TGCGCTTCGA CAGCGACGTG
 GGGGAGTACC GGGCGGTGAC GGAGCTGGGG CGGCGTAGCG CCGAGTACTG
 GAACGGCCAG AAGGACATCC TGGAAGACGC GCGGGCCGCG GTGGACACCT
 ACTGCAGACA CAACTACCGG ATTGGT*  
>DL;IPD:MHC03462
IPD:MHC03462 Mane-DRB1*03:06 226 bases
 TACATCTGAG TGTCACTTCT TCAACGGGAC GGAGCGGGTG CGGTTCCTGG
 ACAGATACTT CTATAACCAG GAGGAGTACG TGCGCTTCGA CAGCGACGTC
 GGGGAGTACC GGGCGGTGAC GGAGCTGGGG CGGCGTAGCG CCGAGTACTG
 GAACGGCCAG AAGGACATCC TGGAAGACGC GCGGGCCGCG GTGGACACCT
 ACTGCAGACA CAACTACGGG GTTTTT*  
>DL;IPD:MHC03463
IPD:MHC03463 Mane-DRB1*03:07 226 bases
 TACATCTGAG TGTCACTTCT TCAACGGGAC GGAGCGGGTG CGGTACCTGG
 ACAGATACTT CTATAACCAG GAGGAGTACG TGCGCTTCGA CAGCGACGTG
 GGGGAGTACC GGGCGGTGTC GGAGCTGGGG CGGCCTGACG CCGAGTACTT
 CAACAGCCAG AAGGACATCC TGGAGCAGAA GCGGGCCCGG GTGGACAATT
 ACTGCAGACA CAACTACCGG GTTGGT*  
>DL;IPD:MHC03464
IPD:MHC03464 Mane-DRB1*03:08 226 bases
 TACATCTGAG TGTCACTTCT TCAATGGGAC GGAGCGGGTG CGGTACCTGG
 ACAGATACTT CTATAACCAA GAGGAGAACG TGCGCTTCGA CAGCGACGTG
 GGGGAGTACC GGGCGGTGAC GGAGCTGGGG CGGCCTGACG CCGAGTACTG
 GAACAGCCAG AAGGACATCC TGGAGCAGAA GCGGGCCCGG GTGGACAATT
 ACTGCAGACA CAACTACGGG GTTTTT*  
>DL;IPD:MHC03891
IPD:MHC03891 Mane-DRB1*03:09 226 bases
 TACATCTGAG TGTCACTTCT TCAACGGGAC GGAGCGGGTG CGGTTCCTGG
 ACAGATACTT CTATAACCAG GAGGAGTACG TGCGCTTCGA CAGCGACGTG
 GGGGAGTTCC GGGCGGTGAC GGAGCTGGGG CGGCGTAGCG CCGAGTACTG
 GAACGGCCAG AAGGACATCC TGGAAGACGC GCGGGCCGCG GTGGACACCT
 ACTGCAGACA CAACTACCGG ATTGGT*  
>DL;IPD:MHC03894
IPD:MHC03894 Mane-DRB1*03:10 534 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CTCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGACTGGG GACATCCGAC
 CACGTTTCTT GGAGTACTCT ACATCTGAGT GTCACTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAACCAGG AGGAGTACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACA GAGCTGGGGC
 GGCCTGACGC CGAGTACTGG AACGGCCAGA AGGACTTCCT GGAAGACAGG
 CGGGCCTCGG TGGACAACTA CTGCAGACAC AACTACGGGG TTGTGGAGAG
 CTTCACAGTG CAGCGGCGAG TCCAACCTAA GGTGACTGTG TATCCTTCAA
 AGATCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAATGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAATG GCCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAC* 
>DL;IPD:MHC03900
IPD:MHC03900 Mane-DRB1*03:11 225 bases
 TACATCTGAG TGTCACTTCT TCAACGGGAC GGAGCGGGTG CGGTACCTGG
 ACAGATACTT CTATAACCAG GAGGAGTACG TGCGCTTCGA CAGCGACGTG
 GGGGAGCACC GGGCGGTGTC GGAGCTGGGG CGGCCTGACG CCGAGTACTG
 GAACAGCCAG AAGGACATCC TGGAAGACCA GCGGGCCTCG GTGGACACCT
 TCTGCAGACA CAACTACCGG GTTGC*  
>DL;IPD:MHC03895
IPD:MHC03895 Mane-DRB1*03:12 226 bases
 TACATCTGAG TGTCACTTCT TCAATGGGAC GGAGCGGGTG CGGTTCCTGG
 AGAGATACTT CTATAACCAG GAGGAGAACG TGCGCTTCGA CAGCGACGTG
 GGGGAGTACC GGGCGGTGTC GGAGCTGGGG CGGCCTGACG CCGAGTACTG
 GAACGGCCAG GAGGACATCC TGGAGCTGAA GCGGGGCCAG GTGGACAATT
 ACTGCAGACA CAACTACGGG GTTTTT*  
>DL;IPD:MHC03892
IPD:MHC03892 Mane-DRB1*03:13 534 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CTCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT GGAGTACTCT ACATCTGAGT GTCACTTCTT CAATGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAACCAGG AGGAGAACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGTCG GAGCTGGGGC
 GGCCTGACGC CGAGAACTGG AACAGTCGGA AGGACATCCT GGAGCGGGAG
 CGGGCCGCGG TGGACAATTA CTGCAGATAC AACTACCGGG TTGGTGAGAG
 CTTCACAGTG CAGCGGCGAG TCCAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACACCCTCC TGGTCTGCTC TGTGAACGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACG GCCAGGAAGA
 GAAAGCTGGG GTGGTGTCCA CAGGCCTGAT CCAC* 
>DL;IPD:MHC03893
IPD:MHC03893 Mane-DRB1*03:14 227 bases
 TACATCTGAG TGTCACTTCT TCAACGGGAC GGAGCGGGTG CGGTTCCTGG
 ACAGATACTT CTACAACCAG GAGGAGTACG TGCGCTTCGA CAGCGACGTG
 GGGGAGTACC GGGCGGTGTC GGAGCTGGGG CGGCCTGACG CCGAGAACTG
 GAACAGTCGG AAGGACATCC TGGAGCGGGC GCGGGCCGCG GTGGACACCT
 ACTGCAGACA CAACTACGGG GCTGTGG*  
>DL;IPD:MHC03901
IPD:MHC03901 Mane-DRB1*03:15 534 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAA CTCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT GGAGTACTCT ACATCTGAGT GTCACTTCTT CAATGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAACCAGG AGGAGAACCT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGTCG GAGCTGGGGC
 GGCCTGACGC CGAGTACTGG AACAGTCAGA AGGACTTCCT GGAGCAGAGG
 CGGGCCGCGG TGGACAACTA CTGCAGATAC AACTACCGGG TTGGTGAGAG
 CTTCACAGTG CAGCGGCGAG TCCAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAACGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACG GCCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAC* 
>DL;IPD:MHC03990
IPD:MHC03990 Mane-DRB1*04:01 534 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CGCTGACAAT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAG
 CACGTTTCTT GGAGCAGGTT AAACATGAGT GTCACTTCTT CAATGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAACCAGG AGGAGTACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCGTAGCGC CGAGTACTGG AACGGCCAGA AGGACCTCCT GGAGCAGAAG
 CGGGCCGCGG TGGACACCTA CTGCAGATAC AACTACGGGG TTGCGGAGAG
 CTTCACAGTG CAGCGGCGAG TCCAAGCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAACGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACG GTCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAG* 
>DL;IPD:MHC03994
IPD:MHC03994 Mane-DRB1*04:02 534 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CGCTGACAAT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTAGG GACACCCGAG
 CACGTTTCTT GGAGCAGGTT AAACATGAGT GTCACTTCTT CAATGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAACCAGG AGGAGTACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCGTAGCGC CGAGTACTGG AACAGCCAGA AGGACATCCT GGAAGACAGG
 CGGGCCGTGG TGGACACCTA CTGCAGACAC AACTACGGGG TTGGTGAGAG
 CTTCACAGTG CAGCGGCGAG TCCAAGCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACACCCTCC TGGTCTGCTC TGTGAACGGT
 TTCTATCCAG GCAGCGTTGA AGTCAGGTGG TTCCGGAACG GCCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAG* 
>DL;IPD:MHC04591
IPD:MHC04591 Mane-DRB1*04:03 534 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CGCTGACAAT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAG
 CACGTTTCTT GGAGCAGGTT AAACATGAGT GTCACTTCTT CAATGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAACCAGG AGGAGTACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCGTAGCGC CGAGTACTGG AACGGCCAGA AGGACCTCCT GGAGCAGAAG
 CGGGCCGCGG TGGACAACTA CTGCAGATAC AACTACGGGG TTGCGGAGAG
 CTTCACAGTG CAGCGGCGAG TCCAAGCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAACGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACG GTCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAG* 
>DL;IPD:MHC03906
IPD:MHC03906 Mane-DRB1*07:01 226 bases
 TAAGGCTAAG TGTCACTTCT TCAACGGGAC GGAGCGGGTG CGGTACCTGC
 AGAGACACTT CTATAACCAG GAGGAGTTCG TGCGCTTCGA CAGCGACGTG
 GGGGAGTTCC GGGCGGTGAC GGAGCTGGGG CGGCCTGTCG CCGAGAACTG
 GAACAGCCAG AAGGACTTCC TGGAGCAGAG GCGGGCCTCG GTGGACAATT
 ACTGCAGACA CAACTACAGG GGTGTG*  
>DL;IPD:MHC03908
IPD:MHC03908 Mane-DRB1*10:01 226 bases
 TAAGTTTGAG TGTCATTTCT TCAACGGGAC GGAGCGGGTG CGGTTCCTGA
 TCAGAGTCTT CCATAACCGA GAGGAGTACG CGCGCTTCGA CAGCGACGTG
 GGGGAGTTCC GGGCGGTGAC GGAGCTGGGG CGGCCTGCAG CCGAGTACTT
 GAACAGTCAG AAGGACTTCC TGGAGGAGAA GCGGGCCGCG GTGGACACCT
 ACTGCAGACA CAACTACCGG ATTGGT*  
>DL;IPD:MHC03909
IPD:MHC03909 Mane-DRB1*10:02 226 bases
 TAAGTTTGAG TGTCATTTCT TCAACGGGAC GGAGCGGGTG CGGTTCCTGA
 TCAGAGTCTT CTATAACCGA GAGGAGTATG TGCGCTTCGA CAGCGACGTG
 GGGGAGTTCC GGGCGGTGAC GGAGCTGGGG CGGCTTAGCG CCGAGTACTT
 CAACAGCCAG AAGGACTTCC TGGAGCAGAA GCGGGCCTCG GTGGACACCT
 ACTGCAGACA CAACTACGGG GCTGTG*  
>DL;IPD:MHC03910
IPD:MHC03910 Mane-DRB1*10:03 226 bases
 TAAGTTTGAG TGTCATTTCT TCAACGGGAC GGAGCGGGTG CGGTTCCTGA
 TCAGAGTCTT CTATAACCGA GAGGAGTACG CGAGCTTCGA CAGCGACGTG
 GGGGAGTTCC GGGCGGTGAC GGAGCTGGGG CGGCCTGACG CCAAGTACTG
 GAACAGCCAG AAGGACTTCC TGGAGGAGAA GCGGGCCGCG GTGGACACCT
 ACTGCAGACA CAACTACCGG GTTGGT*  
>DL;IPD:MHC03931
IPD:MHC03931 Mane-DRB1*10:04 534 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGTATGGCAG CTCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCAAT
 CACGTTTCTT GGAGCAGGTT AAGTTTGAGT GTCATTTCTT CAATGGGACG
 GAGCGGGTGC GGTTCCTGGA GAGACGCGTC CATAACCAAG AGGAGTACGC
 GCGCTTCGAC AGCGACGTCG GGGAGTACCG GGCGGTGACA GAGCTGGGGC
 GGCCTGACGC CGAGTACTGG AACGGCCAGA AGGACCTCCT GGAAGACAGG
 CGGGCCCAGG TGGACACCGT GTGCAGACAC AACTACCGGG TTGGTGAGAG
 CTTCACAGTG CAGCGGCGAG TCCAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC TCTGCAGCAC CACACCCTCC TGGTCTGCTC TGTGAATGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACG GCCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAG* 
>DL;IPD:MHC04592
IPD:MHC04592 Mane-DRB1*10:05 534 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CTCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT GGAGCAGGTT AAGTTTGAGT GTCACTTCTT CAACGGGACG
 GAGCGGGTGC GGTACCTGGT CAGATTCTTC TATAACCGAG AGGAGTATGC
 GCGCTTCGAC AGCCACGTGG GGGAGTTCCG GGCGGTGACG CAGCTGGGGC
 GGCCTGACGC TGAGTACTGG AACAGCCAGA AGGACATCCT GGAGCGGAAG
 CGGGCCGAGG TGGACACAGT GTGCAAACAC AACTACGGGG TTGTGGAGAG
 CTTCACAGTG CAGCGGCGAG TCCAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAACGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACG GCCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAG* 
>DL;IPD:MHC03511
IPD:MHC03511 Mane-DRB3*04:01 226 bases
 TAAGTCTGAG TGTCATTTCT TCAACGGGAC GGAGCGGGTG CGGTACCTGC
 AGAGACACTT CTATAACCAG GAGGAGTTCG TGCGCTTCGA CAGCGACGTG
 GGGGAGTTCC GGGCGGTGTC GGAGCTGGGG CGGCCTGTCG CCGAGTCCTG
 GAACAGCCAG AAGGACTACC TGGAGCAGAG GCGGGCCGCG GTGGACAACT
 ACTGCAGATA CAACTACCAG GTTGGT*  
>DL;IPD:MHC03506
IPD:MHC03506 Mane-DRB3*04:02 534 bases
 ATGGTGTTTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CGCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT GGAGCAGGGT AAGTCTGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTACCTGCA GAGACACTTC TATAACCAGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGTCG GAGCTGGGGC
 GGCCTGTCGC CGAGTACTGG AACAGCCAGA AGGACTACCT GGAGCAGAGG
 CGGGCCCAGG TTGACAACTA CTGCAGATAC AACTACCGGG TTGGTGAGAG
 CTTCACAGTG CAGCGGCGAG TCCAACCTAA GGTGACTGTG TATCCTGAAA
 AGACCCAGCC CCTGCAGCAC CACACCCTCC TGGTCTGCTC TGTGAACGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACG GCCAGGAAGA
 GAAAGCTGGG GTGGTGTCCA CAGGCCTGAT CCAG* 
>DL;IPD:MHC03507
IPD:MHC03507 Mane-DRB3*04:03 534 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CTCTCACAGT
 GACACTGATG GTGCTGAGCT CCCCACTAGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT GGAGCAGGGT AAGTCTGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTACCTGCA GAGATACTTC TATAACCAGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGTCG GAGCTGGGGC
 GGCCTGACGC CGAGTACTTC AACAGTCAGA AGGACTTCCT GGAGCAGAGG
 CGGGCCCAGG TTGACAACTA CTGCAGATAC AACTACCGGG TTGGTGAGAG
 CTTCACAGTG CAGCGGCGAG TCCAACCTAA GGTGACTGTG TATCCTTCAA
 AGACCCAGCC CCTACAGCAC CACACCCTCC TGGTCTGCTC TGTGAGTGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACG GCCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAG* 
>DL;IPD:MHC03911
IPD:MHC03911 Mane-DRB3*04:04 226 bases
 TAAGTCTGAG TGTCATTTCT TCAACGGGAC GGAGCGGGTG CGGTACCTGC
 AGAGACACTT CTATAACCAG GAGGAGTTCG TGCGCTTCGA CAGCGACGTG
 GGGGAGTTCC GGGCGGTGTC GGAGCTGGGG CGGCCTGTCG CCGAGTCCTG
 GAACAGCCAG AAGGACTACC TGGAGCAGAG GCGGGCCCAG GTTGACAACT
 ACTGCAGATA CAACTACCGG GTTGGT*  
>DL;IPD:MHC03453
IPD:MHC03453 Mane-DRB5*01:01 534 bases
 ATGGTGTGTC TGAGGTTCCC TGGAGGCTCC TGCATGGCAG CTCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCATTGGC TTTGGCTGGG GACACCCAAC
 CACGTTTCTT GAAGCAGGAT ATGCATGAGT GTCATTTCTT CAACGGAACC
 GAGCGGGTGC GGTACCTGCA CAGAGACATC TACAACCAAG AGGAGGACTT
 GCGCTTCGAC AGCGACGTCG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC CGAGTACTGG AACAGCCAGA AGGACATCCT GGAAGACGCG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG TTGTGGAGAG
 CTTCACAGTG CAGCGGCGAG TTCAGCCTAA GGTAACTGTG TATCCTGCAA
 AGACCCAGGC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAATGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGAAATG GCCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAG* 
>DL;IPD:MHC03505
IPD:MHC03505 Mane-DRB5*01:02 221 bases
 ATGAGTGTCA TTTCTTCAAC GGAACCGAGC GGGTGCGGTA CCTGCACAGA
 GACATCTACA ACCAAGAGGA GGACTTGCGC TTCGACAGCG ACGTGGGGGA
 GTACCGGGCG GTGACGGAGC TGGGGCGGCC TGACGCCGAG TACTGGAACA
 GCCAGAAGGA CATCCTGGAG CGGAGGCGGG CCGCGGTGGA CACCTACTGC
 AGACACAACT ACGGGGTTGT G*  
>DL;IPD:MHC03510
IPD:MHC03510 Mane-DRB5*01:03 534 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGGCAG CTCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT GAAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGCA CAGAGACATC TACAACCAAG AGGAGGACTT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC CGAGTACTGG AACAGCCAGA AGGACATCCT GGAAGACGCG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG TTGTGGAGAG
 CTTCACAGTG CAGCGGCGAG TTCAGCCTAA GGTAACTGTG TATCCTGCAA
 AGACCCAGGC CCTGCAGCAC CACACCCTCC TGGTCTGCTC TGTGAACGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGAAATG GCCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAG* 
>DL;IPD:MHC03452
IPD:MHC03452 Mane-DRB5*03:01 534 bases
 ATGGTGTGTC TGAGGTTCCC TGGAGGCTCC TGCATGGCAG CTCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCATTGGC TTTGGCTGGG GACACCCAAC
 CACGTTTCTT GAAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGCA CAGAGACATC CATAACCAAG AGGAGGACGC
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGTCG GAGCTGGGGC
 GGCTTAGCGC CGAGTACTTC AACAGCCAGA AGGACGTCCT GGAGCGGAGG
 CGGGCCGAGG TGGACACAGT GTGCAGACAC AACTACAGGG GTGTGGAGAG
 CTTCACAGTG CAGCGGCGAG TTGAGCCTAA GGTAACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAACGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGAAACG GCCAGGAAGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAC* 
>DL;IPD:MHC03504
IPD:MHC03504 Mane-DRB5*03:02 226 bases
 TAAGTATGAG TGTCATTTCT TCAACGGGAC GGAGCGGGTG CGGTTCCTGC
 ACAGATACAT CTATAACCAA GAGGAGGACG CGCGCTTCGA CAGCGACGTG
 GGGGAGTACC GGGCGGTGTC GGAGCTGGGG CGGCTTAGCG CCGAGTACTT
 CAACAGCCAG AAGGACGTCC TGGAGCGGAG GCGGGCCGAG GTGGACACAG
 TGTGCAGACA CAACTACAGG GGTGTG*  
>DL;IPD:MHC03912
IPD:MHC03912 Mane-DRB5*03:03 226 bases
 TAAGTATGAG TGTCATTTCT TCAACGGGAC CGAGCGGGTG CGGTTCCTGC
 ACAGAGACAT CCATAACCAA GAGGAGGACT TGCGCTTCGA CAGCGACGTG
 GGGGAGTACC GGGCGGTGAC GGAGCTGGGG CGGCCTGACG CCGAGTCCTG
 GAACAGCCGG AAGGACATCC TGGAAGACAG GCGGGCCGCG GTGGACACCT
 TCTGCAGACA CAACTACGGG GTTGGT*  
>DL;IPD:MHC03454
IPD:MHC03454 Mane-DRB6*01:01 226 bases
 TAAGTGTGAG TGTCATATCT TCAATGGGAC TGAGCGGGTG CAGTACCTGA
 ACAGAAACAT CCATAAACGG GAGGAGAACC TGCGCTTCCA CAGCGACCTG
 GGGGAGTTCC AGGCGGTGAC GGAACTGGGG CGGCCTGTCG CGGAGAACTG
 GAACAGCCGG ATGGGCATCC TGGAGGAGAA GCGGGACAAG GTGGACATCT
 ACTGCAGATA CAATTACGGG GTTTTT*  
>DL;IPD:MHC03455
IPD:MHC03455 Mane-DRB6*01:02 226 bases
 TAAGTGTGAG TGTCATATCT TCAATGGGAC TGAGCGGGTG CAGTACCTGA
 ACAGAAACAT CCATAAACGG GAGGAGAACC TGCGCTTCCA CAGCGACCTG
 GGGGAGTTCC AGGCGGTGAC GGAACTGGGG CGGCCTGTCG CGGAGAACTG
 GAACAGCCGG ATGGGCATCC TGGAGGAGAA GCGGGACAAG GTGGACACCT
 ACTGCAGATA CAATTACGGG GTTTTT*  
>DL;IPD:MHC03456
IPD:MHC03456 Mane-DRB6*01:03 229 bases
 TAAGTGTGAG TGTCATTTCT TCAATGGGAC TGAGCGGGTG CAGTACCTAA
 ACAGAAACAT CCATAAACGG GAGGAGAACC TGCGCTTCCA CAGCGACCTG
 GGGGAGTTCC AGGCGGTGAC GGAACTGGAG TGGCCGCCTG TCGCGGAGAA
 CTGGAACAGC CAGAAAGGCA TCCTGGAGGA GAAGCGGGAC AAGGGGGACA
 CCTACTGCAT AAACAATTAC GGGGTTTTG*  
>DL;IPD:MHC03503
IPD:MHC03503 Mane-DRB6*01:04 226 bases
 TAAGTCTGAG TGTCAAATCT TCAACGGGAG GGAGCGGGTG CGGTACCTGA
 ACAGATACAT CCATAAACGG GAGGAGAACC TGCGCTTCGA CAGCGACGTG
 GGGGAGTTCC AGGCGGTGAC GGAACTGGGG CGGCCTGTCG CGGAGAACTG
 GAACAGCCAG AAGGGCATCC TGGAGGAGAA GCGGGACAAG GTGGACACCT
 ACTGCAGATA CAATTAACGG GTTTTT*  
>DL;IPD:MHC03890
IPD:MHC03890 Mane-DRB6*01:05 226 bases
 TAAGTGTGAG TGTCATTTCT TCAATGGGAC TGAGCGGATG CAGTACCTGA
 ACAGATACAT CCATAAACGG GAGGAGAACC TGCGCTTCCA CAGCGACGTG
 GGGGAGTTTC AGGCGGTGAC GCAACTGGAG CGGCCTGTCG CGGAGAACTG
 GAACAGCCGG ATGGGCATCC TGGAGGAGAA GCGGGACTAG GTGGACACCT
 ACTGCAGATA CAATTACGGG GTTTTT*  
>DL;IPD:MHC03898
IPD:MHC03898 Mane-DRB6*01:06 164 bases
 TAAGTGTGAG TGTCCTATCT TCAATGGGAC TGAGCCGGTG CAGTACCTGA
 ACAGATACAT CCATAAAAGG GAGGAGAACC TGCGCTACAA CAGCGACCTG
 GGGGAGTTCC AGGCGGTGAC GGAACTGGGG TGGCCTGTCA CAGAGTTACA
 ATTATGGGGT TTTT*   
>DL;IPD:MHC03899
IPD:MHC03899 Mane-DRB6*01:07 229 bases
 TAAGTGTGAG TGTCATTTCT TCAATGGGAC TGAGCGGGTG CAGTACCTAA
 ACAGAAACAT CCATAAACGG GAGGAGAACC TGCGCTTCCA CAGCGACCTG
 GGGGAGTTCC AGGCGGTGAC GGAACTGGAG TGGCCGCCTG TCGCGGAGAA
 CTGGAACAGC CAGAAAGGCA TCCTGGAGGA GAAGCGGGAC AAGGGGGACA
 CCTACTGCAT AAACAATTAC GGGGTTTTT*  
>DL;IPD:MHC03902
IPD:MHC03902 Mane-DRB6*01:08 164 bases
 TAAGTGTGAG TGTCATATCT TCAATGGGAC TGAGCGGGTG CGGTACCTGA
 ATAGAAACAT CCATAAACAG GAGGAGAACC TGCGCTTCCA CAGCGACGTG
 GGGGAGTTCC AGGCGGTGAC GGAACTGGGG TGGCCTGTCA CAGAGTTACA
 ATTGTGGGGT TTTT*   
>DL;IPD:MHC03903
IPD:MHC03903 Mane-DRB6*01:09 164 bases
 TAAGTGTGAG TGTCATATCT TCAATGGGAC TGAGCGGGTG CGGTACCTGA
 ACAGAAACAT CCATAAACAG GAGGAGAACC TGCGCTTCCA CAGCGACGTG
 GGGGAGTTCC AGGCGGTGAC GGAACTGGGG TGGCCTGTCA CAGAGTTACA
 ATTGTGGGGT TTTT*   
>DL;IPD:MHC03907
IPD:MHC03907 Mane-DRB6*01:10 229 bases
 TAAATATGAG TGTCATATCT TCAATGGGAC TGAGCGGGTG CAGTACCTAA
 ACAGAAACAT CCATAAAGGG GAGAAGAACC TGCGCTTCCA GAGCGACGTC
 GGGGAGTTCC AGGCGGTGAC TGAACCGGAG TGGCCGCCTG TCGCGGAGAA
 CTGGAACAGC CAGAAGGGCA TCCTGGAGGA GAAGCAGGAC AAGGTGGACA
 CCTACTGCAG AAACAATTAC GGGGTTTTT*  
>DL;IPD:MHC03923
IPD:MHC03923 Mane-DRB6*01:11 164 bases
 TAAGTGTGAG TGTCATATCT TCAATGGGTC TGAGCAGGTG CAGTACCTGA
 ACAGAAACAT CCATAAACGG GGGGAGAACC TGGGCTTCCA CAGCGACGTG
 GGGGAGTTCC AGGCGGTGAC GCAACTGGGG CGGCCTGTCA CAGAGTTACA
 ATTACCGGGT TTTT*   
>DL;IPD:MHC03924
IPD:MHC03924 Mane-DRB6*01:12 164 bases
 TAAGTGTGAG TGTCCTATCT TCAATGGGAC TGAGTGGGTG CAGTACCTGA
 ACAGAAACAT CCATAAACGG GAGGAGAACC TGCGCTTCCA CAGCGACGTG
 GGGGAGTTCC AGGCGGTGAT GGAACTGGGG CGACCTGTCA CAGAGTTACA
 ATTGTGGGGT TTTT*   
