>DL;IPD:MHC00633
IPD:MHC00633 Mane-I*01:01:01 333 bases
 SGALALTETW AGSHSLRYFG TTVSRPGRGE PRFIAVGYVD DTQFVRFDSD
 AESPRMEPRA PWMEQEGPEY WEEETRIAKA RAQTERGNLR TALRYYNQSE
 GGSHTLQKMC GCDLGPDGRL LRGYYQSAYD GRDYIALNED LRSWTAAGEA
 AQNTQRKWEA AGEAEQRRAY LEGRCVEWLR RYLEKGKETL QRADPPKTHV
 THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEEQTQDTE LVETRPGGDG
 NFQKWAAVVV PSGEEQRYTC HVQHEGLPEP LTLRWEPSSQ STIPIMGIVA
 GLAVLAVVVT GAVVAAVMWR RKSSGGKGGS YSQ* 
>DL;IPD:MHC02137
IPD:MHC02137 Mane-I*01:01:02 363 bases
 MRVMAPGTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC02144
IPD:MHC02144 Mane-I*01:01:03 273 bases
 SHSLRYFGTT VSRPGRGEPR FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 MEQEGPEYWE EETRIAKARA QTERGNLRTA LRYYNQSEGG SHTLQKMCGC
 DLGPDGRLLR GYYQSAYDGR DYIALNEDLR SWTAAGEAAQ NTQRKWEAAG
 EAEQRRAYLE GRCVEWLRRY LEKGKETLQR ADPPKTHVTH HPVSDHEATL
 RCWALGFYPA EITLTWQRDG EEQTQDTELV ETRPGGDGNF QKWAAVVVPS
 GEEQRYTCHV QHEGLPEPLT LRW*  
>DL;IPD:MHC02548
IPD:MHC02548 Mane-I*01:01:04 273 bases
 SHSLRYFGTT VSRPGRGEPR FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 MEQEGPEYWE EETRIAKARA QTERGNLRTA LRYYNQSEGG SHTLQKMCGC
 DLGPDGRLLR GYYQSAYDGR DYIALNEDLR SWTAAGEAAQ NTQRKWEAAG
 EAEQRRAYLE GRCVEWLRRY LEKGKETLQR ADPPKTHVTH HPVSDHEATL
 RCWALGFYPA EITLTWQRDG EEQTQDTELV ETRPGGDGNF QKWAAVVVPS
 GEEQRYTCHV QHEGLPEPLT LRW*  
>DL;IPD:MHC02138
IPD:MHC02138 Mane-I*01:02 273 bases
 SHSLRYFGTT VSRPGRGEPR FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 MEQEGPEYWE EETRIAKARA QTERGNLRTA LRYYNQSEGG SHTLQKMCGC
 DLGPDGRLLR GYYQSAYDGR DYIALNEDLR SWTAAGEAAQ NTQRKWEAAG
 EAEQRRAYLE GRCVEWLRRY LENGKETLQR ADPPKTHVTH HPVSDHEATL
 RCWALGFYPA EITLTWQRDG EEQTQDTELV ETRPAGDGTF QKWAAVVVPS
 GEEQRYTCHV QHEGLPEPLT LRW*  
>DL;IPD:MHC02139
IPD:MHC02139 Mane-I*01:03 273 bases
 SHSLRYFGTT VSRPGRGEPR FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 MEQEGPEYWE EETRIAKARA QTERGNLRTA LRYYNQSEGG SHTLQKMCGC
 DLGPDGRLLR GYYQSAYDGR DYIALNEDLR SWTAAGEAAQ NTQRKWEAAG
 EAEQRRAYLE GRCVEWLRRY LEKGKETLQR ADPPKTHVTH HPVSDHEATL
 RCWALGFYPA EITLTWQRDG EDQTQDTELV ETRPGGDGNF QKWAAVVVPS
 GEEQRYTCHV QHEGLPEPLT LRW*  
>DL;IPD:MHC02140
IPD:MHC02140 Mane-I*01:04 363 bases
 MQIMAPRTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVQ WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC02141
IPD:MHC02141 Mane-I*01:05 273 bases
 SHSLRYFGTT VSRPGRGEPR FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 MEQEGPEYWE EETRIAKARA QTERGNLRTA LRYYNQSEGR SHTLQKMCGC
 DLGPDGRLLR GYYQSAYDGR DYIALNEDLR SWTAAGEAAQ NTQRKWEAAG
 EAEQRRAYLE GRCVEWLRRY LEKGKETLQR ADPPKTHVTH HPVSDHEATL
 RCWALGFYPA EITLTWQRDG EEQTQDTELV ETRPGGDGNF QKWAAVVVPS
 GEEQRYTCHV QHEGLPEPLT LRW*  
>DL;IPD:MHC02142
IPD:MHC02142 Mane-I*01:06 273 bases
 SHSLRYFGTT VSRPGRGEPR FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 MEQEGPEYWE EETRIAKARA QTERGNLRTA LRYYNQSEGG SHTLQKMCGC
 DLGPDGRLLR GYYQSAYDGR DYIALNEDLR SWTAAGEAAQ NTQRKWEAAG
 EAEQRRAYLE GRCVEWLRRY LEKGKETLQR ADPPKTHVTH HPVSDHEATL
 RCWALGFYPA EITLTWQRDG EEQTQDTELV ETRPGGDGNF QKWAAVVVPS
 GEEQRYTCHV QHEGLLEPLT LRW*  
>DL;IPD:MHC02143
IPD:MHC02143 Mane-I*01:07 363 bases
 MRVMAPGTLL LLLSGALALT ETWAGSHSLK YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC02540
IPD:MHC02540 Mane-I*01:08:01 273 bases
 SHSLRYFGTT VSRPGRGEPR FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 MEQEGPEYWE EETRIAKARA QTERGNLRTA LRYYNQSEGG SHTLQKMCGC
 DLGPDGRLLR GYYQSAYDGR DYIALNEDLR SWTAAGEAAQ NTQRKWEAAG
 EAEQRRAYLE GRCVEWLRRY LEKGKETLQR ADPPKTHVTH HPISDHEATL
 RCWALGFYPA EITLTWQRDG EDQTQDTELV ETRPGGDGNF QKWAAVVVPS
 GEEQRYTCHV QHEGLPEPLT LRW*  
>DL;IPD:MHC02885
IPD:MHC02885 Mane-I*01:08:02 363 bases
 MRVMAPGTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGPVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC02888
IPD:MHC02888 Mane-I*01:08:03 363 bases
 MRVMAPGTLL LLLSGALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGPVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
>DL;IPD:MHC02541
IPD:MHC02541 Mane-I*01:09 273 bases
 SHSLRYFGTT VSRPGRGEPR FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 MEQEGPEYWE EQTRIAKARA QTERGNLRTA LRYYNQSEGG SHTLQKMCGC
 DLGPDGRLLR GYYQSAYDGR DYIALNEDLR SWTAAGEAAQ NTQRKWEAAG
 EAEQRRAYLE GRCVEWLRRY LEKGKETLQR ADPPKTHVTH HPVSDHAATL
 RCWALGFYPA EITLTWQRDG EEQTQDTELV ETRPGGDGNF QKWAAVVVPS
 GEEQRYTCHV QHEGLPEPLT LRW*  
>DL;IPD:MHC02549
IPD:MHC02549 Mane-I*01:10 273 bases
 SHSLRYFGTT VSRPGRGEPR FIAVGYVDDT QFVRFDSDAE SPRMEPRAPW
 MEQEGPEYWE EETRIAKARA QTERGNLRTA LRYYNQSEGG SHTLQRMCGC
 DLGPDGRLLR GYYQSAYDGR DYIALNEDLR SWTAAGEAAQ NTQRKWEAAG
 EAEQRRAYLE GRCVEWLRRY LEKGKETLQR ADPPKTHVTH HPISDHEATL
 RCWALGFYPA EITLTWQRDG EDQTQDTELV ETRPGGDGNF QKWAAVVVPS
 GEEQRYTCHV QHEGLPEPLT LRW*  
>DL;IPD:MHC02886
IPD:MHC02886 Mane-I*01:11 363 bases
 MRVMAPGTLL LLLSAALALT ETWAGSHSLR YFGTTVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAESPRME PRAPWMEQEG PEYWEEETRI AKARAQTERG
 NLRTALRYYN QSEGGSHTLQ KMCGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA GEAAQNTQRK WEAAGEAEQR RAYLEGRCVE WLRRYLEKGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEEQTQ
 DTELVETRPG GDGNFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIMG IVAGLAVLAV VVTGAVVAAV MWRRKSSGGK GGSYSQAASS
 NSAQGSDVSL TAX*   
