>DL;IPD:MHC05161
IPD:MHC05161 Mane-DRA*01:01 765 bases
 ATGGCCGAAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTGTGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAAG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCATTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC05153
IPD:MHC05153 Mane-DRA*01:02:01 765 bases
 ATGGCCATAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTGTGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CACTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAAG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTAGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC05154
IPD:MHC05154 Mane-DRA*01:02:02 765 bases
 ATGGCCATAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTGTGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAAG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC05158
IPD:MHC05158 Mane-DRA*01:03:01 765 bases
 ATGGCCGTAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTATGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAAG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC05159
IPD:MHC05159 Mane-DRA*01:03:02 765 bases
 ATGGCCGTAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTATGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACAGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAAG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC05160
IPD:MHC05160 Mane-DRA*01:04 765 bases
 ATGGCCGAAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTGTGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CACTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTAA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAAG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC05155
IPD:MHC05155 Mane-DRA*01:05 765 bases
 ATGGCCATAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTGTGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAAG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGT GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC05156
IPD:MHC05156 Mane-DRA*01:06:01 765 bases
 ATGGCCGTAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTGTGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAAG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTATGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC05157
IPD:MHC05157 Mane-DRA*01:06:02 765 bases
 ATGGCCGTAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA TAGCTGTGCT
 GATGAGCGCT CAGGAATCAT GGGCTATCAA AGAAGAACAC GTGATCATCC
 AGGCTGAGTT CTATCTGAAC CCTGACCAAT CAGGAGAGTT TATGTTTGAC
 TTTGATGGTG ATGAGATTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAAG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC05162
IPD:MHC05162 Mane-DRA*02:01:01 765 bases
 ATGGCCGCAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA CAGCTGTGCT
 GATGAGCGCT CAAGAATCAT GGGCTATCAA AGAAGATCAT GTGATCATCC
 AGGCCGAGTT CTATCTGAAC CCTGACCAAT CAGGCGAGTA TATGTTTGAC
 TTTGATGGTG ATGAGCTTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CACTGGCGAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAAG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
>DL;IPD:MHC05163
IPD:MHC05163 Mane-DRA*02:01:02 765 bases
 ATGGCCGCAA GTGGAGTCCC CGTGCTAGGA TTTTTCATCA CAGCTGTGCT
 GATGAGCGCT CAAGAATCAT GGGCTATCAA AGAAGATCAT GTGATCATCC
 AGGCCGAGTT CTATCTGAAC CCTGACCAAT CAGGCGAGTA TATGTTTGAC
 TTTGATGGTG ATGAGCTTTT CCACGTGGAT ATGGCAAAGA AGGAGACGGT
 CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG GCTCAAGGTG
 CACTGGCGAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACA ATACTCCAAT CACCAATGTA CCTCCAGAGG TAACTGTGCT
 CACAAACAGC CCTGTGGAAC TGGGAGAGCC CAACGTCCTC ATCTGTTTCA
 TCGACAAGTT CTCTCCACCA GTGGTCAAAG TTACATGGCT TAAAAATGGA
 AAACCTGTCA CCACAGGAGT GTCAGAGACA GTCTTCCTGC CCAGGGAAGA
 CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC TCAACTGAGG
 ACATTTATGA CTGCAAGGTG GAGCACTGGG GCTTGGATGC ACCTCTTCTC
 AAGCACTGGG AGTTTGATGC ACCAAGCCCT CTCCCAGAGA CTACAGAGAA
 CGTGGTGTGT GCCCTGGGCC TGATTGTGGG TCTGGTGGGC ATCATCGTTG
 GGACCGTCTT CATCATCAAG GGTGTGCGCA AAAGCAATGC TGCAGAACGC
 AGGGGGCCTC TGTGA*   
