>DL;IPD:MHC00637
IPD:MHC00637 Masi-DRB*W1:01 246 bases
 TTAGAGTACT GTAAGTTTGA GTGCCATTTC TTCAATGGGA CGGAGCGGGT
 GCTGAACCTG ATCAGATACT TCTATAACCA AGAGGAGTAC GTGCGCTACG
 ACAGCGACGT CGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCAAGTACT GGAACGGCCA GAAGGACCTC CTGGAGCAGA GGCGGGCCGA
 GGTGGACACC GTGTGCAGAC ACAACTACCG GGTTGTTGAG AGCTTC*
>DL;IPD:MHC00638
IPD:MHC00638 Masi-DRB*W2:01 246 bases
 TTGGATCAGG TTAAGTATGA GTGTCATTTC TTCAATGGGA CGGAGCGGGT
 GCGGTTGCTG GGCAGACACT TCTATAACCA GGAGGAGTTA GCGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGT CGGAGCTGGG GCGGCCTGAA
 GCCGAGAACT TGAACACTCG GAAGGACCTC CTGGAGCGGG CGCGGGCCGC
 GGTGGACACC GTGTGCAGAC ACAACTACGG GATTGTGGAG AGCTTC*
>DL;IPD:MHC00640
IPD:MHC00640 Masi-DRB*W35:01 246 bases
 TTGGAGCAGG CTAAGTCTGA GTGTCACTTC TTCGACGGGA CGGAGCGGGT
 GCGGTTCCTG GACAGATACT TCTATAACCA GGAGGAGTAC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCGAGTACT GGAACAGCCA GAAGGACATC CTGGAAGACG CGCGGGCCGC
 GGTGGACACC TACTGCAGAC ACAACTACGG GGTTGGCGAG AGCTTC*
>DL;IPD:MHC00639
IPD:MHC00639 Masi-DRB*W3:01 246 bases
 TTGGAGCAGG CTAAACGTGA GTGTCATTTC TTCAATGGGA CGGAGCGGGT
 GCGGTTCCTG GACAGATACT TCTATAACCA GGAGGAGTAC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGA CGGAGCTGGG GCGGCGTAGC
 GCGGAGTACT GGAACAGCCA GAAGGACTTT CTGGAGCAGG CGCGGACCGC
 GGTGGACAAC TACTGCAGAC ACAACTACGG GGTTGGCGAG AGCTTC*
>DL;IPD:MHC00641
IPD:MHC00641 Masi-DRB*W4:01 246 bases
 TTGCAGCAGT TTAAGCCTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTACCTG GAGAGACACT TCTATAACCA GGAGGAGAAC CTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGT CGGAGCTGGG GCGGCCTGAA
 GCCCAGTCCT GGAACAGCCA GAAGGACTTC CTGGAGGAGA AGCGGGCCGC
 GGTGGACACC TACTGCAGAC ACAACTACCG GGTTGGTGAG AGCTTC*
>DL;IPD:MHC00642
IPD:MHC00642 Masi-DRB*W4:02 246 bases
 TTGGAGCACG TTAAGTCTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTCCTG GAGAGACACT TCTATAACCA GGAGGAGAAC CTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCGAGAACT GGAACAGCCA GAAGGACATC CTGGAGGAGA AGCGGGCCCG
 GGTGGACAAC TACTGCAGAC ACAACTACCG GGTTGGTGAG AGCTTC*
>DL;IPD:MHC00634
IPD:MHC00634 Masi-DRB1*03:01 246 bases
 TTGGAGTACT CTACATCTGA GTGTCACTTC TTCAACGGGA CGGAGCGGGT
 GCGGTACCTG GACAGATACT TCTATAACCA GGAGGAGAAC CTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGT CGGAGCTGGG GCGGCCTGAC
 GCCGAGTACT TCAACAGCCA GAAGGACATC CTGGAGCAGA AGCGGGCCCG
 GGTGGACAAT TACTGCAGAC ACAACTACCG GGTTGGTGAG AGCTTC*
>DL;IPD:MHC00635
IPD:MHC00635 Masi-DRB1*04:01 246 bases
 TTGGAGCAGG TTAAACATGA GTGTCACTTC TTCAATGGGA CGGAGCGGGT
 GCGGTTCCTG GACAGATACT TCTATAACCA GGAGGAGTAC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCGTAGC
 GCGGAGTACT GGAACAGCCA GAAGGACTTC CTGGAGGAGA GGCGGGCCGC
 GGTGGACAAT TACTGCAGAC ACAACTACGG GGTTGCGGAG AGCTTC*
>DL;IPD:MHC00636
IPD:MHC00636 Masi-DRB4*01:01 246 bases
 TTGGAGCAGG CTAAGTCTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTACCTG ATCAGACACA TCTACAACCA AGAGGAGAAC GCGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCGAGTACT GGAACGGCCA GAAGGACCTC CTGGAGCGGA GGCGGGCCGA
 GGTGGACACA GTGTGCAGAC ACAACTACGG GGTTGGTGAG AGCTTC*
