>DL;IPD:MHC00645
IPD:MHC00645 Paan-A*01 1098 bases
 ATGGCGGTCA TGGCGCCCCG AACCCTCCTC CTGGTGCTCT CAGGGGTCCT
 GGCCCTGACC CAGACATGGG CGGGCTCCCA CTCCATGAGG TATTTCTACA
 CCTCCATGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCTT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGCGAGCCA
 GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGGA GACACAGAAC ATGAAGGCCC AGACACAGAA TGCCCCAGTG
 AACCTGCGGA ACCTGCGCGG CTACTACAAC CAGAGCGAGG CGGGGTCTCA
 CACCCTCCAG AGGATGCACG GCTGCGACCT GGGACCCGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGTCC GCCTACGACG GCAAGGATTA CTTCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCCGCG GACTTGGCGG CTCAGAACAC
 CCAGCGGAAG TGGGAGGCGG CGGATGTGGC GGAGCAGATT AGAGCCTACC
 TGGAGGGCCG GTGTGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCCAAG ACACATGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCGTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACGGAGC TCATGGAGAC CAGGCCTGCA GGAGATGGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAAA GGAGCAGAGA TACACCTGTC
 ATGTGCAGCA TGAGGGTCTG CCCAAGCCCC TCACCTTGAG ATGGGAGCCG
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATCATTGCTG GCCTGGTTCT
 CCTTGGAGCT ATGGTCATTG GAGCTGTGGT TGCTGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGATAGAAAA GGAGGGAGCT ACTCTCAGGC TGCAAGCAGT
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACGGCTTGTA AAGTGTGA*
>DL;IPD:MHC00646
IPD:MHC00646 Paan-A*02 1098 bases
 ATGGCGGTCA TGGCGCCCCG AACCCTCCTC CTGGTGCTCT CAGGGGCCCT
 GGCCCTGACC CAGACCCGGG CAGGCTCTCA CTCCATGAGG TATTTCTACA
 CCTCCATGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCTT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGCGAGCCA
 GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGT CCAGAGTATT
 GGGACCGGAG CACACGGATC ATGAAGACCG CGACACAGAA TGCCCCAGTG
 GGCCTGCGGA ACCTGCGCGG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCTACCAG AGTATGTATG GCTGCGACCT GGGGCCCGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGTCC GCCTACGACG GCAGGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACGGCCGCC GACATGGCGG CTCAGAACAC
 CCAGCGGAAG TGGGAGACGG AAGGTGTGGC AGAGCAGCTG AGCGCCTACC
 TGGAGGGCGA GTGCCTGGAG TGGCTCCGCA GACACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACATGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGAGAGGA CCAAACTCAG
 GACACGGAGC TCGTGGAGAC CAGGCCCGCA GGGGATGGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAAA GGAGCAGAGA TACACCTGTC
 ATGTGCAGCA TGAGGGTCTG CGTGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATCATTGCTG GCGTGGTTCT
 CCTTGGAATT GTGGTCACTG GAGCTGTGAT TGCTGCTGTG ATATGGAGGA
 GGAAGAGCTC AGATGGAAAA GGAGGGAGCT ACTCTCAGGC TGCAAGCAGT
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACGGCTTGTA AAGTGTGA*
>DL;IPD:MHC00647
IPD:MHC00647 Paan-A*03 1092 bases
 ATGGCGGTCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CAGGGGCCCT
 GGCCCTGACC CAGACCTGGG CGAGCTCCCA CTCCATGAGG TATTTCTACA
 CCTCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CCTGCGGTTC GACAGCGACG CCGCGAGCCA
 GAGGCTGGAG CCGCGGGCGC GGTGGGTGGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGAA CACACGGATC GTGAAGGCCG AGACACAGAA TGCCCCAGTG
 AACCTGCAGA ACCTGCGCGG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCATCCAG AGGATGTACG GCTGCGACCT GGGGCCCGAC GGGCGCCTCC
 TCCGCGGGTA TGAACAGTAC GCCTACGACG GCAGGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCCGCG GACATGGCGG CTCAGAACAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGCGGC GGAGCAGCAC AGAACCTACC
 TGGAGGGCGA GTGCCTGGAG TGGCTCCGCA GACACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCCAAG ACACATGTGA CCCACCACCC
 CGTCTCTGAC TACGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGAGAGGA CCAAACTCAG
 GACACGGAGC TCGTGGAGAC CAGGCCTGCA GGAGATGGAA CCTTCCAGAA
 GTGGGCGGCT GTGGTGGTGC CTTCTGGAAA GGAGCAGAGA TACACCTGTC
 ATGTGCAGCA TGAGGGTCTG CCCAAGCCCC TCACCTTGAG ATGGGAGCCG
 TCTTCCCAGT CCACCATCGT GGGCATCATT GCTGGCCTGG TTCTCCTTGG
 AGCTGTGGTC ACTGGAGCTG TGGTTGCTGC TGTGATGTGG AGGAGGAAGA
 GCTCAGATAG AAAAGGAGGA AGCTACTCTC AGGCTGCAAG CAGTGACAGT
 GCCCAGGGAT CTGATGTGTC TCTCACGGCT TGTAAAGTGT GA*
>DL;IPD:MHC00643
IPD:MHC00643 Paan-AG*01 1082 bases
 CCCGAACCCT CCTCCTGGTG CTCTCAGGGG TCCTGGCCCT GACCCGGACC
 CGGGCGGGCT CGCACTCCAT GAGGTATTTC TACACCTCCA TGTCCCGGCC
 CGGCCGCGGG GAGCCCCGCT TCTTCGCCGT GGGCTACGTG GACGACACGC
 AGTTCGTGCG GTTCGACAGC GACGCCGAGA GTCCGAGGAT GGAGCCGCGG
 GCGCCGTGGG TGGAGCAGGA GGGTCCAGAG TATTGGGACC GGGAGACACA
 GAACATGAAG AACGCGACAC AGACCTACCG AGGAAACCTG CGGACCCTGC
 TCCGCTACTA CAACCAGAGC GAGGCCGGGT CTCACACCGT CCAGAAGATG
 TACGGCTGCG ACCTGGGGCC GGACGGGCGC CTCCTCCACG GGTATGAACA
 GTTCGCCTAC GACGGCAGGG ATTACATCAC CCTGAACGAG GACCTGCGCT
 CCTGGACGGC CGCGGACATG GCGGCTCAGA ACACCCAGCG GAAGTGGGAG
 GCGGCGGGTG CGGCGGAGCA GCACAGAACC TACCTGGAGG GCGAGTGCCT
 GGAGTGGCTC CGCAGATACC TGGAGAACGG GAAGGAGACG CTGCAGCGCG
 CGGACCCCCC CAAGACACAT GTGACCCACC ACCCCGTCTC TGACTACGAG
 GCCACCCTGA GGTGCTGGGC CCTGGGCTTC TACCCTGCGG AGATCACACT
 GACCTGGCAG CGGGATGGAG AGGAACAAAC TCAGGACACA GAGCTCGTGG
 AGACCAGGCC TACAGGGGAT GGAACCTTCC AAAAGTGGGC GGCTGTGGTG
 GTGCCTTCTG GAGAGGAGCA GAGATACACC TGTCATGTGC AGCATGAGGG
 TCTGCCCGAG CCCCTCACCT TGAGATGGGA GCCGTCTTCC CAGTCCACCA
 TCCTCATCGT AGGCATCATT GCTGGCCTGG TTCTCCTTGG AACTGTGGTC
 ACTGGAGCTG TGGTTGCTGC TGTGATGTGG AGGAGGAAGA GCTCAGATAG
 ATAAGGCGGG AGCTACTCTC AGGCTGCAAG CAGTGACAGT GCCCAGGGCT
 CTGATGTGTC TCTCACGGCT TGTAAAGTGT GA* 
>DL;IPD:MHC00644
IPD:MHC00644 Paan-AG*02 1081 bases
 CCCGAACCCT CCTCCTGGTG CTCTCAGGGG TCCTGGCCCT GACCCGGACC
 CGGGCGGGCT CGCACTCCAT GAGGTATTTC TACACCTCCA TGTCCCGGCC
 CGGCCGCGGG GAGCCCCGCT TCTTCGCCGT GGGCTACGTG GACGACACGC
 AGTTCGTGCG GTTCGACAGC GACGCCGAGA GTCCGAGGAT GGAGCCGCGG
 GCGCCGTGGG TGGAGCAGGA GGGTCCAGAG TATTGGGACC GGGAGACACA
 GAACATGAAG AACGCGACAC AGACCTACCG AGGGAACCTG CGGACCCTGC
 TCCGCTACTA CAACCAGAGC GAGGCCGGGT CTCACACCGT CCAGAAGATG
 TACGGCTGCG ACCTGGGGCC GGACGGGCGC CTCCTCCACG GGTATGAACA
 GTTCGCCTAC GACGGCAGGG ATTACATCGC CCTGAACGAG GACCTGCGCT
 CCTGGACGGC CGCGGACATG GCGGCTCAGA ACACCCAGCG GAAGTGGGAG
 GCGGCGGGTG CGGCGGAGCA GCACAGAACC TACCTGGAGG GCGAGTGCCT
 GGAGTGGCTC CGCAGATACC TGGAGAACGG GAAGGAGACG CTGCAGCGCG
 CGGATCCCCC CAAGACACAT GTGACCCACC ACCCCGTCTC TGACTACGAG
 GCCACCCTGA GGTGCTGGGC CCTGGGCTTC TACCCTGCGG AGATCACACT
 GACCTGGCAG CGGGATGGAG AGGAACAAAC TCAGGACACA GAGCTCGTGG
 AGACCAGGCC TACAGGGGAT GGAACCTTCC AAAAGTGGGC GGCTGTGGTG
 GTGCCTTCTG GAGAGGAGCA GAGATACACC TGTCATGTGC AGCATGAGGG
 TCTGCCCGAG CCCCTCACCT TGAGATGGGA GCCGTCTTCC CAGTCCACCA
 TCCTCATCGT AGGCATCATT GCTGGCCTGG TTCTCCTTGG AGCTGTGGTC
 ACTGGAGCTG TGGTTGCTGC TGTGATGTGG AGGAGGAAGA GCTCAGATAG
 ATAAGGCGGG AGCTACTCTC AGGCTGCAAG CAGTGACAGT GCCCAGGGCT
 CTGATGTGTC TCTCACGGCT TTAAAGTGTG A* 
