>DL;IPD:MHC00643
IPD:MHC00643 Paan-AG*01 334 bases
 RTLLLVLSGV LALTRTRAGS HSMRYFYTSM SRPGRGEPRF FAVGYVDDTQ
 FVRFDSDAES PRMEPRAPWV EQEGPEYWDR ETQNMKNATQ TYRGNLRTLL
 RYYNQSEAGS HTVQKMYGCD LGPDGRLLHG YEQFAYDGRD YITLNEDLRS
 WTAADMAAQN TQRKWEAAGA AEQHRTYLEG ECLEWLRRYL ENGKETLQRA
 DPPKTHVTHH PVSDYEATLR CWALGFYPAE ITLTWQRDGE EQTQDTELVE
 TRPTGDGTFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPLTL RWEPSSQSTI
 LIVGIIAGLV LLGTVVTGAV VAAVMWRRKS SDRX* 
>DL;IPD:MHC00644
IPD:MHC00644 Paan-AG*02 334 bases
 RTLLLVLSGV LALTRTRAGS HSMRYFYTSM SRPGRGEPRF FAVGYVDDTQ
 FVRFDSDAES PRMEPRAPWV EQEGPEYWDR ETQNMKNATQ TYRGNLRTLL
 RYYNQSEAGS HTVQKMYGCD LGPDGRLLHG YEQFAYDGRD YIALNEDLRS
 WTAADMAAQN TQRKWEAAGA AEQHRTYLEG ECLEWLRRYL ENGKETLQRA
 DPPKTHVTHH PVSDYEATLR CWALGFYPAE ITLTWQRDGE EQTQDTELVE
 TRPTGDGTFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPLTL RWEPSSQSTI
 LIVGIIAGLV LLGAVVTGAV VAAVMWRRKS SDRX* 
