>DL;IPD:MHC00648
IPD:MHC00648 Paan-B*01 363 bases
 MRVMAVRTLL LLLSGALALT ETWAGSHSMR YFTTALSRPG RWEPRFIAVG
 YVDDTQFVRF DSDAASPRME PRARWIEQEG PEYWEEQTRR AKGHAQTDLG
 SLRILRGYYN QSEAGSHTYQ WMAGCDVGPD GRLLRGYHQR AYDGKDYIAL
 NEDLRSWTAA DVAAQKTQRK WEAARLAEQW RAYLEGECVE WLRRYLENGK
 EMLQRTDPPK THVTHHPVSD HEATLRCWAL GFYPAEISLT WQRDGEDQTQ
 DTELVETRPG GDGTFQKWGA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVIGAVVAAV MWRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00649
IPD:MHC00649 Paan-B*02 19 bases
 MRSWLPEPSS CCSRGPWPX*   
