>DL;IPD:MHC00648
IPD:MHC00648 Paan-B*01 1089 bases
 ATGCGGGTCA TGGCGGTCCG AACCCTCCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCACCA
 CCGCCCTGTC CCGGCCCGGC CGCTGGGAGC CCCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGCGAGTCC
 GAGGATGGAG CCGCGGGCGC GGTGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGAGGAGCA GACACGGAGA GCCAAGGGCC ACGCACAGAC TGACCTAGGG
 AGCCTGAGGA TCCTGCGCGG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCTACCAG TGGATGGCTG GCTGCGACGT GGGACCCGAC GGGCGCCTCC
 TCCGCGGGTA TCACCAGCGC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCCGCG GACGTGGCGG CTCAGAAAAC
 TCAGCGCAAG TGGGAGGCGG CCCGTTTGGC AGAGCAGTGG AGAGCCTACC
 TGGAGGGCGA GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGGACGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CTCACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACTGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA CCTTCCAGAA
 GTGGGGAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACGTGCC
 ATGTGCAGCA CGAGGGATTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATCGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCATCG GAGCTGTGGT CGCTGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACGGCTTGA* 
>DL;IPD:MHC00649
IPD:MHC00649 Paan-B*02 1088 bases
 ATGCGGTCAT GGCTCCCCGA ACCCTCCTCC TGCTGCTCTC GGGGGCCCTG
 GCCCTGACCG AGACCTGGGC CGGCTCGCAC TCCATGAAGT ATTTCTACAC
 CGCCGTGTCC CGGCCCGGCC GCTGGGAGCC CCACTTCATC TCCGTGGGCT
 ACGTGGACGA CACGCAGTTC GTGCGGTTCG ACAGCGACGC CGAGAGTCCG
 AGAAAGGAGC CGCGGGCGCC GTGGGCGGAG CAGGAGGGAC CGGAGTATTG
 GGAAGAGCAG ACACGGAGAG CCAAGGCCAA CGCACAGGCT GACCGAATGT
 GCCTGCGGAC CGTGCCCGGC TACTACAACC AGAGCGAGGC CGGGTCTCAC
 ACCTTCCAGA GTATGTATGG CTGCGACCTG GGGCCCGACT GGCGCCTCCT
 CCGCGGGTAT TACCAGTCCG CCTACGACGG CAGGGATTAC ATCGCCCTGA
 ACGAGGACCT GCTCTCCTGG ACCTCCGCGG ACGTGGCGGC TCAGAACACC
 CAGCGCGAGT GGGAGGCGGA CCGTTATGCG GAGCAGCTGA GAGCCTACCT
 GGAGGGCGAG TGCGTGGAGT CGCTCCGCAG ATACCTGGAG AACGGGAAGG
 AGACGCTGCA GCGCGCGGAC CCCCCAAAGA CACACGTGAC CCACCACCCC
 ATCTCTAACC ATGAGGCCAC CCTGAGGTGC TGGGCCCTGG GCTTCTACCC
 TGCGGAGATC ACACTGACCT GGCAGCGGGA TGGGGAGGAC CAAACTCAGG
 ACACAGAGCT TGTGGAGACC AGGCCAGCAG GAGATGGAAC CTTCCAGAAG
 TGGGGAGCTG TGGTGGTGCC TTCTGGAGAA GAGCAGAGAT ACACGTGCCA
 TGTGCAGCAC GAGGGATTGC CAGAGCCCCT CACCCTCAGA TGGGAACCAT
 CTTCCCAGTC CACCATCCCC ATCGTGGGCA TTGTTGCTGG CCTGGCTGTT
 GTAGCAGTTG TGGTCACCGG AGCTGTGGTC GCTGCTGTGA TGTGGAGGAG
 GAAGAGCTCA GGTGCAAAAG GAGGGAGCTA CTCTCAGGCT GCGTCCAACG
 ACAGTGCCCA GGGCTCTGAT GTGTCTCTCA CGGCTTGA* 
