>DL;IPD:MHC00643
IPD:MHC00643 Paan-AG*01 1082 bases
 CCCGAACCCT CCTCCTGGTG CTCTCAGGGG TCCTGGCCCT GACCCGGACC
 CGGGCGGGCT CGCACTCCAT GAGGTATTTC TACACCTCCA TGTCCCGGCC
 CGGCCGCGGG GAGCCCCGCT TCTTCGCCGT GGGCTACGTG GACGACACGC
 AGTTCGTGCG GTTCGACAGC GACGCCGAGA GTCCGAGGAT GGAGCCGCGG
 GCGCCGTGGG TGGAGCAGGA GGGTCCAGAG TATTGGGACC GGGAGACACA
 GAACATGAAG AACGCGACAC AGACCTACCG AGGAAACCTG CGGACCCTGC
 TCCGCTACTA CAACCAGAGC GAGGCCGGGT CTCACACCGT CCAGAAGATG
 TACGGCTGCG ACCTGGGGCC GGACGGGCGC CTCCTCCACG GGTATGAACA
 GTTCGCCTAC GACGGCAGGG ATTACATCAC CCTGAACGAG GACCTGCGCT
 CCTGGACGGC CGCGGACATG GCGGCTCAGA ACACCCAGCG GAAGTGGGAG
 GCGGCGGGTG CGGCGGAGCA GCACAGAACC TACCTGGAGG GCGAGTGCCT
 GGAGTGGCTC CGCAGATACC TGGAGAACGG GAAGGAGACG CTGCAGCGCG
 CGGACCCCCC CAAGACACAT GTGACCCACC ACCCCGTCTC TGACTACGAG
 GCCACCCTGA GGTGCTGGGC CCTGGGCTTC TACCCTGCGG AGATCACACT
 GACCTGGCAG CGGGATGGAG AGGAACAAAC TCAGGACACA GAGCTCGTGG
 AGACCAGGCC TACAGGGGAT GGAACCTTCC AAAAGTGGGC GGCTGTGGTG
 GTGCCTTCTG GAGAGGAGCA GAGATACACC TGTCATGTGC AGCATGAGGG
 TCTGCCCGAG CCCCTCACCT TGAGATGGGA GCCGTCTTCC CAGTCCACCA
 TCCTCATCGT AGGCATCATT GCTGGCCTGG TTCTCCTTGG AACTGTGGTC
 ACTGGAGCTG TGGTTGCTGC TGTGATGTGG AGGAGGAAGA GCTCAGATAG
 ATAAGGCGGG AGCTACTCTC AGGCTGCAAG CAGTGACAGT GCCCAGGGCT
 CTGATGTGTC TCTCACGGCT TGTAAAGTGT GA* 
>DL;IPD:MHC00644
IPD:MHC00644 Paan-AG*02 1081 bases
 CCCGAACCCT CCTCCTGGTG CTCTCAGGGG TCCTGGCCCT GACCCGGACC
 CGGGCGGGCT CGCACTCCAT GAGGTATTTC TACACCTCCA TGTCCCGGCC
 CGGCCGCGGG GAGCCCCGCT TCTTCGCCGT GGGCTACGTG GACGACACGC
 AGTTCGTGCG GTTCGACAGC GACGCCGAGA GTCCGAGGAT GGAGCCGCGG
 GCGCCGTGGG TGGAGCAGGA GGGTCCAGAG TATTGGGACC GGGAGACACA
 GAACATGAAG AACGCGACAC AGACCTACCG AGGGAACCTG CGGACCCTGC
 TCCGCTACTA CAACCAGAGC GAGGCCGGGT CTCACACCGT CCAGAAGATG
 TACGGCTGCG ACCTGGGGCC GGACGGGCGC CTCCTCCACG GGTATGAACA
 GTTCGCCTAC GACGGCAGGG ATTACATCGC CCTGAACGAG GACCTGCGCT
 CCTGGACGGC CGCGGACATG GCGGCTCAGA ACACCCAGCG GAAGTGGGAG
 GCGGCGGGTG CGGCGGAGCA GCACAGAACC TACCTGGAGG GCGAGTGCCT
 GGAGTGGCTC CGCAGATACC TGGAGAACGG GAAGGAGACG CTGCAGCGCG
 CGGATCCCCC CAAGACACAT GTGACCCACC ACCCCGTCTC TGACTACGAG
 GCCACCCTGA GGTGCTGGGC CCTGGGCTTC TACCCTGCGG AGATCACACT
 GACCTGGCAG CGGGATGGAG AGGAACAAAC TCAGGACACA GAGCTCGTGG
 AGACCAGGCC TACAGGGGAT GGAACCTTCC AAAAGTGGGC GGCTGTGGTG
 GTGCCTTCTG GAGAGGAGCA GAGATACACC TGTCATGTGC AGCATGAGGG
 TCTGCCCGAG CCCCTCACCT TGAGATGGGA GCCGTCTTCC CAGTCCACCA
 TCCTCATCGT AGGCATCATT GCTGGCCTGG TTCTCCTTGG AGCTGTGGTC
 ACTGGAGCTG TGGTTGCTGC TGTGATGTGG AGGAGGAAGA GCTCAGATAG
 ATAAGGCGGG AGCTACTCTC AGGCTGCAAG CAGTGACAGT GCCCAGGGCT
 CTGATGTGTC TCTCACGGCT TTAAAGTGTG A* 
