>DL;IPD:MHC04482
IPD:MHC04482 Paan-DRB*W1:01 262 bases
 TTAGAGTACT GTAAGTTTGA GTGTCATTTC TTCAATGGGA CGGAGCTGGT
 GCTGTACCTG ATCAGATACT TCCATAACCA AGAGGAGTAC GTGCGCTACG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCCTGTC
 GCCGAGAACT GGAACAGCCA GAAGGACCTC CTGGAGCAGA GGCGGGCCGA
 GGTGGACAAC TACTGCAGAC ACAACTACGG GGTTGGTGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04483
IPD:MHC04483 Paan-DRB*W1:02 262 bases
 TTAGAGTACT GTAAGTTTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCTGAACCTG ATCAGATACT TCTATAACCA AGAGGAGTAC GTGCGCTACG
 ACAGCGACGT CGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCGAGTACT GGAACAGCCA GAAGGACCTC CTGGAGCAGA GGCGGGCCGA
 GGTGGACACC TACTGCAGAC ACAACTACGG GGTTGGTGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04484
IPD:MHC04484 Paan-DRB*W1:03 262 bases
 TTAGAGTACT GTAAGTTTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCTGAACCTG ATCAGATACT TCTATAACCA AGAGGAGTAC GTGCGCTACG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCGAGTACT GGAACAGCCA GAAGGACCTC CTGGAGCAGA GGCGGGCCGA
 GGTGGACACC TACTGCAGAC ACAACTACGG GGTTGTGGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04475
IPD:MHC04475 Paan-DRB*W21:01 262 bases
 TTGGAGCAGG TTAAGTCTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTCCTG GAGAGATACT TCTATAACCA GGAGGAGTAC GTGCGCTTCG
 ACAGCGACGT AGGGGAGTAC CGGGCGGTGT CGGAGCTGGG GCGGCTTAGC
 GCCGAGTACT GGAACGGCCA GAAGGACCTC CTGGAGCAGA AGCGGGGCCA
 GGTTGACAAC TACTGCAGAC ACAACTACGG GGTTGTGGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04497
IPD:MHC04497 Paan-DRB*W26:01 262 bases
 TTGGAGCAGG CTAAGTCTGA GTGTCACTTC TTCAATGGGA CGGAGCGGGT
 GCGGTTCCTG GAGAGACACT TCCATAACCA GGAGGAGTAC GCGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGA CGGAGCTGGG GCGGCCTGCA
 GCCGAGTCCT GGAACAGCCA GAAGGACTAC CTGGAAGACA CGCGGGCCTC
 GGTGGACACC TTCTGCAGAT ACAACTACGG GGTTGGTGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04487
IPD:MHC04487 Paan-DRB*W27:01 262 bases
 TTGGAGCAGG CTAAGTCTGA GTGTCATTTC TTCAATGGGA CGGAGCGGGT
 GCGGTACCTG GACAGATACA TCCATAACCA GGAGGAGTTC GTGCGCTTCG
 ACAGCGACGT GGGGGAGCAC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCGAGTACT GGAACAGTCG GAAGGACATC CTGGAAGACC AGCGGGCCGC
 GGTGGACACC TTCTGCAGAT ACAACTACCG GGTTTTTGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04488
IPD:MHC04488 Paan-DRB*W28:01 262 bases
 TTGTGGCAGG CTAAACGTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTCCTG GACAGATACA TCTATAACCA GGAGGAGCTC TTGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGA CGGAGCTGGG GCGGCCTACC
 GCCGAGAACT GGAACAGTCG GCAGGACGTC CTGGAGCAGG CGCGGGCCGC
 GGTGGACAAC TACTGCAGAC ACAACTACGG GGTTGTGGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04485
IPD:MHC04485 Paan-DRB*W3:01 262 bases
 TTGGAGCAGG CTAAACGTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTCCTC GACAGATACT TCCATAACCA GGAGGAGTAC GCGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGA CGGAGCTGGG GCGGCGTAGC
 GCGGAGTACT TCAACAGCCA GAAGGACTTT CTGGAGCAGG CGCGGACCGC
 GGTGGACAAT TACTGCAGAT ACAACTACGG GGTTGGTGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04489
IPD:MHC04489 Paan-DRB*W48:01 262 bases
 TTGGAGCAGG GTAAGTCTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTCCTG GAGAGATACT TCCATAACCA GGAGGAGTTC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCGAGTCCT GGAACAGTCG GAAGGACCTC CTGGAGCAGA AGCGGGGCCA
 GGTTGACAAC TACTGCAGAT ACAACTACGG GGTTGTGGAG AACTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04486
IPD:MHC04486 Paan-DRB*W4:01 262 bases
 TTGGAGCACG TTAAGTCTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTCCTG GAGAGACACT TCTATAACCA GGAGGAGAAC CTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAA
 GCCGAGTCCT GGAACAGCCA GAAGGACATC CTGGAGGAGA AGCGGGCCCG
 GGTGGACAAT TACTGCAGAC ATAACTACCG GGTTGGTGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04490
IPD:MHC04490 Paan-DRB*W53:01 262 bases
 TTGGAGCAGC ATAAGGCTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTGCTG GACAGATACA TCCATAACCA GGAGGAGTTC CTGCGCTTCG
 ACAGCGACGT CGGGGAGTTC CGGGCGGTGA CGGAGCTGGG GCGGCCTGTC
 GCCGAGAACT TGAACACTCG GAAGGAACTC CTGGAGCGGG AGCGGGCCCA
 GGTGGACACC GTGTGCAGAC ACAACTACGG GGGTGTGGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04492
IPD:MHC04492 Paan-DRB*W56:01 262 bases
 CTGCAGCAGT TTAAGTCTGA GTGTCACTTC TTCAACGGGA CGGAGCGGGT
 GCGGTACCTG CAGAGACACT TCTATAACCA GGAGGAGTTC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGA CGGAGCTGGG GCGGCCTGTC
 GCCGAGTACT TGAACAGCCA GAAGGACTAC CTGGAGCAGA GGCGGGCGCA
 GGTGGACAAC TACTGCAGAT ACAACTACCG GGTTGGTGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04495
IPD:MHC04495 Paan-DRB*W56:02 262 bases
 TTGGAGCAGT TTAAGTCTGA GTGTCACTTC TTCGACGGGA CGGAGCGGGT
 GCGGTACCTG CAGAGACACT TCTATAACCA GGAGGAGTTC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCCTGCC
 GCCGAGTACT TGAACAGCCA GAAGGACTAC CTGGAGCAGA GGCGGGCCCA
 GGCGGACAAC TACTGCAGAC ACAACTACGG GGTTTTTGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04498
IPD:MHC04498 Paan-DRB*W57:01 262 bases
 TTGGAGCAGG CTAAGTCTGA GTGTCACTTC TTCAATGGGA CGGAGCGGGT
 GCGGTACCTG GACAGATACT TCTATAACCA GGAGGAGTAC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCCAATACT GGAACAGCCA GAAGGACTTC CTGGAAGACA GTCGGGCCGC
 GGTGGACACC TACTGCAGAC ACAACTACGG GGTTGGTGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04500
IPD:MHC04500 Paan-DRB*W58:01 259 bases
 TTGCAGCGGG ATTATCTTGA GTGTCATTTC TTCAATGGGA CGGAGCGGGT
 GCAGTACCTG GAGAGATACT TCTATAACCA GGAGGAGTTC CTGCGCTTCG
 ACAGCCACGT GGGGGAGTTC CGGGCGGTGT CGGAGCTGGG GCGGCCTGAA
 GCCGAGTCCT GGAACAGCCG GAAGGACGTC CTGGAAGACA GGCGGGCCCG
 GGTGGACATC TGCAGACGGA ACTACCGGGT TGTGGAGAGC TTCACAGTGC
 AGCGGCGAG*    
>DL;IPD:MHC04477
IPD:MHC04477 Paan-DRB*W6:01 262 bases
 TTGAAGCAGA CTAAGGCTGA GTGTCATTTC TTCAATGGGA CGGAGCGGGT
 GCGGTTGCTG GACAGACACT TCTATAACCA GGAGGAGTAT GTGCGCTATG
 ACAGCTACGT CGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCGTAGC
 GCCGAGTACT TCAACAGCCA AAAGGACTAC CTGGAGCGGA CGCGGGCCGA
 GGTGGACACC TACTGCAGAC ACAACTACAG GGTTGTTGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04478
IPD:MHC04478 Paan-DRB*W6:02 262 bases
 TTGAAGCAGA CTAAGGCTGA GTGTCACTTC TTCAATGGGA CGGAGCGGGT
 GCGGTTGCTG GACAGACACT TCTATAACCA GGAGGAGTAT GTGCGCTATG
 ACAGCTACGT CGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCGTAGC
 GCCGAGTACT TCAACAGCCA AAAGGACTAC CTGGAGCAGA GGCGGGCCGC
 GGTGGACACC TACTGCAGAC ACAACTACAG GGTTGGTGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04479
IPD:MHC04479 Paan-DRB*W7:01 262 bases
 TTGCAGCAGC AAAAGGCTGA GTGTCGTTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTCCTG GAGAGATACA TCTATAACCA GGAGGAGTAC GTGCGCTTCG
 ACAGCGACGT CGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCGTAGC
 GCCGAGTACT GGAACAGCCA GAAGGACGCC CTGGAGGAGA AGCGGGCCCG
 GGTGGACACC TACTGCAGAC ACAACTACCG GGTTGGTGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04476
IPD:MHC04476 Paan-DRB*W81:01 262 bases
 TTGTGGCAGT TTAAGCCTGA GTGTCATTTC TTCAACGGGA CGGAGCGAGT
 GCGGTTCCTG GACAGATACT TCTATAACCA GGAGGAGTTC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCCAGTACT GGAACAGCCA GAAGGACATC CTGGAAGACG AGCGGGCCGC
 GGTGGACACC TTCTGCAGAC ACAACTACGG GGGTGTGGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04480
IPD:MHC04480 Paan-DRB*W81:02 262 bases
 TTGTGGCAGT TTAAGCCTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTCCTG GACAGATACT TCTATAACCA GGAGGAGCTC CTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGT CGGAGCTGGG GCGGCCTCAA
 GCCGAGTCCT GGAACAGCCA GAAGGACTTC CTGGAAGACA GGCGGGCCCA
 GGTGGACACC GTGTGCAGAC ACAACTACCG GGTTGTGGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04481
IPD:MHC04481 Paan-DRB*W81:03 262 bases
 TTGTGGCAGT TTAAGCCTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTCCTG GAGAGACACT TCTATAACCA GGAGGAGCTC CTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGT CGGAGCTGGG GCGGCCTCAA
 GCCGAGTCCT GGAACAGCCA GAAGGACTTC CTGGAAGACA GGCGGGCCCA
 GGTGGACACC GTGTGCAGAC ACAACTACCG GGTTGTGGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04491
IPD:MHC04491 Paan-DRB*W82:01 262 bases
 TTGGAGCAGG TTAAACATGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTCCTG GACAGATACT TCTATAACCA GGAGGAGTAC GCGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCGAGTACT GGAACAGCCA GAAGGACCTC CTGGAGCGGA GGCGGGCCGA
 GGTGGACACC TACTGCAGAC ACAACTACGG GGTTGGTGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04499
IPD:MHC04499 Paan-DRB*W83:01 262 bases
 TTGGAGCAGG CTAAGTCTGA GTGTCACTTC TTCAATGGGA CGGAGCGGGT
 GCGGTTCCTG GACAGATACA TCCATAACCA GGAGGAGTTC GCGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCGAGTCCT GGAACAGCCA GAAGGACCTC CTGGAAGGCA GGCGGGCCGC
 GGTGGACACC TACTGCAGAC ACAACTACAG GATTGCGGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04504
IPD:MHC04504 Paan-DRB*W84:01 259 bases
 TTGGAGCAGG CTAAGTGTGA GTGTCATTTC TTCAATGGGA CGGAGCGGGT
 GCGGTACCTG GAGAGATACA TGTATAACCA GGAGGAGTAC GCGCGCTTTG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCGAGAACT GGAACAGCCG GAAGGACGTC CTGGAAGACA GGCGGGCCCG
 GGTGGACATC TGCAGACACA ACTACGGGGT TGGTGAGAGC TTCACAGTGC
 AGCGGCGAG*    
>DL;IPD:MHC04501
IPD:MHC04501 Paan-DRB1*03:01 262 bases
 TTGGAGTACT CTACATCTGA GTGTCACTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTCCTC GACAGATACT TCTATAACCA AGAGGAGAAC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGT CAGAGCTGGG GCGGCCAGAC
 GCCGAGTACT GGAACGGCCG GAAGGACATC CTGGAAGACG AGCGGGCCTC
 GGTGGACACC TTCTGCAGAC ACAACTACAG GGTTGGTGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04505
IPD:MHC04505 Paan-DRB1*03:02 262 bases
 TTGGAGTACT CTACATCTGA GTGTCACTTC TTCAACGGGA TGGAGCGGGT
 GCGGTTCCTG GACAGATACT TCTATAACCA GGAGGAGTAC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGT CGGAGCTGGG GCGGCGTAGC
 GCGGAGTACT GGAACAGCCG GAAGGACTAC CTGGAAGACG AGCGGGCCGC
 GGTGGACACC TACTGCAGAT ACAACTACGG GGTTGTGGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04506
IPD:MHC04506 Paan-DRB1*03:03 262 bases
 TTGGAGTACT CTACATCTGA GTGTCACTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTCCTG GACAGATACT TCTATAACCA GGAGGAGTAC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGT CGGAGCTGGG GCGGCGTAGC
 GCGGAGTACT GGAACAGCCG GAAGGACTAC CTGGAAGACG AGCGGGCCGC
 GGTGGACACC TACTGCAGAT ACAACTACGG GGTTGTGGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04507
IPD:MHC04507 Paan-DRB1*03:04 262 bases
 TTGGAGTACT CTACATCTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTCCTG GACAGATACT TCTATAACCA GGAGGAGTTA GTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGT CGGAGCTGGG GCGGCCTGAA
 GCCGAGTCCT GGAACAGCCG GAAGGACGTC CTGGAGCGGG CGCGGACCGC
 AGTGGACAAC TACTGCAGAT ACAACTACCG GGTTGGTGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04508
IPD:MHC04508 Paan-DRB1*03:05 262 bases
 TTGGAGTACT CTACGTCTGA GTGTCACTTC TTCAATGGGA CGGAGCGGGT
 GCGGTACCTG GACAGATACT TCTATAACCA AGAGGAGTAC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCGAGTACT GGAACAGCCA GAAGGACCTC CTGGAGCAGA AGCGGGGCCA
 GGTGGACAAC TACTGCAGAC ACAACTACGG GGTTGGTGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04502
IPD:MHC04502 Paan-DRB1*07:01 262 bases
 TTGTGGCAGT CTAAGGCTAA ATGTCACTTC TTCAACGGGA CGGAGCGGGT
 GCGGTACCTG GAGAGACACA TCTATAACCA GGAGGAGCTC ATGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGT CGGAGCTGGG GCGGCCTGCC
 GCCGAGTACT GGAACAGCCT GAAGGACTAC CTGGAGCAGA AGCGGGCCGC
 GGTGGACACC TACTGCAGAC ACAACTACGG GGTTGTGGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04503
IPD:MHC04503 Paan-DRB1*10:01 262 bases
 TTGGAGTACG TTAAGTTTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTACCTG ATCAGAGTCT TCCATAACCG AGAGGAGTAC GCGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGA CGGAGCTGGG GCGGCGTAGC
 GCCGAGTACT GGAACAGCCA GAAGGACTTC CTGGAGCAGA AGCGGGCCGC
 GGTGGACACC TACTGCAGAC ACAACTACGG GGTTGTGGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04493
IPD:MHC04493 Paan-DRB3*04:01 262 bases
 TTGGAGCAGG GTAAGTCTGA GTGTCACTTC TTCAACGGGA CGGAGCGGGT
 GCGGTACCTG CAGAGACACT TCTATAACCA GGAGGAGTTC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGA CGGAGCTGGG GCGGCCTGTC
 GCCGAGTCCT GGAACAGCCA GAAGGACTAC CTGGAGCAGA GGCGGGCCGC
 GGTGGACACC TACTGCAGAT ACAACTACCG GGTTGGTGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04494
IPD:MHC04494 Paan-DRB3*04:02 262 bases
 TTGGAGCAGG GTAAGTCTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTACCTG CAGAGACACT TCTATAACCA GGAGGAGTTC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGA CGGAGCTGGG GCGGCCTGTC
 GCCGAGTCCT GGAACAGCCA GAAGGACTAC CTGGAGCAGA GGCGGGCCGC
 GGTGGACAAC TTCTGCAGAT ACAACTACCA GGTTGGTGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04496
IPD:MHC04496 Paan-DRB3*04:03 262 bases
 TTGGAGCAGG GTAAGTCTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTACCTG CAGAGACACT TCTATAACCA GGAGGAGTTC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGA CGGAGCTGGG GCGGCCTGTC
 GCCGAGTCCT GGAACAGCCA GAAGGACTAC CTGGAGCAGA GGCGGGCCGC
 GGTGGACACC TACTGCAGAT ACAACTACCA GGTTGGTGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04509
IPD:MHC04509 Paan-DRB5*03:01 262 bases
 TTGAAGCAGG ATAAGTATGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTGCTG CACAGATACA TCTATAACCA AGAGGAGGAC GCGCGTTTCG
 ACAGCGACGT CGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCGAGTACT GGAACAGCCA GAAGGACGTC CTGGAGCAGA GGCGGGCCGA
 GGTGGACACT GTGTGCAGAC ACAACTACAG GGGTGTGGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04510
IPD:MHC04510 Paan-DRB5*03:02 262 bases
 TTGAAGCAGG ATAAGTATGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTGCTG CACAGAGACA TCTACAACCA AGAGGAGGAC GCGCGTTTCG
 ACAGCGACGT CGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCCTGTC
 GCCGAGTACT TGAACAGCCA GAAGGACGTC CTGGAGCAGA GGCGGGCCGA
 GGTGGACACT GTGTGCAGAC ACAACTACAG GGGTGTGGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04511
IPD:MHC04511 Paan-DRB5*03:03 262 bases
 TTGAAGCAGG AAAAGTTTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTGCTG CACAGATACA TCTATAACCA AGAGGAGGAC GTGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 GCCGAGTACT GGAACAGTCA GAAGGACCTC CTGGAGCAGA GGCGGGCCGC
 GGTGGACACC TACTGCAGAC ACAACTATGG GGTTGTGGAG AGCTTCATAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04512
IPD:MHC04512 Paan-DRB5*03:04 262 bases
 TTGAAGCAGG ATAAGTTTGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT
 GCGGTTCCTG CACAGATACA TCTATAACCA AGAGGAGGAC GCGCGCTTCG
 ACAGCGACGT GGGGGAGTAC CGGGCGGTGA CGGAGCTGGG GCGCCCTGAC
 GCCGAGTACT GGAACAGCCG GAAGGACGTC CTGGAAGACA GGCGGGCCCA
 GGTGGACACC GTGTGCAGAC ACAACTATGG GGTTGTGGAG AGCTTCACAG
 TGCAGCGGCG AG*   
>DL;IPD:MHC04513
IPD:MHC04513 Paan-DRB6*01:01 259 bases
 TTGGAGCAGG CTAAGTGTGA GTGTCATATC TTCAATGGGA CTGAGCGGGT
 GCAGTACCTG GACAGATACA TCCATAAACG GGAGGAGAAC CTGCGCTTCC
 ACAGCGACGT GGGGGAGTTC CAGGCGGTGA CGGAACTGGG GCGGCCTGTC
 GCGGAGAACT GGAACAGCCA GAAGGGCATC CTAGAGAAGC GGGACAAGGT
 GGACTCCTAC TGCAGATACA ATTACGGGGT TTTTGAGAGC TTCACAGAGC
 AGCGATGAG*    
>DL;IPD:MHC04514
IPD:MHC04514 Paan-DRB6*01:02 262 bases
 TTGGAGCAGG CTAAATGTGA GTGTCATATC TTCAATGGCA CTGAGCGGGT
 GCGGTACCTG AACAGAAACA TCCATAAACG GGAGGAGAAC CTGCGCTTCC
 ACAGCGACCT GGGGGAGTTC CAGGCGGTGA CGGAACTGGA GCGGCCTGTC
 GCGGAGAACT GGAACAGCCA GAAGGGCATC CTGGAGGAGA AGCGGGACAA
 GGTGGACACC TACTGCAGAT ACAATTACAG GGTTTTTGAG AGCTTCACAG
 AGCAGCGATG AG*   
>DL;IPD:MHC04515
IPD:MHC04515 Paan-DRB6*01:03 262 bases
 TTGGAGCAGG CTAAGTGTGA GTGTCATATC TTCAATGGGA CTGAGCGGAT
 GCAGTACCTG AACAGATACA TCCATAAACG GGAGGAGAAC CTGCGCTTCC
 ACAGCGACCT GGGGGAGTTC CAGGTGGTGA CGGAACTGGG GCGGCCTGTC
 GCGGAGAACT GGAACAGCCA GAAGGGCATC CTGGAGGAGA AGCGGGACTA
 GGTGGACACC TACTGCAAAT ACAATTACAG GGTTTTTGAG AGCTTCACAG
 AGCAGCGATG AG*   
>DL;IPD:MHC04516
IPD:MHC04516 Paan-DRB6*01:04 259 bases
 TTGGAGCAGG CTAAGTGTAA GTGTCATATC TTCAATGGGA CTGAGCCGGT
 GCAGTACCTG AACAGATACA TCCATAAACG GGAGGAGAAC CTGCGCTTCC
 ACAGCGACGT GGGGGAGTTC CAGGCGGTGA CAGAACTGGA GTGGCCTGTC
 GCGGAGAACT GGAACAGCCA GAAGGGCATC CTAGAGAAGC GGGACAAGGT
 GGACTCCTAC TGCAGATACA ATTACGGGGT TTTTGAGAGC TTCACAGAGC
 AGCGATGAG*    
>DL;IPD:MHC04517
IPD:MHC04517 Paan-DRB6*01:05 262 bases
 TTGGAGCAGG CTAAGTGTGA GTGTCATATC TTCAATGGGA CTGAGCGGGT
 GCAGTACCCG AACAGAAACA TCCATAAACG GGAGGAGAAC CTGCGCTTCC
 ACAGCGACCT GGGGGAGTTC CAGGCGGCGA CGCAACTGGG GCGACCTGTC
 GCGGAGAACT GGAACAGCCA GAAGGGCATC CTGGAGGAGA AGCGGGACAA
 GGTGGACACC TACTGCAGAT ACAATTACGG GGTTTTTGAG AGCTTCACAG
 AGCAGCCAAG AG*   
>DL;IPD:MHC04518
IPD:MHC04518 Paan-DRB6*01:06 262 bases
 TTGGAGCAGG CTAAGTGTGA GTGTCATATC TTCAATGGGA CTGAGCGGGT
 GCAGTACCTG AACAGATACA TCCATAAACG GGAGGAGAAC CTGCGCTTCC
 ACAGCGACCT GGGGGAGTTC CAAGCGGTGA CGGAACTGGG GCGGCCTGTC
 GCGGAGAACT GGAACAGCCA GAACGGCATC CTGGAGGAGA AGCGGGACTA
 GGTGGCCACC TACTGCAGAT ACAATTACGG GGTTTTTGAG AGCTTCACAG
 AGCACCGAAG AG*   
>DL;IPD:MHC04519
IPD:MHC04519 Paan-DRB6*01:07 262 bases
 TTGGAGCAGG CCAAGTGTGA GTGTCCTATC TTCAATGGGA CTGAGCGGGT
 GCAGTACCTG AACAGATACA TCTATAAACG GGAGGAGAAC CTGCGCTTCC
 ACAGCGACCT GGGGGAGTTT CAGGCGGTGA CGCAACTGGG GCGGCCTGTC
 GCAGAGAACT GGAACAGCCA GAAGGGCATC CTGGAGGAGA AGCGGGACTA
 GGTGGACACC TATTGCAGAA ACAATTACGG GGTTTTTGAG AGCTTCACAG
 AGCAGCGATG AG*   
>DL;IPD:MHC04520
IPD:MHC04520 Paan-DRB6*01:08 262 bases
 TTGGAACAGG GTAAGTCTGA GTGTCAAATC TTCAACGGGA GGGAGCGGGT
 GCGGTACCTG AACAGAAACA TCCATAAACG GGAGGAGAAC CTGCGCTTCC
 ACAGCGACGT GGGGGAGTTC CAGGCGGTGA TGGAACTGGG GCGGCCTGTC
 GCGGAGAACT GGAACAGCCA GAAGGGCATC CTGGAGGAGA AGCGGGACAA
 GGTGGACACC TACTGCAGAT ACAATTACCG GGTTTTTGAG AGCTTCACAG
 TGCAGCGATG AG*   
>DL;IPD:MHC04521
IPD:MHC04521 Paan-DRB6*01:09 262 bases
 TTGGAGCAGG GTAAGTCTGA GTGTCAAATC TTCAACGGGA GGGAGCCGGT
 GCGGTACCTG AACAGAAACA TCCATAAACG GGAGGGGAAC CTGCGCTTCG
 ACAGCGACGT CGGGGAGTTC CAGGCGGTGA CGGAACTGGG GCGGCCTGTC
 GCGGAGAACT GGAACAGCCA GAAGGGCATC CTGGAGGAGA AGCGGGACAA
 GGTGGACACC TACTGCAGAT ACAATTACCG GGTTTTTGAG AGCTTCACAG
 AGCAGCGATG AG*   
