>DL;IPD:MHC00655
IPD:MHC00655 Pacy-B*01 1089 bases
 ATGCGGGTCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCGCA CTCCTTGAGG TATTTCAGCA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC AACAGCGACG CCGAGAGTCC
 GAGGATGCAG CCGCGGGCGC GGTGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGAAGAGGA GACACGGAAA GCCAAGGACA TCACACAGTT TTTCCGAGTG
 GGCCTGGGGA ACCTGCGCGG CTACTACAAC CAGAGCGAGG CGGGGTCCCA
 CACCTTCCAG TGGATGGCTG GCTGCGACCT GGGATCCGAC GGGCGCCGCC
 TCGGCGGGTA TCACCAGTTC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGGGGACC TGCGCTCCTG GACCGCCGCG GACATGGCGG CTCGGTTCAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGAGGC AGAGCGGTTC AGAGCCTACG
 TGGAGGGCCG GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA TCCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG AAGGGGAGGA CCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA CCTTCCAGAA
 GTGGGGAGCT GTGGTGGTAC CTTCTGGAGA AGAGCAGAGA TACACGTGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAACCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATCGTTGTTG GCCTGGCTGT
 CCTAGCAGTT GTGTTCACTG GAGCTGTGGT CGCAGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACGGCTTGA* 
>DL;IPD:MHC00656
IPD:MHC00656 Pacy-B*02 1089 bases
 ATGCGGGTCA TGGCGGTCCG AACCCTCCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCACCA
 CCGCCCTGTC CCGGCCCGGC CGCTGGGAGC CCCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGCGAGTCC
 GAGGATGGAG CCGCGGGCGC GGTGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGAGGAGCA GACACGGAGA GCCAAGGGCC ACGCACAGAC TGACCTAGGG
 AGCCTGAGGA TCCTGCGCGG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCTACCAG TGGATGGCTG GCTGCGACGT GGGACCCGAC GGGCGCCTCC
 TCCGCGGGTA TCACCAGCGC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCCGCG GACGTGGCGG CTCAGAAAAC
 TCAGCGCAAG TGGGAGGCGG CCCGTTTGGC AGAGCAGTGG AGAGCCTACC
 TGGAGGGCGA GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGGACGGA CCCCCCAAAG ACACACGTGA CCAACCACCC
 CGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CTCACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGGA GGAGATGGAA CCTTCCAGAA
 GTGGGGAGCT GTGGTGGTGC CTTCTGGACA AGAGCAGAGA TACACGTGCC
 ATGTGCAGCA CGAGGGATTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATCGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCATCG GAGCTGTGGT CGCTGCTGTG ATGTGGAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACGGCTTGA* 
>DL;IPD:MHC00657
IPD:MHC00657 Pacy-B*03 1080 bases
 ATGGCGCCCC GAACCCTCCT CCTGCTGCTC TCGGGGGCCC TGGCCCTGAG
 CGAGACCTGG GCCGGCTCGC ACTCCATGAA GTATTTCTAC ACCGCCGTGT
 CCCGGCCCGG CCGCTGGGAG CCCCGCTTCA TCTCCGTGGG CTACGTGGAC
 GACACGCAGT TCGTGCGGTT CGACAGCGAC GCCGAGAGTC CGAGAAAGGA
 GCCGTGGGCG CCGTGGGCGG AGCAGGAGGG GCCGGAGTAT TGGGAAGAGC
 AGACACGGAG AGCCAAGGCC AACGCACAGG CTGACCGAAT GTGCCTGCGG
 ACCGTGCCCG GCTACTACAA CCAGAGCGAG GCCGGGTCTC ACACCTTCCA
 GAGTATGTAT GGCTGCGGCC TGGGGCCCGA CTGGCGCCTC CTCCGCGGGT
 ATTACCAGTC GGCCTACGAC GGCAGGGATT ACATCGCCCT GAACAAGGAC
 CTGCTCTCCT GGACCTCCGC GGACGTGGCG GCTCAGAACA CCCAGCGCGA
 GTGGGAGGCG GACCGTTATG CAGAGCAGTG GAGAACCTAC CTGGAGGGCG
 AGTGCGTGGA GTCGCTCCGC AGATACCTGG AGAACGGGAA GGAGACGCTG
 CAGCGCGCGG ACCCCCCAAA GACACACGTG ACCCACCACC CCATCTCTAA
 CCATGAGGCC ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA
 TCACACTGAC CTGGCAGCGG GATGGGGAGG ACCAAACTCA GGACACAGAG
 CTTGTGGAGA CCAGGCCAGC AGGAGATGGA ACCTTCCAGA AGTGGGGAGC
 TGTGGTGGTG CCTTCTGGAG AAGAGCAGAG ATACACGTGC CATGTGCAGC
 ACGAGGGATT GCCAGAGCCC CTCACCCTGA GATGGGAACC ATCTTCCCAG
 TCCACCATCC CCATCGTGGG CATTGTTGCT GGCCTGGCTG TTGTAGCAGT
 TGTGGTCACC GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AGGAAGAGCT
 CAGGTGCAAA AGGAGGGAGC TACTCTCAGG CTGCGTCCAA CGACAGTGCC
 CAGGGCTCTG ATGTGTCTCT CACGGCTTGA * 
>DL;IPD:MHC00658
IPD:MHC00658 Pacy-B*04 1080 bases
 ATGGCGCCCG GAACCCTCCT CCTGCTGCTC TCGGAGGCCC TGGCCCTGAC
 CGAGACCTGG GCCGGCTCGC ACTCCTTGAG GTATTTCAGC GCCGGCACGT
 CCCGGCCCGG CCGCGGGGAG CCCCGCTTCA TCTCCGTGGG CTACGTGGAC
 GACACGCAGT TCCTGCGGTT CGACAGCGAC GCCGCGAGTC CGAGGATGGA
 GCCGCGGGCG CCGTGGGCGG AGCAGGAGGG GCCGGAGTAT TGGGAAGAGC
 AGACAGGGCT CGCCAAGGAC ATCACACAGT CTTTCCGAGT GGGCCTGGGG
 AACCTGCGCG GCTACTACAA CCAGAGCGAG GCGGGGTCTC ACACCCTCCA
 GTGGATATAC GGCTGCGACC TGGGGCCCGA CGGGCGACTC CTCCGCGGAT
 ATCACCAGTT CGCCTACGAC GGCAAGGATT ACATCGCCCT GAACGGTGAC
 CTGCGCTCCT GGACCGCGGC AGACACGGCG GCTCAGATAA CTCAGCGCAA
 GTGGGAGGCG GCCCGCGAGG CAGAGCAGAT GAGAGCGCAC CTGGAGGGGA
 CGTGCGTGGA GTGGCTCCGC AGACACCTGG AGAAGGGGAA GGAGAGGCTG
 CAGCGCGCGG ATCCCCCAAA GACACACGTG ACCCACCACC CCGTCTCTGA
 CCATGAGGCC ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA
 TCACATTGAC CTGGCAGCGG GATGGGGAGG AGCAAACTCA GGACACCGAG
 CTTGTGGAGA CCAGGCCAGT AGGAGATGGA ACCTTCCAGA AGTGGGCAGC
 TGTGGTGGTG CCTTCTGGAG AAGAGCAGAG ATACACGTGC CATGTGCAGC
 AACAGGGACT GCCGGAGCCC CTCACCCTGA GATGGGAGCC ATCTTCCCAG
 TCCACCATCA CCATCGTGGG CATTGTTGCT GGCCTGGCTG TCCTAGCAGT
 TGTGGTCACT GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AGGAAGAGCT
 CAGGTGGAAA AGGAGGGAGC GACTCTCAGG CTGCGTCCAG CGACAGTGTC
 CAGGGCTCTG ATGTGTATCT CACGGCTTGA * 
