>DL;IPD:MHC00668
IPD:MHC00668 Pacy-E*02:01 360 bases
 MALGTLLLLL SALTKTWAGS HSLKYFHTSV SRPGRGGPRF ISVGYVDDTQ
 FVRYDSDAAS PRMEPRALWM EQEGPEYWDQ ETRSARDTAQ TFRVNLDTLR
 GYYNQSEAGS HTLQWMHGCD LGPDGRFLRG YEQFAYDGKD YLTLNEDLRS
 WSAVDTAAQI SEQKSNDGSE AEHQRAYLED TCVEWLRRYL ENGKETLQRS
 EPPKTHVTHH PVSDHEATLR CWALGFYPAE ITVTWQRDGE DQTQDTELVE
 TRPAGDGTFQ KWAAVVVPSG EEQRYTCHVQ HEGLPEPLTL RWEPSSQSTI
 PIVGIIAGLV LLGAVVTGAM VAAVMWRRKS SGRKGGSYSQ AVCSDGAQGS
 DESLTAYEPX *   
