>DL;IPD:MHC00651
IPD:MHC00651 Pacy-A*01 364 bases
 MAVMAPRTLL LLLSGALALT QTWASSHSMR YFYTSVSRPG RGEPRFIAVG
 YVDDTQFLRF DSDAASQRLE PRARWVEQEG PEYWDRNTRI VKAETQNAPV
 NLQNLRGYYN QSEAGSHTIQ RMYGCDLGPD GRLLRGYEQY AYDGRDYIAL
 NEDLRSWTAA DMAAQNTQRK WEAARAAEQH RTYLEGECLE WLRRHLENGK
 ETLQRADPPK THVTHHPVSD YEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGKEQR YTCHVQHEGL PKPLTLRWEP
 SSQSTIVGII AGLVLLGAVV TGAVVAAVMW RRKSSDRKGG SYSQAASSDS
 AQGSDVSLTA CKVX*   
>DL;IPD:MHC00652
IPD:MHC00652 Pacy-A*02 364 bases
 MAVMAPRTLL LLLSGALALT QTWASSHSMR YFYTSVSRPG RGEPRFIAVG
 YVDDTQFLRF DSDAASQRLE PRARWVEQEG PEYWDRNTRI VKAETQNAPV
 NLQNLRGYYN QSEAGSHTIQ RMYGCDLGPD GRLLRGYEQY AYDGRDYIAL
 NEDLRSWTAA DMAAQNTQRK WEATRAAEQH RTYLEGECLE WLRRHLENGK
 ETLQRADPPK THVTHHPVSD YEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGKEQR YTCHVQHEGL PKPLTLRWEP
 SSQSTIVGII AGLVLLGAVV TGAVVAAVMW RRKSSDRKGG SYSQAASSDS
 AQGSDVSLTA CKVX*   
>DL;IPD:MHC00653
IPD:MHC00653 Pacy-A*03 366 bases
 MAVMAPRTLL LVLSGVLALT QTWAGSHSMR YFYTSMSRPG RGQPRFFAVG
 YVDDTQFVRF DSDAASQRME PRAPWVEQEG PEYWDRETQN MKAQTQNAPV
 NLRNLRGYYN QSEAGSHTLQ TMLGCDLGPD GRLLRGYYQS AYDGKDYFAL
 NEDLRSWTAA DLAAQNTQRK WEAADVAEQI RAYLEGRCVE WLRRYLENGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAV GFYPAEITLT WQRDGEDQTQ
 DTELMETRPA GDGTFQKWAA VVVPSGKEQR YTCHVQHEGL PKPLTLRWEP
 SSQSTIPIVG IIAGLVLLGA MVIGAVVAAV MWRRKSSDRK GGSYSQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC00654
IPD:MHC00654 Pacy-A*04 366 bases
 MAVMAPRTLL LVLSGALALT QTRAGSHSMS YFYTSMSRPG RGEPRFFAVG
 YVDDTQFVRF DSDAASQRME PRAPWVEQEG PEYWDRSTRI MKTATQNAPV
 GLRNLRGYYN QSEAGSHTYQ SMYGCDLGPD GRLLRGYYQS AYDGRDYIAL
 NEDLRSWTAA DMAAQNTQRK WETEGVAEQL SAYLEGECLE WLRRHLENGK
 EMLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGKEQR YTCHVQHEGL REPLTLRWEP
 SSQSTIPIVG IIAGVVLLGI VVTGAVIAAV IWRRKSSDGK GGSYSQAASS
 DSAQGSDVSL TACKVX*   
