>DL;IPD:MHC00655
IPD:MHC00655 Pacy-B*01 363 bases
 MRVMAPRTLL LLLSGALALT ETWAGSHSLR YFSTAVSRPG RGEPRFIAVG
 YVDDTQFVRF NSDAESPRMQ PRARWIEQEG PEYWEEETRK AKDITQFFRV
 GLGNLRGYYN QSEAGSHTFQ WMAGCDLGSD GRRLGGYHQF AYDGKDYIAL
 NGDLRSWTAA DMAARFTQRK WEAAGEAERF RAYVEGRCVE WLRRYLENGK
 ETLQRADPPK THVTHHPVSD HEATLRCWAL GFYPAEITLT WQREGEDQTQ
 DTELVETRPG GDGTFQKWGA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVVGLAVLAV VFTGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00656
IPD:MHC00656 Pacy-B*02 363 bases
 MRVMAVRTLL LLLSGALALT ETWAGSHSMR YFTTALSRPG RWEPRFIAVG
 YVDDTQFVRF DSDAASPRME PRARWIEQEG PEYWEEQTRR AKGHAQTDLG
 SLRILRGYYN QSEAGSHTYQ WMAGCDVGPD GRLLRGYHQR AYDGKDYIAL
 NEDLRSWTAA DVAAQKTQRK WEAARLAEQW RAYLEGECVE WLRRYLENGK
 EMLQRTDPPK THVTNHPVSD HEATLRCWAL GFYPAEISLT WQRDGEDQTQ
 DTELVETRPG GDGTFQKWGA VVVPSGQEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVIGAVVAAV MWRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00657
IPD:MHC00657 Pacy-B*03 360 bases
 MAPRTLLLLL SGALALSETW AGSHSMKYFY TAVSRPGRWE PRFISVGYVD
 DTQFVRFDSD AESPRKEPWA PWAEQEGPEY WEEQTRRAKA NAQADRMCLR
 TVPGYYNQSE AGSHTFQSMY GCGLGPDWRL LRGYYQSAYD GRDYIALNKD
 LLSWTSADVA AQNTQREWEA DRYAEQWRTY LEGECVESLR RYLENGKETL
 QRADPPKTHV THHPISNHEA TLRCWALGFY PAEITLTWQR DGEDQTQDTE
 LVETRPAGDG TFQKWGAVVV PSGEEQRYTC HVQHEGLPEP LTLRWEPSSQ
 STIPIVGIVA GLAVVAVVVT GAVVAAVMWR RKSSGAKGGS YSQAASNDSA
 QGSDVSLTAX *   
>DL;IPD:MHC00658
IPD:MHC00658 Pacy-B*04 360 bases
 MAPGTLLLLL SEALALTETW AGSHSLRYFS AGTSRPGRGE PRFISVGYVD
 DTQFLRFDSD AASPRMEPRA PWAEQEGPEY WEEQTGLAKD ITQSFRVGLG
 NLRGYYNQSE AGSHTLQWIY GCDLGPDGRL LRGYHQFAYD GKDYIALNGD
 LRSWTAADTA AQITQRKWEA AREAEQMRAH LEGTCVEWLR RHLEKGKERL
 QRADPPKTHV THHPVSDHEA TLRCWALGFY PAEITLTWQR DGEEQTQDTE
 LVETRPVGDG TFQKWAAVVV PSGEEQRYTC HVQQQGLPEP LTLRWEPSSQ
 STITIVGIVA GLAVLAVVVT GAVVAAVMWR RKSSGGKGGS DSQAASSDSV
 QGSDVYLTAX *   
