>DL;IPD:MHC00669
IPD:MHC00669 Paha-DPA1*02:01 189 bases
 TTTGTACAGA CACATAGACC AACAGGGGAG TATATGTTTG AGTTTGATGA
 AGATGAGCAG TTCTATGTGG ATCTGGACAA GAAGGAGACC GTCTGGCATC
 TGGAGGAGTT TGGCCGAGCC TTTTCCTTTG AGGCTCAGGG CGGGCTGGCT
 AACATTGCTA TATTGAACAA CAACTTGAAT ATCACGATC* 
