>DL;IPD:MHC00677
IPD:MHC00677 Paha-DRB1*03:01 270 bases
 CACGTTTCTT GGAGTACTCT ACATCTGAGT GTCACTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAACCGAG AGGAGTACGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC CGAGTACTGG AACGGCCGGA AGGACATCCT GGAAGACGAG
 CGGGCCTCGG TGGACAACTA CTGCAGATAC AACTACGGGG TTGTGGAGAG
 CTTCACAGTG CAGCGGCGAG *  
