>DL;IPD:MHC00670
IPD:MHC00670 Paha-DQA1*01:01 188 bases
 TCTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGACG GAGACGAGCA
 GTTCTACGTG GACCTGGGGA GGAAGGAGAC GGCCTGGCGA TGGCCTGAGT
 TAAGCAAATT TGGAGGTTTT GACCCGCAGG GTGCACTGAG AAACTTGGCT
 ACAGCAAAAT ACAACTTGAA CATCATGACT AAACGCTA* 
>DL;IPD:MHC00671
IPD:MHC00671 Paha-DQA1*05:01 185 bases
 TCTTACGGTT TCTCTGGCCA GTACTCCCAT GAATTTGACG GAGATGAGCA
 GTTCTACGTG GACCTGGAGA GGAAGGAGAC TGTCTGGCGG TTGCCTGTTC
 TCAGCCAATT TAGTTTCGAC GCGCAATTTG CACTGACAAA CATTGCTGTG
 GGAAAACAGA ACTTGAACTA CCAGATGAAA CAGTC* 
>DL;IPD:MHC00672
IPD:MHC00672 Paha-DQA1*05:02 185 bases
 TCTTACGGTT TGTCTGGCCA GTACTCCCAT GAATTTGACG GAGATGAGCA
 GTTCTACGTG GACCTGGAGA GGAAGGAGAC TGTCTGGCAG TTGCCTGTTC
 TCAGCCAATT TAGTTTCGAC GCGCAATTTG CACTGACAAA CATTGCTGTG
 GGAAAACAGA ACTTGAACTA CCTGATGAAA CAGTC* 
>DL;IPD:MHC00673
IPD:MHC00673 Paha-DQA1*25:01 188 bases
 TTTTATGGTT CCTCTGGCCA GTACACCCAT GAATTTGATG GAGACGAGCA
 GTTCTATGTT GACCTGGAGA GGAAGGAGAC TGTCTGGCGG TTGCCTCTGT
 TCAGCAAATT TGCAGGTTTT GACCCTCAGG GTGCACTGAG AAACATCGCT
 GTGGGAAAAC ACACCTTGAA CATGATGATT AAACACTC* 
