>DL;IPD:MHC04392
IPD:MHC04392 Papa-DRB1*02:01 219 bases
 CGTTTCCTGT TGCAGCCTAA GGGGGAGTGT CATTTCTTCA ATGGGACGGA
 GCGGGTGCGG TTGCTGGAGA GATACTTCTA TAACCAAGAG GAGTTCATGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGATGCCG AGTACTGGAA CAGCCAGAAG GACTTCCTGG AGCAGAGGCG
 GGCCGCGGTG GACAATTAC*   
>DL;IPD:MHC04393
IPD:MHC04393 Papa-DRB1*02:02 219 bases
 CGTTTCCTGT TGCAGCCTAA GGGGGAGTGT CATTTCTTCA ATGGGACGGA
 GCGGGTGCGG TTCCTGGACA GATACTTCTA TAACCAAGAG GAGTTCATGC
 GCTTCGACAG CGACGTAGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGTCGCCG AGTACTGCAA CAGCCAGAAG GACTTCCTGG AGCAGAGGCG
 GGCCGCGGTG GACACCTAC*   
>DL;IPD:MHC04394
IPD:MHC04394 Papa-DRB1*03:01 219 bases
 CGTTTCTTGG AGTACTCTAC GCCTGAGTGT CATTTCTTCA ATGGGACGGA
 GCGGGTGCGG TTCCTGGACA GATACTTCTA TAACCAGGAG GAGAACGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGATGCCG AGTACTGGAA CAGCCAGAAG GACCTCCTGG AGGACAGGCG
 GGGCCAGGTG GACACCTAC*   
>DL;IPD:MHC04395
IPD:MHC04395 Papa-DRB1*03:02 219 bases
 CGTTTCTTGG AGTACTCTAC GTCTGAGTGT CATTTCTTCA ATGGGACGGA
 GCGGGTGCGG TTCCTGGACA GATACTTCTA TAACCAGGAG GAGAACGTGC
 GCTTCGACAG CAACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGATGCCG AGTACTGGAA CAGCCAGAAG GACCTCCTGG AGGACAGGCG
 GGGCCAGGTG GACACCTAC*   
>DL;IPD:MHC00697
IPD:MHC00697 Papa-DRB6*01:01 219 bases
 CGTTTCTTGG AGAAGGCTAA GTGTGAGTGT CATATCTTCA ATGGGACGAA
 GCGGGTGCAG TACCTGAACA GATACATCCA TAAACGGGAA GAGAACCTGC
 GCTTCGACAG CGACGTGGAG GAGTTCCAGG CAGTGACAGA ACTGGGGCGG
 CCTGTCGCAG AGAACTGGAA CAGCCAGAAG GGAATCCTGG AGGAGAAGCG
 GGACAAGGTG GACATACAC*   
>DL;IPD:MHC00698
IPD:MHC00698 Papa-DRB6*01:02 203 bases
 CACGTTTCTT GGAGAAGGCT AAGTGTGAGT GTCATATCTT CAATGGGACG
 AAGCGGGTGC AGTACCTGAA CAGATACATC CATAAACGGG AAGAGAACCT
 GCGCTTCGAC AGCGACGTGG AGGAGTTCCA GGCGGTGACA GAACTGGGGC
 GGCCTGTCGC AGAGAACTGG AACAGCCAGA AGGGAATCCT GGAGGAGAAG
 CGG*    
