>DL;IPD:MHC00689
IPD:MHC00689 Papa-DMB*01 269 bases
 GTGGCTTCGT GGCCCACGTG GAAAGCTCCT GTCTGTTGGA TGATGCTGGG
 ACTCCAAAGG ATTTCACATA CTGCATCTCC TTCAACAAGG ATCTGCTGAC
 CTGCTGGGAT CCAGAGGAGA ATAAGATGGC CCCTTGCGAA TTTGGGGTGC
 TGAATAGCTT GGCGAATTTC CTCTCACAGC ACCTCAACCA ACAAGACACC
 CTGATGCAGC GCTTGCGCAA TGGGCTTCAG AATTGTGCCA CACACACCCA
 GCCCTTCTGG GGATCACTG*   
>DL;IPD:MHC00690
IPD:MHC00690 Papa-DMB*02 269 bases
 GTGGCTTCGT GGCCCACGTG GAAAGCTCCT GTCTGTTGGA TGATGCTGGG
 ACTCCAAAGG ATTTCACATA CTGCATCTCC TTCAACAAGG ATCTGCTGAC
 CTGCTGGGAT CCAGAGGAGA ATAAGATGGC CCCTTGCGAA TTTGGGGTGC
 TGAATAGCTT GGCGAATTTC CTCTCACAGC ACCTCAACCA ACAAGACACC
 CTGATGCAGC GCTTGCGCAA TGGGCTTCAG AATTGTGCCA CACACACCCA
 GCACTTCTGG GGATCACTG*   
