>DL;IPD:MHC00689
IPD:MHC00689 Papa-DMB*01 89 bases
 GFVAHVESSC LLDDAGTPKD FTYCISFNKD LLTCWDPEEN KMAPCEFGVL
 NSLANFLSQH LNQQDTLMQR LRNGLQNCAT HTQPFWGSL* 
>DL;IPD:MHC00690
IPD:MHC00690 Papa-DMB*02 89 bases
 GFVAHVESSC LLDDAGTPKD FTYCISFNKD LLTCWDPEEN KMAPCEFGVL
 NSLANFLSQH LNQQDTLMQR LRNGLQNCAT HTQHFWGSL* 
