>DL;IPD:MHC00699
IPD:MHC00699 Papa-G*01:01 241 bases
 CGCCGTGTCC CGGCCCGGCC GCGGGGAGCC CCGCTTCATC GCCATGGGCT
 ACGTGGACGA CACGCAGTTC GTGTGGTTCG ACAGCGACTC GGCGTGTCCG
 AGGATGGAGC CGCGGGCGCC GTGGGTGGAG CAGGAGGGGC CGGAGTATTG
 GGAAGAGGAG ACACGGAACA CCAAGGCCCA CGCACAGACT GACAGAATAA
 ACCTGCAGAC CCTGCGCGGC TACTACAACC AGAGCGAGGC C*
