>DL;IPD:MHC00678
IPD:MHC00678 Papa-A*01 1098 bases
 ATGGGCGTCC TGCCGCCCCG AACTCTCCTC CTGCTACTCT CGGGGGCCCT
 GGCCCTGACC CAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCTTCA
 CCTCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGCGAGCCA
 GAGGATGGAG CCGCGGGCGC CGTGGATAGA GCAGGAGGGT CCGGAGTATT
 GGGACCAGGA GACACGGAAT GTGAAGGCCC ACTCACAGAC TGACCGAGTG
 AACCTGGGGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG ACGGTTCTCA
 CACCATCCAG ATAATGTATG GCTGCGACGT GGGGTCGGAC GGGCGCTTCC
 TCCGCGGGTA CCGGCAGGAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCTTG GACCGCGGCG GACATGGCAG CTCAGATCAC
 CAAGCGCAAG TGGGAGGCGG CCCATGCGGC GGAGCAGCGG AGAGCCTACC
 TGGAGGGCCT GTGCGTGGAC GGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCACGGA CCCCCCCAAG ACACATATGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAGACCCAG
 GACACGGAGC TCGTGGAGAC CAGGCCCGCA GGGGATGGAA CCTTCCAGAA
 GTGGGCGGCT GTGGTGGTAC CTTCTGGAGA GGAGCAGAGA TACACCTGCC
 ATGTGCAGCA TGAGGGTCTT CCCAAGCCCC TCACCCTGAG ATGGGAGCCG
 TCTTCCCAGC CCACCATCCC CATTGTGGGC ATCATTGCTG GCCTGGTTCT
 CCTTGGAGCT GTGATCACTG GAGCTGTGGT CGCTGCCGTG ATGTGGAGGA
 GGAAGAGCTC AGATAGAAAA GGAGGGAGCT ACACTCAGGC TGCAAGCAGT
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGTA AAGTGTGA*
>DL;IPD:MHC00679
IPD:MHC00679 Papa-A*02 1098 bases
 ATGGGCGTCA TGGCGCCCCG AACCCTCGTC CTGCTACTCT CGGGGGCCCT
 GGCCCTGACC CAGACCTGGG CAGGCTCCCA CTCCATGAGG TATTTCTCCA
 CATCGGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CGCCGTGGGC
 TACGTGGACA ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGCGAGCCA
 GAGGATGGAG CCGCGGGCAC CGTGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCAGGA GACCCGGAGC GTCAAGGCCG GCGCACAGAT CAACCGAGCG
 AACCTGGGGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG ACGGTTCTCA
 CACCATCCAG ATAATGTTTG GCTGCGACGT GGGGTCGGAC GGGCGCTTCC
 TCCGCGGGTA TGAGCAGTAT GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCTTG GACCGCGGCG GACATGGCGG CTCAGATTAC
 CCAGCGCAAG TGGGAGGCGG CCCATGCGGC GGAGCAGCAC AGAGCCTCCC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCACTGA CCCCCCCAAG ACACATATGA CCCACCACCC
 CATCTCCGAC CGTGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAGACCCAG
 GACACGGAGC TCGTGGAGAC CAGGCCTGCA GGGGATGGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTAC CTTCTGGAGA GGAGCAGAGA TACACCTGCC
 ATGTGCAGCA TGAGGGTCTG CTCAAGCCCC TCACCCTGAG ATGGGAGCCG
 TCTTCCCAGC CCACCATCCC CATCGTGGGC ATCATTGCTG GCCTGGTTCT
 CCTTGGAGCT GTGATCACTG GAGCTGTGGT CGCTGCCATG ATGTGGAGGA
 GGAAGAGCTC AGATAGAAAA GGAGGGAGCT ACTCTCAGGC TGCAAGCAGT
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGTA AAGTGTGA*
>DL;IPD:MHC00680
IPD:MHC00680 Papa-A*03 1074 bases
 CTCCTCCTGC TACTCTCGGG GACCCTGGCC CTGACCCAGA CCTGGGCGGG
 CTCCCACTCC ATGAGGTATT TCTTCACATC CGTGTCCCGG CCCGGCCGCG
 GGGAGCCCCG CTTCATCGCC GTGGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCCGC GAGCCAGAGG ATGGAGCCGC GGGCGCCGTG
 GATAGAGCAG GAGGGTCCGG AGTATTGGGA CCAGGAGACA CGGAGTGTGA
 AGGCCCAGGC ACAGACTGAC CGAGTGGACC TGGGGACCCT GCGCGGCTAC
 TACAACCAGA GCGAGGACGG TTCTCACACC ATCCAGATAA TGTATGGCTG
 CGACGTGGGG TCGGACGGGC GCTTCCTCCG CGGGTACCGG CAGGACGCCT
 ACGACGGCAA GGATTACATC GCCCTGAACG AGGACCTGCG CTCTTGGACC
 GCGGCGGACA TGGCGGCTCA GATCACCCAG CGCAAGTGGG AGGCGGCCCA
 TGAGGCGGAG CAGTGGAGAG CCTACCTGGA GGGCCTGTGC GTGGAGTGGC
 TCCGCAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CACGGACCCC
 CCCAAGACAC ATATGACCCA CCACCCCATC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG GGAGGACCAG ACCCAGGACA CGGAGCTCGT GGAGACCAGG
 CCCGCAGGGG ATGGAACCTT CCAGAAGTGG GCGGCTGTGG TGGTACCTTC
 TGGAGAGGAG CAGAGATACA CCTGCCATGT GCAGCATGAG GGTCTTCCCA
 AGCCCCTCAC CCTGAGATGG GAGCCGTCTT CCCAGCCCAC CATCCCCATT
 GTGGGCATCA TTGCTGGCCT GGTTCTCCTT GGAGCTGTGA TCACTGGAGC
 TGTGGTCGCT GCCGTGATGT GGAGGAGGAA GAGCTCAGAT AGAAAAGGAG
 GGAGCTACAC TCAGGCTGCA AGCAGTGACA GTGCCCAGGG CTCTGATGTG
 TCTCTCACAG CTTGTAAAGT GTGA*  
>DL;IPD:MHC00681
IPD:MHC00681 Papa-A*04 1074 bases
 CTCCTCCTGC TACTCTCGGG GGCCCTGGCC CTGACCCAGA CCTGGGCGGG
 CTCCCACTCC ATGAGGTATT TCTTCACCTC CGTGTCCCGG CCCGGCCGCG
 GGGAGCCCCG CTTCATCGCC GTGGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCCGC GAGCCAGAGG ATGGAGCCGC GGGCGCCGTG
 GATAGAGCAG GAGGGTCCGG AGTATTGGGA CCAGGAGACC CGGAGCGTCA
 AGGCCGGCGC ACAGATCTAC CGAGCGAACC TGGGGACCCT GCGCGGCTAC
 TACAACCAGA GCGAGGACGG TTCTCACACC ATCCAGTTAA TGTTTGGCTG
 CGACGTGGGG TCGGACGGGC GCTTCCTCCG CGGGTACCGG CAGGACGCCT
 ACGACGGCAA GGATTACATC GCCCTGAACG AGGACCTGCG CTCTTGGACC
 GCGGCGGACA TGGCGGCTCA GATTACCCAG CGCAAGTGGG AGGCGGCCCA
 TGCGGCGGAG CAGCACAGAG CCTCCCTGGA GGGCACGTGC GTGGAGTGGC
 TCCGCAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CACTGACCCC
 CCCAAGACAC ATATGACCCA CCACCCCATC TCCGACCGTG AGGCCACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG GGAGGACCAG ACCCAGGACA CGGAGCTCGT GGAGACCAGG
 CCTGCAGGGG ATGGAACCTT CCAGAAGTGG GCAGCTGTGG TGGTACCTTC
 TGGAGAGGAG CAGAGATACA CCTGCCATGT GCAGCATGAG GGTCTGCTCA
 AGCCCCTCAC CCTGAGATGG GAGCCGTCTT CCCAGCCCAC CATCCCCATC
 GTGGGCATCA TTGCTGGCCT GGTTCTCCTT GGAGCTGTGA TCACTGGAGC
 TGTGGTCGCT GCCATGATGT GGAGGAGGAA GAGCTCAGAT AGAAAAGGAG
 GGAGCTACTC TCAGGCTGCA AGCAGTGACA GTGCCCAGGG CTCTGATGTG
 TCTCTCACAG CTTGTAAAGT GTGA*  
>DL;IPD:MHC00682
IPD:MHC00682 Papa-A*05 1074 bases
 CTCCTCCTGC TACTCTCGGG GGCCCTGGCC CTGACCCAGA CCTGGGCGGG
 CTCCCACTCC ATGAGGTATT TCTCCACATC GGTGTCCCGG CCCGGCCGCG
 GGGAGCCCCG CTTCATCGCC GTGGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCCGC GAGCCAGAGG ATGGAGCCGC GGGCGCCGTG
 GATAGAGCAG GAGGGTCCGG AGTATTGGGA CCAGGAGACA CGGAGTGTGA
 AGGCCCACTC ACAGACTGAC CGAGTGGACC TGGGGACCCT GCGCGGCTAC
 TACAACCAGA GCGAGGACGG TTCTCACACC ATCCAGTTAA TGTATGGCTG
 CGACGTGGGG TCGGACGGGC GCTTCCTCCG CGGGTACCGG CAGGACGCCT
 ACGACGGCAA GGATTACATC GCCCTGAACG AGGACCTGCG CTCTTGGACC
 GCGGCGGACA TGGCAGCTCA GATCACCCAG CGCAAGTGGG AGGCGGCCCA
 TGAGGCGGAG CAGCTGAGAG CCTACCTGGA GGGCCGGTGC GTGGACGGGC
 TCCGCAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CACGGACCCC
 CCCAAGACAC ATATGACCCA CCACCCCATC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG GGAGGACCAG ACCCAGGACA CGGAGCTCGT GGAGACCAGG
 CCCGCAGGGG ATGGAACCTT CCAGAAGTGG GCGGCTGTGG TGGTACCTTC
 TGGAGAGGAG CAGAGATACA CCTGCCATGT GCAGCATGAG GGTCTGCCCA
 AGCCCCTCAC CCTGAGATGG GAGCCGTCTT CCCAGCCCAC CATCCCCATT
 GTGGGCATCA TTGCTGGCCT GGTTCTCCTT GGAGCTGTGA TCACTGGAGC
 TGTGGTCGCT GCCGTGATGT GGAGGAGGAA GAGCTCAGAT AGAAAAGGAG
 GGAGCTACTC TCAGGCTGCA AGCAGTGACA GTGCCCAGGG CTCTGATGTG
 TCTCTCACAG CTTGTAAAGT GTGA*  
