>DL;IPD:MHC00683
IPD:MHC00683 Papa-B*01 355 bases
 VLLLLSAALA LTETWAGSHS MRYFYTSVSR PGRGEPRFIS VGYVDDTQFV
 RFDSDAASPR EEPRAPWMEQ EGPEYWDRNT QICKAQAQTD RESLGNLRGY
 YNQSEAGSHT LQTMYGCDVG PDGRFLRGYR QFAYDGKDYI ALNEDLSSWT
 AADTAAQITQ RKWEAAHEAE QRRAYLEGLC VEWLRRYLEN GKETLQRADP
 PKTHVTHHPI SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDTELVETR
 PAGDRTFQKW AAVVVPSGQE QRYTCHVQHE GLAEPLTLRW EPSSQSTIPI
 VGIVAGLAVL AVVVTGAVVA AVMCRRKSSG GKGGSYSQAA SSDSAQGSDV
 SLTAX*    
>DL;IPD:MHC00684
IPD:MHC00684 Papa-B*02 355 bases
 VLLLLSAALA LTETWAGSHS MRYFYTSVSR PGAGEPRFIS VGYVDDTQFV
 RFDSDAASPR EEPRAPWMEQ EGPEYWDRNT QICKAQAQTD RENLRIALRY
 YNQSEAGSHT LQTMYGCDVG PDGRFLRGYR QFAYDGKDYI ALNEDLSSWT
 AADTAAQITQ RKWEAARVAE QQRAYLEGLC VEWLRRYLEN GKETLQRADP
 PKTHVTHHPI SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDTELVETR
 PAGDRTFQKW AAVVVPSGQE QRYTCHVQHE GLPEPLTLRW EPSSQSTIPI
 VGIVAGLAVL AVVVTGAVVA AVMCRRKSSG GKGGSYSQAA SSDSAQGSDV
 SLTAX*    
>DL;IPD:MHC00685
IPD:MHC00685 Papa-B*03 355 bases
 VLLLLSAALA LTETWAGSHS MRYFDTAVSR PGAGEPRFIT VGYVDDTQFV
 RFDSDAASPR EEPRAPWMEQ EGPEYWDRNT QICKAQAQTD RENLRIALRY
 YNQSEAGSHT LQRMYGCDVG PDGRLLRGYS QSAYDGKDYI ALNEDLSSWT
 AADTAAQITQ RKWEAARVAE QLRAYLEGLC VEWLRRYLEN GKETLQRADP
 PKTHVTHHPI SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDTELVETR
 PAGDRTFQKW AAVVVPSGQE QRYTCHVQHE GLPEPLTLRW EPSSQSTIPI
 VGIVAGLAVL AVVVTGAVVA AVMCRRKSSG GKGGSYSQAA SSDSAQGSDV
 SLTAX*    
>DL;IPD:MHC00686
IPD:MHC00686 Papa-B*04 355 bases
 VLLLLSAALA LTETWAGSHS MRYFYTSVSR PGRGEPRFIS VGYVDDTQFV
 RFDSDAASPR EEPRAPWMEQ EGPEYWDRNT QIYKAQAQTD RESLGNLRGY
 YNQSEAGSHT LQTMYGCDVG PDGRLLRGYE QFAYDGKDYI ALNEDLSSWT
 AADTAAQISQ RKLEAARAAE QWRAYLEGLC VEWLRRYLEN GKETLQRADP
 PKTHVTHHPI SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDTELVETR
 PAGDRTFQKW AAVVVPSGQE QRYTCHVQHE GLPEPLTLRW EPSSQSTIPI
 VGIVAGLAVL AVVVTGAVVA AVMCRRKSSG GKGGSYSQAA SSDSAQGSDV
 SLTAX*    
>DL;IPD:MHC01427
IPD:MHC01427 Papa-B*05 191 bases
 ALALTETWAG SHSMRYFYTS VSRPGRGEPR FISVGYVDDT QFVRFDSDAA
 SPREEPRAPW MEQEGPEYWD RNTQICKAQA QTDRVNLRIA LRYYNQSEAG
 SHTLQTMYGC DVGPDGRFLR GYRQFAYDGK DYIALNEDLS SWTAADTAAQ
 ITQRKWEAAR VAEQQRAYLE GLCVEWLRRY LENGKETLQR A*
>DL;IPD:MHC01428
IPD:MHC01428 Papa-B*06 191 bases
 ALALTETWAG SHSMRYFYTS VSRPGRGEPR FISVGYVDDT QFVRFDSDAA
 SPREEPRAPW MEQEGPEYWD RNTQICKAQA QTDRVSLGNL RGYYNQSEAG
 SHTLQTMYGC DVGPDGRFLR GYRQFAYDGK DYIALNEDLS SWTAADTAAQ
 ITQRKWEAAH EAEQRRAYLE GLCVEWLRRY LENGKETLQR A*
>DL;IPD:MHC01429
IPD:MHC01429 Papa-B*07 191 bases
 ALALTETWAG SHSMRYFDTA VSRPGRGEPR FITVGYVDDT QFVRFDSDAA
 SPREEPRAPW MEQEGPEYWD RNTQICKAQA QTDRENLRIA LRYYNQSEAG
 SHTLQRMYGC DVGPDGRLLR GYSQSAYDGK DYIALNEDLS SWTAADTAAQ
 ITQRKWEAAR VAEQLRAYLE GLCVEWLRRY LENGKETLQR A*
