>DL;IPD:MHC00691
IPD:MHC00691 Papa-DPB1*01 249 bases
 CTTTTCCAGG GACGGCAGGA ATGCTACGCG TTTAATGGGA CACAGCGCTT
 CCTGGAGAGA TACATCTACA ACCGGGAGGA GTTCGCGCGC TTCGACAGCG
 ACGTGGGGGA GTACCGGGCG GTGACGGAGC TGGGGCGGCC TGCTGCGGAG
 TACTGGAACA GCCAGAAGGA CCTCCTGGAG GAGAAGCGGG CAGTGCCGGA
 CAGGATGTGC AGACACAACT ACGAGCTGGA CGAGGCCGTG ACCCTGCAG*
>DL;IPD:MHC00692
IPD:MHC00692 Papa-DPB1*02 249 bases
 GTGTACCAGG GACGGCAGGA ATGCTACGCG TTTAATGGGA CACAGCGCTT
 CCTGGAGAGA TACATCTACA ACCGGGAGGA GTTCGCGCGC TTCGACAGCG
 ACGTGGGGGA GTACCGGGCG GTGACGGAGC TGGGGCGGCC TGCTGCGGAG
 TACTGGAACA GCCAGAAGGA CTTCCTGGAG GAGAAGCGGG CAGTGCCGGA
 CAGGATGTGC AGACACAACT ACGAGCTGGT CGAGGCCATA GCCCTGCAG*
>DL;IPD:MHC00693
IPD:MHC00693 Papa-DPB1*03 249 bases
 GTGTACCAGG GACGGCAGGA ATGCTACGCG TTTAATGGGA CACAGCGCTT
 CCTGGAGAGA TACATCTACA ACCGGGAGGA GTTCGCGCGC TTCGACAGCG
 ACGTGGGGGA GTACCGGGCG GTGACGGAGC TGGGGCGGCC TGCTGCGGAG
 TACTGGAACA GCCAGAAGGA CTTCCTGGAG GAGAAGCGGG CAGTGCCGGA
 CAGGATGTGC AGACACAACT ACGAGCTGGT CGAGGCCGTG ACCCTGCAG*
>DL;IPD:MHC00694
IPD:MHC00694 Papa-DPB1*04 249 bases
 CTTTTCCAGG GACGGCAGGA ATGCTACGCG TTTAATGGGA CACAGCGCTT
 CCTGGAGAGA TACATCTACA ACCGGGAGGA GTTCGCGCGC TTCGACAGCG
 ACGTGGGGGA GTTCCGGGCG GTGACGGAGC TGGGGCGGCC TGCTGCGGAG
 TACTGGAACA GCCAGAAGGA CCTCCTGGAG CAGAAGCGGG CAGTGCCGGA
 CAGGATGTGC AGACACAACT ACGAGCTGGT CGGGGCCGTG ACCTTGCAG*
>DL;IPD:MHC00695
IPD:MHC00695 Papa-DPB1*05 249 bases
 GTGTACCAGG GACGGCAGGA ATGCTACGCG TTTAATGGGA CACAGCGCTT
 CCTGGAGAGA TACATCTACA ACCGGGAGGA GTACGCGCGC TTCGACAGCG
 ACGTGGGGGA GTTCCGGGCG GTGACGGAGC TGGGGCGGCC TGCTGCGGAG
 TACTGGAACA GCCAGAAGGA CTTCCTGGAG GAGAAGCGGG CAGTGCCGGA
 CAGGATGTGC AGACACAACT ACGAGCTGGT CGAGGCCGTG ACCCTGCAG*
>DL;IPD:MHC00696
IPD:MHC00696 Papa-DPB1*06 249 bases
 CTTTTCCAGG GACGGCAGGA ATGCTACGCG TTTAATGGGA CACAGCGCTT
 CCTGGAGAGA TACATCTACA ACCGGGAGGA GTACGCGCGC TTCGACAGCG
 ACGTGGGGGA GTTCCGGGCG GTGACGGAGC TGGGGCGGCC TGCTGCGGAG
 TACTGGAACA GCCAGAAGGA CCTCCTGGAG GAGAAGCGGG CAGTGCCGGA
 CAGGATGTGC AGACACAACT ACGAGCTGGA CGAGGCCGTG ACCCTGCAG*
