>DL;IPD:MHC00687
IPD:MHC00687 Papa-C*03:01:01:01 1101 bases
 ATGCGGGTCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CGGGAGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCTACA
 CCGCCGTGTC CCGGCCCGGC CGCGGAGAGC CCCGCTTCAT CGCAGTGGGC
 TACGTGGATG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGCGAGTCC
 GAGAGGGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGGA GACACAGAAG TACAAGCGCC AGGCACAGGC TGACCGAGTG
 AACCTGCGGA AACTGCGCGG CTACTACAAC CAGAGCGAGG ACGGGTCTCA
 CACTCTCCAG AAGATGTATG GCTGCGACCT GGGGCCCGAC GGGCGCCTCC
 TCCGCGGGTA TGAGCAGTTC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCCGCG GACACGGCGG CTCAGATCAC
 CCAGCGCAAG TTGGAGGCGG CCCGTGCGGC GGAGCAGTGG AGAGCCTACC
 TGGAGGGCCT GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCAGA ACCCCCAAAG ACACACGTGA CCCACCACCC
 CCTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAGACCCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGCA GGAGATGGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGACA AGAGCAGAGA TACACGTGCC
 ATATGCAGCA CGAGGGGCTG CCAGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGC CCACCATCCC CATCATGGGC ATCGTTGCTG GCCTGGCTGT
 CCTGGTTGTC CTAGCTGTCC TTGGAGCTGT GGTCACTGCT ATGATGTGTA
 GGAGGAAGAG CTCAGGTGGA AAAGGAGGGA GCTGCTCTCA GGCTGCGTGC
 AGCAACAGTG CCCAGGGCTC TGATGAGTCT CTCATCACTT GTAAAGCCTG
 A*    
>DL;IPD:MHC00688
IPD:MHC00688 Papa-C*03:01:01:02 1101 bases
 ATGCGGGTCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CGGGAGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCTACA
 CCGCCGTGTC CCGGCCCGGC CGCGGAGAGC CCCGCTTCAT CGCAGTGGGC
 TACGTGGATG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGCGAGTCC
 GAGAGGGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGGA GACACAGAAG TACAAGCGCC AGGCACAGGC TGACCGAGTG
 AACCTGCGGA AACTGCGCGG CTACTACAAC CAGAGCGAGG ACGGGTCTCA
 CACTCTCCAG AAGATGTATG GCTGCGACCT GGGGCCCGAC GGGCGCCTCC
 TCCGCGGGTA TGAGCAGTTC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCCGCG GACACGGCGG CTCAGATCAC
 CCAGCGCAAG TTGGAGGCGG CCCGTGCGGC GGAGCAGTGG AGAGCCTACC
 TGGAGGGCCT GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCAGA ACCCCCAAAG ACACACGTGA CCCACCACCC
 CCTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAGACCCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGCA GGAGATGGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGACA AGAGCAGAGA TACACGTGCC
 ATATGCAGCA CGAGGGGCTG CCAGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGC CCACCATCCC CATCATGGGC ATCGTTGCTG GCCTGGCTGT
 CCTGGTTGTC CTAGCTGTCC TTGGAGCTGT GGTCACTGCT ATGATGTGTA
 GGAGGAAGAG CTCAGGTGGA AAAGGAGGGA GCTGCTCTCA GGCTGCGTGC
 AGCAACAGTG CCCAGGGCTC TGATGAGTCT CTCATCACTT GTAAAGCCTG
 A*    
