>DL;IPD:MHC00701
IPD:MHC00701 Papp-DQA1*01:01 188 bases
 ACTTACGGTC TCTCTGGCCA GTACACCCAT GAATTTGATG GAGACGAGCA
 GTTCTACGTG GACCTGGAGA GGAAGGAGAC GGCCTGGCGA TGGCCTGAAT
 TAAGCAAATT TGGAGGTTTT GACCCGCAGG GTGCACTGAG AAACTTGGCT
 GTGTTAAAAC ACAACTTGAA CATCGTGACT AAACGCTA* 
>DL;IPD:MHC00702
IPD:MHC00702 Papp-DQA1*01:02 188 bases
 TCTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGACG GAGACGAGCA
 GTTCTACGTG GACCTGGGGA GGAAGGAGAC GGCCTGGCGA TGGCCTGAGT
 TAAGCAAATT TGGAGGTTTT GACCCGCAGG GTGCACTGAG AAACTTGGCT
 ACAGCAAAAT ACAACTTGAA CATCATGACT AAACGCTA* 
>DL;IPD:MHC00703
IPD:MHC00703 Papp-DQA1*05:01 185 bases
 TCTTACGGTT TCTCTGGCCA GTACTCCCAT GAATTTGACG GAGATGAGCA
 GTTCTACGTG GACCTGGAGA GGAAGGAGAC TGTCTGGCGG TTGCCTGTTC
 TCAGCCAATT TAGTTTCGAC GCGCAATTTG CACTGACAAA CATTGCTGTG
 GGAAAACAGA ACTTGAACTA CCTGATGAAA CAGTC* 
>DL;IPD:MHC00704
IPD:MHC00704 Papp-DQA1*24:01 188 bases
 TCTTATGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGACGAGGA
 GTTCTATGTG GACCTGGAGA GGAAGGAGAC CGTCTGGCAG TTGCCTCTGT
 TCAGCAAATT TAGAAGTTTT GACCCGCAGG GTGCACTGAG AAACTTGGCT
 GTGGGAAAAC ACAACTTGAA CATCCTGATT AAACGCTC* 
