>DL;IPD:MHC00731
IPD:MHC00731 Patr-B*01:01 1092 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCTACA
 CCTCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ACACCCAGTT CGTGAGGTTC GACAGCGACG CCGCGAGTCC
 GAGGATGGAG CCCCGGGCGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGGA GACACGGAAT ATGAAGGCCT CCGCACAGAC TGACCGAGAG
 AACCTGCGGA TCGCGCTCCG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCTGGCAG ACGATGTATG GCTGCGACAT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TGGCCAGTAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACCGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGAGGC GGAGCAGCGG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGCGAGGA CCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGAA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGAAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATTGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTTGTGGTC ACCGTAGCTG TGGTCGCTGT GGTCGCTGCT GTGATGTGTA
 GGAGGAAGAG CTCAGGTGGA AAAGGAGGGA GCTACTCTCA GGCTGCATCC
 AGCGACAGTG CCCAGGGCTC TGATGTGTCT CTCACAGCTT GA*
>DL;IPD:MHC02972
IPD:MHC02972 Patr-B*01:02 546 bases
 GCTCCCACTC CATGAGGTAT TTCTACACCT CCGTGTCCCG GCCCGGCCGC
 GGGGAGCCCC GCTTCATCAC CGTGGGCTAC GTGGACGACA CCCAGTTCGT
 GAGGTTCGAC AGCGACGCCG CGAGTCCGAG GATGGAGCCC CGGGCGCCAT
 GGATAGAGCA GGAGGGGTCA GAGTATTGGG ACCGGGAGAC ACGGAATATG
 AAGGCCTCCG CACAGACTGA CCGAGAGAAC CTGCGGATCG CGCTCCGCTA
 CTACAACCAG AGCGAGGCCG GTGCTCACAC CTGGCAGACG ATGTATGGCT
 GCGACATGGG GCCGGACGGG CGCCTCCTCC GCGGGTATGG CCAGTACGCC
 TACGACGGCA AGGATTACAT CGCCCTGAAC GAGGACCTGA GCTCCTGGAC
 CGCGGCGGAC ACCGCGGCTC AGATCACCCA GCGCAAGTGG GAGGCGGCCC
 GTGAGGCGGA GCAGCGGAGA GCCTACCTGG AGGGCACGTG CGTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGG*
>DL;IPD:MHC00732
IPD:MHC00732 Patr-B*02:01 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAAG TATTTCTACA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CTCAGTGGGC
 TACGTGGACG ACACGCAGTT CGTGTGGTTC GACAGCGACG CCGCGAGTCC
 GAGAGAGGAG CCGCGGGCGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGAGA GACACAGATC TCCAAGACCA ACGCACAGAC TTACCGAGAG
 AGCCTGCGGA ACCTGCGCGG CTACTACAAC CAGAGCGAGG CCGGTTCTCA
 CATCATCCAG AGGATGTACG GCTGCGACAT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TGAGCAGTAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACCGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTTGGGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACATGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTT GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGCGAGGA CCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGACCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACATGCC
 ATGTACAGCA TGAGGGGCTG CCGAAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCATCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC01430
IPD:MHC01430 Patr-B*02:03 575 bases
 GGCCCTGGCC CTGACCGAGA CCTGGGCCGG CTCCCACTCC ATGAGGTATT
 TCTACACCGC CGTGTCCCGG CCCGGCCGCG GGGAGCCCCG CTTCATCTCA
 GTGGGCTACG TGGACGACAC GCAGTTCGTG TGGTTCGACA GCGACGCCGC
 GAGTCCGAGA GAGGAGCCGC GGGCGCCATG GATAGAGCAG GAGGGGCCGG
 AGTATTGGGA CCGAGAGACA CAGATCTCCA AGACCAACGC ACAGACTTAC
 CGAGAGAGCC TGCGGAACCT GCGCGGCTAC TACAACCAGA GCGAGGCCGG
 TTCTCACATC ATCCAGAGGA TGTACGGCTG CGACATGGGG CCGGACGGGC
 GCCTCCTCCG CGGGTATGAG CAGTACGCCT ACGACGGCAA GGATTACATC
 GCCCTGAACC AGGACCTGAG CTCCTGGACC GCGGCGGACA CCGCGGCTCA
 GATCACCCAG CGCAAGTGGG AGGCGGCCCG TTGGGCGGAG CAGCTGAGAG
 CCTACCTGGA GGGCACGTGC GTGGAGTGGC TCCGCAGATA CCTGGAGAAC
 GGGAAGGAGA CGCTGCAGCG CGCGG*  
>DL;IPD:MHC00733
IPD:MHC00733 Patr-B*03:01 1092 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCGACA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ACACCCAGTT CGTGAGGTTC GACAGCGACG CCGCGAGTCC
 GAGGATGGAG CCCCGGGCGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGGA GACACGGAAC GTGAAGGCCT CCGCACAGAC TGACCGAGAG
 AACCTGCGGA TCGCGCTCCG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCTGGCAG ACGATGTTTG GCTGCGACAT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGTAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGCGGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACATGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGCGAGGA CCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGAA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGAAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATTGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTTGTGGTC ACCGTAGCTG TGGTCGCTGT GGTCGCTGCT GTGTTGTGTA
 GGAGGAAGAG CTCAGGTGGA AAAGGAGGGA GCTACTCTCA GGCTGCATCC
 AGCGACAGTG CCCAGGGCTC TGATGTGTCT CTCACAGCTT GA*
>DL;IPD:MHC00734
IPD:MHC00734 Patr-B*03:02 1092 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCGACA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ACACCCAGTT CGTGAGGTTC GACAGCGACG CCGCGAGTCC
 GAGGATGGAG CCCCGGGCGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGGA GACACGGAAC GTGAAGGCCT CCGCACAGAC TGACCGAGAG
 AACCTGCGGA TCGCGCTCCG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCTGGCAG ACGATGTTTG GCTGCGACAT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGTAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGCGGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGCGAGGA CCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGAA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGAAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATTGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTTGTGGTC ACCGTAGCTG TGGTCGCTGT GGTCGCTGCT GTGTTGTGTA
 GGAGGAAGAG CTCAGGTGGA AAAGGAGGGA GCTACTCTCA GGCTGCATCC
 AGCGACAGTG CCCAGGGCTC TGATGTGTCT CTCACAGCTT GA*
>DL;IPD:MHC00735
IPD:MHC00735 Patr-B*04:01 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAAG TATTTCTACA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGTGGTTC GACAGCGACG CCGCGAGTCC
 GAGGAAGGAG CCGCGGACGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGAGA GACACAGATC TCCAAGACCA ACGCACAGAC TTACCGAGTG
 GGCCTGCGGA ACCTGCTCCG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCTGGCAG ACGATGTTTG GCTGCGACGT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA CCGGCAGTAT GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACCAGGACC TGAGCTCCTG GACCGCGGCG GACACCGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGTGGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACATGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTT GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGCGAGGA CCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGACCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACATGCC
 ATGTACAGCA TGAGGGGCTG CCGAAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCATCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC02056
IPD:MHC02056 Patr-B*04:02 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAAG TATTTCTACA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGTGGTTC GACAGCGACG CCGCGAGTCC
 GAGGAAGGAG CCGCGGACGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGAGA GACACAGATC TCCAAGACCA ACGCACAGAC TTACCGAGTG
 GGCCTGCGGA ACCTGCGCGG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCTGGCAG ACGATGTTTG GCTGCGACGT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA CCGGCAGTAT GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACCAGGACC TGAGCTCCTG GACCGCGGCG GACACCGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGTGGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACATGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTT GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGCGAGGA CCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGACCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACATGCC
 ATGTACAGCA TGAGGGGCTG CCGAAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCATCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00736
IPD:MHC00736 Patr-B*05:01 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAAG TATTTCTACA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CTCAGTGGGC
 TACGTGGACG ACACGCAGTT CGTGTGGTTC GACAGCGACG CCGCGAGTCC
 GAGAGAGGAG CCGCGGGCGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGAGA GACACAGATC TCCAAGACCA ACGCACAGAC TTACCGAGAG
 AGCCTGCGGA ACCTGCGCGG CTACTACAAC CAGAGCGAGG CCGGTTCTCA
 CATCATCCAG AGGATGTACG GCTGCGACAT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TGAGCAGTAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACCAGGACC TGAGCTCCTG GACCGCGGCG GACACCGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTTGGGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACATGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTT GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGCGAGGA CCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGACCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACATGCC
 ATGTACAGCA TGAGGGGCTG CCGAAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCATCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00737
IPD:MHC00737 Patr-B*05:02 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAAG TATTTCTACA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CTCAGTGGGC
 TACGTGGACG ACACGCAGTT CGTGTGGTTC GACAGCGACG CCGCGAGTCC
 GAGAGAGGAG CCGCGGGCGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGAGA GACACAGATC TCCAAGACCA ACGCACAGAC TTACCGAGAG
 AGCCTGCGGA ACCTGCGCGG CTACTACAAC CAGAGCGAGG CCGGTTCTCA
 CATCATCCAG AGGATGTACG GCTGCGACAT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TGAGCAGTAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACCAGGACC TGAGCTCCTG GACCGCGGCG GACACCGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTAGGGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACATGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTT GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGCGAGGA CCAAACTCAG
 GACACGGAGC TTGTGGAGAC CAGACCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACATGCC
 ATGTACAGCA TGAGGGGCTG CCGAAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCATCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00738
IPD:MHC00738 Patr-B*06:01 1065 bases
 GTCCTCCTGC TGCTCTCGGC GGCCCTGGCC CTGACCGAGA CCTGGGCCGG
 CTCCCACTCC ATGAGGTATT TCTACACCGC CGTGTCCCGG CCCGGCCGCG
 GGGAGCCCCG CTTCATCTCA GTGGGCTACG TGGACGACAC CCAGTTCGTG
 AGGTTCGACA GCGACGCCGC GAGTCCGAGG ATGGAGCCCC GGGCGCCATG
 GATAGAGCAG GAGGGGCCGG AGTATTGGGA CCGGGAGACA CGGAACGTGA
 AGGCCTCCGC ACAGACTGAC CGAGGGAGCC TGGCGAACCT GCGCGGCTAC
 TACAACCAGA GCGAGGCCGG GTCTCACACC TGGCAGACGA TGTATGGCTG
 CGACGTGGGG CCGGACGGGC GCCTCCTCCG CGGGTATGAC CAGTACGCCT
 ACGACGGCAA GGATTACATC GCCCTGAACG AGGACCTGAG CTCCTGGACC
 GCGGCGGACA CGGCGGCTCA GATCACCCAG CGCAAGTGGG AGGCGGCCCG
 TGTGGCGGAG CAGTGGAGAG CCTACCTGGA GGGCCTGTGC GTGGAGTGGC
 TCCGCAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CGCGGACCCC
 CCAAAGACAC ACGTGACCCA CCACCCCATC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG GGAGGACCAA ACTCAGGACA CTGAGCTTGT GGAGACCAGG
 CCAGCAGGAG ATAGAACCTT CCAGAAGTGG GCAGCTGTGG TGGTGCCTTC
 TGGACAAGAG CAGAGATACA CATGCCATGT GCAGCATGAG GGGCTGCTGG
 AGCCCCTCAC CCTGAGATGG GAGCCATCTT CCCAGTCCAC CATCCCCATC
 GTGGGCATTG TTGCTGGCCT GGCTGTCCTA GCAGTTGTGG TCACCGGAGC
 TGTGGTCGCT GCTGTGATGT GTAGGAGGAA GAGCTCAGGT GGAAAAGGAG
 GGAGCTACTC CCAGGCTGCG TCCAGCGACA GTGCCCAGGG CTCTGATGTG
 TCTCTCACAG CTTGA*   
>DL;IPD:MHC04211
IPD:MHC04211 Patr-B*06:02 546 bases
 GCTCCCACTC CATGAGGTAT TTCGACACCG CCGTGTCCCG GCCCGGCCGC
 GGGGAGCCCC GCTTCATCTC AGTGGGCTAC GTGGACGACA CCCAGTTCGT
 GAGGTTCGAC AGCGACGCCG CGAGTCCGAG GATGGAGCCC CGGGCGCCAT
 GGATAGAGCA GGAGGGGCCG GAGTATTGGG ACCGGGAGAC ACGGAACGTG
 AAGGCCTCCG CACAGACTGA CCGAGTGGGC CTGCGGAACC TGCGCGGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC CTGGCAGACG ATGTATGGCT
 GCGACGTGGG GCCGGACGGG CGCCTCCTCC GCGGGTATTA CCAGTACGCC
 TACGACGGCA AGGATTACAT CGCCCTGAAC GAGGACCTGA GCTCCTGGAC
 CGCGGCGGAC ACGGCGGCTC AGATCACCCA GCGCAAGTTG GAGGCGGCCC
 GTGCGGCGGA GCAGCTGAGA GCCTACCTGG AGGGCCTGTG CGTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGG*
>DL;IPD:MHC00739
IPD:MHC00739 Patr-B*07:01 1065 bases
 GTCCTCCTGC TGCTCTCGGC GGCCCTGGCC CTGACCGAGA CCTGGGCCGG
 CTCCCACTCC ATGAAGTATT TCTTAACATC CGTGTCCCGG CCCGGCCGCG
 GGGAGCCCCG CTTCATCACC GTGGGCTACG TGGACGACAC CCAGTTCGTG
 AGGTTCGACA GCGACGCCGC GAGTCCGAGG ATGGAGCCCC GGGCGCCATG
 GATAGAGCAG GAGGGGCCGG AGTATTGGGA CCGGGAGACA CGGAACGTGA
 AGGCCTCCGC ACAGACTTAC CGAGAGAACC TGCGGATCGC GCTCCGCTAT
 TACTTCCAGA GCGAGGACGG GTCTCACACT CTCCAGACGA TGTATGGCTG
 CGACGTGGGG CCGGACGGGC GCTTCCTCCG CGGGTACCGG CAGTTCGCCT
 ACGACGGCAA GGATTACATC GCCCTGAACG AGGACCTGAG CTCCTGGACC
 GCGGCGGACA CGGCGGCTCA GATCACCCAG CGCAAGTGGG AGGCGGCCCG
 TGTGGCGGAG CAGCACAGAG CCTACCTGGA GGGCCTGTGC GTGGAGTGGC
 TCCGCAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CGCGGACCCC
 CCAAAGACAC ACGTGACCCA CCACCCCATC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG GGAGGACCAA ACTCAGGACA CTGAGCTTGT GGAGACCAGG
 CCAGCAGGAG ATAGAACCTT CCAGAAGTGG GCAGCTGTGG TGGTGCCTTC
 TGGACAAGAG CAGAGATACA CATGCCATGT GCAGCATGAG GGGCTGCCGG
 AGCCCCTCAC CCTGAGATGG GAGCCATCTT CCCAGTCCAC CATCCCCATC
 GTGGGCATTG TTGCTGGCCT GGCTGTCCTA GCAGTTGTGG TCACCGGAGC
 TGTGGTCGCT GCTGTGATGT GTAGGAGGAA GAGCTCAGGT GGAAAAGGAG
 GGAGCTACTC CCAGGCTGCG TCCAGCGACA GTGCCCAGGG CTCTGATGTG
 TCTCTCACAG CTTGA*   
>DL;IPD:MHC01101
IPD:MHC01101 Patr-B*07:02 546 bases
 GCTCCCACTC CATGAAGTAT TTCTTAACAT CCGTGTCCCG GCCCGGCCGC
 GGGGAGCCCC GCTTCATCAC CGTGGGCTAC GTGGACGACA CCCAGTTCGT
 GAGGTTCGAC AGCGACGCCG CGAGTCCGAG GATGGAGCCC CGGGCGCCAT
 GGATAGAGCA GGAGGGGCCG GAGTATTGGG ACCGGGAGAC ACGGAACGTG
 AAGGCCTTCG CACAGACTTA CCGAGAGAAC CTGCGGATCG CGCTCCGCTA
 TTACAACCAG AGCGAGGACG GGTCTCACAC CATCCAGACG ATGTTTGGCT
 GCGACGTGGG GCCGGACGGG CGCCTCCTCC GCGGGTACCG GCAGTACGCC
 TACGACGGCA AGGATTACAT CGCCCTGAAC GAGGACCTGA GCTCCTGGAC
 CGCGGCGGAC ACGGCGGCTC AGATCACCCA GCGCAAGTGG GAGGCGGCCC
 GTGTGGCGGA GCAGCACAGA GCCTACCTGG AGGGCCTGTG CGTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGG*
>DL;IPD:MHC00740
IPD:MHC00740 Patr-B*08:01 1065 bases
 CTCCTCCTGC TGCTCTGGGG GGCAGTGGCC CTGACCGAGA CCTGGGCCGG
 CTCCCACTCC ATGAGGTATT TCTACACCGC CATGTCCCGG CCCGGCGGCG
 GGGAGCCCCG CTTCATCGCA GTAGGCTATG TGGACGACAC CCAGTTCGTG
 AGGTTCGACA GCGACGCCGC GATTCCGAGG ATGGAGCCGC GGGCGCCATG
 GATAGAGCAG GAGGGGCCGG AGTATTGGGA CCGAGAGACA CAGATCTCCA
 AGACCAACGC ACAGACTTAC CGAGTGGGCC TGCGGAACCT GCGCGGCTAC
 TACAACCAGA GCGAGGCCGG GTCTCACACC TGGCAGACGA TGTATGGCTG
 CGACGTGGGG CCGGACGGGC GCCTCCTCCG CGGGTACCGG CAGTTCGCCT
 ACGACGGCAA GGATTACATC GCCCTGAACA AGGACCTGAG CTCCTGGACC
 GCGGCGGACA CCGCGGCTCA GATCACCCAG CGCAAGTGGG AGGCGGCCCG
 TTGGGCGGAG CAGCTGAGAG CCTACCTGGA GGGCACGTGC GTGGAGTGGC
 TCCGCAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CGCGGACCCC
 CCAAAGACAC ATGTGACCCA CCACCCCATC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTTGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG CGAGGACCAA ACTCAGGACA CGGAGCTTGT GGAGACCAGA
 CCAGCAGGAG ATAGAACCTT CCAGAAGTGG GCAGCTGTGG TGGTGCCTTC
 TGGAGAAGAG CAGAGATACA CATGCCATGT ACAGCATGAG GGGCTGCCGA
 AGCCCCTCAC CCTGAGATGG GAGCCATCTT CCCAGTCCAC CATCCCCATC
 GTGGGCATTG TTGCTGGCCT GGCTGTCCTA GCAGTTGTGG TCATCGGAGC
 TGTGGTCGCT GCTGTGATGT GTAGGAGGAA GAGCTCAGGT GGAAAAGGAG
 GGAGCTACTC TCAGGCTGCG TCCAGCGACA GTGCCCAGGG CTCTGATGTG
 TCTCTCACAG CTTGA*   
>DL;IPD:MHC00741
IPD:MHC00741 Patr-B*08:02 1065 bases
 CTCCTCCTGC TGCTCTGGGG GGCAGTGGCC CTGACCGAGA CCTGGGCCGG
 CTCCCACTCC ATGAGGTATT TCTACACCGC CATGTCCCGG CCCGGCCGCG
 GGGAGCCCCG CTTCATCGCA GTAGGCTATG TGGACGACAC CCAGTTCGTG
 AGGTTCGACA GCGACGCCGC GATTCCGAGG ATGGAGCCGC GGGCGCCATG
 GATAGAGCAG GAGGGGCCGG AGTATTGGGA CCGAGAGACA CAGATCTCCA
 AGACCAACGC ACAGACTTAC CGAGTGGGCC TGCGGAACCT GCGCGGCTAC
 TACAACCAGA GCGAGGCCGG GTCTCACACC TGGCAGACGA TGTATGGCTG
 CGACGTGGGG CCGGACGGGC GCCTCCTCCG CGGGTACCGG CAGTTCGCCT
 ACGACGGCAA GGATTACATC GCCCTGAACA AGGACCTGAG CTCCTGGACC
 GCGGCGGACA CCGCGGCTCA GATCACCCAG CGCAAGTGGG AGGCGGCCCG
 TTGGGCGGAG CAGCTGAGAG CCTACCTGGA GGGCACGTGC GTGGAGTGGC
 TCCGCAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CGCGGACCCC
 CCAAAGACAC ATGTGACCCA CCACCCCATC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTTGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG CGAGGACCAA ACTCAGGACA CCGAGCTTGT GGAGACCAGA
 CCAGCAGGAG ATAGAACCTT CCAGAAGTGG GCAGCTGTGG TGGTGCCTTC
 TGGAGAAGAG CAGAGATACA CATGCCATGT ACAGCATGAG GGGCTGCCGA
 AGCCCCTCAC CCTGAGATGG GAGCCATCTT CCCAGTCCAC CATCCCCATC
 GTGGGCATTG TTGCTGGCCT GGCTGTCCTA GCAGTTGTGG TCATCGGAGC
 TGTGGTCGCT GCTGTGATGT GTAGGAGGAA GAGCTCAGGT GGAAAAGGAG
 GGAGCTACTC TCAGGCTGCG TCCAGCGACA GTGCCCAGGG CTCTGATGTG
 TCTCTCACAG CTTGA*   
>DL;IPD:MHC00742
IPD:MHC00742 Patr-B*09:01 1068 bases
 GTCCTCCTGC TGCTCTCGGC GGCCCTGGCC CTGACCGAGA CCTGGGCCGG
 CTCCCACTCC ATGAGGTATT TCTACACCTC CGTGTCCCGG CCCGGCCGCG
 GGGAGCCCCG CTTCATCACC GTGGGCTACG TGGACGACAC CCAGTTCGTG
 AGGTTCGACA GCGACGCCGC GAGTCCGAGG ATGGAGCCCC GGGCGCCATG
 GATAGAGCAG GAGGGGCCGG AGTATTGGGA CCGGGAGACA CGGAATATGA
 AGGCCTCCGC ACAGACTGAC CGAGAGAACC TGCGGATCGC GCTCCGCTAC
 TACAACCAGA GCGAGGCCGG TTCTCACATC ATCCAGAGGA TGTACGGCTG
 CGACATGGGG CCGGACGGGC GCCTCCTCCG CGGGTATTAC CAGTACGCCT
 ACGACGGCAA GGATTACATC GCCCTGAACG AGGACCTGAG CTCCTGGACC
 GCGGCGGACA CGGCGGCTCA GATCACCCAG CGCAAGTGGG AGGCGGCCCG
 TGCGGCGGAG CAGCGGAGAG CCTACCTGGA GGGCACGTGC GTGGAGTGGC
 TCCGCAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CGCGGACCCC
 CCAAAGACAC ACGTGACCCA CCACCCCATC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG CGAGGACCAA ACTCAGGACA CCGAGCTTGT GGAGACCAGG
 CCAGAAGGAG ATAGAACCTT CCAGAAGTGG GCAGCTGTGG TGGTGCCTTC
 TGGAGAAGAG CAGAGATACA CATGCCATGT GCAGCATGAG GGGCTGCCGA
 AGCCCCTCAC CCTGAGATGG GAGCCATCTT CCCAGTCCAC CATCCCCATT
 GTGGGCATTG TTGCTGGCCT GGCTGTCCTT GTGGTCACCG TAGCTGTGGT
 CGCTGTGGTC GCTGCTGTGT TGTGTAGGAG GAAGAGCTCA GGTGGAAAAG
 GAGGGAGCTA CTCTCAGGCT GCATCCAGCG ACAGTGCCCA GGGCTCTGAT
 GTGTCTCTCA CAGCTTGA*   
>DL;IPD:MHC00743
IPD:MHC00743 Patr-B*10:01 1092 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCTACA
 CCTCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ACACCCAGTT CGTGAGGTTC GACAGCGACG CCGCGAGTCC
 GAGGATGGAG CCCCGGGCGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGGA GACACGGAAT ATGAAGGCCT CCGCACAGAC TGACCGAGAG
 AACCTGCGGA TCGCGCTCCG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCTGGCAG ACGATGTATG GCTGCGACAT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TGGCCAGTAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACCGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGAGGC GGAGCAGCGG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTAC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGCGAGGA CCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGAA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGAAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATTGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTTGTGGTC ACCGTAGCTG TGGTCGCTGT GGTCGCTGCT GTGATGTGTA
 GGAGGAAGAG CTCAGGTGGA AAAGGAGGGA GCTACTCTCA GGCTGCATCC
 AGCGACAGTG CCCAGGGCTC TGATGTGTCT CTCACAGCTT GA*
>DL;IPD:MHC00744
IPD:MHC00744 Patr-B*11:01 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCTACA
 CCTCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CTCAGTGGGC
 TACGTGGACG ACACGCAGTT CGTGAGGTTC GACAGCGACG CCGCGAGTCC
 GAGAGAGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCTGAGTATT
 GGGACCGGAA CACACAGATC TACAAGGCCC AGGCACAGAC TGACCGAGTG
 GGCCTGGGGA ACCTGCGCGG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCTGGCAG ACGATGTATG GCTGCGACGT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TGACCAGTAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGAGGC GGAGCAGCGG AGAGCCTACC
 TGGAGGGCCT GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACTGAGC TTGTGGAGAC CAGGCCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGACA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGAAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATTGTGGGC ATCGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCCCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00745
IPD:MHC00745 Patr-B*11:02 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCTACA
 CCTCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CTCAGTGGGC
 TACGTGGACG ACACGCAGTT CGTGAGGTTC GACAGCGACG CCGCGAGTCC
 GAGAGAGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCTGAGTATT
 GGGACCGGAA CACACAGATC TACAAGGCCC AGGCACAGAC TGACCGAGTG
 GGCCTGGGGA ACCTGCGCGG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCTGGCAG ACGATGTATG GCTGCGACGT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TGACCAGTAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGTGGC GGAGCAGTGG AGAGCCTACC
 TGGAGGGCCT GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACTGAGC TTGTGGAGAC CAGGCCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGACA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCCCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00746
IPD:MHC00746 Patr-B*12:01 444 bases
 GGTTCGACAG CGACGCCGCG AGTCCGAGAG AGGAGCCGCG GGCGCCGTGG
 ATGGAGCAGG AGGGGCCTGA GTATTGGGAC CGGAACACAC AGATCTACAA
 GGCCCAGGCA CAGACTGACC GAGGGAGCCT GGGGAACCTG CGCGGCTACT
 ACAACCAGAG CGAGGCCGGG TCTCACACCC TCCAGAGGAT GTATGGCTGC
 GACGTGGGGC CGGACGGGCG CCTCCTCCGC GGGTATTACC AGGACGCCTA
 CGACGGCAAG GATTACATCG CCCTGAACGA GGACCTGAGC TCCTGGACCG
 CGGCGGACAC GGCGGCTCAG ATCACCCAGC GCAAGTGGGA GGCGGCCCGT
 GTGGCGGAGC AGCACAGAGC CTACCTGGAG GGCCTGTGCG TGGAGTGGCT
 CCGCAGATAC CTGGAGAACG GGAAGGAGAC GCTGCAGCGC GCGG*
>DL;IPD:MHC00747
IPD:MHC00747 Patr-B*12:02 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCTACA
 CCTCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CTCAGTGGGC
 TACGTGGACG ACACGCAGTT CGTGAGGTTC GACAGCGACG CCGCGAGTCC
 GAGAGAGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCTGAGTATT
 GGGACCGGAA CACACAGATC TGCAAGGCCC AGGCACAGAC TGACCGAGGG
 AGCCTGGGGA ACCTGCGCGG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCCTCCAG AGGATGTATG GCTGCGACGT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGGAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGTGGC GGAGCAGCAC AGAGCCTACC
 TGGAGGGCCT GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACTGAGC TTGTGGAGAC CAGGCCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGACA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCCCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00748
IPD:MHC00748 Patr-B*13:01 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCTACA
 CCTCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CTCAGTGGGC
 TACGTGGACG ACACGCAGTT CGTGAGGTTC GACAGCGACG CCGCGAGTCC
 GAGAGAGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCTGAGTATT
 GGGACCGGAA CACACAGATC TACAAGGCCC AGGCACAGAC TGACCGAGTG
 AGCCTGGGGA ACCTGCGCGG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACTCTCCAG TCGATGTATG GCTGCGACGT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TGAGCAGTAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACCAGGACC TGAGCTCCTG GACCGCGGCG GACACCGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGTGGC GGAGCAGCGG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACATGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTT GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGCGAGGA CCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGACCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACATGCC
 ATGTACAGCA TGAGGGGCTG CCGAAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCATCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00749
IPD:MHC00749 Patr-B*14:01 1089 bases
 ATGCGGGTCA CGGCGCCCCG AACCCTCCTC CTGCTGCTCT GGGGGGCAGT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA ATCCATGAGG TATTTCTACA
 CCGCCATGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CGCAGTAGGC
 TATGTGGACG ACACCCAGTT CGTGAGGTTC GACAGCGACG CCGCGATTCC
 GAGGATGGAG CCGCGGGCGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGAA CACACAGGGC ATCAAGACGC AGGCACAGAC TGACCGAGAG
 AACCTGCGGA CCCTGCTCCG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACTCTCCAG TCGATGTATG GCTGCGACAT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TGACCAGTAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACAAGGACC TGAGCTCCTG GACCGCGGCG GACACCGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGTGGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACATGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTT GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGCGAGGA CCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGACCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACATGCC
 ATGTACAGCA TGAGGGGCTG CCGAAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCATCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00750
IPD:MHC00750 Patr-B*15:01 444 bases
 GGTTCGACAG CGACGCCGCG AGTCCGAGAG AGGAGCCGCG GGCGCCATGG
 ATAGAGCAGG AGGGGCCGGA GTATTGGGAC CGAGAGACAC AGATCTCCAA
 GACCAACGCA CAGACTTACC GAGAGAGCCT GCGAACCCTG CGCGGCTACT
 ACAACCAGAG CGAGGCCGGT TCTCACATCA TCCAGAGGAT GTACGGCTGC
 GACATGGGGC CGGACGGGCG CCTCCTCCGC GGGTATGAGC AGTACGCCTA
 CGACGGCAAG GATTACATCG CCCTGAACCA GGACCTGAGC TCCTGGACCG
 CGGCGGACAC CGCGGCTCAG ATCACCCAGC GCAAGTGGGA GGCGGCCCGT
 TGGGCGGAGC AGCTGAGAGC CTACCTGGAG GGCACGTGCG TGGAGTGGCT
 CCGCAGATAC CTGGAGAACG GGAAGGAGAC GCTGCAGCGC GCGG*
>DL;IPD:MHC00751
IPD:MHC00751 Patr-B*16:01:01 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAAG TATTTCTACA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGTGGTTC GACAGCGACG CCGCGAGTCC
 GAGGAAGGAG CCGCGGACGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGAGA GACACAGATC TCCAAGACCA ACGCACAGAC TGACCGAGTG
 AGCCTGCGGA ACCTGCTCCG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCTGGCAG ACGATGTTTG GCTGCGACGT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA CCGGCAGTAT GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACCAGGACC TGAGCTCCTG GACCGCGGCG GACACCGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGTGGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACATGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTT GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGCGAGGA CCAAACTCAG
 GACACGGAGC TTGTGGAGAC CAGACCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACATGCC
 ATGTACAGCA TGAGGGGCTG CCGAAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCATCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00752
IPD:MHC00752 Patr-B*16:01:02 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAAG TATTTCTACA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGTGGTTC GACAGCGACG CCGCGAGTCC
 GAGGAAGGAG CCGCGGACGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGAGA GACACAGATC TCCAAGACCA ACGCACAGAC TGACCGAGTG
 AGCCTGCGGA ACCTGCTCCG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCTGGCAG ACGATGTTTG GCTGCGACGT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA CCGGCAGTAT GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACCAGGACC TGAGCTCCTG GACCGCGGCG GACACCGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGTGGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACATGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTT GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGCGAGGA CCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGACCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACATGCC
 ATGTACAGCA TGAGGGGCTG CCGAAGCCCC TCACCCTGAG ATGGGAGCCG
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCATCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00753
IPD:MHC00753 Patr-B*16:02 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAAG TATTTCTACA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGTGGTTC GACAGCGACG CCGCGAGTCC
 GAGGAAGGAG CCGCGGACGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGAGA GACACAGATC TCCAAGACCA ACGCACAGAC TGACCGAGAG
 AGCCTGCGGA ACCTGCTCCG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCTGGCAG ACGATGTTTG GCTGCGACGT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA CCGGCAGTAT GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACCAGGACC TGAGCTCCTG GACCGCGGCG GACACCGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGTGGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACATGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTT GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGCGAGGA CCAAACTCAG
 GACACGGAGC TTGTGGAGAC CAGACCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACATGCC
 ATGTACAGCA TGAGGGGCTG CCGAAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCATCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00754
IPD:MHC00754 Patr-B*17:01 1089 bases
 ATGATGGTCA TAGCCCCTCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAAG TATTTCTACA
 CCTCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CTCAGTGGGC
 TACGTGGACG ACACGCAGTT CGTGAGGTTC GACAGCGACG CCGCGAGTCC
 GAGGGTGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCTGAGTATT
 GCGACCGAGA GACACAGATC TTTAAGACCA ACACACAGAC TGACCGAGTG
 AGCCTGGGGA ACCTGGGCGG CTACTACAAC CAGAGCGAGG CGGGGTCTCA
 CACTCTCCAG ACGATGTACG GCTGCGACAT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGTAC GCCTACGATG GCAAGGATTA CCTTGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCGGCG GACACGCCGG CTCAGATATC
 CCAGCGCAAG TTCGAGGCGG CCGGTGCGGC GGAGCAGTTG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGTCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGCGAGGA CCAAACTCAG
 GACACGGAGC TTGTGGAGAC CAGGCCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCAAAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCGTCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCATCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00755
IPD:MHC00755 Patr-B*17:02 1089 bases
 ATGATGGTCA TAGCCCCTCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAAG TATTTCTACA
 CCTCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CTCAGTGGGC
 TACGTGGACG ACACGCAGTT CGTGAGGTTC GACAGCGACG CCGCGAGTCC
 GAGGGTGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCTGAGTATT
 GCGACCGAGA GACACAGATC TTTAAGACCA ACACACAGAC TGACCGAGGG
 AGCCTGGGGA ACCTGCGCGG CTACTACAAC CAGAGCGAGG CGGGGTCTCA
 CACTCTCCAG ACGATGTACG GCTGCGACAT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGTAC GCCTACGATG GCAAGGATTA CCTTGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCGGCG GACACGCCGG CTCAGATATC
 CCAGCGCAAG TTCGAGGCGG CCGGTGCGGC GGAGCAGTTG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGTCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGCGAGGA CCAAACTCAG
 GACACGGAGC TTGTGGAGAC CAGGCCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCAAAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCGTCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCATCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00756
IPD:MHC00756 Patr-B*17:03 1089 bases
 ATGATGGTCA TAGCCCCTCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAAG TATTTCTTCA
 CATCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGAGGTTC GACAGCGACG CCGCGAGTCC
 GAGGGTGGAG CCGCGGGCGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGACA GACACAGATC TCCAAGACCA ACGCACAGAC TGACCGAGGG
 AGCCTGGGGA ACCTGCGCGG CTACTACAAC CAGAGCGAGG CGGGGTCTCA
 CACTCTCCAG ACGATGTACG GCTGCGACAT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGTAC GCCTACGATG GCAAGGATTA CCTTGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCGGCG GACACGCCGG CTCAGATATC
 CCAGCGCAAG TTCGAGGCGG CCGGTGCGGC GGAGCAGTTG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGTCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGCGAGGA CCAAACTCAG
 GACACGGAGC TTGTGGAGAC CAGGCCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCAAAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCGTCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCATCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00757
IPD:MHC00757 Patr-B*18:01 1092 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAAG TATTTCTTCA
 CATCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ATACCCAGTT CGTGAGGTTC GACAGCGACG CCGCGAGTCC
 GAGGATGGAG CCCCGGGCGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGGA GACACGGAAC GTGAAGGCCT CCGCACAGAC TGACCGAGAG
 AACCTGCGGA TCGCGCTCCG CTACTACAAC CAGAGCGAGG CCGGTTCTCA
 CATCATCCAG AGGATGTACG GCTGCGACGT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGTCC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACCGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGAGGC GGAGCAGCGG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGCGAGGA CCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGAA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGAAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATTGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTTGTGGTC ACCGTAGCTG TGGTCGCTGT GGTCGCTGCT GTGATGTGTA
 GGAGGAAGAG CTCAGGTGGA AAAGGAGGGA GCTACTCTCA GGCTGCATCC
 AGCGACAGTG CCCAGGGCTC TGATGTGTCT CTCACAGCTT GA*
>DL;IPD:MHC00758
IPD:MHC00758 Patr-B*19:01 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCTACA
 CCTCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CTCAGTGGGC
 TACGTGGACG ATACGCAGTT CGTGAGGTTC GACAGCGACG CCGCGAGTCC
 GAGAGAGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCTGAGTATT
 GGGACCGGAA CACACAGATC TACAAGGCCC AGGCACAGAC TGACCGAGAG
 AACCTGCGGA TCGCGCTCCG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCCTCCAG ACGATGTATG GCTGCGACGT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGGAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGAGGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACTGAGC TTGTGGAGAC CAGGCCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGACA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCCCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC04212
IPD:MHC04212 Patr-B*19:02 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCTACA
 CCTCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CTCAGTGGGC
 TACGTGGACG ATACGCAGTT CGTGAGGTTC GACAGCGACG CCGCGAGTCC
 GAGAGAGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCTGAGTATT
 GGGACCGGAA CACACAGATC TACAAGGCCC AGGCACAGAC TGACCGAGAG
 AACCTGCGGA TCGCGCTCCG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCCTCCAG ACGATGTATG GCTGCGACGT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGGAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCGGCG GACACGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGAGGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACTGAGC TTGTGGAGAC CAGGCCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGACA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCCCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00759
IPD:MHC00759 Patr-B*20:01 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCTACA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ACACCCAGTT CGTGAGGTTC GACAGCGACG CCGCGAGTCC
 GAGGATGGAG CCCCGGGCGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGGA GACACGGAAC GTGAAGGCCT CCGCACAGAC TGACCGAGAG
 AACCTGCGGA TCGCGCTCCG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCTGGCAG ACGATGTATG GCTGCGACGT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA CGGGCAGTTC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACCAGGACC TGAGCTCCTG GACCGCGGCG GACACCGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGTGGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACATGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTT GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGCGAGGA CCAAACTCAG
 GACACGGAGC TTGTGGAGAC CAGACCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACATGCC
 ATGTACAGCA TGAGGGGCTG CCGAAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCATCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC04213
IPD:MHC04213 Patr-B*20:02 546 bases
 GCTCCCACTC CATGAGGTAT TTCTACACCG CCGTGTCCCG GCCCGGCCGC
 GGGGAGCCCC GCTTCATCAC CGTGGGCTAC GTGGACGACA CCCAGTTCGT
 GAGGTTCGAC AGCGACGCCG CGAGTCCGAG GATGGAGCCC CGGGCGCCAT
 GGATAGAGCA GGAGGGGCCG GAGTATTGGG ACCGGGAGAC ACGGAACGTG
 AAGGCCTCCG CACAGACTGA CCGAGAGAAC CTGCGGATCG CGCTCCGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC CTGGCAGACG ATGTATGGCT
 GCGACGTGGG GCCGGACGGG CGCCTCCTCC GCGGGTATGA GCAGTACGCC
 TACGACGGCA AGGATTACAT CGCCCTGAAC CAGGACCTGA GCTCCTGGAC
 CGCGGCGGAC ACCGCGGCTC AGATCACCCA GCGCAAGTGG GAGGCGGCCC
 GTGTGGCGGA GCAGCTGAGA GCCTACCTGG AGGGCACGTG CGTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGG*
>DL;IPD:MHC00760
IPD:MHC00760 Patr-B*21:01 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAAG TATTTCTACA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGTGGTTC GACAGCGACG CCGCGAGTCC
 GAGGATGGAG CCCCGGGCGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGACA GACACAGATC TCCAAGACCA ACACACAGAC TTACCGAGAG
 AGCCTGCGGA ACCTGCGCGG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCATCCAG ACGATGTATG GCTGCGACGT GGGGCCGGAC GGGCGCTTCC
 TCCGCGGGTA CCGGCAGTTC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTTGGGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGCCT GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACTGAGC TTGTGGAGAC CAGGCCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGACA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCCCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00761
IPD:MHC00761 Patr-B*22:01 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAAG TATTTCTACA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGTGGTTC GACAGCGACG CCGCGAGTCC
 GAGGAAGGAG CCGCGGACGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGAGA GACACAGATC TCCAAGACCA ACACACAGAC TTACCGAGAG
 AGCCTGCGGA ACCTGCGCGG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCCTCCAG ACGATGTTTG GCTGCGACGT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TGACCAGTAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGCGGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGCGA GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACTGAGC TTGTGGAGAC CAGGCCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGACA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCCCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00762
IPD:MHC00762 Patr-B*22:02 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAAG TATTTCTACA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGTGGTTC GACAGCGACG CCGCGAGTCC
 GAGGAAGGAG CCGCGGACGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGAGA GACACAGATC TCCAAGACCA ACACACAGAC TTACCGAGAG
 AACCTGCGGA TCGCGCTCCG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCCTCCAG ACGATGTTTG GCTGCGACGT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TGACCAGTAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGCGGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGCGA GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACTGAGC TTGTGGAGAC CAGGCCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGACA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCCCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC04214
IPD:MHC04214 Patr-B*22:03 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAAG TATTTCTACA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGTGGTTC GACAGCGACG CCGCGAGTCC
 GAGGAAGGAG CCGCGGACGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGAGA GACACAGATC TCCAAGACCA ACACACAGAC TTACCGAGAG
 AGCCTGCGGA ACCTGCGCGG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCCTCCAG ACGATGTTTG GCTGCGACGT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TGAACAGCAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGCGGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGCGA GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACTGAGC TTGTGGAGAC CAGGCCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGACA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCCCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00763
IPD:MHC00763 Patr-B*23:01 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAAG TATTTCTACA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CTCAGTGGGC
 TACGTGGACG ACACGCAGTT CGTGTGGTTC GACAGCGACG CCGCGAGTCC
 GAGAGAGGAG CCGCGGGCGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGAGA GACACAGATC TCCAAGACCA ACACACAGAC TTACCGAGAG
 AACCTGCGGA TCGCGCTCCG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACTCTGCAG ACGATGTATG GCTGCGACGT GGGGCCGGAC GGGCGCTTCC
 TCCGCGGGTA CCGGCAGTTC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTTGGGC GGAGCAGTGG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACTGAGC TTGTGGAGAC CAGGCCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGACA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCCCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00764
IPD:MHC00764 Patr-B*23:02 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAAG TATTTCTACA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CTCAGTGGGC
 TACGTGGACG ACACGCAGTT CGTGTGGTTC GACAGCGACG CCGCGAGTCC
 GAGAGAGGAG CCGCGGGCGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGAGA GACACAGATC TCCAAGACCA ACACACAGAC TTACCGAGAG
 AACCTGCGGA TCGCGCTCCG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCCTCCAG ACGATGTATG GCTGCGACGT GGGGCCGGAC GGGCGCTTCC
 TCCGCGGGTA CCGGCAGTTC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTTGGGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGCCT GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CTCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACTGAGC TTGTGGAGAC CAGGCCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGACA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCCCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00765
IPD:MHC00765 Patr-B*23:03 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAAG TATTTCTACA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CTCAGTGGGC
 TACGTGGACG ACACGCAGTT CGTGTGGTTC GACAGCGACG CCGCGAGTCC
 GAGAGAGGAG CCGCGGGCGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGAGA GACACAGATC TCCAAGACCA ACACACAGAC TTACCGAGAG
 AACCTGCGGA CCCTGCTCCG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCCTCCAG ACGATGTATG GCTGCGACGT GGGGCCGGAC GGGCGCTTCC
 TCCGCGGGTA CCGGCAGTAT GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTTGGGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGCCT GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CTCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACTGAGC TTGTGGAGAC CAGGCCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGACA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCCCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC04215
IPD:MHC04215 Patr-B*23:04 546 bases
 GCTCCCACTC CATGAAGTAT TTCTACACCG CCGTGTCCCG GCCCGGCCGC
 GGGGAGCCCC GCTTCATCTC AGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GTGGTTCGAC AGCGACGCCG CGAGTCCGAG AGAGGAGCCG CGGGCGCCAT
 GGATAGAGCA GGAGGGGCCG GAGTATTGGG ACCGAGAGAC ACAGATCTCC
 AAGACCAACG CACAGACTGA CCGAGAGAGC CTGCGGAACC TGCGCGGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC CCTCCAGACG ATGTATGGCT
 GCGACGTGGG GCCGGACGGG CGCTTCCTCC GCGGGTACCG GCAGTTCGCC
 TACGACGGCA AGGATTACAT CGCCCTGAAC GAGGACCTGA GCTCCTGGAC
 CGCGGCGGAC ACGGCGGCTC AGATCACCCA GCGCAAGTGG GAGGCGGCCC
 GTGTGGCGGA GCAGCACAGA GCCTACCTGG AGGGCCTGTG CGTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGG*
>DL;IPD:MHC00766
IPD:MHC00766 Patr-B*24:01 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAAG TATTTCTACA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGTGGTTC GACAGCGACG CCGCGAGTCC
 GAGGAAGGAG CCGCGGACGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGAGA GACACAGATC TCCAAGACCA ACGCACAGAC TGACCGAGAG
 AACCTGCGGA CCCTGCTCCG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCTGGCAG ACGATGTTTG GCTGCGACGT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA CCGGCAGTTC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACCGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGTGGC GGAGCAGCGG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACTGAGC TTGTGGAGAC CAGGCCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGACA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCCCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00767
IPD:MHC00767 Patr-B*24:02 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAAG TATTTCTACA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGTGGTTC GACAGCGACG CCGCGAGTCC
 GAGGAAGGAG CCGCGGACGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGAGA GACACAGATC TCCAAGACCA ACGCACAGAC TGACCGAGAG
 AACCTGCGGA CCCTGCTCCG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCTGGCAG ACGATGTTTG GCTGCGACGT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA CCGGCAGTAT GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACCGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGTGGC GGAGCAGCGG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACTGAGC TTGTGGAGAC CAGGCCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGACA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCCCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00768
IPD:MHC00768 Patr-B*25:01 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAAG TATTTCTTAA
 CATCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ACACCCAGTT CGTGAGGTTC GACAGCGACG CCGCGAGTCC
 GAGGATGGAG CCCCGGGCGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGGA GACACGGAAC ATGAAGGCCT CCGCACAGAC TTACCGAGAG
 AACCTGCGGA TCGCGCTCCG CTATTACAAC CAGAGCGAGG ACGGGTCTCA
 CACTCTCCAG ACGATGTATG GCTGCGACGT GGGGCCGGAC GGGCGCTTCC
 TCCGCGGGTA CCGGCAGTTC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGAGGC GGAGCAGCGG AGAGCCTACC
 TGGAGGGCCT GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACTGAGC TTGTGGAGAC CAGGCCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGACA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCCCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00769
IPD:MHC00769 Patr-B*26:01 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCTACA
 CCTCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ACACCCAGTT CGTGAGGTTC GACAGCGACG CCGCGAGTCC
 GAGGATGGAG CCCCGGGCGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGGA GACACGGAAC GTGAAGGCCT CCGCACTGAC TGACCGAGAG
 AACCTGCGGA CCCTGCTCCG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCCTCCAG ACGATGTATG GCTGCGACGT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TGAGCAGTTC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGAGGC GGAGCAGCAC AGAGCCTACC
 TGGAGGGCCT GTGCGTGGAC GGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACTGAGC TTGTGGAGAC CAGGCCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGACA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCCCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00770
IPD:MHC00770 Patr-B*27:01 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCTACA
 CCTCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ACACCCAGTT CGTGAGGTTC GACAGCGACG CCGCGAGTCC
 GAGGATGGAG CCCCGGGCGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGGA GACACGGAAC GTGAAGGCCT CCGCACAGAC TGACCGAGGG
 AGCCTGCGGA ACCTGCGCGG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCCTCCAG ACGATGTATG GCTGCGACGT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGTAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGTGGC GGAGCAGTGG AGAGCCTACC
 TGGAGGGCCT GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACTGAGC TTGTGGAGAC CAGGCCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGACA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCCCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00771
IPD:MHC00771 Patr-B*28:01 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCTACA
 CCTCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGAGGTTC GACAGCGACG CCGCGAGTCC
 GAGAGAGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGGG CCTGAGTATT
 GGGACCGGAA CACACAGATC TTCAAGGCCC AGGCACAGAC TGACCGAGTG
 GGCCTGGGGA ACCTGCGCGG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCTGGCAG ACGATGTATG GCTGCGACGT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TTACCAGCAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGCGGC GGAGCAGCGG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACTGAGC TTGTAGAGAC CAGGCCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATTGTGGGC ATCGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCCCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00772
IPD:MHC00772 Patr-B*29:01 1061 bases
 TCCTGCTGCT CTGGGGGGCA GTGGCCCTGA CCGAGACCTG GGCCGGCTCC
 CACTCCATGA GGTATTTCTA CACCGCCATG TCCCGGCCCG GCCGCGGGGA
 GCCCCGCTTC ATCGCAGTAG GCTATGTGGA CGACACCCAG TTCGTGAGGT
 TCGACAGCGA CGCCGCGATT CCGAGGATGG AGCCGCGGGC GCCATGGATA
 GAGCAGGAGG GGCCGGAGTA TTGGGACGGG AACACACAGG GCGTCAAGAC
 GCAGGCACAG ACTGACCGAG AGAGCCTGCG GAACCTGCGC GGCTACTACA
 ACCAGAGCGA GGCCGGGTCT CACACCTGGC AGACGATGTA TGGCTGCGAC
 ATGGGGCCGG ACGGGCGCCT CCTCCGCGGG TATGGCCAGT ACGCCTACGA
 CAGCAAGGAT TACATCGCCC TGAACAAGGA CCTGAGCTCC TGGACCGCGG
 CGGACACCGC GGCTCAGATC ACCCAGCGCA AGTGGGAGGC GGCCCGTGTG
 GCGGAGCAGC TGAGAGCCTA CCTGGAGGGC ACGTGCGTGG AGTGGCTCCG
 CAGATACCTG GAGAACGGGA AGGAGACGCT GCAGCGCGCG GACCCCCCAA
 AGACACATGT GACCCACCAC CCCATCTCTG ACCATGAGGC CACCCTGAGG
 TGCTGGGCCC TTGGCTTCTA CCCTGCGGAG ATCACACTGA CCTGGCAGCG
 GGATGGCGAG GACCAAACTC AGGACACCGA GCTTGTGGAG ACCAGACCAG
 CAGGAGATAG AACCTTCCAG AAGTGGGCAG CTGTGGTGGT GCCTTCTGGA
 GAAGAGCAGA GATACACATG CCATGTACAG CATGAGGGGC TGCCGAAGCC
 CCTCACCCTG AGATGGGAGC CATCTTCCCA GTCCACCATC CCCATCGTGG
 GCATTGTTGC TGGCCTGGCT GTCCTAGCAG TTGTGGTCAT CGGAGCTGTG
 GTCGCTGCTG TGATGTGTAG GAGGAAGAGC TCAGGTGGAA AAGGAGGGAG
 CTACTCTCAG GCTGCGTCCA GCGACAGTGC CCAGGGCTCT GATGTGTCTC
 TCACAGCTTG A*   
>DL;IPD:MHC00773
IPD:MHC00773 Patr-B*30:01 1083 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAAG TATTTCTACA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGTGGTTC GACAGCGACG CCGCGAGTCC
 GAGGAAGGAG CCGCGGACGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGAGA GACACAGATC TCCAAGACCA ACGCACAGAC TTACCGAGAG
 AACCTGCGGA TCGCGCTCCG CTACTACAAC CAGAGCGAGG CCGGTTCTCA
 CATCATCCAG AGGATGTACG GCTGCGACAT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TGACCAGTAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTTGGGC GGAGCAGCAC AGAGCCTACC
 TGGAGGGCGA GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGCGAGGA CCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGAA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGAAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCCTGTGGTC ACCGTAGCTG TGGTCGCTGC TGTGATGTGT AGGAGGAAGA
 GCTCAGGTGG AAAAGGAGGG AGCTACTCCC AGGCTGCGTC CAGCGACAGT
 GCCCAGGGCT CTGATGTGTC TCTCACAGCT TGA* 
>DL;IPD:MHC04216
IPD:MHC04216 Patr-B*33:01 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAAG TATTTCTTAA
 CATCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ACACCCAGTT CGTGAGGTTC GACAGCGACG CCGCGAGTCC
 GAGGATGGAG CCCCGGGCGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGGA GACACGGAAC GTGAAGGCCT CCGCACAGAC TTACCGAGAG
 AACCTGCGGA TCGCGCTCCG CTATTACAAC CAGAGCGAGG ACGGGTCTCA
 CACCTGGCAG ACGATGTATG GCTGCGACGT GGGGCCCGAC GGGCGCCTCC
 TCCGCGGGTA TGAGCAGTAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGTGGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGCCT GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACTGAGC TTGTGGAGAC CAGGCCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGACA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCCCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC04217
IPD:MHC04217 Patr-B*34:01 1089 bases
 ATGCAGGTCA CGGCGCCCCG AACCGTCCTC CTGCTGCTCT CGGCGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAAG TATTTCTACA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGTGGTTC GACAGCGACG CCGCGAGTCC
 GAGGAAGGAG CCGCGGACGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGAGA GACACAGATC TCCAAGACCA ACACACAGAC TTACCGAGAG
 AACCTGCGGA TCGCGCTCCG CTACTACAAC CAGAGCGAGG CCGGGTCTCA
 CACCTGGCAG ACGATGTATG GCTGCGACGT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TGAGCAGTAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCGGCG GACACGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGCGGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGCGA GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACTGAGC TTGTGGAGAC CAGGCCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGACA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCACCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCCCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC01100
IPD:MHC01100 Patr-B*35:01 546 bases
 GCTCCCACTC CATGAGGTAT TTCTACATCG CCATGTCCCG GCCCGGCCGC
 GGGGAGCCCC GCTTCATCGC AGTGGGCTAT GTGGACGACA CCCAGTTCGT
 GAGGTTCGAC AGCGACGCCG CGATTCCGAG GATGGAGCCG CGGGCGCCAT
 GGATAGAGCA GGAGGGGCCG GAGTATTGGG ACCGGAACAC ACAGATCTAC
 AAGGCCCAGG CACAGACTGA CCGAGAGAGC CTGCGGAACC TGCGCGGCTA
 CTACAACCAG AGCGAGGCCG GTTCTCACAT CATCCAGAGG ATGTACGGCT
 GCGACATGGG GCCGGACGGG CGCCTCCTCC GCGGGTATGA GCAGTACGCC
 TACGACGGCA AGGATTACAT CGCCCTGAAC CAGGACCTGA GCTCCTGGAC
 CGCGGCGGAC ACCGCGGCTC AGATCACCCA GCGCAAGTGG GAGGCGGCCC
 GTTGGGCGGA GCAGCTGAGA GCCTACCTGG AGGGCACGTG CGTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGG*
>DL;IPD:MHC02055
IPD:MHC02055 Patr-B*36:01 1089 bases
 ATGCGGGTCA CGGCGCCCCG AACCCTCCTC CTGCTGCTCT GGGGGGCAGT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCTACA
 CCGCCATGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CGCAGTAGGC
 TATGTGGACG ACACCCAGTT CGTGAGGTTC GACAGCGACG CCGCGATTCC
 GAGGATGGAG CCGCGGGCGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGAA CACACAGGGC GTCAAGGCCC AGGCACAGAC TGACCGAGAG
 AACCTGCGGA TCGCGCTCCG CTACTACAAC CAGAGCGAGG CCGGTTCTCA
 CATCATCCAG AGGATGTACG GCTGCGACAT GGGGCCGGAC GGGCGCCTCC
 TCCGCGGGTA TGAGCAGTAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACCAGGACC TGAGCTCCTG GACCGCGGCG GACACCGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTTGGGC GGAGCAGCTG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCAAAG ACACATGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTT GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGCGAGGA CCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGACCAGCA GGAGATAGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACATGCC
 ATGTACAGCA TGAGGGGCTG CCGAAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCATCG GAGCTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTCCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC02057
IPD:MHC02057 Patr-B*37:01 546 bases
 GCTCCCACTC CATGAGGTAT TTCTACACCG CCATGTCCCG GCCCGGCCGC
 GGGGAGCCCC GCTTCATCGC AGTAGGCTAT GTGGACGACA CCCAGTTCGT
 GAGGTTCGAC AGCGACGCCG CGATTCCGAG GATGGAGCCG CGGGCGCCAT
 GGATAGAGCA GGAGGGGCCG GAGTATTGGG ACCGGAACAC ACAGGGCGTC
 AAGGCCCAGG CACAGACTGA CCGAGAGAAC CTGCGGATCG CGCTCCGCTA
 CTACAACCAG AGCGAGGCCG GTTCTCACAT CATCCAGAGG ATGTACGGCT
 GCGACATGGG GCCGGACGGG CGCCTCCTCC GCGGGTATTA CCAGTACGCC
 TACGACGGCA AGGATTACAT CGCCCTGAAC GAGGACCTGA GCTCCTGGAC
 CGCGGCGGAC ACGGCGGCTC AGATCACCCA GCGCAAGTGG GAGGCGGCCC
 GTGCGGCGGA GCAGCGGAGA GCCTACCTGG AGGGCACGTG CGTGGAGTGG
 CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCGG*
