>DL;IPD:MHC00911
IPD:MHC00911 Patr-F 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGTTC TCAGGGGCCC TGGCCCTGAC
 CGAGACTTGG GCAGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT
 CGCGGCCCGG CCGCGGGGAG CCCCGGTACA TCGCAGTGGA GTACGTAGAC
 GACACGCAGT TCCTGCGGTT CGACAGCGAC GCCGCGATTC CGAGGATGGA
 GCCTCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT TGGGAGAGGA
 CCACAGGGTA CGCGAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCCGGGTCTC ACACCCTCCA
 GGGAATGAAT GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTTCGCGGGT
 ATCACCAGCA CGCGTACGAC GGCAAGGATT ACATCTCCCT GAACGAGGAC
 CTGCGCTCCT GGACCGCGGC GGACACCGTG GCTCAGATCA CCCAGCGCTT
 CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC CTGGAGGGCG
 AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAACGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACATT GCCCACCACC CCATCTCTGA
 CCATGAGGCC ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA
 TCACGCTGAC CTGGCAGCGG GATGGGGAGG AACAGACCCA GGACACAGAG
 CTTGTGGAGA CCAGGCCTGC AGGGGATGGA AACTTCCAGA AGTGGGCTGC
 TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACCTGC CATGTGCAGC
 ACGAGGGGCT GCCCCAGCCC CTCACCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC
 TGTGGTCACT GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT
 CAGATAGAAA CAGAGGGAGC TACTCTCAGG CTGCAGTGTG A*
