>DL;IPD:MHC00705
IPD:MHC00705 Patr-A*01:01 366 bases
 MAVMPPRTLL LLLSGALALT QTWAGSHSMR YFFTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWIEQEG PEYWDQETRS AKAHSQTDRV
 DLGTLRGYYN QSEDGSHTIQ IMYGCDVGSD GRFLRGYRQD AYDGKDYIAL
 NEDLRSWTAA DMAAQITKRK WEAAHAAEQQ RAYLEGTCVE WLRRYLENGK
 ETLQRTDPPK THMTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQPTIPIVG IIAGLVLLGA VITGAVVAAV MWRRKSSDRK GGSYTQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC00706
IPD:MHC00706 Patr-A*02:01 366 bases
 MAVMPPRTLL LLLSGALALT QTWAGSHSMR YFFTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWIEQEG PEYWDEETRS AKAHSQTDRV
 DLGTLRGYYN QSEDGSHTIQ IMYGCDVGSD GRFLRGYRQD AYDGKDYIAL
 NEDLRSWTAA DMAAQITKRK WEAAHAAEQR RAYLEGTCVE WLRRYLENGK
 ETLQRTDPPK THMTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQPTIPIVG IIAGLVLLGA VITGAVVAAV MWRRKSSDRK GGSYTQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC00707
IPD:MHC00707 Patr-A*03:01 366 bases
 MAVMPPRTLL LLLSGALALT QTWAGSHSMR YFYTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWIEQEG PEYWDQETRN MKASAQTDRV
 DLGTLRGYYN QSEDGSHTIQ IMYGCDVGSD GRFLRGYRQD AYDGKDYIAL
 NEDLRSWTAA AMAAQITKRK WEAAHAAEQL RAYLEGRCVE WLRRYLENGK
 ETLQRTDPPK THMTHHPISD HEATLRCWAL GFYPAVITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQPTIPIVG IIAGLVLLGA VITGAVVAAV MWRRKSSDRK GGSYTQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC00708
IPD:MHC00708 Patr-A*03:02 366 bases
 MAVMPPRTLL LLLSGALALT QTWAGSHSMR YFYTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWIEQEG PEYWDQETRN MKASAQTDRV
 DLGTLRGYYN QSEDGSHTIQ IMYGCDVGSD GRFLRGYRQD AYDGKDYIAL
 NEDLRSWTAA AMAAQITKRK WEAAHAAEQL RAYLEGRCVD GLRRYLENGK
 ETLQRTDPPK THMTHHPISD HEATLRCWAL GFYPAVITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQPTIPIVG IIAGLVLLGA VITGAVVAAV MWRRKSSDRK GGSYTQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC04208
IPD:MHC04208 Patr-A*03:03 366 bases
 MAVMPPRTLL LLLSGALALT QTWAGSHSMR YFYTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWIEQEG PEYWDRETRS VKASAQIYRA
 NLGTLRGYYN QSEDGSHTIQ IMYGCDVGSD GRFLRGYRQD AYDGKDYIAL
 NEDLRSWTAA DMAAQITKRK WEAAHAAEQL RAYLEGRCVD GLRRYLENGK
 ETLQRTDPPK THMTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YICHVQHEGL PKPLTLRWEP
 SSQPTIPIVG IIAGLVLLGA VITGAVVAAV MWRRKSSDRK GGSYTQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC04209
IPD:MHC04209 Patr-A*03:04 366 bases
 MAVMPPRTLL LLLSGALALT QTWAGSHSMR YFFTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWIEQEG PEYWDQETRN MKASAQTDRA
 NLGTLRGYYN QSEDGSHTIQ IMYGCDVGSD GRFLRGYRQD AYDGKDYIAL
 NEDLRSWTAA DMAAQITKRK WEAAHAAEQW RAYLEGRCME WLRRYLENGK
 ETLQRTDPPK THMTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVKTRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQPTIPIVG IIAGLVLLGA VITGAVVAAV MWRRKSSDRK GGSYTQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC00709
IPD:MHC00709 Patr-A*04:01 366 bases
 MAVMAPRTLV LLLSGALALT QTWAGSHSMR YFSTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWIEQEG PEYWDEETRS VKASAQTDRV
 DLGTLRGYYN QSEDGSHTIQ LMFGCDVGSD GRFLRGYRQD AYDGKDYIAL
 NEDLRSWTAA DMAAQITQRK WEAAHAAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRTDPPK THMTHHPISD REATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQPTIPIVG IIAGLVLLGA VITGAVVAAV MWRRKSSDRK GGSYSQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC00710
IPD:MHC00710 Patr-A*04:02 366 bases
 MAVMAPRTLV LLLSGALALT QTWAGSHSMR YFSTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWIEQEG PEYWDEETRS VKASAQTDRV
 DLGTLRGYYN QSEDGSHTIQ LMFGCDVGSD GRFLRGYRQD AYDGKDYIAL
 NEDLRSWTAA DMAAQITQRK WEAAHAAEQW RAYLEGTCVD GLRRYLENGK
 ETLQRTDPPK THMTHHPISD REATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQPTIPIVG IIAGLVLLGA VITGAVVAAV MWRRKSSDRK GGSYSQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC00711
IPD:MHC00711 Patr-A*04:04 366 bases
 MAVMAPRTLV LLLSGALALT QTWAGSHSMR YFSTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWIEQEG PEYWDEETRS VKAQAQTDRV
 DLGTLRGYYN QSEDGSHTIQ LMFGCDVGSD GRFLRGYRQD AYDGKDYIAL
 NEDLRSWTAA DMAAQITQRK WEAAHAAEQW RAYLEGTCVD GLRRYLENGK
 ETLQRTDPPK THMTHHPISD REATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQPTIPIVG IIAGLVLLGA VITGAVVAAV MWRRKSSDRK GGSYSQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC00712
IPD:MHC00712 Patr-A*05:01 366 bases
 MAVMAPRTLV LLLSGALALT QTWAGSHSMR YFSTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWIEQEG PEYWDEETRS VKAFAQTDRV
 DLGTLRGYYN QSEDGSHTIQ LMFGCDVGSD GRFLRGYRQD AYDGKDYIAL
 NEDLRSWTAA DMAAQITQRK WEAAHAAEQW RAYLEGTCVD GLRRYLENGK
 ETLQRTDPPK THMTHHPISD REATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQPTIPIVG IIAGLVLLGA VITGAVVAAV MWRRKSSDRK GGSYSQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC00713
IPD:MHC00713 Patr-A*06:01 366 bases
 MAVMAPRTLV LLLSGALALT QTWAGSHSMR YFSTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWIEQEG PEYWDQETRS VKASAQTDRA
 NLGTLRGYYN QSEDGSHTIQ IMYGCDVGSD GRFLRGYRQD AYDGKDYIAL
 NEDLRSWTAA DMAAQITQRK WEAAHAAEQW RAYLEGTCVD GLRRYLENGK
 ETLQRTDPPK THMTHHPISD REATLRCCAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQPTIPIVG IIAGLVLLGA VITGAVVAAV MWRRKSSDRK GGSYSQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC00714
IPD:MHC00714 Patr-A*06:02 366 bases
 MAVMAPRTLV LLLSGALALT QTWAGSHSMR YFSTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWIEQEG PEYWDQETRS VKAFAQTDRA
 NLGTLRGYYN QSEDGSHTIQ IMYGCDVGSD GRFLRGYRQD AYDGKDYIAL
 NEDLRSWTAA DMAAQITQRK WEAAHAAEQW RAYLEGTCVD GLRRYLENGK
 ETLQRTDPPK THMTHHPISD REATLRCCAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQPTIPIVG IIAGLVLLGA VITGAVVAAV MWRRKSSDRK GGSYSQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC00715
IPD:MHC00715 Patr-A*07:01 366 bases
 MAVMAPRTLV LLLSGALALT QTWAGSHSMR YFSTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWIEQEG PEYWDRETRS VKAGAQIYRA
 NLGTLRGYYN QSEDGSHTIQ LMFGCDVGSD GRFLRGYEQL AYDGKDYIAL
 NEDLRSWTAA DMAAQITQRK WEAVHAAEQQ RAYLEGRCVE SLRRYLENGK
 ETLQRTDPPK THMTHHPISD REATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQPTIPIVG IIAGLVLLGA VITGAVVAAV MWRRKSSDRK GGSYSQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC00716
IPD:MHC00716 Patr-A*08:01 366 bases
 MAVMAPRTLV LLLSGALALT QTWAGSHSMR YFSTSVSRPG RGEPRFIAVG
 YVDNTQFVRF DSDAASQRME PRAPWIEQEG PEYWDQETRS VKAGAQIYRA
 NLGTLRGYYN QSEDGSHTIQ IMFGCDVGSD GRFLRGYEQL AYDGKDYIAL
 NEDLRSWTAA DMAAQITQRK WEAAHAAEQR RAYLEGTCVE WLRRYLENGK
 ETLQRTDPPK THMTHHPISD REATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL LKPLTLRWEP
 SSQPTIPIVG IIAGLVLLGA VITGAVVAAM MWRRKSSDRK GGSYSQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC00717
IPD:MHC00717 Patr-A*08:02 364 bases
 VMAPRTLVLL LSGALALTQT WAGSHSMRYF STSVSRPGRG EPRFIAVGYV
 DNTQFVRFDS DAASQRMEPR APWIEQEGPE YWDQETRSVK AGAQIYRANL
 GTLRGYYNQS EDGSHTIQLM FGCDVGSDGR FLRGYEQLAY DGKDYIALNE
 DLRSWTAADM AAQITQRKWE AAHAAEQRRA YLEGTCVEWL RRYLENGKET
 LQRTDPPKTH MTHHPISDRE ATLRCWALGF YPAEITLTWQ RDGEDQTQDT
 ELVETRPAGD GTFQKWAAVV VPSGEEQRYT CHVQHEGLLK PLTLRWEPSS
 QPTIPIVGII AGLVLLGAVI TGAVVAAMMW RRKSSDRKGG SYSQAASSDS
 AQGSDVSLTA CKVX*   
>DL;IPD:MHC00718
IPD:MHC00718 Patr-A*08:03 364 bases
 VMAPRTLVLL LSGALALTQT WAGSHSMRYF STSVSRPGRG EPRFIAVGYV
 DNTQFVRFDS DAASQRMEPR APWIEQEGPE YWDQETRSVK AGAQIYRANL
 GTLRGYYNQS EDGSHTIQIM FGCDVGSDGR FLRGYEQLAY DGKDYIALNE
 DLRSWTAADM AAQITQRKWE AAHAAEQRRA YLEGTCVEWL RRYLENGKET
 LQRTDPPKTH MTHHPISDRE ATLRCWALGF YPAEITLTWQ RDGEDQTQDT
 ELVETRPAGD GTFQKWAAVV VPSGEEQRYT CHVQHEGLLK PLTLRWEPSS
 QPTIPIVGII AGLVLLGAVI TGAVVAAMMW RRKSSDRKGG SYSQAASSDS
 AQGSDVSLTA CKVX*   
>DL;IPD:MHC00719
IPD:MHC00719 Patr-A*09:01 366 bases
 MAVIAPRTLV LLLSGALALT QTWAGSHSMR YFSTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWIEQEG PEYWDEETRS VKASAQTDRV
 DLGTLRGYYN QSEDGSHTIQ IMYGCDVGSD GRFLRGYRQY AYDGKDYIAL
 NEDLRSWTAA DMAAQITQRK WEAAHAAERL RAYLEGTCVE WLRRYLENGK
 ETLQRTDPPK THMTHHPISD REATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQPTIPIVG IIAGLVLLGA VITGAVVAAV MWRRKSSDRK GGSYSQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC01099
IPD:MHC01099 Patr-A*09:02 181 bases
 SHSMRYFSTS VSRPGRGEPR FIAVGYVDDT QFVRFDSDAA SQRMEPRAPW
 IEQEGPEYWD EETRSVKASA QTDRVDLGTL RGYYNQSEDG SHTIQIMYGC
 DVGSDGRFLR GYRQDAYDGK DYIALNEDLR SWTAADMAAQ ITQRKWEAAH
 AAERLRAYLE GTCVEWLRRY LENGKETLQR T* 
>DL;IPD:MHC00720
IPD:MHC00720 Patr-A*10:01 366 bases
 MAVMAPRTLV LLLSGALALT QTWAGSHSMR YFSTSVSRPG RGEPRFIAVG
 YVDNTQFVRF DSDAASQRME PRAPWIEQEG PEYWDQETRN MKAFAQIYRA
 NLGTLRGYYN QSEDGSHTIQ LMFGCDVGSD GRFLRGYEQH AYDGKDYIAL
 NEDLRSWTAA DMAAQITQRK WEAAHAAEQW RAYLEGRCVD GLRRYLENGK
 ETLQRTDPPK THMTHHPISD REATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL LKPLTLRWEP
 SSQPTIPIVG IIAGLVLLGA VITGAVVAAM MWRRKSSDRK GGSYSQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC00721
IPD:MHC00721 Patr-A*11:01 358 bases
 LLLLLSGALA LTQTWAGSHS MRYFYTSVSR PGRGEPRFIA VGYVDDTQFV
 RFDSDAASQR MEPRAPWIEQ EGPEYWDQET RNMKASAQTD RANLGTLRGY
 YNQSEDGSHT IQIMYGCDVG SDGRFLRGYR QDAYDGKDYI ALNEDLRSWT
 AADMAAQITK RKWEAAHAAE QRRAYLEGTC VDGLRRYLEN GKETLQRTDP
 PKTHMTHHPI SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDTELVETR
 PAGDGTFQKW AAVVVPSGEE QRYTCHVQHE GLPKPLTLRW EPSSQPTIPI
 VGIIAGLVLL GAVITGAVVA AVMWRRKSSD RKGGSYTQAA SSDSAQGSDV
 SLTACKVX*    
>DL;IPD:MHC00722
IPD:MHC00722 Patr-A*12:01 366 bases
 MAVMAPRTLV LLLSGALALT QTWAGSHSMR YFSTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWIEQEG PEYWDEETRS VKASAQTDRA
 NLGTLRGYYN QSEDGSHTIQ LMFGCDVGSD GRFLRGYEQH AYDGKDYIAL
 NEDLRSWTAA DMAAQITQRK WEAAHAAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRTDPPK THMTHHPISD REATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQPTIPIVG IIAGLVLLGA VITGAVVAAV MWRRKSSDRK GGSYSQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC00723
IPD:MHC00723 Patr-A*13:01 358 bases
 LVLLLSGALA LTQTWAGSHS MRYFSTSVSR PGRGEPRFIA VGYVDDTQFV
 RFDSDAASQR MEPRAPWIEQ EGPEYWDEET RSVKAFAQTD RANLGTLRGY
 YNQSEDGSHT IQLMFGCDVG SDGRFLRGYR QYAYDGKDYI ALNEDLRSWT
 AADMAAQITQ RKWEAAHAAE QQRAYLEGTC VEWLRRYLEN GKETLQRTDP
 PKTHMTHHPI SDREATLRCW ALGFYPAEIT LTWQRDGEDQ TQDTELVETR
 PAGDGTFQKW AAVVVPSGEE QRYTCHVQHE GLPKPLTLRW EPSSQPTIPI
 VGIIAGLVLL GAVITGAVVA AVMWRRKSSD RKGGSYSQAA SSDSAQGSDV
 SLTACKVX*    
>DL;IPD:MHC00724
IPD:MHC00724 Patr-A*14:01 366 bases
 MAVMAPRTLV LLLSGALALT QTWAGSHSMR YFSTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWIEQEG PEYWDEETRS VKAFAQTDRA
 NLGTLRGYYN QSEDGSHTIQ LMFGCDVGSD GRFLRGYEQH AYDGKDYIAL
 NEDLRSWTAA DMAAQITQRK CEAAHAAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRTDPPK THMTHHPISD REATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQPTIPIVG IIAGLVLLGA VITGAVVAAV MWRRKSSDRK GGSYSQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC00725
IPD:MHC00725 Patr-A*15:01 366 bases
 MAVMAPRTLV LLLSGALALT QTWAGSHSMR YFSTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWIEQEG PEYWDEETRS VKAFAQTDRA
 NLGTLRGYYN QSEDGSHTIQ LMFGCDVGSD GRFLRGYEQH AYDGKDYIAL
 NEDLRSWTAA DMAAQITQRK WEAAHAAEQQ RAYLEGTCVE WLRRYLENGK
 ETLQRTDPPK THMTHHPISD REATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQPTIPIVG IIAGLVLLGA VITGAVVAAV MWRRKSSDRK GGSYSQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC00726
IPD:MHC00726 Patr-A*15:02 364 bases
 VMAPRTLVLL LSGALALTQT WAGSHSMRYF STSVSRPGRG EPRFIAVGYV
 DDTQFVRFDS DAASQRMEPR APWIEQEGPE YWDEETRSVK AFAQTDRANL
 GTLRGYYNQS EDGSHTIQLM FGCDVGSDGR FLRGYEQHAY DGKDYIALNE
 DLRSWTAADM AAQITQRKWE AAHAAEQDRA YLEGTCVEWL RRYLENGKET
 LQRTDPPKTH MTHHPISDRE ATLRCWALGF YPAEITLTWQ RDGEDQTQDT
 ELVETRPAGD GTFQKWAAVV VPSGEEQRYT CHVQHEGLPK PLTLRWEPSS
 QPTIPIVGII AGLVLLGAVI TGAVVAAVMW RRKSSDRKGG SYSQAASSDS
 AQGSDVSLTA CKVX*   
>DL;IPD:MHC00727
IPD:MHC00727 Patr-A*16:01 366 bases
 MAVMAPRTLV LLLSGALALT QTWAGSHSMR YFYTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWIEQEG PEYWDEETRS AKAHSQTDRV
 DLGTLRGYYN QSEDGSHTIQ LMYGCDVGSD GRFLRGYRQD AYDGKDYIAL
 NEDLRSWTAA DMAAQITQLK WEAAHVAEQL RAYLEGLCVD GLRRYLENGK
 ETLQRTDPPK THMTHHPISD REATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQPTIPIVG IIAGLVLLGA VITGAVVAAV MWRRKSSDRK GGSYSQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC00728
IPD:MHC00728 Patr-A*17:01 364 bases
 VMAPRTLVLL LSGALALTQT WAGSHSMRYF YTSVSRPGRG EPRFIAVGYV
 DDTQFVRFDS DAASQRMEPR APWIEQEGPE YWDEETRSTK ASAQTNRVDL
 GTLRGYYNQS EDGSHTIQIM YGCDVGSDGR FLRGYRQDAY DGKDYIALNE
 DLRSWTAADM AAQITQRKWE AAHVAEQDRA YLEGTCVEWL RRYLENGKET
 LQRTDPPKTH MTHHPISDRE ATLRCWALGF YPAEITLTWQ QDGEDQTQDT
 ELVETRPAGD GTFQKWAAVV VPSGEEQRYT CHVQHEGLPK PLTLRWEPSS
 QPTIPIMGII AGLVLLGAVI TGAVVAAVMW RRKSSDRKGG RYSQAASSDS
 AQGSDVSLTA CKVX*   
>DL;IPD:MHC00729
IPD:MHC00729 Patr-A*17:02 366 bases
 MAVMAPRTLV LLLSGALALT QTWAGSHSMR YFYTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWIEQEG PEYWDEETRS AKASAQTNRV
 DLGTLRGYYN QSEDGSHTIQ IMYGCDVGSD GRFLRGYRQD AYDGKDYIAL
 NEDLRSWTAA DMAAQITQRK WEAAHVAEQD RAYLEGTCVE WLRRYLENGK
 ETLQRTDPPK THMTHHPISD REATLRCWAL GFYPAEITLT WQQDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQPTIPIMG IIAGLVLLGA VITGAVVAAV MWRRKSSDRK GGSYTQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC01098
IPD:MHC01098 Patr-A*17:03 181 bases
 SHSMRYFYTS VSRPGRGEPR FIAVGYVDDT QFVRFDSDAA SQRMEPRAPW
 IEQEGPEYWD QETRNMKASA QTDRVDLGTL RGYYNQSEDG SHTIQIMYGC
 DVGSDGRFLR GYRQDAYDGK DYIALNEDLR SWTAADMAAQ ITQRKWEAAH
 VAEQDRAYLE GTCVEWLRRY LENGKETLQR T* 
>DL;IPD:MHC00730
IPD:MHC00730 Patr-A*18:01 364 bases
 VMAPRTLVLL LSGALALTQT WAGSHSMRYF STSVSRPGRG EPRFIAVGYV
 DDTQFVRFDS DAASQRMEPR APWIEQEGPE YWDEETRSVK AFAQTDRVDL
 GTLRGYYNQS EDGSHTIQLM FGCDVGSDGR FLRGYEQLAY DGKDYIALNE
 DLRSWTAADM AAQITQRKWE AAHEAEQWRA YLEGRCVEWL RRYLENGKET
 LQRTDPPKTH MTHHPISDRE ATLRCWALGF YPAEITLTWQ RDGEDQTQDT
 ELVETRPAGD GTFQKWAAVV VPSGEEQRYT CHVQHEGLPK PLTLRWEPSS
 QPTIPIVGII AGLVLLGAVI TGAVVAAVMW RRKSSDRKGG SYSQAASSDS
 AQGSDVSLTA CKVX*   
>DL;IPD:MHC04210
IPD:MHC04210 Patr-A*21:01 366 bases
 MAVMAPRTLV LLLSGALALT QTWAGSHSMR YFYTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWIEQEG PEYWDQETRN VKAQAQTDRV
 DLGTLRGYYN QSEDGSHTIQ IMYGCDVGSD GRFLRGYRQD AYDGKDYIAL
 NEDLRSWTAA DMAAQITKRK WEAAHVAEQD RAYLEGTCVE WLRRYLENGK
 ETLQRADPPK THMTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQPTIPIVG IIAGLVLLGA VITGAVVAAV MWRRKSSDRK GGSYTQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC01096
IPD:MHC01096 Patr-A*22:01 366 bases
 MAVMAPRTLV LLLSGALALT QTWAGSHSMR YFSTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWIEQEG PEYWDRETRS VKASAQTDRA
 NLGTLRGYYN QSEDGSHTIQ LMFGCDVGSD GRFLRGYRQD AYDGKDYIAL
 NEDLRSWTAA DMAAQITQRK WEAVHAAEQQ RAYLEGRCVE SLRRYLENGK
 ETLQRTDPPK THMTHHPISD REATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQPTIPIVG IIAGLVLLGA VITGAVVAAV MWRRKSSDRK GGSYSQAASS
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC01991
IPD:MHC01991 Patr-A*24:01 181 bases
 SHSMRYFSTS VSRPGRGEPR FIAVGYVDDT QFVRFDSDAA SQRMEPRAPW
 IEQEGPEYWD RETRSVKAGA QTDRANLGTL RGYYNQSEDG SHTIQIMYGC
 DVGSDGRFLR GYRQDAYDGK DYIALNEDLR SWTAADMAAQ ITQRKWEAAH
 AAEQWRAYLE GTCVDGLRRY LENGKETLQR T* 
>DL;IPD:MHC04088
IPD:MHC04088 Patr-AL*01:01:01 366 bases
 MAVMAPRTLL LLLLGALALT QTWAGSHSMR YFFTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASKRME PRAPWMEQEE PEYWDQETQI SKVYAQNDRV
 NLGTLRGYYN QSEAGSHTIQ LMYGCDVGPD GRFLRGYRQY AYDGKDYIAL
 NEDLRSWTAA DMAARITKRK WEAARRAEQL RVYLKGRCVD WLRRYVENGK
 EMLQRTDAPK TRMTHHPVSD RETTLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGKEQR YTCLVQHEGL PEPLTLRWEP
 SSQPTIPIVG IIAGLVLFVA VITGAVVAAV MWRRKSSDRK GGSYFQAASN
 DSSQGSEVSL TACKVX*   
>DL;IPD:MHC04089
IPD:MHC04089 Patr-AL*01:01:02 366 bases
 MAVMAPRTLL LLLLGALALT QTWAGSHSMR YFFTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASKRME PRAPWMEQEE PEYWDQETQI SKVYAQNDRV
 NLGTLRGYYN QSEAGSHTIQ LMYGCDVGPD GRFLRGYRQY AYDGKDYIAL
 NEDLRSWTAA DMAARITKRK WEAARRAEQL RVYLKGRCVD WLRRYVENGK
 EMLQRTDAPK TRMTHHPVSD RETTLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGKEQR YTCLVQHEGL PEPLTLRWEP
 SSQPTIPIVG IIAGLVLFVA VITGAVVAAV MWRRKSSDRK GGSYFQAASN
 DSSQGSEVSL TACKVX*   
>DL;IPD:MHC04092
IPD:MHC04092 Patr-AL*01:01:03 366 bases
 MAVMAPRTLL LLLLGALALT QTWAGSHSMR YFFTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASKRME PRAPWMEQEE PEYWDQETQI SKVYAQNDRV
 NLGTLRGYYN QSEAGSHTIQ LMYGCDVGPD GRFLRGYRQY AYDGKDYIAL
 NEDLRSWTAA DMAARITKRK WEAARRAEQL RVYLKGRCVD WLRRYVENGK
 EMLQRTDAPK TRMTHHPVSD RETTLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGKEQR YTCLVQHEGL PEPLTLRWEP
 SSQPTIPIVG IIAGLVLFVA VITGAVVAAV MWRRKSSDRK GGSYFQAASN
 DSSQGSEVSL TACKVX*   
>DL;IPD:MHC04090
IPD:MHC04090 Patr-AL*01:02 366 bases
 MAVMAPRTLL LLLLGALALT QTWAGSHSMR YFFTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASKRME PRAPWIEQEE PEYWDQETQI SKVYAQNDRV
 NLGTLRGYYN QSEAGSHTIQ LMYGCDVGPD GRFLRGYRQY AYDGKDYIAL
 NEDLRSWTAA DMAARITKRK WEAARRAEQL RVYLKGRCVD WLRRYVENGK
 EMLQRTDAPK TRMTHHPVSD RETTLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGKEQR YTCLVQHEGL PEPLTLRWEP
 SSQPTIPIVG IIAGLVLFVA VITGAVVAAV MWRRKSSDRK GGSYFQAASN
 DSSQGSEVSL TACKVX*   
>DL;IPD:MHC04091
IPD:MHC04091 Patr-AL*01:03 366 bases
 MAVMAPRTLL LLLLGALALT QTWAGSHSMR YFFTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASKRME PRAPWMEQEE PEYWDQETQI SKVYAQNDRV
 NLGTLRGYYN QSEADSHTIQ LMYGCDVGPD GRFLRGYRQY AYDGKDYIAL
 NEDLRSWTAA DMAARITKRK WEAARRAEQL RVYLKGRCVD WLRRYVENGK
 EMLQRTDAPK TRMTHHPVSD RETTLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGKEQR YTCLVQHEGL PEPLTLRWEP
 SSQPTIPIVG IIAGLVLFVA VITGAVVAAV MWRRKSSDRK GGSYFQAASN
 DSSQGSEVSL TACKVX*   
