>DL;IPD:MHC00903
IPD:MHC00903 Patr-DRB*W8:01 82 bases
 LWQTKSECHF FNGTERVRYL DRYFYNQEEY VRFDSDVGEY RAVTELGRPD
 AEYWNSQKDF LEQKRGQVDN YCRHNYGVGE RF* 
>DL;IPD:MHC00849
IPD:MHC00849 Patr-DRB1*02:01 267 bases
 MLCLKLPGVS CMTALTVTLM VLSSPLALAG DTRSRFLLQP KGECHFFNGT
 ERVRFLERDI YNQEEFMRFD SDVGEYRAVT ELGRPVAEYC NSQKDILEQA
 RAAVDNYCRH NYGVGESFTV QRRVQPKVTV YPAKTQPLQH HNLLVCSVSG
 FYPGSIEVRW FLNGQEEKAG VVSTGLIQNG DWTFQTLVML ETVPRSGEVY
 TCQVEHPSVT SPLTVEWRAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGHSGLQ PTGFLSX*   
>DL;IPD:MHC00850
IPD:MHC00850 Patr-DRB1*02:02 267 bases
 MLCLKLPGVS CMTALTVTLM VLSSPLALAG DTRSRFLLQP KGECHFFNGT
 ERVRFLDRYF YNQEEFMRFD SDVGEYRAVT ELGRPVAEYC NSQKDFLEQA
 RAAVDNYCRH NYGAVESFTV QRRVQPKVTV YPAKTQPLQH HNLLVCSVSG
 FYPGSIEVRW FLNGQEEKAG VVSTGLIQNG DWTFQTLVML ETVPRSGEVY
 TCQVEHPSVT SPLTVEWRAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGHSGLQ PTGFLSX*   
>DL;IPD:MHC00851
IPD:MHC00851 Patr-DRB1*02:03 84 bases
 RFLLQPKGEC HFFNGTERVR FLERDIYNQE EFMRFDSDVG EYRAVTELGR
 PVAEYWNSQK DILEQARAAV DNYCRHNYGV GESF* 
>DL;IPD:MHC00852
IPD:MHC00852 Patr-DRB1*02:04 267 bases
 MLCLKLPGVS CMTALTVTLM VLSSPLALAG DTRSRFLLQP KGECHFFNGT
 ERVRFLHRYF YNQEEFMRFD SDVGEYRAVT ELGRPVAEYC NSQKDILEQA
 RAAVDNYCRH NYGVGESFTV QRRVQPKVTV YPAKTQPLQH HNLLVCSVSG
 FYPGSIEVRW FLNGQEEKAG VVSTGLIQDG DWTFQTLVML ETVPRSGEVY
 TCQVEHPSVT SPLTVEWRAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGHSGLQ PTGFLSX*   
>DL;IPD:MHC00853
IPD:MHC00853 Patr-DRB1*02:05 267 bases
 MLCLKLPGVS CMTALTVTLM VLSSPLALAG DTRSRFLLQP KRECHFFNGT
 ERVRFLDRYF YNQEEFMRFD SDVGEYRAVT ELGRPVAEYC NSQKDLLERR
 RAEVDTYCRH NYGVGESFTV QRRVQPKVTV YPAKTQPLQH HNLLVCSVSG
 FYPGSIEVRW FLNGQEEKAG VVSTGLIQNG DWTFQTLVML ETVPRSGEVY
 TCQVEHPSVT SPLTVEWRAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGHSGLQ PTGFLSX*   
>DL;IPD:MHC04396
IPD:MHC04396 Patr-DRB1*02:07 73 bases
 RFLLQPKGEC HFFNGTERVR FLHRYFYNQE EFMRFDSDVG EYRAVTELGR
 PVAEYCNSQK DILEHERAAV DTY*  
>DL;IPD:MHC04397
IPD:MHC04397 Patr-DRB1*02:08 73 bases
 RFLLQPKGEC HFFNGTERVR FLERDIYNQE EFMRFDSDVG EYRAVTELGR
 PVAEYCNSQK DILEHERAAV DNY*  
>DL;IPD:MHC04398
IPD:MHC04398 Patr-DRB1*02:09 73 bases
 RFLLQPKGEC HFFNGTERVR FLHRYFYNQE EFMRFDSDVG EYRAVTELGR
 PVAEYWNSQK DILEHERAAV DNY*  
>DL;IPD:MHC04399
IPD:MHC04399 Patr-DRB1*02:10 73 bases
 RFLLQPKGEC HFFNGTERVR FLERDIYNQE EFMRFDSDVG EYRAVTELGR
 PVAEYCNSQK DILEQAGAAV DTY*  
>DL;IPD:MHC00854
IPD:MHC00854 Patr-DRB1*02:13 82 bases
 LLQPKGECHF FNGTERVRFL ERDIYNQEEF MRFDSDVGEY RAVTELGRPV
 AEYCNSQKDL LERRRAEVDT VCRHNYGVGE SF* 
>DL;IPD:MHC01097
IPD:MHC01097 Patr-DRB1*02:14 267 bases
 MLCLKLPGVS CMTALTVTLM VLSSPLALAG DTRSRFLLQP KGECHFFNGT
 ERVRFLERYF YNQEEFMRFD SDVGEYRAVT ELGRPVAEYC NSQKDLLERR
 RAAVDNYCRH NYGAVESFTV QRRVQPKVTV YPAKTQPLQH HNLLVCSVSG
 FYPGSIEVRW FLNGQEEKAG VVSTGLIQNG DWTFQTLVML ETVPRSGEVY
 TCQVEHPSVT SPLTVEWRAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGHSGLQ PTGFLSX*   
>DL;IPD:MHC02926
IPD:MHC02926 Patr-DRB1*02:15 89 bases
 RFLLQPKGEC HFFNGTERVR FLERDIYNQE EFMRFDSDVG EYRAVTELGR
 PVAEYCNSQK DLLERRRAEV DNYCRHNYGA VESFTVQRR* 
>DL;IPD:MHC04400
IPD:MHC04400 Patr-DRB1*03:01 73 bases
 RFLEYSTSEC HFFNGTERVR FLDRYFHNQE DYVRFDSDVG EYRAVTELGR
 PVAESWNSQK DILEDSGATV DTY*  
>DL;IPD:MHC00855
IPD:MHC00855 Patr-DRB1*03:02 267 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALAG DTRPRFLEYS TSECHFFNGT
 ERVRFLDRYF HNQEEYVRFD SDVGEYRAVT ELGRPVAESW NSQKDILEDR
 RGQVDNYCRH NYGVGESFTV QRRVHPKVTV YPSKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKTG VVSTGLIQNG DWTFQTLVML ETVPQSGEVY
 TCQVEHPSVT SPLTVEWKAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGHSRLP PTGLLSX*   
>DL;IPD:MHC04402
IPD:MHC04402 Patr-DRB1*03:03 73 bases
 RFLEYSTSEC HFFNGTERVR FLDRYFHNQE EYVRFDSDVG EFRAVTELGR
 PDAEYWNSQK DILERRRAEV DTY*  
>DL;IPD:MHC04401
IPD:MHC04401 Patr-DRB1*03:04 73 bases
 RFLEYSTSEC HFFNGTERVR FLDRYFHNQE ESVRFDSDVG EFRAVTELGR
 PVAESWNSQK DYVEQKRGQV DNY*  
>DL;IPD:MHC00856
IPD:MHC00856 Patr-DRB1*03:05 267 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALAG DTRPRFLEYS TSECHFFNGT
 ERVRFLDRYF HNQEEYVRFD SDVGEFRAVT ELGRPVAEYW NSQKDLLEDR
 RGQVDNYCRH NYGAVESFTV QRRVHPKVTV YPSKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKTG VVSTGLIQNG DWTFQTLVML ETVPQSGEVY
 TCQVEHPSVT SPLTVEWKAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGHSRLP PTGLLSX*   
>DL;IPD:MHC00857
IPD:MHC00857 Patr-DRB1*03:06 82 bases
 LEYSTSECHF FNGTERVRFL DRYFYNQEEY VRFDSDVGEF RAVTELGRPD
 AEYWNSQKDL LEDRRGQVDN YCRHNYRVVE SF* 
>DL;IPD:MHC00858
IPD:MHC00858 Patr-DRB1*03:07:01 267 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALAG DTRPRFLEYS TSECHFFNGT
 ERVRFLDRYF HNQEESVRFD SDVGEFRAVT ELGRPDAEYW NSQKDYVEDE
 RAAVDTYCRH NYGVAESFTV QRRVHPKVTV YPSKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKTG VVSTGLIQNG DWTFQTLVML ETVPQSGEVY
 TCQVEHPSVT SPLTVEWRAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGHSRLP PTGLLSX*   
>DL;IPD:MHC02922
IPD:MHC02922 Patr-DRB1*03:07:02 267 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALAG DTRPRFLEYS TSECHFFNGT
 ERVRFLDRYF HNQEESVRFD SDVGEFRAVT ELGRPDAEYW NSQKDYVEDE
 RAAVDTYCRH NYGVAESFTV QRRVHPKVTV YPSKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKTG VVSTGLIQNG DWTFQTLVML ETVPQSGEVY
 TCQVEHPSVT SPLTVEWKAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGHSRLP PTGLLSX*   
>DL;IPD:MHC00859
IPD:MHC00859 Patr-DRB1*03:08 267 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALAG DTRPRFLEYS TSECHFFNGT
 ERVRYLDRYF YNQEEYVRFD SDVGEFRAVT ELGRPVAEYY NSQKDYVEDE
 RAAVDTYCRH NYGVGESFTV QRRVHPKVTV YPSKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKTG VVSTGLIQNG DWTFQTLVML ETVPRSGEVY
 TCQVEHPSVT SPLTVEWKAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGHSRLP PTGLLSX*   
>DL;IPD:MHC00860
IPD:MHC00860 Patr-DRB1*03:09 267 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALAG DTRPRFLEYS TSECHFFNGT
 ERVRFLDRYF YNQEEYVRFD SDVGEFRAVT ELGRPDAEYW NSQKDYVEDE
 RAAVDTYCRH NYGVAESFTV QRRVHPKVTV YPSKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKTG VVSTGLIQNG DWTFQTLVML ETVPRSGEVY
 TCQVEHPSVT SPLTVEWKAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGHSGLQ PTGFLSX*   
>DL;IPD:MHC00861
IPD:MHC00861 Patr-DRB1*03:10 82 bases
 LEYSTSECHF FNGTERVRFL DRYFYNQEES VRFDSDVGEF RAVTELGRPD
 AEYWNSQKDL LEDRRGQVDN YCRHNYGAVE SF* 
>DL;IPD:MHC01448
IPD:MHC01448 Patr-DRB1*03:11 267 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALAG DTRPRFLEYS TSECHFFNGT
 ERVRFLDRYF YNQEEYVRFD SDVGEFRAVT ELGRPDAEYW NSQKDLLEDR
 RGQVDNYCRH NYRVGESFTV QRRVHPKVTV YPSKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKTG VVSTGLIQNG DWTFQTLVML ETVPQSGEVY
 TCQVEHPSVT SPLTVEWKAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGHSRLP PTGLLSX*   
>DL;IPD:MHC01449
IPD:MHC01449 Patr-DRB1*03:12 89 bases
 RFLEYSTSEC HFFNGTERVR FLDRYFYNQE EYVRFDSDVG EFRAVTELGR
 PSAEYYNSQK DYVEDERAAV DTYCRHNYGV AESFTVQRR* 
>DL;IPD:MHC02973
IPD:MHC02973 Patr-DRB1*03:13 86 bases
 RFLEYSTSEC HFFNGTERVR FLDRYFHNQE EYVRFDSDVG EYRAVTELGR
 PVAEYWNSQK DLLEDRRGQV DNYCRHNYGA VESFTV* 
>DL;IPD:MHC02974
IPD:MHC02974 Patr-DRB1*03:14 82 bases
 LEYSTSECHF FNGTERVRFL DRYFYNQEEY VRFDSDVGEF RAVTELGRPD
 AEYWNSQKDL LEDRRGQVDT YCRHNYGVVE SF* 
>DL;IPD:MHC01995
IPD:MHC01995 Patr-DRB1*03:16 75 bases
 SECHFFNGTE RVRFLDRYFH NQEEYVRFDS DVGEYRAVTE LGRPVAESWN
 SQKDLLEDRR GQVDNYCRHN YGVGE*  
>DL;IPD:MHC00862
IPD:MHC00862 Patr-DRB1*07:01 267 bases
 MVCLKLPGGS CMVALTVTLM VLSSPLALAG DTQPRFLWQS KYKCHFFNGT
 ERVQFLERLF YNQEEFVRFD SDVGEYRAVT ELGRPVAESW NSQKDLLEDR
 RGQVDTVCRH NYGVLESFIV QRRVHPEVTV YPAKTQPLQH HNLLVCSVSG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQNG DWTFQTLVML ETVPRSGEVY
 ICQVEHPSVM SPLTVQWRAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGHSGLQ PTGFLSX*   
>DL;IPD:MHC00863
IPD:MHC00863 Patr-DRB1*07:02 267 bases
 MVCLKLPGGS CMVALTVTLM VLSSPLALAG DTQPRFLWQG KYKCHFFNGT
 ERVQFLERLF YNQEEFVRFD SDVGEYRAVT ELGRPVAESW NSQKDLLEDR
 RGQVDTVCRH NYGVGESFTV QRRVHPEVTV YPAKTQPLQH HNLLVCSVSG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQNG DWTFQTLVML ETVPRSGEVY
 ICQVEHPSVM SPLTVQWRAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGHSGLQ PTGFLSX*   
>DL;IPD:MHC00864
IPD:MHC00864 Patr-DRB1*10:01 267 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALAG DTRPRFLEQA KCECHFFNGT
 ERVRFLERRI HNQEEDVRFD SDVGEYRAVT ELGRPDAEYW NSQKDILAQR
 RADVDTFCRH NYGVGESFTV QRRVEPKVTV YPAKTQPLQH HNLLVCSVSG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQNG DWTFQTLVML ETVPQSGEVY
 TCQVEHPSVT SPLTVEWRAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGHSGLQ PTGLLSX*   
>DL;IPD:MHC00865
IPD:MHC00865 Patr-DRB3*01:02 267 bases
 MVCLKLPGGS SLAALTVTLM VLSSRLAFAG DTRPRFLELH KSECHFFNGT
 ERVRYLDRYF HNQEEFLRFD SDVGEYRAVT ELGRPVAESW NSQKDYVEQK
 RGQVDNYCRH NYRVGESFTV QRRVLPKVTV YPAKTQPLQH HNLLVCSVSG
 FYPGSIEVRW FQNGQEEKTG VVSTGLIQNG DWTFQTLVML ETVPRSGEVY
 TCQVEHPSVT SPLTVEWRAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGHSGLQ PTGFLSX*   
>DL;IPD:MHC02923
IPD:MHC02923 Patr-DRB3*01:03 267 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALSG DTRPRFLELV KSECHFFNGT
 ERVRFLERYF HNQEEFLRFD SDVGEYRAVT ELGRPVAESW NSQKDYVEQK
 RGQVDNYCRH NYRVGESFTV QRRVHPQVTV YPAKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQNG DWTFQTLVML ETVPRSGEVY
 TCQVEHPSVM SPLTVEWRAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGHSGLQ PTGFLSX*   
>DL;IPD:MHC00866
IPD:MHC00866 Patr-DRB3*02:01 267 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALSG DTRPRFLELV KSECHFFNGT
 ERVRFLERYF YNQEEYVRFD SDVGEYRAVT EPGRPVAESW NSQKDLLEQK
 RGQVDNYCRH NYGAVESFTV QRRVHPQVTV YPAKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQNG DWTFQTLVML ETVPRSGEVY
 TCQVEHPSVM SPLTVEWRAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGHSGLQ PTEFLSX*   
>DL;IPD:MHC00867
IPD:MHC00867 Patr-DRB3*02:07 89 bases
 RFLELVKSEC HFFNGTERVR FLERYFYNQE EYVRFDSDVG EYRAVTELGR
 PVAESWNSQK DLLEQKRGQV DNYCRHNYGA VESFTVQRR* 
>DL;IPD:MHC00868
IPD:MHC00868 Patr-DRB3*02:08 89 bases
 RFLELVKSEC HFFNGTERVR FLERYFYNQE EYVRFDSDVG EYRAVTELGR
 PVAESWNSQK DLLEQKRGQV DNYCRHNYGA VESFTVQRR* 
>DL;IPD:MHC00869
IPD:MHC00869 Patr-DRB3*02:09 82 bases
 LELVKSECHF FNGTERVRFL ERHFYNQEEY VRFDSDVGEY RAVTELGRPV
 AESWNSQKDL LEQKRGQVDN YCRHNYRAVE SF* 
>DL;IPD:MHC00870
IPD:MHC00870 Patr-DRB3*02:10 82 bases
 LELVKSECHF FNGTERVRFL ERYFYNQEEY FRFDSDVGEY RAVTELGRPV
 AESWNSQKDL LEQKRAKVDN YCRHNYGAVE SF* 
>DL;IPD:MHC00871
IPD:MHC00871 Patr-DRB3*02:11 82 bases
 LEPVKSECHF FNGTERVRFL ERYFYNQEEY VRFDSDVGEY RAVTELGRPV
 AESWNSQKDL LEQKRAKVDN YCRHNYGAVE SF* 
>DL;IPD:MHC00872
IPD:MHC00872 Patr-DRB3*02:12 82 bases
 LELVKSECHF FNGTERVRFL ERYFYNQEEY VRFDSDVGEY RAVTELGRPV
 AESWNSQKDL LEQKRARVDN YCRHNYGAVE SF* 
>DL;IPD:MHC00873
IPD:MHC00873 Patr-DRB3*02:13 82 bases
 LELVKSECHF FNGTERVRFL ERYFYNQEEY VRFDSDVGEY RAVTELGRPV
 AESWNSQKDL LEQKRAKVDN YCRHNYGAVE SF* 
>DL;IPD:MHC00874
IPD:MHC00874 Patr-DRB3*02:14 267 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALSG DTRPRFLELV KSECHFFNGT
 ERVRFLERYF YNQEEYVRFD SDVGEYRAVT ELGRPSAEYW NSQKDYVEQK
 RGQVDNYCRH NYRVGESFTV QRRVLPKVTV YPAKTQPLQH HNLLVCSVSG
 FYPGSIEVRW FQNGQEEKTG VVSTGLIQNG DWTFQTLVML ETVPRSGEVY
 TCQVEHPSVT SPLTVEWRAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGHSGLQ PTGFLSX*   
>DL;IPD:MHC00875
IPD:MHC00875 Patr-DRB3*02:15 82 bases
 LELVKSECHF FNGTERVRFL ERYFYNQEEY VRFDSDVGEY RAVTELGRPS
 AEYWNSQKDY VEQKRAKVDN YCRHNYRVGE SF* 
>DL;IPD:MHC02919
IPD:MHC02919 Patr-DRB3*07:01 267 bases
 MVCLKLPGGS SLAALTVTLM VLSSRLAFAG DTRPRFLEQA KAECHFFNGT
 ERVRFLERYF YNQEEYVRFD SDVGEFRAVT ELGRPSAEYW NSQKDLLEQK
 RGQVDNYCRH NYGVVESFTV QRRVHPQVTV YPAKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQNG DWTFQTLVML ETVPRSGEVY
 TCQVEHPSVT SPLTVEWRAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGHSGLQ PTGFLSX*   
>DL;IPD:MHC02920
IPD:MHC02920 Patr-DRB3*07:02 267 bases
 MVCLKLPGGS CMAALTVTLM VLSSPLALSG DTRPRFLEQA KAECHFFNET
 ERVQYLKRYF YNQEEYVRFD SDVGEFRAVT ELGRPSAEYW NSQKDLLEQK
 RGQVDNYCRH NYRVGESFTV QRRVHPQVTV YPAKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQNG DWTFQTLVML ETVPRSGEVY
 TCQVEHPSVT SPLTVEWRAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGHSGLQ PTGFLSX*   
>DL;IPD:MHC00906
IPD:MHC00906 Patr-DRB3*07:03 89 bases
 RFLEQAKAEC HFFNGTERVR FLERYFYNQE EYVRFDSDVG EFRAVTELGR
 PDAEYWNSQK DLLEQKRGQV DNYCRHNYGV VESFTVQRR* 
>DL;IPD:MHC00907
IPD:MHC00907 Patr-DRB3*07:04 82 bases
 LEQAKAELHF FNGTERVRFL ERYFYNQEEY VRFDSDVGEF RAVTELGRPD
 AEYWNSQKDL LEQKRAKVDN YCRHNYGVGE SF* 
>DL;IPD:MHC00908
IPD:MHC00908 Patr-DRB3*07:05 82 bases
 LEQAKAECHF FNETERVQYL KRYFHNQEEF VRFDSDVGEF RAVTELGRPD
 AEYWNSQKDL LEQKRGQVDN YCRHNYGVVE SF* 
>DL;IPD:MHC00876
IPD:MHC00876 Patr-DRB4*01:04N 89 bases
 RFLEQAKHEC HFLNGTERVW NLIRYIYNQE EYARYNSDLG EYQAVTELGR
 PDAKYWNSQK DLLERTRAEV DTYCRYNYGV VESFTVQRX* 
>DL;IPD:MHC00877
IPD:MHC00877 Patr-DRB4*01:05 89 bases
 RFLEQAKHEC HFLNGTERVW NLIRYIYNQE EYARYNSDLG EYQAVTELGR
 PDAKYWNSQK DLLERTRAEV DTYCRHNYGA VESFTVQRR* 
>DL;IPD:MHC00878
IPD:MHC00878 Patr-DRB4*01:06 82 bases
 LEQAKHECHF LNGTERVWNL IRYIYNQEEY ARYNSDLGEY QAVTELGRPD
 AKYWNSQKDL LERTRAEVDT YCRHNYGVVE SF* 
>DL;IPD:MHC00879
IPD:MHC00879 Patr-DRB4*01:07 82 bases
 LEQAKHECHF LNGTEWVWNL IRYIYNQEEY ARYNSDLGEY QAVTELGRPD
 AKYWNSQKDL LERTRAEVDT YCRYNYGVVE SF* 
>DL;IPD:MHC00880
IPD:MHC00880 Patr-DRB4*02:01 267 bases
 MVCLKLPGGS CMAALTVTLM VLSFPLALAG DTRPRFLEQL KFECHFFNGT
 QRVRLLERYF YNQEEYARYN SDLGEYRAVT ELGRPDAVYW NSQKDLLEQR
 RAAVDTYCRH NYGVVESFTV QRQVHPKVTV YPSKTQPLQH HNLLVCSVSG
 FYPGSIEVRW FRNGQEEKTG VVSTGLIQNG DWTFQTLVML ETVPRSGEVY
 TCQVEHPSMM SPLTVEWRAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGHSGLQ PTGFLSX*   
>DL;IPD:MHC00881
IPD:MHC00881 Patr-DRB5*01:01 267 bases
 MVCLKLPGGS YMAVLTVTLM VLSSPLALAG DTRPRFLKQD KYECHFFNGT
 ERVRYLHRGI YNQEENVRFD SDVGEYRAVT ELGRPDAEYW NSQKDILERR
 RAAVDTYCRH NYGVAESFTV QRRVHPKVTV YPAKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQNG DWTFQILVML ETVPRSGEVY
 TCQVEHPSVM SPLTVEWRAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 KNQKGHSGLH PTGLVSX*   
>DL;IPD:MHC00882
IPD:MHC00882 Patr-DRB5*01:02 267 bases
 MVCLKLPGGS YMAVLTVTLM VLSSPLALAG DTRPRFLKQD KYECHFFNGT
 ERVRYLHRDI YNQEENVRFD SDVGEYRAVT ELGRPVAEYW NSQKDILERR
 RAAVDTYCRH NYGVAESFTV QRRVHPKVTV YPAKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQNG DWTFQILVML ETVPRSGEVY
 TCQVEHPSVM SPLTVEWRAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 KNQKGHSGLH PTGLVSX*   
>DL;IPD:MHC02924
IPD:MHC02924 Patr-DRB5*01:03 267 bases
 MVCLKLPGGS YMAVLTVTLM VLSSPLALAG DTRPRFLKQD KYECHFFNGT
 ERVRYLHRDI YNQEENVRFD SDVGEYRAVT ELGRPDAEYW NSQKDILERR
 RAAVDTYCRH NYGVAESFTV QRRVHPKVTV YPAKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQNG DWTFQILVML ETVPRSGEVY
 TCQVEHPSVM SPLTVEWRAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 KNQKGHSGLH PTGLVSX*   
>DL;IPD:MHC00883
IPD:MHC00883 Patr-DRB5*03:01 267 bases
 MVCLKLPGGS YMAVLTVTLI VLSSPLALAG DTRPRFLKQD KYECHFFNGT
 ERVRFLHRGI YNQEEDLRFD SDVGEYRAVT ELGRPDAEYW NSQKDILERR
 RADVDTFCRH NYGVLESFTV QRRVHPKVTV YPAKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQNG DWTFQILVML ETVPRSGEVY
 TCQVEHPSVT SPLTVEWRAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 KNQKGHSGLH PTGLVSX*   
>DL;IPD:MHC00884
IPD:MHC00884 Patr-DRB5*03:04 267 bases
 MVCLKLPGGS YMAVLTVTLI VLSSPLALAG DTRPRFLKQE KYECHFFNGT
 ERVRFLHRGI YNQEEDLRFD SDVGEYRAVT ELGRPVAEYW NSQKDILERR
 RADVDTFCRH NYGVLESFTV QRRVHPKVTV YPAKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQNG DWTFQILVML ETVPRSGEVY
 TCQVEHPSMT SPLTVEWRAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 KNQKGHSGLH PTGLVSX*   
>DL;IPD:MHC00885
IPD:MHC00885 Patr-DRB5*03:05 82 bases
 LKQDKCECHF FNGTERVRFL HRDIYNQEED LRFDSDVGEY RAVTELGRPD
 AEYWNSQKDI LERRRAAVDT YCRHNYGVLE SF* 
>DL;IPD:MHC00886
IPD:MHC00886 Patr-DRB5*03:06 267 bases
 MVCLKLPGGS YMAVLTVTLM VLSSPLALAG DTRPRFLKQD KCECHFFNGT
 ERVRFLHRDI YNQEEDLRFD SDVGEYRAVT ELGRPDAEYW NSQKDILERR
 RAAVDTYCRH NYGVLESFTV QRRVHPKVTV YPAKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQNG DWTFQILVML ETVPRSGEVY
 TCQVEHPSVM SPLTVEWRAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 KNQKGHSGLH PTGLVSX*   
>DL;IPD:MHC00887
IPD:MHC00887 Patr-DRB5*03:07 267 bases
 MVCLKLPGGS YMAVLTVTLI VLSSPLALAG DTRPRFLKQD KSECHFFNGT
 ERVRFLHRDI YNQEEDLRFD SDVGEYRAVT ELGRPDAEYW NSQKDILERR
 RAAVDTYCRH NYGVLESFTV QRRVHPKVTV YPAKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQNG DWTFQILVML ETVPRSGEVY
 TCQVEHPSVT SPLTVEWRAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 KNQKGHSGLH PTGLVSX*   
>DL;IPD:MHC00888
IPD:MHC00888 Patr-DRB5*03:08 82 bases
 LKQDKYECHF FNGTERVRFL HRYFYNQEED LRFDSDVGEY RAVTELGRPD
 AEYWNSQKDI LERRRAAVDT YCRHNYGVGE SF* 
>DL;IPD:MHC00889
IPD:MHC00889 Patr-DRB5*03:09 89 bases
 RFLKQDKYEC HFFNGTERVR FLHRYFYNQE EDLRFDSDVG EYRAVTELGR
 PDAEYWNSQK DILERRRAEV DTYCRHNYGV GESFTVQRR* 
>DL;IPD:MHC00890
IPD:MHC00890 Patr-DRB5*03:10 267 bases
 MVCLKLPGGS YMAVLTVTLI VLSSPLALAG DTRPRFLKQD KYECHFFNGT
 ERVRFLHRYF YNQEEDLRFD SDVGEYRAVT ELGRPDAEYW NSQKDILERR
 RAEVDTYCRH NYGVGESFTV QRRVHPKVTV YPAKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQNG DWTFQILVML ETVPRSGEVY
 TCQVEHPSMT SPLTVEWRAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 KNQKGHSGLH PTGLVSX*   
>DL;IPD:MHC00891
IPD:MHC00891 Patr-DRB5*03:11 82 bases
 LKQDKCECHF FNGTERVRFL HRDIYNQEED LRFDSDVGEY RAVTELGRPD
 AEYWNSQKDI LEQARAAVDT YCRHNYGVLE SF* 
>DL;IPD:MHC01095
IPD:MHC01095 Patr-DRB5*03:12 267 bases
 MVCLKLPGGS YMAVLTVTLI VLSSPLALAG DTRPRFLKQD KYECHFFNGT
 ERVRFLHRYF YNQEEDLRFD SDVGEYRAVT ELGRPDAEYW NSQKDILERR
 RAEVDTYCRH NYGVLESFTV QRRVHPKVTV YPAKTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQNG DWTFQILVML ETVPRSGEVY
 TCQVEHPSVT SPLTVEWRAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 KNQKGHSGLH PTGLVSX*   
>DL;IPD:MHC02925
IPD:MHC02925 Patr-DRB5*03:13 267 bases
 MVCLKLPGGS YMAVLTVTLM VLSSPLALAG DTRPRFLKQD KHECHFFNGT
 ERVRFLHRDI YNQEEDLRFD SDVGEYRAVT ELGRPDAEYW NSQKDILERR
 RAAVDTYCRH NYGVLESFTV QRRVEPKVTV YPARTQPLQH HNLLVCSVNG
 FYPGSIEVRW FRNGQEEKAG VVSTGLIQNG DWTFQILVML ETVPRSGEVY
 TCQVEHPSVT SPLTVEWRAR SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGHSGLH PTGLVSX*   
>DL;IPD:MHC00892
IPD:MHC00892 Patr-DRB6*01:05N 81 bases
 RFLEKAKCEC HIFNGTKRVQ YLNRYIHKRE ENLRFDSDVE EFQAVTELGR
 PVAENWNSQK GILEEKRDKV DILQIQLRGF X* 
>DL;IPD:MHC00893
IPD:MHC00893 Patr-DRB6*01:06N 78 bases
 EKAKCECHIF NGTKRVQYLN RYIHKREENL RFDSDVEEFQ AVTELGRPVA
 ENWNSQKGIL EEKRDKVDIL QIQLRGFX*  
>DL;IPD:MHC00894
IPD:MHC00894 Patr-DRB6*01:07N 78 bases
 EKAKCECHIF NGTKRVQYLN RYIHKREENL RFDSDVEEFQ AVTELGRPVA
 ENWNSQKGIL EEKRDKVDIL QIQLRGFX*  
>DL;IPD:MHC00895
IPD:MHC00895 Patr-DRB6*01:09N 81 bases
 RFLEKAKCEC HIFNGTKRVQ YLNRYIHKRE ENLRFDSDVE EFQAVTELGR
 PVAENWNSQK GILEEKRDKV DILQIQLRGF X* 
>DL;IPD:MHC00896
IPD:MHC00896 Patr-DRB6*01:10N 81 bases
 LEKAKCECHI FNGTKRVQYL NRYIHKREEN LRFDSDVEEF QAVTELGRPV
 AENWNSQKGI LEEKRDKVDI LQTQLRGFLE L* 
>DL;IPD:MHC00897
IPD:MHC00897 Patr-DRB6*03:01N 79 bases
 EQAKCECHIF NGTERVQYLN RYIHKREENL RFDSDVEEFQ AVTELGQPVA
 ENWNSQKGIL EEKRDKVDTY CRYNYRVFX*  
>DL;IPD:MHC00898
IPD:MHC00898 Patr-DRB6*03:02N 80 bases
 LEQAKCECHI FNGTERVQYL NRYIHKREEN LRFDSDVEEF QAVTELGQPV
 AENWNSQKGI LEEKRDKVDT YCRYNYRVFX * 
>DL;IPD:MHC00899
IPD:MHC00899 Patr-DRB6*03:03N 80 bases
 LEQAKCECHI FNGTERVQYL NRYIHKREEN LRFDSDVEEF QAVTEPGQPV
 AENWNSQKGI LEEKRDKVDT YCRYNYRVFX * 
>DL;IPD:MHC00900
IPD:MHC00900 Patr-DRB6*03:04N 80 bases
 LEQAKCECHI FNGTERVQYL NRYIHKREEN ARFDSDVEEF RAVTELGQPV
 AENWNSQRGI LEEKRDKVDT YCRYNYRVFX * 
>DL;IPD:MHC00901
IPD:MHC00901 Patr-DRB6*03:05N 82 bases
 RFLEQAKCEC HIFNGTERVQ YLNRYIHKRE ENLRFDSDVE EFQAVTELGQ
 PVAENWNSQK GILEEKRDKV DTYCRYNYRV FX* 
>DL;IPD:MHC00902
IPD:MHC00902 Patr-DRB7*01:01N 21 bases
 RFLEQAKSEC HFFNGTERYL X*  
