>DL;IPD:MHC00803
IPD:MHC00803 Patr-DPB1*01 249 bases
 CTTTTCCAGG TACGGCAGGA ATGCTACGCG TTTAATGGGA CACAGCGCTT
 CCTGGAGGGA TACATCTACA ACCGGGAGGA GTTCGTGCGC TTCGACAGCG
 ACGTGGGGGA GTTCCGGGCG GTGACGGAGC TGGGGCGGCC TGCTGCGGAG
 TACTGGAACA GCCAGAAGGA CCTCCTGGAG GAGGAGCGGG CAGTGCCGGA
 CAGGATGTGC AGACACAACT ACGAGCTGGA CGAGGCCGTG ACCCTGCAG*
>DL;IPD:MHC00804
IPD:MHC00804 Patr-DPB1*02 249 bases
 CTTTTCCAGG TACGGCAGGA ATGCTACGCG TTTAATGGGA CACAGCGCTT
 CCTGGAGAGA TACATCTACA ACCGGGAGGA GTTCGTGCGC TTCGACAGCG
 ACGTGGGGGA GTTCCGGGCG GTGACGGAGC TGGGGCGGCC TGCTGCGGAG
 TACTGGAACA GCCAGAAGGA CCTCCTGGAG GAGGAGCGGG CAGTGCCGGA
 CAGGATGTGC AGACACAACT ACGAGCTGGG CGAGGCCGTG ACCCTGCAG*
>DL;IPD:MHC00805
IPD:MHC00805 Patr-DPB1*03 249 bases
 CTTTTCCAGG TACGGCAGGA ATGCTACGCG TTTAATGGGA CACAGCGCTT
 CCTGGAGAGA TACATCTACA ACCGGGAGGA GTTCGCGCGC TTCGACAGCG
 ACGTGGGGGA GTTCCGGGCG GTGACGGAGC TGGGGCGGCC TGCTGCGGAG
 TACTGGAACA GCCAGAAGGA CCTCCTGGAG GAGGAGCGGG CAGTGCCGGA
 CAGGATGTGC AGACACAACT ACGAGCTGGA CGAGGCCGTG ACCCTGCAG*
>DL;IPD:MHC00806
IPD:MHC00806 Patr-DPB1*04 257 bases
 AGAATTACCT TTTCCAGGTA CGGCAGGAAT GCTACGCGTT TAATGGGACA
 CAGCGCTTCC TGGAGAGATA CATCTACAAC CGGGAGGAGT TCGTGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 CTGCGGAGTA CTGGAACAGC CAGAAGGACC TCCTGGAGGA GGAGCGGGCA
 GTGCCGGACA GGATGTGCAG ACACAACTAC GAGCTGGACG AGGCCGTGAC
 CCTGCAG*    
>DL;IPD:MHC00807
IPD:MHC00807 Patr-DPB1*05 249 bases
 GTGTACCAGG GACGGCAGGA ATGCTACGCG TTTAATGGGA CACAGCGCTA
 CCTGGAGAGA TACATCTACA ACCGGGAGGA GTACGCGCGC TTCGACAGCG
 ACGTGGGGGA GTTCCGGGCG GTGACGGAGC TGGGGCGGCC TGCTGCGGAG
 TACAGGAACA GCCAGAAGGA CCTCCTGGAG GAGAAGCGGG CAGTGCCGGA
 CAGGATGTGC AGACACAACT ACGAGCTGGA CGAGGCCGTG ACCCTGCAG*
>DL;IPD:MHC00808
IPD:MHC00808 Patr-DPB1*06 249 bases
 GTGTACCAGG GACGGCAGGA ATGCTACGCG TTTAATGGGA CACAGCGCTA
 CCTGGAGAGA TACATCTACA ACCGGGAGGA GTTCGCGCGC TTCGACAGCG
 ACGTGGGGGA GTTCCGGGCG GTGACGGAGC TGGGGCGGCC TGCTGCGGAG
 TACTGGAACA GCCAGAAGGA CCTCCTGGAG GAGAAGCGGG CAGTGCCGGA
 CAGGATGTGC AGACACAACT ACGAGCTGAA CGAGGCCGTG ACCCTGCAG*
>DL;IPD:MHC00809
IPD:MHC00809 Patr-DPB1*07 249 bases
 GAGTACCAGG GACGGCAGGA ATGCTACGCG TTTAATGGGA CACAGCGCTA
 CCTGGAGAGA TACATCTACA ACCGGGAGGA GTACGCGCGC TTCGACAGCG
 ACGTGGGGGA GTTCCGGGCG GTGACGGAGC TGGGGCGGCC TGCTGCGGAG
 TACTGGAACA GCCAGAAGGA CCTCCTGGAG GAGAAGCGGG CAGTGCCGGA
 CAGGATGTGC AGACACAACT ACGAGCTGGA CGAGGCCGTG ACCCTGCAG*
>DL;IPD:MHC00810
IPD:MHC00810 Patr-DPB1*08 249 bases
 GTGTACCAGG GACGGCAGGA ATGCTACGCG TTTAACGGGA CACAGCGCTT
 CCTGGAGAGA TACATCTACA ACCGGGAGGA GTACGCGCGC TTCGACAGCG
 ACGTGGGGGA GTTCCGGGCG GTGACGGAGC TGGGGCGGCC TGATGCGGAG
 TACTGGAACA GCCAGAAGGA CCTCCTGGAG GAGAAGCGGG CAGTGCCGGA
 CAGGATGTGC AGACACAACT ACGAGCTGAA CGAGCCGTTG ACCCTGCAG*
>DL;IPD:MHC00811
IPD:MHC00811 Patr-DPB1*09 249 bases
 GTGTACCAGG GACGGCAGGA ATGCTACGCG TTTAATGGGA CACAGCGCTA
 CCTGGAGAGA TACATCTACA ACCGGGAGGA GTACGCGCGC TTCGACAGCG
 ACGTGGGGGA GTTCCGGGCG GTGACGGAGC TGGGGCGGCC TGCTGCGGAG
 TACTGGAACA GCCAGAAGGA CCTCCTGGAG GAGAAGCGGG CAGTGCCGGA
 CAGGATGTGC AGGTCGACTT ACGAGCTGGA CGAGGCCGTG ACCCTGCAG*
>DL;IPD:MHC00812
IPD:MHC00812 Patr-DPB1*10 257 bases
 AGAATTACGT GTACCAGGGA CGGCAGGAAT GCTACGCGTT TAATGGGACA
 CAGCGCTACC TGGAGAGATA CATCTACAAC CGGGAGGAGT ACGCGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 CTGCGGAGTA CTGGAACAGC CAGAAGGACC TCCTGGAGGA GAAGCGGGCA
 GTGCCGGACA GGATGTGCAG ACACAACTAC GAGCTGGACG AGGCCGTGAC
 CCTGCAG*    
>DL;IPD:MHC00813
IPD:MHC00813 Patr-DPB1*11 257 bases
 AGAATTACGT GTACCAGGGA CGGCAGGAAT GCTACGCGTT TAACGGGACA
 CAGCGCTTCC TGGAGAGATA CATCTACAAC CGGGAGGAGT ACGCGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 ATGCGGAGTA CTGGAACAGC CAGAAGGACC TCCTGGAGGA GAAGCGGGCA
 GTGCCGGACG GGATGTGCAG ACACAACTAC GAGCTGGACG AGGCCGTGAC
 CCTGCAG*    
>DL;IPD:MHC00814
IPD:MHC00814 Patr-DPB1*12 249 bases
 GTGTACCAGG GACGGCAGGA ATGCTACGCG TTTAATGGGA CACAGCGCTT
 CCTGGAGAGA TACATCTACA ACCGGGAGGA GTACGCGCGC TTCGACAGCG
 ACGTGGGGGA GTTCCGGGCG GTGACGGAGC TGGGGCGGCC TGCTGCGGAG
 TACTGGAACA GCCAGAAGGA CCTCCTGGAG GAGAAGCGGG CAGTGCCGGA
 CAGGATGTGC AGACACAACT ACGAGCTGAA CGAGGCCGTG ACCCTGCAG*
>DL;IPD:MHC00815
IPD:MHC00815 Patr-DPB1*13 257 bases
 AGAATTACGT GTACCAGGGA CGGCAGGAAT GCTACGCGTT TAATGGGACA
 CAGCGCTACC TGGAGAGATA CATCTACAAC CGGGAGGAGT ACGCGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 CTGCGGAGTA CTGGAACAGC CAGAAGGACC TCCTGGAGGA GAAGCGGGCA
 GTGCCGGACA GGATGTGCAG ACACAACTAC GAGCTGAACG AGGCCGTGAC
 CCTGCAG*    
>DL;IPD:MHC00816
IPD:MHC00816 Patr-DPB1*14 249 bases
 GTGTACCAGG TACGGCAGGA ATGCTACGCG TTTAATGGGA CACAGCGCTT
 CCTGGAGAGA TACATCTACA ACCGGGAGGA GTACGCGCGC TTCGACAGCG
 ACGTGGGGGA GTTCCGGGCG GTGACGGAGC TGGGGCGGCC TGCTGCGGAG
 TACTGGAACA GCCAGAAGGA CCTCCTGGAG GAGAAGCGGG CAGTGCCGGA
 CAGGATCTGC AGGTCCAACT ACGAGCTGGA CGAGGCCGTG ACCCTGCAG*
>DL;IPD:MHC00817
IPD:MHC00817 Patr-DPB1*15 249 bases
 GTGTACCAGG GACGGCAGGA ATGCTACGCG TTTAATGGGA CACAGCGCTT
 CCTGGAGAGA TACATCTACA ACCGGGAGGA GTACGCGCGC TTCGACAGCG
 ACGTGGGGGA GTTCCGGGCG GTGACGGAGC TGGGGCGGCC TGCTGCGGAG
 TACTGGAACA GCCAGAAGGA CCTCCTGGAG GAGAAGCGGG CAGTGCCGGA
 CAGGATGTGC AGACACAACT ACGAGCTGGA CGAGGCCGTG ACCCTGCAG*
>DL;IPD:MHC00818
IPD:MHC00818 Patr-DPB1*16 257 bases
 AGAATTACGT GTACCAGGGA CGGCAGGAAT GCTACGCGTT TAATGGGACA
 CAGCGCTTCC TGGAGAGATA CATCTACAAC CGGGAGGAGT ACGCGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 CTGCGGAGTA CTGGAACAGC CAGAAGGACC TCCTGGAGGA GAAGCGGGCA
 GTGCCGGACA GGATCTGCAG ACACAACTAC GAGCTGGACG AGGCCGTGAC
 CCTGCAG*    
>DL;IPD:MHC00819
IPD:MHC00819 Patr-DPB1*17 257 bases
 AGAATTACGT GTACCAGGTA CGGCAGGAAT GCTACGCGTT TAACGGGACA
 CAGCGCTTCC TGGAGAGATA CATCTACAAC CGGGAGGAGT ACGCGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 CTGCGGAGTA CTGGAACAGC CAGAAGGACC TCCTGGAGGA GGAGCGGGCA
 GTGCCGGACG GGATGTGCAG ACACAACTAC GAGCTGAACG AGGCCGTGAC
 CCTGCAG*    
>DL;IPD:MHC00820
IPD:MHC00820 Patr-DPB1*18 257 bases
 AGAATTACGT GTACCAGGTA CGGCAGGAAT GCTACGCGTT TAATGGGACA
 CAGCGCTACC TGGAGAGATA CATCTACAAC CGGGAGGAGT ACGCGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 CTGCGGAGTA CTGGAACAGC CAGAAGGACC TCCTGGAGGA GAAGCGGGCA
 GTGCCGGACA GGATGTGCAG ACACAACTAC GAGCTGAACG AGGCCGTGAC
 CCTGCAG*    
>DL;IPD:MHC00821
IPD:MHC00821 Patr-DPB1*19 257 bases
 AGAATTACCT TTTCCAGGGA CGGCAGGAAT GCTACGCGTT TAATGGGACA
 CAGCGCTTCC TGGAGAGATA CATCTACAAC CGGGAGGAGT TCGTGCGCTT
 CGACAGCGAC ATGAGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 ATGCGGAGTA CTGGAACAGC CAGAAGGACC TCCTGGAGGA GAAGCGGGCA
 GTGCCGGACA GGATGTGCAG ACACAACTAC GAGCTGGTCG GGGCCATGAC
 CCTGCAG*    
>DL;IPD:MHC00822
IPD:MHC00822 Patr-DPB1*20 257 bases
 AGAATTACCT TTTCCAGGGA CGGCAGGAAT GCTACGCGTT TAATGGGACA
 CAGCGCTTCC TGGAGAGATA CATCTACAAC CGGGAGGAGA TCGCGCGCTT
 CGACAGCGAC GTGAGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 ATGCGGAGTA CTGGAACAGC CAGAAGGACC TCCTGGAGGA GAAGCGGGCA
 GTGCCGGACA GGATGTGCAG ACACAACTAC GAGCTGGTCG GGGCCATGAC
 CCTGCAG*    
>DL;IPD:MHC00823
IPD:MHC00823 Patr-DPB1*21 257 bases
 AGAATTACGT GTACCAGGTA CGGCAGGAAT GCTACGCGTT TAATGGGACA
 CAGCGCTTCC TGGAGAGATA CATCTACAAC CGGGAGGAGT ACGCGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 ATGCGGAGTA CTGGAACAGC CAGAAGGACC TCCTGGAGGA GAAGCGGGCA
 GTGCCGGACA GGATCTGCAG ACACAACTAC GAGCTGGACG AGGCCGTGAC
 CCTGCAG*    
>DL;IPD:MHC00824
IPD:MHC00824 Patr-DPB1*22 257 bases
 AGAATTACGT GTACCAGGTA CGGCAGGAAT GCTACGCGTT TAATGGGACA
 CAGCGCTTCC TGGAGAGATA CATCTACAAC CGGGAGGAGT ACGCGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 CTGCGGAGTA CTGGAACAGC CAGAAGGACC TCCTGGAGGA GAAGCGGGCA
 GTGCCGGACA GGATCTGCAG ACACAACTAC GAGCTGGACG AGGCCGTGAC
 CCTGCAG*    
>DL;IPD:MHC00825
IPD:MHC00825 Patr-DPB1*23 257 bases
 AGAATTACGT GTACCAGGGA CGGCAGGAAT GCTACGCGTT TAACGGGACA
 CAGCGCTTCC TGGAGAGATA CATCTACAAC CGGGAGGAGT ACGCGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 ATGCGGAGTA CTGGAACAGC CAGAAGGACC TCCTGGAGGA GAAGCGGGCA
 GTGCCGGACA GGATGTGCAG ACACAACTAC GAGCTGGACG AGGCCGTGAC
 CCTGCAG*    
>DL;IPD:MHC00826
IPD:MHC00826 Patr-DPB1*24 257 bases
 AGAATTACGT GTACCAGGGA CGGCAGGAAT GCTACGCGTT TAATGGGACA
 CAGCGCTACC TGGAGAGATA CATCTACAAC CGGGAGGAGT ACGCGCGCTT
 TGACAGCGGC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGACGGCCTG
 CTGCGGAGTA CTGGAACAGC CAGAAGGACC TCCTGGAGGA GAAGCGGGCA
 GTGCCGGACG GGATGTGCAG ACACAACTAC GAGCTGAACG AGGCCGTGAC
 CCTGCAG*    
>DL;IPD:MHC00827
IPD:MHC00827 Patr-DPB1*25 257 bases
 AGAATTACGT GTACCAGGGA CGGCAGGAAT GCTACGCGTT TAATGGGACA
 CAGCGCTACC TGGAGAGATA CATCTACAAC CGGGAGGAGT ACGCGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 CTGCGGAGTA CTGGAACAGC CAGAAGGACC TCCTGGAGGA GAAGCGGGCA
 GTGCCGGACA GGATCTGCAG ACACAACTAC GAGCTGGACG AGGCCGTGAC
 CCTGCAG*    
>DL;IPD:MHC00828
IPD:MHC00828 Patr-DPB1*26 257 bases
 AGAATTACGT GTACCAGGGA CGGCAGGAAT GCTACGCGTT TAATGGGACA
 CAGCGCTTCC TGGAGAGATA CATCTACAAC CGGGAGGAGT ACGCGCGCTT
 CGACAGTGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 CTGCGGAGTA CTGGAACAGC CAGAAGGACC TCCTGGAGGA GAAGCGGGCA
 GTGCCGGACA GGATCTGCAG ACACAACTAC GAGCTGGACG AGGCCGTGAC
 CCTGCAG*    
>DL;IPD:MHC00829
IPD:MHC00829 Patr-DPB1*27 257 bases
 AGAATTACGT GTACCAGGTA CGGCAGGAAT GCTACGCGTT TAACGGGACA
 CAGCGCTTCC TGGAGAGATA CATCTACAAC CGGGAGGAGT ACGCGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 CTGCGGAGTA CTGGAACAGC CAGAAGGACC TCCTGGAGGA GGAGCGGGCA
 GTGCCGGACA GGATCTGCAG ACACAACTAC GAGCTGAACG AGGCCGTGAC
 CCTGCAG*    
>DL;IPD:MHC00830
IPD:MHC00830 Patr-DPB1*28 257 bases
 AGAATTACGT GTACCAGGTA CGGCAGGAAT GCTACGCGTT TAATGGGACA
 CAGCGCTTCC TGGAGAGATA CATCTACAAC CGGGAGGAGT ACGCGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 CTGCGGAGTA CTGGAACAGC CAGAAGGACC TCCTGGAGGA GGAGCGGGCA
 GTGCCGGACG GGGTGTGCAG ACACAACTAC GAGCTGGACG AGGCCGTGAC
 CCTGCAG*    
>DL;IPD:MHC01447
IPD:MHC01447 Patr-DPB1*29 264 bases
 AGAATTACCT TTTCCAGGTA CGGCAGGAAT GCTACGCGTT TAATGGGACA
 CAGCGCTTCC TGGAGAGATA CATCTACAAC CGGGAGGAGT TCGTGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 ATGCGGAGTA CTGGAACAGC CAGAAGGACC TCCTGGAGGA GAAGCGGGCA
 GTGCCGGACA GGATCTGCAG ACACAACTAC GAGCTGGACG AGGCCGTGAC
 CCTGCAGCGC CGAG*   
