>DL;IPD:MHC00797
IPD:MHC00797 Patr-DMB*01 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESSCL LDDAGTPKDF TYCISFNKDL
 LTCWDPEENK MAPCEFGVLN SLANFLSQHL NQQDTLMQRL RNGLQNCATH
 TQPFWGSLTN RTRPPSVQVA KTTPFNTREP VMLACYVWGF YPAEVTITWR
 KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL ALTPSYGDTY TCVVEHIGAP
 EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW RRAGHSSYTP
 LPGSNYSEGR HIS*   
>DL;IPD:MHC00798
IPD:MHC00798 Patr-DMB*02 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESSCL LDDAGTPKDF TYCISFNKDL
 LTCWDPEENK MAPCEFGVLN SLANFLSQHL NQQDTLMQRL RNGLQNCATH
 TQPFWGSLTN RTRPPSVQVA KTTPFNTREP VMLACYVWGF YPAEVTITWR
 KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL ALTPSYGDTY TCVVEHIGAP
 EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW RRAGHSSYTP
 LPGSNYSEGW HIS*   
