>DL;IPD:MHC00912
IPD:MHC00912 Patr-H*01 360 bases
 MAPRTLLLLL SGTLALTQTW ARSHSMRYFY TTMSRPGRGE PRFISVGYVD
 DTQFVRFDSD DASPREEPRA PWMEREGPEY WDRNTQICKA QAQTERENLR
 MALRYYNQSE GCSHTMQVMY GCDVGPDGRF LRGYEQHAYD GKDYIALNED
 LSSWTAADMA AQITKRKWEA ARRPEQLRAY LEGEFVEWLR RYLENGKETL
 QRADPPKTHM THHPISDHEA TLRCWALGFY PAEITLTWQR DGEDQTQDTE
 LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP LTLRWEPSSQ
 PTVPIVGIVA GLVLLVAVVT GAVVAAVMWR KKSSDRKGGS YSQAASSNSA
 QGSDVSLMAX *   
