>DL;IPD:MHC00912
IPD:MHC00912 Patr-H*01 1090 bases
 TCATGGCGCC CCGAACCCTC CTCCTGCTGC TCTCAGGGAC CCTGGCCCTG
 ACCCAGACTT GGGCGCGCTC CCACTCCATG AGGTATTTCT ACACCACCAT
 GTCCCGGCCC GGCCGCGGGG AGCCCCGCTT CATCTCCGTC GGCTACGTGG
 ACGATACGCA GTTCGTGCGG TTTGACAGCG ACGACGCGAG TCCGAGAGAG
 GAGCCGCGGG CGCCGTGGAT GGAGCGGGAG GGGCCGGAGT ATTGGGACCG
 GAACACACAG ATCTGCAAGG CCCAGGCACA GACTGAACGA GAGAACCTGC
 GGATGGCGCT CCGCTACTAC AACCAGAGCG AGGGCTGTTC TCACACCATG
 CAGGTGATGT ATGGCTGCGA CGTGGGGCCC GACGGGCGCT TCCTCCGCGG
 GTATGAACAG CACGCCTACG ACGGCAAGGA TTACATCGCT CTGAACGAGG
 ACCTGAGCTC CTGGACCGCG GCGGACATGG CAGCTCAGAT CACCAAGCGC
 AAGTGGGAGG CGGCCCGTCG GCCGGAGCAG TTGAGAGCCT ACCTGGAGGG
 CGAGTTCGTG GAGTGGCTCC GCAGATACCT GGAGAACGGG AAGGAGACGC
 TGCAGCGCGC GGACCCCCCC AAGACACATA TGACCCACCA CCCCATCTCT
 GACCATGAGG CCACCCTGAG GTGCTGGGCC CTGGGCTTCT ACCCTGCGGA
 GATCACACTG ACCTGGCAGC GGGATGGGGA GGACCAGACC CAGGACACGG
 AGCTCGTGGA GACCAGGCCT GCAGGGGATG GAACCTTCCA GAAGTGGGCG
 GCTGTGGTGG TGCCTTCTGG AGAGGAGCAG AGATACACCT GCCATGTGCA
 GCATGAGGGT CTGCCCGAGC CCCTCACTCT GAGATGGGAG CCATCTTCCC
 AGCCCACCGT CCCCATCGTG GGCATCGTTG CTGGCCTGGT TCTACTTGTA
 GCTGTGGTCA CTGGAGCTGT GGTCGCTGCT GTAATGTGGA GGAAGAAGAG
 CTCAGATAGA AAAGGAGGGA GCTACTCTCA GGCTGCAAGC AGCAACAGTG
 CCCAGGGCTC TGATGTGTCT CTCATGGCTT GAAAGTGTGA *
