>DL;IPD:MHC00909
IPD:MHC00909 Patr-E*01:01:01:01 582 bases
 TCTCGGAGGC CCTGGCCCTT ACCCAGACCT GGGCGGGCTC CCACTCCTTG
 AAGTATTTCC ACACTTCCGT GTCCCGGCCC GGCCGCGGGG AGCCCCGCTT
 CATCTCTGTG GGCTACGTGG ACGACACCCA GTTCGTGCGC TTCGACAACG
 ACGCCGCGAG TCCGAGGATG GTGCCGCGGG CGCCGTGGAT GGAGCAGGAG
 GGGTCAGAGT ATTGGGACCG GGAGACACGG AGCGCCAGGG ACACCGCACA
 GATTTTCCGA GTGAACCTGC GGACCCTGCG CGGGTACTAC AATCAGAGCG
 AGGCCGGGTC TCACACCCTG CAGTGGATGC ATGGCTGCGA CCTGGGGCCC
 GACGGGCGCT TCCTCCGCGG GTATGAACAG TTCGCCTACG ACGGCAAGGA
 TTATCTCACC CTGAATGAGG ACCTGCGCTC CTGGACCGCG GTGGACACGG
 CGGCTCAGAT CTCCGAGCGA AAGTCAAATG ATGCCTGTGA GGCGGAGCAC
 CAGAGAGCCT ACCTGGAAGA CACATGCGTG GAGTGGCTCC ACAAATACCT
 GGAGAAGGGG AAGGAGACGC TGCTTCACCT GG* 
>DL;IPD:MHC00910
IPD:MHC00910 Patr-E*01:01:01:02 582 bases
 TCTCGGAGGC CCTGGCCCTT ACCCAGACCT GGGCGGGCTC CCACTCCTTG
 AAGTATTTCC ACACTTCCGT GTCCCGGCCC GGCCGCGGGG AGCCCCGCTT
 CATCTCTGTG GGCTACGTGG ACGACACCCA GTTCGTGCGC TTCGACAACG
 ACGCCGCGAG TCCGAGGATG GTGCCGCGGG CGCCGTGGAT GGAGCAGGAG
 GGGTCAGAGT ATTGGGACCG GGAGACACGG AGCGCCAGGG ACACCGCACA
 GATTTTCCGA GTGAACCTGC GGACCCTGCG CGGGTACTAC AATCAGAGCG
 AGGCCGGGTC TCACACCCTG CAGTGGATGC ATGGCTGCGA CCTGGGGCCC
 GACGGGCGCT TCCTCCGCGG GTATGAACAG TTCGCCTACG ACGGCAAGGA
 TTATCTCACC CTGAATGAGG ACCTGCGCTC CTGGACCGCG GTGGACACGG
 CGGCTCAGAT CTCCGAGCGA AAGTCAAATG ATGCCTGTGA GGCGGAGCAC
 CAGAGAGCCT ACCTGGAAGA CACATGCGTG GAGTGGCTCC ACAAATACCT
 GGAGAAGGGG AAGGAGACGC TGCTTCACCT GG* 
