>DL;IPD:MHC02209
IPD:MHC02209 Patr-DRA1*01:01 683 bases
 AAGAACATGT GATCATCCAG GCCGAGTTCT ATCTGAATCC TGACCAATCA
 GGCGAGTTTA TGTTTGACTT TGATGGTGAT GAGATTTTCC ACGTGGATAT
 GGCAAAGAAG GAGACGGTCT GGCGGCTTGA AGAATTTGGA CGATTTGCCA
 GCTTTGAGGC TCAAGGTGCA TTGGCCAACA TAGCTGTGGA CAAAGCCAAC
 CTGGAAATCA TGACAAAGCG CTCCAACTAT ACTCCGATCA CCAATGTACC
 TCCAGAGGTA ACTGTGCTCA CAAACAGCCC TGTGGAACTG AGAGAGCCCA
 ACATCCTCAT CTGTTTCATC GACAAGTTCA CCCCACCAGT GGTCAATGTC
 ACGTGGCTTC GAAATGGAAA ACCTGTCACC ACAGGAGTGT CAGAGACAGT
 CTTCCTGCCC AGGGAAGACC ACCTTTTCCG CAAGTTCCAC TATCTCCCCT
 TCCTGCCCTC AACTGAGGAC GTTTACGACT GCAGGGTGGA ACACTGGGGC
 TTGGATGAGC CTCTTCTCAA GCACTGGGAG TTTGATGCTC CAAGCCCTCT
 CCCAGAGACT ACAGAGAACG TGGTGTGTGC CCTGGGCCTG ACTGTGGGTC
 TGGTGGGCAT CATCATTGGG ACCATCTTCA TCATCAAGGG TGTGCGCAAA
 AGCAATGCAG CAGAACGCAG GGGGCCTCTG TGA* 
>DL;IPD:MHC02210
IPD:MHC02210 Patr-DRA1*01:02 683 bases
 AAGAACATGT GATCATCCAG GCCGAGTTCT ATCTGAATCC TGACCAATCA
 GGCGAGTTTA TGTTTGACTT TGATGGTGAT GAGATTTTCC ACGTGGATAT
 GGCAAAGAAG GAGACGGTCT GGCGGCTTGA AGAATTTGGA CGATTTGCCA
 GCTTTGAGGC TCAAGGTGCA TTGGCCAACA TAGCTGTGGA CAAAGCCAAC
 CTGGAAATCA TGACAAAGCG CTCCAACTAT ACTCCGATCA CCAATGTACC
 TCCAGAGGTA ACTGTGCTCA CAAACAGCCC TGTGGAACTG AGAGAGCCCA
 ACATCCTCAT CTGTTTCATC GACAAGTTCA CCCCACCAGT GGTCAATGTC
 ACGTGGCTTC GAAATGGAAA ACCTGTCACC ACAGGAGTGT CAGAGACAGT
 CTTCCTGCCC AGGGAAGACC ACCTTTTCCG CAAGTTCCAC TATCTCCCCT
 TCCTGCCCTC AACTGAGGAC GTTTATGACT GCAGGGTGGA ACACTGGGGC
 TTGGATGAGC CTCTTCTCAA GCACTGGGAG TTTGATGCTC CAAGCCCTCT
 CCCAGAGACT ACAGAGAACG TGGTGTGTGC CCTGGGCCTG ACTGTGGGTC
 TGGTGGGCAT CATCATTGGG ACCATCTTCA TCATCAAGGG TGTGCGCAAA
 AGCAATGCAG CAGAACGCAG GGGGCCTCTG TGA* 
