>DL;IPD:MHC00731
IPD:MHC00731 Patr-B*01:01 364 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMR YFYTSVSRPG RGEPRFITVG
 YVDDTQFVRF DSDAASPRME PRAPWIEQEG PEYWDRETRN MKASAQTDRE
 NLRIALRYYN QSEAGSHTWQ TMYGCDMGPD GRLLRGYGQY AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAAREAEQR RAYLEGTCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPE GDRTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQSTIPIVG IVAGLAVLVV TVAVVAVVAA VMCRRKSSGG KGGSYSQAAS
 SDSAQGSDVS LTAX*   
>DL;IPD:MHC02972
IPD:MHC02972 Patr-B*01:02 181 bases
 SHSMRYFYTS VSRPGRGEPR FITVGYVDDT QFVRFDSDAA SPRMEPRAPW
 IEQEGSEYWD RETRNMKASA QTDRENLRIA LRYYNQSEAG AHTWQTMYGC
 DMGPDGRLLR GYGQYAYDGK DYIALNEDLS SWTAADTAAQ ITQRKWEAAR
 EAEQRRAYLE GTCVEWLRRY LENGKETLQR A* 
>DL;IPD:MHC00732
IPD:MHC00732 Patr-B*02:01 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMK YFYTAVSRPG RGEPRFISVG
 YVDDTQFVWF DSDAASPREE PRAPWIEQEG PEYWDRETQI SKTNAQTYRE
 SLRNLRGYYN QSEAGSHIIQ RMYGCDMGPD GRLLRGYEQY AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAARWAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVIGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC01430
IPD:MHC01430 Patr-B*02:03 191 bases
 ALALTETWAG SHSMRYFYTA VSRPGRGEPR FISVGYVDDT QFVWFDSDAA
 SPREEPRAPW IEQEGPEYWD RETQISKTNA QTYRESLRNL RGYYNQSEAG
 SHIIQRMYGC DMGPDGRLLR GYEQYAYDGK DYIALNQDLS SWTAADTAAQ
 ITQRKWEAAR WAEQLRAYLE GTCVEWLRRY LENGKETLQR A*
>DL;IPD:MHC00733
IPD:MHC00733 Patr-B*03:01 364 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMR YFDTAVSRPG RGEPRFITVG
 YVDDTQFVRF DSDAASPRME PRAPWIEQEG PEYWDRETRN VKASAQTDRE
 NLRIALRYYN QSEAGSHTWQ TMFGCDMGPD GRLLRGYYQY AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAARAAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRADPPK THMTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPE GDRTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQSTIPIVG IVAGLAVLVV TVAVVAVVAA VLCRRKSSGG KGGSYSQAAS
 SDSAQGSDVS LTAX*   
>DL;IPD:MHC00734
IPD:MHC00734 Patr-B*03:02 364 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMR YFDTAVSRPG RGEPRFITVG
 YVDDTQFVRF DSDAASPRME PRAPWIEQEG PEYWDRETRN VKASAQTDRE
 NLRIALRYYN QSEAGSHTWQ TMFGCDMGPD GRLLRGYYQY AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAARAAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPE GDRTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQSTIPIVG IVAGLAVLVV TVAVVAVVAA VLCRRKSSGG KGGSYSQAAS
 SDSAQGSDVS LTAX*   
>DL;IPD:MHC00735
IPD:MHC00735 Patr-B*04:01 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMK YFYTAVSRPG RGEPRFITVG
 YVDDTQFVWF DSDAASPRKE PRTPWIEQEG PEYWDRETQI SKTNAQTYRV
 GLRNLLRYYN QSEAGSHTWQ TMFGCDVGPD GRLLRGYRQY AYDGKDYIAL
 NQDLSSWTAA DTAAQITQRK WEAARVAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVIGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC02056
IPD:MHC02056 Patr-B*04:02 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMK YFYTAVSRPG RGEPRFITVG
 YVDDTQFVWF DSDAASPRKE PRTPWIEQEG PEYWDRETQI SKTNAQTYRV
 GLRNLRGYYN QSEAGSHTWQ TMFGCDVGPD GRLLRGYRQY AYDGKDYIAL
 NQDLSSWTAA DTAAQITQRK WEAARVAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVIGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00736
IPD:MHC00736 Patr-B*05:01 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMK YFYTAVSRPG RGEPRFISVG
 YVDDTQFVWF DSDAASPREE PRAPWIEQEG PEYWDRETQI SKTNAQTYRE
 SLRNLRGYYN QSEAGSHIIQ RMYGCDMGPD GRLLRGYEQY AYDGKDYIAL
 NQDLSSWTAA DTAAQITQRK WEAARWAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVIGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00737
IPD:MHC00737 Patr-B*05:02 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMK YFYTAVSRPG RGEPRFISVG
 YVDDTQFVWF DSDAASPREE PRAPWIEQEG PEYWDRETQI SKTNAQTYRE
 SLRNLRGYYN QSEAGSHIIQ RMYGCDMGPD GRLLRGYEQY AYDGKDYIAL
 NQDLSSWTAA DTAAQITQRK WEAARRAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVIGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00738
IPD:MHC00738 Patr-B*06:01 355 bases
 VLLLLSAALA LTETWAGSHS MRYFYTAVSR PGRGEPRFIS VGYVDDTQFV
 RFDSDAASPR MEPRAPWIEQ EGPEYWDRET RNVKASAQTD RGSLANLRGY
 YNQSEAGSHT WQTMYGCDVG PDGRLLRGYD QYAYDGKDYI ALNEDLSSWT
 AADTAAQITQ RKWEAARVAE QWRAYLEGLC VEWLRRYLEN GKETLQRADP
 PKTHVTHHPI SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDTELVETR
 PAGDRTFQKW AAVVVPSGQE QRYTCHVQHE GLLEPLTLRW EPSSQSTIPI
 VGIVAGLAVL AVVVTGAVVA AVMCRRKSSG GKGGSYSQAA SSDSAQGSDV
 SLTAX*    
>DL;IPD:MHC04211
IPD:MHC04211 Patr-B*06:02 181 bases
 SHSMRYFDTA VSRPGRGEPR FISVGYVDDT QFVRFDSDAA SPRMEPRAPW
 IEQEGPEYWD RETRNVKASA QTDRVGLRNL RGYYNQSEAG SHTWQTMYGC
 DVGPDGRLLR GYYQYAYDGK DYIALNEDLS SWTAADTAAQ ITQRKLEAAR
 AAEQLRAYLE GLCVEWLRRY LENGKETLQR A* 
>DL;IPD:MHC00739
IPD:MHC00739 Patr-B*07:01 355 bases
 VLLLLSAALA LTETWAGSHS MKYFLTSVSR PGRGEPRFIT VGYVDDTQFV
 RFDSDAASPR MEPRAPWIEQ EGPEYWDRET RNVKASAQTY RENLRIALRY
 YFQSEDGSHT LQTMYGCDVG PDGRFLRGYR QFAYDGKDYI ALNEDLSSWT
 AADTAAQITQ RKWEAARVAE QHRAYLEGLC VEWLRRYLEN GKETLQRADP
 PKTHVTHHPI SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDTELVETR
 PAGDRTFQKW AAVVVPSGQE QRYTCHVQHE GLPEPLTLRW EPSSQSTIPI
 VGIVAGLAVL AVVVTGAVVA AVMCRRKSSG GKGGSYSQAA SSDSAQGSDV
 SLTAX*    
>DL;IPD:MHC01101
IPD:MHC01101 Patr-B*07:02 181 bases
 SHSMKYFLTS VSRPGRGEPR FITVGYVDDT QFVRFDSDAA SPRMEPRAPW
 IEQEGPEYWD RETRNVKAFA QTYRENLRIA LRYYNQSEDG SHTIQTMFGC
 DVGPDGRLLR GYRQYAYDGK DYIALNEDLS SWTAADTAAQ ITQRKWEAAR
 VAEQHRAYLE GLCVEWLRRY LENGKETLQR A* 
>DL;IPD:MHC00740
IPD:MHC00740 Patr-B*08:01 355 bases
 LLLLLWGAVA LTETWAGSHS MRYFYTAMSR PGGGEPRFIA VGYVDDTQFV
 RFDSDAAIPR MEPRAPWIEQ EGPEYWDRET QISKTNAQTY RVGLRNLRGY
 YNQSEAGSHT WQTMYGCDVG PDGRLLRGYR QFAYDGKDYI ALNKDLSSWT
 AADTAAQITQ RKWEAARWAE QLRAYLEGTC VEWLRRYLEN GKETLQRADP
 PKTHVTHHPI SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDTELVETR
 PAGDRTFQKW AAVVVPSGEE QRYTCHVQHE GLPKPLTLRW EPSSQSTIPI
 VGIVAGLAVL AVVVIGAVVA AVMCRRKSSG GKGGSYSQAA SSDSAQGSDV
 SLTAX*    
>DL;IPD:MHC00741
IPD:MHC00741 Patr-B*08:02 355 bases
 LLLLLWGAVA LTETWAGSHS MRYFYTAMSR PGRGEPRFIA VGYVDDTQFV
 RFDSDAAIPR MEPRAPWIEQ EGPEYWDRET QISKTNAQTY RVGLRNLRGY
 YNQSEAGSHT WQTMYGCDVG PDGRLLRGYR QFAYDGKDYI ALNKDLSSWT
 AADTAAQITQ RKWEAARWAE QLRAYLEGTC VEWLRRYLEN GKETLQRADP
 PKTHVTHHPI SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDTELVETR
 PAGDRTFQKW AAVVVPSGEE QRYTCHVQHE GLPKPLTLRW EPSSQSTIPI
 VGIVAGLAVL AVVVIGAVVA AVMCRRKSSG GKGGSYSQAA SSDSAQGSDV
 SLTAX*    
>DL;IPD:MHC00742
IPD:MHC00742 Patr-B*09:01 356 bases
 VLLLLSAALA LTETWAGSHS MRYFYTSVSR PGRGEPRFIT VGYVDDTQFV
 RFDSDAASPR MEPRAPWIEQ EGPEYWDRET RNMKASAQTD RENLRIALRY
 YNQSEAGSHI IQRMYGCDMG PDGRLLRGYY QYAYDGKDYI ALNEDLSSWT
 AADTAAQITQ RKWEAARAAE QRRAYLEGTC VEWLRRYLEN GKETLQRADP
 PKTHVTHHPI SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDTELVETR
 PEGDRTFQKW AAVVVPSGEE QRYTCHVQHE GLPKPLTLRW EPSSQSTIPI
 VGIVAGLAVL VVTVAVVAVV AAVLCRRKSS GGKGGSYSQA ASSDSAQGSD
 VSLTAX*    
>DL;IPD:MHC00743
IPD:MHC00743 Patr-B*10:01 364 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMR YFYTSVSRPG RGEPRFITVG
 YVDDTQFVRF DSDAASPRME PRAPWIEQEG PEYWDRETRN MKASAQTDRE
 NLRIALRYYN QSEAGSHTWQ TMYGCDMGPD GRLLRGYGQY AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAAREAEQR RAYLEGTCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPE GDRTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQSTIPIVG IVAGLAVLVV TVAVVAVVAA VMCRRKSSGG KGGSYSQAAS
 SDSAQGSDVS LTAX*   
>DL;IPD:MHC00744
IPD:MHC00744 Patr-B*11:01 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMR YFYTSVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAASPREE PRAPWMEQEG PEYWDRNTQI YKAQAQTDRV
 GLGNLRGYYN QSEAGSHTWQ TMYGCDVGPD GRLLRGYDQY AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAAREAEQR RAYLEGLCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGQEQR YTCHVQHEGL PKPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVTGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00745
IPD:MHC00745 Patr-B*11:02 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMR YFYTSVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAASPREE PRAPWMEQEG PEYWDRNTQI YKAQAQTDRV
 GLGNLRGYYN QSEAGSHTWQ TMYGCDVGPD GRLLRGYDQY AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAARVAEQW RAYLEGLCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGQEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVTGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00746
IPD:MHC00746 Patr-B*12:01 147 bases
 FDSDAASPRE EPRAPWMEQE GPEYWDRNTQ IYKAQAQTDR GSLGNLRGYY
 NQSEAGSHTL QRMYGCDVGP DGRLLRGYYQ DAYDGKDYIA LNEDLSSWTA
 ADTAAQITQR KWEAARVAEQ HRAYLEGLCV EWLRRYLENG KETLQRA*
>DL;IPD:MHC00747
IPD:MHC00747 Patr-B*12:02 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMR YFYTSVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAASPREE PRAPWMEQEG PEYWDRNTQI CKAQAQTDRG
 SLGNLRGYYN QSEAGSHTLQ RMYGCDVGPD GRLLRGYYQD AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAARVAEQH RAYLEGLCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGQEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVTGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00748
IPD:MHC00748 Patr-B*13:01 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMR YFYTSVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAASPREE PRAPWMEQEG PEYWDRNTQI YKAQAQTDRV
 SLGNLRGYYN QSEAGSHTLQ SMYGCDVGPD GRLLRGYEQY AYDGKDYIAL
 NQDLSSWTAA DTAAQITQRK WEAARVAEQR RAYLEGTCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVIGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00749
IPD:MHC00749 Patr-B*14:01 363 bases
 MRVTAPRTLL LLLWGAVALT ETWAGSQSMR YFYTAMSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAAIPRME PRAPWIEQEG PEYWDRNTQG IKTQAQTDRE
 NLRTLLRYYN QSEAGSHTLQ SMYGCDMGPD GRLLRGYDQY AYDGKDYIAL
 NKDLSSWTAA DTAAQITQRK WEAARVAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVIGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00750
IPD:MHC00750 Patr-B*15:01 147 bases
 FDSDAASPRE EPRAPWIEQE GPEYWDRETQ ISKTNAQTYR ESLRTLRGYY
 NQSEAGSHII QRMYGCDMGP DGRLLRGYEQ YAYDGKDYIA LNQDLSSWTA
 ADTAAQITQR KWEAARWAEQ LRAYLEGTCV EWLRRYLENG KETLQRA*
>DL;IPD:MHC00751
IPD:MHC00751 Patr-B*16:01:01 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMK YFYTAVSRPG RGEPRFITVG
 YVDDTQFVWF DSDAASPRKE PRTPWIEQEG PEYWDRETQI SKTNAQTDRV
 SLRNLLRYYN QSEAGSHTWQ TMFGCDVGPD GRLLRGYRQY AYDGKDYIAL
 NQDLSSWTAA DTAAQITQRK WEAARVAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVIGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00752
IPD:MHC00752 Patr-B*16:01:02 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMK YFYTAVSRPG RGEPRFITVG
 YVDDTQFVWF DSDAASPRKE PRTPWIEQEG PEYWDRETQI SKTNAQTDRV
 SLRNLLRYYN QSEAGSHTWQ TMFGCDVGPD GRLLRGYRQY AYDGKDYIAL
 NQDLSSWTAA DTAAQITQRK WEAARVAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVIGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00753
IPD:MHC00753 Patr-B*16:02 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMK YFYTAVSRPG RGEPRFITVG
 YVDDTQFVWF DSDAASPRKE PRTPWIEQEG PEYWDRETQI SKTNAQTDRE
 SLRNLLRYYN QSEAGSHTWQ TMFGCDVGPD GRLLRGYRQY AYDGKDYIAL
 NQDLSSWTAA DTAAQITQRK WEAARVAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVIGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00754
IPD:MHC00754 Patr-B*17:01 363 bases
 MMVIAPRTVL LLLSAALALT ETWAGSHSMK YFYTSVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAASPRVE PRAPWMEQEG PEYCDRETQI FKTNTQTDRV
 SLGNLGGYYN QSEAGSHTLQ TMYGCDMGPD GRLLRGYYQY AYDGKDYLAL
 NEDLRSWTAA DTPAQISQRK FEAAGAAEQL RAYLEGTCVE WLRRYLENGK
 EMLQRADPPK THVTHHPISD HEVTLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQSTVPIVG IVAGLAVLAV VVIGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00755
IPD:MHC00755 Patr-B*17:02 363 bases
 MMVIAPRTVL LLLSAALALT ETWAGSHSMK YFYTSVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAASPRVE PRAPWMEQEG PEYCDRETQI FKTNTQTDRG
 SLGNLRGYYN QSEAGSHTLQ TMYGCDMGPD GRLLRGYYQY AYDGKDYLAL
 NEDLRSWTAA DTPAQISQRK FEAAGAAEQL RAYLEGTCVE WLRRYLENGK
 EMLQRADPPK THVTHHPISD HEVTLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQSTVPIVG IVAGLAVLAV VVIGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00756
IPD:MHC00756 Patr-B*17:03 363 bases
 MMVIAPRTVL LLLSAALALT ETWAGSHSMK YFFTSVSRPG RGEPRFITVG
 YVDDTQFVRF DSDAASPRVE PRAPWIEQEG PEYWDRQTQI SKTNAQTDRG
 SLGNLRGYYN QSEAGSHTLQ TMYGCDMGPD GRLLRGYYQY AYDGKDYLAL
 NEDLRSWTAA DTPAQISQRK FEAAGAAEQL RAYLEGTCVE WLRRYLENGK
 EMLQRADPPK THVTHHPISD HEVTLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQSTVPIVG IVAGLAVLAV VVIGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00757
IPD:MHC00757 Patr-B*18:01 364 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMK YFFTSVSRPG RGEPRFITVG
 YVDDTQFVRF DSDAASPRME PRAPWIEQEG PEYWDRETRN VKASAQTDRE
 NLRIALRYYN QSEAGSHIIQ RMYGCDVGPD GRLLRGYYQS AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAAREAEQR RAYLEGTCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPE GDRTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQSTIPIVG IVAGLAVLVV TVAVVAVVAA VMCRRKSSGG KGGSYSQAAS
 SDSAQGSDVS LTAX*   
>DL;IPD:MHC00758
IPD:MHC00758 Patr-B*19:01 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMR YFYTSVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAASPREE PRAPWMEQEG PEYWDRNTQI YKAQAQTDRE
 NLRIALRYYN QSEAGSHTLQ TMYGCDVGPD GRLLRGYYQD AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAAREAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGQEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVTGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC04212
IPD:MHC04212 Patr-B*19:02 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMR YFYTSVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAASPREE PRAPWMEQEG PEYWDRNTQI YKAQAQTDRE
 NLRIALRYYN QSEAGSHTLQ TMYGCDVGPD GRLLRGYYQD AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGQEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVTGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00759
IPD:MHC00759 Patr-B*20:01 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMR YFYTAVSRPG RGEPRFITVG
 YVDDTQFVRF DSDAASPRME PRAPWIEQEG PEYWDRETRN VKASAQTDRE
 NLRIALRYYN QSEAGSHTWQ TMYGCDVGPD GRLLRGYGQF AYDGKDYIAL
 NQDLSSWTAA DTAAQITQRK WEAARVAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVIGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC04213
IPD:MHC04213 Patr-B*20:02 181 bases
 SHSMRYFYTA VSRPGRGEPR FITVGYVDDT QFVRFDSDAA SPRMEPRAPW
 IEQEGPEYWD RETRNVKASA QTDRENLRIA LRYYNQSEAG SHTWQTMYGC
 DVGPDGRLLR GYEQYAYDGK DYIALNQDLS SWTAADTAAQ ITQRKWEAAR
 VAEQLRAYLE GTCVEWLRRY LENGKETLQR A* 
>DL;IPD:MHC00760
IPD:MHC00760 Patr-B*21:01 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMK YFYTAVSRPG RGEPRFITVG
 YVDDTQFVWF DSDAASPRME PRAPWIEQEG PEYWDRQTQI SKTNTQTYRE
 SLRNLRGYYN QSEAGSHTIQ TMYGCDVGPD GRFLRGYRQF AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAARWAEQL RAYLEGLCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGQEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVTGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00761
IPD:MHC00761 Patr-B*22:01 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMK YFYTAVSRPG RGEPRFITVG
 YVDDTQFVWF DSDAASPRKE PRTPWIEQEG PEYWDRETQI SKTNTQTYRE
 SLRNLRGYYN QSEAGSHTLQ TMFGCDVGPD GRLLRGYDQY AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAARAAEQL RAYLEGECVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGQEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVTGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00762
IPD:MHC00762 Patr-B*22:02 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMK YFYTAVSRPG RGEPRFITVG
 YVDDTQFVWF DSDAASPRKE PRTPWIEQEG PEYWDRETQI SKTNTQTYRE
 NLRIALRYYN QSEAGSHTLQ TMFGCDVGPD GRLLRGYDQY AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAARAAEQL RAYLEGECVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGQEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVTGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC04214
IPD:MHC04214 Patr-B*22:03 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMK YFYTAVSRPG RGEPRFITVG
 YVDDTQFVWF DSDAASPRKE PRTPWIEQEG PEYWDRETQI SKTNTQTYRE
 SLRNLRGYYN QSEAGSHTLQ TMFGCDVGPD GRLLRGYEQH AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAARAAEQL RAYLEGECVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGQEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVTGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00763
IPD:MHC00763 Patr-B*23:01 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMK YFYTAVSRPG RGEPRFISVG
 YVDDTQFVWF DSDAASPREE PRAPWIEQEG PEYWDRETQI SKTNTQTYRE
 NLRIALRYYN QSEAGSHTLQ TMYGCDVGPD GRFLRGYRQF AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAARWAEQW RAYLEGTCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGQEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVTGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00764
IPD:MHC00764 Patr-B*23:02 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMK YFYTAVSRPG RGEPRFISVG
 YVDDTQFVWF DSDAASPREE PRAPWIEQEG PEYWDRETQI SKTNTQTYRE
 NLRIALRYYN QSEAGSHTLQ TMYGCDVGPD GRFLRGYRQF AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAARWAEQL RAYLEGLCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGQEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVTGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00765
IPD:MHC00765 Patr-B*23:03 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMK YFYTAVSRPG RGEPRFISVG
 YVDDTQFVWF DSDAASPREE PRAPWIEQEG PEYWDRETQI SKTNTQTYRE
 NLRTLLRYYN QSEAGSHTLQ TMYGCDVGPD GRFLRGYRQY AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAARWAEQL RAYLEGLCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGQEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVTGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC04215
IPD:MHC04215 Patr-B*23:04 181 bases
 SHSMKYFYTA VSRPGRGEPR FISVGYVDDT QFVWFDSDAA SPREEPRAPW
 IEQEGPEYWD RETQISKTNA QTDRESLRNL RGYYNQSEAG SHTLQTMYGC
 DVGPDGRFLR GYRQFAYDGK DYIALNEDLS SWTAADTAAQ ITQRKWEAAR
 VAEQHRAYLE GLCVEWLRRY LENGKETLQR A* 
>DL;IPD:MHC00766
IPD:MHC00766 Patr-B*24:01 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMK YFYTAVSRPG RGEPRFITVG
 YVDDTQFVWF DSDAASPRKE PRTPWIEQEG PEYWDRETQI SKTNAQTDRE
 NLRTLLRYYN QSEAGSHTWQ TMFGCDVGPD GRLLRGYRQF AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAARVAEQR RAYLEGTCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGQEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVTGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00767
IPD:MHC00767 Patr-B*24:02 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMK YFYTAVSRPG RGEPRFITVG
 YVDDTQFVWF DSDAASPRKE PRTPWIEQEG PEYWDRETQI SKTNAQTDRE
 NLRTLLRYYN QSEAGSHTWQ TMFGCDVGPD GRLLRGYRQY AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAARVAEQR RAYLEGTCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGQEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVTGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00768
IPD:MHC00768 Patr-B*25:01 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMK YFLTSVSRPG RGEPRFITVG
 YVDDTQFVRF DSDAASPRME PRAPWIEQEG PEYWDRETRN MKASAQTYRE
 NLRIALRYYN QSEDGSHTLQ TMYGCDVGPD GRFLRGYRQF AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAAREAEQR RAYLEGLCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGQEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVTGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00769
IPD:MHC00769 Patr-B*26:01 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMR YFYTSVSRPG RGEPRFITVG
 YVDDTQFVRF DSDAASPRME PRAPWIEQEG PEYWDRETRN VKASALTDRE
 NLRTLLRYYN QSEAGSHTLQ TMYGCDVGPD GRLLRGYEQF AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAAREAEQH RAYLEGLCVD GLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGQEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVTGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00770
IPD:MHC00770 Patr-B*27:01 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMR YFYTSVSRPG RGEPRFITVG
 YVDDTQFVRF DSDAASPRME PRAPWIEQEG PEYWDRETRN VKASAQTDRG
 SLRNLRGYYN QSEAGSHTLQ TMYGCDVGPD GRLLRGYYQY AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAARVAEQW RAYLEGLCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGQEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVTGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00771
IPD:MHC00771 Patr-B*28:01 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMR YFYTSVSRPG RGEPRFITVG
 YVDDTQFVRF DSDAASPREE PRAPWMEQEG PEYWDRNTQI FKAQAQTDRV
 GLGNLRGYYN QSEAGSHTWQ TMYGCDVGPD GRLLRGYYQH AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAARAAEQR RAYLEGTCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVTGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC00772
IPD:MHC00772 Patr-B*29:01 353 bases
 LLLWGAVALT ETWAGSHSMR YFYTAMSRPG RGEPRFIAVG YVDDTQFVRF
 DSDAAIPRME PRAPWIEQEG PEYWDGNTQG VKTQAQTDRE SLRNLRGYYN
 QSEAGSHTWQ TMYGCDMGPD GRLLRGYGQY AYDSKDYIAL NKDLSSWTAA
 DTAAQITQRK WEAARVAEQL RAYLEGTCVE WLRRYLENGK ETLQRADPPK
 THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ DTELVETRPA
 GDRTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP SSQSTIPIVG
 IVAGLAVLAV VVIGAVVAAV MCRRKSSGGK GGSYSQAASS DSAQGSDVSL
 TAX*    
>DL;IPD:MHC00773
IPD:MHC00773 Patr-B*30:01 361 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMK YFYTAVSRPG RGEPRFITVG
 YVDDTQFVWF DSDAASPRKE PRTPWIEQEG PEYWDRETQI SKTNAQTYRE
 NLRIALRYYN QSEAGSHIIQ RMYGCDMGPD GRLLRGYDQY AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAARWAEQH RAYLEGECVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPE GDRTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQSTIPIVG IVAGLAVPVV TVAVVAAVMC RRKSSGGKGG SYSQAASSDS
 AQGSDVSLTA X*   
>DL;IPD:MHC04216
IPD:MHC04216 Patr-B*33:01 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMK YFLTSVSRPG RGEPRFITVG
 YVDDTQFVRF DSDAASPRME PRAPWIEQEG PEYWDRETRN VKASAQTYRE
 NLRIALRYYN QSEDGSHTWQ TMYGCDVGPD GRLLRGYEQY AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAARVAEQL RAYLEGLCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGQEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVTGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC04217
IPD:MHC04217 Patr-B*34:01 363 bases
 MQVTAPRTVL LLLSAALALT ETWAGSHSMK YFYTAVSRPG RGEPRFITVG
 YVDDTQFVWF DSDAASPRKE PRTPWIEQEG PEYWDRETQI SKTNTQTYRE
 NLRIALRYYN QSEAGSHTWQ TMYGCDVGPD GRLLRGYEQY AYDGKDYIAL
 NEDLSSWTAA DTAAQITQRK WEAARAAEQL RAYLEGECVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGQEQR YTCHVQHEGL PEPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVTGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC01100
IPD:MHC01100 Patr-B*35:01 181 bases
 SHSMRYFYIA MSRPGRGEPR FIAVGYVDDT QFVRFDSDAA IPRMEPRAPW
 IEQEGPEYWD RNTQIYKAQA QTDRESLRNL RGYYNQSEAG SHIIQRMYGC
 DMGPDGRLLR GYEQYAYDGK DYIALNQDLS SWTAADTAAQ ITQRKWEAAR
 WAEQLRAYLE GTCVEWLRRY LENGKETLQR A* 
>DL;IPD:MHC02055
IPD:MHC02055 Patr-B*36:01 363 bases
 MRVTAPRTLL LLLWGAVALT ETWAGSHSMR YFYTAMSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAAIPRME PRAPWIEQEG PEYWDRNTQG VKAQAQTDRE
 NLRIALRYYN QSEAGSHIIQ RMYGCDMGPD GRLLRGYEQY AYDGKDYIAL
 NQDLSSWTAA DTAAQITQRK WEAARWAEQL RAYLEGTCVE WLRRYLENGK
 ETLQRADPPK THVTHHPISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDRTFQKWAA VVVPSGEEQR YTCHVQHEGL PKPLTLRWEP
 SSQSTIPIVG IVAGLAVLAV VVIGAVVAAV MCRRKSSGGK GGSYSQAASS
 DSAQGSDVSL TAX*   
>DL;IPD:MHC02057
IPD:MHC02057 Patr-B*37:01 181 bases
 SHSMRYFYTA MSRPGRGEPR FIAVGYVDDT QFVRFDSDAA IPRMEPRAPW
 IEQEGPEYWD RNTQGVKAQA QTDRENLRIA LRYYNQSEAG SHIIQRMYGC
 DMGPDGRLLR GYYQYAYDGK DYIALNEDLS SWTAADTAAQ ITQRKWEAAR
 AAEQRRAYLE GTCVEWLRRY LENGKETLQR A* 
