>DL;IPD:MHC00799
IPD:MHC00799 Patr-DOB 257 bases
 AAGATTTTGT GATTCAGGCA AAGGCTGACT GTTACTTCAC CAACGGGACA
 GAAAAGGTGC AGTTTGTGGT CAGATTCATC TTTAACTTGG AGGAGTATGT
 ACGTTTCGAC AGTGATGTGG GGATGTTTGT GGCATTGACC AAGCTGGGGC
 AGCCAGATGC TGAGCAGTGG AACAGCCGGC TGGATCTCTT GGAGAGGAGC
 AGACAGGCCG TGGATGGGGT CTGTAGACAC AACTACAGGC TGGGCGCACC
 CTTCACT*    
