>DL;IPD:MHC00909
IPD:MHC00909 Patr-E*01:01:01:01 193 bases
 SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE
 AGSHTLQWMH GCDLGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA
 AQISERKSND ACEAEHQRAY LEDTCVEWLH KYLEKGKETL LHL*
>DL;IPD:MHC00910
IPD:MHC00910 Patr-E*01:01:01:02 193 bases
 SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE
 AGSHTLQWMH GCDLGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA
 AQISERKSND ACEAEHQRAY LEDTCVEWLH KYLEKGKETL LHL*
