>DL;IPD:MHC00915
IPD:MHC00915 Pipi-DRB*W12:01 249 bases
 TTGGAGCAGT TTAAGTATGA GTGTCGTCAC CTCAACGGGA CGGAGCGGGT
 GCGGCTCCTG GTGAGATACA TCTATAACCA GGAGGAGTAT GTGCGCTTCG
 ACAGCGACGT GGGGGCGTTC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 CAAGAGTATT TCAACAGCCA GAAGGACTAC ATGGAGCAGG AGCGGGCCGC
 GGTGGACACC GTGTGCAGGC ACAACTACGG GATTTTTGAG AGGTTCCTA*
>DL;IPD:MHC00916
IPD:MHC00916 Pipi-DRB*W12:02 249 bases
 TTGGAGCAGG TTAAGTATGA GTGTCGTCAC TTCAACGGGA CGGAGCGGGT
 GCGGCTCCTG GTGAGATACA TCTATAACCA GGAGGAGTAT GTGCGCTTCG
 ACAGCGACGT GGGGGAGTTC CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC
 CAAGAGTATT TCAACAGCCA GAAGGACTAC ATGGAGCAGG AGCGGGCCGC
 GGTGGACACC GTGTGCAGGC ACAACTACGG GATTTTTGAG AGGTTCCTA*
>DL;IPD:MHC00914
IPD:MHC00914 Pipi-DRB3*05:01 246 bases
 TTGGAGCTGC TTAAGTCTGA GTGTCGTTTC TTCAACGGGA CAGAGCGGGT
 GCGGTTCCTG GAAAGACACA TCTACAACCA GGAGGAGTTC CTCCTCTTCC
 ACAGCGATGT GGGGGAGTAT CGGGAGGTGA CCGCGCTGGG GCGGCCTGAA
 GAAGAGTCCT GGAACCGCCG GAAGGAACTC CTGGAGCTGA AGCGGGGCCA
 GGTGGACAAC TACTGCAGAC ACAACTACGG GGTTGGTGAG AGTTCA*
