>DL;IPD:MHC00913
IPD:MHC00913 Pipi-B*01 345 bases
 LLLLLSGTLA LTETRTGSHS LRYFDTAVSR PGRGEPRIII VGYVDDTQFV
 GFDSDAASPR MEPRAPWMEK EGPEYWEEET GRVKAAAQTY RVSLRTLLDY
 YNQSEAGSHT FQRMFGCDLG PDGRFLRGYN QFAYDGKDYI ALNEDLRSWT
 AADTAAQITQ RKWEADNEAE RARAYLEGEC MDWLRRYLEN GKETLQRAEP
 PKTQVTRHAV SDHEATLRCW ALSFYPAEIT LMWQRGGEDQ TQDTELLETR
 PAGDGTFQKW AAVVVPSGEE QRYTCHVQHK GLAEPLTLRW EPSSQSTVPI
 MGIIAGLAVL GALVTGAVVA AVMWRRKSSI SDSAQGSDVS LRACK*
