>DL;IPD:MHC00918
IPD:MHC00918 Pipi-G*03:01 331 bases
 LLLLLSGALA LTETWAGSHS LRYFETSVSR PGRGEPRFIA VGYVDDTQFV
 RFDSDAAIPR MEPQAAWMEQ EGPEYWEEQT RRAKAHAQTF RVNLRTLRGY
 YNQSEAGSHT VQTMFGCDLG PDGLFLSGYE QYAYDGKDYI ALNEDLRSWT
 AADTAAQITK RKWEAANEAE RTRAYLESEC PEWLHRYLEN GKETLQRAEP
 PKTHVTHHPV SDHEATLRCW ALGFYPAEIT LTWQRNGEDQ TQDMELVETR
 PSGDGNFQKW AAVVVPSGEE QRYTCHVQHE GLPEPLTLRW EPSSQPTIPI
 MGIVAGLAVL GAVVTGAVVA AVMWRKKSSD K* 
>DL;IPD:MHC00919
IPD:MHC00919 Pipi-G*03:02 331 bases
 LLLLLSGALA LTETRAGSHS LRYFHTAVSR PGRGEPRFIA VGYVDDTQFV
 RFDSDAAIPR GEPQAAWMEQ EGPEYWEEQT RRAKAHAQTD RVNLRTALDY
 YNQSEAGSHT FQTMYGCELG PDGLFLSGYE QFAYDGKDYI ALNEDLRSWT
 AADVAAQITK RKWEAANVAE QQRAYLESEC PEWLHRYLEN GKETLQRAEP
 PKTHVTHHPV SDHEATLRCW ALGFYPAEIT LTWQRNGEDQ TQDMELVETR
 PAGDGTFQKW AAVMVLSGEE QRYTCHVQHE GLPKPLTLRW EPYSQPTIPI
 VGIVAGLAVL GAVVTGAVVA AVMWRKKSSD K* 
>DL;IPD:MHC00921
IPD:MHC00921 Pipi-G*03:03 331 bases
 LLLLLSGALA LTETWAGSHS MRYFDTAVSR PGRGEPRFIA VGYVDDTQFV
 RFDSDAAIPR MEPRAPWVEQ EGPEYWEEQT LRVKAPAQTF RVNLRTLLGY
 YNQSEAGSHT VQTMFGCELG PDGLFLSGYE QHAYDGKDYL ALNEDLRSWT
 AADTAAQITK RKWEAANEAE RTRAYLEGEC VEWLRRYLEN GKETLQRAEP
 PKTHVTHHPV SDHEATLRCW ALGFYPAEIT LTWQRNGEDQ IQDMELVETR
 PAGDGTFQKW AAVMVLSGEE QRYTCHVQHE GLPKPLTLRW EPSSQPTIPI
 VGIVAGLAVL GAVVTGAVVA AVMWRRKSSD K* 
>DL;IPD:MHC00920
IPD:MHC00920 Pipi-G*04:01 331 bases
 LLLLLSGALA LTETWAGSHS LRYFETTVSR PGRREPRFIS VGYVDDTQFV
 RFDSDAALPR MEPRAPWMEQ EEPEYWEEQT WISKDNAQTS RVNLRIALGY
 YNQSEAGSHT YQRMYGCDVG PDGRLLRGYQ QHAYDGKDYI ALNDDLRSWT
 AADTAAQITQ RKWEAANVAE QERAYLEGEC LEWLHRYLEN GKETLQRTEP
 PKTHVTHHPV SDHEATLRCW ALGFYPAEIT LIWQRDGEDQ IQDTELVETR
 PTGDGTFQKW AAVVVLSGEE QRYTCHVQHD GLPKPITLRW EPSSQPAIPI
 VGITAGLAVL GAVVTGAVVA AVMWRRKSSD K* 
