>DL;IPD:MHC00917
IPD:MHC00917 Pipi-E*03:01 433 bases
 GCCAGGGACA CCGCACAGAC TTTCCGAGTG AACCTGCGGA CCCTGCGCGG
 CTACTACAAC CAGAGCGAGG CCGGGTCTCA CACTCTCCAG TGGATGCATG
 GCTGCGACGT GGGGCCCGAC GGGCGCTTCC TCCGCGGGTA TGAACAGTTC
 GCCTACGACG GCAGCGATTA CCTCACCTTG AACGAGGACC TGCGCTCCTG
 GACCGCGGCG GACACCGCGG CTCAGATCTC CAAGCGGAAG TCAGAGGAGG
 CCTCTGAGGC GGAGCACCAA AGAGCCTACC TGGAGGGCAC GTGCGTGGAG
 TGGCTCCACA GACACCTGGA GAACGGGAAG GAGACGCTGC AGCGTGCGGA
 TCCCCCAAAG ACACATGTGA CCCACCACCC TGTCTCTGAC CATGAGGCCA
 CCCTGAGGTG CTGGGCCCTG GGTTTCTACC CTG* 
