>DL;IPD:MHC00918
IPD:MHC00918 Pipi-G*03:01 993 bases
 CTCCTCCTGC TGCTCTCGGG GGCCCTGGCC CTGACCGAGA CCTGGGCGGG
 CTCCCACTCC TTGAGGTATT TCGAGACCTC TGTGTCCCGG CCCGGCCGCG
 GGGAGCCCCG CTTCATCGCC GTGGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCCGC GATTCCGAGG ATGGAGCCGC AGGCGGCGTG
 GATGGAGCAG GAGGGGCCGG AGTACTGGGA GGAGCAGACA CGGAGAGCCA
 AGGCCCACGC ACAGACTTTC CGAGTGAACC TGCGGACCCT GCGCGGCTAC
 TACAACCAGA GCGAGGCCGG GTCTCACACC GTCCAGACGA TGTTTGGCTG
 CGACCTGGGG CCGGACGGGC TCTTCCTCAG CGGGTATGAA CAGTACGCCT
 ACGACGGCAA GGACTACATC GCCCTGAACG AGGACCTGCG CTCCTGGACC
 GCCGCGGACA CGGCGGCTCA GATCACCAAG CGCAAGTGGG AGGCGGCCAA
 TGAGGCTGAG AGGACGAGAG CCTACCTGGA GAGCGAGTGC CCGGAGTGGC
 TCCACAGATA CCTGGAGAAC GGGAAGGAGA CCCTGCAGCG CGCGGAGCCC
 CCCAAGACAC ACGTGACCCA CCACCCCGTC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA TTGACCTGGC
 AGCGGAATGG GGAGGACCAG ACCCAGGACA TGGAGCTTGT AGAAACCAGG
 CCCTCAGGGG ATGGAAACTT CCAGAAGTGG GCAGCTGTGG TGGTGCCTTC
 TGGAGAGGAG CAGAGATACA CATGCCATGT GCAGCACGAG GGACTGCCCG
 AGCCCCTCAC CCTGAGATGG GAGCCGTCTT CCCAGCCCAC CATCCCCATC
 ATGGGCATCG TTGCTGGCCT GGCTGTCCTT GGAGCTGTAG TCACTGGAGC
 TGTGGTCGCT GCTGTGATGT GGAGGAAGAA GAGCTCAGAT AAA*
>DL;IPD:MHC00919
IPD:MHC00919 Pipi-G*03:02 993 bases
 CTCCTCCTGC TGCTCTCGGG GGCCCTGGCC CTGACCGAGA CCCGGGCGGG
 CTCCCACTCC TTGAGGTATT TCCACACCGC CGTGTCCCGG CCCGGCCGCG
 GGGAGCCCCG CTTCATCGCC GTGGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCCGC GATTCCGAGA GGGGAGCCGC AGGCGGCGTG
 GATGGAGCAG GAGGGGCCGG AGTACTGGGA GGAGCAGACA CGGAGAGCCA
 AGGCCCACGC ACAGACGGAC CGAGTGAACC TGCGGACCGC GCTCGACTAC
 TACAACCAGA GCGAGGCCGG GTCTCACACC TTCCAGACGA TGTACGGCTG
 CGAGCTGGGG CCGGACGGGC TCTTCCTCAG CGGGTATGAA CAGTTCGCCT
 ACGACGGCAA GGACTACATC GCCCTGAACG AAGACCTGCG CTCCTGGACC
 GCCGCGGACG TGGCGGCTCA GATCACCAAG CGCAAGTGGG AGGCGGCCAA
 TGTGGCGGAG CAACAGAGAG CCTACCTGGA GAGCGAGTGC CCGGAGTGGC
 TCCACAGATA CCTGGAGAAC GGGAAGGAGA CCCTGCAGCG CGCGGAGCCC
 CCCAAGACAC ACGTGACCCA CCACCCTGTC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA TTGACCTGGC
 AGCGGAATGG GGAGGACCAG ACCCAGGATA TGGAGCTTGT GGAGACCAGG
 CCTGCAGGGG ATGGAACCTT CCAGAAGTGG GCAGCTGTGA TGGTGCTTTC
 TGGAGAGGAG CAGAGATACA CTTGCCATGT GCAGCACGAG GGGCTGCCTA
 AGCCCCTCAC CCTGAGATGG GAGCCGTATT CCCAGCCCAC CATTCCCATC
 GTGGGCATCG TTGCTGGCCT GGCTGTCCTT GGAGCTGTAG TCACTGGAGC
 TGTGGTCGCT GCTGTGATGT GGAGGAAGAA GAGCTCAGAT AAA*
>DL;IPD:MHC00921
IPD:MHC00921 Pipi-G*03:03 993 bases
 CTCCTCCTGC TGCTCTCGGG GGCCCTGGCC CTGACCGAGA CCTGGGCGGG
 CTCCCACTCC ATGAGGTATT TCGACACCGC CGTGTCTCGG CCCGGCCGCG
 GGGAGCCCCG CTTCATCGCC GTGGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCCGC GATTCCGAGG ATGGAGCCGC GGGCGCCGTG
 GGTGGAGCAG GAGGGGCCGG AGTACTGGGA GGAGCAGACA CTGAGAGTCA
 AGGCCCCCGC ACAGACTTTC CGAGTGAACC TGCGGACCCT GCTCGGCTAC
 TACAACCAGA GCGAGGCCGG GTCTCACACC GTCCAGACGA TGTTTGGCTG
 CGAGCTGGGG CCGGACGGGC TCTTCCTCAG CGGGTATGAA CAGCACGCCT
 ACGACGGCAA GGACTACCTC GCCCTGAACG AGGACCTGCG CTCCTGGACC
 GCCGCGGACA CGGCGGCTCA GATCACCAAG CGCAAGTGGG AGGCGGCCAA
 TGAGGCTGAG AGGACGAGAG CCTACCTGGA GGGCGAGTGC GTGGAGTGGC
 TCCGCAGATA CCTGGAGAAC GGGAAGGAGA CCCTGCAGCG CGCGGAGCCC
 CCCAAGACAC ACGTGACCCA CCACCCTGTC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA TTGACCTGGC
 AGCGGAATGG GGAGGACCAG ATCCAGGATA TGGAGCTTGT GGAGACCAGG
 CCTGCAGGGG ATGGAACCTT CCAGAAGTGG GCAGCTGTGA TGGTGCTTTC
 TGGAGAGGAG CAGAGATACA CTTGCCATGT GCAGCACGAG GGGCTGCCTA
 AGCCCCTCAC CCTGAGATGG GAGCCGTCTT CCCAGCCCAC CATTCCCATC
 GTGGGCATCG TTGCTGGCCT GGCTGTCCTT GGAGCTGTAG TCACTGGAGC
 TGTGGTCGCT GCTGTGATGT GGAGGAGGAA GAGCTCAGAT AAA*
>DL;IPD:MHC00920
IPD:MHC00920 Pipi-G*04:01 993 bases
 CTCCTCCTGC TGCTCTCGGG GGCCCTGGCC CTGACCGAGA CCTGGGCAGG
 CTCCCACTCC CTGAGGTATT TCGAGACCAC CGTGTCCCGG CCCGGCCGCA
 GGGAGCCCCG CTTCATCTCC GTGGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCCGC CCTTCCGAGG ATGGAGCCGC GGGCGCCGTG
 GATGGAGCAG GAGGAGCCGG AGTACTGGGA GGAGCAGACA TGGATCTCCA
 AGGACAACGC ACAGACTTCC CGAGTGAACC TTCGGATCGC GCTCGGCTAC
 TACAACCAGA GCGAGGCCGG GTCTCACACC TACCAGAGGA TGTACGGCTG
 CGACGTGGGG CCGGACGGGC GCCTCCTCCG CGGGTACCAG CAGCACGCCT
 ACGACGGCAA GGACTACATC GCCCTGAACG ACGACCTGCG CTCCTGGACC
 GCCGCGGACA CGGCGGCTCA GATCACCCAG CGCAAGTGGG AGGCGGCCAA
 TGTGGCGGAG CAGGAGAGAG CCTACCTGGA GGGCGAGTGC CTGGAGTGGC
 TCCACAGATA CCTGGAGAAC GGGAAGGAGA CCCTGCAGCG CACGGAGCCC
 CCCAAGACAC ATGTGACCCA CCACCCCGTC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA CTGATCTGGC
 AGCGGGATGG AGAGGACCAG ATCCAGGACA CGGAACTGGT AGAGACCAGG
 CCCACGGGGG ATGGAACCTT CCAGAAGTGG GCAGCTGTGG TGGTGCTTTC
 TGGAGAGGAG CAGAGATACA CATGCCATGT GCAGCATGAT GGGCTGCCCA
 AGCCCATCAC TCTGAGATGG GAGCCATCTT CCCAGCCCGC CATCCCCATC
 GTGGGCATCA CTGCTGGCCT GGCTGTCCTT GGAGCTGTAG TCACTGGAGC
 TGTGGTCGCT GCTGTGATGT GGAGGAGGAA GAGCTCAGAT AAA*
