>DL;IPD:MHC00964
IPD:MHC00964 Popy-E*01:01 1079 bases
 GGACCCTCCT TTTACTCCTC TCGGAGGCCC TAGCCCTTAC CGAGACCTGG
 GCGGGCTCCC ACTCCTTGAA GTATTTCCAC ACTTCCGTGT CCCGGCCCGG
 CCGCGGGGAG CCCCGCTTCA TCTCTGTGGG CTACGTGGAC GACACCCAGT
 TCGTGCGCTT TGACAACGAC GCCGCGAGTC CGAGGATGGT GCCGCGGGCG
 CAGTGGATGG AGCAGGAGGG GCCAGAGTAT TGGGACCGGG AGACACGGAG
 CGCCAGGGAC ACCGCACAGA CTTTCCGAGT GAACCTGCGG ACCCTGCGCG
 GCTACTACAA TCAGACCGAG GCCGGGTCTC ACACCCTGCA GTGGATGCAT
 GGCTGCGACC TGGGGCCCGA CGGGCGCTTC CTCCGCGGGT ATGAACAGTT
 CGCCTACGAC GGCAAGGATT ATCTCACCCT GAATGAGGAC CTGCGCTCCT
 GGACCGCGGT GGACACGGCG GCTCAGATCT CCGAGCGAAA GTCAAATGAT
 GCCTGTGAGG CGGAGCACCA GAGAGCCTAC CTGGAAGACA CATGCGTGGA
 GTGGCTCCGC AAATACCTGG AGAAGGGGAA GGAGACGCTG CTTCACCTGG
 ATCCCCCAAA GACACATGTG ACCCACCACC GCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACACTGAC
 CTGGCAGCGG GATGGGGAGG ACCAGAACCA GTACACAGAG CTTGTGGAGA
 CCAGGCCTGC CGGGGATGGA ACCTTCCAGA AGTGGGCAGC TGTGGTGGTG
 CCTTCTGGAG AGGAGCAGAG ATACACGTGC CATGTGCAGC ATGAGGGGCT
 ACCCGAACCC CTCACCCTGA GATGGGAGCC GGCTTCCCAG ACCACCATCC
 CCATCGTGGG CATCTTTGCT GGCCTGGTTC TCCTTGGAGC TGTGGTCACT
 GGAGCTACTG TGGTTGCTGC TGTGATGTGG AGGAAGAAGA GCTCAGGTGG
 AAAAGGAGGG AGCTACTCTA AGGCTGAGTG GAGTGACAGT GCCCAGGGAT
 CTGAGTCTCT CACAGCTTGT AAAGCCTGA*  
