>DL;IPD:MHC00964
IPD:MHC00964 Popy-E*01:01 359 bases
 TLLLLLSEAL ALTETWAGSH SLKYFHTSVS RPGRGEPRFI SVGYVDDTQF
 VRFDNDAASP RMVPRAQWME QEGPEYWDRE TRSARDTAQT FRVNLRTLRG
 YYNQTEAGSH TLQWMHGCDL GPDGRFLRGY EQFAYDGKDY LTLNEDLRSW
 TAVDTAAQIS ERKSNDACEA EHQRAYLEDT CVEWLRKYLE KGKETLLHLD
 PPKTHVTHHR ISDHEATLRC WALGFYPAEI TLTWQRDGED QNQYTELVET
 RPAGDGTFQK WAAVVVPSGE EQRYTCHVQH EGLPEPLTLR WEPASQTTIP
 IVGIFAGLVL LGAVVTGATV VAAVMWRKKS SGGKGGSYSK AEWSDSAQGS
 ESLTACKAX*    
