>DL;IPD:MHC00934
IPD:MHC00934 Popy-C*01:01:01 366 bases
 RVMAPRTLLL LFSGVLALTK TWAGSHSMRY FDTSVSRPGR GEPRFISVGY
 VDDTQFVRFD SDAASPRGEP RAPWVEQEGP EYWDRETQSY KRQAQYDRVS
 LRNLRGYYNQ SEDGSHTFQR MYGCYVGPDG RLLSGYNQFA YDGKDYIALN
 EDLRSWTAAD TAAQITQRKW EAARVAEQLR AYLEGLCVES LRRYLENGKE
 TLQRTEPPKT HVTHHPVSNH EATLRCWALG FYPAEITLTW QRDGEDQTQD
 TELVETRPAG DGTFQKWAAV VVPSGQEQRY ACHVQHEGLP EPITLRWEPS
 SQPTITIVGI VAGLAVLVVL AVLGAVVTTV MCRRKSSGGK GGSCSQAACS
 NSAQGSDESL IACKAX*   
>DL;IPD:MHC00935
IPD:MHC00935 Popy-C*01:01:02 367 bases
 MRVMAPRTLL LLFSGVLALT KTWAGSHSMR YFDTSVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDRETQS YKRQAQYDRV
 SLRNLRGYYN QSEDGSHTFQ RMYGCYVGPD GRLLSGYNQF AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAARVAEQL RAYLEGLCVE SLRRYLENGK
 ETLQRTEPPK THVTHHPVSN HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGQEQR YACHVQHEGL PEPITLRWEP
 SSQPTITIVG IVAGLAVLVV LAVLGAVVTT VMCRRKSSGG KGGSCSQAAC
 SNSAQGSDES LIACKAX*   
>DL;IPD:MHC00936
IPD:MHC00936 Popy-C*02:01 366 bases
 RAMAPRTLLL LLSGALALTE TWAGSHSMRY FYTAVSRPGR EDPRFIAVGY
 VDDTQFVRFD SDAASPRGEP RAPWVEQEGP EYWDQETQSY KRQAQYDRVS
 LRNLRGYYNQ SEDGSHTIQS MYGCYVGPDG RLLSGYNQYA YDGKDYIALN
 EDLRSWTAAD TAAQITQRKW EAAREAEQWR AYLEGLCVGS LRRYLENGKE
 TLQRTEPPKT HVTHHPVSNH EATLRCWALG FYPAEITLTW QRDGEDQTQD
 TELVETRPAG DGTFQKWAAV VVPSGQEQRY ACHVQHEGLP EPITLRWEPS
 SQSTITIVGI VAGLAVLVVL AVLGAVVTTV MCRRKSSGGK GGSCSQAACS
 NSAQGSDESL IACKAX*   
>DL;IPD:MHC00937
IPD:MHC00937 Popy-C*02:02 367 bases
 MRAMAPRTLL LLLSGALALT ETWAGSHSMR YFYTAVSRPG RGDPRFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDQETQS YKRQAQYDRV
 SLRNLRGYYN QSEDGSHTIQ SMYGCYVGPD GRLLSGYNQY AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQW RAYLEGLCVG SLRRYLENGK
 ETLQRTEPPK THVTHHPVSN HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGQEQR YACHVQHEGL PEPITLRWEP
 SSQSTITIVG IVAGLAVLVV LAVLGAVVTT VMCRRKSSGG KGGSCSQAAC
 SNSAQGSDES LIACKAX*   
>DL;IPD:MHC00938
IPD:MHC00938 Popy-C*02:03 367 bases
 MRAMAPRTLL LLLSGALALT ETWAGSHSMR YFYTAVSRPG RGDPRFIAVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDQETQS YKRQAQYDRV
 SLRNLRGYYN QSEDGSHTIQ SMYGCYVGPD GRLLSGYNQY AYDGKDYIAL
 NEDLRSWTAA DTAAQITQRK WEAAREAEQW RAYLEGLCVE SLRRYLENGK
 ETLQRTEPPK THVTHHPVSN HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGQEQR YACHVQHEGL PEPITLRWEP
 SSQSTITIVG IVAGLAVLVV LAVLGAVVTT VMCRRKSSGG KGGSCSQAAC
 SNSAQGSDES LIACKAX*   
>DL;IPD:MHC00939
IPD:MHC00939 Popy-C*03:01 367 bases
 MPVMAPRTLL LLFSGALALT KTWAGSHSMR YFDTSVSRPG RGEPRFISVG
 YVDDTQFVRF DSDAASPRGE PRAPWVEQEG PEYWDQETQN YKRQAQYDRV
 SLRNLRGYYN QSEDGSHTIQ RMYGCYVGPD GRLLSGYDQY AYDGKDYIAL
 NEDLRSWTAA DMAAQITQRK WEAARVAEQL RAYLEGLCVE WLRRYLENGK
 ETLQRTEPPK THVTHHPVSN HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGQEQR YACHVQHEGL PEPITLRWEP
 SSQPTITIVG IVAGLAVLVV LAVLGAVVTI VMCRRKSSGG KGGSCSQAAC
 SNSAQGSDES LIACKAX*   
