>DL;IPD:MHC00922
IPD:MHC00922 Popy-A*01:01 366 bases
 MAIMAPRTLL LLLSGALALT QTWAGSHSMR YFSTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRAPWMEQEG PEYWDRETRS VKAHAQTNRV
 DLGTLRGYYN QSDGGSHTIQ RMFGCDVGPD GRFLRGYEQH AYDGKDYIAL
 NEDLRSWTAA DMAAQITQRK WEAAGAAEQD RAYLEGLCVE SLRRYLENGK
 ETLQRTDAPK THMTHHPVSD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGKEQR YTCHVQHEGL PEPLTLRWEL
 SSQPTIPIVG IIAGLVLLGA VITGAVVAAV MWRRRNSDRK GGSYSQAASN
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC00923
IPD:MHC00923 Popy-A*02 358 bases
 LLLLLSGALA LTQTWAGSHS MRYFYTSVSR PGRGEPRFIT VGYVDDTQFV
 RFDSDAASPR MEPRAPWIEQ EGPEYWDRET RSAKAHAQTD RVDLGTLRGY
 YNQSDGGSHT IQRMYGCDVG PDGRFLRGYR QYAYDGKDYI ALNGDLRSWT
 AADMAAQITQ RKWEAAGEAE QRRAYLEGTC VEWLRRYLEN GKETLQRTDA
 PKTHMTHHRI SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDTELVETR
 PAGDGTFQKW AAVVVPSGKE QRYTCLVQHE GLPEPLTLRW EPSSQPTIPI
 VGIVAGLVLL GAVITGAVVA AVMWRRRSSD RKGGSYSQAA SNDSAQGSDV
 SLTACKVX*    
>DL;IPD:MHC00924
IPD:MHC00924 Popy-A*03:01 358 bases
 LLLLLSGALA LTQTWAGSHS MRYFFTAVSR PGRGEPRFIT VGYVDDTQFV
 RFDSDAASPR MEPRAPWIEQ EGPEYWDRET RSAKAHAQTD RVDLGTLRGY
 YNQSDGGSHT IQRMYGCDVG PDGRFLRGYW QYAYDGKDYI ALNGDLRSWT
 AADMAAQITQ RKWEVAGAAE QDRAYLEGEC VEWLRRYLEN GKETLQRTDA
 PKTHMTHHRI SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDTELVETR
 PAGDGTFQKW AAVVVPSGKE QRYTCLVQHE GLPEPLTLRW EPSSQPTIPI
 VGIVAGLVLL GAVITGAVVA AVMWRRRSSD RKGGSYSQAA SNDSAQGSDV
 SLTACKVX*    
>DL;IPD:MHC04094
IPD:MHC04094 Popy-A*03:02 366 bases
 MAVMAPRTLL LLLSGALALT QTWAGSHSMR YFFTAVSRPG RGEPRFITVG
 YVDDTQFVRF DSDAASPRME PRAPWIEQEG PEYWDRETRS AKAHAQTDRV
 DLGTLRGYYN QSDGGSHTIQ RMYGCDVGPD GRFLRGYWQY AYDGKDYIAL
 NGDLRSWTAA DMAAQITQRK WEAAGAAEQD RAYLEGECVE WLRRYLENGK
 ETLQRTDAPK THMTHHRISD HEATLRCWAL GIYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGKEQR YTCLVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLVLLGA VITGAVVAAV MWRRRSSDRK GGSYSQAASN
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC04095
IPD:MHC04095 Popy-A*04:01 150 bases
 MAVMAPRTLI LLLSGALALT QTWAGSHSMR YFYTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRTPWIEQEG PEYWDRNTRN VKAHAQTGRV
 NLGTLRGYYN QSDGGSHTIQ IMYGCDVGPD GRFLRGYRQD AYAARITSPX
>DL;IPD:MHC04096
IPD:MHC04096 Popy-A*04:02 366 bases
 MAVMAPRTLI LLLSGALALT QTWAGSHSMR YFYTSVSRPG RGEPRFIAVG
 YVDDTQFVRF DSDAASQRME PRTPWIEQEG PEYWDRNTRN VKAHAQTDRV
 DLGTLRGYYN QSEDGSHTIQ IMYGCDVGPD GRFLRGYRQD AYDGKDYIAL
 NEDLRSWTAA DMAAQITQRK WEAAGAAEQR RAYLEGLCVE SLRRYLENGK
 ETLQRTDAPK THMTHHRISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGKEQR YTCLVQHEGL PEPLTLRWEP
 SSQPTIPIVG IVAGLVLLGA VITGAVVAAV MWRRRSSDRK GGSYSQAASN
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC04093
IPD:MHC04093 Popy-A*05:01 366 bases
 MAVMAPRTLI LLLSGALALT QTWAGSHSMR YFFTSVSRPG RGEPRFITVG
 YVDDTQFVRF DSDAASQRME PRTPWMEQEG PEYWDRETRS AKARAQTDRM
 NLGTLRDYYN QSEDGSHTIQ IMYGCDVGPD GRFLHGYRQD AYDGKDYIAL
 NEDLRSWTAA DMAAQITQRK WEAAGVAEQQ RAYLEGTCVE WLRRYLENGK
 ETLQRTDAPK THMTHHRISD HEATLRCWAL GFYPAEITLT WQRDGEDQTQ
 DTELVETRPA GDGTFQKWAA VVVPSGKEQR YTCLVQHEGL PETLTLRWEP
 SSQPTIPIVG IVAGLVLLGA VITGAVVAAV MWRRRSSDRK GGSYSQAASN
 DSAQGSDVSL TACKVX*   
>DL;IPD:MHC04978
IPD:MHC04978 Popy-Ap*01:01 101 bases
 LSGALALTES WASSHSMWCF DISESRPGRG EPRFISVGYV DDTQFVQFDS
 DAASPREEPW APWMEQEGPE YWDRNTQISK TQAQTDRVNM RTLLRYYNQS
 X*    
>DL;IPD:MHC04980
IPD:MHC04980 Popy-Ap*02:01 107 bases
 RTLLLVLSGA LALTETWAGS HSMWCFDTSE SRPGRGEPRF ISVGYVDDMQ
 FVQFDSDAAS PREEPWAPWM EQEGPEYWDR NTQISKTQAQ TDRVNMQTLL
 RYYNQSX*    
>DL;IPD:MHC04977
IPD:MHC04977 Popy-Ap*02:02 101 bases
 LSGALALTET WAGSHSMWCF DTSESRPGRG EPRFISVGYV DDMQFVQFDS
 DAASPREEPW APWMEQEGPE YWDRNTQISK TQAQTDRVNM QTLLRYYNQS
 X*    
>DL;IPD:MHC04975
IPD:MHC04975 Popy-Ap*03:01 101 bases
 LSGALALTES WASSHSMWCF DISESRPGRG EPRFISVGYV DDTQFVQFDS
 DAASPREEPW APWMEQEGPE YWDRNTQISK TQAQTDRVNM RTLLRYYNQS
 X*    
>DL;IPD:MHC04979
IPD:MHC04979 Popy-Ap*04:01 84 bases
 MAVMAPRTLL LVLSGALALT ETWAGSHSMW CFDTSESRPG RGEPRFISVG
 YVDDMQFVQF DSDAASPREE PWAPWMEQER PEYX* 
>DL;IPD:MHC04976
IPD:MHC04976 Popy-Ap*05:01 101 bases
 LSGALALTET WAGSHSMWCF DTSESRPGRG EPRFISVGYV DDTQFVQFDS
 DAASPREEPW APWMEQERPE YWDRNTQISK TQAQTDRVNM RTQLRYYNQS
 X*    
>DL;IPD:MHC04974
IPD:MHC04974 Popy-Ap*06:01 101 bases
 LSGALALTET WAGSHSMWCF DTSESRPGRG EPRFISVGYV DDMQFVQFDS
 DAASPREEPW APWMEQEGPE YWDRNTQISK TQAQTDRVNM RTLLRYYNQS
 X*    
