>DL;IPD:MHC00934
IPD:MHC00934 Popy-C*01:01:01 1098 bases
 CGGGTCATGG CGCCCCGAAC CCTCCTCCTG CTGTTCTCGG GAGTCCTGGC
 CCTGACCAAG ACCTGGGCCG GCTCCCACTC CATGAGGTAT TTCGACACCT
 CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC GCTTCATCTC CGTGGGCTAC
 GTGGACGACA CGCAGTTCGT GCGGTTCGAC AGCGACGCCG CGAGTCCGAG
 AGGGGAGCCG CGGGCGCCGT GGGTGGAGCA GGAGGGGCCG GAGTATTGGG
 ACCGGGAGAC ACAGAGCTAC AAGCGCCAGG CACAGTATGA CCGAGTGAGC
 CTGAGGAACC TGCGCGGCTA CTACAACCAG AGCGAGGACG GGTCTCACAC
 CTTCCAGAGG ATGTATGGCT GCTACGTGGG GCCCGACGGG CGCCTCCTCA
 GCGGGTATAA CCAGTTCGCC TACGATGGCA AGGATTACAT CGCCCTGAAC
 GAGGACCTGC GCTCCTGGAC CGCCGCGGAC ACGGCGGCTC AGATCACCCA
 GCGCAAGTGG GAGGCGGCCC GTGTGGCCGA GCAGTTGAGA GCCTACCTGG
 AGGGCCTGTG CGTGGAGTCG CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG
 ACGCTGCAGC GCACGGAACC CCCAAAGACA CACGTGACCC ACCACCCCGT
 CTCTAACCAT GAGGCCACCC TGAGGTGCTG GGCCCTGGGC TTCTACCCTG
 CGGAGATCAC ACTGACCTGG CAGCGGGATG GGGAGGACCA AACTCAGGAC
 ACTGAGCTTG TGGAGACCAG GCCAGCAGGA GATGGAACCT TCCAGAAGTG
 GGCAGCTGTG GTGGTGCCTT CTGGACAAGA GCAGAGATAC GCGTGCCATG
 TGCAGCACGA GGGGCTGCCG GAGCCCATCA CCCTGAGATG GGAGCCGTCT
 TCCCAGCCCA CCATCACCAT CGTGGGCATC GTTGCTGGCC TGGCTGTCCT
 GGTTGTCCTA GCTGTCCTAG GAGCTGTGGT CACCACTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT GCTCTCAGGC TGCGTGCAGC
 AACAGTGCCC AGGGCTCTGA TGAGTCTCTC ATTGCTTGTA AAGCCTGA*
>DL;IPD:MHC00935
IPD:MHC00935 Popy-C*01:01:02 1101 bases
 ATGCGGGTCA TGGCGCCCCG AACCCTCCTC CTGCTGTTCT CGGGAGTCCT
 GGCCCTGACC AAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCGACA
 CCTCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CTCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGCGAGTCC
 GAGAGGGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGGA GACACAGAGC TACAAGCGCC AGGCACAGTA TGACCGAGTG
 AGCCTGAGGA ACCTGCGCGG CTACTACAAC CAGAGCGAGG ACGGGTCTCA
 CACCTTCCAG AGGATGTATG GCTGCTACGT GGGGCCCGAC GGGCGCCTCC
 TCAGCGGGTA TAACCAGTTC GCCTACGATG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCCGCG GACACGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGTGGC GGAGCAGTTG AGAGCCTACC
 TGGAGGGCCT GTGCGTGGAG TCGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCACGGA ACCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTAAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACTGAGC TTGTGGAGAC CAGGCCAGCA GGAGATGGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGACA AGAGCAGAGA TACGCGTGCC
 ATGTGCAGCA CGAGGGGCTG CCGGAGCCCA TCACCCTGAG ATGGGAGCCG
 TCTTCCCAGC CCACCATCAC CATCGTGGGC ATCGTTGCTG GCCTGGCTGT
 CCTGGTTGTC CTAGCTGTCC TAGGAGCTGT GGTCACCACT GTGATGTGTA
 GGAGGAAGAG CTCAGGTGGA AAAGGAGGGA GCTGCTCTCA GGCTGCGTGC
 AGCAACAGTG CCCAGGGCTC TGATGAGTCT CTCATTGCTT GTAAAGCCTG
 A*    
>DL;IPD:MHC00936
IPD:MHC00936 Popy-C*02:01 1098 bases
 CGGGCCATGG CGCCCCGAAC CCTCCTCCTG CTACTCTCGG GGGCCCTGGC
 CCTGACCGAG ACCTGGGCCG GCTCCCACTC CATGAGGTAT TTCTACACCG
 CCGTGTCCCG GCCCGGCCGA GAAGACCCCC GCTTCATCGC AGTGGGCTAC
 GTGGACGACA CGCAGTTCGT GCGGTTCGAC AGCGACGCCG CGAGTCCGAG
 AGGGGAGCCG CGGGCGCCGT GGGTGGAGCA GGAGGGGCCG GAGTATTGGG
 ACCAGGAGAC ACAGAGCTAC AAGCGCCAGG CACAGTATGA CCGAGTGAGC
 CTGAGGAACC TGCGCGGCTA CTACAACCAG AGCGAGGACG GGTCTCACAC
 CATCCAGAGC ATGTATGGCT GCTACGTGGG GCCCGACGGG CGCCTCCTCA
 GCGGGTATAA CCAGTACGCC TACGACGGCA AGGATTACAT CGCCCTGAAC
 GAGGACCTGC GCTCCTGGAC CGCCGCGGAC ACGGCGGCTC AGATCACCCA
 GCGCAAGTGG GAGGCGGCCC GTGAGGCGGA GCAGTGGAGA GCCTACCTGG
 AGGGCCTGTG CGTGGGGTCG CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG
 ACGCTGCAGC GCACGGAACC CCCAAAGACA CACGTGACCC ACCACCCCGT
 CTCTAACCAT GAGGCCACCC TGAGGTGCTG GGCCCTGGGC TTCTACCCTG
 CGGAGATCAC ACTGACCTGG CAGCGGGATG GGGAGGACCA AACTCAGGAC
 ACTGAGCTTG TGGAGACCAG GCCAGCAGGA GATGGAACCT TCCAGAAGTG
 GGCAGCTGTG GTGGTGCCTT CTGGACAAGA GCAGAGATAC GCGTGCCATG
 TGCAGCACGA GGGGCTGCCG GAGCCCATCA CCCTGAGATG GGAGCCGTCT
 TCCCAGTCCA CCATCACCAT CGTGGGCATC GTTGCTGGCC TGGCTGTCCT
 GGTTGTCCTA GCTGTCCTAG GAGCTGTGGT CACCACTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT GCTCTCAGGC TGCGTGCAGC
 AACAGTGCCC AGGGCTCTGA TGAGTCTCTC ATTGCTTGTA AAGCCTGA*
>DL;IPD:MHC00937
IPD:MHC00937 Popy-C*02:02 1101 bases
 ATGCGGGCCA TGGCGCCCCG AACCCTCCTC CTGCTACTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCTACA
 CCGCCGTGTC CCGGCCCGGC CGAGGAGACC CCCGCTTCAT CGCAGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGCGAGTCC
 GAGAGGGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG CCGGAGTATT
 GGGACCAGGA GACACAGAGC TACAAGCGCC AGGCACAGTA TGACCGAGTG
 AGCCTGAGGA ACCTGCGCGG CTACTACAAC CAGAGCGAGG ACGGGTCTCA
 CACCATCCAG AGCATGTATG GCTGCTACGT GGGGCCCGAC GGGCGCCTCC
 TCAGCGGGTA TAACCAGTAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCCGCG GACACGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGAGGC GGAGCAGTGG AGAGCCTACC
 TGGAGGGCCT GTGCGTGGGG TCGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCACGGA ACCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTAAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACTGAGC TTGTGGAGAC CAGGCCAGCA GGAGATGGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGACA AGAGCAGAGA TACGCGTGCC
 ATGTGCAGCA CGAGGGGCTG CCGGAGCCCA TCACCCTGAG ATGGGAGCCG
 TCTTCCCAGT CCACCATCAC CATCGTGGGC ATCGTTGCTG GCCTGGCTGT
 CCTGGTTGTC CTAGCTGTCC TAGGAGCTGT GGTCACCACT GTGATGTGTA
 GGAGGAAGAG CTCAGGTGGA AAAGGAGGGA GCTGCTCTCA GGCTGCGTGC
 AGCAACAGTG CCCAGGGCTC TGATGAGTCT CTCATTGCTT GTAAAGCCTG
 A*    
>DL;IPD:MHC00938
IPD:MHC00938 Popy-C*02:03 1101 bases
 ATGCGGGCCA TGGCGCCCCG AACCCTCCTC CTGCTACTCT CGGGGGCCCT
 GGCCCTGACC GAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCTACA
 CCGCCGTGTC CCGGCCCGGC CGAGGAGACC CCCGCTTCAT CGCAGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGCGAGTCC
 GAGAGGGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG CCGGAGTATT
 GGGACCAGGA GACACAGAGC TACAAGCGCC AGGCACAGTA TGACCGAGTG
 AGCCTGAGGA ACCTGCGCGG CTACTACAAC CAGAGCGAGG ACGGGTCTCA
 CACCATCCAG AGCATGTATG GCTGCTACGT GGGGCCCGAC GGGCGCCTCC
 TCAGCGGGTA TAACCAGTAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCCGCG GACACGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGAGGC GGAGCAGTGG AGAGCCTACC
 TGGAGGGCCT GTGCGTGGAG TCGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCACGGA ACCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTAAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACTGAGC TTGTGGAGAC CAGGCCAGCA GGAGATGGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGACA AGAGCAGAGA TACGCGTGCC
 ATGTGCAGCA CGAGGGGCTG CCGGAGCCCA TCACCCTGAG ATGGGAGCCG
 TCTTCCCAGT CCACCATCAC CATCGTGGGC ATCGTTGCTG GCCTGGCTGT
 CCTGGTTGTC CTAGCTGTCC TAGGAGCTGT GGTCACCACT GTGATGTGTA
 GGAGGAAGAG CTCAGGTGGA AAAGGAGGGA GCTGCTCTCA GGCTGCGTGC
 AGCAACAGTG CCCAGGGCTC TGATGAGTCT CTCATTGCTT GTAAAGCCTG
 A*    
>DL;IPD:MHC00939
IPD:MHC00939 Popy-C*03:01 1101 bases
 ATGCCGGTCA TGGCGCCCCG AACCCTCCTC CTGCTGTTCT CGGGAGCCCT
 GGCCCTGACC AAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCGACA
 CCTCCGTGTC CCGGCCTGGC CGCGGGGAGC CCCGCTTCAT CTCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGCGAGTCC
 GAGAGGGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG CCGGAGTATT
 GGGACCAGGA GACACAGAAC TACAAGCGCC AGGCACAGTA TGACCGAGTG
 AGCCTGAGGA ACCTGCGCGG CTACTACAAC CAGAGCGAGG ACGGGTCTCA
 CACCATCCAG AGGATGTATG GCTGCTACGT GGGGCCCGAC GGGCGCCTCC
 TCAGCGGATA TGACCAGTAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCCGCG GACATGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGTGGC GGAGCAGTTG AGAGCCTACC
 TGGAGGGCCT GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCACGGA ACCCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTAAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACTGAGC TTGTGGAGAC CAGGCCAGCA GGAGATGGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGACA AGAGCAGAGA TACGCGTGCC
 ATGTGCAGCA CGAGGGGCTG CCGGAGCCCA TCACCCTGAG ATGGGAGCCG
 TCTTCCCAGC CCACCATCAC CATCGTGGGC ATCGTTGCTG GCCTGGCTGT
 CCTGGTTGTC CTAGCTGTCC TAGGAGCTGT GGTCACCATT GTGATGTGTA
 GGAGGAAGAG CTCAGGTGGA AAAGGAGGGA GCTGCTCTCA GGCTGCGTGC
 AGCAACAGTG CCCAGGGCTC TGATGAGTCT CTCATTGCTT GTAAAGCCTG
 A*    
