>DL;IPD:MHC00961
IPD:MHC00961 Popy-DRB5*06:03 270 bases
 CACGTTTCTT GAAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACC
 GAGCGGGTGC GGTTCCTGCA CAGAGGCATC TATAACCAAA AGGAGGACGT
 GCGCTTCGAC AGTGACGTGG GGGAGTACCG GGCGGTGGCG GAGCTGGGGC
 GGCCTATCGC CGAGTACTGG AACAGCCAGA AGGACCTCCT GGAGCGGAGG
 CGGGCCGCGG TGGACAATTA CTGCAGACAC AACTACGGGG TTGTGGAGAG
 CTTCACAGTG CAGCGGCGAG *  
>DL;IPD:MHC00962
IPD:MHC00962 Popy-DRB6*02:01N 147 bases
 CTGCGCTTCG ACAGCGACGT GGGGGAGTTC CGGGCGGTGA CGGAACTGGG
 GCGGCCTGTC GCAGAGAACT GGAACAGCCA GAAGGGCATC CCGGAGGAGA
 AGCGGGACAA GGTGGACACC TGCAGATACA GTTACGGGGT TTTTGAG*
>DL;IPD:MHC00963
IPD:MHC00963 Popy-DRB6*02:02N 256 bases
 GAGCAGGCTA AGTGTGAGTG TCATATCTTC AATGGGACGA AGCAGGTGCA
 GTACCTGAAC AGACACATCC ATAAAAGGGA GGAGAACCTG CGCTTCCACA
 GCGACGTGGA GGAGTTCCAG GCGGTGACGG AACTGGGGCG GCCTGTCGCA
 GAGAACTGGA ACAGCCAGAA GGGCATCCCG GAGGAGAAGC GGGACAAGGT
 GGACACCTGC AGATACAGTT ACGGGGTTTT TGAGAGCTTC ACAGTGCAGC
 CATGAG*    
