>DL;IPD:MHC00925
IPD:MHC00925 Popy-B*01 1065 bases
 CTCCTCCTGC TGCTCTCGGC GGCCCTGGCC CTGACCGAGA CCTGGGCCGG
 CTCCCACTCC ATGAAGTATT TCTACACGGG CATGTCCCGG CCCGGCCGCG
 GGGAGCCCCG CTTCATCTCC GTGGGCTACG TGGACGACAC GCAGTTCGTG
 TGGTTCGACA GCGACGCCGC GAGTCCGAGA GAGGAGCCGC GGGCGCCATG
 GATAGAGCAG GAGGGGCCGG AGTATTGGGA CCGGAACACA CAGATCTGCA
 AGACCAACAC ACAGACTTAC CGAGAGGGCC TGCGGATCCT GCGCGGCTAC
 TACAACCAAA GCGAGGACGG GTCTCACACC TGGCAGAGGA TGTTTGGCTG
 CGACGTGGGG CCCGACGGGC GCCTCCTCCG CGGGTATGAC CAGTTCGCCT
 ACGACGGCAA GGATTACATC GCCCTGAACG AGGACCTGAG CTCCTGGACC
 GCCGCGGACA CCGCGGCTCA GATCACCCAG CGCAAGTGGG AGGCGGCCCG
 TGAGGCGGAG CAGTTCAGAG CCTACCTGGA GGGCCTGTGC GTGGAGTCGC
 TCCGCAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CGCGGAGCCC
 CCAAGGACAC ACATGACCCA CCATCCCATC TCTGACCATG AGACTACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGA GGAGGACCTG ACCCAGGACA CCGAGCTTGT GGAGACCAGG
 CCTGCAGGCG ATGGAACCTT CCAGAAGTGG GCAGCTGTGG TGGTGCCTTC
 TGGAGCAGAG CAGAGATACA CATGCCATGT GCAGCACGAG GGGCTGCCGG
 AGCCCCTCAC CCTGAGATGG GAGCCATCTT CCCAGTCCAC CATCCCCATC
 GTGGGCATTG TTGCTGGCCT GGCTGTCCTA GCAGTTGTGG TCATCGGAAT
 TGTGGTCGCT GCTGTGATGT GTAGGAGGAA GAGCTCAGGT GGGAAAGGAG
 GGAGCTACTC TCAGGCTGCG TGCAGCGACA GTGCCCAGGG CTCTGATGTG
 TCTCTCACGG CTTGA*   
>DL;IPD:MHC00926
IPD:MHC00926 Popy-B*02 1065 bases
 CTCCTCCTGC TGCTCTCGGC GGCCCTGGCC CCGACCGAGA CCTGGGCCGG
 CTCCCACTCC ATGAAGTATT TCTACACGGG CATGTCCCGG CCCGGCCGCG
 GGGAGCCCCG CTTCATCTCC GTGGGCTACG TGGACGACAC GCAGTTCGTG
 TGGTTCGACA GCGACGCCGT GAGTCCGAGA GAGGAGCCGC GGGCGCCATG
 GATAGAGCAG GAGGGGCCGG AGTATTGGGA CCGGAACACA CAGATCTACA
 AGGCCAACAC ACAGACTTAC CGAGAGAGCC TGCGGAACCT GCGCGGCTAC
 TACAACCAGA GCGAGGACGG GTCTCACACC TGGCAGAGCA TGTATGGTTG
 CGACGTGGGG CCCGACGGGC GCCTCCTCCG CGGGTATGAC CAGTTCGCCT
 ACGACGGCAA GGATTACATC GCCCTGAACG AGGACCTGAG CTCCTGGACC
 GCCGCGGACA CCGCGGCTCA GATCACCCAG CGCAAGTGGG AGGCGGCCGG
 TTGGGCGGAG CAGTTCAGAG CCTACCTGGA GGGCCGGTGC GTGGAGTCGC
 TCCGCAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CGCGGAGCCC
 CCAAGGACAC ACATGACCCA CCATCCCATC TCTGACCATG AGACTACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGA GGAGGACCAG ACCCAGGACA CCGAGCTTGT GGAGACCAGG
 CCTGCAGGCG ATGGAACCTT CCAGAAGTGG GCAGCTGTGG TGGTGCCTTC
 TGGAGCAGAG CAGAGATACA CATGCCATGT GCAGCACGAG GGGCTGCCGG
 AGCCCCTCAC CCTGAGATGG GAGCCATCTT CCCAGTCCAC CATCCCCATC
 GTGGGCATTG TTGCTGGCCT GGCTGTCCTA GCAGTTGTGG TCATCGGAAT
 TGTGGTCGCT GCTGTGATGT GTAGGAGGAA GAGCTCAGGT GGGAAAGGAG
 GGAGCTACTC TCAGGCTGCG TGCAGCGACA GTGCCCAGGG CTCTGATGTG
 TCTCTCACGG CTTGA*   
>DL;IPD:MHC00927
IPD:MHC00927 Popy-B*03:01 1065 bases
 CTCCTCCTGC TGCTCTCGGA GGTCCTGGCC CTGACCGAGA CCTGGGCCGG
 CTCCCACTCC ATGAGGTATT TCGACACCTC CGTGTCCCGG CCCGGCCGCG
 GGGAGCCCCG CTTCATCACC GTGGGCTACG TGGATGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCCGC GAGTCCGAGG ATGGAGCCGC GGGTGCCATG
 CATAGAGCAG GAGGGGCCGG AGTATTGGGA CCAGGAGACA CAGAAAGCCA
 AGGCCTCCGC ACAGACTGAC CGAGTGAGCC TGCGGACCCT GCTCCGCTAC
 TACAACCAGA GCGAGGACGG GTCTCACACC TGGCAGAGGA TGTATGGCTG
 CTACGTGGGG CCCGACGGGC GCCTCCTCCG CGGGTATGAC CAGTACGCCT
 ACGACGGCAA GGATTACATC GCCCTGAACG AGGACCTGAG CTCCTGGACC
 GCTGCGGACA CCGCGGCTCA GATCACCCAG CGCAAGTGGG AGGCGCGCCG
 TTGGGCGGAG CAGTTGAGAG CCTACCTGGA GGGCCGGTGC GTGCAGTGGC
 TCCGCAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CGCGGACCCC
 CCAAAGACAC ACGTGACCCA CCACCCCAAC TCTGACCATG AGACCACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG GGAGGACCAG ACCCAGGACA CGGAGCTTGT GGAGACCAGG
 CCTGCAGGAG ATGGAACCTT CCAGAAGTGG GCAGCTGTGG TGGTGCCTTC
 TGGAGCAGAG CAGAGATACA CATGCCATGT GCAGCATGAG GGGCTGCCGG
 AGCCCCTCAC CCTGAGATGG AAGCCATCTT CCCAGTCCAC CATCCCCATC
 GTGGGCATTG TTGCTGGCCT GGCTGTCCTA GCAGTTGTGG TCATCGGAAT
 TGTGGTCGCT GCTGTGATGT GTAGGAGGAA GAGCTCAGGT GGAAAAGGAG
 GGAGCTACTC TCAGGCTGCG TCCAGCGACA GCGTCCAGGG CTCTGATGTG
 TCTCTCACGG CTTGA*   
>DL;IPD:MHC00928
IPD:MHC00928 Popy-B*03:02 1086 bases
 CGGGTCATGG CGCCCCGAAC CCTCCTCCTG CTGCTCTCGG AGGTCCTGGC
 CCTGACCGAG ACCTGGGCCG GCTCCCACTC CATGAGGTAT TTCGACACCT
 CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC GCTTCATCAC CGTGGGCTAC
 GTGGATGACA CGCAGTTCGT GCGGTTCGAC AGCGACGCCG CGAGTCCGAG
 GATGGAGCCG CGGGTGCCAT GCATAGAGCA GGAGGGGCCG GAGTATTGGG
 ACCAGGAGAC ACAGAAAGCC AAGGCCTCCG CACAGACTGA CCGAGTGAGC
 CTGCGGACCC TGCTCCGCTA CTACAACCAG AGCGAGGACG GGTCTCACAC
 CTGGCAGAGG ATGTATGGCT GCTACGTGGG GCCCGACGGG CGCCTCCTCC
 GCGGGTATGA CCAGTACGCC TACGACGGCA AGGATTACAT CGCCCTGAAC
 GAGGACCTGA GCTCCTGGAC CGCTGCGGAC ACCGCGGCTC AGATCACCCA
 GCGCAAGTGG GAGGCGGCCC GTTGGGCGGA GCAGTTGAGA GCCTACCTGG
 AGGGCCGGTG CGTGCAGTGG CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG
 ACGCTGCAGC GCGCGGACCC CCCAAAGACA CACGTGACCC ACCACCCCAA
 CTCTGACCAT GAGACCACCC TGAGGTGCTG GGCCCTGGGC TTCTACCCTG
 CGGAGATCAC ACTGACCTGG CAGCGGGATG GGGAGGACCA GACCCAGGAC
 ACGGAGCTTG TGGAGACCAG GCCAGCAGGA GATGGAACCT TCCAGAAGTG
 GGCAGCTGTG GTGGTGCCTT CTGGAGAAGA GCAGAGATAC ACATGCCATG
 TGCAGCATGA GGGGCTGCCG GAGCCCCTCA CCCTGAGATG GAAGCCATCT
 TCCCAGTCCA CCATCCCCAT CGTGGGCATT GTTGCTGGCC TGGCTGTCCT
 AGCAGTTGTG GTCATCGGAA TTGTGGTCGC TGCTGTGATG TGTAGGAGGA
 AGAGCTCAGG TGGAAAAGGA GGGAGCTACT CTCAGGCTGC GTCCAGCGAC
 AGCGTCCAGG GCTCTGATGT GTCTCTCACG GCTTGA* 
>DL;IPD:MHC00929
IPD:MHC00929 Popy-B*04:01 1089 bases
 ATGCGGGTCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CGGCGGTCCT
 GGCCCTGACC GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCCACA
 CGGGCATGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGTGGTTC GACAGCGACG CCGCAAGTCC
 GAGGAAGGAG CCGCGGGCGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGGA GACACAGATC TCCAAGGCCA ACACACAGAG TTACCGAGAG
 AGCCTGGGGA TCCTGCGCGG CTACTACAAC CAGAGCGAGG ACGGGTCTCA
 CACCTGGCAG AGGATGTATG GCTGCGACGT GGGGCCCGAC GGGCGCCTCC
 TCCGCGGGTA TGACCAGTTC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGCGCTCCTG GACCGCCGCG GACACCGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGAGGC GGAGCAGTTC AGAGCCTACC
 TGGAGGGCCT GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA GCCCCCAAGG ACACACATGA CCCACCATCC
 CATCTCTGAC CATGAGACTA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATAGGGAGGA CCAGACCCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGCA GGCGATGGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA CGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCATCG GAATTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGGAAA GGAGGGAGCT ACTCTCAGGC TGCGTGCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACGGCTTGA* 
>DL;IPD:MHC00930
IPD:MHC00930 Popy-B*05:01 1089 bases
 ATGCGGGTCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CGGCGGTCCT
 GGCCCTGACC GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCTACA
 CGGGCATGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CTCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGTGGTTC GACAGCGACG CCGCAAGTCC
 GAGGGTGGAG CCGCGGGCGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGAA CACACAGATC TGCAAGACCA ACACACAGAT CTACCGAGAG
 AACCTGCGGA ACCTGCGCGG CTACTACAAC CAGAGCGAGG ACGGGTCTCA
 CACCTGGCAG AGCATGTATG GCTGCTACGT GGGGCCCGAC GGGCGCCTCC
 TCGGCGGGTA TGACCAGCAC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCCTG GACCGCCGCG GACACCGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGTGGC GGAGCAGTTC AGAGCCTACC
 TGGAGGGCCG GTGCGTGAAG TCGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCACGCGGA CCGCCCAAAG ACACACGTGA CCCACCACCC
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GAGACCGAGC TTGTGGAGAC CAGGCCAGCA GGAGATGGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA CGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCATCG GAATTGTGGT CACTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTGCAGC
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGA* 
>DL;IPD:MHC00931
IPD:MHC00931 Popy-B*06:01 1086 bases
 CGGGTCATGG CGCCCCGAAC CCTCCTCCTG CTGCTCTCGG CGGCCCTGGC
 CCCGACCGAG ACCTGGGCCG GCTCCCACTC CATGAGGTAT TTCGACACCT
 CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC GCTTCATCTC CGTGGGCTAC
 GTGGACGACA CCCAGTTCGT GCGGTTCGAC AGCGACGCTG CGAGTCCGAG
 GATGGAGCCG CGGGCGCCAT GGATAGAGCA GGAGGGGCCG GAGTATTGGG
 ACCAGGAGAC ACAGAAAGCC AAGACCAGCA CACAGACTGA CCGAGAGAAC
 CTGCGGATCC TGCGCGGCTA CTACAACCAG AGCGAGGACG GGTCTCACAC
 CATCCAGAGG ATGTATGGCT GCGACGTGGG GCCGGATGGG CGACTCCTCC
 GCGGGTATGG CCAGTTCGCC TACGACGGCA AGGATTACAT CGCCCTGAAC
 GAGGACCTGA GCTCCTGGAC CGCCGCGGAC ATGGCGGCTC AGATCACCCA
 GCGCAAGTGG GAGGCGGCCC GTTGGGCGGA GCAGTTGAGA CCCTACCTGG
 AGGGCCTGTG CGTGGAGTCG CTCCGCAGAT ACCTGGAAAA CGGGAAGGAG
 ACGCTGCAGC GCGCGGACCG CCCAAAGACA CACGTGACCC ACCACCCTGT
 CTCTGAACAT GAGACCACCC TGAGGTGCTG GGCCCTGGGC TTCTACCCTG
 CGGAGATCAC ACTGACCTGG CAGCGGGATG GGGAGGACCA AACTCAGGAC
 ACCGAGCTTG TGGAGACCAG GCCAGCAGGA GATGGAACCT TCCAGAAGTG
 GGCAGCTGTG GTGGTGCCTT CTGGAGAAGA GCAGAGATAC ACATGCCATG
 TGCAGCATGA GGGGCTGCCG GAGCCCCTTA CTCTGAGATG GAAGCCATCT
 TCCCAGTCCA CCATCCCCAT CGTGGGCATT GTTGCTGGCC TGGCTGTCCT
 AGCAGTTGTG GTCATCGGAA TTGTGGTCGC TGCTGTGATG TGTAGGAGGA
 AGAGCTCAGG TGGGAAAGGA GGGAGCTACT CTCAGGCTGC GTCCAGCGAC
 AGTGCCCAGG GCTCTGATGT GTCTCTCACG GCTTGA* 
>DL;IPD:MHC01431
IPD:MHC01431 Popy-B*06:02 575 bases
 GGCCCTGGCC CCGACCGAGA CCTGGGCCGG CTCCCACTCC ATGAGGTATT
 TCGACACCTC CGTGTCCCGG CCCGGCCGCG GGGAGCCCCG CTTCATCTCC
 GTGGGCTACG TGGACGACAC CCAGTTCGTG CGGTTCGACA GCGACGCTGC
 GAGTCCGAGG ATGGAGCCGC GGGCGCCATG GATAGAGCAG GAGGGGCCGG
 AGTATTGGGA CCAGGAGACA CAGAAAGCCA AGACCAGCAC ACAGACTGAC
 CGAGAGAACC TGCGGATCCT GCGCGGCTAC TACAACCAGA GCGAGGACGG
 GTCTCACACC ATCCAGAGGA TGTATGGCTG CGACGTGGGG CCGGATGGGC
 GACTCCTCCG CGGGTATGAC CAGTTCGCCT ACGACGGCAA GGATTACATC
 GCCCTGAACG AGGACCTGAG CTCCTGGACC GCCGCGGACA TGGCGGCTCA
 GATCACCCAG CGCAAGTGGG AGGCGGCCCG TTGGGCGGAG CAGTTGAGAC
 CCTACCTGGA GGGCCTGTGC GTGGAGTGGC TCCGCAGATA CCTGGAGAAC
 GGGAAGGAGA CGCTGCAGCG CGCGG*  
>DL;IPD:MHC00932
IPD:MHC00932 Popy-B*07:01 1086 bases
 CGGGTCATGG CGCCCCGAAC CCTCCTCCTG CTGCTCTCGG CGGCCCTGGC
 CCCGACCGAG ACCTGGGCCG GCTCCCACTC CATGAGGTAT TTCGACACCT
 CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC GCTTCATCTC CGTGGGCTAT
 GTGGACGACA CCCAGTTCGT GCGGTTCGAC AGCGACGCTG CGAGTCCGAG
 GATGGAGCCG CGGGCGCCAT GGATAGAGCA GGAGGGGCCG GAGTATTGGG
 ACCAGGAGAC ACAGAAAGCC AAGGCCAACA CACAGACTGA CCGAGAGAAC
 CTGCGGACCG CGCTCCGCTA CTACAACCAG AGCGAGGACG GGTCTCACAC
 CTGGCAGAGG ATGTATGGCT GCGACGTGGG GCCGGATGGG CGACTCCTCC
 GCGGGTATTG CCAGTTCGCC TACGACGGCA AGGATTACAT CGCCCTGAAC
 GAGGACCTGA GCTCTTGGAC CGCCGCGGAC ATGGCGGCTC AGATCACCCA
 GCGCAAGTGG GAGGCGGCCC GTGAGGCGGA GCAGTTGAGA CCCTACCTGG
 AGGGCCTGTG CGTGGAGTGG CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG
 ACGCTGCAGC GCGCGGACCG CCCAAAGACA CACGTGACCC ACCACCCTGT
 CTCTGAACAT GAGACCACCC TGAGGTGCTG GGCCCTGGGC TTCTACCCTG
 CGGAGATCAC ACTGACCTGG CAGCGGGATG GGGAGGACCA AACTCAGGAC
 ACCGAGCTTG TGGAGACCAG GCCAGCAGGA GATGGAACCT TCCAGAAGTG
 GGCAGCTGTG GTGGTGCCTT CTGGAGAAGA GCAGAGATAC ACATGCCATG
 TGCAGCATGA GGGGCTGCCG GAGCCCCTTA CTCTGAGATG GAAGCCATCT
 TCCCAGTCCA CCATCCCCAT CGTGGGCATT GTTGCTGGCC TGGCTGTCCT
 AGCAGTTGTG GTCATCGGAA TTGTGGTCGC TGCTGTGATG TATAGGAGGA
 AGAGCTCAGG TGGGAAAGGA GGGAGCTACT CTCAGGCTGC GTCCAGCGAC
 AGTGCCCAGG GCTCTGATGT GTCTCTCACG GCTTGA* 
>DL;IPD:MHC00933
IPD:MHC00933 Popy-B*08:01 1089 bases
 ATGCGGGTCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CGGGGGCCCT
 GGCCCCGACC GAGACCTGGG CCGGCTCCCA CTCCATGAGG TATTTCAGCA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CGCAGTGGGC
 TACGTGGACG ACACCCAGTT CGTGCGGTTC GACAGCGACG CCGCGAGTCC
 GAGGGTGGAG CCGCTGGTGC CATTGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCAGGA GACACAGAAA GCCAAGACCC AGGCACAGAA TGACCGAGTG
 AGCCTGCAGA ACCTGCGCGG CTACTACAAC CAGAGCGAGG ACGGGTCTCA
 CACCTGGCAG AGGATGTATG GCTGCGACGT GGGGCCCGAC GGGCGCCTTC
 TCCGTGGGTA TTGCCAGTTC GCCTACGACG GCAAGGATTA CATCGCCCTG
 AACGAGGACC TGAGCTCTTG GACCGCCGCG GACACCGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCCGTGAGGC GGAGCAGTTG AGAGCCTACC
 TGGAGGGCCT GTGCGTGGAG TCGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACATTGC AGCGCGCGGA CTGCCCAAAG ACACACGTGA CCCACCACCC
 CGTCTCTGAA CATGAGACTA TCCTGAGATG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAAACTCAG
 GACACCGAGC TTGTGGAGAC CAGGCCAGCA GGAGATGGAA CCTTCCAGAA
 GTGGGCAGCG GTGGTGGTGC CTTCTGGAGA AGAGCAGAGA TACACATGCC
 ATGTGCAGCA CGAGGGGCTG CCGGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGT CCACCATCCC CATCGTGGGC ATTGTTGCTG GCCTGGCTGT
 CCTAGCAGTT GTGGTCATCG GAATTGTGGT CGCTGCTGTG ATGTGTAGGA
 GGAAGAGCTC AGGTGGAAAA GGAGGGAGCT ACTCTCAGGC TGCGTGCAGC
 GACAGTCCCC AGGGCTCTGA TGTGTCTCTC ACGGCTTGA* 
>DL;IPD:MHC01432
IPD:MHC01432 Popy-B*09:01 575 bases
 GGTCCTGGCC CTGACCGAGA CCTGGGCGGG CTCCCACTCC ATGAAGTATT
 TCTACACGGG CATGTCCCGG CCCGGCCGCG GGGAGCCCCG CTTCATCTCC
 GTGGGCTACG TGGACGACAC GCAGTTCGTG TGGTTCGACA GCGACGCCGC
 GAGTCCGAGA GAGGAGCCGC GGGCGCCATG GATAGAGCAG GAGGGGCCGG
 AGTATTGGGA CCGGAACACA CAGATCTTCA AGACCAACAC ACAGACTTAC
 CGAGAGGGCC TGCGGATCCT GCGCGGCTAC TACAACCAAA GCGAGGACGG
 GTCTCACACC TGGCAGAGGA TGTATGGCTG CGACGTGGGG CCCGACGGGC
 GCCTCCTCCG CGGGTATGAC CAGTTCGCCT ACGACGGCAA GGATTACATC
 GCCCTGAACG AGGACCTGAG CTCCTGGACC GCCGCGGACA CCGCGGCTCA
 GATCACCCAG CGCAAGTGGG AGGCGGCCCG TGAGGCGGAG CAGTTCAGAG
 CCTACCTGGA GGGCCTGTGC GTGGAGTGGC TCCGCAGATA CCTGGAGAAC
 GGGAAGGAGA CGCTGCAGCG CGCGG*  
