>DL;IPD:MHC00943
IPD:MHC00943 Popy-DPA1*02:01 189 bases
 TTTGTACAGA CGCATAGACC GACAGGAGAG TTTATGTTTG AGTTTGATGA
 AGATGAGCAG TTCTATGTGG ATCTGGATAA GAAGGAGACC GTCTGGCATC
 TGGAGGAGTT TGGCCGAGCC TTTTCCTTTG AGGCTCAGGG CGCGCTGGCT
 AACATTGCTA TATTGAACAA CAACTTGAAT ATCATGATC* 
>DL;IPD:MHC00944
IPD:MHC00944 Popy-DPA1*02:02 189 bases
 TTTGTACAGA CGCATAGACC GACAGGGGAG TATATGTTTG AGTTTGATGA
 AGATGAGCAG TTCTATGTGG ATCTGGATAA GAAGGAGACC GTCTGGCATC
 TGGAGGAGTT TGGCCGAGCC TTTTCCTTTG AGGCTCAGGG CGCGCTGGCT
 GACATTGCTA TATTGAACAA CAACTTGAAT ATCATGATC* 
>DL;IPD:MHC00945
IPD:MHC00945 Popy-DPA1*04:01 189 bases
 TTTGTACAGA CGCATAGAAC AACAGGAGAG TTTATGTTTG AGTTTGATGA
 GGATGAGATG TTCTATGTGG ATCTGGACAA GAAGGAGACC GTCTGGCATC
 TGGAGGAGTT TGGCCGAGCC TTTTCCTTTG AGGCTCAGGG CGGGCTGGCT
 AACATTGCTA TATTGAACAA CAATTTGAAT ATCGCTATC* 
