>DL;IPD:MHC00946
IPD:MHC00946 Popy-DPB1*01 85 bases
 NYVYQGRQEC YAFNGTQRFL ERHIYNREEY VRFDSDVGEF RAVTELGRPA
 AEYWNSQKDL LEEKRAVPDR MCRHNYELDE AVTLQ* 
>DL;IPD:MHC00947
IPD:MHC00947 Popy-DPB1*02 85 bases
 NYVYQARHEC YAFNGTQRYL WRYIYNREEF VRFDSDVGEF RAVTELGRPD
 AEYWNSQKDL LEEKQAEPDR VCRHNYELEE AVTLQ* 
