>DL;IPD:MHC00940
IPD:MHC00940 Popy-DMB*01 89 bases
 GFVAHVESTC LLDDAGTPKD FTYCISFNKV LLTCWDPEEN KMAPCEFGVL
 NGVANVLSHY LNQQDTLMQR LRNGLQNCAT HTQPFWGSL* 
>DL;IPD:MHC00941
IPD:MHC00941 Popy-DMB*02 89 bases
 GFVAHVESTC LLDDAGTPKD FTYCISFNKV LLTCWDPEEN KMAPCEFGVL
 NGVANVLSHY LNQQDTLMQR LRNGLQNCAT HTQPFWGSL* 
>DL;IPD:MHC00942
IPD:MHC00942 Popy-DMB*03 89 bases
 GFVAHVESTC LLDDAGTPKD FTYCISFNKD LLTCWDPEEN KMAPCEFGVL
 NGVANVLSHY LNQQDTLMQR LRNGLQNCAT HTQPFWGSL* 
