>DL;IPD:MHC00922
IPD:MHC00922 Popy-A*01:01 1098 bases
 ATGGCGATCA TGGCGCCCCG CACCCTCCTC CTGCTACTCT CGGGGGCCCT
 GGCCCTGACC CAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCA
 CCTCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGCGAGCCA
 GAGGATGGAG CCGCGAGCGC CGTGGATGGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGGA GACACGGAGC GTGAAGGCCC ACGCACAGAC TAACCGAGTG
 GACCTGGGGA CGCTGCGCGG CTACTACAAC CAGAGCGACG GCGGTTCTCA
 CACCATCCAG AGGATGTTTG GCTGCGACGT GGGGCCCGAC GGGCGCTTCC
 TCCGCGGGTA TGAACAGCAC GCCTACGACG GCAAGGATTA CATCGCCCTA
 AACGAGGACC TGCGCTCCTG GACCGCGGCG GACATGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGCGGC GGAGCAGGAC AGAGCCTACC
 TGGAGGGCCT GTGCGTGGAG TCGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACTCTGC AGCGCACGGA CGCCCCCAAG ACACATATGA CTCACCACCC
 TGTCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAGACCCAG
 GACACGGAGC TCGTGGAGAC CAGGCCTGCA GGGGATGGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAAA GGAGCAGAGA TACACCTGCC
 ATGTGCAGCA TGAGGGTCTG CCCGAGCCCC TCACCCTGAG ATGGGAGCTG
 TCTTCCCAGC CCACCATCCC CATCGTGGGC ATCATTGCTG GCCTGGTTCT
 CCTTGGAGCT GTGATCACTG GAGCTGTGGT CGCTGCTGTG ATGTGGAGGA
 GGAGGAACTC AGATAGAAAA GGAGGGAGCT ACTCTCAGGC TGCAAGCAAT
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGTA AAGTGTGA*
>DL;IPD:MHC00923
IPD:MHC00923 Popy-A*02 1074 bases
 CTCCTCCTGC TACTCTCGGG GGCCCTGGCC CTGACCCAGA CCTGGGCGGG
 CTCCCACTCT ATGAGGTATT TCTACACCTC CGTGTCCCGG CCCGGCCGCG
 GGGAGCCCCG CTTCATCACC GTGGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCCGC GAGCCCGAGG ATGGAGCCGC GGGCGCCATG
 GATAGAGCAG GAGGGGCCGG AGTATTGGGA CCGGGAGACA CGGAGCGCGA
 AGGCCCACGC ACAGACTGAC CGAGTGGACC TGGGGACGCT GCGCGGCTAC
 TACAACCAGA GCGACGGCGG TTCTCACACC ATCCAGAGGA TGTATGGCTG
 CGACGTGGGG CCCGACGGGC GCTTCCTCCG CGGGTACCGG CAGTACGCCT
 ACGACGGCAA GGATTACATC GCCCTAAACG GGGACCTGCG CTCCTGGACC
 GCGGCGGACA TGGCGGCTCA GATCACCCAG CGCAAGTGGG AGGCGGCCGG
 TGAGGCGGAG CAGCGGAGAG CCTACCTGGA GGGCACGTGC GTGGAGTGGC
 TCCGCAGATA CCTGGAGAAC GGGAAGGAGA CTCTGCAGCG CACGGATGCC
 CCCAAGACAC ATATGACTCA CCACCGCATC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCTTGGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG GGAGGACCAG ACCCAGGACA CGGAGCTCGT GGAGACCAGG
 CCTGCAGGGG ATGGAACCTT CCAGAAGTGG GCAGCTGTGG TGGTGCCTTC
 TGGAAAGGAG CAGAGATACA CCTGCCTTGT GCAGCATGAG GGTCTGCCTG
 AGCCCCTCAC CCTGAGATGG GAGCCATCTT CCCAGCCCAC CATCCCCATC
 GTGGGCATCG TTGCTGGCCT GGTTCTTCTT GGAGCTGTGA TCACTGGAGC
 TGTGGTCGCT GCTGTGATGT GGAGGAGGAG GAGCTCAGAT AGAAAAGGAG
 GGAGCTACTC TCAGGCTGCA AGCAATGACA GTGCCCAGGG CTCTGATGTG
 TCTCTCACAG CTTGTAAAGT GTGA*  
>DL;IPD:MHC00924
IPD:MHC00924 Popy-A*03:01 1074 bases
 CTCCTCCTGC TACTCTCGGG GGCCCTGGCC CTGACCCAGA CCTGGGCGGG
 CTCCCACTCC ATGAGGTATT TCTTCACCGC CGTGTCCCGG CCCGGCCGCG
 GGGAGCCCCG CTTCATCACC GTGGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCCGC GAGCCCGAGG ATGGAGCCGC GGGCGCCATG
 GATAGAGCAG GAGGGGCCGG AGTATTGGGA CCGGGAGACA CGGAGCGCGA
 AGGCCCACGC ACAGACTGAC CGAGTGGACC TGGGGACGCT GCGCGGCTAC
 TACAACCAGA GCGACGGCGG TTCTCACACC ATCCAGAGGA TGTATGGCTG
 CGACGTGGGG CCCGACGGGC GCTTCCTCCG CGGGTACTGG CAGTACGCCT
 ACGACGGCAA GGATTACATC GCCCTAAACG GGGACCTGCG CTCCTGGACC
 GCGGCGGACA TGGCGGCTCA GATCACCCAG CGCAAGTGGG AGGTGGCCGG
 TGCGGCGGAG CAGGACAGAG CCTACCTGGA GGGCGAGTGC GTGGAGTGGC
 TCCGCAGATA CCTGGAGAAC GGGAAGGAGA CTCTGCAGCG CACGGATGCC
 CCCAAGACAC ATATGACTCA CCACCGCATC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCTTGGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG GGAGGACCAG ACCCAGGACA CGGAGCTCGT GGAGACCAGG
 CCTGCAGGGG ATGGAACCTT CCAGAAGTGG GCAGCTGTGG TGGTGCCTTC
 TGGAAAGGAG CAGAGATACA CCTGCCTTGT GCAGCATGAG GGTCTGCCTG
 AGCCCCTCAC CCTGAGATGG GAGCCATCTT CCCAGCCCAC CATCCCCATC
 GTGGGCATCG TTGCTGGCCT GGTTCTTCTT GGAGCTGTGA TCACTGGAGC
 TGTGGTCGCT GCTGTGATGT GGAGGAGGAG GAGCTCAGAT AGAAAAGGAG
 GGAGCTACTC TCAGGCTGCA AGCAATGACA GTGCCCAGGG CTCTGATGTG
 TCTCTCACAG CTTGTAAAGT GTGA*  
>DL;IPD:MHC04094
IPD:MHC04094 Popy-A*03:02 1098 bases
 ATGGCGGTCA TGGCGCCCCG AACCCTCCTC CTGCTACTCT CGGGGGCCCT
 GGCCCTGACC CAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCTTCA
 CCGCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGCGAGCCC
 GAGGATGGAG CCGCGGGCGC CATGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGGA GACACGGAGC GCGAAGGCCC ACGCACAGAC TGACCGAGTG
 GACCTGGGGA CGCTGCGCGG CTACTACAAC CAGAGCGACG GCGGTTCTCA
 CACCATCCAG AGGATGTATG GCTGCGACGT GGGGCCCGAC GGGCGCTTCC
 TCCGCGGGTA CTGGCAGTAC GCGTACGACG GCAAGGATTA CATCGCCCTA
 AACGGGGACC TGCGCTCCTG GACCGCGGCG GACATGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGCGGC GGAGCAGGAC AGAGCCTACT
 TGGAGGGCGA GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACTCTGC AGCGCACGGA TGCCCCCAAG ACACATATGA CTCACCACCG
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCTTG GGCATCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAGACCCAG
 GACACGGAGC TCGTGGAGAC CAGGCCTGCA GGGGATGGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAAA GGAGCAGAGA TACACCTGCC
 TTGTGCAGCA TGAGGGTCTG CCTGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGC CCACCATCCC CATCGTGGGC ATCGTTGCTG GCCTGGTTCT
 TCTTGGAGCT GTGATCACTG GAGCTGTGGT CGCTGCTGTG ATGTGGAGGA
 GGAGGAGCTC AGATAGAAAA GGAGGGAGCT ACTCTCAGGC TGCAAGCAAT
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGTA AAGTGTGA*
>DL;IPD:MHC04095
IPD:MHC04095 Popy-A*04:01 1097 bases
 ATGGCGGTCA TGGCGCCTCG AACCCTCATC CTGCTACTCT CGGGGGCCCT
 GGCCCTGACC CAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCTACA
 CCTCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGCGAGCCA
 GAGGATGGAG CCGCGGACGC CGTGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGAA TACACGGAAC GTGAAGGCCC ACGCACAGAC TGGCCGAGTG
 AACCTGGGGA CGCTGCGCGG CTACTACAAC CAGAGCGACG GCGGTTCTCA
 CACCATCCAG ATAATGTATG GCTGCGACGT GGGGCCCGAC GGGCGCTTCC
 TCCGCGGGTA CCGGCAGGAC GCCTACGCGG CAAGGATTAC ATCGCCCTAA
 ACGAGGACCT GCGCTCCTGG ACCGCGGCGG ACATGGCGGC TCAGATCACC
 CAGCGCAAGT GGGAGGCGGC CGGTGCGGCG GAGCAGCGGA GAGCCTACCT
 GGAGGGCCTG TGCGTGGAGT CGCTCCGCAG ATACCTGGAG AACGGGAAGG
 AGACTCTGCA GCGCACGGAC GCCCCCAAGA CACATATGAC TCACCACCGC
 ATCTCTGACC ATGAGGCCAC CCTGAGGTGC TGGGCCTTGG GCTTCTACCC
 TGCGGAGATC ACACTGACCT GGCAGCGGGA TGGGGAGGAC CAGACCCAGG
 ACACGGAGCT CGTAGAGACC AGGCCTGCAG GGGATGGAAC CTTCCAGAAG
 TGGGCAGCTG TGGTGGTGCC TTCTGGAAAG GAGCAGAGAT ATACCTGCCT
 TGTGCAGCAT GAGGGTCTGC CTGAGCCCCT CACCCTGAGA TGGGAGCCAT
 CTTCCCAGCC CACCATCCCC ATCGTGGGCA TCGTTGCTGG CCTGGTTCTT
 CTTGGAGCTG TGATCACTGG AGCTGTGGTC GCTGCTGTGA TGTGGAGGAG
 GAGGAGCTCA GATAGAAAAG GAGGGAGCTA CTCTCAGGCT GCAAGCAATG
 ACAGTGCCCA GGGCTCTGAT GTGTCTCTCA CAGCTTGTAA AGTGTGA*
>DL;IPD:MHC04096
IPD:MHC04096 Popy-A*04:02 1098 bases
 ATGGCGGTCA TGGCGCCTCG AACCCTCATC CTGCTACTCT CGGGGGCCCT
 GGCCCTGACC CAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCTACA
 CCTCCGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CGCCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGCGAGCCA
 GAGGATGGAG CCGCGGACGC CGTGGATAGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGAA TACACGGAAC GTGAAGGCCC ACGCACAGAC TGACCGAGTG
 GACCTGGGGA CGCTGCGCGG CTACTACAAC CAGAGCGAGG ACGGTTCTCA
 CACCATCCAG ATAATGTATG GCTGCGACGT GGGGCCCGAC GGGCGCTTCC
 TCCGCGGGTA CCGGCAGGAC GCCTACGACG GCAAGGATTA CATCGCCCTA
 AACGAGGACC TGCGCTCCTG GACCGCGGCG GACATGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGCGGC GGAGCAGCGG AGAGCCTACC
 TGGAGGGCCT GTGCGTGGAG TCGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACTCTGC AGCGCACGGA CGCCCCCAAG ACACATATGA CTCACCACCG
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCTTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAGACCCAG
 GACACGGAGC TCGTAGAGAC CAGGCCTGCA GGGGATGGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAAA GGAGCAGAGA TATACCTGCC
 TTGTGCAGCA TGAGGGTCTG CCTGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGC CCACCATCCC CATCGTGGGC ATCGTTGCTG GCCTGGTTCT
 TCTTGGAGCT GTGATCACTG GAGCTGTGGT CGCTGCTGTG ATGTGGAGGA
 GGAGGAGCTC AGATAGAAAA GGAGGGAGCT ACTCTCAGGC TGCAAGCAAT
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGTA AAGTGTGA*
>DL;IPD:MHC04093
IPD:MHC04093 Popy-A*05:01 1098 bases
 ATGGCGGTCA TGGCGCCCCG AACCCTCATC CTGCTACTCT CGGGGGCCCT
 GGCCCTGACC CAGACCTGGG CAGGCTCCCA CTCCATGAGG TATTTCTTCA
 CATCTGTGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CACCGTGGGC
 TACGTGGACG ACACGCAGTT CGTGCGGTTC GACAGCGACG CCGCGAGCCA
 GAGGATGGAG CCGCGGACGC CGTGGATGGA GCAGGAGGGG CCGGAGTATT
 GGGACCGGGA GACACGGAGC GCGAAGGCCC GGGCACAGAC TGACCGCATG
 AACCTGGGAA CGCTGCGCGA CTACTACAAC CAGAGCGAGG ACGGTTCTCA
 CACCATCCAG ATAATGTATG GCTGCGACGT GGGGCCCGAC GGGCGCTTCC
 TCCACGGGTA CCGGCAGGAC GCCTACGACG GCAAGGATTA CATCGCCCTA
 AACGAGGACC TGCGCTCCTG GACCGCGGCG GACATGGCGG CTCAGATCAC
 CCAGCGCAAG TGGGAGGCGG CCGGTGTGGC GGAGCAGCAG AGAGCCTACC
 TGGAGGGCAC GTGCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACTCTGC AGCGCACGGA CGCCCCCAAG ACACATATGA CTCACCACCG
 CATCTCTGAC CATGAGGCCA CCCTGAGGTG CTGGGCCTTG GGCTTCTACC
 CTGCGGAGAT CACACTGACC TGGCAGCGGG ATGGGGAGGA CCAGACCCAG
 GACACGGAGC TCGTAGAGAC CAGGCCTGCA GGGGATGGAA CCTTCCAGAA
 GTGGGCAGCT GTGGTGGTGC CTTCTGGAAA GGAGCAGAGA TACACCTGCC
 TTGTGCAGCA TGAGGGTCTG CCTGAGACCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGC CCACCATCCC CATCGTGGGC ATCGTTGCTG GCCTGGTTCT
 TCTTGGAGCT GTGATCACTG GAGCTGTGGT CGCTGCTGTG ATGTGGAGGA
 GGAGGAGCTC AGATAGAAAA GGAGGGAGCT ACTCTCAGGC TGCAAGCAAT
 GACAGTGCCC AGGGCTCTGA TGTGTCTCTC ACAGCTTGTA AAGTGTGA*
>DL;IPD:MHC04978
IPD:MHC04978 Popy-Ap*01:01 1050 bases
 CTCTCAGGGG CTCTGGCCCT GACCGAGTCC TGGGCGAGCT CCCACTCCAT
 GTGGTGTTTC GACATCTCCG AGTCCCGGCC CGGCCGCGGG GAGCCCCGCT
 TCATCTCCGT GGGCTACGTG GACGACACGC AGTTCGTGCA GTTCGACAGC
 GACGCCGCGA GTCCGAGAGA GGAGCCGTGG GCGCCATGGA TGGAGCAGGA
 GGGGCCCGAG TATTGGGACC GGAACACACA GATCTCCAAG ACCCAGGCAC
 AGACTGACCG AGTGAACATG CGGACCCTGC TCCGTTACTA CAACCAGAGC
 TAGGGCGGTT CTCACACCAT CCAGACGAGG TATGGCTGCG AAGTGGGGTC
 GGACGGGCGC CTCCTCGCGG GTATGAACAG CTTGCCTACG ACGGCAAGAA
 TTACATCGTC CTGAACGAGG ACCTGCGCTC TTGGACCGCG GCGGACATGG
 CGACTCAGAT CACCCAGAGC AAGTGGGAGG CGGCCCGTGT GGCGGAGCAG
 CAGAAAGCCT ACCTGGAGGG CGAGTGCGTG GAGTGGCTCC GCAGATACCT
 GGAGAACGGG AAGGAGACTC TACAGCGCAC GGACGCCCCC GAGACACATA
 TGACTCACCA CCGTGTCTCT GACCATGAGG CCACCCTGAG GTGCTGGGCC
 CTGGGCTTCT ACCCTGCGGA GATCACACTG ACCTGGCAGC GGGATGGGGA
 GGACCAGACC CAGGACACGG AGCTCGTGGA GACCAGGCCT GCAGGGGATG
 GAACCTTCCA GAAGTGGGCA GCTGTGGTGG TGCCTTCTGG AAAGGAGCAG
 AGATACACCT ACCTTGTGCA ACATGAGGGT CTGCCTGAGC CCCTCACCCT
 AAGATGGGAG CCGTCTTCCC AGCCCACCAT CCCCATCGTG GTCATCATTG
 CTGGCCTGGT TCTGCTTGGA GCTGTGATCA CCGGCTGCTA TGATATGGAG
 GAGGAAGAGC TCAGATAGAA AAGGAGGGAG CTACTCTCAG GCTGCAAGCA
 GTGACAGTGC CCAGGACTCT GATGTGTCTC TTATAGCTTG TAAAGTGTGA
>DL;IPD:MHC04980
IPD:MHC04980 Popy-Ap*02:01 1082 bases
 CCGAACCCTT CTCCTGGTGC TCTCAGGGGC TCTGGCCCTG ACCGAGACCT
 GGGCGGGCTC CCACTCCATG TGGTGTTTCG ACACCTCCGA GTCCCGGCCC
 GGCCGCGGGG AGCCCCGCTT CATCTCCGTG GGCTACGTGG ACGACATGCA
 GTTCGTGCAG TTCGACAGCG ACGCCGCGAG TCCGAGAGAG GAGCCGTGGG
 CGCCATGGAT GGAGCAGGAG GGGCCCGAGT ATTGGGACCG GAACACACAG
 ATCTCCAAGA CCCAGGCACA GACTGACCGA GTGAACATGC AGACCCTGCT
 CCGTTACTAC AACCAGAGCT AGGGCGATTC TCACACCATC CAGACGCTGT
 ATGGCTGCGA AGTGGGGTCG GACGGGCGCC TCCTCGCGGG TATGAACAGC
 TTGCCTACGA CGGCAAGGAT TACATCGCCC TAAACGAGGA CCTGCGCTCT
 TGGACCGCGG CGGACATAGC GACTCAGATC ACCCAGCGCA AGTGGGAGGC
 GGCCCGTGTG GCGGAGCAGC AGAGAGCCTA CCTGGAGGGC GAGTGCGTGG
 AATGGCTCCG CAGATACCTG GAGAACGGGA AGGAGACTCT CTACAGCGCA
 CGGATGCCCC CAAGACACAT ATGACTCACC ACCCTGTCTC TGACCATGAG
 GCCACCCTGA GGTGCTGGGC CCTGGGCTTC TACCCTGCGG AGATCACACT
 GACCTGGCAG CGGGATGGGG AGGACCAGAT CCAGGACACG GAGCTCGTGG
 AGACCAGGCC TGCAGGGGAT GGAACCTTCC AGAAGTGGGC AGCTGTGGTG
 GTGCCTTCTG GAAAGGAGCA GAGATACACC TGCCTTGTGC AGCATGAGGG
 TCTACCTGAG CCCCTTACCC TGAGATGGAA GCTGTCTTCC CAGCCCACCA
 TCCCCATCGT GGGCATCATT GCTGGCCTGG TTCTGCTTGG AGCTGTGATC
 ACTGGAGCTG TGGTCACTGC TATGATATGG AGGAGGAAGA GCTCAGATAG
 AAAAGGAGGG AGCTACTCTC AGGCTGCAAG CAGTGACAGT GCCCAGGGCT
 CTGATGTGTC TCTCATAGCT TGTAAAATGT GA* 
>DL;IPD:MHC04977
IPD:MHC04977 Popy-Ap*02:02 1063 bases
 CTCTCAGGGG CTCTGGCCCT GACCGAGACC TGGGCGGGCT CCCACTCCAT
 GTGGTGTTTC GACACCTCCG AGTCCCGGCC CGGCCGCGGG GAGCCCCGCT
 TCATCTCCGT GGGCTACGTG GACGACATGC AGTTCGTGCA GTTCGACAGC
 GACGCCGCGA GTCCGAGAGA GGAGCCGTGG GCGCCATGGA TGGAGCAGGA
 GGGGCCCGAG TATTGGGACC GGAACACACA GATCTCCAAG ACCCAGGCAC
 AGACTGACCG AGTGAACATG CAGACCCTGC TCCGTTACTA CAACCAGAGC
 TAGGGCGATT CTCACACCAT CCAGACGCTG TATGGCTGCG AAGTGGGGTC
 GGACGGGCGC CTCCTCGCGG GTATGAACAG CTTGCCTACG ACGGCAAGGA
 TTACATCGCC CTAAACGAGG ACCTGCGCTC TTGGACCGCG GCGGACATAG
 CGACTCAGAT CACCCAGCGC AAGTGGGAGG CGGCCCGTGT GGCGGAGCAG
 CAGAGAGCCT ACCTGGAGGG CGAGTGCGTG GAATGGCTCC GCAGATACCT
 GGAGAACGGG AAGGAGACTC TCTACAGCGC ACGGATGCCC CCAAGACACA
 TATGACTCAC CACCCTGTCT CTGACCATGA GGCCACCCTG AGGTGCTGGG
 ACCTGGGCTT CTACCCTGCG GAGATCACAC TGACCTGGCA GCGGGATGGG
 GAGGACCAGA TCCAGGACAC GGAGCTCGTG GAGACCAGGC CTGCAGGGGA
 TGGAACCTTC CAGAAGTGGG CAGCTGTGGT GGTGCCTTCT GGAAAGGAGC
 AGAGATACAC CTGCCTTGTG CAGCATGAGG GTCTACCTGA GCCCCTTACC
 CTGAGATGGA AGCTGTCTTC CCAGCCCACC ATCCCCATCG TGGGCATCAT
 TGCTGGCCTG GTTCTGCTTG GAGCTGTGAT CACTGGAGCT GTGGTCACTG
 CTATGATATG GAGGAGGAAG AGCTCAGATA GAAAAGGAGG GAGCTACTCT
 CAGGCTGCAA GCAGTGACAG TGCCCAGGGC TCTGATGTGT CTCTCATAGC
 TTGTAAAATG TGA*   
>DL;IPD:MHC04975
IPD:MHC04975 Popy-Ap*03:01 1050 bases
 CTCTCAGGGG CTCTGGCCCT GACCGAGTCC TGGGCGAGCT CCCACTCCAT
 GTGGTGTTTC GACATCTCCG AGTCCCGGCC CGGCCGCGGG GAGCCCCGCT
 TCATCTCCGT GGGCTACGTG GACGACACGC AGTTCGTGCA GTTCGACAGC
 GACGCCGCGA GTCCGAGAGA GGAGCCGTGG GCGCCATGGA TGGAGCAGGA
 GGGGCCCGAG TATTGGGACC GGAACACACA GATCTCCAAG ACCCAGGCAC
 AGACTGACCG AGTGAACATG CGGACCCTGC TCCGTTACTA CAACCAGAGC
 TAGGGCGGTT CTCACACCAT CCAGACGAGG TATGGCTGCG AAGTGGGGTC
 GGACGGGCGC CTCCTCGCGG GTATGAACAG CTTGCCTACG ACGGCAAGAA
 TTACATCGTC CTGAACGAGG ACCTGCGCTC TTGGACCGCG GCGGACATGG
 CGACTCAGAT CACCCAGAGC AAGTGGGAGG CGGCCCGTGT GGCGGAGCAG
 CAGAGAGCCT ACCTGGAGGG CGAGTGCGTG GAGTGGCTCC GCAGATACCT
 GGAGAACGGG AAGGAGACTC TACAGCGCAC GGACGCCCCC AAGACACATA
 TGACTCACCA CCGTGTCTCT GACCATGAGG CCACCCTGAG GTGCTGGGCC
 CTGGGCTTCT ACCCTGCGGA GATCACACTG ACCTGGCAGC GGGATGGGGA
 GGACCAGACC CAGGACACGG AGCTCGTGGA GACCAGGCCT GCAGGGGATG
 GAACCTTCCA GAAGTGGGCA GCTGTGGTGG TGCCTTCTGG AAAGGAGCAG
 AGATACACCT GCCTTGTGCA GCATGAGGGT CTGCCTGAGC CCCTCACCCT
 GAGATGGGAG CCGTCTTCCC AGCCCACCAT CCCCATCGTG GTCATCATTG
 CTGGCCTGGT TCTGCTTGGA GCTGTGATCA CCGGCTGCTA TGATATGGAG
 GAGGAAGAGC TCAGATAGAA AAGGAGGGAG CTACTCTCAG GCTGCAAGCA
 GTGACAGTGC CCAGGACTCT GATGTGTCTC TTATAGCTTG TAAAGTGTGA
>DL;IPD:MHC04979
IPD:MHC04979 Popy-Ap*04:01 1099 bases
 ATGGCGGTCA TGGCGCCCCG AACCCTTCTC CTGGTGCTCT CAGGGGCTCT
 GGCCCTGACC GAGACCTGGG CGGGCTCCCA CTCCATGTGG TGTTTCGACA
 CCTCCGAGTC CCGGCCCGGC CGCGGGGAGC CCCGCTTCAT CTCCGTGGGC
 TACGTGGACG ACATGCAGTT CGTGCAGTTC GACAGCGACG CCGCGAGTCC
 GAGAGAGGAG CCGTGGGCGC CATGGATGGA GCAGGAGCGG CCCGAGTATT
 GAGACCGGAA CACACAGATC TCCAAGACCC AGGCACAGAC TGACCGAGTG
 AACATGCAGA CCCTGCTCCG TTACTACAAC CAGAGCTAGG GCGATTCTCA
 CACCATCCAG AAGCTGTATG GCTGCGAAGT GGGGTCGGAC GGGCGCCTCC
 TCGCGGGTAT GAACAGCTTG CCTACGACGG CAAGGATTAC ATCGTCCTGA
 ACGAGGACCT GCGCTCTTGG ACCGCGGCGG ACATAGCGAC TCAGATCACC
 CAGCGCAAGT GGGAGGCGGC CCGTGTGGCG GAGCAGCAGA GAGCCTACCT
 GGAGGGCGAG TGCGTGGAAT GGCTCCGCAG ATACCTGGAG AACGGGAAGG
 AGACTCTCTA CAGCGCACGG ACACCCCCAA GACACATATG ACTCACCATC
 CTGTCTCTGA CCATGAGGCC ACCCTGAGGT ACTGGGCCCT GGGCTTCTAC
 CCTGCGGAGA TCACAGTGAC CTGGCAGCAG GATGGGGAGG ACCAGATCCA
 GGACACGGAG CTCGTGGAGA CCAGGCCTGC AGGGGATGGA ACCTTCCAGA
 AGTGGGCAGC TGTGGTGGTG CCTTCTGGAA AGGAGCAGAG ATACACCTGC
 CTTGTGCAGC ATGAGGGTCT GCCTGAGCCC CTTACCCTGA GATGGAAGCT
 GTCTTCCCAG CCCACCATCC CCATCGTGGG CATCATTGCT GGCCTGGTTC
 TGCTTGGAGC TGTGATCACT GGAGCTGTGG TCACTGCTAT GATATGGAGG
 AGGAAGAGCT CAGATAGAAA AGGAGGGAGC TACTCTCAGG CTGCAAGCAG
 TGACAGTGCC CAGGGCTCTG ATGTGTCTCT CATAGCTTGT AAAATGTGA*
>DL;IPD:MHC04976
IPD:MHC04976 Popy-Ap*05:01 1063 bases
 CTCTCAGGGG CTCTGGCCCT GACCGAGACC TGGGCGGGCT CCCACTCCAT
 GTGGTGTTTC GACACCTCCG AGTCCCGGCC CGGCCGCGGG GAGCCCCGCT
 TCATCTCCGT GGGCTACGTG GACGACACGC AGTTCGTGCA GTTCGACAGC
 GACGCCGCGA GTCCGAGAGA GGAGCCGTGG GCGCCATGGA TGGAGCAGGA
 GCGGCCCGAG TATTGGGACC GGAACACACA GATCTCCAAG ACCCAGGCAC
 AGACTGACCG AGTGAACATG CGGACCCAGC TCCGTTACTA CAACCAGAGC
 TAGGGCGATT CTCACACCAT CCAGAAGCTG TATGGCTGCG AAGTGGGGTC
 GGACGGGCGC CTCCTCGCGG GTATGAACAG CTTGCCTACG ACGGCAAGGA
 TTACATCGTC CTGAACGAGG ACCTGCGCTC TTGGACCGCA GCGGACATAG
 CGACTCAGAT CACCCAGCGC AAGTGGGAGG TGGCCCGTGT GGCGGAGCAG
 CAGAGAGCCT ACCTGGAGGG CGAGTGCGTG GAATGGCTCC GCAGATACCT
 GGAGAACGGG AAGGAGACTC TCTACAGCGC ACGGACGCCT CCAAGACACA
 TATGACTCAC CACCCTGTCT CTGACCATGA GGCCACCCTG AGGTGCTGGG
 CCCTGGGCTT CTACCCTGCG GAGATCACAC TGACCTGGCA GCGGGATGGG
 GAGGACCAGA TCCAGGACAC GGAGCTCGTG GAGACCAGGC CTGCAGGGGA
 TGGAACCTTC CAGAAGTGGG CAGCTGTGGT GGTGCCTTCT GGAAAGGAGC
 AGAGATACAC CTGCCTTGTG CAGCATGAGG GTCTGCCTGA GCCCCTTACC
 CTGAGATGGA AGCTGTCTTC CCAGCCCACC ATCCCCATCG TGGGCATCAT
 TGCTGGCCTG GTTCTGCTTG GAGCTGTGAT CACTGGAGCT GTGGTCACTG
 CTATGATATG GAGGAGGAAG AGCTCAGATA GAAAAGAAGG GAGCTACTCT
 CAGGCTGCAA GCAGTGACAG TGCCCAGGGC TCTGATGTGT CTCTCATAGC
 TTGTAAAATG TGA*   
>DL;IPD:MHC04974
IPD:MHC04974 Popy-Ap*06:01 1063 bases
 CTCTCAGGGG CTCTGGCCCT GACCGAGACC TGGGCGGGCT CCCACTCCAT
 GTGGTGTTTC GACACCTCCG AGTCCCGGCC CGGCCGCGGG GAGCCCCGCT
 TCATCTCCGT GGGCTACGTG GACGACATGC AGTTCGTGCA GTTCGACAGC
 GACGCCGCGA GTCCGAGAGA GGAGCCGTGG GCGCCATGGA TGGAGCAGGA
 GGGGCCCGAG TATTGGGACC GGAACACACA GATCTCCAAG ACCCAGGCAC
 AGACTGACCG AGTGAACATG CGGACCCTGC TCCGTTACTA CAACCAGAGC
 TAGGGCGGTT CTCACACCAT CCAGACGCTG TATGGCTGCG AAGTGGGGTC
 GGACGGGCGC CTCCTCGCGG GTATGAACAG CTTGCCTACG ACGGCAAGGA
 TTACATCGTC CTGAACGAGG ACCTGCGCTC TTGGACCGCA GCGGACATGG
 CGACTCAGAT CACCCAGCGC AAGTGGGAGG CGGCCCGTGT GGCGGAGCAG
 CAGAGAGCCT ACCTGGAGGG TGAGTGCGTG GAATGGCTCC GCAGATACCT
 GGAGAACGGG AAGGAGACTC TCTACAGCGC ACGGACGCCC CCAAGACACA
 TATGACTCAC CACCGCATCT CTGACCATGA GGCCACCCTG AGGTGCTGGG
 CCCTGGGCTT CTACCCTGCG GAGATCACAC TGACCTGGCA GCGGGATGGG
 GAGGACCAGA TCCAGGACAT GGAGCTCGTG GAGACCAGGC CTGCAGGGGA
 TGGAACCTTC CAGAAGTGGG CAGCTGTGGT GGTGCCTTCT GGAAAGGAGC
 AGAGATACAC CTGCCTTGTG CAGCATGAGG GTCTGCCTGA GCCCCTTACC
 CTGAGATGGA AGCTGTCTTC CCAGCCCACC ATCCCCATCG TGGGCATCAT
 TGCTGGCCTG GTTCTGCTTG GAGCTGTGAT CACTGGAGCT GTGGTCGCTG
 CTGTGATGTG GAGGAGGAAG AGCTCAGATA GAAAAGGAGG GAGATACTCT
 CAGGCTGCAA GCAGTGACAG TGCCCAGGGC TCTGATGTGT CTCTCATAGC
 TTGTAAAATG TGA*   
