>DL;IPD:MHC00965
IPD:MHC00965 Popy-H*01 270 bases
 GCTCCCACTC CATGTGGTGT TTCGACACCT CCGAGTCCCG GCCCGGCCGC
 GGGGAGCCCC GCTTCATCTC CGTGGGCTAC GTGGACGACA TGCAGTTCGT
 GCAGTTCGAC AGCGACGCCG CGAGTCCGAG AGAGGAGCCG TGGGCGCCAT
 GGATGGAGCA GGAGGGGCCG GAGTATTGGG ACCGGAACAC ACAGATCTCC
 AAGACCCAGG CACAGACTGA CCGAGTGAAC ATGCAGACCC TGCTCCGTTA
 CTACAACCAG AGCTAGGGCG *  
