>DL;IPD:MHC04978
IPD:MHC04978 Popy-Ap*01:01 102 bases
 LSGALALTES WASSHSMWCF DISESRPGRG EPRFISVGYV DDTQFVQFDS
 DAASPREEPW APWMEQEGPE YWDRNTQISK TQAQTDRVNM RTLLRYYNQS
 X**    
>DL;IPD:MHC04980
IPD:MHC04980 Popy-Ap*02:01 108 bases
 RTLLLVLSGA LALTETWAGS HSMWCFDTSE SRPGRGEPRF ISVGYVDDMQ
 FVQFDSDAAS PREEPWAPWM EQEGPEYWDR NTQISKTQAQ TDRVNMQTLL
 RYYNQSX**    
>DL;IPD:MHC04977
IPD:MHC04977 Popy-Ap*02:02 102 bases
 LSGALALTET WAGSHSMWCF DTSESRPGRG EPRFISVGYV DDMQFVQFDS
 DAASPREEPW APWMEQEGPE YWDRNTQISK TQAQTDRVNM QTLLRYYNQS
 X**    
>DL;IPD:MHC04975
IPD:MHC04975 Popy-Ap*03:01 102 bases
 LSGALALTES WASSHSMWCF DISESRPGRG EPRFISVGYV DDTQFVQFDS
 DAASPREEPW APWMEQEGPE YWDRNTQISK TQAQTDRVNM RTLLRYYNQS
 X**    
>DL;IPD:MHC04979
IPD:MHC04979 Popy-Ap*04:01 85 bases
 MAVMAPRTLL LVLSGALALT ETWAGSHSMW CFDTSESRPG RGEPRFISVG
 YVDDMQFVQF DSDAASPREE PWAPWMEQER PEYX** 
>DL;IPD:MHC04976
IPD:MHC04976 Popy-Ap*05:01 102 bases
 LSGALALTET WAGSHSMWCF DTSESRPGRG EPRFISVGYV DDTQFVQFDS
 DAASPREEPW APWMEQERPE YWDRNTQISK TQAQTDRVNM RTQLRYYNQS
 X**    
>DL;IPD:MHC04974
IPD:MHC04974 Popy-Ap*06:01 102 bases
 LSGALALTET WAGSHSMWCF DTSESRPGRG EPRFISVGYV DDMQFVQFDS
 DAASPREEPW APWMEQEGPE YWDRNTQISK TQAQTDRVNM RTLLRYYNQS
 X**    
