>DL;IPD:MHC00946
IPD:MHC00946 Popy-DPB1*01 257 bases
 AGAATTACGT GTACCAGGGA CGGCAGGAAT GCTACGCGTT TAATGGGACA
 CAGCGCTTCC TGGAGAGACA CATCTACAAC CGGGAGGAGT ACGTGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 CTGCGGAGTA CTGGAACAGC CAGAAGGACC TCCTGGAGGA GAAGAGGGCA
 GTGCCGGACA GGATGTGCAG ACACAACTAC GAGCTGGACG AGGCCGTGAC
 CCTGCAG*    
>DL;IPD:MHC00947
IPD:MHC00947 Popy-DPB1*02 257 bases
 AGAATTACGT GTACCAGGCA CGGCATGAAT GCTACGCGTT TAATGGGACA
 CAGCGCTACC TGTGGAGATA CATCTACAAC CGGGAGGAGT TCGTGCGCTT
 CGACAGCGAC GTGGGGGAGT TCCGGGCGGT GACGGAGCTG GGGCGGCCTG
 ATGCGGAGTA CTGGAACAGC CAGAAGGACC TCCTGGAGGA GAAGCAGGCA
 GAGCCGGACA GGGTGTGCAG ACACAACTAC GAGCTGGAAG AGGCCGTGAC
 CCTGCAG*    
