>DL;IPD:MHC00948
IPD:MHC00948 Popy-DQA1*01:01 188 bases
 TCTTACGGTC CCTCTGGCCA GTTCACCCAT GAATTTGATG GAGACGAGCA
 GTTCTACGTG GACCTGGAGA AGAAGGAGAC TGCCTGGCGG TGGCCTGAGT
 TACGCAATTT TGGAGGTTTT GACCCGCAGG GCGCACTGAG AAACTTGGCT
 GTGTCAAAAT ACAACTTGAA CCTCATGATT AAACGCTA* 
>DL;IPD:MHC00949
IPD:MHC00949 Popy-DQA1*05:01 185 bases
 TCTTACGGTT CCTTTGGCCA GTACACCCAT GAATTTGATG GAGACGAGCA
 GTTCTACGTG GACCTGGGGA GGAAGGAGAC TGTCTGGTGG TTGCCTGTTC
 TCAGCCAATT TAGTTTTGAC CCGCAATTTG CACTGACAAA CATTGCCGTG
 GGAAAACATA ACTTGAACTT CCTGATTAAA CGCTC* 
>DL;IPD:MHC00950
IPD:MHC00950 Popy-DQA1*21:01 188 bases
 TCTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGGA
 GTTCTATGTG GACCTGGAGA GGAAGGAGAC TGTCTGGCAG TTGCCTCTGT
 TCATCAAATT TAGAAGATTT GACCCACAAG GTGCACTGAG AAACATCATT
 GTGGGAAAAC ACAATTTGGA CATCCTGATT AAATGCTC* 
>DL;IPD:MHC00951
IPD:MHC00951 Popy-DQA2*01:01 188 bases
 TCTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGACGAGGA
 GTTCTACGTG GACCTGGAGA CGAAGGAGAC CATCTGGCAG TTGCCTATGT
 TTAGCAAATT TATAAGTTTT GACCCGCAGA GTGCACTGAG AAATATGGCT
 GTGGGAAAAC ACACCTTGGA ATTCATGATT AAACAGTC* 
