>DL;IPD:MHC00966
IPD:MHC00966 Safu-G*03:01 996 bases
 CTCCTCCTGT TGCTCTCGGG GACCCTGGTC CTGACTGAGA CCTGGGCGGG
 CTCCCACTCC ATGAGGTATT TCTGCACCGC CGTGTCCCGG CCGGGCCGCG
 GGGAGCCCCG CTTCATCGCC GTAGGCTACG TGGACGACAC GCAATTCGTG
 CGGTTCGACA GCGACGCCGC GAGTCCGAGG ATGGAGCCGC GGGCACCGTG
 GGTGGAGCAG GAGGAGCCGG AGTATTGGGA GGAGCAGACA CGGACAGCCA
 AGGCCCACGC ACAGACTTTC CGAGTGAACC TGCAGACCGC GCTCGGCTAC
 TACAACCAGA GCGAGGCCGG GTCTCACACC ATCCAGTGGA TGTCTGGCTG
 CGACCTGGGG TCGGACGGGC GCCTCCTCCG CGGGTATTAC CAGTTCGCCT
 ACGACGGCAA GGACTACATC GCCCTGAATG AGGACCTGCG CTCCTGGACG
 GCCGCGGACG TGGCGGCTCA GATCACCCAG CGCAAGTGGG AGGCGGCCAA
 TGAGGCTGAG GGGAGGAGAG CCTACCTGGA GGGCACGTGC GTGGACTGGC
 TCCACAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CGCCGAGCCC
 CCTAAGACAC ACGTGACCCA CCACCCTGTC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG GGAGGACCAG ACACAGGACA TGGAGCTTGT AGAGACCAGG
 CCAGCAGGGG ATGGAACCTT CCAGAAGTGG GCGGCTGTGG TGGTGCTTTC
 TGGAGAGGAG CACAGATACA CATGCCATGT GCAGCACAAG GGGCTGCCCA
 AGCCCCTCAC CCTGAGATGG GAGCCACCTT CCCAGCCCAC CATGCCCACA
 ATCATGGGCA TCGTTGCTAT CTTGGCTATC CTTGGAGCTG TAGTCACTGG
 AGCTGTGGTC GCTGCTGTGA TGTGGAGGAA GAAGAGCTCA GATAAA*
>DL;IPD:MHC00967
IPD:MHC00967 Safu-G*03:02 993 bases
 CTCCTCCTGT TGCTCTCGGG GGCCCTGGTC CTGACTGAGA CCTGCGCCGG
 CTCCCACTCC ATGAGGTATT TCAGCACCAC CGTGTCCCGG CCGGGCCGCG
 GGGAGCCCCG GTACATCGAA GTCGGCTACG TGGACGACAC GCAATTCGTG
 CGGTTCGACA GCGACGCCGC GAGTCCGAGG ATGGAGCCGC GGTCGCCGTG
 GGTGGAGCAG GAGGGGCCGG AGTATTGGGA GGAGGAGACA CGGAGAGCCA
 AGCGTAACGC ACAGACTTTC CGAGTGAACC TGCAGACCCT GCTCGGCTAC
 TACAACCAGA GCGAGGCCGG GTTTCACACC ATCCAGTGGA TGTATGGCTG
 CGACTTGGGG CCGGACTGGC GCCTCCTCCG CGGGTATTAC CAGTACGCCT
 ACGACGGCAA GGACTACATC GCCCTGAACG AGGACCTGCG CTCCTGGACG
 GCCGCGGACG TGGCGGCTCA GAGCACCCAG CGCAAGTGGG AGGCGGCCAA
 TGAGGCTGAG AGGATGAGAG CCTACCTGGA GGGCAGGTGC CTGGAGTGGC
 TCCTCAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGGC CGCGGAGCCC
 CCTAAGACAC ACGTGACCCA CCACCCTGTC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA TTGACCTGGC
 AGCGGGATGG GGAGGACCAG ACACAGGACA TGGAGCTCGT AGAGACCAGG
 CCAGCAGGGG ATGGAACCTT CCAGAAGTGG GCGGCTGTGG TGGTGCTTTC
 TGGAGAGGAG CACAGATACA CATGCCATGT GCAGCACGAG GGGCTGCCCG
 AGCCCCTCAC CTTGAGATGG GAGCCACCTT CCCAGCCCAC CATCCCCATC
 ATGGGCATCG TTGCTATCTT GGCTATCCTT GGAGCTGTAG TCACTGGAGC
 TGTGGTCGCT GCTGTGATGT GGAGGAAGAA GAGCTCAGAT AAA*
>DL;IPD:MHC00968
IPD:MHC00968 Safu-G*03:03 993 bases
 CTCCTCCTGT TGCTCTCGGG GGCCCTGGTC CTGACTGAGA CCTGGGCCGG
 CTCCCACTCC ATGAGGTATT TCAGCACCAC CGTGTCCCGG CCGGGCCGCG
 GGGAGCCCCG GTACATCGAA GTCGGCTACG TGGACAACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCCGC GAGTCCGAGG ATGGAGCCGC GGGCGCCGTG
 GGTGGAGCAG GAGGGGCCGG AGTATTGGGA GGAGCAGACA CGGAGAGCCA
 AGGCCCACGC ACAGACTTTC CGAGTGAACC TGCAGACCCT GCGCGGCTAC
 TACAACCAGA GCGAGGCTGG GTCTCACACC ATCCAGTGGA TGTCTGGCTG
 CGACCTGGGG CCGGACGGGC GCCTCCTCCG CGGGTATGAC CAGCACGCCT
 ACGACGGCAA GGACTACATC GCCCTGAACG AGGACCTGCG CTCCTGGACG
 GCCGCGGACG TGGCGGCTCA GATCACCCAG CGCAAGTGGG AAGCGGCCAA
 TGTGGCTGAG GAGTGGAGAG CCTACCTGGA GGGCACGTGC GTGGACTGGC
 TCCACAGATA CTTGGAGAAC GGGAAGGAGA CGCTGCAGCG CGCCGAGCCC
 CCTAAGACAC ACGTGACCCA CCACCCTGTC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG GGAGGACCAG ACACAGGACA TGGAGCTCGT AGAGACCAGG
 CCCACAGGGA ATGGAACCTT CCAGAAGTGG GCGGCTGTGG TGGTGCTTTC
 TGGAGACGAG CACAGATACA CATGCCATGT GCAGCACGAG GGGCTGCCCA
 AGCCCCTCAC CCTGAGATGG GAGCCACCTT CCCAGCCCAC CATCCCCATC
 ATGGGCATCG TTGCTATCTT GGCTATCCTT GGAGCTGTAG TCACTGGAGC
 TGTGGTCGCT GCTGTGATGT GCAGGAAGAA GAGCTCAGAT AAA*
>DL;IPD:MHC00969
IPD:MHC00969 Safu-G*03:04 990 bases
 CTCCTCCTGT TGCTCTCGGG TGCCCTGGTC CTGACTGAGA CCTGGGCCGG
 CTCCCACTCC ATGAGGTATT TCAGCACCAC CGTGTCCCGG CCGGGCCGCG
 GGGAGCCCCG CTTCATCGCC GTAGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCCGC GAGTCCGAGG ATGGAGCCGC GGTCGCCGTG
 GGTGGAGCAG GAGGGGCCGG AGTATTGGGA GGAGGAGACA CTGAAAGCCA
 AGGCCCACGC ACAGACTTTC CGAGTGAACC TGCAGACCCT GCGCGGCTAC
 TACAACCAGA GCGAGGCCGG GTCTCACACC ATCCAGTGGA TGTCTGGCTG
 CGACCTGGGG TCGGACGGGC GCCTCCTCCG CGGGTATGAC CAGATGGCCT
 ACGACGGCAA GGACTACATC GCCCTGAACG AGGACCTGCG CTCCTGGACG
 GCCGTGGACG TGGCGGCTCA GAGCACCCAG CGCAAGTGGG AGGCGGCCAA
 TGTGGCTGCG GGGTGGAGAG CCTACCTGGA GGGCGACTGC CTGGAGTGGC
 TCCACAGATA CCTGGAGAAT GGGAAGGAGA TGCTGCAGCG CGCGGAGTCC
 CCTAAGACAC ACGTGACCCA CCACCCTGTC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG GGAGGACCAG ACACAGGACA TGGAGCTCGT AGAGACCAGG
 CCCGCAGGGG ATGGAACCTT CCAGAAGTGG GCTGCTGTGG TGGTGCTTTC
 TGGAGAGGAG CACAGATACA CATGCCATGT GCAGCACGAG GGGCTGCCCG
 AGCCCCTCAC CCTGAGATGG GAGCCATCTT CCCAGCCCAC TATCACCATT
 GTGGGCATTG TTGCTGCCTT GGCTATCCTT GGAGCTGTAG TCACTGGAGC
 TGTAGTTGCT GTGATATGGA GGAAGAAGAG CTCAGACAAA *
