>DL;IPD:MHC00966
IPD:MHC00966 Safu-G*03:01 332 bases
 LLLLLSGTLV LTETWAGSHS MRYFCTAVSR PGRGEPRFIA VGYVDDTQFV
 RFDSDAASPR MEPRAPWVEQ EEPEYWEEQT RTAKAHAQTF RVNLQTALGY
 YNQSEAGSHT IQWMSGCDLG SDGRLLRGYY QFAYDGKDYI ALNEDLRSWT
 AADVAAQITQ RKWEAANEAE GRRAYLEGTC VDWLHRYLEN GKETLQRAEP
 PKTHVTHHPV SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDMELVETR
 PAGDGTFQKW AAVVVLSGEE HRYTCHVQHK GLPKPLTLRW EPPSQPTMPT
 IMGIVAILAI LGAVVTGAVV AAVMWRKKSS DK* 
>DL;IPD:MHC00967
IPD:MHC00967 Safu-G*03:02 331 bases
 LLLLLSGALV LTETCAGSHS MRYFSTTVSR PGRGEPRYIE VGYVDDTQFV
 RFDSDAASPR MEPRSPWVEQ EGPEYWEEET RRAKRNAQTF RVNLQTLLGY
 YNQSEAGFHT IQWMYGCDLG PDWRLLRGYY QYAYDGKDYI ALNEDLRSWT
 AADVAAQSTQ RKWEAANEAE RMRAYLEGRC LEWLLRYLEN GKETLQAAEP
 PKTHVTHHPV SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDMELVETR
 PAGDGTFQKW AAVVVLSGEE HRYTCHVQHE GLPEPLTLRW EPPSQPTIPI
 MGIVAILAIL GAVVTGAVVA AVMWRKKSSD K* 
>DL;IPD:MHC00968
IPD:MHC00968 Safu-G*03:03 331 bases
 LLLLLSGALV LTETWAGSHS MRYFSTTVSR PGRGEPRYIE VGYVDNTQFV
 RFDSDAASPR MEPRAPWVEQ EGPEYWEEQT RRAKAHAQTF RVNLQTLRGY
 YNQSEAGSHT IQWMSGCDLG PDGRLLRGYD QHAYDGKDYI ALNEDLRSWT
 AADVAAQITQ RKWEAANVAE EWRAYLEGTC VDWLHRYLEN GKETLQRAEP
 PKTHVTHHPV SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDMELVETR
 PTGNGTFQKW AAVVVLSGDE HRYTCHVQHE GLPKPLTLRW EPPSQPTIPI
 MGIVAILAIL GAVVTGAVVA AVMCRKKSSD K* 
>DL;IPD:MHC00969
IPD:MHC00969 Safu-G*03:04 330 bases
 LLLLLSGALV LTETWAGSHS MRYFSTTVSR PGRGEPRFIA VGYVDDTQFV
 RFDSDAASPR MEPRSPWVEQ EGPEYWEEET LKAKAHAQTF RVNLQTLRGY
 YNQSEAGSHT IQWMSGCDLG SDGRLLRGYD QMAYDGKDYI ALNEDLRSWT
 AVDVAAQSTQ RKWEAANVAA GWRAYLEGDC LEWLHRYLEN GKEMLQRAES
 PKTHVTHHPV SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDMELVETR
 PAGDGTFQKW AAVVVLSGEE HRYTCHVQHE GLPEPLTLRW EPSSQPTITI
 VGIVAALAIL GAVVTGAVVA VIWRKKSSDK * 
