>DL;IPD:MHC00972
IPD:MHC00972 Sage-PS1 836 bases
 ACCCGGGCGG GCTCCCACTC CTTGGGGTAT TTTCACACCT CTGTGTTCCA
 GCCCGGCCGC GAGAAGCCCA GCTTCATCAC CGTGGGCTAC GTGGACGACA
 CGCAGTTCGT GCGGTTCGAC AGCGACGCCG CGAGTCCGAG AGAGGAGCCG
 CGGGCGCAGT GGGTGGAGCA GGAGGGGGCG GAGTATTGGG ACCCGGAGAC
 GCGGATCTCC AAGGCCCACG CACAGAATTT CCGAGTGAAC CTGCGGACCC
 TGCGCGGCTA CTACAACCAG AGCGAGGCTG GGTCTCACAC CACCCAGGGG
 ATGTCTGGCT GCGACCTGGG GCCGGACGGG CCCCTCCTCC GTGGGTATAA
 CCAGCACCCC TAGGGCGGCA AGGACTACAT CGCCCTGAAC GAGGACCTGC
 GCTCCTGGAC GACCGCCGAC GTGGCGGTTC AGATCACCCA GTGCAAGTGG
 GAGGCGGCCA ATGTGGCTGA GGAGTGGAGA GCCTACCTGG AGGGCAGGTG
 CCTGGAGTCA CTCCTCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTTCAGC
 GCCTGGTGCC CCCCAAGACA CACGTGACCC ACCACCCCAT CTCTGACGAT
 GAGGCCACCC TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAC
 ACTGACCTGG CAGCGGGATG GGGAGGACCA GACCCGGGAC ATGGAGCTTG
 TGGAGACCAG GCCCACAGGG GATGGAAAAT TCCAGAAGTG GGCGGCTGTG
 GTGATGCCTT CTGGAGAGGA GCAGAGATAC ACATGCCATG TGCAGCACGA
 GGGGCTGGCC GAGCCCCTCA CCCTGAGATG GGAGCC* 
>DL;IPD:MHC00973
IPD:MHC00973 Sage-PS2 817 bases
 ACCCGGGCGG GCTCCCACTC CATGAGGTAT TTCTAGACCC GCGTGTCCCG
 GCCCGGCAGC GGGGAGCCCC GCTTCATCGA AGTCGGCTAC CGGGACTGTA
 CGCAGTTCAT GTGGTTCCAC AGCGAGGCAG CGATTGGGAG GATGGAGCAG
 CGGGCGCCGT GGGTGGAGCA GGAGGGGCCG GAGGATCGGG ACTGGAACGC
 ACGGAACTCC AAGGTCTCCG CACAGACTCG GCGAGTGAGC CTGCAGAACC
 AGAGCGAGGC AGGGTCTCAC ACCTACCAGA GGATGTATGG CTGCGACCCG
 GGGCCAGATG GGCGCCTCTT CCGCGGGTAT AACCAGTTCT CCTACAAGGC
 AGGGATTACA TCGCCTTGAA CGAGGACTTG CTCTTCTGGA CTGCCGCGGA
 CGCAGCGGCT CATATCGCCC AGCGCAAGTC GGAGGCGGCC AGTGAGGCGG
 AGCAAAAGAG AGCCTCCCTG GAGGGCAGGT GAGTGGAGTG GCTCCGCAGA
 TACCTGGACA AGGGGAAGGA GACGCTTCAG AGCGAGGAAC CCCCCAAGAC
 ACAAGTGACC CACCACCCCA TCTCTGACCA TGAGGCCACG CTGAGGTGCT
 GGGCCCTCAG CGTCTACCCT GCGGAGATCA CACTGACCTG TCAGCAGGAT
 GGGGAGGACC AGACCCAGGA CATGGAGCTT GTGGAGACCA GACCAGCAGG
 GCACAGAACC TTCCAGAAGT GGGCTGCTGT GGTGGTGCCT TCTGGAGAGG
 AGCAGAGATA CACGTGCCAT GTGCAGCATG AGGGGCTGCC AGAGACCCTC
 ACCCTGAGAT GGGAGCC*   
