>DL;IPD:MHC04229
IPD:MHC04229 Sala-DRB*W76:01 267 bases
 MVCLRFPGGS CVAALTVTLM VLSSPLALAG DTRPRFLEQA KSECHHFNGT
 ERVRYLQRYF HNEEELVRFD SDVGEFRAVT ELGRPEAENW NSQKDILEQK
 RAEVDTFCRH NYEILERFLV PRRVQPKVTV YPAKTQPLQH HNLLVCSVSG
 FYPGSIEVRW FRNDQEEKAG VVSTGLIQNG DWTFQTLVML ETVPQSGEVY
 ICQVEHASVT NPLTVQWRAQ SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGHSGLQ PTGLLSX*   
>DL;IPD:MHC04231
IPD:MHC04231 Sala-DRB*W76:02 267 bases
 MVCLRFPGGS CVAALTVTLM VLSSPLALAG DTRPRFLEQA KSECHHFNGT
 ERVRYLQRYF HNEEELVRFD SDVGEFRAVT ELGRPEAENW NSQKELLEQK
 RAEVDTFCRH NYEISERFLV PRRVQPKVTV YPAKTQPLQH HNLLVCSVSG
 FYPGSIEVRW FRNDQEEKAG VVSTGLIQNG DWTFQTLVML ETVPQSGEVY
 ICQVEHASVT NPLTVQWRAQ SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGHSGLQ PTGLLSX*   
>DL;IPD:MHC04233
IPD:MHC04233 Sala-DRB*W76:03 267 bases
 MVCLRFPGGS CVAALTVTLM VLSSPLALAG DTRPRFLEQG KAECHHFNGT
 ERVRYLQRYF HNEEELVRFD SDVGEFRAVT ELGRPEAENW NSQKDILEQK
 RAEVDTFCRH NYEILERFLV PRRVQPKVTV YPAKTQPLQH HNLLVCSVSG
 FYPGSIEVRW FRNDQEEKAG VVSTGLIQNG DWTFQTLVML ETVPQSGEVY
 ICQVEHASVT NPLTVQWRAQ SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNQKGHSGLQ PTGLLSX*   
>DL;IPD:MHC04232
IPD:MHC04232 Sala-DRB*W77:01 266 bases
 MVCLRFPGGS CVAALTVTLM VLSSPLALAG DSRPRFLEQM KYECHHFNGT
 EGVRLLARLI YNQEEWVRFD SDVGEFRAVT ELGRPIAENA NSRKELLEEA
 RAAVDTCRHN YEISEGFLVP RRVQPKVTVY PAKTQPLQHH NLLVCSVSGF
 YPGSIEVKWF RNDQEEKAGV VSTGLIHNGD WTFQTLVMLE TVPQSGEVYI
 CQVEHASMTS PLTVQWRAQS ESAQSKMLSG VGGFVLGLLF LGAGLFIYFR
 NQKGHSGLQP TGLLSX*   
>DL;IPD:MHC04234
IPD:MHC04234 Sala-DRB*W78:01 266 bases
 MVCLRFPGGS CVAALTVTLM VLSSPLALAG DTRPRFLVQD KCECHHFNGT
 ERVRYLERYF YNQEENLRFD SDVGEFRAVT ELGRPEAEYW NSQKDILEQK
 RATVDRCRHN YEVLERFLVP RRVQPKVTVY PAKTQPLQHH NLLVCSVSGF
 YPGSIEVRWF RNDQEEKAGV VSTGLIQNGD WTFQTLVMLE TVPQSGEVYT
 CQVEHASVTS PLTVQWRARS ESAQSKMLSG VGGFLLGLLF LGAGLFIYFR
 NQKGHSGLQP TGLLSX*   
>DL;IPD:MHC04230
IPD:MHC04230 Sala-DRB1*03:01 267 bases
 MVCLRFPGGS CVAALTVTLM VLSSPLALAG DTRPRFLEYS TSECHYFNGT
 ERVRLLERYI YNQEENLRFD SDVGEFRAVT ELGRPDEEYW NSQKELLEQR
 RAAVDTFCRH NYEISETFLV PRRVQPKVTV YPAKTQPLQH HNLLVCSVSG
 FYPGSIEVRW FRNDQEEKAG VVSTGLIQNG DWTFQTLVML ETVPQSGEVY
 TCQVEHASMT SPLTVQWRAQ SESAQSKMLS GVGGFVLGLL FLGAGLFIYF
 RNKKGHSGLQ PTGLLSX*   
