>DL;IPD:MHC04241
IPD:MHC04241 Sala-G*03:01 1078 bases
 AACCCTCCTC CTGTTGCTCT CGGGGGCCCT GGTCCTGACT GAGACCTGGG
 CGGGCTCCCA CTCCATGAGG TATTTCGAAA CCTCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CACCGTGGGC TACGTGGACG ACACGCAGTT
 CGTGCGGTTC GACAGCGACG CCGCGAGTCC GAGGATGGAG CCGCGGACGC
 CGTGGATGGA GCAGGAGGGG CCGGAGTATT GGGAGGAGGA GACACGGAAA
 GCCAAGGCCG CCGCACAGAC TTTCCGAGTG GACCTGCAGA CCGCGCTGGG
 CTACTACAAC CAGAGCGAGG CCGGGTCTCA CACTATCCAG TGGATGTATG
 GCTGCGACCT GGGGCCGGAC GGGCGCCTCC TCCGCGGGTA TGACCAGTTA
 GCCTACGACG GCAAGGACTA CATCGCCCTG AACGAGGACC TGCGCTCCTG
 GACGGCCGCG GACGTGGCGG CTCAGATCAC CCAGCGCAAG TGGGAGGCGG
 CCAATGAGGC TGAGAGGATG AGAGCCTACC TGGAGGGCAC GTGCGTGGAG
 TGGCTCCTCA GATACCTGGA GAACGGGAAG GAGACGCTGC AGCGCGCCGA
 GCCCCCTAAG ACACACGTGA CCCACCACCC TGTCTCTGAC CATGAGGCCA
 CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CACACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACACAG GACATGGAGC TCGTAGAGAC
 CAGGCCCACA GGGAATGGAA CCTTCCAGAA GTGGGCGGCT GTGGTGGTGC
 TTTCTGGAGA GGAGCACAGA TACACATGCC ATGTGCAGCA CGAGGGGCTG
 CCCGAGCCCC TCACCCTGAG ATGGGAGCCA CCTTCCCAGC CCACCATCTC
 CATCATGGGC ATCGTTGCTA TCTTGGCTAT CCTTGGAGTT GTAGTCACTG
 GAGCTGTGAT CACTGCTGTG ATGTGGAGGA AGAAGAGCTC AGATAAAAAA
 GGAGGAAGCT ACTCTCAGGC TGCAAGAAGC GACAGTGCCC AGGGCTCTGA
 TGTGTCTCTC ATGGCTTGTA AAGTGTGA*  
>DL;IPD:MHC04242
IPD:MHC04242 Sala-G*03:02 1078 bases
 AACCCTCCTC CTGTTGCTCT CGGGGGCCCT GGCCCTGACT GAGACCTGGG
 CGGGCTCCCA CTCCATGAGG TATTTCAGCA CCACCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGGTACAT CGAAGTCGGC TACGTGGACG ACACGCAGTT
 CGTGCGGTTC GACAGCGACA CCGCGAGTCC GAGGATGGAG CCGCGGGCGC
 CGTGGGTGGA GAAGGAGGGG CGGGAGTATT GGGAGGAGGA GACACAGAGA
 GCCAAGGCCT TCGCACAGAC TTTCCGAGTG AACCTGCAGA CCCTGCTCGG
 CTACTACAAC CAGAGCGAGG CCGGGTCTCA CACTATCCAG AGGATGTCTG
 GCTGCGACCT GGGGCCGGAC GGGCGCCTCC TCCGCGGGTA TGACCAGCAC
 GCCTACGACG GCAAGGACTA CATCGCCCTG AACGAGGACC TGCGCTCCTG
 GACGGCCGCT GACGTGGCGG CTCAGATCAC CCAGCGCAAG TGGGAGGCGG
 CCAATGCGGC TGAGAGGACG AGAGCCTACC TGGAGGGCAC GTGCGTGGAG
 TGGCTCCTCA GATACCTGGA GAACGGGAAG GAGACGCTGC AGCGTGCCGA
 GCCCCCTAAG ACACACGTGA CCCACCACCC TGTCTCTGAC CATGAGGCCA
 CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CACACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACACAG GACATGGAGC TCGTAGAGAC
 CAGGCCCACA GGGAATGGAA CCTTCCAGAA GTGGGCGGCT GTGGTGGTGC
 TTTCTGGAGA GGAGCACAGA TACACATGCC ATGTGCAGCA CGAGGGGCTG
 CCTGAGCCCC TCACCCTGAG ATGGGAGCCA CCTTCCCAGC CCACCATCCC
 CATCATGGGC ATCGTTGCTA TCTTGGCTAT CCTTGGAGTT GTAGTCACTG
 GAGCTGTGGT CACTGCTGTG ATGTGGAGGA AGAAGAGCTC AGATAAAAAA
 GGAGGAAGCT ACTCTCAGGC TGCAAGAAGC GACAGTGCCC AGGGCTCTGA
 TGTGTCTCTC ACGGCTTGTA AAGTGTGA*  
>DL;IPD:MHC04243
IPD:MHC04243 Sala-G*03:03 1075 bases
 AACCCTCCTC CTGTTGCTCT CGGGGGCCCT GTCCGTGACT GAGACCTGGG
 CGGGCTCCCA CTCCATGAGG TATTTCAGCA CCGCCGTGTC CCAGCCGGGC
 CGCGGGGAGC CCCGGTACAT CGAAGTCGGC TACGTGGACG ACACGCAGTT
 CGTGCGGTTC GACAGCGACG CCGCGAGTCC GAGGATGGAG CCGCGGGCGC
 CGTGGGTGGA GCAGGAGGGG CCGGAGTATT GGGTCCTGCA GACACGGAAC
 TCCAAGGCCT CCGCACAGAA TTTCCGAGTG GACCTGCAGA CCCTGCGCGG
 CTACTACAAC CAGAGCGAGG CCGGGTCTCA CACTATCCAG AGGATGTATG
 GCTGCGACCT GGGGCCCGAC GGGGGCCTCC TCCGCGGGTA TGACCAGTAC
 GCCTACGACG GCAAGGACTA CATCGCCCTG AACGAGGACC TGCGCTCCTG
 GACGGCCGCG GATGCGGCGG CTCAGATCAC CCAGCGCAAG TGGGTGGCGG
 CCAATGGGGC TGAGAGGTTG AGAGCCTACC TGGAAGGCAC GTGCGTGGAG
 TGGCTCCGCA GATACCTGGA GAACGGGAAG GAGATGCTGC AGCGCGCGGA
 GCCCCCTAAG ACACACGTGA CCCACCACCC TGTCTCTGAC CATGAGGCCA
 CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CACACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACACAG GACATGGAGC TCGTAGAGAC
 CAGGCCCACA GGGAATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC
 TTTCTGGAGA GGAGCACAAA TACACATGCC ATGTGCAGCA CGAGGGGCTG
 CCCGAGCCCC TCACCCTGAG ATGGGAGCCG CCTTCCCAGC CCACCATCCC
 CATTATGGGC ATCATTGCTG GCCTGGCTAT CCTTGGAGTT GTAGTCACTG
 CAGCTGTAGT TGCTGTGATG TGGAGGAAGA AGAGCTCAGA TAAAAAAGGA
 GGAAGCTACT CTCAGGCTGC AAGAAGCGAC AGTGCCCAGG GCTCTCATGT
 GTCTCTCATG GCTTGTAAAG TGTGA*  
>DL;IPD:MHC04244
IPD:MHC04244 Sala-G*03:04 1078 bases
 AACCCTCCTC CTGTTGCTCT CGGGGGCCCT GGTCCTGACT GAGACCTGGG
 CGGGCTCCCA CTCCATGAGG TATTTCAGCA CCACCGTGTC CCGGCCTGGC
 CGCGGGGAGC CCCGGTACAT CGAAGTCGGC TACGTGGACG ACACGCAGTT
 CGTGCGGTTC GACAGCGACG CCGCGAGTCC GAGGATGGAG CAGCGGGCGC
 CCTGGATGGA GCAGGAGGGG CCGGAGTATT GGGAGGAGGA GACACAGAGA
 GCCAAGGCCT TGGCACAGAC TTTCCGAGTG AACCTGCAGA CCCTGCTCGG
 CTACTACAAC CAGAGCGAGG CCGGGTCTCA CACCATCCAG TGGATGTATG
 GCTGCGAGCT GGGGCCGGAC GGGCGCCTCC TCCGCGGGTA TGACCAGCAC
 GCCTACGACG GCAAGGACTA CATCGCCCTG AACGAGGACC TTCGCTCCTG
 GACGGCCGCG GACGTGGCGG CTCAGATCAC CCAGCGCAAG TGGGAGGCGG
 CCAATGAGGC TGAGGGGAAG AGAGCCTACC TGGAGGGCAC GTGCGTGGAG
 TGGCTCCACA GATACCTGGA GAACGGGAAG GAGACGCTGC AGCGCGCCGA
 GCCCCCTAAG ACACACGTGA CCCACCACCC TGTCTCTGAC CATGAGGCCA
 CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CACACTGACC
 TGGCAGCAGG ATGGGGAGGA CCAGACACAG GACATGGAGC TCATAGAGAC
 CAGGCCTACA GGGAATGGAA CCTTCCAGAA GTGGGCGGCT GTGGTGGTGC
 TTTCTGGAGA GGAGCACAGA TACACATGCC ATGTGCAGCA CGAGGGGCTG
 CCCGAGCCCC TCACCCTGAG ATGGGAGCCA CCTTCCCAAC CCACCATCCC
 CATCATGGGC ATCGTTGCTA TCTTGGCTAT CCTTGGAGCT GTAGTCACTG
 GAGCTGTGGT CGCTGCTGTG ATGTGGAGGA AGAAGAGCTC AGATAAAAAA
 GGAGGAAGCT ACTCTCAGGC TGCAAGAAGC GACAGTGCCC AGGGCTCTGA
 TGTGTCTCTC ACGGCTTGTA AAGTGTGA*  
>DL;IPD:MHC04248
IPD:MHC04248 Sala-G*03:05 1078 bases
 AACCCTCCTC CTGTTGCTCT CGGGGGCCCT GGTCCTGACT GAGACCTGGG
 CGAGCTCCCA CTCCATGAGG TATTTCAGCA CCGCCGTGTC CCGGCCGGGC
 CGCGGGGAGC CCCGGTACAT CGAAGTCGGC TACGTGGACG ACACGCAGTT
 CGTGCGGTTC GACAGCGACG CCGCGAGTCC GAGGATGGAG CCGCGGGCGC
 CGTGGATGGA GCAGGAGGGG CCGGAGTATT GGGAGGAGGA GACACAGAGA
 GCCAAGGCCT TCGCACAGAT ATTCCGAGTG AACCTGCAGA CCCTGCTCGG
 CTACTACAAC CAGAGCGGGG CCGGGTCTCA CACTATCCAG ATGATGTATG
 GCTGCGACCT GGGGCCGGAC GGGCGCCTCC TCCGCGGGTA TGACCAGTTC
 GCCTACGACG GCAAGGACTA CATCGCCCTG AACGAGGACC TGCACTCCTG
 GACGGCCGCG GACGTGGCGG CTCAGATCAC ACAGCGCAAG TGGGAGGCGA
 CCAATGCGGC TGAGGAGATG AGAGCCTACC TGGAGGGCAC GTGCGTGGAG
 TGGCTCCTCA GATACCTGGA GAACGGGAAG GAGACGCTGC AGCGCGCCGA
 GCCCCCTAAG ACACACGTGA CCCACCACCC TGTCTCTGAC CATGAGGCCA
 CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CACACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACACAG GACATGGAGC TCGTAGAGAC
 CAGGCCCACA GGGAATGGAA CCTTCCATAA GTGGGCGGCT GTGGTGGTAC
 TTTCTGGAGA GGAGCAGAGA TACACATGCC ATGTGCAGCA CGAGGGGCTG
 CCCGAGCCCC TTACCCTGAG ATGGGAGCCA CCTTCCCAGC CCACCATCCC
 CATCATGGGC ATCGTTGCTA TCTTGGCTAT CCTTGGAGCT GTAGTCACTG
 GAGCTGTGGT CGCTGCTATG ATGTGGAGGA AGAAGAGCTC AGATAAAAAA
 GGAGGAAGCT ACTCTCAAGC TGCAAGAAGC GACAGTGCCC AGGGCTCTGA
 TGTGTCTCTC ACGGCTTGTA AAGTGTGA*  
>DL;IPD:MHC04249
IPD:MHC04249 Sala-G*03:06 1075 bases
 AACCCTCCTC CTGTTGCTCT CGGGGGCCCT GGCCCTGACT GAGACCTGGG
 CCGGCTCCCA CTCCATGAGG TATTTCGGCA CCGCCTTGTC CCGGCCGGGC
 CGCGGGGAGC CCCGCTTCAT CACCGTGGGC TACGTGGACG ACACGCAGTT
 CGTGCGGTTC GACAGCGACG CCGCGAGTCC GAGGATGGAG CCGCGGGCGC
 AGTGGGTGGA GCAGGAGGGG CCGGAGTATT GGGAGGAGGA GACACGGAAA
 GCCAAGGCCG CCGCACAGAC TTACCGAGTG GGCCTGCAGA CCCTGCTCGG
 CTACTACAAC CAGAGCGAGT CCGGGTCTCA CACCATCCAG TGGATGTATG
 GCTGCGACCT GGGGCCGGAC GGGCGCCTCC TCCGCGGGTA TGACCAGCAC
 GCCTACGACG GCAAGGACTA CATCGCCCTG AACGAGGACC TGCGCTCCTG
 GACTGCCGTG GACGTGGCGG CTCAGAGCAC CCAGCGCAAG TGGGTGGCGG
 CCAATGTGGC TGAGAGGATG AGAGCCTACC TAGAGGGCAG GTGCCTGGAG
 TGGCTCCTCA GATACCTGGA GAACGGGAAG GAGACGCTGC AGCGCGCGGA
 GCCCCCTAAG ACACACGTGA CCCATCACCC CGTCTCTGAC CATGAGGCCA
 CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CACATTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACATGGAGC TCGTAGAGAC
 CAGGCCCGCA GGGGATGGAA CCTTCCAGAA GTGGGCTGCT GTGGTGGTGC
 TTTCTGGAGA GGAGCACAGA TACACATGCC ATGTGCAGCA CGAGGGGCTG
 CCCGAGCCCC TCACCTTGAG ATGGGAGCCA TCTTCCCAGC CCACTATCCC
 CATTGTGGGC ATTGTTGCTG CCTTGGCTAT CCTTGGAGCT GTAGTCACTG
 GAGCTGTAGT TGCTGTGAGG TGGAGGAAGA AGAGCTCAGA CAAAAGAGGA
 GGAAACTACT CTCAGGCTGC AAGAAGCGAG AGTGCCCAGG GCTCTGATGT
 GTCTCTCATG GCTTGTAAAG TGTGA*  
>DL;IPD:MHC04250
IPD:MHC04250 Sala-G*03:07 1078 bases
 AACCCTCCTC CTGTTGCTCT CGGGGGCCCT GGTCCTGACT GAGACCTGGG
 CGGGCTCCCA CTCCATGAGG TATTTCGAAA CCTCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CACCGTGGGC TACGTGGACG ACACGCAGTT
 CGTGCGGTTC GACAGCGACG CCGCGAGTCC GAGGATGGAG CCGCGGACGC
 CGTGGATGGA GCAGGAGGGG CCGGAGTATT GGGAGGAGGA GACACGGAAA
 GTCAAGGCCC ACGCACAGAC TGACCGAATG GACCTGCAGA CCGCGCTGGG
 CTACTACAAC CAGAGCGAGG CCGGGTCTCA CACTATCCAG AGGATGTCTG
 GCTGCGACCT GGGGCCGGAC GGGCGCCTCC TCCGCGGGTA TGACCAGTTA
 GCCTACGACG GCAAGGACTA CATCGCCCTG AACGAGGACC TGCGCTCCTG
 GACGGCCGCG GACGTGGCGG CTCAGATCAC CCAGCGCAAG TGGGAGGCGG
 CCAATGAGGC TGAGAGGATG AGAGCCTACC TGGAGGGCAC GTGCGTGGAG
 TGGCTCCTCA GATACCTGGA GAACGGGAAG GAGACGCTGC AGCGCGCCGA
 GCCCCCTAAG ACACACGTGA CCCACCACCC TGTCTCTGAC CATGAGGCCA
 CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CACACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACACAG GACATGGAGC TCGTAGAGAC
 CAGGCCCACA GGGAATGGAA CCTTCCAGAA GTGGGCGGCT GTGGTGGTGC
 TTTCTGGAGA GGAGCACAGA TACACATGCC ATGTGCAGCA CGAGGGGCTG
 CCCGAGCCCC TCACCCTGAG ATGGGAGCCA CCTTCCCAGC CCACCATCTC
 CATCATGGGC ATCGTTGCTA TCTTGGCTAT CCTTGGAGTT GTAGTCACTG
 GAGCTGTGAT CACTGCTGTG ATGTGGAGGA AGAAGAGCTC AGATAAAAAA
 GGAGGAAGCT ACTCTCAGGC TGCAAGAAGC GACAGTGCCC AGGGCTCTGA
 TGTGTCTCTC ATGGCTTGTA AAGTGTGA*  
>DL;IPD:MHC04252
IPD:MHC04252 Sala-G*03:08 1075 bases
 AACCCTCCTG TTGCTCTCGG GGGCCCTGGT CCTGACTGAG ACCTGGGCGG
 GCTCCCACTC CATGAGGTAT TTCAGCACCG CCTTGTCCCG GCTGGGCCGC
 GGGGAGCCCC GCTTCATCAC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCG CGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGATGGAGCA GGAGGGGCCG GAGTATTGGG AGGAGGAGAC ACGGAAAGTC
 AAGGCCCACG CACAGACTGA CCGAATGGAC CTGCAGACCC TGCTCGGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAG CATCCAGTGG ATGTCTGGCT
 GCGACCTGGG GCCGGACGGG CGCCTCCTCC GCGGGTATGA CCAGCACGCC
 TACGACGGCA AGGACTACAT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC
 GGCCGCGGAC GTGGCGGCTC AGATCACCCA GCGCAAGTGG GAGGCGGCCA
 ATGTGGCTGA GGGGCTGAGA GCCTACCTGG AGGGCACGTG CGTGGAGTGG
 CTCCACAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCCGAGCC
 CCCTAAGACA CACGTGACCC ACCACCCTGT CTCTGACCAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG
 CAGCGGGATG GGGAGGACCA GACACAGGAC ATGGAGCTTG TAGAGACCAG
 GCCAGCAGGG GATGGAACCT TCCAGAAGTG GGCGGCTGTG GTGGTGCTTT
 CTGGAGAGGA GCACAGATAC ACATGCCATG TGCAGCACGA GGGGCTGCCT
 GAGCCCCTCA CCCTGAGATG GGAGCCACCT TCCCAGCACA TCATCCCCAT
 CATGGGCATC GTTGCTATCT TGGCTATCCT TGGAGCTGTA GTCACTGGAG
 CTGTGGTCGC TGCTGTGATG TGGAGGAAGA AGAGCTCAGA TAAAAAAGGA
 GGAAGCTACT CTCAGGCTGC AAGAAGCGAC AGTGCCCAGG GCTCTGATGT
 GTCTCTCATG GCTTGTAAAG TGTGA*  
>DL;IPD:MHC04245
IPD:MHC04245 Sala-G*03:09N 1071 bases
 AACCCTCCTC CTGTTGCTCT CGGGGGCCCT GGTCCTGACT GAGGCCTGGG
 CGGGCTCCCA CTCCATGTGG TATTTCGAAA CCTCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGGTACAT CTCCGTGGGC TACGTGGACG ACACGCAGTT
 CGTGCGGTTC GACAGCGACG CCGCGAGTCC GAGGATGGAG CCGCGGGCGC
 CGTGGATGGA GCAGGAGGGG CCGGAGTATT GGGAGGAGGA GACACGGAAA
 GCCAAGGCCG CCGCACAGAC TTTCCGAGTG AACCTGCAGA CCGCGCTCGG
 CTACTACAAC CAGAGCGAGG CCGGGTCTCA CACTATCCAG AGGATGTTTG
 GCTGCGACCT GGGGCCGGAC GGGCGCCTCC TCCGCGGGTA TGACCAGCAC
 GCCTACGACG GCAAGGACTA CATCGCCCTG AACGAGGACC TGCGCTCCTG
 GACGGCCGCG GACGTGGCGG CTCAGATCAC CCAGCGCAAG TGGGAGGCGG
 CCAATGCGGT TGAGGGGCTG AGAGCCTACC TGGAGGGCGC GTGCGTGGAG
 TGGCTCCTCA GATACCTGGA GAACGGGAAG GAGACGCTGC AGCGCGCGGA
 TCCCCCTAAG ACACACGTGA CCCACCACCC TGTCTCTGAC CATGAGGCCA
 CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CACACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACATGGAGC TTGTGGAGAC
 CAGGCCAGCA GGGGATGGAA CCTTCCAGAA GTGGGCGGCT GTGGTGGTGC
 TTTCTGGAGA GGAGCACAGA TACACATGCC ATGTGCAGCA TGAGGGGCTG
 CCCGAGCCCC TCACCCTGAG ATGGGAGCCA CCTTCCCAAC CCACCATATG
 GGCATCGTTG CTATCTTGGC TATCCTTGGA GTTCTAGTCA CTGGAGCTGT
 GGTCACTGCT GTGATGTGGA GGAAGAAGAG CTCAGATAAA AAAGGAGGAA
 GCTACTCTCA GGCTGCAAGA AGCGACAGTG CCCAGGGCTC TGATGTGTCT
 CTCACAGCTT GTAAAGTGTG A*  
>DL;IPD:MHC04246
IPD:MHC04246 Sala-G*03:10N 1068 bases
 AACCCTCCTG TTGCTCTCGG GGGCCCTGGT CCTGACTGAG ACCTGGGCGG
 GCTCCCACTC CATGAGGTAT TTCGAAACCT CCGTGTCCCG GCCCGGCCGC
 GGGGAGCCCC GGTACATCTC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCG CGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGATGGAGCA GGAGGGGCCG GAGTATTGGG AGGAGGAGAC ACGGAAAGCC
 AAGGCCGCCG CACAGACTTT CCGAGTGAAC CTGCAGACCG CGCTCGGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC TATCCAGAGG ATGTTTGGCT
 GCGACCTGGG GCCGGACGGG CGCCTCCTCC GCGGGTATGA CCAGCACGCC
 TACGACGGCA AGGACTACAT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC
 GGCCGCGGAC GTGGCGGCTC AGATCACCCA GCGCAAGTGG GAGGCGGCCA
 ATGCGGCTGA GGGGCTGAGA GCCTACCTGG AGGGCGCGTG CGTGGAGTGG
 CTCCTCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCCGAGCC
 CCCTAAGACA CACGTGACCC ACCACCCTGT CTCTGACCAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG
 CAGCGGGATG GGGAGGACCA GACCCAGGAC ATGGAGCTTG TGGAGACCAG
 GCCAGCAGGG GATGGAACCT TCCAGAAGTG GGCGGCTGTG GTGGTGCTTT
 CTGGAGAGGA GCACAGATAC ACATGCCATG TGCAGCATGA GGGGCTGCCC
 GAGCCCCTCA CCCTGAGATG GGAGCCACCT TCCCAACCCA CCATATGGGC
 ATCGTTGCTA TCTTGGCTAT CCTTGGAGTT CTAGTCACTG GAGCTGTGGT
 CACTGCTGTG ATGTGGAGGA AGAAGAGCTC AGATAAAAAA GGAGGAAGCT
 ACTCTCAGGC TGCAAGAAGC GACAGTGCCC AGGGCTCTGA TGTGTCTCTC
 ACAGCTTGTA AAGTGTGA*   
>DL;IPD:MHC04247
IPD:MHC04247 Sala-G*03:11N 1071 bases
 AACCCTCCTC CTGTTGCTCT CGGGGGCCCT GGTCCTGACT GAGACCTGGG
 CGGGCTCCCA CTCCATGAGG TATTTCGAAA CCTCCGTGTC CCGGCCCGGC
 CGCGAGGAGC CCCGGTACAT CTCCGTGGGC TACGTGGACG ACACGCAGTT
 CGTGCGGTTC GACAGCGACG CCGCGAGTCC GAGGATGGAG CCGCGGGCGC
 CGTGGATGGA GCAGGAGGGG CCGGAGTATT GGGAGGAGGA GACACGGAAA
 GCCAAGGCCG CCGCACAGAC TTTCCGAGTG AACCTGCAGA CCGCGCTCGG
 CTACTACAAC CAGAGCGAGG CCGGGTCTCA CACTATCCAG AGGATGTTTG
 GCTGCGACCT GGGGCCGGAC GGGCGCCTCC TCCGCGGGTA TGACCAGCAC
 GCCTACGACG GCAAGGACTA CATCGCCCTG AACGAGGACC TGCGCTCCTG
 GACGGCCGCG GACGTGGCGG CTCAGATCAC CCAGCGCAAG TGGGAGGCGG
 CCAATGCGGT TGAGGGGCTG AGAGCCTACC TGGAGGGCGC GTGCGTGGAG
 TGGCTCCTCA GATACCTGGA GAACGGGAAG GAGACGCTGC AGCGCGCGGA
 GCCCCCTAAG ACACACGTGA CCCACCACCC TGTCTCTGAC CATGAGGCCA
 CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CACACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACATGGAGC TTGTGGAGAC
 CAGGCCAGCA GGGGATGGAA CCTTCCAGAA GTGGGCGGCT GTGGTGGTGC
 TTTCTGGAGA GGAGCACAGA TACACATGCC ATGTGCAGCA TGAGGGGCTG
 CCCGAGCCCC TCACCCTGAG ATGGGAGCCA CCTTCCCAAC CCACCATATG
 GGCATCGTTG CTATCTTGGC TATCCTTGGA GTTCTAGTCA CTGGAGCTGT
 GGTCACTGCT GTGATGTGGA GGAAGAAGAG CTCAGATAAA AAAGGAGGAA
 GCTACTCTCA GGCTGCAAGA AGCGACAGTG CCCACGGCTC TGATGTGTCT
 CTCACAGCTT GTAAAGTGTG A*  
>DL;IPD:MHC04251
IPD:MHC04251 Sala-G*03:12N 1071 bases
 AACCCTCCTC CTGTTGCTCT CGGGGGCCCT GGTCCTGACT GAGACCTGGG
 CGGGCTCCCA CTCCATGAGG TATTTCGAAA CCTCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGGTACAT CTCCGTGGGC TACGTGGACG ACACGCAGTT
 CGTGCGGTTC GACAGCGACG CCGCGAGTCC GAGGATGGAG CCGCGGGCGC
 CGTGGATGGA GCAGGAGGGG CCGGAGTATT GGGAGGAGGA GACACGGAAA
 GCCAAGGCCG CCGCACAGAC TTTCCGAGTG AACCTGCAGA CCGCGCTCGG
 CTACTACAAC CAGAGCGAGG CCGGGTCTCA CACTATCCAG AGGATGTTTG
 GCTGCGACCT GGGGCCGGAC GGGCGCCTCC TCCGCGGGTA TGACCAGCAC
 GCCTACGACG GCAAGGACTA CATCGCCCTG AACGAGGACC TGCGCTCCTG
 GACAGCCGCG GACGTGGCGG CTCAGATCAC CCAGCGCAAG TGGGAGGCGG
 CCAATGCGGT TGAGGGGCTG AGAGCCTACC TGGAGGGCGC GTGCGTGGAG
 TGGCTCCTCA GATACCTGGA GAACGGGAAG GAGACGCTGC AGCGCGCGGA
 GCCCCCTAAG ACACACGTGA CCCACCACCC TGTCTCTGAC CATGAGGCCA
 CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CACACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACATGGAGC TTGTGGAGAC
 CAGGCCAGCA GGGGATGGAA CCTTCCAGAA GTGGGCGGCT GTGGTGGTGC
 TTTCTGGAGA GGAGCACAGA TACACATGCC ATGTGCAGCA TGAGGGGCTG
 CCCGAGCCCC TCACCCTGAG ATGGGAGCCA CCTTCCCAAC CCACCATATG
 GGCATCGTTG CTATCTTGGC TATCCTTGGA GTTCTAGTCA CTGGAGCTGT
 GGTCACTGCT GTGATGTGGA GGAAGAAGAG CTCAGATAAA AAAGGAGGAA
 GCTACTCTCA GGCTGCAAGA AGCGACAGTG CCCAGGGCTC TGATGTGTCT
 CTCACAGCTT GTAAAGTGTG A*  
>DL;IPD:MHC04253
IPD:MHC04253 Sala-G*03:13N 1068 bases
 AACCCTCCTG TTGCTCTCGG GGGCCCTGGT CCTGACTGAG ACCTGGGCGG
 GCTCCCACTC CATGAGGTAT TTCGAAACCT CCGTGTCCCG GCCCGGCCGC
 GGGGAGCCCC GGTACATCTC CGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGCCG CGAGTCCGAG GATGGAGCCG CGGGCGCCGT
 GGATGGAGCA GGAGGGTCCG GAGTATTGGG AGGAGGAGAC ACGGAAAGCC
 AAGGCCGCCG CACAGACTTT CCGAGTGAAC CTGCAGACCG CGCTGGGCTA
 CTACAACCAG AGCGAGGCCG GGTCTCACAC CATCCAGTGG ATGTCTGGCT
 GCGACCTGGG GCCGGACGGG CGCCTCCTCC GCGGGTATGA CCAGTACGCC
 TACGACGGCA AGGACTACAT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC
 GGCCGCGGAC GTGGCGGCTC AGATCACCCA GCGCAAGTGG GAGGCGGCCA
 ATGGGGCTGA GAGGATGAGA GCCTACCTGG AGGGCGCGTG CGTGGAGTGG
 CTCCTCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC GCGCCGAGCC
 CCCTAAGACA CACGTGACCC ACCACCCTGT CTCTGACCAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAC ACTGACCTGG
 CAGCGGGATG GGGAGGACCA GACCCAGGAC ATGGAGCTTG TGGAGACCAG
 GCCAGCAGGG GATGGAACCT TCCAGAAGTG GGCGGCTGTG GTGGTGCTTT
 CTGGAGAGGA GCACAGATAC ACATGCCATG TGCAGCATGA GGGGCTGCCC
 GAGCCCCTCA CCCTGAGATG GGAGCCACCT TCCCAACCCA CCATATGGGC
 ATTGTTGCTA TCTTGGCTAT CCTTGGAGTT GTAGTCACTG GAGCTGTGGT
 CACTGCTGTG ATGTGGAGGA AGAAGAGCTC AGATAAAAAA GGAGGAAGCT
 ACTCTCAGGC TGCAAGAAGC GACAGTGCCC AGGGCTCTGA TGTGTCTCTC
 ACAGCTTGTA AAGTGTGA*   
