>DL;IPD:MHC04229
IPD:MHC04229 Sala-DRB*W76:01 825 bases
 ATGGTGTGTC TGAGGTTCCC TGGAGGCTCC TGCGTGGCAG CGCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT GGAGCAGGCT AAGTCTGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GGTACCTGCA AAGATACTTC CATAACGAGG AGGAGTTGGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGAAGC GGAGAACTGG AACAGCCAGA AGGACATCCT GGAGCAGAAG
 CGGGCCGAGG TGGACACCTT CTGCAGACAC AACTACGAGA TTTTAGAGAG
 GTTCCTAGTG CCGCGGAGAG TCCAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAGTGGT
 TTCTACCCAG GCAGCATTGA GGTCAGGTGG TTCCGGAACG ACCAGGAGGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCCT GGTGATGCTG GAAACTGTTC CTCAGAGTGG AGAGGTTTAC
 ATCTGCCAAG TGGAGCACGC AAGTGTGACG AACCCTCTCA CAGTGCAATG
 GAGAGCGCAG TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTCGGGG
 GCTTTGTGCT GGGCCTGCTC TTCCTTGGCG CAGGGCTGTT CATCTACTTC
 AGGAATCAGA AAGGACACTC TGGACTTCAG CCAACAGGAC TCCTGAGCTG
 AAGGGAAGAT GACCACATTC AAGGA*  
>DL;IPD:MHC04231
IPD:MHC04231 Sala-DRB*W76:02 825 bases
 ATGGTGTGTC TGAGGTTCCC TGGAGGCTCC TGCGTGGCAG CGCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT GGAGCAGGCT AAGTCTGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GGTACCTGCA AAGATACTTC CATAACGAGG AGGAGTTGGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGAAGC GGAGAACTGG AACAGCCAGA AGGAACTCCT GGAGCAGAAG
 CGGGCCGAGG TGGACACCTT CTGCAGACAC AACTACGAGA TTTCAGAGAG
 GTTCCTAGTG CCGCGGAGAG TCCAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAGTGGT
 TTCTACCCAG GCAGCATTGA GGTCAGGTGG TTCCGGAACG ACCAGGAGGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCCT GGTGATGCTG GAAACTGTTC CTCAGAGTGG AGAGGTTTAC
 ATCTGCCAAG TGGAGCACGC AAGTGTGACG AACCCTCTCA CAGTGCAATG
 GAGAGCGCAG TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTCGGGG
 GCTTTGTGCT GGGCCTGCTC TTCCTTGGCG CAGGGCTGTT CATCTACTTC
 AGGAATCAGA AAGGACACTC TGGACTTCAG CCAACAGGAC TCCTGAGCTG
 AAGGGAAGAT GACCACATTC AAGGA*  
>DL;IPD:MHC04233
IPD:MHC04233 Sala-DRB*W76:03 825 bases
 ATGGTGTGTC TGAGGTTCCC TGGAGGCTCC TGCGTGGCAG CGCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT GGAGCAGGGT AAGGCTGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GGTACCTGCA AAGATACTTC CATAACGAGG AGGAGTTGGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGAAGC GGAGAACTGG AACAGCCAGA AGGACATCCT GGAGCAGAAG
 CGGGCCGAGG TGGACACCTT CTGCAGACAC AACTACGAGA TTTTAGAGAG
 GTTCCTAGTG CCGCGGAGAG TCCAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAGTGGT
 TTCTACCCAG GCAGCATTGA GGTCAGGTGG TTCCGGAACG ACCAGGAGGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCCT GGTGATGCTG GAAACTGTTC CTCAGAGTGG AGAGGTTTAC
 ATCTGCCAAG TGGAGCACGC AAGTGTGACG AACCCTCTCA CAGTGCAATG
 GAGAGCGCAG TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTCGGGG
 GCTTTGTGCT GGGCCTGCTC TTCCTTGGCG CAGGGCTGTT CATCTACTTC
 AGGAATCAGA AAGGACACTC TGGACTTCAG CCAACAGGAC TCCTGAGCTG
 AAGGGAAGAT GACCACATTC AAGGA*  
>DL;IPD:MHC04232
IPD:MHC04232 Sala-DRB*W77:01 822 bases
 ATGGTGTGTC TGAGGTTTCC TGGAGGCTCC TGCGTGGCAG CGCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACAGCCGAC
 CACGTTTCTT GGAGCAGATG AAGTATGAGT GTCATCACTT CAACGGGACG
 GAGGGTGTGC GGCTCCTGGC CAGATTAATC TATAACCAGG AGGAGTGGGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTATCGC GGAGAACGCC AACAGCCGGA AGGAACTCCT GGAGGAGGCG
 CGGGCCGCGG TGGACACCTG CAGACACAAC TACGAGATTT CAGAGGGGTT
 CCTAGTGCCG CGGAGAGTCC AACCTAAGGT GACTGTGTAT CCTGCAAAGA
 CCCAGCCCCT GCAGCACCAC AACCTCCTGG TCTGCTCTGT GAGTGGTTTC
 TACCCAGGCA GCATTGAGGT CAAGTGGTTC CGGAACGACC AGGAGGAGAA
 GGCTGGGGTG GTGTCCACAG GCCTGATCCA CAATGGAGAC TGGACATTCC
 AGACGCTGGT GATGCTGGAA ACTGTTCCTC AGAGTGGAGA GGTTTACATC
 TGCCAAGTGG AGCACGCAAG CATGACGAGC CCTCTCACAG TGCAATGGAG
 AGCGCAGTCT GAATCTGCAC AGAGCAAGAT GCTGAGTGGA GTCGGGGGCT
 TTGTGCTGGG CCTGCTCTTC CTTGGAGCAG GGCTGTTCAT CTACTTCAGG
 AATCAGAAAG GACACTCTGG ACTTCAGCCA ACAGGACTCC TGAGCTGAAG
 GGAAGATGAC CACATTCAAG GA*  
>DL;IPD:MHC04234
IPD:MHC04234 Sala-DRB*W78:01 822 bases
 ATGGTGTGTC TGAGGTTCCC TGGAGGCTCC TGCGTGGCAG CGCTGACAGT
 GACACTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT GGTGCAGGAT AAGTGTGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GGTACCTGGA AAGATACTTC TATAACCAGG AGGAGAACCT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGAAGC GGAGTACTGG AACAGCCAGA AGGACATCCT GGAGCAGAAG
 CGGGCCACGG TGGACAGATG CAGACACAAC TACGAGGTTT TAGAGAGGTT
 CCTAGTGCCG CGGAGAGTCC AACCTAAGGT GACTGTGTAT CCTGCAAAGA
 CCCAGCCCCT GCAGCACCAC AACCTCCTGG TCTGCTCTGT GAGTGGTTTC
 TATCCAGGCA GCATTGAGGT CAGGTGGTTC CGGAACGATC AGGAGGAGAA
 GGCTGGGGTG GTGTCCACAG GCCTGATCCA GAATGGAGAC TGGACATTCC
 AGACCCTGGT GATGCTGGAA ACTGTTCCTC AGAGTGGAGA GGTTTACACC
 TGCCAAGTGG AGCATGCAAG CGTGACGAGC CCTCTCACAG TGCAATGGAG
 AGCACGGTCC GAATCTGCAC AGAGTAAGAT GCTGAGTGGA GTCGGGGGCT
 TTCTGCTGGG TCTGCTCTTC CTTGGCGCAG GGCTGTTCAT CTACTTCAGG
 AATCAGAAAG GACACTCTGG ACTTCAGCCA ACAGGACTCC TGAGCTGAAG
 GGAAGATGAC CACATTCAAG GA*  
>DL;IPD:MHC04230
IPD:MHC04230 Sala-DRB1*03:01 825 bases
 ATGGTGTGTC TGAGGTTCCC TGGAGGCTCC TGCGTGGCAG CGCTGACAGT
 GACGCTGATG GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC
 CACGTTTCTT GGAGTATAGC ACGTCTGAGT GTCATTACTT CAACGGGACG
 GAGCGGGTGC GGCTCCTGGA AAGATACATC TATAACCAGG AGGAGAACCT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGA GGAGTACTGG AACAGCCAGA AGGAACTCCT GGAGCAGAGG
 CGGGCCGCGG TGGACACCTT CTGCAGACAC AACTACGAGA TTTCAGAGAC
 GTTCCTAGTG CCGCGGAGAG TCCAACCTAA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAGTGGT
 TTCTACCCAG GCAGCATTGA GGTCAGGTGG TTCCGGAACG ACCAGGAGGA
 GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCCT GGTGATGCTG GAAACTGTTC CTCAGAGTGG AGAGGTTTAC
 ACCTGCCAAG TGGAGCACGC AAGCATGACG AGCCCTCTCA CAGTGCAATG
 GAGAGCGCAG TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTCGGGG
 GCTTTGTGCT GGGTCTGCTC TTCCTTGGCG CAGGACTGTT CATCTACTTC
 AGGAATAAGA AAGGACACTC TGGACTTCAG CCAACAGGAC TCCTGAGCTG
 AAGTGAAGAT GACCACATTC AAGAA*  
