>DL;IPD:MHC04241
IPD:MHC04241 Sala-G*03:01 359 bases
 TLLLLLSGAL VLTETWAGSH SMRYFETSVS RPGRGEPRFI TVGYVDDTQF
 VRFDSDAASP RMEPRTPWME QEGPEYWEEE TRKAKAAAQT FRVDLQTALG
 YYNQSEAGSH TIQWMYGCDL GPDGRLLRGY DQLAYDGKDY IALNEDLRSW
 TAADVAAQIT QRKWEAANEA ERMRAYLEGT CVEWLLRYLE NGKETLQRAE
 PPKTHVTHHP VSDHEATLRC WALGFYPAEI TLTWQRDGED QTQDMELVET
 RPTGNGTFQK WAAVVVLSGE EHRYTCHVQH EGLPEPLTLR WEPPSQPTIS
 IMGIVAILAI LGVVVTGAVI TAVMWRKKSS DKKGGSYSQA ARSDSAQGSD
 VSLMACKVX*    
>DL;IPD:MHC04242
IPD:MHC04242 Sala-G*03:02 359 bases
 TLLLLLSGAL ALTETWAGSH SMRYFSTTVS RPGRGEPRYI EVGYVDDTQF
 VRFDSDTASP RMEPRAPWVE KEGREYWEEE TQRAKAFAQT FRVNLQTLLG
 YYNQSEAGSH TIQRMSGCDL GPDGRLLRGY DQHAYDGKDY IALNEDLRSW
 TAADVAAQIT QRKWEAANAA ERTRAYLEGT CVEWLLRYLE NGKETLQRAE
 PPKTHVTHHP VSDHEATLRC WALGFYPAEI TLTWQRDGED QTQDMELVET
 RPTGNGTFQK WAAVVVLSGE EHRYTCHVQH EGLPEPLTLR WEPPSQPTIP
 IMGIVAILAI LGVVVTGAVV TAVMWRKKSS DKKGGSYSQA ARSDSAQGSD
 VSLTACKVX*    
>DL;IPD:MHC04243
IPD:MHC04243 Sala-G*03:03 358 bases
 TLLLLLSGAL SVTETWAGSH SMRYFSTAVS QPGRGEPRYI EVGYVDDTQF
 VRFDSDAASP RMEPRAPWVE QEGPEYWVLQ TRNSKASAQN FRVDLQTLRG
 YYNQSEAGSH TIQRMYGCDL GPDGGLLRGY DQYAYDGKDY IALNEDLRSW
 TAADAAAQIT QRKWVAANGA ERLRAYLEGT CVEWLRRYLE NGKEMLQRAE
 PPKTHVTHHP VSDHEATLRC WALGFYPAEI TLTWQRDGED QTQDMELVET
 RPTGNGTFQK WAAVVVLSGE EHKYTCHVQH EGLPEPLTLR WEPPSQPTIP
 IMGIIAGLAI LGVVVTAAVV AVMWRKKSSD KKGGSYSQAA RSDSAQGSHV
 SLMACKVX*    
>DL;IPD:MHC04244
IPD:MHC04244 Sala-G*03:04 359 bases
 TLLLLLSGAL VLTETWAGSH SMRYFSTTVS RPGRGEPRYI EVGYVDDTQF
 VRFDSDAASP RMEQRAPWME QEGPEYWEEE TQRAKALAQT FRVNLQTLLG
 YYNQSEAGSH TIQWMYGCEL GPDGRLLRGY DQHAYDGKDY IALNEDLRSW
 TAADVAAQIT QRKWEAANEA EGKRAYLEGT CVEWLHRYLE NGKETLQRAE
 PPKTHVTHHP VSDHEATLRC WALGFYPAEI TLTWQQDGED QTQDMELIET
 RPTGNGTFQK WAAVVVLSGE EHRYTCHVQH EGLPEPLTLR WEPPSQPTIP
 IMGIVAILAI LGAVVTGAVV AAVMWRKKSS DKKGGSYSQA ARSDSAQGSD
 VSLTACKVX*    
>DL;IPD:MHC04248
IPD:MHC04248 Sala-G*03:05 359 bases
 TLLLLLSGAL VLTETWASSH SMRYFSTAVS RPGRGEPRYI EVGYVDDTQF
 VRFDSDAASP RMEPRAPWME QEGPEYWEEE TQRAKAFAQI FRVNLQTLLG
 YYNQSGAGSH TIQMMYGCDL GPDGRLLRGY DQFAYDGKDY IALNEDLHSW
 TAADVAAQIT QRKWEATNAA EEMRAYLEGT CVEWLLRYLE NGKETLQRAE
 PPKTHVTHHP VSDHEATLRC WALGFYPAEI TLTWQRDGED QTQDMELVET
 RPTGNGTFHK WAAVVVLSGE EQRYTCHVQH EGLPEPLTLR WEPPSQPTIP
 IMGIVAILAI LGAVVTGAVV AAMMWRKKSS DKKGGSYSQA ARSDSAQGSD
 VSLTACKVX*    
>DL;IPD:MHC04249
IPD:MHC04249 Sala-G*03:06 358 bases
 TLLLLLSGAL ALTETWAGSH SMRYFGTALS RPGRGEPRFI TVGYVDDTQF
 VRFDSDAASP RMEPRAQWVE QEGPEYWEEE TRKAKAAAQT YRVGLQTLLG
 YYNQSESGSH TIQWMYGCDL GPDGRLLRGY DQHAYDGKDY IALNEDLRSW
 TAVDVAAQST QRKWVAANVA ERMRAYLEGR CLEWLLRYLE NGKETLQRAE
 PPKTHVTHHP VSDHEATLRC WALGFYPAEI TLTWQRDGED QTQDMELVET
 RPAGDGTFQK WAAVVVLSGE EHRYTCHVQH EGLPEPLTLR WEPSSQPTIP
 IVGIVAALAI LGAVVTGAVV AVRWRKKSSD KRGGNYSQAA RSESAQGSDV
 SLMACKVX*    
>DL;IPD:MHC04250
IPD:MHC04250 Sala-G*03:07 359 bases
 TLLLLLSGAL VLTETWAGSH SMRYFETSVS RPGRGEPRFI TVGYVDDTQF
 VRFDSDAASP RMEPRTPWME QEGPEYWEEE TRKVKAHAQT DRMDLQTALG
 YYNQSEAGSH TIQRMSGCDL GPDGRLLRGY DQLAYDGKDY IALNEDLRSW
 TAADVAAQIT QRKWEAANEA ERMRAYLEGT CVEWLLRYLE NGKETLQRAE
 PPKTHVTHHP VSDHEATLRC WALGFYPAEI TLTWQRDGED QTQDMELVET
 RPTGNGTFQK WAAVVVLSGE EHRYTCHVQH EGLPEPLTLR WEPPSQPTIS
 IMGIVAILAI LGVVVTGAVI TAVMWRKKSS DKKGGSYSQA ARSDSAQGSD
 VSLMACKVX*    
>DL;IPD:MHC04252
IPD:MHC04252 Sala-G*03:08 358 bases
 TLLLLSGALV LTETWAGSHS MRYFSTALSR LGRGEPRFIT VGYVDDTQFV
 RFDSDAASPR MEPRAPWMEQ EGPEYWEEET RKVKAHAQTD RMDLQTLLGY
 YNQSEAGSHS IQWMSGCDLG PDGRLLRGYD QHAYDGKDYI ALNEDLRSWT
 AADVAAQITQ RKWEAANVAE GLRAYLEGTC VEWLHRYLEN GKETLQRAEP
 PKTHVTHHPV SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDMELVETR
 PAGDGTFQKW AAVVVLSGEE HRYTCHVQHE GLPEPLTLRW EPPSQHIIPI
 MGIVAILAIL GAVVTGAVVA AVMWRKKSSD KKGGSYSQAA RSDSAQGSDV
 SLMACKVX*    
>DL;IPD:MHC04245
IPD:MHC04245 Sala-G*03:09N 312 bases
 TLLLLLSGAL VLTEAWAGSH SMWYFETSVS RPGRGEPRYI SVGYVDDTQF
 VRFDSDAASP RMEPRAPWME QEGPEYWEEE TRKAKAAAQT FRVNLQTALG
 YYNQSEAGSH TIQRMFGCDL GPDGRLLRGY DQHAYDGKDY IALNEDLRSW
 TAADVAAQIT QRKWEAANAV EGLRAYLEGA CVEWLLRYLE NGKETLQRAD
 PPKTHVTHHP VSDHEATLRC WALGFYPAEI TLTWQRDGED QTQDMELVET
 RPAGDGTFQK WAAVVVLSGE EHRYTCHVQH EGLPEPLTLR WEPPSQPTIW
 ASLLSWLSLE FX*   
>DL;IPD:MHC04246
IPD:MHC04246 Sala-G*03:10N 311 bases
 TLLLLSGALV LTETWAGSHS MRYFETSVSR PGRGEPRYIS VGYVDDTQFV
 RFDSDAASPR MEPRAPWMEQ EGPEYWEEET RKAKAAAQTF RVNLQTALGY
 YNQSEAGSHT IQRMFGCDLG PDGRLLRGYD QHAYDGKDYI ALNEDLRSWT
 AADVAAQITQ RKWEAANAAE GLRAYLEGAC VEWLLRYLEN GKETLQRAEP
 PKTHVTHHPV SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDMELVETR
 PAGDGTFQKW AAVVVLSGEE HRYTCHVQHE GLPEPLTLRW EPPSQPTIWA
 SLLSWLSLEF X*   
>DL;IPD:MHC04247
IPD:MHC04247 Sala-G*03:11N 312 bases
 TLLLLLSGAL VLTETWAGSH SMRYFETSVS RPGREEPRYI SVGYVDDTQF
 VRFDSDAASP RMEPRAPWME QEGPEYWEEE TRKAKAAAQT FRVNLQTALG
 YYNQSEAGSH TIQRMFGCDL GPDGRLLRGY DQHAYDGKDY IALNEDLRSW
 TAADVAAQIT QRKWEAANAV EGLRAYLEGA CVEWLLRYLE NGKETLQRAE
 PPKTHVTHHP VSDHEATLRC WALGFYPAEI TLTWQRDGED QTQDMELVET
 RPAGDGTFQK WAAVVVLSGE EHRYTCHVQH EGLPEPLTLR WEPPSQPTIW
 ASLLSWLSLE FX*   
>DL;IPD:MHC04251
IPD:MHC04251 Sala-G*03:12N 312 bases
 TLLLLLSGAL VLTETWAGSH SMRYFETSVS RPGRGEPRYI SVGYVDDTQF
 VRFDSDAASP RMEPRAPWME QEGPEYWEEE TRKAKAAAQT FRVNLQTALG
 YYNQSEAGSH TIQRMFGCDL GPDGRLLRGY DQHAYDGKDY IALNEDLRSW
 TAADVAAQIT QRKWEAANAV EGLRAYLEGA CVEWLLRYLE NGKETLQRAE
 PPKTHVTHHP VSDHEATLRC WALGFYPAEI TLTWQRDGED QTQDMELVET
 RPAGDGTFQK WAAVVVLSGE EHRYTCHVQH EGLPEPLTLR WEPPSQPTIW
 ASLLSWLSLE FX*   
>DL;IPD:MHC04253
IPD:MHC04253 Sala-G*03:13N 311 bases
 TLLLLSGALV LTETWAGSHS MRYFETSVSR PGRGEPRYIS VGYVDDTQFV
 RFDSDAASPR MEPRAPWMEQ EGPEYWEEET RKAKAAAQTF RVNLQTALGY
 YNQSEAGSHT IQWMSGCDLG PDGRLLRGYD QYAYDGKDYI ALNEDLRSWT
 AADVAAQITQ RKWEAANGAE RMRAYLEGAC VEWLLRYLEN GKETLQRAEP
 PKTHVTHHPV SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDMELVETR
 PAGDGTFQKW AAVVVLSGEE HRYTCHVQHE GLPEPLTLRW EPPSQPTIWA
 LLLSWLSLEL X*   
