>DL;IPD:MHC00976
IPD:MHC00976 Saoe-DPB1*01:01 171 bases
 GTGCTCCTGG GACGGCACAA CTGCTACGCG TTTAAAGGGA CACAGCACCT
 GCTGGAGAGA CACATCTACA ACCAGGAGGA GTTCGTGCGC TTCGACAGCG
 ACCTGGGGGA GTACCGAGCG GTGACGGAGC TGGGACTGCC TGCTGCCGAG
 CACTTGAACA GCCAGAAGGA C*  
