>DL;IPD:MHC01032
IPD:MHC01032 Saoe-G*03:01 993 bases
 CTCCTCCTGT TGCTCCCGGG GGCCCTGGTC CTGACTGAGA CCTGGGCGGG
 CTCCCACTCC ATGAGGTATT TCAGCACCGC CGTGTCCCGG CCTGGCCGCG
 AGGAGCCCCG CTTCATCAAC GTGGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCCACGCCGC GAGGCCGAGG ATGGAGCCGC GGGCGCCGTG
 GATGGAGCAG GAGGGGCCGG AGTATTGGGA GGAAGAGACA CTGAAAGCCA
 AGGATTGGGC ACAGACTTAC CGAGTGAACC TGCAGACCTT GCTCGGCTAC
 TACAACCAGA GCGAGGCCGG GTCTCACACT TTGCAGTGGA TGTCTGGCTG
 CGACCTGGGG CCGGACGGGC GCCTCCTCCG CGGGTATGAG CAGTACGCCT
 ACGACTGCAA GGACTACATC GCCCTGAACG AGGACCTGCG CTCCTGGACG
 GCCGCGGACG TGGCGGCTCA GATCACCCAG CGCAAGTGGG AGGCGGCCAA
 TGCGGCTGAG GGGATGAGAG CCTACCTGGA GGGCACGTGC GTGGAGTGGC
 TCCACAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CGCCGAGCCC
 CCTAAGACAC ACGTGACCCA CCACCCTGTC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG GGAGGACCAG ACCCAGGACA TGGAGCTCGT AGAGACCAGG
 CCAGCAGGGG ATGGAACCTT CCAGAAGTGG GCGGCTGTGG TGGTGCTTTC
 TGGAGAGGAG CACAGATACA CATGCCATGT GCAGCACGAG GGGCTGCCCG
 AGCCCCTCAC CCTGAGATGG GAGCCACCTT CCCAGCCCAC CATCCCCATC
 ATGGGCATCG TTGCTATCTT GGCTATCCTT GGAGCTGTAG TCACTGGAGC
 TGTGGTCGCT GCTGTGATGT GGAGGAAGAA GAGCTCAGAT AAA*
>DL;IPD:MHC01033
IPD:MHC01033 Saoe-G*03:02 993 bases
 CTCCTCCTGT TGCTCTCGGG GGCCCTGGTC CTGACTGAGA CCTGGGCGGG
 CTCCCACTCC ATGAGGTATT TCGAAACCTC CGTGTCCCGG CCCGGCCGCG
 GGGAGCCCCG GTACATCTCC GTGGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCCGC AAGTCCGAGG ATGGAGCCGC GGGCGCCGTG
 GATGGAGCAG GAGGGGCCGG AGTATTGGGA GGAGGAGACA CGGAAAGGCA
 AGGCCGACGC ACAGACTTTC CGAGTGGGCC TGCAGACCCT GCTCGGCTAC
 TACAACCAGA GCGAGGCCGG GTCTCACACC ATCCAGTGGA TGTATGGCTG
 CGACCTGGGG CCGGACGGGC GCCTCCTCCG CGGGTATCAC CAGTACGCCT
 ACGACTGCAA GGACTACATC GCCCTGAACG AGGACCTGCG CTCCTGGACG
 GCCGCGGACG TGGCGGCTCA GATCACCCAG CGCAAGTGGG AGGCGGCCAA
 TGAGGCTGAG AGGACGAGAG CCTACCTGGA GGGCACGTGC GTGGAGTGGC
 TCCACAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CGCCGAGCCC
 CCTAAGACAC ACGTGACCCA CCATCCTGTC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA GTGACCTGGC
 AGCGGGATGG GGAGGACCAG ACACAGGACA TGGAGCTCGT AGAGACCAGG
 CCAGCAGGGG ATGGAACCTT CCAGAAGTGG GCGGCTGTGG TGGTGCTTTC
 TGGAGAGGAG CAGAGATACA CATGCCATGT GCAGCACGAG GGGCTGCCCG
 AGCCCCTCAC CCTGAGATGG GAGCCGCCTT CCCAGCCCAC CATCCCCATC
 ATGGGCATCG TTGCTATCTT GGCTATCCTT GGAGCTGTAG TCACTGGAGC
 TGTGGTCGCT GCTGTGATGT GGAGGAAGAA GAGCTCAGAT AAA*
>DL;IPD:MHC01034
IPD:MHC01034 Saoe-G*03:03 993 bases
 CTCCTCCTGT TGCTCTCGGG GGCCCTGGTC CTGACTGAGA CCTGGGCGGG
 CTCCCACTCC ATGAGGTATT TCAAAACCTC CGTGTCCCGG CCCGGCCGCG
 GGGAGCCCCG GTACATCTCC GTGGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCAGC GAGTCCGAGG ATGGAGCCGC GGGCGCCGTG
 GATGGAGCAG GAGGGTCCGG AGTATTGGGA GGAGGAGACA CGGACAGCCA
 AGGCCGCCGC ACAGACTTTC CGAGTGGACC TGCAGACCCT GCTCGGCTAC
 TACAACCAGA GCGAGGCCGG GTCTCACACC ATCCAGTGGA TGTCTGGCTG
 CGACCTGGGG CCGGACGGGC GCCTCCTCCG CGGGTATCAC CAGTACGCCT
 ACGACTGCAA GGACTACATC GCCCTGAACG AGGACCTGCG CTCCTGGACG
 GCCGCGGATG CGGCGGCTCA GATCACCCAG CGCAAGTGGG CGGAGGCCAA
 TGCGGCTGAG GGGATGAGAG CCTACCTGGA GGGCGTGTGC GTGGAGTGGC
 TCCTCAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CGCCGAGCCC
 CCTAAGACAC ACGTGACCCA CCACCCTGTC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTCGGCT TTTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG GGAGGACCAG ACACAGGACA TGGAGCTCGT AGAGACCAGG
 CCAGCAGGGG ATGGAACCTT CCAGAAGTGG GCGGCTGTGG TGGTGCTTTC
 TGGAGAGGAA CACAGATACA CATGCCATGT GCAGCACGAG GGGCTGCCCG
 AGCCCCTCAC CCTGAGATGG GAGCCACCTT CCCAGCCCAC CATCCCCATC
 ATGGGCATCG TTGCTATCTT GGCTATCCTT GGAGCTGTAG TCACTGGAGC
 TGTGGTCACT GCTGTGATGT GGAGGAAGAA GAGCTCAGAT AAA*
>DL;IPD:MHC01035
IPD:MHC01035 Saoe-G*03:04 993 bases
 CTCCTCCTGT TGCTCTCGGG GGCCCTGGTC CTGACTGAGA CCTGGGCGGG
 CTCCCACTCC ATGAGGTATT TCGAAACCTC CGTGTCCCGG CCCGGCCGCG
 GGGAGCCCCG GTACATCTCC GTGGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCCGC AAGTCCGAGG ATGGAGCCGC GGGCGCCGTG
 GATGGAGCAG GAGGGGCCGG AGTATTGGGA GGAGGAGACA CGGAAAGGCA
 AGGCCGACGC ACAGACTTTC CGAGTGGACC TGCAGACCCT GCTCGGCTAC
 TACAACCAGA GCGAGGCCGG GTCTCACACC ATCCAGTGGA TGTATGGCTG
 CGACCTGGGG CCGGACGGGC GCCTCCTCCG CGGGTATGAC CAGCACGCCT
 ACGACTGCAA GGACTACATC GCCCTGAACG AGGACCTGCG CTCCTGGACG
 GCCACGGACG TGGCGGCTCA GATCACCCAG CGCAAGTGGG AGGCGGCCAA
 TGAGGCTGAG AGGACGAGAG CCTACCTGGA GGGCACGTGC GTGGAGTGGC
 TCCACAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CGCCGAGCCC
 CCTAAGACAC ACGTGACCCA CCATCCTGTC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA GTGACCTGGC
 AGCGGGATGG GGAGGACCAG ACACAGGACA TGGAGCTCGT AGAGACCAGG
 CCAGCAGGGG ATGGAACCTT CCAGAAGTGG GCGGCTGTGG TGGTGCTTTC
 TGGAGAGGAG CAGAGATACA CATGCCATGT GCAGCACGAG GGGCTGCCCG
 AGCCCCTCAC CCTGAGATGG GAGCCGCCTT CCCAGCCCAC CATCCCCATC
 ATGGGCATCG TTGCTATCTT GGCTATCCTT GGAGCTGTAG TCACTGGAGC
 TGTGGTCGCT GCTGTGATGT GGAGGAAGAA GAGCTCAGAT AAA*
>DL;IPD:MHC01036
IPD:MHC01036 Saoe-G*03:05 993 bases
 CTCCTCCTGT TGCTCTCGGG GGCCCTGGCC CTGACTGAGA CCTGGGCCGG
 CTCCCACTCC ATGAGGTATT TCAGCACCGC CGTGTCCCGG CCTGGCCGCG
 GGGAGCCCCG CTTCATCGCC GTGGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCCGC GAGGCCGAGG ATGGAGCCGC GGGCGCCGTG
 GATGGAGCAG GAGGGGCCGG AGTATTGGGA GGAGGAGACA CGGAAAGTCA
 AGGCCCACGC ACAGATTGAC CGAATGGACC TGCAGACCCT GCTCGGCTAC
 TACAACCAGA GCCAGGCAGG GTCTCACACC ATCCAGGTGA TGTATGGCTG
 CGACCTGGGG CCGGACGGGC GCCTCCTCCG CGGGTATGAC CAGCACGCCT
 ACGACTGCAA GGACTACATC GCCCTGAACG AGGACCTGCG CTCCTGGACG
 GCCGCGGACG TGGCGGCTCA GATCACCCAG CGCAAGTGGG AGGCGGCCAA
 TGCGGCTGAG AGGACGAGAG CCTACCTGGA GGGCATGTGC GTGGAGTGGC
 TCCTCAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CGCCGAGCCC
 CCTAAGACAC ACATGACCCA CCACCCTGTC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG GGAGGACCAG ACACAGGACA TGGAGCTCGT AGAGACCAGG
 CCAGCAGGGG ATGGAACCTT CCAGAAGTGG GCGGCTGTGG TGGTGCTTTC
 TGGAGAGGAG CACAGATACA CATGCCATGT GCAGCATGAG GGGCTGCCCG
 AGCCCCTCAC CCTGAGATGG GAGCCACCTT CCCAGCCCAC CATCCCCATC
 ATGGGCATCG TTGCTATCTT GGCTATCCTT GGAGCTGTAG TCACTGGAGC
 TGTGGTCGCT GCTGTGATGT GGAGGAAGAA GAGCTCAGAT AAA*
>DL;IPD:MHC01037
IPD:MHC01037 Saoe-G*03:06 1014 bases
 ATGGTCATGG CTCCCCGAAC CCTCCTCCTG TTGCTCTCGG GGGCCCTGGC
 CCTGACTGAG ACCTGGGCGG GCTCCCACTC CATGAGGTAT TTCAGCACCG
 CCGTGTCCCG GCCGGGCCGC GAGGAGCCCC GGTACATCGA AGTCGGCTAC
 GTGGACGACA CGCAGTTCGT GCGGTTCGAC AGCGACGCCG CGAGTCCGAG
 GATGGAGCCG CGGGCGCAGT GGGTGGAGAA GGAGGGGCGG GAGTATTGGG
 AGGAGGAGAC ACAGAGAGCC AAGGCCTTCG CACAGACTTT CCGAGTGAAC
 CTCCAGACCG CGCTCGGCTA CTACAACCAG AGCGAGGCCG GGTCTCACAC
 TATCCAGATG ATGTCTGGCT GCGACCTGGG GCCGGACGGG CGCCTCCTCC
 GCGGGTATGA CCAGCACGCC TACGACTGCA AGGACTACAT CTCCCTGAAC
 GAGGACCTGC GCTCCTGGAC GGCCGCGGAC GTGGCGGCTC AGATCACCCA
 GCGCAAGTGG GAGGCGGCCA ATGAGGCTGA GAGGACGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCACAGAT ACCTGGAGAA CGGGAAGGAG
 ACGCTGCAGC GCGCCGAGCC CCCTAAGACA CACGTGACCC ACCACCCTGT
 CTCTGACCAT GAGGCCACCC TGAGGTGCTG GGCCCTGGGC TTCTACCCTG
 CGGAGATCAC ACTGACCTGG CAGCGGGATG GGGAGGACCA GACACAGGAC
 ATGGAGCTCG TAGAGACCAG GCCCACAGGG AATGGAACCT TCCAGAAGTG
 GGCAGCTGTG GTGGTGCTTT CTGGAGAGGA GCACAGATAC ACATGCCATG
 TGCAGCACGA GGGGCTGCCT GAGCCCCTCA CCCTGAGATG GGAGCCGCCT
 TCCCAGCCCA CCATCCCCAT CATGGGCATC GTTGCTATCT TGGCTATCCT
 TGGAGCTGTA GTCACTGGAG CTGTGGTCAC TGCTGTGATG TGGAGGAAGA
 AGAGCTCAGA TAAA*   
>DL;IPD:MHC01038
IPD:MHC01038 Saoe-G*03:07 993 bases
 CTCCTCCTGT TGCTCTCGGG GGCCCTGGTC CTGACTGAGA CCTGGGCGGG
 CTCCCACTCC ATGAGGTATT TCAGCACCAC CGTGTCCCGG CCGGGCCGCG
 GGGAGCCCCG GTACATCGAA GTCGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGATA GCAACGCCGC GAGTCCGAGG ATGGAGCCGC GGGCGCCGTG
 GGTGGAGCAG GAGGGGCCGG AGTATTGGGA GGAGGAGACA CAGAGAGCCA
 AGGCCTTGGC ACAGACTTTC CGAGTGAACC TGCAGACCCT GCTCCGCTAC
 TACAACCAGA GCGAGGCTGG GTCTCACACC ATCCAGTGGA TGTATGGCTG
 CTACCTGGGG CCGGACGGGC GCCTTCTCCG CGGGTATTAC CAGCACGCCT
 ACGACTGCAA GGACTACATC GCCCTGAACG AGGACCTGCG CTCCTGGACG
 GCCGCGGACT TGGCGGCTCA GATCACCCAG CGCAAGTGGG AGGCGGCCAA
 TGCGGCTGAG GAATGGAGAG CCTACCTGGA GGGCACGTGC GTGGAGTGGC
 TCCACAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CGCCGAGCCC
 CCTAAGACAC ACGTGACCCA CCACCCTGTC TCTGACCATG AGGCCACTCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG GGAGGACCAG ACACAGGACA TGGAGCTCGT AGAGACCAGG
 CCCACAGGGA ATGGAACCTT CCAGAAGTGG GCAGCTGTGG TGGTGCTTTC
 TGGAGAGGAG CACATATACA CATGCCATGT GCAGCACGAG GGGCTGCCCG
 AGCCCCTCAC CCTGAGATGG GAGCCACCTT CCCAGCCCAC CATCCCCATC
 ATGGGCATCG TTGCTATCTT GGCTATCCTT GGAGCTGTAG TCACTGGAGC
 TGTGGTCGCT GCTGTGATGT GGAGGAAGAA GAGCTCAGAT AAA*
>DL;IPD:MHC01039
IPD:MHC01039 Saoe-G*03:08 993 bases
 CTCCTCCTGT TGCTCTCGGG GGCCCTGTCC GTGACTGAGA CCTGGGCGGG
 CTCCCACTCC ATGAGGTATT TCAGCACCAC CGTGTCCCGG CCTGGCCGCG
 GGGAGCCCCG GTACATCGAA GTCGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCCGC GAGTCCGAGG ATGGAGCCGC GGGCGCCGTG
 GGTGGAGCAG GAGGGGCCGG AGTATTGGGT CCTGCAGACA CGGAACTCCA
 AGGCCTCCGC ACAGACTTTC CGAGTGAACC TGCAGACCTT GCTCGGCTAC
 TACAACCAGA GCGAGGCCGG GTTTCACACC ATCCAGTGGA TGTATGGCTG
 CGACCTGGGG CCGGACGGGC GCCTCCTCCG CGGGTATCAC CAGTACGCCT
 ACGACTGCAA GGACTACATC GCCCTGAACG AGGACCTGCG CTCCTGGACG
 GCCGCGGATG CGGCGGCTCA GATCACCCAG CGCAAGTGGG CGGAGGCCAA
 TGCGGCTGAG GGGATGAGAG CCTACCTGGA AGGCACGTGC GTGGAGTGGC
 TCCGCAGACA CCTGGAGAAC GGGAAGGAGA TGCTGCAGCG CGCGGAGCCC
 CCTAAGACAC ACGTGACCCA CCACCCTGTC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG GGAGGACCAG GCACAGGACA TGGAGCTCGT AGAGACCAGG
 CCCACGGGGA ATGGAACCTT CCAGAAGTGG GCAGCTGTGG TGGTGCTTTC
 TGGAGAGGAG CACAAATACA CATGCCATGT GCAGCACGAG GGGCTGCCCG
 AGCCCTTCAC CCTGAGATGG GAGCCGCCTT CCCAGCCCAC CATCCCCATC
 ATGGGCATCG TTGCTATCTT GGCTATCCTT GGAGCTGTAG TCACTGGAGC
 TGTGGTCGCT GCTGTGATGT GGAGGAAGAA GAGCTCAGAT AAA*
>DL;IPD:MHC01040
IPD:MHC01040 Saoe-G*03:09 993 bases
 CTCCTCCTGT TGCTCTCGGG GGCCCTGGTC CTGACTGAGA CCTGGGCGGG
 CTCCCACTCC ATGAGGTATT TCAAAACCTC CGTGTCCCGG CCCGGCCGCG
 GGGAGCCCCG GTACATCTCC GTGGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCAGC GAGTCCGAGG ATGGAGCCGC GGGCGCCGTG
 GATGGAGCAG GAGGGGCCGG ACTATTGGGA GAAGGAGACA CGGACAGCCA
 AGGCCGCCGC ACAGACTTTC CGAGTGAACC TGCAGACCCT GCTCGGCTAC
 TACAACCAGA GCGAGGCCGG GTCTCACACC ATCCAGTGGA TGTCTGGCTG
 CGACCTGGGG CCGGACGGGC GCCTCCTCCG CGGGTATGAG CAGCACGCCT
 ACGACTGCAA GGACTACATC GCCCTGAACG AGGACCTGCG CTCCTGGACG
 GCCGCGGACG TGGCGGCTCA GATCACCCAG CGCAAGTGGG AGGCGGCCAA
 TGTCGCTGAG AGGACGAGAG CCTACCTGGA GGGCATGTGC GTGGAGTGGC
 TCCTCAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CGCCGAGCCC
 CCTAAGACAC ACGTGACCCA CCACCCTGTC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTCGGCT TTTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG GGAGGACCAG ACACAGGACA TGGAGCTCGT AGAGACCAGG
 CCAGCAGGGG ATGGAACCTT CCAGAAGTGG GCGGCTGTGG TGGTGCTTTC
 TGGAGAGGAA CACAGATACA CATGCCATGT GCAGCACGAG GGGCTGCCCG
 AGCCCCTCAC CCTGAGATGG GAGCCACCTT CCCAGCCCAC CATCCCCATC
 ATGGGCATCG TTGCTATCTT GGCTATCCTT GGAGCTGTAG TCACTGGAGC
 TGTGGTCGCT GCTGTGATGT GGAGGAAGAA GAGCTCAGAT AAA*
>DL;IPD:MHC01041
IPD:MHC01041 Saoe-G*03:10 993 bases
 CTCCTCCTGT TGCTCTCGGG GGCCCTGGTC CTGACTGAGA CCTGGGCGGG
 CTCCCACTCC ATGAGGTATT TCAGCACCGC CATGTCCCGG CCGGGCCGCG
 GGGAGCCCCG GTACATCGAA GTCGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCCGC GAGTCCGAGG ATGGAGCCGC GGGCGCCGTG
 GGTGGAGAAG GAGGGGCGGG AGTATTGGGA GGAGGAGACA CAGAGAGCCA
 AGGCCTTCGC ACAGACTGAC CGAGTGAACC TGCAGACCGC GCTCGGCTAC
 TACAACCAGA GCGAGGCCGG GTCTCACACC ATCCAGTGGA TGTATGGCTG
 CGACCTGGGG CCGGACGGGC GCTTCCTCCG CGGGTATGAA CAGTTAGCCT
 ACGACTGCAA GGACTACATC GCCCTGAACG AGGATCTGCG CTCCTGGACG
 GCCGCGGACG TGGCGGCTCA GATCACCCAG CGCAAGTGGG AGGCGGCCAA
 TGCGGCTGAG GAGTGGAGAG CCTACCTGGA GGGCACGTGC GTGGAGTGGC
 TCCACAGATA CCTGGAGAAC GGGAAGGAGA CCCTGCAGCG CGCCGAGCCC
 CCTAAGACAC ACGTGACCCA CCACCCTATC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG GGAGGACCAG ACACAGGACA TGGAGCTCGT AGAGACCAGG
 CCAGCAGGGG ATGGAACCTT CCAGAAGTGG GCGGCTGTGG TGGTGCTTTC
 TGGAGAGGAG CACAGATACA CATGCCATGT GCAGCACGAG GGGCTGCCCG
 AGCCCCTCAC CCTGAGATGG GAGCCACCTT CCCAGCCCAC CATCCCCATC
 ATGGGCATCG TTGCTATGTT GGCTATCCTT GGAGCTGTAG TCACTGGAGC
 TGTGGTCACT GCTGTGATGT GGAGGAAGAA GAGCTCAGAT AAA*
>DL;IPD:MHC01042
IPD:MHC01042 Saoe-G*03:11 990 bases
 CTCCTGTTGC TCTCGGGGGC CCTGGCCCTG ACTGACACCT GGGCGGGCTC
 CCACTCCATG AGGTATTTCG AAACCTCCGT GTCCCGGCCC GGCCGCGGGG
 AGCCCCGGTA CATCGAAGTC GGCTACGTGG ACGACACGCA GTTCGTGCGG
 TTCGACAGCG ACGCCGCGAG TCCGAGGATG GAGCCGCGGG CGCCGTGGAT
 GGAGCAGGAG GGGCCGGACT ATTGGGAGAA GGAGACACGG AGAGCCAAGG
 CCGCCGCACA GACTTTCCGA GTGAACCTGC AGACCCTGCT CGGCTACTAC
 AACCAGAGCG AGGCCGGGTC TCACACCATC CAGTGGATGT ATGGCTGCGA
 CCTGGGGCCG GACGGGCGCC TCCTCCGCGG GTATGAGCAG CACGCCTACG
 ACTGCAAGGA CTACATCGCC CTGAACGAGG ATCTGCGCTC CTGGACGGCC
 GCGGACGTGG CGGCTCAGAT CACCCAGCGC AAGTGGGAGG CGGCCAATGC
 GGCTGAGAGG ACGAGAGCCT ACCTGGAGGG CACGTGCGTG GAGTGGCTCC
 ACAGATACCT GGAGAACGGG AAGGAGACGC TGCAGCGCGC CGAGCCCCCT
 AAGACACACG TGACCCACCA TCCTGTCTCT GACCATGAGG CCACCCTGAG
 GTGCTGGGCC CTGGGCTTCT ACCCTGCGGA GATCACACTG ACCTGGCAGT
 GGGATGGGGA GGACCAGACA CAGGACATGG AGCTCGTAGA GACCAGGCCA
 GCAGGGGATG GAACCTTCCA GAAGTGGGCG GCTGTGGTGG TGCTTTCTGG
 AGAGGAGCAC AGATACACAT GCCATGTGCA GCACGAGGGG CTGCCCGAGC
 CCCTCACCCT GAGATGGGAG CCGCCTTCCC AGCCCACCAT CCCCATCATG
 GGCATCGTTG CTATCTTGGC TATCCTTGGA GCTGTAGTCA CTGGAGCTGT
 GGTCGCTGCT GTGATGTGGA GGAAGAAGAG CTCAGATAAA *
>DL;IPD:MHC01043
IPD:MHC01043 Saoe-G*03:12Ps 534 bases
 GCTCTCACTC CATGAAGTAT TTCAACACTG CCAAGTCCCG GCCCGGCTGC
 GGGAAGCCCC GGTACTTCGA AGTCGGTTAC GTGGACGACA CGCAGTTCGT
 GCGGTTTGAC AGCGACGCCG CGAGTCCAAG GATGGAGCCG CGGGCGCCGT
 GGGTAGAGCA GGAGGGCCGG AGTACTGGGC CGAAGAGGAG CAGAAAGCCA
 AGGTCGACGC ACGGAATTTC CGAGGGAACC GGCGGACCCT GCGCGGCTAC
 TACAACTAGA GCGGGCCGCT TCCAGGAGAC GTATGGCTGC TCCCTGGGGT
 TTGACTAGCG CCTCCTCTGC GGATATTACC AGTTAGCCTA AGACTGCAAG
 GATTACCTCT CCCTGAACCA GGACCTTCGC TCCTGGACAG CCTCCTACAC
 AGCAGCTCAG ATCACCCAGC CCAAGTGGGA GGCGGCCAGT GTGGCGGAGC
 GGAGAAGAGC CTACCTGGAG GGGAGGTGCC TGGAGTGGCT CCGCAGACAC
 CTGGAGAACG GGAAGGAGAC GCTGCAGCGC GCGG* 
>DL;IPD:MHC01044
IPD:MHC01044 Saoe-G*03:13Ps 515 bases
 GCTCCCAGAC CATGAGGTAT TTGAGCACCC CGCTTCATCT CTGTGGGCTA
 CATGGACGAC ACGCAGATCG CGCGGTTCAA CAGAGACGCC TCGAGTCCGA
 GGATAGAGCG CGGGCGCCGT GGATGGAGAA GGAGGGGCCG GAGTGTTGGG
 ACCTGGGGAC ACGGATTTTC AAGGACACCG CACAGAGTTT CCGAGTGAAC
 CTGCAGACCC TGCGCTGCTA CTACAACCAG AGCGAAGCCA GTCCCACACC
 CTCCGGGAGA TGTATTGCTA GAACCTGGGG CCGGAAGGGC TCCTTCTCCA
 CGGATATCAC CAGTTCGCCT ATGACTGCAA GGATTAAGTC GCCCCGAACG
 AGGACCTGCG CTCCTGGACC ATCGCGGACA CTGCGGCTCA GATCACCCAG
 CGCAAGTGGG AGGTAGACAA TGTGGCGGAG AAGGTGAGAG CCTACCTGGA
 GGGCAGGTGC CTGGAGTGGA TCCGCAGACA CCTGGAGAAC GGGAAGGAGA
 CACTGGAGTG GGCGG*   
>DL;IPD:MHC01045
IPD:MHC01045 Saoe-G*03:14Ps 558 bases
 GTTCCCACTT CTTCAGGTAT TTCTACATCG CCGCTTCCCG GGCCGGGAGC
 GGGGAGTCCC GCTTCATTTA TGTGGGCTAC GTAGACGACA CGCAGTTCGT
 GCGGTTCGAC AGCGACGACG CGAGTCCGAG GATGGAGACG CGGGCGCCGT
 GGATGGAGCA AGAGGGGCCG GAGTATTGGG ACCGGGAGAC CCGGATAGCC
 AAGGCCTACG CACAGAATTT CCAAGTGAAT CTGTGGAACC TGCGCGGCCA
 CTACAACCAG AGCTAGGCTG GGTCTCACTC CATCCAGAGG ATACACAGCT
 GCGACCTGGG GCCCCACGGG CGCTTCCTCC GCGGGTATGA ACAGTTTGCC
 TACGACTGCA AAGATTATAT CGCCCTGAAT GAGGACCTGA GCTCCTGGAC
 TCCTGCCCGC CGCGGACACT GCGGCTCAGA TCACCCAGCG CAAGTGGGTG
 GCGAACAAAT ACTCAGAGCA GAGCAGGTCA GGACCTACCT GGGGGGCACG
 TGAGTGGAGT GGCTCCTTAG ACAACTGGAG GACGGGAAAA AGACGCTGCG
 TCACGCTG*    
>DL;IPD:MHC01046
IPD:MHC01046 Saoe-G*03:16Ps 501 bases
 GCTCTCACTC CTTGAGGTAT TTCCAGACCG CCGTGTCCCG GCCCGGCCTC
 GAGGAGCCCC ACTTCTTCGC CGTGGGCTAC GTGGAAGACA TGCAGTTTGA
 GCGGTTCGAC AGCGACGCCG CAATTCCGAG AGGGGAGCCG CGGACGCCTT
 GGATGGAGCA GGAGGGGCCG GAGTATTGGG ACCTGCAGAC ACGGACCCTC
 AAGGCCCGCG CACAGAGAGA GGCGAGGTCT CACACCTACC AGAGGATGTA
 TGGCTGCGAC CTGGGGCCTG ATGGGCGCCT CTTCCGCAGG TATGACAAGC
 GCGCCTACGA CTTCAAAGAT TACCTCGCCC TGAACGAGGT CCTGCGCTCT
 TGGACCGCGG CGGAAACGGC GTCTCAAGTC ACCCAGCGCA AGTTCGAGGT
 GACCCATGAG GCGGACAAGA TGAAAGCCTA CCCGGAGGGC ACGTGCGTGG
 AGTCGCTCCC CAGATAACTG GAGAACGGGA AGGTGAGGCT GCAGCGTGCA
 G*    
>DL;IPD:MHC01047
IPD:MHC01047 Saoe-G*03:17Ps 545 bases
 GCTCCCACTC CATGAGGTAT TTCAGCACCA CCGTGTCCCG GCCTGGCCAC
 GAGGAGCCCC GCTTCATCTT AGTGGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTCGAC AACGACGTCG CGATTCCGAG GATGGAGCCG CTGGCGCCGT
 GGGTGGAGCA GGAGGGGCCG GAGTATTGGG ACCTGCAGAC ACGGAGAGTC
 AAGGCCGCCG CACAGAATTT CCGAGTGAAC CTGCGGACCC TGCGCAGCTA
 CTACAACCAG AGCGAGGACG GTCTCACACT ATCCAGATGA TGTATGGCTG
 CGACCTGGGG CCAGACGGGC GCCTCCTCCG CGGGTATAAC CAGCACGCCT
 ACGACTGCAA GGAGTACATC GCCCTGAACG AGGACCTGCG CTCCTGGACG
 GCCGCGGACG TGGCGGCTCA GATCACGCAG CGCAAGTGGG AAGCGGCCAA
 TGTGGCTGAG GGGAGGAGAG CCTACCTGGA GGGCGACTGC CTGGAGTGGC
 TCCGCAGATA CCTGGAGAAC GGGAACGAGA CGCTGCAGCG CGCCG*
>DL;IPD:MHC01048
IPD:MHC01048 Saoe-G*03:18Ps 543 bases
 GCTCCCACTC CTTGAAGTAT TTCAACACTG CCAAGTCCCG GCCCGGCTGC
 GGGAAGCCCC GGTACTTCGA AGTCGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTTGAC AGCGACGCCG CGAGTCCAAG GATGGAGCCG CGGGCGCCGT
 GGGTAGAGCA GGAGGGCCGG AGTACTGGGA CCGAGAGGAG CAGAAAGCCA
 AGGTCGACGC ACGGAATTTC CGAGGGAACC GGCAGACCCT GCGCGGCTAC
 TACAACTAGA GCGGGGCCGT TGGTAGGGCT TCCAAGTGTC GTATGGCTGC
 TCCCTGGGGT CTGACTAGCG CCTCCTCTGC GGATATTACC AGTTAGCCTA
 AGACTGCAAG GATTACCTCT CCCTGAACCA GGACCTTCGC TCCTGGACAG
 CTCCTACACA GCAGCTCAGA TCACCCAGCC CAAGTGGGAA GCGGCCATTG
 TGGCGGAACA AGGAAAAACC TACCTTGAAG GCAGTTGCCT GAATTTGCTC
 CGCCGATAGC TGGAAAACGG AAAGAAAACC CTGCCACGCG CCG*
>DL;IPD:MHC01049
IPD:MHC01049 Saoe-G*03:19Ps 328 bases
 GCTCTCACTC CTTGAAGTAT TTCAACACTG CCAAGTCCCG GCCCGGCTGC
 GGGAAGCCCC GGTACTTCGA AGTCGGCTAC GTGGACGACA CGCAGTTCGT
 GCGGTTTGAC AGCGACGCCG CGAGTCCAAG GATGGAGCCG CGGGCGCCGT
 GGGTAGAGCA GGAGGGCCGG AGTACTGGGA CGAGAAGAAG CAGAAAGCCA
 AGGTCGACGC ACGGAATTTC CGAGGGAACC GGCGGACCCT GCGCGGCTAC
 TACAACTAGA GCGGGCCGGT TGGTAGGGCT TCCAGGAGAC TTATGGCTGC
 TCCCTGGGGT CTAACTACCG CCTCCTCT*  
>DL;IPD:MHC01050
IPD:MHC01050 Saoe-G*03:20Ps 327 bases
 TCCCACTCCA AGAGGTATTT CAACACTGCC AAGTCCCGGC CCGGCTGCGG
 GGAGCCCCGG TACTTCGAAG TCGGCTACGT GGACGACGCG CAGTTCGCGC
 GGTTTGACAG CGACGCCGCG AGACCAAGGA TGGAGCCGCG GGCGCCGTGG
 GTAGAGCAGG AGGGGCCGGA GTACTGGGAC CGGGAGGAGA AGAAAGCCAA
 GGTCGACGCA CGGAACTTCC GAATGAACCG GCGGACCCTG CGCGGTAAAT
 ACAACTAGAG CGGGCCGGTT GGTAGGGCTT CCAGGAGACG TATGGCTGCT
 CCCTGGGGTC TGACTAGCCC CTCACCC*  
