>DL;IPD:MHC01016
IPD:MHC01016 Saoe-DRB*W12:01 270 bases
 CACGTTTCTT GGAGCAGTTT AAGTATGAGT GTCGTCACCT CAACGGGACG
 GAGCGGGTGC GGCTCCTGGT CAGATACATC TACAACCAGG AGGAGTATGT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCGGGGGC
 GGCCTGTTGC AGAGTACTGC AACAGCCTGA AGGACTACGT GGAGCAGGAG
 CGGGCCGCGG TGGACACCGT GTGCAGACAC AACTACGAGA TTTTTGAGAG
 GTTCCTAGTG CAGCGGCGAG *  
>DL;IPD:MHC01017
IPD:MHC01017 Saoe-DRB*W12:03 228 bases
 CGTTTCTTGG AGCAGTTTAA GTATGAGTGT CGTCACCTCA ACGGGACGGA
 GCGGGTGCGG CTCCTGGTCA GATACATCTA CAACCAGGAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTGACGGA GCGGGGGCGG
 CCTGTTGCAG AGTACTTCAA CAGCCTGAAG GACTACGTGG AGCAGGAGCG
 GGCCGCGGTG GACACCGTGT GCAGACAC*  
>DL;IPD:MHC01018
IPD:MHC01018 Saoe-DRB*W12:04 228 bases
 CGTTTCTTGG AGCAGTTTAA GTATGAGTGT CGTCACCTCA ACGGGACGGA
 GCGGGTGCGG CTCCTGGTCA GATACATCTA CAACCAGGAG GAGTCTGTGC
 GCTTCGACAG CGGCATGGGG GAGTTCCGGG CGGTGACGGA GCGGGGGCGG
 CCTGTTGCAG AGTACTTCAA CAGCCTGAAG GACCTACGTG GACAGGAGCG
 GGCCGCGGTG GACACCTTGT GCAGGCAT*  
>DL;IPD:MHC01019
IPD:MHC01019 Saoe-DRB*W12:05 228 bases
 CGTTTCTTGG AGCAGTTTAA GTATGAGTGT CGTCACCTCA ACGGGACGGA
 GCGGGTGCGG CTCCTGGACA GATACATCTA CAACCAGGAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTGACGGA GCTGGGGCGG
 CGGTACGCAG AGTACTTCAA CAGCCTGAAG GACTACGTGG AGCAGGAGCG
 GGCCGCGGTG GACACCGAGT GCAGACAC*  
>DL;IPD:MHC01020
IPD:MHC01020 Saoe-DRB*W22:01 228 bases
 CGTTTCTTGG AGCTGCTTAA GGGTGAGTGT CATCTCTTCA ACCGGACGGA
 GCGGGTGCGG CTCCTGGCCA GACTCATCTA TAGCCAAGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTGACGGA GCTGGGGCGG
 CCTATCGCGG AGAACCTCAA CAGCCGGAAG GAAGTCCTGG AGTACATGCG
 GGCCGCGGTG GACACCTTCT GCAGGCAT*  
>DL;IPD:MHC01021
IPD:MHC01021 Saoe-DRB*W22:02 228 bases
 CGTTTCTTGG AGCAGCTTAA GGGTGAGTGT CATCACTTCA ACCGGACGGA
 GCGGGTGCGG CTCCTGGCCA GACTCATCTA TAACCAGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTGACGGA GCTGGGGCGG
 CCTATCGCGG AGAACCTCAA CAGCCGGAAG GAAGTCCTGG AGTACATGCG
 GGCCGCGGTG GACACCTTCT GCAGGCAT*  
>DL;IPD:MHC01022
IPD:MHC01022 Saoe-DRB*W22:03 228 bases
 CGTTTCTTGG AGCAGCTTAA GGCTGAGTGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCGG CTCCTGGCCA GAAACATCCA TAACCAGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTGACTGA GCTGGGGCGG
 CCTGACGAGG AGAACTGGAA CAGCCGGAAG GACATCCTGG AGCAGACACG
 GGCCGAGGTG GACACCTTCT GCAGGCAT*  
>DL;IPD:MHC01023
IPD:MHC01023 Saoe-DRB*W22:04 228 bases
 CGTTTCTTGG AGCAGCTTAA GGGTGAGTGT CATCACTTCA ACCGGACGGA
 GCGGGTGCGG CTCCTGGCCA GACTCATCTA TAACCAGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTGACGGA GCTGGGGCGG
 CCTATCGCGG AGAACCTCAA CAGCCGGAAG GACATCCTGG AGCAGACACG
 GGCCGCGGTG GACACCTTCT GCAGGCAT*  
>DL;IPD:MHC01024
IPD:MHC01024 Saoe-DRB*W22:05 228 bases
 CGTTTCTTGG AGCAGCTTAA GGGTGAGTGT CATCACTTCA ACCGGACGGA
 GCGGGTGCGG CTCCTGGCCA GACTCATCTA TAACCAGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTGACGGA GCTGGGGCGG
 CCTATCGCGG AGAACCACAA CAGCCGGAAG GAAGTCCTGG AGTACATGCG
 GGCCGCGGTG GACACCTTCT GCAGGCAT*  
>DL;IPD:MHC01025
IPD:MHC01025 Saoe-DRB*W22:06 228 bases
 CGTTTCTTGG AGCTGCTTAA GGGTGAGTGT CATCACTTCA ACCGGACGGA
 GCGGGTGCGC TTCCTGGCCA GACTCATCTA TAACCAGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTGACGGA GCTGGGGCGG
 CCTATCGCGG AGAACCTCAA CAGCCGGAAG GAAGTCCTGG AGTACATGCG
 GGCCGCGGTG GACACCTTCT GCAGGCAT*  
>DL;IPD:MHC01026
IPD:MHC01026 Saoe-DRB*W22:07 228 bases
 CGTTTCTTGG AGCAGCTTAA GGGTGAGCGT CATCACTTCA ACCGGACGGA
 GCGGGTGCGG CTCCTGGCCA GACTCATCTA TAACCAGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTGACGGA GCTGGGGCGG
 CCTATCGCGG AGAACCTCAA CAGCCGGAAG GAAGTCCTGG AGTACATGCG
 GGCCGCGGTG GACACCTTCT GCAGGCAT*  
>DL;IPD:MHC01027
IPD:MHC01027 Saoe-DRB*W22:08 228 bases
 CGTTTCTTGG AGCAGCTTAA GGCTGAGTGT CATTTCTTCA ACGGGACGGA
 GCGGGTGCGG CTCCTGGCCA GAAACATCCA TAACCAGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTGACTGA GCTGGGGCGG
 CCTGACGAGG AGAACTGGAA CAGCCGGAAG GACATCCTGG AGCAGACACG
 GGCCGCGGTG GACACCTTCT GCAGGCAT*  
>DL;IPD:MHC01028
IPD:MHC01028 Saoe-DRB*W22:09 268 bases
 CGTTTCTTGG AGCAGCTTAA GGGTGAGTGT CATCACTTCA ACCGGACGGA
 GCGGGTGCGG CTCCTGGCCA GACTCATCTA TAACCAGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTTCCGGG CGGTGACGGA GCTGGGGCGG
 CCTATCGCGG AGAACCACAA CAGCCGGAAG GAAGTCCTGG AGTACATCGG
 GGCCGCGGTG GACACCTTCT GCAGACACAA CTACAAGGGT TTTGAGATGT
 TCCTAGTGCC GCGGAGAG*   
>DL;IPD:MHC01029
IPD:MHC01029 Saoe-DRB*W22:10 205 bases
 CACGTTTCTT GGAGCAGCTT AAGGCTGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGCTCCTGGC CAGATTCATC TATAACCAGG AGGAGAACCT
 GCGCTTCGAC AGCGACGTGG GGGAGTTCCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGA GGAGAACTGG AACAGCCGGA AGGACATCCT GGAGCAGACA
 CGGGC*    
>DL;IPD:MHC00994
IPD:MHC00994 Saoe-DRB1*03:01 267 bases
 CACGTTTCTT GGAGTATAGC ACGTCTGAGT GTCATCACTT CAATGGGACT
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC CATAACCAGG AGGAGTTCCT
 GCGCTTCGAC AGCGACGTGT GGGAGTACCG GGCGGTGACG GAGCGGGGGC
 GGCGGAGCGC AGAGCACTTC AACAGCCGGA AGAACTACAT GGAGGATGCG
 CGGGCCGCGG TGGACAGTTG CAGACACAAC TACGAGATTT CAGAGAGGTT
 CCTAGTGCTG CGGAGAG*   
>DL;IPD:MHC00995
IPD:MHC00995 Saoe-DRB1*03:02 268 bases
 CACGTTTCTT GGAGTATAGC ACGTCTGAGT GTCATCACTT CAATGGGACT
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC CATAACCAGG AGGAGTTCCT
 GCGCTTCGAC AGCGACGTGT GGGAGTACCC GGCGGTGACG GAGCGGGGGC
 GGCGGACGGC AGAGCACTTC AACAGCCGGA AGGAACTACA TGGAGGATGC
 GCGGGCCGCG GTGGACAGTT GCAGACACAA CTACGAGATT TCAGAGAGGT
 TCCTAGTGCT GCGGAGAG*   
>DL;IPD:MHC00996
IPD:MHC00996 Saoe-DRB1*03:03N 266 bases
 CACGTTTCTT GGAGTATAGC ACGTCTGAGT GTCATCACTT CAATGGGACT
 GAGCGGGTGC GGTTCCTGGA CAGATACTTA TAACCAGGAG GAGTTCCTGC
 GCTTCGACAG CGACGTGGGG GAGTAACCGG CGGTGACGGA GCGGGGGCGG
 CGGACGGCAG AGCACTTCAA CAGCCGGAAG GAACTACATG GAGGATGCGC
 GGGCCGCGGT GGACAGTTGC AGACACAACT ACGAGATTTC AGAGAGGTTC
 CTAGTGCTGC GGAGAG*   
>DL;IPD:MHC00997
IPD:MHC00997 Saoe-DRB1*03:04N 266 bases
 CACGTTTCTT GGAGTATAGC ACGTCTGAGT GTCATCACTT CAATGGGACT
 GAGCGGGTGC GGTTCCTGGA CAGATATTTA TAACCAGGAG GAGTTCCTGC
 GCTTCGACAG CGACGTGGGG GAGTAACCGG CGGTGACGGA GCGGGGGCGG
 CGGACGGCAG AGCACTTCAA CAGCCGGAAG GAACTACATG GAGGATGCGC
 GGGCCGCGGT GGACAGTTGC AGACACAACT ACGAGATTTC AGAGAGGTTC
 CTAGTGCTGC GGAGAG*   
>DL;IPD:MHC00998
IPD:MHC00998 Saoe-DRB1*03:05 270 bases
 CACGTTTCTT GGAGTATAGA ATGTGTGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA AAGATTCATC TATAACCAGG AGGAGAACCT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGA GGAGAACTGG AACAGCCAGA AGGACATCCT GGAGCAGAAG
 CGGGCCGCGG TGGACACCTT CTGCAGACAC AACTACGAGA TTTCAGAGAG
 GTTCCTAGTG CCGCGGAGAG *  
>DL;IPD:MHC00984
IPD:MHC00984 Saoe-DRB11*01:01 270 bases
 CACGTTTCTT GGAGCAGGCT AAGGCTGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GCCTCCTGGA AAGATACTTC TACAACCAGG AGGAGTTGGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGA GGAGTACTGG AACAGCCGGA AGGACATCCT GGAGCAGACA
 CGGGCCGCGG TGGACACCTT CTGCAGACAC AACTACGAGA TTTTAGAGAG
 GTTCCTAGTG CCGCGGAGAG *  
>DL;IPD:MHC00985
IPD:MHC00985 Saoe-DRB11*01:02 270 bases
 CACGTTTCTT GGAGCAGGCT AAGGCTGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GGCTCCTGGA AAGATACTTC TACAACCAGG AGGAGTTGGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGA GGAGTACTGG AACAGCCGGA AGGACATCCT GGAGCAGACA
 CGGGCCGCGG TGGACACCTT CTGCAGACAC AACTACGAGA TTTTAGAGAG
 GTTCCTAGTG CCGCGGAGAG *  
>DL;IPD:MHC00986
IPD:MHC00986 Saoe-DRB11*01:03 270 bases
 CACGTTTCTT GGAGCAGGCT AAGGCTGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GGCTCCTGGA AAGATACTTC TACAACCAGG AGGAGTTCGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGACGA GGAGTACTGG AACAGCCGGA AGGACATCCT GGAGCAGACA
 CGGGCCGCGG TGGACACCTT CTGCAGACAC AACTACGAGA TTTTAGAGAG
 GTTCCTAGTG CCGCGGAGAG *  
>DL;IPD:MHC00987
IPD:MHC00987 Saoe-DRB11*01:04 270 bases
 CACGTTTCTT GGAGCAGGCT AAGGCTGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC CATAACCAGG AGGAGTTGGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGAAGA GGAGTACTGG AACAGCCAGA AGGACATCCT GGAGGACAGG
 CGGGCCGCGG TGGACACCTT CTGCAGACAC AACTACGAGA TTTTAGAGAG
 GTTCCTAGTG CCGCGGAGAG *  
>DL;IPD:MHC00988
IPD:MHC00988 Saoe-DRB11*01:05 270 bases
 CACGTTTCTT GGAGCAGGCT AAGGCTGAGT GTCATCACTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC CATAACCAGG AGGAGTTGGT
 GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTGAAGA GGAGTACTGG AACAGCCAGA AGGACATCCT GGAGCAGACA
 CGGGCCGCGG TGGACACCTT CTGCAGACAC AACTACGAGA TTTTAGAGAG
 GTTCCTAGTG CCGCGGAGAG *  
>DL;IPD:MHC00989
IPD:MHC00989 Saoe-DRB11*01:06 228 bases
 CGTTTCTTGG AGCAGGCTAA GGCTGAGTGT CATCACTTCA ACGGGACGGA
 GCGGGTGCGG TTCCTGGACA GATACTTCCA TAACCAGGAG GAGTTCCTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGAAGAGG AGTACTGGAA CAGCCAGAAG GACATCCTGG AGGACAGGCG
 GGCCCGGGTG GACACCTTCT GCAGGCAT*  
>DL;IPD:MHC00990
IPD:MHC00990 Saoe-DRB11*01:07N 228 bases
 CGTTTCTTGG AGCAGGCTAA GGCTGAGTGT CATCACTTCA ACGGGACGGA
 GCGGGTGCGG CTCCTGGAAA GATGCTTCTA GAACCAGGAG GAGTTCGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGAGG AGTACTGGAA CAGCCGGAAG GACATCCTGG AGCAGACACG
 GGCCGCGGTG GACACCTTCT GCAGGCAT*  
>DL;IPD:MHC00991
IPD:MHC00991 Saoe-DRB11*01:08 228 bases
 CGTTTCTTGG GGCAGGCTAA GGCTGAGTGT CATCACTTCA ACGGGACGGA
 GCGGGTGCGG CTCCTGGAAA GATACAACTA CAACCAGGAG GAGTATGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGACGAGG AGTACTGGAA CAGCCAGAAG GACTTCCTGG AGCAGAGGCG
 GGCCGCGGTG GACACCTTCT GCAGGCAT*  
>DL;IPD:MHC00992
IPD:MHC00992 Saoe-DRB11*01:09 228 bases
 CGTTTCTTGG AGCAGGCTAA GGCTGAGTGT CATCACTTCA ATGGGACGGA
 GCGGGTGCGG TTCCTGGACA GATACTTCCA TAACCAGGAG GAGTTGGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGAAGAGG AGTACTGGAA CAGCCAGAAG GACATCCTGG AGCAGACACG
 GGCCGCGGTG GACACCTTCT GCAGGCAT*  
>DL;IPD:MHC00993
IPD:MHC00993 Saoe-DRB11*01:10 228 bases
 CGTTTCTTGG AGCAGGCTAA GGCTGAGTGT CATCACTTCA ACGGGACGGA
 GCGGGTGCGG TTCCTGGACA GATACTTCCA TAACCAGGAG GAGTTGGTGC
 GCTTCGACAG CGACGTGGGG GAGTACCGGG CGGTGACGGA GCTGGGGCGG
 CCTGAAGAGG AGTACTGGAA CAGCCAGAAG GACATCCTGG AGGACAGGCG
 GGCCGCGGTG GACACCTTCT GCAGGCAT*  
>DL;IPD:MHC00999
IPD:MHC00999 Saoe-DRB3*05:01N 270 bases
 CACGTTTCTT GGACCTGCTT AAGTCTGAGT GTCGTTCCTT CAACCGGTCG
 GAGCAGGTGC GGTTCCTGGA AAGACACATC TATAACCAGG ACGAGTTCCT
 CCTCTTCCAC AGCGATGTGG GGGAGTATCC GGTGCGTAAT CGCGCTGGGG
 CGGCCTGAAG AAGAGTCCTG GAACCACCGG AAGGAACTCC TGGAGCTGAA
 GCCGGGCCAG GTAGACACCT ACTGCAGACA CAACTACGGG ACTGGGAGAG
 CTTCATAGTG CAGCGGTGAG *  
>DL;IPD:MHC01000
IPD:MHC01000 Saoe-DRB3*05:02N 270 bases
 CACGTTTCTT GGACCTGCTT AAATCTGAGT GTCGTTCCTT CAACCGGTCG
 GAGCAGGTGC GGTTCCTGGA AAGACACATC TATAACCAGG ACGAGTTCCT
 CCTCTTCCAC AGCGATGTGG GGGAGTATCC GGTGCGTAAT CGCGCTGGGG
 CGGCCTGAAG AAGAGTCCTG GAACCACCGG AAGGAACTCC TGGAGCTGAA
 GCCGGGCCAG GTAGACACCT ACTGCAGACA CAACTACGGG ACTGGGAGAG
 CTTCATAGTG CAGCGGTGAG *  
>DL;IPD:MHC01001
IPD:MHC01001 Saoe-DRB3*05:03N 269 bases
 CACGTTTCTT GGACCTGCTT AAATCTGAGT GTCGTTCCTT CAACCGGTCG
 GAGCAGGTGC GGTTCCTGGA AAGACACATC TATAACCAGG ACGAGTTCCT
 CCTCTTCCAC AGCGATGTGG GGGAGTATCG GTGCGTAATC GCGCTGGGGC
 GGCCTGAAGA AGAGTCCTGG AACCACCGGA AGGAACTCCT GGAGCTGAAG
 CCGGGCCAGG TAGACACCTA CTGCAGACAC AACTACGGGA CTGGGAGAGC
 TTCATAGTGC AGCGGTGAG*   
>DL;IPD:MHC01002
IPD:MHC01002 Saoe-DRB3*05:05 228 bases
 CGTTTCTTGG ACCTGCTTAA ATCTGAGTGT CGTTCCTTCA ACCGGTCGGA
 GCAGGTGCGG TTCCTGGAAA GACACATCTA TAACCAGGAC GAGTTCCTCC
 TCTTCCACAG CGATGTGGGG GAGTATCCGG TGGTAATCGC GCTGGGGCGG
 CCTGAAGAAG AGTCCTGGAA CCACCGGAAG GAACTCCTGG AGCTGAAGCC
 GGGCCAGGTA GACACCTACT GCAGGCAT*  
>DL;IPD:MHC01003
IPD:MHC01003 Saoe-DRB3*05:06 228 bases
 CGTTTCTTGG ACCTGCTTAA GTCTGAGTGT CGTTCCTTCA ACCGGTCGGA
 GCAGGTGCGG TTCCTGGAAA GACACATCTA TAACCAGGAC GAGTTCCTCC
 TCTTCCACAG CGATGTGGGG GAGTATCCGG TGGTAATCGC GCTGGGGCGG
 CCTGAAGAAG AGTCCTGGAA CCACCGGAAG GAACTCCTGG AGCTGAAGCC
 GGGCCAGGTA GACACCTGGT GCAGGCAT*  
>DL;IPD:MHC01004
IPD:MHC01004 Saoe-DRB3*05:07 228 bases
 CGTTTCTTGG ACCTGCTTAA GTCTGAGTGT CGTTCCTTCA ACCGGTCGGA
 GCAGGTGCGG TTCCTGGAAA GACACATCTA TAACCAGGAC GAGTTCCTCC
 TCTTCCACAG CGATGTGGGG AGTATCCGGT GCGTAATCGC GCTGGGGCGG
 CCTGAAGAAG AGTCCTGGAA CCACCGGAAG GAACTCCTGG AGCTGAAGCC
 GGGCCCAGTA GACACCTACT GCAGGCAT*  
>DL;IPD:MHC01005
IPD:MHC01005 Saoe-DRB3*05:08 228 bases
 CGTTTCTTGG ACCTGCTTAA GTCTGAGTGT CGTTTCTTCA ACCGGTCGGA
 GCAGGTGCGG TTCCTGGAAA GACACATCTA TAACCAGGAC GAGTTCCTCC
 TCTTCCACAG CGATGTGGGG GAGTATCCGG TGGTAATCGC GCTGGGGCGG
 CCAGATGAAG AGTCCTGGAA CCACCGGAAG GAACTCCTGG AGCTGAAGCC
 GGGCCAGGTG GACACCTGCT GCAGGCAT*  
>DL;IPD:MHC01006
IPD:MHC01006 Saoe-DRB3*05:09 228 bases
 CGTTTCTTGG ACCTGCTTAA ATCTGAGCGT CGTTCCTTCA ACCGGTCGGA
 GCAGGTGCGG TTCCTGGAAA GACACATCTA TAACCAGGAC GAGTTCCTCC
 TCTTCCACAG CGATGTGGGG GAGTATCCGG TGGTAATCGC GCTGGGGCGG
 CCTGAAGAAG AGTCCTGGAA CCACCGGAAG GAACTCCTGG AGCTGAAGCC
 GGGCCAGGTA GACACCTACT GCAGGCAT*  
>DL;IPD:MHC01007
IPD:MHC01007 Saoe-DRB3*05:10 228 bases
 CGTTTCTTGG AGCTGCTGAA GTCTGAGTGT CGTTTCTTCA ACGGGACGGA
 GCAGGTGCGG TTCCTGGAAA GACACATCTA TAACCAGGAC GAGTTCCTCC
 TCTTCCACAG CGATGTGGGG GAGTATCCGG TGGTGACCGC GCTGGGGCGG
 CCTGAAGAAG AGTCCTGGAA CCACCGGAAG GAACTCCTGG AGCTGAAGCC
 GGGCCAGGTA GACACCTGGT GCAGGCAT*  
>DL;IPD:MHC01008
IPD:MHC01008 Saoe-DRB3*05:11 228 bases
 CGTTTCTTGG ACCTGCTTAA ATCTGAGTGT CATTCCTTCA ACCGGTCGGA
 GCAGGTGCGG TTCCTGGAAA GACACATCTA TAACCAGGAC GAGTTCCTCC
 TCTTCCACAG CGATGTGGGG GAGTATCCGG TGGTAATCGC GCTGGGGCGG
 CCTGAAGAAG AGTCCTGGAA CCACCGGAAG GAACTCCTGG AGCTGAAGCC
 GGGCCAGGTA GACACCTACT GCAGGCAT*  
>DL;IPD:MHC01009
IPD:MHC01009 Saoe-DRB3*05:12 228 bases
 CGTTTCTTGG AGCTGCTGAA GTCTGAGTGT CGTTTCTTCA ACGGGACGGA
 GCAGGTGCGG TTCCTGGAAA GACACATCTA TAACCAGGAC GAGTTCCTCC
 TCTTCCACAG CGATGTGGGG GAGTATCCGG TGGTGACCGC GCTAGGGCGG
 CCTGAAGAAG AGTCCTGGAA CCACCGGAAG GAACTCCTGG ACGTGAAGCC
 GGGCCAGGTA GACACCTACT GCAGGCAT*  
>DL;IPD:MHC01010
IPD:MHC01010 Saoe-DRB3*05:13 228 bases
 CGTTTCTTGG AGCTGCTGAA GTCTGAGTGT CGTTTCTTCA ACGGGACGGA
 GCAGGTGCGG TTCCTGGAAA GACACATCTA TAACCAGGAC GAGTTCCTCC
 TCTTCCACAG CGATGTGGGG GAGTATCCGT CGGTAATCGC GCTGGGGCGG
 CCTGAAGAAG AGTCCTGGAA CCACCGGAAG GAACTCCTGG AGCTGAAGCC
 GGGCCAGGTA GACACCTACT GCAGGCAT*  
>DL;IPD:MHC01011
IPD:MHC01011 Saoe-DRB3*05:14 228 bases
 CGTTTCTTGG AGCTGCTGAA GTCTGAGTGT CGTTTCTTCA ACGGGACGGA
 GCAGGTGCGG TTCCTGGAAA GACACATCTA TAACCAGGAC GAGTTCCTCC
 TCTTCCACAG CGATGTGGGG GAGTATCGGT GCGTGACCGC GCTGGGGCGG
 CCTGAAGAAG AGTCCTGGAA CCACCGGAAG GAACTCCTGG AGCTGAAGCC
 GGGCCAGGTA GACACCTACT GCAGGCAT*  
>DL;IPD:MHC01012
IPD:MHC01012 Saoe-DRB3*05:15 228 bases
 CGTTTCTTGG ACCTGCTTAA ATCTGAGTGT CGTTCCTTCA ACCGGTCGGA
 GCAGGTGCGG TTCCTGGAAA GACACATCTA TAACCAGGAC GAGTTCCTCC
 TCTTCCACAG CGATGTGGGG GAGTATCGGT GCGTGACCGC GCTGGGGCGG
 CCTGAAGAAG AGTCCTGGAA CCACCGGAAG AACCTCCTGG AGCTGAAGCC
 GGGCCAGGTA GACACCTACT GCAGGCAT*  
>DL;IPD:MHC01013
IPD:MHC01013 Saoe-DRB3*05:16 228 bases
 CGTTTCTTGG ACCTGCTTAA GTCTGAGTGT CGTTTCTTCA ACCGGTCGGA
 GCAGGTGCGG TTCCTGGAAA GACACATCTA TAACCAGGAC GAGTTCCTCC
 TCTTCCACAG CGATGTGGGG GAGTATCCGG TGGTGACCGC GCTAGGGCGG
 CCAGATGAAG AGTCCTGGAA CCACCGGAAG GAACTCCTGG AGCTGAAGCC
 GGGCCAGGTG GACACCTGCT GCAGGCAT*  
>DL;IPD:MHC01014
IPD:MHC01014 Saoe-DRB3*05:17 228 bases
 CGTTTCTTGG ACCTGCTTAA GTCTGAGTGT CGTTCCTTCA ACCGGTCGGA
 GCAGGTGCGG TTCCTGGAAA GACACATCTA TAACCAGGAC GAGTTCCTCC
 TCTTCCACAG CGATGTGGGG GAGTATCCGG TGGTAATCGC GCTGGGGCGG
 CCTGAAGAAG AGTCCTGGAA CCACCGGAAG GAACTCCTGG ACGTGAAGCC
 GGGCCAGGTA GACACCTACT GCAGGCAT*  
>DL;IPD:MHC01015
IPD:MHC01015 Saoe-DRB5*07:01 268 bases
 CACGTTTCTT GAAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGCA CAGAGGCATC TATAACCAAA AGGAGGACGT
 GCGCTTCGAC AGTGACGTGG GGGAGTACCG GGCGGTGACG GAGCTGGGGC
 GGCCTATCGC CGAGTACTGG AACAGCCAGA AGGACCTCCT GGAGCGGAGG
 CGCCGACGTG GACACCTTCT GCAGACACAA CTACGGGGTT TTAGAGAGCT
 TCACAGTGCA GCGGCGAG*   
