>DL;IPD:MHC00980
IPD:MHC00980 Saoe-DQB1*22:01 174 bases
 GGGACGGAGC GCGTGCGCCT TGTGACCCGA TTCATCTATA ACCGAGAGGA
 GTATCTGCGC TTCGACAGCG ACGTGGGGGA GTACCTGCCG GTGACGCCGC
 TGGGGCCGCC CGACGCCGAG TACTTGAACA GCCAGAAGGA CTTCCTGGAG
 AGGACCCGGG CGGACGTGGA CACG*  
>DL;IPD:MHC00981
IPD:MHC00981 Saoe-DQB1*22:02 171 bases
 ACGGAGCGCG TGCGCCTTGT GACCCGATTC ATCTATAACC GAGAGGAGTA
 TCTGCGCTTC GACAGCGACG TGGGGGAGTA CTGGGCAGTG ACGCCGCTGG
 GGCCGCCCGA CGCCGAGTAC TTGAACAGCC AGACTGAAGT CCTGGAGAGG
 ACCCGGGCGG AGCTGGACAC G*  
>DL;IPD:MHC00982
IPD:MHC00982 Saoe-DQB1*23:01 174 bases
 GGGACAGAGC GCGTGCGTCT TGTGACAGAA TACGTCTATA ACCGAGAGGA
 GTACGTGCGC TTCGACAGCG ACGTGGGGGA GTATCGGGCA GTGACGCCGC
 TGGGGCGGCC TGACGCCAAG TACTGGAACA GCCAGAAGGA CATCCTGGAG
 AGCACCCGGG CGGAGCTGGA CACG*  
>DL;IPD:MHC00983
IPD:MHC00983 Saoe-DQB2*01:01 171 bases
 GGGACGGAGC GCGTGCGGGG TGTGGCCAGA TACATCTATA ACCGCGAGGA
 GTACGCGCGC TTCGACAGCG ACGTGGGGGA GTTCCGGGCG GTGACCGAGC
 TGGGGCGGAG CACCGAGGAC TGGAACAACT ATAAGGACTT CTTGGAGCAG
 GAGCGGGCCG CGGTGTACAC G*  
