>DL;IPD:MHC02071
IPD:MHC02071 Saoe-N1 482 bases
 CACTTCCGTG TCCCGGCCCG GCCGTGGGGA GCCCCGCTTC ATCTCCGTGG
 GCTACGTGGA CGACACGCAG TTCGTGCGGT TCGACAGTGA CGCCGCGAGT
 CCGAGAGAGG AGCCGCGGGC GCCATGGGTT GAGCAGGAGG GGCCGGAGTA
 TTGGGACCTG CAGACACAGA TCTCCAAGGC CATCGCACAG ACTCAGCGAT
 AGAACCTGCG GACCCTGCGC GGCTACTACG ACCAGAGCGA GGCAGGGTCT
 CACACCTACC AGAGGATGTA TGGCTGCGAC CTGGGGCCTG CCGGACGCCT
 CCTCCGCGGG TATAGCCAGT ACGCCTTTGA TGGCAAGGAC TACATCGCCC
 TGAACGAGGA CCTGCGCGGA CGTGGCGGCT CAGATCACCC AGCGCAAGTG
 GAAGGCAGCC AACGAGGCTG AGAGGATGAA AGCCTACGTG GAGGGCAGGT
 GCCTGGAGTC GCTCCTCAGA TACCTGGAGA AC* 
>DL;IPD:MHC02072
IPD:MHC02072 Saoe-N3 493 bases
 CACCGTCGTG TCCCGGCCCG GCTGCGGGGA GCCCCGGTAC ATCGAAGTCG
 GCTACGTGGA CTACACGCAG TTCGTGCGGT TCGACAGCGA CGCAGCGAAT
 ACGAGGATGG AGCCGCGGGC GCCGTGGGTG GAGAAGGAGG GGCGGGAGTA
 TTGGGACCGG AATACACGGA GAGCCAAGGC CAACGCAGAC TCTCCGAGTG
 GGCCTGAGGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCGAGTCTCT
 TACCATCCAG ATAACGTACG GCTGCGACGT GGGGCCGAGG GGCGCTTCCT
 CCGTGGGTAC CGACAGGACG CCTACGATGG CAAGGATTAC ACCGCCCTGA
 ACAAGGACCT GCGCTCCTGG ACCGCCGCGG ACATGGCGGC TCAGATCAGC
 AAACGCAAGC GAGAGGCGGC CAATGAGGCT GAGAGGATGA CAGCCTACTT
 GGAGGGCACC TGCGTGGAGT GGCACCTGAG ACACCTGGAG AAC*
>DL;IPD:MHC02073
IPD:MHC02073 Saoe-N4 434 bases
 GAGACCTGAG CAGGCTCCCA GTCCATGAGG TATTTGAGGA CCCCTGCTTC
 ATCTCCATGG GCTACATGGA AGACACGCAG ATCGCGCGGT TCGACAGAGA
 CGCCTCGAGT CCGAGGATGG AGCCGCGGGC GCCGTGGATG GAGAAGGTGG
 GTCTGGAGTA TTGGAACCTG GGTACACGGA CAGAGTTTCC GAGTGAACCT
 GCAGAACCTG CGCGGCTACT ACAACCAGAG CGTAGCCGGG TCCCACACCC
 TCCGGGAGAT GTATTGCTAG AACCTGGGGC CGGAAGGGCT CCTTCTCCAC
 GGGTATCACC AGTTCGCCTA TGACGGCAAG GATTAAGTCG CCCCGAACGA
 GGACCTGCGC TCCTGGACCA TCGCGGACCT GGCGGCTCAG ATCACCCAGC
 TCAAGTGGGA GGTAGACAAT GTGGCGGAGA AGGT* 
