>DL;IPD:MHC01030
IPD:MHC01030 Saoe-E*03:01 1042 bases
 CTCTTGCTGT TCTCGGGAGC CCTATCCCTG ACCGAGACCT GGGCGAGCTC
 CCACTCCTTG AGGTATTTCC ACACCTCCGT GTCCCGGCCC GGCCGCGGGG
 AGCCTCACTT CATCTCCGTG GGCTACGTGG ACGACACGCA GTTCGTGCGG
 TTCGACAGCG ACGCCGCGAT TCCCAGGATG GAGCCGCGGG CGCCGTGGAT
 AGAGCAGGAG GGGCCGGAGT ATTGGGACCG GGAGACACAG AGCGCCAGGG
 ACACAGCACA GAGTTTCCGA GTGAACCTGC GGACCCTGCT CCGCTACTAC
 AATCAGAGCG AGGCTGGGTC TCACACCCTC CAGTGGCTGC ATGGCTGCGA
 CCTGGGGCCA GACGGGCGCT TCCTCCGTGG GTATGAACAG TTCGCCTACG
 ATGGCAAGGA TTACCTCACC TTGAACGAGG ACCTGCGCTC CTGGACCGCA
 GCGGACACCG CGGCTCAGAT CTCCCAGCGC AAGTCAGAGG AGGCCTGTGA
 GGCGGAGCAC CAAAGGGCCT ACCTGGAGGA CACGTGCGTG GAGTGGCTCC
 GCAGATACCT GGAGAACGGA AAGGAGACGC TGCAGCGTGC GGATCCCCCA
 AAGACACATG TGACCCACCA CCCTGTCTCT GACCATGAGG CCACCCTGAG
 ATGCTGGGCC CTGGGTTTCT ACCCTGCGGA GATCACAATG ACCTGGCAGC
 GGGATGGGGA GGACCAGACC CAGGACATGG AGCTTGTGGA GACCAGGCCA
 GCAGGGGATG GAACCTTCCA GAAGTGGGCG GCTGTGGTGG TGCCTTCTGG
 AGAGGAGCAG AGATACACAT GCCATGTGCA GCATGAGGGG CTGCCAGAGC
 CCCTCACCCT GAGATGGAAA CCATCTTCCC AGCCCACCAT CCCCATCAGG
 GGCATGGCTT GCCTGGTTGT CCTTGGAGCT GTGGTCAGTG CAGCTGTGGT
 TGCTGCTGTG ATGCAGAGGA AGAAGAGCTC AGGTGGAAAA GGAGGGAGTT
 ACTTTCAGGC TGCGTGCAAC GACAGTGCCC AGGGCTCTGA GT*
