>DL;IPD:MHC02071
IPD:MHC02071 Saoe-N1 67 bases
 TSVSRPGRGE PRFISVGYVD DTQFVRFDSD AASPREEPRA PWVEQEGPEY
 WDLQTQISKA IAQTQRX*   
>DL;IPD:MHC02072
IPD:MHC02072 Saoe-N3 164 bases
 TVVSRPGCGE PRYIEVGYVD YTQFVRFDSD AANTRMEPRA PWVEKEGREY
 WDRNTRRAKA NADSPSGPED PARLLQPERG RVSYHPDNVR LRRGAEGRFL
 RGYRQDAYDG KDYTALNKDL RSWTAADMAA QISKRKREAA NEAERMTAYL
 EGTCVEWHLR HLEN*   
>DL;IPD:MHC02073
IPD:MHC02073 Saoe-N4 3 bases
 ETX*    
