>DL;IPD:MHC01032
IPD:MHC01032 Saoe-G*03:01 331 bases
 LLLLLPGALV LTETWAGSHS MRYFSTAVSR PGREEPRFIN VGYVDDTQFV
 RFDSHAARPR MEPRAPWMEQ EGPEYWEEET LKAKDWAQTY RVNLQTLLGY
 YNQSEAGSHT LQWMSGCDLG PDGRLLRGYE QYAYDCKDYI ALNEDLRSWT
 AADVAAQITQ RKWEAANAAE GMRAYLEGTC VEWLHRYLEN GKETLQRAEP
 PKTHVTHHPV SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDMELVETR
 PAGDGTFQKW AAVVVLSGEE HRYTCHVQHE GLPEPLTLRW EPPSQPTIPI
 MGIVAILAIL GAVVTGAVVA AVMWRKKSSD K* 
>DL;IPD:MHC01033
IPD:MHC01033 Saoe-G*03:02 331 bases
 LLLLLSGALV LTETWAGSHS MRYFETSVSR PGRGEPRYIS VGYVDDTQFV
 RFDSDAASPR MEPRAPWMEQ EGPEYWEEET RKGKADAQTF RVGLQTLLGY
 YNQSEAGSHT IQWMYGCDLG PDGRLLRGYH QYAYDCKDYI ALNEDLRSWT
 AADVAAQITQ RKWEAANEAE RTRAYLEGTC VEWLHRYLEN GKETLQRAEP
 PKTHVTHHPV SDHEATLRCW ALGFYPAEIT VTWQRDGEDQ TQDMELVETR
 PAGDGTFQKW AAVVVLSGEE QRYTCHVQHE GLPEPLTLRW EPPSQPTIPI
 MGIVAILAIL GAVVTGAVVA AVMWRKKSSD K* 
>DL;IPD:MHC01034
IPD:MHC01034 Saoe-G*03:03 331 bases
 LLLLLSGALV LTETWAGSHS MRYFKTSVSR PGRGEPRYIS VGYVDDTQFV
 RFDSDAASPR MEPRAPWMEQ EGPEYWEEET RTAKAAAQTF RVDLQTLLGY
 YNQSEAGSHT IQWMSGCDLG PDGRLLRGYH QYAYDCKDYI ALNEDLRSWT
 AADAAAQITQ RKWAEANAAE GMRAYLEGVC VEWLLRYLEN GKETLQRAEP
 PKTHVTHHPV SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDMELVETR
 PAGDGTFQKW AAVVVLSGEE HRYTCHVQHE GLPEPLTLRW EPPSQPTIPI
 MGIVAILAIL GAVVTGAVVT AVMWRKKSSD K* 
>DL;IPD:MHC01035
IPD:MHC01035 Saoe-G*03:04 331 bases
 LLLLLSGALV LTETWAGSHS MRYFETSVSR PGRGEPRYIS VGYVDDTQFV
 RFDSDAASPR MEPRAPWMEQ EGPEYWEEET RKGKADAQTF RVDLQTLLGY
 YNQSEAGSHT IQWMYGCDLG PDGRLLRGYD QHAYDCKDYI ALNEDLRSWT
 ATDVAAQITQ RKWEAANEAE RTRAYLEGTC VEWLHRYLEN GKETLQRAEP
 PKTHVTHHPV SDHEATLRCW ALGFYPAEIT VTWQRDGEDQ TQDMELVETR
 PAGDGTFQKW AAVVVLSGEE QRYTCHVQHE GLPEPLTLRW EPPSQPTIPI
 MGIVAILAIL GAVVTGAVVA AVMWRKKSSD K* 
>DL;IPD:MHC01036
IPD:MHC01036 Saoe-G*03:05 331 bases
 LLLLLSGALA LTETWAGSHS MRYFSTAVSR PGRGEPRFIA VGYVDDTQFV
 RFDSDAARPR MEPRAPWMEQ EGPEYWEEET RKVKAHAQID RMDLQTLLGY
 YNQSQAGSHT IQVMYGCDLG PDGRLLRGYD QHAYDCKDYI ALNEDLRSWT
 AADVAAQITQ RKWEAANAAE RTRAYLEGMC VEWLLRYLEN GKETLQRAEP
 PKTHMTHHPV SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDMELVETR
 PAGDGTFQKW AAVVVLSGEE HRYTCHVQHE GLPEPLTLRW EPPSQPTIPI
 MGIVAILAIL GAVVTGAVVA AVMWRKKSSD K* 
>DL;IPD:MHC01037
IPD:MHC01037 Saoe-G*03:06 338 bases
 MVMAPRTLLL LLSGALALTE TWAGSHSMRY FSTAVSRPGR EEPRYIEVGY
 VDDTQFVRFD SDAASPRMEP RAQWVEKEGR EYWEEETQRA KAFAQTFRVN
 LQTALGYYNQ SEAGSHTIQM MSGCDLGPDG RLLRGYDQHA YDCKDYISLN
 EDLRSWTAAD VAAQITQRKW EAANEAERTR AYLEGTCVEW LHRYLENGKE
 TLQRAEPPKT HVTHHPVSDH EATLRCWALG FYPAEITLTW QRDGEDQTQD
 MELVETRPTG NGTFQKWAAV VVLSGEEHRY TCHVQHEGLP EPLTLRWEPP
 SQPTIPIMGI VAILAILGAV VTGAVVTAVM WRKKSSDK* 
>DL;IPD:MHC01038
IPD:MHC01038 Saoe-G*03:07 331 bases
 LLLLLSGALV LTETWAGSHS MRYFSTTVSR PGRGEPRYIE VGYVDDTQFV
 RFDSNAASPR MEPRAPWVEQ EGPEYWEEET QRAKALAQTF RVNLQTLLRY
 YNQSEAGSHT IQWMYGCYLG PDGRLLRGYY QHAYDCKDYI ALNEDLRSWT
 AADLAAQITQ RKWEAANAAE EWRAYLEGTC VEWLHRYLEN GKETLQRAEP
 PKTHVTHHPV SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDMELVETR
 PTGNGTFQKW AAVVVLSGEE HIYTCHVQHE GLPEPLTLRW EPPSQPTIPI
 MGIVAILAIL GAVVTGAVVA AVMWRKKSSD K* 
>DL;IPD:MHC01039
IPD:MHC01039 Saoe-G*03:08 331 bases
 LLLLLSGALS VTETWAGSHS MRYFSTTVSR PGRGEPRYIE VGYVDDTQFV
 RFDSDAASPR MEPRAPWVEQ EGPEYWVLQT RNSKASAQTF RVNLQTLLGY
 YNQSEAGFHT IQWMYGCDLG PDGRLLRGYH QYAYDCKDYI ALNEDLRSWT
 AADAAAQITQ RKWAEANAAE GMRAYLEGTC VEWLRRHLEN GKEMLQRAEP
 PKTHVTHHPV SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ AQDMELVETR
 PTGNGTFQKW AAVVVLSGEE HKYTCHVQHE GLPEPFTLRW EPPSQPTIPI
 MGIVAILAIL GAVVTGAVVA AVMWRKKSSD K* 
>DL;IPD:MHC01040
IPD:MHC01040 Saoe-G*03:09 331 bases
 LLLLLSGALV LTETWAGSHS MRYFKTSVSR PGRGEPRYIS VGYVDDTQFV
 RFDSDAASPR MEPRAPWMEQ EGPDYWEKET RTAKAAAQTF RVNLQTLLGY
 YNQSEAGSHT IQWMSGCDLG PDGRLLRGYE QHAYDCKDYI ALNEDLRSWT
 AADVAAQITQ RKWEAANVAE RTRAYLEGMC VEWLLRYLEN GKETLQRAEP
 PKTHVTHHPV SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDMELVETR
 PAGDGTFQKW AAVVVLSGEE HRYTCHVQHE GLPEPLTLRW EPPSQPTIPI
 MGIVAILAIL GAVVTGAVVA AVMWRKKSSD K* 
>DL;IPD:MHC01041
IPD:MHC01041 Saoe-G*03:10 331 bases
 LLLLLSGALV LTETWAGSHS MRYFSTAMSR PGRGEPRYIE VGYVDDTQFV
 RFDSDAASPR MEPRAPWVEK EGREYWEEET QRAKAFAQTD RVNLQTALGY
 YNQSEAGSHT IQWMYGCDLG PDGRFLRGYE QLAYDCKDYI ALNEDLRSWT
 AADVAAQITQ RKWEAANAAE EWRAYLEGTC VEWLHRYLEN GKETLQRAEP
 PKTHVTHHPI SDHEATLRCW ALGFYPAEIT LTWQRDGEDQ TQDMELVETR
 PAGDGTFQKW AAVVVLSGEE HRYTCHVQHE GLPEPLTLRW EPPSQPTIPI
 MGIVAMLAIL GAVVTGAVVT AVMWRKKSSD K* 
>DL;IPD:MHC01042
IPD:MHC01042 Saoe-G*03:11 330 bases
 LLLLSGALAL TDTWAGSHSM RYFETSVSRP GRGEPRYIEV GYVDDTQFVR
 FDSDAASPRM EPRAPWMEQE GPDYWEKETR RAKAAAQTFR VNLQTLLGYY
 NQSEAGSHTI QWMYGCDLGP DGRLLRGYEQ HAYDCKDYIA LNEDLRSWTA
 ADVAAQITQR KWEAANAAER TRAYLEGTCV EWLHRYLENG KETLQRAEPP
 KTHVTHHPVS DHEATLRCWA LGFYPAEITL TWQWDGEDQT QDMELVETRP
 AGDGTFQKWA AVVVLSGEEH RYTCHVQHEG LPEPLTLRWE PPSQPTIPIM
 GIVAILAILG AVVTGAVVAA VMWRKKSSDK * 
>DL;IPD:MHC01043
IPD:MHC01043 Saoe-G*03:12Ps 102 bases
 SHSMKYFNTA KSRPGCGKPR YFEVGYVDDT QFVRFDSDAA SPRMEPRAPW
 VEQEGRSTGP KRSRKPRSTH GISEGTGGPC AATTTRAGRF QETYGCSLGF
 DX*    
>DL;IPD:MHC01044
IPD:MHC01044 Saoe-G*03:13Ps 138 bases
 SQTMRYLSTP LHLCGLHGRH ADRAVQQRRL ESEDRARAPW MEKEGPECWD
 LGTRIFKDTA QSFRVNLQTL RCYYNQSEAS PTPSGRCIAR TWGRKGSFST
 DITSSPMTAR IKSPRTRTCA PGPSRTLRLR SPSASGRX* 
>DL;IPD:MHC01045
IPD:MHC01045 Saoe-G*03:14Ps 88 bases
 SHFFRYFYIA ASRAGSGESR FIYVGYVDDT QFVRFDSDDA SPRMETRAPW
 MEQEGPEYWD RETRIAKAYA QNFQVNLWNL RGHYNQSX* 
>DL;IPD:MHC01046
IPD:MHC01046 Saoe-G*03:16Ps 155 bases
 SHSLRYFQTA VSRPGLEEPH FFAVGYVEDM QFERFDSDAA IPRGEPRTPW
 MEQEGPEYWD LQTRTLKARA QREARSHTYQ RMYGCDLGPD GRLFRRYDKR
 AYDFKDYLAL NEVLRSWTAA ETASQVTQRK FEVTHEADKM KAYPEGTCVE
 SLPRX*    
>DL;IPD:MHC01047
IPD:MHC01047 Saoe-G*03:17Ps 96 bases
 SHSMRYFSTT VSRPGHEEPR FILVGYVDDT QFVRFDNDVA IPRMEPLAPW
 VEQEGPEYWD LQTRRVKAAA QNFRVNLRTL RSYYNQSEDG LTLSRX*
>DL;IPD:MHC01048
IPD:MHC01048 Saoe-G*03:18Ps 104 bases
 SHSLKYFNTA KSRPGCGKPR YFEVGYVDDT QFVRFDSDAA SPRMEPRAPW
 VEQEGRSTGT ERSRKPRSTH GISEGTGRPC AATTTRAGPL VGLPSVVWLL
 PGVX*    
>DL;IPD:MHC01049
IPD:MHC01049 Saoe-G*03:19Ps 104 bases
 SHSLKYFNTA KSRPGCGKPR YFEVGYVDDT QFVRFDSDAA SPRMEPRAPW
 VEQEGRSTGT RRSRKPRSTH GISEGTGGPC AATTTRAGRL VGLPGDLWLL
 PGVX*    
>DL;IPD:MHC01050
IPD:MHC01050 Saoe-G*03:20Ps 86 bases
 SHSKRYFNTA KSRPGCGEPR YFEVGYVDDA QFARFDSDAA RPRMEPRAPW
 VEQEGPEYWD REEKKAKVDA RNFRMNRRTL RGKYNX* 
