>DL;IPD:MHC01066
IPD:MHC01066 Sasc-G*04:01 993 bases
 CTCCTCCTGC TGCTCTCGGG GGCCCTGGCC CTGACCCAGA CCCGGGCGGG
 CTCCCACTCC CTGAGGTATT TCAGCACCGC CGTGTCCCGG CCCGGCCGCG
 GGGAGCCCCG CTTCATCTCC GTGGGCTACG TGGACGACAC GCAGTTCGTG
 CGGTTCGACA GCGACGCCGC GATTCCGAGG ATGGAGCCGC TGGCGCCATG
 GATGGAGCAG GAGGGGCCGG AGTATTGGGA GGAGCAGACA CGGATCTCCA
 AGGCCAACAC ACAGATTAGC CGACTGAACC TGCGGATCTT GCTCGGCTAC
 TACAACCAGA GCGAGGCCGG GTCTCACACA GTCCAGAAGA TGTTGGGCTG
 CGACCTGGGG CCGGACGGGC GCCTCCTCCG CGGGTATTAC CAGGACGCCT
 ACGACGGCAA GGACTACATC GCCCTGAACG ACGACCTGCG CTCCTGGACC
 GCCGCGGACA TGGCGGCTCA GATCACCAAG CGCAAGTGGG AGGCGGCCAA
 TGTGGCAGAA CAACAGAGAG CCTACCTAGA GGACGAGTGC CTGGAGTGGC
 TCCGCAGATA CCTGGAGAAC GGGAAGGAGA CGCTGCAGCG CGCGGAGCAC
 CCCAAGACAC ACGTGTCCCA TCATCCCATC TCTGACCATG AGGCCACCCT
 GAGGTGCTGG GCCCTGGGCT TCTACCCTGC GGAGATCACA CTGACCTGGC
 AGCGGGATGG GGAGGACCAG ACCCAGGACA TGGAGCTTGT GGAGACCAGG
 CTAGCAGGGG ATGGAACCTT CCAGAAGTGG GCGGCTGTGG TGGTGCCTTC
 TGGAGAGGAG CAGAGATACA CATGCCATGT GCGGCACGAG GGGCTGCGTA
 AGCCCATCAC CCTGAGATGG GAGCCATCTT CCCAGCCCAC CATCCCCATC
 GTGGGCATCG TTGCTGGCCT GGTTGTCCTT GGAGCTGTAG TCACTGGAGC
 TGTGGTCACT GCTGTGATGT GGAGGAAGAA GAGCTCAGAT AAA*
