>DL;IPD:MHC01052
IPD:MHC01052 Sasc-DPA1*05:01 189 bases
 TTTGTACAGA TGCAGAGACC AACAGGGGAG TTTATGTTTG AGTTTGATGA
 GGATGAGATG TTCTATGTGG ATCTGGACAA GAAGGAGACC ATCTGGCATC
 TGGAGGAGTT TGGCCGAGCC TCTTCCTTTG AGTTTCAGAA TGGGCTGTCT
 AACATTGCTG CATTGAACAA CCACTTGAAT ATCATGATC* 
>DL;IPD:MHC01053
IPD:MHC01053 Sasc-DPA1*05:02 189 bases
 TTTGTACAGA TGCAGAGACC AACAGGGGAG TTTATGTTTG AGTTTGATGA
 GGATGAGATG TTCTATGTGG ATCTGGACAA GAAGGAGACC GTCTGGCATC
 TGGAGGAGTT TGGCCGAGCC TTTTCCTTTG AGTTTCAGAA TGGGCTGTCT
 AACATTGCTG CATTGAACAA CCACTTGAAT ATCATGATC* 
>DL;IPD:MHC01054
IPD:MHC01054 Sasc-DPA1*06:01 189 bases
 TTTGTACAGA CACATAGACC AACAGGGGAG TTTATGTTTG AGTTTGATGA
 GGATGAGATG TTCTATGTGG ATCTGGACAA GAAGGAGACC GTCTGGCATC
 TGGAGGAGTT TGGCCGAGCC TTTTCCTTTG AGGCTCAGAG CATCCAGGCT
 CACATTACTA TATTGAAGGA CGACTTGAAT ATCACGATC* 
