>DL;IPD:MHC02068
IPD:MHC02068 Seen-DPB1*01 249 bases
 CTGTTCCAGG CACGGCAGGA ATGCTACGCG TTTAACGGGA CACAGCGCTA
 CCTGGAGAGA TACATCTACA ACCGGGAGGA GTTCGTGCGC TTCGACAGCG
 ACGCCGGGGA GTTCCGGGCG GTGACGGAGC TGGGACGGCG TGCTGCGGAG
 AACTGGAACA GCCAGAAGGA CAAAATGGAG GAGATGCGGG CAGTGGTGGA
 CACGATGTGC AGACACAACT ACGAGGGGAA CGAGGCGGTG ACCCTGCAG*
