>DL;IPD:MHC02069
IPD:MHC02069 Thge-DQA1*01:01 188 bases
 ACTTACGGTC TCTCTGGCCA GTTCACCCAT GAATTTGATG GAGATGAGCA
 GTTCTACGTG GACCTGGAGA GGAAGGAGAC GGCCTGGCGA TGGCCTGAGT
 TAAGCAAATT TGGAGGTTTT GACCCGCAGT GCACACTGAG AAACTTGGCT
 GTGTTAAAAC ACAACTTGAA CATCGTGACT AAACGCTA* 
>DL;IPD:MHC02070
IPD:MHC02070 Thge-DQA1*25:01 188 bases
 TTTTATGGTT CCTCTGGCCA GTACACCCAT GAATTTGATG GAGACGAGCA
 GTTCTATGTT GACCTGGAGA GGAAGGAGAC TGTCTGGCGG TTGCCTCTGT
 TCAGCAAATT TGCAGGTTTT GACCCTCAGG GTGCACTGAG AAACATCGCT
 GTGGGAAAAC ACACCTTGAA CATGATGATT AAACGCTC* 
