>DL;FLA-DRB_0102
FLA-DRB_0102  237 bases  
 AATATGTTGA AGGCCGAGTG CCATTTCACC AACGGGACGG AGCAGGTGCG
 ATTCCTGGTC AGATGTTTCT ATAACGGGGA GGAGTATGTG CGCTTCGACA
 GCGAAGTGGG GGAGTTCCGG GCGGTGACGG AGCTGGGGCG GCCTGATGCC
 AAGTACTGGA ACGAGCAGAA GGACCACCTG GAGCAGGCGC GGACAGCGGT
 GGACCGGATC TGCAGACACA ACTACGGTGT TGGTGAG*

>DL;FLA-DRB_0103
FLA-DRB_0103  237 bases  
 AATATGTTGA AGGCCGAGTG CCATTTCACC AACGGGACGG AGCAGGTGCG
 ATTCCTGGTC AGATGTTTCT ATAACGGGGA GGAGTATGTG CGCTTCGACA
 GCGAAGTGGG GGAGTTCCGG GCGGTGACGG AGCTGGGGCG GCCTGATGCC
 AAGTACTGGA ACGAGCAGAA GGACCACCTG GAGCAGGAGC GGACAGCGGT
 GGACCGGATC TGCAGACACA ACTACGGTGT TGGTGAG*

>DL;FLA-DRB_0104
FLA-DRB_0104  237 bases  
 AATATGTTGA AGGCCGAGTG CCATTTCACC AACGGGACGG AGCAGGTGCG
 ATTCCTGGTC AGATGTTTCT ATAACGGGGA GGAGTATGTG CGCTTCGACA
 GCGAAGTGGG GGAGTTCCGG GCGGTGACGG AGCTGGGGCG GCCAGACGCC
 AAGTACTGGA ACGGGCAGAA GGACCACCTG GAGCAGGAGC GGACAGCGGT
 GGACCGGATC TGCAGACACA ACTACGGTGT TGGTGAG*

>DL;FLA-DRB_0107
FLA-DRB_0107  237 bases  
 AATATGTTGA AGGCCGAGTG CCATTTCACC AACGGGACGG AGCAGGTGCG
 ATTCCTGGTC AGATGTTTCT ATAACGGGGA GGAGTATGTG CGCTTCGACA
 GCGAAGTGGG GGAGTTCCGG GCGGTGACGG AGCTGGGGCG GCCCACTGCC
 AAGTACTGGA ACGAGCAGAA GGACCACCTG GAGCAGGAGC GGACAGCGGT
 GGACCGGATC TGCAGACACA ACTACGGTGT TGGTGAG*

>DL;FLA-DRB_0201
FLA-DRB_0201  237 bases  
 ACCATGTGGA AGTTCGAGTG TCATTTCACC AACGGGACGG AGCGGGTGCG
 GTACCTGGTC AGATTTTTCT ATAACCGGGA GGAGTTAGCT CGCTTCGACA
 GCGAAGTGGG GGAGTTCCGA GCGGTATCAG AGCTGGGGCG GCCAGACGCC
 AAGTACCTGA ACGAGCAGAA GGACTTCATG GAGGGGAAGC GCGCCGAGGT
 GGACACGGTC TGCAGACACA ACTACGGTGT TGGTGAG*

>DL;FLA-DRB_0203
FLA-DRB_0203  237 bases  
 ACCATGTGGA AGTTCGAGTG TCATTATCCC AACGGGACGG AGCGGGTGCG
 ATACCTGGTC AGATTTTTCT ATAACCGGGA GGAGTTAGCT CGCTTCGACA
 ACGAAGTGGG GGAGTTCCGA GCGGTATCAG AGCTGGGGCG GCCAGACGCC
 AAGTACTGGA ATGGGCAGAA GGACTTCATG GAGCGGAAGC ACGCCGAGGT
 GGACACGGTC TGCAGACACA ACTACGGTGT TTTTGAC*

>DL;FLA-DRB_0207
FLA-DRB_0207  237 bases  
 ATCATGGGGA AGGCCGAGTG CCATTTCACC AACGGGACGG AGCGGGTGCA
 ATTCCTGGCC AGATATTTCT ATAACCGGGA GGAGTTAGCT CGCTTCGACA
 GCGAAGTGGG GGAGTTCCGG GCGGTGACGG AGCTGGGGCG GCCTGACGCC
 AAGCACTGGA ATGGGCAGAA GGACTTCATG GAGCAGACGC GGACAGCGGT
 GGACTGGTTC TGCAGACACA ACTACGGTGT TGGTGAG*

>DL;FLA-DRB_0209
FLA-DRB_0209  237 bases  
 ATCATGGGGA AGGCCGAGTG CCATTTCACC AACGGGACGG AGCGGGTGCG
 ATTCCTGGCC AGATATTTCT ATAACCGGGA GGAGTTAGCT CGCTTCGACA
 GCGAAGTGGG GGAGTTCCGG GCGGTGACGG AGCTGGGGCG GCCTGACGCC
 AAGCACTGGA ATGGGCAGAA GGACTTCATG GAGCAGACGC GGACAGCGGT
 GGACTGGTTC TGCAGACACA ACTACGGTGT TGGTGAG*

>DL;FLA-DRB_0303
FLA-DRB_0303  237 bases  
 AATATGTGGA AGGCGGAGTG CCATTTCACC AACGGGACAG AGCGGGTGCG
 GTACCTGGAG AGACACTATC ATAACGGGGA GGAGAACTTG CGCTTCGACA
 GCGAAGTGGG GGAGTACCGG GCGGTGACGG AGCTGGGGCG GCCAGACGCC
 AAGTACTGGA ACGGGCTGAA GGACTACATG GAGGAGACGC GGACAGCGGT
 GGACTGGTTC TGCAGACACA ACCACGGTGT TGGTGAG*

>DL;FLA-DRB_0304
FLA-DRB_0304  237 bases  
 AATATGTGGA AGGCGGAGTG CCATTTCACC AACGGGACAG AGCGGGTGCG
 GTACCTGGAG AGACACTATC ATAACGGGGA GGAGAACTTG CGCTTCGACA
 GCGAAGTGGG GGAGTACCGG GCGGTGACGG AGCTGGGGCG GCCAGACGCC
 AAGTACTGGA ACGGGCTGAA GGACTACATG GAGGAGACGC GGACAGCGGT
 GGACTGGTTC TGCAGACACA ACTACGGTGT TGGTGAG*

>DL;FLA-DRB_0310
FLA-DRB_0310  237 bases  
 AATATGTGGA AGGCGGAGTG CCATTTCACC AACGGGACGG AGCGGGTGCG
 GTACCTGCGG AGACACGTCT ATAACGGTGA GGAGTATGTG CGCTTTGACA
 GCGAAGTGGG GGAGTTCCGG GCGGTGACAG AGCTGGGGCG GCCCACTGCC
 AAGTACTGGA ATGGGCTGAA GGACGTCATG GAGAGGAGGC GGACAGCGGT
 GGACTGGCTC TGCAGACACA ACTACGGTGT TTTTGAC*

>DL;FLA-DRB_0311
FLA-DRB_0311  237 bases  
 AATATGTGGA AGGCGGAGTG CCATTTCACC AACGGGACGG AGCGGGTTTG
 GCTCCTGGAG AGACACTTCT ATAACGGGGA GGAGTGTGTG CGCTTTGACA
 GCGAAGTGGG GGAGTTCCGG GCGGTGACGG AGCTGGGGCG GCCTGACGCC
 AAGTACTGGA ACGGGCTGAA GGACTTCATG GAGCAGAAGC GCGCCGAGGT
 GGACACGGTC TGCAGACACA ACTACGGTGT TTTTGAC*

>DL;FLA-DRB_040101
FLA-DRB_040101  237 bases  
 TTCCTGGGGA AGACCGAGTG CCATTTCACC AACGGGACGG AGCGGGTTCG
 GCTCCTGGAC AGATACTTCT ATAACGGGGA GGAGTATGTG CGCTTCGACA
 GCGAAGTGGG GGAGTTCCGG GCGGTGACTG AGCTGGGGCG GCCCATTGCC
 AAGTACCTGA ACGGGCTGAA GGACTACATG GAGGAGTCGC GGACAGCGGT
 GGACACCTAC TGCAGACACA ACTACGGTGT TGGTGAG*

>DL;FLA-DRB_040103
FLA-DRB_040103  237 bases  
 CTCCTGTGGA AGAGCGAGTG CCATTTCACC AACGGGACGG AGCGGGTTCG
 GCTCCTGGAC AGATACTTCT ATAACGGGGA GGAGTATGTG CGCTTCGACA
 GCGAAGTGGG GGAGTTCCGG GCGGTGACTG AGCTGGGGCG GCCCATTGCC
 AAGTACCTGA ACGGGCTGAA GGACTACATG GAGGAGTCGC GGACAGCGGT
 GGACACCTAC TGCAGACACA ACTACGGTGT TGTTGAC*

>DL;FLA-DRB_0403
FLA-DRB_0403  237 bases  
 CTCCTGTGGA AGAGCGAGTG CCATTTCACC AACGGGACGG AGCGGGTTCG
 GCTTCTGGAC AGATACTTCT ATAACGGGGA GGAGTATGTG CGCTTCGACA
 GCGAAGTGGG GGAGTTCCGG GCGGTGACTG AGCTGGGGCG GCCAGACGCC
 AAGTACTGGA ACGGGCTGAA GGACTACATG GAGGAGTCGC GGACAGCGGT
 GGACACCTAC TGCAGACACA ACTACGGTGT TGTTGAC*

>DL;FLA-DRB_0501
FLA-DRB_0501  237 bases  
 CTCCTGTGGA AGAGCGAGTG CCATTTCACC AACGGGACGG AGCGGGTGCG
 ATTCCTGGAC AGATGTTTCT ATAACGGGGA GGAGTTTGTG CGCTTCGACA
 ACGAAGTGGG GGAGTACCGG GCGGTGACGG AGCTGGGGCG GCCAGACGCC
 AAGTACTGGA ACGGGCAGAA GGACTTCATG GAGCAGAAGC GCGCCGAGGT
 GGACACGGTC TGCAGACACA ACTACGGTGT TGGTGAG*

>DL;FLA-DRB_0504
FLA-DRB_0504  237 bases  
 TTCCTGGGGA AGGCCGAGTG TCATTATCCC AACGGGACGG AGCGGGTTCG
 GCTTCTGGAC AGGTACTTCT ATAACGGGGA GGAGTATGTG CGCTTCGACA
 GCGAAGTGGG GGAGTTCCGG GCAGTGACTG AGCTGGGGCG GCCCACTGCC
 AAGTACTGGA ACGGGCAGAA GGACTTCATG GATCAGAAAC GCGCCGAGGT
 GGACACGGTC TGCAGACACA ACTACGGTGT TGATGAG*

>DL;FLA-DRB_050702
FLA-DRB_050702  237 bases  
 TTCCTGGGGA AGGGCGAGTG CCATTTCACC AACGGGACGG AGCAGGTGCG
 ATTGCTGATC AGATGTTTCT ATAACGGGGA GGAGTTTGTG CGCTTCGACA
 GCGAAGTGGG GGAGTACCGG GCGGTGACGG AGCTGGGGCG GCCCATTGCC
 AAGTACATGA ACGAGCAGAA GGACTTCATG GAGCAAAGGC GCGCCGAGGT
 GGACACGGTG TGCAGACACA ACTACGGTGT TGGTGAG*

>DL;FLA-DRB_0511
FLA-DRB_0511  237 bases  
 TTCCTGGGGA AGGGCGAGTG CCATTTCACC AACGGGACGG AGCAGGTGCG
 ATTGCTGATC AGATGTTTCT ATAACGGGGA GGAGTTTGTG CGCTTCGACA
 GCGAAGTGGG GGAGTACCGG GCGGTGACGG AGCTGGGGCG GCCAGACGCC
 AAGTACATGA ACGAGCAGAA GGACTTCATG GAGCAAAGGC GCGCCGAGGT
 GGACACGGTG TGCAGACACA ACTACGGTGT TGTTGAC*

>DL;FLA-DRB_051201
FLA-DRB_051201  237 bases  
 CTCCTGTGGA AGAGCGAGTG CCATTTCACC AACGGGACGG AGCAGGTGCG
 ACTCCTGGAG AGACACTTCT ATAACGGGGA GGAGTTTGTG CGCTTCGACA
 ACGAAGTGGG GGAGTTCCGG GCGGTGACGG AGCTGGGGCG GCCCATTGCC
 AAGTACCTGA ACGAGCAGAA GGACTTCATG GAGCAGAAGC GCGCCGAGGT
 GGACACGGTC TGCAGACACA ACTACGGTGT TGGTGAG*

