>P1;FLA-DRB_0102
FLA-DRB_0102  79 bases  
 NMLKAECHFT NGTEQVRFLV RCFYNGEEYV RFDSEVGEFR AVTELGRPDA
 KYWNEQKDHL EQARTAVDRI CRHNYGVGE*

>P1;FLA-DRB_0103
FLA-DRB_0103  79 bases  
 NMLKAECHFT NGTEQVRFLV RCFYNGEEYV RFDSEVGEFR AVTELGRPDA
 KYWNEQKDHL EQERTAVDRI CRHNYGVGE*

>P1;FLA-DRB_0104
FLA-DRB_0104  79 bases  
 NMLKAECHFT NGTEQVRFLV RCFYNGEEYV RFDSEVGEFR AVTELGRPDA
 KYWNGQKDHL EQERTAVDRI CRHNYGVGE*

>P1;FLA-DRB_0107
FLA-DRB_0107  79 bases  
 NMLKAECHFT NGTEQVRFLV RCFYNGEEYV RFDSEVGEFR AVTELGRPTA
 KYWNEQKDHL EQERTAVDRI CRHNYGVGE*

>P1;FLA-DRB_0201
FLA-DRB_0201  79 bases  
 TMWKFECHFT NGTERVRYLV RFFYNREELA RFDSEVGEFR AVSELGRPDA
 KYLNEQKDFM EGKRAEVDTV CRHNYGVGE*

>P1;FLA-DRB_0203
FLA-DRB_0203  79 bases  
 TMWKFECHYP NGTERVRYLV RFFYNREELA RFDNEVGEFR AVSELGRPDA
 KYWNGQKDFM ERKHAEVDTV CRHNYGVFD*

>P1;FLA-DRB_0207
FLA-DRB_0207  79 bases  
 IMGKAECHFT NGTERVQFLA RYFYNREELA RFDSEVGEFR AVTELGRPDA
 KHWNGQKDFM EQTRTAVDWF CRHNYGVGE*

>P1;FLA-DRB_0209
FLA-DRB_0209  79 bases  
 IMGKAECHFT NGTERVRFLA RYFYNREELA RFDSEVGEFR AVTELGRPDA
 KHWNGQKDFM EQTRTAVDWF CRHNYGVGE*

>P1;FLA-DRB_0303
FLA-DRB_0303  79 bases  
 NMWKAECHFT NGTERVRYLE RHYHNGEENL RFDSEVGEYR AVTELGRPDA
 KYWNGLKDYM EETRTAVDWF CRHNHGVGE*

>P1;FLA-DRB_0304
FLA-DRB_0304  79 bases  
 NMWKAECHFT NGTERVRYLE RHYHNGEENL RFDSEVGEYR AVTELGRPDA
 KYWNGLKDYM EETRTAVDWF CRHNYGVGE*

>P1;FLA-DRB_0310
FLA-DRB_0310  79 bases  
 NMWKAECHFT NGTERVRYLR RHVYNGEEYV RFDSEVGEFR AVTELGRPTA
 KYWNGLKDVM ERRRTAVDWL CRHNYGVFD*

>P1;FLA-DRB_0311
FLA-DRB_0311  79 bases  
 NMWKAECHFT NGTERVWLLE RHFYNGEECV RFDSEVGEFR AVTELGRPDA
 KYWNGLKDFM EQKRAEVDTV CRHNYGVFD*

>P1;FLA-DRB_040101
FLA-DRB_040101  79 bases  
 FLGKTECHFT NGTERVRLLD RYFYNGEEYV RFDSEVGEFR AVTELGRPIA
 KYLNGLKDYM EESRTAVDTY CRHNYGVGE*

>P1;FLA-DRB_040103
FLA-DRB_040103  79 bases  
 LLWKSECHFT NGTERVRLLD RYFYNGEEYV RFDSEVGEFR AVTELGRPIA
 KYLNGLKDYM EESRTAVDTY CRHNYGVVD*

>P1;FLA-DRB_0403
FLA-DRB_0403  79 bases  
 LLWKSECHFT NGTERVRLLD RYFYNGEEYV RFDSEVGEFR AVTELGRPDA
 KYWNGLKDYM EESRTAVDTY CRHNYGVVD*

>P1;FLA-DRB_0501
FLA-DRB_0501  79 bases  
 LLWKSECHFT NGTERVRFLD RCFYNGEEFV RFDNEVGEYR AVTELGRPDA
 KYWNGQKDFM EQKRAEVDTV CRHNYGVGE*

>P1;FLA-DRB_0504
FLA-DRB_0504  79 bases  
 FLGKAECHYP NGTERVRLLD RYFYNGEEYV RFDSEVGEFR AVTELGRPTA
 KYWNGQKDFM DQKRAEVDTV CRHNYGVDE*

>P1;FLA-DRB_050702
FLA-DRB_050702  79 bases  
 FLGKGECHFT NGTEQVRLLI RCFYNGEEFV RFDSEVGEYR AVTELGRPIA
 KYMNEQKDFM EQRRAEVDTV CRHNYGVGE*

>P1;FLA-DRB_0511
FLA-DRB_0511  79 bases  
 FLGKGECHFT NGTEQVRLLI RCFYNGEEFV RFDSEVGEYR AVTELGRPDA
 KYMNEQKDFM EQRRAEVDTV CRHNYGVVD*

>P1;FLA-DRB_051201
FLA-DRB_051201  79 bases  
 LLWKSECHFT NGTEQVRLLE RHFYNGEEFV RFDNEVGEFR AVTELGRPIA
 KYLNEQKDFM EQKRAEVDTV CRHNYGVGE*

