>P1;Onmy-UBA*0101
Onmy-UBA*0101  704 bases  
 MKGIILLVLG IGLLHTASAA THSLKYFYTA SSEVPNFPEF VVVAMVDGAQ
 MVHYDSNSQR AVPKQDWMNR AAETLPQYWE SQTGIFKGAQ QTFKANIDIV
 KQRFNQSGGV HIVQKMYGCE WDDEAGVTEG FYQYGYDGED FIALDLKTTK
 WIAPTPQAVI TKLKWDSNTA NTEYWNNYLT QTCIEWLKKY VDYGKSTLMR
 TVPPSVSLLQ KAPSSPVTCH ATGFYPRDVM VSWQKDGQDH HEDVEYGETL
 PNDDGTFQKS SHLTVTPEDR KNSKYQCVVQ VKGIKKDFIE VLTDPDAANV
 VPIIGGVVAL LLVIVAVVVG VVIWKKRSKK GFVPASTSDT DSENSGKAAP
 QIMKGIILLV LGIGLLHTAS AATHSLKYFY TASSEVPNFP EFVVVAMVDG
 AQMVHYDSNS QRAVPKQDWM NRAAETLPQY WESQTGIFKG AQQTFKANID
 IVKQRFNQSG GVHIVQKMYG CEWDDEAGVT EGFYQYGYDG EDFIALDLKT
 TKWIAPTPQA VITKLKWDSN TANTEYWNNY LTQTCIEWLK KYVDYGKSTL
 MRTVPPSVSL LQKAPSSPVT CHATGFYPRD VMVSWQKDGQ DHHEDVEYGE
 TLPNDDGTFQ KSSHLTVTPE DRKNSKYQCV VQVKGIKKDF IEVLTDPDAA
 NVVPIIGGVV ALLLVIVAVV VGVVIWKKRS KKGFVPASTS DTDSENSGKA
 APQI*

>P1;Onmy-UBA*0102
Onmy-UBA*0102  349 bases  
 IILLVLGIGL LHTASAATHS LKYFYTASSE VPNFPEFVVV AMVDGAQMVH
 YDSNSQRAVP KQDWMNRAAE TLPQYWESQT GIFKGAQQTF KANIDIVKQR
 FNQSGGVHIV QKMYGCEWDD EAGVTEGFYQ YGYDGEDFIA LDLKTTKWIA
 PTPQAVITKL KWDSNTANTE YWNNYLTQTC IEWLKKYVDY GKSTLMRTVP
 PSVSLLQKAP SSPVTCHATG FYPRDVMVSW QKDGQDHHED VEHGEILFND
 DGTFQKSSHL TVTPEDRKNS KYQCVVQVKG IKKDFIEVLT DPDAANVVPI
 IGGVVALLLV IVAVVVGVVI WKKRSKKGFV SASTSDTDSE NSGKAAPQI*

>P1;Onmy-UBA*0103
Onmy-UBA*0103  236 bases  
 MKGIILLVLG IGLLHTASAA THSLKYFYTA SSEVPNFPEF VVVAMVDGAQ
 MVHYDSNSQR AVPKQDWMNR AAETLPQYWE SQTGIFKGAQ QTFKANIDIV
 KQRFNQSGGV HIVQKMYGCE WDDEAGVTEG FYQYGYDGED FIALDLKTTK
 WIAPTPQAVI TKLKWDSNTA NTEYWNNYLT RTCIEWLKKY VDYGKSTLMR
 TVPPSVSLLQ KAPSSPVTCH ATGFYPRDVM VFWQKE*

>P1;Onmy-UBA*0104
Onmy-UBA*0104  236 bases  
 MKGIILLVLG IGLLHTASAA THSLKYFYTA SSEVPNFPEF VVVAMVDGAK
 MVHYDSNSQR AVPKQDWMNR AAETLPQYWE SQTGIFKGAQ QTFKANIDIV
 KQRFNQSGGV HIVQKMYGCE WDDEAGVTEG FYQYGYDGED FIALDLKTTK
 WIAPTPQAVI TKLKWDSNTA NTEYWNNYLT QTCIEWLKKY VDYGKSTLMR
 TVPPSVSLLQ KAPSSPVTCH ATGFYPRDVM VFWQKE*

>P1;Onmy-UBA*0201
Onmy-UBA*0201  354 bases  
 MKSFIILLLG INAASAVTHS LKYFYTGSTG IEGFPQFVAV GIVNGMQIDY
 FDGVSEKNVL KQSWMEGVRD EKMITNTRKG HQQTFKASVE IVMQRFNQTT
 GVHTFQLMYG CELGDDGIPR GDFQLGYDGA DFLSLDKSTL TWTAANQKAV
 ITKLKWDATG AEANFQKNYL ENTCIEWLKK YVNYGKDTLE RKVRPSVSLL
 QKTPSSPVTC HATGFYPSGV MVFWQKDGQE QHGDVEHGEI LQNDDGTFQK
 STHLTVTPEE WKNNKYQCVV QLAGIEDDIT KVLIESEIQT NFGKTNRGSN
 DPITIGLIIG GVIALLVIIV VGVVIWKKKN KKGFVPASTS DTDSENSGKG
 IQKI*

>P1;Onmy-UBA*0202
Onmy-UBA*0202  343 bases  
 NAASAVTHSL KYFYTGSTGI EGFPQFVAVG IVDGMQIDYF DSVSEKNVLK
 QSWMEGVRDE KMITNTRKGH QQTFKASVEI VMQRFNQTTG VHTFQLMYGC
 ELGDDGITRG DFQLGYDGAD FLSLDKSTLT WTAANQKAVI TKLKWDATGA
 EANFQKNYLE NTCIEWLKKY VNYGKDTLER KVRPSVSLLQ KTPSSPVTCH
 ATGFYPSGVM VFWQKDGQEQ HGDVEHGEIL QNDDGTFQKS THLTVTPEEW
 KNNKYQCVVQ LAGIEDDITK VLIESEIQTN FGKTNRGSND PITIGLIIGG
 VIALLVIIVV GVVIWKKKNK KGFVPASTSD TDSENSGKGI QKI*

>P1;Onmy-UBA*0301
Onmy-UBA*0301  363 bases  
 MKGIILLVLG IGLLHTASAV THSLKYFYTA SSEVPNFPEF VVVGMVDGVQ
 MVHYDSNSQR MVPRQDWMNK AAETLPQYWE SQTGILKGTQ QTYKASIDIV
 KQRFNQSGGV HTVQLMYGCE LGDDGITRGD FQYGYDGADF LSLDKSTLTW
 TAANQKAVIT KLKLDATGAE ANFQKNYLEN TCIEWLKKYV NYGKDTLERK
 VRPSVSLLQK TPSSPVTCHA TGFYPSGVMV FWQKDGQEQH GDVEHGEILQ
 NDDGTFQKST HLTVTPEEWK NNKYQCVVQL AGIEDDITKV LIESEIQTNF
 GKTNRGSNDP NTIGLIIGGV IALLVIIAVV GVVIWKKKNK KGFVPASTSD
 TDSENSGKGI QKI*

>P1;Onmy-UBA*0401
Onmy-UBA*0401  362 bases  
 MKGIILLVLG IGLLHTASAV THSLKYFYTA SSEVPNFPEF VVVGMVDGAQ
 MVHYDSNSQR MVPKQDWMNK AAETLPQYWE SQTGNCKGQQ QTFKANIDIV
 NQRFNQSGGV HTFQLMYGCE LGDDGITRGD FQLGYDGADF LSLDKSTLTW
 TAANQKAVIT KLKWDATGAE ANFQKNYLEN TCIEWLKKYV NYGKDTLERK
 VRPSVSLLQK TPSSPVTCHA TGFYPSGVMV FWQKDGQEQH GDVEHGEILQ
 NDDGTFQKST HLTVTPEEWK NNKYQCVVQL AGIEDDITKV LIESEIQTNF
 GKTNRGSNDP ITIGLIIGGV IALLVIIVVG VVIWKKKNKK GFVPASTSDT
 DSENSGKGIQ KI*

>P1;Onmy-UBA*0402
Onmy-UBA*0402  235 bases  
 MKGIILLVLG IGLLHTASAV THSLKYFYTA SSEVPNFPEF VVVGMVDGAQ
 MVHYDSNSQR MVPKQDWMNK AAETLPQYWE SQTGNCKGQQ QTFKADIDIV
 NQRFNQSGGV HTFQLMYGCE LGDDGITRGD FQLGYDGADF LSLDKSTLTW
 TAANQKAVIT KLKWDATGAE ANFQKNYLEN TCIEWLKKYV NYGKDTLERK
 VRPSVSLLQK TPSSPVTCHA TGFYPSGVMV FWQKE*

>P1;Onmy-UBA*0501
Onmy-UBA*0501  349 bases  
 GLLHTASAAT HSLRYVYTAT SGVPDFPEFV SLGIVDGMQI DYYDSNTKRV
 VPKQDWMAKT EGSDYWERQT QNSIGDEQTF KANIDVAKQR FNQTGGVHTF
 QLMYGCELGD DGITRGDFQL GYDGADFLSL DKSTLTWTAA NQKAVITKLK
 WDATGAEANF QKNYLENTCI EWLKKYVNYG KDTLERKVRP SVSLLQKTPS
 SPVTCHATGF YPSGVMVFWQ KDGQEQHGDV EHGEILQNDD GTFQKSTHLT
 VTPEEWKNNK YQCVVQLAGI EDDITKVLIE SEIQTNFGKT NRGSNDPITI
 GLIIGGVIAL LVIIVVGVVI WKKKNKKGFV PASTSDTDSE NSGKGIQKI*

>P1;Onmy-UBA*0502
Onmy-UBA*0502  233 bases  
 MKGIILLLLG IGLLHTASAA THSLRYVYTA TSGVPDFPEF VSLGIVDGMQ
 IDYYDSNTKR VVPKQDWMAK TEGSDYWERQ TQNSIGDEQT FKANIDVAKQ
 RFNQTGGVHT FQLMYGCELG DDSITRGDFQ LGYDGADFLS LDKSTLTWTA
 ANQKAVITKL KWDATGAEAN FQKNYLENTC IEWLKKYVNY GKDTLERKVR
 PSVSLLQKTP SSPVTCHATG FYPSGVMVFW QKE*

>P1;Onmy-UBA*0601
Onmy-UBA*0601  360 bases  
 KGIILLVLGI GLLHTASAVT HSLKYFYTAS SEVPNFPEFV VVAMVDGVQM
 VHYDSNSQRA VPKQDWVNKA ADPQYWERNT GIFKGSQQTF KANIDIAKQR
 FNQSGGVHTV QLMYGCELGD DGITRGDFQY GYDGADFLSL DKSTLTWTAA
 NQKAVITKLK WDATGADANF QKNYLENTCI EWLKKYVNYG KDTLERKVRP
 SVSLLQKTPS SPVTCHATGF YPSGVMVFWQ KDGQEQHGDV EHGEILQNDD
 GTFQKSTHLT VTPEEWKNNK YQCVVQLAGI EDDITKVLIE SEIQTNFGKT
 NRGSNDPNTI GLIIGGVIAL LVIIAVVGVV IWKKKNKKGF VPASTSDTDS
 ENSGKGIQKI*

>P1;Onmy-UBA*0701
Onmy-UBA*0701  339 bases  
 VLLNTVSAAT NTLQYFYTAT SGIDNFPEFV TVGIVNGHQI DHYDSITKRA
 IQKAEWISGA VDPDYWKSNT QIYAAAETVF LNNIKIVKSR FNQTGGVHVF
 QKMYGCEWDD EAGVTEGFNQ YGYDGEDFIA FDLKTTKWIA PTPQAVITKL
 KWDSNTANTE NWNNYLTQTC IEWLKKYVDY GKSTLMRTVP PSVSLLQKAP
 SSPVTCHATG FYPRDVMVSW QKDGQDHHED VEYGETLPND DGTFQKSSHL
 TVTPEDRKNS KYQCVVQVKG IKKDFIEVLT DPDAANVVPI IGGVVALLLV
 VVAVVVGVVI WRKRSKKGFV PASTSDTDSE NSGKAAPQI*

>P1;Onmy-UBA*0801
Onmy-UBA*0801  341 bases  
 GLLHTTSAAI HTLKNFYTAA SGDIDFPEFI IVGLVDNTPY LYFDSNTKTA
 VPKTEWMKKN VGADYWDSMT QIGIGSHQTF KNNIQVAKDR FNQSKSTGVH
 VFQKMYGCEW DDEAGVTEGF NQYGYDGEDF IAFDLKTTKW IAPTPQAVIT
 KLKWDSNTAN TENWNNYLTQ TCIEWLKKYV DYGKSTLMRT VPPSVSLLQK
 APSSPVTCHA TGFYPRDVMV SWQKDGQDHH EDVEYGETLP NDDGTFQKSS
 HLTVTPEDRK NSKYQCVVQV KGIKKDFIEV LTDPDAANVV PIIGGVVALL
 LVVVAVVVGV VIWRKRSKKG FVPASTSDTD SENSGKAAPQ I*

>P1;Onmy-UBA*0901
Onmy-UBA*0901  338 bases  
 GLLHIASAVT HSLRYFYTAT TGIPDFPEFV DVGVVNGKVI SYYDSITKRK
 VPKQSWMEEN LNQQYWNQGT DQLKGAEQTF KANIQIVQTR FNQTGGVHTF
 QNMYGCEWDD DTGATEGFFQ YGYDGEDFLA LDLKTKKWIA PTPQAVITKH
 KWDSNTANEE RRKHYLTQEC IEWLKKYLDY GKSTLMRTVP PSVFLLQKTP
 SSPVTCHATG FYPSDVMVSW QKDGQDHHED VEYGETLPND DGTFQKSIHL
 TMTPEDRKNN KYQCVVQVKG IKEDFIGVPP DQDAANVVPI IGGVVALLLV
 VVVVVVGVVI WKKRSKKGFV PASTSDTDSD NSGGVKKI*

>P1;Onmy-UBA*0902
Onmy-UBA*0902  234 bases  
 MKGIILLVLG IGLLHIASAV THSLRYSYTA TTGIPDFPEF VDVGVANGKV
 ISYYDSITKR KVPKQSWMEE NLNQQYWNQG TDQLKGAEQT FKANIQIVQT
 RFNQTGGVHT FQNMYGCEWD DDTGATEGFF QYGYDGEDFL ALDLKTKKWI
 APTPQAVITK HKWDSNTANE ERRKHYLTQE CIEWLKKYLD YGKSTLMRTV
 PPSVFLLQKT PSSPVTCHAT GFYPSDVMVF WQKE*

>P1;Onmy-UBA*1001
Onmy-UBA*1001  350 bases  
 MKGIILLVLG IGLLHTASAA THSLKYFYTG SSEVPNFPEF VAVGMVDGVQ
 MFHYDSNSQR AVPKQDWVNK AADPQYWERN TGNCKGSQQT FKASIDIVKQ
 RFNQSGGVHV FQNMYGCEWD DEAGATEGFY QFGYDGEDFI AFDLKTTKWI
 APTPQAVITK QKWDSDTADN KYRKNYCTQE CIDWLKKYVD YGKSTLMRTV
 RPSVSLLQKA PSSPVTCHAT GFYPSDVMVS WQKDGQDHHE DVEYGETLPN
 DDGTFQKSSH LTVTPEDRKK NKYQCVVQVK GIKEDFIKVL PDPDAANVVP
 IIVGVVALLL VIVAVVVGVV IWRKRSKKGF VPASTSDTDS DNSGRAVPQI*

>P1;Onmy-UBA*1101
Onmy-UBA*1101  351 bases  
 KGIILLVLGI GLLHTASAAT HSLKYFYTAS SEVPNFPEFV VVAMVDGAQM
 VHYDSNSQRA VPKQDWMNRA AETLPQYWES QTGIFKGAQQ TFKANIDIVK
 QRFNQSGGVH VFQNMYGCEW DDEAGATEGF YQFGYDGEDF IAFDLKTTKW
 IAPTPQAVIT KQKWDSDTAN NEYRKNYFTQ ECIDWLKKYV DYGKSTLMRT
 VRPSVSLLQK APSSPVTCHA TGFYPSDVMV SWQKDGQDHH EDVEYGETLP
 NDDGTFQKSS HLTVTPEDRK NNKYQCVVQV KGIKEDFIEV LPDPDAANVV
 PIIVGVVALL LVVVAVVVGV VIWRKRSKKG FVPASTSDTD SDNSGRAVPQ
 I*

>P1;Onmy-UBA*1201
Onmy-UBA*1201  351 bases  
 KGIILLVLGI GLLHTASAVT HSLKYFYTAS SEVPNFPEFV VVGMVDGVQM
 VHYDSNSQRA VPKQDWMNRA AETLPQYWES QTGNFKGTQQ TYKANIDIVK
 QRFNQSGGVH IFQRMCGCEW DDEAGVTEGF NQYGYDGEDF IALDLKTTKW
 IAPTPQAVIT KLKWDSNTAN TEYWKNYLTQ TCIEWLKKYV DYGKSTLMRT
 VPPSVSLLQK APSSPVTCHA TGFYPRDVMV SWQKDGQDHH EDVEYGETLP
 NDDGTFQKSS HLTVTPEDRK NSKYQCVVQV KGIKKDFIEV LTDPDAANVV
 PIIGGVVALL LVVVAVVVGV VIWRKRSKKG FVPASTSDTD SENSGKAAPQ
 I*

>P1;Onmy-UBA*1301
Onmy-UBA*1301  352 bases  
 MKGIILLVLG IGLLHTASAV THSLKYFYTG SSEVPNFPEF VVVAMVDGAQ
 MVHYDSNSQR AVPKQDWMNR AAETLPQYWE SQTGIFKGDQ QTFKANIDTA
 KQRFNQSGGV HIVQMMCGCE WDDETGVTEG FNQHGYDGED FIAFDLKTTK
 WIAPTPQAVI TKHKWDSNTA NNEYWKNYIT QECIDWLKKY VDYGKNTLMR
 TVPPSVSLFQ KTPSSPVTCH ATGFYPSDVM VSWQKDGQDH HEDVEYGETL
 PNDDGTFQKS SHLTVTPEDR KNSKYQCVVQ VKGIKEDFIE VLPVPDAANV
 VPIIGGVVAL LLVVVAVVVG VVIWKKRSKK GFVPASTSDT DSENSGKAAP
 QI*

>P1;Onmy-UBA*1401
Onmy-UBA*1401  349 bases  
 KGIILLVLGI GLLHTASAVT HSLKYFYTAS SEVPNFPEFV AVGMVDGVQM
 VHYDSNSQRA VPKQDWVNKA ADPQYWERNT GNFKGSQQTF KANIDIVKQR
 FNQSGGVHIF QMMCGCEWDD EAGVTEGFDQ FGYDGEDFIA FDLKTTKWIA
 PTPQAVITKL KWDSNTAYTE NWNNYLTQTC IEWLKKYVDY GKSTLMRTVP
 PSVSLLQKAP SSPVTCHATG FYPRDVMVSW QKDGQDHHED VEYGETLPND
 DGTFQKSSHL TVTPEDRKNS KYQCVVQVKG IKKDFIEVLT DPDAANVVPI
 IGGVVALLLV VVAVVVGVVI WRKRSKKGFV PASTSDTDSE NSGKAAPQI*

>P1;Onmy-UBA*1501
Onmy-UBA*1501  357 bases  
 MKGIILLVLG IGLLHTASAV THSLKYFYTA SSEVPNFPEF VVVAMVDGVQ
 MVHYDSNSQR AVPKQDWVNK AADPQYWERN TGIFKGSQQT FKANIDIAKQ
 RFNQSGGVHI NQRMYGCEWN DETGATGGYS QDGYDGEDFI AFDLKTKTWI
 APKPQAVITK LKWDSDIAMT ERDKHYLTQT CIEWLKKYLD YGKSTLMTTV
 PPSVSLLQKT PSSPVTCHAT GFYPSGVMVF WQKDGQDQHG DVEHGETLPN
 DDGTFQKSTH LTVTPEEWKK KQYQCVVQVT GIKEDFIKVL TESEIKTNWN
 DPAPNIVLII GVVVALLLVI VAVVGVVIWK KKSKKGFIQA QSSDTDSDNS
 GRAAQQI*

>P1;Onmy-UBA*1502
Onmy-UBA*1502  357 bases  
 MKGIILLVLG IGLLHTASAV THSLKYFYTA SSEVPNFPEF VVVAMVDGVQ
 MVHYDSNSQR AVPKQDWVNK AADPQYWERN TGIFKGSQQT FKANIDIAKQ
 RFNQSGGVHI NQRMYGCEWN DETGATGGYS QDGYDGEDFI AFDLKTKTWI
 APKPQAVITK FKWDSDIAMT ERDKHYLTQT CIEWLKKYLD YGKSTLMTTV
 PPSVSLLQKT PSSPVTCHAT GFYPSGVMVF WQKDGQDQHG DVEHGETLPN
 DDGTFQKSTH LTVTPEEWKK KQYQCVVQVT GIKEDFIKVL TESEIKTNWN
 DPAPNIVLII GVVVALLLVI VAVVGVVIWK KKSKKGFIQA QSSDTDSDNS
 GRAAQQI*

>P1;Onmy-UBA*1601
Onmy-UBA*1601  348 bases  
 GLLHTASAAT HSLKYFYTAS SEVPNFPEFV AVGMVDGVQM VHYDSNSQRA
 VPKQDWMNKA AETLPQYWER ETGNLKGTQQ TYKANIDIVK QRFNQSGGVH
 INQRMYGCEW NDETGATGGY SQDGYDGEDF IAFDLKTKTW IAPKPQAVIT
 KLKWDSDIAM TERDKHYLTQ TCIEWLKKYL DYGKSTLMTT VPPSVSLLQK
 TPSSPVTCHA TGFYPSGVMV FWQKDGQDQH GDVEHGETLP NDDGTFQKST
 HLTVTPEEWK KKQYQCVVQV TGIKEDFIKV LTESEIKTNW NDPAPNIVLI
 IGVVVALLLV IVAVVGVVIW KKKSKKGFIQ AQSSDTDSDN SGRAAQQI*

>P1;Onmy-UBA*1701
Onmy-UBA*1701  344 bases  
 MKSFIILLLG INAASAVTHS LKYFYTGSTG IEGFPQFVAV GIVDGMQIDY
 FDSVSEKNVL KQSWMEGVRD EKMITNTRKG NQQTFKANVE IGMQRFNQTT
 GVHIVQRMYG CEWDDEAGVT EGFNQYGYDG EDFIAFDLKT TKWIAPTPQA
 VITKLKWDSN TAYTENWNNY LTQTCIEWLK KYVDYGKSTL MRTVPPSVSL
 LQKAPSSPVT CHATGFYPRD VMVSWQKDGQ DHHEDVEYGE TLPNDDGTFQ
 KSSHLTVTPE DRKNSKYQCV VQVKGIKKDF IEVLTDPDAA NVVPIIGGVV
 ALLLVVVAVV VGVVIWRKRS KKGFVPASTS DTDSENSGKA APQI*

>P1;Onmy-UBA*1702
Onmy-UBA*1702  228 bases  
 MKSFIIVLLG INAASAVTHS LKYFYTGSTG IERFPQFVAV GIVDGMQIDY
 FDSVSEKNVL KQSWMEGVRD EKMITNTRKG NQQTFKANVE IGMQRFNQTT
 GVHIVQGMYG CEWDDEAGVT EGFNQYGYDG EDFIAFDLKT TKWIAPTPQA
 VITKLKWDSN TAYTENWNNY LTQTCIEWLK KYVDYGKSTL MRTVPPSVSL
 LQKAPSSPVT CHATGFYPRD VMVFWQKE*

>P1;Onmy-UBA*1801
Onmy-UBA*1801  351 bases  
 GLLHTASAAT HSLKYFYTAV SGDIDFPEFT AVGLVDKGQF MYFDSSTKTA
 VPKTEWMKRE GADYWDRQTQ GLIGAHQTFK VNIQTLKDRF NQSKSTGVHT
 FQLMYGCELG DDGITRGDFQ YGYDGADFLS LDKSTLTWTA ANQKAVITKL
 KWDATGADAN FQKNYLENTC IEWLKKYVNY GKDTLERKVR PSVSLLQKTP
 SSPVTCHATG FYPSGVMVFW QKDGQEQHGD VEHGEILQND DGTFQKSTHL
 TVTPEEWKNN KYQCVVQLAG IEDDITKVLI ESEIQTNFGK TNRGSNDPNT
 IGLIIGGVIA LLVIIAVVGV VIWKKKNKKG FVPASTSDTD SENSGKGIQK
 I*

>P1;Onmy-UBA*1802
Onmy-UBA*1802  351 bases  
 GLLHTASAAT HSLKYFYTAV SGDIDFPEFT AVGLVDKGQF MYFDSSTKTA
 VPKTEWMKRE GADYWDRQTQ GLIGAHQTFK VNIQTLKDRF NQSKSTGVHT
 VQLMYGCELG DDGITRGDFQ YGYDGADFLS LDKSTLTWTA ANQKAVITKL
 KWDATGADAN FQKNYLENTC IEWLKKYVNY GKDTLERKVR PSVSLLQKTP
 SSPVTCHATG FYPSGVMVFW QKDGQEQHGD VEHGEILQND DGTFQKSTHL
 TVTPEEWKNN KYQCVVQLAG IEDDITKVLI ESEIQTNFGK TNRGSNDPNT
 IGLIIGGVIA LLVIIAVVGV VIWKKKNKKG FVPASTSDTD SENSGKGIQK
 I*

>P1;Onmy-UBA*1901
Onmy-UBA*1901  346 bases  
 VLLNTVSAAT NTLQYFYTAT SGIDNFPEFV TMGIVNGHQI DHYDSITKRA
 IQKAEWISGA VDPDYWKRNT QTYAAEEPVF LNNIKIAKSR FNQTGGVHTN
 QRMYGCEWND ETGATGGYFQ DGYDGEDFIA FDLKTKTWIA PKPQAVITKL
 KWDSDIAMTE QKKHYLTQEC IEWLKKYLDY GKSTLMTTVP PSVTLLQKTP
 SSPVTCHATG FYPSGVMVFW QKDGQDQHGD VEHGETLPND DGTFQKSTHL
 TLTPEEWKKK QYQCVVQVTG IKEDFIKVLT ESEIKTNWNN PAPNIVLIIG
 VVVALLLVIV AVVGVVIWKK KSKKGFIQAQ SSDTDSDNSG RAAQQI*

>P1;Onmy-UBA*2001
Onmy-UBA*2001  357 bases  
 MKGIILLVLG IGLLHTASAA THSLKYFYTG SSEVPNFPEF VAVGMVDGVQ
 MFHYDSNSQR AVPKQDWVNK AADPQYWERN TGNCKGSQQT FKASIDIVKQ
 RFNQSGGVHI FQYMYGCTWD DSGVIDGFRQ IGYDGEDFLV YDMKTFKWIA
 PKQQAEITQH RWNNNPAEIA QRKSYITQEC VEWLKKYLDY GKDSLMRTVP
 PSVSLLQKTP SSPVTCHATG FYPSGVMVSW HKDGQDHHED VEHGEILQND
 DGTFQKSSHL TVTPEEWKNN KYQCVVQVTG IQKDFIKVLT ESEIQTNWDD
 PAPNIVLIIG VVVALLLVVV AVVVGVVIWK KKSKKGFVPA STSDTESDNS
 GRAAQMT*

>P1;Onmy-UBA*2101
Onmy-UBA*2101  359 bases  
 MKSFILLLGI ALHSSSAVIH SWKAFLTAST GLSDFPEFVA LNLVDDELMG
 YFDTKTNRFE GKQSWVEEKL GQQYMERQEN ILRGTSQSFK VNVGIAMERF
 NQTKGVHTVQ LMYGCELGDD GITRGDFQYG YDGADFLSLD KSTLTWTAAN
 QKAVITKLKW DATGADANFQ KNYLENTCIE WLKKYVNYGK DTLERKVRPS
 VSLLQKTPSS PVTCHATGFY PSGVMVFWQK DGQEQHGDVE HGEILQNDDG
 TFQKSTHLTV TPEEWKNNKY QCVVQLAGIE DDITKVLIES EIQTNFGKTN
 RGSNDPNTIG LIIGGVIALL VIIAVVGVVI WKKKNKKGFV PASTSDTDSE
 NSGKGIQKI*

>P1;Onmy-UBA*2201
Onmy-UBA*2201  337 bases  
 LHTASAATHS LRYVYTATSG VPDFPEFVSL GIVDGMQIDY YDSNTKRVVP
 KQDWMAKTEG SDYWERQTQN SIGDEQTFKA NIDVAKQRFN QTGGVHIVQN
 MYGCEWDDES GVTEGFDQYG YDGEDFIAFD LKTKTWIAPK PQAVITKQKW
 DSNTAQNEQY NNYYTQECIE WLKKYMDYGK STLMRTVPPS VSLFQKTSSS
 PVTCHATGFY PSDVMVSWQK DGQDHHEDVE YGETLPNDDG TFQKSSHLTV
 TPEDRKNSKY QCVVQVKGIK EDFIEVLPDP DAANIVPIIV GVVALLLVIV
 AVVVGVVIWK KRSKKGFVPA STSDTDSENS GKAAPQI*

>P1;Onmy-UBA*2301
Onmy-UBA*2301  357 bases  
 MNGLILLVQG ICLLHTVSAV THSMQYIVTA VSGLDEIPEH TEVGMVDGQQ
 FVYYDSVLKK IIPKTDWIEK NVDASYWKRE TDRNIATEQT FKSNVAIAMT
 RFNQTRGVHT NQRMYGCEWN DETGATGGYF QDGYDGEDFI AFDLKTKTWI
 APKPQAVITK LKWDSDIAMT EQKKHYLTQE CIEWLKKYLD YGKSTLMTTV
 PPSVTLLQKT PSSPVTCHAT GFYPSGVMVF WQKDGQDQHG DVEHGETLPN
 DDGTFQKSTH LTLTPEEWKK KQYQCVVQVT GIKEDFIKVL TESEIKTNWN
 NPAPNIVLII GVVVALLLVI VAVVGVVIWK KKSKKGFIQA QSSDTDSDNS
 GRAAQQI*

>P1;Onmy-UBA*2401
Onmy-UBA*2401  348 bases  
 MKSFILLLGI ALHSSSAVIH SWKAFLTAST GLSDFPEFVA LNLVDDELMG
 YFDTKTNRFE GKQSWVEEKL GQQYMERQEN ILRGTSQSFK VNVGIVMERF
 NQTKGVHIVQ RMYGCEWDDE TGVTEGFNQH GYDGEDFIAF DLKTTKWIAP
 TPQAVITKHK WDSNTVRNEQ KKNYLTQTCI EWLKKYVDYG KSTLMRTVPP
 LVSLFQKTSS SLVTCHATGF YPSDVMLSWQ KDGQDHHEDV EYGETLPNDD
 GTFQKSIHLT VTPEDRKNSK YQCVVQVKGI KEDFIKVLPD PDAANVVPII
 VGVVALLLVI VAVVVGVVIW KKRSKKGFVP ASTSDTDSDN SGRAVPQI*

>P1;Onmy-UBA*2501
Onmy-UBA*2501  350 bases  
 CLLHTVSAVT HSMQYIVTAV SGLDEIPEHT EVGMVDGQQF VYYDSVLKKI
 IPKTDWIEKN VDASYWKRET DRNIATEQTF KSNVAIAMTR FNQTRGVHTV
 QLMYGCELGD DGITRGDFQY GYDGADFLSL DKSTLTWTAA NQKAVITKLK
 LDATGAEANF QKNYLENTCI EWLKKYVNYG KDTLERKVRP SVSLLQKTPS
 SPVTCHATGF YPSGVMVFWQ KDGQEQHGDV EHGEILQNDD GTFQKSTHLT
 VTPEEWKNNK YQCVVQLAGI EDDITKVLIE SEIQTNFGKT NRGSNDPNTI
 GLIIGGVIAL LVIIAVVGVV IWKKKNKKGF VPASTSDTDS ENSGKGIQKI*

>P1;Onmy-UBA*2601
Onmy-UBA*2601  350 bases  
 MNGLILLVQG ICLLHTVSAV THSMQYIVTA VSGLDEIPEH TEVGMVDGQQ
 FVYYDSVLKK IIPKTDWIEK NVDASYWKRE TDRNIATEQT FKSNVAIAMT
 RFNQTRGVHI YQYMYGCMWD DDSGVTEGHR QYGYDGEDFL VYNMKTFTWI
 APKQQSEITQ RKWNNEPAQM EYLKSYITQE CIEWLKKYVD YGKSTLMRTV
 PPSVSLFQKT PSSPVTCHAT GFYPSDVMVS WQKDGQDHHE DVEYGETLPN
 NDGTFQKSIH LTVTPDDRKN NKYQCVVQVK GIMEDFIKVL TDPDAANIVP
 IIGGVVALLL VVVAVVVGVV IWRKRSKKGF VPTSTSDTDS ENSGKAAPQI*

>P1;Onmy-UBA*2602
Onmy-UBA*2602  347 bases  
 IILLVLGICL LHTVSAVTHS MQYIVTAVSG LDEIPEHTEV GMGDGQQFVY
 YDSVLKKIIP KTDWIEKNVD ASYWKRETDR NIATEQTFKS NVAIAMTRFN
 QTRGVHIYQY MYGCMWDDDS GVTEGHRQYG YDGEDFLVYN MKTFTWIAPK
 QQSEITQRKW NNEPAQMEYL KSYITQECIE WLKKYVDYGK STLMRTVPPS
 VSLFQKTPSS PVTCHATGFY PSDVMVSWQK DGQDHHEDVE YGETLPNNDG
 TFQKSIHLTV TPDDRKNNKY QCVVQVKGIM EDFIKVLTDP DAANIVPIIG
 GVVALLLVVV AVVVGVVIWR KRSKKGFVPT STSDTDSENS GKAAPQI*

>P1;Onmy-UBA*2701
Onmy-UBA*2701  351 bases  
 MKGIILLVLG IGLLHTASAV THSLKYFYTA SSEVPNFPEF VVVGMVDGVQ
 MVHYDSNSQR MVPRQDWMNK AAETLPQYWE SQTGILKGTQ QTYKASIDIV
 KQRFNQSGGV HTFQNMYGCE WDDDTGATEG FFQYGYDGED FLALDLKTKK
 WIAPTPQAVI TKHKWDSNTA NEERRKHYLT QECIEWLKKY LDYGKSTLMR
 TVPPSVFLLQ KTPTSPVTCH ATGFYPSDVM VSWQKDGQDH HEDVEYGETL
 PNDDGTFQKS IHLTMTPEDR KNNKYQCVVQ VKGIKEDFIG VPPDQDAANV
 VPIIGGVVAL LLVVVVVVVG VVIWKKRSKK GFVPASTSDT DSDNSGGVKK
 I*

>P1;Onmy-UBA*2801
Onmy-UBA*2801  355 bases  
 MKSFIILLLG INAASAVTHS LKYFYTGSTG IEGFPQFVAV GIVDGMQIDY
 FDSVSEKNVL KQSWMEGVRD EKMITNTRKG NQQTFKANVE IGMQRFNQTT
 GVHTFQLMYG CELGDDGITR GDFQYGYDGA DFLSLDKSTL TWTAANQKAV
 ITKLKWDATG ADANFQKNYL ENTCIEWLKK YVNYGKDTLE RKVRPSVSLL
 QKTPSSPVTC HATGFYPSGV MVFWQKDGQE QHGDVEHGEI LQNDDGTFQK
 STHLTVTPEE WKNNKYQCVV QLAGIEDDIT KVLIESEIQT NFGKTNRGSN
 DPNTIGLIIG GVIALLVIIA VVGVVIWKKK NKKGFVPAST SDTDSENSGK
 GIQKI*

>P1;Onmy-UBA*2901
Onmy-UBA*2901  234 bases  
 MKGYYLLVLG IGLLHIASAV THSLRYFYTA TTGIPDFPEF VDVGVVNGKV
 ISYYDSITKR KVPKQSWMEE NLNQQYWNQG TDQLKGAEQT FKANIQIVQT
 RFNQTGGVHT FQNMYGCEWD DDTGATEGFF QYGYDGEDFL ALDLKTKKWI
 APTPQAVITK HKWDSDTADN KYRKNYLTQE CIDWLKKYVD YGKSTLMRTV
 RPSVPLLQKA PSSPVTCHAT GFYPSDVMVF WQKE*

>P1;Onmy-UBA*3001
Onmy-UBA*3001  228 bases  
 MKSFIILLLG INAASAVTHS LKYFYTGSTG IEGFPQFVAV GIVDGMQIDY
 FDSVSEKNVL KQSWMEGVRD EKMTTNTRKG HQQTFKANVE IGMQRFNQTT
 GVHIVQWMYG CEWDDEAGVT EGFDQHGYDG EDFIAFDLKT TKWIAPTPQA
 VITKNKWDSN TVRNEQNKNY YTQTCIEWLK KYVDYGKSTL MRTVPPSVSL
 FQKTSSSLVT CHATGFYPSD VMVFWQKE*

>P1;Onmy-UBA*3101
Onmy-UBA*3101  235 bases  
 MKGIILLVLG IGLLHTASAA THSLKYFYTA VSGDIDFPEF TAVGLVDKGQ
 FMYFDSNTKT AVPKTEWMKR EGADYWDRET QIAIGVHQTF KVDIQTLKDR
 FNQSKSTGVH VFQNMYGCEW DDEAGATEGF YQFGYDGEDF IAFDLKTTKW
 IAPTPQAVIT KQKWDSDTAD NKYRKNYCTQ ECIDWLKKYV DYGKSTLMRT
 VRPSVSLLQK APSSPVTCHA TGFYPSDVMV FWQKE*

>P1;Onmy-UBA*3201
Onmy-UBA*3201  235 bases  
 MKGIILLVLG IGLLHTASAA THSLKYFYTA VSGDIDFPEF TAVGLVDKGQ
 FMYFDSNTKT AVPKTEWMKR EGADYWDRET QIAIGVHQTF KVDIQTLKDR
 FNQSKSTGVH VFQNMYGCEW DDEAGATEGF YQFGYDGEDF IAFDLKTTKW
 IAPTPQAVIT KQKWDSNTAN EERRKHYLTQ ECIEWLKKYL DYGKSTLMRT
 VPPSVFLLQK TPSSPVTCHA TGFYPSDVMV FWQKE*

