>P1;Onmy-DAB*0101
Onmy-DAB*0101  247 bases  
 MSMPIAFYIC LTLLWSIFSG TDGYFEQVVR QCRYSSKDLH GIEFIDSYVF
 NKAEHVRFNS TVGRYVGYTE HGLKNAEAWN SDAGILGQEQ AELERYCKPS
 AAIDYSAILD KTVEPHVRLS SVTPPSGRHP AMLMCSAYDF YPKQIRVTWL
 RDGREVKSDV TSTEELANGD WYYQIHSHLE YTPKSGEKIS CMVEHISLTE
 PMMYHWDPSL PEAERNKIAI GASGLVLGTI LALAGLIYYK KKSSGVL*

>P1;Onmy-DAB*0201
Onmy-DAB*0201  247 bases  
 MSMPIAFYIC LTLLWSIFSG TDGYFHQRVT QCRFSSEDLH GMEYIDSYVF
 NQAEYIRFNS TVGRFVGYTE HGLKNAEAWN SDAGILGQEQ VQLESYCKHN
 AAIDYSAILD KTVEPHVRLS SVTPPSGRHP AMLMCSAYDF YPKQIRVTWL
 RDGREVKSDV TSTEELANGD WYYQIHSHLE YTPKSGEKIS CMVEHISLTE
 PMMYHWDPSL PEAERNKIAI GASGLVLGTI LALAGLIYYK KKSSGVL*

>P1;Onmy-DAB*0301
Onmy-DAB*0301  223 bases  
 EHRLAQCRYS SKDLHGIEFI DSFFFNKVED IRFNSTVGRY VGYTEHGVKN
 AEAWNSDAGI LGQEQAELER VCKHNADLHY SAILDKTVEP HVRLSSVTPP
 SGRHPAMLMC SAYDFYPKQI RVTWLRDGRE VKSDVTSTEE LANGDWYYQI
 HSHLEYTPKS GEKISCMVEH ISLTEPMMYH WDPSLPEAER NKIAIGASGL
 VLGTILALAG LIYYKKKSSG VLX*

>P1;Onmy-DAB*0401
Onmy-DAB*0401  217 bases  
 HHRLAQCRYS SKDLHGIEFI DSYVFNKVEH IRFNSTVGRY VGYTEHGLKN
 AEAWNSDAGI LGQEQAELER FCKHNAANHY SAILDKTVEP HVRLSSVTPP
 SGRHPAMLMC SAYDFYPKQI RVTWLRDGRE VKSDVTSTEE LANGDWYYQI
 HSHLEYTPKS GEKISCMVEH ISLTEPMMYH WDPSLPEAER NKIAIGASGL
 VLGTILALAG LIYYKKK*

>P1;Onmy-DAB*0501
Onmy-DAB*0501  219 bases  
 YFYHRLAQCR YSSKDLHGIE YIDSYFFNKA EYVRFNSTVG RYVGYTEYGV
 KNAEAWNSDA GILGQEQAGL ESYCKHNADI SYSAILDKTV EPHVRLSSVT
 PPSGRHPAML MCSAYDFYPK QIRVTWLRDG REVKSDVTST EELANGDWYY
 QIHSHLEYTP KSGEKISCMV EHISLTEPMM YHWDPSLPEA ERNKIAIGAS
 GLVLGTILAL AGLIYYKKK*

>P1;Onmy-DAB*0502
Onmy-DAB*0502  214 bases  
 MSMPIAFYIC LTLILFIFSG TDGYFYHRLA QCRYSSKDLH GIEYIDSYFF
 NKAEYVRFNS TVGRYVGYTE YGVKNAEAWN SDAGILGQEQ AGLESYCKHN
 ADISYSAILD KTVEPHVRLS SVTPPSGRHP AMLMCSAYDF YPKQVRVTWL
 RDGREVKSDV TSTEELANGD WYYQIHSHLE YTPKSGEKIS CMVEHISLTE
 PMMYHWDPSL PEAE*

>P1;Onmy-DAB*0601
Onmy-DAB*0601  217 bases  
 YHRLAQCRYS SKDLHGIEFI DSYVFNKAEY VRFNSTVGRY VGYTEYGVKN
 AEAWNSDAGI LGQEQAELER FCKHNADLHY SAILDKTVEP HVRLSSVTPP
 SGRHPAMLMC SAYDFYPKQI RVTWLRDGRE VKSDVTSTEE LANGDWYYQI
 HSHLEYTPKS GEKISCMVEH ISLTEPMMYH WDPSLPEAER NKIAIGASGL
 VLGTILALAG LIYYKKK*

>P1;Onmy-DAB*0701
Onmy-DAB*0701  217 bases  
 NHRLRQCRYS SKDLHGIEYI DSYVFNKVEV IRFNSTVGRF VGYTEHGVKN
 AEAWNSDAGL LGQEQGELER VCKHNTANHY TAILDKTVEP HVRLSSVTPP
 SGRHPAMLMC SAYDFYPKQI RVTWLRDGRE VKSDVTSTEE LANGDWYYQI
 HSHLEYTPKS GEKISCMVEH ISLTEPMMYH WDPSLPEAER NKIAIGASGL
 VLGTILALAG LIYYKKK*

>P1;Onmy-DAB*0801
Onmy-DAB*0801  214 bases  
 MSMPIAFYIC LTLLWSIFSG TDGYFHQMMR QCRYSSKDLH GIELITSYVF
 NQAEYIRFNS TVGRFVGYTE HGLKNAEAWN SDAGILGQEQ AELERFCKHN
 ADLHYSAILD KTVEPHVRLS SVTPPSGRHP AMLMCSAYDF YPKQIRVTWL
 RDGREVKSDV TSTEELANGD WYYQIHSHLE YTPKSGEKIS CMVEHISLTE
 PMMYHWDPSL PEAE*

>P1;Onmy-DAB*0901
Onmy-DAB*0901  217 bases  
 EQSVRQCRFS SEDLHGIEFL HSYVFNKVED IRFNSTVGRF VGYTEHGVKN
 AEAWNSDAGI LGQEQGELER VCKHNADLHY SAILDKTVEP HVRLSSVTPP
 SGRHPAMLMC SAYDFYPKQI RVTWLRDGRE VKSDVTSTEE LANGDWYYQI
 HSHLEYTPKS GEKISCMVEH ISLTEPMMYH WDPSLPEAER NKIAIGASGL
 VLGTILALAG LIYYKKK*

>P1;Onmy-DAB*1001
Onmy-DAB*1001  217 bases  
 EQRVTQCRYS SEDLHGIEFI DSYVFNKVEY IRFNSTVGRF VGYTEHGVKN
 AEARNSDAGI LGQEQGELER YCKHNADIDY SAILDKTVEP HVRLSSVTPP
 SGKHPAMLMC SAYDFYPKQI RVTWLRDGRE VKSDVTSTEE LANGDWYYQI
 HSHLEYTPKS GEKISCMVEH ISLTEPMMYH WDPSLPEAER NKIAIGASGL
 VLGTILALAG LIYYKKK*

>P1;Onmy-DAB*1101
Onmy-DAB*1101  217 bases  
 HQRVTQCRYS SKDLHGIEFI DSYVFNKAEY VRFNSTVGRF VGYTEHGLKN
 AEAWNSDAGI LGQEQAELER FCKPNADIYY SAIRDKTVEP HVRLSSVTPP
 SGRHPAMLMC SAYDFYPKQI RVTWLRDGRE VKSDVTSTEE LANGDWYYQI
 HSHLEYTPKS GEKISCMVEH ISLTEPMMYH WDPSLPEAER NKIAIGASGL
 VLGTILALAG LIYYKKK*

>P1;Onmy-DAB*1201
Onmy-DAB*1201  217 bases  
 HQRVTQCRFS SEDLHGMEYI DSYVFNKVEH IRFNSTVGRY VGYTEHGVKN
 AEAWNSDAGI LGQEQAQLES YCKHNADIDY SAILDKTVEP HVRLSSVTPP
 SGRHPAMLMC SAYDFYPKQI RVTWLRDGRE VKSDVTSTEE LANGDWYYQI
 HSHLEYTPKS GEKISCMVEH ISLTEPMMYH WDPSLPEAER NKIAIGASGL
 VLGTILALAG LIYYKKK*

>P1;Onmy-DAB*1301
Onmy-DAB*1301  217 bases  
 HQTVKQCRFS SKDLHGIEFI DSYVFNKVEY IRFNSTVGRF VGYTEHGVKN
 AEAWNSDAGI LGQEQAQLES YCKPNADIDY SAILDKTVEP HVRLSSVTPP
 SGRHPAMLMC SAYDFYPKQI RVTWLRDGRE VKSDVTSTEE LANGDWYYQI
 HSHLEYTPKS GEKISCMVEH ISLTEPMMYH WDPSLPEAER NKIAIGASGL
 VLGTILALAG LIYYKKK*

>P1;Onmy-DAB*1401
Onmy-DAB*1401  217 bases  
 HQTVSQCRYS SEDLHGMEYI DSYVFNKVED IRFNSTVGRY VGYTEHGVKN
 AEAWNSDAGI LGQEQAELER FCKPNADLHY SAILDKTVEP HVRLSSVTPP
 SGRHPAMLMC SAYDFYPKQI RVTWLRDGRE VKSDVTSTEE LANGDWYYQI
 HSHLEYTPKS GEKISCMVEH ISLTEPMMYH WDPSLPEAER NKIAIGASGL
 VLGTILALAG LIYYKKK*

>P1;Onmy-DAB*1501
Onmy-DAB*1501  217 bases  
 HQTVSQCRYS SKDLHGIEYI DSYVFNKVEY IRFNSTVGRY VGYTEHGVKN
 AEALNSDAGI LGQEQAELER FCKHNAANHY SAILDKTVEP HVRLSSVTPP
 SGRHPAMLMC SAYDFYPKPI RVTWLRDGRE VKSDVTSTEE LANGDWYYQI
 HSHLEYTPKS GEKISCMVEH ISLTEPMMYH WDPSLPEAER NKIAIGASGL
 VLGTILALAG LIYYKKK*

>P1;Onmy-DAB*1601
Onmy-DAB*1601  247 bases  
 MSKSIRFYIC LAVALSTLYE TDGYASDVVT RCLYSSIDMH GAEFIQSYTF
 NKVEHLRFNS TVGEFVGYTE LGLKNAKRLN RGQEVVQMRG ELERLCKPNA
 DIHYRAILDK TVEPHVRLSS VTPPSGRHPA MLMCSAYDFY PKPIRVTWLR
 DGREVKSDVT STEELANGDW YYQIHSHLEY TPKSGEKISC MVEHISLTEP
 MMYHWDPSLP EAERNKIAIG ASGLVLGTIL ALAGLIYYKK KSSGVLX*

>P1;Onmy-DAB*1602
Onmy-DAB*1602  213 bases  
 MSKSIRFYIC LAVALSTLYE TDGYASDVVT RCLYSSIDMH GAEFIQSYTF
 NKVEHLRFNS TVGEFVGYTE LGLKNAKRLN RGQEVVQMRG ELERLCEPNA
 DVHYRAILDK TVEPHVRLSS VTPPSGRHPA MLMCSAYDFY PKPIRVTWLR
 DGREVKSDVT STEELANGDW YYQIHSHLEY TPKSGEKISC MVEHISLTEP
 MMYHWDPSLP EAE*

>P1;Onmy-DAB*1701
Onmy-DAB*1701  214 bases  
 MSMPIAFYIC LTLILSIFSG TDGYFYQMMR QCRYSSKDLH GIELITSYVF
 NQAEYIRFNS TVGRFVGYTE HGLKNAEAWN SDAGILGQEQ AQLESFCKHN
 ADIYYSAIRD KTVEPHVRLS SVTPPSGRHP AMLMCSAYDF YPKQIRVTWL
 RDGREVKSDV TSTEELANGD WYYQIHSHLE YTPKSGEKIS CMVEHISLTE
 PMMYHWDPSL PEAE*

