>DL;Onmy-DAB*0101
Onmy-DAB*0101  741 bases  
 ATGTCGATGC CAATTGCCTT CTACATTTGC CTGACCCTGT TATGGTCCAT
 ATTCTCTGGA ACAGATGGAT ATTTTGAACA GGTTGTGAGA CAGTGTCGAT
 ACTCCTCAAA GGACCTGCAT GGTATAGAGT TTATAGACTC TTATGTTTTC
 AATAAGGCTG AACATGTCAG ATTCAACAGC ACTGTGGGGA GGTATGTTGG
 ATACACTGAA CATGGTCTGA AGAATGCAGA AGCATGGAAC AGTGATGCTG
 GGATCCTGGG TCAAGAGCAG GCGGAGCTGG AGCGTTACTG TAAGCCTAGC
 GCTGCTATCG ACTACAGCGC CATACTGGAC AAGACAGTTG AGCCCCATGT
 CAGACTGAGC TCAGTGACTC CCCCCAGTGG CAGACACCCT GCCATGCTGA
 TGTGCAGCGC CTATGACTTC TACCCCAAAC AAATCAGAGT GACCTGGCTG
 AGGGACGGAC GTGAGGTGAA ATCTGATGTG ACCTCCACTG AGGAGCTGGC
 TAACGGGGAC TGGTACTACC AGATCCACTC CCACCTGGAG TACACACCCA
 AGTCTGGAGA GAAGATCTCC TGTATGGTGG AGCACATCAG CCTCACTGAG
 CCCATGATGT ATCACTGGGA CCCGTCCCTG CCTGAGGCTG AGAGGAATAA
 GATAGCGATC GGTGCATCTG GTCTGGTGCT GGGAACCATC TTAGCATTAG
 CAGGACTGAT CTACTACAAG AAGAAGTCTT CTGGGGTGCT C*

>DL;Onmy-DAB*0201
Onmy-DAB*0201  741 bases  
 ATGTCGATGC CAATTGCCTT CTACATTTGC CTGACCCTGT TATGGTCCAT
 ATTCTCTGGA ACAGATGGAT ATTTTCATCA GAGGGTGACA CAGTGTCGAT
 TCTCCTCAGA GGACCTGCAT GGTATGGAGT ATATAGACTC TTATGTTTTC
 AATCAGGCTG AATATATCAG ATTCAACAGC ACTGTGGGGA GGTTTGTTGG
 ATACACTGAA CATGGTCTGA AGAATGCAGA AGCATGGAAC AGTGATGCTG
 GGATCCTGGG TCAAGAGCAG GTGCAGCTGG AGAGTTACTG TAAGCATAAC
 GCTGCTATCG ACTACAGCGC CATACTGGAC AAGACAGTTG AGCCCCATGT
 CAGACTGAGC TCAGTGACTC CCCCCAGTGG CAGACACCCT GCCATGCTGA
 TGTGCAGCGC CTATGACTTC TACCCCAAAC AAATCAGAGT GACCTGGCTG
 AGGGACGGAC GTGAGGTGAA ATCTGATGTG ACCTCCACTG AGGAGCTGGC
 TAACGGGGAC TGGTACTACC AGATCCACTC CCACCTGGAG TACACACCCA
 AGTCTGGAGA GAAGATCTCC TGTATGGTGG AGCACATCAG CCTCACTGAG
 CCCATGATGT ATCACTGGGA CCCGTCCCTG CCTGAGGCTG AGAGGAATAA
 GATAGCGATC GGTGCATCTG GTCTGGTGCT GGGAACCATC TTAGCATTAG
 CAGGACTGAT CTACTACAAG AAGAAGTCTT CTGGGGTGCT C*

>DL;Onmy-DAB*030101
Onmy-DAB*030101  653 bases  
 TTGAACATCG GTTGGCACAG TGTCGATACT CCTCAAAGGA CCTGCATGGT
 ATAGAGTTTA TAGACTCTTT TTTTTTCAAT AAGGTTGAAG ATATCAGATT
 CAACAGCACT GTGGGGAGGT ATGTTGGATA CACTGAACAT GGTGTGAAGA
 ATGCAGAAGC ATGGAACAGT GATGCTGGGA TCCTGGGTCA AGAGCAGGCG
 GAGCTGGAGC GTGTCTGTAA GCATAACGCT GATCTCCACT ACAGCGCCAT
 ACTGGACAAG ACAGTTGAGC CCCATGTCAG ACTGAGCTCA GTGACTCCCC
 CCAGTGGCAG ACACCCTGCC ATGCTGATGT GCAGCGCCTA TGACTTCTAC
 CCCAAACAAA TCAGAGTGAC CTGGCTGAGG GACGGACGTG AGGTGAAATC
 TGATGTGACC TCCACTGAGG AGCTGGCTAA CGGGGACTGG TACTACCAGA
 TCCACTCCCA CCTGGAGTAC ACACCCAAGT CTGGAGAGAA GATCTCCTGC
 ATGGTGGAGC ACATCAGCCT CACTGAGCCC ATGATGTATC ACTGGGACCC
 GTCCCTGCCT GAGGCTGAGA GGAATAAGAT AGCGATCGGG GCATCTGGTC
 TGGTGCTGGG AACCATCTTA GCATTAGCAG GACTGATCTA CTACAAGAAG
 AAG*

>DL;Onmy-DAB*030102
Onmy-DAB*030102  654 bases  
 CAGTGTCGAT ACTCCTCAAA GGACCTGCAT GGTATAGAGT TTATAGACTC
 TTTTTTTTTC AATAAGGTTG AAGATATCAG ATTCAACAGC ACTGTGGGGA
 GGTATGTTGG ATACACTGAA CATGGTGTGA AGAATGCAGA AGCATGGAAC
 AGTGATGCTG GGATCCTGGG TCAAGAGCAG GCGGAGCTGG AGCGTGTCTG
 TAAGCATAAC GCTGATCTCC ACTACAGCGC CATACTGGAC AAGACAGTTG
 AGCCCCATGT CAGACTGAGC TCAGTGACTC CCCCCAGTGG CAGACACCCT
 GCCATGCTGA TGTGCAGCGC CTATGACTTC TACCCCAAAC AAATCAGAGT
 GACCTGGCTG AGGGACGGAC GTGAGGTGAA ATCTGATGTG ACCTCCACTG
 AGGAGCTGGC TAACGGGGAC TGGTACTACC AGATCCACTC CCACCTGGAG
 TACACACCCA AGTCTGGAGA GAAGATCTCC TGTATGGTGG AGCACATCAG
 CCTCACTGAG CCCATGATGT ATCACTGGGA CCCGTCCCTG CCTGAGGCTG
 AGAGGAATAA GATAGCGATC GGTGCATCTG GTCTGGTGCT GGGAACCATC
 TTAGCATTAG CAGGACTGAT CTACTACAAG AAGAAGTCTT CTGGGGTGCT
 CTAG*

>DL;Onmy-DAB*0401
Onmy-DAB*0401  653 bases  
 TTCATCATCG GTTGGCACAG TGTCGATACT CCTCAAAGGA CCTGCATGGT
 ATAGAGTTTA TAGACTCTTA TGTTTTCAAT AAGGTTGAAC ATATCAGATT
 CAACAGCACT GTGGGGAGGT ATGTTGGATA CACTGAACAT GGTCTGAAGA
 ATGCAGAAGC ATGGAACAGT GATGCTGGGA TCCTGGGTCA AGAGCAGGCG
 GAGCTGGAGC GTTTCTGTAA GCATAACGCT GCTAACCACT ACAGCGCCAT
 ACTGGACAAG ACAGTTGAGC CCCATGTCAG ACTGAGCTCA GTGACTCCCC
 CCAGTGGCAG ACACCCTGCC ATGCTGATGT GCAGCGCCTA TGACTTCTAC
 CCCAAACAAA TCAGAGTGAC CTGGCTGAGG GACGGACGTG AGGTGAAATC
 TGATGTGACG TCCACTGAGG AGCTGGCTAA CGGGGACTGG TACTACCAGA
 TCCACTCCCA CCTGGAGTAC ACACCCAAGT CTGGAGAGAA GATCTCCTGT
 ATGGTGGAGC ACATCAGCCT CACTGAGCCC ATGATGTATC ACTGGGACCC
 GTCCCTGCCT GAGGCTGAGA GGAATAAGAT AGCGATCGGT GCATCTGGTC
 TGGTGCTGGG AACCATCTTA GCATTAGCAG GACTGATCTA CTACAAGAAG
 AAG*

>DL;Onmy-DAB*050101
Onmy-DAB*050101  653 bases  
 TTTATCATCG GTTGGCACAG TGTCGATACT CCTCAAAGGA CCTGCATGGT
 ATAGAGTATA TAGACTCTTA TTTTTTCAAT AAGGCTGAAT ATGTCAGATT
 CAACAGCACT GTGGGGAGGT ATGTTGGATA CACTGAGTAT GGTGTGAAGA
 ATGCAGAAGC ATGGAACAGT GATGCTGGGA TCCTGGGTCA AGAGCAGGCG
 GGGCTGGAGA GTTACTGTAA GCATAACGCT GATATTTCCT ACAGCGCCAT
 ACTGGACAAG ACAGTTGAGC CCCATGTCAG ACTGAGCTCA GTGACTCCCC
 CCAGTGGCAG ACACCCTGCC ATGCTGATGT GCAGCGCCTA TGACTTCTAC
 CCCAAACAAA TCAGAGTGAC CTGGCTGAGG GACGGACGTG AGGTGAAATC
 TGATGTGACC TCCACTGAGG AGCTGGCTAA CGGGGACTGG TACTACCAGA
 TCCACTCCCA CCTGGAGTAC ACACCCAAGT CTGGAGAGAA GATCTCCTGC
 ATGGTGGAGC ACATCAGCCT CACTGAGCCC ATGATGTATC ACTGGGACCC
 GTCCCTGCCT GAGGCTGAGA GGAATAAGAT AGCGATCGGT GCATCTGGTC
 TGGTGCTGGG AACCATCTTA GCATTAGCAG GACTGATCTA CTACAAGAAG
 AAG*

>DL;Onmy-DAB*050102
Onmy-DAB*050102  548 bases  
 GATATTTTTA TCATCGGTTG GCACAGTGTC GATACTCCTC AAAGGACCTG
 CATGGTATAG AGTATATAGA CTCTTATTTT TTCAATAAGG CTGAATATGT
 CAGATTCAAC AGCACTGTGG GGAGGTATGT TGGATACACT GAGTATGGTG
 TGAAGAATGC AGAAGCATGG AACAGTGATG CTGGGATCCT GGGTCAAGAG
 CAGGCGGGGC TGGAGAGTTA CTGTAAGCAT AACGCTGATA TTTCCTACAG
 CGCCATACTG GACAAGACAG TTGAGCCCCA TGTCAGACTG AGCTCAGTGA
 CTCCCCCCAG TGGCAGACAC CCTGCCATGC TGATGTGCAG CGCCTATGAC
 TTCTACCCCA AACAAATCAG AGTGACCTGG CTGAGGGACG GACGTGAGGT
 GAAATCTGAT GTGACGTCCA CTGAGGAGCT GGCTAACGGG GACTGGTACT
 ACCAGATCCA CTCCCACCTG GAGTACACAC CCAAGTCTGG AGAGAAGATC
 TCCTGTATGG TGGAGCACAT CAGCCTCACT GAGCCCATGA TGTATCAC*

>DL;Onmy-DAB*0502
Onmy-DAB*0502  642 bases  
 ATGTCGATGC CAATTGCCTT CTACATTTGC CTGACCTTGA TTTTGTTCAT
 ATTCTCTGGA ACAGATGGAT ATTTTTATCA TCGGTTGGCA CAGTGTCGAT
 ACTCCTCAAA GGACCTGCAT GGTATAGAGT ATATAGACTC TTATTTTTTC
 AATAAGGCTG AATATGTCAG ATTCAACAGC ACTGTGGGGA GGTATGTTGG
 ATACACTGAG TATGGTGTGA AGAATGCAGA AGCATGGAAC AGTGATGCTG
 GGATCCTGGG TCAAGAGCAG GCGGGGCTGG AGAGTTACTG TAAGCATAAC
 GCTGATATTT CCTACAGCGC CATACTGGAC AAGACAGTTG AGCCCCATGT
 CAGACTGAGC TCAGTGACTC CCCCCAGTGG CAGACACCCT GCCATGCTGA
 TGTGCAGCGC CTATGACTTC TACCCCAAAC AAGTCAGAGT GACCTGGCTG
 AGGGACGGAC GTGAGGTGAA ATCTGATGTG ACCTCCACTG AGGAGCTGGC
 TAACGGGGAC TGGTACTACC AGATCCACTC CCACCTGGAG TACACACCCA
 AGTCTGGAGA GAAGATCTCC TGCATGGTGG AGCACATCAG CCTCACTGAG
 CCCATGATGT ATCACTGGGA CCCGTCCCTG CCTGAGGCTG AA*

>DL;Onmy-DAB*060101
Onmy-DAB*060101  653 bases  
 TTTATCATCG GTTGGCACAG TGTCGATACT CCTCAAAGGA CCTGCATGGT
 ATAGAGTTTA TAGACTCTTA TGTTTTCAAT AAGGCTGAAT ATGTCAGATT
 CAACAGCACT GTGGGGAGGT ATGTTGGATA CACTGAGTAT GGTGTGAAGA
 ATGCAGAAGC ATGGAACAGT GATGCTGGGA TCCTGGGTCA AGAGCAGGCG
 GAGCTGGAGC GTTTCTGTAA GCATAACGCT GATCTCCACT ACAGCGCCAT
 ACTGGACAAG ACAGTTGAGC CCCATGTCAG ACTGAGCTCA GTGACTCCCC
 CCAGTGGCAG ACACCCTGCC ATGCTGATGT GCAGCGCCTA TGACTTCTAC
 CCCAAACAAA TCAGAGTGAC CTGGCTGAGG GACGGACGTG AGGTGAAATC
 TGATGTGACC TCCACTGAGG AGCTGGCTAA CGGGGACTGG TACTACCAGA
 TCCACTCCCA CCTGGAGTAC ACACCCAAGT CTGGAGAGAA GATCTCCTGC
 ATGGTGGAGC ACATCAGCCT CACTGAGCCC ATGATGTATC ACTGGGACCC
 GTCCCTGCCT GAGGCTGAGA GGAATAAGAT AGCGATCGGG GCATCTGGTC
 TGGTGCTGGG AACCATCTTA GCATTAGCAG GACTGATCTA CTACAAGAAG
 AAG*

>DL;Onmy-DAB*060102
Onmy-DAB*060102  653 bases  
 TTTATCATCG GTTGGCACAG TGTCGATACT CCTCAAAGGA CCTGCATGGT
 ATAGAGTTTA TAGACTCTTA TGTTTTCAAT AAGGCTGAAT ATGTCAGATT
 CAACAGCACT GTGGGGAGGT ATGTTGGATA CACTGAGTAT GGTGTGAAGA
 ATGCAGAAGC ATGGAACAGT GATGCTGGGA TCCTGGGTCA AGAGCAGGCG
 GAGCTGGAGC GTTTCTGTAA GCATAACGCT GATCTCCACT ACAGCGCCAT
 ACTGGACAAG ACAGTTGAGC CCCATGTCAG ACTGAGCTCA GTGACTCCCC
 CCAGTGGCAG ACACCCTGCC ATGCTGATGT GCAGCGCCTA TGACTTCTAC
 CCCAAACAAA TCAGAGTGAC CTGGCTGAGG GACGGACGTG AGGTGAAATC
 TGATGTGACC TCCACTGAGG AGCTGGCTAA CGGGGACTGG TACTACCAGA
 TCCACTCCCA CCTGGAGTAC ACACCCAAGT CTGGAGAGAA GATCTCCTGC
 ATGGTGGAGC ACATCAGCCT CACTGAGCCC ATGATGTATC ACTGGGACCC
 GTCCCTGCCT GAGGCTGAGA GGAATAAGAT AGCGATCGGT GCATCTGGTC
 TGGTGCTGGG AACCATCTTA GCATTAGCAG GACTGATCTA CTACAAGAAG
 AAG*

>DL;Onmy-DAB*0701
Onmy-DAB*0701  653 bases  
 TTAATCATCG GTTAAGACAG TGTCGATACT CCTCAAAGGA CCTGCATGGT
 ATAGAGTATA TAGACTCTTA TGTTTTCAAT AAGGTTGAAG TTATCAGATT
 CAACAGCACT GTGGGGAGGT TTGTTGGATA CACTGAACAT GGTGTGAAGA
 ATGCAGAAGC ATGGAACAGT GATGCTGGGT TGCTGGGTCA AGAGCAGGGG
 GAGCTGGAGC GTGTCTGTAA GCATAACACT GCTAACCACT ACACCGCCAT
 ACTGGACAAG ACAGTTGAGC CCCATGTCAG ACTGAGCTCA GTGACTCCCC
 CCAGTGGCAG ACACCCTGCC ATGCTGATGT GCAGCGCCTA TGACTTCTAC
 CCCAAACAAA TCAGAGTGAC CTGGCTGAGG GACGGACGTG AGGTGAAATC
 TGATGTGACC TCCACTGAGG AGCTGGCTAA CGGGGACTGG TACTACCAGA
 TCCACTCCCA CCTGGAGTAC ACACCCAAGT CTGGAGAGAA GATCTCCTGT
 ATGGTGGAGC ACATCAGCCT CACTGAGCCC ATGATGTATC ACTGGGACCC
 GTCCCTGCCT GAGGCTGAGA GGAATAAGAT AGCGATCGGT GCATCTGGTC
 TGGTGCTGGG AACCATCTTA GCATTAGCAG GACTGATCTA CTACAAGAAG
 AAG*

>DL;Onmy-DAB*0801
Onmy-DAB*0801  642 bases  
 ATGTCGATGC CAATTGCCTT CTACATTTGC CTGACCCTGT TATGGTCCAT
 ATTCTCTGGA ACAGATGGAT ATTTTCATCA GATGATGAGA CAGTGTCGAT
 ACTCCTCAAA GGACCTGCAT GGTATAGAGT TGATTACCTC TTATGTTTTC
 AATCAGGCTG AATATATCAG ATTCAACAGC ACTGTGGGGA GGTTTGTTGG
 ATACACTGAA CATGGTCTGA AGAATGCAGA AGCATGGAAC AGTGATGCTG
 GGATCCTGGG TCAAGAGCAG GCGGAGCTGG AGCGTTTCTG TAAGCATAAC
 GCTGATCTCC ACTACAGCGC CATACTGGAC AAGACAGTTG AGCCCCATGT
 CAGACTGAGC TCAGTGACTC CCCCCAGTGG CAGACACCCT GCCATGCTGA
 TGTGCAGCGC CTATGACTTC TACCCCAAAC AAATCAGAGT GACCTGGCTG
 AGGGACGGAC GTGAGGTGAA ATCTGATGTG ACCTCCACTG AGGAGCTGGC
 TAACGGGGAC TGGTACTACC AGATCCACTC CCACCTGGAG TACACACCCA
 AGTCTGGAGA GAAGATCTCC TGTATGGTGG AGCACATCAG CCTCACTGAG
 CCCATGATGT ATCACTGGGA CCCGTCCCTG CCTGAGGCTG AG*

>DL;Onmy-DAB*0901
Onmy-DAB*0901  653 bases  
 TTGAACAGTC TGTGAGACAG TGTCGATTCT CCTCAGAGGA CCTGCATGGT
 ATAGAGTTTC TACACTCTTA TGTTTTCAAT AAGGTTGAAG ATATCAGATT
 CAACAGCACT GTGGGGAGGT TTGTTGGATA CACTGAACAT GGTGTGAAGA
 ATGCAGAAGC ATGGAACAGT GATGCTGGGA TCCTGGGTCA AGAGCAGGGG
 GAGCTGGAGC GTGTCTGTAA GCATAACGCT GATCTCCACT ACAGCGCCAT
 ACTGGACAAG ACAGTTGAGC CCCATGTCAG ACTGAGCTCA GTGACTCCCC
 CCAGTGGCAG ACACCCTGCC ATGCTGATGT GCAGCGCCTA TGACTTCTAC
 CCCAAACAAA TCAGAGTGAC CTGGCTGAGG GACGGACGTG AGGTGAAATC
 TGATGTGACG TCCACTGAGG AGCTGGCTAA CGGGGACTGG TACTACCAGA
 TCCACTCCCA CCTGGAGTAC ACACCCAAGT CTGGAGAGAA GATCTCCTGT
 ATGGTGGAGC ACATCAGCCT CACTGAGCCC ATGATGTATC ACTGGGACCC
 GTCCCTGCCT GAGGCTGAGA GGAATAAGAT AGCGATCGGT GCATCTGGTC
 TGGTGCTGGG AACCATCTTA GCATTAGCAG GACTGATCTA CTACAAGAAG
 AAG*

>DL;Onmy-DAB*1001
Onmy-DAB*1001  653 bases  
 TTGAACAGAG GGTGACACAG TGTCGATACT CCTCAGAGGA CCTGCATGGT
 ATAGAGTTTA TAGACTCTTA TGTTTTCAAT AAGGTTGAAT ATATCAGATT
 CAACAGCACT GTGGGGAGGT TTGTTGGATA CACTGAGCAT GGTGTGAAGA
 ATGCAGAAGC ACGGAACAGT GATGCTGGGA TCCTGGGTCA AGAGCAGGGG
 GAGCTGGAGC GTTACTGTAA GCATAACGCT GATATCGACT ACAGCGCCAT
 ACTGGACAAG ACAGTTGAGC CCCATGTCAG ACTGAGCTCA GTGACTCCCC
 CCAGTGGCAA ACACCCTGCC ATGCTGATGT GCAGCGCCTA TGACTTCTAC
 CCCAAACAAA TCAGAGTGAC CTGGCTGAGG GACGGACGTG AGGTGAAATC
 TGATGTGACC TCCACTGAGG AGCTGGCTAA CGGGGACTGG TACTACCAGA
 TCCACTCCCA CCTGGAGTAC ACACCCAAGT CTGGAGAGAA GATCTCCTGT
 ATGGTGGAGC ACATCAGCCT CACTGAGCCC ATGATGTATC ACTGGGACCC
 GTCCCTGCCT GAGGCTGAGA GGAATAAGAT AGCGATCGGT GCATCTGGTC
 TGGTGCTGGG AACCATCTTA GCATTAGCAG GACTGATCTA CTACAAGAAG
 AAG*

>DL;Onmy-DAB*1101
Onmy-DAB*1101  653 bases  
 TTCATCAGAG GGTGACACAG TGTCGATACT CCTCAAAGGA CCTGCATGGT
 ATAGAGTTTA TAGACTCTTA TGTTTTCAAT AAGGCTGAAT ATGTCAGATT
 CAACAGCACT GTGGGGAGGT TTGTTGGATA CACTGAACAT GGTCTGAAGA
 ATGCAGAAGC ATGGAACAGT GATGCTGGGA TCCTGGGTCA AGAGCAGGCG
 GAGCTGGAGC GTTTCTGTAA GCCTAACGCT GATATCTACT ACAGCGCCAT
 ACGGGACAAG ACAGTTGAGC CCCATGTCAG ACTGAGCTCA GTGACTCCCC
 CCAGTGGCAG ACACCCTGCC ATGCTGATGT GCAGCGCCTA TGACTTCTAC
 CCCAAACAAA TCAGAGTGAC CTGGCTGAGG GACGGACGTG AGGTGAAATC
 TGATGTGACC TCCACTGAGG AGCTGGCTAA CGGGGACTGG TACTACCAGA
 TCCACTCCCA CCTGGAGTAC ACACCCAAGT CTGGAGAGAA GATCTCCTGC
 ATGGTGGAGC ACATCAGCCT CACTGAGCCC ATGATGTATC ACTGGGACCC
 GTCCCTGCCT GAGGCTGAGA GGAATAAGAT AGCGATCGGT GCATCTGGTC
 TGGTGCTGGG AACCATCTTA GCATTAGCAG GACTGATCTA CTACAAGAAG
 AAG*

>DL;Onmy-DAB*1201
Onmy-DAB*1201  653 bases  
 TTCATCAGAG GGTGACACAG TGTCGATTCT CCTCAGAGGA CCTGCATGGT
 ATGGAGTATA TAGACTCTTA TGTTTTCAAT AAGGTTGAAC ATATCAGATT
 CAACAGCACT GTGGGGAGGT ATGTTGGATA CACTGAACAT GGTGTGAAGA
 ATGCAGAAGC ATGGAACAGT GATGCTGGGA TCCTGGGTCA AGAGCAGGCG
 CAGCTGGAGA GTTACTGTAA GCATAACGCT GATATCGACT ACAGCGCCAT
 ACTGGACAAG ACAGTTGAGC CCCATGTCAG ACTGAGCTCA GTGACTCCCC
 CCAGTGGCAG ACACCCTGCC ATGCTGATGT GCAGCGCCTA TGACTTCTAC
 CCCAAACAAA TCAGAGTGAC CTGGCTGAGG GACGGACGTG AGGTGAAATC
 TGATGTGACC TCCACTGAGG AGCTGGCTAA CGGGGACTGG TACTACCAGA
 TCCACTCCCA CCTGGAGTAC ACACCCAAGT CTGGAGAGAA GATCTCCTGC
 ATGGTGGAGC ACATCAGCCT CACTGAGCCC ATGATGTATC ACTGGGACCC
 GTCCCTGCCT GAGGCTGAGA GGAATAAGAT AGCGATCGGT GCATCTGGTC
 TGGTGCTGGG AACCATCTTA GCATTAGCAG GACTGATCTA CTACAAGAAG
 AAG*

>DL;Onmy-DAB*1301
Onmy-DAB*1301  653 bases  
 TTCATCAGAC TGTGAAACAG TGTCGATTCT CCTCAAAGGA CCTGCATGGT
 ATAGAGTTTA TAGACTCTTA TGTTTTCAAT AAGGTTGAAT ATATCAGATT
 CAACAGCACT GTGGGGAGGT TTGTTGGATA CACTGAGCAT GGTGTGAAGA
 ATGCAGAAGC ATGGAACAGT GATGCTGGGA TCCTGGGTCA AGAGCAGGCG
 CAGCTGGAGA GTTACTGTAA GCCTAACGCT GATATCGACT ACAGCGCCAT
 ACTGGACAAG ACAGTTGAGC CCCATGTCAG ACTGAGCTCA GTGACTCCCC
 CCAGTGGCAG ACACCCTGCC ATGCTGATGT GCAGCGCCTA TGACTTCTAC
 CCCAAACAAA TCAGAGTGAC CTGGCTGAGG GACGGACGTG AGGTGAAATC
 TGATGTGACC TCCACTGAGG AGCTGGCTAA CGGGGACTGG TACTACCAGA
 TCCACTCCCA CCTGGAGTAC ACACCCAAGT CTGGAGAGAA GATCTCCTGT
 ATGGTGGAGC ACATCAGCCT CACTGAGCCC ATGATGTATC ACTGGGACCC
 GTCCCTGCCT GAGGCTGAGA GGAATAAGAT AGCGATCGGT GCATCTGGTC
 TGGTGCTGGG AACCATCTTA GCATTAGCAG GACTGATCTA CTACAAGAAG
 AAG*

>DL;Onmy-DAB*1401
Onmy-DAB*1401  653 bases  
 TTCATCAGAC TGTGAGCCAG TGTCGATACT CCTCAGAGGA CCTGCATGGT
 ATGGAGTATA TAGACTCTTA TGTTTTCAAT AAGGTTGAAG ATATCAGATT
 CAACAGCACT GTGGGGAGGT ATGTTGGATA CACTGAACAT GGTGTGAAGA
 ATGCAGAAGC ATGGAACAGT GATGCTGGGA TCCTGGGTCA AGAGCAGGCG
 GAGCTGGAGC GTTTCTGTAA GCCTAACGCT GATCTCCACT ACAGCGCCAT
 ACTGGACAAG ACAGTTGAGC CCCATGTCAG ACTGAGCTCA GTGACTCCCC
 CCAGTGGCAG ACACCCTGCC ATGCTGATGT GCAGCGCCTA TGACTTCTAC
 CCCAAACAAA TCAGAGTGAC CTGGCTGAGG GACGGACGTG AGGTGAAATC
 TGATGTGACC TCCACTGAGG AGCTGGCTAA CGGGGACTGG TACTACCAGA
 TCCACTCCCA CCTGGAGTAC ACACCCAAGT CTGGAGAGAA GATCTCCTGC
 ATGGTGGAGC ACATCAGCCT CACTGAGCCC ATGATGTATC ACTGGGACCC
 GTCCCTGCCT GAGGCTGAGA GGAATAAGAT AGCGATCGGG GCATCTGGTC
 TGGTGCTGGG AACCATCTTA GCATTAGCAG GACTGATCTA CTACAAGAAG
 AAG*

>DL;Onmy-DAB*1501
Onmy-DAB*1501  653 bases  
 TTCATCAGAC TGTGAGCCAG TGTCGATACT CCTCAAAGGA CCTGCATGGT
 ATAGAGTATA TAGACTCTTA TGTTTTCAAT AAGGTTGAAT ATATCAGATT
 CAACAGCACT GTGGGGAGGT ATGTTGGATA CACTGAACAT GGTGTGAAGA
 ATGCAGAAGC ATTGAACAGT GATGCTGGGA TCCTGGGTCA AGAGCAGGCG
 GAGCTGGAGC GTTTCTGTAA GCATAACGCT GCTAACCACT ACAGCGCCAT
 ACTGGACAAG ACAGTTGAGC CCCATGTCAG ACTGAGCTCA GTGACTCCCC
 CCAGTGGCAG ACACCCTGCC ATGCTGATGT GCAGCGCCTA TGACTTCTAC
 CCCAAACCAA TCAGAGTGAC CTGGCTGAGG GACGGACGTG AGGTGAAATC
 TGATGTGACC TCCACTGAGG AGCTGGCTAA CGGGGACTGG TACTACCAGA
 TCCACTCCCA CCTGGAGTAC ACACCCAAGT CTGGAGAGAA GATCTCCTGT
 ATGGTGGAGC ACATCAGCCT CACTGAGCCC ATGATGTATC ACTGGGACCC
 GTCCCTGCCT GAGGCTGAGA GGAATAAGAT AGCGATCGGT GCATCTGGTC
 TGGTGCTGGG AACCATCTTA GCATTAGCAG GACTGATCTA CTACAAGAAG
 AAG*

>DL;Onmy-DAB*1601
Onmy-DAB*1601  740 bases  
 TGTCTAAGTC AATTCGCTTC TACATTTGCC TAGCCGTGGC ATTATCCACT
 CTGTATGAAA CAGATGGATA TGCCTCCGAT GTGGTGACTC GATGTTTATA
 CAGCTCTATT GATATGCATG GTGCAGAGTT CATACAGTCT TATACCTTTA
 ATAAGGTTGA ACATCTCAGA TTCAACAGCA CTGTGGGTGA GTTTGTTGGA
 TACACTGAGC TGGGTCTGAA GAATGCAAAG AGATTGAACC GTGGTCAAGA
 GGTGGTTCAA ATGCGAGGAG AGCTGGAGCG TCTATGTAAG CCTAACGCTG
 ATATCCACTA CAGAGCCATA CTGGACAAGA CAGTTGAGCC CCATGTCAGA
 CTGAGCTCAG TGACTCCCCC CAGTGGCAGA CACCCTGCCA TGCTGATGTG
 CAGCGCCTAT GACTTCTACC CCAAACCAAT CAGAGTGACC TGGCTGAGGG
 ACGGACGTGA GGTGAAATCT GATGTGACCT CCACTGAGGA GCTGGCTAAC
 GGGGACTGGT ACTACCAGAT CCACTCCCAC CTGGAGTACA CACCCAAGTC
 TGGAGAGAAG ATCTCCTGCA TGGTGGAGCA CATCAGCCTC ACTGAGCCCA
 TGATGTATCA CTGGGACCCG TCCCTGCCTG AGGCTGAGAG GAATAAGATA
 GCGATCGGGG CATCTGGTCT GGTGCTGGGA ACCATCTTAG CATTAGCAGG
 ACTGATCTAC TACAAGAAGA AGTCTTCTGG GGTGCTCTAG*

>DL;Onmy-DAB*1602
Onmy-DAB*1602  640 bases  
 ATGTCTAAGT CAATTCGCTT CTACATTTGC CTAGCCGTGG CATTATCCAC
 TCTGTATGAA ACAGATGGAT ATGCCTCCGA TGTGGTGACT CGATGTTTAT
 ACAGCTCTAT TGATATGCAT GGTGCAGAGT TCATACAGTC TTATACCTTT
 AATAAGGTTG AACATCTCAG ATTCAACAGC ACTGTGGGTG AGTTTGTTGG
 ATACACTGAG CTGGGTCTGA AGAATGCAAA GAGATTGAAC CGTGGTCAAG
 AGGTGGTTCA AATGCGAGGA GAGCTGGAGC GTCTATGTGA GCCTAACGCT
 GATGTCCACT ACAGAGCCAT ACTGGACAAG ACAGTTGAGC CCCATGTCAG
 ACTGAGCTCA GTGACTCCCC CCAGTGGCAG ACACCCTGCC ATGCTGATGT
 GCAGCGCCTA TGACTTCTAC CCCAAACCAA TCAGAGTGAC CTGGCTGAGG
 GACGGACGTG AGGTGAAATC TGATGTGACC TCCACTGAGG AGCTGGCTAA
 CGGGGACTGG TACTACCAGA TCCACTCCCA CCTGGAGTAC ACACCCAAGT
 CTGGAGAGAA GATCTCCTGC ATGGTGGAGC ACATCAGCCT CACTGAGCCC
 ATGATGTATC ACTGGGACCC GTCCCTGCCT GAGGCTGAGA*

>DL;Onmy-DAB*1701
Onmy-DAB*1701  642 bases  
 ATGTCGATGC CAATTGCCTT CTACATTTGC CTGACCCTGA TTTTGTCCAT
 ATTCTCTGGA ACAGATGGAT ATTTTTATCA GATGATGAGA CAGTGTCGAT
 ACTCCTCAAA GGACCTGCAT GGTATAGAGT TGATTACCTC TTATGTTTTC
 AATCAGGCTG AATATATCAG ATTCAACAGC ACTGTGGGGA GGTTTGTTGG
 ATACACTGAA CATGGTCTGA AGAATGCAGA AGCATGGAAC AGTGATGCTG
 GGATCCTGGG TCAAGAGCAG GCGCAGCTGG AGAGTTTCTG TAAGCATAAC
 GCTGATATCT ACTACAGCGC CATACGGGAC AAGACAGTTG AGCCCCATGT
 CAGACTGAGC TCAGTGACTC CCCCCAGTGG CAGACACCCT GCCATGCTGA
 TGTGCAGCGC CTATGACTTC TACCCCAAAC AAATCAGAGT GACCTGGCTG
 AGGGACGGAC GTGAGGTGAA ATCTGATGTG ACCTCCACTG AGGAGCTGGC
 TAACGGGGAC TGGTACTACC AGATCCACTC CCACCTGGAG TACACACCGA
 AGTCTGGAGA GAAGATCTCC TGTATGGTGG AGCACATCAG CCTCACTGAG
 CCCATGATGT ATCACTGGGA CCCGTCCCTG CCTGAGGCTG AG*

