>DL;Onmy-UBA*0101
Onmy-UBA*0101  1059 bases  
 ATGAAGGGTA TTATCTTGCT GGTGCTGGGA ATAGGCCTTC TTCATACAGC
 ATCTGCTGCG ACTCACTCCC TGAAGTATTT CTACACCGCA TCTTCTGAAG
 TTCCCAACTT CCCAGAGTTC GTGGTTGTGG CGATGGTGGA TGGTGCTCAG
 ATGGTTCACT ATGACAGCAA CAGCCAGAGA GCGGTGCCCA AACAGGACTG
 GATGAACAGG GCAGCAGAAA CACTGCCACA GTACTGGGAG AGTCAGACAG
 GGATTTTCAA GGGTGCCCAG CAGACTTTCA AAGCCAACAT CGATATTGTA
 AAGCAGCGTT TTAACCAAAG TGGAGGTGTG CACATTGTCC AGAAGATGTA
 CGGTTGTGAG TGGGATGATG AGGCTGGAGT CACAGAGGGG TTTTATCAGT
 ATGGATATGA TGGAGAGGAT TTCATAGCAC TTGACCTGAA AACAACGAAA
 TGGATCGCCC CAACGCCACA GGCAGTCATC ACCAAACTCA AGTGGGACAG
 TAACACAGCT AACACTGAGT ACTGGAACAA CTACCTGACC CAGACCTGCA
 TTGAGTGGCT GAAGAAGTAT GTGGACTATG GGAAGAGCAC TCTGATGAGG
 ACAGTCCCTC CCTCAGTGTC TCTGCTCCAG AAGGCCCCCT CCTCTCCAGT
 GACCTGCCAC GCGACAGGTT TCTACCCCAG GGATGTCATG GTGTCCTGGC
 AGAAAGACGG ACAAGATCAC CATGAGGATG TGGAGTATGG AGAGACTCTC
 CCCAACGATG ATGGAACCTT CCAAAAAAGC TCCCACCTGA CAGTGACGCC
 TGAGGACAGG AAGAACAGCA AGTATCAGTG TGTGGTTCAA GTCAAGGGTA
 TCAAGAAGGA CTTCATCGAG GTTCTGACTG ACCCGGATGC CGCCAACGTT
 GTCCCCATCA TTGGAGGGGT GGTAGCTCTC CTCCTGGTCA TTGTTGCTGT
 TGTTGTTGGG GTCGTCATTT GGAAGAAGAG GAGTAAGAAA GGCTTTGTTC
 CGGCCAGCAC TTCCGACACT GACTCTGAAA ACTCTGGGAA AGCTGCCCCG
 CAGATTTGA*

>DL;Onmy-UBA*0102
Onmy-UBA*0102  1051 bases  
 TATTATCTTG CTGGTGCTGG GAATAGGCCT TCTTCATACA GCATCTGCTG
 CGACTCACTC CCTGAAGTAT TTCTACACCG CATCTTCTGA AGTTCCCAAC
 TTCCCAGAGT TCGTGGTTGT GGCGATGGTG GATGGTGCTC AGATGGTTCA
 CTATGACAGC AACAGCCAGA GAGCGGTGCC CAAACAGGAC TGGATGAACA
 GGGCAGCAGA AACACTGCCA CAGTACTGGG AGAGTCAGAC AGGGATTTTC
 AAGGGTGCCC AGCAGACTTT CAAAGCCAAC ATCGATATTG TAAAGCAGCG
 TTTTAACCAA AGTGGAGGTG TGCACATTGT CCAGAAGATG TACGGTTGTG
 AGTGGGATGA TGAGGCTGGA GTCACAGAGG GGTTTTATCA GTATGGATAT
 GATGGAGAGG ATTTCATAGC ACTTGACCTG AAAACAACGA AATGGATCGC
 CCCAACGCCA CAGGCAGTCA TCACCAAACT CAAGTGGGAC AGTAACACAG
 CTAACACTGA GTACTGGAAC AACTACCTGA CCCAGACCTG CATTGAGTGG
 CTGAAGAAGT ATGTGGACTA TGGGAAGAGC ACTCTGATGA GGACAGTCCC
 TCCCTCAGTG TCTCTGCTCC AGAAGGCCCC CTCCTCTCCA GTGACCTGCC
 ACGCGACAGG TTTCTACCCC AGGGATGTCA TGGTGTCCTG GCAGAAAGAC
 GGACAAGATC ACCATGAAGA TGTGGAGCAT GGAGAGATTC TCTTCAACGA
 TGATGGAACC TTCCAGAAAA GCTCCCACCT GACAGTGACG CCTGAGGACA
 GGAAGAACAG CAAGTATCAG TGTGTGGTTC AAGTCAAGGG TATCAAGAAG
 GACTTCATCG AGGTTCTGAC TGACCCGGAT GCCGCCAACG TTGTCCCCAT
 CATTGGAGGG GTGGTAGCTC TCCTCCTGGT CATTGTTGCT GTTGTTGTTG
 GGGTCGTCAT TTGGAAGAAG AGGAGTAAGA AAGGCTTTGT TTCGGCCAGC
 ACTTCCGACA CTGACTCTGA AAACTCTGGG AAAGCTGCCC CGCAGATTTG
 A*

>DL;Onmy-UBA*0103
Onmy-UBA*0103  708 bases  
 ATGAAGGGTA TTATCTTGCT GGTGCTGGGA ATAGGCCTTC TTCATACAGC
 ATCTGCTGCG ACTCACTCCC TGAAGTATTT CTACACCGCA TCTTCTGAAG
 TTCCCAACTT CCCAGAGTTC GTGGTTGTGG CGATGGTGGA TGGTGCTCAG
 ATGGTTCACT ATGACAGCAA CAGCCAGAGA GCGGTGCCCA AACAGGACTG
 GATGAACAGG GCAGCAGAAA CACTGCCACA GTACTGGGAG AGTCAGACAG
 GGATTTTCAA GGGTGCCCAG CAGACTTTCA AAGCCAACAT CGATATTGTA
 AAGCAGCGTT TTAACCAAAG TGGAGGTGTG CACATTGTCC AGAAGATGTA
 CGGTTGTGAG TGGGATGATG AGGCTGGAGT CACAGAGGGG TTTTATCAGT
 ATGGATATGA TGGAGAGGAT TTCATAGCAC TTGACCTGAA AACAACGAAA
 TGGATCGCCC CAACGCCACA GGCAGTCATC ACCAAACTCA AGTGGGACAG
 TAACACAGCT AACACTGAGT ACTGGAACAA CTACCTGACC CGGACCTGCA
 TTGAGTGGCT GAAGAAGTAT GTGGACTATG GGAAGAGCAC TCTGATGAGG
 ACAGTCCCTC CCTCAGTGTC TCTGCTCCAG AAGGCCCCCT CCTCTCCAGT
 GACCTGCCAC GCGACAGGTT TCTACCCCAG GGATGTCATG GTGTTCTGGC
 AGAAAGAA*

>DL;Onmy-UBA*0104
Onmy-UBA*0104  708 bases  
 ATGAAGGGTA TTATCTTGCT GGTGCTGGGA ATAGGCCTTC TTCATACAGC
 ATCTGCTGCG ACTCACTCCC TGAAGTATTT CTACACCGCA TCTTCTGAAG
 TTCCCAACTT CCCAGAGTTC GTGGTTGTGG CGATGGTGGA TGGTGCTAAG
 ATGGTTCACT ATGACAGCAA CAGCCAGAGA GCGGTGCCCA AACAGGACTG
 GATGAACAGG GCAGCAGAAA CACTGCCACA GTACTGGGAG AGTCAGACAG
 GGATTTTCAA GGGTGCCCAG CAGACTTTCA AAGCCAACAT CGATATTGTA
 AAGCAGCGTT TTAACCAAAG TGGAGGTGTG CACATTGTCC AGAAGATGTA
 CGGTTGTGAG TGGGATGATG AGGCTGGAGT CACAGAGGGG TTTTATCAGT
 ATGGATATGA TGGAGAGGAT TTCATAGCAC TTGACCTGAA AACAACGAAA
 TGGATCGCCC CAACGCCACA GGCAGTCATC ACCAAACTCA AGTGGGACAG
 TAACACAGCT AACACTGAGT ACTGGAACAA CTACCTGACC CAGACCTGCA
 TTGAGTGGCT GAAGAAGTAT GTGGACTATG GGAAGAGCAC TCTGATGAGG
 ACAGTCCCTC CCTCAGTGTC TCTGCTCCAG AAGGCCCCCT CATCACCAGT
 GACCTGCCAC GCGACAGGTT TCTACCCCAG GGATGTCATG GTGTTCTGGC
 AGAAAGAA*

>DL;Onmy-UBA*0201
Onmy-UBA*0201  1065 bases  
 ATGAAGTCTT TCATCATTTT GCTCCTGGGA ATTAATGCGG CATCTGCAGT
 AACCCACTCT CTGAAGTATT TCTACACTGG AAGTACTGGC ATTGAGGGGT
 TCCCACAGTT TGTTGCTGTG GGCATCGTAA ATGGAATGCA GATTGATTAC
 TTTGATGGTG TGTCTGAGAA GAATGTTCTG AAGCAGTCTT GGATGGAGGG
 GGTACGTGAT GAAAAAATGA TCACAAACAC AAGAAAGGGC CATCAGCAAA
 CCTTTAAGGC CAGCGTCGAA ATTGTAATGC AACGTTTCAA CCAAACAACA
 GGAGTTCACA CATTCCAGCT GATGTATGGC TGTGAGCTGG GTGATGACGG
 CATCCCTCGA GGAGACTTTC AGCTTGGTTA TGATGGAGCA GATTTCCTCA
 GCCTGGACAA GAGCACTCTC ACCTGGACTG CTGCCAACCA GAAAGCTGTC
 ATCACCAAGC TTAAGTGGGA TGCTACCGGA GCTGAGGCTA ACTTTCAGAA
 GAATTATCTA GAAAACACAT GCATTGAGTG GCTTAAGAAG TATGTCAACT
 ACGGCAAAGA CACTTTGGAA AGGAAAGTCC GTCCCTCAGT GTCTCTGCTC
 CAGAAGACCC CCTCCTCTCC AGTGACCTGC CACGCGACAG GTTTCTACCC
 CAGTGGAGTC ATGGTGTTCT GGCAGAAAGA CGGACAAGAA CAGCATGGAG
 ATGTGGAGCA TGGAGAGATC CTCCAGAACG ATGACGGAAC CTTCCAGAAA
 AGCACCCACC TGACAGTGAC GCCTGAGGAG TGGAAGAACA ACAAGTATCA
 GTGTGTGGTT CAACTCGCGG GTATCGAGGA TGACATCACC AAGGTTCTGA
 TTGAGTCTGA GATCCAGACC AACTTTGGAA AGACCAACAG GGGTTCAAAT
 GACCCAATCA CTATTGGCCT CATCATTGGA GGGGTGATAG CTCTCCTGGT
 CATCATTGTT GTTGGGGTCG TCATTTGGAA GAAGAAAAAC AAGAAAGGCT
 TTGTTCCGGC CAGCACTTCC GACACGGACT CTGAAAACTC TGGGAAAGGT
 ATCCAGAAGA TTTGA*

>DL;Onmy-UBA*0202
Onmy-UBA*0202  1033 bases  
 TAATGCGGCA TCTGCAGTAA CCCACTCTCT GAAGTATTTC TACACTGGAA
 GTACTGGCAT TGAGGGGTTC CCACAGTTTG TTGCTGTGGG CATCGTAGAT
 GGAATGCAGA TTGACTACTT TGATAGTGTG TCTGAGAAGA ATGTTCTGAA
 GCAGTCTTGG ATGGAGGGGG TACGTGATGA AAAAATGATC ACAAACACAA
 GAAAGGGCCA TCAGCAAACC TTTAAGGCCA GCGTCGAAAT TGTAATGCAA
 CGTTTCAACC AAACAACAGG AGTTCACACA TTCCAGCTGA TGTATGGCTG
 TGAGCTGGGT GATGACGGCA TCACTCGAGG AGACTTTCAG CTTGGTTATG
 ATGGAGCAGA TTTCCTCAGC CTGGACAAGA GCACTCTCAC CTGGACTGCT
 GCCAACCAGA AAGCTGTCAT CACCAAGCTT AAGTGGGATG CTACCGGAGC
 TGAGGCTAAC TTTCAGAAGA ATTATCTAGA AAACACATGC ATTGAGTGGC
 TTAAGAAGTA TGTCAACTAC GGCAAAGACA CTTTGGAAAG GAAAGTCCGT
 CCCTCAGTGT CTCTGCTCCA GAAGACCCCC TCCTCTCCAG TGACCTGCCA
 CGCGACAGGT TTCTACCCCA GTGGAGTCAT GGTGTTCTGG CAGAAAGACG
 GACAAGAACA GCATGGAGAT GTGGAGCATG GAGAGATCCT CCAGAACGAT
 GACGGAACCT TCCAGAAAAG CACCCACCTG ACAGTGACGC CTGAGGAGTG
 GAAGAACAAC AAGTATCAGT GTGTGGTTCA ACTCGCGGGT ATCGAGGATG
 ACATCACCAA GGTTCTGATT GAGTCTGAGA TCCAGACCAA CTTTGGAAAG
 ACCAACAGGG GTTCAAATGA CCCAATCACT ATTGGCCTCA TCATTGGAGG
 GGTGATAGCT CTCCTGGTCA TCATTGTTGT TGGGGTCGTC ATTTGGAAGA
 AGAAAAACAA GAAAGGCTTT GTTCCGGCCA GCACTTCCGA CACGGACTCT
 GAAAACTCTG GGAAAGGTAT CCAGAAGATT TGA*

>DL;Onmy-UBA*0301
Onmy-UBA*0301  1092 bases  
 ATGAAGGGTA TTATCTTGCT GGTGCTGGGA ATAGGCCTTC TTCATACAGC
 ATCTGCTGTG ACTCACTCCC TGAAGTATTT CTACACCGCA TCTTCTGAAG
 TTCCCAACTT CCCAGAGTTC GTGGTTGTGG GGATGGTGGA TGGTGTTCAG
 ATGGTTCACT ATGACAGCAA CAGCCAAAGA ATGGTGCCCA GACAGGACTG
 GATGAACAAG GCAGCAGAAA CACTGCCACA GTACTGGGAG AGTCAGACAG
 GGATTCTCAA GGGTACCCAG CAGACTTACA AAGCCAGCAT CGATATTGTA
 AAGCAGCGTT TTAACCAAAG TGGAGGAGTT CACACCGTCC AGCTTATGTA
 TGGCTGTGAG CTGGGTGATG ACGGCATCAC TCGAGGAGAC TTTCAGTATG
 GTTATGATGG AGCAGATTTC CTCAGCCTGG ACAAGAGCAC TCTCACCTGG
 ACTGCTGCCA ACCAGAAAGC TGTCATCACC AAGCTTAAGT TGGATGCTAC
 CGGAGCTGAG GCTAACTTTC AGAAGAATTA TCTAGAAAAC ACATGCATTG
 AGTGGCTTAA GAAGTATGTC AACTACGGCA AAGACACTTT GGAAAGGAAA
 GTCCGTCCCT CAGTGTCTCT GCTCCAGAAG ACCCCCTCCT CTCCAGTGAC
 CTGCCACGCG ACAGGTTTCT ACCCCAGTGG AGTCATGGTG TTCTGGCAGA
 AAGACGGACA AGAACAGCAT GGAGATGTGG AGCATGGAGA GATCCTCCAG
 AACGATGACG GAACCTTCCA GAAAAGCACC CACCTGACAG TGACGCCTGA
 GGAGTGGAAG AACAACAAGT ATCAGTGTGT GGTTCAACTC GCGGGTATCG
 AGGATGACAT CACCAAGGTT CTGATTGAGT CTGAGATCCA GACCAACTTT
 GGAAAGACCA ACAGGGGTTC AAATGACCCA AACACTATTG GCCTCATCAT
 TGGAGGGGTG ATAGCTCTCC TGGTCATCAT TGCTGTTGTT GGGGTCGTCA
 TTTGGAAGAA GAAAAACAAG AAAGGCTTTG TTCCGGCCAG CACTTCCGAC
 ACGGACTCTG AAAACTCTGG GAAAGGTATC CAGAAGATTT GA*

>DL;Onmy-UBA*040101
Onmy-UBA*040101  1087 bases  
 GAAGGGTATT ATCTTGCTGG TGCTGGGAAT AGGCCTTCTT CATACAGCAT
 CTGCTGTGAC TCACTCCCTG AAGTATTTCT ACACCGCATC TTCTGAAGTT
 CCCAACTTCC CAGAGTTCGT GGTTGTGGGG ATGGTGGATG GTGCTCAGAT
 GGTTCACTAT GACAGCAACA GCCAAAGAAT GGTGCCCAAA CAGGACTGGA
 TGAACAAGGC AGCAGAAACA CTGCCACAGT ACTGGGAGAG TCAGACAGGG
 AATTGCAAGG GTCAACAGCA GACTTTCAAA GCCAACATCG ATATTGTAAA
 TCAGCGTTTT AACCAAAGTG GAGGAGTTCA CACATTCCAG CTGATGTATG
 GCTGTGAGCT GGGTGATGAC GGCATCACTC GAGGAGACTT TCAGCTTGGT
 TATGATGGAG CAGATTTCCT CAGCCTGGAC AAGAGCACTC TCACCTGGAC
 TGCTGCCAAC CAGAAAGCTG TCATCACCAA GCTTAAGTGG GATGCTACCG
 GAGCTGAGGC TAACTTTCAG AAGAATTATC TAGAAAACAC ATGCATTGAG
 TGGCTTAAGA AGTATGTCAA CTACGGCAAA GACACTTTGG AAAGGAAAGT
 CCGTCCCTCA GTGTCTCTGC TCCAGAAGAC CCCCTCCTCT CCAGTGACCT
 GCCACGCGAC AGGTTTCTAC CCCAGTGGAG TCATGGTGTT CTGGCAGAAA
 GACGGACAAG AACAGCATGG AGATGTGGAG CATGGAGAGA TCCTCCAGAA
 CGATGACGGA ACCTTCCAGA AAAGCACCCA CCTGACAGTG ACGCCTGAGG
 AGTGGAAGAA CAACAAGTAT CAGTGTGTGG TTCAACTCGC GGGTATCGAG
 GATGACATCA CCAAGGTTCT GATTGAGTCT GAGATCCAGA CCAACTTTGG
 AAAGACCAAC AGGGGTTCAA ATGACCCAAT CACTATTGGC CTCATCATTG
 GAGGGGTGAT AGCTCTCCTG GTCATCATTG TTGTTGGGGT CGTCATTTGG
 AAGAAGAAAA ACAAGAAAGG CTTTGTTCCG GCCAGCACTT CCGACACGGA
 CTCTGAAAAC TCTGGGAAAG GTATCCAGAA GATTTGA*

>DL;Onmy-UBA*040102
Onmy-UBA*040102  1089 bases  
 ATGAAGGGTA TTATCTTGCT GGTGCTGGGA ATAGGCCTTC TTCATACAGC
 ATCTGCTGTG ACTCACTCCC TGAAGTATTT CTACACCGCA TCTTCTGAAG
 TTCCCAACTT CCCAGAGTTC GTGGTTGTGG GGATGGTGGA TGGTGCTCAG
 ATGGTTCACT ATGACAGCAA CAGCCAAAGA ATGGTGCCCA AACAGGACTG
 GATGAACAAG GCAGCAGAAA CACTGCCACA GTACTGGGAG AGTCAGACAG
 GGAATTGCAA GGGTCAACAG CAGACTTTCA AAGCCAACAT CGATATTGTA
 AATCAGCGTT TTAACCAAAG TGGAGGAGTT CACACATTCC AGCTGATGTA
 TGGCTGTGAG CTGGGTGATG ACGGCATCAC TCGAGGAGAC TTTCAGCTTG
 GTTATGATGG AGCAGATTTC CTCAGCCTGG ACAAGAGCAC TCTCACCTGG
 ACTGCTGCCA ACCAGAAAGC TGTCATCACC AAGCTTAAGT GGGATGCTAC
 CGGAGCTGAG GCTAACTTTC AGAAGAATTA TCTAGAAAAC ACATGCATTG
 AGTGGCTTAA GAAGTATGTC AACTACGGCA AAGACACTTT GGAAAGGAAA
 GTCCGTCCCT CAGTGTCTCT GCTCCAGAAG ACCCCCTCCT CTCCAGTGAC
 CTGCCACGCG ACAGGTTTCT ACCCCAGTGG AGTCATGGTG TTCTGGCAGA
 AAGACGGGCA AGAACAGCAT GGAGATGTGG AGCATGGAGA GATCCTCCAG
 AACGATGACG GAACCTTCCA GAAAAGCACC CACCTGACAG TGACGCCTGA
 GGAGTGGAAG AACAACAAGT ATCAGTGTGT GGTTCAACTC GCGGGTATCG
 AGGATGACAT CACCAAGGTT CTGATTGAGT CTGAGATCCA GACCAACTTT
 GGAAAGACCA ACAGGGGTTC AAATGACCCA ATCACTATTG GCCTCATCAT
 TGGAGGGGTG ATAGCTCTCC TGGTCATCAT TGTTGTTGGG GTCGTCATTT
 GGAAGAAGAA AAACAAGAAA GGCTTTGTTC CGGCCAGCAC TTCCGACACG
 GACTCTGAAA ACTCTGGGAA AGGTATCCAG AAGATTTGA*

>DL;Onmy-UBA*0402
Onmy-UBA*0402  705 bases  
 ATGAAGGGTA TTATCTTGCT GGTGCTGGGA ATAGGCCTTC TTCATACAGC
 ATCTGCTGTG ACTCACTCCC TGAAGTATTT CTACACCGCA TCTTCTGAAG
 TTCCCAACTT CCCAGAGTTC GTGGTTGTGG GGATGGTGGA TGGTGCTCAG
 ATGGTTCACT ATGACAGCAA CAGCCAAAGA ATGGTGCCCA AACAGGACTG
 GATGAACAAG GCAGCAGAAA CACTGCCACA GTACTGGGAG AGTCAGACAG
 GGAATTGCAA GGGTCAACAG CAGACTTTCA AAGCCGACAT CGATATTGTA
 AATCAGCGTT TTAACCAAAG TGGAGGAGTT CACACATTCC AGCTGATGTA
 TGGCTGTGAG CTGGGTGATG ACGGCATCAC TCGAGGAGAC TTTCAGCTTG
 GTTATGATGG AGCAGATTTC CTCAGCCTGG ACAAGAGCAC TCTCACCTGG
 ACTGCTGCCA ACCAGAAAGC TGTCATCACC AAGCTTAAGT GGGATGCTAC
 CGGAGCTGAG GCTAACTTTC AGAAGAATTA TCTAGAAAAC ACATGCATTG
 AGTGGCTTAA GAAGTATGTC AACTACGGCA AAGACACTTT GGAAAGGAAA
 GTCCGTCCCT CAGTGTCTCT GCTCCAGAAG ACCCCCTCCT CTCCAGTGAC
 CTGCCACGCG ACAGGTTTCT ACCCCAGTGG AGTCATGGTG TTCTGGCAGA
 AAGAA*

>DL;Onmy-UBA*0501
Onmy-UBA*0501  1051 bases  
 AGGCCTTCTC CATACTGCAT CTGCTGCTAC GCATTCACTG CGTTATGTGT
 ACACTGCAAC TTCCGGAGTA CCAGACTTCC CAGAGTTTGT CAGTCTGGGT
 ATTGTGGATG GAATGCAGAT AGATTACTAT GACAGTAACA CCAAGAGAGT
 AGTACCCAAG CAGGACTGGA TGGCCAAGAC TGAGGGGTCT GACTACTGGG
 AGAGACAGAC TCAGAACTCC ATTGGTGACG AGCAGACCTT CAAAGCCAAC
 ATTGATGTTG CCAAGCAGCG CTTCAATCAG ACTGGAGGAG TTCACACATT
 CCAGCTGATG TATGGCTGTG AGCTGGGTGA TGACGGCATC ACTCGAGGAG
 ACTTTCAGCT TGGTTATGAT GGAGCAGATT TCCTCAGCCT GGACAAGAGC
 ACTCTCACCT GGACTGCTGC CAACCAGAAA GCTGTCATCA CCAAGCTTAA
 GTGGGATGCT ACCGGAGCTG AGGCTAACTT TCAGAAGAAT TATCTAGAAA
 ACACATGCAT TGAGTGGCTT AAGAAGTATG TCAACTACGG CAAAGACACT
 TTGGAAAGGA AAGTCCGTCC CTCAGTGTCT CTGCTCCAGA AGACCCCCTC
 CTCTCCAGTG ACCTGCCACG CGACAGGTTT CTACCCCAGT GGAGTCATGG
 TGTTCTGGCA GAAAGACGGA CAAGAACAGC ATGGAGATGT GGAGCATGGA
 GAGATCCTCC AGAACGATGA CGGAACCTTC CAGAAAAGCA CCCACCTGAC
 AGTGACGCCT GAGGAGTGGA AGAACAACAA GTATCAGTGT GTGGTTCAAC
 TCGCGGGTAT CGAGGATGAC ATCACCAAGG TTCTGATTGA GTCTGAGATC
 CAGACCAACT TTGGAAAGAC CAACAGGGGT TCAAATGACC CAATCACTAT
 TGGCCTCATC ATTGGAGGGG TGATAGCTCT CCTGGTCATC ATTGTTGTTG
 GGGTCGTCAT TTGGAAGAAG AAAAACAAGA AAGGCTTTGT TCCGGCCAGC
 ACTTCCGACA CGGACTCTGA AAACTCTGGG AAAGGTATCC AGAAGATTTG
 A*

>DL;Onmy-UBA*0502
Onmy-UBA*0502  699 bases  
 ATGAAGGGTA TTATCTTGCT GTTGCTGGGA ATAGGCCTTC TCCATACTGC
 ATCTGCTGCT ACGCATTCAC TGCGTTATGT GTACACTGCA ACTTCCGGAG
 TACCAGACTT CCCAGAGTTT GTCAGTCTGG GTATTGTGGA TGGAATGCAG
 ATAGATTACT ATGACAGTAA CACCAAGAGA GTAGTACCCA AGCAGGACTG
 GATGGCCAAG ACTGAGGGGT CTGACTACTG GGAGAGACAG ACTCAGAACT
 CCATTGGTGA CGAGCAGACC TTCAAAGCCA ACATTGATGT TGCCAAGCAG
 CGCTTCAATC AGACTGGAGG AGTTCACACA TTCCAGCTGA TGTATGGCTG
 TGAGCTGGGT GATGACAGCA TCACTCGAGG AGACTTTCAG CTTGGTTATG
 ATGGAGCAGA TTTCCTCAGC CTGGACAAGA GCACTCTCAC CTGGACTGCT
 GCCAACCAGA AAGCTGTCAT CACCAAGCTT AAGTGGGATG CTACCGGAGC
 TGAGGCTAAC TTTCAGAAGA ATTATCTAGA AAACACATGC ATTGAGTGGC
 TTAAGAAGTA TGTCAACTAC GGCAAAGACA CTTTGGAAAG GAAAGTCCGT
 CCCTCAGTGT CTCTGCTCCA GAAGACCCCC TCCTCTCCAG TGACCTGCCA
 CGCGACAGGT TTCTACCCCA GTGGAGTCAT GGTGTTCTGG CAGAAAGAA*

>DL;Onmy-UBA*0601
Onmy-UBA*0601  1084 bases  
 GAAGGGTATT ATCTTGCTGG TGCTGGGAAT AGGCCTTCTT CATACAGCAT
 CTGCTGTGAC TCACTCCCTG AAGTATTTCT ACACCGCATC TTCTGAAGTT
 CCCAACTTCC CAGAGTTCGT GGTTGTGGCG ATGGTGGATG GTGTTCAGAT
 GGTTCACTAT GACAGCAACA GCCAGAGAGC GGTGCCCAAA CAGGACTGGG
 TAAACAAGGC AGCAGACCCA CAGTACTGGG AGAGGAACAC TGGGATTTTC
 AAGGGTAGCC AGCAGACTTT CAAAGCCAAC ATCGATATTG CAAAGCAGCG
 TTTTAACCAA AGTGGAGGAG TTCACACCGT CCAGCTTATG TATGGCTGTG
 AGCTGGGTGA TGACGGCATC ACTCGAGGAG ACTTTCAGTA TGGTTATGAT
 GGAGCAGATT TCCTCAGCCT GGACAAGAGC ACTCTCACCT GGACTGCTGC
 CAACCAGAAA GCTGTCATCA CCAAGCTTAA GTGGGATGCT ACCGGAGCTG
 ATGCTAACTT TCAGAAGAAT TATCTAGAAA ACACATGCAT TGAGTGGCTT
 AAGAAGTATG TCAACTACGG CAAAGACACT TTGGAAAGGA AAGTCCGTCC
 CTCAGTGTCT CTGCTCCAGA AGACCCCCTC CTCTCCAGTG ACCTGCCACG
 CGACAGGTTT CTACCCCAGT GGAGTCATGG TGTTCTGGCA GAAAGACGGA
 CAAGAACAGC ATGGAGATGT GGAGCATGGA GAGATCCTCC AGAACGATGA
 CGGAACCTTC CAGAAAAGCA CCCACCTGAC AGTGACGCCT GAGGAGTGGA
 AGAACAACAA GTATCAGTGT GTGGTTCAAC TCGCGGGTAT CGAGGATGAC
 ATCACCAAGG TTCTGATTGA GTCTGAGATC CAGACCAACT TTGGAAAGAC
 CAACAGGGGT TCAAATGACC CAAACACTAT TGGCCTCATC ATTGGAGGGG
 TGATAGCTCT CCTGGTCATC ATTGCTGTTG TTGGGGTCGT CATTTGGAAG
 AAGAAAAACA AGAAAGGCTT TGTTCCGGCC AGCACTTCCG ACACGGACTC
 TGAAAACTCT GGGAAAGGTA TCCAGAAGAT TTGA*

>DL;Onmy-UBA*0701
Onmy-UBA*0701  1021 bases  
 AGTCCTTCTT AATACAGTAT CTGCTGCAAC CAATACACTG CAGTATTTCT
 ACACGGCCAC TTCTGGTATA GATAACTTCC CAGAGTTTGT GACTGTGGGA
 ATCGTCAATG GCCATCAGAT TGACCACTAC GACAGTATCA CCAAGAGAGC
 AATCCAGAAA GCTGAGTGGA TCAGTGGGGC AGTTGACCCT GACTATTGGA
 AGAGTAACAC CCAAATCTAT GCTGCTGCAG AGACAGTTTT CTTAAACAAC
 ATTAAAATTG TGAAATCCCG CTTCAATCAA ACTGGAGGTG TGCACGTTTT
 CCAGAAAATG TACGGTTGTG AGTGGGATGA TGAGGCTGGA GTCACAGAGG
 GGTTTAATCA GTATGGATAT GATGGAGAGG ATTTCATAGC ATTTGACCTG
 AAAACAACGA AATGGATCGC CCCAACGCCA CAGGCAGTCA TCACCAAACT
 CAAGTGGGAC AGTAACACAG CTAACACTGA GAACTGGAAC AACTACCTGA
 CCCAGACGTG CATTGAGTGG CTGAAGAAGT ATGTGGACTA TGGGAAGAGC
 ACTCTGATGA GGACAGTCCC TCCGTCAGTG TCTCTGCTCC AGAAGGCCCC
 CTCCTCTCCA GTGACCTGCC ACGCGACAGG TTTCTACCCC AGGGATGTCA
 TGGTGTCCTG GCAGAAAGAC GGACAAGATC ACCATGAGGA TGTGGAGTAT
 GGAGAGACTC TCCCCAACGA TGATGGAACC TTCCAAAAAA GCTCCCACCT
 GACAGTGACG CCTGAGGACA GGAAGAACAG CAAGTATCAG TGTGTGGTTC
 AAGTCAAGGG TATCAAGAAG GACTTCATCG AGGTTCTGAC TGACCCGGAT
 GCCGCCAACG TTGTCCCCAT CATTGGAGGG GTGGTAGCTC TCCTCCTGGT
 CGTCGTTGCT GTTGTTGTTG GGGTCGTCAT TTGGAGGAAG AGGAGCAAGA
 AAGGCTTTGT TCCGGCCAGC ACTTCCGACA CTGACTCTGA AAACTCTGGG
 AAAGCTGCCC CGCAGATTTG A*

>DL;Onmy-UBA*0801
Onmy-UBA*0801  1027 bases  
 AGGCCTTCTT CATACAACAT CTGCTGCCAT CCACACTCTG AAGAACTTCT
 ATACAGCAGC CTCAGGTGAT ATTGACTTCC CAGAGTTCAT CATTGTTGGT
 CTGGTAGACA ATACACCATA CCTATACTTT GACAGCAACA CCAAGACTGC
 AGTCCCCAAG ACTGAGTGGA TGAAGAAGAA TGTGGGAGCA GACTACTGGG
 ACAGCATGAC TCAGATTGGT ATTGGTTCCC ATCAAACCTT CAAAAACAAC
 ATTCAAGTAG CAAAGGATCG CTTCAACCAG TCCAAGTCCA CAGGTGTGCA
 CGTTTTCCAG AAAATGTACG GTTGTGAGTG GGATGATGAG GCTGGAGTCA
 CAGAGGGGTT TAATCAGTAT GGATATGATG GAGAGGATTT CATAGCATTT
 GACCTGAAAA CAACGAAATG GATCGCCCCA ACGCCACAGG CAGTCATCAC
 CAAACTCAAG TGGGACAGTA ACACAGCTAA CACTGAGAAC TGGAACAACT
 ACCTGACCCA GACGTGCATT GAGTGGCTGA AGAAGTATGT GGACTATGGG
 AAGAGCACTC TGATGAGGAC AGTCCCTCCG TCAGTGTCTC TGCTCCAGAA
 GGCCCCCTCC TCTCCAGTGA CCTGCCACGC GACAGGTTTC TACCCCAGGG
 ATGTCATGGT GTCCTGGCAG AAAGACGGAC AAGATCACCA TGAGGATGTG
 GAGTATGGAG AGACTCTCCC CAACGATGAT GGAACCTTCC AAAAAAGCTC
 CCACCTGACA GTGACGCCTG AGGACAGGAA GAACAGCAAG TATCAGTGTG
 TGGTTCAAGT CAAGGGTATC AAGAAGGACT TCATCGAGGT TCTGACTGAC
 CCGGATGCCG CCAACGTTGT CCCCATCATT GGAGGGGTGG TAGCTCTCCT
 CCTGGTCGTC GTTGCTGTTG TTGTTGGGGT CGTCATTTGG AGGAAGAGGA
 GCAAGAAAGG CTTTGTTCCG GCCAGCACTT CCGACACTGA CTCTGAAAAC
 TCTGGGAAAG CTGCCCCGCA GATTTGA*

>DL;Onmy-UBA*0901
Onmy-UBA*0901  1018 bases  
 AGGCCTTCTT CATATAGCGT CTGCTGTGAC CCATTCCCTG CGCTACTTCT
 ACACTGCCAC CACAGGAATC CCAGACTTCC CTGAGTTTGT GGATGTGGGG
 GTGGTGAACG GTAAGGTCAT CAGCTACTAT GATAGCATCA CAAAGAGGAA
 GGTCCCCAAG CAGAGCTGGA TGGAAGAGAA TCTCAACCAG CAGTACTGGA
 ATCAAGGCAC AGATCAATTG AAGGGAGCAG AGCAAACCTT CAAAGCCAAC
 ATTCAAATAG TACAGACACG TTTCAATCAA ACTGGAGGTG TGCACACTTT
 CCAGAACATG TATGGTTGTG AATGGGATGA TGACACTGGA GCCACAGAGG
 GTTTTTTTCA GTATGGATAT GATGGAGAGG ATTTCCTGGC ATTGGACCTG
 AAGACAAAGA AATGGATCGC TCCAACACCA CAGGCCGTCA TCACCAAACA
 CAAGTGGGAC AGTAACACAG CTAATGAGGA GCGGAGAAAA CATTACCTCA
 CCCAGGAGTG CATTGAGTGG CTGAAGAAGT ATCTGGACTA TGGGAAGAGC
 ACTCTAATGA GGACAGTCCC TCCCTCTGTG TTTCTGCTCC AGAAGACCCC
 CTCCTCTCCA GTGACCTGCC ACGCGACAGG TTTCTACCCC AGTGATGTCA
 TGGTGTCCTG GCAGAAAGAC GGACAAGATC ACCATGAAGA TGTGGAGTAT
 GGAGAGACTC TCCCCAACGA TGACGGAACC TTCCAGAAAA GCATCCACCT
 GACAATGACA CCTGAGGACA GGAAGAACAA CAAGTATCAG TGTGTGGTTC
 AAGTCAAGGG TATCAAGGAG GACTTCATCG GGGTTCCGCC TGACCAGGAT
 GCCGCCAACG TTGTCCCCAT CATTGGAGGG GTGGTAGCTC TCCTCCTGGT
 CGTCGTTGTT GTTGTTGTTG GGGTCGTCAT TTGGAAGAAG AGGAGCAAGA
 AAGGCTTTGT TCCGGCCAGC ACTTCCGACA CTGACTCTGA CAACTCTGGA
 GGTGTCAAGA AGATTTGA*

>DL;Onmy-UBA*0902
Onmy-UBA*0902  702 bases  
 ATGAAGGGTA TTATCTTGCT GGTGCTGGGA ATAGGCCTTC TTCATATAGC
 GTCTGCTGTG ACCCATTCCC TGCGCTACTC CTACACTGCC ACCACAGGAA
 TCCCAGACTT CCCTGAGTTT GTGGATGTGG GGGTGGCGAA CGGTAAGGTC
 ATCAGCTACT ATGATAGCAT CACAAAGAGG AAGGTCCCCA AGCAGAGCTG
 GATGGAAGAG AATCTCAACC AGCAGTACTG GAATCAAGGC ACAGATCAAT
 TGAAGGGAGC AGAGCAAACC TTCAAAGCCA ACATTCAAAT AGTACAGACA
 CGTTTCAATC AAACTGGAGG TGTGCACACT TTCCAGAACA TGTATGGTTG
 TGAATGGGAT GATGACACTG GAGCCACAGA GGGTTTTTTT CAGTATGGAT
 ATGATGGAGA GGATTTCCTG GCATTGGACC TGAAGACAAA GAAATGGATC
 GCTCCAACAC CACAGGCCGT CATCACCAAA CACAAGTGGG ACAGTAACAC
 AGCTAATGAG GAGCGGAGAA AACATTACCT CACCCAGGAG TGCATTGAGT
 GGCTGAAGAA GTATCTGGAC TATGGGAAGA GCACTCTAAT GAGGACAGTC
 CCTCCCTCTG TGTTTCTGCT CCAGAAGACC CCCTCCTCTC CAGTGACCTG
 CCACGCGACA GGTTTCTACC CCAGTGATGT CATGGTGTTC TGGCAGAAAG
 AA*

>DL;Onmy-UBA*1001
Onmy-UBA*1001  1053 bases  
 ATGAAGGGTA TTATCTTGCT GGTGCTGGGA ATAGGCCTTC TTCATACAGC
 ATCTGCTGCG ACTCACTCCC TGAAGTATTT CTACACCGGA TCTTCTGAAG
 TTCCCAACTT CCCAGAGTTC GTGGCTGTGG GGATGGTGGA TGGTGTTCAG
 ATGTTTCACT ATGACAGCAA CAGCCAGAGA GCGGTGCCCA AACAGGACTG
 GGTAAACAAG GCAGCAGACC CACAGTACTG GGAGAGGAAC ACTGGGAATT
 GCAAGGGTAG CCAGCAGACT TTCAAAGCCA GCATCGATAT TGTAAAGCAG
 CGTTTTAACC AAAGTGGAGG TGTGCACGTT TTCCAGAATA TGTACGGTTG
 TGAGTGGGAT GATGAGGCTG GAGCCACAGA GGGGTTTTAT CAGTTTGGAT
 ATGATGGAGA GGATTTCATA GCATTTGACC TGAAAACAAC TAAATGGATC
 GCTCCAACGC CACAGGCAGT CATCACCAAA CAAAAGTGGG ACAGTGACAC
 AGCTGACAAT AAGTACAGAA AAAACTACTG CACCCAGGAG TGCATTGATT
 GGCTGAAGAA GTATGTGGAC TATGGGAAGA GCACTCTGAT GAGGACAGTC
 CGTCCCTCAG TGTCTCTGCT CCAGAAGGCC CCCTCCTCTC CAGTGACATG
 CCACGCGACA GGTTTCTACC CCAGTGATGT CATGGTGTCC TGGCAGAAAG
 ACGGACAAGA TCACCATGAG GATGTGGAGT ATGGAGAGAC TCTCCCCAAC
 GATGATGGAA CCTTCCAGAA AAGCTCCCAC CTGACAGTGA CGCCTGAGGA
 CAGGAAGAAA AACAAGTATC AGTGTGTGGT TCAAGTCAAG GGTATCAAGG
 AGGACTTCAT CAAGGTTCTG CCTGACCCGG ATGCCGCCAA CGTTGTCCCC
 ATCATTGTAG GGGTGGTAGC TCTCCTCCTG GTCATTGTTG CTGTTGTTGT
 TGGGGTCGTC ATTTGGAGGA AGAGGAGTAA GAAAGGCTTT GTTCCGGCCA
 GCACTTCCGA CACTGACTCT GACAACTCTG GGAGAGCTGT CCCGCAGATT
 TGA*

>DL;Onmy-UBA*1101
Onmy-UBA*1101  1057 bases  
 GAAGGGTATT ATCTTGCTGG TGCTGGGAAT AGGCCTTCTT CATACAGCAT
 CTGCTGCGAC TCACTCCCTG AAGTATTTCT ACACCGCATC TTCTGAAGTT
 CCCAACTTCC CAGAGTTCGT GGTTGTGGCG ATGGTGGATG GTGCTCAGAT
 GGTTCACTAT GACAGCAACA GCCAGAGAGC GGTGCCCAAA CAGGACTGGA
 TGAACAGGGC AGCAGAAACA CTGCCACAGT ACTGGGAGAG TCAGACAGGG
 ATTTTCAAGG GTGCCCAGCA GACTTTCAAA GCCAACATCG ATATTGTAAA
 GCAGCGTTTT AACCAAAGTG GAGGTGTGCA CGTTTTCCAG AATATGTACG
 GTTGTGAGTG GGATGATGAG GCTGGAGCCA CAGAGGGGTT TTATCAGTTT
 GGATATGATG GAGAGGATTT CATAGCTTTT GACCTGAAAA CAACTAAATG
 GATCGCTCCA ACGCCACAGG CAGTCATCAC CAAACAAAAG TGGGACAGTG
 ACACAGCTAA CAATGAGTAC CGAAAAAACT ACTTCACCCA GGAGTGCATT
 GATTGGCTGA AGAAGTATGT GGACTATGGG AAGAGCACTC TGATGAGGAC
 AGTCCGTCCC TCAGTGTCTC TGCTCCAGAA GGCCCCCTCC TCTCCAGTGA
 CATGCCACGC GACAGGTTTC TACCCCAGTG ATGTCATGGT GTCCTGGCAG
 AAAGACGGAC AAGATCACCA TGAGGATGTG GAGTATGGAG AGACTCTCCC
 CAACGATGAT GGAACCTTCC AGAAAAGCTC CCACCTGACA GTGACGCCTG
 AGGACAGGAA GAACAACAAG TATCAGTGTG TGGTTCAAGT CAAGGGTATC
 AAGGAGGACT TCATCGAGGT TCTGCCTGAC CCGGATGCCG CCAACGTTGT
 CCCCATCATT GTAGGGGTGG TAGCTCTCCT CCTGGTCGTC GTTGCTGTTG
 TTGTTGGGGT CGTCATTTGG AGGAAGAGGA GTAAGAAAGG CTTTGTTCCG
 GCCAGCACTT CCGACACTGA CTCTGACAAC TCTGGGAGAG CTGTCCCGCA
 GATTTGA*

>DL;Onmy-UBA*1201
Onmy-UBA*1201  1057 bases  
 GAAGGGTATT ATCTTGCTGG TGCTGGGAAT AGGCCTTCTT CATACAGCAT
 CTGCTGTGAC TCACTCCCTG AAGTATTTCT ACACCGCATC TTCTGAAGTT
 CCCAACTTCC CAGAGTTCGT GGTTGTGGGG ATGGTGGATG GTGTTCAGAT
 GGTTCACTAT GACAGCAACA GCCAGAGAGC GGTGCCCAAA CAGGACTGGA
 TGAACAGGGC AGCAGAAACA CTGCCACAGT ACTGGGAGAG TCAGACAGGG
 AATTTCAAGG GTACCCAGCA GACTTACAAA GCCAACATCG ATATTGTAAA
 GCAGCGTTTT AACCAAAGTG GAGGTGTGCA CATTTTCCAG AGGATGTGCG
 GTTGTGAGTG GGATGATGAG GCTGGAGTCA CAGAGGGGTT TAATCAGTAT
 GGATATGATG GAGAGGATTT CATAGCACTT GACCTGAAAA CAACGAAATG
 GATCGCCCCA ACGCCACAGG CAGTCATCAC CAAACTCAAG TGGGACAGTA
 ACACAGCTAA CACTGAGTAC TGGAAAAACT ACCTGACCCA GACCTGCATT
 GAGTGGCTGA AGAAGTATGT GGACTATGGG AAGAGCACTC TGATGAGGAC
 AGTCCCTCCC TCAGTGTCTC TGCTCCAGAA GGCCCCCTCC TCTCCAGTGA
 CCTGCCACGC GACAGGTTTC TACCCCAGGG ATGTCATGGT GTCCTGGCAG
 AAAGACGGAC AAGATCACCA TGAGGATGTG GAGTATGGAG AGACTCTCCC
 CAACGATGAT GGAACCTTCC AAAAAAGCTC CCACCTGACA GTGACGCCTG
 AGGACAGGAA GAACAGCAAG TATCAGTGTG TGGTTCAAGT CAAGGGTATC
 AAGAAGGACT TCATCGAGGT TCTGACTGAC CCGGATGCCG CCAACGTTGT
 CCCCATCATT GGAGGGGTGG TAGCTCTCCT CCTGGTCGTC GTTGCTGTTG
 TTGTTGGGGT CGTCATTTGG AGGAAGAGGA GCAAGAAAGG CTTTGTTCCG
 GCCAGCACTT CCGACACTGA CTCTGAAAAC TCTGGGAAAG CTGCCCCGCA
 GATTTGA*

>DL;Onmy-UBA*1301
Onmy-UBA*1301  1059 bases  
 ATGAAGGGTA TTATCTTGCT GGTGCTGGGA ATAGGCCTTC TTCATACAGC
 ATCTGCTGTG ACTCACTCCC TGAAGTATTT CTACACCGGA TCTTCTGAAG
 TTCCCAACTT CCCAGAGTTC GTGGTTGTGG CGATGGTGGA TGGTGCTCAG
 ATGGTTCACT ATGACAGCAA CAGCCAGAGA GCGGTGCCCA AACAGGACTG
 GATGAACAGG GCAGCAGAAA CACTGCCACA GTACTGGGAG AGTCAGACAG
 GGATTTTCAA GGGTGACCAG CAGACTTTCA AAGCCAACAT CGATACTGCA
 AAGCAGCGTT TTAACCAAAG TGGAGGTGTG CACATTGTCC AGATGATGTG
 CGGTTGTGAG TGGGATGATG AGACTGGAGT CACAGAGGGG TTTAATCAGC
 ATGGATATGA TGGAGAGGAT TTCATAGCAT TTGACCTGAA AACAACTAAA
 TGGATCGCCC CAACGCCACA GGCAGTCATC ACCAAACACA AGTGGGACAG
 TAACACAGCT AACAATGAGT ACTGGAAAAA CTACATCACC CAGGAGTGCA
 TTGATTGGCT GAAGAAGTAT GTGGACTATG GGAAGAACAC TCTGATGAGG
 ACAGTCCCTC CGTCAGTGTC TCTGTTCCAG AAGACCCCCT CCTCTCCAGT
 GACCTGCCAC GCGACAGGTT TCTACCCCAG TGATGTCATG GTGTCCTGGC
 AGAAAGACGG ACAAGATCAC CATGAGGATG TGGAGTATGG AGAGACTCTC
 CCCAACGATG ATGGAACCTT CCAGAAAAGC TCCCACCTGA CAGTGACGCC
 TGAGGACAGG AAGAACAGCA AGTATCAGTG TGTGGTTCAA GTCAAGGGTA
 TCAAGGAGGA CTTCATCGAG GTTCTGCCTG TCCCGGATGC CGCCAACGTT
 GTCCCCATCA TTGGAGGGGT GGTAGCTCTC CTCCTGGTCG TCGTTGCTGT
 TGTTGTTGGG GTCGTCATTT GGAAGAAGAG GAGCAAGAAA GGCTTTGTTC
 CGGCCAGCAC TTCCGACACT GACTCTGAAA ACTCTGGGAA AGCTGCCCCG
 CAGATTTGA*

>DL;Onmy-UBA*1401
Onmy-UBA*1401  1051 bases  
 GAAGGGTATT ATCTTGCTGG TGCTGGGAAT AGGCCTTCTT CATACAGCAT
 CTGCTGTGAC TCACTCCCTG AAGTATTTCT ACACCGCATC TTCTGAAGTT
 CCCAACTTCC CAGAGTTCGT GGCTGTGGGG ATGGTGGATG GTGTTCAGAT
 GGTTCACTAT GACAGCAACA GCCAGAGAGC GGTGCCCAAA CAGGACTGGG
 TAAACAAGGC AGCAGACCCA CAGTACTGGG AGAGGAACAC TGGGAATTTC
 AAGGGTTCCC AGCAGACTTT CAAAGCCAAC ATCGATATTG TAAAGCAGCG
 TTTTAACCAA AGTGGAGGTG TGCACATTTT CCAGATGATG TGCGGTTGTG
 AGTGGGATGA TGAGGCTGGA GTCACAGAGG GGTTTGATCA GTTTGGATAT
 GATGGAGAGG ATTTCATAGC ATTTGACCTG AAAACAACGA AATGGATCGC
 CCCAACGCCA CAGGCAGTCA TCACCAAACT CAAGTGGGAC AGTAACACAG
 CATACACTGA GAACTGGAAC AACTACCTGA CCCAGACGTG CATTGAGTGG
 CTGAAGAAGT ATGTGGACTA TGGGAAGAGC ACTCTGATGA GGACAGTCCC
 TCCGTCAGTG TCTCTGCTCC AGAAGGCCCC CTCCTCTCCA GTGACCTGCC
 ACGCGACAGG TTTCTACCCC AGGGATGTCA TGGTGTCCTG GCAGAAAGAC
 GGACAAGATC ACCATGAGGA TGTGGAGTAT GGAGAGACTC TCCCCAACGA
 TGATGGAACC TTCCAAAAAA GCTCCCACCT GACAGTGACG CCTGAGGACA
 GGAAGAACAG CAAGTATCAG TGTGTGGTTC AAGTCAAGGG TATCAAGAAG
 GACTTCATCG AGGTTCTGAC TGACCCGGAT GCCGCCAACG TTGTCCCCAT
 CATTGGAGGG GTGGTAGCTC TCCTCCTGGT CGTCGTTGCT GTTGTTGTTG
 GGGTCGTCAT TTGGAGGAAG AGGAGCAAGA AAGGCTTTGT TCCGGCCAGC
 ACTTCCGACA CTGACTCTGA AAACTCTGGG AAAGCTGCCC CGCAGATTTG
 A*

>DL;Onmy-UBA*150101
Onmy-UBA*150101  1074 bases  
 ATGAAGGGTA TTATCTTGCT GGTGCTGGGA ATAGGCCTTC TTCATACAGC
 ATCTGCTGTG ACTCACTCCC TGAAGTATTT CTACACCGCA TCTTCTGAAG
 TTCCCAACTT CCCAGAGTTC GTGGTTGTGG CGATGGTGGA TGGTGTTCAG
 ATGGTTCACT ATGACAGCAA CAGCCAGAGA GCGGTGCCCA AACAGGACTG
 GGTAAACAAG GCAGCAGACC CACAGTACTG GGAGAGGAAC ACTGGGATTT
 TCAAGGGTAG CCAGCAGACT TTCAAAGCCA ACATCGATAT TGCAAAGCAG
 CGTTTTAACC AAAGTGGAGG TGTGCACATT AACCAGAGGA TGTATGGTTG
 TGAGTGGAAT GATGAGACTG GTGCCACAGG GGGTTATAGT CAGGATGGAT
 ATGATGGAGA GGATTTCATA GCATTTGACC TGAAGACAAA GACATGGATC
 GCTCCAAAGC CACAGGCAGT CATCACCAAA CTCAAGTGGG ACAGTGACAT
 AGCTATGACT GAGCGGGATA AACATTACCT GACCCAGACC TGCATTGAGT
 GGCTGAAGAA GTATCTGGAC TATGGGAAGA GCACTCTGAT GACGACAGTC
 CCTCCCTCAG TTTCTCTGCT CCAGAAGACC CCCTCCTCTC CAGTGACCTG
 CCACGCGACA GGTTTCTACC CCAGTGGAGT CATGGTGTTC TGGCAGAAAG
 ACGGACAAGA TCAGCATGGA GATGTGGAGC ATGGAGAGAC TCTCCCCAAC
 GATGACGGAA CCTTCCAGAA AAGCACCCAC CTGACAGTGA CGCCTGAGGA
 GTGGAAGAAG AAACAGTATC AGTGTGTGGT TCAAGTCACT GGTATTAAGG
 AGGACTTCAT CAAGGTGTTG ACTGAGTCTG AGATCAAGAC CAACTGGAAT
 GACCCAGCCC CCAACATTGT CCTCATCATT GGAGTGGTGG TAGCTCTCCT
 CCTGGTCATC GTTGCTGTTG TTGGGGTCGT CATTTGGAAG AAGAAGAGCA
 AGAAAGGCTT TATTCAGGCC CAATCTTCCG ACACTGACTC TGACAACTCT
 GGGAGAGCTG CCCAGCAGAT TTGA*

>DL;Onmy-UBA*150102
Onmy-UBA*150102  1074 bases  
 ATGAAGGGTA TTATCTTGCT GGTGCTGGGA ATAGGCCTTC TTCATACAGC
 ATCTGCTGTG ACTCACTCCC TGAAGTATTT CTACACCGCA TCTTCTGAAG
 TTCCCAACTT CCCAGAGTTC GTGGTTGTGG CGATGGTGGA TGGTGTTCAG
 ATGGTTCACT ATGACAGCAA CAGCCAGAGA GCGGTGCCCA AACAGGACTG
 GGTAAACAAG GCAGCAGACC CACAGTACTG GGAGAGGAAC ACTGGGATTT
 TCAAGGGTAG CCAGCAGACT TTCAAAGCCA ACATCGATAT TGCAAAGCAG
 CGTTTTAACC AAAGTGGAGG TGTGCACATT AACCAGAGGA TGTATGGTTG
 TGAGTGGAAT GATGAGACTG GTGCCACAGG GGGTTATAGT CAGGATGGAT
 ATGATGGAGA GGATTTCATA GCATTTGACC TGAAGACAAA GACATGGATC
 GCTCCAAAGC CACAGGCAGT CATCACCAAA CTCAAGTGGG ACAGTGACAT
 AGCTATGACT GAGCGGGATA AACATTACCT GACCCAGACC TGCATTGAGT
 GGCTGAAGAA GTATCTGGAC TATGGGAAGA GCACTCTGAT GACGACAGTC
 CCTCCCTCAG TTTCTCTGCT CCAGAAGACC CCCTCCTCTC CAGTGACCTG
 CCACGCGACA GGTTTCTACC CCAGTGGAGT CATGGTGTTC TGGCAGAAAG
 ACGGACAAGA TCAGCATGGA GATGTGGAGC ATGGAGAGAC TCTCCCCAAC
 GATGACGGAA CCTTCCAGAA AAGCACCCAC CTGACAGTGA CGCCTGAGGA
 GTGGAAGAAG AAACAGTATC AGTGTGTGGT TCAAGTCACT GGTATTAAGG
 AGGACTTCAT CAAGGTGTTG ACTGAGTCTG AGATCAAGAC CAACTGGAAT
 GACCCAGCCC CCAACATTGT CCTCATCATT GGAGTGGTGG TAGCTCTCCT
 CCTGGTCATC GTTGCTGTTG TTGGGGTCGT CATTTGGAAG AAGAAGAGCA
 AGAAAGGCTT TATTCAGGCC CAATCTTCCG ACACTGACTC TGACAACTCT
 GGGAGAGCTG CCCAGCAGAT TTGA*

>DL;Onmy-UBA*1502
Onmy-UBA*1502  1074 bases  
 ATGAAGGGTA TTATCTTGCT GGTGCTGGGA ATAGGCCTTC TTCATACAGC
 ATCTGCTGTG ACTCACTCCC TGAAGTATTT CTACACCGCA TCTTCTGAAG
 TTCCCAACTT CCCAGAGTTC GTGGTTGTGG CGATGGTGGA TGGTGTTCAG
 ATGGTTCACT ATGACAGCAA CAGCCAGAGA GCGGTGCCCA AACAGGACTG
 GGTAAACAAG GCAGCAGACC CACAGTACTG GGAGAGGAAC ACTGGGATTT
 TCAAGGGTAG CCAGCAGACT TTCAAAGCCA ACATCGATAT TGCAAAGCAG
 CGTTTTAACC AAAGTGGAGG TGTGCACATT AACCAGAGGA TGTATGGTTG
 TGAGTGGAAT GATGAGACTG GTGCCACAGG GGGTTATAGT CAGGATGGAT
 ATGATGGAGA GGATTTCATA GCATTTGACC TGAAGACAAA GACATGGATC
 GCTCCAAAGC CACAGGCAGT CATCACCAAA TTCAAGTGGG ACAGTGACAT
 AGCTATGACT GAGCGGGATA AACATTACCT GACCCAGACC TGCATTGAGT
 GGCTGAAGAA GTATCTGGAC TATGGGAAGA GCACTCTGAT GACGACAGTC
 CCTCCCTCAG TTTCTCTGCT CCAGAAGACC CCCTCCTCTC CAGTGACCTG
 CCACGCGACA GGTTTCTACC CCAGTGGAGT CATGGTGTTC TGGCAGAAAG
 ACGGACAAGA TCAGCATGGA GATGTGGAGC ATGGAGAGAC TCTCCCCAAC
 GATGACGGAA CCTTCCAGAA AAGCACCCAC CTGACAGTGA CGCCTGAGGA
 GTGGAAGAAG AAACAGTATC AGTGTGTGGT TCAAGTCACT GGTATTAAGG
 AGGACTTCAT CAAGGTGTTG ACTGAGTCTG AGATCAAGAC CAACTGGAAT
 GACCCAGCCC CCAACATTGT CCTCATCATT GGAGTGGTGG TAGCTCTCCT
 CCTGGTCATC GTTGCTGTTG TTGGGGTCGT CATTTGGAAG AAGAAGAGCA
 AGAAAGGCTT TATTCAGGCC CAATCTTCCG ACACTGACTC TGACAACTCT
 GGGAGAGCTG CCCAGCAGAT TTGA*

>DL;Onmy-UBA*1601
Onmy-UBA*1601  1048 bases  
 AGGCCTTCTT CATACAGCAT CTGCTGCGAC TCACTCCCTG AAGTATTTCT
 ACACCGCATC TTCTGAAGTT CCCAACTTCC CAGAGTTCGT GGCTGTGGGG
 ATGGTGGATG GTGTTCAGAT GGTTCACTAT GACAGCAACA GCCAGAGAGC
 GGTGCCCAAA CAGGACTGGA TGAACAAGGC AGCAGAAACA CTGCCACAGT
 ACTGGGAGAG GGAGACAGGG AATCTCAAGG GTACCCAGCA GACTTACAAA
 GCCAACATCG ATATTGTAAA GCAGCGTTTT AACCAAAGTG GAGGTGTGCA
 CATTAACCAG AGGATGTATG GTTGTGAGTG GAATGATGAG ACTGGTGCCA
 CAGGGGGTTA TAGTCAGGAT GGATATGATG GAGAGGATTT CATAGCATTT
 GACCTGAAGA CAAAGACATG GATCGCTCCA AAGCCACAGG CAGTCATCAC
 CAAACTCAAG TGGGACAGTG ACATAGCTAT GACTGAGCGG GATAAACATT
 ACCTGACCCA GACCTGCATT GAGTGGCTGA AGAAGTATCT GGACTATGGG
 AAGAGCACTC TGATGACGAC AGTCCCTCCC TCAGTTTCTC TGCTCCAGAA
 GACCCCCTCC TCTCCAGTGA CCTGCCACGC GACAGGTTTC TACCCCAGTG
 GAGTCATGGT GTTCTGGCAG AAAGACGGAC AAGATCAGCA TGGAGATGTG
 GAGCATGGAG AGACTCTCCC CAACGATGAC GGAACCTTCC AGAAAAGCAC
 CCACCTGACA GTGACGCCTG AGGAGTGGAA GAAGAAACAG TATCAGTGTG
 TGGTTCAAGT CACTGGTATT AAGGAGGACT TCATCAAGGT GTTGACTGAG
 TCTGAGATCA AGACCAACTG GAATGACCCA GCCCCCAACA TTGTCCTCAT
 CATTGGAGTG GTGGTAGCTC TCCTCCTGGT CATCGTTGCT GTTGTTGGGG
 TCGTCATTTG GAAGAAGAAG AGCAAGAAAG GCTTTATTCA GGCCCAATCT
 TCCGACACTG ACTCTGACAA CTCTGGGAGA GCTGCCCAGC AGATTTGA*

>DL;Onmy-UBA*1701
Onmy-UBA*1701  1035 bases  
 ATGAAGTCTT TCATCATTTT GCTCCTGGGA ATTAATGCGG CATCTGCAGT
 AACCCACTCT CTGAAGTATT TCTACACTGG AAGTACTGGC ATTGAGGGGT
 TCCCACAGTT TGTTGCAGTG GGCATCGTAG ATGGAATGCA GATTGACTAC
 TTTGATAGTG TGTCTGAGAA GAATGTTCTG AAGCAGTCTT GGATGGAGGG
 GGTACGTGAT GAAAAAATGA TCACAAACAC AAGAAAGGGC AATCAACAAA
 CCTTTAAGGC CAACGTCGAA ATTGGAATGC AACGTTTCAA CCAAACAACA
 GGTGTGCACA TTGTCCAGAG GATGTACGGT TGTGAGTGGG ATGATGAGGC
 TGGAGTCACA GAGGGGTTTA ATCAGTATGG ATATGATGGA GAGGATTTCA
 TAGCATTTGA CCTGAAAACA ACGAAATGGA TCGCCCCAAC GCCACAGGCA
 GTCATCACCA AACTCAAGTG GGACAGTAAC ACAGCATACA CTGAGAACTG
 GAACAACTAC CTGACCCAGA CGTGCATTGA GTGGCTGAAG AAGTATGTGG
 ACTATGGGAA GAGCACTCTG ATGAGGACAG TCCCTCCGTC AGTGTCTCTG
 CTCCAGAAGG CCCCCTCCTC TCCAGTGACC TGCCACGCGA CAGGTTTCTA
 CCCCAGGGAT GTCATGGTGT CCTGGCAGAA AGACGGACAA GATCACCATG
 AGGATGTGGA GTATGGAGAG ACTCTCCCCA ACGATGATGG AACCTTCCAA
 AAAAGCTCCC ACCTGACAGT GACGCCTGAG GACAGGAAGA ACAGCAAGTA
 TCAGTGTGTG GTTCAAGTCA AGGGTATCAA GAAGGACTTC ATCGAGGTTC
 TGACTGACCC GGATGCCGCC AACGTTGTCC CCATCATTGG AGGGGTGGTA
 GCTCTCCTCC TGGTCGTCGT TGCTGTTGTT GTTGGGGTCG TCATTTGGAG
 GAAGAGGAGC AAGAAAGGCT TTGTTCCGGC CAGCACTTCC GACACTGACT
 CTGAAAACTC TGGGAAAGCT GCCCCGCAGA TTTGA*

>DL;Onmy-UBA*1702
Onmy-UBA*1702  684 bases  
 ATGAAGTCTT TCATCATTGT GCTCCTGGGA ATTAATGCGG CATCTGCAGT
 AACCCACTCT CTGAAGTATT TCTACACTGG AAGTACTGGC ATTGAGAGGT
 TCCCACAGTT TGTTGCAGTG GGCATCGTAG ATGGAATGCA GATTGACTAC
 TTTGATAGTG TGTCTGAGAA GAATGTTCTG AAGCAGTCTT GGATGGAGGG
 GGTACGTGAT GAAAAAATGA TCACAAACAC AAGAAAGGGC AATCAACAAA
 CCTTTAAGGC CAACGTCGAA ATTGGAATGC AACGTTTCAA CCAAACAACA
 GGTGTGCACA TTGTCCAGGG GATGTACGGT TGTGAGTGGG ATGATGAGGC
 TGGAGTCACA GAGGGGTTTA ATCAGTATGG ATATGATGGA GAGGATTTCA
 TAGCATTTGA CCTGAAAACA ACGAAATGGA TCGCCCCAAC GCCACAGGCA
 GTCATCACCA AACTCAAGTG GGACAGTAAC ACAGCATACA CTGAGAACTG
 GAACAACTAC CTGACCCAGA CGTGCATTGA GTGGCTGAAG AAGTATGTGG
 ACTATGGGAA GAGCACTCTG ATGAGGACAG TCCCTCCGTC AGTGTCTCTG
 CTCCAGAAGG CCCCCTCCTC TCCAGTGACC TGCCACGCGA CAGGTTTCTA
 CCCCAGGGAT GTCATGGTGT TCTGGCAGAA AGAA*

>DL;Onmy-UBA*1801
Onmy-UBA*1801  1058 bases  
 TAGGCCTTCT TCATACTGCA TCTGCTGCCA CCCACTCTCT GAAATACTTC
 TACACAGCAG TCTCAGGTGA TATTGACTTC CCAGAGTTCA CTGCAGTGGG
 TCTGGTAGAC AAAGGCCAGT TCATGTACTT TGACAGCAGC ACCAAGACTG
 CAGTCCCCAA GACTGAGTGG ATGAAGAGAG AAGGAGCGGA TTACTGGGAC
 AGGCAGACTC AGGGCCTGAT TGGTGCCCAT CAAACCTTCA AAGTCAACAT
 CCAAACATTA AAGGATCGCT TCAACCAGTC CAAGTCCACA GGAGTTCACA
 CATTCCAGCT GATGTATGGC TGTGAGCTGG GTGATGACGG CATCACTCGA
 GGAGACTTTC AGTATGGTTA TGATGGAGCA GATTTCCTCA GCCTGGACAA
 GAGCACTCTC ACCTGGACTG CTGCCAACCA GAAAGCTGTC ATCACCAAGC
 TTAAGTGGGA TGCTACCGGA GCTGATGCTA ACTTTCAGAA GAATTATCTA
 GAAAACACAT GCATTGAGTG GCTTAAGAAG TATGTCAACT ACGGCAAAGA
 CACTTTGGAA AGGAAAGTCC GTCCCTCAGT GTCTCTGCTC CAGAAGACCC
 CCTCCTCTCC AGTGACCTGC CACGCGACAG GTTTCTACCC CAGTGGAGTC
 ATGGTGTTCT GGCAGAAAGA CGGACAAGAA CAGCATGGAG ATGTGGAGCA
 TGGAGAGATC CTCCAGAACG ATGACGGAAC CTTCCAGAAA AGCACCCACC
 TGACAGTGAC GCCTGAGGAG TGGAAGAACA ACAAGTATCA GTGTGTGGTT
 CAACTCGCGG GTATCGAGGA TGACATCACC AAGGTTCTGA TTGAGTCTGA
 GATCCAGACC AACTTTGGAA AGACCAACAG GGGTTCAAAT GACCCAAACA
 CTATTGGCCT CATCATTGGA GGGGTGATAG CTCTCCTGGT CATCATTGCT
 GTTGTTGGGG TCGTCATTTG GAAGAAGAAA AACAAGAAAG GCTTTGTTCC
 GGCCAGCACT TCCGACACGG ACTCTGAAAA CTCTGGGAAA GGTATCCAGA
 AGATTTGA*

>DL;Onmy-UBA*1802
Onmy-UBA*1802  1058 bases  
 TAGGCCTTCT TCATACTGCA TCTGCTGCCA CCCACTCTCT GAAATACTTC
 TACACAGCAG TCTCAGGTGA TATTGACTTC CCAGAGTTCA CTGCAGTGGG
 TCTGGTAGAC AAAGGCCAGT TCATGTACTT TGACAGCAGC ACCAAGACTG
 CAGTCCCCAA GACTGAGTGG ATGAAGAGAG AAGGAGCGGA TTACTGGGAC
 AGGCAGACTC AGGGCCTGAT TGGTGCCCAT CAAACCTTCA AAGTCAACAT
 CCAAACATTA AAGGATCGCT TCAACCAGTC CAAGTCCACA GGAGTTCACA
 CCGTCCAGCT TATGTATGGC TGTGAGCTGG GTGATGACGG CATCACTCGA
 GGAGACTTTC AGTATGGTTA TGATGGAGCA GATTTCCTCA GCCTGGACAA
 GAGCACTCTC ACCTGGACTG CTGCCAACCA GAAAGCTGTC ATCACCAAGC
 TTAAGTGGGA TGCTACCGGA GCTGATGCTA ACTTTCAGAA GAATTATCTA
 GAAAACACAT GCATTGAGTG GCTTAAGAAG TATGTCAACT ACGGCAAAGA
 CACTTTGGAA AGGAAAGTCC GTCCCTCAGT GTCTCTGCTC CAGAAGACCC
 CCTCCTCTCC AGTGACCTGC CACGCGACAG GTTTCTACCC CAGTGGAGTC
 ATGGTGTTCT GGCAGAAAGA CGGACAAGAA CAGCATGGAG ATGTGGAGCA
 TGGAGAGATC CTCCAGAACG ATGACGGAAC CTTCCAGAAA AGCACCCACC
 TGACAGTGAC GCCTGAGGAG TGGAAGAACA ACAAGTATCA GTGTGTGGTT
 CAACTCGCGG GTATCGAGGA TGACATCACC AAGGTTCTGA TTGAGTCTGA
 GATCCAGACC AACTTTGGAA AGACCAACAG GGGTTCAAAT GACCCAAACA
 CTATTGGCCT CATCATTGGA GGGGTGATAG CTCTCCTGGT CATCATTGCT
 GTTGTTGGGG TCGTCATTTG GAAGAAGAAA AACAAGAAAG GCTTTGTTCC
 GGCCAGCACT TCCGACACGG ACTCTGAAAA CTCTGGGAAA GGTATCCAGA
 AGATTTGA*

>DL;Onmy-UBA*1901
Onmy-UBA*1901  1043 bases  
 TAGTCCTTCT TAATACAGTA TCTGCTGCAA CCAATACACT GCAGTATTTC
 TACACGGCCA CTTCTGGTAT AGATAACTTC CCAGAGTTTG TGACTATGGG
 AATCGTCAAT GGCCATCAGA TTGACCACTA CGACAGTATC ACCAAGAGAG
 CAATCCAGAA AGCTGAGTGG ATCAGTGGGG CAGTTGACCC TGACTATTGG
 AAGAGAAACA CCCAAACCTA TGCTGCTGAA GAGCCAGTTT TCTTAAACAA
 CATTAAAATT GCGAAATCCC GCTTCAATCA AACTGGAGGT GTGCACACTA
 ATCAGAGGAT GTATGGTTGT GAGTGGAATG ATGAGACTGG TGCCACAGGG
 GGTTATTTTC AGGATGGATA TGATGGAGAG GATTTCATAG CATTTGACCT
 GAAGACAAAG ACATGGATCG CTCCAAAGCC ACAGGCAGTC ATCACCAAAC
 TCAAGTGGGA CAGTGACATA GCTATGACTG AGCAGAAAAA ACATTACCTG
 ACCCAGGAGT GCATTGAGTG GCTGAAGAAG TATCTGGACT ATGGGAAGAG
 CACTCTGATG ACGACAGTCC CTCCCTCAGT GACTCTGCTC CAGAAGACCC
 CCTCCTCTCC AGTGACCTGC CACGCGACAG GTTTCTACCC CAGTGGAGTC
 ATGGTGTTCT GGCAGAAAGA CGGACAAGAT CAGCATGGAG ATGTGGAGCA
 TGGAGAGACT CTCCCCAACG ATGACGGAAC CTTCCAGAAA AGCACCCACC
 TGACATTGAC GCCTGAGGAG TGGAAGAAGA AACAGTATCA GTGTGTGGTT
 CAAGTCACTG GTATTAAGGA GGACTTCATC AAGGTTTTGA CTGAGTCTGA
 GATCAAGACC AACTGGAATA ACCCAGCCCC CAACATTGTC CTCATCATTG
 GAGTGGTGGT AGCTCTCCTC CTGGTCATCG TTGCTGTTGT TGGGGTCGTC
 ATTTGGAAGA AGAAGAGCAA GAAAGGCTTT ATTCAGGCCC AATCTTCCGA
 CACTGACTCT GACAACTCTG GGAGAGCTGC CCAGCAGATT TGA*

>DL;Onmy-UBA*2001
Onmy-UBA*2001  1074 bases  
 ATGAAGGGTA TTATCTTGCT GGTGCTGGGA ATAGGCCTTC TTCATACAGC
 ATCTGCTGCG ACTCACTCCC TGAAGTATTT CTACACCGGA TCTTCTGAAG
 TTCCCAACTT CCCAGAGTTC GTGGCTGTGG GGATGGTGGA TGGTGTTCAG
 ATGTTTCACT ATGACAGCAA CAGCCAGAGA GCGGTGCCCA AACAGGACTG
 GGTAAACAAG GCAGCAGACC CACAGTACTG GGAGAGGAAC ACTGGGAATT
 GCAAGGGTAG CCAGCAGACT TTCAAAGCCA GCATCGATAT TGTAAAGCAG
 CGTTTTAACC AAAGTGGAGG AGTCCACATT TTCCAGTACA TGTACGGCTG
 TACGTGGGAT GACAGTGGAG TCATTGACGG GTTTCGACAG ATTGGATATG
 ATGGGGAGGA CTTCCTTGTG TACGACATGA AGACTTTCAA ATGGATCGCT
 CCTAAACAGC AAGCTGAGAT CACTCAGCAC AGGTGGAACA ATAACCCTGC
 TGAAATAGCA CAAAGAAAGA GCTACATTAC CCAGGAGTGT GTTGAGTGGC
 TAAAGAAGTA TCTGGACTAT GGGAAGGACT CTCTGATGAG GACAGTCCCT
 CCGTCAGTGT CTCTGCTCCA GAAGACCCCC TCCTCTCCAG TGACCTGCCA
 CGCGACAGGT TTCTACCCCA GTGGAGTTAT GGTGTCCTGG CATAAAGACG
 GACAAGATCA CCATGAAGAT GTGGAGCATG GAGAGATCCT CCAAAACGAT
 GACGGAACCT TCCAGAAAAG CTCCCACCTT ACAGTGACGC CTGAGGAGTG
 GAAGAACAAC AAGTATCAGT GTGTGGTTCA AGTCACAGGT ATCCAGAAGG
 ACTTCATCAA GGTTCTGACT GAGTCTGAGA TCCAGACCAA CTGGGATGAC
 CCAGCCCCCA ACATTGTCCT CATCATTGGA GTGGTGGTAG CTCTCCTCCT
 GGTCGTCGTT GCTGTTGTTG TTGGGGTCGT CATTTGGAAG AAGAAGAGCA
 AGAAAGGCTT TGTTCCGGCC AGCACTTCCG ACACTGAGTC TGACAACTCT
 GGGAGAGCTG CCCAGATGAC TTGA*

>DL;Onmy-UBA*2101
Onmy-UBA*2101  1080 bases  
 ATGAAGTCTT TCATCCTGCT TTTAGGAATA GCCCTACATT CCTCATCTGC
 CGTGATTCAC TCCTGGAAAG CCTTTTTAAC AGCTAGCACA GGGCTTAGCG
 ACTTCCCTGA GTTTGTGGCT CTGAACCTGG TGGATGACGA ACTGATGGGC
 TACTTCGACA CCAAGACCAA CCGCTTTGAG GGCAAACAGA GCTGGGTGGA
 GGAGAAACTG GGACAGCAGT ATATGGAGCG ACAGGAAAAC ATTCTTAGGG
 GCACCTCACA ATCTTTCAAA GTCAATGTGG GAATTGCCAT GGAGCGCTTC
 AACCAAACAA AAGGAGTTCA CACCGTCCAG CTTATGTATG GCTGTGAGCT
 GGGTGATGAC GGCATCACTC GAGGAGACTT TCAGTATGGT TATGATGGAG
 CAGATTTCCT CAGCCTGGAC AAGAGCACTC TCACCTGGAC TGCTGCCAAC
 CAGAAAGCTG TCATCACCAA GCTTAAGTGG GATGCTACCG GAGCTGATGC
 TAACTTTCAG AAGAATTATC TAGAAAACAC ATGCATTGAG TGGCTTAAGA
 AGTATGTCAA CTACGGCAAA GACACTTTGG AAAGGAAAGT CCGTCCCTCA
 GTGTCTCTGC TCCAGAAGAC CCCCTCCTCT CCAGTGACCT GCCACGCGAC
 AGGTTTCTAC CCCAGTGGAG TCATGGTGTT CTGGCAGAAA GACGGACAAG
 AACAGCATGG AGATGTGGAG CATGGAGAGA TCCTCCAGAA CGATGACGGA
 ACCTTCCAGA AAAGCACCCA CCTGACAGTG ACGCCTGAGG AGTGGAAGAA
 CAACAAGTAT CAGTGTGTGG TTCAACTCGC GGGTATCGAG GATGACATCA
 CCAAGGTTCT GATTGAGTCT GAGATCCAGA CCAACTTTGG AAAGACCAAC
 AGGGGTTCAA ATGACCCAAA CACTATTGGC CTCATCATTG GAGGGGTGAT
 AGCTCTCCTG GTCATCATTG CTGTTGTTGG GGTCGTCATT TGGAAGAAGA
 AAAACAAGAA AGGCTTTGTT CCGGCCAGCA CTTCCGACAC GGACTCTGAA
 AACTCTGGGA AAGGTATCCA GAAGATTTGA*

>DL;Onmy-UBA*2201
Onmy-UBA*2201  1014 bases  
 CTCCATACTG CATCTGCTGC TACGCATTCA CTGCGTTATG TGTACACTGC
 AACTTCCGGA GTACCAGACT TCCCAGAGTT TGTCAGTCTG GGTATTGTGG
 ATGGAATGCA GATAGATTAC TATGACAGTA ACACCAAGAG AGTAGTACCC
 AAGCAGGACT GGATGGCCAA GACTGAGGGG TCTGACTACT GGGAGAGACA
 GACTCAGAAC TCCATTGGTG ACGAGCAGAC CTTCAAAGCC AACATTGATG
 TTGCCAAGCA GCGCTTCAAT CAGACTGGAG GTGTGCACAT TGTCCAGAAT
 ATGTACGGTT GTGAGTGGGA TGATGAGTCT GGAGTCACAG AGGGGTTTGA
 TCAGTATGGA TATGATGGAG AGGATTTCAT AGCATTTGAC CTGAAGACAA
 AGACATGGAT CGCTCCAAAG CCACAGGCAG TCATCACCAA ACAAAAGTGG
 GACAGTAACA CAGCTCAAAA TGAGCAGTAC AACAACTACT ACACCCAGGA
 GTGCATTGAG TGGCTGAAGA AGTATATGGA CTATGGGAAG AGCACTCTGA
 TGAGGACAGT CCCTCCGTCA GTGTCTCTGT TCCAGAAGAC CTCCTCCTCT
 CCAGTGACCT GCCACGCGAC AGGTTTCTAC CCCAGTGATG TCATGGTGTC
 CTGGCAGAAA GACGGACAAG ATCACCATGA GGATGTGGAG TATGGAGAGA
 CTCTCCCCAA CGATGATGGA ACCTTCCAGA AAAGCTCCCA CCTGACAGTG
 ACGCCTGAGG ACAGGAAGAA CAGCAAGTAT CAGTGTGTGG TTCAAGTCAA
 GGGTATCAAG GAGGACTTCA TCGAGGTTCT TCCTGACCCG GATGCCGCCA
 ACATTGTCCC CATCATTGTA GGGGTGGTAG CTCTCCTCCT GGTCATTGTT
 GCTGTTGTTG TTGGGGTCGT CATTTGGAAG AAGAGGAGCA AGAAAGGCTT
 TGTTCCGGCC AGCACTTCCG ACACTGACTC TGAAAACTCT GGGAAAGCTG
 CCCCGCAGAT TTGA*

>DL;Onmy-UBA*2301
Onmy-UBA*2301  1074 bases  
 ATGAACGGTT TAATCCTTCT GGTGCAGGGA ATATGTCTTC TTCATACAGT
 ATCTGCTGTG ACTCACTCCA TGCAGTATAT TGTAACAGCT GTTTCTGGTC
 TTGATGAAAT TCCTGAGCAC ACTGAAGTTG GAATGGTAGA TGGTCAGCAG
 TTTGTGTACT ATGACAGCGT TTTAAAGAAG ATTATTCCCA AGACTGACTG
 GATTGAGAAA AATGTGGATG CAAGCTACTG GAAGAGGGAG ACTGACCGGA
 ATATTGCCAC TGAACAAACC TTTAAAAGCA ACGTTGCTAT CGCAATGACA
 CGCTTCAACC AGACCAGGGG TGTGCACACT AATCAGAGGA TGTATGGTTG
 TGAGTGGAAT GATGAGACTG GTGCCACAGG GGGTTATTTT CAGGATGGAT
 ATGATGGAGA GGATTTCATA GCATTTGACC TGAAGACAAA GACATGGATC
 GCTCCAAAGC CACAGGCAGT CATCACCAAA CTCAAGTGGG ACAGTGACAT
 AGCTATGACT GAGCAGAAAA AACATTACCT GACCCAGGAG TGCATTGAGT
 GGCTGAAGAA GTATCTGGAC TATGGGAAGA GCACTCTGAT GACGACAGTC
 CCTCCCTCAG TGACTCTGCT CCAGAAGACC CCCTCCTCTC CAGTGACCTG
 CCACGCGACA GGTTTCTACC CCAGTGGAGT CATGGTGTTC TGGCAGAAAG
 ACGGACAAGA TCAGCATGGA GATGTGGAGC ATGGAGAGAC TCTCCCCAAC
 GATGACGGAA CCTTCCAGAA AAGCACCCAC CTGACATTGA CGCCTGAGGA
 GTGGAAGAAG AAACAGTATC AGTGTGTGGT TCAAGTCACT GGTATTAAGG
 AGGACTTCAT CAAGGTTTTG ACTGAGTCTG AGATCAAGAC CAACTGGAAT
 AACCCAGCCC CCAACATTGT CCTCATCATT GGAGTGGTGG TAGCTCTCCT
 CCTGGTCATC GTTGCTGTTG TTGGGGTCGT CATTTGGAAG AAGAAGAGCA
 AGAAAGGCTT TATTCAGGCC CAATCTTCCG ACACTGACTC TGACAACTCT
 GGGAGAGCTG CCCAGCAGAT TTGA*

>DL;Onmy-UBA*2401
Onmy-UBA*2401  1047 bases  
 ATGAAGTCTT TCATCCTGCT TTTAGGAATA GCCCTACATT CCTCATCTGC
 CGTGATTCAC TCCTGGAAAG CCTTTTTAAC AGCTAGCACA GGGCTTAGCG
 ACTTCCCTGA GTTTGTGGCT CTGAACCTGG TGGATGACGA ACTGATGGGC
 TACTTCGACA CCAAGACCAA CCGCTTTGAG GGCAAACAGA GCTGGGTGGA
 GGAGAAACTG GGACAGCAGT ATATGGAGCG ACAGGAAAAC ATTCTTAGGG
 GCACCTCACA ATCTTTCAAA GTCAATGTGG GAATTGTCAT GGAGCGCTTC
 AACCAAACAA AAGGTGTGCA CATTGTCCAG AGGATGTACG GTTGTGAGTG
 GGATGATGAG ACTGGAGTCA CAGAGGGGTT TAATCAGCAT GGATATGATG
 GAGAGGATTT CATAGCATTT GACCTGAAAA CAACGAAATG GATCGCCCCA
 ACGCCACAGG CAGTCATCAC CAAACACAAG TGGGACAGTA ACACAGTTCG
 AAATGAGCAG AAAAAAAACT ACCTGACCCA GACCTGCATT GAGTGGCTGA
 AGAAGTATGT GGACTATGGG AAGAGCACTC TGATGAGGAC AGTCCCTCCG
 TTAGTGTCTC TGTTCCAGAA GACCTCCTCC TCTCTAGTGA CCTGCCACGC
 GACAGGTTTC TACCCCAGTG ATGTCATGCT GTCCTGGCAG AAAGACGGAC
 AAGATCACCA TGAGGATGTG GAGTATGGAG AGACTCTCCC CAACGATGAT
 GGAACCTTCC AGAAAAGCAT CCACCTGACA GTGACGCCTG AGGACAGGAA
 GAACAGCAAG TATCAGTGTG TGGTTCAAGT CAAGGGTATC AAGGAGGACT
 TCATCAAGGT TCTGCCTGAC CCGGATGCCG CCAACGTTGT CCCCATCATT
 GTAGGGGTGG TAGCTCTCCT CCTGGTCATT GTTGCTGTTG TTGTTGGGGT
 CGTCATTTGG AAGAAGAGGA GCAAGAAAGG CTTTGTTCCG GCCAGCACTT
 CCGACACTGA CTCTGACAAC TCTGGGAGAG CTGTCCCGCA GATTTGA*

>DL;Onmy-UBA*2501
Onmy-UBA*2501  1055 bases  
 TATGTCTTCT TCATACAGTA TCTGCTGTGA CTCACTCCAT GCAGTATATT
 GTAACAGCTG TTTCTGGTCT TGATGAAATT CCTGAGCACA CTGAAGTTGG
 AATGGTAGAT GGTCAGCAGT TTGTGTACTA TGACAGCGTT TTAAAGAAGA
 TTATTCCCAA GACTGACTGG ATTGAGAAAA ATGTGGATGC AAGCTACTGG
 AAGAGGGAGA CTGACCGGAA TATTGCCACT GAACAAACCT TTAAAAGCAA
 CGTTGCTATC GCAATGACAC GCTTCAACCA GACCAGGGGA GTTCACACCG
 TCCAGCTTAT GTATGGCTGT GAGCTGGGTG ATGACGGCAT CACTCGAGGA
 GACTTTCAGT ATGGTTATGA TGGAGCAGAT TTCCTCAGCC TGGACAAGAG
 CACTCTCACC TGGACTGCTG CCAACCAGAA AGCTGTCATC ACCAAGCTTA
 AGTTGGATGC TACCGGAGCT GAGGCTAACT TTCAGAAGAA TTATCTAGAA
 AACACATGCA TTGAGTGGCT TAAGAAGTAT GTCAACTACG GCAAAGACAC
 TTTGGAAAGG AAAGTCCGTC CCTCAGTGTC TCTGCTCCAG AAGACCCCCT
 CCTCTCCAGT GACCTGCCAC GCGACAGGTT TCTACCCCAG TGGAGTCATG
 GTGTTCTGGC AGAAAGACGG ACAAGAACAG CATGGAGATG TGGAGCATGG
 AGAGATCCTC CAGAACGATG ACGGAACCTT CCAGAAAAGC ACCCACCTGA
 CAGTGACGCC TGAGGAGTGG AAGAACAACA AGTATCAGTG TGTGGTTCAA
 CTCGCGGGTA TCGAGGATGA CATCACCAAG GTTCTGATTG AGTCTGAGAT
 CCAGACCAAC TTTGGAAAGA CCAACAGGGG TTCAAATGAC CCAAACACTA
 TTGGCCTCAT CATTGGAGGG GTGATAGCTC TCCTGGTCAT CATTGCTGTT
 GTTGGGGTCG TCATTTGGAA GAAGAAAAAC AAGAAAGGCT TTGTTCCGGC
 CAGCACTTCC GACACGGACT CTGAAAACTC TGGGAAAGGT ATCCAGAAGA
 TTTGA*

>DL;Onmy-UBA*2601
Onmy-UBA*2601  1053 bases  
 ATGAACGGTT TAATCCTTCT GGTGCAGGGA ATATGTCTTC TTCATACAGT
 ATCTGCTGTG ACTCACTCCA TGCAGTATAT TGTAACAGCT GTTTCTGGTC
 TTGATGAAAT TCCTGAGCAC ACTGAAGTTG GAATGGTAGA TGGTCAGCAG
 TTTGTGTACT ATGACAGCGT TTTAAAGAAG ATTATTCCCA AGACTGACTG
 GATTGAGAAA AATGTGGATG CAAGCTACTG GAAGAGGGAG ACTGACCGGA
 ATATTGCCAC TGAACAAACC TTTAAAAGCA ACGTTGCTAT CGCAATGACA
 CGCTTCAACC AGACCAGGGG AGTCCACATT TACCAGTACA TGTACGGCTG
 TATGTGGGAT GATGACAGTG GAGTCACTGA GGGGCATAGG CAGTATGGAT
 ATGATGGGGA GGACTTTCTT GTGTATAACA TGAAGACGTT CACTTGGATT
 GCTCCTAAAC AGCAATCTGA GATCACTCAG CGCAAGTGGA ACAATGAGCC
 TGCTCAAATG GAATACTTAA AGAGCTACAT CACCCAGGAG TGCATTGAGT
 GGCTGAAGAA GTATGTGGAC TATGGGAAGA GCACTCTGAT GAGGACAGTC
 CCTCCGTCAG TGTCTCTGTT CCAGAAGACC CCCTCCTCTC CAGTGACCTG
 CCACGCGACA GGTTTCTACC CCAGTGATGT CATGGTGTCC TGGCAGAAAG
 ACGGACAAGA TCACCATGAA GATGTGGAGT ATGGAGAGAC TCTCCCCAAC
 AATGACGGAA CCTTCCAGAA AAGCATCCAC CTGACAGTGA CGCCTGACGA
 CAGGAAGAAC AACAAGTATC AGTGTGTGGT TCAAGTCAAG GGTATCATGG
 AGGACTTCAT CAAGGTTCTG ACTGACCCGG ATGCCGCCAA CATTGTCCCC
 ATCATTGGAG GGGTGGTAGC TCTCCTCCTG GTCGTCGTTG CTGTTGTTGT
 TGGGGTCGTC ATTTGGAGGA AGAGGAGCAA GAAAGGCTTT GTACCAACCA
 GCACTTCCGA CACTGACTCT GAAAACTCTG GGAAAGCTGC CCCGCAGATT
 TGA*

>DL;Onmy-UBA*2602
Onmy-UBA*2602  1045 bases  
 TATTATCTTG CTGGTGCTGG GAATATGTCT TCTTCATACA GTATCTGCTG
 TGACTCACTC CATGCAGTAT ATTGTAACAG CTGTTTCTGG TCTTGATGAA
 ATTCCTGAGC ACACTGAAGT TGGAATGGGA GATGGTCAGC AGTTTGTGTA
 CTATGACAGC GTTTTAAAGA AGATTATTCC CAAGACTGAC TGGATTGAGA
 AAAATGTGGA TGCAAGCTAC TGGAAGAGGG AGACTGACCG GAATATTGCC
 ACTGAACAAA CCTTTAAAAG CAACGTTGCT ATCGCAATGA CACGCTTCAA
 CCAGACCAGG GGAGTCCACA TTTACCAGTA CATGTACGGC TGTATGTGGG
 ATGATGACAG TGGAGTCACT GAGGGGCATA GGCAGTATGG ATATGATGGG
 GAGGACTTTC TTGTGTATAA CATGAAGACG TTCACTTGGA TTGCTCCTAA
 ACAGCAATCT GAGATCACTC AGCGCAAGTG GAACAATGAG CCTGCTCAAA
 TGGAATACTT AAAGAGCTAC ATCACCCAGG AGTGCATTGA GTGGCTGAAG
 AAGTATGTGG ACTATGGGAA GAGCACTCTG ATGAGGACAG TCCCTCCGTC
 AGTGTCTCTG TTCCAGAAGA CCCCCTCCTC TCCAGTGACC TGCCACGCGA
 CAGGTTTCTA CCCCAGTGAT GTCATGGTGT CCTGGCAGAA AGACGGACAA
 GATCACCATG AAGATGTGGA GTATGGAGAG ACTCTCCCCA ACAATGACGG
 AACCTTCCAG AAAAGCATCC ACCTGACAGT GACGCCTGAC GACAGGAAGA
 ACAACAAGTA TCAGTGTGTG GTTCAAGTCA AGGGTATCAT GGAGGACTTC
 ATCAAGGTTC TGACTGACCC GGATGCCGCC AACATTGTCC CCATCATTGG
 AGGGGTGGTA GCTCTCCTCC TGGTCGTCGT TGCTGTTGTT GTTGGGGTCG
 TCATTTGGAG GAAGAGGAGC AAGAAAGGCT TTGTACCAAC CAGCACTTCC
 GACACTGACT CTGAAAACTC TGGGAAAGCT GCCCCGCAGA TTTGA*

>DL;Onmy-UBA*270101
Onmy-UBA*270101  1056 bases  
 ATGAAGGGTA TTATCTTGCT GGTGCTGGGA ATAGGCCTTC TTCATACAGC
 ATCTGCTGTG ACTCACTCCC TGAAGTATTT CTACACCGCA TCTTCTGAAG
 TTCCCAACTT CCCAGAGTTC GTGGTTGTGG GGATGGTGGA TGGTGTTCAG
 ATGGTTCACT ATGACAGCAA CAGCCAAAGA ATGGTGCCCA GACAGGACTG
 GATGAACAAG GCAGCAGAAA CACTGCCACA GTACTGGGAG AGTCAGACAG
 GGATTCTCAA GGGTACCCAG CAGACTTACA AAGCCAGCAT CGATATTGTA
 AAGCAGCGTT TTAACCAAAG TGGAGGTGTG CACACTTTCC AGAACATGTA
 TGGTTGTGAA TGGGATGATG ACACTGGAGC CACAGAGGGT TTTTTTCAGT
 ATGGATATGA TGGAGAGGAT TTCCTGGCAT TGGACCTGAA GACAAAGAAA
 TGGATCGCTC CAACACCACA GGCCGTCATC ACCAAACACA AGTGGGACAG
 TAACACAGCT AATGAGGAGC GGAGAAAACA TTACCTCACC CAGGAGTGCA
 TTGAGTGGCT GAAGAAGTAT CTGGACTATG GGAAGAGCAC TCTAATGAGG
 ACAGTCCCTC CCTCTGTGTT TCTGCTCCAG AAGACCCCCA CCTCTCCAGT
 GACCTGCCAC GCGACAGGTT TCTACCCCAG TGATGTCATG GTGTCCTGGC
 AGAAAGACGG ACAAGATCAC CATGAAGATG TGGAGTATGG AGAGACTCTC
 CCCAACGATG ACGGAACCTT CCAGAAAAGC ATCCACCTGA CAATGACACC
 TGAGGACAGG AAGAACAACA AGTATCAGTG TGTGGTTCAA GTCAAGGGTA
 TCAAGGAGGA CTTCATCGGG GTTCCGCCTG ACCAGGATGC CGCCAACGTT
 GTCCCCATCA TTGGAGGGGT GGTAGCTCTC CTCCTGGTCG TCGTTGTTGT
 TGTTGTTGGG GTCGTCATTT GGAAGAAGAG GAGCAAGAAA GGCTTTGTTC
 CGGCCAGCAC TTCCGACACT GACTCTGACA ACTCTGGAGG TGTCAAGAAG
 ATTTGA*

>DL;Onmy-UBA*270102
Onmy-UBA*270102  1056 bases  
 ATGAAGGGTA TTATCTTGCT GGTGCTGGGA ATAGGCCTTC TTCATACAGC
 ATCTGCTGTG ACTCACTCCC TGAAGTATTT CTACACCGCA TCTTCTGAAG
 TTCCCAACTT CCCAGAGTTC GTGGTTGTGG GGATGGTGGA TGGTGTTCAG
 ATGGTTCACT ATGACAGCAA CAGCCAAAGA ATGGTGCCCA GACAGGACTG
 GATGAACAAG GCAGCAGAAA CACTGCCACA GTACTGGGAG AGTCAGACAG
 GGATTCTCAA GGGTACCCAG CAGACTTACA AAGCCAGCAT CGATATTGTA
 AAGCAGCGTT TTAACCAAAG TGGAGGTGTG CACACTTTCC AGAACATGTA
 TGGTTGTGAA TGGGATGATG ACACTGGAGC CACAGAGGGT TTTTTTCAGT
 ATGGATATGA TGGAGAGGAT TTCCTGGCAT TGGACCTGAA GACAAAGAAA
 TGGATCGCTC CAACACCACA GGCCGTCATC ACCAAACACA AGTGGGACAG
 TAACACAGCT AATGAGGAGC GGAGAAAACA TTACCTCACC CAGGAGTGCA
 TTGAGTGGCT GAAGAAGTAT CTGGACTATG GGAAGAGCAC TCTAATGAGG
 ACAGTCCCTC CCTCTGTGTT TCTGCTCCAG AAGACCCCCA CCTCTCCAGT
 GACCTGCCAC GCGACAGGTT TCTACCCCAG TGATGTCATG GTGTCCTGGC
 AGAAAGACGG ACAAGATCAC CATGAAGATG TGGAGTATGG AGAGACTCTC
 CCCAACGATG ACGGAACCTT CCAGAAAAGC ATCCACCTGA CAATGACACC
 TGAGGACAGG AAGAACAACA AGTATCAGTG TGTGGTTCAA GTCAAGGGTA
 TCAAGGAGGA CTTCATCGGG GTTCCGCCTG ACCAGGATGC CGCCAACGTT
 GTCCCCATCA TTGGAGGGGT GGTAGCTCTC CTCCTGGTCG TCGTTGTTGT
 TGTTGTTGGG GTCGTCATTT GGAAGAAGAG GAGCAAGAAA GGCTTTGTTC
 CGGCCAGCAC TTCCGACACT GACTCTGACA ACTCTGGAGG TGTCAAGAAG
 ATTTGA*

>DL;Onmy-UBA*270103
Onmy-UBA*270103  1056 bases  
 ATGAAGGGTA TTATCTTGCT GGTGCTGGGA ATAGGCCTTC TTCATACAGC
 ATCTGCTGTG ACTCACTCCC TGAAGTATTT CTACACCGCA TCTTCTGAAG
 TTCCCAACTT CCCAGAGTTC GTGGTTGTGG GGATGGTGGA TGGTGTTCAG
 ATGGTTCACT ATGACAGCAA CAGCCAAAGA ATGGTGCCCA GACAGGACTG
 GATGAACAAG GCAGCAGAAA CACTGCCACA GTACTGGGAG AGTCAGACAG
 GGATTCTCAA GGGTACCCAG CAGACTTACA AAGCCAGCAT CGATATTGTA
 AAGCAGCGTT TTAACCAAAG TGGAGGTGTG CACACTTTCC AGAACATGTA
 TGGTTGTGAA TGGGATGATG ACACTGGAGC CACAGAGGGT TTTTTTCAGT
 ATGGATATGA TGGAGAGGAT TTCCTGGCAT TGGACCTGAA GACAAAGAAA
 TGGATCGCTC CAACACCACA GGCCGTCATC ACCAAACACA AGTGGGACAG
 TAACACAGCT AATGAGGAGC GGAGAAAACA TTACCTCACC CAGGAGTGCA
 TTGAGTGGCT GAAGAAGTAT CTGGACTATG GGAAGAGCAC TCTAATGAGG
 ACAGTCCCTC CCTCTGTGTT TCTGCTCCAG AAGACCCCCA CCTCTCCAGT
 GACCTGCCAC GCGACAGGTT TCTACCCCAG TGATGTCATG GTGTCCTGGC
 AGAAAGACGG ACAAGATCAC CATGAAGATG TGGAGTATGG AGAGACTCTC
 CCCAACGATG ACGGAACCTT CCAGAAAAGC ATCCACCTGA CAATGACACC
 TGAGGACAGG AAGAACAACA AGTATCAGTG TGTGGTTCAA GTCAAGGGTA
 TCAAGGAGGA CTTCATCGGG GTTCCGCCTG ACCAGGATGC CGCCAACGTT
 GTCCCCATCA TTGGAGGGGT GGTAGCTCTC CTCCTGGTCG TCGTTGTTGT
 TGTTGTTGGG GTCGTCATTT GGAAGAAGAG GAGCAAGAAA GGCTTTGTTC
 CGGCCAGCAC TTCCGACACT GACTCTGACA ACTCTGGAGG TGTCAAGAAG
 ATTTGA*

>DL;Onmy-UBA*2801
Onmy-UBA*2801  1068 bases  
 ATGAAGTCTT TCATCATTTT GCTCCTGGGA ATTAATGCGG CATCTGCAGT
 AACCCACTCT CTGAAGTATT TCTACACTGG AAGTACTGGC ATTGAGGGGT
 TCCCACAGTT TGTTGCAGTG GGCATCGTAG ATGGAATGCA GATTGACTAC
 TTTGATAGTG TGTCTGAGAA GAATGTTCTG AAGCAGTCTT GGATGGAGGG
 GGTACGTGAT GAAAAAATGA TCACAAACAC AAGAAAGGGC AATCAACAAA
 CCTTTAAGGC CAACGTCGAA ATTGGAATGC AACGTTTCAA CCAAACAACA
 GGAGTTCACA CATTCCAGCT GATGTATGGC TGTGAGCTGG GTGATGACGG
 CATCACTCGA GGAGACTTTC AGTATGGTTA TGATGGAGCA GATTTCCTCA
 GCCTGGACAA GAGCACTCTC ACCTGGACTG CTGCCAACCA GAAAGCTGTC
 ATCACCAAGC TTAAGTGGGA TGCTACCGGA GCTGATGCTA ACTTTCAGAA
 GAATTATCTA GAAAACACAT GCATTGAGTG GCTTAAGAAG TATGTCAACT
 ACGGCAAAGA CACTTTGGAA AGGAAAGTCC GTCCCTCAGT GTCTCTGCTC
 CAGAAGACCC CCTCCTCTCC AGTGACCTGC CACGCGACAG GTTTCTACCC
 CAGTGGAGTC ATGGTGTTCT GGCAGAAAGA CGGACAAGAA CAGCATGGAG
 ATGTGGAGCA TGGAGAGATC CTCCAGAACG ATGACGGAAC CTTCCAGAAA
 AGCACCCACC TGACAGTGAC GCCTGAGGAG TGGAAGAACA ACAAGTATCA
 GTGTGTGGTT CAACTCGCGG GTATCGAGGA TGACATCACC AAGGTTCTGA
 TTGAGTCTGA GATCCAGACC AACTTTGGAA AGACCAACAG GGGTTCAAAT
 GACCCAAACA CTATTGGCCT CATCATTGGA GGGGTGATAG CTCTCCTGGT
 CATCATTGCT GTTGTTGGGG TCGTCATTTG GAAGAAGAAA AACAAGAAAG
 GCTTTGTTCC GGCCAGCACT TCCGACACGG ACTCTGAAAA CTCTGGGAAA
 GGTATCCAGA AGATTTGA*

>DL;Onmy-UBA*2901
Onmy-UBA*2901  702 bases  
 ATGAAAGGGT ATTATCTGCT GGTGCTGGGA ATAGGCCTTC TTCATATAGC
 GTCTGCTGTG ACCCATTCCC TGCGCTACTT CTACACTGCC ACCACAGGAA
 TCCCAGACTT CCCTGAGTTT GTGGATGTGG GGGTGGTGAA CGGTAAGGTC
 ATCAGCTACT ATGATAGCAT CACAAAGAGG AAGGTCCCCA AGCAGAGCTG
 GATGGAAGAG AATCTCAACC AGCAGTACTG GAATCAAGGC ACAGATCAAT
 TGAAGGGAGC AGAGCAAACC TTCAAAGCCA ACATTCAAAT AGTACAGACA
 CGTTTCAATC AAACTGGAGG TGTGCACACT TTCCAGAACA TGTATGGTTG
 TGAATGGGAT GATGACACTG GAGCCACAGA GGGTTTTTTT CAGTATGGAT
 ATGATGGAGA GGATTTCCTG GCATTGGACC TGAAGACAAA GAAATGGATC
 GCTCCAACAC CACAGGCCGT CATCACCAAA CACAAGTGGG ACAGTGACAC
 AGCTGACAAT AAGTACAGAA AAAACTACCT GACCCAGGAG TGCATTGATT
 GGCTGAAGAA GTATGTGGAC TATGGGAAGA GCACTCTGAT GAGGACAGTC
 CGTCCCTCAG TGCCTCTGCT CCAGAAGGCC CCCTCCTCTC CAGTGACATG
 CCACGCGACA GGTTTCTACC CCAGTGATGT CATGGTGTTC TGGCAGAAAG
 AA*

>DL;Onmy-UBA*3001
Onmy-UBA*3001  684 bases  
 ATGAAGTCTT TCATCATTTT GCTCCTGGGA ATTAATGCGG CATCTGCAGT
 AACCCACTCT CTGAAGTATT TCTACACTGG AAGTACTGGC ATTGAGGGGT
 TCCCACAGTT TGTTGCTGTG GGCATCGTAG ATGGAATGCA GATTGACTAC
 TTTGATAGTG TGTCTGAGAA GAATGTTCTG AAGCAGTCTT GGATGGAGGG
 GGTACGTGAT GAAAAAATGA CCACAAACAC AAGAAAGGGC CATCAGCAAA
 CCTTTAAGGC CAACGTCGAA ATTGGAATGC AACGTTTCAA CCAAACAACA
 GGTGTGCACA TTGTCCAGTG GATGTACGGT TGTGAGTGGG ATGATGAGGC
 TGGAGTCACA GAGGGGTTTG ATCAGCATGG ATATGATGGA GAGGATTTCA
 TAGCATTTGA CCTGAAAACA ACGAAATGGA TCGCCCCAAC GCCACAGGCA
 GTCATCACCA AAAACAAGTG GGACAGTAAC ACAGTTCGAA ATGAGCAGAA
 TAAAAACTAC TACACCCAGA CCTGCATTGA GTGGCTGAAG AAGTATGTGG
 ACTATGGGAA GAGCACTCTG ATGAGGACAG TCCCTCCGTC AGTGTCTCTG
 TTCCAGAAGA CCTCCTCCTC TCTAGTGACC TGCCACGCGA CAGGTTTCTA
 CCCCAGTGAT GTCATGGTGT TCTGGCAGAA AGAA*

>DL;Onmy-UBA*3101
Onmy-UBA*3101  705 bases  
 ATGAAGGGTA TTATCTTGCT GGTGCTGGGA ATAGGCCTTC TTCATACTGC
 ATCTGCTGCC ACCCACTCTC TGAAATACTT CTACACAGCA GTCTCAGGTG
 ATATTGACTT CCCAGAGTTC ACTGCAGTGG GTCTGGTAGA CAAAGGCCAG
 TTCATGTACT TTGACAGCAA CACCAAGACT GCAGTCCCCA AGACTGAGTG
 GATGAAGAGA GAAGGAGCAG ATTACTGGGA CAGGGAGACT CAGATTGCTA
 TTGGTGTACA TCAAACCTTC AAAGTCGACA TCCAAACATT AAAGGATCGC
 TTCAACCAGT CCAAGTCCAC AGGTGTGCAC GTTTTCCAGA ATATGTACGG
 TTGTGAGTGG GATGATGAGG CTGGAGCCAC AGAGGGGTTT TATCAGTTTG
 GATATGATGG AGAGGATTTC ATAGCATTTG ACCTGAAAAC AACTAAATGG
 ATCGCTCCAA CGCCACAGGC AGTCATCACC AAACAAAAGT GGGACAGTGA
 CACAGCTGAC AATAAGTACA GAAAAAACTA CTGCACCCAG GAGTGCATTG
 ATTGGCTGAA GAAGTATGTG GACTATGGGA AGAGCACTCT GATGAGGACA
 GTCCGTCCCT CAGTGTCTCT GCTCCAGAAG GCCCCCTCCT CTCCAGTGAC
 ATGCCACGCG ACAGGTTTCT ACCCCAGTGA TGTCATGGTG TTCTGGCAGA
 AAGAA*

>DL;Onmy-UBA*3201
Onmy-UBA*3201  705 bases  
 ATGAAGGGTA TTATCTTGCT GGTGCTGGGA ATAGGCCTTC TTCATACTGC
 ATCTGCTGCC ACCCACTCTC TGAAATACTT CTACACAGCA GTCTCAGGTG
 ATATTGACTT CCCAGAGTTC ACTGCAGTGG GTCTGGTAGA CAAAGGCCAG
 TTCATGTACT TTGACAGCAA CACCAAGACT GCAGTCCCCA AGACTGAGTG
 GATGAAGAGA GAAGGAGCAG ATTACTGGGA CAGGGAGACT CAGATTGCTA
 TTGGTGTACA TCAAACCTTC AAAGTCGACA TCCAAACATT AAAGGATCGC
 TTCAACCAGT CCAAGTCCAC AGGTGTGCAC GTTTTCCAGA ATATGTACGG
 TTGTGAGTGG GATGATGAGG CTGGAGCCAC AGAGGGGTTT TATCAGTTTG
 GATATGATGG AGAGGATTTC ATAGCATTTG ACCTGAAAAC AACTAAATGG
 ATCGCTCCAA CGCCACAGGC AGTCATCACC AAACAAAAGT GGGACAGTAA
 CACAGCTAAT GAGGAGCGGA GAAAACATTA CCTCACCCAG GAGTGCATTG
 AGTGGCTGAA GAAGTATCTG GACTATGGGA AGAGCACTCT AATGAGGACA
 GTCCCTCCCT CTGTGTTTCT GCTCCAGAAG ACCCCCTCCT CTCCAGTGAC
 CTGCCACGCG ACAGGTTTCT ACCCCAGTGA TGTCATGGTG TTCTGGCAGA
 AAGAA*

