>DL;Onmy-DAA*0101
Onmy-DAA*0101  657 bases  
 ATGAAGACCT CTATGATTGT CCTCATCCTC TGCTGTCAGG TGTATGCAGA
 AGACAAAGTT CTGCATACTG ATATATATAT TAATGGATGC AGTGATTCAG
 ATGGAGTGGA TATGTATGGA CTGGATGGTG AAGAGTTGTG GTACGCAGAC
 TTCAACAAAA AGGAGGGAGT GGTGGCTCTG CCTCCGTTTG CAGATCAGAT
 TTCCTTCCCT GGATATTATG AACAGGCTGT AGGTAATCAG AGGACATGCA
 AAGGAGACCT TGGCGTAGAT ATAAAAGCTT ACAAGAACCC ACCAGAGACA
 ATAGACCCTC CTCACAGCAG CATCTACCCC AGGGATGACG TGGAACTGGG
 GGTGGAGAAC ACCCTCATCT GCCACGTCAG TGGGTTCTTC CCTTCACCTG
 TCAGAGTCAG GTGGACCAGG AACGATCAGA ATGTAACTGA GGGAGGGCGT
 ATCAGCACCC CCTACCCCAA CACTGATGTC ACCTTCAACC AGTTCTCCAG
 TCTGAGCTTC ACCCCAGAGG AGGGAGACAT CTATGGCTGT ACTGTGGAGC
 ACAAGGCCCT TACTGAGCCC CTGACACGGA TCTGGGAACC TGAGGTGAGC
 CAGCCCAGTG TGGGCCCTGC TGTGTTCTGT GGTGTGGGTC TGACTCTGGG
 GCTGCTG*

>DL;Onmy-DAA*0201
Onmy-DAA*0201  708 bases  
 ATGAAGACCT CTATGATTGT CCTCATCCTC TGCTGTCAGG TGTATGCAGA
 AGACAAAGTT CTGCATACTG ATATATATAT TAGTGGATGC AGTGATTCAG
 ATGGAGTGGA TATGTATGGA CTGGATGGTG AAGAGTTGTG GTACGCAGAC
 TTCAACAAAA AGGAGGGAGT GGTGGCTCTG CCTCCGTTTG CAGATCAGAT
 TTCCTTCCCT GGATTTTATG AACAGGCTGT AGGTGACCTG GAGATCTTGA
 AAGGAAACCT GGCCAAATGT ATAAAAGCTT ACAAGAACCC ACCAGAGACA
 ATAGACCCTC CTCACAGCAG CATCTACCCC AGGGATGATG TGGAACTGGA
 AGTGAAGAAC ACCCTTATCT GCCACGTCAG TGGGTTCTTC CCTCCACCTG
 TCAGAGTCAG GTGGACCAGG AACAATCAGA ATGTAACTGA GGGAGGGCGT
 ATCAGCACCC CCTACCCCAA CACTGATGTC ACCTTCAACC AGTTCTCCAG
 TCTGAGCTTC ACCCCAGAGG AGGGAGACAT CTATGGCTGT ACTGTGGAGC
 ACAAGGGCCT TACTGAGCCC CTGACACGGA TCTGGGAACC TGAGGTGAGC
 CAGCCCAGTG TGGCTCCTGC TGTGTTCTGT GGTGTGGGTC TGACTCTGGG
 GCTGCTGGGA GTTGCTACCG GAACATTCTT CCTCATCAAA GGGAACCAGT
 GCAACTGA*

>DL;Onmy-DAA*0301
Onmy-DAA*0301  682 bases  
 ATGAAGACCT CTATGATTGT CCTCATCCTC TGCTGTCAGG TGTATGCAGA
 AGACAAAGTT CTGCATATTG ATTTAGCTAT TACTGGATGC AGTGATTCAG
 ATGGAGTGGA TATGTATGGA CTGGATGGTG AAGAGTTGTG GTACGCAGAC
 TTCAACAAAA AGGAGGGAGT GATGGCTCTG CCTCCGTTTG CAGATCAGAT
 GACCTTCCCT GGATTTTATG AACAGGCTGT AGGTAATCTG GGGATATGCA
 AAGCAAACCT GGCCGTAGCT ATAAAAGCTT CCAAGAACCC ACCAGAGGCA
 ATAGCCCCTC CTCACAGCAG CATCTACCCC AGGGATGATG TGGAACTGGG
 GGTGGAGAAC ACCCTCATCT GCCACGTCAG TGCGTTCCAC CCTGCACCTG
 TCAGAGTCAG GTGGACCAGG AACAATCAGA ATGTGACCGA GGGAGTGCGT
 CTCAGCACCC CCTACCCCAA CACTGATTTC ACCCTCAACC AGTTCTCCAG
 TCTGACCTTC ACCCCAGAGG AGGGAGACAT CTATGGCTGT ACTGTGGAGC
 ACAAGGCCCT TACTGAGCCC CTGACACGGA TCTGGGAACC TGAGGTGAGC
 CAGCCCAGTG TGGCTCCTGC TGTGTTCTGT GGTGTGGGTC TGACTCTGGG
 GCTGCTGGGA GTGGCTACCG GAACATTCTT CC*

