>P1;Sasa-DAA*0101
Sasa-DAA*0101  235 bases  
 MKTSVIVLIL CWQVYAEHKV LHIDLVITGC SDSDGLDMYG LDGEEMWYAD
 FNKQEGVVAL PPFADPFTFP GFYEQAVGNQ GVCKGNLAKC IKAYKNPEEK
 IDPPHSSIYP RDDVDLGVEN TLICHVSGFF PAPVRVRWTR NNQNLTEGVR
 LSTPYPNADF TLNQFSSLPF TPEEGDIYGC TVEHKGLAEP LTRIWEPEVI
 QPSVGPDVFC GVGLTLGLLG VAAGTFFLIK GNQCN*

>P1;Sasa-DAA*0102
Sasa-DAA*0102  225 bases  
 CWQVYAEHKV LHIDLVITGC SDSDGLDMYG LDGEEMWYAD FNKQEGVVAL
 PPFADPFTFP GFYEQAVGNQ GVCKGNLAKC IKAYKNPEEK IDPPHSSIYP
 RDDVDLGVEN TLICHVSGFF PAPVRVRWTR NNQNLTEGVR LSTPYPNADF
 TLNQFSSLPF TPEEGDIYGC TVEHKGLAEP LTRIWEPEVI QPSVGPAVFC
 GVGLTLGLLG VAAGTFFLIK GNQCN*

>P1;Sasa-DAA*0201
Sasa-DAA*0201  225 bases  
 CWQVYAEHKV LHIDLYISGC SDSDGLDMYG LDGEEMWYAD FNKGEGVVAL
 PPFADPFTFP GFYEGAVGNQ GVCKANLAVN IKAYKNPEEK IDPPHSSIYP
 RDDVDLGVEN TLICHVSGFH PAPVRVRWTR NNQNLTEGVR LSTPYPNADF
 TLNQFSSLPF TPEEGDIYGC TVEHKGLAEP LTRIWEPEVI QPSVGPAVFC
 GVGLTVGLLG VAAGTFFLIK GNQCN*

>P1;Sasa-DAA*0301
Sasa-DAA*0301  225 bases  
 CWQVYAEHKV LHIDLVITGC SDSDGVDMYG LDGEEMWYAD FNKGEGVMPL
 PPFADPFTYP GAYEGAVGNQ GICKANLATC IKAYKNPEEK IAPPHSSIYP
 RDDVDLGVEN TLICHVSGFH PAPVRVRWTR NNQNLTEGVR LSTPYPNADF
 TLNQFSSLPF TPEEGDIYGC TVEHKGLAEP LTRIWEPEVI QPSVGPAVFC
 GVGLTLGLLG VAAGTFFLIK GNQCN*

>P1;Sasa-DAA*0302
Sasa-DAA*0302  218 bases  
 HKVLHIDLAI TGCSDSDGLD MYGLDGEEMW YADFNKGEGV MPLPPFADPF
 TYPGAYEGAV GNQGICKANL ATCIKAYKNP EEKIAPPHSS IYPRDDVDLG
 VENTLICHVS GFHPAPVRVR WTRNNQNLTE GVRLSTPYPN ADFTLNQFSS
 LPFTPEEGDI YGCTVEHKGL AEPLTRIWEP EVIQPSVGPA VFCGVGLTLG
 LLGVAAGTFF LIKGNQCN*

>P1;Sasa-DAA*0303
Sasa-DAA*0303  218 bases  
 HKVLHIDLVI TGCSDSDGLN MYGLDGEEMW YADFNKGEGV MPLPPFADPF
 TYPGAYEGAV GNQGICKANL ATCIKAYKNP EEKIAPPHSS IYPRDDVDLG
 VENTLICHVS GFHPAPVRVR WTRNNQNLTE GVRLSTPYPN ADFTLNQFSS
 LPFTPEEGDI YGCTVEHKGL AEPLTRIWEP EVIQPSVGPA VFCGVGLTLG
 LLGVAAGTFF LIKGNQCN*

>P1;Sasa-DAA*0304
Sasa-DAA*0304  71 bases  
 GCSDSDGVDM YGLDGEEMWY ADFNKGEGVM PLPPFADPFT YPGAYEQAVG
 NQGVCKANLA TCIKAYKNPE E*

>P1;Sasa-DAA*0305
Sasa-DAA*0305  71 bases  
 GCSDSDGLNM YGLDGEEMWY ADFNKGEGVM PLPPFADPFT YPGAYERAVG
 NQGVCKANLA ICIKAYKNPE E*

>P1;Sasa-DAA*0401
Sasa-DAA*0401  225 bases  
 CWQVYAEHKV LHIDLHIIGC SDSDGVDMYG LDGEEMWYAD FNKGEGVVAL
 PPFADPFTFP GFYEGAVGNQ GVCKANLAVN IKAYKNPEEK IDPPHSSIYP
 RDDVDLGVEN TLICHVSGFF PAPVRVRWTR NNQNLTEGVR LSTPYPNADF
 TLNQFSSLPF TPEEGDIYGC TVEHKGLAEP LTRIWEPEVI QPSVGPAVFC
 GVGLTVGLLG VAAGTFFLIK GNQCN*

>P1;Sasa-DAA*0501
Sasa-DAA*0501  225 bases  
 CWQVYAEHKV LHIDLAITGC SDSDGVDMYG LDGEEMWYAD FNKGEGVVAL
 PPFADPFTFP GHYEGAVGNQ GVCKANLATS IKAYKNPEEK IAPPHSSIYP
 RDDVDLGVEN TLICHVSGFY PAPVRVRWTR NNQNLTEGVR LSTPYPNADV
 TFNQFSSLPF TPEEGDIYGC TVEHKGLAEP LTRIWEPEVI QPSVGPAVFC
 GVGLTVGLLG VAAGTFFLIK GNQCN*

>P1;Sasa-DAA*0502
Sasa-DAA*0502  225 bases  
 CWQVYAEHKV LHIDLAITGC SDSDGVDMYG LDGEEMWYAD FNKGEGVVAL
 PPFADPFTFP GFYEQAVGNQ GVCKGNLATS IKAYKNPEEK IAPPHSSIYP
 RDDVDLGVEN TLICHVSGFY PAPVRVRWTR NNQNLTEGVR LSTPYPNADV
 TFNQFSSLPF TPEEGDIYGC TVEHKGLAEP LTRIWEPEVI QPSVGPAVFC
 GVGLTVGLLG VAAGTFFLIK GNQCN*

>P1;Sasa-DAA*0601
Sasa-DAA*0601  225 bases  
 CWQVYAEHKV LHIDLVISGC SDSDGVDMYG LDGEEMWYAD FNKGEGVMPL
 PPFADPFTYP GAYEQAVGNQ GVCKANLAVN IKAYKNPEEK IAPPHSSIYP
 RDDVDLGVEN TLICHVSGFY PAPVRVRWTR NNQNLTEGVR LSTPYPNADV
 TFNQFSSLPF TPEEGDIYGC TVEHKGLAEP LTRIWEPEVI QPSVGPAVFC
 GVGLTLGLLG VAAGTFFLIK GNQCN*

>P1;Sasa-DAA*0701
Sasa-DAA*0701  225 bases  
 CWQVYAEHKV LHIDLAITGC SDSDGLDMYG LDGEEMWYAD FNKQEGVVAL
 PPFADPFTYH GAYEQAVGNQ GICKGNLAKC IKAYKNPEEK IDPPHSSIYP
 RDDVDLGVEN TLICHVSGFH PAPVRVRWAR NNQNLTEGVR LSTPYPNADF
 TLNQFSSLPF TPEEGDIYGC TVEHKGLAEP LTRIWEPEVI QPSVGPAVFC
 GVGLTLGLLG VAAGTFFLIK GNQCN*

>P1;Sasa-DAA*0801
Sasa-DAA*0801  218 bases  
 HKVLHIDLAI TGCSDSDGLD MYGLDGEEMW YADFNKQEGV VALPPFADPF
 TFPGHYEGAV GNQGVCKGNL AKCIKAYKNP EEKIDPPHSS IYPRDDVDLG
 VENTLICHVS GFHPAPVRVR WTRNNQNLTE GVRLSTPYPN ADFTLNQFSS
 LPFTPEEGDI YGCTVEHKGL AEPLTRIWEP EVIQPSVGPA VFCGVGLTLG
 LLGVAAGTFF LIKGNQCN*

>P1;Sasa-DAA*0901
Sasa-DAA*0901  218 bases  
 HKVLHIDLVI TGCSDSDGVD MYGLDGEEMW YADFNKGEGV VALPPFADPF
 TFHGAYEGAV GNQGVCKANL AVNIKAYKNP EEKIDPPHSS IYPRDDVDLG
 VENTLICHVS GFHPAPVRVR WTRNNQNLTE GVRLSTPYPN ADFTLNQFSS
 LPFTPEEGDI YGCTVEHKGL AEPLTRIWEP EVIQPSVGPA VFCGVGLTVG
 LLGVAAGTFF LIKGNQCN*

>P1;Sasa-DAA*1001
Sasa-DAA*1001  218 bases  
 HKVLHIDLAI TGCSDSDGLN MYGLDGEEMW YADFNKGEGV VALPPFADPF
 TFPGFYEQAV GNQGVCKANL ATSIKAYKNP EEKIAPPHSS IYPRDDVDLG
 VENTLICHVS GFHPAPVRVR WTRNNQNLTE GVRLSTPYPN ADFTLNQFSS
 LPFTPEEGDI YGCTVEHKGL AEPLTRIWEP EVIQPSVGPA VFCGVGLTLG
 LLGVAAGTFF LIKGNQCN*

>P1;Sasa-DAA*1101
Sasa-DAA*1101  218 bases  
 HKVLHIDLAI TGCSDSDGVD MYGLDGEEMS YADFNKGEGV VALPPFADPF
 TFPGFYEQAV GNQGVCKANL ATSIKAYKNP EEKIAPPHSS IYPRDDVDLG
 VENTLICHVS GFHPAPVRVR WTRNNQNLTE GVRLSTPYPN ADFTLNQFSS
 LPFTPEEGDI YGCTVEHKGL AEPLTRIWEP EVIQPSVGPA VFCGVGLTLG
 LLGVAAGTFF LIKGNQCN*

>P1;Sasa-DAA*1201
Sasa-DAA*1201  218 bases  
 HKVLHIDLHI TGCSDSDGVE MYGLDGEEMW YADFNKGEGV MPLPPFADPF
 TYPGAYEQAV GNQGICKANL AVNIKAYKNP EEKIDPPHSS IYPRDDVDLG
 VENTLICHVS GFHPAPVRVR WTRNNQNLTE GVRLSTPYPN ADFTLNQFSS
 LPFTPEEGDI YGCTVEHKGL AEPLTRIWEP EVIQPSVGPA VFCGVGLTVG
 LLGVAAGTFF LIKGNQCN*

>P1;Sasa-DAA*1202
Sasa-DAA*1202  71 bases  
 GCSDSDGVEM YGLDGEEMWY ADFNKGEGVM PLPPFADPFT FPGAYEQAVG
 NQGVCKANLA VNIKAYKNPE E*

>P1;Sasa-DAA*1301
Sasa-DAA*1301  225 bases  
 CWQVYAEHKV LHIDLVISGC SDSDGVDMYG LDGEEMWYAD FNKGEGVVAL
 PPFADPFTFP GAYEQAVGNQ GVCKANLAVN IKAYKNPEEK IAPPHSSIYP
 RDDVDLGVEN TLICHVSGFF PAPVRVRWTR NNQNLTEGVR LSTPYPNADV
 TFNQFSSLPF TPEEGDIYGC TVEHKGLAEP LTRIWEPEVI QPSVGPAVFC
 GVGLTLGLLG VAAGTFFLIK GNQCN*

>P1;Sasa-DAA*1401
Sasa-DAA*1401  225 bases  
 CWQVYAEHKV LHKDLYITGC SDSDGLDMYG LDGEEMWYAD FNKGEGVVAL
 PPFADPFTFP GFYEQAVGNQ GVCKANLATC IKAYKNPEEK IAPPHSSIYP
 RDDVDLGVEN TLICHVSGFH PAPVRVRWTR NNQNLTEGVR LSTPYPNADF
 TLNQFSSLPF TPEEGDIYGC TVEHKGLAEP LTRIWEPEVI QPSVGPAVFC
 GVGLTLGLLG VAAGTFFLIK GNQCN*

