>DL;Sasa-DAB*0101
Sasa-DAB*0101  737 bases  
 CGATGTCTAT CTTCTGCGTT TCCCTGACCC TGGTTTTGTC CATATTCTCT
 GGAACAGATG GATATTTTGA ACAGGTTGTG AGACAGTGCC GATACTCCTC
 AAAGGACCTG CAGGGTATAG AGTTTATAGA CTCTTATGTT TTCAATAAGG
 CTGAATATAT CAGATTCAAC AGCACTGTGG GGAAGTTTGT TGGATACACT
 GAGCTGGGAG TGAAGAATGC AGAAGCCTGG AACAGTGATG CTGCGGTGCT
 GGCTGTAGAG CGAGGGGAGC TGGAGCGTTA CTGTAAGCAT AACGCTGATC
 TCCACTACAG CACCATACTG GACAAGACAG TTGAGCCCCA TGTCAGACTG
 AGCTCAGTGG CTCCCCCCAG TGGCAGACAC CCTGCCATGC TGATGTGCAG
 CGCCTACGAC TTCTACCCCA AACCAATCAG AGTGACCTGG CTGAGGGACG
 GACGTGAGGT GAAGTCTGAT GTGACCTCCA CTGAGGAGCT GGCTAACGGG
 GACTGGTACT ACCAGATCCA CTCCCACCTG GAGTACACAC CCAGGTCTGG
 AGAGAAGATC TCCTGCATGG TGGAGCACAT CAGCCTCACT GAGCCCATGG
 TGTATCACTG GGACCCGTCC CTGCCTGAGG CTGAGAGGAA TAAGATAGCC
 ATCGGTGCGT CTGGTCTGGT GCTGGGAGCC ATCTTAGCCT TGGCAGGACT
 CATCTACTAC AAGAAGAAGT CTTCTGGGGT GCTGTAG*

>DL;Sasa-DAB*0102
Sasa-DAB*0102  672 bases  
 ATGTCGATGT CTATCTTCTG CGTTTCCCTG ACCCTGGTTT TGTCCATATT
 CTCTGGAACA GATGGATATT TTGAACAGGT TGTGAGACAG TGCCGATACT
 CCTCAAAGGA CCTGCAGGGT ATAGAGTTGA TAGACTCTTA TGTTTTCAAT
 AAGGCTGAAT ATATCAGATT CAACAGCACT GTGGGGAAGT TTGTTGGATA
 CACTGAGCTG GGAGTGAAGA ATGCAGAAGC CTGGAACAGT GATGCTGCGG
 TGCTGGCTGT AGAGCGAGGG GAGCTGGAGC GTTACTGTAA GCATAACGCT
 GATCTCCACT ACAGCACCAT ACTGGACAAG ACAGTTGAGC CCCATGTCAG
 ACTGAGCTCA GTGGCTCCCC CCAGTGGCAG ACACCCTGCC ATGCTGATGT
 GCAGCGCCTA CGACTTCTAC CCCAAACCAA TCAGAGTGAC CTGGCTGAGG
 GACGGACGTG AGGTGAAGTC TGATGTGACC TCCACTGAGG AGCTGGCTAA
 CGGGGACTGG TACTACCAGA TCCACTCCCA CCTGGAGTAC ACACCCAGGT
 CTGGAGAGAA GATCTCCTGC ATGGTGGAGC ACATCAGCCT CACTGAGCCC
 ATGGTGTATC ACTGGGACCC GTCCCTGCCT GAGGCTGAGA GGAATAAGAT
 AGCCATCGGT GCGTCTGGTC TG*

>DL;Sasa-DAB*0201
Sasa-DAB*0201  669 bases  
 ATGTCGATGT CTATCTTCTG CGTTTCCCTG ACCCTGGTTT TGTCCATATT
 CTCTGGAACA GATGGATATT TTGAACAGGT TGTGAGACAG TGCCGATACT
 CCTCAAAGGA CCTGCAGGGT ATAGAGTTTA TAGACTCTTA TGTTTTCAAT
 AAGGCTGAAT ATGTCAGATT CAACAGCACT GTGGGGAAGT ATGTTGGATA
 CACTGAGCTG GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC
 TGGCTGTAGA GCTAGGGGAG CTGGAGCGTT TCTGTAAGCA TAACGCTGCT
 ATCTACTACA GTGCCATACT GGACAAGACA GTTGAGCCCC ATGTCAGACT
 GAGCTCAGTG GCTCCCCCCA GTGGCAGACA CCCTGCCATG CTGATGTGCA
 GCGCCTACGA CTTCTACCCC AAACCAATCA GAGTGACCTG GCTGAGGGAC
 GGACGTGAGG TGAAGTCTGA TGTGACCTCC ACTGAGGAGC TGGCTAACGG
 GGACTGGTAC TACCAGATCC ACTCCCACCT GGAGTACACA CCCAGGTCTG
 GAGAGAAGAT CTCCTGCATG GTGGAGCACA TCAGCCTCAC TGAGCCCATG
 GTGTATCACT GGGACCCGTC CCTGCCTGAG GCTGAGAGGA ATAAGATAGC
 CATCGGTGCG TCTGGTCTG*

>DL;Sasa-DAB*0202
Sasa-DAB*0202  627 bases  
 GTTTCCCTGA CCCTGGTTTT GTCCATATTC TCTGGAACAG ATGGATATTT
 TGAACATGTT GTGAGACAGT GCCGATACTC CTCAAAGGAC CTGCAGGGTA
 TAGAGTTTAT AGACTCTTAT GTTTTCAATA AGGCTGAATA TGTCAGATTC
 AACAGCACTG TGGGGAAGTA TGTTGGATAC ACTGAGCTGG GAGTGAAGAA
 TGCAGAAGCC TGGAACAAAG GTCCTGAGCT GGCTGTAGAG CTAGGGGAGC
 TGGAGCGTTT CTGTAAGCAT AACGCTGCTA TCTACTACAG TGCCATACTG
 GACAAGACAG TTGAGCCCCA TGTCAGACTG AGCTCAGTGG CTCCCCCCAG
 TGGCAGACAC CCTGCCATGC TGATGTGCAG CGCCTACGAC TTCTACCCCA
 AACCAATCAG AGTGACCTGG CTGAGGGACG GACGTGAGGT GAAGTCTGAT
 GTGACCTCCA CTGAGGAGCT GGCTAACGGG GACTGGTACT ACCAGATCCA
 CTCCCACCTG GAGTACACAC CCAGGTCTGG AGAGAAGATC TCCTGCATGG
 TGGAGCACAT CAGCCTCACT GAGCCCATGG TGTATCACTG GGACCCGTCC
 CTGCCTGAGG CTGAGAGGAA TAAGATA*

>DL;Sasa-DAB*0301
Sasa-DAB*0301  669 bases  
 ATGTCGATGT CTATCTTCTG CGTTTCCCTG ACCCTGGTTT TGTCCATATT
 CTCTGGAACA GATGGATATT TTTATCATAT GATGAGACAG TGCCGATACT
 CCTCAAAGGA CCTGCAGGGT ATAGAGTTGA TTACCTCGTA TGTTTTCAAT
 CAGGCTGAAT ATATCAGATT CAACAGCACT GTGGGGAAGT ATGTTGGATA
 CACTGAGTAT GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC
 TGGCTGGAGA GCTAGGGGAG CTGGAGCGTG TCTGTAAGCA TAACGCTCCT
 ATCGACTACA GCGCCATACT GGACAAGACA GTTGAGCCCC ATGTCAGACT
 GAGCTCAGTG GCTCCCCCCA GTGGCAGACA CCCTGCCATG CTGATGTGCA
 GCGCCTACGA CTTCTTCCCC AAACCAATCA GAGTGACCTG GCTGAGGGAC
 GGACGTGAGG TGAAGTCTGA TGTGACCTCC ACTGAGGAGC TGGCTAACGG
 GGACTGGTAC TACCAGATCC ACTCCCACCT GGAGTACACA CCCAGGTCTG
 GAGAGAAGAT CTCCTGCATG GTGGAGCACA TCAGCCTCAC TGAGCCCATG
 GTGTATCACT GGGACCCGTC CCTGCCTGAG GCTGAGAGGA ATAAGATAGC
 CATCGGTGCG TCTGGTCTG*

>DL;Sasa-DAB*0302
Sasa-DAB*0302  254 bases  
 GATGGATATT TTTATCATAT GATGAGACAG TGCCGATACT CCTCAAAGGA
 CCTGCAGGGT ATAGAGTTGA TTACCTCGTA TGTTTTCAAT CAGGCTGAAT
 ATATCAGATT CAACAGCACT GTGGGGAAGT ATGTTGGATA CACTGAGTAT
 GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC TGGCTGGAGA
 GCTAGGGGAG CTGGAGCGTG TCTGTAAGCA TAACGCTCCT ATCTACTACA
 GCGC*

>DL;Sasa-DAB*0303
Sasa-DAB*0303  669 bases  
 ATGTCGATGT CTATCTTCTG CGTTTCCCTG ACCCTGGTTT TGTCCATATT
 CTCTGGAACA GATGGATATT TTTATCATAT GATGAGACAG TGCCGATACT
 CCTCAAAGGA CCTGCAGGGT ATAGAGTTGA TTACCTCGTA TGTTTTCAAT
 CAGGCTGAAT ATATCAGATT CAACAGCACT GTGGGGAAGT ATGTTGGATA
 CACTGAGTAT GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC
 TGGCTGGAGA GCTAGGGGTG CTGGAGCGTT ACTGTAAGCA TAACGCTCCT
 ATCTACTACA GCGCCATACT GGACAAGACA GTTGAGCCCC ATGTCAGACT
 GAGCTCAGTG GCTCCCCCCA GTGGCAGACA CCCTGCCATG CTGATGTGCA
 GCGCCTACGA CTTCTTCCCC AAACCAATCA GAGTGACCTG GCTGAGGGAC
 GGACGTGAGG TGAAGTCTGA TGTGACCTCC ACTGAGGAGC TGGCTAACGG
 GGACTGGTAC TACCAGATCC ACTCCCACCT GGAGTACACA CCCAGGTCTG
 GAGAGAAGAT CTCCTGCATG GTGGAGCACA TCAGCCTCAC TGAGCCCATG
 GTGTATCACT GGGACCCGTC CCTGCCTGAG GCTGAGAGGA ATAAGATAGC
 CATCGGTGCG TCTGGTCTG*

>DL;Sasa-DAB*0401
Sasa-DAB*0401  669 bases  
 ATGTCGATGT CTATCTTCTG CGTTTCCCTG ACCCTGGTTT TGTCCATATT
 CTCTGGAACA GATGGATATT TTTTTCAGGT TGTGAGACAG TGCCGATACT
 CCTCAAAGGA CCTGCAGGGT ATAGAGTTTA TACACTCTTA TGTTTTCAAT
 CAGGCTGAAA ATATCAGATT CAACAGCACT GTGGGGAAGT ATGTTGGATA
 CACTGAGCTG GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC
 TGGCTGGAGA GCTAGGGGAG CTGGAGCGTT TCTGTAAGCA TAACGCTGAT
 CTCCACTACA GCACCATACT GGACAAGACA GTTGAGCCCC ATGTCAGACT
 GAGCTCAGTG GCTCCCCCCA GTGGCAGACA CCCTGCCATG CTGATGTGCA
 GCGCCTACGA CTTCTACCCC AAACCAATCA GAGTGACCTG GCTGAGGGAC
 GGACGTGAGG TGAAGTCTGA TGTGACCTCC ACTGAGGAGC TGGCTAACGG
 GGACTGGTAC TACCAGATCC ACTCCCACCT GGAGTACACA CCCAGGTCTG
 GAGAGAAGAT CTCCTGCATG GTGGAGCACA TCAGCCTCAC TGAGCCCATG
 GTGTATCACT GGGACCCGTC CCTGCCTGAG GCTGAGAGGA ATAAGATAGC
 CATCGGTGCG TCTGGTCTG*

>DL;Sasa-DAB*0501
Sasa-DAB*0501  669 bases  
 ATGTCGATGT CTATCTTCTG CGTTTCCCTG ACCCTGGTTT TGTCCATATT
 CTCTGGAACA GATGGATATT TTTATCAGGT TGTGAGACAG TGCCGATACT
 CCTCAAAGGA CCTGCAGGGT ATAGAGTTTA TAGACTCTTA TGTTTTCAAT
 AAGGCTGAAT ATGTCAGATT CAACAGCACT GTGGGGAAGT ATGTTGGATA
 CACTGAGTAT GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC
 TGGCTGGAGA GCTAGGGGAG CTGGAGCGTT ACTGTAAGCA TAACGCTCCT
 ATCTACTACA GCGCCATACT GGACAAGACA GTTGAGCCCC ATGTCAGACT
 GAGCTCAGTG GCTCCCCCCA GTGGCAGACA CCCTGCCATG CTGATCTGCA
 GCGCCTACGA CTTCTACCCC AAACCAATCA GAGTGACCTG GCTGAGGGAC
 GGACGTGAGG TGAAGTCTGA TGTGACCTCC ACTGAGGAGC TGGCTAACGG
 GGACTGGTAC TACCAGATCC ACTCCCACCT GGAGTACACA CCCAGGTCTG
 GAGAGAAGAT CTCCTGCATG GTGGAGCACA TCAGCCTCAC TGAGCCCATG
 GTGTATCACT GGGACCCGTC CCTGCCTGAG GCTGAGAGGA ATAAGATAGC
 CATCGGTGCG TCTGGTCTG*

>DL;Sasa-DAB*0601
Sasa-DAB*0601  738 bases  
 ATGTCGATGT CTATCTTCTG CGTTTCCCTG ACCCTGGTTT TGTCCATATT
 CTCTGGAACA GATGGATATT TTTATCATAT GATGACACAG TGCCGATACT
 CCTCAAAGGA CCTGCAGGGT ATAGAGTTGA TTACCTCGTA TGTTTTCAAT
 CAGGCTGAAA ATATCAGATT CAACAGCACT GTGGGGAAGT TTGTTGGATA
 CACTGAGCAT GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC
 TGGCTGGAGA GCTAGGGGTG CTGGAGCGTT ACTGTAAGTT TAACGCTCCT
 ATCGACTACA GCGCCATACT GGACAAGACA GTTGAGCCCC ATGTCAGACT
 GAGCTCAGTG GCTCCCCCCA GTGGCAGACA CCCTGCCATG CTGATGTGCA
 GCGCCTACGA CTTCTTCCCC AAACCAATCA GAGTGACCTG GCTGAGGGAC
 GGACGTGAGG TGAAGTCTGA TGTGACCTCC ACTGAGGAGC TGGCTAACGG
 GGACTGGTAC TACCAGATCC ACTCCCACCT GGAGTACACA CCCAGGTCTG
 GAGAGAAGAT CTCCTGCATG GTGGAGCACA TCAGCCTCAC TGAGCCCATG
 GTGTATCACT GGGACCCGTC CCTGCCTGAG GCTGAGAGGA ATAAGATAGC
 CATCGGTGCG TCTGGTCTGG TGCTGGGAGC CATCTTAGCC TTGGCAGGAC
 TCATCTACTA CAAGAAGAAG TCTTCTGGGG TGCTGTAG*

>DL;Sasa-DAB*0701
Sasa-DAB*0701  738 bases  
 ATGTCGATGT CTATCTTCTG CGTTTCCCTG ACCCTGGTTT TGTCCATATT
 CTCTGGAACA GATGGATATT TTGAACAGGT TGTGAGACAG TGCCGATACT
 CCTCAAAGGA CCTGCAGGGT ATAGAGTTTA TAGACTCTTA TGTTTTCAAT
 AAGGCTGAAT ATGTCAGATT CAACAGCACT GTGGGGAAGT ATGTTGGATA
 CACTGAGCTG GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC
 TGGCTGTAGA GCTAGGGGAG CTGGAGCGTT TCTGTAAGCA TAACGCTGAT
 CTCCACTACC GCGCCATACT GGACAAGACA GTTGAGCCCC ATGTCAGACT
 GAGCTCAGTG GCTCCCCCCA GTGGCAGACA CCCTGCCATG CTGATGTGCA
 GCGCCTACGA CTTCTACCCC AAACCAATCA GAGTGACCTG GCTGAGGGAT
 GGACGTGAGG TGAAGTCTGA TGTGACCTCC ACTGAGGAGC TGGCTAACGG
 GGACTGGTAC TACCAGATCC ACTCCCACCT GGAGTACACA CCCAGGTCTG
 GAGAGAAGAT CTCCTGCATG GTGGAGCACA TCAGCCTCAC TGAGCCCATG
 GTGTATCACT GGGACCCGTC CCTGCCTGAG GCTGAGAGGA ATAAGATAGC
 CATCGGTGCG TCTGGTCTGG TGCTGGGAGC CATCTTAGCC TTGGCAGGAC
 TCATCTACTA CAAGAAGAAG TCTTCTGGGG TGCTGTAG*

>DL;Sasa-DAB*0801
Sasa-DAB*0801  669 bases  
 ATGTCGATGT CTATCTTCTG CGTTTCCCTG ACCCTGGTTT TGTCCATATT
 CTCTGGAACA GATGGATATT TTTATCAGAG GGTGTCAGAG TGCCGATACT
 CCTCAAAGGA CCTGCAGGGT ATAGAGTTTA TAGACTCTTA TGTTTTCAAT
 AAGGCTGAAT ATGTCAGATT CAACAGCACT GTGGGGAAGT ATGTTGGATA
 CACTGAGTAT GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC
 TGGCTGGAGA GCTAGGGGAG CTGGAGCGTG TCTGTAAGCA TAACGCTCCT
 ATCGACTACA GCGCCATACT GGACAAGACA GTTGAGCCCC ATGTCAGACT
 GAGCTCAGTG GCTCCCCCCA GTGGCAGACA CCCTGCCATG CTGATGTGCA
 GCGCCTACGA CTTCTTCCCC AAACCAATCA GAGTGACCTG GCTGAGGGAC
 GGACGTGAGG TGAAGTCTGA TGTGACCTCC ACTGAGGAGC TGGCTAACGG
 GGACTGGTAC TACCAGATCC ACTCCCACCT GGAGTACACA CCCAGGTCTG
 GAGAGAAGAT CTCCTGCATG GTGGAGCACA TCAGCCTCAC TGAGCCCATG
 GTGTATCACT GGGACCCGTC CCTGCCTGAG GCTGAGAGGA ATAAGATAGC
 CATCGGTGCG TCTGGTCTG*

>DL;Sasa-DAB*0802
Sasa-DAB*0802  627 bases  
 GTTTCCCTGA CCCTGGTTTT GTCCATATTC TCTGGAACAG ATGGATATTT
 TTATCAGAGG GTGTCAGAGT GCCGATACTC CTCAAAGGAC CTGCAGGGTA
 TAGAGTTTAT AGACTCTTAT GTTTTCAATA AGGCTGAATA TGTCAGATTC
 AACAGCACTG TGGGGAAGTA TGTTGGATAC ACTGAGTATG GAGTGAAGAA
 TGCAGAAGCC TGGAACAAAG GTCCTGAGCT GGCTGGAGAG CTAGGGGAGC
 TGGAGCGTGT CTGTAAGCAT AACGCTCCTA TCTACTACAG CGCCATACTG
 GACAAGACAG TTGAGCCCCA TGTCAGACTG AGCTCAGTGG CTCCCCCCAG
 TGGCAGACAC CCTGCCATGC TGATGTGCAG CGCCTACGAC TTCTTCCCCA
 AACCAATCAG AGTGACCTGG CTGAGGGACG GACGTGAGGT GAAGTCTGAT
 GTGACCTCCA CTGAGGAGCT GGCTAACGGG GACTGGTACT ACCAGATCCA
 CTCCCACCTG GAGTACACAC CCAGGTCTGG AGAGAAGATC TCCTGCATGG
 TGGAGCACAT CAGCCTCACT GAGCCCATGG TGTATCACTG GGACCCGTCC
 CTGCCTGAGG CTGAGAGGAA TAAGATA*

>DL;Sasa-DAB*0901
Sasa-DAB*0901  627 bases  
 GTTTCCCTGA CCCTGGTTTT GTCCATATTC TCTGGAACAG ATGGATATTT
 TGAACAGGTT GTGAGACAGT GCCGATACTC CTCAAAGGAC CTGCAGGGTA
 TAGAGTTTAT AGACTCTTAT GTTTTCAATA AGGCTGAATA TGTCAGATTC
 AACAGCACTG TGGGGAAGTA TGTTGGATAC ACTGAGCTGG GAGTGAAGAA
 TGCAGAAGCC TGGAACAAAG GTCCTGAGCT GGCTGTAGAG CTAGGGGAGC
 TGGAGCGTTA CTGTAAGCTT AACGCTCCTA TCGACTACAG CGCCATACTG
 GACAAGACAG TTGAGCCCCA TGTCAGACTG AGCTCAGTGG CTCCCCCCAG
 TGGCAGACAC CCTGCCATGC TGATGTGCAG CGCCTACGAC TTCTACCCCA
 AACCAATCAG AGTGACCTGG CTGAGGGACG GACGTGAGGT GAAGTCTGAT
 GTGACCTCCA CTGAGGAGCT GGCTAACGGG GACTGGTACT ACCAGATCCA
 CTCCCACCTG GAGTACACAC CCAGGTCTGG AGAGAAGATC TCCTGCATGG
 TGGAGCACAT CAGCCTCACT GAGCCCATGG TGTATCACTG GGACCCGTCC
 CTGCCTGAGG CTGAGAGGAA TAAGATA*

>DL;Sasa-DAB*0902
Sasa-DAB*0902  627 bases  
 GTTTCCCTGA CCCTGGTTTT GTCCATATTC TCTGGAACAG ATGGATATTT
 TGAACAGGTT GTGAGACAGT GCCGATACTC CTCAAAGGAC CTGCAGGGTA
 TAGAGTTTAT AGACTCTTAT GTTTTCAATA AGGCTGAATA TGTCAGATTC
 AACAGCACTG TGGGGAAGTT TGTTGGATAC ACTGAGCTGG GAGTGAAGAA
 TGCAGAAGCC TGGAACAAAG GTCCTGAGCT GGCTGTAGAG CTAGGGGAGC
 TGGAGCGTTA CTGTAAGCTT AACGCTCCTA TCGACTACAG CGCCATACTG
 GACAAGACAG TTGAGCCCCA TGTCAGACTG AGCTCAGTGG CTCCCCCCAG
 TGGCAGACAC CCTGCCATGC TGATGTGCAG CGCCTACGAC TTCTACCCCA
 AACCAATCAG AGTGACCTGG CTGAGGGACG GACGTGAGGT GAAGTCTGAT
 GTGACCTCCA CTGAGGAGCT GGCTAACGGG GACTGGTACT ACCAGATCCA
 CTCCCACCTG GAGTACACAC CCAGGTCTGG AGAGAAGATC TCCTGCATGG
 TGGAGCACAT CAGCCTCACT GAGCCCATGG TGTATCACTG GGACCCGTCC
 CTGCCTGAGG CTGAGAGGAA TAAGATA*

>DL;Sasa-DAB*1001
Sasa-DAB*1001  627 bases  
 GTTTCCCTGA CCCTGGTTTT GTCCATATTC TCTGGAACAG ATGGATACTT
 TCATCAGAGG GTGACACAGT GCCGATACTC CTCAAAGGAC CTGCAGGGTA
 TAGAGTTTAT AGACTCTTAT GTTTTCAATC AGGCTGAATA TATCAGATTC
 AACAGCACTG TGGGGAAGTT TGTTGGATAC ACTGAGCTGG GAGTGAAGAA
 TGCAGAAGCC TTGAACAAAG GTCCTGAGCT GGCTGTAGAG CTAGGGGAGC
 TGGAGCGTTA CTGTAAGCTT AACGCTCCTA TCGACTACAG CGCCATACTG
 GACAAGACAG TTGAGCCCCA TGTCAGACTG AGCTCAGTGG CTCCCCCCAG
 TGGCAGACAC CCTGCCATGC TGATGTGCAG CGCCTACGAC TTCTACCCCA
 AACCAATCAG AGTGACCTGG CTGAGGGACG GACGTGAGGT GAAGTCTGAT
 GTGACCTCCA CTGAGGAGCT GGCTAACGGG GACTGGTACT ACCAGATCCA
 CTCCCACCTG GAGTACACAC CCAGGTCTGG AGAGAAGATC TCCTGCATGG
 TGGAGCACAT CAGCCTCACT GAGCCCATGG TGTATCACTG GGACCCGTCC
 CTGCCTGAGG CTGAGAGGAA TAAGATA*

>DL;Sasa-DAB*1101
Sasa-DAB*1101  627 bases  
 GTTTCCCTGA CCCTGGTTTT GTCCATATTC TCTGGAACAG ATGGATACTT
 TCATCAGAGG GTGACACAGT GCCGATACTC CTCAAAGGAC CTGCAGGGTA
 TAGAGTTTAT AGACTCTTAT GTTTTCAATC AGGCTGAATA TATCAGATTC
 AACAGCACTG TGGGGAAGTT TGTTGGATAC ACTGAGCATG GAGTGAAGAA
 TGCAGAAGCC TGGAACAAAG GTCCTGAGCT GGCTGGAGAG CTAGGGGAGC
 TGGAGCGTTA CTGTAAGTTT AACGCTCCTA TCTACTACAG CGCCATACTG
 GACAAGACAG TTGAGCCCCA TGTCAGACTG AGCTCAGTGG CTCCCCCCAG
 TGGCAGACAC CCTGCCATGC TGATGTGCAG CGCCTACGAC TTCTACCCCA
 AACCAATCAG AGTGACCTGG CTGAGGGACG GACGTGAGGT GAAGTCTGAT
 GTGACCTCCA CTGAGGAGCT GGCTAACGGG GACTGGTACT ACCAGATCCA
 CTCCCACCTG GAGTACACAC CCAGGTCTGG AGAGAAGATC TCCTGCATGG
 TGGAGCACAT CAGCCTCACT GAGCCCATGG TGTATCACTG GGACCCGTCC
 CTGCCTGAGG CTGAGAGGAA TAAGATA*

>DL;Sasa-DAB*1102
Sasa-DAB*1102  254 bases  
 GATGGATACT TTCATCAGAG GGTGACACAG TGCCGATACT CCTCAAAGGA
 CCTGCAGGGT ATAGAGTTTA TAGACTCTTA TGTTTTCAAT CAGGCTGAAT
 ATATCAGATT CAACAGCACT GTGGGGAAGT TTGTTGGATA CACTGAGCAT
 GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC TGGCTGGAGA
 GCTAGGGGAG CTGGAGCGTG TCTGTAAGCA TAACGCTCCT ATCTACTACA
 GCGC*

>DL;Sasa-DAB*1201
Sasa-DAB*1201  627 bases  
 GTTTCCCTGA CCCTGGTTTT GTCCATATTC TCTGGAACAG ATGGATATTT
 TGAACAGGTT GTGAGACAGT GCCGATACTC CTCAAAGGAC CTGCAGGGTA
 TAGAGTTTAT AGACTCTTAT GTTTTCAATA AGGCTGAATA TATCAGATTC
 AACAGCACTG TGGGGAAGTA TGTTGGATAC ACTGAGTATG GAGTGAAGAA
 TGCAGAAGCC TGGAACAAAG GTCCTGAGCT GGCTAGAGCG CTAGGGGAGC
 TGGAGCGTGT CTGTAAGCAT AACGCTCCTA TCTACTACAG CGCCATACTG
 GACAAGACAG TTGAGCCCCA TGTCAGACTG AGCTCAGTGG CTCCCCCCAG
 TGGCAGACAC CCTGCCATGC TGATGTGCAG CGCCTACGAC TTCTACCCCA
 AACCAATCAG AGTGACCTGG CTGAGGGACG GACGTGAGGT GAAGTCTGAT
 GTGACCTCCA CTGAGGAGCT GGCTAACGGG GACTGGTACT ACCAGATCCA
 CTCCCACCTG GAGTACACAC CCAGGTCTGG AGAGAAGATC TCCTGCATGG
 TGGAGCACAT CAGCCTCACT GAGCCCATGG TGTATCACTG GGACCCGTCC
 CTGCCTGAGG CTGAGAGGAA TAAGATA*

>DL;Sasa-DAB*1202
Sasa-DAB*1202  254 bases  
 GATGGATATT TTGAACAGGT TGTGAGACAG TGCCGATACT CCTCAAAGGA
 CCTGCAGGGT ATAGAGTTTA TAGACTCTTA TGTTTTCAAT AAGGCTGAAT
 ATATCAGATT CAACAGCACT GTGGGGAAGT ATGTTGGATA CACTGAGTAT
 GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC TGGCTAGAGC
 GCTAGGGGAG CTGGAGCGTT ACTGTAAGTT TAACGCTCCT ATCTACTACA
 GCGC*

>DL;Sasa-DAB*1301
Sasa-DAB*1301  254 bases  
 GATGGATATT TTTATCATAT GATGAGACAG TGCCGATACT CCTCAAAGGA
 CCTGCAGGGT ATAGAGTTGA TTACCTCGTA TGTTTTCAAT CAGGCTGAAA
 ATATCAGATT CAACAGCACT GTGGGGAAGT TTGTTGGATA CACTGAGCTG
 GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC TGGCTGGAGA
 GCTAGGGGTG CTGGAGCGTT TCTGTAAGCA TAACGCTGAT CTCCACTACA
 GCAC*

>DL;Sasa-DAB*1302
Sasa-DAB*1302  254 bases  
 GATGGATATT TTTATCATAT GATGAGACAG TGCCGATACT CCTCAAAGGA
 CCTGCAGGGT ATAGAGTTGA TTACCTCGTA TGTTTTCAAT CAGGCTGAAA
 ATATCAGATT CAACAGCACT GTGGGGAAGT TTGTTGGATA CACTGAGCAT
 GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC TGGCTGGAGA
 GCTAGGGGAG CTGGAGCGTT TCTGTAAGCA TAACGCTGAT CTCCACTACA
 GCAC*

>DL;Sasa-DAB*1303
Sasa-DAB*1303  669 bases  
 ATGTCGATGT CTATCTTCTG CGTTTCCCTG ACCCTGGTTT TGTCCATATT
 CTCTGGAACA GATGGATATT TTTATCATAT GATGAGACAG TGCCGATACT
 CCTCAAAGGA CCTGCAGGGT ATAGAGTTGA TTACCTCGTA TGTTTTCAAT
 CAGGCTGAAA ATATCAGATT CAACAGCACT GTGGGGAAGT TTGTTGGATA
 CACTGAGCAT GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC
 TGGCTGGAGA GCTAGGGGAG CTGGAGCGTG TCTGTAAGCA TAACGCTGAT
 CTCCACTACA GCACCATACT GGACAAGACA GTTGAGCCCC ATGTCAGACT
 GAGCTCAGTG GCTCCCCCCA GTGGCAGACA CCCTGCCATG CTGATGTGCA
 GCGCCTACGA CTTCTTCCCC AAACCAATCA GAGTGACCTG GCTGAGGGAC
 GGACGTGAGG TGAAGTCTGA TGTGACCTCC ACTGAGGAGC TGGCTAACGG
 GGACTGGTAC TACCAGATCC ACTCCCACCT GGAGTACACA CCCAGGTCTG
 GAGAGAAGAT CTCCTGCATG GTGGAGCACA TCAGCCTCAC TGAGCCCATG
 GTGTATCACT GGGACCCGTC CCTGCCTGAG GCTGAGAGGA ATAAGATAGC
 CATCGGTGCG TCTGGTCTG*

>DL;Sasa-DAB*1401
Sasa-DAB*1401  254 bases  
 GATGGATATT TTTATCAGGT TGTGAGACAG TGCCGATACT CCTCAAAGGA
 CCTGCAGGGT ATAGAGTTTA TAGACTCTTA TGTTTTCAAT CAGGCTGAAT
 ATATCAGATT CAACAGCACT GTGGGGAAGT TTGTTGGATA CACTGAGCAT
 GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC TGGCTGTAGA
 GCTAGGGGAG CTGGAGCGTT ACTGTAAGCA TAACGCTGAT CTCCACTACA
 GCAC*

>DL;Sasa-DAB*1501
Sasa-DAB*1501  254 bases  
 GATGGATATT TTTATCAGGT TGTGAGACAG TGCCGATACT CCTCAAAGGA
 CCTGCAGGGT ATAGAGTTTA TAGACTCTTA TGTTTTCAAT CAGGCTGAAT
 ATATCAGATT CAACAGCACT GTGGGGAAGT TTGTTGGATA CACTGAGCAT
 GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC TGGCTGTAGA
 GCTAGGGGAG CTGGAGCGTT TCTGTAAGCA TAACGCTCCT ATCGACTACA
 GCGC*

>DL;Sasa-DAB*1502
Sasa-DAB*1502  669 bases  
 ATGTCGATGT CTATCTTCTG CGTTTCCCTG ACCCTGGTTT TGTCCATATT
 CTCTGGAACA GATGGATATT TTTATCAGGT TGTGAGACAG TGCCGATACT
 CCTCAAAGGA CCTGCAGGGT ATAGAGTTTA TAGACTCTTA TGTTTTCAAT
 CAGGCTGAAT ATATCAGATT CAACAGCACT GTGGGGAAGT TTGTTGGATA
 CACTGAGCAT GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC
 TGGCTGGAGA GCTAGGGGAG CTGGAGCGTT ACTGTAAGCT TAACGCTCCT
 ATCGACTACA GCGCCATACT GGACAAGACA GTTGAGCCCC ATGTCAGACT
 GAGCTCAGTG GCTCCCCCCA GTGGCAGACA CCCTGCCATG CTGATGTGCA
 GCGCCTACGA CTTCTACCCC AAACCAATCA GAGTGACCTG GCTGAGGGAC
 GGACGTGAGG TGAAGTCTGA TGTGACCTCC ACTGAGGAGC TGGCTAACGG
 GGACTGGTAC TACCAGATCC ACTCCCACCT GGAGTACACA CCCAGGTCTG
 GAGAGAAGAT CTCCTGCATG GTGGAGCACA TCAGCCTCAC TGAGCCCATG
 GTGTATCACT GGGACCCGTC CCTGCCTGAG GCTGAGAGGA ATAAGATAGC
 CATCGGTGCG TCTGGTCTG*

>DL;Sasa-DAB*1601
Sasa-DAB*1601  254 bases  
 GATGGATATT TTGAACAGGT TGTGAGACAG TGCCGATACT CCTCAAAGGA
 CCTGCAGGGT ATAGAGTTTA TAGACTCTTA TGTTTTCAAT CAGGCTGAAT
 ATATCAGATT CAACAGCACT GTGGGGAAGT TTGTTGGATA CACTGAGCTG
 GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC TGGCTGTAGA
 GCTAGGGGAG CTGGAGCGTT ACTGTAAGCT TAACGCTCCT ATCGACTACA
 GCGC*

>DL;Sasa-DAB*1701
Sasa-DAB*1701  254 bases  
 GATGGATATT TTGAACAGGT TGTGAGACAG TGCCGATTCT CCTCAAAGGA
 CCTGCAGGGT ACAGAGTTTA TAGACTCTTA TGTTTTCAAT AAGGCTGAAT
 ATGTCAGATT CAACAGCACT GTGGGGAAGT ATGTTGGATA CACTGAGCTG
 GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC TGGCTGGAGA
 GCTAGGGGAG CTGGAGCGTT TCTGTAAGCA TAACGCTCCT ATCGACTACA
 GCGC*

>DL;Sasa-DAB*1702
Sasa-DAB*1702  254 bases  
 GATGGATATT TTGAACAGGT TGTGAGTCAG TGCCGATTCT CCTCAAAGGA
 CCTGCAGGGT ACAGAGTTTA TAGACTCTTA TGTTTTCAAT AAGGCTGAAT
 ATGTCAGATT CAACAGCACT GTGGGGAAGT ATGTTGGATA CACTGAGCTG
 GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC TGGCTGTAGA
 GCTAGGGGAG CTGGAGCGTT TCTGTAAGCA AAACGCTCCT ATCGACTACA
 GCGC*

>DL;Sasa-DAB*1703
Sasa-DAB*1703  669 bases  
 ATGTCGATGT CTATCTTCTG CGTTTCCCTG ACCCTGGTTT TGTCCATATT
 CTCTGGAACA GATGGATATT TTGAACAGGT TGTGAGTCAG TGCCGATTCT
 CCTCAAAGGA CCTGCAGGGT ACAGAGTTTA TAGACTCTTA TGTTTTCAAT
 AAGGCTGAAT ATGTCAGATT CAACAGCACT GTGGGGAAGT ATGTTGGATA
 CACTGAGCTG GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC
 TGGCTGTAGA GCTAGGGGAG CTGGAGCGTT TCTGTAAGCA TAACGCTCCT
 ATCGACTACA GCGCCATACT GGACAAGACA GTTGAGCCCC ATGTCAGACT
 GAGCTCAGTG GCTCCCCCCA GTGGCAGACA CCCTGCCATG CTGATGTGCA
 GCGCCTACGA CTTCTACCCC AAACCAATCA GAGTGACCTG GCTGAGGGAC
 GGACGTGAGG TGAAGTCTGA TGTGACCTCC ACTGAGGAGC TGGCTAACGG
 GGACTGGTAC TACCAGATCC ACTCCCACCT GGAGTACACA CCCAGGTCTG
 GAGAGAAGAT CTCCTGCATG GTGGAGCACA TCAGCCTCAC TGAGCCCATG
 GTGTATCACT GGGACCCGTC CCTGCCTGAG GCTGAGAGGA ATAAGATAGC
 CATCGGTGCG TCTGGTCTG*

>DL;Sasa-DAB*1801
Sasa-DAB*1801  255 bases  
 GATGGATACT TTCATCAGAG GGTGACACAG TGCCGATACT CCTCAAAGGA
 CCTGCAGGGT ATAGAGTTTA TAGACTCTTA TGTTTTCAAT CAGGCTGAAT
 ATATCAGATT CAACAGCACT GTGGGGAAGT TTGTTGGATA CACTGAGCAT
 GGAGTGAAGA ATGCAGAAGC CTGGAACAGT GATGCTGCGG GGCTGGCTGG
 AGAGCTAGGG GAGCTGGAGC GTTTCTGTAA GCATAACGCT GATCTCCACT
 ACAGC*

>DL;Sasa-DAB*1901
Sasa-DAB*1901  254 bases  
 GATGGATATT TTTATCATAT GATGAGACAG TGCCGATACT CCTCAAAGGA
 CCTGCAGGGT ATAGAGTTGA TTACCTCGTA TGTTTTCAAT CAGGCTGAAT
 ATATCAGATT CAACAGCACT GTGGGGAAGT ATGTTGGATA CACTGAGTAT
 GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC TGGCTGGAGA
 GCTAGGGGAG CTGGAGCGTT ACTGTAAGCA TAACGCTGCT AACCACTACA
 GCGC*

>DL;Sasa-DAB*2001
Sasa-DAB*2001  669 bases  
 ATGTCGATGT CTATCTTCTG CGTTTCCCTG ACCCTGGTTT TGTCCATATT
 CTCTGGAACA GATGGATATT TTTTTCAGGT TGTGAGACAG TGCCGATACT
 CCTCAAAGGA CCTGCAGGGT ATAGAGTTTA TACACTCTTA TGTTTTCAAT
 CAGGCTGAAA ATATCAGATT CAACAGCACT GTGGGGAAGT ATGTTGGATA
 CACTGAGCTG GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC
 TGGCTGTAGA GCTAGGGGAG CTGGAGCGTT ACTGTAAGCA TAACGCTGAT
 ATCGACTACA GCGCCATACT GGACAAGACA GTTGAGCCCC ATGTCAGACT
 GAGCTCAGTG GCTCCCCCCA GTGGCAGACA CCCTGCCATG CTGATGTGCA
 GCGCCTACGA CTTCTACCCC AAACCAATCA GAGTGACCTG GCTGAGGGAC
 GGACGTGAGG TGAAGTCTGA TGTGACCTCC ACTGAGGAGC TGGCTAACGG
 GGACTGGTAC TACCAGATCC ACTCCCACCT GGAGTACACA CCCAGGTCTG
 GAGAGAAGAT CTCCTGCATG GTGGAGCACA TCAGCCTCAC TGAGCCCATG
 GTGTATCACT GGGACCCGTC CCTGCCTGAG GCTGAGAGGA ATAAGATAGC
 CATCGGTGCG TCTGGTCTG*

>DL;Sasa-DAB*2101
Sasa-DAB*2101  669 bases  
 ATGTCGATGT CTATCTTCTG CGTTTCCCTG ACCCTGGTTT TGTCCATATT
 CTCTGGAACA GATGGATATT TTTATCAGAG GGTGTCAGAG TGCCGATACT
 CCTCAAAGGA CCTGCAGGGT ATAGAGTTTA TAGACTCTTA TGTTTTCAAT
 CAGGCTGAAA ATATCAGATT CAACAGCACT GTGGGGAAGT TTGTTGGATA
 CACTGAGCTG GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC
 TGGCTGGAGA GCTAGGGGAG CTGGAGCGTT TCTGTAAGCA TAACGCTGAT
 CTCCACTACA GCACCATACT GGACAAGACA GTTGAGCCCC ATGTCAGGCT
 GAGCTCAGTG GCTCCCCCCA GTGGCAGACA CCCTGCCATG CTGATGTGCA
 GCGCCTACGA CTTCTACCCC AAACCAATCA GAGTGACCTG GCTGAGGGAC
 GGACGTGAGG TGAAATCTGA TGTGACCTCC ACTGAGGAGC TGGCTAACGG
 GGACTGGTAC TACCAGATCC ACTCCCACCT GGAGTACACA CCCAGGTCTG
 GAGAGAAGAT CTCCTGCATG GTGGAGCACA TCAGCCTCAC TGAGCCCATG
 GTGTATCACT GGGACCCGTC CCTGCCTGAG GCTGAGAGGA ATAAGATAGC
 CATCGGTGCG TCTGGTCTG*

>DL;Sasa-DAB*2201
Sasa-DAB*2201  254 bases  
 GATGGATATT TTTATCATAT GATGAGACAG TGCCGATACT CCTCAAAGGA
 CCTGCAGGGT ATAGAGTTGA TTACCTCGTA TGTTTTCAAT CAGGCTGAAA
 ATATCAGATT CAACAGCACT GTGGGGAAGT TTGTTGGATA CACTGAGCAT
 GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC TGGCTGGAGA
 GCTAGGGGAG CTGGAGCGTT TCTGTAAGCA TAACGCTCCT ATCGACTACA
 GCGC*

>DL;Sasa-DAB*2301
Sasa-DAB*2301  254 bases  
 GATGGATACT TTCATCAGAG GGTGACACAG TGCCGATACT CCTCAAAGGA
 CCTGCAGGGT ATAGAGTTTA TAGACTCTTA TGTTTTCAAT CAGGCTGAAT
 ATATCAGATT CAACAGCACT GTGGGGAAGT TTGTTGGATA CACTGAGCTG
 GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC TGGCTGGAGA
 GCTAGGGGTG CTGGAGCGTT ACTGTAAGCA TAACGCTGAT ATCGACTACA
 GCGC*

>DL;Sasa-DAB*2302
Sasa-DAB*2302  669 bases  
 ATGTCGATGT CTATCTTCTG CGTTTCCCTG ACCCTGGTTT TGTCCATATT
 CTCTGGAACA GATGGATACT TTCATCAGAG GGTGACACAG TGCCCATACT
 CCTCAAAGGA CCTGCAGGGT ATAGAGTTTA TAGACTCTTA TGTTTTCAAT
 CAGGCTGAAT ATATCAGATT CAACAGCACT GTGGGGAAGT TTGTTGGATA
 CACTGAGCTG GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC
 TGGCTGGAGA GCTAGGGGTG CTGGAGCGTT ACTGTAAGCA TAACGCTGAT
 ATCGACTACA GCGCCATACT GGACAAGACA GTTGAGCCCC ATGTCAGACT
 GAGCTCAGTG GCTCCCCCCA GTGGCAGACA CCCTGCCATG CTGATGTGCA
 GCGCCTACGA CTTCTACCCC AAACCAATCA GAGTGACCTG GCTGAGGGAC
 GGACGTGAGG TGAAGTCTGA TGTGACCTCC ACTGAGGAGC TGGCTAACGG
 GGACTGGTAC TACCAGATCC ACTCCCACCT GGAGTACACA CCCAGGTCTG
 GAGAGAAGAT CTCCTGCATG GTGGAGCACA TCAGCCTCAC TGAGCCCATG
 GTGTATCACT GGGACCCGTC CCTGCCTGAG GCTGAGAGGA ATAAGATAGC
 CATCGGTGCG TCTGGTCTG*

>DL;Sasa-DAB*2401
Sasa-DAB*2401  669 bases  
 ATGTCGATGT CTATCTTCTG CGTTTCCCTG ACCCTGGTTT TGTCCATATT
 CTCTGGAACA GATGGATATT TTTTTCAGGT TGTGAGACAG TGCCGATACT
 CCTCAAAGGA CCTGCAGGGT ATAGAGTTTA TAGACTCTTA TGTTTTCAAT
 CAGGCTGAAA ATATCAGATT CAACAGCACT GTGGGGAAGT TTGTTGGATA
 CACTGAGCTG GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC
 TGGCTAGAGC GCTAGGGGAG CTGGAGCGTT ACTGTAAGCT TAACGCTCCT
 ATCTACTACA GCGCCATACT GGACAAGACA GTTGAGCCCC ATGTCAGACT
 GAGCTCAGTG GCTCCCCCCA GTGGCAGACA CCCTGCCATG CTGATGTGCA
 GCGCCTACGA CTTCTACCCC AAACCAATCA GAGTGACCTG GCTGAGGGAC
 GGACGTGAGG TGAAGTCTGA TGTGACCTCC ACTGAGGAGC TGGCTAACGG
 GGACTGGTAC TACCAGATCC ACTCCCACCT GGAGTACACA CCCAGGTCTG
 GAGAGAAGAT CTCCTGCATG GTGGAGCACA TCAGCCTCAC TGAGCCCATG
 GTGTATCACT GGGACCCGTC CCTGCCTGAG GCTGAGAGGA ATAAGATAGC
 CATCGGTGCG TCTGGTCTG*

>DL;Sasa-DAB*2501
Sasa-DAB*2501  254 bases  
 GATGGATATT TTGAACAGGT TGTGAGTCAG TGCCGATTCT CCTCAAAGGA
 CCTGCAGGGT ATAGAGTTTA TACACTCTTA TGTTTTCAAT AAGGCTGAAT
 ATATCAGATT CAACAGCACT GTGGGGAAGT ATGTTGGATA CACTGAGCTG
 GGAGTGAAGA ATGCAGAAGC TTGGAACAAA GGTCCTGAGC TGGCTGGAGA
 GCTAGGGGAG CTGGAGCGTT TCTGTAAGCA TAACGCTCCT ATCGACTACA
 GCGC*

>DL;Sasa-DAB*2601
Sasa-DAB*2601  669 bases  
 ATGTCGATGT CTATCTTCTG CGTTTCCCTG ACCCTGGTTT TGTCCATATT
 CTCTGGAACA GATGGATATT TTGAACAGGT TGTGAGTCAG TGCCGATTCT
 CCTCAAAGGA CCTGCAGGGT ATAGAGTTTA TACACTCTTA TGTTTTCAAT
 AAGGCTGAAT ATATCAGATT CAACAGCACT GTGGGGAAGT ATGTTGGATA
 CACTGAGCTG GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC
 TGGCTGGAGA GCTAGGGGAG CTGGAGCGTT TCTGTAAGCA TAACGCTGAT
 CTCCACTACA GCACCATACT GGACAAGACA GTTGAGCCCC ATGTCAGACT
 GAGCTCAGTG GCTCCCCCCA GTGGCAGACA CCCTGCCATG CTGATGTGCA
 GCGCCTACGA CTTCTACCCC AAACCAATCA GAGTGACCTG GCTGAGGGAC
 GGACGTGAGG TGAAGTCTGA TGTGACCTCC ACTGAGGAGC TGGCTAACGG
 GGACTGGTAC TACCAGATCC ACTCCCACCT GGAGTACACA CCCAGGTCTG
 GAGAGAAGAT CTCCTGCATG GTGGAGCACA TCAGCCTCAC TGAGCCCATG
 GTGTATCACT GGGACCCGTC CCTGCCTGAG GCTGAGAGGA ATAAGATAGC
 CATCGGTGCG TCTGGTCTG*

>DL;Sasa-DAB*2701
Sasa-DAB*2701  669 bases  
 ATGTCGATGT CTATCTTCTG CGTTTCCCTG ACCCTGGTTT TGTCCATATT
 CTCTGGAACA GATGGATATT TTTATCATAT GATGAGACAG TGCCGATACT
 CCTCAAAGGA CCTGCAGGGT ATAGAGTTGA TTACCTCGTA TGTTTTCAAT
 CAGGCTGAAA ATATCAGATT CAACAGCACT GTGGGGAAGT TTGTTGGATA
 CACTGAGCTG GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC
 TGGCTGGAGA GCTAGGGGTG CTGGAGCGTT ACTGTAAGCT TAACGCTCCT
 ATCTACTACA GCACCATACT GGACAAGACA GTTGAGCCCC ATGTCAGACT
 GAGCTCAGTG GCTCCCCCCA GTGGCAGACA CCCTGCCATG CTGATGTGCA
 GCGCCTACGA CTTCTTCCCC AAACCAATCA GAGTGACCTG GCTGAGGGAC
 GGACGTGAGG TGAAGTCTGA TGTGACCTCC ACTGAGGAGC TGGCTAACGG
 GGACTGGTAC TACCAGATCC ACTCCCACCT GGAGTACACA CCCAGGTCTG
 GAGAGAAGAT CTCCTGCATG GTGGAGCACA TCAGCCTCAC TGAGCCCATG
 GTGTATCACT GGGACCCGTC CCTGCCTGAG GCTGAGAGGA ATAAGATAGC
 CATCGGTGCG TCTGGTCTG*

>DL;Sasa-DAB*2801
Sasa-DAB*2801  669 bases  
 ATGTCGATGT CTATCTTCTG CGTTTCCCTG ACCCTGGTTT TGTCCATATT
 CTCTGGAACA GATGGATATT TTGAACAGGT TGTGAGTCAG TGCCGATTCT
 CCTCAAAGGA CCTGCAGGGT ATAGAGTTTA TACACTCTTA TGTTTTCAAT
 AAGGCTGAAT ATATCAGATT CAACAGCACT GTGGGGAAGT ATGTTGGATA
 CACTGAGCTG GGAGTGAAGA ATGCAGAAGC CTGGAACAAA GGTCCTGAGC
 TGGCTGGAGA GCTAGGGGAG CTGGAGCGTT ACTGTAAGCT TAACGCTCCT
 ATCGACTACA GCGCCATACT GGACAAGACA GTTGAGCCCC ATGTCAGACT
 GAGCTCAGTG GCTCCCCCCA GTGGCAGACA CCCTGCCATG CTGATGTGCA
 GCGCCTACGA CTTCTACCCC AAACCAATCA GAGTGACCTG GCTGAGGGAC
 GGACGTGAGG TGAAGTCTGA TGTGACCTCC ACTGAGGAGC TGGCTAACGG
 GGACTGGTAC TACCAGATCC ACTCCCACCT GGAGTACACA CCCAGGTCTG
 GAGAGAAGAT CTCCTGCATG GTGGAGCACA TCAGCCTCAC TGAGCCCATG
 GTGTATCACT GGGACCCGTC CCTGCCTGAG GCTGAGAGGA ATAAGATAGC
 CATCGGTGCG TCTGGTCTG*

