>P1;Sasa-DAB*0101
Sasa-DAB*0101  244 bases  
 MSIFCVSLTL VLSIFSGTDG YFEQVVRQCR YSSKDLQGIE FIDSYVFNKA
 EYIRFNSTVG KFVGYTELGV KNAEAWNSDA AVLAVERGEL ERYCKHNADL
 HYSTILDKTV EPHVRLSSVA PPSGRHPAML MCSAYDFYPK PIRVTWLRDG
 REVKSDVTST EELANGDWYY QIHSHLEYTP RSGEKISCMV EHISLTEPMV
 YHWDPSLPEA ERNKIAIGAS GLVLGAILAL AGLIYYKKKS SGVL*

>P1;Sasa-DAB*0102
Sasa-DAB*0102  224 bases  
 MSMSIFCVSL TLVLSIFSGT DGYFEQVVRQ CRYSSKDLQG IELIDSYVFN
 KAEYIRFNST VGKFVGYTEL GVKNAEAWNS DAAVLAVERG ELERYCKHNA
 DLHYSTILDK TVEPHVRLSS VAPPSGRHPA MLMCSAYDFY PKPIRVTWLR
 DGREVKSDVT STEELANGDW YYQIHSHLEY TPRSGEKISC MVEHISLTEP
 MVYHWDPSLP EAERNKIAIG ASGL*

>P1;Sasa-DAB*0201
Sasa-DAB*0201  223 bases  
 MSMSIFCVSL TLVLSIFSGT DGYFEQVVRQ CRYSSKDLQG IEFIDSYVFN
 KAEYVRFNST VGKYVGYTEL GVKNAEAWNK GPELAVELGE LERFCKHNAA
 IYYSAILDKT VEPHVRLSSV APPSGRHPAM LMCSAYDFYP KPIRVTWLRD
 GREVKSDVTS TEELANGDWY YQIHSHLEYT PRSGEKISCM VEHISLTEPM
 VYHWDPSLPE AERNKIAIGA SGL*

>P1;Sasa-DAB*0202
Sasa-DAB*0202  209 bases  
 VSLTLVLSIF SGTDGYFEHV VRQCRYSSKD LQGIEFIDSY VFNKAEYVRF
 NSTVGKYVGY TELGVKNAEA WNKGPELAVE LGELERFCKH NAAIYYSAIL
 DKTVEPHVRL SSVAPPSGRH PAMLMCSAYD FYPKPIRVTW LRDGREVKSD
 VTSTEELANG DWYYQIHSHL EYTPRSGEKI SCMVEHISLT EPMVYHWDPS
 LPEAERNKI*

>P1;Sasa-DAB*0301
Sasa-DAB*0301  223 bases  
 MSMSIFCVSL TLVLSIFSGT DGYFYHMMRQ CRYSSKDLQG IELITSYVFN
 QAEYIRFNST VGKYVGYTEY GVKNAEAWNK GPELAGELGE LERVCKHNAP
 IDYSAILDKT VEPHVRLSSV APPSGRHPAM LMCSAYDFFP KPIRVTWLRD
 GREVKSDVTS TEELANGDWY YQIHSHLEYT PRSGEKISCM VEHISLTEPM
 VYHWDPSLPE AERNKIAIGA SGL*

>P1;Sasa-DAB*0302
Sasa-DAB*0302  85 bases  
 DGYFYHMMRQ CRYSSKDLQG IELITSYVFN QAEYIRFNST VGKYVGYTEY
 GVKNAEAWNK GPELAGELGE LERVCKHNAP IYYSA*

>P1;Sasa-DAB*0303
Sasa-DAB*0303  223 bases  
 MSMSIFCVSL TLVLSIFSGT DGYFYHMMRQ CRYSSKDLQG IELITSYVFN
 QAEYIRFNST VGKYVGYTEY GVKNAEAWNK GPELAGELGV LERYCKHNAP
 IYYSAILDKT VEPHVRLSSV APPSGRHPAM LMCSAYDFFP KPIRVTWLRD
 GREVKSDVTS TEELANGDWY YQIHSHLEYT PRSGEKISCM VEHISLTEPM
 VYHWDPSLPE AERNKIAIGA SGL*

>P1;Sasa-DAB*0401
Sasa-DAB*0401  223 bases  
 MSMSIFCVSL TLVLSIFSGT DGYFFQVVRQ CRYSSKDLQG IEFIHSYVFN
 QAENIRFNST VGKYVGYTEL GVKNAEAWNK GPELAGELGE LERFCKHNAD
 LHYSTILDKT VEPHVRLSSV APPSGRHPAM LMCSAYDFYP KPIRVTWLRD
 GREVKSDVTS TEELANGDWY YQIHSHLEYT PRSGEKISCM VEHISLTEPM
 VYHWDPSLPE AERNKIAIGA SGL*

>P1;Sasa-DAB*0501
Sasa-DAB*0501  223 bases  
 MSMSIFCVSL TLVLSIFSGT DGYFYQVVRQ CRYSSKDLQG IEFIDSYVFN
 KAEYVRFNST VGKYVGYTEY GVKNAEAWNK GPELAGELGE LERYCKHNAP
 IYYSAILDKT VEPHVRLSSV APPSGRHPAM LICSAYDFYP KPIRVTWLRD
 GREVKSDVTS TEELANGDWY YQIHSHLEYT PRSGEKISCM VEHISLTEPM
 VYHWDPSLPE AERNKIAIGA SGL*

>P1;Sasa-DAB*0601
Sasa-DAB*0601  245 bases  
 MSMSIFCVSL TLVLSIFSGT DGYFYHMMTQ CRYSSKDLQG IELITSYVFN
 QAENIRFNST VGKFVGYTEH GVKNAEAWNK GPELAGELGV LERYCKFNAP
 IDYSAILDKT VEPHVRLSSV APPSGRHPAM LMCSAYDFFP KPIRVTWLRD
 GREVKSDVTS TEELANGDWY YQIHSHLEYT PRSGEKISCM VEHISLTEPM
 VYHWDPSLPE AERNKIAIGA SGLVLGAILA LAGLIYYKKK SSGVL*

>P1;Sasa-DAB*0701
Sasa-DAB*0701  245 bases  
 MSMSIFCVSL TLVLSIFSGT DGYFEQVVRQ CRYSSKDLQG IEFIDSYVFN
 KAEYVRFNST VGKYVGYTEL GVKNAEAWNK GPELAVELGE LERFCKHNAD
 LHYRAILDKT VEPHVRLSSV APPSGRHPAM LMCSAYDFYP KPIRVTWLRD
 GREVKSDVTS TEELANGDWY YQIHSHLEYT PRSGEKISCM VEHISLTEPM
 VYHWDPSLPE AERNKIAIGA SGLVLGAILA LAGLIYYKKK SSGVL*

>P1;Sasa-DAB*0801
Sasa-DAB*0801  223 bases  
 MSMSIFCVSL TLVLSIFSGT DGYFYQRVSE CRYSSKDLQG IEFIDSYVFN
 KAEYVRFNST VGKYVGYTEY GVKNAEAWNK GPELAGELGE LERVCKHNAP
 IDYSAILDKT VEPHVRLSSV APPSGRHPAM LMCSAYDFFP KPIRVTWLRD
 GREVKSDVTS TEELANGDWY YQIHSHLEYT PRSGEKISCM VEHISLTEPM
 VYHWDPSLPE AERNKIAIGA SGL*

>P1;Sasa-DAB*0802
Sasa-DAB*0802  209 bases  
 VSLTLVLSIF SGTDGYFYQR VSECRYSSKD LQGIEFIDSY VFNKAEYVRF
 NSTVGKYVGY TEYGVKNAEA WNKGPELAGE LGELERVCKH NAPIYYSAIL
 DKTVEPHVRL SSVAPPSGRH PAMLMCSAYD FFPKPIRVTW LRDGREVKSD
 VTSTEELANG DWYYQIHSHL EYTPRSGEKI SCMVEHISLT EPMVYHWDPS
 LPEAERNKI*

>P1;Sasa-DAB*0901
Sasa-DAB*0901  209 bases  
 VSLTLVLSIF SGTDGYFEQV VRQCRYSSKD LQGIEFIDSY VFNKAEYVRF
 NSTVGKYVGY TELGVKNAEA WNKGPELAVE LGELERYCKL NAPIDYSAIL
 DKTVEPHVRL SSVAPPSGRH PAMLMCSAYD FYPKPIRVTW LRDGREVKSD
 VTSTEELANG DWYYQIHSHL EYTPRSGEKI SCMVEHISLT EPMVYHWDPS
 LPEAERNKI*

>P1;Sasa-DAB*0902
Sasa-DAB*0902  209 bases  
 VSLTLVLSIF SGTDGYFEQV VRQCRYSSKD LQGIEFIDSY VFNKAEYVRF
 NSTVGKFVGY TELGVKNAEA WNKGPELAVE LGELERYCKL NAPIDYSAIL
 DKTVEPHVRL SSVAPPSGRH PAMLMCSAYD FYPKPIRVTW LRDGREVKSD
 VTSTEELANG DWYYQIHSHL EYTPRSGEKI SCMVEHISLT EPMVYHWDPS
 LPEAERNKI*

>P1;Sasa-DAB*1001
Sasa-DAB*1001  209 bases  
 VSLTLVLSIF SGTDGYFHQR VTQCRYSSKD LQGIEFIDSY VFNQAEYIRF
 NSTVGKFVGY TELGVKNAEA LNKGPELAVE LGELERYCKL NAPIDYSAIL
 DKTVEPHVRL SSVAPPSGRH PAMLMCSAYD FYPKPIRVTW LRDGREVKSD
 VTSTEELANG DWYYQIHSHL EYTPRSGEKI SCMVEHISLT EPMVYHWDPS
 LPEAERNKI*

>P1;Sasa-DAB*1101
Sasa-DAB*1101  209 bases  
 VSLTLVLSIF SGTDGYFHQR VTQCRYSSKD LQGIEFIDSY VFNQAEYIRF
 NSTVGKFVGY TEHGVKNAEA WNKGPELAGE LGELERYCKF NAPIYYSAIL
 DKTVEPHVRL SSVAPPSGRH PAMLMCSAYD FYPKPIRVTW LRDGREVKSD
 VTSTEELANG DWYYQIHSHL EYTPRSGEKI SCMVEHISLT EPMVYHWDPS
 LPEAERNKI*

>P1;Sasa-DAB*1102
Sasa-DAB*1102  85 bases  
 DGYFHQRVTQ CRYSSKDLQG IEFIDSYVFN QAEYIRFNST VGKFVGYTEH
 GVKNAEAWNK GPELAGELGE LERVCKHNAP IYYSA*

>P1;Sasa-DAB*1201
Sasa-DAB*1201  209 bases  
 VSLTLVLSIF SGTDGYFEQV VRQCRYSSKD LQGIEFIDSY VFNKAEYIRF
 NSTVGKYVGY TEYGVKNAEA WNKGPELARA LGELERVCKH NAPIYYSAIL
 DKTVEPHVRL SSVAPPSGRH PAMLMCSAYD FYPKPIRVTW LRDGREVKSD
 VTSTEELANG DWYYQIHSHL EYTPRSGEKI SCMVEHISLT EPMVYHWDPS
 LPEAERNKI*

>P1;Sasa-DAB*1202
Sasa-DAB*1202  85 bases  
 DGYFEQVVRQ CRYSSKDLQG IEFIDSYVFN KAEYIRFNST VGKYVGYTEY
 GVKNAEAWNK GPELARALGE LERYCKFNAP IYYSA*

>P1;Sasa-DAB*1301
Sasa-DAB*1301  85 bases  
 DGYFYHMMRQ CRYSSKDLQG IELITSYVFN QAENIRFNST VGKFVGYTEL
 GVKNAEAWNK GPELAGELGV LERFCKHNAD LHYST*

>P1;Sasa-DAB*1302
Sasa-DAB*1302  85 bases  
 DGYFYHMMRQ CRYSSKDLQG IELITSYVFN QAENIRFNST VGKFVGYTEH
 GVKNAEAWNK GPELAGELGE LERFCKHNAD LHYST*

>P1;Sasa-DAB*1303
Sasa-DAB*1303  223 bases  
 MSMSIFCVSL TLVLSIFSGT DGYFYHMMRQ CRYSSKDLQG IELITSYVFN
 QAENIRFNST VGKFVGYTEH GVKNAEAWNK GPELAGELGE LERVCKHNAD
 LHYSTILDKT VEPHVRLSSV APPSGRHPAM LMCSAYDFFP KPIRVTWLRD
 GREVKSDVTS TEELANGDWY YQIHSHLEYT PRSGEKISCM VEHISLTEPM
 VYHWDPSLPE AERNKIAIGA SGL*

>P1;Sasa-DAB*1401
Sasa-DAB*1401  85 bases  
 DGYFYQVVRQ CRYSSKDLQG IEFIDSYVFN QAEYIRFNST VGKFVGYTEH
 GVKNAEAWNK GPELAVELGE LERYCKHNAD LHYST*

>P1;Sasa-DAB*1501
Sasa-DAB*1501  85 bases  
 DGYFYQVVRQ CRYSSKDLQG IEFIDSYVFN QAEYIRFNST VGKFVGYTEH
 GVKNAEAWNK GPELAVELGE LERFCKHNAP IDYSA*

>P1;Sasa-DAB*1502
Sasa-DAB*1502  223 bases  
 MSMSIFCVSL TLVLSIFSGT DGYFYQVVRQ CRYSSKDLQG IEFIDSYVFN
 QAEYIRFNST VGKFVGYTEH GVKNAEAWNK GPELAGELGE LERYCKLNAP
 IDYSAILDKT VEPHVRLSSV APPSGRHPAM LMCSAYDFYP KPIRVTWLRD
 GREVKSDVTS TEELANGDWY YQIHSHLEYT PRSGEKISCM VEHISLTEPM
 VYHWDPSLPE AERNKIAIGA SGL*

>P1;Sasa-DAB*1601
Sasa-DAB*1601  85 bases  
 DGYFEQVVRQ CRYSSKDLQG IEFIDSYVFN QAEYIRFNST VGKFVGYTEL
 GVKNAEAWNK GPELAVELGE LERYCKLNAP IDYSA*

>P1;Sasa-DAB*1701
Sasa-DAB*1701  85 bases  
 DGYFEQVVRQ CRFSSKDLQG TEFIDSYVFN KAEYVRFNST VGKYVGYTEL
 GVKNAEAWNK GPELAGELGE LERFCKHNAP IDYSA*

>P1;Sasa-DAB*1702
Sasa-DAB*1702  85 bases  
 DGYFEQVVSQ CRFSSKDLQG TEFIDSYVFN KAEYVRFNST VGKYVGYTEL
 GVKNAEAWNK GPELAVELGE LERFCKQNAP IDYSA*

>P1;Sasa-DAB*1703
Sasa-DAB*1703  223 bases  
 MSMSIFCVSL TLVLSIFSGT DGYFEQVVSQ CRFSSKDLQG TEFIDSYVFN
 KAEYVRFNST VGKYVGYTEL GVKNAEAWNK GPELAVELGE LERFCKHNAP
 IDYSAILDKT VEPHVRLSSV APPSGRHPAM LMCSAYDFYP KPIRVTWLRD
 GREVKSDVTS TEELANGDWY YQIHSHLEYT PRSGEKISCM VEHISLTEPM
 VYHWDPSLPE AERNKIAIGA SGL*

>P1;Sasa-DAB*1801
Sasa-DAB*1801  85 bases  
 DGYFHQRVTQ CRYSSKDLQG IEFIDSYVFN QAEYIRFNST VGKFVGYTEH
 GVKNAEAWNS DAAGLAGELG ELERFCKHNA DLHYS*

>P1;Sasa-DAB*1901
Sasa-DAB*1901  85 bases  
 DGYFYHMMRQ CRYSSKDLQG IELITSYVFN QAEYIRFNST VGKYVGYTEY
 GVKNAEAWNK GPELAGELGE LERYCKHNAA NHYSA*

>P1;Sasa-DAB*2001
Sasa-DAB*2001  223 bases  
 MSMSIFCVSL TLVLSIFSGT DGYFFQVVRQ CRYSSKDLQG IEFIHSYVFN
 QAENIRFNST VGKYVGYTEL GVKNAEAWNK GPELAVELGE LERYCKHNAD
 IDYSAILDKT VEPHVRLSSV APPSGRHPAM LMCSAYDFYP KPIRVTWLRD
 GREVKSDVTS TEELANGDWY YQIHSHLEYT PRSGEKISCM VEHISLTEPM
 VYHWDPSLPE AERNKIAIGA SGL*

>P1;Sasa-DAB*2101
Sasa-DAB*2101  223 bases  
 MSMSIFCVSL TLVLSIFSGT DGYFYQRVSE CRYSSKDLQG IEFIDSYVFN
 QAENIRFNST VGKFVGYTEL GVKNAEAWNK GPELAGELGE LERFCKHNAD
 LHYSTILDKT VEPHVRLSSV APPSGRHPAM LMCSAYDFYP KPIRVTWLRD
 GREVKSDVTS TEELANGDWY YQIHSHLEYT PRSGEKISCM VEHISLTEPM
 VYHWDPSLPE AERNKIAIGA SGL*

>P1;Sasa-DAB*2201
Sasa-DAB*2201  85 bases  
 DGYFYHMMRQ CRYSSKDLQG IELITSYVFN QAENIRFNST VGKFVGYTEH
 GVKNAEAWNK GPELAGELGE LERFCKHNAP IDYSA*

>P1;Sasa-DAB*2301
Sasa-DAB*2301  85 bases  
 DGYFHQRVTQ CRYSSKDLQG IEFIDSYVFN QAEYIRFNST VGKFVGYTEL
 GVKNAEAWNK GPELAGELGV LERYCKHNAD IDYSA*

>P1;Sasa-DAB*2302
Sasa-DAB*2302  223 bases  
 MSMSIFCVSL TLVLSIFSGT DGYFHQRVTQ CPYSSKDLQG IEFIDSYVFN
 QAEYIRFNST VGKFVGYTEL GVKNAEAWNK GPELAGELGV LERYCKHNAD
 IDYSAILDKT VEPHVRLSSV APPSGRHPAM LMCSAYDFYP KPIRVTWLRD
 GREVKSDVTS TEELANGDWY YQIHSHLEYT PRSGEKISCM VEHISLTEPM
 VYHWDPSLPE AERNKIAIGA SGL*

>P1;Sasa-DAB*2401
Sasa-DAB*2401  223 bases  
 MSMSIFCVSL TLVLSIFSGT DGYFFQVVRQ CRYSSKDLQG IEFIDSYVFN
 QAENIRFNST VGKFVGYTEL GVKNAEAWNK GPELARALGE LERYCKLNAP
 IYYSAILDKT VEPHVRLSSV APPSGRHPAM LMCSAYDFYP KPIRVTWLRD
 GREVKSDVTS TEELANGDWY YQIHSHLEYT PRSGEKISCM VEHISLTEPM
 VYHWDPSLPE AERNKIAIGA SGL*

>P1;Sasa-DAB*2501
Sasa-DAB*2501  85 bases  
 DGYFEQVVSQ CRFSSKDLQG IEFIHSYVFN KAEYIRFNST VGKYVGYTEL
 GVKNAEAWNK GPELAGELGE LERFCKHNAP IDYSA*

>P1;Sasa-DAB*2601
Sasa-DAB*2601  223 bases  
 MSMSIFCVSL TLVLSIFSGT DGYFEQVVSQ CRFSSKDLQG IEFIHSYVFN
 KAEYIRFNST VGKYVGYTEL GVKNAEAWNK GPELAGELGE LERFCKHNAD
 LHYSTILDKT VEPHVRLSSV APPSGRHPAM LMCSAYDFYP KPIRVTWLRD
 GREVKSDVTS TEELANGDWY YQIHSHLEYT PRSGEKISCM VEHISLTEPM
 VYHWDPSLPE AERNKIAIGA SGL*

>P1;Sasa-DAB*2701
Sasa-DAB*2701  223 bases  
 MSMSIFCVSL TLVLSIFSGT DGYFYHMMRQ CRYSSKDLQG IELITSYVFN
 QAENIRFNST VGKFVGYTEL GVKNAEAWNK GPELAGELGV LERYCKLNAP
 IYYSTILDKT VEPHVRLSSV APPSGRHPAM LMCSAYDFFP KPIRVTWLRD
 GREVKSDVTS TEELANGDWY YQIHSHLEYT PRSGEKISCM VEHISLTEPM
 VYHWDPSLPE AERNKIAIGA SGL*

>P1;Sasa-DAB*2801
Sasa-DAB*2801  223 bases  
 MSMSIFCVSL TLVLSIFSGT DGYFEQVVSQ CRFSSKDLQG IEFIHSYVFN
 KAEYIRFNST VGKYVGYTEL GVKNAEAWNK GPELAGELGE LERYCKLNAP
 IDYSAILDKT VEPHVRLSSV APPSGRHPAM LMCSAYDFYP KPIRVTWLRD
 GREVKSDVTS TEELANGDWY YQIHSHLEYT PRSGEKISCM VEHISLTEPM
 VYHWDPSLPE AERNKIAIGA SGL*

