>P1;Sasa-UBA*0101
Sasa-UBA*0101  356 bases  
 MKGFILLVLG IGLLHTASAV THALKYFYTA SSEVPNFPEF VVVGVVDGVQ
 MVHYDSNSQR AVPKQDWVNK AADPQYWERN TGIFKGSQQT FKANIDIAKQ
 RFNQSGGVHV NQWMYGCEWD DEAGVTEGFE QWGYDGEDFI AFDLKTKSWI
 APTPQSVITK LKWDSDTAQN EHDKHYLTQT CIEWLKKYLD YGKSTLMRTV
 PPSVSLLQKT PSSPVTCHAT GFYPSGVMVS WQKDGQDHHE DVEYGETLQN
 DDGTFQKSSH LTVTPEEWKN NKYQCVVQVT GVKEDFIKVL TESEIKTNWN
 EPNIVLIIVV VVALLLLVVA VVVGVVIWKK KSKKGFVPAS TSDTDSDNSG
 RAAQMT*

>P1;Sasa-UBA*0201
Sasa-UBA*0201  353 bases  
 FILLVLGIVL LHTVSAATNT LQYFYTATSG IDNFPEFVTM GIVNGHQIDH
 YDSITKRAIQ KAEWISGAVD PDYWKTNTQI YAGTETVFVN NINVAKSRFN
 QTGGVHVNQK MYGCEWDDET GVTEGFDQDG YDGEDFLAFD LKTLTWIAPT
 PQAVITKLKW DSNTAQNEYR KNYLTQTCIE WLKKYLDYGK STLMRTVPPS
 VSLLQKTPSS PVTCHATGFY PSGVMVSWQK DGQDHHEDVE HGETLQNDDG
 TFQKSSHLTV TPEEWKNNKY QCVVQVTGLQ EDFIKVLTES EIKTNWNDPN
 IVLIIGVVVA LLLVVVAVVV GVVIWKKKSK KGFVPASTSD TDSDNSGRAA
 QMT*

>P1;Sasa-UBA*0301
Sasa-UBA*0301  355 bases  
 MKCFILLLLG IALHSSSAAT HSLRYVYTAT SGIPDFPEFV TVGLVNGEPI
 SYYDSIIRRE TPRQDWMAKT EGSDYWESQT QVSIGSEQTF KANIDVAKQR
 FNQTGGVHVN QKMYGCEWDD ETGVTEGFDQ DGYDGEDFLA FDLKTLTWIA
 PTPQAVITKL KWDSNTAQNE YRKNYLTQTC IEWLKKYLDY GKSTLMRTVP
 PSVSLLQKTP SSPVTCHATG FYPSGVMVSW QKDGQDHHED VEHGETLQND
 DGTFQKSSHL TVTPEEWKNN KYQCVVQVTG LQEDFIKVLT ESEIKTNWND
 PNIVLIIGVV VALLLVVVAV VVGVVIWKKK SKKGFVPAST SDTDSDNSGR
 AAQMT*

>P1;Sasa-UBA*0401
Sasa-UBA*0401  355 bases  
 FIXLVXGIGL LHTASAVTHS LKYFYTASSE VPNFPEFVVV SMVDGVQMVH
 YDSNSQRAVP KQDWMNKAAE ALPQYWDIET GKFLGSHQSF KANIDICKQR
 FNQSGGVHVF QKMYGCEWDD EAGATEGLTQ YGYDGEDFIA FDLKTKSXIA
 PTPQSLITKL KWDSDTAYNE QEKNYLTQIC IEWLKKYVDY GKSTLMRTVP
 PSVSLLQKTP SSPVTCHATG FYPSGVMVSW QKDGQDHHED VEYGETLQND
 DGTFQKSSHL TVTPEEWKNN KYQCVVQVTG VKEDFIKVLT ESEIKTNWND
 PNIVLIIVVV VALLLLVVAV VVGVVIWKKK SKKGFVPAST SDTDSDNSGR
 AAQMT*

>P1;Sasa-UBA*0402
Sasa-UBA*0402  183 bases  
 VTHSLKYFYT ASSEVPNFPE FVVVSMVDGV QMVHYDSNSQ RAVPKQDCIN
 KAAEALPQYW DIETGKFLGS HQSFKANIDI CKQRFNQSGG VHVFQKMYGC
 EWDDEAGATE GLTQYGYDGE DFIAFDLKTK SWIAPTPQSL ITKLKWDSDT
 AYNEQEKNYL TQICIEWLKK YVDYGKSTLM RTV*

>P1;Sasa-UBA*0501
Sasa-UBA*0501  353 bases  
 FILLVLGIGL LHTASAVTHA LKYFYTASSE VPNFPEFVVV GVVDGVQMVH
 YDSNSQRAVP KQDWVNKAAD PQYWERNTGI FKGSQQTFKA NIDIAKQRFN
 QSGGVHVNQR MYGCEWDDET GVTEGFNQDG YDGEDFIAFD LKTLKWIAPT
 PQAVITKLKW DNNMAQIQQD KHYLTQTCIE WLKKYLDYGK STLMRTVPPS
 VSLLQKTPSS PVTCHATGFY PSGVMVSWQK DGQDHHEDVE HGETLQNDDG
 TFQKSSHLTV TPEEWKNNKY QCVVQVTGLQ EDFIKVLTES EIKTNWNDPN
 IVLIIVVVVA LLLLVVAVVV GVVIWKKKSK KGFVPASTSD TDSDNSGRAA
 QMT*

>P1;Sasa-UBA*0601
Sasa-UBA*0601  355 bases  
 FILLVLGIGL LHTASAATHS LKYFYTAVSG DIDFPEFTIV GLVNNGQFVY
 YDSNIKRMVP KTEWMKQSAG ADYWDTESEK QVGQNQGFKN NIQVLKDRFN
 QSMSTGVHVN QWMYGCEWDD EAGVTEGFEQ WGYDGEDFIA FDLKTKSWIA
 PTPQAVITKL KWDSDTAQNE HRKNYYTQIC IEWLKKYVDY GKSTLMRTVP
 PSVSLLQKTP SSPVTCHATG FYPSGVMVSW QKDGQDHHED VEYGETLQND
 DGTFQKSSHL TVTPEEWKNN KYQCVVQVTG VKEDFIKVLT ESEIKTNWND
 PNIVLIIVVV VALLLLVVAV VVGVVIWKKK SKKGFVPAST SDTDSDNSGR
 AAQMT*

>P1;Sasa-UBA*0602
Sasa-UBA*0602  183 bases  
 ATHSLKYFYT AVSGDIDFPE FTIVGLVNNG QFVYYDSNIK RMVPKTEWMK
 QSAGADYWDT ESEKQVGQNQ GFKNNIQVPK DRFNQSMSTG VHVNQWMYGC
 EWDDEAGVTE GFEQWGYDGE DFIAFDLKTK SWIAPTPQAV ITKLKWDSDT
 AQNEHRKNYY TQICIEWLKK YVDYGKSTLM RTV*

>P1;Sasa-UBA*0603
Sasa-UBA*0603  350 bases  
 LGIGLLHTAS AATHSLKYFY TAVSGDIDFP EFTIVGLVNN GQFVYYDSNI
 KRMVPKTEWM KQSAGADYWD TESEKQVGQN QGFKNNIQVL KDRFNQSMST
 GVHVSQWMYG CEWDDEAGVT EGFEQWGYDG EDFIAFDLKT KSWIVPTPQA
 VITKLKWDSD TAQNEHRKNH YTQICIEWLK KYVDYGKSTL MRTVPPSVSL
 LQKTPSSPVT CHATGFYPSG VMVSWQKDGQ DHHEDVEYGE TLQNDDGTFQ
 KSSHLTVTPE EWKNNKYQCV VQVTGVKEDF IKVLTESEIK TNWNDPNIVL
 IIVVVVALLL LVVAVVVGVV IWKKKSKKGF VPASTSDTDS DNSGRAAQMT*

>P1;Sasa-UBA*0701
Sasa-UBA*0701  355 bases  
 FILLVLGIGL LHTASAATHS LKYFYTAVSG DIDFPEFTIV GLVNNGQFVY
 YDSNIKRMVP KTEWMKQSAG ADYWDTESEK QVGQNQGFKN NIQVLKDRFN
 QSMSTGVHVF QVMYGCEWDD EAGATEGFDQ YGYDGEDFLA FDLKTLKWIA
 PTPQAVITKL KWDSDTAQNE YRKNYYTQTC IEWLKKYVDY GKSTLMRTVP
 PSVSLLQKTP SSPVTCHATG FYPSGVMVSW QKDGQDHHED VEHGETLQND
 DGTFQKSSHL TVTPEEWKNN KYQCVVQVTG IKDDIIKVLT ESEIKTNWND
 PNIVLIIGVV VALLLLVVAA VAGVVIWKKK SKKGFVPAST SDTDSDNSGR
 AAQMT*

>P1;Sasa-UBA*0702
Sasa-UBA*0702  183 bases  
 ATHSLKYFYT AVSGDIDFPE FTIVGLVNNG QFVYYDSNIK RMVPKTEWMK
 QSAGADYWDT ESEKQVGQNQ GFKNNIQVPK DRFNQSMSTG VHVFQVMYGC
 EWDDEAGATE GFDQYGYDGE DFLAFDLKTL KWIAPTPQAV ITKLKWDSDT
 AQNEYRKNYY TQTCIEWLKK YVDYGKSTLM RTV*

>P1;Sasa-UBA*0801
Sasa-UBA*0801  353 bases  
 FILLVLGIGL LHTASAATHS LRYVYTATSG IPDFPEFVNL GIVDGMQIDY
 YDSNTKRAVP KQDWMAKTEG SDYWDRQTQV SIGSEQTFKA NIDIVKQRFN
 QTGGVHVNQN MYGCEWDDEA GVTEGFDQYG YDGEDFLAFD LKTLKWIAPT
 PQSLITKLKW DNNMAQIQQD KHYLTQTCIE WLKKYLDYGK STLMRTVPPS
 VSLLQKTPSS PVTCHATGFY PSGVMVSWQK DGQDHHEDVE HGETLQNDDG
 TFQKSSHLTV TPEEWKNNKY QCVVQVTGLQ EDFIKVLTES EIKTNWNDPN
 IVLIIVVVVA LLLLVVAVVV GVVIWKKKSK KGFVPASTSD TDSDNSGRAA
 QMT*

>P1;Sasa-UBA*0901
Sasa-UBA*0901  349 bases  
 FILLVLGIGL LHTASAVTHS LRYFYTATTG IPDFPEFVDV GVVNGKVISY
 YDSIIKRKVP KQSWMEENLN QQYWNQGTDQ LKGTEQSFKA NIQVAQTRFN
 QTGGVHIFQY MYGCTWDDDS GVTDGLRQYG YDGEDFLVYD MKAFTWIAPK
 LQAEITTRKW NNEPAQMEYL KSYITQECVE WLKKYVDYGK NTLMRTVPPS
 VSLLQKSPSS PVTCHATGFY PSGVMVFWQK DGQDQHEDVE YGETLPNHDG
 TFQKSSHLTV TPEDRKNNKY QCVVQVTGIK DDFIKVLTDL DDPTPNIVPI
 IVVVVALLLV VVAVVVGVVI WKKKSKKGFV PASTSDTDSE NSGKGAQKI*

>P1;Sasa-UBA*1001
Sasa-UBA*1001  352 bases  
 FILLLLGIAL HSSSAVIHSW KAFLTASTGL SDFPEFVALN LVDDELMGYF
 DTKTNRFEGK QSWVEEKLGQ QYLEQQENIL RSTSQSFKVN VGIAMERFNQ
 TKGVHVFQNM YGCEWDDETG VTEGFDQDGY DGEDFLAFDL KTLTWIAPTP
 QAVNTKHKWD SNTAYNEQEK NYLTQICIEW LKKYVDYGKS TLMRTVPPSV
 SLLQKTPSSP VTCHATGFYP SGVMVSWQKD GQDHHEDVEY GETLQNDDGT
 FQKSSHLTVT PEEWKNNKYQ CVVQVTGLQE DFIKVLTESE IKTNWNDPNI
 VLIIVVVVAL LLLVVAVVVG VVIWKKKSKK GFVPASTSDT DSDNSGRAAL
 MT*

>P1;Sasa-UBA*1101
Sasa-UBA*1101  350 bases  
 LGIGLLHTAS AVTHSLGYFY TASSEVPNFP EFVVVSMVDG VQMVHYDSNS
 QRAVPKQDWM NKAAEALPQY WDIETGKFLG SHQSFKANID ICKQRFNQSG
 GVHIVQMMCG CEWDDETGVT EGFNQDGYDG EDFIAFDLKT KSWIAPTPQA
 VITKLKWDSN TAQNEYWKNY LTQECIEWLK KYVDYGKSTL MRTVPPSVSL
 LQKTPSSPVT CHATGFYPSG VMVSWQKDGQ DHHEDVEHGE TLQNDDGTFQ
 KSSHLTVTPE EWKNNKYQCV VQVTGIKDDI IKVLTESEIK TNWNDPNIVL
 IIGVVVALLL LVVAAVAGVV IWKKKSKKGF VPASTSDTDS DNSGRAAQMT*

>P1;Sasa-UBA*1201
Sasa-UBA*1201  335 bases  
 HSLRYVYTAT SGIPDFPEFV TVGLVNGEPI SYYDSIIRRE TPRQDWMAKT
 EGSDYWESQT QVSIGSEQTF KANIDVAKQR FNQTGGVHVF QMMCGCEWDD
 EAGATEGFDQ YGYDGEDFIA FDLKTKSWIA PTPQAVITKL KWDSNTAQNE
 YWKNYLTQEC IEWLKKYVDY GKSTLMRTVP PSVSLLQKTP SSPVTCHATG
 FYPSGVMVSW QKDGQDHHED VEHGETLQND DGTFQKSSHL TVTPEEWKNN
 KYQCVVQVTG IKDDIIKVLT ESEIKTNWND PNIVLIIGVV VALLLLVVAA
 VAGVVIWKKK SKKGFVPAST SDTDSDNSGR AAQMT*

>P1;Sasa-UBA*1301
Sasa-UBA*1301  174 bases  
 VTHSLKYFYT ASSEVPNFPE FVVVSMVDGV QMVHYDSNSQ RAVPKQDWMN
 KAAEALPQYW DIETGKFLGS HQSFKANIDI CKQRFNQSGG VHIVQKMYGC
 EWDDETGVTE GFNQYGYDGE DFIAFDLKTL KWIAPTPQAV ITKLKWDSDT
 AQNEYRKNYY TQTCIEWLKK YVDY*

>P1;Sasa-UBA*1401
Sasa-UBA*1401  358 bases  
 MKGFILLVLG IGLLHTASAA THSLKYFYTA VSGDIDFPEF TVVGLVDEGQ
 FMYFDSNTKT AVPKTEWMKK SVGADYWDRQ TQIGIGAHQN FKANIQVAKD
 RFNQSKSTGV HVFQKMYGCE WDDEAGATEG LTQYGYDGED FIAFDLKTKS
 WIAPTPQSLI TKLKWDSDTA YNEQEKNYLT QICIEWLKKY VDYGKSTLMR
 TVPPSVSLLQ KTPSSPVTCH ATGFYPSGVM VSWQKDGQDH HEDVEYGETL
 QNDDGTFQKS SHLTVTPEEW KNNKYQCVVQ VTGVKEDFIK VLTESEIKTN
 WNDPNIVLII VVVVALLLLV VAVVVGVVIW KKKSKKGFVP ASTSDTDSDN
 SGRAAQMT*

>P1;Sasa-UBA*1501
Sasa-UBA*1501  350 bases  
 LGIGLLHTTS AAIHTLKNFY TAASGDIGFP EFIIVGLVDN TPYLYFDSNT
 KTAVPKTEWM KKSVGADYWD SMTQIGIGAN QIFKANIQVV KDRFNQSKST
 GVHVFQNMYG CEWDDEAGVT EGFDQYGYDG GDFIAFDLET KTWIAPKTQA
 VNTKNKWDSD TAQNEFLKNY YTQTCIEWLK KYLDYGKSTL MRTVPPSVSL
 LQKTPSSPVT CHATGFYPSG VMVSWQKDGQ DHHEDVEHGE TLQNDDGTFQ
 KSSHLTVTPE EWKNNKYQCV VQVKGLQEDF IKVLTESEIK TNWNDPNIVL
 IIVVVVALLL LVVAVVVGVV IWKKKSKKGF VPASTSDTDS DNSGRAAQMA*

>P1;Sasa-UBA*1601
Sasa-UBA*1601  182 bases  
 ATHSLKYFYT AVSGDIDFPE FTVVGLVDEG QFMYFDSNTK TAVPKTEWMK
 KSVGADYWDR QTQIGIGAHQ NFKANIQVAK DRFNQSKSTG VHVNQNMYGC
 EWDDEAGVTE GFDQYGYDGE DFLAFDLKTL KWIAPTPQSL ITKLKWDNNM
 AQIQQDKHYL TQTCIEWLKK YLDYGKSTLM RT*

>P1;Sasa-UBA*1701
Sasa-UBA*1701  182 bases  
 AAHSLKYFYT AVSGDIDFPE FTVVGLVDEG QFMYFDSNTK TAVPKTEWMK
 KSVGADYWDR QTQIGIGAHQ NFKANIQVAK DRFNQSKSTG VHVNQWMYGC
 EWDDEAGVTE GFEQWGYDGE DFIAFDLKTK SWIAPTPQAV ITKLKWDSDT
 AQNEHRKNYY TQICIEWLKK YVDYGKSTLM RT*

>P1;Sasa-UBA*1801
Sasa-UBA*1801  180 bases  
 VTHALKYFYT ASSEVPNFPE FVVVGVVDGV QMVHYDSNSQ RAVPKQDWVN
 KAADPQYWER NTGIFKGSQQ TFKANIDIAK QRFNQSGGVH VFQMMCGCEW
 DDEAGATEGF DQYGYDGEDF IAFDLKTKSW IAPTPQAVIT KLKWDSNTAQ
 NEYWKNYLTQ ECIEWLKKYV DYGKSTLMRT*

>P1;Sasa-UBA*1802
Sasa-UBA*1802  180 bases  
 VTHALKYFYT ASSEVPNFPE FVVVGVVDGV QMVHYDSNSQ RAVPKQDWVN
 KAADPQYWER NTGIFKGSQQ TFKANIDIAK QRFNQSGGVH VFQMMCGCEW
 DDEAGTTEGF DQYGYDGEDF IAFDLKTKSW IAPTPQAVIT KIKWDSNTAH
 NECWKNYLTQ ECIEWLKKYV DYGKSTLMRT*

>P1;Sasa-UBA*1901
Sasa-UBA*1901  180 bases  
 VTHALKYFYT ASSEVPNFPG FVAVGVVDGV QMVHYDSNSQ RAVPKQDWVN
 KAADPQYWER NTGNFKGSQQ TFKANIDIAK QRFNQSGGVH VFQICMGCEW
 DDETGATEGF NQDGYDGEDF LAFDLKTLKW IAPTPQSVNT KHKWDSNTAY
 NEHWKNYLTQ ECIEWLKKYV DYGKSTLMRT*

>P1;Sasa-UBA*2001
Sasa-UBA*2001  172 bases  
 ATNTLQYFYT ATSGIDNFPE FVTMGIVNGH QIDHYDSITK RAIQKAEWIS
 GAVDPDYWKT NTQIYAGTET VFVNNINVAK SRFNQTGGVH VFQMMCGCEW
 DDEAGATEGF DQYGYDGEDF IAFDLKTKSW IAPTPQAVIT KLKWDSNTAQ
 NEYWKNYLTQ ECIEWLKKYV DY*

>P1;Sasa-UBA*2002
Sasa-UBA*2002  335 bases  
 NTLQYFYTAT SGIDNFPEFV TMGIVNGHQI DHYDSITKRA IQKAEWISGA
 VDPDIWKTNT QIYAGTETVF VNNINVAKSR FNQTGGVHVF QMMCGCEWDD
 EAGATEGFDQ YGYDGEDFIA FDLKTKSWIA PTPQAVITKL KWDSNTAQNE
 YWKNYLTQEC IEWLKKYVDY GKSTLMRTVP PSVSLLQKTP SSPVTCHATG
 FYPSGVMVSW QKDGQDHHED VEHGETLQND DGTFQKSSHL TVTPEEWKNN
 KYQCVVQVTG IKDDIIKVLT ESEIKTNWND PNIVLIIGVV VALLLLVVAA
 VAGVVIWKKK SKKGFVPAST SDTDSDNSGR AAQMT*

>P1;Sasa-UBA*2101
Sasa-UBA*2101  182 bases  
 VTHSLKYFYT ASSEVPNFPE FVVVSMVDGV QMVHYDSNSQ RAVPKQDWMN
 KAAEALPQYW DIETGKFLGS HQSFKANIDI CKQRFNQSGG VHVNQWMYGC
 EWDDEAGVTE GFEQWGYDGE DFIAFDLKTK SWIAPTPQAV ITKLKWDSDT
 AQNEHRKNYY TQICIEWLKK YVDYGKSTLM RT*

>P1;Sasa-UBA*2201
Sasa-UBA*2201  182 bases  
 VTHALKYFYT ASSEVPNFPE FVAVGVVDGV QMVHYDSNSQ RAVPKQDWMN
 KAAEALPQYW DIETGNLLGS HQSFKANIDI CKQRFNQSGG VHIVQRMCGC
 EWDDETGVTE GFNQDGYDGE DFIAFDLKTK SWIAPTPQAV ITKLKWDSNT
 AQNEYWKNYL TQECIEWLKK YVDYGKSTLM RT*

>P1;Sasa-UBA*2301
Sasa-UBA*2301  180 bases  
 ATNTLQYFYT ATSGIDNFPE FVTMGIVNGH QIDHYDSITK RAIQKAEWIS
 GAVDPDYWKT NTQIYAGTET VFVNNINVAK SRFNQTGGVP VNQKMYGCEW
 DDETGVTEGF NQDGYDGEDF IAFDLKTLKW IAPTPQAVIT KLKWDNNMAQ
 IQQDKHYLTQ TCIEWLKKYL DYGKSTLMRT*

>P1;Sasa-UBA*2401
Sasa-UBA*2401  180 bases  
 ATNTLQYFYT ATSGIGNFPE FVTMGIVNGH QIDHYDSITK RAIQKAEWIS
 GAVDPDYWKT NTQIYAGTET VFVNNINVAK SRFNQTGGVH IVQRMCGCEW
 DDETGVTEGF NQDGYDGEDF IAFDLKTKSW IAPTPQAVIT KLKWDSNTAQ
 NEYWKNYLTQ ECIEWLKKYV DYGKSTLMRT*

>P1;Sasa-UBA*2402
Sasa-UBA*2402  172 bases  
 ATNTLQYFYT ATSGIDNFPE FVTMGIVNGH QIDHYDSITK RAIQKAEWIS
 GAVDPDYWKT NTQIYAGTET VFVNNINVAK SRFNQTGGVH IVQRMCGCEW
 DDETGVTEGF NQDGYDGEDF IAFDLKTKSW IAPTPQAVIT KLKWDSNTAQ
 NEYWKNYLTQ ECIEWLKKYV DY*

>P1;Sasa-UBA*2403
Sasa-UBA*2403  180 bases  
 ATNTLQYFYT ATSGIDNFPE FVTMGIVNGH QIDHYDSITK RAIQKAEWIS
 GAVDPDYWKT NTQIYAGTET VFVNNINVAK SRFNQTGGVH IVQRMCGCEW
 DDETGVTEGF NQNGYDGEDF IQFDLKTKSW IAPTPQAVIT KLKWDSNTAQ
 NEYWKNYLTQ ECIEWLKKYV GYGKSTLMRT*

>P1;Sasa-UBA*2501
Sasa-UBA*2501  180 bases  
 ATHSLRYVYT ATSGIPDFPE FVNLGIVDGM QIDYYDSNTK RAVPKQDWMA
 KTEGSDYWDR QTQVSIGSEQ TFKANIDIVK QRFNQTGGVH VNQWMYGCEW
 DDEAGVTEGF EQWGYDGEDF IAFDLKTKSW IAPTPQAVIT KLKWDSDTAQ
 NEHRKNYYTQ ICIERLKKYV DYGKSTLMRT*

>P1;Sasa-UBA*2601
Sasa-UBA*2601  182 bases  
 ATHSLKYFYT AVSGDIDFPE FTVVGLVDEG QFMYFDSNTK TAVPKTEWMK
 KSVGADYWDR QTQIGIGAHQ NFKANIQVAK DRFNQSKSTG VHVFQNMYGC
 EWDDETGVTE GFDQDGYDGE DFLAFDLKTL TWIAPTPQAV NTKHKWDSNT
 AYNEQRKNYL TQICIEWLKK YVDYGKSTLM RT*

>P1;Sasa-UBA*2602
Sasa-UBA*2602  182 bases  
 ATHSLKYFYT AVSGDIDFPE FTVVGLVDEG QFMYFDSNTK TAVPKTEWMK
 KSVGADYWDR QTQIGIGAHQ NFKANIQVAK DRFNQSKSTG VHVFQNMYGC
 EWDDETGVTE GFDHDGYDGE DFLAFDLKTL TWIAPTPQAV NTKHKWDSNT
 AYNEQEKNYL TQICIEWMKK YVDYGKSTLM RT*

>P1;Sasa-UBA*2701
Sasa-UBA*2701  172 bases  
 VTHALKYFYT ASSEVPNFPE FVAVGVVDGV QMFHYDSNSQ RAVPKQDWVN
 KAADPQYWER NTGNCKGSQQ IFKANIDIVK QRFNQSGGVH VNQWMYGCEW
 DDETGVTEGF NQDGYDGEDF IAFDLKTKSW IAPTPQAVIT KLKWDSDTAQ
 NEYLKNYLTQ ECIEWLKKYL DY*

>P1;Sasa-UBA*2801
Sasa-UBA*2801  174 bases  
 VTHSLKYFYT ASSEVPNFPE FVVVSMVDGV QMVHYDSNSQ RAVPKQDWMN
 KAAEALPQYW DIETGKFLGS HQSFKANIDI CKQRFNQSGG VHIFQYMYGC
 TWDDDSGVTD GLRQYGYDGE DFLVYDMKAF TWIAPKLQAE ITTRKWNNEP
 AQMEYLKSYI TQECVEWLKK YVDY*

>P1;Sasa-UBA*2901
Sasa-UBA*2901  180 bases  
 VTHTLKYFYT ASSEVPNFPE FVAVGVVDGV QMVHYDSNCQ RAVPKQDWVN
 KAADPQYWER NTGNCKGSQQ IFKANIDIVK QRFNQSGGVH VFQMMCGCEW
 DDEAGATEGF DQYGYDGEDF IALDLKTKSW IAPTPQAVIT KLKWDSNTAQ
 NEYWKNYLTQ ECIEWLKKYV DYGKSTLMRT*

>P1;Sasa-UBA*3001
Sasa-UBA*3001  180 bases  
 ATHSLRYVYT ATSGIPDFPE FVNLGIVDGM QIDYYDSNTK RAVPKQDWMA
 KTEGSDYRDR QTQVSIGSEQ TFKANIDIVK QRFNQTGGVH VNQWMYGCEW
 DDEAGATEWF EQWGYDGEDF IAFDLKTKSW IAPTPQAVIT KLKWDSGTAH
 NEYRKNYYSH ICTEWMKKYV EYGKSTVMRT*

>P1;Sasa-UBA*3101
Sasa-UBA*3101  180 bases  
 ATHSLRYVYT ATSGIPDFPE FVNLGIVDGM QIDYYDSNTK RAVPKQDWMA
 KTEGSDYWDR QTQVSIGSEQ TFKANIDIVK QRFNQTGGVH VNQWMYGCEW
 DDEAGVTEGF EQYGYDGEDF IAFDLKTKSW IAPTPQAVIT KLKWDSNTAQ
 NEYWKNYLTQ ECIEWLKKYV DYGKSTLMRT*

>P1;Sasa-UBA*3201
Sasa-UBA*3201  180 bases  
 ATHSLRYVYT ATSGIPDFPE FVNLGIVDGM QIDYYDSNTK RAVPKQDWMA
 KTEGSDYWDR QTQVSIGSEQ TFKANIDIVK QRFNQTGGVH VNQWMYGCEW
 DDEAGVTEGF EQWGYDGKDF MAFDMKTKSW IAPTPQAVIT KLKWDSDTAQ
 NEHREDYYTQ MCIEWLKKYV DYGKSTLMRT*

>P1;Sasa-UBA*3301
Sasa-UBA*3301  339 bases  
 NAASAVTHSL KYFYTGSTGI EGFPQFVAVG IVDGMHIDYF DSVSEKNVLK
 QSWMEGARDE KSITNIRKGH QQSFKANVEI VMQRFNQTTG VHVFQKMYGC
 EWDDEAGATE GLTQYGYDGE DFIAFDLKTK SWIAPTPQSL ITKLKWDSDT
 AYNEQEKNYL TQICIEWLKK YVDYGKSTLM RTVPPSVSLL QKTPSSPVTC
 HATGFYPSGV MVSWQKDGQD HHEDVEYGET LQNDDGTFQK SSHLTVTPEE
 WKNNKYQCVV QVTGVKEDFI KVLTESEIKT NWNDPNIVLI IVVVVALLLL
 VVAVVVGVVI WKKKSKKGFV PASTSDTDSD NSGRAAQMT*

>P1;Sasa-UBA*3401
Sasa-UBA*3401  172 bases  
 VTHALKYFYT ASSEVPNFPE FVVVGVVDGV QMVHYDSNSQ RAVPKQDWVN
 KAADPQYWER NTGIFKGSQQ TFKANIDIAK QRFNQSGGVH VNQWMYGCEW
 DDEAGVTEGF EQWGYDGEDF IAFDLKTKSW IAPTPQAVIT KLKWDSDTAQ
 NEHRKNYYTQ ICIEWLKKYV DY*

