>P1;IPD:MHC02479
IPD:MHC02479 Ovar-DRA*0101, 254 bases, 75287EEA checksum.
 MAITRVPILG LFITVLISLQ ESWAIKEDHV IIQAEFYLNP EESAEFMFDF
 DGDEIFHVDM QKKETVWRLP EFGHFASFEA QGALANMAVM KANLDIMIKR
 SNNTPNTNVP PEVTLLPNKP VELGEPNTLI CFIDKFSPPV ISVTWLRNGI
 PVTDGVSQTV FLPRDDHLFR KFHYLPFLPT TEDVYDCKVE HWGLNEPLLK
 HWEYEAPAPL PETTENAVCA LGLIVALVGI IAGTIFIIKG VRKANTVEGR
 GPLX*

>P1;IPD:MHC02480
IPD:MHC02480 Ovar-DRA*0102, 254 bases, 8F733F69 checksum.
 MAITRVPILG LFITVLISLQ ESWAIKEDHV IIQAEFYLNP EESAEFMFDF
 DGDEIFHVDM QKKETVWRLP EFGRFASFEA QGALANMAVM KANLDIMIKR
 SNNTPNTNVP PEVTLLPNKP VELGEPNTLI CFTDKFSPPV ISVTWLRNGI
 PVTDGVSQTV FLPRDDHLFR KFHYLPFLPT TEDVYDCKVE HWGLNEPLLK
 HWEYEAPAPL PETTENAVCA LGLIVALVGI IAGTIFIIKG VRKANTVEGR
 GPLX*

>P1;IPD:MHC02481
IPD:MHC02481 Ovar-DRA*0201, 254 bases, AFE111AE checksum.
 MAITRVPILG LFITVLISLQ ESWAIKEDHM IIQAGIYVNP EQSAEFMFDF
 DGDEIFHVDM QKKETVWRLP EFGHFASFEA QGALANMAVM KANLDVMTKY
 SNNTPNTNVP PEVTLLPNKP VELGEPNTLI CFIDKFSPPV ISVTWLRNGK
 PVTDGVSQTV FLPRDDHLFR KFHYLSFLPT TEDVYDCKVE HCSLNEPLLK
 HWEYEAPAPL PETTENAVCA LGLIVALVGI IAGTIFIIKG VRKANTVEGR
 GPLX*

