>DL;IPD:MHC02426
IPD:MHC02426 Ovar-DRB1*0101, 801 bases, 6C97210F checksum.
 ATGGTGTGCC TGTATTTCTC CAGAGGCTCC CGGATGGCAG CTCTGATAGT
 GATGCTGATG GCGCTGAGCC CTCCCCTGGC CTGGGCCAGG AAGATCCAAC
 CACATTTCTT GGAGTATACT AAGAAAGAGT GTCGTTTCTC CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC CATAATGGAG AAGAGACCCT
 GCGCTTCGAC AGCGACTGGG GCGAGTACCG AGCGGTGGCC GAGCTGGGGC
 GGCCGGACGC CAAGTACTGG AACAGCCAGA AGGACTTCCT GGAGCGGGCG
 CGGGCCGCCG TGGACACGTA CTGCAGACAC AACTACGGGG TCATTGAGAG
 TTTCACTGTG CAGCGGCGAG TGGAGCCTAT AGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAATGGA
 TTCTACCCAG GCCACATTGA AGTCAGGTGG TTCCGGAATG GCCACGAAGA
 GGAGGCTGGG GTGATCTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCAT GGTGATGCTT GAAACAGTTC CTCAGAGTGG AGAGGTCTAC
 ACCTGCCAAG TGGATCACCC CAGCCGGACG AGCCCTATCA CAGTGGAATG
 GAGGGCACGG TCTGACTCAG CTCAGAGCAA GATGATGAGT GGAGTTGGGG
 GCTTTGTTCT GGGTCTGCTC TTCCTTGCGG TGGGGCTCTT CATCTACTTC
 AGGAATCAGA AAGGACGCCC TACCCTTCAG CCAACAGGGC TCCTGAGCTG
 A*

>DL;IPD:MHC02448
IPD:MHC02448 Ovar-DRB1*0102, 270 bases, F7CE2392 checksum.
 CACATTTCTT GGAGTATACT AAGAAAGAGT GTCGTTTCTC CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC CATAATGGAG AAGAGACCCT
 GCGCTTCGAC AGCGACTGGG GCGAGTACCG AGCGGTGGCC GAGCTGGGGC
 GGCCGGACGC CAAGTACTGG AACAGCCAGA AGGACTTCCT GGAGCGGGCG
 CGGGCCGCCG TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG
 TTTCAGTGTG CAGCGGCGAG*

>DL;IPD:MHC02464
IPD:MHC02464 Ovar-DRB1*0103, 474 bases, D19833E2 checksum.
 AGAGGCTCCC GGATGGCAGC TCTGATAGTG ATGCTGATGG CGCTGAGCCC
 TCCCCTGGCC TGGGCCAGGA AGATCCAACC ACATTTCTTG GAGTATACTA
 AGAAAGAGTG TCGTTTCTCC AACGGGACGG AGCGGGTGCG GTTCCTGGAC
 AGATACTTCC ATAATGGAGA AGAGACCCTG CGCTTCGACA GCGACTGGGG
 CGAGTACCGA GCGGTGGCCG AGCTGGGGCG GCCGGACGCC GAGTACTGGA
 ACAGCCAGAA GGACTTCCTG GAGCGGGCGC GGGCCGCCGT GGACACGTAC
 TGCAGACACA ACTACGGGGT CGGTGAGAGT TTCAGTGTGC AGCGGCGAGT
 GGAGCCTATA GTGACTGTGT ATCCTGCAAA GACCCAGCCC CTGCAGCACC
 ACAACCTCCT GGTCTGCTCT GTGAATGGAT TCTACCCAGG CCACATTGAA
 GTCAGGTGGT TCCGGAACGG CCAC*

>DL;IPD:MHC02783
IPD:MHC02783 Ovar-DRB1*0104, 270 bases, 3B80343E checksum.
 CACATTTCTT GGAGTATACT AAGAAAGAGT GTCGTTTCTC CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC CATAATGGAG AAGAGTACGC
 GCGCTTCGAC AGCGACTGGG GCGAGTACCG AGCGGTGGCC GAGCTGGGGC
 GGCCGGACGC CAAGTACTGG AACAGCCAGA AGGACTTCCT GGAGCGGGCG
 CGGGCCGCCG TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG
 TTTCACTGTG CAGCGGCGAG*

>DL;IPD:MHC02445
IPD:MHC02445 Ovar-DRB1*0201, 801 bases, D4D51E9 checksum.
 ATGGTGTGCC TGTATTTCTC CAGAGGCTCC CGGATGGCAG CTCTGATAGT
 GATGCTGATG GCGCTGAGCC CTCCCCTGGC CTGGGCCAGG AAGATCCAAC
 CACATTTCTT GGAGTATTCT ACGAGCGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAATGGAG AAGAGACCCT
 GCGCTTCGAC AGCGACTGGG GCGAGTACCG AGCGGTGGCC GAGCTGGGGC
 GGCCGGACGC CAAGTACTGG AACAGCCAGA AGGACTTCCT GGAGCAGACG
 CGGGCCGCCG TGGACACGTA CTGCAGACAC AACTACGGGG TCATTGAGAG
 TTTCAGTGTG CAGCGGCGAG TGGAGCCTAT AGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAATGGA
 TTCTACCCAG GCCACATTGA AGTCAGGTGG TTCCGGAACG GCCACGAAGA
 GGAGGCTGGG GTGATCTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCAT GGTGATGCTT GAAACAGTTC CTCAGAGTGG AGAGGTCTAC
 ACCTGCCAAG TGGATCACCC CAGCCGGACG AGCCCTATCA CAGTGGAATG
 GAGGGCACGG TCTGACTCAG CTCAGAGCAA GATGATGAGT GGAGTTGGGG
 GCTTTGTTCT GGGTCTGCTC TTCCTTGCGG TGGGGCTCTT CATCTACTTC
 AGGAATCAGA AAGGACGCCC TACCCTTCAG CCAACAGGGC TCCTGAGCTG
 A*

>DL;IPD:MHC02429
IPD:MHC02429 Ovar-DRB1*0301, 801 bases, ECF52E53 checksum.
 ATGGTGTGCC TGTATTTCTC CAGAGGCTCC CGGATGGCAG CTCTGATAGT
 GATGCTGATG GCGCTGAGCC CTCCCCTGGC CTGGGCCAGG AAGATCCAAC
 CACATTTCTT GGAGTATACT AAGAAAGAGT GTCGTTTCTC CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC CATAATGGAG AAGAGTACGC
 GCGCTTCGAC AGCGACTGGG GCGAGTACCG AGCGGTGGCC GAGCTGGGGC
 GGCCGGACGC CAAGTACTGG AACAGCCAGA AGGAGATCCT GGAGCGGAGG
 CGGACCGAGG TGGACACGTA CTGCAGACAC AACTACGGGG TCATTGAGAG
 TTTCAGTGTG CAGCGGCGAG TGGAGCCTAT AGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAATGGA
 TTCTACCCAG GCCACATTGA AGTCAGGTGG TTCCGGAATG GCCACGAAGA
 GGAGGCTGGG GTGATCTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCAT GGTGATGCTT GAAACAGTTC CTCAGAGTGG AGAGGTCTAC
 ACCTGCCAAG TGGATCACCC CAGCCGGACG AGCCCTATCA CAGTGGAATG
 GAGGGCACGG TCTGACTCAG CTCAGAGCAA GATGATGAGT GGAGTTGGGG
 GCTTTGTTCT GGGTCTGCTC TTCCTTGCGG TGGGGCTCTT CATCTACTTC
 AGGAATCAGA AAGGACGCCC TACCCTTCAG CCAACAGGGC TCCTGAGCTG
 A*

>DL;IPD:MHC02424
IPD:MHC02424 Ovar-DRB1*0302, 474 bases, 54EFEF00 checksum.
 AGAGGCTCCC GGATGGCAGC TCTGATAGTG ATGCTGATGG CGCTGAGCCC
 TCCCCTGGCC TGGGCCAGGA AGATCCAACC ACATTTCTTG GAGTATACTA
 AGAAAGAGTG TCGTTTCTCC AACGGGACGG AGCGGGTGCG GTTCCTGGAC
 AGATACTTCT ATAATGGAGA AGAGTACGTG CGCTTCGACA GCGACTGGGG
 CGAGTACCGA GCGGTGGCCG AGCTGGGGCG GCCGGACGCC AAGTACTGGA
 ACAGCCAGAA GGAGATCCTG GAGCGGAGGC GGACCGAGGT GGACACGTAC
 TGCAGACACA ACTACGGGGT CATTGAGAGT TTCAGTGTGC AGCGGCGAGT
 GGAGCCTATA GTGACTGTGT ATCCTGCAAA GACCCAGCCC CTGCAGCACC
 ACAACCTCCT GGTCTGCTCT GTGAATGGAT TCTACCCAGG CCACATTGAA
 GTCAGGTGGT TCCGGAATGG CCAC*

>DL;IPD:MHC02430
IPD:MHC02430 Ovar-DRB1*0303, 801 bases, 80114530 checksum.
 ATGGTGTGCC TGTATTTCTC CAGAGGCTCC CGGATGGCAG CTCTGATAGT
 GATGCTGATG GCGCTGAGCC CTCCCCTGGC CTGGGCCAGG AAGATCCAAC
 CACATTTCTT GGAGTATACT AAGAAAGAGT GTCGTTTCTC CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAATGGAG AAGAGTACGC
 GCGCTTCGAC AGCGACTGGG GCGAGTACCG AGCGGTGGCC GAGCTGGGGC
 GGCCGGACGC CAAGTACTGG AACAGCCAGA AGGAGATCCT GGAGCGGAGG
 CGGACCGAGG TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG
 TTTCACTGTG CAGCGGCGAG TGGAGCCTAT AGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAATGGA
 TTCTACCCAG GCCACATTGA AGTCAGGTGG TTCCGGAATG GCCACGAAGA
 GGAGGCTGGG GTGATCTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCAT GGTGATGCTT GAAACAGTTC CTCAGAGTGG AGAGGTCTAC
 ACCTGCCAAG TGGATCACCC CAGCCGGACG AGCCCTATCA CAGTGGAATG
 GAGGGCACGG TCTGACTCAG CTCAGAGCAA GATGATGAGT GGAGTTGGGG
 GCTTTGTTCT GGGTCTGCTC TTCCTTGCGG TGGGGCTCTT CATCTACTTC
 AGGAATCAGA AAGGACGCCC TACCCTTCAG CCAACAGGGC TCCTGAGCTG
 A*

>DL;IPD:MHC02454
IPD:MHC02454 Ovar-DRB1*0304, 474 bases, ECF3699D checksum.
 AGAGGCTCCC GGATGGCAGC TCTGATAGTG ATGCTGATGG CGCTGAGCCC
 TCCCCTGGCC TGGGCCAGGA AGATCCAACC ACATTTCTTG GAGTATACTA
 AGAAAGAGTG TCGTTTCTCC AACGGGACGG AGCGGGTGCG GTTCCTGGAC
 AGATACTTCT ATAATGGAGA AGAGTACGCG CGCTTCGACA GCGACTGGGG
 CGAGTACCGA GCGGTGGCCG AGCTGGGGCG GCGGAGCGCC GAGTACTGGA
 ACAGCCAGAA GGAGATCCTG GAGCGGAGGC GGACCGAGGT GGACACGTAC
 TGCAGACACA ACTACGGGGT CATTGAGAGT TTCAGTGTGC AGCGGCGAGT
 GGAGCCTATA GTGACTGTGT ATCCTGCAAA GACCCAGCCC CTGCAGCACC
 ACAACCTCCT GGTCTGCTCT GTGAATGGAT TCTACCCAGG CCACATTGAA
 GTCAGGTGGT TCCGGAATGG CCAC*

>DL;IPD:MHC02462
IPD:MHC02462 Ovar-DRB1*0305, 270 bases, 9AF772FD checksum.
 CACATTTCTT GGAGTATACT AAGAAAGAGT GTCGTTTCTC CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAATGGAG AAGAGTACGC
 GCGCTTCGAC AGCGACTGGG GCGAGTACCG AGCGGTGGCC GAGCTGGGGC
 GGCGGAGCGC CGAGTACTGG AACAGCCAGA AGGAGATCCT GGAGCAGACG
 CGGGCCGAGG TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG
 TTTCAGTGTG CAGCGGCGAG*

>DL;IPD:MHC02476
IPD:MHC02476 Ovar-DRB1*0306, 474 bases, CA1064E1 checksum.
 AGAGGCTCCC GGATGGCAGC TCTGATAGTG ATGCTGATGG CGCTGAGCCC
 TCCCCTGGCC TGGGCCAGGA AGATCCAACC ACATTTCTTG GAGTATACTA
 AGAAAGAGTG TCGTTTCTCC AACGGGACGG AGCGGGTGCG GTTCCTGGAC
 AGATACTTCC ATAATGGAGA AGAGTACGCG CGCTTCGACA GCGACTGGGG
 CGAGTACCGA GCGGTGGCCG AGCTGGGGCG GCCGGACGCC AAGTACTGGA
 ACAGCCAGAA GGAGATCCTG GAGCGGAGGC GGACCGAGGT GGACACGTAC
 TGCAGACACA ACTACGGGGT CGGTGAGAGT TTCACTGTGC AGCGGCGAGT
 GGAGCCTATA GTGACTGTGT ATCCTGCAAA GACCCAGCCC CTGCAGCACC
 ACAACCTCCT GGTCTGCTCT GTGAATGGAT TCTACCCAGG CCACATTGAA
 GTCAGGTGGT TCCGGAATGG CCAC*

>DL;IPD:MHC02472
IPD:MHC02472 Ovar-DRB1*0307, 474 bases, AC885B98 checksum.
 AGAGGCTCCC GGATGGCAGC TCTGATAGTG ATGCTGATGG CGCTGAGCCC
 TCCCCTGGCC TGGGCCAGGA AGATCCAACC ACATTTCTTG GAGTATCATA
 AGAGCGAGTG TCGTTTCTCC AACGGGACGG AGCGGGTGCG GTTCCTGGAC
 AGATACTTCT ATAATGGAGA AGAGTACGCG CGCTTCGACA GCGACTGGGG
 CGAGTACCGA GCGGTGGCCG AGCTGGGGCG GCCGGACGCC GAGTACTGGA
 ACAGCCAGAA GGAGCTCCTG GAGCGGAGGC GGACCGAGGT GGACACGTAC
 TGCAGACACA ACTACGGGGT CGGTGAGAGT TTCACTGTGC AGCGGCGAGT
 GGAGCCTATA GTGACTGTGT ATCCTGCAAA GACCCAGCCC CTGCAGCACC
 ACAACCTCCT GGTCTGCTCT GTGAATGGAT TCTACCCAGG CCACATTGAA
 GTCAGGTGGT TCCGGAACGG CCAC*

>DL;IPD:MHC02483
IPD:MHC02483 Ovar-DRB1*0308, 270 bases, E72373C1 checksum.
 CACATTTCTT GGAGTATACT AAGAAAGAGT GTCGTTTCTC CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAATGGAG AAGAGTACGC
 GCGCTTCGAC AGCGACTGGG GCGAGTACCG AGCGGTGGCC GAGCTGGGGC
 GGCGGAGCGC CGAGTACTGG AACAGCCAGA AGGAGATCCT GGAGCGGAAG
 CGGGCCGCCG TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG
 TTTCACTGTG CAGCGGCGAG*

>DL;IPD:MHC02789
IPD:MHC02789 Ovar-DRB1*0309, 270 bases, 108B179E checksum.
 CACATTTCTT GGAGTATACT AAGAAAGAGT GTCGTTTCTC CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAATGGAG AAGAGTACGC
 GCGCTTCGAC AGCGACTGGG GCGAGTACCG AGCGGTGGCC GAGCTGGGGC
 GGCGGAGCGC CGAGTACTGG AACAGCCAGA AGGAGATCCT GGAGCAGACG
 CGGGCCGAGG TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG
 TTTCACTGTG CAGCGGCGAG*

>DL;IPD:MHC02979
IPD:MHC02979 Ovar-DRB1*0310, 270 bases, C1CF9720 checksum.
 CACATTTCTT GGAGTATCAT AAGAGCGAGT GTCGTTTCTC CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAATGGAG AAGAGTACGC
 GCGCTTCGAC AGCGACTGGG GCGAGTACCG AGCGGTGGCC GAGCTGGGGC
 GGCGGAGCGC CGAGTACTGG AACAGCCAGA AGGAGATCCT GGAGCGGAAG
 CGGGCCGCCG TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG
 TTTCACTGTG CAGCGGCGAG*

>DL;IPD:MHC02425
IPD:MHC02425 Ovar-DRB1*0401, 474 bases, 43D9F216 checksum.
 AGAGGCTCCC GGATGGCAGC TCTGATAGTG ATGCTGATGG CGCTGAGCCC
 TCCCCTGGCC TGGGCCAGGA AGATCCAACC ACATTTCTTG GAGTATCATA
 AGAGCGAGTG TCGTTTCTCC AACGGGACGG AGCGGGTGCG GTACCTGGAC
 AGATACTTCT ATAATGGAGA AGAGTACGTG CGCTTCGACA ACGACTGGGG
 CGAGTACCGA GCGGTGGCCG AGCTGGGGCG GCCGGACGCC AAGTACTGGA
 ACAGCCAGAA GGACTTCCTG GAGCAGACGC GGGCCGAGGT GGACACGTAC
 TGCAGACACA ACTACGGGGT CATTGAGAGT TTCAGTGTGC AGCGGCGAGT
 GGAGCCTATA GTGACTGTGT ATCCTGCAAA GACCCAGCCC CTGCAGCACC
 ACAACCTCCT GGTCTGCTCT GTGAATGGAT TCTACCCAGG CCACATTGAA
 GTCAGGTGGT TCCGGAACGG CCAC*

>DL;IPD:MHC02459
IPD:MHC02459 Ovar-DRB1*0402, 270 bases, 369E8C05 checksum.
 CACATTTCTT GGAGTATCAT AAGAGCGAGT GTCGTTTCTC CAACGGGACG
 GAGCGGGTGC GGTACCTGGA CAGATACTTC TATAATGGAG AAGAGTACGT
 GCGCTTCGAC AACGACTGGG GCGAGTACCG AGCGGTGGCC GAGCTGGGGC
 GGCGGAGCGC CGAGTACTGG AACAGCCAGA AGGACTTCCT GGAGCAGACG
 CGGGCCGAGG TGGACACGTA CTGCAGACAC AACTACGGGG TCATTGAGAG
 TTTCAGTGTG CAGCGGCGAG*

>DL;IPD:MHC02427
IPD:MHC02427 Ovar-DRB1*0501, 801 bases, 3C877D4D checksum.
 ATGGTGTGCC TGTATTTCTC CAGAGGCTCC CGGATGGCAG CTCTGATAGT
 GATGCTGATG GCGCTGAGCC CTCCCCTGGC CTGGGCCAGG AAGATCCAAC
 CACATTTCTT GGAGTATGCT AAGAGCGAGT GTCGTTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA AAGATACTTC TATAATGGAG AAGAGACCCT
 GCGCTTCGAC AGCGACTGGG GCGAGTACCG AGCGGTGGCC GAGCTGGGGC
 GGCCGGACGC CAAGTACTGG AACAGCCAGA AGGAGCTCCT GGAGCGGAAG
 CGGGCCAATG TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG
 TTTCACTGTG CAGCGGCGAG TGGAGCCTAT AGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAATGGA
 TTCTACCCAG GCCACATTGA AGTCAGGTGG TTCCGGAACG GCCACGAAGA
 GGAGGCTGGG GTGATCTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCAT GGTGATGCTT GAAACAGTTC CTCAGAGTGG AGAGGTCTAC
 ACCTGCCAAG TGGATCACCC CAGCCGGACG AGCCCTATCA CAGTGGAATG
 GAGGGCACGG TCTGACTCAG CTCAGAGCAA GATGATGAGT GGAGTTGGGG
 GCTTTGTTCT GGGTCTGCTC TTCCTTGCGG TGGGGCTCTT CATCTACTTC
 AGGAATCAGA AAGGACGCCC TACCCTTCAG CCAACAGGGC TCCTGAGCTG
 A*

>DL;IPD:MHC02784
IPD:MHC02784 Ovar-DRB1*0502, 270 bases, 6D01DC87 checksum.
 CACATTTCTT GGAGTATGCT AAGAGCGAGT GTCGTTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA AAGATACTTC TATAATGGAG AAGAGACCCT
 GCGCTTCGAC AGCGACTGGG GCGAGTACCG AGCGGTGGCC GAGCTGGGGC
 GGCCGGACGC CAAGTACTGG AACAGCCAGA AGGAGCTCCT GGAGCGGAAG
 CGGGCCAATG TGGACACGTA CTGCAGACAC AACTACGGGG TCGATGAGAG
 TTTCACTGTG CAGCGGCGAG*

>DL;IPD:MHC04079
IPD:MHC04079 Ovar-DRB1*0503, 270 bases, ED683E21 checksum.
 CACATTTCTT GGAGTATCGT AAGAGCGAGT GTCGTTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA AAGATACTTC CATAATGGAG AAGAGACCCT
 GCGCTTCGAC AGCGACTGGG GCGAGTACCG AGCGGTGGCC GAGCTGGGGC
 GGCCGGACGC CAAGTACTGG AACAGCCAGA AAGAGCTCCT GGAGCGGAAG
 CGGGCCAATG TGGACACGTA CTGCAGACAC AACTACGGGG TCATTGAGAG
 TTTCAGTGTG CAGCGGCGAG*

>DL;IPD:MHC02446
IPD:MHC02446 Ovar-DRB1*0601, 801 bases, CF7BEB48 checksum.
 ATGGTGTGCC TGTATTTCTC CAGAGGCTCC CGGATGGCAG CTCTGATAGT
 GATGCTGATG GCGCTGAGCC CTCCCCTGGC CTGGGCCAGG AAGATCCAAC
 CACATTTCTT GGAGTATGCT AAGAGCGAGT GTCGTTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA AAGATACTTC TATAATGGAG AAGAGTACGT
 GCGCTTCGAC AGCGACTGGG GCGAGTACCG AGCGGTGGCC GAGCTGGGGC
 GGCGGAGCGC CGAGTACTGG AACAGCCAGA AGGACTTCCT GGAGCGGAAG
 CGGGCCAATG TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG
 TTTCACTGTG CAGCGGCGAG TGGAGCCTAT AGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAATGGA
 TTCTACCCAG GCCACATTGA AGTCAGGTGG TTCCGGAACG GCCACGAAGA
 GGAGGCTGGG GTGATCTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCAT GGTGATGCTT GAAACAGTTC CTCAGAGTGG AGAGGTCTAC
 ACCTGCCAAG TGGATCACCC CAGCCGGACG AGCCCTATCA CAGTGGAATG
 GAGGGCACGG TCTGACTCAG CTCAGAGCAA GATGATGAGT GGAGTTGGGG
 GCTTTGTTCT GGGTCTGCTC TTCCTTGCGG TGGGGCTCTT CATCTACTTC
 AGGAATCAGA AAGGACGCCC TACCCTTCAG CCAACAGGGC TCCTGAGCTG
 A*

>DL;IPD:MHC02431
IPD:MHC02431 Ovar-DRB1*0701, 801 bases, FBB727B0 checksum.
 ATGGTGTGCC TGTATTTCTC CAGAGGCTCC CGGATGGCAG CTCTGATAGT
 GATGCTGATG GCGCTGAGCC CTCCCCTGGC CTGGGCCAGG AAGATCCAAC
 CACATTTCCT GGAGTATACT AAGAAAGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTGCTGGA AAGATACTTC TATAATGGAG AAGAGTACGT
 GCGCTTCGAC AGCGACTGGG GCGAGTTCCG GGCGGTGGCC GAGCTGGGGC
 GGCCGGACGC CAAGTACTGG AACAGCCAGA AGGATTTCCT GGAGAGCAGG
 AGGACCGCGG TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG
 TTTCACTGTG CAGCGGCGAG TGGAGCCTAT AGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAATGGA
 TTCTACCCAG GCCACATTGA AGTCAGGTGG TTCCGGAACG GCCACGAAGA
 GGAGGCTGGG GTGATCTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCAT GGTGATGCTT GAAACAGTTC CTCAGAGTGG AGAGGTCTAC
 ACCTGCCAAG TGGATCACCC CAGCCGGACG AGCCCTATCA CAGTGGAATG
 GAGGGCACGG TCTGACTCAG CTCAGAGCAA GATGATGAGT GGAGTTGGGG
 GCTTTGTTCT GGGTCTGCTC TTCCTTGCGG TGGGGCTCTT CATCTACTTC
 AGGAATCAGA AAGGACGCCC TACCCTTCAG CCAACAGGGC TCCTGAGCTG
 A*

>DL;IPD:MHC02457
IPD:MHC02457 Ovar-DRB1*0702, 270 bases, 398DE678 checksum.
 CACATTTCTT GGAGTATCAT AAGAGCGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAATGGAG AAGAGTACGT
 GCGCTTCGAC AGCGACTGGG GCGAGTTCCG GGCGGTGGCC GAGCTGGGGC
 GGCCGGACGC CAAGTACTGG AACAGCCAGA AGGACTTCCT GGAGAGCAGG
 AGGACCGCGG TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG
 TTTCACTGTG CAGCGGCGAG*

>DL;IPD:MHC02444
IPD:MHC02444 Ovar-DRB1*0801, 801 bases, BA02875A checksum.
 ATGGTGTGCC TGTATTTCTC CAGAGGCTCC CGGATGGCAG CTCTGATAGT
 GATGCTGATG GCGCTGAGCC CTCCCCTGGC CTGGGCCAGG AAGATCCAAC
 CACATTTCTT GGAGTATCAT AAGAGCGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC CATAATGGAG AAGAGTTCGT
 GCGCTTCGAC AGCGACTGGG GCGAGTTCCG GGCGGTGGCC GAGCTGGGGC
 GGCGGAGCGC CGAGTACTGG AACAGCCAGA AGGAGCTCCT GGAGCGGAGG
 CGGACCGAGG TGGACACGTA CTGCAGACAC AACTACGGGG TCTTTGAGAG
 TTTCAGTGTG CAGCGGCGAG TGGAGCCTAT AGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAATGGA
 TTCTACCCAG GCCACATTGA AGTCAGGTGG TTCCGGAACG GCCACGAAGA
 GGAGGCTGGG GTGATCTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCAT GGTGATGCTT GAAACAGTTC CTCAGAGTGG AGAGGTCTAC
 ACCTGCCAAG TGGATCACCC CAGCCGGACG AGCCCTATCA CAGTGGAATG
 GAGGGCACGG TCTGACTCAG CTCAGAGCAA GATGATGAGT GGAGTTGGGG
 GCTTTGTTCT GGGTCTGCTC TTCCTTGCGG TGGGGCTCTT CATCTACTTC
 AGGAATCAGA AAGGACGCCC TACCCTTCAG CCAACAGGGC TCCTGAGCTG
 A*

>DL;IPD:MHC02451
IPD:MHC02451 Ovar-DRB1*0802, 270 bases, 7C122E55 checksum.
 CACATTTCTT GGAGTATGCT AAGAGCGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAATGGAG AAGAGTACGT
 GCGCTTCGAC AGCGACTGGG GCGAGTTCCG GGCGGTGGCC GAGCTGGGGC
 GGCGGAGCGC CGAGTACTGG AACAGCCAGA AGGAGCTCCT GGAGCGGAGG
 CGGACCGAGG TGGACACGTA CTGCAGACAC AACTACGGGG TCTTTGAGAG
 TTTCAGTGTG CAGCGGCGAG*

>DL;IPD:MHC02465
IPD:MHC02465 Ovar-DRB1*0803, 474 bases, 117666C5 checksum.
 AGAGGCTCCC GGATGGCAGC TCTGATAGTG ATGCTGATGG CGCTGAGCCC
 TCCCCTGGCC TGGGCCAGGA AGATCCAACC ACATTTCTTG GAGTATCATA
 AGAGCGAGTG TCATTTCTTC AACGGGACGG AGCGGGTGCG GTTCCTGGAC
 AGATACTTCT ATAATGGAGA AGAGTACGTG CGCTTCGACA GCGACTGGGG
 CGAGTTCCGG GCGGTGGCCG AGCTGGGGCG GCGGAGCGCC GAGTACTGGA
 ACAGCCAGAA GGAGCTCCTG GAGCGGAGGC GGACCGAGGT GGACACGTAC
 TGCAGACACA ACTACGGGGT CTTTGAGAGT TTCAGTGTGC AGCGGCGAGT
 GGAGCCTATA GTGACTGTGT ATCCTGCAAA GACCCAGCCC CTGCAGCACC
 ACAACCTCCT GGTCTGCTCT GTGAATGGAT TCTACCCAGG CCACATTGAA
 GTCAGGTGGT TCCGGAACGG CCAC*

>DL;IPD:MHC02473
IPD:MHC02473 Ovar-DRB1*0804, 474 bases, 211F4E11 checksum.
 AGAGGCTCCC GGATGGCAGC TCTGATAGTG ATGCTGATGG CGCTGAGCCC
 TCCCCTGGCC TGGGCCAGGA AGATCCAACC ACATTTCTTG GAGTATCATA
 AGAGCGAGTG TCATTTCTTC AACGGGACGG AGCGGGTGCG GTTCCTGGAC
 AGATACTTCT ATAATGGAGA AGAGTACGTG CGCTTCGACA GCGACTGGGG
 CGAGTTCCGG GCGGTGGCCG AGCTGGGGCG GCAGAGCGCC GAGTACTGGA
 ACAGCCAGAA GGAGCTCCTG GAGCGGAGGC GGACCGAGGT GGACACGTAC
 TGCAGACACA ACTACGGGGT CTTTGAGAGT TTCAGTGTGC AGCGGCGAGT
 GGAGCCTATA GTGACTGTGT ATCCTGCAAA GACCCAGCCC CTGCAGCACC
 ACAACCTCCT GGTCTGCTCT GTGAATGGAT TCTACCCAGG CCACATTGAA
 GTCAGGTGGT TCCGGAACGG CCAC*

>DL;IPD:MHC04075
IPD:MHC04075 Ovar-DRB1*0805, 270 bases, 85188F48 checksum.
 CACATTTCTT GGAGTATCAT AAGAGCGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC CATAATGGAG AAGAGTTCGT
 GCGCTTCGAC AGCGACTGGG GCGAGTTCCG GGCGGTGGCC GAGCTGGGGC
 GGCGGAGCGC CGAGTACTGG AACAGCCAGA AGGAGCTCCT GGAGCGGAGG
 CGGACCGAGG TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG
 TTTCACTGTG CAGCGGCGAG*

>DL;IPD:MHC02428
IPD:MHC02428 Ovar-DRB1*0901, 801 bases, E0757628 checksum.
 ATGGTGTGCC TGTATTTCTC CAGAGGCTCC CGGATGGCAG CTCTGATAGT
 GATGCTGATG GTGCTGAGCC CTCCCCTGGC CTGGGCCAGG GAGATCCAAC
 CACATTTCCT GGAGTATTAT AGGAGCGAGT GTCATTTCTT CAACGGGACC
 GAGAGGGTGC GGCTCCTGGA AAGATACTTC CATAATGGAG AAGAGTTCGC
 GCGCTTCGAC AGTGACTGGG GCGAGTTTCG GGCAGTGACC GAGCTGGGGA
 GGCCGGCCGC TGAGCAATGG AACAGCCAGA AGAACATCCT GGAGCAGAAG
 CGGGCCGAGG TGAACACGGT GTGCAGACAC AACTATGGGG TCTTTGAGAG
 TTTCGCTGTG CAGCGGCGAG TGGAGCCTAT AGTGACTGTG TATCCTGCGA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAACGGA
 TTCTACCCAG GCCACATTGA AGTCAGGTGG TTCCGAAACG GCCATGAAGA
 GGAGGCTGGG GTGATCTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCAT GGTGATGCTT GAAACAGTTC CTCAGAGTGG AGAGGTCTAT
 ACCTGCCAAG TGGAGCACCC CAGCCGGATG AGCCCTATCA CAGTAGAATG
 GAGGGCACGG TCTGACTCTG CTCAGAGCAA GATGATGAGT GGAGTTGGGG
 GCTTTGTGCT GGGTCTGCTC TTCCTTGCAG TGGGACTCTT CATCTACTTC
 AGGAATCAGA AAGGACGCCC TACACTTCAG CCAACAGGGC TCCTGAGCTG
 A*

>DL;IPD:MHC02477
IPD:MHC02477 Ovar-DRB1*0902, 474 bases, C421202C checksum.
 AGAGGCTCCC GGATGGCAGC TCTGATAGTG ATGCTGATGG TGCTGAGCCC
 TCCCCTGGCC TGGGCCAGGG AGATCGAACC ACATTTCCTG GAGTATTATA
 GGAGCGAGTG TCATTTCTTC AACGGGACCG AGAGGGTGCG GCTCCTGGAA
 AGATACTTCC ATAATGGAGA AGAGTTCGCG CGCTTCGACA GTGACTGGGG
 CGAGTTTCGG GCAGTGACCG AGCTGGGGAG GCCGGCCGCT GAGCAATGGA
 ACAGCCAGAA GAACATCCTG GAGCAGAAGC GGGCCGAGGT GAACACGGTG
 TGCAGACACA ACTATGGGGT CTTTGAGAGT TTCGCTGTGC AGCGGCGAGT
 GGAGCCTATA GTGACTGTGT ATCCTGCGAA GACCCAGCCC CTGCAGCACC
 ACAACCTCCT GGTCTGCTCT GTGAACGGAT TCTACCCAGG CCACATTGAA
 GTCAGGTGGT TCCGAAACGG CCAT*

>DL;IPD:MHC02447
IPD:MHC02447 Ovar-DRB1*1001, 474 bases, 7F066049 checksum.
 AGAGGCTCCC GGATGGCAGC TCTGATAGTG ATGCTGATGG CGCTGAGCCC
 TCCCCTGGCC TGGGCCAGGA AGATCCAACC ACATTTCTTG GAGTATTCTA
 CGAGCGAGTG TCATTTCTTC AACGGGACGG AGCGGGTGCG GTTCCTGGAC
 AGATACTTCT ATAATGGAGA AGAGTACGTG CGCTTCGACA GCGACTGGGG
 CGAGTACCGA GCGGTGGCCG AGCTGGGGCG GCCGGACGCC AAGTACTGGA
 ACAGCCAGAA GGAGATCCTG GAGCGGAGGC GGACCGAGGT GGACACGTAC
 TGCAGACACA ACTACGGGGT CATTGAGAGT TTCAGTGTGC AGCGGCGAGT
 GGAGCCTATA GTGACTGTGT ATCCTGCAAA GACCCAGCCC CTGCAGCACC
 ACAACCTCCT GGTCTGCTCT GTGAATGGAT TCTACCCAGG CCACATTGAA
 GTCAGGTGGT TCCGGAATGG CCAC*

>DL;IPD:MHC02786
IPD:MHC02786 Ovar-DRB1*1002, 270 bases, 18E6DDBF checksum.
 CACATTTCTT GGAGTATTCT ACGAGCGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAATGGAG AAGAGTACGT
 GCGCTTCGAC AGCGACTGGG GCGAGTACCG AGCGGTGGCC GAGCTGGGGC
 GGCCGGACGC CAAGTACTGG AACAGCCAGA AGGACATCCT GGAGCGGAGG
 CGGACCGAGG TGGACACGTA CTGCAGACAC AACTACGGGG TCATTGAGAG
 TTTCAGTGTG CAGCGGCGAG*

>DL;IPD:MHC02978
IPD:MHC02978 Ovar-DRB1*1003, 270 bases, B58D6F96 checksum.
 CACATTTCTT GGAGTATTCT ACGAGCGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAATGGAG AAGAGTACGT
 GCGCTTCGAC AGCGACTGGG GCGAGTACCG AGCGGTGGCC GAGCTGGGGC
 GGCGGAGCGC CGAGTACTGG AACAGCCAGA AGGAGATCCT GGAGCGGAGG
 CGGACCGAGG TGGACACGTA CTGCAGACAC AACTACGGGG TCATTGAGAG
 TTTCAGTGTG CAGCGGCGAG*

>DL;IPD:MHC02449
IPD:MHC02449 Ovar-DRB1*1101, 270 bases, DB693FAE checksum.
 CACATTTCTT GGAGTATTCT ACGAGCGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAATGGAG AAGAGACCCT
 GCGCTTCGAC AGCGACTGGG GCGAGTACCG AGCGGTGGCC GAGCTGGGGC
 GGCCGGACGC CAAGTACTGG AACAGCCAGA AGGAGATCCT GGAGCGGAAG
 CGGGCCGCCG TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG
 TTTCAGTGTG CAGCGGCGAG*

>DL;IPD:MHC02478
IPD:MHC02478 Ovar-DRB1*1102, 474 bases, BE98E893 checksum.
 AGAGGCTCCC GGATGGCAGC TCTGATAGTG ATGCTGATGG CGCTGAGCCC
 TCCCCTGGCC TGGGCCAGGA AGATCCAACC ACATTTCTTG GAGTATTCTA
 CGAGCGAGTG TCATTTCTTC AACGGGACGG AGCGGGTGCG GTTCCTGGAC
 AGATACTTCT ATAATGGAGA AGAGACCCTG CGCTTCGACA GCGACTGGGG
 CGAGTACCGA GCGGTGGCCG AGCTGGGGCG GCCGGACGCC AAGTACTGGA
 ACAGCCAGAA GGAGATCCTG GAGCGGAAGC GGGCCGCCGT GGACACGTAC
 TGCAGACACA ACTACGGGGT CGGTGAGAGT TTCACTGTGC AGCGGCGAGT
 GGAGCCTATA GTGACTGTGT ATCCTGCAAA GACCCAGCCC CTGCAGCACC
 ACAACCTCCT GGTCTGCTCT GTGAATGGAT TCTACCCAGG CCACATTGAA
 GTCAGGTGGT TCCGGAACGG CCAC*

>DL;IPD:MHC02450
IPD:MHC02450 Ovar-DRB1*1201, 270 bases, 560DA4C8 checksum.
 CACATTTCTT GGAGTATCAT AAGAGCGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAATGGAG AAGAGTACGT
 GCGCTTCGAC AGCGACTGGG GCGAGTTCCG GGCGGTGGCC GAGCTGGGGC
 GGCCGGAAGC CAAGTACTGG AACAGCCAGA AGGAGATCCT GGAGCGGAAG
 CGGGCCGCCG TGGACACGTA CTGCAGACAC AACTACGGGG TCATTGAGAG
 TTTCAGTGTG CAGCGGCGAG*

>DL;IPD:MHC02787
IPD:MHC02787 Ovar-DRB1*1202, 270 bases, 89284ADB checksum.
 CACATTTCTT GGAGTATCAT AAGAGCGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAATGGAG AAGAGTACGT
 GCGCTTCGAC AGCGACTGGG GCGAGTTCCG GGCGGTGGCC GAGCTGGGGC
 GGCCGGAAGC CAAGTACTGG AACAGCCAGA AGGAGATCCT GGAGCGGAGG
 CGGACCGAGG TGGACACGTA CTGCAGACAC AACTACGGGG TCATTGAGAG
 TTTCAGTGTG CAGCGGCGAG*

>DL;IPD:MHC02788
IPD:MHC02788 Ovar-DRB1*1203, 270 bases, 76AB0266 checksum.
 CACATTTCTT GGAGTATCAT AAGAGCGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAATGGAG AAGAGTACGT
 GCGCTTCGAC AGCGACTGGG GCGAGTTCCG GGCGGTGGCC GAGCTGGGGC
 GGCCGGAAGC CAAGTACTGG AACAGCCAGA AGGAGATCCT GGAGAGCAGG
 AGGACCGCGG TGGACACGTA CTGCAGACAC AACTACGGGG TCATTGAGAG
 TTTCAGTGTG CAGCGGCGAG*

>DL;IPD:MHC02452
IPD:MHC02452 Ovar-DRB1*1301, 474 bases, 67DC5C7B checksum.
 AGAGGCTCCC GGATGGCAGC TCTGATAGTG ATGCTGATGG CGCTGAGCCC
 TCCCCTGGCC TGGGCCAGGA AGATCCAACC ACATTTCCTG GAGTATAGTA
 AGAGCGAGTG TCATTTCTTC AACGGGACCG AGCGGGTGCG GTTCCTGGAC
 AGATACTACA CTAACGGAGA AGAGAACGTG CGCTTCGACA GCGACTGGGG
 CGAGTTCCGG GCGGTGACCG AGCTGGGGCG GCCGGACGCT GAGCAATGGA
 ACAGCCAGAA GGACTTCCTG GAGAGCAGGA GGACCGCGGT GGACACGTAC
 TGCAGACACA ACTACGGGGT CTTTGAGAGT TTCAGTGTGC AGCGGCGAGT
 GGAGCCTACA GTGACTGTGT ATCCTGCAAA GACCCAGCCC CTGCAGCACC
 ACAACCTCCT GGTCTGCTCT GTGAATGGAT TCTACCCAGG CCACATTGAA
 GTCAGGTGGT TCCGGAACGG CCAC*

>DL;IPD:MHC02469
IPD:MHC02469 Ovar-DRB1*1302, 474 bases, 12150EA5 checksum.
 AGAGGCTCCC GGATGGCAGC TCTGATAGTG ATGCTGATGG CGCTGAGCCC
 TCCCTTGGCC TGGGCCAGGA AGATCCAACC ACATTTCCTG GAGTATAGTA
 AGAGCGAGTG TCATTTCTTC AACGGGACCG AGCGGGTGCG GTTCCTGGAC
 AGATACTACA CTAACGGAGA AGAGAACGTG CGCTTCGACA GCGACTGGGG
 CGAGTTCCGG GCGGTGACCG AGCTGGGGCG GCCGGACGCT GAGCAATGGA
 ACAGCCAGAA GGACTTCCTG GAACGGAAGC GGACCGCGGT GGACACGTAC
 TGCAGACACA ACTACGGGGT CATTGAGAGT TTCAGTGTGC AGCGGCGAGT
 GGAGCCTACA GTGACTGTGT ATCCTGCAAA GACCCAGCCC CTGCAGCACC
 ACAACCTCCT GGTCTGCTCT GTGAATGGAT TCTACCCAGG CCACATTGAA
 GTCAGGTGGT TCCGGAACGG CCAC*

>DL;IPD:MHC02453
IPD:MHC02453 Ovar-DRB1*1401, 474 bases, 281C23D3 checksum.
 AGAGGCTCCC GGATGGCAGC TCTGATAGTG ATGCTGATGG CGCTGAGCCC
 TCCCCTGGCC TGGGCCAGGA AGATCCAACC ACATTTCCTG GAGTATACTA
 AGAAAGAGTG TCATTTCTTC AATGGGACGG AGCGGGTGCG GTTGCTGGAA
 AGATACTTCT ATAATGGAGA AGAGTACGTG CGCTTCGACA GCGACTGGGG
 CGAGTTCCGG GCGGTGGCCG AGCTGGGGCG GCAGAGCGCC GAGTACTGGA
 ACAGCCAGAA GGAGATCCTG GAGAGCAGGA GGACCGCGGT GGACACGTAC
 TGCAGACACA ACTACGGGGT CATTGAGAGT TTCAGTGTGC AGCGGCGAGT
 GGAGCCTATA GTGACTGTGT ATCCTGCAAA GACCCAGCCC CTGCAGCACC
 ACAACCTCCT GGTCTGCTCT GTGAATGGAT TCTACCCAGG CCACATTGAA
 GTCAGGTGGT TCCGGAACGG CCAC*

>DL;IPD:MHC02782
IPD:MHC02782 Ovar-DRB1*1402, 270 bases, F34BAFE5 checksum.
 CACATTTCCT GGAGTATACT AAGAAAGAGT GTCATTTCTT CAATGGGACG
 GAGCGGGTGC GGTTGCTGGA AAGATACTTC TATAATGGAG AAGAGTACGT
 GCGCTTCGAC AGCGACTGGG GCGAGTTCCG GGCGGTGGCC GAGCTGGGGC
 GGCCGGAAGC CAAGTACTGG AACAGCCAGA AGGAGATCCT GGAGAGCAGG
 AGGACCGCGG TGGACACGTA CTGCAGACAC AACTACGGGG TCATTGAGAG
 TTTCAGTGTG CAGCGGCGAG*

>DL;IPD:MHC02455
IPD:MHC02455 Ovar-DRB1*1501, 474 bases, B1BF75F2 checksum.
 AGAGGCTCCC GGATGGCAGC TCTGATAGTG ATGCTGATGG CGCTGAGCCC
 TCCCCTGGCC TGGGCCAGGA AGATCCAACC ACATTTCTTG GAGTATTCTA
 CGAGCGAGTG TCATTTCTTC AACGGGACGG AGCGGGTGCG GTTCCTGGAC
 AGATACTTCT ATAATGGAGA AGAGTACGTG CGCTTCGACA GCGACTGGGG
 CGAGTACCGA GCGGTGGCCG AGCTGGGGCG GCAGAGCGCC GAGCACTGGA
 ACAGCCAGAA GGAGCTCCTG GAGCGGAGGC GGGCCGAGGT GGACACGTAC
 TGCAGACACA ACTACGGGGT CATTGAGAGT TTCAGTGTGC AGCGGCGAGT
 GGAGCCTATA GTGACTGTGT ATCCTGCAAA GACCCAGCCC CTGCAGCACC
 ACAACCTCCT GGTCTGCTCT GTGAATGGAT TCTACCCAGG CCACATTGAA
 GTCAGGTGGT TCCGGAACGG CCAC*

>DL;IPD:MHC02460
IPD:MHC02460 Ovar-DRB1*1502, 474 bases, 50433219 checksum.
 AGAGGCTCCC GGATGGCAGC TCTGATAGTG ATGCTGATGG CGCTGAGCCC
 TCCCCTGGCC TGGGCCAGGA AGATCCAACC ACATTTCTTG GAGTATCATA
 AGAGCGAGTG TCATTTCTTC AACGGGACGG AGCGGGTGCG GTTCCTGGAC
 AGATACTTCT ATAATGGAGA AGAGTACGTG CGCTTCGACA GCGACTGGGG
 CGAGTTCCGG GCGGTGGCCG AGCTGGGGCG GCAGAGCGCC GAGCACTGGA
 ACAGCCAGAA GGAGCTCCTG GAGCGGAGGC GGGCCGAGGT GGACACGTAC
 TGCAGACACA ACTACGGGGT CATTGAGAGT TTCAGTGTGC AGCGGCGAGT
 GGAGCCTATA GTGACTGTGT ATCCTGCAAA GACCCAGCCC CTGCAGCACC
 ACAACCTCCT GGTCTGCTCT GTGAATGGAT TCTACCCAGG CCACATTGAA
 GTCAGGTGGT TCCGGAACGG CCAC*

>DL;IPD:MHC04074
IPD:MHC04074 Ovar-DRB1*1503, 270 bases, B0DDEABB checksum.
 CACATTTCTT GGAGTATCAT AAGAGCGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAATGGAG AAGAGTACGT
 GCGCTTCGAC AGCGACTGGG GCGAGTTCCG GGCGGTGGCC GAGCTGGGGC
 GGCAGAGCGC CGAGCACTGG AACAGCCAGA AGGAGCTCCT GGAGCGGAGG
 CGGGCCGCCG TGGACACGTA CTGCAGACAC AACTACGGGG TCATTGAGAG
 TTTCAGTGTG CAGCGGCGAG*

>DL;IPD:MHC02456
IPD:MHC02456 Ovar-DRB1*1601, 270 bases, D2BF21A7 checksum.
 CACATTTCTT GGAGTATACT AAGAAAGAGT GTCGTTTCTT CAACGGGACG
 GAGCGGGTGC GGTACCTGGA CAGATACTTC TATAATGGAG AAGAGTACGT
 GCGCTTCGAC AACGACTGGG GCGAGTACCG AGCGGTGGCC GAGCTGGGGC
 GGCCGGACGC CAAGTACTGG AACAGCCAGA AGGAGCTCCT GGAGCGGAAG
 CGGGCCAATG TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG
 TTTCACTGTG CAGCGGCGAG*

>DL;IPD:MHC02471
IPD:MHC02471 Ovar-DRB1*1602, 474 bases, 249ABF8A checksum.
 AGAGGCTCCC GGATGGCAGC TCTGATAGTG ATGCTGATGG CGCTGAGCCC
 TCCCCTGGCC TGGGCCAGGA AGATCCAACC ACATTTCTTG GAGTATACTA
 AGAAAGAGTG TCGTTTCTTC AACGGGACGG AGCGGGTGCG GTACCTGGAC
 AGATACTTCT ATAATGGAGA AGAGTACGTG CGCTTCGACA ACGACTGGGG
 CGAGTACCGA GCGGTGGCCG AGCTGGGGCG GCCGGACGCC AAGTACTGGA
 ACAGCCAGAA AGAGCTCCTG GAGCGGAAGC GGGCCAATGT GGACACGTAC
 TGCAGACACA ACTACGGGGT CATTGAGAGT TTCAGTGTGC AGCGGCGAGT
 GGAGCCTATA GTGACTGTGT ATCCTGCAAA GACCCAGCCC CTGCAGCACC
 ACAACCTCCT GGTCTGCTCT GTGAATGGAT TCTACCCAGG CCACATTGAA
 GTCAGGTGGT TCCGGAACGG CCAC*

>DL;IPD:MHC02785
IPD:MHC02785 Ovar-DRB1*1603, 270 bases, 61F204D8 checksum.
 CACATTTCTT GGAGTATACT AAGAAAGAGT GTCGTTTCTC CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAATGGAG AAGAGTACGC
 GCGCTTCGAC AGCGACTGGG GCGAGTACCG AGCGGTGGCC GAGCTGGGGC
 GGCCGGACGC CAAGTACTGG AACAGCCAGA AGGAGCTCCT GGAGCGGAAG
 CGGGCCAATG TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG
 TTTCACTGTG CAGCGGCGAG*

>DL;IPD:MHC02981
IPD:MHC02981 Ovar-DRB1*1604, 270 bases, 678904C7 checksum.
 CACATTTCTT GGAGTATCGT AAGAGCGAGT GTCGTTTCTC CAACGGGACG
 GAGCGGGTGC GGTACCTGGA CAGATACTTC TATAATGGAG AAGAGTACGT
 GCGCTTCGAC AGCGACTGGG GCGAGTACCG AGCGGTGGCC GAGCTGGGGC
 GGCCGGACGC CAAGTACTGG AACAGCCAGA AGGAGCTCCT GGAGCGGAAG
 CGGGCCAATG TGGACACGTA CTGCAGACAC AACTACGGGG TCATTGAGAG
 TTTCAGTGTG CAGCGGCGAG*

>DL;IPD:MHC04076
IPD:MHC04076 Ovar-DRB1*1605, 270 bases, F1C63CE6 checksum.
 CACATTTCTT GGAGTATCAT AAGAGCGAGT GTCGTTTCTC CAACGGGACG
 GAGCGGGTGC GGTACCTGGA CAGATACTTC TATAATGGAG AAGAGTACGT
 GCGCTTCGAC AACGACTGGG GCGAGTACCG AGCGGTGGCC GAGCTGGGGC
 GGCCGGACGC CAAGTACTGG AACAGCCAGA AGGAGATCCT GGAGCGGAAG
 CGGGCCGCCG TGGACACGTA CTGCAGACAC AACTACGGGG TCATTGAGAG
 TTTCAGTGTG CAGCGGCGAG*

>DL;IPD:MHC02458
IPD:MHC02458 Ovar-DRB1*1701, 270 bases, B61D3E0B checksum.
 CACATTTCTT GGAGTATGCT AAGAGAGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAATGGAG AAGAGTACGT
 GCGCTTCGAC AGCGACTGGG GCGAGTTCCG GGCGGTGGCC GAGCTGGGGC
 GGCGGAGCGC CGAGTACTGG AACAGCCAGA AGGACTTCCT GGAGCGGGCG
 CGGGCCGCCG TGGACACGTA CTGCAGACAC AACTACGGGG TCATTGAGAG
 TTTCAGTGTG CAGCGGCGAG*

>DL;IPD:MHC02466
IPD:MHC02466 Ovar-DRB1*1702, 474 bases, 3BA8B5D9 checksum.
 AGAGGCTCCC GGATGGCAGC TCTGATAGTG ATGCTGATGG CGCTGAGCCC
 TCCCCTGGCC TGGGCCAGGA AGATCCAACC ACATTTCTTG GAGTATCATA
 AGAGCGAGTG TCATTTCTTC AACGGGACGG AGCGGGTGCG GTTCCTGGAC
 AGATACTTCT ATAATGGAGA AGAGTACGTG CGCTTCGACA GCGACTGGGG
 CGAGTTCCGG GCGGTGGCCG AGCTGGGGCG GCAGAGCGCC GAGTACTGGA
 ACAGCCAGAA GGACTTCCTG GAGCGGGCGC GGGCCGCCGT GGACACGTAC
 TGCAGACACA ACTACGGGGT CTTTGAGAGT TTCAGTGTGC AGCGGCGAGT
 GGAGCCTATA GTGACTGTGT ATCCTGCAAA GACCCAGCCC CTGCAGCACC
 ACAACCTCCT GGTCTGCTCT GTGAATGGAT TCTACCCAGG CCACATTGAA
 GTCAGGTGGT TCCGGAACGG CCAC*

>DL;IPD:MHC02461
IPD:MHC02461 Ovar-DRB1*1801, 270 bases, AF81983E checksum.
 CACATTTCTT GGAGTATCGT AAGAGCGAGT GTCGTTTCTC CAACGGGACG
 GAGCGGGTGC GGTACCTGGA CAGATACTTC TATAATGGAG AAGAGTACGT
 GCGCTTCGAC AGCGACTGGG GCGAGTACCG AGCGGTGGCC GAGCTGGGGC
 GGCGGAGCGC CGAGTACTGG AACAGCCAGA AGGAGCTCCT GGAGCGGAAG
 CGGGCCAATG TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG
 TTTCACTGTG CAGCGGCGAG*

>DL;IPD:MHC02463
IPD:MHC02463 Ovar-DRB1*1901, 474 bases, 6617C3C1 checksum.
 AGAGGCTCCC GGATGGCAGC TCTGATAGTG ATGCTGATGG CGCTGAGCCC
 TCCCCTGGCC TGGGCCAGGA AGATCCAACC ACATTTCTTG GAGTATGCTA
 AGAGCGAGTG TCATTTCTTC AACGGGACGG AGCGGGTGCG GTTCCTGGAC
 AGATACTTCT ATAATGGAGA AGAGTACGTG CGCTTCGACA GCGACTGGGG
 CGAGTTCCGG GCGGTGGCCG AGCTGGGGCG GCGGAGCGCC GAGTACTGGA
 ACAGCCAGAA GGACTTCCTG GAGCAGACGC GGGCCGAGGT GGACACGTAC
 TGCAGACACA ACTACGGGGT CGGTGAGAGT TTCACTGTGC AGCGGCGAGT
 GGAGCCTATA GTGACTGTGT ATCCTGCAAA GACCCAGCCC CTGCAGCACC
 ACAACCTCCT GGTCTGCTCT GTGAATGGAT TCTACCCAGG CCACATTGAA
 GTCAGGTGGT TCCGGAACGG CCAC*

>DL;IPD:MHC02470
IPD:MHC02470 Ovar-DRB1*1902, 474 bases, C44E42FE checksum.
 AGAGGCTCCC GGATGGCAGC TCTGATAGTG ATGCTGATGG CGCTGAGCCC
 TCCCCTGGCC TGGGCCAGGA AGATCCAACC ACATTTCTTG GAGTATGCTA
 AGAGCGAGTG TCATTTCTTC AACGGGACGG AGCGGGTGCG GTTCCTGGAC
 AGATACTTCT ATAATGGAGA AGAGTACGTG CGCTTCGACA GCGACTGGGG
 CGAGTTCCGG GCGGTGGCCG AGCTGGGGCG GCGGAGCGCC GAGTACTGGA
 ACAGCCAGAA GGACTTCCTG GAGCGGGCGC GGGCCGCCGT GGACACGTAC
 TGCAGACACA ACTACGGGGT CGGTGAGAGT TTCACTGTGC AGCGGCGAGT
 GGAGCCTATA GTGACTGTGT ATCCTGCAAA GACCCAGCCC CTGCAGCACC
 ACAACCTCCT GGTCTGCTCT GTGAATGGAT TCTACCCAGG CCACATTGAA
 GTCAGGTGGT TCCGGAACGG CCAC*

>DL;IPD:MHC02475
IPD:MHC02475 Ovar-DRB1*1903, 474 bases, E5CF7402 checksum.
 AGAGGCTCCC GGATGGCAGC TCTGATAGTG ATGCTGATGG TGCTGAGCCC
 TCCCCTGGCC TGGGCCAGGG AGATCCAACC ACATTTCTTG GAGTATCATA
 AGAGCGAGTG TCATTTCTTC AACGGGACGG AGCGGGTGCG GTTCCTGGAC
 AGATACTTCT ATAATGGAGA AGAGTACGTG CGCTTCGACA GCGACTGGGG
 CGAGTTCCGG GCGGTGGCCG AGCTGGGGCG GCGGAGCGCC GAGTACTGGA
 ACAGCCAGAA GGACTTCCTG GAGCAGACGC GGGCCGAGGT GGACACGTAC
 TGCAGACACA ACTACGGGGT CGGTGAGAGT TTCACTGTGC AGCGGCGAGT
 GGAGCCTATA GTGACTGTGT ATCCTGCAAA GACCCAGCCC CTGCAGCACC
 ACAACCTCCT GGTCTGCTCT GTGAATGGAT TCTACCCAGG CCACATTGAA
 GTCAGGTGGT TCCGGAACGG CCAC*

>DL;IPD:MHC02467
IPD:MHC02467 Ovar-DRB1*2001, 474 bases, BBF67A0E checksum.
 AGAGGCTCCC GGATGGCAGC TCTGATAGTG ATGCTGATGG CGCTGAGCCC
 TCCCCTGGCC TGGGCCAGGA AGATCCAACC ACATTTCTTG GAGTATGCTA
 AGAGCGAGTG TCGTTTCTTC AACGGGACGG AGCGGGTGCG GTTCCTGGAA
 AGATACTTCT ATAATGGAGA AGAGTACGTG CGCTTCGACA GCGACTGGGG
 CGAGTACCGA GCGGTGGCCG AGCTGGGGCG GCCGGACGCC AAGTACTGGA
 ACAGCCAGAA GGACTTCCTG GAGCGGAAGC GGGCCAATGT GGACACGTAC
 TGCAGACACA ACTACGGGGT CATTGAGAGT TTCAGTGTGC AGCGGCGAGT
 GGAGCCTATA GTGACTGTGT ATCCTGCAAA GACCCAGCCC CTGCAGCACC
 ACAACCTCCT GGTCTGCTCT GTGAATGGAT TCTACCCAGG CCACATTGAA
 GTCAGGTGGT TCCGGAACGG CCAC*

>DL;IPD:MHC02468
IPD:MHC02468 Ovar-DRB1*2002, 474 bases, 8DFC3F01 checksum.
 AGAGGCTCCC GGATGGCAGC TCTGATAGTG ATGCTGATGG CGCTGAGCCC
 TCCCCTGGCC TGGGCCAGGA AGATCCAACC ACATTTCTTG GAGTATGCTA
 AGAGCGAGTG TCGTTTCTTC AACGGGACGG AGCGGGTGCG GTTCCTGGAA
 AGATACTTCT ATAATGGAGA AGAGTACGTG CGCTTCGACA GCGACTGGGG
 CGAGTACCGA GCGGTGGCCG AGCTGGGGCG GCCGGACGCC AAGTACTGGA
 ACAGCCAGAA GGACTTCCTG GAGCGGAAGC GGGCCAATGT GGACACGTAC
 TGCAGACACA ACTACGGGGT CTTTGAGAGT TTCAGTGTGC AGCGGCGAGT
 GGAGCCTATA GTGACTGTGT ATCCTGCAAA GACCCAGCCC CTGCAGCACC
 ACAACCTCCT GGTCTGCTCT GTGAATGGAT TCTACCCAGG CCACATTGAA
 GTCAGGTGGT TCCGGAACGG CCAC*

>DL;IPD:MHC02474
IPD:MHC02474 Ovar-DRB1*2101, 474 bases, AF8FD20E checksum.
 AGAGGCTCCC GGATGGCAGC TCTGATAGTG ATGCTGATGG CGCTGAGCCC
 TCCCCTGGCC TGGGCCAGGA AGATCCAACC ACATTTCCTG GAGTATTCTA
 CGAGCGAGTG TCATTTCTCC AACGGGACGG AGCGGGTGCG GTTGCTGGAC
 AGATACTTCC ATAATGGAGA AGAGTTCGTG CGCTTCGACA GCGACTGGGG
 CGAGTTCCGG GCGGTGGCCG AGCTGGGGCG GCCGGACGCC GAGTATTGGA
 ACAGCCAGAA GGACTTCCTG GAGAGCAGGA GGACCGCGGT GGACACGTAC
 TGCAGACACA ACTACGGGGT CATTGAGAGT TTCACTGTGC AGCGGCGAGT
 GGAGCCTATA GTGACTGTGT ATCCTGCAAA GACCCAGCCC CTGCAGCACC
 ACAACCTCCT GGTCTGCTCT GTGAACGGTT TCTACCCAGG CCACATTGAA
 GTCAGGTGGT TCCGGAACGG CCAT*

>DL;IPD:MHC02482
IPD:MHC02482 Ovar-DRB1*2201, 270 bases, 2D01EC56 checksum.
 CACATTTCTT GGAGTATCGT AAGAGCGAGT GTCGTTTCTC CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAATGGAG AAGAGAACGT
 GCGCTTCGAC AGCGACTGGG GCGAGTACCG AGCGGTGGCC GAGCTGGGGC
 GGCCGGACGC CAAGTACTGG AACAGCCAGA AGGACTTCCT GGAGCGGAAG
 CGGGCCAATG TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG
 TTTCACTGTG CAGCGGCGAG*

>DL;IPD:MHC04077
IPD:MHC04077 Ovar-DRB1*2202, 270 bases, 2FF816C2 checksum.
 CACATTTCTT GGAGTATCAT AAGAGCGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAATGGAG AAGAGTACGT
 GCGCTTCGAC AGCGACTGGG GCGAGTACCG AGCGGTGGCC GAGCTGGGGC
 GGCCGGACGC CAAGTACTGG AACAGCCAGA AGGACTTCCT GGAGCGGAAG
 CGGGCCAATG TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG
 TTTCACTGTG CAGCGGCGAG*

>DL;IPD:MHC02980
IPD:MHC02980 Ovar-DRB1*2301, 270 bases, 4B807C39 checksum.
 CACATTTCTT GGAGTATGCT AAGAGCGAGT GTCGTTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA AAGATACTTC TATAATGGAG AAGAGTACGT
 GCGCTTCGAC AGCGACTGGG GCGAGTACCG AGCGGTGGCC GAGCTGGGGC
 GGCAGAGCGC CGAGCACTGG AACAGCCAGA AGGAGCTCCT GGAGCGGAGG
 CGGGCCGAGG TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG
 TTTCACTGTG CAGCGGCGAG*

>DL;IPD:MHC04078
IPD:MHC04078 Ovar-DRB1*2401, 270 bases, E225DB0C checksum.
 CACATTTCTT GGAGTATTCT ACGAGCGAGT GTCATTTCTT CAACGGGACG
 GAGCGGGTGC GGTTCCTGGA CAGATACTTC TATAATGGAG AAGAGTACGT
 GCGCTTCGAC AGCGACTGGG GCGAGTACCG AGCGGTGGCC GAGCTGGGGC
 GGCCGGACGC CAAGTACTGG AACAGCCAGA AGGACTTCCT GGAGCGGGCG
 CGGGCCGCCG TGGACACGTA CTGCAGACAC AACTACGGGG TCGGTGAGAG
 TTTCACTGTG CAGCGGCGAG*

