>P1;IPD:MHC02426
IPD:MHC02426 Ovar-DRB1*0101, 267 bases, 6F806A01 checksum.
 MVCLYFSRGS RMAALIVMLM ALSPPLAWAR KIQPHFLEYT KKECRFSNGT
 ERVRFLDRYF HNGEETLRFD SDWGEYRAVA ELGRPDAKYW NSQKDFLERA
 RAAVDTYCRH NYGVIESFTV QRRVEPIVTV YPAKTQPLQH HNLLVCSVNG
 FYPGHIEVRW FRNGHEEEAG VISTGLIQNG DWTFQTMVML ETVPQSGEVY
 TCQVDHPSRT SPITVEWRAR SDSAQSKMMS GVGGFVLGLL FLAVGLFIYF
 RNQKGRPTLQ PTGLLSX*

>P1;IPD:MHC02448
IPD:MHC02448 Ovar-DRB1*0102, 89 bases, DE64B07A checksum.
 HFLEYTKKEC RFSNGTERVR FLDRYFHNGE ETLRFDSDWG EYRAVAELGR
 PDAKYWNSQK DFLERARAAV DTYCRHNYGV GESFSVQRR*

>P1;IPD:MHC02464
IPD:MHC02464 Ovar-DRB1*0103, 158 bases, 43E5B1F0 checksum.
 RGSRMAALIV MLMALSPPLA WARKIQPHFL EYTKKECRFS NGTERVRFLD
 RYFHNGEETL RFDSDWGEYR AVAELGRPDA EYWNSQKDFL ERARAAVDTY
 CRHNYGVGES FSVQRRVEPI VTVYPAKTQP LQHHNLLVCS VNGFYPGHIE
 VRWFRNGH*

>P1;IPD:MHC02783
IPD:MHC02783 Ovar-DRB1*0104, 89 bases, 5212257B checksum.
 HFLEYTKKEC RFSNGTERVR FLDRYFHNGE EYARFDSDWG EYRAVAELGR
 PDAKYWNSQK DFLERARAAV DTYCRHNYGV GESFTVQRR*

>P1;IPD:MHC02445
IPD:MHC02445 Ovar-DRB1*0201, 267 bases, 15AA465F checksum.
 MVCLYFSRGS RMAALIVMLM ALSPPLAWAR KIQPHFLEYS TSECHFFNGT
 ERVRFLDRYF YNGEETLRFD SDWGEYRAVA ELGRPDAKYW NSQKDFLEQT
 RAAVDTYCRH NYGVIESFSV QRRVEPIVTV YPAKTQPLQH HNLLVCSVNG
 FYPGHIEVRW FRNGHEEEAG VISTGLIQNG DWTFQTMVML ETVPQSGEVY
 TCQVDHPSRT SPITVEWRAR SDSAQSKMMS GVGGFVLGLL FLAVGLFIYF
 RNQKGRPTLQ PTGLLSX*

>P1;IPD:MHC02429
IPD:MHC02429 Ovar-DRB1*0301, 267 bases, 52073F96 checksum.
 MVCLYFSRGS RMAALIVMLM ALSPPLAWAR KIQPHFLEYT KKECRFSNGT
 ERVRFLDRYF HNGEEYARFD SDWGEYRAVA ELGRPDAKYW NSQKEILERR
 RTEVDTYCRH NYGVIESFSV QRRVEPIVTV YPAKTQPLQH HNLLVCSVNG
 FYPGHIEVRW FRNGHEEEAG VISTGLIQNG DWTFQTMVML ETVPQSGEVY
 TCQVDHPSRT SPITVEWRAR SDSAQSKMMS GVGGFVLGLL FLAVGLFIYF
 RNQKGRPTLQ PTGLLSX*

>P1;IPD:MHC02424
IPD:MHC02424 Ovar-DRB1*0302, 158 bases, 6114424A checksum.
 RGSRMAALIV MLMALSPPLA WARKIQPHFL EYTKKECRFS NGTERVRFLD
 RYFYNGEEYV RFDSDWGEYR AVAELGRPDA KYWNSQKEIL ERRRTEVDTY
 CRHNYGVIES FSVQRRVEPI VTVYPAKTQP LQHHNLLVCS VNGFYPGHIE
 VRWFRNGH*

>P1;IPD:MHC02430
IPD:MHC02430 Ovar-DRB1*0303, 267 bases, 6A177408 checksum.
 MVCLYFSRGS RMAALIVMLM ALSPPLAWAR KIQPHFLEYT KKECRFSNGT
 ERVRFLDRYF YNGEEYARFD SDWGEYRAVA ELGRPDAKYW NSQKEILERR
 RTEVDTYCRH NYGVGESFTV QRRVEPIVTV YPAKTQPLQH HNLLVCSVNG
 FYPGHIEVRW FRNGHEEEAG VISTGLIQNG DWTFQTMVML ETVPQSGEVY
 TCQVDHPSRT SPITVEWRAR SDSAQSKMMS GVGGFVLGLL FLAVGLFIYF
 RNQKGRPTLQ PTGLLSX*

>P1;IPD:MHC02454
IPD:MHC02454 Ovar-DRB1*0304, 158 bases, E6ED7A03 checksum.
 RGSRMAALIV MLMALSPPLA WARKIQPHFL EYTKKECRFS NGTERVRFLD
 RYFYNGEEYA RFDSDWGEYR AVAELGRRSA EYWNSQKEIL ERRRTEVDTY
 CRHNYGVIES FSVQRRVEPI VTVYPAKTQP LQHHNLLVCS VNGFYPGHIE
 VRWFRNGH*

>P1;IPD:MHC02462
IPD:MHC02462 Ovar-DRB1*0305, 89 bases, E6858643 checksum.
 HFLEYTKKEC RFSNGTERVR FLDRYFYNGE EYARFDSDWG EYRAVAELGR
 RSAEYWNSQK EILEQTRAEV DTYCRHNYGV GESFSVQRR*

>P1;IPD:MHC02476
IPD:MHC02476 Ovar-DRB1*0306, 158 bases, 3BF3ED7F checksum.
 RGSRMAALIV MLMALSPPLA WARKIQPHFL EYTKKECRFS NGTERVRFLD
 RYFHNGEEYA RFDSDWGEYR AVAELGRPDA KYWNSQKEIL ERRRTEVDTY
 CRHNYGVGES FTVQRRVEPI VTVYPAKTQP LQHHNLLVCS VNGFYPGHIE
 VRWFRNGH*

>P1;IPD:MHC02472
IPD:MHC02472 Ovar-DRB1*0307, 158 bases, 33F45728 checksum.
 RGSRMAALIV MLMALSPPLA WARKIQPHFL EYHKSECRFS NGTERVRFLD
 RYFYNGEEYA RFDSDWGEYR AVAELGRPDA EYWNSQKELL ERRRTEVDTY
 CRHNYGVGES FTVQRRVEPI VTVYPAKTQP LQHHNLLVCS VNGFYPGHIE
 VRWFRNGH*

>P1;IPD:MHC02483
IPD:MHC02483 Ovar-DRB1*0308, 89 bases, EFCF9C4F checksum.
 HFLEYTKKEC RFSNGTERVR FLDRYFYNGE EYARFDSDWG EYRAVAELGR
 RSAEYWNSQK EILERKRAAV DTYCRHNYGV GESFTVQRR*

>P1;IPD:MHC02789
IPD:MHC02789 Ovar-DRB1*0309, 89 bases, 54A55A53 checksum.
 HFLEYTKKEC RFSNGTERVR FLDRYFYNGE EYARFDSDWG EYRAVAELGR
 RSAEYWNSQK EILEQTRAEV DTYCRHNYGV GESFTVQRR*

>P1;IPD:MHC02979
IPD:MHC02979 Ovar-DRB1*0310, 89 bases, 9CEC3348 checksum.
 HFLEYHKSEC RFSNGTERVR FLDRYFYNGE EYARFDSDWG EYRAVAELGR
 RSAEYWNSQK EILERKRAAV DTYCRHNYGV GESFTVQRR*

>P1;IPD:MHC02425
IPD:MHC02425 Ovar-DRB1*0401, 158 bases, E9937B0B checksum.
 RGSRMAALIV MLMALSPPLA WARKIQPHFL EYHKSECRFS NGTERVRYLD
 RYFYNGEEYV RFDNDWGEYR AVAELGRPDA KYWNSQKDFL EQTRAEVDTY
 CRHNYGVIES FSVQRRVEPI VTVYPAKTQP LQHHNLLVCS VNGFYPGHIE
 VRWFRNGH*

>P1;IPD:MHC02459
IPD:MHC02459 Ovar-DRB1*0402, 89 bases, D6C4B1B6 checksum.
 HFLEYHKSEC RFSNGTERVR YLDRYFYNGE EYVRFDNDWG EYRAVAELGR
 RSAEYWNSQK DFLEQTRAEV DTYCRHNYGV IESFSVQRR*

>P1;IPD:MHC02427
IPD:MHC02427 Ovar-DRB1*0501, 267 bases, 2FC6B29E checksum.
 MVCLYFSRGS RMAALIVMLM ALSPPLAWAR KIQPHFLEYA KSECRFFNGT
 ERVRFLERYF YNGEETLRFD SDWGEYRAVA ELGRPDAKYW NSQKELLERK
 RANVDTYCRH NYGVGESFTV QRRVEPIVTV YPAKTQPLQH HNLLVCSVNG
 FYPGHIEVRW FRNGHEEEAG VISTGLIQNG DWTFQTMVML ETVPQSGEVY
 TCQVDHPSRT SPITVEWRAR SDSAQSKMMS GVGGFVLGLL FLAVGLFIYF
 RNQKGRPTLQ PTGLLSX*

>P1;IPD:MHC02784
IPD:MHC02784 Ovar-DRB1*0502, 89 bases, E54A31AD checksum.
 HFLEYAKSEC RFFNGTERVR FLERYFYNGE ETLRFDSDWG EYRAVAELGR
 PDAKYWNSQK ELLERKRANV DTYCRHNYGV DESFTVQRR*

>P1;IPD:MHC04079
IPD:MHC04079 Ovar-DRB1*0503, 89 bases, B39E2057 checksum.
 HFLEYRKSEC RFFNGTERVR FLERYFHNGE ETLRFDSDWG EYRAVAELGR
 PDAKYWNSQK ELLERKRANV DTYCRHNYGV IESFSVQRR*

>P1;IPD:MHC02446
IPD:MHC02446 Ovar-DRB1*0601, 267 bases, DB454FB8 checksum.
 MVCLYFSRGS RMAALIVMLM ALSPPLAWAR KIQPHFLEYA KSECRFFNGT
 ERVRFLERYF YNGEEYVRFD SDWGEYRAVA ELGRRSAEYW NSQKDFLERK
 RANVDTYCRH NYGVGESFTV QRRVEPIVTV YPAKTQPLQH HNLLVCSVNG
 FYPGHIEVRW FRNGHEEEAG VISTGLIQNG DWTFQTMVML ETVPQSGEVY
 TCQVDHPSRT SPITVEWRAR SDSAQSKMMS GVGGFVLGLL FLAVGLFIYF
 RNQKGRPTLQ PTGLLSX*

>P1;IPD:MHC02431
IPD:MHC02431 Ovar-DRB1*0701, 267 bases, F586199D checksum.
 MVCLYFSRGS RMAALIVMLM ALSPPLAWAR KIQPHFLEYT KKECHFFNGT
 ERVRLLERYF YNGEEYVRFD SDWGEFRAVA ELGRPDAKYW NSQKDFLESR
 RTAVDTYCRH NYGVGESFTV QRRVEPIVTV YPAKTQPLQH HNLLVCSVNG
 FYPGHIEVRW FRNGHEEEAG VISTGLIQNG DWTFQTMVML ETVPQSGEVY
 TCQVDHPSRT SPITVEWRAR SDSAQSKMMS GVGGFVLGLL FLAVGLFIYF
 RNQKGRPTLQ PTGLLSX*

>P1;IPD:MHC02457
IPD:MHC02457 Ovar-DRB1*0702, 89 bases, F2B94513 checksum.
 HFLEYHKSEC HFFNGTERVR FLDRYFYNGE EYVRFDSDWG EFRAVAELGR
 PDAKYWNSQK DFLESRRTAV DTYCRHNYGV GESFTVQRR*

>P1;IPD:MHC02444
IPD:MHC02444 Ovar-DRB1*0801, 267 bases, E09DDBDB checksum.
 MVCLYFSRGS RMAALIVMLM ALSPPLAWAR KIQPHFLEYH KSECHFFNGT
 ERVRFLDRYF HNGEEFVRFD SDWGEFRAVA ELGRRSAEYW NSQKELLERR
 RTEVDTYCRH NYGVFESFSV QRRVEPIVTV YPAKTQPLQH HNLLVCSVNG
 FYPGHIEVRW FRNGHEEEAG VISTGLIQNG DWTFQTMVML ETVPQSGEVY
 TCQVDHPSRT SPITVEWRAR SDSAQSKMMS GVGGFVLGLL FLAVGLFIYF
 RNQKGRPTLQ PTGLLSX*

>P1;IPD:MHC02451
IPD:MHC02451 Ovar-DRB1*0802, 89 bases, ED4621B6 checksum.
 HFLEYAKSEC HFFNGTERVR FLDRYFYNGE EYVRFDSDWG EFRAVAELGR
 RSAEYWNSQK ELLERRRTEV DTYCRHNYGV FESFSVQRR*

>P1;IPD:MHC02465
IPD:MHC02465 Ovar-DRB1*0803, 158 bases, 1822998C checksum.
 RGSRMAALIV MLMALSPPLA WARKIQPHFL EYHKSECHFF NGTERVRFLD
 RYFYNGEEYV RFDSDWGEFR AVAELGRRSA EYWNSQKELL ERRRTEVDTY
 CRHNYGVFES FSVQRRVEPI VTVYPAKTQP LQHHNLLVCS VNGFYPGHIE
 VRWFRNGH*

>P1;IPD:MHC02473
IPD:MHC02473 Ovar-DRB1*0804, 158 bases, AE60DC19 checksum.
 RGSRMAALIV MLMALSPPLA WARKIQPHFL EYHKSECHFF NGTERVRFLD
 RYFYNGEEYV RFDSDWGEFR AVAELGRQSA EYWNSQKELL ERRRTEVDTY
 CRHNYGVFES FSVQRRVEPI VTVYPAKTQP LQHHNLLVCS VNGFYPGHIE
 VRWFRNGH*

>P1;IPD:MHC04075
IPD:MHC04075 Ovar-DRB1*0805, 89 bases, 979B231F checksum.
 HFLEYHKSEC HFFNGTERVR FLDRYFHNGE EFVRFDSDWG EFRAVAELGR
 RSAEYWNSQK ELLERRRTEV DTYCRHNYGV GESFTVQRR*

>P1;IPD:MHC02428
IPD:MHC02428 Ovar-DRB1*0901, 267 bases, DCC8A745 checksum.
 MVCLYFSRGS RMAALIVMLM VLSPPLAWAR EIQPHFLEYY RSECHFFNGT
 ERVRLLERYF HNGEEFARFD SDWGEFRAVT ELGRPAAEQW NSQKNILEQK
 RAEVNTVCRH NYGVFESFAV QRRVEPIVTV YPAKTQPLQH HNLLVCSVNG
 FYPGHIEVRW FRNGHEEEAG VISTGLIQNG DWTFQTMVML ETVPQSGEVY
 TCQVEHPSRM SPITVEWRAR SDSAQSKMMS GVGGFVLGLL FLAVGLFIYF
 RNQKGRPTLQ PTGLLSX*

>P1;IPD:MHC02477
IPD:MHC02477 Ovar-DRB1*0902, 158 bases, A009D403 checksum.
 RGSRMAALIV MLMVLSPPLA WAREIEPHFL EYYRSECHFF NGTERVRLLE
 RYFHNGEEFA RFDSDWGEFR AVTELGRPAA EQWNSQKNIL EQKRAEVNTV
 CRHNYGVFES FAVQRRVEPI VTVYPAKTQP LQHHNLLVCS VNGFYPGHIE
 VRWFRNGH*

>P1;IPD:MHC02447
IPD:MHC02447 Ovar-DRB1*1001, 158 bases, AF99DF3D checksum.
 RGSRMAALIV MLMALSPPLA WARKIQPHFL EYSTSECHFF NGTERVRFLD
 RYFYNGEEYV RFDSDWGEYR AVAELGRPDA KYWNSQKEIL ERRRTEVDTY
 CRHNYGVIES FSVQRRVEPI VTVYPAKTQP LQHHNLLVCS VNGFYPGHIE
 VRWFRNGH*

>P1;IPD:MHC02786
IPD:MHC02786 Ovar-DRB1*1002, 89 bases, 6903DE5F checksum.
 HFLEYSTSEC HFFNGTERVR FLDRYFYNGE EYVRFDSDWG EYRAVAELGR
 PDAKYWNSQK DILERRRTEV DTYCRHNYGV IESFSVQRR*

>P1;IPD:MHC02978
IPD:MHC02978 Ovar-DRB1*1003, 89 bases, 8D9C58BA checksum.
 HFLEYSTSEC HFFNGTERVR FLDRYFYNGE EYVRFDSDWG EYRAVAELGR
 RSAEYWNSQK EILERRRTEV DTYCRHNYGV IESFSVQRR*

>P1;IPD:MHC02449
IPD:MHC02449 Ovar-DRB1*1101, 89 bases, 3ADC155B checksum.
 HFLEYSTSEC HFFNGTERVR FLDRYFYNGE ETLRFDSDWG EYRAVAELGR
 PDAKYWNSQK EILERKRAAV DTYCRHNYGV GESFSVQRR*

>P1;IPD:MHC02478
IPD:MHC02478 Ovar-DRB1*1102, 158 bases, 68895235 checksum.
 RGSRMAALIV MLMALSPPLA WARKIQPHFL EYSTSECHFF NGTERVRFLD
 RYFYNGEETL RFDSDWGEYR AVAELGRPDA KYWNSQKEIL ERKRAAVDTY
 CRHNYGVGES FTVQRRVEPI VTVYPAKTQP LQHHNLLVCS VNGFYPGHIE
 VRWFRNGH*

>P1;IPD:MHC02450
IPD:MHC02450 Ovar-DRB1*1201, 89 bases, 4C476C7 checksum.
 HFLEYHKSEC HFFNGTERVR FLDRYFYNGE EYVRFDSDWG EFRAVAELGR
 PEAKYWNSQK EILERKRAAV DTYCRHNYGV IESFSVQRR*

>P1;IPD:MHC02787
IPD:MHC02787 Ovar-DRB1*1202, 89 bases, D800E959 checksum.
 HFLEYHKSEC HFFNGTERVR FLDRYFYNGE EYVRFDSDWG EFRAVAELGR
 PEAKYWNSQK EILERRRTEV DTYCRHNYGV IESFSVQRR*

>P1;IPD:MHC02788
IPD:MHC02788 Ovar-DRB1*1203, 89 bases, 6F727DEC checksum.
 HFLEYHKSEC HFFNGTERVR FLDRYFYNGE EYVRFDSDWG EFRAVAELGR
 PEAKYWNSQK EILESRRTAV DTYCRHNYGV IESFSVQRR*

>P1;IPD:MHC02452
IPD:MHC02452 Ovar-DRB1*1301, 158 bases, C2EB610E checksum.
 RGSRMAALIV MLMALSPPLA WARKIQPHFL EYSKSECHFF NGTERVRFLD
 RYYTNGEENV RFDSDWGEFR AVTELGRPDA EQWNSQKDFL ESRRTAVDTY
 CRHNYGVFES FSVQRRVEPT VTVYPAKTQP LQHHNLLVCS VNGFYPGHIE
 VRWFRNGH*

>P1;IPD:MHC02469
IPD:MHC02469 Ovar-DRB1*1302, 158 bases, 9D48DDE3 checksum.
 RGSRMAALIV MLMALSPPLA WARKIQPHFL EYSKSECHFF NGTERVRFLD
 RYYTNGEENV RFDSDWGEFR AVTELGRPDA EQWNSQKDFL ERKRTAVDTY
 CRHNYGVIES FSVQRRVEPT VTVYPAKTQP LQHHNLLVCS VNGFYPGHIE
 VRWFRNGH*

>P1;IPD:MHC02453
IPD:MHC02453 Ovar-DRB1*1401, 158 bases, AB79F2BB checksum.
 RGSRMAALIV MLMALSPPLA WARKIQPHFL EYTKKECHFF NGTERVRLLE
 RYFYNGEEYV RFDSDWGEFR AVAELGRQSA EYWNSQKEIL ESRRTAVDTY
 CRHNYGVIES FSVQRRVEPI VTVYPAKTQP LQHHNLLVCS VNGFYPGHIE
 VRWFRNGH*

>P1;IPD:MHC02782
IPD:MHC02782 Ovar-DRB1*1402, 89 bases, FEF534AF checksum.
 HFLEYTKKEC HFFNGTERVR LLERYFYNGE EYVRFDSDWG EFRAVAELGR
 PEAKYWNSQK EILESRRTAV DTYCRHNYGV IESFSVQRR*

>P1;IPD:MHC02455
IPD:MHC02455 Ovar-DRB1*1501, 158 bases, A1B0A9ED checksum.
 RGSRMAALIV MLMALSPPLA WARKIQPHFL EYSTSECHFF NGTERVRFLD
 RYFYNGEEYV RFDSDWGEYR AVAELGRQSA EHWNSQKELL ERRRAEVDTY
 CRHNYGVIES FSVQRRVEPI VTVYPAKTQP LQHHNLLVCS VNGFYPGHIE
 VRWFRNGH*

>P1;IPD:MHC02460
IPD:MHC02460 Ovar-DRB1*1502, 158 bases, 7B157C90 checksum.
 RGSRMAALIV MLMALSPPLA WARKIQPHFL EYHKSECHFF NGTERVRFLD
 RYFYNGEEYV RFDSDWGEFR AVAELGRQSA EHWNSQKELL ERRRAEVDTY
 CRHNYGVIES FSVQRRVEPI VTVYPAKTQP LQHHNLLVCS VNGFYPGHIE
 VRWFRNGH*

>P1;IPD:MHC04074
IPD:MHC04074 Ovar-DRB1*1503, 89 bases, 760AB451 checksum.
 HFLEYHKSEC HFFNGTERVR FLDRYFYNGE EYVRFDSDWG EFRAVAELGR
 QSAEHWNSQK ELLERRRAAV DTYCRHNYGV IESFSVQRR*

>P1;IPD:MHC02456
IPD:MHC02456 Ovar-DRB1*1601, 89 bases, 1A7F22AD checksum.
 HFLEYTKKEC RFFNGTERVR YLDRYFYNGE EYVRFDNDWG EYRAVAELGR
 PDAKYWNSQK ELLERKRANV DTYCRHNYGV GESFTVQRR*

>P1;IPD:MHC02471
IPD:MHC02471 Ovar-DRB1*1602, 158 bases, 61EDE9BC checksum.
 RGSRMAALIV MLMALSPPLA WARKIQPHFL EYTKKECRFF NGTERVRYLD
 RYFYNGEEYV RFDNDWGEYR AVAELGRPDA KYWNSQKELL ERKRANVDTY
 CRHNYGVIES FSVQRRVEPI VTVYPAKTQP LQHHNLLVCS VNGFYPGHIE
 VRWFRNGH*

>P1;IPD:MHC02785
IPD:MHC02785 Ovar-DRB1*1603, 89 bases, 232045C9 checksum.
 HFLEYTKKEC RFSNGTERVR FLDRYFYNGE EYARFDSDWG EYRAVAELGR
 PDAKYWNSQK ELLERKRANV DTYCRHNYGV GESFTVQRR*

>P1;IPD:MHC02981
IPD:MHC02981 Ovar-DRB1*1604, 89 bases, FCA7DA3B checksum.
 HFLEYRKSEC RFSNGTERVR YLDRYFYNGE EYVRFDSDWG EYRAVAELGR
 PDAKYWNSQK ELLERKRANV DTYCRHNYGV IESFSVQRR*

>P1;IPD:MHC04076
IPD:MHC04076 Ovar-DRB1*1605, 89 bases, 8097EAF4 checksum.
 HFLEYHKSEC RFSNGTERVR YLDRYFYNGE EYVRFDNDWG EYRAVAELGR
 PDAKYWNSQK EILERKRAAV DTYCRHNYGV IESFSVQRR*

>P1;IPD:MHC02458
IPD:MHC02458 Ovar-DRB1*1701, 89 bases, 41AFABFB checksum.
 HFLEYAKREC HFFNGTERVR FLDRYFYNGE EYVRFDSDWG EFRAVAELGR
 RSAEYWNSQK DFLERARAAV DTYCRHNYGV IESFSVQRR*

>P1;IPD:MHC02466
IPD:MHC02466 Ovar-DRB1*1702, 158 bases, 261040C5 checksum.
 RGSRMAALIV MLMALSPPLA WARKIQPHFL EYHKSECHFF NGTERVRFLD
 RYFYNGEEYV RFDSDWGEFR AVAELGRQSA EYWNSQKDFL ERARAAVDTY
 CRHNYGVFES FSVQRRVEPI VTVYPAKTQP LQHHNLLVCS VNGFYPGHIE
 VRWFRNGH*

>P1;IPD:MHC02461
IPD:MHC02461 Ovar-DRB1*1801, 89 bases, 1DD8278 checksum.
 HFLEYRKSEC RFSNGTERVR YLDRYFYNGE EYVRFDSDWG EYRAVAELGR
 RSAEYWNSQK ELLERKRANV DTYCRHNYGV GESFTVQRR*

>P1;IPD:MHC02463
IPD:MHC02463 Ovar-DRB1*1901, 158 bases, CC20D35 checksum.
 RGSRMAALIV MLMALSPPLA WARKIQPHFL EYAKSECHFF NGTERVRFLD
 RYFYNGEEYV RFDSDWGEFR AVAELGRRSA EYWNSQKDFL EQTRAEVDTY
 CRHNYGVGES FTVQRRVEPI VTVYPAKTQP LQHHNLLVCS VNGFYPGHIE
 VRWFRNGH*

>P1;IPD:MHC02470
IPD:MHC02470 Ovar-DRB1*1902, 158 bases, 294F51F9 checksum.
 RGSRMAALIV MLMALSPPLA WARKIQPHFL EYAKSECHFF NGTERVRFLD
 RYFYNGEEYV RFDSDWGEFR AVAELGRRSA EYWNSQKDFL ERARAAVDTY
 CRHNYGVGES FTVQRRVEPI VTVYPAKTQP LQHHNLLVCS VNGFYPGHIE
 VRWFRNGH*

>P1;IPD:MHC02475
IPD:MHC02475 Ovar-DRB1*1903, 158 bases, F51B2653 checksum.
 RGSRMAALIV MLMVLSPPLA WAREIQPHFL EYHKSECHFF NGTERVRFLD
 RYFYNGEEYV RFDSDWGEFR AVAELGRRSA EYWNSQKDFL EQTRAEVDTY
 CRHNYGVGES FTVQRRVEPI VTVYPAKTQP LQHHNLLVCS VNGFYPGHIE
 VRWFRNGH*

>P1;IPD:MHC02467
IPD:MHC02467 Ovar-DRB1*2001, 158 bases, 1E0E48F0 checksum.
 RGSRMAALIV MLMALSPPLA WARKIQPHFL EYAKSECRFF NGTERVRFLE
 RYFYNGEEYV RFDSDWGEYR AVAELGRPDA KYWNSQKDFL ERKRANVDTY
 CRHNYGVIES FSVQRRVEPI VTVYPAKTQP LQHHNLLVCS VNGFYPGHIE
 VRWFRNGH*

>P1;IPD:MHC02468
IPD:MHC02468 Ovar-DRB1*2002, 158 bases, E2671B17 checksum.
 RGSRMAALIV MLMALSPPLA WARKIQPHFL EYAKSECRFF NGTERVRFLE
 RYFYNGEEYV RFDSDWGEYR AVAELGRPDA KYWNSQKDFL ERKRANVDTY
 CRHNYGVFES FSVQRRVEPI VTVYPAKTQP LQHHNLLVCS VNGFYPGHIE
 VRWFRNGH*

>P1;IPD:MHC02474
IPD:MHC02474 Ovar-DRB1*2101, 158 bases, 9534E30C checksum.
 RGSRMAALIV MLMALSPPLA WARKIQPHFL EYSTSECHFS NGTERVRLLD
 RYFHNGEEFV RFDSDWGEFR AVAELGRPDA EYWNSQKDFL ESRRTAVDTY
 CRHNYGVIES FTVQRRVEPI VTVYPAKTQP LQHHNLLVCS VNGFYPGHIE
 VRWFRNGH*

>P1;IPD:MHC02482
IPD:MHC02482 Ovar-DRB1*2201, 89 bases, D6DEA819 checksum.
 HFLEYRKSEC RFSNGTERVR FLDRYFYNGE ENVRFDSDWG EYRAVAELGR
 PDAKYWNSQK DFLERKRANV DTYCRHNYGV GESFTVQRR*

>P1;IPD:MHC04077
IPD:MHC04077 Ovar-DRB1*2202, 89 bases, 3E0DE6E1 checksum.
 HFLEYHKSEC HFFNGTERVR FLDRYFYNGE EYVRFDSDWG EYRAVAELGR
 PDAKYWNSQK DFLERKRANV DTYCRHNYGV GESFTVQRR*

>P1;IPD:MHC02980
IPD:MHC02980 Ovar-DRB1*2301, 89 bases, 5ED1E6CC checksum.
 HFLEYAKSEC RFFNGTERVR FLERYFYNGE EYVRFDSDWG EYRAVAELGR
 QSAEHWNSQK ELLERRRAEV DTYCRHNYGV GESFTVQRR*

>P1;IPD:MHC04078
IPD:MHC04078 Ovar-DRB1*2401, 89 bases, CDB5AD49 checksum.
 HFLEYSTSEC HFFNGTERVR FLDRYFYNGE EYVRFDSDWG EYRAVAELGR
 PDAKYWNSQK DFLERARAAV DTYCRHNYGV GESFTVQRR*

