>P1;IPD:MHC02432
IPD:MHC02432 Ovar-N*00101, 360 bases, 900EE1AF checksum.
 MGPRTLLLLL SGVLVLTEIR AGPHSLRYVY TGVSRPGLGE PRFIAVGYVD
 DTQFVRFDSD APDPREEPRA RWVEQEGPEY WDRNTRIYKD TAQIFRANLN
 TALGYYNQSE AGSHTFQEMY GCDVGPDGRL LRGYDQLGYD GRDYIALNED
 LRSWTAADTA AQVTQRKWEK EGVAERFRNY VEGRCVEGLR RYLEIGKDTL
 LRADPPKAHV THHPISGHDV TLRCWALGFY PEEISLTWQR NGEDQLQDME
 LVETRPSGDG TFQKWAALVV PSGEEQRYTC HVQHEGLQEP LTLRWEPPQT
 SFLTMGIIVG LVLLVMVAVV AAAVIWRKKC SGEKRGTYTQ ASSNDSAQGS
 DVSLTVHKVX*

>P1;IPD:MHC02433
IPD:MHC02433 Ovar-N*00201, 360 bases, B159E032 checksum.
 MGPRTLLLLL SGVLVLTEIR AGPHSMRYVF TGVSRPGRGE PRFIAVGYVD
 DTQFVRFDSD AADPRMEPRA RWVEQEGPEY WDRETRNMKD TTQSFRANLN
 TLRGYYNQSA AGSHTLQWMV GCDVGPDGRL LRGFWQFGYD GRDYIALNED
 LRSWTAADTA AQITKRKWEK EGAAEAERNY LEGRCVEWLR RYLENGKDTL
 LRADPPKAHV THHPISGHDV TLRCWALGFY PEEISLTWQR NGEDQLQDME
 LVETRPSGDG TFQKWVALVV PSGEEQRYTC HVQHEGLQEP LTLRWEPPQT
 SFLTMGIIVG LVLFVMVAVV AGAVIWRKKC SGEKRGTYTQ ASSNDSAQGS
 DVSLTVHKVX*

>P1;IPD:MHC02437
IPD:MHC02437 Ovar-N*00301, 356 bases, A1BFCFEB checksum.
 LLLLSGVLVL TEIRAGPHSM RYFSTAVSRP GRGEPRYLEV GYVDDTQFVR
 FDSDAPDPKM EPRARWVEQE GPEYWDRNTR NAKGTAQTFR VNLNTALSYY
 NQSEAGSHTW QWMYGCDVGP DGRLLRGFMQ YGYDGRDYIA LNEDLRSWTA
 ADTAAQITQR KWEKEGVAER HRNYLEGTCV EWLRRHLENG KDTLLRADPP
 KAHVTHHPIS GHDVTLRCWA LGFYPEEISL TWQRNGEDQL QDMELVETRP
 SGDGTFQKWA ALVVPSGEEQ RYTCHVQHEG LQEPLTLRWE PPQTSFLTSS
 MGIIVGLVLL VMVAVVAAAV IWRKKCSGEK RGTYTQASSN DSAQGSDVSL
 TVHKVX*

>P1;IPD:MHC02440
IPD:MHC02440 Ovar-N*00401, 354 bases, BE5DAE38 checksum.
 LLLLSGVLVL TEIRAGSHSL RYVYTGVSRP GRGEPRFIAV GYVDDTQFVR
 FDSDTPDPRM EPRARWVEQE GPEYWDRETR NMKDATQRFR ANLNTLRGYY
 NQSEAGSHTL QWMYGCDVGP DGRLLRGYRQ DAYDGRDYIA LNEDLRSWTA
 ADTAAQITKR KWEKEGAAEA ERNYLEGLCV EGLRRYLEIG KDTLLRADPP
 KAHVTHHPIS GHDVTLRCWA LGFYPEEISL TWQRNGEDQL QDMELVETRP
 SGDGTFQKWA ALVVPSGEEQ RYTCHVQHEG LQEPLTLRWE PPQTSFLTMG
 IIVGLVLLVM VAVVAGAVIW RKKCSGEKRG TYTQASSNDS AQGSDVSLTV
 PKVX*

>P1;IPD:MHC02439
IPD:MHC02439 Ovar-N*00501, 360 bases, 8FF18AE3 checksum.
 MGPRTLLLLL SGVLVLTEIR AGPHSMRYFS TAVSRPGRGE PRYLEVGYVD
 DTQFVRFDSD APDPKMEQRA PWMEQVGPEY WDRETRRAKG NGQSFRVGLT
 ILRGYYNQSE AGSHTWQWMY GCDVGPDGRL LRGFMQYGYD GRDYIALNED
 LRSWTAADTA AQVTQRKWEK EGAADHYRNY LEGTCVEWLR RYLEIGKDTL
 QRADPPKAHV THHPISGHDV TLRCWALGFY PEEISLTWQR NGEDQLQDME
 LVETRPSGDG TFQKWAALVV PSGEEQRYTC HVQHEGLQEP LTLRWEPPQT
 SFLTMGIIVG LVLLVMVAVV AAAVIWRKKC SGEKRGTYTQ ASSNDSAQGS
 DVSLTVHKVX*

>P1;IPD:MHC02443
IPD:MHC02443 Ovar-N*00601, 359 bases, B6A442F5 checksum.
 MRPRTPFMLL LGTLVLTETR AGSHSLRYVY TAVSRPGRGE PRFIAVGYVD
 DTQFVRFDSD AADPRMEPRA RWVEQEGPEY WDQETQGTKD AAQTFRANLN
 TLRGYYNQSE AGSHTLQCMY GCDVGPDGLL LRGFMQYGYE GRDYIALNED
 LRSWTAADTA AQISKHNAVV AGAADHYRNY LEGECVEWLR RHLETGKDTL
 LRADPPKAHV THHPISDHEV TLRCWALGFY PEEISLTWQR NGEDQTQDME
 LVETRPSGDG TFQKWAALVV PSGEEQRYTC RVQHEGLQEP LTLRWEPPQT
 SFLTMGIIVG LVLLVVAVVA GAVIWRKKRS GEKGRTYTQA SSSDSAQGSD
 VFLTVPKVX*

>P1;IPD:MHC02436
IPD:MHC02436 Ovar-N*00701, 356 bases, 6CB28F05 checksum.
 RTPFMSLLWT LVLTETLSGP HSLRYFLTAV SRPGRGEPRF IAVGYVDDTQ
 FVRFDSDAAD PRMEPRARWV EQEGPEYWDQ ETRSAKGHAQ TFRVNLNTLR
 GYYNQSEPGS HTLQRMYGCD VGPDGRLLSG YEQFAYDGRD YIALNQDLRS
 WTAADAAAQI SKRKLEKEGV AARVRIYLEG RCVEGLRRYL ETGKDTLQRA
 DPPKAHVTRH PITEREVTLR CWALGFYPEE ISLTWQRNGE DQTQDMELVE
 TRPSGDGTFQ KWAALVVPSG EEQRYTCHVQ HEGLQEPLTL RWAPPQTSFL
 TMGIIVGLVI LAVTVVAGAV VWRKNRSGEK RRTYTQAASS DRAQGSDVSL
 MVPKVX*

>P1;IPD:MHC02438
IPD:MHC02438 Ovar-N*00801, 353 bases, 85A5314E checksum.
 FMSLLWTLVL TETLSGPHSL RYFLTAVSRP GRGEPRFIAV GYVDDTQFVR
 FDSDAADPRM EPRARWVEQE GPEYWDRETR KANDDAQTFR VNLNTLRGYY
 NQSEPGSHTL QEMYGCDVGP DGLLLRGFMQ YGYEGRDYLA LNEDLRSWTA
 ADTAAQISKH NAVVAGAADH YRNYLVGECV EWLLRHLETG KDTLLRADPP
 KAHVAHHPIS EREVTLRCWA LGFYPEEISL TWQHEGEDQT QDMELVETRP
 SGDGTFQKWA ALVVPSGEEQ RYTCRVQHEG LQEPLTLRWE PPQTSFLTMG
 IIVGLVLLVV AVVAGAVIWR KKRSGEKGGT YTQASSSDSA QGSDVSLTVP
 KVX*

>P1;IPD:MHC02779
IPD:MHC02779 Ovar-N*00901, 356 bases, A42C7E2 checksum.
 MGPRTLLLLL SGVLVLTEIR AGPHSLRYFL TAVSRPGLGE PRFIAVGYVD
 DMQFVRFDSD APDPRMEPRA RWMEQEGPEY WDQETRSAKG DAQSFRANLN
 TLRGYYNQSE AGSHTLQEMY GCDVGPDGRL LRGYTQYAYD GRDYIALNED
 LRSWTAADTA AQITQRKLEK EGAAEAERNY LEGTCVEWLR RYLETGKDTL
 LRADPPKAHV THHPISGHDV TLRCWALGFY PEEISLTWQR NGEDQLQDME
 LVETRPSGDG TFQKWAALVV PSGEEQRYTC HVQHEGLQEP LTLRWEPPQT
 SFLTSSMGII VGLVLLVMVA VVAAAVIWRK KCSGEKRGTY TQASSNDSAQ
 GSDVSL*

>P1;IPD:MHC02780
IPD:MHC02780 Ovar-N*01001, 354 bases, 53AF44D9 checksum.
 MGPRTLLLLL SGVLVLTEIR AGPHSLRYFL TAVSRPGLGE PRFIAVGYVD
 DTQFVRFDSD APDPRMEPRA RWMEQEGPEY WDQETRSAKG HAQSFRANLN
 TLRGYYNQSE AGSHTLQWMY GCDVGPDGRL LRGYRQDAYD GRDYIALNED
 LRSWTAADTA AQITQRKWEK EGAAEAERNY LEGTCVEWLR RYLETGKDTL
 LRADPPKAHV THHPISGHDV TLRCWALGFY PEEISLTWQR NGEDQLQDME
 LVETRPSGDG TFQKWAALVV PSGEEQRYTC HVQHEGLQEP LTLRWEPPQT
 SFLTMGIIVG LVLLVMVAVV AGAVIWRKKC SGEKRGTYTQ ASSNDSAQGS
 DVSL*

>P1;IPD:MHC02781
IPD:MHC02781 Ovar-N*01101, 356 bases, A5D94225 checksum.
 MGPRTLLLLL SGVLVLTEIR AGPHSMRYVY TGVSRPGLGE PRFIAVGYVD
 DTQFVRFDSD APDPRMEPRA RWVEQEGPEY WDRETRNMKD ATQSFRVGLN
 TLRGYYNQSE AGSHTWQRMY GCYVGPDGRL LRGYEQFGYD GRDYIALNED
 LRSWTAADTA AQITQRKWEK EGVAEAERNY LEGRCVEWLR RYLETGKDTL
 LRADPPKAHV THHPISGHDV TLRCWALGFY PEEISLTWQR NGEDQLQDME
 LVETRPSGDG TFQKWAALVV PSGEEQRYTC HVQHEGLQEP LTLRWEPPQT
 SFLTSSMGII VGLVLLVMVA VVAAAVIWRK KCSGEKRGTY TQASSNDSAQ
 GSDVSL*

>P1;IPD:MHC02441
IPD:MHC02441 Ovar-N*50001, 356 bases, CC712983 checksum.
 RTLLLLLSGV LVLSETWAGS HSLRYFLTAV SRPGLGEPRF IAVGYVDDTQ
 FVRFDSDARD PRMEPRARWA EQEGPEYWDQ ETRLAKDAAQ TFRANLNTAL
 GYYNQSEAGS HTVQEMYGCD VGPDGRFLRG YEQHGYDGRD YLALNEDLRS
 WTAADTAAQI TKRKWEAAGE AERHRNSLVG ECVEELRRHL ETGKDTLQRA
 DPPKARVTHH PVSEREVTLR CWALGFYPEE ISLTWQRNEE DQTQDMELVE
 TRPSGDGTFQ KWAALVVPSG EEQRYTCHVQ HEGLQEPLTL RWEPPQPSVP
 IMGIILVLVL LLVALVAGAV IWRKKRSGEK GQTYTQASSS DSAQGSDVSL
 TVPKVX*

>P1;IPD:MHC02435
IPD:MHC02435 Ovar-N*50101, 356 bases, 234617BD checksum.
 RTLLLLLSGV LVLTETLAGS HSLRYVYTAV SRPGRGEPRF IAVGYVDDTQ
 FVRFDSDAPD PRMEPRARWV EQEGPEYWDQ ETRIYKDAAQ NFRANLNTLR
 GYYNQSEAGS HTLQAMCGCD VGPDGRLLRG FMQYGYDGRD YIALNEDLRS
 WTAADTAAQI SKRKIEAAGG AEGHRNYFEG LCVEELRRYL ETGKDTLLRA
 DPPKARVTHH PVSEREVTLR CWALGFYPEE ISLTWQRNEE DQTQGMELVE
 TRPSGDGTFQ KWAALVVPSG EEQRYTCRVQ HEGLQEPLTL RWEPPQPSVP
 IMGIILVLVL LLVALVAGAV IWRKKRSGEK GQTYTQASSS DSAQGSDVSL
 TVPKVX*

>P1;IPD:MHC02434
IPD:MHC02434 Ovar-N*50201, 356 bases, 716E8D84 checksum.
 RTLLLLLSGV LVLSETWAGS HSLRYVYTCV SRPGLGEPRF IAVGYVDDTQ
 FVRFDSEARN PRMEPRARWA EQEGPEYWDQ ETRMAKDAAQ NFRVNLNTLR
 GYYNQSEAGS HTVQAMCGCD VGPDWRLLRG FMQYGYDGRD YLALNEDLRS
 WTAADAAAQI SKRKIEAAGG AEGHRNYFEG LCVEMLRRYL EKGKDTLQRA
 DPPKARVTHH PVSEREVTLR CWALGFYPEE ISLTWQRNEE DQTQDMELVE
 TRPSGDGTFQ KWAALVVPSG EEQRYTCHVQ HEGLQEPLTL RWEPPQPSVP
 IMGIILVLVL LLVALVAGAV IWRKKRSGEK GQTYTQASNS DSAQGSDVSL
 TVPKVX*

>P1;IPD:MHC02442
IPD:MHC02442 Ovar-N*50301, 344 bases, 42F9353F checksum.
 RTLLLLLSGA LVLAETRAGS HSLRYFLTAV SRPGLGEPRF IIVGYVDDTQ
 FLRFDSDAPH PRLEPRTRWI EQEGPEYWDE ETRIAKDGIQ TFRANLNTLR
 GYYNQSEAGS HTLQNMHCCG VGPDGRLLRG FMQFGYDGRD YIALNEDLRS
 WTAADTAARI TQRKWEALGA AEEQRNYFEG KCVNLLRRHL ENGKDTLLRT
 NPPKAHVTHH PTSEREVTLR CWALGFYPEE ISLTWQRNGE DQTQDMELVQ
 TRPSGDGTFQ KWAALVVPSG EEQRYTCHVQ HEGLQEPLTL RWEPPQSSIP
 IMGIVLVLVL LVVAVVAGAV IWRKKRSGEN GQTYTQAASS DGAX*

