>DL;IPD:MHC02479
IPD:MHC02479 Ovar-DRA*0101, 762 bases, F8E31E42 checksum.
 ATGGCCATAA CCAGGGTCCC AATATTAGGA CTTTTCATCA CTGTCCTGAT
 CAGCCTACAG GAATCGTGGG CTATTAAAGA GGACCATGTG ATCATCCAGG
 CTGAGTTCTA TCTGAACCCT GAGGAATCAG CCGAGTTTAT GTTTGACTTT
 GATGGTGATG AGATTTTCCA CGTGGATATG CAGAAGAAGG AGACAGTGTG
 GCGGCTTCCA GAATTTGGAC ATTTTGCCAG CTTTGAGGCT CAGGGTGCCC
 TGGCCAATAT GGCTGTGATG AAAGCCAACC TGGACATCAT GATAAAGCGC
 TCCAACAACA CCCCGAACAC CAATGTTCCT CCAGAAGTGA CTCTGCTCCC
 AAACAAGCCT GTGGAACTGG GAGAGCCCAA CACACTCATC TGCTTCATTG
 ACAAGTTCTC GCCACCCGTG ATCAGTGTCA CGTGGCTTCG AAATGGCATA
 CCTGTCACTG ACGGAGTGTC ACAGACGGTC TTCCTGCCCA GGGATGACCA
 CCTTTTCCGC AAGTTCCACT ACCTCCCCTT CCTGCCCACA ACAGAGGACG
 TCTATGACTG CAAGGTGGAG CACTGGGGTC TGAACGAGCC TCTTCTCAAG
 CACTGGGAGT ATGAAGCTCC AGCCCCTCTC CCAGAGACTA CAGAGAATGC
 GGTGTGTGCC CTGGGCCTGA TTGTGGCTCT GGTGGGCATC ATTGCAGGGA
 CCATCTTCAT CATCAAGGGC GTGCGCAAAG CCAACACTGT TGAAGGCCGA
 GGGCCTCTGT GA*

>DL;IPD:MHC02480
IPD:MHC02480 Ovar-DRA*0102, 762 bases, 55CAD7A7 checksum.
 ATGGCCATAA CCAGGGTCCC AATATTAGGA CTTTTCATCA CTGTCCTGAT
 CAGCCTACAG GAATCGTGGG CTATTAAAGA GGACCATGTG ATCATCCAGG
 CTGAGTTCTA TCTGAACCCT GAGGAATCAG CCGAGTTTAT GTTTGACTTT
 GATGGTGATG AGATTTTCCA CGTGGATATG CAGAAGAAGG AGACAGTGTG
 GCGGCTTCCA GAATTTGGAC GTTTTGCCAG CTTTGAGGCT CAGGGTGCCC
 TGGCCAATAT GGCTGTGATG AAAGCCAACC TGGACATCAT GATAAAGCGC
 TCCAACAACA CCCCGAACAC CAATGTTCCT CCAGAAGTGA CTCTGCTCCC
 AAACAAGCCT GTGGAACTGG GAGAGCCCAA CACACTCATC TGCTTCACTG
 ACAAGTTCTC GCCACCCGTG ATCAGTGTCA CGTGGCTTCG AAATGGCATA
 CCTGTCACTG ACGGAGTGTC ACAGACGGTC TTCCTGCCCA GGGATGACCA
 CCTTTTCCGC AAGTTCCACT ACCTCCCCTT CCTGCCCACA ACAGAGGACG
 TCTATGACTG CAAGGTGGAG CACTGGGGTC TGAACGAGCC TCTTCTCAAG
 CACTGGGAGT ATGAAGCTCC AGCCCCTCTC CCAGAGACTA CAGAGAATGC
 GGTGTGTGCC CTGGGCCTGA TTGTGGCTCT GGTGGGCATC ATTGCAGGGA
 CCATCTTCAT CATCAAGGGC GTGCGCAAAG CCAACACTGT TGAAGGCCGA
 GGGCCTCTGT GA*

>DL;IPD:MHC02481
IPD:MHC02481 Ovar-DRA*0201, 762 bases, EE5C9BF7 checksum.
 ATGGCCATAA CCAGGGTCCC AATATTAGGA CTTTTCATCA CTGTCCTGAT
 CAGCCTACAG GAATCGTGGG CTATTAAAGA GGACCATATG ATCATCCAGG
 CTGGGATCTA TGTGAACCCT GAGCAATCAG CCGAGTTTAT GTTTGACTTT
 GATGGTGATG AGATTTTCCA CGTGGATATG CAGAAGAAGG AGACAGTGTG
 GCGGCTTCCA GAATTTGGAC ATTTTGCCAG CTTTGAGGCT CAGGGTGCCC
 TGGCCAATAT GGCTGTGATG AAAGCCAACC TGGACGTCAT GACAAAGTAC
 TCCAACAACA CCCCGAACAC CAATGTTCCT CCAGAAGTGA CTCTGCTCCC
 AAACAAGCCT GTGGAACTGG GAGAGCCCAA CACACTCATC TGCTTCATTG
 ACAAGTTCTC GCCACCCGTG ATCAGTGTCA CGTGGCTTCG AAATGGCAAA
 CCTGTCACTG ATGGAGTGTC ACAGACGGTC TTCCTGCCCA GGGATGACCA
 CCTTTTCCGC AAGTTCCACT ACCTCTCCTT CCTGCCCACA ACAGAGGATG
 TCTATGACTG CAAGGTGGAG CACTGCAGTT TGAATGAGCC TCTTCTCAAG
 CACTGGGAGT ATGAAGCTCC AGCCCCCCTC CCAGAGACGA CAGAGAATGC
 AGTGTGTGCC CTGGGCCTGA TTGTGGCTCT GGTGGGCATC ATTGCAGGGA
 CCATCTTCAT CATCAAGGGC GTGCGCAAAG CCAACACTGT TGAAGGCCGA
 GGGCCTCTGT GA*

