>DL;IPD:MHC02432
IPD:MHC02432 Ovar-N*00101, 1080 bases, D2B39936 checksum.
 ATGGGGCCGC GAACCCTCCT GTTGCTGCTC TCGGGAGTCC TGGTCCTGAC
 CGAGATCCGG GCGGGCCCCC ACTCCCTGAG GTATGTCTAC ACCGGCGTGT
 CCCGGCCCGG CCTCGGGGAG CCCCGCTTCA TCGCCGTCGG CTACGTGGAC
 GACACGCAGT TCGTGCGGTT CGACAGCGAC GCCCCGGATC CGAGGGAGGA
 ACCTCGGGCG CGGTGGGTGG AGCAGGAGGG GCCGGAGTAT TGGGATCGAA
 ACACGAGGAT CTACAAGGAC ACCGCACAGA TTTTCCGAGC GAACCTGAAC
 ACCGCACTCG GCTACTACAA CCAGAGCGAG GCCGGGTCTC ACACCTTCCA
 GGAGATGTAT GGCTGCGACG TGGGGCCGGA CGGGCGTCTC CTCCGCGGGT
 ATGATCAGCT CGGCTACGAC GGCAGAGATT ACATCGCCCT GAACGAGGAC
 CTGCGCTCCT GGACCGCGGC GGACACGGCG GCTCAGGTCA CCCAGCGCAA
 GTGGGAGAAG GAGGGTGTTG CGGAGAGATT CAGAAACTAC GTGGAGGGCC
 GGTGCGTGGA GGGGCTCCGC AGATACCTGG AGATCGGGAA GGACACGCTG
 CTGCGCGCAG ACCCTCCAAA GGCACATGTG ACGCATCACC CCATCTCTGG
 CCATGATGTC ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGAGGAGA
 TCTCACTGAC CTGGCAGCGC AATGGGGAGG ACCAGTTGCA GGACATGGAG
 CTTGTGGAGA CTAGGCCTTC AGGGGATGGA ACCTTCCAGA AGTGGGCAGC
 CCTGGTGGTG CCTTCTGGAG AGGAGCAGAG ATACACATGC CATGTGCAGC
 ATGAGGGGCT TCAGGAGCCC CTCACCCTGA GATGGGAACC TCCTCAGACC
 TCCTTCCTCA CCATGGGCAT CATTGTTGGC CTGGTTCTCC TCGTCATGGT
 GGCTGTGGTG GCTGCAGCTG TGATCTGGAG GAAGAAGTGC TCAGGTGAAA
 AAAGAGGGAC CTATACCCAG GCTTCAAGCA ATGACAGTGC CCAGGGTTCT
 GATGTGTCTC TCACGGTTCA TAAAGTGTGA*

>DL;IPD:MHC02433
IPD:MHC02433 Ovar-N*00201, 1080 bases, 5B8A2A9A checksum.
 ATGGGGCCGC GAACCCTCCT GTTGCTGCTC TCGGGAGTCC TGGTCCTGAC
 CGAGATCCGG GCGGGCCCCC ACTCCATGAG GTATGTCTTC ACCGGCGTGT
 CCCGGCCCGG CCGCGGGGAG CCCCGCTTCA TCGCCGTCGG CTACGTGGAC
 GACACGCAGT TCGTGCGGTT CGACAGCGAC GCCGCGGATC CGAGGATGGA
 GCCGCGGGCG CGGTGGGTGG AGCAGGAGGG GCCGGAGTAT TGGGATCGGG
 AAACTCGAAA CATGAAGGAC ACCACACAGA GTTTCCGAGC GAACCTGAAC
 ACCCTGCGCG GCTACTACAA CCAGAGCGCG GCCGGGTCTC ACACCCTCCA
 GTGGATGGTC GGCTGCGACG TGGGGCCGGA CGGGCGCCTC CTCCGCGGGT
 TCTGGCAGTT CGGCTACGAC GGCAGAGATT ACATCGCCCT GAACGAGGAC
 CTGCGCTCCT GGACCGCGGC GGACACGGCG GCTCAGATCA CCAAGCGCAA
 GTGGGAGAAG GAAGGTGCGG CGGAGGCAGA AAGGAACTAC CTGGAGGGCC
 GGTGCGTGGA GTGGCTCCGC AGATACCTGG AGAACGGGAA GGACACGCTG
 CTGCGCGCAG ACCCTCCAAA GGCACATGTG ACCCATCACC CCATCTCTGG
 CCATGATGTC ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGAGGAGA
 TCTCACTGAC CTGGCAGCGC AATGGGGAGG ACCAGTTGCA GGACATGGAG
 CTTGTGGAGA CTAGGCCTTC AGGGGATGGA ACCTTCCAGA AGTGGGTGGC
 CCTGGTGGTG CCTTCTGGAG AGGAGCAGAG ATACACGTGC CATGTGCAGC
 ATGAGGGGCT TCAGGAGCCC CTCACCCTGA GATGGGAACC TCCTCAGACC
 TCCTTCCTCA CCATGGGCAT CATTGTTGGC CTGGTTCTCT TCGTCATGGT
 GGCTGTGGTG GCTGGAGCTG TGATCTGGAG GAAGAAGTGC TCAGGTGAAA
 AAAGAGGGAC CTATACCCAG GCTTCAAGCA ATGACAGTGC CCAGGGTTCT
 GATGTGTCTC TCACGGTTCA TAAAGTGTGA*

>DL;IPD:MHC02437
IPD:MHC02437 Ovar-N*00301, 1068 bases, 5994E96D checksum.
 CTGTTGCTGC TCTCGGGAGT CCTGGTCCTG ACCGAGATCC GGGCGGGCCC
 CCACTCCATG AGGTATTTCA GCACCGCCGT GTCCCGGCCC GGCCGCGGGG
 AGCCCCGGTA CCTGGAAGTC GGCTACGTGG ACGACACGCA GTTCGTGCGG
 TTCGACAGCG ACGCCCCGGA TCCGAAGATG GAGCCGCGGG CGCGGTGGGT
 GGAGCAGGAG GGGCCGGAGT ATTGGGATCG GAACACGCGA AACGCCAAGG
 GCACCGCACA GACTTTCCGA GTGAACCTGA ACACCGCACT CAGCTACTAC
 AACCAGAGCG AGGCCGGGTC TCACACCTGG CAGTGGATGT ACGGCTGCGA
 CGTGGGGCCG GACGGGCGTC TCCTCCGCGG GTTCATGCAG TACGGCTACG
 ACGGCAGAGA TTACATCGCC CTGAACGAGG ACCTGCGCTC CTGGACCGCG
 GCGGACACGG CGGCTCAGAT CACCCAGCGC AAGTGGGAGA AGGAGGGTGT
 TGCGGAGAGA CACAGGAACT ACCTGGAGGG CACGTGCGTG GAGTGGCTCC
 GCAGACACCT GGAGAACGGG AAGGACACGC TGCTGCGCGC AGACCCTCCA
 AAGGCACATG TGACCCATCA CCCCATCTCT GGCCATGATG TCACCCTGAG
 GTGCTGGGCC CTGGGCTTCT ACCCTGAGGA GATCTCACTG ACCTGGCAGC
 GCAATGGGGA GGACCAGTTG CAGGACATGG AGCTTGTGGA GACTAGGCCT
 TCAGGGGATG GAACCTTCCA GAAGTGGGCA GCCCTGGTGG TGCCTTCTGG
 AGAGGAGCAG AGATACACGT GCCATGTGCA GCATGAGGGG CTTCAGGAGC
 CCCTCACCCT GAGATGGGAA CCTCCTCAGA CCTCCTTCCT CACTTCCTCA
 ATGGGCATCA TTGTTGGCCT GGTTCTCCTC GTCATGGTGG CTGTGGTGGC
 TGCAGCTGTG ATCTGGAGGA AGAAGTGCTC AGGTGAAAAA AGAGGGACCT
 ATACCCAGGC TTCAAGCAAT GACAGTGCCC AGGGTTCTGA TGTGTCTCTC
 ACGGTTCATA AAGTGTGA*

>DL;IPD:MHC02440
IPD:MHC02440 Ovar-N*00401, 1062 bases, F34BA7A0 checksum.
 CTGTTGCTGC TCTCGGGAGT CCTGGTCCTG ACCGAGATCC GGGCGGGCTC
 CCACTCCCTG AGGTATGTCT ACACCGGCGT GTCCCGGCCC GGCCGCGGGG
 AGCCCCGCTT CATCGCCGTC GGCTACGTGG ACGACACGCA GTTCGTGCGG
 TTCGACAGCG ACACCCCGGA TCCGAGAATG GAGCCGCGGG CGCGGTGGGT
 GGAGCAGGAG GGACCGGAGT ATTGGGATCG GGAAACTCGA AACATGAAGG
 ACGCCACACA GCGTTTCCGA GCGAACCTGA ACACCCTGCG CGGCTACTAC
 AACCAGAGCG AGGCCGGGTC TCACACCCTC CAGTGGATGT ACGGCTGTGA
 TGTGGGGCCG GACGGGCGCC TCCTCCGCGG GTACAGGCAG GACGCCTACG
 ACGGCAGAGA TTACATCGCC CTGAACGAGG ACCTGCGCTC CTGGACCGCG
 GCGGACACGG CGGCTCAGAT CACCAAGCGC AAGTGGGAGA AGGAAGGTGC
 GGCGGAGGCA GAAAGGAACT ACCTGGAGGG CCTGTGCGTG GAGGGGCTCC
 GCAGATACCT GGAGATCGGG AAGGACACGC TGCTGCGCGC AGACCCTCCA
 AAGGCACATG TGACCCATCA CCCCATCTCT GGCCATGATG TCACCCTGAG
 GTGCTGGGCC CTGGGCTTCT ACCCTGAGGA GATCTCACTG ACCTGGCAGC
 GCAATGGGGA GGACCAGTTG CAGGACATGG AGCTTGTGGA GACTAGGCCT
 TCAGGGGATG GAACCTTCCA GAAGTGGGCG GCCCTGGTGG TGCCTTCTGG
 AGAGGAGCAG AGATACACGT GCCATGTGCA GCATGAGGGG CTTCAGGAGC
 CCCTCACCCT GAGATGGGAA CCTCCTCAGA CCTCCTTCCT CACCATGGGC
 ATCATTGTTG GCCTGGTTCT CCTCGTCATG GTGGCTGTGG TGGCTGGAGC
 TGTGATCTGG AGGAAGAAGT GCTCAGGTGA AAAAAGAGGG ACCTATACCC
 AGGCTTCAAG CAATGACAGT GCCCAGGGTT CTGATGTGTC TCTCACGGTT
 CCTAAAGTGT GA*

>DL;IPD:MHC02439
IPD:MHC02439 Ovar-N*00501, 1080 bases, 4E99A242 checksum.
 ATGGGGCCGC GAACCCTCCT GTTGCTGCTC TCGGGAGTCC TGGTCCTGAC
 CGAGATCCGG GCGGGCCCCC ACTCCATGAG GTATTTCAGC ACCGCCGTGT
 CCCGGCCCGG CCGCGGGGAG CCCCGGTACC TGGAAGTCGG CTACGTGGAC
 GACACGCAGT TCGTGCGGTT CGACAGCGAC GCCCCGGATC CGAAGATGGA
 GCAGAGGGCG CCGTGGATGG AGCAGGTGGG GCCGGAGTAT TGGGATCGGG
 AGACGCGAAG GGCCAAGGGC AACGGACAGA GTTTCCGAGT GGGCCTGACC
 ATCCTGCGCG GCTACTACAA CCAGAGCGAG GCCGGGTCTC ACACCTGGCA
 GTGGATGTAC GGCTGCGACG TGGGGCCGGA CGGGCGTCTC CTCCGCGGGT
 TCATGCAGTA CGGCTACGAC GGCAGAGATT ACATCGCCCT GAACGAGGAC
 CTGCGCTCCT GGACCGCGGC GGACACGGCG GCTCAGGTCA CCCAGCGCAA
 GTGGGAGAAG GAAGGTGCGG CGGACCACTA CAGGAACTAC CTGGAGGGCA
 CGTGCGTGGA GTGGCTGCGC AGATACCTGG AGATCGGGAA GGACACGCTG
 CAGCGCGCAG ACCCTCCAAA GGCACATGTG ACCCATCACC CCATCTCTGG
 CCATGATGTC ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGAGGAGA
 TCTCACTGAC CTGGCAGCGC AATGGGGAGG ACCAGTTGCA GGACATGGAG
 CTTGTGGAGA CTAGGCCTTC AGGGGATGGA ACCTTCCAGA AGTGGGCAGC
 CCTGGTGGTG CCTTCTGGAG AGGAGCAGAG ATACACGTGC CATGTGCAGC
 ATGAGGGGCT TCAGGAGCCC CTCACCCTGA GATGGGAACC TCCTCAGACC
 TCCTTCCTCA CCATGGGCAT CATTGTTGGC CTGGTTCTCC TCGTCATGGT
 GGCTGTGGTG GCTGCAGCTG TGATCTGGAG GAAGAAGTGC TCAGGTGAAA
 AAAGAGGGAC CTATACCCAG GCTTCAAGCA ATGACAGTGC CCAGGGTTCT
 GATGTGTCTC TCACGGTTCA TAAAGTGTGA*

>DL;IPD:MHC02443
IPD:MHC02443 Ovar-N*00601, 1077 bases, 81F3CB14 checksum.
 ATGAGGCCGC GAACCCCCTT CATGTTGCTC CTGGGGACCC TGGTCCTGAC
 CGAGACCCGG GCAGGCTCCC ACTCCCTGAG GTATGTCTAC ACCGCCGTGT
 CCCGGCCCGG CCGCGGGGAG CCCCGCTTCA TCGCCGTCGG CTACGTGGAC
 GACACGCAGT TCGTGCGGTT CGACAGCGAC GCCGCAGATC CGAGGATGGA
 GCCGCGGGCG CGGTGGGTGG AGCAGGAGGG GCCGGAGTAT TGGGATCAGG
 AGACGCAGGG AACTAAGGAC GCCGCACAGA CTTTCCGAGC GAACCTGAAC
 ACCCTGCGCG GCTACTACAA CCAGAGCGAG GCCGGGTCTC ACACCCTCCA
 GTGTATGTAC GGCTGCGACG TGGGGCCGGA CGGGCTTCTC CTCCGCGGGT
 TCATGCAGTA CGGCTACGAG GGCAGAGATT ACATCGCCCT GAACGAGGAC
 CTGCGCTCCT GGACCGCGGC GGACACGGCG GCTCAGATCT CCAAGCACAA
 TGCTGTGGTG GCAGGTGCTG CGGATCACTA CAGGAACTAC CTGGAGGGCG
 AGTGCGTGGA GTGGCTCCGC AGACACCTGG AGACCGGGAA GGACACGCTG
 CTGCGCGCAG ACCCTCCAAA GGCACATGTG ACCCATCACC CCATCTCTGA
 CCATGAGGTC ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGAGGAGA
 TCTCACTGAC CTGGCAGCGC AATGGGGAGG ACCAGACCCA GGACATGGAG
 CTTGTGGAGA CCAGGCCTTC AGGAGACGGA ACCTTCCAGA AGTGGGCGGC
 CCTGGTGGTG CCTTCTGGAG AGGAGCAGAG ATACACGTGC CGTGTGCAGC
 ACGAGGGGCT TCAGGAGCCC CTCACCCTGA GATGGGAACC TCCTCAGACC
 TCCTTCCTCA CCATGGGCAT CATTGTTGGC CTGGTTCTCC TTGTGGTGGC
 TGTGGTGGCT GGAGCTGTGA TCTGGAGGAA GAAGCGCTCA GGTGAAAAAG
 GACGGACCTA CACCCAGGCT TCAAGCAGTG ACAGTGCCCA GGGCTCTGAT
 GTGTTTCTCA CGGTTCCTAA AGTGTGA*

>DL;IPD:MHC02436
IPD:MHC02436 Ovar-N*00701, 1069 bases, 52AFA410 checksum.
 GCGAACCCCC TTCATGTCGC TCCTGTGGAC CCTGGTCCTG ACTGAGACCC
 TGTCTGGCCC CCACTCCCTG AGGTATTTCC TCACCGCCGT GTCTCGGCCC
 GGCCGCGGGG AGCCCCGCTT CATCGCCGTC GGCTACGTGG ACGACACGCA
 GTTCGTGCGG TTCGACAGCG ACGCCGCGGA TCCGAGGATG GAGCCGCGGG
 CGCGGTGGGT GGAGCAGGAG GGGCCGGAGT ATTGGGATCA GGAGACGCGA
 TCAGCCAAGG GCCACGCACA GACTTTCCGA GTGAACCTGA ACACCCTGCG
 CGGCTACTAC AACCAGAGCG AGCCCGGGTC TCACACCCTC CAGCGGATGT
 ACGGCTGCGA CGTGGGGCCG GACGGGAGAC TCCTGAGCGG GTATGAGCAG
 TTCGCCTACG ACGGCAGAGA TTACATCGCC CTGAACCAGG ACCTGCGCTC
 CTGGACCGCG GCGGACGCGG CGGCTCAGAT CTCCAAGCGC AAGTTAGAGA
 AGGAAGGTGT TGCGGCGCGT GTGAGGATCT ACCTGGAGGG CCGGTGCGTG
 GAGGGGCTCC GCAGATACCT GGAGACCGGG AAGGACACGC TGCAGCGCGC
 AGACCCTCCA AAGGCACATG TGACCCGACA CCCCATCACT GAGCGTGAGG
 TCACCCTGAG GTGCTGGGCC CTGGGCTTCT ACCCTGAGGA GATCTCACTG
 ACCTGGCAGC GCAATGGGGA GGACCAGACC CAGGACATGG AGCTAGTGGA
 GACCAGGCCT TCAGGGGATG GAACCTTCCA GAAGTGGGCA GCCCTGGTGG
 TGCCTTCTGG AGAGGAGCAG AGATACACGT GCCATGTGCA GCACGAGGGG
 CTTCAGGAGC CCCTCACCCT GAGATGGGCA CCTCCTCAGA CCTCCTTCCT
 CACCATGGGC ATCATTGTTG GCCTGGTTAT CCTCGCGGTG ACTGTGGTGG
 CTGGAGCTGT GGTCTGGAGG AAGAATCGCT CAGGTGAAAA AAGACGGACC
 TATACCCAGG CTGCAAGCAG TGACCGTGCC CAGGGCTCTG ATGTGTCTCT
 TATGGTTCCT AAAGTGTGA*

>DL;IPD:MHC02438
IPD:MHC02438 Ovar-N*00801, 1059 bases, CBAB369C checksum.
 TTCATGTCGC TCCTGTGGAC CCTGGTCCTG ACTGAGACCC TGTCTGGCCC
 CCACTCCCTG AGGTATTTCC TCACCGCCGT GTCCCGGCCC GGCCGCGGGG
 AGCCCCGCTT CATCGCCGTC GGCTACGTGG ACGACACGCA GTTCGTGCGG
 TTCGACAGCG ACGCCGCGGA TCCGAGGATG GAGCCGCGGG CGCGGTGGGT
 GGAGCAGGAG GGGCCGGAGT ATTGGGATCG GGAGACACGA AAGGCCAACG
 ATGACGCACA GACTTTCCGA GTGAACCTGA ACACCCTGCG CGGCTACTAC
 AACCAGAGCG AACCCGGGTC TCACACCCTC CAGGAGATGT ACGGCTGCGA
 CGTGGGGCCG GACGGGCTTC TCCTCCGCGG GTTCATGCAG TACGGCTACG
 AGGGCAGAGA TTACCTCGCC CTGAACGAGG ACCTGCGCTC CTGGACCGCG
 GCGGACACGG CGGCTCAGAT CTCCAAGCAC AATGCTGTGG TGGCAGGTGC
 TGCGGATCAC TACAGGAACT ACCTGGTGGG CGAGTGCGTG GAGTGGCTCC
 TCAGACACCT GGAGACCGGG AAGGACACGC TGCTGCGCGC AGACCCTCCA
 AAGGCACATG TGGCCCATCA CCCCATCTCT GAGCGTGAGG TCACCCTGAG
 GTGCTGGGCC CTGGGCTTCT ACCCTGAGGA GATCTCACTG ACATGGCAGC
 ATGAGGGGGA GGACCAGACC CAGGACATGG AGCTTGTGGA GACCAGGCCT
 TCAGGAGACG GAACCTTCCA GAAGTGGGCG GCCCTGGTGG TGCCTTCTGG
 AGAGGAGCAG AGATACACGT GCCGTGTGCA GCACGAGGGG CTTCAGGAGC
 CCCTCACCCT GAGATGGGAA CCTCCTCAGA CCTCCTTCCT CACCATGGGC
 ATCATTGTTG GCCTGGTTCT CCTTGTGGTG GCTGTGGTGG CTGGAGCTGT
 GATCTGGAGG AAGAAGCGCT CAGGTGAAAA AGGAGGGACC TACACCCAGG
 CTTCAAGCAG TGACAGTGCC CAGGGCTCTG ATGTGTCTCT CACGGTTCCT
 AAAGTGTGA*

>DL;IPD:MHC02779
IPD:MHC02779 Ovar-N*00901, 1067 bases, B9902425 checksum.
 ATGGGGCCGC GAACCCTCCT GTTGCTGCTC TCGGGAGTCC TGGTCCTGAC
 CGAGATCCGG GCGGGCCCCC ACTCCCTGAG GTATTTCCTC ACCGCCGTGT
 CCCGGCCCGG CCTCGGGGAG CCCCGCTTCA TCGCCGTCGG CTACGTGGAC
 GACATGCAGT TCGTGCGGTT CGACAGCGAC GCCCCGGATC CGAGGATGGA
 GCCGCGGGCG CGGTGGATGG AGCAGGAGGG GCCGGAGTAT TGGGATCAGG
 AGACGCGATC AGCCAAGGGC GACGCACAGA GTTTCCGAGC GAACCTGAAC
 ACCCTGCGCG GCTACTACAA CCAGAGCGAG GCCGGGTCTC ACACCCTCCA
 GGAGATGTAC GGCTGTGATG TGGGGCCGGA CGGGCGCCTC CTCCGCGGGT
 ACACGCAGTA CGCCTACGAC GGCAGAGATT ACATCGCCCT GAACGAGGAC
 CTGCGCTCCT GGACCGCGGC GGACACGGCG GCCCAGATCA CCCAGCGCAA
 GTTGGAGAAG GAAGGTGCGG CGGAGGCAGA AAGGAACTAC CTGGAGGGCA
 CGTGCGTGGA GTGGCTGCGC AGATACCTGG AGACCGGGAA GGACACGCTG
 CTGCGCGCAG ACCCTCCAAA GGCACATGTG ACCCATCACC CCATCTCTGG
 CCATGATGTC ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGAGGAGA
 TCTCACTGAC CTGGCAGCGC AATGGGGAGG ACCAGTTGCA GGACATGGAG
 CTTGTGGAGA CTAGGCCTTC AGGGGATGGA ACCTTCCAGA AGTGGGCAGC
 CCTGGTGGTG CCTTCTGGGG AGGAGCAGAG ATACACGTGC CATGTGCAGC
 ATGAGGGGCT TCAGGAGCCC CTCACCCTGA GATGGGAACC TCCTCAGACC
 TCCTTCCTCA CTTCCTCAAT GGGCATCATT GTTGGCCTGG TTCTCCTCGT
 CATGGTGGCT GTGGTGGCTG CAGCTGTGAT CTGGAGGAAG AAGTGCTCAG
 GTGAAAAAAG AGGGACCTAT ACCCAGGCTT CAAGCAATGA CAGTGCCCAG
 GGTTCTGATG TGTCTCT*

>DL;IPD:MHC02780
IPD:MHC02780 Ovar-N*01001, 1061 bases, 63954014 checksum.
 ATGGGGCCGC GAACCCTCCT GTTGCTGCTC TCGGGGGTCC TGGTCCTGAC
 CGAGATCCGG GCGGGCCCCC ACTCCCTGAG GTATTTCCTC ACCGCCGTGT
 CCCGGCCCGG CCTCGGGGAG CCCCGCTTCA TCGCCGTCGG CTACGTGGAC
 GACACGCAGT TCGTGCGGTT CGACAGCGAC GCCCCGGATC CGAGGATGGA
 GCCGCGGGCG CGGTGGATGG AGCAGGAGGG GCCGGAGTAT TGGGATCAGG
 AGACGCGATC AGCCAAGGGC CACGCACAGA GTTTCCGAGC GAACCTGAAC
 ACCCTGCGCG GCTACTACAA CCAGAGCGAG GCCGGGTCTC ACACCCTCCA
 GTGGATGTAC GGCTGTGATG TGGGGCCGGA CGGGCGCCTC CTCCGCGGGT
 ACAGGCAGGA CGCCTACGAC GGCAGAGATT ACATCGCCCT GAACGAGGAC
 CTGCGCTCCT GGACCGCGGC GGACACGGCG GCCCAGATCA CCCAGCGCAA
 GTGGGAGAAG GAAGGTGCGG CGGAGGCAGA AAGGAACTAC CTGGAGGGCA
 CGTGCGTGGA GTGGCTGCGC AGATACCTGG AGACCGGGAA GGACACGCTG
 CTGCGCGCAG ACCCTCCAAA GGCACATGTG ACCCATCACC CCATCTCTGG
 CCATGATGTC ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGAGGAGA
 TCTCACTGAC CTGGCAGCGC AATGGGGAGG ACCAGTTGCA GGACATGGAG
 CTTGTGGAGA CTAGGCCTTC AGGGGATGGA ACCTTCCAGA AGTGGGCGGC
 CCTGGTGGTG CCTTCTGGAG AGGAGCAGAG ATACACGTGC CATGTGCAGC
 ATGAGGGGCT TCAGGAGCCC CTCACCCTGA GATGGGAACC TCCTCAGACC
 TCCTTCCTCA CCATGGGCAT CATTGTTGGC CTGGTTCTCC TCGTCATGGT
 GGCTGTGGTG GCTGGAGCTG TGATCTGGAG GAAGAAGTGC TCAGGTGAAA
 AAAGAGGGAC CTATACCCAG GCTTCAAGCA ATGACAGTGC CCAGGGTTCT
 GATGTGTCTC T*

>DL;IPD:MHC02781
IPD:MHC02781 Ovar-N*01101, 1067 bases, 7A6A9093 checksum.
 ATGGGGCCGC GAACCCTCCT GTTGCTGCTC TCGGGAGTCC TGGTCCTGAC
 CGAGATCCGG GCGGGCCCCC ACTCCATGAG GTATGTCTAC ACCGGCGTGT
 CCCGGCCCGG CCTCGGGGAG CCCCGCTTCA TCGCCGTCGG CTACGTGGAC
 GACACGCAGT TCGTGCGGTT CGACAGCGAC GCCCCGGATC CGAGAATGGA
 GCCGCGGGCG CGGTGGGTGG AGCAGGAGGG GCCGGAGTAT TGGGATCGGG
 AAACTCGAAA CATGAAGGAC GCCACACAGA GTTTCCGAGT GGGCCTGAAC
 ACCCTGCGCG GCTACTACAA CCAGAGCGAG GCCGGGTCTC ACACCTGGCA
 GCGGATGTAC GGCTGCTACG TGGGGCCGGA CGGGCGTCTC CTCCGCGGGT
 ATGAGCAGTT CGGCTACGAC GGCAGAGATT ACATCGCCCT GAACGAGGAC
 CTGCGCTCCT GGACCGCGGC GGACACGGCG GCTCAGATCA CCCAGCGCAA
 GTGGGAGAAG GAGGGTGTTG CGGAGGCAGA AAGGAACTAC CTGGAGGGCC
 GGTGCGTGGA GTGGCTGCGC AGATACCTGG AGACCGGGAA GGACACGCTG
 CTGCGCGCAG ACCCTCCAAA GGCACATGTG ACCCATCACC CCATCTCTGG
 CCATGATGTC ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGAGGAGA
 TCTCACTGAC CTGGCAGCGC AATGGGGAGG ACCAGTTGCA GGACATGGAG
 CTTGTGGAGA CTAGGCCTTC AGGGGATGGA ACCTTCCAGA AGTGGGCAGC
 CCTGGTGGTG CCTTCTGGGG AGGAGCAGAG ATACACGTGC CATGTGCAGC
 ATGAGGGGCT TCAGGAGCCC CTCACCCTGA GATGGGAACC TCCTCAGACC
 TCCTTCCTCA CTTCCTCAAT GGGCATCATT GTTGGCCTGG TTCTCCTCGT
 CATGGTGGCT GTGGTGGCTG CAGCTGTGAT CTGGAGGAAG AAGTGCTCAG
 GTGAAAAAAG AGGGACCTAT ACCCAGGCTT CAAGCAATGA CAGTGCCCAG
 GGTTCTGATG TGTCTCT*

>DL;IPD:MHC02441
IPD:MHC02441 Ovar-N*50001, 1069 bases, 1F93A60D checksum.
 GCGAACGCTT CTCCTGCTGC TCTCGGGGGT CCTGGTCCTG AGCGAGACCT
 GGGCGGGCTC CCACTCCCTG AGGTATTTCC TCACCGCCGT GTCCCGGCCC
 GGCCTCGGGG AGCCCCGCTT CATCGCCGTC GGCTACGTGG ACGACACGCA
 GTTCGTGCGG TTCGACAGCG ACGCCCGGGA TCCGAGGATG GAGCCGCGGG
 CGCGGTGGGC GGAGCAGGAG GGGCCGGAGT ATTGGGATCA GGAGACGCGA
 TTAGCCAAGG ACGCCGCACA GACTTTCCGA GCGAACCTGA ACACCGCACT
 CGGCTACTAC AACCAGAGCG AGGCCGGGTC TCACACCGTC CAGGAGATGT
 ACGGCTGCGA CGTGGGGCCG GACGGGCGTT TTCTCCGCGG GTATGAGCAG
 CACGGCTACG ACGGCAGAGA TTACCTCGCC CTGAACGAGG ACCTGCGCTC
 CTGGACCGCG GCGGACACGG CGGCTCAGAT CACCAAACGC AAGTGGGAGG
 CGGCAGGTGA GGCGGAGAGA CACAGGAACT CCCTGGTGGG CGAGTGCGTG
 GAGGAGCTCC GCAGACACCT GGAGACCGGG AAGGACACGC TGCAGCGCGC
 AGACCCTCCA AAGGCACGTG TGACCCATCA CCCCGTCTCT GAGCGTGAGG
 TCACCCTGAG GTGCTGGGCC CTGGGCTTCT ACCCTGAGGA GATCTCACTA
 ACCTGGCAGC GCAATGAGGA GGACCAGACC CAGGACATGG AGCTTGTGGA
 GACCAGGCCT TCAGGGGATG GAACCTTCCA GAAGTGGGCG GCCCTGGTGG
 TGCCTTCTGG AGAGGAGCAG AGATACACGT GCCATGTGCA GCACGAGGGG
 CTTCAGGAGC CCCTCACCCT GAGATGGGAA CCTCCTCAGC CCTCCGTCCC
 CATCATGGGC ATCATTCTTG TCCTGGTTCT CCTCTTGGTG GCTTTGGTGG
 CTGGAGCTGT GATTTGGAGG AAGAAACGCT CAGGTGAAAA AGGACAGACC
 TACACCCAGG CTTCAAGCAG TGACAGTGCC CAGGGCTCTG ATGTGTCTCT
 CACAGTTCCT AAAGTGTGA*

>DL;IPD:MHC02435
IPD:MHC02435 Ovar-N*50101, 1069 bases, 8BACED2E checksum.
 GCGAACGCTT CTCCTGCTGC TCTCGGGGGT CCTGGTCCTG ACCGAGACCC
 TGGCGGGCTC CCACTCCCTG AGGTATGTCT ACACCGCCGT GTCCCGGCCC
 GGCCGCGGGG AGCCCCGCTT CATCGCCGTC GGCTACGTGG ACGACACGCA
 GTTCGTGCGG TTCGACAGCG ACGCCCCGGA TCCGAGGATG GAGCCGCGGG
 CGCGGTGGGT GGAGCAGGAG GGGCCGGAGT ATTGGGATCA GGAGACGAGA
 ATCTACAAGG ACGCCGCACA GAATTTCCGA GCGAACCTGA ACACCCTGCG
 CGGCTACTAC AACCAGAGCG AGGCCGGGTC TCACACCCTC CAGGCGATGT
 GCGGCTGCGA CGTGGGGCCT GACGGGCGTC TCCTCCGCGG GTTCATGCAG
 TACGGCTACG ACGGCAGAGA TTACATCGCC TTGAACGAGG ACCTGCGCTC
 CTGGACCGCG GCGGACACTG CGGCTCAGAT CTCCAAGCGC AAGATTGAGG
 CGGCAGGTGG TGCGGAGGGG CACAGGAACT ACTTTGAGGG CCTGTGCGTG
 GAGGAGCTCC GCAGATACCT GGAGACCGGG AAGGACACGC TGCTGCGCGC
 AGACCCTCCA AAGGCACGTG TGACCCATCA CCCCGTCTCT GAGCGTGAGG
 TCACCCTGAG GTGCTGGGCC CTGGGCTTCT ACCCTGAGGA GATCTCACTA
 ACCTGGCAGC GCAATGAGGA GGACCAGACC CAGGGCATGG AGCTTGTGGA
 GACCAGGCCT TCAGGGGATG GAACCTTCCA GAAGTGGGCG GCCCTGGTGG
 TGCCTTCTGG AGAGGAGCAG AGATACACGT GCCGTGTGCA GCACGAGGGG
 CTTCAGGAGC CCCTCACCCT GAGATGGGAA CCTCCTCAGC CCTCCGTCCC
 CATCATGGGC ATCATTCTTG TCCTGGTTCT CCTCTTGGTG GCTTTGGTGG
 CTGGAGCTGT GATTTGGAGG AAGAAACGCT CAGGTGAAAA AGGACAGACC
 TACACCCAGG CTTCAAGCAG TGACAGTGCC CAGGGCTCTG ATGTGTCTCT
 CACAGTTCCT AAAGTGTGA*

>DL;IPD:MHC02434
IPD:MHC02434 Ovar-N*50201, 1069 bases, F731CBAD checksum.
 GCGAACGCTT CTCCTGCTGC TCTCGGGGGT CCTGGTCCTG AGCGAGACCT
 GGGCGGGCTC CCACTCCCTG AGGTATGTCT ACACCTGCGT GTCCCGGCCC
 GGCCTCGGGG AGCCCCGCTT CATCGCCGTC GGCTACGTGG ACGACACGCA
 GTTCGTGCGG TTCGACAGCG AAGCCCGGAA TCCGAGGATG GAGCCGCGGG
 CGCGGTGGGC GGAGCAGGAG GGGCCGGAGT ATTGGGATCA GGAGACGAGA
 ATGGCCAAGG ACGCCGCACA GAATTTCCGA GTGAACCTGA ACACCCTGCG
 CGGCTACTAC AACCAGAGCG AGGCCGGGTC TCACACCGTC CAGGCGATGT
 GCGGCTGCGA CGTGGGGCCG GACTGGCGCC TCCTCCGCGG GTTCATGCAG
 TACGGCTACG ACGGCAGAGA TTACCTCGCC CTGAACGAGG ACCTGCGCTC
 CTGGACCGCG GCGGATGCGG CGGCTCAGAT CTCCAAGCGC AAGATTGAGG
 CTGCAGGTGG TGCGGAGGGA CACAGGAACT ACTTTGAGGG CCTGTGCGTG
 GAGATGCTCC GCAGATACCT GGAGAAAGGG AAGGACACGC TGCAGCGTGC
 AGACCCTCCA AAGGCACGTG TGACCCATCA CCCCGTCTCT GAGCGTGAGG
 TCACCCTGAG GTGCTGGGCC CTGGGCTTCT ACCCTGAGGA GATCTCACTG
 ACCTGGCAGC GCAATGAGGA GGACCAGACC CAGGACATGG AGCTTGTGGA
 GACCAGGCCT TCAGGGGATG GAACCTTCCA GAAGTGGGCG GCCCTGGTGG
 TGCCTTCTGG AGAAGAGCAG AGATACACAT GCCATGTGCA GCACGAGGGG
 CTTCAGGAGC CCCTCACCCT GAGATGGGAA CCTCCTCAGC CCTCCGTCCC
 CATCATGGGC ATCATTCTTG TCCTGGTTCT CCTCTTGGTG GCTTTGGTGG
 CTGGAGCTGT GATTTGGAGG AAGAAACGCT CAGGTGAAAA AGGACAGACC
 TACACCCAGG CTTCAAACAG TGACAGTGCC CAGGGCTCTG ATGTGTCTCT
 CACAGTTCCT AAAGTGTGA*

>DL;IPD:MHC02442
IPD:MHC02442 Ovar-N*50301, 1069 bases, FBB3369D checksum.
 GCGAACGCTT CTCCTGCTGC TCTCAGGGGC CCTGGTCCTG GCCGAGACCC
 GGGCTGGCTC CCACTCCCTG AGGTATTTCC TCACCGCCGT GTCCCGGCCG
 GGCCTCGGGG AGCCCCGCTT CATCATCGTC GGCTACGTGG ACGACACGCA
 GTTCCTGCGG TTCGACAGCG ACGCCCCGCA TCCAAGGTTG GAGCCGCGGA
 CGCGGTGGAT AGAGCAGGAG GGGCCGGAGT ATTGGGATGA GGAGACGCGG
 ATAGCCAAGG ACGGCATACA GACTTTCCGA GCGAACCTGA ACACCCTGCG
 CGGCTACTAC AACCAGAGCG AGGCCGGGTC TCACACCCTC CAGAATATGC
 ACTGCTGTGG CGTGGGGCCG GACGGGCGTC TCCTCCGCGG GTTCATGCAG
 TTCGGCTACG ACGGCAGAGA TTACATCGCC CTGAACGAGG ACCTGCGCTC
 CTGGACCGCG GCGGACACGG CGGCTCGGAT CACCCAGCGC AAGTGGGAGG
 CGTTAGGTGC TGCGGAGGAA CAAAGGAACT ACTTTGAGGG CAAGTGTGTG
 AACTTGCTCC GCAGACACCT GGAGAACGGG AAGGACACGC TGCTGCGCAC
 AAACCCTCCA AAGGCACATG TGACCCATCA CCCCACCTCT GAGCGTGAGG
 TCACCCTGAG GTGCTGGGCC CTGGGCTTCT ACCCTGAGGA GATCTCACTG
 ACCTGGCAAC GCAATGGGGA GGACCAGACC CAGGACATGG AGCTTGTGCA
 GACCAGGCCT TCAGGGGATG GAACTTTCCA GAAGTGGGCG GCCCTGGTGG
 TTCCTTCTGG AGAGGAGCAG AGATACACGT GCCATGTACA GCACGAGGGG
 CTTCAGGAGC CCCTCACCCT GAGATGGGAA CCTCCTCAGT CCTCCATCCC
 CATCATGGGC ATCGTTCTTG TCCTGGTTCT CCTTGTGGTG GCTGTGGTCG
 CTGGAGCTGT GATTTGGAGG AAGAAACGCT CAGGTGAAAA TGGACAGACC
 TATACCCAGG CTGCAAGCAG TGACGGTGCC TAGGGCTCTG ATGTGTCTCT
 CACAGTTCCT AAAGTGTGA*

