>P1;BoLA-DQA*0101
BoLA-DQA*0101  256 bases  
 MILNRALIWG ALALTTMMGP SGSEDIVADH IGAYGINVYH TYGPSGYYTH
 EFDGDEEFYV DLEKRETVWR LPVFSKFTSF DPQGALRNIA TAKHNLEVLI
 QRSNSTAATN KVPEMTVFPK SPVMLGQPNT LICHVDNIFP PVINITWLRN
 GHLVIEGISE TSFLSKDDHS FAKISYLTFL PSDDDVYDCK VEHWGLDKPL
 LKHWEPEIPA PMSELTETVV CALGLTVGLV GIVVGTVLII RGLRSGGPSR
 HQGPLX*

>P1;BoLA-DQA*0102
BoLA-DQA*0102  82 bases  
 DHIGAYGINV YHTYGPSGYY THEFDGDEEF YVDLEKRETV WRLPVFSKFT
 SFDPQGALRN IATVKHNLEI LIQRSNSTAA TN*

>P1;BoLA-DQA*0103
BoLA-DQA*0103  82 bases  
 DHIGAYGINV YHTYGPSGYY THEFDGDEEF YVDLEKRETV WRLPVFSKFT
 SFDPQGALRN IATTKHNLEI MIRRSNSTAA TN*

>P1;BoLA-DQA*0104
BoLA-DQA*0104  71 bases  
 GAYGINVYHT YGPSGYYTHE FDGDEEFYVD LEKRETVWRL PVFSKFTSFD
 PQGALRNIAT VKHNLEVLIQ R*

>P1;BoLA-DQA*0105
BoLA-DQA*0105  71 bases  
 GAYGINVYHT YGPSGYFTHE FDGDEEFYVD LEKRETVWRL PVFSKFTSFD
 PQGALRNIAT VKHNLEIVIQ R*

>P1;BoLA-DQA*0201
BoLA-DQA*0201  230 bases  
 VADHIGRYGI NVYHTYGPSG YYTHEFDGDE EFYVDLEKRE TVWNLPLFSK
 FRRFDPQGAL RNIATVKHNL EIVIQRSNST AATNKVPEVT VFSKSPMMLG
 QPNTLICHVD NIFPPVINIT WLKNGHLVIE GISETSFLSK DDHSFSKISY
 LTFLPSDDDV YDCKVEHWGL DKPLLKHWEP DIPAPMSELT ETVVCALGLT
 VGLVGIVVGT VLIIRGLRSG GPSRDQGPLX*

>P1;BoLA-DQA*0202
BoLA-DQA*0202  75 bases  
 AYGINVYHTY GPSGYFTHEF DGDEEFYVDL EKRETVWNLP LFSKFRRFDP
 QGALRNIATV KHNLEIVIQR SNSTA*

>P1;BoLA-DQA*0203
BoLA-DQA*0203  82 bases  
 DHIGAYGINV YHTYGPSGYY THEFDGDEEF YVDLEKRETV WNLPLFSKFR
 RFDPQGALRN IATVKHNLEI VIQRSNSTAA TN*

>P1;BoLA-DQA*0204
BoLA-DQA*0204  82 bases  
 DHIGAYGINV YHTYGPSGYY THEFDGDEEF YVDLEKRETV WNLPLFSKFR
 RFDPQGALRN IATAKHNLEI VIQRSNSTAA TN*

>P1;BoLA-DQA*0205
BoLA-DQA*0205  71 bases  
 GAYGINVYHT YGPSGYYTHE FDGDEEFYVD LEKRETVWNL PLFSKFRRFD
 PQGALRNIAT AKHNLEVLIQ R*

>P1;BoLA-DQA*0206
BoLA-DQA*0206  71 bases  
 GAYGINVYHT YGPSGYYTHE FDGDEEFYVD LEKRETVWNL PLFSKFRRFD
 PQGALRNIAT AKHNLEIVIQ R*

>P1;BoLA-DQA*0301
BoLA-DQA*0301  82 bases  
 DHIGAYGINV YHSYGPSGYY THEFDGDEEF YVDLEKRETV WNLPLFSKFR
 RFDPQGALRN IATTKHNLEI MMQRSNSTAA TN*

>P1;BoLA-DQA*0302
BoLA-DQA*0302  74 bases  
 AYGINVYHSY GPSGYYTHEF DGDEEFYVDL EKRETVWNLP LFSKFRRFDP
 RGALRNIATT KHNLEIMMQG SNST*

>P1;BoLA-DQA*0401
BoLA-DQA*0401  82 bases  
 DHIGAYGINV YHSYGPSGYY THEFDGDEEF YVDLEKRETV WNLPLFSKFR
 RFDPQGALRN IATAKHNLEV LIQRSNSTTA TN*

>P1;BoLA-DQA*0801
BoLA-DQA*0801  82 bases  
 DHIGAYGINV YHSYGPSGYY THEFDGDEQF YVDLEKRETV WRLPVFSKFA
 SFDPQGALRN IATAKHNLEI MIQESNSTAA TN*

>P1;BoLA-DQA*0802
BoLA-DQA*0802  82 bases  
 DHIGAYGINV YHSYGPSGYY THEFDGDEQF YVDLEKRETV WRLHVFSKFA
 SFDPQGALRN IATAKHNLEI MIQESNSTAS TN*

>P1;BoLA-DQA*0803
BoLA-DQA*0803  71 bases  
 GAYGINVYHS YGPSGYYTHE FDGDEEFYVD LEKRETVWRL PVFSKFTSFD
 PQGALRNIAT AKHNLEIMIQ E*

>P1;BoLA-DQA*10011
BoLA-DQA*10011  82 bases  
 DHIGTYGISV YHTYGPSGYY THEFDGDEEF YVDLEKRETV WRLPVFSKFT
 SFDPQGALRN IAIVKHNLEI VIQRSNSTAA TN*

>P1;BoLA-DQA*10012
BoLA-DQA*10012  82 bases  
 DHIGTYGISV YHTYGPSGYY THEFDGDEEF YVDLEKRETV WRLPVFSKFT
 SFDPQGALRN IAIVKHNLEI VIQRSNSTAA TN*

>P1;BoLA-DQA*1002
BoLA-DQA*1002  80 bases  
 DHIGAYGINV YHTYGPSGYY THEFDGDEEF YVDLEKRETV WRLPVFSKFT
 SFDPQGALRN IAIVKHNLDI VIQRSNSTAA*

>P1;BoLA-DQA*1101
BoLA-DQA*1101  82 bases  
 DHIGAYGINV YHTYGPSGYY THEFDGDEEF YVDLEKRETV WRLPVFSKFA
 TFDPQGALRN IATMKHNLEI VIQRSNSTAA TN*

>P1;BoLA-DQA*12011
BoLA-DQA*12011  256 bases  
 MVLNRALILG ALALTTMMSP SGSEDIVADH IGTYGISVYH TYGPSGYYTH
 EFDGDEEFYV DLEKRETVWR LPVFSKFATF DPQGALRNIA TTKHNLEIVI
 QRSNSTAATN KVPEVTVFSK SPVMLGQPNT LICHVDNIFP PVINITWLRN
 GHSVTEGVSE TSFLIKSDYS FLKINYLTFL PSDDDVYDCK VEHWGLDEPL
 LKHWEPDIPA PMSELTETVV CALGLTVGLV GIMVGTILII QGLRSGGPSR
 HQGPLX*

>P1;BoLA-DQA*12012
BoLA-DQA*12012  75 bases  
 TYGISVYHTY GPSGYYTHEF DGDEEFYVDL EKRETVWRLP VFSKFATFDP
 QGALRNIATT KHNLEIVIQR SNSTA*

>P1;BoLA-DQA*12021
BoLA-DQA*12021  256 bases  
 MILNRALILG ALALTTMMSP SGSEDIVADH IGTYGISVYH TYGPSGYYTH
 EFDGDEEFYV DLEKRETVWR LPVFSKFATF DPQGALRNIA TMKHNLEIVI
 QRSNSTAATN KVPEVTVFSK SPVMLGQPNT LICHVDNIFP PVINITWLRN
 GHSVTEGVSE TSFLIKSDYS FLKINYLTFL PSDDDVYDCK VEHWGLDEPL
 LKHWEPDIPA PMSELTETVV CALGLTVGLV GIMVGTILII QGLRSGGPSR
 HQGPLX*

>P1;BoLA-DQA*12022
BoLA-DQA*12022  82 bases  
 DHIGTYGISV YHTYGPSGYY THEFDGDEEF YVDLEKRETV WRLPVFSKFA
 TFDPQGALRN IATMKHNLEI VIQRSNSTAA TN*

>P1;BoLA-DQA*1203
BoLA-DQA*1203  228 bases  
 DHIGTYGISV YHTYGPSGYY THEFDGDEEF YVDLEKRETV WRLPVFSKFA
 TFDPQGALRN IATSKHDLEV LIQRSNSTAA TNKVPEVTVF SKSPVMLGQP
 NTLICHVDNI FPPVINITWL RNGHSVTEGV SETSFLIKSD YSFLKINYLT
 FLPSDDDVYD CKVEHWGLDE PLLKHWEPDI PAPMSELTET VVCALGLTVG
 LVGIMVGTIL IIQGLRSGGP SRHQGPLX*

>P1;BoLA-DQA*1204
BoLA-DQA*1204  80 bases  
 DHIGTYGISI YHSYGPSGYY THEFDGDEEF YVDLEKRETV WRLPVFSKFA
 TFDPQGALRN IATTKHNLEI VIQRSNSTAA*

>P1;BoLA-DQA*1301
BoLA-DQA*1301  80 bases  
 DHIGAYGINV YHSYGPSGYY THEFDGDEQF YVDLEKKETV WRLPVFSKFA
 TFDPQGALRN IAVGKQTLEV MIRRSNSTAA*

>P1;BoLA-DQA*1302
BoLA-DQA*1302  74 bases  
 AYGINVYHTY GPSGYYTHEF DGDEQFYVDL EKKETVWRLP VFSKFATFDP
 QGALRNIAVG KQTLEVMIRR SNST*

>P1;BoLA-DQA*1401
BoLA-DQA*1401  82 bases  
 DHIGAYGINV YHSYGPSGYY THEFDGDEEF YVDLEKRETV WRLPVFSKFA
 SFDPQGALRN IAVGKRTLEV MIRRSNSTAA TN*

>P1;BoLA-DQA*2001
BoLA-DQA*2001  74 bases  
 SYGTEVYQSH GPSGQYTQEF DGDEMFYVDL GKKETVWRLP SFSQFAGFDP
 QAALSEIATS KHNLDVLTKR SNFT*

>P1;BoLA-DQA*2002
BoLA-DQA*2002  82 bases  
 DHVGSYGTEV YQSHGPSGQY TQEFDGDEMF YVDLGKKETV WRLPTFSQFA
 GFDPQAALSE IATSKHNLDV LTKRSNFTPV IN*

>P1;BoLA-DQA*2003
BoLA-DQA*2003  75 bases  
 AEFYQSHGPS GQYTQEFDGD EMFYVDLGKK ETVWRLPMFS QFAGFDPQAA
 LSEIATSKHN LDVLTKRSNF TPVIN*

>P1;BoLA-DQA*2101
BoLA-DQA*2101  82 bases  
 DHVGSYGTEV YQSHGPSGQY TQEFDGDEMF YVDLGKKETV WRLPIFSQFA
 GFDPQFALSE IATSKHNLDV LTKRSNFTPV IN*

>P1;BoLA-DQA*2201
BoLA-DQA*2201  256 bases  
 MVLNRALILG ALALTTMMSP NGGEDIVADH VGSYGTEVYQ SHGPSGQYTQ
 EFDGDEMFYV DLGKKETVWR LPMFSQFAGF DPQAALSEIA TSKHNLDVLT
 KRSNFTPVIN EVPEVTVFSK SPVILSQPNT LICHVDNIFP PVINITWLKN
 GHAVTEGVSE TSFLPKDDHS FLKIGYLTFL PSDNDIYDCK VEHWGLDEPL
 LKHWEPEVPA PMSELTETVV CALGLTVGLV GIVVGTIFII QGLRSGGTSR
 HQGPLX*

>P1;BoLA-DQA*22021
BoLA-DQA*22021  256 bases  
 MVLNRALILG ALALTTMMSP SGGEDIVADH VGSYGTEVYQ SHGPSGQYTQ
 EFDGDEMFYV DLGKKETVWR LPMFSQFAGF DPQAALSEIA TAKHNLDVLT
 KRSNFTPVIN EVPEVTVFSK SPVMLGQPNT LICHVDNIFP PVINITWLKN
 GHAVTEGVSE TSFLPKDDHS FLKIGYLTFL PSDNDIYDCK VEHWGLDEPL
 LKHWEPEVPA PMSELTETVV CALGLTVGLV GIVVGTIFII QGLRSGGASR
 HQGPLX*

>P1;BoLA-DQA*22022
BoLA-DQA*22022  74 bases  
 SYGTEVYQSH GPSGQYTQEF DGDEMFYVDL GKKETVWRLP MFSQFAGFDP
 QAALSEIATA KHNLDVLTKR SNFT*

>P1;BoLA-DQA*22023
BoLA-DQA*22023  82 bases  
 DHVGSYGTEV YQSHGPSGQY TQEFDGDEMF YVDLGKKETV WRLPMFSQFA
 GFDPQAALSE IATAKHNLDV LTKRSNFTPV IN*

>P1;BoLA-DQA*22031
BoLA-DQA*22031  82 bases  
 DHVGSYGTEV YQSHGPSGQY TQEFDGDELF YVDLGKKETV WRLPMFSQFA
 GFDPQAALSE IATAKHNLDV LTKRSNFTPV IN*

>P1;BoLA-DQA*22032
BoLA-DQA*22032  74 bases  
 SYGTEVYQSH GPSGQYTQEF DGDELFYVDL GKKETVWRLP MFSQFAGFDP
 QAALSEIATA KHNLDVLTKR SNFT*

>P1;BoLA-DQA*2204
BoLA-DQA*2204  82 bases  
 DHVGSYGTEV YQSHGPSGQY TQEFDGDEMF YVDLGKKETV WRLLMFSQFA
 GFDPQAALSE IATAKHNLDV LTKRSNFTPV IN*

>P1;BoLA-DQA*2205
BoLA-DQA*2205  74 bases  
 SYGTEVYQSH GPSGQYTQEF DGDEMFYVDL GKKETVWRLP MFSQFAGFAP
 QAALSEIATS KHNLDVLTKR SNFT*

>P1;BoLA-DQA*2207
BoLA-DQA*2207  75 bases  
 AEFYQSHGPS GQYTQEFDGD ELFYVDLGKK ETVWRLPMFS QFAGFDPQAA
 LSEIATAKHN LDVLTKRSNF TPVIN*

>P1;BoLA-DQA*2301
BoLA-DQA*2301  74 bases  
 SYGIDFYQSH GPSGQYIHEF DGDEMFYVDL GKKETVWRLP MFGELTGFDP
 QGALRNIATE KHNLDILTKC SNFT*

>P1;BoLA-DQA*2401
BoLA-DQA*2401  82 bases  
 DHVGSYGTEV YQSHGPSGQY THEFDGDELF YVDLGKKETV WRLPMFGDLT
 SFDPQGALSE IATSKHNLDI LTRRSNFTPA IN*

>P1;BoLA-DQA*25011
BoLA-DQA*25011  80 bases  
 DHVGTYGTDF YQSHGPSGQY IHQFDGDEEF YVDLEKEEAV WRLPMFDKRF
 HPQGALRNIA IAKHNLDVLT KLYNFTPVIN*

>P1;BoLA-DQA*25012
BoLA-DQA*25012  80 bases  
 DHVGTYGTDF YQSHGPSGQY IHQFDGDEEF YVDLEKEEAV WRLPMFDKRF
 HPQGALRNIA IAKHNLDVLT KLYNFTPVIN*

>P1;BoLA-DQA*2502
BoLA-DQA*2502  80 bases  
 DHVGTYGADF YQSHGPSGQY IHQFDGDEEF YVDLEKEEAV WRLPMFDKRF
 HPQGALRNIA IAKHNLDVLT KLYNFTPVIN*

>P1;BoLA-DQA*2601
BoLA-DQA*2601  74 bases  
 TYGTDFYQSH GPSGQYIHQF DGDEEFYVDL EKEEAVWRLP MFDKLRRFHP
 QGALRDIAVA KHNLDVLTKR YNFT*

>P1;BoLA-DQA*2602
BoLA-DQA*2602  74 bases  
 TYGTDFYQSH GPSGQYIHQF DGDEEFYVDL EKEEAVWRLP MFDKLRRFHP
 QGALRNIAVA KHNLDVLTKR YNFT*

>P1;BoLA-DQA*2603
BoLA-DQA*2603  78 bases  
 TYGTDFYQSH GPSGQYIHQF DGDEEFYVDL EKEEAVWRLP MFDKLRRFHP
 QGALRNIAIA KHNLDVLTKL YNFTPVIN*

>P1;BoLA-DQA*27011
BoLA-DQA*27011  82 bases  
 DHIGTYGADF YQSHGPSGQY IHEFDGDELF YVDLGKKETV WQLPMFGELT
 SFEAQDALNE IAKAKHTLDV LTKRSNFTPV IN*

>P1;BoLA-DQA*27012
BoLA-DQA*27012  74 bases  
 TYGADFYQSH GPSGQYIHEF DGDELFYVDL GKKETVWQLP MFGELTSFEA
 QDALNEIAKA KHTLDVLTKR SNFT*

>P1;BoLA-DQA*2702
BoLA-DQA*2702  82 bases  
 DHIGTYGAEF YQSHGPSGQY IHEFDGDELF YVDLGKKETV WQLPMFGELT
 SFEAQDALNE IAKAKHTLDV LTKRSNFTPV IN*

>P1;BoLA-DQA*2703
BoLA-DQA*2703  78 bases  
 DHIGTYGADF YQSHGPSGQY IHEFDGDELF YVDLGKKETV WQLPMFGELI
 SFEAQDALNE IAKAKHTLDV LTKRSNFT*

>P1;BoLA-DQA*2704
BoLA-DQA*2704  79 bases  
 GTYGAEFYQS HGPSGQYIHE FDGDELFYVD LGKKETVWQL PMFGELTSFE
 AQDALNEIAK AKHTLDVLTK RSNFTPVIN*

>P1;BoLA-DQA*2801
BoLA-DQA*2801  75 bases  
 IYGISVYQSY GPSGQYTHEF DGDEQFYVDL EKKETAWQLP LFSRMLSFDP
 QLALRNIAIM KLHVDFLTKF SNSTA*

>P1;BoLA-DQA*2901
BoLA-DQA*2901  78 bases  
 DHVGSFGTEI YQSHGPSGQF THEFDGDELF YVDLGKKETV WRLPMFSQFA
 GFDPQAALSE IATSKHNLDV LTKRSNFT*

>P1;BoLA-DQA*3001
BoLA-DQA*3001  82 bases  
 DHVGTYGADF YQSHGPSGQY IHEFDGDELL YVDLEKKETV WRLPMFGELT
 GFDPQGALSE IASSKHNLDV LTKRSNFTPV IN*

>P1;BoLA-DQA*3101
BoLA-DQA*3101  79 bases  
 GSYGTVISQS HGPSDQYTQE FDGDKLFYVD LEKKETVWRL PMFSQFASFD
 PQAILRNIAI SKHNLNIMIK YSNFIPAIN*

