>P1;BoLA-DRB3*0101
BoLA-DRB3*0101  199 bases  
 HFLEYSKSEC HFFNGTERVR FLDRYYTNGE ETVRFDSDWG EFRAVTELGR
 QDAEYWNSQK DFLEEKRAEV DRVCRHNYGG MESFTVQRRV EPTVTVYPAK
 TQPLQHHNLL VCSVNGFYPG HIEVRWFRNA HEEEAVDHPS RTSPITVEWR
 ARSDSAQSKM MSGVGGFVLG LLFLAVGLFI YFRNQKGRPT LQPTGLLSX*

>P1;BoLA-DRB3*0102
BoLA-DRB3*0102  233 bases  
 MVCLYFSGGS WMAALIVMLM VLCPPLAWAR EIQPHFLEYS KSECHFFNGT
 ERVRFLDRYY TNGEETVRFD SDWGEFRAVT ELGWQDAEYW NSQKDFLEEK
 RAEVDRVCRH NYGGMESFTV QRRVEPTVTV YPAKTQPLQH HNLLVCSVNG
 FYPGHIEVRW FRNGHEEEAV DHPSRTSPIT VEWRARSDSA QSKMMSGVGG
 FVLGLLFLAV GLFIYFRNQK GRPTLQPTGL LSX*

>P1;BoLA-DRB3*0103
BoLA-DRB3*0103  89 bases  
 HFLEYSKSEC HFFNGTERVR FLDRYYTNGE ETVRFDSDWG EFRAVTELGR
 QDAEYWNSQK DILEEKRAEV DRVCRHNYGG MESFTVQRR*

>P1;BoLA-DRB3*0201
BoLA-DRB3*0201  87 bases  
 HFLEYSTSEC HFFNGTERVR FLDRYFHNGE EFVRFDSDWG EYRAVTELGR
 PDAEYWNSEI LERARAAVDT YCRHNYGGVE SFTVQRR*

>P1;BoLA-DRB3*0301
BoLA-DRB3*0301  86 bases  
 EYCKSECHFF NGTERVRFLE RSFYNGEEFV RFDSDWGEYR AVTELGRPDA
 KYWNSQKDLL EQKRANVDTY CRHNYGVGES FTVQRR*

>P1;BoLA-DRB3*03021
BoLA-DRB3*03021  89 bases  
 HFLEYCKSEC HFFNGTERVR FLERSFYNGE EFVRFDSDWG EYRAVTELGR
 PDAKYWNSQK DLLEQKRANV DTYCRHNYGV VESFTVQRR*

>P1;BoLA-DRB3*03022
BoLA-DRB3*03022  78 bases  
 EYCKSECHFF NGTERVRFLE RSFYNGEEFV RFDSDWGEYR AVTELGRPDA
 KYWNSQKDLL EQKRANVDTY CRHNYGVV*

>P1;BoLA-DRB3*0303
BoLA-DRB3*0303  83 bases  
 EYCKSECHFF DGTERVRFLE RSFYNGEEFV RFDSDWGEYR AVTELGRPDA
 KLWNSQKDLL EQKRANVDTY CRHNYGVVES FTV*

>P1;BoLA-DRB3*0401
BoLA-DRB3*0401  83 bases  
 EYSTSECHFF NGTERVRFLD RYFYNGEEYV RFDSDWGEFQ AVTELGRPDA
 KYWNSQKDIL ERERAAVDTY CRHNYGGVES FTV*

>P1;BoLA-DRB3*0402
BoLA-DRB3*0402  77 bases  
 EYSTSECHFF NGTERVRFLD RYFYNGEEYV RFDSDWGEFQ AVTELGRPDA
 KYWNSQKDIL ERERAYVDTY CRHNYGG*

>P1;BoLA-DRB3*0501
BoLA-DRB3*0501  86 bases  
 EYHKSECHFF NGTERLRYLD RYFYNGEEYV RFDSDWGEYR AVTELGRPDA
 KYWNSQKEIL ERKRANVDTY CRHNYGVVES FTVQRR*

>P1;BoLA-DRB3*0502
BoLA-DRB3*0502  89 bases  
 HFLEYHKSEC HFFNGTERLR YLDRYFYNGE EYVRFDSDWG EYRAVTELGR
 PDAKYWNSQK DLLERKRANV DTYCRHNYGV GESFTVQRR*

>P1;BoLA-DRB3*0503
BoLA-DRB3*0503  89 bases  
 HFLEYSKSEC HFFNGTERLR YLDRYFYNGE EYVRFDSDWG EYRAVTELGR
 PDAKYWNSQK EILERKRANV DTYCRHNYGV FESFTVQRR*

>P1;BoLA-DRB3*0504
BoLA-DRB3*0504  89 bases  
 HFLEYYKSEC HFFNGTERLR YLDRYFYNGE EYVRFDSDWG EYRAVTELGR
 PDAKYWNSQK EILERKRANV DTYCRHNYGV FESFTVQRR*

>P1;BoLA-DRB3*0601
BoLA-DRB3*0601  83 bases  
 EYCKRECHFF NGTERVRLLD RCFHNGEEFV RFDSDWGEFR AVTELGRRVA
 EHLNSQKEIL ERKRAEVDTV CRHNYGVGES FTV*

>P1;BoLA-DRB3*0701
BoLA-DRB3*0701  89 bases  
 HFLEYCKREC HFFNGTERVR FLDRCFHNGE EFVRFDSDWG EFRAVTELGR
 RVAEQWNSQK DFLEERRAEV DRVCRHNYGV VESFTVQRR*

>P1;BoLA-DRB3*0702
BoLA-DRB3*0702  78 bases  
 EYCKRECHFF NGTERVRFLD RCFHNGEEFV RFDSDWGEFR AVTELGWRDA
 EQWNSQKDFL EERRAEVDRV CRHNYGVV*

>P1;BoLA-DRB3*0703
BoLA-DRB3*0703  78 bases  
 EYSKSECHFF NGTERVRLLD RCFHNGEEFV RFDSDWGEFQ AVTELGRRVA
 EQWNSQKDFL EERRAEVDRV CRHNYGVV*

>P1;BoLA-DRB3*0801
BoLA-DRB3*0801  89 bases  
 HFLEYATSEC HFFNGTERVR FLDRYFHNGE ELVRFDSDWG EFRAVTELGR
 PSAVHLNSQK DFLEDERASV DTYCRHNYGV VESFTVQRR*

>P1;BoLA-DRB3*0901
BoLA-DRB3*0901  89 bases  
 HFLEYSKSEC HFFNGTERVR FLERSFYNGE ENVRFDSDWG EYRAVTELGR
 PDAEYWNSQK EILERKRANV DRVCRHNYGV GESFTVQRR*

>P1;BoLA-DRB3*0902
BoLA-DRB3*0902  89 bases  
 HFLEYSKSEC HFFNGTERVR FLERSFYNGE ENVRFDSDWG EYRAVTELGR
 PDAEYWNSQK EILEERRAEV DRVCRHNYGV GESFTVQRR*

>P1;BoLA-DRB3*0903
BoLA-DRB3*0903  89 bases  
 HFLEYFKSEC HFFNGTERVR FLERSFYNGE ENVRFDSDWG EYRAVTELGR
 PDAEYWNSQK EILEEKRADV DRVCRHNYGV GESFTVQRR*

>P1;BoLA-DRB3*1001
BoLA-DRB3*1001  89 bases  
 HFLEYSKSEC HFFNGTERVR FLDRYFHNGE EYVRFDSDWG EYRAVTELGQ
 RVAEYCNSQK DFLERARAAV DTYCRHNYGV GESFTVQRR*

>P1;BoLA-DRB3*1002
BoLA-DRB3*1002  89 bases  
 HFLEYYKREC HFFNGTERVR FLDRYFHNGE EYVRFDSDWG EYRAVTELGQ
 RVAEYCNSQK DFLERARAAV DTYCRHNYGV GESFTVQRR*

>P1;BoLA-DRB3*1101
BoLA-DRB3*1101  89 bases  
 HFLQYHKGEC HFFNGTERVR LLDRHFYNGE EYVRFDSDWD EFRAVTELGR
 PSAEYWNSQK DFLERRRAEV DTVCRHNYGV VESFTVQRR*

>P1;BoLA-DRB3*1103
BoLA-DRB3*1103  83 bases  
 EYYKGECHFF NGTERVRLLD RHFYNGEEYV RFDSDWGEFR AVTELGRPDA
 EYWNSQKDFL ERKRAEVDTV CRHNYGVVES FTV*

>P1;BoLA-DRB3*1201
BoLA-DRB3*1201  89 bases  
 HFLEYTKKEC HFFNGTERVR FLNRYFHNGE EFVRFDSDWG EYRAVTELGR
 PDAEYWNSQK EILERARAAV DTYCRHNYGV GESFTVQRR*

>P1;BoLA-DRB3*1202
BoLA-DRB3*1202  78 bases  
 EYTKKECHFF NGTERVRFLN RYFHNGEEFV RFDSDWGEYR AVTELGRPDA
 EYWNSQKEIL ERGRAAVDTY CRHNYGVG*

>P1;BoLA-DRB3*1301
BoLA-DRB3*1301  89 bases  
 HFLEYLKSEC HFFNGTERVR FLERYFYNGE EYVRFDSDWG EYRAVTELGR
 PDAKYWNSQK DLLERKRANV DTYCRHNYGV VESFTVQWR*

>P1;BoLA-DRB3*1302
BoLA-DRB3*1302  89 bases  
 HFLEYLKSEC HFFNGTERVR FLERSFYNGE ENVRFDSDWG EYRAVTELGR
 PDAKYWNSQK DLLERKRANV DTYCRHNYGV VESFTVQRR*

>P1;BoLA-DRB3*14011
BoLA-DRB3*14011  89 bases  
 HFLQYHKGEC HFFNGTERVR LLDRHFYNGE EFVRFDSDWD EFRAVTELGR
 PAAEQWNSQK DFLEQKRAEV DRVCRHNYGG VESFTVQRR*

>P1;BoLA-DRB3*14012
BoLA-DRB3*14012  83 bases  
 QYHKGECHFF NGTERVRLLD RHFYNGEEFV RFDSDWDEFR AVTELGRPAA
 EQWNSQKDFL EQKRAEVDRV CRHNYGGVES FTV*

>P1;BoLA-DRB3*1402
BoLA-DRB3*1402  78 bases  
 EYLKSECHFF NGTERVRLLD RHFYNGEEFV RFDSDWDEFR AVTELGRPAA
 EQWNSQKDFL EQKRAEVDRV CRHNYGGV*

>P1;BoLA-DRB3*1501
BoLA-DRB3*1501  89 bases  
 HFLEYSTSEC HFFNGTERVR YLDRYFHNGE EFVRFDSDWG EYRAVTELGR
 RVAEQLNGQK DTLERERAYV DTYCRHNYGV VESFTVQRR*

>P1;BoLA-DRB3*1502
BoLA-DRB3*1502  78 bases  
 EYSTSECHFF NGTERVRYLD RYFHNGEEFV RFDSDWGEYR AVTELGRRSA
 EQLNGQKDTL ERERAYVDTY CRHNYGVV*

>P1;BoLA-DRB3*1503
BoLA-DRB3*1503  78 bases  
 EYSTSECHFF NGTERVRLLD RYFYNGEEFV RFDSDWGEYR AVTELGRRVA
 EQLNGQKDTL ERERAYVDTY CRHNYGVV*

>P1;BoLA-DRB3*1504
BoLA-DRB3*1504  89 bases  
 HFLEYFTSEC HFFNGTERVR YLDRYFHNGE EFVRFDSDWG EYRAVTELGR
 RVAEQLNGQK DTLERERAYV DTYCRHNYGV VESFTVQAR*

>P1;BoLA-DRB3*1505
BoLA-DRB3*1505  89 bases  
 HFLEYSTSEC HFFNGTERVR FLDRYFHNGE EFVRFDSDWG EFRAVTELGR
 RVAEHWNGQK DTLERERAYV DTYCRHNYGV VESFTVQRR*

>P1;BoLA-DRB3*1506
BoLA-DRB3*1506  89 bases  
 HFLEYSTSEC HFFNGTERVR YLDRYFHNGE EFVRFDSDWG EYRAVTELGR
 RVAEQLNGQK DTLEQERAYV DTYCRHNYGV VESFTVQAR*

>P1;BoLA-DRB3*1601
BoLA-DRB3*1601  218 bases  
 MVCLYFSGGS WMAALIVMLM VLCPPLAWAR EIQPHFLEYT KKECHFFNGT
 ERVRFLDRYF HNGEEFVRFD SDWGEYRAVT ELGRPDAKYW NSQKDFLEEK
 RAAVDTYCRH NYGVGESFTV QPLQHHNLLV CSVNGFYPGN IEVRWFRNGH
 EEEAVDHPSR TSPITVEWRA RSDSAQSKMM SGVGGFVLGL LFLDVGLFIY
 FRNQKGRPTL QPTGLLSX*

>P1;BoLA-DRB3*1602
BoLA-DRB3*1602  83 bases  
 EYTKKECHFF NGTERVRFLD RYFHNGEEFV RFDSDWGEYR AVTELGRPDA
 EYWNSQKDLL ERKRANVDTY CRHNYGVGES FTV*

>P1;BoLA-DRB3*1701
BoLA-DRB3*1701  83 bases  
 EYATSECHFF NGTERVRFLH RYFYNGEEYA RFDSDWGEFR AVTELGRPDA
 KYWNSQKEIL ERERAYVDTY CRHNYGVGES FTV*

>P1;BoLA-DRB3*1702
BoLA-DRB3*1702  83 bases  
 EYATSECHFF NGTERVRFLH RYFYNGEEYA RFDSDWGEFW AVTELGRPDA
 KYWNSQKEIL ERERAYVDTY CRHNYGVGES FTV*

>P1;BoLA-DRB3*1703
BoLA-DRB3*1703  83 bases  
 EYSTGECHFF NGTERVRYLD RYFYNGEEYA RFDSDWGEFR AVTELGRPDA
 KYWNSQKEIL ERERAYVDTY CRHNYGVGES FTV*

>P1;BoLA-DRB3*1801
BoLA-DRB3*1801  86 bases  
 EYATSECHFF NGTERVRFLH RYFHNGEEFV RFDSDWGEFR AVTELGRPAA
 EQWNSQKDTL ERERAYVDTY CRHNYGGVES FTVQRR*

>P1;BoLA-DRB3*1802
BoLA-DRB3*1802  83 bases  
 EYATSECHFF NGTERVRFLD RYFHNGEEFV RFDSDWGEFR AVTELGRPAA
 EQWNSQKDTL ERERAYVDTY CRHNYGVVES FTV*

>P1;BoLA-DRB3*1901
BoLA-DRB3*1901  83 bases  
 EYSKSECHFF NGTERVRYLD RYFYNGEEYV RFDSDWGEYR AVTELGRPSA
 EYWNSQKDIL ERKRANVDTY CRHNYGVGES FTV*

>P1;BoLA-DRB3*1902
BoLA-DRB3*1902  89 bases  
 HFLEYSKSEC HFFNGTERVR YLDRYFYNGE EFVRFDSDWG EYRAVTELGR
 PDAEYWNSQK DILERKRANV DTYCRHNYGV VESFTVQRR*

>P1;BoLA-DRB3*1903
BoLA-DRB3*1903  83 bases  
 EYSKSECHFF NGTERVRYLD RSFYNGEEFV RFDSDWGEYR AVTELGRRVA
 EYWNSQKDIL ERKRANVDTY CRHNYGVCES FTV*

>P1;BoLA-DRB3*20011
BoLA-DRB3*20011  83 bases  
 EYCKRECHFF NGTERVRLLD RYFYNGEERV RFDSDWGEFR AVTELGRPSA
 EYWNSQKDFL EQRRAAVDTY CRHNYGVVES FTV*

>P1;BoLA-DRB3*20012
BoLA-DRB3*20012  83 bases  
 EYCKRECHFF NGTERVRLLD RYFYNGEERV RFDSDWGEFR AVTELGRPSA
 EYWNSQKDFL EQRRAAVDTY CRHNYGVVES FTV*

>P1;BoLA-DRB3*2002
BoLA-DRB3*2002  83 bases  
 EYCKRECHFF NGTERVRLLD RYFYNGEERV RFDSDWGEFR AVTELGRPDA
 EYWNSQKDFL EQRRAAVDTY CRHNYGVGES FTV*

>P1;BoLA-DRB3*2003
BoLA-DRB3*2003  83 bases  
 EYCKRECHFF NGTERVRLLD RYFYNGEERV RFDSDWGEFR AVTELGRPDA
 EYWNSQKDFL EQRRAAVDTY CRHNYGVVES FTV*

>P1;BoLA-DRB3*2004
BoLA-DRB3*2004  85 bases  
 YCKRECHFFN GTERVRLLDR YFYNGEERVR FDSDWGEFRA VTELGRPSAE
 YWNSQKDFLE QRRAVVDTYC RHNYGVVESF TVQRR*

>P1;BoLA-DRB3*2005
BoLA-DRB3*2005  83 bases  
 EYSTSECHFF NGTERVRLLD RYFYNGEERV RFDSDWGEFR AVTELGRPDA
 EYWNSQKDFL EQRRAAVDTY CRHNYGVVES FTV*

>P1;BoLA-DRB3*2101
BoLA-DRB3*2101  115 bases  
 IVMLMVLCPP LAWAREIQPH FLEYSTGECH FFNGTERVRF LDRYFYNGEE
 YVRFDSDWGE YRAVTELGRQ DAEQWNSQKD FLEERRAEVD TYCRHNYGVG
 ESFTVQRRVE PIVTV*

>P1;BoLA-DRB3*2201
BoLA-DRB3*2201  115 bases  
 IVMLMVLCPP LAWAREIQPH FLQYHKGECH FFNGTERVRL LDRHFYNGEE
 YVRFDSDWGE YRAVTELGRP SAEHWNSQKE ILERRRAEVD RVCRHNYGVG
 ESFTVQRRVE PIVTV*

>P1;BoLA-DRB3*2202
BoLA-DRB3*2202  83 bases  
 QYHKGECHFF NGTERVRLLD RHFTNGEEYV RFDSDWGEYR ALTELGRPSA
 EHWNSQKEIL ERRRAEVDRV CRHNYGVGES FTV*

>P1;BoLA-DRB3*2203
BoLA-DRB3*2203  78 bases  
 QYHKGECHFF NGTERVRLLD RHFYNGEEHV RFDSDWGEYR AVTELGRPSA
 EHWNSQKEIL ERRRAEVDRV CRHNYGVG*

>P1;BoLA-DRB3*2301
BoLA-DRB3*2301  83 bases  
 EYTKKECHFF NGTERVRLLD RYYTNGEETV RFDSDWGEFR AVTELGRQDA
 EQWNSQKDTL EDERAAVDTY CRYNYGVGES FTV*

>P1;BoLA-DRB3*2401
BoLA-DRB3*2401  83 bases  
 EYCKRECHFF NGTERVRFLD RYFYNGEEYV RFDSDWGEFR AVTELGRPDA
 EYWNSQKEIL EERRAEVDRV CRHNYGVGES FTV*

>P1;BoLA-DRB3*2402
BoLA-DRB3*2402  83 bases  
 EYCKRECHFF NGTERVRFLD RYFYNGEEYV RFDSDWGEFR AVTELGRPSA
 EYWNSQKEIL EERRAEVDRV CRHNYGVGES FTV*

>P1;BoLA-DRB3*2403
BoLA-DRB3*2403  75 bases  
 KRECHFFNGT ERVRFLDRYF YNGEEYVRFD SDWGEFRAVT ELGRPDAEYW
 NSQKDFLEER RAEVDRVCRH NYGVG*

>P1;BoLA-DRB3*25011
BoLA-DRB3*25011  83 bases  
 EYSTSECHFF NGTERVRYLD RYFHNGEEFV RFDSDWGEFR AVTELGRPAA
 EQWNSQKDTL EDERASVDTY CRYNYGVGES FTV*

>P1;BoLA-DRB3*25012
BoLA-DRB3*25012  83 bases  
 EYSTSECHFF NGTERVRYLD RYFHNGEEFV RFDSDWGEFR AVTELGRPAA
 EQWNSQKDTL EDERASVDTY CRYNYGVGES FTV*

>P1;BoLA-DRB3*2502
BoLA-DRB3*2502  74 bases  
 SECHFFNGTE RVRYLDRYFH NGEEFVRFDS DWGEFRAVTE LGRQDAEQWN
 SQKDTLEDER AAVDTYCRYN YGVG*

>P1;BoLA-DRB3*2601
BoLA-DRB3*2601  89 bases  
 HFLEYTKKEC HFFNGTERVR FLDRYFHNGE ETVRFDSDWG EYRAVTELGR
 RVAEQWNSQK DTLERARAAV DTYCRHNYGV GESFTVQRR*

>P1;BoLA-DRB3*2701
BoLA-DRB3*2701  89 bases  
 HFLEYYKREC HFFNGTERVR FLDRCFHNGE EFVRFDSDWG EFRAVTELGR
 PDAEYWNSQK DFLEERRAEV DRVCRHNYGV GESFTVQRR*

>P1;BoLA-DRB3*2702
BoLA-DRB3*2702  83 bases  
 EYYKRECHFF NGTERVQFLD RCYTNGEETV RFDSDWGEFR AVTELGRPDA
 EYWNSQKDFL EERRAEVDRV CRHNYGVGES FTV*

>P1;BoLA-DRB3*2703
BoLA-DRB3*2703  89 bases  
 HFLEYYKREC HFFNGTERVR FLDRCYTNGE ETVRFDSDWG EFRAVTELGR
 PDAEYWNSQK DFLEERRAEV DRVCRHNYGV GESFTVQRR*

>P1;BoLA-DRB3*2704
BoLA-DRB3*2704  83 bases  
 EYYKRECHFF NGTERVRFLD RCFHNGEEFV RFDSDWGEFR AVTELGRPAA
 EYWNSQKDFL EERRAEVDRV CRHNYGVGES FTV*

>P1;BoLA-DRB3*2705
BoLA-DRB3*2705  83 bases  
 EYYKRECHFF NGTERVRFLD RCYTNGEETV RFDSDWGEFR AVTELGRPDA
 EYWNSQKDFL EERRAAVDRV CRHNYGVVES FTV*

>P1;BoLA-DRB3*2706
BoLA-DRB3*2706  78 bases  
 EYYKRECHFF NGTERVRFLD RCYTNGEETV RFDSDWGEFR AVTELGRPSA
 EYWNSQKDIL EERRAEVDRV CRHNYGVV*

>P1;BoLA-DRB3*2707
BoLA-DRB3*2707  83 bases  
 EYYKRECHFF NGTERVRFLD RCYTNGEETV RFDSDWGEFR AVTELGRPDA
 EYWNSQKDFL EERRAEVDRV CRHNYGVVES FTV*

>P1;BoLA-DRB3*2708
BoLA-DRB3*2708  83 bases  
 EYYKRECHFF NGTERVRFLD RCFHNGEEFV RFDSDWGEFR AVTELGRPDA
 EYWNSQKDFL EERRAEVDTV CRHNYGVGES FTV*

>P1;BoLA-DRB3*2709
BoLA-DRB3*2709  85 bases  
 YYKRECHFFN GTERVRFLDR YYTNGEETVR FDSDWGEFRA VTELGRPDAE
 YWNSQKDFLE ERRAEVDRVC RHNYGVGESF TVQRR*

>P1;BoLA-DRB3*2710
BoLA-DRB3*2710  83 bases  
 EYYKRECHFF NGTERVRFLD RCFHNGEEFV RFDSDWGEFR AVTELGRPDA
 EYWNSQKDFL EERRAEVDRV CRHNYGVGES FTV*

>P1;BoLA-DRB3*2801
BoLA-DRB3*2801  115 bases  
 IVMLMVLCPP LAWAREIQPH FLQYHKGECH FFNGTERVRL LDRHFYNGEE
 FVRFDSDWDE FRAVTELGRP AAEYWNSQKD FLEERRAEVD TYCRHNYGGV
 ESFTVQRRVE PIVTV*

>P1;BoLA-DRB3*2802
BoLA-DRB3*2802  89 bases  
 HFLQYHKGEC HFFNGTERVR LLDRHFYNGE EYVRFDSDWD EFRAVTELGR
 PAAEYWNSQK DFLEERRAEV DTYCRHNYGG VESFTVQRR*

>P1;BoLA-DRB3*2901
BoLA-DRB3*2901  83 bases  
 EYAQSECHFF NGTERVRFLH RYFHNGEEFV RFDSDWGEFR AVTELGQRVA
 EQWNSQKDTL ERERAYVDTY CRHNYGVGES FTV*

>P1;BoLA-DRB3*3001
BoLA-DRB3*3001  83 bases  
 EYSKSECHFF NGTERVRFLD RYYTNGEETV RFDSDWGEFR ALTELGRQDA
 EQWNSQKEIL EDERAAVDTY CRYNYGVGES FTV*

>P1;BoLA-DRB3*3002
BoLA-DRB3*3002  83 bases  
 EYCKSECHFF NGTERVRFLD RYYTNGEETV RFDSDWGEFR ALTELGRQDA
 EQWNSQKEIL EDERAAVDTY CRHNYGGVES FTV*

>P1;BoLA-DRB3*3101
BoLA-DRB3*3101  233 bases  
 MVCLYFSGGS WMAALIVMLM VLCPPLAWAR EIQPHFLEYY KGECHFFNGT
 ERVRFLDRHF YNGEEFVRFD SDWGEFRAVT ELGRPAAEHW NSQKDFLEQK
 RAEVDRVCRH NYGGVESFTV QRRVEPTVTV YPAKTQPLQH HNLLVCSVNG
 FYPGHIEVRW FRNGHEEEAV DHPSRTSPIT VEWRARSDSA QSKMMSGVGG
 FVLGLLFQAV GLFIYFRNQK GRPTLQPTGL LSX*

>P1;BoLA-DRB3*3102
BoLA-DRB3*3102  78 bases  
 EYSKGECHFF NGTERVRFLD RHFYNGEEFV RFDSDWGEFR AVTELGRPAA
 KYWNSQKDFL EQKRAEVDRV CRHNYGGV*

>P1;BoLA-DRB3*3103
BoLA-DRB3*3103  89 bases  
 HFLEYYKGEC HFFNGTERVR FLDRHFYNGE EFVRFDSDWD EFRAVTELGR
 PAAEHWNSQK DFLEQKRAEV DRVCRHNYGG VESFTVQRR*

>P1;BoLA-DRB3*3104
BoLA-DRB3*3104  89 bases  
 HFLQYYKGEC HFFNGTERVR FLDRHFYNGE EFVRFDSDWG EFRAVTELGR
 PAAEHWNSQK DFLERKRAEV DRVCRHNYGV VESFTVQRR*

>P1;BoLA-DRB3*3201
BoLA-DRB3*3201  181 bases  
 HFLEYCKREC HFFNGTERVR FLDRYFYNGE EYVRFDSDWG EFRAVTELGR
 PDAKYWNSQK EILERERAYV DTYCRHNYGV GESFTVQRRV EPIVTVYPAK
 TQPLQHHNLL VCSVNGFYPG HIEVRWFRNG HEEEAVDHPS RTSPITVEWR
 ARSDSAQSKM MSGVGGFVLG LLFLTVGLFI X*

>P1;BoLA-DRB3*3202
BoLA-DRB3*3202  86 bases  
 EYCKRECHFF NGTERVRFLD RYFYNGEEYV RFDSDWGEFR AVTELGRPDA
 KYWNSQKEIL ERERAYVDTY CRHNYGVVES FTVQRR*

>P1;BoLA-DRB3*3203
BoLA-DRB3*3203  83 bases  
 EYCKKECHFF NGTERVRFLD RYFYNGEEYV RFDSDWGEFR AVTELGRPDA
 KYWNSQKEIL ERERAYVDTY CRHNYGVVES FTV*

>P1;BoLA-DRB3*3301
BoLA-DRB3*3301  81 bases  
 EYSTSECHFF NGTERVRLLD RYFYNGEEYV RFDSDWGEYQ AVTELGRPSA
 EHWNSEILEQ RRAAVDTYCR HNYGVVESFT V*

>P1;BoLA-DRB3*3401
BoLA-DRB3*3401  89 bases  
 HFLEYCKSEC HFFNGTERVR FLERSFYNGE EFVRFDSDWG EYRAVTELGR
 RVAEQLNSQK DLLEQKRANV DTYCRHNYGV VESFTVQRR*

>P1;BoLA-DRB3*3402
BoLA-DRB3*3402  83 bases  
 EYCKSECHFF NGTERVRFLE RSFYNGEEFV RFDSDWGEYR AVTELGRRVA
 KQLNSQKDLL EQKRANVDTY CRHNYGVVES FTV*

>P1;BoLA-DRB3*3501
BoLA-DRB3*3501  89 bases  
 HFLEYSKSEC HFFNGTERVR YLDRYYTNGE ENVRFDSDWG EFRAVTELGR
 PDAEYWNSQK DFLERKRANV DTYCRHNYGV FESFTVQRR*

>P1;BoLA-DRB3*3601
BoLA-DRB3*3601  83 bases  
 EYSKSECHFF NGTERVRFLD RYYTNGEETV RFDSDWGEFR ALTELGRQDA
 EQWNSQKDTL ERERAYVDTY CRHNYGGVES FTV*

>P1;BoLA-DRB3*3701
BoLA-DRB3*3701  78 bases  
 EYSTSECHFF NGTERVRYLD RYFYNGEEYV RFDSDWGEFR AVTELGRPDA
 KYWNSQKDTL EDERASVDTY CRYNYGVG*

>P1;BoLA-DRB3*3801
BoLA-DRB3*3801  78 bases  
 EYSKSECHFF NGTERVRYLD RYFYNGEEYV RFDSDWGEYR AVTELGRPDA
 EYWNSQKDFL ERKRANVDTY CRHNYGVV*

>P1;BoLA-DRB3*3901
BoLA-DRB3*3901  78 bases  
 EYSTGECHFF NGTERVRYLD RYFYNGEEYV RFDSDWGEFQ AVTELGRPDA
 EYWNSQKDTL ERERAYVDTY CRHNYGVG*

>P1;BoLA-DRB3*4001
BoLA-DRB3*4001  83 bases  
 EYSTGECHFF NGTERVRYLD RYFYNGEEYA RFDSDWGEFR AVTELGRPDA
 KYWNSQKDFL EQKRAEVDRV CRHNYGGVES FTV*

>P1;BoLA-DRB3*4002
BoLA-DRB3*4002  75 bases  
 KGECHFFNGT ERVRLLDRHF YNGEEYVRFD SDWGEFRAVT ELGRPDAKYW
 NSQKDFLEQK RAEVDRVCRH NYGGV*

>P1;BoLA-DRB3*4101
BoLA-DRB3*4101  81 bases  
 EYTKKECHFF NGTERVRFLD RYFYNGEEYV RFDSDWSEYR AVTELGRPDA
 EYWNSEILER ARAAVDTYCR HNYGVGESFT V*

>P1;BoLA-DRB3*4201
BoLA-DRB3*4201  83 bases  
 EYRKSECHFF NGTERVRFLD RYFYNGEEHV RFDSDWGEYR AVTELGRPDA
 KYWNSQKEIL ERRRAEVDTV CRHNYGVVES FTV*

>P1;BoLA-DRB3*4301
BoLA-DRB3*4301  89 bases  
 HFLEYRKSEC HFFNGTERVR YLDRSFYNGE EFVRFDSDWG EYRAVTELGR
 RVAEQWNSQK DLLERKRANV DTYCRHNYGV GESFTVQRR*

>P1;BoLA-DRB3*4302
BoLA-DRB3*4302  89 bases  
 HFLEYRKSEC HFFNGTERVR YLDRYFYNGE EFVRFDSDWG EYRAVTELGR
 RVAEQWNSQK DLLERKRANV DTYCRHNYGV GESFTVQRR*

>P1;BoLA-DRB3*4303
BoLA-DRB3*4303  83 bases  
 EYCKSECHFF NGTERVRYLD RSFYNGEEFV RFDSDWGEYR AVTELGRRVA
 EQWNSQKDFL ERKRANVDTY CRHNYGVGES FTV*

>P1;BoLA-DRB3*4401
BoLA-DRB3*4401  89 bases  
 HFLEYYKSEC HFFNGTERVR FLDRYYTNGE ETVRFDSDWG EFRALTELGR
 QDAEQWNSQK DFLERARAAV DTYCRYNYGV GESFTVQRR*

>P1;BoLA-DRB3*4501
BoLA-DRB3*4501  83 bases  
 EYYKRECHFF NGTERVRFLD RCYTNGEETV RFDSDWGEFR AVTELGRPDA
 KYWNSQKDFL EQARAAVDTY CRHNYGVGES FTV*

>P1;BoLA-DRB3*46011
BoLA-DRB3*46011  83 bases  
 EYCKRECHFF NGTERVRFLD RYFYNGEEYV RFDSDWGEFR AVTELGRPDA
 KYWNSQKDFL EQARAAVDTY CRHNYGVGES FTV*

>P1;BoLA-DRB3*4701
BoLA-DRB3*4701  83 bases  
 EYTKKECHFF NGTERVRLLD RYFYNGEERV RFDSDWGEYR EVTELGRPSA
 EYWNSQKDFL EQRRAAVDTY CRHNYGVVES FTA*

>P1;BoLA-DRB3*4801
BoLA-DRB3*4801  78 bases  
 EYSKSECHFF NGTERVRLLD RYYTNGEETV RFDSDWGEFR AVTELGRPDA
 EYWNSQKDFL EQRRAEVDTY CRHNYGVV*

>P1;BoLA-DRB3*4802
BoLA-DRB3*4802  89 bases  
 HFLEYCKREC HFFNGTERVR LLDRYYTNGE ETVRFDSDWG EFRAVTELGR
 PDAEYWNSQK DFLEQRRAAV DTYCRHNYGV VESFTVQRR*

>P1;BoLA-DRB3*4901
BoLA-DRB3*4901  78 bases  
 EYSTGECHFF NGTERVRYLD RYFYNGEEYA RFDSDWGEFR AVTELGRPDA
 KYWNSQKDFL EEKRAYVDTY CRHNYGVG*

>P1;BoLA-DRB3*5001
BoLA-DRB3*5001  78 bases  
 EYSTGECHFF NGTERVRYLD RYFHNGEELV RFDSDWGEFR AVTELGRPDA
 EHLNGQKDTL ERERAYVDTY CRHNYGVV*

>P1;BoLA-DRB3*5101
BoLA-DRB3*5101  79 bases  
 LEYSKKECHF FNGTERVRFL DRSFHNGEEI VRFDSDWGEY RAVTELGRPD
 AEYWNSQKDF LEEKRAAVDR YCRHNYGVG*

>P1;BoLA-DRB3*5701
BoLA-DRB3*5701  83 bases  
 EYYKSECHFF NGTERVRYLD RYFYNGEEYV RFDSDWGEYR AVTELGRPDA
 KYWNSQKEIL ERRRAEVDTV CRHNYGVVES FTV*

>P1;BoLA-DRB3*5702
BoLA-DRB3*5702  83 bases  
 EYHKSECHFF NGTERLRYLD RYFYNGEEYV RFDSDWGEYR AVTELGRPDA
 KYWNSQKEIL ERRRAEVDTV CRHNYGVGES FTV*

>P1;BoLA-DRB3*5801
BoLA-DRB3*5801  83 bases  
 EYRKSECHFF NGTERVRFLD RYYTNGEETV RFDSDWGEFR ALTELGRPDA
 EYWNSQKEIL ERRRAEVDTV CRHNYGVFES FTV*

>P1;BoLA-DRB3*5901
BoLA-DRB3*5901  83 bases  
 EYSKSECHFF NGTERLRYLD RYFHNGEEYV RFDSDWGEFR AVTELGRPDA
 EYWNSQKDIL EHKRAYVDTY CRYNYGVFES FTV*

>P1;BoLA-DRB3*6001
BoLA-DRB3*6001  83 bases  
 EYYKRECHFF NGTERLRFLD RYFYNGEEYV RFDSDWGEYR AVTELGRPVA
 KYWNSQKDFL ERKRATVDTY CRHNYGVFES FTV*

>P1;BoLA-DRB3*6101
BoLA-DRB3*6101  83 bases  
 EYATSECHFF NGTERVRFLH RYFHNGEEFV RFDSDWGEFR AVTELGRQDA
 EYWNSQKDLL ERKRASVDTY CRHNYGGVES FTV*

>P1;BoLA-DRB3*6201
BoLA-DRB3*6201  83 bases  
 EYFKSECHFF NGTERVRFLD RSYYNGEENV RFDSDWGEFR ALTELGRPDA
 EYWNSQKDLL ERKRANVDTY CRHNYGVVES FTV*

>P1;BoLA-DRB3*6301
BoLA-DRB3*6301  87 bases  
 HFLEYTKKEC HFFNGTERVR FLDRYFHNGE EVVRFDSDWG EYRAVTELGR
 PDAEYWSSEI LERARAAVDT YCRHNYGVGE SFTVQRR*

>P1;BoLA-DRB3*6401
BoLA-DRB3*6401  83 bases  
 EYYKGECHFF NGTERVRFLD RHFYNGEEYV RFDSDWGEFR AVTELGRPDA
 KYWNSQKDFL EQKRAEVDRV CRHNYGGVES FTV*

>P1;BoLA-DRB3*6402
BoLA-DRB3*6402  83 bases  
 EYYKGECHFF NGTERVRFLD RFFYNGEEYV RFDSDLGEFR AVTELGRPDA
 EYWNSQKDFL EQKRAEVDRV CRHNYGGVES FTV*

>P1;BoLA-DRB3*6501
BoLA-DRB3*6501  83 bases  
 EYFKSECHFF NGTERVRFLE RSFYNGEENV RFDSDWGEYR ALTELGRPDA
 KYWNSQKDML ERKRANVDTY CRYNYGVVES FTV*

>P1;BoLA-DRB3*6601
BoLA-DRB3*6601  83 bases  
 EYYKSECHFF NGTERVRYLD RSFYNGEEFV RFDSDWGEYR AVTELGRPVA
 EHWNSQKDFL ERKRANVDTC CRHNYGVGES FTV*

>P1;BoLA-DRB3*6701
BoLA-DRB3*6701  89 bases  
 HFLEYSKSEC HFFNGTERVR FLDRYFHNGE EFVRFDSDWG EYRAVTELGR
 PDAEYWNSQK DFLERKRAYV DTYCRHNYGV GESFTVQRR*

>P1;BoLA-DRB3*6801
BoLA-DRB3*6801  89 bases  
 HFLQYHKGEC HFFNGTERVR FLDRHFYNGE EFVRFDSDWG EFRAVTELGR
 PDAEYWNSQK DFLERKRAEV DTYCRHNYGV VESFTVQRR*

>P1;BoLA-DRB3*6901
BoLA-DRB3*6901  89 bases  
 HFLEYSTNEC HFFNGTERVR YLDRYFHNGE EFVRFDSDWG EYRAVTELGR
 RDAEYWNSQK DTLERERAYV DTYCRHNYGV VESFTVQRR*

>P1;BoLA-DRB3*7001
BoLA-DRB3*7001  89 bases  
 HFLEYSKSEC HFFNGTERVR FLDRYFHNGE ENVRFDSDWG EFRAVTELGR
 PAAEYWNSQK DILERERAYV DTYCRHNYGV VESFTVQRR*

>P1;BoLA-DRB3*7101
BoLA-DRB3*7101  89 bases  
 HFLEYSKNEC HFFNGTERVR FLDRYFHNGE EFVRFDSDWG EDRAVTELGR
 PVAEYWNSQK DFLEEKRVYV DTYCRHNYGV GESFTVQRR*

