>DL;BoLA-DQB*0101
BoLA-DQB*0101  243 bases  
 TACCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGAACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTTCA ACAGCCAGAA GGACTTCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*0102
BoLA-DQB*0102  243 bases  
 TACCAGTTTA TGGGCCAGTG TTATTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGAACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTTCA ACAGCCAGAA GGACTTCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*0103
BoLA-DQB*0103  737 bases  
 TACCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGACACATCT ACAACCAGGA GGAGAACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGT GGAAGCCCCC TTCGGCCTGT
 GTTACTTCAC CAACGGGACG GAGCGGGTGC GGTACGTGAC CAGACACATC
 TACAACCAGG AGGAGAACGT GCGGTTCGAC AGCGACTGGG ACGAGTACCG
 GGCGGTGACC CCGCTGGGGC GGCCGGACGC CGAGTACTGG AACAGCCAGA
 AGGACATCCT GGAGCGGACG CGGGCCGAGG CGGACACGGT GTGCAGACAC
 AACTACCAGG TGGAAGCCCC CTTCACCTGG CAGCGGCTAG GGCCTGTGTT
 ACTTCACCAA CGGGACGGAG CGGGTGCGGT ACGTGACCAG ACACATCTAC
 AACCAGGAGG AGAACGTGCG GTTCGACAGC GACTGGGACG AGTACCGGGC
 GGTGACCCCG CTGGGGCGGC CGGACGCCGA GTACTGGAAC AGCCAGAAGG
 ACATCCTGGA GCGGACGCGG GCCGAGGCGG ACACGGTGTG CAGACACAAC
 TACCAGGTGG AAGCCCCCTT CACCTGGCAG CGGCTAG*

>DL;BoLA-DQB*0104
BoLA-DQB*0104  247 bases  
 GGCCTGTGTT ACTTCACCAA CGGGACGGAG CGGGTGCGGA GTGTGAACAG
 ATACATCTAC AACCAGGAGG AGTACGTGCG GTTCGACAGC GACTGGGACG
 AGTACCGGGC GCTGACCCCG CTGGGGCGGC CGGACGCCGA GTACTGGAAC
 AGCCAGAAGG ACATCCTGGA GCGGACGCGG GCCGAGGCGG ACACGGTGTG
 CAGAAACAAC TACCAGGTGG ATGCCCCCTT CACCTGGCAG CGGCTAG*

>DL;BoLA-DQB*0201
BoLA-DQB*0201  243 bases  
 TACCAGTTTA AGTGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACGTGGG CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGCCCGCC
 GAGCACTGGA ACAGCCAGAA GGACTTCCTG GAGCAGACGC GGGCCGAGGT
 GGACAGCGTG TGCAGACACA ACTACCAACT GGAGCTCATC ACA*

>DL;BoLA-DQB*0301
BoLA-DQB*0301  243 bases  
 TTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GCTCGTGACC AGAAACATAT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGG CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACCTCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGC GAGGCTCATC ACA*

>DL;BoLA-DQB*0302
BoLA-DQB*0302  243 bases  
 TTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GCTCGTGACC AGAAACATAT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGG CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACCTCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*0303
BoLA-DQB*0303  266 bases  
 TTTCGTGTTC CAGTTTAAGG GCCTGTGTTA CTTCACCAAC GGGACGGAGC
 GGGTGCGGCT CGTGACCAGA AACATATACA ACCAGCTGCA GTACGTGCGG
 TTCGACAGCG ACTGGGGCGA GTACCGGGCG CTGACCCCGC TGGGGCGGCC
 GGACGCCGAG TACTGGAACA GCCAGAAGGA CCTCCTGGAG CAGACGCGGG
 CCGAGGCGGA CACGGTGTGC AGACACAACT ACCAGGCGGA GCTCATCACA
 TCCTTGCAGC GGCGAG*

>DL;BoLA-DQB*0401
BoLA-DQB*0401  243 bases  
 GTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGAACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGGTGC GGGCCGAGGT
 GGACAGGGTG TGCAGAAACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*0402
BoLA-DQB*0402  243 bases  
 TACCAGTTTA AGTGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGAACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGGTGC GGGCCGAGGT
 GGACAGGGTG TGCAGAAACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*0403
BoLA-DQB*0403  243 bases  
 TACCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGCCGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGGTGC GGGCCGAGGT
 GGACAGGGTG TGCAGAAACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*0404
BoLA-DQB*0404  243 bases  
 TACCAGTTTA AGTGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGCCGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGGTGC GGGCCGAGGT
 GGACAGGGTG TGCAGAAACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*0405
BoLA-DQB*0405  266 bases  
 TTTCGTGTAC CAGTTTAAGT GCCTGTGTTA CTTCACCAAC GGGACGGAGC
 GGGTGCGGTA CGTGACCTGC AGCATCTACA ACCAGGAGGA GAACGTGCGG
 TTCGACAGCG ACTGGGACGA GTACCGGGCG GTGACCCCGC TGGGGCGGCC
 GGACGCCGAG TACTGGAACA GCCAGAAGGA CATCCTGGAG CGGGTGCGGG
 CCGAGGTGGA CAGGGTGTGC AGAAACAACT ACCAGGCGGA GCTCATCACA
 TCCTTGCAGC GGCGAG*

>DL;BoLA-DQB*0501
BoLA-DQB*0501  243 bases  
 TACCAGTATA AGGGCCTGTG TTACTTCACC AACGGGACGC AGCGGGTGCG
 GCTCGTGACC AGATACATCT ACAACCGGGA GGAGTTCGCG CGGTTCGACA
 GCGACGTGAA CGAGTTCCGG GCGGTGACCC CACTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCAGAGGC GGGCCGAGGT
 GGACAGGGTG TGCAGACACA ACTACCAGCT GGATGCCCCC TTC*

>DL;BoLA-DQB*0502
BoLA-DQB*0502  243 bases  
 TACCAGTATA AGGGCCTGTG TTACTTCACC AACGGGACGC AGCGGGTGCG
 GCTCGTGACC AGATACATCT ACAACCGGGA GGAGTTCGCG CGGTTCGACA
 GCGACGTGAA CGAGTTCCGG GCGGTGACCC CACTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGACGC GGGCCGAGGT
 GGACAGGGTG TGCAGACACA ACTACCAGGT GGATGCCCCC TTC*

>DL;BoLA-DQB*0601
BoLA-DQB*0601  240 bases  
 TACCAGTTTA TATACCAGTG TTACTTCACC AATGGGACAG AGCGGGTGCG
 GAGTGTGAAA AAACAGATCT ACAACCGGCA AGAACACGTG CGATTCGACA
 GCGACGTGAA CGAGTTCCGG GCGGTTTCCC CGCTGGGGCA GCGGGACGCC
 GAGTACTTCA ATAGCCACGA CTTCCTGAAG CAGACGCGGG CCGAGGTGGA
 CACGGTGTGC AGACACAACT ACCAACTGGA GCTCCTCACA*

>DL;BoLA-DQB*0701
BoLA-DQB*0701  243 bases  
 GTCCAGTTTC TGGGCCAGTG TTACTTCACC AACGGGACGG AGCGGGTCCG
 GGGTGTGACC AGATACATCT ACAACCGGGA GGAGTACGTG CGCTTCGACA
 GCGACGTGAA CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGTCCGCC
 GAGTACTGGA ACAGCCAGGA GGACATCCTG GAGCGGGTGC GGGCCGAGGT
 GGACACGGTG TGCAGACACA ACTACCAACT GGAGCTCATC ACA*

>DL;BoLA-DQB*0801
BoLA-DQB*0801  243 bases  
 ATCCAGTTTA AGTGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCA
 GTACGTGACC AGACACATCT ACAACCAGGA AGAGTTCATG CGCTTCGACA
 GCGAAGTGGG CGAGTACCGG GCGGTGACTC CGCTAGGGCG GCGGCAAACC
 GAGTACTTCA ACAGCCAGAA GGACGAACTG GAGCGGGTGC GGGCCGAGGC
 GGACACAGTG TGCAGACACA ACTACCAGGC GGAGCTCATT ACA*

>DL;BoLA-DQB*0802
BoLA-DQB*0802  243 bases  
 TTCCAGTTTA AGTGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCA
 GTACGTGACC AGATACATCT ACAACCAGGA AGAGTTCATG CGCTTCGACA
 GCGAAGTGGG CGAGTACCGG GCGGTGACCC CGCTAGGGCG GCGGCAAACC
 GAGTACTTCA ACAGCCAGAA GGACGAACTG GAGCGGGTGC GGGCCGAGGC
 GGACACAGTG TGCAGACACA ACTACCAGGC GGAGCTCATT ACA*

>DL;BoLA-DQB*0901
BoLA-DQB*0901  243 bases  
 GTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGAGTGCG
 GCTCGTGGTC AGACACATCT ACAACCGGGA GGAGTACGCG CGGTTTGACA
 GCGACGTGAA CGAGTACCGG GCGGTGACCC CTCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACCTCCTG GAGCAGAGGC GGGCCGAGGT
 GGACAGGGTG TGCAGACACA ACTACCAGGT GGCTGCCCCC TTC*

>DL;BoLA-DQB*0902
BoLA-DQB*0902  243 bases  
 GTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGAGTGCG
 GCTCGTGGTC GGACACATCT ACAACCGGGA GGAGTACGCG CGGTTTGACA
 GCGACGTGAA CGAGTACCGG GCGGTGACCC CTCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACCTCCTG GAGCAGAGGC GGGCCGAGGT
 GGACAGGGTG TGCAGACACA ACTACCAGGT GGCTGCCCCC TTC*

>DL;BoLA-DQB*0903
BoLA-DQB*0903  240 bases  
 GTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGAGTGCG
 GCTCGTGGTC AGACACATCT ACAACCGGGA GGAGTACGCG CGGTTTGACA
 GCGACGTGAA CGAGTACCGG GCGGTGACCT CTGGGGCGCC GCACGCCGAG
 TACTGGAACA GCCAGAAGGA CCTCCTGGAG CAGAGGCGGG CCGAGGTGGA
 CAGGGTGTGC AGACACAACT ACCAGGTGGC TGCCCCCTTC*

>DL;BoLA-DQB*1001
BoLA-DQB*1001  243 bases  
 TACCAGTTTA TGGGCCAGTG TTATTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGTACGCG CGCTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGCCGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGACGC GGGCCGAGGT
 GGACAGGGTG TGCAGAAACA ACTACCAGGT GGATGCCCCC TTC*

>DL;BoLA-DQB*10021
BoLA-DQB*10021  243 bases  
 TACCAGTTTA TGGGCCAGTG TTATTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGTACGCG CGCTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGCCGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGACGC GGGCCGAGGT
 GGACAGGGTG TGCAGAAACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*1003
BoLA-DQB*1003  243 bases  
 TACCAGTTTA TGGGCCAGTG TTATTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGTACGCG CGCTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGCCGCC
 GAGTACTGGA ACAGCCAGGA GGACATCCTG GAGCGGACGC GGGCCGAGGT
 GGACAGGGTG TGCAGAAACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*1005
BoLA-DQB*1005  243 bases  
 TTCCAGTTTA TGGGCCAGTG TTATTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGTTCGCG CGCTTCGACA
 GCGACTGGGA CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGGACGCC
 GAGCTCTGGA ACAGCCAGAA GGACATCCTG GAGCGGACGC GGGCCGAGGT
 GGACAGGGTG TGCAGAAACA ACTACCAGGT GGATGCCCCC TTC*

>DL;BoLA-DQB*1006
BoLA-DQB*1006  240 bases  
 GTCCAGTTTA TGGGCCAGTG TTATTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGTACGCG CGCTTCGACA
 GCGACTGGGG CGAGTACCGG GCGCTGACCC GCTGGCGGCC GGCCGCCGAG
 TACTGGAACA GCCAGAAGGA CATCCTGGAG CAGACGTGGG CCGAGGTGGA
 CAGGGTGTGC AGAAACAACT ACCAGGTGGA AGCCCCCTTC*

>DL;BoLA-DQB*1008
BoLA-DQB*1008  243 bases  
 TACCAGTTTA TGGGCCAGTG TTATTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGTACGCG CGCTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGCCGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GGGCGGACGC GGGCCGAGGT
 GGACAGGGTG TGCAGAAACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*1009
BoLA-DQB*1009  243 bases  
 TACCAGTTTA TGGGCCAGTG TTATTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATTCATCT ACAACCAGGA GGAGTACGCG CGCTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGCCGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGACGC GGGCCGAGGT
 GGACACGGTG TGCAGACACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*1101
BoLA-DQB*1101  243 bases  
 TTCCGGTTTA AGGGCCTGTG TTACTTCACC AACAGGACGG AGCGGGTGCG
 GTACGTGACC AGATACACCT ACAACCAGGA GGAGAACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGTCCGCC
 GAGTACTTCA ACAGCCAGGA GGACCTCCTG GAGCGGACGC GGGCCGAGGT
 GGACAGGGTG TGCAGAAACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*1201
BoLA-DQB*1201  243 bases  
 TTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GAGTGTGAAC AGATACATCT ACAACCGGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCAGGACGCC
 GAGTACTTCA ACAGCCAGAA GGACTTCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGT GGCTGCCCCC TTC*

>DL;BoLA-DQB*1301
BoLA-DQB*1301  243 bases  
 TTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GAGTGTGACC AGATACATCT ACAACCGGGA GGAGTACGTG CGGTTCGACA
 GCGACGTGAA CGAGTACCGG GCGGTGACCC CACTGGGGCG GCCGTCCGCC
 GAGTACTTCA ACAGCCAGGA GGACCTCCTG GAGCGGACGC GGGCCGAGGT
 GGACAGGGTG TGCAGACACA ACTACCAGCT GGATGCCCCC TTC*

>DL;BoLA-DQB*1302
BoLA-DQB*1302  244 bases  
 GTTCCAGTTT AAGGGCCTGT GTTACTTCAC CAACGGGACG GAGCGGGTGC
 GGTACGTGAC CAGATACATC TACAACCGGG AGGAGTACGT GCGGTTCGAC
 AGCGACGTGA ACGAGTACCG GGCGGTGACC CCACTGGGGC GGCCGTCCGC
 CGAGTACTTC AACAGCCAGG AGGACCTCCT GGAGCGGACG CGGGCCGAGG
 TGGACAGGGT GTGCAGACAC AACTACCAGC TGGATGCCCC CTTC*

>DL;BoLA-DQB*1401
BoLA-DQB*1401  270 bases  
 AGGATTTCGT GGTCCAGTTT AAGGGCCTGT GTTACTTCAC CAACGGGACG
 GAGCGGGTGC GGAGTGTGAA CAGATACATC TACAACCAGG AGGAGTACGT
 GCGGTTCGAC AGCGACTGGG ACGAGTACCG GGCGCTGACC CCGCTGGGGC
 GGCCGGACGC CGAGTACTGG AACAGCCAGA AGGACATCCT GGAGCGGACG
 CGGGCCGAGG CGGACACGGT GTGCAGAAAC AACTACCAGG TGGATGCCCC
 CTTCACCTGG CAGCGGCTAG*

>DL;BoLA-DQB*1402
BoLA-DQB*1402  243 bases  
 TACCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GAGTGTGAAC AGATACATCT ACAACCGGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*1403
BoLA-DQB*1403  243 bases  
 GTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GAGTGTGAAC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTTCA ACAGCCAGAA GGACATCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGAAACA ACTACCAGGT GGATGCCCCC TTC*

>DL;BoLA-DQB*1404
BoLA-DQB*1404  243 bases  
 GTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG ATCGGGTGCG
 GAGTGTGAAC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGACGC GGGCCGAGGC
 GGACACGGTG TGCAGAAACA ACTACCAGGT GGATGCCCCC TTC*

>DL;BoLA-DQB*1405
BoLA-DQB*1405  247 bases  
 GGCCTGTGTT ACTTCACCAA CGGGACGGAG CGGGTGCGGA GTGTGAACAG
 ATACATCTAC AACCAGGAGG AGTACGTGCG GTTCGACAGC GACTGGGACG
 AGTACCGGGC GCTGACCCCG CTGGGGCGGC CGGACGCCGA GTACTGGAAC
 AGCCAGAAGG ACATCCTGGA GCGGACGCGG GCCGAGGCGG ACACGGTGTG
 CAGAAACAAC TACCAGGTGG ATGCCCCCTT CACCTGGCAG CGGCTAG*

>DL;BoLA-DQB*1501
BoLA-DQB*1501  243 bases  
 TACCAGTTTA AGTGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGAACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACCTCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*1601
BoLA-DQB*1601  243 bases  
 TACCAGTATA AGGGCCTGTG TTACTTCACC AACGGGACGC AGCGGGTGCG
 GCTCGTGACC AGATACATCT ACAACCGGGA GGAGTACGCG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GTGGTGACCC CACTGGGGCG GCCGGCCGCC
 GAGTACTGGA ACAGCCAGAA GGACCTCCTG GAGCAGACGC GGGCCGAGGT
 GGACAGGGTG TGCAGACACA ACTACCAGGT GGCTGCCCCC TTC*

>DL;BoLA-DQB*1602
BoLA-DQB*1602  241 bases  
 ACCAGTATAA GGGCCTGTGT TACTTCACCA ACGGGACGCA GCGGGTGCGG
 CTCGTGACCA GATACATCTA CAACCGGGAG GAGTACGCGC GGTTCGACAG
 CGACTGGGAC GAGTACCGGG CGGTGACCCC ACTGGGGCGG CCGGCCGCCG
 AGTACTGGAA CAGCCAGAAG GACCTCCTGG AGCAGACGCG GGCCGAGGTG
 GACAGGGTGT GCAGACACAA CTACCAGGTG GCTGCCCCCT T*

>DL;BoLA-DQB*1701
BoLA-DQB*1701  243 bases  
 GTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GCTCGTGACC AGACACATCT ACAACCGGGA GGAGTACGCG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CACTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCAGAGGC GGGCCGAGGT
 GGACAGGGTG CGCAGACACA ACTACCAGCT GGATGCCCCC TTC*

>DL;BoLA-DQB*1702
BoLA-DQB*1702  241 bases  
 TCCAGTTTAA GGGCCTGTGT TACTTCACCA ACGGGACGGA GCGGGTGCGG
 CTCGTGACCA GACACATCTA CAACCGGGAG GAGTACGCGC GGTTCGACAG
 CGACTGGGAC GAGTACCGGG CGCTGACCCC ACTGGGGCGG CCGGACGCCG
 AGTACTGGAA CAGCCAGAAG GACATCCTGG AGCAGAGGCG GGCCGAGGTG
 GACAGGGTGT GCAGACACAA CTACCAGCTG GATGCCCCCT T*

>DL;BoLA-DQB*1801
BoLA-DQB*1801  243 bases  
 CTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GAGTGTGAAC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGCCGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*1802
BoLA-DQB*1802  243 bases  
 GTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GCACGTGACC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CTTGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*1803
BoLA-DQB*1803  241 bases  
 TCCAGTTTAA GGGCCTGTGT TACTTCACCA ACGGGACGGA GCGGGTGCGG
 TACGTGACCA GATACATCTA CAACCAGGAG GAGTACGTGC GGTTCGACAG
 CGACTGGGAC TTGTACCGGG CGCTGACCCC GCTGGGGCGG CCGGACGCCG
 AGTACTGGAA CAGCCAGAAG GACATCCTGG AGCAGACGCG GGCCGAGGCG
 GACACGGTGT GCAGACACAA CTACCAGGCG GAGCTCATCA C*

>DL;BoLA-DQB*1804
BoLA-DQB*1804  243 bases  
 TACCAGTTTA AGTGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CTTGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGTCAGAA GGACATCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*1805
BoLA-DQB*1805  243 bases  
 CTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GAGTGTGAAC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*1806
BoLA-DQB*1806  243 bases  
 TACCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGCCGCC
 GAGCTCTGGA ACAGCCAGAA GGACATCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*1807
BoLA-DQB*1807  244 bases  
 GGTCCAGTTT AAGGGCCTGT GTTACTTCAC CAACGGGACG GAGCGGGTGC
 GGTACGTGAC CAGATACATC TACAACCAGG AGGAGTACGT GCGGTTCGAC
 AGCGACTGGG ACTTGTACCG GGCGCTGACC CCGCTGGGGC GGCCGGACGC
 CGAGTACTGG AACAGCCAGA AGGACCTCCT GGAGCAGACG CGGGCCGAGG
 CGGACACGGT GTGCAGACAC AACTACCAGG CGGAGCTCAT CACA*

>DL;BoLA-DQB*1808
BoLA-DQB*1808  247 bases  
 GGTCCAGTTT AAGGGCCTGT GTTACTTCAC CAACGGGACG GAGCGGGTGC
 GGTACGTGAC CAGATACATC TACAACCAGG AGGAGTACGT GCGGTTCGAC
 AGCGACTGGG ACTTGTACCG GGCGCTGACC CCGCTGGGGC GGCCGGACGC
 CGAGTACTGG AACAGCCAGA AGGACTTCCT GGAGCAGACG CGGGCCGAGG
 CGGACACGGT GTGCAGACAC AACTACCAGG CGGAGCTCAT CACATCC*

>DL;BoLA-DQB*1809
BoLA-DQB*1809  246 bases  
 CTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGCCGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACATCC*

>DL;BoLA-DQB*1901
BoLA-DQB*1901  242 bases  
 TCCAGTTTAA GGGCCTGTGT TACTTCACCA ACGGGACGGA GCGGGTCCGG
 GGTGTGACCA GATACATCTA CAACCAGGAG GAGTACGTGC GGTTCGACAG
 CGACTGGGAC GAGTACCGGG CGCTGACCCC GCTGGGGCGG CCGGAAGCCG
 AGTACTGGAA CAGCCAGAAG GACTTCCTGG AGCAGACGCG GGCCGCGGTG
 GACACGGTGT GCAGAAACAA CTACCAGGCG GAGCTCATCA CA*

>DL;BoLA-DQB*1902
BoLA-DQB*1902  243 bases  
 GTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTCCG
 GGGTGTGACC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGACCGCC
 GAGTACTTCA ACAGCCAGAA GGACATCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*2001
BoLA-DQB*2001  243 bases  
 GTCCACTTTA TGGGCCAGTG TTACTTCACT AATGGCACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGACCGCA TACTATGACA
 GTGACGTGGG AGAGTACCGG GCTGTGACCC AACTAGGGCG GACTTTGGCT
 GAGTATTGGA ACAGCCAGAA AGATATCCTG GAGCAGACAC GGGCGGAGCT
 GGACACGGTG TGCAGACACA ATTACCAGCT GGAGGTCATC ACG*

>DL;BoLA-DQB*2101
BoLA-DQB*2101  243 bases  
 TTTCTGTTTA TGGGCCAGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GCTCGTGACC AGATACATCT ACAACCAGGA GGAGTACGTG CGCTTCGACA
 GCGACTGGGG CGAGTACCGG GCGGTGACGC CGCCGGGGCA GCGGCAAGCC
 GAGTACTTCA ACAGCCAGAA GGACTTCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGT GGAAGCCGCC TTC*

>DL;BoLA-DQB*2201
BoLA-DQB*2201  243 bases  
 ATCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTCCG
 GGGTGTGACC AGATACATCT ACAACCAGGA AGAGTTCATG CGCTTCGACA
 GCGAGGTGGG CGAGTACCGG GCGGTGACTC CGCTAGGGCG GCGGCTAACC
 GAGTACTTCA ACAGCCAGAA GGACGAACTG GAGCGGGTGC GGGCCGAGGC
 GGACACAGTG TGCAGACACA ACTACCAGGC GGAGCTCATT ACA*

>DL;BoLA-DQB*2301
BoLA-DQB*2301  243 bases  
 GTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GCTCGTGACC AGATACATAT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CGGGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTTCA ACAGCCAGAA GGACATCCTG GAGCGGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*2401
BoLA-DQB*2401  243 bases  
 CTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGA AGCGGGTGCG
 GCTCGTGACC AGACACATCT ACAACCAGGA AGAGTTCATG CGCTTCGACA
 GCGACGTGGG CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCGGCAAACC
 GAGTACTTCA ACAGCCAGAA GGACGAACTG GAGCGGGTGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*2501
BoLA-DQB*2501  243 bases  
 TACCAGTTTA AGGGCCTGTG TTATTTCACC AACGGGACGG AGCGGGTGCG
 GCTCGTGACC AGATACATAT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACGTGGG CGAACACCGG GCGGTGACCC CGCTGGGGCG GCCGGCCGCC
 GAGCACTGGA ACAGCCAGAA GGACCTCCTG GAGCAGAGGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*2502
BoLA-DQB*2502  243 bases  
 TACCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG ATAGGGTGCG
 GCTCGTGACC AGACACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACGTGGG CGAACACCGG GCGCTGACCC CGCTGGGGCG GCCGGCCGCC
 GAGTACTGGA ACAGCCAGAA GGACCTCCTG GAGCAGAGGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*2601
BoLA-DQB*2601  243 bases  
 TACCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG ATAGGGTGCG
 GCTCGTGGCC AGATACATCT ACAACCAGGA GGAGAACGTG CGGTTCGACA
 GCGACTGGGG CGAACACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCAGAGGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*2701
BoLA-DQB*2701  243 bases  
 TACCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GCACGTGACC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGGCCGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGACGC GGGCCGAGGC
 GGACACGGTG TGCAGAAACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*2702
BoLA-DQB*2702  243 bases  
 TACCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GGGCGTGACC AGACACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGCCGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGACGC GGGCCGAGGC
 GGACACGGTG TGCAGAAACA ACTACCAGGT GGAAGCCCCC TTC*

>DL;BoLA-DQB*2801
BoLA-DQB*2801  243 bases  
 TACCAGTTTA TGGGCCAGTG TTATTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCGGGA GGAGTTCGCG CGGTTCGACA
 GCGACGTGAA CGAGTTCCGG GCGGTGACCC CACTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACCTCCTG GAGGGGACGC GGGCCGAGGT
 GGACAGGGTG TGCAGACACA ACTACCAGGT GTATGCCCCC TTC*

>DL;BoLA-DQB*2901
BoLA-DQB*2901  243 bases  
 TTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GCTCGTGACC AGATACATCT ACAACCGGGA GGAGTACGCG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGCTGACCC CACTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCAGACGC GGGCCGAGGT
 GGACAGGGTG TGCAGACACA ACTACCAGGT GTATGCCCCC TTC*

>DL;BoLA-DQB*2902
BoLA-DQB*2902  244 bases  
 GGTCCAGTTT AAGGGCCTGT GTTACTTCAC CAACGGGACG CAGCGGGTGC
 GGCTCGTGAC CAGATACATC TACAACCGGG AGGAGTACGC GCGGTTCGAC
 AGCGACTGGG ACGAGTACCG GGCGCTGACC CCACTGGGGC GGCCGGACGC
 CGAGTACTGG AACAGCCAGA AGGACATCCT GGAGCAGACG CGGGCCGAGG
 TGGACAGGGT GTGCAGACAC AACTACCAGG TGTATGCCCC CTTC*

>DL;BoLA-DQB*2903
BoLA-DQB*2903  244 bases  
 GTTCCAGTTT AAGGGCCTGT GTTACTTCAC CAACGGGACG GAGCGGGTGC
 GGCTCGTGAC CAGATACATC TACAACCGGG AGGAGTACGC GCGGTTCGAC
 AGCGACTGGG ACGAGTACCG GGCGGTGACC CCACTGGGGC GGCCGACCGC
 CGAGTACTGG AACAGCCAGA AGGACATCCT GGAGCGGGTG CGGGCCGAGG
 TGGACAGGGT GTGCAGACAC AACTACCAGG TGTATGCCCC CTTC*

>DL;BoLA-DQB*3001
BoLA-DQB*3001  243 bases  
 TACCAGTTTG TAGGCCAGTG TTACTTTAAC AATGGGACAG AGCGGGTGCG
 GAGTGTGAAA AAACAGATCT ACAACCGGGC GGAGCACGTG CGATTCGACA
 GCGACGTGAA CGAGTTCCGG GCGGTTTCCC CGCTGGGGCA GCAAGACGCC
 GAGTACTTCA ACAGCCAGAA GGACATCCTG GAGCGGGCGC GGGCCGAGGT
 GGACGCGGTA TGCAGACACA ACTACCAACT GGAGCTCCGC ACA*

>DL;BoLA-DQB*3101
BoLA-DQB*3101  243 bases  
 TACCAGTATA AGGGCCTGTG TTACTTCACC AACGGGACGC AGCGGGTGCG
 GCTCGTGACC AGATACATCT ACAACCGGGA GGAGTTCGCG CGGTTCGACA
 GCGACGTGAA CGAGTTCCGG GCGGTGACCC CACTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACCTCCTG GAGGGGACGC GGGCCGAGGT
 GGACAGGGTG TGCAGATACA ACTACCAGGT GTATGCCCCC TTC*

>DL;BoLA-DQB*3201
BoLA-DQB*3201  243 bases  
 GTCCAGTTTA AGTTCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGA CTTGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGGTGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*3301
BoLA-DQB*3301  243 bases  
 TACCAGTTTA AGTGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGAACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*3302
BoLA-DQB*3302  243 bases  
 TACCAGTTTA AGTGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGAACGTG CGGTTCGACA
 GCGACTGGGA CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTTCA ACAGCCAGAA GGACTTCCTG GAGCAGACGC GGGCCGAGGC
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*3401
BoLA-DQB*3401  243 bases  
 TACCAGTTTA TGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGTACGTG CGATTCGACA
 GCGACTGGGA CGGGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCGGGTGC GGGCCGAGGT
 GGACACGGTG TGCAGAAACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*3501
BoLA-DQB*3501  243 bases  
 TACCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTCCG
 GGGTGTGACC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGG CGAACACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTTCA ACAGCCAGAA GGACTTCCTG GAGCAGACGC GGGCCGCGGT
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*3601
BoLA-DQB*3601  243 bases  
 TACCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTCCG
 GGGTGTGACC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGG CGAACACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTTCA ACAGCCAGAA GGACCTCCTG GAGCAGACGC GGGCCGCGGT
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*3602
BoLA-DQB*3602  244 bases  
 GTACCAGTTT AAGGGCCTGT GTTACTTCAC CAACGGGACG GAGCGGGTCC
 GGGGTGTGAC CAGATACATC TACAACCAGG AGGAGTACGT GCGGTTCGAC
 AGCGACGTGG GCGAACACCG GGCGCTGACC CCGCTGGGGC GGCCGGACGC
 CGAGTACTTC AACAGCCAGA AGGACCTCCT GGAGCAGACG CGGGCCGCGG
 TGGACACGGT GTGCAGACAC AACTACCAGG CGGAGCTCAT CACA*

>DL;BoLA-DQB*3701
BoLA-DQB*3701  243 bases  
 TACCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGG AGCGGGTCCG
 GGGTGTGGCC AGATACATCT ACAACCAGGA GGAGTACGTG CGGTTCGACA
 GCGACTGGGG CGAACACCGG GCGCTGACCC CGCTGGGGCG GCCGGACGCC
 GAGTACTTCA ACAGCCAGAA GGACTTCCTG GAGCAGACGC GGGCCGCGGT
 GGACACGGTG TGCAGACACA ACTACCAGGC GGAGCTCATC ACA*

>DL;BoLA-DQB*3801
BoLA-DQB*3801  243 bases  
 CTCCAGTTTA AGGGCCTGTG TTACTTCACC AACGGGACGA AGCGGGTGCG
 GCTCGTGACC AGACACATCT ACAACCAGGA AGAGTTCATG CGCTTCGACA
 GCGACGTGGG CGAGTACCGG GCGGTGACCC CGCTGGGGCG GCGGCAAACC
 GAGTACTTCA ACAGCCAGAA GGACGAACTG GAGCGGGTGC GGGCCGAGGC
 GGACACAGTG TGCAGACACA ACTACCAGGC GGAGCTCATT ACA*

>DL;BoLA-DQB*3901
BoLA-DQB*3901  266 bases  
 TTTCGTGTAC CAGTTTAAGT GCCTGTGTTA CTTCACCAAC GGGACGGAGC
 GGGTGCGGTA CGTGACCAGT TACATCTGCA GCCAGGAGGA GATCGTGCGG
 TTCGACAGCG ACTGGGACGA GTACCGGGCG GTGACCCCGC TGGGGCGGCC
 GGACGCCGAG TACTGGAACA GCCAGAAGGA CATGCTGGAG CGGGTGCGGG
 CCGAGGTGGA CAGGGTGTGC AGAAACAACT ACCAGGCGGC GCTCATCACA
 TCCTTGCAGC GGCGAG*

>DL;BoLA-DQB*4001
BoLA-DQB*4001  266 bases  
 TTTCGTGTAC CAGTTTATGG GCCAGTGTTA TTTCACCAAC GGGCTGCAGC
 GGGTGCGGTA CGTGACCAGA TACATCTACA ACCAGGAGGA GTACGCGCGC
 TTCGACAGCG ACTGGGACGA GTACCGGGCG CTGACCCCGC TGGGGCGGCC
 GGCCGCCGAG TACTGGAACA GCCAGAAGGA CATCCTGCAG CGGACGCGGG
 CCGAGGTGGA CAGGGTGTGC AGAAACAACT ACCAGGTGGA AGCCCCCTTC
 ACCTGGCAGC GGCGAG*

>DL;BoLA-DQB*4101
BoLA-DQB*4101  246 bases  
 GTCCAGTTTA TGGGCCAGTG TTATTTCACC AACGGGACGG AGCGGGTGCG
 GTACGTGACC AGATACATCT ACAACCAGGA GGAGTACGCG CGCTTCGACA
 GCGACTGGGG CGAGTACCGG GCGCTGACCC CGCTGGGGCG GCCGGCCGCC
 GAGTACTGGA ACAGCCAGAA GGACATCCTG GAGCAGACGT GGGCCGAGGT
 GGACAGGGTG TGCAGAAACA ACTACCAGGT GGAAGCCCCC TTCACC*

