>DL;Bubu-DQB*0101
Bubu-DQB*0101  771 bases  
 ATGTTTGGGA TGGTGGCTCT GCGGATCTCC AGAGGCCTTT GGACAGCAGC
 CGTGATGGTG ACCCTGGTGG TGCTGAGCAC CCCAGGGGCC GAGGGCAGAG
 ACTCTCCAGA GGATTTCGTG TACCAGTTTA TATACCAGTG TTACTTCACC
 AATGGGACAC AGCGGGTGCG GAGTGTGAAA AAACAGATCT ACAACCGGCA
 GGAGCACGTG CGATTCGACA GCGACGTGAA CGAGTTCCGG GCGGTTTCCC
 CGCTGGGGCG GCAGGACGCC GAGTACTTCA ACAGCCACGA CTTCCTGAAG
 CAGACGCGGG CCGAGGTGGA CACGGTGTGC AGACACAACT ACCAACTGGA
 GCTCCTCACA TCCTTGCAGC GGCGAGTGGA ACCTACAGTG ACCATCTCCC
 CATCCAGGAC TGAGGCTCTA AACCACCACA ACCTGCTGGT CTGCTCGGTG
 ACAGATTTCT ATCCAGGCCA GATCAAGGTT CAGTGGTTCC GGAATGACCG
 GGAGGAGACA GCTGGCGTTG TGTCCACACC TCTTATTAGA AATGGGGACT
 GGACCTTCCA GATCCTTGTA ATGTTGGAAG TGACGCCCCA GCGAGGAGAT
 GTCTACACCT GCCGCGTGGA GCACCCCAGC CTCCAGAGCC CCATCTTGGT
 GGAGTGGCGG GCACAGTCTG AATCTGCCCA GAACAAGATG CTGAGTGGTG
 TTGGGGGCTT CGTGCTGGGG CTGATCTTCC TCGGCCTGGG CCTCATCGTC
 CGTCACAGGA GCCAGAAGGG G*

