>P1;Bubu-DQA*0101
Bubu-DQA*0101  256 bases  
 MVLNRALILG ALALTTMMSP SGSEDIVADH IGAYGINVYH SYGPSGYYTH
 EFDGDEEFYV DLEKKETVWH LPLFSKFTSF DPQGALRNIA NAKYNLEIMI
 QESNSTAATN KVPEVTVFSK SPVMLDQPNT LICHVDNIFP PVISITWLRN
 GHSVIEGVSE TSFLSKDDHS FSKISYLTFL PSDDDVYDCK VEHWGLDEPL
 LKHWEPEIPA PMSELTETVV CALGLTVGLV GIVVGTVLII RGLRSGGPSR
 HQGPLX*

>P1;Bubu-DQA*0102
Bubu-DQA*0102  157 bases  
 DHIGAYGINV YHSYGPSGYY THEFDGDEEF YVDLEKKETV WHLPLFSKFA
 SFDPQGALRN IANAKYNLEF MIQESNSTAA TNKVPEVTVF SKSPVMLDQP
 NTLICHVDNI FPPVISITWL RNGHSVIEGV SETSFLSKDD HSFSKISYLT
 FLPSDDD*

>P1;Bubu-DQA*0201
Bubu-DQA*0201  157 bases  
 DHIGAYGINV YHSYGPSGYY THEFDGDEEF YVDLEKKETV WHLPLFSKFR
 SFDPQGALRN IAIVKYNLEI MIQESNSTAA TNKVPEVTVF SKSPVMLDQP
 NTLICHVDNI FPPVISITWL RNGHSVIEGV SEASFLSKDD HSFSKISYLT
 FLPSDDD*

>P1;Bubu-DQA*2001
Bubu-DQA*2001  256 bases  
 MVLNRALILG ALALTTMMSP SGGEDIVADH VGSYGTEIYQ SHGPSGQYTQ
 EFDGDEMFYV DLGKKETVWR LPMFSQFAGF DPQAALSEIA TSKHNLDVLT
 KRSNFTPVIN EVPEVTVFSK SPVMLGQPNT LICHVDNIFP PVINITWLKN
 GHSVTEGVSE TSFLSKDDHS FLKIGYLTFL PSDDDVYDCK VEHWGLDEPL
 LKHWEPEVPA PMSELTETVV CALGLTVGLV GIVVGTIFII QGLRSGGASR
 HQGPLX*

>P1;Bubu-DQA*2101
Bubu-DQA*2101  155 bases  
 DHIGSYGTEI YQSHGPPGQY TQEFDGDELF YVDLGKEVWR LPMFSQFAGF
 DPQAALSEIA KAKHNLDVLT KRSNFTPVIN EVPEVTVFSK SPMVLGQPNI
 LICHMDNIFP PVINITWLKN GHAVIEGVSE TSFLPKDDHS FLKIGSLTFL
 PSDDD*

>P1;Bubu-DQA*2201
Bubu-DQA*2201  157 bases  
 DHIGTYGINV YHTYGPSGYY THEFDGDEQF YVDLEKRETV WRLPVFSKFA
 SFDPQGALRN IATEKHNLEI MIQRSNSTAA TNKVPEVTVF SKSPVMLGQP
 NTLICHVDNI FPPVVNITWL RNGHSVIEGV SETSFLSKND FSFSKISYLT
 FLPSDDD*

>P1;Bubu-DQA*2301
Bubu-DQA*2301  157 bases  
 DHVGSYGTEI YQSHGPPDQY TQEFDGDEMF YVDLGKKETV WRLPMFSQFA
 GFDPQAALSE IATTKHNLDV LTKRSNFTPV INEVPEVTVF SKSPVMLGQP
 NTLICHVDNI FPPVINITWL KNGHSVTEGV SETSFLFKDD HSFLKIGYLT
 FLPSDDD*

>P1;Bubu-DQA*2401
Bubu-DQA*2401  157 bases  
 DHVGSYGTEI YQSHGPSGQY TQEFDGDEMF YVDLGKKETV WRLPMFSQFA
 GFDPQAALSE IATTKHNLDV LTKRSNFTPV INEVPEVTVF SKSPVMLGQP
 NTLICHVDNI FPPVINITWL KNGHSVTEGV SETSFLSKDD HSFLKIGYLT
 FLPSDDD*

