>DL;Bubu-DQA*0101
Bubu-DQA*0101  768 bases  
 ATGGTCCTGA ACAGAGCCCT GATTTTGGGG GCCCTCGCCC TCACCACCAT
 GATGAGTCCC TCTGGGAGTG AAGACATTGT GGCTGACCAC ATTGGCGCCT
 ATGGCATAAA CGTCTACCAC TCATATGGTC CCTCTGGCTA CTATACCCAT
 GAATTTGATG GAGATGAAGA GTTCTACGTG GACCTGGAAA AGAAGGAGAC
 TGTCTGGCAT CTGCCTCTGT TTAGTAAATT TACAAGTTTT GACCCTCAGG
 GTGCGCTGAG AAACATAGCT AATGCGAAAT ATAATTTGGA GATTATGATT
 CAAGAGTCCA ACTCTACTGC TGCTACCAAC AAGGTTCCTG AGGTGACTGT
 GTTTTCCAAG TCTCCCGTGA TGCTGGATCA GCCCAACACT CTCATCTGTC
 ACGTGGACAA CATCTTTCCT CCTGTGATCA GCATCACATG GCTTAGGAAT
 GGACACTCAG TGATAGAAGG TGTTTCTGAG ACCAGCTTCC TCTCCAAGGA
 TGATCATTCC TTCTCCAAGA TCAGTTACCT CACCTTCCTC CCTTCTGATG
 ATGATGTTTA TGACTGCAAA GTGGAGCACT GGGGCCTGGA TGAGCCACTG
 CTAAAACACT GGGAACCTGA GATTCCAGCC CCTATGTCAG AGCTGACAGA
 GACTGTGGTC TGTGCCCTGG GGTTGACCGT GGGCCTTGTG GGCATCGTGG
 TGGGCACCGT CCTCATCATC CGAGGTCTGC GTTCAGGTGG CCCCTCCAGA
 CACCAGGGGC CGTTGTGA*

>DL;Bubu-DQA*0102
Bubu-DQA*0102  473 bases  
 CTGACCACAT TGGCGCCTAT GGCATAAACG TCTACCACTC ATATGGTCCC
 TCTGGCTACT ATACCCATGA ATTTGATGGA GATGAAGAGT TCTACGTGGA
 CCTGGAAAAG AAGGAGACTG TCTGGCATCT GCCTCTGTTT AGTAAATTTG
 CAAGTTTTGA CCCTCAGGGT GCGCTGAGAA ACATAGCTAA TGCGAAATAT
 AATTTGGAGT TTATGATTCA AGAGTCCAAC TCTACTGCTG CTACCAACAA
 GGTTCCTGAG GTGACTGTGT TTTCCAAGTC TCCCGTGATG CTGGATCAGC
 CCAACACTCT CATCTGTCAC GTGGACAACA TCTTTCCTCC TGTGATCAGC
 ATCACATGGC TTAGGAATGG ACACTCAGTG ATAGAAGGTG TTTCTGAGAC
 CAGCTTCCTC TCCAAGGATG ATCATTCCTT CTCCAAGATC AGTTACCTCA
 CCTTCCTCCC TTCTGATGAT GAC*

>DL;Bubu-DQA*0201
Bubu-DQA*0201  473 bases  
 CTGACCACAT TGGCGCCTAT GGCATAAACG TCTACCACTC ATATGGTCCC
 TCTGGCTACT ATACCCATGA ATTTGATGGA GATGAAGAGT TCTACGTGGA
 CCTGGAAAAG AAGGAGACTG TCTGGCATCT GCCTCTGTTT AGTAAATTTA
 GAAGTTTTGA CCCTCAGGGT GCGCTGAGAA ACATAGCTAT TGTGAAATAT
 AATTTGGAGA TTATGATTCA AGAGTCCAAC TCTACTGCTG CTACCAACAA
 GGTTCCTGAG GTGACTGTGT TTTCCAAGTC TCCCGTGATG CTGGATCAGC
 CCAACACTCT CATCTGTCAC GTGGACAACA TCTTTCCTCC TGTGATCAGC
 ATCACATGGC TTAGGAATGG ACACTCAGTG ATAGAAGGTG TTTCTGAGGC
 CAGCTTCCTC TCCAAGGATG ATCATTCCTT CTCCAAGATC AGTTACCTCA
 CCTTCCTCCC TTCTGATGAT GAC*

>DL;Bubu-DQA*2001
Bubu-DQA*2001  768 bases  
 ATGGTCCTGA ACAGAGCTCT GATTCTGGGG GCCCTCGCCC TGACCACCAT
 GATGAGCCCC AGTGGAGGTG AAGACATTGT GGCTGACCAC GTTGGCTCCT
 ATGGCACAGA GATCTACCAA TCTCATGGTC CCTCTGGCCA GTACACCCAG
 GAATTTGATG GAGACGAGAT GTTTTATGTG GACCTGGGGA AGAAGGAGAC
 TGTCTGGAGG CTGCCTATGT TTAGCCAGTT TGCAGGTTTT GACCCACAGG
 CTGCACTGAG TGAAATAGCT ACATCAAAAC ACAATTTGGA TGTCCTGACT
 AAACGCTCCA ACTTTACCCC TGTTATTAAT GAGGTTCCTG AGGTGACTGT
 GTTTTCCAAG TCTCCCGTGA TGCTGGGTCA GCCCAACACC CTCATCTGTC
 ACGTGGACAA CATTTTTCCC CCTGTGATCA ACATTACATG GCTGAAGAAT
 GGGCATTCAG TCACAGAAGG TGTTTCTGAG ACCAGCTTCC TCTCTAAGGA
 TGATCATTCC TTCCTCAAGA TTGGTTATCT CACCTTCCTC CCTTCTGATG
 ATGACGTTTA TGACTGCAAA GTGGAGCACT GGGGCCTGGA TGAGCCACTG
 CTCAAACACT GGGAGCCTGA GGTTCCAGCC CCTATGTCAG AGCTGACAGA
 GACTGTGGTC TGTGCCCTGG GGTTGACCGT GGGCCTCGTG GGCATCGTGG
 TGGGCACCAT CTTCATCATC CAAGGCCTGC GCTCAGGTGG GGCCTCCAGA
 CACCAGGGTC CCTTGTGA*

>DL;Bubu-DQA*2101
Bubu-DQA*2101  470 bases  
 CTGACCACAT TGGCTCCTAT GGCACAGAGA TCTACCAATC TCATGGTCCC
 CCTGGCCAGT ACACCCAGGA ATTTGATGGA GATGAGCTGT TTTATGTGGA
 CCTGGGGAAG GAGACTGTCT GGAGGCTGCC TATGTTTAGC CAGTTTGCAG
 GTTTTGACCC ACAGGCTGCA CTGAGTGAAA TAGCTAAAGC AAAACACAAC
 TTGGATGTCC TGACTAAACG CTCCAACTTT ACCCCTGTTA TCAATGAGGT
 TCCTGAGGTG ACTGTGTTTT CCAAGTCTCC CATGGTGCTA GGTCAGCCCA
 ATATTCTCAT CTGTCACATG GACAACATTT TTCCCCCTGT GATCAACATT
 ACATGGCTGA AGAATGGACA TGCAGTCATA GAGGGTGTTT CTGAGACCAG
 CTTCCTCCCT AAGGATGATC ATTCCTTCCT CAAGATTGGT TCTCTCACCT
 TCCTCCCTTC TGATGATGAC*

>DL;Bubu-DQA*2201
Bubu-DQA*2201  473 bases  
 CTGACCACAT TGGCACCTAT GGCATAAACG TCTACCACAC ATATGGTCCC
 TCTGGCTACT ATACCCATGA ATTTGATGGA GATGAACAGT TCTACGTGGA
 CCTGGAAAAG AGGGAGACTG TCTGGCGTCT GCCTGTGTTT AGTAAATTTG
 CAAGTTTTGA CCCTCAGGGT GCGCTGAGAA ACATAGCTAC AGAGAAACAC
 AATTTGGAGA TCATGATTCA AAGGTCCAAC TCTACTGCTG CTACCAACAA
 GGTTCCTGAG GTGACTGTGT TTTCCAAGTC TCCTGTGATG CTGGGTCAGC
 CCAACACCCT CATCTGTCAC GTGGACAACA TCTTTCCTCC TGTGGTCAAC
 ATTACATGGC TGAGGAACGG GCACTCGGTC ATAGAGGGTG TTTCTGAGAC
 CAGCTTCCTC TCCAAGAATG ATTTTTCCTT CTCCAAGATC AGTTACCTCA
 CCTTCCTCCC TTCTGATGAT GAC*

>DL;Bubu-DQA*2301
Bubu-DQA*2301  473 bases  
 CTGACCACGT TGGCTCCTAT GGCACAGAGA TCTACCAATC TCATGGTCCC
 CCTGACCAGT ACACCCAGGA ATTTGATGGA GACGAGATGT TTTATGTGGA
 CCTGGGGAAG AAGGAGACTG TCTGGAGGCT GCCTATGTTT AGCCAGTTTG
 CAGGTTTTGA CCCACAGGCT GCACTGAGTG AAATAGCTAC AACAAAACAC
 AATTTGGATG TCCTGACTAA ACGCTCCAAC TTTACCCCTG TTATTAATGA
 GGTTCCTGAG GTGACTGTGT TTTCCAAGTC TCCCGTGATG CTGGGTCAGC
 CCAACACCCT CATCTGTCAC GTGGACAACA TTTTTCCCCC TGTGATCAAC
 ATTACATGGC TGAAGAATGG GCATTCAGTC ACAGAAGGTG TTTCTGAGAC
 CAGCTTCCTC TTTAAGGATG ATCATTCCTT CCTCAAGATT GGTTATCTCA
 CCTTCCTCCC TTCTGATGAT GAC*

>DL;Bubu-DQA*2401
Bubu-DQA*2401  473 bases  
 CTGACCACGT TGGCTCCTAT GGCACAGAGA TCTACCAATC TCATGGTCCC
 TCTGGCCAGT ACACCCAGGA ATTTGATGGA GACGAGATGT TTTATGTGGA
 CCTGGGGAAG AAGGAGACTG TCTGGAGGCT GCCTATGTTT AGCCAGTTTG
 CAGGTTTTGA CCCACAGGCT GCACTGAGTG AAATAGCTAC AACAAAACAC
 AATTTGGATG TCCTGACTAA ACGCTCCAAC TTTACCCCTG TTATTAATGA
 GGTTCCTGAG GTGACTGTGT TTTCCAAGTC TCCCGTGATG CTGGGTCAGC
 CCAACACCCT CATCTGTCAC GTGGACAACA TTTTTCCCCC TGTGATCAAC
 ATTACATGGC TGAAGAATGG GCATTCAGTC ACAGAAGGCG TTTCTGAGAC
 CAGCTTCCTC TCTAAGGATG ATCATTCCTT CCTCAAGATT GGTTATCTCA
 CCTTCCTCCC TTCTGATGAT GAC*

